### ISSUE TITLE
Beats can't to write to older versions of ES than 6.2 due to _doc

### ISSUE THREAD

**Issue by henrikno** [elastic/beats#10012]
I tried to point filebeat master at a 5.6.14 ES cluster and it fails with:

`{"type":"invalid_type_name_exception","reason":"Document mapping type name can't start with '_', f
ound: [_doc]"}`

It will be the same for ES <6.2 since support for `_doc` was added to 6.2: https://github.com/elastic/elasticsearch/pull/27816

According to the PR switching to _doc it should only do so for ES 7.0 https://github.com/elastic/beats/pull/9056
But it looks like it's hard coded:
https://github.com/elastic/beats/blob/41f87a4681d3dec1654728372955447a0757ddff/libbeat/outputs/codec/json/event.go#L49
Shouldn't this use eventType?
https://github.com/elastic/beats/blob/41f87a4681d3dec1654728372955447a0757ddff/libbeat/outputs/elasticsearch/client.go#L693-L697

**Comment by urso** [comment]
This should work now with recent master.

**Comment by ph** [comment]
This should be fixed in latest releases.
