### ISSUE TITLE
Document docker "Default" from test suite

### ISSUE THREAD

**Issue by kkirsche** [elastic/beats#1002]
Document how to create an image of the "default" docker image for use with the test suite.

**Comment by ruflin** [comment]
@kkirsche Can you add some more details to this issue? Not 100% sure I understand it.

**Comment by kkirsche** [comment]
So when running the `make testsuite` command to run the test suite on Mac for example, the rest suite attempts to open a docker machine called default yet it's not documented how to make this machine, and as such the tests don't run.

**Comment by ruflin** [comment]
@kkirsche Got it. 

Do you need any help in the meantime until we have it in the docs?

**Comment by kkirsche** [comment]
If you have any information on how to set that up, that'd be great. I wasn't sure where to begin with that part of it but was hoping I could get it working before my flight tonight so I wouldn't have to hit Travis with failing builds due to simple reasons like a variable name being changed everywhere except one line. Not a huge problem though, just want to be more considerate of when a PR gets pushed to your team

**Comment by ruflin** [comment]
Assuming you have docker, docker-compose and docker-machine installed, run the following command:

```
docker-machine create --driver=virtualbox --virtualbox-memory "2048" default
```

Be aware that the first time you will run make testsuite it will download and generate all the images which takes quite a bit of time. But that is only done once, from then on it should be fast.

**Comment by eherot** [comment]
This issue may be obsolete at this point because the new Docker.app (at least on the mac) creates that machine by default.

**Comment by dedemorton** [comment]
@ruflin Can we close this one?

**Comment by ruflin** [comment]
Yes
