### ISSUE TITLE
[CM] Add timestamp to backup file

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#10031]
Consider the following scenario:

1. User enrolls a filebeat instance. The user's `filebeat.yml` gets backed up as `filebeat.yml.bak`.
2. User un-enrolls the instance.
3. User makes changes to their `filebeat.yml`.
4. User re-enrolls the instance. The user's `filebeat.yml` gets backed up as `filebeat.yml.bak`, overwriting their previous `filebeat.yml.bak`.

If the user wants to peruse the contents of their original `filebeat.yml`, they cannot do that any more.

Perhaps we should add a timestamp portion somewhere in the `.bak` filename?

**Comment by ph** [comment]
I will add this, I think that will help since we are still in the beta state.
