### ISSUE TITLE
Improve error message when running setup against Kibana with prefix

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#10045]
When running `metricbeat --setup` against a Kibana instance running under `/foo` prefix path, it returns the following error:

```
Exiting: Error importing Kibana dashboards: fail to create the Kibana loader: Error creating Kibana client: Error creating Kibana client: fail to get the Kibana version: HTTP GET request to /api/status fails: parsing kibana response: invalid character '<' looking for beginning of value. Response: <!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><meta name="viewport" content="width=device-width"><title>Kibana</title><style>@font-face {   font-family: 'Open Sans';   font-st... (truncated).
```

The reason is that it can't find the version information under the default path. Instead of outputting the above a better error should be returned that Kibana / status information could not be found under the default path.

**Comment by jailbreakerSN** [comment]
Hello!
Did you finaly find the solution? if yes, can you share it with us, I have the same issue!

**Comment by opoplawski** [comment]
FWIW - you get the same error when kibana requires authentication and the beat configuration does not provide it.
