### ISSUE TITLE
Packetbeat 1.1.1 - Thrift request/response correlation issue

### ISSUE THREAD

**Issue by zhangbo1** [elastic/beats#1005]
2016/02/19 09:18:16.178253 thrift.go:1014: DBG  Response from another request received 'userService:sendResetTradePasswordSMS' 'sendResetTradePasswordSMS'. Ignoring.

@andrewkroh

**Comment by tsg** [comment]
We need more details to figure this out. Best would be to record a short trace and send it to one of us. See here on how to do that: https://www.elastic.co/guide/en/beats/packetbeat/current/_recording_a_trace.html

**Comment by zhangbo1** [comment]
@tsg  trace.pcap file Has been sent to your mail

**Comment by faec** [comment]
This hasn't been updated since version 1, so I'm closing this issue -- we can reopen it if anyone observes it in a current version.
