### ISSUE TITLE
Filebeat not closing deleted files

### ISSUE THREAD

**Issue by saltsa** [elastic/beats#1006]
Filebeat doesn't close deleted files by default. This can cause huge disk space consumption when deleting large logfiles.

IMHO expected behaviour should be that when the file is deleted, it's closed by the filebeat.

Steps to reproduce:
1. Configure filebeat to gather log file, for e.g. /var/log/messages and start the filebeat
2. Make sure file is open: lsof -n | grep filebeat.*log/messages
3. Remove the file: rm /var/log/messages and optionally create the new file: touch /var/log/messages
4. Expect the file to be closed.

Current behaviour in version 1.1.1:

```
# lsof -n|grep log/messages
filebeat   1457           root   10r      REG              253,1         0    3018424 /var/log/messages
filebeat   1457           root   17r      REG              253,1  72458645    3428011 /var/log/messages (deleted)
filebeat   1457  1458     root   10r      REG              253,1         0    3018424 /var/log/messages
filebeat   1457  1458     root   17r      REG              253,1  72458645    3428011 /var/log/messages (deleted)
filebeat   1457  1459     root   10r      REG              253,1         0    3018424 /var/log/messages
filebeat   1457  1459     root   17r      REG              253,1  72458645    3428011 /var/log/messages (deleted)
filebeat   1457  1460     root   10r      REG              253,1         0    3018424 /var/log/messages
filebeat   1457  1460     root   17r      REG              253,1  72458645    3428011 /var/log/messages (deleted)
filebeat   1457  1461     root   10r      REG              253,1         0    3018424 /var/log/messages
filebeat   1457  1461     root   17r      REG              253,1  72458645    3428011 /var/log/messages (deleted)
filebeat   1457  1462     root   10r      REG              253,1         0    3018424 /var/log/messages
filebeat   1457  1462     root   17r      REG              253,1  72458645    3428011 /var/log/messages (deleted)
filebeat   1457  1463     root   10r      REG              253,1         0    3018424 /var/log/messages
filebeat   1457  1463     root   17r      REG              253,1  72458645    3428011 /var/log/messages (deleted)
filebeat   1457  1464     root   10r      REG              253,1         0    3018424 /var/log/messages
filebeat   1457  1464     root   17r      REG              253,1  72458645    3428011 /var/log/messages (deleted)
filebeat   1457  1465     root   10r      REG              253,1         0    3018424 /var/log/messages
filebeat   1457  1465     root   17r      REG              253,1  72458645    3428011 /var/log/messages (deleted)
```

**Comment by saltsa** [comment]
Ok, after reading the source code it seems that the files is closed, by default, after 24h. Should this be shorter time period? I think it's almost always a failure if deleted files get written.

**Comment by ruflin** [comment]
The time period is configurable. As ignore_older has some side affects we introduce close_older in the next major release (already part of master): https://github.com/elastic/beats/pull/958

About deleted files: It is hard to differentiate between a file that was completely deleted or only rotated (means it will show a bit later again). If you always want to close it if a file disappears, use the `force_close_files` option which does exactly that: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#_force_close_files

**Comment by tsg** [comment]
Closing as question. Feel free to reopen if you feel there's a bug.
