### ISSUE TITLE
Rename kibana directory version or not

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#10069]
In Beats we have for the Kibana files the following directory structure:  `_meta/kibana/6/...`. We have the version number in the path for Kibana compatibility as we had 5 and 6 dashboards. For 7 we change a lot of dashboards as they are only compatible with 7.x data (https://github.com/elastic/beats/pull/9998). But the dashboards itself are still compatible with Kibana 6. I'm now wondering if we should rename the directory to 7 or not as initially this described the Kibana and not Beats compatiblity.

On the other hand Kibana 7 potentially gets a new storage format and we will migrate to it at one stage. Like this we already have a 7 directory for it. Also in general it is recommended that Kibana is newer then the Beats version, so Beats 7 should only be used with 7 or newer.

@urso @andrewkroh @exekias @jsoriano Would be great to get your thoughts on this one. I think it's also a change we could do at a later stage as it's not necessarily breaking.

**Comment by jsoriano** [comment]
If Beats 7.0 needs to be compatible with 6.7 versions of the stack (as Beats 6.0 is compatible with 5.6), and there is a new storage format in Kibana 7, then I guess we need 2 directories, even if we later remove the old one in Beats 7.X (X>0).

If Beats 7 doesn't need to be compatible with any version of Kibana/ES 6 then we can have a single directory.

**Comment by exekias** [comment]
I'm +1 on keeping compatibility of Beats 7.0 running against ES+Kibana 6.X, that should ease the upgrade.

So keeping a `6` dir as long as it doesn't take too much time makes sense to me. All new dashboards would be 7 only

**Comment by ruflin** [comment]
To clarify: For now we don't change the format and Kibana does the conversion for us. We could move to a 7 directory and still allow to load against 6.x (for now). Main issue is if we remove the directory or this support in the 7.x cycle, I would say this is a breaking change?
