### ISSUE TITLE
outputs/kafka breaks with latest go-metrics

### ISSUE THREAD

**Issue by 7AC** [elastic/beats#10096]
Looks like `rcrowley/go-metrics` added a `GetAll()` method in https://github.com/rcrowley/go-metrics/commit/6eef1fc14e6f6020c8e1faba7cfe5558c4771955, as a result vendoring the latest `libbeat` is broken:

```
21:32:05 go build -ldflags "-s -w -X github.com/aristanetworks/openconfigbeat/cmd.Version=0.0.2-2-g07ce46b"
21:32:31 # github.com/aristanetworks/openconfigbeat/vendor/github.com/elastic/beats/libbeat/outputs/kafka
21:32:31 vendor/github.com/elastic/beats/libbeat/outputs/kafka/config.go:213:19: cannot use adapter.GetGoMetrics(monitoring.Default, "libbeat.outputs.kafka", adapter.Rename("incoming-byte-rate", "bytes_read"), adapter.Rename("outgoing-byte-rate", "bytes_write"), adapter.GoMetricsNilify) (type *adapter.GoMetricsRegistry) as type metrics.Registry in assignment:
21:32:31 	*adapter.GoMetricsRegistry does not implement metrics.Registry (missing GetAll method)
21:32:31 make: *** [vendor/github.com/elastic/beats/libbeat/scripts/Makefile:100: openconfigbeat] Error 2
```

**Comment by ruflin** [comment]
I assume you vendored your own version here and the one we have in libbeat works?

@7AC Glad to see your still active around beats ;-)

**Comment by 7AC** [comment]
Good to hear from you @ruflin :) The context is I need to update the dependencies in `aristanetworks/openconfigbeat`. I was using `glide` but decided to switch to `dep` instead (can't switch to Go modules until go1.12 due to https://github.com/golang/protobuf/issues/751). I could pin the version of `go-metrics` but it feels wrong to do it downstream from libbeat so I figured you might just want to add the method? Definitely let me know if there's a better recommended way to vendor dependencies in beats.

**Comment by ruflin** [comment]
We are still using govendor (https://github.com/kardianos/govendor) for managing the vendor directories. For some tricks on how to best vendor Beats dependencies have a look at apm-server here: https://github.com/elastic/apm-server/tree/master/_beats

Updating go-metrics on our end and adding the method should also work. I don't think it's a bad idea to get the newer version. Want to open a PR?

**Comment by sentient** [comment]
This worked for me

Gopkg.toml

[[constraint]]
  name = "github.com/elastic/beats"
  version = "6.5.4"

[[constraint]]
  name = "github.com/rcrowley/go-metrics"
  revision = "1f30fe9094a513ce4c700b9a54458bbb0c96996c"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.20.1"

**Comment by 7AC** [comment]
Thanks I know that works that's why I mentioned "I could pin the version of go-metrics but it feels wrong" 😄 I've been meaning to post a PR but didn't get the time yet.
