### ISSUE TITLE
[Packetbeat] MongoDB causes high memory usage

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#10108]
Customer reports high memory usage in Packetbeat, with peaks of ~6GB per process.

Only beat with mongodb enabled shows this problem, and it disappears once the mongodb protocol decoder is disabled.

For confirmed bugs, please report:
- Version: 6.4.3
- Operating System:  Linux

**Comment by willemdh** [comment]
This issue has never been solved or analysed and should not have been auto closed imho. See also https://discuss.elastic.co/t/my-packetbeat-memory-is-growing-continuously/258221/4 and https://github.com/elastic/beats/issues/20755
