### ISSUE TITLE
[Beats CM] Saying no to enrollment still enrolls but config is not overwritten 

### ISSUE THREAD

**Issue by liza-mae** [elastic/beats#10150]
Version: 6.6.0 BC6
Operating System: Ubuntu 16.04 
Steps to Reproduce: 
1. Install ES, Kibana, Filebeat
2. In Kibana go Beats CM and enroll beat filebeat 
3. In terminal, enroll filebeat, but hit 'N' I would have expected it to cancel out the enrollment, but looks like it still enrolls and does not overwrite the config.  Is this intended to work that way?   Seems it should cancel the enrollment too. 

./filebeat enroll URL TOKEN 
This will replace your current settings. Do you want to continue? [Y/n]:n
Enrolled and ready to retrieve settings from Kibana

**Comment by ph** [comment]
Taking a look at this, we definitively should not override the config.

**Comment by ph** [comment]
I have a fix for that, It was a problem with the logic, first the token was right away enrolled and the confirm method did not return the right thing.

I have fixed the code, will do a bit more testing and see if there is any more edge cases.

**Comment by liza-mae** [comment]
Thanks @ph !
