### ISSUE TITLE
common.Backoff doesn't have any form of jitter.

### ISSUE THREAD

**Issue by ph** [elastic/beats#10172]
The current implementation of the [common.Backoff](https://github.com/elastic/beats/blob/master/libbeat/common/backoff.go) only sleep for a period of time, since an error can affect multiple beats at the same time and multiple retries can greatly affect the performance remote endpoints or even kill them in some circumstances it is necessary to add some jitter in the backoff strategy to help distribute the requests.

**Comment by mickelastic** [comment]
Relates to elastic/cloud/issues/25895
