### ISSUE TITLE
Create a readme to test the KVM module

### ISSUE THREAD

**Issue by alvarolobato** [elastic/beats#10217]
Should contain instructions on how to setup the environment.

**Comment by ruflin** [comment]
@jsoriano As part of writing this readme and setting up KVM, could you also update the data.json file? https://github.com/elastic/beats/blob/master/metricbeat/module/kvm/dommemstat/_meta/data.json

**Comment by ruflin** [comment]
@amandahla If you find some time to update the `data.json` that would also be great.

**Comment by amandahla** [comment]
Hi @ruflin , do you want me to open a PR for this? The updated file is [here](https://github.com/estaleiro/beats/blob/5bd3108fdde95c8ddce227d9dcd155b6f3327ce3/metricbeat/module/kvm/dommemstat/_meta/data.json)

**Comment by amandahla** [comment]
Hi @alvarolobato , I'm not sure if this is what you want for the README file but I followed [these instructions](https://www.howtogeek.com/117635/how-to-install-kvm-and-create-virtual-machines-on-ubuntu/) to create a minimum KVM environment to build this module.

Then in the metricbeat.yml:
```
- module: kvm
  metricsets: ["dommemstat"]
  enabled: true
  period: 5s
  hosts: ["unix:///var/run/libvirt/libvirt-sock"]
```

**Comment by ruflin** [comment]
@amandahla Would be great if you could open a PR with the updated data.json.

@jsoriano In case you need in some inspiration for the Readme: https://www.howtogeek.com/117635/how-to-install-kvm-and-create-virtual-machines-on-ubuntu/

@amandahla The goal on our end is to make this module GA but for this to happen, we must have a reliable and reproducible way to setup an environment on our end to debug potential support issues. In most modules we have a Dockerfile for this but this is not really feasible for kvm.

**Comment by jsoriano** [comment]
I [started](https://github.com/elastic/beats/compare/master...jsoriano:metricbeat-kvm-testing?expand=1) to try to script some test with our test framework using docker, this test will need linux and kvm for good, but maybe we can make libvirtd work also with software emulation if kvm is not available.
My main problem now is to create a minimal base image.
I will try to continue next week.
