### ISSUE TITLE
Heartbeat Logging Improvements

### ISSUE THREAD

**Issue by Alsheh** [elastic/beats#10231]
### Issue#1
When using `heartbeat.config.monitors` to load monitors from files in a directory and one of the files has an invalid config, I get the following log:
```
heartbeat    | 2019-01-21T19:38:10.306Z	ERROR	cfgfile/reload.go:223	Error loading config: invalid config: yaml: line 17: mapping values are not allowed in this context
```
This log doesn't tell me which file has the invalid config; it can be very hard to locate the problematic file when there're many files in the `heartbeat.config.monitors.path` especially when the files are generated by script.
### Solution:
Include the absolute path of the config file in the log.
### Bonus:
In addition to reporting the absolute path of the config file, include a unique identifier for the specific monitor causing the issue in the event there are multiple monitors defined in a config file.

----
### Issue#2
When a Heartbeat monitor is disabled, the following log is constantly being emitted:
```
heartbeat    | 2019-01-21T21:18:54.984Z	ERROR	[reload]	cfgfile/list.go:96	Error creating runner from config: Monitor not loaded, plugin is disabled
```
Three problems with this issue:
1. This log should have an `INFO` log-level not an `ERROR` log-level since enabling and disabling a monitor are most likely done intentionally in the config file.
2. The fact that this log is emitted constantly is not necessary and can hide some other important logs and it would be better to log it just once as an `INFO` log-level.
3. Same as issue#1, config file path is missing especially in the event when multiple config files are used.

**Comment by benberg86** [comment]
Believe I am hitting the enabled: false issue. Attempting to use a docker container and have some of the monitors defined with enabled: false using variables but the container dies after the error logged for the disabled monitor. This is preventing from being able to deploy some monitors disabled per environment. Any workaround for this? Documentation describes using the enabled field to be able to do this sort of thing.

**Comment by andrewvc** [comment]
@benberg86 this seems to be a bug (and we seem to have missed the original complaint). I've opened https://github.com/elastic/beats/issues/22665 to track this more directly. We probably won't be able to get to it for a few weeks, but a patch would be appreciated!

**Comment by benberg86** [comment]
Thanks @andrewvc - signed the contributor agreement, etc. Think I have a working fix or at least a PR to start a discussion 😜

**Comment by andrewvc** [comment]
@benberg86 as a heads up I just merged a fix for the `enabled: false` issue here: https://github.com/elastic/beats/pull/22829 . As for the YAML filename issue we'd still gladly accept a patch to enhance that, but it's not something we're likely to prioritize. Instead, we're focusing on agent support as the primary way to configure things for heartbeat. While heartbeat is not yet supported here, it's something we're working on. See https://www.elastic.co/guide/en/kibana/7.x/fleet.html
