### ISSUE TITLE
Logger from the standard library is not correctly disabled.

### ISSUE THREAD

**Issue by ph** [elastic/beats#10251]
I've seen a report where a keep alive TCP connection received some garbage from the remote end, since we didn't have anything configured to handle that request the http client did just log the error directly using the default logger. Since beats was running as a service the log went to stdout/stderr and was dump to the `/var/log/message`, This is indeed an unexpected behavior.

The following code is not exactly what it need to be. We have to setup `ioutil.Discard` when the catch all selector `*` is not set or `stdlog` is not set. When either of the selector is defined we need to use our logger output.

https://github.com/elastic/beats/blob/4cb9bd7e75b3eb1ce8f3e8ea3a115dc34674fa16/libbeat/logp/core.go#L101-L105

**Comment by urso** [comment]
@ph Any idea if the problem still exists?

**Comment by ph** [comment]
double checked the code, this  is still an issue but a good first issue.
