### ISSUE TITLE
fields_under_root: true missing in docs for configurations to be equivalent

### ISSUE THREAD

**Issue by dblazeka** [elastic/beats#1025]
In file beats/filebeat/docs/migration.asciidoc, multiple Logstash Forwarder and Filebeat configurations are said to be equivalent although the Filebeat prospector configuration misses 
`fields_under_root: true`
for that to be true. I am aware that there is a chapter **Custom Fields are Grouped Under a "fields" Dictionary** which describes the differences between the two but that does not make the configurations equivalent.

**Comment by ruflin** [comment]
Good point. We should add this to the config. 

We are talkinga bout this page here: https://www.elastic.co/guide/en/beats/filebeat/current/_migrating_your_configuration.html

@dedemorton FYI

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/beats/pull/1697 was merged.
