### ISSUE TITLE
Web Service module in Metricbeat

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#1027]
Similar to https://github.com/elastic/beats/issues/619, it can be useful to have a beat similar to the metrics beat, but support custom web services as the source.

**Comment by ruflin** [comment]
Beats are in general target to run as close to the source as possible, means normally on the host machine. I assume you are talking here about remote web services like Google API, Twitter or others to receive a status. I'm not sure if Logstash Plugins are actually better target for such use cases.

**Comment by ppf2** [comment]
Also for the case where there are custom web services returning metrics running internally on web servers.

**Comment by ruflin** [comment]
Monitoring your own web services is definitively an interesting use case. As the data fetched and the structure of the data is very app specific, it sounds like a good use case to use metricbeat as a library and to implement its own module / metricset on top of it. This is normally only a few lines of code.

**Comment by ruflin** [comment]
Closing this as I think the `http` module we have now covers this use case.
