### ISSUE TITLE
Create Kibana index patterns on the fly instead of shipping with package

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#10291]
Currently Kibana index patterns are shipped inside the package of each Beat. With the introduction of migration aliases we need two different index patterns depending on if the config `migration.enabled` is true or false. In the case of false the migration aliases should not be part of the index pattern.

To make this possible, index patterns must be generated and loaded when running the Beat instead of using the pre generated one.

This issue is to set the foundation for this. As soon as this feature exist, this follow up PR (https://github.com/elastic/beats/pull/10204) can be rebased and make use of it.

**Comment by exekias** [comment]
ey @ruflin what's the status of this?

**Comment by ruflin** [comment]
This was implemented in https://github.com/elastic/beats/pull/10478. Closing.
