### ISSUE TITLE
Filebeat log support for OpenShift/Kubernetes

### ISSUE THREAD

**Issue by jstrassb** [elastic/beats#10292]
**Describe the enhancement:**

It would be nice if Filebeat supported a way for collecting logs in an OpenShift/Kubernetes environment by supporting a collection of the logstreams for all those pods (within its own namespace) via the Kubernetes api-server, e.g. https://{api-server}/api/v1/namespaces/{namespace}/pods/log?follow&timeStamps by using the kubernetes rest api (https://docs.openshift.com/container-platform/3.6/rest_api/kubernetes_v1.html#read-log-of-the-specified-pod).

**Describe a specific use case for the enhancement or feature:**

This functionality would be helpful in restricted environments where daemonsets  (where Filebeat can easily pick up container logs locally on the Kubernetes nodes) are not allowed by policy.

**Comment by beckjim** [comment]
+1 
Would solve container/pod log collection problems in case you're not a cluster admin.

**Comment by Feder1co5oave** [comment]
I'm not sure this would be a scalable solution. In case of very verbose logging containers, all logs passing through the API server doesn't sound like a good idea!
