### ISSUE TITLE
Improve look of generate_docs.py script

### ISSUE THREAD

**Issue by sayden** [elastic/beats#10316]
Comments left for a followup PR from here https://github.com/elastic/beats/pull/10232

- https://github.com/elastic/beats/pull/10232#discussion_r250544312 Use `os.path.join` for joining paths here https://github.com/elastic/beats/blob/master/metricbeat/scripts/docs_collector.py#L26
- https://github.com/elastic/beats/pull/10232#discussion_r250544857 The code to generate modules_path is twice here and only depends on X_base_dir (and X_path but can be obtained from the other one). Extract it to a function? https://github.com/elastic/beats/blob/master/metricbeat/scripts/docs_collector.py#L39
- https://github.com/elastic/beats/pull/10232#discussion_r250545807 Named tuples are pretty handy in these cases, specially when fields of these objects are accessed so many times. https://github.com/elastic/beats/blob/master/metricbeat/scripts/docs_collector.py#L37
- https://github.com/elastic/beats/pull/10232#discussion_r250547547 it appears as experimental but the module is beta, in any case I guess this is not related to this PR https://github.com/elastic/beats/blob/master/metricbeat/docs/modules/aws/ec2.asciidoc
- ~~https://github.com/elastic/beats/pull/10232#discussion_r250547928 these metricsets are experimental but the module is beta, is it expected? https://github.com/elastic/beats/blob/master/metricbeat/docs/modules/mssql/performance.asciidoc~~
- https://github.com/elastic/beats/pull/10232#discussion_r250553212 `modules_list[module['name']]` referenced lots of times, it could be created as a single object and assigned to the dict when finished. https://github.com/elastic/beats/blob/master/metricbeat/scripts/docs_collector.py#L169

**Comment by ruflin** [comment]
@palash25 Go for it. Best open a PR with the changes early so we can start discussing.
