### ISSUE TITLE
Xpack modules are missing in the snapshot distribution files

### ISSUE THREAD

**Issue by sayden** [elastic/beats#10314]
I was checking the contents of the Metricbeat distribution files we have now and expecting to find the xpack modules within this distribution file https://storage.cloud.google.com/beats-ci-artifacts/snapshots/metricbeat/metricbeat-7.0.0-SNAPSHOT-linux-x86_64.tar.gz 

I think that's is the file that it's being generated by running `make snapshot` from `beats` or `metricbeat` (OSS) folder and that you can find in `metricbeat/build/distributions`. Unfortunately no conf files of Xpack  were found in `modules.d` from the extracted content.

As far as I can see:
- `mage package` from `xpack/metricbeat` folder generates files in `xpack/metricbeat/build/distribution` with both OSS and XPack modules and Elastic License.
- `make snapshot` from `metricbeat` folder generates files in `metricbeat/build/distribution` with only OSS modules. Also you can find here 2 types of distributions: one with Elastic license and one with AS2L.

What I'm lacking is to see the files that are generated in `mage package` on the generated artifacts (for example here https://beats-ci.elastic.co/job/elastic+beats+master+multijob-package-linux/269/gcsObjects/)

@andrewkroh maybe you are interested in this or you can help me to fix the issue.

**Comment by andrewkroh** [comment]
It sounds like the last TODO listed on https://github.com/elastic/beats/pull/9202 hasn't been addressed.

>  Stop building x-pack packages from the OSS folder and use the mage package target added to x-pack/metricbeat.

This means that the OSS metricbeat/magefile.go needs to be updated to not build x-pack packages. The root Makefile also needs to be [changed](https://github.com/elastic/beats/blob/0b8bdd582397dba7a19505040a178488d6478de5/Makefile#L16-L24).

**Comment by sayden** [comment]
Ok, thanks for the help pointing to the files I need to check! I'll take a look and ping you if I get blocked :+1:

**Comment by sayden** [comment]
Fixed https://github.com/elastic/beats/pull/10396
