### ISSUE TITLE
CouchDB metribeat module

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#10354]
Keep track of development of CouchDB module started in elastic/beats#9406 

* [x] Supported versions are documented
* [x] Integration tests exist
* [x] System tests exist
* [x] Automated checks that all fields are documented
* [ ] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] Dashboards exists (if applicable)
* [ ] Kibana Home Tutorial (if applicable)
  * [ ] Open issue in [EUI repo](https://github.com/elastic/eui) to add [icon for module](https://elastic.github.io/eui/#/display/icons) if not already exists.
  * [ ] Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).
* [x] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [x] Test environment in Docker exist for integration tests
* [ ] Support CouchDB 2 #16352 #16455
* [ ] Support CouchDB 3 #16352

**Comment by sayden** [comment]
Reference about how to make the module work on 2.x https://discuss.elastic.co/t/metricbeat-couchdb-module-not-working/219094

By the way, 3.0 is released.
