### ISSUE TITLE
Improve documentation 'server' Metricset in Zookeeper Metricbeat module

### ISSUE THREAD

**Issue by sayden** [elastic/beats#10376]
`server` Metricset uses the `srvr` [4 letter word](https://zookeeper.apache.org/doc/r3.1.2/zookeeperAdmin.html#sc_zkCommands) to extract and parse data from a Zookeeper instance. 

[Our documentation](https://github.com/elastic/beats/blob/master/metricbeat/module/zookeeper/server/_meta/fields.yml) and [here](https://github.com/elastic/beats/blob/master/metricbeat/module/zookeeper/server/_meta/docs.asciidoc) of the fields returned by this _endpoint_ is not really detailed. It will be nice to improve it and describe a good description of each field

**Comment by arsalanc-v2** [comment]
Hi @sayden I would like to work on this

**Comment by ruflin** [comment]
@arsalanc-v2 Would be great if you could take this on.

**Comment by arsalanc-v2** [comment]
Great, I'll get started. Is there anything in particular I should go through apart from the zookeeper documentation and code?

**Comment by ruflin** [comment]
Nothing special comes to my mind. Perhaps @sayden has some more hints.

**Comment by sayden** [comment]
As a guideline when you fetch the `srvr` command to Zookeeper, this is what is returned:

```
echo srvr | nc localhost 2181
Zookeeper version: 3.4.8--1, built on 02/06/2016 03:18 GMT
Latency min/avg/max: 0/0/0
Received: 2
Sent: 1
Connections: 1
Outstanding: 0
Zxid: 0x0
Mode: standalone
Node count: 4
```

This is not very descriptive at all by itself and it seems that nothing is very detailed in the docs either. We want to make users happy when reading what each field is for, so that when they look at a dashboard and the description of each metric, they really understand what each field is for. For example, `Connections: 1`, does it mean that there's only a single connection open? A single connection on the last minute (open and closed)? Etc.

**Comment by arsalanc-v2** [comment]
Thank you for clarifying! I have opened a pull request with preliminary changes, I would appreciate your feedback.
