### ISSUE TITLE
Filebeat 1.1.1 fails to parse a regexp

### ISSUE THREAD

**Issue by shapirus** [elastic/beats#1038]
Hi.

I'm having issues trying to feed an exclude_lines regexp to Filebeat version 1.1.1 (on Ubuntu 14.04).

Here's the relevant line from filebeat.yml:

```
exclude_lines: ['PID\s\d+:\s$']
```

The YAML parsing step seems to be working fine (otherwise Filebeat will throw an error to stderr and refuse to start). Filebeat starts, but sends the following message to syslog (repeated, by the way, *541 times* making it a total of 1082 lines):

```
Feb 25 23:57:12 testhost /usr/bin/filebeat[22712]: util.go:37: Fail to compile the regexp PID\s\d+:\s$: error parsing regexp: invalid escape sequence: `\s`
Feb 25 23:57:12 testhost /usr/bin/filebeat[22712]: prospector.go:388: Error initializing harvester: error parsing regexp: invalid escape sequence: `\s`
```

Note that the entire regexp pattern appears in the log as is, which means it's not the issue of the YAML parsing procedure tampering with it (which apparently would be the case if there were double quotes in the .yml file instead of the single ones).

It looks like the pattern in question gets passed to the Go regexp compiling engine not as a raw string, but as a string in which escape sequences undergo further processing before it is finally used as a regexp pattern.

As a temporary workaround, I have to resort to using alternative sequences like ```[[:space:]]``` or ```[[:digit:]]``` to get rid of backslashes. Curiously, doubling the backslashes,

```
exclude_lines: ['PID\\s\\d+:\\s$']
```

does not seem to work. There's no error messages, but the respective log lines don't get excluded.

Is Filebeat designed to support perl-compatible regular expressions at all?

**Comment by andrewkroh** [comment]
You found the correct work-around by using POSIX regular expressions.

See #912 and #740.
