### ISSUE TITLE
Packetbeat on Windows Cannot Capture Localhost

### ISSUE THREAD

**Issue by fahmipriadi** [elastic/beats#104]
Is there any solution so the Packetbeat agent on Windows could sniff mysql connection on 127.0.0.1? I learned from http://www.hsc.fr/ressources/articles/win_net_srv/missing_loopback.html that Windows doesn't implement network loopback interface.

**Comment by monicasarbu** [comment]
@fahmipriadi What Windows version are you using?

**Comment by monicasarbu** [comment]
RawCap is a free command line network sniffer for Windows that uses raw sockets: http://www.netresec.com/?page=RawCap. It works to sniff the loopback interface, so I mark the issue as a Packetbeat enhancement.

**Comment by andrewkroh** [comment]
I tried [npcap v0.06-r10](https://github.com/nmap/npcap/releases) on Windows 2012 and it enabled me to capture traffic from the loopback interface using Packetbeat.

**Comment by hsluoyz** [comment]
Hi,

Please try Npcap: https://github.com/nmap/npcap/releases.

It is based on WinPcap and supports loopback traffic capturing on ``Windows Vista/7/8/10``.

After you installed Npcap, you can capture the loopback traffic using the created ``Npcap Loopback Adapter``.

**Comment by fahmipriadi** [comment]
@monicasarbu @hsluoyz @andrewkroh Thank you very much for all the advice, i'll try it on my server. I'm using Windows Server 2008 R2.
