### ISSUE TITLE
[CM] Improve documentation with CM when Filebeat is installed as a service on Windows

### ISSUE THREAD

**Issue by ph** [elastic/beats#10415]
When a Beat is installed with our service install scripts (`install-service-metricbeat.ps1`), the script will change the default data path to follow Windows convention.

The new data path will be `C:\ProgramData\metricbeat` or ``C:\ProgramData\filebeat`. If a user tries to enroll beats without specifying the correct data path, the beat will be enrolled to CM with the wrong UUID and will never receive the configuration. 

To fix the problem you can specify at enroll time the new data path using the ` -path.data` option.

Similar to this:

```
.\metricbeat.exe enroll http://xyz.gov:5601 70f4b584e8024b96b682c46125a8d81a --username elastic --password stdin --force -path.data "C:\ProgramData\metricbeat"
```

**Comment by dedemorton** [comment]
@ph I will update the docs, but I'm concerned that users might overlook this. They might copy the command generated by the CM UI and run it without reading the docs at all. Is there any way to add something to the command generated by the U? 

BTW, is this a problem on other platforms besides windows?

**Comment by ph** [comment]
@dedemorton This is a really good point!

We could do one of the following:
1. Add an explicit `-path.data` on the UI which point to `C:\ProgramData\metricbeat`
2. Add an explicit `-path.data` on the UI that point to the current data directory.
3. Search for `-path.data` in multiple place with the code.


Things I do not want to do is 3, this could open a big can of worms.

I am lacking a information of the Windows deployment usage, @urso or @andrewkroh do you think solution 1 would solve the most cases?

**Comment by ph** [comment]
@dedemorton Concerning other platforms, this should not be an issue because we install a shim on the platform that takes care of the paths.
