### ISSUE TITLE
Forcing Filebeat to resend files

### ISSUE THREAD

**Issue by muaazsaleem** [elastic/beats#1041]
Hi Guys,

I'm using filebeat to push log files to logstash. I have some static (unchanging) files to get started. But I can't seem to make filebeat resend files. I've tried 
- Deleting the registry file in /var/lib/filebeat/registry, 
- Updating the files using "touch /path/to/files",
- Even setting the ignore_older field to a really huge number e.g 10000h . 

But nothing seems to work. Filebeat just says **"DBG  Not harvesting, file didn't change:"**

Please help!

**Comment by muaazsaleem** [comment]
So it turns out the problem was my multiline config, It was
 multiline:
        pattern: '.*'
when it should've been
 multiline:
        pattern: '.*'
        match: after

**Comment by ruflin** [comment]
@muaazsaleem As it seems like your issue is resolved, I will close this one. In the future please use discuss for questions: https://discuss.elastic.co/c/beats

**Comment by muaazsaleem** [comment]
Will do, thanks!
