### ISSUE TITLE
confg `setup.template.settings.index.lifecycle.name` is not working

### ISSUE THREAD

**Issue by kimxogus** [elastic/beats#10422]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: filebeat, metricbeat 6.6.0
- Operating System: official docker images
- Discuss Forum URL: https://discuss.elastic.co/t/confg-setup-template-settings-index-lifecycle-name-is-not-working/166253
- Steps to Reproduce:
    1. Install [filebeat](https://github.com/helm/charts/tree/master/stable/filebeat) and [metricbeat](https://github.com/helm/charts/tree/master/stable/metricbeat) using helm chart.
       - set custom value for `setup.template.settings.index.lifecycle.name`

**Comment by ph** [comment]
I am missing details here, but I do believe this issue have fixed in the latest ILM implementation. If it still an issue please reopen it.
