### ISSUE TITLE
Packetbeat TLS protocol reports 0.0 version

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#10423]
- Version: 6.6.0
- Operating System: n/a
- Discuss Forum URL: n/a
- Steps to Reproduce: 

![image 2](https://user-images.githubusercontent.com/15056957/51973518-1c40d180-247e-11e9-9200-582479f0bec9.png)

This seems to happen after failed handshakes and can be related to #8772

Reported by @jamesspi

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
