### ISSUE TITLE
Add support to monitor CoreDNS

### ISSUE THREAD

**Issue by exekias** [elastic/beats#10432]
# Metricbeat Module / Dataset release checklist

Implement a new module to monitor `CoreDNS`. This is probably similar to what we did for apiserver: https://github.com/elastic/beats/pull/7059

## Modules
For a metricset to go GA, the following criterias should be met:

* [x] Supported versions are documented
* [x] System tests exist
* [x] Automated checks that all fields are documented
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] Dashboards exists #11619
* [x] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [x] Test environment in Docker exist for integration tests
* [x] Add Data UI

**Comment by ChrsMark** [comment]
Hey @exekias! 
Is anyone working on this already? @ioandr and me would be happy to implement this!

In this, are you considering this as a standalone metricebeat module, or a metricset ubder kubernetes's module? 
 
This integration seems really interesting now that CoreDNS is the default cluster DNS server of k8s.

**Comment by ruflin** [comment]
Hi @ChrsMark Nobody is working on this yet. I would see this as a separate module like Nats.

**Comment by ChrsMark** [comment]
Perfect! We will give it a try with @ioandr.

**Comment by ruflin** [comment]
@ChrsMark Great, thank you 🎉

**Comment by ruflin** [comment]
Implementation started in https://github.com/elastic/beats/pull/10585

**Comment by ChrsMark** [comment]
Hello, it would be nice to have the checklist updated!

From what I can see the only thing left is the dashboard?

**Comment by ruflin** [comment]
@ChrsMark Updated. Agree that Dashboards are missing and I added one more item to the list: Add Data UI.

**Comment by ioandr** [comment]
Hey @ruflin, 

I plan to take up the Dasbhoard and @ChrsMark can move on with the Kibana Tutorial (Data UI).

**Comment by ioandr** [comment]
> Hey @ruflin,
> 
> I plan to take up the Dasbhoard and @ChrsMark can move on with the Kibana Tutorial (Data UI).

@ruflin I have just opened a PR https://github.com/elastic/beats/pull/11619 for this, let me know WDYT when you find the time

**Comment by ruflin** [comment]
Thanks 👍
