### ISSUE TITLE
Add support to monitor kubernetes kube-proxy

### ISSUE THREAD

**Issue by exekias** [elastic/beats#10431]
# Metricbeat Module / Dataset release checklist

Implement a new metricset under Kubernetes module to monitor `kube-proxy`. This is similar to what we did for apiserver: https://github.com/elastic/beats/pull/7059

## Modules
For a metricset to go GA, the following criterias should be met:

* [x] Supported versions are documented
* [x] System tests exist
* [x] Automated checks that all fields are documented
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] Dashboards exists (if applicable)
* [x] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [ ] Test environment in Docker exist for integration tests

**Comment by exekias** [comment]
@odacremolbap can you update this? I think only dashboards are missing

**Comment by odacremolbap** [comment]
I have filled the checks at the original issue comparing to the apiserver.
kube-proxy lacks dashboards and docker test environment

**Comment by odacremolbap** [comment]
closing, pending system tests for all kubernetes components will be managed at a different issue
