### ISSUE TITLE
Single Beats Agent/Supervisor

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#10452]
The Beats supervisor will be a single agent that allows the users to manage and configure multiple Beats and also run them in a separate process for each Beat. It will also be able to download and upgrade the Beats as well as upgrade itself.

**Product name:** `Beats`
  
## Why?

* Reduce the number of services/agents that need to be maintained: For example, our users usually are interested in collecting logs as well as metrics, and currently, they need to install Filebeat, Metricbeat and others. With the addition of the Beats agent, the user needs to install a single agent that allows them to start any Beat on demand. 
* Improve user experience: The user should be able to choose from the Beats central management UI what data sources they are interested to collect. For example, in case the user wants to monitor MySQL metrics and also collect the slow logs, then the user would be able to do that with just one UI click that allows the Beats agent enable the MySQL module in Filebeat and Metricbeat. 
* Control resource usage consumption of the Beats
* Improves the getting started experience as the user needs to download a single package instead of multiple ones for each Beat.
* Be able to upgrade Beats from a central location.

## How it works

The Beats supervisor will come with specific packages for download for each OSS, similar to the Beats. It will be offered for download in addition to the current Beats packages. 

On a fresh install, the Beats supervisor package doesn't contain any Beat, but it's able to download and install any Beat on request. For air-gapped environments, we consider offering for download the Beats binaries also from Kibana itself. As an alternative for the users, there will also be a Beats supervisor package that already contains all Beats. 

The Beats supervisor is coming with a simple configuration file that allows the user to configure all the managed Beats. 

Server-side components such as Heartbeat and APM server could also be part of the Beats supervisor, with a single configuration similarly defining and instrumenting what gets deployed
 
## Integration with Beats Central Management

Currently, in Beats Central Management, each Beat needs be enrolled by running a command line. In the case of 80k+ Beats, a script is required to be run on the user site. 

With the addition of the Beats supervisor, we reduce the number of enrollments as the user needs to enroll only the Beats supervisor and this will automatically enroll all the managed Beats. 

## Auto-upgrade 

The Beats supervisor needs to be at the same version as all managed Beats. That’s why at upgrade, the Beats supervisor downloads and installs the newer version of Beats as well as a newer version of the Beats supervisor to upgrade itself. 

The Beats supervisor will come with an auto-upgrade configuration option. 

## First phase: 
- Start with Beats online version (offline / air-gapped version can come later)
- Beats will come with no other default bundled *beat, but instead will be able to download, install, and run other *beats as needed. The perception of a smaller binary size for an agent is important.
- Support a single configuration file, and based on that config it will download and run respective *beats required for the collection workload
- Centralized mgmt (CM) should only communicate with the Beats supervisor, and the Beats supervisor will communicate with and orchestrate the other *beats. The “only install one agent” story is very compelling.

@elastic/beats @elastic/beats-contributors

**Comment by ppf2** [comment]
As we look into building a single beats agent, it will be great if we can consider the metricbeat use case (https://github.com/elastic/beats/issues/11519) and the fact that stack monitoring will use beats in the future v.s. an Elasticsearch http exporter.  Providing the ability to configure this single agent to route all stack monitoring events to an Elasticsearch output, while allowing users to configure this agent to route all production non-monitoring events to a different output (e.g., output.kafka) will greatly simply the configuration of these use cases in the field.
