### ISSUE TITLE
add_kubernetes_metadata processor is broken because it uses old field "source" for lookup

### ISSUE THREAD

**Issue by alakahakai** [elastic/beats#10505]
Filebeat add_kubernetes_metadata processor is no longer working, because it still uses old field "source" for matcher, while the source field has been changed to log.file.path by ECS.

**Comment by ruflin** [comment]
@alakahakai This indeed sounds like a bug. I haven't tested it locally but I see you already have a commit above. Could you open a PR with the fix against the Beats repo?

**Comment by ruflin** [comment]
Nevermind, just found this PR: https://github.com/elastic/beats/pull/10506

**Comment by odacremolbap** [comment]
@alakahakai @ruflin 
can we close this issue?

**Comment by ruflin** [comment]
@odacremolbap I assume yes, can you check if all the needed backports happened?

**Comment by odacremolbap** [comment]
it is
(although it looks like the `cherrypick_pr` tool was not used, but the code is present at `7.0` and `7.x`)

closing
