### ISSUE TITLE
Journalbeat translated conatiner.id_truncated field typo

### ISSUE THREAD

**Issue by SpComb** [elastic/beats#10519]
Version: 6.5.4
Operating system: Amazon Linux 2
Discuss Forum URL: https://discuss.elastic.co/t/incorrect-journalbeat-container-output-fields-for-docker-journald-messages/166017

Journalbeat translates the Docker journald logging driver `CONTAINER_ID` field to `conatiner.id_truncated`: https://github.com/elastic/beats/blob/v6.5.4/journalbeat/reader/fields.go#L83

This is a typo, it should be `container.id_truncated`.

**Comment by stanxing** [comment]
@kvch This problem still exists in 6.7 release. Is there any plan to release it?
https://github.com/elastic/beats/blob/v6.7.0/journalbeat/reader/fields.go#L83

**Comment by kvch** [comment]
It's not going to be fixed in 6.x, as it would be a breaking change.
