### ISSUE TITLE
Journalbeat reports Docker CONTAINER_TAG as container.image.tag

### ISSUE THREAD

**Issue by SpComb** [elastic/beats#10520]
Version: 6.5.4
Operating system: Amazon Linux 2
Discuss Forum URL: https://discuss.elastic.co/t/incorrect-journalbeat-container-output-fields-for-docker-journald-messages/166017

Journalbeat translates the `CONTAINER_TAG` field generated by the Docker journald log driver to `container.image.tag`: https://github.com/elastic/beats/blob/v6.5.4/journalbeat/reader/fields.go#L86

This is not consistent with the semantics for `container.image.tag` in ECS: https://github.com/elastic/ecs#container

> Container image tag.

The `CONTAINER_TAG` field generated by the Docker journald log driver can be customized using `--log-opt tag=...`, and it defaults to the short container ID: https://docs.docker.com/config/containers/logging/journald/#options https://docs.docker.com/config/containers/logging/log_tags/

It would be possible to configure Docker with `--log-opt 'tag={{.ImageName}}'`, but this would generate a `CONTAINER_TAG` field with the full `REPOSITORY/IMAGE:TAG` field, not just the tag part.

I don't know what the correct translated field would be, ECS does not include any appropriate field for the user-defined `CONTAINER_TAG`. However, the `CONTAINER_TAG` field is very useful for applying the correct logstash grok rules to the correct container outputs, because the `container.name` can vary on different hosts or similar containers.

**Comment by SpComb** [comment]
Current workaround is to simply use the `container.image.tag` field in logstash. However, if something were to overwrite the `container.image.tag` field with the actual container image tag, then the original `CONTAINER_TAG` field would become completely inaccessible.

I have not yet tested the `add_docker_metadata` processor, but it looks like the `add_docker_metadata` currently only writes `container.image.name`, but not `container.image.tag`: https://github.com/elastic/beats/blob/f43683f1bb9395cd262af72c68e426cca0c42f6f/libbeat/processors/add_docker_metadata/add_docker_metadata.go#L185-L187 (looks like the `container.image.name` ends up being the `sha256:...` hash of the Container image?)

**Comment by ruflin** [comment]
@webmat This is worthing having a look for ECS.

**Comment by webmat** [comment]
Perhaps Journalbeat could add the user-defined tags to the top level [tags](https://github.com/elastic/ecs#user-content-tags) field?

I'm actually a bit fuzzy on which one will contain what. I need to see the data to fully grasp.

Note for @ruflin `tags` vs `tag` inconsistency 😢

**Comment by SpComb** [comment]
:+1: for `container.log.tag` - the `--log-opt tag=...` is specific to logging, and the usecase is to identify the log events themselves, not the container.

**Comment by kvch** [comment]
Thank you for the verification!

**Comment by webmat** [comment]
I'm fuzzy on what's being suggested overall. Are we talking about adding both `container.log.tag` and `container.tag`? Or are we trying to decide between the two? :-)
