### ISSUE TITLE
Filebeat collect binary file with custom codec.

### ISSUE THREAD

**Issue by wenerme** [elastic/beats#1055]
I got some binary file,like kafka commit log,I want to use the filebeat to forward these file to logstash then decode with custom codec.I checked filebeat source, it's only support line based test encoding.

I think filebeat also can use like a library, the prospector, harvester and encoding should be customizeable, the encoding is not only text based.

**Comment by ruflin** [comment]
As you described, filebeat is currently focus on files which are line based. Could you give some more details on the structure of the files you are talking about? How is the end of a "segment / message" defined?

Also have a look at https://github.com/cleesmith/unifiedbeat

**Comment by wenerme** [comment]
The file structure like 
```
|4 byte message length|message|....
```
the beat should publish every message.

and it's not a single file, it's directory like 
```
log/
     0000000000
     0000006473
     0000009028
```
the filename indicate the fist offset of the message in this file.It should read by order.

Also these file is mmaped by running app.they are still growing.so after a EOF, the file may contain more messages.

Currently the collector of these log is written by Java with flume, it's heavy,so I try to replace it with beats.

I checked https://github.com/cleesmith/unifiedbeat, want I want to do is very similar to this, it'a good start, thanks, but it also repeat a lot stuff which filebeat already do it well.

**Comment by ruflin** [comment]
Thanks for the additional details.

It is definitively on our roadmap to better abstract the prospector and harvester. This should make it possible to use filebeat also as a library, means only few additional things must be implemented to create a beat based on it. Then the decision can be made if it should be part of filebeat or leave as its own beat.

But we are not there yet. Prospector and harvester or still not fully separated, but we are working on it to get there (for example https://github.com/elastic/beats/pull/964). We also learned quite a bit from unifiedbeat on which parts should be better abstracted. Contributions to get us closer to the filebeat as a library are more then welcome :-)

**Comment by monicasarbu** [comment]
Closing this question. @wenerme Please re-open the issue if you need more details.
