### ISSUE TITLE
Central management E2E testing improvements

### ISSUE THREAD

**Issue by ph** [elastic/beats#10636]
Scenario not tested with the current integration suite:

- TLS handling when enrolling, when you enroll you can pass -E options to configure your certificate authorities.
- Events reporting from the beats, when an internal state changes or an error occurs the beats will periodically sends events to the backend, we unit test the behavior buts we don't have an integration test for it.
- unenroll a beats

Future:

We might want to explore limit scenarios when errors occur under load. Discovery from this phase would certainly lead to add feature to libbeat to deal with the errors.

**Comment by ph** [comment]
@kvch this is really a high level list.

**Comment by urso** [comment]
@ph Can the introduction of the agent, we close this?

**Comment by ph** [comment]
We can close this.
