### ISSUE TITLE
Documented log path is wrong format for windows

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#10646]
The example in the Winlogbeat doc uses the wrong path format because the content is shared across all Beats. We need to add conditional blocks to render this section correctly for Windows.

Replaces https://github.com/elastic/website-www.elastic.co/issues/3540

**Comment by neu5ron** [comment]
any update on this? I just used 6.6.1 and have to use forward slashes "/" in the winlogbeat config -- and that is opposite of the logic of windows as it uses back slashes "\" (as I am sure you all know).

**Comment by dedemorton** [comment]
@neu5ron Yes! I've opened a PR to fix the problem: https://github.com/elastic/beats/pull/10647. There were some failures in the tests, though, so I had to do some extra stuff to make everything green. It looks like my changes worked, so I will merge the PR today.
