### ISSUE TITLE
Enhance BeatsCM with automatic setup of ingest pipelines

### ISSUE THREAD

**Issue by n0othing** [elastic/beats#10651]
Today, we require users to manually load ingest pipelines[1] if using Logstash or BeatsCM. It'd be really helpful if ingest pipelines were loaded automatically if a beat is enrolled and configured via central management.

[1] https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-modules-quickstart.html#load-ingest-pipelines

**Comment by ph** [comment]
I've created https://github.com/elastic/beats/issues/11167 to define the objectives.
