### ISSUE TITLE
Filebeat apache2 module > Provided Grok expressions do not match field value

### ISSUE THREAD

**Issue by Detzler** [elastic/beats#10656]
Provided Grok expressions do not match field value on:

`127.0.0.1 - - [02/Feb/2019:05:38:45 +0100] "-" 408 152 "-" "-"`

- Version: 6.6.0 stack of Filebeat, ES & Kibana. Apache/2.4.25
- Operating System: Debian 9.7
- Steps to Reproduce: Default Setup of Filebeat and Apache2

**Comment by sayden** [comment]
Fixed in https://github.com/elastic/beats/pull/10730
