### ISSUE TITLE
Support kafka output testing

### ISSUE THREAD

**Issue by Popsiclestick** [elastic/beats#10652]
**Describe the enhancement:**
Beats Kafka output does not currently support output testing. We should add functionality for verifying  connectivity of the kafka output.

**Describe a specific use case for the enhancement or feature:**
This would allow users to test their beats ability to interface with kafka before starting their application. Kafka output is a common use case for beats and this would be a helpful test/healthcheck.

Current behavior:
```
:; ./filebeat test output
kafka output doesn't support testing
```

**Comment by jsoriano** [comment]
Closing this, and created https://github.com/elastic/beats/issues/10652 for TLS support on this check.
