### ISSUE TITLE
Add support for TLS and HTTP auth for the HTTP API endpoint.

### ISSUE THREAD

**Issue by ph** [elastic/beats#10674]
Currently, the beat HTTP API endpoint that exposes metrics and other information related to the running beat do not allow a user to lock down that endpoint.

We should allow users to configure TLS and/or allow a user to setup HTTP Auth for incoming requests.

**Comment by ruflin** [comment]
@ph An alternative to that which we discussed in the past is exposing this information through a socket.

@urso @andrewkroh should have here some more details.

**Comment by ph** [comment]
@ruflin Yes, I do remember that discussion, we can still allow that. But for now, the endpoint offers only ready only information, allowing people to add their cert to the endpoint is not too bad.
