### ISSUE TITLE
Filebeat: All memory can be consumed by Filebeat when Elasticsearch is in read-only state

### ISSUE THREAD

**Issue by to-bar** [elastic/beats#10696]
- Version: 6.5.4
- Operating System: Red Hat 7.5
- Steps to Reproduce:
1. Switch Elasticsearch to read only mode (this happens when disk space is low):
`curl -X PUT '${ES_HOST_IP}:9200/_all/_settings' -H 'Content-Type: application/json' -d'{ "index.blocks.read_only_allow_delete" : true } }'`

2. Measure memory used by Filebeat in short gaps, it incrementally grows:
```
$ sudo smem --processfilter="filebeat" -t -k
  PID User     Command                         Swap      USS      PSS      RSS
93736 root     /usr/share/filebeat/bin/fil        0   318.8M   318.9M   319.2M

$ sudo smem --processfilter="filebeat" -t -k
  PID User     Command                         Swap      USS      PSS      RSS
93736 root     /usr/share/filebeat/bin/fil        0   844.0M   844.1M   844.7M

$ sudo smem --processfilter="filebeat" -t -k
  PID User     Command                         Swap      USS      PSS      RSS
88319 root     /usr/share/filebeat/bin/fil        0     2.1G     2.1G     2.1G
```

This caused invoking oom-killer and at that moment most of memory was used by filebeat process.
 
This issue can be related to #10691, it seems that in only happens when in filebeat.yml there is:
```
- type: log
  include_lines: ['ERROR', 'WARN']
  paths:
    - /var/log/filebeat/filebeat* 
```
[filebeat.yml.txt](https://github.com/elastic/beats/files/2856026/filebeat.yml.txt)

**Comment by ph** [comment]
OK, from what I see I believe the issue in 6.5.4 was in the Docker inputs, we did quite a lot of refactoring of that input.  I think this should not be an issue anymore. If its still an issue in the latest beats please reopen the issue.
