### ISSUE TITLE
Documentation on changing index is subpar, in my opinion.

### ISSUE THREAD

**Issue by ensemblebd** [elastic/beats#10707]
**Describe the enhancement:**
The documentation [here](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-template.html) is not sufficient to change an index pattern.
1. [Covered] metricbeat.yml, change `output.elasticsearch` -> `index`. 
2. [Semi-Covered] Therefore also change: `setup.template.name`, `setup.template.pattern`. One must change the template.name which leads to..
3. Modify all files under kibana folder to replace `metricbeat-*` and `metricbeat*` (use grep), with your new index pattern. Noting that if you changed `setup.template.name` (I did), you must also create that file under `kibana/<v>/index-pattern/<template>.json` (clone existing, grep&replace).
4. Cleanup/reset, then run [setup] switch on executable to reload dashboards/etc.

**Describe a specific use case for the enhancement or feature:**
When setting up multiple spaces with several independently tracked indices for different purposes.
Instead of conglomerating all stats into a single index, despite "multi-space support" in kibana.

**Comment by urso** [comment]
@dedemorton fyi
