### ISSUE TITLE
[Metricbeat] Add best practice metrics to Couchbase module

### ISSUE THREAD

**Issue by dbason** [elastic/beats#10708]
**Describe the enhancement:**
Couchbase has a blog post detailing some best practice metrics to include - https://blog.couchbase.com/monitoring-couchbase-cluster/.  In particular it might be good to include the the cache miss ratio and disk drain metrics in the bucket metricset

**Comment by masci** [comment]
Superseded by https://github.com/elastic/integrations/issues/909
