### ISSUE TITLE
"Package" beat for monitoring installed packages

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#1071]
Use case:  Provide metrics/report on the software that is installed on which servers (eg. yum, rpm, msi, etc..). The use case is for auditing and tell admins if there are software that need to be patched.  For both Windows and Linux environments.

**Comment by ruflin** [comment]
This is a very interesting and powerful use case. Sounds like a beat that could be implemented quite easily for Linux. Not sure about OS X and Windows. Perhaps someone from the community already built it (or is interested in building it).

Perhaps https://github.com/christiangalsterer/execbeat or https://github.com/PhaedrusTheGreek/nagioscheckbeat could be used as an intermediate solution.

**Comment by ppf2** [comment]
Yep, we are using execbeat + logstash split filter as a workaround.

**Comment by ruflin** [comment]
@ppf2 Nice :-)

**Comment by tsg** [comment]
[Factbeat](https://github.com/jarpy/factbeat) might also be an option.

**Comment by l0x-c0d3z** [comment]
We're currently looking at implementing this.

Our immediate needs are:
 - List installed Windows patches
 - List installed software and versions.

We are thinking about implementing this in the Windows module of metricbeat, just like services are implemented. Would this be the right way, and what are the chances of getting a pull request for this feature merged ?

In a longer term we're thinking about implementing similar functionality for common linux packages (rpm, deb, etc.).

**Comment by kresss** [comment]
We have this for Linux now using Auditbeat's System Module. Can we get this same thing for Windows?

**Comment by kresss** [comment]
This would still be nice to have.
