### ISSUE TITLE
Traefik module not support access log with json format

### ISSUE THREAD

**Issue by AlloVince** [elastic/beats#10765]
**Describe the enhancement:**
Hi guys, due to traefik support access log with json format:

https://docs.traefik.io/configuration/logs/

```
    [accessLog]
       format = "json"
```

Currently, filebeat only support the default CLF format, but json format will take more info and easier to expending, I hope the json format could be supported

**Describe a specific use case for the enhancement or feature:**

**Comment by sayden** [comment]
Hi @AlloVince . We usually only support default formats with some exceptions. In this case you can workaround this issue by using Filebeat Log input configuring it to parse JSON https://www.elastic.co/guide/en/beats/filebeat/6.4/filebeat-input-log.html#filebeat-input-log-config-json

**Comment by MikaelElkiaer** [comment]
> Hi @AlloVince . We usually only support default formats with some exceptions. In this case you can workaround this issue by using Filebeat Log input configuring it to parse JSON https://www.elastic.co/guide/en/beats/filebeat/6.4/filebeat-input-log.html#filebeat-input-log-config-json

@sayden How would this work together the built-in dashboard or something like GeoIP?
Would that require some additional steps?
