### ISSUE TITLE
Beats 7.x documentation pages should mention `migration.enabled:true`

### ISSUE THREAD

**Issue by webmat** [elastic/beats#10772]
**Describe the enhancement:**

I haven't seen mentions of the `migration.enabled` setting, for the Beats YAML config.

This is the setting that lets people decide whether their index template should include field aliases that were introduced in the ECS migration from 6.x to 7.x. By default this setting is off, so it's pretty important to document it well.

I was looking at the Filebeat documentation, here's places I think should mention its usage:

- Getting Started with Filebeat: filebeat-configuration.html, filebeat-template.html or both.
- Perhaps even a whole page in the "Configuring Filebeat" section would be in order: configuring-howto-filebeat.html

I haven't looked at the documentation of the other Beats, but I think this applies to all of the official ones.

**Comment by ruflin** [comment]
This should be in our migration guide.

cc @roncohen

**Comment by webmat** [comment]
Related: https://github.com/elastic/beats/pull/11286

**Comment by dedemorton** [comment]
Note that this setting has been renamed from migration.enabled to migration.6_to_7.enabled

**Comment by dedemorton** [comment]
Note that I've added info about this option to the 7.0 upgrade docs: https://github.com/elastic/beats/pull/11378. I'm keeping this open because I plan to add a general topic to the docs that describes the compatibility layer.

**Comment by webmat** [comment]
The commented out setting is now changing to true here https://github.com/elastic/beats/pull/11559

**Comment by dedemorton** [comment]
@webmat Do you think we cover this sufficiently in the upgrade docs, or should I add a separate topic where we talk about configuration options? I'm not sure this setting is relevant outside of migration.

**Comment by webmat** [comment]
This setting is definitely very specific to the upgrade, I agree with you it's not really relevant outside of the migration steps. I think we're good with what we have.

Your latest updates to the upgrade docs are now published right? I haven't been following closely. If so, I think we can stop there for now, and revisit only if we get feedback or repeated questions about it.

Speaking of which, I think I've seen a few distinct questions about the upgrade, but my understanding of what I've seen on Discuss is that these were made by users upgrading by "winging it" (to use the scientific term) and / or using custom index names without understanding what they were getting into.

What I take from this is that we could use more pointers to libbeat/upgrading-6-to-7. If users don't RTFM we can't help them much, but we need to make sure the upgrade docs get on people's radar that do RTFM :-)

Other than that, I think we're good.

**Comment by dedemorton** [comment]
OK, I'll look for more opportunities to add links to the upgrade docs.
