### ISSUE TITLE
Add cloud metadata processor docs are out of date

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#10775]
This came up in a discussion with @ruflin who was on his way out and asked me to open an issue. Apparently the docs for https://www.elastic.co/guide/en/beats/filebeat/master/add-cloud-metadata.html are out of date with the latest implementation and should be updated.

**Comment by andrewkroh** [comment]
I added a fix in https://github.com/elastic/beats/pull/10987.

**Comment by kaiyan-sheng** [comment]
`Amazon Elastic Compute Cloud (EC2)` should change to `Amazon Elastic Compute Cloud (AWS)` after https://github.com/elastic/ecs/pull/348 is merged. In the example here https://www.elastic.co/guide/en/beats/filebeat/master/add-cloud-metadata.html, `cloud.provider` should change from `ec2` to `aws` as well. I will push a PR for this later.

**Comment by dedemorton** [comment]
@andrewvc  Has all the missing content been added? Can we close this issue now?
