### ISSUE TITLE
Cleanup work for 8.0.0

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#10773]
This issue is to track all the cleanup work needs to be done before 8.0.0. Please feel free to add items into this list. 

- [ ] Dedot docker and k8s labels/annotations by default

**Comment by jsoriano** [comment]
> Dedot docker and k8s labels/annotations by default

I think the plan was to do it in 7.0, wasn't it done? :grimacing:

**Comment by jsoriano** [comment]
> I think the plan was to do it in 7.0, wasn't it done? grimacing

Replying to myself, yes, it seems to be set to true by default. @kaiyan-sheng is dedotting missing in some place?

**Comment by kaiyan-sheng** [comment]
@jsoriano Yes it's done for 7.0. Do we need to remove the dedot option in 8.0?

**Comment by jsoriano** [comment]
I think we can keep it, in case someone doesn't want dedotting.

**Comment by kaiyan-sheng** [comment]
Maybe I should close this issue :-)

**Comment by exekias** [comment]
+1 to keep the feature, we just ship we the right defaults :)

**Comment by kaiyan-sheng** [comment]
Yeah, I will close this for now!
