### ISSUE TITLE
Functionbeat validation of the presence of the Elasticsearch is not done before the pipeline is created.

### ISSUE THREAD

**Issue by ph** [elastic/beats#10813]
In functionbeat, we override some of the core defaults by using the [Settings overrides](https://github.com/elastic/beats/blob/master/x-pack/functionbeat/config/config.go#L30-L35), When you we are referencing the elasticsearch output it will cause initialization issue with the pipeline.

So instead of outputing a good message telling that the elasticsearch output is required for functionbeat to correctly work we get the following:

```
    error unpacking config data: more than one namespace configured accessing 'output'
```

**Comment by Randy-312** [comment]
I will be using FuntionBeat in an AWS Account that is separate from my AWS Account that contains ElasticSearch.

Please consider this in the 'startup and retry backoff mechanisms' for this function.
It may just be making recommendations on how to use / configure functionbeat.

**Comment by jlind23** [comment]
We endeavor to address Functionbeat use cases via the new Serverless Forwarder project (https://github.com/elastic/elastic-serverless-forwarder)with a better integration with serverless functionality provided by major cloud providers. Enhancements to the current Functionbeat will therefore be limited.
