### ISSUE TITLE
Metricbeat: Add support for ZFS metrics

### ISSUE THREAD

**Issue by msLinuxNinja** [elastic/beats#10848]
With ZFS on Linux almost (a long way) reaching version 1.0 and an increasing user base, Metricbeat should add metric collection for ZFS metrics such as zpool iostat (pool metrics) and arcstat (ARC and L2ARC cache metrics).

Dashboards should also be included for ZFS metrics.

**Comment by guillaumedsde** [comment]
kind bump :) would be very interested in this feature

**Comment by loop-evgeny** [comment]
Would be great to see, especially monitoring for failed disks in zpools.
