### ISSUE TITLE
Add the ability to enable/disable geoip for Filebeat Apache 2 Module

### ISSUE THREAD

**Issue by sachin-frayne** [elastic/beats#10867]
**Describe the enhancement:**

It would be useful if the Filebeat Apache 2 Module could have the option to enable/disable the use of the ingest-geoip plugin or at least the ability to stop the geoip call.

**Describe a specific use case for the enhancement or feature:**

The specific use case would be purely internal logs where the `geoip` is not necessary.

**Comment by chiemeleakoma** [comment]
This  is affecting user of AWS ES as it does not have the ingest-geoip plugin installed and cant be installed by users either

**Comment by okgolove** [comment]
The same idea for the nginx plugin.

**Comment by eapenj** [comment]
Is there any temporary workaround for this issue ? ( filebeat nginx module does not work with AWS ES due to lack of support for ingest-geoip plugin in AWS ES )

**Comment by sinkr** [comment]
Same issue here.

**Comment by edo-lynx** [comment]
+1

**Comment by vdmkenny** [comment]
dealing with the same issue.

**Comment by generalconsensus** [comment]
+1, unable to use filebeat with aws ES due to this issue. Moving to use another system

**Comment by arukaen** [comment]
+1, Almost 2 years later.

**Comment by idwessough** [comment]
+1,  any answer today ? I'm usinng AWS ES with Filebeat OSS but my IIS module dosn't work cause of this plugin

**Comment by sachin-frayne** [comment]
I am re-opening as this has not yet been taken into consideration
