### ISSUE TITLE
make test runs vendor test cases as well

### ISSUE THREAD

**Issue by vjsamuel** [elastic/beats#1086]
```
ok  	github.com/elastic/beats/metricbeat/module/mysql	0.014s	coverage: 71.4% of statements
ok  	github.com/elastic/beats/metricbeat/module/mysql/status	0.016s	coverage: 86.2% of statements
ok  	github.com/elastic/beats/metricbeat/module/mysql/vendor/github.com/go-sql-driver/mysql	0.023s	coverage: 24.6% of statements
ok  	github.com/elastic/beats/metricbeat/module/redis	0.010s	coverage: 71.4% of statements
ok  	github.com/elastic/beats/metricbeat/module/redis/info	0.012s	coverage: 87.0% of statements
```

This is the output of make test of metricbeat and can be also found here:
https://travis-ci.org/elastic/beats/jobs/112868869

We should not be running vendor test cases as they require many more dependencies to build and run hence causing the need to import too many modules through glide.

The reason for this is because glide novendor doesnt look for nested glide files and ignores their vendors.

Each module has a glide.yaml which doesnt seem to be picked up when identifying the directories on which tests have to be run against.

**Comment by radoondas** [comment]
I had the same issue and I have discussed with @ruflin at elastic{ON}. 
Should be fixed. 
You have to use 'make unit-tests' to run only beat tests and no vendor tests.
I hope I'm not mistaken and it haven't changed since one week :)

**Comment by vjsamuel** [comment]
Fixed in https://github.com/elastic/beats/pull/1088

**Comment by ruflin** [comment]
@vjsamuel Glad we found the same solution: https://github.com/elastic/beats/pull/1073/files#diff-10a13ca4ead559a247a9fc409662791cR6

@radoondas That is an issue with the nested vendor directory. The line provided here by @vjsamuel fixes it: https://github.com/elastic/beats/pull/1088/files#diff-d2f9f6e7040050cd09938355f7d358a6R7
