### ISSUE TITLE
Renegotiation setting missing in tls.Config

### ISSUE THREAD

**Issue by simitt** [elastic/beats#10871]
When configuring ssl/tls users can configure a `Renegotiation` option. This option is set in the [`TLSConfig`](https://github.com/elastic/beats/blob/master/libbeat/common/transport/tlscommon/tls_config.go#L62) but not passed to [`tls.Config`](https://github.com/elastic/beats/blob/master/libbeat/common/transport/tlscommon/tls_config.go#L82).
Thus, `BuildModuleConfig` ignores the configured renegotiation option and uses the default. 

While at it, as @andrewkroh pointed out, there is also a typo in the [yml config](https://github.com/elastic/beats/blob/0a914fa298acb55bb57b9a8d45a25319feff8543/libbeat/common/transport/tlscommon/config.go#L35) for _renegotiation_.

**Comment by konstantinoskostis** [comment]
@simitt hello! I have provided a PR (https://github.com/elastic/beats/pull/12354) that fixes this issue!
Review at your earliest convenience.

PS: Not sure why the CLA signature is marked as erroneous. My email is correct, present in https://patch-diff.githubusercontent.com/raw/elastic/beats/pull/12354.patch and present on github!
