### ISSUE TITLE
Docs page for Community Beats has broken link for burrowbeat

### ISSUE THREAD

**Issue by MarkSettleES** [elastic/beats#10885]
The [Docs page for Community Beats](https://www.elastic.co/guide/en/beats/libbeat/current/community-beats.html) lists several community-developed Beats. The fourth one on this list, _burrowbeat_, [points here](https://github.com/goomzee/burrowbeat), which currently 404s.

Perhaps it has simply [moved here](https://github.com/adswizz/burrowbeat)?

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/beats/pull/12330.
