### ISSUE TITLE
Shipper docs should point to logs and infrastructure solution docs 

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#10883]
This request comes from @tbragin:

Beats documentation has some content on getting started with logs and metrics use cases, especially as part of Filebeat and Metricbeat guides. At the moment, they do not bear any mention of Logs and Infrastructure solutions, nor added value APM adds to the equation.

Recommendation: We should point to Logs and Infrastructure guides from the Filebeat and Metricbeat docs.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
