### ISSUE TITLE
make create-metricset fails on Windows

### ISSUE THREAD

**Issue by jlhde123** [elastic/beats#10919]
I want to extend metricbeat.
I follow the document,And execute make create-metricset.
but it failed,why?
The error message is as follows:

**C:\Users\Administrator\go\src\github.com\elastic\beats\metricbeat
λ make create-metricset
C:\Users\Administrator\go\bin\mage.exe
Unknown target specified: create-metricset**

**Comment by jsoriano** [comment]
@jlhde123 thanks for reporting this, it looks like a problem in Windows, it works for me on Linux.
