### ISSUE TITLE
Would like to specify the beat module index pattern

### ISSUE THREAD

**Issue by peasead** [elastic/beats#10918]
**Describe the feature:**
Add a CLI switch when running `[beat] setup --dashboards` to select what index pattern to use instead of requiring a specific index pattern or set something in `/etc/[beat]/[beat].yml`

**Describe a specific use case for the feature:**
We have created a Suricata module for Filebeat but we'd like to swap off of that to use the built-in Suricata module for Filebeat if possible. Mainly because it is maintained by Elastic and comes with some prebuilt visualizations.

During testing, we identified that the index pattern for the dashboards must be `filebeat-*`. While it's fine to have this when it ships, we don't use that index pattern format for our Suricata data.

**Comment by andrewkroh** [comment]
You can do this:

`filebeat setup —dashboards -E setup.dashboards.index=myindex-*`

https://www.elastic.co/guide/en/beats/filebeat/current/configuration-dashboards.html#_literal_setup_dashboards_index_literal

**Comment by jsoriano** [comment]
I am closing this by now, @peasead please reopen if the proposed flag doesn't work for you for some reason.
