### ISSUE TITLE
unknown key [objects] in the template

### ISSUE THREAD

**Issue by greenpau** [elastic/beats#10922]
Attempted to create an index template from `winlogbeat.json` provided with `winlogbeat-6.6.1-windows-x86_64.zip`:

```
wget https://artifacts.elastic.co/downloads/beats/winlogbeat/winlogbeat-6.6.1-windows-x86_64.zip
unzip winlogbeat-6.6.1-windows-x86_64.zip
cd winlogbeat-6.6.1-windows-x86_64/kibana/6/index-pattern
curl -s --insecure -XPUT -H 'Content-Type: application/json' 'https://localhost:9200/_template/winlogbeat' -d@winlogbeat.json | python -m json.tool
```

The upload fails with:

```
{
    "error": {
        "reason": "unknown key [objects] in the template ",
        "root_cause": [
            {
                "reason": "unknown key [objects] in the template ",
                "type": "parse_exception"
            }
        ],
        "type": "parse_exception"
    },
    "status": 400
}
```

**Comment by greenpau** [comment]
An attempt to do the same via Kibana API failed:

```
# curl -s --insecure -XPUT -H 'Content-Type: application/json' 'http://localhost:5601/api/saved_objects/index-pattern/filebeat-*'  -H 'kbn-xsrf:true' -d@winlogbeat.json | python -m json.tool
{
    "error": "Bad Request",
    "message": "child \"attributes\" fails because [\"attributes\" is required]. child \"version\" fails because [\"version\" must be a number]. \"objects\" is not allowed",
    "statusCode": 400,
    "validation": {
        "keys": [
            "attributes",
            "version",
            "objects"
        ],
        "source": "payload"
    }
}
```

**Comment by andrewkroh** [comment]
Please see https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-template.html for instructions how to load the Elasticsearch Index Template.

And please use https://discuss.elastic.co/c/beats for posting questions. If we confirm there is a bug then we will track it in Github. Thanks.

**Comment by greenpau** [comment]
> Please see https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-template.html for instructions how to load the Elasticsearch Index Template.

@andrewkroh , I did read it. As you can see I am using a different interface from the one in the article.

**Comment by andrewkroh** [comment]
> Attempted to create an index template

> cd winlogbeat-6.6.1-windows-x86_64/kibana/6/index-pattern

> -d@winlogbeat.json

But that file is not an Elasticsearch index template. That's for Kibana.

To manually install the Elasticsearch index template you need to first export the template for your specific ES version as shown in those docs. Like

> PS > .\winlogbeat.exe export template --es.version 6.6.1 | Out-File -Encoding UTF8 winlogbeat.template.json

Then you can install it.
