### ISSUE TITLE
Add ECS container fields for kubernetes

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#10926]
Kubernetes fields are not migrated to ECS, but from some of them we could extract some common fields:
* `kubernetes.container.id` has the form `runtime://id`, we could extract `container.runtime` and `container.id`.
* `kubernetes.node.name` could be copied to some general hostname-like field. (It could be covered by #12790)

**Comment by kaiyan-sheng** [comment]
@jsoriano Thanks for creating this issue! Is this for 7.x?

**Comment by jsoriano** [comment]
@kaiyan-sheng this would be nice to have soon, but not required for 7.0 as won't introduce breaking changes, this will only add new fields.

**Comment by ruflin** [comment]
I remember discussing this with @exekias and there was something like: kubernetes.container.id could be different from the container.id but don't remember why anymore.

**Comment by jsoriano** [comment]
@ruflin yes, it is different, but we could maybe use it to extract the runtime and the id in the runtime.

**Comment by ruflin** [comment]
SGTM

**Comment by exekias** [comment]
Let's move this one forward, specially for `container.id`, as this is the field used by Infra UI to link logs & metrics. That will make docker metrics correlate with kubernetes logs, for instance

**Comment by kaiyan-sheng** [comment]
I just realized I won't have the bandwidth to finish this for 7.5.0. Please feel free to pick it up and start working on it!
