### ISSUE TITLE
Jolokia autodiscover fields are not documented

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#10925]
As part of #10898 we tried to enable checks for documented fields also for Jolokia autodiscover provider, and we found that the fields injected by it are not documented.
```
'jolokia.agent.version' found in event is not documented
```
We should add them to some fields definition file. At the moment there are not fields definition files in autodiscover providers. Fields in other providers are covered by common docker and kubernetes fields, but this doesn't happen to Jolokia.

**Comment by kaiyan-sheng** [comment]
This error showed up after `self.assert_fields_are_documented(output[0])` is added into test.
