### ISSUE TITLE
Could not locate that index-pattern (id: winlogbeat-*), [click here to re-create it](#/management/kibana/index)

### ISSUE THREAD

**Issue by greenpau** [elastic/beats#10923]
Uploaded  `Winlogbeat-overview.json` dashboard that came with `winlogbeat-6.6.1-windows-x86_64.zip`:

```
wget https://artifacts.elastic.co/downloads/beats/winlogbeat/winlogbeat-6.6.1-windows-x86_64.zip
unzip winlogbeat-6.6.1-windows-x86_64.zip
cd winlogbeat-6.6.1-windows-x86_64/kibana/6/dashboard
curl -s --insecure -XPOST -H 'Content-Type: application/json' 'http://localhost:5601/api/kibana/dashboards/import' -H 'kbn-xsrf:true' -d@Winlogbeat-overview.json | python -m json.tool
```

When it gets loaded, I see the following error: `Could not locate that index-pattern (id: winlogbeat-*), [click here to re-create it](#/management/kibana/index)`

![image](https://user-images.githubusercontent.com/3826416/53304720-93cc0b80-3846-11e9-950f-ecba08d0afa7.png)

**Comment by greenpau** [comment]
The index pattern mentioned does exist:

![image](https://user-images.githubusercontent.com/3826416/53304952-4ef5a400-3849-11e9-9dca-a714678d93c0.png)

**Comment by jsoriano** [comment]
@greenpau how did you create this index pattern?

It can be that the index pattern has `winlogbeat-*` as name, but not as id. If you created the index patterns with `winlogbeat setup` they should have been created correctly.

To check if this is the problem, you can delete the index pattern and recreate it with `winlogbeat setup`, or manually with `winlogbeat-*` as name and as id. The id can be set in the advanced options when creating an index pattern.

**Comment by greenpau** [comment]
@jsoriano, 👍 Thank you for looking into this. I think my issues stem from the fact that I am not using `winlogbeat.exe` to do the setup. Closing this.
