### ISSUE TITLE
Filebeat Enhancement: Support reading from UNIX stream sockets

### ISSUE THREAD

**Issue by dcode** [elastic/beats#10934]
**Describe the enhancement:**
Similar to Filebeats support to read from a TCP socket, it would be very helpful to read from a UNIX stream socket (optionally UNIX datagram sockets for more flexibility, I guess). 

**Describe a specific use case for the enhancement or feature:**
My particular use-case is to be able to read my Suricata eve.json file as a stream instead of paying penalty of disk I/O. However, this isn't an isolated feature. Many UNIX tools can optionally write to UNIX sockets as an output. Various syslog engines are especially prevalent examples. For my Suricata use-case, this means I don't have to worry about on-disk management of log files because the rather verbose JSON log won't be eating up all my storage. It also means that Suricata and Filebeat will not be competing for the disk IOPS (which can get contentious on a production sensor) since the stream will exist in memory.

**Comment by superdave** [comment]
This is also my exact use case. PRs welcome, I assume?

**Comment by novaksam** [comment]
I send DNS, TLS, HTTP and Fileinfo to Unix sockets to minimize wear on my SSD. This would be awesome, as I'm actively working on migrating to ECS.

**Comment by superdave** [comment]
Welp, this is about a year old. Maybe I should do something this week.

**Comment by superdave** [comment]
Ha, well, clearly that didn't happen. Maybe soon after I've cleared some of my queue.

**Comment by ljeromets** [comment]
+1 we would like to have this feature ^^

**Comment by superdave** [comment]
Oh, that's very exciting, thanks so much! I'll have to check it out soon.
