### ISSUE TITLE
Clearly state in the doc that topology is available for Packetbeat only

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#1095]
We need to make sure we are clear wherever we describe the network topology to indicate that it's only relevant for Packetbeat. (We mostly are, but there are a couple of places where we should clarify.)

Users are getting a bit confused because of the topology options come from libbeat and are shared across the Beats.

**Comment by ruflin** [comment]
I think that is not a documentation issue, but a code issue that must be resolved. See https://github.com/elastic/beats/issues/946

**Comment by dedemorton** [comment]
I'm closing this issue this since the problem will be resolved in the code fix.
