### ISSUE TITLE
Refactor Kubernetes performance metrics cache

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#10965]
Metricbeat module for kubernetes includes a cache for performance metrics that is used mostly to calculate percentages on memory and cpu usage. This cache maintains the container and node limits, values that are not collected by other performance metrics.

This cache expires values after they haven't been updated or read (https://github.com/elastic/beats/pull/10946) during a timeout currently set to 120 seconds.

The main problem with this is that metricsets with greater periods would be missing metrics, and they wouldn't be recovered unless pods or nodes are updated.

Some possible solutions for this:
* Allow cache consumers to set TTLs for the metrics they use.
* Implement mechanisms to retrieve the missing values.

I wouldn't consider this so urgent as I don't think that periods of more than 120 seconds are so usual, if they are, a quick workaround would be to increase the default timeout.

**Comment by alvarolobato** [comment]
The most problematic situation is already fixed here: https://github.com/elastic/beats/pull/10946 we will close this for now.
