### ISSUE TITLE
[BUG] add_cloud_metadata does not populate host.type correctly

### ISSUE THREAD

**Issue by webmat** [elastic/beats#10968]
On GCE, the `add_cloud_metadata` processor populates `host.type` with a value such as this

`projects/NNN/machineTypes/n1-standard-2`

In ECS, `host.type` is intended to be populated with short name like `n1-standard-2`. Not an account-specific or a fully qualified (e.g. regions / dc / resource) URI.

Could we adjust the processor to contain the short value?

**Comment by andrewkroh** [comment]
`add_cloud_metadata` doesn't populate `host.type`. However it does populate `cloud.machine.type` with a value that's very similar to what's given above. Additionally `cloud.availability_zone` is populated with `projects/111111111111/zones/us-east1-b`.

What we can do is trim the leading parts of those values for the GCE provider.
