### ISSUE TITLE
Document how datasets in the Auditbeat system module collect data

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#10970]
Here is a summary from @cwurm.

1. Host dataset works for Windows, macOS, and Linux and is using system APIs for the most part
2. Process dataset works for all three OS as well, and is using `/proc` on Linux, and system APIs on macOS and Windows
3. Package dataset (Homebrew on macOS, dpkg and rpm on Linux, no Windows support) is reading the package manager database files: parsing `/var/lib/dpkg/status` since it's a text file, using the Librpm API to read `/var/lib/rpm/*`, or parsing `/usr/local/Cellar` since it's mostly JSON
4. Socket is Linux only and gets its data from the Linux kernel netlink interface
5. Login is Linux only and reading `/var/log/wtmp` and `/var/log/btmp` (which are binary)
6. User is Linux only and reading `/etc/passwd`, `/etc/group`, and `/etc/shadow`, but using glibc APIs not directly reading them

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
