### ISSUE TITLE
Documentation clarification on how to properly enroll Beats Central Management with environment variables using sudo

### ISSUE THREAD

**Issue by joshjanoski** [elastic/beats#10997]
The documentation page and section I am looking to see enhanced is:

https://www.elastic.co/guide/en/beats/filebeat/current/enroll-beats.html#username-password-enrollment

I ran into an issue trying to enroll Beats into Beats Central Management using environment variables set in Ubuntu for the password. This wasn't working, and the issue turned out to be related to running the enroll command with sudo which isn't outlined in the above documentation link.  Since I had set the environment variable as the current user, then ran the enroll command using sudo, I needed to run it as sudo - E to preserve the environment variables. An example of the proper syntax when running as sudo with environment variables set would be:

`sudo -E filebeat enroll http://xyz.gov:5601 --username myuser --password env:VAR_NAME`

I was wanting to see if we could maybe add a note under this section that if the enroll command is being ran as sudo and an environment variable is being used for the password then the -E parameter may be needed for this to work. If you have any additional questions or need additional details regarding this doc change request, please let me know. Thank you!

**Comment by dedemorton** [comment]
Closing because Beats central management has been discontinued.
