### ISSUE TITLE
[Metricbeat] Enhance Consul Module

### ISSUE THREAD

**Issue by sayden** [elastic/beats#11021]
After merging https://github.com/elastic/beats/pull/8631 and set the foundations for the module, we need to keep adding metrics and try to enhance the module as much as possible.

Until now, the metrics we have added were rather basic, tyring to just establish foundation of the module to keep adding later. We already fetch this metrics

* consul.autopilot.healthy
* consul.runtime.alloc_bytes
* consul.runtime.total_gc_pause_ns
* consul.runtime.gc_pause_ns
* consul.runtime.total_gc_runs
* consul.runtime.num_goroutines
* consul.runtime.heap_objects
* consul.runtime.sys_bytes
* consul.runtime.malloc_count

While many more are available, it's unclear how they are fetched and accumulated by Consul. In order to avoid a never ending PR, we omitted the following metrics:

 * consul.raft.apply
 * consul.raft.commitTime

Further discussion is needed to establish an approach about how to fetch and store those metrics

**Comment by alvarolobato** [comment]
We need to discuss the approach here, given the problems with the counters reseting.

**Comment by odacremolbap** [comment]
we need some cluster related metrics indeed.
I'm not sure what counter reseting problem are we talking here, can you elaborate on it?
At first glance, local consul member metrics should be reset when the process is reset, sounds fair.

This sounds like an authoritative resource for gathering and using metrics:
https://learn.hashicorp.com/consul/day-2-operations/monitoring

**Comment by andresrc** [comment]
@sorantis maybe we could check what the next steps for this module are.

**Comment by sorantis** [comment]
@andresrc Consul docs for telemetry have a nice categorization for metrics. Right now the immediate step would be to add the necessary functionality to move the module to GA and the list of [Key Metrics](https://www.consul.io/docs/agent/telemetry.html) looks like the right pick for it. The module dashboard needs to be updated accordingly. 
Going forward we will expand the module with more specific metrics, depending on requests.
