### ISSUE TITLE
ES/Logstash log modules use wrong field to convert timezone

### ISSUE THREAD

**Issue by LoadingZhang** [elastic/beats#11055]
- Version: Filebeat 6.6.1
I see ES/Logstash pipeline use `event.timezone` to convert timezone, but acutlly only `beat.timezone` added to ES, so default pipleline can not execute date processor.
see the [pipeline code](https://github.com/elastic/beats/blob/b652c6480f244d3c83f21c386334bcf5aa9c3bf0/filebeat/module/elasticsearch/server/ingest/pipeline.json#L64)

**Comment by andrewkroh** [comment]
We use `event.timezone` for 7.0+. So probably something got backported without being adjusted for 6.x.

**Comment by cachedout** [comment]
I think this is the same as https://github.com/elastic/beats/pull/9797

**Comment by ycombinator** [comment]
Resolved via https://github.com/elastic/beats/pull/11164.
