### ISSUE TITLE
Split the Elasticsearch output and the Elasticsearch client

### ISSUE THREAD

**Issue by ph** [elastic/beats#11068]
Linked to https://github.com/elastic/beats/issues/10547 and https://github.com/elastic/beats/issues/10491

--- 

We have found a few issues concerning output reloading triggered by a CM changes, the problem is we have a hard time to make the fix because the code of the Elasticsearch output is also used in other places in the code base for servers request, like uploading templates, uploading pipeline, checking for license.

We have decided to do the following steps:
- Extract the API layer in a `esclientleg` AKA Legacy
- Simplify the Elasticsearch output by only having the related code for publishing events and closing the output.
- Give us a migration path to the official ES golang client.

**Comment by andresrc** [comment]
@ycombinator what's missing to close this one?

**Comment by ycombinator** [comment]
This is done now, via https://github.com/elastic/beats/pull/16150.
