### ISSUE TITLE
[Metricbeat] Improve / add integration tests of Ceph

### ISSUE THREAD

**Issue by sayden** [elastic/beats#11080]
In its current state Ceph module doesn't have any integration tests because Ceph containers take too long to start: over 1 minute in most situations and more than 5 even sometimes, producing a flaky test because `compose.EnsureUp` function we use defaults to 5 minutes. Probably, it has some problem if it reaches 5 minutes for starting up that wouldn't allow it to ever start properly.

`TestData` must be manually skipped for the same reason as it tries to reach the server that is not started as described here https://github.com/elastic/beats/pull/10990#discussion_r262406519 and here https://github.com/elastic/beats/pull/10993#discussion_r261627931

As soon as we have this merged https://github.com/elastic/beats/pull/10648 the module should be more friendly to add those tests.

**Comment by mtojek** [comment]
I think we can resolve this one. There are multiple integration tests and system tests verifying metrics collection.

Resolving
