### ISSUE TITLE
[Flaky Test] Panic on elasticsearch_integration_test

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#11109]
## Flaky Test

* **Test Name:** elasticsearch_integration_test.go
* **Branch:** 7.0
* **Artifact Link:** https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/5687/beat=metricbeat,label=linux-immutable/console
* **Notes:** It seems like the enabling of the trial caused some errors which then further down caused a null pointer exception. Perhaps ES was not available properly?

### Stack Trace

```
17:54:35 --- FAIL: TestFetch (74.43s)
17:54:35 	assertions.go:256: 
17:54:35 			Error Trace:	elasticsearch_integration_test.go:75
17:54:35 			Error:      	Received unexpected error:
17:54:35 			            	Post http://elasticsearch:9200/_xpack/license/start_trial?acknowledge=true: EOF
17:54:35 			Test:       	TestFetch
17:54:35 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
17:54:35 	panic: runtime error: invalid memory address or nil pointer dereference
17:54:35 [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa2f906]
17:54:35 
17:54:35 goroutine 18 [running]:
17:54:35 testing.tRunner.func1(0xc42035a0f0)
17:54:35 	/usr/local/go/src/testing/testing.go:742 +0x567
17:54:35 panic(0xac1300, 0xe882d0)
17:54:35 	/usr/local/go/src/runtime/panic.go:502 +0x24a
17:54:35 github.com/elastic/beats/metricbeat/module/elasticsearch_test.createMLJob(0xc4201d21e0, 0x12, 0xc420360400, 0xc4201379e0, 0x0)
17:54:35 	/go/src/github.com/elastic/beats/metricbeat/module/elasticsearch/elasticsearch_integration_test.go:230 +0x1e6
17:54:35 github.com/elastic/beats/metricbeat/module/elasticsearch_test.TestFetch(0xc42035a0f0)
17:54:35 	/go/src/github.com/elastic/beats/metricbeat/module/elasticsearch/elasticsearch_integration_test.go:77 +0x2c7
17:54:35 testing.tRunner(0xc42035a0f0, 0xb73ff0)
17:54:35 	/usr/local/go/src/testing/testing.go:777 +0x16e
17:54:35 created by testing.(*T).Run
17:54:35 	/usr/local/go/src/testing/testing.go:824 +0x565
17:54:35 FAIL	github.com/elastic/beats/metricbeat/module/elasticsearch	74.545s```

**Comment by fearful-symmetry** [comment]
So TIL that [testify.assert](https://github.com/elastic/beats/blob/master/metricbeat/module/elasticsearch/elasticsearch_integration_test.go#L77) just calls `T.Errorf()` which will mark the test as failed but continue execution. [Here](https://github.com/elastic/beats/blob/master/metricbeat/module/elasticsearch/elasticsearch_integration_test.go#L230) we might want to test the error before grabbing a value from the `*http.Response` pointer.

This has nothing to do with ES giving back the EOF, but we might want this to fail a bit more elegantly?

**Comment by fearful-symmetry** [comment]
Oop. It looks like the err check is in the master branch, but I don't see it in [7.0](https://github.com/elastic/beats/blob/7.0/metricbeat/module/elasticsearch/elasticsearch_integration_test.go#L228)

**Comment by fearful-symmetry** [comment]
Looks like this was fixed by  #10874 in master.

**Comment by ruflin** [comment]
Will keep the issue open as hopefully #10874 will give us at least some better info.

**Comment by mtojek** [comment]
Stale, resolving
