### ISSUE TITLE
Problems with the beat generator and mage

### ISSUE THREAD

**Issue by richbai90** [elastic/beats#11137]
I ran into this issue while following the guide to make a beat. I looked around the internet and found the solution on the discuss forum. The solution posted there fixed my issue as well, so it seem like it's still a problem. I am opening this issue to see about getting it fixed or the documentation updated.

Please include configurations and logs if available.

```
$ python $GOPATH/src/github.com/elastic/beats/script/generate.py
Beat Name [Examplebeat]:
Your Github Name [your-github-name]: richbai90
Beat Path [github.com/richbai90/examplebeat]:
Firstname Lastname: Rich Baird
$ cd examplebeat/
$ python --version
Python 2.7.16
$ virtualenv --version
16.4.3
$ make setup
...
make[1]: *** No rule to make target `../dev-tools/make/mage.mk'.  Stop.
make: *** [pre-setup] Error 2
```

For confirmed bugs, please report:
- Version: latest? -- I'll update this when I know how to get that info
- Operating System: MacOS 10.13.6
- Discuss Forum URL: https://discuss.elastic.co/t/please-help-create-new-beats/163560
- Steps to Reproduce: Follow the guide on the official documentation https://www.elastic.co/guide/en/beats/devguide/current/newbeat-generate.html and run make setup

**Comment by fearful-symmetry** [comment]
I was able to reproduce this. So, I suspect that the problem is in the generated Makefile that's put in the [custom beat directory](https://github.com/elastic/beats/blob/master/generator/beat/%7Bbeat%7D/Makefile) here:

```
ES_BEATS?=./vendor/github.com/elastic/beats
```

This includes the libbeat Makefile, which has this helpful comment, attached to the same variable name:

```
ES_BEATS?=..## @community_beat Must be set to ./vendor/github.com/elastic/beats. It must always be a relative path.
```

If you change the custom beat makefile to export the variable:

```
export ES_BEATS?=./vendor/github.com/elastic/beats
```
everything seems to work.  However, I am by no means a makefile expert.

**Comment by andrewkroh** [comment]
Looking at the Makefile you linked to I see that it uses

`$(MAKE) ...`

when this occurs it's starting a new make process. That new process will not have the ES_BEATS variable unless it gets exported. So I'd say adding `export ES_BEATS` somewhere in the makefile is the right thing to do.
