### ISSUE TITLE
[Metricbeat][Discuss] Separate inputs and modules

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#11132]
Today we have two kind of modules: 

* Modules which produce a predefined data structure like Apache or MySQL
* Modules which pull or get data pushed and we don't know about the structure in advance like Prometheus, Munin or Http.

Already today modules are built on top of these more generic modules. Most http modules have the same foundation. In Filebeat there are inputs and modules today with the distinction that inputs are more generic and modules provide and out of the box experience.

I would propose to also start this separate in Metricbeat. Http, prometheus, munin and a few others should become an inputs. For inputs the data format is not know in advance and no dashboards are provided. For modules the exact data structure is known and the user gets an out of the box experience.

In the future most modules should be built on top of the inputs we have. The http input would serve as a foundation for all the http based modules. This could potentially allow us at some point to make these modules pure config based.

Configuration wise I would follow the same scheme we already have in Filebeat:

```
metricbeat.inputs:
- type: http
  ...
```

**Comment by fearful-symmetry** [comment]
I think this is a step in the right direction, as I imagine it would simplify a lot of code infrastructure, testing, etc. as well as making things more generic. 

This might also allow users to add support for their own metrics with just config work. From my time in the embedded/bare metal space, you'd be _amazed_ at how many vendors just say "Here's an http endpoint with some json/a postgres database/a kafka endpoint/whatever!" and let the users do the rest. Letting users turn that into meaningful data gathering using just configs could be really cool.

>  For modules the exact data structure is known and the user gets an out of the box experience.

This is going to be true for a lot of things, but not everything. I imagine there's lots of services out there that spit out arbitrary json and such, as well as odd, vendor-specific things. SNMP for example: OIDs like IP data (.1.3.6.1.2.1.4 or whatever) are fairly standard, but my UniFi AP at home has a special set of OIDs that are vendor-specific and well, who knows how that'll change. 

I can see a future where we have inputs like http/snmp/whatever where metricsets based on them are entirely config-defined, as you say, and users can add to them with relative ease. 


Here's another fun avenue of exploration: If we have inputs that can do the actual data gathering work, can we use that to generate the configs you talk about?

I'm thinking like this:
- User runs something like `$ metricbeats input setup http --data json --endpoint $ENDPOINT --name my_http_service`
- metricbeat scrapes that endpoint multiple times, gets some data.
- We look at multiple data scrapes to see if there are mapping conflicts (i.e. json key `user` is a string in one GET, an int in another) and to protect against services where certain fields aren't present 100% of the time)
- metricbeat generates the config, mapping, types, and so on.
- user is prompted to look it over, add docs, edit as needed.

**Comment by ruflin** [comment]
For the config generation: Definitively an interesting idea, especially the template part. There are similar things in the work for Filebeat. ML has some capabilities now to detect grok patterns. These could also be used to generate templates.
