### ISSUE TITLE
MetricBeat support for additional configs

### ISSUE THREAD

**Issue by vjsamuel** [elastic/beats#1116]
It would be good if there is a feature in the metric module config where I have some custom configurations that the module could use. For instance if there is some additional info that my module needs to send as part of the JSON payload to ES like the environment that the server belongs to.

**Comment by ruflin** [comment]
That is definitively a must. I think there are two points here:
* Adding support for fields for each module (same as we have in filebeat)
* Support for dynamic config options per module. I was waiting here for the implementation of ucfg. Now that we have it in the repo and already implemented in packetbeat, it is time to add it https://github.com/elastic/beats/pulls?q=is%3Apr+ucfg+is%3Aclosed

I will ping you here as soon as this is added also providing an example.

**Comment by vjsamuel** [comment]
Thanks!

**Comment by ruflin** [comment]
Support for fields and ucfg can be found here: https://github.com/elastic/beats/pull/1119

This also adds ucfg as part of  the setup method in moduler which allows to process additional configurations. So far there is no example. It should already work but I will also add an example so it is easier to understand how it works.

**Comment by vjsamuel** [comment]
Thank you. Let me give it a try.

**Comment by ruflin** [comment]
Module and metricset specific configurations are now also implemented with ucfg. For an example see redis-info: https://github.com/elastic/beats/blob/master/metricbeat/module/redis/info/info.go#L33

Based on this closing this issue. Let me know if there is a need for more custom data.
