### ISSUE TITLE
[Metricbeat] clean up behavior of uwsgi/status metricset

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#11162]
This came out of a discussion with @ruflin and following my migration of the uwsgi/status metricset to ReporterV2. He asked me to open a separate issue.

It appears as though there's a lot of weird behavior [in the module](https://github.com/elastic/beats/tree/master/metricbeat/module/uwsgi) that we might want to rectify.

- [The metricset sends three different kinds of events](https://github.com/elastic/beats/blob/master/metricbeat/module/uwsgi/status/data.go). A worker event, a core event, and a total event. These are somewhat hierarchical: totals represent one "scrape" of the uwsgi endpoint, a scrape has _n_ workers and each worker has _n_ cores. @ruflin was concerned that we were sending events from one metricset with wildly different data structures. 
- [Many of the unit tests seem unnecessary](https://github.com/elastic/beats/blob/master/metricbeat/module/uwsgi/status/status_test.go) and are probably too tightly coupled to the underlying implementation

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
