### ISSUE TITLE
Filebeat field generated based on file inode/UID

### ISSUE THREAD

**Issue by pedrosk** [elastic/beats#11169]
**Desc**Describe the enhancement:**

I unique ID to be created based on the file / inode id. 

The idea is to capture some information that would track the uniqueness of a files on disk, inode + volume id. Target would be to generate an ID with that + maybe the create date of the file, that could be loaded into a field.

**Describe a specific use case for the enhancement or feature:**
An ETL creates a log. Every-time the ETL  code runs, which runs every few minutes, it  deletes the log files and starts a new log file with the same name. Looking to capture a unique id based on the file UID. The purpose is to differentiate which document the date originated from -- in which ETL run. 
So it can queried based on the generated unique  ID --> retrieve all the documents generated by a specific run.

Thanks

Ed

**Comment by ph** [comment]
Maybe linked to #11173

**Comment by matschaffer** [comment]
Would be a good feature to help eliminate possibly of duplicate records stored in the event of partial failure & retry.
