### ISSUE TITLE
Replace string mappings through text / keyword for ES 5.0

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#1117]
In ES 5.0 string type will be removed: https://github.com/elastic/elasticsearch/pull/16877

Several mappings in the beats depend on string. This must be changed.

**Comment by tsg** [comment]
This is a blocker for 5.0 alpha1, from the Beats POV. I posted a ticket to Elasticsearch here: https://github.com/elastic/elasticsearch/issues/17241

To me it seems that we might have to generate exact mappings for the fields we have, rather than rely on dynamic mappings.

**Comment by jpountz** [comment]
Should it be closed now that #1221 is merged?

**Comment by tsg** [comment]
Yep, thanks @jpountz
