### ISSUE TITLE
filebeat 6.6.2 on redhat5.4 can not work

### ISSUE THREAD

**Issue by czq5783095** [elastic/beats#11220]
OS ENV：
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 5.4 (Tikanga)

uname -r
2.6.18-164.el5

Filebeat version：
6.6.2

when i run cmd：./filebeat -e -c ./filebeat.yml , i got those info：
runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x179661c, 0x17)
/usr/local/go/src/runtime/panic.go:616 +0x81
runtime.netpoll(0x158b63a61a3a5000, 0x0)
/usr/local/go/src/runtime/netpoll_epoll.go:75 +0x216
runtime.sysmon()
/usr/local/go/src/runtime/proc.go:4265 +0x424
runtime.mstart1(0x0)
/usr/local/go/src/runtime/proc.go:1227 +0xe7
runtime.mstart()
/usr/local/go/src/runtime/proc.go:1193 +0x76

goroutine 1 [runnable, locked to thread]:
regexp/syntax.(*Regexp).Simplify(0xc42032aa10, 0xc42032a930)
/usr/local/go/src/regexp/syntax/simplify.go:99 +0xb19
regexp/syntax.(*Regexp).Simplify(0xc42032aa80, 0x2)
/usr/local/go/src/regexp/syntax/simplify.go:23 +0xc0
regexp/syntax.(*Regexp).Simplify(0xc42032a8c0, 0xc42000df40)
/usr/local/go/src/regexp/syntax/simplify.go:23 +0xc0
regexp.compile(0xc4202e5480, 0x13, 0xd4, 0x13, 0xc4202e5480, 0x13)
/usr/local/go/src/regexp/regexp.go:177 +0xb9
regexp.Compile(0xc4202e5480, 0x13, 0x1, 0x2, 0xc4202e5480)
/usr/local/go/src/regexp/regexp.go:133 +0x41
regexp.MustCompile(0xc4202e5480, 0x13, 0x1)
/usr/local/go/src/regexp/regexp.go:238 +0x4d
github.com/elastic/beats/vendor/github.com/docker/distribution/reference.capture(0xc42000e2c8, 0x1, 0x1, 0xc4202f5d60)
/go/src/github.com/elastic/beats/vendor/github.com/docker/distribution/reference/regexp.go:137 +0xb9

goroutine 5 [syscall]:
os/signal.signal_recv(0xc420078fc8)
/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

Please help me，my os server couldn't upgrade!
Thanks!

**Comment by kvch** [comment]
Please first submit a question on Discuss: https://discuss.elastic.co/c/beats
GH issues are reserved for verified bugs only.
