### ISSUE TITLE
Some extra fields under kubernetes.replicaset seem to be missing

### ISSUE THREAD

**Issue by alakahakai** [elastic/beats#11222]
We can see some fields in libbeat/kibana/testdata/extensive/fields.yml:

        - name: replicaset
          type: group
          description: >
            kubernetes replica set metrics
          fields:
            - name: name
              type: keyword
              description: >
                Kubernetes replica set name
            - name: replicas
              type: group
              description: >
                Kubernetes replica set paused status
              fields:
                - name: available
                  type: long
                  description: >
                    The number of replicas per ReplicaSet
                - name: desired
                  type: long
                  description: >
                    The number of replicas per ReplicaSet
                - name: ready
                  type: long
                  description: >
                    The number of ready replicas per ReplicaSet
                - name: observed
                  type: long
                  description: >
                    The generation observed by the ReplicaSet controller
                - name: labeled
                  type: long
                  description: >
                    The number of fully labeled replicas per ReplicaSet

But they are not defined in the libbeat fields.yml. Open this PR to track this problem.

Notice that kubernetes.replicaset.name is addressed by PR #11133.

**Comment by odacremolbap** [comment]
hi @alakahakai 

I'm trying to understand this, and currently tracing the code around `add_kubernetes_metadata` processor.

It is still not clear to me what is missing.
Are we retrieving some fields using the processor that do not show at the `/kibana/testdata/extensive/fields.yml` you reference above?

> But they are not defined in the libbeat fields.yml. Open this PR to track this problem.

you mean this file: https://github.com/elastic/beats/blob/master/libbeat/processors/add_kubernetes_metadata/_meta/fields.yml

contains (or should contain) some fields that are missing at the kibana tests yaml?

I'll continue tracing the code, but sure some clarifications will be a time saver.
Thanks!

**Comment by alakahakai** [comment]
We have added the missing fields in libbeat - pull [#11134](https://github.com/elastic/beats/pull/11134). This issue can be closed.
