### ISSUE TITLE
Cannot select host on System Overview [Metricbeat system + Kibana dashboard]

### ISSUE THREAD

**Issue by akhamar** [elastic/beats#11246]
Hi,

I've just installed a full ELK from scratch under the version 6.6.1 (updated to 6.6.2, but the bug was present on 6.6.1). I'm using metricbeats and the dashboard, especially the system one.
When I'm on the "[Metricbeat System] Overview" dashboard I'm getting all the information needed per Hosts. But as soon as I double click (choose) an Host, I'm redirected to the "[Metricbeat System] Host overview" dashboard without the Host filtered. That mean all Hosts are aggregated on this page.
As per the metricbeats documentation explain, I should been able to be redirected to this page filtering the Host I just choose.

You can find more information in forum : [post](https://discuss.elastic.co/t/cannot-select-host-on-system-overview-after-upgrade-to-6-6-0/166642)

Regards.

**Comment by ruflin** [comment]
This seems to be an issue in Kibana: https://github.com/elastic/kibana/issues/31060 and a PR for a fix is open here: https://github.com/elastic/kibana/pull/33276

**Comment by lukasolson** [comment]
Just for the record, the fix relies on both https://github.com/elastic/kibana/pull/33074 and https://github.com/elastic/kibana/pull/33276.

**Comment by ruflin** [comment]
I tested this on the most recent snapshot of the 6.x (6.7.2 snapshot) Elastic Stack and things now seem to work as expected. Closing.
