### ISSUE TITLE
packer / xgo-image-deb6: docker image can't be built locally / libpcap0.8-dev_1.1.1-2+squeeze1_amd64.deb  removed from ftp.debian.org

### ISSUE THREAD

**Issue by cyrilleverrier** [elastic/beats#1125]
- Version: libbeat from master
- Operating System: Ubuntu
- Steps to Reproduce: 

```
$ cd <mybeat_path>/vendor/github.com/elastic/beats/dev-tools/packer/docker/xgo-image-deb6
$  docker build beats-builder 

Sending build context to Docker daemon 4.096 kB
Step 1 : FROM tudorg/xgo-deb6-1.6
 ---> 10822c2789e1
Step 2 : MAINTAINER Tudor Golubenco <tudor@elastic.co>
 ---> Using cache
 ---> c4716328c6a8
Step 3 : RUN mkdir -p /libpcap &&     wget http://ftp.de.debian.org/debian/pool/main/libp/libpcap/libpcap0.8-dev_1.1.1-2+squeeze1_i386.deb && 	dpkg -x libpcap0.8-dev_*_i386.deb /libpcap/i386 && 	wget http://ftp.de.debian.org/debian/pool/main/libp/libpcap/libpcap0.8-dev_1.1.1-2+squeeze1_amd64.deb && 	dpkg -x libpcap0.8-dev_*_amd64.deb /libpcap/amd64 && 	rm libpcap0.8-dev*.deb
 ---> Running in b4e8ff07a8ce
--2016-03-08 08:23:26--  http://ftp.de.debian.org/debian/pool/main/libp/libpcap/libpcap0.8-dev_1.1.1-2+squeeze1_i386.deb
Resolving ftp.de.debian.org... 141.76.2.4
Connecting to ftp.de.debian.org|141.76.2.4|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-08 08:23:26 ERROR 404: Not Found.
```

@tsg : AFAIK, the docker images with Go 1.6 are not pushed to docker hub, are they?

**Comment by andrewkroh** [comment]
Have you updated your vendored `elastic/beats` to include https://github.com/elastic/beats/pull/1097 ? It looks like you have since it's pulling a Go 1.6 image.

**Comment by cyrilleverrier** [comment]
@andrewkroh Yes I did and got this problem.
Can you reproduce it on your side?

**Comment by andrewkroh** [comment]
Yeah, I just cleaned my images and tried re-building and got the same error.

**Comment by tsg** [comment]
@cyrilleverrier A fix for this is coming with: https://github.com/elastic/beats/pull/1140/files#diff-70c6d2f3ebcd954957f38cad208d31eaR8

Debian Squeeze got EOL a couple of weeks back, and now some of the resources started to disappear on us.

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/beats/pull/1140 was merged.
