### ISSUE TITLE
beats setup should show username:password options and add to docs

### ISSUE THREAD

**Issue by LeeDr** [elastic/beats#11264]
**Describe the enhancement:** 
1. make `*beat setup --help` show how to pass a username and password as arguments to be used only for that setup action.
2. Document to run the setup with a username and password on the command line.

**Describe a specific use case for the enhancement or feature:**

It seems the `output.elasticsearch.username:` config parameter should generally be set to limit privileges to that required to write data to that specific beat index pattern.

But to run `setup`, additional privs are required.  And if ILM is enabled (automatically in some cases) then even more privs are required.  

Best security practice would be to run the setup step with a user who does have the required privs, but not leave that user as the configured `output.elasticsearch.username:` in the yml file.

**Comment by dedemorton** [comment]
@elastic/beats I'm working on doc changes right now that should address some of Lee's concerns, but I'm not sure what we should do about the command line help. The help does show -E for config overrides, but new users are unlikely to know what that means.  We also don't want to mislead users by showing them examples that pass credentials in plain text. Thoughts?

**Comment by dedemorton** [comment]
I'm closing this issue because I think we've addressed the concerns that prompted it (clarify around which privileges are required for users who set up vs run a Beat:

https://www.elastic.co/guide/en/beats/filebeat/current/feature-roles.html

Passing credentials through the command line is not considered a best practice AFAIK.
