### ISSUE TITLE
Include Apache (httpd) v2.4.6 as a supported version of Apache Metricbeat Module

### ISSUE THREAD

**Issue by itlevel3** [elastic/beats#11262]
It seems that v2.4.6 is the default version installed in CentOS. Would be nice if the built-in Metricbeat Apache module would support this version. Currently the documentation shows it supports versions >= 2.4.16.

**Comment by ruflin** [comment]
Initial discussion happened here: https://discuss.elastic.co/t/metricbeat-apache-module-error-message-http-error-404-in-status-404-not-found/169911/8

**Comment by itlevel3** [comment]
I believe I may have found the issue. It appears that my virtual host was not responding to requests on localhost which is the default "host" in the Apache module. I changed it to the specific virtual host and I am now getting stats info in Kibana.
Sorry for that.
However, it is nice to verify and confirm that it does in fact work with versions of Apache 2.4.6

**Comment by ruflin** [comment]
@itlevel3 Thanks for testing further. I assume that means we can close this? I hope we can add testing for 2.4.6 in the near future and make it "officially" supported.

Please reopen if the above is not the case.
