### ISSUE TITLE
[Docs] Clarify getting started exceptions when using Logstash

### ISSUE THREAD

**Issue by cjcenizal** [elastic/beats#11276]
The current "Getting started" docs provide guidance on [loading the index template into Elasticsearch](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-template.html), but largely from the perspective of users who have configured Metricbeat to ship directly to ES.

When I ran through this tutorial, I was testing the full stack, with Metricbeat configured to ship to Logstash. The linked docs state:

>  If you accept the default configuration in the metricbeat.yml config file, Metricbeat loads the template automatically after successfully connecting to Elasticsearch.

When I read this, I saw the initial statement about "default configuration" and missed the nuance regarding "connecting to Elasticsearch" at the end. Because I was new to the stack, I assumed that because I hadn't changed much in the config file, I was still basically using the default config. Of course I was mistaken... 😄  The index template never loaded, so my dashboards were broken and I couldn't understand why.

I think we could resolve this problem by make the docs explicitly state something like this:

> The recommended index template file for Metricbeat is installed by the Metricbeat packages. If your metricbeat.yml config file is configured to connect directly to Elasticsearch, then Metricbeat automatically loads the index template into Elasticsearch for you. If the template already exists, it’s not overwritten unless you configure Metricbeat to do so.
> However, if you have metricbeat.yml configured to connect to something else, such as Logstash or Kafka, then you will need to manually setup the index template using the command line (see below).
> Whichever path you take, you can verify the metricbeat index template has been set up by running `GET _template/metricbeat*` in Kibana's Dev Tools. You should see an index template with an index pattern that will match the indices you're ingesting.

And then on the [Kibana dashboards step](https://www.elastic.co/guide/en/beats/metricbeat/current/load-kibana-dashboards.html), it would be helpful to state something in an info box like this:

> **Not seeing data in the sample dashboards?** If the dashboard panels are showing errors, then you may need to set up the metricbeat index template (link to previous step).

**Comment by cjcenizal** [comment]
CC @ruflin

**Comment by cjcenizal** [comment]
Additionally, in the [beats upgrade docs](https://www.elastic.co/guide/en/beats/libbeat/6.6/upgrading-minor-versions.html) we should clarify that users need to re-setup the index template in order for the sample dashboards to be updated with data ingested after upgrading.

**Comment by cjcenizal** [comment]
### Multi-node clusters are special exceptions

The "Getting started" docs also assume that the user is on a single-node cluster, since the index template defaults to setting `number_of_shards` to 1. We might want to point out that the user should either 1) update the config file with a higher `number_of_shards` value or b) provide a command line flag to increase this number, if their cluster contains multiple nodes.

**Comment by dedemorton** [comment]
@alvarolobato This content is in libbeat so probably should not be labeled "Infrastructure".
