### ISSUE TITLE
[Filebeat/MongoDB] Add support to new MongoDB additional diagnostic information 

### ISSUE THREAD

**Issue by gemaliano** [elastic/beats#11287]
**Describe the enhancement:**
Filebeat using MongoDB Module.
MongoDB has added a lot of additional diagnostic information since v3.6.x, with specific reference to the replication feature, which the current filebeat pattern (including filebeat 6.6.2) does not capture.

**Describe a specific use case for the enhancement or feature:**
Log line:
```2019-03-07T15:10:26.960+0000 I ASIO [NetworkInterfaceASIO-Replication-0] Successfully connected to dbbox7:27017, took 10ms (1 connections now open to dbbox7:27017)```
Grook pattern:
```%{TIMESTAMP_ISO8601:mongodb.log.timestamp}%{SPACE}%{MONGO3_SEVERITY:mongodb.log.severity}%{SPACE}%{MONGO3_COMPONENT:mongodb.log.component}%{SPACE}(?:\\[%{DATA:mongodb.log.context}\\])?%{SPACE}%{GREEDYDATA:mongodb.log.message}```

This grok pattern is present in:
https://github.com/logstash-plugins/logstash-patterns-core/blob/master/patterns/mongodb

**Comment by sayden** [comment]
@ruflin if you think is ok, I'll self-assign this one because I already have some task that involves Mongo here https://github.com/elastic/beats/issues/10793 Feel free to reassign it if you have other plans
