### ISSUE TITLE
Journalbeat in kubernetes not reporting the source host information

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/beats#11310]
- Version: 6.6.1
- Operating System: GKE Kubernetes
- Steps to Reproduce: Deploy with manifest included below and view records.  There is no field containing the source of the journals, only the info for the pod where the Journalbeat is deployed.

**Comment by DanRoscigno** [comment]
[journalbeat-kubernetes.yaml.txt](https://github.com/elastic/beats/files/2984025/journalbeat-kubernetes.yaml.txt)

**Comment by DanRoscigno** [comment]
more info @kvch : 
I tried 7.0.0-beta1 and the source hostname is in host.hostname, which is helpful, I can modify the saved searches to show host.hostname instead of host.name

But, I would really like to be able to add the journalbeat index pattern to the list of patterns for the Logs UI and bring up the journals in the Logs UI.  The launch from the Infrastructure UI to the Logs UI (at least in 6.6.1) is populating the search bar in the Logs UI with host.name:

<img width="1212" alt="Screen Shot 2019-03-19 at 10 57 49 PM" src="https://user-images.githubusercontent.com/25182304/54656223-30c34280-4a9b-11e9-9811-4e1c88b62204.png">

**Comment by timp87** [comment]
This is still true for 6.8.x, but not for at leat 7.6.x

**Comment by jlind23** [comment]
Hello @DanRoscigno  

As of 7.16 journald is provided as an input to Filebeat: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-journald.html which supports multi-line. Consequently journalbeat has been deprecated from that release onwards.

cc @kvch
