### ISSUE TITLE
Resources leaks when checking configs

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#11313]
Libbeat's config reloading code can leak `Runner` instances when executing its [`Check`](https://github.com/elastic/beats/blob/master/libbeat/cfgfile/reload.go#L112) method.

The root cause is that the `Check` method invokes `RunnerFactory.Create`, instead of `RunnerFactory.CheckConfig`. `Create` returns a runner. If this runner allocates any resources that are not GC-able they will not be freed since `Check` never invokes `Stop()` on the returned `Runner`.

This originally came up in https://github.com/elastic/beats/pull/11165 , since Heartbeat 7 now allocates some global state when new `Runner` instances are created. That PR contains a hacky fix, invoking `Stop()` on the returned `Runner` instance in `libbeat`'s reload code.

In an ideal world we would invoke `CheckConfig`, however there are a [number](https://github.com/elastic/beats/blob/master/filebeat/fileset/factory.go#L120) of [places](https://github.com/elastic/beats/blob/master/filebeat/input/runnerfactory.go#L60) where that is not implemented. Even where it is, since it is not invoked, we need to validate the behavior.

After discussing this with @ph and @ruflin we've discussed that we need a better fix.

One proposed solution is to change the `RunnerFactory` interface to:

```go
type RunnerFactory interface {
        // Used to be Create(p beat.Pipeline, config *common.Config, meta *common.MapStrPointer) (Runner, error)
	Create(config *common.Config) (Runner, error)
	CheckConfig(config *common.Config) error
}
```

and to add the `pipeline` and `meta` variables as arguments to `Runner.Start`, since those shouldn't be required to instantiate a runner.

**Comment by ruflin** [comment]
@vjsamuel Pinging you on this one as I see you were involved in https://github.com/elastic/beats/pull/7961 where this TODO's were initially introduced :-)

**Comment by vjsamuel** [comment]
The initial implementation was done the described way for the exact reason that was mentioned. Many places don’t implement check config and it was just too much work. I would agree that the above change is the right foot forward. We should also try to implement check config across the board and not rely on creating runners. Heartbeat is code I am unfamiliar with and didn’t realize there are global states.
