### ISSUE TITLE
max_message_size is ignored for HTTP in Packetbeat

### ISSUE THREAD

**Issue by ifmusic** [elastic/beats#11326]
I'm using packetbeat for troubleshooting some apps. For this, I needed to turn on full payload packet capture. Some of the packets on the network are big pdf base64 streams, which I don't want to capture.
I'd like to limit the max capture size, however the  `max_messsage_size:` gets ignored.

- Version:  packetbeat version 6.6.2 (amd64), libbeat 6.6.2 
- Operating System:   Ubuntu 16.04.1 LTS
- Discuss Forum URL:
- Steps to Reproduce: 
This is my current config for HTTP:
` - type: http` 
`   max_messsage_size: 1024` 
`   send_request: true` 
`   send_response: true` 
`   real_ip_header: "X-Forwarded-For"` 
`   send_all_headers: true` 
`   transaction_timeout: 600` 
`   include_body_for: [""]` 
`   ports: [80]`

Any HTTP request/response gets fully captured and not capped to 1024 bytes.

Thanks!

**Comment by leopucci** [comment]
Hi!
**Any HTTP request/response gets fully captured and not capped to 1024 bytes.**

You are using send_request: true and send_response: true (https://www.elastic.co/guide/en/beats/packetbeat/6.2/packetbeat-http-options.html#_literal_include_body_for_literal)

max_messsage_size will not be used if you want request and response to be sent!

If you want the body to be exported, you can try to filter based on type:
include_body_for: ["text/html"]

try these ones:

```
- type: http
max_messsage_size: 1024
send_request: true
send_response: true
real_ip_header: "X-Forwarded-For"
send_all_headers: true
transaction_timeout: 600
include_body_for: ["text/html"]
ports: [80]
```


- type: http
max_messsage_size: 1024
real_ip_header: "X-Forwarded-For"
send_all_headers: true
transaction_timeout: 600
ports: [80]

**Comment by leopucci** [comment]
@andrewkroh @ruflin this seems to be by design to me. 

https://github.com/elastic/beats/commit/26acf4313e4ed32ad88e907f5575d15e5f56ce0b#diff-a8a2d3e966bf5dae5ccd16c8ee77cf30R292

**Comment by ifmusic** [comment]
> 
> 
> Hi!
> **Any HTTP request/response gets fully captured and not capped to 1024 bytes.**
> 
> You are using send_request: true and send_response: true (https://www.elastic.co/guide/en/beats/packetbeat/6.2/packetbeat-http-options.html#_literal_include_body_for_literal)
> 
> max_messsage_size will not be used if you want request and response to be sent!
> 
> If you want the body to be exported, you can try to filter based on type:
> include_body_for: ["text/html"]
> 
> try these ones:
> 
> filtering body for text/html only if mime type is correct (application/pdf) will filter out pdfs.
> 
> ```
> - type: http
> max_messsage_size: 1024
> send_request: true
> send_response: true
> real_ip_header: "X-Forwarded-For"
> send_all_headers: true
> transaction_timeout: 600
> include_body_for: ["text/html"]
> ports: [80]
> ```
> 
> This config should trim on 1024 bytes, but take a look on mime type, I think that the first one will help you.
> 
> ```
> - type: http
> max_messsage_size: 1024
> real_ip_header: "X-Forwarded-For"
> send_all_headers: true
> transaction_timeout: 600
> ports: [80]
> ```

Hi! I need to be able to capture full packets without  setting the "Content-Type", since I could be sending SOAP requests, RESTs (to some services or elasticsearch instances), etc.
That's why I left the `include_body_for: [""]` blank.

And I'm trying to cap the max packet with `max_messsage_size` in case a big stream in base64 (some file download for example) goes through the wire (I don't want big pdf files stored in elasticsearch...)

(I tried both options you suggested, but it was a no go.. :( )

> 
> 
> @andrewkroh @ruflin this seems to be by design.
> 
> [26acf43#diff-a8a2d3e966bf5dae5ccd16c8ee77cf30R292](https://github.com/elastic/beats/commit/26acf4313e4ed32ad88e907f5575d15e5f56ce0b#diff-a8a2d3e966bf5dae5ccd16c8ee77cf30R292)

I think I didn't understand that diff, why would a max_message_size NOT restrict the max amount of data placed on the response field ?

Thanks!

**Comment by leopucci** [comment]
Can you share some http request example with a pdf here?

**Comment by ifmusic** [comment]
It's not PDFs , that's just an example, but this is a screenshot.
![imagen](https://user-images.githubusercontent.com/919625/54844402-9a1e9d80-4cb5-11e9-8df5-e5a85ef6e819.png)

with this config: 
```
- type: http
  # Configure the ports where to listen for HTTP traffic. You can disable
  # the HTTP protocol by commenting out the list of ports.
  ports: [80, 8080, 8000, 9200, 5200, 5000, 8002]
  send_response: true
  send_request: true
  include_body_for: [""]
  message_size: 300
  real_ip_header: "X-Forwarded-For"
```

As you can see, the message body is not restricted to 300bytes
Thanks!

**Comment by leopucci** [comment]
@ifmusic 
max_message_size
If an individual HTTP message is larger than this setting (in bytes), it will be trimmed to this size
. **Unless this value is very small (<1.5K),**

Try setting this value to `message_size: 1048576` (1 mega)

**Comment by ifmusic** [comment]
Hi!, 

I tried several values from  1501 (>1.5kb), 512000 (500k) and  1048576 (1024Kb) ; still the same :(

**Comment by leopucci** [comment]
:(
