### ISSUE TITLE
Metadata based filtering for CM

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#11358]
CM will support metadata as attributes for config blocks. Per a discussion with @mattapperson we should make it possible for beats to request config blocks filtered by metadata criteria.

In the case of heartbeat we would filter by something like `{location: "us-east-1a"}` to get config blocks targeted at a given location. Note that config blocks might have multiple locations associated as an array.

CC @ph

**Comment by mattapperson** [comment]
To allow beats CM to be able to accurately display data to uses in the CM UI, we will be supporting this feature by setting a templated query filter on a config black that will be used to define what beats receive that config block.

Pseudo example:

Query "metadata" field on config
``` 
{
    query: `beat.metadata.location={location}`
}
```
where location is a field of the config itself, being a string or an array of strings

thus any beat with a location metadata field that matches a config blocks location will get returned to that beat

**Comment by andrewvc** [comment]
Seems like something better is in the works, closing.
