### ISSUE TITLE
Legacy ML saved objects should not be created by filebeat setup

### ISSUE THREAD

**Issue by sophiec20** [elastic/beats#11350]
- Version: 6.x, 7.x, 8.x
- Operating System: n/a

When filebeat is setup it loads multiple Kibana dashboards and visualizations. This includes legacy saved objects which were needed for ML prior to 6.1.

ML now has saved objects, stored as configuration items, which are created as part of its ml-module setup procedure, which is called by filebeat setup. Therefore filebeat setup does not need to additionally create legacy ml saved objects.

The following Nginx and Traefik dashboards and their associated saved objects (visualizations and saved searches) are no longer required:
```
- id: ML-Nginx-Access-Remote-IP-Count-Explorer
  file: ml-nginx-access-remote-ip-count-explorer.json

- id: ML-Nginx-Remote-IP-URL-Explorer
  file: ml-nginx-remote-ip-url-explorer.json

- id: ML-Traefik-Access-Remote-IP-Count-Explorer
  file: ml-traefik-access-remote-ip-count-explorer.json

- id: ML-Traefik-Remote-IP-URL-Explorer
  file: ml-traefik-remote-ip-url-explorer.json
```

Note. `filebeat setup --modules traefik` implies that ML module configuration is done. However there is no equivalent ML module for Traefik as this would have required a representative data sample to develop against. Legacy Traefik saved objects for ML are created but ML jobs are not. As there are no ML jobs then I believe that the ML legacy Traefik saved objects should also be removed as they are orphaned.

**Comment by ruflin** [comment]
If we just remove them from our config file, I assume that would solve the issue?

**Comment by sophiec20** [comment]
This is my assumption, but would imagine beats knows better.

I could not find reference to the visualizations or saved searches, so I have assumed that the Dashboard somehow cascades the creation of the saved objects that it requires.

**Comment by kvch** [comment]
@ruflin @sophiec20 I think so. It seems like a leftover from my PR which removed these assets. But looking at the code these files might be required if someone uses ES/KB 6.1 or older. Are we dropping the support completely in 7.x?

**Comment by ruflin** [comment]
Backward compatibility is a good question. As the general expecation is that ES/KB >= Beats I would be ok with dropping support for it.

**Comment by kvch** [comment]
Removed in #10795 and deprecated in #14532 (v7.6)
