### ISSUE TITLE
Winlogbeat 6.6.2 - replace to unicode problem

### ISSUE THREAD

**Issue by netbluew** [elastic/beats#11360]
For confirmed bugs, please report:
- Version: winlogbeat 6.6.2
- Operating System: Windows Server 2012 R2 (Language mode is Korean)

When update winlogbeat version 6.6.1 to 6.6.2 winlogbeat message replace newline to unicode.

**winlogbeat 6.6.1 message example**

<pre>
계정이 성공적으로 로그온되었습니다.

주체:
</pre>

**winlogbeat 6.6.2 message example**
<pre>
계정이 성공적으로 로그온되었습니다.\u000d\u000a\u000d\u000a주체:
</pre>

**Comment by leopucci** [comment]
Related  #11328
