### ISSUE TITLE
Libbeat-logp: keeps older files on rotation type change

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#11364]
Consider this content of the log directory:

```
-rw------- 1 root root 0 Feb 20 03:46 filebeat.7 
-rw------- 1 root root 0 Feb 20 11:19 filebeat.6 
-rw-r--r--. 1 root root 0 Feb 21 03:19 filebeat.5 
-rw-r--r--. 1 root root 0 Feb 21 16:09 filebeat.4 
-rw-r--r--. 1 root root 0 Feb 22 03:40 filebeat.3 
-rw-r--r--. 1 root root 0 Feb 25 03:16 filebeat.2 
-rw-r--r--. 1 root root 0 Feb 28 03:15 filebeat.1 
-rw-r--r--. 1 root root 0 Mar 11 08:47 filebeat-2019-03-11-35 
-rw-r--r--. 1 root root 0 Mar 11 08:52 filebeat-2019-03-11-36 
-rw-r--r--. 1 root root 0 Mar 11 08:56 filebeat-2019-03-11-37 
-rw-r--r--. 1 root root 0 Mar 11 13:38 filebeat 
```

`filebeat.X` files were created while the user had `interval` rotation disabled.
`filebeat-{time}-N` are current log files created by setting `interval` rotator

when we try to sort the files `interval` based are ordered before `size-only` and as a result, `size-only` are kept while purging all but latest 10 log files.
sort order would be 

```
filebeat-2019-03-11-34 
filebeat-2019-03-11-35 
filebeat-2019-03-11-36 
filebeat-2019-03-11-37 
filebeat.1
....
filebeat.7
```

so when purging latest 10 `filebeat-2019-03-11-34` is deleted. 

Point for discussion is whether or not to take into account date modified/created or delete `size-only` first with `interval` rotator and vice versa

**Comment by leopucci** [comment]
I don't see this as a bug (maybe i'm wrong), but it is expected that after a log filename syntax change, that the old logs are left behind. I would categorize this as a very low priority enhancement. Not a bug.

**Comment by michalpristas** [comment]
we had a discussion with a customer who was very confused that `filename.N` were left there and rotation of new logging type happened only on 3 files (instead of configured 10) 
for me as a user, it is important to see the configured number of most recent logs. 
in case the customer has 10 files from old configuration we say, the rotation is keeping only the active file. 
i agree that it's not maybe the most burning thing in the backlog but maybe we should mention it at least in docs. so they can perform manual cleanup of old log files when changing rotation type. sound possible?

**Comment by leopucci** [comment]
Let me test this. If I understood the new log rotation just rotated 3 files, not 10? If so, it is a bug :)

**Comment by michalpristas** [comment]
yes exactly 👍

**Comment by michalpristas** [comment]
also careful about the delimiter there it is not simple minus sign `-` but this longer one
