### ISSUE TITLE
Add support for PKI realm authentication in beats monitoring

### ISSUE THREAD

**Issue by jguay** [elastic/beats#11368]
**Describe the enhancement:**
At the moment, when security is enabled, it is required to specify a [username/password](https://www.elastic.co/guide/en/beats/filebeat/6.6/configuration-monitor.html) to ship monitoring data. This means it is possible for user to belong to native or ldap realm for example but it is not possible to use certificate authentication using [PKI realm](https://www.elastic.co/guide/en/elasticsearch/reference/6.6/configuring-pki-realm.html)
**Describe a specific use case for the enhancement or feature:**
Ability to use PKI realm for beats monitoring

**Comment by cachedout** [comment]
Hi @jguay. Thanks for filing this!

This almost sounds like a bug to me. Correct me if I'm wrong, but I feel like this should work as you describe out of the box.

I'll cc: @elastic/stack-monitoring for additional thoughts.

**Comment by ycombinator** [comment]
This should already be supported. See https://www.elastic.co/guide/en/beats/filebeat/current/configuration-monitor.html#_literal_ssl_literal_5.

@jguay Did you already try specifying `xpack.monitoring.elasticsearch.ssl.*` settings and it didn't work?

**Comment by jguay** [comment]
thank you @ycombinator I am closing this as it appears to work fine already as you mentioned
xpack.monitoring.elasticsearch.ssl.certificate.key
