### ISSUE TITLE
Unused ingest pipelines in cluster state

### ISSUE THREAD

**Issue by inqueue** [elastic/beats#11375]
Over time, the use of various Beats modules can lead to a build up of unused ingest node pipelines in the Elasticsearch cluster state. For example, there are 9 pipelines just from using the Filebeat Nginx module since 5.6:

```
curl $CURL'/_ingest/pipeline/filebeat*' | jq '.|keys'
[
  "filebeat-5.6.15-nginx-access-default",
  "filebeat-5.6.15-nginx-error-pipeline",
  "filebeat-6.6.1-nginx-error-pipeline",
  "filebeat-6.6.2-nginx-access-default",
  "filebeat-6.6.2-nginx-error-pipeline",
  "filebeat-6.7.0-nginx-access-default",
  "filebeat-6.7.0-nginx-error-pipeline",
  "filebeat-7.0.0-rc1-nginx-access-default",
  "filebeat-7.0.0-rc1-nginx-error-pipeline"
]
```

All but the 7.0 pipelines are unused in this example and there could easily be many more. I have commented on https://github.com/elastic/elasticsearch/issues/31954 to get `_cat` API support for pipelines in Elasticsearch, but it seems something more should be done to manage unused pipelines from Beats even if it is just documentation-- keeping in mind to not remove any pipelines in use by older Beats. 

The same is true for index templates. Perhaps this should be part of Central Management?

**Comment by ruflin** [comment]
This reminds me of https://github.com/elastic/curator/issues/1100
