### ISSUE TITLE
[stack upgrade] mapping conflicts in default Kibana index patterns

### ISSUE THREAD

**Issue by inqueue** [elastic/beats#11381]
After a series of upgrades from 5.6.15 -> 6.6.2 -> 6.7.0 -> 7.0.0, the default `filebeat-*` and `metricbeat-*` index patterns contain mapping conflicts due to mapping changes along the way. The Kibana Upgrade Assistant has been used for each major release upgrade to ensure index compatibility:

```
GET /_cat/indices/metricbeat*,filebeat-*
green open reindexed-v7-metricbeat-2019.02.27                  nsYTMy0MRfS4wpy7Wq_qUg 5 1   85384 0    40mb  19.9mb
green open reindexed-v7-filebeat-6.7.0-2019.03.16              M1SKO400TWytGFGpLjH_dg 1 1    1164 0 562.5kb 281.2kb
green open reindexed-v7-filebeat-6.6.2-2019.03.16              xArRNEzOTf2PsTiofPjzTA 1 1    3203 0     1mb 526.1kb
green open reindexed-v7-metricbeat-2019.03.15                  0tGQFVXPTN6av7NKMEJm1Q 5 1  319921 0 118.1mb    59mb
green open reindexed-v7-metricbeat-6.7.0-2019.03.16            O-Kq53cfStafj0IBDmbpNg 1 1  575915 0 259.8mb 129.9mb
green open reindexed-v7-metricbeat-6.7.0-2019.03.15            3b6GhduEQcmBX4F-ankRfA 1 1   87190 0  41.1mb  20.5mb
green open reindexed-v7-filebeat-6.6.2-2019.03.15              7NF7qL68QOyxgD9kgbG59g 1 1    1200 0 632.4kb 316.2kb
green open reindexed-v7-metricbeat-7.0.0-rc1-2019.03.16-000001 e_AHm2F6RGiEQUg1j760JA 1 1 3907297 0   2.1gb     1gb
green open reindexed-v7-metricbeat-6.6.2-2019.03.15            QwCpHKN6St6_JmYJ0xUtIQ 5 1   27702 0  27.6mb  13.8mb
green open reindexed-v7-filebeat-2019.03.15                    5dJaarA7Smm_EazorwTitw 5 1   48882 0  22.5mb  11.2mb
green open filebeat-7.0.0-rc1-2019.03.18-000001                _FBzFpT8Rv6BRkKBnN6PXQ 1 1    9266 0   3.9mb   1.9mb
```

**Metricbeat mapping conflicts**
<img width="1375" alt="Screen Shot 2019-03-21 at 2 18 16 PM" src="https://user-images.githubusercontent.com/6099128/54775374-37a99c80-4be4-11e9-820b-3c345a9d1f10.png">

**Filebeat mapping conflicts**
<img width="1678" alt="Screen Shot 2019-03-21 at 2 16 43 PM" src="https://user-images.githubusercontent.com/6099128/54775274-0761fe00-4be4-11e9-87bf-d335252abc3c.png">

This feels like something that should be solved since it seems it could leave index patterns in a bad state for visualizations, though I do not know the full implications.

**Comment by ruflin** [comment]
Is there a way to see which fields are conflicting? My guess is that Kibana tries to do too much magic. Our recommendation should be that users going to 7.0 overwrite the index pattern and have `migration.6_to_7.enabled: true` set in their config if they still want to use the old dashboards.
