### ISSUE TITLE
Debug selector setting for processors

### ISSUE THREAD

**Issue by kvch** [elastic/beats#11390]
Add support for setting debug selector for every processor.

**Comment by andrewkroh** [comment]
I don't think I'd add a configurable debug selector per processor, but I would give each processor it's own named logger like `processor.{name}`. And I would allow for adding a tag to each instance.

```
type SuperProcessor struct {
    log *logp.Logger
}

// At construction time.
processor.log = logp.NewLogger("processor.super")
if config.Tag != "" {
    processor.log = processor.log.With("instance_id", config.Tag)
}
```

Then when it logs you'll be able to distinguish between instances.

`INFO [processor.super] processors/super.go:30 Made the event super duper. {"instance_id": "my_processor"}`
