### ISSUE TITLE
Filebeat docker autodiscovery does not pick up logs sometime

### ISSUE THREAD

**Issue by vchan2002** [elastic/beats#11392]
I am using filebeat 6.6.1 and using autodiscovery to have it try to pick up container logs (Amazon ECS).  Filebeat runs as a container, with mounts to the config file on the system, along with file mounts on.  It's being shipped directly to elasticsearch.

volume='/etc/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro' --volume='/var/lib/docker/containers:/var/lib/docker/containers:ro' --volume='/var/run/docker.sock:/var/run/docker.sock:ro' 

I have two test scheduled job running, both running once an hour.  One produces about 20 lines of logs before exiting, and the other one produces only two lines because it is still erroring out and exiting right now.  I validated the logs are being produced underneath /var/lib/docker/containers/

For some reason, while filebeat picks up all the logs from the test scheduled job that produces about 20 lines, it only picks up the test job that produces two lines... sometimes.... I checked Kibana and it shows the job logs at like 1 a.m.... then 2 a.m., then 7 a.m., and so forth.  I checked /var/lib/docker/containers and it shows that the jobs did run every hour... Filebeat just didn't pick it up for some reason.....

I can't think of any anything on my end that reasonably explains this.... Is there a way to "force" filebeat to make sure it looks at the right directory?  

This is my filebeat config, BTW....  I tried addeding the -"*" to see if it helps picking up the logs, but not really....

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

filebeat.autodiscover:
  providers:
    - type: docker
      containers.ids:
        - "*"
      hints.enabled: true

processors:
- add_cloud_metadata: ~

**Comment by exekias** [comment]
I suspect this was fixed by https://github.com/elastic/beats/pull/10905. Before that change autodiscover was stopping workers right away after the container stops. Sometimes, not giving time to the input to read all their output.

Please try again with Filebeat 6.7 or later and reopen if this is still happening
