### ISSUE TITLE
how to query metricbeat system cpu and memory data stored in elasticsearch 

### ISSUE THREAD

**Issue by nilakshibhosale** [elastic/beats#11429]
how to query metricbeat system cpu and memory data stored in elasticsearch 
I am writing,
GET metricsindex/_search
{
  "query": {
    "bool": {
      "should": [
        { "match": { "metricset.name": "cpu" }},
        { "match": { "host.name": "example.locall" }}
        ]
    }
  }
}

but i m getting entire response object, how can we know through query

**Comment by jsoriano** [comment]
Hi @nilakshibhosale,

We try to use github only for confirmed issues, please next time use http://discuss.elastic.co for questions about usage of the Elastic Stack.

In your queries you can use [source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/6.6/search-request-source-filtering.html), for example to retrieve only `system.cpu` fields:

```
GET metric*/_search
{
  "_source": "system.cpu.*",
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "metricset.name": "cpu"
          }
        },
        {
          "match": {
            "host.name": "example.locall"
          }
        }
      ]
    }
  }
}
```

For metrics and other time series data is interesting to use the [time series visual builder](https://www.elastic.co/guide/en/kibana/6.6/time-series-visual-builder.html), that allows you to build visualizations based on this kind of data.
