### ISSUE TITLE
Configtest for module configurations

### ISSUE THREAD

**Issue by DanielBerman** [elastic/beats#11421]
Would be great to have the config test command verify a module configuration. Using the command right now does not output anything. You see an "all OK" message or an error message.

**Comment by ruflin** [comment]
@DanielBerman I remember this comes out of a discuss topic. I think the main point here was that it also verifies the connection details, for example AWS?

**Comment by DanielBerman** [comment]
Correct. Thanks for clarifying that!

**Comment by kaiyan-sheng** [comment]
link to the discuss topic: https://discuss.elastic.co/t/new-aws-module/173129
