### ISSUE TITLE
[Auditbeat] user.id/name misleading for login/user-login

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#11430]
The `uid` value in these events is the UID of the sshd process. So when Auditbeat reports `user.name` of `root` it's not really an attempted login for the root account. The `auditd.summary.actor` fields appear to be set accurately.

------
`type=USER_LOGIN msg=audit(1553501549.148:110544844): user pid=374 uid=0 auid=4294967295 ses=4294967295 msg='op=login acct="(unknown)" exe="/usr/sbin/sshd" hostname=? addr=1.2.3.4 terminal=ssh res=failed'`

user.uid: 0
user.audit: unset

auditd.summary.actor.primary: unset
auditd.summary.actor.secondary: (unknown)

------

`type=USER_LOGIN msg=audit(1553452002.231:110276965): user pid=10318 uid=0 auid=700 ses=5388 msg='op=login id=700 exe="/usr/sbin/sshd" hostname=1.2.3.4 addr=1.2.3.4 terminal=/dev/pts/0 res=success'`

user.id: 0
user.auid: 700

auditd.summary.actor.primary: admin
auditd.summary.actor.secondary: admin

**Comment by andrewkroh** [comment]
@FrankHassanabad  I think you had found a related case where `type=LOGIN` (that's what I have in my notes). Do you have the contents of that event available?

**Comment by FrankHassanabad** [comment]
I cannot find that one and do not know if I had that event occur. If I find it I will put here but doing some searches and did not see it.

**Comment by FrankHassanabad** [comment]
There is this one I did find which is `type=USER_AUTH`

```
type=USER_AUTH msg=audit(1552714590.571:21114): pid=11312 uid=0 auid=0 ses=62 msg='op=PAM:authentication acct="bob" exe="/bin/su" hostname=? addr=? terminal=/dev/pts/0 res=success'
```

You can get to it through like this screen shot and see that the `user.name` is almost always `root` even when you have one user turning into a different user and root is not involved

<img width="1483" alt="Screen Shot 2019-03-25 at 9 42 50 PM" src="https://user-images.githubusercontent.com/1151048/54970295-33b0ae00-4f47-11e9-99b0-51c13cec648b.png">

**Comment by FrankHassanabad** [comment]
Here is one more that looks like the same issue with `user.name` when `type=CRED_ACQ`

```
  "event": {
    "action": "acquired-credentials",
    "category": "user-login",
    "module": "auditd",
    "original": [
      "type=CRED_ACQ msg=audit(1553557236.015:4088825): pid=9033 uid=0 auid=1001 ses=352 msg='op=PAM:setcred acct=\"bob\" exe=\"/usr/sbin/sshd\" hostname=8.42.77.171 addr=8.42.77.171 terminal=ssh res=success'"
    ]
  },
```

Screenshot:
<img width="1353" alt="Screen Shot 2019-03-26 at 8 49 27 AM" src="https://user-images.githubusercontent.com/1151048/55007081-6e94ff00-4fa4-11e9-8e53-732ea9ba4081.png">

**Comment by FrankHassanabad** [comment]
Here `event.action : "ended-session"` when `type=USER_END`

```
  "event": {
    "action": "ended-session",
    "category": "user-login",
    "module": "auditd",
    "original": [
      "type=USER_END msg=audit(1553557283.240:4089553): pid=8944 uid=0 auid=1001 ses=352 msg='op=PAM:session_close acct=\"bob\" exe=\"/usr/sbin/sshd\" hostname=8.42.77.171 addr=8.42.77.171 terminal=ssh res=success'"
    ]
  },
```

You can see that it should list out `user.name` as `bob` per screenshot of ending a session:
<img width="1456" alt="Screen Shot 2019-03-26 at 11 12 59 AM" src="https://user-images.githubusercontent.com/1151048/55018382-62b33800-4fb8-11e9-92e4-78750ed0fd32.png">
