### ISSUE TITLE
[Auditbeat] Remove unset user.auid and auditd.session

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#11431]
It has been requested to drop the user.auid field when the value is `unset`.

Likewise we should follow the same practice for the unset session IDs (`auditd.session:unset`).

**Comment by andrewkroh** [comment]
cc: @FrankHassanabad

**Comment by adriansr** [comment]
Is there a reason to do this only for `user.auid` and not for all the uid fields?
