### ISSUE TITLE
When "log" field is missing in docker container's log line, filebeat immediately exited with Go routine panic

### ISSUE THREAD

**Issue by DebashisMondal** [elastic/beats#11464]
**Objective:**
Verifying the filebeat behavior when  json field "log" is missing  from container's log line but "stream" and "time" fields are present.

**Version:**
6.4,  6.7
**Execution Steps:**
1. Create a docker container
`      # docker run hello-world`
2. Make a note of  the  docker container id created by <Step-1> in "/var/lib/docker/containers"
3. Configure the container ID in "filebeat.yml"
> filebeat.inputs:
>   `-` type: docker
>          containers:
>          ids:  'd401788ed2c1186afed103ff05e0f9426e1a2657d541b84e3873fb1121ca9c6c'
4. Edit the container log as per the objective for verification
`    # vim /var/lib/docker/containers/d401788ed2c1186afed103ff05e0f9426e1a2657d541b84e3873fb1121ca9c6c/d401788ed2c1186afed103ff05e0f9426e1a2657d541b84e3873fb1121ca9c6c-json.log`

    {"log":"Hello from Docker! \n","stream":"stdout","time":"2019-03-15T08:46:59.401128771Z"}
    {"stream":"stdout","time":"2019-03-15T08:46:59.401161003Z"}

    [Note: a) 1st line is in correct format
                    b) In 2nd line "log" json field is missing
    ] 
5. Start filebeat
  `    # filebeat -e`

**Observation:**
It is observed that when container's log does not have "log" json field in log line but have "stream" and "time" fields, then filebeat can't parse the corresponding log line and exited immediately with below go routine panic error.

panic: runtime error: index out of range

[OutputConsoleLog.txt](https://github.com/elastic/beats/files/3007636/OutputConsoleLog.txt)

**Expected Behavior:**
Basically as "autodiscover" is disabled so filebeat treats the containers log file as normal logs but as prospector type is set to "docker" so it will parse the log line through docker-json parser.

So If any one try to interrupt the production environment then they can corrupt it by sending a log line just like docker json log format without "log" key. So for the security purpose and to prevent failure we need to enhance the code to handle this kind of situation.

When "log" field is missing in any container's log line, then filebeat should treat it as ""  and it should be treated as partial line by docker json parser during event preparation. This blank line will be combined with next line where log message have "\n" at the end just like the behavior with other partial lines.

Otherwise if somehow in any container's log the log data is corrupted then due to go panic error filebeat will be stopped working which will impact the production environment.

_**Example of Partial Line:**_
According to current behavior of filebeat docker parser, if json lines are as per below

 line-1: "log": "This is first line"
 line-2: "log":"This is second line \n"
 line-3: "log": "This is third line \n"

During event preparation 2 events will be prepared
In 1st event : "message" : "This is first line This is second line"
In 2nd event: "message": "This is third line"

As line-1 has no "\n" so it is treated as partial line hence it is combined with line-2 during event preparation.

In mentioned scenario when "log" key is not present then the value of "log" key will be taken as "" and it should be combined with next complete line.

**Comment by DebashisMondal** [comment]
Confirmed Discussion Link : https://discuss.elastic.co/t/bug-when-log-field-is-missing-in-containers-log-line-filebeat-immediately-exited-with-go-routine-panic/173880/3

**Comment by DebashisMondal** [comment]
@kvch 
I am going to propose fix in package "docker-json" but the thing is that in 
v6.7 location is : https://github.com/elastic/beats/filebeat/reader/docker_json
In master the location is : https://github.com/elastic/beats/tree/master/libbeat/reader/readjson

So, what should be done regarding PR.

Can I have to open one PR for "master" branch and another for "6.7" ?

Kindly let me know.

Thanks

**Comment by ruflin** [comment]
@DebashisMondal Best open a PR against master and then we can check from there if and how we backport.

**Comment by DebashisMondal** [comment]
Thanks @ruflin 
One more thing, I want to know that as in master I have to make changes in package under libbeat so in Changelog which section need to be updated  "Affected all beats" or "Filebeat"?

**Comment by ruflin** [comment]
yes, if it is in libbeat, it would affect all Beats. There are potentially more then 1 changelog entry, but the PR should show it and we can worry about it during discussing the PR.

**Comment by michalpristas** [comment]
Closing fixed here: #12165
