### ISSUE TITLE
[Filebeat] Populate source.bytes from Netflow Input

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#11473]
For unidirectional flows it only populates the `network.bytes` and `network.packets`. I think also populating `source.bytes/packets` would make the data a little more consistent with other data sources.

**Comment by adriansr** [comment]
@andrewkroh do you have a sample of those unidirectional flows? I'd like to see which fields are included. I think it might be the case that the Netflow exporter is not providing this information

**Comment by andrewkroh** [comment]
Like for the event linked below (when the flow direction is forward) the `network.bytes` / `network.packets` are the `source.bytes` / `source.packets` values, right?

https://github.com/elastic/beats/blob/50f1180c3a35c2c0cdf334f54a288777518393a3/x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Ubiquiti-Edgerouter-with-MPLS-labels.golden.json#L47-L48
