### ISSUE TITLE
[Heartbeat] Some Durations are of questionable utility.

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#11476]
Looking at the code for some of our duration stats it seems that

* Looking at the git history as far back as v5.0.0 it seems we never set `http.rtt.validate_body.us `. Its inclusion in the docs is probably an error. I'll remove the mapping definition/docs in a subsequent release.
* `http.rtt.total.us` is the total time for the HTTP request to complete + any validations to run.
* `http.rtt.validate.us` is probably not that useful. It measures the time between starting the write to the socket, after the TCP connection is setup, and the entire check being completed.
* `monitor.duration.us` is the total time for any check to be executed.
* `tcp.validate.us`: is the length of time to run a check against the payload, but that time is never siginificant enough to measure. 

There's a lot of duplication there. I propose the following changes:

* Remove `http.rtt.validate_body.us`
* Remove `http.rtt.total.us`
* Remove all `*.validate.*` options

**Comment by ruflin** [comment]
@urso is probably the best person to comment on this.

**Comment by urso** [comment]
Uff, it's quite a time. I try to answer based on what I remember

> Looking at the git history as far back as v5.0.0 it seems we never set http.rtt.validate_body.us . Its inclusion in the docs is probably an error. I'll remove the mapping definition/docs in a subsequent release.

+1. Looks like an error.

> http.rtt.total.us is the total time for the HTTP request to complete + any validations to run.

This includes all network layers. The host is already resolved to an IP, so this RTT is: `TCP connect + send request + read response + validate body`.

> http.rtt.validate.us is probably not that useful. It measures the time between starting the write to the socket, after the TCP connection is setup, and the entire check being completed.

Not sure if this behavior kind of changed. The validation itself should be quite fast, but as the contents is streamed from the server once the response headers have been received. This metric used to measure the time to read the full response body only. Better name would have been `http.rtt.read_body.us`. We did some changes to heartbeat, such that we always read the body now.
The usefullness depends on the server, like if and when the response body becomes available.

> monitor.duration.us is the total time for any check to be executed.

This includes required DNS calls if a hostname is required. Which again varries depending on DNS caching on the local machine/network.

> tcp.validate.us: is the length of time to run a check against the payload, but that time is never siginificant enough to measure.

I'd say this depends on the server. If the server is slow to generate the response payload we might be able to see it. But TCP monitor is indeed such 'generic' that this metric is not that useful here.

**Comment by andrewvc** [comment]
@urso let me know what you think of the following plan:

We can deprecate `http.rtt.validate_body.us` and `tcp.validate.us` for removal in 8.0. 

We should deprecate `http.rtt.validate.us` as well since its naming is so confusing, and consider adding `http.rtt.read_body.us` in the future since that would be more clear.

We can deprecate `http.rtt.total.us` since the values here are so similar to monitor.duration.us and DNS issues can be determined via subtraction.

On the whole, perhaps we should rethink the way we record and store timing information. Instead of these separate overlapping spans we could instead think of things as discrete phases. So, we could create a timer object, and let each phase in execution set the current phase as we move through time. While spans are more powerful, especially when parallelism is involved, they are more complex to work with and understand. Since an individual check is executed linearly, a span may not be the best fit.

In the future we may have cases where we want to compose multiple linear checks, but we aren't quite there yet, and a linear check can always be turned into a span if need be. 

CC @dov0211 @ruflin @justinkambic
