### ISSUE TITLE
Document all possible types generated by topbeat

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#1149]
Using topbeat 1.1.1

Currently, we document only 1 type value as part of "common fields"
https://www.elastic.co/guide/en/beats/topbeat/current/exported-fields-env.html#_type

But topbeat can create (to date) 3 different types of events: 
system, filesystem and process

Will be helpful to document all available type values set by topbeat.

**Comment by ruflin** [comment]
This is solved in metricbeat which automatically generates documentation and example json files for all fields. Closing this issue.
