### ISSUE TITLE
[Infrastructure] part of the drop-down is hidden on k8s section

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/beats#11509]
On the k8s section, with the table view enable when you click on a pod part of the drop-down is hidden under the left menu bar. 

<img width="433" alt="Screenshot 2019-03-28 at 13 26 53" src="https://user-images.githubusercontent.com/5400788/55158055-47822d00-515e-11e9-91e0-2688bfbe03da.png">

For confirmed bugs, please report:
- Version: 7.0.0-rc1
- Operating System: Linux on k8s
- Discuss Forum URL: N/A
- Steps to Reproduce: 

* Access to the Infrastructure view
* go to k8s section (only happens here)
* change the view to "table view"
* click on some item near the left side

**Comment by alvarolobato** [comment]
superseded by https://github.com/elastic/kibana/issues/35524
