### ISSUE TITLE
[ECS] 7.0.0-rc1 Broken Beats Dashboards

### ISSUE THREAD

**Issue by EthanStrider** [elastic/beats#11517]
Certain Beats dashboards appear to be broken by ECS changes since they still reference the old data field names.

<img width="1792" alt="Screen Shot 2019-03-28 at 10 06 43 AM" src="https://user-images.githubusercontent.com/4145612/55164669-72f71e80-5142-11e9-8dea-8850d6a98446.png">
<img width="1792" alt="Screen Shot 2019-03-28 at 1 24 14 PM" src="https://user-images.githubusercontent.com/4145612/55179391-ac895300-515d-11e9-8b70-5f70b3391673.png">
<img width="1792" alt="Screen Shot 2019-03-28 at 1 26 40 PM" src="https://user-images.githubusercontent.com/4145612/55179392-ac895300-515d-11e9-8698-58a06f0256c8.png">
<img width="1792" alt="Screen Shot 2019-03-28 at 1 26 33 PM" src="https://user-images.githubusercontent.com/4145612/55179393-ad21e980-515d-11e9-839c-a61fa03b5aa3.png">
<img width="1792" alt="Screen Shot 2019-03-28 at 1 41 46 PM" src="https://user-images.githubusercontent.com/4145612/55180114-4f8e9c80-515f-11e9-8adb-2d0e6bedb724.png">
<img width="1792" alt="Screen Shot 2019-03-28 at 1 45 28 PM" src="https://user-images.githubusercontent.com/4145612/55180943-f7589a00-5160-11e9-8249-50aa6f1e85d4.png">
<img width="1792" alt="Screen Shot 2019-03-28 at 1 52 16 PM" src="https://user-images.githubusercontent.com/4145612/55180944-f7589a00-5160-11e9-9c61-0b4467e9d7e8.png">

There are probably more...  I'll update this ticket as I find them.

For confirmed bugs, please report:
- Version: `7.0.0-rc1`
- Operating System: Cloud

**Comment by EthanStrider** [comment]
Ok, seems like there are a lot of broken dashboards.  I'm thinking about writing a script to search all the old terms against this repo: https://github.com/elastic/kibana/tree/7.0/x-pack/plugins/ml/server/models/data_recognizer/modules

**Comment by ruflin** [comment]
For the Beats dashboards we were running this script to migrate the fields: https://github.com/elastic/beats/blob/master/script/kibana-migration.py That should also work for the ML dashboards. But the dashboards you link above, are these from ML or the ones loaded through Beats?

**Comment by EthanStrider** [comment]
@ruflin I think it's a combination of ML dashboards and dashboards loaded through Beats.  I'm working on upgrading the demo.elastic.co demo environment, so we use everything.

**Comment by EthanStrider** [comment]
From the docs here: https://www.elastic.co/guide/en/beats/libbeat/7.0/breaking-changes-7.0.html

Isn't this backwards?

Shouldn't it be:
```
auditd.message_type --> event.type
```

<img width="664" alt="Screen Shot 2019-03-28 at 3 02 26 PM" src="https://user-images.githubusercontent.com/4145612/55191260-14e52e00-5178-11e9-8679-7fc6558bbb5c.png">

**Comment by fearful-symmetry** [comment]
Yah, `auditd.message_type` seems backwards.


So, I'm just gonna preface this by saying I have almost no experience with the kibana side of things, but I'm trying to learn. That being said, I'm looking at the nginx dashboards, and it looks like a few fields weren't hit by https://github.com/elastic/beats/pull/9998.

From what I can tell, the script will only change names if `alias: True` which isn't the case for a lot of the user agent fields in `ecs-migration.yml` https://github.com/elastic/beats/blob/d026281870573495a82b95df602f108e9d2bbad0/dev-tools/ecs-migration.yml#L1260

This might be why a lot of the visualizations that rely on user_agent are using the pre-ecs fields: https://github.com/elastic/beats/blob/d026281870573495a82b95df602f108e9d2bbad0/filebeat/module/nginx/_meta/kibana/7/dashboard/Filebeat-nginx-overview.json#L114

that should be `user_agent.os.version` for ecs?

I wonder if this is a case where we need to start changing dashboards by hand.

**Comment by EthanStrider** [comment]
> that should be user_agent.os.version for ecs?

Yes, that is correct.

**Comment by EthanStrider** [comment]
Created a PR here: https://github.com/elastic/beats/pull/11520

**Comment by ruflin** [comment]
@EthanStrider As #11520 is closed, I think we can close this issue.

@fearful-symmetry Could you do some test checks if we miss some more fields which don't have an alias? I thought I did but seems like I missed some :-(

**Comment by EthanStrider** [comment]
@ruflin Thanks!  Is there going to be an updated build for `7.0.0-rc1`?
https://staging.elastic.co/7.0.0-rc1-2fe9f018/summary-7.0.0-rc1.html

I'm not sure how the build system works.

**Comment by webmat** [comment]
@EthanStrider For the `event.type` change, I know it looks backwards, but this is actually expected.

`event.type` will come back with a very well defined set of values that need to be used across all sources. So whatever was in there, populated by prior versions of Auditbeat's auditd module is being moved to a custom field now.

cc @fearful-symmetry

**Comment by ruflin** [comment]
@webmat So the change in this PR to event.type should be reverted? I'm now also confused :-)

**Comment by webmat** [comment]
`event.type` right now is reserved. Must not be used in 7.0.

Still going through the PR, but yes, it needs to be made `auditd.event_type` again

**Comment by EthanStrider** [comment]
@ruflin Sounds like just the change to the doc needs to be reverted.  I added a comment.

**Comment by fearful-symmetry** [comment]
Trying to track where we are with this. We have 
#11520
Related, #11538 
#11545 

I _think_ those PRs should cover everything?

**Comment by webmat** [comment]
As far as I know, everything here has been addressed.

WDYT @EthanStrider?

**Comment by EthanStrider** [comment]
Looks good!  If I find anything else, I'll let you know.

**Comment by ruflin** [comment]
Thanks everyone, closing this for now.
