### ISSUE TITLE
Libbeat.rotator: enable flag for rotating log files on startup

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#11537]
At this point, log file gets rotated automatically on startup

Idea is to make it configurable in a way that:
- `rotateOnStartup == true`: log file is automatically rotated
- `rotateOnStartup == false`: log file is not rotated, new logs are appended and rotation happens only if the condition specified in rotator is evaluated positively

**Comment by kvch** [comment]
Hints for getting started:
A new boolean option needs to be added under `logging.files` named `rotate_on_startup`. By default, it has to be true, to avoid introducing a breaking change.
The struct `file.Rotator` needs to be able to rotate files on startup if configured to.
