### ISSUE TITLE
[Hearbeat] Allow check.send to be a byte trame format on TCP type

### ISSUE THREAD

**Issue by Raphyyy** [elastic/beats#11532]
Hi,

We use hearbeat as a monitoring service for all of our service, including non-http ones.
The problem is that for some service like PostgreSQL, performing a simple TPC check on a service will result errors like `incomplete startup packet`, caused by an incomplete try to connect.

This lead to log flood and sometimes, app do not permit to remove those.

Actually `check.send` allow to send ASCII chars on top of TCP, on the Application layer. But most of services protocol do not use ASCII trame. 
So it could be nice if `check.send` allow to be an array of byte like `check.send = [0x00, 0x12, 0x23, 0x37, 0x65]` in order to _simulate_ a connection trame to the server and so, avoid socket error log on server.

**Comment by andrewvc** [comment]
Apologies for the delay in response. Thanks for the input on this! What do you think about base64 encoding, or do you prefer hex encoded bytes?

**Comment by Raphyyy** [comment]
No problem, thank you for noticing this.
I have no particular preference, still I believe that hex encoded should be more efficient and choose base64 will leads to specify if the specified check.send is a 64b encoded str or plain text.
