### ISSUE TITLE
[Winlogbeat] Decode AccessList from auditing messages

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#11539]
Some auditing messages ([4663](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4663) for example) contain a list of permissions (a.k.a AccessList).

This is list encoded as a list of numeric identifiers ("%%4416") and we would like to have them mapped to their textual representation ("ReadData (or ListDirectory) ") as Event Viewer does.

**Comment by leopucci** [comment]
Hello Adrian, 
There is a list on %windir%\system32\msobjs.dll

I am following this instructions. 
http://blog.ivanspiridonov.com/?p=407

I will try to help you out with this.  :)

**Comment by leopucci** [comment]
Windows 10 list from msobjs.dll
https://gist.github.com/leopucci/25a06a305a2a74f297eab1493a136dcb
Tomorrow I will understand the behavior and convert it to text. o/!

**Comment by leopucci** [comment]
Finishing other issues before starting this one. 
Just a note for myself or anyone that wants to help
Good starting point winlogbeat/sys/event_test.go - create test with Access List first.

**Comment by andrewkroh** [comment]
This sounds like something that we could bake into the Security log processor I'm adding in [this PR](https://github.com/elastic/beats/pull/11651/commits/5c9e90d14fc55bf86b0edfe876fbdf5057949bdb#diff-a645643fac60e432d04797f89c42c159R85).

One thing I'd like to check is what event IDs have the `AccessList` parameter and do the values have the same meaning.

**Comment by leopucci** [comment]
Many event ids will have the AccessList, but it will be alway using this pattern:
```
<Event>
 <EventData>
  <Data Name="AccessList">%%1537 %%4418 %%4417</Data>
 </EventData>
</Event>
```

The values have the same meaning since the XP windows. For new windows OS they might create new values, so if the value is not mapped, it should pass the %%1537 value (i think, just to be sure that it will not pass 0 or "" ahead).

**Comment by andrewkroh** [comment]
Gist for extracting the message table: https://gist.github.com/andrewkroh/665dca0682bd0e4daf194ab291694012
