### ISSUE TITLE
add_docker_metadata's match_source does not work

### ISSUE THREAD

**Issue by axw** [elastic/beats#11556]
For confirmed bugs, please report:
- Version: 7.0.0-rc1
- Operating System: Linux
- Steps to Reproduce: 

1. Run Filebeat on the host machine, with the following set in filebeat.yml:

```
filebeat.inputs:
- type: docker
  containers.ids: '*'

processors:
- add_docker_metadata: ~
```
2. Run a Docker container that logs something.
3. Observe logs show up in Discover, but there is no `container.id` field.

**Comment by axw** [comment]
In https://github.com/elastic/beats/pull/8902, filebeat's `source` field was removed and replaced with `log.file.path`.

The `add_docker_metadata` processor still references `source`: https://github.com/elastic/beats/blob/v7.0.0-rc1/libbeat/processors/add_docker_metadata/add_docker_metadata.go#L89

**Comment by odacremolbap** [comment]
This should be solved now.
Can you confirm @axw ?

**Comment by axw** [comment]
@odacremolbap confirmed by building off the 7.0 branch. Thank you!
