### ISSUE TITLE
packetbeat - decoding option 82, vendor options

### ISSUE THREAD

**Issue by waszi** [elastic/beats#11555]
Could you consider adding support for DHCP Option 82 decoding (dhcp relay, agent remote-id, etc).

Also it would be nice to be able to define custom fields decoding. It is simple TLV encoding. You could use config to define vendor field name to TLV code mapping.

Currently I am using python based sniffer to dhcp (push redis -> logstash), but it is not very efficient solution.

**Comment by itayrozenberg** [comment]
i'm using packetbeat at this monent,
but i really need option-82/remote-id.

please consider adding this feature
thank you

**Comment by fgierlinger** [comment]
Please consider this feature. Do not stall.

**Comment by alexsuppanz** [comment]
Also from my side, please consider this feature!

**Comment by fgierlinger** [comment]
Please consider this feature. Do not stall / reopen this issue please.

**Comment by itayrozenberg** [comment]
Please consider this .... 
thank you
