### ISSUE TITLE
[PostgreSQL] - Don't have Query count and cumulated duration

### ISSUE THREAD

**Issue by patsevanton** [elastic/beats#11588]
Hi. ELK stack version 6.6.2. I deployed a new server with PostgreSQL and I use Filebeat to send PostgreSQL logs the the elasticsearch cluster. I added the pluggin PostgreSQL and imported the dashboard (filebeat setup -e).

Dont have:
Query count and cumulated duration [Filebeat PostgreSQL]
Query Durations [Filebeat PostgreSQL]
Slow Queries [Filebeat PostgreSQL]

cat modules.d/postgresql.yml
```
- module: postgresql
  # All logs
  log:
    enabled: true

    var.paths:
     - /var/lib/pgsql/11/data/log/*.log
```

cat /var/lib/pgsql/11/data/postgresql.conf | grep -v "^#" | grep -v "^$"
```
max_connections = 100 
shared_buffers = 128MB
dynamic_shared_memory_type = posix 
max_wal_size = 1GB
min_wal_size = 80MB
log_destination = 'stderr'
logging_collector = on
log_directory = 'log' 
log_filename = 'postgresql-%a.log' 
log_truncate_on_rotation = on 
log_rotation_age = 1d 
log_rotation_size = 0 
log_duration = on
log_line_prefix = '%m [%p] '
log_timezone = 'W-SU'
datestyle = 'iso, mdy'
timezone = 'W-SU'
lc_messages = 'en_US.UTF-8' 
lc_monetary = 'en_US.UTF-8' 
lc_numeric = 'en_US.UTF-8'
lc_time = 'en_US.UTF-8' 
default_text_search_config = 'pg_catalog.english'
```

![](https://discourse-cdn-sjc1.com/elastic/uploads/default/original/3X/d/1/d1cafe505e0d5fcadec50dfea315271f26e56db0.png)
![](https://discourse-cdn-sjc1.com/elastic/uploads/default/original/3X/2/8/28b09ab36a7edae1f33685cb5e7e657594f899bd.png)

**Comment by sayden** [comment]
Hi @patsevanton :slightly_smiling_face:  you need to also activate all `log_statement` in your config. Without it, queries aren't logged and therefore captured by filebeat.

Can you check, please?

**Comment by patsevanton** [comment]
Hi
`log_statement on` ?
Try later

**Comment by sayden** [comment]
Check the docs for your Postgres version because in some versions it's `log_statement = true` or `log_statement = 'all'`

**Comment by patsevanton** [comment]
Install filebeat, ELK - 7.0.1
Install Postgresql 11

cat /etc/filebeat/modules.d/postgresql.yml 
```
- module: postgresql
  log:
    enabled: true
    var.paths:
     - /var/lib/pgsql/11/data/log/*.log
```

cat /var/lib/pgsql/11/data/postgresql.conf | grep -v "^#" | grep -v "^$"
```
max_connections = 100			
shared_buffers = 128MB			
dynamic_shared_memory_type = posix	
max_wal_size = 1GB
min_wal_size = 80MB
log_destination = 'stderr'		
logging_collector = on			
log_directory = 'log'			
log_filename = 'postgresql-%a.log'	
log_truncate_on_rotation = on	
log_rotation_age = 1d			
log_rotation_size = 0			
log_line_prefix = '%m [%p] '	
log_statement = 'all'			
log_timezone = 'W-SU'
datestyle = 'iso, mdy'
timezone = 'W-SU'
lc_messages = 'en_US.UTF-8'	
lc_monetary = 'en_US.UTF-8'	
lc_numeric = 'en_US.UTF-8'	
lc_time = 'en_US.UTF-8'		
default_text_search_config = 'pg_catalog.english'

```

Run pgbench and https://gist.github.com/ololobus/5b25c432f208d7eb31051a5f238dffff

![Screenshot from 2019-05-20 14-53-49](https://user-images.githubusercontent.com/10828883/58008989-4d1d4300-7b0f-11e9-87c6-b93cbf34dc5a.png)
![Screenshot from 2019-05-20 14-54-01](https://user-images.githubusercontent.com/10828883/58008990-4db5d980-7b0f-11e9-90ed-ccea6d2cc4b9.png)

**Comment by sayden** [comment]
Ok, I managed to reproduce the issue. Postgres 11 has not been tested yet. I have opened a PR to solve the issue here: https://github.com/elastic/beats/pull/13053

**Comment by sayden** [comment]
Solved in https://github.com/elastic/beats/pull/13053
