### ISSUE TITLE
Update Platform Reference to show correct index patterns

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#1159]
Docs show old format for index patterns: https://www.elastic.co/guide/en/beats/libbeat/1.1/load-kibana-dashboards.html. Need to update docs to show newer pattern (without YYYY.MM.DD).

Also update screen capture here: https://www.elastic.co/guide/en/beats/libbeat/1.1/view-kibana-dashboards.html

See https://github.com/elastic/beats-dashboards/issues/91

**Comment by ruflin** [comment]
@dedemorton Thanks for taking this up. I think that change is quite important as all new starters with K4.4 will hit this issue. I put the 1.2 label in.

**Comment by monicasarbu** [comment]
Closing it as it fixed.
