### ISSUE TITLE
add ability to pass configuration options on the command line

### ISSUE THREAD

**Issue by djschny** [elastic/beats#1161]
There are various options that can be specified in `*beat.yml` files. However many times it is easier, more convenient, and more script friendly to have these options passed in on the command line. For example:

`packetbeat --interfaces.device=any`

This is to represent a request for this ability in *beats (assuming it would be done at the lib-beat level). Additionally my example above is not meant to dictate syntax but rather act as just that, an example.

**Comment by monicasarbu** [comment]
Indeed there are many configuration options available, but If you would have to choose only a few options what configuration options would you pass on the command line? It also depends on the Beat, as each Beat has specific configuration options besides the ones from libbeat.

**Comment by monicasarbu** [comment]
At a second thought, I agree we should export all the configuration options (libbeat + specific beat configuration options) and pass the configuration option to the command line similar with what Elasticsearch is doing:
<pre>
    -Dproperty=value             Configures an Elasticsearch specific property, like -Dnetwork.host=127.0.0.1

    --property=value             Configures an elasticsearch specific property, like --network.host 127.0.0.1
</pre>

**Comment by urso** [comment]
Not sure I already created a ticket for this, but this is on my ucfg TODO list.

**Comment by ruflin** [comment]
This is now possible the most recent beats releases thanks to go-ucfg. All config options can also be passed via `-E` flag. Closing.
