### ISSUE TITLE
Metricbeat autodiscover’s doc minor bug

### ISSUE THREAD

**Issue by starkchao** [elastic/beats#11622]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 6.7
- Operating System: CentOS Linux release 7.5.1804 (Core)
- Discuss Forum URL: https://discuss.elastic.co/t/metricbeat-autodiscovers-doc-minor-bug/174947
- Steps to Reproduce: 
1. metricbeat.yml's config:
metricbeat.autodiscover:
  providers:
    - type: kubernetes
      hints.enabled: true
      in_cluster: false
      kube_config: /opt/k8s/etc/kubernetes/kubelet.kubeconfig

2. k8s pod yaml:
  template:
    metadata:
      annotations:
        co.elastic.metrics/module: prometheus
        co.elastic.metrics/metricsets: collector
        co.elastic.metrics/hosts: '${data.host}:{data.port}'
        co.elastic.metrics/period: 1m
        co.elastic.metrics/namespace: exporter
3. run metricbeat : metricbeat -e -d "*"

4. In the output log, you can get the following error message：
2019-04-03T15:13:14.430+0800	DEBUG	[autodiscover]	autodiscover/autodiscover.go:195	Check failed for config &{{<nil> } <nil> 0xc420b93540}: 1 error: host parsing failed for prometheus-collector: error parsing URL: parse http://10.244.5.10:{data.port}: invalid character "{" in host name, won't start runner
————————————
Metricbeat autodiscover's doc【https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover.html#configuration-autodiscover】
![image](https://user-images.githubusercontent.com/29062764/55459964-5b78d380-5623-11e9-9487-aff68afc856b.png)
this config need to change : hosts: "${data.host}:${data.port}", if not metricbeat won't work correctly.

**Comment by exekias** [comment]
Thank you for reporting, you are indeed right!
