### ISSUE TITLE
[Central Management] Template not loaded when running Beat

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#11626]
* Version: 7.0.0-rc2 (Stack and Metricbeat), Cloud

The template for a Beat is not loaded when used in combination with Central Management. This means data is index into an index without a template and because of ILM, this should be the actual alias.

Steps to reproduce:

* Setup Elastic Stack
* Enroll Beat, configure ES Output and System module
* Start Beat

Data is ingested but no template is there.

**Comment by michalpristas** [comment]
Closing this with fleet in mind this flow is outdated
