### ISSUE TITLE
Improve Kubernetes module testing code

### ISSUE THREAD

**Issue by sayden** [elastic/beats#11624]
Kubernetes module has few metricsets with a quite complex code that probably can be improved, make it more clear or test more code. "Offending" metricsets are:

- `state_deployment`
- `state_pod`
- `state_replicaset`
- `state_statefulset`

Ideally, all of them should work in a similar way, like `state_container` does with this small snippet:

```go
func TestEventMapping(t *testing.T) {
	ptest.TestMetricSet(t, "kubernetes", "state_container",
		ptest.TestCases{
			{
				MetricsFile:  "../_meta/test/kube-state-metrics",
				ExpectedFile: "./_meta/test/kube-state-metrics.expected",
			},
			{
				MetricsFile:  "../_meta/test/kube-state-metrics.v1.3.0",
				ExpectedFile: "./_meta/test/kube-state-metrics.v1.3.0.expected",
			},
		},
	)
}
```

**Comment by ruflin** [comment]
I assume all these tests can be removed. The focus for me of this issue should be on improving the kubernetes helper to get rid of these hacks: 

https://github.com/elastic/beats/blob/9f3aede8493d9e5d800e1ee45c27be53db50aa9c/metricbeat/module/kubernetes/state_deployment/state_deployment.go#L107-L115

This means the prometheus helper should natively support putting fields on the module or root level.
