### ISSUE TITLE
[Heartbeat] Autodiscover docs uses `hosts` for http instead of `urls`

### ISSUE THREAD

**Issue by mdibaiee** [elastic/beats#11643]
- Version: N/A
- Operating System: N/A
- Discuss Forum URL: https://discuss.elastic.co/t/heartbeat-autodiscover-documentation-uses-hosts-instead-of-urls-for-http/175398
- Steps to Reproduce: 

In the Autodiscover documentation page of Heartbeat, the example for Kubernetes uses `hosts` under the HTTP configuration, whereas it should be `urls`.

https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-autodiscover.html

If you set `hosts` instead of `urls`, following the example, you get:

```
Check failed for config &{{<nil> } <nil> 0xc42011fd40}: job err missing required field accessing 'urls', won't start runner
```

**Comment by alvarolobato** [comment]
Probably related to https://github.com/elastic/kibana/issues/34684

**Comment by andrewvc** [comment]
Patch here: https://github.com/elastic/beats/pull/11891
