### ISSUE TITLE
License checked assumes license UIDs are hex encoded

### ISSUE THREAD

**Issue by tsg** [elastic/beats#11640]
When running Beats master or 6.7.0 against one of our test clusters, we got an error like this one:

```
could not extract license information from the server response: encoding/hex: invalid byte: U+0074 't']
```

We've tracked it down to the fact that the `license.uid` in our development license contains a `t` character, so it's not valid hex. From what I understand, real customer licenses don't have these issue, and should only be hex, but it's probably better to just treat it as a string, to avoid such issues in the future.

**Comment by tsg** [comment]
FYI @ph @urso @monicasarbu.

**Comment by ph** [comment]
@tsg does that mean the test cluster in question don't have a valid license?

**Comment by nyurik** [comment]
Would it be possible to use a hex UUID for the platinum license? There are multiple places that check the validity of the license code, so it might be safer to always adhere to a proper hex UUID - e.g. map tile server checks it, and the tile license checker relies on it too. There could be other places that I am not aware of that could also cause issues.
