### ISSUE TITLE
Provide Beat-specific upgrade instructions

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#11655]
Right now, we have one set of instructions for upgrading all the Beats. The commands show metricbeat, which isn't ideal for users who are upgrading other Beats.

@cjcenizal indicated that it would be useful to have instructions specific to each Beat rather than general instructions, so users don't have to look at content that is not relevant to them.

It wouldn't be hard to make the content generic and create multiple topics that contain Beat-specific content.

**Comment by cjcenizal** [comment]
In terms of structuring content, I envisioned a central page titled "Upgrading from 6.x to 6.x" (or something like that), with a list of links to each Beat's specific upgrade steps.

**Comment by dedemorton** [comment]
No longer planning to make this change so I'm closing this issue.
