### ISSUE TITLE
Apache module to support non-standard ports

### ISSUE THREAD

**Issue by qmaxquique** [elastic/beats#11656]
**Apache module to use non standard ports?**
Hello!

I've a few HTTP servers running Apache over non standard ports like 8080, 8090, etc.. I have been trying to configure the metricbeat apache module to get the stats from these ports but looks like I could not find a way to configure it yet, so I assume (as I didn't see it documented anywhere) it's not possible to specify another ports than the standard 80 and 443.

I apologize beforehand if this is just a dumb mistake on my end.

Thank you!

**Comment by ruflin** [comment]
I think you should be able to the port to your hosts config. Can you open a topic on discuss for this? https://discuss.elastic.co/c/beats/metricbeat Closing this as we try to keep it for confirmed bugs.

On discuss please also put in the config you use, log files, versions you use etc.
