### ISSUE TITLE
add_cloud_metadata processor overwrites fields when field keys contains dots

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#11697]
In https://github.com/elastic/beats/pull/11612, we realized when `overwrite` flag equals `false` in add_cloud_metadata processor, it checks if `cloud` field exists but can't deal with when field key containing dots for example `cloud.provider`.  Please see `TestRetrieveAWSMetadata` in provider_aws_ec2_test.go for more details. 

This PR is to discuss if add_cloud_metadata processor needs to deal with dots in field keys and if so what's the best implementation here.

**Comment by kaiyan-sheng** [comment]
In https://github.com/elastic/beats/pull/11612, I tried out some code to check if field key starts with `cloud.`, if so, add_cloud_metadata should not overwrite cloud fields: https://github.com/elastic/beats/blob/38badaa57f14922562520ee38de7b9b5aba0aacf/libbeat/processors/add_cloud_metadata/add_cloud_metadata.go#L372

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
