### ISSUE TITLE
Multiple files types in one Index?

### ISSUE THREAD

**Issue by fatmanmclone90** [elastic/beats#1169]
Our applications log in either JSON format or simple text format.  Both are being sent to ElasticSearch by Filebeat in a single Index.

How could we setup the Elasticsearch templates to handle the two different types separately?  Once JSON support is introduced into Filebeat we want to be able to query on JSON elements but also simply display the text logs as well.  Will this be supported?

Or is there anyway to send logs from different prospectors to their own index in Elasticsearch, so that each type is processed separately?

**Comment by ruflin** [comment]
If you want to split up your logs to different index and also do some processing, you need to send the logs to Logstash. In logstash you can split the events by types and send them to different ES indices.

**Comment by RehanSaeed** [comment]
@ruflin What if the JSON and text logs have different file extensions? Would a future version of filebeat supporting JSON send those logs to ElasticSearch using different templates based on the file extension?

**Comment by ruflin** [comment]
@RehanSaeed Interesting idea. So far libbeat does not support any routing of events based on the event content (or filename). The comment here is somehow related to this: https://github.com/elastic/beats/issues/1115#issuecomment-193141625 The main problem is that it adds a lot of complexity on the output side.

**Comment by RehanSaeed** [comment]
As a workaround, can we start multiple instances of the filebeat service, each with it's own config?

**Comment by ruflin** [comment]
@RehanSaeed That should work. Make sure to have to different paths for the registry file.

**Comment by monicasarbu** [comment]
@RehanSaeed I hope the workaround with two instances of Filebeat work well for you. I am closing the GitHub issue, but feel free to re-open it if it doesn't work for you.
