### ISSUE TITLE
[Filebeat] RabbitMQ Filebeat module

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#11692]
# Metricbeat Module / Dataset release checklist

This checklist is intended for Devs which create or update a module to make sure modules are consistent.

## Modules

For a fileset to go GA, the following criterias should be met:

* [x] Supported versions (of RabbitMQ) are documented
* [x] Supported operating systems are documented (if applicable)
* [x] System tests exist
* [x] Automated checks that all fields are documented
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] ~~Dashboards exists (if applicable)~~
* [x] ~~Kibana Home Tutorial (if applicable)~~
  * [x] ~~Open issue in [EUI repo](https://github.com/elastic/eui) to add [icon for module](https://elastic.github.io/eui/#/display/icons) if not already exists.~~
  * [x] ~~Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).~~
* [x] Test log files exist for the grok patterns
* [x] Generated output for at least 1 log file exists

## Filebeat module

* [x] Test log files exist for the grok patterns
* [x] Generated output for at least 1 log file exists

**Comment by jfsiii** [comment]
Working on this in https://github.com/jfsiii/beats.

Still WIP but as of https://github.com/jfsiii/beats/commit/d858af39862ba967d6b617faec74e60e0a3c2415 it can process single and multiline logs messages and extract key ECS fields like `@timestamp`, `log.level`, and `message`
