### ISSUE TITLE
Backward's compatibilty breaks with filebeat 6.7.0!

### ISSUE THREAD

**Issue by Fabian1976** [elastic/beats#11693]
I'm updating from filebeat 6.3.2 to 6.7.0. According to [semver](https://semver.org/), this should be a minor update which should be backwards compatible.
But it isn't.

We use Kafka as an output for Filebeat and support for Kafka 0.10 is stripped in 6.7.0.

If support for newer Kafka version was just added, it would comply with semver. But removing compatibility for older versions, doesn't comply to proper versioning. It should have been a major version bump.

Please be aware of this in the future.

I posted this under bug, but it could also be flaky testing.

OS: Linux
Filebeat version: 6.3.2 and 6.7.0
Steps to reproduce:
  Install Kafka version 0.10
  Install Filebeat 6.3.2 and configure Kafka as output (all is functioning fine)
  Upgrade to Filebeat 6.7.0 (all should be fine, but it is not)
Symptom:
  Filebeat keeps trying to connect to Kafka. Kafka logs show this message:
```org.apache.kafka.common.errors.InvalidRequestException: Error getting request for apiKey: 0 and apiVersion: 3
Caused by: java.lang.IllegalArgumentException: Invalid version for API key 0: 3
```

**Comment by kaiyan-sheng** [comment]
Seems like for filebeat 6.3 https://www.elastic.co/guide/en/beats/filebeat/6.3/kafka-output.html, it's compatible with output from Kafka 0.8, 0.9, and 0.10. But in filebeat 6.7 https://www.elastic.co/guide/en/beats/filebeat/6.7/kafka-output.html, it's compatible with Kafka versions in between 0.11 and 2.0.0.

**Comment by ruflin** [comment]
If I remember correctly, there were some breaking changes between the versions and we opted to support the newer ones especially as the 0.1* releases were pre GA releases.

I would agree that this is perhaps not 100% semver compatible but I would argue quite a few projects with external dependencies and different release cycles sometimes faces this issue. If the external dependency makes breaking changes during a minor release, a decision has to be made.

I'm closing this for now as I don't expect us to provide a fix here. 

@Fabian1976 One thing I'm curious about is if there is something specific holding you back from upgrading your Kafka version?

**Comment by Fabian1976** [comment]
@ruflin There isn't something holding us back, but it increases the scope, of what should be a minor update without breaking changes, a lot. Semver is there for a reason. It's just disappointing.
