### ISSUE TITLE
Add the entity_id to the add_process_metadata processor

### ISSUE THREAD

**Issue by aarju** [elastic/beats#11695]
**Describe the enhancement:**
Add the event_id value from the Auditbeat System module to the add_process_metadata processor. 
With the following metadata processor I should be able to enrich each Process event so that each event contains two entity_id fields, one for the event, and the entity_id of the parent process
 
processors:
- add_process_metadata:
    match_pids: [process.ppid]
    target: process.parent

**Describe a specific use case for the enhancement or feature:**
When investigating a process I would like to be able to also see all activity by the parent process. For example, if I am investigating a security alert on a process whose parent process is bash I would use a Kibana dashboard to query elasticsearch for all events with the matching parent process entity_id to see all activity by that specific bash process. Right now I only have the ppid for investigations and this field is not unique enough when querying an elasticsearch instance with events from more than one system.

See https://discuss.elastic.co/t/auditbeat-system-module-add-parent-process-entity-id-field-to-process-and-socket-events/174610 for discussion about this.

**Comment by andrewkroh** [comment]
An alternative proposed by @cwurm is to enhance the system process dataset to always add information about the parent process, effectively building this feature into the dataset.
