### ISSUE TITLE
Example beats config files show old index patterns

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#1170]
Related to issue #1159: The configuration files for each of the beats (for example, [packetbeat.yml](https://github.com/elastic/beats/blob/master/packetbeat/packetbeat.yml) still mention the older index pattern:

````
# Optional index name. The default is "topbeat" and generates
    # [topbeat-]YYYY.MM.DD keys.
````
This should say:
topbeat-* keys

@ruflin Thought you (or someone in dev) would want to fix this problem since it's in the code. I'll take care of the doc changes.

**Comment by andrewkroh** [comment]
The comment in the config files is correct. This is the daily index pattern that Beats use when they write to ES.

In Kibana and ES queries, `topbeat-*` is used to match against indexes like `topbeat-2016.03.16`.

**Comment by dedemorton** [comment]
Ohhhh thanks for the clarification!
