### ISSUE TITLE
[Filebeat] No way to disable use of proxy config defined in env

### ISSUE THREAD

**Issue by bczifra** [elastic/beats#11713]
There is currently no way to tell Filebeat to ignore the HTTPS_PROXY or HTTP_PROXY environmental variables aside from relying on another environment variable, the NO_PROXY variable. In Windows environments this is [particular difficulty](https://docs.microsoft.com/en-us/windows/desktop/services/service-startup) because:
>The service control manager does not support passing custom environment variables to a service at startup. Also, the service control manager does not detect and pass on changes to environment variables as the service is running. 

Filebeat should support a configuration option of its own for this purpose.

**Comment by kvch** [comment]
Hints to get started:
A new option needs to be added to all outputs to disable proxy configuration of a Beat. The function `transport.ProxyDialer` needs to be modified to allow disabling proxy.
