### ISSUE TITLE
metricbeat5.4: Compilation finished with exit code 2

### ISSUE THREAD

**Issue by Bruce2jiang** [elastic/beats#11719]
metricbeat\main.go:21:12: undefined: beat.Run
metricbeat\main.go:21:31: undefined: beater.New

Compilation finished with exit code 2

**Comment by andrewkroh** [comment]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

Definitely include more information about what you are running and trying to accomplish when you post to the Discuss forum. That will help us help you.
