### ISSUE TITLE
Heartbeat 6.7 regression bug; http mode:all always logs a false or incomplete UP

### ISSUE THREAD

**Issue by hyksos** [elastic/beats#11737]
Heartbeat 6.7 when using the mode:all of the type:http monitor will generated false/broken UP events for DOWN and UP targets... in addition to real/expected UP/DOWN events representing the true status of the monitored target. Minimal repro case below. This behavior can't be reproduced with heartbeat < 6.7.0 (tested with 6.7.1, 6.7.0, 6.6.2, 6.6.1, 6.6.0)

For confirmed bugs, please report:
- Version: 6.7.0 6.7.1
- Operating System: centos 7 (official heartbeat docker image)
- Discuss Forum URL: https://discuss.elastic.co/t/heartbeat-6-7-regression-bug-mode-all-always-logs-a-false-up/174892
- Steps to Reproduce: 

1. heartbeat.docker.yml content:
```yaml
heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://google.com #reachable target
    - http://elastic.co:8888 #unreachable target
  mode: all
  ipv6: false
  timeout: 2s
```

2. Start heartbeat
```bash
docker run --volume="$(pwd)/heartbeat.docker.yml:/usr/share/heartbeat/heartbeat.yml:ro"   docker.elastic.co/beats/heartbeat:6.7.1   --strict.perms=false -e  -E output.console.enabled=true
```

3. Results:
Bad UP event for google.com(reachable target), notice all the missing fields that should come with a normal UP event.
```json
{
  "@timestamp": "2019-04-10T04:39:40.159Z",
  "@metadata": {
    "beat": "heartbeat",
    "type": "doc",
    "version": "6.7.1"
  },
  "beat": {
    "name": "29e998770c99",
    "hostname": "29e998770c99",
    "version": "6.7.1"
  },
  "monitor": {
    "type": "http",
    "duration": {
      "us": 1607
    },
    "status": "up",
    "scheme": "http",
    "id": "http@http://google.com",
    "name": "http"
  },
  "http": {
    "url": "http://google.com"
  },
  "tcp": {
    "port": 80
  },
  "event": {
    "dataset": "uptime"
  },
  "host": {
    "name": "29e998770c99"
  }
}
```

Bad UP event for elastic.co:8888(unreachable target), notice all the missing fields that should come with a normal UP event.
```json
{
  "@timestamp": "2019-04-10T04:39:40.159Z",
  "@metadata": {
    "beat": "heartbeat",
    "type": "doc",
    "version": "6.7.1"
  },
  "tcp": {
    "port": 8888
  },
  "event": {
    "dataset": "uptime"
  },
  "beat": {
    "name": "29e998770c99",
    "hostname": "29e998770c99",
    "version": "6.7.1"
  },
  "host": {
    "name": "29e998770c99"
  },
  "monitor": {
    "name": "http",
    "type": "http",
    "duration": {
      "us": 1561
    },
    "status": "up",
    "scheme": "http",
    "id": "http@http://elastic.co:8888"
  },
  "http": {
    "url": "http://elastic.co:8888"
  }
}
```

Good UP event for google.com(reachable target), notice that all the expected fields for a normal UP event are there.
```json
{
  "@timestamp": "2019-04-10T04:39:40.161Z",
  "@metadata": {
    "beat": "heartbeat",
    "type": "doc",
    "version": "6.7.1"
  },
  "beat": {
    "name": "29e998770c99",
    "hostname": "29e998770c99",
    "version": "6.7.1"
  },
  "host": {
    "name": "29e998770c99"
  },
  "http": {
    "rtt": {
      "content": {
        "us": 2312
      },
      "total": {
        "us": 96849
      },
      "write_request": {
        "us": 88
      },
      "response_header": {
        "us": 60115
      },
      "validate": {
        "us": 62428
      }
    },
    "response": {
      "status_code": 200
    },
    "url": "http://google.com"
  },
  "monitor": {
    "scheme": "http",
    "id": "http@http://google.com",
    "name": "http",
    "type": "http",
    "host": "google.com",
    "ip": "172.217.13.110",
    "duration": {
      "us": 96972
    },
    "status": "up"
  },
  "resolve": {
    "host": "google.com",
    "ip": "172.217.13.110",
    "rtt": {
      "us": 1601
    }
  },
  "tcp": {
    "port": 80,
    "rtt": {
      "connect": {
        "us": 1802
      }
    }
  },
  "event": {
    "dataset": "uptime"
  }
}
```

Good DOWN events (x4) for elastic.co:8888(unreachable target), notice that all the expected fields for a normal DOWN event are there. There are 4 of those events, all good, since we use the setting "mode:all". Only one such event is shown here, the other 3 are for the other IPs you get for an elastic.co DNS resolution where I am (Multi A DNS record). So you get 4 good DOWN event, 1 per IP.
```json
{
  "@timestamp": "2019-04-10T04:39:40.161Z",
  "@metadata": {
    "beat": "heartbeat",
    "type": "doc",
    "version": "6.7.1"
  },
  "event": {
    "dataset": "uptime"
  },
  "beat": {
    "name": "29e998770c99",
    "hostname": "29e998770c99",
    "version": "6.7.1"
  },
  "host": {
    "name": "29e998770c99"
  },
  "tcp": {
    "port": 8888
  },
  "monitor": {
    "type": "http",
    "host": "elastic.co",
    "ip": "151.101.2.217",
    "status": "down",
    "duration": {
      "us": 2001576
    },
    "scheme": "http",
    "id": "http@http://elastic.co:8888",
    "name": "http"
  },
  "resolve": {
    "host": "elastic.co",
    "ip": "151.101.2.217",
    "rtt": {
      "us": 1533
    }
  },
  "http": {
    "url": "http://elastic.co:8888"
  },
  "error": {
    "type": "io",
    "message": "Get http://elastic.co:8888: dial tcp 151.101.2.217:8888: i/o timeout"
  }
}
```

[...] This continues of course, for every interval. There is always 2 bad UP event, followed by the truth; the normal expected events, either UP or DOWN depending on the true status of the target.

Using "mode:any" in the monitor config, you can't replicate, all events are good and true. There is of course only 1 DOWN event for elastic.co:8888, since mode:any only checks one of the IP.
Using heartbeat 6.6.2 you can't replicate.

**Comment by hyksos** [comment]
This also replicate, you get a broken UP event with missing fields, in addition to a true good UP event with all the required fields:

```yaml
heartbeat.monitors:
- type: icmp
  schedule: '@every 5s'
  hosts:
    - www.google.com
  mode: all
  ipv6: false
  timeout: 2s
```

Again if you flip it to "mode:any" the broken UP event with missing field stops and you get the expected behavior. Only 1 good UP event with all the expected fields.

I also tested a target which is a non-existent DNS record, could not replicate, either in mode:all or mode:any. You get the expected, correct DOWN event and that's it.

I also tested a target which is a non-pingable IP, could not replicate, either in mode:all or mode:any. You get the expected, correct DOWN event and that's it.

I also tested a target which is a pingable IP, could not replicate, either in mode:all or mode:any. You get the expected, correct UP event and that's it.

**Comment by hyksos** [comment]
Works ok with either mode: all or any, all expected events, nothing broken or false.
```yaml
heartbeat.monitors:
- type: icmp
  schedule: '@every 5s'
  hosts:
    - 8.8.8.8 # pingable
    - 2.2.2.2 # non-pingable
  mode: all
  ipv6: false
  timeout: 2s
```

Works ok with either mode: all or any, all expected events, nothing broken or false.
```yaml
heartbeat.monitors:
- type: icmp
  schedule: '@every 5s'
  hosts:
    - www.idonotexist-forreal.com # does not resolve
  mode: all
  ipv6: false
  timeout: 2s
```

**Comment by ruflin** [comment]
This initially reminded me of https://github.com/elastic/beats/pull/10777 but it seems to be an other issue.

**Comment by odacremolbap** [comment]
Able to reproduce.
Also an issue for 7.x

**Comment by andrewvc** [comment]
So, the root issue here, it seems, is that there is some category of error that is no longer being handled correctly due to one of the refactors. All of the erroneous up events also do not have an `error` field set.

The status is set to `down` when the error is set, so my suspicion is that some error case is not being handled correctly.

**Comment by andrewvc** [comment]
I have an initial fix here: https://github.com/elastic/beats/pull/11895, which needs some work tomorrow to become reviewable.

The root cause is that the `all` ping mode now spawns multiple sub-tasks, but the parent task still runs as a job, even though it tests very little, and will always succeed so long as the DNS query does.

The right solution is to keep that task, but to let jobs mark themselves as `discardable` so that their associated event disappears.
