### ISSUE TITLE
Filebeat log4j org.apache.log4j.RollingFileAppender questions

### ISSUE THREAD

**Issue by zhaopei8948** [elastic/beats#11736]
file is logs/ecss/ecss.log, fixed size 10M
After more than 10M, the file is rewritten and offset of filebeat records is always at the end。
How to send the current new file content to elasticsearch？

**Comment by kvch** [comment]
Please post your question on our discuss forum: https://discuss.elastic.co/
GH issues are reserved for verified bugs.
