### ISSUE TITLE
RootCmd

### ISSUE THREAD

**Issue by Bruce2jiang** [elastic/beats#11741]
github.com\elastic\beats\metricbeat\main.go:34:23: "github.com/elastic/beats/metricbeat/cmd".RootCmd.execute undefined (type *"github.com/elastic/beats/libbeat/cmd".BeatsRootCmd has no field or method execute

**Comment by ruflin** [comment]
Could you share a bit more details here?

**Comment by Bruce2jiang** [comment]
compile fail

**Comment by Bruce2jiang** [comment]
I have spent four days solving this problem,so can you give me a 
git address about an useful develop environment project??

**Comment by ruflin** [comment]
Can you share a bit more about your setup and how you try to compile Beats? Which go version are you on?

**Comment by Bruce2jiang** [comment]
my go version is 'go version go1.12.3 windows/amd64, which MetricsBeat version suitable for my go version ??I did not find the answer on the official website

**Comment by Bruce2jiang** [comment]
when I run my project , the console of the develop tool show this message:
GOROOT=C:\Go #gosetup
GOPATH=C:\gowork #gosetup
C:\Go\bin\go.exe build -o C:\Users\chengbiao\AppData\Local\Temp\___go_build_main_go__1_.exe C:/gowork/github.com/elastic/beats/metricbeat/main.go #gosetup
C:\Users\chengbiao\AppData\Local\Temp\___go_build_main_go__1_.exe #gosetup
Exiting: error loading config file: open metricbeat.yml: The system cannot find the file specified.

**Comment by ruflin** [comment]
Ah you get the error when your run metricbeat? Try `mage update` which should generate the missing file. Also I see you are executing metricbeat from an other directory then inside the go path. Try to build the binary directly there with `mage build` and then run it out of this directory. Like this it will also find the config file etc.
