### ISSUE TITLE
Heartbeat docs need more detail about loading dashboards

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#11748]
For 7.0, Heartbeat dashboards have moved to an external repository, but there are no details about how to load the dashboards. The `setup --dashboards` command no longer works.
It's also not clear if or how the dashboards work with the settings documented here:  https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-dashboards.html.

Note that we have a `:no_dashboards:` flag that we can set in the index.asciidoc to suppress all content related to dashboards in files that are reused from libbeat, but I'm not sure it makes sense to use the flag because we do have dashboards...they're just in a different location than the other beats and it's not clear how to load them.

**Comment by dedemorton** [comment]
@andrewvc Can you provide more info here about how we should proceed with the 7.0 docs?

**Comment by ruflin** [comment]
@dov0211 You might help here?

**Comment by dov0211** [comment]
As we do not ship Heartbeat dashboard, i think that for now should set the `no dashboard` flag, as it is very confusing.
we need to discuss:
- should we bring back Heartbeat dashboard
- what should we do with uptime-contrib repo

**Comment by dov0211** [comment]
@dedemorton we agreed over our weekly meeting to set the `no dashboard` flag to in Heartbeat, in addition, we will add instructions on the contrib-repo on how to load the dashboard

**Comment by njbmartin** [comment]
The dashboard is also mentioned in the doc:
https://www.elastic.co/guide/en/beats/heartbeat/current/running-on-docker.html

This was the cause of my confusion. I like the uptime interface, but I'd want to add those visualisations to a dashboard.

**Comment by dedemorton** [comment]
@njbmartin Good catch. I already have a PR in progress in a local branch that turns on the no_dashboards flag. I'll also fix the shared docker content.

**Comment by dedemorton** [comment]
Here's the PR: https://github.com/elastic/beats/pull/11769

**Comment by andrewvc** [comment]
Should this PR still be open? Or is this waiting on those instructions to be added to https://github.com/elastic/uptime-contrib ? If so, @dov0211 is that something you'd be able to tackle?

**Comment by dedemorton** [comment]
@andrewvc Let's wait until the instructions are available in https://github.com/elastic/uptime-contrib. Otherwise users won't know how to load the dashboards that we point them to.

**Comment by dedemorton** [comment]
@dov0211 If you can tell me how to import manually from /elastic/uptime-contrib, I can update the readme. I tried a couple different ways (based on current docs) but it didn't work. I'd like to get this resolved soon because users are hitting this issue. For example: https://www.elastic.co/guide/en/beats/devguide/current/import-dashboards.html. Maybe if you answer the forum post, I can take your answer and update the readme?

**Comment by andrewvc** [comment]
As an update here we've added instructions to the README on https://github.com/elastic/uptime-contrib . Thoughts on next steps @dedemorton?

**Comment by dedemorton** [comment]
@andrew-moldovan This OK for now, but I worry about the content in GitHub (links, UI steps) getting out of date over time. Given current plans, maybe it's not worth worrying about at the moment, so I'll close this. Thanks!
