### ISSUE TITLE
Functionbeats manual deployment procedure/ package build

### ISSUE THREAD

**Issue by radoondas** [elastic/beats#11781]
**Describe the enhancement:** 
Hi,
we would like to implement option to perform manual deployment of Functionbeats

**Current state:**
We are currently looking into implementing Functionbeat into our AWS environment but all the documentation seems to guide you to using the automated deployment feature that preps all required resources for you. It seems that we cannot do any manual deploy at the moment as all of the documentation seems to be based around this automated deploy feature (apologies if i have missed the pages).

**Reason:**
As we have a company wide governance over AWS accounts, no one can actually deploy using this feature as different people have access over the different resources and we have different IAM roles that also have different resource access. 

**Request:**
We would like to be able easily create manual package with correct IAM roles. This package can be later deployed by others who are supposed to do so. 

**Questions and considerations:**
It appears to be that one of the functions is to create a package for your own deployment which suggests that I can ignore the deploy and set it up myself. Its this that seems to lack documentation. 
I cant seem to find what resources need setting up in AWS for this to work. I have created an IAM role for the lambda and the lambda itself but its the notification and triggers that i am unsure of. Obviously what i have setup is currently guess work so if you have any documentation for the required setup or even what the './functionbeat deploy' sets up then that would be helpful. 

Thanks.

**Comment by ph** [comment]
Closed by https://github.com/elastic/beats/pull/13886
