### ISSUE TITLE
Missing field changes in the 7.0 breaking changes doc

### ISSUE THREAD

**Issue by webmat** [elastic/beats#11790]
In migrating Beats to ECS for 7.0, we've initially used the `ecs-migration.yml` file as a place to list all fields that were being aliased or moved for the ECS migration specifically.

Some Beats also appear to have made breaking changes to fields independently of the ECS migration.

As far as I understand, the [Breaking changes in 7.0](https://www.elastic.co/guide/en/beats/libbeat/7.0/breaking-changes-7.0.html) is generated based on the `ecs-migration.yml` file, which currently doesn't list all the changes.

The result is that not all of the field breaking changes are listed on this page.

The "breaking changes" page should be updated to include all fields that have a breaking change. See comments below, for non-exhaustive notes of what I observed.

Note that the YAML file could potentially be a very useful file to send customers to, in order to help them perform their migration. So my preference would be that this file is renamed/repurposed to list all changes from 6 to 7, not just the ECS changes.

**Comment by webmat** [comment]
First set of conflicts I've noticed was in Packetbeat, where we have the following breaking changes:

```
- error.code          keyword => long
- final               keyword => boolean
- http.request.body   text => object
- http.response.body  text => object
- http.response.code  keyword => long
- real_ip             keyword => ip
- server              keyword => object
- service             keyword => object
- source.ip           keyword => ip
- source.port         keyword => long
- vlan                keyword => long
```

These don't appear in the breaking changes page

**Comment by webmat** [comment]
Note actually that both the `.body` fields are present and listed as "renamed" in the docs.

The vast majority of the fields that are renamed come with an alias. However the HTTP body fields cannot be aliased, since the payload is now nested deeper under the same key (hence the conflict "text => object" above).

So perhaps there could be an additional column in the "renames" tables that indicates which fields come with an alias, and which don't.

Note #2 on Packetbeat: the breaking changes state that `http.response.code` has moved to `http.response.status_code`. But the 7.0 index shows `http.response.code` as still there, but changed from keyword to long. Seems like there's a discrepancy to look into here as well

**Comment by ruflin** [comment]
Initially we put only the ECS breaking changes into the file but later added all the breaking changes. Probably we should have renamed the file ...

@andrewkroh Could you look into the above issues?

**Comment by webmat** [comment]
Was about to list a few breaking changes I had noticed for Filebeat as well. Will dig them up and add them momentarily.

Documenting these should happen for all the other Beats as well.

**Comment by webmat** [comment]
Note that Kibana displays a field as in conflict with a type change, even if the field has moved (like `read_timestamp`), and that the alias destination field is of a different type (like `event.created`).

This initially confused me in the Packetbeat list above, where I listed a type change for `http.response.code`. This field is correctly aliased to the new ECS field, and the conflict would read more accurately as `http.response.code (keyword) => http.response.status_code (long)`, for example.

**Comment by webmat** [comment]
Here are the Filebeat conflicts I've noticed, that should be better documented:

```
auditd.log.pid    keyword => long
auditd.log.ppid   keyword => long
elasticsearch.audit.request   keyword => object
error.code        keyword => long
haproxy.destination.ip        keyword => ip
mysql.slowlog.ip  keyword => ip
read_timestamp    keyword => date
source            keyword => object
system.auth.groupadd.gid      long => keyword
system.auth.timestamp         keyword => date
system.auth.useradd.gid       long => keyword
system.auth.useradd.uid       long => keyword
system.syslog.pid             keyword => long
system.syslog.timestamp       keyword => date
user_agent.device             keyword => object
```

Final not about this: the conflicts have showed up for me only once data was coming in. Which means these two lists are far from exhaustive.

**Comment by dedemorton** [comment]
Can we also add some information to tell users what they need to do to resolve these conflicts? The instruction to reindex the data is too vague.

**Comment by inqueue** [comment]
I received a report of a broken pipeline depending on the `source` field from Filebeat 6.x after upgrading to 7.1. The documentation changes outlined in this issue would have helped isolate the cause since dropping the `source` Filebeat field is not mentioned in breaking changes. Can we please get these important updates added to public documentation? Thanks!

**Comment by dedemorton** [comment]
Closing this issue because it is stale. Going forward, we need to do a much better job of tracking and documenting field changes that impact users.
