### ISSUE TITLE
Should we remove the Reference container from the documentation?

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#1179]
With the reorganization of the doc, I wanted to make it easier for users to find reference information by grouping the information together under a container called Reference. We do this in some of the other docs (Shield and Watcher). But after talking to @ruflin last month, I'm wondering if the Reference container is helpful or just an extra layer that users need to click through. 

What do you think? Do you like it? Not like it? Or don't care? I don't want to overthink this, but tweaking the TOC at this point would be easy and wouldn't break any links that point to the doc. If we agree to remove the Reference container, I would simply move the topics to logical locations in the doc. So, for example, in the Filebeat doc we would have:

Overview
Getting Started with Filebeat
Configuring Filebeat - _I'll expand the contents of this section so you can see where things will go_
- YAML Tips and Gotchas
- Regular Expression Support
- Configuration Options
- Securing Communication
- Specifying Multiple Processors

Exported Fields
Troubleshooting
Migrating from Logstash Forwarder to Filebeat

**Comment by ruflin** [comment]
I like the reference container, my concern is that it takes for example too many links to get to the filebeat config options. My current path: `elastic.co / docs / Filebeat / Reference / Configuration Options / Filebeat`. This is 5 clicks. One thing that I think is a general issue with all docs is that there are sometime almost empty pages. For example https://www.elastic.co/guide/en/beats/filebeat/current/reference.html is almost empty and the links are somehow hidden on the right side. Why not have on this page directly the expanded possible links? I know there is a + sign on the right but I really never click it.

**Comment by dedemorton** [comment]
@ruflin You know about the Search function on the main page, right? :-) Just kidding. I do think people will get to the content in lots of different ways, and searching is (hopefully) a more common use case than clicking through the TOC. 

I agree with your comment about our container topics. Other tools I've used (like DITA XML) automatically add links to container topics. I think our doc build process tries to do that by expanding the TOC on the right to show the section you're in, but it's kind of wonky because it doesn't highlight the actual topic that you're looking at. Plus, for really short topics, the relevant stuff might not even be visible eon the page. 

To solve this problem, I've added summary links to a couple of topics where they were really necessary, and I could do that for all the container topics, but it becomes a hack that we need to remember to maintain over time. It would be better if the doc build could generate overview links automatically. I'll investigate this because it's come up before. Thanks for the input!

**Comment by dedemorton** [comment]
Note that I've opened https://github.com/elastic/docs/issues/82 to see if we can get some kind of automation for adding links to container topics.

**Comment by dedemorton** [comment]
No luck on getting the doc build process changed to automate the generation of links in container topics. 

To fix the container topic problem, we'll need to consider adding links manually. I'm going to leave the Reference container as it is for now, and close this issue for because it sounds like the current organization of reference content isn't causing problems. 

I'll start adding overview links on a case-by-case basis to container topics (as time allows) if I believe that it helps users find content more easily.
