### ISSUE TITLE
heartbeat 7.0.0 missing kibana dashboards

### ISSUE THREAD

**Issue by jasonslater2000** [elastic/beats#11802]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 7.0.0 
- Operating System: Mac
- Discuss Forum URL: n/a
- Steps to Reproduce: unpack .tar.gz, notice files are missing.  

also notice that ./heartbeat setup produces the following output:
Index setup complete.
Loading dashboards (Kibana must be running and reachable)
*Skipping loading dashboards, No directory /Users/jasonslater/Downloads/t/heartbeat-7.0.0-darwin-x86_64/kibana/7*

tar -tvf heartbeat-7.0.0-darwin-x86_64.tar.gz 

-rw-r--r--  0 root   root    82511 Apr  5 14:57 heartbeat-7.0.0-darwin-x86_64/fields.yml
drwxr-xr-x  0 root   root        0 Apr  5 14:57 heartbeat-7.0.0-darwin-x86_64/kibana/
-rw-r--r--  0 root   root       41 Apr  5 14:59 heartbeat-7.0.0-darwin-x86_64/.build_hash.txt
-rw-------  0 root   root     6058 Apr  5 14:57 heartbeat-7.0.0-darwin-x86_64/heartbeat.yml
-rw-r--r--  0 root   root    50808 Apr  5 14:57 heartbeat-7.0.0-darwin-x86_64/heartbeat.reference.yml
drwxr-xr-x  0 root   root        0 Apr  5 14:52 heartbeat-7.0.0-darwin-x86_64/monitors.d/
-rw-r--r--  0 root   root     2575 Apr  5 14:52 heartbeat-7.0.0-darwin-x86_64/monitors.d/sample.http.yml.disabled
-rw-r--r--  0 root   root     1568 Apr  5 14:52 heartbeat-7.0.0-darwin-x86_64/monitors.d/sample.icmp.yml.disabled
-rw-r--r--  0 root   root     3252 Apr  5 14:52 heartbeat-7.0.0-darwin-x86_64/monitors.d/sample.tcp.yml.disabled
-rwxr-xr-x  0 root   root 29562812 Apr  5 14:58 heartbeat-7.0.0-darwin-x86_64/heartbeat
-rw-r--r--  0 root   root      839 Apr  5 14:59 heartbeat-7.0.0-darwin-x86_64/README.md
-rw-r--r--  0 root   root   168334 Apr  5 14:52 heartbeat-7.0.0-darwin-x86_64/NOTICE.txt
-rw-r--r--  0 root   root    13675 Apr  5 14:52 heartbeat-7.0.0-darwin-x86_64/LICENSE.txt

note there are no version folders under kibana directory

looking at 6.7.1, the files are there.

tar -tvf heartbeat-6.7.1-darwin-x86_64.tar.gz 

-rw-------  0 root   root     6027 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/heartbeat.yml
-rw-r--r--  0 root   root       41 Apr  2 08:05 heartbeat-6.7.1-darwin-x86_64/.build_hash.txt
drwxr-xr-x  0 root   root        0 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/
drwxr-xr-x  0 root   root        0 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/5/
drwxr-xr-x  0 root   root        0 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/5/dashboard/
-rw-r--r--  0 root   root     1496 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/5/dashboard/f3e771c0-eb19-11e6-be20-559646f8b9ba.json
drwxr-xr-x  0 root   root        0 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/5/index-pattern/
-rw-r--r--  0 root   root    15362 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/5/index-pattern/heartbeat.json
drwxr-xr-x  0 root   root        0 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/5/search/
-rw-r--r--  0 root   root     1097 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/5/search/02014c80-29d2-11e7-a68f-bfaa2341cc52.json
drwxr-xr-x  0 root   root        0 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/5/visualization/
-rw-r--r--  0 root   root     2109 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/5/visualization/091c3a90-eb1e-11e6-be20-559646f8b9ba.json
-rw-r--r--  0 root   root     2268 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/5/visualization/0f4c0560-eb20-11e6-9f11-159ff202874a.json
-rw-r--r--  0 root   root     1989 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/5/visualization/1738dbc0-eb1d-11e6-be20-559646f8b9ba.json
-rw-r--r--  0 root   root     1930 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/5/visualization/920e8140-eb1a-11e6-be20-559646f8b9ba.json
-rw-r--r--  0 root   root     1818 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/5/visualization/c65ef340-eb19-11e6-be20-559646f8b9ba.json
drwxr-xr-x  0 root   root        0 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/6/
drwxr-xr-x  0 root   root        0 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/6/dashboard/
-rw-r--r--  0 root   root    14033 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/6/dashboard/Heartbeat-http-monitor.json
drwxr-xr-x  0 root   root        0 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/6/index-pattern/
-rw-r--r--  0 root   root    15549 Apr  2 08:03 heartbeat-6.7.1-darwin-x86_64/kibana/6/index-pattern/heartbeat.json

**Comment by dov0211** [comment]
The team decided to remove Heartbeat dashboard from 7.0
https://github.com/elastic/beats/pull/10294
In case you would like to import it manually you can find the dashboard here https://github.com/elastic/uptime-contrib

**Comment by jasonslater2000** [comment]
got it.  so does that mean that heartbeat setup should not try looking at the kibana folder for dashboards, or alternatively could we add a readme item with instructions for installing from uptime-contrib?

**Comment by dov0211** [comment]
yes, we should add the instructions on the readme in the repo, this is something I am planning to add this week

**Comment by eedugon** [comment]
@dov0211 , also note that the default heartbeat.yml file is coming with this commented section:

```
#============================== Dashboards =====================================
# These settings control loading the sample dashboards to the Kibana index. Loading
# the dashboards is disabled by default and can be enabled either by setting the
# options here or by using the `setup` command.
#setup.dashboards.enabled: false
```

That should be considered as might cause confusion.
If a user enables it, the process will fail to start as it will be looking for the dashboards in the default directory.

**Comment by andrewvc** [comment]
We now document dashboards better here: https://www.elastic.co/guide/en/beats/heartbeat/current/view-kibana-dashboards.html

I've opened https://github.com/elastic/beats/pull/12769 to fix the config file

**Comment by andrewvc** [comment]
This issue isn't serving a lot of purpose at the moment, since there's only one minor item left here. I'm going to close it since https://github.com/elastic/beats/pull/12769 should address the remainder of the issue here.

**Comment by sastorsl** [comment]
There is still confusion on this issue.

Alt least the old documentation should clearly note the deprecation of built-in kibana dashboards, i.e. on the https://www.elastic.co/guide/en/beats/heartbeat/6.8/load-kibana-dashboards.html page.
