### ISSUE TITLE
Add steal to CPU Usage visualisation

### ISSUE THREAD

**Issue by z3ndrag0n** [elastic/beats#11803]
**Describe the enhancement:**
The metric beat default metricset gathers steal (system.cpu.steal.pct), but the default CPU Usage visualisation doesn't display it, just user, system, nice, irq, softirq and iowait. Please add a series for system.cpu.steal.pct (Aggregation average and the same options as the other CPU stats - Chart type: Line, Stacked: Stacked, Fill: 1, Line width: 1, Point size 0).
**Describe a specific use case for the enhancement or feature:**
This metric shows you how much CPU time you aren't getting, which in a virtualisation cluster, be it on-prem or Cloud, can be really important. If your steal time is basically visible on the chart at all, you potentially have performance issues that no tuning of the VM or the OS running inside will address.

**Comment by z3ndrag0n** [comment]
Folks please don't let this one die. It's important *especially* in cloud environments where the cloud provider has no commitment to not over-provisioning.

**Comment by fearful-symmetry** [comment]
`steal` has been in for a while now, looks like it never got linked to this issue. Closing.
