### ISSUE TITLE
Heartbeat Kubernetes host is wrong in the documentation

### ISSUE THREAD

**Issue by dov0211** [elastic/beats#11813]
In the Autodiscover documentation page of Heartbeat, the example for Kubernetes uses hosts under the HTTP configuration, whereas it should be URL instead.

https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-autodiscover.html

**Comment by andrewvc** [comment]
Fixed in https://github.com/elastic/beats/pull/11891
