### ISSUE TITLE
[metricbeat] Remove deprecated fields

### ISSUE THREAD

**Issue by roncohen** [elastic/beats#11835]
We have numerous fields that have been deprecated. They should be removed.

- [x] Docker https://github.com/elastic/beats/pull/27933
- [x] kafka
- [x] kubernetes https://github.com/elastic/beats/pull/28046
- [x] redis https://github.com/elastic/beats/pull/28246
- [ ] nats

This is not an exhaustive list. Part of this work is to find more deprecated fields and remove them.  We also need to discuss if we can remove these fields in a minor.

**Comment by exekias** [comment]
We need to come up with the full list of affected metrics.

About deprecating these in 7.x: 

Docs show deprecation warnings for the affected metrics ([example](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-docker.html#_read_fields_2)). Still some users may be using the deprecated metrics. I would suggest to check if we are providing good alternatives to all of them (probably yes), then it's probably safe to remove them.
