### ISSUE TITLE
Ship with default Beats users/roles with minimal permissions

### ISSUE THREAD

**Issue by fkelbert** [elastic/beats#11847]
Ideally, users should run Beats with minimal permissions. However, it is currently tedious to create corresponding users and roles, partially because [required privileges are not clearly documented](https://github.com/elastic/beats/issues/11845).

I propose to ship Elasticsearch with default Beats users/roles, providing just the bare minimum of privileges that are required to run Beats in production.

**Comment by fkelbert** [comment]
Instead of pre-installing those users, maybe it would also be an option to provide the user with the possibility to install these users using `filebeat setup --users`, or something along those lines.

**Comment by richiejarvis-elastic** [comment]
+1 on this - I dislike the idea of running beats with the elastic user permanently.  I assumed (wrongly as it turned out) that the system default  ```beats_system``` user would be the correct one with the correct perms out of the box.
