### ISSUE TITLE
[Metricbeat] Enhancement: systemd service support

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#11846]
I said "support" as I'm not sure where this would fit in, as a module, metricset, etc.

Right now, we're gathering data for processes and containers, including getting cgroup data for any given PID. Systemd is separate these (although related, obviously), and can be used to gather data per-service for IaaS/bare metal/etc.

For example, here's a systemd service for unifi running on a server in my home lab:

```
● unifi.service - unifi
   Loaded: loaded (/lib/systemd/system/unifi.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-03-21 22:07:25 UTC; 3 weeks 4 days ago
 Main PID: 3157 (jsvc)
    Tasks: 126 (limit: 2027)
   CGroup: /system.slice/unifi.service
           ├─3157 unifi -cwd /usr/lib/unifi {...}
           ├─3158 unifi -cwd /usr/lib/unifi {...}
           ├─3159 unifi -cwd /usr/lib/unifi {...}
           ├─3185 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java {...}
           └─3302 bin/mongod {...}
```

We get a list of all the processes associated with the service, the uptime, start time, count of tasks, and status. We can use the cgroup information to get resource usage for the service, although this may overlap with the system/process metricset, although we'd be formatting the data per-service as opposed to per-process, which may be helpful.

We can also get restart counts:
```
systemctl show unifi | grep 'NRestarts'
NRestarts=0
```
And if enabled via the service unit file, there are many other interesting features, such as IP accounting: http://0pointer.net/blog/ip-accounting-and-access-lists-with-systemd.html 

We can also list sockets exposed by systemd, and I'm willing to bet there's a lot of data lurking under `systemctl show` that we might find interesting.

**Comment by exekias** [comment]
I definitely see valuable info here, I wonder what's the best way to offer it to the user. For instance, `process` metricset could be enriched with info about the systemd unit they belong to (if any).

Having a standalone systemd metricset could also be interesting to watch info and status of all services

**Comment by fearful-symmetry** [comment]
Yah, that's an interesting idea. I wonder if there's some 'global' systemd metrics we could gather too. (count of services, sockets, jobs, etc)

**Comment by moetemad** [comment]
I would love to see this feature in Metricbeat. Right now I have my oen java application to handle this, but it would be nice to have it as a module in Metricbeat for sure.

**Comment by inspirit1986** [comment]
+1. to add systemd services status in metricbeat. :)

**Comment by kresss** [comment]
I think this issue is related to #6595.

**Comment by kresss** [comment]
Was this feature implemented and I missed it?

**Comment by fearful-symmetry** [comment]
@kresss we have a system/service metricset in 7.6: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-system-service.html

**Comment by kresss** [comment]
@fearful-symmetry That is great news. Thank you.
