### ISSUE TITLE
Docs: Improve documentation of required privileges

### ISSUE THREAD

**Issue by fkelbert** [elastic/beats#11845]
It seems that the Beats documentation does not clearly describe which are the minimum permissions required to run Beats in a production environment. The [Troubleshooting Beats upgrade issues guide](https://www.elastic.co/guide/en/beats/libbeat/current/troubleshooting-upgrade.html#user-unauthorized) seems to be a good start. However, I propose to integrate this and more information in the main documentation, somewhere within [Getting started with (File|Audit|Heart)beat](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-getting-started.html).

Security is the default with licensed Elasticsearch and we should make it easy for users to run Beats with minimum privileges required. E.g., the docs should answer the following questions:

- which are the minimum permissions needed to run Beats with ILM/Rollover
- which are the minimum permissions needed to run Beats with daily/weekly/monthly indices
- what are the permissions needed to install index templates
- what are the permissions needed to install Kibana dashboards

Ideally, the docs would also provide a short walk through:

- Which user (permissions) should be used to install templates/dashboards? Is it recommended to perform this one-off operation with the `elastic` user?
- Which user (permissions) should be used to run Beats in production?

Ideally, Beats would provide predefined users with minimal permissions. I will open a separate issue for that.

**Comment by dedemorton** [comment]
I merged a PR recently that should address some of your concerns: https://github.com/elastic/beats/pull/11329. You can see the updates under the security sections in the Beats docs. For example: https://www.elastic.co/guide/en/beats/filebeat/current/securing-beats.html.

Let me know if I can close this issue.

**Comment by fkelbert** [comment]
Looks good! Great work @dedemorton , thank you!
