### ISSUE TITLE
InitPaths not threadsafe

### ISSUE THREAD

**Issue by asanderson15** [elastic/beats#11869]
There is a race when using [InitPaths](https://github.com/elastic/beats/blob/master/libbeat/paths/paths.go#L94) during initial beat configuration if you initialize more than a single beat in parallel.

Calling `InitPaths` calls `Path.InitPaths` ([code](https://github.com/elastic/beats/blob/master/libbeat/paths/paths.go#L95)), where `Path` is a [shared global pointer](https://github.com/elastic/beats/blob/master/libbeat/paths/paths.go#L66). That method in turn calls `initPaths`, which [sets the global ptr to the Path ptr passed by the caller](https://github.com/elastic/beats/blob/master/libbeat/paths/paths.go#L101). This creates a race where, if `InitPaths` is called in parallel, the global `Path` ptr can be redirected before `MkdirAll` gets called, meaning that some paths are not properly created and that beat initialization will fail.

An easy fix to make this threadsafe would be to declare a global mutex corresponding to the `Paths` var and then to wrap the `Paths.InitPaths` call with it:

```
var pathsMutex sync.Mutex

...

func InitPaths(cfg *Path) error {
    pathsMutex.Lock()
    defer pathsMutex.Unlock()
	return Paths.InitPaths(cfg)
}
```

Callers can also do this on their side, but will generally not think to do so unless they're aware of this issue since this is pretty non-obvious without delving into the implementation, which is why I believe this should be fixed in the library itself.

- Version: >= 5.0
- Operating System: All
- Discuss Forum URL: https://discuss.elastic.co/t/initpaths-is-not-threadsafe/177519
- Steps to Reproduce: I was able to reliably reproduce by repeatedly calling `InitPaths` with sufficiently high parallelism (required parallelism varies based on environment) and then checking for expected directories that never got created.

**Comment by TDAbboud** [comment]
@ycombinator What would be the best way to get input on this issue from the elastic/beats team? We are happy to contribute this fix, but want to make sure we talk through the design / implementation first.

**Comment by ycombinator** [comment]
Pinging @elastic/beats for input.

**Comment by urso** [comment]
The Beats framework does not support to run instantiate multiple beats at the same time. There might be other unknown issues due to global state you might run into due to this.

**Comment by asanderson15** [comment]
Yes, we realized that the amount of global state has only increased over time on later versions after upgrading to latest beats, so agree this doesn’t make sense. Closing this out.
