### ISSUE TITLE
Document Functionbeat use cases

### ISSUE THREAD

**Issue by acchen97** [elastic/beats#11867]
We should better outline the Functionbeat use cases in the documentation for user clarity, either in the [overview page](https://www.elastic.co/guide/en/beats/functionbeat/current/functionbeat-overview.html) or a dedicated page.

Lambda is a natural integration point for many AWS services, and Functionbeat can be used in conjunction with it to stitch together integrations with many of these services. We currently have integrations with Cloudwatch Logs, SQS, and Kinesis, and we expect to enable more integrations over time. Currently, Functionbeat enables two core use cases:
1. Monitoring AWS services with Cloudwatch Logs
2. Event driven processing workflows with Kinesis and SQS

@dedemorton is this something you could help with? I'm happy to help provide more context if needed.

/cc @pieterhumphrey @DanRoscigno

**Comment by dedemorton** [comment]
@acchen97 Sure. Let's get it on the our "docs" roadmap for an upcoming release.
