### ISSUE TITLE
filebeat stats endpoint showing wrong value for endpoint

### ISSUE THREAD

**Issue by danielkasen** [elastic/beats#11874]
Looks like trying to use the libbeat.output.read.bytes is showing the wrong number. This is supposed to be the number of bytes read from a file correct? or am I missing that. My issue stems from the write.bytes outputting the compressed number and not the raw number so I was hoping to use this value to see the uncompressed bytes read.

**Comment by kvch** [comment]
Please post your question on Discuss: https://discuss.elastic.co/
GH issues are reserved for verified bugs.
