### ISSUE TITLE
[Filebeat] apache2 log directory not match?

### ISSUE THREAD

**Issue by DanielTimLee** [elastic/beats#11887]
**Describe the enhancement:**

At Fedora, `apache2` (as a `httpd`) package can be installed by `httpd-2.4.39-2.fc29.x86_64`
At RHEL 7, `httpd` can be installed with `httpd-2.4.6-88.el7.x86_64`

And on these OSes, `httpd` access/error logs are found in directory:

`/var/log/httpd/access_log`
`/var/log/httpd/error_log`

The log files are located `httpd` instead of  `apache2`
And also, log file names are in `*_log` not in `.log`

https://github.com/elastic/beats/blob/8caa332df41dd2fa45df66610e22f6b2f089b9de/filebeat/module/apache/access/manifest.yml#L3-L12

As the upper `filebeat/module/apache/access/manifest.yml` manifest file only 
defines the location of 
`var/log/apache2/access.log`

**Since these `httpd` packages save logs at as `/var/log/httpd/*_log` a default (at RH type OS),**
adding this directory to the manifest file will help `filebeat apache module` to run out of the box on these environments.

**Describe a specific use case for the enhancement or feature:**

Enhance will help `filebeat apache` to run out of the box.

**Comment by kaiyan-sheng** [comment]
Closing this issue since the fix https://github.com/elastic/beats/pull/11888 is merged.
