### ISSUE TITLE
Allow custom headers in http request

### ISSUE THREAD

**Issue by markwalkom** [elastic/beats#11886]
**Describe the enhancement:** We allow custom http headers when we [talk to  Elasticsearch](https://github.com/elastic/beats/issues/1768), it'd be handy if we had these in the http request for Metricbeat. That is, when we are calling the endpoint to collect the response.

**Describe a specific use case for the enhancement or feature:**
I am using [Bloomsky](https://www.bloomsky.com/) and they require an `Authorization` header when using their API. [This is an example Logstash config](https://github.com/markwalkom/bloomsky-on-elastic/blob/master/logstash.conf) using the `http_poller` that I'd like to be able to replicate in Metricbeat.

**Comment by exekias** [comment]
Hi @markwalkom, Metricbeat HTTP `json` metricset should be able to add custom headers, as it supports default HTTP parameters, see https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-metricbeat.html#_literal_headers_literal

I think we can close this?

**Comment by markwalkom** [comment]
Yep we can. I missed this as I didn't realise it was in the common HTTP settings!
