### ISSUE TITLE
[Heartbeat] Monitor - Add support for processing an array of objects from a JSON payload

### ISSUE THREAD

**Issue by eddieturizo** [elastic/beats#11884]
**Describe the enhancement:** 

Add support for processing an array of objects from a JSON payload.

https://www.elastic.co/guide/en/beats/heartbeat/6.6/configuration-heartbeat-options.html#monitor-http-check

**Describe a specific use case for the enhancement or feature:**

Sample JSON payload containing an array of objects to parse using a Heartbeat HTTP monitor:

```
{  
   "nimbuses":[  
      {  
         "host":"nimbus.a.b.net",
         "port":1234,
         "nimbusLogLink":"http://nimbus.a.b.net:8000/daemonlog?file=nimbus.log",
         "status":"Leader",
         "version":"1.2.2",
         "nimbusUpTime":"1h 47m 33s",
         "nimbusUpTimeSeconds":10622
      }
   ]
}
```

Another sample JSON payload containing an array of objects to parse using a Heartbeat HTTP monitor: 

```
{
    "something": [{
        "item1": "value1",
        "item2": "value2"
    }, {
        "item1": "value3",
        "item2": "value4"
    }]
}
```

where the HTTP monitor option would be able to access using something like: 

```
condition:
  equals:
    something[0].item1: "value1"
```

**Comment by andrewvc** [comment]
@eddieturizo have you seen the json option under [HTTP Options](https://www.elastic.co/guide/en/beats/heartbeat/master/configuration-heartbeat-options.html#monitor-http-options) in the docs? I think that might do what you need.

**Comment by andrewvc** [comment]
Closing due to a lack of activity. Please open a new issue if this is ongoing.

**Comment by amerinoo** [comment]
Hi, I'm also interested in this feature. 

In my case I need to know the lenght of an array, is it possible? 

If not, is it possible to check a field into the json array like array[0].field1: "value"?
