### ISSUE TITLE
Remove warning in code about Redis being deprecated

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#1190]
Redis output is no longer deprecated. The docs has been changed to reflect this. However, the code still generates a warning if the user selects redis output. This code needs to be removed, and the changelog needs to be updated to reflect that redis output is no longer deprecated.

See https://github.com/elastic/beats/blob/master/libbeat/outputs/redis/redis.go#L1 and https://github.com/elastic/beats/blob/master/libbeat/outputs/redis/redis.go#L72.

**Comment by urso** [comment]
warning still there on purpose, as plugin as is still needs some update (redis output is 'unsafe' when used with filebeat). Once plugin being updated, warning will be removed.

Related: https://github.com/elastic/beats/issues/943
