### ISSUE TITLE
[AuditBeat] Duplicate audit logs for successful logins in auditbeat

### ISSUE THREAD

**Issue by RiteshKuchukulla** [elastic/beats#11902]
When an auditbeat logs a successful login on ubuntu, it logs a success and a failed event.
Example - I tried logging into my Ubuntu instance and it was successful, so here I get a success log and a failure log. The failure log shouldn't have been there.
logs - (failure log from auditbeat for a successful login to the instance)
{
  "_index": "auditbeat-6.7.1-2019.04.23",
  "_type": "doc",
  "_id": "ox_QSmoBVWWEnTzwiivn",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2019-04-23T15:29:01.419Z",
    "tags": [
      "auditbeat18"
    ],
    "event": {
      "type": "user_login",
      "action": "logged-in",
      "module": "auditd",
      "category": "user-login"
    },
    "process": {
      "pid": "17601",
      "exe": "/usr/sbin/sshd"
    },
    "network": {
      "direction": "incoming"
    },
    "auditd": {
      "session": "unset",
      "data": {
        "terminal": "sshd",
        "acct": "ubuntu",
        "op": "login"
      },
      "summary": {
        "how": "/usr/sbin/sshd",
        "actor": {
          "primary": "unset",
          "secondary": "ubuntu"
        },
        "object": {
          "primary": "sshd",
          "secondary": "xxxxxxxxxxxx",
          "type": "user-session"
        }
      },
      "messages": [
        "type=USER_LOGIN msg=audit(1556033341.419:62645): pid=17601 uid=0 auid=4294967295 ses=4294967295 msg='op=login acct=\"ubuntu\" exe=\"/usr/sbin/sshd\" hostname=? addr=xxxxxxx terminal=sshd res=failed'"
      ],
      "sequence": 62645,
      "result": "fail"
    },
    "beat": {
      "version": "6.7.1",
      "name": "auditbeat18",
      "hostname": "ip-xxxxxxxxx"
    },
    "host": {
      "name": "auditbeat18"
    },
    "user": {
      "uid": "0",
      "name_map": {
        "uid": "root"
      },
      "auid": "unset"
    },
    "source": {
      "ip": "xxxxxxxxxxxxx"
    }
  },
  "fields": {
    "@timestamp": [
      "2019-04-23T15:29:01.419Z"
    ]
  },
  "highlight": {
    "event.action": [
      "@kibana-highlighted-field@logged-in@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1556033341419
  ]
}

This is affecting the success and failure login filtering in Kibana

**Comment by kvch** [comment]
Github Issues are reserved for verified bugs. Please post your question on Discuss: https://discuss.elastic.co/c/beats
