### ISSUE TITLE
filebeat nil point crash when new configuration pushed from kibana central management

### ISSUE THREAD

**Issue by jerryjune** [elastic/beats#11945]
My customer report a filebeat crash bug to me. They have a trial for elastic xpack features. Their filebeats are enrolled and managed in kibana, sometimes when they change the input paths and deploy the new configuration to filebeat, some of the filebeats will crash. From the log, it throws nil pointer error when applying configuration for output, the output is kafka. See following screenshot
Filebeat version 6.7.0
Kafka version 2.12

![ErrorImage](https://user-images.githubusercontent.com/3723112/56809506-9bb82400-6866-11e9-9097-8ff1abcda9e2.png)

**Comment by ph** [comment]
Looking at the code this look like a race inside our kafka client implementation, Connect didn't happen yet and we try to close the producer.

**Comment by ph** [comment]
PR is at #11950
