### ISSUE TITLE
[metricbeat] Enhancement: gather more data for the system/network metricset

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#11951]
Yes, I file a lot of these.

It looks like the network counters we're getting from system/network now are fairly basic. At least on linux and BSD, there's much more detailed data we can get.

One under-used interface is `/proc/net/sockstat` 

```
$ cat /proc/net/sockstat
sockets: used 251
TCP: inuse 2 orphan 0 tw 0 alloc 12 mem 1
UDP: inuse 2 mem 5
UDPLITE: inuse 0
RAW: inuse 0
FRAG: inuse 0 memory 0
```
`orphan` and `mem` data can be very useful for diagnosing network performance and tuning issues, and demonstrated [here](https://blog.tsunanet.net/2011/03/out-of-socket-memory.html), and can be used to calculate memory used by network sockets.  This is fairly valuable information that is often collected by other monitoring stacks.

Aside from this, there's _tons_ of network counters on linux and BSD that we may want to access that can provide useful info. `/proc/net/snmp` for example, can provide us with much more detailed error info, broken down by network protocol:

```
Tcp: RtoAlgorithm RtoMin RtoMax MaxConn ActiveOpens PassiveOpens AttemptFails EstabResets CurrEstab InSegs OutSegs RetransSegs InErrs OutRsts InCsumErrors
Tcp: 1 200 120000 -1 57797 48 41856 36 1 2758120 1810372 1376 0 44840 0
```
`/proc/net/netstat` can also be used to get data on TCP errors, connection aborts and other valuable data. On BSD, we can get similar info via netstat/sysctl on BSD. (I'm having to keep this a bit high level, as there's a _lot_ of network counters out there.)

A lot of this is fairly valuable diagnostic data for servers that handle high network loads, and many other monitoring stacks collect data at a more detailed level than the system/network metricset.

**Comment by fearful-symmetry** [comment]
@ruflin @jsoriano I'm thinking that `/proc/net/sockstat` data should be metricset in its own right, as it's linux-only and fairly distinct from the data that's being gathered in system/network. Thoughts?

**Comment by jsoriano** [comment]
There are at least two things here in this issue:
* `system/network` metricset collects information per network interface (in Linux from `/proc/net/dev`), there is actually more information there, and gopsutil also gets it. It could be easy to add these additional metrics that gopsutil already collects to the metricset.
* `sockstat`, `snmp`, `netstat` and so on are not per interface, they are stats on sockets in the system. We already have the `socket_summary` metricset, before adding a new one we should consider improving the existing one.

**Comment by fearful-symmetry** [comment]
Now that the sockstat PR is merged, I'm gonna close this and open a more specific issue about enhancements from `netstat` and `snmp`
