### ISSUE TITLE
Complete config file with elasticsearch loadbalance option

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#1197]
In the code and docs with have a load balance option for elasticsearch output which is not part of the libbeat.yml file.
- [ ] Add Loadbalance option to `libbeat.yml`
- [ ] Check if other output options are missing in `libbeat.yml`

**Comment by dedemorton** [comment]
@ruflin I think this is fixed, no? Can we close this?

**Comment by ruflin** [comment]
Yes, it seems that was fixed over time.
