### ISSUE TITLE
Metricbeat  kubernetes.container.cpu.limit.cores  data type

### ISSUE THREAD

**Issue by evilezh** [elastic/beats#11975]
kubernetes.container.cpu.limit.cores  field shall be some kind of float rather than long. It is possible to have 0.1 core as it is recorded in elasticsearch. If type is long and we do aggs, then 0.x is interpreted as 0, which is wrong.

**Comment by exekias** [comment]
This sounds about right, we should change their type to support these values

**Comment by evilezh** [comment]
I just went through more fields. There is more .cores fields which are also long. 
Maybe just review all of them. 
I think nanocores was replaced with cores and second, shall be with decimal places. e.g. nano to full core conversion.

**Comment by kaiyan-sheng** [comment]
Right now in kubernetes module, we have `cpu.usage.core.ns` and `cpu.usage.nanocores`. These numbers are relatively large so do we still need to change the field type from `long` to `double` to preserve the decimals?

**Comment by exekias** [comment]
I think those are ok as long, they don't have decimals, or we can ignore them
