### ISSUE TITLE
Improve collection of Docker memory metrics in Windows

### ISSUE THREAD

**Issue by chrisvanderpennen** [elastic/beats#11971]
**Describe the enhancement:**
* Improve [`module/docker/memory/helper.go`](https://github.com/elastic/beats/blob/e5b6c94f924a0592940ea07c84282f3d3c4f91c5/metricbeat/module/docker/memory/helper.go#L56) to report [Windows container memory stats](https://github.com/moby/moby/blob/8a4070a044f989d778e8930b99defc8b35389d34/api/types/stats.go#L73-L81), if present.
* Test if `myRawStat.Stats.MemoryStats.Limit` is non-zero and only then assign to `TotalRssP` and `UsageP`, instead of dividing by zero and assigning NaN.  This should avoid breaking JSON outputs.

**Describe a specific use case for the enhancement or feature:**
Monitoring Windows container memory usage

**Comment by exekias** [comment]
pinging @narph, I think you wanted to this module a pass on Windows

**Comment by chrisvanderpennen** [comment]
Looks like this has been affected by #11676 - Windows memory stats don't include limit, so that change will prevent memory stat collection altogether on Windows.

**Comment by exekias** [comment]
good catch! thank you for sharing. @fearful-symmetry we may need to rethink your fix?

**Comment by fearful-symmetry** [comment]
@exekias  Yah. I tried to find a more elegant way of fixing the `NaN` issues on Linux, but settled on checking the limit, as the moby source stated that it would never be 0 for a running container. The core problem is that it's possible to get a status object back before a container has started, hence a bunch of junk values and the `NaN`. Ideally we would find a better way of detecting the invalid status objects such that we don't interfere with valid windows events.

**Comment by fearful-symmetry** [comment]
Still chewing over how to do this elegantly. After poking around the docker API for a bit, I figure there's two other checks we can get from the `stats` object that _should_ be platform independent:

`OnlineCPUs` : count of online CPUs. Is zero during an invalid event.
`CPUusage.TotalUsage` : Used to calculate deltas for CPU usage percentage. Also zero for an invalid event.

Does any of this sound reasonable @chrisvanderpennen ?

**Comment by chrisvanderpennen** [comment]
`OnlineCPUs` is Linux only, sadly.  0 `CPUusage.TotalUsage` seems a reasonable guard for an invalid stats sample though, I don't see a way for a container in normal operation to have used <1ns of CPU time and my testing on Windows shows it resets to 0 after a running container is stopped.

In case it's useful, [here's a gist](https://gist.github.com/chrisvanderpennen/ecdaee8b0c70cd43c3b5ef77c7b17f11) with json from the stats API on Windows for a started and stopped container.

**Comment by fearful-symmetry** [comment]
@chrisvanderpennen Thanks a ton! I'm gonna put in a PR for this, so we can at least get this part of the issue squared away.

**Comment by fearful-symmetry** [comment]
That PR has been merged, so we should be good to move on to adding the actual windows memory stats.

**Comment by fearful-symmetry** [comment]
That's been merged! I'm gonna close this for now, since it seems like we've squared away the problems in the original issue.
