### ISSUE TITLE
-E does not override configuration

### ISSUE THREAD

**Issue by mkrasuski** [elastic/beats#11972]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 7.0.0
- Operating System: linux
- Discuss Forum URL:
- Steps to Reproduce: 

assuming filebeat.yml like
```yaml
...
output:
  logstash.hosts: [ 'host:port' ]
...
```
if we run

`filebeat -E 'output={console:{pretty:true}}' `

we encounter error about 'more than one output'
This -E should override whole definition of output, not only merge to one in .yml file

**Comment by hholst80** [comment]
Looks like a potential parsing problem? Have you tried filebeat -E output.console.pretty=true?

**Comment by mkrasuski** [comment]
No, parsing is probably ok. But problem is that setting some yaml path on '-E' does not override whole subtree of configuration, but appends defined value to standard tree defined by .yml config.

'output' file is crucial here. Filebeat requires ONLY one output, declines to start elsewhere with:
```
Exiting: error unpacking config data: more than one namespace configured accessing 'output' (source:'filebeat.yml')
```
but when .yml file defines logstash output and we'd like to force other with '-E', there is no way to do it. Any setting with 'output' on command line will be appended to existing logstasch and filebeat won't start due to multiple outputs. My workaround was to exactly set -E output={whole config tree} instead of not working intuitive '-E output.console.pretty=true'. If there is no output in filebrat.yml would work perfectly, but if 'logstash' is there it won't.

**Comment by kaiyan-sheng** [comment]
@mkrasuski Can you try running `./filebeat -E output.console.enabled=true`? 

I tried to run `./filebeat -e -E "output.elasticsearch.hosts=['http://myhost:9200']"` just to see if the `output.elasticsearch.hosts` will get overwritten and turned out it did. It's showing `2019-04-29T16:40:50.316-0600    INFO    elasticsearch/client.go:166     Elasticsearch url: http://myhost:9200` which seems like it's overwriting the config for me.

Also by looking at `filebeat.reference.yml`, if you want to enable pretty-print json event, the parameter to control that is `output.console.codec.json.pretty`.

**Comment by mkrasuski** [comment]
Unfortunately `filebeat -E output.console.enabled=true` has the same error.

To reproduce my problem in clean dir just create filebeat.yml like
```
filebeat.inputs:
- type: log
  paths:
  - '*.log'
output:
  file:
    path: .
    filename: filebeat
```
filebeat starts normally. Now try

```
filebeat -e -E output.console.enabled=true -E output.console.pretty=true
Exiting: error unpacking config data: more than one namespace configured accessing 'output' (source:'filebeat.yml')
```
That's caused by effective `output` config (from .yml and then cmd) being:
```
output:
  file:
    path: .
    filename: filebeat
  console:
    enabled: true
    pretty: true
```
Ok, that was even consistent for me - `-E` appends key to configuration.  But I'd like to override output, so tried to override whole `output` object with:
```
filebeat -e -E 'output={console:{pretty:true}}'
Exiting: error unpacking config data: more than one namespace configured accessing 'output' (source:'filebeat.yml')
```
Fail. Probably there is no chance to override output to different type than this in .yml. That's serious operational problem, especially for testing production processors with sample data. 

But in my opinion `-E path=value` should *REPLACE* config object addressed by `path` with `value`, and not only append to it...

**Comment by mkrasuski** [comment]
> Looks like a potential parsing problem? Have you tried filebeat -E output.console.pretty=true?
No, tried some:
`-E output={}` 
`-E output={foo:1}`
`-E output={foo:{bar:true}}`
all are OK but they don't change anything...
But if we change property `foo` to meaningful `console` - multi-output error arises

**Comment by mkrasuski** [comment]
> @mkrasuski Can you try running `./filebeat -E output.console.enabled=true`?

BTW, there is a way to redirect output. We've to set all other outputs with `enabled=false`, so in my case it was:
```
filebeat -e \
    -E filebeat.inputs=[{type:stdin}] \
    -E output.logstash.enabled=false \
    -E output.console.pretty=true
```
works fine - redirects both input and output to stdin/stdout - no multi-output error. Useful for processors testing, imho.
