### ISSUE TITLE
Set ILM in central beats management

### ISSUE THREAD

**Issue by vaivars** [elastic/beats#11989]
**Describe the enhancement:**
Enable setting "other" settings in CBM - specifically configure ILM

**Describe a specific use case for the enhancement or feature:**
Using ILM in conjunction with CBM

**Comment by ph** [comment]
Beats central development is stopped, all our effort is moved to the Fleet/Agent and the Elastic Package manager. Setting UP the ILM will be handled by the Elastic Package Manager.
