### ISSUE TITLE
[Heartbeat] Permit IP address override

### ISSUE THREAD

**Issue by peterpramb** [elastic/beats#12010]
**Describe the enhancement:**

In load balanced setups where services behind the load balancer share the same properties (e.g. certificate name) it would be helpful to specify the destination IP address together with the DNS name to direct the request to the proper service endpoint.

**Describe a specific use case for the enhancement or feature:**

Consider the following scenario: `www.sample.net` points to the load balancer, which balances traffic to a number of web servers behind it, all providing the same certificate for `www.sample.net`.

Currently one can either specify `www.sample.net` in the HTTP monitor, thus monitoring the load balancer itself, or the IP address of the web servers behind it, but that causes issues with the SSL handshake. While there was elastic/beats#9376 adding support for custom Host headers, this won't help with SNI, where still the IP address is sent.

It would be great when the destination IP address could be specified together with the DNS name, or some other way to prepopulate the DNS cache.

**Comment by narthollis** [comment]
I am also interested in the ability to do this.

I would also be interested to have Heartbeat check all of the entries for an address in a rr-dns setup (should I file a separate issue?)

Eg. foo.example.com -> a.a.a.a, b.b.b.b, c.c.c.c it would be good if Heartbeat could check all 3 addresses when it it configured to check `foo.example.com`
