### ISSUE TITLE
Create index pattern in Kibana does not work anymore

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#12026]
* Version: Metricbeat master and ES / KB master

## Steps to reproduce

* Setup the master version of the Elastic Stack
* Run `./metricbeat -E setup.dashboards.directory=_meta/kibana.generated/ setup -e`
* Go to Kibana and check the index pattern for `metricbeat-*``

The index pattern only contains 5 default fields but is missing all the other required fields. Looking at the logs and also investigated in the code, it seems like Kibana would accept the index pattern as no error is returned and a 200. But the index pattern is not loaded.

Not sure if there was a change on the Beats side related to this or in Kibana master (my current assumption), but tested with Stack 7.0 and things work as expected.

**Comment by kvch** [comment]
@ruflin I am not able to reproduce the issue on master. Could you please provide more info?

**Comment by ruflin** [comment]
@kvch Tried to reproduce this again with the most recent version of Kibana master on my end and couldn't anymore. My guess is that it was a bug somewhere in KB that got fixed. Closing.
