### ISSUE TITLE
Journalbeat 6.71 failed to iterate journal: 74 dead lock

### ISSUE THREAD

**Issue by dennisme** [elastic/beats#12023]
- Version: journalbeat 6.7.1
- Operating System: CoreOS 1911.3

Logs 

```bash
go:167        Error while reading event: failed to iterate journal: 74        {"id": "a552eb90-7725-43fe-a26f-e5baef7d8880"}
May 01 21:28:00 example-host docker[26483]: 2019-05-01T21:28:00.873Z        ERROR        [input]        input/input.go:167        Error while reading event: failed to iterate journal: 74        {"id": "a552eb90-7725-43fe-a26f-e5baef7d8880"}
May 01 21:28:00 example-host docker[26483]: 2019-05-01T21:28:00.873Z        ERROR        [input]        input/input.go:167        Error while reading event: failed to iterate journal: 74        {"id": "a552eb90-7725-43fe-a26f-e5baef7d8880"}
```

Workaround: restart the process

**Comment by kvch** [comment]
This is an issue with systemd, not Journalbeat. What is your systemd version?

**Comment by dennisme** [comment]
@kvch ah good to know. 

https://coreos.com/releases/#1911.3.0 systemd  238

**Comment by dennisme** [comment]
On some newer systems coreos 2079.3.0, systemd 241 I don't see the issue.

**Comment by dennisme** [comment]
@kvch can we link the systemd issue? Once that is done how do you feel about closing it out?

**Comment by ymatsiuk** [comment]
I see the same issue on `CoreOS 2247.3.0` with `systemd 241 (241-30-gf0da8f7+)`

**Comment by mickymiek** [comment]
Hitting the same here with:
`systemd 241 (241-30-gf0da8f7+)`
`coreos 2303.0.0`
`journalbeat 7.4.0`
@ymatsiuk can you confirm if the journal rotation is the source of this issue?
