### ISSUE TITLE
Windows Server 2019 OS support

### ISSUE THREAD

**Issue by HansOMartinsen** [elastic/beats#12064]
After looking at the OS support matrix: https://www.elastic.co/support/matrix I detected that Windows Server 2019 is not supported. 

We need that the agent is supported to implement it in our customers systems.

I raise this issue here after asking a question in the forum and getting directed here by Mark Walkom from Elastic. (https://discuss.elastic.co/t/os-support-matrix/179701/3)

Kind Regards
Hans O. Martinsen

**Comment by jsoriano** [comment]
Hi @HansOMartinsen,

Thanks for the request. The support matrix is for official support, but the Beats could work in other operating systems not listed there.
Did you have a chance to try winlogbeat in Windows Sever 2019?

**Comment by acchen97** [comment]
@HansOMartinsen thanks for filing this request. We don't have a delivery ETA for this yet, but its something we're looking into.

**Comment by mikemadden42** [comment]
With version 7.4.x of beats, Windows Server 2019 is supported.

https://www.elastic.co/support/matrix
