### ISSUE TITLE
Input validation & protocol handling libbeat/outputs/transport/tcp.go - Central Beats Management

### ISSUE THREAD

**Issue by andynz2017** [elastic/beats#12061]
Cluster Version: 6.7.1

Issue:
-	When defining logstash output hosts: with protocol://hostname:port within the central beats management part of the Kibana UI, we get DNS resolution issues. The DNS resolver attempts to lookup "protocol://hostname:port" rather than "hostname" only.
-	This occurs if http or https is specified in front of the host:port. Does not occur if host:port is presented.

Initial stab at root cause analysis/triage:
-	Library affected: libbeat/outputs/transport/tcp.go
-	Function: func TestNetDialer
-	Detail:
        - net.SplitHostPort appears to take a string (address parameter) in the format hostname:port.
        - The format of the string passed to the input does not appear to be checked before the SplitHostPort function is called. Input validation based on GoLangs recommendations for the function does not appear to be present in this library.
-	Result:
        - It does not appear to be currently possible to specify https://hostname:port within the user interface under hosts to enable https communication. The management.yml file does update and shows hosts: - "https://hostname:port" but the parsing and transport logic cannot detect the port or hostname correctly and no traffic is sent to logstash.

I have tried specifying ssl.enabled: true in the logstash output within central beats management to see if a hosts definition of hostname:port without protocol being specified would default to https. The behavior in this scenario is that DNS resolution of the host succeeds, traffic originates on the network on the user defined port specified, but the logs aren't ingested with lumberjack protocol errors (not talking https is my take on it).

Can we please confirm if the above is an accurate account of the issue? Best effort from my side, understanding could be wrong.

Thanks
Andrew

**Comment by jsoriano** [comment]
Hi @andynz2017,

The host should be in the `host:port` format, and if SSL is required then [`ssl` options](https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html#_literal_ssl_literal_2) have to be used. This is not expected to work with the `protocol://host:port` form.

What is the input configuration you are using in logstash? You can find an example of the beats input here: https://www.elastic.co/guide/en/beats/filebeat/7.0/logstash-output.html

**Comment by urso** [comment]
I'm closing this issue, because it was not updated for a long time. For general questions like this please use the community forums at http://discuss.elastic.co. Your question will reach a wider audience on the forums, as developers and users do participate in them.
