### ISSUE TITLE
How do I send logs from glassfish 4.1 to logstash to analyze them with kibana? Any example that works?

### ISSUE THREAD

**Issue by martinmurciego** [elastic/beats#12083]
I have installed ELK Stack but I can not find examples of capturing glassfish logs and less version 4.1. Could you explain me in detail?

I have installed ELK, configured the three tools and from a VPS. Then install filebeat on the vps that has installed Glassfish 4.1 indicating its path. But when launching the filebeat service after configuring it to send the logs to the other vps, 
I get this error that is not understood: 
> insserv: Starting glassfish depends on grafana-server and therefore on system facility `$all' which can not be true!

[https://askubuntu.com/posts/1139160/revisions](url)

It is not understood because grafana server is installed on another server.

**Comment by jsoriano** [comment]
Hi @martinmurciego,

We use to keep github issues for confirmed bugs and enhancement requests, please use https://discuss.elastic.co for questions about how to use the Elastic Stack.

**Comment by exekias** [comment]
Hi @martinmurciego, we try to keep this repo for confirmed issues and feature requests, could you please ask in our forums? https://discuss.elastic.co/c/beats/filebeat

Best regards
