### ISSUE TITLE
"Socket" doesn't show the kind of port (UDP or TCP)

### ISSUE THREAD

**Issue by q2dg** [elastic/beats#12090]
There's a "ip" and "port" field inside "local" and "server" but there's no a "type" field or similar
Thanks!

**Comment by fearful-symmetry** [comment]
Are you referring to `socket`? `socket_summary` divides all the statistics into tcp and udp.

**Comment by q2dg** [comment]
Yes, I'm refering to "socket", sorry!!
I've edited the title
(And thanks!)
