### ISSUE TITLE
Add a Kubernetes manifest for Heartbeat

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/beats#12093]
If there is a sample manifest for deploying Heartbeat in Kubernetes please add it to the docs.  I do not see it here:
https://www.elastic.co/guide/en/beats/heartbeat/current/heartbeat-installation.html

But I do see autodiscover information, so it must have been run in Kubernetes.

I have not been able to get it to work.

**Comment by andrewvc** [comment]
Hey @DanRoscigno we've discussed this and don't see it as something we would work on in the near to medium term due to a lack of demand. We may re-evaluate in the future. Would you mind if we closed it for now?

**Comment by DanRoscigno** [comment]
Here is [one](https://github.com/elastic/examples/blob/6d6ece21e8dec906254bf37b104ad457e65906c2/k8s-observability-with-eck/heartbeat-kubernetes.yaml) I wrote @andrewvc .  I do think that our messaging around "deploy Heartbeat in various data centers or cloud locations" fits directly with "use k8s".  I also have [Docker instructions for Heartbeat](https://github.com/DanRoscigno/docker_observability/tree/master/Heartbeat).

**Comment by DanRoscigno** [comment]
If it is OK, I will write the PR.

**Comment by andrewvc** [comment]
@DanRoscigno it's always OK to write a PR! Much appreciated, and thanks.

**Comment by DanRoscigno** [comment]
WIP:
Create secret:
```
echo your:reallylongcloudid > ELASTIC_CLOUD_ID

echo beat-setup:secret > ELASTIC_CLOUD_SETUP_AUTH
echo beat-writer:anothersecret > ELASTIC_CLOUD_AUTH

kubectl create secret generic dynamic-logging \
   --from-file=./ELASTIC_CLOUD_ID \
   --from-file=./ELASTIC_CLOUD_AUTH \
   --from-file=./ELASTIC_CLOUD_SETUP_AUTH \
   --namespace=kube-system
```

Here is the manifest that uses the above secret:

[heartbeat-k8s.yaml.txt](https://github.com/elastic/beats/files/4069259/heartbeat-k8s.yaml.txt)

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
