### ISSUE TITLE
[Heartbeat] host.name should not be set in heartbeat

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#12107]
libbeat still [sets](https://github.com/elastic/beats/blob/master/libbeat/publisher/processing/default.go#L80) `host.name` on all events even with the `add_host_metadata` processor removed. We should remove it, as heartbeat is an `observer` not a `host` in ECS parlance. There is [prior art](https://github.com/elastic/apm-server/blob/master/cmd/root.go#L83) here in APM.

**Comment by shahzad31** [comment]
**Testing for release 7.6.0**
Ran heatbeat 7.5 and i can see host.name field

![image](https://user-images.githubusercontent.com/3505601/72738351-ac04f180-3ba1-11ea-8e12-814488d256b3.png)

Ran heartbeat 7.6.0 and it doesn't contains host.name field.
Ran heartbeat 8.0.0 and it doesn't contains host.name field.
