### ISSUE TITLE
reloader never continue loop when updated is false

### ISSUE THREAD

**Issue by DanielQujun** [elastic/beats#12155]
https://github.com/elastic/beats/blob/master/libbeat/cfgfile/reload.go#L209
```
			if !updated && !overwriteUpdate {
				overwriteUpdate = false
				continue
			}

			// Load all config objects
			configs, _ := rl.loadConfigs(files)

			debugf("Number of module configs found: %v", len(configs))

			if err := list.Reload(configs); err != nil {
				// Make sure the next run also updates because some runners were not properly loaded
				overwriteUpdate = true
			}
```
when reloader check config files that is not updated, it should not execute [list.Reload](https://github.com/elastic/beats/blob/master/libbeat/cfgfile/reload.go#L219) , however overwriteUpdate is defined true at the beginning of the for loop , so the if condition will never be true.

maybe we should set overwriteUpdate false when list.Reload execute success.

**Comment by exekias** [comment]
This was already fixed by https://github.com/elastic/beats/pull/16440
