### ISSUE TITLE
Fields are missing from index mapping

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#12161]
For confirmed bugs, please report:
- Version: master (7.1 not affected)
- Operating System: -
- Discuss Forum URL:
- Steps to Reproduce: 

When I feed data to a clean ES, the index mapping (/filebeat-8.0.0/_mapping) has about ~160* fields and the fields of `geo_point` type are missing (`source.geo.location` missing, `source.geo.location.lat` is present).

The index template does contain all ~980* fields (/_template/filebeat-8.0.0).

If I delete the filebeat-8.0.0 index and feed the same data again, the new index does have all the fields in its mapping.

(* Field count is for `x-pack/filebeat`. OSS version will be lower.)

Here's a script that can be used with git bisect: [script.tar.gz](https://github.com/elastic/beats/files/3165504/script.tar.gz)

Unpack the files directly into the Beats repo and run `./check.sh setup` for the first time before running `git bisect`.

**Comment by simitt** [comment]
Will be fixed with https://github.com/elastic/beats/pull/12149

**Comment by simitt** [comment]
@adriansr can you confirm this is fixed in `master`? If so, please close the issue.

**Comment by adriansr** [comment]
@simitt fixed 💯
