### ISSUE TITLE
[MetricBeat] Why are multiple events created for `network ` in system module

### ISSUE THREAD

**Issue by whiletruelearn** [elastic/beats#12179]
- Version:  7.0.1
- Operating System:  Linux
- Discuss Forum URL: https://discuss.elastic.co/t/why-are-multiple-events-created-for-network-in-system-module/180810
- Steps to Reproduce:  
Despite giving period as 1m , i was able to see about 8 events created for the same timestamp
for the metricset containing network

**Comment by ph** [comment]
Closing this we keep the issue tracker for bugs, lets finish the conversation on discuss before moving to the issue tracker.
