### ISSUE TITLE
[Metricbeat] Cronjob support

### ISSUE THREAD

**Issue by mdibaiee** [elastic/beats#12183]
**Describe the enhancement:**

As [discussed](https://discuss.elastic.co/t/kubernetes-metrics-cronjobs/180377) on the board, it seems like Metricbeat doesn't support Kubernetes Cronjob metrics, i.e. when cronjobs create pods, those pods' metrics are not monitored and so there is no data about those pods sent over to ES. We use Cronjobs in our clusters often and we could really use the metrics for those pods.

**Describe a specific use case for the enhancement or feature:**

Monitoring CPU and Memory usage of Cronjobs to optimize their hardware/software.

**Comment by exekias** [comment]
Thanks for opening, I'm linking this to the meta issue: https://github.com/elastic/beats/issues/7058
cc @odacremolbap
