### ISSUE TITLE
[Heartbeat] Dynamic properties

### ISSUE THREAD

**Issue by marbin** [elastic/beats#12184]
**Describe the enhancement:**
A way to inject code/script to provide dynamic properties in the heartbeat request, typically in a SOAP or JSON request body. See example use case below.

The WebService testing tool SoapUI provides "dynamic properties" and lets you inject java code
See (Dynamic Properties)
https://www.soapui.org/scripting-properties/property-expansion.html

The Heartbeat equivalent would be the possibility to inject Go code, I guess.

**Describe a specific use case for the enhancement or feature:**
I have a use case where I want to use Heartbeat to call a SOAP-based web-service to check for uptime.
The SOAP interface forces me to provide
1. A unique request ID for each call, e.g. a UUID
2. A timestamp in ISO 8601 format, e.g. "2019-05-13T10:32:48.000+02:00"

I would like to produce a SOAP request body like this one:
```
check.request.body: '
    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"        
    <soapenv:Header/>
    <soapenv:Body>
        <someRequest>
            <requestID>b804e8b2-a5f3-418b-bc07-d47af32c49f6</requestID
             <requestTimestamp>2019-05-13T10:32:48.000+02:00</requestTimestamp>
...
```
In SOAP UI, I can do something like this

```
<com:requestID>${=java.util.UUID.randomUUID()}</com:requestID>
 <requestTimestamp>${=new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ").format(new Date())}</requestTimestamp>
```

**Comment by andrewvc** [comment]
Thanks for this enhancement request! What would you like that heartbeat interface to look like?

One thing we've considered is allowing users to script requests with Javascript. Would that solve your use case?

**Comment by marbin** [comment]
I my case, any method to generate dynamic content in the request body would fulfill my needs.
The language or syntax does not matter. Javascript is probably more flexible/familiar than Go for most users.

**Comment by gchiartosini** [comment]
Why was this request closed?
The use case should be highly researched.
I have the same requirement even if it is a json rest call.

Is there currently no workaround?
