### ISSUE TITLE
[Heartbeat] Ability to add randomized cache busting string to HTTP check

### ISSUE THREAD

**Issue by rbayliss** [elastic/beats#12194]
**Describe the enhancement:**
I'd like to have the ability to add random strings or numbers to the URL for an HTTP check.  It would be great if this worked as a string replacement, so I could do something like this:

```
- type: http
  schedule: '@every 5s'
  urls: ["http://myhost?cachebuster=${RANDOM_STRING}"]
 ```

**Describe a specific use case for the enhancement or feature:**
The use case here is that sometimes I want to check an HTTP endpoint where the origin is behind one or more layers of reverse proxy caching (CDNs, etc).  To check the response of the _origin_, I need a reliable way to bust through the cache.   The easiest way I can think of to do that is to add a cache busting query parameter to the URL.

**Comment by exekias** [comment]
as a system specific workaround, I think `${RANDOM}` should probably work on Linux?

**Comment by rbayliss** [comment]
Hmm, `${RANDOM}` doesn't work for me (Linux).  I get `Error creating runner from config: missing field accessing 'urls'` when I add `?cachebuster=${RANDOM}` to the end of my URL.

**Comment by andrewvc** [comment]
This is a great idea, but it's probably not going to be our highest priority. We'd gladly accept a patch accomplishing this however.

**Comment by bczifra** [comment]
Related: https://github.com/elastic/beats/issues/38550
