### ISSUE TITLE
heartbeat is crashing due to High Availability Cluster Communication 

### ISSUE THREAD

**Issue by iamyogesh** [elastic/beats#12197]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: heartbeat 5.4.3, elasticsearch 4 node cluster with version 6.3.2
- Operating System: heartbeat installed on ubuntu 18.04, elasticsearch cluster centos 7
- Discuss Forum URL:

hearbeat in runing in ubuntu machine to check the ip status using follwing configuration
# Configure monitors
heartbeat.monitors:
- type: icmp
  # Configure task schedule
  schedule: '*/10 * * * *'
  hosts: ["192.168.11.76"]

pushing data to elastic search , it crashes after 2 days on continues run of heartbeat service
- Steps to Reproduce: 
systemctl status heartbeat

● heartbeat.service - Heartbeat High Availability Cluster Communication and Membership
   Loaded: loaded (/lib/systemd/system/heartbeat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-05-16 10:15:10 IST; 1h 53min ago
  Process: 929 ExecStart=/usr/lib/heartbeat/heartbeat -f (code=exited, status=6)
 Main PID: 929 (code=exited, status=6)

May 16 10:15:10 adumaster systemd[1]: Started Heartbeat High Availability Cluster Communication and Memb
May 16 10:15:10 adumaster heartbeat[929]: May 16 10:15:10 adumaster heartbeat: [929]: ERROR: Cannot open
May 16 10:15:10 adumaster heartbeat[929]: May 16 10:15:10 adumaster heartbeat: [929]: info: An annotated
May 16 10:15:10 adumaster heartbeat[929]: May 16 10:15:10 adumaster heartbeat: [929]: info: Please copy 
May 16 10:15:10 adumaster heartbeat[929]: May 16 10:15:10 adumaster heartbeat: [929]: ERROR: Heartbeat n
May 16 10:15:10 adumaster heartbeat[929]: May 16 10:15:10 adumaster heartbeat: [929]: ERROR: Configurati
May 16 10:15:10 adumaster systemd[1]: heartbeat.service: Main process exited, code=exited, status=6/NOTC
May 16 10:15:10 adumaster systemd[1]: heartbeat.service: Failed with result 'exit-code'.

check the error log message
/var/log/heartbeat/heartbeat

019-05-17T14:21:22+05:30 INFO No non-zero metrics in the last 30s
2019-05-17T14:21:30+05:30 ERR Failed to perform any bulk index operations: Post http://ip:port/_bulk: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2019-05-17T14:21:30+05:30 INFO Error publishing events (retrying): Post http://ip:port/_bulk: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2019-05-17T14:21:31+05:30 ERR Connecting error publishing events (retrying): Get http://ip:port: EOF

**Comment by andrewvc** [comment]
Apologies for the long delay. Is this still an issue? If so, do you have any metrics for the heartbeat process? If so, do you see any excessive memory or other resource usage.

Unfortunately there are no smoking guns in the error logs here.

**Comment by iamyogesh** [comment]
@andrewvc  this issue is fixed i have upgraded heartbeat from 5.4 to 6.5.4 as 5.4 was beat version in the 6.5.4 version this issue is not there heartbeat is continuously runing without any issue
