### ISSUE TITLE
Auditbeat [6.7.2] - Exiting: 1 error: 1 error: this metricset does not support OS family

### ISSUE THREAD

**Issue by AbdellatifHousni** [elastic/beats#12198]
Hello,
I wanted to upgrade auditbeat to 6.7.2 on XCP-ng (fork of XenServer based on Centos) I receive the following message : 
> Exiting: 1 error: 1 error: this metricset does not support OS family

Is there a way to fix this myself ?

Thank you

**Comment by ph** [comment]
I am not familiar in XCP-ng, but I believe we should support all of them, can you share your configuration?

**Comment by cwurm** [comment]
@AbdellatifHousni This should be fixed in versions 6.8.1 and 7.2.0. Please let us know if this problem persists.

**Comment by AbdellatifHousni** [comment]
Thank you tried it and it is ok now.

Le jeu. 27 juin 2019 à 14:51, Christoph Wurm <notifications@github.com> a
écrit :
