### ISSUE TITLE
Missing dependencies for `make update`

### ISSUE THREAD

**Issue by 7AC** [elastic/beats#12195]
Looks like running `make update` now requires to

```bash
go get github.com/jstemmer/go-junit-report github.com/magefile/mage
```

but the `libbeat/scripts/Makefile` doesn't take care of it.

**Comment by ruflin** [comment]
Looks like it's in the vendor directory, so it should just work? https://github.com/elastic/beats/tree/master/vendor/github.com/jstemmer/go-junit-report

**Comment by 7AC** [comment]
Thanks @ruflin. Looks like it was broken briefly, I was at https://github.com/elastic/beats/commit/b70fdcd5108ca1ec1c1c51f206e324b4a9ad29d6 and it was fixed at https://github.com/elastic/beats/commit/5f05ac7bf20cda8c8da3a68d213e471fa0a51476#diff-9c857e4f4f4771aae95a355d9d30f3c2
