### ISSUE TITLE
As a developer, I'd like to generate the filebeat binary for tests in a separate command

### ISSUE THREAD

**Issue by mdelapenya** [elastic/beats#12207]
**Describe the enhancement:**
Instead of executing the unit tests (fastest) to generate the filebeat binary to run the checks for field validation, I'd like to have a build command to do it separately

**Describe a specific use case for the enhancement or feature:**
Once working on a filebeat for first time, I have to execute the unit tests to generate the binary to run the checks for field validation, because it's the way to generate the `filebeat.test` binary. For x-pack structure it's fast, but not that fast on the OSS structure.

**Comment by jsoriano** [comment]
The go native way to build test binaries is `go test -c`. I find this enough, but it could be also good to have an specific mage/make target to do it.
