### ISSUE TITLE
Field validation is not handling properly typos in fields.yml

### ISSUE THREAD

**Issue by mdelapenya** [elastic/beats#12206]
It seems that the field validation is not considering typos in the fields. I found a typo here: https://github.com/elastic/beats/blob/master/filebeat/module/osquery/result/_meta/fields.yml#L24-L27

```diff
-      tupe: keyword
+      type: keyword
```

- Version: master branch
- Operating System: MacOS
- Discuss Forum URL: none
- Steps to Reproduce: 

1. Prepare test environment (`make start`, and generate the binary for tests)
2. Execute `make update`
3. Execute test

```shell
TESTING_FILEBEAT_MODULES=osquery INTEGRATION_TESTS=1 GENERATE=1 BEAT_STRICT_PERMS=false nosetests -v -d -s tests/system/test_xpack_modules.py -v
```

**Expected results:** the typo must be caught, as `tupe` is not syntactically correct
**Actual results:** the typo is not caught and the process passes

**Comment by ruflin** [comment]
There is currently no validation of the used keys in our test system. We should probably start with defining which are the allowed keys.

I opened a fix here: https://github.com/elastic/beats/pull/12232 I'm wondering how you found this one, good catch.
