### ISSUE TITLE
Feature request: AWS SignatureV4

### ISSUE THREAD

**Issue by vtmas** [elastic/beats#12234]
Please add SignatureV4 authentication support for beats.

In this case beats would be able to send data to ES hosted in AWS via access key/secret authentication.

**Comment by ph** [comment]
I am sorry, at the moment we don't plan to support non standard elasticsearch output, there are a few more discussion in a [previous opened PRs](https://github.com/elastic/beats/pull/5466#issuecomment-340450460.

**Comment by vtmas** [comment]
Thank you.
