### ISSUE TITLE
Write system tests for stack modules' xpack code paths

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#12256]
We have integration and system tests for the stack modules in Metricbeat, but these don't exercise the xpack code path (i.e. when `xpack.enabled` is set to `true` in the module config). We need to write these as another safety net for catching bugs like https://github.com/elastic/kibana/issues/36943 early.

**Comment by ycombinator** [comment]
* PRs to resolve this issue:
  * [ ] Elasticsearch module system test: https://github.com/elastic/beats/pull/12482
  * [ ] Kibana module system test:
  * [ ] Logstash module system test:
  * [ ] Beats module system test:

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
