### ISSUE TITLE
[Metricbeat] Add ability to collect tags for aws services

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#12263]
Quote from AWS documentation: 
A tag is a label that you assign to an AWS resource. Each tag consists of a key and an optional value, both of which you define. Tags enable you to categorize your AWS resources in different ways, for example, by purpose, owner, or environment. This is useful when you have many resources of the same type—you can quickly identify a specific resource based on the tags you've assigned to it. For example, you could define a set of tags for your account's Amazon EC2 instances that helps you track each instance's owner and stack level.

Adding the ability to collect tags for AWS ec2 metricset, will give users the flexibility to query/filter on tags for better monitoring each instance. Tags can be a part of the metadata in ec2 metricset under field `aws.ec2.instance.tags.*` and this will be only available for `ec2` metricset. If users use `cloudwatch` metricset to collect EC2 monitoring metrics, then there will be no tags included.

**Comment by exekias** [comment]
+1 to having this. Just a note, as tags are also present in other AWS resources, it could make sense to use `aws.tags` as the field name

**Comment by kaiyan-sheng** [comment]
Yes, good point! We can start with adding tags for EC2 and then expand to other resources. Thanks!

**Comment by powderr** [comment]
+1 PMI is requesting as well
