### ISSUE TITLE
[Metricbeat] Replace mgo library with mongo-go-driver in mongodb module

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#12273]
The library we are using right now in mongodb metricbeat module is https://github.com/go-mgo/mgo/tree/v2 which says it is unmaintained. This driver is also missing support to use `readPreference` as a connection URL option in hosts. If user specifies `hosts: ["mongodb://specter-mongodb-node-2?replicaSet=rs0&readPreference=primary"]`, metricbeat will report error:
```
2019-05-16T05:58:35.678Z	ERROR	instance/beat.go:906	Exiting: 1 error: 5 errors: host parsing failed for mongodb-dbstats: unsupported connection URL option: readPreference=primary; host parsing failed for mongodb-status: unsupported connection URL option: readPreference=primary; host parsing failed for mongodb-collstats: unsupported connection URL option: readPreference=primary; host parsing failed for mongodb-metrics: unsupported connection URL option: readPreference=primary; host parsing failed for mongodb-replstatus: unsupported connection URL option: readPreference=primary
```
This is caused by the limitation in mongodb go library https://github.com/go-mgo/mgo/blob/v2-unstable/session.go#L271.

I originally created an issue to document the limitation on URL option https://github.com/elastic/beats/issues/12220 but after more discussion, we think it will be good to replace the current mgo driver with a better and maintained one, for example https://github.com/mongodb/mongo-go-driver.

**Comment by fearful-symmetry** [comment]
Considering the library is unmaintained, I almost wonder if this is more a bug than an enhancement? Either way, probably a good idea to replace it.

My only concern would be mongodb version compatibility, and I can't find any mgo docs about what mongo versions it supports, but the official go driver supports 2.6 and up, which is fairly old.

**Comment by kaiyan-sheng** [comment]
Yeah good point, I checked the mongodb module documentation and it says `The MongoDB metricsets were tested with MongoDB 3.4 and 3.0 and are expected to work with all versions >= 2.8.`. When working on this issue, we need to make sure the compatibility and/or update the documentation accordingly.

**Comment by kaiyan-sheng** [comment]
Just realized I still have this ticket, I just removed myself and added the correct team label. Please feel free to pick it up(based on priority of course).
