### ISSUE TITLE
Kibana dashboard load retries seems to not happen

### ISSUE THREAD

**Issue by sayden** [elastic/beats#12283]
Thanks for discovering this @dadoonet ! I confirm the behavior.

Steps to reproduce: Without Kibana running, run Metricbeat with a config which includes 

```yaml
setup.dashboards.enabled: true
setup.dashboards.retry.enabled: true
```

Which, afaik, should retry the process of importing dashboards to Kibana once every second.

I have seen that this [line](https://github.com/elastic/beats/blob/master/libbeat/cmd/instance/beat.go#L753) tries to connects to Kibana before the retry loop happens deep inside this [line](https://github.com/elastic/beats/blob/master/libbeat/cmd/instance/beat.go#L771)

#### Expected behavior
The expected behavior is that Metricbeat stays running trying to connect to Kibana. Starting a Kibana instance while Metricbeat is running should allow Metricbeat break the retry loop and load the dashboards.

#### Current behavior
The code tries to connect to Kibana first so it crashes before entering the retry loop.

**Comment by segevfiner** [comment]
I'm seeing this in filebeat v7.8.1, even though I enabled dashboard loading retries, it still fails on startup when Kibana is not running or haven't finished starting yet.

**Comment by activeshadow** [comment]
Same here, but for PacketBeat v7.9.3.
