### ISSUE TITLE
Validate metricsets with xpack.enabled is set to true

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#12327]
Stack modules in Metricbeat can take an `xpack.enabled: true` flag in their configuration. If this flag is set, a precise set of metricsets must also be enabled for the module. We should bake this validation into module initialization, if possible.

**Comment by cachedout** [comment]
I ran into this issue the other day. Raising a warning message would have been very helpful so this is a big +1 from me.

**Comment by ycombinator** [comment]
Related: https://github.com/elastic/beats/pull/12264.

**Comment by lcawl** [comment]
I think there might need to be some variation depending on your license level.  When I test with a gold license, for example, I receive the following:

> 2019-05-27T16:50:18.606-0700	INFO	module/wrapper.go:244	Error fetching data for metricset elasticsearch.ccr: the CCR feature is available with a platinum Elasticsearch license. You currently have a gold license. Either upgrade your license or remove the ccr metricset from your Elasticsearch module configuration.

**Comment by ycombinator** [comment]
Yes, good point re: CCR. I've been considering removing this "error" altogether and essentially making the CCR metricset just be smarter. That is, if the metricset can't get CCR metrics from ES because ES isn't running a high enough license, maybe we should just ignore that situation and continue on? Or at best we could log something at the debug level. 

Thoughts?

**Comment by cachedout** [comment]
If we were to refine this, IMHO, `warn` would be the appropriate log level for such an event. It indicates a configuration which is not going to behave as the user expects and they should be alerted of its existence so that they can either acknowledge the anomaly or correct their configuration.

**Comment by ycombinator** [comment]
I like that idea, @cachedout. Will implement!
