### ISSUE TITLE
Make elasticsearch/audit fileset work against inconsistent timestamp fieldnames

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#12339]
I ran Elasticsearch 7.1.0 in a Docker container with audit logging turned on. Consider the following sample log entry I generated:

```
{"type": "server", "timestamp": "2019-05-28T19:17:36,708+0000", "level": "INFO", "component": "o.e.x.s.a.l.LoggingAuditTrail", "cluster.name": "docker-cluster", "node.name": "68394c3e3bbe", "cluster.uuid": "BI0VZnPyRJuQWQzhuwO8sg", "node.id": "mQjSOd7bREOwl_I4IUaEtw",  "message": "event.action=\"anonymous_access_denied\" event.type=\"rest\" node.id=\"mQjSOd7bREOwl_I4IUaEtw\" origin.address=\"172.17.0.1:36744\" origin.type=\"rest\" request.id=\"2nj_ww26T0eODoilHXDPSA\" request.method=\"GET\" url.path=\"/\""  }
```

Notice that the name of the timestamp field is `timestamp`.

Now, I ran Elasticsearch 7.1.0 again, but by downloading and extracting it from a `.tar.gz` file instead of in a Docker container. Here's a sample audit log entry I generated:

```
{"@timestamp":"2019-05-28T12:33:31,246", "node.id":"qUZG15diSquz8jpvQbTmhA", "event.type":"rest", "event.action":"anonymous_access_denied", "origin.type":"rest", "origin.address":"[::1]:49499", "url.path":"/", "request.method":"GET", "request.id":"b5A_F-ihQaOHrxBgAa3gjA"}
```

Notice that the name of the timestamp field is `@timestamp`.

This field name discrepancy is causing [some issues for users](https://discuss.elastic.co/t/filebeat-7-1-0-elasticsearch-module-audit-pipeline-incorrectly-references-timestamp-instead-of-timestamp/182721) trying to use Filebeat to parse the audit log, depending on whether the environment is a Docker container vs. not.

Other types of Elasticsearch logs (server, deprecation) consistently use `timestamp` (no `@` prefix) in either Docker or non-Docker logs.

In the longer term it would be nice if Elasticsearch consistently just used `timestamp` (no `@` prefix) for audit logs in both Docker and non-Docker logs. I've created https://github.com/elastic/elasticsearch/issues/42666 to track this.

However, for the short term we should make Filebeat look for either `@timestamp` or `timestamp` when its trying to parse Elasticsearch deprecation logs.

**Comment by pgomulka** [comment]
btw how was the parsing done before 7.0?
I can see that on 6.5 ES docker audit logs would end up like this:
```
[2019-05-29T11:32:34,110][INFO ][o.e.x.s.a.l.LoggingAuditTrail] [fC6BeBH] action="cluster:admin/xpack/security/realm/cache/clear" event.action="access_granted" event.type="transport" node.id="fC6BeBHURYGBhkBDLCXqGw" node.name="fC6BeBH" origin.address="172.17.0.2:9300" origin.type="local_node" request.name="ClearRealmCacheRequest" user.name="_xpack_security" user.realm="__attach" user.roles="["superuser"]"
```

**Comment by ycombinator** [comment]
@pgomulka We used an ingest pipeline with a grok processor for the plaintext (non-JSON) format.

Until 6.6, this was the only ingest pipeline used as the logs were always in plaintext format: https://github.com/elastic/beats/blob/6.6/filebeat/module/elasticsearch/audit/ingest/pipeline.json.

Starting with 6.7, we got a bit smarter and detected the format of the log entry first: https://github.com/elastic/beats/blob/6.7/filebeat/module/elasticsearch/audit/ingest/pipeline.json. Then, depending on whether it was JSON or not, we delegated further parsing to the appropriate sub-pipeline: https://github.com/elastic/beats/blob/6.7/filebeat/module/elasticsearch/audit/ingest/pipeline-plaintext.json (for plaintext) or https://github.com/elastic/beats/blob/6.7/filebeat/module/elasticsearch/audit/ingest/pipeline-json.json (for json).

**Comment by ycombinator** [comment]
I looked into fixing this in Filebeat for the short term. I'm afraid the fix isn't straightforward because there are other differences between Docker vs. non-Docker audit logs, such as certain other fields being present in one but not the other. I suspect we will just have to wait for the proper fix in Elasticsearch, which is being worked on over here: https://github.com/elastic/elasticsearch/pull/42671.

However, there is a workaround that could be used in the interim: https://github.com/elastic/elasticsearch-docker/commit/2931ec8e8f78ba645f91f20b2ca3cbfa86feed11.
