### ISSUE TITLE
[Linux] my server is cpu high when redis is down

### ISSUE THREAD

**Issue by Cyyking** [elastic/beats#12336]
I check filebeat log file is alway try to connect redis then server cpu io wait is more high.
How can resolve the problem?

**Comment by Cyyking** [comment]
![120](https://user-images.githubusercontent.com/16470319/58552682-983d0180-8245-11e9-988e-b720dafb13b5.png)
![1](https://user-images.githubusercontent.com/16470319/58552688-9b37f200-8245-11e9-8826-288a902bf2fb.png)

**Comment by kvch** [comment]
GH issues are reserved for verified bugs. Please post your question on Discuss: https://discuss.elastic.co
