### ISSUE TITLE
Document the expected behavior of the 'Beater' interface

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#1234]
The contract around the [Beater interface](https://github.com/elastic/beats/blob/master/libbeat/beat/beat.go#L40-L47) is not well documented which is problematic since third-parties implement it for their own Beats.

This has led to slightly different implementations among our Beats.

The `Beater.Cleanup()` can be called before the `Beater.Run()` finishes. This issue occurs if `Beater.Stop()` is implemented as a non-blocking method (i.e. signal to stop, but don’t wait). In this case `Stop()` is called and returns immediately and then `Cleanup()` is called. Meanwhile `Beater.Run()` has not exited yet.

Another related issue is that the process exits before `Beater.Run()` completes. This is problematic if any state needs to be flushed to disk before the process exits.

All Beats except Filebeat implement the `Stop()` method as a non-blocking method.

**Comment by ruflin** [comment]
@andrewkroh +1 on this. We should probably add some docs to the source code directly for godoc but also add more details to the developer guide. I would probably expect Stop() to always be blocking, what is your expectation?

**Comment by andrewkroh** [comment]
I think that it should not matter whether or not `Stop()` blocks because the process should not exit until after `Run()` and `Cleanup()` have completed.
