### ISSUE TITLE
Heartbeat default timeouts are too long

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#12360]
The default heartbeat timeout of 16s is quite long and can cause performance issues with large amounts of jobs since many idle jobs hang out in the scheduler. We should lower this to something more sensible, like `5s`. Users can set this to longer values if needed.

**Comment by jasonneurohr** [comment]
Any update on this issue and the PR? I came across this issue when looking into why my heartbeat monitors were taking 17 minutes between checks. Once I modified the ICMP checks to be 60s and added a timeout of 5s the problem went away. 

I'm pasting the scheduler logs so others who encounter the same thing might find this issue.

`WARN scheduler/scheduler.go:152.     2 tasks have missed their schedule deadlines in the last 15s`

and another exert from the heartbeat metric log

`{"scheduler":{"jobs":{missed_deadline":133}}}`

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
