### ISSUE TITLE
CoreDNS module documentation needs to be updated because autodiscover default input settings was changed

### ISSUE THREAD

**Issue by alakahakai** [elastic/beats#12380]
autodiscover default input settings was changed to the following, so CoreDNS module documentation needs to be updated accordingly.

filebeat.autodiscover:
  providers:
    - type: kubernetes
      hints.enabled: true
      hints.default_config.enabled: false

**Comment by exekias** [comment]
I think this can be closed now?

**Comment by ph** [comment]
PR was merged closing this.
