### ISSUE TITLE
[metricbeat]Add kube-controller metrics

### ISSUE THREAD

**Issue by odacremolbap** [elastic/beats#12389]
# Metricbeat Module / Dataset release checklist

Implement a new metricset under Kubernetes module to kube-controller `kubecontroller`. 

## Modules
For a metricset to go GA, the following criterias should be met:

* [x] Supported versions are documented
* [x] System tests exist
* [x] Automated checks that all fields are documented
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] Dashboards exists (if applicable)
* [x] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [ ] Test environment in Docker exist for integration tests

**Comment by andresrc** [comment]
Part of https://github.com/elastic/beats/issues/7058 ?

**Comment by odacremolbap** [comment]
closed since the only item left for all kubernetes components is integrated testing
