### ISSUE TITLE
filebeat setup fails when multiple versions of filebeat setup are invoked?

### ISSUE THREAD

**Issue by jordansissel** [elastic/beats#12436]
Log message reported from `filebeat -e setup`

```
error loading /usr/share/filebeat/kibana/7/dashboard/Filebeat-Zeek-Overview.json: returned 400 to import file: <nil>. Response: {"statusCode":400,"error":"Bad Request","message":"Document \"7cbb5410-3700-11e9-aa6d-ff445a78330c\" has property \"dashboard\" which belongs to a more recent version of Kibana (7.0.0)."}
```

This causes `filebeat setup` to exit non-zero/failure.

Background: We have multiple beats versions sending to the same cluster. At present, all versions of filebeat (v6.2.0 through v7.1.1 inclusive) have `filebeat -e setup` invoked[1], and there appears to be some conflict with multiple beats setups since v7.0.0

[1] We don't necessarily control which version of filebeat is sending us data, so we prepare by running `filebeat setup` for any number of expected beats versions.

Versions reporting this error:
* 7.0.0
* 7.0.1
* 7.1.0
* 7.1.1

![image](https://user-images.githubusercontent.com/131818/58932008-c70c1980-8716-11e9-96c5-7549d49e837f.png)

**Comment by ruflin** [comment]
What is your Elasticsearch & Kibana version?

**Comment by jordansissel** [comment]
Elasticsearch 6.5.4, Kibana 6.5.4

**Comment by gadelkareem** [comment]
Same error here with filebeat panw 7.9.0 and Kibana 7.5.0
