### ISSUE TITLE
[Auditbeat] auditd network.direction should use inbound/outbound

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#12445]
As per ECS the `network.direction` values should be `inbound` or `outbound` or `unknown`.

https://github.com/elastic/ecs/blob/v1.0.1/schemas/network.yml#L88-L92

But the `auditd` modules uses `incoming` and `outgoing` for audit events that include a socket message.

https://github.com/elastic/beats/blob/6c55de47f1fc9d0d41210e94f787eff4218bff14/vendor/github.com/elastic/go-libaudit/aucoalesce/coalesce.go#L112-L120

**Comment by leehinman** [comment]
https://github.com/elastic/go-libaudit/pull/76
