### ISSUE TITLE
Apache module to support 2.4.33

### ISSUE THREAD

**Issue by alloystory** [elastic/beats#12444]
Hi all,

I have a couple of logs from apache v2.4.33 that cannot be parsed properly by the default apache module. No configuration has been made to the apache log format. An example is shown below. I have opened a thread [here](https://discuss.elastic.co/t/filebeat-apache-module-unable-to-parse-certain-logs/184279) to note the issue. Please do assist in supporting this version.

Example:
Input
`123.123.123.123 - - [04/Jun/2019:12:25:00 +0000] "-" 400 226 "-" "-"`

Output (error.message on Kibana)
`Provided Grok expressions do not match field value: [123.123.123.123 - - [04/Jun/2019:12:25:00 +0000] \"-\" 400 226 \"-\" \"-\"]`

Thanks

**Comment by exekias** [comment]
Hi, could you please tell us a little bit more about your deployment?

- What operative system are you using?
- How did you install Apache?
- Are you using Apache default logging settings?
