### ISSUE TITLE
Add specific setting to turn on debugPrintProcessor

### ISSUE THREAD

**Issue by bschaeffer** [elastic/beats#12468]
Just because I turn on debug logging, doesn't mean I want to write all events to the debug log. I feel like there should be a separate configuration value for that.

Open to a PR?

**Comment by exekias** [comment]
Hi @bschaffer We have debug selectors that allow you to debug only for the subsystems you are interested on. Perhaps we could make events output use its own selector

are you willing to open a PR for this?

**Comment by bschaeffer** [comment]
Sure!
