### ISSUE TITLE
Please support AWS IAM Instance profiles!

### ISSUE THREAD

**Issue by davidmco65** [elastic/beats#12464]
I can't use the Functionbeat on my EC2 server because it doesn't appear to use the default credential provider chain.  Meaning that I have a Role assigned to me EC2 instance that gives it permission to access the bucket specified in the configuration, but the deploy function doesn't see use it and therefore has no permissions to do anything with S3.

I'm trying to deploy the functionbeat from our EC2 server and it's not possible given this missing functionality.  I've got my entire ELK stack deployment scripted except for this functionbeat.

**Comment by exekias** [comment]
I think https://github.com/elastic/beats/pull/12727 would fix this if used in Functionbeat? cc @kvch

**Comment by kvch** [comment]
Yes, I think so. But still, it needs a bit of work in Functionbeat. :)

**Comment by kaiyan-sheng** [comment]
@davidmco65 Thanks for creating this issue. When you mentioned `default credential provider chain`, do you mean the aws credential file under `~/.aws/credentials`?

**Comment by davidmco65** [comment]
@kaiyan-sheng No, the default credential provider chain runs through a set of potential credential providers.  One of which is the ~/.aws/credentials file, but others include the EC2 Instance Profile - a role that's assigned to the EC2 instance running the beat and would give the beat the permissions it needs to access the resources it needs, i.e., S3 bucket.  In our environment, we literally cannot use access key id/secret key, so there is no way to configure the function beat that will allow it to install properly.

Thanks!

**Comment by jderose9** [comment]
I need to be able to specify a named profile present in the ~/.aws/credentials file.

**Comment by Thiago-Dantas** [comment]
I also need this but in Metricbeat, should I open a new issue?

**Comment by kaiyan-sheng** [comment]
@Thiago-Dantas I'm planning to use this same issue to track for Metricbeat as well! Thanks!

**Comment by jeffvestal** [comment]
I have a customer who is interested in this feature so they don't have to store creds locally on the ec2 instance. 
@kaiyan-sheng ping me if you need more details. 
Thanks!

**Comment by kvch** [comment]
@kaiyan-sheng Are you sure this issue can be closed? The original author requested the feature for Functionbeat. However, your PR only adds support in metrcibeat and filebeat.

**Comment by kaiyan-sheng** [comment]
@kvch Good point, does Functionbeat use https://github.com/elastic/beats/blob/master/x-pack/libbeat/common/aws/credentials.go#L34 for getting credentials? I will reopen this issue for Functionbeat. Thank you!

**Comment by kvch** [comment]
No, it does not. Functionbeat depends on the AWS SDK to handle credentials. Thus, it only supports passing those via environment variables.

**Comment by prabaharang** [comment]
If Functionbeat uses AWS SDK, what is the credential provider chain is being used. Wouldn't AWS SDK allow to use Instance profile credentials by default (in case of Default Credential Provider Chain)?

**Comment by kvch** [comment]
I guess yes, but we haven't tested it yet. Also, all of the information I was able to found on the subject is for the v1 of `aws-sdk-go`. However, in Beats we use `aws-sdk-go-v2`, so there migth be differences between the docs of v1 and reality of v2.

**Comment by kaiyan-sheng** [comment]
Hi @kvch, since this issue is related to Functionbeat, is it ok if I assign it to you instead?

**Comment by kvch** [comment]
@kaiyan-sheng I've just assinged myself. Thanks for the ping.

**Comment by s-t-ev** [comment]
@kvch Any luck with implementing this for functionbeat?  Thanks!

**Comment by BrunoMCBraga** [comment]
Fellas, i come from the future and this problem still persists. Functionbeat seems to still be using AWS env variable credentials. I am currently playing with Elastic stack using one single node on as private network and i cannot afford to put my credentials there, specially when the list of permissions necessary: https://www.elastic.co/guide/en/beats/functionbeat/current/iam-permissions.html#iam-permissions-cloudwatch

Is quite big. Looks like a disaster ready to happen.
