### ISSUE TITLE
Getting error when filebeat connected to ES with SSL connection

### ISSUE THREAD

**Issue by ishu52** [elastic/beats#12494]
Hi Team,

I am deploying filebeat 6.7.2 on 'Database for ES" service on IBM cloud.

I have tried the same in the month of March 2019 and it was working fine but now with the same yaml i am getting error (as attached).

I have tried with local ES and everything works fine.

[kibanalogs.txt](https://github.com/elastic/beats/files/3275412/kibanalogs.txt)

![image](https://user-images.githubusercontent.com/7520400/59255963-8c433d80-8c50-11e9-8036-a21668ef0b6a.png)

![image](https://user-images.githubusercontent.com/7520400/59255981-97966900-8c50-11e9-8a6b-b9676a7ecb4f.png)

![image](https://user-images.githubusercontent.com/7520400/59256012-aa10a280-8c50-11e9-90e3-70b9d3a2ce2e.png)
![image](https://user-images.githubusercontent.com/7520400/59256043-b98feb80-8c50-11e9-8075-55ea5896c5db.png)

**Comment by prima101112** [comment]
Where is the error its all kubernetes config
