### ISSUE TITLE
List all known mountpoints in filesystem events

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#12497]
After https://github.com/elastic/beats/pull/6819, the filesystem metricset collects one event per mounted filesystem. If the filesystem is mounted several times only one event is generated per filesystem. This is intended to avoid data duplication as this metricset is intended to report metrics of filesystems. The mount point reported is the shortest one. The problem with this approach is that there are mount points that are not reported.

Something we could do to avoid this is to report all the known mountpoints instead of only the shortest one, this could be done by generating the event with a list of mountpoints instead of a single value, this wouldn't be breaking as the type of the field would still be keyword.

For example a resulting event would have fields like this:
```
    "system": {
        "filesystem": {
            ...
            "device_name": "/dev/dm-1",
            "mount_point": ["/var/log", "/etc/hosts"]
            "type": "xfs",
            ...
            }
        }
    }
```

**Comment by qqqasdwx** [comment]
Has this problem been solved?

**Comment by groge** [comment]
I have the same problem. 
host:/srv directory mapped /etc/hosts on container.
[host : df -h]
![image](https://user-images.githubusercontent.com/7495073/91510528-4edfd400-e918-11ea-88a5-71b8bd594b87.png)
[container: df -h]
![image](https://user-images.githubusercontent.com/7495073/91510568-733bb080-e918-11ea-9768-d0aad29696f7.png)

**Comment by qqqasdwx** [comment]
I saw that this problem was marked as stale, but no one told me that this problem has been fixed. Has this problem been fixed now?
