### ISSUE TITLE
Document default metricsets

### ISSUE THREAD

**Issue by urso** [elastic/beats#12502]
Metricbeat modules start a set of default metricsets, if no metricset is configured, or if the list of metricsets is empty. The set of default metricsets is based on internal knowledge available in code only. Without reading the code it is quite difficult to learn the default metricsets to be run.

Request:
- Document default metricsets
- Make it clear in docs that an empty list will load the default ones.
- (wishfull thinking) Have the info available in a modules _meta section and have support for automated testing.

**Comment by ruflin** [comment]
Added the `:infrastructure` label as I think the integrations team should take care of this. I was thinking we already document this for most modules but need to double check.

**Comment by fearful-symmetry** [comment]
Agreed, I think this is a good idea.

**Comment by fearful-symmetry** [comment]
Okay actually looking into this now. 
So, default metricsets are defined by `mb.DefaultMetricSet()` in `init()` Using that to generate the actual list of defaults isn't gonna be hard. Where do we want to document this? In `modules.d/*.yml` somehow? In the asciidocs for the modules? in `_meta` ?

> (wishfull thinking) Have the info available in a modules _meta section and have support for automated testing.

@urso Automated testing of what? The correctness of the list of default modules?

**Comment by ruflin** [comment]
Having it documented in the docs would be great.

Thinking ahead for lightweight modules it probably has to be specified in the module `fields.yml` (or best case, generated to keep it in sync). This we can then use for testing and generating docs.

**Comment by fearful-symmetry** [comment]
> Thinking ahead for lightweight modules it probably has to be specified in the module fields.yml

I wonder if we can have it in _just_ the fields.yml as opposed to `init()` ? 

Either way, I'll put together a PR to document it in the module-level docs.

**Comment by ruflin** [comment]
Good question, agree that we don't necessarly need it in the init part. Would mean a change to the framework but sounds like a good change if we can do it.

**Comment by fearful-symmetry** [comment]
Yah, `init` is kinda a weird place for it, and it took me forever to track down at first.

I'm also thinking that once we have it in the yml, we could easily generate a `=== Default Modules` asciidoc blurb.

**Comment by dedemorton** [comment]
@fearful-symmetry Can we close this issue now?

**Comment by fearful-symmetry** [comment]
Yep!
