### ISSUE TITLE
Relavant warnings when config file is missing during installation

### ISSUE THREAD

**Issue by maheshmadpathi** [elastic/beats#12526]
**Describe the enhancement:**
Filebeat doesn't warn anything about config when its missing during installtion or service startup on Windows, I used ansible to deploy filebeat on windows machines somehow the specific template wasn't picked up correctly and one of the VM didnt get the config file because of which filebeat service couldn't get started with no specific errors related to config, I got below errors but nothing specific that helps to investigate

_“Error 1067: The process terminates unexpectedly.”
“Error 109: The pipe has been ended.”
“Error 1053: The service did not respond in a timely fashion.”
"ERROR instance/beat.go:691 Exiting: Could not start registrar: Error loading state: Error decoding states: invalid character '\x00' looking for beginning of value"_

**Describe a specific use case for the enhancement or feature:**
Filebeat on windows server should return specific warnings when config is missing

**Comment by andrewkroh** [comment]
There isn't any way that I'm aware of for the Beat to return a better error message to the service manager.

One idea though would be to detect that the Beat is running as a service and then write the final error message to the Application event log.

**Comment by maheshmadpathi** [comment]
unfortunately nothing found in eventlog either, multiple error codes eventually misleads.
