### ISSUE TITLE
[Journalbeat] incorrect values when reading received journal from other hosts

### ISSUE THREAD

**Issue by frantz45** [elastic/beats#12528]
journald can forward events thanks to systemd-journal-upload/systemd-journal-remote.
By default received events are written to /var/log/journal/remote/remote-host.journal.
If you configure journalbeat to read this directory some values are wrong.
Journalbeat does not read all fields from the journal.

Example:

journalctl --file /var/log/journal/remote/remote-1.1.1.1.journal:
{
        "__CURSOR" : "s=79b8ce42aeef4d6d88e2584c06ed56b1;i=3d37;b=c74406dc583b4f41b4b8551ab86202c7;m=383b55e8;t=58b345a5dc59b;x=5bb54af179ef8a92",
        "__REALTIME_TIMESTAMP" : "1560431854208411",
        "__MONOTONIC_TIMESTAMP" : "943412712",
        "_BOOT_ID" : "c74406dc583b4f41b4b8551ab86202c7",
        "PRIORITY" : "6",
        "_MACHINE_ID" : "4e27ba6133b14e3abad7581e9e6b2fe7",
        "SYSLOG_FACILITY" : "3",
        "SYSLOG_IDENTIFIER" : "systemd",
        "_UID" : "0",
        "_GID" : "0",
        "CODE_FILE" : "src/core/job.c",
        "CODE_FUNCTION" : "job_log_status_message",
        "MESSAGE_ID" : "39f53479d3a045ac8e11786248231fbf",
        "RESULT" : "done",
        "_TRANSPORT" : "journal",
        "_PID" : "1",
        "_COMM" : "systemd",
        "_EXE" : "/usr/lib/systemd/systemd",
        "_CAP_EFFECTIVE" : "1fffffffff",
        "_SYSTEMD_CGROUP" : "/",
        "_CMDLINE" : "/usr/lib/systemd/systemd --switched-root --system --deserialize 22",
        "_SELINUX_CONTEXT" : "system_u:system_r:init_t:s0",
        "CODE_LINE" : "773",
        "UNIT" : "systemd-tmpfiles-clean.service",
        "MESSAGE" : "Started Cleanup of Temporary Directories.",
        "_HOSTNAME" : "centos7.localdomain",
        "_SOURCE_REALTIME_TIMESTAMP" : "1560431854205545"
}

Corresponding log written by journalbeat:
{
	"@timestamp":"2019-06-13T13:17:34.208Z",
	"@metadata":{
		"beat":"journalbeat",
		"type":"_doc",
		"version":"7.1.1"
	},
	"message":"Started Cleanup of Temporary Directories.",
	"event":{
		"created":"2019-06-13T13:17:38.589Z"
	},
	"syslog":{
		"facility":3,
		"priority":6,
		"identifier":"systemd"
		},
	"process":{
		"name":"systemd",
		"uid":0,
		"capabilites":"1fffffffff",
		"executable":"/usr/lib/systemd/systemd",
		"cmd":"/usr/lib/systemd/systemd --switched-root --system --deserialize 22",
		"pid":1
	},
	"host":{
		"containerized":false,
		"boot_id":"f2affeac84124fb697a4ec0c57bff084",
		"hostname":"foobar",
		"id":"85acb32bb5234428a32ee7fa22face61",
		"name":"foobar",
		"architecture":"x86_64",
		"os":{
			"version":"7 (Core)",
			"family":"redhat",
			"name":"CentOS Linux",
			"kernel":"3.10.0-957.5.1.el7.x86_64",
			"codename":"Core",
			"platform":"centos"
		}
	},
	"agent":{
		"id":"ea7376ec-83c1-4482-a93b-0286a17e7068",
		"version":"7.1.1",
		"type":"journalbeat",
		"ephemeral_id":"d9121701-f028-4aa0-9d11-a24ad15eeb58",
		"hostname":"foobar"
	},
	"systemd":{
		"cgroup":"/",
		"transport":"journal"
	},
	"journald":{
		"code":{
			"file":"src/core/job.c",
			"line":773
		},
		"custom":{
			"code_function":"job_log_status_message",
			"message_id":"39f53479d3a045ac8e11786248231fbf",
			"result":"done",
			"unit":"systemd-tmpfiles-clean.service",
			"selinux_context":"system_u:system_r:init_t:s0"
		}
	},
	"ecs":{"version":"1.0.0"}
}

As you can see some values (especially host values) are wrong: hostname, machine_id, boot_id... they correspond to the localhost and not the remote host.

**Comment by ph** [comment]
cc @kvch

**Comment by kvch** [comment]
Indeed. We need to support all fields of the export format: https://www.freedesktop.org/wiki/Software/systemd/export/

**Comment by kvch** [comment]
Looking in the the problem, the issue is that `add_host_metadata` processor overwrites the field `host.hostname` set by the journal reader.  Open PR to copy the field if `remote` is set: https://github.com/elastic/beats/pull/12714

Until the option is released, you can modify your processor configuration to rename the field before `add_host_metadata` is applied to the event:
```yaml
processors:
- rename:
    fields:
     - from: "host.hostname"
       to: "source.hostname"
- add_host_metadata: ~
```
