### ISSUE TITLE
[Filebeat] Logstash module should be able to read Logstash logs from a container

### ISSUE THREAD

**Issue by bczifra** [elastic/beats#12531]
**Describe the enhancement:**
Allow [Filebeat's Logstash module](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-logstash.html) to read Logstash logs from another container.

**Describe a specific use case for the enhancement or feature:**
In a scenario where Logstash is running [on Docker](https://www.elastic.co/guide/en/logstash/current/docker.html) it would be helpful to be able to use Filebeat's [Logstash module](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-logstash.html) in such a way as to read Logstash logs from the Logstash container. There is a [container input](https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-container.html)- perhaps this could be leveraged?

**Comment by jsoriano** [comment]
@bczifra thanks for opening this request, but I think this should be already possible.

Any module can be used when filebeat is run in a container and the service generating the logs is in a different container, this is something we support.
The best way to do it is by using the [docker autodiscover provider](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover.html), with [hints-based autodiscover](https://www.elastic.co/guide/en/beats/filebeat/7.1/configuration-autodiscover-hints.html) filebeat will setup the proper input automatically. Internally this is going to use the [docker input](https://www.elastic.co/guide/en/beats/filebeat/7.1/filebeat-input-docker.html), that is going to be deprecated in favour of the new [container input](https://www.elastic.co/guide/en/beats/filebeat/7.2/filebeat-input-container.html) in 7.2.
If hints-based autodiscover is not used, the autodiscover template will need to have the input configurations, you can find an example for redis module in the autodiscover docs.
Filebeat will need access to the docker socket and log files, you can find more information about running filebeat on docker with all these options here: https://www.elastic.co/guide/en/beats/filebeat/7.1/running-on-docker.html

If logstash is configured to write logs to files things can get a bit trickier but it should be also possible. In this case the logs should be written into a volume that is also mounted in filebeat, and the logstash module should be configured with the paths for these files.

Happy to help if you have found a case where none of these options would work.

**Comment by andresrc** [comment]
Closing, please reopen if a follow up is needed.
