### ISSUE TITLE
some of filebeats crashed when receiving new configuration from central management

### ISSUE THREAD

**Issue by jyj1993126** [elastic/beats#12530]
- Version: 
filebeat: 6.5.4
elasticsearch: 6.5.4
kibana: 6.5.4
logstash: 6.5.4

- Operating System: 
os: rhel 6.6
go version: 1.10.6
kernel version: 2.6.32-504.el6.x86_64

panic: send on closed channel

![image](https://user-images.githubusercontent.com/6315451/59440860-36c28880-8e2a-11e9-9011-ce24f8c9cf46.png)

**Comment by ph** [comment]
Closed by #12424
