### ISSUE TITLE
not read correctly fields that declared within filebeat

### ISSUE THREAD

**Issue by zdhuangelephant** [elastic/beats#12542]
there is a filebeat.yaml file that declared using configmap, but it is not read correctly field's value?
please tell me why? thanks guy 

the filebeat.yaml as followiing:
`---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.projectName }}-filebeat-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "Business.projectName" . }}
    chart: {{ template "Business.chart" . }}
    releaseTime: {{ quote .Release.Time.Seconds }}
    release: {{ template "Business.fullname" . }}
    kubernetes.io/cluster-service: "true"
data:
  filebeat.yml: |
    output.kafka:
      enabled: true
      hosts: ["10.22.xxx.xxx:9092","10.22.xxx.xxx:9092","10.22.xxx.xxx:9092"]
      topic: 'original-log-aaa-%{[fields.log_source]}'
      partition.round_robin:
        reachable_only: false
      required_acks: 1
      compression: gzip
      max_message_bytes: 1000000

    filebeat:
      inputs:
        - type: log
          paths:
            {{ tpl .Values.filebeat.collectPaths.containerConfd . }}
          fields_under_root: true
          fields:
            log_source: container-confd
            #log_department: {{ .Values.groupName }}
          tail_files: true
          symlinks: true
` 

problem:
 the topic not joined correctly!

**Comment by zdhuangelephant** [comment]
please ignore style format

**Comment by exekias** [comment]
hi @zdhuangelephant, we try to keep Github issues for confirmed bugs only, could you please open a new thread asking for help on discuss? https://discuss.elastic.co/c/beats

best regards
