### ISSUE TITLE
Dashboard screen captures are old and inconsistent

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#12555]
**The problem:**

The Filebeat and Metricbeat module docs show very old screen captures, and the screen captures are inconsistent (some include chrome, some do not, some use `[role="screenshot"]`, most are captured using different resolutions/aspect ratio/, etc).

For Metricbeat, we [list all the modules](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-modules.html) and show which modules have dashboards, but when you follow the link to the doc page, the dashboard section is often missing.

We need to ask ourselves:

_Does the value of providing screenshots outweigh the effort required to maintain them?_

**If yes** - let's create a plan and guidelines for creating and maintaining these assets over time.

**If no** - let's remove them from the docs because the current state is potentially confusing to customers, makes the documentation seem out-of-date, and looks a bit unprofessional. 

@Titch990 FYI - feel free to take the lead on this and decide how you want to proceed.

**Comment by dedemorton** [comment]
@exekias FYI that I created an issue for the problem we discussed in chat. Marjorie and/or I can help you come up with consistency guidelines if you decide that you want to maintain the screenshots.

**Comment by exekias** [comment]
We discussed this and we agree that dashboard screenshots are important, so we should come up with a plan to keep them up to date. More discussions will happen, I hope we can reach a compromise between manual/automatic work for this task.

**Comment by kaiyan-sheng** [comment]
I agree with what @tbragin suggested at the meeting. If we can remove the Kibana left hand side from dashboard screenshots, everything else seem to be consistent for different versions.
For example:
<img width="1158" alt="Screen Shot 2019-06-18 at 3 14 20 PM" src="https://user-images.githubusercontent.com/14081635/59720341-d3df4180-91db-11e9-934e-9631299de6d4.png">

**Comment by dedemorton** [comment]
@kaiyan-sheng Removing the chrome definitely makes it less obvious that the dashboards are out-of-date. This is a double-edged sword, however. Let's make this the standard (dashboard only...no chrome) but also have a plan for updating the screenshots at major releases (using automation, if possible).
