### ISSUE TITLE
[metricbeat]kubernetes apiserver metric deprecated

### ISSUE THREAD

**Issue by odacremolbap** [elastic/beats#12569]
we are currently gathering using metrics from `apiserver_request_latencies` kubernetes apiserver. That metric is marked as deprecated, and is somehow behind the WIP controller, proxy and scheduler metrics.

`apiserver_request_duration_seconds_bucket` seems to be the metric we should be looking at.

There are some other counters we could add to be on par with the aforementioned kubernetes metricsets

**Comment by exekias** [comment]
Thanks for noticing! I hope we can document what versions this is expected to work with

**Comment by odacremolbap** [comment]
closing as of #12922
