### ISSUE TITLE
6.5 incorrectly has docs for logging.files.redirect_stderr

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#12560]
In 6.5 the docs show [`logging.files.redirect_stderr`](https://www.elastic.co/guide/en/beats/winlogbeat/6.5/configuration-logging.html#_literal_logging_files_redirect_stderr_literal_phrase_role_experimental_phrase) as an option, but this option first appeared in v6.6.0.

The 6.5 docs got this in https://github.com/elastic/beats/pull/9317.

**Comment by dedemorton** [comment]
Closed a long time ago by #12847
