### ISSUE TITLE
Couldn't get the Perfmon data for all the processes in Windows-7 32 bit server

### ISSUE THREAD

**Issue by prakash1243** [elastic/beats#12590]
Hi @narph ,
I have tested the snapshot build from (gs://beats-ci-artifacts/snapshots/metricbeat/metricbeat-oss-8.0.0-SNAPSHOT-windows-x86.zip) on a 32-bit server with a wild card query, it  just gives the output with the process name as '*' instead of all the processes, Here is the config and the output:

**Config:**
`- module: windows
  metricsets: [perfmon]
  period: 1s
  perfmon.counters:
  - instance_label: process_thread_count
    measurement_label: process.thread.count
    query: '\Process(*)\Thread Count'`

**Output:**

`:183    Publish event: {
  "@timestamp": "2019-06-18T06:04:11.701Z",
  "@metadata": {
    "beat": "metricbeat",
    "type": "_doc",
    "version": "8.0.0"
  },
  "metricset": {
    "name": "perfmon"
  },
  "service": {
    "type": "windows"
  },
  "windows": {
    "perfmon": {
      "process_thread_count": "*",
      "process": {
        "thread": {
          "count": 4
        }
      }
    }
  },`

It works fine with the windows 64 bit servers with the metricbeats 64 bit binary, this has been found only with the 32-bit servers.

**Comment by narph** [comment]
hi @prakash1243 , good find. 
Indeed, in 32 bit windows systems, the PdhExpandWildCardPathW does not seem to expand the counter paths, will not return any errors but just the initial counter query.
I have tested the scenario using [PdhExpandCounterPathW](https://docs.microsoft.com/en-us/windows/desktop/api/pdh/nf-pdh-pdhexpandcounterpathw) instead and seems to return the list of counter paths.

**Comment by prakash1243** [comment]
> hi @prakash1243 , good find.
> Indeed, in 32 bit windows systems, the PdhExpandWildCardPathW does not seem to expand the counter paths, will not return any errors but just the initial counter query.
> I have tested the scenario using [PdhExpandCounterPathW](https://docs.microsoft.com/en-us/windows/desktop/api/pdh/nf-pdh-pdhexpandcounterpathw) instead and seems to return the list of counter paths.

@narph , Thank you . Could you please merge this with the PR with the master branch, I'll test the snapshot build and let you know. Thanks !

**Comment by narph** [comment]
@prakash1243 , merged, feel free to reopen this issue if the fix did not work for you

**Comment by prakash1243** [comment]
@narph - It worked. Thanks !
But I encountered a different issue this time, when a process has been stopped and started again, metribceats windows module not able to get the data for the particular restarted process, unless metricbeats is completely restarted. Should I need to create a new issue ? please do let me know.
