### ISSUE TITLE
Change Unpack method for tlsClientAuth

### ISSUE THREAD

**Issue by simitt** [elastic/beats#12602]
Change [`Unpack`](https://github.com/elastic/beats/blob/master/libbeat/common/transport/tlscommon/types.go#L228) method for `tlsClientAuth` from `Unpack(interface{}) error` to `Unpack(string) error` and remove setting to `required` when nil.
Current implementation is misleading as default setting is to only set `client_auth: required` when `CAs` are configured, see https://github.com/elastic/beats/blob/master/libbeat/common/transport/tlscommon/server_config.go#L101. 

cc @urso and @ph

**Comment by danishprakash** [comment]
@simitt correct me If I'm wrong but this looks like a rather trivial change, mind if I raise a PR for this?
