### ISSUE TITLE
[tests] Add more tests reflecting expected behavior when TLS is enabled

### ISSUE THREAD

**Issue by simitt** [elastic/beats#12601]
Enhance the current testsuite around server/client communication over TLS to better reflect default and allowed settings. 

Some of the tests from [apm-server](https://github.com/elastic/apm-server/blob/master/tests/system/test_access.py) could be added to the existing [filebeat tests](https://github.com/elastic/beats/blob/master/filebeat/tests/system/test_tcp_tls.py). The tests follow a similar setup. 

There is also a https://github.com/elastic/apm-server/pull/2291 up, testing the default and supported cipher suites (although tests on CI need to be fixed first). 

cc @ph and @urso

**Comment by urso** [comment]
@kvch fyi

**Comment by kvch** [comment]
Current TLS tests in apm-server: https://github.com/elastic/apm-server/blob/master/tests/system/test_tls.py

**Comment by urso** [comment]
Anything in the test suite we want to port to tlscommon go based tests?
