### ISSUE TITLE
Send period in metricbeat data

### ISSUE THREAD

**Issue by skh** [elastic/beats#12616]
For querying metricbeat documents for the Kibana Infra UI app, it would be very helpful to know the interval in which data is sent by the various metricbeat modules.

One idea that came up in a call is to include the configured `period` in the documents themselves.

**Comment by kaiyan-sheng** [comment]
Nicolas had an old PR for doing the same thing: https://github.com/elastic/beats/pull/6929

**Comment by exekias** [comment]
Thank you for opening, is there anywhere where we can read how you plan to use it?

**Comment by skh** [comment]
@exekias It would be a solution to the problem outlined in https://github.com/elastic/kibana/issues/36774

**Comment by simianhacker** [comment]
@exekias If the period is stored with the event data then we would need to get a sample from the time range. Either using an aggregation (terms?) or just plucking the last document where the field exists (along with filtering for time range and whatnot).

**Comment by exekias** [comment]
As discussed yesterday:

In order to detect gaps, it would be nice to have the reporting period in docs. The UI can then query for the max period across docs for some metric and use it as the minimum bucket size for the query. Then it will now that an empty bucket is a gap int he data.

**Comment by exekias** [comment]
@sorantis FYI ^
