### ISSUE TITLE
GPG Signed Elastic Container Images

### ISSUE THREAD

**Issue by canit00** [elastic/beats#12666]
We're enabling signature-verification in Docker enforcing trusted registries as described in this [article.](https://rhelblog.redhat.com/2017/07/25/signed-images-red-hat-container-catalog/)

However, been unable to determine that the beats docker images are gpg signed and would like to request this.

The command as described in the article is as follows.

```
# atomic trust add \
--pubkeys /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release \
--sigstore https://access.redhat.com/webassets/docker/content/sigstore \
registry.access.redhat.com
```

Regardless of the OS vendor once images are GPG signed it will require the following
> --pubkeys 
> --sigstore 

- Beat Version: filebeat:6.2.1
- Operating System: RHEL 7.4
- Docker Version: 
 Version: 1.12.6
 API version: 1.24
 Package version: docker-1.12.6-68.gitec8512b.el7.x86_64
 Go version: go1.8.3
 Git commit: ec8512b/1.12.6
 Built: Thu Nov 16 15:19:17 2017
 OS/Arch: linux/amd64

**Comment by kvch** [comment]
I've transferred the issue, as beats-docker is going to be archived.

**Comment by andrewkroh** [comment]
Docker has "Docker Content Trust" (DCT) now (https://docs.docker.com/engine/security/trust/content_trust). That's probably the avenue to for signing images.

@Conky5 Do you know if we are signing any images today?

**Comment by Conky5** [comment]
@andrewkroh no we aren't currently signing any docker images today with the Docker Content Trust mechanism.

**Comment by fxdgear** [comment]
@andrewkroh FWIW we already have the infra in place to sign images with DCT.  We just need to add it to the release process! :)
