### ISSUE TITLE
HEALTHCHECK in Docker images

### ISSUE THREAD

**Issue by willfarrell** [elastic/beats#12665]
Would you like a PR for having a default `HEALTHCHECK` in place. I'm more than happy to submit one.

Filebeat example:
```Dockerfile
HEALTHCHECK --interval=5s --timeout=3s \
    CMD ps aux | grep '[f]ilebeat' || exit 1
```
The above HEALTHCHECK is more for consistency in monitoring tools. As pointed out by @exekias adding instrumentation to beats may be required. We're compiling a list of what would constitute an unhealthy state, please post below if you have ideas.

## Situations where beats would be running and be unhealthy
- config has syntax errors
- networking errors - unable to resolve endpoint

**Comment by kvch** [comment]
I have transferred the issue, as `beats-docker` repo is going to be archived.
