### ISSUE TITLE
Feature: Use alpine as base image

### ISSUE THREAD

**Issue by willfarrell** [elastic/beats#12664]
Would be nice to have a smaller docker image.

You can see a sample of `filebeat` on `alpine` here: https://github.com/willfarrell/docker-filebeat/blob/master/5.2.1/Dockerfile

Is is possible to compile `beats` for `muslibc` so that a `glibc` hack is not required? Tackling this would allow for an even smaller image than I currently have.

**Comment by kvch** [comment]
I transferred the issue to elastic/beats, as beats-docker is going to be archived.

**Comment by ph** [comment]
@mikemadden42 Is this is something we are planning to do?

**Comment by mikemadden42** [comment]
@ph I have not seen a plan to switch from centos to alpine as the base image.  However, we're working on releasing additional images bases on Red Hat UBI7.

https://github.com/elastic/beats/issues/14214

**Comment by ph** [comment]
I would say we can close this since redhat UBI7 offer a similar experience wdyt @mikemadden42 ?

**Comment by mikemadden42** [comment]
@ph I think we can close it, especially considering this historical article.  RH's UBI7 image is really close to a minimal CentOS 7 image.

https://www.elastic.co/blog/docker-base-centos7
