### ISSUE TITLE
build script docker run --network=host does not work with mac os

### ISSUE THREAD

**Issue by alakahakai** [elastic/beats#12668]
The build script uses the following:

local-httpd:
	docker run --rm -d --name=$(HTTPD) --network=host \
	  -v $(ARTIFACTS_DIR):/mnt \
	  python:3 bash -c 'cd /mnt && python3 -m http.server'
timeout 120 bash -c 'until curl -s localhost:8000 > /dev/null; do sleep 1; done'

--network=host does not work on mac os with docker desktop, suggest to change to the following:

local-httpd:
	docker run --rm -d --name=$(HTTPD) -p 8000:8000/tcp \
	  -v $(ARTIFACTS_DIR):/mnt \
	  python:3 bash -c 'cd /mnt && python3 -m http.server'
timeout 120 bash -c 'until curl -s localhost:8000 > /dev/null; do sleep 1; done'

**Comment by kvch** [comment]
I have transferred the issue, as the repo `beats-docker` is going to be archived.

**Comment by jsoriano** [comment]
@alakahakai what build script do you mean? Is this still an issue after the migration of docker builds to the beats repo?
