### ISSUE TITLE
Default CMD does not allow syslog/file output for logging

### ISSUE THREAD

**Issue by NirBenor** [elastic/beats#12667]
The container CMD sets the `-e`(See `CMD` at `Dockerfile.j2`) flag by default which logs to stderr and disables syslog/file output.
This means configuring `logging.to_files` in `filebeat.yml` has no effect

- Beat Version: 6.3.1
- Operating System: MacOS High sierra 10.13.5
- Docker Version: Version 18.03.1-ce-mac65 (24312)
- Steps to Reproduce: Add `logging.to_files` in `filebeat.yml`.
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-logging.html

**Comment by kvch** [comment]
I have transferred the issue, as `beats-docker` is going to be archived.
