### ISSUE TITLE
Syslog input fails to close sockets exhausting file handles 

### ISSUE THREAD

**Issue by alakahakai** [elastic/beats#12684]
Filebeat is running with the Syslog input and the Kafka output. 

When there was a network config error on the Kafka side and Filebeat spawned threads continually to ingest data to the point that the OS ran out of file descriptors. 

There is no configuration option for the Syslog input to limit the number of harvesters like the regular Log input. There should be a default limit to control the number of threads spawned so this doesn't happen. In addition, there should be a configurable limit like the file input, so that users can change the system default.

**Comment by ph** [comment]
Hello, sorry for the late response, it's now possible to limit the number of concurrent connections in the syslog input.

https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-syslog.html#filebeat-input-syslog-tcp-max-connections

**Comment by ph** [comment]
Not that, this is best effort due to the nature of syslog communication.
