### ISSUE TITLE
AWS module support sdk credential provider chain

### ISSUE THREAD

**Issue by justinwalz** [elastic/beats#12708]
First - big thanks to the people working on the AWS module. It's great to be able to ingest these metrics and view them alongside our other metrics and logs.

**Describe the enhancement:**
Allow users to decide how to configure aws credentials, by relying on the default sdk provider chain if keys are not specified in the beats configuration directly.

Using the aws metricbeat module, I expected that I would be able to mount a credentials file into our docker container at `/root/.aws/credentials`, however config validation requires `access_key_id` and others to be set. 

See https://discuss.elastic.co/t/aws-module-credentials-configuration-support-default-credentials-provider for more context. 

**Describe a specific use case for the enhancement or feature:**
The aws sdk by default will look for configuration, env variables, and even ec2metadata if present. All of these are viable alternatives to templating the beats config file or using env variables.

**Comment by kaiyan-sheng** [comment]
Thank you @justinwalz for creating this ticket. We actually just talked about this enhancement literally 1 week ago in a meeting 😬I will use this ticket to track the work and please feel free to test and review the code once the PR is ready.

**Comment by exekias** [comment]
@kaiyan-sheng this is a great opportunity to create a common AWS client initialization function under `libbeat/common`, it should help us standardizing client initialization parameters and behavior across all beats (functionbeat, metricbeat module & ELB autodiscover provider)

cc @ph @kvch @andrewvc

**Comment by kaiyan-sheng** [comment]
@exekias Yes, I already need this function in libbeat so it can be used for both filebeat s3 input and metricbeat aws module.
