### ISSUE TITLE
PacketBeat for mongo slow query monitoring

### ISSUE THREAD

**Issue by abhimanyunagrath** [elastic/beats#12732]
Hi I have a mongo 4.0 (config(27018), shard(27021) and monogos(27017) running on the same machine) with SSL enabled. I have enabled packetbeat 6.7 on the server . Rest all stats look fine . But in top 10 slow queries I am getting query name like : admin.$cmd.otherCommand(),
config.$cmd.otherCommand()

Any help how I will get the exact query name?

**Comment by ernanirst** [comment]
I'm running packetbeat `7.0.0-rc2` as a DaemonSet insise a k8s cluster to monitor a MongoDB v3.6 and am experiencing the same problem. I suspect it's some missing configuration.

**Comment by sbiffi** [comment]
I have the same behavior with some clients, eg: nodejs moongoose.

**Comment by mitoihs** [comment]
I have the same issue. Windows Server 2016, MongoDB 4.4, Packetbeat 7.10.0, no SSL.
