### ISSUE TITLE
Add `instance` label by default when using Prometheus collector

### ISSUE THREAD

**Issue by exekias** [elastic/beats#12739]
Prometheus server adds `job` and `instance` labels when scraping endpoints, more info can be found here: https://prometheus.io/docs/concepts/jobs_instances/

When you use Metricbeat to scrape Prometheus endpoints, these labels are not present. Users may expect this labels to be present anyway, so we could add `instance` at the very least, like this:

 - Add `instance` label, defaulting to the `host:port` combination of the scraped service, this would give it the same behavior as in Prometheus.

 - **If label is present already** the code should NOT change it. This could happen, for instance, if we are using the federate API to scrape directly from Prometheus server.

We would need to figure out a good default for `job` label, or leave it out for now. One option could be setting the module name in it. So when using raw Prometheus collector it will always be `prometheus`, but when using lightweight modules it could be something else, like `cockroachdb`

**Comment by vjsamuel** [comment]
on similar lines, should we generate the `up` metric as well?

**Comment by ChrsMark** [comment]
@exekias `instance` label addition is done. Should we consider this as completed?

**Comment by exekias** [comment]
Great to see that implemented! What about the `job` field? I'm leaning towards filling it with the module name unless we find a better value. It's probably better to have that than nothing. Any other idea?

**Comment by exekias** [comment]
> on similar lines, should we generate the `up` metric as well?

This probably makes sense, I'll open a different issue for it!

**Comment by ChrsMark** [comment]
> Great to see that implemented! What about the `job` field? I'm leaning towards filling it with the module name unless we find a better value. It's probably better to have that than nothing. Any other idea?


Hey @exekias , I think this is a good idea! I opened a PR with this implementation:
https://github.com/elastic/beats/pull/13878
