### ISSUE TITLE
Incorrect topology IP detection on windows servers

### ISSUE THREAD

**Issue by SergNG** [elastic/beats#128]
Hi guys,

at first thanks for such a great tool :)

I think I've found a bug in topology IP detection on windows servers(at least it's present on windows 2003 server). The issue is that net.InterfaceAddrs() returns IPs without netmask (for example 1.1.1.1) on windows, and obviously it can't pass validation against:

```
            if ipnet, ok := addr.(*net.IPNet); ok {
```

I've fixed this by changing to:

```
            if ipnet, ok := addr.(*net.IPAddr); ok {
```

in file common/net.go (line 17), but I believe there should be added some kind of OS check so this detection works correctly on both linux and windows servers.

Best regards, Serg

**Comment by shadowcodex** [comment]
How did you get it installed on windows?

**Comment by monicasarbu** [comment]
Gathering topology map information with Packetbeat is deprecated starting with 5.0.0, but the fix can still be applied to older versions.

**Comment by monicasarbu** [comment]
Closing it for now.
