### ISSUE TITLE
filebeat can not use modules system on centos7

### ISSUE THREAD

**Issue by wangqiongkaka** [elastic/beats#12806]
this my config
/etc/filebeat/modules.d/system.yml
```
# Module: system
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.1/filebeat-module-system.html

- module: system
  # Syslog
  syslog:
    enabled: true

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths: ["/var/log/messages"]

    # Convert the timestamp to UTC. Requires Elasticsearch >= 6.1.
    #var.convert_timezone: false

  # Authorization logs
  auth:
    enabled: true

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths: ["/var/log/audit/audit.log"]

    # Convert the timestamp to UTC. Requires Elasticsearch >= 6.1.
    #var.convert_timezone: false
```
I can not reading messages and the dashboards of syslog says no results found

![图片](https://user-images.githubusercontent.com/34996871/60750810-871fa700-9fe0-11e9-9948-f6ecadd00cd0.png)

**Comment by kaiyan-sheng** [comment]
Hello @wangqiongkaka thanks for creating this. But we would kindly ask you to post all questions and issues on https://discuss.elastic.co/c/beats before opening a Github Issue. Your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue or open a new one with more details. Thanks in advance!
