### ISSUE TITLE
filebeat can not use modules system on centos7

### ISSUE THREAD

**Issue by wangqiongkaka** [elastic/beats#12807]
this my config
/etc/filebeat/modules.d/system.yml

Module: system
Docs: https://www.elastic.co/guide/en/beats/filebeat/7.1/filebeat-module-system.html

    module: system
    Syslog

    syslog:
    enabled: true
    Set custom paths for the log files. If left empty,
    Filebeat will choose the paths depending on your OS.

    var.paths: ["/var/log/messages"]
    Convert the timestamp to UTC. Requires Elasticsearch >= 6.1.

    #var.convert_timezone: false
    Authorization logs

    auth:
    enabled: true
    Set custom paths for the log files. If left empty,
    Filebeat will choose the paths depending on your OS.

    var.paths: ["/var/log/audit/audit.log"]
    Convert the timestamp to UTC. Requires Elasticsearch >= 6.1.

    #var.convert_timezone: false
    

I can not reading messages and the dashboards of syslog says no results found

![图片](https://user-images.githubusercontent.com/34996871/60750973-01046000-9fe2-11e9-99a4-34315d088e3d.png)

**Comment by exekias** [comment]
Hi @wangqiongkaka, indentation seems off, not sure if it's because of the copy/paste. Could you please share your Filebeat logs?

**Comment by andresrc** [comment]
Closed for now. Please reopen if a follow up is needed.
