### ISSUE TITLE
[Metricbeat] Matrix compatibility versions to be tested out

### ISSUE THREAD

**Issue by v1v** [elastic/beats#12817]
I'd like to discuss further the possibility to extend the test coverage for the modules fo the metricbeat project. The idea of this particular test coverage is to extend the current version matrix for each module and therefore have a way to test every module with a certain list of versions. 

At the moment, I've seen some specific configuration where those versions are overridden in the docker-compose file, but only for certain modules, such as mysql, apache, kafka and haproxy. See https://github.com/elastic/beats/blob/d21cf680bc8b7e923ea257a2050cacebec81763d/metricbeat/docker-compose.yml#L63 for instance.

Regarding the implementation side, we could keep the docker-compose configuration as simple as possible with the default version for each module and add some other matrix version tests which could run outside of the main PR validations for the specific list of versions to be tested. Therefore a module would be evaluated, as usual, with a default version and also with a list of versions without affecting the PR build/test times. 

## Outcomes
- Easy to configure what versions are defaulted for each module and what version matrix will be tested for each module.
- Easy to test locally
- Create a Jenkins pipeline to test this particular matrix of versions initially triggered by a timer for the main branches. 

## Future actions
- Extend the test coverage per PR with the above list of versions per module if possible.
- Cutting edge; far in the future, we could even test each module with its nightly version a kind of cutting edge validation which might help to proactively detect any compatibility issues upfront. But as I said, that's something far in the future and also required to discuss with the team members.

**Comment by exekias** [comment]
cc @elastic/infrastructure

**Comment by alvarolobato** [comment]
Superseded by https://github.com/elastic/observability-dev/issues/187
