### ISSUE TITLE
Support packet recognition within VxLAN

### ISSUE THREAD

**Issue by marco-gulino** [elastic/beats#1283]
Hi, it would be nice if packetbeat could recognize packets sent inside a VxLan (used in docker overlay networks over swarm cluster).
An example of the vxlan packets reconstruction is here:
http://www.lovemytool.com/blog/2011/11/analyzing-vxlan-packets-using-wireshark-by-srivats-p.html

Thanks
Marco

**Comment by zsandrus** [comment]
Adding another use case for this. Azure Virtual network TAP sends mirrored traffic to packet analysis VMs using VXLAN. Being able to process the VXLAN encoded packets would be a requirement for packetbeat to be compatible with Azure vTAP:
https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-tap-overview

**Comment by stourmarine** [comment]
Hello,
We're looking for this feature (to decode VXLAN traffic). We have an ES cluster in AWS and traffic mirrored comes encapsulated in VXLAN packets.

Best Regards,
Mihai R.

**Comment by stourmarine** [comment]
If anyone experience the same issue, this is a good workaround:
https://manpages.ubuntu.com/manpages/bionic/man4/if_vxlan.4freebsd.html

**Comment by p-8-z** [comment]
> If anyone experience the same issue, this is a good workaround: https://manpages.ubuntu.com/manpages/bionic/man4/if_vxlan.4freebsd.html

Can you please elaborate how did you make it work using vxlan — Virtual eXtensible LAN interface
Thanks

**Comment by stourmarine** [comment]
Hello,

Run a tcpdump and find the vxlan id. Then run this:
ip link add vxlan0 type vxlan id xxxxxx dev ens6 local 10.x.x.x dstport 4789
ip link set vxlan0 up

PS. Filters on packetbeat won't work, but that was fine for me because we have made the proper filters in Kibana Visualisations

BR.
