### ISSUE TITLE
Include SSL configuration to enroll Beats with central management

### ISSUE THREAD

**Issue by romain-chanu** [elastic/beats#12863]
**Describe the enhancement:** The [current documentation](https://www.elastic.co/guide/en/beats/filebeat/current/enroll-beats.html ) about how to enroll beats with central management should include information on how to enroll beats when Kibana is configured with TLS/SSL.

**Describe a specific use case for the enhancement or feature:** As a user, I want to enroll beats with the central management. Both my Elasticsearch and Kibana are configured with TLS/SSL. The above documentation does not explain how to enroll beats with central management when TLS/SSL is used. As a result, I am unable to enroll beats with the central management.

### My experimentation/findings

I looked at the beats code (version 7.2) and **I found two different ways** to enroll beats with central management when Kibana is configured with TLS/SSL. **Unfortunately, these are undocumented** but I hope this will be helpful for any user who encounters the same problems. 

As example, I will use:
- Filebeat 7.2, Kibana 7.2, Elasticsearch 7.2
- the username/password-based enrollment, but I would believe the same apply to the token-based enrollment.

### What if I just follow the current documentation, what will happen?

The enrollment will fail (as expected). For reference this is what happens when running the enrollment command:

```bash
filebeat -e -v -d "*" enroll https://kibana_url:5601 --username myuser --password stdin
<some debug logs>
This will replace your current settings. Do you want to continue? [Y/n]:Y
Enter password: 
<some debug logs>
Error creating a new enrollment token: fail to execute the HTTP POST request: Post https://kibana_url:5601/api/beats/enrollment_tokens: x509: certificate signed by unknown authority
```

These are the two different methods to enroll beats with central management when TLS/SSL is used.

### Method 1: filebeat command flag (-E)

The flag `-E` allows Filebeat to overwrite a particular setting with the one specified in the command line. In this case, I will use the `management.kibana.ssl.certificate_authorities` (**which is not documented, hence the current issue**). This is the list of root certificates for server verifications. If certificate_authorities is empty or not set, the trusted certificate authorities of the host system are used (c.f [SSL settings](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html#_configuration_options_16)). Note that the value is an array of files paths, delimited by comma.

Example:

```bash
filebeat -e -v -d "*" enroll https://kibana_url:5601 --username myuser --password stdin -E "management.kibana.ssl.certificate_authorities=[ca_certificate_file_path]"
<some debug logs>
This will replace your current settings. Do you want to continue? [Y/n]:Y
Enter password: 
<some debug logs>
Saving a copy of current settings to filebeat.yml.YYYY-MM-DDTHH:MM:SS+TZHH:TZMM.bak
Enrolled and ready to retrieve settings from Kibana
```

**Note 1:** the `ssl.certificate_authorities` is used as part of `management.kibana` and not `setup.kibana`. It kinda makes sense since I am trying to enroll the beat with central **management**. But...**this is currently not documented**

**Note 2**: as the documentation mentioned, I could install the CA certificates in the machine (in the certificate store) where I run the beat. If I do so, it is not required to specify `management.kibana.ssl.certificate_authorities`. The enrollment will be successful too.

### Method 2: Filebeat configuration file (filebeat.yml)

The other method is to use the Filebeat configuration file. `management.kibana.ssl.certificate_authorities` can also be added in the `filebeat.yml` file. Depending on your client (e.g Filebeat) / server (e.g Kibana) settings, you may want to add other [SSL settings](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html#_configuration_options_16) in  `management.kibana`. There is a [GitHub beats enhancement issue](https://github.com/elastic/beats/issues/12641) that can give you some additional information (which are currently not in the existing SSL settings documentation).

These are the steps I performed:

1) Add the required settings in `filebeat.yml`:

```yml
management.kibana:
  ssl.certificate_authorities: ["ca_certificate_file_path"]
```

**Note:** For beats enrollment, remember to add the SSL settings under `management.kibana` and not `setup.kibana`

2) Run the enrollment command

```bash
filebeat -e -v -d "*" enroll https://kibana_url:5601 --username myuser --password stdin
<some debug logs>
This will replace your current settings. Do you want to continue? [Y/n]:Y
Enter password: 
<some debug logs>
Saving a copy of current settings to filebeat.yml.YYYY-MM-DDTHH:MM:SS+TZHH:TZMM.bak
Enrolled and ready to retrieve settings from Kibana
```

### Troubleshooting

These are the errors I faced while exploring/testing:

1) In the client machine, adding the `-e -v -d "*"` filebeat command flags can be helpful for debugging.

2) When running the beat enrollment command, adding a "/" after the port number in the Kibana URL (eg. https://kibana_url:5601/) will result in the beat enrollment failure. An error is logged: `Error creating a new enrollment token: error while parsing Kibana response: json: cannot unmarshal string into Go struct field BaseResponse.error of type api.ErrorResponse`

3) Incorrect credentials (e.g incorrect password) will result in the beat enrollment failure. An error is logged: `Error creating a new enrollment token: error while parsing Kibana response: json: cannot unmarshal string into Go struct field BaseResponse.error of type api.ErrorResponse`. The authentication failure will also be logged in the Kibana logs (that can be helpful to determine the failure).

4) For issues related to certificates, using openssl command (e.g. to test a connection from the client to the server using the certificate) could be of a good help.

5) There could be some beat enrollment issues when using Filebeat 7.2.0 and Kibana <= 7.1.1. I do not think there is any documentation related to Filebeat vs Kibana versions. A good practice would be to keep all components to the same versions?

**Comment by coute** [comment]
Thanks for the tip about `management.kibana`
This issue report was the only way to find how to solve SSL/TLS issue with Central Beat Management.
More documentation about this feature will be appreciate.

**Comment by coute** [comment]
Will be updated with the new system using agent.

**Comment by Nips-ZA** [comment]
Thanks for this. It helped. I also found I was able to add   `ssl.verification_mode: none` under management.kibana on a server that wasn't happy with the elastic cert util self signed cert.
