### ISSUE TITLE
Add more helpful logs for beats enrollment with central management

### ISSUE THREAD

**Issue by romain-chanu** [elastic/beats#12865]
**Describe the enhancement:** The messages logged by a beat (e.g filebeat 7.2.0) are not really useful for troubleshooting issues with the beats enrollment. Ideally, the logs messages should be helpful and more intuitive.

**Describe a specific use case for the enhancement or feature:**

Examples are extracted from this [GH enhancement issue](https://github.com/elastic/beats/issues/12863). 

### Example 1

Running the enroll command (when Kibana uses TLS/SSL) without configuring filebeat to use the CA certificate:

```bash
filebeat -e -v -d "*" enroll https://kibana_url:5601 --username myuser --password stdin
<some debug logs>
This will replace your current settings. Do you want to continue? [Y/n]:Y
Enter password: 
<some debug logs>
Error creating a new enrollment token: fail to execute the HTTP POST request: Post https://kibana_url:5601/api/beats/enrollment_tokens: x509: certificate signed by unknown authority
```

The error message is confusing. CA certificate configuration is missing in this example but the error message refers to a `certificate signed by unknown authority`.

### Example 2

When running the beat enrollment command, adding a "/" after the port number in the Kibana URL (eg. https://kibana_url:5601/) will result in the beat enrollment failure. An error is logged: `Error creating a new enrollment token: error while parsing Kibana response: json: cannot unmarshal string into Go struct field BaseResponse.error of type api.ErrorResponse`

The error message is cryptic. It is unrelated to the "incorrect" Kibana URL.

### Example 3:

Incorrect credentials (e.g incorrect password) will result in the beat enrollment failure. An error is logged: `Error creating a new enrollment token: error while parsing Kibana response: json: cannot unmarshal string into Go struct field BaseResponse.error of type api.ErrorResponse.`

The error message is also cryptic. It is unrelated to the authentication failure. Take note that the authentication failure is logged in the Kibana logs.

### Others scenarios

I have not tested these but I can think of a few other scenarios:
- Kibana is unreachable.
- Roles/permissions issues when using `myuser` in the command line.
- Certificates issues (expired certificate, unsupported format, etc.).
- Incorrect settings in the command line (incorrect files paths, unknown settings, etc.).
- Incorrect settings in the filebeat.yml file (incorrect files paths, unknown settings, etc.).

**Comment by flowl** [comment]
Still having a hard time figuring out the error messages.
Also noticed the verbose `-v` flag is not doing anything:

```
[root@a3c654a61aa5 filebeat]# filebeat enroll http://kibana:5601 <token> --force
Error while enrolling: empty access_token

[root@a3c654a61aa5 filebeat]# filebeat enroll http://kibana:5601 <token> --force -v
Error while enrolling: empty access_token
```
