### ISSUE TITLE
Metricbeat Elasticsearch module: Collect JVM heap_memory values

### ISSUE THREAD

**Issue by rschirin** [elastic/beats#12884]
Description:

Using Elasticsearch module, currently, we cannot get the values of heap_memory_used. It should be very important to get it if we have to collect values to monitor Elasticsearch instance.

Specific use:

Trying to monitoring Elasticsearch instance, I'm creating also a dashboard in Kibana (but you can create it whenever you want). Without this type of values, I cannot known how JVM is acting.

**Comment by cdalexndr** [comment]
I guess you could use APM agent to monitor elasticsearch java machine

**Comment by cdalexndr** [comment]
Metricbeat's elasticsearch module has `node_stats` metricset with jvm memory spaces:
https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-elasticsearch.html#_node_stats
