### ISSUE TITLE
ELB Filebeat Module

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#12893]
The goal of this issue is to create a filebeat module for AWS Elastic Local Balancer access logs which leverages the S3 filebeat input (https://github.com/elastic/beats/issues/12582)

## Filebeat module

* [ ] Test log files exist for the grok patterns
* [ ] Generated output for at least 1 log file exists

**Comment by panpanpandas** [comment]
Is there any timeline for this?

**Comment by kaiyan-sheng** [comment]
@panpanpandas Currently we have a PR up for adding S3 access log in Filebeat, this will be next. Thanks!
