### ISSUE TITLE
Heartbeat autodiscover should support Netflix Eureka

### ISSUE THREAD

**Issue by gmarziou** [elastic/beats#12919]
**Describe the enhancement:**

Heartbeat autodiscover should support Netflix Eureka service discovery or at least provide a plugin mechanism so that we can provide our own implementation.

**Describe a specific use case for the enhancement or feature:**

Microservice services architectures based on Spring Cloud Netflix Eureka could be monitored in Heartbeat.

**Comment by andrewvc** [comment]
Thanks for the idea! Would you be interested in providing a patch to support this? You could take a look at #12401 for an example

**Comment by gmarziou** [comment]
When I look at the number of commits in #12401 it just makes me think I cannot afford such effort.
