### ISSUE TITLE
[filebeat] Allow wildcards for drop_fields

### ISSUE THREAD

**Issue by fhemberger** [elastic/beats#12923]
**Describe the enhancement:**
`drop_fields.fields` should support glob or regex patterns. 

**Describe a specific use case for the enhancement or feature:**
I'm using the `add_docker_metadata` processor to extract container metadata, which also includes Docker labels. For some containers, there are quite a lot that don't contain relevant information for logging purposes. For example, the official `elasticsearch` image includes:

- "container.labels.license"
- "container.labels.org_label-schema_build-date"
- "container.labels.org_label-schema_license"
- "container.labels.org_label-schema_name"
- "container.labels.org_label-schema_schema-version"
- "container.labels.org_label-schema_url"
- "container.labels.org_label-schema_vcs-url"
- "container.labels.org_label-schema_vendor"
- "container.labels.org_label-schema_version"

Also many labels coming from `docker-compose` are not really needed and can be dropped as well. So you quickly end up with quite a list of labels, all starting with the same prefix.

(The exact same labels are also repeated as `docker.container.…`, but that's a different issue).

So instead of having to list all those labels under `drop_fields`, it would be nice to just write:

- "container.labels.license"
- "container.labels.org_label-schema*"

**Comment by querry43** [comment]
I wouldn't mind this functionality.  My use case is slightly different.  I would drop `foo.*.baz` which would remove `foo.bar.baz` but not `foo.bar.blarg`.

**Comment by henriqueyun** [comment]
I need this too

**Comment by orest-gulman** [comment]
I would be useful if it will be possible to use at list wildcard in processors:
`  processors:
    - drop_event.when.not.equals:
        windows.service.display_name: "myApplication*"`

**Comment by jzako** [comment]
+1

**Comment by fnunez306** [comment]
+1

**Comment by ijardillier** [comment]
+1

**Comment by kudodenko** [comment]
+1

**Comment by pantovad** [comment]
+1

**Comment by smnschneider** [comment]
+1
