### ISSUE TITLE
Metricbeat dashboards are broken

### ISSUE THREAD

**Issue by garaboncias** [elastic/beats#12924]
For confirmed bugs, please report:
- Version: 7.2
- Operating System: Debian
- Discuss Forum URL: https://discuss.elastic.co/t/errors-in-kibana-with-metricbeat-6-7-1/186301/4
- Steps to Reproduce: 
As i add dashboards to kibana with "sudo metricbeat setup --dasboards" (Metricbeat 7.2 on debian) its appears but most of them broken. Example: Metricbeat-system-overview
<img width="1440" alt="Screenshot 2019-07-15 at 11 27 09" src="https://user-images.githubusercontent.com/2393180/61284136-aa0b4180-a7be-11e9-86a0-3e77733ce4d0.png">
<img width="401" alt="Screenshot 2019-07-15 at 11 27 30" src="https://user-images.githubusercontent.com/2393180/61284138-aaa3d800-a7be-11e9-958e-36ec850ac913.png">

as I see field is empty in the query
when I check it in, query is missing and also no "savedSearchId":
/usr/share/metricbeat/kibana/7/dashboard/Metricbeat-system-overview.json

{
"attributes": {
"description": "",.
"kibanaSavedObjectMeta": {
"searchSourceJSON": "{"filter": , "index": "metricbeat-*", "query": {"query": "", "language":
},.
"title": "Number of hosts [Metricbeat System] ECS",.
"uiStateJSON": "{"vis": {"defaultColors": {"0 - 100": "rgb(0,104,55)"}}}",.
"version": 1,.
"visState": "{"type": "metric", "params": {"gauge": {"useRange": false, "gaugeType": "Metric", "sty
},.
"id": "c6f2ffd0-4d17-11e7-a196-69b9a7a020a9-ecs",.
"type": "visualization",.
"version": 2
}

**Comment by kaiyan-sheng** [comment]
Hello @garaboncias ,I see that you already posted on discuss forum. Let's discuss there first. If it's a confirmed bug, then please feel free to reopen this issue or create a new github issue for it. Sorry for the inconvenience!
