### ISSUE TITLE
[Meta] [SIEM] Document ECS mappings

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#12944]
Modules docs should describe the mapping from vendor-specific fields to ECS, similar to [what the PANW module does](https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-module-panw.html#_ecs_field_mappings).

- [ ] Cisco ASA
- [ ] Cisco IOS
- [ ] CoreDNS
- [ ] Envoy Proxy
- [ ] Iptables / Ubiquiti
- [ ] Suricata EVE
- [ ] Zeek

**Comment by mtojek** [comment]
I assume it's stale, resolving.
