### ISSUE TITLE
[Auditbeat] Add support for --loginuid-immutable flag

### ISSUE THREAD

**Issue by dmlary** [elastic/beats#12953]
**Describe the enhancement:**
Similar to  #8352, support for the `--loginuid-immutable` flag in audit rules needs to be added to the `auditd` module.  Issue elastic/go-libaudit#56 exists to add the needed underlying support in go-libaudit to support this enhancement.

**Describe a specific use case for the enhancement or feature:**
Currently, auditbeat fails to load any ruleset that includes the `--loginuid-immutable` flag.  This flag, when set to 1, prevents root from changing their audit uid after it has been set.

**Comment by dmlary** [comment]
Not stale.  Still a needed feature.  Please fix.

**Comment by jamiehynds** [comment]
Closing this issue as we've just added support for immutability: https://github.com/elastic/integrations/pull/3760

**Comment by andrewkroh** [comment]
This is different from the `-e 2` kernel audit rule immutability.
