### ISSUE TITLE
Metricbeat - Prometheus Module - Add optional URL Parameters

### ISSUE THREAD

**Issue by forestodencgi** [elastic/beats#12954]
**Add Parameters option to Metricbeat Prometheus Module:**

Prometheus scrape config allows for parameters to be added to the URL. Metricbeat should be able to do the same. I tried to simply pass the parameter into the metrics path, but that is not working.

**Describe a specific use case for the enhancement or feature:**

I am trying to collect metrics from HashiCorp Vault via their Prometheus exporter. This exposes metrics at `/v1/sys/metrics` but by default in JSON output. Prometheus output is at the path `/v1/sys/metrics?format=prometheus`. Setting the `metrics_path` to that URL results in a 404, but I am able to curl the URL directly.

Vault's documentation has the following note:

>Vault does not use the default Prometheus path, so Prometheus must be configured as follows. Note that using ?format=prometheus in the path won't work as "?" will be escaped, so it must be specified as a parameter. 

I believe adding an optional `params`  configuration option to the Prometheus module should resolve this, but I am open to other suggestions to resolve this.

For reference this is how the `params` option looks in Prometheus' config:

```
# Optional HTTP URL parameters.
params:
  [ <string>: [<string>, ...] ]
```

**Comment by jsoriano** [comment]
Hi @forestodencgi,

Thanks for filling this request. I think this should be already supported using the generic [`query` HTTP option](https://www.elastic.co/guide/en/beats/metricbeat/7.2/configuration-metricbeat.html#_literal_query_literal). You can find [an example](https://www.elastic.co/guide/en/beats/metricbeat/7.2/metricbeat-metricset-prometheus-collector.html#_scraping_all_metrics_from_a_prometheus_server) in the prometheus collector documentation.

For this case the config would be something like this (not tested):
```
- module: prometheus
  hosts: ["localhost:9090"]
  metrics_path: '/v1/sys/metrics'
  query:
    format: prometheus
```

I am closing this as I think this should already work, please reopen if it is not working as I agree that this should be supported.

**Comment by forestodencgi** [comment]
That worked! Didn't realize `query` worked like that. I'm not familiar with the `/federate` API, so I had glossed over that section.

Thank you!
