### ISSUE TITLE
Custom Indexname support with ILM

### ISSUE THREAD

**Issue by dsengar121** [elastic/beats#12977]
**Describe the enhancement:**
Need ability to specify index name with iLM enabled in winlogbeat and Metricbeat. As of now if we enable iLm, the index name setting is ignored and data is indexed in <beatname>-<version>-<rollover pattern> index.
**Describe a specific use case for the enhancement or feature:**

We have a multi-tenant environment and want to keep logs and metric data separate for each client. The current index naming convention is <beatname>-<clientname>-<yyyy.MM>

**Comment by jsoriano** [comment]
Hi @dsengar121,

You can do something similar with the [`setup.ilm.rollover_alias` option](https://www.elastic.co/guide/en/beats/metricbeat/7.2/ilm.html).
I am closing this as I think that it is already possible to customize index name with ILM, but with a different set of settings.
