### ISSUE TITLE
[FunctionBeat] Concatenate multiline logs

### ISSUE THREAD

**Issue by Bajena** [elastic/beats#12981]
Hey, I recently discovered functionbeat and so far it does really great job!

**Describe the enhancement:**
It'd be great to have `multiline` config option, similar to what FileBeat has (https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html).

**Describe a specific use case for the enhancement or feature:**
My use case is very similar to the one mentioned in FileBeat docs:
```
The logs harvested by FunctionBeat may contain messages that span multiple lines of text. 
For example, multiline messages are common in lambdas containing Ruby stack traces
```

**Comment by acchen97** [comment]
@ph does Functionbeat support multiline today?

**Comment by ph** [comment]
@Bajena it doesn't support it at the moment, but can you give us a bit more information about your use case? What trigger you are using that would require multiline?

cc @kvch
