### ISSUE TITLE
Consul docs not showing the supported metricsets

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#13007]
The documentation page for Consul module doesn't show the supported metricsets:
<img width="795" alt="Screen Shot 2019-07-22 at 14 59 35" src="https://user-images.githubusercontent.com/1685068/61634335-65d1e280-ac91-11e9-8bce-75072984f9d3.png">

needs an additional `[float]` tag.

**Comment by sayden** [comment]
Fixed here https://github.com/elastic/beats/pull/13660 thanks to @dedemorton :slightly_smiling_face:
