### ISSUE TITLE
Multiple instances of wineventlog in goroutines raise errors randomly.

### ISSUE THREAD

**Issue by adamiklukasz** [elastic/beats#13005]
When running multiple eventlog instances in >25% of execution errors occurs:

`Error New(): 2 errors: Invalid event log key 'api' found. Valid keys are batch_read_size, event_id, fields, fields, fields_under_root, forwarded, ignore_older, include_xml, level, name, processors, processors, provider, tags; Invalid event log key 'no_more_events' found. Valid keys are batch_read_size, event_id, fields, fields, fields_under_root, forwarded, ignore_older, include_xml, level, name, processors, processors, provider, tags`

`Error New(): 2 errors: Invalid event log key 'api' found. Valid keys are batch_read_size, event_id, fields, fields, fields_under_root, forwarded, ignore_older, include_xml, level, name, processors, processors, provider, tags; Invalid event log key 'no_more_events' found. Valid keys are batch_read_size, event_id, fields, fields, fields_under_root, forwarded, ignore_older, include_xml, level, name, processors, processors, provider, tags`

Error randomly refer to different valid field, ie. `Invalid event log key 'name' found.`, `Invalid event log key 'no_more_events' found` etc.

Looks like issue doesn't occur when running eventlog one after another (single go-routine) or when running with random sleep at the beginning for each goroutine.

- Version: v7.2.0
- Operating System: Windows 10 Enterprise (1903, build 18362.145)

Code:
```
    package main

    import (
        "fmt"
        "github.com/elastic/beats/libbeat/common"
        "github.com/elastic/beats/winlogbeat/checkpoint"
        "github.com/elastic/beats/winlogbeat/eventlog"
        "time"
    )

    func main() {
        channels := []string{"System", "Application", "Setup"}

        for _, ch := range channels {
            go func() {
                cfg, _ := common.NewConfigFrom(common.MapStr{
                    "name":            ch,
                    "api":             "wineventlog",
                    "no_more_events":  "wait",
                    "batch_read_size": 100,
                })

                st := checkpoint.EventLogState{}

                el, err := eventlog.New(cfg)
                if err != nil {
                    fmt.Printf("Error New(): %v\n", err)
                    return
                }

                err = el.Open(st)
                if err != nil {
                    fmt.Printf("Error Open(): %v\n", err)
                    return
                }

                for {
                    rec, _ := el.Read()
                    for _, r := range rec {
                        fmt.Printf("r=%#v\n", r)
                    }
                }
            }()
        }

        time.Sleep(10 * time.Second)

    }
```

**Comment by andrewkroh** [comment]
I have opened #13048 to fix the issue.

**Comment by andrewkroh** [comment]
Thanks for including the code sample. This made it every easy to reproduce. BTW this example code has its own data race. It's affected by https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables.
