### ISSUE TITLE
freebsd support

### ISSUE THREAD

**Issue by BitSums** [elastic/beats#13019]
Hello.
I see that there is no progress on this issue.

Official support freebsd will be?

p.s. Maybe someone already worked on it. Are there any results?

**Comment by jakommo** [comment]
There are no official FreeBSD packages yet, you can follow https://github.com/elastic/beats/issues/1034 for that, but there are FreeBSD packages available in ports/pkg (a bit outdated though), see https://www.freshports.org/sysutils/beats

**Comment by jsoriano** [comment]
Closing it as comment answers the question, and it can be considered a duplicated of #1034.
