### ISSUE TITLE
"error" ECS key in event is detected as test error by system tests

### ISSUE THREAD

**Issue by sayden** [elastic/beats#13052]
When running filebeat if you have a field which contains a succesfully captured error, tests will always fail because an `error` key is detected and triggers the "fail" state... but ECS allows an `error` key: https://www.elastic.co/guide/en/ecs/current/ecs-error.html

Assertion line is this: https://github.com/elastic/beats/blob/master/filebeat/tests/system/test_modules.py#L165

An example event, from postgres 11:

```json
{
        "@timestamp": "2019-07-23T12:09:57.565Z",
        "event.dataset": "postgresql.log",
        "event.module": "postgresql",
        "event.timezone": "UTC",
        "fileset.name": "log",
        "input.type": "log",
        "log.level": "LOG",
        "log.offset": 2193,
        "message": ": duration: 2.139 ms",
        "error.code": "00000",
        "process.pid": 44,
        "service.type": "postgresql"
    }
```

**Comment by jsoriano** [comment]
As commented offline, I think we could remove this check, `error` is a valid field to contain errors from events according to ECS (as well as to contain errors happened while fetching). We would still be checking for unexpected errors when comparing with the expected json files.

**Comment by sayden** [comment]
A couple of comments more from Slack:

* @adriansr commented to _change the check to look for "error.message"_ which I confirm that will work
* @kaiyan-sheng commented: _Can we modify the test to check if the error is expected?_

**Comment by sayden** [comment]
> As commented offline, I think we could remove this check, `error` is a valid field to contain errors from events according to ECS (as well as to contain errors happened while fetching). We would still be checking for unexpected errors when comparing with the expected json files.

Can you develop the downsides of this approach? I can only think that when using `GENERATE=1` we'll never have errors but they will be there, on the generated json. Which may be obscure in my opinion. Maybe I'm wrong about this behavior

**Comment by jsoriano** [comment]
Yes, it can hide errors if we don't review carefully the generated expected jsons.
Regarding the other options, checking for `error.message` will work... till we have a log file that contains an error message that we want to capture. This is probably the best option by now so you can continue with #13053.
Kaiyan's proposal is probably the best one, but also requires more effort, there is already an open issue to support something like this: https://github.com/elastic/beats/issues/10182

**Comment by adriansr** [comment]
I didn't realise that this is used only when checking against generated events. Then it will be cleaner to remove the check as @jsoriano suggests. How difficult is it to have modules report when errors are expected?

**Comment by exekias** [comment]
let's try to move this forward, @sayden WDYT about doing what @jsoriano suggests (remove the check for now) and keep the conversation going here to see if we can find another solution for the long term?

**Comment by sayden** [comment]
@exekias I think it's better to take baby steps with this issue and to not omit the error check that all developers use now. I think it's best to develop the least intrusive approach that doesn't change the _flow_ of how a Filebeat is developed right now. Specially when we have so many people on holidays now that might miss this important change. This is specially critical when you have an input file with 20 or more lines where you'll have to carefully look between all events to see which one is wrong.

Omit the error will introduce one slow step more into development (first `GENERATE` then run test again to check if output is exactly the same)

So I propose to just check `error.message` which is the least intrusive and we don't have that field in ECS.

**Comment by jsoriano** [comment]
> So I propose to just check `error.message` which is the least intrusive and we don't have that field in ECS.

I am ok with doing that to unblock https://github.com/elastic/beats/pull/13053, but take into account that [`error.message` is in ECS](https://www.elastic.co/guide/en/ecs/1.0/ecs-error.html) the same as `error.code`, and could be a legit event field in the future.

Another compromise option to unblock #13053 could be to store this error code in `postgresql.error.code` till we have a clear solution.

I was checking now and we also have the fields `haproxy.error_message`, `mysql.error.message`, `nats.log.msg.error.message`, `nginx.error.message`... all of them could go to `error.message` according to the definition in ECS.

We also have the `apache.error` metricset writing the error message directly in the `message` field, but I think that it could also very well be in `error.message`.

On the other hand it is true that we use to use `error.message` only for errors in event parsing, but for the same reason we could decide to do the same with all `error.*` fields for consistency. In that case this error code should go to `postgresql.error.code`.

**Comment by exekias** [comment]
Something we could do here is removing the check, but dump events with `error.*` to a different file `result.expected-error` instead of `result.expected`. This way it's more obvious that there was an error that could be intended. It will also be less likely that we miss that during a review
