### ISSUE TITLE
ILM policy being over written after every beats install

### ISSUE THREAD

**Issue by syedsfayaz** [elastic/beats#13050]
Beats overwriting the ILM policy for every install. 

ELK 7.2
https://discuss.elastic.co/t/ilm-settings-not-working/190060

Version: 7.2
Operating System: RedHat
Discuss Forum URL:  https://discuss.elastic.co/t/ilm-settings-not-working/190060

**Comment by syedsfayaz** [comment]
Can some one help me with this issue.  It still happens in Version: 7.3.2

**Comment by fpompermaier** [comment]
I also think that there's a bug in beats with ILM setup: when you specify the **setup.ilm.policy_name** but you don't configure **setup.ilm.policy_file** the default lifecycle policy will override the specified policy (if it exists). 

I think you should be able to configure a policy name to associate to the index template and, on setup --index-management., you should be able to not override the existing ILM policy
