### ISSUE TITLE
Automatically enable `add_docker_metadata` or `add_kubernetes_metadata`

### ISSUE THREAD

**Issue by exekias** [elastic/beats#13068]
We configure `add_cloud_metadata` and `add_host_metadata` by default in all Beats.

`add_cloud_metadata` does autodetection, and it will only enrich events if the beat is running on a known public cloud.

It would be interesting to find a way to do the same for docker and kubernetes, so if Beats is started in a scenario where Docker is available, it automatically enables metadata for it. If Docker is not present nothing will happen.

**Comment by ChrsMark** [comment]
Related PRs:
https://github.com/elastic/beats/pull/13374

**Comment by ChrsMark** [comment]
Should we close this now that features and docs are completed?

**Comment by exekias** [comment]
Thank you for tackling this!
