### ISSUE TITLE
[Auditbeat] Operation not permitted - Failed to create process table

### ISSUE THREAD

**Issue by SMBx00** [elastic/beats#13076]
Getting this error on a 14.04 box and cannot figure it out - its running as root, auditd is not running on the system, and verified config works, and connection tests all check out.

>  NAME="Ubuntu"
> VERSION="14.04.2 LTS, Trusty Tahr"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 14.04.2 LTS"
> VERSION_ID="14.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

```
ERROR   instance/beat.go:877    Exiting: 1 error: 1 error: failed to create process table: could not read /proc: stat /proc: operation not permitted
Exiting: 1 error: 1 error: failed to create process table: could not read /proc: stat /proc: operation not permitted
```

Could not find post with an issue specific to not reading /proc - Any help would be appreciated, i have this working on Ubuntu 16 and 18 boxes with no issue.

Regards
S

**Comment by andrewkroh** [comment]
Please provide the output of `auditbeat version`.

**Comment by SMBx00** [comment]
> auditbeat version 7.2.0 (386), libbeat 7.2.0

**Comment by andrewkroh** [comment]
We think we have this fixed already, but it hasn't been released yet https://github.com/elastic/beats/issues/12990. You could try one of our snapshot builds to test if the issue has been fixed https://storage.googleapis.com/beats-ci-artifacts/snapshots/auditbeat/auditbeat-8.0.0-SNAPSHOT-i386.deb.

Or you can workaround the issue with your current version by setting this in your configuration file.

```
seccomp:
  default_action: allow 
  syscalls:
  - action: errno 
    names: 
    - execve
    - execveat
    - fork
    - vfork
```

**Comment by SMBx00** [comment]
I couldnt get it to work with the workaround, just spit out two lines with no other indications or why it wouldnt start:
```
2019-07-25T15:39:49.829-0400    INFO    instance/beat.go:606    Home path: [/usr/share/auditbeat] Config path: [/etc/auditbeat] Data path: [/var/lib/auditbeat] Logs path: [/var/log/auditbeat]

2019-07-25T15:39:49.829-0400    INFO    instance/beat.go:614    Beat ID: ce312ff6-4709-48dc-b935-2c61d7413f3c
```

However the snapshot you provided (8.0) did do the trick and it is up and running, I am in a testing environment atm with this server so this is perfect for what I need. I appreciate the quick response!

Regards,
S
