### ISSUE TITLE
[Filebeat] Show a clear and simple example of how to parse JSON logs

### ISSUE THREAD

**Issue by roncohen** [elastic/beats#13093]
JSON logs is a very common use case. We need to have a very clear and straight forward example in the docs that shows how to set up filebeat to parse JSON. Maybe even a note in the getting started with Filebeat docs or a separate "Getting start with JSON" page. 

The docs today describe three configuration options, but do not show a full example: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#filebeat-input-log-config-json

We have a blost post from 2016 that seems very popular, but it's difficult to find and really should be part of the documentation: https://www.elastic.co/blog/structured-logging-filebeat

cc @dedemorton @urso.

**Comment by antegulin** [comment]
+1

**Comment by hkirsman** [comment]
+1

**Comment by roycrxtw** [comment]
+1

**Comment by Wang-Kai** [comment]
+1

**Comment by MarcOverIP** [comment]
+1 Would really appreciate this. Just spent way too much time with a basic setup. Couldn't get filebeat to parse it as json. Now have Logstash do all the json parsing. Feels counter intuitive and is not in line with the elastic blog. But it's the only way to make it do something. A detailed blog with several use cases would surely help!

**Comment by atkinson** [comment]
The 2016 blog post looks out of date?

**Comment by belimawr** [comment]
Thanks for the input and interest folks, I'll look into this. A blog post is a very good idea for a detailed walk through.

**Comment by mukeshelastic** [comment]
@belimawr my recommendation is to include it in public docs, potentially as getting started guide with parsing json logs with elastic, or something on those lines.

**Comment by belimawr** [comment]
Thanks @mukeshelastic ! I have some material prepared in the form of a blog post, now I just need to find time to review it and get it published somewhere.
