### ISSUE TITLE
[Docs] Should "Upgrade from 6.x to 7.x" ask to upgrade to 6.7 or 6.8? 

### ISSUE THREAD

**Issue by kiju98** [elastic/beats#13101]
"Upgrade from 6.x to 7.x" (https://www.elastic.co/guide/en/beats/libbeat/current/upgrading-6-to-7.html#upgrading-6-to-7, https://www.elastic.co/guide/en/beats/libbeat/7.3/upgrading-6-to-7.html#upgrading-6-to-7, and https://www.elastic.co/guide/en/beats/libbeat/7.x/upgrading-6-to-7.html#upgrading-6-to-7) asks to upgrade Beats to 6.7 before upgrading to 7.0.
The latest 6.x release is 6.8. Should it be changed to ask to upgrade to 6.8?

**Comment by dedemorton** [comment]
closing because this will be fixed when https://github.com/elastic/beats/pull/13141 is merged.
