### ISSUE TITLE
[Metricbeat] HTTP Module - XML metricset

### ISSUE THREAD

**Issue by tazbert** [elastic/beats#13107]
Add XML metricset to Metricbeat HTTP Module

Basically, a clone of the JSON metricset, but with the ability to parse XML.

There was a quick discussion a while back (https://discuss.elastic.co/t/ingest-xml-from-http/122955) and @ruflin suggested a feature request be created. I don't see one created from that discussion, so here it is.

**Comment by DahlPatric** [comment]
Is someone working on this request or have it been put in trash bin?
It would be very much appreciated if it could be developed.
