### ISSUE TITLE
Some module docs are missing the x-pack role

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#13112]
The Metricbeat module docs that are under xpack do not include the xpack label, but should. To add the label, we need to include `[role="xpack"]` before each section that will be a unique html topic.

This is going to require some logic in the doc collector script and templates used to generate the docs. Basically, we need to check to see if the module is under the x-pack directory, and if it is, add the following role:

[role="xpack"]

The role needs to be added to the line before the section titles here:

https://github.com/elastic/beats/blob/master/metricbeat/scripts/mage/template/metricsetDoc.tmpl#L6

https://github.com/elastic/beats/blob/master/metricbeat/scripts/mage/template/moduleDoc.tmpl#L6

@Titch990 @fearful-symmetry

**Comment by exekias** [comment]
cc @andresrc

**Comment by fearful-symmetry** [comment]
It looks like there's still some debate about how we should label these at all, but for now I can at least get started on something to add in `x-pack`.

**Comment by dedemorton** [comment]
Adding the role is the right way to go. If we decide to change the way we flag licensed content, we'll do it on the publishing side, I suspect.

**Comment by fearful-symmetry** [comment]
This was fixed in https://github.com/elastic/beats/pull/13271 , and should be in 7.4
