### ISSUE TITLE
[Filebeat] Cleanup channelContext and s3Context in s3 input

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#13129]
After common patterns are collected in [github.com/elastic/go-concert](https://github.com/elastic/go-concert), both `channelContext` and `s3Context` can be removed and replaced by the common pattern. This issue is to track the work mentioned in https://github.com/elastic/beats/pull/12640#discussion_r308959061 by @urso .

**Comment by urso** [comment]
In progress PR: https://github.com/elastic/beats/pull/19756

**Comment by jsoriano** [comment]
I guess this was solved in https://github.com/elastic/beats/pull/20005, so I am closing this. @kaiyan-sheng, please reopen if you think that this is still an issue.
