### ISSUE TITLE
Add configuration option for field name

### ISSUE THREAD

**Issue by iuuuuan** [elastic/beats#13139]
Beats 7.x are using field name agent.* instead of beat.*.

Field name agent is already used in logstash grok pattern COMBINEDAPACHELOG which cause that beat agent field overrides logstash grok pattern COMBINEDAPACHELOG field.

Option for beat field name should is configurable.

**Comment by jsoriano** [comment]
Hi @iuuuuan,

In principle you can use the [`rename` processor](https://www.elastic.co/guide/en/beats/filebeat/7.3/rename-fields.html) to select a different name in filebeat.

I am going to close this issue as I think there are workarounds for your use case using processors. If you have more questions we are happy to answer in https://discuss.elastic.co.
