### ISSUE TITLE
[Heartbeat] Improved Redirect Behavior Plan

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#13146]
Heartbeat's redirect behavior is broken, per https://github.com/elastic/beats/issues/10823 . The key issue is that we resolve the IP ahead of all HTTP requests, and re-use the IP on subsequent post-redirect requests which is necessary for the `mode: all` behavior. This issue outlines our technical approach to fixing it.

Some people want to follow redirects, others do not. The proposed solution is to:

1. Disable redirects by default in 8.0, since the behavior of following a redirect is surprising for a monitoring product.
2. Fix the redirect following behavior to work in the following way:
  * We would create one heartbeat document per redirect followed. So, a heartbeat check that follows a redirect would produce multiple documents, one per item in the redirect chain. 
  * We would not allow the following of redirects in conjunction with the `mode: all` setting. That could create quite an explosion in terms of the number of documents created/redirects followed.

**Comment by roncohen** [comment]
as mentioned in the issue, `max_redirects` is useful and we should document it in conjunction with your proposal

**Comment by andrewvc** [comment]
As an update on documenting max redirects @roncohen that's in this PR here https://github.com/elastic/beats/pull/13882

**Comment by andrewvc** [comment]
Fixed via https://github.com/elastic/beats/pull/14125
