### ISSUE TITLE
[Metricbeat] Add ability to filter on tags for aws module

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#13145]
Users might only interested in metrics that are from certain EC2 instances with specific tags and only want ec2 metricset to collect from these instances that have these tags. Similarly for cloudwatch metricset. 

This issue is from https://github.com/elastic/beats/issues/10115#issuecomment-516720198.

**Comment by andresrc** [comment]
can we close this one?

**Comment by kaiyan-sheng** [comment]
Yes! There might be more PRs for improvements/bug fixes coming but those will be separate.
