### ISSUE TITLE
Loading the template by default doesn't work on Windows when running as a serivce

### ISSUE THREAD

**Issue by tsg** [elastic/beats#1315]
The problem is that the Beats look for the template by default in the working directory. When running as a service, the current working directory is set to `%WinDir%\System32` or something like that.

Possible solution 1: modify logic to look for the template relative to the path where the binary is.
Possible solution 2: copy the template in `C:\programdata\*beat\` and use an absolute path for it.

Workaround: manually load the template

**Comment by urso** [comment]
I'd prefer solution 2, but when/who/how to copy the file to programdata?

**Comment by tsg** [comment]
Solution 2 is tricky because we don't have a real installer, but an "install" script. The install script could copy it there, but it would also need to modify the configuration file, which is weird.

**Comment by andrewkroh** [comment]
From with ruflin back on March 24, he was under the impression that it was doing solution 1.

**Comment by tsg** [comment]
@andrewkroh I also somehow remember that, but the code doesn't seem to have any special logic for it: https://github.com/elastic/beats/blob/master/libbeat/outputs/elasticsearch/output.go#L146

**Comment by ruflin** [comment]
It was the intention that it is doing solution one. To start we should use the same logic as for the config file. In the long run I hope instead of solution 2 to have a general config and data directory we can use.

**Comment by tsg** [comment]
+1 on handling this together with the concept of the data path. Since the data path will be a breaking change, it would be nice to introduce it in alpha2. I'll put together a proposal.

**Comment by tsg** [comment]
This was fixed via #1371.
