### ISSUE TITLE
[Filebeat][elasticsearch][gc] picking up wrong logs with docker autodiscover

### ISSUE THREAD

**Issue by kesslerm** [elastic/beats#13164]
When the filebeat elasticsearch module is used with docker autodiscover, the gc logs pick up all JSON formatted log entries and index them into the `elasticsearch.gc` dataset.

**Comment by ycombinator** [comment]
@kesslerm Thanks for filing this issue and the associated PR. I'm looking at the PR now.

**Comment by ycombinator** [comment]
This looks like a duplicate of #16583.
