### ISSUE TITLE
Kafka (sarama) log levels 

### ISSUE THREAD

**Issue by urso** [elastic/beats#13177]
Sarama only supports a print like callback for logging what happens internally. Beats currently log these messages as INFO log level. Some might be more critical then others, therefore we should attempt to get some proper log levels being applied.

For example:

```
2019-08-01T20:33:24Z DBG [kafka] Kafka publish failed with: kafka server: The client is not authorized to access this topic.
```

**Comment by simitt** [comment]
@urso we recently got a bug report related to this issue (https://github.com/elastic/apm-server/issues/4068). Are there any plans for working on this?

**Comment by simitt** [comment]
as pointed out by @andrewkroh, there is no level in the [sarama StdLogger interface](https://github.com/Shopify/sarama/blob/2b9c5932132b34a9c59ad6475c08ff17fc7d71bc/sarama.go#L106);
some limited error specific check already happens in beats for differentiating between level `info` and `warning` https://github.com/elastic/beats/blob/78e481d541796ad572ec28d0f4324701fc54aec7/libbeat/outputs/kafka/log.go#L42
