### ISSUE TITLE
Beats hang or panic on shutdown when Elasticsearch/Logstash is not available

### ISSUE THREAD

**Issue by tsg** [elastic/beats#1319]
Experienced with 5.0.0-alpha1, but it is known to affect 1.X versions as well.

Steps to Reproduce: 

* Start Elasticsearch
* Start Topbeat in foreground to connect to Elasticsearch
* Stop Elasticsearch
* Try to stop Topbeat with ^C or SIGTERM

Topbeat doesn't exit and needs to be killed -9.

**Comment by tsg** [comment]
This was fixed in the meantime, tested with alpha3.

**Comment by Kif11** [comment]
I experience the same problem on 1.3.1 on OSX
