### ISSUE TITLE
Missing privilege in docs for securing filebeat

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/beats#13207]
For confirmed bugs, please report:
- Version: Filebeat 7.3
- Operating System: Linux (Ubuntu 18 LTS)
- Steps to Reproduce: 
  - Configure a role "beat-writer" with Kibana that contains the roles as documented in [filebeat docs](https://www.elastic.co/guide/en/beats/filebeat/current/feature-roles.html#privileges-to-publish-events)
  - Run filebeat setup:
  ```
  sudo filebeat setup \
    -E cloud.id=<my cloud id> \
    -E cloud.auth=\${ES_SETUP_USER}:\${ES_SETUP_PASSWORD}`
  ```
  - Configure filebeat.yml using the new writer user
  - sudo filebeat -e

Fix: Add `manage_index_templates` permission to the role.  I tried to write a PR for the docs, but I could not figure out where to add it.  My asciidoc skills must be worse than my [nunchuck skills](https://www.youtube.com/watch?v=XsiiIa6bs9I) today.

<img width="761" alt="Screen Shot 2019-08-08 at 5 30 15 PM" src="https://user-images.githubusercontent.com/25182304/62739999-71006e80-ba04-11e9-8afa-0f2b1efe7754.png">

**Comment by dedemorton** [comment]
I'd like to stick with our recommendation that users pre-load the index template (using a setup role) before they run the Filebeat. I'll update the security docs as described here to make it more explicit that users need to either disable the option to automatically load the index template, or grant additional privileges: https://github.com/elastic/beats/issues/10241#issuecomment-522610334

**Comment by DanRoscigno** [comment]
Thanks @dedemorton.

**Comment by dedemorton** [comment]
@DanRoscigno I think your concerns will be addressed in https://github.com/elastic/beats/pull/13847 and https://github.com/elastic/beats/pull/13849. Can I close this issue, or do you want to keep it open?
