### ISSUE TITLE
Kubernetes Metric beat http module is not coming up

### ISSUE THREAD

**Issue by bhasvij** [elastic/beats#13218]
Unable to load http metric beat module in kubernetes environment. Following is the configuration used:

tried with metric beat: curl -L -O https://raw.githubusercontent.com/elastic/beats/7.3/deploy/kubernetes/metricbeat-kubernetes.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-config
  namespace: kube-system
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    processors:
      - add_cloud_metadata:

    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}

    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: true

    # To enable hints based autodiscover uncomment this:
    #metricbeat.autodiscover:
    #  providers:
    #    - type: kubernetes
    #      host: ${NODE_NAME}
    #      hints.enabled: true
    metricbeat.modules:
    - module: system
    metricsets:
      - cpu             # CPU usage
    enabled: true
    period: 10s
    processes: ['.*']
    metricbeat.modules:
    - module: graphite
    metricsets: ["server"]
    enabled: true
    metricbeat.modules:
    - module: http
    #metricsets:
    #  - json
    period: 10s
    hosts: ["localhost:80"]
    namespace: "json_namespace"
    path: "/"
    method: "GET"

http module path parameter being interpreted wrongly in metricbeat.yml file to be an object and exiting out with the following error:

Exiting: error extracting default paths: required 'object', but found 'string' in field 'path' (source:'/etc/metricbeat.yml')

Tried in minikube environment and kubernetes latest environment

**Comment by jsoriano** [comment]
Hi @bhasvij ,

For questions related to beats usage and for not confirmed bugs, please open a topic in https://discuss.elastic.co/c/beats.

On a quick look to your configuration there can be a couple of problems:
- You are not enabling the [`server` metricset](https://www.elastic.co/guide/en/beats/metricbeat/7.3/metricbeat-metricset-http-server.html) for the http module.
- You are using port 80, you may not have permissions to use this port, or it may be used by other services.

Logs will probably help to diagnose the problem, please add them if you still have this problem and you open a topic in discuss about this.
