### ISSUE TITLE
MQTT as output

### ISSUE THREAD

**Issue by caevv** [elastic/beats#13222]
Would be great to have MQTT as the output for Filebeat and Metricbeat.

We have an IoT use case and the only way we should be getting logs out of the devices is through MQTT.

**Comment by rickardp** [comment]
Did you see https://github.com/nathan-K-/mqttbeat? Never tried it, but it’s on my list of things to try out for my home automation.

**Comment by caevv** [comment]
This looks different, wouldn't that do MQTT -> ES? 
What I'm looking is output MQTT.

**Comment by caevv** [comment]
This seems to do it:
https://github.com/sidleal/mqttout

Would be great to have this officially.

**Comment by rickardp** [comment]
Sorry, I misunderstood. Yes it ingests mqtt. Are you looking to install Beats on your IoT device and use that to transform logs and send over MQTT?

**Comment by caevv** [comment]
Yes, that's it.

**Comment by checkmatesolo** [comment]
checkmatesolo
