### ISSUE TITLE
IP's field conflict between metricbeat 7.2 and 7.3

### ISSUE THREAD

**Issue by alogishetty** [elastic/beats#13224]
I am having issues with below fields when migrating for 7.2 to 7.3. All the fields below are being reported as conflict's. The field type in 7.2 is IP and field type in 7.3 is text. Please let me know how can I fix this?

- destination.ip
- docker.container.ip_addresses
- kubernetes.pod.host_ip
- kubernetes.pod.ip
- server.ip
- source.ip
- system.socket.local.ip
- system.socket.remote.ip

**Comment by jsoriano** [comment]
Hi @alogishetty,

These fields haven't changed from 7.2 to 7.3, their type is still `ip`. I think that you may have some setup problem.
We keep github issues for confirmed bugs, please start a topic in https://discuss.elastic.co/ to get more help on this issue.
