### ISSUE TITLE
Cannot import exported dashboard via helm chart

### ISSUE THREAD

**Issue by slawekww** [elastic/beats#13220]
Installed Elasticsearch 7.2.0, kibana 7.2.0 using eck-operator.
Installed metricbeat using helm chart version 1.7.0 from stable/metricbeat.
Use setup.dashboards.enabled: true to insert default visualization/dashboard.

Reproduce problem:
1/ Export Kubernetes overview dashboard via kibana, export.ndjson.
2/ Rename file export.ndjson to mydashboard.json.
3/ add volume with custom dashboards to helm chart
4/ install metricbeat via helm
5/ error at importing dashboards:

2019-08-12T07:56:01.824Z	INFO	instance/beat.go:418	metricbeat stopped.
2019-08-12T07:56:01.824Z	ERROR	instance/beat.go:877	Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing directory /usr/share/metricbeat/kibana: Failed to import dashboard: Failed to load directory /usr/share/metricbeat/kibana/7/dashboard:
  error loading /usr/share/metricbeat/kibana/7/dashboard/kubernetes-metrics.json: fail to unmarshal the dashboard content from file /usr/share/metricbeat/kibana/7/dashboard/kubernetes-metrics.json: json: cannot unmarshal array into Go value of type common.MapStr
Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing directory /usr/share/metricbeat/kibana: Failed to import dashboard: Failed to load directory /usr/share/metricbeat/kibana/7/dashboard:
  error loading /usr/share/metricbeat/kibana/7/dashboard/kubernetes-metrics.json: fail to unmarshal the dashboard content from file /usr/share/metricbeat/kibana/7/dashboard/kubernetes-metrics.json: json: cannot unmarshal array into Go value of type common.MapStr

It sounds like https://github.com/elastic/beats/issues/8200 is still not solved for 7.2.0 version
and metricbeat import pre-defined dashboard using helm deployment.

Note: exported dashboards / visualizations can be imported again via Kibana.
Problem is only seen if import is done thru helm chart for metricbeat.

For confirmed bugs, please report:
- Version: 7.2.0
- Operating System: Centos7
- Discuss Forum URL:
- Steps to Reproduce:

**Comment by jsoriano** [comment]
Hi @slawekww,

Beats use a different API to export and import dashboards, that is not compatible with the dashboards exported using the Kibana UI. You can try to export your dashboard to reuse it with metricbeat with the `metricbeat export` command, something like this:
```
metricbeat export dashboard --decode -id <dashboard id>
```

I am going to close this issue as this should be supported by metricbeat subcommands, and I don't think that we are going to add support for dashboards exported as Kibana objects soon.

If you have further questions about Beats usage or non-confirmed issues, please start a topic on https://discuss.elastic.co/c/beats
