### ISSUE TITLE
cannot change  default Metricbeat index for Elasticsearch 

### ISSUE THREAD

**Issue by beyondmars3** [elastic/beats#13235]
I cannot change my default Metricbeat index name for Elasticsearch. Did you guys find a fix? I appreciate if you can share it with me. Thank you.

this is my  metricbeat.yml
```
#================================ Outputs =====================================

# Configure what output to use when sending the data collected by the beat.

#-------------------------- Elasticsearch output ------------------------------

output.elasticsearch:
  # this is demo hosts, not true
  hosts: ["0.0.0.0:9200","0.0.0.0:9200","0.0.0.0:9200"]

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"
  
output.elasticsearch.index: "customname-%{[agent.version]}-%{+yyyy.MM.dd}"
setup.template.name: "customname"
setup.template.pattern: "customname-*"
```

and this is Final Elasticsearch results
```
metricbeat-7.3.0-2019.08.14-000001
```

**why it not work ?** 

For confirmed bugs, please report:
- Version: metricbeat 7.3
- Operating System: windows 7 and linux centos -6.7
- Discuss Forum URL:
- Steps to Reproduce:

**Comment by jsoriano** [comment]
Hi @beyondmars3,

Since Beats 7.x, ILM (Index lifecycle management) is enabled by default and it manages your indexes lifecycle, including index names. You can read more about this in https://www.elastic.co/guide/en/beats/metricbeat/7.3/ilm.html

If you have more questions about this, please open a topic in https://discuss.elastic.co/c/beats

**Comment by beyondmars3** [comment]
Thank you very much.  it work. I use it this way. Daily Index

```
setup.ilm.enabled: false
```
