### ISSUE TITLE
[DOCS] Tiny capitalisation issue in autogenerated Metricbeat docs for Graphite module

### ISSUE THREAD

**Issue by Titch990** [elastic/beats#13237]
On this page https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-graphite.html, which is autogenerated from metricbeat/module/graphite/_meta/docs.asciidoc, we have "graphite Module" in the body of the text. It should, of course, be "Graphite module.

**Comment by Titch990** [comment]
@fearful-symmetry As discussed yesterday. I'm not sure what the process is here. I'm happy to make the change if someone can talk me through what else needs to happen to get the auto-generated content redone.

**Comment by dedemorton** [comment]
Closed by #13900
