### ISSUE TITLE
filebeat: Add "partial line" support based on timeouts.

### ISSUE THREAD

**Issue by danielmotaleite** [elastic/beats#1324]
As per discussion in https://discuss.elastic.co/t/filebeat-multiline-ignores-line-if-the-newline-doesnt-exist/46098/3

i have a php app that is writing 3 lines and i already have a working multiline working fine, except that the last line does not print a newline and the event is rare, so multiline filebeat will timeout before there is a new event, breaking the event in to 2 events, one incomplete multiline event and a lone line. Increasing the multiline timeout could push the event end a long time and may even not solve if there is no new event for hours.

This is a app log problem, but not all apps can be changed, so filebeat needs a way to solve this.

If filebeat line parser had support for a timeout for partial line, i could put that one with a timeout of X seconds and line parser would send the partial line to the multiline and the event would be correctly processed.

Example:
currently:

```
2016-04-01 blabla bla\n  \_ multiline event received after multiline timeout of 300s reach
bla bla\n                /
bla bla                            -> no newline
2016-04-01 blabla bla\n  -> after 30 minutes this event show up and previous line is a new event. Repeat
```

after partial line timeout of 3 seconds:

```
2016-04-01 blabla bla\n  \ 
bla bla\n                 |-> multiline event received, after the multiline time of 5s  the event ends
bla bla                  /          -> after 3 seconds, push the line to multiline
2016-04-01 blabla bla\n  -> after 30 minutes this event show up. Repeat
```

**Comment by sergiu-tot** [comment]
Hello guys,

I have a similar issue regarding filebeat + Magento2 reports (var/report).

Any updates or workarounds?

**Comment by danielmotaleite** [comment]
Sorry, but no still workarounds, other than trying to fix the log line to have a "\n" in the end or having a external process  rebuilding/fixing the log (hacky, only really doable if a small logs)
