### ISSUE TITLE
Prometheus collector in metricbeat silently fails if metric name is incorrect

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#13252]
Prometheus collector silently fails if the prometheus response contains invalid metric
names, this can be reproduced for example if the metric name contain dots.
[This error](https://github.com/elastic/beats/blob/v7.3.0/metricbeat/helper/prometheus/prometheus.go#L82) should be reported, or at least logged on the debug level.

For confirmed bugs, please report:
- Version: 6.X, 7.X
- Steps to Reproduce: Configure the prometheus collector to an endpoint that exposes
prometheus metrics with incorrect names. Seen in java applications with Micrometer
exposing metrics with dots in their names.

**Comment by kaiyan-sheng** [comment]
https://github.com/elastic/beats/pull/13353 fixed this.
