### ISSUE TITLE
[Functionbeat] Add support for adding "Timeout" for Lambda

### ISSUE THREAD

**Issue by CloudViking86** [elastic/beats#13267]
**Describe the enhancement:**
According to Functionbeat 7.3 > functionbeat.reference.yml there is no parameter that you can set for the Lambda "timeout". You can set "memory_size" but when searching in the reference there seems to be no way to set the "timeout"-value for the Lambda.

**Describe a specific use case for the enhancement or feature:**
This not being added requires you to modify the function / Lambda outside Cloudformation.

**Comment by kvch** [comment]
It is possible to configure timeout by configuring the option `timeout`. It is just missing from the reference.
