### ISSUE TITLE
use single field for URLs across modules

### ISSUE THREAD

**Issue by randomuserid** [elastic/beats#13279]
**Describe the enhancement:**

Get the filebeat modules to populate URLs in the same field. Looks like IIS module uses url.path while the nginx module uses url.original

**Describe a specific use case for the enhancement or feature:**

Would enable a single machine learning job to analyze this field in logs from different web servers.

**Comment by kaiyan-sheng** [comment]
I checked ECS https://www.elastic.co/guide/en/ecs/current/ecs-url.html and seems like `url.original` should be used across different modules.

**Comment by webmat** [comment]
My recommendation in how to solve this is to:

- always put the url or path as is into `url.original`. It's not meant to be used directly, it's meant to be a reflection of whatever URL format this source gave you (just a path or full url).
- Always populate `url.path` with the path of the web call, excluding the domain and query params
- if the scheme, host and so on are known, parse them out as well and fill `url.scheme` and `url.domain` accordingly
