### ISSUE TITLE
"filebeat -e setup" fails with a wildcard certificate

### ISSUE THREAD

**Issue by Zamiell** [elastic/beats#13285]
Greetings; [I've posted my bug on the forums already](https://discuss.elastic.co/t/filebeat-setup-fails-with-wildcard-certificate/193847) but no-one has replied in 14 days, so I am now posting it here.

Steps to reproduce:

* Install vanilla CentOS 7
* Download and install filebeat-6.8.0-x86_64.rpm
* Edit "/etc/filebeat/filebeat.yml" to include the host, username, and password of the remote ElasticSearch cluster with HTTPS enabled on a wildcard certificate.
* Run "filebeat -e setup".
* This results in the following error:

```
2019-08-05T12:16:20.409-0400    ERROR   elasticsearch/elasticsearch.go:252      Error connecting to Elasticsearch at https://es-1-dev.company.com:9200: Get https://es-1-dev.company.com:9200: x509: certificate is valid for es-*.company.com, not es-1-dev.company.com
```

My initial take is that whoever programmed this forgot about wildcard certificates, but it is also possible that I am not configuring ElasticSearch properly. Please advise.

**Comment by andrewkroh** [comment]
Answered at https://discuss.elastic.co/t/filebeat-setup-fails-with-wildcard-certificate/193847/2?u=andrewkroh.
