### ISSUE TITLE
Working Filebeat Modules and Kafka output

### ISSUE THREAD

**Issue by iamhowardtheduck** [elastic/beats#13290]
**Describe the enhancement:**

**Describe a specific use case for the enhancement or feature:**

Would it be possible to incorporate the logstash documentation into the Beats documentation, or a link for it?

https://www.elastic.co/guide/en/logstash/current/use-filebeat-modules-kafka.html

This is absolutely critical in order to get working, and trying to find this information was exceptionally difficult.

**Comment by candlerb** [comment]
Can you be more specific about what you want and where?

Filebeat already documents how to connect to logstash [here](https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html).  On that page, you'll see the following text:

> Want to use [Filebeat modules](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-modules.html) with Logstash? You need to do some extra setup. For more information, see [Working with Filebeat modules](http://www.elastic.co/guide/en/logstash/7.3/filebeat-modules.html).

The second of those links goes to the relevant logstash documentation, and the filebeat-modules-kafka page you quoted is a subpage of that page.

**Comment by jsoriano** [comment]
@iamhowardtheduck as @candlerb mentions I think that there is already documentation about how to use filebeat with logstash.

Maybe what is not clear enough from the filebeat documentation is how to consume logs from Kafka when sent from filebeat. We should probably add something else about how to use logstash (or the upcoming filebeat kafka input #7641) in https://www.elastic.co/guide/en/beats/filebeat/7.3/kafka-output.html.

**Comment by faec** [comment]
The Kafka input now exists and is documented at https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-kafka.html
