### ISSUE TITLE
[Metricbeat] Redis keys dashboard references non-existing index

### ISSUE THREAD

**Issue by rudolf** [elastic/beats#13300]
Importing and opening the [[Metricbeat Redis] Keys ECS dashboard](https://github.com/elastic/beats/blob/master/metricbeat/module/redis/_meta/kibana/7/dashboard/Metricbeat-redis-keys.json) loads visualizations which point to non-existing indexes. Because of the missing index references, opening the dashboard in kibana shows broken vizualizations:

<img width="1277" alt="Screenshot 2019-08-21 at 12 37 58" src="https://user-images.githubusercontent.com/1281646/63426700-c16bc900-c413-11e9-8af1-82f61aabbd33.png">

- Version: 7.3.1
- Steps to Reproduce: 
1. `./metricbeat setup -E "setup.dashboards.url=https://staging.elastic.co/7.3.1-89dbfb4a/downloads/beats/beats-dashboards/beats-dashboards-7.3.1.zip"`
2. Open the "[Metricbeat Redis] Keys ECS" dashboard

**Comment by rudolf** [comment]
I didn't test it, but grepping through the source code I also noticed a hard index reference in which might lead to similar problems https://github.com/elastic/beats/blob/master/x-pack/auditbeat/module/system/_meta/kibana/7/dashboard/auditbeat-system-host-dashboard.json#L628

**Comment by jsoriano** [comment]
> I didn't test it, but grepping through the source code I also noticed a hard index reference in which might lead to similar problems https://github.com/elastic/beats/blob/master/x-pack/auditbeat/module/system/_meta/kibana/7/dashboard/auditbeat-system-host-dashboard.json#L628

I have tested this dashboard and it seems to work, this index seems to be referenced in the metadata of a saved search, but the saved search itself references to the expected `auditbeat-*` index, so I think this is ok.
