### ISSUE TITLE
Refactor Jolokia metrics to provide dynamic mapping

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#13316]
Metrics collected by jolokia module are stored now in events with fields like `jolokia.<namespace>.<custom field name>`, with the field name allowed to have dots. This makes impossible to provide a mapping, and it can provoke fields explosion in complex deployments.

This module could be refactored following the strategy followed in more recent "generic" metricsets implementations as prometheus collector or aws cloudwatch, where all metrics are stored under the same object (`prometheus.metrics.*` and `aws.metrics.*.*`), so we can provide a mapping for all fields.

There are two things that can condition the decision on the structure:
* APM agent for Java is also able to collect metrics from JMX, it'd be good to follow the same naming (discussed in https://github.com/elastic/apm-agent-java/issues/469).
* In contrast to prometheus, where all metrics are doubles, JMX can return non-numeric values, we will have to consider if we provide a different namespace for them.

If it is done as a replacement of current implementation it will have to be done in 8.0, alternatively we can consider to make it as a new metricset, or add a flag to chose what naming to use.

We would still need to offer the possibility of define explicit mappings to continue supporting light modules like tomcat (see [example](https://github.com/elastic/beats/blob/v7.8.0/x-pack/metricbeat/module/tomcat/cache/_meta/data.json#L21)) or other custom usages.

Possibly related issues:
* https://github.com/elastic/beats/issues/3585
* https://github.com/elastic/beats/issues/13604

**Comment by jsoriano** [comment]
Related discussion for the SQL case, where there are also multiple data types: https://github.com/elastic/beats/pull/13257#issuecomment-525389890

**Comment by kaiyan-sheng** [comment]
@jsoriano Are we still considering making this breaking change for 8.0?

**Comment by jsoriano** [comment]
@kaiyan-sheng I wouldn't consider it so prioritary and I don't think we are going to have time for this. So I think we can close this.

If at some moment we can dedicate a little of time to this I would consider https://github.com/elastic/beats/issues/13604 more valuable for current users, and is probably a low-hanging fruit.

And if we can or need to dedicate more efforts we can re-consider how we collect JMX metrics, and this could be done in a new module/integration (something like what was discussed in https://github.com/elastic/beats/issues/18324). Agent opens the gates to have a native Java collector that could be used to avoid the requirement of Jolokia.

Pinging @akshay-saraswat for awareness.
