### ISSUE TITLE
Set Fileversion metafield on exe to beat version

### ISSUE THREAD

**Issue by Shaoranlaos** [elastic/beats#13310]
**Describe the enhancement:**
Each Exe in Windows has a Metafield Fileversion which normaly describe's the version of the program the file is starting. This field is empty for Filebeat, Metricbeat and WInlogbeat (these are the ones i checked). This field should be filled during the build process with the beat version.
![image](https://user-images.githubusercontent.com/25054970/63486810-481eb580-c4a9-11e9-93ef-732487dab120.png)
(I only have access to a german windows so please excuss the non english screenshot)

**Describe a specific use case for the enhancement or feature:**
This would make it easier to identify if an update of the beat through a centralized software management was successful, because these can easily check these meta fields.

**Comment by jsoriano** [comment]
@Shaoranlaos thanks for opening this enhancement proposal. I think it should be possible to do it with https://github.com/josephspurrier/goversioninfo

**Comment by jsoriano** [comment]
Fixed by https://github.com/elastic/beats/pull/16048
