### ISSUE TITLE
Change http exported fields

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#1332]
To fix the [question](https://discuss.elastic.co/t/packetbeat-http-content-lenth-fields-is-for-request-or-response/46468) on discuss, I propose the following changes:
- http
  - request
    - path
    - params
    - content_length
    - content_type 
    - headers
  - response
    - code
    - phrase
    - content_length
    - content_type
    - headers 

This includes also the changes suggested in https://github.com/elastic/beats/issues/1333.

**Comment by urso** [comment]
+1, but right now request/response is the raw content, right? This will break bc (which is ok)?

**Comment by monicasarbu** [comment]
Yes, request and response contain the raw request/response. http.request and http.response will be added. Yes, it breaks compatibility, so I am thinking to include this change for alpha2.
