### ISSUE TITLE
Implement normalized percentages for Docker module

### ISSUE THREAD

**Issue by Rickvanderwaal** [elastic/beats#13343]
**Describe the enhancement:**
The system module of metricbeat does have some nice normalized cpu percentages. It seems we have to do devide the cpu percentage by the number of cores manualy for the docker module. Can you support normalized cpu percentages for the docker module?
Version: `Metricbeat 7.3.1`

Docs for system module: https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-system.html - field `system.process.cpu.total.norm.pct`.

**Describe a specific use case for the enhancement or feature:**
We are monitoring the cpu load of our docker containers. At this time we need a logstash pipeline to calculate the normalized percentages. We then have some XPack watchers to alert whenever the cpu load is above a threshold (0-100%).

**Comment by ChrsMark** [comment]
@Rickvanderwaal thank you for bringing this up!
The suggestion of this issue was implemented in #13695, so I'm gonna close this issue.
Feel free to comment if you find anything that is still missing.
