### ISSUE TITLE
Document separation of manager and function in Functionbeat

### ISSUE THREAD

**Issue by kvch** [elastic/beats#13372]
In #12939 Functionbeat binary was split into two parts: manager and function. 

#### Manager

It is able to deploy, update and delete functions to/from the cloud provider. Name of the binary is `functionbeat`. It cannot be run as a regular Beat.

##### Who needs the manager?
It is not necessary to use this binary if someone has their own infrastructure to deploy functions to their selected cloud provider. It is just for people who are getting started with cloud functions and/or do not have such infrastructure.

##### How does the manager deploy the function?

It generates a Cloudformation template, packages the function bin and configuration and uploads it. To inspect the generated CF template, you can export it using the subcommand `function export {function-name}`.

#### Function

Currently, it resides under the folder `pkg` in the various packages we distribute (DEB, RPM, etc.). Right now only one function is available: `functionbeat-aws`. This is supposed to run on AWS as a Lamda function. It does not make sense to run it on the host of the user unless one is testing it locally using e.g. `sam local invoke`.

##### How to deploy the function?

There are several options: using the manager provided by us, manually using the cloud provider's web UI or automatically doing the supported way by the provider (for example using Cloudformation templates in case of AWS).

To run the function on the provider you need to package the following files: function, configuration and keystore if configured.
You can package the function using the subcommand `package`.

Contents of the generated package:
```
$ unzip -l package.zip
Archive:  package-aws.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     1582  1980-00-00 00:00   functionbeat.yml
 60031440  1980-00-00 00:00   functionbeat-aws
     1540  1980-00-00 00:00   /tmp/functionbeat.keystore
---------                     -------
 60033022                     2 files
```

Apart from having the required files in the package, one has to set two environment variables.
- `BEAT_STRICT_PERMS=false`: This makes the function skip the ownership check of the configuration file
- `ENABLED_FUNCTIONS={function-name-1},{function-name-2}`: This requires a comma-separated list of enabled functions from the configuration file. Meaning, if functions `my-kinesis` and `my-cloudwatch-logs` are enabled, the environment variable has to be set to `my-kinesis,my-cloudwatch-logs`.

##### How to deal with certs?

Unfortunately, the `package` command is not able to package certs. So if those are required, users need to package the files manually. They need to make sure that cert files are under the same path in the zip as configured in `functionbeat.yml`.

Related issue: #11781

**Comment by dedemorton** [comment]
Closed by #13886
