### ISSUE TITLE
Kafka module can fail to collect partition offsets for topics with many partitions

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#13380]
In some Kafka clusters with topics with many partitions there can be problems collecting the offsets, what causes many errors that can flood logs.

This is possibly caused by the way Metricbeat collects the partitions offsets. It gets first the metadata and then it gets the offsets partition by partition. Under some circumstances, with many partitions, some errors happen, like:
* `kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.`
* `broker is not leader`

There are two possible solutions for these errors, but it may be good to implement both:
* Offset requests can request several partition offsets at once. Try to request all the offsets in a single request, or at least split them in less requests. It may be needed to make one request per broker, as the offsets for each partition should be requested to their leaders.
* Handle the error about out of date metadata, and request the metadata again to continue requesting partitions.

**Comment by mraliagha** [comment]
Is there any workaround for this issue?

**Comment by jsoriano** [comment]
> Is there any workaround for this issue?

@mraliagha I am afraid that not at the moment :slightly_frowning_face: Are you being hit by this issue? Do you see errors about outdated metadata?

**Comment by mraliagha** [comment]
> @mraliagha I am afraid that not at the moment 🙁 Are you being hit by this issue? Do you see errors about outdated metadata?
Yes, we are facing this issue with 7.10.1.

**Comment by mraliagha** [comment]
I'm still having this issue with version 7.16.1.
