### ISSUE TITLE
incluster: false and kubeconfig settings not work for kubernetes module in metricbeat

### ISSUE THREAD

**Issue by KielChan** [elastic/beats#13392]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: v7.3.1
- Operating System: docker
- Discuss Forum URL:
- Steps to Reproduce: 

1. set kuberneters module and access security port just like kubelet 10250, kube-apiserver 8443
2. set kubernetes module in cluster equals to false
3. set kubernetes module kubeconfig, its cluster role almost has all rights to access any objects in kubernetes cluster including metrics url.
4. finally, error msgs in kibana told that no auth

**Comment by odacremolbap** [comment]
Hi @KielChan 

Is there a https://discuss.elastic.co/c/beats issue you can refer to?
If not, please open the issue at discuss, if it is a bug we will open a Github issue.

Closing for now
