### ISSUE TITLE
Add License headers to all the files under the x-pack directory

### ISSUE THREAD

**Issue by ph** [elastic/beats#13408]
We would like to make it explicit which files is cover under what license, right now everything that lives under the x-pack folder is under the Elastic License. All modules in the x-pack/files/modules.d are under the Elastic License by default. 

But at the moment the following files *.JSON, *.YML in the x-pack folder does not declare a license.

We need to make sure that:
- Manifests
- Pipelines
- Dashboards

Are all covered by the Elastic headers.

Things we need:

- We need to check the presence of the license headers for theses files when running `make check`
- Having tooling in place to automatically add headers to the files.

**Comment by ph** [comment]
List of unique file type in the directory ordered by the number of files. 
```
    358 json
    330 yml
     88 dat
     69 asciidoc
     46 log
     21 md
     15 tmpl
     13 py
     12 plain
     11 png
      7 Makefile
      7 Dockerfile
      6 js
      6 gitignore
      5 evtx
      5 csv
      3 yaml
      3 txt
      3 j2
      3 bat
      2 pcap
      2 jpg
      1 wtmp
      1 svg
      1 status
      1 rl
      1 rb
      1 placeholder
      1 examples
      1 Corefile
      1 btmp_ubuntu1804
```

**Comment by kuisathaverat** [comment]
related to https://github.com/elastic/observability-robots/issues/411

**Comment by kuisathaverat** [comment]
related to https://github.com/elastic/beats/issues/13408
