### ISSUE TITLE
Winlogbeat core informations doesn't follow ECS at all

### ISSUE THREAD

**Issue by ragri8** [elastic/beats#13416]
While we're trying to converge same fields in a single name and follow the ECS guidelines, the events from windows are still in the dark age. Most "header fields", such as `winlog.api`, `winlog.channel`, `winlog.user.*`, `agent.*`, `event.*` etc, are well populated. But every fields nested in `winlog.event_data.*` are a complete mess.

Here's some example, but the list is incredibly long:
`DestAddress`, `DestinationIp`, `DisplayName`, `DomainName`, `IpAddress`, `ProcessId`, `ProcessGuid`, `SourceIp`, `SubjectDomainName`, `SubjectUserName`, `TargetDomainName`, `TargetUserName`, `UserWorkstations`, etc

Most fields, depending on the event, share common data with other ones, like `DestAddress` and `DestinationIp`.
Sometime the same field doesn't have the same information between events, like `TargetUserName` which is most of the time a user name, but can also be a group name in some events.
Sometime you can't even find what does the field represent without searching hours for some incomplete windows documentation specific to your event, like for the field `Value` which is an IP address related to destination and/or server in the event 1024 or 1102 from Microsoft-Windows-TerminalServices-RDPClient/Operational.
IMO, the worst ones are the application events because most fields are mapped in `param1`, `param2`, `param3`, ..., `param21` and everyone of them are specific to their event code.

All those fields should be renamed and mapped properly. I understand that it is a quite complex task, but winevents analysis is really important for security monitoring.
Networks and users fields could be handled first, along with security events because there is at least documentation for most events [here](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/master/windows/security/threat-protection/auditing).

Also, to help with the mapping, the Hunting ELK already tried to map in proper way most winevents. Everything is done  [in their logstash pipeline](https://github.com/Cyb3rWard0g/HELK/tree/master/docker/helk-logstash/pipeline). They are not using ECS (for now), but at least they spread some light on this darkness. It could be a good starting point for the remapping and if needed, their team offered some help some months ago in issue #10435, they might still be interested.

**Comment by mbudge** [comment]
Yep https://github.com/elastic/beats/issues/13394
