### ISSUE TITLE
Test s3 input parallel processing with multiple Filebeats

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#13457]
This issue is just for me to track the test work needs to be done for s3 input. If users want to horizontally scale the processing, they should be able to have multiple Filebeats reading from the same SQS queue.

**Comment by kaiyan-sheng** [comment]
I started two filebeats running. Then I uploaded 15 log sample files into S3 bucket and that generated 15 messages in SQS immediately, which got read by two filebeats separately seem like. The events reported by both filebeats in Kibana look like:
<img width="2080" alt="Screen Shot 2019-09-03 at 4 58 30 PM" src="https://user-images.githubusercontent.com/14081635/64214287-2213f080-ce6d-11e9-9657-f8043700b207.png">

**Comment by kaiyan-sheng** [comment]
Tested with 3 filebeat with 15 log sample files as well:
<img width="1008" alt="Screen Shot 2019-09-04 at 8 05 43 AM" src="https://user-images.githubusercontent.com/14081635/64262818-ea985900-ceeb-11e9-844c-ebccb65cef51.png">

**Comment by kaiyan-sheng** [comment]
@acchen97 Thanks for asking about testing filebeat parallel processing. Please see results above. These two tests I did are very basic and simple with 15 files and each file only has one log line in it. Do you think it's efficiently enough to prove that parallel works or you'd like to see more? Please let me know.

**Comment by kaiyan-sheng** [comment]
I did more tests with larger scale:
1000 log example files, each log file contains 10 lines of logs. For example:
```
kaiyansheng@KaiyanMacBookPro:/tmp/example-logs$ cat log-1.txt 
line1
line2
line3
line4
line5
line6
line7
line8
line9
line10
```

Because each log line will be stored into a separate event, total we should be getting **_10000_** events.

These log files are all uploaded into an S3 bucket and immediately you can see notification messages are coming into SQS queue.
<img width="845" alt="Screen Shot 2019-09-13 at 12 04 39 PM" src="https://user-images.githubusercontent.com/14081635/64885408-5633a200-d621-11e9-8a5f-f257e6965085.png">

Start 3 filebeats at the same time (almost) with s3 input enabled, after 30 seconds ish, all logs are read and events are stored into Elasticsearch. Check Kibana and you can see 10000 hits total in 30 seconds:
<img width="683" alt="Screen Shot 2019-09-13 at 12 18 40 PM" src="https://user-images.githubusercontent.com/14081635/64885640-df4ad900-d621-11e9-8260-da29da426fd5.png">

Since we have 3 filebeats running, I also checked how many events are reported by each filebeat. Each filebeat should have its own unique `agent.id` and this is shown in the filter:
<img width="398" alt="Screen Shot 2019-09-13 at 12 20 10 PM" src="https://user-images.githubusercontent.com/14081635/64885741-17521c00-d622-11e9-85de-07ed29f7b7dc.png">

Use each `agent.id` as a filter, I can see:

| Filebeat #  | Total # of Events | Total # of log files|
| ------------- | ------------- | ------------- |
| 1 |  3350 |  335| 
| 2| 3350 |  335| 
| 3| 3300 |  330| 

Filebeat1:
<img width="1621" alt="Screen Shot 2019-09-13 at 12 20 30 PM" src="https://user-images.githubusercontent.com/14081635/64886155-c262d580-d622-11e9-8aa2-978ee4c64635.png">

Filebeat2: 
<img width="1630" alt="Screen Shot 2019-09-13 at 12 20 48 PM" src="https://user-images.githubusercontent.com/14081635/64886188-ce4e9780-d622-11e9-9aa8-c452958d1ddf.png">

Filebeat3: 
<img width="817" alt="Screen Shot 2019-09-13 at 12 21 15 PM" src="https://user-images.githubusercontent.com/14081635/64886210-d9a1c300-d622-11e9-8ffe-1064d62c90f3.png">

**Comment by acchen97** [comment]
@kaiyan-sheng looks great, thanks for doing this! Love the even processing distribution. :)

At this point, do you think it makes sense for us to outline this parallel processing use case in the S3 input docs? I think it will help raise visibility, and will be beneficial for the stack as a whole given this is an existing feature gap. /cc @dedemorton
