### ISSUE TITLE
journalbeat OSS version contains _xpack code

### ISSUE THREAD

**Issue by benny-medflyt** [elastic/beats#13461]
Hi, I'm using journalbeat 7.3.1 OSS, downloaded from:

<https://www.elastic.co/downloads/beats/journalbeat-oss> 

(<https://artifacts.elastic.co/downloads/beats/journalbeat/journalbeat-oss-7.3.1-x86_64.rpm>)

But it gives an error when trying to connect to elasticsearch:

    request checking for ILM availability failed: 401 Unauthorized: {"Message":"Your request: '/_xpack' is not allowed."}

It seems like the "xpack" code mistakenly got added to the OSS version of journalbeat.

Related: #11607

**Comment by kvch** [comment]
Github Issues are reserved for verified bugs. Please post your question on Discuss: https://discuss.elastic.co/c/beats
