### ISSUE TITLE
Add field `backend_type` column in "activity" metricset as supported by PostgreSQL 10

### ISSUE THREAD

**Issue by kshitij10496** [elastic/beats#13464]
**Describe the enhancement:**
Can we support a new field corresponding to the newly added column `backend_type` in `pg_stat_activity`? This was added in PostgreSQL 10. 

I noticed that the latest beats shipper is compatible with PostgreSQL 9.2.
Are there any plans for this support in the roadmap?

**Describe a specific use case for the enhancement or feature:**
Get more info about the server at a query level.

**Comment by dplavcic** [comment]
This is something that I'm working on together with few other things. I'll create PR for this soon.

**Comment by kshitij10496** [comment]
Thanks a lot @dplavcic ! 😃 
I look forward to it.

**Comment by dplavcic** [comment]
Fixed [metricbeat]: [24402](https://github.com/elastic/beats/pull/24402)
