### ISSUE TITLE
Wrong timestamp in system and auth logs

### ISSUE THREAD

**Issue by VN1977** [elastic/beats#13489]
We have cluster from 2 data nodes and 3 master nodes. Recently we started to gather logs from linux with filebeat 7.3.0. All was going OK but yesterday I realized that timestamp in logs differs in 3 hours, my timezone is Europe/Moscow. All our servers have the same timezone.
I looked through forum and other resources, tried setting var.convert_timezone to true, deleted pipeline at ingest node but nothing changes.
Today I installed new filebeat 7.3.1 at new linux server and noticed that there is no setting var.convert_timezone any more. I added the new pipeline for filebeat-7.3.1 but the same bug and timestamp differs from timestamp in /var/log/messages or /var/log/secure
The difference is 3 hours exactly so I suspect that Elastic stores data from filebeat not in UTC but localtimezone Moscow. When I see data in Kibana, my timezone taken from browser is Moscow too. If I change Kibana timezone to UTC everything got from filebeat is OK, but other logs got from winlogbeat have wrong timestamp.
So how to solve this problem with filebeat and system module?

For confirmed bugs, please report:
- Version: 7.3.1
- Operating System: Centos 7.4
- Discuss Forum URL:
- Steps to Reproduce:

**Comment by kaiyan-sheng** [comment]
Hello! Thanks for reporting this problem. I believe recently we just fixed it and backported into 7.3 https://github.com/elastic/beats/pull/13358. This should be included by the next release.

**Comment by willemdh** [comment]
Just noticed timezone issues in the logstash.log dataset too...

**Comment by lingonl** [comment]
Also noticed timezone issues with nginx error log.

**Comment by kaiyan-sheng** [comment]
@lingonl I think nginx timezone problem should be fixed by https://github.com/elastic/beats/pull/13369 and this is backported to 7.3 and 7.4.

**Comment by jsoriano** [comment]
I am closing this because I think that this should be fixed in upcoming versions, please reopen if you continue seeing these issues in following versions.

Thanks for reporting!
