### ISSUE TITLE
Beat creates incorrect index after index is deleted

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#13501]
Version: `master` / 8.0.0

Tested with Filebeat but I'm pretty sure this will happen with any beat.

### Steps to reproduce

1. Run Filebeat with the Elasticsearch output with a fresh install of Elasticsearch.
2. Make sure at least one event is indexed by Filebeat.
3. Verify that a Filebeat index and alias are created.
   ```
   GET _cat/aliases/filebeat*
   GET _cat/indices/filebeat*
   ```
4. Delete the Filebeat index.
    ```
    DELETE filebeat-*-*
    ```
5. Note that at this point the alias gets deleted as well.
6. Now make sure at least one new event is indexed by the same Filebeat.
7. Note that a new Filebeat index is created but it's called just `filebeat-VERSION`. That is, there are no date and ILM counter suffixes to the index name. Also note that the `filebeat-VERSION` alias is not created.

Thanks to @chrisronline for originally finding this bug.

**Comment by chrisronline** [comment]
Just to add a little more information.

If the user does run the `DELETE filebeat-*` and then Filebeat sends a new event, it won't have the right mappings and therefore any visualizations or dashboards using `filebeat-*` will not work properly as a result.

**Comment by ycombinator** [comment]
This looks related to https://github.com/elastic/elasticsearch/issues/41699.

**Comment by ycombinator** [comment]
Closing as duplicate of https://github.com/elastic/elasticsearch/issues/41699.

**Comment by tsigouris007** [comment]
@ycombinator I read the whole thread and while somewhat related it's not the same issue and this does not fix this particular problem. The thread is about the rollover alias while this one happens when you delete an index.
