### ISSUE TITLE
Metricbeat docker dashboard container table sorting is irrelevant

### ISSUE THREAD

**Issue by cdalexndr** [elastic/beats#13529]
The docker dashboard table ("Docker containers" top left) shows only top 5 containers (sorted by some unknown metric), but if I want to sort by some top header column, only the displayed data is sorted, missing some containers that may be in top 5 using that sort order.

When I sort the data I expected the displayed container data to be recomputed and displayed top 5 using the selected sort column. 
Another way is to show all containers in table so that the data is correctly sorted in UI without backend access.

**Comment by sorantis** [comment]
Hi @cdalexndr, you can quickly solve this by expanding the number of containers shown on that table. Enter the Edit mode on the dashboard and press Edit Visualization on the `Docker panel
<img width="301" alt="edit" src="https://user-images.githubusercontent.com/1685068/69163548-b6960280-0aee-11ea-9260-48a5d72fda43.png">

Expand the `Buckets` configuration and replace 5 with any reasonable number that covers your amount of containers. Eventually you'll see something like this:
<img width="2454" alt="table" src="https://user-images.githubusercontent.com/1685068/69163657-e6450a80-0aee-11ea-9975-d2401b281471.png">

Notice the appeared pagination and that the size of the table remains the same. You can control how many entries you want to see by editing the `Max rows per page` entry in the `Options` menu. Visibly the table should remain the same, but now you should be able to sort on all your containers. 

Eventually your table will look something like this:

<img width="1226" alt="Screen Shot 2019-11-19 at 17 10 52" src="https://user-images.githubusercontent.com/1685068/69164064-94e94b00-0aef-11ea-8be9-81a953686935.png">
