### ISSUE TITLE
[Metricbeat] Improve go test flags

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#13531]
When testing kubernetes metricbeat module, I realize we have three different flags for generating/updating files:
```
go test -generate
go test -data
go test -update_expected
```

For `-generate`, it regenerates the `.json` files under `_meta/testdata`. For `-update_expected`, it regenerates the `.expected` files under `_meta/test`. For this enhancement, the goal is to use one flag `-generate` to generate/update all files. So `-data` and `-update_expected` can be deprecated later.

It would be nice to have a common package for all kinds of test helpers so they reuse the logic to decide if files should be regenerated.

**Comment by jsoriano** [comment]
`-data` is documented in the devguide and in the checklist of the issue template for new modules, so I would go for it, and deprecate the others.

**Comment by mtojek** [comment]
PRs merged, resolving.
