### ISSUE TITLE
[Metricbeat] Investigate on adding AccountID in aws module

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#13551]
AccountID will be very useful to have when users run metricbeat with more than one set of aws credentials from different accounts. Either account id or account name will be good to have. 

cc @sorantis 👍

**Comment by kaiyan-sheng** [comment]
@sorantis By looking at `add_cloud_metadata` https://www.elastic.co/guide/en/beats/metricbeat/current/add-cloud-metadata.html, I can see `cloud.account.id` under the AWS example is the actual id number, not the account name/alias. What do you think about adding both `cloud.account.id` and `cloud.account.name`? Will this work for infra-ui page?

**Comment by sorantis** [comment]
@kaiyan-sheng `cloud.account.id` doesn't look user friendly, and I wonder if the user would be able to distinguish between different cloud ids when they navigate AWS inventory? `cloud.account.name` sounds more like it for Infra UI. cc @simianhacker

**Comment by kaiyan-sheng** [comment]
@sorantis Yes `cloud.account.name` is definitely gonna be more user-friendly. But the account name/alias is optional I think for AWS so some accounts might not have a name. In that case, should the account name be the same as the account id instead? Or in the UI, we can put in the logic for `if account.name is empty, then uses account.id`?

**Comment by sorantis** [comment]
@kaiyan-sheng Makes sense, so to answer your first question, yes, we probably need both fields.
