### ISSUE TITLE
CPU Idle, CPU IOWait, CPU IRQ and CPU SoftIRQ also as a percentage

### ISSUE THREAD

**Issue by jaliph** [elastic/beats#1356]
Hi.. 

Can we have CPU Idle, CPU IOWait, CPU IRQ and CPU SoftIRQ also as a percentage value rather than CPU time. ??? This can be used for getting more regressive system CPU analysis.

It will be very helpful. 

Thanks

**Comment by andrewkroh** [comment]
@monicasarbu  Was this addressed by https://github.com/elastic/beats/pull/1705? Looks to me like that PR adds all these values.

**Comment by monicasarbu** [comment]
@andrewkroh yes, that's right. Thanks!
@jaliph Topbeat is replaced with Metricbeat in 5.0. Metricbeat gathers periodically metrics from external systems, and by default Metricbeat is collecting system statistics as Topbeat does. Their configuration files are similar, so you can easily migrate to Metricbeat. The feature that you are requesting is available in the system module of Metricbeat. Please have a look at the exported fields of Metricbeat: https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-system.html

**Comment by jaliph** [comment]
Thanks a lot for this... We will have our topbeat being replaced by metricbeat when we have a stable version of it.
