### ISSUE TITLE
Add tests for HTTP API server

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#13578]
Beats can spin up [an HTTP server](https://github.com/elastic/beats/blob/master/libbeat/api/server.go) to serve a few API endpoints. This API is currently untested. It would be nice to add some tests for this API, particularly asserting on the shape of it's responses, as other projects (Stack Monitoring, Fleet) start to rely on it.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
