### ISSUE TITLE
Wrong value for proc.cpu.total_p

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#1358]
Testing Topbeat (master version) on OSX, running the burn process.

![screen shot 2016-04-08 at 10 37 19 am](https://cloud.githubusercontent.com/assets/11757159/14378588/110aac8c-fd76-11e5-8ecd-d44064da8d67.png)

**Comment by andrewkroh** [comment]
Was there a resolution? Or was this not a bug? I have not seen this before.
