### ISSUE TITLE
[Filebeat] Support SQS notifications through SNS for S3 input

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#13585]
Current s3 input in Filebeat only support SQS as notification destination for S3 bucket. It will be good to add support for notifications from SNS to SQS as well.

**Comment by kedbirhan** [comment]
what is the status of  SNS support?. do we still have to use SQS notification for s3 input?

**Comment by kaiyan-sheng** [comment]
We have a PR in progress for this: https://github.com/elastic/beats/pull/25492

**Comment by christianherweg0807** [comment]
Hey @kaiyan-sheng. We currently investigating a possible solution without a change at the beats code.
See:
https://docs.aws.amazon.com/sns/latest/dg/sns-large-payload-raw-message-delivery.html

**Comment by kaiyan-sheng** [comment]
Thank you @christianherweg0807 ! We would still like to continue working on the PR you started it. Is that OK for you? Also do you mind contributing to our documentation on this solution without changing the beats code? cc @aspacca
