### ISSUE TITLE
[Heartbeat] Support for multiple status codes

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#13595]
Right now heartbeat assumes that a service has a single HTTP status code representing its up state. In [this forum thread](https://discuss.elastic.co/t/specifying-multiple-success-status-codes-for-heartbeat-monitor/198074/10) we found that isn't the case in the real world.

I propose we allow ` check.response.status` to take an array of codes as an argument to better handle this situation. While it's not ideal, this is a real situation operators may find themselves in.

**Comment by hjmwijnen** [comment]
+1 - is there currently any workaround?

**Comment by weedaj** [comment]
+1

**Comment by william20111** [comment]
+1 this would be useful. HA Vault cluster would give both a 200 if you hit the master or a 429 if you get a backup instance. As you say this is a requirement for some real world examples

**Comment by bartDecos** [comment]
+1

**Comment by andrewvc** [comment]
This was merged into our 7.x branch (targeting the 7.7 release) thanks to the awesome contribution from @amandahla in https://github.com/elastic/beats/pull/15587 . Thanks @amandahla !

**Comment by amandahla** [comment]
I’m glad I was able to help! :-)
