### ISSUE TITLE
Certificates with Agent and Fleet

### ISSUE THREAD

**Issue by ph** [elastic/beats#13591]
## Context

Private certificates are commonly generated to secure communication between beats and remote services like Logstash or Elasticsearch. In the current state of Libbeat when you setup your TLS certificate, The certificate need to be present on disk on the system. All the current TLS options expect one or more files to exist.

#### Central Management

When Central Management was created one of the major roadblock was the certificate usage. Because Central management did not have an option to send certificates to the running beats. The work around for our user was making sure the certificate was present on the machine and accessible by the running beats.

#### Fleet

Fleet is also managing remotely the agent and will also have to deal with the certificates.

## Proposal 1 for libbeat: Split two concerns

There are actually two kinds of sensitives information that a beats need to have to operate correctly:
 - One is key-values related, private keys, certificate, password or API keys for external this task is given to the keystores
 - Certificates Authority (CA, or certificate chain used to validates the remote certs)

In the context of other languages like Java we refers theses two contexts as: "Keystore", and "Truststore", Currently beats only support the former one. We should add a truststore in beats with a CLI tool to correctly generate it. Both the Keystore and the truststore could be a separates files on disk. And we should support having multiples files and allow the system to merge them.

Taking Filebeat as an example we could get something like this.

```
data/filebeat.keystore (Define Elasticsearch password, client certificate)
data/filebeat.trustore (Define CAs for verifying Elasticsearch)
```

**Required Changes for keystore** 
- Allow the Keystore to embed files as content of the key, files could be embedded using a `--stdin` flag.
    ` cat mycert | filebeat keystore add --stdin mycert`
- Allow the TLS options defined in the YAML configuration to accepts base64 data? (need investigation)
- Allow the *TLSConfig* and *ServerConfig* to accepts base64 for the certificates.

Using the above changes we could reference the certificate and the private key like this:

```yaml
output.elasticsearch:
  enabled: true
  hosts: ["localhost:9200"]
  ssl.certificate: ${ssl_cert}
  ssl.key: ${ssl_key}
  ```

**Required changes for having a truststore**

- We will need to changes the *tls.TLSConfig* struct and *tls.ServerConfig* to add support a truststore.
- The TLSConfig and ServerConfig will need to be able to use the truststore when creating the TLSOptions.

Now concerning the Truststore, there is a few ways we could deal with that.

1. We make the truststore global at the application level.

This mean, that all CA will be used everywhere to trust remote services.

Pro:
 - Simplicity, No need to reference them.
 - Possibly a single truststore.

Cons:
 - Remove the control where trust is established, IE: different trust store for a metricbeat HTTP module vs the Elasticsearch output.

2. We allow to reference the truststore to be used a the *TLSConfig* or *ServerConfig* level. Like the following:

```yaml
output.elasticsearch:
  enabled: true
  hosts: ["localhost:9200"]
  ssl.truststore: /tmp/truststore
  ssl.certificate: ${ssl_cert}
  ssl.key: ${ssl_key}
```

From the two options above the global truststore as defined in option 1 is probably the easiest way to implement or use.

## Proposal 2 for libbeat: Virtual file system

I think the cleaness way to define the CA or the certificate is to add support for file to keystore and create a truststore. Cleaness in the sense, it really represent what we are trying to achieve.

But, we could also have another way is to create a virtual file system in libbeat where path defined in the configuration would be file defined in the VFS. We could create a bunch FS help to either fetch the content on disk or on the VFS. Note that the VFS is mostly just a Key value store and we could reuse go-txfile library to build it.

```yaml
output.elasticsearch:
  enabled: true
  hosts: ["localhost:9200"]
  ssl.certificates_authorities: [${vfs:/ca1}, ${vfs:/ca2}]
  ssl.certificate: ${vfs:/certificate}
  ssl.key: ${ssl_key}
```

Pro:
  - The big advantages for the Proposal 2, is this work for everything that we could possibly need to bundle with beats.
 - We could add the content of the files as part of our checksum?
 - We could support encrypted VFS 

Cons:
 - Security might be an issue, but all solutions still requires us for now to load stuff in memory.

## Concerning Fleet

I think both proposal works well with Fleet, since we are just packaging additionals files.

## Risk

- How reloadable can affect beats, I believe that when a keystore changes or a truststore changes we might need to reload everything in beats to make sure we use the new settings, I am not sure the system will behave correctly unless we do that.

## Requirements to keep in mind.

High level requirements that need to be completed

- Allow the keystore to be reloadable
- Add support for Truststore
- Allow the truststore to be reloadable
- Allow TLS Options to accepts more than one type.

---

cc @mattapperson @urso @faec @michalpristas

**Comment by mattapperson** [comment]
I like proposal 2. It seems to have the best ergonomics too IMHO.
That said, I would ideally like to see this be a more holistic solution between agent and fleet too as an alternative to or replacement for an api key.

**Comment by ph** [comment]
Also, VFS, could only be read-only for now and we could support multiples VFS files as mount points.

**Comment by ph** [comment]
> I would ideally like to see this be a more holistic solution between agent and fleet too as an alternative to or replacement for an api key.

@mattapperson Did you think about the javascript processors in the context of fleet? That processors accepts both inline code and external code.

**Comment by ph** [comment]
After discussing with @urso we might to push the idea a little further.

1. Could we Merge the configuration, certificate and any other files into a single archive (zip?). This would help the functionbeat use case. The VFS could operate on the archive?

2. Instead of using ${} we could use URI scheme similar. So resolving the configuration is not dependant on the VFS. We will still provide Helpers to operate on the file. Here a few examples:

```
file:///var/beats.keystore
vfs://certf1
```

**Notes:**

Don't worry about the JS processor for now, we should force inline code instead.


@mattapperson Do you do you an early idea about how managing certificate would look like in the UI and how the worklow would be for the users?

- Users upload certificates?
- Fleet retrieve them somehow?

**Comment by ph** [comment]
I am going to close this, we do not plan at the moment to allow this.
