### ISSUE TITLE
[Metricbeat] NATS Module Compatibility

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#13599]
NATS 2.0.0 [introduced](https://github.com/nats-io/nats-server/releases/tag/v2.0.0) some breaking changes that might break the NATS module in Metricbeat. The change is related to the `/varz` endpoint used by Metricbeat for collecting server stats:

*For users embedding NATS Server and using Varz() to get server statistics should be aware of some changes described in https://github.com/nats-io/nats-server/pull/989*

In order to ensure that the NATS module works as intended, check compatibility with NATS 2.0.x and also update the Compatibility section in the documentation.

**Comment by ChrsMark** [comment]
Hi @sorantis! Thank you bringing this up. 

I did tested the NATS metricbeat module against a `nats:2.0.4` server locally.
Steps I followed:
1. Run a nats-server instance: `docker run -p 4222:4222 -ti nats:2.0.4`
2. Build metricbeat, enable nats module and start metricbeat

Seems that nothing is broken regarding `varz` (`stats` metricset of nats module). and here is what I get see in kibana:
```json
{
  "_index": "metricbeat-8.0.0-2019.09.11-000001",
  "_type": "_doc",
  "_id": "ZWiOIG0Bv25pKmQHkHbh",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2019-09-11T13:41:16.084Z",
    "ecs": {
      "version": "1.1.0"
    },
    "host": {
      "name": "Christoss-MacBook-Pro.local",
      "hostname": "Christoss-MacBook-Pro.local",
      "architecture": "x86_64",
      "os": {
        "build": "18G95",
        "platform": "darwin",
        "version": "10.14.6",
        "family": "darwin",
        "name": "Mac OS X",
        "kernel": "18.7.0"
      },
      "id": "883134FF-0EC4-5E1B-9F9E-FD06FB681D84"
    },
    "agent": {
      "ephemeral_id": "21f91253-5b38-47fa-bf17-c6dbcc2590f4",
      "hostname": "Christoss-MacBook-Pro.local",
      "id": "5f3351d8-7657-4320-8150-117d15f20557",
      "version": "8.0.0",
      "type": "metricbeat"
    },
    "metricset": {
      "period": 10000,
      "name": "stats"
    },
    "service": {
      "type": "nats",
      "address": "localhost:8222"
    },
    "event": {
      "dataset": "nats.stats",
      "module": "nats",
      "duration": 1603657
    },
    "nats": {
      "server": {
        "id": "NDNB2DZI347MEHRESTF525IJYV7XDH55PEKNF6EZEMEFR3C5ZLEBPCQU",
        "time": "2019-09-11T13:41:16.1121289Z"
      },
      "stats": {
        "cores": 8,
        "cpu": 0,
        "remotes": 0,
        "mem": {
          "bytes": 10223616
        },
        "in": {
          "messages": 0,
          "bytes": 0
        },
        "out": {
          "messages": 0,
          "bytes": 0
        },
        "uptime": 348,
        "total_connections": 0,
        "slow_consumers": 0,
        "http": {
          "req_stats": {
            "uri": {
              "root": 1,
              "connz": 13,
              "routez": 12,
              "subsz": 12,
              "varz": 14
            }
          }
        }
      }
    }
  },
  "fields": {
    "nats.server.time": [
      "2019-09-11T13:41:16.112Z"
    ],
    "@timestamp": [
      "2019-09-11T13:41:16.084Z"
    ]
  },
  "sort": [
    1568209276084
  ]
}
```

Last but not least, events from all metricsets are populated and the Kibana dashboard is loaded successfully:
![Screenshot 2019-09-11 at 16 49 49](https://user-images.githubusercontent.com/11754898/64703234-b822c900-d4b4-11e9-9e97-53e0ff89c0ba.png)

Let me know what you think!

**Comment by sorantis** [comment]
LGTM.
