### ISSUE TITLE
Extract fields from mbeans in Jolokia metricset

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#13604]
We could parse mbean identifiers so they can be more easily used for filtering and correlation, for example with the following mbean identifier:
```
kafka.log:type=Log,name=Size,topic=sometopic,partition=5
```
We could add something like this to the event:
```
"jmx": {
  "mbean": {
    "id": "kafka.log:type=Log,name=Size,topic=sometopic,partition=5"
    "name": "kafka.log",
    "property": {
      "type": "Log",
      "name": "Size",
      "topic": "sometopic",
      "partition": "5"
    }
  }
}
```

What in this example it could be used to more easily filter and correlate per topic or partition.

This would be specially useful when using wildcards, where mbeans cannot be so easily predicted.

**Comment by andresrc** [comment]
cc @sorantis
