### ISSUE TITLE
Consider leveraging KUBECONFIG for all our Kubernetes features

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#13648]
**Topic:**
Now that auto-detection has been introduced for `add_kuberentes_metadata` on https://github.com/elastic/beats/pull/13473, we should consider the use of KUBECONFIG for all Kubernetes features.
Currently only "in_cluster" configuration and user-provided `kube_config` are being taken into consideration. Consequently, `KUBECONFIG` detection in the system might be handy too.

Concerns, thoughts or possible approaches for this are more than welcome.

Related to k8s auto-detection: https://github.com/elastic/beats/issues/13068

cc: @jsoriano , @odacremolbap , @exekias

**Comment by exekias** [comment]
I understand you mean using `KUBCONFIG` env var if present. This makes sense to me! So clients would work with this priority:

1. If `kube_config` setting is present, use it. done
2. If `KUBECONFIG` env var is present, use it. done
3. Try autodetection

This is, in practice, like defaulting `kube_config` to `${KUBECONFIG}`
