### ISSUE TITLE
[metricbeat] [docker] Add support for all docker memory metrics

### ISSUE THREAD

**Issue by unixsurfer** [elastic/beats#13664]
**Describe the enhancement:**
The number of metrics that `docker.memory` exposes , see below, are much more than beats [exposes](https://www.elastic.co/guide/en/beats/metricbeat/6.8/exported-fields-docker.html#_memory_fields_2). Can we fill the gap?
```
% sudo curl -s --unix-socket /var/run/docker.sock http:/containers/foobar/stats?stream=false|jq '.memory_stats'
{
  "usage": 4294901760,
  "max_usage": 4294967296,
  "stats": {
    "active_anon": 2069188608,
    "active_file": 82817024,
    "cache": 1692340224,
    "dirty": 28672,
    "hierarchical_memory_limit": 4294967296,
    "hierarchical_memsw_limit": 4294967296,
    "inactive_anon": 534294528,
    "inactive_file": 1608601600,
    "mapped_file": 51642368,
    "pgfault": 5677437,
    "pgmajfault": 22074,
    "pgpgin": 852739845,
    "pgpgout": 851691285,
    "rss": 2602561536,
    "rss_huge": 0,
    "total_active_anon": 2069188608,
    "total_active_file": 82817024,
    "total_cache": 1692340224,
    "total_dirty": 28672,
    "total_inactive_anon": 534294528,
    "total_inactive_file": 1608601600,
    "total_mapped_file": 51642368,
    "total_pgfault": 5677437,
    "total_pgmajfault": 22074,
    "total_pgpgin": 852739845,
    "total_pgpgout": 851691285,
    "total_rss": 2602561536,
    "total_rss_huge": 0,
    "total_unevictable": 0,
    "total_writeback": 0,
    "unevictable": 0,
    "writeback": 0
  },
  "limit": 4294967296
}
```

**Describe a specific use case for the enhancement or feature:**
It will improve observability as we will get more information about the state and behavior of a container.

**Comment by ChrsMark** [comment]
> **Describe the enhancement:**
> The number of metrics that `docker.memory` exposes , see below, are much more than beats [exposes](https://www.elastic.co/guide/en/beats/metricbeat/6.8/exported-fields-docker.html#_memory_fields_2). Can we fill the gap?
Hey, the version of metricbeat you point to is `6.8`. I think that what you are looking for is to be included in `7.4` in which `memory.stats` will be included -> https://www.elastic.co/guide/en/beats/metricbeat/7.4/exported-fields-docker.html#_memory_2.
Here is what I can see running `7.4`:
```json
{
  "@timestamp": "2019-09-13T12:19:52.460Z",
  "@metadata": {
    "beat": "metricbeat",
    "type": "_doc",
    "version": "7.4.0"
  },
  "docker": {
    "memory": {
      "stats": {
        "total_active_file": 0,
        "total_pgfault": 2080,
        "total_writeback": 0,
        "hierarchical_memsw_limit": 9.223372036854772e+18,
        "total_pgpgin": 1659,
        "total_unevictable": 0,
        "unevictable": 0,
        "total_mapped_file": 36864,
        "hierarchical_memory_limit": 9.223372036854772e+18,
        "mapped_file": 36864,
        "pgfault": 2080,
        "total_inactive_anon": 2.342912e+06,
        "dirty": 0,
        "inactive_anon": 2.342912e+06,
        "rss_huge": 0,
        "total_pgmajfault": 1,
        "total_rss_huge": 0,
        "total_dirty": 0,
        "total_inactive_file": 36864,
        "active_file": 0,
        "cache": 36864,
        "inactive_file": 36864,
        "total_active_anon": 2.224128e+06,
        "total_rss": 4.56704e+06,
        "writeback": 0,
        "pgmajfault": 1,
        "rss": 4.56704e+06,
        "total_cache": 36864,
        "total_pgpgout": 535,
        "active_anon": 2.224128e+06,
        "pgpgin": 1659,
        "pgpgout": 535
      },
      "fail": {
        "count": 0
      },
      "limit": 2095378432,
      "rss": {
        "total": 4567040,
        "pct": 0.002179577650630318
      },
      "usage": {
        "max": 5300224,
        "total": 5054464,
        "pct": 0.0024121962519083524
      }
    }
  },...
}

```
> 
> **Describe a specific use case for the enhancement or feature:**
> It will improve observability as we will get more information about the state and behavior of a container.

Do you think that there is still something that is missing and you would like to be added? 🙂

**Comment by unixsurfer** [comment]
Yes 7.4 version has everything that is exposed by docker. But, in the documentation I don't see `dirty` and `mapped_file` metrics mentioned; I only checked those two. I only see ` docker.memory.stats.* ` mentioned and I guess it is about the  metrics from the `stats` key.

**Comment by ChrsMark** [comment]
Yes, these two are included! Actually all the stats will be dumped into the metricset.

cc: @fearful-symmetry
