### ISSUE TITLE
Possible wrong calculation of CPU percentage 

### ISSUE THREAD

**Issue by unixsurfer** [elastic/beats#13674]
While making some graphs about CPU usage for containers I noticed that the value for `docker.cpu.system.pct` metric was always **128**, see below.

```json
    "docker": {
      "container": {

[...snip...]
      },
      "cpu": {
        "total": {
          "pct": 0.8163001504950496
        },
        "user": {
          "ticks": 10512030000000,
          "pct": 0.5544554455445545
        },
        "kernel": {
          "ticks": 7535110000000,
          "pct": 0.07920792079207921
        },
        "system": {
          "ticks": 33178519540000000,
          "pct": 128
        }
      }
    },
```
`docker.cpu.system.pct` metric is about the CPU usage at the system level of the host and not of the container, but the value it didn't make any sense and it was a bit weird that it was always 128. So, I tried to find the source of the calculation and together with @jsoriano found that we always [multiple](https://github.com/elastic/beats/blob/v7.3.2/metricbeat/module/docker/cpu/helper.go#L151) with the number of CPUs. The interesting part and I think the source of the problem, is what we use in order to find the number of CPUs that a container has available for use.

We take the number of CPUs from a [struct](https://github.com/elastic/beats/blob/v7.3.2/metricbeat/module/docker/cpu/helper.go#L93) that maps to the key `percpu_usage` from the docker JSON returned by stats [API](https://github.com/elastic/beats/blob/v7.3.2/vendor/github.com/docker/docker/api/types/stats.go#L27). 

When we query docker stats API for that key we get the following array:

```bash
%  curl -s --unix-socket /var/run/docker.sock http:/containers/foobar/stats?stream=false|jq '.cpu_stats.cpu_usage.percpu_usage'
[
  1591462984321,
  1336900474783,
  1299519608293,
  1523505121665,
  1534929251305,
  1598895084015,
  1596303734884,
  1589933758050,
  1571067731181,
  3889800894763,
  1775123179858,
  2673055959624,
  1830111721572,
  1737517877489,
  1649620359282,
  1600884540589,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
]

```

Docker uses `cpuacct.usage_percpu` file to feed that array, which has 128 elements(there is one empty line thus 129 as result)

```bash
% cat /sys/fs/cgroup/cpu,cpuacct/docker/foobar/cpuacct.usage_percpu| tr ' ' '\n'|wc -l
129
```

So, we multiple all CPU metrics by 128. Why do we have 128 elements in this array? The host has 16 CPU cores and the container has available for use all those 16 CPUs as `CpusetCpus` docker config for the container is empty. According to [RedHat documentation about CPU Accounting (cpuacct) subsystem in cgroups](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/resource_management_guide/sec-cpuacct) and [kernel](https://www.kernel.org/doc/Documentation/cgroup-v1/cpuacct.txt) the array contains the CPU usage of all **tasks** of the cgroup.

So, I believe we do wrong calculations because we use an incorrect value for the number of CPUs. docker stats API exposes `online_cpus` which should be a safer way to extract the number of CPUs a container has available for use.

```bash
%  curl -s --unix-socket /var/run/docker.sock http:/containers/foobar/stats?stream=false|jq '.cpu_stats.online_cpus'
16
```
- Version: 6.3.2
- Operating System: Linux
- Discuss Forum URL: Discussed internally with @jsoriano 
- Steps to Reproduce: 
Enable `cpu` metricset of `docker` module and find a container where the length of `percpu_usage` in the JSON returned by docker stats API is not equal with the number of CPUs the container has available for use. The value of `docker.cpu.system.pct` will be equal with the length of the aforementioned array.

**Comment by jsoriano** [comment]
I agree with the proposal of using `online_cpus` for the number of CPUs.

**Comment by unixsurfer** [comment]
The proposal to use `online_cpus` turned out to be wrong because it is always set to the number of CPUs of the host and **not** to available CPUs for the container. For instance, on host with 8 CPUs we spin a container and limit the number of CPUs to 4
```bash
% docker run --name redis-slave-7 --cpuset-cpus="0-3" -d redis
```

`onlie_cpus` has 8 instead of 4. This is  because all CPUs are available to the docker but the scheduler decices which CPUs can be used.
```bash
%  curl -s --unix-socket /var/run/docker.sock http:/docker/containers/redis-slave-7/stats?stream=false|jq '.cpu_stats.online_cpus'
8
```

The only reliable way to retrieve the CPUs is to either from cgroup or from quering `inspect` API:
```
% docker exec redis-slave-7 cat  /sys/fs/cgroup/cpuset/cpuset.cpus
0-3

% cat /sys/fs/cgroup/cpuset/docker/c066acb9bc2b5624191da89a77fed780c7b4cd45662cdeafcaf92d1c68cf3d29/cpuset.cpus
0-3

%  curl -s --unix-socket /var/run/docker.sock http:/docker/containers/redis-slave-7/json|jq '.HostConfig.CpusetCpus'
"0-3"

```

According to docker [documentation](https://docs.docker.com/engine/api/v1.39/#operation/ContainerCreate) the ` CpusetCpus` accepts values in different formats, `0-3`,`1`, `0-2,3` and etc. So, parsing it could be a bit tricky. I guess we can use [ParseUintList()](https://github.com/docker/docker-ce/blob/91754bf4bad779b74fb4ca0256f4e11e3c93c556/components/engine/pkg/parsers/parsers.go#L39) function from docker code.

**Comment by jsoriano** [comment]
> The proposal to use online_cpus turned out to be wrong because it is always set to the number of CPUs of the host and not to available CPUs for the container.

This is the current expected behaviour, to calculate the percentage respect to the CPUs in the host machine, so I think that we are good to go with `online_cpus` solution by now, to at least fix this for the cases where the length of percpu metrics cannot be trusted.

I have to confess that I don't like percentages so much as metrics :slightly_smiling_face: Percentages are always tricky, because for its calculation some kind of total is needed and it is not always clear which one to use. Also in some cases it is more convenient to use normalized percentages and in others not normalized ones. It is always going to depend on the expected usage for the percentages.
In the system module we solved that by supporting different ways to calculate the percentages, and we have an open issue to have something similar in the docker module: https://github.com/elastic/beats/issues/13343, we could add another calculation for "capacity", that only takes into account the assigned resources, I wonder if for that we should also consider the cpu shares apart of the cpu set (yet another variable to the percentages calculation :slightly_smiling_face: ).

Also notice that another option for percentages, as with other calculated fields, is to calculate them at query time, for that we would need to collect fields with the possible "totals" (CPUs in the host, number of available CPUs, CPU shares, and so on).

**Comment by unixsurfer** [comment]
> > The proposal to use online_cpus turned out to be wrong because it is always set to the number of CPUs of the host and not to available CPUs for the container.
> 
> This is the current expected behaviour, to calculate the percentage respect to the CPUs in the host machine, so I think that we are good to go with `online_cpus` solution by now, to at least fix this for the cases where the length of percpu metrics cannot be trusted.
> 

It only fixes the cases where we don't set  `CpusetCpus` container setting, but it doesn't fix the case where a user sets the aforementioned docker setting and for this case we do the wrong calculation.


> I have to confess that I don't like percentages so much as metrics slightly_smiling_face Percentages are always tricky, because for its calculation some kind of total is needed and it is not always clear which one to use. Also in some cases it is more convenient to use normalized percentages and in others not normalized ones. It is always going to depend on the expected usage for the percentages.
> In the system module we solved that by supporting different ways to calculate the percentages, and we have an open issue to have something similar in the docker module: #13343, we could add another calculation for "capacity", that only takes into account the assigned resources, I wonder if for that we should also consider the cpu shares apart of the cpu set (yet another variable to the percentages calculation slightly_smiling_face ).
> 
> Also notice that another option for percentages, as with other calculated fields, is to calculate them at query time, for that we would need to collect fields with the possible "totals" (CPUs in the host, number of available CPUs, CPU shares, and so on).

I am fine with normalized metrics, but don't we still need to use the correct number of CPUs?
