### ISSUE TITLE
Support for macros in file names (like syslog-ng)

### ISSUE THREAD

**Issue by tajohnson** [elastic/beats#1367]
Syslog-ng has a great feature - the ability to create log file names based on things like the year, month, date:

`
destination d_sorted { file("/var/log/remote/${YEAR}_${MONTH}_${DAY}.log" create-dirs(yes)); }
`
or even

`
destination d_sorted { file("/var/log/remote/${YEAR}/${MONTH}/${DAY}/something.log" create-dirs(yes)); }
`

This allows logs to be "rotated" without ever having to stop or reload syslog-ng.

It would be great to have support for this in filebeat prospectors.

**Comment by ruflin** [comment]
You can configure filebeat with globs to fetch all these files. For the first on it would be:

`/var/log/remote/*.log`

Second example is:

`/var/log/remote/*/*/*/something.log`

Is there a specific issue having it like this?

**Comment by tajohnson** [comment]
My mistake - I had a bad setting in the scan_frequency parameter so that I didn't see filebeat picking up the new files, and assumed that it would require a restart or reload to open new log files.
