### ISSUE TITLE
Socket support for Metricbeat memcached module

### ISSUE THREAD

**Issue by aaalekseev** [elastic/beats#13685]
Add support for connection via socket to memcached.

Socket is more performant way of memcached usage and is popular in large-scale installations. 
At this moment only http-connection to memcached is supported in Metricbeat module. 

It would be great socket connection support for covering all the cases without additional proxy-layers.

**Comment by PanovAlexey** [comment]
Good idea!
We need it too.

**Comment by mtojek** [comment]
Resolving.
