### ISSUE TITLE
[Heartbeat] For an HTTPS monitor heartbeat doesn't capture expired ssl certificate information

### ISSUE THREAD

**Issue by shahzad31** [elastic/beats#13687]
**Heartbeat HTTPS Monitor Expired SSL Certificate information:**

while working in Uptime app, if a monitor is an https, we are displaying it's ssl information in overview page 
![image](https://user-images.githubusercontent.com/3505601/64935355-3e9b2a00-d86a-11e9-8855-6f5e1d10fc1f.png)

while heartbeat captures information when the ssl certificate is going to expire, it doesn't capture if the certificate is already expired. In that case we should be able to capture information when the certificate got expired. Usually when visiting any expired ssl site, chrome is able to display information that certificate got expired on such data. So it might be possible as well in heartbeat agent to capture that information.

this is also discussed in
https://github.com/elastic/kibana/pull/45613

**Comment by andrewvc** [comment]
Re-opening this as the prior PR didn't actually fix this. This isn't an easy item to fix as golang doesn't want to provide metadata about connections that are invalid.

**Comment by Pupkur** [comment]
In addition. I`m renew certificate ~10h ago.
Heartbeat shows:
tls.certificate_not_valid_after | Feb 11, 2020 @ 08:07:06.000
Browser info about certificate:
Expires On	Tuesday, April 28, 2020 at 4:53:34 PM

**Comment by shahzad31** [comment]
This has been fixed in https://github.com/elastic/beats/pull/17687
