### ISSUE TITLE
Packetbeat: transactions are dropped without notification

### ISSUE THREAD

**Issue by McStork** [elastic/beats#1368]
In Packetbeat, if too many transactions are created and not outputed fast enough, they are dropped ([see Packetbeat publisher](https://github.com/elastic/beats/blob/2f48f37cf91fce251b4af8484fe281d210f98f54/packetbeat/publish/publish.go#L53-L61)).

There should be a log message that let know the user that transactions are dropped because of insufficient values in his current configuration options.
For example, if there are transactions dropped during a 1 second window, a log message could be displayed. User could then increase values of output options (number of workers, bulk size, ...), or increase the [queue size](https://www.elastic.co/guide/en/beats/packetbeat/current/configuration-shipper.html#_queue_size) value to buffer more transactions, at the cost of more memory usage.

**Comment by McStork** [comment]
This might happen in other Beats I guess.
Also, it might relate to issue https://discuss.elastic.co/t/packetbeat-performance/46834.

**Comment by monicasarbu** [comment]
I think @urso is the best person to answer here.

**Comment by urso** [comment]
If packetbeat is under heavy load we should not log too much, as this can slow down packetbeat even more.
Packetbeat has queue metrics for when events are being dropped. But some more detailed metrics per protocol would be nice to have. Like pending requests/response, drops, and such.
