### ISSUE TITLE
Metricbeat - RabbitMQ Module - export connection "state" field

### ISSUE THREAD

**Issue by chandra2037** [elastic/beats#13697]
Metricbeat
Module: RabbitMQ
Metricset: connection

Right now, Metricbeat not exporting [RabbitMQ connection](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-rabbitmq.html#_connection_2) "state" information.  This field is available under RabbitMQ GET "/api/connections" [endpoint](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.17/priv/www/api/index.html). And can be stored under "rabbitmq.connection.state" field

state value can be Running, Flow, Blocked or others.  

"state" field will be useful for 
-recognizing any throttled connections
-notifying for any blocked connections

I can provide more details if needed.

Thank you

**Comment by amandahla** [comment]
If it's ok, I'll try this :)

**Comment by kaiyan-sheng** [comment]
@amandahla Yes, please feel free to assign this to yourself and create a PR against master branch. Thanks for contributing!

**Comment by odacremolbap** [comment]
closing due to #13981
