### ISSUE TITLE
Puppet / Chef / Ansible / Salt / etc. modules

### ISSUE THREAD

**Issue by tsg** [elastic/beats#137]
It's important for Packetbeat to have really good configuration management support, to reduce the effort for the people that want to use it in production.

**Comment by NITEMAN** [comment]
A proper repository for the main distributions will for sure help a lot

**Comment by tsg** [comment]
@NITEMAN we know, it's definitely planned, we just didn't have time for this first release.

**Comment by varac** [comment]
Hej, wonder what's the state of this - I'm looking for a metricbeat puppet module.

**Comment by smasa90** [comment]
There is some work for puppet here,
https://github.com/elastic/puppet-beats
but how can we ping relevant people to push work from community ?
