### ISSUE TITLE
[Winlogbeat] Fails to start with default config having 

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#13705]
Winlogbeat fails to start with the default configuration file after https://github.com/elastic/beats/pull/13473. There's an error with the `add_kubernetes_metadata` processor. @ChrsMark can you please take a look at this issue.

> Failed to initialize 'export' command: error initializing processors: Can not initialize kubernetes plugin with zero matcher plugins.

For confirmed bugs, please report:
- Version: winlogbeat version 8.0.0 (amd64), libbeat 8.0.0 [ef177a6292863a44c35d7e3dd08db34bb9eda5fd built 2019-09-16 21:08:35 +0000 UTC]
- Operating System: Windows / Darwin
- Steps to Reproduce: Download Winlogbeat, Run `./winlogbeat export template -e` (or without the subcommand)

**Comment by ChrsMark** [comment]
Hi @andrewkroh and thank you for reporting this!

As far as I can see, the problem with Beats other than Filebeat and Metricbeat is that they do not have default matchers. In the docs is mentioned that Filebeat enables logs_path matcher by default (Metricbeat, enables field matcher).

I'm not sure if we should add default matchers for all other Beats.
I think that ignoring that error and just disable the processor should be ok.
I wonder if this should had make the CI to fail 🤔 .

**Comment by ChrsMark** [comment]
> After double-thinking about this and my comment in [#13709 (review)](https://github.com/elastic/beats/pull/13709#pullrequestreview-289100760), I would propose to do this:
> 
> * Go on with #13709, this would be in any case needed as part of #13473, as this is another error that could be logged but ignored like the ones for client configuration.

+1 for this.

> * Add some condition to the configuration file template, like [the one used for `add_observer_metadata`](https://github.com/elastic/beats/blob/v7.3.2/libbeat/_meta/config.yml.tmpl#L90), so `add_kubernetes_metadata` is only added by default to the configurations of beats with indexers and matchers.
> * Add a dummy implementation of `add_docker_metadata` and `add_kuberentes_metadata` for platforms without docker support (see #13509) that only prints an info message about these processors not being available in current platform.
> * Add system tests that test beats with the default configurations, so we prevent this kind of regressions to happen in the future.
> 

We could open different issues for them, to track them down. 

> They could be done in different PRs.
> 

I will go along with accepting #13709 to resolve this blocking issue, and after that to open follow-up issues for the rest 3 points of @jsoriano.

> @ChrsMark @andrewkroh, what do you think?
