### ISSUE TITLE
[Filebeat] Add support for AWS CloudWatch logs

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#13716]
The goal of this issue is to create a filebeat fileset to support AWS CloudWatch logs. Depends on the CloudWatch logs type, there might be some additional work on the s3 input needs to be done first.

## Filebeat module

* [ ] Test log files exist for the grok patterns
* [ ] Generated output for at least 1 log file exists

**Comment by exekias** [comment]
Hi @kaiyan-sheng could you add a little more detail about what this issue is about?

- How do you plan to get these logs?
- Is there any useful link to AWS docs on this?

**Comment by kaiyan-sheng** [comment]
@exekias Yes will do!
