### ISSUE TITLE
[Metricbeat][Docker] Consider adding more metrics for `cpu` metricset

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#13726]
**Describe the enhancement:**
Currently we have metrics like `docker.cpu.*.pct` and `docker.cpu.*.norm.pct` for the cpu monitoring. As mentioned on https://github.com/elastic/beats/pull/13695 and on https://github.com/elastic/beats/issues/13674 we would like to be able to expose the data to calculate percentages in the events, so custom percentages can be calculated on query time. 
So we could consider adding:

- Available cpus
- metric about available memory (?)
- CPU shares
- CpusetCpus
- ...

**Describe a specific use case for the enhancement or feature:**
As discussed in https://github.com/elastic/beats/pull/13695 and https://github.com/elastic/beats/issues/13674 the metrics we have can be a bit counterintuitive in some cases. So by adding these extra metrics will help us calculating them at query time.

@jsoriano and @unixsurfer feel free to comment and/or add anything that might be missing!

**Comment by fearful-symmetry** [comment]
So, it looks like the only thing we're not sending that's needed to calculate usage pct as metricbeat does is the count of online CPUs, which is pretty easy.

After the PR I made that dumps most of the cgroup data, we're sending almost all the memory data that's available.
