### ISSUE TITLE
[Metricbeat] Update documentation to `testdata` testing feature

### ISSUE THREAD

**Issue by sayden** [elastic/beats#13735]
After this https://github.com/elastic/beats/pull/11818 this README.md file wasn't update with the new functionality https://github.com/elastic/beats/blob/master/metricbeat/mb/testing/data/README.md

Plus the mage target doesn't seem to be correct now https://github.com/elastic/beats/blob/master/metricbeat/magefile.go#L123

**Comment by andresrc** [comment]
Maybe we should also move this from a README in some deep path of the repo to the development guide.
