### ISSUE TITLE
Update documentation with document_id

### ISSUE THREAD

**Issue by urso** [elastic/beats#13739]
PR elastic/beats#5844 adds the new document_id setting for json decoding. This configures the field in the JSON document, that is read into `@metadata.id`.

The elasticsearch output sets the document id `@metadata.id` if present and uses the create operation -> if ID exists already, event is not indexed again.

For other outputs the `@metadata.id` field is added to the event so it can be used by logstash.

The original PR mentions the new setting, but we have to add some more documentation about the impact.

**Comment by dedemorton** [comment]
We need to add a topic (all under the umbrella of de-duplication) that describes the various ways to configure document IDs: ES chooses, via JSON input, random, fingerprinting,

**Comment by urso** [comment]
@ycombinator fyi
