### ISSUE TITLE
Filebeat missing log lines.

### ISSUE THREAD

**Issue by paritosh16** [elastic/beats#1374]
I have filebeat up and running. My configuration looks something like 

    filebeat:
      prospectors:
        -
          paths:
            - /home/abc/access.log.2016*
          input_type: log
          ignore_older: 24h
          document_type: access
        -
          paths:
            - /home/abc/console.log.2016*
          input_type: log
          document_type: console
          ignore_older: 24h
      registry_file: /var/lib/filebeat/registry
    output:
      logstash:
        hosts: ["localhost:5044"]
    logging:
      files:
        path: /var/log/mybeat
        name: mybeat
        rotateeverybytes: 10485760 # = 10MB
      level: debug

Filebeat misses out on some of the logs at random. I haven't seen any pattern as such as far as missing logs are concerned.

I know this is abnormal and any help is appreciated.

**Comment by ruflin** [comment]
Can you please provide all the data that was requested when you created the issue?

```
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For confirmed bugs, please report:
- Version: 
- Operating System: 
- Steps to Reproduce: 
```

I would suggest to move this discussion for to discuss to figure out more details about the issue so we can confirm if it is a bug or not: https://discuss.elastic.co/c/beats/filebeat Can you please open a new topic there with all the details?

**Comment by ruflin** [comment]
Closing this one as no update. @paritosh16 In case you still have the problem, please open a topic on https://discuss.elastic.co/c/beats/filebeat
