### ISSUE TITLE
Allow to configure max internal queue size in bytes [filebeat]

### ISSUE THREAD

**Issue by flexoid** [elastic/beats#13740]
**Describe the enhancement:**

Currently, the only way to configure internal queue size is to set max event count (as described [here](https://www.elastic.co/guide/en/beats/filebeat/current/configuring-internal-queue.html))

```yaml
queue.mem:
  events: 4096
```

In case of varying size of the events, it is very hard to predict filebeat memory consumption, which is very dangerous as filebeat usually runs on the same node with the production app.

For example, [fluentd](https://docs.fluentd.org/configuration/buffer-section#buffering-parameters) have such a thing as `total_limit_size`.

What I propose for example:

```yaml
queue.mem:
  events: 4096
  max_bytes: 10485760 # 10Mb
```

**Describe a specific use case for the enhancement or feature:**

We had a disaster on our production env. Usually, log events are small (~3K), and it is reasonable to have a large queue size (4096 by default). But that time we unexpectedly received multiple very heavy events (1-3Mb each), which consumed all the available memory on the host. Definitely there should be a way to be protected from such a scenario.

**Comment by m00lecule** [comment]
Bump - I would also appreciate this configuration option
