### ISSUE TITLE
Prometheus untyped metrics with NaN value generate incorrect events

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#13750]
If a metric with `untyped` type has `NaN` as value, it generates incorrect events. We should apply https://github.com/elastic/beats/pull/12084 also to metrics with `untyped` metrics.

This Prometheus response reproduces the issue:
```
# TYPE net_conntrack_listener_conn_closed_total untyped
net_conntrack_listener_conn_closed_total{listener_name="http"} NaN 1568652315554
```

**Comment by kaiyan-sheng** [comment]
Oh no, this is missed by my previous pr. I will take it and push a pr to fix this.
