### ISSUE TITLE
Filebeat Netflow Module - flow_start_microseconds Not Being Parsed Properly

### ISSUE THREAD

**Issue by ankurthuse** [elastic/beats#13769]
Hi,

Filebeat Netflow module ingesting IPFIX data from Cisco Netscaler is not able to parse  flow_start_microseconds correctly. The first flow record into elasticsearch is setting the flow_start_microseconds to "long" type and when flow data with this field set to "date" is encountered, there is a parsing error and the data is dropped. 

Example of error: 
```
{"type":"mapper_parsing_exception","reason":"failed to parse field [netflow.flow_start_microseconds] of type [long] in document with id 'xxx'. 
Preview of field's value: '2019-09-17T04:10:43.000Z'","caused_by":{"type":"illegal_argument_exception","reason":"For input string: \"2019-09-17T04:10:43.000Z\""}}
```

First record setting the field as Long as the value below: 
```
flow_start_microseconds" : 6998680046697597780
```
If more information is required, please reach out to me internally. 

Regards,

Ankur Thuse

**Comment by andrewkroh** [comment]
Would it be possible to provide a sample of the netflow traffic in PCAP format to help reproduce the issue and test? Like a sample collected via `tcpdump -i eth0 -w cisco_netscaler_netflow.pcap udp port 2055`.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
