### ISSUE TITLE
Have mage derive doc-branch from stack-version

### ISSUE THREAD

**Issue by jalvz** [elastic/beats#13765]
Docs team is on a quest to simplify docs releases, for which they are moving towards managing all versions from one [file](https://github.com/elastic/docs/blob/master/shared/versions/stack/master.asciidoc) per release.

This [change](https://github.com/elastic/apm-server/commit/aa971e1b46e62ecf3395be5ec8713fc8886095d0) in apm-server broke the release target, as the `doc-branch` attribute is not only on another file, but also on a different repo, and it needs to be resolved substituting asciidoc variables.

This problem was encountered in apm-server only, but beats was planning to follow up and they will find the same limitation. 

I _think_ we can get around that by instructing mage to derive the `doc-branch` attribute from the `stack-version` attribute, which if I am not wrong, is the same minus the patch.

Does that make sense @andrewkroh @kvch ?

**Comment by jalvz** [comment]
cc @bmorelli25 @dedemorton

**Comment by nik9000** [comment]
@jalvz Could you point me to where you use the doc-branch attribute? I'd be happy to help brainstorm from the docs side.

**Comment by jalvz** [comment]
I actually don't know, it is used in Beats here: https://github.com/elastic/beats/blob/f6629a8ddc3c76493933ee9c5aabe0194c1feeef/dev-tools/mage/settings.go#L364, but didn't dig into what for.

It could be the case that is not needed for apm-server at all...

**Comment by nik9000** [comment]
> It could be the case that is not needed for apm-server at all...

I think it is important to figure out what it is used for so we can link to it properly. I imagine it has to do with linking to your own docs.

**Comment by andrewkroh** [comment]
Beats uses `{{beat_doc_branch}}` in in URLs that link to the docs. It puts a URL in the [README](https://github.com/elastic/beats/blob/2f5b81694a2993b1ad4badc79f86261ac7c109da/dev-tools/packaging/templates/common/README.md.tmpl#L27) that's included in packages. And it's used links to the docs that are added to `modules.d/` [files](https://github.com/elastic/beats/blob/2f5b81694a2993b1ad4badc79f86261ac7c109da/metricbeat/modules.d/aerospike.yml.disabled#L2).

**Comment by dedemorton** [comment]
Wanted to note here that the beats documentation uses the local version file to resolve other attributes (like `go-version`). We will need to continue maintaining the local file regardless of how we get the stack version.
