### ISSUE TITLE
[Filebeat] Add support for more IIS log file formats

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#13799]
Right now, iis module seems to only support W3C Extended Log File Format with different versions. Based on Microsoft documentation 
https://docs.microsoft.com/en-us/previous-versions/iis/6.0-sdk/ms525807(v%3Dvs.90), there are other log formats like IIS Log File Format and NCSA Common Log File Format will be useful too. 

IIS Log File Format example:
192.168.114.201, -, 03/20/01, 7:55:20, W3SVC2, SALES1, 172.21.13.45, 4502, 163, 3223, 200, 0, GET, /DeptLogo.gif, -, 
172.16.255.255, anonymous, 03/20/01, 23:58:11, MSFTPSVC, SALES1, 172.16.255.255, 60, 275, 0, 0, 0, PASS, /Intro.htm, -,

NCSA Common Log File Format example:
172.21.13.45 - Microsoft\fred [08/Apr/2001:17:39:04 -0800] "GET /scripts/iisadmin/ism.dll?http/serv HTTP/1.0" 200 3401

**Comment by philippkahr** [comment]
Hi,

I recently stumbled across the IIS plugin and I am using it in conjunction with Microsoft Exchange. The logs from IIS in combination with Exchange look a bit more different because Exchange puts a lot of fields inside the IIS. 

Here are some log messages and a working GROK pattern. I tested the grok pattern using the Kibana Grok analyzer inside the dev tools.

```log
2019-10-20 15:13:55 POST /Microsoft-Server-ActiveSync/default.eas Cmd=Ping&User=philipp.kahr&DeviceId=9c731cc0e9fe8798783cb57e5977edd5e&DeviceType=Outlook&CorrelationID=<empty>;&ClientId=MJKNJEDEUJUUUID&cafeReqId=896c4201-8uue-489c-b193-f1e73aa6287a; - 212.166.112.250 Outlook-iOS-Android/1.0 - 200
```
<details><summary>Grok filter 1</summary>
<p>
Example Grok Pattern, I cannot figure out how to skip `-`character, so I put it inside a field called `drop`.
```grok
%{TIMESTAMP_ISO8601:iis.access.time} %{WORD:http.request.method} %{URIPATH:url.path} %{NOTSPACE:url.query} %{NOTSPACE:drop} %{IPORHOST:source.address} %{NOTSPACE:user_agent.original} %{NOTSPACE:drop} %{NUMBER:http.response.status_code:long}
```
Result
```json
{
  "drop": "-",
  "iis": {
    "access": {
      "time": "2019-10-20 15:13:55"
    }
  },
  "http": {
    "request": {
      "method": "POST"
    },
    "response": {
      "status_code": 200
    }
  },
  "source": {
    "address": "212.166.112.250"
  },
  "user_agent": {
    "original": "Outlook-iOS-Android/1.0"
  },
  "url": {
    "path": "/Microsoft-Server-ActiveSync/default.eas",
    "query": "Cmd=Ping&User=philipp.kahr&DeviceId=9c731cc0e9fe8798783cb57e5977edd5e&DeviceType=Outlook&CorrelationID=<empty>;&ClientId=MJKNJEDEUJUUUID&cafeReqId=896c4201-8uue-489c-b193-f1e73aa6287a;"
  }
}
```
</p>
</details>

```log
2019-10-20 15:13:56 POST /mapi/emsmdb/ MailboxId=3c5a09e2-u9u9-4451-b1b6-21dd29813d3f@example.com&CorrelationID=<empty>;&ClientId=FBLAXEWQEITNKQWERFFLG&ClientRequestInfo=R:{F66F1938-D99D-43F6-QWER-93FEF763BBCF}:22444;CI:{B2939AE0-65A7-1234-BD08-4FF5F68CA673}:19;RT:Execute&cafeReqId=bac0dc43-d123-4d15-8c47-436651764660; EXAMPLE\philippkahr 84.112.190.213 Microsoft+Office/16.0+(Windows+NT+10.0;+Microsoft+Outlook+16.0.4849;+Pro) ClientId=FBLAXEWQWERNKCPORFFLG;MapiContext=MAPIAAAAAPaj+99+yf7d79/u1/rK8t/u7u7/MbyxP7N9a+MtYazgrOKuYu8Bw0zAAAAAAA=;MapiSequence=22364-xw+vIA==;X-BackEndCookie=3c5a09e2-u8u8-4451-b1b6-21dd29813d3f=u56Lnp2ejJqBnsibxseeyJzSy8jMydLLxsrN0sedyJzSz87OmpudysnLmZvKgYHNz87G0s7O0s7Gq87Kxc7MxcrJ 200
```

<details><summary>Grok filter 2</summary>
<p>
I am not quite sure if `url.param` is the best field to place this information `ClientId=FBLAXEWQWERNKCPORFFLG;MapiContext=MAPIAAAAAPaj+99+yf7d79/u1/rK8t/u7u7/MbyxP7N9a+MtYazgrOKuYu8Bw0zAAAAAAA=;MapiSequence=22364-xw+vIA==;X-BackEndCookie=3c5a09e2-u8u8-4451-b1b6-21dd29813d3f=u56Lnp2ejJqBnsibxseeyJzSy8jMydLLxsrN0sedyJzSz87OmpudysnLmZvKgYHNz87G0s7O0s7Gq87Kxc7MxcrJ`
```grok
%{TIMESTAMP_ISO8601:iis.access.time} %{WORD:http.request.method} %{URIPATH:url.path} %{NOTSPACE:url.query} %{NOTSPACE:user.name} %{IPORHOST:source.address} %{NOTSPACE:user_agent.original} %{NOTSPACE:url.param} %{NUMBER:http.response.status_code:long}
```
```json
{
  "iis": {
    "access": {
      "time": "2019-10-20 15:13:56"
    }
  },
  "http": {
    "request": {
      "method": "POST"
    },
    "response": {
      "status_code": 200
    }
  },
  "source": {
    "address": "84.112.190.213"
  },
  "user": {
    "name": "EXAMPLE\\philippkahr"
  },
  "user_agent": {
    "original": "Microsoft+Office/16.0+(Windows+NT+10.0;+Microsoft+Outlook+16.0.4849;+Pro)"
  },
  "url": {
    "path": "/mapi/emsmdb/",
    "param": "ClientId=FBLAXEWQWERNKCPORFFLG;MapiContext=MAPIAAAAAPaj+99+yf7d79/u1/rK8t/u7u7/MbyxP7N9a+MtYazgrOKuYu8Bw0zAAAAAAA=;MapiSequence=22364-xw+vIA==;X-BackEndCookie=3c5a09e2-u8u8-4451-b1b6-21dd29813d3f=u56Lnp2ejJqBnsibxseeyJzSy8jMydLLxsrN0sedyJzSz87OmpudysnLmZvKgYHNz87G0s7O0s7Gq87Kxc7MxcrJ",
    "query": "MailboxId=3c5a09e2-u9u9-4451-b1b6-21dd29813d3f@example.com&CorrelationID=<empty>;&ClientId=FBLAXEWQEITNKQWERFFLG&ClientRequestInfo=R:{F66F1938-D99D-43F6-QWER-93FEF763BBCF}:22444;CI:{B2939AE0-65A7-1234-BD08-4FF5F68CA673}:19;RT:Execute&cafeReqId=bac0dc43-d123-4d15-8c47-436651764660;"
  }
}
```
</p>
</details>

I would also have one additional request/suggestion. Maybe using the `KV Processor` from elasticsearch could help with splitting the data inside `url.query` into something more useful. I tested it with the simulate API and my first example, there it would work perfectly. I did not do any mapping to correct fields I just dumped them inside `kvsplitted`. Here is my simulate pipeline:

```json
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "description": "_description",
    "processors": [
      {
        "grok":{
          "field": "message",
          "patterns":[
            "%{TIMESTAMP_ISO8601:iis.access.time} %{WORD:http.request.method} %{URIPATH:url.path} %{NOTSPACE:url.query} %{NOTSPACE:drop} %{IPORHOST:source.address} %{NOTSPACE:user_agent.original} %{NOTSPACE:drop} %{NUMBER:http.response.status_code:long}"
            ]
        },
        "kv": {
          "field_split": "&",
          "value_split": "=",
          "field": "url.query",
          "target_field": "kvsplitted",
          "ignore_failure": true
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "index",
      "_id": "id",
      "_source": {
        "message": "2019-10-20 15:13:55 POST /Microsoft-Server-ActiveSync/default.eas Cmd=Ping&User=philipp.kahr&DeviceId=9c731cc0e9fe8798783cb57e5977edd5e&DeviceType=Outlook&CorrelationID=<empty>;&ClientId=MJKNJEDEUJUUUID&cafeReqId=896c4201-8uue-489c-b193-f1e73aa6287a; - 212.166.112.250 Outlook-iOS-Android/1.0 - 200"
      }
    }
  ]
}
```
and the example result:
```json
{
  "docs" : [
    {
      "doc" : {
        "_index" : "index",
        "_type" : "_doc",
        "_id" : "id",
        "_source" : {
          "drop" : "-",
          "iis" : {
            "access" : {
              "time" : "2019-10-20 15:13:55"
            }
          },
          "http" : {
            "request" : {
              "method" : "POST"
            },
            "response" : {
              "status_code" : 200
            }
          },
          "source" : {
            "address" : "212.166.112.250"
          },
          "message" : "2019-10-20 15:13:55 POST /Microsoft-Server-ActiveSync/default.eas Cmd=Ping&User=philipp.kahr&DeviceId=9c731cc0e9fe8798783cb57e5977edd5e&DeviceType=Outlook&CorrelationID=<empty>;&ClientId=MJKNJEDEUJUUUID&cafeReqId=896c4201-8uue-489c-b193-f1e73aa6287a; - 212.166.112.250 Outlook-iOS-Android/1.0 - 200",
          "kvsplitted" : {
            "DeviceType" : "Outlook",
            "User" : "philipp.kahr",
            "DeviceId" : "9c731cc0e9fe8798783cb57e5977edd5e",
            "ClientId" : "MJKNJEDEUJUUUID",
            "Cmd" : "Ping",
            "CorrelationID" : "<empty>;",
            "cafeReqId" : "896c4201-8uue-489c-b193-f1e73aa6287a;"
          },
          "user_agent" : {
            "original" : "Outlook-iOS-Android/1.0"
          },
          "url" : {
            "path" : "/Microsoft-Server-ActiveSync/default.eas",
            "query" : "Cmd=Ping&User=philipp.kahr&DeviceId=9c731cc0e9fe8798783cb57e5977edd5e&DeviceType=Outlook&CorrelationID=<empty>;&ClientId=MJKNJEDEUJUUUID&cafeReqId=896c4201-8uue-489c-b193-f1e73aa6287a;"
          }
        },
        "_ingest" : {
          "timestamp" : "2019-10-20T16:37:59.856569Z"
        }
      }
    }
  ]
}

```

**Comment by narph** [comment]
@kaiyan-sheng ,
In principle filebeat modules are intended to support default log formats of services which seems to be the case here as well (we currently support only W3C formats). 
We should edit the filebeat/iis module documentation and specify this limitation.

I wonder what are the most common iis log formats users work with (besides W3C) , @sorantis , feel free to chime in if you have any ideas, but this issue sounds like a great starting point.

@philippkahr , the situation you are dealing with seems to be different than the initial conversation point (supporting NCSA and IIS logs). From the log lines provided, it seems that the log format  is W3C.
I suggest creating a different issue to followup, correct me if I am wrong here and the subjects are related.

**Comment by sorantis** [comment]
@kaiyan-sheng @narph looks like W3C is the most common format for collecting logs.
According to the official [documentation](https://support.microsoft.com/en-us/help/313437/how-to-enable-logging-in-internet-information-services-iis): `the W3C Extended log file format is the preferred log type to use.` Also, other IIS integration providers default to it.

**Comment by philippkahr** [comment]
Hi @narph 

seems ok to me. I wanted to help and point to the other "weird" log formats that IIS comes up with. I will create an additional issue and link it to my comment. I needed it for my work anyway, so I implemented the grok patterns in our pipeline and they work :D. At least we know something ;).

**Comment by kaiyan-sheng** [comment]
@narph W3C is the most common format 👍 We can either add support for other "weird" log formats(@philippkahr thank you for your help!) or add more documentation on exactly what we support currently.

**Comment by narph** [comment]
I would update the documentation in this case and specify that in this case we support W3C formats only, at the moment no NCSA or IIS.
I would like to follow up on  https://github.com/elastic/beats/issues/14284 and test if we can improve the current pipeline and accommodate this use case for the W3C format.
Regarding the other formats you mentioned above ( NCSA or IIS) would be interesting to hear from  users, if this is something they are interested.

**Comment by philippkahr** [comment]
My log files are only generated when using an exchange mail server. We use them quite often to troubleshoot any connectivity issues. I do not know how the community feels about it. Maybe start with a similar architecture like the cisco module?

```yaml
- module: iis-generic
- module: iis-exchange
- module: iis...
```

**Comment by jvossler** [comment]
Hi there, any updates on adding a parser for W3C Extended Log File Format? I have old Bro/Zeek logs that are in  W3C Extended Log File Format and I am looking to ingest them. I am having an issue parsing the data effectively.
