### ISSUE TITLE
[Metricbeat][Docker] Enrich statistics about blkio

### ISSUE THREAD

**Issue by unixsurfer** [elastic/beats#13798]
**Describe the enhancement:**
[Docker API stats](https://docs.docker.com/config/containers/runmetrics/) exposes most of the metric that [cgroup blkio controller](https://www.kernel.org/doc/Documentation/cgroup-v1/blkio-controller.txt) provides but [metricbeat exposes](https://www.elastic.co/guide/en/beats/metricbeat/7.4/exported-fields-docker.html#_diskio) only read/write rate/throughtput. I would like to see the following metrics(copied from cgroup blkio controller documentation) exposed per container:

- blkio.io_service_time
	 Total amount of time between request dispatch and request completion
	  for the IOs done by this cgroup. This is in nanoseconds to make it
	  meaningful for flash devices too. For devices with queue depth of 1,
	  this time represents the actual service time. When queue_depth > 1,
	  that is no longer true as requests may be served out of order. This
	  may cause the service time for a given IO to include the service time
	  of multiple IOs when served out of order which may result in total
	  io_service_time > actual time elapsed. This time is further divided by
	  the type of operation - read or write, sync or async. First two fields
	  specify the major and minor number of the device, third field
	  specifies the operation type and the fourth field specifies the
	  io_service_time in ns.

- blkio.io_wait_time
	 Total amount of time the IOs for this cgroup spent waiting in the
	  scheduler queues for service. This can be greater than the total time
	  elapsed since it is cumulative io_wait_time for all IOs. It is not a
	  measure of total time the cgroup spent waiting but rather a measure of
	  the wait_time for its individual IOs. For devices with queue_depth > 1
	  this metric does not include the time spent waiting for service once
	  the IO is dispatched to the device but till it actually gets serviced
	  (there might be a time lag here due to re-ordering of requests by the
	  device). This is in nanoseconds to make it meaningful for flash
	  devices too. This time is further divided by the type of operation -
	  read or write, sync or async. First two fields specify the major and
	  minor number of the device, third field specifies the operation type
	  and the fourth field specifies the io_wait_time in ns.
- blkio.io_queued
	 Total number of requests queued up at any given instant for this
	  cgroup. This is further divided by the type of operation - read or
	  write, sync or async.

all above are available in the Docker Stats API, see below:

```bash
% curl -s --unix-socket /var/run/docker.sock http:/containers/c2/stats?stream=false|jq '.blkio_stats|keys'
[
  "io_merged_recursive",
  "io_queue_recursive",
  "io_service_bytes_recursive",
  "io_service_time_recursive",
  "io_serviced_recursive",
  "io_time_recursive",
  "io_wait_time_recursive",
  "sectors_recursive"
]
```

**Describe a specific use case for the enhancement or feature:**
Knowing service and wait time together with the size of the queue will provide a better view on the performance of the container.

**Comment by andresrc** [comment]
Anything else to do here, or can we close to issue?

**Comment by unixsurfer** [comment]
> Anything else to do here, or can we close to issue?

Shall we wait for the release to come out before we close this one?
