### ISSUE TITLE
Stack compatibility version matrix and upgrade process document differ

### ISSUE THREAD

**Issue by michaelhyatt** [elastic/beats#13797]
Stack version support matrix states that the 7.x version of the stack requires beats to be at least on version 6.8.x, which contradicts our upgrade process document that suggests upgrading early 6.x versions to 6.7.x before the upgrade of the rest of the stack to 7.x. 

Supported version matrix suggesting beats to be minimum 6.8:
https://www.elastic.co/support/matrix#matrix_compatibility

The upgrade process for beats page suggesting to go to 6.7 before upgrading the stack:
https://www.elastic.co/guide/en/beats/libbeat/7.2/upgrading-6-to-7.html

Reading these two pages creates confusion about which version of beats should be the interim when upgrading from early 6.x to the latest and greatest 7.x.

**Comment by dedemorton** [comment]
Sorry that this issue got lost in the docs repo for awhile. This problem is fixed in https://github.com/elastic/beats/pull/13141 (should be merged soon, so I will close this issue now).
