### ISSUE TITLE
Getting process information is slow

### ISSUE THREAD

**Issue by tsg** [elastic/beats#138]
During load testing, I discovered that the way we map sockets to processes (by polling `/proc/net/tcp`) is slow in some situations. In particular, it is slow when there lots of open sockets, because the `/proc/net/tcp` file can become very large.

Some micro-optimisations could be done for the parsing (current hotspot is in `bytes.Fields`), but I'm afraid the real solution would be to switch away from `/proc/net/tcp`. 

Here is a potential way forward: https://vividcortex.com/blog/2014/09/22/using-netlink-to-optimize-socket-statistics/

**Comment by ruflin** [comment]
I switched the label `bug` to `enhancement` because as far as I understand it's working as expected but it's not too efficient.
