### ISSUE TITLE
[metricbeat] change server_status_path default setting for nginx module

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/beats#13806]
In nginx.xml, it makes server_status_path as `server-status`, but https://www.nginx.com/blog/monitoring-nginx/ makes `nginx_status` as an example and some people simply copy&paste that and they can run into `HTTP error 404 in stubstaus: 404 Not Found"` error

```
  # Path to server status. Default server-status
  #server_status_path: "server-status"
```

Maybe changing the default to `nginx_status` reduces the hassles?

**Comment by goku321** [comment]
Can I work on this?

**Comment by kaiyan-sheng** [comment]
@goku321 Yes please do! Please assign this issue to yourself once you start working and link the PR with the issue as well. Thanks!
