### ISSUE TITLE
json.ignore_decoding_error is missing from beats reference.yml

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#13804]
Reported by a forum user:

PR https://github.com/elastic/beats/pull/6547 added a new option json.ignore_decoding_error but documentation for this option is missing in the Beats reference.yml.

**Comment by akshit-rohra-debug** [comment]
Is anyone working on this issue?

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
