### ISSUE TITLE
logp.Warn() in libbeat/common/event.go is missing one parameter

### ISSUE THREAD

**Issue by zstyblik** [elastic/beats#1380]
Hello,

one of `logp.Warn()` in `libbeat/common/event.go` is short of one parameter as can be seen in the code below.

```
				anothermap, err := MarshallUnmarshall(value)
				if err != nil {
					logp.Warn("fail to marshall & unmarshall map (%v): key=%v value=%#v",
						key, value)
					continue
				}
```

It's an easy fix. However, I couldn't figure out what the parameter should be.

Thank you.

**Comment by ruflin** [comment]
The idea was probably to use `anothermap`. @urso Please correct me if I'm wrong here.

**Comment by monicasarbu** [comment]
@zstyblik It's missing the error message. I will fix it in a different PR. Thanks for opening the issue.

**Comment by monicasarbu** [comment]
@zstyblik It's interesting that you get these warnings. Can I ask you what Beat are you using?

**Comment by zstyblik** [comment]
@monicasarbu I'll go with `libbeat 5.0.0-SNAPSHOT`? :p I don't know, to be honest. It's something that I haven't written originally.

**Comment by ruflin** [comment]
Closing as I think this was solved in https://github.com/elastic/beats/pull/1379

**Comment by zstyblik** [comment]
@ruflin, as @monicasarbu this should've been fixed by a different PR. #1379 for sure did not address this issue.

**Comment by zstyblik** [comment]
... but it did get fixed over the time indeed. Just not in #1379 :)
