### ISSUE TITLE
Document privileges needed to use Metricbeat MongoDB module

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#13820]
Check the privileges needed to use the MongoDB module and document them.

Add user and roles to MongoDB integration tests so these privileges are checked.

**Comment by hwang381** [comment]
I am new to the project but I'd like to work on this issue as a Hacktoberfest issue. A few questions though

- Does the work involve both checking privileges within code itself AND document those privileges? The issue description seems to indicate that but the title only says document
- Is "privileges" referring to MongoDB privileges, e.g. as described [here](https://docs.mongodb.com/manual/core/authorization/#privileges)
- If that's the case, what exact privileges are needed?

Cheers

**Comment by jsoriano** [comment]
Hey @hwang381,

Welcome to the project :slightly_smiling_face: It is great that you want to work on this issue for the Hacktoberfest, let's see if I can help with your questions.

> * Does the work involve both checking privileges within code itself AND document those privileges? The issue description seems to indicate that but the title only says document
> 

We should at least document them. Having something in tests to verify the permissions would be great, but not so important, and it could be done in a separate PR.

>  * Is "privileges" referring to MongoDB privileges, e.g. as described [here](https://docs.mongodb.com/manual/core/authorization/#privileges)
> 

Yes.

>  * If that's the case, what exact privileges are needed?
> 

I don't really know, this would be the main task of this issue :slightly_smiling_face: Once we confirm which privileges are needed, then we can add them to the documentation of the module in `metricbeat/module/mongodb/_meta/docs.asciidoc`.

Thanks!

**Comment by hwang381** [comment]
Trying to find all privileges that would be needed by

1. Finding all places where a mongodb query is executed in the `mongodb` package. For example, `mongoSession.Run("top", &result)` in `collstats.go`. There are about 5 or 6 of them in the package.
2. For each of the mongodb queries, find and document the required privileges in mongodb doc

Let me know whether the methodology sounds right to you and then I will proceed with a PR.

**Comment by jsoriano** [comment]
@hwang381 this sounds great! It'd be also good to document how to add these privileges, or where to find instructions to do so. But let's focus first on finding the required privileges.

**Comment by hwang381** [comment]
PR created #13932
