### ISSUE TITLE
[Stack Monitoring] Deprecate `monitoring.elasticsearch.*` settings

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#13823]
In 7.2.0, we introduced `monitoring.elasticsearch.*` settings to allow Beats and APM Server to directly ship their internally-collected monitoring data to a _monitoring_ Elasticsearch cluster via the standard `POST _bulk` Elasticsearch API endpoint. Prior to this, users would use the `xpack.monitoring.elastiscearch.*` settings, which would ship internally-collected monitoring data to their _production_ Elasticsearch cluster via the custom `POST _monitoring/bulk` Elasticsearch API endpoint. 

However, by 7.3.0, our thinking changed and we decided to introduce a `beat` module in Metricbeat (with a `beat-xpack` module configuration variant). We now want users to use this module to monitor Beats and APM Server externally and ship the collected data to a _monitoring_ Elasticsearch cluster.

As such, we must now deprecate the `monitoring.elasticsearch.*` settings introduced in 7.2.0 and ask users to switch over to using Metricbeat with the `beat-xpack` module enabled.

**Comment by cachedout** [comment]
@ycombinator I confess that I don't know much about what the deprecation procedure is for a setting in Beats. Do you typically add a warning to the log if the flag is enabled? Or is it just purely a documentation change? Of, if there is a standard document that describes the typical deprecation procedure across the stack (if such a document exists) that you could link me to, that would be even better. :) Thanks!

**Comment by ycombinator** [comment]
Concretely, deprecation of the setting mentioned in this issue will require 3 changes:

1. Issuing a deprecation warning in the Beats log if the setting is used.
2. Adding a deprecation note above the setting in the Beat's reference configuration YML file.
3. Adding a deprecation note in Beats online documentation, e.g. https://www.elastic.co/guide/en/beats/filebeat/current/monitoring-internal-collection.html.

**Comment by cachedout** [comment]
PR for deprecation notice in Beats documentation: https://github.com/elastic/beats/pull/14887. Linked in this direction to avoid public->private GH linking.

**Comment by cachedout** [comment]
Deprecation notice (Items 1 and 2 [here](https://github.com/elastic/beats/issues/13823#issuecomment-556259772)): https://github.com/elastic/beats/pull/14858
