### ISSUE TITLE
Make docs doesn't return errors?

### ISSUE THREAD

**Issue by ph** [elastic/beats#13864]
I've come across an issue in a build doc in https://github.com/elastic/beats/pull/13336 and I think it's worth investigating, the PR was making the main doc build fails but the "make docs" was working and did not complain at all. I've fixed the issue in https://github.com/elastic/beats/pull/13862.

I think it worth investigating why this is the case, I mean we do test locally the build with make docs and it would be nice that we can have a 1:1 representation of the build.

**Comment by andrewkroh** [comment]
Looks like the script should be setting the return code:

https://github.com/elastic/beats/blob/cfdae76a3963c0b1ff1ebd133b6098b4aff1a5d7/script/build_docs.sh#L3

Double-check these (I think they're OK):

https://github.com/elastic/beats/blob/41312410b8f5cc324d74ef9b2ed89af48bc52c8f/Makefile#L132-L134

https://github.com/elastic/beats/blob/41312410b8f5cc324d74ef9b2ed89af48bc52c8f/libbeat/scripts/Makefile#L342-L347
