### ISSUE TITLE
[Metricbeat] Tomcat module

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#13860]
# Metricbeat Module / Dataset release checklist

This checklist is intended for Devs which create or update a module to make sure modules are consistent.

## Modules

For a metricset to go GA, the following criterias should be met:

* [X] Supported versions are documented
* [X] Supported operating systems are documented (if applicable)
* [X] Integration tests exist
* [ ] System tests exist
* [ ] Automated checks that all fields are documented
* [X] Documentation
* [X] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [X] Dashboards exists (if applicable)
* [ ] Kibana Home Tutorial (if applicable)
  * [ ] Open issue in [EUI repo](https://github.com/elastic/eui) to add [icon for module](https://elastic.github.io/eui/#/display/icons) if not already exists.
  * [ ] Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).

## Metricbeat module

* [ ] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [ ] Test environment in Docker exist for integration tests

**Comment by masci** [comment]
superseded by https://github.com/elastic/integrations/issues/640
