### ISSUE TITLE
close_removed and close_renamed only checked after EOF

### ISSUE THREAD

**Issue by urso** [elastic/beats#13889]
Checking the code in log.go, it looks like close_removed/close_renamed are only checked once we reached EOF. As long as filebeat has an open file handle, but hasn't reached the end yet, the OS will never report an error. Due to this filebeat would keep files open, even the settings are set.

**Comment by ycombinator** [comment]
Steps to reproduce (for `close_removed`):

1. Configure the `log` input in `filebeat.yml` to point to an empty folder, e.g.:
   ```yml
   - type: log
     enabled: true
     paths:
       - /tmp/fbtest/*
   ```

2. Start up Filebeat.
   ```
   filebeat -e
   ```

2. Run `lsof` to see file descriptors in use by the Filebeat process.
   ```
   watch -n 1 lsof -p $(ps | grep './filebeat -e' | grep -v grep | awk '{print $1}')
   ```

3. Copy a large file (several MB will suffice) into the empty logs folder.
   ```
   cp some_large_file.txt /tmp/fbtest/test.log
   ```

4. Watch the `lsof` output to see the log file appear in it. You can also check the Filebeat log to see that a harvester has started for this file.

5. Delete the log file.
   ```
   rm /tmp/fbtest/test.log
   ```

6. Keep watching the `lsof` output. The file descriptor for the log file you deleted is never closed, even after several minutes.

**Comment by ycombinator** [comment]
Hi @urso, I'm unable to reproduce this bug on `master`. Here are the steps I tried:

1. Configure Filebeat to use the `log` input pointing to an empty folder, like so:
   ```yml
   - type: log
     enabled: true
     paths:
       - /tmp/fbin/*.log
   ```

  Configure the `file` output to make it easy for debugging purposes.
  ```
  output.file:
    enabled: true
    path: /tmp/fbout
  ```

2. Start Filebeat.
   ```
   rm -rf data/registry/filebeat/
   filebeat -e
   ```

2. Use `lsof` to watch FDs opened by Filebeat:
   ```
   watch -n 1 lsof -c filebeat
   ```

3. Copy a large file (several MB will suffice) into `/tmp/fbin`.
   ```
   cp some_large_file.txt /tmp/fbin/test.log
   ```

4. Watch the `lsof` output to see that Filebeat has opened a file descriptor for `/tmp/fbin/test.log`.

5. Immediately delete `/tmp/fbin/test.log`.
   ```
   rm /tmp/fbin/test.log
   ```

6. Notice in the `lsof` output that the file descriptor for `/tmp/fbin/test.log` is no longer there.

7. Also notice in the Filebeat log that there is a message like this:
   ```
   2019-10-03T11:20:18.033-0700      INFO    log/harvester.go:268    File was removed: /tmp/fbtest/test.log. Closing because close_removed is enabled.
   ```

8. Verify that Filebeat did not reach EOF on `/tmp/fbin/test.log` by comparing the size of the large source log file with the size of the file output to by Filebeat.
   ```
   wc -l some_large_file.txt
   wc -l /tmp/fbout/filebeat
   ```

**Comment by ycombinator** [comment]
Chatted with @urso off-issue. The above method doesn't quite work when using a `file` output (assuming there's enough disk space for the output file). Filebeat will read to the end of the input file, enqueue it, and periodically flush the queue to the output.

Really the only way to prevent Filebeat from reaching EOF is by slowing down the output. So to simulate that I used an Elastiscearch output and periodically started/stopped my 1-node ES cluster.
