### ISSUE TITLE
Filebeat 7.4 but field agent.version is 7.3.2

### ISSUE THREAD

**Issue by VN1977** [elastic/beats#13897]
Hello!
I upgraded filebeat from 7.3.2 to 7.4, then uploaded new pipelines and index template.
Filebeat sends system logs to logstash which is installed at the same host. Then logstash sends info to coordinating node installed at the same host.
But when I look though docs from this host I see that index is filebeat-7.4.0-xxxxxxx but agent.version is 7.3.2.
I tried to reinstall filebeat but nothing helps. Tried to erase all files, install again and set but doesn't help too.
Such a situation happend only with one host. Others six hosts send correct info with agent.version 7.4.0.

For confirmed bugs, please report:
- Version: 7.4
- Operating System: Centos 7.5
- Discuss Forum URL: 
- Steps to Reproduce: Can't do it.

**Comment by jsoriano** [comment]
Hi @VN1977,

This is really weird, specially if this happens in an only host. Could you check if the filebeat binary is the same in the hosts where you don't see this issue and in the one where you see it?
Please also check if filebeat is actually updated to the version you expect with `filebeat version`.

I am going to close this issue till we confirm that this is an actual bug. Please for future questions consider using https://discuss.elastic.co to confirm issues before opening a new issue in Github.
