### ISSUE TITLE
Allow customised index time ranges/suffixes

### ISSUE THREAD

**Issue by tsg** [elastic/beats#139]
@markwalkom posted on the private repo:

Currently you can only set the prefix that Packtbeat uses when creating indices in ES.

For systems that may have low volume it doesn't make sense to have a daily index, and rolling up to weekly/monthly is a better use of resources.

It'd be awesome if there was an option to customise the index name including the time period.

**Comment by ruflin** [comment]
Closing in favor of https://github.com/elastic/beats/issues/921
