### ISSUE TITLE
Kibana Filebeat Plugin sending immense fields

### ISSUE THREAD

**Issue by kresss** [elastic/beats#13901]
I received the following error when trying to setup metricbeat. I have the system module enabled for metricbeat and was trying to have metricbeat setup kibana. I have the kibana filebeat module enabled and pulling in the kibana logs. The logs are published to logstash and shipped into elasticsearch. The request was to create the metricbeat index pattern in kibana, but this isn't desirable.

Command: 
`# metricbeat setup -c /etc/metricbeat/metricbeat-setup.yml --index-management --dashboards --machine-learning`

Error: 
`[2019-10-03T15:27:08,601][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"filebeat-7.3.2-2019.10.03", :_type=>"_doc", :routing=>nil, :pipeline=>"filebeat-7.3.2-kibana-log-pipeline"}, #<LogStash::Event:0x43396d27>], :response=>{"index"=>{"_index"=>"filebeat-7.3.2-2019.10.03", "_type"=>"_doc", "_id"=>"VyY7km0BogYVSdT4Yurp", "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"Document contains at least one immense term in field=\"kibana.log.meta.args.attributes.fields\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[91, 123, 34, 110, 97, 109, 101, 34, 58, 34, 64, 116, 105, 109, 101, 115, 116, 97, 109, 112, 34, 44, 34, 116, 121, 112, 101, 34, 58, 34]...', original message: bytes can be at most 32766 in length; got 186746", "caused_by"=>{"type"=>"max_bytes_length_exceeded_exception", "reason"=>"bytes can be at most 32766 in length; got 186746"}}}}}
`

Log Entry in kibana.stdout

`{
    "type": "log",
    "@timestamp": "2019-10-03T15:27:07Z",
    "tags": [
        "info",
        "audit",
        "security",
        "saved_objects_authorization_success"
    ],
    "pid": 5495,
    "username": "kresss",
    "action": "update",
    "types": [
        "index-pattern"
    ],
    "args": {
        "type": "index-pattern",
        "id": "filebeat-*",
        "attributes": {
            "title": "filebeat-*",
            "timeFieldName": "@timestamp",
            "fields": "[{\"name\":\"@timestamp\",\"type\":\"date\",\"esTypes\":[\"date\"],\"count\":0, ///// VERY LONG LINE ///// ]",
            "fieldFormatMap": "{\"client.bytes\":{\"id\":\"bytes\"},\"client.port\":{\"id\":\"string\"},///// VERY LONG LINE /////}"
        },
        "options": {
            "version": "WzM0NDMsMzdd",
            "references": []
        }
    },
    "eventType": "saved_objects_authorization_success",
    "message": "kresss authorized to update index-pattern"
}`

For confirmed bugs, please report:
- Version:  7.3.2
- Operating System: RHEL 7.7

**Comment by jsoriano** [comment]
Hi @kresss,

We try to keep Github for confirmed issues, could you please post this question as a new topic in https://discuss.elastic.co? There we could try to help you and confirm if this is an actual bug in filebeat or kibana.

In the meantime, could you try to upgrade filebeat to a more recent version?

**Comment by kresss** [comment]
@jsoriano Sorry that was typo I was running 7.3.2. 

As for reporting through the discuss.elastic.co, I will just walk away from this one. Sorry for the waste of time & resources.

**Comment by jsoriano** [comment]
Oh, if this is happening with 7.3.2 it may worth to take a look, sorry for closing it so fast, and thanks for reporting!

What configuration are you using for the Kibana module?

**Comment by kresss** [comment]
I have the system module enabled for metricbeat and the kibana module enabled on filebeat. In kibana.yml I set `logging.dest: /var/log/kibana/kibana.stdout`. That is the path that the filebeat kibana module watches by default. 

I think the steps are:

- Setup Filebeat -> Logstash -> ES
- Setup Kibana w/ the logging destination.
- Setup Metricbeat w/ system module
- Run the metricbeat setup command and have it try to publish to ES & Kibana.

I am just upgraded my test box to 7.4. I will try to reproduce it and give more definitive steps.

**Comment by JohnLyman** [comment]
I'm getting this as well.  Is the Kibana module expecting the logs to be in json or not?  `logging.json: true|false` in kibana.yml.

**Comment by JohnLyman** [comment]
I can confirm this is still an issue with filebeat 7.13.2.

I was able to work-around this by setting `kibana.log.meta.args.attributes.fields` properties to `type: text` with `index: false`.
