### ISSUE TITLE
Allow hints based autodiscover based on namespace metadata

### ISSUE THREAD

**Issue by exekias** [elastic/beats#13913]
Once we get namespace metadata in https://github.com/elastic/beats/issues/13873, it should be possible to use it for hints based autodiscover.

Users should be able to set hints at the namespace level, so they don't need to repeat them across all pods in the namespace. Hints from the namespace and the Pod should be merged. If one is present in both the namespace and the pod, the one in the Pod overrides the namespace's.

For instance, adding this hint to a namespace should make Filebeat ignore logs from all its pods: `co.elastic.logs/enabled: false`. While if `co.elastic.logs/enabled: true` is added to a pod in the namespace, its logs should be retrieved.

**Comment by exekias** [comment]
cc @odacremolbap @ChrsMark @sorantis

**Comment by jsoriano** [comment]
This could be a fix for some use cases related to https://github.com/elastic/beats/issues/9123

**Comment by sorantis** [comment]
keep open

**Comment by jsoriano** [comment]
Would this be solved by https://github.com/elastic/beats/pull/16321?

**Comment by ChrsMark** [comment]
> Would this be solved by #16321?

Looks like yes! @exekias could you confirm that?

**Comment by exekias** [comment]
++ closing
