### ISSUE TITLE
filebeat - unable to stop process in foreground after connection issue to ES

### ISSUE THREAD

**Issue by djschny** [elastic/beats#1392]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For confirmed bugs, please report:
- Version: v5.0.0-alpha1
- Operating System: Darwin 10.11.4

__Steps to Reproduce:__
1. Start filebeat shipping to a remote ES instance
2. Shut the ES instance down
3. Notice connection error message and then try to stop filebeat with Ctrl-C and notice that it will not stop

```
djschny:topbeat-5.0.0-alpha1-darwin djschny$ sudo ./topbeat -e
2016/04/14 00:22:10.062423 client.go:136: ERR Failed to perform any bulk index operations: Post http://192.168.43.35:9200/_bulk: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
^C
^C^C

^C^C^C



^C^C


```

**Comment by andrewkroh** [comment]
Thanks for reporting. Sounds like a duplicate of #1319 which is listed as a known issue in the 5.0.0-alpha1 release notes.

**Comment by djschny** [comment]
Oye, sorry @andrewkroh , sorry about the dupe.
