### ISSUE TITLE
Filebeat Nginx dashboard has no data to display

### ISSUE THREAD

**Issue by lukelee1987** [elastic/beats#13933]
Hi need some help. Almost 99% of my dashboards cannot display the data collected, while there are data collected from the other servers stored and received into our Elasticsearch DB. Wonder why the default dashboard cannot display? 

I have tried various method to resolve this, but all of it just doesn't work. 

![image](https://user-images.githubusercontent.com/29053050/66282981-37f55500-e8f4-11e9-9284-93eb7a68524d.png)

![image](https://user-images.githubusercontent.com/29053050/66283054-8dc9fd00-e8f4-11e9-80bb-c7897ce34e60.png)

**Comment by jsoriano** [comment]
Hi @lukelee1987,

We try to keep github for confirmed issues, could you please post this question in https://discuss.elastic.co? If at the end it happens to be a bug, we will be happy to reopen this issue.

It case it can help in the meantime, dashboards included in Filebeat are though to be used along with Filebeat modules, but in the events you show I cannot see any fields like the ones parsed by the nginx module. You should be using the [nginx module](https://www.elastic.co/guide/en/beats/filebeat/7.3/filebeat-module-nginx.html) to parse the logs to the structure expected by the dashboard.
