### ISSUE TITLE
Init script hangs when executed over SSH

### ISSUE THREAD

**Issue by tsg** [elastic/beats#1394]
Easiest way to reproduce, do something like this:

```
ssh host "sudo /etc/init.d/topbeat start"
```

where the target host is a centos6 machine. The SSH session stays open forever instead of returning after starting topbeat in background. I tracked this to go-daemon and opened a PR that I think should fix the issue: https://github.com/fiorix/go-daemon/pull/7

This ticket is to make sure we incorporate the fix when it's merged upstream.

**Comment by frederic-jomedia** [comment]
Hello,
Same problem with using tool like Saltstack.

As a quick workaround in the init script (line 61 on ubuntu), I replaced : 
`                --exec $WRAPPER -- $WRAPPER_ARGS $DAEMON $DAEMON_ARGS \`
with 
               ` --exec $WRAPPER -- $WRAPPER_ARGS -- $DAEMON $DAEMON_ARGS \`

**Comment by tsg** [comment]
@frederic-jomedia looks like we already have that change: https://github.com/elastic/beats/blob/master/dev-tools/packer/platforms/debian/init.j2#L61

I seem to remember we add it at some point, perhaps you tried a while ago? Or you mean the change in the other direction?

**Comment by frederic-jomedia** [comment]
My bad, the replacement was actually :
`--exec $WRAPPER -- $WRAPPER_ARGS -- $DAEMON -- $DAEMON_ARGS \`

but I was wrong. it return true but filebeat did not start.
At the moment there is no way to start or restart filebeat if you are not logged in.

**Comment by tsg** [comment]
https://github.com/fiorix/go-daemon/pull/7 was just merged, so this should be fixed with the next release.
