### ISSUE TITLE
[Packetbeat]Kubernetes: add IP (without port) indexer for the kube processor

### ISSUE THREAD

**Issue by odacremolbap** [elastic/beats#13962]
Received an off channel request to be able to map kubernetes metadata using Pod IP, without port.

Packetbeat can map a connection from a source to a destination by matching the kubernetes `IP:Port`. That data is declared at kubernetes manifests for exposed services, which means we can identify and add metadata for the destination only.

To be able to also include information about the source pod where the client resides we could add the ability to match per `Pod IP`, disregarding Port.

Resulting event should prefix the added metadata to distinguish between _destination metadata_ and _source metadata_

**Comment by exekias** [comment]
The `ip_port` indexer stores metadata both by `ip` and `ip:port` pairs. Check: https://github.com/elastic/beats/blob/master/libbeat/processors/add_kubernetes_metadata/indexers.go#L237

Would that be enough?

**Comment by odacremolbap** [comment]
I think we can close this issue.
If you think otherwise, please re-open
