### ISSUE TITLE
New Needing in Filebeat (Protobuf Codec In Output Configuration)

### ISSUE THREAD

**Issue by kiss001** [elastic/beats#13979]
I found there only hava two codec method in https://www.elastic.co/guide/en/beats/filebeat/current/configuration-output-codec.html website, Now I hava a new requirement that It use protocol buffer to codec the data. Whether you hava a new plan to support the protobuf codec in ouput configuration？

**Comment by EberliAugusto** [comment]
I was just looking for the same thing, what I am trying to achieve is this:
Each line of the log file is a json, FileBeat picks each line up, and sends it to Kafka using protobuf in the value, and the key comes from a field in the json (for the key existing functionality would work just fine).
