### ISSUE TITLE
Filebeat haproxy module cannot parse syslog line

### ISSUE THREAD

**Issue by andrask** [elastic/beats#13995]
- Version: 7.4.0
- Operating System: Linux
- Steps to Reproduce: 

1. Example line: `2019-10-10T07:46:25+02:00 localhost haproxy[30143]: 127.0.0.1:39442 [10/Oct/2019:06:46:15.492] service-backend service-backend/dest-server 1/0/98 8398 -- 6/5/5/5/0 0/0`
2. Apply the patterns from the [ingest pipeline](https://github.com/elastic/beats/blob/master/filebeat/module/haproxy/log/ingest/pipeline.json).
3. The parsing fails on the syslog date.

Proposal: use the SYSLOGBASE2 pattern instead of the custom constructed HAPROXY_DATE and followup patterns.

**Comment by andrask** [comment]
This issue has not been fixed yet.

**Comment by Andrey4ik85** [comment]
Hello! What about this issue?
I have this problem too
1. Example line: `2021-07-15T20:12:59+03:00 localhost haproxy[6345]: 10.20.30.40:42650 [15/Jul/2021:20:12:59.403] service_tcp_80 service_backend_tcp_80/backend_server 0/0/0/52/52 200 1381 - - ---- 488/8/0/0/0 0/0 "POST /test/test HTTP/1.1"`
2. Send line to kafka: 
`event:	{
dataset:	haproxy.log
module:	haproxy
timezone:	+03:00
}
fileset:	{
name:	log
}
group:	test_group
inst:	localhost
message:	2021-07-15T20:12:59+03:00 localhost haproxy[6345]: 10.20.30.40:42650 [15/Jul/2021:20:12:59.403] service_tcp_80 service_backend_tcp_80/backend_server 0/0/0/52/52 200 1381 - - ---- 488/8/0/0/0 0/0 "POST /test/test HTTP/1.1"
service:	{
type:	haproxy
}`
