### ISSUE TITLE
Unify common Kubernetes configuration docs

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#13997]
Currently we have 3 basic Kubernetes features:

- Kubernetes Module
- Autodiscover
- add_kubernetes_metadata processor 

All these 3 have very similar configuration settings like `kube_config`, `host`, etc.
So it would be nice to have these common configuration settings to be documented centrally for all Kubernetes related features and not at each one of them separately.

Let's discuss here the why/how!

cc: @odacremolbap , @exekias

**Comment by dedemorton** [comment]
This makes sense. There's a related issue that I opened quite some time ago but have not had time to pursue. I https://github.com/elastic/beats/issues/8305. Carlos made some good points.

**Comment by dedemorton** [comment]
Bumping the priority of this work to get it into a release plan.
