### ISSUE TITLE
Document change to monitoring settings in 7.2 and later

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#13994]
**Question that provoked this issue**
Is there any document about the changes and the new functionality of the new "monitoring" engine in beats 7.3 that works totally different than when `xpack.monitoring` config setting was set? 

**Response**
There's no public-facing documentation focused on the change other than the pre-7.2 docs which talk about the old setting (https://www.elastic.co/guide/en/beats/filebeat/7.1/monitoring.html) and the 7.2+ docs which talk about the new setting (https://www.elastic.co/guide/en/beats/filebeat/7.2/monitoring.html).

Starting in 7.2,  we didn't want users to use `xpack.monitoring.*` which is why we removed it from the docs. However, they can still use it, which is how we prevent this from being a breaking change to anyone upgrading to 7.2 or later. We will show a deprecation notice in the logs in this case. 

The newer setting is going to be deprecated soon too. See https://github.com/elastic/beats/issues/13823.

**Affect on existing customers**

* Customers who use the `xpack.monitoring` functionality in the beat to write monitoring data towards 2 clusters, via a local exporter + a remote exporter in the elasticsearch server... those customers won't be able to do this anymore

* Metricbeat is now the recommended way to monitor Beats.

* The `xpack.monitoring.*` and `monitoring.*` settings will be deprecated and then removed in 8.0

**Doc changes required**

 * Draw attention to the fact that the setting name changed in 7.2 (from `xpack.monitoring` to just `monitoring`) in these pages: https://www.elastic.co/guide/en/beats/filebeat/7.1/monitoring.html https://www.elastic.co/guide/en/beats/filebeat/7.2/monitoring.html
* Add a brief explanation in the 7.2+ docs about the new config parameter. Mention that the parameter is new (it's not `xpack.monitoring` anymore) and that it works in a slightly different way. With the new parameter, the routing of monitoring data from cluster to cluster via Elasticsearch remote exporters won't be possible anymore. A lot of our customers are using that already (because they were forced to in previous releases with `xpack.monitoring`), but with the new setting that wouldn't work and they should be aware.
* Make sure the old monitoring settings are marked as deprecated.

**Comment by dedemorton** [comment]
@lcawl FYI I've added an issue to track these changes. I'm trying to narrow requests down to one point of ingress...GitHub! If you decide you want to take on this work, feel free, but I'll add it to my queue.

**Comment by cachedout** [comment]
Hi @dedemorton. I just wanted to check in on the progress of this. Has there been any movement here or do you have an ETA on when this work might start?

**Comment by dedemorton** [comment]
It's on my short list of items to tackle after 7.5 ships, but I have no progress to report at this time.

**Comment by cachedout** [comment]
Thank you for the update, @dedemorton !

**Comment by dedemorton** [comment]
@cachedout I plan to start working on this today or tomorrow, but want to make sure my work won't conflict with any changes you have in flight. Is it OK for me to get started on this now?

**Comment by cachedout** [comment]
@dedemorton Nothing in-flight from me that should conflict with this. Go for it!
