### ISSUE TITLE
Check performance of (*Log).Read method

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#14008]
In #13907 we fixed #13488 by checking if the log file being harvested was renamed or removed right before we read each log line. 

@urso has noted that there might be some inefficiencies in the #13907 implementation. The implementation results in 3 stat system calls:

1. https://github.com/elastic/beats/blob/660daa1bb82ab0d636d821c4085310a6b5cf7ab0/filebeat/input/log/log.go#L168
2. https://github.com/elastic/beats/blob/660daa1bb82ab0d636d821c4085310a6b5cf7ab0/filebeat/input/file/file.go#L40
3. https://github.com/elastic/beats/blob/660daa1bb82ab0d636d821c4085310a6b5cf7ab0/libbeat/common/file/file_windows.go#L143 (Windows) https://github.com/elastic/beats/blob/660daa1bb82ab0d636d821c4085310a6b5cf7ab0/libbeat/common/file/file_other.go#L68 (not-Windows)

For not-Windows we should be able to reduce at least one extra stat by removing the duplication between 2 and 3.

Further, we may be able to cache the results of 1.

We should benchmark the current implementation (as introduced in #13907) vs. the changes described above.

**Comment by urso** [comment]
@kvch I expect this issue to be resolved by architectural changes in the new log file input. Would be nice to have benchmarks, though.

**Comment by faec** [comment]
Stale (the filestream input has superceded logs), closing.
