### ISSUE TITLE
Unrealistic Data after implementing the Refresh Counter List

### ISSUE THREAD

**Issue by prakash1243** [elastic/beats#14036]
Hi @narph -
As I mentioned in the other thread, with respect to the CPU related process counters, there seems to be un-realistic data found after pushing the Refresh counter list changes, I manually executed the  typeperf command manually and here are my findings:
> 
> "(PDH-CSV 4.0)","\\CI-Win2012\Process(metricbeat)\% Processor Time"
> "10/14/2019 12:23:43.812","6.245860"
> "10/14/2019 12:23:44.813","0.000000"
> "10/14/2019 12:23:45.813","0.000000"
> "10/14/2019 12:23:46.814","0.000000"
> "10/14/2019 12:23:47.815","0.000000"
> "10/14/2019 12:23:48.815","3.122951"
> "10/14/2019 12:23:49.816","0.000000"
> "10/14/2019 12:23:50.817","1.561464"
> "10/14/2019 12:23:51.817","0.000000"
> "10/14/2019 12:23:52.818","0.000000"
> "10/14/2019 12:23:53.819","7.807248"
> "10/14/2019 12:23:54.819","0.000000"
> "10/14/2019 12:23:55.820","3.122925"
> "10/14/2019 12:23:56.821","0.000000"
> "10/14/2019 12:23:57.821","0.000000"
> "10/14/2019 12:23:58.822","3.122931"
> The command completed successfully.

The value seems to way huge with the metricbeats at the same time:
![image](https://user-images.githubusercontent.com/24888031/66746996-b79a9b00-ee83-11e9-8b1f-d164cae0e076.png)

And its the same issue with this query as well (`\Process(*)\% User Time`)

OS: Windows 2012 R2
      32 GB RAM
      64-Bit Operating System

Please let me know if you need any additional details. Thanks !

**Comment by narph** [comment]
hi @prakash1243, I was able to reproduce this issue and provide a potential fix https://github.com/elastic/beats/pull/14039.  
Let us know if it worked or not in your case.
(Thanks for bringing this to our attention)

**Comment by prakash1243** [comment]
@narph - Sure, I'll take the latest snapshot version as soon as the PR gets merged to the master :) 
Thanks for your quick response.

**Comment by narph** [comment]
hi @prakash1243 , the fix is merged in, let us know if this helped or not in your case

**Comment by prakash1243** [comment]
It worked. thanks !
