### ISSUE TITLE
 Beats - fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by Vishnugmavelil** [elastic/beats#14031]
Hello Everyone

I have checked out the branch 7.4 and created a new beat called httpbeat for capturing the request and process it. While running it, I encountered the below issue

Beat Version: 7.4.0

**Error Log:**

`fatal error: concurrent map read and map write
goroutine 1 [running]:
runtime.throw(0x2593c1d, 0x21)
    /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0003766c0 sp=0xc000376690 pc=0x101add2
runtime.mapaccess2(0x24b45c0, 0xc000336000, 0xc0003bdd20, 0xc0003bdd20, 0x1c)
    /usr/local/go/src/runtime/map.go:472 +0x284 fp=0xc000376708 sp=0xc0003766c0 pc=0xffb164
reflect.mapaccess(0x24b45c0, 0xc000336000, 0xc0003bdd20, 0x25837be)
    /usr/local/go/src/runtime/map.go:1321 +0x3f fp=0xc000376740 sp=0xc000376708 pc=0xffd53f
reflect.Value.MapIndex(0x24b45c0, 0xc000336000, 0x15, 0x22b6aa0, 0xc0003bdd20, 0x98, 0xc000376870, 0xc0001ad998, 0x1bae9598a26b2701)
    /usr/local/go/src/reflect/value.go:1112 +0x10a fp=0xc0003767a0 sp=0xc000376740 pc=0x10b0d1a
encoding/json.mapEncoder.encode(0xc000339af0, 0xc00034a070, 0x24b45c0, 0xc000336000, 0x15, 0x24b0100)
    /usr/local/go/src/encoding/json/encode.go:702 +0x303 fp=0xc0003768e8 sp=0xc0003767a0 pc=0x10f6a83
encoding/json.mapEncoder.encode-fm(0xc00034a070, 0x24b45c0, 0xc000336000, 0x15, 0xc000370100)
    /usr/local/go/src/encoding/json/encode.go:678 +0x64 fp=0xc000376928 sp=0xc0003768e8 pc=0x1102624
encoding/json.(*encodeState).reflectValue(0xc00034a070, 0x24b45c0, 0xc000336000, 0x15, 0x23d0100)
    /usr/local/go/src/encoding/json/encode.go:334 +0x82 fp=0xc000376960 sp=0xc000376928 pc=0x10f3d22
encoding/json.(*encodeState).marshal(0xc00034a070, 0x24b45c0, 0xc000336000, 0x706d4c760100, 0x0, 0x0)
    /usr/local/go/src/encoding/json/encode.go:306 +0xee fp=0xc0003769a8 sp=0xc000376960 pc=0x10f37ce
encoding/json.Marshal(0x24b45c0, 0xc000336000, 0xff9bb8, 0x8, 0x24b2400, 0xe6fd36985e48e301, 0xc000316020)
    /usr/local/go/src/encoding/json/encode.go:160 +0x52 fp=0xc000376a20 sp=0xc0003769a8 pc=0x10f2df2
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/common.marshalUnmarshal(0x24b45c0, 0xc000336000, 0x24ab5c0, 0xc000316020, 0x24b45c0, 0x2f472df2b84b6100)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/common/event.go:254 +0x39 fp=0xc000376a68 sp=0xc000376a20 pc=0x1420329
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/common.normalizeValue(0x24b45c0, 0xc000336000, 0xc000377270, 0x2, 0xa, 0x22b05a0, 0xc00016c188, 0x0, 0x0, 0x0)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/common/event.go:235 +0xa9f fp=0xc000376cd8 sp=0xc000376a68 pc=0x141e74f
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/common.normalizeMap(0xc000336060, 0xc000377270, 0x1, 0xa, 0x0, 0xbf76b5d6400e0300, 0x6aa0828a0def7edb, 0xf40654994967cfdc)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/common/event.go:64 +0x1a4 fp=0xc000376e20 sp=0xc000376cd8 pc=0x141c9f4
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/common.normalizeValue(0x2317ea0, 0xc000336060, 0xc000377270, 0x1, 0xa, 0x85024dc0b4d1f5d0, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/common/event.go:209 +0x117f fp=0xc000377090 sp=0xc000376e20 pc=0x141ee2f
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/common.normalizeMap(0xc0004502d0, 0xc000377270, 0x0, 0xa, 0x0, 0x9ad444c41e0fd906, 0xfaa9a7b2a1b6aeef, 0x2dcfc88a0bd794af)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/common/event.go:64 +0x1a4 fp=0xc0003771d8 sp=0xc000377090 pc=0x141c9f4
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/common.ConvertToGenericEvent(0xc0004502d0, 0x203000)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/common/event.go:48 +0x84 fp=0xc000377320 sp=0xc0003771d8 pc=0x141c724
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/publisher/processing.glob..func2(0xc000158240, 0xff9329, 0xc000158240, 0x40)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/publisher/processing/processors.go:49 +0x48 fp=0xc000377358 sp=0xc000377320 pc=0x1593ec8
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/publisher/processing.(*processorFn).Run(0xc000185360, 0xc000158240, 0x38, 0x40, 0xc000158240)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/publisher/processing/processors.go:131 +0x34 fp=0xc000377388 sp=0xc000377358 pc=0x1593784
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/publisher/processing.(*group).Run(0xc00027dbc0, 0xc000158240, 0xf6b6cbe12111a1ed, 0x271fe94d564046cf, 0x1ce1b0e8597cf06a)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/publisher/processing/processors.go:101 +0x94 fp=0xc000377438 sp=0xc000377388 pc=0x1593424
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/publisher/pipeline.(*client).publish(0xc00027a980, 0xbf6118691a3e05fa, 0x59042a4de3, 0x3b57d20, 0x0, 0xc0004502d0, 0x0, 0x0, 0x0)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/publisher/pipeline/client.go:89 +0x5c3 fp=0xc000377658 sp=0xc000377438 pc=0x15975b3
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/publisher/pipeline.(*client).Publish(0xc00027a980, 0xbf6118691a3e05fa, 0x59042a4de3, 0x3b57d20, 0x0, 0xc0004502d0, 0x0, 0x0, 0x0)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/publisher/pipeline/client.go:68 +0x9c fp=0xc0003776b8 sp=0xc000377658 pc=0x1596fbc
github.com/vishnugmavelil/httpbeat/beater.(*httpbeat).Run(0xc00037e0f0, 0xc00045ed80, 0x3b75ae0, 0x1)
    /go/src/github.com/vishnugmavelil/httpbeat/beater/httpbeat.go:66 +0x113 fp=0xc0003777c8 sp=0xc0003776b8 pc=0x142fec3
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/cmd/instance.(*Beat).launch(0xc00045ed80, 0x2571756, 0x9, 0x2571756, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go:432 +0x61d fp=0xc000377a90 sp=0xc0003777c8 pc=0x2138b8d
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/cmd/instance.Run.func1(0x2571756, 0x9, 0x2571756, 0x9, 0x0, 0x0, 0xc0004e3ca0, 0x2627a48, 0x0, 0x0)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go:182 +0x552 fp=0xc000377c40 sp=0xc000377a90 pc=0x21415e2
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/cmd/instance.Run(0x2571756, 0x9, 0x2571756, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go:183 +0x7e fp=0xc000377ca0 sp=0xc000377c40 pc=0x213710e
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/cmd.genRunCmd.func1(0xc0001f5180, 0xc0003bdd60, 0x0, 0x1)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/libbeat/cmd/run.go:36 +0x9d fp=0xc000377df8 sp=0xc000377ca0 pc=0x215b79d
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001f5180, 0xc00000e090, 0x1, 0x1, 0xc0001f5180, 0xc00000e090)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/vendor/github.com/spf13/cobra/command.go:704 +0x289 fp=0xc000377ea8 sp=0xc000377df8 pc=0x2149e29
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0001f5180, 0x215d2ba, 0xc0004e3f88, 0xc00004e0b8)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/vendor/github.com/spf13/cobra/command.go:785 +0x2ca fp=0xc000377f68 sp=0xc000377ea8 pc=0x214a7ca
github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/vendor/github.com/spf13/cobra.(*Command).Execute(...)
    /go/src/github.com/vishnugmavelil/httpbeat/vendor/github.com/elastic/beats/vendor/github.com/spf13/cobra/command.go:738
main.main()
    /go/src/github.com/vishnugmavelil/httpbeat/main.go:12 +0x30 fp=0xc000377f98 sp=0xc000377f68 pc=0x215d310
runtime.main()
    /usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc000377fe0 sp=0xc000377f98 pc=0x101d49c
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000377fe8 sp=0xc000377fe0 pc=0x104b171`

**Comment by andrewkroh** [comment]
Do you have some shared map that you are adding to each event you produce? You might need to clone it so that each event has its own copy.

Another helpful thing to do is to build your beat with the race detector (`go build -race`) enabled and see if it detects any data races and points you to them.

**Comment by andrewkroh** [comment]
Please reopen if need help tracking down the race.
