### ISSUE TITLE
Deprecate Beats central management docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#14045]
Central management docs need to be marked as deprecated.

If we want to add more explanation around the deprecation (beyond our standard boiler place text), we should say: "Beats central management is now deprecated. We’re working on a comprehensive solution to replace this feature."

**Comment by mattapperson** [comment]
@skearns64 pinging you as this relates to the discussion earlier in case you care to comment

**Comment by mattapperson** [comment]
Related to this PR to make this change in code https://github.com/elastic/kibana/pull/48097

**Comment by dedemorton** [comment]
Fixed in #14104. Let me know if you want me to tweak the wording, or I can remove it entirely and just indicate that CM is deprecated in 7.5.0.
