### ISSUE TITLE
[Auditbeat] Add syscall names to to violated-seccomp-policy events

### ISSUE THREAD

**Issue by jordansissel** [elastic/beats#14055]
**Describe the enhancement:**

(Tested on Auditbeat 6.5.4)

when `event.action` is `violated-seccomp-policy`, there's `auditd.data.syscall` which is a number, but I want a name.

**Describe a specific use case for the enhancement or feature:**

When trying to understand what kinds of syscalls are causing seccomp violations, it would be more useful to have these syscalls available by name.

Here's a sample chart which isn't really useful unless you have memorized the syscall -> name mappings, and I don''t have these memorized ;)

![firefox_0IaUlbaj2B](https://user-images.githubusercontent.com/131818/66796104-8211a400-eebb-11e9-81b7-a189d7339e04.png)

cc @stiltz who may be interested in this

**Comment by andrewkroh** [comment]
I believe this stems from elastic/go-libaudit not enrich the seccomp events with the syscall name. It's only happening on the audit events triggered by rules to watch a syscall.

https://github.com/elastic/go-libaudit/blob/db7d4996da54bed87ecf047e6c19d7656d237082/auparse/auparse.go#L407

**Comment by andrewkroh** [comment]
I opened https://github.com/elastic/go-libaudit/pull/64 to add enrichment of arch, syscall, and signal name.

FYI @spinscale

**Comment by andrewkroh** [comment]
PR to update Beats with new go-libaudit release: https://github.com/elastic/beats/pull/19300
