### ISSUE TITLE
Add fields with datatype ip to default_field in index template

### ISSUE THREAD

**Issue by jderose9** [elastic/beats#14050]
**Describe the enhancement:**
When generating the index template from filebeat, ip fields are not included

**Describe a specific use case for the enhancement or feature:**
It would make sense for a Kibana user to be able to enter an IP in the search bar and return all logging documents associated with that ip.

It looks like there was some discussion or plans around including this for 7.x, but it doesn't appear that it was addressed further:
https://github.com/elastic/beats/pull/11399

**Comment by opoplawski** [comment]
This is definitely biting people:
https://discuss.elastic.co/t/search-for-ip-address-does-not-return-results/229326/3
https://discuss.elastic.co/t/unable-to-search-all-fields-for-ip-address/208141
