### ISSUE TITLE
Can http endpoint of filebeat /stats expose metrics for monitoring the file harvest stats

### ISSUE THREAD

**Issue by DeeeFOX** [elastic/beats#14054]
## Ask for file related stats for monitoring

I do want to keep track of these stats, but finding out that current given stats metrics from /stats endpoint are not satisfied:

* what files(absolutely path) are being tracking/harvested/harvesting
* current file offset/harvested offset of every tracking files
* last successful harvest time of every files

**Comment by DeeeFOX** [comment]
hello？

**Comment by sayden** [comment]
Hi @DeeeFOX :slightly_smiling_face: 

Thanks for contributing with some enhancements. Please, can you briefly describe your use case too? Why is it useful for you to have such data?

I have concerns that to expose those metrics might impact Filebeat performance while harvesting.

**Comment by DeeeFOX** [comment]
Thanks for your considering @sayden 

In our use case, we are monitoring filebeat by prometheus, and we do want to know such things:
* 1. What exactly the files are filebeat harvesting now when we configure the path like:

* 2. Whether the log collection rate can keep up with the write rate (of each file that filebeat watching)

**Comment by sayden** [comment]
Sorry, I didn't explain myself properly.

What is important to know is what you are trying to solve more than how. I'm thinking that we have a lot of ways to understand how Filebeat is working and some of them might help you with your use case. For example, have you seen [this section in docs?](https://www.elastic.co/guide/en/beats/filebeat/current/how-filebeat-works.html) 

I understand that:

- Knowing which files are being harvested and...
- What's is the log collection rate

... are your solutions for your particular use case so, my question is, what's your use case? :slightly_smiling_face: Are you having issues with Filebeat and some particularly big files? Do you need to ensure somehow that every byte is being transferred?

I hope it's more clear now :slightly_smiling_face:

**Comment by DeeeFOX** [comment]
Oh my fault @sayden

I use filebeat to collect logs in time. But found some problem when :

* Q1: 

    - Situation: When some files change to write debug logs, fb will suddenly suffer a huge events wave, and it will affect other files' collection(make latency happen).

    - By FB's metrics: We want to find out which file is the main problem.

* Q2:

    - Situation: When latency of collection happen on a file suddenly

    - By FB's metrics: We want to find out whether the writing rate of this file is suddenly rising, or this is a new, huge file that suddenly being moved into the watching paths.

...

So if filebeat expose metrics of the collection stats of files, it will help me a lot to solve problems above.
