### ISSUE TITLE
[Metricbeat] - vsphere module dashboards

### ISSUE THREAD

**Issue by philippkahr** [elastic/beats#14101]
# Metricbeat Module VSPHERE

Hi,

I created some dashboards for the metricbeat vsphere module, which is divided into two separate dashboards.

1. VSphere hosts
As VSphere has ESXi hosts running and an ESXi host is a machine that runs all VMs, there is a dashboard dedicated to seeing how well one ESXi host or the entire fleet is doing.

2. VSphere VM
Currently I am extracting all the data from the VM dataset, which is not much, however, there is one interesting thing. I build a heatmap that shows if a virtual machine has been moved between the hosts.

I am not quite certain on how I should proceed with the dashboards, maybe someone can help me out here. I dumped the JSON which I exported with the `export dashboard` into a folder `dashboard` in the `beats/metricbeat/module/vsphere/dashboards`. The current VSphere module does not have a `module.yml` and I'm not sure if it's ok if I just create one with all the info.

I included some sample screenshots, please note that I had to add white boxes around some information since it is collected from a production cluster.

![image](https://user-images.githubusercontent.com/12175559/66955097-fbe39200-f061-11e9-9218-bb5c95389d6d.png)
![image](https://user-images.githubusercontent.com/12175559/66955130-056cfa00-f062-11e9-83f5-c495c5d117f9.png)
![image](https://user-images.githubusercontent.com/12175559/66955135-069e2700-f062-11e9-9034-e6d3992c2fe5.png)
![image](https://user-images.githubusercontent.com/12175559/66955141-0867ea80-f062-11e9-8856-dfede44c2bdc.png)
![image](https://user-images.githubusercontent.com/12175559/66955148-09991780-f062-11e9-867f-e71f2d341a1c.png)
![image](https://user-images.githubusercontent.com/12175559/66955152-0aca4480-f062-11e9-9497-d807678918b1.png)

**Comment by ChrsMark** [comment]
@philippkahr awesome! You can start with opening a PR (see https://github.com/elastic/beats/pull/14021 or https://github.com/elastic/beats/pull/11170).

The dashboard file should be located in `metricbeat/module/vsphere/_meta/kibana/7/dashboard/Metricbeat-vsphere-overview.json`

The process I follow to export/import dashboards is:
(under `/beats/metricbeat` directory)
1. `MODULE=vsphere ID=c359a6c0-4242-11e9-a1b4-79a7ae42ab61 mage exportDashboard`
2. `make import-dashboards`

Another thing you should have in mind is the name conventions to follow. Visualisations' names should  be like `VMs Per Host [Metricbeat VSphere]`

Finally yes, you will need to add a `module.yml`.

**Comment by philippkahr** [comment]
Thanks for the instructions! :)
