### ISSUE TITLE
Filebeat 7.4.0 and Netflow poor performance

### ISSUE THREAD

**Issue by fredbcode** [elastic/beats#14112]
Hello,

I'm using logstash and elasticsearch (7.4.0) but Filebeat is not working well 

With logstash I have more or less 5000 in elastic indexing rates, by server, each second 
With filebeat more or less 200 without any explicit warning or error 

I guess I'm missing something, but ... 

 timeout 20 tcpdump -i any -n port 2055 -> Netflow to Filebeat
124471 packets captured
124689 packets received by filter
209 packets dropped by kernel

netflow.yml
```
- module: netflow
  log:
    enabled: true
    var:
      netflow_host: 0.0.0.0
      netflow_port: 2055
      max_message_size: 1000
      queue_size: 32000
```

`filebeat -e -E output.elasticsearch.workers=4 -E output.elasticsearch.hosts=http://elastic:9200 -E logging.level=info `

Log level Info
```
Oct 17 17:10:49  app_filebeat_1[1368]: 2019-10-17T15:10:49.210Z#011INFO#011[monitoring]#011log/log.go:145#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":210620,"time":{"ms":4866}},"total":{"ticks":435360,"time":{"ms":10202},"value":435360},"user":{"ticks":224740,"time":{"ms":5336}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":8},"info":{"ephemeral_id":"f2b417fb-c27e-4da9-bb0d-52306959a03a","uptime":{"ms":1290038}},"memstats":{"gc_next":10716432,"memory_alloc":6919608,"memory_total":5364614904},"runtime":{"goroutines":28}},"filebeat":{"events":{"added":19,"done":19},"harvester":{"open_files":0,"running":0},"input":{"netflow":{"flows":19,"packets":{"received":63116}}}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"acked":19,"batches":2,"total":19},"read":{"bytes":822},"write":{"bytes":35731}},"pipeline":{"clients":2,"events":{"active":0,"published":19,"total":19},"queue":{"acked":19}}},"registrar":{"states":{"current":0}},"system":{"load":{"1":0.97,"15":0.66,"5":0.75,"norm":{"1":0.0404,"15":0.0275,"5":0.0313}}}}}}
Oct 17 17:11:19  app_filebeat_1[1368]: 2019-10-17T15:11:19.210Z#011INFO#011[monitoring]#011log/log.go:145#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":215600,"time":{"ms":4983}},"total":{"ticks":445580,"time":{"ms":10222},"value":445580},"user":{"ticks":229980,"time":{"ms":5239}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":8},"info":{"ephemeral_id":"f2b417fb-c27e-4da9-bb0d-52306959a03a","uptime":{"ms":1320038}},"memstats":{"gc_next":10716944,"memory_alloc":7821280,"memory_total":5487365728},"runtime":{"goroutines":28}},"filebeat":{"events":{"added":2,"done":2},"harvester":{"open_files":0,"running":0},"input":{"netflow":{"flows":2,"packets":{"received":63119}}}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"acked":2,"batches":1,"total":2},"read":{"bytes":354},"write":{"bytes":4019}},"pipeline":{"clients":2,"events":{"active":0,"published":2,"total":2},"queue":{"acked":2}}},"registrar":{"states":{"current":0}},"system":{"load":{"1":1.06,"15":0.68,"5":0.79,"norm":{"1":0.0442,"15":0.0283,"5":0.0329}}}}}}
Oct 17 17:11:49  app_filebeat_1[1368]: 2019-10-17T15:11:49.210Z#011INFO#011[monitoring]#011log/log.go:145#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":220380,"time":{"ms":4778}},"total":{"ticks":455640,"time":{"ms":10054},"value":455640},"user":{"ticks":235260,"time":{"ms":5276}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":8},"info":{"ephemeral_id":"f2b417fb-c27e-4da9-bb0d-52306959a03a","uptime":{"ms":1350038}},"memstats":{"gc_next":10707088,"memory_alloc":6092728,"memory_total":5607304056,"rss":4096},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":0,"running":0},"input":{"netflow":{"packets":{"received":61800}}}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":2,"events":{"active":0}}},"registrar":{"states":{"current":0}},"system":{"load":{"1":0.97,"15":0.68,"5":0.79,"norm":{"1":0.0404,"15":0.0283,"5":0.0329}}}}}}
Oct 17 17:12:19  app_filebeat_1[1368]: 2019-10-17T15:12:19.210Z#011INFO#011[monitoring]#011log/log.go:145#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":225370,"time":{"ms":4988}},"total":{"ticks":465600,"time":{"ms":9960},"value":465600},"user":{"ticks":240230,"time":{"ms":4972}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":8},"info":{"ephemeral_id":"f2b417fb-c27e-4da9-bb0d-52306959a03a","uptime":{"ms":1380040}},"memstats":{"gc_next":10737744,"memory_alloc":9495832,"memory_total":5730813384,"rss":4096},"runtime":{"goroutines":28}},"filebeat":{"events":{"added":28,"done":28},"harvester":{"open_files":0,"running":0},"input":{"netflow":{"flows":28,"packets":{"received":62401}}}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"acked":28,"batches":7,"total":28},"read":{"bytes":2588},"write":{"bytes":53961}},"pipeline":{"clients":2,"events":{"active":0,"published":28,"total":28},"queue":{"acked":28}}},"registrar":{"states":{"current":0}},"system":{"load":{"1":1,"15":0.7,"5":0.81,"norm":{"1":0.0417,"15":0.0292,"5":0.0338}}}}}}
```

Not directly related,but there is no warning about missing netflow template, how we can know if there is something wrong about this ? Logstash logs with 'Can't decode netflow ... missing template" and after we should 1) add a template or/and 2) wait a template from router

**Comment by andrewkroh** [comment]
There were a few issues that were fixed recently with the netflow input and will be released in v7.4.1. One of them is https://github.com/elastic/beats/pull/13846.

If you want to test out a pre-release version you can download it from the CI servers at https://beats-ci.elastic.co/job/elastic+beats+7.4+multijob-package-linux/lastSuccessfulBuild/gcsObjects/.

**Comment by fredbcode** [comment]
Ok tested, but the indexing rate still at least /10 less than my logstash docker image
 
```
Oct 22 15:35:07  app_filebeat_1[1368]: 2019-10-22T13:35:07.793Z#011INFO#011[monitoring]#011log/log.go:145#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":133490,"time":{"ms":4701}},"total":{"ticks":352600,"time":{"ms":12397},"value":352600},"user":{"ticks":219110,"time":{"ms":7696}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":7},"info":{"ephemeral_id":"e7e9ed2b-7085-4b97-9905-3ff870cdb97b","uptime":{"ms":840065}},"memstats":{"gc_next":9212752,"memory_alloc":6533296,"memory_total":22195636856},"runtime":{"goroutines":24}},"filebeat":{"events":{"active":-60,"added":961,"done":1021},"harvester":{"open_files":0,"running":0},"input":{"netflow":{"flows":961,"packets":{"received":67915}}}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"acked":1021,"active":-50,"batches":32,"total":971},"read":{"bytes":17947},"write":{"bytes":1962998}},"pipeline":{"clients":1,"events":{"active":0,"published":961,"total":961},"queue":{"acked":1021}}},"registrar":{"states":{"current":0}},"system":{"load":{"1":0.36,"15":2.09,"5":0.88,"norm":{"1":0.015,"15":0.0871,"5":0.0367}}}}}}
Oct 22 15:35:37  app_filebeat_1[1368]: 2019-10-22T13:35:37.793Z#011INFO#011[monitoring]#011log/log.go:145#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":138630,"time":{"ms":5146}},"total":{"ticks":365790,"time":{"ms":13198},"value":365790},"user":{"ticks":227160,"time":{"ms":8052}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":7},"info":{"ephemeral_id":"e7e9ed2b-7085-4b97-9905-3ff870cdb97b","uptime":{"ms":870064}},"memstats":{"gc_next":9226384,"memory_alloc":5100264,"memory_total":23005497984},"runtime":{"goroutines":24}},"filebeat":{"events":{"added":1335,"done":1335},"harvester":{"open_files":0,"running":0},"input":{"netflow":{"flows":1335,"packets":{"received":69809}}}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"acked":1335,"batches":38,"total":1335},"read":{"bytes":21706},"write":{"bytes":2700237}},"pipeline":{"clients":1,"events":{"active":0,"published":1335,"total":1335},"queue":{"acked":1335}}},"registrar":{"states":{"current":0}},"system":{"load":{"1":0.52,"15":2.05,"5":0.87,"norm":{"1":0.0217,"15":0.0854,"5":0.0363}}}}}}
```

**Comment by adriansr** [comment]
Hi @fredbcode,

In my tests Filebeat's netflow input is able to decode around 35k flows per second, which means in practice indexing the flows to ES is the bottleneck.

Those numbers you have are way too low, more so in comparison with the number or packets received.

Can you share a pcap so I can see what's wrong? You can send me an email to adrian at elastic.co if you don't want to share it publicly.

**Comment by adriansr** [comment]
Ups, closed the wrong issue

**Comment by fredbcode** [comment]
Hi Adrian,

Unfortunately, I can't sorry 

How do you generate this flow ? with a tool or with production servers ? Here, this is samplicate netflow sources

I'm trying with output file and same issue the file grow very very slowly 

Not directly related but with output-file the directory is not created 

path: "/tmp/filebeat"

filebeat is generated in /

Related to: #14126 the command-line should take precedence over an existing value, same issue for any entries, eg: I can't disabled/enable elastic if there is an entry in config file

**Comment by fredbcode** [comment]
The load average is low, 0.30, it's like packets are silently dropped

**Comment by fredbcode** [comment]
The issue seems (to me) in input not output

As you can here in debug mode there is more or less on packet by second in input
In same time tcpdump 6200 netflow packets 
I forgot to mention I'm using docker for filebeat/elastic/logstash 

`
Oct 22 17:14:07  app_filebeat_1[1342]: 2019-10-22T15:14:07.315Z#011DEBUG#011[netflow]#011netflow/input.go:193#011Stats total:[ packets=508728 dropped=0 flows=5987 queue_len=0 ] delta:[ packets/s=1948 dropped/s=0 flows/s=27 queue_len/s=+0 ]
Oct 22 17:14:08  app_filebeat_1[1342]: 2019-10-22T15:14:08.315Z#011DEBUG#011[netflow]#011netflow/input.go:193#011Stats total:[ packets=510685 dropped=0 flows=5987 queue_len=0 ] delta:[ packets/s=1957 dropped/s=0 flows/s=0 queue_len/s=+0 ]
Oct 22 17:14:09  app_filebeat_1[1342]: 2019-10-22T15:14:09.315Z#011DEBUG#011[netflow]#011netflow/input.go:193#011Stats total:[ packets=512666 dropped=0 flows=5987 queue_len=0 ] delta:[ packets/s=1981 dropped/s=0 flows/s=0 queue_len/s=+0 ]
Oct 22 17:14:10  app_filebeat_1[1342]: 2019-10-22T15:14:10.315Z#011DEBUG#011[netflow]#011netflow/input.go:193#011Stats total:[ packets=514657 dropped=0 flows=6041 queue_len=0 ] delta:[ packets/s=1991 dropped/s=0 flows/s=54 queue_len/s=+0 ]
Oct 22 17:14:11  app_filebeat_1[1342]: 2019-10-22T15:14:11.315Z#011DEBUG#011[netflow]#011netflow/input.go:193#011Stats total:[ packets=516557 dropped=0 flows=6072 queue_len=0 ] delta:[ packets/s=1900 dropped/s=0 flows/s=31 queue_len/s=+0 ]
Oct 22 17:14:12  app_filebeat_1[1342]: 2019-10-22T15:14:12.315Z#011DEBUG#011[netflow]#011netflow/input.go:193#011Stats total:[ packets=518416 dropped=0 flows=6099 queue_len=0 ] delta:[ packets/s=1859 dropped/s=0 flows/s=27 queue_len/s=+0 ]
Oct 22 17:14:13  app_filebeat_1[1342]: 2019-10-22T15:14:13.315Z#011DEBUG#011[netflow]#011netflow/input.go:193#011Stats total:[ packets=520366 dropped=0 flows=6099 queue_len=0 ] delta:[ packets/s=1950 dropped/s=0 flows/s=0 queue_len/s=+0 ]
Oct 22 17:14:14  app_filebeat_1[1342]: 2019-10-22T15:14:14.315Z#011DEBUG#011[netflow]#011netflow/input.go:193#011Stats total:[ packets=522309 dropped=0 flows=6126 queue_len=0 ] delta:[ packets/s=1943 dropped/s=0 flows/s=27 queue_len/s=+0 ]
Oct 22 17:14:15  app_filebeat_1[1342]: 2019-10-22T15:14:15.315Z#011DEBUG#011[netflow]#011netflow/input.go:193#011Stats total:[ packets=524278 dropped=0 flows=6153 queue_len=0 ] delta:[ packets/s=1969 dropped/s=0 flows/s=27 queue_len/s=+0 ]
Oct 22 17:14:16  app_filebeat_1[1342]: 2019-10-22T15:14:16.315Z#011DEBUG#011[netflow]#011netflow/input.go:193#011Stats total:[ packets=526275 dropped=0 flows=6207 queue_len=0 ] delta:[ packets/s=1997 dropped/s=0 flows/s=54 queue_len/s=+0 ]
Oct 22 17:14:17  app_filebeat_1[1342]: 2019-10-22T15:14:17.315Z#011DEBUG#011[netflow]#011netflow/input.go:193#011Stats total:[ packets=528207 dropped=0 flows=6207 queue_len=0 ] delta:[ packets/s=1932 dropped/s=0 flows/s=0 queue_len/s=+0 ]
Oct 22 17:14:18  app_filebeat_1[1342]: 2019-10-22T15:14:18.315Z#011DEBUG#011[netflow]#011netflow/input.go:193#011Stats total:[ packets=530145 dropped=0 flows=6234 queue_len=0 ] delta:[ packets/s=1938 dropped/s=0 flows/s=27 queue_len/s=+0 ]
Oct 22 17:14:19  app_filebeat_1[1342]: 2019-10-22T15:14:19.315Z#011DEBUG#011[netflow]#011netflow/input.go:193#011Stats total:[ packets=532071 dropped=0 flows=6234 queue_len=0 ] delta:[ packets/s=1926 dropped/s=0 flows/s=0 queue_len/s=+0 ]
Oct 22 17:14:20  app_filebeat_1[1342]: 2019-10-22T15:14:20.315Z#011DEBUG#011[netflow]#011netflow/input.go:193#011Stats total:[ packets=533976 dropped=0 flows=6265 queue_len=0 ] delta:[ packets/s=1905 dropped/s=0 flows/s=31 queue_len/s=+0 ]
`

**Comment by adriansr** [comment]
@fredbcode have you filtered those logs?

7.4.1 debugs logs should include a message like `Packet from:<ip> src:<obs.domain> seq:<sequence number>` for each packet received. Looks like you're still running 7.4.0.

**Comment by fredbcode** [comment]
Oups yes sorry ! I missed an error with package filebeat-7.4.1-SNAPSHOT-amd64.deb, netlow is missing so I'm using the previous docker image 

There is no file about netflow, and when I enable it with "filebeat modules enable netflow" I have 
"Module netflow doesn't exist !"

I'm doing something wrong ?
```

ls -la /etc/filebeat/modules.d/
total 84
drwxr-xr-x 2 root root 4096 Oct 22 17:48 .
drwxr-xr-x 3 root root 4096 Oct 22 17:48 ..
-rw-r--r-- 1 root root  475 Oct 18 11:05 apache.yml.disabled
-rw-r--r-- 1 root root  280 Oct 18 11:05 auditd.yml.disabled
-rw-r--r-- 1 root root  964 Oct 18 11:05 elasticsearch.yml.disabled
-rw-r--r-- 1 root root  376 Oct 18 11:05 haproxy.yml.disabled
-rw-r--r-- 1 root root  651 Oct 18 11:05 icinga.yml.disabled
-rw-r--r-- 1 root root  470 Oct 18 11:05 iis.yml.disabled
-rw-r--r-- 1 root root  398 Oct 18 11:05 kafka.yml.disabled
-rw-r--r-- 1 root root  293 Oct 18 11:05 kibana.yml.disabled
-rw-r--r-- 1 root root  470 Oct 18 11:05 logstash.yml.disabled
-rw-r--r-- 1 root root  296 Oct 18 11:05 mongodb.yml.disabled
-rw-r--r-- 1 root root  471 Oct 18 11:05 mysql.yml.disabled
-rw-r--r-- 1 root root  287 Oct 18 11:05 nats.yml.disabled
-rw-r--r-- 1 root root  472 Oct 18 11:05 nginx.yml.disabled
-rw-r--r-- 1 root root  495 Oct 18 11:05 osquery.yml.disabled
-rw-r--r-- 1 root root  305 Oct 18 11:05 postgresql.yml.disabled
-rw-r--r-- 1 root root  566 Oct 18 11:05 redis.yml.disabled
-rw-r--r-- 1 root root  266 Oct 18 11:05 santa.yml.disabled
-rw-r--r-- 1 root root  477 Oct 18 11:05 system.yml.disabled
-rw-r--r-- 1 root root  302 Oct 18 11:05 traefik.yml.disabled
```

**Comment by adriansr** [comment]
It looks like you installed the OSS version (`filebeat-oss-...`), which only includes Apache-licensed modules, not the ones covered by the Elastic license.

You need this one https://storage.cloud.google.com/beats-ci-artifacts/snapshots/filebeat/filebeat-7.4.1-SNAPSHOT-amd64.deb

**Comment by fredbcode** [comment]
Ho, thank you Adrian, I didn't know

It's very better, but still have something weird, I guess I reach some unknown limitations

One samplicate (netflow) -> three filebeat -> elastic cluster 

I'm looking the kibana indexing rate 

With only one filebeat I loss more or less 30% but there is no message in syslog filebeat/elastic and the load average is at worst 3 without memory problem

If I share the load to a second server 50/50, indexing rate up 

Primary shard: 4524 /s one server
Primary shard: 6024 /s two servers
Primary shard: 6700 /s three servers

With tcpdump 7700 netflow packets by second 

In syslog I'm seeing that many packets are "dropped" 

```

Oct 24 10:53:42  app_filebeat_1[1368]: 2019-10-24T08:53:42.040Z#011INFO#011[monitoring]#011log/log.go:145#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":242130,"time":{"ms":2856}},"total":{"ticks":905960,"time":{"ms":11019},"value":905960},"user":{"ticks":663830,"time":{"ms":8163}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":7},"info":{"ephemeral_id":"08c7516b-94ff-4db2-acbc-43ac3de671ee","uptime":{"ms":2130404}},"memstats":{"gc_next":230446656,"memory_alloc":189801104,"memory_total":119235191136},"runtime":{"goroutines":25}},"filebeat":{"events":{"added":20130,"done":20130},"harvester":{"open_files":0,"running":0},"input":{"netflow":{"flows":20119,"packets":{"dropped":12666,"received":61616}}}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"acked":20130,"batches":403,"total":20130},"read":{"bytes":270921},"write":{"bytes":40196037}},"pipeline":{"clients":1,"events":{"active":4117,"published":20130,"total":20130},"queue":{"acked":20130}}},"registrar":{"states":{"current":0}},"system":{"load":{"1":3.83,"15":3.53,"5":3.2,"norm":{"1":0.1596,"15":0.1471,"5":0.1333}}}}}}

Oct 24 10:54:12  app_filebeat_1[1368]: 2019-10-24T08:54:12.041Z#011INFO#011[monitoring]#011log/log.go:145#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":244950,"time":{"ms":2824}},"total":{"ticks":917460,"time":{"ms":11500},"value":917460},"user":{"ticks":672510,"time":{"ms":8676}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":7},"info":{"ephemeral_id":"08c7516b-94ff-4db2-acbc-43ac3de671ee","uptime":{"ms":2160404}},"memstats":{"gc_next":250505200,"memory_alloc":144038352,"memory_total":120506499672},"runtime":{"goroutines":25}},"filebeat":{"events":{"added":20380,"done":20380},"harvester":{"open_files":0,"running":0},"input":{"netflow":{"flows":20382,"packets":{"dropped":2502,"received":72088}}}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"acked":20380,"batches":408,"total":20380},"read":{"bytes":273644},"write":{"bytes":40829360}},"pipeline":{"clients":1,"events":{"active":4117,"published":20380,"total":20380},"queue":{"acked":20380}}},"registrar":{"states":{"current":0}},"system":{"load":{"1":3.76,"15":3.54,"5":3.24,"norm":{"1":0.1567,"15":0.1475,"5":0.135}}}}}}
Oct 24 10:54:42  app_filebeat_1[1368]: 2019-10-24T08:54:42.041Z#011INFO#011[monitoring]#011log/log.go:145#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":247750,"time":{"ms":2796}},"total":{"ticks":928820,"time":{"ms":11359},"value":928820},"user":{"ticks":681070,"time":{"ms":8563}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":7},"info":{"ephemeral_id":"08c7516b-94ff-4db2-acbc-43ac3de671ee","uptime":{"ms":2190404}},"memstats":{"gc_next":252866240,"memory_alloc":132339456,"memory_total":121786436336},"runtime":{"goroutines":25}},"filebeat":{"events":{"added":20980,"done":20980},"harvester":{"open_files":0,"running":0},"input":{"netflow":{"flows":20982,"packets":{"dropped":3575,"received":70844}}}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"acked":20980,"batches":420,"total":20980},"read":{"bytes":282277},"write":{"bytes":42129099}},"pipeline":{"clients":1,"events":{"active":4117,"published":20980,"total":20980},"queue":{"acked":20980}}},"registrar":{"states":{"current":0}},"system":{"load":{"1":3.13,"15":3.5,"5":3.15,"norm":{"1":0.1304,"15":0.1458,"5":0.1313}}}}}}

```

**Comment by adriansr** [comment]
The bottleneck is ingestion of events into Elasticsearch. This creates back pressure and eventually packets need to be dropped because the queue fills.

See https://www.elastic.co/blog/how-to-tune-elastic-beats-performance-a-practical-example-with-batch-size-worker-count-and-more for more hints on tunning the Beats output to Elasticsearch.

You can confirm what's taking more CPU by adding the `--cpuprofile cpu.prof` option to Filebeat and then inspecting that file in your browser with `go tool pprof -http :9999 /usr/share/filebeat/bin/filebeat cpu.prof` (Select View->Flame graph).

**Comment by fredbcode** [comment]
Ok, after tuning all seems good to me, thank for your help and the team for the bug fixes
