### ISSUE TITLE
Adding systemd support across the beats ecosystem

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#14122]
This is a continuation of elastic/beats#11846 as the scope of this whole idea has expanded somewhat, and we now face the question of _where_ and to what extent we want systemd state information and metrics. After talking with @jsoriano , there seem to be three places where systemd support would make sense, none of which are mutually exclusive:

- As a processor for existing metricbeat system module data, presumably system/process or system/process_summary
- As its own metricbeat module
- As its own auditbeat module

This issue came up because systemd (as I'm sure you're aware) is quite large, and spans a wide number of system components that expose a wide array of information. This includes:

### Service metrics:
```
./dbusreader 
Enter a service: sshd.service
2019/10/17 13:14:41 *** Metrics for your service: ***
2019/10/17 13:14:41 Number of restarts: 0
2019/10/17 13:14:41 Current PID: 987
2019/10/17 13:14:41 CPUUsageNSec: 461638071
2019/10/17 13:14:41 Current Memory: 8982528
2019/10/17 13:14:41 Current Tasks: 1
2019/10/17 13:14:41 IPIngressBytes: 106190
2019/10/17 13:14:41 IPIngressPackets: 1061
2019/10/17 13:14:41 IPEgressBytes: 110074 
2019/10/17 13:14:41 IPEgressPackets: 662 
```
These are traditional metrics tied to a given systemd service. Its important to note that a systemd service can have multiple processes, making this a good way to monitor services compared to PID-level monitoring. We can also get start/stop timestamps, current service state, and uptime.

### Data on systemd-managed sockets

```
./dbusreader 
Enter a service: cockpit.socket
2019/10/17 15:25:59 *** Metrics for your socket: ***
2019/10/17 15:25:59 Current Memory: 1978368
2019/10/17 15:25:59 Current Tasks: 0
2019/10/17 15:25:59 IPIngressBytes: 3236
2019/10/17 15:25:59 IPIngressPackets: 38
2019/10/17 15:25:59 IPEgressBytes: 47147 
2019/10/17 15:25:59 IPEgressPackets: 23 
```
Systemd can manage sockets for its associated services. We can use this to audit sockets managed by systemd, get metrics, and alert on downed sockets, among other things.

### Data on timers, jobs, VMs and all the other things systemd does.
Systemd also has a cron-like `timers` and `jobs`, the data might prove useful for auditing and alerting, as well as a (https://www.freedesktop.org/wiki/Software/systemd/machined/)[machines] feature that can track VMs and containers.:
```
systemctl list-jobs
NEXT                         LEFT       LAST                         PASSED       UNIT                         ACTIVATES
Thu 2019-10-17 14:30:00 CDT  7min left  Thu 2019-10-17 14:20:00 CDT  2min 30s ago sysstat-collect.timer        sysstat-collect.service
Thu 2019-10-17 14:50:00 CDT  27min left Thu 2019-10-17 13:50:00 CDT  32min ago    dnf-makecache.timer          dnf-makecache.service
Fri 2019-10-18 00:00:00 CDT  9h left    Thu 2019-10-17 00:00:38 CDT  14h ago      mlocate-updatedb.timer       mlocate-updatedb.service
Fri 2019-10-18 00:00:00 CDT  9h left    Thu 2019-10-17 00:00:38 CDT  14h ago      unbound-anchor.timer         unbound-anchor.service
Fri 2019-10-18 00:07:00 CDT  9h left    n/a                          n/a          sysstat-summary.timer        sysstat-summary.service
Fri 2019-10-18 12:54:00 CDT  22h left   Thu 2019-10-17 12:54:00 CDT  1h 28min ago systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
```

Many other products support systemd. The issue is more where this'll go across the beats ecosystem. I'm hesitant to have a bunch of similar bits of data spread across different beats and modules, but it also makes sense that some of this be put in auditbeat vs metricbeat, vs an enhancement to existing metricset.

**Comment by exekias** [comment]
Thank you for putting this together! Really interesting. I see a clear fit for a `services` metricset, reporting metrics for all systemd services.

Do you know what's the meaning of `Current Memory` for sockets?

**Comment by fearful-symmetry** [comment]
> Do you know what's the meaning of Current Memory for sockets? 

Not entirely sure. If memory accounting is enabled, it'll grab just about anything from the cgroup and I imagine that casts a fairly wide net.

**Comment by jsoriano** [comment]
> I see a clear fit for a services metricset, reporting metrics for all systemd services.

We could have a services metricset with several providers, like `systemd`, `launchd`, `inetd`, Windows Services... not sure though if this would fit better in auditbeat or in metricbeat.

**Comment by fearful-symmetry** [comment]
@elastic/siem Does anyone on the SIEM team have options about adding some of this data to Auditbeat?

**Comment by fearful-symmetry** [comment]
Closing this for now, as #14206 is merged.
