### ISSUE TITLE
[Metricbeat] Add support for Amazon AuroraDB in rds metricset

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#14142]
This issue is to track the work of adding support for AuroraDB in rds metricset:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Monitoring.html

For current rds metricset, we are only collecting metrics that are available among different DBs from cloudwatch. There are some metrics that are specifically for AuroraDB but under the same namespace AWS/RDS.

This is a enhancement request from https://discuss.elastic.co/t/metricbeat-aws-rds-module-for-aurora-serverless/203077

**Comment by justinwalz** [comment]
Thanks @kaiyan-sheng!

**Comment by justinwalz** [comment]
Hi. Another feature request (from https://discuss.elastic.co/t/aws-rds-metricset-whitelist-by-database-name-and-or-tags/207796/2) is adding the ability to whitelist based on db name, id, or tags. This would have a large impact for us as it reduces the total cost of collecting these metrics. Best, Justin
