### ISSUE TITLE
Error in Documentation for system.diskio.iostat.request.avg_size

### ISSUE THREAD

**Issue by dnwobu** [elastic/beats#14204]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 7.3
- Operating System: CentOS 7.6
- Discuss Forum URL: https://discuss.elastic.co/t/documentation-error-for-metricbeat-system-diskio-iostat-request-avg-size/204945
- Steps to Reproduce: Incorrect documentation

The value calculated in https://github.com/elastic/beats/blob/master/metricbeat/module/system/diskio/diskstat_linux_test.go line 88 does not align with the documentation: 

https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-system.html
system.diskio.iostat.request.avg_size
The average size (in sectors) of the requests that were issued to the device.
type: float

Diskio metricset calculates bytes and does not simply pull the sectors value from iostat. The documentation needs to be updated.

**Comment by odacremolbap** [comment]
Thanks @dnwobu ,

to whoever is the owner of this metricset, probably using [the naming convention](https://www.elastic.co/guide/en/beats/devguide/current/event-conventions.html) is something to consider here.

**Comment by dnwobu** [comment]
The issue is still present in 7.5:

https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-system.html

![image](https://user-images.githubusercontent.com/40581464/69999954-7cc9f080-151f-11ea-9ef7-9d8d1a1e170e.png)

**Comment by fearful-symmetry** [comment]
Hey, @dnwobu, sorry for the delay, not sure how this got dropped. It'll be in 7.5.1.
