### ISSUE TITLE
Heartbeat service doesn't start when system rebooted

### ISSUE THREAD

**Issue by SlavikCA** [elastic/beats#14217]
`heartbeat version 7.4.1 (amd64), libbeat 7.4.1 [12ee6cd05c1bfdc69721ddab1f473417b1514576 built 2019-10-22 15:57:57 +0000 UTC]`

OS: Ubuntu 16.04.6 LTS

I installed heartbeat per docs:
https://www.elastic.co/guide/en/beats/heartbeat/current/setup-repositories.html
Specifically, I ran this:
```
sudo update-rc.d heartbeat-elastic defaults 95 10
```
Installed 7.2, then upgraded to 7.4, then rebooted

*Steps:*
Reboot Ubuntu and the check the service status:
```
~$ sudo reboot
...
~$ sudo service heartbeat-elastic status
● heartbeat-elastic.service - Ping remote services for availability and log results to Elasticsearch or send to Logstash.
   Loaded: loaded (/lib/systemd/system/heartbeat-elastic.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
```

service can be started manually:
```
slavik@piwik:~$ sudo service heartbeat-elastic start
slavik@piwik:~$ sudo service heartbeat-elastic status
● heartbeat-elastic.service - Ping remote services for availability and log results to Elasticsearch or send to Logstash.
   Loaded: loaded (/lib/systemd/system/heartbeat-elastic.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-10-23 19:20:13 PDT; 3s ago
```

Looking at the syslog: the heartbeat wasn't even attempted to start.

Is there a way to check that service is included in the list of services to start on the boot?

**Comment by SlavikCA** [comment]
I also have another system:
centos-release-7-7.1908.0.el7.centos.x86_64

same heartbeat version:
`heartbeat version 7.4.1 (amd64), libbeat 7.4.1 [12ee6cd05c1bfdc69721ddab1f473417b1514576 built 2019-10-22 15:57:57 +0000 UTC]`

This command was ran as part of installation:
```
sudo chkconfig --add heartbeat-elastic
```
However, the service is not starting after reboot. Have to start it manually:
```
[slavik@Cent7-az ~]$ sudo service heartbeat-elastic status
● heartbeat-elastic.service - Ping remote services for availability and log results to Elasticsearch or send to Logstash.
   Loaded: loaded (/usr/lib/systemd/system/heartbeat-elastic.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

[slavik@Cent7-az ~]$ sudo service heartbeat-elastic start
Starting heartbeat-elastic (via systemctl):                [  OK  ]
[slavik@Cent7-az ~]$ sudo service heartbeat-elastic status
● heartbeat-elastic.service - Ping remote services for availability and log results to Elasticsearch or send to Logstash.
   Loaded: loaded (/usr/lib/systemd/system/heartbeat-elastic.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2019-10-24 02:23:15 UTC; 4s ago
```

**Comment by andrewkroh** [comment]
On systems that manage the service with systemd you would need to enable the service.

`sudo systemctl enable heartbeat-elastic`

**Comment by SlavikCA** [comment]
@andrewkroh 
That's it. That fixes it.

Please add that step to docs

**Comment by SlavikCA** [comment]
fixed by https://github.com/elastic/beats/pull/14218
