### ISSUE TITLE
[SIEM] Netflow Data always displays 0 bytes in / out

### ISSUE THREAD

**Issue by StefanSa** [elastic/beats#14212]
**Kibana version:**
7.4
**Elasticsearch version:**
7.4
**Filebeat version:**
7.4
SIEM App always shows 0 bytes for Netflow data. Filebeat, however, transmits correct data.
This problem exists in general and not only in this example.

**Screenshots (if relevant):**

SIEM App:
![SIEM_0Bytes](https://user-images.githubusercontent.com/6105075/66701109-bdb04080-ecf8-11e9-85a6-8cc4fa3cfa9f.PNG)

Filebeat Netflow Dashboard:
![Dashboard_Netflow](https://user-images.githubusercontent.com/6105075/66701118-d6205b00-ecf8-11e9-879b-1b52d23f9317.PNG)

**Comment by StefanSa** [comment]
@adriansr 
Problem still exists in v7.5.
Is there a chance that the problem will be solved this year?

**Comment by StefanSa** [comment]
@adriansr 
any ETA here when the bug is fixed?

**Comment by andrewkroh** [comment]
Unidirectional flows are populating `source.bytes` and `source.packets` in Filebeat v7.5.0. The SIEM Network page will have one non-zero column for these unidirectional flow.

<img width="1518" alt="kibana-siem-v7 5 0-network" src="https://user-images.githubusercontent.com/4565752/70483710-668bd980-1ab7-11ea-8dd3-7261982ef681.png">

**Comment by adriansr** [comment]
@StefanSa as I said in a comment above, the problem here is that your Netflow templates are not exporting the necessary fields (`octetDeltaCount` and `packetDeltaCount`), you need to change the configuration on your netflow exporter so those fields are sent to Filebeat.

This is not a bug on our side.

**Comment by StefanSa** [comment]
@adriansr 
Thank you for your answer.
Question, we are talking about IPFIX (```octetDeltaCount``` and ```packetDeltaCount```) or Netflow ?

**Comment by adriansr** [comment]
Turns out this IS a bug on our side, I failed to notice that those fields have a different meaning in NetFlow V9 vs IPFIX.

**Comment by maggieghamry** [comment]
He's going to work on getting me something by tomorrow, which I'll pass on as soon as I receive it.
