### ISSUE TITLE
Missing resources field in azure module configuration examples

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#14224]
In azure module config example https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-azure.html#_example_configuration_5, `resources` field is not a part. But when I tried to run azure module monitor metricset without `resources`, metricbeat reported error: 
```2019-10-24T11:59:53.049-0600	ERROR	instance/beat.go:894	Exiting: 1 error: no resource options defined: module azure - monitor metricset```

**Comment by kaiyan-sheng** [comment]
@narph What do you think? I'm not sure if `resources` field is not there on purpose.

**Comment by narph** [comment]
@kaiyan-sheng , a resource option must be implemented, a configuration example can be found in the azure.yml/.disabled file. Will try to update the .ascii files as well.
