### ISSUE TITLE
[AllBeats]Travis: add kubernetes v1.16 version to CI tests

### ISSUE THREAD

**Issue by odacremolbap** [elastic/beats#14234]
Tests environment for kubernetes features at beats use the following versions:

- `1.9.4`
- `1.10.0`
- `1.15.3`

Current version as of this writing is `1.16.0`, which deprecates some settings that are being manually tested. In order to support his release the proposal is to add it.

No versions would be removed, `1.9.x` is still supported by some cloud providers

**Comment by jsoriano** [comment]
1.16 is in the list of tested versions now: https://github.com/elastic/beats/blob/d8d35a16b0beae02cb8048df2a66c3a743d0633f/deploy/kubernetes/Jenkinsfile.yml#L15
