### ISSUE TITLE
[Metricbeat]Diskio metricset - some windows metric values  expressed in increments of 100 nanoseconds

### ISSUE THREAD

**Issue by narph** [elastic/beats#14233]
For the system/diskio metricset some of the metric values for windows are expressed in increments of 100 nanoseconds instead of `miliseconds` as stated in the docs (https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntdddisk/ns-ntdddisk-_disk_performance).
Options here are to:
- update the docs and inform users about the differences between the os's
- convert values to milliseconds
I tend to go for the second one, what do you think @andrewkroh ?

**Comment by andrewkroh** [comment]
Normalizing to a consistent unit in Beats would be good for usability. So +1 for going to milliseconds since Linux is already reporting in that unit (I'm assuming the latter part about Linux).
