### ISSUE TITLE
Document script.max_compilations_per_minute needs for Cisco ASA/FTD

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#14236]
Need to investigate an appropriate value for `script.max_compilations_per_minute` when the Cisco module is enabled, which uses a lot of scripts in ingest pipelines.

Once a safe value is found it can be included in the docs.

**Comment by andrewkroh** [comment]
It might actually be that the script cache is thrashing. It's set to 100 by default (`script.cache.max_size`). We asked a user to try a larger value in https://github.com/elastic/beats/issues/16293#issuecomment-586055008.

**Comment by andrewkroh** [comment]
Related: https://github.com/elastic/elasticsearch/issues/49763

**Comment by adriansr** [comment]
This was closed by https://github.com/elastic/beats/pull/14789
