### ISSUE TITLE
Support 'enterprise' license type

### ISSUE THREAD

**Issue by ph** [elastic/beats#14246]
Elasticsearch teams want to add a new license type called "enterprise", we need to add this new type to the list of supported types.

https://github.com/elastic/beats/blob/b0890942df4bcb5005265b672c9fee7bf672d44c/x-pack/libbeat/licenser/types.go#L11-L18

The _Enterprise_ type will be a superset of the _Platinum_ License.

**NOTE: This is a breaking change for older best and the following comment need to be resolved https://github.com/elastic/elasticsearch/issues/48510#issuecomment-546419261**

Elasticsearch issues https://github.com/elastic/elasticsearch/issues/48510

**Comment by bytebilly** [comment]
Thanks for creating this @ph!

Do you already know if this change could happen in 7.6? This would help in a better understanding of the migration process, even if it's not strictly required.

As far as I can guess, the required change in Beats will not create any breaking change (even if we'll have the breaking change in Elasticsearch), so there are no concerns to add it. Is this correct?
