### ISSUE TITLE
[Winlogbeat] Lowercase and uppercase Channel values

### ISSUE THREAD

**Issue by Cyb3rWard0g** [elastic/beats#14261]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 7.4.0
- Operating System: Win10 1903
- Discuss Forum URL:
- Steps to Reproduce: Install winlogbeat 7.4.0 on Win10, send events to Kafka broker, use `kafkacat -b kafka-ip:9092 -t winlogbeat -C -o end`

I send events from Winlogbeat -> Kafka broker

Winlogbeat Config: https://github.com/hunters-forge/Blacksmith/blob/master/aws/mordor/cfn-files/configs/shire/shire_winlogbeat.yml

I use kafkacat to monitor events hitting my kafka broker. When I did that I see Windows Security events showing up, but the `Channel` field value shows `Security` in some events and `security` in other events. 

Lowercase Event (`winlog:{channel:security,process:{pid:4,thread:{id:3332}}`)
```
{@timestamp:2019-10-27T14:43:53.499Z,@metadata:{beat:winlogbeat,type:_doc,version:7.4.0,topic:winlogbeat},log:{level:information},message:A process has exited.nnSubject:ntSecurity ID:ttS-1-5-18ntAccount Name:ttACCT001$ntAccount Domain:ttshirentLogon ID:tt0x3E7nnProcess Information:ntProcess ID:t0x1ab8ntProcess Name:tC:\Windows\System32\rundll32.exentExit Status:t0x0,ecs:{version:1.1.0},host:{name:WECServer},agent:{type:winlogbeat,ephemeral_id:df5ad137-6594-4bd7-a3eb-e0eda670370c,hostname:WECServer,id:f8e32ecf-6ac8-4748-86ec-f026490623c4,version:7.4.0},winlog:{channel:security,process:{pid:4,thread:{id:3332}},event_data:{SubjectLogonId:0x3e7,Status:0x0,ProcessId:0x1ab8,ProcessName:C:\Windows\System32\rundll32.exe,SubjectUserSid:S-1-5-18,SubjectUserName:ACCT001,SubjectDomainName:shire},computer_name:ACCT001.shire.com,record_id:25674,keywords:[Audit Success],provider_guid:{54849625-5478-4994-a5ba-3e3b0328c30d},event_id:4689,provider_name:Microsoft-Windows-Security-Auditing,task:Process Termination,api:wineventlog,opcode:Info},event:{action:Process Termination,created:2019-10-27T14:43:56.106Z,kind:event,code:4689}}
```

Uppercase Event (`channel:Security`)
```
{@timestamp:2019-10-27T14:43:55.573Z,@metadata:{beat:winlogbeat,type:_doc,version:7.4.0,topic:winlogbeat},agent:{type:winlogbeat,ephemeral_id:df5ad137-6594-4bd7-a3eb-e0eda670370c,hostname:WECServer,id:f8e32ecf-6ac8-4748-86ec-f026490623c4,version:7.4.0},winlog:{record_id:77547,api:wineventlog,process:{thread:{id:32},pid:4},provider_guid:{54849625-5478-4994-a5ba-3e3b0328c30d},version:1,event_id:5156,computer_name:HFDC01.shire.com,provider_name:Microsoft-Windows-Security-Auditing,event_data:{RemoteMachineID:S-1-0-0,Application:System,LayerName:%%14611,SourceAddress:172.18.39.5,DestAddress:172.18.39.255,FilterRTID:66459,LayerRTID:48,ProcessID:4,Direction:%%14593,RemoteUserID:S-1-0-0,SourcePort:138,DestPort:138,Protocol:17},channel:Security,task:Filtering Platform Connection,keywords:[Audit Success],opcode:Info},event:{kind:event,code:5156,action:Filtering Platform Connection,created:2019-10-27T14:43:57.127Z},log:{level:information},message:The Windows Filtering Platform has permitted a connection.nnApplication Information:ntProcess ID:tt4ntApplication Name:tSystemnnNetwork Information:ntDirection:ttOutboundntSource Address:tt172.18.39.5ntSource Port:tt138ntDestination Address:t172.18.39.255ntDestination Port:tt138ntProtocol:tt17nnFilter Information:ntFilter Run-Time ID:t66459ntLayer Name:ttConnectntLayer Run-Time ID:t48,ecs:{version:1.1.0},host:{name:WECServer}}
```

I am not sure if it makes sense, but thats very inconsistent.

Impact:

Logstash Output Config misses events: https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/9951-winevent-security-output.conf#L7

I was able to catch those inconsistencies with an output config that catches everything else: https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/9990-winevent-catchall-output.conf

I only rename `Channel` to `log_name` in here: https://github.com/Cyb3rWard0g/HELK/blob/530b6ca847b29aca3f222ef05e41ec6917ac5363/docker/helk-logstash/pipeline/1010-winevent-winlogbeats-filter.conf#L103 , but I do not lowercase anything after that. I proved with the kafkacat output above that they arrive like that (lowercase or uppercase).

At the end I have the following:

Uppercase Security Logs:

![image](https://user-images.githubusercontent.com/9653181/67637053-2547bd80-f8ad-11e9-8759-085d1167388d.png)

Lowercase security logs:

![image](https://user-images.githubusercontent.com/9653181/67637064-385a8d80-f8ad-11e9-9d0b-a323345eb4d2.png)

Thank you in advance!

**Comment by andrewkroh** [comment]
Winlogbeat does not manipulate the value used in the `winlog.channel` field AFAIK. It should be coming straight out of the XML event it was given from Windows. Then writing into the document that it sends to the output.

https://github.com/elastic/beats/blob/12ee6cd05c1bfdc69721ddab1f473417b1514576/winlogbeat/sys/event.go#L47


https://github.com/elastic/beats/blob/12ee6cd05c1bfdc69721ddab1f473417b1514576/winlogbeat/eventlog/eventlog.go#L88-L89

What would be interesting to see is what value is given to Winlogbeat from Windows. You can enable `include_xml: true` for the event log and it will pass along the raw XML in the event. https://www.elastic.co/guide/en/beats/winlogbeat/7.3/configuration-winlogbeat-options.html#_event_logs_include_xml

**Comment by Cyb3rWard0g** [comment]
Thank you @andrewkroh I will do that in my next test. I am sorry I got caught up with a few things at work and I am also just recovering from a cold :( Thank you again. I will keep you posted with my test.
