### ISSUE TITLE
Better contributing guidelines

### ISSUE THREAD

**Issue by philippkahr** [elastic/beats#14260]
**Describe the enhancement:**
Hi,

I just wanted to point out that I had a really hard time, contributing to beats. Setting up go and python environment on my mac was not very clear. I did struggle all the way and it took me nearly 3 hours to set up everything. There were various errors with `mage` and `python2.7` and `GOPATH` and so on. it is still broken and does not work, especially the python2.7 part not finding all the modules (like `import yaml`) and go not being able to find the `libbeat` except I copy `github.com/elastic/beats` to the vendor folder inside the beat I am building.

Maybe we should add an ansible playbook that correctly installs GO, set's the python environment and do all the stuff needed? I know that that might break existing settings, but it might help get started? Alternatively, add a guide on how to use the Vagrantfile, and what has to be installed locally to use it. I added a bit more code to the Vagrantfile to make it more useable <https://github.com/elastic/beats/issues/14148>. 

**Testing**

Would it be possible to trigger the Travis build from outside a pull request? I like to open a pull request once, my entire code is tested and not notify a bunch of people commenting on my pull request that `I fixed the Capitalletter typo`.

**Dashboards**

There is a linter already in place checking for `name of dashboard [beat module] ...`. Maybe adding a new rule for `title: Capitalletter name of visualisation [beat module] ...`. Would help? In my pull request, I missed a few `Capitalletter` and Travis did not point them out. Also `mage exportDashboard` is not available for `winlogbeat` <https://github.com/elastic/beats/issues/14149#issuecomment-544147487>. 

**Ressources**
<https://github.com/elastic/beats/issues/4984>
<https://github.com/elastic/beats/pull/14135#issuecomment-546296160>
<https://github.com/elastic/beats/issues/14148>

**Comment by jsoriano** [comment]
Hey @philippkahr,

Thanks for your feedback!

Python 2.7 shouldn't be an issue after https://github.com/elastic/beats/pull/14798. If you can, please give a try to the current code. You may need to remove your existing virtual environments.

Installation of mage should be easy with `make mage`, but I think we don't mention it in any docs :confused: 

> Would it be possible to trigger the Travis build from outside a pull request?

In principle you can enable Travis in your fork in github, and then it should trigger Travis builds in your own account. Let me know if it works for you.

> Maybe adding a new rule for title: `Capitalletter name of visualisation [beat module] ....` Would help?

Visualizations must match this regexp: https://github.com/elastic/beats/blob/v7.5.1/dev-tools/mage/check.go#L291 Any contribution there is welcome :slightly_smiling_face: 

> Also mage exportDashboard is not available for winlogbeat #14149 (comment).

This should be easy to add by copying one of the targets from one of the magefiles that have it. You can also use `winlogbeat export dashboard --decode --id [id of the dashboard]` and save the output.

**Comment by philippkahr** [comment]
Hi @jsoriano 
thanks for the tip with the Travis build! I will try that.

> Visualizations must match this regexp: https://github.com/elastic/beats/blob/v7.5.1/dev-tools/mage/check.go#L291 Any contribution there is welcome 🙂

You are right, I will definitely check this out. Maybe we can add that as a rule for a linter?

> This should be easy to add by copying one of the targets from one of the magefiles that have it. You can also use winlogbeat export dashboard --decode --id [id of the dashboard] and save the output.

Expecting great things from me, I do not feel confident enough in Go yet, to achieve such a task. I did try it but it did not work after a few hours of copying code around I gave up ;).

**Comment by jsoriano** [comment]
> > This should be easy to add by copying one of the targets from one of the magefiles that have it. You can also use winlogbeat export dashboard --decode --id [id of the dashboard] and save the output.
> 
> Expecting great things from me, I do not feel confident enough in Go yet, to achieve such a task. I did try it but it did not work after a few hours of copying code around I gave up ;).

No worries :slightly_smiling_face:

Did you try to export the dashboards with `winlogbeat export dashboard --decode --id [id of the dashboard]`?
