### ISSUE TITLE
Move k8s metricsets to GA

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#14277]
For the metricsets below:

- Ensure the [requirements](https://github.com/elastic/beats/blob/master/.github/ISSUE_TEMPLATE/module-checklist.md) are met.
- Move them to GA

Metricsets:
- [ ] `controllermanager`
- [ ] `proxy`
- [ ] `scheduler`
- [ ] `state_cronjob`

**Comment by odacremolbap** [comment]
closed by https://github.com/elastic/beats/pull/14584
