### ISSUE TITLE
Move the oracle metricbeat module to GA

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#14279]
For a metricset to go GA, the following criterias should be met:

* [x] Supported versions are documented
* [x] Supported operating systems are documented (if applicable)
* [x] Integration tests exist
* [x] System tests exist
* [ ] Automated checks that all fields are documented. (Awaiting a wati to run Python tests only in Jenkins or Travis will always fail.
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] Dashboards exists (if applicable)
* [x] Kibana Home Tutorial (if applicable)
* Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).
data.json` exists and an automated way to generate it exists (`go test -data`)
* [x] Test environment in Docker exist for integration tests

**Comment by sayden** [comment]
We have the library available in the docker image of Metricbeat but we have just realized that the Oracle docker image also requires accepting an EULA before download, so we'll have to work on this now.

**Comment by andresrc** [comment]
can we close this one?

**Comment by sayden** [comment]
Only the automated check for documented fields is missing because of some issue in the CI yet
