### ISSUE TITLE
Synchronize the changelog between the beats branches

### ISSUE THREAD

**Issue by ph** [elastic/beats#14285]
If you look at the master or the 7.x branch changelog, we stopped updating them at 7.1.1. When we cut the branch or do mass backport we need to define a way or have something in place to keep them in sync too.

I was looking for when a fix was added in beats and the only I was able to know when the fix landed was to go in the 7.5 branch.

**Comment by ph** [comment]
@urso @mikemadden42 something to keep in mind with your automated tooling reflexion.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
