### ISSUE TITLE
Better IIS parsing for Exchange

### ISSUE THREAD

**Issue by philippkahr** [elastic/beats#14284]
**Describe the enhancement:**

Adding support for log lines such as `2019-10-20 15:13:55 POST /Microsoft-Server-ActiveSync/default.eas Cmd=Ping&User=philipp.kahr&DeviceId=9c731cc0e9fe8798783cb57e5977edd5e&DeviceType=Outlook&CorrelationID=<empty>;&ClientId=MJKNJEDEUJUUUID&cafeReqId=896c4201-8uue-489c-b193-f1e73aa6287a; - 212.166.112.250 Outlook-iOS-Android/1.0 - 200` In this comment I 
<https://github.com/elastic/beats/issues/13799#issuecomment-544268925> provided some GROK patterns that work (with simulate API). Only thing to figure out is whether to use a KV processor and rename it to ECS. I pointed out some log formats that IIS comes up with when used in conjunction with Exchange and someone is accessing `Outlook Web App`, `ActiveSync` and `Mapi`. @narph I hope it is ok that I ping you on this one.

**Comment by philippkahr** [comment]
I just wanted to do a little bump here if this is still interesting? I am using it on a daily basis. I append my grok filters to the ingest pipeline file in the IIS module directory.

**Comment by KnowMoreIT** [comment]
I am new to Elastic SIEM and trying to do this. Currently I use Graylog with Elastic on the backend but making the move to Kibana. I have this working with nxlog. I would like to see this enhancement as well
