### ISSUE TITLE
Azure compute_vm metricset reports duplicate metrics

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#14318]
In event that reported by `compute_vm` metricset, I see some fields are similar but with different values:
<img width="643" alt="Screen Shot 2019-10-29 at 5 34 36 PM" src="https://user-images.githubusercontent.com/14081635/67817277-6b9a4980-fa72-11e9-8fd4-f224b24834bf.png">

@narph Is this intended? If it is, what's the different between `.total` and `_total.total`?

**Comment by narph** [comment]
@kaiyan-sheng , those are different metrics Network in and Network in total / Network out and Network out total, see https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftcomputevirtualmachines.
The primary aggregation type for all these 4 metrics is `total`

**Comment by kaiyan-sheng** [comment]
Ahh saw it! Thanks for the clarification. I will close this ticket then!
