### ISSUE TITLE
[Filebeat] Improve documentation for Filebeat PostgreSQL module

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#14337]
Current documentation for PostgreSQL module does not mention anything about what Postgres logging settings are required in order to use this Filebeat module: https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-module-postgresql.html

Also the tested compatible version mentioned in the doc(version 9.5 and 9.6) is too old. This needs to be revalidated and updated as well.

**Comment by jsoriano** [comment]
It seems important to document the expectations related to `log_statement` and `log_min_duration_statement` options: https://github.com/elastic/beats/issues/20321#issuecomment-796704902
