### ISSUE TITLE
Add filtering to each prospector in Filebeat 

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#1433]
- [ ] Add possibility to configure a list of filtering rules for each prospector.

The following configuration, ignores all the debug log messages:

<pre>
prospectors:
   - input_type: log
     paths: ["/var/log/*.log]
     filter:
       - drop_event:
           regexp:
             message: "^DBG" 
</pre>

- [ ] In addition, we can also replace `include_lines` and `exclude_lines` with filtering rules. 

For example, if you want to drop the debug messages printed by `decoder.go` you would configure both options: 

<pre>
include_lines: ["decoder.go:.*"]
exclude_lines: ["^DBG"]
</pre>

This can be translated to the following (using a filtering rule):

<pre>
filter:
  - include_event:
      regexp:
        message: "decoder.go:.*"
  - drop_event:
      regexp:
        message: "^DBG"
</pre> 

The filtering rule should be placed under the `prospector` configuration section.

Note:  Similar could be done for the `exclude_files` option. Its functionality can be achieved by adding a filtering rule to the prospector, but it is slower as Filebeat needs to read each log line from the excluded files before deciding to drop the event.

For example, if you want to exclude all the access files created by the Apache server:

<pre>
drop_event:
   "source": "apache2/access.*"
</pre>

cc-ed: @tsg @ruflin

**Comment by ruflin** [comment]
Should we keep include_lines and exclude_lines as an alias for the more complex filter configuration. From a usability perspective I think it would make sense. As these are the most common filter use cases I think it would be nice to keep the configuration compact but still offer the full "filter" power.

**Comment by monicasarbu** [comment]
@ruflin I updated the ticket with an example of how filtering rules would be added into the configuration file. 
I agree with you that `include_lines` and `exclude_lines` might be easier to use as you only have to add a line instead of 3 lines, but if you are defining both options then I think it is easier to understand the filtering rules.
