### ISSUE TITLE
Nginx error module can't handle multiline entries

### ISSUE THREAD

**Issue by SlavikCA** [elastic/beats#14349]
Elastic version: 7.4.0
Filebeat versions: 7.4.1
OS: Ubuntu 18.04

I have only one output defined in the "filebeat.yml":
```
#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["elk.slavikf.com:9200"]
```

I have enabled nginx module with default configuration

PHP errors shows in the nginx error logs and they are multiline:
```
2019/10/30 23:26:34 [error] 205860#205860: *180289 FastCGI sent in stderr: "PHP message: PHP Warning:  Declaration of FEE_Field_Terms::wrap($content, $taxonomy, $before, $sep, $after) should be compatible with FEE_Field_Post::wrap($content, $post_id = 0) in /var/www/pittsburgh-church.com/web/wp-content/plugins/front-end-editor/php/fields/post.php on line 0
PHP message: PHP Warning:  Declaration of FEE_Field_Tags::wrap($content, $before, $sep, $after) should be compatible with FEE_Field_Terms::wrap($content, $taxonomy, $before, $sep, $after) in /var/www/pittsburgh-church.com/web/wp-content/plugins/front-end-editor/php/fields/post.php on line 0
PHP message: PHP Warning:  Declaration of FEE_Field_Category::wrap($content, $sep, $parents) should be compatible with FEE_Field_Terms::wrap($content, $taxonomy, $before, $sep, $after) in /var/www/pittsburgh-church.com/web/wp-content/plugins/front-end-editor/php/fields/post.php on line 0
```

**Defect:**
instead of sending multiline event, filebeat sends every line as separate message, resulting in this error:
`Provided Grok expressions do not match field value: [PHP message: PHP Warning: Declaration of FEE_Field_Comment::wrap($content) should be compatible with FEE_Field_Base::wrap($content, $data) in /var/www/pittsburgh-church.com/web/wp-content/plugins/front-end-editor/php/fields/other.php on line 0]`

I expect multiline to works, because your docs say so:
https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-module-nginx.html
> Makes sure each multiline log event gets sent as a single event

**Comment by SlavikCA** [comment]
Workaround is to specify multiline explicitly in the nginx module config (nginx.yml):
```
- module: nginx

  # Error logs
  error:
    enabled: true

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths: ["/var/log/nginx/*/*error.log"]

    input:
      # The regexp Pattern that has to be matched.
      # multiline.pattern: "^PHP message"
      multiline.pattern: ^[0-9]{4}

      # Defines if the pattern set under pattern should be negated or not. Default is false.
      multiline.negate: true

      # Match can be set to "after" or "before". It is used to define if lines should be append to a pattern
      # that was (not) matched before or after or as long as a pattern is not matched based on negate.
      multiline.match: after
```

However, I think this is still valid bug: default config should be enabled to process multiline entries

**Comment by kaiyan-sheng** [comment]
I'm glad it works for you. We are not very consistent on multiline settings in default config. Some modules have it by default. Thanks for making the suggestion!

**Comment by mtojek** [comment]
Resolving on behalf of this: https://github.com/elastic/beats/pull/14499

Thank you for the report, @SlavikCA !
