### ISSUE TITLE
Infinite ingestion retry when batches are too large and using GuaranteedSend

### ISSUE THREAD

**Issue by simitt** [elastic/beats#14350]
Elasticsearch returns status code `413` when a bulk request exceeds the size limit. A user can either increase the `http.max_content_length` in ES or decrease the `bulk_max_size` in the Beat to overcome such failures. 
However, when this error happens and the beat is using a `GuaranteedSend` publisher method the current implementation can lead to an infinite retry, sending the same request to ES.
This might result in not being able to ingest any more events.

It might be worth exploring to use a special handling for the batch when the request size exceeds a limit, e.g. split it in half.

**Comment by ph** [comment]
Related issue https://github.com/elastic/beats/issues/3688

**Comment by ph** [comment]
Prior experience with that from LS https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/497

**Comment by ph** [comment]
Linked to https://github.com/elastic/beats/issues/6749

**Comment by jlind23** [comment]
Ping @mukeshelastic @nimarezainia as you were both interested by this issue. It will be fixed to 8.1 thanks TL @rdner

**Comment by mukeshelastic** [comment]
Thanks @jlind23

**Comment by dikshachauhan-qasource** [comment]
Hi @simitt 

Could you please help us on this Ticket validation with below points:

- How can we create bulk requests for elasticsearch?
- Can it be covered under manual testing.

Thanks
QAS

**Comment by simitt** [comment]
@rdner given that you implemented the fix, can you please provide guidance for the testers.
It's been a long time since I created the issue, and don't believe this is reproducible anymore with the latest apm-server version, as it is not using libbeat output to ES anymore.

**Comment by rdner** [comment]
@dikshachauhan-qasource I described the testing process in my PR https://github.com/elastic/beats/pull/29368

Let me know if it's missing something.
