### ISSUE TITLE
[METRICBEAT]  Implementation of iostats for Windows

### ISSUE THREAD

**Issue by alokkumar95** [elastic/beats#14351]
**Describe the enhancement:**
Enhancement for Consideration

**METRICBEAT version : 7.4.1**
In the documentation, 

To get average Queue length of the requests that were issued to the device. 
we have  system.diskio.iostat.queue.avg_size. 

But this functionality is not available for Windows. 

In windows we are getting only implementation of **read,write,io**.

**So,Requesting for the implementation of IOSTAT in windows**

**Comment by seungyongshim** [comment]
+1

**Comment by kishorerv93** [comment]
Any Update on this ?

**Comment by xuyuqi77** [comment]
What's going on?

**Comment by fearful-symmetry** [comment]
@narph Do we know if or how similar metrics are present on windows? On linux, these metrics are coming from the kernel.

**Comment by michaelhyatt** [comment]
Seeing a potentially related issue. On Linux, I am seeing `system.diskio.io.ops` being populated while on Windows this field is not available. 

Can someone confirm if this is related to the `iostat` implementation on Windows?
