### ISSUE TITLE
Document metrics / metricsets that require specific permissions and / or running as root

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#14385]
The `system` module provides many metricsets. For some of the metrics in them, depending on how they are collected some special permissions may be needed, including the need to run metricbeat as a privileged user (e.g. `root`).

In many situations, users may need to minimize the use of privileged users so it's important to know what metrics would not be available in this case and what metrics can be made available with some additional configuration. 

The goal of this issue is to include in the [system module documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-system.html) information about the metrics / metricsets that require specific permissions or the use of privileged user. In some cases this would imply describing how the metrics are obtained as this can provide the information needed to correcly configure the needed permissions.

Once we have this information documented, in a follow-up, we can whether there are alternative ways to collect those metrics that require the use of a privileged user.

**Comment by jsoriano** [comment]
We did something like this in the `system/socket` metricset, but specially focused in the docker use case, we could check if a similar approach would be needed in other metricsets https://github.com/elastic/beats/pull/12039, and review the docs so they apply to more use cases.
