### ISSUE TITLE
Make cloud.id work for monitoring Elasticsearch reporter

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#14399]
Should inherit from global `cloud.id` setting. But `monitoring.cloud.id` setting should take precedence.

**Comment by ycombinator** [comment]
@cachedout I want to double check my understanding of the current plan around monitoring of Beats, as it will impact the prioritization of this issue here.

As things stand today, there are 3 ways to monitor a Beat (in no particular order):

1. Internal collection, shipping to production cluster (i.e. using `xpack.monitoring.*` settings). This method has been deprecated since 7.2.0 in favor of method 2 below and will be removed in 8.0.0.
2. Internal collection, shipping to monitoring cluster (i.e. using `monitoring.*` settings, which is what this issue here relates to, BTW). This method was introduced in 7.2.0.
3. External collection, using the `beat` Metricbeat module. This method was introduced in 7.3.0.

My understanding is that we want to keep method 2 around for the 7.x series and even into 8.x until Agent becomes GA. At that point, we can deprecate method 2 and ask users to install Agent instead, which will setup monitoring for the Beat(s) it is managing under the hood.

Can you confirm that my understand is correct and in line with yours as well?

**Comment by cachedout** [comment]
@ycombinator Thanks for the great question! I was just looking around today for the right place to codify that decision around keeping the second option around through 8.0 since to the best of my knowledge, the decision only exists in [this GH discussion](https://github.com/elastic/beats/issues/14886). I'll find a better home for it tomorrow.

Anyhow, yes, this syncs with my understanding. Thanks again for checking!

**Comment by ycombinator** [comment]
Thanks for confirming, @cachedout. This means this issue is still relevant and working on it needs to be prioritized.

**Comment by ycombinator** [comment]
@urso I would like to get your opinion on something.

Based on my testing here is the precedence order that is currently being followed amongst the various settings that determine which Elasticsearch cluster will be used by the monitoring code in libbeat:

- Is `monitoring.elasticsearch.hosts` set?
  - Yes: `monitoring.elasticsearch.hosts` will be used.
  - No:
    - Is `cloud.id` set?
      - Yes: `cloud.id` will be used.
      - No: `elasticsearch.hosts` will be used.

If we introduce a `monitoring.cloud.id` setting, we need to figure out what precedence ordering makes the most sense.

Here's what I propose:

- Is `monitoring.cloud.id` set?
  - Yes: `monitoring.cloud.id` will be used.
  - No:
    - Is `monitoring.elasticsearch.hosts` set?
      - Yes: `monitoring.elasticsearch.hosts` will be used.
      - No:
        - Is `cloud.id` set?
          - Yes: `cloud.id` will be used.
          - No: `elasticsearch.hosts` will be used.

An alternative proposal could be the following. I don't like it because it's not backwards compatible, i.e. it breaks the current ordering shown above.

- Is `monitoring.cloud.id` set?
  - Yes: `monitoring.cloud.id` will be used.
  - No:
    - Is `cloud.id` set?
      - Yes: `cloud.id` will be used.
	  - No: 
        - Is `monitoring.elasticsearch.hosts` set?
          - Yes: `monitoring.elasticsearch.hosts` will be used.
          - No: `elasticsearch.hosts` will be used.

Note that everything said above about `cloud.id` and `elasticsearch.hosts` applies to `cloud.auth` and `elasticsearch.username/elasticsearch.password` as well.

**Comment by urso** [comment]
I think your first proposal makes the most sense. If the endpoint is configured in the `monitoring` namespace, it should have precedence.
