### ISSUE TITLE
Version 1.2.2 available as rpm on download.elastic.co

### ISSUE THREAD

**Issue by wkoot** [elastic/beats#1440]
Latest available is https://download.elastic.co/beats/filebeat/filebeat-1.2.1-x86_64.rpm
I can't find filebeat-1.2.2-x86_64.rpm and the filebeat-1.2.2-SNAPSHOT-x86_64.rpm was removed.
Since there's already a tag v1.2.2 here on github I'm assuming it's been released?

**Comment by ruflin** [comment]
We are in the process of creating the release for testing, but the official release will not be before next week. As soon as we did the official release it will show up here (https://github.com/elastic/beats/releases) and on the download page. As soon as we have a "testing" link we can make it available to you for testing, but be aware that it still goes through QA

**Comment by wkoot** [comment]
Ok, is it possible to keep the snapshot rpm available on beats-nightlies.s3.amazonaws.com ?
Otherwise I'll have to install 1.2.1 and override the filebeat go-daemon by hand :-)

**Comment by tsg** [comment]
That was deleted during a cleanup routine. We'll build it again today.

**Comment by wkoot** [comment]
I'll just use the filebeat-god from the 1.2.1 snapshot, or are there also other changes in the version bump?

**Comment by tsg** [comment]
1.2.2 was released in the meantime. The blog post with the changes is here: https://www.elastic.co/blog/beats-1-2-2-released
