### ISSUE TITLE
Functionbeat manager - Allow deploy or update with single command

### ISSUE THREAD

**Issue by jderose9** [elastic/beats#14414]
**Describe the enhancement:**
Currently, the user has to know whether a cloudformation stack exists. If it does not, they need to use `deploy` to deploy functionbeat from the CLI. If it does, they need to use `update`. It would be nice to have functionbeat CLI manager detect whether the stack exists and issue the proper action automatically (create if not exists).

**Describe a specific use case for the enhancement or feature:**
I am deploying/updating functionbeat from many different CI/CD pipelines and don't want to concern myself with whether a stack exists or not.

**Comment by stevewritescode** [comment]
Yes, I have similarly started to write bash scripts that try a `deploy` followed by an `update` to catch both cases. Having a built-int idempotent command to create and/or update would be ideal.

**Comment by stevewritescode** [comment]
Also, to help with people searching for issues: This is the error I got when I tried to `deploy` a function that was already deployed. It took me a few minutes to realize this wasn't a "real" error but just indicated that I should use `update` instead.

```
Function: cloudwatch-rds, could not deploy, error: AlreadyExistsException: Stack [fnb-cloudwatch-rds-stack] already exists
	status code: 400, request id: 94fac630-b41e-45db-8b04-c424bbe80be0
Fail to deploy 1 function(s)
```

**Comment by onoranzefunebricloud** [comment]
Is there a way to update instead of deploy because after the first deployment, if you want to change something, it's impossible

**Comment by pawarrchetan** [comment]
@elastic-jb  Please tag appropriate contacts in this comment.

I think this should be done as an additional flag to the `functionbeat deploy` command.
For example :
functionbeat -v -e -d "*" -update deploy function-name

**Comment by mbarretta** [comment]
reopening since auto-closed. 

This is still an issue, I think. Received a question about it today with these logs:
[functionbeat_logs.txt](https://github.com/elastic/beats/files/6576597/functionbeat_logs.txt)
