### ISSUE TITLE
Document supported versions

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#1450]
#### Supported versions for the outputs:

- Redis: 
 - v
 - v
- Kafka: 
 - v
 - v

#### Supported versions for the Metricbeat modules:

- Apache: 
 - v
 - v
- Mysql: 
 - v
 - v
- Redis:
 - v
 - v

**Comment by ruflin** [comment]
For apache I would suggest:
* >= 2.2.31
* >= 2.4.16

Test with 2.4.20

@radoondas Does that make sense? Will it work with the 2.2.x versions?

Logic behind this is supporting the releases from the last 6 month and the last version of the 2.2. release as I think it is still quite popular.

**Comment by ruflin** [comment]
For mysql I would suggest:

* >= 5.5.46
* >= 5.6.27
* >= 5.7.10

Tested with 5.7.10

I never tested with 5.5 and 5.6. I will do some manual testing to see if behaves the same.

For MySQL the question that probably pops up is if it also works with MariaDB. I assume it does but I didn't test it so far. Should we mentioned MariaDB?

**Comment by radoondas** [comment]
@ruflin Apache 2.2 is still wildly used and it will take a long time for 2.4 to be the most used. The cycle between major releases is very long.
Implementation support both major versions and I would say, that in case of Apache I would also suggest to simplify it to:

-     = 2.2
-     = 2.4

But we can also take the latest versions of apache as is now at the apache.org and define it always to the latest ones as you suggested.

I noticed that there are new fields in 2.4 and most of the is already implemented. I do review metrics time to time to see if there are changes. Main fields don't change and stay as now.

**Comment by ruflin** [comment]
@radoondas Thanks for the details. There is a difference between "supported" and "should work". The version we mention above mean also that in case of a bug or crash, we fix it. For the others, it probably works, but we will not necessary fix all issues. That is why I try to keep the "official" supported list smaller the then list of actual versions it works with.

You mentioned that there are more fields in 2.4. As we have these fields implemented, could it be that it breaks the 2.2 implementation?

**Comment by ruflin** [comment]
For redis Metricbeat I suggest:

* >= 3.0.5

Tested with Redis 3.0.7.

This is probably the same for the output? @urso ?

**Comment by radoondas** [comment]
@ruflin No, it will not crash 2.2 implementation. Have tested it a lot. 
Fields are independent, don't cross each other. Implementation is done the way that it will not crash it the field is not implemented. Either in standard output, or extended, or if any new field will appear in new versions. We are fine with both 2.2 and 2.4 latest versions as support.

**Comment by ruflin** [comment]
@radoondas Nice, we should probably put this on top of the `data.go` file.

**Comment by tsg** [comment]
For the output versions, I suggest:

* Elasticsearch: same version as the Beats + the latest minor of the last major (currently 2.4).
* Logstash: same version as the Beats + the latest minor of the last major (currently 2.4).
* Kafka: 0.8, 0.9, 0.10
* Redis: Tested with 3.2.0. Likely it works with any version that has the [list](http://redis.io/commands#list) and/or [pub/sub](http://redis.io/commands#pubsub) commands.

@urso Does the above sound right?

**Comment by urso** [comment]
versions look good. For redis we might even support redis 1.0.0 . In redis 2.4 `rpush` capabilities have been changed supporting a 'batch' of values. While the output checks the versions I haven't tested with pre 2.4 redis yet.

**Comment by ruflin** [comment]
Lets only list redis 3.2, if it works with previous version that is great, but as long as we don't run the test on it, I would not list it.

**Comment by monicasarbu** [comment]
Closing it as the PR was merged.
