### ISSUE TITLE
Documentation improvements for "Generating Your Beat"

### ISSUE THREAD

**Issue by liu-xiao-guo** [elastic/beats#14509]
**Describe the enhancement:**
at the link https://www.elastic.co/guide/en/beats/devguide/7.5/newbeat-generate.html

1) The {user} is not so clear. According to the context, "user" refers to the account name of github. it could be confused as the username on the local machine

2) For some of the developers who have installed python3, virtualenv may not work properly, to fix that, we have to do:

export VIRTUALENV_PYTHON='/usr/local/bin/python'

where python refers to python 2.x

3) We need to install mage at https://github.com/magefile/mage in order to make it work.
 python $GOPATH/src/github.com/elastic/beats/script/generate.py
The above step is not needed

**Describe a specific use case for the enhancement or feature:**

**Comment by philippkahr** [comment]
If you are having trouble with python like I did you could always use Vagrant, like I described there: https://github.com/elastic/beats/issues/14148

There is an issue regarding moving python2 to python3 https://github.com/elastic/beats/issues/5950

**Comment by jsoriano** [comment]
Hey @liu-xiao-guo,

Python 2 is not required anymore (https://github.com/elastic/beats/pull/14798), it'd be great if you could try how is the current experience with Python 3.

> The {user} is not so clear. According to the context, "user" refers to the account name of github. it could be confused as the username on the local machine

Regarding this, current prompt mentions that the expected user name is the name of the github account. Do you have a proposal on how we could improve that?

Thanks for your feedback!

**Comment by jsoriano** [comment]
cc @fearful-symmetry
