### ISSUE TITLE
Mention the LSF to Beats input plugin migration path in the Filebeat migration doc

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#1452]
The Filebeat migration doc needs to be updated to indicate that we're now supporting the data shipping path from Logstash Forwarder (LSF) -> Beats input plugin until LSF EOL in September.  This is an enablement option for customers migrating from LSF to Filebeat.  

What's required?

- Beats input version 2.2.8 or later
- SSL must be explicitly enabled in the Beats input (ssl => true) since SSL is on by default with LSF.  The SSL/TLS configs should be the same for both LSF and Filebeat instances.

Why the change?  The current recommended migration option is to run LSF and Filebeat in parallel, with both lumberjack and beats inputs running side-by-side in LS.  This requires opening one or more additional ports which, depending on the organization, could result in approvals/red tape and potentially significant time delays.  This data flow gives users another option for phased migrations to Filebeat.

The LSF -> Beats input option is only supported for Filebeat migration purposes.

**Comment by ruflin** [comment]
I think we should get this in pretty soon as this option will be potentially removed in future versions.

**Comment by dedemorton** [comment]
+1

**Comment by tsg** [comment]
I guess this can be closed now.
