### ISSUE TITLE
Use ssl settings in the haproxy module

### ISSUE THREAD

**Issue by cafuego** [elastic/beats#14579]
**Describe the enhancement:**
Honour ssl settings in the haproxy module. The documentation suggests it is possible to override ssl verification and other settings for the haproxy module, but this is not the case; these override settings are ignored.

**Describe a specific use case for the enhancement or feature:**
In cases where haproxy is configured to only allow access to the stats backend via https using a self-signed certificate, the haproxy module throws errors. By allowing users to specify that ssl validation errors should be ignored, stats may be fetched and processed.

**Comment by cafuego** [comment]
Is this simply a matter of including {{settings: ["ssl"]}} in the metricbeat/module/haproxy/_meta/fields.yml file?

**Comment by exekias** [comment]
Thanks for opening this @cafuego, I'm afraid it's not that simple, as that would only update docs. This will require some changes in haproxy code to honor SSL settings

**Comment by cafuego** [comment]
Fair enough, I won't make a useless pull request then ;-)

**Comment by mtojek** [comment]
All PRs merged. Resolving.

**Comment by cafuego** [comment]
Thank you for doing this :-) Has it made it into a release yet?
