### ISSUE TITLE
Filebeat: high CPU load when reading from a large number of files

### ISSUE THREAD

**Issue by robin13** [elastic/beats#1457]
- Version: 1.0.1
- Operating System: RHEL kernel 2.6.32-573.18.1.el6.x86_64
- Steps to Reproduce: 

Set up filebeat to read from many files - 50k files seems to work, though the limit may be lower.  Filebeat will consume 100% CPU.

**Comment by ruflin** [comment]
This issue was solved through the implementation of the `harvester_limit` config option in the 5.0 release. In general several issues happened when filebeat reached the max open file handlers.

@robin13 Please reopen if you think there are more fixes needed.
