### ISSUE TITLE
Zeek ingest pipeline ignores millisecond in the timestamp

### ISSUE THREAD

**Issue by inqueue** [elastic/beats#14599]
- Version: Filebeat 7.4.2
- Operating System: n/a

Zeek logs may have milliseconds in the timestamp like this: `1573757353.774572`. When it happens, the statement `ctx['@timestamp'] = (long)ctx['zeek']['notice']['ts'] * 1000;` turns the value into `1573757353000`. 

Making the statement `ctx['@timestamp'] = (long)(ctx['zeek']['notice']['ts'] * 1000)` solves the issue.

@andrewkroh

**Comment by andrewkroh** [comment]
It looks like the latest version in master does the conversion in a slightly different manner.

https://github.com/elastic/beats/blob/ee5a4e73a98fbf63307cd5d7f6cfcf196bb15bd3/x-pack/filebeat/module/zeek/connection/ingest/pipeline.json#L11-L15

And it does preserve the milliseconds part of the timestamp:

https://github.com/elastic/beats/blob/ee5a4e73a98fbf63307cd5d7f6cfcf196bb15bd3/x-pack/filebeat/module/zeek/connection/test/connection-json.log-expected.json#L3

So we might just want to backport these latest changes to 7.5 and 7.x.
