### ISSUE TITLE
[Filebeat] Add persistent Netflow template cache 

### ISSUE THREAD

**Issue by fredbcode** [elastic/beats#14618]
Hi all,

I found no way to use an netflow cache, cache_save_path (logstash syntax), in netflow 
I don't know if this option is really missing or I just found no documentation about

With logstash I used a netflow.erb file https://github.com/elastic/logstash/blob/master/modules/netflow/configuration/logstash/netflow.conf.erb

With cache_ttl, cache_save_path and netflow_definitions added and all works well 

related with #14617 ?

Filebeat version: 7.4.2

**Comment by shipler** [comment]
@andrewkroh is there any expected update for the persistant template loading in the beats netflow module for the newer versions?

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
