### ISSUE TITLE
STAN (NATS streaming) module

### ISSUE THREAD

**Issue by exekias** [elastic/beats#14629]
@devon-kim implemented a new module for STAN (NATS streaming), thank you!. This issue is minded to try to include this module in the beats repo so everyone can benefit from it: 

https://github.com/elastic/beats/compare/7.2...devon-kim:ops-1844-stan-metricbeat

# Metricbeat Module / Dataset release checklist

This checklist is intended for Devs which create or update a module to make sure modules are consistent.

## Modules

For a metricset to go GA, the following criterias should be met:

* [x] Supported versions are documented
* [x] Supported operating systems are documented (if applicable)
* [x] Integration tests exist
* [x] System tests exist
* [x] Automated checks that all fields are documented
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] Dashboards exists (if applicable)
* [x] Kibana Home Tutorial (if applicable) https://github.com/elastic/kibana/pull/54102
  * [x] Open issue in [EUI repo](https://github.com/elastic/eui) to add [icon for module](https://elastic.github.io/eui/#/display/icons) if not already exists.
  * [x] Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).

## Filebeat module

* [ ] Test log files exist for the grok patterns
* [ ] Generated output for at least 1 log file exists

## Metricbeat module

* [x] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [x] Test environment in Docker exist for integration tests

**Comment by exekias** [comment]
cc @andresrc 

also @ChrsMark you may be interested, as you were involved in the NATS module

**Comment by ChrsMark** [comment]
Giving an update on this, Kibana tutorial is on its road elastic/kibana#54102 and we are waiting for a  the original dashboards.

**Comment by ChrsMark** [comment]
Note that the Kibana tutorial should be updated with the dashboard screenshot when the dashboard is in.

**Comment by devon-kim** [comment]
![screenshot](https://user-images.githubusercontent.com/56362295/72467445-e6891b80-37a8-11ea-9dfd-8f2082794046.png)

So I have this screenshot and have exported the JS to generate it from Kibana and left it up as a gist since I'm not quite sure where the dashboard should go https://gist.github.com/devon-kim/9f0514616b0869e31e721d11ca997db4

**Comment by ChrsMark** [comment]
Thanks @devon-kim! https://github.com/elastic/beats/pull/14026 can be used as an example of how the dashboard should be added. Could you give it a try?

**Comment by ChrsMark** [comment]
Kibana Tutorial link to dashobard PR: https://github.com/elastic/kibana/pull/55837

**Comment by ChrsMark** [comment]
Thanks for contributing the Dashboard @devon-kim!  Backports to `7.x` and `7.6` are on the way!

@andresrc should we add the Dashboard to the test-plan for an extra check and then maybe the module can go to GA?

**Comment by andresrc** [comment]
@ChrsMark what's missing here?

**Comment by ChrsMark** [comment]
@andresrc we have already test it so I think it can go to GA.
