### ISSUE TITLE
Update gopsutil after WithoutUids was addeed

### ISSUE THREAD

**Issue by exekias** [elastic/beats#14640]
**Describe the enhancement:**

This PR from @Brian-Williams (Thank you!) should improve performance when retrieving connections using gopsutil: https://github.com/shirou/gopsutil/pull/783. We can use it in the `socket_summary` metricset: https://github.com/elastic/beats/blob/d5bfe6bc5e5e4eadf87b04e43765564939acced4/metricbeat/module/system/socket_summary/socket_summary.go#L151

**Describe a specific use case for the enhancement or feature:**

This issue is minded to track the new release of gopsutil and fetch it so we can make use of this.

**Comment by exekias** [comment]
ey @Brian-Williams do you have numbers on the performance improvement here?

cc @fearful-symmetry

**Comment by exekias** [comment]
gopsutil `v2.19.11` has been released, we should be able to do this change already

**Comment by Brian-Williams** [comment]
Using benchmarking we see a 8-9% performance diff.

```
SMP: smp-platform-3.10.0-141.77f69bab.ga.noarch
H2: h2-1.12.3-154.x86_64
Sensor: endgame-sensor-3.51.10-3.51.10-51.noarch
Scores: smp-scores-0.5-11.x86_64
```

Dictionary:
H2: endpoint mocking tool
Scores: smp benchmarking tool

| investigation_name | es_document_count|es_documents_generated|index_size_in_bytes|index_bytes_per_second|
|--- |--- |--- |--- |--- |
| Application Survey | 706372130.0 -> 774877301.0; 9.7%(68505171.0) | 776932.0 -> 776932.0; 0.0%(0.0) | 1038286813.0 -> 164846532.0; -84.12%(-873440281.0) | 70058534.1 -> 10087055.44; -85.6%(-59971478.66)|
| Firewall Rules Survey | 707149062.0 -> 775654233.0; 9.69%(68505171.0) | 11894604.0 -> 11895094.0; 0.0%(490.0) | -23502641788.0 -> 4059115982.0; -117.27%(27561757770.0) | -222656717.5 -> 40226373.43; -118.07%(262883090.94)|
| Loaded Drivers Survey | 719043666.0 -> 787549327.0; 9.53%(68505661.0) | 6215456.0 -> 6215456.0; 0.0%(0.0) | 987832890.0 -> -1020498622.0; -203.31%(-2008331512.0) | 25722216.55 -> -25757707.95; -200.14%(-51479924.5)|
| Network Survey | 725259122.0 -> 793764783.0; 9.45%(68505661.0) | 1852684.0 -> 1852684.0; 0.0%(0.0) | -250869177.0 -> -473093645.0; 88.58%(-222224468.0) | -9785803.3 -> -18378804.07; 87.81%(-8593000.76)|
| Network Survey | 725259122.0 -> 793764783.0; 9.45%(68505661.0) | 2122544.0 -> 2122544.0; 0.0%(0.0) | -426210050.0 -> -110593546.0; -74.05%(315616504.0) | -4475247.59 -> -1161501.35; -74.05%(3313746.24)|
| Network Survey | 725259122.0 -> 793764783.0; 9.45%(68505661.0) | 2490016.0 -> 2490016.0; 0.0%(0.0) | 94093810.0 -> 114295651.0; 21.47%(20201841.0) | 582510.59 -> 708186.33; 21.57%(125675.74)|
| Persistence Survey | 727749138.0 -> 796254799.0; 9.41%(68505661.0) | 27175316.0 -> 26835656.0; -1.25%(-339660.0) | 17497109174.0 -> 21885904010.0; 25.08%(4388794836.0) | -17497109174.0 -> -21885904010.0; 25.08%(-4388794836.0)|
| Process Survey | 754924454.0 -> 823090455.0; 9.03%(68166001.0) | 12029868.0 -> 12369528.0; 2.82%(339660.0) | 28313656636.0 -> 38827908660.0; 37.13%(10514252024.0) | 49930144.91 -> 65077237.26; 30.34%(15147092.35)|
| Process Survey | 754924454.0 -> 823090455.0; 9.03%(68166001.0) | 13230745.0 -> 13570405.0; 2.57%(339660.0) | 32939794781.0 -> 43893683329.0; 33.25%(10953888548.0) | 50248552.16 -> 64366936.11; 28.1%(14118383.94)|
| Process Survey | 754924454.0 -> 823090455.0; 9.03%(68166001.0) | 13404638.0 -> 13744298.0; 2.53%(339660.0) | 33289248325.0 -> 28404282284.0; -14.67%(-4884966041.0) | 45065248.81 -> 37054187.9; -17.78%(-8011060.91)|
| Registry Survey | 768329092.0 -> 836834753.0; 8.92%(68505661.0) | 5946518.0 -> 5946518.0; 0.0%(0.0) | 1461423846.0 -> -6234014205.0; -526.57%(-7695438051.0) | 32393784.31 -> -169455730.79; -623.11%(-201849515.1)|
| Removable Media Survey | 774275610.0 -> 842781271.0; 8.85%(68505661.0) | 268938.0 -> 268938.0; 0.0%(0.0) | 4158128415.0 -> 4337364104.0; 4.31%(179235689.0) | 273921230.72 -> 291732283.48; 6.5%(17811052.76)|
| System Configuration Survey | 774544548.0 -> 843050209.0; 8.84%(68505661.0) | 59764.0 -> 59764.0; 0.0%(0.0) | 5275626162.0 -> 2173012961.0; -58.81%(-3102613201.0) | 228163580.78 -> 113961074.74; -50.05%(-114202506.04)|
| System Configuration Survey | 774544548.0 -> 843050209.0; 8.84%(68505661.0) | 73257.0 -> 73257.0; 0.0%(0.0) | 5290786225.0 -> 6504165411.0; 22.93%(1213379186.0) | 57326892.0 -> 73398325.0; 28.03%(16071433.0)|
| System Configuration Survey | 774544548.0 -> 843050209.0; 8.84%(68505661.0) | 76538.0 -> 76538.0; 0.0%(0.0) | -3747735006.0 -> 6344757716.0; -269.3%(10092492722.0) | -23749468.08 -> 41241817.54; -273.65%(64991285.62)|
| Users Survey | 774621086.0 -> 843126747.0; 8.84%(68505661.0) | 209174.0 -> 209174.0; 0.0%(0.0) | 1452950590.0 -> 4303301838.0; 196.18%(2850351248.0) | 91556523.57 -> 304132306.49; 232.18%(212575782.92)|
| Users Survey | 774621086.0 -> 843126747.0; 8.84%(68505661.0) | 249653.0 -> 249653.0; 0.0%(0.0) | 2608218850.0 -> 3237546756.0; 24.13%(629327906.0) | 29274386.4 -> 36973980.3; 26.3%(7699593.9)|
| Users Survey | 774621086.0 -> 843126747.0; 8.84%(68505661.0) | 256215.0 -> 256215.0; 0.0%(0.0) | -22572754359.0 -> -14381365838.0; -36.29%(8191388521.0) | -118456274.33 -> -75999858.24; -35.84%(42456416.1)|

**Comment by exekias** [comment]
closed by https://github.com/elastic/beats/pull/14957
