### ISSUE TITLE
[Metricbeat] Collectd module

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#14643]
Today Metricbeat already provides integrations with several third party monitoring agents (statsd, prometheus). Adding support for more agents will:

1. make it easier to connect and monitor existing (legacy) deployments. 
2. assist in migrations from other monitoring systems.  

One such agent is Collectd. 
[Collectd](https://collectd.org/) is a lightweight system and application statistics collection agent written in C that has been around since 2005. The agent is open source and has a large ecosystem of plugins that span over many different systems and use cases. It's also lightweight enough to even be used in embedded devices. 
Collectd is already supported in [Logstash](https://www.elastic.co/blog/logstash-collectd-input-plugin) and adding a respective module in Metricbeat would expand our integrations capabilities. Among many system plugins, Collectd has the [write Graphite plugin](https://collectd.org/wiki/index.php/Plugin:Write_Graphite) that stores collected metrics in Graphite. Which is good news since Metricbeat already has the `graphite` module. Therefore it should be possible to create a light `collectd` module that would serve as a write endpoint that can accept `collectd` metrics and store them with the respective naming `collectd.*`.

For a metricset to go GA, the following criterias should be met:

* [ ] Supported versions are documented
* [ ] Supported operating systems are documented (if applicable)
* [ ] Integration tests exist
* [ ] System tests exist
* [ ] Automated checks that all fields are documented
* [ ] Documentation
* [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] Dashboards exists (if applicable)
* [ ] Kibana Home Tutorial (if applicable)
  * Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).
* [ ] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [ ] Test environment in Docker exist for integration tests

**Comment by exekias** [comment]
ey Dimitri, we have an issue template for new modules, could you please use it? It adds a checklist of things we need to implement in order to consider it done. This is it: https://github.com/elastic/beats/issues/new?template=module-checklist.md

**Comment by sorantis** [comment]
@exekias sure, updated the issue. I usually use the enhancement request template, thought that the module template is for an implementation issue.

**Comment by OrbitalNet** [comment]
Thanks @sorantis for this thread. The documentation from collectd and ELK sites seem to imply this is already supported, but I guess this post confirms not yet? I've found several online tutorials implementing collectd, with several other back/front end solutions, and they all have worked; So far, collectd + ELK/Kibana has been elusive. Any guidance for collectd->logstash workarounds (or a tutorial if anyone has discovered a way it works), would be helpful, thanks.

**Comment by EricDales** [comment]
👍
