### ISSUE TITLE
Document how to write test for Filebeat and Metricbeat modules

### ISSUE THREAD

**Issue by exekias** [elastic/beats#14651]
Currently we have sparse public documentation on how to run tests for modules, for example here: https://www.elastic.co/guide/en/beats/devguide/current/creating-metricbeat-module.html#_run_environment_tests_for_one_module

The aim of this issue is to better document how to write both integration & system tests as part of the developer guide.

**Comment by kaiyan-sheng** [comment]
How to reproduce all CI failures locally will be something great to document.

**Comment by mtojek** [comment]
We can consider making it really straightforward - copy-paste-hello-world test cases or having a generator of stubs to just fill in.

**Comment by exekias** [comment]
cc @jsoriano as some of this ideas are also in https://github.com/elastic/beats/issues/14606

**Comment by jsoriano** [comment]
Yeah, I think that when we finish moving all the pieces to the modules directories we can consider adding stubs of the test files in the module generator.
