### ISSUE TITLE
Describe all Python virtual environments in docs

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#14650]
Hi,

while going through the onboarding process and basic project setup, I met few different Python virtual environments:

```
$ find . | egrep "activate$"
./metricbeat/build/python-env/bin/activate
./libbeat/build/python-env/bin/activate
./build/ve/darwin/bin/activate
```

As beats developer I wish to see unified or described purposes or details of every single one. It might be confusing for a community developer, which environment should be used for system testing, formatting docs or simply updating the project on Mac.

**Comment by kaiyan-sheng** [comment]
How to run these tests in oss and x-pack should both be documented and how to reproduce all CI failures locally will be something great to document as well.

**Comment by philippkahr** [comment]
I hope that this will get a lot better as soon as python3 is used? https://github.com/elastic/beats/issues/5950 Also I think it would be worth pointing out to an ansible script, or shell script, or something like that, that exactly sets up your macOS, some linux distros and windows machine.

I love using vagrant for such things, maybe it is worth pointing out how to use vagrant to create a rebuildable OS that can be tested :)

https://github.com/elastic/beats/issues/14148

**Comment by jsoriano** [comment]
Some extra documentation has been added during the migration to Python 3, that mentions the existing virtual environments (https://github.com/elastic/beats/pull/15833), @mtojek would this be enough?

We would be still missing the documentation Kaiyan mentions about running oss and x-pack tests, but I guess this is quite specific to the filebeat modules tests? Maybe we should create an specific issue for that.

**Comment by mtojek** [comment]
> Some extra documentation has been added during the migration to Python 3, that mentions the existing virtual environments (#15833), @mtojek would this be enough?

Looks good to me! Thanks!

**Comment by jsoriano** [comment]
Ok, thanks! I am closing this.

@kaiyan-sheng would you mind to open another issue to better document how to test filebeat modules? or maybe we should just make it easier with a common script or mage target.
