### ISSUE TITLE
packetbeat: nfs_*.pcap "bad dump file format"

### ISSUE THREAD

**Issue by jasperla** [elastic/beats#1467]
While looking into the `nfs_v3.pcap` and `nfs_v4.pcap` failures as reported in https://github.com/elastic/beats/pull/1456 by @andrewkroh, I noticed that not even tcpdump can handle the files on OpenBSD:

```
$ doas tcpdump -r nfs_v4.pcap
tcpdump: bad dump file format
$ file nfs_v4.pcap
nfs_v4.pcap: data
$
```

The other pcaps work fine and report the right output, e.g.:

```
$ file pgsql_insert.pcap
pgsql_insert.pcap: tcpdump capture file (little-endian) - version 2.4 (Ethernet, capture length 65535)
$
```

Comparing the pcap files, it does seem that at least the file header is different between the files. For example the nfs pcap files seem to have been generated with Wireshark in the dumpcap format. The manpage for that says:
`Dumpcap's default capture file format is pcap-ng format. When the -P option is specified, the output file is written in the pcap format.`

So the issue is that the pcap files themselves are not really pcap, but pcap-ng. If I [convert it](http://pcapng.com/) it works fine. Shall I open an PR to merge the converted files?

**Comment by andrewkroh** [comment]
> Shall I open an PR to merge the converted files?

Yes, please open a PR with the converted pcap files.

**Comment by kofemann** [comment]
My bad. In did I have used **editcap** to extract needed data and missed that file format is different. Thanks for fixing that.
