### ISSUE TITLE
[Metricbeat]Prometheus metrics/labels tracking

### ISSUE THREAD

**Issue by odacremolbap** [elastic/beats#14682]
**Current status**

Current [prometheus helper](https://github.com/elastic/beats/tree/master/metricbeat/helper/prometheus) is being used at metricbeat for fetching all prometheus exposed metrics.

Applications exposing metrics using prometheus need to design their metrics hierarchy, groupings, tags and key/values into the prometheus format.

The prometheus helper at metricbeat re-formats the prometheus resource fetched and turns it into an event. It is able to extract one key/value per prometheus family. Labels are classified globaly, some of them are used as keys that serve to group metrics into events that metricbeat pushes, while some others will not. In either case all labels are stored in a common map for all the prometheus resource, and then are added as key/values to a a location at the pushed event.

Caveat:

- We are not tracking context of labels/family. That's usually ok when labels are unique, or are common but they are used as unique keys to group families, or if they are not unique labels that can be mapped using the `LabelMetric`at the metricbeat helper. For other cases the prometheus helper seems to fall short.

```
kube_pod_container_resource_requests{namespace="kube-system",pod="coredns-5644d7b6d9-2gbs2",container="coredns",node="minikube",resource="cpu",unit="core"} 0.1
kube_pod_container_resource_requests{namespace="kube-system",pod="coredns-5644d7b6d9-2gbs2",container="coredns",node="minikube",resource="memory",unit="byte"} 7.340032e+07
```

- There is no constraint that will prevent someone to create multiple prometheus families that use the same label names but that do not refer to the same concept like:

```
my_metric_one_relates_to_dogs {label1="value1",label2="value2"} metric_value_one
my_metric_two_relates_to_airplanes {label1="1",label2="2"} metric_value_two
```

It would be desirable to place each of those same-name-labels at different locations at the event, or maybe discard or transform the one coming from one metric but not the other one for the other metric.
When these kind of metrics do not match the `LabelMetric`, I don't think it is possible to track which label comes from which metric.

**Proposal?**

No proposal yet.
I'd like to know if this is something to work on or not a concern at this moment.

**Related**

https://github.com/elastic/beats/issues/12938
https://github.com/elastic/beats/pull/14306

@exekias

**Comment by exekias** [comment]
ey @odacremolbap do you have a concrete example where you need this already? Would love to see the source metrics and the document you would like to output with them

**Comment by odacremolbap** [comment]
@exekias sure!

the first example at the issue is a real one
```
kube_pod_container_resource_requests{namespace="kube-system",pod="coredns-5644d7b6d9-2gbs2",container="coredns",node="minikube",resource="cpu",unit="core"} 0.1
kube_pod_container_resource_requests{namespace="kube-system",pod="coredns-5644d7b6d9-2gbs2",container="coredns",node="minikube",resource="memory",unit="byte"} 7.340032e+07
kube_pod_container_resource_requests{namespace="kube-system",pod="kube-apiserver-minikube",container="kube-apiserver",node="minikube",resource="cpu",unit="core"} 0.25
kube_pod_container_resource_requests{namespace="kube-system",pod="kube-addon-manager-minikube",container="kube-addon-manager",node="minikube",resource="cpu",unit="core"} 0.005
kube_pod_container_resource_requests{namespace="kube-system",pod="kube-addon-manager-minikube",container="kube-addon-manager",node="minikube",resource="memory",unit="byte"} 5.24288e+07
kube_pod_container_resource_requests{namespace="kube-system",pod="kube-controller-manager-minikube",container="kube-controller-manager",node="minikube",resource="cpu",unit="core"} 0.2
kube_pod_container_resource_requests{namespace="kube-system",pod="coredns-5644d7b6d9-hxpmf",container="coredns",node="minikube",resource="cpu",unit="core"} 0.1
kube_pod_container_resource_requests{namespace="kube-system",pod="coredns-5644d7b6d9-hxpmf",container="coredns",node="minikube",resource="memory",unit="byte"} 7.340032e+07
kube_pod_container_resource_requests{namespace="kube-system",pod="kube-scheduler-minikube",container="kube-scheduler",node="minikube",resource="cpu",unit="core"} 0.1
kube_pod_container_resource_requests{namespace="kube-system",pod="memory-demo",container="memory-demo-ctr",node="minikube",resource="memory",unit="byte"} 1.048576e+08
```
That kind of families would need some new _Metric_ at the prometheus helper I guess, that would act like an InfoMetric but retrieving the value, and ideally putting each value and a different location depending on the unit type.

These labels are reused at a different family that does not deal with pods but with nodes:
```
kube_node_status_capacity{node="minikube",resource="pods",unit="integer"} 110
kube_node_status_capacity{node="minikube",resource="cpu",unit="core"} 2
kube_node_status_capacity{node="minikube",resource="ephemeral_storage",unit="byte"} 1.736114176e+10
kube_node_status_capacity{node="minikube",resource="hugepages_2Mi",unit="byte"} 0
kube_node_status_capacity{node="minikube",resource="memory",unit="byte"} 1.940836352e+09
```

And also here, where `type` is also used, but with a different meaning to `type` labels at other places (pod, resourceqouta, secrets and services also have a type)
```
kube_limitrange_created{limitrange="quotaTest",namespace="testNS"} 1.5e+09
kube_limitrange{constraint="default",limitrange="quotaTest",namespace="testNS",resource="memory",type="Pod"} 2.1e+09
kube_limitrange{constraint="defaultRequest",limitrange="quotaTest",namespace="testNS",resource="memory",type="Pod"} 2.1e+09
kube_limitrange{constraint="max",limitrange="quotaTest",namespace="testNS",resource="memory",type="Pod"} 2.1e+09
kube_limitrange{constraint="maxLimitRequestRatio",limitrange="quotaTest",namespace="testNS",resource="memory",type="Pod"} 2.1e+09
kube_limitrange{constraint="min",limitrange="quotaTest",namespace="testNS",resource="memory",type="Pod"} 2.1e+09
```

Summary: 

- problem 1 is getting labels and data per family in one prometheus helper metric type, something that can be worked on.
- problem 2 is being able to put at the output event each label and family value at their desired path. Using `kubernetes.statemetrics.type` for everything that contains label `type` sounds sub-optimal.
- and finally, being able to chose an output event path based on labels. In the examples above that would be when reading a prometheus family that includes `resource="memory"`, put the value in `<path-for-metric>.memory: <value-for-metric>`

**Comment by odacremolbap** [comment]
after an out of band talk with @exekias we will
- avoid putting all kube-state-metrics information in one metricset. That will probably bring some more unknown conflicts to the table. We can learn from using separate metricsets and then decide if we want to heavily modify the prometheus helper and what we'll find.
- for some of the cases above a new prometheus helper metric type will be needed, so it should be created along the lines of other metric types already created.

Closing this issue for now.
