### ISSUE TITLE
Report cgroups stats if running in container

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#14691]
**Describe the enhancement:**

All Beats report CPU usage stats via the `GET stats` API endpoint (when the Beat is running with `http.enabled: true`). Currently, these do not account for the Beat running in a container. The [Elasticsearch Node Stats API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html) and the [Logstash Node Stats API](https://www.elastic.co/guide/en/logstash/current/node-stats-api.html#os-stats) both return additional `os.cgroup.*` metrics when running in a container. We should consider doing something similar for Beats as well.

**Describe a specific use case for the enhancement or feature:**

The Stack Monitoring UI can take advantage of these metrics and display CPU usage more accurately, depending on whether the Beat is running in a container or not. It already does this for Elasticsearch (see https://www.elastic.co/guide/en/kibana/current/monitoring-settings-kb.html#monitoring-ui-cgroup-settings).

**Comment by ycombinator** [comment]
cc: @simitt since she originally asked a question (off-issue) that led to this enhancement request.

**Comment by simitt** [comment]
This issue originated from a discussion about normalizing CPU percentages against container limits/throttling. Would the suggested enhancement allow for the stack monitoring to use quota information for showing CPU utilization being throttled, although CPU is really not at 100%?
