### ISSUE TITLE
Registered metricsets fail to load if listed as light modules

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#14698]
When we added support for light modules in Metricbeat (https://github.com/elastic/beats/issues/12270), we defined that available light metricsets in a module should be listed in a `module.yml` file.

In the case of mixed modules (modules with light and registered metricsets), only light modules are intended to be listed there. We have found that this is confusing, a developer would expect that metricsets listed there continue working no matter their kind, but current implementation fails to load a light module if one of the metricsets listed in `module.yml` doesn't have a `manifest.yml`.

Metricbeat shouldn't try to load metricsets as light metricsets if they are registered, even if they are listed in the `module,yml` file.

How to reproduce:
* Implement a mixed module
* List all metricsets in the `module.yml` file
* Configure metricbeat with a light metricset of this module
* Metricbeat fails to load the light metricset

Expected behaviour:
* Metricbeat is able to load the light metricset, ignoring metricsets listed in `module.yml` that are registered.
* Metricbeat still fails if it is going to load a light module and one of the listed metricsets doesn't have a `manifest.yml` AND is not registered.

**Comment by mtojek** [comment]
Done. Resolving.
