### ISSUE TITLE
Packetbeat DNS protocols uses arrays

### ISSUE THREAD

**Issue by tsg** [elastic/beats#1470]
Version: all

The DNS protocol in Packetbeat uses arrays for `dns.answers`, `dns.authorities`, etc. Arrays are not well supported by Kibana, so we should see if we can reorganize the data to make this more useful. Alternatively, we should consider to not index this data by default to save space.

**Comment by tsg** [comment]
Set as P2 because it will be a breaking change, so we might want to do it for 5.0.

**Comment by McStork** [comment]
If we wanted to extract the Ressource Records from the arrays, we could have `dns.answers.A`, `dns.answers.AAAA`, ... for a transaction. 
But the thing is that a dns transaction can have multiple times a given RR. For example there can be more than one NS record in `dns.authorities` or more than one DS record in `dns.answers`. And we can't map multiple `dns.answers.DS` fields, so this won't do.

At first glance I don't see a clean way to bypass these arrays.

**Comment by tsg** [comment]
I think going from a single `dns.answers` array to multiple `dns.asnwers.A`, `dns.answers.AAAA`, etc. fields, even if still arrays, would make it better, I think. You could still do a pie chart on `dns.answers.A`, for example.

**Comment by frennkie** [comment]
Has there been any progress on this?
I would really helpful if I could filter/query e.g. on the dns.answers.data and dns.answers.type fields.

**Comment by frennkie** [comment]
What do you guys think about this: #2504 ?
