### ISSUE TITLE
filebeat cluster management

### ISSUE THREAD

**Issue by vickluck** [elastic/beats#14701]
**Describe the enhancement:**
Usually, each machine has a filebeat installed. If there are hundreds of filebeats, as users, they want to manage the filebeat services on these hundreds.

**Describe a specific use case for the enhancement or feature:**
For example,
When a filebeat service is abnormal, it can be monitored.
For the abnormal filebeat, recover after solving the problem manually.
When filebeat.yml is updated, it can be loaded automatically. That is to support hot start.

**Comment by vickluck** [comment]
In other words, when there are hundreds of machines deploying filebeat, how to manage filebeat on these machines?

**Comment by philippkahr** [comment]
Beats central management / Fleet management would be the answer if you are a paying Elastic customer. Else I would recommend using the ansible role, or any other configuration management tool. There are also SaltStack formulas available.

**Comment by vickluck** [comment]
Thank you very much for your reply. Now I am learning to use ansible.

**Comment by philippkahr** [comment]
Please close this issue and for the next time such a question belongs more to discuss.elastic.co there you will also reach more people.
