### ISSUE TITLE
[Filebeat] ActiveMQ module

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#14744]
# Introduction

As the Metricbeat for ActiveMQ has been delivered in https://github.com/elastic/beats/issues/14510 , a corresponding filebeat should be also implemented.

Logging is enabled using Log4j appenders. Default logging configuration: 

```
# Console appender
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%5p | %m%n
log4j.appender.console.threshold=INFO

# File appender
log4j.appender.logfile=org.apache.log4j.RollingFileAppender
log4j.appender.logfile.file=${activemq.data}/activemq.log
log4j.appender.logfile.maxFileSize=1024KB
log4j.appender.logfile.maxBackupIndex=5
log4j.appender.logfile.append=true
log4j.appender.logfile.layout=org.apache.log4j.PatternLayout
log4j.appender.logfile.layout.ConversionPattern=%d | %-5p | %m | %c | %t%n
```

(source: https://github.com/apache/activemq/blob/7d14ddb0d15c9221f35318661c98f4993b94e3bd/activemq-all/src/main/resources/log4j.properties)

## Modules

For a fileset to go GA, the following criterias should be met:

* [x] Supported versions are documented
* [x] Supported operating systems are documented (if applicable)
* [x] Integration tests exist
~~*[ ] System tests exist~~
* [x] Automated checks that all fields are documented
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] Dashboards exists (if applicable)
* [x] Kibana Home Tutorial (if applicable)
  * Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).

# Filebeat module

* [x] Test log files exist for the grok patterns
* [x] Generated output for at least 1 log file exists

**Comment by mtojek** [comment]
_To be addressed in the PR:_

Apart from the general application logging, ActiveMQ provides also audit logs. Briefly described here: https://activemq.apache.org/audit-logging

**Comment by exekias** [comment]
I updated the description to put back the Modules section, it affects both to Metricbeat and Filebeat modules

**Comment by mtojek** [comment]
Status table has been updated. I'm proceeding with dashboards.

**Comment by mtojek** [comment]
All action items have been cleared. I will proceed with backports.

**Comment by mtojek** [comment]
All backports have been merged. Resolving.
