### ISSUE TITLE
Beats HTTP user agent does not follow RFC

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#14747]
Our beats user agent of `Elastic Beatname/Version` does not follow the HTTP spec. The spaces separates user agents, so we should use `Elastic-Beatname` instead.

Since we've already released this code into the wild I propose we consider this a breaking change for beats 8.0+.

It looks like the Azure node client had a similar issue https://github.com/Azure/azure-sdk-for-node/issues/694 .

Thanks to @OrangeDog for reporting this in https://github.com/elastic/beats/pull/14297#issuecomment-558139733

**Comment by OrangeDog** [comment]
Sorry I didn't check earlier. I wasn't aware that you'd released this yet.
7.x releases will have the erroneous UA then?

**Comment by andrewvc** [comment]
@OrangeDog actually, it looks like I forgot to backport the HTTP fix to 7.5, so we can fix it in heartbeat for 7.6. 

However, for the affected metricbeat modules we'll have to wait till 8.0 since the UA has had the space for a very long time. This patch just created a common helper function.
