### ISSUE TITLE
root owned files on docker host after building beats

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#1475]
When running `make testsuite`, the build uses docker containers that mount a host volume. Files written to the volume from within the container are owned by root. Because these files are owned by root, on the host system they cannot be removed by a normal user.

This causes problems for Jenkins when it is configured to clean the workspace prior to executing a job. Jenkins handles the problem by moving the original workspace that cannot be deleted and creates a new one for the build. Over time this fills the disk.

One solution is to run the processes inside of the docker container using the same UID as the user that started the container. This can be done by building the container and passing in the user's UID using `--build-arg UID=${UID}`. See https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables-build-arg

**Comment by cyrilleverrier** [comment]
@andrewkroh : is it related to https://github.com/karalabe/xgo/issues/37 ?
I had a look few months ago but I didn't really go far

**Comment by andrewkroh** [comment]
@cyrilleverrier Yeah, it sounds like the same underlying issue (just not related to the usage of xgo).

**Comment by andrewkroh** [comment]
I think this has been resolved by running a `chown` from inside the container to return the ownership to the user executing the build.
