### ISSUE TITLE
Add documentation to exclude Beats files/processes from antivirus scans

### ISSUE THREAD

**Issue by romain-chanu** [elastic/beats#14783]
**Describe the enhancement:** Antivirus software may interfere with Beats files/processes. As a good practice, Beats files/processes should be excluded from the antivirus scans. This recommendation is currently missing in the Beats documentation and should be added.

**Describe a specific use case for the enhancement or feature:** We recently experienced an issue with Filebeat where Filebeat was stalling. We found out that the antivirus was "locking" the registry files ( `registry`, `registry.old`, `registry.new`). After excluding the files from the antivirus scan, the problem was solved.

**Comment by urso** [comment]
Seems to be a common problem on Windows. On windows files can't just be deleted or renamed if some other process is accessing them.
