### ISSUE TITLE
Add support for Haproxy 2.0 in filebeat and metricbeat

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#14793]
Haproxy 2.0 has been already [released](https://www.haproxy.com/blog/haproxy-2-0-and-beyond/), we should check if filebeat and metricbeat support them and document or adapt what needed.

We will have to specially check changes in the metrics format. Haproxy 2.0 also includes [a prometheus exporter](https://www.haproxy.com/blog/haproxy-exposes-a-prometheus-metrics-endpoint/).

- [x] Metricbeat support
   - [x] add new metrics https://github.com/elastic/beats/pull/18523
   - [x] investigate support of RPC
   - [x] investigate support of HTTP/2
- [x] Filebeat support
  - [x] follow-up changes in logging in the pipeline
    There hasn't been any changes in the format of the logs.

**Comment by injectedfusion** [comment]
Agreed, HTTP2 & grpc support has been available as version1.9 and version2.0 is currently broken with Metricbeat :(

**Comment by ElasticStewart** [comment]
++

**Comment by kvch** [comment]
@injectedfusion I am working at the moment on this issue. Could you please share the error you are getting with HAProxy v2? I tried to find errors, but I was not successful. :(

**Comment by injectedfusion** [comment]
@kvch 
Message received, I'll draft up my test case with more details.

**Comment by kvch** [comment]
@injectedfusion I would like to close this ticket. When you are ready to share the test case, do you mind posting it into a separate issue and ping me in it?

**Comment by kvch** [comment]
I still have to update the docs.
