### ISSUE TITLE
Monitor Kubernetes PVs / PVCs with Metricbeat (including dashboards)

### ISSUE THREAD

**Issue by eedugon** [elastic/beats#14821]
**Describe the enhancement:**
When using Metricbeat to monitor Kubernetes there's no visibility on the PVs / PVCs (status / filesystem usage, etc).
Some of the data is already available at OS metrics level (filesystem metricset) from the kubernetes hosts, as they should have the PVs mounted, but there isn't any high level view around them, neither considering the filesystems as related with PVs and PVCs.

**Describe a specific use case for the enhancement or feature:**
Monitoring Kubernetes should give visibility of Persistent Volumes status, size and occupation.

**Comment by exekias** [comment]
I think this is only missing a dashboard
