### ISSUE TITLE
[Metricbeat] windows module - Monitor Active Directory

### ISSUE THREAD

**Issue by narph** [elastic/beats#14836]
**Describe the enhancement:** Monitoring Active Directory in Windows

Possible implementation: lightweight metricset (from perfmon) by reading the  NTDS performance object counters.

Origin discuss https://discuss.elastic.co/t/metricbeat-active-directory-ad-performance-metrics-perfmon-yaml-build/209687

Could be added as a new metricset inside the windows module

cc: @sorantis

**Comment by FreerideTheWorld** [comment]
I'll be testing this out early this week but if someone else has some better insight that would be appreciated.  We're trying to mirror a lot of Splunk functionality into Elasticsearch.
- instance_label: ntds.name
   instance_name: ntds.ds_directory.reads_sec
   measurement_label: ntds.ds_directory.reads_sec
   query: '\NTDS\DS Directory Reads/sec'

**Comment by leandroscardua** [comment]
Hi Elastic Team,

Any news on that PR?
