### ISSUE TITLE
[Metricbeat] AWS Module: DynamoDB metricset

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#14856]
Related metrics are in the `AWS/DynamoDB` namespace.

# Metricbeat Module / Dataset release checklist

This checklist is intended for Devs which create or update a module to make sure modules are consistent.

## Modules

For a metricset to go GA, the following criteria should be met:

* [ ] ~~Supported versions are documented~~
* [ ] ~~Supported operating systems are documented (if applicable)~~
* [ ] ~~Integration tests exist~~
* [ ] ~~System tests exist~~
* [ ] ~~Automated checks that all fields are documented~~
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] Dashboards exists (if applicable)
* [x] Kibana Home Tutorial (if applicable)
  * Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).

## Metricbeat module

* [x] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [ ] ~~Test environment in Docker exist for integration tests~~

**Comment by ChrsMark** [comment]
Hey @kaiyan-sheng @andresrc ! I could work on it if it's not claimed by someone else.

**Comment by kaiyan-sheng** [comment]
This can be developed with light module using cloudwatch metricset.

**Comment by ChrsMark** [comment]
Hey @kaiyan-sheng @andresrc giving a heads-up on this, is there anything else missing for this metricset? Otherwise we can consider it "done".
