### ISSUE TITLE
[Metricbeat] AWS Module: SNS metricset

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#14855]
Related metrics are in the `AWS/SNS` namespace.

# Metricbeat Module / Dataset release checklist

This checklist is intended for Devs which create or update a module to make sure modules are consistent.

## Modules

For a metricset to go GA, the following criterias should be met:

* [x] Supported versions are documented
* [x] Supported operating systems are documented (if applicable)
* [x] Integration tests exist
* [ ] ~~System tests exist~~
* [ ] ~~Automated checks that all fields are documented~~
* [x] Documentation
* [ ] ~~Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)~~
* [x] Dashboards exists (if applicable)
* [ ] ~~Kibana Home Tutorial (if applicable)~~
  * Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).

## Metricbeat module

* [x] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* ~~[ ] Test environment in Docker exist for integration tests~~

**Comment by mtojek** [comment]
Checklist has been updated. I will proceed with dashboard.

**Comment by mtojek** [comment]
All items have been merged.

Resolving.
