### ISSUE TITLE
Set clean_inactive by default in autodiscover inputs

### ISSUE THREAD

**Issue by exekias** [elastic/beats#14864]
Setting a fairly large [clean_inactive](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#filebeat-input-log-clean-inactive) (ie 4h) value for autodiscover inputs should help on making sure registry entries are removed after the input has been stopped.

We can update the default autodiscover input settings to include it. And also update documentation to recommend always using it, including the kubernetes deploy manifests.

**Comment by exekias** [comment]
@urso what happens if I have `clean_inactive: 4h` and a running container (hence its input is running) stays silent for that long?

**Comment by urso** [comment]
As long as the input is active it has a 'lock' on the file. Only files that are marked as 'finished' (no active harvester) will be removed. The registrar will log an error message in this case:

```
State for %s should have been dropped, but couldn't as state is not finished.
```
