### ISSUE TITLE
HTTP 0.9 support for Packetbeat

### ISSUE THREAD

**Issue by ErnestoBezanilla** [elastic/beats#14866]
**Describe the enhancement:**

Packetbeat does not capture HTTP/0.9 packets when using Telnet. For example:

```
telnet myserver 80
Trying 192.168.0.30...
Connected to myserver.
Escape character is '^]'.
GET http://myserver/blabla
```

ER: Capture HTTP over Telnet traffic 

Also document the versions of HTTP supported by Packetbeat.

**Comment by MikePaquette** [comment]
This is a reasonable enhancement request, and implementing it would improve the overall monitoring capability of Packetbeat for http.

I recommend assigning it to backlog with low priority.

At higher priority, we should update the [documentation](https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-http-options.html) with a note about what versions of http are currently supported.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
