### ISSUE TITLE
Create Migration Guide for 2.x to 5.x

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#1488]
We have several backward compatibility breaks in 5.0. We should create a migration guide to make migration easier.

Please post below all the entries that should go into this migration guide.

**Comment by ruflin** [comment]
# Config Migration Topbeat 

All config options of topbeat were moved under its own topbeat namespace. Topbeat will still work with the old configuration but this will be removed in the next major release. To adjust your configuration, you have to take the following steps:

* Find `input:` in your topbeat.yml file with all its sub config options. 
* Replace `input:` with `topbeat:`

This will look similar to:

```
topbeat:
  period: 10
  ...
```

**Comment by ruflin** [comment]
## Config Migration Packetbeat

All config options of packetbeat were moved under its own packetbeat namespace. To keep packetbeat running, you must make the following modifications to your config file.

### Option 1

* Find the following 4 config options in your config file: `interfaces`, `flows`, `procs`, `protocols`
* Indent all these config options including its sub configs with 2 spaces
* Add `packetbeat:` on top of the config options

This will look as following:

```
packetbeat:
  interfaces:
    ...
  flows:
    ...
  procs:
    ...
  protocols:
    ...
```

### Option 2

* Find the following 4 config options in your config file: `interfaces`, `flows`, `procs`, `protocols`
* Prepend all 4 options with `packetbeat.`

This will look as following:
```
packetbeat.interfaces:
  ...
packetbeat.flows:
  ...
packetbeat.procs:
    ...
packetbeat.protocols:
    ...
```

**Comment by andrewkroh** [comment]
Another topic is changing the URL used in your APT and Yum repo config. I don't think we've published 5.x to any package repos yet, but we will and the URL will be different.

**Comment by tsg** [comment]
Move config settings from under `beat` to top level: https://github.com/elastic/beats/pull/1570

**Comment by tsg** [comment]
This can be closed as we now have migration guides.
