### ISSUE TITLE
Kafka output dropping messages due to size, but doesn’t increment the “failed” counter

### ISSUE THREAD

**Issue by imriz** [elastic/beats#14906]
Not sure yet if this is a bug, or intentional behavior -
I've noticed in my logs that sometimes Filebeat's Kafka output will drop messages due to size error from the brokerm, but won't increment the "failed" counter (https://github.com/elastic/beats/blob/master/libbeat/outputs/kafka/client.go#L247).
It seems this was introduced here: https://github.com/elastic/beats/pull/2737 as a result of the discussion in https://discuss.elastic.co/t/filebeat-5-0beta1-with-kafka-output-multiplication-of-log-lines/62513/12

The end result is that apparently one can lose messages without any alert ever firing (since the failures stats are not being incremented). This seems like the wrong behavior, and I think this should be accounted under "failed" or "dropped", so one could be alerted.

I've also opened a discussion in the forums (https://discuss.elastic.co/t/kafka-output-dropping-messages-due-to-size-but-doesnt-increment-the-failed-counter/210081), but got no reply yet, and this does smell like a bug to me.

**Comment by imriz** [comment]
Thanks. Any objections I will open a PR to cherry pick it into 7.x?

**Comment by faec** [comment]
Probably just 7.5 but sure, and you can assign the review to me to make sure I see it :-)
