### ISSUE TITLE
metricbeat and azure load balancer

### ISSUE THREAD

**Issue by Hkyx** [elastic/beats#14919]
#### Problem:
I deployed filebeat and metricbeat on a new Azure IIS installation (custom image), and send all ths logs and metrics to logstash behind a loadbalancer. 
In this image filebeat is perfectly working, but metricbeat can't etablish a connection and seem to timeout: 
Failed to connect to backoff(async(tcp://mylogstash.com:5044)): dial tcp x.x.x.x:5044: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
where mylogstash is my load balancer url(tried with the LB ip too).

#### Version:
- Version:  metricbeat version 6.7.0 (amd64), libbeat 6.7.0 14ca49c28a6e10b84b4ea8cdebdc46bd2eab3130 
- Operating System:  iis 2016

#### Steps to Reproduce: 
  * Deploying IIS instance with filebeat and metricbeats (w/ chocolatey), version 6.7.0.  on Azure, as a scale with IIS 2016.. 
  * a Logstash on centOS7 with beats plugin on the 5044  and a Azure Scaleset with the basic loadbalancer.

the configuration of filebeat: 
```
#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["mylogstash:5044"]
```

the configuration of metricbeat: 
```
#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["mylogstash:5044"]
```

I tried to change the async to ttl:
  loadbalance: true
  pipelining: 0
  ttl: 2s

but same result.

but if instead of the hosts output mylogstash.loadbalancer.com I directly put one of my VM ip, it work. it look closed to the load balancer. but don't understand where....

Anyone with a idea ? :)

**Comment by Hkyx** [comment]
cosed, found the Alb problem

**Comment by bigwind123** [comment]
Hi barret,
    I am facing same problem, could you share your solution that about 'Alb problem' ?

**Comment by adrien-barret** [comment]
Something close to a bag or something like that. I don’t really remember tbh it’s like 5/6years ago ;)
