### ISSUE TITLE
[Agent] Discuss the monitoring of the Agent (Logs + metrics)

### ISSUE THREAD

**Issue by ph** [elastic/beats#14914]
Currenly in #14390 we starts sidecars for monitoring the runnings process (Filebeat and Metricbeat). We also need to discuss how we want to report monitoring informations and logs from the Agent.

Early thoughts are we can configure the sidecars to also monitor the Agent.

**Comment by ruflin** [comment]
What is the status of this?

**Comment by ph** [comment]
I think we can close it, we are still keeping the external processes to monitor the agent.
