### ISSUE TITLE
[Metricbeat] Missing data collection from some EC2 instances using aws module

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#14926]
Seems like there is a hard _limit_ in aws module when trying to collect metrics from all EC2 instances. Some instances are missed from the collection. Please see https://discuss.elastic.co/t/metricbeat-aws-cpu-total-pct-missing/209723 for more details.

**Comment by kaiyan-sheng** [comment]
Im currently trying to reproduce this and hopefully will get a workaround and fix soon.

**Comment by skimwpi** [comment]
Hi, we are encountering this issue. If it helps at all, we have instances all in us-east but in various availability zones. We have over 600 EC2 instances and only 100 instances are identified. I imagine if you create EC2 instances slightly over 100 like 150 spread over multiple AZ, it will not recognize all the EC2 instances.

**Comment by kaiyan-sheng** [comment]
Thank you @skimwpi for this info! I will try to reproduce it this way today!

**Comment by skimwpi** [comment]
Also I had the following in my yml file:
**************************
- module: aws
  period: 300s
  metricsets:
    - ec2
  regions:
    - us-east-1
- module: aws
  period: 300s
  metricsets:
    - cloudwatch
  metrics:
    - namespace: AWS/EC2
  regions:
    - us-east-1

**Comment by kaiyan-sheng** [comment]
@skimwpi I found a small bug in the code but I don't think that's the main reason for this issue. Do you see any metrics from these missing instances? In my case, I created 125 instances in AWS us-east-1 region spread into 4 different availability zones. When running aws module, I can see 125 metrics returned. But only some of the metrics have `aws.ec2.cpu.total.pct`.
<img width="1331" alt="Screen Shot 2019-12-04 at 11 00 43 AM" src="https://user-images.githubusercontent.com/14081635/70168206-a4d36400-1685-11ea-9417-2c7d4fb921bb.png">

**Comment by kaiyan-sheng** [comment]
I think I finally was able to reproduce the problem! Working on finding the solution now!

**Comment by kaiyan-sheng** [comment]
Ah found the problem, I missed a pagination in ListMetrics API call.
