### ISSUE TITLE
Clarify intermediate CA usage in Logstash TLS docs

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#1494]
We have a note about "Certificates must be signed by your root CA. Intermediate CAs are currently not supported." We should qualify that point about intermediate CAs. They can only be used if you supply the fully CA chain in a `certificate_authorities` entry. This is caused by logstash-plugins/logstash-input-beats#64.

The PEM file containing the CA chain is created by concatenating the root CA cert and the intermediate CA into a single file: `cat root-ca.crt intermediate-ca.crt > chain.crt` then you set `certificate_authoriities: ['chain.crt']`.

This was prompted by: https://discuss.elastic.co/t/winlogbeat-ignores-ca-certificates-in-windows-certificate-store/48209

**Comment by dedemorton** [comment]
Closing this because we've clarified the docs.
