### ISSUE TITLE
[Agent] FIPS  compliance and could it impact the Agent and endpoint.

### ISSUE THREAD

**Issue by ph** [elastic/beats#14953]
See https://github.com/elastic/beats/issues/14750

**Comment by ruflin** [comment]
@ph Where are we standing here?

**Comment by ph** [comment]
@ferullo Is this a requirement from endpoint or existing endgame users?

**Comment by ferullo** [comment]
This is a potential new requirement coming to us that would a requirement for existing endgame users and endpont.

**Comment by ph** [comment]
@ferullo but at the moment **FIPS compliance is not a requirement**? Because when this **becomes a requirement** this is an effort for the beats framework and we would need some time to assert and implement that.

**Comment by ph** [comment]
Just to be clear I want to prioritize the right way since this has a bigger impact and also much bigger effort to get it right.  AKA if we need this we would depend on a specific branch of Go which is not the normal release.

**Comment by ferullo** [comment]
Correct. Endgame did not ship a FIPS compliant product and we have not received a formal requirement to begin shipping one. I will let you know when either of those things happen.

**Comment by ph** [comment]
Thanks @ferullo :+1:
