### ISSUE TITLE
ContainerID support for non docker containers

### ISSUE THREAD

**Issue by ndubss** [elastic/beats#14967]
Add_docker_metadata needs to be refactored to get containerID of non docker containers. 
[https://github.com/elastic/beats/blob/ce68c7814e5c34ff417701481e1f65f1d5e100cf/libbeat/processors/add_docker_metadata/add_docker_metadata.go#L257-L264](url)

Lookup CID using process cgroup membership data can be moved to add_process_metadata
[https://github.com/elastic/beats/blob/ce68c7814e5c34ff417701481e1f65f1d5e100cf/libbeat/processors/add_docker_metadata/add_docker_metadata.go#L142-L148](url)

@vjsamuel add anything you think I've missed

**Comment by andresrc** [comment]
Can you provide some more detail on the ask? E.g, which runtimes are you expecting to be supported? Thanks!

**Comment by vjsamuel** [comment]
Containerd is one such use case. Under the hood it just uses systemd to create cgroups and can be seen as systemd.slice in the cgroup files.
