### ISSUE TITLE
Investigate adding support for AWS Cloudtrail with both Metricbeat and Filebeat

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#14966]
AWS CloudTrail is a service that enables governance, compliance, operational auditing, and risk auditing of your AWS account.  This issue is to track investigation on supporting Cloudtrail for both Metricbeat and Filebeat.

**Comment by andrewkroh** [comment]
@leehinman is working on a aws/cloudtrail module for Filebeat in https://github.com/elastic/beats/issues/14657.

**Comment by exekias** [comment]
Closed in favor of #14657 :tada: , we missed this one!

**Comment by kaiyan-sheng** [comment]
How about the metricbeat side for Cloudtrail?

**Comment by andrewkroh** [comment]
What is the metricbeat side of Cloudtrail? Does it expose metrics somewhere?

**Comment by kaiyan-sheng** [comment]
Ahh no it does not. I was originally thinking about events from Cloudtrail but that's not monitoring metrics for cloudtrail itself.
