### ISSUE TITLE
[Filebeat] Cisco ASA module failed to parse field [destination.port] of type [long]

### ISSUE THREAD

**Issue by esbenvial** [elastic/beats#14978]
Our ASA sends the following:
%ASA-4-106023: Deny tcp src outside:x.x.xx/56444 dst srv:y.y.y.y/51635(hostname.domain) by access-group "global_access_1"

Filebeat reports
"Cannot index event publisher"
{"type":"mapper_parsing_exception","reason":"failed to parse field [destination.port] of type [long] in document with id 'mPsJ224BZPvwHfzAu5br'. Preview of field's value: '51635(hostname.domain)'","caused_by":{"type":"illegal_argument_exception","reason":"For input string: \"51635(hostname.domain)\""}

Filebeat version: 7.5.0

**Comment by kaiyan-sheng** [comment]
Hi! Seems like cisco module is only supporting `inside:172.31.98.44/8309` instead of `dst srv:y.y.y.y/51635(hostname.domain)`.
