### ISSUE TITLE
[Filebeat] Add dashboard for elb fileset

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#14970]
Dashboard is missing for elb fileset. Adding a predefined dashboard will help improve user experience.

**Comment by mtojek** [comment]
After reviewing the ELB access logs I see that some log data are redundant comparing to ELB metrics (e.g. status codes). Even though I think it's worth putting them here.

I'm considering the following visualizations:
* Requests Geolocation (map)
* Total Requests
* Successful Requests (2xx)
* Redirected Requests (3xx)
* Failed Requests (4xx and 5xx)
* Inbound and Outbound Traffic
* Top user agents
* Top IP addresses

@kaiyan-sheng WDYT?

**Comment by kaiyan-sheng** [comment]
Thanks for working on this @mtojek ! Looking forward to the dashboard (especially the geolocation map)!!

**Comment by mtojek** [comment]
Done. Resolving.
