### ISSUE TITLE
[Metricbeat] Prometheus Remote Endpoint

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#14983]
Today we can capture metrics from Prometheus servers, exporters, push gateways via our Prometheus module in Metricbeat. This requirement takes the next step by adding support for the [remote write](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) feature available in Prometheus. 

Create a way to configure Elastic as a remote endpoint for Prometheus metrics in order to stream samples to Elasticsearch for long term storage and further analysis.

**Comment by exekias** [comment]
This could be a new metricset in the prometheus module, it would open an HTTP server listening for remote_write API calls. Similar to the http.server metricset. I did some tests around this in the past: https://github.com/elastic/beats/compare/master...exekias:prometheus-remote-storage?expand=1

**Comment by ChrsMark** [comment]
@exekias I cherry-picked your commit to start working on it

**Comment by exekias** [comment]
:clap: it's probably quite outdated, so expect there be :dragon:, feel free to change anything there!

**Comment by sorantis** [comment]
> here be dragons

**Comment by ChrsMark** [comment]
Folks there is also this custom beat https://github.com/infonova/prometheusbeat which is also mentioned at https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage.
