### ISSUE TITLE
New protocol support: Oracle TNS

### ISSUE THREAD

**Issue by tsg** [elastic/beats#150]
Split from #22.

**Comment by juerkan** [comment]
+1

**Comment by yeroc** [comment]
Someone referenced this link on the original ticket this was split off from: http://www.pythian.com/blog/repost-oracle-protocol/ (it has useful information on the Oracle TNS protocol).

**Comment by darxriggs** [comment]
[Wireshark](https://www.wireshark.org/) already has a TNS dissector. See [packet-tns.h](https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-tns.h) and [packet-tngs.c](https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-tns.c).

**Comment by darxriggs** [comment]
I will have a look at this protocol. But no promises.

**Comment by easyrasta** [comment]
+1

**Comment by oraant** [comment]
+1

**Comment by binlaniua** [comment]
@darxriggs +1

**Comment by JosefJezek** [comment]
Any progress? :+1:

**Comment by darxriggs** [comment]
From my side it's on hold until someone resolves the legal aspects.

**Comment by monicasarbu** [comment]
We are currently not planning to add support for Oracle TNS as it's a proprietary protocol and an implementation would require a special license from Oracle. If you are an Oracle partner/customer you might be able to help us with this. Please contact me privately at monica@elastic.co.

**Comment by binlaniua** [comment]
@darxriggs expect

**Comment by kimchy** [comment]
to add to @monicasarbu note, we would love to work with Oracle to make sure this is available. The best solution from my perspective is that it will end up being a joint work with the community, Elastic, and Oracle, to make sure this is something that is well maintained. We will try and reach out and see what we can do, but we need your help as Oracle customers to raise it with Oracle as well.

**Comment by tinisky** [comment]
+1

**Comment by alrocar** [comment]
+1

**Comment by smougenot** [comment]
@monicasarbu  Sounds strage to me that Wireshark team can openly (like in opensourced code) analyse Oracle protocol whereas Elastic team could not.

In fact as mentioned in the links posted by @darxriggs (on this issue), The code in Wireshark is based on reversed engineering and not on the official partnership access to Oracle documentations.

Might be worth to contact Wireshark team about it?

**Comment by michalpristas** [comment]
@monicasarbu do you recall if there was a conversation with Oracle about this one?
If no actions were made can we close this issue?
