### ISSUE TITLE
Filebeat module for APM Server

### ISSUE THREAD

**Issue by graphaelli** [elastic/beats#15054]
As part of [monitoring the Elastic stack with Filebeat], we'll want a new Filebeat module for APM server.

**Comment by cachedout** [comment]
Hi @graphaelli. The bot pinged the Stack Monitoring team but you may want @elastic/beats-contributors to see this as well. :)

**Comment by willemdh** [comment]
@graphaelli This shouldn't be closed no?

**Comment by axw** [comment]
In the future APM Server will integrate with Elastic Agent, which will know how to collect logs and metrics for APM Server; this will remove the need for an APM Server-specific Filebeat module.
