### ISSUE TITLE
[Auditbeat] Add full kubernetes support

### ISSUE THREAD

**Issue by nickbabkin** [elastic/beats#15077]
**Describe the enhancement:**

Currently auditbeat supports only files integrity checks when running on kubernetes (according to official documentation here: https://www.elastic.co/guide/en/beats/auditbeat/master/running-on-kubernetes.html). Neither network connections nor process executions and auditd rules are officially supported. Filebeat and packetbeat, on the other hand, already have full support for kubernetes-based environments.

**Describe a specific use case for the enhancement or feature:**

As more and more environments are moving towards microservice based architechture, the demand for auditing kubernetes will grow. Auditbeat shall support auditing same activities on kubernetes that it is currently capable of auditing on regular linux hosts.

**Comment by borgesm** [comment]
Agree 100%. It's a good moment to have Auditbeats to get insights from Kubernetes side.
Here some examples would be great:
- Collection and Dashboard about authentication events from K8s;
- Collection and Dashboard about transactions events from K8s;
- Collection and Dashboard about core components, such as proxy, process and packages updates;

Thanks, Mauricio
