### ISSUE TITLE
test output does not work with ipv6 addresses

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#15078]
Discuss issue: https://discuss.elastic.co/t/help-metricbeat-to-elasticsearch-using-ipv6/211373/2

It seems that running `metricbeat test output` with an ipv6 ES host in the output.hosts does not work.

```console
root@10-245-76-9:/etc/metricbeat# metricbeat test output
elasticsearch: http://[2a00:47c0:511:1297:7aae:5e12:607f:7372]:9200...
parse url... OK
connection...
parse host... ERROR address 2a00:47c0:511:1297:7aae:5e12:607f:7372:9200: too many colons in address
```
The address should be `[2a00:47c0:511:1297:7aae:5e12:607f:7372]:9200` instead.

Maybe the problem lies in https://github.com/elastic/beats/blob/a9aff6f1d8c0eff77b867a358f0fae0a641cbfb9/libbeat/outputs/elasticsearch/client.go#L671.

**Comment by onequid** [comment]
Just created a PR for this. And I am new here, so please tell if anything is inappropriate. Thank you.
