### ISSUE TITLE
[Fingerprint processor] Add xxHash as hash option

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#15080]
Per @vjsamuel's suggestion, [xxHash](https://cyan4973.github.io/xxHash/) is a much faster hashing algorithm than sha256, which is currently the default method for the [fingerprint processor](https://www.elastic.co/guide/en/beats/filebeat/master/fingerprint.html).

We should add xxHash as an hashing method option to the fingerprint processor in 7.x. In 8.0 we can make this the default method (as it would be a breaking change).

**Comment by rvillablanca** [comment]
Hi @ycombinator, I would like to work on this :smiley:

**Comment by ycombinator** [comment]
Sounds great, @rvillablanca, thanks!  Just put up a pull request whenever you have it ready and ping me on it for review.  Happy to answer any questions you might have.

**Comment by rvillablanca** [comment]
Friendly reminder we can close this issue now

**Comment by ycombinator** [comment]
Closed via #15418.
