### ISSUE TITLE
Topbeat numeric value out of range of int

### ISSUE THREAD

**Issue by tsg** [elastic/beats#1509]
- Version: 5.0.0-alpha2SNAPSHOT
- Operating System: Linux
- Elasticsearch 2.x

I've got an error while testing topbeat on a VM with Elasticsearch 2.3.2

```
2016/04/28 09:05:53.714141 client.go:171: DBG  Publish: {
  "@timestamp": "2016-04-28T09:05:53.700Z",
  "beat": {
    "hostname": "precise32",
    "name": "precise32"
  },
  "fs": {
    "avail": 19168059392,
    "device_name": "vagrant",
    "files": 1000,
    "free": 19168059392,
    "free_files": 1000,
    "mount_point": "/vagrant",
    "total": 249779191808,
    "used": 230611132416,
    "used_p": 0.92
  },
  "type": "filesystem"
}
2016/04/28 09:05:54.609210 output.go:108: DBG  output worker: publish 45 events
2016/04/28 09:05:54.655655 client.go:283: WARN Can not index event (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse [fs.avail]","caused_by":{"type":"json_parse_exception","reason":"Numeric value (78209593344) out of range of int\n at [Source: org.elasticsearch.common.io.stream.InputStreamStreamInput@ceb6ac7; line: 1, column: 118]"}
```

Looks like something should be long rather than integers.

**Comment by tsg** [comment]
It seems that in the previous templates we didn't specify any type for most of the numeric values, and the default that ES choses is `long`.

CC @ruflin, this likely affects metricbeat in many places. We should probably go with long whenever we are unsure.

**Comment by ruflin** [comment]
@cerw Please open a topic on discuss with some more details like your config and your logs: https://discuss.elastic.co/c/beats/metricbeat
