### ISSUE TITLE
Filebeat: Error watching for docker events: context deadline exceeded

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#15096]
The following error has been reported:
```
{
  "stream": "stderr",
  "caller": "docker/watcher.go:303",
  "level": "error",
  "message": "Error watching for docker events: context deadline exceeded"
}
```

Since this is something that comes from https://github.com/elastic/beats/blob/24c1e59c1a91fb2aad97531a54e7337259af0343/libbeat/common/docker/watcher.go#L247 and most probably because Docker API takes to long to respond for events at the point of reaching timeout, we should consider of handling this "error" explicitly at  https://github.com/elastic/beats/blob/24c1e59c1a91fb2aad97531a54e7337259af0343/libbeat/common/docker/watcher.go#L311 and log a friendlier message.

This will avoid creating confusion.

discuss: https://discuss.elastic.co/t/filebeat-error-watching-for-docker-events-context-deadline-exceeded/211113

**Comment by mattschoch** [comment]
Just updated to filebeat 7.5.0 and now I'm getting this error every hour, I wasn't getting it before on 7.2.0. Is there a known workaround, or any idea why this is seeming to happen now when it wasn't previously?

**Comment by jacobmw** [comment]
I am on filebeat 7.5.1 and get this message four times, at the same time, every hour.  Seems to be at the same minute as when I started the service.
