### ISSUE TITLE
Switch doc build to use direct_html

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#15105]
When all beats books build successfully with the `direct_html` flag, change `make docs` and `make docs-preview` to use the new flag.

Here's the first PR for changes: https://github.com/elastic/docs/pull/1597

**Comment by nik9000** [comment]
I believe all of the beats books build successfully with `--direct_html` but they don't build *perfectly* yet. I should get to that early next week.

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/beats/pull/15159
