### ISSUE TITLE
Add username/password in Metricbeat autodiscover hints

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#15115]
**Describe the enhancement:**
Currently we don't have username/password in [autodiscover hints](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html).  In order to set this you need to make use of `raw` hint. Since these are really common configuration options we should consider adding them to the list of known hints.

**Describe a specific use case for the enhancement or feature:**
https://discuss.elastic.co/t/metricbeat-autodiscover-hints-for-mysql/211575/3

Implementation would be similar to https://github.com/elastic/beats/pull/14208#.

### Manual Testing
1. Enable autodiscover in metricbeat.yml
```
metricbeat:
  autodiscover.providers:
    - type: docker
      hints.enabled: true
```
2. Start metricbeat with log enabled: `./metricbeat -e -d "hints.builder" `
3. `docker run -l co.elastic.metrics/module=nats -l co.elastic.metrics/username=user42 --name nats nats`
4. Check in Metricbeat logs for : `2019-12-16T15:53:18.712+0200	DEBUG	[hints.builder]	hints/metrics.go:144	generated config: {"enabled":true,"hosts":null,"metricsets":["connections","routes","stats","subscriptions"],"module":"nats","period":"1m","processors":null,"ssl":null,"timeout":"3s","username":"user42"}`

**Comment by rvillablanca** [comment]
This issue is marked as `good first issue` but it already has a PR in progress. Is there any label to mark some issues that have PR ?

**Comment by ChrsMark** [comment]
> This issue is marked as `good first issue` but it already has a PR in progress. Is there any label to mark some issues that have PR ?

Hey usually they should be marked with `in progress` label. I just added it.
