### ISSUE TITLE
Update Elasticsearch metricbeat modules to support `max_resource_units`

### ISSUE THREAD

**Issue by ph** [elastic/beats#15148]
With the addition of the "Enterprise" license in Elasticsearch, the response returned by the API will be changed. The endpoint will return `max_resource_units` instead of `max_nodes` So the code in the [module](https://github.com/elastic/beats/blob/157ea8fe641001dcb6ad9309d25285ba33ba1498/metricbeat/module/elasticsearch/elasticsearch.go#L117) will need to be adjusted.

**Example output:**

```json
{ 
  "license": { 
    "uid": "bf610b02-470e-d453-0b75-d2f7dfead89f",
    "type": "enterprise",
    "issue_date_in_millis": 1576000000000,
    "start_date_in_millis": 1576000000000,
    "expiry_date_in_millis": 1590000000000,
    "max_resource_units": 100,
    "issued_to": "Elastic - INTERNAL",
    "issuer": "Fabio Busatto",
    "signature": "AAAA...xyz"
  }
}
```

**Note:** we need to clarify what happens with the other license type are they still returning the old format of everything has been moved to `max_resource_units`

**Comment by ph** [comment]
@elastic/stack-monitoring @ycombinator we will need to make this change with the addition of the new license type.

**Comment by ph** [comment]
Adding a note concerning other license types and the response format, we need to do a followup on that.

**Comment by bytebilly** [comment]
Thanks for the issue @ph!

Do you already have a possible timeline for that?
I think that this is not really required until 8.0, unless you want to add the `accept_enterprise=true` to the API call from the agent.
In 7.x the default behavior is to return `platinum` with `max_nodes` (backward compatible mode).

Clearly if you have capacity to move in advance, nothing against that 🙂

**Comment by ycombinator** [comment]
@bytebilly PR for the change is already up: https://github.com/elastic/beats/pull/15152. We should be able to get this out in 6.8.
