### ISSUE TITLE
Make Kubernetes log metadata more discoverable and consistent

### ISSUE THREAD

**Issue by JoshMock** [elastic/beats#15151]
**Describe the enhancement:**

When metricbeat records Kubernetes events, it [writes the resource's namespace to the field `kubernetes.event.metadata.namespace`](https://www.elastic.co/guide/en/beats/metricbeat/7.5/exported-fields-kubernetes.html#_metadata_2). Alternatively, when filebeat records logs from a Kubernetes pod, it [writes them to the field `kubernetes.namespace`](https://www.elastic.co/guide/en/beats/filebeat/7.5/exported-fields-kubernetes-processor.html#exported-fields-kubernetes-processor).

Furthermore, because events in k8s behave more like logs than metrics data, it's unintuitive and time-consuming to learn that the events are being written to a metricbeat index rather than a filebeat index.

When exploring large amounts of k8s data, these kinds of inconsistencies can inhibit developers from quickly finding and working with the data they're looking for.

**Describe a specific use case for the enhancement or feature:**

Diagnosing a Kubernetes deployment that is failing to get to a healthy state. Someone might start by searching for a pod's logs in a filebeat index pattern, using queries like `kubernetes.namespace: "production"`. If there are no logs, and the failure is happening before the pod starts writing logs, the relevant information would likely be recorded as events in a pod, deployment, service, ingress, etc. In order to find _those_ logs, someone would need to switch to a metricbeat index pattern, and use a query like `kubernetes.event.metadata.namespace: "production"`.

**Comment by exekias** [comment]
++ I think we should rename `kubernetes.event.metadata.namespace` to `kubernetes.namespace`. Also review the rest of fields that we have there to see if there are more ECS fields we can rename.

**Comment by ChrsMark** [comment]
Keeping open.
