### ISSUE TITLE
[Functionbeat] Investigate the behavior when Logstash output is used.

### ISSUE THREAD

**Issue by ph** [elastic/beats#15161]
The way AWS lambda operates is as soon as the lambda handle returns from execution the system can decide to freeze the function, unfreeze it later or completely destroy the running container. Because of that, we have a few things we would want to investigate to make sure the output behaves correctly:

- How retries affect the Logstash output, are we retrying indefinitely 
- How freezing the function affect the TCP connection (@ph thinks beats will reconnect and Logstash will kill the connection after a period of time)

**Comment by jsoriano** [comment]
> How retries affect the Logstash output, are we retrying indefinitely

I saw some similar issues in other beats some time ago https://github.com/elastic/beats/issues/11732
