### ISSUE TITLE
[Heartbeat] Rootless ping sometimes returns a cryptic error with invalid perms

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#15165]
Sometimes, in scenarios I'm still trying to pin down, running ICMP pings without permission to do so can yield the cryptic error `write udp 0.0.0.0:0->8.8.4.4: invalid argument` where the second IP is the target of the ping.

This seems to be caused when running as a regular user on linux without adequate perms (either through setcap or sysctl ping groups). 

I was able to reproduce this once on my linux laptop, but weirdly not a second time.

In any event, the fix here is to properly detect this lack of perms somehow. For some odd reason capability detection started working for me after failing earlier today.

**Comment by afshineffati** [comment]
running rhel ubi9  image with heartbeat on OpenShift as non-root user. \\Container has sysctl ipv4 ping group range of `net.ipv4.ping_group_range = 0  2147483647`

Despite the non-root user falling within the range, still getting 
`could not write to conn: write udp 0.0.0.0:8> ***: invalid argument`

heartbeat 8.15.1
