### ISSUE TITLE
[Heartbeat] `http` type: `urls` vs `hosts`

### ISSUE THREAD

**Issue by fkelbert** [elastic/beats#15183]
Version:  7.5

The [documentation](https://www.elastic.co/guide/en/beats/heartbeat/7.5/configuration-heartbeat-options.html#monitor-http-options) lists option `hosts` for the Heartbeat `http` type.

In contrast to this, the default config file (`heartbeat.yml`) uses option `urls` for the same purpose.

I suppose this should be corrected within `heartbeat.yml`.

**Comment by gchiartosini** [comment]
Sorry anyone has updates on this issue?
Could you update the documentation about it?

**Comment by maximhan** [comment]
Any plan for when this will be fixed?

It's very confusing how it's currently written in the documentation, as the docs themselves (in several places) shift between `hosts` and `urls` for the examples listed, like:

![image](https://user-images.githubusercontent.com/264774/116057706-59a56100-a67f-11eb-8dee-21fcf6a2eb9a.png)

Pages we've found this:

- https://www.elastic.co/guide/en/beats/heartbeat/7.5/configuration-heartbeat-options.html#monitor-http-options
- https://www.elastic.co/guide/en/beats/heartbeat/current/monitor-http-options.html

The `urls` option is not documented anywhere, but it is then confusing if it's just remnants of a change done previously, or if the `urls` option actually has a special meaning/use.

**Comment by muhammad-elastic** [comment]
"urls" and "hosts" both still persist in heartbeat 7.15. Very confusing for the customers.

**Comment by maxim-hansen** [comment]
👍
