### ISSUE TITLE
[Heartbeat] Docs do not mention `name:` option

### ISSUE THREAD

**Issue by fkelbert** [elastic/beats#15185]
Version: 7.5

[Heartbeat documentation](https://www.elastic.co/guide/en/beats/heartbeat/7.5/configuration-heartbeat-options.html) does not mention option `name` for monitors. Setting this option, is, however essential to get a meaningful description within the Kibana Uptime app (otherwise, an auto-generated name will be shown). 

Similarly, `heartbeat.yml` should list this option with an example value (possibly commented).

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
