### ISSUE TITLE
[Filebeat]add compatibility information to kafka input

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/beats#15199]
**Describe the enhancement:**

Current doc https://www.elastic.co/guide/en/beats/filebeat/7.5/filebeat-input-kafka.html may warrant compatibility information such as below.
Below exists in [kafka output](https://www.elastic.co/guide/en/beats/filebeat/7.5/kafka-output.html#kafka-compatibility) but not in [kafka input](https://www.elastic.co/guide/en/beats/filebeat/7.5/filebeat-input-kafka.html)

```
Compatibility
This output works with all Kafka versions in between 0.11 and 2.1.0. Older versions might work as well, but are not supported.
```

I tracked [sarama](https://github.com/Shopify/sarama#compatibility-and-api-stability) library is used in both input and output, but I could not determine if they are using the same version.

**Comment by jsoriano** [comment]
@TomonoriSoejima in principle same versions are supported in kafka input and output, but it is true that it should be documented in both places. Thanks for reporting!
