### ISSUE TITLE
Include description, product name and product version in Windows versions of Beats 

### ISSUE THREAD

**Issue by ehengel** [elastic/beats#15232]
The Windows version of different Beats has an .exe file that lacks info on Product name and Product version. See screenshot1.png.  Also, the Beat service doesn't seem to have a Description like other services in Windows when looking at services.msc.  See screenshot2.png. 

The above would be great to have when scripting upgrades of Beats using for example powershell and you want to check which product version of the is file available. Apart from that this info would make it consistent with other .exe files and services in Windows. 

<img width="738" alt="screenshot1" src="https://user-images.githubusercontent.com/10902108/71246837-c97f3b00-2317-11ea-94be-6dc0bf792edc.png">
<img width="1206" alt="screenshot2" src="https://user-images.githubusercontent.com/10902108/71246864-d865ed80-2317-11ea-9d81-254afff47a21.png">

**Comment by andrewkroh** [comment]
I opened a PR to add this info to .exe files in https://github.com/elastic/beats/pull/16048.
