### ISSUE TITLE
Metricbeat 7.5.1 with kibana-xpack enabled , fails to start if Kibana is unavailable upon start

### ISSUE THREAD

**Issue by kkh-security-distractions** [elastic/beats#15258]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 
       Metricbeat : 7.5.1
- Operating System: 
    Redhat linux 7.6
- Discuss Forum URL:
- Steps to Reproduce: 
      Follow documentation to enable kibana-xpack.yml module in metricbeat
     configure kibana-xpack.yml to point at local kibana instance , with credentials
    stop kibana
    start metricbeat
   check status of metricbeat , it is failed
   try launch metricbeat manually , attached error screenshot

  now start kibana
  start metricbeat
  verify all is ok

![image](https://user-images.githubusercontent.com/46199257/71514046-3efd8500-289d-11ea-8acc-a8058a3dc304.png)

**Comment by ycombinator** [comment]
I can confirm this behavior locally. I believe this is a bug as we should allow Metricbeat to be running independently of Kibana's lifecycle. I'm working on a fix now.

**Comment by kkh-security-distractions** [comment]
I have since I created this issue also verified the same problem occurs with the logstash-xpack nodule.

**Comment by ycombinator** [comment]
Thanks @kkh-security-distractions. I just put up the fix for the `kibana-xpack` module. I will work on a similar fix for the `logstash-xpack` module as well.

**Comment by ycombinator** [comment]
Issue to track Logstash module bug: https://github.com/elastic/beats/issues/15276.
