### ISSUE TITLE
Apache-2.0, not ASL 2.0 for org.label-schema.license

### ISSUE THREAD

**Issue by urso** [elastic/beats#15259]
Correct naming of the apache license used by Beats is "Apache License 2.0". The short identifier for said license, that is also used by Elasticsearch for example, is "Apache-2.0". Not "ASL 2.0" . See: https://www.apache.org/licenses/LICENSE-2.0

The docker container label 'org.label-schema.license' should use "Apache 2.0".

**Comment by andrewkroh** [comment]
`ASL 2.0` is the appropriate value to using in RPMs if I understand this info correctly.
- https://fedoraproject.org/wiki/Packaging:LicensingGuidelines#Valid_License_Short_Names
- https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#Good_Licenses

**Comment by urso** [comment]
The issue is about docker containers, not rpm/deb. Sorry for the confusion. The Elasticsearch docker container already uses "Apache 2.0". License via label-schema (which has been more or less superseded by the opencontainers initiative) seems to prefer SPDX: https://spdx.org/licenses/

Open Containers annotations: https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys
Label schema PR defining the license field: https://github.com/label-schema/label-schema.org/pull/21

Elasticsearch also uses ASL for its deb/rpm packages.
