### ISSUE TITLE
[Agent] Add Agent UUID  in a metadata field to the events shipped from the process

### ISSUE THREAD

**Issue by ph** [elastic/beats#15268]
**Goal:** We want to track the source of events created from process managed by an Agent. The obvious path would be to add metadata fields in the generated configuration for the process. To add support for this we have the following options:

1. Make fleet generates the right configuration and Agent only executes it.

This actually hides the details and the implementations, Fleet already knows everything about the agent to make it work. This might also help with the upgrades between versions?

2. Make the agent generates directly the right configuration.

This adds more logic to the agent and actually requires the agent to know even more about the processes that need to be executed. Also, it requires us to do merges in fields values.

3. A mix of both, generate a configuration from Fleet and use `variables` that will be replaced by the agent with concrete values.

This is similar to 1 but it might open more new use cases when we can use local metadata.

----

**Agent UUID**

With that we need to add the Agent UUID to each generated events, if we look at ECS one possibility would be to use the `agent.id` but this actually could lead to issues since that field represent the system that created the event. The safest course of action would be to actually use an `elastic` namespace and keep the _UUID_ under `elastic.agent.id`

**Comment by ph** [comment]
cc @ruflin @michalpristas

**Comment by michalpristas** [comment]
we need to include it in all errors as well. if we do the injection at the point when event gets into reporter it should be e fairly simple change

**Comment by ruflin** [comment]
+1 on introducing ˋelastic.agent.idˋ. There will be cases where ˋagent.idˋ is populated but with a different id, for example when running apm-server in the future.

**Comment by ph** [comment]
@ruflin @ruflin For where that configuration is generated what your position on that? Maybe it make more sense that this is actually handled by Fleet because we could possible keep multiples version of the configuration.

**Comment by ruflin** [comment]
Fleet should not have an influence on `elastic.agent.id`. If the agent is run with or without Fleet, there shouldn't be a different. For the `agent.id`, lets move it to an other thread.

**Comment by michalpristas** [comment]
I think we can close this @ph is there something missing?
