### ISSUE TITLE
[Metricbeat] Add Redis node and proxy 

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#15269]
Currently the Redis module in Metricbeat only support database metrics. In addition to db metrics Redis Enterprise exposes node and proxy metrics. We should add support for node and proxy metrics to redis module. Note that starting from v 5.0.2 Redis [exposes metrics at the node, database, shard and proxy levels via a Prometheus endpoint](https://docs.redislabs.com/latest/rs/administering/monitoring-metrics/prometheus-integration/). This could simplify further development of the redis module.

## Modules

For a metricset to go GA, the following criterias should be met:

* [x] Supported versions are documented
* ~[ ] Supported operating systems are documented (if applicable)~
* [x] Integration tests exist
* [x] System tests exist
* [x] Automated checks that all fields are documented
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] Dashboards exists (if applicable)
* [x] Kibana Home Tutorial (if applicable)
  * Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).
* [x] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [x] Test environment in Docker exist for integration tests

**Comment by mtojek** [comment]
@sorantis

Here comes to mind similar questions to https://github.com/elastic/beats/issues/7723 : 

1. Can we simply switch Prometheus metrics endpoint only?

2. How can we deprecate old code?

**Comment by andresrc** [comment]
IMHO, when possible we should keep native integration

**Comment by sorantis** [comment]
See my response in #7723. TLDR; I agree with Andres - use native APIs if possible.

**Comment by mtojek** [comment]
Checklist has been updated. I've started preparing a relevant dashboard.

**Comment by mtojek** [comment]
Resolving.
