### ISSUE TITLE
[Metricbeat] When Logstash module is enable and we fail to reach it, metricbeat refuses to starts

### ISSUE THREAD

**Issue by ph** [elastic/beats#15276]
Looking at the code of the Logstash module I believe the module is also affected by a similar bug defined in https://github.com/elastic/beats/issues/15258 for Kibana. I also looked at the Elasticsearch module but I think this one is OK.

https://github.com/elastic/beats/blob/d545f6902ecbea3fcaf48e91edd1e1d4e1bcd7e3/metricbeat/module/logstash/node/node.go#L55-L81

**Comment by ph** [comment]
@ycombinator could you take a look?

**Comment by ph** [comment]
I haven't checked the beat modules, so we might want to double-check them to make sure the module is not affected by a similar bug.

**Comment by ycombinator** [comment]
I checked the `beat` module, and it is okay. It's not making any HTTP calls in the `New` function.

**Comment by radoondas** [comment]
Hey @ycombinator & @ph, I am a bit confused if this one is bug which we will fix or this is not a bug for Logstash output in the end. Can you please clarify? Thanks!

**Comment by ph** [comment]
@radoondas It's a bug, but it's not related tot he Logstash output but to **Metricbeat's Logstash module**, the module that query the Logstash API to collect metrics and send them to Elasticsearch.
