### ISSUE TITLE
filebeat 1.2.2 reships rotated log files upon restart due to lost offset

### ISSUE THREAD

**Issue by jstangroome** [elastic/beats#1528]
We just updated from filebeat 1.1.2 to 1.2.2 to resolve #1281 in our environment. This has revealed a new issue.

We are experiencing the problem on a local ext4 file system on Ubuntu 14.04 running in AWS EC2 and also running in Virtualbox 5.

I have created a bash script which reproduces the issue and published it as a gist, including a log of the output:
https://gist.github.com/jstangroome/0774df94b46aa288b0855f533c67d152

Essentially when filebeat exits, the registry is recorded with the entry for the fully-shipped and recently-rotated log file not having an offset specified.

When filebeat is started again, the missing offset value is treated effectively the same as `"offset": 0` and the log file's contents are reshipped. Because the file was rotated recently, it is still new enough that `ignore_older` directives won't exclude it.

/cc @ruflin

**Comment by ruflin** [comment]
@jstangroome Thanks for the report. I will have a look and hopefully be able to provide a fix.

**Comment by ruflin** [comment]
I created a test case for the issue here: https://github.com/elastic/beats/pull/1532 Hopefully I can provide a fix soon.

**Comment by ruflin** [comment]
@jstangroome I think I found a fix in https://github.com/elastic/beats/pull/1532

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/beats/pull/1532 was merged. This fix will also be backported to master.
