### ISSUE TITLE
Filebeat: retain original type of fields added in configuration

### ISSUE THREAD

**Issue by robin13** [elastic/beats#1534]
If you add a field in the prospector section of filebeat configuration

```
      fields:
        widget_number: 10
```

This will be added to each document as:

```
"widget_number":"10"
```

but it would be better if numbers were not cast as string, and would remain:

```
"widget_number":10
```

**Comment by DirkAmelinckx** [comment]
+1

**Comment by ruflin** [comment]
I assigned the libbeat label here as this would be a general improvement to the way fields are handled.

**Comment by andrewkroh** [comment]
This is the behavior in v5. Changed in https://github.com/elastic/beats/pull/1092

From the 5.0 changelog:

> - Scalar values in used in the `fields` configuration setting are no longer automatically converted to strings. {pull}1092[1092]
