### ISSUE TITLE
[Agent]  Defining an index or an ingest pipeline in stream doesn't work.

### ISSUE THREAD

**Issue by ph** [elastic/beats#15391]
When you define an index or an ingest pipeline in a streams the events generated from the streams doesn't respect it.

**Comment by ph** [comment]
Let's do the minimal work initially before doing the rework on the input strategy to have the least have data going in and test for permissions and make sure that fleet branch have a complete end to end code.

The logic will be something like this:

For every filebeat inputs send data to `logs-*`..
For every Metricbeat input send data to the `metrics-*`

**Comment by michalpristas** [comment]
can we close this?
with new config structure we are composing index in form of logs/metrics-dataset-namespace

**Comment by ph** [comment]
ok to close.
