### ISSUE TITLE
file is closed

### ISSUE THREAD

**Issue by peng0208** [elastic/beats#15412]
hi, can you take me a hand?
my file can not be collected, and there are a lot of logs output:
"file is falling under ignore_older before harvesting is finished. Adjust your close_* settings."
What's the problem?

**Comment by faec** [comment]
Hello! Sorry, this is for filing issues and bugs related to beats. For help with general use and configuration, please try the [discuss forums](https://discuss.elastic.co/c/beats/filebeat).
