### ISSUE TITLE
How to match Event ID, Knowledge Base DB with winlogbeat

### ISSUE THREAD

**Issue by kan1207** [elastic/beats#1541]
I am new to Winlogbeat and would like to know how to match Event ID, Knowledge Base DB (https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/default.aspx) with winlogbeat  Thanks.

**Comment by ruflin** [comment]
@kan1207 Thank you for getting in contact with us. For questions please use https://discuss.elastic.co/c/beats/winlogbeat Closing this issue.
