### ISSUE TITLE
[Filebeat 7.5.1] Bug in imported Cisco ASA Dashboard

### ISSUE THREAD

**Issue by MarcusCaepio** [elastic/beats#15420]
Hi all,

At Filebeat 7.5.1 the imported Dashboard "[Filebeat Cisco] ASA Firewall" has a Visualization called "Top ACL by Blocked" which wants to access the field "cisco.asa.list_id".
Since Filebeat 7.4 this field is not valid anymore. It has to be "cisco.asa.rule_name" according to the docs at https://www.elastic.co/guide/en/beats/libbeat/master/breaking-changes-7.4.html

Cheers,
Marcus

**Comment by MarcusCaepio** [comment]
Same for the Visualization "Top ASA Messages [Filebeat Cisco]" -> "Sample Message". Has to be event.original instead of log.original

**Comment by adriansr** [comment]
Thanks for reporting. It'll be fixed in 7.5.2
