### ISSUE TITLE
beats/logstash doesn't consistently name ES index for ILM default

### ISSUE THREAD

**Issue by sgreszcz** [elastic/beats#15424]
Elasticsearch version (bin/elasticsearch --version):

7.5.1 (elastic.co cloud), problem happened with previous 7 versions too.

I was asked to open this issue from the elasticsearch github: https://github.com/elastic/elasticsearch/issues/50789

Description of the problem including expected versus actual behavior:

According to the documentation, the default beat/logstash index pattern should be applied to the index name to support ILM. https://www.elastic.co/guide/en/beats/metricbeat/current/ilm.html#setup-ilm-pattern-option

%{now/d}-000001

This is not happening consistently, and indices are being named with the "filebeat-7.5.1-" without the extension. It seems to be happening randomly. You can see in the screenshot below that some of them are named properly and some of them are not. The elastic output from beats and logstash are set as default and there are no changes to the index name.

![72063705-31e78980-32d2-11ea-9d38-ef56f18611cb](https://user-images.githubusercontent.com/22910494/72089657-5a887700-3304-11ea-8669-158dd613da00.png)

Steps to reproduce:

Stop all beats or logstash shippers
Delete indexes in elasticsearch
Start up the beats/logstash
Sometimes they name the new index with the proper ILM extension (%{now/d}-000001), and sometimes only with just the prefix (shipper-version-).
Provide logs (if relevant):

If someone can tell me how from the cloud instance, I can attach them.

After doing a stop of all metricbeat 7.5.1 and logstash 7.5.1 indexes and index templates, and starting the data shipper containers, this time the indexes got names properly and linked to the ILM profiles OK.

I'm still not sure why it works sometimes and not another, especially when upgrading from one version of the shippers to the next. Maybe it gets caught up with the existing index template being there?

<img width="870" alt="72086733-573ebc80-32ff-11ea-8080-00cf7e2a053c" src="https://user-images.githubusercontent.com/22910494/72089745-7db32680-3304-11ea-89e5-9ce4ee7e06bc.png">
<img width="825" alt="72086734-573ebc80-32ff-11ea-92f4-da3271ee69b4" src="https://user-images.githubusercontent.com/22910494/72089747-7e4bbd00-3304-11ea-91aa-b8e315f7f49f.png">

**Comment by faec** [comment]
Thanks for reporting! You may not have this anymore if all the indices are working now, but in the first screenshot it shows indices with lifecycle errors, do you know what those errors were?

**Comment by sgreszcz** [comment]
> Thanks for reporting! You may not have this anymore if all the indices are working now, but in the first screenshot it shows indices with lifecycle errors, do you know what those errors were?

I think the lifecycle errors were either the APM indexes (that always seem to report some sort of lifecycle errors) or the fact that the default index naming (as per this issue) was incorrect and therefore the ILM profile wasn't working.

Fortunately our production filebeat, metricbeat, and logstash naming is now OK and the indexes are looking good:

<img width="1052" alt="Screenshot 2020-01-13 at 12 06 14" src="https://user-images.githubusercontent.com/22910494/72281378-54f79d80-3632-11ea-92fa-fdac1d8d9344.png">

**Comment by sgreszcz** [comment]
Something is still not healthy with ILM despite the naming being OK and the policies existing.  I've got a red filebeat-7.5.1-2020.01.13-000005 index:

<img width="1163" alt="Screenshot 2020-01-16 at 11 22 26" src="https://user-images.githubusercontent.com/22910494/72521048-9f576500-3852-11ea-8c84-3270caf2a846.png">

**Comment by sgreszcz** [comment]
This is still a problem sometimes in 7.6.0.  Stopping beats and deleting the incorrect named indexes works.  If you don't do this the default beats ILM policies won't work.

Before:

<img width="1181" alt="Screenshot 2020-03-10 at 12 50 39" src="https://user-images.githubusercontent.com/22910494/76316352-61b30d80-62d2-11ea-849a-b6e419de3901.png">

After:

<img width="1176" alt="Screenshot 2020-03-10 at 13 18 15" src="https://user-images.githubusercontent.com/22910494/76316375-6a0b4880-62d2-11ea-9ad4-856f3c3081ff.png">
