### ISSUE TITLE
[Agent] Missing dependency

### ISSUE THREAD

**Issue by mattapperson** [elastic/beats#15433]
When compiling Agent from source you get an error that "github.com/hashicorp/go-multierror" is missing. Installing that dependency fixes the error

**Comment by ph** [comment]
@michalpristas  can  you take a look, we have probably had an issue when we updated from master?

**Comment by ph** [comment]
One thing that is curious is this work on CI? I wonder if the environment that @mattapperson uses have go modules enabled. I am not sure how that would happen.

**Comment by ph** [comment]
@mattapperson What is the output of `find -name go.mod` in the beats repository?

**Comment by ph** [comment]
After discussing with @mattapperson He was using another branch named [agen](https://github.com/elastic/beats/tree/agent)`, so I think that branch is broken. @michalpristas I don't think we have anything in that branch worth to keep? if its a yes I am going to delete it next week.

**Comment by michalpristas** [comment]
oh i think it's the branch i used for work on fb/mb integration on our first try even before we had fleet branch
i'm going to delete it

**Comment by ph** [comment]
@mattapperson I am going to close this because I strongly believe its just because its the wrong branch.
