### ISSUE TITLE
Add 'pipeline' config param to elasticsearch output

### ISSUE THREAD

**Issue by urso** [elastic/beats#1547]
ingest node pipeline can be configured via generic parameters in elasticsearch:

before:
```
output.elasticsearch:
  parameters:
    pipeline: my-node
```

after:
```
output.elasticsearch:
    pipeline: my-node
```

**Comment by ruflin** [comment]
+1 on this change as it makes pipeline a first class citizen. I assume in the background it is just a mapping of the params.
