### ISSUE TITLE
[Heartbeat] Add monitors of type udp

### ISSUE THREAD

**Issue by nkakouros** [elastic/beats#15490]
**Describe the enhancement:**

Currently, `tcp`, `icmp` and `http` monitor types are provided. A new type, 'udp', could be introduced that checks if a udp port is open. Since there is no handshake going on, support for the most popular protocols could be added. For instance, for DNS, a query for a dummy domain could be sent. `nmap` has support for UDP that could be useful.

**Describe a specific use case for the enhancement or feature:**

There are lots of useful protocols that run over UDP, such as DNS, DHCP, etc. There is no way to test that such services are up and running right now.

**Comment by andrewvc** [comment]
Apologies for the delay in responding here. 

This is a good proposal, and one that I think makes sense to implement at some point in some manner.

The key difficulty with UDP monitoring is that UDP is a connection-less protocol without any guarantee of replies. There are some ways to determine if a port is definitely closed (see [this](https://networkengineering.stackexchange.com/questions/26541/how-to-verify-that-a-udp-port-is-open) SO reply), but it isn't very robust.

What probably makes more sense is to individually support, say, DNS checks, or DHCP checks IMHO, where we natively speak the higher-level protocol.

I'd be curious as to your thoughts @nkakouros

**Comment by andrewvc** [comment]
Having discussed this with the team, this isn't something that would fit onto our near or medium term roadmap. We appreciate the thoughtful issue, but this isn't something we'd tackle ourselves at the moment. Our current focuses on alerting and a richer UI are a higher priority at the moment.

I'm going to close this for now to help keep our issues clean, but expanding the number of services heartbeat can monitor is something we may tackle in the future.

**Comment by nkakouros** [comment]
Just for the record, having specific protocol support is super fine too, at least for those services that are quite crucial for a network (DNS, DHCP, ...)

**Comment by ZuoGuocai** [comment]
Hope see the dns and dhcp check  in the furture feature.
