### ISSUE TITLE
Launch between apps fails due to filebeat and metricbeat defaults

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/beats#15521]
Launch between Uptime, Logs, and Metrics depends on the field `host.ip` being populated in metricbeat and filebeat records.  By default this is disabled.  I opened a PR with the changes to the configs: https://github.com/elastic/beats/pull/15347

Default config:
```
processors:
  - add_host_metadata: ~
```

Necessary config:
```
processors:
  - add_host_metadata:
      netinfo.enabled: true
```

- Version: 7.5.1
- Steps to reproduce:
    - run with default configs
    - attempt to launch from uptime to Logs or Metrics
    - note the filter that is applied
    - check to see if the field in the filter is being populated
    - modify filebeat.yml or metricbeat.yml and enable netinfo
    - restart filebeat or metricbeat
    - notice that the filter succeeds

**Comment by exekias** [comment]
Thank you for opening @DanRoscigno! pinging @andrewvc && @jasonrhodes as I don't know much about how links from Uptime work. Is this expected?

**Comment by andrewvc** [comment]
Yes, it is expected, IPs are really the only way we can correlate. Is there any opposition to changing this default?

**Comment by blakerouse** [comment]
Wouldn't hostname be a better correlation as IP addresses can move around with VIP's and DHCP leases?

**Comment by DanRoscigno** [comment]
> Wouldn't hostname be a better correlation as IP addresses can move around with VIP's and DHCP leases?

yes, I think that in the future that would be a good idea.  I would be glad to open an issue for that for a future change.  I would still like this fixed soon as the integrations are broken.

**Comment by andrewvc** [comment]
Maybe? I mean it depends on the setup. I think what we need here is to broaden the scope a bit and think about how we want this integration to work. Is automatic guessing of fields even the right approach?

@drewpost would appreciate your input here.

**Comment by DanRoscigno** [comment]
@andrewvc, that is exactly the right question.

In my experience, ops wants to "see everything for my service".  So, not the logs for a particular host, but all of the logs for a particular service.  Going back to the reason i opened the issue: I was looking at uptime for a service.  From there I launched into Logs.  The way the integration is written today, the filter is for all of the logs from the host which heartbeat is testing.  What I would want is to have all of the logs from:
 - all of the hosts related to that service being monitored with heartbeat
 - all of the related containers / pods
 - all of the serverless functions
 - a few things I have not thought of yet, but in summary: All of the logs for my _service_

One thing I don't want is to have this hard coded by a vendor.

Here is how I have done this in the past:
 - Add a field (in ECS I would use `service.id`) and enrich all of my data with a `service.id`.  

The design is more complicated now than in the past when I did this.  Back a few years ago the concatenation of IPADDR and port number was a pretty great unique identifier.  I think we are now in a serverless world, and therefore a world without IPADDRs .

I would love to see us work on a design where we used the enrich processor

**Comment by exekias** [comment]
> Is there any opposition to changing this default?

Not really, but if we want links to work using this info I think we should be more opinionated and *always* send it. The proposed change only enables it through config defaults, for new installations. Short term fix would be either enabling this in the code defaults or using the hostname in the Heartbeat side.

**Comment by DanRoscigno** [comment]
I would do these ~three~ four things:
 - change the default in the Beat configs to fix for new users
 - update the docs to fix for existing users (probably in the Beats docs, and the Kibana docs)
 - discuss this in the monthly Best practices for ingest webinar ([already added to slides](https://docs.google.com/presentation/d/1Ccg6aLCwsKAQIp6h27vQmqX-CwB5xPIC-mKYavcVfO8/edit#slide=id.g5e8e0debf0_0_2436)) to fix for existing users
 - start the discussion on how best to correlate IT Ops data.  I would include services, support, and the Observability folks, I don't think hostname or IPADDR are the right filter

**Comment by andrewvc** [comment]
I really am skeptical of using hostnames extensively. For that to work the hostname of the box would have to align with the URL being monitored. That's a big maybe.

I agree with adding the netinfo stuff by default, that's a clear win (unless there's a reason not to do it), but past that I really think we need to talk about correlation at more of a service level.

Pinging @roncohen , would love his feedback here.

**Comment by tbragin** [comment]
@cyrille-leclerc FYI - a discussion on cross-linking. 

@andrewvc I agree with the tactical answer, but the bigger-picture item may need broader discussion in which I'd like to involve @drewpost and @cyrille-leclerc. Happy to take it offline and update the issue later.

**Comment by andrewvc** [comment]
@tbragin @DanRoscigno  any updates here? If not I'd rather close this issue since there's not a specific action item we can take here.

@jsoriano did merge https://github.com/elastic/beats/pull/16077 , which enables netinfo metadata by default which does help some here.

**Comment by DanRoscigno** [comment]
I will grab a snapshot and test it.

Personally I would love to know that there is a discussion about correlation beyond IPADDR (I think we all agree that IPADDR was a decent MVP, but not the goal, right?).  Should I open a new issue for that and close this one @tbragin ?

**Comment by andrewvc** [comment]
@DanRoscigno do you mind if we close this? 

Feel free to open a new issue for this, but I do think we need a bigger rethink of how this feature works. I'd be curious to see how @cyrille-leclerc thinks we should approach this issue. I'm not sure that looking piecemeal at Uptime is the right approach here.
