### ISSUE TITLE
Netflow protocol version 0 not supported

### ISSUE THREAD

**Issue by w33ha-zxc** [elastic/beats#15532]
- Version: 7.5.1
- Operating System: Ubuntu
- Discuss Forum URL: https://discuss.elastic.co/t/netflow-protocol-version-0-not-supported/214971
- Steps to Reproduce: 
 Config - 

`module: netflow
log:
enabled: true
var:
netflow_host: 192.168.0.154
netflow_port: 2055
protocols: [ v9 ]`

Warning - 
`2020-01-14T15:44:15.507+0530    WARN    [netflow]       netflow/input.go:240    Error parsing NetFlow packet of length 144 from 192.168.1.10:4216: netflow protocol version 0 not supported`

**Comment by adriansr** [comment]
Can you provide a pcap for the traffic arriving at port 2055?

**Comment by w33ha-zxc** [comment]
Uploaded it on packettotal. [PT](https://packettotal.com/app/analysis?id=f61b3f0bf179a91a83b52a229da9f7ef&name=conn)

**Comment by adriansr** [comment]
Unfortunately this is not Netflow, but sFlow (v5), which is a completely different protocol that we don't support yet.

I see some confusion between the two protocols and some posts on the internet related to Fortinet devices seem to use the term Netflow when in fact they refer to sFlow.

Some devices support both, so you might still be able to configure Netflow in your device:

https://www.plixer.com/blog/fortigate-netflow-configuration/
