### ISSUE TITLE
Kubernetes: fix statefulset watcher typo

### ISSUE THREAD

**Issue by nerddelphi** [elastic/beats#15556]
Hi.

Opening a new issue related to this one [13905](https://github.com/elastic/beats/pull/13905), once it didn't fix.

**Comment by nerddelphi** [comment]
I've got the same issue in 7.5.2 as well.

**Comment by odacremolbap** [comment]
@nerddelphi there was still a missing apiGroup migration for `ReplicaSets` which was [recently merged](https://github.com/elastic/beats/pull/16018).

Can you upgrade to 7.6 and re-test?
If there are issues, your config and logs would be much appreciated.

**Comment by luistilingue** [comment]
@odacremolbap It was fixed in 7.6.0, indeed.

Thank you very much.

**Comment by nerddelphi** [comment]
@odacremolbap It was fixed in 7.6.0, indeed.

Thank you very much.
