### ISSUE TITLE
[Metricbeat] IBMMQ module : no data in Kibana

### ISSUE THREAD

**Issue by tvatin** [elastic/beats#15609]
Hi,

I would like to get ibm mq metrics in my Kibana based on metricbeat data.

Here is my metricbeat.yml :

> metricbeat.config.modules:
>   path: ${path.config}/modules.d/*.yml
>   reload.enabled: true
> #-------------------------------- Kibana --------------------------------------
> setup.kibana.host: "kibana:5601"
> setup.kibana.protocol: "http"
> setup.kibana.path: /kibana
> #-------------------------------- Outputs --------------------------------------
> output.elasticsearch:
>   #hosts: ["http://localhost:9200"]
>   hosts: ["${HOST_ELASTICSEARCH}"]
> #-------------------------------- Dashboards -----------------------------------
> #setup.dashboards.enabled: true
> #setup.dashboards.always_kibana: true
> #setup.dashboards.retry.enabled: true
> #-------------------------------- Logging --------------------------------------
> logging.level: warning
> logging.to_files: true
> logging.to_syslog: false
> logging.files:
>   path: /var/log/metricbeat
>   name: metricbeat.log
>   keepfiles: 2
>   permissions: 0644

My ibmmq.yml located in metricbeat/modules.d/ :

> #-------------------------------- Ibmmq Module ---------------------------------
> - module: ibmmq
>   #metricsets: ["qmgr", "queue", "channel"]
>   period: 10s
>   hosts: ["ibmmq:9157"]
>   metrics_path: /metrics
> 
>   #client_id: metricbeat
>   #retries: 3
>   #backoff: 250ms

My docker-compose.yml :
 
> version: '2'
> services:
>   ibmmq:
>     build:
>       context: ./mqm
>       dockerfile: Dockerfile
>     environment:
>       - LICENSE=accept
>       - MQ_QMGR_NAME=MyMQ
>       - MQ_ENABLE_METRICS=true
>       - "WAIT_FOR_HOSTS=es01:9200 kibana:5601"
>       - "HOST_ELASTICSEARCH=es01:9200"
>       - "HOST_KIBANA=kibana:5601"
>     ports: 
>       - 1414:1414
>       - 9443:9443
>       - 9157:9157
>     volumes:
>       - loggingvolume:/mnt/mqm/data/
>     networks:
>       - stack
> 
>   es01:
>     image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
>     container_name: es01
>     environment: 
>       - node.name=es01
>       - discovery.type=single-node
>       - bootstrap.memory_lock=true
>       - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
>     ulimits:
>       memlock:
>         soft: -1
>         hard: -1
>     ports: ['9200:9200']
>     networks: ['stack']
> 
>   kibana:
>     image: docker.elastic.co/kibana/kibana:7.4.0
>     environment:
>       - SERVER_NAME=localhost
>       - ELASTICSEARCH_HOSTS=http://es01:9200
>     container_name: kibana
>     ports: ['5601:5601']
>     networks: ['stack']
>     depends_on: ['logstash']
> 
>   logstash:
>     container_name: logstash
>     build:
>       context: ./logstash
>       dockerfile: Dockerfile
>     networks: ['stack']
>     depends_on: ['es01']
> 
>   metricbeat:
>     #build:
>     #  context: ./metricbeat
>     #  dockerfile: Dockerfile
>     restart: always
>     image: metricbeat
>     container_name: metricbeat
>     command: -e
>     environment:
>       - "WAIT_FOR_HOSTS=es01:9200 kibana:5601"
>       - "HOST_ELASTICSEARCH=es01:9200"
>       - "HOST_KIBANA=kibana:5601"
>     depends_on: ['kibana']
>     networks:
>       - stack
> 
>   filebeat:
>     #build: ./filebeat
>     image: filebeat
>     container_name: filebeat
>     command: -e
>     environment:
>       - "WAIT_FOR_HOSTS=es01:9200 kibana:5601"
>       - "HOST_ELASTICSEARCH=es01:9200"
>       - "HOST_KIBANA=kibana:5601"
>     depends_on: ['kibana']
>     volumes:
>       - loggingvolume:/mnt/mqm/data/
>     networks: ['stack']
> 
> volumes:
>   loggingvolume: {}
>   prometheus_data: {}
>   grafana_data: {}
>     
> networks:
>   stack:
>     driver: bridge

In this configuration, I have 8 containers :
- ibm mq
- kibana
- logstash
- elasticsearch
- grafana
- prometheus
- filebeat
- metricbeat

I'm able to get AMQERR*.json files in my Kibana through filebeat, but the ibm mq metrics gathered by ibmmq metricbeat module seems not working.

Any idea about this ?

Regards

**Comment by jsoriano** [comment]
Hi @tvatin,

What version of metricbeat are you using? IBM MQ module hasn't been released yet.

**Comment by tvatin** [comment]
Hi @jsoriano ,

I'm using Metricbeat v7.5.0.
Do you know if it's going to be released ?

**Comment by jsoriano** [comment]
It was introduced in #15301, it is already merged in master and 7.x branches, but not included in 7.6. So it will be released in principle in 7.7.0.

In the meantime you can try it if you prepare your own build of Metricbeat from the 7.x branch.

I am going to close this issue as we keep github for confirmed bugs and enhancement requests, please use the discuss forum (https://discuss.elastic.co) for further questions. Thanks!
