### ISSUE TITLE
Make Topbeat's proc.cpu.start_time a timestamp

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#1565]
The current value of `proc.cpu.start_time` is not very usable and is possibly broken. I propose that we make this field a timestamp in the index template and format it appropriately. **This will be a breaking change to the data mapping.**

Here's what I see now.

OS|`start_time`
----|---------------
darwin|"Apr30"
linux|"21:25"

**Comment by ruflin** [comment]
Could we get this change in for beta1 as it is breaking?

**Comment by andrewkroh** [comment]
I opened PR #2191 to address this in Metricbeat. I'm not planning on changing this for Topbeat 1.X as this is a breaking change.
