### ISSUE TITLE
Google Cloud Module Additional Field Extraction Request

### ISSUE THREAD

**Issue by danielaugustyn23** [elastic/beats#15651]
The current Google Cloud module doesn't extract "insertId" field from the VPC flow logs in GCP. According to GCP documentation, this is a unique identifier for the log entry. 

_Optional. A unique identifier for the log entry. If you provide a value, then Logging considers other log entries in the same project, with the same timestamp, and with the same insertId to be duplicates which can be removed. If omitted in new log entries, then Logging assigns its own unique identifier. The insertId is also used to order log entries that have the same timestamp value._
ref: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry

Extracting the field with the Google Cloud module would help to find the exact log event in Stackdriver. Right now, it's a bit harder to do it.

**Comment by andrewkroh** [comment]
For the vpcflow dataset I think it would be just one change at:

https://github.com/elastic/beats/blob/9ece104ac263772b12068776fc7accfb699433eb/x-pack/filebeat/module/googlecloud/vpcflow/config/pipeline.js#L60

to add `{from: "json.insertId", to: "label.insert_id"},`.

And it would be a very similar change to the audit and firewall datasets.
