### ISSUE TITLE
how to add path name as event field?

### ISSUE THREAD

**Issue by Tomccat3** [elastic/beats#15669]
Hey 
     I'm new to filebeat, I use filebeat to tail yarn container logs, the directory may like below:
    
    /data/yarn/application_1278356/container_13414_001/stdout
    /data/yarn/application_1278356/container_13414_001/stderr

   I can set the input config like this:

  type: log
  enable: 'true'
  paths: /data/yarn/*/*/*
  
 but i want to know which file each event from, can i add file path as a field? if so, how to do this?

**Comment by jsoriano** [comment]
Hey @Tomccat3, welcome to beats :slightly_smiling_face: 

We prefer to use the discuss forum in https://discuss.elastic.co for this kind of questions, and leave Github for confirmed issues and enhancement requests.

In any case, regarding your question, it can have an quick answer. The file path should be in the generated events, in the `log.source.path` fields, is it not there in your case?

**Comment by Tomccat3** [comment]
Hey@jsoriano , I'm sorry for the wrong place.

Thank you for your reply.
