### ISSUE TITLE
[Winlogbeat] Sysmon Module - Missing DNS Status Codes

### ISSUE THREAD

**Issue by nicpenning** [elastic/beats#15685]
For confirmed bugs, please report:
- Version: 7.4.0 (WLB)
- Operating System: Windows 10 
- Discuss Forum URL: https://discuss.elastic.co/t/sysmon-dns-query-missing-status-codes/213396/3
- Steps to Reproduce: With SysMon on a Windows 10 device run this in a command prompt:
ping www.google,com

Look at the logs that get ingested into Elastic or see the JSON output of WLB and see that event code 9560 is stored in the symon.dns.status field.

Similar behavior exists for these event codes as well, but I do not know how to test for them at this time:

1460
9560
123
1223
4312
10054

More rare ones that trip:
14
1214
8
10060
13
10055
5

This is per request by @andrewkroh.

Thank you!

**Comment by andrewkroh** [comment]
I opened a fix for this issue in #16040.

**Comment by nicpenning** [comment]
Thanks for addressing and fixing these @andrewkroh . I look forward to the update, whenever that may come. I will follow up after we apply the new SysMon .js module when it has been released.
