### ISSUE TITLE
[Agent] Provide sane defaults for index name

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#15691]
Index name should have a default format of `{type}-{namespace}-{dataset}`
If any of these is missing use a default matching:

| Key | Value
| ------------- |:-------------:| 
| type: | `logs` for filebeat, `metrics` for metricbeat |
| namespace: | default|
| dataset: | generic |

Inject this generated name into respective beats

Requires: #15690

**Comment by ph** [comment]
I've missed that issue somehow.

**Comment by neptunian** [comment]
FYI, the docs were changed so that the naming should now be `{type}-{dataset}-{namespace}` https://github.com/elastic/kibana/blob/feature-ingest/docs/epm/index.asciidoc
