### ISSUE TITLE
Beats DNS processor: limit reverse to internal networks

### ISSUE THREAD

**Issue by fpompermaier** [elastic/beats#15735]
**Describe the enhancement:**
Il would be VERY useful to limit DNS (reverse) resolution to internal networks

**Comment by andresrc** [comment]
Hi! Are you using some specific module which performs the reverse resolution?

Thanks

**Comment by fpompermaier** [comment]
I usually want to get the host names from IP addresses. For external ones I can use the geoip processor so I need to use internal DNS servers only for internal IPs..however to achieve that I need to attach some tag using the CIDR filter (like public_ip or private_ip) and then apply DNS ressolution only to tag=private_ip..this is very annoyinh

**Comment by urso** [comment]
Hi,

I think the questions was more about your Beats configuration. I presume you use the [`dns` process](https://www.elastic.co/guide/en/beats/filebeat/current/processor-dns.html#processor-dns)? Do you use it with conditionals?

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
