### ISSUE TITLE
[Metricbeat] Add container metrics to the Azure module

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#15751]
Add support of the following namespaces in Azure Monitor that cover container metrics:

**Namespace**: Microsoft.ContainerInstance/containerGroups
**Namespace**: Microsoft.ContainerRegistry/registries
**Namespace**: Microsoft.ContainerService/managedClusters

Reference: https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftcontainerinstancecontainergroups 
## Modules

For a metricset to go GA, the following criterias should be met:

* [ ] Supported versions are documented
* [ ] Supported operating systems are documented (if applicable)
* [ ] Integration tests exist
* [ ] System tests exist
* [ ] Automated checks that all fields are documented
* [ ] Documentation
* [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] Dashboards exists (if applicable)
* [ ] Kibana Home Tutorial (if applicable)
  * Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).
* [ ] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [ ] Test environment in Docker exist for integration tests

**Comment by narph** [comment]
container metricsets have been added together with dashboards and documentation. Can we close this issue @sorantis ?
