### ISSUE TITLE
[Metricbeat] Add database metrics to the Azure module

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#15758]
Azure has a multitude of SQL and NoSQL database services. It is important to have capabilities in the Azure module that cover these services. We start by adding support of the following namespaces in Azure Monitor covering Cosmos DB a multi-model NoSQL database service:

**Namespace**: Microsoft.DocumentDB/databaseAccounts

Reference: https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftdocumentdbdatabaseaccounts

## Modules

For a metricset to go GA, the following criteria should be met:

* [x] Supported versions are documented
* [x] Supported operating systems are documented (if applicable)
* [x] Integration tests exist
* [x] System tests exist
* [x] Automated checks that all fields are documented
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] Dashboards exists (if applicable)
* [ ] Kibana Home Tutorial (if applicable)
  * Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).
* [x] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [] Test environment in Docker exist for integration tests

**Comment by blookot** [comment]
Hi
I'm not seing it in https://www.elastic.co/guide/en/beats/metricbeat/7.7/metricbeat-module-azure.html#_metricsets_9
Am I missing it?
thanks in advance

**Comment by sorantis** [comment]
https://www.elastic.co/guide/en/beats/metricbeat/7.7/metricbeat-metricset-azure-database_account.html

**Comment by andresrc** [comment]
@narph is there anything missing to close this issue?

**Comment by narph** [comment]
I do not think anything is missing, we have a separate issue to enrich this metricset's dashboards https://github.com/elastic/beats/issues/17929.

**Comment by blookot** [comment]
sorry i missed it @sorantis 
thanks for your answer
