### ISSUE TITLE
Provide a jmxbeat

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#1580]
This is an enhancement request for a jmxbeat (or potentially a jmx module as part of a general collectbeat).  The idea is to be able to ship metrics/info available via JMX to ES/LS from beats.  One use case is the output from dumpAllThreads method.   There are likely other use cases like the ones discussed in this previous ticket (https://github.com/elastic/beats/pull/1088).

**Comment by navya35** [comment]
Hello,

I want to retrieve JMX information via metricbeat but I saw that there is no module to do this for the moment.
But I see that here https://github.com/vas78/beats/tree/master/metricbeat/module, a jmx module has been developped.
Do you inlclude this module in the future in metricbeat or not ?
Is there another solution in current beats to retrieve JMX metrics ?

Thanks

**Comment by ruflin** [comment]
@navneet83 I was so far not aware of this module. JMX is definitively on our todo list. Perhaps you can make an intro to @vas78 ? I'm more then happy to have a conversation with him to see if we could add this as an officially supported module.

**Comment by navya35** [comment]
Hello,

We compile the code of @vas78 on our project and we use it now to retrieve JMX informations of Spark and Cassandra.
It works fine for the moment, we have to test with our clusters.

Thanks @vas78

**Comment by ruflin** [comment]
@navya35 You will be happy to know that there is some work going on in https://github.com/elastic/beats/pull/3051

**Comment by laurent-malvert** [comment]
@ppf2 I think this can be closed, since there's now the Jolokia Module (https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-jolokia.html) providing a jmx implementation (https://github.com/elastic/beats/blob/master/metricbeat/module/jolokia/jmx/jmx.go). Or are there limitations to this solution that make it not suitable for your desired scenarios?

**Comment by ppf2** [comment]
We can probably close this one, the limitation of not able to use the proxy mode for jolokia is filed as https://github.com/elastic/beats/issues/4421, thx
