### ISSUE TITLE
[Metricbeat] Googlecloud: storage metricset

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#15810]
# Metricbeat Module / Dataset release checklist

This checklist is intended for Devs which create or update a module to make sure modules are consistent.

## Modules

For a metricset to go GA, the following criterias should be met:

* [x] Supported versions are documented
* [ ] ~~Supported operating systems are documented (if applicable)~~
* [x] Integration tests exist
* [x] System tests exist
* [x] Automated checks that all fields are documented
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] Dashboards exists (if applicable)
* [ ] Kibana Home Tutorial (if applicable)
  * Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).

## Metricbeat module

* [ ] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [ ] Test environment in Docker exist for integration tests

**Comment by kaiyan-sheng** [comment]
Added dashboard for storage metricset in https://github.com/elastic/beats/pull/18172.

**Comment by masci** [comment]
Superseded by https://github.com/elastic/integrations/issues/490
