### ISSUE TITLE
[Heartbeat] Support HTTP Digest auth.

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#15837]
**Describe the enhancement:**

It looks like go's HTTP client doesn't support digest, but [there is a proposal here](https://github.com/golang/go/issues/29409). So, we'd have to do a custom implementation. This originated with [this discuss post](https://discuss.elastic.co/t/type-http-with-auth-digest/216482).

**Describe a specific use case for the enhancement or feature:**

HTTP digest is an old insecure standard, using a long deprecated hashing algorithm (MD5), and provides few of the protections TLS/SSL provide.

Users may be forced to use it to monitor legacy software however, so it wouldn't be bad to support.

**Comment by hendry-lim** [comment]
+1 for HTTP Digest auth support. We have a client's requirement to monitor JBoss through its management URL/API, but it is configured with Digest auth by default.

**Comment by cskowronnek** [comment]
+1 we'd need this too

**Comment by andrewvc** [comment]
One thought is as we roll out our synthetics framework, based on node.js, you'll have access to a full JS environment, letting you do weird things like digest auth. It's a bit early (and we're focusing on browsers at the moment) but it makes sense as a path to me. See https://www.elastic.co/what-is/synthetic-monitoring .

**Comment by beirtipol** [comment]
I'll throw my hat in the ring for this too. Again, need to access JBoss stats and only Digest auth is supported. I'll probably set up a script to curl and log the data I need on a timer and then scrape the json with filebeat

**Comment by beirtipol** [comment]
👍

**Comment by andrewvc** [comment]
I'm going to close this issue in favor of https://github.com/elastic/synthetics/issues/137, which will almost certainly be the way this is implemented in the future. Please feel free to follow that issue!
