### ISSUE TITLE
[Metricbeat] oracle: to change the sysdba host parameter to be optional

### ISSUE THREAD

**Issue by hendry-lim** [elastic/beats#15846]
**Describe the enhancement:**
The `sysdba` flag host parameter in the oracle module for Metricbeat is a required parameter and has to have a value of 1. However, in real case scenario, the `sysdba` flag is not required to be able to retrieve all the required metrics from the Oracle database.

Discuss URL: [https://discuss.elastic.co/t/metricbeat-oracle-module/215097](url)

**Describe a specific use case for the enhancement or feature:**
User access as a `sysdba` is usually not allowed regardless of environment and be it through local or remote access.

**Comment by wolframhaussig** [comment]
I would like to see this fixed too: According to the principle of least privileges we are not allowed to give a user DBA access if it needs only a subset of the privileges. In my opinion this is not a small enhancement - it is a security relevant feature!
