### ISSUE TITLE
Missing fields in Topbeats?

### ISSUE THREAD

**Issue by githubmui** [elastic/beats#1584]
Hi,
in my usecases I am often missing following two fields:

1) Number of cpus: Since user_p can raise to a maximum of 100%*(Number of CPUs), I want to show these important limit to the users. If "cpu_per_core" is configured to false (to ensure a compact data file), it would be great to have the "Number of CPUs" always in the "cpu" record.

2) If process is configured to true, I don't know how to calculate the "system_p" information for each process line. It would be helpful to have this value also in the "cpu" record beside the already existing "user_p" value?

What do you think about that?

**Comment by githubmui** [comment]
3) A further issue is to provide the fields "load1", "load5" and "load15" also on Windows. Would be really great to compare windows and linux machines in one kibana diagram.

**Comment by ruflin** [comment]
1) For metricbeat I seperated cpu and core stats into two separate metricsets (https://github.com/elastic/beats/pull/1596). I like the idea of adding the total number of cores to the metricset.
2) Can you elaborate a little bit more here?
3) Agree. Contributions are welcome ;-)

**Comment by ruflin** [comment]
Closing this issue as it was initially opened for Topbeat and Topbeat was superset by Metricbeat. For missing features in Metricbeat please open a new issue.
