### ISSUE TITLE
Filebeat to redis using multiple keys for different document types

### ISSUE THREAD

**Issue by tsegal** [elastic/beats#1587]
Hello,

This issue is raised following my question at:
https://discuss.elastic.co/t/filebeat-to-redis-using-multiple-keys-for-different-document-types/49526:

I am using filebeat to ship logs from a centralized log server. In the prospectors section, I defined multiple files, each with its own type, for example:

paths:

```
-/tmp/manager.log
 input_type:log
 document_type: manager.log

 -/tmp/worker.log
 input_type:log
 document_type: worker.log
```

in the output part, I defined a redis server. I leave the default index "filebeat". This can be configurable but my issue is it's global for all types, so I end up having redis with a single key storing all documents. This is an issue if I want to replay just a single type of log into the system while it's working (hot) because I don't have a proper way of removing only the keys for that log type.

Best case scenario - can I define dynamically a key by document type?
A good solution as well - can I define explicitly a key per type? or path? or something else?

**Comment by ruflin** [comment]
This is currently not possible. Currently the best way to do this kind of stuff is sending data to Logstash and do the routing there.

**Comment by tsegal** [comment]
Thanks ruflin for your prompt reply. This takes a bit off of the advantage of filebeat, being lightweight and all. Do you happen to know if this is in the road map or not?

**Comment by ruflin** [comment]
Outputs and possible configuration are under discussion. This specific feature is not on the roadmap but we will add it to our discussion.

**Comment by urso** [comment]
Closing, as dynamic redis key support is available for a while.
