### ISSUE TITLE
Add more keystore backends to support Functionbeat cloud providers

### ISSUE THREAD

**Issue by kvch** [elastic/beats#15879]
Right now the keystore only supports file backend. However, this is not suited to run on serverless environments where less restrictive permissions are required to read a file.

Possible backends for providers:
- AWS: https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html
- GCP: Secret manager (https://cloud.google.com/secret-manager/docs)
- Both: HashiCorp Vault

In the meantime, users should use environment variables to pass secrets to Functionbeat.

Original issue: https://github.com/elastic/beats/issues/15808

**Comment by exekias** [comment]
ping @kaiyan-sheng @ChrsMark for awareness

**Comment by ChrsMark** [comment]
Maybe we should add `Kubernetes` secrets into the list of possible backends? related to https://github.com/elastic/beats/issues/8847

**Comment by kaiyan-sheng** [comment]
For AWS, IAM roles can also be used for authentication without requiring a file at the backend: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-api.html. Also, https://github.com/elastic/beats/issues/12464 might be related too.

**Comment by toby-lego** [comment]
This is still an issue. We're trying to use functionbeats but don't want to put secure credentials in environment variables. Any integration with AWS Secrets Manager or System Parameter would be very useful.
