### ISSUE TITLE
[Auditbeat] system/package dataset updates too often

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#15877]
**Describe the enhancement:**

The `system/package` dataset fetches the list of installed packages every 10s by default (`system.period`), in order to check for newly installed packages. In some cases, for example rpm systems with a lot of installed packages, this frequent check causes a lot of unnecessary CPU usage by Auditbeat.

The problem with `system.period` is that most system datasets rely on this period to poll for changes, so setting it to a higher value can negatively impact other datasets. Adding a dedicated setting, like `system.package.poll.period`, similar to `system.package.state.period`, will be a better solution imho.

Alternatively, the time it takes to fetch the list of packages could be measured and the poll interval adjusted within some bounds (10s ... 5min) to ensure that only a minimum percentage of time is spent checking for new packages.

As an example, right now Auditbeat peaks to 50% CPU for ~1s every 10s, in an rpm system with ~800 packages installed, which some users find unnacceptable.

**Comment by rvillablanca** [comment]
Hi @adriansr, I would like to help in this :dancer:

**Comment by rvillablanca** [comment]
If I understood we need to add almost the same validation as for the `Metricset.reportState` but this time for `Metricset.reportChanges` like this:

https://github.com/elastic/beats/blob/2ff1678aacf16c848814401fb2fbe2c111fd7f2d/x-pack/auditbeat/module/system/package/package.go#L233

But keeping it in separated config options

**Comment by adriansr** [comment]
That's correct, @rvillablanca 

Thanks for taking this 👏

**Comment by andrewkroh** [comment]
Would a possible solution be to separate out the package dataset in the configuration similar to how Metricbeat does for the system/filesystem datatset that requires a different polling interval than other datasets. For example in the auditbeat.yml file:

```yaml
auditbeat.modules:
- module: system
  datasets: [package]
  period: 30m
- module: system
  datasets: [host, login, process, socket, user]
```

**Comment by rvillablanca** [comment]
Hi @andrewkroh. What I did was to copy the way that datasets override `state.period` but this time for the polling of `package` dataset.

I thing your suggestion is ok but viewing the code is not the way it was done, because for several datasets there is a `ìf` condition asking if an update is needed, for example for `user` dataset.

https://github.com/elastic/beats/blob/83cf89454779a0d024d699ca69170ff21fdbe3de/x-pack/auditbeat/module/system/user/user.go#L272

That's why filesets can override `state.period` for example.

```yml
# How often datasets send state updates with the
  # current state of the system (e.g. all currently
  # running processes, all open sockets).
  state.period: 12h

  # The state.period can be overridden for any dataset.
  # host.state.period: 12h
  # package.state.period: 12h
  # package.poll.period: 1m
  # process.state.period: 12h
  # socket.state.period: 12h
  # user.state.period: 12h
```

So your suggestion is more elegant I think but it requires more refactor. Of course all I said could be a bit wrong because my knowledge of `elastic/beats` is limited since I'm new into this :sweat_smile:

**Comment by adriansr** [comment]
You're completely right @andrewkroh, it's much easier that way.

@rvillablanca this would only require to test if the above configuration works in Auditbeat and if it does, update the generated `auditbeat.yml` / `auditbeat.reference.yml`

**Comment by rvillablanca** [comment]
I works perfectly, I don't have a linux based in redhat so I replaced `package` dataset by `user` dataset and it worked, the config I used was:

```yaml
auditbeat.modules:

- module: system
  datasets: [user]
  state.period: 1s
  period: 10s

- module: system
  datasets: [host]
  state.period: 1s
  period: 2s
```

The two datasets started correctly and for every 5 logged events of `host` dataset there was one of `user` dataset as expected.

**Comment by rvillablanca** [comment]
I've updated the configuration for both files :+1: @adriansr
