### ISSUE TITLE
[FILEBEAT] Problem with ActiveMq Module

### ISSUE THREAD

**Issue by geoffreydjof** [elastic/beats#15907]
Hey !

Sorry for bothering you.
I'm quite new in the use of Filebeat but I wanted it to run on a server where ActiveMq is installed.

I then installed Filebeat (6.3.0 OSS) and get the ActiveMq module of Activemq. When I enable it and launch Filebeat, I got that error :

`2020-01-28T17:17:47.976+0100    DEBUG   [modules]       fileset/pipelines.go:28 Required processors: []
2020-01-28T17:17:47.976+0100    ERROR   fileset/factory.go:97   Error loading pipeline: Error getting pipeline for fileset activemq/log: Error JSON decoding the pipeline file: ingest/pipeline.yml: invalid character '#' looking for beginning of value
`

Which I don't really understand cause the doc says it is possible to have a pipeline in YAML.
An anyway, I tried with a JSON but of crouse, I got that mistake 
`2020-01-28T17:21:41.392+0100    ERROR   fileset/factory.go:97   Error loading pipeline: Error getting pipeline for fileset activemq/log: Error reading pipeline file ingest/pipeline.yml: open /appl/wasbivh1/filebeat/share/module/activemq/log/ingest/pipeline.yml: no such file or directory
`

Could anyone help me please ? 

Regards,

Jeffrey

**Comment by kaiyan-sheng** [comment]
Hi @geoffreydjof, thanks for creating this. But we would kindly ask you to post all questions and issues on https://discuss.elastic.co/c/beats/filebeat before opening a Github Issue. Your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue or open a new one with more details. Thanks in advance!

**Comment by geoffreydjof** [comment]
Hi @kaiyan-sheng 

Sorry for getting in the wrong place.

Regards

**Comment by kaiyan-sheng** [comment]
@geoffreydjof Not a problem 😄 Thanks for reaching out!!
