### ISSUE TITLE
Filebeat - Suricata - Cannot write to a field alias [suricata.eve.flow.bytes_toserver]

### ISSUE THREAD

**Issue by MakoWish** [elastic/beats#15922]
I am sending Filebeat through Logstash (primarily for the sake of GeoLocation data and normalization of host.name, etc. fields). I am getting quite a lot of error messages for Logstash unable to index an event due being unable to write to an alias field. 

- Elasticsearch Version: 7.5.2
- Logstash Version: 7.5.2
- Operating System: Ubuntu 19.10
- Steps to Reproduce: Enable Filebeat Suricata module, send Filebeat output to Logstash, Logstash output to Elasticsearch. Errors are seen in journal logs. 

```
Jan 28 19:27:18 <HostName> logstash[147366]: [2020-01-28T19:27:18,421][WARN ][logstash.outputs.elasticsearch][main] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"filebeat-7.5.2", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x7f679338>], :response=>{"index"=>{"_index"=>"filebeat-7.5.2-2020.01.23-000001", "_type"=>"_doc", "_id"=>"m_FW728B2M5hYr_AwwZz", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"Cannot write to a field alias [suricata.eve.flow.bytes_toserver]."}}}}}
Jan 28 19:27:40 <HostName> logstash[147366]: [2020-01-28T19:27:40,660][WARN ][logstash.outputs.elasticsearch][main] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"filebeat-7.5.2", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x6b06213b>], :response=>{"index"=>{"_index"=>"filebeat-7.5.2-2020.01.23-000001", "_type"=>"_doc", "_id"=>"bfFX728B2M5hYr_AGhJg", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"Cannot write to a field alias [suricata.eve.flow.bytes_toserver]."}}}}}
Jan 28 19:27:48 <HostName> logstash[147366]: [2020-01-28T19:27:48,634][WARN ][logstash.outputs.elasticsearch][main] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"filebeat-7.5.2", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x322e58a5>], :response=>{"index"=>{"_index"=>"filebeat-7.5.2-2020.01.23-000001", "_type"=>"_doc", "_id"=>"xPFX728B2M5hYr_AORRR", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"Cannot write to a field alias [suricata.eve.flow.bytes_toserver]."}}}}}
Jan 28 19:27:48 <HostName> logstash[147366]: [2020-01-28T19:27:48,667][WARN ][logstash.outputs.elasticsearch][main] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"filebeat-7.5.2", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x493e1e7c>], :response=>{"index"=>{"_index"=>"filebeat-7.5.2-2020.01.23-000001", "_type"=>"_doc", "_id"=>"QfFX728B2M5hYr_AORWn", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"Cannot write to a field alias [suricata.eve.flow.bytes_toserver]."}}}}}
Jan 28 19:27:53 <HostName> logstash[147366]: [2020-01-28T19:27:53,748][WARN ][logstash.outputs.elasticsearch][main] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"filebeat-7.5.2", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x1e7d79cb>], :response=>{"index"=>{"_index"=>"filebeat-7.5.2-2020.01.23-000001", "_type"=>"_doc", "_id"=>"tPFX728B2M5hYr_ATRZl", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"Cannot write to a field alias [suricata.eve.flow.bytes_toserver]."}}}}}
Jan 28 19:28:07 <HostName> logstash[147366]: [2020-01-28T19:28:07,488][WARN ][logstash.outputs.elasticsearch][main] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"filebeat-7.5.2", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x5f30160b>], :response=>{"index"=>{"_index"=>"filebeat-7.5.2-2020.01.23-000001", "_type"=>"_doc", "_id"=>"xvFX728B2M5hYr_AgxkD", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"Cannot write to a field alias [suricata.eve.flow.bytes_toserver]."}}}}}
```

**Comment by MakoWish** [comment]
UPDATE:

There are additional fields giving the same error. There may be even more, but these are all I am seeing at the moment. 

suricata.eve.flow.pkts_toclient
suricata.eve.flow.pkts_toserver
suricata.eve.app_proto

**Comment by andrewkroh** [comment]
This does not sound like a Filebeat bug. It's probably an issue with your install or LS setup.

If I look at the Filebeat Suricata module it has an Ingest Node pipeline that renames the field in question so it should not be writing to `suricata.eve.flow.bytes_toserver`.

https://github.com/elastic/beats/blob/v7.5.2/x-pack/filebeat/module/suricata/eve/ingest/pipeline.yml#L96-L99

Check that you have LS configured to set the `pipeline` option in the elasticsearch output. See:
https://www.elastic.co/guide/en/logstash/7.6/use-ingest-pipelines.html

**Comment by gyterpena** [comment]
Getting same errors, but only from time to time(eg not on all suricata logs), logstash does send to pipeline. I believe that type is wrong, eg somehow field ends up not matching date type. 

2020-11-24T14:48:40,077][WARN ][logstash.outputs.elasticsearch][default-new][out_beats_pipeline_suri] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logs-suri-filebeat", :routing=>nil, :_type=>"_doc", :pipeline=>"filebeat-7.10.0-suricata-eve-pipeline"}, #<LogStash::Event:0x47989265>], :response=>{"index"=>{"_index"=>"filebeat-suri-000000", "_type"=>"_doc", "_id"=>"Dgy6-nUBgG8HLDtPV6Ef", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"Cannot write to a field alias [suricata.eve.flow.start]."}}}}}

**Comment by masual** [comment]
Same problem hear, Elastic, Kibana and Filebeat versión 7.10.2 with the Suricta Filebeat Module enabled, getting:

`"reason":"Cannot write to a field alias [suricata.eve.http.hostname]."}}`
