### ISSUE TITLE
Metricbeat cannot read beat expose metric via npipe

### ISSUE THREAD

**Issue by ph** [elastic/beats#15938]
When doing the QA for the 7.6 releases we discovered an issue with the Metricbeat beat module. When the monitoring information of beat was exposed via windows named pipe. Metricbeat refused to connect and collect metrics.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version:  7.6
- Operating System: Windows

cc @fearful-symmetry

**Comment by fearful-symmetry** [comment]
So we're not calling this a blocker? Do we have a workaround?

**Comment by ph** [comment]
I've marked it as a blocker, starting to work on it. I don't expect the fix to be too long. I wam trying to get a workaround with that.

**Comment by ph** [comment]
Note, that It might not be considered a blocker, because collecting data via HTTP still work.

**Comment by ph** [comment]
@andresrc @urso Just you keep you in the loop.
