### ISSUE TITLE
Add FAQ topic that explains how to get Filebeat to re-process log files

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#1595]
Add "how do I get Filebeat to re-process log files" to the FAQ. See related discussion in the forums here: https://discuss.elastic.co/t/how-do-i-reset-the-file-pointer-in-filebeats/49440

**Comment by ruflin** [comment]
@dedemorton We should be careful with the word "parse" as Filebeat does not parse log lines.

**Comment by dedemorton** [comment]
Closing in favor of tracking this issue in https://github.com/elastic/beats/issues/2482

**Comment by chrisribe** [comment]
Ehuuu anyone care to answer the question ???
Read the documentation, I don't get the clear_* options and how to use them in my configuration file.

Please help.
Chris

**Comment by dedemorton** [comment]
@chrisribe Please post any questions to the [Filebeat discussion forum](https://discuss.elastic.co/c/beats/filebeat), not Github. 

To be honest it's not clear to me what you're trying to do. If you want to get Filebeat to reprocess all your log files, just delete the registry file in the data folder. See [Directory layout ](https://www.elastic.co/guide/en/beats/filebeat/current/directory-layout.html) if you need help finding the registry file. If you need to know something else, post a question to the discussion forum.

**Comment by chrisribe** [comment]
Hi dedemotron,

Sorry for posting on a closed topic.
My question was exactly this post title and you answered perfectly, thanks.

After searching google this post was the best result I could find. I did not see the filebeat forum. The docs are clearly missing this detail, it's something any dev will need to do after testing filebeat.

Thanks
Chris
