### ISSUE TITLE
Beats package Job is broken

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/beats#15953]
Since Jan 14 the Beats package job is failing with the following errors

https://beats-ci.elastic.co/job/elastic+beats+master+package/

Linux job

```
10:02:52 2020/01/14 08:02:52 Found Elastic Beats dir at /var/lib/jenkins/workspace/elastic+beats+master+multijob-package-linux/src/github.com/elastic/beats
10:15:50 Error: runtime error: invalid memory address or nil pointer dereference
10:15:50 make[1]: Leaving directory `/var/lib/jenkins/workspace/elastic+beats+master+multijob-package-linux/src/github.com/elastic/beats/x-pack/dockerlogbeat'
10:15:50 make[1]: *** [release] Error 1
10:15:50 make: *** [release] Error 1
```

Mac OS X job (it started failed before Dec 30)
```
16:50:51 Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
16:50:51 package ran for 6.122117456s
16:50:51 Error: docker is not available: running "docker info -f {{ json .}}" failed with exit code 1
16:50:51 docker is not available: running "docker info -f {{ json .}}" failed with exit code 1
16:50:51 make[1]: *** [release] Error 1
16:50:51 make: *** [release] Error 1
```

**Comment by v1v** [comment]
## Linux job

is now back to business -> https://beats-ci.elastic.co/job/elastic+beats+master+multijob-package-linux/

**Comment by v1v** [comment]
CI Darwin worker is now back in business, let's see if [build](https://beats-ci.elastic.co/job/elastic+beats+master+multijob-package-darwin/348/) works as expected

**Comment by v1v** [comment]
No more failures with the docker socket in Darwin but some other errors. So I'll close this ticket and raise a new one to track the new changes to ensure we do keep those build errors in different issues that are isolated.
