### ISSUE TITLE
Port notice generator to Golang

### ISSUE THREAD

**Issue by kvch** [elastic/beats#15981]
Currently, the NOTICE.txt file is generated using the Python script `dev-tools/generate_notice.py`. To integrate better with `mage` and to utilize Golang specific tools, we should port the script to Golang.

**Comment by jsoriano** [comment]
When implementing this we have to take into account that `dev-tools/generate_notice.py --csv` is used by internal release processes.

**Comment by kvch** [comment]
We should evaluate if we can use this tool instead of creating our own: https://github.com/elastic/cloud-on-k8s/tree/master/hack/licence-detector

**Comment by kvch** [comment]
Closing as have already adopted https://github.com/elastic/go-licence-detector in #18655
