### ISSUE TITLE
[Filebeat] Add module for Checkpoint Firewall

### ISSUE THREAD

**Issue by leehinman** [elastic/beats#16041]
Most likely using Checkpoint Log Exporter and CEF format

Checkpoint can export logs via CEF using their "Log Exporter".  I found a list of mappings:
https://community.checkpoint.com/t5/Logging-and-Reporting/Log-Exporter-CEF-Field-Mappings/td-p/41060

Info on Log Exporter:
https://community.checkpoint.com/t5/Logging-and-Reporting/Log-Exporter-guide/td-p/9035

https://sc1.checkpoint.com/documents/R80.20.M2/WebAdminGuides/EN/CP_R80.20_M2_LoggingAndMonitoring_AdminGuide/html_frameset.htm?topic=documents/R80.20.M2/WebAdminGuides/EN/CP_R80.20_M2_LoggingAndMonitoring_AdminGuide/203039

**Comment by hazcod** [comment]
@leehinman Since not yet supported by beats, how are you currently shipping SIEM events?

**Comment by hazcod** [comment]
Thank you @adriansr !

**Comment by adriansr** [comment]
This was closed after merging CEF support for Check Point but shouldn't have been closed as this is just support for the CEF output but not for Check Point logs in general.

**Comment by hazcod** [comment]
@adriansr: what’s the difference here?

**Comment by adriansr** [comment]
Check Point can generate logs in CEF format, so we updated the cef module to understand the custom fields it adds. But also has it's own log format which is the default and provides more information than CEF. We'll add a new module to support those logs.
