### ISSUE TITLE
`add_metadata` setting in Kubernetes metricbeat module is not documented

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#16047]
The `add_metadata` setting is shown in the [configuration example](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-kubernetes.html#_example_configuration_25) for the Kubernetes module, but is not documented. Users are confused about how/whether this setting differs from the add_kubernetes_metadata processor.

This setting needs to be added to the the [Kubernetes module docs](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-kubernetes.html#metricbeat-module-kubernetes) under a section called "Module-specific configuration notes"

See https://github.com/elastic/beats/pull/7470 (original PR that added the setting).

**Comment by romain-chanu** [comment]
Clarifications should be added regarding the differences between `add_metadata` and `add_kubernetes_metadata` processor. According to https://github.com/elastic/beats/pull/7470, it is stated that the "enricher" for `add_metadata` behaves the same way as the `add_kubernetes_metadata` processor. `add_metadata` is also enabled by default.

According to this documentation, if users want to populate the `Kubernetes` view in the Metrics app with metrics data, they must enable the `add_kubernetes_metadata` processor. This sounds rather confusing and contradictory with the above statement related to `add_metadata`.

**Comment by dedemorton** [comment]
@exekias Can you add clarity here? What recommendations should we make in the docs wrt these settings?

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
