### ISSUE TITLE
Kubernetes autodiscover: add/restructure variables from resources

### ISSUE THREAD

**Issue by odacremolbap** [elastic/beats#16059]
Recently autodiscover for kubernetes was refactored to allow different resources to be used:
https://github.com/elastic/beats/pull/14738

Node identification (stored at the `host` variable) uses the external IP, and if not present internal IP. There are also more addresses present at the structure which we should consider using

On a related matter autodiscover for pods and services might also need to be expanded to address exposed ports by number or name, use CNAMES when availables, considering all kinds of services, and headless services to pod scenarios.
https://github.com/elastic/beats/issues/15796

Not requested (yet) but probably something that we will need to consider to keep variables for autodiscover homogeneus are ingresses, since they share most of the aforementioned variables.

**Comment by arthurh4** [comment]
Hello, @odacremolbap 

I've been looking into heartbeat for kubernetes and it's really amazing. Using it we can let our devs setup heartbeat monitors directly from CICD pipeline through YAML labels. We would like to also add the feature for external services like ExternalName services (CNAME). it would be very very appreciated ! 

Looking at. the code it should not be that complicated:

```
	host := svc.Spec.ClusterIP.   
        // If a service doesn't have an IP then dont monitor it. 
	if host == "" && flag != "stop" {. 
		return. 
	}
```

We mostly need to add a handler for externalIP:

>NAME           TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)          AGE
google-com     ExternalName   <none>          google.com      80/TCP           106m

Do you have any plan on implemtenting this ? Thanks a lot
