### ISSUE TITLE
Redis output multiple password support.

### ISSUE THREAD

**Issue by urso** [elastic/beats#16058]
The redis output allows the user to configure multiple redis hosts. Beats will use the list of hosts for load-balancing. The redis output allows users to configure an username and password, but this requires users to setup each redis host with the same set of credentials.

Similar to other outputs and modules in metricbeat the username and password should be configurable with per host like this (proposal by @andrewkroh https://github.com/elastic/beats/pull/5891#issuecomment-352827788):

```
hosts:
- user:pass@remote:6379
- localhost:6379
username: default
password: secret
```

**Comment by rvillablanca** [comment]
I know that redis only authenticates with password and username is not required, so in the example of the configuration the key `username` would be invalid right ?

Maybe a valid configuration could be

```yaml
hosts:
- :pass@remote:6379
- localhost:6379
password: secret
```
But not sure if for case of `remote` host is a valid url

**Comment by urso** [comment]
Right, it is more like a shared secret, and less a full authentication scheme. We can easily remove the `:` prefix as well.

For reference (Redis Security docs): https://redis.io/topics/security
