### ISSUE TITLE
Metricbeat: create list_windows.go for windows modules in order to avoid cross-compiling issues

### ISSUE THREAD

**Issue by narph** [elastic/beats#16102]
At the moment, the windows modules are listed in `list_common.go` but cross compiling can get  tricky:

```
go build github.com/elastic/beats/metricbeat/module/iis/application_pool: build constraints exclude all Go files in /mnt/.../elastic/beats/metricbeat/module/iis/application_pool
go build github.com/elastic/beats/metricbeat/module/iis/website: build constraints exclude all Go files in /mnt/.../elastic/beats/metricbeat/module/iis/website
Error: error getting default metricsets: Error running subcommand to get metricsets: running "go run /mnt.../elastic/beats/metricbeat/scripts/msetlists/cmd/main.go" failed with exit code 1
``` 

Workaround at the moment is creating an empty go file `doc.go`
Should follow the same steps as list_docker.go and update ` metricbeat/scripts/mage/fields.go`

**Comment by BananaEgg** [comment]
How does list_windows.go work?
what do you put in it?
what are the steps for compiling?
I'm trying to compile on Linux for windows using a build.hs file for cross compiling that contains the following commands:

#!/bin/bash

mage collectAll
mage build
go build -o metricbeat_0.0.9 main.go
GOOS=windows GOARCH=amd64 go build -o metricbeat_0.0.9.exe main.go

 I'm getting an error 
exit status 2
Error: error getting default metricsets: Error running subcommand to get metricsets: running "go run /home/reuven/go/src/github.com/elastic/beats/metricbeat/scripts/msetlists/cmd/main.go" failed with exit code 1

**Comment by BananaEgg** [comment]
> Hi! We just realized that we haven't looked into this issue in a while. We're sorry!
> 
> We're labeling this issue as `Stale` to make it hit our filters and make sure we get back to it as soon as possible. In the meantime, it'd be extremely helpful if you could take a look at it as well and confirm its relevance. A simple comment with a nice emoji will be enough `:+1`. Thank you for your contribution!

Thank you for the FU, but this is not relevant
