### ISSUE TITLE
Multiline sends unmatched multiline beginning of file

### ISSUE THREAD

**Issue by fraseracct** [elastic/beats#1611]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For confirmed bugs, please report:
- filebeat-1.2.1
- Windows 2007
- Steps to Reproduce: 

1. Extract sample.zip (attached)
2. run filebeat -e -v -c filebeat.yml

Observed:

*********************** UNEXPECTED NON MATCHING DATA

2016/05/11 13:34:24.325552 publish.go:88: INFO Start sending events to output
{"@timestamp":"2016-05-11T13:34:24.286Z","beat":{"hostname":"ITEM-AX35133","name":"ITEM-AX35133"},"count":1,"fields":null,"input_type":"log","message":"04/18/2016 05:07:42.775  INFO=\u003eHello there world.\r\n04/18/2016 05:07:42.775  INFO=\u003eYou should not see this\r\n04/18/2016 05:07:42.776  INFO=\u003eAre you seeing this and why\r\n04/18/2016 05:07:42.776  INFO=\u003eYep some data here\r\n04/18/2016 05:07:43.205  INFO=\u003eMore text\r\n04/18/2016 05:07:50.770  INFO=\u003eEven more stuff\r\n04/18/2016 05:07:56.126  INFO=\u003eThis line has the","offset":0,"source":"sample.log","type":"log"}
2016/05/11 13:34:26.777797 publish.go:104: INFO Events sent: 1
2016/05/11 13:34:26.778797 registrar.go:157: INFO Registry file updated. 1 states written.

*********************** MATCHING DATA

{"@timestamp":"2016-05-11T13:34:24.286Z","beat":{"hostname":"ITEM-AX35133","name":"ITEM-AX35133"},"count":1,"fields":null,"input_type":"log","message":"04/18/2016 05:08:47.546  ------------------ Begin Data -----------------\r\n04/18/2016 05:08:47.546  This I want Line 2\r\n04/18/2016 05:08:47.546  This I want Line 3\r\n04/18/2016 05:08:47.546  This I want Line 4\r\n04/18/2016 05:08:47.546
  This I want Line 5\r\n04/18/2016 05:08:47.546  This I want Line 6\r\n04/18/2016 05:08:47.546  This I want Line 7","offset":426,"source":"sample.log","type":"log"}
2016/05/11 13:34:31.778297 publish.go:104: INFO Events sent: 1
2016/05/11 13:34:31.779297 registrar.go:157: INFO Registry file updated. 1 states written.

[sample.zip](https://github.com/elastic/beats/files/259376/sample.zip)

**Comment by ruflin** [comment]
Closing this issue as it is not a confirmed bug and double post: https://discuss.elastic.co/t/multiline-sends-unmatched-multiline-beginning-of-file-1611/49772
