### ISSUE TITLE
Windows based default high_mean_cpu_iowait_ecs job

### ISSUE THREAD

**Issue by inqueue** [elastic/beats#16115]
When setting up an anomaly detection job using Metricbeat system data from the template, it does not include fields required to setup IO wait monitoring for Windows systems. See https://github.com/elastic/beats/issues/505. Attempting to apply the default job to data originating from Windows Metricbeat results in analysis over empty field `system.cpu.iowait.pct` when it should be using `cpu.user_p`.

![snip1](https://user-images.githubusercontent.com/6099128/73882115-83325c80-482f-11ea-94c2-4c5149e1fcf1.jpg)

![snip2](https://user-images.githubusercontent.com/6099128/73882125-86c5e380-482f-11ea-86e9-8bd2e4f8067a.jpg)

![snip3](https://user-images.githubusercontent.com/6099128/73882129-89c0d400-482f-11ea-88e6-abcad348d39f.jpg)

Setting up a job with the correct field for Windows resolves the issue. It would be a big usability bonus to have a default job that ships with Metricbeat that works with Windows data.

**Comment by kunisen** [comment]
hi @inqueue

May I ask your help to check this comment please?

> Attempting to apply the default job to data originating from Windows Metricbeat results in analysis over empty field `system.cpu.iowait.pct` when it should be using `cpu.user_p`.

I did some investigation and found `cpu.user_p` seems to be an old field, and it's now replaced with `system.cpu.user.pct`, which is not `system.cpu.iowait.pct`.

https://github.com/elastic/beats/pull/4550/files#diff-d1f0b4526ef0b5e6ec951c4fcd427a0aa9caa0f6175e430a7d06f6b237dc6d81L10051
https://github.com/elastic/beats/pull/4550/files#diff-9c6b1c59af18f2f1fb31d5c033f850aa2bcb8b990bdd9cdc2afc4e380f7b3d40L16

Do you happen to know how we could get `system.cpu.iowait.pct` for Metricbeat on Windows please?
