### ISSUE TITLE
FileBeat not being load balanced

### ISSUE THREAD

**Issue by GittyHup** [elastic/beats#1614]
- Version: 
  On windows server: FileBeat (Windows - filebeat version 1.2.2 (386))
  On logstash indexer server: logstash 2.3.2
  
- Operating System: 
  Windows server: Microsoft Windows NT 6.0.6002 Service Pack 2
  Logstash indexer server: RHEL Linux 4.1.13-19.30.amzn1.x86_64

- Steps to Reproduce: 
  
I tried load balancing with 2 different logstash indexer servers, but when I add, say 1000 lines to my log, filebeats sends logs exclusively to only one server (I enabled stdout and can visually check output too see which logstash server is receiving the log events)

My filebeats conf:

	filebeat:
	  prospectors:
		-
		  paths:
			- "D:/ApacheLogs/Test/access.*.log"
		  input_type: log
		  document_type: my_test_log
		  scan_frequency: 1s
	  registry_file: "C:/ProgramData/filebeat/registry"
	output:
	  logstash:
		hosts: ["10.231.2.223:5044","10.231.4.143:5044"]
		loadbalance: true
	shipper:
	logging:
	  files:

will there be added support to disable persistent TCP connection on filebeats? I currently cannot use AWS ELB since due to sticky connection it always sends to one logstash server until it gets reset. Is this not the right architecture for it? Should I be sending to redis queue instead? In filebeats I have no idea nor could find any documentation how to send to redis queue?

Something like these did not work, I can't even find a way to debug it because filebeats leaves no logs

	filebeat:
	  prospectors:
		-
		  paths:
			- "D:/ApacheLogs/Test/access.*.log"
		  input_type: log
		  document_type: my_test_log
		  scan_frequency: 1s
	  registry_file: "C:/ProgramData/filebeat/registry"
	output:
	  redis:
		# Set the host and port where to find Redis.
		host: "logstash-redis.abcde.0001.usw2.cache.amazonaws.com"
		port: 6379
	shipper:
	logging:
	  level: warning
	  # enable file rotation with default configuration
	  to_files: true
	  files:
		path: C:\temp\filebeat.log

**Comment by ruflin** [comment]
@GittyHup To get more debug info, set your logging level to "debug". Here are the docs for the redis output: https://www.elastic.co/guide/en/beats/filebeat/current/redis-output.html

**Comment by urso** [comment]
filebeat is operating in batches. Default values is 2048 events. Adding 1000 lines at once will have filebeat collect all these lines into one batch and forward the batch to only one logstash instance.

The config options `filebeat.spool_size` and `output.logstash.bulk_max_size` do configure the batch sizes being used.

By default filebeat operates by waiting for ACK from remote logstash before having the spooler send the next batch. One can enable async processing in filebeat via `filebeat.publish_async=true`. Async mode will push multiple batches into the pipeline and handle ACKs asynchronously. Alternatively (or in addition) set  `filebeat.spool_size` to be a multiple of `output.logstash.bulk_max_size`. In this case the output will split up the batches into N batches of `bulk_max_size` and load-balances them on configured outputs.

Filebeat 1.2.2 redis output is not recommended. It has been rewritten in 5.0 alpha2 to support load balancing by configuring multiple hosts + (optionally) multiple workers. But even for redis output the  `spool_size`, `publish_async` and `bulk_max_size` do operate similar to logstash output and must be adjusted to get some good load-balancing. Question is if load balancing is reuiqred.

Closing issue. Please do not ask support questions on github, but use discuss forum first.

**Comment by GittyHup** [comment]
@urso Just quick question, why is redis output not recommended, is it because it is only in alpha stage? Also for load balancing, we do need to make sure if logstash indexer goes down, another one will take its place, so I tried an AWS load balancer, but due to persistent TCP connections, filebeat always sends to one of the logstash indexer instances, hence I decided to use the redis queue. Updating filebeat config file hosts with dynamically changing IP, or in case of scaling events where we add more logstash indexers, this simply won't work.

**Comment by urso** [comment]
1. filebeat versions 1.x redis output is not recommended for: potentially silent message drops (no error handling or recovery), no support for load-balancing. It has been re-implemented in 5.0 alpha2. With 5.x you're free to use filebeat+redis. Delivery guarantees are up to your redis cluster (e.g. all state in memory, what happens if redis crashes)

2. filebeat will attempt to reconnect on failure. if pointed to public host, filebeat will be forwarded to another logstash instance. You can also set the `output.logstash.worker>1`. In this case you will get some load-balancing with N workers each connected to another logstash endpoint (thanks to ELB distributing connections) and if one connection goes down filebeat will reconnect via ELB to another logstash endpoint.
