### ISSUE TITLE
[Filebeat] Upgrade cef module to ECS 1.4

### ISSUE THREAD

**Issue by leehinman** [elastic/beats#16157]
### Filesets

  - [ ] log

**Comment by leehinman** [comment]
evaluated and no changes were needed.

**Comment by leehinman** [comment]
On further consideration should populate all related.user, related.ip & related.hash fields

**Comment by MikePaquette** [comment]
@leehinman Nice - we often forget to populate those fields, which are valuable for pivoting in SIEM timeline.

**Comment by webmat** [comment]
I'm not sure how close we are to using the default pipeline (#14001), but the `related.*` fields would be a great candidate to add in there, specifically to make sure they're not forgotten :-)
