### ISSUE TITLE
Filebeat 7.5.1 clogging memory and crashing

### ISSUE THREAD

**Issue by ct0br0** [elastic/beats#16195]
We have 1-2 directories with 5-10 json files we collect, sometimes 1 sub directory with lower file count and size of files.
Some of these can reach 100s of GB a day and get rotated around UTC midnight.

A box may be fine for a day or few, but eventually filebeat will clog up memory and constantly crash. Virtual memory will jump from 1-2-5---200GB and filebeat will repeatedly die within a few minutes to an hour after the initial crash.
The only thing that we find will fix it is a reboot. Until it happens again.
This happens on 100-200 machines.

Filebeat (and whole stack) 7.5.1
Oracle Linux 7.7

<details>
<summary>configs</summary>
/etc/filebeat/filebeat.yml

filebeat.config.inputs:
  enabled: true
  path: /etc/filebeat/conf.d/*.yml

queue.mem:
  events: 262144
  flush.min_events: 512
  flush.timeout: 0s

output.logstash:
  hosts:
    -12 or so removed
  loadbalance: true
  ssl.certificate: removed
  ssl.key: removed
  ssl.verification_mode: removed
  workers: 4
  bulk_max_size: 4096
  pipelining: 3

xpack.monitoring:
  enabled: true
  elasticsearch:
    username: removed
    password: removed
    ssl.enabled: true
    ssl.key: removed
    ssl.certificate: removed
    ssl.verification_mode: removed
    hosts: [ 1 removed ]

1 or 2 configs with same content for different directories
/etc/filebeat/conf.d/*

- type: log
  enabled: true
  paths:
    - /path/removed/*.json
  fields:
    removed: removed (custom hostnames)
    removed: removed (directory tag)
  fields_under_root: true
  exclude_files: ['removed various .json files']
- type: log
  enabled: true
  paths:
    - /path/removed/sameasabove/*.json (directory another layer deep from above)
  fields:
    removed: removed (directory tag)
  exclude_files: ['removed various .json files']
</details>

**Comment by kvch** [comment]
Github Issues are reserved for verified bugs. Please post your question on Discuss: https://discuss.elastic.co/c/beats

**Comment by ct0br0** [comment]
I made a comment on another issue and was requested to open a new bug.

**Comment by kvch** [comment]
Could you please refer to that issue comment?

**Comment by ct0br0** [comment]
https://github.com/elastic/beats/issues/14917

not that i have much knowledge of the inner workings, but https://github.com/elastic/beats/issues/16286 seems related

**Comment by ct0br0** [comment]
we are restarting filebeat daily and have not seen a significant memory issue yet. will update in a week with how it's going

**Comment by ct0br0** [comment]
this may have something to do with it ?
https://www.elastic.co/guide/en/beats/filebeat/current/file-log-rotation.html#log-rotate-example


<details>
<summary>logrotate</summary>
"/dir/removed/*.json" {
  daily
  create 0644 user user
  minsize 16
  rotate 5
  missingok
  copytruncate
  delaycompress
}
</details>

**Comment by ct0br0** [comment]
looks like over the weekend everything started hogging memory again

**Comment by ct0br0** [comment]
7.6.1 - same issues

**Comment by ct0br0** [comment]
FYI - I will be leaving my position where I am able to test this issue.
It is still outstanding but I can no longer provide input.
