### ISSUE TITLE
Change aws_elb autodiscover provider meta field prefix to aws.elb

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#16219]
This issue came from comment https://github.com/elastic/beats/pull/14823#discussion_r359766532 when adding `aws_ec2` autodiscover provider in https://github.com/elastic/beats/pull/14823. In `aws_ec2` provider, meta fields are started with `aws.ec2` to match metrics from aws module Metricbeat. 

Similarly,  it would be good to update `aws_elb` provider to also have `aws.elb` prefix for meta fields. Also meta fields are not added to autodiscover template, similar to https://github.com/elastic/beats/pull/14823#discussion_r375714303.

**Comment by kaiyan-sheng** [comment]
@andrewvc `aws_elb` is experimental, does that mean we can make the change without waiting till 8.0.0?

**Comment by andrewvc** [comment]
That's a good point @Kaiyan-Sheng , given the experimental status I'm OK with this. Do you mind updating the docs as well?

**Comment by kaiyan-sheng** [comment]
@andrewvc Will do, thanks!
