### ISSUE TITLE
[Filebeat - Module Cisco-ASA] Parsing of Cisco Event Message 734001

### ISSUE THREAD

**Issue by MarcusCaepio** [elastic/beats#16212]
Hi all,
**Describe the enhancement:**
we recently switched from Logstash to Ingest with filebeat-cisco-asa and unfortunately noticed, that one important cisco message is not yet ingested (correctly), the cisco.asa.message_id:734001 . These messages give information about the DAP records, which a user gets, when he connects via VPN and are very while troubleshooting VPN problems. 
**Describe a specific use case for the enhancement or feature:**
The ID Pattern given by cisco looks like this:
%ASA-6-734001: DAP: User _user_, Addr _ipaddr_ , Connection _connection_ : The following DAP records were selected for this connection: _DAP record names_
https://www.cisco.com/c/en/us/td/docs/security/asa/syslog/b_syslog/syslogs9.html#con_5678113

Here is a sample event:
`%ASA-6-734001: DAP: User firstname.lastname@domain.com, Addr 1.2.3.4, Connection AnyConnect: The following DAP records were selected for this connection: dap_name1, dap_name2`
The Pattern and Logstash filter, I used in the past, looks like this:
```
Pattern:
CISCOFW734001 DAP: User %{DATA:user}, Addr %{IP:src_ip}, Connection %{GREEDYDATA:connection_type}: The following DAP records were selected for this connection: %{GREEDYDATA:dap_records}

Filter:
    if [dap_records] {
      mutate {
        split => { "dap_records" => ", " }
      }

```

It would be very nice, if this could be Ingested by Filebeat, too. At the moment, we are not able use elastic for this use case, because we can though search the message id, but as soon as we additionally search for a username in the event.original field, the search really takes very, very long.

As I am currently totally inexperienced in creating modules. So I don't know, if I can give constructive help here. But if sb. can lend me a hand, where I have to begin (beside the docs), I will try to help.

Also relates to elastic/beats#14151

Thanks in advanced!
Cheers,
Marcus

**Comment by MarcusCaepio** [comment]
Maybe @adriansr can help here most?

**Comment by andrewkroh** [comment]
> But if sb. can lend me a hand, where I have to begin (beside the docs), I will try to help.

Hi @MarcusCaepio, the Cisco ASA module uses an Elasticsearch Ingest Node pipeline to do the parsing. This module is bundled into the Filebeat install. You can try making modification to your pipeline and testing the results. Any time you change the pipeline config on disk you need to reinstall it to Elasticsearch before indexing any log data.

Your filebeat install will have a module/cisco/shared/ingest/asa-ftd-pipeline.yml file. You probably want to insert a [`dissect` processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/dissect-processor.html) for message 734001. For example this is how message 106001 is parsed:

https://github.com/elastic/beats/blob/4b69bf21467a20ef6a916ddc7855ef29d912ba77/x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml#L159-L162

After you make changes to that file you need to re-install the pipeline to ES with 

  `filebeat setup --pipelines -E filebeat.overwrite_pipelines=true -e` 

so your changes take effect. Then you can send some test log lines through and check the result. If the changes work let us know and we can update the module with your changes.

**Comment by MarcusCaepio** [comment]
Hey @andrewkroh ,
Thanks a lot for the tipps. Today I tried your suggestion and I think, I have created a working pattern. Maybe you want to have a look on the commit in my fork (the last one, as the first one had a missing pattern for connection_type) and tell me if this is ok for a PR?

Thanks in advance.

**Comment by adriansr** [comment]
@MarcusCaepio , go ahead with the PR. You'll have to make sure that the new fields under `cisco` are added to `module/cisco/asa/_meta/fields.yml` and `module/cisco/ftd/_meta/fields.yml` and maybe you can add an example log line to `module/cisco/asa/test`.

Instead of `cisco.user` I think you can use one of the ECS fields, `user.name` or `user.email`.

**Comment by MarcusCaepio** [comment]
Hi @adriansr ,
Is it necessary to set "cisco.dap_records" to fields.yml? As it is a text, which has to be split anyway and its entries may very a lot, I see no sense to use anything beside default text type. For cisco.connection_type, I see a sense to use "type: keyword", at it is one of 
- IPsec
- AnyConnect
- Clientless (web browser)
- Cut-Through-Proxy
- L2TP
