### ISSUE TITLE
Packetbeat Enhancement Request: Add support for reloadable config path

### ISSUE THREAD

**Issue by axrayn** [elastic/beats#16227]
Currently all the other Beats support a reloadable config and subdirectory for specific config files:

- Filebeat (inputs.d)
- Metricbeat (modules.d)
- Auditbeat (modules.d and audit.rules.d)
- Heartbeat (monitors.d)

It would be good to similar support for a reloadable config directory like `/etc/packetbeat/protocols.d` where users could have individual yml files per protocol. This would also facilitate the use of automation (ansible et al) to dynamically enable/disable protocol parsing as required and mean that updating which protocols are enabled doesn't require the editing of the primary packetbeat.yml file and restarting the service.

e.g. /etc/packetbeat/protocols.d/cassandra.yml would hold:
```
# Protocol: cassandra
# Docs: https://www.elastic.co/guide/en/beats/packetbeat/current/configuration-cassandra.html

- type: cassandra
  #Cassandra port for traffic monitoring.
  #ports: [9042]
```
and /etc/packetbeat/protocols.d/dns.yml would hold:
```
# Protocol: dns
# Docs: https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-dns-options.html

- type: dns
  # Configure the ports where to listen for DNS traffic. You can disable
  # the DNS protocol by commenting out the list of ports.
  ports: [53]
  enabled: true

  # include_authorities controls whether or not the dns.authorities field
  # (authority resource records) is added to messages.
  include_authorities: true

  # include_additionals controls whether or not the dns.additionals field
  # (additional resource records) is added to messages.
  include_additionals: true
```

**Comment by gittygoo** [comment]
much needed from my side also, deploying with puppet and facing the exact same problem

**Comment by axrayn** [comment]
Would still be good to get this feature for packetbeat.

**Comment by axrayn** [comment]
Still interested in this feature.
