### ISSUE TITLE
Add support for custom endpoint configuration in AWS modules for Filebeat and Metricbeat

### ISSUE THREAD

**Issue by mbarretta** [elastic/beats#16245]
**Describe the enhancement:**
Add support for custom endpoint configuration in the AWS modules for Filebeat and Metricbeat

**Describe a specific use case for the enhancement or feature:**
Many users are running in AWS private cloud regions. The existing modules hardcode the AWS endpoints making these modules useless.

Similar configuration options are available in the Logstash s3 input and the s3 snapshot repository for Elasticsearch.

**Comment by andresrc** [comment]
Closed by #16263
