### ISSUE TITLE
Beats package got an error when building for darwin/amd64

### ISSUE THREAD

**Issue by v1v** [elastic/beats#16299]
https://github.com/elastic/beats/issues/15953 was closed as the CI workers are now back to business.

[build for macos](https://beats-ci.elastic.co/job/elastic+beats+master+multijob-package-darwin/348/) has failed with:

```
18:14:33 Status: Downloaded newer image for docker.elastic.co/beats-dev/golang-crossbuild:1.13.7-darwin
18:14:34 >> Building using: cmd='build/mage-linux-amd64 golangCrossBuild', env=[CC=o64-clang, CXX=o64-clang++, GOARCH=amd64, GOARM=, GOOS=darwin, PLATFORM_ID=darwin-amd64]
18:14:34 sh: 1: build/mage-linux-amd64: not found
18:14:34 Error: failed building for darwin/amd64: exit status 127
18:14:34 failed building for darwin/amd64: exit status 127
18:14:34 package ran for 2m26.996460457s
18:14:34 Error: running "docker run --env EXEC_UID=596 --env EXEC_GID=503 --rm --env MAGEFILE_VERBOSE= --env MAGEFILE_TIMEOUT= -v /private/var/lib/jenkins/workspace/elastic+beats+master+multijob-package-darwin/src/github.com/elastic/beats:/go/src/github.com/elastic/beats -w /go/src/github.com/elastic/beats/auditbeat docker.elastic.co/beats-dev/golang-crossbuild:1.13.7-darwin --build-cmd build/mage-linux-amd64 golangCrossBuild -p darwin/amd64" failed with exit code 1
18:14:34 make[1]: *** [release] Error 1
```

## Actions
- Debug what's going on
- Reproduce locally if possible and document the steps to help with similar issues in the future.
- Propose a fix if possible or contact/transfer this ticket

**Comment by v1v** [comment]
It seems the issue is now with the python3 version:

```
21:53:07 + make release
21:53:07 Installing mage v1.9.0 from vendor dir.
21:53:07 go install -mod=vendor -ldflags="-X github.com/magefile/mage/mage.gitTag=v1.9.0" github.com/magefile/mage
21:53:12 /var/lib/jenkins/workspace/elastic+beats+master+multijob-package-darwin/.magefile cleaned
21:53:12 /bin/sh: python3: command not found
```

See [build](https://beats-ci.elastic.co/blue/organizations/jenkins/elastic%2Bbeats%2Bmaster%2Bmultijob-package-darwin/detail/elastic%20beats%20master%20multijob-package-darwin/382/pipeline#log-125)

@mikemadden42 , I guess this issue might be related to the one you mentioned to install python3 in the MacOS. I'll wait for your feedback before doing any other actions.

**Comment by mikemadden42** [comment]
@v1v `python3` should be on the beat-ci worker now. 🤞

**Comment by v1v** [comment]
I'm now able to reproduce it locally

```
docker run --env EXEC_UID=$(id -u) --env EXEC_GID=$(id -g) \
    --env GOFLAGS=-mod=vendor \
    --rm --env MAGEFILE_VERBOSE= \
    --env MAGEFILE_TIMEOUT= \
    --env SNAPSHOT=true \
    -v $(pwd):/go/src/github.com/elastic/beats \
    -w /go/src/github.com/elastic/beats/auditbeat \
    docker.elastic.co/beats-dev/golang-crossbuild:1.13.9-darwin \
    --build-cmd build/mage-linux-amd64 golangCrossBuild -p darwin/amd64
>> Building using: cmd='build/mage-linux-amd64', env=[CC=o64-clang, CXX=o64-clang++, GOARCH=amd64, GOARM=, GOOS=darwin, PLATFORM_ID=darwin-amd64]
sh: 1: build/mage-linux-amd64: not found
Error: failed building for darwin/amd64: exit status 127
failed building for darwin/amd64: exit status 127
```

**Comment by v1v** [comment]
I'm now able to run the below commands locally:

```
git checkout master
eval $(gvm $(cat .go-version))
SNAPSHOT=true PLATFORMS=darwin GO111MODULE=on WORKSPACE=$(pwd) make release
```

**Comment by v1v** [comment]
#### Status
- python3 issue solved
- Beats packaging gets stalled/failed in a particular, even when running the CI Job or when ssh onto the CI worker:
  - `mage CollectAll`
  - `Generated fields.yml for functionbeat to /private/var/lib/jenkins/workspace/elastic+beats+master+multijob-package-darwin/src/github.com/elastic/beats/x-pack/functionbeat/fields.yml`
- Asked infra to use ephemeral Darwin workers
- There is only one darwin worker that it seems it's the only one enabled to run this job for some unknown required configuration.
- The current OSX worker has got 4gb of RAM and 2 CPUs and about a few years old.

#### Next actions
- Configure `apm-ci` darwin workers with the required dependencies (keychain, vault, xcode, docker)
- Enable a pipeline in the apm-ci for running the packaging.

**Comment by v1v** [comment]
I'll close this issue now, we don't need to use the only worker for signing now, since we are not signing in the CI builds for PRs
