### ISSUE TITLE
[Agent] Investigate Jenkins CI for PRs targetting Fleet branch.

### ISSUE THREAD

**Issue by ph** [elastic/beats#16290]
We use to have the Jenkins Ci run on our PRs but for a few days this doesn't appear to be the case we only have Travis-ci running.  I am going to take a look, creating the issue so it's doesn't fall into a crack.

Did you saw the same behavior @michalpristas  ?

**Comment by michalpristas** [comment]
i havent noticed as i mostly check Travis (i like UI better) but this is indeed weird

**Comment by ph** [comment]
Yeah, after discussing over slack its because or feature branch doesn't follow the appropriate scheme for having them included we need to add `feature-* in front of our branch.

**Comment by ph** [comment]
So I've renamed the **fleet** branch to **feature-ingest**, the same name as Kibaban this indeed fix the problems with the **beats-ci** job. I am almost certain that it did work at some point.

**Comment by ph** [comment]
Note, that renaming the branch did auto-close all the PRs that was targeting that branch.

If you want  to see that beats-ci is running you can also take a look at https://github.com/elastic/beats/pull/16314
