### ISSUE TITLE
[Filebeat] Add human readable field with translation for FW_EVENT to NetFlow module

### ISSUE THREAD

**Issue by crisdarocha** [elastic/beats#16296]
**Describe the enhancement:** In the Filebeat NetFlow module, `FW_EVENT` are numeric codes that are mapped to `netflow.firewall_event`. 

From the [Cisco documentation](https://www.cisco.com/c/en/us/td/docs/routers/sdwan/configuration/security/ios-xe-16/security-book-xe/enterprise-firewall.html#concept_0CFD43B24B544D8583777D8B25191292), we have the meaning of the codes:
```
Indicates a firewall event. The allowed values are:
0 - Ignore (invalid)
1 - Flow Created
2 - Flow Deleted
3 - Flow Denied
4 - Flow Alert
5 - Flow Update 
```

It would be great to have a new field, ECS compliant, that stores the "translated" human readable value for the `FW_EVENT`.

**Describe a specific use case for the enhancement or feature:**
Numeric codes are great for programatic analysis, but don't say much when humans try to understand the event lines. Enriching the data at pipeline level would add value to the analysis.

**Comment by abraxxa** [comment]
It‘s still relevant for us.

**Comment by abraxxa** [comment]
👍🏻
