### ISSUE TITLE
Collect number of threads per process

### ISSUE THREAD

**Issue by henrikno** [elastic/beats#16292]
**Describe the enhancement:**
Collect number of threads, either per process, or the total on the machine, or both.
On linux per process is available in `/proc/pid/task` or `/proc/pid/stat`.

**Describe a specific use case for the enhancement or feature:**
We had a case where a process was running rampant creating lots of threads, which caused the machine to run out of pids, which made the box unresponsive (can't create new ssh connection, etc).
It would have been easier to spot which process caused this with number of threads per process, or at least be able to identify it by having the total number of threads on the machine as a warning sign, which is e.g. shown by top
![image](https://user-images.githubusercontent.com/147660/74383709-9780d700-4da4-11ea-95a1-9dcf3fcbc5e9.png)

**Comment by amandahla** [comment]
@henrikno What a interesting situation...I think that to prevent this, it would be need to monitor the sum of all threads and check if it's above the maximum allowed. 
What do you think?

Maximum number of threads:
cat /proc/sys/kernel/threads-max

Maximum number of PID's:
cat /proc/sys/kernel/pid_max

Show sum of all threads:
ps -eo nlwp | tail -n +2 | awk '{ num_threads += $1 } END { print num_threads }'

References:
https://www.geeksforgeeks.org/maximum-number-threads-can-created-within-process-c/ 
https://askubuntu.com/questions/88972/how-to-get-from-terminal-total-number-of-threads-per-process-and-total-for-al
