### ISSUE TITLE
Add Windows installer

### ISSUE THREAD

**Issue by tsg** [elastic/beats#163]
We used to provide packages for Windows, but they were pretty much manually created and the installation process was also quite complex.

This ticket is for having the proper infrastructure for building the Windows binaries and for finding a good way for running the service.

**Comment by Zelnox** [comment]
+1

**Comment by shadowcodex** [comment]
This is needed, badly... +1

**Comment by monicasarbu** [comment]
Sadly, we didn't start working on this yet. Removing the "in progress" label.

**Comment by andrewkroh** [comment]
Based on the description

> "This ticket is for having the proper infrastructure for building the Windows binaries and for finding a good way for running the service"

I'd say this is complete. We have both Windows binaries and an easy way to install it as a service.

What we do not have have is a Windows installer (e.g. an MSI). If that's what we are waiting on then let's update the title.

**Comment by monicasarbu** [comment]
@andrewkroh You are right. The title is misleading. I have updated the title to "Add Windows installer".

**Comment by maddin2016** [comment]
Hi there,
i see that this issue is still open. Is this feature still from interest?

**Comment by tsg** [comment]
@maddin2016 we are still interested in providing better Windows packages, but our current packaging system builds everything from Linux via cross compilation, so I'm not sure if Wix can help. See https://github.com/elastic/beats/tree/master/dev-tools/packer

I did, a long time ago, used wixl from msitools to build MSIs from linux, but from what I remember I hit some bugs.

**Comment by elvarb** [comment]
You could easily use inno installer to create a install package. http://www.jrsoftware.org/isinfo.php

**Comment by maddin2016** [comment]
@tsg, i thought we create the msi at build and then like the `exe` copy the `msi` into the zip?!

**Comment by dominiquearpin** [comment]
Any news for a msi package?

**Comment by dominiquearpin** [comment]
It will be great to have a msi for each beats.  That could be great with tools like Puppet/Chef for deploying in large environment.

**Comment by OffColour** [comment]
I've created a Filebeat MSI generator.
Run the PS script with the URl to the filebeat zip and it'll create the MSI for you.

[https://github.com/OffColour/filebeat-msi](https://github.com/OffColour/filebeat-msi)

**Comment by sasubillis** [comment]
Yes, please get MSI for each beat. We are having issues with beats installation using puppet without msi.

**Comment by OffColour** [comment]
Come on folks. I'd never touched WIX before in my life and it took me all of two days to build the MSI generator. Grab my code and build away!

**Comment by ygel** [comment]
Beats Windows MSI packages are official in v7.6.0, for example, [winlogbeat](https://www.elastic.co/downloads/beats/winlogbeat)

Also: https://github.com/elastic/elastic-stack-installers
