### ISSUE TITLE
automatically load new configuration files from config_dir

### ISSUE THREAD

**Issue by inqueue** [elastic/beats#1630]
Provide the capability to dynamically load and unload prospector configuration files in `filebeat.config_dir`. This could make it easier, for example, for a Chef cookbook to drop a file into the `config_dir` and start shipping logs without restart.

**Comment by vsantoshkiran1** [comment]
Thanks for adding this request Jason.

**Comment by nickcarenza** [comment]
Is there any way to accomplish loading multiple config files currently? Even if I have to restart.

**Comment by nickcarenza** [comment]
I have tested providing multiple -c flags to filebeat to no avail.

**Comment by ruflin** [comment]
This is kind of related to https://github.com/elastic/beats/issues/464 as both need dynamic reloading of configuration options.

**Comment by ruflin** [comment]
Closing as this was introduced with dynamic reloading: https://www.elastic.co/guide/en/beats/filebeat/5.4/filebeat-configuration-reloading.html
