### ISSUE TITLE
[Agent] Monitor Agent metrics and logs

### ISSUE THREAD

**Issue by ph** [elastic/beats#16303]
We need to monitor the Agent logs and metrics and send them to Elasticsearch. 

**Question:** Are we still using the sidecars strategy to do that and where does it fit?

**Comment by ph** [comment]
Maybe we need to discuss the possibility of having the agent send events directly to Elasticsearch?

**Comment by ruflin** [comment]
@ph I can see that in some cases where this will become useful to report back to the Elasticsearch cluster with Fleet in case the sidecards for example can't be started. But I would not use it for full monitoring / logging.

**Comment by kevinlog** [comment]
@ruflin @ph for what it's worth, we're planning to have the Endpoint send Endpoint specific logs directly into ES without a sidecar.  Not sure what kind of impact that has on decision making for the Agent level.

FYi @ferullo

**Comment by ph** [comment]
@kevinlog I don't have a problem with that we could disable it for endpoint, I supose the logs will be send to an indice matching our `logs-*` pattern?
