### ISSUE TITLE
Redis slow log missing fields

### ISSUE THREAD

**Issue by mrudrara** [elastic/beats#16312]
**Describe the enhancement:**
We use filebeat module for ingesting Redis slow logs and it is awesome. 
my problem: seems like the current module skip to ingest extra fields that were introduced post 3.x version like application name, client IP address

like below 

myredis:6379> SLOWLOG get 10
1) 1) (integer) 9134029
   2) (integer) 1581615540
   3) (integer) 219721
   4) 1) "SUNION"
      2) "awesome-service:dhdjkclpjdjj:1234"
   5) "10.10.10.10:34595"
   6) "aweomeservice"

**Describe a specific use case for the enhancement or feature:**
this helps us to pinpoint the application and client ip

**Comment by wangbaocongnb** [comment]
Have you solved this problem?

**Comment by mrudrara** [comment]
@andrae-sec Wondering if this can be prioritized. Client Ip and Application Name was added to slow logs in 4.x and current new release redis 6.x
this is good enhancement and adds value to our Redis Observability
