### ISSUE TITLE
Filebeat 7.6.0 - the number of source shards [4] must be a factor of [30]

### ISSUE THREAD

**Issue by MarcusCaepio** [elastic/beats#16323]
Hi all,
long story short: After updating to Filebeat 7.6.0, there is (again?) a necessary number of source shards of factor 30. This was not present on 7.5.2 as all my indices has a number of shards of max. 4 which worked very well. Why did this change? I think, I have to check all my beats now, if this came up on everyone...
`{"type":"illegal_argument_exception","reason":"the number of source shards [4] must be a factor of [30]"}
`

Regards,
Marcus

**Comment by urso** [comment]
Filebeat adds the `number_of_routine_shards` to the template by default. Overwrite the setting to be a multiple of 4, or export the template via `filebeat export template` and remove the setting. Filebeat 7.7.0 will have the setting removed: https://github.com/elastic/beats/pull/16038

> This was not present on 7.5.2 as all my indices has a number of shards of max. 4 which worked very well. Why did this change?

Checking the source code for Filebeat 7.5.2, I can tell that `number_of_routing_shards` was set by default to 30. The default can be overwritten in the configuration file. Is there a chance that you modified part of your configuration file when upgrading?
