### ISSUE TITLE
Fix broken external dependencies

### ISSUE THREAD

**Issue by Pungyeon** [elastic/beats#16326]
**Describe the enhancement:**
It is currently not possible to import `github.com/elastic/beats/cmd.GenRootWithSettings` using go modules. This will break (several things):

1. This will retrieve a really old version of the docker-client, which is incompatible
2. The same is true for k8s.io client
3. The `github.com/dop251/goja` dependencies which are included (vendored) in the github repository, is completely broken. The function `RegisterSimpleMaptype()` does not exist anymore, and even worse, there are no releases and no branches for this library. The only way to fix this would be to fork the project and revert the changes back to before the deletion of said function. 

I therefore propose to fix these dependencies and include a `go.mod`, to make working with the `libbeat` library much easier. 

I am willing to help with this project and will happily contribute to fixing this.

**Describe a specific use case for the enhancement or feature:**
Make writing custom beats much easier (when using go modules).

**Comment by kvch** [comment]
Beats has just adopted go modules as a dependency manager. Does this fix your problems?

**Comment by Pungyeon** [comment]
Hi @kvch I though this would fix it, but it seems that there are still some external dependencies which aren't being imported correctly, when using the libbeat library from a new project. 

Perhaps I am doing something wrong though.... This is the error message that I receive, when I try to build my project:

```
# github.com/elastic/beats/libbeat/common/docker
../../go/pkg/mod/github.com/elastic/beats@v7.6.0+incompatible/libbeat/common/docker/client.go:37:12: undefined: client.Opt
../../go/pkg/mod/github.com/elastic/beats@v7.6.0+incompatible/libbeat/common/docker/client.go:46:23: undefined: client.WithVersion
../../go/pkg/mod/github.com/elastic/beats@v7.6.0+incompatible/libbeat/common/docker/client.go:49:23: undefined: client.WithAPIVersionNegotiation
../../go/pkg/mod/github.com/elastic/beats@v7.6.0+incompatible/libbeat/common/docker/client.go:52:9: undefined: client.NewClientWithOpts
# k8s.io/client-go/rest
../../go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
# github.com/elastic/beats/libbeat/processors/script/javascript
../../go/pkg/mod/github.com/elastic/beats@v7.6.0+incompatible/libbeat/processors/script/javascript/session.go:260:14: s.Runtime().RegisterSimpleMapType undefined (type *goja.Runtime has no field or method RegisterSimpleMapType)
# github.com/corticph/benchmark-model/beater
beater/beater.go:84:5: cannot use "github.com/Pungyeon/beats/libbeat/common".MapStr literal (type "github.com/Pungyeon/beats/libbeat/common".MapStr) as type "github.com/elastic/beats/libbeat/common".MapStr in field value
```

**Comment by kvch** [comment]
Could you share your `go.mod`?

We are using a forks of a few dependencies. You need to add those to the replace section of your Beats because the go version we are using is a bit limited in that regard. I think adding those directives will fix your issue.

Also, I am working on moving Beat generators to go modules as well. It is in progress, but I expect it to be done soon. You might be interested in it: https://github.com/elastic/beats/pull/16288

**Comment by Pungyeon** [comment]
@kvch , so having tried quite a few things. I started over... in the end I was still receiving the following error:

```
../../go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
        have (*versioned.Decoder)
        want (watch.Decoder, watch.Reporter)
```

But updating the version to the following:

> go get k8s.io/client-go@kubernetes-1.16.0

Seemed to work a charm. So, now everything is indeed working as intended.

Thank you so much for helping with addressing this 🙏 You are awesome !! 👏

**Comment by richard-mauri** [comment]
Is it true that beats has adopted gomodules?
Was this publicly announced and if so where and are there samples to adopting it?
EllieMae has several golang projects that need to build beats from source and so far have ben struggling with elastic beat go modules.
I want to upgrade our important custom beats to test if it helps several production issues.

**Comment by richard-mauri** [comment]
FYI, here is my compile error and go.mod file that I am fighting with.
I had to manually go get github.com/docker/docker@v19.03.11 to get past one compile failure and no I am on some goja issue.

CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o /Users/rmauri/gopath/src/githubdev.dco.elmae/CloudPlatform/em-top-beats/encompassbeat/bin/darwin/encompassbeat -ldflags "-X githubdev.dco.elmae/CloudPlatform/em-top-beats/encompassbeat/beater.Version=0.0.6-2020-08-06-07-50-18" main.go
go: downloading github.com/sirupsen/logrus v1.4.1
go: finding google.golang.org/grpc v1.31.0
go: downloading google.golang.org/grpc v1.31.0
go: finding github.com/opencontainers/image-spec v1.0.1
go: finding github.com/containerd/containerd v1.3.7
go: downloading github.com/opencontainers/image-spec v1.0.1
go: downloading github.com/containerd/containerd v1.3.7
go: extracting github.com/sirupsen/logrus v1.4.1
go: extracting github.com/opencontainers/image-spec v1.0.1
go: extracting google.golang.org/grpc v1.31.0
go: extracting github.com/containerd/containerd v1.3.7
go: downloading github.com/google/go-cmp v0.4.0
go: downloading github.com/golang/protobuf v1.3.3
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: extracting github.com/google/go-cmp v0.4.0
go: extracting github.com/golang/protobuf v1.3.3
go: extracting google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: finding google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: finding github.com/golang/protobuf v1.3.3
go: finding github.com/sirupsen/logrus v1.4.1
go: finding github.com/google/go-cmp v0.4.0
# github.com/elastic/beats/libbeat/processors/script/javascript
../../../../../pkg/mod/github.com/elastic/beats@v7.6.2+incompatible/libbeat/processors/script/javascript/session.go:260:14: s.Runtime().RegisterSimpleMapType undefined (type *goja.Runtime has no field or method RegisterSimpleMapType)

OSXRMAURMBP16:encompassbeat rmauri$ cat go.mod
module githubdev.dco.elmae/CloudPlatform/em-top-beats/encompassbeat

go 1.13

require (
	github.com/DATA-DOG/godog v0.7.13 // indirect
	github.com/Microsoft/go-winio v0.4.14 // indirect
	github.com/Shopify/sarama v1.25.0 // indirect
	github.com/Sirupsen/logrus v1.4.2 // indirect
	github.com/cespare/xxhash v1.1.0 // indirect
	github.com/containerd/containerd v1.3.7 // indirect
	github.com/dlclark/regexp2 v1.2.0 // indirect
	github.com/docker/distribution v2.7.1+incompatible // indirect
	github.com/docker/docker v17.12.0-ce-rc1.0.20200531234253-77e06fda0c94+incompatible // indirect
	github.com/docker/go-connections v0.4.0 // indirect
	github.com/docker/go-units v0.4.0 // indirect
	github.com/docker/libtrust v0.0.0-20160708172513-aabc10ec26b7 // indirect
	github.com/dop251/goja v0.0.0-20200110130636-0a0a0d8cb944 // indirect
	github.com/dop251/goja_nodejs v0.0.0-20200120171228-34eac44e576f // indirect
	github.com/dustin/go-humanize v1.0.0 // indirect
	github.com/elastic/beats v7.6.2+incompatible
	github.com/elastic/ecs v1.2.0 // indirect
	github.com/elastic/go-elasticsearch/v7 v7.8.0
	github.com/elastic/go-lumber v0.1.0 // indirect
	github.com/elastic/go-seccomp-bpf v1.1.0 // indirect
	github.com/elastic/go-structform v0.0.6 // indirect
	github.com/elastic/go-txfile v0.0.6 // indirect
	github.com/elastic/gosigar v0.10.5 // indirect
	github.com/fatih/color v1.9.0 // indirect
	github.com/garyburd/redigo v1.6.0 // indirect
	github.com/go-sourcemap/sourcemap v2.1.2+incompatible // indirect
	github.com/gofrs/flock v0.7.1 // indirect
	github.com/gofrs/uuid v3.2.0+incompatible // indirect
	github.com/imdario/mergo v0.3.8 // indirect
	github.com/jstemmer/go-junit-report v0.9.1 // indirect
	github.com/karrick/godirwalk v1.14.1
	github.com/magefile/mage v1.10.0 // indirect
	github.com/miekg/dns v1.1.27 // indirect
	github.com/mitchellh/hashstructure v1.0.0 // indirect
	github.com/opencontainers/go-digest v1.0.0-rc1 // indirect
	github.com/opencontainers/image-spec v1.0.1 // indirect
	github.com/rcrowley/go-metrics v0.0.0-20190826022208-cac0b30c2563 // indirect
	github.com/spf13/cobra v0.0.5 // indirect
	go.elastic.co/apm v1.8.0
	go.elastic.co/fastjson v1.1.0 // indirect
	go.uber.org/multierr v1.4.0 // indirect
	go.uber.org/zap v1.13.0 // indirect
	golang.org/x/crypto v0.0.0-20200117160349-530e935923ad // indirect
	golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d // indirect
	golang.org/x/sys v0.0.0-20200625212154-ddb9806d33ae // indirect
	golang.org/x/text v0.3.2
	golang.org/x/time v0.0.0-20191024005414-555d28b269f0 // indirect
	google.golang.org/grpc v1.31.0 // indirect
	k8s.io/api v0.0.0-20191108065827-59e77acf588f // indirect
	k8s.io/client-go v0.0.0-20190620085101-78d2af792bab // indirect
	k8s.io/utils v0.0.0-20191030222137-2b95a09bc58d // indirect
)

replace github.com/Sirupsen/logrus v1.4.2 => github.com/sirupsen/logrus v1.4.2

**Comment by bjanders** [comment]
I have this issue too. I receive: 
```
# github.com/elastic/beats/v7/libbeat/processors/script/javascript
../../go/pkg/mod/github.com/elastic/beats/v7@v7.17.8/libbeat/processors/script/javascript/session.go:267:15: s.Runtime().RegisterSimpleMapType undefined (type *goja.Runtime has no field or method RegisterSimpleMapType)
```
<details><summary>My go.mod:</summary>

```
go 1.18

require (
	github.com/elastic/beats/v7 v7.17.8
	github.com/magefile/mage v1.14.0
)

require (
	github.com/Microsoft/go-winio v0.5.2 // indirect
	github.com/Shopify/sarama v1.38.1 // indirect
	github.com/StackExchange/wmi v0.0.0-20170221213301-9f32b5905fd6 // indirect
	github.com/akavel/rsrc v0.8.0 // indirect
	github.com/armon/go-radix v1.0.0 // indirect
	github.com/cespare/xxhash/v2 v2.1.2 // indirect
	github.com/containerd/containerd v1.5.13 // indirect
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/dlclark/regexp2 v1.1.7-0.20171009020623-7632a260cbaf // indirect
	github.com/docker/distribution v2.8.0+incompatible // indirect
	github.com/docker/docker v1.4.2-0.20190924003213-a8608b5b67c7 // indirect
	github.com/docker/go-connections v0.4.0 // indirect
	github.com/docker/go-units v0.4.0 // indirect
	github.com/dop251/goja v0.0.0-20200831102558-9af81ddcf0e1 // indirect
	github.com/dop251/goja_nodejs v0.0.0-20171011081505-adff31b136e6 // indirect
	github.com/dustin/go-humanize v1.0.0 // indirect
	github.com/eapache/go-resiliency v1.3.0 // indirect
	github.com/eapache/go-xerial-snappy v0.0.0-20230111030713-bf00bc1b83b6 // indirect
	github.com/eapache/queue v1.1.0 // indirect
	github.com/elastic/ecs v1.12.0 // indirect
	github.com/elastic/elastic-agent-client/v7 v7.0.0-20210727140539-f0905d9377f6 // indirect
	github.com/elastic/go-concert v0.2.0 // indirect
	github.com/elastic/go-lumber v0.1.0 // indirect
	github.com/elastic/go-seccomp-bpf v1.2.0 // indirect
	github.com/elastic/go-structform v0.0.9 // indirect
	github.com/elastic/go-sysinfo v1.8.1 // indirect
	github.com/elastic/go-txfile v0.0.7 // indirect
	github.com/elastic/go-ucfg v0.8.6 // indirect
	github.com/elastic/go-windows v1.0.1 // indirect
	github.com/elastic/gosigar v0.14.2 // indirect
	github.com/fatih/color v1.13.0 // indirect
	github.com/go-logr/logr v0.4.0 // indirect
	github.com/go-ole/go-ole v1.2.6 // indirect
	github.com/go-sourcemap/sourcemap v2.1.2+incompatible // indirect
	github.com/gofrs/flock v0.7.2-0.20190320160742-5135e617513b // indirect
	github.com/gofrs/uuid v4.2.0+incompatible // indirect
	github.com/gogo/protobuf v1.3.2 // indirect
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/golang/snappy v0.0.4 // indirect
	github.com/gomodule/redigo v1.8.3 // indirect
	github.com/google/go-cmp v0.5.6 // indirect
	github.com/google/gofuzz v1.1.0 // indirect
	github.com/googleapis/gnostic v0.4.1 // indirect
	github.com/h2non/filetype v1.1.1 // indirect
	github.com/hashicorp/errwrap v1.1.0 // indirect
	github.com/hashicorp/go-multierror v1.1.1 // indirect
	github.com/hashicorp/go-uuid v1.0.3 // indirect
	github.com/hashicorp/golang-lru v0.5.4 // indirect
	github.com/imdario/mergo v0.3.12 // indirect
	github.com/inconshreveable/mousetrap v1.0.0 // indirect
	github.com/jcmturner/aescts/v2 v2.0.0 // indirect
	github.com/jcmturner/dnsutils/v2 v2.0.0 // indirect
	github.com/jcmturner/gofork v1.7.6 // indirect
	github.com/jcmturner/gokrb5/v8 v8.4.3 // indirect
	github.com/jcmturner/rpc/v2 v2.0.3 // indirect
	github.com/joeshaw/multierror v0.0.0-20140124173710-69b34d4ec901 // indirect
	github.com/jonboulle/clockwork v0.2.2 // indirect
	github.com/josephspurrier/goversioninfo v0.0.0-20190209210621-63e6d1acd3dd // indirect
	github.com/json-iterator/go v1.1.12 // indirect
	github.com/klauspost/compress v1.15.14 // indirect
	github.com/mattn/go-colorable v0.1.12 // indirect
	github.com/mattn/go-isatty v0.0.14 // indirect
	github.com/miekg/dns v1.1.41 // indirect
	github.com/mitchellh/hashstructure v0.0.0-20170116052023-ab25296c0f51 // indirect
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
	github.com/modern-go/reflect2 v1.0.2 // indirect
	github.com/opencontainers/go-digest v1.0.0 // indirect
	github.com/opencontainers/image-spec v1.0.2 // indirect
	github.com/pierrec/lz4/v4 v4.1.17 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/prometheus/procfs v0.7.3 // indirect
	github.com/rcrowley/go-metrics v0.0.0-20201227073835-cf1acfcdf475 // indirect
	github.com/rogpeppe/go-internal v1.9.0 // indirect
	github.com/santhosh-tekuri/jsonschema v1.2.4 // indirect
	github.com/shirou/gopsutil v3.20.12+incompatible // indirect
	github.com/sirupsen/logrus v1.8.1 // indirect
	github.com/spf13/cobra v1.3.0 // indirect
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/urso/diag v0.0.0-20200210123136-21b3cc8eb797 // indirect
	github.com/urso/go-bin v0.0.0-20180220135811-781c575c9f0e // indirect
	github.com/urso/magetools v0.0.0-20190919040553-290c89e0c230 // indirect
	github.com/urso/sderr v0.0.0-20210525210834-52b04e8f5c71 // indirect
	github.com/xdg/scram v1.0.3 // indirect
	github.com/xdg/stringprep v1.0.3 // indirect
	go.elastic.co/apm v1.11.0 // indirect
	go.elastic.co/apm/module/apmelasticsearch v1.7.2 // indirect
	go.elastic.co/apm/module/apmhttp v1.7.2 // indirect
	go.elastic.co/ecszap v1.0.1 // indirect
	go.elastic.co/fastjson v1.1.0 // indirect
	go.uber.org/atomic v1.9.0 // indirect
	go.uber.org/multierr v1.8.0 // indirect
	go.uber.org/zap v1.21.0 // indirect
	golang.org/x/crypto v0.5.0 // indirect
	golang.org/x/net v0.5.0 // indirect
	golang.org/x/oauth2 v0.0.0-20211104180415-d3ed0bb246c8 // indirect
	golang.org/x/sys v0.4.0 // indirect
	golang.org/x/term v0.4.0 // indirect
	golang.org/x/text v0.6.0 // indirect
	golang.org/x/time v0.0.0-20210723032227-1f47c861a9ac // indirect
	golang.org/x/tools v0.1.12 // indirect
	google.golang.org/appengine v1.6.7 // indirect
	google.golang.org/genproto v0.0.0-20220426171045-31bebdecfb46 // indirect
	google.golang.org/grpc v1.46.0 // indirect
	google.golang.org/protobuf v1.28.0 // indirect
	gopkg.in/inf.v0 v0.9.1 // indirect
	gopkg.in/jcmturner/aescts.v1 v1.0.1 // indirect
	gopkg.in/jcmturner/dnsutils.v1 v1.0.1 // indirect
	gopkg.in/jcmturner/goidentity.v3 v3.0.0 // indirect
	gopkg.in/jcmturner/gokrb5.v7 v7.5.0 // indirect
	gopkg.in/jcmturner/rpc.v1 v1.1.0 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	howett.net/plist v1.0.0 // indirect
	k8s.io/api v0.21.1 // indirect
	k8s.io/apimachinery v0.21.1 // indirect
	k8s.io/client-go v0.21.1 // indirect
	k8s.io/klog/v2 v2.8.0 // indirect
	k8s.io/utils v0.0.0-20201110183641-67b214c5f920 // indirect
	sigs.k8s.io/structured-merge-diff/v4 v4.1.0 // indirect
	sigs.k8s.io/yaml v1.2.0 // indirect
)
```
</details>

**Comment by herry-go** [comment]
> I have this issue too. I receive:我也有这个问题。我收到：
> 
> ```
> # github.com/elastic/beats/v7/libbeat/processors/script/javascript
> ../../go/pkg/mod/github.com/elastic/beats/v7@v7.17.8/libbeat/processors/script/javascript/session.go:267:15: s.Runtime().RegisterSimpleMapType undefined (type *goja.Runtime has no field or method RegisterSimpleMapType)
> ```
> 
> My go.mod:

replace (
	github.com/Shopify/sarama v0.0.0-00010101000000-000000000000 => github.com/IBM/sarama v1.43.0
	github.com/dop251/goja_nodejs => github.com/dop251/goja_nodejs v0.0.0-20171011081505-adff31b136e6
)

Adding the above mod file can solve this problem
