### ISSUE TITLE
kinesis

### ISSUE THREAD

**Issue by Prakash-droid** [elastic/beats#16325]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 
- Operating System: 
- Discuss Forum URL:
- Steps to Reproduce:

**Comment by ph** [comment]
Hello @Prakash-droid, I am going to close this issue because there are not details concerning the problems you are having. If you are looking for help please use our forum at  https://discuss.elastic.co/c/beats and if you think you are having a bug feel free to open a new issue.
