### ISSUE TITLE
[docs] Update GCP content when feature is GA

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#16337]
The following issues/questions were not addressed in the beta-level docs that we added in https://github.com/elastic/beats/pull/16228.

When the feature is ready for GA, we should:

- [ ] Remove `beta[]` annotations.
- [ ] Consider recommending a longer timeout (seems like I had to change the timeout for all functions that I deployed). We might even consider changing the default.
- [ ] Clarify description  about the `trigger.service` setting (not clear how/why this is set)
- [ ] Add more info to `maximum_instances` setting. Does `0` setting mean unlimited?
- [ ] Consider removing the page "Export AWS CloudFormation template" because we cover that in the page about deployment (when we added the page about exporting, we didn't have the page about deployment).
- [ ] Clarify docs about deployment, specifically:
  - [ ] Is the ENABLED_FUNCTIONS env var still required, or only required for AWS?  (NOTES: When I tried to enable a function under gcp and package the function, I got a zip file containing a binary called  "functionbeat-aws" even though the function I enabled was a cloud function. The ENABLED_FUNCTIONS env var seems to be ignored for GCP. Is that expected? Does it still work for AWS?)
  - [ ] Should users deploying to GCP put a certificate in the zip file as documented for AWS?
  - [ ] Should we say more about the exported YAML file (giving users more specifics about what they need to change). My deployment failed with `errors: - code: RESOURCE_NOT_FOUND message: The type [google.cloud.functions.v1.CloudFunction] was not found.` It sounds like we are generated a YAML file with an invalid type or that maybe deployment with the file is not yet supported. For GA, we want to make sure this works correctly.

**Comment by kvch** [comment]
GCP functions will never be GA.
