### ISSUE TITLE
Add support to collects tags in RDS (AWS module)

### ISSUE THREAD

**Issue by tony2k84** [elastic/beats#16358]
**Describe the enhancement:**
AWS module - RDS metric set doesn't include tags. This is a very standard mechanism to include specific metadata for resources. All services discovered should have tags.

**Describe a specific use case for the enhancement or feature:**
Ex. our implementation keeps application name tied to a database (RDS) in the tags object in AWS. There is no way in metric beat to get that information.

**Comment by kaiyan-sheng** [comment]
@tony2k84 Thanks for reporting this issue. You are absolutely right for needing tags in rds metricset. I just created a PR to add this. Thank you!

**Comment by eedugon** [comment]
@kaiyan-sheng , for curiosity... will the PR provide the tags on the RDS events and also allow configuring the metricset to filter certain tags for the input too?

Like with other AWS metricsets where we can filter what to monitor via `tags_filter`.

**Comment by kaiyan-sheng** [comment]
Good question @eedugon, I'm planning to add `tags_filter` for RDS and EC2 metricsets together in a separate PR after this one is merged.

**Comment by tony2k84** [comment]
What is the timeline for tags PR for RDS.

Regards,
Abhishek Tanwar
________________________________

**Comment by kaiyan-sheng** [comment]
@eedugon Sorry I was thinking EC2 metricset needs the tags_filter as well. Turned out it already has it. So I will add tags_filter for RDS in this same PR. Thanks!

**Comment by tony2k84** [comment]
@kaiyan-sheng I am really looking for this to be implemented - any idea on the merge for this one?

**Comment by kaiyan-sheng** [comment]
@tony2k84 This PR just got merged into master branch. Sorry for the delay!
