### ISSUE TITLE
metricbeat couchdb module not working with couch 2.x

### ISSUE THREAD

**Issue by nerdvegas** [elastic/beats#16352]
metricbeat version: 7.5.2
couchdb version: 2.1.0
system: Linux, CentOS-7.4
discussion: https://discuss.elastic.co/t/metricbeat-couchdb-module-not-working/219094/3

The metricbeat couchdb module does not work for couchdb-2.x. This version has a different _stats response than 1.x, and the module is zeroing out all numeric values in its elastic docs.

On a related note, to get it working at all, you need to set the module's "hosts" entries to something like "localhost:5984/_node/_local/_stats". This is undocumented and confusing, as "hosts" does not suggest that you need to provide the stats endpoint there.

**Comment by sayden** [comment]
PR opened with fix https://github.com/elastic/beats/pull/16455
