### ISSUE TITLE
Impossible to downgrade filebeat version in kubernetes

### ISSUE THREAD

**Issue by dudicoco** [elastic/beats#16371]
We had filebeat v7.5.1 installed on a k8s cluster, when attempting to downgrade to v6.4.2 the following error appeared in the logs:
```Registry file path must be a file. /usr/share/filebeat/data/registry is a directory```

It seems that the directory structure is different between the two versions, making it not possible to downgrade to the older version.
We had to replace the nodes in order to get around this issue.

**Comment by andresrc** [comment]
Hi @dudicoco ! Can you please open a [discuss topic](https://discuss.elastic.co/) describing the issue? Thanks!
