### ISSUE TITLE
Beats HTTP API endpoint is not using the configured beat name

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#16381]
For confirmed bugs, please report:
- Version: 
- Operating System: 
- Discuss Forum URL:
- Steps to Reproduce: 

Change your Beat's name and enable the http server:
filebeat.yml:
```
[...]
name: notfilebeat
http.enabled: true
monitoring.enabled: true
```

Access the HTTP API and confirm that `name` is the host name instead of `notfilebeat`.

```
$ curl -XGET 'localhost:5066/?pretty'
{
  "beat": "filebeat",
  "hostname": "Adrian-Elastic.local",
  "name": "Adrian-Elastic.local",
  "uuid": "752e78bd-a8cb-4346-9f82-469265f8ef4c",
  "version": "8.0.0"
}
```

Looking at the code I see that the custom name is set at `(*Beat).launch` by the `InitWithSettings` call https://github.com/elastic/beats/blob/21e15609a7b2ca3d1a0ce17440510219629d2210/libbeat/cmd/instance/beat.go#L369

but the name provided by the http endpoint is set at https://github.com/elastic/beats/blob/21e15609a7b2ca3d1a0ce17440510219629d2210/libbeat/cmd/instance/beat.go#L175 just before calling `b.launch`.

**Comment by ma-hei** [comment]
Created a PR for this: https://github.com/elastic/beats/pull/16717
