### ISSUE TITLE
Metricbeat to support IAM Roles for Service Accounts

### ISSUE THREAD

**Issue by evilezh** [elastic/beats#16406]
I do refer to this section: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-aws.html#aws-credentials-config
When we run within kubernetes, then usually latest versions of aws sdk would automatically pick up EKS injected aws token for authentication. 
I did not try out as per link it describes exact few options available, rather than referencing to SDK. 

As we run a lot of things inside k8s, it would be great, if it could pick up authentication method described here: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Comment by kaiyan-sheng** [comment]
I believe this is implemented by https://github.com/elastic/beats/pull/17658. Will close this issue! Please feel free to comment if the implementation needs more improvement. Thank you!!

**Comment by smiklos** [comment]
> I believe this is implemented by #17658. Will close this issue! Please feel free to comment if the implementation needs more improvement. Thank you!!

Hi @kaiyan-sheng ,
The linked pr does not solve this issue. 

Normally, any recent version of the aws sdk would be able to resolve tokens and the role injected by EKS to a pod. What the pr implements is regular assume role support for which we still need permission on the workers to assume the role. 

I did try to setup a service account with metricbeat 7.6.1 and it does not pick it up. Perhaps a fallback is missing to the default credentials chain somewhere in the code?

**Comment by kaiyan-sheng** [comment]
Hi @smiklos, sorry I didn't make it clear, this code is planed to be in 7.8.0.

**Comment by smiklos** [comment]
> Hi @smiklos, sorry I didn't make it clear, this code is planed to be in 7.8.0.

But the the fix doesn't fix what this issue is all about, or does it? 
Will version 7.8.0 support EKS IAM Service accounts?

**Comment by aviau** [comment]
> Ideally, if none of the custom methods work, the code should fall back to the built in provider chain

Wondering if this was addressed?
