### ISSUE TITLE
Data path already locked by another beat

### ISSUE THREAD

**Issue by yodog** [elastic/beats#16407]
after upgrading from 7.5.1 to 7.6.0 my filebeat breaks with error `data path already locked by another beat`

i have two instances of filebeat running for a very long time, one reading a specific set of files and sending to logstash, and the other one reading another set of files and sending to elasticsearch.

could not find this breaking change on the docs below.

https://www.elastic.co/guide/en/beats/libbeat/7.6/breaking-changes-7.6.html
and
https://www.elastic.co/guide/en/beats/libbeat/7.6/release-notes-7.6.0.html

**Comment by yodog** [comment]
**filebeat.elasticsearch.yml**

```
filebeat.registry.path: registry.elasticsearch

processors:
- add_host_metadata:
    netinfo.enabled: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 1h

filebeat.modules:
- module: apache
  access:
    var.paths: ["/var/log/apache2/*/access.log"]
  error:
    var.paths: ["/var/log/apache2/*/error.log"]

output.elasticsearch:
  compression_level : 5
  hosts            : elastic-zmb-pool
  loadbalance       : true
  worker            : 2

```

**Comment by yodog** [comment]
**filebeat.logstash.yml**

```
filebeat.registry.path: registry.logstash

processors:
- add_host_metadata:
    netinfo.enabled: true

filebeat.inputs:
- type              : log
  enabled           : true
  exclude_files     : ['.gz$']
  fields_under_root : true
  tags              : ["zimbra"]
  paths:
    - /opt/zimbra/log/access_log.*
    - /opt/zimbra/log/audit.log
    - /opt/zimbra/log/mailbox.log
    - /opt/zimbra/log/nginx.log
    - /opt/zimbra/log/nginx.access.log
    - /opt/zimbra/log/sync.log
    - /var/log/zimbra.log

output.logstash:
  hosts             : elastic-zmb-pool
  loadbalance       : true

```

**Comment by ycombinator** [comment]
Hi, I see that you already posted your question on our discussion forums: https://discuss.elastic.co/t/data-path-already-locked-by-another-beat/219852/. Let's continue the conversation there. The Beats GitHub repository is intended for confirmed bugs and feature requests. Thanks!

**Comment by yodog** [comment]
@ycombinator 
it breaks current production environment with undocumented changes. 
could you please reconsider and reopen the issue?
the forum does not have the same appeal...

**Comment by yodog** [comment]
https://github.com/elastic/beats/pull/16424
https://github.com/elastic/beats/pull/16428
