### ISSUE TITLE
Filebeat - reading the registry to delete old logs

### ISSUE THREAD

**Issue by areller** [elastic/beats#16423]
I wonder whether there's a reliable way to tell when Filebeat finished consuming a log file, so that I could mark it for deletion.  

I thought about reading the `data.json` (registry file), but I was told in the forums that reading it during the runtime of Filebeat might be dangerous because Filebeat acquires an exclusive lock on that file.  

I was told instead I should rely on the fact that Filebeat will keep the file open as long as it still reads it, and mark closed files to deletion, but I think that it's not 100% reliable. What if filebeat crashed? All files will be closed regardless of whether they were processed or not.

Is there a way to actually read the filebeat registry during runtime? What about the `data.json.old` file? Is it safe to read during runtime?  

I am using Filebeat on a Windows Server by the way.

Thank you

**Comment by ycombinator** [comment]
Hi @areller, we use GitHub issues for enhancement requests and confirmed bugs. For questions, please use our discussion forums at discuss.elastic.co. Thanks!
