### ISSUE TITLE
Compiling filebeat for ppc64 h/w using go complier - issues

### ISSUE THREAD

**Issue by lemmeno** [elastic/beats#16433]
Hi, I am trying to build filebeat/metrics beat for power hardware (running RHEL v7) and go version go1.13.8 linux/ppc64le. However, when I run the make command - I see some issues as listed here:

https://discuss.elastic.co/t/compiling-filebeat-for-ppc64-h-w-using-go-complier-issues/219682

Reached out to elastic support and they suggested to open a case here. Any help in this regard is highly appreciated.

**Comment by lemmeno** [comment]
Any update on this one please?

**Comment by adammike** [comment]
Any update on this?
