### ISSUE TITLE
Include output directory/file

### ISSUE THREAD

**Issue by Tatsu-Kishi** [elastic/beats#16451]
**Describe the enhancement:**
Add an option to include an external output configuration file or directory, similar to input and modules.

**Describe a specific use case for the enhancement or feature:**
We need different output configurations between different zones and would like to reduce config redundancy for the zones, since everything else is the same or already modular.
This would also allow for an easier/faster switch between outputs too, like for debugging, without having to edit the configs themselves in case of an output.d/ directory.

If there will be commands included to enable an output, it could disable all other outputs that might be active to ensure only a single output is active - such a command could reduce user error too if accidentally two outputs are "active" resulting in an invalid configuration.

**Comment by urso** [comment]
Output reloading is currently not possible, and is unlikely to be implemented based on file reloading. The team is working an alternative solution for centrally managing Beats.

Alternatively to modifying the configuration file one can pass multiple configuration files to Beats using the `-c` flag. For example `filebeat -c /etc/filebeat/filebeat.yml -c /etc/filebeat/outputs.d/active.yml`. Having multiple files prepared one can just copy/rename/link the wanted file to `/etc/filebeat/outputs.d/active.yml` and restart the Beat. I hope this idea helps to workaround having to edit files a little.
