### ISSUE TITLE
Support alternative format(s) for config files instead of YAML

### ISSUE THREAD

**Issue by ZLightning** [elastic/beats#16457]
**Describe the enhancement:**
The docs for the config file format claim `Beats config files are based on YAML, a file format that is easier to read and write than other common data formats like XML or JSON.`

I would say that is a rather opinionated claim.  The problem with YAML is that it relies on whitespace.  Both tabs and spaces look the same to the eye, but they can throw off how the file is parsed.  That means it is NOT easier to read considering you can't validate it visually.

Both YAML and JSON, when parsed, should result in a compatible object representation, so there is no reason not to support both YAML and JSON based on the file extension.  Since JSON does not rely on whitespace characters, it is easier to read and parse.  It does require more typing because of quoting and bracketing, so that would make it harder to write.  I gladly accept the extra typing in order to have a predictable and visually readable format.

**Describe a specific use case for the enhancement or feature:**
configuration

**Comment by strawgate** [comment]
JSON is valid YML so you can just write your configurations in JSON. We do this today.
