### ISSUE TITLE
functionbeat 6.8 reference.yml manual shows ouput to kafka

### ISSUE THREAD

**Issue by chipzzz** [elastic/beats#16470]
Functionbeat 6.8 reference.yml contains kafka.output as an option while 7.6 does not. Is there a kafka output capability in 6.8 functionbeat?

https://www.elastic.co/guide/en/beats/functionbeat/6.8/functionbeat-reference-yml.html

**Comment by kvch** [comment]
Duplicate of https://github.com/elastic/beats/issues/11496
