### ISSUE TITLE
[Metricbeat] Reset statement stats in PosgtreSQL module

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#16530]
Currently the `PostgreSQL` module in Metricbeat while querying the `pg_stat_statements` view [doesn't reset the statement](https://github.com/elastic/beats/blob/master/metricbeat/module/postgresql/statement/statement.go#L62) view thereby resulting in stats between now and back when the server had reset the view. 

Some users find this confusing and would like the option to reset stats every time Metricbeat pulls the `statement` metrics.

**Comment by urso** [comment]
In general Metricbeat should not reset data on the system it collects data from by default. This can interfere with other tools consuming APIs/tables at the same time.

**Comment by andresrc** [comment]
The agreed approach will be to provide the capability to supply a custom query to fetch the metrics.

**Comment by jsoriano** [comment]
> The agreed approach will be to provide the capability to supply a custom query to fetch the metrics.

Custom queries are already possible with the [SQL module](https://www.elastic.co/guide/en/beats/metricbeat/7.7/metricbeat-module-sql.html).
