### ISSUE TITLE
Beat generator improvements

### ISSUE THREAD

**Issue by kvch** [elastic/beats#16555]
As the Beat generator is moved to use go modules instead of vendoring, there are still a few improvements:

- [ ] provide a better default value for selected beats revision, based on the version information provided by the source repository
- [ ] only copy contents of metricbeat if the selected type is metricbeat

Requires elastic/beats#16288

**Comment by kvch** [comment]
This issues is related: https://github.com/elastic/beats/issues/17033

**Comment by jlind23** [comment]
Closing it as beats generator is now deprecated.
