### ISSUE TITLE
Update Beats to Go 1.14

### ISSUE THREAD

**Issue by kvch** [elastic/beats#16566]
This issue is created to make sure all changes in go modules are addressed.

- [ ] remove configurable `-mod=vendor` option as Go automatically pick it up
- [ ] follow up changes in Beats generators
- [ ] update version in Dockerfiles
- [ ] update version in `.go-version`

**Comment by m1357** [comment]
This issue still persists and cannot build x-pack mods from source

**Comment by lasselj** [comment]
+1
