### ISSUE TITLE
ECS tracing fields should not have tracing.* prefix

### ISSUE THREAD

**Issue by shoustech** [elastic/beats#16567]
The templates that are currently generating the two fields:
- tracing.trace.id
- tracing.transaction.id

These fields are currently being listed in ECS 1.4 without the `tracing.*` prefix. So the fields should be:
- trace.id
- transaction.id

**Comment by andresrc** [comment]
Hi! Which beat / module is causing this issue for you?

**Comment by shoustech** [comment]
I have tested with:
- Auditbeat
-- Using auditd and file integrity module
- Metricbeat
-- Using system module
- Filebeat
-- Simple config looking at one file

In all of those beat templates the incorrect fields `tracing.trace.id` and `tracing.transaction.id` can be found in the template.

**Comment by shoustech** [comment]
The reason I think the template is being generated incorrectly is because the fields.ecs.yml file in libbeat does not have the `prefix` field that can be found in the ECS field definitions. From what I understand the prefix field is there to define what is prefixed before the field name. In all fields except the tracing fields and base fields the prefix is the same as the name of the group.

What I think is that the template generation is doing is using the group name + the field name to get the complete field name. This would work for every field except the tracing fields. The base fields are unaffected because they are not inside of a group like the tracing fields.

https://github.com/elastic/beats/blob/6816bb1065913b5ad000c0a9bf9c216d91efb3b6/libbeat/_meta/fields.ecs.yml#L3689-L3715

https://github.com/elastic/ecs/blob/feb6a46285b47745f333bd0098625c97a9fa75fd/generated/ecs/ecs_nested.yml#L7688-L7730
