### ISSUE TITLE
[libbeat] Proposal: Support autodiscover of containers running via podman

### ISSUE THREAD

**Issue by atoom** [elastic/beats#16589]
**Describe the enhancement:**
Starting from RHEL 8/CentOS 8 there is no official support for docker anymore (as I understand it) - instead Red Hat has replaced docker with a suite of new tools: podman, buildah, skopeo.

There are hacks to install docker-ce on RHEL 8/CentOS 8 but doing so is on your own risk. In cases where organizations are running production workloads in containers via docker and leveraging autodiscovery functionality in filebeat for log ingestion it would not be possible to upgrade to RHEL 8/CentOS 8 at the moment.

**Describe a specific use case for the enhancement or feature:**
Leveraging filebeat autodiscovery functionality to find and ingest logs from containers running via podman.

**Comment by dcode** [comment]
Just as a note, I recently ran across that in Podman 2.0, they officially supported a REST API that allows for this integration. Of specific interest, it offers a `compatibility` API that emulates the Docker API. I've had some success with some other tools to can interact with the Docker socket with this compat mode.

Reference: https://podman.io/blogs/2020/06/29/podman-v2-announce.html

**Comment by laconi51** [comment]
Hi,
We deploy podman instances on several of our servers. 
I would be very interested in this issue to centralize the logs by filebeat

:+1
👍

**Comment by silvan-talos** [comment]
👍🏻
