### ISSUE TITLE
[CI] add a packaging stage to the pipeline

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/beats#16603]
add a new pipeline stage to run the packaging process as we make in the packaging job. In the process, we can see if we can fix the Mac OS packaging.

https://beats-ci.elastic.co/job/elastic+beats+master+package/

**Comment by andrewkroh** [comment]
@kuisathaverat Looks like we are hitting a timeout (max running time) for this [job](https://beats-ci.elastic.co/job/Beats/job/packaging/job/master/). Probably the simplest solution is to increase the maximum running time. But another solution would be packaging each Beat in parallel (`mage package`).

**Comment by kuisathaverat** [comment]
@andrewkroh I saw the timeout, I am trying to parallelize the thing, I started by selection platforms but the PLATFORMS env var seems ignored. I will explore the option to build beats separately
