### ISSUE TITLE
logstash bulk_max_size only 1024 by default in 1.x releases 

### ISSUE THREAD

**Issue by urso** [elastic/beats#1662]
by default bulk_max_size for logstash is still 1024, but should be 2048.

Workaround: Set bulk_max_size for logstash output plugin.

**Comment by ruflin** [comment]
As part of this, also introduce `bulk_max_size` as confg variable in `libbeat.yml` under Logstash. Currently it is missing.

**Comment by tsg** [comment]
#1828 was merged.
