### ISSUE TITLE
[Auditbeat] Unable to get packages related data

### ISSUE THREAD

**Issue by samoz83** [elastic/beats#16661]
I keep getting the below from the System module of Auditbeat in relation to packages information.

`failed to get packages: error getting DEB packages: error converting 25G to int: strconv.ParseUint: parsing "25G": invalid syntax`

For confirmed bugs, please report:
- Version: Auditbeat 7.6.0
- Operating System: Ubuntu 18.04.4
- Discuss Forum URL: https://discuss.elastic.co/t/system-module-packages-error/214448/2
- Steps to Reproduce: Install standard Auditbeat config

**Comment by rvillablanca** [comment]
Looking in two files of some friends `/var/lib/dpkg/status`  (I don't have it because I use Arch), none of them have the line `Installed-Size:` with `G` or any other non-numeric character so, this could be even an invalid file I think

**Comment by samoz83** [comment]
Ah I wasn't sure what file it was looking at, it does seem to be a random package that someone has put into our apt repos. I'll pull the package and fix it on my side. Thanks

**Comment by adriansr** [comment]
Reopened as this is an issue users are experiencing from time to time.
