### ISSUE TITLE
[Metricbeats] Diskio is failing on DeviceIoControl function call on windows 10 IoT x32 (1809) and windows 7 Embedded x32.

### ISSUE THREAD

**Issue by yaroslavmamrokha** [elastic/beats#16680]
DISKIO ioCounter function is constantly failing with error "The parameter is incorrect" during DeviceIoControl call on Windows environment.

Issue is reproducible on Windows 10 IoT x32 and Windows 7 Embedded.
This issue is related only to x32 version of metricbeat service.

To reproduce issue you need:
- x32 build of metricbeats
- default configuration with enabled DISKIO
- Windows 10/7 x32 or you can check also on x64.

PR with more information in comments about issue:
https://github.com/elastic/beats/pull/16553

**Comment by narph** [comment]
@yaroslavmamrokha , I was able to reproduce the issue on Windows 7, 32 bit as well. 
It looks like DeviceIoControl() ends up failing with `ERROR_INSUFFICIENT_BUFFER` (The data area passed to a system call is too small). The memory layout is indeed different for 32 bit vs 64 bit.
Adding the alignment as in your PR seemed to clear the issue.
I would suggest in this case, defining the `diskPerformance` struct in 2 different files ex. `disk_performance_386.go` (with alignment) and `disk_performance_amd64.go` (without alignment) so the go compiler will pick up the corresponding version depending on the CPU architecture.
Let us know if you want to open a separate PR for this, else we can help.

**Comment by yaroslavmamrokha** [comment]
@narph 

Great thanks, I'm not familiar with Go. I guess it's better you guys to do this, so that it could be in a valid manner. thanks!

**Comment by yaroslavmamrokha** [comment]
@narph 
I've also tested this fix with x64 bit version, and some how it was working. I guess this is something related to GoLang. Seems like they try to align memory blocks based on arch. So if it is x32 they will align based on x32 arch (to 4 bytes) and if this is on x64 arch (to 8 bytes). So fix is basically, adding alignment to x32 version, and overwriting alignment on x64 version. But guess this should be tested.
