### ISSUE TITLE
Support for kubernetes Metrics Server instead of kube-state-metrics

### ISSUE THREAD

**Issue by iahmad-khan** [elastic/beats#16682]
I am not sure if all kubernetes installations are doing metrics-server by default but i have installed about 50 clusters so for and by default there is metrics-server installed and I dont want to install another metrics thing like kube-state-metrics, is there a possibilty to use metrics-server instead of kube-state-metrics.

https://github.com/elastic/helm-charts/pull/289

thanks

**Comment by andresrc** [comment]
Somewhat related (this one focuses on kubelet): https://github.com/elastic/beats/issues/12792

**Comment by blakerouse** [comment]
Looking into this metrics-server is not a replacement for kube-state-metrics. Both serve a very different purpose.

**kube-state-metrics**: Provides metrics on the state of all objects in kubernetes. Example the creation of a new daemonset would be a metric exposed. It simply listens to the kubernetes event API and records metrics based on those events.

**metrics-server**: Provides usage metrics for nodes and pods in the cluster. This would be more of a replace for running metricbeat as a daemonset on all the nodes (would not recommend that, as metricbeat will be more detailed system metrics). It could be a replacement for having metricbeat connect to kubelet on each host to gather metrics.

**Comment by blakerouse** [comment]
Being that these are used for different use-cases and #12792 already documents the migration to using metrics-server, I am going to close this issue.
