### ISSUE TITLE
Remove libbeat/outputs/transport

### ISSUE THREAD

**Issue by urso** [elastic/beats#16728]
The libbeat/outputs/transport package has been superseded by the libbeat/common/transport package, with the common/transport package being supposed to have sub-packages per use-cases/service. The libbeat/output/transport package mostly aliases libbeat/common/transport/tlscommon and should be removed.

**Comment by ycombinator** [comment]
Thanks for creating this issue! I ended up doing much of this work as part of #16150. I will pull it out of that very large PR and make a separate PR for it. Then #16150 can simply depend on the new, smaller PR.
