### ISSUE TITLE
[Agent] Enforce TLS connection for enrolling or checking in.

### ISSUE THREAD

**Issue by ph** [elastic/beats#16736]
Currently, it's possible to enroll the Agent without using a TLS connection, you only need to use the "HTTP" protocol when enrolling. Since the Agent can be effectively controlled by a remote kibana instance we want to enforce the requirement of TLS and refuse to enroll if the Kibana endpoint doesn't have TLS enabled.

**It should fail when using the following to enroll**
```
agent enroll http://localhost:5901 <enroll_key>
```

**You can disable the TLS requirement by using the `-insecure`, using this flag should warn the user that the connection is **insecure** and this flag should not be used in production.**

```
agent enroll -insecure http://localhost:5901 <enroll_key>
```

**Comment by michalpristas** [comment]
are we verifying cert in any way? like we have process defined elsewhere comparing cert hash? or will we rely on standard ways

**Comment by ph** [comment]
@michalpristas We actually rely on the standard way, the _ca_sha256_ pins check when provided is done as a callback after the chain was created. 

What we want to do is without the _-insecure_  flag set we refuse to connect to the remote host if TLS is not used. I think it will be used in two scenario:

1. For us as developper, because dealing with TLS in testing is kinda a pain.
2. Someone that wants to _try_ Fleet/Agent but not in production.


This is why when the _-insecure_ flag is used we want to be noisy in the terminal to inform them about the risk. I believe on the Kibana side they wanted to add a banner to warn if fleet was enabled without TLS.

**Comment by ph** [comment]
@blakerouse could you take a look at this to unblock our integration tests?

**Comment by ph** [comment]
@blakerouse Could you take a look?

**Comment by blakerouse** [comment]
@ph looking into it
