### ISSUE TITLE
[Metricbeat] Support systemd version from RHEL 7 for system service metricset

### ISSUE THREAD

**Issue by hochraldo** [elastic/beats#16757]
RHEL 7 uses systemd version 219. Therefore the system service metricset does not work as the `ListUnitsByPatterns` (see https://github.com/elastic/beats/blob/d89675fc3bc4f6a8e72671ed887bf96ad8ca159b/metricbeat/module/system/service/service.go#L80)  method call did not exist in that version.

It seems that this method call was introduced in a later version of systemd:  https://github.com/systemd/systemd/commit/313fe66fbd0cd3d62566edece7944d6cf45b1b21

As an alternative `ListUnitsFiltered` could be used, as this method call is available since earlier versions of systemd and provides similar results to my understanding.

RHEL 7 is a widely used Linux system in enterprises which will get "normal" support until 30 June 2024.

**Comment by jsoriano** [comment]
Hey @hochraldo, thanks for reporting, I agree that it would be nice to support RHEL 7.

cc @fearful-symmetry

**Comment by fearful-symmetry** [comment]
I'll see what I can do. I agree, we should support this. Might require some hacking depending on what our vendored library supports.

**Comment by nabeel-shakeel** [comment]
@fearful-symmetry: service metricset not generating any event on CentOS after this fix.
