### ISSUE TITLE
[Metricbeat] System service allow to filter processes

### ISSUE THREAD

**Issue by hochraldo** [elastic/beats#16753]
Currently the processes to list can only be filtered by state (`service.state_filter`). In addition filtering by "module" name should be supported.

This module name pattern is hardcoded at the moment:
`	units, err := m.conn.ListUnitsByPatterns(m.cfg.StateFilter, []string{"*.service"})`

This feature would allow to list services that are running under the same user/group and would not need "superuser" power.

**Comment by jsoriano** [comment]
cc @fearful-symmetry
