### ISSUE TITLE
Winlogbeat missing MSI installer documentation

### ISSUE THREAD

**Issue by dcode** [elastic/beats#16773]
I attempted to follow the instructions for [Getting Started with Winlogbeat](https://www.elastic.co/guide/en/beats/winlogbeat/7.6/winlogbeat-getting-started.html) and was confused when I tried to find the powershell script.

It turns out the service is installed by the MSI installer automatically, but there's some additional information that has changed.

- The install path is now `C:\Program Files\Elastic\Beats\<version>\winlogbeat\`
- The configuration file should now be created at `C:\ProgramData\Elastic\Beats\winlogbeat\winlogbeat.yml`
- Should probably add new steps how to test the config
- Once configured, then you can start the service via command line or from `services.msc`

For confirmed bugs, please report:
- Version: 7.6.0
- Operating System: Windows Server 2016
- Steps to Reproduce: See above

**Comment by softengchick** [comment]
I had a customer recently complain about this to me.  So seconding that this needs an update.

**Comment by ChrisAlambik** [comment]
I confirm that it is not useful to split the software in 2 folders. Actually we are using the zip version to avoid it

**Comment by tomgilson08** [comment]
Has this documentation been created yet? Still can't find a good resources for configuring winlogbeat after installing it with the Windows MSI package.

**Comment by faurkaurage** [comment]
Greetings All

I'm not sure if much has been added to the Windows MSI documentation but I do hope they update it soon as the MSI could be a faster and easier way to deploy beats on a system. One thing that the MSI did not mention, was that if you simply copy the winlogbeat.examply.yml to winlogbeat.yml it is missing one key field that needs to be there to work. Under the 'OUTPUT' section you can select to send your output to either Elasticsearch or Logstash and now you need to include 
  "enabled: True"  <-- place this under the output you want to use

 If I don't explicitly put this then the beat is not working....took me a minute to figure this out so hope it helps someone else

![image](https://user-images.githubusercontent.com/87826802/156416270-fa188b41-2d17-4c30-8f3d-ed412ddce30c.png)
