### ISSUE TITLE
Implement backoff for Kafka output

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#16777]
**Describe the enhancement:**

Currently the Kafka output does not support any sort of backoff for publishing events in the situation where the Kafka broker might've temporarily gone away. We should add support for this, similar to what the Redis and Elasticsearch outputs.

**Describe a specific use case for the enhancement or feature:**

To prevent the Kafka output aggressively retrying to publish events to a Kafka broker that might have temporarily gone away.

**Comment by ycombinator** [comment]
Potentially useful for implementation:

https://github.com/elastic/beats/blob/95626b8f1690344312c0831ab2bdcbccffe4d089/libbeat/outputs/kafka/config.go#L256

https://github.com/Shopify/sarama/blob/58123455d1a70c7f438871597d9a1715462e5d1c/config.go#L218-L229

**Comment by ycombinator** [comment]
The backoff options I found in Sarama (the Kafka client we use in Beats) for the consumer are here: https://github.com/Shopify/sarama/blob/4ba4c2f6cb7a3aa9ab9151ecff3cac1319801dfd/config.go#L284-L291. 

cc: @faec @urso

**Comment by ycombinator** [comment]
@faec @urso See the link in the previous comment for backoff/retry options for the producer in Sarama.

**Comment by urso** [comment]
BackoffFunc is new. We should give it a try. From experience the 'Backoff' setting did not always work correctly, which did lead to us using 100% CPU (depending where an error occured and if the internal write buffer is full). Not sure if this has been improved.

**Comment by ZHumphries** [comment]
Just experienced this issue. Someone changed kafka to use authentication and all winlogbeat instances on every server spiked to 100% cpu once the buffer was full. Fortunately the winlogbeat rollout wasnt complete so vmware didnt grid completely to a halt.

**Comment by toby-sutor** [comment]
It's worth mentioning that a temporary workaround is to add the Kafka IPs to the local /etc/hosts file of the Beats nodes to relieve the DNS servers until this has been implemented.
