### ISSUE TITLE
Missing Suite and Origin in Beats Release file

### ISSUE THREAD

**Issue by ThomasdOtreppe** [elastic/beats#1679]
I've been using Ubuntu automatic updates on my servers and it has been working fine for a few years. I'd like to be able to do the same with Filebeat. I found a [post on askubuntu.com explaining](https://askubuntu.com/questions/87849/how-to-enable-silent-automatic-updates-for-any-repository) how to do it.

It tells to look into ```/var/lib/apt/lists/``` directory and at the files ending with 'Release'. I'm checking beats repo file and unfortunately, it doesn't contain Origin and Suite is empty which is a problem.

See elastic/elasticsearch#16488 for the same problem with Elasticsearch and elastic/kibana#7030 for the same issue with Kibana.

**Comment by tsg** [comment]
Pinging @andrewkroh, he set up the repos.

**Comment by andrewkroh** [comment]
When we release 5.0 GA, the repository will have `Origin: elastic` and `Suite: stable` in the APT Release file. This will apply to each of the projects you mentioned.
