### ISSUE TITLE
[Filebeat] PANW Module - Pass-through other log types

### ISSUE THREAD

**Issue by jvernon214** [elastic/beats#16815]
**Describe the enhancement:**
Currently the Filebeat PANW module discards events that are not of type Traffic or Threat.  This module should minimally not discard the non threat/traffic logs as they're still useful.

**Comment by nanjum88** [comment]
@andrewkroh - I created a similar ticket on Jan 15h, 2020. https://github.com/elastic/beats/issues/15603

CC: @mukeshelastic
