### ISSUE TITLE
Let's put the "reference" back into reference docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#16821]
The Beats documentation has grown organically over time as the list of Beats has exploded. Right now, our "reference" docs are a Frankenstein-like combination of installation, how-to, and reference. As we build out solution-focused documentation that addresses specific use cases, we should tease non-reference content out of the reference guides, when possible. This will:

* Make it easier for developers to maintain the content.
* Make it easier for users to find reference info.
* Help us avoid duplicating content in more than one place.

As part of this effort, we should optimize the content for readability, making it easier to scan and retrieve.

- [x] Add shorter nav titles.
- [x] Sort lists alphabetically, when feasible.
- [ ] ~Make sure overview lists are generated and not manually maintained.~
- [ ] ~Organize files into sub-folders (for maintainers).~

UPDATE 9/16/2020 Given the planned doc redesign, I don't plan to move forward with the remaining changes. So I will close this issue as completed.

**Comment by dedemorton** [comment]
@bmorelli25 FYI as this will probably affect APM.

**Comment by bmorelli25** [comment]
Looking at the PR you opened, it's amazing how much the shorter nav titles alone really clean things up. These changes will definitely impact the APM Server documentation, and I'm happy to help however I dcan.
