### ISSUE TITLE
[Metricbeat] Windows msi installer file, overwrites system.yml in modules.d

### ISSUE THREAD

**Issue by StefanSa** [elastic/beats#16865]
hi there,
first of all thanks for the Windows msi file, it makes it much easier to roll out the beats with it.
Since version `7.6.0`, the problem is that the installation file ignores and overwrites the existing `system.yml` in the `modules.d` folder.

For confirmed bugs, please report:
- Version: 7.6.0
- Operating System: Windows 2016

**Comment by jsoriano** [comment]
Hey @StefanSa,

Thanks for reporting! Take into account that MSI installer is currently beta.

@ygel could you help with this?

**Comment by ygel** [comment]
Hello @StefanSa, current beta doesn't support upgrades yet.

**Comment by StefanSa** [comment]
privjet / hi  @ygel,
thanks for the feedback.
the upgrade from 7.6.0 to 7.6.1 went without problems except for this error.
not too bad for a beta
