### ISSUE TITLE
Export generates wrong default field, lot of "text" duplicities

### ISSUE THREAD

**Issue by vbohata** [elastic/beats#16891]
I noticed a lot of versions of beats generate wrong index templates. For example in 7.6.1 using "./filebeat export template" I get this in default_field section:

...
          "process.args",
          **"text",**
          "process.executable",
          "process.hash.md5",
          "process.hash.sha1",
          "process.hash.sha256",
          "process.hash.sha512",
          "process.name",
          **"text",
          "text",
          "text",
          "text",
          "text",**
          "process.thread.name",
...

It looks like it takes field type instead of field name for text fields ...

**Comment by andresrc** [comment]
Hi! Thank you for creating the issue. We use GitHub issues for confirmed bugs, can you open a [discuss topic](https://discuss.elastic.co/c/beats/) first?

Thanks!
