### ISSUE TITLE
[Functionbeat] Allow to specific the parellization factor for Kinesis.

### ISSUE THREAD

**Issue by ph** [elastic/beats#16901]
When you create a function that monitors a Kinesis stream, the way by default that Kinesis operates is to create a lambda per shards. When you have a lot of data this causes the function to lag behind the data.

The solution is to change the [parallelization factor](https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-parallelization-factor-for-kinesis-and-dynamodb-event-sources/) and this [post](https://aws.amazon.com/blogs/compute/new-aws-lambda-scaling-controls-for-kinesis-and-dynamodb-event-sources/). From their documentation:

> Now you can specify the number of concurrent batches that Lambda polls from a shard via a Parallelization Factor from 1 (default) to 10. For example, when Parallelization Factor is set to 2, you can have 200 concurrent Lambda invocations at maximum to process 100 Kinesis data shards. This helps scale up the processing throughput when the data volume is volatile and the IteratorAge is high.

**Comment by ph** [comment]
ping @kvch

**Comment by ravinaik1312** [comment]
Assigning this to myself
