### ISSUE TITLE
Support CgroupsV2 in processors and Metricbeat

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#16958]
Some Linux distros are starting to adopt CgroupsV2 and the container runtimes are being updated as well. Beats should be updated to support reading data from CgroupsV2. This affects Metricbeat's system/process metricset and some of the `add_*_metadata` processors that try to associate processes to container IDs.

- https://fedoraproject.org/wiki/Changes/CGroupsV2
- https://github.com/opencontainers/runc/pull/2113
- https://github.com/opencontainers/runtime-spec/issues/1002

**Comment by fearful-symmetry** [comment]
Fedora has adopted it, as of F31: https://fedoraproject.org/wiki/Changes/CGroupsV2

I'll spin a VM sometime and test out what happens.

**Comment by fearful-symmetry** [comment]
After a quick test, I don't see any errors being thrown with the system/process or system/process_summary metricsets.

**Comment by andrewkroh** [comment]
@fearful-symmetry Did you get any cgroup metrics from system/process for processes that have cgroups applied?

**Comment by fearful-symmetry** [comment]
@andrewkroh I'm mostly looking for errors at this point. Testing this with docker metadata is functionally moot, as the only way to get docker working is to enable enable cgroupv1 backwards compatibility. What other use cases are there? Should I try manually adding PIDs to cgroups or something?

**Comment by andrewkroh** [comment]
> Should I try manually adding PIDs to cgroups or something?

Yeah, either do that or use systemd to do it for you. systemd supports v2 on fedora31 from what I've read. So maybe install a beat RPM (or some other service) then edit the service unit file to add some [resource constraint](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html).

**Comment by exekias** [comment]
For inventory:

`add_docker_metadata` will also be affected if Docker adds support for v2, check https://github.com/elastic/beats/blob/1d36da75c3b73cc075cd2cdb15053e529de3337b/libbeat/processors/add_docker_metadata/add_docker_metadata.go#L219-L266. 

Also `add_process_metadata` after this pr: https://github.com/elastic/beats/pull/15947

**Comment by eyalkoren** [comment]
For the record - cgroup (v1 and v2) memory metrics issue in APM - https://github.com/elastic/apm/issues/291.
See if you can use anything when implementing and let the APM know if you think something can be done better.

**Comment by fearful-symmetry** [comment]
This is a good reminder, this is on the board for 7.15.

**Comment by graphaelli** [comment]
@fearful-symmetry is this one done now?  It seems to have been moved on the project board without closing the issue.  If it is complete, can you point us at the implementation?

**Comment by fearful-symmetry** [comment]
@graphaelli , yep, must have forgotten. Implementation is here: https://github.com/elastic/beats/tree/master/libbeat/metric/system/cgroup/cgv2

**Comment by fearful-symmetry** [comment]
Just going to close this, since it looks like the issue itself was limited to the basic groupsv2.
