### ISSUE TITLE
Updating the tested/supported version of Filebeat's Kafka input/output for more recent versions

### ISSUE THREAD

**Issue by hemantmalik** [elastic/beats#16960]
**Documentation for Filebeat's output currently state supported version up to 2.1.0. This version was released back in Nov, 2018.:**

**Supporting more recent versions to keep up with deployed Apache kafka versions**

**Comment by JohnRoesler** [comment]
Looks like docs say up to `2.0.0` are further versions of kafka supported? https://www.elastic.co/guide/en/beats/filebeat/master/kafka-output.html#_version_2

My broker runs `2.2.1`

**Comment by userguy** [comment]
any update on this thread ,Can weuse filebeat for kafka 2.4.x
