### ISSUE TITLE
Find kubernetes resource's root controller when including kubernetes metadata

### ISSUE THREAD

**Issue by flaper87** [elastic/beats#16974]
The current implementation of the `add_kubernetes_metadata` processor includes the `Pod` metadata and the immediate controller that is returned in the `OwnerReferences` list. This information is quite useful but it is not enough.

As part of https://github.com/elastic/infra/pull/17976 we added the option to compute "unique" service names for the events coming from a `filebeat` process running within a POD. Ideally, the service name would be unique per deployment but we don't have that information for events coming from a POD because the controller of the pod is the `replicaset`.

The service name we are computing right now is unique during the lifespan of the replicaset contorlling the PODs. Ideally, this shouldn't change after a rollout or upgrade, which is what using the deployment name would give us.

**Describe the enhancement:**

It would be great to have `libbeats` resolve the entire chain of controllers and return their metadata, which gives a better way to group events coming from pods based on the entire chain of resource controllers.

**Describe a specific use case for the enhancement or feature:**

* Create unique service names from llama: https://github.com/elastic/infra/pull/17976
* Have full context of the application environment 
* Create metrics, and visualizations for events coming from child resources using their parent resources.

**Comment by flaper87** [comment]
FWIW, I am happy to work on this myself (I actually already started playing around with it a bit) if someone would be willing to provide support while I do it. I'm not super familiar with the codebase or `libbeats` common practices :smile:

**Comment by blakerouse** [comment]
@flaper87 I agree with this, I have noticed the same behavior. When using a `Deployment` the event for the `Pod` does not provide that information just the `ReplicaSet` that is created by the `Deployment` and you cannot tell from the event what kind was ultimately responsible for the event.

**Comment by flaper87** [comment]
@blakerouse thanks for the feedback. I'm working on a PR now but I'm unsure whether I'm implementing this the best way possible. :smile: We'll see when it is ready for review. :+1:

**Comment by ChrsMark** [comment]
Should be covered by https://github.com/elastic/beats/pull/23610. Closing for now.
