### ISSUE TITLE
Filebeat decode_cef parser error with \n\r chars in message

### ISSUE THREAD

**Issue by chicco27** [elastic/beats#16995]
The filebeat decode_cef function doesn't skip the new lines chars if are present into message field.

es.
`event.original: "CEF:0|Trend Micro|Deep Security Manager|12.0.393|771|Contact by Unrecognized Client|6|src=10.41.128.199 suser=System msg=A connection to Deep Security Manager was initiated by a client not identifiable as a managed computer: 10.41.130.142:63944. Either the client is not a computer managed by Deep Security, or a secure communication channel could not be established.\n\nAgent GUID or virtual ID did not map to any Hosts. The following endpoint information was provided.\r\n\r\nHTTP Headers:\r\nx-dsa-time: 1584092734\r\ncontent-length: 202\r\nx-dsa-capabilities: 1092777293\r\nx-dsm-minimum-dsm-version: 9.5.0\r\ncontent-encoding: deflate\r\nx-dsm-notifications: GetInterfaces\r\ncontent-type: text/plain; charset\="UTF-8"\r\nplatform: Windows;10;0;14393;;x86_64;400;3\r\nx-dsa-listenport: 4118\r\nuser-agent: Trend Micro Deep Security Agent (10.0.0.2888)\r\n\r\nHost Info:\r\nhostname: test02.local\r\nbios-uuid: 44164530-FAF8-734C-81DF-1D5AC071065B\r\ndomain: LOCAL\r\nhostname-nb: TEST02\r\nhostname-id: {b70482c0-b44c-4221-96df-4dc55f04177e}\r\nhostname-canonical: local/LOCAL-Dienste/TGW/TEST02\r\n TrendMicroDsTenant=Primary TrendMicroDsTenantId=0" , 
error.message: "malformed value for msg at pos 369"
`

For confirmed bugs, please report:
- Version: 7.5.X
- Operating System: Windows Server 2019
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-7-4-decode-cef-getting-error-malformed-value/202469 
- Steps to Reproduce: 
when a device send a message with \n or \r chars the decode function rise-up 'malformed value for xx at pos xxx'

**Comment by nerophon** [comment]
@jamiehynds a user has hit this recently in a large use-case; is there any chance it can be prioritised so that it gets fixed? Thank you.

**Comment by andrewkroh** [comment]
I tested with the CEF message and I can reproduce. It chokes at the first `\n`.

```json
  {
    "source": {
      "ip": "10.41.128.199",
      "user": {
        "name": "System"
      }
    },
    "@timestamp": "2021-11-12T19:11:22.635Z",
    "cef": {
      "severity": "6",
      "version": "0",
      "device": {
        "product": "Deep Security Manager",
        "vendor": "Trend Micro",
        "version": "12.0.393",
        "event_class_id": "771"
      },
      "extensions": {
        "sourceUserName": "System",
        "TrendMicroDsTenant": "Primary",
        "TrendMicroDsTenantId": "0",
        "sourceAddress": "10.41.128.199"
      },
      "name": "Contact by Unrecognized Client"
    },
    "error": {
      "message": "malformed value for msg at pos 369"
    },
    "event": {
      "code": "771",
      "severity": 6
    },
    "message": "Contact by Unrecognized Client",
    "observer": {
      "product": "Deep Security Manager",
      "vendor": "Trend Micro",
      "version": "12.0.393"
    }
  }
```

To quote the spec:

https://community.microfocus.com/cfs-file/__key/communityserver-wikis-components-files/00-00-00-00-23/3731.CommonEventFormatV25.pdf

> Multi-line fields can be sent by CEF by encoding the newline character as \n or \r. Note that multiple lines are only allowed in the value part of the extensions.

I think the allowed chars in the value needs adjusted at:

https://github.com/elastic/beats/blob/d9d000d1b31069bb1e7c880e2d221e6ff9411c5a/x-pack/filebeat/processors/decode_cef/cef/cef.rl#L127

**Comment by lucabelluccini** [comment]
As a side note - the default size of such message extraction can easily pass default 1024 of `ignore_above`.

**Comment by andrewkroh** [comment]
@lucabelluccini Are you reporting that there's a problem with the `decode_cef` processor with respect to `ignore_above`? Or is this a separate issue? What field specifically are you referring to?

**Comment by lucabelluccini** [comment]
I've seen users get an `event.original` message being in `_ignored` once indexed because of the length of the event at source. But I think we're covering the problem on https://github.com/elastic/ecs/issues/105

**Comment by andrewkroh** [comment]
That won't affect the operation of the `decode_cef` processor in any way. It runs before the data is sent from the Beat.

**Comment by lucabelluccini** [comment]
Yes I am aware of that. I am mentioning it because users running in this parsing issue (before reaching ES) will end up on potentially the need to fix the event on Elasticsearch side and they'll need to use `event.original`.
The fields are limited to `1024`, which means they'll be able to fix them via reindexing or update by query, but they'll not be able to search on the `event.original` field if it exceeds 1024 of length. 

I agree, let's keep this issue focused on`decode_cef` . Sorry for the noise.
