### ISSUE TITLE
Zeek Module to work with Kafka Input

### ISSUE THREAD

**Issue by Shak3** [elastic/beats#17024]
**Describe the enhancement:**
Configure filebeat modules to work with kafka input. As long as logs are being shipped in raw format that Filebeat would read from.
**Describe a specific use case for the enhancement or feature:**
Currently using zeek for traffic networks 5Gbps++. Prior to the increase in traffic monitoring Filebeat was working ok~, as traffic started to increase Filebeat could not keep up with the amount of Logs zeek kicks out.  We output to kafka from zeek and are currently doing manual conversions in logstash currently. This could also be done for other modules, We haven't had an issue yet with suricata, but that is because it is tuned as only an IDS at this time. If we were to move away from zeek and use all of Suricatas features I would guess it would be the same thing at high traffic throuputs.

**Comment by kvch** [comment]
Modules can be configured to use different inputs using the option named `input` under the modules.

Also, please do not post questions or issues on GH without being asked to. If you have a possible bug or enhancement request, go to our Discuss forum: https://discuss.elastic.co/c/beats
