### ISSUE TITLE
GenerateCustomBeat returns error for missing github.com/elastic/beats/v7

### ISSUE THREAD

**Issue by andrew-expanse** [elastic/beats#17033]
I'm attempting to create a new custom beat but am hitting some errors when using the mage GenerateCustomBeat command.

For confirmed bugs, please report:
- Version: (master branch) 
- Operating System: macOS 10.15.3
- Discuss Forum URL: https://discuss.elastic.co/t/generatecustombeat-returns-error-for-missing-github-com-elastic-beats-v7/223785
- Steps to Reproduce: 
1. Follow Environment setup steps from https://www.elastic.co/guide/en/beats/devguide/current/beats-contributing.html#setting-up-dev-environment
2. Run `mage GenerateCustomBeat` to create a custom beat
3. Error encountered for `Error: expected 1 line, got 0 while looking for github.com/elastic/beats/v7`

Logs:
```
$ mage GenerateCustomBeat
Enter the beat name [examplebeat]: testbeat
Enter your github name [your-github-name]: andrewexpanse
Enter the beat path [github.com/andrewexpanse/testbeat]:
Enter your full name [Firstname Lastname]: Andrew Scott
Enter the github.com/elastic/beats revision [master]:
go: creating new go.mod: module github.com/andrewexpanse/testbeat
go get github.com/elastic/beats/v7@master: module github.com/elastic/beats@master found (v7.0.0-alpha2.0.20200224095451-b0c600a28dbc+incompatible), but does not contain package github.com/elastic/beats/v7
Error: error while getting required beats version: running "go get -d -u github.com/elastic/beats/v7@master" failed with exit code 1```

**Comment by lrettig** [comment]
I ran into the same issue on macOS 10.15.4, go version 1.14.2 installed using homebrew. I was able to work around it by downgrading go using [these instructions](https://blog.notmyhostna.me/posts/downgrade-go-installed-with-homebrew/) as [described in the forum post](https://discuss.elastic.co/t/generatecustombeat-returns-error-for-missing-github-com-elastic-beats-v7/223785/10):

```
> brew install go@1.13
> brew unlink go
> brew link --force go@1.13
```
