### ISSUE TITLE
Run 'yum update' during container build

### ISSUE THREAD

**Issue by joshbressers** [elastic/beats#17035]
The various beats containers are using centos:7 as the baseimage. This image hasn't been updated in dockerhub for some time now.
https://github.com/CentOS/sig-cloud-instance-images/blob/d9560a37644faaeac50162582f82a5ee920dc37e/docker/Dockerfile

We should ensure we run 'yum update' during the container build to grab the latest updates from Centos.

**Comment by andrewkroh** [comment]
To address this, the two Dockerfile templates in https://github.com/elastic/beats/tree/master/dev-tools/packaging/templates/docker need be updated.

**Comment by andrewkroh** [comment]
PR: https://github.com/elastic/beats/pull/17037
