### ISSUE TITLE
Server 2003 - PID’s not recognized - Topbeat

### ISSUE THREAD

**Issue by csuka** [elastic/beats#1704]
- Version: TopBeat 1.2.3
- Operating System: Windows Server 2003
- Steps to Reproduce: Use the same input as configured in the topbeat.yml file
- Error: PID's not recognized in Server 2003, therefor nothing is sent to Logstash

Attachment:
[topbeatSettingsAndErrorlog.zip](https://github.com/elastic/beats/files/277603/topbeatSettingsAndErrorlog.zip)

Original thread:
https://discuss.elastic.co/t/server-2003-pids-not-recognized/50450

**Comment by andrewkroh** [comment]
The [`Win32_Process `](https://msdn.microsoft.com/en-us/library/aa394372(v=vs.85).aspx) WMI query is supported on Windows Vista and newer. So Topbeat should not attempt the query on those operating systems and just report the other available process metrics. We should also document that `proc.cmdline` is not supported on XP and 2003.
