### ISSUE TITLE
[Auditbeat] Error process.entity_id is duplicated error running setup

### ISSUE THREAD

**Issue by liza-mae** [elastic/beats#17042]
- Version: master
- Operating System: Linux
- Discuss Forum URL: snapshot
- Steps to Reproduce: 

Running auditbeat setup is throwing an error: 

Overwriting ILM policy is disabled. Set `setup.ilm.overwrite:true` for enabling.

Index setup finished.
Loading dashboards (Kibana must be running and reachable)
Exiting: error generating index pattern: field <process.entity_id> is duplicated, remove it or set 'overwrite: true', {Name:entity_id Type:keyword Description:ID uniquely identifying the process. It is computed as a SHA-256 hash of the host ID, PID, and process start time.
 Format: Fields:[] MultiFields:[] Enabled:<nil> Analyzer: SearchAnalyzer: Norms:false Dynamic:{Value:<nil>} Index:<nil> DocValues:<nil> CopyTo: IgnoreAbove:0 AliasPath: MigrationAlias:false Dimension:<nil> ObjectType: ObjectTypeMappingType: ScalingFactor:0 ObjectTypeParams:[] Analyzed:<nil> Count:0 Searchable:<nil> Aggregatable:<nil> Script: Pattern: InputFormat: OutputFormat: OutputPrecision:<nil> LabelTemplate: UrlTemplate:[] OpenLinkInCurrentTab:<nil> Overwrite:false DefaultField:<nil> Path:process.entity_id}, {"aggregatable":true,"analyzed":false,"count":0,"doc_values":true,"indexed":true,"name":"process.entity_id","scripted":false,"searchable":true,"type":"string"}

**Comment by liza-mae** [comment]
@adriansr thanks for the fix, this needs to be backported to 7.x please.

**Comment by adriansr** [comment]
@liza-mae yes, the backport is on its way 👍

**Comment by liza-mae** [comment]
Thank you @adriansr :) !

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
