### ISSUE TITLE
[Agent] Cut SNAPSHOT keyword from artifacts while producing snapshots

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#17057]
When producing SNAPSHOT artifact from agent we pack in beats artifacts with a correct name by fix introduced here: https://github.com/elastic/beats/pull/16927

When archive is extracted it resulting folder contains SNAPSHOT keyword again.

**Comment by ph** [comment]
This weird, when I've tested it locally with `make snapshot` at the root of the directory the agent had the "SNAPSHOT" but not the embedded artifacts?

**Comment by michalpristas** [comment]
the problem is a content of beats artifact
agent-8.0.0.tar.gz/beats/filebeat.8.0.0.tar.gz/_filebeat-8.0.0-SNAPSHOT_

**Comment by ph** [comment]
Oh my the **binary** itself, so we have actually two problems I think. I think I had the wrong assumption when I created the #16927 PR. So we should if possible, this might be complicated with our build system, have artifacts with the `SNAPSHOT` suffix and also support suffix in the binary.

**Comment by michalpristas** [comment]
i was thinking about this today and as fixing this on build/package level would be complicated touching common code to fix our specific issue i would suggest fixing it on our code. with your PR in mind i would unpack beat tar and then rename resulting folder if it contains `SNAPSHOT` keyword to a correct form.

**Comment by ph** [comment]
For the package content, maybe it's easy to fix it. I think that the template replacement variable is all done at the same time. so you could add the "SNAPSHOT"  in the name like `downloads/metricbeat-{{ beat_version }}-{{.GOOS}}-{{.AgentArchName}}.tar.gz`

https://github.com/elastic/beats/blob/99fd13a6145cd130f49615924a8e503101b6f7b1/dev-tools/packaging/packages.yml#L60

**Comment by michalpristas** [comment]
the thing you linked is ok, problem is content of the packed tar.
this is created by calling snapshot on filebeat and metricbeat before packaging agent. 

agent packaging consists of two steps, first one is checking if there are archives for needed beats if not (e.g. because you're calling `mage package` from `x-pack/agent` directory) then it will call `mage package` on filebeat and metricbeat. second step is actual construction of agent archive by following recipe from `packages.yml`
the problem is that even though we're constructing snapshot we want it to behave and contain archives which behave as non-snapshot version of beats (by having a regular name), therefore a fix you did last week. the problem is mismatch of how archive is named and what the inside content is. I will prepare a fix tomorrow and I think it will be much more clear.

**Comment by ph** [comment]
> the problem is that even though we're constructing snapshot we want it to behave and contain archives which behave as non-snapshot version of beats (by having a regular name), therefore a fix you did last week. the problem is mismatch of how archive is named and what the inside content is. I will prepare a fix tomorrow and I think it will be much more clear.

Agree, but I think we should make the agent expects snapshot when it's build as a snapshot binaries?

**Comment by michalpristas** [comment]
the scenario i was thinking about here is SNAPSHOT fallback in filesystem downloader. if it is built as a snapshot then downloader tries to locate normal version and then fallbacks to SNAPSHOT if it is not found. 

the thing is that even though it is a snapshot it should be able to download binary from elastic.co if it is missing entirely and this binary will be regular not a snapshot.

**Comment by ph** [comment]
It needs to work with both cases but not at the same time because we have a strict version requirement:

- An Agent snapshot should download snapshots version and not non snapshot version.
- An agent official release should only download official release.

**Comment by michalpristas** [comment]
@ph do you know of existing way to detect if executable was built as a snapshot during runtime? 
if not i will need to modify build process to mark some flag

**Comment by michalpristas** [comment]
@ph i went through code looking for a place where version is updated because it did make sense that using same dev-tools we dont get SNAPSHOT suffix for free. i could not find anything

when i built filebeat as a snapshot afterwards it reported standard version though

```sh
vagrant@vagrant:~/go/src/github.com/elastic/beats/x-pack/filebeat/build/distributions/filebeat-8.0.0-SNAPSHOT-linux-x86_64$ ./filebeat version
filebeat version 8.0.0 (amd64), libbeat 8.0.0 [unknown built unknown]
```

it's usually handled in `runXXX` (e.g runFPM) in this way
```go
outputFile, err := spec.Expand("{{.Name}}-{{.Version}}{{if .Snapshot}}-SNAPSHOT{{end}}-{{.Arch}}")
```

in this case i would like to avoid changing version or suffixing it with SNAPSHOT and use some build tag instead

**Comment by michalpristas** [comment]
today I iterated to a fairly simple installation of what i think is the correct way of handling it. 
take a look at PR please here: https://github.com/elastic/beats/pull/17077
