### ISSUE TITLE
Make the IP-name resolution work over Lumberjack

### ISSUE THREAD

**Issue by tsg** [elastic/beats#171]
#### Background

If we want the **server names** from both ends of a transaction to published in Elasticsearch, we need the Packetbeat shippers to know which IP addresses belong to which servers. This is because from packets we get IP information, and we need to transform it in server names to store it in the transaction objects. 

This is currently implemented via a function of the output plugins. For example, if the output plugin is Elasticsearch, the `.packetbeat-topology` index is used to build this IP-name mapping. If the output is Redis, the map is built in a secondary Redis DB.

The way it works is that on startup, and then periodically, the shippers publish the name of the server on which they run and the local IP addresses in the common index. Periodically, all shippers download the list of IP-server name mapping and use it to fill in the appropriate fields.
#### Issue

This model doesn't fit well with our plans in which the shippers only send data to Elasticsearch, not the other way around. This one-way model is especially important when we'll use Lumberjack as an output.

Also, the current ES implementation uses TTL on the records, which is currently not supported by Shield.
#### Proposed solution
- Continue building the IP - server names map in Elasticsearch just like before, but don't read it from the clients. We'd need to be able to insert in the `.packetbeat-topology` index via Lumberjack and Logstash.
- The topology map could be build from the Kibana app which would resolve IPs to names as needed.
- The Packetbeat agents then download periodically the list of IPs via HTTPS from Elasticsearch or from an tiny RESTful app in front of it. This way the server names can be inserted in each transaction, so that searches based on server names work. It's a bit of cheating that we require outbound HTTPS access, but we can make this part optional.
- Optionally, we could have other sources of naming, like DNS or service registries like Consul. Support for this could be done in Logstash as a "data enrichment" filter.

I think this is the final solution we envision for this and other similar issues, but we might break this in smaller parts and have temporary solutions as other components become available (Lumberjack output, Kibana app, etc.)

**Comment by ph** [comment]
We can close this, we don't do a graph anymore of the machines that belong together. It was a pre 1.0 feature.
