### ISSUE TITLE
filebeat output plugin to AWS kinesis 

### ISSUE THREAD

**Issue by ghost** [elastic/beats#17143]
Hi,
Will be nice to see output plugin to AWS kinesis for filebeat

This will allow to write logs to HA queue system and then process them.

As a benefit:
  Logs can be processed with multiple logstash groups for different purposes (OPS team can write to ES and data team to data lake)
  Logs will not be lost when logstash is down or restarting
  In case of wrong logstash configuration logs can be processed again

**Comment by abdalians** [comment]
+1 
we are actually considering an alternate shipper due to the lack of beats -> kinesis output.

**Comment by sihil** [comment]
We continue to use logstash for this purpose but are evaluating https://github.com/s12v/awsbeats. Having a native output plugin would be a great fir for our architecture.

**Comment by iamhowardtheduck** [comment]
I have several folks that are _HIGHLY_ interested in this output.

**Comment by Alkiris** [comment]
Would be great indeed

**Comment by yanivpaz** [comment]
its not https://github.com/aws/amazon-kinesis-firehose-for-fluent-bit/releases ?

**Comment by papovyr** [comment]
@yanivpaz 
Yes, This is fluentbit which works fine however its not providing as rich metadata about cloud provider as filebeat dose

**Comment by rafael-gumiero** [comment]
This would be a great feature to be available natively.
