### ISSUE TITLE
[Metricbeat] Investigate collection period=1m for googlecloud module

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#17141]
By looking at monitoring metrics on google cloud platform console, they ones I saw all have 1 minute interval. For example:
<img width="1788" alt="Screen Shot 2020-03-19 at 2 44 11 PM" src="https://user-images.githubusercontent.com/14081635/77113441-738e6200-69f0-11ea-910b-e073f3c1a131.png">

Also with current code, when period = 5min is set, metrics are collected per minute for 2 or 3 out of the 5 minutes. I would like to see either collecting every minute in each 5-minute instead of partially. Please see kibana snapshot for this:
<img width="2522" alt="Screen Shot 2020-03-09 at 1 12 13 PM" src="https://user-images.githubusercontent.com/14081635/77113816-134bf000-69f1-11ea-9f33-e03056c9e2e2.png">

**Comment by kaiyan-sheng** [comment]
[GCP monitoring metrics latency](https://cloud.google.com/monitoring/api/v3/latency-n-retention): Sampled every 60 seconds. After sampling, data is not visible for up to 240 seconds.

**Comment by exekias** [comment]
We had a chat about this and I think we need to change some things. It sounds like we should collect more often but account for the 240 seconds delay when choosing the time range. Also find a way to avoid sending duplicate data
