### ISSUE TITLE
Old logos used in the docs

### ISSUE THREAD

**Issue by tsg** [elastic/beats#1716]
For example [here](https://www.elastic.co/guide/en/beats/libbeat/master/logstash-installation.html) as noticed by @dadoonet. We should use the new product logos.

**Comment by dedemorton** [comment]
@tsg We also have Topbeat showing up in an overview diagram.

**Comment by dedemorton** [comment]
@brandonmensing I'd like to do an overhaul of the graphics before the 5.0 GA. I'm wondering if there are any existing graphics that I can pull from. Thought you might have some ideas....

**Comment by dedemorton** [comment]
Removed this image in PR #2892 in favor of the image added to the overview.
