### ISSUE TITLE
Check for duplicates in template generation

### ISSUE THREAD

**Issue by urso** [elastic/beats#17203]
Having multiple `dynamic_template`s with the same field name in templates can lead to bugs. For example: https://github.com/elastic/apm-server/issues/2693, https://github.com/elastic/apm-server/issues/2693#issuecomment-530366857 

The Elasticsearch team is discussing to disallow multiple dynamic templates: https://github.com/elastic/elasticsearch/issues/53326

Beats template generator should check for duplicates and fail (or at least warn) if we detect duplicates.

**Comment by simitt** [comment]
@urso removing multiple `dynamic_template`s is totally fine for APM Server. The server creates additional minimal templates for ILM, but they do not contain `dynamic_template`s, e.g. 
```
  "apm-7.7.0-error" : {
    "order" : 2,
    "index_patterns" : [
      "apm-7.7.0-error*"
    ],
    "settings" : {
      "index" : {
        "lifecycle" : {
          "name" : "apm-rollover-30-days",
          "rollover_alias" : "apm-7.7.0-error"
        }
      }
    },
    "mappings" : { },
    "aliases" : { }
  }
```

**Comment by simitt** [comment]
In APM Server we currently have the same key in the dynamic template for e.g. `labels`: 
```
    "mappings" : {
      "dynamic_templates" : [
        {
          "labels" : {
            "path_match" : "labels.*",
            "mapping" : {
              "type" : "keyword"
            },
            "match_mapping_type" : "string"
          }
        },
        {
          "labels" : {
            "path_match" : "labels.*",
            "mapping" : {
              "type" : "boolean"
            },
            "match_mapping_type" : "boolean"
          }
        },
        {
          "labels" : {
            "path_match" : "labels.*",
            "mapping" : {
              "scaling_factor" : 1000000,
              "type" : "scaled_float"
            },
            "match_mapping_type" : "*"
          }
        },
        ...
     ]
  }
```

The logic for creating the dynamic template with multiple entries for the same key in [`libbeat`](https://github.com/elastic/beats/blob/master/libbeat/template/processor.go#L320) could be adapted to e.g. adding a sequence to the key if the same key exists multiple times. 
The corresponding definition in `_meta/fields.yml` looks like the following
```
    - name: labels
      type: object
      object_type_params:
        - object_type: keyword
        - object_type: boolean
        - object_type: scaled_float
          scaling_factor: 1000000
      dynamic: true
```
