### ISSUE TITLE
Missing proc.cpu.total_p fields in topbeat

### ISSUE THREAD

**Issue by biswajit86** [elastic/beats#1720]
Hi,

Topbeat used to export a field named proc.cpu.total_p which used to capture the total cpu usage in percentage terms. I cannot see the field exported by topbeat anymore. Also, I see it was dropped from the documentation in the list of fields exported.

Can someone please send a link to the documentation where it was dropped. Can this value be revived in the future releases ?

**Comment by ruflin** [comment]
@biswajit86 Which version of topbeat are you using? In master it is still here: https://www.elastic.co/guide/en/beats/topbeat/master/exported-fields-process.html#_proc_cpu_total_p

**Comment by biswajit86** [comment]
I am using the latest stable version [1.2.3](https://www.elastic.co/guide/en/beats/topbeat/1.2/exported-fields-process.html#_proc_cpu_total_p)

**Comment by andrewkroh** [comment]
AFAIK Topbeat 1.x has never had a field named `proc.cpu.total_p`. `proc.cpu.total_p` was introduced in Topbeat 5.0.0-alpha1. Here's a link to the [release notes](https://www.elastic.co/guide/en/beats/libbeat/master/release-notes-5.0.0-alpha1.html#_breaking_changes_2) where the change was made.

**Comment by biswajit86** [comment]
@andrewkroh  , it did exist before 1.2.2 . I remember because I setup a dashboard just to monitor the toal CPU % .

I was checking the history of the topbeat field reference in github and found the field referenced in some topbeat builds, for ex the [ topbeat asciidoc](https://github.com/elastic/beats/blob/8918be892ebc2e77f77ebee2582d3a9a6b91a61f/topbeat/docs/fields.asciidoc) file on Apr 26.

**Comment by andrewkroh** [comment]
The file you linked to is part of commit 8918be892ebc2e77f77ebee2582d3a9a6b91a61f which is included in 5.0.0-alpha2. The 1.X code is now branched and we have tags for all the releases if you want to check them. I just don't think `proc.cpu.total_p` was ever part of Topbeat 1.X.

https://github.com/elastic/beats/blob/v1.2.3/topbeat/docs/fields.asciidoc
https://github.com/elastic/beats/blob/v1.2.2/topbeat/docs/fields.asciidoc
https://github.com/elastic/beats/blob/v1.2.1/topbeat/docs/fields.asciidoc
https://github.com/elastic/beats/blob/v1.2.0/topbeat/docs/fields.asciidoc
https://github.com/elastic/beats/blob/v1.1.2/topbeat/docs/fields.asciidoc

**Comment by biswajit86** [comment]
Ahh, I believe I picked it up from a nightly build then while trying to get a fix for some issue in 1.2.* . That makes sense now. Thanks
