### ISSUE TITLE
[ci] Enable Jenkinsfile Pipeline for master and 7.x

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#17204]
We want to enable the Jenkinsfile based pipeline build for changes that affect master and 7.x, including pull-requests. And then disable the old Jenkins build for those same targets.

**Comment by kuisathaverat** [comment]
It is enabled on 7.x and other branches, PRs discover is enabled too, we have to enable tags discover.

<img width="462" alt="Screenshot 2020-03-24 at 16 00 36" src="https://user-images.githubusercontent.com/5400788/77440458-9fdb2180-6de8-11ea-94fd-eea1b5be0313.png">
