### ISSUE TITLE
Looking for sampling feature as packetbeat is sending too much traffic over network

### ISSUE THREAD

**Issue by harshamadala** [elastic/beats#1721]
Raising issue here to discuss more about sampling code implementation 
Previous discussion in post:
https://discuss.elastic.co/t/is-there-any-way-to-do-data-sampling-at-client-side/50428/8?u=harshafrnd4u

Since packetbeat is doing lot of work to prepare a event with all fields, Is there any way we can design for it to randomly sample or sample based on some frequency like (send one event out of every ten events). May be we can enhance using drop_events but it would be better if we can drop before preparing event with fields.

Please guide me where can I add this kind of functionality in packetbeat.

**Comment by ruflin** [comment]
@harshamadala Where to add this probably heavily depends on what it does. I would suggest to first have here a discussion on how this should work and behave. There are lots of things to be taken into account, also related to ordering. Just an example: What happens first: Sampling or filtering?

**Comment by harshamadala** [comment]
@ruflin I suggest it would be better if we can do some sampling based on ip like (send every 10th transaction based on ip) I dont know whether it is possible to sample based on ip before decoding complete transaction, so that we can reduce some cpu utilisation. One obvious possible thing is we can sample and skip further process for few transactions before sending them over network, as it is consuming lot of network bandwidth.

**Comment by ruflin** [comment]
Pulling in @urso in this conversation as he knows much more about sampling.

**Comment by calston** [comment]
Probably worth looking at the mechanism SFlow uses for sampling

**Comment by sunny137** [comment]
Rate limiting as goreplay does would be a good starting point. This will optimize the network bandwidth aspects:

https://github.com/buger/goreplay/wiki/Rate-limiting

**Comment by sunny137** [comment]
Actually, this is one of the major reasons I decided to go ahead and use goreplay tool. The free version does only http so we don't have visibility across other protocols :-( but gives us more control over other aspects. In no way comparing these two tools but as can be seen there is a bit of overlap when it comes to monitoring incoming traffic.

**Comment by sunny137** [comment]
Can someone please comment on the idea proposed above? I think this is a much needed feature. Would love to see it happen and help with testing etc.

**Comment by lcaballero** [comment]
I suggested something like this here: [Rate limit published events](https://discuss.elastic.co/t/idea-rate-limit-filebeat-published-events-by-a-percentage/149333).  I did write something that works for my specific use case, but think it would be a great feature.  I started the discussion to cover how it might be implemented.
