### ISSUE TITLE
[Agent] Rename our binary from agent to elastic-agent

### ISSUE THREAD

**Issue by ph** [elastic/beats#17239]
The name "agent" is too generic to be installed on a system and will potentially conflict with other installed software we should rename the binaries to use the full name which is "elastic-agent" for the binary for every package generated.

This change needs to be done on the system/init.d files too, as a note heartbeat is using this strategy in the RPM/deb package.  The following is an extract of the debian package:

## Early list
- [ ] Change the directory x-pack/agent to x-pack/elastic-agent
- [ ] Change the binary to elastic-agent.
- [ ] Change the system.d / init.d to elastic-agent
- [ ] audit code  for "agent" mention to rename to Elastic Agent.
- [ ] Rename yml.

I think the above list is incomplete.

```
winterfell/tmp/out(:|✔) % tree
.
├── etc
│   ├── heartbeat
│   │   ├── fields.yml
│   │   ├── heartbeat.reference.yml
│   │   ├── heartbeat.yml
│   │   └── monitors.d
│   │       ├── sample.http.yml.disabled
│   │       ├── sample.icmp.yml.disabled
│   │       └── sample.tcp.yml.disabled
│   └── init.d
│       └── heartbeat-elastic
├── lib
│   └── systemd
│       └── system
│           └── heartbeat-elastic.service
└── usr
    ├── bin
    │   └── heartbeat
    └── share
        ├── doc
        │   └── heartbeat-elastic
        │       └── changelog.gz
        └── heartbeat
            ├── bin
            │   ├── heartbeat
            │   └── heartbeat-god
            ├── kibana
            ├── LICENSE.txt
            ├── NOTICE.txt
            └── README.md

**Comment by ph** [comment]
@ruflin @michalpristas concerning the beat folder "x-pack/agent" for consistency we might want to rename it to "x-pack/elastic-agent"

**Comment by ruflin** [comment]
++
