### ISSUE TITLE
winlogbeat logs lost

### ISSUE THREAD

**Issue by Aixic-Love** [elastic/beats#17236]
winlogbeat 6.2.0  Some logs are lost, such as 4661 logs
There may be other losses
Windows：Server2012
Logstash-6.2.4 is connected
winlogbeat -> Logstash ->>>ES  and rabbitmq 
![image](https://user-images.githubusercontent.com/50495439/77525545-2e70a100-6ec4-11ea-8127-92ea8657bc95.png)

**Comment by Aixic-Love** [comment]
There are 15 servers. Three of them have problems. Others may be lost. I've only looked at 4661 servers here

**Comment by adriansr** [comment]
Please post all questions and issues on https://discuss.elastic.co/c/beats before opening a Github Issue. Your questions will reach a wider audience there, and if we confirm that there is a bug, then you can open a new issue.
