### ISSUE TITLE
Support dedicated Filebeat port(s)

### ISSUE THREAD

**Issue by maggieghamry** [elastic/beats#17271]
**Describe the enhancement:**
Currently, there is no way to assign a dedicated source port for Filebeat. It seems that the agent will open a random high port (> 5000) on the source side (application server), then connect to port 5044 (by default) on the log stash server. 

**Describe a specific use case for the enhancement or feature:**
Filebeat process running on a several Linux servers sending data to Logstash. On the Logstash server, there are 10 ports (6000 - 6010); one for each of the logstash configurations running. 

Whenever Filebeat is restarted, it starts up on a new TCP port. There is presently no way to specify a fixed port every time or even a range of ports. 

This creates the necessity to request a range of ports to be opened from a Linux server (running filebeat) to the Logstash server each time the port changes, which raises security issues and questions.

**Proposal**
Enable ability to assign dedicated port(s) to Filebeat source ports, so they do not change on restart, and the TCP port can be secured at the firewall level, and streamline network firewall requests.

**Comment by andresrc** [comment]
Hi @maggieghamry !

Thanks for opening the issue. Client ports are usually handled by the OS from the ephemeral port range. Firewall rules should be set allowing traffic from the servers where filebeat is running to the server logstash is running, with the destination ports set to the appropriate range (6000-6010) in this case.

If you want to restrict the source side a little more, you can use the same port range configured in the OS.

Thanks
