### ISSUE TITLE
`mage vendor` chokes when `go mod vendor` deletes C source files.

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#17304]
Modules are gonna be the death of us, I swear.

Anyways, whenever you run `mage vendor`, it fails with this:

```
Error: copy failed: cannot stat source file /home/alexk/go/src/github.com/elastic/beats/vendor/github.com/godror/godror/odpi: stat /home/alexk/go/src/github.com/elastic/beats/vendor/github.com/godror/godror/odpi: no such file or directory
```

That entire vendor directory, `github.com/godror/godror/odpi`, is entirely C files, which `go mod vendor` likes to delete because reasons. When this gets deleted, during a later copy operation here:
https://github.com/elastic/beats/blob/850d1fabb64376250fadc614ac5ff14ff181d7b8/dev-tools/mage/copy.go#L47-L58

We bomb out because those files no longer exist. Right now I can hack around this by skipping files that don't exist:
```
	info, err := os.Stat(t.Source)
	if os.IsNotExist(err) {
		return nil
	}
```

But we'll need a less terrible solution in the long term.

**Comment by kvch** [comment]
I cannot reproduce your issue. Could you please provide more context?

What I have done to reproduce:

```
$ go mod vendor  # i have ran it to introduce an incorrect state
$ mage vendor  # then to try to fix it
```

My hunch is that you have had run incorrect commands to update dependencies. Please __DO NOT__ run `go mod` commands directly. Use the dedicated `mage vendor` command which is supposed to take care of maintaining dependencies. You can find more information about how to add, update and delete dependencies using go modules: https://github.com/elastic/beats/pull/15853

**Comment by kvch** [comment]
The source file which is specified is incorrect. This issue was fix by this change: https://github.com/elastic/beats/pull/17013/files#diff-c00cc9ee2b0acc89fa33743fcfee7d79R81
