### ISSUE TITLE
Incorrect exclude_files documentation?

### ISSUE THREAD

**Issue by royaldark** [elastic/beats#1731]
I was reading the [`exclude_files` documentation](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#_exclude_files), which gives the following example: 

"...ignore all the files that have a gz extension: `exclude_files: [".gz$"]`"

To me this was a red flag, since I wouldn't expect this regex to only match files with a `.gz` extension - but rather any file at least 3 characters long ending in `gz`, for example `i-am-not-a-gz`. Under most regular expression implementations, the `.` would need to be escaped to match a literal period: `\.gz$` The [beats regex documentation](https://www.elastic.co/guide/en/beats/filebeat/current/regexp-support.html) seems to indicate this as well.

Could someone clarify if the example is incorrect or not?

**Comment by ruflin** [comment]
@royaldark You are correct and we should fix this. @dedemorton Could you check this and perhaps also check if there are other similar "errors" in our docs?
