### ISSUE TITLE
Filebeat docker Mac support

### ISSUE THREAD

**Issue by celikmus** [elastic/beats#17310]
Filebeat doesn't seem to be collecting logs from Docker containers on Mac OSX host.. Docker images are not stored on the host in Macs, rather in the Docker vm, and Filebeat doesn't seem to know that. 

Any plan to support it?

PS. Current Mac version:
MacOS Catalina
v 10.15.3

**Comment by andresrc** [comment]
Unfortunately, it is not currently possible directly. A possible workaround could be to run filebeat as its own container mounting the correct filesystems.

**Comment by djmcgreal-cc** [comment]
@andresrc - any ideas what the correct mounts would be?
