### ISSUE TITLE
[Agent] Add support for the versioning of the API.

### ISSUE THREAD

**Issue by ph** [elastic/beats#17331]
Kibana will add a `v1` prefix on the API exposed by Fleet, we will need to changes our API library to support that and need to synchronize the merge with https://github.com/elastic/kibana/issues/61831

**Comment by jlind23** [comment]
@ruflin your opinion. Shall we keep it open?

**Comment by ruflin** [comment]
I think this never happened so we can close it. @joshdover There is no versioning in the Fleet API, correct?
