### ISSUE TITLE
Auditbeat - socket.entity_id still used in dashboard and docs after being removed in #13058

### ISSUE THREAD

**Issue by HonzaKral** [elastic/beats#17346]
The `socket.entity_id` field was introduced in `6.7.0` via https://github.com/elastic/beats/pull/10500 but then later removed in `7.4.0` via https://github.com/elastic/beats/pull/13058.

**Comment by adriansr** [comment]
The whole System Socket dashboard needs a complete rewrite as the dataset changed completely in 7.4.0 and now provides network flows by process instead of sockets stats.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
