### ISSUE TITLE
Add bulk/write threadpool stats in MB ES module

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#17359]
**Describe the enhancement:**

Teach the `elasticsearch` Metricbeat module (`xpack.enabled: false` code path) to index bulk/write threadpool stats.

**Describe a specific use case for the enhancement or feature:**

Elastic Cloud could use these stats.

**Comment by matschaffer** [comment]
Bump. This is still needed so we can remove some old troublesome ESS services.

**Comment by matschaffer** [comment]
ha! funny that exactly a year later I'm seeing this issue again but on the other side of the value proposition :)

I'll add this to the @elastic/infra-monitoring-ui board for consideration.

I seem so recall some of that data being available in metricbeat already but not 100% sure.

**Comment by smith** [comment]
Not prioritizing this at this time.
