### ISSUE TITLE
copy username/password comments from *beats.full.yml to *beats.yml

### ISSUE THREAD

**Issue by LeeDr** [elastic/beats#1736]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For confirmed bugs, please report:
- Version: 5.0.0-alpha3
- Operating System: Ubuntu 15.10
- Steps to Reproduce: 

1. Write an integration test script for alpha2 that uses sed to set the username/password in *beat.yml
2. start *beat
3. *beat fails to write to elasticsearch because there's no username/password in *beat.yml
4. check the journalctl for any error messages?  nothing...

**Comment by ruflin** [comment]
Now you can use the -E flag to pass variables in the command line to a beat. I think that resolves this problem. Closing this issue.

**Comment by LeeDr** [comment]
It doesn't solve the problem for running beats as a service.  I'm OK with closing this as "won't fix" because users can do what I'm doing.  I'm saving a copy of the beat .yml to beat.short.yml, and then copying beat.full.yml to beat.yml.  Then I use sed to set the username and password.

But I think is a step more work for a user than previous release where the username/password were in the beat.yml and commented-out.


```
for beat in $BEATS; do (
  cp /etc/$beat/$beat.yml /etc/$beat/$beat.short.yml
  cp /etc/$beat/$beat.full.yml /etc/$beat/$beat.yml || exit 1
  sed -i "s/#username:.*/username: \"$ELASTICUSER\"/" /etc/$beat/$beat.yml
  sed -i "s/#password:.*/password: \"$ELASTICPWD\"/"  /etc/$beat/$beat.yml
); done
```

**Comment by ruflin** [comment]
Looks like we already made this change here: https://github.com/elastic/beats/commit/dff726cb2dc3ec0a73081e563531df169cf737e9#diff-4e8f49753b842891a1a862402b8a09cbR85 Username and password are not also part of the "short" config. Fully agree that it should be there as authentication is quite a standard case. 

@LeeDr Can you close the issue if that is what you expected? I think we just forgot to notify here of this change.

**Comment by LeeDr** [comment]
I verified in the 5.0.0-beta1 build that username and password are in the `output.elasticsearch:` section again.  Closing.
