### ISSUE TITLE
[Agent] Enable debug logging for Agent and Processes

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#17390]
Sometime for debug purpose it would be nice, to have the debug logs of Metricbeat and Filebeat. My expectation would be that if I enable debug logging for the agent, this would also enable debug logging for Filebeat and Metricbeat.

**Comment by ruflin** [comment]
@ph @michalpristas I suggest we make this our default for our alpha release to always log in debug mode?

**Comment by ph** [comment]
sound good.

I believe its a one line change
