### ISSUE TITLE
Missing CI targets for x-pack software

### ISSUE THREAD

**Issue by ph** [elastic/beats#17411]
In the issue https://github.com/elastic/beats/pull/17391 and looking at the [Jenkinsfile](https://github.com/elastic/beats/blob/master/Jenkinsfile) I've found out that we are missing a few important platform targets to test, here an incomplete list.

- x-pack/agent (Linux, Windows, macOS)
- Filebeat x-pack (Linux, Windows, macOS)
- Metricbeat x-pack (Linux, Windows, macOS)
- Missing some x-pack target for all the beats.
- Generators Beats Windows

I think we have to audit all x-pack jobs at least.

[Table with stages in the Jenkinsfile](https://docs.google.com/spreadsheets/d/1cns4lri45WpYkl13Qeqk3ZyCuHv-ZTpEugxKpxV_ng0)

**Comment by ph** [comment]
I've added test for the agent in https://github.com/elastic/beats/pull/17445

**Comment by andrewkroh** [comment]
I created a spreadsheet with all of the test targets that I think we need (haven't looked at the generators yet).

https://docs.google.com/spreadsheets/d/1-m2-JlxeG_lmnvdL3UBQ7_BHhee_VL9J_EBM75SttLs

**Comment by andrewkroh** [comment]
Relates: https://github.com/elastic/beats/issues/18515 https://github.com/elastic/beats/pull/18494

**Comment by jsoriano** [comment]
I have prepared a table with the stages that we have now, and the ones that we may be missing: https://docs.google.com/spreadsheets/d/1cns4lri45WpYkl13Qeqk3ZyCuHv-ZTpEugxKpxV_ng0/edit#gid=0

**Comment by andrewkroh** [comment]
@jsoriano  I think I need a legend/key for the table.
`y` - we have it now?
`-` - not applicable / doesn't exist ?
🔴 (red) - missing?
💚 (green) - synonymous with `y`

**Comment by jsoriano** [comment]
> @jsoriano I think I need a legend/key for the table.
> `y` - we have it now?
> `-` - not applicable / doesn't exist ?
> red_circle (red) - missing?
> green_heart (green) - synonymous with `y`

Legend added to the spreadsheet.

**Comment by v1v** [comment]
Regarding this particular issue, since I'm working on the 2.0 Pipeline implementation, I created a script to generate the table with what beats are enabled in the CI and what build/stages are enabled for each, please see below:

https://github.com/elastic/beats/pull/20104#build-stages

__NOTE__: the above-mentioned PR is still in progress, but wanted to clarify that we can create what we run in the CI in a markdown table.

**Comment by jsoriano** [comment]
With the current pipelines I think we are covered. Closing this.
