### ISSUE TITLE
[filebeat] Netflow overview dashboard error - Could not locate that index-pattern-field (id: flow.locality)

### ISSUE THREAD

**Issue by opoplawski** [elastic/beats#17457]
For confirmed bugs, please report:
- Version: Kibana 
- Operating System: ScientificLinux 7.7
- Discuss Forum URL: https://discuss.elastic.co/t/could-not-locate-that-index-pattern-field-id-flow-locality/225441
- Steps to Reproduce: 

* Import filebeat 7.6.1 kibana dashboards
* Collect netflow data with filebeat
* Open [Filebeat Netflow] Overview dashboard

Third visualization down on the left column generates:

Could not locate that index-pattern-field (id: flow.locality)

I can't find that field in the index pattern mappings.

**Comment by pcmerc** [comment]
What is the status on this? 7.10.2 still suffers with the same missing config setup.

**Comment by opoplawski** [comment]
Is this a licensing issue (flow being part of x-pack) or some such?
