### ISSUE TITLE
Functionbeat dynamic names

### ISSUE THREAD

**Issue by EricaJCasePhD** [elastic/beats#17495]
Similar to index names, make the index lifecycle management template name dynamic in functionbeat.  We need separate different policy names based on an environmental variable passed through serverless.

**Comment by andresrc** [comment]
Hi @EricaJCasePhD ! Thanks for creating the issue. In it's current form, we are not planning any change in this direction in functionbeat. Nevertheless, we are working on a better way to manage indices and their lifecycle for metricbeat and filebeat, and once available we will analyse how to bring equivalent features to functionbeat.

I'm closing this issue for now. Thanks!
