### ISSUE TITLE
[Flaky Test] TestConfigAcceptValid/Kerberos_with_keytab

### ISSUE THREAD

**Issue by sincejune** [elastic/beats#17506]
## Flaky Test

* **Test Name:** TestConfigAcceptValid
* **Link:** https://github.com/elastic/beats/blob/62f297169fafaf458ccd2963ca6ea51f1832e5d1/libbeat/outputs/kafka/config_test.go#L38-L46
* **Branch:** master
* **Artifact Link:** If available, attach the generated zip artifact associated with the stack trace for this failure.
* **Notes:** It's failing on travis-ci when running `make testsuite`

### Stack Trace

```
github.com/elastic/beats/v7/libbeat/outputs/kafka]: exit status 1
--- FAIL: TestConfigAcceptValid (0.00s)
    --- FAIL: TestConfigAcceptValid/Kerberos_with_keytab (0.00s)
        config_test.go:69: Failure creating sarama config: kafka: invalid configuration (Net.SASL.GSSAPI.Username must not be empty when GSS-API mechanism is used)
FAIL
```

**Comment by kvch** [comment]
It's not a flaky test. It fails consistently on my host.

**Comment by sincejune** [comment]
Oh, I'm sorry. I just used the issue template, renamed this issue. Thanks.
