### ISSUE TITLE
[Discovery] CRI-O module

### ISSUE THREAD

**Issue by exekias** [elastic/beats#17515]
# Metricbeat Module / Dataset release checklist

CRI-O is a container runtime often used in Kubernetes. It exposes prometheus metrics when enabled, so we can leverage that to create a module based on them.

I'm not sure about logs myself so part of this task is to check if CRI-O generates logs and what value can we get out of them.

https://cri-o.io/

## Modules

For a metricset to go GA, the following criterias should be met:

* [ ] Supported versions are documented
* [ ] Supported operating systems are documented (if applicable)
* [ ] Integration tests exist
* [ ] System tests exist
* [ ] Automated checks that all fields are documented
* [ ] Documentation
* [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] Dashboards exists (if applicable)
* [ ] Kibana Home Tutorial (if applicable)
  * Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).

## Filebeat module

* [ ] Test log files exist for the grok patterns
* [ ] Generated output for at least 1 log file exists

## Metricbeat module

* [ ] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [ ] Test environment in Docker exist for integration tests

**Comment by danmx** [comment]
Making it more generic, [`OCI runtime`](https://github.com/opencontainers/runtime-tools) compliant, would cover most container runtimes including `docker`

**Comment by jonas27** [comment]
Hi, is containerd socket supported now?

**Comment by jonas27** [comment]
Hi, any answer on the question above?

**Comment by ChrsMark** [comment]
Hi @jonas27, unfortunately there is still no progress in this one. However if you run on Kubernetes, you can collect container metrics through the `kubernetes` module (`container` metricset more specifically) . Also it would be nice if you could share  more information about your use case.

**Comment by jonas27** [comment]
Thanks @ChrsMark In my team we were using the metric overview for "docker" containers in Kibana quite frequently. This overview is not functional anymore after upgrading to containerd and k8s 1.21 
In my opinion  it would be nice to have the ability to query CRI instead of docker for the same metrics.

**Comment by ChrsMark** [comment]
Yeap, this is a known issue I think, see https://github.com/elastic/kibana/issues/100229.
The thing is that the UI is tightly coupled with `docker.*` fields while the same metrics could be displayed using for example `kubernetes.container.cpu`, as I mentioned in my previous comment. This one should be fixed with the on-going work around ECS fields introduction https://github.com/elastic/beats/issues/22179. But in general yes it would be of benefit to have support for additional container runtimes.

**Comment by jonas27** [comment]
Makes sense and it seems you are working on it, so I will wait and be happy when the feature arrives 🙂 
(Maybe as a last note, I think cri support would be enough. Imo there are not many people using none cri compatible container runtimes except from docker)

**Comment by tetianakravchenko** [comment]
1. Local environment:

**kind**: cri-o is not supported by default, to get cri-o on kind can be built a custom docker image, based on `kindest/node` image, see this [discussion](https://gist.github.com/aojea/bd1fb766302779b77b8f68fa0a81c0f2)
> NOTE: for the latest k8s version `1.23` and cri-o version 1.23 cluster does not work properly, see the [comment](https://gist.github.com/aojea/bd1fb766302779b77b8f68fa0a81c0f2?permalink_comment_id=4168270#gistcomment-4168270)

**minikube** - 

2. Metrics:

2.1. CRI-O prometheus metrics - https://github.com/cri-o/cri-o/blob/main/tutorials/metrics.md#available-metrics
NOTE: in version 1.23 metrics names got changed (e.g.`crio_operations` -> `crio_operations_total` and old names got deprecated).
Those metrics include only runtime stats, like number of operations, latency of operations, number of errors of the specific operations, example:
```
container_runtime_crio_operations_total{operation="ContainerStatus"} 165459
```
but it does not provide container cpu/memory/etc usage.
Now there are available 13 metrics, I think next 3 might be of use: `container_runtime_crio_operations_total`, `container_runtime_crio_operations_errors_total`, `container_runtime_crio_operations_latency_seconds`.

2.2. Containers stats:
`crictl` cli provides container(s) resource usage statistics:
```
CONTAINER           CPU %               MEM                 DISK                INODES
1330e8a0c041d       3.51                258.6MB             12B                 17
537436533d58f       0.00                8.995MB             2.294kB             27
6a4958c587c58       0.31                17.64MB             12B                 10
a79e15203cb30       2.29                52.22MB             12B                 23
c54e9bb1577ef       0.44                13.48MB             12B                 17
d35de6345d5f8       0.31                13.53MB             12B                 17
e7206b19152bd       1.39                55.19MB             12B                 14
```
also available in json format:
```
crictl stats --output json
...
{
      "attributes": {
        "id": "e7206b19152bd2746e1588fc4ba36eb64bf7fe7a2dd6347ef7812976fe60807b",
        "metadata": {
          "name": "etcd",
          "attempt": 0
        },
        "labels": {
          "io.kubernetes.container.name": "etcd",
          "io.kubernetes.pod.name": "etcd-crio-control-plane",
          "io.kubernetes.pod.namespace": "kube-system",
          "io.kubernetes.pod.uid": "70d01b4eeb05ccb1474d7790b21e75cc"
        },
        "annotations": {
          "io.kubernetes.container.hash": "4fb1fe28",
          "io.kubernetes.container.restartCount": "0",
          "io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
          "io.kubernetes.container.terminationMessagePolicy": "File",
          "io.kubernetes.pod.terminationGracePeriod": "30"
        }
      },
      "cpu": {
        "timestamp": "1652980972173820343",
        "usageCoreNanoSeconds": {
          "value": "373281530000"
        }
      },
      "memory": {
        "timestamp": "1652980972173820343",
        "workingSetBytes": {
          "value": "54239232"
        }
      },
      "writableLayer": {
        "timestamp": "1652980972173861900",
        "fsId": {
          "mountpoint": "/var/lib/containers/storage/overlay/917603cd85e6db64e554a98359867f8a6a7c8253e933c2b26eb97ec1bb41a17d/merged"
        },
        "usedBytes": {
          "value": "12"
        },
        "inodesUsed": {
          "value": "14"
        }
      }
    }
...
```
but there is no other way except of `crictl stats` command.

HTTP API is exposed https://github.com/cri-o/cri-o#the-http-status-api, but `crictl stats` is not exposed (available endpoints `/info`, `/containers/:id`, `/config`)

`/containers/:id` does not provide cpu/memory data:
```
curl -s --unix-socket /run/crio/crio.sock http://127.0.0.1/containers/e7206b19152bd2746e1588fc4ba36eb64bf7fe7a2dd6347ef7812976fe60807b | jq
{
  "name": "k8s_etcd_etcd-crio-control-plane_kube-system_70d01b4eeb05ccb1474d7790b21e75cc_0",
  "pid": 349,
  "image": "k8s.gcr.io/etcd:3.5.1-0",
  "image_ref": "k8s.gcr.io/etcd@sha256:05c1a3be66823dcaca55ebe17c3c9a60de7ceb948047da3e95308348325ddd5a",
  "created_time": 1652705234152224300,
  "labels": {
    "io.kubernetes.pod.namespace": "kube-system",
    "io.kubernetes.pod.name": "etcd-crio-control-plane",
    "io.kubernetes.container.name": "etcd",
    "io.kubernetes.pod.uid": "70d01b4eeb05ccb1474d7790b21e75cc"
  },
  "annotations": {
    "io.kubernetes.container.terminationMessagePolicy": "File",
    "io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
    "io.kubernetes.container.restartCount": "0",
    "io.kubernetes.container.hash": "4fb1fe28",
    "io.kubernetes.pod.terminationGracePeriod": "30"
  },
  "crio_annotations": {
    "io.kubernetes.cri-o.SandboxName": "k8s_etcd-crio-control-plane_kube-system_70d01b4eeb05ccb1474d7790b21e75cc_0",
    "io.kubernetes.cri-o.ResolvPath": "/run/containers/storage/overlay-containers/b4efc940509e59c84cd03f31be3f433fc2b4d5de17030538d7d9e3c4d6fc962d/userdata/resolv.conf",
    "io.kubernetes.container.name": "etcd",
    "io.kubernetes.cri-o.Stdin": "false",
    "kubernetes.io/config.source": "file",
    "io.kubernetes.cri-o.ImageName": "k8s.gcr.io/etcd:3.5.1-0",
    "io.kubernetes.cri-o.ImageRef": "25f8c7f3da61c2a810effe5fa779cf80ca171afb0adf94c7cb51eb9a8546629d",
    "io.kubernetes.cri-o.MountPoint": "/var/lib/containers/storage/overlay/917603cd85e6db64e554a98359867f8a6a7c8253e933c2b26eb97ec1bb41a17d/merged",
    "io.kubernetes.cri-o.SeccompProfilePath": "runtime/default",
    "io.kubernetes.cri-o.Labels": "{\"io.kubernetes.container.name\":\"etcd\",\"io.kubernetes.pod.name\":\"etcd-crio-control-plane\",\"io.kubernetes.pod.namespace\":\"kube-system\",\"io.kubernetes.pod.uid\":\"70d01b4eeb05ccb1474d7790b21e75cc\"}",
    "io.kubernetes.cri-o.Volumes": "[{\"container_path\":\"/etc/hosts\",\"host_path\":\"/var/lib/kubelet/pods/70d01b4eeb05ccb1474d7790b21e75cc/etc-hosts\",\"readonly\":false},{\"container_path\":\"/dev/termination-log\",\"host_path\":\"/var/lib/kubelet/pods/70d01b4eeb05ccb1474d7790b21e75cc/containers/etcd/5231e749\",\"readonly\":false},{\"container_path\":\"/var/lib/etcd\",\"host_path\":\"/var/lib/etcd\",\"readonly\":false},{\"container_path\":\"/etc/kubernetes/pki/etcd\",\"host_path\":\"/etc/kubernetes/pki/etcd\",\"readonly\":false}]",
    "io.kubernetes.container.terminationMessagePolicy": "File",
    "io.kubernetes.pod.terminationGracePeriod": "30",
    "io.kubernetes.pod.name": "etcd-crio-control-plane",
    "io.kubernetes.cri-o.LogPath": "/var/log/pods/kube-system_etcd-crio-control-plane_70d01b4eeb05ccb1474d7790b21e75cc/etcd/0.log",
    "io.kubernetes.cri-o.Metadata": "{\"name\":\"etcd\"}",
    "io.kubernetes.cri-o.Annotations": "{\"io.kubernetes.container.hash\":\"4fb1fe28\",\"io.kubernetes.container.restartCount\":\"0\",\"io.kubernetes.container.terminationMessagePath\":\"/dev/termination-log\",\"io.kubernetes.container.terminationMessagePolicy\":\"File\",\"io.kubernetes.pod.terminationGracePeriod\":\"30\"}",
    "kubernetes.io/config.seen": "2022-05-16T12:46:55.233663318Z",
    "io.kubernetes.cri-o.SandboxID": "b4efc940509e59c84cd03f31be3f433fc2b4d5de17030538d7d9e3c4d6fc962d",
    "io.kubernetes.pod.uid": "70d01b4eeb05ccb1474d7790b21e75cc",
    "kubernetes.io/config.hash": "70d01b4eeb05ccb1474d7790b21e75cc",
    "io.kubernetes.cri-o.Image": "k8s.gcr.io/etcd@sha256:05c1a3be66823dcaca55ebe17c3c9a60de7ceb948047da3e95308348325ddd5a",
    "io.kubernetes.cri-o.ContainerType": "container",
    "io.kubernetes.cri-o.TTY": "false",
    "io.container.manager": "cri-o",
    "io.kubernetes.cri-o.Created": "2022-05-16T12:47:14.0953592Z",
    "io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
    "io.kubernetes.pod.namespace": "kube-system",
    "kubeadm.kubernetes.io/etcd.advertise-client-urls": "https://172.18.0.2:2379",
    "io.kubernetes.cri-o.ContainerID": "e7206b19152bd2746e1588fc4ba36eb64bf7fe7a2dd6347ef7812976fe60807b",
    "io.kubernetes.container.restartCount": "0",
    "io.kubernetes.cri-o.Name": "k8s_etcd_etcd-crio-control-plane_kube-system_70d01b4eeb05ccb1474d7790b21e75cc_0",
    "io.kubernetes.cri-o.StdinOnce": "false",
    "io.kubernetes.container.hash": "4fb1fe28"
  },
  "log_path": "/var/log/pods/kube-system_etcd-crio-control-plane_70d01b4eeb05ccb1474d7790b21e75cc/etcd/0.log",
  "root": "/var/lib/containers/storage/overlay/917603cd85e6db64e554a98359867f8a6a7c8253e933c2b26eb97ec1bb41a17d/merged",
  "sandbox": "b4efc940509e59c84cd03f31be3f433fc2b4d5de17030538d7d9e3c4d6fc962d",
  "ip_addresses": null
}
```

**Comment by jonas27** [comment]
@tetianakravchenko how does your finding relate to the new module for containerd added in 8.1, see https://www.elastic.co/guide/en/beats/metricbeat/8.1/metricbeat-module-containerd.html

**Comment by tetianakravchenko** [comment]
@jonas27 it is not related to the containerd module, I think this comment https://github.com/elastic/beats/issues/17699#issuecomment-1070988373 and corresponding issue might clarify it

**Comment by MichaelKatsoulis** [comment]
@tetianakravchenko I also believe that since  `crio` runtime is not providing container stats for the time being is not worth it to create a new module for that. At least for the time being. Could we open an enhancement request to them, so as to provide a `/stats` endpoint in the future? 
I think we can close this issue for now. 
@gizas wdyt?

**Comment by gizas** [comment]
You surely know more here than me, and have not seen any discussions about supporting known runtimes at the moment. So even an enhancement will just gain us some time but I think we need to discuss internally if we need to support them and when.

Making a note to at least plan the discussions

**Comment by tetianakravchenko** [comment]
@MichaelKatsoulis I've create an issue - https://github.com/cri-o/cri-o/issues/5915
