### ISSUE TITLE
Add keystore tip wherever we describe passwords.

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#17547]
We want users to store sensitive values in either the keystore or environment variables to avoid showing them in plain text in config files. We need to add this tip to all the Beats docs where we show how to set passwords:

```
TIP: To obfuscate passwords and other sensitive settings,
ifndef::serverless[]
use the <<keystore,secrets keystore>>.
endif::[]
ifdef::serverless[]
use environment variables.
endif::[]
```

This will also help the problem where `$$` needs to be escaped as `$$$$` in text string values because the template engine can't handle them.

**Comment by EamonnTP** [comment]
Hi @dedemorton I was going to pick this up as a good first issue. However, it looks like this issue has already been addressed in the Beats docs. Step 2 here: https://www.elastic.co/guide/en/beats/functionbeat/current/beats-basic-auth.html

Do we want to remove step 2 and replace it with a tip?

**Comment by dedemorton** [comment]
Yah I think we are using slightly different language. In fact, Brandon has removed the tip here: https://github.com/elastic/beats/pull/18594/files#diff-de0dd5cdacb6ff127abb5ee368c4ef6dL34

TBH, I'm not sure this is the best issue to fix right now because Brandon and I both have PRs open that touch those files. Instead, I suggest searching the docs for instances where we don't say anything. If we're covered, then you can just close this issue. Thanks!!

**Comment by dedemorton** [comment]
FYI...here's the PR that I have open. Feel free to add a suggestion to my PR if you notice inconsistent wording around use of the keystore. https://github.com/elastic/beats/pull/17007

**Comment by EamonnTP** [comment]
No problem, thanks.

**Comment by dedemorton** [comment]
Closing. I think we've covered this sufficiently.
