### ISSUE TITLE
[Metricbeat] Add integration tests for AWS

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#17551]
We want to improve our coverage with integration tests for aws module using real AWS services. Similar to terraform scenario in Filebeat for ELBs, we can create scenarios for deploying and destroying testing services in AWS using Terraform for individual metricsets.

There are aws module in Metricbeat and aws autodiscover provider need to be tested:

- Metricbeat aws module
  - cloudwatch metricset for a given namespace
  - separate tests for metricsets that are not created using light weight module, such as ec2, s3, rds
  - test metrics from CloudWatch like `aws.ec2.cpu.total.pct`
  - test metrics from other API calls like DescribeInstances in EC2: `aws.ec2.instance.state`.
  - test tag collection

- Metricbeat `aws_ec2` autodiscover
  - Check that a module is launched when an EC2 instance(with a specific tag) is created
  - Check the module stops when this EC2 instance is deleted

**Comment by ravikesarwani** [comment]
Close it as stale. Will create specific focused issue based on use cases seen from the field.
