### ISSUE TITLE
[Metricbeat] Add integration tests for GCP

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#17552]
We want to improve our coverage with integration tests for googlecloud module using real GCP services. Similar to terraform scenario in Filebeat for ELBs, we can create scenarios for deploying and destroying testing services in GCP using Terraform for individual metricsets.

- create terraform scenario for each metricset in googlecloud module 
- make sure service is up and running before trying to query for monitoring metrics
- test metadata collection for compute metricset

**Comment by endorama** [comment]
Work on adding required test infrastructure for running system/integration test is being performed in `integrations` repo. I plan to understand how to leverage the same terraform code to test beats and integration package, as the required infrastructure should be the same.

PRs adding tests to `gcp` integration package:
- https://github.com/elastic/integrations/pull/2312
