### ISSUE TITLE
[Metricbeat] Azure database_account metricset reports empty database name and tag value

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#17553]
When I'm testing `database_account` metricset, I see some empty field values in the event:

- `azure.dimensions.database_name`: `"<empty>"`
- `azure.tags.hidden-cosmos-mmspecial`: `""`

Here is the full event for reference:
```
{
  "_index": "metricbeat-7.7.0-2020.04.03-000001",
  "_type": "_doc",
  "_id": "zhFLUXEBqeQakGIj8cDY",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2020-04-06T20:56:00.000Z",
    "metricset": {
      "period": 300000,
      "name": "database_account"
    },
    "azure": {
      "subscription_id": "7657426d-c4c3-44ac-88a2-3b2cd59e6dba",
      "namespace": "Microsoft.DocumentDb/databaseAccounts",
      "dimensions": {
        "database_name": "<empty>"
      },
      "database_account": {
        "metadata_requests": {
          "count": 223
        }
      },
      "timegrain": "PT5M",
      "resource": {
        "tags": {
          "CosmosAccountType": "Non-Production",
          "created-by": "ks",
          "defaultExperience": "Core (SQL)",
          "hidden-cosmos-mmspecial": ""
        },
        "type": "Microsoft.DocumentDb/databaseAccounts",
        "group": "test-mb-fb"
      }
    },
    "ecs": {
      "version": "1.5.0"
    },
      "name": "KaiyanMacBookPro"
    },
    "service": {
      "type": "azure"
    },
    "cloud": {
      "provider": "azure",
      "region": "westus",
      "instance": {
        "name": "cosmosks1",
        "id": "/subscriptions/7657426d-c4c3-44ac-88a2-3b2cd59e6dba/resourceGroups/test-mb-fb/providers/Microsoft.DocumentDb/databaseAccounts/cosmosks1"
      }
    },
    "event": {
      "dataset": "azure.database_account",
      "module": "azure",
      "duration": 2070636224
    }
  },
  "fields": {
    "@timestamp": [
      "2020-04-06T20:56:00.000Z"
    ]
  },
  "sort": [
    1586206560000
  ]
}
```

As you can see in Azure portal, the database I created does have a name `cosmosks1` and there are 3 sets of tags come with it:
<img width="2558" alt="Screen Shot 2020-04-06 at 3 10 08 PM" src="https://user-images.githubusercontent.com/14081635/78605494-de290580-7818-11ea-94ed-670ed58eda13.png">

If I didn't miss anything, I think in the output event from `database_account` account, `azure.dimensions.database_name` should be `cosmosks1` and `azure.tags` should not include `hidden-cosmos-mmspecial` tag key.

**Comment by narph** [comment]
@kaiyan-sheng ,

> If I didn't miss anything, I think in the output event from database_account account, azure.dimensions.database_name should be cosmosks1 and azure.tags should not include hidden-cosmos-mmspecial tag key.

Database name value is  `<empty>` because you have no containers/databases created in your database account which is called `cosmosks1`. The name will never be the resource name unless you add a database called `cosmosks1` as well.
That is the output of the API which I would like to keep in order for users to filter out, group etc.

Regarding the extra tag `hidden-cosmos-mmspecial` that has been generated, we might see tags that start with `hidden-` and `link:`. These are internal tags, which users are usually advised to ignore and avoid changing.
I do not want to remove these type of tags just yet as they might serve some purpose for the users, could be something to do in the future if they turn out to be useless.

Also, I am not able to reproduce this behavior, what was the process you followed when creating this db account, have you taken any specific steps?

**Comment by kaiyan-sheng** [comment]
> Database name value is `<empty>` because you have no containers/databases created in your database account which is called `cosmosks1`. The name will never be the resource name unless you add a database called `cosmosks1` as well.
> That is the output of the API which I would like to keep in order for users to filter out, group etc.

Thank you for pointing that out. I created a container inside the database account and was able to verify `azure.dimensions.database_name` changed to the database name.

> Regarding the extra tag `hidden-cosmos-mmspecial` that has been generated, we might see tags that start with `hidden-` and `link:`. These are internal tags, which users are usually advised to ignore and avoid changing.
> I do not want to remove these type of tags just yet as they might serve some purpose for the users, could be something to do in the future if they turn out to be useless.

OK, I agree to keep the empty tag since it's generated by azure.

> Also, I am not able to reproduce this behavior, what was the process you followed when creating this db account, have you taken any specific steps?

I just created cosmos db using azure portal:
<img width="877" alt="Screen Shot 2020-04-07 at 7 59 15 AM" src="https://user-images.githubusercontent.com/14081635/78680867-4293a580-78a9-11ea-88b5-c929e9f6d082.png">

I'm closing this issue for now since the conclusion is to keep the `azure.tags.hidden-cosmos-mmspecial: ""` as it is.
