### ISSUE TITLE
[Functionbeat] Wrong error message when using a bucket which doesn't exists in AWS

### ISSUE THREAD

**Issue by sayden** [elastic/beats#17572]
When using `cloudwatch` Functionbeat with a non existing bucket, you get the following error message:

`Function: cloudwatch, could not deploy, error: bucket 'sdfja;sdlkfja;lsdkjfa;lsdkfjalksdjhfg928y3zs' already exist and you don't have permission to access it`

Obviously, bucket `sdfja;sdlkfja;lsdkjfa;lsdkfjalksdjhfg928y3zs` does not exists :smile:

**Comment by mgilgar** [comment]
I have the same issue, just following the example in the documentation, nothing fancy https://www.elastic.co/guide/en/beats/functionbeat/current/functionbeat-configuration.html

**Comment by ravinaik1312** [comment]
I think this is coming from the catch all error [here](https://github.com/elastic/beats/blob/master/x-pack/functionbeat/manager/aws/op_ensure_bucket.go#L59), I believe we can stop something like this pretty early on where we are validating the configuration, can send in a PR soon.

**Comment by sunilmchaudhari** [comment]
What is  the solution finally?
Sorry I don't know how to track issues and get to the solution from Github.

**Comment by ravinaik1312** [comment]
[This](https://github.com/elastic/beats/pull/20887#event-3788532846) shows that the bugfix is now available in version `7.10.0`

**Comment by sunilmchaudhari** [comment]
Hi,
Still same error in version 7.10.0 and 7.11

**Comment by sunilmchaudhari** [comment]
This is solved by installing and configuring AWS CLI.  I could easily upload function in aws.  Probably the document need to update for  Windows users and add this step under  https://www.elastic.co/guide/en/beats/functionbeat/current/functionbeat-installation-configuration.html#setup-assets
