### ISSUE TITLE
[Functionbeat] AWS binary not included in Windows packaging of 7.7

### ISSUE THREAD

**Issue by sayden** [elastic/beats#17571]
When downloading a Functionbeat a `function-aws.exe` binary is expected but it's not there.

**Comment by andresrc** [comment]
was it included in 7.6? is this a regression?

**Comment by kvch** [comment]
`functionbeat-aws.exe` is not expected to be present under the folder `pkg`. I am sorry if I was not clear when chatting about it offline.

`functionbeat-aws` is the Lambda function which is uploaded to AWS. It should be compiled for `linux` regardless of the platform of the installer/package. Only the manager needs a platform-specific binary, as it runs on the users' hosts.
