### ISSUE TITLE
Move AWS Filebeat module to GA

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#17597]
- Ensure the [requirements](https://github.com/elastic/beats/blob/master/.github/ISSUE_TEMPLATE/module-checklist.md) are met.
- Move the module to GA

**Comment by kaiyan-sheng** [comment]
@leehinman What do you think about moving AWS Filebeat module to GA for 7.14 or 7.15? Thanks!

**Comment by leehinman** [comment]
> @leehinman What do you think about moving AWS Filebeat module to GA for 7.14 or 7.15? Thanks!

Sounds good to me.
