### ISSUE TITLE
[BUG] Filebeat creates wrong index name

### ISSUE THREAD

**Issue by vutkin** [elastic/beats#17607]
Hi All,

Filebeat affected: 7.6.1/7.6.2, installed via Elastic's helm charts (with default config).

ES: 7.5.1

We are running into an issue where setting the ILM policy via filebeat config with the default index pattern of filebeat-7.6.1-%{now/d}<del>000001</del> but instead the index gets the name filebeat-7.6.1 and that seems to ruin the ILM setup, as the index template doesn't match (it's looking for filebeat-7.6.1*) and thus the ILM policy doesn't get applied to the index.

Reproduce steps : Need to delete current correct index on running filebeat and it recreate index with wrong name.

Healthy
![image](https://user-images.githubusercontent.com/25753488/78775721-5de0dc80-799f-11ea-8136-9f154b4c9bc4.png)
Problem
![image](https://user-images.githubusercontent.com/25753488/78775742-6507ea80-799f-11ea-8c5c-96a684596d9b.png)

Could you please investigate a bug?

ref to discussion: https://discuss.elastic.co/t/bug-filebeat-creates-wrong-index-name-on-index-deletion/227100

**Comment by faec** [comment]
Unassigning to re-triage

**Comment by jlind23** [comment]
No more news yet, closing it until further notice.
