### ISSUE TITLE
Preconfigured ELB and Billing Dashboards in Kibana

### ISSUE THREAD

**Issue by vennemp** [elastic/beats#17617]
Hey guys, I just started using your product to get AWS metrics in to ELK and love the preconfigured EC2 dashboard.  However, I was having some problems with getting the ELB and Billing dashboards to appear.  I am using AWS ElasticSearch/Kibana (their ELK as a service) and have enabled the AWS module and configured it properly according to documentation.  

When I run metricbeat setup, it created a ton of Kibana dashboards but only did EC2 for AWS-related.  Not the billing and elb ones. Any idea how to get them?

**Comment by kaiyan-sheng** [comment]
Hello, @vennemp thanks for creating this issue. But we would kindly ask you to post all questions on https://discuss.elastic.co/c/beats before opening a Github Issue. Github issues are intended for confirmed bugs only. Thanks in advance! 

Also what version of Metricbeat are you running?
