### ISSUE TITLE
Filebeat Apache module - failed grok expression

### ISSUE THREAD

**Issue by 0xtf** [elastic/beats#17663]
- Beats: Filebeat
- Version: 7.6.2
- Operating System: Ubuntu 18.04

The following entry in **access.log** fails when grok expression tries to process it:

`45.148.120.150 - - [10/Apr/2020:15:04:47 +0000] "moteSubmit=Save" 400 0 "-" "-"`

Error from **error.message**:

`Provided Grok expressions do not match field value: [45.148.120.150 - - [10/Apr/2020:15:04:47 +0000] \"moteSubmit=Save\" 400 0 \"-\" \"-\"]`

**Comment by andresrc** [comment]
Hi @0xtf ! Thanks for opening the issue. Can you create a [discuss topic](https://discuss.elastic.co/)? Thanks!

**Comment by 0xtf** [comment]
The current grok expressions are not taking into account an existing log
entry. Is it not a bug or an improvement?
