### ISSUE TITLE
[Filebeat] Allow modules to set the ecs.version field value

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#17688]
**Describe the enhancement:**

As a user of Filebeat modules I would like the ECS version number (`ecs.version`) to reflect what version the data from the module comforms to rather than what version of the schema has been imported by libbeat.

**Describe a specific use case for the enhancement or feature:**

It's helpful to have an accurate `ecs.version` field in the data when you are trying to build queries for the data. You might need one query for earlier versions and then can use a generic query for the later versions that have categories and types.

It will also serve as documentation of when the module was last updated for ECS.

Relates: https://github.com/elastic/beats/issues/16089

**Comment by andrewkroh** [comment]
I verified that modules can set `ecs.version` without having libbeat overwrite the value. It could be as simple as putting an `add_fields` processor into the module's config with the ECS version. This works:

```diff
diff --git a/x-pack/filebeat/module/panw/panos/config/input.yml b/x-pack/filebeat/module/panw/panos/config/input.yml
index 929237b99..a1aeda8f5 100644
--- a/x-pack/filebeat/module/panw/panos/config/input.yml
+++ b/x-pack/filebeat/module/panw/panos/config/input.yml
@@ -18,6 +18,11 @@ exclude_files: [".gz$"]
 tags: {{.tags}}
 
 processors:
+  - add_fields:
+      target: ecs
+      fields:
+        version: 1.6.0-beta
+
   - add_locale: ~
 
   - decode_csv_fields:
```

@leehinman What do you think of that approach?

**Comment by leehinman** [comment]
I like it I'll add to all the filesets I've updated.

**Comment by andrewkroh** [comment]
I want to expand this issue to include explicitly setting the `ecs.version` for Packetbeat, Auditbeat, and Winlogbeat.

- [ ] Winlobeat Security Modules
- [ ] Winlogbeat Sysmon Module
- [ ] Packetbeat - We could do this for Packetbeat as whole by using custom modifier rather than `WithECS`. See [example](https://github.com/elastic/beats/blob/f80f82c8dbe15f0215a7224c8b633312efbb4c71/winlogbeat/cmd/root.go#L39-L43). 
- [ ] Auditbeat - Do the same thing as Packetbeat.

**Comment by andrewkroh** [comment]
I have opened https://github.com/elastic/beats/pull/19159 to cover Auditbeat, Winlogbeat, Packetbeat.

**Comment by andrewkroh** [comment]
@leehinman The Filebeat part of this issue is complete, right?

**Comment by leehinman** [comment]
> @leehinman The Filebeat part of this issue is complete, right?

Once #19198 is merged.
