### ISSUE TITLE
Ability to add additional information in HTTP header

### ISSUE THREAD

**Issue by ramakrishnachirra** [elastic/beats#1768]
Hi,
Currently there is no way of adding an additional information in HTTP header (for authentication on server) in http request from filebeat to ElasticSearch. Please add this as a new feature in future releases of FileBeat. This would be very helpful for authentication purposes.

Thanks,
RK

**Comment by ruflin** [comment]
Can you add some more details about the headers you would like to add (with an example if possible)? I assume you are not referring to http auth? https://github.com/elastic/beats/blob/master/libbeat/_beat/config.full.yml#L86

**Comment by ramakrishnachirra** [comment]
Hi Ruflin,
              Thanks for your quick reply.
We have a requirement where we need to have a custom header in HTTP call which may contain device MAC ID , and may be used on the reverse proxy server for validation .After a successful validation, the reverse proxy would forward it to the ElasticSearch. This is someway of custom authentication which we are looking at.

Thanks,
RK
