### ISSUE TITLE
[CI] Fix docker pull from internal registry

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/beats#17683]
if we make a `docker pull` we can pull the image but the command `cd x-pack/metricbeat; mage update build test` cannot pull the image. We have to find why and fix it.
When we fix the issue we can remove the workaround from the Jenkinsfile.

related to https://github.com/elastic/beats/pull/17620

**Comment by kuisathaverat** [comment]
I think `github.com/elastic/beats/v7/libbeat/tests/compose` ignore the Docker credentials.

**Comment by kuisathaverat** [comment]
I think https://golang.org/pkg/os/exec ignores de environment variables defined on the parent environment, because of that HOME is incorrect and the Docker credentials are not defined.

**Comment by andrewkroh** [comment]
I had to do a little hunting to understand why the docker login was required. IIUC the integration tests for Metricbeat that run when TEST_TAGS=oracle require a non-public image.

The integrations tests that are using `github.com/elastic/beats/v7/libbeat/tests/compose` are being run inside of this container:

https://github.com/elastic/beats/blob/6160e20ee5949dafc423d46b22883a87a1622d1c/x-pack/metricbeat/docker-compose.yml#L4-L14

`docker login` persists state to `$HOME/.docker/config.json`. So if Metricbeat needs those credentials then you could add a

**Comment by kuisathaverat** [comment]
Couchbase needs to login too and more will come sure.

**Comment by kuisathaverat** [comment]
I have to tested it but this add the credentials to the metricbeat Docker container, Do the metricbeat Docker container build the Oracle image for the tests?

**Comment by andrewkroh** [comment]
Yes, I believe docker-compose starts this [service](https://github.com/elastic/beats/blob/8a2ed7660482d6e9a12fd6e1dd23db9fe79aafc4/x-pack/metricbeat/module/oracle/docker-compose.yml#L4-L12) on demand when the test asks for it. And the test is running inside of a container.
