### ISSUE TITLE
Generic containers module

### ISSUE THREAD

**Issue by exekias** [elastic/beats#17699]
The number of containers runtime is growing, we could put some effort in figuring out a common way to monitor all of them, instead of approaching them natively.

The goal of this issue is to discuss our options and come up with a plan for a module that can monitor any container runtime.

A few ideas:

 - Investigate opencontainers/containerd to see if there is any metrics API we can use
 - Collect and analyze resource usage at the system level
 - A mix of the above + native implementations of known runtimes (ie docker)

**Comment by endorama** [comment]
I was wondering if there is any initiative around [eBPF](https://ebpf.io/)? Looks very promising to me.

Some resources:
- [Linux BPF Superpowers - Brendan Gregg](http://www.brendangregg.com/blog/2016-03-05/linux-bpf-superpowers.html) (30m, CPU performance monitoring and eBPF introduction)
- [Kernel Tracing With eBPF - Unlocking God Mode on Linux](https://media.ccc.de/v/35c3-9532-kernel_tracing_with_ebpf) (54m, interesting due to the security perspective of eBPF cababilities)
- [Low-Overhead Tracing Using eBPF for Observability into Kubernetes Apps and Services - Gaurav Gupta](https://www.youtube.com/watch?v=ug3lYZdN0Bk) (30m, how to leverage eBPF as low-overhead monitor for K8s applications)

**Comment by ChrsMark** [comment]
Related issue: https://github.com/elastic/beats/issues/17515

**Comment by ChrsMark** [comment]
@MichaelKatsoulis since you already added a `containerd` module could you update this one too with the current situation? Do you see any next steps in the current issue and the `cri-o` related one?

**Comment by ChrsMark** [comment]
> I was wondering if there is any initiative around [eBPF](https://ebpf.io/)? Looks very promising to me.
> 
> Some resources:
> 
> * [Linux BPF Superpowers - Brendan Gregg](http://www.brendangregg.com/blog/2016-03-05/linux-bpf-superpowers.html) (30m, CPU performance monitoring and eBPF introduction)
> * [Kernel Tracing With eBPF - Unlocking God Mode on Linux](https://media.ccc.de/v/35c3-9532-kernel_tracing_with_ebpf) (54m, interesting due to the security perspective of eBPF cababilities)
> * [Low-Overhead Tracing Using eBPF for Observability into Kubernetes Apps and Services - Gaurav Gupta](https://www.youtube.com/watch?v=ug3lYZdN0Bk) (30m, how to leverage eBPF as low-overhead monitor for K8s applications)

Thanks for raising this @endorama !


@akshay-saraswat @mlunadia do you think it would be valuable to investigate metrics collection through ebpf? It can be that we get more accurate and with lower cost metrics but what makes me thoughtful if the required permissions to achieve having ebpf programs loaded. Maybe it can be an advanced feature only for users that are actually interested into this and have the capability to provide the required permissions. Let me know what you think.

**Comment by MichaelKatsoulis** [comment]
> A few ideas:
> 
> * Investigate opencontainers/containerd to see if there is any metrics API we can use
> * Collect and analyze resource usage at the system level
> * A mix of the above + native implementations of known runtimes (ie docker)

This issue needs an update. In beats 8.1 version [containerd module](https://github.com/elastic/beats/pull/29247) will be included as well, collecting metrics from container runtime.
There is also [crio](https://cri-o.io) runtime that may provide some metrics that need to investigated as well. https://github.com/elastic/beats/issues/17515

In Kubernetes regardless of the runtime we collect the metrics mainly from kubelet and kube-state-metrics.
So I believe we need the native implementations of known runtimes for some extra metrics that they provide, or in case a user is using the runtimes without Kubernetes.

**Comment by akshay-saraswat** [comment]
> > I was wondering if there is any initiative around [eBPF](https://ebpf.io/)? Looks very promising to me.
> > Some resources:
> > 
> > * [Linux BPF Superpowers - Brendan Gregg](http://www.brendangregg.com/blog/2016-03-05/linux-bpf-superpowers.html) (30m, CPU performance monitoring and eBPF introduction)
> > * [Kernel Tracing With eBPF - Unlocking God Mode on Linux](https://media.ccc.de/v/35c3-9532-kernel_tracing_with_ebpf) (54m, interesting due to the security perspective of eBPF cababilities)
> > * [Low-Overhead Tracing Using eBPF for Observability into Kubernetes Apps and Services - Gaurav Gupta](https://www.youtube.com/watch?v=ug3lYZdN0Bk) (30m, how to leverage eBPF as low-overhead monitor for K8s applications)
> 
> Thanks for raising this @endorama !
> 
> @akshay-saraswat @mlunadia do you think it would be valuable to investigate metrics collection through ebpf? It can be that we get more accurate and with lower cost metrics but what makes me thoughtful if the required permissions to achieve having ebpf programs loaded. Maybe it can be an advanced feature only for users that are actually interested into this and have the capability to provide the required permissions. Let me know what you think.

Absolutely, IMO, it would be beneficial to explore the eBPF route not only for the advanced users but from the auto-attachment point of view as well. But let's create another issue and discuss it there.
