### ISSUE TITLE
[Metricbeat] kubernetes module to support UNTYPED metrics

### ISSUE THREAD

**Issue by liladler** [elastic/beats#17710]
I am willing to map prometheus metrics to ECS since the prometheus module does not implement is out of the box.
Looking at the source code, I've noticed that the kubernetes module is performing the mapping for the all of `kube-state-metrics` metricsets.
Since both `kube-state-metrics` and prometheus are using the prometheus exposition format, I was planning to take advantage of the existing mapping by directing the kubebernetes module to promethues instead of `kube-state-metrics`, using prometheus federate API.
To align prometheus with `kube-state-metrics`, I've create an ingress rule to redirect all metrics endpoint requests to the federate API  as follows - 
 `/metrics > /federate?match[]={__name__=~"*"}`

However, the prometheus federate API is not exposing the TYPE metadata of the metrics, and instead using the `UNTYPED` type. 

The `UNTYPED` metedata type is not supported by the prometheus helper therefore the metrics are being dropped - 
https://github.com/elastic/beats/blob/3f5005861561e53b198b316236ec5c8bc07fa56b/metricbeat/helper/prometheus/metric.go#L260

Once the `GetValue` function will be added to the `UNTYPED` type, the integration from prometheus to ECS should be simple, and dashboards should work OOB.

**Comment by ChrsMark** [comment]
@liladler if i understand it correctly you want to avoid scraping from `kube-state-metrics`? Also what ECS fields you are interested into?
