### ISSUE TITLE
Support AWS Firelens

### ISSUE THREAD

**Issue by lifeofguenter** [elastic/beats#17731]
General info: https://aws.amazon.com/blogs/containers/under-the-hood-firelens-for-amazon-ecs-tasks/

AWS offers a managed docker container hosting service called "Fargate" (https://aws.amazon.com/fargate/). It is possible to run sidecars, but access to the docker-host is limited. As such, running filebeat as sidecar with the docker-input option as it relies on accessing files on the docker-host itself: https://www.elastic.co/guide/en/beats/filebeat/master/running-on-docker.html, which one does not have access to with Fargate.

To allow 3rd parties to tap into the logs, AWS recently released a new method/service called "Firelens". Currently it majorly supports fluentd/fluentbit, which then run as a sidecar and are able to intake logs from other containers within the same task.

It would be great if filebeat were also supported.

My guess is, that internally Fargate uses fluentd logdriver which is officially supported by docker: https://docs.docker.com/config/containers/logging/fluentd/ - I am not sure though, but it is according to them a open format/protocol.

**Comment by kaiyan-sheng** [comment]
Hello @lifeofguenter, thanks for creating this feature request. Could you add more information here please? That would be very help! Thank you!

**Comment by sorantis** [comment]
Firelens uses both fluentd and fluent bit. It seems that for container services fluent bit is the preferred option because of the amount of 3pp connectors.

**Comment by kaiyan-sheng** [comment]
@Udayel I think this is covered by the work you've been working on. Could you comment here please? Thanks!

**Comment by kaiyan-sheng** [comment]
https://github.com/aws-samples/amazon-ecs-firelens-examples/pull/55 is merged into AWS samples for ecs firelens.

**Comment by lifeofguenter** [comment]
Thanks @kaiyan-sheng those are great news <3

I might have been unclear with my original request which is to add support to filebeat for the fluentd-forwarding protocol as an input (https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html).

This would allow us to run filebeat as a sidecar to work with firelens directly. Currently only fluentd/fluentbit is supported, but some might prefer the configuration of filebeat.

I don't actively need this anymore. Fluentbit was good enough to ship the logs via a homegrown router to Elasticsearch :)
