### ISSUE TITLE
Issues with the exported fields in Metricbeat

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#1774]
The following changes I suggest to be done in Metricbeat:
- use `type` to filter for the metricset (example `type: filesystem`) instead of `metricset.name: filesystem`
- `system.memory.swap.used.pct` -> `system.swap.used.pct`
- `mysql.status.bytes.sent` -> `mysql.status.sent.bytes`
- `apache.status.total_kbytes` -> shouldn't be in in bytes for an easy representation in Kibana?
- `mysql.status.bytes.received` -> `mysql.status.received.bytes`
- `system.memory.total` -> `system.memory.total.bytes` 
  Shouldn't we have all values that are expressed in `bytes` contain `.bytes`?

cc-ed @ruflin @andrewkroh @tsg

**Comment by ruflin** [comment]
Going through the list from top to bottom:

* For the type: We had that initially but decide to not use type. See also https://www.elastic.co/blog/index-vs-type
* Making this as described, would required to add a metricset for swap which I somehow like. It depends a little bit if users always need all the data together anyways or are only interested in sub sets. @urso made here a suggestion for an alternatives format: https://github.com/elastic/beats/issues/1757
* Agree, your proposal seems to make more sense
* This is a very good question. Should we standardise the units and do some conversions on it. I like the idea but not sure yet of the impact. Definitively worth discussing in more detail.
* For the time being, we set the "type" only if there were multiple types. Setting the type can happen at two places, either in the template or directly in the metric. We should investigate this further.

**Comment by ruflin** [comment]
We never did this changes I think as they are breaking and there was no direct benefit expect nicer naming. Going to close this issue and see if we stumble over it again.
