### ISSUE TITLE
Filebeat meta data fields

### ISSUE THREAD

**Issue by wjmcdonald** [elastic/beats#1775]
Feature Request: 

We have a file that contains information written by another application. It only has one line, but doesn't contain any timestamp information. I'd like to use the timestamp on the file itself. In general, since filebeat is reading files, shouldn't it make some file metadata like (creationTime, modifiedTime, lastReadTime, creator, size, etc) available to the plugin as optional fields?

**Comment by ruflin** [comment]
For more details also see: https://github.com/elastic/filebeat/issues/315
