### ISSUE TITLE
Enhance Usability and Functional Discoverability in Default heartbeat.yml File In Installer

### ISSUE THREAD

**Issue by drewpost** [elastic/beats#17774]
I recently went through the "new to Heartbeat, first time user experience" and I walked away with a handful of tweaks we could do to make this experience easier for customers and also increase discoverability of our capabilities.

- Add the Monitor "name" field by default
- (bug) potential spacing issue on the lat/long line of the overseer geo meta data that will impact heartbeat loading in and running
- I suggest that we make reload.enabled as true to prevent multiple sudo service heartbeat-elastic stop and sudo service heartbeat-elastic starts every time we tweak a YML config
- Add in sample monitor types for TCP and IMCP with their relevant config points
- Default capturing response body content capture to "always"
- Enable tags by default with a default value (so this will populate the UI)

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
