### ISSUE TITLE
[Heartbeat] ICMP RTT field is missing

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#17796]
We [document](https://www.elastic.co/guide/en/beats/heartbeat/master/exported-fields-icmp.html) the `icmp.rtt.us` field, but probably lost it at some point in 7.x. We should bring this back, it's useful because it tracks ping time less DNS resolution time. 

This came up in [this forum thread](https://discuss.elastic.co/t/cannot-show-ping-because-icmp-rtt-us-no-value/226011/6)

**Comment by shahzad31** [comment]
This is working as expected as part of test-plan 
![image](https://user-images.githubusercontent.com/3505601/82915295-d5c78e00-9f70-11ea-82c8-02f8f730d6f5.png)
