### ISSUE TITLE
[Metricbeat] Incorrect percentages when a process uses multiple cores on the kibana dashboard

### ISSUE THREAD

**Issue by premierpsp** [elastic/beats#17820]
Hi,
When i have a process using multiples cores the percentage values ​​are wrong in Top Processes By CPU module.

Top Output:
![image](https://user-images.githubusercontent.com/46852468/79705760-d3448b00-8284-11ea-8d16-f6ce4346312d.png)

Kibana dashboard (Top Processes By CPU module):
![image](https://user-images.githubusercontent.com/46852468/79705798-ed7e6900-8284-11ea-8b6a-fa3fff7d5bc2.png)

I also cannot set the conditions for thresholds. If I select a condition it is not saved:
![image](https://user-images.githubusercontent.com/46852468/79706601-c1181c00-8287-11ea-8b8c-002781a2b206.png)

Meanwhile, the CPU Usage Gauge is ok:
![image](https://user-images.githubusercontent.com/46852468/79706098-105d4d00-8286-11ea-9135-d6b49c458318.png)

Thank you guys.

**Comment by andresrc** [comment]
Hi @premierpsp!

Thank you very much for creating this issue. However, we would kindly like to ask you to post all questions and issues on the [Discuss forum](https://discuss.elastic.co/c/beats) first. In addition to awesome, knowledgeable community contributors, core Beats developers are on the forums every single day to help you out as well. So, your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue with the new information or open a new one.
