### ISSUE TITLE
Filebeat - Cloud Foundry Input not handling app.id and app.name correctly for access logs

### ISSUE THREAD

**Issue by bvader** [elastic/beats#17846]
**Summary:** 
Filebeat : The Cloud Foundry Input and add_cloudfoundry_metadata processor are not handling / interpreting the `cloudfoundry.app.id` GUID correctly for the `cloudfoundry.type : access`

Sample Good GUID : 
```
cloudfoundry.app.id: 4ef05e5d-d2a6-4c58-9229-d112587b74dd
cloudfoundry.app.name: cardatabase-back-end
```

Sample BAD GUID : 
`cloudfoundry.app.id: low:3046190763798940950 high:12644936126740546741`

**The result of this is:**
1. The meta data processor fails and so the `cloudfoundry.app.name `is not found, cached and populated
2. Because `cloudfoundry.app.name` is not found and cached, the api call to get the metadata is called repeatedly for each access to the app and thus filebeat is adding significant log events to the overall log stream
3. This is potentially adding undo load to the the cloud foundry meta data API

**Example Data** 
Discover
Index Pattern : `filebeat-*`
`url.path : *3046190763798940950* or cloudfoundry.app.id : *3046190763798940950*'`

<img width="1652" alt="Screen Shot 2020-04-20 at 1 15 34 PM" src="https://user-images.githubusercontent.com/15572155/79796246-139a1c80-830a-11ea-9282-3fc207c2ed1c.png">

Note both the original HTTP Accees log and the call to the Meta Data API have the malformed GUID.

<img width="1347" alt="Screen Shot 2020-04-20 at 1 16 37 PM" src="https://user-images.githubusercontent.com/15572155/79796224-07ae5a80-830a-11ea-9297-56f450efd588.png">

**Expected Result.**
The GUID is properly handled,
The `cloudfoundry.app.name` is available and cached
There is a reduced load on the cloudfoundry API.

**Comment by exekias** [comment]
@blakerouse is this fixed by https://github.com/elastic/beats/pull/17847?

**Comment by blakerouse** [comment]
@exekias Yes it was, forgot to add it to the PR description.
