### ISSUE TITLE
Winlogbeat message field is not parsing properly

### ISSUE THREAD

**Issue by yeruvass** [elastic/beats#17852]
I'm using winlogbeat for pushing all windows events to elasticsearch. Parsing is not happening properly.

One of the examples is under “Message” there is “Properties” which when parsed in winlog.event_data.Properties does not show up correctly

Actual message :-1
<img width="576" alt="message" src="https://user-images.githubusercontent.com/5181193/79825696-d043ba80-83aa-11ea-8c81-a5275848bc52.png">
Parsed field :- 
<img width="576" alt="parsed_event" src="https://user-images.githubusercontent.com/5181193/79825705-dcc81300-83aa-11ea-89a2-105ed9c9ea04.png">
It should come read property but coming some number %%7684

**Comment by andrewkroh** [comment]
Discuss post (duplicate): https://discuss.elastic.co/t/winlogbeat-data-is-not-parsing-properly/228820/2

Closing as this does not appear to be a bug (at least not yet).
