### ISSUE TITLE
Icon for Elastic Agent

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#17871]
We need to choose an icon for Elastic Agent to display on the Elastic downloads page https://www.elastic.co/downloads/. We also need to choose an icon for our installer apps.

**Comment by mostlyjason** [comment]
Since feature freeze for 7.8 is only two weeks away, I was thinking we could pick a temporary existing icon for our Alpha release. We can aim to have a custom logo for our GA release.

**Comment by hbharding** [comment]
@ruflin @jen-huang @mostlyjason To help narrow our choices for Alpha, here are 3 options for "Elastic Agent" for the Downloads page. These are existing icons that were created by the creative services team and may already be in use elsewhere. More options can be found on the [EUI docs](https://elastic.github.io/eui/#/display/icons) under the "Apps" section.

![image](https://user-images.githubusercontent.com/847805/79902217-19156680-83df-11ea-8585-dda1897b604b.png)
> `SavedObjects`, `Metricbeat` and `IndexManagement`

Of the 3, `SavedObjects` has my vote.
- We're already using it for Ingest Manager, which is used to manage Elastic Agents. It makes sense for that icon to follow you from Kibana to the Downloads page. 1 less icon to learn.
- Visually, I think the icon portrays moving and storing data, which is part of what the Elastic Agent does.
- I think the icon is no longer in use by the "Saved Objects" app, so it feels safe to use.

<details><summary>Screenshot of saved objects app</summary>

![image](https://user-images.githubusercontent.com/847805/79903649-6db9e100-83e1-11ea-89f1-f8ce6e1f4490.png)

</details>
<details><summary>Screenshot of Ingest Manager</summary>

![image](https://user-images.githubusercontent.com/847805/79904334-81197c00-83e2-11ea-90af-e5a41c9d6729.png)

</details>
<details><summary>Screenshot of Downloads Page</summary>

![image](https://user-images.githubusercontent.com/847805/79904386-9393b580-83e2-11ea-92c1-8ed1d5acc655.png)


</details>


Long term, we need to work with creative services for a proper Elastic Agent logo. 

@JessSmithSup if you have an opinion on what we should do for the short term please chime in, or i'd be happy to chat. Hate to put stuff on your plate last minute. I plan to open an issue in the design repo for you soon for our beta or GA release. The icon in Ingest Manager is going to go away when we introduce the new "iconless" navigation in Kibana.

**Comment by hbharding** [comment]
As for an "icon for our installer apps" - I don't have much experience here or really know what this looks like. I'm curious to see what we currently use before I propose something unique. If operating systems provide a default icon or allow for no icon, I'd be tempted to just use that for alpha. I'll look into this.

**Comment by JessSmithSup** [comment]
@hbharding thanks for the ping. Brand prefers to avoid reusing any of the product feature icons if at all possible, but if I had to choose I would say the "saved Objects". 2 weeks might still be enough time to create an icon if we have a solid idea, otherwise, we have a set of [generic icons](https://drive.google.com/drive/u/0/folders/1gbF8ADclMzoRu26C_dGdP9r7iVcYSUDg) that might work better.

Let me know thoughts

**Comment by mostlyjason** [comment]
@hbharding savedObjects could work as a temporary icon, unless you think one of the generic ones would be better

**Comment by mostlyjason** [comment]
Closing this issue so we can track work here https://github.com/elastic/Design/issues/2469
