### ISSUE TITLE
Filebeat fails with ambiguous error when using multiline

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#1788]
5.0 Alpha 3

If you run filebeat with a single multiline option below:

```
  multiline.pattern: ^\[
```

It will fail with an ambiguous message:

```
./filebeat
Exiting: Error in initing prospector: missing required field accessing 'filebeat.prospectors.0.multiline'
```

It doesn't tell you what required field is missing.  From trial and error, it looks like in order for it to run with multiline option, `multiline.match` is also required in the configuration.  This is not clear in the error message reported above.  Let's all specify this as "required" in the default yml file comments for multiline.match.

**Comment by tsg** [comment]
@urso would it be possible to name the required field in the error message?

**Comment by urso** [comment]
@tsg yes, the missing name is a bug in ucfg. Related ticket urso/ucfg#31

**Comment by tsg** [comment]
This should fixed in the last alpha.
