### ISSUE TITLE
Report number of handles / file descriptors held by processes

### ISSUE THREAD

**Issue by kinghrothgar** [elastic/beats#1789]
I am in the process of adding number of file descriptors into metricbeat and or topbeat.  After this gets merged https://github.com/elastic/gosigar/pull/30, I want to start implementing it in beats.  As it appears metricbeat is just calling topbeat under the hood for most stuff, it seems like I should add it there first and make the needed changes on the metricbeat side?

**Comment by ruflin** [comment]
Currently the best option is to do what you described above. As Topbeat and Metricbeat are in one repo, the changes can go into 1 PR. We plan to move parts of topbeat into gosigar and parts into metricbeat, but it is not clear yet how this will exactly look.

Thanks for your contribution.

**Comment by andrewkroh** [comment]
@kinghrothgar Just checking in. Are you still pursing this? Is there anything I can do to help?

**Comment by andrewkroh** [comment]
I opened PR #2257 to add FD usage information to the system.process MetricSet in Metricbeat.

I think the overall system FD usage information could go into a system.info MetricSet if we had one. That MetricSet would report things like OS version, uptime, total FD usage, virtualization info, etc.
