### ISSUE TITLE
Auditbeat file integrity doesn't scan shares nor mount points

### ISSUE THREAD

**Issue by ormam** [elastic/beats#17903]
auditbeat file integrity doesn't scans shares nor mount points

I tried to mount windows share to a windows machine with a auditbeat on it mapped to Z:
The auditbeat does not recognizing changes there

moreover i tried mounting the same share to a linux machine and the beat doesn't recognizing changes as well
but when i restart the auditbeat on linux it detected the changes

any ideas about windows and linux ?

For confirmed bugs, please report:
- Version: 7.6.2
- Operating System: windows & liux
- Discuss Forum URL: https://discuss.elastic.co/t/auditbeat-file-integrity-doesnt-scans-shares-nor-mount-points/229291
- Steps to Reproduce:

**Comment by ycombinator** [comment]
Hi, we use GitHub issues for enhancements and confirmed bugs. For questions and discussions, we use discuss.elastic.co. I see you already have already created a post on discuss at about the same time as you created this issue. Please wait for someone to respond to your post on discuss. Thanks!
