### ISSUE TITLE
How to configure using this force panel?

### ISSUE THREAD

**Issue by zhaoxiaole** [elastic/beats#1790]
Where I can get this configuration example of FIG effect?
![image](https://cloud.githubusercontent.com/assets/14342521/15771222/daee1f56-299b-11e6-9c06-a5dadd719f2b.png)
Looking forward to your reply, thank you!

**Comment by zstyblik** [comment]
@zhaoxiaole, may be here - https://www.youtube.com/watch?v=6h6mhaGFAbU?

**Comment by zhaoxiaole** [comment]
@zstyblik I use the version is packetbeat + Elasticsearch + kibana3, this version has a force panel, but it seems, and you gave me this video is not the same,thanks

**Comment by zstyblik** [comment]
@zhaoxiaole, my bad, sorry. Panel seemed similar to me as the one in Graph. Now I know it's not, resp. is different. Good luck.

**Comment by zhaoxiaole** [comment]
It should be how to configure, where the main role is what？
![image](https://cloud.githubusercontent.com/assets/14342521/15774845/26f62f96-29b1-11e6-8524-4474e352950c.png)

**Comment by tsg** [comment]
@zstyblik See this [link](https://www.elastic.co/guide/en/beats/packetbeat/current/_viewing_the_topology_diagram.html). Unfortunately that map is only supported with K3. We do hope to have an improved version that works with K4/K5, but don't have any timelines on it.

**Comment by zstyblik** [comment]
@tsg, I see. Thanks.
