### ISSUE TITLE
[Elastic-Agent] Make duration default to 30s and configurable.

### ISSUE THREAD

**Issue by ph** [elastic/beats#17900]
The current period for checking the API is every 2 seconds this is way too frequent we need to move that to 30 sec and make it configurable.

**Comment by michalpristas** [comment]
i remember we had it set to 30s and we moved it to 2s to achieve "immediate action" behavior as we were using sockets. 
are we ok with prolonging the feedback loop now?

**Comment by ph** [comment]
@michalpristas I do remember this discussion to move to 2sec, but this will seriously hurt Kibana.  For the scale of alpha 1 we have decided to move that value by default to 30sec. Users can still change that values in the configuration if they want to have a quicker feedback at the risk of seriously impact the Kibana server.

**Comment by ruflin** [comment]
@ph You mention it can be changed in the config. How is this possible when connected to Fleet?

**Comment by ph** [comment]
@ruflin right now its a local-only configuration but we could expand that to fleet. Not sure how that will look like and we would need to make a tiny changes in the gateway to make it reconfigurable.

@ruflin  WDYT to have an issue for b1 that keep a list of configurable options in the agent and with  yes not to make it configurable via fleet?

**Comment by ruflin** [comment]
+1 on having this option. In general I think all options must also be configurable in Fleet, even if it is through pure yaml.
