### ISSUE TITLE
[Winlogbeat] event.action missing for event.code 4648

### ISSUE THREAD

**Issue by willemdh** [elastic/beats#17926]
- Version: 7.6.1
- Operating System: Windows 2016 Server
- Discuss Forum URL:https://discuss.elastic.co/t/winlogbeat-event-action-for-4648/227919

Using the Winlogbeat 'security ' module I noticed event.code 4648 does not (yet) have an event.action defined:

```
var eventActionTypes = {
    "4624": "logged-in",
    "4625": "logon-failed",
    "4634": "logged-out",
    "4672": "logged-in-special",
    "4688": "created-process",
    "4689": "exited-process",
```

4624, 4625 and 4648

```
* 4624 - An account was successfully logged on.
* 4625 - An account failed to log on.
* 4648 - A logon was attempted using explicit credentials.
```

The result is that the 4648 events have 'Logon' as event.action.
The resulting histogram for `event.action` for logon events ooks like this:

![image](https://user-images.githubusercontent.com/6462991/80079528-b5ab4600-8550-11ea-829c-481fe7e41c00.png)

event.action should be something like `explicit-logon-attempt`

**Comment by willemdh** [comment]
Pinging

**Comment by willemdh** [comment]
Ping -t2

**Comment by jamiehynds** [comment]
@willemdh can you confirm if this is still an issue for you? I just checked our latest Windows Security pipeline for both Filebeat module and Agent integration, and `event.category` is set to `logged-in-explicit`

https://github.com/elastic/beats/blob/main/x-pack/winlogbeat/module/security/ingest/security.yml#L107

**Comment by willemdh** [comment]
Will test.

**Comment by willemdh** [comment]
![image](https://user-images.githubusercontent.com/6462991/161383370-1baa75c5-bf95-4e13-b9d1-81f904566849.png)

Sorry @jamiehynds , aparrently fixed indeed => Closing

**Comment by jamiehynds** [comment]
Thanks for confirming @willemdh!
