### ISSUE TITLE
Metricbeat - Azure database account - add dashboards for Mongo, Cassandra, Gremlin, SQL

### ISSUE THREAD

**Issue by narph** [elastic/beats#17929]
New azure supported metrics for the database account namespace have been added for the Cassandra, Mongo, Gremlin, Sql.
Would be great to have several dashboards added to the  database account overview one.
Original PR https://github.com/elastic/beats/pull/17901

- [ ] Mongo
- [ ] Cassandra
- [ ] Gremlin
- [ ] SQL

cc @sorantis

**Comment by ravikesarwani** [comment]
Closing as stale. Already done as part of various integrations work.
