### ISSUE TITLE
Add Openshift scenario for CI

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#17962]
This would be the next step of https://github.com/elastic/beats/issues/17516.
We would like to test our Kubernetes stuff against Openshift. Currently we test our manifests against Kubernetes versions but testing against Openshift will be confirming our compatibility on constant basis.

Things to check:
1. manifests are being deployed as expected
2. run integration tests for modules

This is mostly an extension of  #17516. 
Related to https://github.com/elastic/beats/pull/17656.

cc: @exekias @jsoriano @blakerouse

**Comment by exekias** [comment]
Thanks for opening this! I think the second reference link you added is not correct, please have a look

**Comment by ChrsMark** [comment]
Still valid.

**Comment by mbudge** [comment]
+1 for Azure Openshift.
