### ISSUE TITLE
Edit module documentation for Filebeat

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#17986]
The module documentation has quite a few quality issues and grammatical nits because it has been authored by many different people. We need to do a technical edit to clean up the most egregious issues. Here's a list of some modules that definitely require work:

- [ ] [Azure module](https://github.com/elastic/beats/blob/master/x-pack/filebeat/module/azure/_meta/docs.asciidoc)

**Comment by dedemorton** [comment]
I never got back to this to add module names, but here's another editorial issue that we should resolve. It's kind of minor, but I think has some implications where we might be using trademarked names. https://github.com/elastic/beats/issues/18220

**Comment by 8yumzy88** [comment]
Slightly off topic, but with regards to "filebeat" and "documentation" and "modules".  I cannot find any documentation that explains how to load "custom" modules (e.g., in this case from the x-pack/beats git repo).  For example, how to setup the module path in filebeat.yml such that you can use both the modules in /etc/filebeat/modules.d and also xpack modules from /etc/filebeat/module/xxx/  ???

**Comment by dedemorton** [comment]
@8yumzy88 Please accept my apologies for missing your comment. If this is still an issue, please open a new issue to describe the problem. 

This issue is too broad, so I am closing it.
