### ISSUE TITLE
[Filebeat][Module Request] Microsoft ATP API support

### ISSUE THREAD

**Issue by P1llus** [elastic/beats#17997]
This issue is to track the progress of a filebeat module for Microsoft ATP API.

When a demo environment is present to test, first an investigation needs to be done if the capabilities of the httpjson input plugin supports the Oauth implementation expected by the API. If not a separate PR would have to be created to extend that input plugin first before the module can be created.

When the module creation has started, a PR will be linked to this issue by me.

**Comment by andrewkroh** [comment]
Closed by https://github.com/elastic/beats/pull/19197.
