### ISSUE TITLE
No such input type exist: 'mqtt' in Filebeat

### ISSUE THREAD

**Issue by BigGitWorld** [elastic/beats#17996]
Elastic document in the [configure inputs](https://www.elastic.co/guide/en/beats/filebeat/master/configuration-filebeat-options.html) page says that:
> You can configure Filebeat to use the following inputs:

But in practice, the MQTT input does not exist.  I will receive the below error when add mqtt to filebeat.yml config file:
```
ERROR	instance/beat.go:933	Exiting: Error while initializing input: Error creating input. No such input type exist: 'mqtt'
```
I think you have to modify the document and say that this feature will be coming from the Filebeat version 7.7.0.

- Version: 
Filebeat 7.6.2
- Operating System: 
Ubuntu 16.04

**Comment by P1llus** [comment]
On the menu on the right side, it is possible to view documentation for specific versions. The documentation you linked is to the master branch, which is where a lot of our content is located before being included in a release branch.

If you change this from master to 7.6(Current) then MQTT should not be on the list. Can you confirm this?

**Comment by BigGitWorld** [comment]
Thank you. you are right.
But I think its better to modify the way that elastic site works to do not confuse users.
I think the elastic site has very duplicate contents that makes difficult to work with them.
Simplicity is always the best option.

**Comment by BBDooooog** [comment]
I used version 7.7.1 and still couldn't boot. I want to know how the Windows version views the boot log.
