### ISSUE TITLE
Better support and documentation for stderr logging (journald)

### ISSUE THREAD

**Issue by kinghrothgar** [elastic/beats#1807]
So after much searching I believe it is possible with libbeat to log to stdout / stderr as is stated here https://github.com/elastic/beats/blob/master/libbeat/docs/loggingconfig.asciidoc#logging-format.  I still however do not know what to set in the config to get it to do this.  Furthermore, it says "this option should be used mainly for debugging."  The problem is that on journald systems, which are quickly becoming the norm for Linux, logging to stdout is what you want the program to do.  Is there something in the implementation of libbeat's stderr logging that makes it not fit for production use?  Also, there needs to be an option to have the stderr logging not include the timestamp as that is added by journald.

**Comment by ruflin** [comment]
Do log to stderr you must start the beat with the `-e    Log to stderr and disable syslog/file output` option. There is currently not config option for this.

We had recently a discussion that we need to rethink / refactor our logging. We will also take the above comments into account for this.

**Comment by neumayer** [comment]
I stumbled across the same issue just last week.

I'm currently running both my application and filebeat via supervisord (and as such start filebeat with the -e). I agree that a config option for that seems to make sense, then stdout/stderr logging would be on the same level as the other options. The exact same problem occurs when running stuff in docker.

Anyway, I guess I just want to say I'm glad it's on the agenda :-)
