### ISSUE TITLE
Make log level reloadable in beats

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#18081]
The goal here is to enable agent to change log level on the fly. at the moment we can change it at start using configuration option but we don't have ability to change it after beat is started

**Comment by yaf0** [comment]
> The goal here is to enable agent to change log level on the fly. at the moment we can change it at start using configuration option but we don't have ability to change it after beat is started

I'm sorry , I'm wondering how to change log level before starting,I mean the log from the beat client ( /var/log/filebeat/filebeat)
and the default level is INFO.
_Failed to publish events: temporary bulk send failure_
For I have an same error(above) from various problems,I want to make it clear that each problem means what.
I make out some of them.but some I can't.
So I want to see  more logs such as debug? if it is possible.

**Comment by ph** [comment]
Going to remove this from the ingest managemetn team, we have a solution that work.

**Comment by ruflin** [comment]
@ph I'm still thinking we should push an option forward that does not require restarting the process. Lets assume a process has an issue and you want to dig into the details by getting more logs. Restarting the process might make the issue disappear.

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
