### ISSUE TITLE
Add URL suggestion to Filebeat Okta module documentation

### ISSUE THREAD

**Issue by jasonslater2000** [elastic/beats#18099]
The API endpoint URL for our Okta Filebeat module isn't in our docs, e.g.

 https://{company}.okta.com/api/v1/logs

can we please add it so customers know how to configure the module?

**Comment by threat-punter** [comment]
I went through the process of enabling and configuring the Okta Filebeat module and, I agree with @jasonslater2000 that the [docs](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-okta.html) could be more comprehensive.

We've written 16+ Okta rules for the detection engine, so more detailed docs with a config example would really help users configure the Okta module and make use of these rules to protect their organization.

In addition to including the Okta System log URL, can we please include the following info?

- The details need to be entered into the Okta module: `/etc/filebeat/modules.d/okta.yml`
- Mention that an Okta API token is required in the config file to pull Okta System logs on a regular cadence
- A link to Okta’s System log API documentation: https://developer.okta.com/docs/reference/api/system-log/
- An example config file like what's in the [AWS Filebeat module docs](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-aws.html) would be really helpful to our users, I expect

**Comment by threat-punter** [comment]
The [7.9 docs](https://www.elastic.co/guide/en/beats/filebeat/7.9/filebeat-module-okta.html) provide more comprehensive instructions on how to configure the Okta Filebeat module.
