### ISSUE TITLE
add option to switch on/off redis.return_value to reduce network consumption

### ISSUE THREAD

**Issue by thomassun** [elastic/beats#181]
in production environment, redis server run with heavy network load. For a redis server with consuming more than 50% of network bandwidth,  say 500M/s of a 1Gb network, when we install packetbeat on it, the network transaction will almost be double because redis.return_value duplicates the data sent to redis client to output endpoint, that makes redis server run over the network capacity which may impact redis clients.
It would be better if we can switch off redis.return_value just like we can switch off response_raw by set "send_response" to false.

**Comment by monicasarbu** [comment]
For now, we don't have anything in place for switching off some fields. We will find a way to solve it in the next releases.

**Comment by monicasarbu** [comment]
Similar with #179

**Comment by sk163** [comment]
I also encountered the same problem, really looking forward to solve this problem, thank you! I ask about what time can be released?

**Comment by lifeofguenter** [comment]
+1
