### ISSUE TITLE
[Elastic-Agent] Work around unix socket path length limit

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#18118]
Elastic agent uses unix sockets or windows named pipes to create a communication layer between agent and a process it manages. 

What is unfortunate is a length limit operating systems put on path lengths:
- Windows: 256 characters [link](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createnamedpipea#parameters)
- Unix: 108 chars [link](http://man7.org/linux/man-pages/man7/unix.7.html)
- Mac and BSD: 104

Construction of this path in agent consist of few variables which makes it easy to overflow this limit.
we create unix socket inside data path (where agent lives + data, or provided by user)
we post fix this by output name and program name which are also not limited in length.

Previously we had unix socket created in `/var/run` which resulted in shorter paths but a need for root privileges.

The problem is we do not know there is a problem until beat crashes with unknown error. Not until we search beats logs which are not helpful as well because golangs default answer for this is `bind: invalid argument` [golang issue](https://github.com/golang/go/issues/6895#issuecomment-98006662)

For this reason this should be part of health checks (https://github.com/elastic/beats/issues/17737) which will become part of beats so we know that something failed and ideally what failed. 

We were thinking together with @ph about the right strategy but we could not find the right solution here which allows us to stay outside of paths which requires us to run elevated and not putting some funny length limits to data path (where agent lives), output name and program name.

**Comment by ruflin** [comment]
Could we put the sockets into /tmp/elastic-agent/* ?

**Comment by michalpristas** [comment]
i think `/tmp` seems fine except that tmp is wide open by default so we might need to check permissions of the socket

any other thoughts @ph

**Comment by ph** [comment]
Yes socket permissions would be an issue.

Could we have two strategies depending on the execution?
- /tmp/ok.sock for tar.gz|zip
- /var/run/elastic-agent/.. when  run from a package.

**Comment by ph** [comment]
We can close this @michalpristas ?

**Comment by michalpristas** [comment]
i think for now it's good
