### ISSUE TITLE
Escape periods in field names to avoid Mapper Parsing Exception [packetbeat]

### ISSUE THREAD

**Issue by mikesparr** [elastic/beats#1812]
Reference discussion: https://discuss.elastic.co/t/mapper-parsing-exception-periods-in-field-name/51811/4

Since packetbeat allows you to capture http headers and cookies, there's no way to control what some 3rd-party frameworks name their variables, and packetbeat should escape characters that will fail in ElasticSearch Mapping Parser.  
- expect packetbeat output to Elasticsearch to not break during ES bulk loading

**Comment by ruflin** [comment]
The problem with the header is that it contains fields like `aaa.bbb` with the dot notation which is not allowed under elasticsearch 2.x. I suggest we replaced `.` either with `_` or `-`. Based on the naming standard we use in other fields `_` would probably be the better option. @tsg Any thoughts here?
