### ISSUE TITLE
[Metricbeat] [metricset prometheus collector] Multiple match query

### ISSUE THREAD

**Issue by RoySunnySean007** [elastic/beats#18123]
Dear Metricbeat experts,

I am using metricset prometheus collector and using the following query to scrape data from prometheus. And I found only the last query ('match[]': '{job="jobC"}') take effect.
Can I use multiple query for metricset prometheus collector?  If YES, could u please kindly let me know how? If NO, do u have any suggestion for my requirement?

- module: prometheus
  period: 10s
  hosts: ["localhost:9090"]
  metrics_path: '/federate'
  headers:
    accept: "text/plain"
  query:
    'match[]': '{job="jobA",cluster_arn=~".*clusterA"}'
    'match[]': '{job="jobB",cluster_arn=~".*clusterB"}'
    'match[]': '{job="jobC"}'

Thanks,
Roy

**Comment by andresrc** [comment]
Hi @RoySunnySean007 !

Thank you very much for creating this issue. However, we would kindly like to ask you to post all questions and issues on the [Discuss forum](https://discuss.elastic.co/c/beats) first. In addition to awesome, knowledgeable community contributors, core Beats developers are on the forums every single day to help you out as well. So, your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue with the new information or open a new one.
