### ISSUE TITLE
[Cohesity] metricbeat vsphere module, add cluster name to host details

### ISSUE THREAD

**Issue by jasonslater2000** [elastic/beats#18137]
This ER is related to the VSphere module for Metricbeat.

ESX nodes are often clustered together for HA. VMs share resources from the cluster nodes (hosts).

Including cluster name in the ESX Host helps with grouping the nodes together as a cluster to view the overall cluster health.

Request is to include the cluster name in the host details
Also include the Host and Cluster details in the VirtualMachine metrics
Cluster Data Center property would be helpful as well (ESX-Host --> ESX Cluster --> Cluster Datacenter)

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
