### ISSUE TITLE
lowercase causes missed detections and broken searches

### ISSUE THREAD

**Issue by neu5ron** [elastic/beats#18154]
In the Zeek HTTP file, there is a lowercasing of `http.request.method` - shown here: https://github.com/elastic/beats/blob/f39d8695bf5faa73f496173e56a35ace3ef9894b/x-pack/filebeat/module/zeek/http/ingest/pipeline.yml#L53

`http.request.method` will have values of `POST`, `GET`, `OPTIONS`, etc... the vast majority of dashboards, visualizations, searches, threat hunts, etc..  are all built on how the vast majority of HTTP requests work ie: the value of `GET` for outbound stuff or `POST` for inbound web attacks.
couple this with values being case sensitive, there is no even "fail safe" that would have made this not such an impactful thing.
also, this field can be used for anomalous variations of the above, such as looking for `PoST`.

**Comment by leehinman** [comment]
I definitely should have marked this as a breaking change, I'll fix that.

The reason for making it lowercase is because it is an ECS field and the doc for the field is:
```
HTTP request method.

The field value must be normalized to lowercase for querying.
See the documentation section "Implementing ECS".

type: keyword

example: get, post, put
```
@webmat & @MikePaquette thoughts?

What do you think about having "zeek.http.method" as the unmodified request method?

**Comment by neu5ron** [comment]
cross reference for Suricata too, same scenario - https://github.com/elastic/beats/blob/6d7d919967e0da052a40435240d41e5a8f7fee35/x-pack/filebeat/module/suricata/eve/ingest/pipeline.yml#L5

**Comment by leehinman** [comment]
And Apache & nginx
