### ISSUE TITLE
Kafka module support kafka logs from apache kafka 2.2.2 or higher version

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#18164]
**Describe the enhancement:**
As a user of Filebeat I would like to collect logs from Confluent kafka 5.2.3 (apache kafka 2.2.2). 

**Describe a specific use case for the enhancement or feature:**
Support logs coming from kafka 2.2.2

Sample logs: 
[state-change.log.gz](https://github.com/elastic/beats/files/4620510/state-change.log.gz)

**Comment by urso** [comment]
It looks that the logs are different because the logging formatter configuration has been changed. Do we know if the configuration has been by the user or does confluent ship a modified configuration?

**Comment by kvch** [comment]
@urso Confluent does not change the default logging configuration. It was the user who modified the logger, but we do not have their configuration.
