### ISSUE TITLE
[Agent] Update warning text to Experimental messaging

### ISSUE THREAD

**Issue by jen-huang** [elastic/beats#18214]
To match with our other external messaging, we should change this to say "is currently experimental" instead of "is currently in Alpha":

https://github.com/elastic/beats/blob/66609a3fd676c0b3b3facf0b4536150c8b2fa55e/x-pack/elastic-agent/pkg/agent/warn/warn.go#L14

**Comment by ruflin** [comment]
Opened https://github.com/elastic/beats/pull/18227
