### ISSUE TITLE
Could we use upx to shrink beats?

### ISSUE THREAD

**Issue by jordansissel** [elastic/beats#1822]
Go programs are generally large binaries, but [someone](https://github.com/pwaller/goupx) has explored using [upx](http://upx.sourceforge.net/) to pack the binary.

I tested this with the latest release of filebeat, and the results are as follows:

```
% du -hs filebeat
12M     filebeat
% time ./filebeat --help
0.00s user 0.00s system 65% cpu 0.011 total

# After running UPX on filebeat:
% du -hs filebeat
3.5M    filebeat

% time ./filebeat --help  
0.06s user 0.01s system 97% cpu 0.073 total
```

Pretty decent space savings. It has a startup cost that adds roughly 60ms. This startup cost can be mitigated by the operator by having upx decompress it after installation with `upx -d filebeat`.

Thoughts?

**Comment by zstyblik** [comment]
@jobigeorge, it's an interesting idea. However, I have some counter-points:
* upx is probably not as common as tar/bzip/gzip, therefore new dependency is introduced
* `startup cost can be mitigated [...] by having upx decompress it after installation` ~ for me, I can't see the difference between using bzip2/gzip/xz + tar then :\

**Comment by ruflin** [comment]
From a technical point of view I like the idea. But is the size of the beats binaries a concern for some of the users, means is it something that needs optimisation?

**Comment by urso** [comment]
-1

No idea how stable UPX + golang has become recently, but in past there has been quite a number of issues with UPX+golang.

Testing filebeat linux build on master branch:
- go1.6: 16M
- go1.7: 13M

**Comment by jordansissel** [comment]
I think this idea was explored sufficiently at this point, so I'm OK closing this until there's more demand.  :)
