### ISSUE TITLE
Error in GenerateCustomBeats

### ISSUE THREAD

**Issue by Szanik** [elastic/beats#18224]
Hello everyone,

I'm trying to get started to develop my own beat.
I followed the instruction on the homepage.
But the following error is what i get after "executing" "mage GenerateCustomBeat"
inside the github.com/elastic/beats folder:

```
go: downloading github.com/urso/magetools v0.0.0-20200106130147-61080ed7b22b
Error: error while copying required files to vendor: error while looking up cached dir of module: github.com/elastic/beats/v7: expected 1 line, got 0 while looking for github.com/elastic/beats/v7
```

For the GenerateCustomBeat I set the following values after it asked me:
beat type: beat
revision: master

There are some files generated from the "GenerateCustomBeat" command, but sadly i can't use them because the next steps of the Getting Started Guide run into an error aswell. 
I guess because of the error above.

What should I do? is there a fix?
Hope i explained it well enough. 
Thanks for reading.

Specs:
Win10
go version go1.14.2 windows/amd64

**Comment by andresrc** [comment]
Hi @Szanik !

Thank you very much for creating this issue. However, we would kindly like to ask you to post all questions and issues on the [Discuss forum](https://discuss.elastic.co/c/beats) first. In addition to awesome, knowledgeable community contributors, core Beats developers are on the forums every single day to help you out as well. So, your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue with the new information or open a new one.
