### ISSUE TITLE
[Elastic Agent] Prevent a second agent from starting.

### ISSUE THREAD

**Issue by ph** [elastic/beats#18243]
Prevent a second instance of the Agent from running to reduce the problems of collision in the configuration or race in the configuration on disk

**Comment by ph** [comment]
cc @EricDavisX

**Comment by EricDavisX** [comment]
what is the actual desired behavior if / when this is attempted?  Perhaps the behavior should be to un-install the existing agent and then install the new / current agent?  I don't know ramifications.

**Comment by blakerouse** [comment]
@ph I think with #18021 we can easily prevent multiple from running. Being that the GRPC server will be open on a specific port or socket. We can verify that if its already in use then to not start.

**Comment by ph** [comment]
@blakerouse I think we might need mot than that, I was considering adding an _flock_ on the data folder to make sure only one process can read the file in it. This would prever two agents running on different port accessing the same files.

**Comment by blakerouse** [comment]
@ph okay I can work on adding the *flock*

**Comment by ruflin** [comment]
Is a `flock` something that is supported cross platform?

**Comment by blakerouse** [comment]
Seems `github.com/gofrs/flock` supports both unix and windows, so should be. libbeat already uses that module in its `libbeat/cmd/instance/locker.go`.

**Comment by ph** [comment]
@blakerouse sound good.
