### ISSUE TITLE
disk io - use a cumulative counter

### ISSUE THREAD

**Issue by easyrasta** [elastic/beats#1825]
I tried to use disk io metrics, but it seem that it is a cumulative counter. So All metrics seem flat:
![capture d ecran 2016-06-09 a 11 47 45](https://cloud.githubusercontent.com/assets/1186969/15925607/1f9647aa-2e38-11e6-9ca7-b6a69892f13f.png)

**Comment by tsg** [comment]
The plan is to make the derivate at query time (in UI or in Elasticsearch via pipeline aggs). This is currently not possible in Kibana, unfortunately, but it works with Timelion so you could give that one a try. We do plan improvements on the UI so this gets easier.

I'm closing this one for now, feel free to reopen if you want to add more infos.

**Comment by ruflin** [comment]
See also https://discuss.elastic.co/t/metricbeat-cant-graph-network-i-o/52387
