### ISSUE TITLE
Decompress S3 files without ".gz" extension

### ISSUE THREAD

**Issue by fdartayre** [elastic/beats#18283]
**Describe a specific use case for the enhancement or feature:**
Some files automatically generated by AWS are gzip compressed but named without a `.gz` extension. 

**Describe the enhancement:**
Support for gzipped files in S3 input has been introduced in 7.5.0 (https://github.com/elastic/beats/pull/13980) but as it relies on the `.gz` extension of the files, the S3 input doesn't decompress the files with a `.gz` extension. The request is to be able to decompress independently of the naming.

**Comment by exekias** [comment]
I think this makes sense, we could do something like this:

Allow to configure a list of regexps to determine if decompression must be done, the default would be just `\.gz$`

**Comment by kaiyan-sheng** [comment]
Thank you @fdartayre for creating this issue!
