### ISSUE TITLE
[Metricbeat] Enhanced Oracle Module

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#18295]
Today the Oracle module collects some performance and tablespace related metrics. There are more sources that should be also be covered to ensure that the module is production ready.
Querying [V$SYSMETRIC](https://docs.oracle.com/en/database/oracle/oracle-database/18/refrn/V-SYSMETRIC.html#GUID-623748C3-F765-4149-8378-F5CDAD59909A) gives [a lengthy list of system level metrics](https://www.oradev.com/oracle_dba_metrics.html). With one parameterized function selecting from the correct table we can collect 160+ accurate metrics as used by Oracle DBAs, e.g:
`SELECT VALUE FROM V$SYSMETRIC WHERE METRIC_NAME = <metric-name> AND group_id = 2`
Note that these are aggregated stats for all physical and container databases for this instance (connection string). Recommended period is 60s only as that is the rate of internal metric collection/aggregation.

Add the ability to collect system level metrics to the Oracle module.

In addition the aforementioned common metrics look at the possibility of adding support for a number of additional specific metrics: 
- Blocking Sessions 
- Long Running Sessions
- Physical Standby Gaps
- Temp space used
- SGA Allocation
- PGA Allocation
- Number of current logins
- Number of logins by users
- Number of blocked logins

**Comment by mtojek** [comment]
I need to collect some help resources to cover all your points.

Physical Standby Gaps

https://rajeevjhaoracle.wordpress.com/2014/06/25/how-to-check-whether-physical-standby-is-in-sync-with-the-primary-or-not-and-resolved-gap/

(I will follow up with edits)

**Comment by sorantis** [comment]
If that's documented and not enabled by default, I don't see why not

**Comment by andresrc** [comment]
Closing as superseded by https://github.com/elastic/beats/issues/30810
