### ISSUE TITLE
Elastic Agent: docker image doesn't report host information

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#18319]
I've pulled the Elastic Agent image to the testing cluster (https://github.com/elastic/integrations/pull/10/files) and I noticed that the agent doesn't report information about host.

![screencapture-localhost-5601-app-ingestManager-2020-05-06-16_55_56](https://user-images.githubusercontent.com/14044910/81193107-448d7900-8fbb-11ea-860c-c430f9cdc63f.png)

BTW I'm not able to enroll 20 instances at once. It seems to fail for some reason (some connection pool exhaustion?). Maybe it's also worth looking into it.

**Comment by mtojek** [comment]
I think it was caused by using an old image (the last one in the observabilit-ci namespace). Once switched to "beats", it looks good:

![screencapture-localhost-5601-app-ingestManager-2020-05-07-12_36_54](https://user-images.githubusercontent.com/14044910/81285260-8cfe7280-905f-11ea-8b5c-76cd3e1fb01c.png)

On the other hand, I wasn't able to enrolled 20 agent instances at once (14 passed). It probably needs some more verification.

**Comment by ph** [comment]
I will close this one.

>  On the other hand, I wasn't able to enrolled 20 agent instances at once (14 passed). It probably needs some more verification.

Is this is still a problem? I remember you had a docker-composer file. I would like to test it locally.
