### ISSUE TITLE
Migration aliases for 8.0

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#18329]
For the transition from 6.x to 7.0 Beats added a configuration option to add alias fields to index templates pointing from the old field to the new field. Those need to be removed.

https://github.com/elastic/beats/blob/95626b8f1690344312c0831ab2bdcbccffe4d089/libbeat/idxmgmt/idxmgmt.go#L114

**Changes**
- [ ] Remove migration aliases from fields.yml files.
- [ ] Change migration.6_to_7 to migration.7_to_8
- [ ] Delete dev-tools/ecs-migration.yml.

For 8.0 we will track migrations inside of `dev-tools/ecs-migration-8x.yml`. The file will have the same format as the previous `dev-tools/ecs-migration.yml`. It's moved into the `script` directory to be colocated with the two scripts that used the file.

New migration aliases for 8.0 can then begin to be added to the fields.yml files as they were in the past.

**Comment by dedemorton** [comment]
Reopening because this autoclosed. Looks like `migration.6_to_7` still exists in the configuration file and needs to be removed.

I'm not sure which other parts of this work has been done or not done.
