### ISSUE TITLE
Elastic Agent: agent inspect gives "unknown error"

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#18344]
After successful enrollment to the fleet (status "online" in Kibana), I tried the following command:

```
[root@cab420969cda elastic-agent]# ./elastic-agent inspect
no fleet config retrieved yet: /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/introspect_config_cmd.go[56]: unknown error
```

**Comment by mtojek** [comment]
I came to this issue, because I don't see any filebeat or metricbeat running:

```
[root@379cfb2dc534 elastic-agent]# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.2 567840 17308 ?        Ssl  11:03   0:00 elastic-agent run
root       172  0.0  0.0  11836  3032 pts/0    Ss   11:06   0:00 /bin/bash
root       208  0.0  0.0  51764  3500 pts/0    R+   11:19   0:00 ps aux
```

The image is unusable at the moment.

**Comment by michalpristas** [comment]
looks correct, you enrolled and fleet havent sent a configuration just yet, 
it says in the beginning `no fleet config retrieved yet` so there's nothing to inspect.
i can improve error message so it does not contain all the things coming out thanks to our custom error types but i think behavior is correct

**Comment by michalpristas** [comment]
this is happening for me when i run 
```
export PLATFORMS='+all linux/amd64'
mage package
```

from `x-pack/elastic-agent` directory

error:
`The command '/bin/sh -c yum -y --setopt=tsflags=nodocs update &&     yum install -y epel-release jq     yum clean all' returned a non-zero code: 1`

**Comment by mtojek** [comment]
Thank you for taking look into this. If this is a correct behavior, then agree - the output should be improved.

`/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/application/introspect_config_cmd.go[56]: unknown error` - it's not an error in this situation.
