### ISSUE TITLE
Elastic Agent: Kibana URL and Elasticseach URL not picked up

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#18343]
I setup Kibana using config properties:

```
xpack.ingestManager.fleet.kibana.host: "http://kibana:5601"
xpack.ingestManager.fleet.elasticsearch.host: "http://elasticsearch:9200"
```

It got reflected in the Kibana UI:

<img width="628" alt="Zrzut ekranu 2020-05-7 o 12 19 49" src="https://user-images.githubusercontent.com/14044910/81283531-1791a280-905d-11ea-8cfe-ef02ed37f48b.png">

Unfortunately the agent didn't pick it up:

```
[root@cab420969cda elastic-agent]# pwd
/usr/share/elastic-agent
[root@cab420969cda elastic-agent]# grep 9200 elastic-agent.yml
[root@cab420969cda elastic-agent]#
```

Build hash:
```
[root@cab420969cda elastic-agent]# cat .build_hash.txt
1d67ba46e5a964be56ccd28b2c3ea60585c1febf
```

**Comment by nchaulet** [comment]
@ph should we send Kibana url in the agent config?

**Comment by ph** [comment]
@nchaulet  we could indeed add it to the configuration that the Agent receive this would complement what we already send to the Endpoint. See https://github.com/elastic/beats/pull/19448 for a configuration example.

@michalpristas @blakerouse @nchaulet @ruflin  We should probably use an array of hosts for kibana. I would assume that some day we could return a list of kibana url to connect to similar to elasticsearch's sniffing feature. 

Also having multiple URL would help here in the case that you don't have a proxy in front kibana, we could load balance request to multiples hosts.

**Comment by ruflin** [comment]
++ on array.

**Comment by ph** [comment]
@nchaulet is this still an issue?

**Comment by nchaulet** [comment]
Yes it's still not in the configuration

**Comment by ph** [comment]
still an issue :(

**Comment by michalpristas** [comment]
closing, changing ES output is reflected in agent. 
kibana host is not used anymore
