### ISSUE TITLE
[Winlogbeat] More ECS changes for Sysmon

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#18364]
There are few addition improvements we can make the Winlogbeat Sysmon module to better align we ECS.

- Set related.hash.
- Set file.extension/name/directory. Use the JS [`path` module ](https://github.com/elastic/beats/blob/master/libbeat/processors/script/javascript/module/path/path.go#L29-L54).
- `hash.*` is not part of ECS. It should be used as `file.hash.*` or `process.hash.*`. We can't delete the existing `hash.*` fields until 8.0, so for 7.x we can populate them both. And then do a breaking change for 8.0 where we drop `hash.*` completely.
- Drop the `rule.name` field when it has a tack `-` value

**Comment by marc-gr** [comment]
Do you think it might also be needed for `related.ip`, `related.user` and `process.parent.hash`?

**Comment by andrewkroh** [comment]
Yes to all. Good catch.
