### ISSUE TITLE
Topbeat and your Dashboard don't marry

### ISSUE THREAD

**Issue by marcinkubica** [elastic/beats#1836]
Hi

I've installed current topbeat, and imported Dashboards,  submitting to ES 2.3.3, and KB 4.5.1

All according to instructions in docs.

I'm sending from one node however:

1. dashboard seem to see four nodes, not one. (my fqdn hostname has three dashes and one dot)
2. above is replicated across few of visualisations
3. Top processes show 'java' and something called 0, 0h, 1 ,1h and so on.
4. Disk utilisation seem to show /var/lib/elasticsearch as three different mountpoints (?)

Thanks

![image](https://cloud.githubusercontent.com/assets/1593987/15993194/f9e91dd4-30d5-11e6-8c2f-df088986c9db.png)

**Comment by tsg** [comment]
Hi @marcinkubica, this all looks like you didn't load the Elasticsearch template. Please make sure you followed this [step](https://www.elastic.co/guide/en/beats/topbeat/current/topbeat-template.html).

**Comment by marcinkubica** [comment]
@tsg thanks. It probably would be nice to have a basic working experience OOTB rather than explanations which can be missed when deploying fundamentals. thanks ;)

**Comment by tsg** [comment]
Yeah, agreed, and the template loading will be done automatically in the next major version.
