### ISSUE TITLE
[Metricbeat] Add Citus integration to Postgres module

### ISSUE THREAD

**Issue by sayden** [elastic/beats#18375]
In the same way that we have Galera integration in the MySQL module, I think we should also add the most common extension to provide clustering to PostgreSQL: Citus https://www.citusdata.com/

**Comment by andresrc** [comment]
Also to discuss whether if it should be a metricset or a different module

/cc @sorantis

**Comment by andresrc** [comment]
We would do it as a new metricset, not as new integration.

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
