### ISSUE TITLE
[Packetbeat] Official Kubernetes deployment

### ISSUE THREAD

**Issue by maver1ck** [elastic/beats#18377]
**Describe the enhancement:**

For Filebeat, Metricbeat and Auditbeat we have official yaml files for K8s deployment.
https://github.com/elastic/beats/tree/master/deploy/kubernetes

Can we add one for Packetbeat ?

Probably this could be based on this example:
https://github.com/elastic/examples/blob/master/MonitoringKubernetes/packetbeat-kubernetes.yaml

**Describe a specific use case for the enhancement or feature:**

Deploying Packetbeat on Kubernetes clusters.

**Comment by maver1ck** [comment]
If there is a need I can provide PR.

**Comment by ChrsMark** [comment]
@maver1ck , PRs are always welcome so feel free!

**Comment by ironknight78** [comment]
Hi there! Is anybody working on this issue currently? I'd like to investigate this further

**Comment by ChrsMark** [comment]
@ironknight78 I don't think there is anything in progress regarding this, so if @maver1ck has no strong objection you can take this, thanks!

**Comment by ironknight78** [comment]
Oh yeah! what you think @maver1ck  ? I'd be happy to help you there.

**Comment by maver1ck** [comment]
No problem from my side.

**Comment by ironknight78** [comment]
Nice! thanks a lot, @ChrsMark I'm up for it! Can you assign it? 

Thanks !!

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
