### ISSUE TITLE
Error when combining multiple processors in Apache module

### ISSUE THREAD

**Issue by arielromeo** [elastic/beats#18397]
Hi!, 
I'm getting an odd Error when the following configuration is made for apache.yml module. 
It reports that: **"...each processor must have exactly one action, but found 2 actions (add_locale,add_fields)"** As you can see in my config, there is none add_locale processor there. 

The step to reproduce is configure apache.yml like the example below, start the filebeat service and you will see the error reported below. 
```
- module: apache
  access:
    enabled: true
    var.paths: ["/var/log/apache2/access.log*"]
    input:
      processors:
        - add_fields:
            target: '' 
            fields:
              project: "SOME_VALUE"
  error:
    enabled: true
    var.paths: ["/var/log/apache2/error.log*" ]
    input:
      processors:
        - add_fields:
            target: '' 
            fields:
              project: "SOME_VALUE"
```

The error that I got is:
``` 
May  8 21:14:28 server1 filebeat[9458]: 2020-05-08T21:14:28.242Z#011ERROR#011instance/beat.go:933#011Exiting: each processor must have exactly one action, but found 2 actions (add_locale,add_fields)
May  8 21:14:28 server1 filebeat[9458]: Exiting: each processor must have exactly one action, but found 2 actions (add_locale,add_fields)
May  8 21:14:28 server1 systemd[1]: filebeat.service: Main process exited, code=exited, status=1/FAILURE
``` 
The OS configuration is:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

filebeat version 7.6.2 (amd64), libbeat 7.6.2 [d57bcf8684602e15000d65b75afcd110e2b12b59 built 2020-03-26 05:23:38 +0000 UTC]
```

**Comment by arielromeo** [comment]
@andresrc could you please explain me why did you close this? Is related a misconfiguration on my side?

**Comment by andresrc** [comment]
My apologies @arielromeo , I it seems the comment did not appear and I missed the ping.

I was going to ask you to post the issue on the [Discuss forum](https://discuss.elastic.co/c/beats) first. In addition to awesome, knowledgeable community contributors, core Beats developers are on the forums every single day to help you out as well. So, your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue with the new information or open a new one.

Sorry for the misunderstanding
