### ISSUE TITLE
New protocol support: LDAP

### ISSUE THREAD

**Issue by tbragin** [elastic/beats#184]
Metrics of interest:
- operation type (bind, delete, add, etc.)
- bind_dn
- dn
- all name-value pairs as an array

**Comment by cameronkerrnz** [comment]
I would love to take my custom reporting on LDAP performance and replace it with a suitable beat and Kibana.

What my current reporting does is as follows:

* a histogram of response-time (100msec buckets truncating at 8000 ms)
* for each bind_dn that was observed:
 ** grouping by 'generalised' filter, result code, nentries range, count, min,avg,max response time:

Easier to see a screenshot. This also helps to explain what I mean by 'generalised' filter: trying to abstract out the variation to get back to a pattern, so you can say things like (wow, this ldap server really has issues with boolean queries, or "that query is likely to be _that_ particular application).

![image](https://cloud.githubusercontent.com/assets/938702/12832043/a0d6cff4-cbfc-11e5-87b7-bc5c70b60948.png)

This report is quite useful, but really would benefit from being something I can drill down and pivot on in Kibana.

**Comment by inqueue** [comment]
nice, thanks @cameronkerrnz!

What loglevel do you run? You might give Filebeat a try on your logs.

**Comment by cameronkerrnz** [comment]
The log level is higher than I would prefer, although these are access logs, not diagnostic logs (the logs are a stream of shortish XML documents). My current processing incorporates a lot of sqlite to join up the various log events and build the report. Thus, filebeat (at least by itself) would be inappropriate because there is still a lot of joining up to do... which means carrying around a certain amount of state while operations are in-flight. One of the things I like least about the input I have available is that it doesn't list what attributes were requested. Also, the clients source IP is invisible to me as the SSL connection gets terminated elsewhere and so everything seems to come from the same IP.

**Comment by cameronkerrnz** [comment]
Because LDAP can be high-volume, it would be useful to be able to only emit logs for certain conditions, including response time metrics (which implies still having to carry around state for everything).

**Comment by inqueue** [comment]
slapd log level 256 comes to mind, but that is a lot of data for a busy LDAP. I wonder if you could aggregate on the `conn`, process and `op` fields:

```
Feb  5 03:20:22 zmb1 slapd[1558]: conn=345881 op=1 BIND dn="uid=user,cn=admins,cn=top" method=128
Feb  5 03:20:22 zmb1 slapd[1558]: conn=345881 op=1 BIND dn="uid=user,cn=admins,cn=top" mech=SIMPLE ssf=0
Feb  5 09:34:31 zmb1 slapd[1558]: conn=1031 op=318276 SRCH base="" scope=0 deref=0 filter="(objectClass=*)"
Feb  5 09:34:31 zmb1 slapd[1558]: conn=1031 op=318276 SRCH attr=1.1
Feb  5 09:34:31 zmb1 slapd[1558]: conn=1031 op=318276 SEARCH RESULT tag=101 err=0 nentries=1 text=
Feb  5 09:34:31 zmb1 slapd[1558]: conn=1032 op=318668 SRCH base="" scope=0 deref=0 filter="(objectClass=*)"
Feb  5 09:34:31 zmb1 slapd[1558]: conn=1032 op=318668 SRCH attr=1.1
Feb  5 09:34:31 zmb1 slapd[1558]: conn=1032 op=318668 SEARCH RESULT tag=101 err=0 nentries=1 text=
```

Today, Logstash would be needed to enrich this data for Elasticsearch. Soon, an ES Ingest node will be able to do this straight from Filebeat. Still, an LDAP beat is the better and right answer.

**Comment by McStork** [comment]
@inqueue A future feature of Packetbeat will be flows support #670. From what I understand it collects data on layers below application layer (for now?).
Maybe the application layer will be taken in consideration by this feature in a future phase? Data about ```conn``` could then be aggregated.

**Comment by cameronkerrnz** [comment]
My LDAP server is far from OpenLDAP.

**Comment by inqueue** [comment]
> My LDAP server is far from OpenLDAP.

Bad assumption on my part. Hopefully we'll just look forward to the Beat.

**Comment by SHolzhauer** [comment]
This would be a great addition to packetbeat: +1

**Comment by inqueue** [comment]
_keepalive_

**Comment by daikerSec** [comment]
keepalive

**Comment by Blyth0He** [comment]
i have a problem parsing Fragmented Ldap SearchResponse, how do you solved this?
