### ISSUE TITLE
Why doesn't filebeat support reloading entire configuration files？

### ISSUE THREAD

**Issue by jiankunking** [elastic/beats#18403]
I see from the documentation that filebeat only supports dynamic loading of input and module configurations:
[https://www.elastic.co/guide/en/beats/filebeat/current/_live_reloading.html](https://www.elastic.co/guide/en/beats/filebeat/current/_live_reloading.html)

Why not support loading entire configuration files dynamically, like logstash:
[https://www.elastic.co/guide/en/logstash/7.6/reloading-config.html](https://www.elastic.co/guide/en/logstash/7.6/reloading-config.html)

**Comment by jiankunking** [comment]
> This issue doesn't have a `Team:<team>` label.

filebeat

**Comment by andresrc** [comment]
Hi @jiankunking ,

We don't expect to provide this feature soon in the current state of the beats, but it should be provided in some form by the new agent that is in the works.

Thanks.
