### ISSUE TITLE
[filebeat] improve cisco ASA module message patterns

### ISSUE THREAD

**Issue by immon** [elastic/beats#18410]
**Describe the enhancement:**

Filebeat's cisco ASA module does not parse messages of the following types:

<details>
  <summary>unhandled messages ids</summary>

```
%ASA-7-609002
%ASA-6-302020
%ASA-6-302021
%ASA-6-302013
%ASA-6-302014
%ASA-4-313004
%ASA-6-305011
%ASA-6-305012
%ASA-6-302015
%ASA-6-302016
%ASA-2-106001
%ASA-4-106023
%ASA-1-106021
%ASA-2-106006
%ASA-6-106015
%ASA-6-302023
%ASA-6-302022
%ASA-7-111009
%ASA-6-106100
%ASA-7-609001 
```

</details>

We would like to extract at least `destination.ip` and `source.ip` fields.

Here are examples of messages not being parsed [cisco_syslog.txt](https://github.com/elastic/beats/files/4609484/cisco_syslog.txt)

**Comment by immon** [comment]
Similar issues https://github.com/elastic/beats/issues/14978 https://github.com/elastic/beats/issues/14034

**Comment by P1llus** [comment]
I am taking a look at this one, will update the issue with a status later on.

**Comment by Gimlie102** [comment]
Any update on this? These message types are frequently used and should definitely be supported.

**Comment by felix-lessoer** [comment]
@P1llus Any updates?

**Comment by P1llus** [comment]
I ended up doing a larger rewrite which tok longer time than anticipated. I see now that I should have rather done this change first. Give me a couple of days and I can post an update @felix-lessoer and @Gimlie102
