### ISSUE TITLE
Beats Developer Guide step for adding new config option is wrong

### ISSUE THREAD

**Issue by PhantomV1989** [elastic/beats#18427]
Step for adding new config option is wrong. 
Official documentation (https://www.elastic.co/guide/en/beats/devguide/current/beater-interface.html) states that new config option is added to _meta/beat.yml
>You also need to add path to _meta/beat.yml:

>countbeat:
  period: 10s
  path: "."

When in fact, the file does not exist. After some trying, it is finally understood that the correct place to update the config options is located at _meta/config/beat.yml.tmpl

Maybe it would be better to reflect this discrepancy in the documentation?

**Comment by andresrc** [comment]
@andrewkroh can you take a look? Seems related to a previous change. Thanks!

**Comment by andrewkroh** [comment]
Yep, that file got moved to `_meta/config/beat.yml.tmpl` and the docs need updated.
