### ISSUE TITLE
[Elastic Agent] Revert logic in place to add the prefer_v2_template

### ISSUE THREAD

**Issue by ph** [elastic/beats#18428]
The Elasticsearch team [will remove the requirement](https://github.com/elastic/elasticsearch/issues/56528) to send the _prefer_v2_templates_ on every bulk request to enforce the use of v2 templates.

Because of this we have to revert in part the code in https://github.com/elastic/beats/pull/18318 that inject the **parameter option** to the elasticsearch output but we should keep the change for the parameters since it does fix a bug in ES output.

**Comment by ph** [comment]
@blakerous can you take a look at this this need to go in with the Elasticsearch PR, I think we can have the PR ready and we can synchronize the merge.

**Comment by BlakeRous** [comment]
What is that

**Comment by ph** [comment]
@blakerous oh typo, I've missed the e. sorry about that, I was faster than the autocomplete. I've meant @blakerouse

**Comment by ph** [comment]
The Elasticsearch PR is up at https://github.com/elastic/elasticsearch/pull/56546
