### ISSUE TITLE
[Elastic Agent] Agent 8.0 can connect to 7.8 Kibana

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#18430]
It is possible to connect a 8.0 agent to a 7.8 Kibana version but this connection should be refused as the two are not compatible with each other. KB version must be >= Elastic Agent version.

**Comment by ph** [comment]
@ruflin where do you expect to see that logic?

 I believe it should be handled in Kibana:
-  Kibana would be free to inspect the user agent and refuse it.
- We could add that logic to the audit log?
- Could be used for out of compliance detection?

**Comment by ruflin** [comment]
I think the check should be in 3 places:

* Kibana: Ensure only compatible (compliant?) agents connect. For example if Kibana is on 8.0 it might not support the second last minor of 7.x anymore. As Kibana must be newer or equal to the Agent, Kibana knows which versions to support.
* Agent: Ensure that Kibana is always newer or equal to its own version.
* Process output: Ensure that Elasticsearch version is newer or equal. This is important in the standalone case but requires changes to Beats and other processes.

Lets start with enforcing it on the Kibana and make sure we have good error messages on why a connection is refused.

**Comment by michalpristas** [comment]
i'm thinking about agent side, agent does not know what it is connecting to at any moment until request is made. on the other hand if we made a check and kibana is older it does not mean that it cannot be newer few seconds later (e.g. weird load balancing) and so i think it's worthless to check it after a request, request was already done.

maybe we could perform special kind of handshake before actually executing a request but i dont really like this idea
i'm on the same page as ph, kibana should handle this

**Comment by ruflin** [comment]
Lets start with Kibana, then the Output and last if needed, the Agent one.

**Comment by EricDavisX** [comment]
we implemented this in Kibana, its been tested with 7.9.0 and attempting to deploy an 8.0 latest version agent and the enroll command refuses with an error message about version incompatibility?  shall we close it out then?

Please re-open if needed for any purpose.
