### ISSUE TITLE
[Metricbeat] Add ADC support for googlecloud module

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#18454]
Google Cloud client libraries use a strategy called [Application Default Credentials (ADC)](https://cloud.google.com/docs/authentication/production) to find your application's credentials. When your code uses a client library, the strategy checks for your credentials in the following order:

1. First, ADC checks to see if the environment variable GOOGLE_APPLICATION_CREDENTIALS is set. If the variable is set, ADC uses the service account file that the variable points to. 
2. If the environment variable isn't set, ADC uses the default service account that Compute Engine, Google Kubernetes Engine, Cloud Run, App Engine, and Cloud Functions provide, for applications that run on those services.
3. If ADC can't use either of the above credentials, an error occurs.

This issue is to track the work of adding ADC support into Metricbeat, similar to what https://github.com/elastic/beats/pull/15668 is done for Filebeat.

Note: also needs to consider if there's enough code between Filebeat/Metricbeat around credentials to move to `x-pack/libbeat/common` directory.

**Comment by lesaux** [comment]
I have a feeling this has never been implemented, or the docs haven't been updated.
