### ISSUE TITLE
Documentation on the minimum required permissions for Winlogbeat 

### ISSUE THREAD

**Issue by mbarretta** [elastic/beats#18482]
**Describe the enhancement:**
Provide documentation that details the minimum set of permissions for Winlogbeat for each module

**Describe a specific use case for the enhancement or feature:**
In secure environments, there are requirements to limit the number of people and processes with Local Administrator access. As such, there is a need to run Winlogbeat (as well as other Beats) as non-admin account (specifically a named service account) that have the minimum permissions necessary. 

For example, are `BUILT IN\Event Log Readers` and `Log on as a service` sufficient for Winlogbeat to run as a service and read the event log?

Currently, the documentation assumes the Beat is run as an Administrator.

**Comment by andrewkroh** [comment]
Duplicate of #15773
