### ISSUE TITLE
Elastic Agent installed on Windows is showing Error state due to 'chown' being used and not supported in File Beat

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#18495]
**Kibana version:**
8.0 nightly snapshot, latest (as of May 13 today)

**Elasticsearch version:**
8.0 nightly snapshot, latest (as of May 13 today)

**Server OS version:**
Debian10

**Browser version:**
Chrome latest on mac

**Original install method (e.g. download page, yum, from source, etc.):**
installed with snapshots to the endpoint/ingest team nightly demo server:
https://kibana.endpoint.elastic.dev/app/ingestManager#/fleet
 - login with Okta

**Describe the bug:**
The Agent seems to be enrolled and started correctly, it shows up in the Fleet UI but shows an error very quickly as such:

Application: filebeat[f5ab391b-b242-472d-bac3-73dcc41b79c0]: operation-start: chown C:\Temp\elastic-agent-8.0.0-SNAPSHOT-windows-x86_64\data\logs\default: not supported by windows

**Steps to reproduce:**
1. using 8.0 snapshots and latest 8.0 agent, deploy to a Windows environment (linux and macos do not show the bug)
2. go to the Fleet page in Ingest Manager in Kibana, and see the 'error' state shown
3. it never changes from error at this point it seems.

**Expected behavior:**
It should not throw the error as the 'chown' executable is not supported on Windows so the Filebeat / Agent code should not attempt to use it.  

**Screenshots (if relevant):**
![Screen Shot 2020-05-13 at 1 37 37 PM](https://user-images.githubusercontent.com/12970373/81847331-72c20a00-9521-11ea-81f6-8690904a997c.png)

**Errors in browser console (if relevant):**
n/a

**Provide logs and/or server output (if relevant):**
n/a

**Any additional context:**
I have a separate concern about the 'state' saying error but the Agent still showing as 'on-line in other views, we may need to review how we present this?

**Comment by EricDavisX** [comment]
this can be reproduced with a windows vm as host, on my local laptop, using virtual box, fyi. 
you can download a (big!) Windows zip file of the 2004DevEval image from:
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

**Comment by michalpristas** [comment]
thanks eric for testing on windows, i will look at it
