### ISSUE TITLE
Possible missing CI target for Metricbeat x-pack windows

### ISSUE THREAD

**Issue by narph** [elastic/beats#18515]
Build triggered by PR containing changes in Metricbeat that affected Metricbeat x-pack as well did not seem to trigger the CI for Metricbeat x-pack in Windows. 
Ex PR shouldn't have had a successful build https://github.com/elastic/beats/pull/18361.

**Comment by jsoriano** [comment]
I think we are missing stages for auditbeat, filebeat and libbeat too, in Windows and OSX, I am trying some things in https://github.com/elastic/beats/pull/18494

**Comment by jsoriano** [comment]
Closing this so discussion is centralized in https://github.com/elastic/beats/issues/17411
