### ISSUE TITLE
Add support for Azure billing metrics in Metricbeat 

### ISSUE THREAD

**Issue by narph** [elastic/beats#18571]
**Describe the enhancement:**
- add `billing` metricset in the Metricbeat `azure` module

**Describe a specific use case for the enhancement or feature:**
- make use of the azure sdk for go:
https://github.com/Azure/azure-sdk-for-go/tree/master/services/consumption
https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/billing/
- Billing APIs and Consumption APIs, for reference here https://docs.microsoft.com/en-us/rest/api/billing/, https://docs.microsoft.com/en-us/rest/api/consumption/#rest-operation-groups

**Comment by richcollier** [comment]
+1 - I have a customer who is asking for this
