### ISSUE TITLE
Old python version on beats-ci nosetests

### ISSUE THREAD

**Issue by P1llus** [elastic/beats#18614]
**Describe the enhancement:**

Noticed that the python version was quite old on beats-ci. It seems to currently be 3.5 (at least on this instance). @andrewkroh mentioned to create an issue to track it.

Link to the failing instance: https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats-beats-mbp/detail/PR-18298/20/pipeline/382#step-879-log-1

3.5 is soon EOL, so might be good to get it higher. It also creates failures if we use newer python built-in functions that relies on newer versions.

**Comment by kuisathaverat** [comment]
We fixed the workers to Ubuntu 18.04 the version of Python used now is 3.6.9 final: 2019-07-02.
