### ISSUE TITLE
Fortinet 7.8 - network.bytes 

### ISSUE THREAD

**Issue by RamiusKahn** [elastic/beats#18620]
Hello @P1llus , 

We are testing the 7.8 version of the Fortinet module and are receiving the following error message:

> failed to parse field [network.bytes] of type [long] in document with id 'B0PFJ3IBZHCtNXd-pzP9'. Preview of field's value: '490003500110019619332',

Typical entries for our data set are:
sentbyte=568 rcvdbyte=2152 sentpkt=7
sentbyte=0 rcvdbyte=0 sentpkt=0
sentbyte=112 rcvdbyte=60 sentpkt=2 rcvdpkt=1

and the output of some fields are as follows:

> May 18, 2020 @ 11:20:10.762 | **24.1PB**
> May 18, 2020 @ 11:20:10.762 | 0B
> May 18, 2020 @ 11:20:10.762 | 21.9MB
> May 18, 2020 @ 11:20:10.762 | 0B
> May 18, 2020 @ 11:20:10.762 | 70.5KB
> May 18, 2020 @ 11:20:10.762 | 9.2MB
> May 18, 2020 @ 11:20:10.762 | 62.6KB
> May 18, 2020 @ 11:20:10.762 | 62.6KB
> May 18, 2020 @ 11:20:10.762 | **18.8GB**
> May 18, 2020 @ 11:20:10.762 | 8.8MB
> May 18, 2020 @ 11:20:10.855 | 37.6MB
> May 18, 2020 @ 11:20:10.855 | 25.3MB
> May 18, 2020 @ 11:20:10.855 | 0B
> May 18, 2020 @ 11:20:10.855 | 0B
> May 18, 2020 @ 11:20:10.855 | 101.6MB

Thank you for writing this module. Let me know if you need anything else in the way of information to troubleshoot.

**Comment by kaiyan-sheng** [comment]
Hello, thanks for creating this issue. But we would kindly ask you to post all questions and issues on https://discuss.elastic.co/c/beats before opening a Github Issue. Your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue or open a new one with more details. Thanks in advance!

If you could attach the log entries which cause the error message in the discuss forum issue, that would be very helpful for us to reproduce. Thanks!

**Comment by A-Hall** [comment]
@kaiyan-sheng FYI, this issue appears to be replicated by another user who has opened a discuss on it here:
https://discuss.elastic.co/t/filebeat-module-fortinet-7-8/233803

**Comment by A-Hall** [comment]
https://github.com/elastic/beats/issues/18707
