### ISSUE TITLE
Does Metricbeat or Topbeat support send alert feature?

### ISSUE THREAD

**Issue by aqiao** [elastic/beats#1862]
First of all, very appreciate for the great effort of Beat team, i'm a big fans of all the beat products.
A question is if the topbeat or metricbeat support sending alert via email

**Comment by ruflin** [comment]
I think what you are looking for is Watcher: https://www.elastic.co/guide/en/watcher/current/introduction.html

In the future for questions, please use Discuss: https://discuss.elastic.co/

**Comment by aqiao** [comment]
ok! thanks ruflin
