### ISSUE TITLE
Unknown capability to add: "CAP_AUDIT_READ"

### ISSUE THREAD

**Issue by rajputvishwas** [elastic/beats#18631]
Please include configurations and logs if available.
I am setting up auditbeat on k8s cluster using link given at https://www.elastic.co/guide/en/beats/auditbeat/master/running-on-kubernetes.html

but it throws error: 
 kubelet, blrpaas005.ad.infosys.com  Error: failed to start container "auditbeat": Error response from daemon: linux spec capabilities: Unknown capability to add: "CAP_AUDIT_READ"

For confirmed bugs, please report:
- Version: 7.5.2
- Operating System: Linux
- Discuss Forum URL:

- Steps to Reproduce: 
curl -L -O https://raw.githubusercontent.com/elastic/beats/master/deploy/kubernetes/auditbeat-kubernetes.yaml

kubectl create -f auditbeat-kubernetes.yaml

**Comment by andrewkroh** [comment]
`CAP_AUDIT_READ` may not present in some older OS versions, but as long as you've given it `CAP_AUDIT_CONTROL` it should work.

`CAP_AUDIT_READ` capability allows auditbeat to work in multicast mode where it only read the logs and does not manage any rules.
