### ISSUE TITLE
Hidden indices not exposed in monitoring index_stats documents

### ISSUE THREAD

**Issue by chrisronline** [elastic/beats#18639]
With the [introduction of hidden indices](https://github.com/elastic/elasticsearch/pull/50452), it looks like they are not included in the monitoring `index_stats` documents collected by Metricbeat. It looks we need to add `expand_wildcards=hidden` to [this api call](https://github.com/elastic/beats/blob/master/metricbeat/module/elasticsearch/index/index.go#L42).

We should also add an additional field for hidden indices that indicates they are hidden, so the UI can filter it. I'm suggesting this to be `index_stats.hidden: <boolean>`. The challenge here is the API doesn't return this state, but it's rather available in `/*/_settings` so I'm not sure the right solution moving forward. Happy to discuss

Related to https://github.com/elastic/elasticsearch/issues/56949

**Comment by ycombinator** [comment]
@chrisronline Thanks for bringing this up. For starters I've inquired with the ES team if it makes sense to make `GET stats` behave as before, given the intent of hidden indices was more about hiding their _data_ from user's by default, not so much their metadata like stats IIUC. I've started that conversation here: https://github.com/elastic/elasticsearch/pull/50452#issuecomment-632623778.

**Comment by ycombinator** [comment]
I'm relabeling this issue as an enhancement because the hidden indices feature in Elasticsearch itself was an enhancement. We now need to enhance the Metricbeat elasticsearch module correspondingly.

**Comment by ycombinator** [comment]
@chrisronline I'm planning to resolve this issue via two PRs: 
- [ ] one for collecting stats for all indices, including hidden ones: #18703. This PR may not be necessary depending on the outcome of this discussion: https://github.com/elastic/elasticsearch/pull/50452#issuecomment-632623778.
- [ ] one for marking hidden indices with `index_stats.hidden: <boolean>`.
