### ISSUE TITLE
[All Beats] `Keystore add` hangs under Windows

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#18649]
Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 7.7.0...master
- Operating System: Windows
- Discuss Forum URL: n/a
- Steps to Reproduce: 

  - Download 7.7.0 Beat of your choice (.zip)
  - Unpack
  - Run `beatname keystore add ES_PWD`
  - Answer `y` to create a keystore
  - In the password prompt, write something and press enter.
  - Nothing happens

The Beat seems stuck at some point. It can be killed by CTRL+C.

![image](https://user-images.githubusercontent.com/15056957/82420312-dc8d6700-9a7f-11ea-934b-cc0a4394336a.png)

Reproduced in CMD.exe / Powershell and Windows 2012 - 2019

Works fine in 7.6.2

**Comment by adriansr** [comment]
Seems caused by https://github.com/golang/go/issues/36609

**Comment by adriansr** [comment]
A workaround is to use the `-stdin` flag

**Comment by janniten** [comment]
Using old and keystore (from version 7.6.2) and copying into the 7.7 installation also works :)

**Comment by hueyg** [comment]
I just encountered this today.  While the stdin option allows you to get past the locked prompt it does not seem to have entered the correct value for the variable I was storing.  Not sure of a way to verify, but I am stuck unless I hard code a password now.

**Comment by adriansr** [comment]
Hi @hueyg ,

This is fixed in version 7.7.1.

If for whatever reason you don't want to upgrade, you can use 7.7.1 to create the keystore and then use the keystore file on an older version. But afaik this problem only affected 7.7.0 so I don't see an issue with upgrading.
