### ISSUE TITLE
add node.attr.data to Metricbeat Elasticsearch module

### ISSUE THREAD

**Issue by jasonslater2000** [elastic/beats#18646]
Customer cannot visualize or alert on disk space available on their cluster based on data temperature (hot warm cold) which is stored in each node's node.attr.data field, but not part of the Elasticsearch module's metric set.  Can we please add this?

**Comment by ycombinator** [comment]
Heya @jasonslater2000, the `elasticsearch` Metricbeat module can operate in one of two modes: default (when the `xpack.enabled` setting in the module is omitted to set to `false`) and stack-monitoring (when the `xpack.enabled` setting in the module is set to `true`). In the default mode, the module indexes data into the usual `metricbeat-*` indices. In the `stack-monitoring` mode, the module indexes data into `.monitoring-es-*` indices which are used to drive the Stack Monitoring UI in Kibana. 

Do you know which of these indices the customer is trying to build their visualizations/alerts on top of? That will determine the code paths that need to be changes to implement this enhancement.

**Comment by jasonslater2000** [comment]
The origin of this request was that the customer wanted a simple way of
alerting and/or visualizing their ESS cluster usage by hot & warm
temperatures, e.g. hot is 80% full and warm is 70% full.  They have a
separate monitoring cluster set up.  So my assumption is that this would be
w/ .monitoring-es-* indices.
