### ISSUE TITLE
Issue with Metricbeat "Database selector [Metricbeat MSSQL] ECS" Visualization

### ISSUE THREAD

**Issue by MakoWish** [elastic/beats#18659]
**Kibana version**: 7.3.0

**Elasticsearch version**: 7.3.0

**Server OS version**: Ubuntu 19.04 disco

**Browser version**: Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Browser OS version**: Microsoft Windows 10 Enterprise Version 1903

**Original install method (e.g. download page, yum, from source, etc.)**: Debian Package

**Description of the problem including expected versus actual behavior**: The "Database selector [Metricbeat MSSQL] ECS" visualization included with Metricbeat dashboards does not recognize the field "mssql.database.name". I can confirm in both Discover and the metricbeat-* index pattern that the field does exist, and there are tons of records with data in the field. 

**Steps to reproduce**:
 1. Install dashboards using "metricbeat.exe setup"
 2. View "Database selector [Metricbeat MSSQL] ECS" visualization
 3. Attempt to click on the selector

**Errors in browser console (if relevant)**: "Filtering occurs on the "mssql.database.name" field, which doesn't exist on any documents in the "metricbeat-*" index pattern. Choose a different field or index documents that contain values for this field."

**Provide logs and/or server output (if relevant)**:

**Comment by MakoWish** [comment]
Any update on this? Issue has been open for nearly a year and is still present on 7.8.0.

**Comment by sayden** [comment]
Can you open an ER in Beats GH? That's the reason why we haven't come up to fix this yet. Thanks!

**Comment by MakoWish** [comment]
I don't believe this is a Beats issue. This is a Kibana visualization issue.

**Comment by fabinho1314** [comment]
Any news regarding this matter? 

I also cannot select any DB in the Database selector [Metricbeat MSSQL] ECS  mssql.database.name

**Comment by insu0929** [comment]
Using both Kibana, MetricBeat version 7.12, with MSSQL Server on Windows system.
Facing the same issue here... Any updates??
