### ISSUE TITLE
Show Beats in the Stack Monitoring UI regardless of zero doc count in an index

### ISSUE THREAD

**Issue by eddieturizo** [elastic/beats#18669]
**Describe the enhancement:**

It would be useful to be able to have a Beat displayed in the Stack Monitoring app even if a Beat (e.g. Filebeat) has yet to collect and ship data to Elasticsearch. With 7.7.0, you need to have a Beat index data before it shows up in the Stack Monitoring app. 

**Describe a specific use case for the enhancement or feature:**

As part of deploying Filebeat, I started off with configuring [monitoring](https://www.elastic.co/guide/en/beats/filebeat/current/monitoring-metricbeat-collection.html#configure-metricbeat) using Metricbeat to collect and ship the Beats monitoring metrics to Elasticsearch. I specifically disabled log collection in `filebeat.yml` because I wanted to ensure I could monitor Beats before shipping any metrics to a monitoring cluster. Beats did not show up in the Stack Monitoring app until I enabled log file collection.

**Comment by ycombinator** [comment]
Just to add more light here: the current behavior is a result of fetching the Elasticsearch cluster UUID in a callback that's called only when the Beat connects to the Elasticsearch output cluster (if `output.elasticsearch.enabled: true`). And the latter happens lazily, only when the Beat has an event to send to Elasticsearch. 

We would need to "detach" the cluster UUID fetching functionality from the mechanism that connects to the Elasticsearch output cluster. Instead, we would need to eagerly fetch the cluster UUID from the Elasticsearch output cluster.
