### ISSUE TITLE
Make python integration tests honor `MODULE` env var

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#18678]
Currently, in Metricbeat, it is possible to run golang integration tests for a specific module by setting the `MODULE` environment variable. However, the same is not true for python integration tests (aka system tests). Let's make the python integration tests also honor the `MODULE` environment variable.

**Comment by kvch** [comment]
AFAIK, if one sets `TESTING_FILEBEAT_MODULES`, he/she can specify which modules to run. Is the goal of the issue to unify the names of environment variables?

**Comment by ycombinator** [comment]
> AFAIK, if one sets TESTING_FILEBEAT_MODULES, he/she can specify which modules to run. Is the goal of the issue to unify the names of environment variables?

Yes, for Filebeat system tests, we should replace `TESTING_FILEBEAT_MODULES` with `MODULE` or at least use `MODULE` to populate `TESTING_FILEBEAT_MODULES`.

Also, for Metricbeat system tests I don't believe there is any way to restrict the modules for which to run them. Probably because these are more self-contained within each module folder so it's easy to manually run the system tests for just one module. We just need to make it easy to do the same thing for CI as well, by honoring the `MODULE` environment variable.
