### ISSUE TITLE
Filebeat configuration file validation

### ISSUE THREAD

**Issue by tpolekhin** [elastic/beats#1869]
Hello, i send 2 days trying to identify issue with filebeat-5.0.0alpha3 not writing to Kafka.
I tried to use debug logging but its just a mess, and showed nothing(

Finally, the issue was in config file output.kafka
i used `topic_id` as in logstash config, instead of just `topic`

Having a validation for config file would help a lot in this not obvious issues

Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For confirmed bugs, please report:
- Version: 
- Operating System: 
- Steps to Reproduce:

**Comment by ruflin** [comment]
We are working on improving the configuration validation. @urso created the project ucfg which greatly helps here as the default yaml golang libs are not enough here: https://github.com/urso/ucfg

Our current focus is on validating that the existing files have the correct format. A second step is also to detect fields that were configured but should not be there.

**Comment by ruflin** [comment]
We heavily improve the validation of the config file. We still can't tell if there are too many fields which we don't use, but we very most of the fields that exist with `go-ucfg`. Closing this issue as this is some general that we keep improving.

**Comment by lucabelluccini** [comment]
I am reopening this issue as without configuration validation:
- it can happen users are not able to know if settings are really taken into account (e.g. typo or wrong placement in the yaml structure)
- it can lead to Beats being unhealthy (when under Elastic Agent) and producing cryptic messages not easy to understand

Possible solutions:
- While it would be quite tough to have a global schema validation up-front, we might delegate each component which loads configuration (unmarshalling from yaml) to raise at least a warning in case a setting key is unexpected.
- We might provide at least one API to get the **runtime configuration dumped as JSON**. This would allow us to confirm what are the actual settings being used by Beat. Sensible settings should be redacted.
