### ISSUE TITLE
logging.to_files: false is not honored when override BEAT_LOG_OPTS to Environment="BEAT_LOG_OPTS="

### ISSUE THREAD

**Issue by kunisen** [elastic/beats#18702]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 7.4.2
- Operating System: Linux
- Discuss Forum URL: N/A
- Steps to Reproduce: 

### manual

https://www.elastic.co/guide/en/beats/filebeat/7.4/setup-repositories.html

### create repo

- become su

```bash
sudo su -
```

- create repo

```bash
vi /etc/yum.repos.d/elastic.repo

# put this into elastic.repo
[elastic-7.x]
name=Elastic repository for 7.x packages
baseurl=https://artifacts.elastic.co/packages/7.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
```

### Install filebeat

```bash
# latest version
yum install -y filebeat

# specific version (e.g. 7.4.2)
yum install -y filebeat-7.4.2-1.x86_64
```

### Start filebeat

```bash
systemctl daemon-reload
systemctl restart filebeat
```

### Create dir for drop-in unit file

```bash
mkdir /etc/systemd/system/filebeat.service.d
```

### Override to disable syslog output

- Add override

```bash
# run command
systemctl edit filebeat.service

# add the following part
[Service]
Environment="BEAT_LOG_OPTS="
```

- Check override

```bash
ll /etc/systemd/system/filebeat.service.d

# sample response - we should be able to see override.conf
total 4
-rw-r--r--. 1 root root 41 May 22 00:08 override.conf
```

### Restart filebeat to apply the change

```bash
systemctl daemon-reload
systemctl restart filebeat
```

### Check syslog

We could see filebeat stops logging to syslog.

```bash
cat /var/log/messages | grep -i filebeat | tail -3

# response
# - line1 : filebeat process said it stopped
# - line2 : systemd stopped filebeat
# - line3 : systemd started filebeat
# So, we will no longer see filebeat process gives logging message
May 22 00:50:44 kuni-es filebeat: 2020-05-22T00:50:44.844Z#011INFO#011instance/beat.go:432#011filebeat stopped.
May 22 00:50:44 kuni-es systemd: Stopped Filebeat sends log files to Logstash or directly to Elasticsearch..
May 22 00:50:44 kuni-es systemd: Started Filebeat sends log files to Logstash or directly to Elasticsearch..
```

### Check filebeat log

We could see filebeat log output will be honored accordingly as well.

```bash
cat /var/log/filebeat/filebeat | tail

# sample response
2020-05-22T01:48:59.939Z	INFO	[publisher]	pipeline/module.go:97	Beat name: kuni-es
2020-05-22T01:48:59.939Z	INFO	instance/beat.go:422	filebeat start running.
2020-05-22T01:48:59.939Z	INFO	registrar/registrar.go:145	Loading registrar data from /var/lib/filebeat/registry/filebeat/data.json
```

## [BUG] Disable filebeat log output

To disable filebeat log, we could config `filebeat.yml`.

- Add log output setting to `filebeat.yml`

```bash
logging.to_files: false
```

- Restart filebeat

```bash
systemctl daemon-reload
systemctl restart filebeat
```

- Check filebeat log

**Expected result**

We expected there is no log output here as logging to file & syslog are both disabled.

**Actual result**

However, we got log output even we disable file log output.

```bash
cat /var/log/filebeat/filebeat | tail -1

# sample response
2020-05-22T02:03:18.325Z	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": ...
```

**Comment by urso** [comment]
Checking the code, Beats requires at least one valid log output. With the settings demonstrated here no log output is configured at all. In this case Beats falls back to the default log output, which is the file output here. In 7.7 this behavior is changed for systemd, with Filebeat falling back to the stderr logger (the `-environment` CLI flag is taken into account to decide on the default logger type.).

Why do you want run Beats without any logs at all?

**Comment by 111andre111** [comment]
Hi @urso ,

Observed a similar issue with having an output section and tested with most new 7.13.2 and was as well the same for instance for 7.11.2.
Let's assume you would have a filebat.yml like this:
```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/boot.log
- type: filestream
  enabled: false
  paths:
    - /var/log/*.log
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
output.file:
  path: "/tmp"
  filename: filebeat
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
```
OS is CentOS7 as well as tested with RHEL7 and installed filebeat via RPM.

If you now start filebeat using systemctl:
`systemctl start filebeat`
the log will be output to `/var/log/messages`

However ps aux input is like that:
`root      6169  2.3  6.4 1019804 121284 ?      Ssl  12:50   0:05 /usr/share/filebeat/bin/filebeat --environment systemd -c /etc/filebeat/filebeat.yml --path.home /usr/share/filebeat --path.config /etc/filebeat --path.data /var/lib/filebeat --path.logs /var/log/filebeat`
which would make me think the log should be output to `/var/log/filebeat` which makes me think why that might happen.

I even increased the log level to debug, but didn't find a valuable reason why that happens as well.

**Comment by 111andre111** [comment]
Forked last message to https://github.com/elastic/beats/issues/26802

**Comment by urso** [comment]
Closing this issue. Updating Beats should improve the situation, as newer Beats releases take the kind of environment into account when computing the default logging settings.
