### ISSUE TITLE
Add a minimum TTL to auditbeat reverse DNS resolution

### ISSUE THREAD

**Issue by ansell** [elastic/beats#18709]
**Describe the enhancement:**

I am having an issue with auditbeat performing reverse DNS resolution too often. However, it doesn't look like a bug, as the responses seem to have `TTL: 0`, and based on the documentation it appears as though that response value is honoured and the responses are never cached by design:

https://www.elastic.co/guide/en/beats/auditbeat/master/processor-dns.html

**Describe a specific use case for the enhancement or feature:**

It would be very useful for me to be able to configure a minimum TTL for caching successful auditbeat reverse DNS resolutions to allow `TTL: 0` responses to be cached for the minimum configured time rather than never cached.

Reverse DNS requests are generally out-of-system requests, so there is also the potential for DoS if malicious users are aware of the use of auditbeat reverse DNS resolution and this issue.

**Comment by andrewkroh** [comment]
It's probably a pretty simple enhancement to make if anyone is interested in contributing. It would involve adding a new configuration option to the success cache then update the code to set a minimum bound on the cache TTL value. It would need a test case and docs update too.

https://github.com/elastic/beats/blob/bfe773e4d80d0d77d17d6a80c58a07448458d5cd/libbeat/processors/dns/config.go#L84-L88

https://github.com/elastic/beats/blob/bfe773e4d80d0d77d17d6a80c58a07448458d5cd/libbeat/processors/dns/cache.go#L52

**Comment by ansell** [comment]
@andrewkroh I attempted to make the necessary changes, but not sure how to test them so I am not sure if they are actually working. I have previously been using the dns processor with the auditbeat system socket module that doesn't seem to be open sourced. I have signed the CLA, so feel free to take this commit and complete it:

https://github.com/ansell/beats/commit/b736d97be04283e3a1b7176c9de9b7d1c99bc4b2

**Comment by andrewkroh** [comment]
hey @ansell, can you please open a PR with that patch? I can take a look at it and try to push in some unit tests to go with it.

**Comment by ansell** [comment]
@andrewkroh PR is at #18986 . I have enabled "Maintainer push access" to the branch.
