### ISSUE TITLE
Metricbeat kafka output documentation

### ISSUE THREAD

**Issue by suikast42** [elastic/beats#18710]
The [metricbeat docu ](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-kafka-broker.html) covers only the jmx metrics for standalone installation but not a description for a dockerized environment.

The way I have done is the folowing:

1. Create a custom docker image 
`FROM confluentinc/cp-kafka:${stack.modulenversion}
ADD docker/jolokia-jvm-1.6.2-agent.jar /opt/jolokia-jvm-agent.jar
EXPOSE  9092
`
2. Add Enviroment variable to docker compose
`KAFKA_OPTS: -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.local.only=false -javaagent:/opt/jolokia-jvm-agent.jar=port=8775,host=kafka`

that can be helpful in the docu.

**Comment by jsoriano** [comment]
Hey @suikast42,

We have plans to reorganize the documentation of features that use Jolokia (see #18845). I think that documenting how to create custom images with the Jolokia jar included can be actually a good idea.
I have added this and a note about JVM options that could affect jolokia to the issue, lets keep #18845 as a central point to keep track of these improvements.

Thanks for your feedback!
