### ISSUE TITLE
[Metricbeat] Missing documentation in SQL module

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#18743]
The [SQL module documentation](https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-sql.html) doesn't explain well how to work with the module. E.g. there is no indication which SQL drivers are supported, how each driver can be configured, limitations (if any) on what types of queries can be executed, etc.
Update the module documentation with relevant description and examples of configuration for the supported drivers.

Part of https://github.com/elastic/beats/issues/15048

**Comment by sayden** [comment]
Original community PR: https://github.com/elastic/beats/pull/13257

**Comment by jsoriano** [comment]
Added reference to this issue in the meta ticket for this module https://github.com/elastic/beats/issues/15048

**Comment by sorantis** [comment]
keep open
