### ISSUE TITLE
[Elastic Agent] Support multiples host for kibana

### ISSUE THREAD

**Issue by ph** [elastic/beats#18744]
In the current iteration we only support a single Kibana host, it would be nice to support multiple kibana host and load balance our request to them.

Ideas:

- Support multiples host at enroll time.
- Allow to receive kibana hosts as part of the checkin.

**Comment by ph** [comment]
@nchaulet @jen-huang does Kibana has a cluster concept? IE can a kibana aware of other kibana instance available? It would be nice if Kibana could return the list of available Kibana instance.

**Comment by nchaulet** [comment]
I do not think Kibana as a cluster concept, so we would have to allow the user to configure the multiple `hosts` (the user already need to configure one currently so it's not a big change in the user experience)

**Comment by ph** [comment]
> I do not think Kibana as a cluster concept, so we would have to allow the user to configure the multiple hosts (the user already need to configure one currently so it's not a big change in the user experience)

That could be a simple solutions, we could send them as part of the configuration and the agent could update his local list. 

Concerning the enrollment we could, either support comma-separated host and the agent could pick a random one to establish the trust with Kibana.

@nchaulet When I've asked the _cluster mode_ for Kibana  I was thinking about the Background Job feature used by alerting, where a job can be distributed and run on a Kibana instance, I thought that they might have that concept.

cc @blakerouse @michalpristas
