### ISSUE TITLE
[Ingest Manager] Fix start script for windows service

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#18811]
at the moment start script has the same form as for any other beat,
agent is on the other hand started with different set of input arguments and these need to be taken into account

cc @EricDavisX @ph

**Comment by EricDavisX** [comment]
what testing is warranted based on this change, do we need to re-test installing Agent on the 3 major OS types, or do more specific installations on types of Linux, macOS, and all Windows variants?

**Comment by michalpristas** [comment]
@EricDavisX  this affects windows only and only the service installation part
