### ISSUE TITLE
Auditbeat system/socket fails to start due to IPv6 disabled on loopback device

### ISSUE THREAD

**Issue by 111andre111** [elastic/beats#18869]
I did some tests with auditbeat and it seems if IPv6 is disabled for all network interfaces using
```
/etc/sysctl.conf
net.ipv6.conf.all.disable_ipv6 = 1
```
needed to fix that by
```
net.ipv6.conf.lo.disable_ipv6 = 0
```
https://www.elastic.co/guide/en/beats/auditbeat/master/auditbeat-dataset-system-socket.html#_kernel_configuration
```/proc/sys/net/ipv6/conf/lo/disable_ipv6 (IPv6 enabled in loopback device) is required when running with IPv6 enabled.```

My question is why IPv6 even needs to be enabled if IPv6 is disabled for all interfaces?

Error thrown is like this:
```
May 30 10:12:58 ubuntu2004.localdomain auditbeat[4124]: 2020-05-30T10:12:58.781Z        ERROR        instance/beat.go:932        Exiting: 1 error: system/socket dataset setup failed: unable to guess one or more required parameters: guess_struct_creds failed: failed to add kprobe 'r:guess_struct_creds prepare_creds +0({{.RET}}):u64 +8({{.RET}}):u64 +16({{.RET}}):u64 +24({{.RET}}):u64 +32({{.RET}}):u64 +40({{.RET}}):u64 +48({{.RET}}):u64 +56({{.RET}}):u64 +64({{.RET}}):u64 +72({{.RET}}):u64 +80({{.RET}}):u64 +88({{.RET}}):u64 +96({{.RET}}):u64 +104({{.RET}}):u64 +112({{.RET}}):u64 +120({{.RET}}):u64': failed installing probe 'r:auditbeat/guess_struct_creds prepare_creds +0(%ax):u64 +8(%ax):u64 +16(%ax):u64 +24(%ax):u64 +32(%ax):u64 +40(%ax):u64 +48(%ax):u64 +56(%ax):u64 +64(%ax):u64 +72(%ax):u64 +80(%ax):u64 +88(%ax):u64 +96(%ax):u64 +104(%ax):u64 +112(%ax):u64 +120(%ax):u64': write /sys/kernel/tracing/kprobe_events: file exists
May 30 10:12:58 ubuntu2004.localdomain auditbeat[4124]: Exiting: 1 error: system/socket dataset setup failed: unable to guess one or more required parameters: guess_struct_creds failed: failed to add kprobe 'r:guess_struct_creds prepare_creds +0({{.RET}}):u64 +8({{.RET}}):u64 +16({{.RET}}):u64 +24({{.RET}}):u64 +32({{.RET}}):u64 +40({{.RET}}):u64 +48({{.RET}}):u64 +56({{.RET}}):u64 +64({{.RET}}):u64 +72({{.RET}}):u64 +80({{.RET}}):u64 +88({{.RET}}):u64 +96({{.RET}}):u64 +104({{.RET}}):u64 +112({{.RET}}):u64 +120({{.RET}}):u64': failed installing probe 'r:auditbeat/guess_struct_creds prepare_creds +0(%ax):u64 +8(%ax):u64 +16(%ax):u64 +24(%ax):u64 +32(%ax):u64 +40(%ax):u64 +48(%ax):u64 +56(%ax):u64 +64(%ax):u64 +72(%ax):u64 +80(%ax):u64 +88(%ax):u64 +96(%ax):u64 +104(%ax):u64 +112(%ax):u64 +120(%ax):u64': write /sys/kernel/tracing/kprobe_events: file exists
May 30 10:12:58 ubuntu2004.localdomain systemd[1]: auditbeat.service: Main process exited, code=exited, status=1/FAILURE
```

Here was already a similar PR to that 
https://github.com/elastic/beats/pull/13966

I had a look to where this may happen:
https://github.com/elastic/beats/blob/v7.7.0/x-pack/auditbeat/module/system/socket/guess/creds.go#L69

I am asking me if this can be something to this here?
https://go101.org/article/channel-closing.html

Tested with Ubuntu 20.04 and Auditbeat 7.7.0, but I think it is the same for Ubuntu 18.xx.
(Still open to be tested)

**Comment by adriansr** [comment]
Found no issues with current master and `net.ipv6.conf.all.disable_ipv6 = 1`.

The attached error snippet points to something other than IPv6 issues:

> Exiting: 1 error: system/socket dataset setup failed: unable to guess one or more required parameters: guess_struct_creds failed: failed to add kprobe '[...]': failed installing probe '[...]': write /sys/kernel/tracing/kprobe_events: file exists

This looks like a failure trying to install a duplicated kprobe, which means an instance of Auditbeat was already running. This kind of collision should not be possible in v7.8.2+ which includes https://github.com/elastic/beats/pull/20325.

**Comment by IkeEichenberger** [comment]
Having the issue:
net.ipv6.conf.all.disable_ipv6 = 1
and getting this error in logs:

May  5 09:34:06 ip-172-16-7-188 auditbeat: Exiting: 1 error: 1 error: system/socket dataset setup failed: unable to guess one or more required parameters: guess_sockaddr_in failed: timeout while waiting for trigger to complete
May  5 09:34:06 ip-172-16-7-188 systemd: auditbeat.service: main process exited, code=exited, status=1/FAILURE
May  5 09:34:06 ip-172-16-7-188 systemd: Unit auditbeat.service entered failed state.
May  5 09:34:06 ip-172-16-7-188 systemd: auditbeat.service failed.

And NO, I can't enable ipv6 in the lo:

**Comment by andrewstucki** [comment]
@IkeEichenberger your error is related to `guess_sockaddr_in` -- the **_ipv4_** probe used to calculate structure offsets for socket address/port data -- it is unrelated to the above error and could be either due to a bug or things such as unsupported kernel version. I would suggest opening up a new bug issue with your error and some basic kernel information and we can prioritize and figure out a time to look at it. Thanks.
