### ISSUE TITLE
Filebeat Nginx module documentation does not reference Nginx ingest pipeline

### ISSUE THREAD

**Issue by rwaight** [elastic/beats#18860]
**Describe the enhancement:**
The [Filebeat Nginx module guide](https://www.elastic.co/guide/en/beats/filebeat/7.7/filebeat-module-nginx.html) could be improved to reference the dependency of the nginx ingest pipeline.

**Describe a specific use case for the enhancement or feature:**
While the Filebeat Nginx ingest pipeline is mentioned in the [Filebeat quickstart guide](https://www.elastic.co/guide/en/beats/filebeat/7.7/filebeat-modules-quickstart.html#load-ingest-pipelines) and in the [Logstash pipelines for parsing guide](https://www.elastic.co/guide/en/logstash/7.7/logstash-config-for-filebeat-modules.html#parsing-nginx), it is not referenced in the [Filebeat Nginx module guide](https://www.elastic.co/guide/en/beats/filebeat/7.7/filebeat-module-nginx.html).

**Comment by andrewkroh** [comment]
All modules have a dependency on an ingest node pipeline. The [overview page mentions this

**Comment by dedemorton** [comment]
@rwaight What do you have in mind? Is it enough to mention the module by name? I'm doing a bunch of updates on the Filebeat docs right now (moving around a lot of content and trying to fix things that are confusing). There's a lot of cruft that has built up over time.

The intro that Andrew describes is in a shared file, which means that including the name wouldn't be difficult.

**Comment by rwaight** [comment]
I was looking at it from how the [Filebeat Cisco module](https://www.elastic.co/guide/en/beats/filebeat/7.7/filebeat-module-cisco.html) has [references to the ingest pipelines](https://www.elastic.co/guide/en/beats/filebeat/7.7/filebeat-module-cisco.html#dynamic-script-compilations), which is provides more clarity to users that an ingest pipeline is needed.

The other alternative would be to have a document (or section of the quick start guide) that specifies which modules _do_ use ingest pipelines and which modules _do not_ use ingest pipelines.

If _all_ modules use ingest pipelines, then we should instead update the [overview page](https://www.elastic.co/guide/en/beats/filebeat/7.7/filebeat-modules-overview.html#filebeat-modules-overview) to clarify that all modules need to have the ingest pipeline loaded.

**Comment by dedemorton** [comment]
Thanks. I think I understand the confusion now. There are some situations where the ingest pipeline doesn't get loaded automatically when you run the module. I'll see what I can do to clarify. Thanks!

**Comment by dedemorton** [comment]
Adding a note that we should also clean up our use of terminology related to ingest node/ingest pipelines/ingest node pipelines. We use all three terms in the docs to more or less mean the same thing. Probably should clean that up when we are updating the module docs.
