### ISSUE TITLE
Expand system/process memory data to include VmSwap Data

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#18863]
**Describe the enhancement:**

As far as I can tell, nothing in `system/process` is collecting per-process Swap stats:

```
cat /proc/1/status | grep Swap
VmSwap:	     220 kB
```

We have cgroup swap stats, but it doesn't appear to be the same. 

**Describe a specific use case for the enhancement or feature:**

Granular swap data is an important part of the diagnostic process for operational memory issues. This might be an easy win.

**Comment by fearful-symmetry** [comment]
Closed, moved to https://github.com/elastic/beats/issues/7461

**Comment by fdartayre** [comment]
@fearful-symmetry this issue has been closed in favor or https://github.com/elastic/beats/issues/7461, but AFAICT we still don't have swap information per process. Can we reopen?
