### ISSUE TITLE
packetbeat error

### ISSUE THREAD

**Issue by lindsay-show** [elastic/beats#1887]
- Version:  packetbeat-1.2.3  elasticsearch-2.3.3 
- Operating System: mac osx 
- Steps to Reproduce: 
First ,I have developed some new protocols in packetbeat source code 
Then,make and ./packetbeat in /packetbeat/ directory 
But ,meeting the following problem：
beat.go:336: CRIT Exiting: Initializing sniffer failed: Error creating decoder: Unsupported link type: UnknownLinkType(12)
Exiting: Initializing sniffer failed: Error creating decoder: Unsupported link type: UnknownLinkType(12)

very strange , libbeat/beat/beat.go only have 325 lines codes

BTW, in order to firgue out  this problem ,I don't config  my new protocol,namely the packetbeat.yml is same to  the elastic.cn

**Comment by urso** [comment]
duplicate: #1823
cross post of hijacked discuss topic: https://discuss.elastic.co/t/error-creating-sniffer-on-os-x-permission-denied/32622/9
