### ISSUE TITLE
metricbeat test config fails if a module is disabled

### ISSUE THREAD

**Issue by turnUpTheChill** [elastic/beats#18896]
## Flaky Test

* **test module:** Name of the failing test.
* **Link:** Link to file/line number in github.
* **Branch:** Git branch the test was seen in. If a PR, the branch the PR was based off.
* **Artifact Link:** If available, attach the generated zip artifact associated with the stack trace for this failure.
* **Notes:** Additional details about the test. e.g. theory as to failure cause
Metricbeat test modules fails if any of the modules in a yaml are disabled. For example, if you run with the default system module config and disable just one of the modules, the whole test fails. in theory it should ignore the disabled modules and test the enabled ones. 
### Stack Trace

```
metricbeat test modules system
Error getting metricbeat modules: module initialization error: disabled module
```

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
