### ISSUE TITLE
[Elastic Agent] Refactor the Fleet Gateway to use long polling instead.

### ISSUE THREAD

**Issue by ph** [elastic/beats#18906]
To reduce the load on the Kibana instance we will move the _checkin_ API from a request/response to support long-polling.

Depends on https://github.com/elastic/kibana/issues/67985

**Comment by ph** [comment]
Kibana PR is up. https://github.com/elastic/kibana/pull/68922

**Comment by ph** [comment]
@michalpristas Can you take a look what need to change on our side for that? I think it should minimal.

**Comment by michalpristas** [comment]
i will take a look

**Comment by ruflin** [comment]
@michalpristas Can this be closed?

**Comment by michalpristas** [comment]
yes closing
