### ISSUE TITLE
Replace references to intrinsic attributes in the Beats documentation

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#18903]
The [new recommendation](https://github.com/elastic/docs/blob/master/README.asciidoc#shared-attributes) is to avoid using intrinsic asciidoc attributes (like `{docdir}` or `{asciidoc-dir}`) and instead use *-root attributes generated by our build, or define *-repo-dir attributes that you can control.

The intrinsic attributes break when you try to reuse content from different paths. 

We need to remove references to `{docdir}` and `{asciidoc-dir}` throughout the docs. 

PS: Let's choose our timing carefully on this one so we don't have any big doc PRs in flight that need to be rebased.

**Comment by andresrc** [comment]
does this need to be done as a single PR or can it be done gradually in multiple small changes?

**Comment by dedemorton** [comment]
Sorry, I think your question got lost in my github notification filters. It would be a simple search, but given the latest thinking about beats, let's just close this issue. We can fix any errors that come up as we encounter them.
