### ISSUE TITLE
Unable to generate non-UTC timezone identifier using strftime

### ISSUE THREAD

**Issue by morganchristiansson** [elastic/beats#1893]
RFC3339 date format requires punctuation (i.e. the :) in the timezone specifier.
But strftime() which is commonly used to produce timestamps is unable to produce the current timezone with a punctuation (a colon it) it other than using a hardcoded Z.
- http://man7.org/linux/man-pages/man3/strftime.3.html

Examples of being unable to use strftime() to produce RFC3339 dates:
- http://stackoverflow.com/a/17700374/34516
- https://www.ruby-forum.com/topic/52657

This is a lower priority as our apps run in UTC timezone and we can hardcode the Z in the time format.

I still suggest not trying to parse the @timestamp field is a much better way to do it. Trying to properly parse dates is hard work and best avoided altogether when possible.

**Comment by ruflin** [comment]
For reference, some previous discussions happened here: https://github.com/elastic/beats/pull/1831

**Comment by morganchristiansson** [comment]
I belive this was fixed in #1889
