### ISSUE TITLE
Change query for ILM alias exist

### ISSUE THREAD

**Issue by simitt** [elastic/beats#19029]
**Problem Description**
While setting up ILM libbeat checks whether or not a `rollover_alias` already exists in Elasticsearch. The check is done by calling `GET /_alias/{name}`, see: https://github.com/elastic/beats/blob/c01dfe680e8d4d810e014c6caa6b0e543c56df57/libbeat/idxmgmt/ilm/client_handler.go#L156

This call resolves to the same call as `GET /*/_alias/xyz` which looks for the alias including all indices, aliases and in the future data streams. This conflicts with some data stream validations in `master`. There is an alternative way for how to check for an alias: `GET {name}/_alias`. 

While these validations are likely to change to avoid compatibility issues, it would be a minimal effort to change the query in libbeat, and ensure that the alias is not checked for data streams. 

related to https://github.com/elastic/elasticsearch/issues/57712

**Comment by urso** [comment]
+1 on changing the URL.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
