### ISSUE TITLE
docs: Create redirects for common docs 404s

### ISSUE THREAD

**Issue by bmorelli25** [elastic/beats#19054]
We should set up redirects for common beats docs 404s.

```
/guide/en/beats
/guide/en/beats/
/guide/en/beats/libbeat/current/setup-repositories.html
/guide/en/beats/libbeat/current/breaking-changes-6.3.html
/guide/en/beats/libbeat/current/logstash-installation.html
/guide/en/beats/filebeat/current/exported-fields-beat.html
/guide/en/beats/filebeat/current/config-filebeat-logstash.html
/guide/en/beats/filebeat/current/exported-fields-env.html
/guide/en/beats/filebeat/current/migration-changed-fields.html
```

The first two are interesting. I'm guessing users edit the URL themselves to try to go to a high-level overview of all Beats.

cc @dedemorton @EamonnTP

**Comment by bmorelli25** [comment]
Do we need a `Team:docs` label for things like this?

**Comment by dedemorton** [comment]
We've already created redirects for most of these: https://github.com/elastic/website-www.elastic.co/issues/6260.

Do the other ones show up in the top 100 now?

**Comment by bmorelli25** [comment]
Awesome! Yes, all of these show up in the top 100 docs 404s of the last week.

**Comment by andresrc** [comment]
@bmorelli25 we can just use `Team:Integrations`

**Comment by dedemorton** [comment]
/guide/en/beats - done 
/guide/en/beats/ - done 
/guide/en/beats/libbeat/current/setup-repositories.html - done
/guide/en/beats/libbeat/current/breaking-changes-6.3.html - done
/guide/en/beats/libbeat/current/logstash-installation.html - done
/guide/en/beats/filebeat/current/exported-fields-beat.html
/guide/en/beats/filebeat/current/config-filebeat-logstash.html
/guide/en/beats/filebeat/current/exported-fields-env.html
/guide/en/beats/filebeat/current/migration-changed-fields.html

**Comment by dedemorton** [comment]
Most of these redirects are already set up so I'm going to close this. I've requested redirects for the 2 remaining (seems like they are the result of people guessing at the URL).
