### ISSUE TITLE
[MetricBeat]keep tags original value, `DeDot` is not unnecessary? 

### ISSUE THREAD

**Issue by kwinstonix** [elastic/beats#19112]
**Describe a specific use case for the enhancement or feature:**

tags value may contain dot, eg: IPv4 address.  I think It is safe to include dots in the tag value.

https://github.com/elastic/beats/blob/0c15394a85134e1797d30592cd08789c4c1a8e1d/x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go#L617-L624

**Comment by kaiyan-sheng** [comment]
Hi @kwinstonix, thanks for opening this issue! You are right, we only need to dedot for tag key, which will be the json field name in Elasticsearch. I will push a PR to fix this soon. Thank you!
