### ISSUE TITLE
[libbeat] Calculate the health status of beats.

### ISSUE THREAD

**Issue by ph** [elastic/beats#19115]
As part of the Elastic Agent, we have added a method over the Manager to report health check back to Fleet in https://github.com/elastic/beats/issues/17737. In our implementation we haven't defined what it means for a specific beat to be healthy or not, Instead, we have defined possible states.

```golang
Unknown Status = iota
// Starting is status describing application is starting.
Starting
// Configuring is status describing application is configuring.
Configuring
// Running is status describing application is running.
Running
// Degraded is status describing application is degraded.
Degraded
// Failed is status describing application is failed. This status should
// only be used in the case the beat should stop running as the failure
// cannot be recovered.
Failed
// Stopping is status describing application is stopping.
Stopping
```

By default we only [added the minimum to make the Agent works](https://github.com/elastic/beats/pull/19114/files). But we should add more logic internally in libbeat to allow to detect issue with the [Elasticsearch output.](https://github.com/elastic/beats/pull/19114/files) or with Metricbeat inputs.

# Acceptance criteria

- [ ] As a user I would like to know if the output is working correctly.
- [ ] Elastic Agent should report to Fleet when an error is happening on the output.
- [ ] Elastic Agent should be set to "degraded" when output aren't working correctly

**Comment by ph** [comment]
@andresrc @urso I was discussing with @blakerouse concerning this issue, we have an issue this week where a beat was reporting "Running" but actually should have reported his status as degraded. The problem was that the beats wasn't able to reach Elasticsearch. If we could make the output reports the status I think that would be a good win for the debugging scenario.

**Comment by ph** [comment]
I've updated the AC of this issue, @urso please review.

I was opting for **degraded** state but, in our code **degraded** means it can be recovered and go back to healthy when a process is marked as **Failed** the agent will restart it.

@blakerouse or @michalpristas might have another opinion.

**Comment by jlind23** [comment]
@ph is this one still relevant?
