### ISSUE TITLE
[Metricbeat] GetStartTimeEndTime potential causing duplicate data

### ISSUE THREAD

**Issue by cx-sbarfoot** [elastic/beats#19126]
Hi Support, @kaiyan-sheng

Please can you elaborate why the GetStartTimeEndTime function was changed to return double period time where as before it return the period. I think this has caused metricbeat to report double metrics.

```
// GetStartTimeEndTime function uses durationString to create startTime and endTime for queries.
func GetStartTimeEndTime(period time.Duration) (time.Time, time.Time) {
	endTime := time.Now()
	// Set startTime double the period earlier than the endtime in order to
	// make sure GetMetricDataRequest gets the latest data point for each metric.
	return endTime.Add(period * -2), endTime
}
```

To reproduce this issue: 
The GetStartTimeEndTime function creates a query time period double that specified. This would mean that if I set the period to 1m and the time was 11am. Let's say that a metric is recorded at 10:59am. The first data collection request where the metric would appear, would be with the following time period, start time=10:58am and the end time=11:00am. This would return one data point at 10:59am. 1m later data collection happens again, with the time period start time=10:59am and the end time=11:01am. This would return the same data point for the error at 10:59am.

queries
[queries.json.txt](https://github.com/elastic/beats/files/4764381/queries.json.txt)
[queries1.json.txt](https://github.com/elastic/beats/files/4764382/queries1.json.txt)

y 1
aws cloudwatch get-metric-data --cli-input-json file://./queries.json
{
    "MetricDataResults": [
        {
            "Id": "request",
            "Label": "myRequestLabel",
            "Timestamps": [
                "2020-06-11T09:40:00Z"
            ],
            "Values": [
                1.0
            ],
            "StatusCode": "Complete"
        }
    ],
    "Messages": []
}

query 2 
aws cloudwatch get-metric-data --cli-input-json file://./queries1.json
{
    "MetricDataResults": [
        {
            "Id": "request",
            "Label": "myRequestLabel",
            "Timestamps": [
                "2020-06-11T09:40:00Z"
            ],
            "Values": [
                1.0
            ],
            "StatusCode": "Complete"
        }
    ],
    "Messages": []
}

**Comment by cx-sbarfoot** [comment]
@kaiyan-sheng please let me know if you need any details from me

**Comment by cx-sbarfoot** [comment]
@kaiyan-sheng do you have any updates?

**Comment by cx-sbarfoot** [comment]
@ycombinator @kaiyan-sheng  is there any update?

**Comment by hhuang-godaddy** [comment]
This should be considered as a bug. It effectively caused publishing the same metric data twice.

**Comment by hhuang-godaddy** [comment]
https://github.com/elastic/beats/blob/683130a37daf0ee3399aa363fdee64e98c78f649/x-pack/metricbeat/module/aws/utils.go#L34
This should be just 
```return endTime.Add(period * -1), endTime```

**Comment by hhuang-godaddy** [comment]
https://github.com/elastic/beats/blob/683130a37daf0ee3399aa363fdee64e98c78f649/x-pack/metricbeat/module/aws/utils.go#L34
This should be just 
```return endTime.Add(period * -1), endTime```
@kaiyan-sheng
