### ISSUE TITLE
[Elastic Agent] Limit Endpoint usage

### ISSUE THREAD

**Issue by blakerouse** [elastic/beats#19130]
- With the enablement of Endpoint in the Elastic Agent, Agent needs to know that Endpoint cannot run even if present in the configuration unless Elastic Agent is connected and controlled by Fleet.
- We should also enforce only one endpoint can be managed at any time from an Elastic Agent.

**Comment by ph** [comment]
There is currently no plan to support endpoint outside of the fleet execution, actually, we should prevent that in the spec file definition.

cc @ferullo

**Comment by paul-tavares** [comment]
@ph FYI - on the Kibana side we have an issue tracking to enforce in the UI/API that only at most 1 endpoint integration should be part of a Agent Configuration. Perhaps that Issue can be expanded to also only allow Endpoint to be added if Fleet is enabled?

Issue here: https://github.com/elastic/kibana/issues/64371
