### ISSUE TITLE
[Elastic Agent] Starting beats with log level of trace causes every event to be logged

### ISSUE THREAD

**Issue by blakerouse** [elastic/beats#19179]
I noticed that running the Elastic Agent that all the started beats are started in trace mode. While this helps with debugging it also currently causes all events to be logged to the log for that running beat.

I think we should either lower the logging level to ensure that every event is not logged, or adjust the debug selector to ensure that events are not logged.

**Comment by michalpristas** [comment]
we had a discussion with @ruflin and @ph somewhere on slack about this

i changed it to info 
https://github.com/elastic/beats/pull/18657

and reverted here
https://github.com/elastic/beats/pull/18726

so we can get more information when raising issues until 8.0

**Comment by blakerouse** [comment]
I agree that having more information is great, but having every event in
the log will fill up the local disk and make it harder to parse a log to
help with debugging.

We should see if we can keep it the way it is, but turn off just the
logging of each event.

**Comment by ruflin** [comment]
My end goal is to have info by default but allow users to dynamically enable debug if needed. A first step should be to allow it at least on restart to change (@michalpristas do we already have this)? And +1 on the proposal from @blakerouse to be more specific on what trace means and remove some of the data if we can.

**Comment by michalpristas** [comment]
yes we can change event level on restart. this will change both agent and beats level. 
we support trace, debug, info and error 
we differentiate between trace and debug but beats does not have a notion of trace level so we use debug when trace is used

**Comment by michalpristas** [comment]
closing as we moved to `info` log level recently
