### ISSUE TITLE
GeoIP does not work on MacOSX

### ISSUE THREAD

**Issue by andydude** [elastic/beats#1918]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For confirmed bugs, please report:
- Version: 
- Operating System: 
- Steps to Reproduce:

**Comment by andydude** [comment]
When running packetbeat with elasticsearch as the only output, and geoip enabled, I get the following stacktrace:

http://pastie.org/pastes/10892091/text

**Comment by tsg** [comment]
Hi, which GeoIP library did you install and to which file are you pointing Packetbeat to? Please also post your configuration file.

**Comment by andydude** [comment]
interfaces:
  device: en0

protocols:
  dns:
    ports: [53]
    include_authorities: true
    include_additionals: true
  http:
    ports: [80, 8080, 8000, 5000, 8002]
  memcache:
    ports: [11211]
  mysql:
    ports: [3306]
  pgsql:
    ports: [5432]
  redis:
    ports: [6379]
  thrift:
    ports: [9090]
  mongodb:
    ports: [27017]

output:
  elasticsearch:
    hosts: ["http://localhost:9200"]
    bulk_max_size: 50

shipper:
  geoip:
    paths:
      - "**PATH_TO**/GeoLite2-City.mmdb"

logging:
  to_syslog: true
  to_files: false

**Comment by andydude** [comment]
I'm using the only library I could find:
https://www.maxmind.com/en/geoip2-city

**Comment by tsg** [comment]
Try the legacy geoip city database instead: https://dev.maxmind.com/geoip/legacy/geolite/

See the docs here: https://www.elastic.co/guide/en/beats/packetbeat/1.2/configuration-shipper.html#_geoip_paths
