### ISSUE TITLE
Journalbeat container image output is incompatible with ECS

### ISSUE THREAD

**Issue by baileygm** [elastic/beats#19188]
Using Journalbeat, logstash and elasticsearch version 7.7.1 we are getting bulk indexing errors due to an incompatibility with the ECS schema

Journalbeat appears to be outputting container.image as a concrete value whereas ecs defines it as object with 2 fields - container.image.name and container.image.tag

- Version: 7.7.1
- Operating System: Ubuntu / docker
- Forum URL: https://discuss.elastic.co/t/journalbeat-container-image-output-incompatible-with-ecs/236475

**Comment by baileygm** [comment]
Has this issue been addressed in later releases of Journalbeat ?

**Comment by jlind23** [comment]
Hello @baileygm  

As of 7.16 journald is provided as an input to Filebeat: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-journald.html which supports multi-line. Consequently journalbeat has been deprecated from that release onwards.
Then unfortunately this concern will not be addressed.

cc @kvch
