### ISSUE TITLE
[Elastic Agent] Proposal: Rename logs input type to logfile

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#19187]
Over the past weeks it has come to several confusion between `input.type: logs` and `dataset.type: logs`. The input type logs exists in Filebeat since day one and was the only input supported in the early days. Over time we added more inputs like syslog, tcp, S3 and others. Now looking at the name `logs` it is too generic and also confusing in some parts of the config. What the logs input does, is tail a file which contains log entries separated by a newline (simplified).

To remove the confusion and make it more obvious what the input is for, I propose to rename it to `logfile` or `log_file`. I also played with the idea of naming it `file` but this is too generic again.

This is not about renaming it in Filebeat itself, but only when used in the Agent.

**Comment by ruflin** [comment]
@ph Would be great to get your input on this.

**Comment by michalpristas** [comment]
i think logfile sounds ok, change is also not that difficult we can support both for some time until kibana change is in place

**Comment by ph** [comment]
+1 for _logfile_, well _file_ is indeed generic but you can do more than just log :)

**Comment by ruflin** [comment]
Closing this as I filed https://github.com/elastic/beats/issues/19318 as the implementation tracking issue. @ph I assume you prefer `logfile` over `log_file` as this is the one you picked :-)

**Comment by ph** [comment]
@ruflin I don't have a preference to be honest, naming is hard and would like to move quickly on this. :)
