### ISSUE TITLE
[Filebeat] Panic in Windows nano server container

### ISSUE THREAD

**Issue by zhiweiv** [elastic/beats#19185]
It should be same issue with https://github.com/golang/go/issues/21867, latest klog fixed it: https://github.com/kubernetes/klog/blob/master/klog_file.go#L62

- Version: 
7.7 
- Operating System: 
Windows nano server container
- Discuss Forum URL:
https://discuss.elastic.co/t/filebeat-panic-in-windows-nano-server-container/236838
- Steps to Reproduce: 
FROM mcr.microsoft.com/windows/nanoserver:1809
COPY . /app/
docker build -t fb:v1 .
docker run -it --rm fb:v1 cmd
C:\app>filebeat-7.7.exe
panic: Failed to load netapi32.dll: The specified module could not be found.

goroutine 1 [running]:
syscall.(*LazyProc).mustFind(0xc000083920)
/usr/local/go/src/syscall/dll_windows.go:311 +0x5f
syscall.(*LazyProc).Addr(0xc000083920, 0x1a)
/usr/local/go/src/syscall/dll_windows.go:318 +0x32
syscall.NetGetJoinInformation(0x0, 0xc0002dda00, 0xc0002dd9fc, 0xd, 0xc000385080)
/usr/local/go/src/syscall/zsyscall_windows.go:1804 +0x38
os/user.isDomainJoined(0xc0002dda58, 0x44b72e, 0x0)
/usr/local/go/src/os/user/lookup_windows.go:18 +0x5a
os/user.lookupFullName(0xc0003f25f0, 0xc, 0xc0003f25e0, 0xd, 0xc000385080, 0x1a, 0xd, 0xc000385080, 0x1a, 0x1)
/usr/local/go/src/os/user/lookup_windows.go:55 +0x2d
os/user.newUser(0xc0003f25b0, 0xc, 0xc0003f25d0, 0xc, 0xc000385040, 0x16, 0xc0003f25e0, 0xd, 0xc0003f25f0, 0xc, ...)
/usr/local/go/src/os/user/lookup_windows.go:186 +0xd4
os/user.current(0x0, 0x0, 0x0)
/usr/local/go/src/os/user/lookup_windows.go:230 +0x2bd
os/user.Current.func1()
/usr/local/go/src/os/user/lookup.go:15 +0x29
sync.(*Once).doSlow(0x463c900, 0x292a030)
/usr/local/go/src/sync/once.go:66 +0xea
sync.(*Once).Do(...)
/usr/local/go/src/sync/once.go:57
os/user.Current(0xc0003f25a0, 0xc, 0x2804065)
/usr/local/go/src/os/user/lookup.go:15 +0xf9
k8s.io/klog.init.1()
/go/src/github.com/elastic/beats/vendor/k8s.io/klog/klog_file.go:58 +0x48

**Comment by andresrc** [comment]
We need to look for the right moment to update the client library.

**Comment by zhiweiv** [comment]
Any new? we can only use filebeat 7.3 in Windows container for now.

**Comment by zhiweiv** [comment]
Copy netapi32.dll  to /Windows/System32 works.
https://github.com/kubernetes-csi/csi-driver-smb/blob/847b2f335c45b41a38d5703933301c0b7b767cd2/pkg/smbplugin/Windows.Dockerfile
