### ISSUE TITLE
Agent crash on latest master

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#19215]
I'm hitting something weird on Agent:  
```elastic-agent_1     | 2020-06-16T11:46:56Z ERROR	reporter.go:47	2020-06-16T11:46:56Z: type: 'ERROR': sub_type: 'CONFIG' message: Application: metricbeat[8f443d17-d1b5-4f4a-beac-76ff94b18664]: application 'metricbeat--8.0.0-SNAPSHOT' crashed: /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/core/plugin/app/app.go[214]: unknown error. ```

This happens when I run Agent with the compose approach `docker-compose -f snapshot.yml -f agent.yml up --force-recreate` as suggested at https://github.com/elastic/integrations/tree/master/testing/environments.

Using `docker.elastic.co/beats/elastic-agent:7.8.0-SNAPSHOT` works fine.

cc: @michalpristas

**Comment by ruflin** [comment]
I've seen something similar today and was not sure if it could be related some issues with the system package (@fearful-symmetry ).

@ChrsMark Do you have access to the metricbeat load file by chance?

**Comment by ChrsMark** [comment]
> @ChrsMark Do you have access to the metricbeat load file by chance?
```console
[root@5e96509e65a2 elastic-agent]# cd data/install/
[root@5e96509e65a2 install]# ./metricbeat-8.0.0-SNAPSHOT-linux-x86_64/
kibana/     metricbeat  module/     modules.d/  
[root@5e96509e65a2 install]# ./metricbeat-8.0.0-SNAPSHOT-linux-x86_64/metricbeat version
metricbeat version 8.0.0 (amd64), libbeat 8.0.0 [8745e17354de069f4a7f655af6e8dc0f155e3c6f built 2020-06-14 08:42:31 +0000 UTC]
```

**Comment by fearful-symmetry** [comment]
@ruflin I've never run into anything like this?

**Comment by blakerouse** [comment]
@ChrsMark Does that latest snapshot have: https://github.com/elastic/beats/pull/19178

This could be same issue as #19165

**Comment by ChrsMark** [comment]
@blakerouse it seems that the snapshot doesn't have it. Its on https://github.com/elastic/beats/commit/8745e17354de069f4a7f655af6e8dc0f155e3c6f.

I will try with a newer one, and come back. Thanks!

**Comment by ChrsMark** [comment]
It's fixed for latest snapshot.
