### ISSUE TITLE
How to change inbuilt modules index name with the same fields?

### ISSUE THREAD

**Issue by anust** [elastic/beats#19231]
I want to change default filebeat-* index name to zeek-* with the same fields as configured in the zeek.yml, Until now I have changed 

 hosts: ["localhost:9200"]
  protocol: "http"
  index: "zeek-%{+yyyy.MM.dd}"

setup.template:
  name: 'zeek-*'
  pattern: 'zeek-*'
  enabled: true

setup.template:
  name: 'zeek-*'
  pattern: 'zeek-*'
  enabled: true
  setup.ilm.enabled: false

but still getting all the fields in filebeat-* index instead of zeek-* index, any help is appreciable.

**Comment by anust** [comment]
Also, I have change kibana dashboard id filebeat-* to zeek-* in its dashboard  Filebeat-Zeek-Overview.json file. what else I need to do? I have a siem with multiple sources, suricata, netflow and zeek, and they are conflicting with the index pattern , any person whi is being successful in SIEM from multiple servers using filebeat to the same Elasticsearch server may help.

**Comment by anust** [comment]
@botelastic how to add it?

**Comment by jsoriano** [comment]
Hey @anust,

We try to keep the github issue tracker for confirmed issues an enhancement requests, for questions about Beats usage please use the forum in https://discuss.elastic.co/c/elastic-stack/beats/
You can probably find some threads there about using custom index names. If they don't help, please open a new topic there.
