### ISSUE TITLE
[Metricbeat] Collect tags for clusters when using rds metricset

### ISSUE THREAD

**Issue by n0othing** [elastic/beats#19274]
**Describe the enhancement:**

The AWS module's rds metricset collects tags [1] for instances. It'd be useful to retrieve tags for clusters as well.

[1] https://github.com/elastic/beats/blob/master/x-pack/metricbeat/module/aws/rds/rds.go#L187

**Comment by amandahla** [comment]
@n0othing I made some change [here](https://github.com/estaleiro/beats/tree/iss19274). Could you test?

**Comment by kaiyan-sheng** [comment]
Thanks @amandahla 👍 Would you mind making a PR for this so we can get it into the master branch?

**Comment by amandahla** [comment]
@kaiyan-sheng Sure! PR created

**Comment by kaiyan-sheng** [comment]
@amandahla Thank you!!
