### ISSUE TITLE
Enhance Beats CI to call new e2e Agent test when Elastic Agent files change

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#19291]
**Describe the enhancement:**
Enhance Beats CI to call new e2e Agent test when Elastic Agent files change
 - Automation Team was kind enough to help us set up a small initial test for Agent!  The next step is to have it run when Agent files change.  
Files from this repo location should trigger the noted CI:
https://github.com/elastic/beats/tree/master/x-pack/elastic-agent

The e2e test is here:
https://github.com/elastic/e2e-testing/tree/master/e2e/_suites/ingest-manager

It can be called as, from the elastic/e2e-testing repo e2e/_suites/ingest-manager
$ godog -t stand_alone_mode
 - you'll also need dependencies of course.  specifics are being Doc'ed for that immediately so we can use them here.

Note, this project is in use for Metricbeat already.

Question for @ruflin @ph @michalpristas - should we also run this separate test when Metricbeat or Filebeat changes are put in to ensure nothing from those repos breaks Elastic Agent downstream?  
Meaning, changes to these locations will trigger the Ingest Manager / Agent e2e test as well:
 - https://github.com/elastic/beats/tree/master/filebeat
 - https://github.com/elastic/beats/tree/master/metricbeat

**Describe a specific use case for the enhancement or feature:**
Lets say a developer somehow puts a bug into the code, during PR CI this could catch it so it isn't merged, which saves the company time overall.

**Comment by ruflin** [comment]
++ on having these changes also when MB / FB changes for now. I assume these tests can be run in parallel so it should not increase build time?

**Comment by ph** [comment]
++ for MB/filebeat.

@EricDavisX with so many test triggered. I wonder what is the plan to get notified?

**Comment by EricDavisX** [comment]
My assumption is that we will notify on the PR author for build breaks on their PR.  I'm unsure if we have anything more formal to cite, or any adjustments to that general idea?

**Comment by ph** [comment]
@EricDavisX I though it was periodically run and not done on every PR?

**Comment by EricDavisX** [comment]
this ticket is specific to the ci / pr work.  you are correct that the repo currently builds nightly.   I think... here: 
https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-ingest-manager-daily/activity

**Comment by EricDavisX** [comment]
Victor and Ivan, hi @kuisathaverat @v1v - Manu pointed me in your direction to get a walk-thru of the Beats-ci.  I can try to implement this, I have a bit of Jenkinsfile experience, but when I sat and looked at the repo and the flow of operations I had too many questions already.  :)

Capturing info I got from Ivan:
we build the Elastic Agent Docker image with every merge on the master branch of Beats, this image is published as `docker.elastic.co/observability-ci/elastic-agent`  the one published on docker.elastic.co/beats/elastic-agent is published daily by the release team. 

Ivan notes that any Elastic user can trigger the packaging job with a comment in a PR /package or /packaging  (both works), also manually from the PR job in Jenkins, this will publish an image in  docker.elastic.co/observability-ci/elastic-agent:COMIT_SHA

I will put a meeting request out perhaps for us to look at this sometime soon!
The questions i already have, to target after the brief walk thru:

1 in Beats ci, where is the code that's doing the prep for a given Agent pr in terms of test.  I see a test stage but am not sure how to reverse trace where the source lies.  https://github.com/elastic/beats/blob/master/.ci/build-docker-images.groovy#L67
... is this only for Release BC / GA builds perhaps? I need to identify the place add in additional tests, don't see it yet, if not this.

2 how literally, can I call the same functions (with api?), that are listed above as exposed commands for building the Docker container /package?  we could just have it called immediately after every PR is created.
...the next step would be to have an automatic deletion right? :)  something like... 24 hours after the pr is closed, or perhaps just when the pr is closed / merged we can trigger a deletion.

3 I tried the /package command in this pr:  https://github.com/elastic/beats/pull/19805 but I'm not sure I see any indication it *did anything... how does a user know its done to look in docker.elastic.co/observability-ci/elastic-agent:COMIT_SHA

4 I might ask Manu for an example docker compose file and environment setup which would run the noted test with latest Kibana/ES and COMIT_SHA Agent container triggered from the Beats repo (in ci).  
...And as relates to the nuances of the e2e test, as an immediate follow up, if the docker container built in the pr will have the 'Agent' as the main process in the container we'll only be able to run a smaller portion of tests with the pr's agent code (due to current Agent usage knowledge... to more than basic 'stand-alone' agent usage we'd need to know if we can enroll an active agent and have the configuration switch from stand-alone to fleet-mode without restarting Agent (the container).  If that can't be done, we could think about implementing support to enable testing (separate product side ticket).  If nothing else tho, I would still like to follow thru and set up tests against the stand-alone feature file.

**Comment by kuisathaverat** [comment]
>1 in Beats ci, where is the code that's doing the prep for a given Agent pr in terms of test. I see a test stage but am not sure how to reverse trace where the source lies. https://github.com/elastic/beats/blob/master/.ci/build-docker-images.groovy#L67
... is this only for Release BC / GA builds perhaps? I need to identify the place add in additional tests, don't see it yet, if not this.

This pipeline is for Integration test Docker images, it is triggered daily. So you want to add additional tests for the Elastic Agent, When you need to run those tests? Scheduled? On all PRs? On merges? Manually? 

>2 how literally, can I call the same functions (with api?), that are listed above as exposed commands for building the Docker container /package? we could just have it called immediately after every PR is created.
...the next step would be to have an automatic deletion right? :) something like... 24 hours after the pr is closed, or perhaps just when the pr is closed / merged we can trigger a deletion.

I am not sure to understand the use case, but Is not the same we make with the `/package` GitHub comment, this triggers the packaging job to publish a Docker image. About delete the Docker images, the disk space is not an issue, thus the Infra team does not have any policy to delete Docker images, also we are storing only deltas between Docker images.

>3 I tried the /package command in this pr: #19805 but I'm not sure I see any indication it *did anything... how does a user know its done to look in docker.elastic.co/observability-ci/elastic-agent:COMIT_SHA

the packaging job send some GitHub checks to the PR, your comments on that PR did not work because a bug I should introduce on Thursday with my latest changes in that job, I have to check it.

>4 I might ask Manu for an example docker compose file and environment setup which would run the noted test with latest Kibana/ES and COMIT_SHA Agent container triggered from the Beats repo (in ci).
...And as relates to the nuances of the e2e test, as an immediate follow up, if the docker container built in the pr will have the 'Agent' as the main process in the container we'll only be able to run a smaller portion of tests with the pr's agent code (due to current Agent usage knowledge... to more than basic 'stand-alone' agent usage we'd need to know if we can enroll an active agent and have the configuration switch from stand-alone to fleet-mode without restarting Agent (the container). If that can't be done, we could think about implementing support to enable testing (separate product side ticket). If nothing else tho, I would still like to follow thru and set up tests against the stand-alone feature file.

I guess that it would depend on the use, maybe we want to run those tests directly on Elastic Cloud with the latest Kibana snapshot.

**Comment by EricDavisX** [comment]
Thank you @kuisathaverat again, those are good detailed questions!  my reply below:

> > 1 in Beats ci, where is the code... 
> This pipeline is for Integration test Docker images, it is triggered daily. So you want to add additional tests for the Elastic Agent, When you need to run those tests? Scheduled? On all PRs? On merges? Manually?

I propose we add in support to run this set of tests on every Agent oriented Beats PR when it is first opened, and allow pr owners to run it again before they merge with something like a  '/test-agent' option.  There is a separate job running the test nightly already.


> > 2 how literally, can I call the same functions (with api?), that are listed above as exposed commands for building the Docker container /package? we could just have it called immediately after every PR is created.
> > ...the next step would be to have an automatic deletion right? :) something like... 24 hours after the pr is closed, or perhaps just when the pr is closed / merged we can trigger a deletion.
> 
> I am not sure to understand the use case, but Is not the same we make with the `/package` GitHub comment, this triggers the packaging job to publish a Docker image. About delete the Docker images, the disk space is not an issue, thus the Infra team does not have any policy to delete Docker images, also we are storing only deltas between Docker images.

I believe the intent is clear now, to run it one time with every Beats PR (when Agent code or Metricbeat or Filebeat code folders are updated) and to have manual option to re-run it.  I was looking for the source code for the docker build, just so I can copy it and review it.  If there is another way to get the code from a PR tested before its merged I am open to the easiest option.  And, I'm glad we need not concern over docker image deletion.  

> > 4 I might ask Manu for an example docker compose file and environment setup which would run the noted test with latest Kibana/ES and COMIT_SHA Agent container triggered from the Beats repo (in ci).
> > ...And as relates to the nuances of the e2e test, as an immediate follow up, if the docker container built in the pr will have the 'Agent' as the main process in the container we'll only be able to run a smaller portion of tests with the pr's agent code (due to current Agent usage knowledge... to more than basic 'stand-alone' agent usage we'd need to know if we can enroll an active agent and have the configuration switch from stand-alone to fleet-mode without restarting Agent (the container). If that can't be done, we could think about implementing support to enable testing (separate product side ticket). If nothing else tho, I would still like to follow thru and set up tests against the stand-alone feature file.
> 
> I guess that it would depend on the use, maybe we want to run those tests directly on Elastic Cloud with the latest Kibana snapshot.

I'm assuming that we'd do as little work as possible to make this go as quick as possible... I am ok with whatever is quickest for us to implement.  If we use a setup on cloud it sounds like we would need to modify more of the test configuration and setup, which is a downside - I'd like to keep things with as few permutations of us as possible, so we need only 'learn it' one time and we'll know how to maintain the tests.  Still, lets talk about whats quickest to implement!  @mdelapenya do you have any thoughts as to how it would be easiest to re-use the e2e-testing framework work we have for Ingest Manager in Beats?  I wonder if I am not using some common assumptions that others with more experience in Beats / Observability would have.  Any help guiding this is great.  sorry to pull you in to a long git thread!  :)

**Comment by EricDavisX** [comment]
I spoke with Ivan in a brief meeting and we confirmed the following:

- He can work this in near term with Manu's help for instructions to run the e2e test.
- He can include me or PH for any spec / requirements for the test
- we decided for now that we'd run the test with every commit that includes Metricbeat, Filebeat, or Agent code as noted.  
... with the exception that it won't be run if there is the common "no ci" label, or if it is a draft-pr.
- he can also follow thru after the initial work is done to add in a Jenkins github hook command to 'Jenkins run Agent tests' or something similar in an on-demand fashion

He expects it will take a few days of work total, estimated.  And we can sync next week to see how its going.  Thanks @kuisathaverat I appreciate it!

**Comment by kuisathaverat** [comment]
>... with the exception that it won't be run if there is the common "no ci" label, or if it is a draft-pr.

This is a work in progress feature we do not have ETA yet

**Comment by kuisathaverat** [comment]
I have created the issue https://github.com/elastic/beats/issues/20131

**Comment by ph** [comment]
@EricDavisX assigning this to you since its in progress and you are following the work.

**Comment by EricDavisX** [comment]
@ph @kuisathaverat Hi - Ivan, I'll ping you for an update on when we can work with you on this?
Is it something we can plan for near-term (this coming release time frame?)

**Comment by EricDavisX** [comment]
we're tracking coming progress in https://github.com/elastic/beats/issues/20131, fyi

**Comment by mdelapenya** [comment]
I believe we can close this one, as every time a PR is packaged, then the e2e tests are triggered.

**Comment by ruflin** [comment]
So if I understand this correctly, to run it at the moment it is required that the dev adds a comment to the PR?

**Comment by kuisathaverat** [comment]
yep, if you put the comment `/package` or  `/packaging` you will build the packages for that PR and run the e2e test, right now is not granular and you will generate all packages before running the tests, this now takes 1h 30min, but we are working to reduce it to 24min on average and 10 min running only the needed platform and beat

**Comment by ph** [comment]
@kuisathaverat Can you link that issue and PR here?

**Comment by ruflin** [comment]
@kuisathaverat This is great and exactly what I'm looking for so it can be run on each PR.

**Comment by kuisathaverat** [comment]
we have a PR open https://github.com/elastic/beats/pull/22178 we are dealing with a concurrence issue with the GCP plugin as soon as we resolved it we can merge it.
