### ISSUE TITLE
Add syslog over TCP with TLS support to the Checkpoint module

### ISSUE THREAD

**Issue by abraxxa** [elastic/beats#19309]
**Describe the enhancement:**
Please add syslog over TCP with TLS support to the Checkpoint module.

**Describe a specific use case for the enhancement or feature:**
For secure (TLS) and reliable (TCP) transport of log data.

If you wouldn't bundle inputs and processing in the modules but let the user combine inputs and processing themselves you wouldn't need to add this support to every module separately which would give us users much more flexibility.

**Comment by hazcod** [comment]
@abraxxa this was added, see https://github.com/elastic/beats/pull/21988

**Comment by andrewkroh** [comment]
Closed by #19560.
