### ISSUE TITLE
Filebeat - Fields from disabled modules in ingested data

### ISSUE THREAD

**Issue by 0xtf** [elastic/beats#19311]
- Version: 7.8.0
- Operating System: Ubuntu 18.04
- Steps to Reproduce: Upgraded from a former (7.7.1) version of Filebeat.

I've noticed that since the upgrade to the latest stable, several fields from:

- misp
- aws
- cef
- zeek
- azure
- netflow

Started showing up in my ingested data, even though all those modules are disabled (and were never enabled before).

A few screenshots:

![image](https://user-images.githubusercontent.com/24301448/85178693-0e5c3e00-b277-11ea-954c-f51990d45fa7.png)

![image](https://user-images.githubusercontent.com/24301448/85178707-17e5a600-b277-11ea-9132-87d0ba7b7c89.png)

I'm curious if this is an expected behavior.

**Comment by P1llus** [comment]
Related to or duplicate https://github.com/elastic/kibana/issues/69545.

Just adding that here for tracking purposes.

**Comment by martensson** [comment]
I got the same issue after upgrading today from 7.7.1 to 7.8, a bunch of new fields are created.

**Comment by StefanSa** [comment]
Same problem here since upgrading to 7.8.

**Comment by andresrc** [comment]
Closing this in favor of https://github.com/elastic/kibana/issues/69545 and https://github.com/elastic/elasticsearch/pull/58418
