### ISSUE TITLE
[Filebeat][Fortinet Module] Triage on changes needed to add support for FortiAnalyzer

### ISSUE THREAD

**Issue by P1llus** [elastic/beats#19315]
Forwarding logs from Fortinet products from Fortianalyzer is a common usecase scenario. Research needs to be put into how this affects current and any future filesets on this module, to add support for both.

**Comment by fredtj** [comment]
I've ticketed Fortinet on this issue and they weren't very helpful. They basically said they could find no mention of these fields in their documentation and also said they "think" it is not possible to turn them off. I have asked for clarification from them:

> Basically, the FAZ is adding (at least) 2 fields to forwarded logs:
>
>tz (sometimes already exists in original log message and is added again by FAZ)
>timestamp (already exists as eventtime in original log message and is added again as timestamp by FAZ)
>
>There is no mention of these fields in your documentation.
>
>Can you please confirm:
>
>1) Are we able to disable these extra fields?
>2) Are there any other fields we should be aware of that FAZ may add to forwarded log messages?
