### ISSUE TITLE
[libbeat] add_docker_metadata fails when docker daemon restarts

### ISSUE THREAD

**Issue by LucaWintergerst** [elastic/beats#19323]
**The Issue:**
Using the `add_docker_metadata` processor requires users to mount the `docker.sock` 
If the docker daemon restarts, this sock becomes unavailable.
Even after docker restarted successfully, the sock is still not accessible and the Beat will log
`Error watching for docker events: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
every second. 

Depending on the configuration of the beat and the usage in Kibana, this can have severe consequences.
- using the docker fields in Kibana breaks if this happens, as these fields are no longer present
- conditionals in the beats config for dropping/forwarding events breaks 

This scenario can happen frequently due to dockers `live-restore`, where it keeps containers alive when the daemon restarts. 
https://docs.docker.com/config/containers/live-restore/

There's an issue in the Moby repository, which talks about this exact scenario, but it's been open for more than 4 years and does not really get much attention. https://github.com/moby/moby/issues/21109

The reason why I expect many people to run into this, is the way some cloud providers run docker. 
For example, GKE has this script which monitors the docker daemon. 
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/health-monitor.sh

What it does is it runs `docker ps`, and if it does not respond within 60 seconds, it kills the daemon and restarts it. 

60s is a long time, but especially on busy Kubernetes nodes, this can happen somewhat frequently. 
The daemon restart does not impact the Kubernetes cluster in any way, but because of the `live-restore` mentioned above, it kills the docker.sock

**Ideas for a fix:**
We are obviously working around an upstream issue here, so the solution will not be perfect. 
I propose that we add a flag to beats, which tells the process to exit cleanly if it encounters the error more than 30 times (that's 30 seconds of erroring)
Docker/K8s would then just restart that failed container. 

**Steps to reproduce:** 
This error appears for (likely) all of the beats versions. We most recently tested with 7.8, 7.7 and 7.5. It would make sense that the version does not make a difference for an error of this kind. 

- launch a beat in GKE with the add_docker_metadata processor 
- get the pod and the node it's running on: `kubectl get pods -o wide`
- ssh to the node: `gcloud compute ssh gke-foo-bar-node-1`
- become root: `sudo su`
- kill docker: `systemctl kill --kill-who=main docker` 

`curl --unix-socket /var/run/docker.sock http://localhost/containers/json` fails inside the container when this happens, so the fix is not as simple as just reconnecting

**Comment by exekias** [comment]
Thank you for opening @LucaWintergerst, have you tried mounting the `/var/run/` instead of just the socket? If it gets recreated we should be able to pick the new one that way

**Comment by LucaWintergerst** [comment]
Thanks @exekias, that fixes it! 

Should we update ours docs / templates to include this, or do we see any major downsides to mounting all of `/var/run`?

**Comment by exekias** [comment]
I've opened https://github.com/elastic/beats/pull/19541
