### ISSUE TITLE
k8s manifests for Master nodes to monitor control plane

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#19331]
**Describe the enhancement:**
Currently the k8s manifests we provide to the users have not `controllermanager`, `scheduler` enabled by default. We could add manifests for these Master specific metricsets and deploy with a Daemonset with access to host network along with a `nodeSelector` to only deploy on Master Nodes of k8s cluster.

**Describe a specific use case for the enhancement or feature:**
With this we will provide a wider out-of-the box solution to the users avoid having them enabling the metricsets on their own in case they need them.

**Comment by exekias** [comment]
good point @ChrsMark! I wonder if we could achieve this also by using autodiscover in the daemonset

**Comment by ChrsMark** [comment]
> good point @ChrsMark! I wonder if we could achieve this also by using autodiscover in the daemonset

It should be possible! It could be a commented out section in the Daemonset's Configmap with a relevant note. Do you find it more preferable?
