### ISSUE TITLE
Winlogbeat: include_xml option is not working with experimental api

### ISSUE THREAD

**Issue by theodiefenthal** [elastic/beats#19339]
When using the new experimental API of winlogbeat 7.7+, setting `include_xml` option in the config has no more effect. There is no "original xml" data field in the produced event anymore.

**Comment by andrewkroh** [comment]
This is a known limitation as of now for the experimental API and it is mentioned in the docs https://www.elastic.co/guide/en/beats/winlogbeat/7.7/configuration-winlogbeat-options.html#_event_logs_api. We'll have to address it before bring this feature out of "experimental". Thank you for testing it and reporting issues.

> Setting include_xml: true has no effect.
