### ISSUE TITLE
Filebeat Cisco Module, IOS fileset, issue with timezone

### ISSUE THREAD

**Issue by jasonslater2000** [elastic/beats#19383]
During daylight savings, Cisco WS-C3650-48PD seems to output the following format:

Jun 23 10:20:17 xxxx.corp.xxx 44124: hostname: Jun 23 10:20:16.775 PSTDST: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet2/0/10, changed state to down

Which causes these the timestamp parsing in the ingest yml to fail.

Not sure if this is something which needs a different setting on the cisco device, or something we should handle.  Will amend this ticket as I learn more.

**Comment by kaiyan-sheng** [comment]
Hello, thanks for creating this issue. But we would kindly ask you to post all questions and issues on https://discuss.elastic.co/c/beats before opening a Github Issue. Your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue or open a new one with more details. Thanks in advance! 

Also if you could give an example log from cisco for us to reproduce the error locally, that would be very helpful.
