### ISSUE TITLE
Filebeat exclude_lines prior to multiline

### ISSUE THREAD

**Issue by ptrlv** [elastic/beats#1940]
Filebeat (1.2.3) feature request to drop lines prior to being included in a multiline message. According to the docs exclude_lines is done after the multiline is combined.

**Comment by Busindre** [comment]
+1

**Comment by Cepega-kef** [comment]
Is issue dead?)

**Comment by Suchismita1tutun** [comment]
In which release this feature will be available?

**Comment by zzq0324** [comment]
Any solution? I have the same problem ~
