### ISSUE TITLE
Support for ESXi and vCenter 6.7 and 7 for Metricbeat vSphere Module

### ISSUE THREAD

**Issue by amitkv321** [elastic/beats#19435]
As per [vSphere module](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-vsphere.html#metricbeat-module-vsphere) metricbeat reference,
vSphere module library is built for and tested against ESXi and vCenter 5.5, 6.0 and 6.5.

**Can we expect support for ESXi and vCenter 6.7? or Is there any way to configure vSphere module to support ESXi and vCenter 6.7?**
![image](https://user-images.githubusercontent.com/39275588/85856879-672b5980-b7d6-11ea-8e96-6a0f65cd8686.png)

**Update**: Update govmomi and check support with ESXi 7 too.

**Comment by jsoriano** [comment]
In the meantime ESXi/vSphere 7 has been released, updating descriptions of this issue.

**Comment by billkindle** [comment]
This breaks other tools such as Telegraf too. Is this a problem with metricbeat or a VMware issue?

Pinging @elastic/integrations (Team:Integrations) @elastic/integrations-platforms (Team:Platforms)

**Comment by billkindle** [comment]
govmomi appears to have been updated / released around Jun 3: https://github.com/vmware/govmomi

**Comment by BrassPeddler** [comment]
+1

**Comment by linzwelch1** [comment]
+1 for vsphere 7.0.3
