### ISSUE TITLE
Content about loading beats dashboards should be in the guide for each beat

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#1943]
Right now, the Platform Ref provides content about loading the beats dashboards. In the getting started guide for each beat, we point to the Platform Ref for info about loading the dashboards. This is not an ideal getting started experience because we send users out to a different book, and they need to find their way back to the specific guide for the beat they are using. We don’t make it super easy for people to navigate between books!

Instead of making users jump back to the Platform Ref, we should use asciidoc includes to suck the shared content into the docs for each beat (like we do with other sections of the guides).

**Comment by chrisribe** [comment]
The guide is **very** confusing, I am just starting with topbeat (which is to be replaced by Metricbeat) and for the last hour have been looking how to load the sample dashboards !!! 

Is this it?
https://www.elastic.co/guide/en/beats/libbeat/1.2/load-kibana-dashboards.html

The original doc starts here:
https://www.elastic.co/guide/en/beats/topbeat/1.2/_step_5_loading_sample_kibana_dashboards.html
Then hints to here:
https://www.elastic.co/guide/en/beats/libbeat/1.2/visualizing-data.html
Then finaly here:
https://www.elastic.co/guide/en/beats/libbeat/1.2/load-kibana-dashboards.html

WHAT THE FRACK !
Chris

**Comment by dedemorton** [comment]
@chrisribe Thanks for your feedback. I agree that we need to improve the docs in this area (that's what prompted me to open this issue). As you've figured out, the content for loading the dashboards is documented in the Platform Reference because the content is relevant to all Beats. However, I'm planning to move this information to the guide for each Beat so that you won't have to jump back to the Platform Reference after you've gotten the Elastic Stack set up. Hopefully that will make the getting started process more straightforward. We're also making some improvements to the dashboard import process to give you more flexibility over loading the dashboards.

**Comment by dedemorton** [comment]
Note that we've also made an enhancement to the way the topics display in the right-hand navigation pane in the docs. The current topic is now highlighted in the TOC so that its relationships to other topics is more obvious.

**Comment by dedemorton** [comment]
Closing in favor of tracking this issue in https://github.com/elastic/beats/issues/2482
