### ISSUE TITLE
Fix inconsistency of GCP Filebeat/Metricbeat names

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#19467]
Currently we have several Filebeat inputs with inconsistent naming, such as `azureeventhub`, `googlepubsub` and `s3`. With the migration work to elastic-agent, this is a good opportunity for us to make changes on these names.

This issue is to start the discussion on if we should rename `s3` to `awss3`, or should we remove the public cloud names completely. 

TODO list:
| Description          	| Current Name           	| Proposed New Name  | PR | 
|----------------------	|----------------	|------------	|-----------	|
| Google Cloud Metricbeat module | googlecloud | gcp | https://github.com/elastic/beats/pull/22246 |
| Google Cloud Filebeat module | googlecloud | gcp | https://github.com/elastic/beats/pull/22214 |
| Google Cloud Filebeat Pub/Sub input 	| google-pubsub  	| gcp-pubsub 	| https://github.com/elastic/beats/pull/22213 |
| AWS S3               	| s3             	| aws-s3     	| Will be tracked with issue https://github.com/elastic/beats/issues/22799 |
| AWS CloudWatch Filebeat input | awscloudwatch | aws-cloudwatch | https://github.com/elastic/beats/pull/22228 |

**Comment by ycombinator** [comment]
Ah, naming :) 

My vote would be to include the cloud provider names (or abbreviations) in the input names, since the input implementations are specific to cloud providers. So I prefer `awss3`. But perhaps we could shorten/abbreviate the cloud provider names so maybe `google` becomes `gcp`.

**Comment by kaiyan-sheng** [comment]
Agree on changing `googlecloud` to `gcp` and also agree on changing `s3` to `awss3` 😄 @ycombinator Thank you for the input!!

**Comment by kaiyan-sheng** [comment]
We would like to rename `googlecloud` to `gcp` for both Metricbeat and Filebeat. @andrewkroh WDYT? I see in cloud ECS field, we are using `gcp` for cloud provider name instead of `googlecloud`.

**Comment by andrewkroh** [comment]
In Filebeat the input name for collecting data from Google Cloud's Pub/Sub service is called `google-pubsub`. The Filebeat module for Google Cloud is called `googlecloud`.

So is the proposal to change the input name, module, or both?

**Comment by andrewkroh** [comment]
I like the hyphenated input names for readability. If we want to shorten google to gcp then how about

| Description          	| Name           	| Proposal   	|
|----------------------	|----------------	|------------	|
| Azure Event Hub      	| azure-eventhub 	|        NO CHANGE    	|
| AWS S3               	| s3             	| aws-s3     	|
| Google Cloud Pub/Sub 	| google-pubsub  	| gcp-pubsub 	|

We should look across all the other input names too (this was just a quick look for me).

**Comment by kaiyan-sheng** [comment]
@andrewkroh Thank you! We are proposing to change both the Filebeat input name and Filebeat/Metricbeat module name.

**Comment by kaiyan-sheng** [comment]
Here is the proposal for both input names and module names.

Filebeat input name:
| Description          	| Name           	| Proposal  |
|----------------------	|----------------	|------------	|
| Azure Event Hub      	| azure-eventhub |  NO CHANGE |
| AWS S3               	| s3             	| aws-s3     	|
| Google Cloud Pub/Sub 	| google-pubsub  	| gcp-pubsub 	|

Filebeat module name:
| Description          	| Name           	| Proposal  |
|----------------------	|----------------	|------------	|
| AWS   | aws	| NO CHANGE |
| Azure  	| azure | NO CHANGE |
| Google Cloud Filebeat module | googlecloud | gcp |

Metricbeat module name:
| Description          	| Name           	| Proposal  |
|----------------------	|----------------	|------------	|
| AWS   | aws	| NO CHANGE |
| Azure  	| azure | NO CHANGE |
| Google Cloud Filebeat module | googlecloud | gcp |

**Comment by andrewkroh** [comment]
The above list SGTM.

When Filebeat modules are renamed aliases can be installed so that existing users are not broken by the change. See the apache module for an example.

**Comment by andrewkroh** [comment]
>Do you know if google pubsub Filebeat input is GA or Beta?

It must be GA since there are not beta labels at. https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-google-pubsub.html

**Comment by kaiyan-sheng** [comment]
> It must be GA since there are not beta labels at. https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-google-pubsub.html

Yeah good to know, thank you! I also didn't see `release: ga` under filebeat input 😬 That's why I want to confirm.

**Comment by kaiyan-sheng** [comment]
GCP part of the renaming is done, will close this issue.
