### ISSUE TITLE
Namespace labels to kubernetes metadata - ELasticsearch - Metricbeat

### ISSUE THREAD

**Issue by AMAbhi** [elastic/beats#19474]
Hi
I am working on an issue where i have assigned labels to my kubernetes namespace externally through kubectl command and wanted to get those kubernetes namespace labels in the metricbeat. I am following this https://github.com/elastic/beats/issues/14044.
I have seen that this feature is now added in the ES 7.x, but i am using ES 6.6. so is there any way to support this feature in ES 6.6 or modifying the code in my 6.6 forked branch to support this? Is there any possible solution available?

It would be great if you just give me an update or some guidance on this.

**Comment by andresrc** [comment]
Hi,

New features are not backported to the previous major, but 7.x should be able to write to ES 6.8.x? Could you give it try just upgrading metricbeat?

**Comment by AMAbhi** [comment]
> Hi,
> 
> New features are not backported to the previous major, but 7.x should be able to write to ES 6.8.x? Could you give it try just upgrading metricbeat?

Thank you for the response!
We are using ES 6.6 and we have no plan to upgrade the version. We want "get namespace label functionality" in 6.6 version. So is there any way to add features in 6.6 or any reference code files or is it possible to add this feature in 6.6?

**Comment by andresrc** [comment]
Hi,

We only backport needed bug fixes to the last minor of the previous major (6.8.x in this case) but not new features. You could try to backport the PR to your private 6.6 branch yourself, but I'm afraid we won't be able to provide support.

Thanks
