### ISSUE TITLE
Unable to generate custom beats depend on master branch

### ISSUE THREAD

**Issue by KEVISONG** [elastic/beats#19479]
For confirmed bugs, please report:
- Version: 7.X
- Operating System: macOS Catalina 10.15.3 
- Discuss Forum URL:
- Steps to Reproduce: 

Go Version: 1.13.10
OS: macOS Catalina 10.15.3

I followed the steps on https://www.elastic.co/guide/en/beats/devguide/current/newbeat-generate.html

when I run command `mage GenerateCustomBeat`

the following error occurs

`
Error: error while copying required files to vendor: error while looking up cached dir of module: github.com/elastic/beats/v7: expected 1 line, got 0 while looking for github.com/elastic/beats/v7
`

Is there any change on this? The complete output is shown below:

`
kevisong@KEVISONG-MB0 beats % sudo mage GenerateCustomBeat
Enter the beat name [examplebeat]: Countbeat
Enter your github name [your-github-name]: KEVISONG
Enter the beat path [github.com/KEVISONG/countbeat]: 
Enter your full name [Firstname Lastname]: KEVIN
Enter the beat type [beat]: 
Enter the github.com/elastic/beats revision [master]: 
go: creating new go.mod: module github.com/KEVISONG/countbeat
go: github.com/elastic/beats/v7 master => v7.0.0-alpha2.0.20200629050351-5426df01489e
go: gopkg.in/yaml.v2 upgrade => v2.3.0
go: github.com/pkg/errors upgrade => v0.9.1
go: golang.org/x/net upgrade => v0.0.0-20200625001655-4c5254603344
go: github.com/dlclark/regexp2 upgrade => v1.2.0
go: golang.org/x/sys upgrade => v0.0.0-20200625212154-ddb9806d33ae
go: golang.org/x/text upgrade => v0.3.3
go: go.uber.org/atomic upgrade => v1.6.0
go: golang.org/x/tools upgrade => v0.0.0-20200626171337-aa94e735be7f
go: github.com/elastic/go-windows upgrade => v1.0.1
go: go.uber.org/multierr upgrade => v1.5.0
go: honnef.co/go/tools upgrade => v0.0.1-2020.1.4
go: github.com/prometheus/procfs upgrade => v0.1.3
go: golang.org/x/crypto upgrade => v0.0.0-20200622213623-75b288015ac9
go: golang.org/x/lint upgrade => v0.0.0-20200302205851-738671d3881b
go: github.com/mitchellh/hashstructure upgrade => v1.0.0
go: go.uber.org/zap upgrade => v1.15.0
go: github.com/jstemmer/go-junit-report upgrade => v0.9.1
go: go.elastic.co/apm upgrade => v1.8.0
go: github.com/mattn/go-colorable upgrade => v0.1.7
go: github.com/elastic/go-ucfg upgrade => v0.8.3
go: github.com/elastic/go-sysinfo upgrade => v1.3.0
go: go.elastic.co/ecszap upgrade => v0.2.0
go: go.elastic.co/fastjson upgrade => v1.1.0
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: github.com/fatih/color upgrade => v1.9.0
go: github.com/rcrowley/go-metrics upgrade => v0.0.0-20200313005456-10cdbea86bc0
go: github.com/go-sourcemap/sourcemap upgrade => v2.1.3+incompatible
go: github.com/josephspurrier/goversioninfo upgrade => v0.0.0-20200309025242-14b0ab84c6ca
go: github.com/akavel/rsrc upgrade => v0.9.0
go: github.com/dop251/goja upgrade => v0.0.0-20200622111502-2faa37d3dedf
go: github.com/dop251/goja_nodejs upgrade => v0.0.0-20200626162143-3e6a054e8447
go: howett.net/plist upgrade => v0.0.0-20200419221736-3b63eb3a43b5
Error: error while copying required files to vendor: error while looking up cached dir of module: github.com/elastic/beats/v7: expected 1 line, got 0 while looking for github.com/elastic/beats/v7
`

**Comment by kvch** [comment]
@KEVISONG Could you please test again? There were several changes in Beat generators in the last few days.

**Comment by kvch** [comment]
This issue is for an old version of beats, I suggest to try out the latest version of beats. If this is still a problem in the newly released version feel free to reopen this issue. Thanks.
