### ISSUE TITLE
[Metricbeat] Postgresql user permission?

### ISSUE THREAD

**Issue by LucasVerneyDGE** [elastic/beats#19496]
Hi,

I cannot find any information about the minimum set of permission required for a dedicated user in Metricbeat postgresql module.

I came across https://discuss.elastic.co/t/postgres-privileges/144603/2 which was inviting to open a Github issue about this, but cannot find any related Github issue. So, here is one.

Thank you in advance!
Best,

**Comment by andresrc** [comment]
Thank you, closing as ducplicate of https://github.com/elastic/beats/issues/8033
