### ISSUE TITLE
[Elastic Agent] Support custom certificate authorities 

### ISSUE THREAD

**Issue by pebrc** [elastic/beats#19504]
Consider: Agent runs in managed mode and the Kibana instance it is connecting to is configured with a custom certificate authority that is not globally trusted in order to connect to Elasticsearch. 

IIUC the agent config that is shipped to the Agent from Kibana does not include that custom certificate authority setup and the certificate authority certs are also not shipped as assets to the agent. I believe the programs relying on the output configuration will in that case just fail to connect to Elasticsearch. 

In order to make it work any referenced assets from the configuration would need to be shipped to the agent as well.

For example [ECK](https://github.com/elastic/cloud-on-k8s) uses custom certificate authorities for Elasticsearch and Kibana to run with a secure configuration by default if a user has not yet set up their own certificates.

**Comment by scunningham** [comment]
Delivering a custom CA Cert(s) per ES output would work.  

If a CA is provided, should the agent (beat) only trust connections where the peer is signed with this cert, or should it also trust installed CA's in addition to the configured cert.  I would say the former; fallback to installed CA's would not be expected by the customer.

I would imagine this would require support in each of the beats and the elastic security agent;  to my knowledge each are talking directly to elastic search and not routing through the agent.

**Comment by ph** [comment]
@scunningham we could deliver the CA (embedded) in the configuration so that would require minimal changes into the beats?

**Comment by scunningham** [comment]
I figured it would come through the configuration.  That makes it very flexible.  Would need some UX treatment.

**Comment by blakerouse** [comment]
I agree, being that we are already sending the password to Elastic Agent in the configuration, no reason to do anything different for a CA.

I think the issue at the moment is that the CA settings in filebeat and metricbeat only accept a filepath to a CA and not the data directly. That would need to be added to libbeat `tlscommon.Config` to accept the CA data, instead of just a filepath.
