### ISSUE TITLE
Filebeat inputs types: docker vs container

### ISSUE THREAD

**Issue by dudicoco** [elastic/beats#19523]
Hi,

The official docs describe both the docker input type and the container input type, but does not describe the difference between them and which use cases each one fits.

Can someone please explain the difference between these inputs? Should this be added to the docs?

Thanks

**Comment by exekias** [comment]
Hi @dudicoco, these two inputs are very similar, but `docker` is only minded for Docker logs, while `container` is more generic, it doesn't make assumptions on the logs paths.

`docker` input is deprecated and will be removed in 8.0, we recommend using `container` instead
