### ISSUE TITLE
[Elastic Agent] when Agent is stopped, Metricbeat & Filebeat are not stopped

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#19522]
[Elastic Agent] when Agent is stopped, Metricbeat & Filebeat are not stopped
 - docker container environment from https://github.com/elastic/e2e-testing/

@mdelapenya found this while helping Agent team write a smoke test.  Testing on latest 8.0 containers (the Agent container is custom created, so it can be tested more thoroughly)
 
Please include configurations and logs if available.

For confirmed bugs, please report:
load up Agent and deploy to fleet.
when you stop agent process, the 2 beat processes are still running.

See his Centos7 logs info:
 e2e-testing git:(148-fleet-scenarios) $> docker exec ingest-manager_elastic-agent_1 ps
  PID TTY          TIME CMD
    1 ?        00:00:00 tail
  105 ?        00:00:05 elastic-agent
  119 ?        00:00:00 metricbeat
  151 ?        00:00:00 filebeat
  163 ?        00:00:00 metricbeat
  185 ?        00:00:00 ps
➜  e2e-testing git:(148-fleet-scenarios) $> docker exec ingest-manager_elastic-agent_1 kill 105
➜  e2e-testing git:(148-fleet-scenarios) $> docker exec ingest-manager_elastic-agent_1 ps      
  PID TTY          TIME CMD
    1 ?        00:00:00 tail
  119 ?        00:00:00 metricbeat
  151 ?        00:00:00 filebeat
  163 ?        00:00:00 metricbeat
  196 ?        00:00:00 ps
➜  e2e-testing git:(148-fleet-scenarios) $> docker exec ingest-manager_elastic-agent_1 ps
  PID TTY          TIME CMD
    1 ?        00:00:00 tail
  119 ?        00:00:00 metricbeat
  151 ?        00:00:00 filebeat
  163 ?        00:00:00 metricbeat
  201 ?        00:00:00 ps
➜  e2e-testing git:(148-fleet-scenarios) $> docker exec ingest-manager_elastic-agent_1 ps
  PID TTY          TIME CMD
    1 ?        00:00:00 tail
  119 ?        00:00:00 metricbeat
  151 ?        00:00:00 filebeat
  163 ?        00:00:00 metricbeat
  206 ?        00:00:00 ps
After manually killing the process, it does not stop metricbeat and filebeat

**Comment by mdelapenya** [comment]
Adding context: the runtime docker image is Centos:7, where I installed the Agent following the guide: https://www.elastic.co/guide/en/ingest-management/7.8/elastic-agent-installation.html

```shell
$ curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.8.0-linux-x86_64.tar.gz
$ tar xzvf elastic-agent-7.8.0-linux-x86_64.tar.gz
# add agent to PATH
$ ln -s /elastic-agent-7.8.0-linux-x86_64.tar.gz /usr/local/bin/elastic-agent
$ elastic-agent enroll http://kibana:5601 $token -f
$ elastic-agent run
```

**Comment by mdelapenya** [comment]
More on this: when running `elastic-agent` on Centos, I got this process list:

```shell
[root@e0b3382bbe0f /]# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4412   676 ?        Ss   18:52   0:00 tail -f /dev/null
root        38  3.3  0.2 850328 23560 ?        Ssl  18:52   0:05 elastic-agent run
root        56  0.4  0.7 429032 64320 ?        Sl   18:52   0:00 /elastic-agent-8.0.0-SNAPSHOT-linux-x86_64/data/install/filebeat-8.0.0-SNAPSHOT-linux-x86_64/filebeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.mode=x-pack-fleet -E management.enabled=true -E logging.level=debug -E logging.
root        69  0.6  1.0 676580 85808 ?        Sl   18:52   0:01 /elastic-agent-8.0.0-SNAPSHOT-linux-x86_64/data/install/metricbeat-8.0.0-SNAPSHOT-linux-x86_64/metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.mode=x-pack-fleet -E management.enabled=true -E logging.level=debug -E logg
root        81  1.8  0.7 707568 65012 ?        Sl   18:52   0:03 /elastic-agent-8.0.0-SNAPSHOT-linux-x86_64/data/install/filebeat-8.0.0-SNAPSHOT-linux-x86_64/filebeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.mode=x-pack-fleet -E management.enabled=true -E logging.level=debug -E logging.
root        93  0.4  0.9 471776 81060 ?        Sl   18:52   0:00 /elastic-agent-8.0.0-SNAPSHOT-linux-x86_64/data/install/metricbeat-8.0.0-SNAPSHOT-linux-x86_64/metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.mode=x-pack-fleet -E management.enabled=true -E logging.level=debug -E logg
root       157  0.0  0.0  11840  3116 pts/0    Ss   18:52   0:00 bash
root       338  0.0  0.0  51768  3440 pts/0    R+   18:55   0:00 ps aux
```

**Comment by rahulgupta-qasource** [comment]
### Bug Conversion:
Created **01** new Test-Case for this Ticket 
- https://elastic.testrail.io/index.php?/cases/view/27067
