### ISSUE TITLE
[Packetbeat] Visualizations of the NFS ECS dashboard use a wrong filter

### ISSUE THREAD

**Issue by fdartayre** [elastic/beats#19547]
Visualizations of the [Packetbeat-nfs](https://github.com/elastic/beats/blob/master/packetbeat/_meta/kibana/7/dashboard/Packetbeat-nfs.json#L850) dashboard use a match value `nfs-ecs` for `event.dataset` when it should be `nfs`:
```json
"query": {
  "match": {
    "event.dataset": {
      "query": "nfs-ecs",
      "type": "phrase"
    }
  }
}
```
The value of `event.dataset` is set to `nfs` in [request_handler.go](https://github.com/elastic/beats/blob/master/packetbeat/protos/nfs/request_handler.go#L84):
```java
pbf.Event.Dataset = "nfs"
```
As a result the dashboard comes empty. This discrepancy seems to have been introduced by https://github.com/elastic/beats/pull/9998 so it's there since the very beginning of 7.0.0.

**Comment by Dave-c-Ross** [comment]
Any update or work around ?
