### ISSUE TITLE
[packetbeat] Do not limit `url.full` in packetbeat index

### ISSUE THREAD

**Issue by nkakouros** [elastic/beats#19554]
**Describe the enhancement:**
Packetbeat's index template defines the mapping for the `url.full` field as:

```
          "full": {
            "ignore_above": 1024,
            "type": "keyword",
            "fields": {
              "text": {
                "norms": false,
                "type": "text"
              }
            }
          }
        }
```

It would be nice to not have a limit of only 1024.

**Describe a specific use case for the enhancement or feature:**
I want to be able to track attacks on my website. One of the attacks that people (or bots) try is SQL injection with automated tools such as sqlmap. This tool can generate long queries that exceed 1024 characters. My tools that ask elasticsearch about sql injections fail to match these attacks because of the limitation.

Also, since it is the full url, what is the reason to limit it? It should be able to handle the length of the full url.

**Comment by andrewkroh** [comment]
This part of the template is being inherited from [ECS](https://github.com/elastic/ecs/blob/050a4256f763d77de283fb2ac396713515173c95/schemas/url.yml#L29). We would probably want to make the change there rather than override the 1024. It probably does make sense to increase the limit a bit.

This seems to be a useful resource on the subject of lenghts https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers#417184.

cc: @elastic/ecs

**Comment by webmat** [comment]
I think it's fine if this gets bumped up. I don't think this will create problems.

Note however that this field is a top candidate to being moved to `wildcard` which will not have a length limitation. So no active work is happening right now in reviewing these limits.

**Comment by nkakouros** [comment]
According to the [source code](https://github.com/elastic/beats/blob/23e4403ae093fcc8f7905345cad2c7ad256976d8/libbeat/_meta/fields.ecs.yml#L5782), this is still limited to 1024. Is the move to `wildcard` still planned?

**Comment by ebeahan** [comment]
`url.full` is now using the `wildcard` field type [in ECS](https://www.elastic.co/guide/en/ecs/current/ecs-url.html#field-url-full), and `url.full` doesn't have `ignore_above: 1024` configured in its mapping:

```json
{
  ".ds-packetbeat-8.1.2-2022.03.29-000001" : {
    "mappings" : {
      "url.full" : {
        "full_name" : "url.full",
        "mapping" : {
          "full" : {
            "type" : "wildcard",
            "fields" : {
              "text" : {
                "type" : "match_only_text"
              }
            }
          }
        }
      }
    }
  }
}
```
