### ISSUE TITLE
[Elastic-agent]: Getting issue with "elast-agent.reference.yml" file while performing Standalone (Manual Configuration) for agent 8.0 on 8.0 cloud environment

### ISSUE THREAD

**Issue by ghost** [elastic/beats#19550]
**Kibana version:**
Kibana: 8.0

**Elasticsearch version:**
Elasticsearch: 8.0

**Agent version:**
Agent: 8.0 

**Browser version:**
Windows 10, Chrome

**Original install method (e.g. download page, yum, from source, etc.):**
From download page.

**Description**
[Elastic-agent]: Getting issue with "elast-agent.reference.yml" file while performing Standalone (Manual Configuration) for agent 8.0 on 8.0 cloud environment

**Preconditions**
1.Kibana 8.0 cloud environment should be available.

**Steps to Reproduce**
1. Open the Kibana 8.0 cloud environment in browser, then click Ingest Manager>Configuration tab.
2. Navigate to default configuration page and then click on "Action" link and select "Copy Config" option.
3. Paste the same in Agent 8.0>elastic-agent.reference.yml file.
4. Then added username and password (for elasticsearch) under "Output" section inside yml file and save it.
5. Now open the power shell window and move to the location of agent.
6. Run the "elastic-agent.reference.yml" file with command: ./elastic-agent -c elastic-agent.reference.yml run
5. Observe that error "did not find "-" expected indicator appears on running the above command.

**Test data**
Followed steps given for "Standalone Manual Configuration" inside the "Ingest Management Guide for [8.0]".

**Impacted Test case id**
N/A 

**Actual Result**
[Elastic-agent]: Did not find expected "-" indicator error appears while running the "elast-agent.reference.yml" config file for performing Standalone (Manual Configuration) for agent 8.0 on 8.0 cloud environment

**Expected Result**
[Elastic-agent]: No error should come while performing Standalone (Manual Configuration) for agent 8.0 on 8.0 cloud environment

**What's working**
N/A

**What's not working**
N/A

**Screenshot**
![errorstandalonequery](https://user-images.githubusercontent.com/61860613/86249706-45164a80-bbcd-11ea-958d-a6d6c7112f01.png)

**Logs**
N/A

**Comment by kamalpreetpahwa-qasource** [comment]
@manishgupta-qasource : Review and assigned the issue

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by ph** [comment]
moved to @michalpristas

**Comment by michalpristas** [comment]
oh i see it now, problem is with indentation of username and password. it is subkey of hosts where hosts is expected to be a list of strings and credentials should be coupled with output. 
@kamalpreetpahwa-qasource if you could place credential information at the same level as hosts key and verify (it worked for me). i think then we can close this issue

**Comment by kamalpreetpahwa-qasource** [comment]
Hi @michalpristas 

Thanks for looking into the issue and providing your inputs  on the same.

We checked the issue after updating the "elastic-agent.reference.yml" file with correct indentation for "username and password" information and observed that issue is resolved.

Environment Details:

```
Kibana 8.0
Agent 8.0.0 snapshot
Windows 10

```

Now we are able to successfully configure  the stand alone agent and data is streaming under Data stream tab.

Screenshot:
![indentation](https://user-images.githubusercontent.com/61860613/86451178-27b1bf80-bd38-11ea-8aba-fb602985172b.png)

Hence, we are closing this issue.

Thanks

**Comment by EricDavisX** [comment]
@kamalpreetpahwa-qasource hi - are the docs for this wrong somewhere?  We can leave it open for the Docs to be updated as needed.  Thanks!  Please confirm with screenshots and we can re-close it if its fixed in the main docs.  :)

**Comment by michalpristas** [comment]
went through configuration files and I dont see wrong intentation anywhere. can we close this @EricDavisX

**Comment by EricDavisX** [comment]
yes, closing it out - thanks Michal
