### ISSUE TITLE
Improve how-to topics

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#19578]
**Describe the enhancement:**

In 7.9, we moved content that was previously in the getting started guides into the "how-to" section of the docs. These topics contained varying levels of detail and incomplete coverage of the subject they discuss. As a next step, we need to improve the quality and coverage of those topics so that they are organized logically and adequately cover the topic.

Here's a preliminary list:

    * Manage indices (also look for open issues related to index templates, patterns, and so on)
      * Load the Elasticsearch index template
      * Change the index name - add coverage of ILM
      * Lifecycle management?
    * Parse and enrich data
      * Enrich events with geoIP information
      * Deduplicate data
      * Parse data by using ingest node - add info about UI for building ingest pipeline

**Comment by jlind23** [comment]
@dedemorton is it still relevant?
