### ISSUE TITLE
Winlogbeat - parse and index raw XML representation of Windows events

### ISSUE THREAD

**Issue by eddieturizo** [elastic/beats#19576]
**Describe the enhancement:**
Parse the raw XML representation of Windows events when using `event_logs.include_xml` in Winlogbeat. 

**Describe a specific use case for the enhancement or feature:**

Instead of having to use Logstash filter plugins to parse and index the raw XML fields generated after setting `event_logs.include_xml`, it would be useful if Winglogbeat did this natively.

**Comment by jamiehynds** [comment]
Closing this out as we recently implemented the decode_xml processor for Windows events via https://github.com/elastic/beats/issues/23910
