### ISSUE TITLE
Oracle tablespace metricset for storage space care about correct autoextensible and temp tablespace

### ISSUE THREAD

**Issue by 111andre111** [elastic/beats#19612]
**Describe the enhancement:**
At the moment fields `space.free.bytes, space.total.bytes, space.used.bytes` don't care about autoextensible table space and there this information is missing or leads to potential wrong result at the moment.
Additionally especially for TEMP tablespace it seems we need some better special handling and want to shout out to the community, how to do that better.
https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-oracle-tablespace.html

**Describe a specific use case for the enhancement or feature:**
Our approach is to discuss this topic to be as near as possibly to the Oracle best practice.

At the moment the select statement that we have in place are somewhere here
https://github.com/elastic/beats/blob/v7.8.0/x-pack/metricbeat/module/oracle/tablespace/data.go#L82
https://github.com/elastic/beats/blob/v7.8.0/x-pack/metricbeat/module/oracle/tablespace/data.go#L102

But that's just like what happens today, but we want to discuss more or less free from today's approach, but more how it should be done if that makes sense.

Now the oracle documentation pages don't seem to be 100% clear about every single field and how they relate together.
Let me still add the configuration pages that I found during my investigation regarding the used tables and views:
  DBA_FREE_SPACE
  https://docs.oracle.com/database/121/REFRN/GUID-0FFCB990-4013-4D8A-A2FC-CF4B38DB7CC8.htm#REFRN23076
  DBA_TEMP_FREE_SPACE
  https://docs.oracle.com/database/121/REFRN/GUID-61C81A2C-C8D6-4B79-ABA3-296489CBB17A.htm#REFRN23627
  DBA_DATA_FILES
  https://docs.oracle.com/database/121/REFRN/GUID-0FA17297-73ED-4B5D-B511-103993C003D3.htm#REFRN23049
  USER_FREE_SPACE
  https://docs.oracle.com/database/121/REFRN/GUID-41F293A6-4698-4CA6-BDF1-346D53539590.htm#REFRN26076
  DBA_SEGMENTS
  https://docs.oracle.com/database/121/REFRN/GUID-7BF4F8C7-1917-4532-B048-C044E17A1754.htm

So what we request for is maybe having better documentation pages on Oracle side plus what is the exact best practice of obtaining the correct result for tablespace disk space used, total and free?

**Comment by 111andre111** [comment]
Maybe a partial topic of https://github.com/elastic/beats/issues/18295

**Comment by 111andre111** [comment]
https://github.com/elastic/beats/pull/19620

**Comment by andresrc** [comment]
@masci @sorantis should this one be open?

**Comment by sorantis** [comment]
yes, let's keep it open
