### ISSUE TITLE
[Elastic-Agent] Allow to specify what artifacts to embed at build times

### ISSUE THREAD

**Issue by ph** [elastic/beats#19623]
We need to embed signatures files at build times to allow us to verify the artifacts in the work in  #19222. The Elastic Agent is built by the release manager which also builds all the other artifacts. 

We need to change the order of operation.

- build filebeat/create signature.
- build metricbeat/create signature file
- build endpoint/create signature file.
- build Elastic-Agent with the right "archives" and the right signature files.

To do this we could have at parameters at build times to specify what needs to be embedded.

**Comment by Conky5** [comment]
To be clear the order of operations today looks like:
1. All beats projects are built
1. release-manager generates signature files
1. downstream codesigning jobs are run
1. release-manager re-generates signature files for codesigned artifacts

What I think we'll want it to look like:
1. All beats projects minus `elastic-agent` are built
1. release-manager generates signature files
1. downstream codesigning jobs are run
1. release-manager re-generates signature files for codesigned artifacts
1. The `elastic-agent` build runs, which is passed the fully signed artifacts and signature files by release-manager, which are then bundled into the `elastic-agent` distribution
1. release-manager generates a signature file for the `elastic-agent` archives

**Comment by michalpristas** [comment]
this one's already in place, closing
