### ISSUE TITLE
[Elastic Agent] Ensure that agent data and config is only accessible by user/group not world

### ISSUE THREAD

**Issue by blakerouse** [elastic/beats#19624]
Elastic Agent needs to ensure that it created all agent configurations and data are accessible by the executing user and are not world readable.

Sensitive information is present in those files and Elastic Agent need to ensure that they stay un-readable unless the user has the correct permissions to read those files.

Elastic Agent should on startup re-permission files if they are not correct, to ensure that a user mistake is auto corrected by Elastic Agent.

**Comment by michalpristas** [comment]
Let's use current user instead of root. Running as root is not a prerequisite, i think this changes with endpoint in that case we need to add a check to make sure we're running elevated
