### ISSUE TITLE
[metricbeat] node_stats > jvm.gc.collectors > old gc stats looks incorrect, it's the same as young gc

### ISSUE THREAD

**Issue by hubbleview** [elastic/beats#19636]
- Version: 6.8, 7.7, 7.8.0
- Operating System: Linux, MacOS
- Steps to Reproduce: 

1. Follow [this guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-metricbeat.html) to enable elasticsearch monitoring by metricbeat. 

2. Check the node_stats data for jvm.gc.collectors using following API:
```
GET .monitoring-es-7-mb*/_search
{
  "size": 20,
  "sort": [
    {
      "timestamp": {
        "order": "desc"
      }
    }
  ], 
  "_source": "node_stats.jvm.gc.collectors", 
  "query": {
    "term": {
      "type": {
        "value": "node_stats"
      }
    }
  }
}
```

The young gc and old gc have the same stats, which is not correct and different from output of `GET _nodes/stats?filter_path=**.jvm.gc.collectors`. 

The output of querying `.monitoring-es-7-mb-*`:
```
          "node_stats" : {
            "jvm" : {
              "gc" : {
                "collectors" : {
                  "young" : {
                    "collection_count" : 17,
                    "collection_time_in_millis" : 795
                  },
                  "old" : {
                    "collection_count" : 17,
                    "collection_time_in_millis" : 795
                  }
```

The `_nodes/stats` output:

```
        "gc" : {
          "collectors" : {
            "young" : {
              "collection_count" : 18,
              "collection_time_in_millis" : 820
            },
            "old" : {
              "collection_count" : 0,
              "collection_time_in_millis" : 0
            }
          }
        },
```

I tested 6.8, 7.7 and 7.8, all the same symptom. Looks like a bug here.

**Comment by ravikesarwani** [comment]
@andresrc Is there someone from the beats team that can help with the investigation?

**Comment by andresrc** [comment]
We missed this one, I'll add it to the triage.

**Comment by milanage** [comment]
@sayden 

The issue seems to be reproducible on 7.9.3 as well. Any chance to move this forward?
```
              "gc" : {
                "collectors" : {
                  "old" : {
                    "collection_count" : 280,
                    "collection_time_in_millis" : 6404
                  },
                  "young" : {
                    "collection_count" : 280,
                    "collection_time_in_millis" : 6404
                  }
                }
              }
```


@elastic/integrations-services

**Comment by masci** [comment]
We've a bug here https://github.com/elastic/beats/blob/7.x/metricbeat/module/elasticsearch/node_stats/data_xpack.go#L137-L140 where we pick the `young` key from the dict and store it in the `old` field. Let me discuss this offline, I'll come back with a plan to roll out a fix.

**Comment by sayden** [comment]
PR opened for `7.x` already https://github.com/elastic/beats/pull/26616
