### ISSUE TITLE
[Filebeat] Using the System module while running Filebeat in docker

### ISSUE THREAD

**Issue by miande-acxiom** [elastic/beats#19631]
I noticed that when running Filebeat as a docker container configured to use the System module AND the processor "add_process_metadata" the system & process details of the syslog/audit/etc. are not being captured.  Because the Metricbeat configuration has the --system.hostfs to mount the /proc necessary to get the metadata, Metricbeat can capture the details; however, because Filebeat doesn't have a configuration that is similar then Filebeat can't get metadata about the syslog/audit/etc. that is running on the host.  Is there a work around for this?

**Comment by jsoriano** [comment]
You are right, it would make sense to add `--system.hostfs` to all beats that can use `add_host_metadata`.

**Comment by miande-acxiom** [comment]
What's the next step for turning this into an enhancement request?

**Comment by victorpintot8** [comment]
Hi, same issue here. I want to collect host system logs using the Filebeat docker image but can't. This is the run command I'm using: `docker run \
--restart always \
-dti \
--name=filebeat \
--user root \
--volume="$(pwd)/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro" \
--volume="/var/lib/docker/containers:/var/lib/docker/containers:ro" \
--volume="/var/run/docker.sock:/var/run/docker.sock:ro" \
--volume="/proc:/hostfs/proc:ro" \
--volume="/var/log:/var/log:ro" \
docker.elastic.co/beats/filebeat:7.10.1 filebeat -e -strict.perms=false \
-E cloud.id= \
-E cloud.auth=
`

**Comment by PrplHaz4** [comment]
this is still an issue
