### ISSUE TITLE
Add SCRAM authentication to kafka metrics source

### ISSUE THREAD

**Issue by l0x-c0d3z** [elastic/beats#19648]
**Describe the enhancement:**

Allow the kafka metricbeat module to specify an authentication mechanism.

This is related to elastic/beats#16723

We probably want to move some of the code from elastic/beats#12867 to a common directory to avoid code dupplication.

**Describe a specific use case for the enhancement or feature:**

We're running a kafka cluster with SCRAM-SHA-256 authentication. We would like to be able to pull metrics.

**Comment by gjelenc** [comment]
Is there some ETA for release of this feature ?
