### ISSUE TITLE
New protocol support: Ceph API & OSD

### ISSUE THREAD

**Issue by portante** [elastic/beats#197]
Place holder for now, but to start would like to see metrics on:
- top operations
- top clients
- error rates
- data rates

Looking to do the contributions myself if somebody does not get to it first.

**Comment by amandahla** [comment]
I'm working on a module for MetricBeat here:
https://github.com/amandahla/beats/tree/master/metricbeat/module/ceph

I do accept suggestions and help. :-)

I'm using Telegraf as reference:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/ceph/ceph.go

**Comment by monicasarbu** [comment]
@amandahla I am happy to see your contribution to Metricbeat. I think the best would be to open a PR with the `ceph` module, so we can easily add suggestions there.

**Comment by amandahla** [comment]
Thank you @monicasarbu !I'm still working but I opened a PR now.
