### ISSUE TITLE
Increase Agent install timeout for macOS Endpoint to 10 minutes

### ISSUE THREAD

**Issue by ferullo** [elastic/beats#19700]
Agent should increase how long it allows the Endpoint installer/uninstaller to run to 10 minutes. Loading and unloading a kernel extension on macOS can randomly take a very long time. Endpoint cannot shorten this delay imposed by macOS.

We've found through experience that often under 30 seconds works and usually under 4 minutes works. We've never seen it take longer than 10 minutes to load or unload a kernel extension though, which is why we use that very long timeout.

**Comment by blakerouse** [comment]
Currently it is set to 120 seconds, will increase to 10 minutes.

Being that uninstall unloads the extensions, I assume that should also be set to 10 minutes?

**Comment by ferullo** [comment]
Yes please set that to 10 minutes too.
