### ISSUE TITLE
./filebeat generate fields with pipeline.yml

### ISSUE THREAD

**Issue by Bernhard-Fluehmann** [elastic/beats#19712]
Hey, stop right there!

Hi, I have opened a [discussion](https://discuss.elastic.co/t/filebeat-generate-fields-with-pipeline-yml/239790) and was told to open an issue for this topic.

**This is the text of the original request:**
I am developing a new filebeat module for sophos firewall logs. Now I got stuck on
the ./filebeat generate fields command. It returns with the following error:

cannot read pipeline: open module/sophos/secureweb/ingest/pipeline.json: no such file or directory

This makes sense since my pipeline is called pipeline.yml. It is configured like this in the manifest file of the fileset. I have though already to convert the file back to json but since almost all pipelines of the existing modules are in yml I wonder what I am doing wrong.

It was mentioned that the field creation script only supports json pipelines. and I should request adding yml support.

One other strange thing I observed when I was testing the script with a json pipeline was that it seems just to create fields parsed with grok. All other fields created with set and rename processors, were ignored.
Given that observation and the fact that almost all module pipelines are yml files let me wonder if the script is still needed at all or if there are other tools or manual processes in use to create fields.

And as a last question, let me ask the best practice to create pipelines. The manual proposes to use devtools (json pipeline) with simulate api. This is what I am doing so far. But this means at all module pipelines are in yml, the developed pipelines need to be converted somehow to yml. Is there a way to simulate yml pipelines directly, either by elasticsearch accepting yml pipelienes or with a simulate script in filebeat?

I am looking forward for your answers, since I have a couple of use cases to process new log types

Regards
Bernhard

**Comment by hazcod** [comment]
I have the exact same issue @Bernhard-Fluehmann

**Comment by jlind23** [comment]
Closing it for now until further activity.
