### ISSUE TITLE
[CI] Build all stages on a branch merge

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/beats#19752]
The idea is to test everything on merges to the main branches (master,7.*) this will catch errors that PRs did not catch.

```
  Scenario: A developer creates a new PR
    When the PR is merged in the target branch
    Then all pipeline stages are executed
```

cc @elastic/observablt-robots

**Comment by cachedout** [comment]
Hmm. I wonder if we could look up the PR that triggered the job to run and then automatically comment on the PR if it fails? (Obviously the PR would be closed at that point, but the author should still get notified.)

**Comment by kuisathaverat** [comment]
>Hmm. I wonder if we could look up the PR that triggered the job to run and then automatically comment on the PR if it fails?

yes, we can, you have the SHA of the merge commit and that commit has the PR number, probably you can search also the PR by the SHA.
