### ISSUE TITLE
Common Fields for Host Inventory Schema

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#19757]
This issue is to track the work for adding common fields among different host metrics. These proposed common fields (eventually) will become required fields to collect when adding support for new host type.

Proposed Common Fields:

- host.id
- host.name
- host.cpu.pct
- host.network.in.bytes
- host.network.in.packets
- host.network.out.bytes
- host.network.out.packets
- host.disk.read.bytes
- host.disk.write.bytes

TODO:
For each Metricbeat module listed below, we need to investigate if all proposed common fields are collected. If they are, we should duplicate these fields and change to use the names from above. If there are missing fields, we need to add them in the module first.

| module | assign to | github issue | PR |
| -|-|-|-|
| system | @exekias | | https://github.com/elastic/beats/pull/20415 |
| aws | @kaiyan-sheng  | | https://github.com/elastic/beats/pull/20171 |
| gcp | @kaiyan-sheng  | | https://github.com/elastic/beats/pull/20391 |
| azure | @narph  | | https://github.com/elastic/beats/pull/20641 |
| vsphere | @jsoriano | https://github.com/elastic/beats/issues/20313 |  |
| kvm | @jsoriano | https://github.com/elastic/beats/issues/18513 |  |

cc: @exekias @sorantis

**Comment by kaiyan-sheng** [comment]
AWS: we are not collecting `cloud.instance.name` for EC2 instance. https://github.com/elastic/beats/pull/20077 is to add this field.

**Comment by jsoriano** [comment]
For vsphere metrics we are going to need add support to collect performance metrics. I have collected [a list of metrics](https://gist.github.com/jsoriano/c759597aebd0ebba6ecb9ad0ec995336) that we can collect using a variation of [this example code](https://github.com/vmware/govmomi/blob/master/performance/example_test.go).

**Comment by webmat** [comment]
See also Stage 1 RFC PR https://github.com/elastic/ecs/pull/950
