### ISSUE TITLE
[Ingest Manager][Security-app] Agent fails to download the Endpoint (tested on macOS + Linux x64)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#19760]
[Ingest Manager][Security-app] Agent fails to download the Endpoint (tested on macOS + Linux x64)

Testing with latest snapshot of ELK on cloud-staging as of this morning, July 8.

7.9 linux agent:
https://snapshots.elastic.co/7.9.0-0c81f8ea/downloads/beats/elastic-agent/elastic-agent-7.9.0-SNAPSHOT-linux-x86_64.tar.gz
 - current as of last night too.

CentOS7 and High Sierra tested against with Agent:

For confirmed bugs, please report:
- Steps to Reproduce: 
to see this:
deploy cloud
enable fleet
install agent to centos or macOS with default config
then enable endpoint in the default config
 - there is a bug being worked that happens AFTER this, but I am not seeing the download of the Endpoint locally to the host data/downloads folder

I know Blake had confirmed Windows seemed to work and was going to test on Linux.  perhaps its a windows vs non-windows type problem?

screenshot from my centos box.  i can provide more support but didn't want to wait to put the ticket in
<img width="1393" alt="Screen Shot 2020-07-08 at 5 42 09 PM" src="https://user-images.githubusercontent.com/12970373/86973478-a183e780-c142-11ea-86d3-26610b680b1d.png">

**Comment by EricDavisX** [comment]
here are screenshots from UI, nothing looks bad in Agent details, and it shows it is with a config that has Endpoint.

<img width="1447" alt="Screen Shot 2020-07-08 at 5 47 42 PM" src="https://user-images.githubusercontent.com/12970373/86973984-7e0d6c80-c143-11ea-9e50-62c5f1f0cdfc.png">
<img width="1209" alt="Screen Shot 2020-07-08 at 5 47 30 PM" src="https://user-images.githubusercontent.com/12970373/86973985-7e0d6c80-c143-11ea-9353-06cb541d259d.png">

in the logs all looks pretty well to me...

[download-Endpoint-log.txt](https://github.com/elastic/beats/files/4893426/download-Endpoint-log.txt)

**Comment by EricDavisX** [comment]
chris owens says his 8.0 (version / date tbd) Agent worked on Centos7 to download the Endpoint - so perhaps its on its way to being fixed.  still unsure, i can re-test with latest 8.0 and 7.9 and various os versions.

**Comment by EricDavisX** [comment]
I tested again with this version of 8.0 linux x64 Agent:
https://snapshots.elastic.co/8.0.0-08649193/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz
 - from today, July 8 around 5 PM compile time it seems.

I am using this commit for ELK stack / Kibana cloud deploy:
edavis-mbp:kibana edavis$ git show -s 50a29913
commit 50a2991312ad05a5ce78d988bdce35d27f0cb9fe
Author: Jean-Louis Leysens <jloleysens@gmail.com>
Date:   Tue Jul 7 19:22:58 2020 +0200

@crowens can you paste the versions of kibana (commit / timestamp) and of Agent so we can cross compare?  Maybe yours is older and working and a bug has since been introduced?

**Comment by crowens** [comment]
I used the https://snapshots.elastic.co/8.0.0-08649193/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz on mac just now and the Endpoint downloaded and installed.  I used it on linux too, it also downloaded and installed.

**Comment by crowens** [comment]
I have not been able to reproduce this problem on mac or linux.

**Comment by EricDavisX** [comment]
I wonder whats different in the environments or what I may be doing differently!  I tried starting with Endpoint in the deployed Agent config, vs starting without it on default and then switching to it. I'll keep thinking on it, but I'm super glad that others are seeing this work.

**Comment by ph** [comment]
@EricDavisX I was able to make it work with the latest snapshot.

on Linux, windows, I haven't tested yet on mac.

@EricDavisX if you have this probleme maybe we could screenshare with @blakerouse ?

**Comment by blakerouse** [comment]
I am also not able to reproduce this. I have had it work on both Windows and Linux.

Please attach the full agent log.

**Comment by ph** [comment]
Is that the same bug as identified by @crowens, can you check _action_store.yml_ content and "View Config" in the UI?

**Comment by EricDavisX** [comment]
it looks fixed to me, as tested on the same environment - unsure what the cause was, but it was a hectic week with snapshots broken etc.  i'm going to close this to clear noise.

fix-confirmed in 7.9 latest snapshot available as of 7/15 am

**Comment by rahulgupta-qasource** [comment]
**Bug Conversion:**

Test-Case already exists for this ticket:

https://elastic.testrail.io/index.php?/cases/view/15872
