### ISSUE TITLE
[Metricbeat] docker diskio module double counts numbers

### ISSUE THREAD

**Issue by henrikno** [elastic/beats#19766]
**Describe the enhancement:**
Currently metricbeat diskio module double (or triple) counts number of bytes read/written on systems with e.g. md-raid or LVM.
This is because it's taking the sum of all the counters of all the disk devices, but devices such as `md0`, `dm-0`, etc are already summing up the counters of their sub-devices.

System diskio module reports the stats per disk, so it does not have this issue.

Comparison of disk throughput from system module vs docker module:
![image](https://user-images.githubusercontent.com/147660/86996003-54623e80-c15f-11ea-9047-af277bb03533.png)

Docker module claims this container is using 17.4GB/s, which is not possible on this system. The system module says each disk is doing ~350MB/s (8 SSDs), which matches the `dm-1` speed of around 2.7GB/s. I'm not sure why `md0` speed is showing around ~3.9GB/s, but those all correspond with e.g. `sar` output.
But the issue is that docker diskio module adds each of those 350MB/s to 2.7GB/s, plus 3.9GB, plus some more, adding up to 17.4GB/s.

The md/lvm devices form a tree:
```
$ lsblk
NAME         MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
nvme0n1      259:0    0  375G  0 disk
└─md0          9:0    0    3T  0 raid0
  ├─lxc-data 253:1    0  2.9T  0 lvm   /mnt/data
  └─lxc-swap 253:0    0 51.1G  0 lvm   [SWAP]
nvme0n8      259:7    0  375G  0 disk
└─md0          9:0    0    3T  0 raid0
  ├─lxc-data 253:1    0  2.9T  0 lvm   /mnt/data
  └─lxc-swap 253:0    0 51.1G  0 lvm   [SWAP]
nvme0n6      259:5    0  375G  0 disk
└─md0          9:0    0    3T  0 raid0
  ├─lxc-data 253:1    0  2.9T  0 lvm   /mnt/data
  └─lxc-swap 253:0    0 51.1G  0 lvm   [SWAP]
nvme0n4      259:3    0  375G  0 disk
└─md0          9:0    0    3T  0 raid0
  ├─lxc-data 253:1    0  2.9T  0 lvm   /mnt/data
  └─lxc-swap 253:0    0 51.1G  0 lvm   [SWAP]
nvme0n2      259:1    0  375G  0 disk
└─md0          9:0    0    3T  0 raid0
  ├─lxc-data 253:1    0  2.9T  0 lvm   /mnt/data
  └─lxc-swap 253:0    0 51.1G  0 lvm   [SWAP]
nvme0n7      259:6    0  375G  0 disk
└─md0          9:0    0    3T  0 raid0
  ├─lxc-data 253:1    0  2.9T  0 lvm   /mnt/data
  └─lxc-swap 253:0    0 51.1G  0 lvm   [SWAP]
sda            8:0    0   30G  0 disk
└─sda1         8:1    0   30G  0 part  /
nvme0n5      259:4    0  375G  0 disk
└─md0          9:0    0    3T  0 raid0
  ├─lxc-data 253:1    0  2.9T  0 lvm   /mnt/data
  └─lxc-swap 253:0    0 51.1G  0 lvm   [SWAP]
nvme0n3      259:2    0  375G  0 disk
└─md0          9:0    0    3T  0 raid0
  ├─lxc-data 253:1    0  2.9T  0 lvm   /mnt/data
  └─lxc-swap 253:0    0 51.1G  0 lvm   [SWAP]
```

Notice the major number 9 corresponds with md raid devices, and 253 is device-mapper (from `/proc/devices`).
These are also available in `/proc/diskstats`
```
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
   8       0 sda 18821921 4891 742344753 5210868 17237092 22847905 521428432 8605568 0 1263612 2864040
   8       1 sda1 18821725 4891 742333339 5210748 14342901 22847905 521427616 8436996 0 1279416 2887700
 259       0 nvme0n1 114101513 104140653 54677598816 2998774624 144813422 9630258 12588696976 42037728 0 72941496 1581412936
 259       1 nvme0n2 114025597 105159336 54894213624 4250499424 120080971 10394095 12387679744 41259740 0 75159684 2835838688
 259       2 nvme0n3 114047524 104511875 54744338240 3333000212 101409020 10303973 12229814096 36153360 0 74213848 1914539064
 259       3 nvme0n4 113279806 105475539 54763900272 3331491672 123196688 9026921 12413227616 39297092 0 74402208 1910521896
 259       4 nvme0n5 114124085 105172721 54869872432 4128439608 203573739 8517977 13056282376 59552996 0 76339140 2718089108
 259       5 nvme0n6 114068765 104844099 54797866464 3468558028 114385966 7789698 12323711280 40100268 0 75244212 2050503628
 259       6 nvme0n7 113694323 104939805 54708097312 3119445884 115731667 7900245 12326108240 37747976 0 74457392 1700093452
 259       7 nvme0n8 113342639 104721256 54582314632 2808556324 156938829 9197935 12699266728 47500108 0 73312656 1390806432
   9       0 md0 1749648166 0 619877334624 0 2054305417 0 100416874872 0 0 0 0
 253       0 dm-0 626 0 17776 136 115208 0 921656 73120 0 1404 73260
 253       1 dm-1 295932486 0 438038121784 3033248540 1779706390 0 100023865224 429497880 0 248288332 3473031260
```
So it should be possible to filter out those that are "aggregate" devices. The more "layers" of devices you have the more wrong the number will be (e.g. if you add encryption etc).

**Describe a specific use case for the enhancement or feature:**
If I see the disk usage is 4GB/s on the host, I want to pinpoint the corresponding docker container that's using around 4GB/s, but when I see numbers like 17GB/s I start scratching my head, wondering if the data is correct.

**Comment by fearful-symmetry** [comment]
@henrikno Can you get me raw event JSON for one of the offending events. The `docker/diskio` metricset is doing so much data manipulation that I'm not too sure what I'm looking at. Either way, this seems to be a fairly complicated problem, as we essentially need to figure out when we're dealing with LVs or RAID setups and adjust how we sum data accordingly?

**Comment by fearful-symmetry** [comment]
@henrikno is this still an issue? If so, I'd like to see a few of the ES documents.

**Comment by fearful-symmetry** [comment]
Alright, I actually managed to dig into the `diskio` metricset and figured out what's going on. For reference, here's the data that metricbeat gets:
```
        "io_service_bytes_recursive": [
            {
                "major": 8,
                "minor": 0,
                "op": "read",
                "value": 2359296
            },
            {
                "major": 8,
                "minor": 0,
                "op": "write",
                "value": 18572800
            },
            {
                "major": 253,
                "minor": 0,
                "op": "read",
                "value": 2359296
            },
            {
                "major": 253,
                "minor": 0,
                "op": "write",
                "value": 18572800
            }
        ],
```

Considering that the metricset blindly sums up device values, I wonder if the easiest solution here is, as @henrikno suggested, just to skip aggregate devices based on the major number, like `9` and `253`.

**Comment by henrikno** [comment]
Thanks! I think that should work. Alternative is to do something like netdata, but having it configurable should cover the same functionality.
> Total Disk I/O, for all physical disks. Physical are all the disks that are listed in /sys/block, but do not exist in /sys/devices/virtual/block.
