### ISSUE TITLE
Pass AWS tags to Functionbeat

### ISSUE THREAD

**Issue by g3kr** [elastic/beats#19807]
I am using Functionbeat 7.6.2 and I wanted to inject a few tags to all the AWS resources that get created as part of `functionbeat deploy cloudwatch`. Is there a way to do this today? I do not see documentation or examples on how to do it.

**Comment by kaiyan-sheng** [comment]
Hello, thanks for creating this issue. But we would kindly ask you to post all questions and issues on https://discuss.elastic.co/c/beats before opening a Github Issue. Your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue or open a new one with more details. Thanks in advance!
