### ISSUE TITLE
Please have report filesystem type

### ISSUE THREAD

**Issue by ckmcd** [elastic/beats#1980]
It would be very helpful to be able to filter on filesystem type (e.g. ext*, nfs, proc, etc.)

I know this as been mention in several discussion and it was suggested that an ER be opened.  I could not find one so here it is.

Thanks!

Chris

**Comment by tsg** [comment]
For clarity, does this refer to Filebeat or the Topbeat/Metricbeat disk usage stats?

**Comment by monicasarbu** [comment]
Closing this issue, as no more details were provided for 7 months.

**Comment by andrewkroh** [comment]
This may have been a duplicate of https://github.com/elastic/beats/issues/1980 if it was for Metricbeat.
