### ISSUE TITLE
[Metricbeat] Update Redis Library

### ISSUE THREAD

**Issue by trengrj** [elastic/beats#19820]
**Describe the enhancement:**
Current redis library used is redigo. v1.0.1.

This version of the library https://github.com/elastic/beats/blob/master/go.sum#L281 was last released in 2016 and needs updating. Development has moved on to https://github.com/gomodule/redigo.

**Describe a specific use case for the enhancement or feature:**
The current version does not support the `rediss://` url scheme for TLS (which is used for example in Azure Cache for Redis).

**Comment by jsoriano** [comment]
Library updated in https://github.com/elastic/beats/pull/23438, closing this.
