### ISSUE TITLE
Metricbeat: Hint based autodiscover for docker does not work when internal and exposed port differ

### ISSUE THREAD

**Issue by atoom** [elastic/beats#19825]
**Describe the enhancement:**
We are running our workloads on vm:s with metricbeat installed as a system service. We have started migrating some of our applications to run as docker containers and we are looking to use the hint based autodiscover functionality for simple configuration of metrics collection. I have been digging into the code a bit and it seems that the configuration is only generated if the docker event port matches the port in the hosts annotation. Since we are running our metricbeat agent as a standalone process and not in a container on a shared docker network the most natural thing for us is to use `localhost:<exposed port>` as the value for the hosts annotation - unfortunately this will not work since the autodiscover logic cannot map the match the exposed port to the internal port which results in the `no hosts selected for port 8081 with hints localhost:<exposed port>` message being logged.

Some background discussion can be found here: https://github.com/elastic/beats/pull/12086

**Describe a specific use case for the enhancement or feature:**

We would like to be able to use autodiscover on a container that exposes one or more ports with different values that the local ports. See example of docker configuration below:

```
$ docker inspect <my container>
[
    {
        "Id": "48b9345020ad2f8a5ec756c77e2c5fd301eeef33c30f226f73f9e01b1699549e",
        "Created": "2020-07-13T05:40:42.656568846Z",
        "Path": "java",
        "Args": [
            "org.springframework.boot.loader.JarLauncher"
        ],
        ...
        "HostConfig": {
            ...
            "PortBindings": {
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "48169"
                    }
                ],
                "8083/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "48569"
                    }
                ]
            },
        ...
        "Config": {
            ...
            "Labels": {
                "co.elastic.metrics/hosts": "localhost:48569",
                "co.elastic.metrics/metrics_path": "/actuator/prometheus",
                "co.elastic.metrics/module": "prometheus",
                "co.elastic.metrics/period": "30s",
            }
        },
        ...
```

A workaround for us is to make sure that the internal port and exposed port are identical however it is some extra configuration that must be passed into the container at runtime instead of being able to use static configuration and leveraging the port mapping functionality in docker to expose the internal port.

**Comment by ChrsMark** [comment]
Maybe we can introduce a similar approach to what we did for named Pod ports at https://github.com/elastic/beats/pull/19398.

However we it seems that the Docker lib does not map `PortBindings ` field at https://github.com/docker/engine/blob/1022c6608ee22a86eef8cd9a9c2c281fb4b653cc/api/types/types.go#L72 which is used at https://github.com/docker/engine/blob/1022c6608ee22a86eef8cd9a9c2c281fb4b653cc/api/types/types.go#L72.

**Comment by atoom** [comment]
It should be possible to use the `Ports` property instead (https://github.com/docker/engine/blob/1022c6608ee22a86eef8cd9a9c2c281fb4b653cc/api/types/types.go#L66) ? 

Unfortunately it does not look like the Docker api support naming of ports - maybe it is possible to use indexing instead ? Not sure if the ordering of ports is consistent though.

**Comment by ChrsMark** [comment]
> It should be possible to use the `Ports` property instead (https://github.com/docker/engine/blob/1022c6608ee22a86eef8cd9a9c2c281fb4b653cc/api/types/types.go#L66) ?
> 
> Unfortunately it does not look like the Docker api support naming of ports - maybe it is possible to use indexing instead ? Not sure if the ordering of ports is consistent though.

My original idea was to map each `port` to a `HostPort` by leveraging the content of `PortBindings ` so as events would look like:
```
{
  "ports": {
    "8080/tcp": 48169,
    "8083/tcp": 48569,
  }
}
```
Then the hint would be `"co.elastic.metrics/hosts": "localhost:${data.ports.8080/tcp}"` which I think would be really handy. However as I mentioned earlier the Docker lib does not seem to preserve `PortBindings` in the decoded sturct.

If we are not able to go with this approach, maybe by providing a patch in Docker lib to support this, then we could re-think about port matching logic we have right now and see if could somehow cover such cases like this one. cc:@jsoriano

**Comment by atoom** [comment]
> Then the hint would be "co.elastic.metrics/hosts": "localhost:${data.ports.8080/tcp}"

Yes that looks readable/understandable!

> However as I mentioned earlier the Docker lib does not seem to preserve PortBindings in the decoded sturct.

Ah - so `Port` is a go native type ? The docker api returns the port mapping in the response (https://docs.docker.com/engine/api/v1.40/#operation/ContainerList) - too bad that they have not implemented a 1:1 mapping in the wrapper library ?

**Comment by ChrsMark** [comment]
👍 good catch @atoom ! If `PublicPort` is what we need here then it could work by emitting a container level event at https://github.com/elastic/beats/blob/f91c96f672ba88edc668fe3d44249e46a3e9d2ec/libbeat/autodiscover/providers/docker/docker.go#L290 (after the for loop) with a key called `ports` with the following struct:

```
{ ...
  "ports": {
    "8080": 48169,
    "8083": 48569,
  }
}
```
which would be the result of privatePort:publicPort mapping. wdyt?

**Comment by atoom** [comment]
I just found the same code block in libbeat :)

Your suggestion sounds like it should work but maybe you should have some internal discussion about it with your team - having both `port` and `ports` in the api/type might be considered ugly by some - maybe there is a more elegant way to implement the fix and be backwards compatible at the same time ? Not sure if you have to align the api with other providers as well ?

As for `PrivatePort` vs `PublicPort` the code comments in the godoc should be trustable ?

```
   // Port on the container
    // Required: true
    PrivatePort uint16 `json:"PrivatePort"`

    // Port exposed on the host
    PublicPort uint16 `json:"PublicPort,omitempty"`
```

**Comment by ChrsMark** [comment]
@atoom 👍  will evaluate this solution and let you know soon!

**Comment by ChrsMark** [comment]
Another option would be to emit an extra event for the `PublicPort` too at https://github.com/elastic/beats/blob/f91c96f672ba88edc668fe3d44249e46a3e9d2ec/libbeat/autodiscover/providers/docker/docker.go#L290

**Comment by atoom** [comment]
It would probably work but publishing two events on the internal bus for each docker event would probably not be what subscribers initially excpect and could lead to some undesired behaviour i.e. double processing of some logic if not reading the docs carefully ?

**Comment by ChrsMark** [comment]
@atoom this was falling behind into the priorities' list ...sorry for the delay.
I have opened a PR to suggest a possible support for this case, see https://github.com/elastic/beats/pull/31243.

One question I have is why you want to use `localhost` and the `HostPort` instead of the container's IP along with the internal port. This happens when you define the `host` like `${data.host}:${data.port}` instead of `localhost:48569`. Wouldn't that work in your case?

**Comment by atoom** [comment]
@ChrsMark no worries - thanks for taking the time to work on this!

We are not running Kubernetes or any other orchestration tool so we just start our containers on a host via the docker daemon and expose our service and metric ports via docker standard port mappings. As for metricbeat we runt that as normal host process which means that it can scrape metric data for local containers using localhost + host.port.

**Comment by ChrsMark** [comment]
I see. 

What I have in mind is that you can use `IPAddress` of the container directly (nothing to do with Kubernetes or any orchestrator). 

For example if I run `docker run --name nats --rm -p 4222:4222 -p 8081:8222 nats:2.1.4 --http_port 8222` and then `inspect` the container I see:

```
...
"Networks": {
        "bridge": {
          "IPAMConfig": null,
          "Links": null,
          "Aliases": null,
          "NetworkID": "28282ac5c72ef0c141700be06930a27d2a2c097c4c6e600f9bc896a1be258174",
          "EndpointID": "4101f2e35c51dcb5c62664e44e07c98416f732cb31a1b7590cc732dc04c1f5bb",
          "Gateway": "172.17.0.1",
          "IPAddress": "172.17.0.4",
          "IPPrefixLen": 16,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
          "MacAddress": "02:42:ac:11:00:04",
          "DriverOpts": null
        }
      }
...
```

so from the host I can directly `curl http://172.17.0.4:8222` without a problem which is actually what `${data.host}:${data.port}` would do in case of autodiscovery.

You can give it a try, but nevertheless is the feature of having the option to use the host ports too can be considered valid.
