### ISSUE TITLE
[Filebeat] S3 input module should trim the delimiter of log line 

### ISSUE THREAD

**Issue by kwinstonix** [elastic/beats#19853]
- Bug

For confirmed bugs, please report:
- Version: 7.8.0

Here `log` contains delimiter `\n`,  so each event message filed also  has `\n`.  

I think It is better to trim `\n`,  just like the behavior of reading log files 

https://github.com/elastic/beats/blob/d0f705858f0058e5f5c64db066ee48aa35f1981c/x-pack/filebeat/input/s3/input.go#L477-L486

**Comment by exekias** [comment]
This looks reasonable to me, I think this is what we do for all the other inputs
