### ISSUE TITLE
Request: Make a universal installer that automaties the installation and configuration of all Elastic products

### ISSUE THREAD

**Issue by rugabunda** [elastic/beats#19855]
Too much configuration complicates and confuses people and wastes precious time. Please create an all in one installer that offers the ability to both install and configure a working setup, that works. Automates the installation of winlogbeat, kibana, and logstash (etc) without having to use the commandline or manually install services... that automates the templates needed to get logstash to work automatically with winlogbeat, and all the rest without any need to manually configure anything outside of the installer. Thanks.

**Comment by andresrc** [comment]
Hi,

The stack is a distributed environment where each of the components can be installed in may different ways, and in most cases in different platforms.

For an all-in-one approach (though it does not include all the components yet, but getting there) one approach would be [ECK](https://www.elastic.co/guide/en/cloud-on-k8s/current/index.html)

Thanks
