### ISSUE TITLE
Kubernetes components logs module

### ISSUE THREAD

**Issue by exekias** [elastic/beats#19874]
**Describe the enhancement:**

Some Kubernetes internal components write logs under `/var/log`.

We should evaluate what makes sense to retrieve, and create a `kubernetes` module/integration for them
https://kubernetes.io/docs/concepts/cluster-administration/logging/#system-component-logs for mor details.

**Comment by exekias** [comment]
@ChrsMark are you familiar with these? I'm wondering what would make sense to retrieve

**Comment by ChrsMark** [comment]
For components that run as container/Pods like `kube-proxy`, `kube-scheduler` I think we already collect those logs (without having a specific fileset though to further analyse them). For instance:

```
tail -f /var/log/containers/kube-proxy-w6jnn_kube-system_kube-proxy-35a23882db7a3bab26ee375f67bf7c22a72e47d832fc86edd94712737345b5c6.log
{"log":"I0713 08:47:11.664817       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072\n","stream":"stderr","time":"2020-07-13T08:47:11.674362088Z"}
{"log":"I0713 08:47:11.664842       1 conntrack.go:52] Setting nf_conntrack_max to 131072\n","stream":"stderr","time":"2020-07-13T08:47:11.674402172Z"}
{"log":"I0713 08:47:11.664907       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400\n","stream":"stderr","time":"2020-07-13T08:47:11.674408073Z"}
{"log":"I0713 08:47:11.664943       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600\n","stream":"stderr","time":"2020-07-13T08:47:11.674411131Z"}
{"log":"I0713 08:47:11.667059       1 config.go:313] Starting service config controller\n","stream":"stderr","time":"2020-07-13T08:47:11.674419229Z"}
{"log":"I0713 08:47:11.667078       1 shared_informer.go:197] Waiting for caches to sync for service config\n","stream":"stderr","time":"2020-07-13T08:47:11.674423812Z"}
{"log":"I0713 08:47:11.669775       1 config.go:131] Starting endpoints config controller\n","stream":"stderr","time":"2020-07-13T08:47:11.674426932Z"}
{"log":"I0713 08:47:11.669794       1 shared_informer.go:197] Waiting for caches to sync for endpoints config\n","stream":"stderr","time":"2020-07-13T08:47:11.674429694Z"}
{"log":"I0713 08:47:11.768548       1 shared_informer.go:204] Caches are synced for service config \n","stream":"stderr","time":"2020-07-13T08:47:11.772311427Z"}
{"log":"I0713 08:47:11.770936       1 shared_informer.go:204] Caches are synced for endpoints config \n","stream":"stderr","time":"2020-07-13T08:47:11.772496142Z"}
```

![Screenshot 2020-07-14 at 11 52 43](https://user-images.githubusercontent.com/11754898/87405769-8e509c00-c5c8-11ea-91ad-c5f7490a8cb8.png)

Would it be of value to create specific filesets for this kind of components?

Regarding `kubelet`, it would be different since in most cases it is a daemon running on the host and in most cases it is handled by systemd which make things a little bit if we want to read the logs using filebeat.
Some goes for container runtimes like `containerd`.

**Comment by exekias** [comment]
Nice, probably the question here is: should we add pipelines to parse these logs into structured documents? Is there any value in them that could end up in a dashboard?

**Comment by eedugon** [comment]
@exekias, @chrsblck , this is a very interesting topic and probably covers a lot of areas / possibilities:

- The majority of the logs we are already retrieving them via the default DaemonSet that we propose, as @ChrsMark says. Even if we are not processing them with pipelines, at least they are very well organized thank to the `add_kubernetes_metadata`. The pipelines might add some extra value, but most probably we should go case by case.

- There are extra logs at "node" level (as @exekias mentioned) that we might not be considering at the moment, like kubelet logs or the normal system logs (syslog, etc).

On the other hand we also have the "As s service" environments (GKE, EKS, etc) where I believe the cloud provider offers a single point to fetch all kubernetes logs.

Maybe this last case would be an interesting one too, to organize all this data, as most probably if a user retrieves them they won't be able to identify much, as `add_kubernetes_metadata` processor wasn't really applied to them. Anyway I haven't looked deeply into the format or content of this "as a service" provided logs.

**Comment by schewara** [comment]
+1 for providing a module for properly parsing Kubernetes logs

From what i saw so far many software components which are intended to run on Kubernetes seem to use klog and even there is an alpha support for structured logging in json (text will still be the default it seems), but the lack of influence on the logformat in a hosted kubernetes environment, a module to properly parse these log entries would be highly valuable to filter for the different loglevels (1st Character of the Logline)

For completeness the Link to the Documentation:
https://kubernetes.io/docs/concepts/cluster-administration/system-logs/
