### ISSUE TITLE
Add azure `application_state` light metricset based on app_insights metricset

### ISSUE THREAD

**Issue by narph** [elastic/beats#19881]
The `app_insights` metricset offers users the possibility to select any of the metrics they would like to collect, together with any filtering options as aggs, segments, interval etc.: https://github.com/elastic/beats/pull/18940

The `application_state` metricset will be a light metricset based on the `app_insights` metricset which will collect the most relevant metrics and will provide dashboards.
Example metrics:
- top failing requests by name
- top slowest requests by name
- cpu and memory avg
- avg page load time 
etc

`application_state` or `application_status` does not sound too great , any opinions are more than welcome @sorantis , @andresrc

**Comment by sorantis** [comment]
Perhaps `app_state`? I think it would be good if all related metricsets had similar naming convention

**Comment by narph** [comment]
has been implemented, closed
