### ISSUE TITLE
packetbeat error about flexible ports

### ISSUE THREAD

**Issue by Jayranbutong** [elastic/beats#1989]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For confirmed bugs, please report:
- Version: packetbeat version 5.0.0-SNAPSHOT (amd64)
- Operating System: osx
- Steps to Reproduce: I have develped a new protocol，but the protocol's port is flexibled.But packetbeat must set the ports[] item in pacektbeat.yml.So,what about this issue？BTW，this protocol'ports have a range，about 4,000 in total.

**Comment by tsg** [comment]
So what protocol is it? :-). 

I think it would be possible to extend the protocol matching code to accept port ranges.

**Comment by urso** [comment]
[related discussion](https://discuss.elastic.co/t/what-about-flexible-ports/54940)

**Comment by lindsay-show** [comment]
msrp.every session will be assigned a port.so，I have solved it with your help.Thanks a lot.

**Comment by urso** [comment]
Will keep this open. Still valid request to have port ranges being supported out of the box by packetbeat + more efficient BPF filter based on `portrange`can be constructed, if ranges are natively supported by packetbeat.
