### ISSUE TITLE
add process UID data to topbeat process information

### ISSUE THREAD

**Issue by zenfish** [elastic/beats#1991]
Currently you can get proc.username (https://www.elastic.co/guide/en/beats/topbeat/current/exported-fields-process.html), but that's not a terribly useful bit of data without the corresponding uid; for instance the canonical added account after a compromise is a arbitrarily named account with uid=0 (AKA root.)

Permissions/security wise the username doesn't mean anything; instead the real/effective IDs of the process in question are examined. Seeing a process run by user "foo" is close to meaningless unless you know that foo also has an effective uid of 0, 666, or whatever.

Ideally I'd like the:
- real uid
- effective uid
- saved uid

**Comment by alvarolobato** [comment]
Topbeat is not under development any more.
