### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc'

### ISSUE THREAD

**Issue by Bernhard-Fluehmann** [elastic/beats#19915]
make testsuite in x-pack/filebeat prints the following error message:
......./tmp/python-env/build/ve/docker/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(key, collections.Hashable):

I don't know how important this is but thought it would be worth mentioning.

For confirmed bugs, please report:
- Version: master
- Operating System: Mac OS 
- Steps to Reproduce: make testsuite

**Comment by tirkarthi** [comment]
This is due to pyyaml : https://github.com/yaml/pyyaml/issues/202
