### ISSUE TITLE
[Heartbeat] Add HTTP header fields

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#19928]
**Describe the enhancement:**

Add HTTP headers similar to APM to heartbeat.

Completed in https://github.com/elastic/beats/pull/18327

**Comment by justinkambic** [comment]
I tested this as part of the 7.9 test plan and was able to see http headers in my heartbeat documents:

![image](https://user-images.githubusercontent.com/18429259/88104951-2e7e6600-cb71-11ea-9578-69116eb07b5c.png)
