### ISSUE TITLE
metricbeat : Failed to publish events: unsupported float value: NaN / Broken Error handling

### ISSUE THREAD

**Issue by jlvrhee** [elastic/beats#19937]
We have an issue with metricbeat on servers where we run docker containers, where it starts logging "Failed to publish events: unsupported float value: NaN" after some time. A restart of metricbeat solves the issue temporary.

Versions:
Metricbeat version: 7.7.1
OS version : Flatcar 2303.4.0 and RHEL 7.4
Docker : Docker version 18.06.3-ce, build d7080c1
We also configured docker swarm on these nodes

Discuss Forum URL:
https://discuss.elastic.co/t/metricbeat-7-7-1-failed-to-publish-events-caused-by-unsupported-float-value-nan/240400

metricbeat config:
```
 #-------------------------------- System Module --------------------------------
- module: system
  enabled: true
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
    - core
    - diskio
    - socket
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
    - service
    - users
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)'

- module: system
  period: 15m
  metricsets:
    - uptime

#-------------------------------- Docker Module --------------------------------
- module: docker
  enabled: true
  period: 10s
  metricsets:
    - container
    - cpu
    - diskio
    - event
    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
```

The logs after a certain period get full with:
```
Jul 08 13:05:53 sldclr0102 metricbeat[129177]: 2020-07-08T13:05:53.169+0200        DEBUG        [logstash]        logstash/async.go:119        connect
Jul 08 13:05:53 sldclr0102 metricbeat[129177]: 2020-07-08T13:05:53.177+0200        INFO        [publisher_pipeline_output]        pipeline/output.go:111        Connection to backoff(async(tcp://cpxlog-elk102.support.local:5045)) established
Jul 08 13:05:53 sldclr0102 metricbeat[129177]: 2020-07-08T13:05:53.177+0200        DEBUG        [logstash]        logstash/enc.go:37        Failed to encode event: &{2020-07-08 12:32:02.974424766 +0200 CEST m=+1187.408593395 {} Not valid json: json: error calling MarshalJSON for type common.Float: invalid character 'N' looking for beginning of value <nil> true}
Jul 08 13:05:53 sldclr0102 metricbeat[129177]: 2020-07-08T13:05:53.177+0200        DEBUG        [logstash]        logstash/async.go:171        35 events out of 35 events sent to logstash host cpxlog-elk102.support.local:5045. Continue sending
Jul 08 13:05:53 sldclr0102 metricbeat[129177]: 2020-07-08T13:05:53.177+0200        DEBUG        [logstash]        logstash/async.go:127        close connection
Jul 08 13:05:53 sldclr0102 metricbeat[129177]: 2020-07-08T13:05:53.177+0200        DEBUG        [transport]        transport/client.go:118        closing
Jul 08 13:05:53 sldclr0102 metricbeat[129177]: 2020-07-08T13:05:53.178+0200        ERROR        [logstash]        logstash/async.go:279        Failed to publish events caused by: unsupported float value: NaN
Jul 08 13:05:53 sldclr0102 metricbeat[129177]: 2020-07-08T13:05:53.178+0200        DEBUG        [logstash]        logstash/async.go:127        close connection
 ```

This only occurs on systems where we have docker containers running and especially when they are stopped/started/restarted regularly. We still try to figure out which docker metricset is causing this.

We are running logging allready in debug mode on some servers, but logging is not very specific which field contains the value NaN. Can we change this some how?

**Comment by fearful-symmetry** [comment]
@jlvrhee Can you disable the system module so we can try and see where this is coming from? If the issue persists with just the docker module, it's something in there, otherwise we know it's something in the system module.

**Comment by fearful-symmetry** [comment]
Also, @jlvrhee is there a chance you could upgrade to 7.8? The problem may be fixed in a newer version.

**Comment by jlvrhee** [comment]
Thanks for the suggestion. We will start working on these and let you know

**Comment by jlvrhee** [comment]
I have disabled the system module by commenting out that whole section. I have tested with below docker module set and then it still gives this error after some time. Next step I will install 7.8 and see if it still fails then.
 
```
#-------------------------------- Docker Module --------------------------------
- module: docker
  enabled: true
  period: 10s
  metricsets:
    - container
    - cpu
    - diskio
    - event
#    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
```

**Comment by jlvrhee** [comment]
Is there a way we could change the debug logging so we could see which field gives this issue? Like you did with : https://github.com/elastic/beats/issues/11283#issuecomment-480334437

**Comment by fearful-symmetry** [comment]
@jlvrhee We modified the source code to to get some of that extra debugging. I'm hoping that 7.8 fixes the issue.

**Comment by jlvrhee** [comment]
Before the weekend we installed metricbeat 7.8 on one server. Untill now that server didn't give any issue anymore. I just enabled all the metricsets again including the system metricsets and will monitor this server futher.

**Comment by fearful-symmetry** [comment]
@jlvrhee does it look like 7.8 fixed the issue?

**Comment by jlvrhee** [comment]
@fearful-symmetry Yes it looks like 7.8 solved the issue. So I propose to close this issue.

**Comment by Kindrat** [comment]
@fearful-symmetry I'm on 7.8 now and still getting this error.
