### ISSUE TITLE
[Metricbeat] Add cost warning to AWS modules docs

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#19940]
Some users are unaware of the underlying implementation of the AWS module and are taken by surprise when they see a CloudWatch bill. Add a warning message to the AWS module documentation stating that there's a potential cost associated with using the module due to the GetMetricData API calls.

**Comment by exekias** [comment]
We should extend this discussion to GCP & Azure modules too. I see there is a pretty detailed guide on cost estimation here: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-aws.html#_aws_api_requests_count_per_metricset

I guess you are asking about an explicit warning balloon in the docs?

**Comment by sorantis** [comment]
Correct, the warning message could actually link to the detailed guide you mentioned.

**Comment by kaiyan-sheng** [comment]
Good point! We should have warning message in the documentation for all public cloud providers. I will take this issue and create a PR for AWS. Thank you!

**Comment by narph** [comment]
we already mention in the Azure doc https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-azure.html#_additional_notes_about_metrics_and_costs
and where users can find the pricing and call daily limit.
Also, if they reach the daily limit and calls are starting to require a cost, users are warned in the logs.

**Comment by kaiyan-sheng** [comment]
@narph Thank you for the info. I propose to add the cost warning message at the beginning of the documentation for all AWS, Azure and GCP modules. Even with mentioning cost in other parts of the doc, I would like to make these three modules consistent and warn user at the beginning. This way, it's less possible for users to miss.

**Comment by ycombinator** [comment]
Sounds like we're talking about adding warnings in docs and Metricbeat logs. In addition, would it make sense to show a warning toast in the Metrics UI if cloud metrics are detected? Just wondering where users are actually looking so maybe we cover all our bases?

**Comment by kaiyan-sheng** [comment]
@ycombinator Good point! Azure module already has warning in the Metricbeat log. It would be good for GCP and AWS to do the same.

**Comment by andresrc** [comment]
What's missing to close this issue?

**Comment by kaiyan-sheng** [comment]
@andresrc We haven't added any log message in the code yet. Only added warning in doc.

**Comment by kaiyan-sheng** [comment]
Warning log message is added. Will close this issue now.
