### ISSUE TITLE
IPv6 support for PacketBeat

### ISSUE THREAD

**Issue by raboof** [elastic/beats#1995]
(feature request as discussed at https://discuss.elastic.co/t/packetbeat-ipv6-support/54941)

It'd be neat if packetbeat supported IPv6.

I've done some preliminary work at https://github.com/elastic/beats/compare/master...raboof:packetbeat-ipv6 - of course needs finishing and tests. Feel free to provide feedback already, though unfortunately it might be a while before I can find someone who is authorized to sign the CLA for me.

**Comment by tsg** [comment]
Diff doesn't look huge, so if you think you won't get approval for contributing the code, let us know. We can reimplement the changes.

**Comment by monicasarbu** [comment]
Closing the issue, as the PR was merged.
