### ISSUE TITLE
[Agent] Mention that Elastic Agent must be run as SYSTEM on Windows when using Endpoint

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#19955]
**Describe the enhancement:**
Add a statement to the current docs where we describe running the Elastic Agent to make it clear that Windows users must run as SYSTEM to use Endpoint.

**Comment by tonymeehan** [comment]
Would this statement make its way to the download page instructions as well? https://www.elastic.co/downloads/elastic-agent

**Comment by ph** [comment]
@tonymeehan I think it would be nice to add it, let me try figure out where it land. web team or infra.
