### ISSUE TITLE
Support/Document Enabling Multiple Beat Processes On A Single Host Server

### ISSUE THREAD

**Issue by MorrieAtElastic** [elastic/beats#19996]
**Describe the enhancement:**
- Something that our customers frequently do is to run multiple versions of the same beat process off of the same server. 

- This is typically true of filebeat; it allows users to run different versions of filebeat to read different input streams and write to different indexes. 

- I don't know if this is or is not supported: I'm not able to find any discussion of it in the official documentation. So this Enhancement Request has 2 parts:

(1) officially support the running of multiple filebeat (at least) processes on the same host server

(2) for each type of Linux service, document the correct way to do this. 

**Describe a specific use case for the enhancement or feature:**
- as mentioned above, users can then run separate filebeat instances for separate log inputs and index outputs. I believe that this is simpler to implement and safer to implement than having a single filebeat process supporting multiple input streams and multiple output streams concurrently.

**Comment by kvch** [comment]
Running multiple instances of the same Beat is supported. However, the user needs to adjust the path configurations to prevent the instances from overwriting each other's metadata and logs. There are two options to overwrite these path settings. The first one is changing `path.home` to a different folder and put the configuration file in that folder. The other `path.*` options can be derived from the `path.home` option.

Alternatively, users can change the following folder separately:
* `path.config`: Path to the configuration files and keystore
* `path.log`: Path to the logs of the Beat
* `path.data`: Path to the data files of the Beat (e.g. ID, registry file)

If someone runs Beats with `systemd`, they have to adjust the unit file as well. Or in case of Windows the `install-service.ps1` file, etc.

The following optional changes are needed to be able to tell apart the different instances. It is not required for correct behaviour.
* `name`: By default, it is set to the name of the host. However, if you run multiple Beats on the same host it will be the same value.

**Comment by ph** [comment]
This is a problem the Agent doesn't support running multiples agent side by side really easily.
I think we should concentrate on fixing the actual use case and not having really going on multiple binaries.

Sending data to different index is already supported, you can use the "index" key in the input to route event to a specific index.

**Comment by jlind23** [comment]
Closing it for now until further activity.
