### ISSUE TITLE
Display Processing Details for Filebeat

### ISSUE THREAD

**Issue by pulkits1998** [elastic/beats#19991]
I have 100 logs files in a directory and each log file contains 10000 log lines (Assume that no new file will be added or deleted or modified). I started filebeat giving path to the log directory.

At the end, when processing of all files is completed, I want : 

- Number of files processed

- Number of log lines processed

- Number of successfully sent log lines

- Number of failed log lines

- Total time taken to process all the log files

It would be better if we can see these statistics even when filebeat is processing log files.

Currently, there is no feature to view these details. If these enhancements are made, It will be very helpful for estimating the efficiency of filebeat for different use cases.

**Comment by andresrc** [comment]
Hi @pulkits1998,

Some of that information is already available through the [metrics endpoint](https://www.elastic.co/guide/en/beats/filebeat/7.8/http-endpoint.html) and [stack monitoring](https://www.elastic.co/guide/en/beats/filebeat/7.8/monitoring.html) features.

Thanks

**Comment by jlind23** [comment]
Closing it for now until further activity.
