### ISSUE TITLE
Identify files based on their contents in Filebeat

### ISSUE THREAD

**Issue by kvch** [elastic/beats#19990]
Now multiple options are available to identify files in Filebeat: `native`, `path` and `inode_marker` since #18748. These options provide a quick method to generate an identifier for a file. However, in some use cases or on platforms these might not be sufficient.

More advanced identification can be implemented by fingerprinting full or partial contents of a file.

Follow up issue of elastic/beats#13492

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
