### ISSUE TITLE
Add option to output without the JSON wrapper

### ISSUE THREAD

**Issue by tsg** [elastic/beats#2000]
The log lines generated by Filebeat are wrapped automatically in a JSON object. For some outputs (console, file, kafka, redis) it could be an option to just send the original log lines with wrapping them. The way this could be implemented is by allowing at the output level to build a message via a format string. 

For example:

```
output.kafka:
  format: "%{@timestamp} %{message}"
```

This would be helpful during development (console and file outputs) as well as in some deployment situations.

**Comment by treff7es** [comment]
I like this generic solution and happy to help implement it.
