### ISSUE TITLE
"Error setting up ML for apache_ecs:" when running filebeat setup 

### ISSUE THREAD

**Issue by MikePaquette** [elastic/beats#20022]
For confirmed bugs, please report:
- Elasticsearch Version: 7.9.0 BC2 
- Filebeat Version: 7.9.0 BC2
- Operating System: macOS10.14.6
- Steps to Reproduce: 

mikep$ `./filebeat modules enable system`
Enabled system
mikep$ `./filebeat setup`
Overwriting ILM policy is disabled. Set `setup.ilm.overwrite: true` for enabling.
Index setup finished.
Loading dashboards (Kibana must be running and reachable)
Loaded dashboards
Setting up ML using setup --machine-learning is going to be removed in 8.0.0. Please use the ML app instead.
See more: https://www.elastic.co/guide/en/machine-learning/current/index.html
Exiting: 1 error: Error setting up ML for apache_ecs: cannot set up ML with prefix: filebeat-apache_ecs-access-
mikep$

**Comment by kvch** [comment]
@MikePaquette Could you please share your configuration? Also, a bit more details about Elasticsearch and Kibana would be useful? Are you using the OSS version? Did you enable security?

**Comment by kvch** [comment]
Please share debug logs as well.
