### ISSUE TITLE
Add info about cloudwatch_logs_kinesis to the Functionbeat Reference

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#20042]
**Describe the enhancement:**
The Functionbeat Reference needs to be updated with the new function type, `cloudwatch_logs_kinesis`, added in https://github.com/elastic/beats/pull/13317. Right now, it's only covered in the reference.yml.

As part of this work, we should restructure the docs as described here: https://github.com/elastic/beats/issues/13908

**Comment by jlind23** [comment]
Closing it for now until further activity.
