### ISSUE TITLE
Tried running this in Windows and get the following error , "go: cannot determine module path for source directory C:\Users\gurke\go\src\ (outside GOPATH, module path must be specified)"

### ISSUE THREAD

**Issue by Keerat666** [elastic/beats#20047]
Hi,

Was trying to setup a custom beat template on Windows.Everything works fine until when I hit the mage generateCustomBeat command and then get this issue, 

'go: cannot determine module path for source directory C:\Users\gurke\go\src (outside GOPATH, module path must be specified)'

Any help is appreciated!

**Comment by TanmaiShukla** [comment]
go: cannot determine module path for source directory C:\Users\shukl\go\src (outside GOPATH, module path must be specified)

Example usage:
        'go mod init example.com/m' to initialize a v0 or v1 module
        'go mod init example.com/m/v2' to initialize a v2 module

Run 'go help mod init' for more information.
Error: error initializing a module for the Beat: running "go mod init" failed with exit code 1
