### ISSUE TITLE
winlogbeat 7.8 event.outcome on non-english OS

### ISSUE THREAD

**Issue by okoehler-okocon** [elastic/beats#20079]
Hello,

i just encountered that winlogbeat 7.8 is not setting eventOutcomes on non-english OS correctly (here in German)

this is the original Events in winlogbeat-security.js and that will not catch the german translation in the eventlog

var eventOutcomes = {
        "Audit Success": "success",
        "Audit Failure": "failure",
    };

this works...
var eventOutcomes = {
        "Audit Success": "success",
        "Audit Failure": "failure",
        "Überwachung erfolgreich": "success",
        "Überwachung fehlgeschlagen": "failure"
    };

**Comment by willemdh** [comment]
(Same for Dutch events)
