### ISSUE TITLE
Kafka version compatibility documentation

### ISSUE THREAD

**Issue by brandonmensing** [elastic/beats#2018]
Similar to how we document in LS, we should explain the versions of Kafka we're compatible with. @urso Might you be best to confirm which version(s) we support?

**Comment by urso** [comment]
beats uses [sarama](https://github.com/shopify/sarama) lib for kafka. Lib officially supports kafka 0.8 and 0.9. Kafka 0.10 might work too, but with potential performance loss. See [kafka upgrading docs](http://kafka.apache.org/documentation.html#upgrade)

**Comment by ppf2** [comment]
@urso Thanks.  Does it mean that if a user already has Kafka 0.10 broker running prior to using the upcoming Kafka beats output (vs. having Kafka beats output running and later upgrade their broker to 0.10), there will be no potential performance loss?

**Comment by brandonmensing** [comment]
Ooops, just realized this duplicates https://github.com/elastic/beats/issues/1450 - closing.
