### ISSUE TITLE
Issue with output kafka multiple topics

### ISSUE THREAD

**Issue by vasilievs** [elastic/beats#20233]
For confirmed bugs, please report:
- Version: 7.8.0
- Operating System: Docker container (Host - RHEL 7)
- Discuss Forum URL: https://discuss.elastic.co/t/issue-with-output-kafka-multiple-topics/242316
- Steps to Reproduce: 
(use config) Create mutiple input filebeat, add fileds for difficult topics, set output kafka.topics with '%{[fields.kafka_topic]}'

filebeat.yml

name: filebeat.host
logging.level: info
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*-json.log
  fields:
    log_topic: 'containerlogs'
- type: log
  enabled: true
  fields:
    log_topic: 'kafkalogs'
  paths:
    - /var/log/kafka/*.log
#
output.kafka:
  hosts: [ "kafka_sasl_ssl_server:9093" ]
  username: 'filebeat'
  password: 'filebeat-password'
  ssl.enabled: true
  ssl.certificate_authorities: ["root-ca.crt"]
  topic: '%{[fields.kafka_topic]}'
  compression: none
  max_retries: -1
  backoff.max: 10s
  required_acks: 1

**Comment by andresrc** [comment]
Hi! We will provide and answer in the discuss topic. Sorry for the delay.

Thanks!
