### ISSUE TITLE
Please add DNS module under googlecloud.yml (filebeat)

### ISSUE THREAD

**Issue by augustynd** [elastic/beats#20231]
The current parsers under beats/x-pack/filebeat/modules.d/googlecloud.yml.disabled include parsers for vpcflow, firewall, and audit. Can you please add dns parser as well?

**Comment by augustynd** [comment]
@masci can you please add Filebeat to Labels, thanks!

**Comment by andrewkroh** [comment]
Can you please provide a URL reference for the specific logs you're interested in ingesting. I found https://cloud.google.com/dns/docs/monitoring#dns-log-record-format, but I wanted to be sure.

**Comment by augustynd** [comment]
This is the right URL, thanks!

**Comment by augustynd** [comment]
Any updates on this?

**Comment by jamiehynds** [comment]
PR for GCP DNS was merged recently (see [here](https://github.com/elastic/integrations/pull/2624)) - curious is this covers the logs you were hoping to ingest @augustynd? Worth noting it only covers our Elastic Agent integration, not the Filebeat module.

**Comment by LiamSennitt** [comment]
I believe @augustynd is asking for it to be added to `filebeat`, I did create a PR for that originally in #29953.

**Comment by andrewkroh** [comment]
The path here is to migrate to the Fleet integration for GCP which now has the [DNS](https://docs.elastic.co/en/integrations/gcp#dns) data stream from @LiamSennitt.

If you haven't migrated to Elastic Agent and Fleet you can still take advantage of the GCP Fleet integration. It requires a bit of experience configuring the stack. Basically you setup a Pub/Sub input in Filebeat and route the data to Fleet integration's `logs-gcp.dns-default` data stream. There's a rough tutorial at [tutorial](https://gist.github.com/andrewkroh/c253717ebe82f2ec47fe003eda99c1dc).

**Comment by jamiehynds** [comment]
Closing, as our GCP integration now supports the DNS data stream.
