### ISSUE TITLE
[Elastic Agent] Warn user when agent is run without sudo or admin privileges

### ISSUE THREAD

**Issue by jesse-sant** [elastic/beats#20257]
When running the Elastic Agent after enrolling, there is no indication that the agent needs to be run with `sudo`, or administrator privileges.  Instead, if you run without `sudo`/administrator, the agent appears to start and run normally, but the actual setup does not continue (beats, and critically Elastic Endpoint, are not installed).  The agent also goes to the `online` status in Fleet, but within around 2 minutes stops reporting back and changes to `offline`.

There should be a warning presented to the user at the CLI if the agent is started in this manner.  There should also be a note in the Ingest Manager UI for the enrolment instructions that makes the requirement to run with administrator privileges clear.

- Version: 7.9 BC4
- Operating System: Linux and macOS
- Steps to Reproduce: 
  - Start a cloud instance of 7.9 BC4 with Ingest Manager enabled
  - Setup Fleet
  - Add the Elastic Endpoint to the default agent configuration
  - (If on Windows, open a *non-administrator* powershell)
  - Enroll a new agent using the default configuration
  - Run `./elastic-agent run` as recommend by the UI, note whether beats are installed, Elastic Endpoint is installed, or agent successfully applies its `agent config`
  - Kill the previous agent with `ctrl + c`
  - run `sudo ./elastic-agent run` and note the same items as in the above step (if on windows don't use sudo, just open an *administrator* powershell first)

**Comment by EricDavisX** [comment]
@ph @blakerouse @michalpristas do you have thoughts on this?

**Comment by michalpristas** [comment]
this was an issue of recent discussion, we have few strategies in mind one of them would be limiting scope of agent when not running elevated. i dont think we agreed on anything just yet but we would like to see agent being capable of non elevated runs

cc @ruflin

**Comment by ph** [comment]
I think we should allow elastic agent to run without elevated. I think we could leverage our "conditions" idea for integration and stream and applies in at the configuration level. So the Agent could use these conditions defined in the program spec and output the warning in the log and report it back to fleet.

**Comment by blakerouse** [comment]
@ph That is a really good idea. If we add it to "conditions" then it allows the packages to define what can/can't run on a host without privileges. That way we do not need to build lots of logic into Agent on how things should run, when in reality Agent doesn't really know what inputs need what permissions.

**Comment by ph** [comment]
@blakerouse Yes, I think that makes the concepts more powerful, conditions at the program spec level, conditions at the input level.

**Comment by ruflin** [comment]
@blakerouse Very interesting idea, that each dataset could also specify a condition which privileges it needs. I like it.

**Comment by ph** [comment]
This requires more investigation, @ruflin @urso I know that currently we don't allow Elastic Agent to run without root or multiple instance on the same same. I do not consider this really high priority. cc @mostlyjason

**Comment by jlind23** [comment]
@mostlyjason regarding your actual work around superuser removal. Shouldn't we close this issue?

**Comment by mostlyjason** [comment]
I believe this about root privileges on the host, not about superuser privileges in Kibana. We already offer a warning as of 7.13 so I think we can close this issue now.

```
$ ./elastic-agent install
Error: unable to perform install command, not executed with root permissions
```

Once the agent is installed it runs as a system service
