### ISSUE TITLE
Filebeat cisco/asa and ftd sets event.outcome to a non-conforming value

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#20253]
The shared ingest pipeline sets `event.outcome` to _allow_ or _deny,_ instead of using one of the [values allowed by ECS:
](https://www.elastic.co/guide/en/ecs/1.5/ecs-allowed-values-event-outcome.html)

- failure
- success
- unknown

**Comment by BenB196** [comment]
Just an fyi, this is a related issue: https://github.com/elastic/beats/issues/19943
