### ISSUE TITLE
[Ingest-Management]: Agent "restart" service gets crashed and error appears under "Agent activity log" page, when we restart the agent service (installed using PS1 command)

### ISSUE THREAD

**Issue by kamalpreetpahwa-qasource** [elastic/beats#20260]
**Kibana version:**
Kibana: 7.9 BC4

**Elasticsearch version:**
Elasticsearch: 7.9 

**Agent version:**
Agent:7.9 

**Browser version:**
Windows 10_x64, Chrome

**Original install method (e.g. download page, yum, from source, etc.):**
From download page.

**Description**
[Ingest-Management]: Agent "restart" service gets crashed and error appears under "Agent activity log" page, when we restart the agent service (installed using PS1 command)

**Preconditions**
1.Kibana 7.9 BC4 cloud environment should be available.
2. Agent service should be installed on local machine using PS1 command using following steps:
steps:
(a)Run PS1 command at location where agent is unzipped: command: .\install-service-elastic-agent.ps1
(b)Then enroll the agent with Fleet>string having token.
(c)Start the agent service from "Services" window.

**Steps to Reproduce**
1. Open the Kibana 7.9 BC4 cloud environment in browser, then click Ingest Manager>Fleet tab.
2. Notice that agent is displayed in Online status.
3. Click on "restart" link displayed next to agent service under "Service" window.
4. Notice that it will first stop the agent service and then will restart.
5. Navigate to "Activity log" page and observe that error appears.

**Test data**
N/A

**Impacted Test case id**
N/A 

**Actual Result**
Agent "restart" service gets crashed and error appears under "Agent activity log" page, when we restart the agent service (installed using PS1 command)

**Expected Result**
Agent should get successfully restarted and error should not appear under "Agent activity log" page, when we restart the agent service (installed using PS1 command)

**What's working**
N/A

**What's not working**
N/A

**Screenshot**
![CrashedOnRestart](https://user-images.githubusercontent.com/61860613/88640116-31320b80-d0db-11ea-92a8-1ab40e5cfb87.png)

**Activity Logs**

Timestamp | Type | Subtype | Message |  
-- | -- | -- | -- | --
Jul 28, 2020, 1:59:28 PM | State | Running | Application: metricbeat--7.9.0--36643631373035623733363936343635[487f1899-5fc0-4f6f-af1f-62a33733faa8]: State changed to DEGRADED: Missed last check-in |  
Jul 28, 2020, 1:59:27 PM | State | Starting | Application: metricbeat--7.9.0[487f1899-5fc0-4f6f-af1f-62a33733faa8]: State changed to RESTARTING: Restarting |  
Jul 28, 2020, 1:59:27 PM | Error | Failed | Application: metricbeat--7.9.0--36643631373035623733363936343635[487f1899-5fc0-4f6f-af1f-62a33733faa8]: State changed to CRASHED: exited with code: 1 |  
Jul 28, 2020, 1:59:27 PM | State | Starting | Application: metricbeat--7.9.0--36643631373035623733363936343635[487f1899-5fc0-4f6f-af1f-62a33733faa8]: State changed to STARTING: Starting |

**Comment by kamalpreetpahwa-qasource** [comment]
Please review and assign the defect @rahulgupta-qasource

**Comment by rahulgupta-qasource** [comment]
Reviewed and assigned to @EricDavisX

**Comment by michalpristas** [comment]
u think this should get fixed by work @blakerouse is doing - implementing service interface.

**Comment by EricDavisX** [comment]
please re-test this in BC5 - It has all of the expected fixes for persistence (which is what the service and powershell script relate to) thank you.

**Comment by kamalpreetpahwa-qasource** [comment]
Hi @Eric,

We have validated this issue on 7.9 BC5 environment with 7.9 agent on Windows 10 64 bit and 32 bit Host OS and found that issue is fixed.

**Observation:**

1. We observed that now Agent>start/stop/restart service (installed using PS1 command: ./install-service-elastic-agent.ps1) is working properly and no error appears under "Activity logs" page.

**Steps to be followed:**

1. Navigate to Endpoint security>Administration>Host tab.
2. Enroll the agent from Elastic endpoint security and then navigates to Fleet tab
3. Now click on Add agent button and fly out will appear.
4. Now for windows 02 commands are displayed.
    - to enroll the agent with token
    - to install the service
5. Then enroll the agent with first command having token in powershell.
6. Then run the PS1 command. ./install-service-elastic-agent.ps1
7. Now observe that service will start under Services window
8. Then stop the elastic-agent service and it will successfully get stopped and agent become offline.
9. Restart the service, it will first stop the service ans then start it again.

Screenshot :
![PS1_Restart](https://user-images.githubusercontent.com/61860613/89017002-460adb00-d337-11ea-9887-c0471a8005c2.png)

Hence, we are closing this issue.

Thanks,

**Comment by rahulgupta-qasource** [comment]
**Bug conversion:**

Testcase updated for this ticket:
https://elastic.testrail.io/index.php?/cases/view/15850
