### ISSUE TITLE
Support PRs to use PR ID in the artifact name

### ISSUE THREAD

**Issue by mdelapenya** [elastic/beats#20274]
When packaging a PR, the generated artifact is uploaded to a Google Cloud bucket with the name of the snapshot. We'd like to generate the artifact including the PR ID:

```diff 
- gs://beats-ci-artifacts/snapshots/elastic-agent-8.0.0-SNAPSHOT-linux-x86_64.tar.gz
+ gs://beats-ci-artifacts/pull-requests/elastic-agent-8.0.0-SNAPSHOT-${PR_ID}-linux-x86_64.tar.gz
```

cc/ @elastic/observablt-robots @ph @EricDavisX

**Comment by mdelapenya** [comment]
Revisiting the mage build tools, and to avoid refactoring it to support creating the packages with a different name, I think we can use another schema for the bucket layout:

```
gs://beats-ci-artifacts/pull-requests/pr-123/elastic-agent-8.0.0-SNAPSHOT-linux-x86_64.tar.gz
```

@kuisathaverat wdyt?

**Comment by ph** [comment]
@mdelapenya +1 for not changing the artifact names, the Elastic-Agent relies on that quite heavily and with the upgrade this will only increase. 

@michalpristas and @blakerouse for info.
