### ISSUE TITLE
Metricbeat Azure Module can't poll for compute_vm memory stats for Linux VMs

### ISSUE THREAD

**Issue by TheRiffRafi** [elastic/beats#20289]
- Version: 7.8
- Operating System: Generic Linux
- Steps to Reproduce: 

1.Start an Azure's Linux VM (better luck with ubuntu as currently CentOS or RedHat is having some trouble getting Azure's monitoring tools installed).
2. Install the monitoring add-on from Azure
3. Install metricbeat on the Azure Linux VM.
4. Configure all credentials and enable the Azure Module.
5. Enable the compute_vm metric set.
6. Install the kibana dashboards.
7. Let some metrics be captured, then go to Kibana.
8. Look at the [Metricbeat Azure] Compute VMs Overview dashboard.
9. Appreciate that there are no metrics for "VM Available Memory".
10. Be sad.

*Notes:*
1. The [Azure Kibana Dashboard Documentation](https://www.elastic.co/guide/en/beats/metricbeat/7.8/metricbeat-module-azure.html) does show some screenshots with both Linux and Windows VMs listed in the examples, but only the windows vm shows the data. However, it is not ever explicitly stated anyway that one *shouldn't* see VM memory metrics for Linux VMs. 
2. The [Compute_VM page in the Docs](https://www.elastic.co/guide/en/beats/metricbeat/7.8/metricbeat-metricset-azure-compute_vm.html) includes and example of the fields captured, and we can see them listed as:
```json
"memory_available_bytes": {
                "avg": 2951829094.4
            },
            "memory_cache_bytes": {
                "avg": 60126003.2
            },
            "memory_committed_bytes": {
                "avg": 8922399539.2
            },
            "memory_page_faults_per_sec": {
                "avg": 1484.2
            },
            "memory_pages_per_sec": {
                "avg": 6
            },
            "memory_pct_committed_bytes_in_use": {
                "avg": 82.4
            },
            "memory_pool_nonpaged_bytes": {
                "avg": 204028313.6
            },
            "memory_pool_paged_bytes": {
                "avg": 359613235.2
            }
```
But, there is still no mention that those aren't polled for Linux VMs. 

3. After doing some research, I've found that _maybe_ the compute_vm metricset at one point could report on memory usage for the VM being monitored, but Azure changed their "metrics" feature and released an "insights" dashboard which no longer exposes the memory usage as part of the compute_vm metric set. (interestingly enough, if one goes to Azure's console, and looks at the "Metrics" there is no mention of memory stats, but if one goes to the metric's "logs", azure DOES report on the vm memory, but for some reason one can't query that via [API](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftcomputevirtualmachines).
The memory is still reported, however, from metricbeat's own system.* metrics but that doesn't get populated on the dashboard.
Being that this seems to stem from a change that happened on azure, not sure if it should be a bug or a feature request?
Or if devs knew about this limitation already, maybe Doc update should be requested?

Thanks!

**Comment by narph** [comment]
@TheRiffRafi ,
The memory related metrics come from the guest namespace in that scenario.
The guest metrics are not available on linux vm's at the moment due to the fact that the Azure monitor data sink is only supported on Windows VMs , they do have a workaround found here https://github.com/MicrosoftDocs/azure-docs/issues/28457#issuecomment-524081288
At the moment those metrics are available only for windows machines and only when the guest vm namespace is supported by that resource.

**Comment by TheRiffRafi** [comment]
Thank you for the follow up @narph! 
The workaround specifies the install of a third party tool which doesn't help us much for the module. As it is not clear when the mem metrics will be supported for linux, perhaps a doc update would be a good idea. Another route would be to update the dashboard to read the mem values from the system.memory fields generated by metricbeat itself but that could be too much of a change for something that might fundamentally change in the future with Azure.

**Comment by narph** [comment]
@TheRiffRafi , indeed, this is a limitation on the Azure side.
Updating the dashboards is not a route we will take, the dashboards are specific to the azure metricset and I believe they should stay this way. Also, users will have to install Metricbeat on that specific vm in order to get the system metrics, whereas with the azure module this is not necessary.
I agree on some level of clarification regarding where these metrics are coming from, I will followup with a PR on doc.

**Comment by narph** [comment]
created https://github.com/elastic/beats/pull/20448 to add more info on the guest metrics, also replaced the event output to one supported by both Linux and windows vm's.

**Comment by narph** [comment]
PR's merged, will close the issue, feel free to reopen if you feel is necessary
