### ISSUE TITLE
Request for the Qualys Module in Filebeat

### ISSUE THREAD

**Issue by augustynd** [elastic/beats#20294]
I'd like to request a filebeat module for the Qualys vulnerability scan reports and user activity logs. 
- vulnerability scan reports
- user activity logs (page # 655) in the following document https://www.qualys.com/docs/qualys-api-vmpc-user-guide.pdf

**Comment by jamiehynds** [comment]
Hi @augustynd - thanks for raising the request. Support for vulnerability data is on our radar and we are currently working on experimental modules for [Nessus](https://www.elastic.co/guide/en/beats/filebeat/7.9/filebeat-module-tenable.html) and [Nexpose ](https://www.elastic.co/guide/en/beats/filebeat/7.9/filebeat-module-rapid7.html). 

While we aren't currently working on Qualys support, we'll certainly take the request onboard.

**Comment by tesla-consulting** [comment]
> I'd like to request a filebeat module for the Qualys vulnerability scan reports and user activity logs.
> 
> * vulnerability scan reports
> * user activity logs (page # 655) in the following document https://www.qualys.com/docs/qualys-api-vmpc-user-guide.pdf

https://github.com/tesla-consulting/qualysbeat/

**Comment by augustynd** [comment]
@jamiehynds do you have any updates on Qualys support?

**Comment by jamiehynds** [comment]
Hi @augustynd, thanks for the ping. Unfortunately, I don't have an update on an Elastic support Qualys module. It's something we continue to track demand for. However, there are some options available for Qualys ingestion. Have you tried the Qualysbeat developed by @tesla-consulting (linked above). [VulnWhisperer](https://github.com/HASecuritySolutions/VulnWhisperer) is also a popular option and supports Qualys.

**Comment by tesla-consulting** [comment]
Hi guys,
a new version of QualysBeat has been released! [QualysBeat_v2](https://github.com/tesla-consulting/qualysbeat/tree/QualysBeat_v2)
In this one you can choose the Qualys's API URL through qualysbeat.yml file. 

We're glad to help you 🙂 !
