### ISSUE TITLE
[Auditbeat][test failures] master branch got some test failures for the last few days

### ISSUE THREAD

**Issue by v1v** [elastic/beats#20303]
## Tests failures:
    
* **Name**: `Build and Test / Auditbeat x-pack / test_connected_udp_ipv4 – test_system_socket.Test`
* **Name**: `Build and Test / Auditbeat x-pack / test_connected_udp_ipv6 – test_system_socket.Test`
* **Name**: `Build and Test / Auditbeat x-pack / test_dns_enrichment – test_system_socket.Test`
* **Name**: `Build and Test / Auditbeat x-pack / test_dns_long_request – test_system_socket.Test`    
* **Name**: `Build and Test / Auditbeat x-pack / test_dns_udp_ipv6 – test_system_socket.Test`    
* **Name**: `Build and Test / Auditbeat x-pack / test_dns_unidirectional_udp – test_system_socket.Test`    
* **Name**: `Build and Test / Auditbeat x-pack / test_multi_udp_upv4 – test_system_socket.Test`    
* **Name**: `Build and Test / Auditbeat x-pack / test_no_dns_enrichment – test_system_socket.Test`    
* **Name**: `Build and Test / Auditbeat x-pack / test_tcp_ipv4 – test_system_socket.Test`    
* **Name**: `Build and Test / Auditbeat x-pack / test_tcp_ipv6_disabled – test_system_socket.Test`    
* **Name**: `Build and Test / Auditbeat x-pack / test_udp_ipv4 – test_system_socket.Test`    
* **Name**: `Build and Test / Auditbeat x-pack / test_udp_ipv6 – test_system_socket.Test`    
* **Name**: `Build and Test / Auditbeat x-pack / test_udp_ipv6_disabled – test_system_socket.Test`

## Logs

Log details: see https://gist.github.com/v1v/eca7ba76912013c85da7fb6f85cae459

### How to reproduce:

- Spinup an ubuntu-18 VM
- Run the below command
```bash
cd x-pack/auditbeat
mage update build test
```

**Comment by andrewkroh** [comment]
It looks like these tests are each failing with an error similar to:

`2020-07-29T10:11:00.925Z	ERROR	instance/beat.go:935	Exiting: 1 error: system/socket dataset setup failed: unable to delete existing KProbes. Is Auditbeat already running?: 19 errors: unable to remove kprobe 'p:auditbeat/sys_execve_call __x64_sys_execve path=+0(+0x70(%di)):u64 ... arg40=+248(+192(%si)):u64': write /sys/kernel/debug/tracing/kprobe_events: device or resource busy; unable to remove kprobe 'p:auditbeat/tcp_sendmsg_in tcp_sendmsg sock=%di size=%dx laddr=+4(%di):u32 lport=+776(%di):u16 raddr=+0(%di):u32 rport=+12(%di):u16 family=+16(%di):u16 laddr6a=+72(%di):u64 laddr6b=+80(%di):u64 raddr6a=+56(%di):u64 raddr6b=+64(%di):u64': write /sys/kernel/debug/tracing/kprobe_events: device or resource busy
`

I grabbed the logs from https://beats-ci.elastic.co/job/Beats/job/beats/job/master/142/artifact/x-pack-auditbeat--system-tests-linux.tgz.

**Comment by andrewkroh** [comment]
The machine that Auditbeat is testing on is already running Auditbeat with the system/socket metricset. This is causing a conflict with the tests.

**Comment by adriansr** [comment]
I think adding a parameter option to set the "group" name for the kprobes would allow multiple instances to coexist. It is currently hardcoded to "auditbeat". I should experiment in case there's other conflicts. WDYT @andrewkroh

**Comment by andrewstucki** [comment]
@adriansr that would likely be a nice feature, but I'm wondering--I'm assuming the group was hardcoded to make a best-effort to clean up any accidentally orphaned debugfs kprobe entries? Would the potential to do something like reconfigure the group and potentially leave orphaned entries be an issue?

**Comment by andrewkroh** [comment]
I like the idea. What would the "group" be? If the PID were incorporated into the name then would this facilitate cleanup or orphaned probes too? You could detected if the other groups were still "owned" a running auditbeat process.

**Comment by adriansr** [comment]
Orphaned entries aren't really a big problem afaik, as they are disabled once the controlling process dies. There doesn't seem to be a limit on disabled kprobes (I've tested with >10000 of them without trouble). So the cleanup is just to avoid cluttering `kprobe_events`.

Actually adding the PID to the group makes sense. Created #20325 with this change.
