### ISSUE TITLE
Support PRs to use PR ID in the docker images pushed to our docker registry

### ISSUE THREAD

**Issue by mdelapenya** [elastic/beats#20317]
When packaging a PR, the generated docker image is pushed to our docker registry with the name of the snapshot. We'd like to generate the docker image including the PR ID:

```diff 
- def newName = "${DOCKER_REGISTRY}/observability-ci/${name}:${libbetaVer}"
- def commitName = "${DOCKER_REGISTRY}/observability-ci/${name}:${env.GIT_BASE_COMMIT}"
+ def newName = "${DOCKER_REGISTRY}/observability-ci/${name}:${PR_ID}-${libbetaVer}"
+ def commitName = "${DOCKER_REGISTRY}/observability-ci/${name}:${PR_ID}-${env.GIT_BASE_COMMIT}"
```

cc/ @elastic/observablt-robots @ph @EricDavisX

**Comment by mdelapenya** [comment]
I'm thinking about the proposed name, and I could see two different choices:

1. def newName = "${DOCKER_REGISTRY}/observability-ci/${name}:${libbetaVer}"
1. def newName = "${DOCKER_REGISTRY}/observability-ci/${name}/${PR_ID}:${libbetaVer}"

The first one adds the PR-ID to the tag, and the second one adds it to the namespace. I like the second one as it preserves the tag name structure, so it's easier to identify the tag.

Which one do you prefer?

**Comment by ph** [comment]
I like option 2.

**Comment by mdelapenya** [comment]
Adding @kuisathaverat's comments for context: https://github.com/elastic/beats/pull/20323#discussion_r462429228

**Comment by mdelapenya** [comment]
What he suggests is a third option:

3. def newName = "${DOCKER_REGISTRY}/observability-ci/${name}:${PR_ID}

I like this option the most
