### ISSUE TITLE
[FileBeat] Illegal escape characters for include/exclude_lines (escaping [ and ])

### ISSUE THREAD

**Issue by boeboe** [elastic/beats#2031]
It is impossible to use literal chars '[' and ']' in the regex for include_lines and exclude_lines:

Example logline to include (starting with a space):

`<space>[some_key] <<"{\"lotId\":12786,\"amount\":20,\"timestamp\":1468339147905}">>` 

**filebeat.yml** extract, escaping the '[' and ']' characters:

`include_lines: ["^ \[some_key\] <<"]`

Errors occur when checking filebeat configuration file, that point to the escaped '[' character:
`# filebeat -configtest -e`

FileBeat Version: 1.2.3
Operating System Ubuntu LTS 16.04

**Comment by urso** [comment]
Escaping + YAML is fun. When defining regexes in beats configs (YAML), use single quotes. With double quotes a string would be processed by the YAML parser (applying escape), and then the string is processed again by the regex parser (not finding already processed escape anymore). One either has to escape the escape, or better use single quotes.

This is a quite old issue + questions like this will normally get more attention on discuss.elastic.co . I'm closing this. Feel free to reopen if it is a bug.
