### ISSUE TITLE
Remove unnecessary restarts of metricsets while using Pod/Service autodiscover

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#20311]
**Describe the enhancement:**
Improve update checks for `pod` and `service` resources to avoid having  unnecessary restarts of metricsets.
Similar to https://github.com/elastic/beats/pull/19974.

**Comment by ChrsMark** [comment]
I did some first investigation for this and it looks like Pods (and most probably services)  are properly handled on Updates: https://github.com/elastic/beats/blob/bcb4e0c9c314f04cee3efcc20e7064169ca76616/libbeat/autodiscover/providers/kubernetes/pod.go#L140

I also added debug messages to observe the updates and I didn't catch any update that we don't handle properly and can cause unnecessary restarts. I think that we are ok with the current state.

@jsoriano do you have any ideas around this? Otherwise we can close it.

**Comment by jsoriano** [comment]
> I did some first investigation for this and it looks like Pods (and most probably services) are properly handled on Updates:
> 
> https://github.com/elastic/beats/blob/bcb4e0c9c314f04cee3efcc20e7064169ca76616/libbeat/autodiscover/providers/kubernetes/pod.go#L140
> 
> I also added debug messages to observe the updates and I didn't catch any update that we don't handle properly and can cause unnecessary restarts. I think that we are ok with the current state.
> 
> @jsoriano do you have any ideas around this? Otherwise we can close it.

Yep, I am ok with closing this, thanks for the investigation.
