### ISSUE TITLE
[Ingest Manager] RHEL 6.10 Agent (and others) install but comms / policy fail with Endpoint

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#20331]
[Ingest Manager] RHEL 6.10 Agent installs but comms fail with Endpoint
 - https://github.com/elastic/integrations-dev/issues/22 it is cited as supported from Elastic, version 6.5 and up.

Update:  I'm seeing somehow the same thing with most other BC4 Linux agents that are deployed to this server - Centos7, Ubuntu 18, RHEL 7.3
and also the same with Centos 6.4, tho this one is below the version requirement so I would expect potential problems, or maybe for it to be prevented from running if its not supported?

- Steps to Reproduce: 
deploy Centos 6.10 on the latest 7.9 (BC4 is available now) and configure it with Endpoint.  this is when the issues start.  It seems Agent is running, but it reports a comms failure with Endpoint.  It seems that Endpoint started running, at least, and may be in fact started - but with a bad / wrong config.  

I'm seeing the same thing with RHEL 8 on an Endgame vSphere system, logs look remarkably similar in the UI so I'm not yet attaching.

screenshots:
[elastic-agent-rhel.yml.txt](https://github.com/elastic/beats/files/4998416/elastic-agent-rhel.yml.txt)
<img width="978" alt="Screen Shot 2020-07-29 at 10 07 40 PM" src="https://user-images.githubusercontent.com/12970373/88873346-78f38880-d1ea-11ea-9ba6-05f9fa6f8ccb.png">
<img width="636" alt="Screen Shot 2020-07-29 at 10 07 11 PM" src="https://user-images.githubusercontent.com/12970373/88873348-78f38880-d1ea-11ea-9f76-968399210c87.png">
<img width="986" alt="Screen Shot 2020-07-29 at 10 06 59 PM" src="https://user-images.githubusercontent.com/12970373/88873349-78f38880-d1ea-11ea-89a6-8cb225c3dfb7.png">
<img width="1450" alt="Screen Shot 2020-07-29 at 10 05 03 PM" src="https://user-images.githubusercontent.com/12970373/88873350-798c1f00-d1ea-11ea-8d93-19fd6aa0896f.png">
<img width="376" alt="Screen Shot 2020-07-29 at 10 04 38 PM" src="https://user-images.githubusercontent.com/12970373/88873353-798c1f00-d1ea-11ea-8ce8-fe420edccf17.png">

**Comment by EricDavisX** [comment]
I need to sync up with charlie and see how he deployed this environment's linux hosts.  @charlie-pichette did you remember to use 'sudo' with the linux boxes?

**Comment by charlie-pichette** [comment]
Yes.  I used sudo.  However I did not deploy to RHEL 6.10.

**Comment by blakerouse** [comment]
Please include the steps take to run on Agent on the host. Is the Agent running as a service under systemd or is it running from a bash shell?

**Comment by EricDavisX** [comment]
I got some cross-contamination with my screen shots, I appreciate the clarification Charlie.  Both of those are supported so it should have worked I believe.  

The deploy was a bash shell without the service installed (it was a .tar.gz) deploy.  I'm hoping to re-test this... something must have been off somehow, for so many (all I think?) of the Linux boxes to go to a Failed policy.  Maybe its a known issue on the Endpoint side about artifact download.  Which would explain why one started and then shortly after all would fail, since they were deployed individually, but in a quick sequence.

**Comment by charlie-pichette** [comment]
The Linux tar.gz file was used for the agent.  A bash shell script containing the elastic-agent commands was executed using sudo on the host in an interactive terminal.  The shell script was:
```
#!/bin/bash
./elastic-agent enroll https://f0678a411ca749338936731de2fba514.europe-west1.gcp.cloud.es.io:443 RE9OSm0zTUI5VGJiem05b3dxUHY6ZjdDdGItQ1NRWDZ1SjFYemphQ1BwUQ== -f --staging 312096d7
./elastic-agent run
```

**Comment by EricDavisX** [comment]
we have successfully set up all of the Linux hosts we expected to, with the BC 5 build - tho some do not support .deb / .rpm or persistent usage as they are too old and do not meet the requirements the code expects for system components.  I'm not going to log those separately - I'd like to close this as a combination of poorly doc'ed steps on my side, minimally incorrect usage, and needing new bug fixes that we have since gotten.

7.9 BC 5 look good and is being documented as such, with any nuances from the noted above support that older systems don't have.  closing this out.
