### ISSUE TITLE
[Kafka output] Detect Kafka leader changes sooner to resume writing

### ISSUE THREAD

**Issue by inqueue** [elastic/beats#20358]
**Describe the enhancement:**  Filebeat should notice sooner when the Kafka leader changes. Currently, 10 minutes will elapse before Filebeat notices a leader change as controlled by `metadata.refresh_frequency`. Change the defaults for this configuration so Filebeat can resume writing when a leader goes down.

**Describe a specific use case for the enhancement or feature:**

Please (re)consider reasonable defaults for how often Filebeat should refresh Kafka metadata. In the case of performing maintenance on a Kafka cluster by taking one Kafka broker down at a time, it is expected events will continue to flow when Kafka has already declared a follower partition to be the new leader-- everything is good on the Kafka side. Filebeat should detect this change sooner than later to prevent lag.

**Comment by faec** [comment]
Hi, can you give more details for how this behavior is produced? The default refresh frequency may be 10 minutes, but the Kafka output should immediately refresh the Kafka metadata on a failed write -- if the lead broker goes down while a Beat is writing, then it should be updated immediately. Do you have a configuration where this isn't happening?

**Comment by inqueue** [comment]
The user noted their Kafka cluster was not down, but had incurred rolling broker restarts where partitions were assigned a new leader. Filebeat did not detect the leader change in a desirable time period. They also noted the Logstash Kafka output does not appear to have the issue. Decreasing `metadata.refresh_frequency` resolved the issue.

**Comment by faec** [comment]
Additional context: the original observation for this report was using Filebeat 7.0.2.

**Comment by faec** [comment]
We've never managed to reproduce this issue or seen it reported after 7.0 -- closing absent any fresh reports
