### ISSUE TITLE
console output: check stdout being available

### ISSUE THREAD

**Issue by urso** [elastic/beats#2035]
Check stdout being available when init the console output. Return error and quit beat if check fails.

**Comment by andrewkroh** [comment]
From urso: https://play.golang.org/p/OOiCvQuYB1

**Comment by inqueue** [comment]
The error looks like this when beats is running as a service where there is no stdout:
```
Jul 14 14:51:02 grok /usr/bin/filebeat[22191]: log.go:113: Harvester started for file: /var/log/nginx/error.log
Jul 14 14:51:04 grok /usr/bin/filebeat[22191]: output.go:92: Error bulk publishing events: write /dev/stdout: invalid argument
```
