### ISSUE TITLE
[Ingest Management]: Agent logs and metrics data is not displayed under 'Datasets' tab if enrolled agent 7.8 on 7.9 BC 5 cloud environment

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#20398]
**Kibana version:**
Kibana: 7.9 BC5

**Elasticsearch version:**
Elasticsearch: 7.9 BC5

**Host OS and Browser version:**
Windows 10, All

**Original install method (e.g. download page, yum, from source, etc.):**
From 7.9 BC5

**Description**
[Ingest Management]: Agent logs and metrics data is not displayed under 'Datasets' tab if enrolled agent 7.8 on 7.9 BC 5 cloud environment

**Preconditions**
1. 7.9 Kibana BC5 cloud environment should be available.
2. 7.8 Elastic Agent should be enrolled under Fleet tab (say with Default configuration).
3. Collect agent logs, Collect agent metrics checkboxes must be enabled in Default configuration.

**Steps to Reproduce**
1. Open the Kibana 7.9 BC5 cloud environment in browser, then click Ingest Manager.
2. Click on Datasets tab.
3. Observe that 7.8 Elastic agent logs and metrics data is not displayed.

**Test data**
N/A

**Impacted Test case id**
N/A

**Actual Result**
[Ingest Management]: Agent logs and metrics data is not displayed under 'Datasets' tab if enrolled agent 7.8 on 7.9 BC 5 cloud environment

**Expected Result**
[Ingest Management]: 7.8 Elastic agent logs and metrics data should be displayed under 'Datasets' tab if enrolled on 7.9 Kibana.

**What's working**
 - Issue is not occurring if 7.9 Elastic agent is enrolled 7.9 Kibana.

**What's not working**
 - Data for integrations added under 7.8 elastic agent configuration is also not displayed under 'Datasets' tab if enrolled on 7.9 Kibana

**Screenshot**
![image](https://user-images.githubusercontent.com/59917944/89177977-3810c080-d5aa-11ea-8298-3b442451f332.png)

**Logs**
N/A

**Comment by rahulgupta-qasource** [comment]
@kamalpreetpahwa-qasource  Please review the bug.

**Comment by kamalpreetpahwa-qasource** [comment]
Reviewed and Assigned defect to @EricDavisX

**Comment by EricDavisX** [comment]
I don't know if this is supported - 7.8 Agent and 7.9 Kibana had a lot of changes... we generally intend to support current-minus-1 versions as such, but this may be a bad example since its from Alpha to Beta.  Even the Beta 1 may not work well with the Beta 2, time will tell. 

@blakerouse just confirming, 7.8 Agent isn't going to work with 7.9 right?  If so, we can close this and hold off on this testing for now

**Comment by blakerouse** [comment]
@EricDavisX Current we intend to support current-minus-1 so the upgrade of the stack can occur first, then the upgrade of the Agents. There is a lot of breaking changes in 7.9, so support of 7.8 Agent on 7.9 is not something we are supporting, yet!

**Comment by EricDavisX** [comment]
agree - lets call this done for now and we can plan tests for 7.9 to 7.10

**Comment by rahulgupta-qasource** [comment]
**Bug Conversion:**

Test-Case not required for this Ticket as 7.8 Agent is not supported on 7.9

**Comment by EricDavisX** [comment]
@rahulgupta-qasource lets add a test for it, and make it generic - Agent of "kibana version minus 1" should be able to connect and be enrolled anew and function fully.

**Comment by rahulgupta-qasource** [comment]
Hi @EricDavisX

Thank you for the feedback.

We have created **01** generic testcase for the same:-
https://elastic.testrail.io/index.php?/cases/view/22509

Please review and let us know if anything is missing from our end.
