### ISSUE TITLE
Start-Service fails with Elastic Agent on windows.

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#20404]
For confirmed bugs, please report:
- Version: 7.9-SNAPSHOT
- Operating System: Windows Server 2016
- Discuss Forum URL:
- Steps to Reproduce: 
  - Download the latest 7.9 BC
  - enroll a new agent via the Kibana interface
  - Run the ps1 installer script as directed by the Kibana UI.

So, if you run the PS1 installer script included with the download, you get this error:
```
Start-Service : Service 'elastic-agent (elastic-agent)' cannot be started due to the following error: Cannot start service elastic-agent on computer '.'.
At line:1 char:1
+ Start-Service -name elastic-agent
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand
```

I found more details in the windows event-log:

```
Log Name:      System
Source:        Service Control Manager
Date:          7/31/2020 12:33:45 PM
Event ID:      7009
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      vagrant
Description:
A timeout was reached (30000 milliseconds) while waiting for the elastic-agent service to connect.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" />
    <EventID Qualifiers="49152">7009</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2020-07-31T19:33:45.241879700Z" />
    <EventRecordID>2245</EventRecordID>
    <Correlation />
    <Execution ProcessID="560" ThreadID="1828" />
    <Channel>System</Channel>
    <Computer>vagrant</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="param1">30000</Data>
    <Data Name="param2">elastic-agent</Data>
    <Binary>65006C00610073007400690063002D006100670065006E0074000000</Binary>
  </EventData>
</Event>
```

I confirmed via `Get-Service` that the service in installed, but I can't really get any farther than that. Alas, my Windows knowledge is fairly limited.

**Comment by fearful-symmetry** [comment]
Also, confirmed that @narph is running into this as well.

**Comment by blakerouse** [comment]
Which BC build are you using? Can you provide the complete steps taken? Can you provide the output of `elastic-agent.log`?

**Comment by fearful-symmetry** [comment]
Bah, sorry for the missing detail @blakerouse. This is BC5. After unpacking the zipfile, I ran the commands from the kibana fleet UI:

```
./elastic-agent enroll [url] [hash]
./install-service-elastic-agent.ps1
```

There really weren't that many steps. The enroll part completed without issue. There's no log files either, other than what's in the windows event logs. The failure is in this part of the `install-service-elastic-agent.ps1` script:

```
# Start the new service.
Start-Service -name elastic-agent
```

The actual agent itself never starts.

**Comment by blakerouse** [comment]
@fearful-symmetry I believe BC5 still was broken. Can you try BC6?

**Comment by fearful-symmetry** [comment]
I'm _still_ running into issues. @blakerouse  On BC6, the PS1 installer works, but the `enroll` command just hangs indefinitely until you ctrl+break out of it.

```
PS C:\Users\vagrant\Downloads\elastic-agent-7.9.0-windows-x86_64\elastic-agent-7.9.0-windows-x86_64> .\elastic-agent.exe -v enroll [url] [key]



The Elastic Agent is currently in BETA and should not be used in production
```

Tried this on both the oblt test server and a local docker test env.

**Comment by blakerouse** [comment]
Are you sure that you didn't accidentally highlight some text in the terminal, that will cause the terminal to pause the application. I have not ever ran into that issue and I enroll on Windows multiple times a day.

**Comment by narph** [comment]
The BC6 version looks good to me as well, I was able this time to start the service (testing on Windows 10).
Enrolling was not an issue as well.
@fearful-symmetry do you see anything in the agent logs that might shed some light?
Have you first started the service and then tried to enroll instead? 
What os version version are you testing on?

**Comment by fearful-symmetry** [comment]
If @narph can get it running, I'm assuming everything is fine and I'm just dumb. There's nothing in the logs, it look like the enroll step is just hangning this time.

This is windows 10 in a VM.

```
CsUserName                                              : VAGRANT\vagrant
CsWakeUpType                                            : PowerSwitch
CsWorkgroup                                             : WORKGROUP
OsName                                                  : Microsoft Windows Server 2019 Datacenter Evaluation
OsType                                                  : WINNT
OsOperatingSystemSKU                                    : 80
OsVersion                                               : 10.0.17763
```

**Comment by fearful-symmetry** [comment]
Okay, tried installing the service first. Still no dice.

**Comment by russcam** [comment]
This type of error happens when a service fails to notify the Service Control Manager within a specified timeout (default is 30 seconds) that it is ready. 

Whilst [the service timeout can be increased by editing the registry](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc756342(v=ws.10)?redirectedfrom=MSDN), a common approach in attempting to mitigate this type of error is to perform any potential long running startup operations on a separate thread, to allow the main thread to notify SCM it is ready in a prompt fashion.

**Comment by alexfrangissonos** [comment]
I can confirm I'm seeing this as well on 7.9 release. The elastic-agent binary doesn't seem to report to windows that it has started, preventing the install ps1 script from concluding.

The agent does start, and it spawns integrations and starts to report data. I'd second russcam this seems like an issue of sending this signal to windows on time.

**Comment by xhofk00** [comment]
Hello,

yes, it really doesn´t work. I found a way to run the elastic agent in a different way:

1. ./install-service-elastic-agent.ps1
2. open app Services, there should be newly added 'elastic-agent'. Status of 'elastic-agent' is Stopped.
3. restart computer
4. open app Services. Status of 'elastic-agent' is Running
5. enroll agent '.\elastic-agent enroll http://localhost:5601 xxxxxxxxxxxxxxxx --insecure'
6. ./install-service-elastic-agent.ps1
7. now you should have active agent in Kibana Fleet

It works for me. Hope it will help you.

**Comment by EricDavisX** [comment]
I appreciate the work-arounds posted.  we're refactoring the install of Agent and hope it will alleviate the pain - @blakerouse do we have any comment about whether we had explicitly covered the race-condition / timing that was noted above https://github.com/elastic/beats/issues/20404#issuecomment-674719037 ?

**Comment by blakerouse** [comment]
@EricDavisX Yes the new install command should solve this issue.

**Comment by alvarolobato** [comment]
Did we get to the bottom of this issue?
I'm seeing this issue or a similar one with 7.13.

These are the steps I followed in Windows 10:
 - Download the agent
 - Run the enroll command
 - The agent will enroll successfully and stay in an "updating" state, it won't move from there
```
C:\Users\XXXX\Downloads\elastic-agent-7.13.0-windows-x86_64>.\elastic-agent.exe install -f --url=https://6b744b5715d84795bd1e89dc17bbe068.fleet.eu-west-1.aws.found.io:443 --enrollment-token=TUVqNXRIa0J4TENCejVWcXdqcG86VTZaYUVTdWpSX3ExbUFXeTlPT2IzZw==
The Elastic Agent is currently in BETA and should not be used in production

2021-05-29T05:04:41.693+0200    INFO    cmd/enroll_cmd.go:201   Elastic Agent might not be running; unable to trigger restart
2021-05-29T05:04:41.701+0200    INFO    cmd/enroll_cmd.go:203   Successfully triggered restart on running Elastic Agent.
Successfully enrolled the Elastic Agent.
Elastic Agent has been successfully installed.
```
- If I go to services, the service has been installed but it's not running.
- If I try to run it it will terminate unexpectedly with error 1067

There are no logs in the agent's folder with the exception of a new elastic-agent-<TIMESTAMP> file which is created every time I try to start the service, that only contains this line:
```
 2021-05-29T05:10:45.146+0200	ERROR	cmd/watch.go:61	failed to load markeropen C:\Program Files\Elastic\Agent\data\.update-marker: El sistema no puede encontrar el archivo especificado.
```

If I run the agent from the command line it works correctly and the status in Kibana changes to healthy

```
2021-05-29T05:14:47.263+0200	INFO	warn/warn.go:18	The Elastic Agent is currently in BETA and should not be used in production
2021-05-29T05:14:47.281+0200	INFO	application/application.go:68	Detecting execution mode
2021-05-29T05:14:47.287+0200	INFO	application/application.go:93	Agent is managed by Fleet
2021-05-29T05:14:47.289+0200	INFO	capabilities/capabilities.go:59	capabilities file not found in C:\Program Files\Elastic\Agent\capabilities.yml
2021-05-29T05:14:48.085+0200	INFO	[composable]	composable/controller.go:46	EXPERIMENTAL - Inputs with variables are currently experimental and should not be used in production
2021-05-29T05:14:48.225+0200	INFO	[composable.providers.docker]	docker/docker.go:43	Docker provider skipped, unable to connect: protocol not available
2021-05-29T05:14:48.233+0200	INFO	[api]	api/server.go:62	Starting stats endpoint
2021-05-29T05:14:48.233+0200	INFO	application/managed_mode.go:291	Agent is starting
2021-05-29T05:14:48.233+0200	INFO	[api]	api/server.go:64	Metrics endpoint listening on: \\.\pipe\elastic-agent (configured: npipe:///elastic-agent)
2021-05-29T05:14:48.345+0200	WARN	application/managed_mode.go:304	failed to ack update open C:\Program Files\Elastic\Agent\data\.update-marker: El sistema no puede encontrar el archivo especificado.
2021-05-29T05:14:50.299+0200	INFO	stateresolver/stateresolver.go:48	New State ID is VoHXoJOY
2021-05-29T05:14:50.299+0200	INFO	stateresolver/stateresolver.go:49	Converging state requires execution of 3 step(s)
2021-05-29T05:14:55.086+0200	INFO	cmd/run.go:189	Shutting down Elastic Agent and sending last events...
2021-05-29T05:14:55.086+0200	INFO	operation/operator.go:191	waiting for installer of pipeline 'default' to finish
2021-05-29T05:15:03.393+0200	ERROR	status/reporter.go:236	Elastic Agent status changed to: 'error'
2021-05-29T05:15:03.393+0200	ERROR	fleet/fleet_gateway.go:180	failed to dispatch actions, error: operator: failed to execute step sc-run, error: context canceled: context canceled
2021-05-29T05:15:03.393+0200	INFO	process/app.go:176	Signaling application to stop because of shutdown: filebeat--7.13.0
2021-05-29T05:15:03.405+0200	INFO	application/managed_mode.go:320	Agent is stopped
2021-05-29T05:15:03.406+0200	INFO	cmd/run.go:197	Shutting down completed.
2021-05-29T05:15:03.415+0200	INFO	[api]	api/server.go:66	Stats endpoint (\\.\pipe\elastic-agent) finished: use of closed network connection

```

**Comment by fearful-symmetry** [comment]
If I remember correctly, this was an issue with the installer on windows that magically went away during a subsequent BC-- @alvarolobato you might want to file a new issue.

**Comment by alvarolobato** [comment]
ok, I'll do that. 
Should we close this one then?

**Comment by fearful-symmetry** [comment]
Yep, I can close it.
