### ISSUE TITLE
Please Backport PR #13356  "Add container image in Kubernetes metadata" to 6.8.x 

### ISSUE THREAD

**Issue by westwind-sc** [elastic/beats#20429]
Hello, 

We found `kubernetes.container.image` in the 6.8.x doc https://www.elastic.co/guide/en/beats/filebeat/6.8/exported-fields-kubernetes-processor.html
But while using it, the container image not reported as part of Kubernetes metadata.
We found the PR #13356 fixed it in v7.4.0. Could you backport the fix to 6.8.x?

**Comment by jsoriano** [comment]
Hey @westwind-sc,

Thanks for opening this request, but this change is considered and enhancement, and we only backport bugfixes to released branches. We didn't even backport this change to other 7.x releases.
The documentation can be a bit confusing for this field, we document all kubernetes fields in a single place, and the `kubernetes.container.image` field was already available in other places, as in the `state_container` metricset. Depending on your use case you could use this metricset to collect this field.
If you want to have this field in logs collected by Filebeat I am afraid that the only solution would be to upgrade to 7.4 :slightly_frowning_face: 

I am going to close this issue as I don't expect this is something that we are going to add to 6.8.x.
