### ISSUE TITLE
Give Winlogbeat the capability to grab logs that are written to log files.

### ISSUE THREAD

**Issue by A-Hall** [elastic/beats#20433]
**Describe the enhancement:**  

Give Winlogbeat the ability to read and parse log files on Windows systems, similar to Filebeat.  

**Describe a specific use case for the enhancement or feature:**

Some logs are not written to the Windows Event Logs, such as the [Windows Defender firewall logs](Give Winlogbeat the capability to grab some logs that are written to log files.).  It would be nice if a single Beat endpoint could handle all of the Windows logs, including the ones that are not written to the Event Logs.

**Comment by andrewkroh** [comment]
This is not a feature that's on the Winlogbeat roadmp. But being able to read the Windows event logs is something that Filebeat will be able to accomplish (see https://github.com/elastic/beats/pull/19622) as we consolidate all of the log reading features into it.
