### ISSUE TITLE
what is the meaning about filebeat metric?

### ISSUE THREAD

**Issue by lwx294821** [elastic/beats#20436]
![image](https://user-images.githubusercontent.com/28983979/89359595-c98e4880-d6f8-11ea-8278-d37fc652efde.png)

**Comment by kaiyan-sheng** [comment]
Hi @lwx294821, thanks for creating this issue. But we would kindly ask you to post all questions and issues on https://discuss.elastic.co/c/beats before opening a Github Issue. Your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue or open a new one with more details. Thanks in advance!
