### ISSUE TITLE
Beats cant send data suddenly to ES with errors pop up

### ISSUE THREAD

**Issue by kan1207** [elastic/beats#2049]
I am using ES 5.0, Kibana 5.0 alpha4 and various beats to send data to ES. Everything runs fine and smooth at first. However, after a day, the beats suddenly cannot send the beats to the ES. I have been using different bearts, including winlogbeat, metribeats, etc. All of them suddenly stop working.

Error is as shown

    2016/07/16 15:22:15.259659 single.go:130: INFO Connecting error publishing events (retrying): 401 Unauthorized
    2016/07/16 15:22:15.259695 single.go:145: INFO send fail

What would be the issues?

**Comment by ruflin** [comment]
Closing this issue in favor of https://discuss.elastic.co/t/beats-cant-send-data-suddenly-to-es-with-errors-pop-up/55668 until we have a confirmed bug. Please do not double post.
