### ISSUE TITLE
Important settings missing from MISP module documentation

### ISSUE THREAD

**Issue by softengchick** [elastic/beats#20524]
The online documentation for the FIlebeat - MISP module is missing several key variables.  They are not listed in the misp.yml either, which caused us to have to go to the source to figure out how to use it.  The most important one for us missing was var.interval and the lack of understanding that the module would poll once and never again by default.

Missing:
var.interval
var.ssl
var.http_method
var.http_client_timeout
var.http_headers
var.http_request_body
var.pagination

As mentioned above, these are actually missing from the misp.yml as well.  Would be great to have this corrected to save folks a bit of time digging.

 @dedemorton

**Comment by markwalkom** [comment]
FYI this came up in https://discuss.elastic.co/t/filebeat-misp-module-refresh/256281, specifically around the `var.interval` and the "poll once" appearance.

**Comment by hilt86** [comment]
@softengchick does the var.interval use standard elastic date notation, i.e: 60m = 60 minutes?

**Comment by softengchick** [comment]
@hilt86 - You have likely figured this out by now, but yes, if I recall correctly it does.  Sorry for delayed response.

**Comment by amemkdm** [comment]
@softengchick is there a way to not import attributes which are already imported? Right with every run  it imports the same one all over again.

**Comment by softengchick** [comment]
@amemkdm  - I am going  to move this discussion back to the discuss forum mentioned above.

**Comment by hilt86** [comment]
@markwalkom how can I help get this done?

**Comment by markwalkom** [comment]
@hilt86 I will defer to the Beats team for the best way to handle that :)
