### ISSUE TITLE
Documents beats testing for developers

### ISSUE THREAD

**Issue by urso** [elastic/beats#2052]
[Related discussion including some testing details](https://discuss.elastic.co/t/how-to-test-my-beat-output/55449)

With libbeat being mostly targeted for developers, maybe it makes sense to have a separate beats-developer documentation instead of some guide here and there?

**Comment by dedemorton** [comment]
@urso This one has been open for awhile. Is this work still required?

**Comment by urso** [comment]
Let's keep it open. I checked the current docs. While we show how to create a module/beat, there is no documentation helping users in testing their creations.

**Comment by fearful-symmetry** [comment]
Currently working on this as part of #12105

**Comment by dedemorton** [comment]
Looks like this issue is resolved in https://github.com/elastic/beats/pull/12105, so I'm closing it.
