### ISSUE TITLE
Winlogbeat fails to export index-pattern with migration.6_to_7 enabled

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#20521]
For confirmed bugs, please report:
- Version: 7.8.1 (reported since 7.4.0)
- Operating System: -
- Discuss Forum URL: https://discuss.elastic.co/t/winlogbeat-error-during-setup/244093
- Steps to Reproduce: 

Run:

> winlogbeat export index-pattern -E migration.6_to_7.enabled=true

It fails with:

> Error generating Index Pattern: field <user.domain> is duplicated.

**Comment by andrewkroh** [comment]
Let's add a new system test case to check the `export index-pattern` with `migration.6_to_7.enabled=true`.
