### ISSUE TITLE
Monitoring goes to Standalone Cluster until elasticsearch output used

### ISSUE THREAD

**Issue by softengchick** [elastic/beats#20529]
Using Filebeat with Suricata module, elasticsearch output was configured, monitoring section only contains monitoring enabled setting.  When you first start Filebeat all the monitoring data came through with no cluster_uuid, but once we started suricata traffic, the beats all started reporting with the cluster_uuid properly filled.  We saw the same behavior with zeek module setup.  NOt the end of the world, but a bit annoying to the team (Air Force CVAH).  Manually setting the monitoring uuid is a bit of work for them as they create everything when the kit is deployed and would have to add a process to find the cluster_uuid and set up a variable.   I'll get the configs used tomorrow and add them.

*they do use ECK operator and kubernetes to deploy everything for the CVAH kit.

Beats Version: 7.8.1 & 7.7.1

**Comment by ycombinator** [comment]
Duplicate of #18669.
