### ISSUE TITLE
Finalize release related docs for 7.9

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#20528]
In preparation for 7.9, we need to finalizes the release-related docs. Specifically, we need to:

- [x] Clean up 7.9 release notes: https://www.elastic.co/guide/en/beats/libbeat/7.9/release-notes-7.9.0.html
- [x] [DeDe] Add content to the "What's new" topic (previously called "Release highlights): https://www.elastic.co/guide/en/beats/libbeat/7.9/whats-new.html PR: https://github.com/elastic/beats/pull/20618
- [x] [DeDe] Identify any serious breaking changes that we want to highlight here: https://www.elastic.co/guide/en/beats/libbeat/7.9/breaking-changes.html PR: https://github.com/elastic/beats/pull/20595
- [x] [DeDe] Quick edit of the release notes to remove empty sections. PR: https://github.com/elastic/beats/pull/20619

Here are the queries I've used in the past to find items for the release docs, but they aren't returning much (mostly nothing). Someone needs to assign the appropriate labels or add a comment to this issue to let me know what to highlight.

What’s new (aka Release highlights):
https://github.com/elastic/beats/issues?q=sort%3Aupdated-desc+label%3Av7.9.0+-label%3A%22breaking+change%22+label%3Arelease-highlight+

Breaking changes: https://github.com/elastic/beats/issues?q=sort%3Aupdated-desc+label%3Av7.9.0+label%3A%22breaking+change%22

Breaking changes we should highlight: https://github.com/elastic/beats/issues?q=sort%3Aupdated-desc+label%3Av7.9.0+label%3A%22breaking+change%22+label%3Arelease-highlight+

**Comment by fearful-symmetry** [comment]
The Elastic Log Driver supports `docker logs` now, which is one thing.
