### ISSUE TITLE
[Ingest Management]: Activity logs show 'Error' but Agent remains in 'Offline' status on adding 'Elastic Endpoint Security' to agent configuration without endpoint-security zip and sha files

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#20534]
**Kibana version:**
Kibana: 7.9 BC8

**Elasticsearch version:**
Elasticsearch: 7.9 BC8

**Host OS and Browser version:**
Windows 10, All

**Original install method (e.g. download page, yum, from source, etc.):**
From 7.9 BC8 artifacts page

**Description**
Activity logs show 'Error' but Agent remains in 'Offline' status on adding 'Elastic Endpoint Security' to agent configuration without endpoint-security zip and sha files while enrolling the agent.

**Note**: We need to get the agent into 'Error' state for validating count of agents in Error state in Telemetry json.

**Preconditions**
1. 7.9 BC8 Kibana cloud environment should be available.

**Steps to Reproduce**
1. Open the Kibana 7.9 BC8 cloud environment in browser, then click Ingest Manager.
2. Click on 'Configurations' tab -> Default config.
3. Click on 'Add Integration' -> 'Elastic Endpoint Security' and click on Save button.
4. **Do not place endpoint-security zip and sha files in Elastic Agent data/downloads location**.[This step is important to reproduce this issue]
5. Click on Fleet tab and Enroll the agent on Windows 10 64bit environment.
6. Click on Host to view the activity logs.
7. Observe that activity logs shows Type 'Error' but agent status is Offline.

**Test data**
N/A

**Impacted Test case id**
https://elastic.testrail.io/index.php?/cases/view/15840
https://elastic.testrail.io/index.php?/cases/view/15842

**Actual Result**
Activity logs show 'Error' but Agent remains in 'Offline' status on adding 'Elastic Endpoint Security' to agent configuration without endpoint-security zip and sha files while enrolling the agent

**Expected Result**
Agent should move to 'Error' status on adding 'Elastic Endpoint Security' to agent configuration without endpoint-security zip and sha files while enrolling the agent

**What's working**
- Agent enrolled successfully without any error if endpoint-security zip and sha files are available in Elastic Agent folder.

**What's not working**
- N/A

**Screenshot**
1. Activity logs show 'Error' but Agent remains in 'Offline' status on adding 'Elastic Endpoint Security' to agent configuration with no endpoint-security zip and sha files added :-
![#20534_ActivityLogs_AgentStatus](https://user-images.githubusercontent.com/59917944/89869966-c4d30400-dbd2-11ea-9579-5ccc15fe2703.jpg)

**Logs**
Activity Logs with Type 'Error' :-
[#20534_ActivityLogs_Error.zip](https://github.com/elastic/beats/files/5055389/20534_ActivityLogs_Error.zip)

**Comment by rahulgupta-qasource** [comment]
@manishgupta-qasource Please review the bug

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by EricDavisX** [comment]
this is a confusing scenario and issue, let me explain briefly why:
 - the Agent is intending to always download the Endpoint when it is first added to the configuration used on a given host.   It should and will do this anytime it can.  

The snapshot builds do this fine, and the GA builds will pull Endpoint from the GA location. This brief 1-month period where we are in 'build candidate' mode and we do not have a GA Endpoint (or Agent) yet is when we would ever manually copy the files.  But we even have a work-around for this as discussed, using the -- staging option put in to redirect the Agent to pull Endpoint from some the 'staging' location that relates to a given Build Candidate.

If you can re-test on a 7.9 or 8.0 snapshot build and report back that would help, as it would be a bug if it didn't work then. As it is now, this is all expected, just during the Build Candidate phase.

**Comment by EricDavisX** [comment]
About the expected result started:
Agent should move to 'Error' status on adding 'Elastic Endpoint Security' to agent configuration without endpoint-security zip and sha files while enrolling the agent

I think this is not a way to get Agent into an error state, with Agent running I guess.  : /

**Comment by rahulgupta-qasource** [comment]
Hi @EricDavisX

Thank you for sharing the feedback.

We have validated the above scenario on latest 7.9.1 BC2 Kibana cloud environment with 7.9.1 BC2 agent and found it **working fine**.

**Steps Followed**
1. Open the 7.9.1 BC2 Kibana cloud environment in browser, then click Ingest Manager.
2. Click on 'Configurations' tab -> Default config.
3. Click on 'Add Integration' -> 'Elastic Endpoint Security' and click on Save button.
4. Download and extract the 7.9.1 BC2 windows x86_64.zip agent file from [7.9.1 BC2 artifacts page](https://staging.elastic.co/7.9.1-7b774025/summary-7.9.1.html) on 'Windows 10' x64 bit endpoint.
5. Click on Fleet tab and enroll the agent on Windows10 x64 bit with '--staging' parameter by using the following commands(say): 
(i) .\elastic-agent enroll https://9b7a8573d1bf4e7aaaefd7dbfe82a2fe.us-central1.gcp.foundit.no:443 SVFIN1RYUUJFT1d3YzZ4ZG9aQ0M6YU9GWnVxN1RUamFCTG83SzJ6cU9BUQ== --staging 7b774025
(ii) .\install-service-elastic-agent.ps1


**Observations**:
1. Endpoint files(endpoint-security zip and sha512 files) are downloaded under Elastic Agent data/downloads location.
2. Endpoint-security is running successfully under Activity log(with agent in Online status).


Screenshot:
![#20534_closed](https://user-images.githubusercontent.com/59917944/92006242-17cb5180-ed62-11ea-97b4-b9c9f430fec6.jpg)


Hence, closing the issue.
