### ISSUE TITLE
Set a different autodiscover cleanup_timeout per beat

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#20543]
`cleanup_timeout` is now set to 60 seconds for all beats. This timeout is useful in filebeat, that may need to collect the last logs of a suddenly stopped container, but it is not so useful in other beats like Hearbeat or Metricbeat, that will be hitting endpoints that are no longer available, or assingned to newly created containers.

Keep this default value to 60 seconds for filebeat, but reduce it to 0 seconds for other beats.

**Comment by AbhilashBalaji** [comment]
I'd like to work on this issue , could someone give me any idea on where to start from ?

**Comment by jsoriano** [comment]
@AbhilashBalaji thanks for your interest! I am not sure what would be the best way of doing it, but let me try to give some guidelines.

Defaults are currently set here for the Kubernetes provider:
https://github.com/elastic/beats/blob/e805494c1a8fa0977fec50d1822c2fad8f646ed9/libbeat/autodiscover/providers/kubernetes/config.go#L64
And here for the Docker provider:
https://github.com/elastic/beats/blob/e805494c1a8fa0977fec50d1822c2fad8f646ed9/libbeat/autodiscover/providers/docker/config.go#L48

These defaults should be zero, and then we would need to find a way to keep them as 60 seconds only for filebeat. Not sure what would be the best way of doing it.
For example a not very clean solution could be to place these defaults in global variables in these providers and set them to 60 seconds from some Filebeat `init()`.
We also have a mechanism to customize hints-based autodiscover per Beat, for example [here](https://github.com/elastic/beats/blob/e805494c1a8fa0977fec50d1822c2fad8f646ed9/filebeat/autodiscover/builder/hints/logs.go#L38) we register the hints handler for Filebeat. Something like this would be a better option, but may be too much for a default.

Any other suggestion is welcome, ping me if you open a PR :slightly_smiling_face:
