### ISSUE TITLE
report disk failures

### ISSUE THREAD

**Issue by jmcclelland** [elastic/beats#20562]
In journald I get a report like this:

```
Jul 22 09:39:26 zora kernel: sd 3:0:0:0: [sdd] tag#14 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Jul 22 09:39:26 zora kernel: sd 3:0:0:0: [sdd] tag#14 Sense Key : Medium Error [current] 
Jul 22 09:39:26 zora kernel: sd 3:0:0:0: [sdd] tag#14 Add. Sense: Unrecovered read error - auto reallocate failed
Jul 22 09:39:26 zora kernel: sd 3:0:0:0: [sdd] tag#14 CDB: Read(16) 88 00 00 00 00 00 6a 35 61 50 00 00 02 60 00 00
```
Unfortunately, [it seems this information is not reported by metricbeat](https://discuss.elastic.co/t/report-disk-failures/243605/2).

It would be useful to get a report of disk failures. A few use cases would include:

1. One dashboard showing all servers with disk errors
2. Triggering an alert if any disk reports an error

Thanks!

**Comment by brettowe** [comment]
I'll add if all smart stats are logged you could then watch for indication of failure before they do.
more about which can be read about here: [https://www.backblaze.com/blog/what-smart-stats-indicate-hard-drive-failures/](https://www.backblaze.com/blog/what-smart-stats-indicate-hard-drive-failures/)
