### ISSUE TITLE
Edit Elastic Agent command line help

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#20579]
**Describe the enhancement:**
Current help accessible from the command line with the --help or help subcommand needs a good edit. There are some grammatical issues and inconsistencies.

**Comment by jlind23** [comment]
@dedemorton do you know if it has been fixed? Do you remember what were the issues and inconsistencies?

**Comment by dedemorton** [comment]
No, it's not fixed. I can see just from looking at the --help screen that there are still a lot of inconsistencies: inconsistent capitalization, inconsistent punctuation, lack of parallelism, unclear descriptions (possibly typos, too, but I didn't dig down into all the subcommands to confirm). There were so many nits that I figured someone on the writing team should just go through and edit everything.

I optimistically assigned this to myself, but lost track because it's not on our docs project board. :-( 

I'll add it to our board and make sure it gets into our plan. Thanks!

**Comment by dedemorton** [comment]
Also wanted to note that the [Elastic Agent command reference](https://www.elastic.co/guide/en/fleet/master/elastic-agent-cmd-options.html) has (hopefully) clearer descriptions. Some of them are too detailed for CLI help, but whoever works on this issue should use the docs to inform the edits.

**Comment by dedemorton** [comment]
I'm going to close this as a duplicate of https://github.com/elastic/observability-docs/issues/666 because the other issue has more detail about what needs to be changed.
