### ISSUE TITLE
[Metricbeat] Elasticsearch module, metricset node_stats documentation is empty in exported fields

### ISSUE THREAD

**Issue by turnUpTheChill** [elastic/beats#20575]
When trying to check exported fields in the Elasticsearch module [node_stats](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-elasticsearch.html#_node_stats) metricset, we are seeing that its empty.

The metricset [documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-elasticsearch-node_stats.html) is showing some of the fields, but not having the exported fields fully documented is causing some confusion.

**Comment by ycombinator** [comment]
@sayden This might be a good issue for you to look at to get your feet wet with the stack modules. WDYT?

**Comment by sayden** [comment]
Yeah! Good opportunity to take a look at this now that I have some background!
