### ISSUE TITLE
[Elastic Agent] Print a message confirming shutdown

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#20578]
**Describe the enhancement:**
Currently, when you exit the Elastic Agent it takes several seconds to close the app. The user may be left wondering if its frozen or crashed. It'd be better to print a line to stdout and to the logfile confirming the shutdown is in progress and what needs to happen before the application exits.

For example, it could say:
```
$ sudo ./elastic-agent run
[sudo] password for jason: 
^C
Shutting down Elastic Agent and sending last events...
```
In the example above on linux, the `^C` indicates that we requested the application to close by pressing Ctrl-C. It should print the same on a graceful kill signal.

**Comment by michalpristas** [comment]
i like the proposal, simple change but makes it much more clear to the user
