### ISSUE TITLE
[Ingest Management]: Metricbeat crashes and Error is displayed in Activity Logs on integrating SUSE Linux Enterprise Server 12.5 with 'Elastic Endpoint Security' integration

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#20585]
**Kibana version:**
Kibana: 7.9 BC9

**Elasticsearch version:**
Elasticsearch: 7.9 BC9

**Host OS and Browser version:**
SUSE Linux Enterprise Server 12.5 , All

**Original install method (e.g. download page, yum, from source, etc.):**
From 7.9 BC9 artifacts page

**Description**
[Ingest Management]: Metricbeat crashes and Error is displayed in Activity Logs on integrating SUSE Linux Enterprise Server 12.5 with 'Elastic Endpoint Security' integration

**Preconditions**
1. 7.9 BC9 Kibana cloud environment should be available.

**Steps to Reproduce**
1. Open the Kibana 7.9 BC9 cloud environment in browser, then click Ingest Manager.
2. Click on 'Configurations' tab -> Default config.
3. Click on 'Add Integration' -> 'Elastic Endpoint Security' and click on Save button.
4. Place endpoint-security zip and sha files in Elastic Agent data/downloads location.
5. Click on Fleet tab and Enroll the agent with sudo on SUSE Linux Enterprise Server 12.5 environment.
6. Click on Host to view the activity logs.
7. Observe that agent is in Online status but metricbeat is crashed with Type 'Error' displayed in activity logs.

**Test data**
N/A

**Impacted Test case id**
https://elastic.testrail.io/index.php?/cases/view/15872

**Actual Result**
[Ingest Management]: Metricbeat crashes and Error is displayed in Activity Logs on integrating SUSE Linux Enterprise Server 12.5 with 'Elastic Endpoint Security' integration

**Expected Result**
[Ingest Management]: Metricbeat should not crash and 'Error' Type should not be displayed in Activity Logs on integrating SUSE Linux Enterprise Server 12.5 with 'Elastic Endpoint Security' integration

**What's working**
 - Issue is not occurring on integrating 'Elastic Endpoint Security' with Linux CentOS7, Windows 10 and Mac Mojave 10.14.1

**What's not working**
 - N/A

**Screenshot**
1. Activity Logs:
![bug_SUSE](https://user-images.githubusercontent.com/59917944/90127203-6e0c2c80-dd82-11ea-8cbe-3c8ad3e07bfa.jpg)

**Logs**
1. Activity Logs:
[#20585_ActivityLogs_SUSE.zip](https://github.com/elastic/beats/files/5068625/20585_ActivityLogs_SUSE.zip)

2. Metricbeat Logs:
[#20585_Metricbeat logs.zip](https://github.com/elastic/beats/files/5068655/20585_Metricbeat.logs.zip)

**Comment by rahulgupta-qasource** [comment]
@manishgupta-qasource Please review the bug

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by EricDavisX** [comment]
this is why we test!  :)  @mostlyjason FYI.  Relates to our support matrix discussions.  I think we decided to leave Suse Linux uncited for now right?  So, that's good.

@michalpristas or @blakerouse when you get a chance could you look at the logs and take a guess as to why it happens when Endpoint integration is put into use?  @ferullo does that sound interesting for your Endpoint team to poke at, too?

**Comment by mostlyjason** [comment]
@EricDavisX thanks for testing! Suse is not listed as supported at the moment for the Agent.

**Comment by ph** [comment]
@EricDavisX Only seems to be related to metricbeat and not endpoint?
Do we have debug log level of the elastic-agent?

the metricbeat logs doesn't show any error except at shutdown.
```
metricbeat-json.log:{"log.level":"error","@timestamp":"2020-08-13T06:09:53.500-0400","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"fleet/manager.go","file.line":187},"message":"elastic-agent-client got error: rpc error: code = Canceled desc = context canceled","ecs.version":"1.5.0"}
metricbeat-json.log:{"log.level":"error","@timestamp":"2020-08-13T06:09:53.500-0400","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"fleet/manager.go","file.line":187},"message":"elastic-agent-client got error: rpc error: code = Canceled desc = context canceled","ecs.version":"1.5.0"}
metricbeat_monitor-json.log:{"log.level":"error","@timestamp":"2020-08-13T06:09:53.496-0400","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"fleet/manager.go","file.line":187},"message":"elastic-agent-client got error: rpc error: code = Canceled desc = context canceled","ecs.version":"1.5.0"}
metricbeat_monitor-json.log:{"log.level":"error","@timestamp":"2020-08-13T06:09:53.496-0400","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"fleet/manager.go","file.line":187},"message":"elastic-agent-client got error: rpc error: code = Canceled desc = context canceled","ecs.version":"1.5.0"}

**Comment by EricDavisX** [comment]
@rahulgupta-qasource hi - can you confirm the steps followed... break down the timing for us, please.  if the Endpoint and Metricbeat are alive and well, for a time, that is good to know.  if it happens only at shut-down that is informational, and if it happens on that environment without Endpoint included it would be god to know too.

If you can set the policy value in the fleet.yml file on the host and re-start and see what comes from it so you can post a more robust log file please?  

the log level is here, per os family (windows, linux, macos):
      linux:
        logging:
          file: info

**Comment by rahulgupta-qasource** [comment]
Hi @EricDavisX

Thank you for the feedback.

We have validated this ticket on latest 7.9.1-SNAPSHOT Kibana cloud environment with 7.9.1-SNAPSHOT agent and found it **fixed**.

**Steps Followed**
1. Open the 7.9.1-SNAPSHOT Kibana cloud environment in browser, then click Ingest Manager.
2. Click on 'Configurations' tab -> Default config.
3. Click on 'Add Integration' -> 'Elastic Endpoint Security' and click on Save button.
4. Download and extract the 7.9.1-SNAPSHOT linux .tar.gz agent file from [7.9.1-SNAPSHOT artifacts page](https://artifacts-api.elastic.co/v1/search/7.9.1-SNAPSHOT) by using the following commands(say) on SUSE Linux Enterprise Server 12.5 endpoint:-
 (i) curl -L -O https://snapshots.elastic.co/7.9.1-aeb6bbc0/downloads/beats/elastic-agent/elastic-agent-7.9.1-SNAPSHOT-linux-x86_64.tar.gz`
 (ii) tar xzvf elastic-agent-7.9.1-SNAPSHOT-linux-x86_64.tar.gz

5. Place endpoint-security zip and sha512 files in Elastic Agent data/downloads location by using the following commands(say):
  (i) sudo curl -L -O https://snapshots.elastic.co/7.9.1-aeb6bbc0/downloads/endpoint-dev/endpoint-security-7.9.1-SNAPSHOT-linux-x86_64.tar.gz
 (ii) sudo curl -L -O https://snapshots.elastic.co/7.9.1-aeb6bbc0/downloads/endpoint-dev/endpoint-security-7.9.1-SNAPSHOT-linux-x86_64.tar.gz.sha512

6. Click on Fleet tab and enroll the agent on SUSE Linux Enterprise Server 12.5 environment by using the following commands(say):
 (i) sudo ./elastic-agent enroll https://e48cd01abfc14c58a15651b2b981d22a.us-central1.gcp.foundit.no:443 c2ctOEszUUJodEdRTTNiUzhCc0w6TVRJcFFFQWJUVnV0TlVDZVExQmVvdw==
(ii) sudo ./elastic-agent run

7. Click on Host to view the activity logs.


**Observation**:
Observed that agent is in Online status and metricbeat is running successfully[with no error in activity logs] on integrating SUSE Linux Enterprise Server 12.5 with 'Elastic Endpoint Security' integration.


Screenshot:
![#20585](https://user-images.githubusercontent.com/59917944/91434611-ae8ba000-e882-11ea-82f8-569e6a3c7b10.jpg)


Hence, closing the issue.

**Comment by EricDavisX** [comment]
@mostlyjason You can update this for 7.9.1 or 7.10.0 web site update.
