### ISSUE TITLE
Output MAC address along with IP

### ISSUE THREAD

**Issue by rshriram** [elastic/beats#206]
In a container or VM environment with multiple vlans and overlapping IP addresses across subnets (think openstack), Mac addresses can be used to distinguish different vms with same IP. it would be useful to have Mac addresses of these endpoints emitted as part of log entries so that they can be correlated to the respective tenant vms or containers.

**Comment by tsg** [comment]
I think it makes sense as an enhancement. Thanks.

**Comment by purplesrl** [comment]
+1

**Comment by Choosue** [comment]
What's the aftermath of this issue? As replied by @purplesrl ，the "flow" type data actually contains the "client.mac" field. But what about other types? Like, "http", "dhcp", how can I inspect the mac address on these types of packet?
