### ISSUE TITLE
[metricbeat] Metricbeat is missing kubernetes.pod.uid field

### ISSUE THREAD

**Issue by wajika** [elastic/beats#20623]
https://discuss.elastic.co/t/how-to-get-kubernetes-metadata-with-elastic-apm/242865/3

I don't know why my metricbeat did not produce kubernetes.pod.name and kubernetes.pod.uid data.
Can someone help me analyze the reason？

**Comment by jsoriano** [comment]
Hey @wajika,

Thanks for opening this issue, but I am slightly confused. The link you have posted refers to an issue with APM. How does it relate to your issue with Metricbeat?

We keep Github issues for confirmed bugs and enhancement requests, I am going to close this issue by now. Could you please open a topic in the discuss forum (https://discuss.elastic.co/) with your question and more information about your issue?
