### ISSUE TITLE
Index template example uses deprecated API, needs updating

### ISSUE THREAD

**Issue by nerophon** [elastic/beats#20636]
Version: 7.8.1

The [docs here](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-template.html#load-template-manually) show an number of examples of index template creation. However, they use the old, deprecated API. It should be updated to use the [new Index Template API](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/index-templates.html).

Furthermore, we believe that Filebeat is also using the old API under the hood as well when you run _setup.template.*_.

**Comment by nerophon** [comment]
Sorry, I'm not sure which team would be most appropriate for this issue.

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
