### ISSUE TITLE
Don't drop unparsed messages

### ISSUE THREAD

**Issue by strawgate** [elastic/beats#20635]
For Cisco IOS (and other modules) when the module doesn't have a dedicated parser for the message it should forward the message without parsing instead of dropping the message.

This would allow us to write our own Logstash or Elasticsearch Ingest Pipeline to handle the unparsed messages

The current behavior essentially makes it so that if there are any messages that can't be parsed you can't use the module as it is written.

**Comment by andrewkroh** [comment]
Do you have an example where an unparsed Cisco IOS message is dropped? Do you mean the event is dropped or just the `message` field? None of the modules drop events intentionally AFAIK.
