### ISSUE TITLE
Start ILM counter at 0

### ISSUE THREAD

**Issue by markwalkom** [elastic/beats#20648]
**Describe the enhancement:** When a new ILM policy is implemented, the index name is prefixed with `000001`, we should really be indexing from zero, making it `000000`.

**Describe a specific use case for the enhancement or feature:** We do try to index from 0 after all :)

**Comment by markwalkom** [comment]
Or is this an Elasticsearch ILM matter?

**Comment by andresrc** [comment]
https://github.com/elastic/beats/blob/95626b8f1690344312c0831ab2bdcbccffe4d089/libbeat/idxmgmt/ilm/config.go#L61

**Comment by MadhavJivrajani** [comment]
Hi!
Can I work on this?

**Comment by kaiyan-sheng** [comment]
@MadhavJivrajani Of course! Please feel free to start on this! Assign the issue to yourself and we can't wait to see your PR!

**Comment by MadhavJivrajani** [comment]
Hi,
I just wanted to clarify a couple of things:

- I change the value from `000001` to `000000` [over here](https://github.com/elastic/beats/blob/95626b8f1690344312c0831ab2bdcbccffe4d089/libbeat/idxmgmt/ilm/config.go#L61)
- I update CHANGELOG.next.asciidoc
- Do I make the corresponding changes to the other yaml/asciidoc files as well?

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
