### ISSUE TITLE
Document all Kubernetes processor parameters

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/beats#20651]
**Describe the enhancement:**

In general, the `add_kubernetes_metadata` processor shares most of the parameters of the Kubernetes autodiscover (but it is not stated in the documentation).

If we compare the following 2 pages, we can see the processor doesn't document options such as `include_annotations`:
- https://www.elastic.co/guide/en/beats/filebeat/current/add-kubernetes-metadata.html
- https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover.html

Can we document all the supported parameters?

In the specific case of `include_annotations`, we need to state it is not possible to pull all the annotations (we do not support wildcards).

**Comment by jsoriano** [comment]
It seems that annotations cannot be pulled from all resources, at least from namespaces when using `add_resource_metadata.namespace` (see [code](https://github.com/elastic/beats/blob/03748b32fef7018396750c25baf80321cf931459/libbeat/common/kubernetes/metadata/namespace.go#L94)). This should be also stated in the docs, or added to the code.
