### ISSUE TITLE
docker-compose example in the docs

### ISSUE THREAD

**Issue by markwalkom** [elastic/beats#20650]
**Describe the enhancement:** Per the subject, this would be super handy, and we offer this for Elasticsearch and Kibana.

**Describe a specific use case for the enhancement or feature:** docker-compose is a pretty standard way of running containers, and this would be a nice example to provide for our users to copy.

**Comment by bmorelli25** [comment]
We did this for [APM Server](https://www.elastic.co/guide/en/apm/get-started/current/quick-start-overview.html) in https://github.com/elastic/apm-server/pull/3106. It might be a good starting point for these docs, or an opportunity to single-source from the Beats repo.
