### ISSUE TITLE
[Elastic Agent] Failed to enroll on Synology NAS

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#20657]
Trying to enroll the Elastic Agent on an older Synology NAS failed with the following error:

```
fail to enroll: acquiring metadata failed: failed to gather host metadata: 1 error: no /etc/<distrib>-release file found
```

`uname -a` outputs:

```
Linux buster 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
```

It seems some of the files we want to read data from do not exist in this environment.

Filing this as enhancement as this platform is not supported.

**Comment by ph** [comment]
@ruflin I think the enhancement should instead be in the `go-sysinfo` repository,  looking at the code, it's `sysinfo` that actually fails hard in that specific case. I think sysinfo should instead return _unknown_.

https://github.com/elastic/beats/blob/f2c4c0a4b8d9c33c8602a8d2573f36eae686d92c/x-pack/elastic-agent/pkg/agent/application/info/agent_metadata.go#L114-L124

**Comment by ph** [comment]
I want to clarify, it's become it's all or nothing in the sysinfo side, I think it's wrong.

**Comment by andrewkroh** [comment]
An API change in sysinfo would probably help clarify sysinfo API usage. Like changing the [`Host.Info()`](https://github.com/elastic/go-sysinfo/blob/master/types/host.go#L25) to be able to return an error.

The trouble comes from that `sysinfo.Host()` can return an error while still returning a usable non-nil `Host` object. If this occurs there was some trouble collecting data from the host, but it still tries return as much data as it could collect. So agent can proceed after the error, but it does need to always do a nil check on the `HostInfo.OS` value before using it.

**Comment by andrewkroh** [comment]
@ruflin Are there any files matching /etc/*release* or /usr/lib/*release* on the system?

**Comment by ph** [comment]
@andrewkroh I think that would work, I mean we could have partial information. "unknown or unsupported" for string field.

**Comment by ruflin** [comment]
@andrewkroh Unfortunately couldn't find any of these files. I wonder where they are hidden :-(

**Comment by ph** [comment]
@ruflin I've checked on my Synology and I don't have theses files too. iirc they were based on debian a long time ago.

**Comment by fabiogermann** [comment]
@andrewkroh and @ruflin same problem here:
`uname -a` reports: `Linux localhost 4.14.38 #2 SMP Fri Jun 5 23:03:53 UTC 2020 x86_64 GNU/Linux`
and
`ls /etc/*-release` reports: `/etc/lsb-release`
so there is a non-empty file.

**Comment by fabiogermann** [comment]
@ph it contains only one line "DISTRIB_ID=Sophos Firewall"

**Comment by jlind23** [comment]
@nimarezainia is this something we should investigate or shall we close this as won't fix?

**Comment by ruflin** [comment]
This is likely is more coming from a personal interest to run Elastic Agent on my NAS, not sure how common this is.

**Comment by nimarezainia** [comment]
@jlind23 I haven't seen any other customer requests for this. I can't justify dev time on it :-(
