### ISSUE TITLE
[DOCS] List supported field data types for metricset

### ISSUE THREAD

**Issue by jrodewig** [elastic/beats#20671]
In the [Metricset Details](https://www.elastic.co/guide/en/beats/devguide/current/metricset-details.html#_fields_yml) docs:

> metricbeat/module/{module}/{metricset}/_meta/fields.yml: Contains all fields definitions retrieved by the metricset. As field types, each field must have a core data type [supported by elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-types.html#_core_datatypes).

In ES, there is no formal/technical definition for `core` field data types. This is just an arbitrary grouping used in our docs. As the ES team is looking at reorganizing the docs, this reference should be updated with the supported types.

Elasticsearch should also be capitalized. Thanks!

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
