### ISSUE TITLE
Bug workflow for issues in Github is flawed 

### ISSUE THREAD

**Issue by 0xtf** [elastic/beats#20682]
It's unfortunate that I'm forced to open a bug because of this, but I believe there is a loophole in what Elastic is asking users to do, and that will result in the impossibility of submitting bugs. 

The following bug was closed, with just a remark to open a thread in Discuss: https://github.com/elastic/beats/issues/20219

While I don't agree with that approach, someone apparently is facing the same [issue](https://discuss.elastic.co/t/filebeat-processor-for-single-line-logs/242812/5), and did in fact post it in Discuss. I've also tried to follow this up in the community Slack, with no luck either.

Now:

* I can't open a bug because it's not confirmed in Discuss (and I believe the issue I mentioned does not appear to be trying to fetch anything, and provides a valid use case where something definitely is wrong)
* The Discuss thread is not followed up and put into whatever state Elastic classifies it as "bug worthy" 

This means that what appears to be a valid issue in Filebeat will ... not be followed up.

**Comment by andresrc** [comment]
Hi @0xtf ,

I'm sorry about the inconvenience. However, we currently need this flow to better control the inbound flow of issues, by providing a bigger audience to those ones that may not be bugs.

I understand that sometimes replies in discuss take longer that we would have like. I'm afraid that depends on the availability of everyone participating in the community, including the team.

Thanks

**Comment by 0xtf** [comment]
The report has nothing to do with time but with the actual outcome of the workflow. Looking at the example I provided clearly shows that this approach is not, to say the least, productive. 

Not only it makes it hard for people wanting to contribute, through bug submissions, but also to Elastic itself, as it creates a loophole (IMHO) in the process.

Up to you though :+1:
