### ISSUE TITLE
[Elastic Agent] Applies POLICY* Changes from Fleet to the Agent.

### ISSUE THREAD

**Issue by ph** [elastic/beats#20687]
- [x] Rename action type `CONFIG_CHANGE` -> `POLICY_CHANGE`
- [x] Read policy field to retrieve new agent policy on `POLICY_CHANGE` actions instead of config field
- [x] Update Agent Policy file to not mention config anymore
- ~~[ ] Update docs~~

**Comment by ruflin** [comment]
@ph Can this be closed?

**Comment by ph** [comment]
PR still up at https://github.com/elastic/beats/pull/20779

@michalpristas took it over and syncing with @jen-huang, I will reassign it to him.
