### ISSUE TITLE
Navigation between Metrics System dashboard is broken (Metricbeat system module dashboards)

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/beats#20692]
[Short video of issue](https://github.com/elastic/beats/files/5097448/Nav.mp4.zip)

These are the two dashboards I am navigating between:
<img width="265" alt="image" src="https://user-images.githubusercontent.com/25182304/90641836-ab980c00-e1ff-11ea-8fb4-5ef31ac5c01a.png">

If I am on a host dashboard and click to go to the overview dashboard:

<img width="491" alt="image" src="https://user-images.githubusercontent.com/25182304/90642111-fb76d300-e1ff-11ea-9abe-c53da01ccaac.png">

 I see this:
`Could not locate that dashboard (id: system-Metrics-system-overview-ecs)`

- Version: 7.9.0
- Operating System: ESS
- Steps to Reproduce: 
    - Deploy Agent 7.9.0 using the default configuration
    - Start the agent
    - Open Dashboard > `[Metrics System] Overview ECS`
    - Navigate to one host by double clicking the host
    - Try to navigate back to the overview using the link

[Nav.mp4.zip](https://github.com/elastic/beats/files/5097448/Nav.mp4.zip)

**Comment by naveenkumarsp** [comment]
i am experiencing the same after i have upgraded the deployment from 7.8.1 to 7.9.0 in elastic cloud

**Comment by sinoohe** [comment]
I have the same issue here.

**Comment by DanRoscigno** [comment]
I believe that this is fixed in 7.9.3 of Metricbeat.  I tested it this morning cc: @sinoohe @naveenkumarsp @scottwallacesh
