### ISSUE TITLE
[metricbeat] Add IopsInProgress metric in the list of exported fields for diskio system module

### ISSUE THREAD

**Issue by unixsurfer** [elastic/beats#20691]
**Describe the enhancement:**
Kernel exposes a metric for IO operations in progress with [field 12](https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats) but the metricbeat [diskio module](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-system.html#_diskio_3) doesn't exported it. 
The [metric](https://github.com/shirou/gopsutil/blob/master/disk/disk_linux.go#L432) is available from [shirou Go library](https://github.com/shirou/gopsutil/blob/master/disk/disk_linux.go#L423) that metricbeat uses.

**Describe a specific use case for the enhancement or feature:**
We want to get an inside in the number of IO operations in progress in order to calculate the queue time in the same way that https://www.percona.com/doc/percona-toolkit/LATEST/pt-diskstats.html does, see `qtime`.

**Comment by MadhavJivrajani** [comment]
Hi!
I'd love to take this up if possible.
