### ISSUE TITLE
[Elastic Agent] Enforce validation on namespace

### ISSUE THREAD

**Issue by ph** [elastic/beats#20693]
In Kibana we are adding validation on [top](https://github.com/elastic/kibana/pull/75381/) of the namespace to remove the possibility to create invalid index name.
We should have the same rules applied on the elastic-agent.

**Comment by michalpristas** [comment]
should be done at configuration parse time: https://github.com/elastic/beats/blob/f06bcc5d401d7b6fc833bc0e516064ace0a68d45/x-pack/elastic-agent/pkg/agent/application/filters/stream_checker.go#L173

**Comment by ph** [comment]
@michalpristas Can you confirm that the validation match between Kibana and the Agent?

**Comment by michalpristas** [comment]
i will verify what they are using, we took rules from ES documentation so if they did the same we should be fine. i will confirm

**Comment by michalpristas** [comment]
the validation rules used in kibana is more relaxed I left a comment there in a PR https://github.com/elastic/kibana/pull/75381/files#r476228944

**Comment by ph** [comment]
@michalpristas I think both are incorrect, see my comment in https://github.com/elastic/kibana/pull/75381/files#r476416054 Can you take a lead and synchronized with @jen-huang to have unique validation for both?

**Comment by jen-huang** [comment]
I followed up in https://github.com/elastic/kibana/issues/75846#issuecomment-680092618.

**Comment by michalpristas** [comment]
Closing, fixed by https://github.com/elastic/beats/pull/21406
