### ISSUE TITLE
Feature Request: Store a YUM .repo file somewhere so that yum/dnf can add the repo directly

### ISSUE THREAD

**Issue by joshuar** [elastic/beats#2070]
In our [repositories instructions for yum](https://www.elastic.co/guide/en/beats/libbeat/current/setup-repositories.html#_yum), we currently ask people to manually create the repo file.  We should instead  store the `.repo` file somewhere where people can download it directly with `yum` or `dnf` as well, which is much more convenient.  Then, they can use:

```
sudo yum-config-manager --add-repo repository_file_url
```

or 

```
sudo dnf config-manager --add-repo repository_file_url
```

**Comment by andrewkroh** [comment]
I like this idea. I can publish a versioned file to the S3 bucket. I propose that it be located at https://packages.elastic.co/beats/yum/el/beats-1.x.repo   How does that sound?

```
[beats-1.x]
name=Elastic Beats Repository
baseurl=https://packages.elastic.co/beats/yum/el/$basearch
enabled=1
gpgkey=https://packages.elastic.co/GPG-KEY-elasticsearch
gpgcheck=1
```

If we do this, then for 5.x we should do it for all products as part of the unified release. @rjernst, thoughts?

**Comment by andrewkroh** [comment]
@joshuar Can you please open an elastic/stack enhancement request for this one.
