### ISSUE TITLE
Dashboards display partially when using custom index (other than metricbeat*)

### ISSUE THREAD

**Issue by Xat59** [elastic/beats#20703]
**Kibana version:** 7.8.1

**Elasticsearch version:** 7.8.1

**Server OS version:** Ubuntu 18.04.4 LTS

**Browser version:** Firefox 77.0.1 (64 bits)

**Original install method (e.g. download page, yum, from source, etc.):** `aptitude install kibana`  from artifacts.elastic.co repository.

**Describe the bug:** 
I am using custom index name to store metrics instead of the default metricbeat index. I've installed Kibana dashboards using `metricbeat setup`.
After that, some visualizations in Kibana dashboards do not display while the most of the other visualizations in the same dashboard work fine.

**Steps to reproduce:**
1. Install metricbeat, then send system (or apache) metrics to the index named ` customindex ` . Ensure metrics data are received in the ` customindex ` index.
2. Configure Kibana Index Patterns to use data from the ` customindex ` index. Now you have metrics data from the custom index.
3. On the metricbeat instance, do the following : ` metricbeat setup ` .
4. In Kibana, go to Kibana > Dashboards , and click on `[Metricbeat System] Overview ECS` to see that dashboard.

**Expected behavior:**
All vizualisations in the dashboard are displaying correctly.

**Screenshots (if relevant):**
![image](https://user-images.githubusercontent.com/1276192/90617498-08e78980-e20f-11ea-9f08-178c370c0b53.png)

**Errors in browser console (if relevant):**
- Error: "Could not locate that index-pattern (id: metricbeat-*), [click here to re-create it](#/management/kibana/index_pattern)"
This is a normal error and that's probably the reason of the bug, because I'm not using `metricbeat` indices. 

**Any additional context:**
I have the same behavior on other dashboards, such as ` [Metricbeat Apache] Overview ECS ` 

Thank a lot guys.
Regards,

**Comment by bevano8** [comment]
Is there any ETA on a fix for this?

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
