### ISSUE TITLE
[Elastic-Agent] Clean up the elastic agent's changelog.

### ISSUE THREAD

**Issue by ph** [elastic/beats#20715]
The Elastic-Agent changelog is in https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/CHANGELOG.asciidoc

- [x] Verify the documentation to make sure the changelog is the right one.
- [x] Make sure we agree to keep it separate vs other beats.
- [x] Verify the automated changelog.

**Comment by ruflin** [comment]
Agree to keep it separate as I expect us to move to a separate repo soon.

**Comment by ph** [comment]
We are not there yet with the automated changelog.

**Comment by ph** [comment]
I've created the PRs for all the active branch, master, 7.x, 7.9 and 7.8.
