### ISSUE TITLE
[Docs] Filebeat Kafka module exported fields page is confusing

### ISSUE THREAD

**Issue by woodywalton** [elastic/beats#20726]
Several sections of the [exported fields page for the Filebeat Kafka module](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-kafka.html) appear to be either missing or transposed on other sections - these are some of the issues I see:

- Multiple sections are labeled the same, e.g. `broker`, `partition`
- Some sections are essentially empty (there's an empty `kafka` section at the beginning, and `consumergroup` and the first `partition` sections are empty as well)
- Some sections are titled one thing, but are really discussing another (e.g. the first `broker` section seems to be the `consumergroup` entities)

**Comment by sayden** [comment]
I can confirm this issue. I have taken a look at the fields in Kafka and they need some proper nesting and reordering. The problem I see is that we need to introduce breaking changes to sanitize them. For example we have `kafka.broker.id` which is a module level field but we also have a `broker` metricset creating events in `kafka.broker.*`. This breaks the rule of not having module level fields overlapping names with metricset field names. The first solution that comes to my mind is to rename the metricset to `broker_stats`. Another solution could be to introduce more nesting layers to clearly separate module level from metricset level fields.
