### ISSUE TITLE
monitor size of specific directory/file size on disk

### ISSUE THREAD

**Issue by zaynkorai** [elastic/beats#20733]
**A feature in metric beat to monitor size of specific folder/files, after some research I got to know there is no way to check size of specific directory/file size on disk**

**Incase I needed a way to monitor size of specific directories on disk over time. like we are running multiple sites(low traffic) on single server and disk, Now we wanted to monitor size of specific site on disk overtime and disk monitoring data is not enough to know out of all sites which site is eating disk space on server. This feature will help to monitor size of 
 single site even though there are multiples site on one server:**

@Team:Metricbeat

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
