### ISSUE TITLE
Packetbeat mongodb high memory usage

### ISSUE THREAD

**Issue by sidineycrescencio** [elastic/beats#20755]
Hi there!

I have an issue with packetbeat monitoring mongodb traffic, I know this is not the right place to discuss that, but I already opened a thread in the forum, and unfortunately got no responses, so maybe someone here is able to help me out.

https://discuss.elastic.co/t/packetbeat-memory-usage/244177

If more details are needed for troubleshoot this just let me know.

**Comment by bamboo2017** [comment]
I got the same issue when backup the MongoDB database with mongodump tool . 

{"level":"info","timestamp":"2020-08-25T01:22:50.028+0800","logger":"monitoring","caller":"log/log.go:145","message":"Non-zero metrics in the last 30s","monitoring":{"metrics":{"beat":{"cpu":{"system":{"ticks":1932620,"time":{"ms":216}},"total":{"ticks":8734660,"time":{
"ms":2068},"value":8734660},"user":{"ticks":6802040,"time":{"ms":1852}}},"handles":{"limit":{"hard":4096,"soft":1024},"open":12},"info":{"ephemeral_id":"5d26e67f-9c5e-4a10-a0bd-b7bc697bd475","uptime":{"ms":86190099}},"memstats":{"gc_next":51355216,"memory_alloc":4607628
0,"memory_total":700317168944,"rss":1957888},"runtime":{"goroutines":27}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"acked":4072,"batches":28,"total":4072},"read":{"bytes":168},"write":{"bytes":475615}},"pipeline":{"clients":2,"events":{"active":7
,"published":4067,"total":4067},"queue":{"acked":4072}}},"system":{"load":{"1":0.18,"15":0.32,"5":0.34,"norm":{"1":0.009,"15":0.016,"5":0.017}}}}}}
{"level":"error","timestamp":"2020-08-25T01:23:05.108+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 859124792 ((value=859124792))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.116+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1714894645 ((value=1714894645))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.128+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1929409601 ((value=1929409601))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.150+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: -2122258008 ((value=-2122258008))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.167+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1952539664 ((value=1952539664))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.168+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 117440515 ((value=117440515))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.169+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1280 ((value=1280))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.174+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 2162809 ((value=2162809))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.181+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 6572396 ((value=6572396))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.187+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 230144 ((value=230144))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.307+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 858994995 ((value=858994995))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.352+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1717712738 ((value=1717712738))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.390+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 912352821 ((value=912352821))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.419+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1952673385 ((value=1952673385))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.426+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1829765120 ((value=1829765120))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.438+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 943011126 ((value=943011126))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.492+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 859058485 ((value=859058485))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.501+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 14080 ((value=14080))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.511+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 608593243 ((value=608593243))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.526+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1802257761 ((value=1802257761))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.537+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: -2076696860 ((value=-2076696860))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.537+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 919 ((value=919))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.546+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 878797414 ((value=878797414))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.556+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 892613688 ((value=892613688))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.645+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1231840622 ((value=1231840622))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.650+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 608593303 ((value=608593303))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.678+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 899 ((value=899))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.714+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 909325621 ((value=909325621))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.744+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1745879040 ((value=1745879040))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.766+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1718503788 ((value=1718503788))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.868+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 926036272 ((value=926036272))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.971+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: -2076696948 ((value=-2076696948))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.983+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1043 ((value=1043))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.991+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 267008 ((value=267008))"}
{"level":"error","timestamp":"2020-08-25T01:23:05.995+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 987 ((value=987))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.008+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1850305637 ((value=1850305637))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.015+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 825309493 ((value=825309493))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.034+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1684288312 ((value=1684288312))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.179+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 842281529 ((value=842281529))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.317+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 825451621 ((value=825451621))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.318+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1680959030 ((value=1680959030))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.321+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 943023416 ((value=943023416))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.329+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1677852772 ((value=1677852772))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.335+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1717842534 ((value=1717842534))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.336+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 825229312 ((value=825229312))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.337+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 892941108 ((value=892941108))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.338+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 943207476 ((value=943207476))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.340+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1698182242 ((value=1698182242))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.342+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 926299961 ((value=926299961))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.342+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 959722803 ((value=959722803))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.343+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 842006528 ((value=842006528))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.358+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 909195314 ((value=909195314))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.383+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 638 ((value=638))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.407+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 608593257 ((value=608593257))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.409+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 608593344 ((value=608593344))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.492+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 1079 ((value=1079))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.517+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 234240 ((value=234240))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.523+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 22 ((value=22))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.662+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: -2076696897 ((value=-2076696897))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.693+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: -1140820927 ((value=-1140820927))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.758+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 14 ((value=14))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.770+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 6912 ((value=6912))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.864+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 808595762 ((value=808595762))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.910+0800","caller":"mongodb/mongodb_parser.go:68","message":"Unknown operation code: 7936 ((value=7936))"}
{"level":"error","timestamp":"2020-08-25T01:23:06.921+0800","caller":"mongodb/mongodb_parser.go:148","message":"An error occurred while parsing OP_REPLY message: document out of bounds"}

**Comment by marc-gr** [comment]
Thanks for moving your question here @sidineycrescencio.

From your forum question, I see you are on 

```
Beats: 7.8.0
Mongo: 4.0.6
```

A bit more details about specific operations you are performing that might help us reproduce it would be helpful.

Can you please also add your beats/mongo versions @bamboo2017? 

Will start looking into it while I wait for more details.

Thanks!
