### ISSUE TITLE
MSSQL Filebeat module documentation confusion

### ISSUE THREAD

**Issue by asc-adean** [elastic/beats#20761]
Documentation at **beats/filebeat/docs/modules/mssql.asciidoc** appears to be mostly a copy paste from the Traefik documentation.  It's referencing a Linux file path and has the word 'Traefik' in the document.  Is there an effort to document this module properly?

Thank you

**Comment by sayden** [comment]
Thank you for reporting this! I have opened a PR to fix it: https://github.com/elastic/beats/pull/23360
