### ISSUE TITLE
[Elastic Agent] Define behavior of `--insecure` at enrollment time vs runtime.

### ISSUE THREAD

**Issue by ph** [elastic/beats#20763]
Recently we have added the `--insecure` flag at enrollment time when the flag is set it will do the following:

- Disable the TLS check for the _enrollment_.
- Save this option in the local configuration of the Elastic Agent.
- The _checkin_ will also be insecure.

The flag is often used when you are running with self-signed certificates

This will not change any TLS options for the elasticsearch output of any inputs that use TLS options, **this is not a global modifier.** When @nicholasberlin used that flag, he was also expecting that the verification would be also turned off for the elasticsearch output, the result was a bit unexpected.

I don't think we ever discussed the behavior outside of the enrollment and the checkin time. I still believe we are doing the right thing by not modifying anything outside of the agent communication but I would like to also get your opinion.

@ruflin @michalpristas @blakerouse @EricDavisX

**Comment by nicholasberlin** [comment]
My understanding is that beats connect directly to elasticsearch. Does `--insecure` affect their tls verification?

**Comment by ph** [comment]
@nicholasberlin Beats doesn't have that flag at all, if we want to make it a global modifier we would need to add support for it.

**Comment by michalpristas** [comment]
just a note that for standalone mode there is an option to specify `ssl.*` (described here https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html)  options in output config section (`output.elasticsearch.ssl.*`) which will then be passed to respective beats. 
i think this is not possible using fleet

**Comment by blakerouse** [comment]
I agree, I think Agent is currently doing the correct thing. I think allowing the user to configure in Fleet to communicate to elasticsearch insecurely is the correct path forward, instead of making it behavior or `--insecure`.

**Comment by ph** [comment]
Sound like we have an agreement here, going to close this and we can expose the right settings in fleet for controlling the verification or provides certificates for the Elasticsearch output.
