### ISSUE TITLE
Kibana stats: less aggressive usage collection if failed

### ISSUE THREAD

**Issue by afharo** [elastic/beats#20771]
Metricbeat for Kibana collects usage stats once a day. 

But, if the collection request fails (we've seen timeouts lately for requests taking longer than [10s default timeout](https://github.com/elastic/beats/blob/03748b32fef7018396750c25baf80321cf931459/metricbeat/helper/config.go#L38)), it will request the usage again on the next poll interval (10s later), overloading the server even more.

https://github.com/elastic/beats/blob/03748b32fef7018396750c25baf80321cf931459/metricbeat/module/kibana/stats/stats.go#L166-L173

Can we set up a backoff mechanism that will try to skip the collection of the usage for a few rounds (maybe for another day?), prioritising metric-stats over usage-collection?

**Comment by afharo** [comment]
@andresrc thank you for amending the labels 😅 
I've created a tentative PR in here: https://github.com/elastic/beats/pull/20772

But I'm not a go developer so maybe there's a better way to implement it 😉

**Comment by andresrc** [comment]
Thank you very much @afharo !
