### ISSUE TITLE
[filebeat] Azure Module Docs Incorrect Config Settings

### ISSUE THREAD

**Issue by SpencerLN** [elastic/beats#20808]
The sample configuration included in the [Azure Filebeat module docs](https://www.elastic.co/guide/en/beats/filebeat/7.9/filebeat-module-azure.html#_module_configuration_2) results in an error on startup:
`2020-08-26T14:02:25.371-0500	ERROR	instance/beat.go:951	Exiting: Failed to start crawler: starting input failed: Error while initializing input: can not convert 'object' into 'string' accessing 'eventhub'
reading azure-eventhub input config`.

This is due to the `eventhub` setting for the `signinlogs` being set to an array of strings. The value should just be the Event Hub name as a string. 

For confirmed bugs, please report:
- Version: 7.9.0
- Operating System: N/A
- Steps to Reproduce: 
  - Start a Filebeat instance configured with the snippet from the [Azure module docs](https://www.elastic.co/guide/en/beats/filebeat/7.9/filebeat-module-azure.html#_module_configuration_2)
  - Receive an error since the config is wrong.

**Comment by narph** [comment]
hi @SpencerLN , 
The azure module was previously using the kafka input to retrieve the azure logs. The eventhub property could support multiple eventhub names. Switching to the azure-eventhub input, this functionality is not supported (hopefully this will be the case in the future).
This detail was missed in the docs.
I have opened https://github.com/elastic/beats/pull/20815 to fix the docs, thanks for bringing this to our attention.
