### ISSUE TITLE
Functionbeat 7.9.0 deploy failure on GCP

### ISSUE THREAD

**Issue by aschifman** [elastic/beats#20830]
Deploying functionbeat 7.9.0 fails after the following command:

`./functionbeat -v -e -d "*" deploy storage`

Error output:

~~~"DEBUG   [gcp]   gcp/cli_manager.go:47   Deploy finish for function 'storage'
Function: storage, could not deploy, error: error while creating function (code: 3):
Build failed: src/storage/storage.go:11:2: cannot find package "github.com/elastic/beats/v7/libbeat/beat" in any of:
        /usr/local/go/src/github.com/elastic/beats/v7/libbeat/beat (from $GOROOT)
        /workspace/src/github.com/elastic/beats/v7/libbeat/beat (from $GOPATH)"
~~~
Many additional lines similar to above and finishes with...

~~~"DEBUG   [cli-handler]   cmd/cli_handler.go:62   Deploy execution ended
Fail to deploy 1 function(s)"
~~~

For confirmed bugs, please report:
- Version: functionbeat-7.9.0-linux-x86_64
- Operating System: CentOS-6-1
- Discuss Forum URL: spoke with Noémi Ványi through slack #beats
- Steps to Reproduce: I can see same results with MacOS laptop and GCP provisioned CentOS VM. Previous 7.8.1 version using the same **credentials file** and **functionbeat.yml** file succeeded with following output:

~~~"DEBUG   [gcp]   gcp/op_wait_for_function.go:57  Successfully deployed function
2020-08-27T14:43:11.850Z        DEBUG   [gcp.executor]  executor/executor.go:68 All operations successful
2020-08-27T14:43:11.850Z        DEBUG   [gcp]   gcp/cli_manager.go:50   Successfully created function 'storage'
2020-08-27T14:43:11.850Z        DEBUG   [gcp]   gcp/cli_manager.go:51   Deploy finish for function 'storage'
Function: storage, deploy successful
2020-08-27T14:43:11.850Z        DEBUG   [cli-handler]   cmd/cli_handler.go:64   Deploy execution ended"  
~~~

**Comment by rayward** [comment]
I'm getting a whole bunch of package missing errors as well. Should `./functionbeat` be generating a `go.mod` file to be bundled into the package?

**Comment by kvch** [comment]
@rayward Yes, the issue exists because of go modules. However, we need to go back to vendoring because the Beats framework supports only Golang 1.14. This seems to be incompatible with the Go 1.13 environment on GCP.

**Comment by rayward** [comment]
@aschifman I was able to deploy with 7.7.1 of functionbeat

**Comment by rayward** [comment]
@kvch I thought 1.13 supported go modules, and GCP supports this - https://cloud.google.com/functions/docs/writing/specifying-dependencies-go

**Comment by aschifman** [comment]
Thanks @rayward. Please try with 7.8.1 if you can, it had worked for me.
