### ISSUE TITLE
filebeat wildcard for directories

### ISSUE THREAD

**Issue by runningman84** [elastic/beats#2084]
It looks like filebeat does not support wildcards in directories like this:

```
/opt/codedeploy-agent/deployment-root/*/*/logs/scripts.log
```

**Comment by ruflin** [comment]
This is related to https://github.com/elastic/filebeat/issues/68 Wildcards for directories should already be supported. What is the behaviour you were expecting? Are you looking for `**` which crawls all subdirectories (and is not supported at the moment)?

**Comment by runningman84** [comment]
My folders look like this
```
/opt/codedeploy-agent/deployment-root/4b74562c-cee3-40f5-8d36-6f588eeed802/d-KYVV5AYKF/logs/scripts.log
/opt/codedeploy-agent/deployment-root/b41f722c-80e8-41e9-866e-1f11228f5ab3/d-UIIXR9K9F/logs/scripts.log
```
This config does not seem to work:
```
'/opt/codedeploy-agent/deployment-root/*/*/logs/scripts.log'
```
Do I need to change the config to this?
```
'/opt/codedeploy-agent/deployment-root/**/logs/scripts.log'
```

**Comment by ruflin** [comment]
I would expect it to work, but TBH so far I only tested `/opt/*/scripts.log` examples, means only one directory with a `*` pattern. Could you briefly tests if `/opt/codedeploy-agent/deployment-root/4b74562c-cee3-40f5-8d36-6f588eeed802/*/logs/scripts.log` works for you? Which filebeat version are you using?

**Comment by runningman84** [comment]
yes 
/opt/codedeploy-agent/deployment-root/e8be8394-bb4f-403e-abd8-03045480217d/*/logs/scripts.log
works

**Comment by ruflin** [comment]
Ok, so it seems to work with one directory but not 2 nested directories. We use directly `Glob` from Golang for the pattern: https://golang.org/pkg/path/filepath/#Glob Currently all pattern supported by `Glob` are supported by filebeat.

**Comment by runningman84** [comment]
do you know a pattern which would work here?

**Comment by andrewkroh** [comment]
@ruflin I'm thinking we should list the patterns supported (https://golang.org/pkg/path/filepath/#Match) in our documentation or link to it. Also we should put some info in there to clarify that only one wildcard is supported (assuming I understand correctly)?

If you agree I can open a new issue to add this to the docs.

**Comment by ruflin** [comment]
@andrewkroh Agree. TBH so far it wasn't clear to me that multiple `*` do not work. It also doesn't seem to be state in the Golang docs (or haven't found it yet).

**Comment by wjoel** [comment]
The lack of multiple wildcards means it's not possible to have a setup as described in [Log Management with ELK](https://docs.mesosphere.com/1.7/administration/logging/elk/) for Mesos, where paths have the format `/var/lib/mesos/slave/slaves/*/frameworks/*/executors/*/runs/latest/stdout`

From https://github.com/golang/go/issues/11862 it seems Golang will not support this any time soon, and the discussion ends with a reference to [go-zglob](https://github.com/mattn/go-zglob). Would it be possible to use that for the glob patterns in filebeat? According to [this commit](https://github.com/dcu/capn-hook/commit/1522ebd2e00db06ae86c0567f2e9b5734bf0c857) it looks like a simple change.

**Comment by ruflin** [comment]
It's definitively worth a discussion. But it seems to me we are discussing two things here: 

* Support for `**` which can go into multiple sub directories
* And replacing just one directory but multiple times with *

I'm not so much worried about the implementation work itself, more the potential side affects we are not aware of yet of which parts are also in the golang issue.

It especially see the need to support multiple `*`, I'm a little bit sceptical about `**` support. I assume zglob is doing both? To keep the default setup stable and reliable I would suggest instead of replacing the current implementation with zglob or something similar, I would make it a config option that has to be turned on specifically to get support for it. This will make it possible for use to better identify problems which could be related to it and we could test it first.

Are there alternatives to zglob? Could this be done in a few lines in filebeat itself to not have an additional dependency and be able to fix bugs directly?

**Comment by runningman84** [comment]
** is not need for my use case, this would be enough
'/opt/codedeploy-agent/deployment-root/*/*/logs/scripts.log'

**Comment by cjgeode** [comment]
Potential workaround:

Currently, unknown depth of subdirectories is not supported. 

However, if the depth is known, like it is exactly 4, you could use wildcards to do something like:
`['path/*/*/*/*']'

If limit can be 2, 3 or 4 use `['path/*/*', 'path/*/*/*', 'path/*/*/*/*']`

You can also create a shared variable to point to the root path, so your config might look like:
['${fb.watch.path}/*/*', '${fb.watch.path}/*/*/*', '${fb.watch.path}/*/*/*/*']

**Comment by tsg** [comment]
Multiple `*` are already supported. I re-confirmed this with 5.0.0-rc1, but should also work with 1.3. `**` is not supported.

@runningman84 perhaps something else was wrong in your test, can you re-try it, please?

**Comment by runningman84** [comment]
Yes it does work for me now.

**Comment by nostrebor** [comment]
This is not working for me as well. Single * works, but a matching of the format: 
    - \\network-share\subdir\*\*\*\*.log
Yields no output. The same behavior is seen in logstash. If I replace it with a only a single wildcard:
    - \\network-share\1\2\3\4\*.log
Files are discovered by both logstash and filebeat.

**Comment by raiusa** [comment]
Any update on support of * * in filebeat. 
I have logs in following directory structure.
/opt/cloudera/yarn/container-logs/application_*/container_*/*.log

**Comment by raiusa** [comment]
Sorry some how it's stripping * from directory  application_* and container_*
/opt/cloudera/yarn/container-logs/application_*/container_*/*.log

**Comment by ruflin** [comment]
@raiusa I updated your post to have it posted as code. There is no update yet on this.

**Comment by zkf9971** [comment]
I have the log files under the path like /data/*/_data/*/*/*/*/*/, for filebeat, is it possible to get the real value for these wildcard * in the path, because the * in this path represents some important information, for instance the log file /data/containers/_data/container_1/serverid_123/*/*/*/serverid_123.log, can filebeat get the value like serverid_123? Thanks a lot.
Following is snippet of my filebeat.yml for these log files:
`
filebeat.prospectors:
- input_type: log
  paths:
    - /data/*/_data/*/*/*/*/*/*.log
`

**Comment by ruflin** [comment]
@zkf9971 As far as I understand you want to add the path names as fields to the event? If yes, this would be a different feature request then this one here.

**Comment by ruflin** [comment]
@nostrebor @zkf9971 @raiusa @runningman84 https://github.com/elastic/beats/pull/3980 ws just merged into master. It would be great if you could check if that works with your use case. The snapshot builds can be found here: https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/

**Comment by ruflin** [comment]
@Subtalime This change is only in the 6.x releases. For further questions please use discuss.

**Comment by hsluoyz** [comment]
Hi @ruflin 

> This is related to [elastic/filebeat#68](https://github.com/elastic/filebeat/issues/68) Wildcards for directories should already be supported. What is the behaviour you were expecting? Are you looking for `**` which crawls all subdirectories (and is not supported at the moment)?

https://github.com/elastic/filebeat/issues/68 is 404 now. What is the latest link?

**Comment by andrewkroh** [comment]
That repo no longer exists, but you can read about glob support in the Filebeat documentation.

https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#input-paths
