### ISSUE TITLE
[Metricbeat/UI] Misleading naming of Azure metrics

### ISSUE THREAD

**Issue by nerophon** [elastic/beats#20845]
Version: 7.2.x

A user has found that some of the naming of Azure metrics is inconsistent and leads to confusion when trying to use the UI in Kibana.

Firstly, most metrics follow the pattern _azure.metrics.*_, but a few don't which makes it seem like they are missing from the data and index pattern. For example _azure.compute_vm_ is missing the "metrics." part of the pattern.

Secondly, something is wrong with the monitor metricset, insofar as the the included visualisations don't show it by default; the only way to make it appear is to deliberately filter for it.

Please find attached some screenshots illustrating how these problems manifest in the UI and lead to confusion:

![azure-metric-instead-of-azure-monitor](https://user-images.githubusercontent.com/4341829/91553775-da139680-e925-11ea-9622-4150c9a9b181.png)
![azure-metricset-monitor-discovery](https://user-images.githubusercontent.com/4341829/91553779-dbdd5a00-e925-11ea-9904-1d825d151b8f.png)
![Metricset-not-showing-monitor](https://user-images.githubusercontent.com/4341829/91553781-dc75f080-e925-11ea-9c61-1f54eba3b924.png)

**Comment by narph** [comment]
hi @nerophon , few things to understand here:
- the azure module was introduced in 7.5 , can you provide us with the exact Metricbeat version
- can you provide us also with the configuration for the module as well 

> Firstly, most metrics follow the pattern azure.metrics.*, but a few don't which makes it seem like they are missing from the data and index pattern. For example azure.compute_vm is missing the "metrics." part of the pattern.

There should be any `azure.metrics.` type of data coming from the azure module, but `azure.monitor.metrics` which are the events resulted by configuring the `monitor` metricset.

The `azure.compute_vm` metricset is a different metricset in this case, which contains vm specific metrics and will not require the `metrics` object. This is consistent to other existing modules inside Metricbeat also documented inside the elastic docs.

I am not sure what is going on, but logs will help here as well (can you enable debug logging) and provide them to us.

**Comment by narph** [comment]
@nerophon , no answer has been provided for some time now, will close issue, feel free to reopen if necessary.
