### ISSUE TITLE
Windows Event Log integration module for Elastic Agent

### ISSUE THREAD

**Issue by dancs85** [elastic/beats#20886]
**Describe the enhancement:**
The Elastic Agent should have a module that replicates the functionality of Winlogbeat, including the Powershell, Security and Sysmon modules. If possible, Sysmon itself should be able to be bundled in (if licencing allows) as this will populate a lot of the information the SIEM app uses. 

**Describe a specific use case for the enhancement or feature:**
The Windows event logs are used in both Observability and Security arenas.
Bundling sysmon will cover users who don't opt to use the Elastic Endpoint module (I believe Sysmon/Elastic Endpoint generate very similar logs)

**Comment by ph** [comment]
@dancs85 Is under our radar, we want to do some refactor of Winlogbeat/filebeat to add to the elastic agent. But having better windows support is one of our priority.

**Comment by ph** [comment]
I think we are able to close this, the Elastic Agent now support the window event logs via https://github.com/elastic/beats/pull/19622

@urso WDYT?

**Comment by urso** [comment]
The [windows package](https://github.com/elastic/integrations/tree/master/packages/windows) already makes use of the winlog input in Agent. For Sysmon and others we should consider separate integrations. But on the Beats/Agent side itself I think we are done.
