### ISSUE TITLE
[Filebeat] Nginx ingress-controller Dashboard

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#20897]
**Describe the enhancement:**
Add a dashboard visualizing key fields for the Nginx's [ingress-controller](https://www.elastic.co/guide/en/beats/filebeat/master/exported-fields-nginx.html#_ingress_controller).

The ingress-controller [documentation](https://kubernetes.github.io/ingress-nginx/user-guide/monitoring/) has a section describing what to monitor.

**Comment by ChrsMark** [comment]
Closing this through #21052.
