### ISSUE TITLE
Show uninterruptible sleep in process_summary

### ISSUE THREAD

**Issue by micoq** [elastic/beats#20902]
Currently, processes in a uninterruptible sleep (state `D`) are counted as idle processes:

https://github.com/elastic/beats/blob/2a0e0998243db56d0bfd681ff3cb06183166bdd5/metricbeat/module/system/process_summary/process_summary.go#L86-L92

It could useful to create a separate bucket for these processes (eg. many processes can be blocked on a shared IO resource).

**Comment by micoq** [comment]
The "Idle" state defined in the gosigar library is a little bit confusing since it corresponds to the uninterruptible process state:
https://github.com/cloudfoundry/gosigar/blob/0bb2fe4a1c0cdce8cbe6bfe2c9d375cab4cc15c7/sigar_interface.go#L106

and the `I` state doesn't seam to really exist.

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
