### ISSUE TITLE
Packetbeat flow visualization: wrong aggregation for source.bytes and destination.bytes

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#20944]
Version: 7.9.0
Operation System: MacOS X
Steps to Reproduce:

1. Start up Elasticsearch and Kibana.

1. Download Packetbeat, load Kibana dashboards, and start it up.

2. Visit the "[Packetbeat] Flows ECS" dashboard and look at the "Network Traffic Between Hosts [Packetbeat Flows] ECS" visualization.

3. Set the time picker duration to something small like "15 minutes".

3. Notice that it has unexpectedly large numbers in the "Source Bytes" and "Destination Bytes" columns.

**Comment by ycombinator** [comment]
Doing some testing locally, it's easy to reproduce the unexpectedly large numbers for the "Source Bytes" and "Destination Bytes" columns in the "Network Traffic Between Hosts [Packetbeat Flows] ECS" visualization.

<img width="1806" alt="Screen Shot 2020-09-02 at 4 44 10 PM" src="https://user-images.githubusercontent.com/51061/92048706-3cf99900-ed3d-11ea-870d-e0f8db5a3fcc.png">

Let's focus on "Destination Bytes". I suspect whatever we find about it will apply to "Source Bytes" as well.

Looking at the definition of the visualization, we can see that the "Destination Bytes" field is calculated by doing a sum of the `destination.bytes` field.

<img width="1806" alt="Screen Shot 2020-09-02 at 4 46 39 PM" src="https://user-images.githubusercontent.com/51061/92048645-18052600-ed3d-11ea-9e33-0c60416b48c3.png">

So next I looked at the flow event documents, ordered over time, while focussing on the `destination.bytes` field. Concretely, I ran the following query in Kibana Console:

```
GET packetbeat-*/_search?filter_path=hits.hits._source
{
  "_source": [
    "source.port",
    "destination.bytes",
    "destination.port"
    ],
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "type": "flow"
          }
        },
        {
          "term": {
            "destination.port": 9200
          }
        }
      ]
    }
  }, 
  "aggs": {
    "type": {
      "terms": {
        "field": "type",
        "size": 10
      }
    }
  },
  "sort": [
    {
      "@timestamp": {
        "order": "desc"
      }
    }
  ]
}
```

The results look like this:
```
{
  "hits" : {
    "hits" : [
      {
        "_source" : {
          "destination" : {
            "port" : 9200,
            "bytes" : 307168
          },
          "source" : {
            "port" : 62430
          }
        }
      },
      {
        "_source" : {
          "destination" : {
            "port" : 9200,
            "bytes" : 303755
          },
          "source" : {
            "port" : 62430
          }
        }
      },
      {
        "_source" : {
          "destination" : {
            "port" : 9200,
            "bytes" : 300343
          },
          "source" : {
            "port" : 62430
          }
        }
      },
      {
        "_source" : {
          "destination" : {
            "port" : 9200,
            "bytes" : 296939
          },
          "source" : {
            "port" : 62430
          }
        }
      },
      {
        "_source" : {
          "destination" : {
            "port" : 9200,
            "bytes" : 293533
          },
          "source" : {
            "port" : 62430
          }
        }
      },
      {
        "_source" : {
          "destination" : {
            "port" : 9200,
            "bytes" : 290130
          },
          "source" : {
            "port" : 62430
          }
        }
      },
      {
        "_source" : {
          "destination" : {
            "port" : 9200,
            "bytes" : 286722
          },
          "source" : {
            "port" : 62430
          }
        }
      },
      {
        "_source" : {
          "destination" : {
            "port" : 9200,
            "bytes" : 283326
          },
          "source" : {
            "port" : 62430
          }
        }
      },
      {
        "_source" : {
          "destination" : {
            "port" : 9200,
            "bytes" : 279854
          },
          "source" : {
            "port" : 62430
          }
        }
      },
      {
        "_source" : {
          "destination" : {
            "port" : 9200,
            "bytes" : 276379
          },
          "source" : {
            "port" : 62430
          }
        }
      }
    ]
  }
}
```

As you can see the value of `destination.bytes` keeps increasing over time, **strongly indicating that it is a cumulative value**.

Indeed, if I temporarily fix the visualization to calculate "Destination Bytes" as the **max** (as opposed to sum) of `destination.bytes`, the numbers look much more realistic.

<img width="1806" alt="Screen Shot 2020-09-02 at 4 50 44 PM" src="https://user-images.githubusercontent.com/51061/92048615-f4da7680-ed3c-11ea-877e-b7cb2e5b3c77.png">

**Comment by andrewkroh** [comment]
The viz should probably have a filter for final flows only.

> Packetbeat sets the flow.final flag to false to indicate that the event contains an intermediate report about a flow that it’s tracking. When the flow completes, Packetbeat sends one last event with flow.final set to true. If you want to aggregate sums of traffic, you need to filter on final:true, or use some other technique, so that you get only the latest update from each flow. You can disable intermediate reports by setting period: -1s.

source: https://www.elastic.co/guide/en/beats/packetbeat/current/configuration-flows.html

If you use the Network tab in the Security app in Kibana does it show the correct values? I think it has this filter built-in.

**Comment by ycombinator** [comment]
Thanks @andrewkroh. The Flows visualization in the Network tab of the Security app shows the same values as the Packetbeat visualization (pages loaded a couple seconds apart so values are slightly different):

### Flows visualization

<img width="1647" alt="Screen Shot 2020-09-03 at 4 47 08 AM" src="https://user-images.githubusercontent.com/51061/92111392-14a38600-eda1-11ea-83c9-460fbda0753d.png">


### Packetbeat visualization

<img width="1320" alt="Screen Shot 2020-09-03 at 4 47 21 AM" src="https://user-images.githubusercontent.com/51061/92111375-0fded200-eda1-11ea-9bcd-606390ce5aa3.png">

I inspected the Flows visualization from the Security app and here's the request it's sending to ES. It uses the `sum` metric agg on `destination.bytes` and doesn't seem to have the filter for final flows (same as the Packetbeat visualization).

```
{
  "aggregations": {
    "top_n_flow_count": {
      "cardinality": {
        "field": "destination.ip"
      }
    },
    "destination": {
      "terms": {
        "field": "destination.ip",
        "size": 10,
        "order": {
          "bytes_in": "desc"
        }
      },
      "aggs": {
        "bytes_in": {
          "sum": {
            "field": "source.bytes"
          }
        },
        "bytes_out": {
          "sum": {
            "field": "destination.bytes"
          }
        },
        "domain": {
          "terms": {
            "field": "destination.domain",
            "order": {
              "timestamp": "desc"
            }
          },
          "aggs": {
            "timestamp": {
              "max": {
                "field": "@timestamp"
              }
            }
          }
        },
        "location": {
          "filter": {
            "exists": {
              "field": "destination.geo"
            }
          },
          "aggs": {
            "top_geo": {
              "top_hits": {
                "_source": "destination.geo.*",
                "size": 1
              }
            }
          }
        },
        "autonomous_system": {
          "filter": {
            "exists": {
              "field": "destination.as"
            }
          },
          "aggs": {
            "top_as": {
              "top_hits": {
                "_source": "destination.as.*",
                "size": 1
              }
            }
          }
        },
        "flows": {
          "cardinality": {
            "field": "network.community_id"
          }
        },
        "source_ips": {
          "cardinality": {
            "field": "source.ip"
          }
        }
      }
    }
  },
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [],
            "filter": [
              {
                "match_all": {}
              }
            ],
            "should": [],
            "must_not": []
          }
        },
        {
          "range": {
            "@timestamp": {
              "gte": "2020-09-02T11:46:49.993Z",
              "lte": "2020-09-03T11:46:49.993Z",
              "format": "strict_date_optional_time"
            }
          }
        }
      ]
    }
  }
}```
