### ISSUE TITLE
Add dashboards for elasticsearch module

### ISSUE THREAD

**Issue by matschaffer** [elastic/beats#20945]
**Describe the enhancement:**

https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-elasticsearch-node_stats.html has a bunch of interesting metrics that we'd like to have graphs for, but it's a little unclear what each metric is showing.

It'd be awesome to have a packaged dashboard available via `metricbeat setup` that provided things like percentage of time spent in young/old GC.

**Describe a specific use case for the enhancement or feature:**

For debugging production elasticsearch clusters :)

**Comment by matschaffer** [comment]
guessing platforms team based on https://github.com/elastic/beats/pull/20812, feel free to re-label as necesary.

**Comment by matschaffer** [comment]
@jasonrhodes If we have any issues open to cover an an elasticsearch integration we could probably close this issue in favor of those.

**Comment by smith** [comment]
Not prioritizing this at this time.
