### ISSUE TITLE
DOCUMENTATION versus functionality mismatch for logging.selectors: ["publish"] should be logging.selectors: ["publisher"]

### ISSUE THREAD

**Issue by jrykowski-huron** [elastic/beats#20970]
Various online documentation pages refer to "publish" selector, however at least for 7.9.0 filebeat (where tested) that **value needs to be "publisher**".   for example https://www.elastic.co/guide/en/beats/filebeat/current/configuration-logging.html#selectors
and also https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-reference-yml.html

**Comment by dedemorton** [comment]
Also there's a very old issue open here that we should resolve: https://github.com/elastic/beats/issues/7603

**Comment by dedemorton** [comment]
Looked into this a bit more.... It looks like the "publish" selector does still exist, but it doesn't show the published events like it has in previous releases. I'm not sure when the behavior changed, but users who expect to see the published events will be disappointed.

Users who want to see the published events are better off running in debug mode with _no_ selectors, or specifying the "processors" selector. 

There *is* a valid "publisher" selector, so I will use that in the docs, even though the behavior is not the same as the old "publish" selector. I'll update the text accordingly.
