### ISSUE TITLE
Add support for different Azure Cloud environments in Metricbeat

### ISSUE THREAD

**Issue by kaltman** [elastic/beats#20988]
Metricbeat Azure module currently does not have an option to override the resource manager endpoint or the active directory endpoint.

Example:
Attempting to use Metricbeat Azure module against Azure Govcloud results in:

`
failed to retrieve resources: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/{SUBSCRIPTION_ID}/resources?%24filter=resourceType+eq+%27Microsoft.ContainerInstance%2FcontainerGroups%27&api-version=2019-03-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: 
{"error":"invalid_request","error_description":"AADSTS900439: Confidential Client requests are not supported on the public endpoint (login.microsoftonline.com) for tenants in the Azure Government cloud. Send your login requests to https://login.microsoftonline.us instead. Please see https://devblogs.microsoft.com/azuregov/azure-government-aad-authority-endpoint-update/ for more details}
`

Currently we have a way to control the endpoint in [Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-azure.html) via: [resource_manager_endpoint](https://github.com/elastic/beats/pull/17659) would be great to have a similar option in Metricbeat.

**Comment by bhoskins7** [comment]
I'm curious is their a short term workaround to change the endpoint to something other than public azure endpoint in metricbeat?
