### ISSUE TITLE
[Elastic Agent] Disable upgrade capability of Agent

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#21001]
With https://github.com/elastic/beats/issues/20205 Fleet will be able to upgrade an Agent. But not in all cases upgrade of Agents should be enabled. Some examples:

* Agent running Docker should be upgraded through the container
* Agent administrator wants to use his own tooling for upgrade
* Agent does not have the permissions, no root.

**Comment by neptunian** [comment]
@ruflin Should we also be guarding against trying to upgrade if their version is < 7.10 in which case it's not possible to upgrade it?

**Comment by ph** [comment]
@neptunian Yes I think this is a good idea. a lot of things changed between 7.9 and 7.10, structure on disk etc.

**Comment by neptunian** [comment]
@ph @hbharding Are we wanting to still show the "Upgrade Available" indications in the UI and just disable the actual upgrade buttons or not show these indications at all if they can't take the action?

**Comment by ruflin** [comment]
Perhaps we can turn this on the head to simplify things. An Elastic Agent must report that it is upgradable, so the default is it is not. Like this we don't have to cover all the special cases where it is not but the Agent does.

**Comment by blakerouse** [comment]
@ruflin I like that idea, Agent should tell Kibana, yes I am upgradable, then Kibana should do the version comparison.

**Comment by ph** [comment]
:+1: Good plan @ruflin.

**Comment by blakerouse** [comment]
The #21206 branch now includes the logic to prevent upgrading of Elastic Agent unless the conditions are correct.

I filed #21318 to cover the reporting aspect.
