### ISSUE TITLE
[Fleet] Tests for the Agent restructure / symlink work

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#21023]
In this PR we had some test questions, since it is closed I'd like to open an issue for testing and automation work and track it here:
https://github.com/elastic/beats/pull/20400#issuecomment-688492552

@michalpristas can you make sure any changes that break the e2e-testing are fixed?

@rahulgupta-qasource we can use this as a running tally of questions + tests.  I'll seed the list with what questions we had from the pr.

Queries:

Could you please let us know if we have to validate the above packages on 7.9.2-SNAPSHOT or 8.0.0-SNAPSHOT also.
 - It was not backported to 7.9.2, so no testing needed there.  
 - 8.0 is a valid code base to test against, but we need not do this.  Once thru is ok.

Could you please share the exact steps to execute the upgrade/rollback scenarios (say as per comment #20400  (review) , #20400  (comment) and elastic/beats#20400 (comment) )
Please let us know if we are missing something to validate this ticket or need to add any other validation scenario.
 - I think the UI side is not implemented yet, so it isn't testable.  If / when it is we can do so and Engg can confirm when all moving / needed parts are merged and backported.  Thanks.

**Comment by ph** [comment]
The upgrade / rollback scenario aren't implemented yet, its still a work in progress.

**Comment by rahulgupta-qasource** [comment]
Hi @EricDavisX / @ph

Thank you for sharing the feedback.

Please keep us posted once upgrade / rollback scenarios are implemented and share the exact steps to validate the same.

**Comment by EricDavisX** [comment]
I think we'll want to leave it open to confirm the test material is updated.  we're still compiling how to test it, I've started putting details and open questions into the main ticket -> https://github.com/elastic/beats/issues/20205#issuecomment-708421296

and the automation ticket has details of how to trigger it:
https://github.com/elastic/e2e-testing/issues/341#issuecomment-708497411

**Comment by EricDavisX** [comment]
@rahulgupta-qasource about the upgrade-agent cases, it is testable and we will track that separately as well
