### ISSUE TITLE
[Elastic Agent] Add documentation for new input substitution and conditions

### ISSUE THREAD

**Issue by blakerouse** [elastic/beats#21040]
We need to add documentation for the new input substitution and EQL-like condition, that is shipping as experimental in 7.10.

See #20839 and #20994 for information on the syntax.

**Comment by ph** [comment]
cc @dedemorton

**Comment by ph** [comment]
Tasks:
- create outline
- explain eql subset of the syntax.

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/beats/pull/22409
