### ISSUE TITLE
provide mapping as artefacts for use with component templates

### ISSUE THREAD

**Issue by jaakoob** [elastic/beats#21051]
**Describe the enhancement:**

It would be nice if the mappings for the beats fields would be published as artefacts for use with content templates.

**Describe a specific use case for the enhancement or feature:**

No Elastic Beat is directly connected to Logstash and a Index Pattern which differs from the standard Beat Index Pattern/ ILM Policys is used. It should be possible to load an appropriate mapping for the used beats as component template. Therefore the mappings are required to be released as artefacts.

**Comment by ruflin** [comment]
@jaakoob I wonder if the ingest manager will solve your problem here: https://www.elastic.co/blog/introducing-elastic-agent-and-ingest-manager The assets are all loaded centrally through Kibana instead of from the Beats. Also the indexing strategy changed quite a bit which might help you too.

**Comment by jaakoob** [comment]
I use an extended ECS so ingest manager would have to provide component templates so that I can use the beat fields in combination with my extended ECS. I am also not interested in dashboard and visualization templates, so ingest manger can´t do much for me.

**Comment by ruflin** [comment]
Having a package with ECS components and parts is a discussion we had in an other issue, but couldn't find it. I know @webmat was thinking about this too.

**Comment by webmat** [comment]
Yeah step 1 of before working on an ECS package is literally just to produce new artifacts in the ECS project (tracked here https://github.com/elastic/ecs/issues/961), but @jaakoob has already chimed in over there :-)

**Comment by HonzaKral** [comment]
Getting artefacts based on ECS would be ideal, but as an interim solution it would be great to have the settings and mappings installed as component templates with the index template consisting primarily of just the list of those components. That way users could reuse the mappings/settings without having to modify the provided template which requires maintenance with every new release. Previously this was easily solved by creating another template that would be merged with the default one but with component template this now requires essentially copy/pasting the entire template.

This is also the case for templates managed by the elastic agent.
