### ISSUE TITLE
Capture pagetables with Metricbeat

### ISSUE THREAD

**Issue by bczifra** [elastic/beats#21091]
**Describe the enhancement:**
This enhancement request is for Metricbeat's  to capture `PageTables` from the `/[proc](https://man7.org/linux/man-pages/man5/proc.5.html)/meminfo ` output as part of the [memory metric set fields](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-system-memory.html).

**Comment by fearful-symmetry** [comment]
Did some hunting around, and I'm kind of surprised we don't report this already. We'll need to add it to elastic/go-sysinfo and go from there. _However_ because this metric is probably exclusive to linux, it'll end up in `linux/memory` and not `system/memory`. @bczifra

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
