### ISSUE TITLE
Allow metricbeat haproxy module to use the stats unix socket.

### ISSUE THREAD

**Issue by jhaprins** [elastic/beats#21104]
HaProxy on a unix host can provide statistics output in different ways.
Either using a unix socket, a tcp socket or an http socket. 
The http socket is often used for external monitoring or quick checks, while unix socket is often used only locally on the system and not accessible from remote. 
For the haproxy beats module is a module that is typically running on the local system, it would be perfect if it could use the local unix socket for read access to the haproxy statistics. This would make it unnecessary to put the authentication credentials of the http socket in the haproxy beats module configuration.

**Comment by rcuperus** [comment]
This is possible by defining the host as follows:
`hosts = ["unix:///path/to/socket"]`

**Comment by andresrc** [comment]
We should add it to the documentation.

**Comment by dedemorton** [comment]
Closed by #23727
