### ISSUE TITLE
Call one API for Kibana MB module (for 8.0)

### ISSUE THREAD

**Issue by chrisronline** [elastic/beats#21119]
Right now, there are two endpoints the Kibana MB module (with `xpack.enabled`: true) calls:

`/api/stats` and `/api/settings`

However, the data returned from the `/api/settings` API is (or will be before 8.0) also exposed from the `/api/stats` endpoint, with the exception of the `xpack` key, but that is deprecated and will be removed in 8.0. 

For 8.0, we'd like the Kibana MB module to only call the `/api/stats` endpoint to collect all the data to index the two document types `kibana_stats` and `kibana_settings`.

**Comment by lukeelmers** [comment]
@elastic/integrations-services The Kibana Core team is planning to remove `/api/settings` in 8.0. Is switching over to `/api/stats` for this data still on the Metricbeat roadmap?

**Comment by jlind23** [comment]
Backlog grooming: Closing for now as 8.0 is already out.

**Comment by consulthys** [comment]
@jlind23 Can you or someone provide insights as to why this issue and the [related PR](https://github.com/elastic/beats/pull/28410) have been closed without a clear resolution? The `kibana` Metricbeat module is still calling the non-existing `/api/settings` API, but that doesn't make much sense. 
Thanks for your feedback!
