### ISSUE TITLE
[Elastic Agent] Agent's Readme need to be modified to reflect Agent reality

### ISSUE THREAD

**Issue by ph** [elastic/beats#21122]
Two links related to our Beats Agent is giving a 404 error.

(https://www.elastic.co/guide/en/beats/elastic-agent/7.9/index.html, https://www.elastic.co/guide/en/beats/elastic-agent/7.9/elastic-agent-installation-configuration.html)

dev-tools/packaging/templates/common/README.md.tmpl

The link should be adjusted to point to ingest manager.

**Comment by narph** [comment]
Links are working now, can be closed
