### ISSUE TITLE
Metricbeat 7.4.2 error: metricset 'aws/lambda' not found

### ISSUE THREAD

**Issue by EmViKay** [elastic/beats#21126]
We are using Metricbeat 7.4.2. Few days ago we have tried enable aws/lambda module. 
Followed documentation from here: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-aws-lambda.html
On linux and Windows we get the error : Exiting: 1 error: metricset 'aws/lambda' not found and service down.
Can someone help?

```- module: aws
  period: 300s
  metricsets:
    - lambda
  access_key_id: '321'
  secret_access_key: '123'

**Comment by kaiyan-sheng** [comment]
@EmViKay I believe we added `aws/lambda` support into Metricbeat in 7.7 release. That's why it's showing not found in 7.4.2. Could you please upgrade to newer version Metricbeat please? Thanks! I will close this issue for now.
