### ISSUE TITLE
[docs] improve registry files description after changes introduced in 7.9.0

### ISSUE THREAD

**Issue by immon** [elastic/beats#21158]
**Describe the enhancement:**

With newly introduced filebeat registry format it would be helpful to reveal more details around registry log.json and the marker file to the docs. For example here https://www.elastic.co/guide/en/beats/filebeat/current/configuration-general-options.html#_registry_path

**Describe a specific use case for the enhancement or feature:**

**Comment by vsxen** [comment]
Whati's the different between log.json  and data.json?

**Comment by immon** [comment]
log.json includes a list of actions made to the registry. Once the log file reaches 10MB a snapshot is created. Snapshot includes current registry state in data.json-like format but under a file named `<last-action-id>.json`.

There is also active.dat file including the path to last snapshot file.

I might be not fully right here and beats developers are the best to ask for a comment.

**Comment by andresrc** [comment]
we won't initially add this documentation as we don't want this part to be considered a public API. We will look for other options to make this information available for consumers.

**Comment by MikeSaveItiviti** [comment]
I see that the log.json file has registry information and does appear to be historical, however I see no other registry file like the "old" data.json file which had one line per monitored file for input type log like I used to see. Earlier comments make it seem as if another file representing the currently monitored files states still exist. I see no documentation around this and it appears based on code comparisons of 7.8.0 to 7.9.0 that log.json replaces data.json. Some documentation would have been nice to see and in particular, I believe, should have been provided in 7.9.0 release notes.
