### ISSUE TITLE
[Elastic Agent] Support retry

### ISSUE THREAD

**Issue by david-kow** [elastic/beats#21167]
It would be great if Elastic Agent had a configurable retry for enrolment (and other commands if that's not the case yet). It would simplify the logic for any init scripts and orchestration in cases where there are intermittent network issues or when Kibana is just being started and it's not available yet.

**Comment by blakerouse** [comment]
@michalpristas Doesn't Agent already perform retries?

**Comment by ph** [comment]
I don't think this is the case today.

Are you suggesting an infinite retry with a backoff?

**Comment by david-kow** [comment]
I was initially thinking about a configurable retry that allows specifying retry count and timeout with backoff. But I realized that for any successful enrolment, one would need to query Kibana first to obtain the token, so being resilient against Kibana not yet started is not really that useful. If there would be a command that didn't require knowing the token upfront (and, for example, use the default) then the retry would be more relevant. 

I leave up to you whether to leave this open.

**Comment by ruflin** [comment]
I need @michalpristas for details on this. If we don't I think it would be valuable to support.

**Comment by michalpristas** [comment]
if we imagine retry as running install command exiting with code 0 and let agent do retry in a background, we dont have that. 
we do have a normal retry which performs enroll in a loop with some backoff configured. this is not configurable and defaults to `min: 60s, max: 10m`

i think we should close this

**Comment by jlind23** [comment]
Agree.
