### ISSUE TITLE
Module dependency on Shopify/sarama is broken with every versioned release

### ISSUE THREAD

**Issue by seanhoughton** [elastic/beats#21188]
- Version: go 1.14.3
- Operating System: linux (ubuntu 20.04)

- Steps to Reproduce: 

create main.go with the following content

```
package main
import "github.com/elastic/beats/v7"
func main() {
	//beats.foo()
}
```
run `go build`

output is

```
go: finding module for package github.com/elastic/beats/v7
go: downloading github.com/elastic/beats/v7 v7.9.1
go: downloading github.com/elastic/beats v1.3.1
go: found github.com/elastic/beats/v7 in github.com/elastic/beats/v7 v7.9.1
go: github.com/elastic/beats/v7@v7.9.1 requires
        github.com/Shopify/sarama@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by seanhoughton** [comment]
It looks like the cause of this problem is `replace` directives in the beats `go.mod` file. These are not inherited by dependent projects (see https://github.com/golang/go/issues/37261) and are only intended for local development. If replacements are required for this module to build I would suggest making them very clear in the readme documentation.

As of v7.9.1 all downstream projects will need the following replacements in their own `go.mod` file.

```
replace (
	github.com/Shopify/sarama => github.com/elastic/sarama v1.19.1-0.20200629123429-0e7b69039eec
	github.com/docker/docker v1.13.1 => github.com/docker/engine v0.0.0-20191113042239-ea84732a7725
	github.com/dop251/goja => github.com/andrewkroh/goja v0.0.0-20190128172624-dd2ac4456e20
	github.com/fsnotify/fsevents => github.com/elastic/fsevents v0.0.0-20181029231046-e1d381a4d270
)
```

**Comment by kvch** [comment]
Replace directives are indeed have to be added to your `go.mod` file. However, AFAIK it has not changed in v7.9.1, but was the case since adopting go modules. Our Beat generator automatically adds the replace directives to the `go.mod` file of the generated Beat. May I ask why are you not using it?

**Comment by seanhoughton** [comment]
The beat I was working on was generated with the tools before the go module support was added and I was working on making it work with modules. The migration docs don't mention anything about updating your go.mod file

https://www.elastic.co/guide/en/beats/devguide/current/newbeat-migrate-gomodules.html

I ran in to a ton of problems updating the beat to work with v7.9.1 (it still doesn't work without manually hacking the python requirements.txt in the modcache folder).

**Comment by kvch** [comment]
There is a section about adding the replace directives:

> Make sure to add the approprite replace directives from the go.mod file of Beats: https://github.com/elastic/beats/tree/master/go.mod Unfortunately, this workaround is needed to make sure your Beat can be compiled.

Is this not clear? Should we reword it?

**Comment by kvch** [comment]
Also, for these issues, please open a question on Discuss next time, not a GH issue. GH issues are reserved for confirmed bugs, not questions.

**Comment by seanhoughton** [comment]
Somethow I missed that line in the docs. Sorry for the GH issue, I brought up the next problem I had on the forum.

**Comment by jpfreyen** [comment]
To me:

github.com/Shopify/sarama => github.com/elastic/sarama v1.19.1-0.20200629123429-0e7b69039eec

needs to use a more up-to-date sarama, like github.com/Shopify/sarama v1.29.1.

the file gssapi_kerberos.go has moved on and added to the DisablePAFXFAST to type GSSAPIConfig struct.  The official Shopify/sarama go package mentions when this was first added, back July 2 2019 via v1.23.0, 2 years ago: https://pkg.go.dev/github.com/Shopify/sarama

**Comment by jpfreyen** [comment]
I don't know if it's a 'new' issue, but I think the issue still lurks until the sarama package is unwound to use more recent versions in filebeat.

**Comment by faec** [comment]
@jpfreyen FYI: our fork is active, and its Sarama baseline version is 1.27.2 (Golang module dependency specs are weird and sometimes misleading; see the README at https://github.com/elastic/sarama for version details). It is about due for a bump, but it has been updated this year :-)

**Comment by jpfreyen** [comment]
So the https://github.com/elastic/sarama/blob/v1.23.1-elastic release doesn't have an updated type GSSAPIConfig struct

**Comment by jpfreyen** [comment]
the repo says the latest release is v1.23.1-elastic which is old:

![Screen Shot 2021-08-20 at 9 00 07 AM](https://user-images.githubusercontent.com/10945795/130261183-ed79c230-d368-40af-8032-c39ced7d904b.png)

**Comment by Davide95** [comment]
Hi everyone

I have a similar issue.
If I run
`go get github.com/elastic/beats/v7`
it returns
```
go get: github.com/elastic/beats/v7@none updating to
        github.com/elastic/beats/v7@v7.15.0 requires
        github.com/Shopify/sarama@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```
any idea on how to fix it? Thanks in advance
