### ISSUE TITLE
Document usage of filebeat with OpenShift

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#21189]
Our solution currently work with OpenShift, both with Docker and CRI-O. However this is not shown in the documentation.

The goal of this issue is to document this support, providing if possible example manifests, for both 7.x and 6.8.x.

**Comment by rajputvishwas** [comment]
Is this issue open?

**Comment by ChrsMark** [comment]
@rajputvishwas yes

**Comment by ChrsMark** [comment]
Our solution currently (`7.x`) versions can support multiple kinds of container runtimes like cri-o or docker. This is possible through the [container input](https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-container.html.

However this is not possible in with `6.8.x` versions and [docker input](https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-docker.html) should be used instead. We have a working  example on how this can be used to work with Openshift and cri-o. I will add this to the respective docs for `6.8.x`.
