### ISSUE TITLE
filebeat azure module not mapping event.category for activitylogs

### ISSUE THREAD

**Issue by pwen090** [elastic/beats#21190]
Filebeat Azure module does not seem to be mapping Azure activitylogs event.category field. This causes most Azure detections to fail. For example rules like "Azure Diagnostic Settings Deletion" will not match because event.category is missing. The event is shown in Elastic with category set within azure.activitylogs.properties.eventCategory but this does not seem to be mapped to event.category which the detection rules are looking for. Might be related to other mapping issues noted here: #20990 

- Version: Filebeat 7.9.1
- Operating System: Windows

**Comment by bm11100** [comment]
We'll be updating all the detection rules to remove `event.category` - https://github.com/elastic/detection-rules/issues/333

These rules are targeted for the 7.10 release.

**Comment by leehinman** [comment]
@pwen090 do you have a list of expected values for azure.activitylogs.properties.eventCategory that we could use for a mapping to event.category ?
