### ISSUE TITLE
Check ingress_controller fileset compatibility with newer versions

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#21198]
According to the documentation, the `ingress_controller` fileset has been tested with version 0.28.0 of [ingress-nginx](https://github.com/kubernetes/ingress-nginx).

However, there have been multiple additional [releases](https://github.com/kubernetes/ingress-nginx/releases) (up to 3.x). We should check whether the fileset works with newer versions and document it.

**Comment by ChrsMark** [comment]
Thanks for opening this @andresrc . The thing here is that versioning is a little bit tricky. Note that there is versions like `3.x` named `ingress-nginx-3.2.0` and versions like `v0.35.0` named `controller-v0.35.0`. 
`3.2.0` is the helm chart version, in that chart is running ingress controller version `0.35.0`.

The version we are interested in is just he `controller` version.
So we tested the fileset with `0.28.0` and now the latest version of the service is `0.35.0` means that we have not diverge so much. I will verify with this latest version and update the docs.
