### ISSUE TITLE
[Elastic Agent] Allow the elastic agent to receive new Kibana host and reconnect to them.

### ISSUE THREAD

**Issue by ph** [elastic/beats#21231]
in https://github.com/elastic/kibana/issues/72731 we have added support for configuring multiple Kibana host in the UI but we haven't completed the loop on the Elastic Agent side.

**Comment by ph** [comment]
@blakerouse I think we previously had a discussion concerning how we could handle theses kind of changes on the Elastic Agent, did we meant to restart the Agent on some configuration changes?

**Comment by blakerouse** [comment]
@ph The idea is that this information will be sent down from Fleet in the configuration, from there Agent will update its connection information. I do not see the need for Agent to have to restart in this case.

I think the only real case we need Agent to do a full restart is switching between standalone more and Fleet mode.

**Comment by ph** [comment]
@blakerouse sound good, the above PR does exactly that, So I think we need to update the local hosts list and probably reconnect to rebalance the connections.

For the restart I was thinking about logging change.

**Comment by blakerouse** [comment]
@ph Yes probably will have to restart on logging change.

**Comment by ruflin** [comment]
I would hope fo the logging change we don't need a restart but I assume this is off topic here. Do we have an issue to discuss this further?
