### ISSUE TITLE
Review windows flaky tests

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#21235]
As part of the migration to the new pipeline, we have found [several test issues](https://github.com/elastic/beats/issues?q=is%3Aopen+is%3Aissue+author%3Av1v+label%3ATeam%3APlatforms) that are blocking enabling the windows side. We should investigate them and either fix or disable them.

**Comment by narph** [comment]
@andresrc , all the flaky tests for windows 7 32 bit and windows 2008 have been reviewed fixed or skipped, PR's merged, let me know if we should keep this issue still open

**Comment by andresrc** [comment]
Thanks!!
