### ISSUE TITLE
elastic-agent uninstall command is unable to uninstall the elastic-agent on endpoint

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#21247]
**Kibana version:**
Kibana: 8.0.0-SNAPSHOT

**Elasticsearch version:**
Elasticsearch: 8.0.0-SNAPSHOT

**Host OS and Browser version:**
Windows 10 , All

**Original install method (e.g. download page, yum, from source, etc.):**
From 8.0.0-SNAPSHOT on staging cloud environment https://staging.found.no/

**Description**
elastic-agent uninstall command is unable to uninstall the elastic-agent on endpoint

**Preconditions**
1. 8.0.0-SNAPSHOT Kibana cloud environment should be available.

**Steps to Reproduce**
1. Open the 8.0.0-SNAPSHOT Kibana cloud environment in browser.
2. Download the 8.0.0 agent from artifact link(https://console.cloud.google.com/storage/browser/beats-ci-artifacts/pull-requests/pr-21206/elastic-agent?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)
3. RDP to the endpoint and place the agent.
4. Unarchive the agent
5. Open powershell as admin and run the command for interactive mode:
./elastic-agent install
6. Observe that installation is successful on endpoint but agent is unable to enroll into fleet.
7. Now run the elastic-agent uninstall command and observe that agent is still running.
Message displayed: can only be uninstall by executing the installed Elastic Agent at: C:\Program Files\Elastic\Agent\elastic-agent.exe

**Test data**
N/A

**Impacted Test case id**
N/A

**Actual Result**
[Ingest Management]: elastic-agent uninstall command is unable to uninstall the elastic-agent

**Expected Result**
[Ingest Management]: elastic-agent uninstall command should be able to uninstall the elastic-agent

**What's working**
 - N/A

**What's not working**
 - Issue is also occurring for mac and linux

**Screenshot**
![Untitled](https://user-images.githubusercontent.com/59917944/94014023-96973580-fdc8-11ea-8325-611490e95297.jpg)

**Logs**
N/A

**Comment by rahulgupta-qasource** [comment]
@muskangulati-qasource Please review the bug.

**Comment by muskangulati-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by blakerouse** [comment]
This is correct behavior. As it states you must perform:

`C:\Program Files\Elastic\Agent\elastic-agent.exe uninstall`

A non-installed Elastic Agent cannot uninstall an installed agent.

**Comment by rahulgupta-qasource** [comment]
**Bug Conversion:**

Testcase already exists for this ticket.
https://elastic.testrail.io/index.php?/cases/view/33951
