### ISSUE TITLE
Azure module event.category incorrectly mapped

### ISSUE THREAD

**Issue by bm11100** [elastic/beats#21259]
## Description
Our team is currently working on Azure rules and it appears that `event.category` in the Azure module has incorrect field mappings. We are seeing `event.category:Administrative`  for Activity logs and `event.category:AuditLogs` for Audit logs. According to the [documentation](https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-category.html), neither appear to be valid values. Example issue with screenshot - https://github.com/elastic/detection-rules/issues/197.

![image](https://user-images.githubusercontent.com/56412096/94036017-d68ef600-fd91-11ea-8186-1d4ffd337ea4.png)

For confirmed bugs, please report:
- Version: 7.8.1
- Operating System: all
- Discuss Forum URL: n/a
- Steps to Reproduce: Configure the Azure Filebeat module to send data to ES. Obsever the `event.category` field. 

## Screenshots

![image](https://user-images.githubusercontent.com/56412096/94036067-e3abe500-fd91-11ea-9166-9cfd9d4e0705.png)

![image](https://user-images.githubusercontent.com/56412096/94036114-f4f4f180-fd91-11ea-97e6-47041f6058a0.png)

**Comment by bm11100** [comment]
spoke to @leehinman. looks like this is a non issue in version 7.9. I have not confirmed, but will close based on his feedback pointing to this PR - https://github.com/elastic/beats/pull/19376

**Comment by pwen090** [comment]
This is still an issue in 7.9.1 see #21190 rules do not fire properly and also your point on documentation still stands.

**Comment by bm11100** [comment]
@pwen090 please see https://github.com/elastic/detection-rules/issues/333 to address this issue.
