### ISSUE TITLE
External Heartbeat checks via custom scripts

### ISSUE THREAD

**Issue by wasserman** [elastic/beats#21276]
**Describe the enhancement:**
It would be helpful if users could write scripts that can emit health data for easy integration with Uptime.  This would allow users to implement advanced business logic and complex scenarios. 

Some possible ways to do this would be:
1. Create a library (Python and/or Go) to emit heartbeat compatible events that would show up in Uptime.
2. Add the capability for Heartbeat to digest a json file which could be sent to Elastic as a health check based on the inputs.  Possibly introduce Heartbeat modules to support this and future scenarios.
3.  Add the capability for Filebeat to take a file (flat and/or json) with special fields that would be used to output in the Heartbeat-compatible output.

**Describe a specific use case for the enhancement or feature:**
My use case involves the following:
- We have Python scripts to generate JSON for filebeat ingestion, so it would be trivial to adapt that for heartbeat compatibility if there was a supported mechanism to push this to Elastic.
- The check requires multiple HTTP requests for authentication that obtains token and cookies for a subsequent request that is the actual check.  
- The check that requires multiple inputs and logic that determines the resulting health.

**Comment by andresrc** [comment]
Requires https://github.com/elastic/beats/issues/18323

**Comment by wasserman** [comment]
I just checked back on this and some of it seems to now be captured by the Synthetics and monitor/browser options.  This feature looks really nice, although it may take some time to figure out how to use it effectively.
https://www.elastic.co/guide/en/beats/heartbeat/current/monitor-browser-options.html

The other piece I wonder if some of the httpjson functionality from filebeat can be leveraged for API support that could require various authentication methods, such as oauth2?
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-httpjson.html#_auth_oauth2_enabled

**Comment by andrewvc** [comment]
That's a great point @wasserman , re: combining those `httpjson` options into heartbeat. That said, it may be better at some point to just have first class support for API journeys in JS, which are much more powerful.

Which would you prefer?

**Comment by wasserman** [comment]
@andrewvc I can't speak to the journeys since I've never been on one. ;)  I feel like the quickest simplest path forward would be `httpjson` given that a config from filebeat could be easily ported over to heartbeat.  Maybe even leveraging the filebeat code would be easy enough?

There may be value in including it as API journeys since it could be authored by users who already understand this workflow.  I'm guessing this requires a headless browser or equivalent so it could carry a bit more overhead than necessary, but there are always trade-offs.  Keep in mind that APIs often may have specific custom headers including non-UI user agent strings.  Is this supported by Playwright?

Another thought could be having some monitoring params permitted in beat inputs (filebeat, etc.) that could add this visibility without having to replicate configuration into heartbeat.  This then could be used to leverage Uptime or other monitoring by source through the input responses instead of more roundabout ways.
