### ISSUE TITLE
The statsd metricbeat module shouldn't treat each metric as a separate field

### ISSUE THREAD

**Issue by anna-yn** [elastic/beats#21271]
**Describe the enhancement:**
Currently the statsd module reports each metric as a separate field, for example, here are some of the statsd fields from our metricbeat index:

```
            "metric_name": {
              "properties": {
                "15m_rate": {
                  "type": "float"
                },
                "1m_rate": {
                  "type": "float"
                },
                "5m_rate": {
                  "type": "float"
                },
                "count": {
                  "type": "long"
                },
                "max": {
                  "type": "float"
                },
                "mean": {
                  "type": "float"
                },
                "mean_rate": {
                  "type": "float"
                },
                "median": {
                  "type": "float"
                },
                "min": {
                  "type": "float"
                },
                "p75": {
                  "type": "float"
                },
                "p95": {
                  "type": "float"
                },
                "p99": {
                  "type": "float"
                },
                "p99_9": {
                  "type": "float"
                },
                "stddev": {
                  "type": "float"
                }
              }
            },
```

Each field like `15m_rate`, `1m_rate`, `5m_rate` is a separate field too. 

In our previous metrics collector, the statsd module put all the different metric names in a field called `name`. I think this way things are much cleaner (see other reasons below)

**Describe a specific use case for the enhancement or feature:**
The current implementation potentially causes field explosion, and it can cause metrics to get dropped because it pushes the total number of fields above the 10k limit. We could raise the limit, but we don't want to do it just for statsd. Without statsd, our # of fields in the metricbeat index is well below the limit, but statsd can easily bring in a few thousand fields. We had talked to elastic support and it sounds like this could be a top contributor to our elasticsearch's instability, so now we just can't use the statsd module at all.

**Comment by sorantis** [comment]
@Nevvea7 thanks for filing the issue. We've reviewed it and added to our backlog.
