### ISSUE TITLE
Beat names longer than 16 characters break the process stats reporting

### ISSUE THREAD

**Issue by eirc** [elastic/beats#21297]
For confirmed bugs, please report:
- Version: 7.3.1
- Operating System: Linux
- Steps to Reproduce: Create a new beat with a name longer than 16 characters, run it. You'll get errors like:

```
DEBUG   [processes]     process/process.go:480  Process name does not matches the provided regex; pid=XXX; name=<ONLY THE FIRST 16 LETTERS OF THE BEAT NAME>: <nil>
ERROR   instance/metrics.go:92  Error while getting memory usage: error retrieving process stats: cannot find matching process for pid=XXX
```

The problem is in [libbeat/metric/system/process/process.go#L487](https://github.com/elastic/beats/blob/master/libbeat/metric/system/process/process.go#L487) where a check is made to ensure it has the right process. It checks the name of the process against the name given by elastic/go-sysinfo. The later one is taken from `/proc/<pid>/comm` which only provides the first 16 bytes of a process name. (I'm not sure where the other process name is taken from, I think from gosigar? but I got a bit lost in there)

**Comment by fearful-symmetry** [comment]
Fix here: https://github.com/elastic/beats/pull/22550

**Comment by fearful-symmetry** [comment]
Fix has been merged, closing.
