### ISSUE TITLE
Flaky Test [Build&Test / libbeat-build / TestClientPublishEventKerberosAware – elasticsearch]

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#21295]
## Flaky Test

* **Test Name:** TestClientPublishEventKerberosAware
* **Link:** https://github.com/elastic/beats/blob/a9db1b1f9421eb7372ae74faa8f6cd455148de94/libbeat/outputs/elasticsearch/client_integration_test.go#L57
* **Branch:** Failing in many PRs, for example [here](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-19645/3/pipeline#step-1509-log-107).
* **Notes:**
  * It is failing quite frequently in travis and jenkins. Not able to reproduce it locally, but same trace can be reproduced removing the kerberos settings, so it looks like if the kerberos settings are lost at some point, or somehow a client without kerberos credentials is used.
  * May be related to #21197.

### Stack Trace

```
client_integration_test.go:97: 401 Unauthorized: {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/_bulk]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Negotiate"]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/_bulk]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Negotiate"]}},"status":401}
```

**Comment by v1v** [comment]
Probably https://github.com/elastic/beats/issues/21838 is also affected since the docker image doesn't start.

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
