### ISSUE TITLE
No IP defragmentation 

### ISSUE THREAD

**Issue by urso** [elastic/beats#213]
When replaying IP fragmented pcap, the fragmented packets are not forwarded to the TCP/UDP layer.

**Comment by urso** [comment]
When sending an ip fragmented packet the decoder will not process it. See debug output:

    decoder.go:129: DBG  Decoding error: No decoder for layer type Fragment

**Comment by ruflin** [comment]
@urso Unassigned you here to make it available for others to pick up.

**Comment by seawolf888** [comment]
any plan for this?

**Comment by khangtc61785** [comment]
Have any change for this?

**Comment by jlind23** [comment]
Backlog grooming: Stalled issue, closing for now. Feel free to reopen it if needed
