### ISSUE TITLE
Flaky test: test_docker

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/beats#21305]
## Flaky Test

* **Test Name:** test_docker
* **Link:** https://github.com/elastic/beats/blob/becca8de135f41e94156e8040cf9a0d5c4800553/filebeat/tests/system/test_autodiscover.py#L17
* **Branch:** Master
* **Artifact Link:** If available, attach the generated zip artifact associated with the stack trace for this failure.
* **Notes:** Additional details about the test. e.g. theory as to failure cause

### Stack Trace

```
paste stack trace here
```

**Comment by jsoriano** [comment]
This should have been fixed by https://github.com/elastic/beats/pull/21242, please reopen if this is still an issue.
