### ISSUE TITLE
Flaky test: test_reload_same_config

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/beats#21307]
## Flaky Test

* **Test Name:** test_reload_same_config
* **Link:** https://github.com/elastic/beats/blob/becca8de135f41e94156e8040cf9a0d5c4800553/filebeat/tests/system/test_reload_inputs.py#L254
* **Branch:** Master
* **Artifact Link:** If available, attach the generated zip artifact associated with the stack trace for this failure.
* **Notes:** Additional details about the test. e.g. theory as to failure cause

### Stack Trace

```
paste stack trace here
```

**Comment by kvch** [comment]
I increased the number of reruns to 2. If the test keeps failing it has to be skipped on Windows. Also, it needs investigation.

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.

**Comment by VihasMakwana** [comment]
Fixed via https://github.com/elastic/beats/pull/40389
