### ISSUE TITLE
[metricbeat][arm] Test failures TestAll, TestEventMapping, TestData, TestEventMappingV1_8

### ISSUE THREAD

**Issue by v1v** [elastic/beats#21301]
## Flaky Test

* **Test Name:** TestAll, TestEventMapping, TestData, TestEventMappingV1_8
* **Link:** Link to file/line number in github.
* **Branch:** https://github.com/elastic/beats/pull/21284
* **Artifact Link:** Build logs in the CI -> [here](https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats-mbp-2.0/branches/PR-21284/runs/8/nodes/3793/steps/7307/log/?start=0) or in [gist](https://gist.github.com/v1v/1ba27ea0eeb0c6a02850bb1bb63a0b37)

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
