### ISSUE TITLE
[xpack/metricbeat][arm] TestEventMapping,TestPromHistogramToES,TestData

### ISSUE THREAD

**Issue by v1v** [elastic/beats#21304]
## Flaky Test

* **Test Name:** TestEventMapping,TestPromHistogramToES, TestData
* **Link:** Link to file/line number in github.
* **Branch:** https://github.com/elastic/beats/pull/21284
* **Artifact Link:** Build logs in the CI -> [here](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats-mbp-2.0/branches/PR-21284/runs/8/nodes/3819/steps/8328/log/) or in [gist](https://gist.github.com/v1v/c514458eb11eaebf63df4f747a204bed)

**Comment by andrewkroh** [comment]
It kind of looks like the events arrived in a different order than what was expected by the tests.
