### ISSUE TITLE
[Elastic-Agent] Elastic Agent data streams are not present

### ISSUE THREAD

**Issue by mdelapenya** [elastic/beats#21319]
>This report comes from executing the E2E tests in https://github.com/elastic/e2e-testing

We have a test scenario querying the elastic agent's log index in ES (`logs-elastic.agent-default`) which is randomly failing because the index is not found.

#### The test scenario (BDD)
```gherkin
@enroll
Scenario Outline: Deploying the <os> agent
  When a "<os>" agent is deployed to Fleet
  Then the agent is listed in Fleet as "online"
    And system package dashboards are listed in Fleet
Examples:
| os     |
| centos |
| debian |
```
This scenario, which repeats with exactly same code for each row in the scenario Examples table, starts a Centos/Debian container using `systemd` as process manager, then it installs the proper package (RPM or DEB), and enable the elastic-agent service.

>It's important to mention that before any scenario is run, runtime dependencies and state is created: elastisearch, kibana and package registry are started, and Fleet setup is executed (using APIs).

A fleet policy is created for each scenario, so that we can isolate test execution, and then it creates a fleet token in that policy. This token is used to enroll the agent in Fleet, using this command:

```shell
$ elastic-agent enroll http://kibana:5601 $TOKEN -f --insecure
```
And finally we start the service in the elastic-agent.
> We detected a race condition if the agent was enrolled **after** starting the service. That's why we use this order: enable > enroll > start.

The next step is to check if the agent is listed on Fleet as online, and for that we use Fleet APIs. We get the current agent ID (for the current hostname) from the list of agents in Fleet (`/api/ingest_manager/fleet/agents`), and with that agentID we query again the APIs (`/api/ingest_manager/fleet/agents/{AGENT_ID}`) to get the status. If it is "online", we continue.

Finally, we check that system packages are listed in Fleet. We check the APIs (`/api/ingest_manager/data_streams`)

#### Actual result
We cannot get datastreams in 3 minutes (maxTimeout)

>We have seen these tests to pass a few weeks ago

## How to test this

0. Install requirements: docker + docker-compose
1. Clone the e2e repo: `git clone https://github.com/elastic/e2e-testing`
2. Run the fleet tests

```shell
$ cd e2e-testing
$ SUITE=ingest-manager DEVELOPER_MODE=true FEATURE="fleet_mode" LOG_LEVEL=TRACE make -C e2e functional-test
```

cc/ @EricDavisX @ph

**Comment by ph** [comment]
@michalpristas is this is still an issue?

**Comment by EricDavisX** [comment]
The fixes are all in for known problems, and we're expecting nightly runs to all pass!  When we see it (formally) we can close this out.

**Comment by mdelapenya** [comment]
Closing because the builds are passing again!
