### ISSUE TITLE
 stack monitoring: libbeat bytes sent rate is always 0

### ISSUE THREAD

**Issue by graphaelli** [elastic/beats#21322]
Discovered while investigating elastic/apm-server#4235, stack monitoring shows the same for other libbeat based applications:

<img width="949" alt="image" src="https://user-images.githubusercontent.com/83483/94191168-209fd680-fe7b-11ea-9b77-7baf34b387e7.png">

https://github.com/elastic/apm-server/issues/4235#issuecomment-698061904 looks like a good starting place to debug this

**Comment by ycombinator** [comment]
Looks like a duplicate of #20752. If so, @kvch recently resolved this via https://github.com/elastic/beats/pull/21197.

**Comment by graphaelli** [comment]
Thanks!  We'll get this over to APM Server shortly
