### ISSUE TITLE
[DOC] Document usage of troubleshooting parameters of beats

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/beats#21329]
**Describe the enhancement:**

We have the following parameters:
```
--cpuprofile FILE
--httpprof [HOST]:PORT
--memprofile FILE
```

**Describe a specific use case for the enhancement or feature:**

It would be nice to add a section on how to use them so users can troubleshoot potential issues or provide more insights about issues.

In general, at least for `httpprof`, we have to download the output
```
$ curl -O http://localhost:8000/debug/pprof/heap
$ curl -O http://localhost:8000/debug/pprof/profile
```

The file can be attached or sent out, or can be rendered using `go tool pprof -http :9999 /path/to/filebeat/binary heap`

For `cpuprofile` and `memprofile` once the files are generated, we should be able to use `go tool pprof cpu.prof` or `go tool pprof memory.prof`

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.

**Comment by lucabelluccini** [comment]
🤣

**Comment by nerophon** [comment]
I thought only Cloud did this. It's spreading!

**Comment by lucabelluccini** [comment]
I fully agree @adoerrES 
It's a pity we have embedded tooling for profiling CPU & memory, but users who would be willing to self-troubleshoot or  collect information do not have a public reference about this.
Golang developers might find their way without any documentation as those are standard features of Go, but it would be great to share some examples / references.

**Comment by jlind23** [comment]
@pierrehilbert @ph do we have a similar issue for Elastic Agent? I think it is better to spend time on enhancing Elastic Agent troubleshooting guide instead than investing on Beats one.
