### ISSUE TITLE
Add cloud.availability_zone into azure module

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#21363]
As a part of inventory schema work, we want to make sure aws, azure and googlecloud module all have `cloud.availability_zone` field. This issue is to track the work for adding `cloud.availability_zone` into azure module.

**Comment by kaiyan-sheng** [comment]
@narph mentioned to me about we have some issue collecting az for Azure because the zone is not mapped in the sdk although it is returned by the API. We can leave `cloud.availability_zone` as optional for now.

**Comment by narph** [comment]
The GetById resource API does return the zone but it looks like it is not mapped inside the Azure SDK.
Someone has already raised this issue https://github.com/Azure/azure-rest-api-specs/issues/3358 for the vm scalesets , will raise an issue as well.

**Comment by ravikesarwani** [comment]
Closing as stale. No users ask.
