### ISSUE TITLE
Common Fields for Cloud Inventory Schema

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#21365]
This issue is to track the work for adding common fields among different cloud metrics. These proposed common fields will become required fields to collect when adding support for new cloud platforms.

Proposed Common Fields:

- cloud.account.id
- cloud.availability_zone
- cloud.instance.id
- cloud.instance.name
- cloud.machine.type
- cloud.provider
- cloud.region

TODO:

- [ ] 1. Add `cloud.availability_zone` into azure: https://github.com/elastic/beats/issues/21363
- [x] 2. Add `cloud.account.id` into azure: https://github.com/elastic/beats/issues/21381

**Comment by kaiyan-sheng** [comment]
For `cloud.account.id`, the definition in [ECS](https://www.elastic.co/guide/en/ecs/current/ecs-cloud.html) is: 
```
The cloud account or organization id used to identify different entities in a multi-tenant environment.

Examples: AWS account id, Google Cloud ORG Id, or other unique identifier.
```

AWS and GCP are both clear what to use for `cloud.account.id`. For Azure, we are looking at using subscription ID for `cloud.account.id`.  I think we should update the ECS document on `cloud.account.id` to include what is used for Azure.

**Comment by kaiyan-sheng** [comment]
Question from @narph: 
If we map it to the subscription id, how do we envision this to look in the UI? Will users be able to filter using the account.id? If so, can we have a more clear naming in the UI that would make sure azure users will understand? Just having `Account ID` in the list could make them think of the billing account or other types of accounts when it comes to Azure?

@sorantis @exekias WDYT?

**Comment by exekias** [comment]
@narph, correct me if I'm wrong here, this is how I understand it:

All resources (ie VMs) are tied to the subscription id. Users know it well, as they use it to configure Azure API clients (like our own agent), you cannot move a resource to another subscription.

Billing accounts group subscriptions for billing purposes. You can move subscriptions from some billing accounts to another.

Having all this into account (pun intended 😛), it would look like subscription id is a better fit for `account.id`. For these reasons:

- Resources are always tied to the same subscription id
- This id is closer to users, so they know it better
-  If we store billing account as `account.id`, I cannot filter to a single subscription id, which is something I may want? If we store subscription id, you can still jump from a billing account to all the subscription ids on it, using that as a filter if needed.

**Comment by narph** [comment]
@exekias , I thought we previously agreed that we would align the sub ID to the `cloud.account.id` field (and still keep the value inside `azure.subscriptionId`) , my question was more related to the UI, how will it look and if we can accommodate a naming (in the UI) that would help azure users understand we are talking about the subscription ID., for example `Account ID/Subscription ID`.

**Comment by exekias** [comment]
Understood, any opinions @sorantis? Something that comes to my mind is that UI can be smart enough to detect the `cloud.provider` and show the correct name based on it

**Comment by sorantis** [comment]
Today the UI doesn't provide account id as a default field to group by. Here the default option for Hosts:
<img width="757" alt="Screen Shot 2020-09-30 at 14 04 27" src="https://user-images.githubusercontent.com/1685068/94682912-f8eeb980-0325-11eb-84b9-a8897be0a19f.png">

Users are free to group by any field, e.g. `cloud.account.id`, but right now it's not explicitly provided. If we decide to have it by default then I'd use Account ID as the preferred naming even for Azure.

cc @simianhacker

**Comment by kaiyan-sheng** [comment]
We discussed this question during meeting and the conclusion is: we will use subscription ID as `cloud.account.id` and once we start changing metrics UI, we can start discuss how to clarify the definition of `cloud.account.id` between different cloud providers.

**Comment by kaiyan-sheng** [comment]
I'm closing this issue because the only one task left is to add `cloud.availability_zone` into azure, which is tracked by #21363. This issue is depends on a fix in Azure SDK so we don't know when will be resolved.
