### ISSUE TITLE
Filebeat error is displayed in activity logs on installing elastic agent with new install command 

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#21378]
**Kibana version:**
Kibana: 8.0.0-SNAPSHOT

**Elasticsearch version:**
Elasticsearch: 8.0.0-SNAPSHOT

**Host OS and Browser version:**
Windows 10 , All

**Original install method (e.g. download page, yum, from source, etc.):**
From 8.0.0-SNAPSHOT Kibana cloud on staging cloud environment https://staging.found.no/

**Description**
Filebeat error is displayed in activity logs on installing elastic agent with new install command 

**Preconditions**
1. 8.0.0-SNAPSHOT Kibana cloud environment should be available [say Cloud Provider: AWS, Region: US East (N. Virginia)]

**Steps to Reproduce**
1. Open the 8.0.0-SNAPSHOT Kibana cloud environment in browser.
2. Download the 8.0.0 latest agent from artifact link(https://console.cloud.google.com/storage/browser/beats-ci-artifacts/pull-requests/pr-21206/elastic-agent?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)
3. RDP to the endpoint and place the agent.
4. Unarchive the agent
5. Open powershell as admin and run the command for interactive mode:
./elastic-agent install
6. Proceed further and provide the kibana url and Fleet enrollment token.
7. Observe that agent is enrolled under fleet tab[with error in activity logs and powershell] 

**Test data**
N/A

**Impacted Test case id**
N/A

**Actual Result**
Filebeat error is displayed in activity logs on installing elastic agent with new install command

**Expected Result**
No error should be displayed in activity logs after successfully installing elastic agent with new install command 

**What's working**
 - Agent is displayed under fleet tab

**What's not working**
 - N/A

**Screenshot**
![#21378](https://user-images.githubusercontent.com/59917944/94558703-d6a16100-027d-11eb-8a93-4e62c873b6c5.jpg)

**Logs**
1. Activity logs:
[activity_logs.zip](https://github.com/elastic/beats/files/5299022/activity_logs.zip)

2. elastic-agent logs:
[elastic-agent_logs.zip](https://github.com/elastic/beats/files/5299025/elastic-agent_logs.zip)

**Comment by rahulgupta-qasource** [comment]
@muskangulati-qasource Please review the bug

**Comment by blakerouse** [comment]
This is unrelated to the #21206. It is related to the recent #20186 that landed in master.

**Comment by ph** [comment]
@michalpristas Is there something missing in the 8.x snapshot?

**Comment by michalpristas** [comment]
the thing is that during build there is a certain amount of time when intermediate snapshot is published.
this intermediate snapshot of agent does not include endpoint or any *.asc files. 
these files get bundled after postbuild job is done and endpoint artifacts are updated. this also includes CI built artifacts of beats not in-place built one so hash or PGP may be different.

infra has an issue which once fixed should result in publishing agent snapshots only once post-build job is finished. until the we need to manually check the artifacts for asc files or build itself for completion.

**Comment by ph** [comment]
@michalpristas could you link from the private issue to this issue?

**Comment by EricDavisX** [comment]
https://github.com/elastic/beats/issues/21320 - we can track this related issue, too, for Docker containers

**Comment by EricDavisX** [comment]
this is fixed in latest build - i do not see it in my assessment with a darwin test.  closing as fixed

**Comment by rahulgupta-qasource** [comment]
**Bug Conversion:**

Updated 01 Testcase for this ticket.
https://elastic.testrail.io/index.php?/cases/view/33948
