### ISSUE TITLE
Using Metricbeat's system module inside Docker

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#2137]
# Running Metricbeat in Docker

Goal: We want to be able to monitor the host machine from within a container.

#### The Command:

```
sudo docker run \
  --rm \
  --volume=/proc:/hostfs/proc:ro \
  --volume=/sys/fs/cgroup:/hostfs/sys/fs/cgroup \
  --net=host \
  --name=metricbeat \
  akroh/metricbeat:5.0.0-alpha6-SNAPSHOT \
  -system.hostfs=/hostfs \
  -E output.elasticsearch.enabled=false \
  -E output.console.pretty=false
```

This would mount the host’s filesystem under /rootfs inside the container. This gives Metricbeat’s system module access to data from the host. Normally Metricbeat reads the following data, but it will need to read all of this data relative to /rootfs to capture data from the host.

- cpu
  - /proc/stat
- memory
  - /proc/meminfo
- load
  - /proc/loadavg
- core
  - /proc/stat
- diskio (gopsutil)
  - /proc/diskstats
- filesystem
  - /etc/mtab
  - statfs (syscall)
- network (gopsutil)
  - /proc/net/dev
  - This does not appear to work, /rootfs/proc/net/dev and /proc/net/dev are exactly the same and contain container metrics not host metrics. You must start the container with --net=host to see the host’s network stats.
- process
  - /proc
  - /proc/[pid]/stat
  - /proc/[pid]/status
  - Username lookup from uid will likely fail. (?)
- cgroup
  - /proc/cgroups
  - /proc/self/mountinfo
  - /proc/[pid]/cgroup
  - /sys/fs/cgroup or /cgroup (for some systems like RHEL 6)
    - This filepath is read from /proc/self/mountinfo so it must be interpreted as relative to /rootfs when running inside a container.

#### Required Changes

- [x] For gopsutil, set the path to `/etc`, `/proc`, and `/sys` relative to the `-system.hostfs` value by setting `HOST_ETC`, `HOST_PROC`, and `HOST_SYS` environment variables.
- [x] For gosigar, set the global `Procd` variable relative to the `-system.hostfs` value when `GOOS=linux`.
- [x] For gosigar, make the path to `/etc/mtab` configurable and set it relative to the `-system.hostfs` value.
- [x] Need ability to filter filesystems by mountpoint. (Just use a `drop_event` filter, see system.filesystem docs.)
- [x] Update docs to show how to run Metricbeat inside a container.

**Comment by ruflin** [comment]
@andrewkroh +1 on this suggestion. This would probably be a config option of the system module?

**Comment by andrewkroh** [comment]
Due to some limitations in gosigar and gopsutil this cannot be a config option. The values are global so having a per module config value won't work.

**Comment by ruflin** [comment]
Would it work as a `metricbeat.*` option? Means it applies to all system modules?
