### ISSUE TITLE
Beats common "add cloud metadata" function doesn't use HTTPS

### ISSUE THREAD

**Issue by maggieghamry** [elastic/beats#21392]
To use the  OpenStack API with Auditbeat, HTTPS is required, but the Beats common "add cloud metadata" function doesn't (just uses plain HTTP). 

Currently, there is no workaround to enable the connection to OpenStack API to use HTTPS
- Version: 7.9

**Comment by jsoriano** [comment]
http is hardcoded here: https://github.com/elastic/beats/blob/d8d35a16b0beae02cb8048df2a66c3a743d0633f/libbeat/processors/add_cloud_metadata/http_fetcher.go#L141

**Comment by andrewkroh** [comment]
Does OpenStack always require HTTPS? Should the processor attempt both http and https for the broadest compatibility?

**Comment by jsoriano** [comment]
@maggieghamry do you know how can OpenStack be configured to use HTTPS? In the latest documentation I only see references to HTTP: https://docs.openstack.org/nova/latest/user/metadata.html

**Comment by jsoriano** [comment]
Ok, there seems to be an [`enabled_ssl_apis` option](https://docs.openstack.org/nova/train/configuration/config.html#DEFAULT.enabled_ssl_apis) that can be used to enable SSL.
