### ISSUE TITLE
Beats:Outputs:Codec introduce json-gzip codec that can compress json

### ISSUE THREAD

**Issue by williamd67** [elastic/beats#21412]
**Describe the enhancement:**
Introduce a new output-codec that not only jsonify the content but also compresses (gzip) it. The current 'json'-codec can be reused and the output of that content would be compressed by a gzip-component and the compressed content would be returned from the codec.

As far as I could determine it is not possible to chain codecs so my proposal is to introduce a new 'json-gzip' codec which is derived from the existing 'json'-codec with the extra functionality to compress the content.

**Describe a specific use case for the enhancement or feature:**
Azure Event Hub is not able to support compressed Kafka-messages but it is able to handle compressed content. This means that the compression that can be set at the Kafka level cannot be used. An alternative would be to compress the content that is sent with the Kafka-protocol to Azure Event Hub. Unfortunately such a compression does currently not exists hence my request to create a codec that not only jsonify the content but also compresses that content.

When a lot of data is sent to Azure Event Hub the compression saves bandwidth and message handling time.

**Comment by andresrc** [comment]
We usually add the compression at the output level. This sounds like a path for another implementation of the protocol limitation. 

Do EventHub support some other compression protocol. IIRC we also support SPDY in this output.

**Comment by williamd67** [comment]
Azure Event Hub does not support, as far as I know, any other compression on the output level.

> This sounds like a path for another implementation of the protocol limitation.

I do not completely understand _another_. As far as I could determine this is not supported yet.

Creating a propriety filebeat version with the content compression (json-gzip-codec) is quiet straight-forward especially as codecs are plugins. I filed the request as my assumption is that more people have this request and can benefit from an out-of-the-box implementation.

**Comment by andresrc** [comment]
Hi! I edited my comment for some typos. What I meant with another is that we have already had some issues because of differences in the Kafka interface provided by EventHub.

Thanks

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
