### ISSUE TITLE
[Elastic Agent] How to monitor inputs

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#21413]
In Fleet a user deploys and Integration policy as part of an Agent policy. From an Agent perspective, an integration policy is just an array of inputs. The user needs to know if an Integration policy is working or not. For an Agent to report if an integration works or not, the Agent needs to know  about the status of each input. As the Agent is mostly a supervisor and the inputs are run by the processes, this data needs to be reported by the processes.

This issue is to discuss the following points:

* What are the metrics that each input should report
* How is each input going to report this metrics

## Proposal on reporting path

To take a first stab on how this could work, here a proposal on the part on how the metrics are reported. Today metrics and logs are collected from a separate Metricbeat / Filebeat instance. I would not change this for now but introduce an additional path for the input monitoring. Each process has a standardised way on how to report inputs metrics to the Elastic Agent through GRPC. Then the Agent decides on how all these metrics are shipped / reported to Elasticsearch / Fleet.

![image](https://user-images.githubusercontent.com/244900/94679190-f9845180-031f-11eb-935d-8761b3d4fad4.png)

**Comment by jlind23** [comment]
@belimawr will start working on it. 
@kvch how does it match with the input manager proposal you wrote?
