### ISSUE TITLE
Data streams are not displayed on installing standalone elastic agent with new install command

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#21449]
**Kibana version:**
Kibana: 8.0.0-SNAPSHOT

**Elasticsearch version:**
Elasticsearch: 8.0.0-SNAPSHOT

**Host OS and Browser version:**
Windows 10x64 , All

**Original install method (e.g. download page, yum, from source, etc.):**
From 8.0.0-SNAPSHOT Kibana

**Description**
Data streams are not displayed on installing standalone elastic agent with new install command

**Preconditions**
1. 8.0.0-SNAPSHOT Kibana  environment should be available.
2. Download the 8.0.0 latest agent from GCP link(https://console.cloud.google.com/storage/browser/beats-ci-artifacts/snapshots/elastic-agent?pageState=%28%22StorageObjectListTable%22:%28%22f%22:%22%255B%255D%22%29%29&prefix=&forceOnObjectsSortingFiltering=false)

**Steps to Reproduce**
1. Open the Kibana cloud environment in browser, then click Ingest Manager->Fleet tab.

2. Click on Add agent->Run Standalone

3. Click on "Copy to clipboard" button to copy the 'Default Config' configuration data.

4. Paste the configuration and put it into a file named elastic-agent.yml on the prerequisite endpoint where the Elastic Agent is installed.

5. Modify the ES_USERNAME and ES_PASSWORD in the outputs section of the configuration file based on your cloud environment.

6. Start the agent with following command:

   ./elastic-agent install
   
and proceed with installation.
   
7. Observe that Installation is successful and use the dialog to cite 'not' to enroll in fleet when asked.

**Test data**
N/A

**Impacted Test case id**
N/A

**Actual Result**
Data streams are not displayed on installing standalone elastic agent with new install command

**Expected Result**
Data streams should be displayed on installing standalone elastic agent with new install command 

**What's working**
 - N/A

**What's not working**
 - Issue is also occurring on enrolling agent into fleet

**Screenshot**
![standalone_agent_bug](https://user-images.githubusercontent.com/59917944/94805281-c28a6a80-0409-11eb-88b9-37281f53da07.jpg)

**Logs**
N/A

**Comment by rahulgupta-qasource** [comment]
@muskangulati-qasource Please review the bug.

**Comment by muskangulati-qasource** [comment]
Reviewed and assigned to @EricDavisX

**Comment by EricDavisX** [comment]
same problem as the 'activity detail' issue - it is resolved in the latest build.  closing as fixed!
