### ISSUE TITLE
[Fleet /  Agent] when persistent agent 'install' is rebooted on darwin system, not all Beats are restarted

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#21451]
[Fleet /  Agent] when persistent agent 'install' is rebooted on darwin system, not all Beats are restarted

related to https://github.com/elastic/beats/issues/21424 which is for the Elastic Endpoint port.  This is just for the other beats, tho the cause may be related (tbd), logging separately for safety.

tested with latest 8.0 Agent + Kibana
agent: 
https://snapshots.elastic.co/8.0.0-f437c552/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz

kibana, commit: 5aa3fb5e0634c84ae3521de6cad663585d7b01ae, from date: Wed Sep 30 19:04:22 2020 -0600

Tested on darwin 10.15.6 (19G2021)

download the agent and unzip.
install kibana via cloud
use the (not yet shown in the UI) steps to install, as:

then add Endpoint to the policy
then wait 5-10 mins for it to all come on line
do a 'ps ax | grep elastic' to see all of the Beats running, from the default config options (4)
then reboot the machine.
see that only 1 beat comes back with Agent (Endpoint concern is logged separately)

screenshots:
before reboot, after install and policy change and 5 min wait:
<img width="1502" alt="Screen Shot 2020-10-01 at 1 40 15 PM" src="https://user-images.githubusercontent.com/12970373/94844109-bdb6be00-03eb-11eb-85b4-7fae7ea869f0.png">

after reboot:
<img width="1512" alt="Screen Shot 2020-10-01 at 1 39 59 PM" src="https://user-images.githubusercontent.com/12970373/94844115-bee7eb00-03eb-11eb-9631-d135e86a527f.png">

note we have a test that covers this, but not sufficiently - we need help to implement the test, see:
https://github.com/elastic/e2e-testing/issues/218

**Comment by ph** [comment]
@EricDavisX This is with a latest snapshot?

@blakerouse Can you take a look?

**Comment by EricDavisX** [comment]
@rahulgupta-qasource please hold off on doing more install tests for reboot until after this is fixed.  you can still test basic initial stand-alone mode install, and we can test 'upgrade' when its available (soon).

**Comment by rahulgupta-qasource** [comment]
Hi Eric

Thank you for the update.

We have hold on the install tests for reboot validated the basic initial stand-alone mode install under [#21019](https://github.com/elastic/beats/issues/21019) ticket.

We will test the 'upgrade' tests once they are available.

**Comment by blakerouse** [comment]
@EricDavisX Is this still reproducable? I think this was because of the action_store.yaml issue that is now fixed.

**Comment by EricDavisX** [comment]
indeed this looks fixed to me - tested on 7.10 BC2 on a catalina darwin host.  i feel ok to close this out.
