### ISSUE TITLE
[Ingest Manager] Update procedure: rollback on failure

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#21518]
With update procedure in place we need a mechanism for the case when update procedure wont succeed. 

For this we need additional subprocess which will be triggered and will watch for several indicators during a grace period:
- health of agent
- health of agents subprocesses (beats, endpoint)
- unusual restarts/crashed of agent or subprocesses 

what is healthy or not is defined on the level of agent/subprocess and provided to watcher using some form of API. 
In case one component turns out failing during the grace period rollback procedure is initiated which means:
- symlinks are switched 
- paths are updated
- configuration is recovered 
- active.commit.id is updated
- update marker removed
- installation files remove
- failing binaries removed

Food for thought: maybe we should keep log files of failing version for possible investigation

**Comment by ph** [comment]
Any progress on this front?

**Comment by michalpristas** [comment]
Update: i got rollback working on macos, killing agent was detected and agent was rolled back to previous version
TODO: windows/linux

**Comment by ph** [comment]
@EricDavisX I've talked with @michalpristas to how we can include that in end2end testing. Any idea of how we should deal with that with QA?

**Comment by michalpristas** [comment]
Scenario in mind is like follows 
- get version X
- enroll
- see fleet says version X
- upgrade
- see fleet says version Y
- loop N times
-   get pid
-   kill -9 pid
- endloop
- wait for rollback to kick in (sleep 5 s)
- see fleet says version X

**Comment by EricDavisX** [comment]
I'd really like to get the upgrade feature in, based on 7.10 Agent as soon as we can... explicitly before we try to check in changes that enhance (may break) the existing functionality.  that ticket is: https://github.com/elastic/e2e-testing/issues/341

@ph I'm not sure what else you may mean?  We can talk off-line or you can expand a bit what your concern is please?

**Comment by ph** [comment]
Yes it will be great to have it in++ @michalpristas is looking into it.

@EricDavisX I did not express myself correctly.  The AC is "On upgrade error the Agent should rollback", my question is in manual QA do we want to trigger that scenario manual to assert the working behavior of that feature? I am not sure how easy is to trigger based on https://github.com/elastic/beats/issues/21518#issuecomment-722407219

**Comment by EricDavisX** [comment]
oh thanks!  I assert this can be safely covered without manual UI testing, presuming the code paths in Agent are not in any OS specific paths.  That is, if we get the e2e-testing scenario implemented as above, and the main upgrade test.  

I will ask the QA team to document the expectation for roll-back but we can mark it as not-needed manually.

**Comment by michalpristas** [comment]
actually there's quite OS specific code, mainly related to monitoring agent process PID and kicking of watching subprocess which we dont want to die with an agent.

**Comment by ph** [comment]
@EricDavisX @michalpristas once it's in working space we can discuss how we test that feature? I would prefer to have automated test here. But we only cover a fraction of our supported Oses.

**Comment by EricDavisX** [comment]
Happy to discuss anytime.

**Comment by EricDavisX** [comment]
@michalpristas  Hi, I know you were working on automated tests, did you have a WIP PR you wanted to discuss or a branch to point to?  Happy to review and pull and work it with ya.

**Comment by ph** [comment]
PR is at https://github.com/elastic/beats/pull/22537

**Comment by michalpristas** [comment]
closing as PR #22537 is merged
