### ISSUE TITLE
Error "failed to discover the source directory for installation: missing elastic-agent" is displayed on running elastic-agent install command on linux .deb

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#21512]
**Kibana version:**
Kibana: 7.10.0-SNAPSHOT

**Elasticsearch version:**
Elasticsearch: 7.10.0-SNAPSHOT

**Host OS and Browser version:**
Linux .deb , All

**Original install method (e.g. download page, yum, from source, etc.):**
From 7.10.0-SNAPSHOT cloud environment

**Description**
Error "failed to discover the source directory for installation: missing elastic-agent" is displayed on running elastic-agent install command on linux .deb

**Preconditions**
1. 7.10.0-SNAPSHOT Kibana  environment should be available.
2. Download the elastic-agent-7.10.0-SNAPSHOT-amd64.deb from artifact link(https://artifacts-api.elastic.co/v1/search/7.10.0-SNAPSHOT) and place it on home/zeus location at Linux Debian 9 machine.

**Steps to Reproduce**
1. Hit the command to get the root/admin permission: sudo su root
2. sudo dpkg -i elastic-agent-7.10.0-SNAPSHOT-amd64.deb
3. sudo elastic-agent install
4. Proceed with the installation and observe that error "failed to discover the source directory for installation: missing elastic-agent" is displayed.

**Test data**
N/A

**Impacted Test case id**
N/A

**Actual Result**
Error "failed to discover the source directory for installation: missing elastic-agent" is displayed on running elastic-agent install command on linux .deb

**Expected Result**
Agent should be successfully enrolled under Fleet tab on running elastic-agent install command on linux .deb

**What's working**
 - Issue is not occurring with Windows 64-bit package.

**What's not working**
 - N/A
 
**Screenshot**
![Linux deb](https://user-images.githubusercontent.com/59917944/95064744-cd047700-071d-11eb-8347-96ee134a0a22.jpg)

**Logs**
N/A

**Comment by rahulgupta-qasource** [comment]
@muskangulati-qasource Please review the bug.

**Comment by muskangulati-qasource** [comment]
Reviewed & assigned to @EricDavisX .

**Comment by EricDavisX** [comment]
@muskangulati-qasource @rahulgupta-qasource can you confirm if the vm was in a clean state when you ran the first command cited?  the error messaging sounds like an upgrade case, if not its just error handling that could maybe be cleaned up.  @blakerouse thoughts on when that error sequence would be shown?

Also, it would be helpful to know the hash of the build from Infra or the 'version' output of the Agent to know specifically what file you had.

**Comment by blakerouse** [comment]
You cannot use `elastic-agent install` from installation of `*.deb`. You just use `elastic-agent enroll` no `elastic-agent install`. This is expected behavior.

**Comment by EricDavisX** [comment]
it is strange that we had tested and thought it was working prior.  regardless, we know the spec know and will report if it errantly somehow works and we can update our test scripts to indicate to continue testing / supporting .deb / .rpm with enroll commands (and not to use 'install').  Thanks Blake

**Comment by peasead** [comment]
I had the same issue with an installation via `dnf install elastic-agent`. Version `7.13.1`.

To enroll in Fleet, I simply used the `enroll` command as @blakerouse mentioned above.

```
sudo /usr/bin/elastic-agent -f --url=https://nnnn.fleet.nn.cloud.es.io:443 --enrollment-token=12345==
```

**Comment by nadavkav** [comment]
> You cannot use `elastic-agent install` from installation of `*.deb`. You just use `elastic-agent enroll` no `elastic-agent install`. This is expected behavior.

Also true for the RPM install.
So please fix the Add agent "Enroll and start the Elastic Agent" CLI instructions.

**Comment by FlorianHeigl** [comment]
Error: failed to discover the source directory for installation: missing elastic-agent

Also some proper error handling (and message) would be rather nice.
