### ISSUE TITLE
Select ECS fields at setup time

### ISSUE THREAD

**Issue by novaksam** [elastic/beats#21521]
**Describe the enhancement:** For the setup command in beats (specifically filebeat) give the user the ability to select which ECS fields they upload to the index template. Similar to something like ```filebeat -c /etc/filebeat/filebeat.filebeat.yml setup --modules auditd,apache,azure```

**Describe a specific use case for the enhancement or feature:** As I'm troubleshooting cluster issues, I found that I had a cluster state of ~400MB. After trimming down default_fields for custom indexes I use I found that I still have a pretty large cluster state. Looking at the state, it appears that my indexes contain a considerable amount of fields that they don't need, however, I want to use ECS in those indices so that I have a consistent set of field to work with when querying my data. I propose adding an argument to filebeat setup where the user can select which set of ECS fields they add to their index pattern.

Ex. ```filebeat setup --fields network,source,destination,log,agent```

**Comment by andresrc** [comment]
We are evolving towards a new indexing strategy that will prevent this kind of issues.
