### ISSUE TITLE
Hope to add a new feature in google cloud modules of metricbeat

### ISSUE THREAD

**Issue by ChenTsungYu** [elastic/beats#21552]
Hello,

I want to ask is there any existed module of metricbeat for google cloud?  
I recommend the feature that counting all used resources in monitoring because it's useful to collect information about the total quantity in each resource.
Please check it below: 
![截圖 2020-09-29 下午6 26 06](https://user-images.githubusercontent.com/46296838/95179512-4d48dc00-07f3-11eb-975e-a8ab4db727bc.png)

Thanks!

**Comment by kaiyan-sheng** [comment]
cc @sorantis 
I have a draft PR to add [resource discover for AWS](https://github.com/elastic/beats/issues/19200). It would be good to add similar functionality for GCP as well.
