### ISSUE TITLE
[Elastic Agent] Heartbeat should not be bundled by default

### ISSUE THREAD

**Issue by ph** [elastic/beats#21564]
When working on adding support for Heartbeat in the agent the packaging code was changed to add heartbeat as part of the default shipped beats. We need to remove the code that add it to the packaging.

**Comment by ph** [comment]
cc @blakerouse and @EricDavisX

**Comment by EricDavisX** [comment]
can we link to the original discussion / ticket about this, I'd like to read for more context if possible.

**Comment by ph** [comment]
Found that original discussion https://github.com/elastic/beats/pull/20387#discussion_r464227046,

Going to create an issue to discuss bundle.

**Comment by ph** [comment]
@blakerouse @andrewvc Since the implementation is not complete we should just disable heartbeat for 7.x completely.

**Comment by blakerouse** [comment]
@ph I think for 7.10 its probably good to disable it.
