### ISSUE TITLE
Deprecation logs for Beats

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#21591]
Elastic Stack products will start to ship deprecation logs to a specific index based on the new indexing strategy. 

We should analyse how to leverage this functionality from beats:
* Directly or via stack monitoring?
* A single stream per beat, one stream for all the beats?

Coordinate with https://github.com/elastic/beats/issues/21336

**Comment by ph** [comment]
duplicate of #21592 ?

**Comment by andresrc** [comment]
mmm, I got an error but it seems it was created twice
