### ISSUE TITLE
Dell /EMC Powermax2000 Logs / Monitoring

### ISSUE THREAD

**Issue by BokuKDVZ** [elastic/beats#21606]
Hello, 
we do have an Dell / EMC Powermax 2000 Storage as datastore and we'd like to grep the logs and metrics from it and transfer it to elasticsearch. 
Currently we don't have any "own" monitoring og that system. We rely on the cloudIQ Website and some grafana Graphs, but we don't have a system which is capable of sending notifications and visulize MEtrics and Logs.
Our Monitoring Tool Check MK is neihter able to monitor the powermax.
Dell / EMC provides an API which could be used to grep all the necessary informations (https://www.dellemc.com/en-us/collaterals/unauth/quick-reference-guides/products/storage/docu88876.pdf).
The community beat "powermaxbeat" (https://github.com/kckecheng/powermaxbeat) isn't working and is almost 2 years old.

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
