### ISSUE TITLE
filebeat 1.2.2 and 1.2.3 beats_input_flushed_by_end_of_connection

### ISSUE THREAD

**Issue by rcsavage** [elastic/beats#2161]
FYI -

I am seeing this message in my Kibana display under "Tags" for some of my logs.

JSON SNIPIT of LOGS
    "@version": "1",
    "tags": [
      "beats_input_flushed_by_end_of_connection"
    ]
  },

This appears on some of my logs, but not most.   It makes my developer's lives very frustrating when they are searching Kibana.   

My setup:  Logstash->Elasticsearch 

I've tried setting the max lines in filebeat.yml to 8192 under multiline and that does not make a difference.   

For confirmed bugs, please report:
- Version: 1.2.2 and 1.2.3
- Operating System: CentOS 7/x86_64
- Steps to Reproduce: service filebeat restart

**Comment by urso** [comment]
No idea about this tag. I guess it's inserted by [logstash input plugin](https://github.com/logstash-plugins/logstash-input-beats)? I think one can still remove unwanted tags in logstash.

**Comment by rcsavage** [comment]
Logstash is configured with an input plugin called “logstash-input-beats” which is the translator that converts the filebeat messages into Logstash format.   Basically the problem exists inside the logstash-input-beats plugin.   See below, the snippet of code in the plugin is only called when there is a new thread.   There’s a RUBY “ensure” statement that seems to always call tag override function transformer.transform(event) into the new tag value “beats input flushed by end of connection”.   This is why you are seeing it.   Unfortunately, I don’t think there is a way for me to easily fix this problem.  

 # This Method is called inside a new thread
  def handle_new_connection(connection)
    @logger.debug? && @logger.debug("Beats inputs: accepting a new connection",
                                  :peer => connection.peer)

    LogStash::Util.set_thread_name("[beats-input]>connection-#{connection.peer}")

    connection_handler = LogStash::Inputs::BeatsSupport::ConnectionHandler.new(connection, self, @buffered_queue)
    @connections_list[connection] = connection_handler

    # All the errors handling is done here
    @circuit_breaker.execute { connection_handler.accept }
  rescue Lumberjack::Beats::Connection::ConnectionClosed => e
    # Only show theses errors if we run in debug mode,
    # This logger can get noisy if we use a proxy that check if the host is alive.
    @logger.debug? && @logger.debug("Beats Input: Remote connection closed",
                                  :peer => connection.peer,
                                  :exception => e)
  rescue LogStash::Inputs::BeatsSupport::CircuitBreaker::OpenBreaker,
    LogStash::Inputs::BeatsSupport::CircuitBreaker::HalfOpenBreaker => e
    @logger.warn("Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecting new connection until the pipeline recover.",
                :exception => e.class)
  rescue Exception => e # If we have a malformed packet we should handle that so the input doesn't crash completely.
    @logger.error("Beats input: unhandled exception",
                  :exception => e,
                  :backtrace => e.backtrace)
  ensure
    transformer = LogStash::Inputs::BeatsSupport::EventTransformCommon.new(self)
    connection_handler.flush do |event|
      # handle the basic event enrichment with tags
      # since at that time we lose all the context
      transformer.transform(event)
      event.tag("beats_input_flushed_by_end_of_connection")
      @output_queue << event
    End

**Comment by ruflin** [comment]
@ph perhaps you can comment on this one?

**Comment by ph** [comment]
First, in the latest beats input (> 3.1), I have removed this feature following the users complaints of the need to have it.

This can only happen in the following scenario:

- You are using a codec that can buffer, ie, multiline.
- Connection get killed or interrupted
- Events are still buffered in the codec.
- Event get tagged and send to the pipeline


Since no flush was done by the codec itself, the event could be considered as incomplete that why I've decided to add that tag.

You can use the mutate with `remove_tags` to get rid of them.
```
remove_tag => ["beats_input_flushed_by_end_of_connection"]
```
