### ISSUE TITLE
Netflow: Support v9 biflows by Cisco Meraki devices

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#21648]
**Describe the enhancement:**

Filebeat's Netflow input interprets Netflow v9 fields as IPFIX fields (fields 0-127 of IPFIX are supposed to be compatible with fields 0-127 of NetFlow v9). However, there's some issues with field IDs 23 and 24, which have a different meaning in the Cisco Meraki:

The RFCs define these and related fields as:

| ID | NetFlow v9 |  | IPFIX |  |
| --- | --- | --- | --- | --- |
| 1 | IN_BYTES | Incoming counter with length N x 8 bits for number of bytes associated with an IP Flow. | octetDeltaCount | The number of octets since the previous report (if any) in incoming packets for this Flow at the Observation Point. The number of octets includes IP header(s) and IP payload. |
| 2 | IN_PKTS | Incoming counter with length N x 8 bits for the number of packets associated with an IP Flow | packetDeltaCount | The number of incoming packets since the previous report (if any) for this Flow at the Observation Point. |
| 23 | OUT_BYTES | Outgoing counter with length N x 8 bits for the number of bytes associated with an IP Flow | postOctetDeltaCount | The definition of this Information Element is identical to the definition of Information Element 'octetDeltaCount', except that it reports a potentially modified value caused by a middlebox function after the packet passed the Observation Point.  |
| 24 | OUT_PKTS | Outgoing counter with length N x 8 bits for the number of packets associated with an IP Flow | postOctetPacketCount | The definition of this Information Element is identical to the definition of Information Element 'packetDeltaCount', except that it reports a potentially modified value caused by a middlebox function after the packet passed the Observation Point |

Under IPFIX the meaning is clear. `{counter}DeltaCount` is the incoming value into the observer, `post{Counter}DeltaCount` is the value after leaving the observer, if some middleware has modified it. The same meaning seems to be attributed to those fields by most NetFlow v9 devices. However, other devices (at least Cisco Meraki) seem to use these fields as the reverse counters for biflows (IPFIX uses fields under Private Enterprise Number (PEN) 29305 for that purpose, as defined in [RFC 5103.](https://tools.ietf.org/html/rfc5103)).

We should find a way to detect the use of fields 23&24 under v9 for reporting biflows, and, if not possible, at least provide a configuration option to enable the interpretation of such fields a reverse counters.

**Comment by dainperkins** [comment]
@adriansr this is just how netflow reports bi flow packets & bytes - I just happened to find it on meraki - [Netflow 9 fields](https://www.cisco.com/en/US/technologies/tk648/tk362/technologies_white_paper09186a00800a3db9.html) 

IPfix should always be reported as netflow v10, so keying off of netflow version 9 for handling fields 23 &24 should be sufficient.
