### ISSUE TITLE
Document common practice for bandwidth throttling in FAQ

### ISSUE THREAD

**Issue by brandonmensing** [elastic/beats#2164]
Users often want a Beat to limit network usage but it makes more sense for the network stack in the OS to handle this for many reasons. Let's provide an explanation of this and potentially an example of how this could be done on a common platform.

**Comment by tsg** [comment]
Googling a bit, [this](http://www.cyberciti.biz/faq/linux-traffic-shaping-using-tc-to-control-http-traffic/) seems to contain what we need, but I didn't test it yet.

Something like:
```
# delete existing rules
tc qdisc del dev eth1 root

# Create a class that limits to 512 Kbps
tc qdisc add dev eth1 root handle 1:0 htb default 10
tc class add dev eth1 parent 1:0 classid 1:10 htb rate 512kbps ceil 640kbps prio 0

# Use iptables to mark the packets going to Logstash
iptables -A OUTPUT -t mangle -p tcp --dport 5044 -j MARK --set-mark 10

# Assign the marked connections to the traffic shaping class
tc filter add dev eth1 parent 1:0 prio 0 protocol ip handle 10 fw flowid 1:10
```

**Comment by tsg** [comment]
After testing I managed to get the right effect with the following commands:

```
tc qdisc add dev $DEV root handle 1: htb
tc class add dev $DEV parent 1:1 classid 1:10 htb rate 50kbps ceil 50kbps
tc filter add dev $DEV parent 1:0 prio 1 protocol ip handle 10 fw flowid 1:10
iptables -A OUTPUT -t mangle -p tcp --dport 5044 -j MARK --set-mark 10
```

This sets a limit of 50 kbps on the TCP connections towards port 5044. I.e. you would normally execute this on the Beat side. It doesn't slow down any other connections.

Where should we put this example? FAQ? Troubleshooting guide?

**Comment by ruflin** [comment]
@tsg I would put it into FAQ. We should add some details there on why it is not part of beats itself and that is the way we recommend to do it.

**Comment by dedemorton** [comment]
Added to the FAQ with in #2225 (and cherry-picked into relevant branches)
