### ISSUE TITLE
Stats server should make harvester per file stats opt-in/out

### ISSUE THREAD

**Issue by bschaeffer** [elastic/beats#21653]
**Describe the enhancement:**

When enabled, the stats server started by filebeat for version 7.7.1 renders harvester statistics that include _per-file_ stats like so:

```json
"harvester": {
  "closed": 36484,
  "files": {
    "06ea1ab2-fc33-4b17-8672-c8d26e382511": {
      "last_event_published_time": "2020-10-07T16:29:53.347Z",
      "last_event_timestamp": "2020-10-07T16:29:48.646Z",
      "name": "/var/lib/docker/containers/843fa94da302257c7439ba0f4678d3c057c1f767682305ad031cc33118115154/843fa94da302257c7439ba0f4678d3c057c1f767682305ad031cc33118115154-json.log",
      "read_offset": 7396552,
      "size": 7396332,
      "start_time": "2020-10-07T16:27:18.339Z"
    },
    "fb06486c-5017-4a5e-8ed6-a1192b200071": {
      "last_event_published_time": "2020-10-07T16:28:54.405Z",
      "last_event_timestamp": "2020-10-07T16:28:54.404Z",
      "name": "/var/lib/docker/containers/e97b863f70c777da6c72ab1fc99ce2b563612cd284ea46356589718e992fb539/e97b863f70c777da6c72ab1fc99ce2b563612cd284ea46356589718e992fb539-json.log",
      "read_offset": 3374238,
      "size": 3374238,
      "start_time": "2020-10-07T16:28:54.404Z"
    }
  },
  "open_files": 2,
  "running": 2,
  "skipped": 0,
  "started": 36486
}
```

It would be great if the inclusion of the `harvester.files` was metric was configurable. Something along the lines of:

```yaml
http:
  enabled: true
  stats:
    harvesterFiles: false # IDK about the name but you get the idea
```

**Describe a specific use case for the enhancement or feature:**

We do not limit the number of open harvesters any of our filebeat instances can have, and we regularly have many instances with thousands (1-2k+) of open harvesters. I don't think the reason matters, but basically instances fall behind but we allow them to keep the file handles open because they do eventually catch up.

We also use a prometheus exporter ([`beat-exporter`](https://github.com/trustpilot/beat-exporter)) sidecar that reads the filebeat `/stats` API and allows it to be scrapped by prometheus. As you can imagine, it is not very efficient to have filebeat JSON-render precise harvester file statistics for 2000 files at `15s` intervals.

Would you be open to a PR to make this optional?

**Comment by bschaeffer** [comment]
I also think it might be good enough to extract this to its own endpoint: `/stats/harvester`

**Comment by bschaeffer** [comment]
Just dropping by to see if y'all would be open to a PR for this. Happy to do the work.

**Comment by kvch** [comment]
Sure, we would appreciate a PR. Our goal was to make it configurable from `*beat.yml` and enable it by default to make sure there is no backwards-incompatible change or any unexpected surprise.

If you open a PR, please ping me on it. Thank you so much!
