### ISSUE TITLE
[Agent] Reboot of Agent (with Endpoint installed) shows an temporary failure in Agent Activity log regarding bind port 6788 

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#21663]
Not sure if this is high priority, but its scary and is certainly big red warning that goes away so maybe we could squash it (if it isn't otherwise important to fix).

It seems a reboot of a Windows host with Endpoint enabled will yield a red ‘error’ state in the Agent activity log:

MessageApplication: endpoint-security--8.0.0-SNAPSHOT[3a872887-901b-4839-a139-6b15b549a0a2]: State changed to FAILED: failed to start connection credentials listener: listen tcp 127.0.0.1:6788: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

tested on 
hash of agent is: af3cda3c from build on Oct 6
Agent is here: snapshots.elastic.co/8.0.0-af3cda3c/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip

endpoint: 
snapshots.elastic.co/8.0.0-af3cda3c/downloads/endpoint-dev/endpoint-security-8.0.0-SNAPSHOT-windows-x86_64.zip

cloud Kibana info is$ git show -s 6f983728d7f8c2cf065a6d5099157a5cfdc3cd08
Date: Tue Oct 6 09:46:56 2020 +0300

see the vm was rebooted twice in this time frame:
<img width="984" alt="Screen Shot 2020-10-07 at 4 34 13 PM" src="https://user-images.githubusercontent.com/12970373/95386354-29ea6380-08bd-11eb-9f94-d0dee0b6073d.png">

**Comment by ph** [comment]
I think we have discussed that issue yesterday in a zoom call,  @blakerouse _idea_ was this would be fixed by locking introduced in a [PR](https://github.com/elastic/beats/pull/21573) from @michalpristas. IIRC this build from october 6 didn't include that fix.

**Comment by EricDavisX** [comment]
Thanks PH. I had thought that was a different symptom and fix (about .asc files only) but I see his pr has to do also with configs in general - so I can see that it relates to this now.

Further, I'm seeing another scenario too that seems to relate, when changing policy (from Endpoint Admin page) it started throwing an error repeatedly as Endpoint-security is stuck in a loop trying to re-start.
<img width="1006" alt="Screen Shot 2020-10-07 at 5 16 14 PM" src="https://user-images.githubusercontent.com/12970373/95389312-a2ebba00-08c1-11eb-8366-927c902a788b.png">

Application: endpoint-security--8.0.0-SNAPSHOT[3a872887-901b-4839-a139-6b15b549a0a2]: State changed to FAILED: failed to start connection credentials listener: listen tcp 127.0.0.1:6788: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
--
 
I'm not gonna log this separately, but we can test that tomorrow or soon, unless we know / think it is a separate bug now we could start following up on it.   @ph up to you if you want a separate ticket.

**Comment by EricDavisX** [comment]
the policy update also manifested on a linux host as the exact .asc file problem.  lol see this screenshot:
<img width="968" alt="Screen Shot 2020-10-07 at 5 25 16 PM" src="https://user-images.githubusercontent.com/12970373/95389659-23121f80-08c2-11eb-898c-9f91a55075ee.png">

**Comment by michalpristas** [comment]
This should be fixed by #21573 
Tested artifacts above do not include this fix
Today tested a flow multiple times:
- install agent
- update policy to include security
- update security policy

without any issues
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/1522652/95983659-4b4dd100-0e22-11eb-9654-8022e16dbb2c.png">

therefore closing. if we run into this again i will reopen
