### ISSUE TITLE
Test output of go tests is not printed in CI

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#21685]
When a go test fails, its output is not printed, difficulting the investigation of the problem.

For example the stacktrace of the failure in [this build](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-21671/2/tests) is only displayed as:
```
logger_test.go:43: 
    logger_test.go:59:
```

The problem may be in the library we use to parse the output to generate the junit files: https://github.com/elastic/beats/blob/df03addd29f2d051ea54c55ba10273eaf44d2bfa/dev-tools/mage/gotest.go#L255
Perhaps a different approach could be to do the parsing based on the JSON output of go test.

Ideally we should be able to:
* Always show the output of go test or equivalent information.
* Enable verbose output of go test when verbosity is enabled in mage.
* Still generate the junit files for jenkins.

**Comment by v1v** [comment]
Another example:

![image](https://user-images.githubusercontent.com/2871786/95992905-5dca0980-0e26-11eb-8a8a-58b6e69e15e9.png)

**Comment by jsoriano** [comment]
Maybe we can use [gotestsum](https://github.com/gotestyourself/gotestsum) to fix this as explored here: https://github.com/elastic/beats/pull/22541 Thanks @urso!
