### ISSUE TITLE
[Agent] the Elastic-agent.exe version command on Windows x64 is not responding when called from the Progam Files installed file location

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#21695]
verison info: 
8.0 snapshot tested on cloud

edavis-mbp:kibana_elastic edavis$ git show -s 43495d80ba02199216bf7f5679ea67874cb690f7
commit 43495d80ba02199216bf7f5679ea67874cb690f7
Date:   Wed Oct 7 18:53:19 2020 -0600

Agent:
https://snapshots.elastic.co/8.0.0-af3cda3c/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip

**Describe the bug:**
I'm not sure if this ever worked since we put in the new 'install' command, but it works from the unzipped Windows path, but I expect this usage is the definitive way to have a user know what version is installed so I'm logging it.

**Steps to reproduce:**
- install 8.0 latest
- install the agent with 'install' command
- change Agent to the new policy
on the host open an Admin powershell terminal and browse to C:\Program Files\Elastic\Agent and type:
elastic-agent.exe version

**Expected behavior:**
it should give you the Agent version of whatever is installed

<img width="705" alt="Screen Shot 2020-10-08 at 3 36 56 PM" src="https://user-images.githubusercontent.com/12970373/95507190-0be53780-097f-11eb-975b-0109bcd60c75.png">
 it just hangs on this prompt ^

**Comment by blakerouse** [comment]
I am interested in the state of your Elastic Agent. Seems like the running background Agent might be having an issue. Does the command ever timeout?

I just tried reproducing this on Windows 10 x64 with the 7.10.0 BC1 and I was un-able to reproduce the issue:

```
PS C:\Program Files\Elastic\Agent> .\elastic-agent.exe version
Daemon: 7.10.0 (build: 47b32e915424e16cafa74ddd9054e4848c283084 at 2020-10-08 20:44:05 +0000 UTC)
Binary: 7.10.0 (build: 47b32e915424e16cafa74ddd9054e4848c283084 at 2020-10-08 20:44:05 +0000 UTC)
```

**Comment by ph** [comment]
I think it's low impact.

I though initially its because the terminal is clicked and the "version" is interrupted? From eric this seems unlikely.

@blakerouse would the version command timeout if is not able to reach the daemon?

**Comment by EricDavisX** [comment]
I see it working on Win 10. When we can figure out what is wrong and fix my Win 7 environment I can re-test there, but this issue is likely a symptom of that issue where in the Agent just wasn't fully well and installed - that issue is: https://github.com/elastic/beats/issues/21601

**Comment by blakerouse** [comment]
@ph No it should not.

I am working on getting a Windows 7 VM setup so I can test on Windows 7. It seems to be having some issues specifically related to Windows 7.

**Comment by rahulgupta-qasource** [comment]
**Bug Conversion:**

Created **01** Testcase for this ticket:
https://elastic.testrail.io/index.php?/cases/view/35171
