### ISSUE TITLE
Instantiate a common Sarama logger for debugging

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#21710]
Sometimes the only way to investigate issues connecting with Kafka is to take a look to the Sarama logs. Sarama uses for logging a global logger, defined as [`Logger`](https://godoc.org/github.com/Shopify/sarama#Logger) in the top-level of the package. This means that all features using Sarama in the same binary, use the same logger, this makes it difficult to enable selective debugging.

Kafka output [enables this logging](https://github.com/elastic/beats/blob/d35dfb53111a86ed0e484f8450ffcf1474be60e8/libbeat/outputs/kafka/kafka.go#L50), but afaik this doesn't enable the logging if kafka input or the metricbeat kafka module are used.

Beats should have a unique way of enabling debugging for Sarama independently of the feature using Sarama clients.

I explored something like this for Metricbeat in https://github.com/jsoriano/beats/commit/e47a3cfbe0bc7af99418654031ef316929c2d385, but is not ideal as it would only work for Metricbeat. We could consider adding something like this at the libbeat level.

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
