### ISSUE TITLE
[Elastic Agent] Partial extracted beat result in failure to spawn beat

### ISSUE THREAD

**Issue by blakerouse** [elastic/beats#21718]
If Elastic Agent is stopped during a extraction of a beat or any application the resulting extraction can become incomplete if Elastic Agent is stopped while the extraction is occurring. The partial extracted folder is not removed during stop and on the next start the newly running Elastic Agent process will think the extraction was successful and run that binary. The starting of the binary can result in failure:

`Application: metricbeat--7.10.0[6a52a569-7a63-447a-82db-5102d3fb26b9]: State changed to FAILED: failed to start 'C:\Program Files\Elastic\Agent\data\elastic-agent-47b32e\install\metricbeat-7.10.0-windows-x86_64\metricbeat': fork/exec C:\Program Files\Elastic\Agent\data\elastic-agent-47b32e\install\metricbeat-7.10.0-windows-x86_64\metricbeat.exe: %! (MISSING)is not a valid Win32 application.`

For confirmed bugs, please report:
- Version: 7.10.0 BC1
- Operating System: Windows (expect same result on others)

**Comment by blakerouse** [comment]
Best solution is probably to perform extraction into a temporary folder then only move to the correct directory name, once extraction is successful. That would ensure that even if the program crashed or was hard killed would not result in a bad extraction.

**Comment by michalpristas** [comment]
I had the very same strategy in mind for this ;-)
