### ISSUE TITLE
Auditbeat unable to capture the bash builtin commands, variables and I/O redirections

### ISSUE THREAD

**Issue by deepayel** [elastic/beats#21728]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 8
- Operating System:  Linux
- Discuss Forum URL:
- Steps to Reproduce:  kill, unset commands

**Comment by andrewkroh** [comment]
Shell builtins are not monitored because they are just activity within the bash process. So this is expected.

If you need to monitor this activity then you can enable the pam_tty_audit PAM module. This will write audit events containing all of the activity within the shell.
