### ISSUE TITLE
[filebeat] in windows-2016 got some test failures TestSocketCleanup/TestReceiveNewEventsConcurrently

### ISSUE THREAD

**Issue by v1v** [elastic/beats#21757]
## Flaky Test

* **Test Name:** TestSocketCleanup and TestReceiveNewEventsConcurrently
* **Link:** https://github.com/elastic/beats/blob/32d45264d27acb5c62a272431dff96c47d1dea83/filebeat/inputsource/unix/server_test.go#L257 and https://github.com/elastic/beats/blob/32d45264d27acb5c62a272431dff96c47d1dea83/filebeat/inputsource/unix/server_test.go#L300
* **Branch:** Git branch the test was seen in. If a PR, the branch the PR was based off.
* **Artifact Link:** https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-21750/runs/1/steps/993/log/
```

=== RUN   TestSocketCleanup
    server_test.go:264: 
        	Error Trace:	server_test.go:264
        	Error:      	Received unexpected error:
        	            	listen unix C:\Users\JENKIN~1.PAC\AppData\Local\Temp\test.sock: socket: An address incompatible with the requested protocol was used.
        	Test:       	TestSocketCleanup
--- FAIL: TestSocketCleanup (0.00s)
=== RUN   TestReceiveNewEventsConcurrently
    server_test.go:330: 
        	Error Trace:	server_test.go:330
        	Error:      	Received unexpected error:
        	            	listen unix C:\Users\JENKIN~1.PAC\AppData\Local\Temp\test.sock: socket: An address incompatible with the requested protocol was used.
        	Test:       	TestReceiveNewEventsConcurrently
--- FAIL: TestReceiveNewEventsConcurrently (0.00s)
```
* **Notes:** Additional details about the test. e.g. theory as to failure cause

## Actions

- Disable them temporarily
- See https://github.com/elastic/beats/pull/21750#issuecomment-708314236 for further references

**Comment by urso** [comment]
The tests seem to be skipped by now.

Unix sockets are added only rather "recently" to windows. I think an up to date Windows 10 or Windows 2019 are required the least.
