### ISSUE TITLE
elastic-agent is reporting filebeat/metricbeat crash/restart loop and consumes CPU/RAM under Windows

### ISSUE THREAD

**Issue by sophiaxu8** [elastic/beats#21768]
elastic-agent was logging filebeat/metricbeat crash/restarts under Windows , and during this process was consuming high CPU and Memory.   

```
{
"list": [{
"id": "2be78562-fcd8-11ea-9e5f-352c21065ce3",
"agent_id": "31eda806-1598-4958-bcee-127ca4af5d0b",
"type": "ERROR",
"timestamp": "2020-09-22T14:33:11.6403368+01:00",
"subtype": "FAILED",
"message": "Application: filebeat--7.9.1[31eda806-1598-4958-bcee-127ca4af5d0b]: State changed to CRASHED: exited with code: 1",
"config_id": "e75bc000-f993-11ea-ad5c-0387b9ef4ebe"
}, {
"id": "2be78563-fcd8-11ea-9e5f-352c21065ce3",
"agent_id": "31eda806-1598-4958-bcee-127ca4af5d0b",
"type": "STATE",
"timestamp": "2020-09-22T14:33:11.6403368+01:00",
"subtype": "STARTING",
"message": "Application: filebeat--7.9.1[31eda806-1598-4958-bcee-127ca4af5d0b]: State changed to STARTING: Starting",
"config_id": "e75bc000-f993-11ea-ad5c-0387b9ef4ebe"
}, {
"id": "2be78564-fcd8-11ea-9e5f-352c21065ce3",
"agent_id": "31eda806-1598-4958-bcee-127ca4af5d0b",
"type": "STATE",
"timestamp": "2020-09-22T14:33:11.6403368+01:00",
"subtype": "STARTING",
"message": "Application: filebeat--7.9.1[31eda806-1598-4958-bcee-127ca4af5d0b]: State changed to RESTARTING: Restarting",
"config_id": "e75bc000-f993-11ea-ad5c-0387b9ef4ebe"
}
```

![renditionDownload](https://user-images.githubusercontent.com/18129911/95894873-9989a400-0d3e-11eb-922e-0dc44aa4ee3f.jpeg)

> On inspecting the logs the following errors appear for the host:

- `"elastic-agent-client got error: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: remote error: tls: internal error\""`
- ` Error getting details for process Registry with pid=144: error getting process mem for pid=144: OpenProcess failed for pid=144: Access is denied.` (error appears for a number of different processes/PIDs)

A restart resolved the issue, ths OS is `Windows 10 Enterprise Version 10.0.18363`.

**Comment by mgevans-5** [comment]
We have also seen this behavior.  Win 2016 server.  Only out of the box default config running.

{"log.level":"info","@timestamp":"2020-08-21T15:54:50.746-0400","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2020-08-21T15:54:50-04:00: type: 'STATE': sub_type: 'STARTING' message: Application: filebeat--7.9.0[ca0b8190-ad90-4e15-90b2-fc85a67aecb8]: State changed to STARTING: Starting","ecs.version":"1.5.0"}
{"log.level":"error","@timestamp":"2020-08-21T15:54:50.746-0400","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2020-08-21T15:54:50-04:00: type: 'ERROR': sub_type: 'FAILED' message: Application: filebeat--7.9.0[ca0b8190-ad90-4e15-90b2-fc85a67aecb8]: State changed to CRASHED: exited with code: 1","ecs.version":"1.5.0"}
{"log.level":"info","@timestamp":"2020-08-21T15:54:50.746-0400","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2020-08-21T15:54:50-04:00: type: 'STATE': sub_type: 'STARTING' message: Application: filebeat--7.9.0[ca0b8190-ad90-4e15-90b2-fc85a67aecb8]: State changed to RESTARTING: Restarting","ecs.version":"1.5.0"}
{"log.level":"info","@timestamp":"2020-08-21T15:54:50.992-0400","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2020-08-21T15:54:50-04:00: type: 'STATE': sub_type: 'STARTING' message: Application: metricbeat--7.9.0[ca0b8190-ad90-4e15-90b2-fc85a67aecb8]: State changed to STARTING: Starting","ecs.version":"1.5.0"}
{"log.level":"error","@timestamp":"2020-08-21T15:54:50.992-0400","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2020-08-21T15:54:50-04:00: type: 'ERROR': sub_type: 'FAILED' message: Application: metricbeat--7.9.0[ca0b8190-ad90-4e15-90b2-fc85a67aecb8]: State changed to CRASHED: exited with code: 1","ecs.version":"1.5.0"}
{"log.level":"info","@timestamp":"2020-08-21T15:54:50.992-0400","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2020-08-21T15:54:50-04:00: type: 'STATE': sub_type: 'STARTING' message: Application: metricbeat--7.9.0[ca0b8190-ad90-4e15-90b2-fc85a67aecb8]: State changed to RESTARTING: Restarting","ecs.version":"1.5.0"}

![Elastic-Agent-Ran-Server-Out-Of-Memory](https://user-images.githubusercontent.com/69169238/96597057-605faf80-12bb-11eb-9068-ad89ac27c6bc.jpg)

**Comment by ph** [comment]
Going to close this as fixed, we have been doing extensive testing on windows.
