### ISSUE TITLE
Packetbeat misconfigured default JSON setting

### ISSUE THREAD

**Issue by CrispySteak** [elastic/beats#2177]
Using Kibana 5.0 v4 on Linux x64 the following fields import as strings rather than numbers (which is more than rather inconvenient and intuitive):

source.stats.net_packets_total
source.stats.net_bytes_total 
dest.stats.net_bytes_total
dest.stats.net_packets_total

Problem should be in the  beats/packetbeat/etc/kibana/index-pattern/packetbeat.json 

Thanks!

**Comment by andrewkroh** [comment]
It looks like these fields are marked as `keyword` type in the [index template](https://github.com/elastic/beats/blob/master/packetbeat/packetbeat.template.json#L276-L282) so both the fields.yml and the dashboards will need to be updated.
