### ISSUE TITLE
Collect kafka cluster id in Metricbeat module

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#21781]
Collect the [kafka cluster ID](https://cwiki.apache.org/confluence/display/KAFKA/KIP-78%3A+Cluster+Id) in Metricbeat module, so it is easier to separate metrics from different clusters.

Cluster ID can be obtained from a [Metadata Response object](https://godoc.org/github.com/Shopify/sarama#MetadataResponse), from clusters implementing [Metadata API version >= 2](https://kafka.apache.org/protocol) (since kafka 0.10.1.0).

Cluster ID in Kafka is randomly generated on cluster creation (see [docs](https://kafka.apache.org/documentation/#impl_clusterid)).

New field can be stored in `kafka.cluster.id`, all metricsets should collect it. For the broker metricset, based on Jolokia, we'd need to find if this value is exposed through JMX.

Dashboards could leverage this field when available.

Links:
* [Kafka Cluster ID KIP-78](https://cwiki.apache.org/confluence/display/KAFKA/KIP-78%3A+Cluster+Id).
* [Metadata Response object in Sarama](https://godoc.org/github.com/Shopify/sarama#MetadataResponse).
* [Cluster ID](https://kafka.apache.org/documentation/#impl_clusterid) in Kafka user documentation.

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
