### ISSUE TITLE
New protocol support: MySQL binlog

### ISSUE THREAD

**Issue by BrickXu** [elastic/beats#218]
Could we support to dump MySQL packets between master and slave to analyze the replication statements ?

**Comment by tsg** [comment]
Marked this as a new protocol request, because I think the replication protocol is completely different in the case of MySQL. It's something that I think it makes sense to have, but it's unlikely that we'll get to it soon.

**Comment by moooofly** [comment]
I need this feature too.

In my scenario, I need to measure the latency of mysql replication across data center. So this feature means a lot to me.
