### ISSUE TITLE
Elastic Agent duplicates work of packaging included Beats

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#21810]
We would like to speed up the build time on CI for packaging Elastic Agent. I think there are two ways in which we can speed it up. Both are related to that it repackages Filebeat, Metricbeat, and Heartbeat.

1. Reuse artifacts from the those Beats if they have already been built. This would reduce the build time for Unified Build by about 17 minutes. It's currently taking `22m39.379290932s` of which 5m16.45350963s is Filebeat, 4m56.564996773s is Heartbeat, and 7m42.517185465s is Metricbeat.
1. Only build beat packages for the target architectures of the agent package. When [beats-ci packages](https://beats-ci.elastic.co/job/Beats/job/packaging/job/master/) it tests many architectures like ppc and s390x, but Agent only builds for specific architectures mentioned in its [magefile](https://github.com/elastic/beats/blob/2996b6f1891ec03f48ab5cf2d2b989b94e7ec1d9/x-pack/elastic-agent/magefile.go#L302-L307). So it builds extra beat artifacts that it does not use. We see times like `package ran for 1h18m57.50154753s` for Agent in this scenario. This can be accomplished by passing `PLATFORMS` when packaging the individual beats that go into Agent.

**Comment by ruflin** [comment]
My preference would be to go with approach 1. The reason is also having things like apm-server and endpoint in mind. The Agent should not build its process but just use prebuilt binaries. This becomes more obvious when Elastic Agent is in its own repository.

**Comment by ph** [comment]
I would go with option 1, as @ruflin mentioned I think having it in his own repo would drive that requirement.
