### ISSUE TITLE
[Agent] Upgradeable Agent issue - 8.0 Agent is not showing as 'upgradeable=true' 

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#21822]
The saved object api output shows that they are not upgradeable.  I think the windows agent install should be.  the linux installs are still using the old 'enroll and elastic-agent run' commands.

https://kibana.endpoint.elastic.dev/api/saved_objects/_find?type=fleet-agents

here is the version currently:
edavis-mbp:kibana_elastic edavis$ git show -s 0dba45d247ab24b749c342718e98190d25a96577
Date:   Mon Oct 12 20:21:04 2020 -0500

Agent will be from the same time frame build....  I can't ssh on to an Agent to get its version info currently
<img width="1002" alt="Screen Shot 2020-10-14 at 4 54 46 PM" src="https://user-images.githubusercontent.com/12970373/96044151-ff108a00-0e3d-11eb-963b-6ca7ada116bc.png">

[agent-upgradeable.json.txt](https://github.com/elastic/beats/files/5380550/agent-upgradeable.json.txt)
<img width="557" alt="Screen Shot 2020-10-14 at 3 56 00 PM" src="https://user-images.githubusercontent.com/12970373/96038898-d71d2880-0e35-11eb-9619-bec0e565157a.png">

here is the siem-team repo code that does the install for windows, updated to use 'install' command:
https://github.com/elastic/siem-team/blob/master/cm/ansible/roles/deploy-agent/tasks/win-main.yml#L44

**Comment by EricDavisX** [comment]
the demo server is not deploying today... that will need to be solved before we could hope to use it.  i'll look at this after some more direct testing of the upgrade feature

**Comment by EricDavisX** [comment]
Ah we think this is fixed - see above.  thats great news!

**Comment by michalpristas** [comment]
@EricDavisX  This was closed by PR, should be working now

**Comment by EricDavisX** [comment]
I have seen this in the data on the saved objects for the 8.0 based Endpoint / Fleet 'demo' server.  and in the 7.10 object -> https://asdf.europe-west1.gcp.cloud.es.io:9243/api/saved_objects/_find?type=fleet-agents
 - it shows the Agent as upgradeable as desired.  its good.  and i've tested end to end with 7.11 and done the upgrade.  we're good here
