### ISSUE TITLE
Stop file based dynamic inputs after some timeout

### ISSUE THREAD

**Issue by exekias** [elastic/beats#21837]
**Describe the enhancement:**

Containers based dynamic providers launch log inputs (Filebeat) to read logs from certain containers. Providers implement a cleanup timeout function for these, so the actual removal of the input happens some time after the container finishes. This gives some room for the input to read last messages from the container, hopefully reaching EOF.

Filebeat/Metricbeat autodiscover providers used this cleanup, which is useful only for the case of logs (for metrics we don't want to keep polling from a dead container, as it will result on errors while trying to fetch the metrics). Metricbeat could configure this timeout to 0, to avoid keeping the input this extra time.

This logic is now in composable dynamic providers, which are common to logs and metrics, ie: https://github.com/elastic/beats/blob/be5c2902cd5c492f98d299740de03cf9d19626b4/x-pack/elastic-agent/pkg/composable/providers/docker/docker.go#L86

We need to come up with a plan to do this timeout only for log inputs. I think this logic should be outside the provider, either done by the agent composable code or Filebeat itself.

**Comment by exekias** [comment]
@blakerouse we discussed briefly about this one

**Comment by blakerouse** [comment]
Been thinking about this and trying to understand why a grace period is needed on a container or a pod in Kubernetes for logs at all? Being that the provider should only remove the pod once it has fully stopped, wouldn't that mean all of the log data is written to the log file?

The only reason I would think that all the log data would not be in that file is because Kubernetes runtime does not guarantee that the log data is flushed to disk before marking the pod as finished. Which seems like a bug of the runtime, but something we still might need to handle none the less.

**Comment by exekias** [comment]
The log data may have been written to the disk, but we still need to have the input around to actually read it until EOF. Log input is not guaranteed to be up to date with the last written bytes at all times, situations like high IO / buffers or a slow ES cluster may delay collection from the Filebeat side, making us miss the last few lines of the file.

**Comment by ruflin** [comment]
Is this generic to logs input or more specific to the logfile input and dockerlogs input but does not matter for all the others? If no config is added, what is the default behaviour currently?

@exekias You mention above, it should not be the provider adding this information, can you elaborate on why? My thinking is that it should not be in Filebeat as Filebeat would not know, if it comes from autodiscovery or just a normal input, it just executes.

**Comment by exekias** [comment]
> Is this generic to logs input or more specific to the logfile input and dockerlogs input but does not matter for all the others? If no config is added, what is the default behaviour currently?

Yes, this problem would be specific to any file based input, normally the `container` input would be the most used (`docker` input is deprecated in favour of it).

> @exekias You mention above, it should not be the provider adding this information, can you elaborate on why? My thinking is that it should not be in Filebeat as Filebeat would not know, if it comes from autodiscovery or just a normal input, it just executes.

The provider doesn't know what the event will be used for, it may spawn a metrics input, a logs input, or even both. I agree Filebeat may not need to know either (although it's a possible approach), so this would be somewhere in the dynamics input manager code, not the providers.

**Comment by ruflin** [comment]
I missed the point around "The provider doesn't know what the event will be used". So agree, provider is also not the place for it.

**Comment by exekias** [comment]
> Update: Back to the provider. The provider might not add it to the event but it is the place where it is defined, on what additional configs should be added if it matches certain input types?

This could be ok from my POV. I'm not sure if the need for a wait is really tied to the type of provider, but the dynamic nature of it. Still I'm ok with adding this as a flag/setting hardcoded in providers, where they tell you: "file based inputs need to wait for a little bit before closing" still they don't handle that logic
