### ISSUE TITLE
[Elastic Agent] Add documentation for the k8s provider

### ISSUE THREAD

**Issue by ph** [elastic/beats#21848]
There are currently no docs for any providers https://github.com/elastic/beats/pull/21480

Documentation guide that walks through steps required to enable K8s and pod level observability with elastic agent in standalone mode

**Comment by ph** [comment]
@ChrsMark it is possible that you take that over from @exekias ?

**Comment by ChrsMark** [comment]
@ph should this be a section in [providers docs](https://github.com/elastic/observability-docs/blob/master/docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc#docker-provider) like `docker` provider?

Also, I'm wondering if we should completely remove (or just replace with standalone version) the [running on k8s](https://github.com/elastic/observability-docs/blob/master/docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc) docs.

**Comment by ph** [comment]
Maybe it's a bit of both? @dedemorton could certainly offer guidelines here.

**Comment by ChrsMark** [comment]
@dedemorton any thoughts here?

**Comment by dedemorton** [comment]
@ChrsMark Sorry I missed your comment last week. I had to take some personal time off unexpectedly. Thanks for opening the PR. I will review it and make my recommendations there.
