### ISSUE TITLE
Discuss: Beats instance meta.json generation

### ISSUE THREAD

**Issue by urso** [elastic/beats#21847]
An issue we are often seeing is that users copy the data directory between multiple Beats instances. Either in order to copy an installation/setup to another machine, or more often when preparing an Image for reuse with multiple physical machines. The impact is that different sources actual data or stack-monitoring data originate from can often not be distinguished anymore.

Some potential options to reduce the impact:
1. Do not create a data/meta.json file or other when running `<beatname> setup`. When preparing an image it is not uncommon to run setup only in order to prepare the Stack. Setup and user credentials for publishing events might even differ.
2. Add a machine-hash (based on MAC address and other hardware information) to meta.json. We can not use the hash as ID, as multiple instance of a Beat might be running on a machine, but we can use this hash as additional guard. If we figure that the hash has changed we will not start up and warn the user that the data directorly might have been copied from another machine and must therefore cleaned. Sometimes you have to replace Hardware. In that case users can just remove the machine hash from `meta.json` and a new hash will be computed, without changing the identity of the Beat.

**Comment by maederm** [comment]
It would be really helpful if the behavior was at least documented.
