### ISSUE TITLE
[Elastic Agent] Wrong format of the data_stream for metrics and log.

### ISSUE THREAD

**Issue by ph** [elastic/beats#21862]
Currently we send the log of the elastic agent and the subprocess to `logs-elastic.agent.{process-name}-default` and it should be `logs-elastic_agent.{process-name}-default`. Note the **underscore** vs the dot.

**Comment by ruflin** [comment]
To share a bit more background here. The initial proposal was `elastic.agent`. It was also inspired by the field name we have which is `elastic.agent.id`. But the question was then raised, if monitoring data from kibana or elasticsearch should also have such a prefix but I think the answer is no. So the prefix is the product name which in our case is `elastic_agent`. And that is why we should change it.

**Comment by ph** [comment]
@ruflin Thanks for the clarification, I was like that why we messed up :)

**Comment by rahulgupta-qasource** [comment]
**Bug Conversion:**

Created **01** Testcase for this ticket:
https://elastic.testrail.io/index.php?/cases/view/35173
