### ISSUE TITLE
how to build the metricbeat where use oracle module

### ISSUE THREAD

**Issue by linjikun** [elastic/beats#21875]
when I add the oracle package,go build metricbeat fail!

1.first: set env
GOARCH=amd64;GOOS=linux;CGO_ENABLED=0
2.error msg:
E:\gitAndGo\go\pkg\mod\github.com\godror\godror@v0.10.4\orahlp.go:450:53: undefined: VersionInfo
E:\gitAndGo\go\pkg\mod\github.com\godror\godror@v0.10.4\orahlp.go:459:53: undefined: VersionInfo
E:\gitAndGo\go\pkg\mod\github.com\godror\godror@v0.10.4\orahlp.go:477:19: undefined: VersionInfo
E:\gitAndGo\go\pkg\mod\github.com\godror\godror@v0.10.4\orahlp.go:478:19: undefined: VersionInfo
E:\gitAndGo\go\pkg\mod\github.com\godror\godror@v0.10.4\orahlp.go:479:30: undefined: ObjectType
E:\gitAndGo\go\pkg\mod\github.com\godror\godror@v0.10.4\orahlp.go:480:31: undefined: Event
E:\gitAndGo\go\pkg\mod\github.com\godror\godror@v0.10.4\orahlp.go:480:41: undefined: Subscription
E:\gitAndGo\go\pkg\mod\github.com\godror\godror@v0.10.4\orahlp.go:481:10: undefined: StartupMode
E:\gitAndGo\go\pkg\mod\github.com\godror\godror@v0.10.4\orahlp.go:482:11: undefined: ShutdownMode
E:\gitAndGo\go\pkg\mod\github.com\godror\godror@v0.10.4\orahlp.go:483:59: undefined: Data
E:\gitAndGo\go\pkg\mod\github.com\godror\godror@v0.10.4\orahlp.go:483:59: too many errors

3.second: set env
GOOS=linux;CGO_ENABLED=1
4.error msg:
gcc_linux_amd64.c: In function '_cgo_sys_thread_start':
gcc_linux_amd64.c:61:2: error: unknown type name 'sigset_t'; did you mean '_sigset_t'?
  sigset_t ign, oset;
  ^~~~~~~~
  _sigset_t
gcc_linux_amd64.c:66:2: error: implicit declaration of function 'sigfillset' [-Werror=implicit-function-declaration]
  sigfillset(&ign);
  ^~~~~~~~~~
gcc_linux_amd64.c:61:16: error: unused variable 'oset' [-Werror=unused-variable]
  sigset_t ign, oset;
                ^~~~
cc1.exe: all warnings being treated as errors

I want to know how to fix it

**Comment by sayden** [comment]
This kind of support requests must be opened in https://discuss.elastic.co/

Follow the instructions provided here: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-oracle.html#_requirements and open a issue in Discuss if you have any.

I'm closing this.
