### ISSUE TITLE
Clarify manual template loading is required for use with Logstash

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#2189]
On https://www.elastic.co/guide/en/beats/winlogbeat/5.0/config-winlogbeat-logstash.html  we should highlight that manual template loading is required and link to the instructions on the next page of the getting started guide.

And under https://www.elastic.co/guide/en/beats/winlogbeat/5.0/winlogbeat-template.html#load-template-auto we should state that those template options are not supported with using `output.logstash`. I have seen several users trying to use those options with the Logstash output.

https://discuss.elastic.co/t/winlogbeat-logs-not-being-captured/57500
https://discuss.elastic.co/t/logstash-not-receiving-logs-from-winlogbeat-5-0-alpha/57277/3

**Comment by dedemorton** [comment]
Closed with #2477
