### ISSUE TITLE
Beats diagnostics tooling

### ISSUE THREAD

**Issue by urso** [elastic/beats#21965]
Beats should provide a tool that allows one to easily collect information that can help to analyze known user issues. Diagnostics should contain static information like host meta data, configuration files and existing log files. Active data collection should also be supported, like metrics or memory profiles.

Tasks Phase 1:
- ~~Enable http endpoint with unix socket or named pipe by default. e.g. `/var/lib/<meta-hash>.sock`~~ - completed as part of previous work to enable monitoring
- ~~Add API to read current Beats configuration. For now the static configuration used on startup, including modules.~~ - completed as part of previous work for `elastic-agent inspect`
- [x] Introduce CLI subcommand 'diag collect' collecting diagnostics into a zip file:
  - [x] query Beat info via unix socket
  - [x] query active Beat configuration
- [x] Collect the Beat instance log files if file output has been configured.
- [ ] #29776
  - [ ] Libbeat collects metrics every 10s into ring buffer (N=60)
  - [ ] Expose internal metrics via API
  - [ ] Diagnostics tool reads metrics ring buffer
- [ ] (optional) CLI subcommand `diag add` to add extra files and directories to a diagnostics report.
- [ ] log / capture std from the processes started

**Comment by jlind23** [comment]
@michel-laterman just added a task around:  log / capture std from the processes started

**Comment by jlind23** [comment]
Closing - Future work will be track there: https://github.com/elastic/beats/issues/29776
