### ISSUE TITLE
[Fleet] Upgradeable Agent issue, need Agent to figure out best correct source_uri when not passed in, based on '-SNAPSHOT' in version or not.  

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#21971]
**Kibana version:**
commit: 7.11 snapshot cloud install of whole stack, with 7.10 BC1 Agent
edavis-mbp:kibana_elastic edavis$ git show -s 29426f57db725bedc29ee9d7adb5efd2aa2f1983
Date:   Mon Oct 12 12:35:00 2020 +0200

Agent hash 116336aa, the BC1 build from : elastic-agent-7.10.0-linux-x86_64.tar.gz
from the elastic /dev/issues/1496 release repo.
7.10.0-116336aa
https://staging.elastic.co/7.10.0-116336aa/downloads/beats/elastic-agent/elastic-agent-7.10.0-linux-x86_64.tar.gz

**Browser version:**
Chrome on macOS

**Describe the bug:**
The UI exposes the 'upgrade agent' option and we are currently under discussion on if it can work or if it should be disabled in the UI only (API will work) for Agent 'snapshot' builds.

**Steps to reproduce:**
Install 7.11 cloud kibana
and then install a 7.10 snapshot Agent
then upgrade via the API or upgrade via the UI?  Is the UI even a valid mechanism to test here?  If the Agent is a formal BC AND it was installed with the Agent 'install' mechanism it should be upgradeable.  

I had 2 agents and used the UI to do a bulk_upgrade api as follows

POST to: https://77366674948c4252bb020480c0973260.us-east-1.aws.staging.foundit.no:9243/api/fleet/agents/bulk_upgrade

with BODY as:
{"agents":["73556801-7458-4a34-99e7-09eb542f26c1","90872928-e61d-43d6-95c8-d5181095588f"],"version":"7.11.0-SNAPSHOT"}

screenshot, it returns a 200/ok
<img width="1048" alt="Screen Shot 2020-10-14 at 4 36 01 PM" src="https://user-images.githubusercontent.com/12970373/96042463-6f69dc00-0e3b-11eb-89bc-13c8b0d8ca17.png">

**Expected behavior:**
1) UI works, or the UI is grayed out if it isn't going to work.  I'm not sure if the correct location can be figured out for Kibana Snapshot builds (is it dependent on the Agent or the Kibana build state?)

2) API should work, if the POST passes all required params... 

**Screenshots from UI:**
<img width="1156" alt="Screen Shot 2020-10-14 at 4 30 27 PM" src="https://user-images.githubusercontent.com/12970373/96042610-a7711f00-0e3b-11eb-9751-ee7c135cc403.png">

**Errors in browser console (if relevant):**
none

**Provide logs and/or server output (if relevant):**
n/a

**Comment by EricDavisX** [comment]
discussed with Michal, we are pushing this to Beats side to finish off:

In some minimal detail:
I am expecting the Beats change here to be that Beats will use the -SNAPSHOT or lack thereof in the version passed in (when there is no source_uri), to determine the ‘latest Agent’ url to attempt to download from on the Elastic artifacts repository side, for upgrading.  This is as we had chatted, just confirming.

those URLs will look quite like this for the windows x86 zip example:
https://snapshots.elastic.co/7.11.0-cb2d1f35/downloads/beats/elastic-agent/elastic-agent-7.11.0-SNAPSHOT-windows-x86.zip
 - I will ping @Conky5 and @mgreau from Infra team.  My intention on including them is to help any future path updating... if the path changes it will impact this feature.  Of course, that's not really unique to just this feature but I wanted to reach out just as a bare-minimum communication point between the teams, on the chance it is ever helpful.  Cheers.

The nuance for the Beats side is to take the set version URL and parse out the hash for the build, and to get the os specific naming and extension correct for a given install... Windows (x86 and x64) zip, and linux (x86 and x64) .tar.gz and darwin .tar.gz.

**Comment by EricDavisX** [comment]
The following PR should fix this, its merged and back-ported - just waiting on all builds to be completed so we can assess.  https://github.com/elastic/beats/issues/21971

**Comment by EricDavisX** [comment]
We tested with the 7.11 Kibana cloud snapshot and the 7.10 snapshot Agent (both of which have all known fixes required) and found one more bug.  the Agent side update is cited as hopefully easy fix and @michalpristas is working it.  we'll test again in SNAPSHOT and that will give us expectation that the final BC will work great.

the bug as I see it is that the attempted version to download got the versions mixed + matched, 7.10 + 7.11 in the url, which isn't going to work.   See below highlight:
snapshots.elastic.co/7.10.0-6e8d8d51/downloads/beats/elastic-agent/elastic-agent-7.11.0-SNAPSHOT-darwin-x86_64.tar.gz

full error reported in Activity Log:
MessageApplication: [f6a113d6-cf5a-41b9-844b-97d1039d89a2]: State changed to FAILED: failed upgrade of agent binary: 3 errors occurred: * package ‘/Library/Elastic/Agent/data/elastic-agent-773b7e/downloads/elastic-agent-7.11.0-SNAPSHOT-darwin-x86_64.tar.gz’ not found: open /Library/Elastic/Agent/data/elastic-agent-773b7e/downloads/elastic-agent-7.11.0-SNAPSHOT-darwin-x86_64.tar.gz: no such file or directory * call to ‘https://snapshots.elastic.co/7.10.0-6e8d8d51/downloads/beats/elastic-agent/elastic-agent-7.11.0-SNAPSHOT-darwin-x86_64.tar.gz’ returned unsuccessful status code: 404: /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/artifact/download/http/downloader.go[142]: unknown error * call to ‘https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.11.0-SNAPSHOT-darwin-x86_64.tar.gz’ returned unsuccessful status code: 404: /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/artifact/download/http/downloader.go[142]: unknown error

**Comment by EricDavisX** [comment]
pr is here for the master line fix: https://github.com/elastic/beats/pull/22175/files

**Comment by michalpristas** [comment]
@EricDavisX can we close this?

**Comment by EricDavisX** [comment]
I think we can now - we did great here to make this happen and I expect user's will be delighted by our efforts!

Final tests will be detailed in the meta issue.  Cheers!
