### ISSUE TITLE
Problems with obtaining reviewdog 

### ISSUE THREAD

**Issue by advancedwebdeveloper** [elastic/beats#21976]
Hi.
Here is my situation:

> $make lint
> go: downloading golang.org/x/lint v0.0.0-20200302205851-738671d3881b
> go: found golang.org/x/lint/golint in golang.org/x/lint v0.0.0-20200302205851-738671d3881b
> go: downloading github.com/haya14busa/reviewdog v0.10.2
> go: found github.com/haya14busa/reviewdog/cmd/reviewdog in github.com/haya14busa/reviewdog v0.10.2
> go get: github.com/haya14busa/reviewdog@v0.10.2: parsing go.mod:
> 	module declares its path as: github.com/reviewdog/reviewdog
> 	        but was required as: github.com/haya14busa/reviewdog
> make: *** [Makefile:142: lint] Error 1

> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD="/home/oceanfish81/beats/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build107471361=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
> 

CC @haya14busa @shogo82148

**Comment by shogo82148** [comment]
Hi, Can you try this fix? https://github.com/elastic/beats/pull/21981
It works in my environment.

```
% make lint
go: found github.com/reviewdog/reviewdog/cmd/reviewdog in github.com/reviewdog/reviewdog v0.10.2
go: found golang.org/x/lint/golint in golang.org/x/lint v0.0.0-20200302205851-738671d3881b
reviewdog -diff "git diff master"
2020/10/19 23:37:43 reviewdog: [start]	runner=golint
2020/10/19 23:41:35 reviewdog: [finish]	runner=golint
```

**Comment by andresrc** [comment]
We are not using this tool anymore, it might be removed.

**Comment by urso** [comment]
There is an optional pre-commit hook one can install via `make setup-commit-hooks`. The pre-commit hook will run `make lint`, which runs reviewdoc in order to check if commits have any lint errors. Given the number of lint messages we get from multiple packages it is not widely used.

The fix and backports have been merged. Closing.
