### ISSUE TITLE
[Docs] Indicate that only some fields can be used in rollover_alias

### ISSUE THREAD

**Issue by fdartayre** [elastic/beats#21970]
**Describe the enhancement:**
We should document that a restricted set of field names can be used in [`setup.ilm.rollover_alias`](https://www.elastic.co/guide/en/beats/filebeat/master/ilm.html#setup-ilm-rollover_alias-option) (and `setup.ilm.policy_name`).

According to the [code](https://github.com/elastic/beats/blob/7.9/libbeat/idxmgmt/ilm/ilm.go#L149), it relies on [`fmtstr.FieldsForBeat`](https://github.com/elastic/beats/blob/7.9/libbeat/common/fmtstr/formattimestamp.go#L47) which accepts only certain fields:
```go
// FieldsForBeat returns a common.MapStr with the given beat name and
// version assigned to their standard field names.
func FieldsForBeat(beat string, version string) common.MapStr {
	return common.MapStr{
		// beat object was left in for backward compatibility reason for older configs.
		"beat": common.MapStr{
			"name":    beat,
			"version": version,
		},
		"agent": common.MapStr{
			"name":    beat,
			"version": version,
		},
		// For the Beats that have an observer role
		"observer": common.MapStr{
			"name":    beat,
			"version": version,
		},
	}
```

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
