### ISSUE TITLE
INFO log if TLS is used

### ISSUE THREAD

**Issue by urso** [elastic/beats#2198]
Print TLS information in outputs if TLS is enabled (server/client auth, some certificate information) for users to validate TLS is actually being used.

**Comment by racevedoo** [comment]
Is this still relevant? Can you provide more details? I'd like to start contributing :D

**Comment by urso** [comment]
Idea is to log some information when [TLS is configured](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html). First on init, but also after a connection has been established.

On init (or per connection attempt) we should log that TLS is enable, the verification, and client_authentication mode. 

After a successful connection attempt we should log some information from the [connections state](https://godoc.org/crypto/tls#ConnectionState). For example TLS version in use, HandshakeComplete, DidResume, name of the CipherSuite. In debug mode we might also log [certificate details](https://godoc.org/crypto/x509#Certificate) from the certificate chain.
