### ISSUE TITLE
Agent assumes /usr/local/bin exists on macOS when installing

### ISSUE THREAD

**Issue by ferullo** [elastic/beats#22037]
I installed 7.10.0 BC 2 on fresh macOS 10.15.7 and macOS 11.0 beta 10 machines. From the output below it looks like Agent assumes `/usr/local/bin` always exists on macOS. That final `bin` directory does not exist by default.

```
Dougies-Mac:elastic-agent-7.10.0-darwin-x86_64 dougie$ sudo ./elastic-agent install -f --kibana-url=https://<REDACTED>:443 --enrollment-token=<REDACTED>
The Elastic Agent is currently in BETA and should not be used in production

Error: failed to write shell wrapper (/usr/local/bin/elastic-agent): open /usr/local/bin/elastic-agent: no such file or directory
Dougies-Mac:elastic-agent-7.10.0-darwin-x86_64 dougie$ ls /usr/local/bin
ls: /usr/local/bin: No such file or directory
Dougies-Mac:elastic-agent-7.10.0-darwin-x86_64 dougie$ sudo mkdir /usr/local/bin
Dougies-Mac:elastic-agent-7.10.0-darwin-x86_64 dougie$ sudo ./elastic-agent install -f --kibana-url=https://<REDACTED>:443 --enrollment-token=<REDACTED>
The Elastic Agent is currently in BETA and should not be used in production

2020-10-20T17:10:44.820-0400	DEBUG	kibana/client.go:170	Request method: POST, path: /api/fleet/agents/enroll
Successfully enrolled the Elastic Agent.
Installation was successful and Elastic Agent is running.
Dougies-Mac:elastic-agent-7.10.0-darwin-x86_64 dougie$ ./elastic-agent version
Failed talking to running daemon: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /tmp/elastic-agent-<REDACTED>.sock: connect: no such file or directory"
Daemon: <failed to communicate>
Binary: 7.10.0 (build: 81dc8921c31cbf7f96447d4b020877380d99ddc1 at 2020-10-15 05:46:10 +0000 UTC)
Dougies-Mac:elastic-agent-7.10.0-darwin-x86_64 dougie$

**Comment by EricDavisX** [comment]
Excellent find Dan - @ph do we know if everything is ok on Linux and Windows installs or do we want to rush some 'new os install' tests?

**Comment by ph** [comment]
I've double-checked on Linux, the path is the `/usr/bin` on windows we do not have a shell wrapper so its not an issue.

Concerning macOS, @EricDavisX Do the macOS VM used have homebrew installed? I believe this could explain why it worked.

**Comment by EricDavisX** [comment]
Thanks.  @ph I can confirm on 2 VMs and my personal work mac (That I test on) homebrew is installed.  I don't have concrete info on the state management of the vm templates used for our macOS testing - it has been years since I have considered it.  It is likely one of several updates done to facilitate general 'sensor' or Endpoint testing, including the installation of the 'Leia' modules to trigger various events, and specific users to facilitate access.  I verified this on a sample of our configs: Mojave and High Sierra vms.

**Comment by ph** [comment]
After discussing with @blakerouse we cannot just change the installation path from `/usr/local/bin` to `/usr/bin` because of SIP restriction. The best we can do is to ensure that the `/usr/local/bin` is created and install the shim there.

```
blake@Blakes-MacBook-Pro beats % sudo echo "/bin/bash" > /usr/bin/test
zsh: operation not permitted: /usr/bin/test
```

**Comment by ph** [comment]
For more details https://support.apple.com/en-us/HT204899
