### ISSUE TITLE
Add pod-ip support for add_kubernetes_metadata

### ISSUE THREAD

**Issue by majian159** [elastic/beats#22043]
**Describe the enhancement:**
add pod `status.podIP` and `status.podIPs`.
**Describe a specific use case for the enhancement or feature:**

**Comment by zgfh** [comment]
v7.13.3 is added
PR: https://github.com/elastic/beats/pull/25037

**Comment by ChrsMark** [comment]
Closing this issue since it was implemented at  https://github.com/elastic/beats/pull/25037
