### ISSUE TITLE
Metricbeat PostgreSQL Dashboard creates significant load and long running queries

### ISSUE THREAD

**Issue by ckauf** [elastic/beats#22085]
- Version: 7.9.1 on ECE 2.6.2
- Operating System: CentOS 7
- Steps to Reproduce: Open Metricbeat PostgreSQL dashboard.

Opening the Metricbeat PostgreSQL dashboard for longer time spans (e.g. 7 days) creates significant CPU usage. Specifying an additional filter (`event.module: postgresql`) on the dashboard level reduces the loading time from minutes to seconds. This effect is also visible after waiting some time and manually clearing the caches.

First try opening the dashboard ~13:13 without the filter and second try ~13:16 with the filter:

Hot node monitoring:
![hot_node](https://user-images.githubusercontent.com/12035877/96865538-62b43c00-146a-11eb-8032-be931528635a.PNG)
Warm Node monitoring:
![warm_node](https://user-images.githubusercontent.com/12035877/96865561-6b0c7700-146a-11eb-9413-846352377cec.PNG)

**Comment by sorantis** [comment]
@sayden is this related to or a regression after https://github.com/elastic/beats/issues/20321?

**Comment by jsoriano** [comment]
> Specifying an additional filter (`event.module: postgresql`) on the dashboard level reduces the loading time from minutes to seconds.

If this is helpful in this case, I think this kind of filters could be helpful in the dashboards of many other modules. We might consider adding filters like these ones to all dashboards.

With agent/fleet and data streams we could even query directly to `logs-postgresql.*` in postgresql dashboards. @ruflin do you know if this is something we are already doing or considering to do?

> @sayden is this related to or a regression after #20321?

I don't think this is related to this issue, #20321 is about the contents of a filebeat dashboard, not its performance.

**Comment by jsoriano** [comment]
> TBH I'm surprised we don't have this kind of filter already in the dashboards. I think in most cases we should filter by `event.module` and `event.dataset` to reduce the amount of data.

I have checked now and this is actually done in several dashboards, but not in many of them.

I think it may worth to add it to the ones missing it, even if it is solved in agent with the use of data streams.

**Comment by jsoriano** [comment]
Adding filters in PostgreSQL dashboards in https://github.com/elastic/beats/pull/24607.
