### ISSUE TITLE
Error 'Failed to install service' is displayed during install command when upgrading .rpm 7.9 Agent usage to 7.10.0 linux tar.gz install

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#22090]
**Kibana version:**
Kibana: 7.10.0 Kibana BC2 cloud environment

**Elasticsearch version:**
Elasticsearch: 7.10.0 Kibana BC2 cloud environment

**Host OS and Browser version:**
Windows , All

**Original install method (e.g. download page, yum, from source, etc.):**
Upgraded 7.10.0 Kibana BC2 environment

**Description**
Error Failed to install service is displayed on install with linux tar.gz file on upgarded 7.10.0 BC2 environment

**Preconditions**
1. Test Case Id https://elastic.testrail.io/index.php?/cases/view/22506 need to be executed.
2. Login into the above Kibana environment with 'elastic' superuser.
3. Endpoint integration should be added in Default Policy
4. 7.9 Linux .rpm enroll-deploy on 7.9.2 BC2 Kibana
https://staging.elastic.co/7.9.2-9a979774/summary-7.9.2.html
https://staging.elastic.co/7.10.0-174bd372/summary-7.10.0.html

**Steps to Reproduce**
1. Upgrade the environment to 7.10.0 BC2
2. systemctl to stop Agent / Endpoint.
3. uninstall the rpm
4. download the 7.10.0 BC2 Linux .tar.gz and use the 'install' command 
5. Observe that failed to install service is displayed.

**Test data**
N/A

**Impacted Test case id**
https://elastic.testrail.io/index.php?/cases/view/34908

**Actual Result**
Error Failed to install service is displayed on install with linux tar.gz file on upgarded 7.10.0 BC2 environment

**Expected Result**
User should be able to install agent with linux tar.gz file on upgarded 7.10.0 BC2 environment

**What's working**
 - N/A

**What's not working**
 - N/A
 
**Screenshot**
![fail](https://user-images.githubusercontent.com/59917944/96877566-732edb80-1497-11eb-8639-ac2bddb253a2.jpg)

**Logs**
N/A

**Comment by rahulgupta-qasource** [comment]
@vipulsrivastava-qasource Please review the bug

**Comment by vipulsrivastava-qasource** [comment]
Reviewed and Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
I would feel better about us releasing 7.10 with this if we had a work-around.  I presume we can give the user a command to 'sudo rm -drf /specific/Agent/directories' and it will wipe out and the install will proceed ok.  Its not optimal, but it is also only if an .rpm install user chooses to switch over to .tar.gz usage - which is a selection of users out of the selection of users who use .rpm (tho .tar.gz is the preferred usage)

**Comment by blakerouse** [comment]
Please provide the command you used to uninstall the RPM, so we can reproduce the same path.

**Comment by EricDavisX** [comment]
@rahulgupta-qasource when you are on, can you post back pls

**Comment by rahulgupta-qasource** [comment]
Hi @blakerouse / @EricDavisX 

I ran the following command to uninstall the above 7.9.2 elastic-agent rpm(as per [uninstall rpm package link](https://www.howtoforge.com/community/threads/how-do-i-uninstall-rpm-packages.8/)):-

```
sudo rpm -e <package name>
i.e sudo rpm -e elastic-agent-7.9.2-1.x86_64
```

Screenshot:
![uninstall_rpm](https://user-images.githubusercontent.com/59917944/97144936-5d693100-178b-11eb-871b-22fddee39bf6.jpg)


Please let us know if anything is missing from our end.

**Comment by blakerouse** [comment]
That warning is expected and what you want RPM uninstall to do. Being that `elastic-agent.yml` is updated from installation RPM will save it on uninstall.

I am unable to reproduce this, but I used `yum remove elastic-agent` which is the recommend way from the distro on how to remove an RPM installed package.

**Comment by rahulgupta-qasource** [comment]
Hi @blakerouse

Thank you for sharing the feedback.

We have validated the ticket with above 'yum remove elastic-agent' command after upgrade from 7.9.3 BC1 Kibana cloud to 7.10 BC3 Kibana cloud environment and found it **fixed**.

**Build Details:**
Kibana Cloud : 7.10.0 BC3 build
Commit : ed66f41a8a60ad03426beff65ed270a743c46ac4
Build : 35817
Elastic-Agent Hash : aea04452


Steps followed:
1. Login into the above Kibana environment with 'elastic' superuser.
2. Add Endpoint integration in Default Policy
3. 7.9.3 Linux .rpm enroll-deploy on 7.9.3 BC1 Kibana
4. Upgrade the environment to 7.10.0 BC2
5. systemctl to stop Agent / Endpoint.
6. Uninstall the rpm using 'yum remove elastic-agent' command.
7. Download, extract the 7.10.0 BC3 Linux .tar.gz and use the 'install' command with Default policy.
8. Navigate to Agents tab->Hosts 

Observation:
7.10 Elastic-agent is in Online status with running activity logs.
Screenshot:
![image](https://user-images.githubusercontent.com/59917944/97300790-ec09ab00-187c-11eb-99a2-c60a608e9a55.png)


![image](https://user-images.githubusercontent.com/59917944/97300805-ef9d3200-187c-11eb-8559-f4fea334f142.png)

Hence, we are closing the bug.

**Comment by rahulgupta-qasource** [comment]
**Bug Conversion:**

Testcase already exists for this ticket.
https://elastic.testrail.io/index.php?/cases/view/34908
