### ISSUE TITLE
Functionbeat/Filebeat do not update document with existing ID

### ISSUE THREAD

**Issue by amitaiporat** [elastic/beats#22167]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.
processor config in functionbeat.yml:
    processors:                                                                         
      - decode_json_fields:                                                             
          fields: ["message"]                                                           
          process_array: true.                                                          
          max_depth: 1                                                                  
          target: ""                                                                    
          overwrite_keys: true

For confirmed bugs, please report:
- Version: 7.9.2
- Operating System: N/A
- Discuss Forum URL: [https://discuss.elastic.co/t/functionbeat-does-not-update-documents-with-existing-id/252901](https://discuss.elastic.co/t/functionbeat-does-not-update-documents-with-existing-id/252901)

- Steps to Reproduce: 
On Functionbeat can isolate the behavior with the below steps:

Write message to aws sqs queue i.e.
aws sqs send-message --queue-url <queue_url> --message-body '{
"val": "foo",
}' --message-group-id f1 --message-deduplication-id 1
Doc is successfully written to ES, with _id: <doc_id>.

Take the ID from the created message above, and write the message to queue again with updated values and pass in the _id.
aws sqs send-message --queue-url <queue_url> --message-body '{
"val": "bar",
"_id": <doc_id>
}' --message-group-id f1 --message-deduplication-id 2
When I do this I do not see the document being updated or rewritten at all.

The same result can be achieved for filebeat. 

cc @kvch @ycombinator

**Comment by ycombinator** [comment]
Hi @amitaiporat, we only use GitHub issues for **confirmed** bugs. For questions and troubleshooting, we use Discuss. Since you have already posted your question there and we are engaging, there is no need to also create a GitHub issue with the same contents here. So I'm going to close this issue now. Let's continue the discussion on Discuss. If the discussion confirms that we have a bug or need an enhancement, we can reopen this issue at that time.

**Comment by ycombinator** [comment]
Apologies for closing this issue, I just caught up on the Slack conversation about it. Sounds like @kvch believes this to be a bug. Reopening...

**Comment by kvch** [comment]
@amitaiporat I have discussed this issue with the team. It has been pointed out to me that Beats does not send events to Elasticsearch if the ID already exists. It is a form of deduplication. So this is not a bug, but a feature.

**Comment by amitaiporat** [comment]
@kvch thank you for following up here. So is the only way to do this via logstash? I do see preliminary documentation for fingerprint processor in filebeat here: https://www.elastic.co/guide/en/beats/filebeat/master/fingerprint.html does this mean the behavior will be changing? cc @ycombinator

**Comment by tong-bluehill** [comment]
+1. We do need to overwrite existing data with same id. This should be configurable as overwrite: true/false in functionbeat/filebeat.
