### ISSUE TITLE
Document that Npcap has been officially supported

### ISSUE THREAD

**Issue by hsluoyz** [elastic/beats#2221]
There's a problem in the docs:
https://github.com/elastic/docs/blob/master/html/en/beats/packetbeat/master/packetbeat-loopback-interface.html#L519

I'm the author of [Npcap](https://github.com/nmap/npcap).

I'm glad to inform you that Nmap has **officially** supported Npcap now. The latest Nmap installer has also integrated Npcap. So you can rephrase the wording when you have time:)

**Comment by ruflin** [comment]
@hsluoyz Thanks for brining this up. We will update the docs. Also feel free to open a PR if you find the time.
