### ISSUE TITLE
[Elastic Agents] Send agents logs directly to ES

### ISSUE THREAD

**Issue by nchaulet** [elastic/beats#22243]
## Description 

Once defined here https://github.com/elastic/integrations/issues/350 Elastic agents should send it's logs (previously agent events) directly to the default output instead of sending them through Kibana during the checkin

**Comment by ph** [comment]
@michalpristas Can you add acceptance criteria before starting this issue?

**Comment by nchaulet** [comment]
This is resolved @michalpristas which PR resolved that?

**Comment by ph** [comment]
I think this is resolved.
