### ISSUE TITLE
[winlogbeat][6.8] integration-tests-environment goal does not work

### ISSUE THREAD

**Issue by v1v** [elastic/beats#22265]
### What

`RACE_DETECTOR=1 make -C winlogbeat check testsuite` fails

### Stacktrace

```
00:40:42 TESTING_ENVIRONMENT=snapshot ES_BEATS=.. docker-compose -p winlogbeat5cab1521847a6768eb19c386ce62f75ab8e7facc  -f docker-compose.yml down -v
00:40:43 .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose.yml'
00:40:43 make: [stop-environment] Error 1 (ignored)
00:40:43 ../libbeat/scripts/Makefile:400: recipe for target 'stop-environment' failed
```

![image](https://user-images.githubusercontent.com/2871786/97589246-344bd900-19f5-11eb-93b4-32b5cd02f3c2.png)

[build](https://beats-ci.elastic.co/job/elastic+beats+6.8+multijob-linux/beat=winlogbeat,label=ubuntu-16/16/console) if the build is gone please refers to the below gist:

- [gist](https://gist.github.com/v1v/c2b930030b5531c883260bc608c077df)

**Comment by andrewkroh** [comment]
The tests for Winlogbeat should not be starting Docker. IIRC it has TEST_ENVIRONMENT=false in its Makefile to prevent the integration tests from starting any containers.
