### ISSUE TITLE
[packetbeat][6.8] integration-tests-environment goal does not work

### ISSUE THREAD

**Issue by v1v** [elastic/beats#22266]
### What

`RACE_DETECTOR=1 make -C packetbeat check testsuite integration-tests-environment` fails

### Stacktrace

```
00:48:32 + make stop-environment
00:48:32 TESTING_ENVIRONMENT=snapshot ES_BEATS=.. docker-compose -p packetbeat5cab1521847a6768eb19c386ce62f75ab8e7facc  -f docker-compose.yml down -v
00:48:33 .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose.yml'
00:48:33 ../libbeat/scripts/Makefile:400: recipe for target 'stop-environment' failed
```

![image](https://user-images.githubusercontent.com/2871786/97589749-d10e7680-19f5-11eb-8904-77f072a87ec2.png)

[build](https://beats-ci.elastic.co/job/elastic+beats+6.8+multijob-linux/beat=winlogbeat,label=ubuntu-16/16/console) if the build is gone please refers to the below gist:

- [gist](https://gist.github.com/v1v/7988d2aa77b85e146a731af1ea790acc)

**Comment by andrewkroh** [comment]
This is similar to the Winlogbeat failure. Packetbeat also has TEST_ENVIRONMENT=false to prevent use of the docker environment. https://github.com/elastic/beats/blob/6.8/packetbeat/Makefile#L4
