### ISSUE TITLE
Windows Agent doesn't uninstall with a lowercase `c:` drive in the path

### ISSUE THREAD

**Issue by ferullo** [elastic/beats#22268]
See the below screenshot. Agent refuses to uninstall if the C drive is in lowercase although Windows filesystems are caseless.

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/56368752/97598154-0195e680-19dd-11eb-8d04-497ce4fee9ec.png">

**Comment by ph** [comment]
I think it's low priority, the comparison to check where you are executing the command is case sensitive, probably always assuming lowercase would fix the case.
