### ISSUE TITLE
Error agent is not upgradeable is displayed on upgrading Linux deb (7.10 to 7.11)

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#22304]
**Kibana version:**
Kibana: 7.11.0 Snapshot cloud environment

**Elasticsearch version:**
Elasticsearch: 7.11.0 Snapshot cloud environment

**Host OS and Browser version:**
Linux deb , All

**Original install method (e.g. download page, yum, from source, etc.):**
7.11 Snapshot cloud environment

**Description**
Error agent is not upgradeable is displayed on upgrading Linux deb 7.10 BC4 agent

**Preconditions**
1. 7.11-snapshot agent cloud should be available.
2. Login into the above Kibana environment(with commit 06278dcdec4e3d34df6b0b617b70e961aa630f15) with 'elastic' superuser.
3. 7.9 BC4 Linux deb Agent should be downloaded and enrolled from below location:
https://staging.elastic.co/7.10.0-c650b297/downloads/beats/elastic-agent/elastic-agent-7.10.0-x86_64.rpm

**Steps to Reproduce**
1. Navigate to Agents tab in Kibana
2. Click on upgrade agent from bulk options
3. Observe that error agent is not upgradeable is displayed.

**Test data**
N/A

**Impacted Test case id**
Upgrade agent testcases

**Actual Result**
Error agent is not upgradeable is displayed on upgrading Linux deb 7.10 BC4 agent

**Expected Result**
Linux deb agent should be upgradeable

**What's working**
 - N/A

**What's not working**
 - N/A
 
**Screenshot**
![agent not upgradeable](https://user-images.githubusercontent.com/59917944/97708849-6afe1e00-1adf-11eb-9948-34a839d36ef7.jpg)
![Full_message_not_upgrade](https://user-images.githubusercontent.com/59917944/97708860-6df90e80-1adf-11eb-8ce5-2a707d00d10a.jpg)

**Logs**
N/A

**Comment by rahulgupta-qasource** [comment]
Reviewed and assigned to @vipulsrivastava-qasource

**Comment by vipulsrivastava-qasource** [comment]
Reviewed and Assigned to @EricDavisX

**Comment by blakerouse** [comment]
This is correct. DEB packages cannot be upgraded from Kibana. I think the issue here is that the Agent should not be able to be even selected to try to perform the upgrade. Which I believe is a Kibana issue.

**Comment by EricDavisX** [comment]
I agree it is not a Beats bug.  It is a good error handling case tho.  This test case shows what we already know that the 'Bulk Action' menu does not introspect the different systems before sending the request to upgrade it.  Note that the requirement for the Agent to be 'installed' via Agent install is documented in the main ticket.

My request for testing content @rahulgupta-qasource is that we should have mixed and matched cases of Agents deployed:
 - Windows BC / GA via Agent 'install'
 - macOS BC / GAvia Agent 'install'
 - linux BC / GAvia Agent 'install'
 - .deb BC / GA via RPM install
 - macOS BC / GA enrolled but not installed (still supported, tho not recommended)
 - Windows Snapshot build via Agent 'install'

then trigger them all by 'bulk action' and they should all upgrade ok, except for 2:  the .rpm and the one that is not installed.

Those 2 should show an error, like you report and remain running and alive on the 7.10 (earlier) version of Agent.  I don't mind really, what the error in the UI so long as the App doesn't crash or degrade, and so long as the error comes back within a minute.

Can you set up that test and help verify?  @blakerouse can you think of any more variation in the hosts or the setup or OS config that we want to attempt as part of the test?  any supported OSes that are 'tricky' in a given way we aren't accounting for yet?  Thanks much.

**Comment by EricDavisX** [comment]
for now I am closing this, we can report any subsequent different than the above error exceptions or other problems separately

**Comment by EricDavisX** [comment]
ah, one additional thought - we should update the test case to explicitly verify that for an .rpm or .deb install, that the right hand side 'actions' menu for single-agent actions has the option greyed out.

**Comment by rahulgupta-qasource** [comment]
Hi @EricDavisX 

Thank you for sharing the feedback.

We have created the below 02 testcases(01 for Linux rpm and 01 for Linux deb) for 'Upgrade Agent' option disabled under right hand side 'Actions' menu on Agents tab:-
https://elastic.testrail.io/index.php?/cases/view/34986
https://elastic.testrail.io/index.php?/cases/view/34987
