### ISSUE TITLE
Investigate which fields can be dropped from `logstash-xpack` events

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#22370]
We have been seeing a few issues with memory consumption in Metricbeat when the `logstash-xpack` module attempts to monitor very large Logstash pipelines (say, ones with a couple hundred vertices or more). 

Each event generated by the `logstash_state` metricset corresponds to a single Logstash pipeline. The `logstash_state.pipeline.representation.graph.vertices` field is an array of vertex objects. Each vertex object looks like this:

```
            {
              "type": "plugin",
              "config_name": "tcp",
              "explicit_id": true,
              "id": "some_id",
              "meta": {
                "source": {
                  "column": 3,
                  "id": "/path/to/pipeline/file.conf",
                  "line": 20,
                  "protocol": "file"
                }
              },
              "plugin_type": "input"
            },
```

For a quick win in reducing memory consumption, we should audit which of these fields are actually being used by the Stack Monitoring UI and only keep those.

**Comment by sgrodzicki** [comment]
@igoristic could you help with that?

**Comment by igoristic** [comment]
@ycombinator This investigation will also include usage of: 
```
pipeline.vertices
pipeline.representation.graph.vertices
```
which I'm assuming also has heavy nested footprint

**Comment by ycombinator** [comment]
Hmm, I don't see those fields in the [`.monitoring-logstash` mappings](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/resources/monitoring-logstash.json). The `nested` fields I _do_ see in the mappings are:

- [`logstash_stats.pipelines`](https://github.com/elastic/elasticsearch/blob/5b143b40bf05e1a13c12bfaf8efb7af70f636379/x-pack/plugin/core/src/main/resources/monitoring-logstash.json#L251-L252)
- [`logstash_stats.pipelines.vertices`](https://github.com/elastic/elasticsearch/blob/5b143b40bf05e1a13c12bfaf8efb7af70f636379/x-pack/plugin/core/src/main/resources/monitoring-logstash.json#L298-L299)
- [`logstash_stats.pipelines.vertices.long_counters`](https://github.com/elastic/elasticsearch/blob/5b143b40bf05e1a13c12bfaf8efb7af70f636379/x-pack/plugin/core/src/main/resources/monitoring-logstash.json#L309-L310)
- [`logstash_stats.pipelines.vertices.double_gauges`](https://github.com/elastic/elasticsearch/blob/5b143b40bf05e1a13c12bfaf8efb7af70f636379/x-pack/plugin/core/src/main/resources/monitoring-logstash.json#L320-L321)

**Comment by igoristic** [comment]
The Stack Monitoring UI is still using the following fields:
```
type
config_name
explicit_id
id
plugin_type
stats
```
To represent the pipeline's details page

However we're only using vertices of `plugin_type`: `input`, `filter`, and `output`. So, if there are any other types they can be safely removed

Also, `meta` field can be safely removed as well

**Comment by igoristic** [comment]
Since, this is only an investigation ticket, I'm going to close this issue (but feel free to re-open)
