### ISSUE TITLE
process.name is truncated when running system module on mac

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#22404]
When working on `system.process` metricset on mac os, I see some of the process names are truncated. For example:
<img width="919" alt="Screen Shot 2020-11-03 at 1 08 40 PM" src="https://user-images.githubusercontent.com/14081635/98035425-b6614680-1dd5-11eb-9da8-c1f692e54f71.png">

- Version: master branch
- Operating System: mac os
- Discuss Forum URL: https://discuss.elastic.co/t/process-name-incomplete/250804

I don't see a limit set in [ECS process field](https://www.elastic.co/guide/en/ecs/current/ecs-process.html) documentation so I suspect the problem might be in [Go sigar](https://github.com/elastic/gosigar). This will need more investigation on different operating systems.

**Comment by fearful-symmetry** [comment]
Digging into this. The C API we're accessing returns data via this struct: https://github.com/apple/darwin-xnu/blob/a449c6a3b8014d9406c2ddbdc81795da24aa7443/bsd/sys/proc_info.h#L63

The name field we're accessing is in this field:

```
char			pbi_comm[MAXCOMLEN];
```

Here, `MAXCOMLEN` is set to `16`: https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/osfmk/mach/resource_monitors.h#L66

So this appears to be a limitation of the OS API we're using.

There's ` pbi_name`, but the code implies that it could be empty:
```
char			pbi_name[2*MAXCOMLEN];	/* empty if no name is registered */
```

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
