### ISSUE TITLE
improve logging by log separation for better troubleshooting purposes

### ISSUE THREAD

**Issue by 111andre111** [elastic/beats#22414]
**Describe the enhancement:**
I would like to have a better segregated logging in filebeat, metricbeat,... per module/input/output

**Describe a specific use case for the enhancement or feature:**
Sometimes it happens that we have more complex filebeat configuration files with lots of enabled inputs and lots of enabled modules it can sometimes get very tricky even with enabled DEBUG logging to turn down certain issues where they are really located when it comes to logical configuration issues

Looking away to logstash there are really helpful tools for troubleshooting this.
1. Since if I recall correctly 7.4 we always have a prefix in the logstash logs, that always log as well the pipeline where a certain event was happening.
2. You additionally have the possibility to segregate the logs per pipeline using setting `pipeline.separate_logs`
https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html

Now having this said, can't we have a similar functionality in the beats logs, that tell when something happened in an input/output/processor/module which one really was it?
Can we separate these log files per input/output/module as well. I think that should help for such issues to take the burden a little bit away from troubleshooting knowing exactly where certain things are happening?

**Comment by andresrc** [comment]
Related: https://github.com/elastic/beats/issues/15699

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
