### ISSUE TITLE
Allow Filebeat to read from pipes

### ISSUE THREAD

**Issue by dooblem** [elastic/beats#2242]
This can be considered as an enhancement.

When Filebeat is trying reading from a fifo file:
`Aug 11 12:31:23 XXXXXXXXXXXXXXX /usr/bin/filebeat[20879]: log.go:103: Stop Harvesting. Unexpected file opening error: Given file is not a regular file`

Old issue from Logstash Forwarder, and steps to reproduce, here:
https://github.com/elastic/logstash-forwarder/issues/525

Thanks in advance,
Marc

**Comment by ruflin** [comment]
It seems like this would require a new `input_type`?

**Comment by dooblem** [comment]
Maybe. Basically a pipe can be read like a log file, but no offset should be recorded in the registry I think.
You may forget this issue, as I seem to be the only one to need this. And this is to work around that:
https://discuss.elastic.co/t/can-filebeat-watch-for-new-files-created-in-a-directory/57811/1

**Comment by dooblem** [comment]
Here: https://github.com/elastic/beats/issues/2246

**Comment by apelsina** [comment]
>I seem to be the only one to need this.
I need this, too.

**Comment by hezor** [comment]
Yes, I would find this handy too.

**Comment by meerkampj** [comment]
Could this be used to grab Journald logs ? 

Like : 
Journald :
ForwardToConsole=yes
TTYPath=/dev/console

Filebeat : 
filebeat.prospectors:
- input_type: fifo
  paths:
    - /dev/console

**Comment by vacri** [comment]
This would solve a problem of mine as well.

**Comment by ruflin** [comment]
I'm currently finally refactoring the prospector part which will allow additional prospectors. This is good news for this feature request above as it should make it much easier to add (potentially). If someone is interested to contribute it, ping me here in about 1-2 weeks from now and I can point to the code parts which must be touched.

**Comment by ledav-net** [comment]
I would be interested in such feature too... Had some progress done already for this ?

**Comment by ruflin** [comment]
Progress has been made on the refactoring and the prospectors / input or now properly separated: https://github.com/elastic/beats/tree/master/filebeat/input On the implementation of the feature itself nothing has happened but the above change should make a contribution much eaiser.

**Comment by ledav-net** [comment]
Good to kniw, thanks for your answer :-)

**Comment by yalok** [comment]
Need this feature as well.

**Comment by gaetanquentin** [comment]
readding from pipe could be a solution for filebeat not reading compressed files (.gz).
