### ISSUE TITLE
[Filebeat][Gsuite] Create default dashboard

### ISSUE THREAD

**Issue by marc-gr** [elastic/beats#22441]
**Describe the enhancement:**

Now that Gsuite is been out for a while, would be nice to provide a default dashboard for it.

**Comment by jamiehynds** [comment]
Given the diversity of data collected from G Suite, I think we'd need to consider multiple dashboards. Some ideas: 

**G Suite Audit:** logon failures, logon failure, successful/failed logon by country (maybe include a map), top event categories, suspicious logins blocked by user, most recent authorised applications

**User Accounts:** recent password changes, 2FA enrollment and disable by user, account recovery changes by type (email, phone, secret) and by user 

**G Drive**: top event types (file/folder create, delete, etc), top doc types, top users (based on no. of events), top 10 users by storage used, top users by downloads. 

**Groups:** ACL changes, Top Group Changes, Recent user added to group, recent user removed from group.
