### ISSUE TITLE
Application name is not displayed in activity logs on upgrading the agent 

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#22442]
**Kibana version:**
Kibana: 7.11.0 Snapshot cloud environment

**Elasticsearch version:**
Elasticsearch: 7.11.0 Snapshot cloud environment

**Host OS and Browser version:**
Windows 10 x64 , All

**Original install method (e.g. download page, yum, from source, etc.):**
7.11 Snapshot cloud environment from https://staging.found.no

**Description**
Application name is not displayed in activity logs on upgrading the agent 

**Preconditions**
1. 7.11-snapshot Kibana cloud(with commit 233a3e3a4afc4f3e40a03280b11fab054ee35602) should be available.
2. Login into the above Kibana environment with 'elastic' superuser.
3. 7.10-snapshot windows Agent should be downloaded and installed from below location:
https://snapshots.elastic.co/7.10.0-0453fe0b/downloads/beats/elastic-agent/elastic-agent-7.10.0-SNAPSHOT-windows-x86_64.zip

**Steps to Reproduce**
1. Navigate to Agents tab in Kibana
2. Select the prerequisite endpoint and click on upgrade agent from bulk options
3. Observe that 'Upgrading agent' success toast is displayed. 
4. Wait for some time for agent to upgrade.
5. Once agent upgrade is successful, navigate to activity logs.
6. Observe that Application name is not displayed for one of the application.

**Test data**
N/A

**Impacted Test case id**
N/A

**Actual Result**
Application name is not displayed in activity logs on upgrading the agent 

**Expected Result**
Application name should be displayed in activity logs on upgrading the agent 

**What's working**
 - Application name is displayed for other applications like filebeat, metricbeat.

**What's not working**
 - N/A
 
**Screenshot**
![bug](https://user-images.githubusercontent.com/59917944/98249388-30dbc300-1f9c-11eb-91ce-343497421758.jpg)

**Logs**
N/A

**Comment by rahulgupta-qasource** [comment]
@vipulsrivastava-qasource Please review the bug

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
I saw this prior and mentioned it to the team, I don't know if we had another ticket logged - but I'm glad this is in and we can review if we want to do it for 7.11 cycle.  It isn't urgent as I see it.

**Comment by ph** [comment]
I think there is some misleading information here. 

The **upgrade action is at the agent level**, when you upgrade the agent you actually upgrade everything. But Yes, I think we are missing an appropriate logging statement here.

**Comment by EricDavisX** [comment]
@rahulgupta-qasource with the new Agent logs feature in, I think we can close this, it is not urgent enough to fix in 7.10.X and is not seen as the statements in 7.11 / 8.0 are vastly different when reviewing the actual logs.  If you would review and please close if you agree it is not the same use case any more?

**Comment by rahulgupta-qasource** [comment]
Hi @EricDavisX 

I agree with you. It is not the same use case any more with new Agent logs feature in.

Hence, closing the ticket.
