### ISSUE TITLE
Too many logs printout about kafka retry logs

### ISSUE THREAD

**Issue by drakejin** [elastic/beats#22459]
**Describe the enhancement:**
It's very annoying when I configuration filebeat setting for kafka.
When It failed to connect with kafka, It's printout too many logs. in my terminal, and my terminal was exploded.
So, I can't debug about filebeat. It really makes me annoying.

When it run on server environment, It'll expensive log cost.

``` go
// https://github.com/elastic/beats/blob/master/libbeat/publisher/pipeline/retry.go#L219
func (r *retryer) checkConsumerBlock(numOutputs, numBatches int) bool {
	consumerBlocked := blockConsumer(numOutputs, numBatches)
	if r.consumer == nil {
		return consumerBlocked
	}

	if consumerBlocked {
		r.logger.Info("retryer: send wait signal to consumer") // remove or down the log level to `trace`
		if r.consumer != nil {
			r.consumer.sigWait()
		}
		r.logger.Info("  done")
	} else {
		r.logger.Info("retryer: send unwait signal to consumer") // remove or down the log level to `trace`
		if r.consumer != nil {
			r.consumer.sigUnWait()
		}
		r.logger.Info("  done")
	}

	return consumerBlocked
}
```

I recommend erasing the logging codes or printing out at least one time.

**Comment by faec** [comment]
Thanks for reporting! It looks like this is probably the same as another recently filed issue: https://github.com/elastic/beats/issues/22437
