### ISSUE TITLE
Make Filebeat timestamp processor able to handle underscores

### ISSUE THREAD

**Issue by zoulja** [elastic/beats#22478]
Currently Filebeat [timestamp processor](https://www.elastic.co/guide/en/beats/filebeat/master/processor-timestamp.html#processor-timestamp) follows Golang spec limitations and can't parse timestamp which contains underscores.
**Example**: `2020/11/06_18:17:25_455`

I get access logs in such format and can't change it.
Could you please add some option to handle such situation?
Probably use some more advanced timestamp formatting/parsing engine(Go's seems too limited and not user-friendly) or add some new escaping parameter?

**Comment by andresrc** [comment]
We would recommend doing the parsing in the ingest node. Thanks!

**Comment by zoulja** [comment]
Parsing in the ingest node would be a disrespect to timestamp processor's developer.
I want to believe a man with all software development achievements in his hands can beat the underscore. Some day.

**Comment by andresrc** [comment]
And with all due respect to the timestamp processor's developer, we recommend doing the processing in the ingest node. Thanks.
