### ISSUE TITLE
Consider copying kubernetes.node.hostname to host.name

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#22519]
Follow up of https://github.com/elastic/beats/pull/22189#discussion_r518018179

We need to evaluate if `kubernetes.node.hostname` added at https://github.com/elastic/beats/pull/22189 can be copied at `host.name`. Some testing need to take place in that case to verify that what is added is expected in that case as well what will happen if `add_host_metadata` is enabled at the same time.

Related to https://github.com/elastic/integrations-dev/issues/385, https://github.com/elastic/beats/issues/20434

cc: @jsoriano @kaiyan-sheng @exekias

**Comment by ChrsMark** [comment]
@jsoriano After reading https://github.com/elastic/beats/issues/20434 again and running Metricbeat on GKE to test it I see the following:
![Screenshot 2022-02-22 at 10 42 04 AM](https://user-images.githubusercontent.com/11754898/155116121-47e40e46-abdc-405f-ba22-2c1f023cf3be.png)


It seems that `kubernetes.node.name` and `host.name` is the same while the `kubernetes.node.hostname` is actually different. 

I guess that the main point of https://github.com/elastic/beats/issues/20434 was to suggest using `kubernetes.node.hostname` in place of `host.name` (copy) as a more representative value, right? Just want to verify if this theory align with what we see in this example above?

**Comment by jsoriano** [comment]
Let's close this by now as it doesn't seem to be causing specific problems now, we can reopen later if we find specific use cases that need improvements.

**Comment by ChrsMark** [comment]
A note about ECS compatibility:

```
In this case, we can place the FQDN into host.name and use host.hostname for the value returned by hostname on the system (or returned from API).
Idea being that host.hostname represents what the server defines itself as but host.name is more of an accurate identity decided by the implementor. host.name is meant to only hold one value.
```

Leaving it here as reference for the future but we will need it to validate it again.
