### ISSUE TITLE
Flaky test: auditbeat/module/file_integrity.TestActions

### ISSUE THREAD

**Issue by urso** [elastic/beats#22518]
## Flaky Test

* **Test Name:** auditbeat/module/file_integrity.TestActions
* **Link:** https://github.com/elastic/beats/blob/master/auditbeat/module/file_integrity/metricset_test.go#L162
* **Branch:** master
* **Notes:** Windows 2019

### Stack Trace

```
[2020-11-06T16:32:58.457Z] FAILURES:

[2020-11-06T16:32:58.457Z] Package: github.com/elastic/beats/v7/auditbeat/module/file_integrity

[2020-11-06T16:32:58.457Z] Test:    TestActions

[2020-11-06T16:32:58.457Z]     metricset_test.go:162: 

[2020-11-06T16:32:58.457Z]     metricset_test.go:164: 

[2020-11-06T16:32:58.457Z] ----
```

**Comment by ChrsMark** [comment]
This one fails for `macos` too:

## Flaky Test

* **Test Name:** auditbeat/module/file_integrity.TestActions
* **Link:** https://github.com/elastic/beats/blob/master/auditbeat/module/file_integrity/metricset_test.go#L173
* **Branch:** master
* * **Artifact Link:** https://beats-ci.elastic.co/job/Beats/job/beats/job/master/lastFailedBuild/testReport/junit/github/com_elastic_beats_v7_auditbeat_module_file_integrity/Build_Test___auditbeat_macos_macosx___TestActions/
* **Notes:** macosx

### Stack Trace

```
=== RUN   TestActions
    metricset_test.go:173: 
        	Error Trace:	metricset_test.go:173
        	Error:      	[]string{"created", "updated"} does not contain "attributes_modified"
        	Test:       	TestActions
--- FAIL: TestActions (0.13s)
```

**Comment by ChrsMark** [comment]
Closed via https://github.com/elastic/beats/pull/23966
