### ISSUE TITLE
High cpu usage when running iis/application_pool metricset with a high number of websites/app pools

### ISSUE THREAD

**Issue by narph** [elastic/beats#22522]
Retrieving counter values for each of the worker processes can generate a high number of cgo calls which seem to to be the cause of high CPU usage.
CGO is a must on Windows, as all OS functionality is available via dlls only.
Paths to investigate:
- reducing the current number of calls (caching, re-adding counter paths)
- re-implementing the retrieval of performance counters, trying to retrieve the counters values using the wildcard path.
- looking into other solutions besides the PDH dll.

**Comment by masci** [comment]
Can we add benchmarking within the scope of this task? Whatever solution we come up with, we should be able to provide a rough estimation of the expected CPU/mem usage depending on the size of the application pool.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
