### ISSUE TITLE
`logstash/node` metricset for Stack Monitoring should deduplicate events before publishing

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#22535]
Currently, when the `logstash` module is enabled with `xpack.enabled: true` set (or alternatively when the `logstash-xpack` module is enabled), the `node` metricset produces events and sets their `@metadata._id` field.

https://github.com/elastic/beats/blob/120f9319cd28f54cdbd7e636a49d467645a3865e/metricbeat/module/logstash/node/data_xpack.go#L56

The idea behind this is that the `@metadata._id` field gets mapped to the `_id` field when publishing events to Elasticsearch. Consequently, Elasticsearch overwrites documents with the same `_id`, essentially performing deduplication.

While this is great because it saves having too many `type: logstash_state` documents in Elasticsearch, it doesn't help with memory usage and wire size between the `node` metricset producing events and the events being stored as documents in Elasticsearch. This is especially impactful (in a negative way) when large Logstash pipelines are being monitored by the `logstash-xpack` module.

A fix to this would be to track already seen event IDs in the `node` metricset itself using a `StringSet`. This data structure should persist across mutiple `Fetch` calls.  Using this data structure, the metricset should:
* not publish events for known IDs, i.e. those already in the data structure,
* publish events with unknown IDs and add to the data structure, and
* remove IDs from the data structure if the ID is not "seen" in the last query.

Logstash pipelines rarely change their configuration, particularly in production environments. As a result, the impact of this change would be a saving in memory within Metricbeat and also in how many duplicate events are sent to Elasticsearch over the wire.

**Comment by faec** [comment]
This is probably not too hard of a fix, but other issues took precedence and it never made it into a release cycle; not sure at this point how important it is since other related memory fixes have been implemented in the meantime. Unassigning so this can be re-triaged.
