### ISSUE TITLE
[Fleet] Test & automation support for 'upgrade' from the Agent CLI

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#22530]
[Fleet] I initially logged this a a bug and come to find it is working as expected, but we can use it to review and finish out tests for the 'upgrade' feature from the Agent CLI

cli output looks like this:
  upgrade     Upgrade the currently running Elastic Agent to the specified version

For confirmed bugs, please report:
- Version: 7.10

the questions:
- [ ] is 'upgrade' the correct usage, or does it need additional params added?
- [ ] do we have unit and/or api tests for this?
- [ ] do we have and do we need any e2e-testing coverage for this for stand-alone agent (we have a separate ticket for fleet-mode Agent upgrade passed in via the Kibana API

We can work the above and edit this in line if desired, or log separate tickets in different repos

**Comment by EricDavisX** [comment]
actually - I'll need to ping the team and trace this backwards... maybe we did want to support it, but perhaps only for stand-alone agent mode?  I see this commit:
https://github.com/elastic/beats/commit/c858dd0f3188793ffd52d8975c8120ce0f442ff8
 - which references that.  

@ph @blakerouse is it good as is?  we can close this if so.  do we need any manual coverage over this or anything in e2e-testing?

**Comment by EricDavisX** [comment]
i updated the issue and changed it to a feature tracking / test automation work issue.  @rahulgupta-qasource we can wait for info and sync up from Blake and Michal and then figure out what we want to add for manual test coverage.

**Comment by rahulgupta-qasource** [comment]
Hi Eric

We have created and executed the test cases for stand-alone agent upgrade through CLI under https://github.com/elastic/beats/pull/22510 ticket.

Please let us know if any other scenario needs to be validated.

**Comment by ph** [comment]
assigning @michalpristas for the question, I think we should have e2e test for this, I believe Michal correct me If I am wrong but that would could be done at the same time of the e2e you are currently working on.

**Comment by EricDavisX** [comment]
Good question.  Yes, I think relevant, with some commentary:

We have an Agent upgrade test in e2e-testing repo that uses the Kibana API to trigger the upgrade, as most usage will.  I expect that the test would fail if anything on the Agent side failed, so it probably covers this case ok.  

If we agree on that, then it just becomes a matter of documenting the option correctly in the Agent side and in on-line Docs if desired there as well.  
@jlind23

**Comment by jlind23** [comment]
I do agree but i am not the most knowledgeable on this. @ruflin do we assume that if the upgrade fails Kibana call will also fail?

For the on-line docs, who should take care of it? Is it part of your area @dedemorton?

**Comment by dedemorton** [comment]
@jlind23 From scanning this issue, it's not clear to me what needs to be added to the documentation. To get this work on our radar, please [open an issue in the observability-docs repo](https://github.com/elastic/observability-docs/issues/new/choose) and describe what needs to be added/changed in the docs. Depending on what's required, either an obs-docs writer or someone on the development team will handle the change.

**Comment by jlind23** [comment]
@EricDavisX upgrade is documented here and it is explicitly defined for standalone agent.
https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html#elastic-agent-upgrade-command

Tests are green.
So, afaik we can close this issue. What do you think?

**Comment by ruflin** [comment]
AFAIK the Kibana call only triggers the upgrade. The question is if the tests then wait to see if the upgrade was successful. If yes, I think we can close this issue.

Side note: It would be nice (if possible) if we could upgrade tests for various versions as some issues like upgrading 7.13 to 7.15 broke things etc. We would need to define what the matrix is.

**Comment by EricDavisX** [comment]
The test waits to see if it is successfully started, but not much more.  I added the requirement for multiple-versions in a matrix to the existing Fleet Agent upgrade issue - https://github.com/elastic/e2e-testing/issues/53

I am pleased to see the Agent side docs are in, see screenshot below.  Let's close this out.  
<img width="1297" alt="Screen Shot 2021-11-03 at 1 37 07 PM" src="https://user-images.githubusercontent.com/12970373/140162684-05f461e2-e568-46b7-8e41-2ad807e42556.png">
