### ISSUE TITLE
`logstash/node` metricset used for Stack Monitoring is publishing too many events

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#22534]
Consider a Logstash pipeline with three Elasticsearch output plugins, like so:

```
input {
  generator {}
}

output {
  elasticsearch {
    id => es_out_1
    hosts => "localhost:9200"
  }

  elasticsearch {
    id => es_out_2
    hosts => "localhost:9200"
  }

  elasticsearch {
    id => es_out_3
    hosts => "localhost:9210"
  }
}
```

Notice that the first two `elasticsearch` output plugins in the pipeline, `es_out_1` and `es_out_2`, are actually pointing to the same Elasticsearch cluster. But the third `elasticsearch` output plugin, `es_out_3` is pointing to a different Elasticsearch cluster.

When the `logstash` module is enabled with `xpack.enabled: true` (or alternatively when the `logstash-xpack` module is enabled), the `node` metricset will produce **three** events. Two of these events will be identical in every field, except their `timestamp` field may differ by a few milliseconds or even less. The third event will be mostly identical to the first two events, except its `timestamp` field may differ by a few milliseconds or even less and its `cluster_uuid` field will be different too. Further, note that the `@metadata._id` field of all three events will be the same.

In actuality, what the metricset **should** produce in the above setup is **two** events. These events should be identical in every field, except their `timestamp` field may differ by a few milliseconds or even less and their `cluster_uuid` field will be different too.  In other words, there should be an event produced for every unique pipeline (determined by the pipeline's `ephemeral_id` field and every unique Elasticsearch cluster that the pipeline connects to (determined by the `cluster_uuid`s in that pipeline's Elasticsearch output plugins). Further, the `@metadata._id` should be derived from this combination to prevent overwriting of events as documents in Elasticsearch.

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
