### ISSUE TITLE
Can't start auditbeat

### ISSUE THREAD

**Issue by davidgite** [elastic/beats#22548]
I have installed auditbeat (latest version). 

[This is my config file](https://pastebin.com/U7Qr0A36) (I hid the `output.logstash/kibana` part as it's irrelevant and has sensitive data. Also, it doesn't even have audit rules - it didn't work before so I removed it)

When I start auditbeat, this is what I get:

    {"level":"error","timestamp":"2020-11-11T16:17:28.970Z","caller":"instance/beat.go:951","message":"Exiting: 1 error: failed to initialize file event reader: function not implemented"}
    Exiting: 1 error: failed to initialize file event reader: function not implemented

Does anyone happen to know why it's happening?

Thanks ahead.

**Comment by adriansr** [comment]
Issues in this repository are reserved for confirmed bugs.

For unconfirmed bugs or troubleshooting please use https://discuss.elastic.co/c/beats.

I see there's already a topic for this issue, let's continue the discussion in there.

https://discuss.elastic.co/t/cant-start-auditbeat/255097
