### ISSUE TITLE
Support for log file without newline

### ISSUE THREAD

**Issue by jguay** [elastic/beats#22542]
**Describe the enhancement:**
Currently using filebeat, filebeat does not support reading files without any newline character [per doc](https://www.elastic.co/guide/en/beats/filebeat/7.9/newline-character-required-eof.html)

**Describe a specific use case for the enhancement or feature:**
For non-standard applications which create log files which might have a single line without a newline, ability for filebeat to read the unfinished line based on timeout would help.

Currently 2 workaround solutions are : 
1- Change the application to generate standard entries (with newline)
2- Use logstash file input [read mode](https://www.elastic.co/guide/en/logstash/7.9/plugins-inputs-file.html#_read_mode) : 
```
input
{
 file
  {
   path => "/location/of/files/without/newline/*"
   mode => "read"
  }
}
```

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
