### ISSUE TITLE
Elastic Agent writes to the wrong data_stream

### ISSUE THREAD

**Issue by ph** [elastic/beats#22551]
https://github.com/elastic/beats/issues/21862

Based from this comment https://github.com/elastic/beats/pull/22526#issuecomment-725587553

We are writing endpoint's log event to `logs-elastic_agent-endpoint-security-default` but this is problematic because we wont be able to correctly extract the namespace and the dataset.  This would result in the following extraction:

**type:** logs
**datastream:** elastic-agent
**namespace:** security-default

I suggest we use this _data_stream_ instead: `logs-elastic_agent.endpoint_security-default`  this would align with the existing format.

We also have logic in the Agent and Kibana that will reject namespace with a `-`

**Comment by blakerouse** [comment]
My comment was wrong it was `logs-elastic_agent.endpoint-security-default`. So the `endpoint-security` is still problematic. #22554  ensures that no matter the application name it is convert from `-` to `_`.

**Comment by blakerouse** [comment]
@ph This doesn't need to be targeted to 7.10 as the `.` is currently correct. So this only needs to go to 7.x because endpoint logging with be in 7.x+.

**Comment by ph** [comment]
Agree
