### ISSUE TITLE
can output file using every docker's container name?

### ISSUE THREAD

**Issue by lpdswing** [elastic/beats#22563]
my filebeat.yml:
```
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

# filebeat.inputs:
#   - type: log
#     paths:
#       - "/biomind/logs/pm2/*.log"


filebeat.autodiscover:
  providers:
    - type: docker
    # hints.enabled: true
      templates:
        - condition.regexp:
            # docker.container.labels.collectLog: "true"
            docker.container.image: "^biomind.*"
          config:
            - type: log
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  enabled: false
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:elastic}'
  password: '${ELASTICSEARCH_PASSWORD:WQabc123++}'

output.file:
  enabled: true
  path: "/tmp/filebeat"
  codec.format:
    string: '%{[@timestamp]} %{[container.name]} %{[message]}'
```

i want output the filename for example:

nginx.log
redis.log
.........
by container name

can use some config do that?

**Comment by jsoriano** [comment]
Hey @lpdswing,

Not sure of following. When collecting logs from docker there is no filename like `nginx.log` or `redis.log` :thinking: 

Log file is available in the `log.file.path`, for the case of logs collected from docker it is something like `/var/lib/docker/containers/98b42a98e8e0ad5ec7fffdcc720ebe550979b605669997d91a4fdfd87298c7b5/98b42a98e8e0ad5ec7fffdcc720ebe550979b605669997d91a4fdfd87298c7b5-json.log`.

Container name is available in the `container.name` field. If your containers are named `nginx` or `redis`, you will have these names there.

If this doesn't answer your question, could you please open a new topic in https://discuss.elastic.co/? This is a better place for general questions and community support. We keep github for confirmed bugs and enhancement requests, I will close this issue.

Thanks!
