### ISSUE TITLE
Filebeat documentation: volume mount should be added to preserve registry files

### ISSUE THREAD

**Issue by SlavikCA** [elastic/beats#22586]
**Describe the enhancement:**
There is the page, describing how to run Filebeat in the Docker:
https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html

What's missing in the doc is description about mounting path for registry files.

So, this mount should be added:
`/var/lib/filebeat:/usr/share/filebeat/data:rw`  
I think using named volume would be even better solution.

The reason for that, is because currently, when Filebeat container recreated (for example during the upgrade) - it will lose registry, and therefore will lose position of tracked files.
Adding mount for the registry will preserve the position of tracked files, and so will avoid the issue of sending duplicate records.

**Comment by jur3** [comment]
That is still the issue. A lot of users don't know that and resend logs after a container restart.

upvote

**Comment by SlavikCA** [comment]
Issue still exists.

I think it should have major priority.

Please update the docs.

**Comment by kilfoyle** [comment]
@SlavikCA I'm sorry this has been delayed for so long. I'll add something to the docs as soon as possible.

One question: Rather than ask customers to mount `/var/lib/filebeat:/usr/share/filebeat/data:rw` could we maybe be more clear and provide an example mount command? I haven't worked with Filebeat at all so I'm not sure exactly what to add.

**Comment by SlavikCA** [comment]
> could we maybe be more clear and provide an example mount command? 

There is no separate mount command. It's part of the docker command (or part of docker compose file).

There is a section of the document called "Volume-mounted configuration" and has docker command with 3 '--volumes' options. There needs to be 4th '--volume' option in that command:

--volume="registry:/usr/share/filebeat/data:rw"

**Comment by kilfoyle** [comment]
Thanks @SlavikCA. This should be fixed via https://github.com/elastic/beats/pull/37043

The docs will update a little while after the backport PRs are merged. Let me know if anything doesn't look okay.
