### ISSUE TITLE
Filebeat auditd ingest pipeline fails at kv processor when field value contains whitespaces

### ISSUE THREAD

**Issue by simioa** [elastic/beats#22587]
- Version: 7.9.2
- Operating System: RHEL 7.9

Some auditd messages contain a reason field which contains informations on why a specific event was logged. This field can contain whitespaces. This whitespaces are interpreted by the kv ingest processor as a field split which causes the kv processor to fail.

https://github.com/elastic/beats/blob/b6896ee6892da8ce4567d63ee0fa962512fb8701/filebeat/module/auditd/log/ingest/pipeline.yml#L22-L26

- Steps to Reproduce: 

  - Issue the following request against the pipeline simulation api:
```
POST _ingest/pipeline/filebeat-7.9.2-auditd-log-pipeline/_simulate
{
  "docs": [
    {
      "_source": {
        "message": "type=ANOM_ABEND msg=audit(1605431420.026:123): auid=12345 uid=123 gid=123 ses=123456789 pid=1234 comm=\"extproc\" reason=\"memory violation\" sig=6"
      }
    }
  ]
}
```
  - The Ingest pipeline fails because of the "reason" Field with the following error:
```
...
          "error" : {
            "message" : "field [auditd.log.kv] does not contain value_split [=]"
          }
...
```

**Comment by simioa** [comment]
https://github.com/elastic/elasticsearch/issues/31786 looks related.
Using field_split and value_split patterns from https://github.com/elastic/elasticsearch/issues/31786#issuecomment-646174386 seems to work

**Comment by gyterpena** [comment]
it fails because of space in "reason=\"memory violation\""

**Comment by jaijhala** [comment]
I believe this is still an issue. The workaround mentioned [here](https://github.com/elastic/elasticsearch/issues/31786#issuecomment-646174386) does seem to work but would be good to fix this as part of the auditd integration?

**Comment by jamiehynds** [comment]
@efd6 would you mind taking a look at this one when you get a chance? Curious is the workaround mentioned in https://github.com/elastic/elasticsearch/issues/31786#issuecomment-646174386 could be applied to our Auditd pipelines or if the bug within the kb processor needs to be addressed first?

**Comment by efd6** [comment]
@jamiehynds Fixes for the beats pipeline and the integration pipeline have been sent.
