### ISSUE TITLE
Winlogbeat new dashboards

### ISSUE THREAD

**Issue by janniten** [elastic/beats#22580]
**Describe the enhancement:**
I've working in winlogbeat new dashboards in https://github.com/elastic/beats/pull/18775.
Those dashboards present some visual and functional improvements and in addition implement some fixes.
The PR is in _merge_ state but the new dashboards are not coming with the new version of winlogbeat.
Do I have to do something more?
Thank you

**Comment by andresrc** [comment]
It seems the PR was not backported.

**Comment by janniten** [comment]
Hi Andres,
what does "not backported" means? Please let me know if I need to do something more.
Thank you!

**Comment by andrewkroh** [comment]
I've opened a PR to backport the commit in https://github.com/elastic/beats/pull/22598. Sorry about that @janniten.
