### ISSUE TITLE
elastic-agent : fails to enroll (missing authentication credentials)

### ISSUE THREAD

**Issue by TheFausap** [elastic/beats#22615]
Hello all,

I'm testing the enrollment process under Windows 2019.
I downloaded the latest 8.0.0 snapshot (8.0.0-b557611c) of the agent. Elasticsearch node and Kibana runs under Linux, in the same LAN of the agent. I also imported, in Windows, the CA certificate used to create the kibana cert.
I unzipped the file under Program Files, renamed it to Elastic-Agent, then I ran the enrollment command (I didn't modify any yml file in the directory):

`.\elastic-agent.exe install -f --kibana-url=https://10.10.10.14:5601 --enrollment-token=<token>`

I get the following error:

```
2020-11-17T11:31:49.525+0100    DEBUG   kibana/client.go:170    Request method: POST, path: /api/fleet/agents/enroll
Error: fail to enroll: fail to execute request to Kibana: Status code: 401, Kibana returned an error: Unauthorized, message: [security_exception] missing authentication credentials for REST request [/_security/_authenticate], with { header={ WWW-Authenticate={ 0="Basic realm=\"security\" charset=\"UTF-8\"" & 1="Bearer realm=\"security\"" & 2="ApiKey" } } }
Error: enroll command failed with exit code: 1
```
I found a closed bug related to this error, but it was for a Docker environment. 
Is there any specific configuration steps I am missing here?

thanks,
Fausto Saporito

**Comment by TheFausap** [comment]
Hello, I suppose I found the error. 
In this case the error message is correct, because I used a revoked token. 
The problem, by the way, is why a revoked token is shown in the Step 3 (in the Add Agent window).

**Comment by ph** [comment]
Yes, theses token should not be shown in that flyout there is already an issue for it there https://github.com/elastic/kibana/issues/73529

Closing this one.
