### ISSUE TITLE
[CEF] Add TCP support to CEF Module

### ISSUE THREAD

**Issue by jamiehynds** [elastic/beats#22625]
The [CEF module](https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-module-cef.html) only supported the UDP input,  but TCP has been smoke tested without any issues. 

Can we update the module and associated docs to reflect support for TCP? 

- Change udp to tcp in /usr/share/filebeat/module/cef/log/config/input.yml 

<img width="559" alt="Screenshot 2020-11-17 at 14 32 42" src="https://user-images.githubusercontent.com/62879768/99402907-c7d04580-28e1-11eb-9478-941d59e4c4de.png">

**Comment by andrewkroh** [comment]
It's a little more than docs, but not much. The module config needs another conditional to support the tcp protocol.

https://github.com/elastic/beats/blob/8af0424bf411fda474dfcf0c2bacfee433bfe219/x-pack/filebeat/module/cef/log/config/input.yml#L1-L5
