### ISSUE TITLE
Filebeat 7.9.1 HAProxy ingest pipeline failing

### ISSUE THREAD

**Issue by turnUpTheChill** [elastic/beats#22638]
In Filebeat 7.9.1 the ingest pipeline `filebeat-7.9.1-haproxy-log-pipeline` has two issues with a customers HAProxy 2.2 logs. While recreating the issue the following was found. 

1. the top level Grok does not properly parse messages like below
`Nov 11 16:25:17 localhost haproxy[22382]: Connect from 11.70.1.241:21114 to 11.70.2.235:50567 (frontend:/TCP)`

Current Grok: `%{HAPROXY_DATE:haproxy.request_date} %{IPORHOST:haproxy.source} %{PROG:process.name}(?:\[%{POSINT:process.pid:long}\])?: %{GREEDYDATA} %{IPORHOST:source.address}:%{POSINT:source.port:long} %{WORD} %{IPORHOST:destination.ip}:%{POSINT:destination.port:long} \(%{WORD:haproxy.frontend_name}/%{WORD:haproxy.mode}\)`

Working Grok: `%{HAPROXY_DATE:haproxy.request_date} %{IPORHOST:haproxy.source} %{PROG:process.name}(?:\[%{POSINT:process.pid:long}\])?: %{GREEDYDATA} %{IPORHOST:source.address}:%{POSINT:source.port:long} %{WORD} %{IPORHOST:destination.ip}:%{POSINT:destination.port:long} \(%{WORD:haproxy.frontend_name}:/%{WORD:haproxy.mode}\)`

The only change is to add a `:` between the last two Grok patterns.

2. The second date processor has an unsafe check that causes a Null exception. 
```
"error" : {
            "message" : """Cannot invoke \"Object.getClass()\" because \"callArgs[0]\" is null"""
          }
```

Current: `"if": "ctx.event.timezone == null"`
Working: `"if": "ctx?.event?.timezone == null"`

This behavior can be reproduced by running the below commands in any cluster with the aforementioned pipeline loaded. 

```
POST _ingest/pipeline/filebeat-7.9.1-haproxy-log-pipeline/_simulate
{
  "docs": [
    {
      "_source":{
        "message":"""
        Jul 30 09:03:52 localhost haproxy[32450]: 1.2.3.4:38862 [30/Jul/2018:09:03:52.726] incoming~ docs_microservice/docs 0/0/1/0/2 304 168 - - ---- 6/6/0/0/0 0/0 {docs.example.internal||} {|||} "GET /component---src-pages-index-js-4b15624544f97cf0bb8f.js HTTP/1.1"
        """
      }
    }
    ]
}

POST _ingest/pipeline/filebeat-7.9.1-haproxy-log-pipeline/_simulate
{
  "docs": [
    {
      "_source":{
        "message":"Nov 11 16:25:17 localhost haproxy[22382]: Connect from 11.70.1.241:21114 to 11.70.2.235:50567 (frontend:/TCP)"
      }
    }
    ]
}
```

Relevant [PR](https://github.com/elastic/beats/pull/22637) here

**Comment by jsoriano** [comment]
> Current: `"if": "ctx.event.timezone == null"`

This expression should work even if `ctx.event.timezone` is null. This will fail if `ctx.event` is null, what shouldn't happen if filebeat modules are used.

Have you seen this error happening with filebeat or only with the simulate API?

**Comment by turnUpTheChill** [comment]
@jsoriano for the second issue, in my environment I was seeing it when running without the module, only with the pipeline called out. The customer I am working with we saw it with the module, but I will take a closer look to see if the event field is populated properly.

**Comment by jlind23** [comment]
Backlog grooming: Closing for now as it is related to filebeat 7.9.1.
