### ISSUE TITLE
[Filebeat][Netflow] Running Filebeat in container does not set `network.exporter.address` to the network device IP that generated the netflow record

### ISSUE THREAD

**Issue by hendry-lim** [elastic/beats#22678]
For confirmed bugs, please report:
- Version: `7.10.0`
- Steps to Reproduce: 
Deploy Filebeat on Docker
Enable and configure `netflow` module
Configure a network device to send Netflow records to Filebeat over UDP.

We are running Filebeat on Docker. The `netflow.exporter.address` is set to the Docker `bridge` network gateway IP address.
This behaviour is expected as the following function:
```
func (h PacketHeader) ExporterMetadata(source net.Addr) record.Map {
	return record.Map{
		"version":      uint64(h.Version),
		"timestamp":    h.UnixSecs,
		"uptimeMillis": uint64(h.SysUptime),
		"address":      source.String(),
		"sourceId":     uint64(h.SourceID),
	}
}
```

However, this is not the expected behaviour, because in this case the `netflow.exporter.address` is not set to the correct source IP of the network device that generated the Netflow records.
In our case, Filebeat ingested the Netflow records into Elasticsearch with `network.exporter.address` field value set to `172.17.0.1:50743`.

**Comment by andrewkroh** [comment]
The exporter's source address is always obtained from the received UDP packet header. This is always the behavior.

What value are you expecting the exporter address to contain? Is the exporter itself running within the docker network?

**Comment by hendry-lim** [comment]
The exporter is not running within the Docker network, because it is a router. However, for some reason Filebeat captured the exporter's source address as the Docker gateway IP address instead of the actual exporter IP.

**Comment by andrewkroh** [comment]
This appears to be a bug in Docker's `docker-relay`.

- https://github.com/moby/moby/issues/15127
- https://github.com/moby/libnetwork/issues/1729

**Comment by andrewkroh** [comment]
As per https://github.com/moby/libnetwork/pull/2577 as possible workaround for the Docker issue to bind to specific addresses in the port mappings.

> Currently the only workaround is to explicitly bind docker-proxy to each local IP address (e.g. -p 1.1.1.1:1234/1234, -p 1.1.1.2:1234/1234), which is not possible in situations where IPs change (for instance, VPN tunnels coming up and down).

Since this isn't a Filebeat bug I'm going to close this.
