### ISSUE TITLE
Override Default Filebeat Module Pipeline

### ISSUE THREAD

**Issue by PBarnard** [elastic/beats#22679]
I would like the ability to provide a custom Ingest Pipeline to be used by a Module in the filebeat.yml configuration.

In our setup we have a number of metrics and dashboards that use specific cross-service fields and values in the indexed documents. 

When using, for example, the RabbitMq module in Filebeat it creates its own Ingest Pipeline for the logs. I can edit this pipeline to add some extra fields but we're seeing that these Pipelines often get reset to the default. It would be useful to be able to take the default Pipeline definition, edit it to create a custom version then specify that custom version in the configuration.

**Comment by andresrc** [comment]
The recommended approach is to copy the module and make the changes there.

**Comment by PBarnard** [comment]
@andresrc I dont think you understood my question

**Comment by ycombinator** [comment]
@PBarnard Any Filebeat module's `input` settings can be overridden: https://www.elastic.co/guide/en/beats/filebeat/master/advanced-settings.html. One such `input` setting is the ingest pipeline: https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-log.html#_pipeline_10. Does this help with your use case?

**Comment by PBarnard** [comment]
@ycombinator Ahh, looks like the lack of understanding was on my part, that's exactly what I was looking for! Many thanks :)

**Comment by PBarnard** [comment]
@ycombinator will this work with filebeat hints-based autodiscover? So `co.elastic.logs.rabbitmq/module.log.input.pipeline: *pipeline-name*`

**Comment by ycombinator** [comment]
There is no supported hint like the one you're trying to use for overriding the input pipeline. The full list of supported hints is at https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html.

However, you can always use the `co.elastic.logs/raw` "escape hatch" hint: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html#_co_elastic_logsraw.

---

BTW, happy to continue this particular discussion here but, in general, we prefer to reserve GitHub issues for enhancement requests or confirmed bugs. For Q&A type discussions, please post them on https://discuss.elastic.co/c/beats in the future. Thanks!

**Comment by PBarnard** [comment]
Thanks for that @ycombinator I'll have a look at those links.

I take your point re. posting here in a github Issue, I asked a similar question here - https://discuss.elastic.co/t/specify-module-pipeline-in-kubernetes-annotation/256802 - but it's not getting a lot of traction :|
