### ISSUE TITLE
[Filebeat] filebeat can add docker aware?

### ISSUE THREAD

**Issue by sqtds** [elastic/beats#22671]
**Describe the enhancement:**

**Describe a specific use case for the enhancement or feature:**
When I used filebeat in docker, it cost too much CPU performance. After analysis, I found that it was caused by golang identifying the number of CPU cores of the physical machine. It should identify the number of cpu cores of the docker container. When I modify this, it can reduce CPU consumption by 20%.

**Comment by segevfiner** [comment]
May want to take a look at https://github.com/uber-go/automaxprocs

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
