### ISSUE TITLE
Support multiple IPs in envoy module

### ISSUE THREAD

**Issue by hochraldo** [elastic/beats#22715]
Currently the envoy module only supports one IP for the X-Forwarded-For header into the envoy access logs.
However, according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For this header can contain multiple IP addresses. That's why an envoy access log can have the following entry (with the default access log format set: https://www.envoyproxy.io/docs/envoy/v1.10.0/configuration/access_log#default-format-string)

```
[2020-11-23T15:32:25.590Z] "GET /ping/ HTTP/1.0" 200 - 0 1 0 - "XXX.XXX.XXX.XXX,YYY.YYY.YYY.YYY" "-" "5ecb371a-b443-458f-969a-34c69b6ba4f2" "somehost.somedomain.com" "-"
```

This issue looks to similar to this one mentioned here: https://github.com/elastic/beats/issues/4322

**Comment by ChrsMark** [comment]
Possibly helpful PR: https://github.com/elastic/beats/pull/21215
