### ISSUE TITLE
In Metric Kafka Module topic name should be extracted from MBean name

### ISSUE THREAD

**Issue by gquintana** [elastic/beats#22734]
For metric name like `kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec,topic=mytopic`, the topic name should be extracted in specific Elasticsearch document field.
This would allow to build dashboard with topic specific metrics.
 
Several JMX/Jolokia metrics are concerned:
* `kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec,topic=mytopic`
* `kafka.server:type=BrokerTopicMetrics,name=BytesOutPerSec,topic=mytopic`
* `kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec,topic=mytopic`
* etc.

They could be merged in a single topic related document

**Comment by jsoriano** [comment]
Duplicate of https://github.com/elastic/beats/issues/22738. Thanks for reporting! I agree that this would be nice to have.
