### ISSUE TITLE
Extract topic name from "mbean" field for throughput fields

### ISSUE THREAD

**Issue by ckauf** [elastic/beats#22738]
**Describe the enhancement:**
Currently the Kafka Metricbeat Module does report `kafka.broker.topic.net.out.bytes_per_sec`, `kafka.broker.topic.net.in.bytes_per_sec`, and `kafka.broker.topic.messages_in`.

Same issue is for `kafka.consumer` metrics.

The topic name is included in the `mbean` and should be present as a single field for this metric.
Current state:
```json
       "kafka" : {
            "broker" : {
             "mbean" :"kafka.server:name=BytesOutPerSec,topic=example,type=BrokerTopicMetrics",
              "topic" : {
                "net" : {
                  "out" : {
                    "bytes_per_sec" : 1505.1950468321356
                  }
                }
              }
            }
          }
```

Suggestion: Use an ingest pipeline with a `kv` processor to extract the `topic` value. Something along this lines:
```json
POST _ingest/pipeline/_simulate
{
  "docs": [
    {
      "_source": {
        "kafka": {
          "broker": {
            "mbean": "kafka.server:name=BytesOutPerSec,topic=example,type=BrokerTopicMetrics",
            "topic": {
              "net": {
                "out": {
                  "bytes_per_sec": 1505.1950468321356
                }
              }
            }
          }
        }
      }
    }
  ],
  "pipeline": {
    "processors": [
      {
        "kv": {
          "field": "kafka.broker.mbean",
          "field_split": ",",
          "value_split": "=",
          "target_field": "__temp",
          "include_keys": ["topic"]
        }
      },
      {
        "rename": {
          "field": "__temp.topic",
          "target_field": "kafka.topic.name"
        }
      },
      {
        "remove": {
          "field": "__temp"
        }
      }
    ]
  }
}
```

**Describe a specific use case for the enhancement or feature:**
Visualization / Dashboards / Alerting on a per topic base

**Comment by ChrsMark** [comment]
cc: @andresrc

**Comment by sorantis** [comment]
Related: https://github.com/elastic/beats/issues/13604

**Comment by jsoriano** [comment]
Reported also https://github.com/elastic/beats/issues/22734 and https://github.com/elastic/beats/issues/24355. This would be something definitely interesting to do.

I don't think we can do it with an ingest pipeline at the moment, but it could be done by the Jolokia metricset used as base of this one.
