### ISSUE TITLE
[Metricbeat][docker][memory] Gracefully handle unavailibility of docker memory stats

### ISSUE THREAD

**Issue by atoom** [elastic/beats#22752]
**Describe the enhancement:**
In cases where no conatiners are running and therefor no memory stats available the  `memory` metricset in the Metricbeat `docker` module should not print the log line below:

`2020-11-25T10:56:45.629+0100    INFO    module/wrapper.go:259   Error fetching data for metricset docker.memory: No memory stats data available`

Over time this accumulates to a lot of log lines:

```
[user@host ~]$ grep -i "no memory" /opt/metricbeat/logs/metricbeat.log | wc -l
68809
```

**Describe a specific use case for the enhancement or feature:**
We deploy a generic setup with both docker and metricbeat on all our hosts. On some of our hosts there are no containers running and our metricbeat log file gets filled with log lines about no memor stats available. This should be handled more gracefully and the log line should not be printed.

**Comment by ahbonsu** [comment]
I'm still facing this issue... anyone has found a workaround?

**Comment by swtrux** [comment]
We are also facing this issue.  The logs are unneeded and cause in increase in data we ingest from the syslog.  There should be a way to turn this off.
