### ISSUE TITLE
[Enhancement request] adding XML functionality to read in winlogbeat or winlog input

### ISSUE THREAD

**Issue by 111andre111** [elastic/beats#22762]
**Describe the enhancement:**
Add functionality that the winlogbeat is able to read as well XML exported events
**Describe a specific use case for the enhancement or feature:**
At the moment winlogbeat can directly read EVTX files.
https://www.elastic.co/guide/en/beats/winlogbeat/current/reading-from-evtx.html
But for certain use cases like for instance test events or erroneously exported Event logs entries in XML format it might be interesting to add to winlogbeat the functionality to read XML files too and work with all the logic that happens during this way toward shipping the events. Today this is not possible.
It might be a good starting point when the start can be somewhere here
https://github.com/elastic/beats/blob/e0765e44911520c17c96ddb5fdffee19752ad795/winlogbeat/eventlog/wineventlog.go#L260
and maybe go there directly by a configurable format parameter if the source format is binxml or xml.
And in case the format is xml, just leave out the process of the conversion from binxml to xml.

**Comment by andrewkroh** [comment]
We've adding a processor to Filebeat called `decode_xml_wineventlog` that can parse XML windows event logs and produce an event that is similar to Winlogbeat. We've used in this in cases where users only have XML available. In some case we've paired this up with the Fleet integrations for Windows that contain Ingest Node pipelines for mapping the data to ECS. So I think this request is mostly met.

https://www.elastic.co/guide/en/beats/filebeat/7.14/decode-xml-wineventlog.html

**Comment by 111andre111** [comment]
This has worked apart from the fact that the parser goes wrong when the XML doesn't have a new line at the end. In this case the parser ended with an error:
```
"failed in decode_xml_wineventlog on the \"message\" field: error decoding XML field: XML syntax error on line 33: unexpected EOF
```

**Comment by andrewkroh** [comment]
Do you have an example JSON event that fails so I can reproduce it?

**Comment by andrewkroh** [comment]
> This has worked apart from the fact that the parser goes wrong when the XML doesn't have a new line at the end.

Most of the unit tests for `decode_xml_wineventlog` (and `decode_xml`) test on XML documents without a trailing newline. I don't think this is a problem for the processor.
