### ISSUE TITLE
Agent goes to Offline status in UI for some time on 7.11.0-SNAPSHOT Kibana cloud environment

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#22773]
**Kibana version:**
Kibana: 7.11.0-SNAPSHOT Kibana cloud environment

**Elasticsearch version:**
Elasticsearch: 7.11.0-SNAPSHOT cloud environment

**Host OS and Browser version:**
macOS Sierra 10.12.6 , All

**Original install method (e.g. download page, yum, from source, etc.):**
7.11.0-SNAPSHOT Kibana cloud environment from https://staging.found.no

**Description**
Agent goes to Offline status in UI for some time on 7.11.0-SNAPSHOT Kibana cloud environment

**Preconditions**
1. 7.11.0-SNAPSHOT Kibana cloud environment(with commit 968b6e5104013e02b55fefaa27793f878764361f) should be available.
2. Login into the above Kibana environment with 'elastic' superuser.
3. Endpoint integration should be added in Default Policy.
4. 7.11.0-SNAPSHOT version darwin x86_64 tar.gz agent should be installed with Default policy on macOS Sierra 10.12.6 with above kibana :-
(a) VM Name in VSphere: rahul_qa_mac_sierra
(b) Agent download location: https://snapshots.elastic.co/7.11.0-26a1a412/downloads/beats/elastic-agent/elastic-agent-7.11.0-SNAPSHOT-darwin-x86_64.tar.gz

**Steps to Reproduce**
1. Open the left hand menu and click 'Fleet' link under Management.
2. Navigate to Agents tab in Kibana and observe that agent comes to Online status.
3. Wait for some time(say 10 min)
4. Observe that agent goes to offline status in UI while agent and endpoint service is still running on the macOS host.
5. Wait for some more time(say 10 min) and observe that agent is now displayed in Online status.

**Test data**
N/A

**Impacted Test case id**
N/A

**Actual Result**
Agent goes to Offline status in UI for some time on 7.11.0-SNAPSHOT Kibana cloud environment

**Expected Result**
Agent should remain in Online status(should not go to Offline status) in UI on 7.11.0-SNAPSHOT Kibana cloud environment

**What's working**
 - N/A

**What's not working**
 - N/A
 
**Screenshot**
1. Online Agent goes to Offline and then comes back Online.
![Online-Offline-Online](https://user-images.githubusercontent.com/59917944/100348737-58f39a80-300d-11eb-802d-b203386eb087.jpg)

2. Agent and Endpoint in running state when agent is in Offline status.
![agent_endpoint_running](https://user-images.githubusercontent.com/59917944/100348762-60b33f00-300d-11eb-8e4f-404a03123f23.jpg)

3. macOS Sierra VM Template:
![mac_sierra_VM_Template](https://user-images.githubusercontent.com/59917944/100349302-3dd55a80-300e-11eb-9dda-4b03143dcd55.jpg)
 

**Logs**
N/A

**Comment by vipulsrivastava-qasource** [comment]
Reviewed and  Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@rahulgupta-qasource can you attach the usual Agent, Endpoint, and Kibana side logs so we can review them?

**Comment by rahulgupta-qasource** [comment]
Hi @EricDavisX

Thank you for sharing the feedback.

We have validated the defect on 7.11.0-SNAPSHOT Kibana cloud environment (with commit 968b6e5104013e02b55fefaa27793f878764361f) deployed from https://staging.found.no and 7.11.0-SNAPSHOT darwin agent tar.gz package on macOS Sierra 10.12.6 :-
https://snapshots.elastic.co/7.11.0-135ba4ce/downloads/beats/elastic-agent/elastic-agent-7.11.0-SNAPSHOT-darwin-x86_64.tar.gz

and found it **Fixed**.


**Preconditions**
1. 7.11.0-SNAPSHOT Kibana cloud environment(with commit 968b6e5104013e02b55fefaa27793f878764361f) should be available.
2. Login into the above Kibana environment with 'elastic' superuser.
3. Endpoint integration should be added in Default Policy.
4. 7.11.0-SNAPSHOT version darwin x86_64 tar.gz agent should be installed with Default policy on macOS Sierra 10.12.6 with above kibana :-
(a) VM Name in VSphere: rahul_qa_mac_sierra
(b) Agent download location: https://snapshots.elastic.co/7.11.0-135ba4ce/downloads/beats/elastic-agent/elastic-agent-7.11.0-SNAPSHOT-darwin-x86_64.tar.gz

**Steps to Reproduce**
1. Open the left hand menu and click 'Fleet' link under Management.
2. Navigate to Agents tab in Kibana and observe that agent comes to Online status.
3. Wait for some time(say 10 min)
4. Observe that agent remains in online status in UI.
5. Wait for some more time(say 10 min) and observe that agent is still displayed in Online status.

Screenshot:
![#22773](https://user-images.githubusercontent.com/59917944/101483430-2ab37a80-397e-11eb-9787-a7e73b1b6dab.jpg)


Hence, closing the issue.
