### ISSUE TITLE
Document setup step in Kubernetes and Cloud Foundry guides 

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#22772]
For some beats a setup step is needed to install dashboards and sometimes also needed to pre-install index templates and pipelines. This is mentioned in the [quick start guide](https://www.elastic.co/guide/en/beats/metricbeat/7.10/metricbeat-installation-configuration.html#setup-assets) focused on packages and in the [docker](https://www.elastic.co/guide/en/beats/metricbeat/7.10/running-on-docker.html#_run_the_metricbeat_setup) one, but not in the guides for [Kubernetes](https://www.elastic.co/guide/en/beats/metricbeat/7.10/running-on-kubernetes.html) or [Cloud Foundry](https://www.elastic.co/guide/en/beats/metricbeat/7.10/running-on-cloudfoundry.html).

We should mention the setup steps in all installation guides. Maybe we should have a shared page that all guides can refer to.

**Comment by EamonnTP** [comment]
Hi @jsoriano Just so I'm 100% sure on this. Can you confirm that the following steps (1-4) in the [quick start guide](https://www.elastic.co/guide/en/beats/metricbeat/7.10/metricbeat-installation-configuration.html#setup-assets) are required for Kubernetes? Steps 5 and 6 are what we currently have in the [Kubernetes](https://www.elastic.co/guide/en/beats/metricbeat/7.10/running-on-kubernetes.html) guide.
1. Install Beat
2. Connect to the Elastic Stack
3. Enable and configure data collection modules
4. Set up assets
5. Download and edit manifest
5. Deploy Beat

**Comment by jsoriano** [comment]
@EamonnTP only the step 4 is missing in Kubernetes and Cloud foundry guides. Rest of steps seem covered by current docs.

In these scenarios it'd be important to install the dashboards (indexes and pipelines are created by Beats on runtime if they don't exist), so we can focus on running `metricbeat/filebeat setup --dashboards`.
In the case of Kubernetes we could use the docker container as is done in the instructions for docker.
In the case of Cloud Foundry we can do something more similar to the generic steps given [here](https://www.elastic.co/guide/en/beats/metricbeat/7.10/metricbeat-installation-configuration.html#setup-assets) for Linux.

**Comment by dedemorton** [comment]
@jsoriano Do users still need to enable modules before running the setup command? I think that was only required for loading pipelines, but wanted to confirm.

**Comment by dedemorton** [comment]
If we only need to talk about dashboard loading, I wonder if we should just revamp the existing topic about loading dashboards and point to that?

https://www.elastic.co/guide/en/beats/filebeat/current/load-kibana-dashboards.html

I am a little concerned that here are various configuration settings that change the default behavior of things like template and pipeline loading.

**Comment by jsoriano** [comment]
> @jsoriano Do users still need to enable modules before running the setup command? I think that was only required for loading pipelines, but wanted to confirm.

In principle users deploying Beats on Kubernetes or Cloud Foundry are not going to enable/disable modules, they are going to provide directly the configuration files. So I don't think we should document these steps for these cases.

> If we only need to talk about dashboard loading, I wonder if we should just revamp the existing topic about loading dashboards and point to that?
> https://www.elastic.co/guide/en/beats/filebeat/current/load-kibana-dashboards.html

Sounds perfect to me, maybe we can also link to this topic in the "Running on docker" topic instead of explaining the same thing there.

> I am a little concerned that there are various configuration settings that change the default behavior of things like template and pipeline loading.

This is specially true for Filebeat pipelines, but they are installed by Filebeat itself if they cannot be found when ingesting data from modules, and this takes config settings into account.

Though this only works for Elasticsearch output, for other outputs, they will need to use the `--pipelines --modules` flags of `filebeat setup`. This is documented [here](https://www.elastic.co/guide/en/beats/filebeat/7.10/load-ingest-pipelines.html). We could link to this page to support this.

Index templates are also installed by Beats if needed when using the Elasticsearch output, for other cases we can point to this topic: https://www.elastic.co/guide/en/beats/filebeat/7.10/filebeat-template.html
