### ISSUE TITLE
script processor support for Heartbeat

### ISSUE THREAD

**Issue by arpit1305** [elastic/beats#22788]
currently "script" processor is not supported for Heartbeat unlike metricbeat.
Script processors are very useful when we want to enhance the data before we send to logstash when we want to enhance data with complex conditional logic. 

Can we add the support of it for heartbeat please?

**Comment by andrewvc** [comment]
I've opened https://github.com/elastic/beats/pull/23229 to add this, thanks for the suggestion!

**Comment by arpit1305** [comment]
Thanks much Andrew for considering this :)
