### ISSUE TITLE
How can I configure Packetbeat to prevent sending preflight http requst( OPTIONS request)

### ISSUE THREAD

**Issue by abdoegy83** [elastic/beats#22796]
How can I configure Packetbeat to prevent sending preflight http requst( OPTIONS request)
how to access  http method (post,get,put,.. options)

**Comment by andrewkroh** [comment]
Please reopen with the Packetbeat version and config you are using. And if you any more details about the request (like something captured from the network) that would help. I'm not aware of the Elasticsearch output making any HTTP OPTIONS requests.
