### ISSUE TITLE
Filebeat - httpjson missing "content-type"

### ISSUE THREAD

**Issue by jkaufman-LogRhythm** [elastic/beats#22807]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version:  Latest 7 release of FileBeat
- Operating System:  Centos 7
- Discuss Forum URL:  https://discuss.elastic.co/t/filebeat-httpjson-with-content-type-plus-beat-block/257131
- Steps to Reproduce: 

To the Yaml, make a POST API Call but add content-type

  http_headers:
   content_type: "application/json"

You seem to have it for http_endpoint but that doesn't support POST body for the API call? If you could enable that would be great, it is all that I am missing.

**Comment by jkaufman-LogRhythm** [comment]
Team:Security-External Integrations

**Comment by marc-gr** [comment]
> I got a comment in some beat issue by a marc-gr, "Content-Type and Accept headers are application/json by default, but can be overridden with a set transform on request. As far as the actual body of the response is json all should be fine, since the input just supports json decoding."
> 
> However I do not believe this is being honored if this is just a default, plus the set transform I cannot seem to find it in the filebeat documentation. I have a very specific POST api call that has a body request but it only works if you literally pass: 'Content-Type': 'application/json'
> 
> I know there is an http endpoint but that appears to not allow request body? Just response body.
> I did also pass the json object in two different ways to see if that was effecting:
> 
> ```
> - type: httpjson
>   enabled: true
>   url: redactid
>   interval: 1m
>   http_headers:
>    content_type: "application/json"
>   http_request_body:
>    filter:
>      severities: []
>      tags: []
>      tagOperator: AND
>      dateRange: ALL
>      dateRangeField: published
>      types: []
>      withFeedback: true
>      withoutFeedback: true
>    sort:
>      property: date
>      direction: DESCENDING
>    pagination:
>      size: 50
>      offset: 0
>   fields_under_root: false
>   processors:
>    - decode_json_fields:
>        fields: ["message"]
>        target: json
> ```
> 
> also just did:
> 
> ```
>    {
>    "filter": {
>     "severities": [],
>     "tags": [],
>     "tagOperator": "AND",
>     "dateRange": "ALL",
>     "dateRangeField": "published",
>     "types": [],
>     "withFeedback": true,
>     "withoutFeedback": true
>     },
>    "sort": {
>     "property": "date",
>     "direction": "DESCENDING"
>     },
>    "pagination": {
>     "size": 50,
>     "offset": 0
>     }
>    }
> ```

Hello @jkaufman-LogRhythm ! I think you are referring to my comment in https://github.com/elastic/beats/pull/22320#issuecomment-736310001, if that is the case, it was making reference to the new functionalities of httpjson that are going to be included in the next release (they are in `master` also, you can find documentation for them https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-httpjson.html). Sorry if my answer caused confusion.

As you mentioned, with previous versions of httpjson it is not possible to set custom content-type or accept headers.
