### ISSUE TITLE
[Monitoring] Provide cluster display name information in node_stats for term grouping

### ISSUE THREAD

**Issue by ravikesarwani** [elastic/beats#22806]
Currently we do not have cluster display name information at the node_stats level.
This field is key for creating meaningful visualizations and term groupings, especially when multiple cluster data is being stored in the monitoring cluster.

We should look at adding this field for 7.11 and also in modules to package transition with the Agent work.

cc: @andresrc @ycombinator @chrisronline

**Comment by ravikesarwani** [comment]
@chrisronline It is node display name information. I updated issue title and description to make it more clear.

**Comment by chrisronline** [comment]
We currently do show the node name though? It's here: https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/resources/monitoring-es.json#L46

<img width="515" alt="Screen Shot 2020-12-01 at 10 36 49 AM" src="https://user-images.githubusercontent.com/56682/100761671-25c05b00-33c1-11eb-9606-d0ee06264399.png">

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
