### ISSUE TITLE
runoptions is only a Packetbeat option

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#2281]
`runoptions` is only supported by Packetbeat on Linux so it should only appear in the Packetbeat docs and there should probably be a note about it only working on linux.

https://www.elastic.co/guide/en/beats/filebeat/current/configuration-run-options.html

**Comment by ruflin** [comment]
The runoptions should probably also be moved under the packetbeat namespace (if possible)

**Comment by andrewkroh** [comment]
Good catch, the example should be:

```
packetbeat:
  runoptions:
    uid=501
    gid=501
```

**Comment by ruflin** [comment]
Closing as #2439 is merged.
