### ISSUE TITLE
[elastic-agent] older name dataset (endpoint-security vs endpoint_security) is created with 7.11 Agent, may be missing a back-port?

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#22828]
@michalpristas N Chaulet pointed me to you...  to help review why we’d see:
elastic_agent.endpoint-security as well as
elastic_agent.endpoint_security
listed in the logs dataset drop down in Kibana for the new Agent logs feature which references the datasets.

It would seemingly point to a PR being missing a back-port to 7.11 right?  I saw this on the 8.0 kibana.endpoint.elastic.dev demo server (which happens to also run a few 7.11 Agents), you can check there or ping back to me for more comment / clarification if needed.

screenshot:
<img width="277" alt="Screen Shot 2020-11-30 at 11 52 12 AM" src="https://user-images.githubusercontent.com/12970373/100774983-a9ce0f00-33d0-11eb-9c63-b79240745448.png">

Sorry for dropping a bare-bones ticket, please do help fill out with anything that is needed.  just didn't want to lose this in slack

**Comment by ph** [comment]
@blakerouse Are we missing a backport for 7.11?

**Comment by blakerouse** [comment]
Yes seems this was not backported: https://github.com/elastic/beats/pull/22554

**Comment by blakerouse** [comment]
This was backported.
