### ISSUE TITLE
[Elastic Agent] Investigate how inputs are run for each application that Elastic Agent spawns

### ISSUE THREAD

**Issue by blakerouse** [elastic/beats#22823]
## Current Behavior

Currently Elastic Agent runs a single application per multiple inputs. So if the system integration is being used and the nginx integration is being used, only 1 metricbeat will be ran. That metricbeat will collect both the system integrations and the nginx metrics and send them to elasticsearch.

This is currently focusing on `metricbeat` but the same could be applied to any application ran by Elastic Agent.

### Pros

*  1 connection is made to elasticsearch for multiple metrics
* Less memory usage
  * This **needs more research** on if it truly is less memory usage to make a difference. The way page mapping works it could be that the `.text` section of the executing binary is map to the same physical memory and the virtual memory is then mapped into each executing process, meaning that it's actually not using more memory. The stack and heap would be more memory usage.

### Cons

* No way to distinguish which between X inputs is causing load on metricbeat.
  * Without knowing which input is causing load inside of the running metricbeat it is not obvious for a user to know which input is causing the load so they could take the appropriate action. When Elastic Agent reports the metrics for an input, it would be for the whole application not for a single input.

## Possible Future Behavior

Elastic Agent could change to run a single application per input. This means that in the previous scenario with both the running system integrations and the nginx metrics 2 metricbeats would be ran. 1 for the system integration and another for nginx metrics.

### Pros

* Possible to distinguish the load between the different integrations/inputs.
  * Metric collections for the running metricbeats would be clear that the load is coming from X input and not the other input.
* **Bonus**: Log level could be adjusted per input.
  * At the moment the log level is at the Elastic Agent level, but could be moved to each input level with this design.

### Cons

* A connection per input to elasticsearch
  * The number of connections back to elasticsearch would increase. At the moment this is already high, because a default installation of Elastic Agent running the system integration will have 4 connections to elasticsearch per host. (2 metricbeat, 2 filebeat). **This already needs to be solved**.
  * Possible solution is to proxy all the events from the running applications through the Elastic Agent.
* More memory usage
  * The counter pro above highlights how this could be minimal. Stack and heap usage might not grow as much across both beats because instead of 1 running 2 inputs, 2 are running 1 input. (**Needs more research**)

**Comment by ph** [comment]
cc @simitt @ruflin

**Comment by ph** [comment]
@urso I would like your opinion on this or ideas.

**Comment by ruflin** [comment]
Yes, closing it directly. I added a reference to the v2 architecture doc.
