### ISSUE TITLE
[Fleet] The log level feature in UI is showing logs for a given libbeat line and we don't see it associated correctly with the log level

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#22858]
We see a specific log line that seems to only be shown when no-specific log level is selected in the UI.  It should be categorized and shown as being under one of the ones listed right?  Unless we have a Kibana side bug that the log level isn't in the listing (that would make sense actually, maybe its a Kibana bug).

This is as tested with an 8.0 self managed stack snapshot setup and 8.0 latest Agent on Linux Debian.  I am testing on our demo server:  kibana.endpoint.elastic.dev/app/fleet#/fleet/agents/

see video for concern:
[what-level-is-this-log-line-at.mov.zip](https://github.com/elastic/beats/files/5629818/what-level-is-this-log-line-at.mov.zip)

PH notes it should be at Info level, per libbeat code here:
https://github.com/elastic/beats/blob/master/libbeat/monitoring/report/log/log.go#L145

I took another video showing off that there are logs, but that when selected NONE of the available levels show any logs
[no-log-levels-matching.zip](https://github.com/elastic/beats/files/5629991/no-log-levels-matching.zip)

screenshots:
![logs-exist](https://user-images.githubusercontent.com/12970373/100887123-9b403000-3482-11eb-8095-e575096219de.png)
![nothing-at-info-level](https://user-images.githubusercontent.com/12970373/100887125-9bd8c680-3482-11eb-91b6-0f5aa866966a.png)

**Comment by ferullo** [comment]
Endpoint logs are ECS compliant. If you find they aren't that's a bug in Endpoint.

**Comment by blakerouse** [comment]
I think what you are seeing here is that because all beats are started at `trace` level, that means that every event is logged to the file with the `log.level: debug`. Then its picked up again by the monitoring filebeat, so every event is in the log twice.

#19179 documents the real issue, this seems to be a side-effect.

**Comment by ph** [comment]
Ok, I though we change the default of beats to _info_ this is not the case?

**Comment by blakerouse** [comment]
Maybe we did? If so should close the #19179 issue.

@michalpristas ^ can you confirm? Thought beats were still running at a higher level.

**Comment by michalpristas** [comment]
yep we changed it to info some time ago when making log level reloadable

**Comment by michalpristas** [comment]
@ph we did turn of ECS because there was a version reported twice with different ecs versions. one coming from beat another one from library #21616

**Comment by ph** [comment]
@michalpristas Maybe the fix was the incorrect one and we should just align the version?

**Comment by michalpristas** [comment]
even if versions are aligned field is reported twice, which is not nice. i will drop one of the fields added by lib and turn on ecs back

**Comment by michalpristas** [comment]
@EricDavisX this got closed with the PR please reopen if you see this behavior again, i checked events and they have correct log level field now

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

While performing exploratory testing on 8.0.0 kibana cloud build today, we have observed that no-specific level logs get generated at logs UI on specific search.

Pre-condition:
1. Agent should be deplayed to 8.0.0 Kibana cloud environment. Build details are as follows:
```
BUILD 38728
COMMIT f2d961df6a5f78807dc2ef265aaba3c96d691881
Artifact link: https://snapshots.elastic.co/8.0.0-5823f363/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip
```

Steps to reproduce:
1. Login to Kibana cloud environment.
2. Go to Agents tab. Observe, logs are generated successfully.
3. Click on Agent logging level and select option 'error'.
4. Apply changes. And observe confirmation messgae is displayed.
5. Refresh the browser. Observe, changes are updated on agent details page at logging level field.
6. Navigate back to Logs UI. Select 'elastic-agent.filebeat' filter at 'Dataset'
7. Observe, no-specific level logs are displayed.

As per our understanding, whenever we change agent logging level, no-specific level logs are generated at backend. 

Screenshot:
![#22858_reopen](https://user-images.githubusercontent.com/72375798/101780738-e8746f80-3b1c-11eb-8993-5d9bf4076cfe.jpg)

Hence, we are reopening this issue.

**Comment by EricDavisX** [comment]
I don't know if the last research @dikshachauhan-qasource posted is a separate issue, I will need to review and play with the feature more.  I am seeing the specific original concern is still happening, so I am glad it is re-opened.  I will push some convo to slack to see if we can hash out what remains to be done.  @ph @nchaulet @michalpristas

**Comment by michalpristas** [comment]
i need to take a look but these sshould be info level so with this settings they should not be there.
also checked commit used in agent ` deba31` this commit is 3 commits before fix got in.

**Comment by EricDavisX** [comment]
I'm testing in on 8.0 latest a few days later and I am not seeing the original issue, so I would like to close this out, it looks like the latest changes helped fix this up.  @dikshachauhan-qasource can you confirm if you are still seeing the problem you reported, and if so, let us open a new ticket please with all specifics and a clean history?  And then we can close this out.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

Thanks for the feedback.

We have noticed same behavior on 8.0 latest Kibana cloud build.  Hence, reported new defect [#23145 ](https://github.com/elastic/beats/issues/23145) for same.

Please let us know if anything is required from our side.
