### ISSUE TITLE
Metricbeat built-in dashboards for Kafka should account for splitting consumer lag by partition ID

### ISSUE THREAD

**Issue by eddieturizo** [elastic/beats#22859]
**Describe the enhancement:**

Consider updating the Metricbeat built-in dashboards so that consumer lag can be split by partition ID. 

**Describe a specific use case for the enhancement or feature:**

If a Kafka topic has 10 partitions and every partition lags by 10, the actual topic lag is 100. Using the built-in Metricbeat dashboards, the max metric would (incorrectly) show a lag of 10. The goal of the use case is to be able to take the max consumer lag of each partition and then sum the values per topic.

related https://github.com/elastic/kibana/issues/84776

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
