### ISSUE TITLE
[filebeat]only add need label in k8s processors ?

### ISSUE THREAD

**Issue by vsxen** [elastic/beats#22878]
the pod label is indefinite, such as
```
app: nginx
helm.sh/chart: foo-chart
app.kubernetes.io/instance: foo
app.kubernetes.io/managed-by: Tiller
app.kubernetes.io/component: foo
```
I only want to add `app` label ,ignore other label ? 

how to configure it ?

Ref
https://discuss.elastic.co/t/filebeats-auto-mapping-of-kubernetes-labels-causing-big-issues/

**Comment by vsxen** [comment]
And can I reload filebeat auto discover config?

https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-reloading.html

**Comment by kaiyan-sheng** [comment]
Hello, thanks for creating this. But we would kindly ask you to post all questions and issues on https://discuss.elastic.co/c/beats before opening a Github Issue. Your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue or open a new one with more details. Thanks in advance!
