### ISSUE TITLE
Dynamic CPU allocation support in Metricbeat System module

### ISSUE THREAD

**Issue by gbanasiak** [elastic/beats#22885]
**Describe the enhancement:**

Currently Metricbeat assumes fixed number of CPU cores, which is determined at startup ([code](https://github.com/elastic/beats/blob/v7.10.0/libbeat/metric/system/cpu/cpu.go#L29-L33)). This assumption is not valid in case of certain hypervisors (e.g. [Oracle VM](https://docs.oracle.com/cd/E50245_01/E50249/html/vmcon-vm-vcpus.html)). To support such environments, Metricbeat should periodically update the number of CPU cores.

**Comment by fearful-symmetry** [comment]
So, needless to say, `NumCPUs` is used quite a few times for a variety of things, but at least it should be fairly easy to update the metrics scraping code so we can respond to dynamic CPUs.

**Comment by fearful-symmetry** [comment]
PR has been merged, will be backported. Change should be there in 7.12.
