### ISSUE TITLE
[Heartbeat] Add `no_chromium_sandbox` option for synthetics

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#22901]
**Describe the enhancement:**

Once https://github.com/elastic/synthetics/issues/136 is added to synthetics we the corresponding no sandbox option in the heartbeat yaml.

**Describe a specific use case for the enhancement or feature:**

This makes it easier to run chromium in docker since you don't need elevated seccomp privs

**Comment by justinkambic** [comment]
When running a browser monitor with `sandbox: true`, the command that Heartbeat sends to Elastic Synthetics includes `--sandbox`, so I am assuming this feature is working as designed. The flag is not present when I remove the config option.

![image](https://user-images.githubusercontent.com/18429259/117015416-b62c0000-acbf-11eb-8017-4fb911575a12.png)
