### ISSUE TITLE
Add Metricbeat --system.hostfs equivalent to Elastic Agent

### ISSUE THREAD

**Issue by david-kow** [elastic/beats#22915]
**Describe the enhancement:**

When configuring metrics inputs in Elastic Agent, user should be able to pass Metricbeats `--system.hostfs` equivalent.

**Describe a specific use case for the enhancement or feature:**

I'd like to monitor a host out of a container that's running on it. With raw Metricbeat I [can](https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html#CO9-1) mount the hosts `/proc` directory in the container and pass it with the `--system.hostfs` flag on the command line. I don't think that's currently possible with Elastic Agent.

To improve past what Metricbeat offers, this could be part of the config instead of command line flag.

**Comment by ph** [comment]
I think this should be part of the metricbeat input configuration and not system we have to deal at the agent level.  @exekias @masci ? I've send to your team but if we don't agree lets discuss it.

**Comment by david-kow** [comment]
> I think this should be part of the metricbeat input configuration and not system we have to deal at the agent level. @exekias @masci ? I've send to your team but if we don't agree lets discuss it.

I'll just chime in that from my perspective, this being a part of the configuration would be preferable to a command line flag.

**Comment by masci** [comment]
Ack. I agree this should be a config option.
