### ISSUE TITLE
cisco module ?

### ISSUE THREAD

**Issue by RRadziejewski** [elastic/beats#22933]
Any idea why it is not working ?
Versions of software 7.9.1-oss

Config is the simplest one:

`- module: cisco
  asa:
    enabled: true
`

But none of the configuration parameters work problem is all the time this:

`2020-12-04T17:09:00.989+0100	ERROR	cfgfile/reload.go:258	Error loading configuration files: 1 error: Error creating runner from config: fileset cisco/asa is configured but doesn't exist`

**Comment by philippkahr** [comment]
@RRadziejewski you have an error in your configuration it should be
```yml
- module: cisco
  asa:
      enabled: true
```
