### ISSUE TITLE
[Heartbeat][Agent] Synthetics deps and Elastic Agent

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#22932]
This picks up part of the discussion from https://github.com/elastic/beats/issues/22837 where we agreed to include an extra gigabyte of deps for synthetics in the main heartbeat image. The remaining question is what to do about agent? There are essentially two paths forward:

1. Make the agent docker image include the extra ~1GiB of deps for synthetics (RPM deps, node, and chromium)
2. Make a separate agent docker image that is larger for use in situations where synthetics is needed.

I propose that we make a new 'centralized' agent docker distribution with the extra deps. It won't be intended for use as a side car, and will only be put in place on the few machines where running agent is the main purpose, rather than say, every server or k8s pod etc.

**Comment by ruflin** [comment]
As the Elastic Agent has also the option to download the dependencies if needed, it would be good to know how long it would take to download this additional dependency?

**Comment by mostlyjason** [comment]
Thanks I assume this isn't just concerning docker and also concerns adding synthetics to the agent installer?

If we add 1GB to the main agent image, that would eat a lot of bandwidth & storage across 1000s of hosts. So option 2 sounds better for the majority of users.

More generally, we talked about having a minimal docker image for hosts that are internet connected so they can download dependencies on demand, and a full docker image for offline hosts. @ph do you remember where this conversation ended up? I can't seem the find the issue.

**Comment by ph** [comment]
@mostlyjason I can't find that issue, we mentioned it in the heartbeat issue some time ago but this use case is different, and I am not sure it fit well with docker.

---

_I might ask question that have been already decided, but I don't have enough details about the architecture_

Now, I think there is multiple question to asks, as @mostlyjason pointed out what is the usecase when there is no docker involved for synthetics. Is Docker a **hard requirement** on that new feature? Do people that run heartbeat from the _tar.gz_ will be able to use that new behavior?

How the execution look like, is heartbeat starting a new container from hearbeat how this work  inside the docker images?


Maybe @ruflin or @andrewvc could

**Comment by andrewvc** [comment]
@ph docker is not a hard requirement, but it is one initially, mostly because we don't want to support multiple platforms. There's a lot that can go wrong with all the GUI deps, node deps, etc., and it makes more sense to focus on features right now.

I expect that will change in the future. However, it sort of ruins the whole "click to add an integration, it just works" aspect, since you can't just do that. You need a box with all the stuff. So, for agent, maybe it *should* be docker only.

That said, I think we practically need to go with the second approach, of two docker images. A regular fleet version and a jumbo version. That also hurts the vision of a single agent, but it's the better compromise IMHO.

**Comment by andrewvc** [comment]
It looks like heartbeat with synthetics is actually only ~500MiB. Given that the size isn't so bad, is there any objection to simply merging synthetics into the agent docker image?

**Comment by ruflin** [comment]
Our current image is ~569MB. So adding synthetics would double it. My biggest concern is that if Elastic Agent is deployed across many machines, this will consume now double the bandwidth, 500 is already quite a bit.

**Comment by andrewvc** [comment]
@ruflin we're at the point where we need a firm decision relatively soon. The two options I see are either include it in the mainline image or make an alternate `agent-synthetics` image. Which way should we go?

**Comment by ruflin** [comment]
It is a tricky decision here. If we include it and later realise the size is too large, we can't remove it anymore as it is a breaking change. If we go the separate container, my understanding is that a user could not just add synthetics but would need a separate container for it. @alvarolobato @tbragin Would be nice if you could chime in here.

**Comment by ph** [comment]
@ruflin @andrewvc That size increase would only affect our container's release or all of our artifacts?

**Comment by andrewvc** [comment]
Just the container, and it wouldn't increase by 500 Mib, probably only a few hundred if I had to guess. Metricbeat's docker image is 190MiB today by comparison, so we could call that the base size.

**Comment by mostlyjason** [comment]
It helps that its just the container. Containers are usually run on servers, not as often on endpoints. Usually there are a smaller number of servers and 500MB of disk isn't a concern. In that case increasing the size shouldn't be as much of an issue. 

Also, does that mean users cannot run synthetics on a regular agent install? If so, we should consider adding that to the blocklist to prevent users from adding it.

**Comment by andrewvc** [comment]
Yes, correct on both counts, how do we add it to the blocklist?

**Comment by andrewvc** [comment]
@ruflin @ph @mostlyjason do we have enough info to come to a decision here? I vote we bundle with docker agent.

**Comment by mostlyjason** [comment]
+1 to bundle it then. You can add it to the blocklist here https://github.com/elastic/beats/issues/21000

**Comment by ph** [comment]
+1 to bundle it for docker-agent.

**Comment by paulb-elastic** [comment]
@mostlyjason / @ph, irrespective of this being bundled or not, what is the behaviour from a Fleet perspective, if the non-Docker version of the Elastic Agent is used (reason for asking is I wonder if this is a similar flow to if we didn’t bundle Synthetics with the image)?

For example, if I install the binary version of the Elastic Agent (non-Docker), and associate this to an Agent Policy which has a Synthetic Integration policy, what happens in that case?  Is there some kind of *you are running the wrong version of the Agent* error?

**Comment by ruflin** [comment]
@paulb-elastic Not much happens today except that you will get an error from the Elastic Agent when rolling out the policy. We should fix this by bringing knowledge about the capabilities of an Elastic Agent to Fleet. There are other features which require this too.

**Comment by paulb-elastic** [comment]
This has been discussed and although simpler for onboarding, we can’t ignore the additional space overhead of bundling Synthetics+dependencies with the Docker build of Elastic Agent.

As such, to proceed with this, we will be opting for a separate Docker build of the Elastic Agent+Synthetics+Dependencies and clarify in the [documentation](https://github.com/elastic/observability-docs/issues/668) and [readme](https://github.com/elastic/uptime/issues/328) that this must be used to try Real Browser Synthetic Integrations.

**Comment by mostlyjason** [comment]
@paul-tavares I jsut want to answer your question:

> what is the behaviour from a Fleet perspective, if the non-Docker version of the Elastic Agent is used (reason for asking is I wonder if this is a similar flow to if we didn’t bundle Synthetics with the image)?

If you add synthetics to the [blocklist](https://github.com/elastic/beats/issues/21000) that gets bundled by default in distributions of the agent without synthetics, then the user will see the agent show up as unhealthy on the agents page and they will be able to see an error that synthetics is blocked. Without adding it to the blocklist, the agent will show as healthy when it is not.

**Comment by andrewvc** [comment]
Thanks @mostl we've opened an issue around that here https://github.com/elastic/beats/issues/25775

**Comment by andrewvc** [comment]
Reopening because we now have an implementation in https://github.com/elastic/synthetics/issues/360

**Comment by dominiqueclarke** [comment]
Tested with `beats/elastic-agent-complete:7.15.0-caca3588-SNAPSHOT`: https://container-library.elastic.co/r/beats/elastic-agent-complete:7.15.0-caca3588-SNAPSHOT

Working as expected for both inline and zip url tests.
<img width="926" alt="Screen Shot 2021-08-31 at 10 33 56 AM" src="https://user-images.githubusercontent.com/11356435/131522092-c685acc9-dd5f-4499-9f35-f28e5a58efe0.png">

**Comment by paulb-elastic** [comment]
Re closing as opened by Zube
