### ISSUE TITLE
process.args_count not populated for windows sysmon process creation events 

### ISSUE THREAD

**Issue by Samirbous** [elastic/beats#22958]
**Describe the enhancement:**

Apparently [process.arsg_count](https://www.elastic.co/guide/en/ecs/current/ecs-process.html#field-process-args-count) is not populated in Winlogbeat (e.g Sysmon Process Creation Events or Windows Process Creation EventID 4688):

![image](https://user-images.githubusercontent.com/64742097/101358378-0cc11980-389b-11eb-98ae-094eb54de980.png)

And this is an example to confirm that Sysmon process creation data contains process.args details:

![image](https://user-images.githubusercontent.com/64742097/101358598-5c074a00-389b-11eb-85ad-0f53921c023c.png)

**Describe a specific use case for the enhancement or feature:**

**Comment by fearful-symmetry** [comment]
@narph Can you look at this? It doesn't look like something in metricbeat code.
