### ISSUE TITLE
Investigate Performant XML Identification

### ISSUE THREAD

**Issue by andrewstucki** [elastic/beats#22965]
**Describe the enhancement:**

https://github.com/elastic/beats/pull/22940 adds code for mime type sniffing. Currently, if an xml document doesn't begin with an `<?xml` signature the way the code determines if it's xml is by unmarshaling everything and seeing if an error occurred. Go's xml implementation is pretty bad in terms of speed and memory pressure. We should replace this with a more scalable implementation. See https://github.com/elastic/beats/pull/22940#discussion_r537744159 for some ideas for identification rules for an XML document.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
