### ISSUE TITLE
[Ingest Manager]: Log are not updated as per log levels applied at Agent logging level on Agents tab.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#22986]
**Kibana version**:
Kibana:8.0.0 snapshot Cloud environment

**Elasticsearch version**:
Elasticsearch:  8.0.0 snapshot Cloud environment  

**Host OS and Browser version**:
Windows 10, All

**Original install method (e.g. download page, yum, from source, etc.)**:
8.0.0 snapshot Cloud environment 

**Description**:
[Ingest Manager]: Logs are not updated as per log levels applied at Agent logging level on Agents tab.

**Preconditions**:
1. Artifacts for 8.0.0 snapshot Agent should be available.
Link used: https://staging.elastic.co/7.10.1-de6b0b5d/summary-7.10.1.html/elastic-agent-7.10.1-windows-x86_64.zip
2. 8.0.0 snapshot Cloud environment should be available.
COMMIT 008c6a0e19a1c9e130152a6082c574057c841f89
BUILD 38640
3. Agent must be deployed.

**Steps to Reproduce**:
1. Login to Kibana using a super admin account.
2. Go to Agents. Notice, by default 'info' agent logging level is selected. 
3. Click on Agent logging level. Select 'debug' 
4. Click on Apply changes.
5. Observe, a confirmation message is displayed.
6. Now, refresh the page.
7. Observe, info logs are generated after the debug level is selected at agent logging level

**Impacted Test case id**:
- [C173096](https://elastic.testrail.io/index.php?/tests/view/173096)
- [C173097](https://elastic.testrail.io/index.php?/tests/view/173097)
- [C173098](https://elastic.testrail.io/index.php?/tests/view/173098)

**Actual Result**:
Info logs are generated after the debug level is selected at agent logging level.

**Expected Result**
Only debug level logs should be generated as per verbosity order after debug level is selected at agent logging level.
`Verbosity order: Error > Warning > Info > Debug`

**What's working**:
N/A

**What's not working**:
N/A

**Screenshot**: 
![Loglevelerror](https://user-images.githubusercontent.com/72375798/101491168-6dc71b00-3989-11eb-9176-3bdfe0d76be3.jpg)

**Comment by dikshachauhan-qasource** [comment]
@muskangulati-qasource please review

**Comment by muskangulati-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
Thanks for testing and logging.  I think the feature isn't ready to be evaluated yet, this was bad communication from me and the team I think, sorry.  For details, I can cite: we had 75% of the UI finished and then afterwards started putting the PRs up to make the Agent and backend align... it should be ready end to end soon.

This one is just merged to 8.0 and has open backports:
https://github.com/elastic/beats/pull/22815
 - so we'll wait on this to test it end to end.

This is relating, and is for bugs for the same feature so we should wait to test until this as well:
https://github.com/elastic/beats/pull/22987/files

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX

Thank you for the confirmation.
Please let us know whenever the feature is ready to test. We will re-validate them.

Also, we have validated the merged changes for  [#22815 ](https://github.com/elastic/beats/pull/22815) and has shared our detailed observation under same ticket.

Please let us know if anything else is required from our side.

**Comment by dikshachauhan-qasource** [comment]
The feature has been implemented successfully.
Hence closing this out.
