### ISSUE TITLE
Metricbeat prometheus module: merge series in a single event

### ISSUE THREAD

**Issue by jmartin51** [elastic/beats#22984]
**Describe the enhancement:**

Using prometheus module query metricset, we can see that an event is sent for each series contained in the prom query results.
Same behavior could be observed when using multiple queries. 

The Enhancement would be to add an option in metricbeat configuration to add all series returned by queries in a unique document

**Describe a specific use case for the enhancement or feature:**

For example:
The following basic query `rate(prometheus_http_requests_total[5m])`  return multiple series (11 here) see the screenshots:
What is happening is that metricbeat sends 11 events/documents (1 per series).
![Screenshot 2020-12-08 at 10 06 40](https://user-images.githubusercontent.com/62959805/101473942-be6b5380-394a-11eb-823f-ccd960e4b4ad.png)

Metricbeat prometheus configuration file:
```
- module: prometheus
  period: 10s
  hosts: ["192.168.64.10:9090"]
  metricsets: ["query"]
  queries:
  - name: "rate_http_requests_total"
    path: "/api/v1/query"
    params:
      query: "rate(prometheus_http_requests_total[5m])
```

Example of metricbeats event:
```
2020-12-08T09:52:54.160+0100	DEBUG	[processors]	processing/processors.go:203	Publish event: {
  "@timestamp": "2020-12-08T08:52:54.000Z",
  "@metadata": {
    "beat": "metricbeat",
    "type": "_doc",
    "version": "7.10.0"
  },
  "event": {
    "dataset": "prometheus.query",
    "module": "prometheus",
    "duration": 73238470
  },
  "metricset": {
    "name": "query",
    "period": 10000
  },
  "service": {
    "type": "prometheus",
    "address": "http://192.168.64.10:9090"
  },
  "prometheus": {
    "labels": {
      "code": "200",
      "handler": "/api/v1/status/tsdb",
      "instance": "localhost:9090",
      "job": "prometheus"
    },
    "query": {
      "rate_http_requests_total": 0
    }
  }
```

Then another event for another series:
```
2020-12-08T09:52:54.161+0100	DEBUG	[processors]	processing/processors.go:203	Publish event: {
  "@timestamp": "2020-12-08T08:52:54.000Z",
  "@metadata": {
    "beat": "metricbeat",
    "type": "_doc",
    "version": "7.10.0"
  },
  "service": {
    "address": "http://192.168.64.10:9090",
    "type": "prometheus"
  },
  "prometheus": {
    "labels": {
      "code": "200",
      "handler": "/favicon.ico",
      "instance": "localhost:9090",
      "job": "prometheus"
    },
    "query": {
      "rate_http_requests_total": 0
    }
  },
  "event": {
    "dataset": "prometheus.query",
    "module": "prometheus",
    "duration": 100822431
  },
```
 
Etc...

The aim would be to have everything in one event when the option is enabled

**Comment by ChrsMark** [comment]
Hey!

In principal storing different timeseries in the same event is not correct. In Prometheus world different set of labels means different timeseries. 

In our case this would mean that we merge all these different timeseries something that might cause issues in searches, visualisations, dashboards. To illustrate the point let me provide an example:

Timeseries:
```
series_X(label_a="a")
series_X(label_b="b")
```

Storing them into the same event will be like having:
```
series_X(labels_a="a", labels_b="b")
```

In this, I'm not so sure we would like sth like this.

@exekias @sorantis thoughts?
