### ISSUE TITLE
[Elastic-Agent] Testing over Agent Roll-back on Failure

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#22993]
This will manage the manual test done from this ticket / pr:
https://github.com/elastic/beats/issues/21518
https://github.com/elastic/beats/pull/22537

The Agent, during a automated upgrade may have problems, it will have the ability to rollback to the prior working version and clean up.

Details of A/C and test considerations are below:
TBD

**Comment by rahulgupta-qasource** [comment]
Hi Eric

We have gone through the linked tickets and found that it requires validation through automation tests.

Please let us know if anything is required from our end.

**Comment by EricDavisX** [comment]
we should test on all of the different OSes, mac, linux + windows please.

**Comment by rahulgupta-qasource** [comment]
Hi @EricDavisX

Thank you for sharing the feedback.

We have created **04** and updated **01** testcase for each of mac, linux tar, deb, rpm and windows x64 agent packages.

```
Build details:
Kibana commit: 818246e4675c2960667900ba99b3ca178800360a
Build: 38930
Agent download location: https://snapshots.elastic.co/7.11.0-fa101d11/downloads/beats/elastic-agent/elastic-agent-7.11.0-SNAPSHOT-darwin-x86_64.tar.gz
```


**Observations:**
(a) As per @michalpristas comment https://github.com/elastic/beats/issues/21518#issuecomment-722407219 , we have validated the steps for macOS and found that elastic agent is not rolled back on 8.0.0-snapshot Kibana cloud environment.

Prerequisite:
1. 8.0.0-snapshot Kibana cloud environment should be available and elastic(superuser) is logged-in to the application.
2. 7.11.0-snapshot macOS agent should be installed(using sudo ./elastic-agent install) on 8.0.0-snapshot kibana cloud.


Steps followed:-
1. Open the 8.0.0-snapshot kibana cloud environment and click on L.H.S Fleet link.
2. Click on Agents tab and observe that prerequisite 7.11.0-snapshot agent is in 'Healthy' status.
3. Upgrade the agent to 8.0.0-snapshot version by clicking on 'Upgrade agent' option under 'Actions' column
4. Observe that agent is successfully upgraded to 8.0.0-snapshot agent version.
5. SSH to prerequisite macOS host and get the pid of main agent process using command:
ps -ef | grep 'elastic-agent'

![elastic-agent process](https://user-images.githubusercontent.com/59917944/102346388-c23f4b80-3fc4-11eb-9b8b-aaa6cde03bbe.jpg)


6. Kill the agent process several times with below command :-
sudo kill -9 {PID} where PID is a process ID of /Library/Elastic/Agent/elastic-agent

7. Repeat steps 5 and 6 several times.
8. Wait for some time and observe that agent version is 8.0.0-snapshot and is not rolled back to 7.11.0-snapshot agent.
Screenshot:-
![after_upgrade_kill](https://user-images.githubusercontent.com/59917944/102346398-c703ff80-3fc4-11eb-8370-05bfc4a58ec6.jpg)




(b) Moreover, 7.11.0-snapshot macOS agent version is still upgraded successfully to 8.0.0-snapshot agent version(agent is not rolled back to 7.11.0-snapshot agent) if we get and kill pid several times while upgrading the agent(while agent is in 'UPDATING' status).
as per testcase https://elastic.testrail.io/index.php?/cases/view/35211


**Query:**-
Could you please share the exact steps to rollback the elastic agent and how many times the elastic-agent process is to be killed for rollback to trigger.

**Comment by EricDavisX** [comment]
I am just now realizing that the Agent Hardening feature would likely impact how easy it is to successfully 'kill' the Agent randomly - we may not be able to test this.  I'll research and post back as possible, but for now we can assume the Engineering team's' tests may have to suffice along with any unit tests, etc.

**Comment by blakerouse** [comment]
@EricDavisX Testing with Endpoint Security off is really the best way to test, without the Endpoint Security integration you will be able to kill -9 agent

**Comment by EricDavisX** [comment]
That is an excellent point!  Tho, it precludes us testing that Endpoint is successfully rolled-back.

**Comment by rahulgupta-qasource** [comment]
Hi @blakerouse /@EricDavisX

Thank you for sharing the feedback.

As per [above comment](https://github.com/elastic/beats/issues/22993#issuecomment-746187529) , we are successfully able to kill the 7.11-snapshot agent with Endpoint Security OFF using:-

`sudo kill -9 {PID} where PID is a process ID of /Library/Elastic/Agent/elastic-agent`

on 8.0.0-snapshot cloud environment. However, agent is not successfully rolled back.

Please share the exact steps or build number to verify the same.

**Comment by EricDavisX** [comment]
we will leave this for the automation to cover.  we can close it out
