### ISSUE TITLE
Official Docker image for Filebeat

### ISSUE THREAD

**Issue by mkuzmin** [elastic/beats#2300]
Please create an official image on Docker Hub for Filebeat, the same way, as we use images for [Elasticsearch](https://hub.docker.com/_/elasticsearch/), [Logstash](https://hub.docker.com/_/logstash/), and [Kibana](https://hub.docker.com/_/kibana/).

**Comment by ruflin** [comment]
@mkuzmin It is important to note, that the images you linked for ES, LS, KB are not official images from Elastic.

**Comment by mkuzmin** [comment]
Yeah, I see, there is no mention of Docker at https://www.elastic.co/downloads.

But we, your users, don't really care: `Docker Inc.` said the repos are official - that's enough, we're good to go :)

![image](https://cloud.githubusercontent.com/assets/712402/17828128/89cec322-6691-11e6-9ae5-0d413deae63e.png)

Now you have to communicate `not official images from Elastic` message to the rest of the world.

Docker Hub is a well-known and reliable repository, so the are two options:
- Adopt the images, and make them officially supported,
- or contact Docker Inc, and get rid of `official` label from these pages.

**Comment by willfarrell** [comment]
I've been running https://hub.docker.com/r/willfarrell/filebeat/ for quite some time. I would love to have an official repo I could use instead. Having Elastic maintain them would be amazing.

**Comment by danielcondemarin** [comment]
+1

**Comment by andrewkroh** [comment]
Info about our official images can be found in [elastic/beats-docker](https://github.com/elastic/beats-docker). We will be updated the docs to point to these soon. At the moment they are to be considered alpha, so please test them but don't put them info prod just yet.

**Comment by dedemorton** [comment]
We've merged that PR that adds documentation for the official docker images: https://github.com/elastic/beats/pull/4312.

**Comment by tsg** [comment]
I think we can close this one, since we do provide official docker images now.

**Comment by willfarrell** [comment]
For those skimming this thread: The image uses `centos:7` as it's base. `alpine` has been requested https://github.com/elastic/beats-docker/issues/12
