### ISSUE TITLE
Add field `kubernetes.volume.fs.used.pct` for used storage

### ISSUE THREAD

**Issue by davelosert** [elastic/beats#23016]
## Feature Description

It would be great if there was an acutal value for the percentage of used storage for a Kubernetes-Volume.
That would be a simple calculation with the existing data:

```go
volumeEvent.put("fs.used.pct", volume.UsedBytes / volume.CapacityBytes)
```
*(i'm not very good with Go, so I'm not sure if this is a 100% correct):*

Much like it is done for `CPU` or `Memory` in some other metrics, e.g. for [pods](https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/pod/data.go#L121).

## Use Case

Our Use-Case would be a simple montoring of the used storage and an alert when a certain threshold is hit.

For example as soon as more than 90% of storage of any volume is used, we want an alert so we can take the appropriate action (delete data, extend the volume etc.).

AFAIK, an Alert like this is currently neither possible with `X-Pack` nor with `Elastalert` (at least not without extension) as they do not natively offer calculations.

It would also make it way easier to create a used-storage-visualization.

**Comment by ChrsMark** [comment]
@sorantis do you think this is sth we can add? I already opened a PR for this (#23564) but wanted your feedback to verify if this field is actually of sense or it could be calculated on the fly at kibana visualisations/alerts for instance.

**Comment by sorantis** [comment]
@ChrsMark LGTM
