### ISSUE TITLE
[Ingest Manager]: ECS version is different at endpoint and elastic-agent logs.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#23067]
Kibana version:
Kibana:8.0.0 snapshot Cloud environment

Elasticsearch version:
Elasticsearch:  8.0.0 snapshot Cloud environment  

Host OS and Browser version:
Windows 10, All

Original install method (e.g. download page, yum, from source, etc.):
8.0.0 snapshot Cloud environment 

Description
[Ingest Manager]: ECS version is different at endpoint and elastic-agent logs.

Preconditions
1. Artifacts for 8.0.0 snapshot Agent should be available.
Link used: https://snapshots.elastic.co/8.0.0-5823f363/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip
2. 8.0.0 snapshot Cloud environment should be available.
BUILD 38728
COMMIT f2d961df6a5f78807dc2ef265aaba3c96d691881
3. Agent must be deployed using default policy.
4. System and endpoint security integration should be added to Default policy.

Steps to reproduce:

1. Login to Kibana cloud environment.
2. Go to Agents tab. Observe, logs are generated successfully foe elastic agent and endpoint security.
3. RDP to enpoint.
4. Go to agent logs at location 'C:\Program Files\Elastic\Agent\data\elastic-agent-deba31\logs'
5. Open 'elastic-agent-json' log file and look for ecs version. Value displayed as "ecs.version":"1.6.0"
5. Now, go to Endpoint logs at location 'C:\Program Files\Elastic\Endpoint\state\log'.
6. Open log file 'endpoint-000000' and look for for ecs version. Value displayed as "ecs":{"version":"1.5.0"}

Reference ticket Id:
https://github.com/elastic/beats/pull/22987

Actual Result
 ECS version is different at endpoint and elastic-agent logs.

Expected Result
 ECS version should be same at endpoint and elastic-agent logs.

What's working
N/A

What's not working
N/A

Screenshot: 
![ecs_version_error](https://user-images.githubusercontent.com/72375798/101783438-49ea0d80-3b20-11eb-9bf6-3bb0e37d7964.png)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

While performing exploratory testing today on 7.11 Bc7 Kibana cloud build, we have observed same issue on 7.11Bc build as well.

- ECS version is different at endpoint and elastic-agent logs.
- Elastic agent logs has ecs version 1.6.0
- endpoint logs has ecs version 1.5.0

**Logs file:**
[elastic-agent-json.log](https://github.com/elastic/beats/files/5943434/elastic-agent-json.log)
[endpoint-000000.log](https://github.com/elastic/beats/files/5943436/endpoint-000000.log)

**Build details:**
```
BUILD 37897
COMMIT 3f71ce7177a41e067ddb1e670ec4ace5f6d4f5fe
Artifact link:  https://staging.elastic.co/7.11.0-1f38d552/summary-7.11.0.html
```

Please let us know if anything is required from our side.

Thanks 
QAS

**Comment by ph** [comment]
I am not considering this a big issue each process is responsible for its own log format, we aren't talking about a major version bump so the minor difference should be fine and reflect exactly the format of the data.

@ferullo sending this your way, we will need to figure out a process.

**Comment by ferullo** [comment]
I'll comment back once this is updated in 7.11.1

**Comment by EricDavisX** [comment]
@ph @ferullo As the ECS versions are allowed to be different, although we do attempt to keep the version used fairly current should we just close this I guess?  

That is, unless there is immediate action we need to take or process enhancement / documentation to make on either side.

**Comment by ferullo** [comment]
Oh worry, I never commented back. Endpoint was bumped to 1.6.0. I agree with you though Eric, from what I understand, I don't think there is a reason that all data providers managed by Agent need to set the same ECS version. In fact, I wouldn't consider it a bug if the ECS version is different for different documents generated by the same source (e.g. Endpoint). AFAIK the ECS version only applies to the document it is in, so there's no same-version-correlation expected across documents.

Maybe I'm wrong?

**Comment by ruflin** [comment]
I think it is totally fine that different inputs use different versions of ECS. In the future I expect it will be the integration that defines the ECS version it uses and not the input so things might diverge further. 

We should aspire to use the most recent version of ECS in all the places we control.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX @ruflin @ferullo 

Thanks for the Feedback on current behavior. As per above feedback we are closing this out.
