### ISSUE TITLE
Suggestion move the "installation layout" as the same level as the "Install Elastic Agent"

### ISSUE THREAD

**Issue by ph** [elastic/beats#23073]
Reported by @skh 

Move [Installation layout](https://www.elastic.co/guide/en/fleet/7.10/elastic-agent-installation.html) at the same level of "Install Elastic Agent"

**Comment by ph** [comment]
@dede what do you think?

**Comment by dedemorton** [comment]
Yup. Closing because this is already addressed. It wasn't on our project board, though, so this issue slipped through the cracks. :-/
