### ISSUE TITLE
Filebeat config/TestReadConfig2

### ISSUE THREAD

**Issue by csdrane** [elastic/beats#2309]
I'm new to the beats codebase and am wondering whether test `TestReadConfig2` in `filebeat/config` is working as intended. Namely, it seems that `cfgfile.Read()` on line 23 isn't working correctly. A println reveals that config is unpacked to "zero" values, with an empty Prospectors list. Similarly, if I make a small edit to the yml file and set spool size to 1 the test will still pass (and vice versa). It seems that the way to fix this is to change line 20 `config := &Config{}` to `config := &struct{ Filebeat Config}{}`. It's not super clear to me why exactly this wrapper is necessary -- would appreciate if someone could explain the reason for this and the relevant part of the unpacking code. Let me know if I should add this to the github issue tracker.

This is based on commit f3f55c4ef8d99ad620f0882f8b55c0caf1d40795 in the master branch.

I posted the above on discuss.elastic.co yesterday but feel like it was the wrong place for it.

**Comment by ruflin** [comment]
@csdrane Only had a quick look but I think you stumbled over and outdated test which is by accident still working. We replaced most of our internal config with the `go-ucfg` project which does now all the magic: https://github.com/elastic/go-ucfg

Do your question: Why is the filebeat prefix needed to make the test working: The config file is `filebeat.prospectors.*`. This prefix you also see on line 87 and is also added by go-ucfg. 

The conclusion from my side is that these obsolete tests should be removed and in case needed, some new more accurate tests should be added.

Does this help?

**Comment by csdrane** [comment]
That doesn't actually address my question but I'm OK closing out this issue.

**Comment by ruflin** [comment]
@csdrane Reopening the issue as I think we should remove these obsolete tests. Can you please also reiterate your question as I assume I answered it in my second paragraph?

**Comment by csdrane** [comment]
My question pertains to `config.Unpack()`. In the failing test, `config.Unpack()` gets called during the call to `config.Read()`. For me as an outsider, the type of struct that `config.Unpack()` requires is nonobvious. Further, it appears to me that the reason why the test fails is because an incorrect struct is being passed. It seems that the way to fix this is to change line 20, `config := &Config{}` to `config := &struct{ Filebeat Config}{}`. My question is why `config.Unpack()` was written such that the latter is necessary. I didn't see any documentation on the proper way to call this method other than it being used in some of the example code.
