### ISSUE TITLE
Add support for newer Kafka versions

### ISSUE THREAD

**Issue by ggml1** [elastic/beats#23093]
**Describe the enhancement:**

Add support for newer Kafka versions. I'm currently using Filebeat and it only offers support for versions up to 2.2.1, which seems to be outdated for a little more than a year.

**Describe a specific use case for the enhancement or feature:**

Most Kafka operators and tools we've tried to use require newer versions. Since my use case is in AWS, we could use an older version on AWS's MSK, but it lacks some features which are present in newer versions and are required for our use case.

**Comment by jlind23** [comment]
Backlog grooming: Not relevant anymore.
