### ISSUE TITLE
Loadbalance Filebeat with a single host

### ISSUE THREAD

**Issue by yissachar** [elastic/beats#2310]
I have multiple Logstash instances provisioned behind a load-balancer. If I point Filebeat to the load-balancer DNS, it will resolve to one of the Logstash instances and then maintain that connection for as long as it is valid. This means that Filebeat will always send logs to that particular Logstash, even though I may have several other Logstash instances sitting around doing nothing.

It would be great if Filebeat could loadbalance in this scenario, perhaps by resolving the host several times. 

One workaround I've found is to specify the same host multiple times:

```
hosts: ["myhost", "myhost"]
loadbalance: true
```

Which causes Filebeat to resolve `myhost` twice and loadbalance across the resulting IPs. This isn't an ideal solution though, for a few reasons:
1. `myhost` can resolve to the same IP, which would mean no loadbalancing
2. The number of Logstash instances I have is dynamic, so either I will be underutilizing them if I don't repeat `myhost` enough times, or I have to repeat `myhost` enough times to cover the hypothetical maximum number of instances (and in this case I believe it would be inefficient, if this causes Filebeat to open multiple connections to the same Logstash host, when multiple `myhost` resolves to the same IP) 
3. It's hacky

**Comment by yissachar** [comment]
Just found https://github.com/elastic/beats/issues/661 which seems to another way of solving this problem.

**Comment by danielmotaleite** [comment]
I'm also with this problem, but the multiple `myhost` do not work for me, my dns is returning the same dns, so i have 3 connection, all to the same host... not very useful :(

I would say that with `loadbalance` is `true`, the beat should resolve all all the dns and use then.

**Comment by danielmotaleite** [comment]
By  https://discuss.elastic.co/t/load-balancing-with-a-single-logstash-output/55756/3, increasing the number of workers, i still only get connections to the same IP. Either 5.6.5 do not like my dns (consul) or it is not resolving multiple IPs
