### ISSUE TITLE
Recommend ECS logging in Filebeat docs

### ISSUE THREAD

**Issue by felixbarny** [elastic/beats#23115]
We're currently working towards GA'ng [ECS logging](https://www.elastic.co/guide/en/ecs-logging/overview/master/intro.html) for 7.11.

We should link to the ECS docs from the Filebeat docs in order to promote the project. The [quick start](https://www.elastic.co/guide/en/beats/filebeat/7.10/filebeat-installation-configuration.html) guide seems to be an appropriate place for that.

**Comment by andresrc** [comment]
@urso ok to this?

**Comment by urso** [comment]
I'm okay with that. Filebeat has a set of [How-To-Guides](https://www.elastic.co/guide/en/beats/filebeat/7.10/howto-guides.html) as well. Would it make sense to add dedicated documentation there as well? Any plans to provide a specialized filebeat module?

**Comment by urso** [comment]
@dedemorton WDYT?

**Comment by felixbarny** [comment]
> Filebeat has a set of How-To-Guides as well. Would it make sense to add dedicated documentation there as well?
++

> Any plans to provide a specialized filebeat module?

You mean for ECS loggers? There's a plan to auto-detect ECS logs so that no special config is required.

**Comment by dedemorton** [comment]
Yes I think a topic in the how-to section makes the most sense.

**Comment by felixbarny** [comment]
Closed via https://github.com/elastic/beats/pull/23791
