### ISSUE TITLE
[Kubernetes] Leverage higher's resource updates to keep metadata and hints-based configurations in sync

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#23139]
**Describe the enhancement:**
Update pod's metadata, and related hints-based configurations when node metadata or namespace metadata getting updated.

**Describe a specific use case for the enhancement or feature:**
(from a @jsoriano 's old comment):
An issue we have is that namespace metadata and hints are used when available when a pod is created or updated. But, if the namespace is modified, its metadata is not updated in pods events, and hints-based autodiscover is not retriggered. Pods need to be updated so the info from its namespaces is leveraged.
Perhaps we could have higher-level watchers and indexers that keep all the related metadata on sync, and this wouldn't be optional. E.g. the higher level pod watcher/informer would always internally have watchers/informers for pods, nodes and namespaces and would trigger updates with all the data if any of them change. The watcher used in `add_kubernetes_metadata` should do the same.

**Comment by ChrsMark** [comment]
This is fixed for namespaces at https://github.com/elastic/beats/pull/25117. @jsoriano I guess the same approach could be used for node's metadata too, right? If so we can work on it and completely fix this.

**Comment by jsoriano** [comment]
> This is fixed for namespaces at #25117. @jsoriano I guess the same approach could be used for node's metadata too, right? If so we can work on it and completely fix this.

Yes, in principle the same approach could be used for other related metadata. Thanks!
