### ISSUE TITLE
[Filebeat] json.expand_keys conflict behaviour should be configurable

### ISSUE THREAD

**Issue by axw** [elastic/beats#23135]
**Describe the enhancement:**

https://github.com/elastic/beats/pull/22849 introduced a new `json.expand_keys` option which recursively de-dots object keys, producing a hierarchical object structure.

If two keys expand to the same path (e.g. `a.b: 1` and `a: {b: 2}`), then JSON decoding will fail.

**Describe a specific use case for the enhancement or feature:**

There may be use-cases where failing on conflicts is undesirable. We should consider either making the behaviour configurable, and/or changing this default behaviour. For example, we might rename one of the keys as described in https://github.com/elastic/beats/pull/22849#discussion_r540213668.

**Comment by jlind23** [comment]
Backlog grooming: Closing until further needs.
