### ISSUE TITLE
Move Filebeat HTTP endpoint to GA

### ISSUE THREAD

**Issue by narph** [elastic/beats#23144]
All the beats support the monitoring feature https://www.elastic.co/guide/en/beats/filebeat/current/monitoring.html and one of the supported options is using metricbeat:  https://www.elastic.co/guide/en/beats/filebeat/current/monitoring-metricbeat-collection.html there is no experimental warning despite this method relies on the HTTP endpoint feature.

HTTP endpoint is used by several others GA components should it also be moved to GA?

**Comment by exekias** [comment]
Looping @urso, any thoughts?

**Comment by urso** [comment]
> any thoughts?

Stack monitoring already relies on the HTTP endpoint. Thinking about diagnostics we will also need to provide some RPC for the tool to collect internals.

For the HTTP endpoint we can make it GA, also moving the `/stats` and `/state` URLs into GA. Moving the endpoint to GA means we also need to document the supported paths, which I think is incomplete today.

Having the HTTP endpoint GA means that we want to switch granularity for the different paths. Currently we have `/`, `/stats`, `/state`, and `/dataset`. See: https://github.com/elastic/beats/blob/master/libbeat/api/routes.go#L37

I'd prefer to keep `/dataset` as experimental today and document the others as GA.
