### ISSUE TITLE
[Agent] Enabling elastic-agent system service fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by fkelbert** [elastic/beats#23159]
OS: Ubuntu 20.04.1
Elastic Agent: 7.10.1

Following the [Elastic Agent install guide](https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html) (DEB package):

```
curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.10.1-amd64.deb
sudo dpkg -i elastic-agent-7.10.1-amd64.deb
sudo elastic-agent enroll <kibana_url> <enrollment_token> 
```

Starting `elastic-agent` using `sudo systemctl enable elastic-agent ` is successful.

However, enabling the `elastic-agent` as system service fails:

```
$ sudo systemctl enable elastic-agent
Synchronizing state of elastic-agent.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable elastic-agent
update-rc.d: error: elastic-agent Default-Start contains no runlevels, aborting.
```

**Comment by hermlam** [comment]
Exact same issue here

**Comment by biastogit** [comment]
I solved this issue by locating and updating the script  /etc/init.d/elastic-agent like this:

added on line 2

\### BEGIN INIT INFO
\# Default-Start:     2 3 4 5
\### END INIT INFO


once done, the command _systemctl enable elastic-agent_  finished without errors.

\# systemctl enable elastic-agent
Synchronizing state of elastic-agent.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable elastic-agent
\#

Hope it helps :-)

**Comment by hermlam** [comment]
It did help! Thanks.

Herman

**Comment by sreehari3** [comment]
what u added on line 2

**Comment by sreehari3** [comment]
> I solved this issue by locating and updating the script /etc/init.d/elastic-agent like this:
> 
> added on line 2
> 
> ### BEGIN INIT INFO
> # Default-Start: 2 3 4 5
> ### END INIT INFO
> 
> once done, the command _systemctl enable elastic-agent_ finished without errors.
> 
> # systemctl enable elastic-agent
> Synchronizing state of elastic-agent.service with SysV service script with /lib/systemd/systemd-sysv-install.
> Executing: /lib/systemd/systemd-sysv-install enable elastic-agent
> #
> 
> Hope it helps :-)

what u added on line 2

**Comment by faec** [comment]
Looks like this is obsolete.
