### ISSUE TITLE
Certificate validation fails on Windows 2012

### ISSUE THREAD

**Issue by blakerouse** [elastic/beats#23172]
## Issue

On Windows 2012 certificate validation against a custom signed certificate for an IP address fails. This seems to be a core issue with Windows API in 2012 with the golang library. https://github.com/golang/go/issues/37176

This seems to be related to the fact that certificate validation is against an IP address and not against a domain.

## Workaround

Possible workaround would be to communicate to the host from Windows 2012 using a hostname with the certificate generated using the hostname instead of an IP address. This still needs to be verified.

Original discuss question: https://discuss.elastic.co/t/error-installing-elastic-agent-v7-10-0/258140/2

**Comment by ph** [comment]
@urso will you update the know issues with that problem?

**Comment by urso** [comment]
> will you update the know issues with that problem?

Sure.

**Comment by jlind23** [comment]
Backlog grooming: Closing until further needs.
