### ISSUE TITLE
Filebeat logstash module pipeline not correct for some types of logs

### ISSUE THREAD

**Issue by eedugon** [elastic/beats#23171]
Component affected: Logstash module of Filebeat
Version: 7.10.0

The pipeline created by Logstash module inside filebeat is valid for the majority of Logstash logs but not for all of them.
The current code of the `plaintext pipeline` includes (taken directly from Elasticsearch installed pipeline)

```
    patterns:
    - \[%{TIMESTAMP_ISO8601:logstash.log.timestamp}\]\[%{LOGSTASH_LOGLEVEL:log.level}\s?\]\[%{LOGSTASH_CLASS_MODULE:logstash.log.module}\s*\]\[%{NOTSPACE:logstash.log.pipeline_id}\]
      %{GREEDYMULTILINE:message}
    - \[%{TIMESTAMP_ISO8601:logstash.log.timestamp}\]\[%{LOGSTASH_LOGLEVEL:log.level}\s?\]\[%{LOGSTASH_CLASS_MODULE:logstash.log.module}\s*\]
      %{GREEDYMULTILINE:message}
```

This works fine with log lines like:
```
[2020-11-26T18:09:47,441][INFO ][logstash.outputs.elasticsearch][obaa-ios-logs-monitoring-non_live-logstash] ES Output version determined {:es_version=>7} 
```

But for this type of logs (note that we have at least 1 extra field before the space) it fails:
```
[2020-11-26T18:09:50,378][INFO ][org.apache.kafka.clients.consumer.internals.SubscriptionState][obaa-ios-logs-monitoring-non_live-logstash][1acd40c2e83d105b973d0ad46a0233bd9a1a0057ded12af60b224a97f43eb531] [Consumer clientId=logstash-0, groupId=logstash-obaa-ios-logs-monitoring-non_live-logstash-0] Resetting offset for partition obaa-ios-logs-monitoring-non_live-logstash-2 to offset 0.
```

When this type of line comes, the problem is that the generated `logstash.log.pipeline_id` will have the value `obaa-ios-logs-monitoring-non_live-logstash][1acd40c2e83d105b973d0ad46a0233bd9a1a0057ded12af60b224a97f43eb531` instead of the expected `obaa-ios-logs-monitoring-non_live-logstash`.

That is really an issue because we can't keep track of pipeline_ids properly (they should be consistent across all events), so it looks like a bug.

I checked with @colinsurprenant from LS team and in the previous example, the field `1acd40c2e83d105b973d0ad46a0233bd9a1a0057ded12af60b224a97f43eb531` corresponds to the autogenerated `plugin ID`.

The processing expectation should be:
- Pipeline ID value has to be `obaa-ios-logs-monitoring-non_live-logstash` (the main issue)
- The other fields could go towards new fields or directly to be considered part of the `message` (up to you to decide)

Here you have a proposal for the fix (it should be fully tested):

- I have created an extra `pattern_definition` called `NOTSPACENOTBRACKETS` and then added a `pattern` at the beginning of the list of patterns:

```
     # In pipeline format, it should be changed to the internal code of the module
      "pattern_definitions" : {
        "NOTSPACENOTBRACKETS" : """[^\t\n\v\f\r \[\]]+""",
      }
```

```
# Final pipeline format, with double escapes
"\\[%{TIMESTAMP_ISO8601:logstash.log.timestamp}\\]\\[%{LOGSTASH_LOGLEVEL:log.level}\\s?\\]\\[%{LOGSTASH_CLASS_MODULE:logstash.log.module}\\s*\\]\\[%{NOTSPACENOTBRACKETS:logstash.log.pipeline_id}\\]\\[%{NOTSPACE:logstash.log.plugin_id}\\] %{GREEDYMULTILINE:message}"

# devtools format (single escapes)
\[%{TIMESTAMP_ISO8601:logstash.log.timestamp}\]\[%{LOGSTASH_LOGLEVEL:log.level}\s?\]\[%{LOGSTASH_CLASS_MODULE:logstash.log.module}\s*\]\[%{NOTSPACENOTBRACKETS:logstash.log.pipeline_id}\]\[%{NOTSPACE:logstash.log.plugin_id}\] %{GREEDYMULTILINE:message}
```

With this extra pattern (at the beginning of the list) the result would be:
- `logstash.log.pipeline_id`: "obaa-ios-logs-monitoring-non_live-logstash" --> __Correct__
- `logstash.log.plugin_id`: "1acd40c2e83d105b973d0ad46a0233bd9a1a0057ded12af60b224a97f43eb531" --> __NEW FIELD__, note that it's __not in the mapping__.
- `message`: "[Consumer clientId=logstash-0, groupId=logstash-obaa-ios-logs-monitoring-non_live-logstash-0] Resetting offset for partition obaa-ios-logs-monitoring-non_live-logstash-2 to offset 0."

In this case, my decision / proposal was to store the plugin_id in a new field and the rest as part of the message. Of course we could avoid creating a new field that probably needs to be included in the mapping and keep everything after the pipeline_id in the message.

**Comment by smith** [comment]
Closing this. Not prioritizing at this time.
