### ISSUE TITLE
Re-check Rules in Kernel against desired rules

### ISSUE THREAD

**Issue by ndubss** [elastic/beats#23184]
A running auditbeat instance does not ever re-check the loaded kernel rules against the desired ruleset. We are trying to work towards deploying immutability but our rules are changing quite frequently. 

If an attacker is able to gain access to auditctl tools or launch a pod in the right namespace, they can issue an 'auditctl -D' and auditbeat will continue to run as if healthy. This will clear all rules from the kernel and kill any associated monitoring. Luckily there is one last event shipped before the kernel clears rules.

Please consider an enhancement request to recheck loaded rules against desired rules. We do have another enhancement request open to add auditd rules to config reloader, but I'm not sure it will check whats in kernel every time.
https://github.com/elastic/beats/issues/8556

**Comment by andrewstucki** [comment]
@ndubss -- not entirely sure your use-case, but just trying to understand this piece of your comment:

> We are trying to work towards deploying immutability but our rules are changing quite frequently.

Are you more concerned with making sure the particular ruleset is enforced periodically, or would exposing the ability to set auditd rules immutably via auditbeat configuration fit your use-case? We added the ability to set immutable rules some time ago in the library that auditbeat uses to do much of the heavy lifting in the underlying audit-framework integration -- it's just not currently exposed in auditbeat.

https://github.com/elastic/go-libaudit/pull/68

**Comment by ndubss** [comment]
@andrewstucki We want to adopt immutability longer term. It's not currently supported, as you mentioned the ongoing work but we are aware that auditbeat intends to support this. 

For us, we deploy new rules often, so even if we are able to deploy immutability, we need a mechanism to reboot all the nodes in each cluster before rules will change. For these few reasons, we don't use immutability yet. Because auditbeat does not recheck rules in the kernel after starting, rules could be cleared from kernel and service will continue running as if healthy. 

Wondering if we can incorporate this into: https://github.com/elastic/beats/pull/10835

@BrookHF
