### ISSUE TITLE
Filebeat udp input: Support line_delimiter option

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#23195]
**Describe the enhancement:**

Add a `line_delimiter` option to `udp` input (same as in [tcp input](https://www.elastic.co/guide/en/beats/filebeat/7.10/filebeat-input-tcp.html#filebeat-input-tcp-tcp-line-delimiter)). So that udp packets containing more than one message can be supported.
 
**Describe a specific use case for the enhancement or feature:**

For example, Squid likes to squeeze multiple lines in a single UDP packet. See http://squid-web-proxy-cache.1019090.n4.nabble.com/Squid-logging-to-UDP-logs-multiple-lines-at-the-same-time-td4685384.html

**Comment by AYDEV-FR** [comment]
Hi
You're talking about TCP and UDP sending of logs,
I have the same error with the "file" version, in /var/log/squid/access.log

Have you found a way to solve the problem?

Here's my log error : 
```
    ERROR        [processor.javascript]        console/console.go:54        extract_page failed for 'http://aydev.fr/'
```

**Comment by nebriv** [comment]
I am also have this exact issue as stated by @AYDEV-FR:

filebeat[60700]: 2022-01-27T11:54:51.799-0500 ERROR [processor.javascript] console/console.go:54 extract_page failed for 'arstechnica.com:443'

1643302491.246      0 172.18.8.206 TCP_DENIED/200 0 CONNECT arstechnica.com:443 - HIER_NONE/- -
