### ISSUE TITLE
[Elastic Agent] Work todo for communication with new Fleet Server

### ISSUE THREAD

**Issue by blakerouse** [elastic/beats#23205]
## Overview

Elastic Agent communication to the new [elastic/fleet-server](https://github.com/elastic/fleet-server) does require some changes to the Fleet gateway code. This is a minimal change that should allow Elastic Agent to communicate with either Kibana or a Fleet Server if done correctly.

## Items to do

- [x] Save and send the check-in action token (this is now used to determine what actions the Agent has or has not received)
- [ ] Add HTTP2 communication. Agent should now always try to use HTTP2 first, as this provides a performance benefit of having less TCP connections to Fleet Server.

## Why

Reduce the TLS load and cloud already support HTTP2, this should be simple addition and it should degrade easily.

**Comment by nchaulet** [comment]
@blakerouse I think the agent should know how to talk both to Kibana and Fleet Server if we want to provide the best migration path possible, there is two options here: 
* Kibana could support the fleet server API for agent > 7.x
* The agent could know if he is talking to Fleet Server or Kibana (I have a preference for this one, as we do not have a good API versioning strategy on Kibana)

**Comment by blakerouse** [comment]
@nchaulet I think we can do that without Agent having to worry about which it is talking to.

If we do the following we can remove the need to adjust Agent:

- If when communicating a checkin token is returned then Agent records it and sends it next time. If not its ignored and not sent next time.
- Add the `error` field to `/acks` on kibana side (basically just to ignore acks with errors).
- Agent fallsback from HTTP2 to HTTP/1.1 (standard golang stuff)

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

Cloud you please provide Acceptance criteria for same to validate the ticket.

Thanks
QAS

**Comment by EricDavisX** [comment]
@ph @blakerouse I will pass the request on to you!  If you wish to cite AC we can test against along with notes on which parts are already covered in Unit or e2e tests that would be nice.

**Comment by ph** [comment]
@blakerouse I know we have discussed this together, wdyt if @michel-laterman take it over?
