### ISSUE TITLE
Different Agents versions are not upgradable to 8.0 Kibana cloud build from 'upgrade Agent' option available on Fleet UI.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#23222]
Kibana version:
Kibana: 8.0.0 snapshot Kibana Cloud environment  

Elasticsearch version:
Elasticsearch:  8.0.0 snapshot Kibana Cloud environment  

Host OS and Browser version:
Windows 10, All

Original install method (e.g. download page, yum, from source, etc.):
 8.0.0 snapshot Kibana Cloud environment  

Description
[Ingest Manager]: Different Agents versions are not upgradable to 8.0 Kibana cloud build from  'upgrade Agent' option available on Fleet UI.

Preconditions
1.  8.0.0 snapshot Kibana Cloud environment should be available.
BUILD 39128
COMMIT 0d9b40dfef0acaf6d3848c3f67784ca5b9665e37
Artifact link: 
Agent 7.10.0 : https://www.elastic.co/downloads/past-releases/elastic-agent-7-10-0
Agent 7.10.1: https://www.elastic.co/downloads/past-releases/elastic-agent-7-10-1
Agent 7.11: https://staging.elastic.co/7.11.0-710164a0/summary-7.11.0.html
2. Different versions Agent should be installed say: 7.10.0, 7.10.1, 7.11

Steps to reproduce:
1. Login to Kibana cloud environment.
2. Go to Agents tab. Observe 'upgrade available' option is displayed for above agents.
3. Notice, Select check box for bulk actions.
4. Select 'Upgrade agents' option.
5. Provide confirmation on notification.
6. Notice, upgrading agents notification pops up .
7. Wait for 4-5 secs and Observe, Agents all change to healthy state without upgrading.

Logs generated at Agents logs UI
```
17:59:35.053
elastic_agent
[elastic_agent][info] 2020-12-21T07:29:26-05:00: type: 'STATE': sub_type: 'UPDATING' message: Application: [b0fa9b90-4384-11eb-9588-6730baac3a20]: State changed to UPDATING: Update to version '8.0.0-SNAPSHOT' started
17:59:35.095
elastic_agent
[elastic_agent][error] 2020-12-21T07:29:34-05:00: type: 'ERROR': sub_type: 'FAILED' message: Application: [b0fa9b90-4384-11eb-9588-6730baac3a20]: State changed to FAILED: failed verification of agent binary: 3 errors occurred:
	* fetching asc file from 'C:\Program Files\Elastic\Agent\data\elastic-agent-fc48a3\downloads\elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\Program Files\Elastic\Agent\data\elastic-agent-fc48a3\downloads\elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: The system cannot find the file specified.
	* check detached signature: openpgp: invalid signature: hash tag doesn't match
	* fetching asc file from https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404: /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/artifact/download/http/verifier.go[211]: unknown error
17:59:35.095
elastic_agent
[elastic_agent][error] failed to dispatch actions, error: failed verification of agent binary: 3 errors occurred:
	* fetching asc file from 'C:\Program Files\Elastic\Agent\data\elastic-agent-fc48a3\downloads\elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\Program Files\Elastic\Agent\data\elastic-agent-fc48a3\downloads\elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: The system cannot find the file specified.
	* check detached signature: openpgp: invalid signature: hash tag doesn't match
	* fetching asc file from https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404: /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/artifact/download/http/verifier.go[211]: unknown error
17:59:35.095
elastic_agent
[elastic_agent][warn] Elastic Agent status changed to: 'degraded'
17:59:35.095
elastic_agent
[elastic_agent][info] Elastic Agent status changed to: 'online'
```

Reference ticket Id:
N/A

Actual Result
Agents are not upgradable to 8.0 Kibana Cloud successfully.

Expected Result
Agents should upgrade to 8.0 Kibana Cloud successfully.

What's working
Agent shows up as healthy without complete upgrade.

What's not working
Notification for unsuccessful upgrade should be displayed.

Screenshot: 
![AgentsnotUpgradable](https://user-images.githubusercontent.com/72375798/102778304-5855e600-43b8-11eb-9d80-79e50e21214f.jpg)

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@michalpristas I don't recall any spec about not being able to upgrade multiple Agent versions simultaneously, can you confirm / remind?  It is likely to happen in production over time.  So, we could think about fixing this for GA or at least better documenting it - thoughts?

**Comment by michalpristas** [comment]
this looks like build timing issue we've seen before @EricDavisX 
from logs we can see SNAPSHOT build is downloaded and then agent tries to verify hash and signature but this fails on hash checksum mismatch. downloaded binary is not the same as hash says.

in the logs we see that first it tries to find asc locally. this is not there.
then second try, it downloaded snapshot.asc from snapshot repo. it failed on verification
third try is downloading snapshot.asc from official repo. it fails on 404 as expected. 

i would check local machine for some artifacts, maybe there is something pre-existing, some snapshot package whcih is older. although agent should delete those after unsuccessful upgrade.

**Comment by EricDavisX** [comment]
we can test again for sure, with known working Agent versions (individually upgradeable) and then we can run them together.

**Comment by ph** [comment]
I think this is fixed, closing this.

**Comment by dikshachauhan-qasource** [comment]
Hi @ph @EricDavisX 

We have attempted to upgrade 7.11BC8 agent upgrade scenario on 8.0 snapshot Kibana Cloud build and was able to upgrade agent successfully.

Artifact link: https://staging.elastic.co/7.11.0-657c0367/summary-7.11.0.html

Thanks
QAS
