### ISSUE TITLE
Agent process is successfully killed on Windows 8.1 x64 bit when Endpoint Security is enabled in its policy

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#23223]
**Kibana version:**
Kibana: 8.0.0-SNAPSHOT Kibana cloud environment

**Elasticsearch version:**
Elasticsearch: 8.0.0-SNAPSHOT cloud environment

**Host OS and Browser version:**
Windows 8.1 x64, All

**Original install method (e.g. download page, yum, from source, etc.):**
8.0.0-SNAPSHOT Kibana cloud environment from https://staging.found.no

**Description**
Agent process is successfully killed on Windows 8.1 x64 bit when Endpoint Security is enabled in its policy

**Preconditions**
1. 8.0.0-SNAPSHOT Kibana cloud environment(with commit 0d9b40dfef0acaf6d3848c3f67784ca5b9665e37) should be available.
2. Login into the above Kibana environment with 'elastic' superuser.
3. 8.0.0-SNAPSHOT version windows-x86_64.zip agent should be installed with Default policy on Windows 8.1 x64 bit on above kibana :-
Agent download location: https://snapshots.elastic.co/8.0.0-f82b4eca/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip
4. Endpoint Security integration should be added in 'Default policy'.

**Steps to Reproduce**
1. RDP to the prerequisite endpoint and open cmd as admin
2. Trigger 'tasklist' command and capture elastic-agent.exe process id(say 4052)
3. Trigger cmd command:  taskkill /F /PID 4052
4. Observe that agent process is successfully killed and agent goes to Unhealthy status in Kibana.

**Test data**
N/A

**Impacted Test case id**
https://elastic.testrail.io/index.php?/cases/view/35199

**Actual Result**
Agent process is successfully killed on Windows 8.1 x64 bit when Endpoint Security is enabled in its policy

**Expected Result**
Error message "ERROR_ACCESS_DENIED" should be displayed on killing elastic-agent on Windows 8.1 x64 bit when Endpoint Security is enabled in its policy

**What's working**
 - N/A

**What's not working**
 - Issue is also occurring with macOS 10.15 x64

**Screenshot**
elastic-agent process killed and Agent goes to Unhealthy status :
![cmd_kill](https://user-images.githubusercontent.com/59917944/102785510-1f237300-43c4-11eb-99ac-597cc4fa4293.jpg)

**Logs**
N/A

**Comment by rahulgupta-qasource** [comment]
@manishgupta-qasource Please review the bug

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@ferullo any bug here would be on the Endpoint side right?  If so, please help push it on and prioritize, etc. Thx

**Comment by ferullo** [comment]
Protection of Agent hasn't been enabled in 8.0 yet. I'll post back on this issue when it has been..

**Comment by EricDavisX** [comment]
Thanks Dan, there must have been a blocking problem with using 7.11 to test, and we assumed the usual merge to master then backport process was in place.  

For testing:  We can keep all tests to 7.11 for now.  @rahulgupta-qasource @manishgupta-qasource - I commented on this in email for follow up, I'm not sure if we need to keep this Beats ticket open.  I'd like to log any new ones against the 7.11 BC 1 (or newer BC) if things are not working there.   

Please re-open if you have any questions or concerns.
