### ISSUE TITLE
Diskio metricset errors with shared drives under Windows

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#23225]
For confirmed bugs, please report:
- Version: 7.10.1
- Operating System:  Windows 2016
- Discuss Forum URL:
- Steps to Reproduce: 

 1. Run the `diskio` metricset with a shared drive (for example `net use Z: \\vboxsvr\vagrant`)
 2. The following error is printed to the logs every time the metricset is run:
 > ERROR diskio/diskstat_windows_helper.go:89 Could not return any performance counter values for \\.\Z: .Error: Incorrect function.

It could potentially just skip network drives as I understand there aren't perf counters for those, or lower the message severity.

**Comment by adriansr** [comment]
@narph @fearful-symmetry I see you've been working on this metricset lately, maybe you can take this.

**Comment by fearful-symmetry** [comment]
@narph would be best, I don't really have any knowledge of windows-specific functions that are failing out here.

**Comment by fearful-symmetry** [comment]
@narph this got fixed, right? I remember us tinkering with the disk reporting a while back. Assuming it is, and moving to backlog for now.

**Comment by narph** [comment]
@adriansr , I've recently fixed this with https://github.com/elastic/beats/pull/24502, do you encounter the same issue with 7.12.1?

**Comment by adriansr** [comment]
Hi @narph, I haven't tested this again since this issue was created. If you're confident that it was fixed then we can close.

**Comment by narph** [comment]
@adriansr. just noticed this is a different metricset, I created a similar fix for filesystem, will try to reproduce the issue and make the necessary changes, lets keep it open
