### ISSUE TITLE
Seeing error with `createEventsFromS3Info` - status code received is 200 with OK

### ISSUE THREAD

**Issue by sraju-optimizely** [elastic/beats#23226]
After I integrated Cloudflare’s audit logs with `filebeat`, I started seeing the following error:

```
ERROR   [s3]    s3/input.go:395 createEventsFromS3Info failed processing file from s3 bucket "XXXXXXXXXXX" with name "XXXXXXXXXXXXXXXXXXX_9149b6a6.json": S3 GetObjectRequest failed for 'XXXXXXXXXXXXXXXXXXX_9149b6a6.json_9149b6a6.json' from S3 bucket 'XXXXXXXXXXX': OK: OK
        status code: 200, request id: 6K1R7HBYAZCT5M4Y, host id: hrCJ7lGJpoDD6hg9vJ22Vcacy8JvZOr2fERy9lJ4JzUCs0ezR70DTzgWJnzfQWif/5SlsS0uNco=
```

Seems like the (from the error log) status code received is `200` with `OK`.  I am wondering why that is populated in `err`

https://github.com/elastic/beats/blob/5a6f830483f1010ca20713c7c7fc89b70de4f613/x-pack/filebeat/input/s3/input.go#L417

**Comment by kushagra-io** [comment]
@kaiyan-sheng  Has there been an update to this issue yet? We're experiencing the same issue as well on filebeat version 7.13.3

**Comment by kostty** [comment]
Hi @kaiyan-sheng In case this helps to debug the problem, we did some troubleshooting on our side by comparing a working setup with the one that is giving the error in the subject. For us, as soon as [object locking](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html) is enabled on a bucket, it prevents Filebeat from consuming objects.

An example of Terraform configuration that creates a bucket that produces an error:
```
resource "aws_s3_bucket" "test_bucket" {
  bucket = "test-bucket-name"
  acl = "private"

  object_lock_configuration {
    object_lock_enabled = "Enabled"

    rule {
      default_retention {
        mode = "COMPLIANCE"
        days = 5
      }
    }
  }
}
```

**Comment by aspacca** [comment]
@kostty 7.15 will ship with multiples refactoring on the AWS S3 input.
From my test on a bucket with object lock enabled (but without retention rule) the issue is not present anymore.

**Comment by kaiyan-sheng** [comment]
We will keep this issue open for now. If @kostty could give 7.15 a try, that would be great. Thanks!!

**Comment by kostty** [comment]
Hi @aspacca, @kaiyan-sheng, I've built a 7.15 version (with `mage build` in `x-pack/filebeat`) but it hasn't reached the data consumption stage, failing with a config error:

```
./filebeat -c filebeat-aws.yml -N -v -e 2>&1 | grep queue_url
2021-08-24T13:18:19.085+0200	INFO	[input.aws-s3]	awss3/input.go:176	AWS api_timeout is set to 2m0s.	{"id": "77CD613F4C8BD343", "queue_url": "https://sqs.eu-west-2.amazonaws.com/<MY_ACCOUNT>/<MY_QUEUE_NAME>"}
2021-08-24T13:18:19.085+0200	INFO	[input.aws-s3]	awss3/input.go:177	AWS region is set to eu-west-2.	{"id": "77CD613F4C8BD343", "queue_url": "https://sqs.eu-west-2.amazonaws.com/<MY_ACCOUNT>/<MY_QUEUE_NAME>"}
2021-08-24T13:18:19.085+0200	INFO	[input.aws-s3]	awss3/input.go:178	AWS SQS visibility_timeout is set to 5m0s.	{"id": "77CD613F4C8BD343", "queue_url": "https://sqs.eu-west-2.amazonaws.com/<MY_ACCOUNT>/<MY_QUEUE_NAME>"}
2021-08-24T13:18:19.085+0200	INFO	[input.aws-s3]	awss3/input.go:179	AWS SQS max_number_of_messages is set to 5.	{"id": "77CD613F4C8BD343", "queue_url": "https://sqs.eu-west-2.amazonaws.com/<MY_ACCOUNT>/<MY_QUEUE_NAME>"}
2021-08-24T13:18:19.085+0200	DEBUG	[input.aws-s3]	awss3/input.go:180	AWS S3 service name is s3.	{"id": "77CD613F4C8BD343", "queue_url": "https://sqs.eu-west-2.amazonaws.com/<MY_ACCOUNT>/<MY_QUEUE_NAME>"}
2021-08-24T13:18:19.109+0200	ERROR	instance/beat.go:989	Exiting: Failed to start crawler: starting input failed: Error while initializing input: queue_url or bucket_arn must provided accessing config
Exiting: Failed to start crawler: starting input failed: Error while initializing input: queue_url or bucket_arn must provided accessing config
```

The URL in the INFO lines above matches the URL from the supplied config file, however when it reaches `input/awss3/config.go` `c.QueueURL` apparently evaluates to empty for some reason.

If for testing purposes I define `var.bucket_arn` in addition to `var.queue_url` in the config, then `filebeat` does see the defined queue URL:
```2021-08-24T13:58:56.540+0200	ERROR	instance/beat.go:989	Exiting: Failed to start crawler: starting input failed: Error while initializing input: queue_url <https://sqs.eu-west-2.amazonaws.com/<MY_ACCOUNT>/<MY_QUEUE_NAME>> and bucket_arn <blablabla> cannot be set at the same time accessing config```

This config file worked well with v7.13.3, but from a quick look I couldn't see where the problem came from in v7.15.

**Comment by kostty** [comment]
One more thing, normally we run Filebeat on Kubernetes. So it would be nice to test v7.15 on Kubernetes as well. Where can I find a link to the Dockerfile to build a Docker image with Filebeat?

**Comment by kaiyan-sheng** [comment]
@kostty Good catch, sorry that was my mistake. I just created a PR to fix this: https://github.com/elastic/beats/pull/27575.

**Comment by kostty** [comment]
@kaiyan-sheng The PR doesn't seem to help the problem I'm seeing:
```
$ git log -n 1
commit 088a57167bd1afb6d82b97f594c6590015e46330 (HEAD, patch/awsfargate_config)
Author: kaiyan-sheng <kaiyan.sheng@elastic.co>
Date:   Tue Aug 24 13:07:01 2021 -0600

    Remove fargate from aws module config
$
$ mage build
>> build: Building filebeat
$
$ ./filebeat -c filebeat-aws.yml -N -v -e 2>&1 | grep queue_url
<...>
2021-08-25T09:25:41.894+0200	DEBUG	[input.aws-s3]	awss3/input.go:180	AWS S3 service name is s3.	{"id": "C66DD6E147B6EB0D", "queue_url": "https://sqs.eu-west-2.amazonaws.com/<MY_ACCOUNT>/<MY_QUEUE_NAME>"}
2021-08-25T09:25:41.901+0200	ERROR	instance/beat.go:971	Exiting: Failed to start crawler: starting input failed: Error while initializing input: queue_url or bucket_arn must provided accessing config
Exiting: Failed to start crawler: starting input failed: Error while initializing input: queue_url or bucket_arn must provided accessing config
$
```

It should be easy to reproduce, my config is looking like the following:
```
filebeat.modules:
- module: aws
  cloudtrail:
    enabled: true
    var.queue_url: https://sqs.eu-west-2.amazonaws.com/<MY_ACCOUNT>/<MY_QUEUE_NAME>
    var.process_cloudtrail_logs: true
    var.process_digest_logs: false
    var.process_insight_logs: false
    var.endpoint: amazonaws.com
    var.credential_profile_name: SOME_PROFILE
   
```

**Comment by aspacca** [comment]
@kostty I've identified the issue, can you confirm this config will fix the issue as a workaround?

```
filebeat.modules:
- module: aws
  cloudtrail:
    enabled: true
    var.queue_url: https://sqs.eu-west-2.amazonaws.com/<MY_ACCOUNT>/<MY_QUEUE_NAME>
    var.process_cloudtrail_logs: true
    var.process_digest_logs: false
    var.process_insight_logs: false
    var.endpoint: amazonaws.com
    var.credential_profile_name: SOME_PROFILE
    cloudwatch:
      enabled: false
    ec2:
      enabled: false
    elb:
      enabled: false
    s3access:
      enabled: false
    vpcflow:
      enabled: false
```

**Comment by kostty** [comment]
@aspacca That did it! Filebeat successfully starts now and from a quick look at the output it is indeed able to read objects from the S3 bucket. 

I will deploy it and test properly. Is there a Dockerfile I can use to rebuild the image with 7.15?

**Comment by aspacca** [comment]
@kostty you can build from docker-compose file in x-pack filebeat: https://github.com/elastic/beats/blob/master/x-pack/filebeat/docker-compose.yml

the `beat` service should be enough
