### ISSUE TITLE
Heartbeat scripting

### ISSUE THREAD

**Issue by gergof** [elastic/beats#23269]
**Describe the enhancement:**

I would like to have a fully customizable monitor.
Using this monitor you could define scripts (for example using JS with a library like [otto](https://github.com/robertkrimen/otto)) and inside the script you would have access to functions to make http requests and send tcp packages. Then the script could return the status of the monitor and if it doesn't return until the given timeout elapses, the script is killed and the monitor fails.

**Describe a specific use case for the enhancement or feature:**

It would be especially useful when the health of the service can not be checked using the http monitor.

In my case I would like to check the health of our authentication server by first doing a request to log in, save the returned access token, using that token to do a basic request and finally log out.

In this case the monitor should only pass if:
- we get a token in response to the first request
- we can make a request using that token to query the user's info
- we can log out

An other example would be to check the health of our real-time messaging stack. If we make a request to the API we should receive a packet on our websocket connection.

These kind of complex checks could be easily resolved using scripting.

**Comment by paulb-elastic** [comment]
Linking to https://github.com/elastic/synthetics/issues/137
