### ISSUE TITLE
[Elastic Agent] Agent attempts to download build candidate artifacts from the wrong location

### ISSUE THREAD

**Issue by axw** [elastic/beats#23266]
I'm testing Elastic Agent 7.11 BC1 with the "apm" (snapshot) integration. Elastic Agent is attempting to download the apm-server binary archive from `artifacts.elastic.co`. This fails since the build candidate has not been promoted/released:

```
2020-12-23T17:14:26.580+0800    ERROR   log/reporter.go:36      2020-12-23T17:14:26+08:00: type: 'ERROR': sub_type: 'FAILED' message: Application: apm-server--7.11.0[aa633810-4400-11eb-bc64-2b65e7226012]: State changed to FAILED: 2 errors occurred:
        * package '/tmp/zinga/elastic-agent-7.11.0-linux-x86_64/data/elastic-agent-fc48a3/downloads/apm-server-7.11.0-linux-x86_64.tar.gz' not found: open /tmp/zinga/elastic-agent-7.11.0-linux-x86_64/data/elastic-agent-fc48a3/downloads/apm-server-7.11.0-linux-x86_64.tar.gz: no such file or directory             
        * call to 'https://artifacts.elastic.co/downloads/apm-server/apm-server-7.11.0-linux-x86_64.tar.gz' returned unsuccessful status code: 404: /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/artifact/download/http/downloader.go[150]: unknown error
```

Elastic Agent should be fetching the artifact from `https://staging.elastic.co/7.11.0-710164a0/downloads`. After updating `elastic-agent.yml` to set `agent.download.sourceURI: "https://staging.elastic.co/7.11.0-710164a0/downloads"`, the artifact is downloaded successfully.

I think it's OK if we need to set this config, but:
 - We could alternatively query `https://artifacts-api.elastic.co/v1/search` like we do for snapshot builds, and alleviate the need to modify config. This works for build candidates. e.g. `curl https://artifacts-api.elastic.co/v1/search/7.11.0/apm-server` points to the most recent build candidate.
 - I don't think there's a practical way of doing this in Docker.

For the Docker case, if you attempt to bind mount `elastic-agent.yml` into an Elastic Agent container in order to set sourceURI, then Elastic Agent will fail with the error "Device or resource busy" when running the enroll command, when it attempts to move/rename `elastic-agent.yml`.

**Comment by michalpristas** [comment]
we have covered cases for SNAPSHOT but BC is missing indeed.

**Comment by faec** [comment]
This looks probably obsolete.
