### ISSUE TITLE
Document how to conditionally disable autodiscover providers

### ISSUE THREAD

**Issue by thenewguy** [elastic/beats#23285]
I am trying to run `filebeat test config` via CI runner to validate the configuration.  It fails with:

```
Exiting: error in autodiscover provider settings: error setting up docker autodiscover provider: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

I follow the docs at: https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html

[I am using the sample configuration referenced by the docs.](https://raw.githubusercontent.com/elastic/beats/7.10/deploy/docker/metricbeat.docker.yml)

[The reference configuration](https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.reference.yml#L31) does not list an enabled key or anything like that to use for conditionally disabling the provider based on env vars

**Comment by thenewguy** [comment]
This issue history doesn't indicate it was ever considered

**Comment by tetianakravchenko** [comment]
> [The reference configuration](https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.reference.yml#L31) does not list an enabled key or anything like that to use for conditionally disabling the provider based on env vars

could you please explain what did you want to achieve?

**Comment by tetianakravchenko** [comment]
I will close this issue, as it seems to be outdated, feel free to reopen it and ping me in case it required some additional attention.
