### ISSUE TITLE
[Elastic Agent] Typo in log line

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#23297]
There seems to be a set of typos on this log line:

`Dec 22 14:55:38 monitor systemd[1]: Started Elastic Agent is a unified agent to observe, monitor and protect your system..`

This is not a complete sentence. I think it should say something like:

`Dec 22 14:55:38 monitor systemd[1]: Started Elastic Agent**. It is** a unified agent to observe, monitor and protect your system**.**`

I also removed the extra period at the end.

For confirmed bugs, please report:
- Version: 10.1
- Operating System: linux

**Comment by jfsiii** [comment]
@ph can we transfer this to https://github.com/elastic/beats?

I did some searching there and found 

https://github.com/elastic/beats/blob/ef6274d0d1e36308a333cbed69846a1bd63528ae/x-pack/elastic-agent/pkg/agent/install/svc.go#L18

Which would make that log line: `Started ${ServiceDescription}.` (which explains the double period). However, I don't see  where this is logged in this repo or https://github.com/kardianos/service. 

@blakerouse or @michalpristas can you point me in the right direction for this?

**Comment by blakerouse** [comment]
@jfsiii That log line is printed by systemd itself. So that description is defined in the service file in systemd.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX ,

Could you please confirm if we need to validate this. 

Kindly please let us know more details to validate the same as well in case we need to cover it.

Thanks
QAS

**Comment by EricDavisX** [comment]
no testing needed

**Comment by EricDavisX** [comment]
I am updating the label from 7.14 to 7.15 and we can re-review if we want to spend time and are indeed able to easily access the files to fix.
