### ISSUE TITLE
Rename fields in log output

### ISSUE THREAD

**Issue by rshriram** [elastic/beats#233]
The names of the fields and format of log outputs in the current form is bit confusing and difficult to parse/work with, when using tools other than Elasticsearch.
For e.g.,

```
{"bytes_in":201,"bytes_out":0,"client_ip":"172.16.1.1","client_port":54161,"client_proc":"","client_server":"","count":1,"http":{"code":200,"content_length":11230,"phrase":"OK"},"ip":"172.16.1.2","method":"GET","params":"","path":"/","port":8080,"proc":"","query":"GET /","responsetime":6,"server":"","shipper":"acmeair-test","status":"OK","timestamp":"2015-08-27T12:19:20.745Z","type":"http"}
```

While the output may be amenable for elastic search, there are several redundant fields (i.e., more bandwidth). The output is also unstructured.

Could you change the output to something more canonical, like

client_ip, client_port, server_ip, server_port, timestamp, bytes_in, bytes_out, .. 
Move the HTTP related stuff (e.g., status, path, method, params, responsetime) into the HTTP nested field, eliminate the unnecessary status/phrase field). 

This makes it very easy to parse the output. Also, if the user has disabled process monitoring, you could omit client_proc, client_server, proc fields, to reduce the output size.

I can send a pull request for HTTP log output atleast, if you would like.

**Comment by tsg** [comment]
The reason status, path, and the like are common is because we wanted to have common views in Kibana for them. Otherwise you'd need, for example in the Discover view, to keep changing the fields you display depending on the protocol you are watching.

+1 on removing client_proc and proc when they have no values.

**Comment by rshriram** [comment]
What about ip->server_ip and server port?

On Wed, Sep 9, 2015, 12:03 PM Tudor Golubenco <notifications@github.com>
wrote:

> The reason status, path, and the like are common is because we wanted to
> have common views in Kibana for them. Otherwise you'd need, for example in
> the Discover view, to keep changing the fields you display depending on the
> protocol you are watching.
>
> +1 on removing client_proc and proc when they have no values.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/packetbeat/issues/233#issuecomment-138957460>.
>
-- 

~shriram

**Comment by tsg** [comment]
Yes, that I'd agree with.

**Comment by monicasarbu** [comment]
Mark it as enhancement as it requires changing ip to server_ip.
