### ISSUE TITLE
Windows: Auditbeat/file_integrity reports "short read in readEvents()"

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#23314]
For confirmed bugs, please report:
- Version: 7.11
- Operating System: Windows 2016
- Discuss Forum URL:
- Steps to Reproduce: 

With this config:
```yaml
auditbeat.modules:
- module: file_integrity
  paths:
  - 'C:/users'
  recursive: true
  scan_at_start: false
```

Running under Windows (tested on 2016), the following warning appears periodically in Auditbeat's log:

```
WARN    [file_integrity]        file_integrity/eventreader_fsnotify.go:153      fsnotify watcher error  {"error": "short read in readEvents()"}
WARN    [file_integrity]        file_integrity/eventreader_fsnotify.go:153      fsnotify watcher error  {"error": "short read in readEvents()"}
WARN    [file_integrity]        file_integrity/eventreader_fsnotify.go:153      fsnotify watcher error  {"error": "short read in readEvents()"}
```

Seems to be the same issue as in: https://github.com/fsnotify/fsnotify/issues/72

**Comment by oscar-sanchez-ekasa** [comment]
Update fsnotify to at least version 1.6.0 to apply the change ["windows: increase buffer size from 4K to 64K"] (https://github.com/fsnotify/fsnotify/pull/485)
