### ISSUE TITLE
<!-- CLA-CHECK:23325 -->

### ISSUE THREAD

**Issue by solomonqbq** [elastic/beats#23326]
I've signed

&#10060; Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement):
   37289b4e0738982278ef21f92480712e6e7508e0

   Please, read and sign the above mentioned agreement if you want to contribute to this project

_Originally posted by @cla-checker-service[bot] in https://github.com/elastic/beats/issues/23325#issuecomment-752378484_

**Comment by andresrc** [comment]
Checking in the PR itself.
