### ISSUE TITLE
[Auditbeat] Default distribution fails to start on aarch64 

### ISSUE THREAD

**Issue by liza-mae** [elastic/beats#23349]
For confirmed bugs, please report:
- Version: 7.11.0 BC1 
- Operating System: Ubuntu aarch64
- Steps to Reproduce: 
  Install auditbeat and try to start, observe error 
```
2021-01-03T21:25:57.910Z	INFO	instance/beat.go:437	auditbeat stopped.
2021-01-03T21:25:57.913Z	ERROR	instance/beat.go:971	Exiting: 1 error: metricset 'system/socket' not found
```
Same thing happens on 7.10.1 so not a regression.  The oss distribution works.

**Comment by adriansr** [comment]
You need to disable the `socket` dataset in the `system` module. It only works on x86 architectures.

**Comment by liza-mae** [comment]
Thanks let me try, is it documented or do we need to document this?

**Comment by liza-mae** [comment]
This is the document I found: https://www.elastic.co/guide/en/beats/auditbeat/7.11/auditbeat-module-system.html - does it make sense to add something about it there?

**Comment by andrewkroh** [comment]
We should update the config template to only include the modules that work for arm64. Then the config file will work out of the box.

https://github.com/elastic/beats/blob/518e8b366818c50e4859b7fa945171308dc30156/x-pack/auditbeat/module/system/_meta/config.yml.tmpl#L23-L24

**Comment by liza-mae** [comment]
Sounds good @andrewkroh

**Comment by fearful-symmetry** [comment]
This should be an easy fix, I'll see if I can knock it out

**Comment by liza-mae** [comment]
Thank you @fearful-symmetry - it would be nice if we can get it into 7.11.0 and 7.10.2 upcoming releases.  

I already tested removing the system module and auditbeat comes up, having it do so out of the box would be best.

**Comment by fearful-symmetry** [comment]
@adriansr do we know what parts of the system module do work on aarch64?

**Comment by liza-mae** [comment]
It may make sense to also update the documentation to say something about Linux aarch64 system module.  Thoughts?   

```
The module is fully implemented for Linux. Some datasets are also available for macOS (Darwin) and Windows.
```

**Comment by fearful-symmetry** [comment]
Yah, with the coming age of M1 macs, we might want to be more explicit with ARM support

**Comment by fearful-symmetry** [comment]
Fix here: https://github.com/elastic/beats/pull/23381

Apologies for the delay, my country is struggling with democracy and the news is a tad distracting.

**Comment by fearful-symmetry** [comment]
I think we're good to close this.
