### ISSUE TITLE
[Heartbeat] Trigger Synthetics E2E tests on heartbeat code changes

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#23346]
Ideally we would trigger the synthetics [E2E tests](https://github.com/elastic/synthetics/tree/master/__tests__/e2e) on heartbeat code changes. Is this possible? If so, what would need to be done? CC @KseniaElastic  @kuisathaverat 

This came up in: https://github.com/elastic/beats/compare/master...andrewvc:copy-synthetics-volumes?expand=1

**Comment by kuisathaverat** [comment]
I think we need to backport the changes in https://github.com/elastic/synthetics/pull/148 to the package pipeline, and after generate a Docker image for synthetics https://github.com/elastic/synthetics/blob/master/__tests__/e2e/docker-compose.yml#L43 run those test.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
