### ISSUE TITLE
[Fleet] Dashboards and visualizations are not clearly labeled to distinguish from Beats

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#23390]
The dashboards and visualizations created by packages for Elastic Agent are not clearly labeled to distinguish them from Beats. This is confusing when the system package is installed by default even when the user is not using Elastic Agent. The user may accidentally click on one of the Elastic Agent dasbhoards mistakenly thinking they are for Beats, and there will be no data visible. Also, it will appear to using the incorrect index pattern. We have gotten a support request for this and it may be confusing to other users as well.

To address this confusion, we should clearly label the dashboards and visualizations for Elastic Agent. This could be done via a [tags on saved objects](https://github.com/elastic/kibana/issues/74571), if tags are displayed on the dashboard and visualization selector page. Alternatively, they could include "Elastic Agent" in the title of the asset.

**Comment by sorantis** [comment]
Moved the issue to beats repo.

**Comment by ruflin** [comment]
I wonder if we need to a second issue in the integrations repo. In the best case, Beats and Integrations both add labels to distinguish between the two.

**Comment by mostlyjason** [comment]
@sorantis where is the best place to track/discuss this issue? For integrations, it seems like we could add labels as part of our development guidelines? https://github.com/elastic/obs-dc-team/blob/master/development/generic_guidelines.md

**Comment by sorantis** [comment]
@mostlyjason We can add the to the generic guidelines or preferably to the [dashboard guidelines](https://github.com/elastic/integrations/issues/269). Thanks!

**Comment by mostlyjason** [comment]
Moved this discussion to the integrations repo, so closing this one
