### ISSUE TITLE
Filebeat apache2 error fileset doesn't support timezones 6.x

### ISSUE THREAD

**Issue by ravenbyron** [elastic/beats#23412]
As stated in 
https://github.com/elastic/beats/issues/12772
and fixed in https://github.com/elastic/beats/pull/13304

Any chance this could be back ported to the 6.x releases? We are going to plan an upgrade but that is complicated.  We just found this issues with our error logs being 6 hours behind  (timezone -6) our access logs making coordinating events very hard.

**Comment by kaiyan-sheng** [comment]
https://github.com/elastic/beats/pull/23818 is merged into 6.8. I'm not sure if this will make it to 6.8.14 since BC1 is already created earlier today. If not 6.8.14, it will be in 6.8.15.
