### ISSUE TITLE
System.cpu.cores value should be the actual number of cores, not number usable.

### ISSUE THREAD

**Issue by kevinsmithwrs** [elastic/beats#23453]
**Describe the enhancement:** 
This request is related to request: https://github.com/elastic/beats/issues/22885 resolved with PR: https://github.com/elastic/beats/pull/23154

The issue is that the metricbeat system.cpu module is using the go runtime.NumCPU() function to get the number of cores.  According to the documentation for this function (https://golang.org/pkg/runtime/#NumCPU) ,  "NumCPU returns the number of logical CPUs _usable_ by the current process."  As system.cpu is using gosigar to retrieve cpu statistics, and in the case of linux this is via polling /proc/stat, NumCPU() may not return the same value if cores are reserved via cpusets.

**Describe a specific use case for the enhancement or feature:**
In a kubernetes environment with cpu-manager-policy=static launch a pod with Guaranteed QoS Class in order to reserve cpus.
In the metricbeat container, /proc/stat will still show all cpu cores, yet NumCPU() will report a reduced number of cores due to cores being reserved by the Guaranteed Qos Class pod.  The system.core metricset will however (correctly) report information for all cpus, not the reduced set.

Ideally I think the best fix is for a gosigar function to return an OS independent view of the number of cores upon which it is calculating the cpu usage statistics and then use that in place of NumCPU().  Failing that, metricbeat could do a sigar.CpuList.Get() and use the len of the returned List, though that seems expensive.

I am however wondering about the original issue reported with Oracle VM where vcpus can be dynamically resized.  What does the system.core report in this case?  Does it report information on the same number of cpus as system.cpu.cores?  It seems to me that these should match.  If they do not match, and since documentation for system.cpu.cores states that it is: "The number of CPU cores present on the host" ,  https://github.com/elastic/beats/pull/23154 could be reverted and a one time initialization call to get the size of the list reported from sigar.CpuList.Get() would be sufficient to set the number of cores.

**Comment by kevinsmithwrs** [comment]
I just tried hotplugging vcpus with an Oracle VM VirtualBox VM running Ubuntu.  /proc/stat gets updated on the fly in the running VM as I plug/unplug a cpu (cpux lines in the file are added/removed), so it seems there really is a need to poll for the number of cores every sample.

For the linux case, in:
https://github.com/elastic/gosigar/blob/master/sigar_linux_common.go
A function similar to:  (self *CpuList) Get() that just returns the number of lines in /proc/stat with "cpux" would do it, or else modifying (self *Cpu) Get() to also return a count of the lines of "cpux" would work.

For now though, the system.cpu.cores and the non-normalized system.cpu values will be incorrect any time cpusets are used to reserve cpus.

**Comment by fearful-symmetry** [comment]
I've filed https://github.com/elastic/beats/issues/25647, which I'll be using to track this issue going forward, as I'd like to deploy a working solution sometime within the next two releases. Unless there's something unique about this particular manifestation of this issue, I'd like to close this so we can centralize things.
