### ISSUE TITLE
Improve error reporting of functionbeat deploy in AWS

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#23466]
When deploying functionbeat to AWS using `functionbeat deploy`, it checks if the bucket exists. This check does an authenticated HEAD request to the bucket. If this request doesn't return any error, the check passes. If it returns any error, it only checks if the bucket doesn't exist, for any other error it returns: `"bucket '%s' already exist and you don't have permission to access it"`: https://github.com/elastic/beats/blob/f9df2493f9b757f7d5eeb0df8d11769f23949eb8/x-pack/functionbeat/manager/aws/op_ensure_bucket.go#L58-L59
This is misleading for many other errors that could be happening. For example any connectivity or authentication problem is going to print this error.

Return the actual cause of the failure instead of this error.

Related issues:
* https://github.com/elastic/beats/issues/21708
* https://github.com/elastic/beats/issues/15112#issuecomment-682007011
* Seen several times in discuss: https://discuss.elastic.co/search?q=%22already%20exist%20and%20you%20don%27t%20have%20permission%20to%20access%20it%22

**Comment by cachedout** [comment]
Strong +1 to fixing this issue. I've been fighting Functionbeat for a few hours now and still can't get pass this error and it's totally unclear what's happening here. :-/

**Comment by kvch** [comment]
Closed in #25262
