### ISSUE TITLE
cannot successfully uninstall 7.11+ Agent from command line directly after doing an 'Agent upgrade' when Endpoint is deployed

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#23492]
I’m in a bad state on my Windows vm.  I installed 7.11 (on an 8.0 Kibana) - then attempted to upgrade the Agent to 8.0.  There is a bug I’m following up on that I ran into during this, but I think it is already be accounted / logged.  Putting that aside, in attempting to confirm that, I want to install 7.11 again.  

But in trying I ran into https://github.com/elastic/beats/issues/21870
 - which seems to relate to the mechanisms I happened to use to remote Agent /Endpoint from my host.  It may relate or note, but now after that work around I’m hitting a different Agent specific problem.
 
See screenshot for 'denied' access when trying to install Agent.  And 'denied' when trying to delete the remaining 'data' folder of Agent:

![Screen Shot 2021-01-13 at 2 01 04 PM](https://user-images.githubusercontent.com/12970373/104498900-4c6dd600-55aa-11eb-98ca-3fd8dc6f16d3.png)

Version of Agent is / was 8.0 at this point, but it started as 7.11 and was partially upgraded (Endpoint and Beats were upgraded but Agent was not confirmed as fully starting up, which is the separate problem).

Agent was downloaded initially from here, on Jan 13:
https://snapshots.elastic.co/7.11.0-d50c3350/downloads/beats/elastic-agent/elastic-agent-7.11.0-SNAPSHOT-windows-x86_64.zip

- host perating System: Windows 2012 

Steps, some of these may be condensed once we know the problem:
- install 8.0 Kibana snapshot
- install 7.11 Agent to 8.0
- deploy Endpoint in Policy.  everything works well up to now
- upgrade Agent, using the UI - should start the 8.0 deploy of Agent
- this is where I see a problem... so I want to uninstall the Agent from the host
- I run the ./elastic-agent uninstall
- I run the ./elastic-endpoint uninstall
this is where I run into above bug 21870 - that requires a work-around of manually uninstalling Endpoint, which I do.  But it doesn't help.  The same install command from before doesn't work, as seen in the screenshot.  To try, I reboot the host, but it doesn't help either - the Admin powershell doesn't have access to remove or over-install the 'data' folder on the host.

**Comment by blakerouse** [comment]
@EricDavisX can you provide a screenshot of the permissions of the `data` directory?

**Comment by EricDavisX** [comment]
Thanks Blake - It looks like it was the Agent watcher process that was remaining / alive (as intended) after I upgraded when I tried to un-install it - it seems the Endpoint is protecting that Agent process as well and it was unable to perform it.  When I re-test this, if I wait for the watcher process to conclude and exit I don't see this - so I'm marking it as a fairly low priority as there is nothing additional that is needed except for some patience to wait the 10 minutes.

**Comment by EricDavisX** [comment]
this is what it looks like when it is happening, the data directory and the 'watcher' are still existing:
<img width="539" alt="Screen Shot 2021-01-13 at 5 20 33 PM" src="https://user-images.githubusercontent.com/12970373/104517910-df1b6e80-55c4-11eb-99f1-5d621cd2d834.png">

**Comment by jlind23** [comment]
Not relevant anymore
