### ISSUE TITLE
Remove version specific download links

### ISSUE THREAD

**Issue by markwalkom** [elastic/beats#235]
[Here](https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-getting-started.html).

Otherwise we lock ourselves into having to update the links constantly. Instead we should use things like `https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-latest.zip` :)

**Comment by monicasarbu** [comment]
It's great to be able to download the _latest_ package for Elasticsearch, but I think in the getting started guide it's better to choose what version of Elasticsearch and Kibana work better with each Beat release. It might be that an older version of a Beat doesn't work with the _latest_ Elasticsearch or Kibana.

**Comment by dedemorton** [comment]
Giving users the exact commands to run makes it much easier for them to get started. I vote for keeping the version-specific commands and updating the doc when required. It's a quick change from a doc perspective, but it makes the user experience much better.

**Comment by dedemorton** [comment]
For now, we will leave the version-specific information to ensure that Beats users get the version of Elasticsearch and Kibana that works best with Beats.
