### ISSUE TITLE
Allow metricbeat to dynamically identify the number of cores instead of using runtime.NumCPU()

### ISSUE THREAD

**Issue by marc-gr** [elastic/beats#23523]
**Describe the enhancement:**

Currently metricbeat uses `runtime.NumCPU()` to grab the number of cores: https://github.com/elastic/beats/blob/master/metricbeat/module/system/cpu/data.go#L100

This has some limitations, since there are a bunch of situations where the reported number does not match the actual number of cores:

- You modified the number of cores without restarting (either because you are using an hypervisor that allows hot addition or you enabled them at runtime)
- You have some offline or disabled cores
- You run the process with a more restrictive affinity (using [taskset](https://man7.org/linux/man-pages/man1/taskset.1.html))
- or you have isolated CPUs in the system

**Describe a specific use case for the enhancement or feature:**

If any of the above situations happen, we still want to report the real number of cores. A similar change was done for auditbeat [here](https://github.com/elastic/beats/pull/22827)

**Comment by fearful-symmetry** [comment]
Agreed, we need to do this differently, the sooner the better. Both `lscpu` and auditbeat pull from `/sys/devices/system/cpu` on linux, which is the way to go. Not sure about other platforms.

**Comment by fearful-symmetry** [comment]
Closing, as we now no longer use the `runtime` libs for CPU info, and we're now actually looking at os-reported CPU config.
