### ISSUE TITLE
[Elastic Agent] Not sending correct hostname to Beats when certificate is missing

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#23547]
I'm running Elastic Agent in standalone mode and it doesn't seem to be sending the correct hostname to metricbeat. I set my hostname in `elastic-agent.yml` in my home directory before installing it. I then verified this hostname is set in 
```
$ sudo cat /opt/Elastic/Agent/elastic-agent.yml
id: 9a58b7a0-4514-11eb-b4dd-739d3e98403f
revision: 11
outputs:
  default:
    type: elasticsearch
    hosts:
      - 'https://monitor.lan:9200'
```

However, when I check the metricbeat logs it says:

```
default/metricbeat_monitor-json.log:{"log.level":"debug","@timestamp":"2021-01-18T10:27:47.065-0500","log.logger":"esclientleg","log.origin":{"file.name":"eslegclient/connection.go","file.line":294},"message":"Ping request failed with: Get \"http://localhost:9200\": dial tcp 127.0.0.1:9200: connect: connection refused","ecs.version":"1.6.0"}
```

It should not be trying to ping localhost because the hostname I set in the yml file is `monitor.lan`. Perhaps I set something up incorrectly?

For confirmed bugs, please report:
- Version: 7.10.1
- Operating System: Debian 
- Steps to Reproduce: install a 7.10.1 elastic agent on a linux system, edit the elastic-agent.yml file with a hostname for ES, then check the metricbeat-json.log to verify if its using the correct output

**Comment by ph** [comment]
This is a strange behavior you are describing. I've tested the above with the following output and only the default system metric:

```yaml
outputs:
  default:
    type: elasticsearch
    hosts: http://hola.lan:9200
    username: elastic
    password: changeme
```

Looking at the logs Metricbeat and two monitor beats they actually try to connect to "hola.lan"

```
winterfell~/tmp/elastic-agent-7.10.2-linux-x86_64(:|✔) % ag "hola.lan" -l
data/elastic-agent-aacf9e/logs/default/metricbeat-json.log
data/elastic-agent-aacf9e/logs/default/metricbeat_monitor-json.log
data/elastic-agent-aacf9e/logs/elastic-agent-json.log
data/elastic-agent-aacf9e/logs/default/filebeat_monitor-json.log
```

Content of the metricbeat log:
```
{"log.level":"debug","@timestamp":"2021-01-18T13:31:50.442-0500","log.logger":"esclientleg","log.origin":{"file.name":"eslegclient/connection.go","file.line":294},"message":"Ping request failed with: Get \"http://hola.lan:9200\": lookup hola.lan: no such host","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-01-18T13:31:51.985-0500","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/output.go","file.line":154},"message":"Failed to connect to backoff(elasticsearch(http://hola.lan:9200)): Get \"http://hola.lan:9200\": lookup hola.lan: no such host","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-01-18T13:31:51.985-0500","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/output.go","file.line":145},"message":"Attempting to reconnect to backoff(elasticsearch(http://hola.lan:9200)) with 1 reconnect attempt(s)","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2021-01-18T13:31:51.985-0500","log.logger":"esclientleg","log.origin":{"file.name":"eslegclient/connection.go","file.line":290},"message":"ES Ping(url=http://hola.lan:9200)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-01-18T13:31:51.985-0500","log.logger":"publisher","log.origin":{"file.name":"pipeline/retry.go","file.line":219},"message":"retryer: send unwait signal to consumer","ecs.version":"1.6.0"}
````

# Questions:

Where is located the `elastic-agent.yml` that you have edited on disk?

**Comment by mostlyjason** [comment]
This file is located in two places and they both have the elasticsearch output set to monitor.lan

```
/home/mostlyjason/elastic-agent-7.10.1-linux-x86_64/elastic-agent.yml
/opt/Elastic/Agent/elastic-agent.yml
```

**Comment by mostlyjason** [comment]
I think I found the root cause of this. When the certificate is missing on the local filesystem, it never applies the elasticsearch URLs to the output settings. As a result, they get set to the default value of localhost. 

Here is what happens when the certificate is missing:
```
{"log.level":"info","@timestamp":"2021-01-25T06:25:14.980-0500","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"fleet/manager.go","file.line":224},"message":"Applying settings for output","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-01-25T06:25:14.980-0500","log.logger":"tls","log.origin":{"file.name":"tlscommon/tls.go","file.line":154},"message":"Failed reading CA certificate: open /opt/Elastic/elasticsearch-ca.pem: no such file or directory","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-01-25T06:25:14.980-0500","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"fleet/manager.go","file.line":244},"message":"1 error: open /opt/Elastic/elasticsearch-ca.pem: no such file or directory reading <nil>","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-01-25T06:25:14.980-0500","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"fleet/manager.go","file.line":224},"message":"Applying settings for filebeat.modules","ecs.version":"1.6.0"}
```

And here is with the certificate present (and after a restart):
```
{"log.level":"info","@timestamp":"2021-01-25T06:12:40.340-0500","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"fleet/manager.go","file.line":224},"message":"Applying settings for output","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2021-01-25T06:12:40.341-0500","log.logger":"tls","log.origin":{"file.name":"tlscommon/tls.go","file.line":172},"message":"Successfully loaded CA certificate: /opt/Elastic/elasticsearch-ca.pem","ecs.version":"1.6.0"
{"log.level":"info","@timestamp":"2021-01-25T06:12:40.341-0500","log.origin":{"file.name":"eslegclient/connection.go","file.line":99},"message":"elasticsearch url: https://elasticsearch:9200","ecs.version":"1.6.0"}
```

I'm wondering if we should change anything to make the behavior more clear? I didnt see this error right away and the 100s of localhost pings was a red herring. Its a little confusing that it ignores my settings and that a failed certificate would cause it to ping localhost. It would have been more clear to me if the url was changed to the value I set, and then I got an error message in my ES pings about a missing/invalid certificate. Alternatively, if filebeat just stopped running since the outputs didn't load correctly. I have no idea if those options are reasonable from a technical perspective.

**Comment by faec** [comment]
This is pretty stale, so I'm closing. I wonder if the issue was in the testing environment? If Elasticsearch was running on the local host (whether directly or proxied to a container or etc) that could lead to network connections (especially in go) describing the connection as `localhost` and similar even if the DNS name that was used to look it up was something else. If we see this in a current setup we can reopen.
