### ISSUE TITLE
Macos BigSur 11.1  Packetbeat Cross-compile to windows 

### ISSUE THREAD

**Issue by Aixic-Love** [elastic/beats#23543]
Mainly a problem with libpcap. 

go.mod 
`github.com/tsg/gopacket v0.0.0-20200626092518-2ab8e397a786`

![image](https://user-images.githubusercontent.com/50495439/104895649-1917b680-59b1-11eb-9809-cea158c7e681.png)
First of all, when this problem occurred, I modified the pcap.go file.
![image](https://user-images.githubusercontent.com/50495439/104895735-32b8fe00-59b1-11eb-98fe-9ff86c45fd9b.png)
WpdPack is downloaded from here：https://www.winpcap.org/devel.htm
![image](https://user-images.githubusercontent.com/50495439/104895843-5419ea00-59b1-11eb-8a22-d804debade01.png)

Try to cross compile...
`CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 go build -x -v`

--------------
![image](https://user-images.githubusercontent.com/50495439/104896304-e6ba8900-59b1-11eb-9dd0-7d4a21d733c0.png)
![image](https://user-images.githubusercontent.com/50495439/104896337-f043f100-59b1-11eb-9376-a1a548d9eb33.png)

I need to deploy through the build machine, is there any solution?

---

**Comment by Aixic-Love** [comment]
I tried to modify pcap.go to look like this
![image](https://user-images.githubusercontent.com/50495439/104900914-a3fbaf80-59b7-11eb-857e-edb270c83933.png)
It can be compiled normally, but it will report an error when it runs.
![image](https://user-images.githubusercontent.com/50495439/104900902-9e9e6500-59b7-11eb-831a-e016447672b3.png)

**Comment by andrewkroh** [comment]
Cross-compile for Windows can be accomplished with the `package` target. You must have Docker setup on your macos.

```
cd packetbeat
make mage
PLATFORMS='windows/amd64' mage package
ls -la build/distributions
```
