### ISSUE TITLE
Packetbeat memory leak with http prasing

### ISSUE THREAD

**Issue by itayrozenberg** [elastic/beats#23552]
server: Physical
cpu: 12 cpus
ram: 64GB

os: centos 7 x86_64
packetbeat: 7.3.2 (rpm package)

hi
i'm sniffing http traffic, and for some strange reason ther is a big memory leak,
it looks like most of the memory is going to http body parsing.
memory keeps filling until its full and packetbeat stops sending traffic to logstash

could anyone help me on this problem?
thanks in advance.

relevant configuration:

packetbeat.interfaces.device: ens1f1
packetbeat.interfaces.type: af_packet
packetbeat.interfaces.buffer_size_mb: 2000
packetbeat.interfaces.bpf_filter: host 172.23.64.26 or host 172.23.64.28 or host 172.23.64.29  or host 172.23.192.28 or host 172.23.192.29 or host 172.23.192.26 and tcp port 80

- type: http
  ports: [80, 8080, 8000]
  send_all_headers: true
  include_body_for: ["text/html","text/xml","application/json","x-www-form-urlencoded"]
  send_request: true
  decode_body: false
  max_message_size: 94850

pprof file is attached
[out.zip](https://github.com/elastic/beats/files/5831819/out.zip)

**Comment by andrewkroh** [comment]
> packetbeat: 7.3.2 (rpm package)

Can you please upgrade to the latest Packetbeat release and check if the leak still occurs. If it does then please reopen and attach a new pprof profile.
