### ISSUE TITLE
[Heartbeat] Allow multiple directories for monitor defintions

### ISSUE THREAD

**Issue by bvader** [elastic/beats#23578]
**Describe the enhancement:**
Allow more than 1 directory to define monitors. For customers for many potentially 100s of monitors a single directory is limiting and hard to manage. 

**Describe a specific use case for the enhancement or feature:**

```
heartbeat.config.monitors:
  # Directory + glob pattern to search for configuration files
  path: ${path.config}/monitors.d/*.yml
```
Allow that path to be an array or 

`${path.config}/monitors.d/*/*.yml`

**Comment by andrewvc** [comment]
This actually does work @bvader , the syntax needs to be `${path.config}/monitors.d/**/*.yml`, The double star `**` means any subdirectory in glob syntax in bash and elsewhere.

**Comment by bvader** [comment]
NICE thanks I will retry... I tried like 20 version but that! 
I will verify and close.

**Comment by bvader** [comment]
Verified Works

**Comment by immon** [comment]
@bvader did it work for you with a deeper directory structure like `monitors.d/prod/hostname/service1/*.yml`?

From what I've learned the double wildcard syntax is not supported in Go -- https://github.com/golang/go/issues/11862 and `**` works like a single `*`.
One can use one-level deep directory structure like `monitors.d/prod_hostname_sevice1/http.yml`, `monitors.d/dev_hostname_sevice2/smtp.yml` but a deeper directory hierarchy would not work.

**Comment by bvader** [comment]
@immon @andrewvc

Apologies for the delayed response. 
I did try with one directory deep and it did work as noted, which was my current use case (customer requirement). 

Also I did try 2 levels deep with both the following they worked, 

`path: ${path.config}/monitors.d/*/*/*.yml`
and 
`path: ${path.config}/monitors.d/**/**/*.yml`

But you are correct this does not work. 

`path: ${path.config}/monitors.d/**/*.yml`

I think we can close as it seems like a reasonable workaround, but the `heartbeat.yml` does say globs are supported so perhaps that should be taken out. 

```
  # Directory + glob pattern to search for configuration files
  path: /path/to/my/monitors.d/*.yml
```
