### ISSUE TITLE
Verify ECS alignment in container fields reported by kubernetes module and meta processor

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#23585]
We need to make sure that we have consistent way of aligning common ECS fields across integrations reporting same resource information. An example can be `container.image.name` and `kubernetes.container.image` (added at https://github.com/elastic/beats/pull/20984) which is actually the same field but it not aliased like what is [happening with Docker](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-docker-processor.html):
```
docker.container.image
type: alias
alias to: container.image.name
```

Update:
Verify that `state_*` metricsets follow ECS. For instance testing `state_container` datastream of k8s package I get:
```
kubernetes/state_container default:
[0] field "container.runtime" is undefined
[1] field "kubernetes.container.image" is undefined
[2] field "kubernetes.container.name" is undefined
[3] field "kubernetes.namespace" is undefined
[4] field "kubernetes.node.name" is undefined
[5] field "kubernetes.pod.name" is undefined
```
So `kubernetes.container.*` seem to need to be changed.

**Comment by ChrsMark** [comment]
`state_container` ECS fix PR: https://github.com/elastic/beats/pull/23802

**Comment by ChrsMark** [comment]
## Summary

Right now it seems that we have not been consistent on the way we report container ECS fields. There are 2 ways we report container ECS fields:
1. using `alias`
2. explicitly copying the fields in the code while preserving the original ones until 8.0

### alias
`add_docker_metadata` uses the [`alias` approach](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-docker-processor.html):
```
docker.container.image
type: alias
alias to: container.image.name
```

### copy explicitly
So far the `kubernetes` module, `add_kubernetes_metadata` processor and k8s metadata for autodiscover copy ECS containers fields explicitly in the code while:
1. `state_container` metricset: #23802, #13884
2. k8s metadata: https://github.com/elastic/beats/pull/20984

**Comment by ChrsMark** [comment]
Heads-up on this.

 I did a simple test to verify that using `alias` for container meta collected through [`add_docker_metadata` for Filebeat,](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-docker-processor.html) gives us the option to build visualisations on both `container.name` and `docker.container.name` as well as perform searches on these both fields:

<img width="1605" alt="Screenshot 2021-03-01 at 3 57 08 PM" src="https://user-images.githubusercontent.com/11754898/109507063-0364d900-7aa7-11eb-8877-900c44637f9e.png">
<img width="1613" alt="Screenshot 2021-03-01 at 3 56 55 PM" src="https://user-images.githubusercontent.com/11754898/109507083-08298d00-7aa7-11eb-93aa-2affcfd32ddb.png">

<img width="1591" alt="Screenshot 2021-03-01 at 3 57 33 PM" src="https://user-images.githubusercontent.com/11754898/109507080-0790f680-7aa7-11eb-8d8e-11ad081ea566.png">
<img width="484" alt="Screenshot 2021-03-01 at 3 51 54 PM" src="https://user-images.githubusercontent.com/11754898/109507092-0a8be700-7aa7-11eb-82ea-93dd697603d1.png">


It seems that we are not able to search/visualise with reference to the `alias` fields like `docker.container.name`.
Didn't check what happens with prebuilt visualisations and what will happen when change the `kubernetes.container.name` and making an alias of `container.name`, but the first two examples shouldn't work for us so as to make use of alias right?

@exekias does it happen to remember why we preferred to just copy `kubernetes.container.*` fields back then (https://github.com/elastic/beats/pull/13884) and we didn't use alias option?

**Comment by jsoriano** [comment]
> It seems that we are not able to search/visualise with reference to the `alias` fields like `docker.container.name`.

Could you check if the alias is actually in the index pattern?

This alias is defined with `migration: true`, so this is probably only included in the index pattern if the migration options are used. This option was included for the migration to ECS in 7.0, see these docs: https://www.elastic.co/guide/en/beats/libbeat/7.11/upgrading-6-to-7.html#enable-ecs-compatibility
```
        - name: container.name
          type: alias
          path: container.name
          migration: true
```

**Comment by ChrsMark** [comment]
You are right @jsoriano 👍🏼 !!!

With `migration: true` it is not shown in index_template.
I changed to:
```
"docker": {
          "properties": {
            "attrs": {
              "type": "object"
            },
            "container": {
              "properties": {
                "id": {
                  "type": "alias",
                  "path": "container.id"
                },
                "image": {
                  "type": "alias",
                  "path": "container.image.name"
                }
   }
}
```
And now it seems to be possible to both search and visualise using the alias:
<img width="1609" alt="Screenshot 2021-03-02 at 12 21 56 PM" src="https://user-images.githubusercontent.com/11754898/109634736-44fe8e00-7b52-11eb-9ebb-3a70cdcbbbc7.png">

**Comment by exekias** [comment]
> @exekias does it happen to remember why we preferred to just copy `kubernetes.container.*` fields back then (#13884) and we didn't use alias option?

I don't really remember this, but I think we can revisit this if needed!

**Comment by jsoriano** [comment]
> I don't really remember this, but I think we can revisit this if needed!

+1 to use alias more for deprecated fields if they work well with visualizations.

**Comment by ChrsMark** [comment]
Using alias sounds good to me! 

I will work on a PR to change the "copy" approach we have for k8s fields so as to further test the alias approach and use it for future reference.

**Comment by ChrsMark** [comment]
So after some investigation on https://github.com/elastic/beats/pull/24380, we end up to change how we handle `kubernetes.container.image` field. Before the change this field was set in `kubernetes.container.image` and `container.image.name` programatically. This means that both fields are stored. With the use of alias though (at  #24380) we only store `container.image.name` and then we can refer to `kubernetes.container.image` through an alias in searches and visualisations. 

We didn't do the same for `kubernates.container.name` and `conatiner.name` since these are actually different fields (https://github.com/elastic/beats/pull/24380#issuecomment-795221668).

In 8.0 we can completely remove the alias  field `kubernates.container.name` and move on with only the ECS field, if we verify that it's not used in visualisations/searches/dashboards.

We can use this issue as reference in the future when it comes to ECS fields and deprecation plan.

cc: @ruflin

**Comment by MichaelKatsoulis** [comment]
> In 8.0 we can completely remove the alias field kubernates.container.name and move on with only the ECS field, if we verify that it's not used in visualisations/searches/dashboards.

Discussing with @ChrsMark  the removal of `kubernetes.container.image` in 8.0 we reached to the point that we could still keep that field as it is an alias to  ECS field `container.image.name` and is not an extra field in the database. That way users can leverage both in case they want to.
About `kubernetes.container.name` and `kubernates.container.id` they have actually different values than  ECS fields `container.id` and `container.name`. 
`container.name` is the name of the container that the runtime populates while `kubernates.container.name` is the name of the container in the kubernetes manifest. 
I believe that there is no point to delete those kubernetes fields as their values do not relate 100% to any ECS field.

@ruflin, @exekias do you agree on this?

**Comment by ruflin** [comment]
What did during the migration to 7.0 is to offer users a flag to enable the alias if they want it, but it was opt in. The problem with keep it by default is that you will keep the fields forever. Having 2 fields with the same meaning is not great and if we keep having more and more aliases, the overall number of fields keeps growing. It is here only about 2 fields it will set a precedence and we will use it in other places too.

For the fields that have separate values, agree we should keep them if these provide value.

**Comment by MichaelKatsoulis** [comment]
Ok @ruflin I will remove `kubernetes.container.image` in 8.0.
