### ISSUE TITLE
Dissect processor doesn't support greedy match in an expected way

### ISSUE THREAD

**Issue by cy-zheng** [elastic/beats#23582]
- Version: 7.10.2
- Operating System: Ubuntu 16.04
- Discuss Forum URL: https://discuss.elastic.co/t/does-dissect-processor-in-beats-support-greedy-lazy-match/261616
- Steps to Reproduce: 

I'm using dissect processor to parse a value like 
`/var/log/containers/calico-node-ltx4t_kube-system_calico-node-21e03abb29adcec39f69e3f76c16eb2b3ed4dd1a51675279de5cedc59bdce56b.log`

using tokenizer:`/var/log/containers/%{kube_pod_name}_%{kube_namespace_name}_%{container_name}-%{container_id}.log`

The result is:
```
"kube_pod_name": "calico-node-ltx4t",
"container_id": "node-21e03abb29adcec39f69e3f76c16eb2b3ed4dd1a51675279de5cedc59bdce56b"
"kube_namespace_name": "kube-system",
"container_name": "calico",
```

However, the result I expected is:
```
"container_id": "21e03abb29adcec39f69e3f76c16eb2b3ed4dd1a51675279de5cedc59bdce56b"
"container_name": "calico-node"
```

**Comment by andresrc** [comment]
@sayden can you check if dissect in Logstash and ES ?

**Comment by andresrc** [comment]
ping @sayden

**Comment by sayden** [comment]
Sorry for the late reply.

For this particular case, you must append a second right match to the pattern, like this:
```
%{kube_pod_name}_%{kube_namespace_name}_%{container_name}-%{+container_name}-%{container_id}.log
```

```json
{
  "container_id": "21e03abb29adcec39f69e3f76c16eb2b3ed4dd1a51675279de5cedc59bdce56b",
  "container_name": "calico-node",
  "kube_namespace_name": "kube-system",
  "kube_pod_name": "calico-node-ltx4t"
}
```

But this implies that all your containe names have a `-` on them.

**Comment by ph** [comment]
Going to close this, because I think this is the correct behavior of dissect.
