### ISSUE TITLE
[Agent] when we enable Endpoint in Agent Policy, monitoring filebeat doesn't get sent the log path until Agent is re-started

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#23599]
[Agent] when we turn on Endpoint in Agent Policy, Agent doesn't tell filebeat to monitor logs until Agent is re-started

looking with a debug build with Blake...
comes out of research during: https://github.com/elastic/security-team/issues/727

testing on Centos7 on a clean host with 8.0 Kibana cloud / stack and PR sourced Agent from
https://console.cloud.google.com/storage/browser/beats-ci-artifacts/pull-requests/pr-23574

**Comment by EricDavisX** [comment]
@ph we think this is pretty bad for 7.11 - and we'd like to pull in @michalpristas in the AM to review...

**Comment by ph** [comment]
Agree

**Comment by michalpristas** [comment]
looking, probably have a root cause and a fix. need to test

**Comment by EricDavisX** [comment]
I helped test Michals branch - it looks great.  We'll look for the backports and we can track when it goes in for 7.11, plenty of time to make next week's BC5

**Comment by EricDavisX** [comment]
Let us get this reviewed and merged asap - @blakerouse @ph 
https://github.com/elastic/beats/pull/23636 - 7.11 backport

**Comment by EricDavisX** [comment]
7.11 PR is merged - @dikshachauhan-qasource this should be available to test out fully in BC5 7.11 that is coming in a day or two.  Thanks all!

**Comment by EricDavisX** [comment]
this is tested as ok in BC5 7.11 build, but I have logged an issue that was being masked:
https://github.com/elastic/beats/issues/23720 
 - this is closed out and fixed tho.
