### ISSUE TITLE
filebeat logging permissions

### ISSUE THREAD

**Issue by mscamara** [elastic/beats#23639]
I have a problem with Filebeat and I think it's a bug. I changed the permission in Filebeat configuration to 0644. after restarting Filebeat the permission changes. I have tried several combinations without success.
When I try to consult the logs with a user other than root the answer is: cannot open the directory / var / log / filebeat /: Permission not granted
I have seen a lot of discussion around the same problem.

https://discuss.elastic.co/t/filebeat-permissions/261912
https://discuss.elastic.co/t/filebeat-5-3-1-config-dir-files-needs-644-permissions/84108

Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 
- Operating System: 
- Discuss Forum URL:
- Steps to Reproduce:

**Comment by urso** [comment]
> I changed the permission in Filebeat configuration to 0644. after restarting Filebeat the permission changes.

> I installed the agent with user root and would like other users to be able to view the logs and conf. But by modifying the conf filebeat logging permissions level to 0644 but it is not taken into account, it is modified in 420.

Which setting exactly did you change? Just on disk or in the filebeat configuration file? The octal value 420 is 644 decimal.
