### ISSUE TITLE
Provide a way to collect tags associated to some cloud objects

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#23637]
**Describe the enhancement:**

The different cloud providers provide ways to add custom tags to resources (e.g. [compute instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html)). However these tags may not be collected by the existing processors (`add_cloud_metadata`) as they may need different API calls with different requirements.

**Describe a specific use case for the enhancement or feature:**

The information from the tags is useful for filtering / classification.

Related: https://discuss.elastic.co/t/filebeat-and-ec2-tags/98737

**Comment by ravikesarwani** [comment]
Closing it as stale. Something that we will look at as a feature/enhancement in the Elastic Agent integrations.
