### ISSUE TITLE
[Ingest Manager]: Able to stop .deb Agent service when Endpoint Security is enabled (should be protected?)

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#23646]
**Kibana version:**
7.11 BC4 Kibana Cloud environment 

Elasticsearch version:
7.11 BC4 Kibana Cloud environment 

**Host OS and Browser version:**
Deb 9, All

Original install method (e.g. download page, yum, from source, etc.):
7.11 BC4 Kibana Cloud environment

**Preconditions**
1.  7.11 BC4 Kibana Cloud environment  should be available.
```
BUILD 37776
COMMIT efd7b70e2803294a95395629dee55c89441d742a
Artifact link: https://staging.elastic.co/7.11.0-c9f0a1f5/downloads/beats/elastic-agent/elastic-agent-7.11.0-amd64.deb
```
2. Default policy having **Endpoint Integration** integration should exist.[No change in namespace].
3. '.deb Agent' should be deployed using above policy. 

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Agents Tab.. 
3. Agent Agent is in healthy status with running endpoint logs.
4. SSh to endpoint and run below command to check elastic-agent service status:-
sudo systemctl status elastic-agent
5. Observe, agent is in Active state.
6. Now, run below command to stop agent:
sudo systemctl stop elastic-agent
7. Repeact step 4.
8. Observe, agent service is stopped and agent is in inactive state.

Reference ticket Id:
n/a

Actual Result:
Able to stop deb Agent service with Endpoint Security

Expected Result:
User should not be able to stop deb Agent service with Endpoint Security.

What's working:
N/A

What's not working:
N/A

**Logs**
As we are not able to access logs from endpoint due to ' Permission denied' error message. So, Please find environment details as follows:
7.11BC4 Kibana cloud build:
elastic/d7c2SRVWZnw3Vd032blzNrZS
URL: https://58e1536ee1434f9c933b862aa4ecf4e5.us-central1.gcp.foundit.no:9243/
Endpoint IP: 10.0.7.83
Machine Link: https://unimog.it.endgames.local/ui/#?extensionId=vsphere.core.vm.summary&objectId=urn:vmomi:VirtualMachine:vm-3444816:B8879A27-10BA-4593-855B-95A82ED24F31&navigator=vsphere.core.viTree.vmsAndTemplatesView

**Screenshots:** 
![deb_agent_stopped](https://user-images.githubusercontent.com/72375798/105683591-c8a4d980-5f19-11eb-94fd-c8b3072eb351.png)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please Review

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@willyu-elastic @michalpristas @blakerouse - is there any difference we can confirm about .rpm /deb usage that the Endpoint protection of Agent we can guess would not be in effect, like a different process path vs an Agent set up with 'install' command?   

@dikshachauhan-qasource can you attach the full Agent and Endpoint logs from the time around when you deployed and/or turned on Endpoint security?  It may give us the evidence there, itself, in an error log citing 'cannot protect process' or something (Just a guess).

**Comment by EricDavisX** [comment]
@ferullo This would be on Endpoint side to fix, correct?  But you may need info from Agent Fleet team to process it on.  If you agree, would you please update issue as desired.

**Comment by ferullo** [comment]
Endpoint has no self protection features on Linux. I'm not quite sure what the issue is here, but it looks like an Agent issue. I don't see anything Endpoint related in the commands @dikshachauhan-qasource ran.

Endpoint and Agent have independent services. Both should be able to stop/start independently.

**Comment by EricDavisX** [comment]
Ah!  Indeed, we don't have any self-protection features on Linux, I forgot that.  We were testing with the expectation of it being there, sorry for noise.

 @dikshachauhan-qasource please update the test content to not expect it to be protected.  For any Linux tar.gz or .rpm/.deb installs.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

Thanks for the confirmation.

Currently, we have no testcases related to above functionality on Linux OSs. Hence, no updates are required.
