### ISSUE TITLE
[Ingest Manager]: Unable to install 8.0 snapshot agent (Verified on windows and macOS so far)

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#23652]
**Kibana version:**
8.0 snapshot Kibana Cloud environment 

Elasticsearch version:
8.0 snapshot Kibana Cloud environment 

**Host OS and Browser version:**
Windows 10, windows server 2012, All

**Windows Test Signing ON**

Original install method (e.g. download page, yum, from source, etc.):
8.0 snapshot Kibana Cloud environment  

[Ingest Manager]: Unable to install 8.0 snapshot agent on windows.

**Preconditions**
1.  8.0 snapshot Cloud environment  should be available.
```
BUILD 39794
COMMIT 8263d47d378315bdcad990620010c8452f3133d1
Artifact link: https://snapshots.elastic.co/8.0.0-24830523/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip
```
2. Default policy having system integration should exist.[No change in namespace].

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Add Agents flyout.
3. Copy installation command for windows Agent.
4. RDP to endpoint. Open powershell with Admin mode.
5. Run command copied at step 3 at location c:\>Program Files>elastic-agent
6. Observe, below error message is displayed.
```
Error: fail to enroll: fail to execute request to Kibana: Post "https://1ed62a6e3547403093eeb507927b385e.us-central1.gcp.foundit.no:443/api/fleet/agents/enroll?": x509: certificate is valid for *.gcp.foundit.no, *.us-central1.gcp.foundit.no, *.europe-west1.gcp.foundit.no, *.apm.us-central1.gcp.foundit.no, *.app-search.us-central1.gcp.foundit.no, *.apm.europe-west1.gcp.foundit.no, *.app-search.europe-west1.gcp.foundit.no, *.ent-search.us-central1.gcp.foundit.no, gcp.foundit.no, us-central1.gcp.foundit.no, apm.us-central1.gcp.foundit.no, app-search.us-central1.gcp.foundit.no, europe-west1.gcp.foundit.no, apm.europe-west1.gcp.foundit.no, app-search.europe-west1.gcp.foundit.no, ent-search.us-central1.gcp.foundit.no, not 1ed62a6e3547403093eeb507927b385e.us-central1.gcp.foundit.no
Error: enroll command failed with exit code: 1
```

Reference ticket Id:
N/A

Actual Result:
Unable to install 8.0 snapshot agent on windows.

Expected Result:
User should be able to install 8.0 snapshot agent on windows.

What's working:
N/A

What's not working:
N/A

**Screenshots:** 
![AgenterrorOnWindows](https://user-images.githubusercontent.com/72375798/105703315-09f5b300-5f33-11eb-9164-6449a7f7a5a4.png)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by ph** [comment]
@michalpristas this is interesting, could that be possibly linked to the Golang upgrade from last week?

**Comment by manishgupta-qasource** [comment]
Reviewed

**Comment by dikshachauhan-qasource** [comment]
Hi @michalpristas 

We have attempted to install 8.0 snapshot agent on mac as well and observed 'Error enroll command with exit code: 1' error message. 

Please refer below screenshot.
![#23652_error_on_mac](https://user-images.githubusercontent.com/72375798/105707001-4aa3fb00-5f38-11eb-8ce2-1445cce178a2.png)

Thanks
QAS

**Comment by EricDavisX** [comment]
Thanks Diksha, it directly relates to the new GoLang upgrade noted here:
https://github.com/elastic/beats/pull/22495

I read thru it briefly, and wasn’t sure what impact it would have on our systems.  A guess is we may need to update the Windows vm templates.  I’m not sure yet - but thank you for logging.  @charlie-pichette care to help us research our Windows vSphere host templates?

**Comment by michalpristas** [comment]
yes seems to be related with latest change in go version and TLS handling will take a look

**Comment by kvch** [comment]
Fix that will probably help: https://github.com/elastic/beats/pull/23661

**Comment by ph** [comment]
closing #23661 was merged.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX
We have re-validated this issue on 8.0.0 Snapshot Kibana Cloud environment found it **Fixed**. Build details are as follows:

```
Build: 39872
Commit: 0fe7b9e080c67c43aefdb7ea25d5e90a80cb4ade
Artifact link for Windows: https://snapshots.elastic.co/8.0.0-e9bbbb5f/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip
Artifact link for MAC: https://snapshots.elastic.co/8.0.0-e9bbbb5f/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz
```
**Observations:**
- Windows Agent enrolled successfully.
- MAC Agent enrolled successfully.

**Screenshots:**
![#23652](https://user-images.githubusercontent.com/77374876/105986489-05600480-60c3-11eb-84fe-a66bda926c45.png)

Please let us know if anything else is required.

Thanks
QAS
