### ISSUE TITLE
[metricbeat] Error setup kibana dashboards read-only metricbeat.yml

### ISSUE THREAD

**Issue by cdalexndr** [elastic/beats#23657]
```
λ docker exec -it docker_metricbeat_1 sh
sh-4.2# metricbeat setup --dashboards
Exiting: error loading config file: config file ("metricbeat.yml") can only be writable by the owner but the permissions are "-rwxrwxrwx" (to fix the permissions use: 'chmod go-w /usr/share/metricbeat/metricbeat.yml')
```

metricbeat.yml is mounted as read-only in docker-compose:
```
    volumes:
      - ./config/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
```

Why is setup complaining `metricbeat.yml` is read-only?
Setup shouldn't write to this file, so it should ignore write access.

For confirmed bugs, please report:
- Version:  7.10.1
- Operating System: docker win
- Discuss Forum URL:
- Steps to Reproduce:

**Comment by cdalexndr** [comment]
This is a bug because `setup` shouldn't complain that `metricbeat.yml` is not writable.

**Comment by MerzDaniel** [comment]
Kindly asking to reopen as it is still an issue. The Elastic docker setup guide also does not work due to this error 
https://www.elastic.co/blog/getting-started-with-the-elastic-stack-and-docker-compose
