### ISSUE TITLE
Adding support for Octet counting in TCP input

### ISSUE THREAD

**Issue by P1llus** [elastic/beats#23663]
When ingesting syslog data with TCP it would be good for the input to also support Octet Counting, ref: https://tools.ietf.org/html/rfc6587

When syslog data is received using Octet Counting the event starts with the length of the message, allowing syslog to send multiple messages that are not separated by newlines.

This issue is to track adding support for splitting syslog messages that uses this feature.

**Comment by martine-stratdat** [comment]
Octet counting has been part of remote syslog standards for a while.  There are now services that wont support new lines because of the issues they cause so I think this is important.
