### ISSUE TITLE
Sign Beats RPMs w/ SHA256 header for FIPS-enabled Operating Systems

### ISSUE THREAD

**Issue by n0othing** [elastic/beats#23670]
**Describe the enhancement:**

Beats RPMs will fail to install on RHEL 8 w/ FIPS mode enabled because the RPMs aren't signed with a SHA256 header (see `BZ#1581990` [1]. 

```
[robbie@rob-nix-06 ~]$ sudo rpm -ivh auditbeat-7.9.2-x86_64.rpm
warning: auditbeat-7.9.2-x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
        package auditbeat-7.9.2-1.x86_64 does not verify: no digest
```

It's possible to get around this by installing with `--nodigest --nofiledigest` arguments [2], but such a workaround may not be acceptable for certain organizations.

[1] https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.0_release_notes/index
[2] https://access.redhat.com/solutions/4460971

**Comment by ruflin** [comment]
There is currently some work ongoing in Elasticsearch, see https://github.com/elastic/elasticsearch/pull/75731 and the related issues / pull requests. We need to figure out we make this best happen as part of the build process.

**Comment by breskeby** [comment]
just for clarification. I think apart from the sha256 header digest also file digest needs to be switched from md5 (rpm default) to sha256. how are the beats rpms currently build? ES is using the nebula ospackage plugin which relies on redline, a java library for building rpms. We needed to patch this redline library to get sha256 header and sha256 payload + file digests in our ES RPMS

**Comment by andrewkroh** [comment]
The RPMs from beats are built using [fpm](https://github.com/jordansissel/fpm/wiki). FPM does have an `--rpm-digest` flag that appears to control the `_binary_filedigest_algorithm`.

https://github.com/jordansissel/fpm/blob/067f4ccfd07d228256ff313be4f9dc36e61055ee/templates/rpm.erb#L23-L27

https://github.com/elastic/beats/blob/5481b06b9c1c08ba9ab3214963c4b6e8614430f5/dev-tools/mage/pkgtypes.go#L712-L758

**Comment by andrewkroh** [comment]
Here's the update for FPM: https://github.com/elastic/golang-crossbuild/pull/118

**Comment by breskeby** [comment]
@andrewkroh that looks good IMO. For elasticsearch we have this output for the rpm I've tested succesfully on centos tips enabled:

```
rpm --checksig -v elasticsearch-8.0.0-SNAPSHOT-x86_64.rpm
elasticsearch-8.0.0-SNAPSHOT-x86_64.rpm:
    Header V4 RSA/SHA512 Signature, key ID d88e42b4: OK
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V4 RSA/SHA512 Signature, key ID d88e42b4: OK
```

**Comment by breskeby** [comment]
one thing I also needed to change is to use filedigestalgo to sha256 (defaults to md5) to get our rpm working. You should be able to test the RPM on one of our centos 8 fips enabled CI images

**Comment by andrewkroh** [comment]
And this is the change to Beats to add the `--rpm-digest` flag to FPM. https://github.com/elastic/beats/pull/27103
