### ISSUE TITLE
Formalize Guideline for adding a new process to the Elastic Agent.

### ISSUE THREAD

**Issue by ph** [elastic/beats#23696]
The elastic agent supports multiples process: filebeat, metricbeat, apm-server and heartbeat.
The current process to add a new binary to the Elastic Agent is ad-hoc and not documentated.
We should write documentation that explains the tasks to integration with Elastic agent.

The following list is incomplete:

- What is Program Specification.
- What are the supported operating system
- What the configuration look for the added input.
- What testing should be done on the Elastic Agent.
- Should we bundle the binary by default.

**Comment by faec** [comment]
Closing as this is now out of scope for this repository; good luck, https://github.com/elastic/elastic-agent!
