### ISSUE TITLE
Create docker image for Elastic Agent on Cloud

### ISSUE THREAD

**Issue by simitt** [elastic/beats#23697]
Create a docker image for Elastic Agent that can run the APM Server in the deprecated standalone mode, or in the managed mode. APM Server binary is bundled with the Elastic Agent, so no download is required. 

Ensure that the process startup script for the standalone APM Server is placed inside `init.d`. Any container healthcheck is only expected to check the Elastic Agent health, not the  APM Server process. 

The docker image should be usable in managed deployment environments and be opinionated about the default policy and which integrations to include: APM Server and Fleet Server. Default policy+integrations are expected to get set up when starting the container. 
Deployment relevant information, such as API Keys, URLs, configuration settings etc are passed into the container, most probably via ENV vars and must be picked up accordingly.

**Comment by jalvz** [comment]
@simitt should be this closed or is there anything else pending?

**Comment by simitt** [comment]
Yep, I'll close it.
