### ISSUE TITLE
Feature enhancement request -  Jira and Gitlab

### ISSUE THREAD

**Issue by krishnaprasadhg** [elastic/beats#23728]
Please consider the below enhancement requests for future release.

1. Jira monitoring/reporting/analytics module
2. Git hub monitoring/reporting/analytics module

**Comment by SHolzhauer** [comment]
A module in filebeat for Gitlab would be really nice.

I'm not that familiar with setting up and configuring Gitlab but it looks to me like there are multiple locations it can log to, does anyone know how much the log formats themself change?
