### ISSUE TITLE
'Info' level logs are generated when Agent logging level is set to 'Warning'.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#23735]
ON 7.11 BC5, we have observed issue at Agent logging level that Next level logs are getting generated for Agent under Logs tab when logging level is set to one step below in verbosity order. 
_**We have noticed it takes at least 5 mins to sync up and display logs as per level set.**_

**Preconditions**
1.  7.11BC5 Kibana Cloud environment should be available.
```
Artifact page: https://staging.elastic.co/7.11.0-903dc0b6/summary-7.11.0.html/
BUILD: 37827
COMMIT: d801a7bb08e17368584d00fbd97a5d0006285b51
```
2. Agent should be installed using a test policy [having system and endpoint integration].

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Agents tab. Click on Hostname. And navigate to logs section.
3. Notice, info level logs are displayed by default.
4. Change Agent logging level to 'Warning'. Apply changes and wait for confirmation message
5. Refresh browser. Notice, agent logging level updated.
6. Wait for 10-15 secs.

**Kibana version:** 7.11BC5 Kibana Cloud environment  

**Host OS and Browser version:** Windows 10, All

**Actual Result**
Observe, Info level logs are displayed for Agent under 'elastic-agent'.
Further, when error log level is applied, warning level logs are getting displayed.

**Expected Result**
Warning level logs should be displayed for Agents under 'elastic-agent' when Agent logging level is set to 'Warning'.

**Screenshots:** 
![Agent_log_level_error](https://user-images.githubusercontent.com/72375798/106147751-4416bd00-619e-11eb-9def-c2ba20814357.png)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please Review

**Comment by manishgupta-qasource** [comment]
Reviewed & assigend to @EricDavisX

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource can you confirm if you see anything after say 5 minutes?  I submit there is a complex interaction going on, and it is ok if the change is not immediate, I agree it is low priority.  If it takes 1-5 minutes for the final logs which may have already been written by Agent to be sent by monitoring Beat then it is ok by me and we can set the expectation as such.  If anything comes after a full 5 minutes we can investigate further.  Does that sound ok?  If so, you can comment and tag Michal or close it out.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

Thanks for the feedback.

We have re-validated this and observed functionality is working fine after 5 minutes.

Thus, closing this out. 

Further, we have one query.

**QUERY**: Could you please confirm about refresh button on Agent logs page. As currently, we hard refresh the browser for Agent logging level to update. It could be helpful if you could provide us any information regarding this.

Thanks
QAS

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have validated this issue on 7.11 BC5 Kibana cloud build . Build details are as follows:

```
BUILD 37827
COMMIT d801a7bb08e17368584d00fbd97a5d0006285b51
Artifact Link: https://staging.elastic.co/7.11.0-903dc0b6/downloads/beats/elastic-agent/elastic-agent-7.11.0-windows-x86_64.zip
```
**Observations:**
'debug' level log are getting displayed under elastic_agent.filebeat/metricbeat dataset even after 20 minutes of time when agent logging level was last updated.

**Screenshot:**
![23735](https://user-images.githubusercontent.com/72375798/106277735-923fc500-625f-11eb-8bff-859953002bda.png)

Thanks
QAS

**Comment by EricDavisX** [comment]
I have a hunch it should be less than 5 minutes, but the nuance is that the logs are being written to disk and picked up by the monitoring beat and being sent to ES and then being indexed and shown in Fleet - it is understandable for it to take a minute or so for the final logs that were already in progress to run their course.  5 minutes seems longer than I'd expect, but it is hard to get timing on this and I think it is an ok spec, so I'll halt research on my side at least.  :)

To your query @dikshachauhan-qasource , I have understood that if you open the date picker and re-apply the changes it will refresh the logs shown, which should be quicker than a full page refresh.  Can you assess how it feels on your side?

Also, I put this ticket in for a proper support or 'button' to refresh it:
https://github.com/elastic/kibana/issues/89042

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
Thanks for the feedback we have re-validated this issue on 7.11.0 Kibana Cloud environment. 
**Build details:**
```
Artifact link used: https://staging.elastic.co/7.11.0-903dc0b6/downloads/beats/elastic-agent/elastic-agent-7.11.0-windows-x86_64.zip
Build: 37827
Commit: d801a7bb08e17368584d00fbd97a5d0006285b51
```
**Observations:**
- We are able to fetch new logs on re-applying filters at date picker as per the updated agent logging level.

Please let us know if anything else is required.

Thanks
QAS

**Comment by EricDavisX** [comment]
I validated on latest 8.0 env, too - looks fixed to me.  I'm sure 7.11 BC6 with the fix will show it as well. we can re-test that soon too.
