### ISSUE TITLE
[build] Generator tests fail in 7.x

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#23758]
The generator tests are broken in the 7.* branches. The reason is that the generation step always pulls in beats from `master`. We should change the generator tests so that they pull in the current branch (or target branch for PRs). Or we should disable these tests on non-`master` branches since they don't reflect the status of the current branch.

It's always been a problem but now that master is on Go 1.15 and using newer APIs and 7.x is on Go 1.14 you have incompatibilities at generator build time.

The is the problem line: https://github.com/elastic/beats/blob/9e7321ac2bf9dc362a6416ac4aac6f6f1c4aa247/generator/common/Makefile#L40

So if there is some CI env var that we can use to override `origin/master` with the current branch or target branch for PRs then I think this would address the issue.

**Comment by andrewkroh** [comment]
Or an even simpler fix is to simply change the origin/master in each branch.

**Comment by v1v** [comment]
@andrewstucki  asked about some of the environment variables in the CI, see  https://github.com/elastic/apm-pipeline-library/issues/927 , that I think it's related to this particular issue

**Comment by andrewkroh** [comment]
Temporary fix for 7.x https://github.com/elastic/beats/pull/23761. A similar fix was already applied to 7.11.
