### ISSUE TITLE
Relay up to date Agent and Beats pids to Endpoint

### ISSUE THREAD

**Issue by ferullo** [elastic/beats#23759]
Endpoint is targeting 7.13 to add support for host isolation (an aggressive firewall). When a host is isolated it's important Agent and Endpoint are still able to connect to Kibana to receive updates (especially, an unisolate action). Endpoint can handle making sure that is the case without Agent changes.

We also expect a user will want Beats to continue to be able to stream data while the host is isolated. To make that happen, Endpoint needs to know the PID of each Beat Agent is running. So we'd like to add some data to the policy Endpoint is sent from Agent that lists all the PIDs Endpoint should allowlist.

**Comment by ph** [comment]
closing this as duplicate
