### ISSUE TITLE
[Elastic Agent] Report error if Fleet server is misconfigured

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#23753]
If the user installs fleet server, but it is not able to run because it is misconfigured, lacks credentials, or the credentials are no longer valid, or it is not able to contact Elasticsearch, report an error in the agent log file.

Related:
- https://github.com/elastic/fleet-server/issues/274

**Comment by ph** [comment]
@mostlyjason Is this still the case? talking with the teams we are reporting these kind problems now in the log.

**Comment by mostlyjason** [comment]
@ph if its already done thats great! Would it be worthwhile to have QA test these cases?

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

Can you please share steps with us hoe to expire credentials and validated above scenario.

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource hi, I don't know.  we'll have to research it.  First step is to define what tests we want to run.  Can you start working a list, and we'll get engineering to sign off on each (and we can test and verify behavior, too).

- [ ] when Fleet Server is enrolled / installed with missing, required param --fleet-server-es an error is put into the Fleet Server (or Agent?) log file
- [ ] when Fleet Server is enrolled / installed with missing, required 'token' param  an error is thrown to console
- [ ] when api token is revoked while Fleet Server is running
- [ ] when ES UI/pwd creds are changed after start up using them (and stack / fs are rebooted)
- [ ] others?

It would be nice to have @mostlyjason @ph help lay out what we want to ensure we test.  And it would be great to re-capture this info into an automation ticket (after we've discussed it) for the team to tackle / review.
