### ISSUE TITLE
Filebeat Cisco module parsing incorrect source/destination addresses for some events

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#23764]
There seems to an issue with this pattern in the filebeat Cisco module:
```
"Built %{network.direction} %{network.transport} connection %{_temp_.cisco.connection_id} for %{_temp_.cisco.source_interface}:%{source.address}/%{source.port} (%{_temp_.natsrcip}/%{_temp_.cisco.mapped_source_port}) to %{_temp_.cisco.destination_interface}:%{destination.address}/%{destination.port} (%{_temp_.natdstip}/%{_temp_.cisco.mapped_destination_port})"
```

It appears that the logic that determines source and destination addresses isn't quite as simple as it looks, and a few other products have run into basically the same gotcha: 

https://community.splunk.com/t5/All-Apps-and-Add-ons/Splunk-Add-on-for-Cisco-ASA-Is-parsing-of-src-ip-and-dest-ip/m-p/141121

https://community.microfocus.com/t5/ArcSight-User-Discussions/Cisco-PIX-ASA-Events-have-the-source-and-destination-in-the/td-p/1507325

Here's a discussion on the logic that determines direction: https://community.cisco.com/t5/network-security/asa-syslog-how-is-direction-determined-in-302013-302015/td-p/2008542

We'll probably need something a little more sophisticated to parse this.

@adriansr @andrewstucki

**Comment by threatangler-jp** [comment]
Thank you for opening this bug. We are willing to provide beta testing of changes made to the parsing if that is helpful to your progress.

**Comment by fearful-symmetry** [comment]
I see a bunch of associated merges, closing.

**Comment by Keunwool** [comment]
How did you solve this problem?
