### ISSUE TITLE
Unable to install Agent on windows 7 sp1 (32-bit)

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#23778]
**Kibana version:** 7.11BC5 Kibana Cloud environment  

**Host OS and Browser version:** Windows 7 sp1 32bit, All

**Preconditions**
1.  7.11BC5 Kibana Cloud environment should be available.
```
Artifact page: https://staging.elastic.co/7.11.0-903dc0b6/downloads/beats/elastic-agent/elastic-agent-7.11.0-windows-x86_64.zip
BUILD: 37827
COMMIT: d801a7bb08e17368584d00fbd97a5d0006285b51
```
2. Download and extract elastic agent zip file in c:/>program files

**Steps to reproduce:**
1. RDP to endpoint.
2. Open PowerShell>run as administrator
3. Run install agent command.

**Actual Result**
Observe, below error message displayed: "Program 'elastic-agent.exe' failed to run: The specified executable is not a valid application for this OS platform. At line:1 char:1"

**Expected Result**
Elastic-agent should be installed successfully.

**Screenshots:** 

![image](https://user-images.githubusercontent.com/72375798/106460288-1e98f480-64b9-11eb-9436-48eeda2500dc.png)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
I think this is a simple mistake. 

elastic-agent-7.11.0-windows-x86.zip
 is the correct one for x86.  desc above shows:
elastic-agent-7.11.0-windows-x86_64.zip

@dikshachauhan-qasource can you re-test with the x86 artifact?  You listed the x64 artifact in the repo steps (very helpful!).  We know that the x64 won't work on x86 so this is expected.  And the error message is helpful, so we can close this out if you are ok.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX

Thank you for correcting us.

We have retested above issue with x86 artifact and found it Working fine

We are able to deploy agent . Hence, closing this issue. Sorry for the confusion.

Thanks
QAS
