### ISSUE TITLE
Support creating Docker images regardless of arch for all platforms

### ISSUE THREAD

**Issue by kvch** [elastic/beats#23775]
The advantage of this approach is that we could continue cross-building all the packages from any machine supporting a linux/amd64 docker runtime. The same way that we cross-build other packages. Also, a similar approach could also work for windows images, something that we would like to support sooner than later (https://github.com/elastic/beats/issues/16814).

However, we would need to refactor the Dockerfiles to prepare all files in previous stages, and to avoid running any command with `RUN` in the last platform-specific stage. 

As the users can use ARM-based images with the current approach as well, this is a nice to have feature for the future.

Based on the idea of @jsoriano in https://github.com/elastic/beats/pull/23592#issuecomment-769876155

For example this Dockerfile generates a `linux/arm64` image with mage for arm64 from an amd64 machine, without buildx or special images:
```
FROM golang:1.15 AS build
ENV GOARCH=arm64 GOOS=linux
RUN go get -u -d github.com/magefile/mage
RUN go install github.com/magefile/mage

FROM --platform=linux/arm64 debian:stable-slim
COPY --from=build /go/bin/linux_arm64/mage /bin/mage
```
```
$ docker build . -t mage-arm64
...
Successfully tagged mage-arm64:latest
```
```
$ docker run -it --rm mage-arm64:latest /bin/mage
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error
```
```
$ docker inspect mage-arm64:latest | grep -A1 Architecture
        "Architecture": "arm64",
        "Os": "linux",
```

**Comment by jlind23** [comment]
ping @nimarezainia for prioritization

**Comment by nimarezainia** [comment]
@kvch what would be the effort involved in making the change? I can see the benefit to us but not so much an immediate direct customer benefit. If it's a small enough an effort we could address it in 8.3. lmk

**Comment by nimarezainia** [comment]
@mlunadia fyi. Could we get your input on this? whether we should go ahead with it or not. TIA

**Comment by mlunadia** [comment]
@nimarezainia I don't have data to assess the impact of doing this and provide a go/no go answer. 
IIUC the use case is deploying beats natively on windows (this is independent of the orchestration provided by Kubernetes) 
I can also see a more specific use case for deploying K8s on ARM, useful when working with edge devices.
Who would be the best person to provide info on use cases but more importantly data to help us understand the demand for this? 
cc: @akshay-saraswat

**Comment by kvch** [comment]
> what would be the effort involved in making the change? I can see the benefit to us but not so much an immediate direct customer benefit. If it's a small enough an effort we could address it in 8.3. lmk

On our side this is probably medium effort. But we also have to collaborate with the robots team and the infra team. Collaboration with multiple team could potentially slow it down because our issues are usually not as important to them as to us.

This issue was rather to record the idea we came up with. I would prefer to postpone this until there is a company-wide effort or an immediate customer benefit.
