### ISSUE TITLE
[Fleet]: Agent goes to "offline" state (after no user actions performed).

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#23781]
**Kibana version:** Kibana: 7.11.0 BC-5 Cloud environment

**Host OS and Browser version:** Windows 10, All

**Preconditions:**
1. 7.11.0 BC-5 Cloud environment should be available.

**Build Details:**
```
    Artifact link used: https://staging.elastic.co/7.11.0-903dc0b6/downloads/beats/filebeat/filebeat-7.11.0-windows-x86_64.zip
    BUILD: 37827
    COMMIT: d801a7bb08e17368584d00fbd97a5d0006285b51
```
2. Agent must be enrolled with default name policy.

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Navigate to Agents tab. 
3. Open agent> "Logs" tab in another browser tab.
4. Leave the environment for 5-10 minutes.
5. Observe that agent goes to "offline" state due to inactivity.
6. Observe "error: Status code: 503" under agent "Logs" tab.

**Reference ticket:**
https://github.com/elastic/beats/issues/23756

**Expected Result:**
Agent should not go to "offline" state due to inactivity.

**Screenshots:**
![offline](https://user-images.githubusercontent.com/77374876/106467515-c49d2c80-64c2-11eb-8e53-8589b4237568.png)

**Note:**
We have observed the same issue on:
- agent installed on Linux.
- v8.0.0 SNAPSHOT agent.

It is observed that this issue was due to inactivity and not because of network issues on endpoint.
After changing tabs on the cloud environment, agent status goes back to "Healthy" state.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource  Please review. Thanks

**Comment by EricDavisX** [comment]
@nchaulet this relates to other research we are doing, but may shed some light in terms of the user actions / use-case, with regards to user 'switching tabs' and it starts to show ok again?  If true it is certainly insightful.

**Comment by EricDavisX** [comment]
this issue is potentially fixed by https://github.com/elastic/kibana/pull/90066 - I am testing in latest snapshot of 7.11 with teh fix and I do not need any agent going unhealthy or off-line. I do however see a single instance of the 503 socket-hangup error in the logs.  Let us test more on the BC and with more agents, and assess - but it seems indeed a helpful fix.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this issue on 7.11 BC-7 Kibana Cloud Environment and found it as Fixed.

**Build details:**
```
Artifact link: https://staging.elastic.co/7.11.0-1f38d552/downloads/beats/elastic-agent/elastic-agent-7.11.0-windows-x86_64.zip
Build: 37897
Commit: 3f71ce7177a41e067ddb1e670ec4ace5f6d4f5fe
```
**Observations:**

-Agent don't go to "offline" state on inactivity and remains "Healthy" throughout.

Hence, closing this issue.

**Screenshots:**
![4](https://user-images.githubusercontent.com/77374876/107213086-ea2fb600-6a2d-11eb-8936-164365a2ba01.JPG)

Please let us know if anything else is required.

Thanks
QAS
