### ISSUE TITLE
Large http.request

### ISSUE THREAD

**Issue by hollligan** [elastic/beats#2378]
Hello, please help to get rid of the error in the PacketBeat, again.
I was faced with the problem of parsing large requests.

I use **PacketBeat** ver 1.2.3, the problem is also repeated on 5.0.0-alpha5 & [alpha6](https://beats-nightlies.s3.amazonaws.com/packetbeat/packetbeat-5.0.0-alpha6-SNAPSHOT-windows-x86_64.zip).

**error message:**
```
2016/08/24 18:06:00.797975 http.go:421: WARN Response from unknown transaction.
Ingoring. 
```
https://github.com/elastic/beats/blob/1.2/packetbeat/protos/http/http.go#L421

If I understand correctly, it cannot collect the http.request?

**The error can be reproduced:** 
C:\temp\packetbeat> packetbeat.exe -e -I C:\temp\packetbeat\trace.pcap

Please note that paketbeat successfully parses the packet №1-14 and can not understand the other.

The trace dump.pcap and packetbeat.yml file in the attachment:
[dump.pcap](https://github.com/elastic/beats/files/436465/dump.pcap.txt)
[packetbeat.yml](https://github.com/elastic/beats/files/436467/packetbeat.yml.txt)

Thank you.

**Comment by ruflin** [comment]
@hollligan Is that the same issue reported in https://github.com/elastic/beats/issues/2201 ?

**Comment by monicasarbu** [comment]
Duplicates https://github.com/elastic/beats/issues/2201.

**Comment by hollligan** [comment]
@ruflin, no, it's a new problem

**Comment by monicasarbu** [comment]
@hollligan I have tried to reproduce the issue on windows server 2012 without any success. I have tried with alpha5 and the latest Packetbeat release from the [nightlies](https://beats-nightlies.s3.amazonaws.com/index.html). Can you please try it again on your side with the latest release? Thank you in advance.

**Comment by hollligan** [comment]
@monicasarbu, my problem was not with the big http.request as I assumed, and transactionTimeout. In packetbeat.yml was setting transaction_timeout: 2s. 
When specifying this option, I made two mistakes: 1) transaction_timeout not involved in http section (because I put three problem and not four) 2) value type must be int
As a consequence was set transaction_timeout default ([10s](https://github.com/elastic/beats/blob/1.2/packetbeat/protos/protos.go#L17)).

**This is not a bug, thank you for your time! Please close this question.**
