### ISSUE TITLE
which go version should we use?

### ISSUE THREAD

**Issue by linrl3** [elastic/beats#23797]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: go version go1.14 linux/amd64
- Operating System: 4.14.81.bm.21-amd64
- Discuss Forum URL:
- Steps to Reproduce: 

```bash
root@IP:/PATH/beats/auditbeat# make
go build -ldflags "-X github.com/elastic/beats/libbeat/version.buildTime=2021-02-02T05:53:06Z -X github.com/elastic/beats/libbeat/version.commit=2fb256182f1c973eea99b49e309297689a34e88e"
#github.com/elastic/beats/v7/libbeat/common/transport/tlscommon
../libbeat/common/transport/tlscommon/tls_config.go:112:3: unknown field 'VerifyConnection' in struct literal of type tls.Config
../libbeat/common/transport/tlscommon/tls_config.go:123:4: unknown field 'VerifyConnection' in struct literal of type tls.Config
../libbeat/common/transport/tlscommon/tls_config.go:141:4: unknown field 'VerifyConnection' in struct literal of type tls.Config
../libbeat/common/transport/tlscommon/tls_config.go:149:8: config.VerifyConnection undefined (type *tls.Config has no field or method VerifyConnection)
note: module requires Go 1.15
../libbeat/scripts/Makefile:137: recipe for target 'auditbeat' failed
make: *** [auditbeat] Error 2
```

Should I use go 1.15 or above to build beats?

**Comment by andresrc** [comment]
Hi, we are currently using 1.15.7, please check https://www.elastic.co/guide/en/beats/devguide/current/beats-contributing.html#setting-up-dev-environment
