### ISSUE TITLE
Filebeat : collect & parse CISCO APIC logs

### ISSUE THREAD

**Issue by gevraud** [elastic/beats#23815]
Hello,

We plan to use filebeat (CISCO and Fortinet) modules to collect Network logs.

We also have CISCO APIC and we want to collect the logs (https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/all/faults/guide/b_APIC_Faults_Errors/b_IFC_Faults_Errors_chapter_010.html) 

It should be cool if Filebeat could directly parse those logs too.

Do you plan to do this in any roadmap ?

Regards

**Comment by HaZet1968** [comment]
We have a CISCO APIC, too, and I am interested in a parser, too.

**Comment by HaZet1968** [comment]
Interested in it, too.
