### ISSUE TITLE
[Meta] Agent integration testing prioritization

### ISSUE THREAD

**Issue by ph** [elastic/beats#23821]
- [ ] **Upgrade Agent** tests. a 7.10 feature, we completed an initial test but it needed maintenance due to lack of ability to test during ‘ci’ process. elastic/e2e-testing#534
- [ ]  **Fleet Server** initial support in e2e-testing elastic/e2e-testing#438

**Comment by simitt** [comment]
Are there plans to have a basic environment setup that allows adding some integration tests for [Elastic Agent commands](https://github.com/elastic/beats/tree/master/x-pack/elastic-agent/pkg/agent/cmd)? 
For example, the container setup command has some complexity, and while having high level end-to-end tests in a dedicated repository is great, I believe bugs could be avoided and changes could be implemented with a higher level of confidence if we had some integration tests for these commands. 

Referencing [APM Server systemtests#fleettest setup](https://github.com/elastic/apm-server/tree/master/systemtest/fleettest) for inspiration.

**Comment by faec** [comment]
Obsolete / out of scope, closing
