### ISSUE TITLE
When Agent starts up it logs an error about Watcher, we could add a log line to indicate this single error log line is expected

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#23850]
Version 7.11+ Elastic Agent

From slack:
watcher tries to load update file, if it is not present it logs error and exits. might be misleading but we need to know in case after upgrade

Suggestion:
We can add a line to Agent logging to indicate this is ok and expected on start up, akin to what we have in Kibana browser output, see screenshot:

![Screen Shot 2021-02-04 at 9 17 43 AM](https://user-images.githubusercontent.com/12970373/106905670-807c7880-66ca-11eb-8ec6-a0889398832d.png)

In Agent it could say something like:
^ A single error about Watcher component on new Agent start up is expected!

**Comment by EricDavisX** [comment]
@michalpristas says he would consider this, not a bad idea.

**Comment by ph** [comment]
good point, @EricDavisX Do you have the error message somewhere or another issue? I believe the message your referrencing is this https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/pkg/agent/application/upgrade/step_mark.go#L58-L65

But I want to make sure.

**Comment by EricDavisX** [comment]
the log line I refer to is:
`[elastic_agent][error] failed to load markeropen C:\Program Files\Elastic\Agent\data\.update-marker: The system cannot find the file specified.`

**Comment by ph** [comment]
Maybe just doing something like this: 

- Set log level to "info"
- Change the message to "no .update-marker found, this is a new installation." ?

**Comment by EricDavisX** [comment]
I don't mind that at all - but I didn't want to presume to change the severity of the log message, if Info is acceptable, it is always nice not to throw any more Errors than we have to.

**Comment by ph** [comment]
We have change that log level to _info_ instead of error.
