### ISSUE TITLE
System memory usuage in Megabytes

### ISSUE THREAD

**Issue by premsompura** [elastic/beats#2387]
By default metricbeat generate **system.memory.used** in bytes. However I changed the **system.memory.used.bytes** to **system.memory.used.mb** in template and then reloaded the template but all in vain. It isn't that easy, is it?

I want not this but various metrics to be in Megabytes.

**Comment by ruflin** [comment]
Closing this in favor of https://discuss.elastic.co/t/system-memory-usuage-in-mbytes/58913/1 as we want to keep Github issue for confirmed bugs. Please do not double post.

**Comment by premsompura** [comment]
but no one has replied.

**Comment by ruflin** [comment]
@premsompura You waited less then a day for a response. Please be patient.
