### ISSUE TITLE
"error: loading config file" while installing Filebeat for MAC.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#23874]
**Kibana version:**
Kibana: 7.11.0 BC-6 Cloud environment

**Host OS and Browser version:**
Mac OS X 10.12, All

**Preconditions:**
1.  7.11.0 BC-6 Cloud environment should be available.

**Build Details:**
```
Artifact link: https://staging.elastic.co/7.11.0-af4ff60e/downloads/beats/filebeat/filebeat-7.11.0-darwin-x86_64.tar.gz
Build: 37890
Commit: 80030db683333591cf7de76bc6780c96e8b733a2
```
2. Download Filebeat darwin .tar file and extract at /users/zeus/

**Steps to reproduce:**
1. Connect to Kibana cloud environment by providing cloud.id and cloud.auth in filebeat.yml.

2. Enable system modules from Filebeat installation directory:
zeus/Filebeat> sudo chmod go-w /home/zeus/Filebeat/filebeat.yml
zeus/Filebeat> sudo chown root filebeat.yml
zeus/Filebeat> ./filebeat modules enable system

3. Setup assets from installation directory and run:
zeus/Filebeat> ./filebeat setup -e

4. Observe "error: loading config file" after running setup command.

**Reference ticket Id:**
https://github.com/elastic/observability-test-plans/issues/88

**Expected Result:**
Filebeat should be installed as per [Filebeat quick start: installation and configuration](https://www.elastic.co/guide/en/beats/filebeat/7.x/filebeat-installation-configuration.html.)

**Screenshots:**
![11](https://user-images.githubusercontent.com/77374876/107037941-d5f77900-67e1-11eb-904a-39d3554d6a1f.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review. Thanks

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by ph** [comment]
Like I've mentioned in the other issues, this is not an issue there are check in place to check what is the ownership of the files, we enforce that behavior. Like I've said using sudo will not change the ownership owner chown will.

**Comment by EricDavisX** [comment]
Thanks PH, I don't think myself (or test team) understood the implications prior.  We split this off from the other ticket for clarity and can follow through now, on test side.

@amolnater-qasource if you want to re-try with modified chown call that is good, we can update test content to reflect the needed setup.  Thanks all.
