### ISSUE TITLE
'fields' should be omitted when null - problem still exist

### ISSUE THREAD

**Issue by crashev** [elastic/beats#2390]
The problems with 'fields' attribute described:

- https://github.com/elastic/filebeat/issues/126
- https://github.com/elastic/beats/issues/899

still exist in 1.2.3 version.
It is still being sent as:

016-08-26T13:53:15+02:00 DBG  Publish: {
  "@timestamp": "2016-08-26T11:53:07.533Z",
  "beat": {
    "hostname": "apibackends",
    "name": "apibackends"
  },
  "count": 1,
  "fields": null,
  "input_type": "log",
.....

Will it be finally fixed or there was another resolution of this problem that I missed?

**Comment by andrewkroh** [comment]
I re-opened #899. Thanks for reporting.
