### ISSUE TITLE
s390x support for Beats Jenkins CI

### ISSUE THREAD

**Issue by vibhutisawant** [elastic/beats#23918]
**Describe the enhancement:**
Add s390x arch to Beats Jenkins CI

**Describe a specific use case for the enhancement or feature:**
As per the discussion [here ](https://discuss.elastic.co/t/s390x-support-for-beats/263382), raising this issue to add s390x support in Beats Jenkins CI for build and test execution.We can provide linux/s390x VM if required. Please let us know if any help is needed from our end.

**Comment by vibhutisawant** [comment]
Hi @andresrc, Any update on this?

**Comment by andresrc** [comment]
Thanks @vibhutisawant . I'm afraid we don't expect to move forward with this in the near feature, as there are other priorities for the CI environment.

**Comment by vibhutisawant** [comment]
Thanks @andresrc . We will be happy to help if things change in the future.
