### ISSUE TITLE
Elastic Agent Docker: agent always picks up the newest policy

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#23928]
Hi,

I'm working on the Kubernetes integration and just spotted a weird issue. Steps to reproduce:

1. Create a policy A.
2. Run new Docker container with Elastic Agent. The agent will get enrolled and will be assigned the newest available policy (policy A, not Default).

If I'm working on a policy which is not ready yet and suddenly a new agent boots up, it should pick up the Default policy.

**Comment by mtojek** [comment]
I have also found that Elastic Agent is trying to use non-active enrollment token by default.

<img width="1663" alt="Zrzut ekranu 2021-02-9 o 16 33 16" src="https://user-images.githubusercontent.com/14044910/107386972-ac499500-6af4-11eb-821a-9c816688a58a.png">

<img width="1656" alt="Zrzut ekranu 2021-02-9 o 16 33 31" src="https://user-images.githubusercontent.com/14044910/107386985-ae135880-6af4-11eb-8889-0ba61a0c2582.png">

**Comment by ph** [comment]
@mtojek Are you using the token associated with the Default policy.

**Comment by mtojek** [comment]
No, I'm not using any enrollment key and I expect from the Dockerized app to pick up the default one.

**Comment by ph** [comment]
I've talked with @mtojek on slack, and the [logic defined ](https://github.com/elastic/beats/blob/master/dev-tools/packaging/templates/docker/docker-entrypoint.elastic-agent.tmpl#L40) in our shell script lead to inconsistent behavior.

The pseudo logic should be something like this.

- Get the list of agent policies.
- Get id of the Default Agent policy
- If the Default Agent policy is not found raise an error and suggest using the API key instead.
-
@mtojek WDYT ^?

**Comment by mtojek** [comment]
Yes, this would be the ideal flow.

**Comment by nchaulet** [comment]
There is for sure a bug in the docker script but I am wondering if it’s the docker image we publicly distribute if yes, I think we should really avoid the user to provide the Kibana username and password and we should probably only allow to provide the enrollment token.

**Comment by mtojek** [comment]
One more point regarding tooling. We use auto-enrollment feature in elastic-package to test integrations, so it would be **backward-incompatible** to enforce passing the enrollment token.
Please keep in mind that it's a convenient option to quickly boot up the Agent in Docker or Kubernetes cluster using static resources: https://github.com/elastic/beats/blob/master/deploy/kubernetes/elastic-agent-kubernetes.yaml

**Comment by ycombinator** [comment]
++ to pseudo-logic suggested by @ph in https://github.com/elastic/beats/issues/23928#issuecomment-776040984. It will lead to deterministic behavior, which is a good thing.

**Comment by mtojek** [comment]
@ph @nchaulet could you please provide ETA on this issue? I'd like to know whether I should introduce a workaround for this bug in https://github.com/elastic/elastic-package/pull/246 . I'm fine with keeping the discussion whether the option is good or not, but it would be convenient to detach it from fixing for the reported issue.

**Comment by ph** [comment]
@mtojek I agree that fixing the behavior and doing the right think are separate discussion. @mtojek I think implementing the workaround and fixing the issue would take a similar amount of time, can you make a PR?

**Comment by ph** [comment]
I think we can close this will the recent changes for the Elastic Agent and Fleet server?
