### ISSUE TITLE
[Agent] no indication given in logs when the wrong architecture artifact is attempted like x86 artifact on x64 Windows

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#23950]
we could reasonably at least send a note to the logging 'error' level in Agent when this is detected, right?  tested with BC8 on 7.11 on cloud stack deploy with the Agent host behind the Endgame VPN.

Perhaps we could handle it more gracefully even, but that is a larger ticket item, clearly.  For a quick win do we want to put some enhanced logging in place?

The Security Engineering Productivity team accidentally set up a win 10 x64 host with the x86.zip artifact and we found nothin in the logs that helped us triage it.  might be nice to cover just one more known scenario of user error.

here are the error logs we did see:
[win10-x64-with-x86-artifact-installed-agent-error-logs.log](https://github.com/elastic/beats/files/5954023/win10-x64-with-x86-artifact-installed-agent-error-logs.log)

and here are the first 5 mins of full debug logging for Agent & Endpoint
[win10-x64-with-x86-artifact-installed-agent-full-logs-first-5-mins.log](https://github.com/elastic/beats/files/5954021/win10-x64-with-x86-artifact-installed-agent-full-logs-first-5-mins.log)

**Comment by ph** [comment]
Going to close this one in favor of https://github.com/elastic/beats/issues/24092
