### ISSUE TITLE
[Heartbeat] Process status code should not be used as error message for synthetics

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#23981]
Synthetics now returns an exit code of (1) when a run fails. Now the uptime UI is showing that as the error message when it should show the step error message instead.
![image](https://user-images.githubusercontent.com/131427/107578872-edf04380-6bb9-11eb-94e8-b1bab267593f.png)

**Comment by paulb-elastic** [comment]
7.11 has already gone, so bumping this to 7.12

**Comment by paulb-elastic** [comment]
Thia has been fixed in https://github.com/elastic/beats/pull/24194
