### ISSUE TITLE
[Elastic Agent] Support memory queue configuration

### ISSUE THREAD

**Issue by simitt** [elastic/beats#23993]
The `queue.*` parameters in combination with `output.elasticsearch.bulk_max_size` and `output.elasticsearch.worker` are the most important settings to tune when scaling an APM Server deployment. Therefore it is important that the `queue.*` params are still supported; it is a requirement for running APM Server managed by Elastic Agent on cloud. 

Different queue configurations should be allowed per sub process, as they will expect different workloads. Generally it is recommended to choose the queue settings in alignment with the above mentioned elasticsearch settings. While only one global output can be configured at the moment, the queue settings should still be configurable per sub process.   

This probably requires changes in the [memqueue](https://github.com/elastic/beats/tree/master/libbeat/publisher/queue/memqueue) to make it reloadable. 

cc @ph, @ruflin, @urso

**Comment by urso** [comment]
Hm, I would rather see the memory queue to be removed in the future. In context of agent the memory queue would become an output setting, although it is somewhat unfortunated that each Beat will have it's own output.

**Comment by simitt** [comment]
We will need some support to configure the queue for 7.x when APM Server is managed by Elastic Agent. This is important to be able to scale the APM Server.

**Comment by ruflin** [comment]
@simitt As a temporary solution, would it be enough to configure it through the input part and apm-server translates it to the correct place?

**Comment by simitt** [comment]
Configuration wise it would be fine to configure within the APM Server input vars; but we still need to have a solution in beats for actually applying the queue settings to the memory queue. This cannot be done by the APM Server code itself. Probably something similar to [libbeat/cmd/instance/beat.go](https://github.com/elastic/beats/blob/ef6274d0d1e36308a333cbed69846a1bd63528ae/libbeat/cmd/instance/beat.go#L351) would be required in beats.

**Comment by ph** [comment]
It is just me or having the queue defined in the input or adding it to the output requires the same amount of work, which to makes the queue reloadable? I don't think restarting the beats is an option here?

**Comment by simitt** [comment]
I believe the difference would be that currently only one global output can be configured, but the queue size should be configurable per sub process (e.g. having a different queue size for APM Server than for metricbeat, as the event size probably differs etc.). 
Agree that applying the queue settings needs to be done in libbeat in both cases.

**Comment by ruflin** [comment]
Reloading would definitively not be nice but I think today this is what happens with apm-server legacy if the queue config is changed?

**Comment by simitt** [comment]
Closing this in favor of https://github.com/elastic/beats/issues/26638
