### ISSUE TITLE
[Elastic Agent] Starting docker container when enrollment 

### ISSUE THREAD

**Issue by simitt** [elastic/beats#24033]
It seems https://github.com/elastic/beats/pull/23973 introduced a regression for when starting the Elastic Agent docker container. 
When starting the container by not providing an enrollment token, the script fails with `/usr/local/bin/docker-entrypoint: line 43: ${$apikeyId}: bad substitution`.

It seems the additional '$' in [`${$apikeyId}`](https://github.com/elastic/beats/pull/23973/files#diff-048470c984e7ec3c816bd8a28cf489f7a042dd44bb896bfc7094792b6e2ed01eR43) is the root cause.

**Comment by mtojek** [comment]
Fix in-progress: https://github.com/elastic/beats/pull/24036

**Comment by simitt** [comment]
I had it self-assigned and put up a PR already https://github.com/elastic/beats/pull/24035 :) 
Closing in favor of your fix then.

**Comment by ph** [comment]
closing #24036 is merged.
