### ISSUE TITLE
[Filebeat] Add automated tests for modules using httpjson input

### ISSUE THREAD

**Issue by P1llus** [elastic/beats#24032]
This issue is to track any progress on automating tests on modules that utilizes the httpjson input.

The current modules that uses httpjson are:

- [x] google_workspace
- [ ] gsuite
- [ ] microsoft
- [ ] threat_intel
- [ ] snyk
- [ ] okta

There needs to be an initial discussion on a few things:

1. Should the tests be created for both modules and packages/integrations?
2. For modules **with** a public API endpoint available, should be use the real API or mock?
3. For modules **without** a public endpoint available, **but** has the possibility to set up something like a docker container, should we mock or test with docker? One example here is the `misp` fileset for the `threat_intel` module
4. For modules **without** any possibility to configure a running instance or a public endpoint, should we mock the API in some way?

**Implementation language**
For the language of choice it has to be a decision between python (currently used for the module tests) or golang (currently used for package/integration tests).
Personally I believe golang would be the appropriate choice, as it would match the package/integrations moving forward, but that does mean we would not test it on the original modules.

**High level overview and considerations**
Depending a bit on the outcome of the discussion points above, it could be implemented in several ways.

_Testing with public API endpoints:_
Public API endpoints do not return the same data each time, to what extent should a test pass or fail? Since data is not always the same, we cannot check the availability of certain fields, as they might not always be included, but we can check for errors or overall format.

_Testing with Docker containers:_
These tests seems to already been done in `package/integrations` repository, but would have similar concerns as the above.

_Testing with Mock API_
To create a mock API server, each package/integration would need to include a mock definition, for example in JSON or YAML, the definition would need to include something like this:
- The URL prefix
- The expected headers from the httpjson request
- The expected body of the httpjson request (if any)
- The response headers
- The response body
- The response code

It can either be an array of Mock definitions at the root level (package), or for each child (fileset).
Some more research would need to be done on how this process works, for example it would be more sufficient to have one Mock instance started once, so that it does not need to start up for each fileset.

**Comment by P1llus** [comment]
As mentioned by @andrewkroh in another issue, this is created to track future work on testing httpjson.

**Comment by andrewkroh** [comment]
Relates to this idea: https://github.com/andrewkroh/stream/issues/9

**Comment by jamiehynds** [comment]
@marc-gr is this issue still valid or can it be closed?

**Comment by andrewkroh** [comment]
The httpjson modules are now being tested againsts a mock http server provided by https://github.com/elastic/stream#http-server-mock-reference.
