### ISSUE TITLE
Support TLS connections to Zookeeper in Metricbeat Zookeeper module

### ISSUE THREAD

**Issue by bczifra** [elastic/beats#24058]
**Describe the enhancement:**
Introduce support for [TLS connections to Zookeeper](https://cwiki.apache.org/confluence/display/ZOOKEEPER/ZooKeeper+SSL+User+Guide) in the Metricbeat [Zookeeper module](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-zookeeper.html).

**Describe a specific use case for the enhancement or feature:**
Ensuring a secure connection between Metricbeat and Zookeeper.

**Comment by Kordishal** [comment]
This has not been implemented. Is it ever planned to implement this? Or should we switch to the HTTP module and use the Admin Server?
