### ISSUE TITLE
Confusing message about ccr metricsets on Elasticsearch module.

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/beats#24059]
If Elasticsearch xpack module is used against a non-platinum license, we get the message about `ccr` metricset:
```
the CCR feature is available with a platinum Elasticsearch license. You currently have a gold license. Either upgrade your license or remove the ccr metricset from your Elasticsearch module configuration.
```

We have a mandatory list of metricsets in case xpack is enabled.
The metricset `ccr` must be present and cannot be removed.
If we remove it, Metricbeat doesn't start and shows:
```
The elasticsearch module with xpack.enabled: true must have metricsets: [ccr cluster_stats index index_recovery index_summary ml_job node_stats shard]
```

I would suggest to amend the statement "or remove the ccr metricset from your Elasticsearch module configuration".

Ref: https://github.com/elastic/beats/issues/12327 https://github.com/elastic/beats/issues/8915

**Comment by Ahmadhashem86** [comment]
Is there any update about this issue! 
My monitoring cluster are not working now!

**Comment by Radiergummi** [comment]
Meh. This is *still* an issue on 8.13; metrics work, but every single minute, metricbeats will issue a warning log message like this one:
```
Apr 22 20:32:08 kibana.host.tld metricbeat[72595]: {"log.level":"warn","@timestamp":"2024-04-22T20:32:08.913+0200","log.logger":"elasticsearch.ccr","log.origin":{"function":"github.com/elastic/beats/v7/metricbeat/module/elasticsearch/ccr.(*MetricSet).Fetch","file.name":"ccr/ccr.go","file.line":78},"message":"the CCR feature is available with a platinum or enterprise Elasticsearch license. You currently have a basic license. Either upgrade your license or remove the ccr metricset from your Elasticsearch module configuration.","service.name":"metricbeat","ecs.version":"1.6.0"}
```

Do we really need a license for basic monitoring of Elasticsearch itself..?

**Comment by Idam7961** [comment]
any update?

**Comment by adrian-arapiles** [comment]
👍🏼
