### ISSUE TITLE
Filebeat kubernetes manifest is missing `nodes` in the ClusterRole

### ISSUE THREAD

**Issue by jeffspahr** [elastic/beats#24051]
For confirmed bugs, please report:
- Version: 7.11.0
- Operating System: Kubernetes v1.20.2+k3s1  on Ubuntu 20.04
- Steps to Reproduce: 

Deploy Filebeat from the latest manifest in the docs:
https://www.elastic.co/guide/en/beats/filebeat/7.11/running-on-kubernetes.html
curl -L -O https://raw.githubusercontent.com/elastic/beats/7.11/deploy/kubernetes/filebeat-kubernetes.yaml

Use the autodiscover config by doing the following:
    # To enable hints based autodiscover, remove `filebeat.inputs` configuration and uncomment this:

Filebeat starts up and is unable to list nodes:
>E0215 03:45:32.109053       7 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.4/tools/cache/reflector.go:156: Failed to watch *v1.Node: failed to list *v1.Node: nodes "k3s-01a.spahr.dev" is forbidden: User "system:serviceaccount:bourbontracker:filebeat" cannot list resource "nodes" in API group "" at the cluster scope
>E0215 03:45:33.243209       7 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.4/tools/cache/reflector.go:156: Failed to watch *v1.Node: failed to list *v1.Node: nodes "k3s-01a.spahr.dev" is forbidden: User "system:serviceaccount:bourbontracker:filebeat" cannot list resource "nodes" in API group "" at the cluster scope

This error goes away after adding `nodes` to the ClusterRole.

``` diff
diff --git a/deploy/kubernetes/filebeat-kubernetes.yaml b/deploy/kubernetes/filebeat-kubernetes.yaml
index 6c98c85f3..85e971762 100644
--- a/deploy/kubernetes/filebeat-kubernetes.yaml
+++ b/deploy/kubernetes/filebeat-kubernetes.yaml
@@ -151,6 +151,7 @@ rules:
   resources:
   - namespaces
   - pods
+  - nodes
   verbs:
   - get
   - watch
```

**Comment by maggieghamry** [comment]
@jeffspahr and @ChrsMark , FYI this same issue is occurring for Metricbeat on `7.11` as well; is there an issue for that as well?
