### ISSUE TITLE
Exposing Data from Agent and APM Server

### ISSUE THREAD

**Issue by ph** [elastic/beats#24091]
Make the `http.endpoint` configurable for the APM Server, Elastic Agent and Fleet Server to bind to a TCP port in addition to the default socket. The exposed metric endpoints can be used by Cloud metricbeats to collect data. If this is not possible, take a look at the alternative solution (which has more drawbacks).

The APM Server http endpoint reports data in the same format as currently, but _cgroup_ data have a different meaning. They include the consolidated resource usage from the whole cgroup, so the Elastic Agent, APM Server and all other running sub processes (in the cloud case only Fleet Server for phase 1). The APM Server additionally reports its process system usage and custom metrics.

**Comment by ph** [comment]
@ruflin You ping me a few weeks ago and asked me if it could be possible that the Elastic Agent exposes an HTTP endpoint for the metrics and proxy the calls to the running processes? Is that what the above implies?

**Comment by simitt** [comment]
Alternative: Add API to Elastic Agent to expose metrics for itself and all sub processes. The tricky part is that Elastic Agent itself does not collect the metrics, but it would avoid having to expose multiple ports, and the current logic for collecting metrics via sockets could be reused. 
This could potentially also be used as a healthcheck endpoint.

**Comment by ph** [comment]
@simitt OK, this is exactly what @ruflin talked with me, I do not see it as terribly complicated to do, the thing is what we do when multiples processes are running, we just use different "path"  like /metricbeat, /apm-server, /filebeat, filebeat-monitoring

**Comment by ruflin** [comment]
I was thinking of the following:

* `/processes`: List of processes that are running
* `/process/{process-name}`: Details about the process, basically what we have today. If we even need two API endpoints for a single process, it could be `/process/{process-name}/foo`

The question is what we do about the 2 MB / FB instances. As you indidcated we could give them unique names and attach `-monitoring`. There is still the issue on what if we have 3MB instance because of multiple outputs. Perhaps the answer is, we don't support it yet.

**Comment by urso** [comment]
I would say instead of process name the API should expose the sub-processes via ids. Either PID or some UUID that is known internally by the agent. An stable UUID would be nice, such that if a process is restarted, the UUID did not change.

About API:

> `/processes`: List of processes that are running

Success response:
```
{
  ...
  "processes": [
    {
      "id": "<process id>",
      "pid": "...",
      "binary": "filebeat",
      "source": {
        "kind": "internal",
        "outputs": ["default"] // internal monitoring uses default output/pipeline?
      },
      // other status details?
    },
    {
      "id": "<process id>",
      "pid": "...",
      "binary": "filebeat",
      "source": {
        "kind": "fleet", // configured by user via fleet
        "outputs": ["default"] // name of "outputs", "pipeline" the process is associated with
      },
      // other status details?
    },
    {
      ...
    }
  ]
}
```

Error response:

```
{
  "type": "..."
  "reason": "..."
}
```

> /process/{process id}: Details about the process, basically what we have today. If we even need two API endpoints for a single process, it could be /process/{process id}/foo

+1. Replacing `name` with `id`, though.

**Comment by michalpristas** [comment]
i think what steffen proposed makes sense. 
we can generate ID which is unique enough e.g `{outputName}-{processName}-{monitoring:optional}`

does this mean that APM by having this endpoint at hand, will be able to monitor metrics for processes itself? 
other option would be for agent to serve as a proxy and when `/processes/{process_id}` is called then it would query beat itself. i dont see any advantage in this approach as APM would need to enumerate these still based on `/processes` response.

having agent to provide composed response in a similar manner as above: calling `/processes` would result on agent iterating over processes and composing a response with all the metrics collected. this may be not that optimal maybe as one slow responder would slow down the whole process. in this case this endpoint could not be used as healthcheck as well. 

@simitt what approach would you prefer from APM side of view, or just correct me if my assumption is wrong somewhere

**Comment by simitt** [comment]
I think generally the proposal makes sense. In case a caller wants to fetch all metrics from all (sub) processes wouldn't it also make sense to support a query string param to include the details already in the `processes` request?

Additional note: The Elastic Agent should also expose itself and its own metrics as a process.

**Comment by michalpristas** [comment]
> make sense to support a query string param to include the details already in the processes request?

do you mean metrics themselves or what kind of details?

**Comment by simitt** [comment]
yes metrics themselves, so basically including the information that would be sent when requesting `/processes/{process_id}`. 
The reason I am asking is that this way it would be easier to consume from cloud.

**Comment by michalpristas** [comment]
i think this sounds doable. what kind of metrics are you interested in, regular beats module or something on top of it?

**Comment by simitt** [comment]
I believe it would make sense to keep the exposed metrics in sync with the metrics that are exposed by every process via the socket. So it would be up to every process which metrics it exposes, but I am generally thinking of resource usage related + event processing data.

**Comment by michalpristas** [comment]
@simitt i linked a draft PR here. it exposes both list of processes in a form Steffen described and detailed view which is just a proxy to `/stats` of the beat itself. 
sample responses are there i tested this on ubuntu and windows.
please feel free to run this locally and see if there's something missing, form is wrong etc...for your needs
