### ISSUE TITLE
[filebeat][netflow] filebeat does't start when internal_networks variable isn't defined in config file

### ISSUE THREAD

**Issue by abraxxa** [elastic/beats#24094]
- Version: 7.11.1
- Operating System: Ubuntu 18.04
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-netflow-module-do-not-start-after-update-to-7-11/264037/3
- Steps to Reproduce: enable the netflow module without the internal_networks variable defined in its yaml config file

The new variable 'internal_networks' is also neither documented in https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-netflow.html nor https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-netflow.html.

Error messages from `journalctl -u filebeat --no-pager`:
```
Feb 18 09:38:03 tsa-tc-tsses-1 filebeat[2411]: 2021-02-18T09:38:03.352+0100        INFO        instance/beat.go:474        filebeat stopped.
Feb 18 09:38:03 tsa-tc-tsses-1 filebeat[2411]: 2021-02-18T09:38:03.352+0100        ERROR        instance/beat.go:971        Exiting: Failed to start crawler: creating module reloader failed: could not create module registry for filesets: Error getting config for fileset netflow/log: Error interpreting the template of the input: template: text:8:5: executing "text" at <.internal_networks>: map has no entry for key "internal_networks"
Feb 18 09:38:03 tsa-tc-tsses-1 filebeat[2411]: Exiting: Failed to start crawler: creating module reloader failed: could not create module registry for filesets: Error getting config for fileset netflow/log: Error interpreting the template of the input: template: text:8:5: executing "text" at <.internal_networks>: map has no entry for key "internal_networks"
```

**Comment by andrewkroh** [comment]
I opened a fix at https://github.com/elastic/beats/pull/24110.

To workaround the issue you'll have to update the module config to add the `var.private_networks` like at https://github.com/elastic/beats/blob/dc2d84991ce074b82744fc6980241cba6607c49e/x-pack/filebeat/modules.d/netflow.yml.disabled#L13-L14.
