### ISSUE TITLE
bit-depth check in Agent / Beats to prevent x86 artifact from running on x64 env

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#24092]
No installation error for a 32-Bit agent on a 64-Bit windows machine & agent goes to unhealthy state after successful installation

tested on 7.11.1 and was discussed with Endpoint team.  

there are multiple options to fix, but we decided to
be more strict and do "Agent refuses to install on 32bits of itself on 64 bit machines

AC
- [ ] Beats x86 should refuses to starts on x64.
- [ ] Elastic Agent x86 should refuse to install and starts on x64.

**Comment by EricDavisX** [comment]
@ph @urso fyi

**Comment by urso** [comment]
@michalpristas can you look into this?

**Comment by ph** [comment]
@faec I've clarified the Acceptance criteria on this issue.
