### ISSUE TITLE
Payload content length greater than maximum allowed: 1048576

### ISSUE THREAD

**Issue by biswabhusandash** [elastic/beats#24119]
We are working to capture logs from server to elasticsearch by filebeat. We are getting below issue, while setup the filebeat.

Response: {"statusCode":413,"error":"Request Entity Too Large","message":"Payload content length greater than maximum allowed: 1048576"}

We have added http.max_content_length: 1200mb in elasticsearch.yml and server.maxPayloadBytes: 26214400 in kibana.yml. Still this issue is there.

How to resolve this issue?

Here is the YML files we are using for FileBeat, ElasticSearch & Kibana

**FileBeat.yml**

filebeat.inputs:

type: log

enabled: true paths:

c:\logs\XXX*
type: filestream

enabled: false

paths:

/var/log/*.log
filebeat.config.modules: path: ${path.config}/modules.d/*.yml

reload.enabled: false

setup.template.settings: index.number_of_shards: 1

setup.kibana:

host: "0.0.0.0:0000"
username: "XXXX"
password: "XXXX"
output.elasticsearch: hosts: ["0.0.0.0:0000"]

username: "XXXX" password: "XXXX"

processors:

add_host_metadata: when.not.contains.tags: forwarded
add_cloud_metadata: ~
add_docker_metadata: ~
add_kubernetes_metadata: ~

**ElasticSearch.yml**

module: elasticsearch server: enabled: true

gc: enabled: true

audit: enabled: true

slowlog: enabled: true

deprecation: enabled: true

access: var.paths: ["/var/logs/XXX/XXX.log"]

http.max_content_length: 1200mb

**Kibana.yml**

module: kibana

log: enabled: true

audit: enabled: true

server.maxPayloadBytes: 26214400

**Comment by andresrc** [comment]
Thank you very much for creating this issue. However, we would kindly like to ask you to post all questions and issues on the [Discuss forum](https://discuss.elastic.co/c/beats) first. In addition to awesome, knowledgeable community contributors, core Beats developers are on the forums every single day to help you out as well. So, your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue with the new information or open a new one.
