### ISSUE TITLE
[Heartbeat] Add `synthetics.step.status` field

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#24141]
It looks like we have a use for searching for steps based on status as demonstrated here: https://github.com/elastic/kibana/pull/90978/files#r579505168 . This should be easy to add.

**Comment by justinkambic** [comment]
This field is present in the mapping:

![image](https://user-images.githubusercontent.com/18429259/117022304-23429400-acc6-11eb-95dc-f9772c46da83.png)

**Comment by justinkambic** [comment]
This field is present in my mapping: 
![image](https://user-images.githubusercontent.com/18429259/117022477-4705da00-acc6-11eb-8708-a6b6340ae6d9.png)
