### ISSUE TITLE
Elasticsearch template check treats non-200 response as "template not found"

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/beats#24144]
Today at startup/reconnection we check for template existence with a call to `GET /_cat/templates`, which confirms the template exists if it returns 200 OK and the response contains the template name:

https://github.com/elastic/beats/blob/a7f820f7a6a7ef158d76bf5c53efe4a00159a882/libbeat/template/load.go#L157

If we think the template does not exist then by default we try and create it. This means that we are trying to create templates by default if:

- the template does not exist so the response is empty, although this is still 200 OK ✅ 
- the cluster is overwhelmed and returns a 429 ❌
- there's temporarily no master so we get a 503 ❌
- the request times out and a proxy returns a 499 or 504 ❌
- some other error occurred :question:

The trouble with treating an error as "the template does not exist" is that frequently the error is due to the cluster being overloaded, there are many Beats trying to reconnect, and the resulting [thundering horde](https://en.wikipedia.org/wiki/Thundering_herd_problem) of thousands of Beats all trying to create a template just makes everything worse. Elasticsearch today does its best to deal with no-op template creation but even so it is not completely trivial to check that any given template creation is a no-op.

Could we do something better with non-200 responses here? Retrying until success might be reasonable: if we can't even `GET /_cat/templates` successfully there's little point in proceeding with any indexing. If that's no good then could we at least treat an error as if the template does exist to avoid this common situation in an overloaded cluster?

Relates #17923, https://github.com/elastic/elasticsearch/pull/57851, https://github.com/elastic/elasticsearch/pull/64498

**Comment by urso** [comment]
Fix in progress in #24332

The `/_cat/templates` API returns "200 OK" no matter if the template exists or not. We will treat any status code but 200 as error and force exponential backoff, with random jitter, which over time should also reduce the number of Beats instances that concurrently ask for template availability. The backoff starts with a randomized time window of [500ms, 1s] and a max time windows of [30s, 60s] by default.

**Comment by DaveCTurner** [comment]
Sounds perfect, thanks @urso
