### ISSUE TITLE
[Elastic Agent] Allow separation of runtime state location and installation and executable location. 

### ISSUE THREAD

**Issue by pebrc** [elastic/beats#24160]
We ran into an issue on Kubernetes with ECK and Elastic Agent. The released version of ECK [has a bug](https://github.com/elastic/cloud-on-k8s/issues/4260) in that it does not use a `hostPath` volume we configure for the Elastic Agent data directory. The intention behind using a `hostPath` volume was to create a location for the runtime state of Agent to be persistent across container restarts. Fixing this issue has surfaced a problem with the planned approach in that we cannot just configure `--path.home` to be the `hostPath` volume on Kubernetes because Elastic Agent installs the programs it wants to run into that filesystem and tries to execute them from there as well but `hostPath` volumes are mounted `noexec` on Kubernetes. Running Elastic Agent as DaemonSet, as probably many users will want to do, means there is no good way to use persistent volumes as an alternative, which might not have the `noexec` restriction.

The current filesystem structure for the Elastic Agent Docker container seems to be roughly: 

`/usr/share/elastic-agent` => home **`--path.home`**
`/usr/share/elastic-agent/data` => data directory _derived from home_
`/usr/share/elastic-agent/data/elastic-agent-${hash}/run` => runtime state _derived from home_
`/usr/share/elastic-agent/data/elastic-agent-${hash}/install` => install location for the programs to execute **`agent.download.install_path`**
`/usr/share/elastic-agent/data/elastic-agent-${hash}/download` => download location for packages to install  **`agent.download.target_directory`**

If we had a way to separately configure the directory for the runtime state (presumably everything below `run`) that would allow us to sidestep this issue. The fact that the hash of the Elastic Agent build is part of the directory structure makes it very hard for an orchestrator to mount something on top of the directory without knowing that hash upfront or having such an explicit config option.

But even with the ability to configure a separate directory for runtime state, it would still be problematic that Elastic Agent would download and execute the packages in the filesystem of the Docker container. But I don't see a good way of addressing this other than effectively reimplementing a DaemonSet in the ECK operator and using persistent volumes that are not `hostPath` based.

**Comment by blakerouse** [comment]
This is actually a core issue that we need to solve for the K8s enablement for Elastic Agent. I linked this to the overall meta issue. #23613.

**Comment by blakerouse** [comment]
@ph I believe this needs to be done for 7.13.

**Comment by ph** [comment]
@blakerouse I have added to 7.13 iteration, can you add bit of details what need to changed in the Agent architecture?

**Comment by blakerouse** [comment]
@ph The bug description gives a good break down of the issue and the paths. I would need to dig into more on a proper way of fixing this.

I think I will pick this one, up because I believe that the new `container` subcommand I added will be the best place to handle this.

**Comment by ph** [comment]
Thanks @blakerouse I was missing context to assign it. thanks for grabbing it.

**Comment by simitt** [comment]
++ on the requirements for the cloud setup. 
Created https://github.com/elastic/beats/issues/24271 for a similar issue with the logs path configuration.
