### ISSUE TITLE
TestConfigurable Failure on Windows 2008|7|2012

### ISSUE THREAD

**Issue by ph** [elastic/beats#24166]
Build&Test  / x-pack/elastic-agent-windows-2008-windows-2008-r2 /  TestConfigurableFailed –  github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/operation | https://beats-ci.elastic.co/job/Beats/job/beats/job/master/228/ | test.status : "FAILED" | 2021-02-16 | 18
-- | -- | -- | -- | --
Build&Test  / x-pack/elastic-agent-windows-2008-windows-2008-r2 /  TestConfigurableFailed –  github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/operation | https://beats-ci.elastic.co/job/Beats/job/beats/job/7.x/216/ | test.status : "FAILED" | 2021-02-17 | 5
Build&Test  / x-pack/elastic-agent-windows-2008-windows-2008-r2 /  TestConfigurableFailed –  github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/operation | https://beats-ci.elastic.co/job/Beats/job/beats/job/7.x/97/ | test.status : "FAILED" | 2021-01-22 | 1
Build&Test  / x-pack/elastic-agent-windows-2008-windows-2008-r2 /  TestConfigurableFailed –  github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/operation | https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-23224/6/ | test.status : "FAILED" | 2021-01-29 | 1
Build&Test  / x-pack/elastic-agent-windows-2008-windows-2008-r2 /  TestConfigurableFailed –  github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/operation | https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-23997/1/ | test.status : "FAILED" | 2021-02-11 | 1
Build&Test / x-pack/elastic-agent-windows-2008-windows-2008-r2 / TestConfigurableFailed – operation | https://beats-ci.elastic.co/job/Beats/job/beats/job/7.11/18/ | test.status : "FAILED" | 2020-12-29 | 1
Build&Test / x-pack/elastic-agent-windows-2008-windows-2008-r2 / TestConfigurableFailed – operation | https://beats-ci.elastic.co/job/Beats/job/beats/job/7.11/95/ | test.status : "FAILED" | 2021-02-11 | 1
Build&Test / x-pack/elastic-agent-windows-2008-windows-2008-r2 / TestConfigurableFailed – operation | https://beats-ci.elastic.co/job/Beats/job/beats/job/master/841/ | test.status : "FAILED" | 2020-12-07 | 1
Build&Test / x-pack/elastic-agent-macos-macosx / TestConfigurableFailed – operation | https://beats-ci.elastic.co/job/Beats/job/beats/job/7.11/50/ | test.status : "FAILED" | 2021-01-20 | 1
Build&Test / x-pack/elastic-agent-macos-macosx / TestConfigurableFailed – operation | https://beats-ci.elastic.co/job/Beats/job/beats/job/master/38/ | test.status : "FAILED" | 2021-01-07 | 1
Build&Test  / x-pack/elastic-agent-windows-2012-windows-2012-r2 /  TestConfigurableFailed –  github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/operation | https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-23878/2/ | test.status : "FAILED" | 2021-02-05 | 1
Build&Test  / x-pack/elastic-agent-windows-7-windows-7 / TestConfigurableFailed –  github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/operation | https://beats-ci.elastic.co/job/Beats/job/beats/job/7.x/219/ | test.status : "FAILED" | 2021-02-17 | 1

**Comment by michalpristas** [comment]
this was worked upon here: https://github.com/elastic/beats/pull/25701
test is now enabled and not failing, closing
