### ISSUE TITLE
[Heartbeat] Make synthetics sandbox configurable, default to off

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#24171]
We should make the synthetics sandbox configurable, and default it to off, since this is required in most server-side envs. We've evaluated the security impact of this and don't believe it will be impactful except in rare circumstances.

**Comment by andrewvc** [comment]
dupe of https://github.com/elastic/beats/issues/22901

**Comment by justinkambic** [comment]
Applying `test-plan-ok` label to get this off of our test plan lists.
