### ISSUE TITLE
[ARM] Ubi8 Docker images are not included in the unified release

### ISSUE THREAD

**Issue by mdelapenya** [elastic/beats#24186]
Although Beats CI is generating the Ubi8 ARM Docker images for all beats (and pushed to our GCP bucket), the Unified Release Process is not generating those ubi8 images. See https://artifacts-api.elastic.co/v1/search/8.0.0-SNAPSHOT/elastic-agent?x-elastic-no-kpi=true

**Comment by jlind23** [comment]
@mdelapenya is it something we should keep open as relevant?

**Comment by mdelapenya** [comment]
I think this can be closed for now
