### ISSUE TITLE
Conflict when doing filebeat setup

### ISSUE THREAD

**Issue by QueenAmidala** [elastic/beats#24192]
Hi, 

I am posting this as a question because I am not sure if it is a bug. I will fill out the bug questions as if it were a bug report. But since I am not sure I am going to ask my question below. 

So here is my problem it seems filbeats setup is failing for me. I get a bunch of empty error messages

**"Exiting: 1 error: Error setting up ML for apache_ecs: 17 errors: ; ; ; ; ; ; ; ; ; ; error while".**

I'm thinking that this is because the error structure used by filebeats is wrong.
The structure is defined here: beats/importer.go at v7.11.1 · elastic/beats · GitHub.

And, the errors get appeneded here:beats/importer.go at v7.11.1 · elastic/beats · GitHub.

The errors in the response looks more like: kibana/types.ts at v7.11.1 · elastic/kibana · GitHub.

There was a merge request a while ago that looks like it changed the error responses [ML] Switching to new es client by jgowdyelastic · Pull Request elastic/kibana#74965 · elastic/kibana · GitHub.

Does anyone know if filebeats is representing errors incorrectly or is this just another kind of error it doesn't know about?

The errors are just datafeed and job conflicts which it looks like the code was trying to watch for.

Reference to: https://discuss.elastic.co/t/conflict-when-doing-filebeat-setup/265134

Here is my info for it incase it might be a bug:

**Elasticsearch version: 7.11**
**Server OS version:RHEL 8.2**
**Browser version: not used it is an image.**
**Browser OS version: not used**
**Original install method (e.g. download page, yum, from source, etc.): container**
**Describe the bug: see up above.**

**Comment by andresrc** [comment]
The current idea is to remove the ML jobs setup from the `setup` command. Please use the ML UI to set up the job, as mentioned in https://github.com/elastic/beats/issues/24192#issuecomment-784424127. Thanks!
