### ISSUE TITLE
Unable to install Linux .rpm and .deb agent on 7.12.0

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#24199]
**Kibana version:** 7.12.0 BC-2 Kibana Cloud environment

**Host OS and Browser version:** Linux Centos 8.0 and Debian 10, All

**Preconditions:**
1. 7.12.0 BC-2 Kibana cloud environment should be available.

**Build Details:**
```
Artifact link(.deb): https://staging.elastic.co/7.12.0-37f40745/downloads/beats/elastic-agent/elastic-agent-7.12.0-amd64.deb
Artifact link(.rpm): https://staging.elastic.co/7.12.0-37f40745/downloads/beats/elastic-agent/elastic-agent-7.12.0-x86_64.rpm
Build: 39000
Commit: 4f65a5a1268fa78f1af9117d12312e1cee433376
```
2. Linux .rpm and .deb packages must be extracted.

**Steps to reproduce:**
1. Login to Kibana Cloud environment.
2. Run `sudo elastic-agent enroll kibana-url enrollment-token ` command.
3. Observe `"Error: fail to enroll: fail to execute request to Kibana: 1 error occurred:
        * missing enrollment api key"` error.

**Expected Result:**
Agent should be successfully installed with linux .rpm and .deb package.

**Screenshot:**
![rpm deb](https://user-images.githubusercontent.com/77374876/108980735-02503800-76b2-11eb-9980-cded924ef64f.png)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have reported this issue to track down the .deb and .rpm fixes.

Thanks

**Comment by ph** [comment]
@mdelapenya @EricDavisX That should have been caught by the e2e testing?

**Comment by EricDavisX** [comment]
@ph it was, we updated the test, but I was waiting a day to see it pass routinely, and failed to realize we'd get the issue logged from manual test before then.  Sorry Amol!

@amolnater-qasource can you confirm if the deb / rpm install string is anywhere in the UI?  it would need to be updated if so.  If it is only in Docs, then we can leave this open for that Docs update.

See relating commit here that notes the simple change (just need to add the paramater 'api_key=' before you type in the api key in the command line
I don’t recall why this was decided for the change. The latest fix that relates is here, this was was for docker:
https://github.com/elastic/beats/commit/239f2438348c5550980ca2c50b164d18d9bba64b#diff-6dd8618b51eac33aa32251e23a4[…]b0c9f0dde459fafd03ab1dfde157344e
 
so the enrollment for Agent would look like:
enroll --url=<your kibana houst> --enrollment-token=<your api key>

Charlie helped us confirm it works today, please try again confirm back.

For now I'll ping @dedemorton that we want / need to update docs for 7.12 for this.

**Comment by dedemorton** [comment]
@EricDavisX So it looks like I simply need to update the docs anywhere the enroll command is described, correct?

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 

We have attempted to reinstall .rpm and .deb agents on 7.12.0 BC-2 and we are able to install with updated command:
 `sudo elastic-agent enroll --kibana-url= --enrollment-token=`

> can you confirm if the deb / rpm install string is anywhere in the UI?

No Eric, no installation command is available for .deb / .rpm on Kibana UI.
 
However this enrollment command needs to be updated for .deb and .rpm agent installation docs available under: [Install Elastic Agent](https://www.elastic.co/guide/en/fleet/7.12/elastic-agent-installation.html)

Please let us know if anything else is required.
Thanks

**Comment by EricDavisX** [comment]
@dedemorton hi - yes, that is correct.  And I can help on this one if you want.

Thank you Amol for highlighting.

**Comment by EricDavisX** [comment]
I think I got the PR right for the Docs update - here it is: https://github.com/elastic/observability-docs/pull/410

so I'll close this ticket out.  And @amolnater-qasource you can test the docs when it gets merged.

@dedemorton happy to help, if you'd kindly review the PR, we're all good here.
