### ISSUE TITLE
[Agent] Win 2016 OS host is Healthy status, but Metricbeat is failed (and not shipping data to ES)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#24212]
The team is testing on the latest BC of 7.12 and relating current snapshot builds (since BC was not usable)

Default Policy was used, with nothing else in it
 - though later / at some point we did try to add Endpoint in to compare / assess that as well
 
The 2 concers are:
1) why was Metricbeat unhealthy - which may be followed up in separate ticket already
2) why is Agent reporting 'healthy' when Metricbeat is failed (is this a feature request or a bug?)

I can attach logs
[elastic-agent-json (1).log](https://github.com/elastic/beats/files/6036865/elastic-agent-json.1.log)

**Comment by ph** [comment]
Weird, looking at the issue `{"log.level":"error","@timestamp":"2021-02-24T07:15:41.825-0500","log.origin":{"file.name":"process/start.go","file.line":130},"message":"failed writing connection info to spawned application: failed to write connection information: write |1: The pipe has been ended.","ecs.version":"1.6.0"}
`
The above logs is show really often in the logs, this would make me thinks there is something going on with the gRPC endpoint. @blakerouse or @michalpristas any ideas?

**Comment by muskangulati-qasource** [comment]
Hi @EricDavisX,

We saw this issue on the latest 7.12.0 BC2 build. Please find below the testing details:

**Build Details**:
```
Version: 7.12.0 BC2
Commit: 4f65a5a1268fa78f1af9117d12312e1cee433376
Build number: 39000
Artifact: https://staging.elastic.co/7.12.0-37f40745/summary-7.12.0.html
```

**Observations**:
- **Log**: [elastic_agent][error] failed writing connection info to spawned application: failed to write connection information: write |1: The pipe has been ended.'
- **Windows template**: Windows 10 Pro 1909
- **Metric beat**: Not working
- **Agent Status**: Unhealthy
- **Discover Tab**: 
![dicoverTab](https://user-images.githubusercontent.com/60252716/109150095-647e6b00-778e-11eb-810e-9ac93ef1bfd7.PNG)
- **Data Streams Tab**:
![DataStreams](https://user-images.githubusercontent.com/60252716/109147971-a823a580-778b-11eb-9c4a-b8052a5f8ed7.PNG)

Please let us know if anything else is required from our end.
Thanks!

**Comment by EricDavisX** [comment]
this sounds the same as in https://github.com/elastic/beats/issues/24180 - it is all related to Metricbeat state and being only partially unzipped.  And it is also seemingly a timing issue on lower spec'ed vm usage, so it is a performance / stability issue, too, hence why not all usage shows this.

**Comment by EricDavisX** [comment]
i'm going to close it as a duplicate actually - less noise and time spent as we know they are the same and we'll test rigorously anyhow when we get the fix.
