### ISSUE TITLE
Update Sysmon module for v13.01 (EID 24 and 25)

### ISSUE THREAD

**Issue by crimsoncore** [elastic/beats#24217]
Sysmon event ID 24 and 25 are missing from winlogbeat-sysmon.js

**Comment by jamiehynds** [comment]
Hi @crimsoncore - support for Sysmon v13 is being tracked in this issue, which we plan on addressing soon: https://github.com/elastic/beats/issues/21172

Could you provide sample events (sanitised is fine) for event ID 24 and 25? Thanks!

**Comment by crimsoncore** [comment]
sure here's the raw xml for EID 25

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Sysmon" Guid="{5770385f-c22a-43e0-bf4c-06f5698ffbd9}" /> 
  <EventID>25</EventID> 
  <Version>5</Version> 
  <Level>4</Level> 
  <Task>25</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2021-02-24T16:32:22.836773300Z" /> 
  <EventRecordID>10150325</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="3800" ThreadID="5080" /> 
  <Channel>Microsoft-Windows-Sysmon/Operational</Channel> 
  <Computer>DESKTOP-I9CQVAQ</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <EventData>
  <Data Name="RuleName">-</Data> 
  <Data Name="UtcTime">2021-02-24 16:32:22.833</Data> 
  <Data Name="ProcessGuid">{9497d8d9-7f96-6036-ec10-000000001000}</Data> 
  <Data Name="ProcessId">11916</Data> 
  <Data Name="Image">C:\Program Files\Git\mingw64\libexec\git-core\git.exe</Data> 
  <Data Name="Type">Image is replaced</Data> 
  </EventData>
  </Event>

**Comment by crimsoncore** [comment]
EventID 24

`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Sysmon" Guid="{5770385f-c22a-43e0-bf4c-06f5698ffbd9}" /> 
  <EventID>24</EventID> 
  <Version>5</Version> 
  <Level>4</Level> 
  <Task>24</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2021-02-25T09:36:21.965118200Z" /> 
  <EventRecordID>10423991</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="3800" ThreadID="10560" /> 
  <Channel>Microsoft-Windows-Sysmon/Operational</Channel> 
  <Computer>DESKTOP-I9CQVAQ</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <EventData>
  <Data Name="RuleName">-</Data> 
  <Data Name="UtcTime">2021-02-25 09:36:21.958</Data> 
  <Data Name="ProcessGuid">{9497d8d9-b70b-602f-fc07-000000001000}</Data> 
  <Data Name="ProcessId">1912</Data> 
  <Data Name="Image">C:\Windows\System32\cmd.exe</Data> 
  <Data Name="Session">1</Data> 
  <Data Name="ClientInfo">user: DESKTOP-I9CQVAQ\luks</Data> 
  <Data Name="Hashes">SHA256=B2426CAFF4AA3374CB39E32FBB0510B3507C8A26D565BDC7188A6EE9F209B1E0,IMPHASH=00000000000000000000000000000000</Data> 
  <Data Name="Archived">true</Data> 
  </EventData>
  </Event>`

**Comment by jamiehynds** [comment]
Thanks @crimsoncore, really helpful! Is there any chance you could export those two events to evtx from the Windows Event Viewer. We'll have all we need to update the module from there.

**Comment by crimsoncore** [comment]
[
[Archive.zip](https://github.com/elastic/beats/files/6043868/Archive.zip)

](url)

**Comment by jamiehynds** [comment]
Thanks very much @crimsoncore!

FYI @andrewkroh
