### ISSUE TITLE
Elapsed time calculation

### ISSUE THREAD

**Issue by trevorndodds** [elastic/beats#2422]
How about a feature for filebeat that will calculate the elapsed time between two regex tags within a log file and add the result as an extra field to the last tag line? 

Many of my log files follow the format below.
<date> "Start Task"
<date> ....
<date> "Finished Task"

It would be great if it could calculate the task time between the above tags. I've looked at trying to accomplish this with Elasticsearch or Kibana but I have not found a solution. 

I'm not sure how doable this is or what the implications would be.

**Comment by andrewkroh** [comment]
This sounds like a task for Logstash. Use a grok filter to extract the timestamps then an [elapsed](https://www.elastic.co/guide/en/logstash/current/plugins-filters-elapsed.html) filter to calculated the time difference.

**Comment by trevorndodds** [comment]
Thanks, I'll give it a try. I thought it may have been better to do it at the source. I'll work on a grok filter to try keep log files together as there is nothing unique on the log lines to match between other server log files.
