### ISSUE TITLE
[Elastic agent] Log rotation not clearing files

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#24249]
I have a Elastic Agent that has been running for over a month and although the log files are getting rotated, they don't appear to be deleted. This is filling up space on my HD. I expected they would be cleaned up at some interval shorter than a month, at least with the default settings. A full HD can cause machines to crash if it goes on long enough.

```
# ls -l /opt/Elastic/Agent/elastic-agent.log*
-rw------- 1 root root       85 Feb 23 06:45 elastic-agent.log
-rw------- 1 root root    54640 Feb 25 10:16 elastic-agent.log.1
-rw------- 1 root root   367464 Feb 23 06:35 elastic-agent.log.2
-rw------- 1 root root   799426 Feb 22 09:33 elastic-agent.log.3
-rw------- 1 root root   197002 Feb 21 06:55 elastic-agent.log.4
-rw------- 1 root root    57096 Feb 20 06:53 elastic-agent.log.5
-rw------- 1 root root 10245566 Feb 20 06:16 elastic-agent.log.6
-rw------- 1 root root   717155 Dec 25 07:09 elastic-agent.log.7
```

For confirmed bugs, please report:
- Version: 7.11.1
- Operating System: Debian
- Steps to Reproduce: Install an agent, let it run for several weeks, then look at the elastic-agent.log files

**Comment by ph** [comment]
This is a real problem, we are using the libbeat framework for the log handling, maybe we don't have the right default or something is missing.

**Comment by michalpristas** [comment]
just to mention our defaults. we use logp defaults for this one which is 
```
Files: FileConfig{
	MaxSize:         10 * 1024 * 1024,
	MaxBackups:      7,
	Permissions:     0600,
	Interval:        0,
	RotateOnStartup: true,
},
```

**Comment by EricDavisX** [comment]
I see via email that PH confirmed we can lower the priority on this - I'll note, getting this fixed soon still is a good priority!  It is ok if it doesn't make 7.12 though, but if the fixing pr isn't impactful it might be worth fixing and backporting to 7.12

**Comment by EricDavisX** [comment]
I am changing my mind already, removing 7.12.1 label - we should try super hard to keep patch release backports to a minimum as they can be very costly overall.

**Comment by mostlyjason** [comment]
Just to be clear on the behavior, the max size on disk is 10MB * 7 backups = 70MB? That seems reasonable and we can close this if thats true.

**Comment by ph** [comment]
Yeah this is the current behavior.
