### ISSUE TITLE
topBeat install from repositories links to filebeat install

### ISSUE THREAD

**Issue by chrisribe** [elastic/beats#2425]
This is simply put confusing...

The documentation for topbeat install:
https://www.elastic.co/guide/en/beats/topbeat/1.3/topbeat-installation.html

Links to the libbeat main setup document:
https://www.elastic.co/guide/en/beats/libbeat/current/setup-repositories.html

But those instructions contain apt-get install **filebeat** NOT apt-get install **topbeat**

Great product, but the documentation is not simple to follow. It's like bits of docs but not all linked together properly.

**Comment by dedemorton** [comment]
Thanks for taking time to give us feedback about the documentation. The topic about installing from our repositories is meant to describe how to install any Beat. We show Filebeat as an example, but I can see why the current structure might be confusing. Over time, I've been moving a lot of the shared libbeat content into the reference guides for each Beat. It sounds like I need to do the same with this topic. 

I'm also working on some changes for the upcoming 5.0 release that will hopefully address your concerns and make it easier for you to find content. 

Please let me know if you have specific feedback regarding how the docs are linked together (and where links are missing).  

Thanks for helping us improve the documentation.

**Comment by dedemorton** [comment]
Sorry it took me awhile to get around to this. Topbeat is legacy now, but I've updated the other Beats docs in #3601.
