### ISSUE TITLE
[Elastic Agent] docker image on cloud run without root privileges

### ISSUE THREAD

**Issue by simitt** [elastic/beats#24269]
The Elastic Agent docker image >= `8.0` needs to be runnable in cloud without root privileges and any cloud specific changes. The requirements are
* the HOME directory is owned by a non-root user 
* all data get written to a bind mount directory only

This issue is meant to keep track of these requirements and ensure they are fulfilled for the `8.0` docker image.

cc @mieciu

**Comment by mieciu** [comment]
That's correct. 

Just to clarify that "all data get written to a bind mount directory only" (as the container can get away with `--group-add 0`), the main concern is that if the user decides to run container like this: 
```
docker run --user $ARBITRARY_UID:$ARBITRARY_UID -v $HOST_PATH:/local_mount agent_image
```
we should have all the paths to which agent process wants to write to configurable (e.g. `--path.home /local_mount`, `--path.data /local_mount`).

**Comment by simitt** [comment]
@mieciu @jsoriano are you aware of anything left for this issue? I believe it can be closed, as the images have been replace.

**Comment by mieciu** [comment]
Correct, we can surely close this one
