### ISSUE TITLE
Locality values mismatch between Netflow input and ingest pipeline

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#24272]
For confirmed bugs, please report:
- Version: 7.11
- Operating System: -
- Discuss Forum URL: -
- Steps to Reproduce: -

Netflow input will populate {source,destination,flow}.locality fields with values either `private` or `public`, depending on the `internal_networks` configuration option.

The ingest pipeline for the netflow module uses those fields to populate `network.direction`. However, it is expecting the values to be `internal` or `external`, which causes `network.direction` to always be `unknown`.

**Comment by adriansr** [comment]
To clarify the issue:

The Netflow input will set locality fields to one of two possible values: `private` or `public`.

https://github.com/elastic/beats/blob/6986c8410d45164b7f1401b83215631353fb5165/x-pack/filebeat/input/netflow/convert.go#L385-L388

The Netflow module ingest pipeline uses those values to set `network.direction`, but it expects either `internal` or `external`:

https://github.com/elastic/beats/blob/6986c8410d45164b7f1401b83215631353fb5165/x-pack/filebeat/module/netflow/log/ingest/pipeline.yml#L54-L73


We need to choose which pair of values to use, private/public or internal/external.

**Comment by andrewkroh** [comment]
In addition to the mismatch of values, there is another bug that could be at play https://github.com/elastic/beats/pull/24110 since this would cause there to be no default value for internal_networks.
