### ISSUE TITLE
Build scripts download packages with read only access

### ISSUE THREAD

**Issue by v1v** [elastic/beats#24284]
### What

When using static workers then things can get ugly when the workspace cannot be deleted. This happens with the static CI workers.

```
jenkins@worker-0eaeecf32aca4fe3a:~/workspace$ ls -ltra Beats_beats_7.11/pkg/mod/github.com/\!shopify/toxiproxy@v2.1.4+incompatible/
total 200
-r--r--r--  1 jenkins jenkins     6 Mar  1 11:16 VERSION
-r--r--r--  1 jenkins jenkins   183 Mar  1 11:16 .travis.yml
-r--r--r--  1 jenkins jenkins 19165 Mar  1 11:16 README.md
-r--r--r--  1 jenkins jenkins  3016 Mar  1 11:16 Makefile
-r--r--r--  1 jenkins jenkins  1075 Mar  1 11:16 LICENSE
dr-xr-xr-x  2 jenkins jenkins  4096 Mar  1 11:16 Godeps
-r--r--r--  1 jenkins jenkins   131 Mar  1 11:16 .gitignore
dr-xr-xr-x  2 jenkins jenkins  4096 Mar  1 11:16 .github
-r--r--r--  1 jenkins jenkins   206 Mar  1 11:16 Dockerfile
-r--r--r--  1 jenkins jenkins  6693 Mar  1 11:16 CREATING_TOXICS.md
dr-xr-xr-x  2 jenkins jenkins  4096 Mar  1 11:16 client
drwxr-xr-x  3 jenkins jenkins  4096 Mar  1 11:16 ..
dr-x------ 12 jenkins jenkins  4096 Mar  1 11:16 .

```

https://github.com/elastic/beats/pull/24233 was added to mitigate this issue but I'm afraid it's still there.

I'd like the team to look for where in the magefiles those particular folders are downloaded and why with 0444 permissions.

**Comment by andrewkroh** [comment]
This looks like the contents of the Go package cache which defaults to being located at GOPATH/pkg IIRC. https://golang.org/cmd/go/#hdr-Build_and_test_caching

What's preventing these files from being deleted? That they are read-only 0444?

**Comment by v1v** [comment]
Exactly they are read only.

It also fails in windows


```
[2021-03-03T11:42:17.444Z] Also:   	Also:   java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\master-292\pkg\mod\bazil.org\fuse@v0.0.0-20160811212531-371fbbdaa898\doc
```

**Comment by andrewkroh** [comment]
https://golang.org/ref/mod#go-clean-modcache describes the problem as well as possible solutions.

> This [go clean -modcache] is usually the best way to remove the module cache. By default, most files and directories in the module cache are read-only to prevent tests and editors from unintentionally changing files after they've been authenticated. Unfortunately, this causes commands like rm -r to fail, since files can't be removed without first making their parent directories writable.
