### ISSUE TITLE
[Windows specific]: Metricbeat service is not started by itself and unable to unzip completely at Endpoint under Elastic folder.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#24317]
**Kibana version:** 7.12 BC3 Kibana Cloud environment 

**Host OS and Browser version:** Windows 10, All

**Preconditions**
1.  7.12 BC3 Kibana Cloud environment should be available.
```
Build: 39134
Commit: 08417cbd6c15e4c866651a7dcdfeded58845206d
Artifact link: https://staging.elastic.co/7.12.0-96914cb5/downloads/beats/elastic-agent/elastic-agent-7.12.0-windows-x86_64.zip
```
2. Default policy having system integration should exist.

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Install a new agent using Default policy.
3. Wait for agent logs to come up.
4. Observe an error logs for metricbeat are generated in Agent Tab.

Logs on Ui:
```
19:11:03.357
elastic_agent
[elastic_agent][error] Elastic Agent status changed to: 'error'
19:11:03.357
elastic_agent
[elastic_agent][error] 2021-03-03T08:41:02-05:00: type: 'ERROR': sub_type: 'FAILED' message: Application: metricbeat--7.12.0--36643631373035623733363936343635[bda121a0-7c25-11eb-8585-5b9f507c66c5]: State changed to CRASHED: exited with code: 1
```

Actual Result:
Metricbeat service is not started by itself and unable to unzip completely at Endpoint under Elastic folder.

**Screenshots:** 
![image](https://user-images.githubusercontent.com/72375798/109815723-f6d2b300-7c55-11eb-9481-e6d9e625ec50.png)

Expected result:
All binaries like Filebeat nad metricbeat should be in running state.

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource  please review

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by EricDavisX** [comment]
this is a duplicate to https://github.com/elastic/beats/issues/24180 - we need to trace if that fix made it into the BC3, looks it it did not - or the changes caused a breakage with the exact same symptoms.

**Comment by EricDavisX** [comment]
update;  this seems not exactly a duplicate, i was wrong I think.  the error is slightly different, tho it is the same use case and failing in the same area.  @michalpristas will look to investigate.
