### ISSUE TITLE
filebeat kafka input lockfree 

### ISSUE THREAD

**Issue by joshua0x** [elastic/beats#24311]
Setup wont have concurrent issues , whe need a lock ? 

<img width="724" alt="图片" src="https://user-images.githubusercontent.com/44366103/109784934-8a03ec80-7c46-11eb-8616-248a07234705.png">

MarkOffser is safety called concurrent ,

<img width="754" alt="图片" src="https://user-images.githubusercontent.com/44366103/109785071-b4ee4080-7c46-11eb-83e1-dd9efd941d28.png">

**Comment by andresrc** [comment]
Hi, have you found any issue at runtime?

**Comment by joshua0x** [comment]
> Hi, have you found any issue at runtime?

no issues ,but the lock is unnecessary ,

**Comment by faec** [comment]
This doesn't seem to cause any problems, closing
