### ISSUE TITLE
[metricbeat] redis module does not support tls settings for connection

### ISSUE THREAD

**Issue by leehinman** [elastic/beats#24333]
https://github.com/elastic/beats/blob/024dd5c98021368bda3c7b8b0a91f69c9b14d5aa/metricbeat/module/redis/redis.go#L197

No TLS settings are passed to the Dial settings.

**Comment by jsoriano** [comment]
Related to #16522.

**Comment by ewingmatthewPFG** [comment]
Related to this piece of code - Redis 6 supports ACLs where a username and password are used to authenticate; however, this currently only supports a password. We wish the Redis module would support this in addition to TLS.

**Comment by svenbroeker** [comment]
Are there any news for this, we're waiting for the tls integration to get metrics from redis.
