### ISSUE TITLE
x-pack/metricbeat: panic: Not enough storage is available to process this command.

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#24337]
It seems that Windows 7 32bit builders for Beats started to complain again:

```
[2021-03-04T08:20:05.366Z] # github.com/elastic/beats/v7/x-pack/metricbeat
[2021-03-04T08:20:05.366Z] panic: Not enough storage is available to process this command.
```

As a temporary workaround we (@andres, @kuisathaverat and @mtojek) decided to switch of the Windows 7 32bit builder from the process.

I will prepare a relevant PR.

**Comment by v1v** [comment]
Duplicates https://github.com/elastic/beats/issues/24082

**Comment by andresrc** [comment]
Closed as duplicate of https://github.com/elastic/beats/issues/24082
