### ISSUE TITLE
Rpm agent unable to upgrade using upgrade command. <7.10.2 to 7.12>

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#24344]
**Kibana version:**
7.12 BC3 Kibana Cloud environment 

**Host OS and Browser version:**
Linux 7.6, All

**Preconditions**
1.  7.12 BC3 Kibana Cloud environment should be available.
```
Build: 39134
Commit: 08417cbd6c15e4c866651a7dcdfeded58845206d
Artifact link 1:  curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.10.2-x86_64.rpm
Artifact link2:  https://staging.elastic.co/7.12.0-96914cb5/downloads/elasticsearch/elasticsearch-7.12.0-x86_64.rpm

```
2. Default policy having system integration should exist.
3. 7.10.2 rpm agent installed.

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Observe 7.10.2 agent is in healthy state and successfully.
3. SSH to endpoint.
4. Download and extract artifacts for 7.12 rpm agent.
5. run command 'sudo elastic-agent upgrade elasticsearch-7.12.0-x86_64'

**Error Logs generated:**
```
The upgrade process of Elastic Agent is currently EXPERIMENTAL and should not be used in production
Failed trigger upgrade of daemon: cannot be upgraded; perform upgrading using Fleet
```

**Actual Result:**
Rpm agent unable to upgrade using upgrade command.

**Screenshots:** 
![image](https://user-images.githubusercontent.com/72375798/109957201-a1a4a900-7d0a-11eb-890b-f54922f02ab2.png)

**Expected result:**
Rpm agent should be able to upgrade successfully.

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource hello.  this feature of 'Agent upgrade' is not supported at all for either RPM or DEB installed Agents.  Please update the test content that relates if needed.   Also, would you please check if our on-line Documentation mentions this anywhere and if not, we can log a bug to make a small edit to that effect.  Then you can close the issue out.

Thanks so much for the thorough testing!

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

Thanks for the feedback.

We have performed above scenario in exploratory and couldn't find much test content related to RPM and deb agent upgrades in our test suite. And hence closing this out.

Thanks
QAS
