### ISSUE TITLE
Ingest pipeline to help with sparse data from Kafka.broker metricset

### ISSUE THREAD

**Issue by jamiesmith** [elastic/beats#24355]
**Describe the enhancement:**

I started using the broker metricset in Kafka and noticed that the data is very sparse:
![discover-kafka-broker-metrics](https://user-images.githubusercontent.com/220994/109986221-8bc7c180-7cd3-11eb-9cec-3e9565c6b33e.png)

There's one field, `kafka.broker.mbean`, which muxes together multiple other fields:
```
kafka.server:name=BytesOutPerSec,topic=_confluent-controlcenter-6-1-0-1-TriggerEventsStore-changelog,type=BrokerTopicMetrics
```

This contains the metric name (`BytesOutPerSec`), the Kafka topic that it refers to (`_confluent-controlcenter-6-1-0-1-TriggerEventsStore-changelog`), and the metric type (`BrokerTopicMetrics`). Depending on the metric type and name, different fields will be set. In this example, only the `kafka.broker.topic.net.out.bytes_per_sec` is populated (it's 0). 

This could _really_ benefit from an ingest pipeline (using better field names than I did):
```
PUT _ingest/pipeline/kafka-broker-fields
{
  "processors": [
    {
      "grok": {
        "if": "ctx.kafka?.broker?.mbean != null",  
        "field": "kafka.broker.mbean",
        "patterns": ["kafka.server:name=%GREEDYDATA:kafka_broker_metric},topic=%GREEDYDATA:kafka_broker_topic},type=%GREEDYDATA:kafka_broker_type}"
        ]
      }
    }
  ]
}
```

This now enables me to select specific metrics and break down by topic:
![metrics-explorer-for-broker-metrics-per-topic](https://user-images.githubusercontent.com/220994/109986930-30e29a00-7cd4-11eb-8e88-29756bf549a7.png)

Note that any other Jolokia-gathered metricsets can likely benefit from similar ingest pipelines (I didn't try the producer or consumer metricsets)

**Comment by jsoriano** [comment]
Thanks for opening this issue!

I don't think we can do it with an ingest pipeline at the moment, Metricbeat doesn't support modules with pipelines. But we can do it at the module level, we have already an open issue about this: https://github.com/elastic/beats/issues/13604

For this specific use case of leveraging mbeans to collect Kafka metadata we also have this open issue: https://github.com/elastic/beats/issues/22734

**Comment by jsoriano** [comment]
Also reported here: https://github.com/elastic/beats/issues/22738.

Closing as duplicated of the others.
