### ISSUE TITLE
[Discuss] Cloud.id and Cloud.auth for Elastic Agent.

### ISSUE THREAD

**Issue by ph** [elastic/beats#24351]
Beats support `cloud.id` and `cloud.auth` as a way to simplify the Kibana setup and the communication to Elasticsearch, theses option are defined at the top level section of the beats conffiguration. Today the Elasticsearch agent doesn't copy theses option to the running beats or even endpoint. 

We are having a bigger discussion on the future of the cloud's id, that will affect Elastic Agent or beats.

**Comment by ph** [comment]
@ruflin @mostlyjason @urso My opinion is we don't need `cloud.id` and `cloud.auth` for the Elastic Agent because api key is the way to go and we recommend an api key per Elastic Agent,  is that correct?

**Comment by ruflin** [comment]
We don't need Cloud id in the managed use case. But what about standalone? Having an API per Elastic Agent is the recommended way but I'm not sure this is realistic in standalone mode. I guess many users will just reused the same username / password or API Key. What we should push for, is that the reused username / password is moved to an API Key that is used instead which is already a step forward. 

If we go the API Key route, how do we make it easy for the user to retrieve one in the UI? What permission does this API key have? All or specific to the policy it is created for?

Going back to the Cloud id: For standalone to work, ES endpoint + API key is needed. The first one is in the Cloud id but not sure if there is much benefit using it for this.

**Comment by ph** [comment]
Going to close this one, there is an higher discussion that need to happen concerning cloud.id.
