### ISSUE TITLE
[Heartbeat] clarify “context deadline exceeds” further 

### ISSUE THREAD

**Issue by lowryxiao** [elastic/beats#24371]
It is said that Heartbeat employs Golang builtin context to manage the session to do the http check, will get “context deadline exceeds” error message in case timeout happens while accessing a target.
However, there’re 2 different kinds cases promise to cause timeout:
The target host is unpingable, for example:
```
ping -q -c 1 <faked host>
PING <faked host> (<faked host>) 56(84) bytes of data.
--- <faked host> ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
$ time telnet <faked host>
Trying <faked host>...
telnet: Unable to connect to remote host: Connection timed out
real	2m9.623s
```
The port that the specific service is listening on is very slow
Wondering if there’s a way to distinguish these 2 kinds of cases?

**Comment by lowryxiao** [comment]
Any comments?

**Comment by andrewvc** [comment]
Apologies for the delay. I'm not sure this is an existing problem, are you not getting distinct error messages?

There should be different error messages for connection refused vs. connection timed out already, though I can't recall the exact text. 

To be clear, a ping's success won't inform HTTP behavior, ICMP != HTTP/TCP
