### ISSUE TITLE
[Agent] Windows Agent continues to display in 'updating' state when used only unenroll option[without force un-enroll].

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#24390]
**Kibana version:**
7.12 BC3 Kibana Cloud environment 

**Host OS and Browser version:**
Windows, All

**Preconditions**
1.  7.12 BC3 Kibana Cloud environment should be available.
```
Build: 39134
Commit: 08417cbd6c15e4c866651a7dcdfeded58845206d
Artifact link : https://staging.elastic.co/7.12.0-96914cb5/summary-7.12.0.html
```
2. Default policy having system integration should exist.
3. few Windows agents should be installed.

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to fleet> Agents tab.
3. Select and Agent and Go to Actions.
4. Select unenroll Agent option.
5. Observe, agent continues to display in 'updating' state.

Actual Result:
- Agent continues to display in 'updating' state.

What's working: Agent gets unenrolled when used Force unenroll option.

**Screenshots:** 
![image](https://user-images.githubusercontent.com/72375798/110111715-c403f880-7dd6-11eb-8385-eec95608e8db.png)

**Comment by EricDavisX** [comment]
@michalpristas @blakerouse @ph I'd like us to research this for 7.12 and know what is going on before deciding if we do or not not need to fix it there - I'm leaning towards fixing it as a regression, but depending on the fix complexity we may want to hold off

**Comment by nchaulet** [comment]
I do not know if it can help here but just tested locally an `unenroll` and the agent stayed in Updating for a long time but after ~1 minutes it was succesfully unenrolled. So maybe there is no bug here.

**Comment by EricDavisX** [comment]
Thanks Nicolas - it is aways helpful to have more test data.  

It will help to have the Agent logs posted here @dikshachauhan-qasource when you get back in office, thanks!
It is failing from this test case: 
https://elastic.testrail.io/index.php?/runs/view/1355&group_by=cases:section_id&group_order=asc&group_id=529
though, I expect there is no more detail captured in testrail that is not in git.

**Comment by ph** [comment]
@EricDavisX I've assigned blake to this issue, but looking at @nchaulet's comment can we confirm this is actually the case?
@nchaulet the ~1 wait time is this due to an internal timer?

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have performed this scenario again on 7.12 BC3 build and was not able to reproduce today. However, Agent logs as requested are:
[8marAgentlogs.txt](https://github.com/elastic/beats/files/6101713/8marAgentlogs.txt)

We can close this issue after your confirmation.

Thanks 
QAS

**Comment by EricDavisX** [comment]
Can we re-test on BC4 and on other Windows hosts please to feel better that this was not a consistently enough bug we'll see?  @amolnater-qasource @dikshachauhan-qasource thank you

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

Thank you for the feedback.

And we have revalidated above on 7.11bc4 environment and found it not reproducible.

Build details are as follows:
```
BUILD 39242
COMMIT 99ac38d70e426f589bb61a034c96e602d759cfab
Artifact link: https://staging.elastic.co/7.12.0-336ff10d/downloads/beats/elastic-agent/elastic-agent-7.12.0-windows-x86_64.zip
```

Hence closing this out.

Thanks
QAS
