### ISSUE TITLE
[Elastic Agent] Logs, metrics and status info for Fleet server

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#24415]
Fleet server run by Elastic Agent should expose metrics, logs and status info. These should be collected in ES and visible in Fleet and dashboards.

As a Fleet operator, I need:
- [ ] Error logs to troubleshoot when Fleet server is not configured correctly or is not able to access Elasticsearch due to connectivity or authorization problems. https://github.com/elastic/beats/issues/23753 @mostlyjason looking into this.
- [ ] An Unhealthy status on Fleet when there are critical errors preventing the Fleet server from running.
- [x] Metrics to know when to scale my Elastic Agent slider by adding additional memory or nodes. This can be determined by system resource usage like CPU and memory, both by the Elastic Agent overall and by the Fleet server process specifically. This will allow me to determine if the resource usage is high, and determine if the cause of the increase in resource usage is due to Fleet server. These metrics should be reported per host, so I can select all Fleet servers or filter the metrics by a single Fleet server. **Elastic Agent should collect this metric**
- [ ] Metrics on the number of connected agents across Fleet servers and how it varies over time, because this may explain uneven resource usage. *Verify we can calculate the number of active connection*
- [x] Logs to troubleshoot problems visible on the agent details page. We should match the same default log level as Filebeat. 

Stretch:
- [ ] Metrics that are accurate when running inside a container, such as with cgroups.
- [ ] Metrics on the number of rejected requests over time so I can determine whether I need to scale and the impact its having on clients. 
- [ ] Access logs for non-2xx HTTP response codes with client IPs so I can troubleshoot client and server errors.

Related issues:
- Metrics already added https://github.com/elastic/fleet-server/issues/99 https://github.com/elastic/fleet-server/pull/113
  - tcp_open - tcp_close == total currently connected
- No ES output validation can lead to stopped sub processes and no logs https://github.com/elastic/beats/issues/23844

**Comment by mostlyjason** [comment]
@ph @mukeshelastic @ravi-elastic I updated the description above with more definition for use cases to cover with our Fleet server logs and metrics. Please let me know if you would change or add anything.

**Comment by mostlyjason** [comment]
Assigning to @ph to evaluate and assign to the dev team

**Comment by mostlyjason** [comment]
@scunningham I want to create a visualization of the number of connected agents to each Fleet Server over time. To do that, I'd need an aggregation across (tcp_open - tcp_close). I think scripted fields can do this, but we don't have any way to ship a scripted field in a package AFAIK. Do you think we could calculate that in the Fleet Server and report the current open connections as as metric?

**Comment by ruflin** [comment]
@ph @jasonrhodes What is the status here. The initial issue got expanded with additional metrics but I don't think all of it will land in 7.13. Can we close this or is there more needed?

**Comment by scunningham** [comment]
@ruflin This was added with this PR: https://github.com/elastic/fleet-server/pull/219

To count the number of current long poll connections use, http_server.routes.checkin.active

**Comment by ruflin** [comment]
Going to close this. @jasonrhodes please follow up with an additional issue if we need more later on.

**Comment by dikshachauhan-qasource** [comment]
Hi Rufflin,

Could you please confirm the test scenarios required to validate any data around piont 3 and 4 in ticket summary.

Currently, we just validate data for hosts is displayed on dashboards for system resource usage like CPU and memory.

Thanks

**Comment by ruflin** [comment]
@ph Can you follow up here?

**Comment by ph** [comment]
@dikshachauhan-qasource

Fleet server log should be present in the log section of the elastic agent, fleet-server metrics are not currently collected and exposed to the users.

**Comment by dikshachauhan-qasource** [comment]
Hi @ph 

Thanks for the feedback. We will update testcase accordingly.

**Comment by jasonrhodes** [comment]
@ruflin I was pinged twice on this issue -- did you intend to ping me or @mostlyjason ? E_TOO_MANY_JSON

**Comment by ruflin** [comment]
@jasonrhodes jep, sorry.

**Comment by dikshachauhan-qasource** [comment]
Hi Eric

We have updated below two testcases for point 3 and 4 in ticket summary.

Testcases link is as folows:
- [C77042](https://elastic.testrail.io/index.php?/cases/view/77042)
- [C77043](https://elastic.testrail.io/index.php?/cases/view/77043)

Thanks
QAS
