### ISSUE TITLE
[Fleet] Support fleet server in the agent policy

### ISSUE THREAD

**Issue by nchaulet** [elastic/beats#24448]
## Description 

We need to allow the fleet server url to be configured in the agent policy, the same way the kibana url was configured before.

I suggest we use the following format in the agent policy similar to kibana and ES
```yaml
fleet:
    hosts: ["https://fleet-server1.com", ""https://fleet-server2.com"]
```

Note we are currently able to test the Fleet server with agent by using the Kibana url but's it's kind of hacky

**Comment by hbharding** [comment]
Just to clarify, is this something we'll need designs for in the UI, or API only?

**Comment by nchaulet** [comment]
For the UI it will be the part in the settings where the user configure the fleet server url

**Comment by ph** [comment]
@nchaulet I've adjusted the label, this is agent work and not fleet UI work.

**Comment by blakerouse** [comment]
```
fleet:
  server:
     ...keys...
```

Is reserved for the Elastic Agent running the Fleet Server locally. I think we should make the keys top-level in the fleet block:

```
fleet:
   ...keys...
```

**Comment by nchaulet** [comment]
So this will be better?

```
fleet:
    hosts: ["https://fleet-server1.com", ""https://fleet-server2.com"]
```

**Comment by blakerouse** [comment]
Yes

**Comment by nchaulet** [comment]
Also as part of this is issue we should probably support `--fleet-server-url` during the enrollment

**Comment by blakerouse** [comment]
@nchaulet Elastic Agent already supports that, its just `--url {url}`.

**Comment by ruflin** [comment]
@ph Is this issue still open or can it be closed?

**Comment by blakerouse** [comment]
This can be closed, it is solved.
