### ISSUE TITLE
Add more resources in kubernetes composable provider

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#24496]
At https://github.com/elastic/beats/pull/21480 the base of the kubernetes provider was implemented.

We need to also add support for other resources like `node` and `service`.

Related to https://github.com/elastic/beats/issues/24495#issuecomment-796594505

cc: @exekias @masci

**Comment by exekias** [comment]
I remember @blakerouse added priority support with this in mind: https://github.com/elastic/beats/pull/22352
