### ISSUE TITLE
Add complete k8s metadata through composable provider

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#24495]
At https://github.com/elastic/beats/pull/21480 the base of the kubernetes provider was implemented.

We need to ensure that we add the proper amount of metadata via the provider. For instance at https://github.com/elastic/beats/blob/d6310ab189752b47280bacc97768d96098bc2515/x-pack/elastic-agent/pkg/composable/providers/kubernetes/kubernetes.go#L144 we add the following:

`kubernetes.namespace`
`kubernetes.pod.name`
`kubernetes.pod.uuid`
`kubernetes.pod.ip`
`kubernetes.pod.labels`
`kubernetes.container.name`
`kubernetes.container.runtime`
`kubernetes.container.id`
`kubernetes.container.image`

We need more metadata like:
- [ ] annotations
- [ ] nodeName
- [ ] deployment
- [ ] replicaset
- [ ] container port

cc: @exekias @masci

**Comment by wzt-tao** [comment]
I want to do this too, how can I solve it!

**Comment by ChrsMark** [comment]
@wzt-tao this is something that is not yet supported and the purpose of this issue it to track down the work for it. We plan to start working on this really soon.
