### ISSUE TITLE
Atom IDE crashed when I try to open beats repository 

### ISSUE THREAD

**Issue by raghzz** [elastic/beats#2452]
Atom IDE v1.10.0 crashes everytime I try to open https://github.com/elastic/beats. Other repositories seems to open without any issues.

**Comment by ruflin** [comment]
I frequently work with Atom (just updated to v1.10.0 to test) on the beats repo on different branches and never had an issue. I assume this is related to some plugins in Atom and not Atom or beats itself. 

I'm closing this issue as we like to keep the Github issues for confirmed bugs. Can you open a discuss topic here? https://discuss.elastic.co/c/beats Please provide more details about your Atom setup for example OS and the errors you see in the log. Perhaps someone else has similar issues and knows how to solve it.
