### ISSUE TITLE
Add `unsigned_long` as supported type

### ISSUE THREAD

**Issue by stuartnelson3** [elastic/beats#24545]
**Describe the enhancement:**
Currently, libbeat doesn't support the use of `unsigned_long` types:

https://github.com/elastic/beats/blob/master/libbeat/mapping/field.go#L125-L149

It is, however, a supported numeric field type: https://www.elastic.co/guide/en/elasticsearch/reference/7.11/number.html

**Describe a specific use case for the enhancement or feature:**
We're adding field definitions in `apm-server` for cgroups, and their types are `uint64`.
https://github.com/elastic/apm/issues/368

**Comment by calebpower** [comment]
Would also like to see this. Current docs contradict by stating "The value of type can be any datatype available in Elasticsearch" but subsequent execution of `make update` yields "unexpected type 'unsigned_long' for field 'foo'..."
