### ISSUE TITLE
[DOCS] Metricbeat Elasticsearch module - Warn we should point to the current master elected when testing

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/beats#24541]
**Describe the enhancement:**

Document the fact:
- All the nodes must be specified in the list of hosts
- Explain that when testing it, we should point to the current master elected node of the cluster or the cluster will not show up in the stack monitoring.

At least at the page:
- https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-elasticsearch.html

**Describe a specific use case for the enhancement or feature:**

When testing Metricbeat Elasticsearch module against a cluster, it happens quite often to configure it to collect the information just from one of the nodes, prior to configuring it with all the hosts of the cluster.

If the configured Elasticsearch node is not the master elected node, the cluster will not show up in the stack monitoring page.

---

Please backport it to previous versions.

UPDATE: I've discovered we had already https://github.com/elastic/elasticsearch/issues/40026 to cover the Elasticsearch docs.

**Comment by lucabelluccini** [comment]
Bump

**Comment by laraMorenoIgle** [comment]
@lucabelluccini 
If I understood it correctly, in case you are using `scope: cluster` in metricbeat you should point the `hosts` to a load balancer that sends the requests to the non master eligable nodes.
So, not sure when this issue you opened here applies, please, could you clarify?
Thanks!

**Comment by lucabelluccini** [comment]
Hey @laraMorenoIgle , at the time I wrote this issue, `scope` didn't exist.

To recap:
- `scope: cluster` means the `hosts` parameter will be handled as pointer to a cluster. So it's up to the final user to put in place a load balancer to hit different nodes of the same cluster
- `scope: node` means the `hosts` parameter will be handled as pointer to nodes of the same cluster. This setup requires the master to be in the list of nodes (or at least, it was)

I'll leave this issue to @elastic/stack-monitoring to clarify if the behavior changed

**Comment by klacabane** [comment]
While obscure the behavior is well described in the [metricbeat documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-metricbeat.html) so I'm inclined to keep the status quo here. Note that when not configured to poll a master node the potential misconfiguration will be logged

**Comment by lucabelluccini** [comment]
The module evolved since the issue was created, I think we're good to close this - especially if we warn users to point to a master eligible node when applicable.
