### ISSUE TITLE
Can't install packetbeat 5.0.0-alpha5 from apt repositories

### ISSUE THREAD

**Issue by t-umeno** [elastic/beats#2454]
I saw this URL:

Beats Platform Reference [5.0] 
Getting Started with Beats and the Elastic Stack 
Repositories for APT and YUM
https://www.elastic.co/guide/en/beats/libbeat/5.0/setup-repositories.html

By this method, packetbeat 1.3 is installed, not 5.0.0-alpha5
I think  "deb https://packages.elastic.co/beats/apt stable main" is for stable repositories, not for 5.0.0-alpha repositories.

- Version: 5.0.0-alpha5
- Operating System: Ubuntu 16.04.1
- Steps to Reproduce: 

``
  echo "deb https://packages.elastic.co/beats/apt stable main" |  sudo tee -a /etc/apt/sources.list.d/beats.list
``
``
  sudo apt-get update
``
``
  sudo apt-get install packetbeat
``

**Comment by tsg** [comment]
That's true, we don't offer yum/apt repositories for the alphas. We'll have them starting with the beta, which we expect quite soon. In the meantime, please download the debs and install them manually.

**Comment by t-umeno** [comment]
If you think so, please remove "We have repositories available for APT and YUM-based distributions. " at this time.

**Comment by t-umeno** [comment]
Thank you.
