### ISSUE TITLE
[Agent] When a macOS host did an OS update and rebooted, Agent did not come back on-line

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#24544]
7.12 BC4 Cloud based Kibana / stack and Elastic Agent deployed to the Endgame VPN on a mac host 
 - we can work to see if we can reproduce the OS upgrade from a specific host, and see about alternate ways to reproduce (like if just rebooting a host could work?)
 
 Charlie had seen this and can confirm version of mac host.  

to reproduce (afaik):
install Agent + set it with a policy that includes Endpoint (this may be relevant)
wait for OS to do automatic update
upon re-start of OS, confirm if Agent + Endpoint + Beats are all sending data still

**Comment by charlie-pichette** [comment]
I am closing this as a non-issue.  The VM did not restart due to an issue with macOS and vSphere.  The agent could not get back online because the host operating system failed to start.  The OS failure is a known issue with macOS and vSphere.

**Comment by EricDavisX** [comment]
oh! I mis-understood the slack note - thanks so much for closing it out. cheers
