### ISSUE TITLE
Unable to export logs from AKS cluster to kibana for specific pods

### ISSUE THREAD

**Issue by sanjeevsharma-1** [elastic/beats#24540]
We are using filebeat.yaml configuration(which is similar to https://github.com/elastic/beats/blob/master/deploy/kubernetes/filebeat/filebeat-daemonset.yaml) to migrate or export all the logs from AKS cluster to Kibana and till date everything works fine for React, Node, Python and .NET Core applications.

We have recently started using Lenses SQL processor, which in turn creates a pod in our AKS cluster, which is producing the logs in AKS cluster and we are able to see it there but this logs are not getting exported to Kibana.

Is there any configuration which enables/disables few kind of pod logs to be not exported into kibana?

**Comment by ycombinator** [comment]
Hi @sanjeevsharma-1, we use GitHub issues for confirmed bugs and enhancements. For questions such as this one, please post them on our discussion forums at https://discuss.elastic.co/.
