### ISSUE TITLE
logging.files.permissions setting is not taken into account

### ISSUE THREAD

**Issue by AndyHunt66** [elastic/beats#24555]
In some cases, I want to have the Filebeat logs readable by any user on the system.
The `logging.files.permission` setting should let me adjust the log files permissions as necessary, but any change to the `Other` part of the permissions mask is ignored. `Owner` settings are fine, `Group` settings are limited to read and execute.

- Version: 7.11.2
- Operating System: Ubuntu
- Steps to Reproduce: 
Using the following as `test.yml`:
```
logging.files:
  permissions: 0644

filebeat.inputs:
- type: stdin

output:
  console:
    pretty: true
```
run the following:
```
$ umask 
0002
$
$ ls -las logs
ls: cannot access 'logs': No such file or directory
$
$ ./filebeat -c test.yml 
^C
$
$ ls -las logs
total 16
4 drwxr-x--- 2 elastic elastic 4096 Mar 16 09:13 .
4 drwxrwxr-x 7 elastic elastic 4096 Mar 16 09:13 ..
8 -rw-r----- 1 elastic elastic 7226 Mar 16 09:13 filebeat
$
```
The same thing happens if we change the umask for the user running the elastic process to `0000`:
```
$ umask 0000
$ umask
0000
$
$ ./filebeat -c test.yml 
^C
$
$ ls -las logs
total 24
4 drwxr-x--- 2 elastic elastic 4096 Mar 16 09:13 .
4 drwxrwxr-x 7 elastic elastic 4096 Mar 16 09:13 ..
8 -rw-r----- 1 elastic elastic 7226 Mar 16 09:13 filebeat
8 -rw-r----- 1 elastic elastic 7226 Mar 16 09:13 filebeat.1
$
```

Expected behaviour:
- the `permissions: 0644` should mean that Filebeat log is be set to `-rw-r--r--` 

Observed behaviour:
- the Filebeat log is set to `-rw-r-----`

In [PR 14119](https://github.com/elastic/beats/pull/14119) **all** files created by Filebeat are restricted to a umask of `0027`

**Comment by andresrc** [comment]
@ycombinator the `libbeat/cmd/instance.Settings.Umask` setting in #14119 can be set in the configuration file or only in code?

**Comment by ycombinator** [comment]
@andresrc It is hardcoded. But we want to make it so it can be overridden. That was the use case that led to this issue.

**Comment by jakommo** [comment]
Ran into this as well today. 

As a workaround on systems with systemd/journald users can use `journalctl -u filebeat` to read the logs.

**Comment by prandelicious** [comment]
Is there a way to override the default umask setting?
