### ISSUE TITLE
Filebeat: coredns ingest pipeline not compatible when running on Docker

### ISSUE THREAD

**Issue by toby-sutor** [elastic/beats#24561]
We have [multiple reports](https://discuss.elastic.co/t/filebeat-autodiscovery-for-coredns-in-docker-what-labels-to-use/201530) that the [default ingest pipelines](https://github.com/elastic/beats/tree/ef6274d0d1e36308a333cbed69846a1bd63528ae/x-pack/filebeat/module/coredns/log/ingest) shipped with the [cordns module](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-coredns.html) are not working when coredns runs in a Docker container, because there is apparently no timestamp being provided in the coredns logs.

There are two workarounds:

1. update the ingest pipelines in the docker container and create a custom docker image, which is undesired as it adds additional complexity to maintain
2. update the ingest pipelines directly on Elasticsearch, which needs to be done every time Filebeat is being updated and as such is also coupled to unnecessary overhead

I think the best solution would be to adjust the pipelines so that the `%{timestamp}` in the grok patterns is optional.

**Comment by cdalvaro** [comment]
This issue stills happen
