### ISSUE TITLE
[Agent] Win 10 host stopped sending logs after a few days, need to triage more

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#24602]
Using a cloud stack of 7.12 bc4 and a 7.12 bc4 Agent the Engg Productivity team stood up a server to test, and found that after a few days a Win 10 Agent stopped showing logs in the Fleet UI.
 - we first need to assess if there are more severe impact going on.. like if it stopped sending data overall, too

It is set up with debug logging, and has Endpoint integration included.

I'll post details via slack for us to connect.  the host is qa-kb-7.12-bc3-windows10-x64-01 and it is behind the Endgame VPN

don’t see any other errors except one from Endpoint that may be a symptom (if nothing else):
[elastic_agent.endpoint_security][error] Http.cpp:131 HTTP code 404: Not Found
it posted that repeatedly for about 5 mins and then everything stopped one minute later after the last error at 17:41:57.147  

maybe Endpoint related maybe not.  we should check vSphere to confirm the host is ok there too.

**Comment by EricDavisX** [comment]
@michalpristas offered to take a look, see if anything jumps out as to what happened / is happening

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX ,

Today, while performing testing on 7.13 Cloud-qa build we observed that, now only win10 Os agent is sending logs and found that all other agents are not. 

Build details:
```
BUILD 40647
COMMIT ac09c73a4a7998c770b50d39177c22036ae14375
Artifact link: https://staging.elastic.co/7.13.0-100107e6/summary-7.13.0.html
```

Screenshots for references:
- created policies having endpoint and system integration.
![image](https://user-images.githubusercontent.com/72375798/116849822-11e98100-ac0d-11eb-9ad6-362b4b924fe2.png)

- updated port value in fleet settings.
- copied command from add agent flyout.
- install agent on linux and mac, win 7
![image](https://user-images.githubusercontent.com/72375798/116849848-1e6dd980-ac0d-11eb-8111-706722548000.png)

- However, no logs and data streams were available for above mentioned OSs except for agent on windows 10.
![image](https://user-images.githubusercontent.com/72375798/116849979-6987ec80-ac0d-11eb-8a29-2e7e8e486489.png)

- Agents with endpoint security are not visible on admin tab.
 
Please let us know if anything requires.

Agent logs: 
[elastic-agent-logs.zip](https://github.com/elastic/beats/files/6414281/elastic-agent-logs.zip)


Thanks
QAS

**Comment by EricDavisX** [comment]
I feel like this will have been another instance of the timing off-line/on-line issue which we think is closed.  I saw Charlie had set up the server with all of the OS hosts deployed, we can use that for validation and close this out.  If anything rears up, we'll need detailed logs so it doesn't help much to have this stay open.
