### ISSUE TITLE
Connect to Okta module of Filebeat via proxy

### ISSUE THREAD

**Issue by adityasrivastava2790** [elastic/beats#24615]
As I want to fetch logs from Okta, I am using filebeat 7.11 to do it. In the modules.d directory of filebeat, I can see configurations for Okta available.

I have entered the URL & credentials mentioned there. But now the problem is the URL is accessible via a proxy from my environment.
Where do I configure the proxy setting like
Proxy URL, Proxy Port, Proxy username, Proxy password, etc

Now had I used logstash http_poller input to connect to Okta API, below would have been my configuration,
```
urls => {
                        test2 => {
                                method => get
                                url => "https://okta/api/v1/logs"
                                headers => {
                                        Accept => "application/json"
                                        Authorization => "KEY*****************"
                                }
                        }
                }
                proxy => { host => "1.2.3.4" port => 4444 scheme => "http"}
                request_timeout => 60
                schedule => { cron => "0 * * * *"}
                codec => "json"
```
But I dont see any such options while configuring Okta in filebeat.

Any input how to achieve this would be really helpful.

Thanks,
@elastic-data-integration

**Comment by ycombinator** [comment]
I'm tagging both the Agent and SIEM teams as the `okta` module seems to be maintained by the SIEM team but it uses the `httpjson` Filebeat input.

**Comment by legoguy1000** [comment]
Looking at the httpjson docs, there doesn't appear to be any config for a proxy.  The only proxy configs I could find were for outputs to elasticsearch, logstash, redis

**Comment by andrewkroh** [comment]
This sounds like a feature request to add proxy support to the httpjson input. I assume based on the LS example that it's an http proxy rather than socks5 that you want to use.

You might be able to configure proxy settings globally via Go's environment variables as a workaround, but I'm not 100% sure those are taken into account. https://golang.org/pkg/net/http/#ProxyFromEnvironment

**Comment by legoguy1000** [comment]
@andrewkroh This is my first wack at Golang, https://github.com/elastic/beats/compare/master...legoguy1000:httpjson-input-proxy.  It passed the integration test but IDK if there is a better way to test the changes to the httpjson input.
