### ISSUE TITLE
7.12 Windows host fails in 'Agent upgrade' to 8.0 (unrelated to Fleet Server changes)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#24630]
When i upgraded the Windows (and Linux) host on the Demo / test server from 7.12.0-snapshot to 8.0-snapshot it failed for Windows (Linux worked).

So, I'm logging this to track that.  The Agent went to 'unhealthy'.  Regrettably I had the Agent on 'info' level logging so we may need to re-run it to get more details.

<img width="937" alt="Screen Shot 2021-03-18 at 9 23 13 AM" src="https://user-images.githubusercontent.com/12970373/111633168-969e4e00-87cb-11eb-8f80-998f23bd4aa3.png">

[7.12-to-8.0-windows-host-upgrade-bug.log](https://github.com/elastic/beats/files/6164413/7.12-to-8.0-windows-host-upgrade-bug.log)

**Comment by michalpristas** [comment]
is this WIn 10?

**Comment by EricDavisX** [comment]
Hi, this host was specifically Win 2019

**Comment by EricDavisX** [comment]
this worked in my latest test.  i don't know if we want to keep it open to confirm if it is intermittent or what?

**Comment by ph** [comment]
Lets close and reopen if we see it?

**Comment by EricDavisX** [comment]
another re-test on a new build passes - i agree, let us close it out.
