### ISSUE TITLE
[Filebeat] Fix Cisco ASA parsing issue

### ISSUE THREAD

**Issue by P1llus** [elastic/beats#24695]
Before updating the CI to look for the message `Cannot index event` in ingest pipeline pytest logs, we need to fix a certain error generated in the cisco filebeat module:

Ref the cisco test here: https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-24661/4/tests/
The error is:
`AssertionError: Error found in log:2021-03-22T09:25:23.214-0200 WARN [elasticsearch] elasticsearch/client.go:408 Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Time{wall:0xc00e3d88627562c8, ext:94919251, loc:(*time.Location)(0x60e21a0)}, Meta:{"pipeline":"filebeat-8.0.0-cisco-asa-asa-ftd-pipeline"}, Fields:{"agent":{"ephemeral_id":"eada6b6f-0c00-4834-a18e-e11cbbcb23d3","id":"d65aa6c6-dee7-4128-8710-883205eb85e3","name":"73dae6280352","type":"filebeat","version":"8.0.0"},"ecs":{"version":"1.8.0"},"event":{"dataset":"cisco.asa","module":"cisco","timezone":"-02:00"},"fileset":{"name":"asa"},"input":{"type":"log"},"log":{"file":{"path":"/go/src/github.com/elastic/beats/x-pack/filebeat/module/cisco/asa/test/additional_messages.log"},"offset":4472},"message":"May  5 19:02:58 dev01: %ASA-6-302022: Built director stub TCP connection for fw1111:10.10.10.10/38540 (8.8.8.5/38540) to net:192.168.2.2/10051 (8.8.8.8/10051)","service":{"type":"cisco"},"tags":["cisco-asa","forwarded"]}, Private:file.State{Id:"native::6711042-2049", PrevId:"", Finished:false, Fileinfo:(*os.fileStat)(0xc0008de0d0), Source:"/go/src/github.com/elastic/beats/x-pack/filebeat/module/cisco/asa/test/additional_messages.log", Offset:4631, Timestamp:time.Time{wall:0xc00e3d8862366690, ext:90791452, loc:(*time.Location)(0x60e21a0)}, TTL:-1, Type:"log", Meta:map[string]string(nil), FileStateOS:file.StateOS{Inode:0x666702, Device:0x801}, IdentifierName:"native"}, TimeSeries:false}, Flags:0x1, Cache:publisher.EventCache{m:common.MapStr(nil)}} (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse field [destination.port] of type [long] in document with id 'gfauWXgBMExUQhu1reZ9'. Preview of field's value: '10051 (8.8.8.8/10051)'","caused_by":{"type":"illegal_argument_exception","reason":"For input string: \"10051 (8.8.8.8/10051)\""}}    assert True is False`

**Comment by leehinman** [comment]
Duplicate of #24405
