### ISSUE TITLE
How to use prometheus to monitor filebeat with Kubernetes

### ISSUE THREAD

**Issue by riteshbangal** [elastic/beats#24709]
How to use prometheus to monitor filebeat with Kubernetes?

**Comment by jsoriano** [comment]
Hi @riteshbangal,

The possible answers to this question are quite broad :slightly_smiling_face: Could you please start a topic in discuss for this? https://discuss.elastic.co/
We try to keep github issues for feature requests and confirmed bugs.

Thanks!
