### ISSUE TITLE
[Filebeat] Bring syslog input to GA

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#24729]
The syslog input on Filebeat is currently experiemental and it logs the following line:
`2021-03-17T12:20:20.975+0100    WARN    [cfgwarn]    syslog/input.go:111    EXPERIMENTAL: Syslog input type is used`

However, it is not communicated as experimental in the documentation. https://www.elastic.co/guide/en/beats/filebeat/7.11/filebeat-input-syslog.html

After discussing with engineers the reason it's experimental is the lack of RFC5424 and multiline support. We could document these limitations instead of letting them block the whole module from going GA.

The request for this issue is to remove the experimental log line, add the limitations to the docs, and make the input GA.

CC @mukeshelastic @andresrc @ph

**Comment by jamiehynds** [comment]
We discussed this among the security integrations team earlier this week, and would love to move syslog to GA. 

Just an FYI, we had a community contribution for RFC5424 support recently, waiting on review. https://github.com/elastic/beats/pull/23954

**Comment by ph** [comment]
- Remove Experimental for RFC31*
- Add Beta for RFC5424
- Add Beta mention for RFC5424 in the documentation.

**Comment by urso** [comment]
The work in progress meta issue with open tasks is here: https://github.com/elastic/beats/issues/24954

Can we close one of the two?
