### ISSUE TITLE
Validate and update the Elasticsearch URL with the agent policy

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#24739]
Currently, Fleet server does not apply updates to the Elasticsearch URL when the agent policy is updated. This is inconsistent with other integrations and can result in a situation where a single agent may be using two different Elasticsearch URLs, one for Fleet server and one for the other integrations. The user may be confused why they updated the URL in FLeet settings but it is not applied. This is unexpected and a little confusing.

Also, Fleet server is not currently able to validate the Elasticsearch URL before applying it to agents. As a result, the agents will be reported as healthy even though they are not sending data.

It'd be better to use the same logic we have for updating the Fleet server URL. Fleet server should check whether the URL is valid before accepting the policy update. If it is not, it should log the error and report itself as unhealthy until a valid URL is given. It should not deliver the policy update to the agents until it is valid.

**Comment by blakerouse** [comment]
I think the idea of validating the elasticsearch URL should be on the Elastic Agent. Elastic Agent is also the one that does the validation of the Fleet Server URL.

We should ensure that the Elastic Agent can communicate with the outputs defined in a policy before the Elastic Agent even tries to apply the policy. This would provide the same user experience that we now have for the Fleet Server URL and a better overall user experience for our users.

Currently our users see Elastic Agents reported has healthy even in the case that the cannot communicate with elasticsearch. This is a bad experience and does not report the true health of the Elastic Agent. By switched to the model I described if a policy has a bad output then the Elastic Agent would fail to apply the policy and it would report back to Fleet that it is unhealthy. Only once the output configuration is fixed and the Elastic Agent can communicate would it fully apply the policy.

I think this could be a rather simple change to implement on the Elastic Agent side but would provide a large improvement to UX when it comes to having Elastic Agent installed but your are getting no data.

A simple GET request to elasticsearch using the provided credentials and SSL configuration would be enough for the Elastic Agent to confirm valid connection before sending it on.
