### ISSUE TITLE
[Heartbeat] Root fields for synthetics

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#24768]
We need to interpolate the new `root_fields` field from synthetics into the base of events per https://github.com/elastic/synthetics/pull/215

This just means looking for that field and merging it in.

**Comment by justinkambic** [comment]
When running 7.13 stack, I was able to query for the fields that are specified as root fields in the [synthetics PR](https://github.com/elastic/synthetics/pull/215) that introduced these `root_fields`.

![image](https://user-images.githubusercontent.com/18429259/117017341-84b43400-acc1-11eb-9512-b04bb4209f16.png)
