### ISSUE TITLE
Beats docs have a broken link to packetbeat on 'what are beats' overview page

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#24776]
for both 7.12 and master, this page on our main elastic site has a broken link, from Beats repo docs:
https://www.elastic.co/guide/en/beats/libbeat/current/beats-reference.html

That URL maps to this:
https://github.com/elastic/beats/blob/master/libbeat/docs/overview.asciidoc

and in this... the link for packetbeat is broken.  The file doesn't exist so it throws a 500 error.  
The link points to:
https://www.elastic.co/products/beats/packetbeat

where I believe want it to resole to:
https://www.elastic.co/downloads/beats/packetbeat

I'm sure it is a short-link or otherwise dynamically controlled so I'm not sure who owns that or where it is etc.

![Screen Shot 2021-03-25 at 8 26 56 PM](https://user-images.githubusercontent.com/12970373/112561186-11a6cc00-8dab-11eb-8c5b-8060952b8ee5.png)

**Comment by jamiehynds** [comment]
@jmikell821 is this something your team can take care of? Thanks!

**Comment by jmikell821** [comment]
@jamiehynds this isn't my team, but looping in @dedemorton, who handles beats docs.

**Comment by dedemorton** [comment]
I'm back from vacation. Will take a look today. :-)

**Comment by dedemorton** [comment]
It looks like marketing changed the base URL for Beats product pages at some point. Now there are redirects in place, but I have updated the files in the beats repo, too, because it's not a good idea to rely on redirects.
