### ISSUE TITLE
Add arm64 docker containers to docker hub for beats

### ISSUE THREAD

**Issue by mloebl** [elastic/beats#24786]
**Describe the enhancement:**
With beats now being officially supported on arm64, would it be possible to add arm64 based containers to docker hub?

**Describe a specific use case for the enhancement or feature:**
Working with k8s and arm64, and the ability to easily deploy beats containers from the official elastic docker hub would be greatly appreciated.

**Comment by ChrsMark** [comment]
Might be related to https://github.com/elastic/beats/issues/23775
