### ISSUE TITLE
Agent fails if first cert in certificate_authorities cannot be found

### ISSUE THREAD

**Issue by dwhyrock** [elastic/beats#24796]
A user posted in Discuss asking how to provide a list of certificates for Elasticsearch in the `Fleet` -> `Settings` in order to support certificate paths for multiple OSes.

The user tried adding the following config entry:

```
ssl.certificate_authorities: ["C:\\\\Program Files\\\\Elastic\\\\Agent\\\\elasticsearch-ca.pem", "/etc/pki/ca-trust/source/anchors/ca.crt"]
```

After entering this, the Agent went into an unhealthy state.

I tried a similar thing on a local Kibana/ES instance and confirmed that Agent goes into an Unhealthy state.  The Endpoint doesn't seem affected and is still able to connect to ES w/ the second certificate.

> Please include configurations and logs if available.

My `Fleet`->`Settings`:

```
ssl:
  certificate_authorities:
  - C:\\\\Program Files\\\\Elastic\\\\Agent\\\\elasticsearch-ca.pem
  - /tmp/certs/ca.crt
  verification_mode: certificate
```

Initial Agent log related to the issue:
```
2021-03-26T12:21:25.719-0400    ERROR   log/reporter.go:36      2021-03-26T12:21:25-04:00: type: 'ERROR': sub_type: 'FAILED' message: Application: metricbeat--7.11.1[102df520-8e4f-11eb-8787-d37931e386e6]: State changed to FAILED: 1 error: 1 error: open C:\\\\Program Files\\\\Elastic\\\\Agent\\\\elasticsearch-ca.pem: no such file or directory reading <nil>
```

My agent log:
[agent-log.zip](https://github.com/elastic/beats/files/6213304/agent-log.zip)

For confirmed bugs, please report:
- Version: `7.11.1`
- Operating System: Linux (Ubuntu 20.04) 
- Discuss Forum URL: https://discuss.elastic.co/t/possible-bug-with-elastic-agent-ca-certificate-checks/267253/4
- Steps to Reproduce: 
1. Install a Linux agent
2. In `Fleet` -> `Settings`, add an entry for `certificate_authorities` that has a Windows path first, and the correct Linux path to the Kibana server certificate second.
  - e.g., `ssl.certificate_authorities: ["C:\\\\Program Files\\\\Elastic\\\\Agent\\\\elasticsearch-ca.pem", "/etc/pki/ca-trust/source/anchors/ca.crt"]`
3. The Linux Agent will then go into an Unhealthy state

I provided an answer to the user to specify the cert text in the config, which should work.  However, I think users would expect the `certificate_authorities` file list would work cross-platform and ignore any files it cannot find.

**Comment by michel-laterman** [comment]
I'm able to recreate the issue on MacOS using a build from 7.14, attempting to run the agent with a windows path and unix path to the system cert file results in the agent appearing offline and the output is:
`
Agent|⇒ sudo ./elastic-agent
could not parse configuration file /Library/Elastic/Agent/elastic-agent.yml: 1 error: open C:\\\\Program Files\\\\Elastic\\\\Agent\\\\elasticsearch-ca.pem: no such file or directory reading <nil> accessing 'fleet'
`

**Comment by michel-laterman** [comment]
@michalpristas I think the issue being here is that TLS config will error out if the (client) cert or CAs produce any error:
https://github.com/elastic/beats/blob/eb758b9b11addf05816ce9f0bcdf6eab725ca2dc/libbeat/common/transport/tlscommon/config.go#L67-L76

I think that we can solve the issue by changing the behaviour after `LoadCertificateAuthorities` so that it will not error out if `cas` has at least one entry.

**Comment by michel-laterman** [comment]
@dwhyrock, the pr I have would create more failure cases than it would resolve. It would introduce a lot of new silent failure modes as the agent would not be able to detect invalid certs, need platform/path knowledge, may ignore typos.
I think our recommendation for fleet is to inline the certificates, is that an acceptable solution (here's [an example of the syntax](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html#client-certificate-authorities))

**Comment by dwhyrock** [comment]
@michel-laterman Thanks for the response.  I agree that inlining the certificates is probably the best cross-platform solution.

Would this mean disallowing/ignoring file paths in the agent?  Or enforcing the inlining of certificates in the Fleet UI (and disallowing file paths)?  Or something else?

**Comment by urso** [comment]
One can either rely on the hosts CA storage (e.g. /etc/ssl/storage on linux I think), or try to inline the certificate as @michel-laterman already mentioned.

I think the Fleet UI allows you to add custom YAML based settings to outputs. This should allow you to put the certificates inline. @mostlyjason Any idea if we have planned dedicated UI in Fleet?

> Would this mean disallowing/ignoring file paths in the agent?

I'm not sure I understand your question. The agent config syntax accepts an array of certificates. Each entry can either be a path, or an inlined certificate. But if you set a path, then the path must exist, otherwise loading the CA store will fail. In general when working with Fleet and multiple platforms, I would recommend to inline those certs, but there is no hard rule how you do it.

**Comment by mostlyjason** [comment]
We already support inline certs like this

```
ssl.certificate_authorities:
  - |
   -----BEGIN CERTIFICATE-----
   MIIDSTCCAjGgAwIBAgIUSG64XLc34rcXzT6jbmo13itoZuYwDQYJKoZIhvcNAQEL
   BQAwNDEygDAGA1UEAxMpRWxhc3RpYyBDZXJ0aWZpY2F0ZSBUb29sIEF1dG9nZW5l
   cmF0ZWQgQ0EwHhcNMjAxMjIyMTg1NTA0WhcNMjMxMjIyMTg1NTA0WjA0MTIwMAYD
   VQQDEylFbGFzdGljIENlcnRpZmljYXRlIFRvb2wgAXV0b2dlbmVyYXRlZCBDQTCC
   ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAManUXssX6WI5iObj/EfOOOt
   XJn2t7EfSVylY9v79VgtQ7iZHoLfLxPH4DqHutno0w6pqqnLD0kv9e9GFeobI3d9
   dvJtb2ChRiJsX9AyU4jrioafUhNHibvD0r8xECeWILqSG34vkjHwX4/YHrS5GG9i
   zj0ZkeLm3L7//dTLeZRQ0h0SahUo0YR58BvndTl+bedEJNuQICTA8zuYMG+ohOjv
   jltqjDx2/PqFrtsQCeY2HYZnbGza++vMcyeOUcX6I2HkJOURNuh0I+nQpZvt+nVF
   cAjeZY8kBZCIJ0iZ0SHenrSvM7G2KnnduGYqIxAHGTzWkJwM/K7sM34ltYOm0oUC
   AwEAAaNTMFEwHQYDVR0OBBYEFNAA3vwPOD00bV1MDQEnA/i3XutWMB8GA1UdIwQY
   MBaAFNAA3vwPOD00bV1MDQEnA/i3XutWMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZI
   hvcNAQELBQADggEBAKHegTIvphV+y7/XZ5dv5BEH1Nf9rSBd1qs0F2Bz8A7pnyxM
   XFQtlkx386EDGQZeYXB63mgXLoayzxSnAzqo+TFZlbxg8Lfm245H7hqjyGqVXynt
   iexAFkevXN4QcxT/G4deF2hIgTrlU/PsW6xgA0tckpLpnp+GJd5dBnhsyf1NmqDB
   CJKNrPsOM3gGPwM52720tOhwHRyTHdu5oLmWGg1xBXXNM0OB8ETr19xcLcelcOnF
   o55ozZknr0pBccEdWDbHRSaTdzJwTThFkaxSAry8KlNmjuh9qmb9+jlgVI8eiVgA
   ya/QYmC2OsPAQxZTBp10IqKiWFOz6OchQISle1k=
   -----END CERTIFICATE-----
```

**Comment by dwhyrock** [comment]
> I'm not sure I understand your question. The agent config syntax accepts an array of certificates. Each entry can either be a path, or an inlined certificate. But if you set a path, then the path must exist, otherwise loading the CA store will fail. In general when working with Fleet and multiple platforms, I would recommend to inline those certs, but there is no hard rule how you do it.

I was mainly asking about how this would be handled in Fleet.  I could see others trying to do as I did and adding a path for each OS that they support.  But my suggestion for preventing them from adding paths in Fleet seems like a poor choice as well since they could be in a homogenous OS environment where that would be a fine solution.

It sounds like the documentation will be the cleanest solution that doesn't open up the potential for several other bugs or prevent use cases that customers would want to use.

Closing this issue.
