### ISSUE TITLE
Metric for throttled input (back-pressure support request)

### ISSUE THREAD

**Issue by SelAnt** [elastic/beats#24797]
Please add a metric (primary for Filebeat) which indicates that beat input was throttled by back-pressure support? 
For example - Logstash was overloaded and asked Filebeat to reduce rate

It allows to track which parts of a system require tuning, detect possible missing logs (Filebeat lost logs because was asked to 
throttled shipping logs and logs were rolled over during this time)

For now it is hard to figure out if missing logs case was caused by Filebeat performance or by overloaded Logstash

**Comment by michel-laterman** [comment]
I think that these metrics are already gathered as part of the beat stats metricset: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-beat-stats.html

**Comment by michel-laterman** [comment]
@SelAnt, we are going to close this as beat stats contains this info. Please tag me if you have questions or need this re-opened

**Comment by SelAnt** [comment]
Hi Michael,
Great!
Could you please help to figure out which metrics contains it?
                        "acked": 0,
                        "active": 0,
                        "batches": 0,
                        "dropped": 0,
                        "duplicates": 0,
                        "failed": 0,
                        "toomany": 0,
                        "total": 0

**Comment by michel-laterman** [comment]
`toomany` indicates a 429 response from ES

**Comment by SelAnt** [comment]
Thank you Michael for your help!
