### ISSUE TITLE
MSI for elastic-agent

### ISSUE THREAD

**Issue by jguay** [elastic/beats#24825]
**Describe the enhancement:**
MSI installer for Elastic Agent (Windows installer which would install Elastic Agent as a service)

**Comment by mostlyjason** [comment]
@ygel you volunteered to help. Do you have information that would help us prioritize and scope this feature?

**Comment by ygel** [comment]
Hello @mostlyjason, we'll work on scoping and prioritization with @nkammah.

**Comment by nkammah** [comment]
@mostlyjason and I synced up offline - MSI's are not a priority at the moment for the Infra Release team and from what I understand, they're also not a priority for the agent team.

**Comment by nimarezainia** [comment]
This seems to be available for Winlogbeat already (and other beats) although in Beta. Closing this issue for now.

**Comment by maederm** [comment]
👍

**Comment by nimarezainia** [comment]
Elastic Agent MSI will be available for download in 8.13
