### ISSUE TITLE
Move Palo Alto module to GA

### ISSUE THREAD

**Issue by jamiehynds** [elastic/beats#24835]
## Modules

For a Filebeat module to go GA, the following criterias should be met:

* [x] Supported versions are documented
  * [x] Supported operating systems are documented (if applicable)
  * [x] Integration tests exist
* [x] System tests exist
* [x] Automated checks that all fields are documented
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] Dashboards exists (if applicable)
* [x] Kibana 'Add Data' Tutorial (if applicable)

## Filebeat module

* [x] Test log files exist for the grok patterns
* [x] Generated output for at least 1 log file exists

**Comment by willemdh** [comment]
@jamiehynds Something that imho should be added is giving us the choice to use tcp instead of udp to ingest panw data. We are experiencing issues with udp (up to 5 % loss during peak ingest times). Tcp seems to be more reliable.

Currently we have to edit /usr/share/filebeat/module/panw/panos/config/input.yml ourselves and change:

```
type: syslog
protocol.udp:
  host: "{{.syslog_host}}:{{.syslog_port}}"
```

to:

```
type: syslog
protocol.tcp:
  host: "{{.syslog_host}}:{{.syslog_port}}"
```

Considering the sensitivity of the panw data, it would be even better if tcp over tls would be allowed, so the data can be sent encrypted.

**Comment by jamiehynds** [comment]
Thanks @willemdh - your suggestion makes total sense. I've created an issue for it: https://github.com/elastic/beats/issues/25035

**Comment by jamiehynds** [comment]
@willemdh - PANW seem to recommend IETF format syslog when sending via TCP? Have you enabled IETF and if so, any issues?

**Comment by willemdh** [comment]
Yes, we tried IETF, but it doesnt work.

**Comment by jamiehynds** [comment]
@willemdh would you be able to provide some sample events in IETF format? RFC5424 was [recently added ](https://github.com/elastic/beats/pull/23954#pullrequestreview-595832655) to the syslog input and would like to ensure we can support IETF as part of the TCP support. Will get in touch offline regarding the scale issues you've seen with the PANW module.

**Comment by willemdh** [comment]
@jamiehynds It'll be hard to provide you with IETF logs in ahort time, as I have multiple holidays coming up and also one week SANS course.  I also need our network team for this and they are also overworked. Maybe end of May I could provide those.

**Comment by jamiehynds** [comment]
@andrewkroh all the tasks here seem to be complete. Are we ok to GA the PANW module at this point? Docs still indicating it's Beta - https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-panw.html

**Comment by willemdh** [comment]
@jamiehynds Is PANW 10.x syslog supported? Imho a requirement to get this GA.

**Comment by jamiehynds** [comment]
@willemdh 10.x is not yet supported, but we are working directly with PANW to understand the updates made in the 10.x syslog, with a view to supporting. If you have any examples of changes made to syslog in 10.x, would love to see some examples. 

Any updates, such as support for 10.x, would be an enhancement to the module, so generally not considered a blocker to GA. In this particular case, the PANW Elastic Agent integration is now GA but the Filebeat module is Beta, so aiming to address that discrepancy asap.

**Comment by willemdh** [comment]
@jamiehynds One more suggestion. Currently the `user.name` fields include the domain, making those field incorrelatable with other field. Please separate the domainfrom the user.

Currently `user.name` value is for example `"DOMAIN\username"`. This should be:

user.name => username
user.domain => DOMAIN

Thanks for considering this.

**Comment by jamiehynds** [comment]
Thanks for the suggestions @willemdh. Will create separate issues for these. Would you be able to share log samples showing the `user.name` and `observer.hostname` issues? If you could share some PANW 10.x logs too, it'd be great. I can share my contact details to send them directly if you like. Sanitised events are fine. 

The `suricata.*` fields should be resolved now, as we removed those field alias recently, see [here](https://github.com/elastic/beats/pull/26627  ). Can you confirm what version of Filebeat you are running?

**Comment by willemdh** [comment]
@jamiehynds We are on 7.14.1. Please share your contact to me @ willem.dhaese_at_district09.gent 
I'll try to give some samples, but not making any promises, as I'm a bit 'overworked'.

**Comment by jamiehynds** [comment]
@andrewkroh anything stopping up from GA'ing the PANW module? The integration is GA, so makes sense to GA the Filebeat module also if possible.

**Comment by leehinman** [comment]
https://github.com/elastic/beats/pull/30602 is merged which was last thing so closing
