### ISSUE TITLE
Unable to upgrade 7.13.0 Snapshot agent with Endpoint on 8.0 Snapshot Kibana

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#24836]
**Kibana version:** 8.0 Kibana cloud environment

**Host OS and Browser version:** Windows, All

**Build Details:**
```
   Artifact link used: https://snapshots.elastic.co/7.13.0-8cf5aa00/downloads/beats/elastic-agent/elastic-agent-7.13.0-SNAPSHOT-windows-x86_64.zip
   Build: 41600
   Commit: cf8ebe619b539399310205ffa08d0ba02efddc6f
```

**Preconditions:**
1. 8.0 Snapshot Kibana Cloud environment should be available.
2. 7.13.0 Snapshot agent must be enrolled with default policy having System and Endpoint Security integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to agents tab and click on "Actions">"Upgrade Agent".
3. Observe agent is unable to upgrade.

**Reference Ticket:**
[[BUG] Unable to upgrade Endpoint via Agent](https://github.com/elastic/beats/issues/24477)

**Expected Result:**

- 7.13.0 Snapshot agent should be upgraded to 8.0 Snapshot agent. 
- Agent upgrade failure message should be displayed when agent fails to upgrade.

**Logs:**
[elastic-agent-json.log](https://github.com/elastic/beats/files/6227916/elastic-agent-json.log)
```
{"log.level":"error","@timestamp":"2021-03-30T04:49:25.678-0400","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2021-03-30T04:49:25-04:00: type: 'ERROR': sub_type: 'FAILED' message: Application: [8d5e6a6b-a208-41b4-8242-508017ebda7a]: State changed to FAILED: failed verification of agent binary: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-34e528\\downloads\\elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-34e528\\downloads\\elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: The system cannot find the file specified.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-03-30T04:49:25.678-0400","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":179},"message":"failed to dispatch actions, error: failed verification of agent binary: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-34e528\\downloads\\elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-34e528\\downloads\\elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: The system cannot find the file specified.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-03-30T04:49:25.678-0400","log.origin":{"file.name":"status/reporter.go","file.line":233},"message":"Elastic Agent status changed to: 'error'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-03-30T04:54:08.677-0400","log.origin":{"file.name":"status/reporter.go","file.line":233},"message":"Elastic Agent status changed to: 'online'","ecs.version":"1.6.0"}
```

**Endpoint logs:**
[endpoint-000000.log](https://github.com/elastic/beats/files/6228063/endpoint-000000.log)

**Version Screenshot:**
![17](https://user-images.githubusercontent.com/77374876/112972989-79279780-916e-11eb-9203-278bec1396a4.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by EricDavisX** [comment]
I think it is already logged, @amolnater-qasource can you search for dupes?  @michalpristas may have the number handy.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have  a similar reported defect at: https://github.com/elastic/beats/issues/24477 but in that case we are able to upgrade the agent and issue is only with Endpoint errors. Further, this issue is fixed and closed.

However in the current reported issue agent upgrade fails completely and same version is observed after clicking "Upgrade Agents" option. Rest details are shared above.

Thanks
QAS

**Comment by EricDavisX** [comment]
i see the dupe and it is closed, and I tested on 8.0 on our 1-day old system deployed to the internal test/demo cluster and I don't see this problem.  But it was with a 7.12 Win/Linux Agent (which was failing prior).  We can leave this open for engineering to review.  @michalpristas can we add it to your list for earlier priority review?

**Comment by michalpristas** [comment]
tried this today from 7.13 top and it worked. issue seems like the one we have when packaging was broken or incomplete. i would say agent did the right thing and refused to upgrade with signature mismatch

**Comment by EricDavisX** [comment]
Thanks Michal.  @amolnater-qasource on the chance you are in a different configuration than us, please do re-test and close out if fixed and re-post all needed details if not.  thank you

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this issue on 8.0 Kibana cloud environment and found it **fixed**. 
We are now able to upgrade 7.13.0 Snapshot agent to 8.0 Snapshot agent from Kibana UI. Hence closing this out.

**Build details:**
```
Build: 41814
Commit: f1d662932133c49f3c2efe334b60201eeaa20a7d
```
**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/113827603-1e5ef300-97a1-11eb-8b98-052008c51bf5.JPG)

Thanks
QAS
