### ISSUE TITLE
Syntax error for journalbeat installation at setup command on user guide page.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#24846]
**Description**: Syntax error for journalbeat installation at setup command on user guide page.

**Steps to reproduce:**
1. Go to user guide link for journalbeat installation at:
 https://www.elastic.co/guide/en/beats/journalbeat/current/journalbeat-installation-configuration.html
2. Scroll down to step 4.
3. Observe forward slash is provided under linux tab for setup command.

**Expected result:**
Backward slash should be provided under linux tab for setup command.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/112990688-f4477880-9183-11eb-9a02-5a84fc11f998.png)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by jmikell821** [comment]
I don't work on Beats docs, so assigning @dedemorton.

**Comment by dedemorton** [comment]
Ouch. This error has been in the published docs for awhile. :-( Just a small fix to the widget code. The problem is fixed in https://github.com/elastic/beats/pull/24880.

**Comment by dikshachauhan-qasource** [comment]
We have validated it as per merge from #24880 and found it fixed.
