### ISSUE TITLE
S3 collector aborts when there is a blank line in the log file

### ISSUE THREAD

**Issue by sinzui** [elastic/beats#24872]
For confirmed bugs, please report:
- Version: 7.9.0
- Operating System: centos
- Steps to Reproduce: 
  - Create a log file with 10 lines in it
  - Insert a blank line anywhere in the file
  - Copy the file to s3
  - Ingest (optionally with debug enabled for s3/awss3)
  - Verify the 10 events are in elastic search
    - Elastic will only have the lines before the blank line
    - No errors were logs from filebeat
 - Moving the blank line controls the number of events created

We discovered that filebeat 7.9.0 s3 input stops collecting messages when there is a blank line in the log file. Only the messages before the blank line are collected. I see the problem in the source code, and that problem is in master in the renamed and restructured awss3 input

In `In func (p *s3Input) createEventsFromS3Info` in [7.9.0](https://github.com/elastic/beats/blob/7.9.0/x-pack/filebeat/input/s3/input.go#L492) and in [master](https://github.com/elastic/beats/blob/master/x-pack/filebeat/input/awss3/collector.go#L394) the loop calls `break` when the line in an empty string `""`. It could call `continue` to read the next line. (This fix will be required for multiline support)

**Comment by jsoriano** [comment]
@sinzui good catch! thanks for reporting.

ping @kaiyan-sheng
