### ISSUE TITLE
Selective filebeat mappings for setup

### ISSUE THREAD

**Issue by novaksam** [elastic/beats#24875]
**Describe the enhancement:** As it appears to work now, when doing a Filebeat setup, all mappings are imported, regardless of modules provided in the configuration. I'm currently having cluster state size issues, which I partially attribute to excessive mappings. For instance, if I have a custom index where I'm importing Cisco Umbrella logs, I don't need OSQuery mappings in there, so if I could specify which ECS mappings I use my templates in the filebeat config/arguments that would be ideal.

**Describe a specific use case for the enhancement or feature:**  I make use of ECS for my custom indices by way of 'filebeat setup' commands to make sure I'm using the latest mappings for consistency.

**Comment by jsoriano** [comment]
With Fleet and Agent, only resources of configured integrations are installed.

With Filebeat I am not sure if something can be done, apart of providing custom mappings, but this can be cumbersome to maintain.
