### ISSUE TITLE
Filebeat multiline concatenates all events that does not match the pattern

### ISSUE THREAD

**Issue by sesto** [elastic/beats#24888]
I have the following multiline pattern to handle Java stack traces:
```
multiline.type: pattern
multiline.pattern: '^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.\d{3}'
multiline.negate: true
multiline.match: after
```
The regex matches timestamp in the beginning of the message.
It works fine for java logs:
```
2021-04-01 08:25:38.416+0000 [id=17857421]	WARNING	j.i.j.p.e.ExtensibleChoiceParameterDefinition#getDefaultParameterValue: Illegal choice for the default value. Ignore and use the value in the top of the list instead.
java.lang.IllegalArgumentException: Illegal choice '<Top Most Value>' in parameter 'deploy'
	at jp.ikedam.jenkins.plugins.extensible_choice_parameter.ExtensibleChoiceParameterDefinition.createValueCommon(ExtensibleChoiceParameterDefinition.java:456)
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
```	
However, all non-java logs that are collected from other applications are concatenated in a multiline message split every 5 sec when timeout occurs. Start of the message in those logs is totally different and it does not match the pattern:
```
time="2021-04-01T08:40:37Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=filebeat
time="2021-04-01T08:40:37Z" level=info msg="No status changes. Skipping patch" application=filebeat
time="2021-04-01T08:40:37Z" level=info msg="Reconciliation completed" application=filebeat dest-name= dest-namespace=filebeat dest-server="https://kubernetes.default.svc" fields.level=0 time_ms=5
time="2021-04-01T08:40:37Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=filebeat
time="2021-04-01T08:40:37Z" level=info msg="No status changes. Skipping patch" application=filebeat
time="2021-04-01T08:40:37Z" level=info msg="Reconciliation completed" application=filebeat dest-name= dest-namespace=filebeat dest-server="https://kubernetes.default.svc" fields.level=0 time_ms=6
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
```
This problem can be solved by adding a regex for these logs in the multiline configuration:
```
multiline.pattern: '(^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.\d{3}|^time=)'
```
- Steps to reproduce:
1. Create a multiline config matching one of the logs:
```
multiline.type: pattern
multiline.pattern: '<pattern matching one of the logs>'
multiline.negate: true
multiline.match: after
```
2. Observe that the messages that do not match the pattern are concatenated
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-multiline-concatenates-all-events-that-does-not-match-the-pattern/267779

- Version: filebeat 7.10.2
- Deployed in GCP GKE using the helm-chart: https://github.com/elastic/helm-charts/tree/master/filebeat

**Comment by jsoriano** [comment]
Hi @sesto,

I am sorry, but I don't fully understand :thinking: Is this a bug report or an enhancement request? It seems that multiline is working as expected.

You also started a topic in discuss, was there a reason to don't continue the conversation there?

Is this a suggestion to improve the docs mentioned in discuss?

**Comment by sesto** [comment]
Hi @jsoriano, I have discussed this here https://discuss.elastic.co/t/filebeat-multiline-concatenates-all-events-that-does-not-match-the-pattern/267779. From the discussion I have understood that this was not the expected behaviour

**Comment by jsoriano** [comment]
@sesto according to your description there was a pattern that didn't handle your logs as expected, but you found another one that solved your issues.
This didn't require any fix or enhancement in Filebeat, Filebeat seems to be working correctly for these given patterns, so it is not clear to me what should be improved or fixed.

What change would you expect from this bug report?

@ChrsMark you commented in the discuss issue, do you see something that is not working as it should with the given patterns?

**Comment by sesto** [comment]
@jsoriano I will try to explain better what I mean. Suppose we have 20 applications having totally different patterns and suppose that only 5 of those have multiline log events. In the current situation, I will need to design a regex matching all 20 patterns, instead of only 5. If I design the regex for those 5 only, in the rest 15 all log events will be concatenated. It looks like the current logic is: if there is no match just multiline everything. Is this the intended behaviour?
To me, the logic should be to find the match first and then do something. If no match is found at all, do nothing

**Comment by jsoriano** [comment]
Ok, yes, you may be right, according to the [docs](https://www.elastic.co/guide/en/beats/filebeat/7.12/multiline-examples.html#multiline), with `multiline.negate: true` and `multiline.match: after`: _Consecutive lines that don’t match the pattern are appended to the previous line that does match._ I guess that the behaviour if no line has matched is open to interpretation, but I agree that current implementation can be unexpected for cases where the pattern never matches.

@urso @kvch wdyt?

In any case, I think it would be a better practice to have specific configs for different logs formats, and in this case it wouldn't happen that a configured multiline pattern doesn't ever match when `multiline.negate: true` and `multiline.match: after` are used.
If multiple logs formats need to be supported by the same multiline config as in this case, there is the workaround of extending the pattern as @sesto did.

**Comment by urso** [comment]
> I will try to explain better what I mean. Suppose we have 20 applications having totally different patterns and suppose that only 5 of those have multiline log events. In the current situation, I will need to design a regex matching all 20 patterns, instead of only 5. If I design the regex for those 5 only, in the rest 15 all log events will be concatenated. 

Why would you need 20 patterns if you only have 5 applications that use multiline. In order to keep some sanity  regarding multiple regex patterns I would create maybe 6 input configurations. 1 configuration with appropriate multiline configuration per app that uses multiline + one configuration without multiline.

Multiline requires the correct interplay of `pattern`, `negate`, and `match`. Oftentimes one does not just design a common regex.
If you find similarities between the different input configurations, such that only `patterns` needs to be adapted, then you might consider to create a pattern using an `or-operation` like `(pat1)|(pat2)|...`. These are computationally more expensive, though.

You can test multiline configurations with sample logs using this [go playground](https://play.golang.org/p/uAd5XHxscu) or on command line using the [filebeat-multiline-tester](https://github.com/hartfordfive/filebeat-multiline-tester).

**Comment by sesto** [comment]
@urso I am running applications on kubernetes. I cannot create separate inputs per application/set of applications because this will undermine the whole idea of kubernetes. I have a "cattle" not "pets". And this is my config:
```
filebeat.inputs:
     - type: container
        paths:
            - /var/log/containers/*.log
```
Tomorrow I might have 100s microservices. I cannot split the inputs by `paths`, it is not feasible. 
Ideally, all of these applications should have the same log pattern. Most of them do have the same pattern. Unfortunately, a number of them are 3d party applications, with different log patterns that I cannot manage.

**Comment by jsoriano** [comment]
@sesto take a look to the [autodiscover](https://www.elastic.co/guide/en/beats/filebeat/7.12/configuration-autodiscover.html) features of Filebeat, they are intended exactly for this use case.

Even if you have cattle, you probably have different kinds of animals :slightly_smiling_face: Autodiscover allows to define different configuration templates, and conditions to chose between them, so you can use different configurations for each kind of "animal" in your cattle.

With [hints-based](https://www.elastic.co/guide/en/beats/filebeat/7.12/configuration-autodiscover-hints.html) autodiscover, this configuration can even be defined in the annotations of the pods being monitored.

**Comment by sesto** [comment]
@jsoriano Thanks, I will have a look

**Comment by urso** [comment]
As @jsoriano already said, autodiscovery was introduced to Filebeat for exactly this use case.
