### ISSUE TITLE
filebeat generate command issues from release version

### ISSUE THREAD

**Issue by huaz836** [elastic/beats#24895]
I download filebeat from
`https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.12.0-linux-x86_64.tar.gz`

I use  command line to create custom modules, shows like
`./filebeat generate module mymod`
`cannot read template: open scripts/module/_meta/fields.yml: no such file or directory`

The `scripts` dir not in release tar.gz, may need to be fixed.

**Comment by urso** [comment]
One still requires the Beats source code to be checked out. The scripts directory can be found in the filebeat folder.

For generic questions/discussions I would recommend to ask them first on discuss.elastic.co. In the Forums you might get help from developers and community members alike, which gives you a much wider audience who might help with your problems more timely.

**Comment by kvch** [comment]
Unfortunately, we do not support generating Filebeat modules without checking out the repository.
