### ISSUE TITLE
[Fleet] Elastic agent should publish the list of packages in metadata

### ISSUE THREAD

**Issue by nchaulet** [elastic/beats#24901]
## Description

Replace https://github.com/elastic/fleet-server/issues/196 

To allow to search all the agent running an integration, it would be great if the agent publish that in this metadata

Something like `elastic.agent.packages: ["endpoint", "fleet_server"]` 

This was previously done by Kibana but with the move to Fleet Server we loose that feature.

**Comment by ruflin** [comment]
It seems odd that the agent should publish this data as the Elastic Agent does not know about packages and integrations. Instead we should find a way to make this happen inside Kibana.

**Comment by ruflin** [comment]
Related PR can be found here: https://github.com/elastic/beats/pull/25070

**Comment by michalpristas** [comment]
can we close this?

**Comment by ruflin** [comment]
yes, I think for now we don't need it.
