### ISSUE TITLE
[Stack Monitoring] Store Current shard size and max shard size of a monitored Elasticsearch

### ISSUE THREAD

**Issue by sayden** [elastic/beats#24916]
Stack Monitoring is missing two key metrics related with Shard information and health:

- Current Shard size: As shard over / under sizing is a hot topic in the Elasticsearch community, it will be useful to know how much space a shard is using.
- Shard max size / Shard configured size: Following the recommendations about shard sizing https://www.elastic.co/guide/en/elasticsearch/reference/current/size-your-shards.html#shard-size-recommendation , it will be useful to have this value to correlate with current shard size and setup alerts

**Comment by jasonrhodes** [comment]
Just a note: it may be difficult to store size for all shards, so from my perspective the more important thing to figure out is how to store _just_ the max shard size for an index. We can currently calculate the average size for all shards (we think), but if data is being routed to shards in some custom way, the average could miss a single exploding shard, and we wouldn't be able to tell, whereas max size would at least help us know at least one shard is over the recommended limit.

Thanks!

**Comment by jasonrhodes** [comment]
From @imotov -- 

> you can actually get this information on per individual shard level if you prefer. There is not very well known level parameter in the stats api that can do that https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html#index-stats-api-query-params

**Comment by smith** [comment]
Not prioritizing this at this time.
