### ISSUE TITLE
functionbeat 7.12 can't deploy -- unknown field 'VerifyConnection' in struct literal of type tls.Config

### ISSUE THREAD

**Issue by jasonslater2000** [elastic/beats#24925]
OS: OSX
Version: 7.12

2021-04-03T16:55:49.929-0700	DEBUG	[gcp]	gcp/cli_manager.go:47	Deploy finish for function 'jslater-pubsub'
Function: jslater-pubsub, could not deploy, error: error while creating function (code: 3):
Build failed: # pubsub/vendor/github.com/elastic/beats/v7/libbeat/common/transport/tlscommon
src/pubsub/vendor/github.com/elastic/beats/v7/libbeat/common/transport/tlscommon/tls_config.go:112:3: unknown field 'VerifyConnection' in struct literal of type tls.Config
src/pubsub/vendor/github.com/elastic/beats/v7/libbeat/common/transport/tlscommon/tls_config.go:123:4: unknown field 'VerifyConnection' in struct literal of type tls.Config
src/pubsub/vendor/github.com/elastic/beats/v7/libbeat/common/transport/tlscommon/tls_config.go:141:4: unknown field 'VerifyConnection' in struct literal of type tls.Config
src/pubsub/vendor/github.com/elastic/beats/v7/libbeat/common/transport/tlscommon/tls_config.go:149:8: config.VerifyConnection undefined (type *tls.Config has no field or method VerifyConnection); Error ID: 6191efcd
2021-04-03T16:55:49.929-0700	DEBUG	[cli-handler]	cmd/cli_handler.go:62	Deploy execution ended
Fail to deploy 1 function(s)

identical configuration works fine w/ functionbeat 7.11.1

**Comment by kvch** [comment]
Yes, `VerifyConnection` was introduced in Golang 1.15 and on GCP the most up to date Golang environment is 1.13. We need some conditional building to make sure it works with older Golang versions.

**Comment by ph** [comment]
So, this means that functionbeat in the latest revision doesn't work when using TLS options.

**Comment by andrewkroh** [comment]
I'm just adding a few links for background info in the issue.

References:

- GCP Cloud Function Go version is 1.13 - https://cloud.google.com/functions/docs/concepts/go-runtime
- 7.12 update to start using new Go features - https://github.com/elastic/beats/pull/22495

**Comment by chipzzz** [comment]
For anyone trying to use functionbeat with gcp still, what's the option? tried 7.11.1 but that fails too as OP mentioned but that fails too with same error.
