### ISSUE TITLE
[Windows 2019]: Unable to install agent on 7.13.0 Snapshot with policy having only System Integration.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#24934]
**Kibana version:** 7.13.0 Snapshot Kibana cloud environment

**Host OS and Browser version:** Windows 2019, All

**Build Details:**
```
  Artifact link used: https://snapshots.elastic.co/7.13.0-ea909f94/downloads/beats/elastic-agent/elastic-agent-7.13.0-SNAPSHOT-windows-x86_64.zip
  Build: 40014
  Commit: 5ea2cf6854c12b9c49217c22f9b5e70668a2379d

```

**Preconditions:**
1. 7.13.0 Snapshot Kibana cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana Cloud environment.
2. Navigate to Agents tab.
3. Install Agent with Default policy having only System integration.
4. Observe following errors after running install command:
```
Error: fail to enroll: fail to execute request to Kibana: x509: certificate has expired or is not yet valid:
Error: enroll command failed with exit code: 1
```
5. Add Endpoint Security to Default Policy. 
6. Run install command again and observe agent is installed with "Unhealthy" status. 

**Expected Result:**
Agent should be installed on 7.13.0 Snapshot with policy having only System Integration.

**Screenshots:**
![Agent 2019](https://user-images.githubusercontent.com/77374876/113579594-27857e00-9642-11eb-9307-91ebbe575be9.jpg)

**Logs:**
[elastic-agent-json.log](https://github.com/elastic/beats/files/6258380/elastic-agent-json.log)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource can you re-test this with latest BC code please?

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have validated this issue on latest 7.13 BC3 cloud-qa build. Build details are as follows:
```
BUILD 40647
COMMIT ac09c73a4a7998c770b50d39177c22036ae14375
Artifact page: https://staging.elastic.co/7.13.0-100107e6/summary-7.13.0.html
```

- Able to install agent with only system integration in user policy. We were not able to verify above with default policy as its currently not available.
- Agent logs and data stream was available.
![image](https://user-images.githubusercontent.com/72375798/116986947-0d47ca00-acec-11eb-823c-469d4c0431b7.png)


Hence closing this out.

Thanks
QAS
