### ISSUE TITLE
[agent build] "mage build" should produce a usable local product

### ISSUE THREAD

**Issue by faec** [elastic/beats#24936]
Currently, running `mage build` in `x-pack/agent` produces a local binary with no apparent errors -- however, this binary is not usable for development or testing, since it lacks auxiliary files / metadata that it needs to run. An example error is, for instance:

```
2021-03-29T15:10:25.558-0400	ERROR	log/reporter.go:36	2021-03-29T15:10:25-04:00: type: 'ERROR': sub_type: 'FAILED' message: Application: metricbeat--8.0.0[8f13961c-c7db-4686-bf35-d8a150a52ab8]: State changed to FAILED: operation 'operation-verify' failed to verify metricbeat.8.0.0: 2 errors occurred:
	* open /Users/fae/go/src/github.com/elastic/beats/x-pack/elastic-agent/data/elastic-agent-unknow/downloads/metricbeat-8.0.0-darwin-x86_64.tar.gz.sha512: no such file or directory
```

To build a working binary, one instead must run `mage dev:package` or another command in combination with the proper environment variables. (By default, this also builds packages for all platforms, and requires additional environment variables be set to restrict to a single / current platform.)

While there are lots of reasons we might want specialized build configurations, we should make sure the default `mage build` gives a usable product, or (if that is infeasible for some reason) gives a clear error / pointer to the correct method instead.

**Comment by ph** [comment]
> While there are lots of reasons we might want specialized build configurations, we should make sure the default mage build gives a usable product, or (if that is infeasible for some reason) gives a clear error / pointer to the correct method instead.

@faec should mage build be an alias to "mage dev:package"?

**Comment by faec** [comment]
I think `mage dev:package` would be better than the current behavior, though if there's a way to target only the host platform by default that would be nicer. If that's infeasible then maybe the default build could be equivalent to `dev:package` but also print instructions for how to manually restrict to a single platform?

**Comment by blakerouse** [comment]
I agree the `mage build` is not useful. I have never actually even used it.

I do not thing that `mage dev:package` should only be for the current platform. I use that command all the time to then take that same build and test it on Mac, Linux, and Windows. Working on all platforms is key for Elastic Agent.

**Comment by ph** [comment]
What if we make `mage build` that automatically default to the current platform and do what what `dev:package` does  and keep `dev:package` as is?

@urso WDYT?

**Comment by blakerouse** [comment]
That works for me.

**Comment by urso** [comment]
`mage build` is for developers and should produce a binary we as developers can use for local development (consistency between the different Beats).

Is there a reason why `mage build` produces an incomplete artifact? Is it because of the integration with the release manager?

> By default, this also builds packages for all platforms, and requires additional environment variables be set to restrict to a single / current platform.

I didn't check the Agent build in detail, but it contains a few calls to `Getenv/Setenv/LookupEnv`. In general (especially on the Beats side) we have too many hidden undocumented environment variables. Alternatively to that we might consider to introduce configuration file based profiles. Having a configuration file we could document the variables and effects in the files directly (e.g. Beats like reference configuration files with a set of default profile files, or single config file like Rusts' cargo).

**Comment by faec** [comment]
Agreed, I wasn't intending to propose a change to `dev:package`, it makes sense to have an option that builds everything, I just wouldn't want it being the default behavior for `mage build`.

**Comment by ph** [comment]
@urso the `mage build' doesn't create an artifact with the bundled beats which are sadly needed to actually be able to test and develop.

**Comment by urso** [comment]
> the `mage build` doesn't create an artifact with the bundled beats which are sadly needed to actually be able to test and develop.

Bad wording. `mage build` should produce an artifact (including the required Beats) that allows me to test its functionality locally (if the default configuration file).

**Comment by faec** [comment]
This issue no longer fits here, since agent is no longer in the beats repo (as I understand it related work is in progress elsewhere).
