### ISSUE TITLE
Updated to 7.12 through Fleet console currently seeing this in Elastic-Agent logs

### ISSUE THREAD

**Issue by S3l3ct3d** [elastic/beats#24946]
{"log.level":"error","@timestamp":"2021-04-05T07:34:48.250-0400","log.origin":{"file.name":"status/reporter.go","file.line":233},"message":"Elastic Agent status changed to: 'error'","ecs.version":"1.6.0"}

{"log.level":"error","@timestamp":"2021-04-05T07:34:48.250-0400","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2021-04-05T07:34:48-04:00: type: 'ERROR': sub_type: 'FAILED' message: Application: metricbeat--7.12.0[8f1c4c50-8379-11eb-8dcd-5b878f131d03]: State changed to FAILED: 1 error: 1 error: Error creating runner from config: 1 error: metricset 'system/load' not found","ecs.version":"1.6.0"}

{"log.level":"info","@timestamp":"2021-04-05T07:34:48.254-0400","log.origin":{"file.name":"status/reporter.go","file.line":233},"message":"Elastic Agent status changed to: 'online'","ecs.version":"1.6.0"}

{"log.level":"info","@timestamp":"2021-04-05T07:34:48.254-0400","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-04-05T07:34:48-04:00: type: 'STATE': sub_type: 'STARTING' message: Application: metricbeat--7.12.0[8f1c4c50-8379-11eb-8dcd-5b878f131d03]: State changed to STARTING: Starting","ecs.version":"1.6.0"}

{"log.level":"info","@timestamp":"2021-04-05T07:34:48.254-0400","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-04-05T07:34:48-04:00: type: 'STATE': sub_type: 'STARTING' message: Application: metricbeat--7.12.0[8f1c4c50-8379-11eb-8dcd-5b878f131d03]: State changed to RESTARTING: Restarting","ecs.version":"1.6.0"}

{"log.level":"info","@timestamp":"2021-04-05T07:34:49.540-0400","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-04-05T07:34:49-04:00: type: 'STATE': sub_type: 'STARTING' message: Application: metricbeat--7.12.0[8f1c4c50-8379-11eb-8dcd-5b878f131d03]: State changed to STARTING: Starting","ecs.version":"1.6.0"}

{"log.level":"error","@timestamp":"2021-04-05T07:34:50.042-0400","log.origin":{"file.name":"status/reporter.go","file.line":233},"message":"Elastic Agent status changed to: 'error'","ecs.version":"1.6.0"}

{"log.level":"error","@timestamp":"2021-04-05T07:34:50.042-0400","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2021-04-05T07:34:50-04:00: type: 'ERROR': sub_type: 'FAILED' message: Application: metricbeat--7.12.0[8f1c4c50-8379-11eb-8dcd-5b878f131d03]: State changed to FAILED: 1 error: 1 error: Error creating runner from config: 1 error: metricset 'system/load' not found","ecs.version":"1.6.0"}

[elastic-agent-json.log](https://github.com/elastic/elastic-agent-client/files/6257907/elastic-agent-json.log)

**Comment by ph** [comment]
@S3l3ct3d Have you tried to add a new integration in the agent policy? I think ` metricset 'system/load' ` was caused with an older version of the system package.

**Comment by S3l3ct3d** [comment]
Nothing has changed since the upgrade to 7.12. I am willing and able to test or try anything that you may need. 

Thanks for your assistance as well.

**Comment by EricDavisX** [comment]
@S3l3ct3d sorry for the long pause in reply - do you mind to test on a new / fresh install of 7.12 stack or 7.13 stack (even better) ?  Alternatively, I would just seek to confirm which version of the System Integration is in use in the policy where the error is being seen.  We had this problem and indeed fixed it in the System Package (which needs some specific 'admin' like stack side work to get it in use on the individual hosts running Agent...)
