### ISSUE TITLE
[Standalone Agent]:No "Agent Installed" confirmation message on successful standalone agent installation.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#24960]
**Kibana version:** 7.13.0 Snapshot Kibana cloud environment

**Host OS and Browser version:** Windows, All

**Build Details:**
```
  Artifact link used: https://snapshots.elastic.co/7.13.0-bf9ad0ac/downloads/beats/elastic-agent/elastic-agent-7.13.0-SNAPSHOT-windows-x86_64.zip
  Build: 40068
  Commit: a455d0fa208238638ac744ff255a590ad3fb042a
```

**Preconditions:**
1. 7.13.0 Snapshot Kibana cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Agents tab>Add Agent>Run Standalone.
3. Follow the steps provided under "Run Standalone" section.
4. Run `./elastic-agent install` and observe no "Agent Installed" confirmation message.

**Expected Result:**
Agent installed confirmation message should be displayed on successful standalone agent installation.

**Screenshot:**
![5](https://user-images.githubusercontent.com/77374876/113852263-0051bc80-97ba-11eb-93f4-a43080a6067f.JPG)

**Note:**
No impact on working of standalone agent is observed due to this issue.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
ping @blakerouse @michalpristas not sure if either of you know about recent changes that would impact the relating cli messaging specifically?
