### ISSUE TITLE
Use pinned versions of the elastic stack in testing scenarios

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#24972]
Testing scenarios currently use the [latest snapshots](https://github.com/elastic/beats/blob/a2440a662e5550c53f97bfaf69faef4824cdc986/testing/environments/snapshot.yml#L6) of docker images for the Elastic Stack. This has the benefit of earlier detecting issues with the more recent versions in development, but also has the problem of breaking builds if some unexpected breaking changes, or new fields, are introduced.

To avoid unexpectedly affecting all developers, while keeping testing Beats with the latest versions of the stack, the proposal would be to:
* Use specific pinned versions of the snapshots.
* Automatically create a daily PR that updates these versions to the most recent snapshot.
* If the PR is green, it is merged automatically.
* If the PR fails, it pings the build manager (or beats-contrib?) for investigation.

**Comment by v1v** [comment]
Initial draft:
- https://github.com/elastic/beats/pull/25148

Requires the automation part:
- Run the above script when there is a new version for the active branches
- Create the PR with the proposal changes.

**Comment by jsoriano** [comment]
This was already implemented, thanks!
