### ISSUE TITLE
elastic-agent: Report invalid variables while using dynamic inputs

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#24986]
Follow-up of: https://github.com/elastic/beats/issues/24943

If the integrations developer uses a non-existing variable together with the dynamic input, the entire input is ignored, but nothing seems to be reported in logs. The goal of this issue is to improve logging here to make debugging easier.

**Comment by blakerouse** [comment]
How do we know the variable is invalid? At any point that variable might be added by a dynamic provider. How does Elastic Agent know that its truly an invalid variable.

I think placing this information into the Elastic Agent logs would be very verbose and the wrong behavior as well. Being that the configuration can be re-rendered based on a change from any provider. I think this really comes down to better debugging of dynamic inputs, where it can show when inputs where removed and why. But I think that would be a specific action to inspect the running daemon.

Related to #21148

**Comment by ruflin** [comment]
The way I was thinking of it is that it is not logged when a variable is invalid but it is logged when a complete input is skipped because not all variables match. But this might also become tricky with the providers which have a list as we only know after all iterations if it matched 0 times 🤔

**Comment by ph** [comment]
@urso This might also related to the security around input templates.

**Comment by urso** [comment]
> This might also related to the security around input templates.

It can become a problem if we blindly log variables on error or make them available to some other operator in Kibana UI.

> The way I was thinking of it is that it is not logged when a variable is invalid but it is logged when a complete input is skipped because not all variables match

What makes a variable invalid?

> But this might also become tricky with the providers which have a list as we only know after all iterations if it matched 0 times

Dynamic inputs ignore inputs on error on purpose. We don't have an error/failure model, which means we can't distinguish failure from correct execution. Having 0 matches is not necessarily an error, but exactly what was intended by the user.

> Related to #21148

Being able to inspect the agents state would be helpful. We would need to reported (active) provider states + associated inputs.

Although inspect + debugging will be helpful, how can users discover potential problems (no input started via hints based autodiscovery thanks to a typo in the label name) without figuring out they have missing date 7 days after?
