### ISSUE TITLE
[Question]: Observed new notification message for restart after running agent installation command.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#24982]
**Observation:**
Currently, when we run  agent installation command on different OSs, we have observed a new notification message for restart along with successful agent installation message.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/113979881-73fbd400-9863-11eb-8cef-891dbefba8db.png)

Could any body confirm, if any changes have been made to agent installation process. 
Further, which service has been restarted with this trigger.

Thanks
QAS

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & assigend to @EricDavisX

**Comment by EricDavisX** [comment]
I'm unsure on this - seems lower priority for now, let us circle back when build is stable with Fleet Server included and re-assess.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have observed that this notification is still visible on 7.13 BC3 agent installation. Please refer below screenshot:


![image](https://user-images.githubusercontent.com/72375798/116517106-1a2f7c80-a8ec-11eb-8f55-b945d5a7a308.png)


Could you please confirm us which process is being triggered by it and why.

Thanks
QAS

**Comment by EricDavisX** [comment]
Hi - various operations can trigger a re-start of the Agent, I think including policy changes and Fleet Server / ES URL changes and maybe even log-level changes.  We can ask @ph to confirm if that is accurate.

**Comment by ph** [comment]
This the expected behavior, we install , we change the configuration and we restart to make sure the change is correctly picked up.

**Comment by dikshachauhan-qasource** [comment]
Hi @ph Thanks for the clarification.
