### ISSUE TITLE
[Docs] Update Metricbeat and Filebeat documentation to remove mentions of PKI authentication for Kibana APIs

### ISSUE THREAD

**Issue by mbarretta** [elastic/beats#24980]
In https://github.com/elastic/kibana/pull/82817, support for PKI auth against Kibana APIs was removed. The SSL documentation[0][1][2][3] still reference PKI configuration. This should be removed and a note highlighting the inability to use PKI should be added.

[0]https://www.elastic.co/guide/en/beats/metricbeat/7.12/configuration-ssl.html
[1]https://www.elastic.co/guide/en/beats/filebeat/7.12/configuration-ssl.html
[2]https://www.elastic.co/guide/en/beats/filebeat/7.12/setup-kibana-endpoint.html
[3]https://www.elastic.co/guide/en/beats/metricbeat/7.12/setup-kibana-endpoint.html

**Comment by EamonnTP** [comment]
Thanks @mbarretta Just to confirm. Do we need to change the paths to the following:

**Client:**
output.elasticsearch.ssl.certificate_authorities: ["/etc/client/ca.pem"]
output.elasticsearch.ssl.certificate: "/etc/client/cert.pem"
output.elasticsearch.ssl.key: "/etc/client/cert.key" 

**Server:**
output.elasticsearch.ssl.certificate_authorities: ["/etc/server/ca.pem"]
output.elasticsearch.ssl.certificate: "/etc/server/cert.pem"
output.elasticsearch.ssl.key: "/etc/server/cert.key" 

In terms of the note, could you provide some guidance on what we need to call out? Do we need to link to another section in the docs?

**Comment by mbarretta** [comment]
@EamonnTP 

Yes, I think just dropping `pki/` from the ssl path examples (you covered them all, I think) will do fine.

Re note, I think a note is only needed in the `setup-kibana-endpoint` pages. Since the configuration is for the Kibana API connection, I think some text in the intro linking to API authentication methods makes sense. Something like:


> Starting with Filebeat 6.0.0, the Kibana dashboards are loaded into Kibana via the Kibana API. This requires a Kibana endpoint configuration. Details on authenticating to the Kibana API can be found in the [Kibana API authentication documentation](https://www.elastic.co/guide/en/kibana/current/api.html#api-authentication)
