### ISSUE TITLE
why does packetbeat-linux-7.11.1 can not parse MySQL Community Server 8.0.23 while tcpdump can capture packets on ubuntu20.04

### ISSUE THREAD

**Issue by carlos9310** [elastic/beats#24991]

**Comment by jsoriano** [comment]
Hey @carlos9310,

This question probably belongs to discuss https://discuss.elastic.co/, could you please open a new topic there?

If you are opening this as an enhancement request, could you please provide more information about what you are missing and what you would expect?

I am closing this by now, please feel free to reopen if you can provide more information.

Thanks!
