### ISSUE TITLE
[elastic-agent] cloud restrict elastic-agent setup

### ISSUE THREAD

**Issue by simitt** [elastic/beats#25005]
For backwards compatibility on cloud, ensure that the `container` cmd only triggers the elastic-agent setup if any of the configuration files for the agent are present.

**Comment by ruflin** [comment]
Will this make testing without a container or in the default container harder? I wonder if we could have some logic that it is always executed by default but if a certain condition matches, it is skipped.

**Comment by simitt** [comment]
This will not impact the default container behavior, it is only in combination with the cloud setup.

**Comment by blakerouse** [comment]
The `container` command already skips the enrollment and boot strapping if `fleet.yml` is present (unless its forced by the environment variable)? Is this different than that?

**Comment by mostlyjason** [comment]
Tagging @ph track this one and adding to iteration board

**Comment by simitt** [comment]
@blakerouse yes, because for backwards compatibility to older ECE versions (which will not support the agent and fleet setup), there shouldn't be any notion of enrolling the elastic agent etc; there won't be a `fleet.yml` present when first called. 
The way we can figure this out is to not run a enroll/setup command when `ELASTIC_AGENT_CLOUD=false` or unset and no configuration file is provided. I'll create a PR for this in a bit.
