### ISSUE TITLE
[Metricbeat]: Unable to view "[Metricbeat System] Overview ECS dashboard" under Dashboard tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#25015]
**Kibana version:** 7.13.0 Snapshot Kibana cloud environment

**Host OS and Browser version:** All, All

**Build Details:**
```
  Artifact link used: https://artifacts-api.elastic.co/v1/search/7.13.0-SNAPSHOT
  Build: 40112
  Commit: 6f0d093915d937453c617a63cff5aee00a12a4c6
```

**Preconditions:**
1. 7.13.0 Snapshot Kibana cloud environment should be available.
2. Metricbeat must be installed for windows, mac .tar , linux .tar and .rpm.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Dashboards.
3. Search for "[Metricbeat System] Overview ECS dashboard".
4. Observe no such Dashboard available.

**Expected Result:**
"[Metricbeat System] Overview ECS dashboard" dashboard should be available under Dashboard tab for Metricbeat.

**Test Case reference:**
[T381637](https://elastic.testrail.io/index.php?/tests/view/381637)

**Screenshots:**
![4](https://user-images.githubusercontent.com/77374876/114368344-f9042780-9b9a-11eb-9b47-bd390deaa358.JPG)

**What's Working Fine:**
- Metricbeat data is generating for all OS's under Discover tab.

![Metricbeat](https://user-images.githubusercontent.com/77374876/114369713-4af97d00-9b9c-11eb-98db-ff3ccab18e42.png)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@ph who can take a look at this?  is it a package issue we need to fix?

**Comment by ph** [comment]
@EricDavisX This is a Metricbeat issue correct? We haven't changed anything in metricbeat for some time but did the "setup" metricbeat's subcommand was run?

**Comment by amolnater-qasource** [comment]
Hi @ph 

Yes, this is a Metricbeat issue and we have run `metricbeat setup` command. 
Further we observed expected data as per our testcases under all the other sections:
- Discover tab [Screenshots attached above- in **What's Working Fine** section]
- [Metricbeat System] Host overview ECS
- [Metricbeat System] Containers overview ECS

However as per our testcase we are unable to view "[Metricbeat System] Overview ECS dashboard" under dashboards.

Thanks 
QAS

**Comment by ph** [comment]
Can you add the output of the s**setup** subcommand?

**Comment by amolnater-qasource** [comment]
Hi @ph 
Please find following screenshot for the output of setup command:

![1](https://user-images.githubusercontent.com/77374876/114660788-8c606880-9d13-11eb-9bea-afa576494281.JPG)

Further, on revalidating this issue today we are getting required "[Metricbeat System]: Overview ECS" Dashboard, hence closing this out.

![2](https://user-images.githubusercontent.com/77374876/114660990-d9443f00-9d13-11eb-8b24-425945e698eb.JPG)

**Build details:**
Build: 40237
Commit: 8b60488a58eeae6be1b994bf6be0110d39e8924c

Thanks
QAS
