### ISSUE TITLE
Beats Index Template and Index Lifecycle forwards compatibility

### ISSUE THREAD

**Issue by urso** [elastic/beats#25018]
Index Templates v1 are deprecated in Elasticsearch (https://github.com/elastic/elasticsearch/issues/71307). In order to ensure forwards compatility with Elasticsearch 8, we should update Beats to move to the v2 API with template component support. Support is already available in libbeat, but we still default to the v1 API.

ILM and alias setup can be somewhat fragile at times. Deleting/updating the wrong resource at the wrong time can leave users with unmanaged indices. Moving to [data streams](https://www.elastic.co/guide/en/elasticsearch/reference/master/data-streams.html) streams already in 7.x will help improve robustness in resource setup and management.

Moving to data streams will not change the indexing strategy, naming, or versioning of Beats. We would just change which/how resources are setup:
- Index template will be updated to generate data streams instead of indices. We will add `"data_stream": { }` to the generated template if data streams are enabled.
- Do not generate first ILM index if data streams are enabled
- Do not set up Alias if data streams are enabled
- Create data stream when `<beatname> setup` is used (So we can create writer roles with reduced permissions). API: `PUT _data_stream/<name>`.

The data stream naming schema will follow the current index/alias naming schema. There are no changes required on the kibana index mapping setup.

Beats will default to v2 templates and data streams if Elasticsearch versions is > 7.13. Users should still be able to opt-out, though.

From an users point of view, this might be a breaking change. If alias settings are explicitely configured we will report a deprecation warning with details/link explaining to users that they should update their settings. In order to not surprise users with wrongly-named unexpected resources, we either have to fail or fall back to old school ILM+Alias generation.

**Comment by strawgate** [comment]
How are breaking changes to the templates going to be handled going forward? My understanding is that datastreams are the future and that the methodology going forward doesnt include putting the beat version in the datastream. This means the backing indices are pinned to some set of templates that will need to be forever forwards and backwards compatible?

**Comment by urso** [comment]
For Beats the indexing strategy will not change. The datastream name will be the same as the index name is today. All inputs/modules of a Beat will continue to index into the same datastream. Even from within Kibana, the datastream can be used as an ordinary Beats index. Templates are still allowed (also it is not necessarily encouraged) to introduce breaking changes between Beats versions.

**Comment by strawgate** [comment]
> The data stream naming schema will follow the current index/alias naming schema

The current index/alias naming scheme involves using ILM to generate ###### indices and to include the beat version in the index.

Datastreams require type-dataset-namespace which doesn't appear to be compatible with the current index naming scheme. The expected datastream would be something like `logs-generic-default` or `logs-system.application-default` or `metrics-system.process-default` and something like `winlogbeat-7.5.0` would violate the datastream naming convention. This would minimally require `log-winlogbeat-7.5.0-default` which again would violate the datastream naming convention.

You'd have to do something like `log-winlogbeat.7.5.0-default` to match the naming convention as its written but certainly not the spirit of the naming convention.

Given the datastream requirements I'm having a hard time figuring out how `The datastream name will be the same as the index name is today.` would work?

**Comment by urso** [comment]
To me an indexing strategy (among others) defines a common set of conventions for:
- Index naming
- Template setup + Field standardization
- Schema evolution strategy (e.g. add version to index name in order to introduce breaking changes, or forbid breaking changes).
- Data Lifecycle management
- Sharding, Replication, ...

The Indexing strategy has changed over time. Initially the default indexing strategy used to add a daily timestamp to indices, and one would have used custom scripts or currator to manage the Data/Index Lifecycle.
The template and index names originally were not versioned. We eventually moved to versioned indices/templates, in order to make it easier for users to deal with breaking changes between Beats versions. 

When Elasticsearch introduced ILM, we chose to update the default indexing strategy, to leverage the new available capabilities. The indexing strategy changes did include: Setup and prepare an ILM policy, updates templates to use ILM policies, use read/write aliases for indexing, remove daily timestamp from Index Naming.
It is true, that this strategy uses multiple indices under the hood, but as these indices are managed by Elasticsearch, users are not supposed to touch those indices directly. Or even touch the aliases once the system is setup (These are also owned and managed by Elasticsearch now). Users manually interacting with managed resources is a common source of errors. Instead users are required to read/write via the Aliases only, but resources must not be modified.

Elasticsearch now introduced a new Templating format and Datastreams as a new feature. From Beats point of view, Datastreams as a feature is not much different from Aliases + ILM policy + indices. It is just another way how resources are managed. Under the hood Datastreams use hidden indices named like `.ds_<your name>-<date>-<sequence number>` ([docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/data-streams.html#data-streams-generation)). Plus Elasticsearch puts adds some addtional restriction, e.g. you can't delete a template that is in use by a datastream. This makes it more difficult for users to mess up their setup, plus some idiosyncratics on setting up ILM+Aliases are gone, which makes the setup process easier for us. Other then that we will keep the indexing strategy. The datastream naming will continue to follow the Beats index naming.

> Datastreams require type-dataset-namespace which doesn't appear to be compatible with the current index naming scheme. 

No, datastreams do not require indices to be named `type-dataset-namespace`. Do not confuse The Agent indexing strategy with Datastreams as a feature in Elasticsearch. The Agent indexing strategy differs from the Beats indexing strategy. Although Agent runs Beats under the hood, it is no Beat. The Agent indexing strategy does mandate this naming format. The Agent indexing strategy also mandates that all events should have additonal meta-data to describe the datastream as well, to ease search in case one searches in multiple indices.

Elasticsearch even provides default ECS templates that match on `logs-*` and `metrics-*`. But from Elasticsearch [datastream docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/data-streams.html) we can tell that:
- (quote) `A data stream requires a matching index template. The template contains the mappings and settings used to configure the stream’s backing indices.`.
- (quote) `Every document indexed to a data stream must contain a @timestamp field, mapped as a date or date_nanos field type. `
- (quote) `Data streams are designed for use cases where existing data is rarely, if ever, updated. You cannot send update or deletion requests for existing documents directly to a data stream.`

The default Beats indexing strategy already fullfils these requirements. The datastream name in Elasticsearch will just be called `Filebeat-7.15.0` for example.
