### ISSUE TITLE
[Elastic Agent] Unenroll timeout for containers

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#25030]
**Problem**
When an Elastic Agent container is removed, it will leave an orphan agent in Fleet visible on the Agents page. Users have to manually force unenroll them to remove them from the page. This is particularly problematic for Elastic Agents in hosted agent policies because users are not allowed to unenroll them, so they will remain visible as offline forever.

Elastic Agents that run in container orchestration environments like ECE or Kubernetes should be stateless by design. When a container is removed the the agent API keys are deleted. This results in an orphan agent tracked in Fleet. 

**Solution**
An agent policy can specify an unenroll timeout so that it will automatically unenroll after being gone for a period of time. This will happen with a timeout value specified on the Fleet side. We need to consider the use case of temporary service disruptions. The agent should be able to resume if the service or network can recover in a short time window.

As an Elastic Agent operator, I want:
- [ ] To configure my agent policy with an unenroll timeout
- [ ] Fleet to force unenroll agents when they are offline more than a TTL so they don't remain active forever if they do not gracefully unenroll
- [ ] To remove all the orphan offline hosted agents from 7.13

Stretch:
- [ ] All agents will trigger an unenroll command when they are uninstalled to remove a manual step in the Fleet UI
- [ ] Agents will gracefully unenroll from Fleet when they get a SIG_TERM

**Comment by ph** [comment]
@mostlyjason @ruflin We need definition for this to implement in 7.14.

**Comment by mostlyjason** [comment]
@nimarezainia updated this based on the new definition, feel free to change if needed

**Comment by ph** [comment]
Elasticsearch issues at https://github.com/elastic/elasticsearch/pull/74180 merged in master, backported to 7.x

Fleet Server backport issue https://github.com/elastic/fleet-server/pull/472

**Comment by jen-huang** [comment]
Both of the above PRs are merged and backported so I think this can be closed now 🎉

**Comment by ruflin** [comment]
@blakerouse @ph Do we have any e2e tests in place for this?

**Comment by EricDavisX** [comment]
closing the loop: Blake reports in slack they are well tested in Fleet-Server repo.

**Comment by blakerouse** [comment]
This is well tested in an integration test in Fleet Server repository. It adds a policy with `unenroll_timeout` set and adds an Elastic Agent that has missed the checkin window > then the `unenroll_timeout` and it ensures that it unenrolls that Elastic Agent and invalidates it keys. The tests also ensures that other Elastic Agents that don't match the criteria are not unenrolled.

If we want to test the flow including that Kibana is setting the correct value in the `.fleet-policies` index then a e2e test should be added.
