### ISSUE TITLE
[Palo Alto] Add TCP Support 

### ISSUE THREAD

**Issue by jamiehynds** [elastic/beats#25035]
The Palo Alto module is currently limited to ingesting events via UDP. To ensure more reliable transmission of Palo Data data, users should have the option to ingest events via TCP, similar to our [Fortinet var.input options](https://www.elastic.co/guide/en/security/current/ingest-data.html). 

Users can enable this option today, but requires manual editing of the input.yml file:

```
type: syslog
protocol.tcp:
  host: "{{.syslog_host}}:{{.syslog_port}}"
```

Adding support for ssl.var is nice to have, to enforce mutual TLS.

**Comment by legoguy1000** [comment]
Doesn't look like this was worked yet.

**Comment by jamiehynds** [comment]
Closing this issue as we're working on adding support for TCP across all of our firewall integrations here: https://github.com/elastic/integrations/issues/1878
