### ISSUE TITLE
[elastic-agent][container] increase limit for retries to Kibana

### ISSUE THREAD

**Issue by simitt** [elastic/beats#25063]
The container cmd retries requests to Kibana up to [30 times with 1 second sleep intervals](https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/pkg/agent/cmd/container.go#L43-L44). 
Kibana can take several minutes to start up. Increase the retry counter/timeout accordingly, or make it configurable. This is important for scenarios where Kibana and the Elastic Agent get deployed at the same time, such as in ESS/ECE.

**Comment by ph** [comment]
@michalpristas Can you take a look at this one? 
@simitt I would consider this a bug, but the risk is to have a disconnected instance of Elastic Agent, right?

Should we make it retry infinitely

**Comment by blakerouse** [comment]
We should not make it go infinitely by default. It would be better to see the container restarted in Kubernetes versus it always up even though its not connected.

I think adding ENV variables to control this would be best.

**Comment by simitt** [comment]
making the timeout configurable SGTM; 

> but the risk is to have a disconnected instance of Elastic Agent, right?

yes, but in some cases that's preferable to having the container being restarted (because the elastic-agent is in `beta`, but `apm-server` also started from this process is `GA`).

**Comment by ph** [comment]
Ok, let's make it configurable.

**Comment by ph** [comment]
@simitt The retry PR were merged, can we close this issue?

**Comment by ruflin** [comment]
Closing, please reopen if issue still exists.
