### ISSUE TITLE
Release note/changelog missing since 7.9.0

### ISSUE THREAD

**Issue by merlixelastic** [elastic/beats#25107]
Changelog are available up to version 7.9.0 there:
 [https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/CHANGELOG.asciidoc](https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/CHANGELOG.asciidoc)

Changelog should go up the the latest version (7.12.0 at the time I'm writing this).
Documentation should contain release notes based on the changelog.

**Comment by dedemorton** [comment]
Closing this because we've added release notes to the Fleet User Guide here (starting in 7.13): https://www.elastic.co/guide/en/fleet/current/release-notes.html
