### ISSUE TITLE
[elastic-agent] error on checking but agent shows as healthy

### ISSUE THREAD

**Issue by simitt** [elastic/beats#25122]
Configuring a managed policy in Kibana and enrolling with elastic-agent and fleet-server creates policy and agent as expected, but after some time agents logs errors for checking API while Kibana still shows agent as healthy with recent activity; agent logs:
```
2021-04-16T09:34:40.700Z	INFO	status/reporter.go:236	Elastic Agent status changed to: 'online'
2021-04-16T09:39:41.837Z	ERROR	fleet/fleet_gateway.go:203	Could not communicate with Checking API will retry, error: fail to checkin to fleet: Post "https://e28578e7321b:8220/api/fleet/agents/c3504b01-760a-46c5-9a03-81fcc70fb4f8/checkin?": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-04-16T09:46:08.009Z	ERROR	fleet/fleet_gateway.go:203	Could not communicate with Checking API will retry, error: fail to checkin to fleet: Post "https://e28578e7321b:8220/api/fleet/agents/c3504b01-760a-46c5-9a03-81fcc70fb4f8/checkin?": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
<img width="1315" alt="Screenshot 2021-04-16 at 12 09 53" src="https://user-images.githubusercontent.com/5555349/115009543-ae412300-9eac-11eb-81d1-dce8d0ea645e.png">

## How to reproduce
Configure a managed policy in `kibana.yml` and start kibana:
```
xpack.fleet.packages:
  - name: fleet_server
    version: 0.2.1
xpack.fleet.agentPolicies:
  - name: Test policy
    is_managed: true
    id: test-policy
    is_default_fleet_server: true
    package_policies:
      - package:
          name: fleet_server
        name: Fleet Server
        inputs:
          - type: fleet-server
            vars:
            - name: host
              value: 0.0.0.0
```

Start Elastic Agent docker container with following command (change hosts and passwords accordingly):
```
docker run --name elastic-agent-local -it \
  --env Fleet_SERVER_POLICY_ID=test-policy \
  --env KIBANA_FLEET_SETUP=1  \
  --env FLEET_SERVER_ENABLE=1 \
  --env FLEET_ENROLL=1  \
  --env FLEET_INSECURE=1 \
  --env ELASTICSEARCH_HOST="http://elasticsearch:9200" \
  --env ELASTICSEARCH_USERNAME=admin \
  --env ELASTICSEARCH_PASSWORD=password \
  --env KIBANA_FLEET_HOST="http://kibana:5601" \
  --env KIBANA_FLEET_PASSWORD="password" \
  --env KIBANA_FLEET_USERNAME="admin"  \
  -p 8220:8220 --network-alias elastic-agent  \
  --rm docker.elastic.co/beats/elastic-agent:7.13.0-SNAPSHOT
```

## Version
snapshot build `7.13` (2021/04/16)

**Comment by ruflin** [comment]
@michalpristas Can you take a look at this?

**Comment by ph** [comment]
We have discussed in our weekly sync, this might be an OK log message, we need to align the HTTP polling timeout to reduce the number of log messages. We do not consider this aa blocker.

**Comment by ruflin** [comment]
Looking at this I stumbled over the following TODO in our code: https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/pkg/agent/application/gateway/fleet/fleet_gateway.go#L200 Not sure I fully understand the todo but might be relevant.

**Comment by dikshachauhan-qasource** [comment]
Hi Team, 

We are also facing this issue though we have updated port no. for fleet server url, still getting above mentioned errors.

![image](https://user-images.githubusercontent.com/72375798/116880046-20e92700-ac3f-11eb-8b62-12befe40444b.png)

Kindly please let us know if we are missing anything.

Thanks
QAS

**Comment by blakerouse** [comment]
This is because of a missing backport into 7.x and 7.13. This is now fixed.

elastic/beats#25498
