### ISSUE TITLE
[elastic-agent] docker container cannot be stopped

### ISSUE THREAD

**Issue by simitt** [elastic/beats#25123]
Docker container cannot be stopped after starting the elastic-agent docker container with fleet setup and fleet-server enrollment enabled;  keyboard interrupt is ignored and `docker stop <id>` just hangs forever. There is no indicator of why it hangs in the logs. The only way to shut down was to restart the docker daemon. 

This is not a consistent behavior, but was observed multiple times. To exclude some weird state, the docker environment was completely wiped in between. 

Behavior observed with `7.13.0-SNAPSHOT` (2021/04/16)

**Comment by blakerouse** [comment]
@simitt I have not be able to reproduce this, the container stops for my ctrl-c. Is it possible this is only the case when running a legacy apm-server? The `run` command` attaches to the signals.

**Comment by simitt** [comment]
I already feared that this would be hard to reproduce; not certain I always apm-server legacy running when encountering it. Is it ok to keep this issue open for a bit to collect feedback if others run into it; and close it if not? Will keep an eye out for it to happen again.

**Comment by blakerouse** [comment]
we can keep it open, but I do want to make it clear that pressing `CTRL-C` doesn't mean that Elastic Agent will stop instantly or even quickly.

Elastic Agent signals each running application (filebeat, metricbeat, fleet-server, apm-server, etc...) to stop, giving them 60 seconds to fully stop. If it does not fully stop after 60 seconds it will kill it and then it will stop itself. This is to ensure that the application have plenty of time to persist any state and send any events that is has queued up.

**Comment by simitt** [comment]
thanks @blakerouse; the graceful shutdown makes sense. I was waiting several minutes to rule that out, but the app was really stuck, and I had to do a full docker daemon restart to be able to kill the container.

**Comment by ph** [comment]
@simitt @blakerouse so we are keeping this open on the backlog and remove the 7.13.0 label on? Could we have a dead lock in the code that could cause the shutdown logic to hang?

**Comment by simitt** [comment]
Yes I believe that makes sense for now; updated the labels accordingly

**Comment by simitt** [comment]
Haven't seen this issue again, so closing it out,
