### ISSUE TITLE
Use addresses and names reserved for test data (and documentation)

### ISSUE THREAD

**Issue by ypid-geberit** [elastic/beats#25134]
**Describe the enhancement:**

Addresses and other identifiers are anonymized in this repo (for example test logs) which is good practice. Using identifiers that are explicitly reserved for use cases like this would make this even clearer.

#### MAC (rfc7042)

https://tools.ietf.org/html/rfc7042#page-7

The following values have been assigned for use in documentation:

* 00:00:5E:00:53:00 to 00:00:5E:00:53:FF for unicast
* 01:00:5E:90:10:00 to 01:00:5E:90:10:FF for multicast.

#### IPv4 (rfc5737)
https://tools.ietf.org/html/rfc5737

* 192.0.2.0/24
* 198.51.100.0/24
* 203.0.113.0/24

#### IPv6 (rfc3849)

https://tools.ietf.org/html/rfc3849

* 2001:DB8::/32

#### Domains (rfc2606)

https://tools.ietf.org/html/rfc2606

* "example.com", "example.net", "example.org" reserved example second level domain names
* ".example" TLDs for testing and documentation examples

**Describe a specific use case for the enhancement or feature:**

When I search over this repo, I find `8.8.8.8` all over the place as an example for a DNS server. Example: https://github.com/elastic/beats/blob/master/x-pack/filebeat/module/sophos/xg/test/firewall.log

With this issue, I want to propose better/unbiased examples.

**Comment by dedemorton** [comment]
Closing this issue for now because it's quite old and the work is a low priority compared to other requests in our work queue. I agree that using the reserved names and addresses should be a best practice in our docs.
