### ISSUE TITLE
[FileBeat] Sophos xg field has a space in it's name

### ISSUE THREAD

**Issue by mvanderlee** [elastic/beats#25154]
Since at least 7.9.0, Sophos xg has `trans_src_ ip` instead of `trans_src_ip`

https://github.com/elastic/beats/blob/23e4403ae093fcc8f7905345cad2c7ad256976d8/x-pack/filebeat/module/sophos/xg/_meta/fields.yml#L228

**Comment by legoguy1000** [comment]
Easy fix but i don't even see that field anywhere in teh pipeline.

**Comment by legoguy1000** [comment]
PR opened
