### ISSUE TITLE
Hearthbeat ready for developer self-service in ECK

### ISSUE THREAD

**Issue by plaformsre** [elastic/beats#25152]
**Describe the enhancement:**

We have hundreds of teams that would need to contribute their configuration of Healtbeat endpoints to be monitored. In reality, all teams reside in their own Kubernetes namespace and have no access to the central service of Hearthbeat. 

**Describe a specific use case for the enhancement or feature:**

What we are looking for is a simple way for developers to share 1-2 endpoints to be monitored in a configmap and then ECK can read and validate the config and incorporate into a running Heartbeat without failing. 

We do not really want to work around the functionality by copying configmap cross namespaces or clusters, but rather being detected automatically by e. g. labels or annotations.

**Comment by jsoriano** [comment]
Hey @mapdegree,

Thanks for reporting.

Heartbeat supports [autodiscover](https://www.elastic.co/guide/en/beats/heartbeat/7.12/configuration-autodiscover.html), what allows to define configuration using templates and conditions. With [hints-based autodiscover](https://www.elastic.co/guide/en/beats/heartbeat/7.12/configuration-autodiscover-hints.html), configuration can be also defined in annotations.
Would this work in your case?
