### ISSUE TITLE
[Discuss] Upstream geoip database changes affecting tests

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#25159]
Changes in the Elasticsearch geoip database have always affected golden file tests in Beats. When the database changes and an IP address moves to a new location our golden file tests break (there are several reasons the tests could break).

Historically we dealt with this by updating the golden file tests with enrichments based on the new geoip database version. This hasn't been too much of a hassle because the geoip database wasn't updated since 2019, but now that burden will grew because of enhancements to Elasticsearch (https://github.com/elastic/elasticsearch/issues/68920) enable the database to automatically update itself.

I see two possible solutions:

1. Disable database updates via an Elasticsearch property `ingest.geoip.downloader.enabled: false`. This will cause Elasticsearch to use the 2019 database version that is embedded. This would work for now, but the embedded database will be removed in 8.x IIUC. We might be able to request that infra host a test geoip database that is static, and then we can configure our test ES instances to use the static database URL (idea suggest by @jakelandis).

2. Update test code to ignore geo IP fields (like add them to https://github.com/elastic/beats/blob/226485bd22e13a027acc8e644cc1f43280d8b851/filebeat/tests/system/test_modules.py#L229-L230). The downside here is that we might not catch configuration issues with geoip processors in pipelines.

**Comment by leehinman** [comment]
I like Option 2 if we can test to make sure the fields are present, but we don't compare the values.  This should let us know if the geo processor adds or deletes fields.

We would then be trusting the tests in elastic/elasticsearch#68920 to let us know that lookups work.
