### ISSUE TITLE
Filebeat setup throws Error setting up ML for apache_ecs: 10 errors

### ISSUE THREAD

**Issue by n0othing** [elastic/beats#25181]
FIlebeat Version:  `7.12.0`
Operating System: `macOS Big Sur (11.2.3)`

Bug Description:

Filebeat's `setup` command can throw a strange error, presumably related to not being able to overwrite existing `filebeat-apache_ecs*` and `filebeat-nginx_ecs*` Machine Learning Jobs:

```
2021-04-20T14:05:14.035-0400	ERROR	instance/beat.go:971	Exiting: 1 error: Error setting up ML for apache_ecs: 10 errors: ; ; ; ; ; ; ; ; ; 
Exiting: 1 error: Error setting up ML for apache_ecs: 10 errors: ; ; ; ; ; ; ; ; ; 
```

![fb_ml_jobs](https://user-images.githubusercontent.com/11917935/115446501-4f99e300-a1e5-11eb-89ca-f78dec9ed22e.jpg)

Deleting these 10x jobs and re-running `setup` completes without error.

Steps to Reproduce: 

On a brand new `7.12.0` Elasticsearch cluster (w/ Machine Learning enabled) run the Filebeat `setup` command --> after it completes, run it again.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

While performing testing on 7.13 P1 regression plan, we have also observed same errors on filebeat installation at Linux machine.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/117131932-bf9c9180-adbf-11eb-9442-2d7fec28afe9.png)

However, attempted same on Linux arm machine and found it working fine there.

![image](https://user-images.githubusercontent.com/72375798/117132132-02f70000-adc0-11eb-8023-3bc87b38f3c5.png)

Thanks
QAS

**Comment by alexabidri** [comment]
Same issue on my side, any updates ?

**Comment by EricDavisX** [comment]
@ph or @urso when you can make time, can you help review and see if we should poke into it deeper and who should look at it (if not Agent team) ?  Thanks

**Comment by kvch** [comment]
This issue resurfaces from time to time. However, I could never reproduce it no matter what I did. 

The recommended way to install ML job is using Kibana, not Beats. The current `--machine-learning` and the whole ordeal is deprecated and going to be removed soon.

**Comment by ph** [comment]
@kvch I think it's fair, we will not fix that in beats, the elastic agent and integration are the new way to go. I will keep open but I think we should  not dedicate time in it.

**Comment by urso** [comment]
The code to setup ML via Beats has already been removed from the master branch.

**Comment by Sara-cos** [comment]
Same error in windows power shell
`Exiting: 2 errors: Error setting up ML for nginx_ecs: 10 errors: ; ; ; ; ; ; ; ; ; ; Error setting up ML for apache_ecs: 10 errors: ; ; ; ; ; ; ; ; ;`

and I was using the 14 days trial version

**Comment by Sara-cos** [comment]
Same error in windows power shell
`Exiting: 2 errors: Error setting up ML for nginx_ecs: 10 errors: ; ; ; ; ; ; ; ; ; ; Error setting up ML for apache_ecs: 10 errors: ; ; ; ; ; ; ; ; ;`

and I was using the trial version

**Comment by liu-xiao-guo** [comment]
I have the same error when trying to run "filebeat setup" command. It give me the error:
root@liuxgu:/etc/filebeat# filebeat setup
Overwriting ILM policy is disabled. Set `setup.ilm.overwrite: true` for enabling.

Index setup finished.
Loading dashboards (Kibana must be running and reachable)
Loaded dashboards
Setting up ML using setup --machine-learning is going to be removed in 8.0.0. Please use the ML app instead.
See more: https://www.elastic.co/guide/en/machine-learning/current/index.html
Exiting: 1 error: Error setting up ML for apache_ecs: 10 errors: ; ; ; ; ; ; ; ; ; 
![image](https://user-images.githubusercontent.com/8455957/124542338-ceea9a80-de55-11eb-8970-f5be04786009.png)

**Comment by fuomag9** [comment]
same error RHEL 8.4

**Comment by XxLilBoPeepsxX** [comment]
Same error here, Ubuntu 20.04


```Exiting: 1 error: Error setting up ML for apache_ecs: 17 errors: ; ; ; ; ; ; ; ; ; ; error while setting up visualization: ml_http_access_map_ecs, error: Saved object [visualization/ml_http_access_map_ecs] conflict; error while setting up visualization: ml_http_access_source_ip_timechart_ecs, error: Saved object [visualization/ml_http_access_source_ip_timechart_ecs] conflict; error while setting up visualization: ml_http_access_status_code_timechart_ecs, error: Saved object [visualization/ml_http_access_status_code_timechart_ecs] conflict; error while setting up visualization: ml_http_access_top_source_ips_table_ecs, error: Saved object [visualization/ml_http_access_top_source_ips_table_ecs] conflict; error while setting up visualization: ml_http_access_top_urls_table_ecs, error: Saved object [visualization/ml_http_access_top_urls_table_ecs] conflict; error while setting up visualization: ml_http_access_unique_count_url_timechart_ecs, error: Saved object [visualization/ml_http_access_unique_count_url_timechart_ecs] conflict; error while setting up visualization: ml_http_access_events_timechart_ecs, error: Saved object [visualization/ml_http_access_events_timechart_ecs] conflict```

**Comment by EvgenyPrikhodko** [comment]
Oracle Linux 8.5 
![image](https://user-images.githubusercontent.com/25795145/145906121-ee03bd8d-c568-4d8d-b3bb-d8df44166b34.png)

**Comment by Lokey92** [comment]
Encountering similar issue this morning:

```
2022-05-09T11:13:02.175-0600	ERROR	instance/beat.go:1014	Exiting: 1 error: Error setting up ML for nginx_ecs: 10 errors: ; ; ; ; ; ; ; ; ; 
Exiting: 1 error: Error setting up ML for nginx_ecs: 10 errors: ; ; ; ; ; ; ; ; ; 
```

Trying to run setup on CIsco module (Meraki), ingest pipelines aren't loading. 

Deployment is on 7.17.3 same as the beat.
