### ISSUE TITLE
[Integrations] Docker images are only built for AMD, not for ARM

### ISSUE THREAD

**Issue by mdelapenya** [elastic/beats#25194]
This results in the e2e-testing project not being able to test in ARM, as the AMD images for Redis, Mysql, etc cannot be run in the ARM workers.

As we do not know if all integrations support building images in ARM, it's very probably that not all of them can be built, causing we will be skipping them at e2e test time on ARM.

cc/ @jsoriano

**Comment by mdelapenya** [comment]
@jsoriano Do you think we should update the `mage` goals to append the platform in the docker tag? something like?

```diff
- https://container-library.elastic.co/r/integrations-ci/beats-redis:5.0.5-1-amd64
+ https://container-library.elastic.co/r/integrations-ci/beats-redis:5.0.5-1-arm64
```

**Comment by jsoriano** [comment]
> @jsoriano Do you think we should update the `mage` goals to append the platform in the docker tag? something like?
> 
> ```diff
> - https://container-library.elastic.co/r/integrations-ci/beats-redis:5.0.5-1-amd64
> + https://container-library.elastic.co/r/integrations-ci/beats-redis:5.0.5-1-arm64
> ```

This will also imply to modify all references to these images.

The alternative would be to push multi-architecture manifests, but not sure about the implications of this.

**Comment by mdelapenya** [comment]
I think this is not relevant any more and can be closed for now
