### ISSUE TITLE
[elastic-agent] Change log message from Kibana to Fleet Server

### ISSUE THREAD

**Issue by simitt** [elastic/beats#25199]
Some log messages still mention Kibana, although the Agent now communicates via Fleet Server. Go through code and replace Kibana with Fleet Server where appropriate. 

Example
```
Error: fail to enroll: fail to execute request to Kibana: status code: 0, Kibana returned an error: , message: Resource is under maintenance / recovery.
```

**Comment by ruflin** [comment]
I opened https://github.com/elastic/beats/pull/25365 to get this fixed: https://github.com/elastic/beats/pull/25365
