### ISSUE TITLE
[Heartbeat] Flexible screenshot functionality

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#25201]
As mentioned in [this forum post](https://discuss.elastic.co/t/need-to-disable-all-the-steps-snaps-in-elastic-synthetic/269916) it would be useful to not create screenshots for every run. This issue proposes adding a new `screenshot` option that would have several modes, in-line with the [`http.response.body`](https://www.elastic.co/guide/en/beats/heartbeat/current/monitor-http-options.html#monitor-http-response) options:

1. `always`
2. `on_error`
3. `never`

A challenge here is that for `on_error` we'd have to buffer the screenshots in heartbeat, waiting for the error event before sending them if we want to maintain the entire journey's screenshots. Alternatively, we could have `on_error` just retain the screenshot of the error-ing step.

I think for an initial implementation here that makes more sense since it's much more lightweight.

**Comment by paulb-elastic** [comment]
I’d agree that having screenshots for all steps (when any step is in error) would be the desired end goal here, as that adds a lot of value in terms of context, however understand it’s a more complex implementation (so, having it just for the failed step initially is still an improvement and offers more flexibility).

**Comment by jahtalab** [comment]
I think we can expand the `--screenshots` config option in the synthetic agent to accept `always` `on_error` and `never`, so then heartbeat only passes these arguments to the agent.

An alternative approach is to define a retention policy in ES for screenshots, e.g. keep all screenshots for one day then only keep screenshots for errors. WDYT?

**Comment by paulb-elastic** [comment]
Being depriorised from 7.14 in favor of de-duping

**Comment by vigneshshanmugam** [comment]
closed by https://github.com/elastic/synthetics/pull/311

**Comment by justinkambic** [comment]
I tested this in a local cluster with recent Heartbeat, worked as expected.
