### ISSUE TITLE
Update auditbeat docs for systemd to add LimitNOFILE to systemd service

### ISSUE THREAD

**Issue by msimos** [elastic/beats#25216]
The current docs only talk about macOS when getting "too many open files":

https://www.elastic.co/guide/en/beats/auditbeat/master/ulimit.html

However this can also be an issue with systemd as it only applies the default 1024. In production this can be too low as well as seen here for example:

https://discuss.elastic.co/t/auditbeat-filebeat-error-system-socket-dataset-setup-failed-unable-to-monitor-probe-p-inet6-create-inet6-create-proto-p3-perf-event-open-too-many-open-files/251210

The documentation either known issues above or in the URL:

https://www.elastic.co/guide/en/beats/auditbeat/master/running-with-systemd.html

Add this to /lib/systemd/system/auditbeat.service or use /etc/systemd/system/auditbeat.service.d/override.conf with something like:

[Service]
LimitNOFILE=1048576

**Comment by flakrat** [comment]
I just installed Auditbeat 7.14 via RPM (from elastic.co) on a RHEL 7 system and encountered the same issue. Auditbeat worked running it interactively but not via Systemd:

```
/usr/share/auditbeat/bin/auditbeat -c /etc/auditbeat/auditbeat.yml --path.home /usr/share/auditbeat --path.config /etc/auditbeat --path.data /var/lib/auditbeat --path.logs /var/log/auditbeat -e -d "*"
```

Copying `/usr/lib/systemd/system/auditbeat.service` to `/etc/systemd/system/` and then adding `LimitNOFILE=65536` to the `[Service]` section got it running via Systemd.
