### ISSUE TITLE
[Elastic Agent] Improve logging

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#25230]
The logging output in Elastic Agent is sometimes a bit cryptic and for someone not knowing the internals of Elastic Agent, hard to interpret. Some effort should be spent going through all the log messages and evaluate how it can be improved to make it easier to understand.

Every Error message should contain details around why it is happening and potentially how it can be resolved.

**Comment by mtojek** [comment]
One of the goal would be improving logging around enrollment. We can figure out the root cause of flakiness of https://github.com/elastic/elastic-package/pull/329 .

**Comment by jlind23** [comment]
@ruflin this one seems to be to generic for me. I would rather close it and keep the following issues:
- https://github.com/elastic/fleet-server/issues/838
- https://github.com/elastic/beats/issues/28334
- https://github.com/elastic/beats/issues/27764
- https://github.com/elastic/beats/issues/22902

What do you think?

**Comment by ruflin** [comment]
SGTM. Going to close this. I also plan to add some recommendation around logging for processes run by Elastic Agent to dev docs soonish.
