### ISSUE TITLE
[Elastic Agent] Provide k8s manifest to deploy agent on k8s with automatic enrolment to fleet.

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#25237]
We already support [Elastic-Agent on k8s in standalone mode](https://github.com/elastic/beats/blob/master/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml). We should be able to provide proposed manifests so as to start agent as Daemonset pods and automatically enrol them to fleet server (ie https://github.com/elastic/elastic-package/blob/f092978b96cc25d55144236d46b2d201079316a7/internal/install/static_kubernetes_elastic_agent_yml.go#L39). Then through kibana we can enable the k8s integration accordingly. 

And if we tune k8s package so as to enable conditions we can do sth similar with https://github.com/elastic/integrations/blob/88b02e1ec40e122fa0de28f4b777cb51b3aba[…]s/linux/data_stream/network_summary/agent/stream/stream.yml.hbs so as we can use `leaderelection` for `state_*` metrics from kibana UI as we do with standalone mode.

I'm not sure about the priority of this right now but let's have a specific issue for reference.

cc: @mukeshelastic @exekias @blakerouse

**Comment by adam-stokes** [comment]
I dont know if this helps but here is a WIP im doing that brings up a full stack with fleet server enabled.  The next step would be to add X number of agents to enroll into fleet and run our e2e test suite against it

https://github.com/elastic/e2e-testing/tree/k8s-deployment/cli/config/kubernetes

**Comment by ChrsMark** [comment]
This is cool @adam-stokes , thanks for sharing! The Agent part you are planning to add should be reused here too I guess.

**Comment by ChrsMark** [comment]
An interesting related one: https://github.com/elastic/k8s-dev/issues/271 (cc: @MichaelKatsoulis )
