### ISSUE TITLE
[Filebeat][Fortinet Module] Can we include hardware id in observer.serial_number in fortimail fileset, just in like firewall fileset?

### ISSUE THREAD

**Issue by kunisen** [elastic/beats#25254]
**Describe the enhancement:**
**Describe a specific use case for the enhancement or feature:**

We use firewall fileset of Filebeat Fortinet module.
We found that, unlike the firewall fileset in the fortinet module, the device ID was not set to `observer.serial_number`.
Therefore we need to set it manually like this in pipeline.yml.

```
​ - rename:
field: rsa.misc.hardware_id
target_field: observer.serial_number
ignore_missing: true
```

Could we improve this in the future version please?

**Comment by legoguy1000** [comment]
@jamiehynds There are 26 modules that use the rsa2elk conversions and the fortinet module is the only one to have sample data that actually has content for the `rsa.misc.hardware_id` field.  I can update just the fortinet module or I can do all 26 so its consistent between them.  Just let me know.

**Comment by jamiehynds** [comment]
Hi @legoguy1000 - I'd recommend only updating the Fortinet module for now. Thanks for yet another contribution!

**Comment by legoguy1000** [comment]
I merged the minor change with another PR I already had open for Fortinet.  PR is updated and ready for review. @kunisen please take a look at the PR and let me know if you have any comments on the other changes I made for the Fortinet Firewall pipeline. It was mainly removing duplicate items and a few other minor changes.
