### ISSUE TITLE
[Filebeat][Fortinet Module] Can we add RFC​6587 in fortimail fileset when sending the syslog

### ISSUE THREAD

**Issue by kunisen** [elastic/beats#25253]
**Describe the enhancement:**
**Describe a specific use case for the enhancement or feature:**

We use fortimail fileset of Filebeat Fortinet module to send syslog.
We found that on fortimail side, the log is sent as RFC​6587 format, thus we need to add `framing: rfc6587` in module setting (input.yml).

Could we improve this in the future version please?

**Comment by jamiehynds** [comment]
@leehinman am I correct in saying that your [RFC6587 PR](https://github.com/elastic/beats/pull/23724) will allow us to easily add this setting to the Fortinet module?
