### ISSUE TITLE
[Cyberark] Deprecate experimental Cyberark Filebeat Module + Integration

### ISSUE THREAD

**Issue by jamiehynds** [elastic/beats#25261]
Now that our new Cyberark PSA is complete, we need to deprecate our experimental Cyberark filebeat module and Elastic agent integration, in favour of the new module. 

Experimental module: [Docs](https://github.com/elastic/beats/tree/master/x-pack/filebeat/module/cyberark) | [Module ](https://github.com/elastic/beats/tree/master/x-pack/filebeat/module/cyberark)

New module: [Docs](https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-module-cyberarkpas.html) | [Module](https://github.com/elastic/beats/tree/master/x-pack/filebeat/module/cyberarkpas)

**Comment by shimonmodi** [comment]
Events captured from CyberArk - https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/PASREF/Vault%20Audit%20Action%20Codes.htm
