### ISSUE TITLE
Osquerybeat: osquery failed: write unix ->/var/run/642722736/osquery.sock: write: broken pipe

### ISSUE THREAD

**Issue by aleksmaus** [elastic/beats#25297]
Osquerybeat often fails to execute scheduled or ad-hoc queries after user creates the two scheduled queries and restarts the agent. 

The issue seems to be caused by multiple goroutines sending queries over osqueryd socket at the same time, that leads to intermittent errors, for example:
```
osquery failed: write unix ->/var/run/642722736/osquery.sock: write: broken pipe
```
```
: *osquery.ExtensionResponse error reading struct: error reading field 0: read unix ->/var/run/404419649/osquery.sock: i/o timeout
```

For confirmed bugs, please report:
- Version: 7.13  and 8.0.0-SNAPSHOT
- Operating System: tested on Mac but most likely all
- Steps to Reproduce: 
1. Add osquery manager integration to the policy
2. Enroll the agent 
3. Add two scheduled queries
<img width="1528" alt="Screen Shot 2021-04-25 at 10 25 03 AM" src="https://user-images.githubusercontent.com/872351/115997311-ab32ea80-a5b0-11eb-9319-263636526ff2.png">

4. Restart the agent 
5. Check osquerybeat log. It should show the the failures to execute the scheduled queries.
6. Try ad-hoc query it will fail on time out.

Leaving the osquerybeat running for some time creates the time gap between the two queries and they could start working again.

**Comment by melissaburpo** [comment]
@aleksmaus - I'm hitting this exact same error in a new 7.14 cluster. I'm just going to reopen this issue for now, but please let me know if I should create a new one.

Here's my setup + version info.

* Yesterday I enrolled a few agents that include 2 linux VMs - one CentOS 8, and one Debian 10. Those are the only 2 with this error (Windows and MacOS are fine).
* I scheduled some queries.
* Yesterday all of the queries ran as expected with regular updates.
* Today when I accessed the cluster again, I get this error on the 2 Linux VMs for all live queries I run:
```
osquery failed: write unix @->/var/run/275791736/osquery.sock: write: broken pipe
```
* I'm connected to both VMs, and it looks like elastic agent is running. Here are the active processes on the Debian VM, in case it helps:

![image](https://user-images.githubusercontent.com/5898424/128541023-a7c5e64a-bc08-43ab-8dc4-c1f8d955513c.png)

Here are the two log files from the same VM (changed to .txt to attach)
* [elastic-agent-json.log-20210805200420.txt](https://github.com/elastic/beats/files/6946875/elastic-agent-json.log-20210805200420.txt)
* [elastic-agent-json.log-20210805200416.txt](https://github.com/elastic/beats/files/6946877/elastic-agent-json.log-20210805200416.txt)

Version info from `GET /` for the cluster:
```
  "version" : {
    "number" : "7.14.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "dd5a0a2acaa2045ff9624f3729fc8a6f40835aa1",
    "build_date" : "2021-07-29T20:49:32.864135063Z",
    "build_snapshot" : false,
    "lucene_version" : "8.9.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  }
```

**Comment by melissaburpo** [comment]
After stopping/restarting both agents (with `sudo service elastic-agent stop` then `sudo service elastic-agent start`), live queries are now working again. But it seems like an agent restart shouldn't be required, unless there's some setup issue I'm missing.

In case it helps, here is the osquerybeat-json.log after the restart:
[osquery.log.txt](https://github.com/elastic/beats/files/6947328/osquery.log.txt)

**Comment by aleksmaus** [comment]
After leaving the agent to run for some time the linux box started to exhibit the problem mentioned above again.
 
Here are few observations for the record:

1. This problem affected only linux systems (one debian and one centos box). 
2. Both of the boxes in this case had the soft limit on file handles set to 1024.
3. There are quite a lot of "Error reading from connection: read tcp 10.128.0.123:33736->40.65.235.20:443: use of closed network connection" errors in the logs as well. Not sure if this is an actual issue.

I played with increasing the soft limit on the centos box and the osquerybeat kept running over few days fine. 
On the debian box with the default soft limit the problem started to happen again.

On the centos box the number of open handles since boot:
```
cat /proc/sys/fs/file-nr
1696	0	376869
```

current number of open files handles on all agent processes is 142:
```
$ sudo lsof -c elastic-agent -c osquery -c filebeat -c metricbeat | grep -P "^(\w+\s+){3}\d+\D+" | wc -l
142
```

Beats had one of the leaks fixed in the libbeat on 7.14 branch
https://github.com/elastic/beats/commit/5ce7faed89a0b50d1cf45a9483aca6af709bf40c

The osquerybeat build that is running on these boxes version/commit info:
```
$ sudo /opt/Elastic/Agent/data/elastic-agent-e127fc/install/osquerybeat-7.14.0-linux-x86_64/osquerybeat version
osquerybeat version 7.14.0 (amd64), libbeat 7.14.0 [e127fc31fc6c00fdf8649808f9421d8f8c28b5db built 2021-07-29 20:46:54 +0000 UTC]
```
Which is two commits after the libebeat leak fix and should have been included.


One more thing to note the scheduled queries from debian box kept posting the results over the weekend fine. Which points that the communication between osqueryd and the logger extension implemented in the osquerybeat still works.

**Comment by aleksmaus** [comment]
One thing we could probably improve is to open the client connection that communicates with osqueryd (to execute ad-hoc queries) only when we need to execute the query. Currently it is open when the beat is started and is held until the beat shuts down. 
This part of the code was rewritten quite a bit for 7.15, so that would be two different changes: one for 7.14 and another for 7.15 and after.

**Comment by directionless** [comment]
One possible cause of that kind of `i/o timeout` is around multiple clients accessing the same thrift socket. Osquery is single threaded, and I don't think the SDKs have mutexes there. So if your callers hammer on it, you'll see all kinds of weird errors bubble up from thrift. 

On the go SDK, I recently filed https://github.com/osquery/osquery-go/issues/98 and will likely patch that this week,
