### ISSUE TITLE
Metricbeat kubernetes will throw an error unless `nodes` defined in the ClusterRole as of 7.11

### ISSUE THREAD

**Issue by maggieghamry** [elastic/beats#25290]
For confirmed bugs, please report:
- Version: 7.11.0
- Operating System: Kubernetes v1.20.2+k3s1  on Ubuntu 20.04
- Steps to Reproduce: 

Running `ECK 1.4`. From version From version `7.11+` for Metricbeat - fixed in Filebeat with https://github.com/elastic/beats/issues/24051 and PR https://github.com/elastic/beats/pull/24052 (this may be the case for additional beats as well) on ECK, the following error is shown:
```
Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:supriya:metricbeat" cannot list resource "nodes" in API group "" at the cluster scope
```
Deploy Metricbeat from the latest manifest in the docs:
https://www.elastic.co/guide/en/beats/metricbeat/7.11/running-on-kubernetes.html
curl -L -O https://raw.githubusercontent.com/elastic/beats/7.11/deploy/kubernetes/metricbeat-kubernetes.yaml

Use the autodiscover config by doing the following:
    # To enable hints based autodiscover, remove `metricbeat.inputs` configuration and uncomment this:

Metricbeat starts up and is unable to list nodes:
>E0215 03:45:32.109053       7 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.4/tools/cache/reflector.go:156: Failed to watch *v1.Node: failed to list *v1.Node: nodes "k3s-01a.spahr.dev" is forbidden: User "system:serviceaccount:bourbontracker:metricbeat" cannot list resource "nodes" in API group "" at the cluster scope
>E0215 03:45:33.243209       7 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.4/tools/cache/reflector.go:156: Failed to watch *v1.Node: failed to list *v1.Node: nodes "k3s-01a.spahr.dev" is forbidden: User "system:serviceaccount:bourbontracker:metricbeat" cannot list resource "nodes" in API group "" at the cluster scope

This error goes away after adding `nodes` to the ClusterRole.

``` diff
diff --git a/deploy/kubernetes/metricbeat-kubernetes.yaml b/deploy/kubernetes/metricbeat-kubernetes.yaml
index 6c98c85f3..85e971762 100644
--- a/deploy/kubernetes/metricbeat-kubernetes.yaml
+++ b/deploy/kubernetes/metricbeat-kubernetes.yaml
@@ -151,6 +151,7 @@ rules:
   resources:
   - namespaces
   - pods
+  - nodes
   verbs:
   - get
   - watch
```

**Comment by ChrsMark** [comment]
Hi @maggieghamry thanks for reporting this, can you please point to a GH line or something more specific for the file where you add the line? In 7.11 it seems to be there https://github.com/elastic/beats/blob/7.11/deploy/kubernetes/metricbeat-kubernetes.yaml#L241 🤔 .

**Comment by maggieghamry** [comment]
@ChrsMark thanks for taking a look at this - it may be defined somewhere differently for ECK? However, it appears that from 7.11 and up, Filebeat, Metricbeat, and Heartbeat all need the `ClusterRole` configured to use `nodes`.

It also appears that for Metricbeat, the nodes privilege was added 3 years back and we were not using it, and that Filebeat did not have the nodes privilege, which was a bug and fixed in 7.11.

It seems the issue is that for users up till 7.10 could use a `ClusterRoles` definition without the `nodes` privilege, but now requires it from 7.11+

The definition was there for metricbeat and heartbeat as well. Everything was working till 7.10 and stopped working as of 7.11

After addition of nodes privilege it started working as before.

This is the `metricbeat_clusterrole.yml` that used to work (up till 7.10) - to fix, it requires adding the `-nodes` under `resources`:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
```

Question:
- Do you know why as of 7.11 we need to add - nodes privilege for the metricbeat clusterrole (metricbeat serviceaccount has this role assigned); only namespaces and pods privilege used to work till 7.10 it seems
- Was there some access related bug introduced in new version (7.11+) ?
-  Is there any other solution/workaround other than providing nodes privilege?

**Comment by ChrsMark** [comment]
Hi!

The reason for the need to add the node resource in clusterRole is because in autodiscovery we automatically enrich the events for pods with node's and namespace's metadata. 

There is no bug in there I think.

You can always disable this functionality by setting `enabled: false` in `add_resource_metadata` (see https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover.html):

```
add_resource_metadata:
  node:
    enabled: false      
```

**Comment by maggieghamry** [comment]
@ChrsMark thank you. I think the reason we thought there was an issue is because everything worked until 7.11, where this now seems to be enforced. Perhaps it's as simple as adding documentation or something in the change logs from 7.10 - 7.11?

**Comment by ChrsMark** [comment]
@maggieghamry I see the point of this making some confusion however we keep up to date  the https://github.com/elastic/beats/blob/7.11/deploy/kubernetes/metricbeat-kubernetes.yaml manifests so as to be the point of reference. Our official documentation on [how to run X-Beats on k8s](https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-kubernetes.html) refers to these manifests too. It works like `New Metricbeat version` -> `New manifests to work with new version`, so I would expect that if someone try to update to a newer product's version should also check the recommended way to do it on k8s and not to expect to just work as is, even if in most cases old manifests are compatible too.

**Comment by maggieghamry** [comment]
Thanks so much @ChrsMark !
