### ISSUE TITLE
Run kubernetes autodiscover E2E tests in CI

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#25307]
Changes in the main kubernetes-related packages should trigger autodiscover E2E tests in CI. These tests were added in https://github.com/elastic/e2e-testing/pull/1064

Main packages related to this feature are:
```
./libbeat/autodiscover
./metricbeat/autodiscover
./heartbeat/autodiscover
./filebeat/autodiscover
./x-pack/libbeat/autodiscover
./libbeat/common/kubernetes
```

More generally this would be:
```
./*/autodiscover
./x-pack/*/autodiscover
./libbeat/common/kubernetes
```

For agent we should also add the `kubernetes` provider, but there are no E2E test cases yet (https://github.com/elastic/e2e-testing/issues/1090).
```
./x-pack/elastic-agent/pkg/composable/providers/kubernetes
```

**Comment by faec** [comment]
Looks like this was already completed in the linked issues and PRs a few days later :-)
