### ISSUE TITLE
[Elastic Agent][question] How to trigger Unhealthy status for testing?

### ISSUE THREAD

**Issue by manishgupta-qasource** [elastic/beats#25321]
As per below comment
https://github.com/elastic/kibana/issues/84962#issuecomment-742524042

We need to make Agent into Unhealthy state to test the filters. Can a team member advise on the easiest way to trigger an Unhealthy state on an agent?

**Comment by ph** [comment]
@urso What do you think should be the experience here? should we allow some kind of debug tool?

**Comment by ph** [comment]
@michalpristas or @blakerouse Any tips for them?

**Comment by blakerouse** [comment]
I don't really have a way to do it in Elastic Agent. Could possible come up with a API call that would allow you to manipulate the `.fleet-agents` index to make it show up that way, for a short period of time.

**Comment by jen-huang** [comment]
@blakerouse Good point idea, I hadn't considered that.

@manishgupta-qasource / @muskangulati-qasource You can run the following query in `Dev Tools` to force an agent into `Unhealthy` status. Replace `d0415977-c688-44c7-abe0-065887ddc52b` with the agent ID you want to update:

```
POST .fleet-agents/_update/d0415977-c688-44c7-abe0-065887ddc52b
{
  "doc": {
    "last_checkin": "2021-05-03T22:06:20Z",
    "last_checkin_status": "error"
  }
}
```

Forcing it like this will probably trigger other unintended effects, so please use this for UI testing only 😉

**Comment by muskangulati-qasource** [comment]
Hi @jen-huang,

Thank you for providing the steps for the same. Our query is now resolved and we were successful in updating the agent status from healthy to Unhealthy & back to healthy!!

Please find below the whole testing details.

**Build Details**:
```
Version: 7.13.0-SNAPSHOT
Commit: 62a98b97048b3639b8dfe7884776d95581dc1eb5
Build number: 40746
```

**Refer Screenshots**:
- Healthy Status:
![Healthy](https://user-images.githubusercontent.com/60252716/116971786-b33d0980-acd7-11eb-9ac9-cd497047f4f1.JPG)

- API hit to change agent status from Healthy to Unhealthy:
![API](https://user-images.githubusercontent.com/60252716/116972016-10d15600-acd8-11eb-94c6-7b5f209038f8.JPG)

- Unhealthy status:
![Error](https://user-images.githubusercontent.com/60252716/116972066-1f1f7200-acd8-11eb-8449-b4686c98492d.JPG)

- API hit to change agent status from Unhealthy to Healthy:
![API2](https://user-images.githubusercontent.com/60252716/116972127-31011500-acd8-11eb-83a9-2a5441674101.JPG)

Hence, we closing this ticket. 

Thanks!!
