### ISSUE TITLE
Upgrade to Golang 1.16.4

### ISSUE THREAD

**Issue by ph** [elastic/beats#25346]
Upgrade to Golang 1.16.2:

 - [x] Update crossbuild images https://github.com/elastic/golang-crossbuild/pull/82
 - [x] Update Beats to 1.16.2
 - [x] Update Fleet-Server
 - [x] Ping APM-Server
 - [x] Update macOS SDK in our crossbuild

**Comment by kvch** [comment]
My test branch: https://github.com/elastic/beats/pull/24251

**Comment by michel-laterman** [comment]
@simitt, The golang-crossbuild images have been update to provide 1.16.4.
For MacOSX the `golang-crossbuild:1.16.4-darwin-debian10` image provides the OSX 10.14 SDK (and artifacts will only run on 10.14+); the beats use this image to cross compile as there are issues building the beats when using go 1.16 with the earlier (10.11) SDK

**Comment by simitt** [comment]
Thanks for the ping @michel-laterman. So dropping support for `OSX <10.14` is not considered a breaking change (it is done in a minor version upgrade)? 
Referring to the current [support matrix](https://www.elastic.co/support/matrix#matrix_os).
