### ISSUE TITLE
elastic-agent: HEALTHY status fluctuates for fleet-server

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#25341]
Spotted in https://github.com/elastic/integrations/pull/950

We tried to use `elastic-agent status` as healthcheck for the fleet server, but apparently the stack initialization fails due to unstable HEALTHY status (suspected by @blakerouse ).

We would like to use the  `status` command instead of `/api/status`, but this issue seems to be a blocker.

**Comment by blakerouse** [comment]
@ph I think we should move this to 7.14. Being that it will take some investigating on the best way to fix this issue and it's not critical for the 7.13 release.

**Comment by ph** [comment]
Added to 7.14 and to the meta issue.

**Comment by urso** [comment]
@ph @blakerouse Do we have an update for this issue?

**Comment by ph** [comment]
Could this be similar to issue described in https://github.com/elastic/beats/issues/25940  ?

**Comment by blakerouse** [comment]
I don't have an update for this issue. We need to determine how we want to improve the status command.

An approach to providing stability to this command would be to add debouce to healthy reporting. Basically requiring that healthy be reported for an X amount of time before actually saying internally that Elastic Agent is healthy.

**Comment by ruflin** [comment]
If I remember correctly, one issue in the past was that Elastic Agent was healthy but then goes to unhealthy state again when updating the policy. If this is the case, I'm not sure this is expected as the Elastic Agent itself is still healthy. Something similar was the case during the fleet-server self enrollment. What is our expected behaviour if the health status of the Elastic Agent if a subprocess is not healthy?

**Comment by EricDavisX** [comment]
@mtojek do you have an easy way to reproduce this... maybe re-doing the change as you originally tried?  or @blakerouse do you need that at this point?

**Comment by mtojek** [comment]
I think there is nothing special to reproduce. It's just interpretation of the behavior that Blake described above.

**Comment by EricDavisX** [comment]
I'm doing follow-ups on open issue for 7.14 - is this still under review / possible merge for 7.14?  If we aren't attempting it, then please update the label to 7.15 or beyond and put it to backlog from 'iteration' as well.  Thank you.  @blakerouse
