### ISSUE TITLE
Elastic Agent should allow a namespace to be configured

### ISSUE THREAD

**Issue by ph** [elastic/beats#25350]
As a user I should be able to select to which namespace internal monitoring and log collection should be send.

```diff
agent:
  monitoring:
    enabled: true
+   namespace: test_1
    use_output: default
    logs: true
    metrics: true
```

based on the bug reporting from https://github.com/elastic/beats/issues/23020

**Comment by ph** [comment]
@jen-huang Looking at this, I don't think it's a lot of effort on our side to add this behavior.

 Buts I think there is a bit more on your side that we may have missed:

- How a user can configure a namespace, what is the UX experience?
- The `permissions block` in the agent policy need to also contains the metrics and logs destination so fleet server can create them. 


I think we should keep the  logic simple on the fleet-server and fleet should dictate what are all the permission an elastic agent needs.

**Comment by jen-huang** [comment]
> How a user can configure a namespace, what is the UX experience?

This one is easy, we already have this UI here that collects `namespace` on agent policy level. We just need to populate the `agent.monitoring` block to include the new `namespace` field.

![image](https://user-images.githubusercontent.com/1965714/116296009-90967800-a74e-11eb-9254-40035decc91f.png)

> The permissions block in the agent policy need to also contains the metrics and logs destination so fleet server can create them.

Can you expand on this a bit? Currently the agent policy yaml contains these permissions for `metrics-*` and `logs-*`, isn't this sufficient?

![image](https://user-images.githubusercontent.com/1965714/116296248-d6ebd700-a74e-11eb-90e5-9335613f92b4.png)

**Comment by ph** [comment]
> Can you expand on this a bit? Currently the agent policy yaml contains these permissions for metrics-* and logs-*, isn't this sufficient?

This is currently enough, but as soon as the permission block _target non wildcard indices_ they would need to include the data stream for the logs and metric collection. We could potentially land this in 7.14.

**Comment by jen-huang** [comment]
> as soon as the permission block target non wildcard indices they would need to include the data stream for the logs and metric collection

Understood, but we don't have this yet so I don't want to conflate the issue 🙂  I created https://github.com/elastic/kibana/issues/98542 for the Fleet part of the work.
