### ISSUE TITLE
[Elastic Agent] Agent policy change log doesn't track new policy id

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#25355]
[Ingest Manager] Agent config changes don't have the actual config being changed to in the log
 - I don't know how else to get it and this would make it a traceability / auditing problem, at least for Endpoint users if not others

do we also need to put the user who has done the change in the log as well?  I think that's a common request

**Kibana version:**
7.9.0 BC3 deployed to cloud with BC3 Agent installed to win 7 x64 host 

**Browser version:**
chrome latest on macos

**Describe the bug:**
when changing a config in Ingest Manager I see logging about the config change, but not the details I'd need to see if I was truly concerned with audit-logging and tracing who had done what. 

<img width="1039" alt="config-change" src="https://user-images.githubusercontent.com/12970373/88311863-6c999800-ccdf-11ea-9862-077273f6ce71.png">

**Comment by jen-huang** [comment]
@ph I'm moved this to Agent backlog:

- We should check to see if the policy change even logged by agent contains the agent policy ID it was reassigned to. If not, can we do work to include it?
- The audit logging aspect of this would be on the Kibana side, but audit logging is not on the near horizon.
