### ISSUE TITLE
[Metricbeat] Configuration parameter for docker.container

### ISSUE THREAD

**Issue by nikulinivan** [elastic/beats#25361]
**Describe the enhancement:**
Metricbeat currently only lists running containers.
It will be nice to have configuration parameter for `docker.container` that will pass `All: true` for `types.ContainerListOptions{}`

**Describe a specific use case for the enhancement or feature:**
We have a use case where we need to monitor list of containers including stalled(during creation), exited etc...

**Comment by matschaffer** [comment]
@elastic/integrations-services any updates on this issue?
