### ISSUE TITLE
[elastic-agent] failed to invoke rollback waterfork

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#25371]
* Environment: docker
* Version: 7.13.0-SNAPSHOT

The following error is shown in the logs:

```
ERROR	cmd/run.go:129	failed to invoke rollback watcherfork/exec /usr/share/elastic-agent/data/elastic-agent: no such file or directory
```

The above is running inside a container. It does not break the setup but would be good to investigate the issue. Two thoughts:

* It might be related to STATE_PATH inside Docker
* Upgrades are not allowed in Docker, maybe that is the issue?

**Comment by michalpristas** [comment]
in case of upgrade not being upgradable we exit fail fast with no error. no fork should be performed. looking
