### ISSUE TITLE
Sync up logger used in Fleet server with Agent/ Beats

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#25391]
The Fleet Server component is known to use a different logging construct.  We find that in doing so it doesn't allow for easy debugging of Fleet Server / Agent because the logs will show different timestamps.

here is an example from the fleet server log:
"@timestamp":"2021-04-26T17:59:49.824Z"
/opt/Elastic/Agent/data/elastic-agent-9c3fe9/logs/default/fleet-server-json.log

and here is one from the Agent log:
"@timestamp":"2021-04-26T15:21:38.184-0400"
/opt/Elastic/Agent/data/elastic-agent-9c3fe9/logs/elastic-agent-json.log

Note that the formatting is different, besides the fact that events that seemed to happen near the same time frame were cited a being minutes apart, making the non-interleaved files much harder to match up, causing false alarms in some cases with reasonable assumptions made based on the logging information.

**Comment by ph** [comment]
@michalpristas This look like a good issue to pair with @michel-laterman?

**Comment by scunningham** [comment]
The beats should log in rfc-3339 zulu. It is a smaller format and more concise.

**Comment by michalpristas** [comment]
@urso can this change on beats level be considered breaking?

**Comment by ruflin** [comment]
For Beats itself I would consider this a breaking change. If the log format changes, from a log collector perspective things break.

Bug if Beats logs differently when run by Elastic Agent it is a breaking change but one we could still do as we are in beta. So maybe we should adjust it when run by Elastic Agent?

**Comment by urso** [comment]
Most important is that filebeat can pick up json logs and parse the timestamps correctly. In the past the RFC-3339 Zulu was the only supported format.

@michalpristas  Updated the timestamp parser. It should be able to parse both formats, right?

> Bug if Beats logs differently when run by Elastic Agent it is a breaking change but one we could still do as we are in beta. So maybe we should adjust it when run by Elastic Agent?

Not sure how straight forward this is. +1 if its easy to change the timestamp format in our logger.
When Filebeat collects JSON logs it parses the timestamp into a `time.Time`. When shipping those logs to ES, all logs will use the same format.

@michalpristas Is the updated timestamp parser aware of timezones?

**Comment by ph** [comment]
I've reassigned it to 7.14, its a bug but I think it's not required for 7.13.

**Comment by michalpristas** [comment]
updated timestamp praser recognizes two formats :
- `2006-01-02T15:04:05Z07:00`
- `2006-01-02T15:04:05.000Z0700`
 
when log timestamp contains information about timezone, this information is not lost.
timezone info is lost with format `fleet-server` uses but they have a workaround in a form of transforming time to UTC before printing it.
https://play.golang.org/p/LY7R9rG2Y2V

**Comment by urso** [comment]
> when log timestamp contains information about timezone, this information is not lost.
timezone info is lost with format fleet-server uses but they have a workaround in a form of transforming time to UTC before printing it.

In other words, logs indexed in Elasticsearch will all be correctly indexed with the same timestamp and timezeone (Beats also converts timestamps to UTC before indexing) and there will be no offset between Log events from Agent, Beats, and Fleet Server in Elasticsearch.

@EricDavisX As Agent is supposed to ship logs to ES, we rather might want to check the logs in Elasticsearch and not on disk for now. Minor formatting differences on disk should be no problem (and we can fix those later). But when shipping Logs, they get parsed and processed by Filebeat before shipping to ES (which might introduce other errors). In ES (Logs UI):
- are logs with corresponding times close to each other (no time offsets)
- Is the log format consistent (e.g. `msg` vs `message`?)
- Are ECS fields added?


> besides the fact that events that seemed to happen near the same time frame were cited a being minutes apart

I guess we got too focused on formatting here. After timestamps have been normalized, are there still big gaps between corresponding events in Agent and Fleet-Server. If so, let's file a separate issue, if you think the offsets are too big.

**Comment by EricDavisX** [comment]
will do, thanks for the good discussion here.

**Comment by ph** [comment]
We shouldn't change beats but we could change Fleet Server format.
