### ISSUE TITLE
Fleet: error: could not decode the response

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#25405]
The goal of the issue to root cause problems with Elastic Agent/Fleet/Kibana with latest snapshots. The stack boots up correctly, then a new policy should be reassigned to the agent, but it seems that it never happens.

Artifacts/logs: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package/detail/PR-319/1/artifacts

```
[36mfleet-server_1               |[0m 2021-04-12T08:52:08.659Z	ERROR	fleet/fleet_gateway.go:203	Could not communicate with Checking API will retry, error: could not decode the response, raw response: 
[36mfleet-server_1               |[0m 
[36mfleet-server_1               |[0m 2021-04-12T08:53:42.756Z	ERROR	fleet/fleet_gateway.go:203	Could not communicate with Checking API will retry, error: could not decode the response, raw response: 
[36mfleet-server_1               |[0m 
[36mfleet-server_1               |[0m 2021-04-12T08:56:45.556Z	ERROR	fleet/fleet_gateway.go:203	Could not communicate with Checking API will retry, error: could not decode the response, raw response: 
[36mfleet-server_1               |[0m 
```

We deployed an emergency fix to use last known stable revisions. Here is the PR reverting this change: https://github.com/elastic/elastic-package/pull/319 . This one is expected to be back to green.

It impacts elastic/integrations for ~5 days now.

**Comment by jen-huang** [comment]
I went ahead and moved this and put it in the agent Iteration board :)

**Comment by ph** [comment]
This is indeed an agent  @elastic/agent Anyone could take a look at this one?

**Comment by faec** [comment]
Confirmed that this is no longer happening in local snapshots or nightly builds. Closing, though we can reopen if this is spotted again independent of #25341.
