### ISSUE TITLE
`docker-fleet-agent` container does not appear to be containerized

### ISSUE THREAD

**Issue by kvch** [elastic/beats#25426]
I cleaned up my environment with `docker system prune -a` and then I started a fresh install of the stack with the following command:

```
./elastic-package stack up --version=7.13.0-SNAPSHOT -v
```

When I played around on the UI I noticed that one of the containers `docker-fleet-agent` is not reported as containerized.

![notcontainer](https://user-images.githubusercontent.com/3876218/116551964-c9725080-a8f8-11eb-89df-e2d4577fafe5.jpg)

**Comment by jlind23** [comment]
@jen-huang is this still something relevant on your end?

**Comment by jen-huang** [comment]
@jlind23 This looks like a potential bug for Infrastructure Monitoring UI team as it's in the Metrics UI and not Fleet.
