### ISSUE TITLE
Elastic-Agent cannot enroll to Cloud QA Fleet Server

### ISSUE THREAD

**Issue by simitt** [elastic/beats#25430]
Creating a `7.13` deployment on cloud QA, a local Elastic Agent cannot be enrolled. It keeps logging that it is waiting for the remote server to be ready:
```
docker run --name elastic-agent-local -it \
  --env FLEET_ENROLL=1 \
  --env FLEET_INSECURE=1 \
  --env FLEET_URL=https://8bb062aed7124135927141c19756d584.fleet.us-central1.gcp.qa.cld.elstc.co \
  --env FLEET_ENROLLMENT_TOKEN=d0pkcEhIa0JYbEh5SkJQdG9sdzQ6VHBDNXRqbE5Rdk82UHNDeUtrMFhLdw== \
  --rm docker.elastic.co/beats/elastic-agent:7.13.0-SNAPSHOT
Policy selected for enrollment:
The Elastic Agent is currently in BETA and should not be used in production

2021-04-29T14:16:26.555Z	WARN	[tls]	tlscommon/tls_config.go:98	SSL/TLS verifications disabled.
2021-04-29T14:16:58.461Z	WARN	cmd/enroll_cmd.go:348	Remote server is not ready to accept connections, will retry in a moment.
2021-04-29T14:17:58.464Z	INFO	cmd/enroll_cmd.go:355	Retrying to enroll...
2021-04-29T14:18:30.624Z	WARN	cmd/enroll_cmd.go:348	Remote server is not ready to accept connections, will retry in a moment.
2021-04-29T14:20:30.628Z	INFO	cmd/enroll_cmd.go:355	Retrying to enroll...
2021-04-29T14:21:02.693Z	WARN	cmd/enroll_cmd.go:348	Remote server is not ready to accept connections, will retry in a moment.
```

I tried with both Fleet-Server URLS - the one specified in the Kibana Fleet UI, and the one shown in the Cloud UI - none of them worked for the enrollment; both of them return a valid Fleet Server status. 

The cloud deployment shows an healthy Elastic Agent enrolled to the Cloud Policy. 

Update:
The Elastic Agent goes offline after a couple of minutes. 
The cloud logs show:
```
Could not communicate with Checking API will retry, error: fail to checkin to fleet: Post "https://56d164b211dc:8220/api/fleet/agents/c0b24bea-b2fa-405a-856d-35e8cfee76f2/checkin?": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
Seeing these logs was reported already in https://github.com/elastic/beats/issues/25122, where the suggestion was that this is just a logging issue, so not sure if this is related.

**Comment by ruflin** [comment]
Can you try to set the url to https://8bb062aed7124135927141c19756d584.fleet.us-central1.gcp.qa.cld.elstc.co:9243 and also in the UI settings?

**Comment by simitt** [comment]
Yes this worked, I didn't make the connection that this is related to the default port missing (https://github.com/elastic/beats/issues/25420). Closing this as duplicate.
