### ISSUE TITLE
[libbeat?, filebeat] Kafka Input: Add support for SASL authentication 

### ISSUE THREAD

**Issue by benqua** [elastic/beats#25458]
**Describe the enhancement:**
Kafka input doesn't support SASL, while the support has been added to the kafka output (see https://github.com/elastic/beats/issues/8387 ) .
It would be great to have SASL support in Kafka (filebeat) input.
For example the kafka service from AWS, AWS MSK, only support SSL auth or SASL/SCRAM-SHA512. Supporting this scheme would make it possible to read from AWS MSK with filebeat.
 
**Describe a specific use case for the enhancement or feature:**
We use filebeat to collect EKS logs, send them to MSK, read them back with filebeat to finally index them in the Elastic Cloud service.

**Comment by benqua** [comment]
Any plan to support sasl kafka input?

**Comment by pchheda-lyft** [comment]
We need this as well. Any plan to support this?

**Comment by benqua** [comment]
Somehow related to https://github.com/elastic/beats/issues/26294. 
Any reaction from the maintainers of the project?

By the way, the fact that kafka input and output don't support the same set of feature is quite confusing.

**Comment by benqua** [comment]
Hi beat team, any plan to support sasl for kafka input?
