### ISSUE TITLE
Update docs to point out which logFormat the IIS filebeat module supports

### ISSUE THREAD

**Issue by jakommo** [elastic/beats#25456]
**Describe the enhancement:**
I was talking to a user who was interested in understanding why IIS `logFormat` the module would support. 
The default is `W3C` and looking at the grok patterns [used in the pipeline](https://github.com/elastic/beats/blob/v7.12.1/filebeat/module/iis/error/ingest/pipeline.yml) I think this is the only one the module does support currently. 

Looking at https://docs.microsoft.com/en-us/iis/configuration/system.applicationhost/sites/sitedefaults/logfile/#configuration, it also supports other types like `IIS`, `NSCA` and custom. 

Not sure if we are planing to add those formats (except for custom), but we should at least point out in the module docs that we currently only support the default W3C format.

**Comment by legoguy1000** [comment]
If someone provides logs in the other formats, it would be easy to update the pipeline to support those as well.
