### ISSUE TITLE
[Filebeat] Sonicwall Module don't show all ecs fields 

### ISSUE THREAD

**Issue by AlcebiadesFilho** [elastic/beats#25469]
Hi guys im using filebeat 7.9.0 and im activeted sonicwall module to analyse my sonicwall firewalls but i cant find older fields like user, portal ... where i activeded the options to show this fields?

in the print i show my manifest.yml 
![manifest](https://user-images.githubusercontent.com/78539159/116725879-eec69380-a9b8-11eb-8083-345f484b00d7.jpg)

Anyway, Thanks !!

**Comment by legoguy1000** [comment]
It sounds like you just have questions about how to use the module.  General questions should be posted on https://discuss.elastic.co/. What do you mean show older fields? The file you're showing is a file of the actual module itself, not the config to enable/disable it for use.  that is located in `module.d/sonicwall.yml`

**Comment by AlcebiadesFilho** [comment]
others * sorry i wrote it wrong.

There is no data from the ECS field in the kibana for example, it doesn’t have the user’s name, ip ... I was able to enable the rsa field and I thought it could be some configuration to activate the ECS field 
![github](https://user-images.githubusercontent.com/78539159/116868006-63314a80-abe4-11eb-9558-2ecc77502e83.png)

the pint shows the field

**Comment by legoguy1000** [comment]
can you post 1-2 of the documents from ES to show what's missing? How are you sending the data to Filebeat, log file or syslog??

**Comment by AlcebiadesFilho** [comment]
![github4](https://user-images.githubusercontent.com/78539159/116875052-a8f41000-abf0-11eb-8865-409e47483fa8.png)
![github3](https://user-images.githubusercontent.com/78539159/116875054-a98ca680-abf0-11eb-854e-7119298255bd.png)
![github2](https://user-images.githubusercontent.com/78539159/116875057-aa253d00-abf0-11eb-9386-b460ea316e7b.png)

Follow the screenshots of the fields that are available, notice that "ecs" only has "version"

I use sonicwall syslogs fields, i'm making a sonicwall log analyzer in the msg field has an example of the log

**Comment by legoguy1000** [comment]
That is the only ECS field, see https://www.elastic.co/guide/en/ecs/current/ecs-ecs.html

**Comment by AlcebiadesFilho** [comment]
I am expressing myself badly .. I wanted the fields that I saw in the source code, because I need all these fields, see the photo below. These fields appeared when I didn’t use the sonicwall module. I just want these fields to be able to use my logstash correctly 

![image](https://user-images.githubusercontent.com/78539159/116877933-fecab700-abf4-11eb-9c96-630895106966.png)

**Comment by legoguy1000** [comment]
Those are the raw fields from the logs, they will be transformed to the appropriate ECS fields if they exist. The whole point of the module is to parse the vendor specific logs into "generic" ECS fields so once they are parsed, the vendor specific fields are removed since it would be redundant.  For example, `srcMac` would be renamed into `source.mac` and `srcMac` would not longer exist in the document.

**Comment by AlcebiadesFilho** [comment]
Thanks this link help me a lot.

https://github.com/elastic/beats/blob/61a34aec762a6083db87aae1a0c4f14be253d104/x-pack/filebeat/module/sonicwall/firewall/test/generated.log-expected.json

After you said that you had changed the names, I went back and found the link above and one more thing do you know why my user field and others are blank in kibana? 

![image](https://user-images.githubusercontent.com/78539159/116913435-d906d780-ac1f-11eb-8096-550626b0a089.png)

**Comment by legoguy1000** [comment]
how are u generating `user.name.name`?? thats not a proper field/

**Comment by AlcebiadesFilho** [comment]
I created this field by copying the rsa.raw.username field. 

Another thing is that I have 154 fields but only 40 are active, do you know how I could find out why they are empty? because in the original msg they are there 

![image](https://user-images.githubusercontent.com/78539159/116921522-7961f980-ac2a-11eb-9dc1-9174334b6d76.png)

Available fields

rsa.internal.messageid
rsa.misc.action
rsa.raw._facility
rsa.raw._pri
rsa.raw._severity
rsa.raw.hcategory
rsa.raw.header_id
rsa.raw.hfld1
rsa.raw.hfld20
rsa.raw.hseverit
_id
_index
_score
_type
@timestamp
@version
ecs.version
input.type
log.flags
log.original
log.source.address
log.syslog.facility.code
log.syslog.priority
log.syslog.severity.code
log.syslog.severity.name
message
observer.product
observer.serial_number
observer.type
observer.vendor
rsa.internal.event_desc
rsa.internal.msg
rsa.raw.event_description
rsa.raw.event_time
rsa.raw.fld2
rsa.raw.hdate
rsa.raw.htime
rsa.raw.msg
rsa.raw.p0
rsa.time.event_time
service.type
sonicwall.action
sonicwall.event.id
tags

Thank you very much for the replies

**Comment by legoguy1000** [comment]
What does your config look like for the module? I'm still somewhat confused as to the actual issue?

**Comment by AlcebiadesFilho** [comment]
![github8](https://user-images.githubusercontent.com/78539159/116927551-31df6b80-ac32-11eb-9176-60b53ed9f508.png)
![github7](https://user-images.githubusercontent.com/78539159/116927556-32780200-ac32-11eb-97d8-b1d1c26007aa.png)
![image](https://user-images.githubusercontent.com/78539159/116927651-51769400-ac32-11eb-9624-9e7e3f87c27e.png)



Just out of curiosity here is the logtsash configuration that I used when I took the filebeat data without the sonicwall module but by the udp mode

`filter {
  # Preserve original raw message.
  mutate {
    copy => { "message" => "[log][original]" }
  }

  # Extract key-value pairs into fields.
  kv {
    exclude_keys => [ "n", "vp_time" ]
  }

#natSrc
#natDst
  # Map Sonicwall field names to ECS.
  mutate {
    rename => { "app" => "[sonciwall][application][id]" }
    rename => { "arg" => "[url][path]" }
    rename => { "Category" => "[sonciwall][cfs][category]" }
    rename => { "c" => "[sonciwall][category][id]" }
    rename => { "code" => "[sonciwall][cfs][code]" }
    rename => { "dstMac" => "[destination][mac]" }
    rename => { "dstV6" => "[destination][ip]" }
    rename => { "dstname" => "[url][domain]" }
    rename => { "fw" => "[host][ip]" }
    rename => { "fw_action" => "[sonicwall][action]" }
    rename => { "icmpCode" => "[icmp][request][type]" }
    rename => { "id" => "[host][type]" }
    rename => { "m" => "[sonicwall][event][id]" }
    rename => { "note" => "[sonicwall][event][note]" }
    rename => { "msg" => "message" }
    rename => { "nxClientIPAddress" => "[client][ip]" }
    rename => { "op" => "[sonicwall][http][code]" }
    rename => { "packetousIn" => "[srce][packets]" }
    rename => { "packetsOut" => "[destination][packets]" }
    rename => { "packetsTotal" => "[network][packets]" }
    rename => { "portal" => "[sonicwall][portal]" }
    rename => { "pri" => "[log][syslog][severity][code]" }
    rename => { "proto" => "[network][protocol]" }
    rename => { "rcvd" => "[source][bytes]" }
    rename => { "rpkt" => "[source][packets]" }
    rename => { "rule" => "[sonicwall][rule][id]" }
    rename => { "sent" => "[destination][bytes]" }
    rename => { "sess" => "[sonicwall][session][type]" }
    rename => { "sn" => "[observer][serial_number]" }
    rename => { "spkt" => "[destination][packets]" }
    rename => { "srcMac" => "[source][mac]" }
    rename => { "srcV6" => "[source][ip]" }
    rename => { "vpnpolicy" => "[sonicwall][vpn][policy]" }
  }

  # Handle Sonicwall rule id.
  if [sonicwall][rule][id] {
    if [sonicwall][rule][id] !~ /^\d+$/ {
      mutate {
        rename => { "[sonicwall][rule][id]" => "[sonicwall][rule][name]" }
      }
    }
  }

  # Handle network protocol.
  if [network][protocol] {
    if "/" in [network][protocol] {
      mutate {
        split => { "[network][protocol]" => "/" }
        add_field => { "[network][transport]" => "%{[network][protocol][0]}" }
      }
      if [network][protocol][1] =~ /\D+/ {
        mutate {
          replace => { "[network][protocol]" => "%{[network][protocol][1]}" }
        }
      }
      else {
        mutate {
          remove_field => [ "[network][protocol]" ]
        }
      }
    }
  }

  # Handle event duration.
  if [cdur] {
    # Connection duration is logged in milliseconds. ECS expects nanoseconds.
    ruby {
      code => "event.set('[event][duration]', Integer(event.get('cdur')) * 1000000 )"
    }
  }
  else if [duration] {
    # VPN session (?) duration is logged in seconds. ECS expects nanoseconds.
    ruby {
      code => "event.set('[event][duration]', Integer(event.get('duration')) * 1000000000 )"
    }
  }

  # Convert agent field type from string to hash.
  if [agent] {
    mutate {
      add_field => { "agent" => "[@metadata][agent]" }
      remove_field => [ "agent" ]
    }
    mutate {
      rename => { "[@metadata][agent]" => "[agent][name]" }
    }
  }

  # Handle username.
  if [usr] and [usr] != "" {
    mutate {
      rename => { "usr" => "[user][name]" }
    }
  }
  if [user] and [user] != "" {
    mutate {
      rename => { "user" => "[user][name]" }
    }
  }
  translate {
    id => "filter-sonicwall-translate-http_code"
    regex => false
    field => "[sonicwall][http][code]"
    destination => "[http][request][method]"
    dictionary => {
      "0" => "other"
      "1" =>  "get"
      "2" =>  "post"
      "3" =>  "head"
    }
    remove_field => [ "[sonicwall][http][code]" ]
  }
  translate {
    id => "filter-sonicwall-translate-category_id"
    regex => false
    field => "[sonciwall][category][id]"
    destination => "[sonciwall][category][name]"
    dictionary => {
      "0" => ""
      "1" =>  "System Maintenance"
      "2" =>  "System Errors"
      "4" =>  "Blocked Web Sites"
      "8" =>  "Blocked Java Etc"
      "16" =>  "User Activity"
      "32" =>  "Attacks"
      "64" =>  "Dropped TCP"
      "128" =>  "Dropped UDP"
      "256" =>  "Dropped ICMP"
      "512" =>  "Network Debug"
      "1024" =>  "Syslog Only For Traffic Reporting"
      "2048" =>  "Dropped LAN TCP"
      "4096" =>  "Dropped LAN UDP"
      "8192" =>  "Dropped LAN ICMP"
      "32768" =>  "Modem Debug"
      "65536" =>  "VPN Tunnel Status"
      "131072" =>  "802.11 Management"
      "262144" =>  "Syslog Only For Traffic Reporting"
      "524288" =>  "System Environment"
      "1048576" =>  "Expanded VOIP Activity"
      "2097152" =>  "Expanded WLAN IDS Activity"
      "4194304" =>  "Expanded SonicPoint Activity"
    }
  }
  translate {
    id => "filter-sonicwall-translate-event_id"
    regex => false
    field => "[sonciwall][event][id]"
    destination => "[sonciwall][event][name]"
    dictionary => {
      "22" =>  "Ping of Death Blocked"
      "23" =>  "IP Spoof Detected"
      "25" =>  "Possible SYN Flood"
      "27" =>  "Land Attack"
      "81" =>  "Smurf Attack"
      "82" =>  "Port Scan Possible"
      "83" =>  "Port Scan Probable"
      "165" =>  "Allow Email Attachment"
      "177" =>  "TCP FIN Scan"
      "178" =>  "TCP Xmas Scan"
      "179" =>  "TCP Null Scan"
      "248" =>  "Email Attachment"
      "267" =>  "TCP Xmas Tree Attack"
      "428" =>  "Drop Source Route Packet"
      "437" =>  "Email Fragment Dropped"
      "446" =>  "FTP Passive Attack"
      "527" =>  "FTP Port Bounce Attack"
      "528" =>  "FTP Passive Bounce Attack"
      "546" =>  "Rogue AP Found"
      "548" =>  "WLAN Association Flood"
      "606" =>  "Spank Attack"
      "608" =>  "IPS Detection Alert"
      "609" =>  "IPS Prevention Alert"
      "615" =>  "WLAN Probe Check"
      "662" =>  "Non SonicPoint Traffic Drop"
      "789" =>  "IDP Detection Alert"
      "790" =>  "IDP Prevention Alert"
      "794" =>  "AntiSpyware Prevention Alert"
      "795" =>  "AntiSpyware Detection Alert"
      "856" =>  "SYN Flood Watch Mode"
      "857" =>  "SYN Flood Trigger Mode"
      "858" =>  "SYN Flood Proxy Mode"
      "859" =>  "SYN Flood Proxy Trigger Mode"
      "860" =>  "SYN Flood Detected"
      "861" =>  "SYN Flood Proxy Mode Cancel"
      "862" =>  "SYN Flood Blacklist On"
      "863" =>  "SYN Flood Blacklist Off"
      "864" =>  "SYN Flooding Machine Blacklisted"
      "865" =>  "Machine removed from SYN Flood Blacklist"
      "866" =>  "Possible SYN Flood Continues"
      "867" =>  "Possible SYN Flood Ceased"
      "868" =>  "SYN Flood Blacklist Continues"
      "869" =>  "TCP SYN Receive"
      "898" =>  "RST Flooding Machine Blacklisted"
      "899" =>  "RST Flood Blacklist Continues"
      "900" =>  "Machine Removed From RST Flood Blacklist"
      "901" =>  "FIN Flooding Machine Blacklisted"
      "902" =>  "FIN Flood Blacklist Continues"
      "903" =>  "Machine Removed From FIN Flood Blacklist"
      "904" =>  "Possible RST Flood"
      "905" =>  "Possible FIN Flood"
      "906" =>  "Possible RST Flood Ceased"
      "907" =>  "Possible FIN Flood Ceased"
      "908" =>  "Possible RST Flood Continues"
      "909" =>  "Possible FIN Flood Continues"
      "1098" =>  "DNS Rebind Attack Detected"
      "1099" =>  "DNS Rebind Attack Blocked"
      "1209" =>  "MAC IP Anti Spoof Check Enforced For Hosts"
      "1210" =>  "MAC IP Anti Spoof Cache Not Found For Router"
      "1211" =>  "MAC IP Anti Spoof Cache Not Router"
      "1212" =>  "MAC IP Anti Spoof Cache Blacklisted Device"
      "1213" =>  "UDP Flood Detected"
      "1214" =>  "ICMP Flood Detected"
      "1366" =>  "TCP Flooding Machine Blacklisted"
      "1367" =>  "TCP Flood Blacklist Continues"
      "1368" =>  "Machine Removed From TCP Flood Blacklist"
      "1369" =>  "Possible TCP Flood"
      "1370" =>  "Possible TCP Flood Ceased"
      "1371" =>  "Possible TCP Flood Continues"
      "1373" =>  "IPv6 fragment size is less than minimum"
      "1374" =>  "IP Reassembly : Incomplete IGMP fragment"
      "1375" =>  "UDP fragmented datagram is too big"
      "1376" =>  "Nestea/Teardr op Attack"
      "1387" =>  "TCP Null Flag Attack"
      "1450" =>  "UDPv6 Flood Detected"
      "1451" =>  "ICMPv6 Flood Detected"
      "1452" =>  "Half Open TCP Connection Threshold Exceeded"
    }
  }
  translate {
    id => "filter-sonicwall-translate-priority_id"
    regex => false
    field => "[log][syslog][severity][code]"
    destination => "[log][syslog][severity][name]"
    dictionary => {
      "0" =>  "Emergency"
      "1" =>  "Alert"
      "2" =>  "Critical"
      "3" =>  "Error"
      "4" =>  "Warning"
      "5" =>  "Notice"
      "6" =>  "Info"
      "7" =>  "Debug"
    }
  }

  # Create network bytes field as a sum of rcvd and sent if bytesTotal doesnt exist.
  if ![bytesTotal] {
    if [source][bytes] and [destination][bytes] {
      ruby {
        code => "event.set('[network][bytes]', Integer(event.get('[source][bytes]')) + Integer(event.get('[destination][bytes]')))"
      }
    }
    else if [source][bytes] {
      ruby {
        code => "event.set('[network][bytes]', Integer(event.get('[source][bytes]')))"
      }
    }
    else if [destination][bytes] {
      ruby {
        code => "event.set('[network][bytes]', Integer(event.get('[destination][bytes]')))"
      }
    }
  }
  else {
    mutate {
      rename => { "bytesTotal" => "[network][bytes]" }
    }
  }

  # If source field exists, parse it.
  if [src] {
    if ":" not in [src] {
        mutate {
          copy => { "src" => "[source][ip]" }
      }
    }
    else if [src] =~ "^::(.*)" {
      # Split source address into port and interface.
      mutate {
        split => { "src" => ":" }
        add_field => { "[source][interface][name]" => "%{[src][2]}" }
      }
    }
    else if [src] =~ "(.*)::$" {
      # Split source address into ip and port
      mutate {
        split => { "src" => ":" }
        add_field => { "[source][ip]" => "%{[src][0]}" }
      }
    }
    else if [src] =~ "^:(.*):(.*)" {
      # Split source address into port and interface.
      mutate {
        split => { "src" => ":" }
        add_field => {
          "[source][port]" => "%{[src][1]}"
          "[source][interface][name]" => "%{[src][2]}"
        }
      }
    }
    else if [src] =~ "(.*)::(.*)" {
      # Split source address into port and interface.
      mutate {
        split => { "src" => ":" }
        add_field => {
          "[source][ip]" => "%{[src][0]}"
          "[source][interface][name]" => "%{[src][2]}"
        }
      }
    }
    else if [src] =~ "(.*):(.*):(.*)" {
      # Split source IP address into IP, port and interface.
      mutate {
        split => { "src" => ":" }
        add_field => {
          "[source][ip]" => "%{[src][0]}"
          "[source][port]" => "%{[src][1]}"
          "[source][interface][name]" => "%{[src][2]}"
        }
      }
    }
    else if [src] =~ "^:(.*)" {
      # Split destination address into ip and port.
      mutate {
        split => { "src" => ":" }
        add_field => { "[source][port]" => "%{[src][1]}" }
      }
    }
    else if [src] =~ "(.*):(.*)" {
      # Split source address into ip and port.
      mutate {
        split => { "src" => ":" }
        add_field => {
          "[source][ip]" => "%{[src][0]}"
          "[source][port]" => "%{[src][1]}"
        }
      }
    }
    else {
      mutate {
        add_tag => [ "src_parse_failure" ]
      }
    }
  }

  # If destination field exists, parse it.
  if [dst] {
    if ":" not in [dst] {
      mutate {
        copy => { "dst" => "[destination][ip]" }
      }
    }
    else if [dst] =~ "^::(.*)" {
      # Split destination address into port and interface.
      mutate {
        split => { "dst" => ":" }
        add_field => { "[destination][interface][name]" => "%{[dst][2]}" }
      }
    }
    else if [dst] =~ "(.*)::$" {
      # Split destination address into ip and port.
      mutate {
        split => { "dst" => ":" }
        add_field => { "[destination][ip]" => "%{[dst][0]}" }
      }
    }
    else if [dst] =~ "^:(.*):(.*)" {
      # Split destination address into port and interface.
      mutate {
        split => { "dst" => ":" }
        add_field => {
          "[destination][port]" => "%{[dst][1]}"
          "[destination][interface][name]" => "%{[dst][2]}"
        }
      }
    }
    else if [dst] =~ "(.*)::(.*)" {
      # Split destination address into port and interface.
      mutate {
        split => { "dst" => ":" }
        add_field => {
          "[destination][ip]" => "%{[dst][0]}"
          "[destination][interface][name]" => "%{[dst][2]}"
        }
      }
    }
    else if [dst] =~ "(.*):(.*):(.*)" {
      # Split destination IP address into IP, port and interface.
      mutate {
        split => { "dst" => ":" }
        add_field => {
          "[destination][ip]" => "%{[dst][0]}"
          "[destination][port]" => "%{[dst][1]}"
          "[destination][interface][name]" => "%{[dst][2]}"
        }
      }
    }
    else if [dst] =~ "^:(.*)" {
      # Split destination address into ip and port.
      mutate {
        split => { "dst" => ":" }
        add_field => { "[destination][port]" => "%{[dst][1]}" }
      }
    }
    else if [dst] =~ "(.*):(.*)" {
      # Split destination address into ip and port.
      mutate {
        split => { "dst" => ":" }
        add_field => {
          "[destination][ip]" => "%{[dst][0]}"
          "[destination][port]" => "%{[dst][1]}"
        }
      }
    }
    else {
      mutate {
        add_tag => [ "dst_parse_failure" ]
      }
    }
  }

  # If source interface fields exists, split it into interface and VLAN.
  if [source][interface][name] {
    if "-" in [source][interface][name] {
      mutate {
        split => { "[source][interface][name]" => "-" }
        add_field => { "[source][vlan][id]" => "%{[source][interface][name][1]}" }
      }
    }
  }

  # If destination interface field exists, split it into interface and VLAN.
  if [destination][interface][name] {
    if "-" in [destination][interface][name] {
      mutate {
        split => { "[destination][interface][name]" => "-" }
        add_field => { "[destination][vlan][id]" => "%{[destination][interface][name][1]}" }
      }
    }
  }

  # Remove "V" from VLAN ID and replace array with interface value.
  if [source][vlan][id] {
    mutate {
      gsub => [ "[source][vlan][id]", "V", "" ]
      replace => { "[source][interface][name]" => "%{[source][interface][name][0]}" }
    }
  }
  if [destination][vlan][id] {
    mutate {
      gsub => [ "[destination][vlan][id]", "V", "" ]
      replace => { "[destination][interface][name]" => "%{[destination][interface][name][0]}" }
    }
  }

  # Remove src and dst arrays.
  if "dst_parse_failure" not in [tags] or "src_parse_failure" not in [tags] {
    mutate {
      remove_field => [ "src", "dst" ]
    }
  }

  mutate {
	    remove_field => ["host","original,fields"]
      }
  }`

**Comment by jamiehynds** [comment]
@AlcebiadesFilho we're in the process of rewriting the Sonicwall integration, thanks to this contribution from @jhaugh0 - https://github.com/elastic/integrations/pull/2729

However, we currently have a limited set of sample logs from Sonicwall devices. Would you be willing to provide some log samples to ensure we have broad coverage with this new integration? If so, I can share a link to upload samples to. Thanks!
