### ISSUE TITLE
[Filebeat] [HaProxy] Parse http and url fields

### ISSUE THREAD

**Issue by SHolzhauer** [elastic/beats#25480]
**Describe the enhancement:**
The current pipeline for HaProxy does not parse the `haproxy.http.request.raw_request_line` further into possible fields.
Example:
```
{
    "haproxy.http.request.raw_request_line": "POST /path/to/page HTTP/1.1"
}
```
Can be further parsed into:
```
{
    "haproxy": {
        "http": {
            "request": {
                "raw_request_line": "POST /path/to/page HTTP/1.1"
            }
        }
    },
    "http": {
        "request": {
            "method": "POST"
        ",
        "version": "1.1"
    },
    "url": {
        "path": "/path/to/page"
    }
}
```

I'm not entirely sure if HaProxy logs request parameters (query) but if so the path can be split into it ofcourse:
```
{
    "haproxy.http.request.raw_request_line": "POST /path/to/page?key=value HTTP/1.1"
}
```
Can be further parsed into:
```
{
    "haproxy": {
        "http": {
            "request": {
                "raw_request_line": "POST /path/to/page?key=value HTTP/1.1"
            }
        }
    },
    "http": {
        "request": {
            "method": "POST"
        ",
        "version": "1.1"
    },
    "url": {
        "path": "/path/to/page",
        "query": "key=value"
    }
}
```

**Describe a specific use case for the enhancement or feature:**
More complete parsing will allow for better monitoring in both observability (how often is page `y` opened) as well as security.

**Comment by legoguy1000** [comment]
I'll take a look at this.

**Comment by legoguy1000** [comment]
@SHolzhauer Changes made and PR ready for review.
