### ISSUE TITLE
Visualization not working on Azure billing dashboard

### ISSUE THREAD

**Issue by pmusa** [elastic/beats#25511]
For confirmed bugs, please report:
- Version: 7.12.0 (did not test other versions)
- Steps to Reproduce: Ingest billing metrics from Azure and open the Azure Billing dashboard. The **[Billing resource name]** visualization will be empty.

After further investigation, I noticed that we are using a field that does not exist in the collected documents. In the visualization, we bucket on `azure.resource.name`, but the correct field is `azure.resource.type`. I also noticed that the visualization is not filtering documents that contain the field, which results in a slower aggregation (~40ms vs. ~2ms) and wrong results (see screenshots).

Bucket using `azure.resource.name` with no results:
<img width="1068" alt="Screenshot 2021-05-03 at 23 39 09" src="https://user-images.githubusercontent.com/361280/116937330-5d317d00-ac69-11eb-9c0a-be135e848c28.png">

Bucket using `azure.resource.type` no filter with wrong results:
<img width="1060" alt="Screenshot 2021-05-03 at 23 40 14" src="https://user-images.githubusercontent.com/361280/116937297-530f7e80-ac69-11eb-9c94-6c606b1dca3f.png">

Bucket using `azure.resource.type` and filter with correct results:
<img width="1064" alt="Screenshot 2021-05-03 at 23 38 26" src="https://user-images.githubusercontent.com/361280/116937284-4e4aca80-ac69-11eb-8be1-035fea270130.png">

**Comment by ChrsMark** [comment]
Thanks for reporting this @pmusa!

@narph could you please verify if this is actually a bug?

**Comment by narph** [comment]
confirmed this looks like a bug, `azure.resource.name` should be still there, it looks like we took it out while working on the inventory fields, this might not have been the goal for billing as well. I will investigate this further.

**Comment by narph** [comment]
@pmusa , I have fixed the visualization in the above PR, in the visualization above we split by resource name. Maybe in the future we can add a visualization splitting on the resource type as well.
