### ISSUE TITLE
Create new module or integration for ForgeRock logs

### ISSUE THREAD

**Issue by a03nikki** [elastic/beats#25532]
**Describe the enhancement:**

There are a number of existing [integrations](https://www.elastic.co/integrations) for ingesting logs. It would be nice if there was support for [ForgeRock](https://www.forgerock.com/) identity and access management logs.

**Describe a specific use case for the enhancement or feature:**

There are multiple Mitre Att&ck techniques that target authentication and identity providers.  Additionally, software development teams integrating and using the platform, want to observer it as well.

ForgeRock is used by organizations to provide SSO and end user system access.  These organizations would like to monitor its activity.

**Comment by jamiehynds** [comment]
Thansk @a03nikki - I noticed ForgeRock mention support for Elastic on their site: https://www.forgerock.com/platform/common-services/common-audit

I've reached out for more information.

**Comment by legoguy1000** [comment]
It looks like a Filebeat integration would be another HTTP poller, https://backstage.forgerock.com/docs/idcloud/latest/tenant-audit-logs.html

**Comment by jamiehynds** [comment]
We are currently working on a Forgerock integration with Elastic Agent. Please track this issue for updates: https://github.com/elastic/integrations/issues/1085

**Comment by jamiehynds** [comment]
Integration now available with ForgeRock. Docs available here: https://docs.elastic.co/integrations/forgerock
