### ISSUE TITLE
Remove 32 bits artifact for the Elastic Agent

### ISSUE THREAD

**Issue by ph** [elastic/beats#25533]
We want to make sure that all the platform supported by the Elastic Agent are only 64 bits. Because we want to make sure that all the binaries are compiled with ASLR.

### 7.13
- [x] Update the release manager to remove all the 32 artifacts.
- [x] Communicate with QA Source.
- [x] Documentation, release notes?
- [x] Ensure that the artifacts are removed from the website.
- [x] Update download page to remove 32-bit links https://github.com/elastic/product-marketing/issues/557

### 7.14

- [x] Remove 32 bits jobs for the Elastic Agent.
- [x] Remove 32 bits support in the `mage package` of the elastic agent.
- [x] Remove 32 bits artifacts for the fleet server.

**Comment by dikshachauhan-qasource** [comment]
Hi @ph cc @EricDavisX 

Could you please let us know how to validate this ticket.

Thanks
QAS

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX cc @ph 

As currently ticket has no merges for 7.13 build so we will wait to validate this ticket till the merges are available for the removal of elastic agent 32 bit artifacts.

Thanks
QAS

**Comment by mostlyjason** [comment]
@EricDavisX yes this was requested by Tony to mitigate the ASLR vulnerability

**Comment by EricDavisX** [comment]
So, there are draft PRs open still but I think other work resolves the desire here.  Not sure if we want to track down the teams / prs (and tickets) and do the leg work to close this all out.  I don't know any larger coordination needs, like with the Web site or all of the downloadable locations to find artifacts.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

For now, as per the merges we have validated the 7.14 snapshot artifact link and found 32 bits artifacts links are still available.

**Artifact link referred:**
https://artifacts-api.elastic.co/v1/search/7.14.0-SNAPSHOT

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/120149380-4306a280-c207-11eb-93e2-9dc93ca0a061.png)

@ph Could you please confirm us about mage package of the elastic agent. And if we have mistaken anything in validating above merges.

Thanks
QAS

**Comment by EricDavisX** [comment]
This makes sense then, the above PRs surely are for the Infra job side removal - I just couldn't be sure prior, thanks for noting it Diksha.  We can follow up again when the PRs are merged later.

**Comment by ph** [comment]
@mgreau I think all the items were achieved on our side for 7.13-14. I will close this one.

**Comment by EricDavisX** [comment]
Indeed - I don't see us shipping 32-bit arch artifacts as of now.  closing it out.
