### ISSUE TITLE
Create new module or integration for LastPass logs

### ISSUE THREAD

**Issue by a03nikki** [elastic/beats#25531]
**Describe the enhancement:**

There are a number of existing [integrations](https://www.elastic.co/integrations) for ingesting logs.  It would be nice if there was support for [LastPass](https://www.lastpass.com/) password manager.

**Describe a specific use case for the enhancement or feature:**

One of the Mitre Att&ck  techniques, [T1555.005](https://attack.mitre.org/techniques/T1555/005/), is "Credentials from Password Stores: Password Managers".  LastPass is a password manager so people and organizations using it would like to monitor its activity.

**Comment by legoguy1000** [comment]
This would be dope.  Do u have any info on the Last Pass Enterprise API? THe docs are definitely lacking

**Comment by austinsonger** [comment]
@jamiehynds I'm surprise Elastic made 1Password before LastPass when LastPass has more users globally than 1Password.

**Comment by jamiehynds** [comment]
Hey @austinsonger - 1Password actually developed the integration via our integration partnership program. We're continuing to track demand for LastPass. 

Does LastPass have an API we can hit for events or do they push to a http endpoint? Can't find much information from their docs.

**Comment by a03nikki** [comment]
FYI, there is now a Fleet / Agent integration for this
- https://github.com/elastic/integrations/issues/1157
- https://github.com/elastic/integrations/pull/4254
