### ISSUE TITLE
[ Agent ] No Agent folder for the Linux machine after successful installation

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/beats#25549]
**Describe the bug**
No Agent folder for the Linux machine after successful installation [Debian10_x64]

**Build Details:**
```
Version: 7.13.0
Commit: 62a98b97048b3639b8dfe7884776d95581dc1eb5
Build number: 40746
Artifact: https://staging.elastic.co/7.13.0-100107e6/summary-7.13.0.html
```

**Browser Details**
All

**Preconditions**
1. Elastic Cloud 7.13.0 environment should be deployed

**Steps to Reproduce**
1. Download the "elastic-agent-x.x.x-amd64.deb" package from artifact page.
2. Then place the agent package on home/zeus location on Debian 10 Linux machine.
3. Hit the command to get the root/admin permission: sudo su root
4. sudo dpkg -i elastic-agent-x.x.x-amd64.deb
5. Then run the below enroll command:-
elastic-agent enroll --url=<URL> --enrollment-token=<Enrollment-Token>
7. Then run the below command to enable the agent:
    - systemctl enable elastic-agent
8. After that run the below command to start the agent.
    - systemctl start elastic-agent

**Test data**
N/A

**Impacted Test case(s)**
N/A

**Actual Result**
No Agent folder for the Linux machine after successful installation

**Expected Result**
Agent folder should be created for the Linux machine after successful installation

**What's Working**
N/A

**What's not Working**
N/A

**Screenshot**
![Logs](https://user-images.githubusercontent.com/60252716/117132617-b3650400-adc0-11eb-9c63-ad7c0501c87f.JPG)

**Logs**
N/A

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
I believe the install locations for DEB/RPM are different than /opt/Elastic/ location.  you can do a 'find / -name elastic' command to see where they are?  And we can check the docs to confirm where it says the logs will be found.  And 3rd, if Agent is running ok at this point then we can know it isn't a bug and close it out.  @muskangulati-qasource thank you for the help following up and let us know!

**Comment by blakerouse** [comment]
For the DEB/RPM they are spread out in a few locations:

/etc/elastic-agent
/usr/share/elastic-agent
/var/lib/elastic-agent

**Comment by muskangulati-qasource** [comment]
Hi @EricDavisX, @blakerouse

Thank you for the information. 

We are able to access the logs. 
![image](https://user-images.githubusercontent.com/60252716/117137858-f5de0f00-adc7-11eb-9542-c6bb2ab04b18.png)

Hence closing this issue.

Thanks!
