### ISSUE TITLE
 "elastic_agent.filebeat" data events not available on Discover tab after enable logs collection settings at Elastic agent on cloud policy.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#25555]
**Kibana version:**
7.13 BC4 Kibana Cloud QA environment 

**Host OS and Browser version:**
Managed host on cloud, All

**Preconditions**
1.  7.13 BC4 Kibana Cloud QA environment should be available.
```
Kibana version: 7.13 BC4
BUILD 40749
COMMIT 5a6bad454ffe263aafed54cbd3f764253694bf37
Artifact link: https://staging.elastic.co/7.13.0-5c4bc719/summary-7.13.0.html
```

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Policies tab.
3. Navigate to  Elastic agent on cloud policy's settings tab.
4. Enable checkboxes for logs and metrics collection.
5. Save the updated settings and wait for few seconds to generate data events on data streams page. 
6. Navigate to discover tab after dataevents are available on Data stream page.
7. Apply filter: host.hostname : "10f295938b7f" and event.dataset : "elastic_agent.filebeat"

**Actual Result:**
 "elastic_agent.filebeat" data events not available on Discover tab after enable logs collection settings at Elastic agent on cloud policy.

**Screenshots:** 
![image](https://user-images.githubusercontent.com/72375798/117147272-b832b380-add2-11eb-9d21-4f3357ed1a74.png)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by mostlyjason** [comment]
Can you check how much memory you have in your APM & Fleet instance? You might want to set it to 2GB to make sure there is enough space for Filebeat to run

**Comment by dikshachauhan-qasource** [comment]
Hi @mostlyjason 

Thanks for the feedback.

We have revalidated it with above recommended changes and found it working fine. Now events for both metricbeat and filebeat are available under Discover tab.

![image](https://user-images.githubusercontent.com/72375798/117153453-9a684d00-add8-11eb-9e79-306d3dccbcb8.png)

However, also observed a new managed host got deployed with the APM changes. So each time whenever we will trigger these changes a new managed host will appear.

Thanks
QAS

**Comment by mostlyjason** [comment]
@dikshachauhan-qasource by managed host you mean you see an other offline agent on the agents page? That is expected and a known bug we hope to address here https://github.com/elastic/beats/issues/25030

**Comment by dikshachauhan-qasource** [comment]
### `Bug Conversion`

-  01 new testcase is created under the 'Discover' section:
   - https://elastic.testrail.io/index.php?/cases/view/147372

Thanks!
