### ISSUE TITLE
[Fleet] Multiple instances of Heartbeat appear to run with Synthetics integrations

### ISSUE THREAD

**Issue by justinkambic** [elastic/beats#25569]
**Kibana version:**
7.13

**Elasticsearch version:**
7.13

**Server OS version:**
macOS Big Sur

**Browser version:**
Chrome 90

**Browser OS version:**
macOS Big Sur

**Original install method (e.g. download page, yum, from source, etc.):**
from source

**Describe the bug:**
I created numerous Synthetics integrations while testing the Synthetics package/associated UI. After noticing that a number of my monitors weren't showing up, I checked Agent's logs and it appeared there were multiple processes attempting to lock `path.data`, and thus causing the beat to crash.

**Steps to reproduce:**
1. I have included the policy I was using.
2. When running this policy, see that some of the monitors (integrations) will appear in the Uptime app.
3. Looking at agent's logs, you should see that Heartbeat is crashing each time it attempts to run.

Note - I did perform numerous edits to some of the integrations.

**Expected behavior:**
My many Synthetics integrations would all appear as Uptime monitors in the application.

**Provide logs and/or server output (if relevant):**
**Heartbeat Logs*
```
13:19:45.788
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Beat ID: e0cf3659-51ff-4f2e-bede-7ff7f0bb1c7d
13:19:45.791
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] heartbeat stopped.
13:19:45.815
elastic_agent.heartbeat
[elastic_agent.heartbeat][error] Exiting: data path already locked by another beat. Please make sure that multiple beats are not sharing the same data path (path.data).
13:19:45.981
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Home path: [/Library/Elastic/Agent/data/elastic-agent-d05461/install/heartbeat-7.13.0-SNAPSHOT-darwin-x86_64] Config path: [/Library/Elastic/Agent/data/elastic-agent-d05461/install/heartbeat-7.13.0-SNAPSHOT-darwin-x86_64] Data path: [/Library/Elastic/Agent/data/elastic-agent-d05461/run/default/heartbeat--7.13.0-SNAPSHOT] Logs path: [/Library/Elastic/Agent/data/elastic-agent-d05461/install/heartbeat-7.13.0-SNAPSHOT-darwin-x86_64/logs]
```

**Agent logs**
```
13:19:46.746
elastic_agent
[elastic_agent][info] Elastic Agent status changed to: 'online'
13:19:46.747
elastic_agent
[elastic_agent][info] 2021-05-05T13:19:46-04:00 - message: Application: heartbeat--7.13.0-SNAPSHOT[0efa381a-eae2-4e4f-932f-0836afb087ed]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
13:19:46.747
elastic_agent
[elastic_agent][info] 2021-05-05T13:19:46-04:00 - message: Application: heartbeat--7.13.0-SNAPSHOT[0efa381a-eae2-4e4f-932f-0836afb087ed]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'
13:19:46.747
elastic_agent
[elastic_agent][info] fleet reporter dropped event because threshold[10000] was reached: &{0efa381a-eae2-4e4f-932f-0836afb087ed STATE {13843169306175520096 12992407552333 0x10af610a0} STARTING Application: heartbeat--7.13.0-SNAPSHOT[0efa381a-eae2-4e4f-932f-0836afb087ed]: State changed to STARTING: Starting map[]}
13:19:46.747
elastic_agent
[elastic_agent][info] fleet reporter dropped event because threshold[10000] was reached: &{0efa381a-eae2-4e4f-932f-0836afb087ed STATE {13843169306175667096 12992407699455 0x10af610a0} STARTING Application: heartbeat--7.13.0-SNAPSHOT[0efa381a-eae2-4e4f-932f-0836afb087ed]: State changed to RESTARTING: Restarting map[]}
```

**Any additional context:**

I have posted the policy that led to this here: https://gist.github.com/justinkambic/3f65fbd42c68dd5b9145ba1790fb6779

**Comment by justinkambic** [comment]
We are working to merge https://github.com/elastic/integrations/pull/981 which should address part of the problem we had getting Heartbeat functionality working again. I am still seeing logs of Filebeat trying to run as part of the integration, however, and it not being able to write to its `path.data` directory.

```
09:12:07.729 [elastic_agent.filebeat][info] Beat ID: 272bf739-e1fb-498f-a38f-850f21c47e66
09:12:07.730 [elastic_agent.filebeat][info] Set gc percentage to: 100
09:12:07.732 [elastic_agent.filebeat][info] add_cloud_metadata: hosting provider type not detected.
09:12:07.758 [elastic_agent.filebeat][info] filebeat stopped.
09:12:07.803 [elastic_agent.filebeat][error] Exiting: data path already locked by another beat. Please make sure that multiple beats are not sharing the same data path (path.data).
09:12:07.965 [elastic_agent.filebeat][info] Home path: [/Library/Elastic/Agent/data/elastic-agent-afbdaa/install/filebeat-8.0.0-SNAPSHOT-darwin-x86_64] Config path: [/Library/Elastic/Agent/data/elastic-agent-afbdaa/install/filebeat-8.0.0-SNAPSHOT-darwin-x86_64] Data path: [/Library/Elastic/Agent/data/elastic-agent-afbdaa/run/default/filebeat--8.0.0-SNAPSHOT] Logs path: [/Library/Elastic/Agent/data/elastic-agent-afbdaa/install/filebeat-8.0.0-SNAPSHOT-darwin-x86_64/logs]
09:12:07.967 [elastic_agent.filebeat][info] Beat ID: 272bf739-e1fb-498f-a38f-850f21c47e66
09:12:07.969 [elastic_agent.filebeat][info] Set gc percentage to: 100
09:12:07.972 [elastic_agent.filebeat][info] add_cloud_metadata: hosting provider type not detected.
09:12:08.066 [elastic_agent.filebeat][error] Error watching for docker events: error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/events?filters=%7B%22type%22%3A%7B%22container%22%3Atrue%7D%7D&since=1620738728.065772000": context canceled
```

**Comment by blakerouse** [comment]
@justinkambic Could you provide the policy configuration that was showing the filebeat error in the logs? That would ensure I am running the same thing for me to reproduce.

**Comment by ph** [comment]
@paulb-elastic @justinkambic Can you give us the policy configuration that you are using that generate the above issue? We haven't found this issue in our code at that with the existing beats. We have marked it as a blocker but I would like to remove the label.

**Comment by justinkambic** [comment]
Hi @ph, we discovered an issue in our synthetics package that [we've subsequently fixed](https://github.com/elastic/integrations/pull/981); Heartbeat functions the way we'd expect now. The policy that led us to open this issue can be found here: https://gist.github.com/justinkambic/3f65fbd42c68dd5b9145ba1790fb6779

The only remaining unexpected behavior I see at this point is that the logs for my Synthetics integration contain Filebeat logs; I don't fully understand why FB would be running.

**Comment by blakerouse** [comment]
@justinkambic Elastic Agent runs Filebeat to collect logs for the running beats. So Filebeat should be running to collect the logs from Heartbeat. Is that the filebeat you are speaking of?

**Comment by ph** [comment]
This seems to be resolved, going to remove blocker.

If @justinkambic I think the running filebeat is indeed the internal collection that we are running.

**Comment by justinkambic** [comment]
We can likely close this issue then. Will reopen if anything relevant arises.
