### ISSUE TITLE
Add "version" to 5.x templates

### ISSUE THREAD

**Issue by pickypg** [elastic/beats#2556]
Templates (and pipelines) now support a `"version"` integer field that can added to them for the type of need that Logstash has: when to replace the existing template. (https://github.com/elastic/elasticsearch/issues/20171)

We should add the `"version"` to the existing 5.x Beats template, which should allow us to simplify replacing it, as needed, in the future as well as the older templates.

``` http
GET /_template/my_template?filter_path=*.version
```

This will return an empty JSON object for non-versioned templates.

``` json
{}
```

and it will return whatever version is set for templates that do set it:

``` json
{"my_template":{"version":20160915}}
```

**Comment by ruflin** [comment]
We introduced a version in our template very recently as a meta field: https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.template.json#L8 It is great to see that this is now supported natively. I will adjust our script to put the version now on the top level. Thanks for pinging us on this one.
