### ISSUE TITLE
Existing agents do not re-enroll in fleet correctly after 7.12-snapshot to 7.13-snapshot upgrade

### ISSUE THREAD

**Issue by mukeshelastic** [elastic/beats#25586]
**Steps to reproduce:**

1. A 7.12-snapshot deployment was spun in the qa.cld.elstc.co environment with zero apm instance.  
2. I went to Kibana and enabled fleet ( this is pre-fleet-server implementation) and enrolled an agent. 
3. I came back to cloud console and upgraded the deployment to 7.13-snapshot.
4. I went to fleet UI and was asked to set up fleet server. I did that from cloud console
5. Then I re-enrolled the agent. 
5. The agent remained online for few mins but then became offline. 
I saw the following in the agent logs:
_`Could not communicate with Checking API will retry, error: could not decode the response, raw response: Client sent an HTTP request to an HTTPS server`_

6. Agent continues to send data to ES 

**Note This problem isn't reproducible if you start with 7.13 deployment and enroll agents with fleet server.**

**Comment by nchaulet** [comment]
If it could help investigating my `fleet.yml` file for the agent show the protocol `http` here

<img width="672" alt="Screen Shot 2021-05-06 at 10 17 59 AM" src="https://user-images.githubusercontent.com/1336873/117314247-8feb9900-ae54-11eb-98f4-6a731f0aff10.png">

**Comment by ph** [comment]
@mukeshelastic what was the enrollment command that you have been running? The error you see in the log make total sense if the tls is remove from the URL. cc @blakerouse

**Comment by blakerouse** [comment]
I am a little lost on the steps here. So it was a 7.12 installation before connected to QA cloud? Then you upgraded the cloud deployment to 7.13 (running a Fleet Server), and your trying to enroll the Elastic Agent into that Fleet Server using a newly downloaded 7.13?

The newly extracted Elastic Agent will not read anything from the existing installation from the disk. So I question what Kibana is actually setting as the policy? If Kibana added the `protocol: http` to the policy and that is what is getting sent in the policy to the Elastic Agent.

**Comment by mukeshelastic** [comment]
@blakerouse happy to clarify the repro steps. 

1. A 7.12-snapshot deployment was spun in the qa.cld.elstc.co environment with single apm instance.  
2. I went to Kibana and enabled fleet ( this is pre-fleet-server implementation) and enrolled an agent. 
3. I came back to cloud console and upgraded the deployment to 7.13-snapshot.
4. I went to fleet UI and was asked to re-enroll the agent. 
5. I re-enrolled the agent and it remained online for few mins but then became offline. 

@ph @EricDavisX has this scenario been tested by someone on QA team? I am hoping that this is either user error or an environment problem. If it isn't then this is high severity bug.

**Comment by blakerouse** [comment]
@mukeshelastic Could you provide the logs of the Elastic Agent? Looking at the logs is the best way for me to see what occurred.

**Comment by mukeshelastic** [comment]
The deployment gets deleted periodically so don't have logs for it :-/  FWIW, it looks similar story as #25667. i will spin up a deployment and test out now.

**Comment by mukeshelastic** [comment]
Here is the log line that shows the checkin failed:

`14:42:36.571
elastic_agent
[elastic_agent][error] Could not communicate with Checking API will retry, error: fail to checkin to fleet: Post "https://5994bc11a32c4e06b52306cc3cb448cc.fleet.us-central1.gcp.qa.cld.elstc.co:443/api/fleet/agents/f70a15b0-a618-43be-b723-11bb5f6f0b4c/checkin?": net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

`14:49:04.752
elastic_agent
[elastic_agent][error] Could not communicate with Checking API will retry, error: fail to checkin to fleet: Post "https://5994bc11a32c4e06b52306cc3cb448cc.fleet.us-central1.gcp.qa.cld.elstc.co:443/api/fleet/agents/f70a15b0-a618-43be-b723-11bb5f6f0b4c/checkin?": net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Comment by ph** [comment]
@mukeshelastic The two checking is from 5 minute away, this might be a long pooling timeout. Does the Agent is marked as heathy in Fleet?

**Comment by mukeshelastic** [comment]
That's right, the polling time is five minutes which I believe is much longer than expected ( 30 seconds?) 

The agent shows offline, likely because of the timeouts.

**Comment by ph** [comment]
@mukeshelastic I think you are confusing the implementation, the elastic agent will connect to fleet server and keep that connection open, if there an action to execute or a policy change it will retrieve it and ACK. When there is nothing to do it will just hang and wait for a timeout and reconnect.

**Comment by mukeshelastic** [comment]
ah.. thanks for clarification. Don't want to derail this discussion on the architectural questions but I assumed there is some frequent health "checkin" between agents and fleet-server independent of whether there is a policy update or not. Either ways, l will dig into how things work separately outside of this issue.

**Comment by mukeshelastic** [comment]
The elastic agent version is as follows:

mukeshgadiya@Mukeshs-MBP elastic-agent-7.13.0-SNAPSHOT-darwin-x86_64 % ./elastic-agent version --yaml
binary:
  version: 7.13.0
  commit: 035664e68274216424b77147f959e910dc2bfc5c
  build_time: 2021-05-10T16:26:25Z
  snapshot: true
failed to communicate with running daemon: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /tmp/elastic-agent/f9424f37837ac6d36d46f1c18545e33b92c794473d16a5259ad4eb6665466a71.sock: connect: no such file or directory"

**Comment by blakerouse** [comment]
@mukeshelastic Please check the Fleet Server URL setting in the Kibana URL. I believe that it is missing the `:443` port in the URL and that is what is causing your issue.

**Comment by mukeshelastic** [comment]
it does have 443 port in it. 

<img width="868" alt="Screen Shot 2021-05-13 at 7 12 15 AM" src="https://user-images.githubusercontent.com/59452300/118138870-a9906180-b3bb-11eb-93c1-ff24d2f532d0.png">

The elastic agent logs are as follows:

`07:13:11.517
elastic_agent
[elastic_agent][info] 2021-05-13T07:13:11-07:00 - message: Application: metricbeat--7.13.0-SNAPSHOT[9f19a42c-e0a7-4214-a39e-07d5ef55e571]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
07:13:12.925
elastic_agent
[elastic_agent][info] 2021-05-13T07:13:12-07:00 - message: Application: filebeat--7.13.0-SNAPSHOT[9f19a42c-e0a7-4214-a39e-07d5ef55e571]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
07:13:13.101
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for filebeat.7.13.0-SNAPSHOT
07:13:13.278
elastic_agent
[elastic_agent][info] 2021-05-13T07:13:13-07:00 - message: Application: filebeat--7.13.0-SNAPSHOT--36643631373035623733363936343635[9f19a42c-e0a7-4214-a39e-07d5ef55e571]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
07:13:13.456
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for metricbeat.7.13.0-SNAPSHOT
07:13:13.514
elastic_agent
[elastic_agent][info] 2021-05-13T07:13:13-07:00 - message: Application: metricbeat--7.13.0-SNAPSHOT--36643631373035623733363936343635[9f19a42c-e0a7-4214-a39e-07d5ef55e571]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
07:13:13.521
elastic_agent
[elastic_agent][info] Updating internal state
07:13:13.634
elastic_agent
[elastic_agent][error] failed to dispatch actions, error: acknowledge 1 actions '[action_id: policy:504f8ba0-b3f2-11eb-8ba9-2bb101be8aac:1:1, type: POLICY_CHANGE]' for elastic-agent '9f19a42c-e0a7-4214-a39e-07d5ef55e571' failed: could not decode the response, raw response: Client sent an HTTP request to an HTTPS server.
07:13:13.634
elastic_agent
[elastic_agent][error] Elastic Agent status changed to: 'error'
07:13:14.669
elastic_agent
[elastic_agent][info] 2021-05-13T07:13:14-07:00 - message: Application: metricbeat--7.13.0-SNAPSHOT--36643631373035623733363936343635[9f19a42c-e0a7-4214-a39e-07d5ef55e571]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
07:13:15.371
elastic_agent
[elastic_agent][error] Could not communicate with fleet-server Checking API will retry, error: could not decode the response, raw response: Client sent an HTTP request to an HTTPS server.
07:13:15.437
elastic_agent
[elastic_agent][info] 2021-05-13T07:13:15-07:00 - message: Application: filebeat--7.13.0-SNAPSHOT[9f19a42c-e0a7-4214-a39e-07d5ef55e571]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
07:13:15.441
elastic_agent
[elastic_agent][info] 2021-05-13T07:13:15-07:00 - message: Application: filebeat--7.13.0-SNAPSHOT--36643631373035623733363936343635[9f19a42c-e0a7-4214-a39e-07d5ef55e571]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
07:14:20.001
elastic_agent
[elastic_agent][error] Could not communicate with fleet-server Checking API will retry, error: could not decode the response, raw response: Client sent an HTTP request to an HTTPS server.
07:18:14.013
elastic_agent
[elastic_agent][error] Could not communicate with fleet-server Checking API will retry, error: could not decode the response, raw response: Client sent an HTTP request to an HTTPS server.`

**Comment by blakerouse** [comment]
@mukeshelastic can you attach the `state.yml`? that should include the configuration that the Fleet Server sent the Elastic Agent, something is a-miss here.

**Comment by blakerouse** [comment]
@simitt Have you seen this in the cloud?
