### ISSUE TITLE
Auditbeat.yml examples for system datasets:[login,socket,user]

### ISSUE THREAD

**Issue by stefnestor** [elastic/beats#25619]
In follow-up to https://github.com/elastic/beats/issues/25618, will you show me / update your docs to include examples for your auditbeat/`module:system`/`datasets:[login,socket,user]`.

The three don't reference in the downloaded auditbeat.yml or auditbeat.reference.yml & the docs don't say how to configure.
- login
    - [doc reference](https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-dataset-system-login.html)
    - [Github code](https://github.com/elastic/beats/tree/master/x-pack/auditbeat/module/system/login)
- socket
    - [doc reference](https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-dataset-system-socket.html)
    - [Github code](https://github.com/elastic/beats/tree/master/x-pack/auditbeat/module/system/socket)
- user
    - [doc reference](https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-dataset-system-user.html)
    - [Github code](https://github.com/elastic/beats/tree/master/x-pack/auditbeat/module/system/user)

**Comment by andrewkroh** [comment]
> The three don't reference in the downloaded auditbeat.yml or auditbeat.reference.yml & the docs don't say how to configure.

What OS package are you looking at? As noted in the documentation that you linked, those 3 are only implemented on Linux. Only the config files in the Linux artifacts will contain references to those datasets.

**Comment by stefnestor** [comment]
Ah, I straight up missed that, sorry! Thanks for the quick response!
