### ISSUE TITLE
Add new metrics about queue size and output workers to template

### ISSUE THREAD

**Issue by simitt** [elastic/beats#25628]
With https://github.com/elastic/beats/issues/22215 additional metrics for stack monitoring are collected (`queue.mem.events`, `output.elasticsearch.workers`, `output.elasticsearch.bulk_max_size`). They should also be added to the template to allow to query by them. 

this is targeting `7.14`

**Comment by graphaelli** [comment]
Let's also grab `beat.info.version` from #26214 while we're at it.

**Comment by jlind23** [comment]
Backlog grooming: @simitt is this issue still relevant?

**Comment by simitt** [comment]
For APM Server this is not relevant any more for APM Server; might still be interesting for other beats though.
