### ISSUE TITLE
Using Keystores - not working (v6.6.0)

### ISSUE THREAD

**Issue by anaconda2196** [elastic/beats#25621]
Hello,

I'm trying to use a keystore value in my metricbeatbeat configuration and I can't seem to get it working...

I have created initContainer in that I am just creating keystore and add my elasticsearch password in ES_PWD!
```
metricbeat --path.config=/usr/share/metricbeat/keystore -c /etc/metricbeat.yml keystore create
echo 'my-ES-clear-text-pwd' | metricbeat --path.config=/usr/share/metricbeat/keystore -c /etc/metricbeat.yml keystore add ES_PWD --stdin --force 
metricbeat --path.config=/usr/share/metricbeat/keystore -c /etc/metricbeat.yml keystore list
```
[sharing volumes between initContainer and actual container!]

In actual metricbeat container trying to run metricbeat service but it is not starting.
(./metricbeat --path.config=/usr/share/metricbeat/keystore -c /etc/metricbeat.yml -e)

However pod is running but metricbeat service is not starting up inside it!

If i exec into pod and manually copy metricbeat.keystore from --path.config=/usr/share/metricbeat/keystore to --path.data (/usr/share/metricbeat)  and if I try to run metricbeat service manually then it is running. (./metricbeat -c /etc/metricbeat.yml -e -system.hostfs=/hostfs)

I found one similar issue: https://discuss.elastic.co/t/using-keystores-not-working-v6-6-0/167301

Thanks in advance.

**Comment by ph** [comment]
@anaconda2196 Looking at the title, are you testing this in metricbeat v6.6.6? If this is the case can you try in a more recent version? We have released recently 7.12

**Comment by anaconda2196** [comment]
@ph Thank you for your reply. No, I am using v6.6.0 and I have no longer plan use latest version. So, is it the bug in V6.6.0? Do I have to copy every time my keystore from --path.config to --path.data to run metricbeat service?

**Comment by anaconda2196** [comment]
Hello @ph @jsoriano 
Just wanted to confirm if it is bug in v6.6? Thank you for your time.

**Comment by jsoriano** [comment]
Hey @anaconda2196,

Your problem may be similar to this one: https://github.com/elastic/beats/issues/12315. There the problem is with Windows installations, but the workaround also seems to be to move the keystore to the data directory. Another maybe better alternative mentioned there is to explicitly set `keystore.path`.

Btw, could you share the logs of your metricbeat that fails to start?

**Comment by faec** [comment]
Seems to be from an outdated version.
