### ISSUE TITLE
Please support goebpf in packetbeat

### ISSUE THREAD

**Issue by manning23** [elastic/beats#25620]
Please support goebpf in packetbeat

goebpf is a more advanced packet capture technology, which is more efficient than gopacket.

**Comment by andrewkroh** [comment]
Is https://github.com/dropbox/goebpf the project to which you are referring? Is there full packet capture example somewhere to get an idea of how much effort it would be to integrate?

**Comment by manning23** [comment]
I think you can look at this case, https://github.com/dropbox/goebpf/blob/master/examples/xdp/xdp_dump/main.go.

> Is https://github.com/dropbox/goebpf the project to which you are referring? Is there full packet capture example somewhere to get an idea of how much effort it would be to integrate?
