### ISSUE TITLE
[METRICBEAT] Jolokia JMX mBeanName.Canonicalize() fails to sort correctly the properties

### ISSUE THREAD

**Issue by Hacko-nPacko** [elastic/beats#25630]
Hey folks,

I noticed that the the Canonicalize method will sort the strings, but that has some edge cases:
https://github.com/elastic/beats/blob/afbdaa93ccc2d1a10adb7eed275840f3a66bf498/metricbeat/module/jolokia/jmx/config.go#L142

here:
https://github.com/elastic/beats/blob/afbdaa93ccc2d1a10adb7eed275840f3a66bf498/metricbeat/module/jolokia/jmx/config.go#L153

e.g. input "solr:dom1=jvm,name=used,name0=memory,name1=total"
the method returns "solr:dom1=jvm,name0=memory,name1=total,name=used" which is not very canonical

can i submit a pull request for this?
https://github.com/elastic/beats/blob/afbdaa93ccc2d1a10adb7eed275840f3a66bf498/metricbeat/module/jolokia/jmx/config.go#L156
I'd propose sorting only on the keys, then adding the correct values

best regards
atanas

**Comment by jsoriano** [comment]
Reopening, fix still not merged.
