### ISSUE TITLE
Heartbeat not connecting to Elasticsearch

### ISSUE THREAD

**Issue by liza-mae** [elastic/beats#25651]
For confirmed bugs, please report:
- Version: 8.0.0-SNAPSHOT
- Operating System: Ubuntu 18
- Steps to Reproduce: 
1. Install Elasticsearch and Heartbeat 
2. Start Heartbeat 
3. On all the other beats I get this message like the following in the logs: 
```
INFO	[publisher_pipeline_output]	pipeline/output.go:143	Connecting to backoff(elasticsearch(https://10.0.2.15:9200))
INFO	[publisher_pipeline_output]	pipeline/output.go:151	Connection to backoff(elasticsearch(https://10.0.2.15:9200)) established
```
For Heartbeat I am not seeing those messages.  Heartbeat process is running, but I am getting no data, there are no error messages in the logs that I can tell, nothing has changed in the configuration.  Not sure if something changed for 8.0 that needs to be updated or if this is a bug, need someone to take a look.

**Comment by liza-mae** [comment]
This is now occurring on 7.13, so a recent backport to this branch (within the last two days) is causing this.

**Comment by ph** [comment]
@liza-mae you are able to reproduce it constantly, but only with heartbeat? The  only thing that I could think of is the adding #25351. But that should affect all the beats and not only heartbeat. 

Can you start heartbeat with `--httpprof "localhost:8080` and do the following.

- Wait a few seconds
- Take a goroutine dump `curl -q http://localhost:8080/debug/pprof/goroutine?debug=2 > goroutine1.dump`
- Wait 15 seconds
- Take a goroutine dump `curl -q http://localhost:8080/debug/pprof/goroutine?debug=2 > goroutine2.dump`
- Wait 15 seconds 
- Take a goroutine dump. `curl -q http://localhost:8080/debug/pprof/goroutine?debug=2 > goroutine3.dump`

I wonder if we have a deadlock somewhere either in beats or heartbeat.

**Comment by ph** [comment]
@andrewvc Anything on your side that you think could generate the above behavior?

**Comment by liza-mae** [comment]
@ph yes it is reproducible and just heartbeat.   Attaching pprof logs. 

[goroutine1.dump.txt](https://github.com/elastic/beats/files/6473491/goroutine1.dump.txt)
[goroutine2.dump.txt](https://github.com/elastic/beats/files/6473493/goroutine2.dump.txt)
[goroutine3.dump.txt](https://github.com/elastic/beats/files/6473494/goroutine3.dump.txt)

**Comment by ph** [comment]
I don't see anything obvious in the goroutine dump, I don't run into issues here with the minimal configuration I am running. @liza-mae could you share your configuration?

@paulb-elastic is there someone from your side that could help us on this issue?

**Comment by liza-mae** [comment]
@ph attached is my configuration. 

[heartbeat.yml.txt](https://github.com/elastic/beats/files/6474728/heartbeat.yml.txt)

**Comment by andrewvc** [comment]
I think we can file this as not a bug. https://github.com/elastic/beats/pull/25592 introduced this change in behavior. In that PR we no longer set a default monitor. Since heartbeat only connects to elasticsearch when it has data to send it does not connect in your situation because there is no monitor data to provoke the elasticsearch output code to connect.

To change this all you have to do is to set `enabled: true` or delete the `enabled` line.

**Comment by andrewvc** [comment]
To clarify this is not really a behavior change but rather a default config file change. The application code is identical.

**Comment by liza-mae** [comment]
Yes that fixed, thanks @andrewvc
