### ISSUE TITLE
Metricbeat 7.12.1 kubernetes.container.memory.usage.limit.pct is calculated incorrectly

### ISSUE THREAD

**Issue by F-Potter** [elastic/beats#25657]
Hi,

Metricbeat is providing the kubernetes.container.memory.usage.limit.pct value by obtaining the memory.max_usage_in_bytes (which can be divined by setting a resource memory limit in the kubernetes deployment) and dividing it by the kubernetes.container.memory.usage.bytes.

While kubernetes is OOM killing containers based on the kubernetes.container.memory.workingset.bytes. Meaning that the kubernetes.container.memory.usage.limit.pct currently is not a good value to have alerting on, since the kubernetes.container.memory.usage.bytes is higher than the kubernetes.container.memory.workingset.bytes and giving false positives that the container is almost OOM killed, while in reality it is still okay, until the kubernetes.container.memory.workingset.bytes is reaching the resource memory limit.

Is it possible to adjust the kubernetes.container.memory.usage.limit.pct based on the kubernetes.container.memory.workingset.bytes?

**Comment by jsoriano** [comment]
Hi @F-Potter,

`kubernetes.container.memory.workingset.bytes` is only greater than zero in Windows, are your affected nodes running in Windows?

If that is the case, I guess this is similar to the issue with pods, solved by https://github.com/elastic/beats/pull/25428.

**Comment by F-Potter** [comment]
Hi @jsoriano,

No the affected nodes are all Ubuntu 18.04.5 LTS

**Comment by F-Potter** [comment]
![Screenshot 2021-05-11 at 13 44 23](https://user-images.githubusercontent.com/9828931/117809979-1f32eb00-b25f-11eb-8507-25eaba6464c5.png)

**Comment by F-Potter** [comment]
@brianharwell will look at it, not sure if it stops at 100% or goes over it, but the issue is more that the wrong value is measured, since k8s is looking at the kubernetes.container.memory.workingset.bytes. So monitoring a different value will result in a different percentage which results in wrong alerting

**Comment by F-Potter** [comment]
The limit.pct stops at 1 (100%), so won't get higher than that.
