### ISSUE TITLE
[Agent] The Agent shows as offline sometimes in the Kibana UI, even though it may still be online

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#25667]
For confirmed bugs, please report:
- Version: 7.13 BC4 and latest 7.13 Snapshot / 8.0 snapshot

- Operating System: linux / windows / macOS

- Steps to Reproduce: 
TBD, not sure what causes it or what the timing is, but if you monitor an Agent over an hour or more it seems to go offline and then come back.

I'm logging this as it has been seen and discussed in slack and we'll want to find a case evidencing this and gather all relating logs etc.

**Comment by EricDavisX** [comment]
@ph @ruflin @mostlyjason should we bump this to 'critical' for 7.13 or no?

**Comment by EricDavisX** [comment]
I only meant 'looking at the Agent details page', PH.

In discussion with PH and Jen we are assessing if this is a resource constraint problem.  The memory + CPU are quite small on the Linux hosts (Fleet Server is separate) as a GCP -micro resoruce.  Due to improved reporting on the Fleet Server side, this issue may be surfacing now, when it didn't in the past.

We need to confirm this theory and feel confident about it.

**Comment by ph** [comment]
@blakerouse Could that be a possible explanation for the inconsistent behavior like stuck in unenrolling, or offline / online state changes? Is that possible, if this is possible could you test that possibility?

**Comment by blakerouse** [comment]
@EricDavisX have you ruled out that an error is not occurring on the Elastic Agent and it is reporting an error to Kibana and that is why it is showing unhealthy? Do you have the logs from the host showing this behavior?

**Comment by EricDavisX** [comment]
I don't have logs, we need to gather them.  We have several systems showing this off, one is behind Endgame VPN, one is behind Elastic vault credentials in our main demo setup.  I will circle back to this after other follow-ups in progress.  We were hoping to pull in more folks to test (don't want to put all research on your shoulders or Michal's).  Let's see if anyone has time, and I"ll work this after the other urgent ones I'm hitting.

**Comment by EricDavisX** [comment]
I'm going to leave an Agent running for a bit and see what comes, but with BC5 tested with a self-managed Fleet Server host I'm not seeing this.  Let's hope it is gone.  I'll report back

**Comment by EricDavisX** [comment]
ok, looks like it is passing.  several days later the Agents I stood up are still there and ok and healthy.

I'd like to ask @dikshachauhan-qasource and @amolnater-qasource to run a test against BC6 and leave an Agent running for a few hours to re-test it.  I'm closing it for now to clear out the list of Blockers though.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this issue with agents installed on 7.13 BC-6 cloud-qa environment and found it not reproducible.
We have kept the agents for 6 hours and they all remained "Healthy" throughout.

**Build details:**
```
Build: 40852
Commit: 1ce2632ae192b3b41f6eef4625b97b18971a4864
Artifact link: https://staging.elastic.co/7.13.0-40b6b79a/downloads/beats/elastic-agent/elastic-agent-7.13.0-windows-x86_64.zip
```
Further we had few agents installed from past 24 hours on 7.13 Snapshot(staging) Kibana environment and they were also in "Healthy" state.

Please let us know if we are missing anything
Thanks
QAS
