### ISSUE TITLE
Revert code from the Licenser for APM-Server

### ISSUE THREAD

**Issue by ph** [elastic/beats#25672]
APM-Server was using code inside the **Licenser** to check if the remote cluster had a platinum license.

https://github.com/elastic/apm-server/blob/b0cd96dcd1989c655969b96f492ae1ecc252c48c/x-pack/apm-server/main.go#L100-L104

```go
    checkPlatinum := licenser.CheckLicenseCover(licenser.Platinum)
    licenser.Enforce("apm-server", func(logger *logp.Logger, license licenser.License) bool {
        logger.Infof("Checking license for tail-based sampling")
        return checkPlatinum(logger, license) || licenser.CheckTrial(logger, license)
    })
```

When we merged the PR https://github.com/elastic/beats/pull/25351 we actually broke a feature inside APM, they use code to verify the remote version of the cluster. The PR removed code that we though was unnecessary but was used.

**Comment by axw** [comment]
I don't think we necessarily need to revert, as I don't think the implementation we had was ideal. What we need is to be able to check the license level is Platinum+ and dynamically enable/disable a specific feature. We can still do that after the changes in https://github.com/elastic/beats/pull/25351.

**Comment by simitt** [comment]
fixed in https://github.com/elastic/apm-server/pull/5252
