### ISSUE TITLE
[Agent]: Microsoft Module (ATP) keeps showing permission errors

### ISSUE THREAD

**Issue by btvmunoz** [elastic/beats#25670]
Filebeat 7.11, Microsoft Module
OS: Ubuntu
Steps to Reproduce:
- Enabled Microsoft module after doing the configuration
- Per the documentation the permissions required have been given
- All permissions added to confirm if this is the issue
- Verifying through Journalctl reveals that it still requires permissions even though it has all of them

![image](https://user-images.githubusercontent.com/37713049/117864094-467ebd80-b249-11eb-883d-82fc2d0f4a50.png)
![image](https://user-images.githubusercontent.com/37713049/117864571-cf95f480-b249-11eb-87d4-5a23d9e708c3.png)

**Comment by jamiehynds** [comment]
@P1llus have you come across any similar permission errors with ATP in the past?

**Comment by cakarlen** [comment]
Commenting here to stay up to date on this issue. Currently preventing workflows related to pulling events from M365 API endpoints

**Comment by P1llus** [comment]
Hllo @cakarlen, Microsoft decided to modify some of their audit flow, there is a PR merged for this now: https://github.com/elastic/beats/pull/24829, I will merge a similar one for Agent as well.

**Comment by btvmunoz** [comment]
@P1llus I just got an e-mail from Microsoft about a value change on the OS Architecture field, while I know this was originally opened because of an authentication issue I am wondering if the change will have any impact on the Microsoft module?

**Comment by eduardoarreolabt** [comment]
I experience the same permission error on Filebeat v.7.11 and have upgraded to version 7.14 but I received a new error 
![Filebeat error](https://user-images.githubusercontent.com/88786866/129054347-cb099073-24f7-4dc4-923d-b7639658bf31.PNG)

**Comment by eduardoarreolabt** [comment]
recently update my var.oauth2.token_url in the Microsoft defender_atp module and the error is regarding "oauth2: cannot fetch token: 400 Bad Request"
![Filebeat error (2)](https://user-images.githubusercontent.com/88786866/129058105-60fc9e42-b386-463a-95ce-f78045a703dd.PNG)

**Comment by tmrt22** [comment]
I am experiencing the same issue. I followed the microsoft documentation step by step. But it is not working. Even if I try to connect via curl i get the same error message (401: Unauthorized).

One of our azure experts told me that the authentication via client id & secret is not sufficient anymore to access the security center.

https://m365log.com/apps-365/oauth-interface-for-office-365-reporting-web-service/

An alternative would be using app id & app secret oder using the graph API.
