### ISSUE TITLE
[ECS] Upgrade modules to ECS 1.10

### ISSUE THREAD

**Issue by P1llus** [elastic/beats#25734]
Updating all modules to ECS 1.10 after release

**New fields:**
Datastream: https://github.com/elastic/ecs/blob/master/rfcs/text/0009-data_stream-fields.md

**Beta fields:**
Orchestrator: https://github.com/elastic/ecs/blob/master/rfcs/text/0012-orchestrator-field-set.md

**Experimental:**
Threat fields: https://github.com/elastic/ecs/blob/master/rfcs/text/0018-extend-threat-group-software.md

**Comment by andrewkroh** [comment]
We should consider adding an alias where `data_stream.dataset` -> `event.dataset`. It may help ease the transition (way) later when apps and rules remove support for querying both `event.dataset` and `data_stream.dataset` (currently we are making apps/rules work with data that has either field, but the long term plan is to only use the `data_stream.dataset`). Then older data you had indexed with Beats can continue to be queried by apps and rules.

**Comment by P1llus** [comment]
Related modules:

**Libbeat:**
- [ ] Global ECS file update

**Journalbeat**
- [ ] Update ECS mapping

**Metricbeat**
_OSS_
- [ ] aerospike
- [ ] apache
- [ ] beat
- [ ] ceph
- [ ] consul
- [ ] couchbase
- [ ] couchdb
- [ ] docker
- [ ] dropwizard
- [ ] elasticsearch
- [ ] envoyproxy
- [ ] etcd
- [ ] golang
- [ ] graphite
- [ ] haproxy
- [ ] http
- [ ] jolokia
- [ ] kafka
- [ ] kibana
- [ ] kubernetes
- [ ] kvm
- [ ] linux
- [ ] logstash
- [ ] memcached
- [ ] mongodb
- [ ] munin
- [ ] mysql
- [ ] nats
- [ ] nginx
- [ ] php_fpm
- [ ] postgresql
- [ ] prometheus
- [ ] rabbitmq
- [ ] redis
- [ ] system
- [ ] traefik
- [ ] uwsgi
- [ ] vsphere
- [ ] windows
- [ ] zookeeper

**X-Pack**
- [ ] activemq
- [ ] appsearch
- [ ] aws
- [ ] awsfargate
- [ ] azure
- [ ] cloudfoundry
- [ ] cockroachdb
- [ ] coredns
- [ ] gcp
- [ ] ibmmq
- [ ] iis
- [ ] mssql
- [ ] openmetrics
- [ ] oracle
- [ ] prometheus
- [ ] redisenterprise
- [ ] sql
- [ ] stan
- [ ] statsd
- [ ] tomcat

**Filebeat:**
_OSS:_
- [ ] Apache2
- [ ] auditd
- [ ] elasticsearch
- [ ] haproxy
- [ ] icinga
- [ ] iis
- [ ] kafka
- [ ] kibana
- [ ] logstash
- [ ] mongodb
- [ ] mysql
- [ ] nats
- [ ] nginx
- [ ] osquery
- [ ] pensando
- [ ] postgresql
- [ ] redis
- [ ] santa
- [ ] system
- [ ] traefik

_X-Pack:_
- [ ] activemq
- [ ] aws
- [ ] awsfargate
- [ ] azure
- [ ] barracuda
- [ ] bluecoat
- [ ] cef
- [ ] checkpoint
- [ ] cisco
- [ ] coredns
- [ ] crowdstrike
- [ ] cyberark
- [ ] cyberarkpas
- [ ] cylance
- [ ] envoyproxy
- [ ] f5
- [ ] fortinet
- [ ] gcp
- [ ] google_workspace
- [ ] googlecloud
- [ ] gsuite
- [ ] ibmmq
- [ ] imperva
- [ ] infoblox
- [ ] iptables
- [ ] juniper
- [ ] microsoft
- [ ] misp
- [ ] mssql
- [ ] mysqlenterprise
- [ ] netflow
- [ ] netscout
- [ ] o365
- [ ] okta
- [ ] oracle
- [ ] panw
- [ ] proofpoint
- [ ] rabbitmq
- [ ] radware
- [ ] snort
- [ ] snyk
- [ ] sonicwall
- [ ] sophos
- [ ] squid
- [ ] suricata
- [ ] threatintel
- [ ] tomcat
- [ ] zeek
- [ ] zookeeper
- [ ] zoom
- [ ] zscaler

**Auditbeat:**
- [ ] auditd
- [ ] file_integrity
- [ ] host
- [ ] login
- [ ] package
- [ ] process
- [ ] socket
- [ ] user

**Comment by andrewstucki** [comment]
Heartbeat, Winlogbeat and OSQuerybeat should likely also be updated. Heads up that you'll also need to update the default ECS version in each beat, in case a module doesn't explicitly set it (such as [here](https://github.com/elastic/beats/blob/9e5aafded2c49d19ee00a5d63b6ef5f6aad5ffaa/x-pack/metricbeat/cmd/root.go#L34)), the various test fixtures, and then also regenerate the embedded field yml files and docs for each beat after you globally update the shared ECS field definitions.

**Comment by P1llus** [comment]
Will update the issue accordingly, thanks @andrewstucki !

**Comment by andrewstucki** [comment]
One more thing, as we discussed yesterday, there may be a few places that might be worth adding in the `orchestrator` fields. I'm thinking that we may specifically want to consider taking a look at the autodiscover code and the `add_*_metadata` processors. Specifically seeing if the following make sense to update:

[Kubernetes Autodiscover](https://github.com/elastic/beats/tree/master/libbeat/autodiscover/providers/kubernetes)
[Kubernetes Metadata Processor](https://github.com/elastic/beats/tree/master/libbeat/processors/add_kubernetes_metadata)
[Nomad Autodiscover](https://github.com/elastic/beats/tree/master/x-pack/libbeat/autodiscover/providers/nomad)
[Nomad Metadata Processor](https://github.com/elastic/beats/tree/master/x-pack/libbeat/processors/add_nomad_metadata)

The other module/filesets that we might want to just ping the observability folks on to get their take are for fargate and kubernetes from what I can tell.

**Comment by P1llus** [comment]
> One more thing, as we discussed yesterday, there may be a few places that might be worth adding in the `orchestrator` fields. I'm thinking that we may specifically want to consider taking a look at the autodiscover code and the `add_*_metadata` processors. Specifically seeing if the following make sense to update:
> 
> [Kubernetes Autodiscover](https://github.com/elastic/beats/tree/master/libbeat/autodiscover/providers/kubernetes)
> [Kubernetes Metadata Processor](https://github.com/elastic/beats/tree/master/libbeat/processors/add_kubernetes_metadata)
> [Nomad Autodiscover](https://github.com/elastic/beats/tree/master/x-pack/libbeat/autodiscover/providers/nomad)
> [Nomad Metadata Processor](https://github.com/elastic/beats/tree/master/x-pack/libbeat/processors/add_nomad_metadata)
> 
> The other module/filesets that we might want to just ping the observability folks on to get their take are for fargate and kubernetes from what I can tell.

Yeah for sure, I looked over the security integration modules first, and didn't find any that needed updates for this yet. For the Obs based ones there is a meeting planned this week to go through them and see what we find.

Thanks for the list, makes it a lot easier for me as well! :)
