### ISSUE TITLE
[Endpoint Test tracking issue on upgraded 7.13]: Need to validate uninstallation of Endpoint folder that caused trouble while reinstalling agent on inactive hosts

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#25737]
While performing testing around 7.13 kibana build, we had come up in a state where an Endpoint folder left stranded on a host [having 7.12.1 agent with Endpoint] that became inactive after Kibana upgrade from 7.12.1 to 7.13.

After kibana upgrade, we  7.12.1 agent went into inactive state as expected, so when we tried to re-install agent on same host, we attempted to uninstall existing agent first using elastic-agent uninstall command. On attempting, we noticed that:
- Agent was uninstalled.
- however, endpoint did not uninstalled along with agent [Reference ticket: https://github.com/elastic/beats/issues/21870]

Further, we when attempted to uninstall endpoint with agent at 7.13 agent, it worked fine.

So, we wanted to confirm here, if it is expected for 7.12.1 or lower agents that went to inactive state after Kibana upgrade. 

QUERY:
For reinstallation of agents on same host after kibana upgrade, do we need to uninstall endpoint first and then agent?

We wanted to confirm above because, (In case) if we don't uninstall endpoint first THEN, installed Endpoint is left in stranded state, hence blocking user to reinstall agent on same endpoint.

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned @EricDavisX

**Comment by EricDavisX** [comment]
@ruflin @ph @jen-huang  this seems a blocker for 7.13 - @ferullo fyi.  I don't know what action is called during the upgrade to unenroll / uninstall Agent (and which should uninstall Endpoint), but this may be the same or related to https://github.com/elastic/fleet-server/issues/244
@nchaulet do you know?

**Comment by ph** [comment]
@EricDavisX @ferullo @ruflin Could we document this for 7.13, is that a possibility?

**Comment by ferullo** [comment]
I don't quite understand what the bug is.

I read this bug to say that when a 7.12.1 (Agent with Endpoint) failed to upgrade to 7.13.0 it left Endpoint stranded on the computer. Is that right? That seems expected to me, since 7.12.1 Agent doesn't uninstall Endpoint. If 7.13.0 didn't get onto the computer then no Agent code that would uninstall Endpoint was ever run.

**Comment by dikshachauhan-qasource** [comment]
Hi @ferullo 

`it left Endpoint stranded on the computer. Is that right? `

No after upgrade, all agent went to inactive state. And suppose, if we want to re-enroll agents on same host so in that case I had questions:

` For reinstallation of agents on same host after kibana upgrade, do we need to uninstall endpoint first and then agent?`
Here, **if I directly uninstall agent** having endpoint, what happens is as below:

- Agent gets uninstalled 
- however, Endpoint left in stranded state on the host. [Blocking us to re-install agents on them]

So, I need a confirmation here for hosts, how to handle them while reinstallation of agent on same hosts is required, that were having Endpoint Security  integration installed earlier on them.

**Comment by ferullo** [comment]
Ok. You should be able to remove Endpoint when you get into this situation to unblock a new agent installation by doing the below steps. Does that work around the issue?

Regarding whether this a blocker or not, I'll defer to @ph . It seems like this is just the same behavior as prior to 7.13? So there's no new bug, just a bug fix that's buggy?

These steps will remove Endpoint:
```
cp c:\Program Files\Elastic\Endpoint\elastic-endpoint.exe %TEMP%\elastic-endpoint.exe
%TEMP%\elastic-endpoint.exe uninstall
del %TEMP%\elastic-endpoint.exe
```

**Comment by ruflin** [comment]
At the moment, I would not consider this a blocker. But we should further investigate what the actual issue / bug is to fully understand it. In parallel, test and document what @ferullo provided above.

**Comment by ferullo** [comment]
I'm not sure where, but I know @kevinlog has coordinated documentation of those steps to remove an orphaned Endpoint. Kevin, where is that documentation going? Does it already document this too?

**Comment by EricDavisX** [comment]
I believe an Endpoint over-install will not work if / when users migrate from 7.12.x to 7.13 and want to enroll with Fleet Server and then set Endpoint back into any policies - uers will have to run the uninstall steps noted.

I acknowledge we can document around this, and indeed if we are relying on the prior version (currently installed) Agent code for the un-install, there is little we can reasonably do.

**Comment by EricDavisX** [comment]
are we in agreement that we can set up the same case and test and upgrade of 7.13 to 7.14 to validate this?  @dikshachauhan-qasource  if that works we can close this out.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We are able to uninstall endpoint with agent uninstall. Hence wont be a problem while upgrade test of 7.13 to 7.14. So we are closing this out.

Thanks for all the discussion.
