### ISSUE TITLE
Build cloud docker images in upstream repo

### ISSUE THREAD

**Issue by simitt** [elastic/beats#25755]
The cloud docker images should be built directly in the upstream repositories for `>=8.0`. This mainly requires adding metricbeat and filebeat processes to the docker image. 

cc @urso

**Comment by drewr** [comment]
Hi @simitt, thanks for the issue! Do you know if the team has a rough time window when this would be able to be worked?

**Comment by simitt** [comment]
referring to @urso for more information/timeline on this.

**Comment by simitt** [comment]
@andresrc this will be required from `>= 8.0`.

**Comment by cachedout** [comment]
@simitt Thanks for tracking this. When I look at [the description here](https://github.com/elastic/cloud/issues/81254#issue-889813889) this tracking issue is supposed to be for both Elastic Agent and APM Server.

However, I suspect that you're likely just tracking the Elastic Agent piece of that, correct? If so, I think we might need to track the APM Server piece separately. Please let me know if that aligns with your understanding and I'll open a separate issue for APM Server if so. Thanks!

**Comment by simitt** [comment]
With recent changes, ESS/ECE runs the elastic-agent docker image when an `apm` deployment is created. (The Elastic Agent has the APM Server binary bundled which is used to run APM Server on cloud). There won't be any dedicated apm-server docker image for cloud moving forward.

**Comment by cachedout** [comment]
Ah, I didn't know that. Makes sense. Thanks!

**Comment by v1v** [comment]
https://github.com/elastic/beats/pull/28134 has been merged now therefore this particular issue can be closed as done.

Thought, there are still some changes needed to be done in the Unified Release process, but those changes will be tackle in some other follow ups. The meta issue will contain those references.

Cheers
