### ISSUE TITLE
[Bug] Osquerybeat: Osqueryd binary on linux doesn't have executable permissions out of the box

### ISSUE THREAD

**Issue by aleksmaus** [elastic/beats#25762]
The osquerybeat package for linux contains the osqueryd binary that doesn't have executable permissions

```
-rw-r--r-- 1 root root 45460912 May 18 12:37 osqueryd
```

which causes osquerybeat to fail to run osqueryd as a child process:
```
{"log.level":"error","@timestamp":"2021-05-18T12:38:47.368Z","log.logger":"osquerybeat","log.origin":{"file.name":"beater/osquerybeat.go","file.line":173},"message":"Failed to start osqueryd process: fork/exec /opt/Elastic/Agent/data/elastic-agent-64ec73/install/osquerybeat-7
.13.0-SNAPSHOT-linux-x86_64/osqueryd: permission denied","ecs.version":"1.6.0"}
```

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu tested)

**Comment by lloydmeta** [comment]
https://github.com/elastic/beats/pull/25760 was merged, so I'm guessing this can be closed?

**Comment by aleksmaus** [comment]
Closing, this been addressed long time ago.
