### ISSUE TITLE
Beats fail to setup indices with 7.13 if .fleet-actions-results datastream is created

### ISSUE THREAD

**Issue by aleksmaus** [elastic/beats#25770]
This issue was originally reported in https://github.com/elastic/kibana/issues/100019

The repro steps on clean Elasticsearch 7.13:

```
curl -X POST -u elastic:changeme "localhost:9200/.fleet-actions-results/_doc" -H 'Content-Type: application/json' -H 'X-elastic-product-origin: fleet' -d'{}'
```

```
curl -u elastic:changeme "localhost:9200/_alias/auditbeat-7.13.0"  
```

Returns an error:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Data stream(s) [.fleet-actions-results] use and access is reserved for system operations"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "Data stream(s) [.fleet-actions-results] use and access is reserved for system operations"
  },
  "status" : 400
}
```

The impact:
The beats indices setup will fail after the first document is pushed into ```.fleet-actions-results``` datastream.

This seems to be a regression caused by the addition of the fleet system datastream with the fleet system index plugin, and would have to be addressed on ES side. Opened this issue in beats repository as requested for tracking purposes.

**Comment by ruflin** [comment]
Thanks for tracking this down @aleksmaus . As it turns out, this is a bug in Elasticsearch: https://github.com/elastic/elasticsearch/issues/73218 I'm going to close this issue as I think there is unfortunately not much we can do on the Beats side here :-(
