### ISSUE TITLE
[Heartbeat] Synthetics should be on blocklist for plain heartbeat

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#25775]
Per https://github.com/elastic/beats/issues/22932#issuecomment-841301435 , we should add synthetics to the block list for agents that do not include the synthetics capability (meaning browser deps). Without this the upcoming integrations UI for synthetics will have problematic use cases as outlined in the link above; namely that users will be able to apply the integration to a group of agents that may not be capable of actually executing synthetics.

**Comment by paulb-elastic** [comment]
This isn't the right solution, instead focusing on https://github.com/elastic/beats/issues/27366
