### ISSUE TITLE
[Agent] Non-Fleet-Server Agent is shown as stuck in 'updating' state when unenrolled via UI

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#25773]
Testing with BC6 of Elastic Agent and Kibana code from from May 14 (via Elastic Cloud deploy) I can confirm that Agent does not get removed from the UI when you unenroll it.   This is just a normal Agent, not a fleet server.

Kibana details:
edavis-mbp:kibana_elastic edavis$ git show -s 1ce2632ae192b3b41f6eef4625b97b18971a4864
commit 1ce2632ae192b3b41f6eef4625b97b18971a4864
Date:   Fri May 14 14:14:48 2021 -0400

relating error logs from Agent at time of unenroll:
{"log.level":"debug","@timestamp":"2021-05-18T16:06:56.799-0400","log.origin":{"file.name":"dispatcher/dispatcher.go","file.line":95},"message":"Failed to dispatch action 'action_id: 5ed337ce-9445-48bb-a671-966f941fddd3, type: UNENROLL', error: acknowledge 1 actions '[action_id: 5ed337ce-9445-48bb-a671-966f941fddd3, type: UNENROLL]' for elastic-agent 'cc474816-28b1-4537-9093-ded3aaf77f4c' failed: status code: 400, fleet-server returned an error: BadRequest","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-05-18T16:06:56.799-0400","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: acknowledge 1 actions '[action_id: 5ed337ce-9445-48bb-a671-966f941fddd3, type: UNENROLL]' for elastic-agent 'cc474816-28b1-4537-9093-ded3aaf77f4c' failed: status code: 400, fleet-server returned an error: BadRequest","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2021-05-18T16:06:56.800-0400","log.origin":{"file.name":"status/reporter.go","file.line":200},"message":"'gateway-a15f03b0' has status 'error'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-05-18T16:06:56.800-0400","log.origin":{"file.name":"status/reporter.go","file.line":236},"message":"Elastic Agent status changed to: 'error'","ecs.version":"1.6.0"}

full log attached, debug level:
[unenroll-hangs.log](https://github.com/elastic/beats/files/6504225/unenroll-hangs.log)

UI screenshot, state:
![Screen Shot 2021-05-18 at 4 20 01 PM](https://user-images.githubusercontent.com/12970373/118718239-01ccc680-b7f5-11eb-9a10-1d9faa0d9273.png)

...which shows that the Agent is still communicating with Fleet Server - this is startling.

The Agent process is still running
<img width="655" alt="Screen Shot 2021-05-18 at 4 21 51 PM" src="https://user-images.githubusercontent.com/12970373/118718542-5cfeb900-b7f5-11eb-97c0-15d15925c899.png">

it seems to be in a  bad state where the agent binary is removed, but other files are still in place

[root@mainqa-atlcolo-10-0-6-147 elastic-agent-7.13.0-linux-x86_64]# ls -l /opt/Elastic/Agent/
total 8504
drwxrwxr-x. 4 root root      63 May 18 16:00 data
-rw-------. 1 root root    1743 May 18 16:00 elastic-agent-20210518160019
-rw-------. 1 root root     143 May 18 16:00 elastic-agent-20210518160020
-rw-------. 1 root root    5944 May 18 16:01 elastic-agent-20210518160021
-rw-------. 1 root root   60313 May 18 16:22 elastic-agent-20210518160143
-rw-r--r--. 1 root root    9020 May 18 16:00 elastic-agent.reference.yml
-rw-------. 1 root root    1946 May 18 16:00 elastic-agent.yml
-rw-------. 1 root root    9017 May 18 16:00 elastic-agent.yml.2021-05-18T11-19-57.1287.bak
-rw-------. 1 root root     478 May 18 16:01 fleet.yml
-rw-------. 1 root root       0 May 18 16:00 fleet.yml.lock
-rw-r--r--. 1 root root   13675 May 18 16:00 LICENSE.txt
-rw-r--r--. 1 root root 8576604 May 18 16:00 NOTICE.txt
-rw-r--r--. 1 root root     863 May 18 16:00 README.md
[root@mainqa-atlcolo-10-0-6-147 elastic-agent-7.13.0-linux-x86_64]# elastic-agent version
/bin/elastic-agent: line 2: /opt/Elastic/Agent/elastic-agent: No such file or directory
[root@mainqa-atlcolo-10-0-6-147 elastic-agent-7.13.0-linux-x86_64]# ./elastic-agent version
Binary: 7.13.0 (build: 71251ef6233b52729c23013deef11d7f47ea1795 at 2021-05-14 23:06:47 +0000 UTC)

**Comment by EricDavisX** [comment]
@ruflin @ph @blakerouse @michalpristas fyi.

**Comment by EricDavisX** [comment]
more info after the unenroll is called.
Fleet.yml:

[root@mainqa-atlcolo-10-0-6-147 elastic-agent-7.13.0-linux-x86_64]# cat fleet.yml
agent:
  id: ab2e4fd5-34d2-4160-8590-c20f88387606
  monitoring.http:
    enabled: false
    host: ""
    port: 6791
fleet:
  enabled: true
  access_api_key: Rk4wUGdIa0IxNDdEeU9nVTZGNEc6b2VFOF9zcl9STlNnbjZVZXl2TTFCZw==
  protocol: https
  host: 10.0.6.208:8220
  timeout: 10m0s
  ssl:
    verification_mode: none
    renegotiation: never
  reporting:
    threshold: 10000
    check_frequency_sec: 30
  agent:
    id: ""

[root@mainqa-atlcolo-10-0-6-147 elastic-agent-7.13.0-linux-x86_64]# cat /opt/Elastic/Agent/data/elastic-agent-71251e/state.yml 
action:
  action_id: 5ed337ce-9445-48bb-a671-966f941fddd3
  action_type: UNENROLL
  is_detected: false
ack_token: 5ed337ce-9445-48bb-a671-966f941fddd3

**Comment by blakerouse** [comment]
In this case you got a BadRequest response from the Fleet Server. Something in the body of the HTML request the Fleet Server did not like. I have not seen this or been able to reproduce this (I have spent considerable amount of time trying to cause failures in UNENROLL with no success).

Best path forward here is for you to get the logs from the Fleet Server. It will include the actual reason on why it responded with a 400 error for the Ack.

**Comment by EricDavisX** [comment]
Retested with 7.13 BC8 Agent / Kibana code.  @blakerouse 

nothing on the fleet server side jumps out at me, I do see a 'failed to Ack' log line around the time of unenrolling the secondary agent at 16:27 ish.  
full logs zip and state.yml and fleet.yml from fleet server host is attached here:
[logs-fs-logs.zip](https://github.com/elastic/beats/files/6511423/logs-fs-logs.zip)

UI log capture for FS is below over the same (brief) timeframe.  These logs do not correlate in time with the prior logs attached, it was a separate reproduction.  happens every time on every host of mine, it seems.

```
16:14:20.148
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Error - could not start the HTTP server for the API: failed to listen on the named pipe \\.\pipe\default-fleet-server: open \\.\pipe\default-fleet-server: Access is denied.
16:14:20.148
elastic_agent.fleet_server
[elastic_agent.fleet_server][error] Fleet Server failed
16:14:22.149
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Starting
16:14:22.544
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Cluster Info
16:14:22.642
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] versions are compatible
16:14:23.035
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Cluster Info
16:14:23.036
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Checkin install limits
16:14:23.036
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Enroller install limits
16:14:23.036
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Artifact install limits
16:14:23.036
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Ack install limits
16:14:23.036
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] server listening
16:14:23.036
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] server hard connection limiter disabled
16:14:23.036
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] run policy monitor
16:14:23.036
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] start
16:14:23.037
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] start
16:14:23.603
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Running on policy with Fleet Server integration: a48f4980-b8d9-11eb-9906-65ccd138364f
16:14:24.436
elastic_agent.fleet_server
{"zap":{"level":"info","ts":1621455241.8390841,"name":"fleet-metrics.api","msg":"Starting stats endpoint"}
16:14:24.436
elastic_agent.fleet_server
,"@timestamp":"2021-05-19T20:14:01.839Z"}
16:14:24.436
elastic_agent.fleet_server
{"zap":{"level":"info","ts":1621455241.8390841,"name":"fleet-metrics.api","msg":"Metrics endpoint listening on: \\\\.\\pipe\\default-fleet-server (configured: npipe:///default-fleet-server)"}
16:14:24.436
elastic_agent.fleet_server
,"@timestamp":"2021-05-19T20:14:01.839Z"}
16:14:24.440
elastic_agent.fleet_server
{"zap":{"level":"info","ts":1621455260.1485424,"name":"fleet-metrics.api","msg":"Stats endpoint (\\\\.\\pipe\\default-fleet-server) finished: use of closed network connection"}
16:14:24.440
elastic_agent.fleet_server
,"@timestamp":"2021-05-19T20:14:20.148Z"}
16:14:24.440
elastic_agent.fleet_server
{"zap":{"level":"info","ts":1621455262.1501281,"name":"fleet-metrics.api","msg":"Starting stats endpoint"}
16:14:24.440
elastic_agent.fleet_server
,"@timestamp":"2021-05-19T20:14:22.15Z"}
16:14:24.440
elastic_agent.fleet_server
{"zap":{"level":"info","ts":1621455262.1501281,"name":"fleet-metrics.api","msg":"Metrics endpoint listening on: \\\\.\\pipe\\default-fleet-server (configured: npipe:///default-fleet-server)"}
16:14:24.440
elastic_agent.fleet_server
,"@timestamp":"2021-05-19T20:14:22.15Z"}
16:14:26.169
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] applying new local metadata
16:14:26.526
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] starting coordinator for policy
16:14:26.526
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] starting coordinator for policy
16:14:26.526
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] starting coordinator for policy
16:14:26.746
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] policy revised
16:14:26.746
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] no pending subscriptions to revised policy
16:14:26.746
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] new policy
16:14:26.748
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] new policy
16:14:29.178
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Running on policy with Fleet Server integration: a48f4980-b8d9-11eb-9906-65ccd138364f
16:20:38.713
elastic_agent.fleet_server
[elastic_agent.fleet_server][error] 
16:20:54.708
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] applying new local metadata
16:20:55.571
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Updating agent record to pick up default output key.
16:26:38.616
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Stopping
16:26:38.616
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Fleet Server exited
16:27:11.264
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] boot
16:27:11.266
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] environment
16:27:11.266
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] makeCache
16:27:11.268
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] Install signal handlers for SIGINT and SIGTERM
16:27:11.268
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] starting communication connection back to Elastic Agent
16:27:11.269
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] waiting for Elastic Agent to send initial configuration
16:27:13.609
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Running on policy with Fleet Server integration: a48f4980-b8d9-11eb-9906-65ccd138364f
16:27:15.513
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] applying new local metadata
16:27:15.869
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] Subscribed to action dispatcher
16:27:15.869
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] subscribed to policy monitor
16:27:16.227
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] starting coordinator for policy
16:27:16.227
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] starting coordinator for policy
16:27:16.227
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] starting coordinator for policy
16:27:16.440
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] policy revised
16:27:16.440
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] no pending subscriptions to revised policy
16:27:16.440
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] new policy
16:27:16.442
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] new policy
16:27:19.208
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Running on policy with Fleet Server integration: a48f4980-b8d9-11eb-9906-65ccd138364f
16:27:19.208
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] Policy self monitor exited
16:27:19.248
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] applying new local metadata
16:27:19.611
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] Subscribed to action dispatcher
16:27:19.611
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] subscribed to policy monitor
16:27:36.229
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] ensuring leadership of policies
16:27:59.068
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] ensuring leadership of policies
16:28:04.397
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] updated checkpoint
16:28:04.397
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] Unsubscribed from action dispatcher
16:28:07.685
elastic_agent.fleet_server
[elastic_agent.fleet_server][info] Fail ACK
16:28:09.748
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] Subscribed to action dispatcher
16:28:09.748
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] subscribed to policy monitor
16:28:21.408
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] ensuring leadership of policies
16:28:43.756
elastic_agent.fleet_server
[elastic_agent.fleet_server][debug] ensuring leadership of policies

```

**Comment by blakerouse** [comment]
@EricDavisX 

I found this in the log:

`
{"log.level":"info","error.message":"fail InvalidateAPIKey: [403 Forbidden] {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"action [cluster:admin/xpack/security/api_key/invalidate] is unauthorized for user [elastic/fleet-server] with roles [], this action is granted by the cluster privileges [manage_api_key,manage_security,all]\"}],\"type\":\"security_exception\",\"reason\":\"action [cluster:admin/xpack/security/api_key/invalidate] is unauthorized for user [elastic/fleet-server] with roles [], this action is granted by the cluster privileges [manage_api_key,manage_security,all]\"},\"status\":403}","code":400,"@timestamp":"2021-05-19T20:28:07.685Z","message":"Fail ACK"}
`

This makes me think the service token doesn't have the correct permissions.

**Comment by blakerouse** [comment]
This is an issue in elasticsearch - https://github.com/elastic/elasticsearch/issues/73278

**Comment by blakerouse** [comment]
Going to close this issue, as the real issue is on Fleet Server side - https://github.com/elastic/fleet-server/issues/380
