### ISSUE TITLE
[Question:] Usage of Fleet-server artifacts

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#25789]
While going through the package list available on 7.13 artifact link page, we have come across few Fleet server artifact packages.
Could anyone please confirm why Fleet server artifacts are available at staging artifact link. 
- What is the purpose of those package files.

Artifact link: https://staging.elastic.co/7.13.0-8eb98cbf/summary-7.13.0.html

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/118820273-be955500-b8d3-11eb-8611-e861542aef11.png)

**Comment by dikshachauhan-qasource** [comment]
@amolnater-qasource Please review

**Comment by amolnater-qasource** [comment]
Reviewed and Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@Conky5 @ph @ruflin can we have the quick chat... I don't know if there is much value in the Fleet Server binary being separately posted here.  And, further, I think it may be odd to expose it to a user if we were planning on doing so in any other public downloadable location.

Can you offer agreement or dissent PH / Ruflin?  And Conky can you cite intention for the shipped artifact?  Thanks.

Thanks @amolnater-qasource for raising it.

**Comment by Conky5** [comment]
Fleet server artifacts appearing in that report are an artifact of the build process, and can be ignored if they are not used. The fleet-server artifacts are built during one phase, then bundled into the agent in a downstream phase. The summary report displays all artifacts and so includes the fleet-server artifacts on their own.

Currently the fleet-server artifacts do go to the production download locations, for example https://artifacts.elastic.co/downloads/fleet-server/fleet-server-7.12.1-linux-x86_64.tar.gz, but there is no download page or other public documentation that links there as far as I am aware.

**Comment by ruflin** [comment]
As @Conky5 mentions, it is expected to show up on this page. No download links should show up in any public place. Going to close this issue.

**Comment by EricDavisX** [comment]
Thanks @Conky5 for offering up info so fast.  I'm glad it needs nothing more, I will plan on adding some internal team wiki docs or something that indicate we don't validate this artifact separately (for long term communication), and that they aren't very useful on their own, I hope that is obvious to users.  cheers.
