### ISSUE TITLE
Inconsistent ack metrics between elasticsearch and other output

### ISSUE THREAD

**Issue by spacewander** [elastic/beats#2579]
When testing with elasticsearch output, I find the metric `eventsNotAcked` is always zero, even in the situation sending all failed.

Hence I dig into the source and figure out the es output counts `eventsNotAcked` only after `sendErr` is nil:
https://github.com/elastic/beats/blob/master/libbeat/outputs/elasticsearch/client.go#L231

Quite strange, isn't it? This behaviour is different from the same metric in logstash or kafka, which counts `eventsNotAcked` after any sending failure happened.

**Comment by ruflin** [comment]
It seems like `sendErr` means the complete bulk request failed. It is possible that out of a bulk request, only few messages arrived. So there is a difference between connection failed and some acked failed. 

I see the point that in case the full request failed, we should also increase the counter with notAcked events as the user the above difference doesn't matter. @urso WDYT?
