### ISSUE TITLE
Cannot set name of Filebeat instance for Stack Monitoring with Metricbeat-based monitoring

### ISSUE THREAD

**Issue by kiju98** [elastic/beats#25800]
- Version: 7.11.1
- Operating System: Linux and macOS
- Discuss Forum URL:
- Steps to Reproduce: 
1. Run `filebeat-1` and `filebeat-2` on a server
2. Stack Monitoring shows 

<img alt="스크린샷 2021-05-18 오후 5 51 06" src="https://user-images.githubusercontent.com/25359646/118621766-a81ec900-b801-11eb-90b2-97b34b00a780.png">

where `Kijuui-MacBook2021.local` is the hostname of the server.

3. Try to set `name` to `filebeat-5066` and `filebeat-5067` for each Filebeat instance as 
[fllebeat-yml.zip](https://github.com/elastic/beats/files/6513279/fllebeat-yml.zip)

4. The names in Stack Monitoring don't change to `filebeat-5066` and `filebeat-5067` but stays as `Kijuui-MacBook2021.local`. The Metricbeat log and the Beats module configuration (beat-xpack.yml) is
[metricbeat.zip](https://github.com/elastic/beats/files/6513303/metricbeat.zip)

Please note that the Beat name change works as expected in Stack Monitoring with self-monitoring.

**Comment by matschaffer** [comment]
I'm pretty new to metricbeat based monitoring, but why do you have `monitoring.enabled: false` set here?

**Comment by matschaffer** [comment]
oh, I see. that's what https://www.elastic.co/guide/en/beats/filebeat/current/monitoring-metricbeat-collection.html has you do

**Comment by matschaffer** [comment]
I checked today that `name` works as expected when using the filebeat & metricbeat definitions found in https://github.com/elastic/kibana/tree/main/x-pack/plugins/monitoring/dev_docs/reference

![Screen Shot 2022-06-24 at 12 41 05](https://user-images.githubusercontent.com/690/175457580-4985ae12-7ef2-4c69-841f-90e020eb4555.png)

If you run into further trouble, I'd recommend opening it as a support case so we can debug specific deployment config in a non-public space.
