### ISSUE TITLE
[Metricbeat] Kubernetes Module of Metricbeat does not get metrics from Kubelet on Kubernetes 1.21.1

### ISSUE THREAD

**Issue by rdrgporto** [elastic/beats#25801]
- Version: Elastic Stack 7.9.2 & Kubernetes 1.21.1 
- Operating System: Ubuntu 18.04
- Discuss Forum URL: [Discuss URL](https://discuss.elastic.co/t/kubernetes-module-of-metricbeat-does-not-get-metrics-7-9-2-with-kubernetes-1-21-1/272996)

Hi, everyone

I have been testing with a new version of **Kubernetes**, in this case, **1.21.1**. I use **Metricbeat** in order to get metrics of **containers**, **pods** and **nodes** with [kubelet](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) and [kube-state-metrics](https://github.com/kubernetes/kube-state-metricsl).

With **Kubernetes 1.20.6**, I have not any issue. Nevertheless, with **Kubernetes 1.21.1**, **Metricbeat** is not be able to get metrics from **Kubelet**. I have found an issue on **Kubernetes** which talks about remove metrics on **Kubelet** : [Issue #68522 ](https://github.com/kubernetes/kubernetes/issues/68522).

Is there any workaround ? Will **Metricbeat** get metrics for **new Kubernetes versions** ?

I have attached a **.zip** ([kubernetes-module.zip](https://github.com/elastic/beats/files/6514274/kubernetes-module.zip)) with my **Metricbeat's deployment** on **Kubernetes** and an **example of JSON document from Elasticsearch**.

Thanks in advance,

Rodrigo

**Comment by ChrsMark** [comment]
Hi @rdrgporto ! 

I just checked the module (v7.9.3 of Metricbeat) on v1.21.1 using kind and it works fine from what I've seen so far.

Some questions for you:
1. Why you set `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` as the certificate? This file file most probably doesn't exit and since you setting `ssl.verification_mode: none` then there is no need for define a certificate.
2. What exactly do you see? I see you shared an event with zero values. Does Metricbeat fetches metrics from kubelet's api? Can you exec inside Metricbeat's Pod and run `export token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) && curl -H "Authorization: Bearer $token" https://$HOSTNAME:10250/stats/summary --insecure`, what do you see?
3. Also do you see anything interesting in Metricbeat's logs?


In general we have a full set of manifests we test and propose as base for our users so feel free to crosscheck yours with them: https://github.com/elastic/beats/blob/master/deploy/kubernetes/metricbeat-kubernetes.yaml


cc: @MichaelKatsoulis

**Comment by rdrgporto** [comment]
Hi @ChrsMark,

1. Sorry, my mistake 🙈.
2. I have run the command and it shows metrics about the pods. However, I have not metrics about **memory.availableBytes** and more metrics like **network**. 

I have attached a .zip ([kubelet-metrics.zip](https://github.com/elastic/beats/files/6707744/kubelet-metrics.zip)) in which you can compare metrics between **Kubernetes 1.20.6 and Kubernetes 1.21.1**. In both JSONs you can see metrics of **Kubernetes Dashboard**. 

[Kind](https://github.com/kubernetes-sigs/kind) tool deploy **Kubernetes with Docker or Containerd** ? I use **Docker in Kubernetes 1.20.6** and **Containerd in Kubernetes 1.21.1** because Docker is [deprecated](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/).

Thanks in advance

**Comment by MichaelKatsoulis** [comment]
Hi @rdrgporto !

Thanks for the reply.

Indeed kind only uses docker runtime. I tested with minikube with option  `minikube start --kubernetes-version=v1.21.1 --container-runtime=containerd` which betters simulates your environment.

I can still get all metrics from kubelet including memory and network stats. Here(
[kubernetes-1.21.1-containerd-1.4.6.json.zip](https://github.com/elastic/beats/files/6708896/kubernetes-1.21.1-containerd-1.4.6.json.zip)) you can see the output of the curl command.

Comparing the _json-example.json_ and _kubernetes-1.21.1.json_ that you attached I notice that as network and availableBytes stats information are not provided by kubelet in your setup metricbeat then fills the values with zero.

It does not look like an error on Metricbeat's side. Maybe something went wrong with your upgrade?
Do you have another environment to test(dev, staging) and reproduce this behaviour? 

Thanks in advance

**Comment by rdrgporto** [comment]
Hi, @MichaelKatsoulis 

I tested with **Minikube** and it worked. Nevertheless, I had to install **Docker** in order to launch **Minikube** ([drivers](https://minikube.sigs.k8s.io/docs/drivers/)).

I realised that when **Docker** is not installed in the machine, **Kubelet** does not get all metrics. So that, I installed **Kubernetes 1.21.1 with Docker** and it worked, **Kubelet** get all metrics. I guess that **Kubelet needs Docker** in order to get all metrics. However, this kind of behaviour is strange because **Docker is deprecated** and it will removed.

I attached two **markdowns** regarding my **Kubernetes installation** ([kubernetes-installation.zip](https://github.com/elastic/beats/files/6713983/kubernetes-installation.zip)).

Thanks in advance

**Comment by MichaelKatsoulis** [comment]
Hi @rdrgporto,

Out of curiosity I set up a Kubernetes cluster on GKE (Google Kubernetes Engine) version 1.21.1 with containerd
[gke-cluster-runtime.zip](https://github.com/elastic/beats/files/6726816/gke-cluster-runtime.zip)

I then performed a `curl`  to get Kubelet metrics and I actually got them all as you can see in the file.
[gke-1.21.1-containerd.json.zip](https://github.com/elastic/beats/files/6726881/gke-1.21.1-containerd.json.zip)


In that scenario Docker should not have ben used at all. As far as metricbeat is concerned it will parse all stats that kubelet reports. If kubelet does not report some of them then metricbeat will not be able to report these values too.. 

I took a look at your cluster configuration and didn't see anything that seemed wrong but again I am not the right person to judge. Maybe you could ask the Kubernetes team if they have an opinion on the matter.

If you don't have an objection I will go on and close this issue. 

Thanks in advance

**Comment by rdrgporto** [comment]
Hi, @MichaelKatsoulis 

Thank you very much 😃 . I am going to look over my Kubernetes installation and ask to Kubernetes community.

Regards
