### ISSUE TITLE
Disable useless HTML escaping when marshaling JSON

### ISSUE THREAD

**Issue by magnusbaeck** [elastic/beats#2581]
Go's HTML marshaler escapes ampersand and angle brackets by default, i.e.

```
{"message": "<b>hello world</b>"}
```

becomes this:

```
{"message": "\u003cb\u003ehello world\u003c/b\u003e"}
```

This is done to keep browsers from interpreting the JSON text as HTML, but that's hardly useful in the Beats case. Go 1.7 introduced an option to disable this kind of escaping (see [json.Encoder.SetEscapeHTML](https://golang.org/pkg/encoding/json/#Encoder.SetEscapeHTML)), and now that Beats has switched to Go 1.7 we might as well disable this behavior. This should have a marginally positive performance impact and could decrease the payload size at least when compression is disabled.

See also https://discuss.elastic.co/t/beats-encodes-angle-brackets-and-as-u003c-and-u003e-in-json-output/60667.

**Comment by christiangalsterer** [comment]
+1

**Comment by ruflin** [comment]
Anyone wants to open a PR for it? :-D

**Comment by lerencao** [comment]
+1

**Comment by andrewkroh** [comment]
Here's another Discuss issue where this led to confusion. https://discuss.elastic.co/t/filebeat-character-encoding-problem/136486

**Comment by monkkitarp** [comment]
+1 (data integrity)
