### ISSUE TITLE
Run yum update during the 6.8 build

### ISSUE THREAD

**Issue by joshbressers** [elastic/beats#25886]
When we build the 6.8 beats containers, we are not running yum update

The beats are self contained and do not use the operating system packages. Any updates not being installed do not pose a risk. Security scanners pick up these missing updates however, it is good practice to install them every time we build a container.

A workaround for anyone using the 6.8 container images is to manually run "yum update" within the container if they want all updated packages.

**Comment by joshbressers** [comment]
One extra note. We are running yum update on the 7.x line
https://github.com/elastic/beats/blob/9e5aafded2c49d19ee00a5d63b6ef5f6aad5ffaa/dev-tools/packaging/templates/docker/Dockerfile.tmpl#L33

This is only needed for 6.8

**Comment by urso** [comment]
Template for 6.8: https://github.com/elastic/beats/blob/6.8/dev-tools/packaging/templates/docker/Dockerfile.tmpl
