### ISSUE TITLE
PacketBeats: Record the request and response of transactions that cannot be identified by a valid protocol under tcp

### ISSUE THREAD

**Issue by manning23** [elastic/beats#25929]
I hope to record the request and response of transactions that cannot be identified by a valid protocol under tcp. :)

like this

- type: unknow-tcp
  enable: true
  send_request: true
  send_response: true

**Comment by manning23** [comment]
need help

**Comment by jsoriano** [comment]
Hey @manning23,

Could you please open a new topic in https://discuss.elastic.co? This is probably a better place for questions, we prefer to keep Github issues for confirmed bugs or enhancement requests.

Thanks!
