### ISSUE TITLE
Latest Heartbeat snapshot is not sending data to Elasticsearch

### ISSUE THREAD

**Issue by mdelapenya** [elastic/beats#25958]
@shahzad31 detected and notified that the edge cluster was not receiving Uptime data since yesterday.

We started an investigation and found that a deployment of the latest 8.0.0-SNAPSHOT for heartbeat fails to connect to ES:

>2021-05-27T10:12:48.403Z ERROR [publisher_pipeline_output] pipeline/output.go:154 Failed to connect to backoff(elasticsearch(https://REDACTED)): Connection marked as failed because the onConnect callback failed: failed to check for alias 'heartbeat-8.0.0': (status=400) {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Data stream(s) [.fleet-actions-results] use and access is reserved for system operations"}],"type":"illegal_argument_exception","reason":"Data stream(s) [.fleet-actions-results] use and access is reserved for system operations"},"status":400}: 400 Bad Request: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Data stream(s) [.fleet-actions-results] use and access is reserved for system operations"}],"type":"illegal_argument_exception","reason":"Data stream(s) [.fleet-actions-results] use and access is reserved for system operations"},"status":400}

**Comment by andrewvc** [comment]
@mdelapenya somehow we missed this, but can I ask if this is still happening? This would likely have been a libbeat issue, and if it was there is likely resolved by now.

**Comment by mdelapenya** [comment]
I'd double check with @shahzad31. If he agrees, yes, then we can close this one

**Comment by paulb-elastic** [comment]
@shahzad31 did you have a view on this?

**Comment by mdelapenya** [comment]
I think this is not relevant any more and can be closed for now
