### ISSUE TITLE
Helm install  metricbeat on minikube

### ISSUE THREAD

**Issue by jbrunetext** [elastic/beats#25966]
When i install metricbeat on minikuke a faced an issue in the logs :

Here : DNS lookup failure "minikube": lookup minikube on 10.96.0.10:53: no such host

For confirmed bugs, please report:
- Version: last one
- Operating System Container :  containerd
- Steps to Reproduce: 
1)  minikube start --cpus 4 --memory 6144  --kubernetes-version=v1.17.17 --container-runtime=containerd
wait for the cluster is ready 
2) install elasticsearch 
3) install kibana
4) install metricbeat
Set the Discover index pattern in kibana.

5) Display logs from pods : 
k -n monitoring logs metricbeat-metricbeat-vcvtx

the hostname must  host.minikube.internal and not just minikube.
maybe it will work

**Comment by jsoriano** [comment]
Hey @jbrunetext,

We try to keep github for bugs and enhancement requests, could you please open a topic in https://discuss.elastic.co/c/elastic-stack/beats/28 to continue discussing what could be happening?

If we confirm that this is an issue in Metricbeat, we can reopen this issue, or if it is an issue in the helm charts you can report it in https://github.com/elastic/helm-charts.

Thanks!
