### ISSUE TITLE
[SM] Add "roles" field in elasticsearch/node_stats metricsets

### ISSUE THREAD

**Issue by sayden** [elastic/beats#25968]
elasticsearch nodes exposes the roles that each of them has assigned, this information looks like this:

```json
[
  "data",
  "data_cold",
  "data_content",
  "data_frozen",
  "data_hot",
  "data_warm",
  "ingest",
  "master",
  "ml",
  "remote_cluster_client",
  "transform"
]
```

Those roles are also related to [Data Tiers](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/data-tiers.html) which is very useful information for a user. At the same time, we are now showing warning when the storage of a frozen node trespasses the [*high watermark level*](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/data-tiers.html) which is a expected situation as the frozen node won't move shards around.

Ideally, the roles should be added into a new field and SM UI use it to show more relevant information in Kibana about each node. The resulting `json` should be similar to:

```json
{
    "@timestamp": "2017-10-12T08:05:34.853Z",
    "elasticsearch": {
        "node": {
            "roles":[
                "data",
                "data_cold",
                "data_content",
                "data_frozen",
                "data_hot",
                "data_warm",
                "ingest",
                "master",
                "ml",
                "remote_cluster_client",
                "transform"
            ],
            "stats": {
                "indices": {
                    "docs": {
                        "count": 9207,
                        "deleted": 43
                    }
                }
            }
        }
    }
}
```

(Some fields have been omitted for brevity)

**Comment by sayden** [comment]
@henningandersen thanks for the heads up :slightly_smiling_face:

**Comment by sayden** [comment]
I opened a PR https://github.com/elastic/beats/pull/25988

**Comment by jlind23** [comment]
@sayden can we make this issue move forward? I saw your PR, is it ready to be merged?
