### ISSUE TITLE
Add upgrade guide for Beats

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#2604]
The beats platform does not currently provide an upgrade guide which is not consistent with the rest of the Elastic offerings.  This is to track the development of an upgrade guide that covers the upgrade process of each beat (eg. 1.x->1.x and 1.x->5.x).

@eskibars @pickypg @asawariS

**Comment by asawariS** [comment]
@ppf2 Beats team will be creating one for 5.0. See #1488. I have asked @tsg and @monicasarbu to share the early draft with us. Likely in the post beta1 timeframe.

**Comment by ppf2** [comment]
Thanks, will 1488 include a 1.x to 1.x upgrade guide?  If not, let's cover Beats 1.x->1.x as well even if it's a simple backup configs -> uninstall -> install new version just so that the end user will know what is involved :)

**Comment by tsg** [comment]
I this should be covered. @ppf2 let us know if there's any info missing.
