### ISSUE TITLE
Elastic-agent [Metricbeat] crashed on upgrading 7.13.1 snapshot agent to 7.14.0 Snapshot agent.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#26041]
**Kibana version:** 7.14.0 Snapshot Kibana cloud environment

**Host OS and Browser version:** Windows 10 x64, All

**Build Details:**
```
 Artifact link used: https://snapshots.elastic.co/7.13.1-e4c670b7/downloads/beats/elastic-agent/elastic-agent-7.13.1-SNAPSHOT-windows-x86_64.zip
 Build: 41361
 Commit: 66d63f384e775fe02799bd9a64b5f6353f123f30
```

**Preconditions:**
1. 7.14.0 Snapshot Kibana cloud environment should be available.
2. 7.13.1 Snapshot Agent must be installed with Default policy having System and Endpoint Security.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Upgrade 7.13.1 Snapshot Agent from Kibana UI 
3. Navigate to Logs tab and observe below errors:
```
16:01:23.452
elastic_agent
[elastic_agent][info] 2021-06-01T06:31:23-04:00 - message: Application: metricbeat--7.14.0-SNAPSHOT[285c3ffd-55cf-41f5-98a6-305362bc77ea]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
16:01:23.452
elastic_agent
[elastic_agent][info] 2021-06-01T06:31:23-04:00 - message: Application: metricbeat--7.14.0-SNAPSHOT[285c3ffd-55cf-41f5-98a6-305362bc77ea]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'
16:01:24.461
elastic_agent
[elastic_agent][error] Elastic Agent status changed to: 'error'
16:01:24.466
elastic_agent
[elastic_agent][info] Elastic Agent status changed to: 'online'
16:01:24.475
elastic_agent
[elastic_agent][error] 2021-06-01T06:31:24-04:00 - message: Application: metricbeat--7.14.0-SNAPSHOT[285c3ffd-55cf-41f5-98a6-305362bc77ea]: State changed to CRASHED: exited with code: 1 - type: 'ERROR' - sub_type: 'FAILED'
```
**Expected Result:**
7.13.1 snapshot agent should be upgraded to 7.14.0 Snapshot agent without any errors.

**Logs:**
[logs.zip](https://github.com/elastic/beats/files/6575580/logs.zip)
[logs2.zip](https://github.com/elastic/beats/files/6575582/logs2.zip)

**Screenshot:**
![9](https://user-images.githubusercontent.com/77374876/120310017-8c342080-c2f3-11eb-9b5f-ed250f9d4e15.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@michalpristas I assigned this to you for quick triage if not more.  let us know if you need more logs or what you think.  I'm adding it to the high-priority tracking list

**Comment by gerardnorton** [comment]
I also have this problem.
Metricbeat doesn't seem to find the API endpoint.

Error:
{"log.level":"info","@timestamp":"2021-06-02T07:59:58.933+0200","log.origin":{"file.name":"module/wrapper.go","file.line":259},"message":"Error fetching data for metricset beat.stats: error making http request: Get \"http://npipe/stats\": open \\\\.\\pipe\\default-endpoint-security: El sistema no puede encontrar el archivo especificado.","ecs.version":"1.6.0"}

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have upgraded 7.13.0 (shipped) agent on 7.13.1 Kibana cloud environment and found this issue **reproducible** there.
We observed that after upgrading 7.13.0 agent to 7.13.1, agent stucks in [Metricbeat] Starting-Restarting-Crash loop.

**Logs:**
[logs1.zip](https://github.com/elastic/beats/files/6598148/logs1.zip)
[logs2.zip](https://github.com/elastic/beats/files/6598151/logs2.zip)

**Screenshot:**
![13](https://user-images.githubusercontent.com/77374876/120795983-d1f12300-c557-11eb-9c6b-8f94c030c137.JPG)

Thanks
QAS

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have observed this issue **reproducible** on 7.13.2 BC-1 Kibana cloud environment.

**Observation:**
- On restarting elastic-agent (installed with policy having System and ES) from services, Metricbeat stuck under Starting-Restarting-Crashed loop.
- This issue is not observed when log level was set to "debug".

**Logs:**
[logs.zip](https://github.com/elastic/beats/files/6647058/logs.zip)

**Build details:**
Artifact Link: https://staging.elastic.co/7.13.2-d3092f38/downloads/beats/elastic-agent/elastic-agent-7.13.2-windows-x86_64.zip
Build: 40943
Commit: 288dada92621719c3e812310124f12e7824ee571

Thanks
QAS

**Comment by EricDavisX** [comment]
We confirmed this missed the 7.13.2 BC so it will need to be tested on 7.13.3 or 7.14

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We will retest this once 7.13.3 will be available.

However we have validated this issue on 7.14.0 Snapshot environment and found it **fixed** there.
Agent is installed with Default Policy having System and Endpoint Security.
- Agent remains healthy after reboot.
- All binaries come back in RUNNING state.
- No impact of changing log level to debug.

Further this issue is also not observed on 7.13.2 Snapshot Agent upgraded to 7.14.0 Snapshot Agent.

Build details:
```
Build: 41559
Commit: 9838db392e7fcfc12f004b68fb1b09739f131148
```
Hence we are closing this out.

Thanks
QAS
