### ISSUE TITLE
[Elastic-agent] Filebeat, required editing option for "exclude_files" in modul "system"

### ISSUE THREAD

**Issue by StefanSa** [elastic/beats#26113]
**Describe the enhancement:**

Currently in the elastic-agent, filebeat-module `system` defined as "exclude_files" `gz$`, but also need `xz$` as this is standard at SuSe / openleap.

So it would make sense to make `exclude_files` editable.

**Comment by P1llus** [comment]
To add to this, after some discussion on slack, it would be nice if the system integration/package would export the "exclude_files" part of the config template, so that more types can easily be excluded. This issue might need to move to elastic/integration, but we will see what people say.
