### ISSUE TITLE
[Filebeat][Cisco] Allow for TCP syslog input

### ISSUE THREAD

**Issue by BenB196** [elastic/beats#26118]
**Describe the enhancement:**
Allow the Filebeat Cisco syslog modules to use TCP

**Describe a specific use case for the enhancement or feature:**
Currently the Filebeat Cisco syslog modules are hard-coded to using UDP, however most Cisco equipment that can do syslog output, can be configured to use TCP. It would be ideal if you could switch between UDP and TCP input for the Cisco Filebeat syslog modules.

**Comment by legoguy1000** [comment]
@BenB196 The Nexus and Meraki fileset should allow you to choose `var.input: udp` currently.  I've updated ASA, FTD, IOS filesets in my branch that Im testing.
