### ISSUE TITLE
[Heartbeat] Add mappings for synthetics browser metrics

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/beats#26122]
+ Synthetics has added a new metrics like user timings, core vitals etc https://github.com/elastic/synthetics/pull/194, These fields have added to `root_fields` which does not have any mappings yet. 

We need to add mappings to all the fields exposed from the `journey/timings` data.

**Comment by justinkambic** [comment]
Checked mapping for these fields, looks ok.
