### ISSUE TITLE
Agent: enable setting headers for fleet

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#26137]
During enrollment we want to have an option to add custom headers used in output. 

These headers will be injected to elasticsearch output used by fleet server using elasticsearch client.

**Comment by ruflin** [comment]
This is one more feature where we mix local configs with configs coming from Fleet. It would be nice if we find a general pattern for these scenarios.

**Comment by ph** [comment]
@ruflin and @michalpristas  I need more details on this issue, does this affect both communication from Elastic Agent to Elastic Agent running fleet in cloud and Elastic agent sending events to Elasticsearch?

**Comment by ruflin** [comment]
@michalpristas Can this one be closed? As far as I can see, PR related to it has been merged.

**Comment by michalpristas** [comment]
i wanted to test it with cloud before closing, but  i guess if it does not work i will just create a bug
