### ISSUE TITLE
[Self-managed]: Upgraded Agent went offline after changing log level on Upgraded 7.14.0 Snapshot Kibana.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#26131]
**Kibana version:** 7.14.0 Snapshot upgraded from 7.13.0 self-managed Kibana environment

**Host OS and Browser version:** Windows 10 x64, All

**Build Details:**
```
  Artifact link used[7.13.0]: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.13.0-windows-x86_64.zip
  Build: 41403
  Commit: 4f0781737cdb5cf9b5dfa624368b4306b5d6bcb0
```

**Preconditions:**
1. Upgraded 7.14.0 Snapshot  self-managed  Kibana environment should be available.
2. 7.13.0 released Windows 10 x64 Fleet Server Agent must be installed with policy having System, Endpoint Security and Fleet Server integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. After Kibana upgraded to 7.14.0, upgrade existing 7.13.0 Fleet Server Agent to 7.14.0
3. After successful upgrade change logging level to debug.
4. Observe Agent debug level didn't change on Kibana UI and agent went "offline".

**Expected Result:**
Agent should remain healthy after upgrade and log level should be updated on Kibana UI.

**Logs:**
[logs.zip](https://github.com/elastic/beats/files/6591311/logs.zip)

**Note:**
- Debug level is updated in Fleet.yml
[fleet.zip](https://github.com/elastic/beats/files/6591327/fleet.zip)

**Screenshot:**
![Fleet](https://user-images.githubusercontent.com/77374876/120642447-80cb2b80-c492-11eb-83e1-96e4bc3befd1.jpg)

**Comment by amolnater-qasource** [comment]
@karanbirsingh-qasource Please review.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
This issue is similar to https://github.com/elastic/beats/issues/26034. However this reported issue is reproduced with different steps and on self-managed kibana.

So we reported this ticket for tracking this issue separately.

Thanks
QAS

**Comment by EricDavisX** [comment]
We think this is likely a duplicate to this issue: https://github.com/elastic/beats/issues/26041
 - let's track that and re-test this when it is confirmed in the build and has been backported.  i think that will be soon.  @amolnater-qasource

**Comment by amolnater-qasource** [comment]
Sure @EricDavisX, We will retest this issue whenever Metricbeat issue will be fixed.

Thanks
QAS

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 

We have revalidated this issue on 7.14.0 self-managed Snapshot Kibana and found it **fixed**.

**Build Details:**
```
Artifact link: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.13.1-windows-x86_64.zip
Build: 41559
Commit: 9838db392e7fcfc12f004b68fb1b09739f131148
```

**What's working:**
On changing log level agent remains "Healthy" and services like Filebeat and Metricbeat are in running state under logs tab.

Hence we are closing this out.

Thanks
QAS
