### ISSUE TITLE
libbeat/idxmgmt: alias creation fails when `setup.ilm.overwrite: true` and alias exists

### ISSUE THREAD

**Issue by axw** [elastic/beats#26142]
When ILM is enabled, libbeat will attempt to create a write alias. It does this by creating an index, and attempting to pointing the write alias to it:

https://github.com/elastic/beats/blob/dc576280f49baec169cd86f64a043cdc3d4fbab6/libbeat/idxmgmt/ilm/client_handler.go#L178-L208

If the _index_ already exists, Elasticsearch will return 400; libbeat then checks if the alias exists, and carries on without error if it does.

If the index does not exist (e.g. because it rolled over), but the _write alias_ exists and points to some other index, then Elasticsearch returns 500. In this case, libbeat fails index management setup with an error like (taken from apm-server):

> Index Alias apm-7.13.0-span setup failed: failed to create alias: {"error":{"root_cause":[{"type":"illegal_state_exception","reason":"alias [apm-7.13.0-span] has more than one write index [apm-7.13.0-span-000001,apm-7.13.0-span-000008]"}],"type":"illegal_state_exception","reason":"alias [apm-7.13.0-span] has more than one write index [apm-7.13.0-span-000001,apm-7.13.0-span-000008]"},"status":500}: 500 Internal Server Error: {"error":{"root_cause":[{"type":"illegal_state_exception","reason":"alias [apm-7.13.0-span] has more than one write index [apm-7.13.0-span-000001,apm-7.13.0-span-000008]"}],"type":"illegal_state_exception","reason":"alias [apm-7.13.0-span] has more than one write index [apm-7.13.0-span-000001,apm-7.13.0-span-000008]"},"status":500}.

**Comment by mfinelli** [comment]
I'm having the same issue when the initial index gets created on one day and then a beat agent restarts on a different day and tries to write to an index now named with the current day. As a temporary workaround I need to restart all of the beats so that they all try to write to the new day index and then I update the old index alias no no longer be a write index:

```
{"error":{"root_cause":[{"type":"illegal_state_ex
ception","reason":"alias [metricbeat-7.13.1] has more than one write index [metricbeat-7.13.1-2021.06.03-000001,metricbeat-7.13.1-2021.06.04-000001]"}],"type":"illegal_state_exception","reason":"a
lias [metricbeat-7.13.1] has more than one write index [metricbeat-7.13.1-2021.06.03-000001,metricbeat-7.13.1-2021.06.04-000001]"},"status":500}: 500 Internal Server Error: {"error":{"root_cause":
[{"type":"illegal_state_exception","reason":"alias [metricbeat-7.13.1] has more than one write index [metricbeat-7.13.1-2021.06.03-000001,metricbeat-7.13.1-2021.06.04-000001]"}],"type":"illegal_state_exception","reason":"alias [metricbeat-7.13.1] has more than one write index [metricbeat-7.13.1-2021.06.03-000001,metricbeat-7.13.1-2021.06.04-000001]"},"status":500}
```

```
PUT metricbeat-7.13.1-2021.06.03-000001/_alias/metricbeat-7.13.1
{
  "is_write_index": false
}
```
