### ISSUE TITLE
Kafka output - Use tcp proxy or http tunneling to connect filebeat to Kafka cluster

### ISSUE THREAD

**Issue by yaakov-berkovitch** [elastic/beats#26155]
Hello,

we have a requirement to use a tcp proxy or http tunneling between our machine on which we are running both filebeat and metricbeat and our Kafka cluster running in the cloud.

To do that we configure for example filebeat like below:
```
output.kafka:
  hosts:
  - tcp-proxy-ip:9094
```
We expected that the filebeat Kafka client will use the address configured in e/tc/filebeat/filebeat.yml to connect to the cluster and not the broker IPs returned from the metadata after the first connect to the cluster.
So, this behavior caused filebeat to failed connecting to the Kafka cluster because the broker IPs are not reachable from the filebeat machine.

BTW, in our Java based application that uses the apache Kafka client library it works as we expected: the Kafka client uses the address configured to access the Kafka cluster and not the brokers IPs returned in the metadata.

So, did we make wrong configuration to achieve this scenario ? Do you think it can/should work ?

Thanks

**Comment by jsoriano** [comment]
Hey @yaakov-berkovitch,

I think this is more a question about Kafka, but it may worth to investigate this.

In general, when clients connect to kafka, they receive a set of advertised addresses from the brokers, and they must reconnect to one of these addresses. In your case your kafka broker should be configured to advertise the `tcp-proxy-ip:9094` address. I am not sure if there is some other way to circunvent this. It'd be interesting to see what your Java clients are doing.

If clients can circunvent this and connect to any address, even if it is not advertised, I think this would actually simplify many things in metricbeat and its integration tests with Kafka.

**Comment by yaakov-berkovitch** [comment]
Finally, make it working.
I'm using chisel http tunnel, and the solution looks like this:
![image](https://user-images.githubusercontent.com/8049489/124783501-c9707b80-df4d-11eb-8af7-36f582fd4516.png)

I made it working by adding localhost to broker advertised addresses, and so filebeat can now use the same addresses as configured in the fileabeat.yml.

Below is the kafka output section from the filebeat.yml:
```
....
output.kafka:
  hosts:
   - localhost:19094
   - localhost:39094
   - localhost:29094
....
```
