### ISSUE TITLE
[Heartbeat] Make synthetics deps auto-download from container

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#26153]
we have had previous conversations about making a separate docker image for synthetics enabled agent. This has always been a non-optimal solution, and in this issue I propose we consider evaluating whether we can use dynamic downloading of synthetics dependencies instead.

We would still bundle heartbeat with the agent but the `yum` dependencies and node etc. would be downloaded on the first indication of the synthetics monitor. One hurdle to overcome would be the fact that those dependencies require the root user to be installed. This could be overcome by shipping a small setuid binary written in golang in the container that would invoke the `yum/dnf` command and do any other required work.

A downside of this approach would be that for on premises customers we would still need a separate image or they would need to make their own docker image that has this command invoked.

Perhaps we probably still need both images but the default image could do the dynamic download. We could call the larger image the `offline` version.

@paulb-elastic @mostlyjason @ruflin @drewpost @vigneshshanmugam @andresrc  WDYT?

**Comment by andresrc** [comment]
I have the gut feeling that we might need the two images anyway. From the installation point of view, Agent already runs with elevated privileges, so maybe the need would be for it to also be able to install dependencies. Not sure if we can consider that a good idea or not (security, etc.)

**Comment by mostlyjason** [comment]
I think this would be great because it would make it easier for users to adopt synthetics without having to reinstall a separate image. Installing dependencies on demand will reduce the size for 99%+ of hosts that are not running synthetics. 

Users with an offline environment are a smaller percentage so we could have a separate larger image for that scenario. However, it sounded like users would still need to add dependencies for custom scripts. I imagine the users who have offline environments are used to pulling in dependencies for offline use.

**Comment by ruflin** [comment]
In general I like this idea. What is the total download size we talk about? And how long does the setup take normally (on your laptop)? If we go down this path, we should make sure the "downloading/waiting" is visible in Fleet and the user understands what is happening.

**Comment by andrewvc** [comment]
@andresrc the more I think about it, you're right, we need two for sure. Cloud would want to always run the 'full' image. 

++ @ruflin to having a better 'waiting' state. We'd ideally have this in the Uptime app, where we can instantly create a monitor with a 'waiting state'

**Comment by andrewvc** [comment]
Looking more closely into the security issues associated with setuid I think that option is off the table, I'll have to research alternatives.

**Comment by andrewvc** [comment]
For now, this is on pause in favor of https://github.com/elastic/beats/issues/26398 which will cover our needs for some time. I'm going to leave this open because we will probably pursue this in the future

**Comment by kuisathaverat** [comment]
I am not sure if download packages in runtime is a good idea, the user will download some packages from internet with all the problems that can cause this (security, download failures, ...), also I dunno if it is something allowed for the IronBank Docker images of other restricted environments like banks, these systems use to not have access to internet or it is really limited to a few sites.

**Comment by andrewvc** [comment]
Closing as this is way out of date
