### ISSUE TITLE
packetbeat filter

### ISSUE THREAD

**Issue by luweijun1992** [elastic/beats#26157]
How does packetbeat filter its own data packets sent to es:9200, because the server itself sends data to es:9200 in the collected data.
How to filter the information in this part.

**Comment by legoguy1000** [comment]
I would ask your question here, https://discuss.elastic.co/tags/c/elastic-stack/beats/28/packetbeat

**Comment by luweijun1992** [comment]
> I would ask your question here, https://discuss.elastic.co/tags/c/elastic-stack/beats/28/packetbeat

https://discuss.elastic.co/t/packetbeat-filter/275087

**Comment by luweijun1992** [comment]
> I would ask your question here, https://discuss.elastic.co/tags/c/elastic-stack/beats/28/packetbeat

@legoguy1000 Please help me thanks .

**Comment by jsoriano** [comment]
Closing this issue and following up in discuss. Thanks!
