### ISSUE TITLE
[Httpjson input] Adding array support to request body

### ISSUE THREAD

**Issue by P1llus** [elastic/beats#26165]
Currently the request body only support scalar values and a single JSON object, some modules would require to build bodies like this:

```
{
    "request_data": {
        "filters": [{
            "field": "creation_time",
            "operator": "gte",
            "value": 1623052965000
        }]
    }
}
```

In which the `filters` field is an `array of one or more objects`, and `value` can be a cursor field from the last API call similar to how cursors work today.

**Comment by marc-gr** [comment]
With the addition of https://github.com/elastic/beats/pull/26847 this can be achieved through `value_type`.
