### ISSUE TITLE
Improve AWS Billing with linked account and account name

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#26185]
Thanks to @fxdgear for trying out AWS Billing in Metricbeat. As we discussed, there are several useful enhancements can be done for the `billing` metricset:

- [x] Add `LINKED_ACCOUNT` into group_by dimension key by default (so the next two points will be actually useful)
- [x] Expose linked accounts under `AWS Account Filter` in Kibana AWS Billing dashboard when they exist
- [x] Expose account names in the dashboard instead of account IDs

Will update this list if we manage to find more enhancements.

**Comment by fxdgear** [comment]
Thanks for taking this on @kaiyan-sheng let me know how else I can help.

**Comment by kaiyan-sheng** [comment]
@Udayel Please feel free to comment here for any enhancement you see for billing. TIA!
