### ISSUE TITLE
Update to golang 1.16.5/1.15.13

### ISSUE THREAD

**Issue by michel-laterman** [elastic/beats#26182]
Update the versions of golang used to the latest patches which contain security fixes

- [x] Update crossbuild images
- [x] Update beats
- [x] Update fleet-server
- [x] ping APM

**Comment by michel-laterman** [comment]
@simitt, The images to update to go 1.16.5 and 1.15.13 are available. I didn't have any issues when updating beats 7.13.2 to 1.15.13; however due to a change in the [go mod download](https://github.com/golang/go/issues/46214) command there may be issues with the update to 1.16.5

**Comment by simitt** [comment]
thanks for the ping, we will try to update when the beats PR is merged.
