### ISSUE TITLE
New beat excute setup command . "type":"mapper_parsing_exception","reason":"No handler for type [constant_keyword] declared on field [namespace]"}

### ISSUE THREAD

**Issue by 94192448** [elastic/beats#26191]
Why?

2021-06-08T11:37:38.188+0800	INFO	[template]	template/load.go:240	Existing template will be overwritten, as overwrite is enabled.
2021-06-08T11:37:38.300+0800	INFO	[template_loader]	template/load.go:143	Try loading template fastdfsbeat-8.0.0 to Elasticsearch
2021-06-08T11:37:38.385+0800	ERROR	**instance/beat.go:971	Exiting: error loading template: could not load template. Elasticsearch returned: couldn't load template: 400 Bad Request: {"error":{"root_cause":[{"type":"mapper_parsing_exc
eption","reason":"No handler for type [constant_keyword] declared on field [namespace]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: No handler for type [constant_keyword] declared on field [namespace]","c**
aused_by":{"type":"mapper_parsing_exception","reason":"No handler for type [constant_keyword] declared on field [namespace]"}},"status":400}. Response body: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler f
or type [constant_keyword] declared on field [namespace]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: No handler for type [constant_keyword] declared on field [namespace]","caused_by":{"type":"mapper_pars
ing_exception","reason":"No handler for type [constant_keyword] declared on field [namespace]"}},"status":400}. Template is: {
  "index_patterns": [
    "fastdfsbeat-8.0.0-*"
  ],
  "mappings": {
    "_meta": {
      "beat": "fastdfsbeat",

**Comment by jsoriano** [comment]
Hey @94192448,

What version of Elasticsearch are you using? The error seems to indicate that it doesn't support the [`constant_keyword` field type](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/keyword.html#constant-keyword-field-type), introduced in 7.9.

**Comment by csdenboer** [comment]
Why is this happening?

**Comment by shawnz** [comment]
@jsoriano That appears to be an X-pack exclusive feature but I'm not using X-pack. How can I run the filebeat setup in such a configuration?

**Comment by ruflin** [comment]
In general, Elasticsearch "should" be of a newer version then Filebeat. The problem here is likely not the "x-pack" part but that Elasticsearch 7.9 does not support yet constant keywords. If you use a newer version of Elasticsearch, things should work again.

**Comment by shawnz** [comment]
Here it seems to recommend the opposite: https://www.elastic.co/support/matrix#matrix_compatibility

> * We recommend running the latest version of Beats, Logstash, Elastic Agent and ES-Hadoop; earlier versions will work with reduced functionality.

**Comment by ruflin** [comment]
😢  @nimarezainia Could you take a look at this?

One thing that needs to be pointed out, the initial error reported was for `fastdfsbeat-8.0.0` which is a custom beat. So maybe we see 2 different errors here? @yyymmp or @shawnz Could one of you provide the errors you see? Also if you say you don't use x-pack, do you mean you use the pure Apache version of Elasticsearch and Beats?

**Comment by ksp987** [comment]
Does anyone have any resolution for this? I am trying to get my packetbeat running on my computer and output beats AWS-managed elastic search. Getting the same error.

**Comment by ruflin** [comment]
@ksp987 I'm not sure if the AWS Elasticsearch version supports constant_keywords, I think it doesn't. So this is likely the issue.

**Comment by d3zorg** [comment]
Having elasticsearch 7.4.0 running, had to install auditbeat 7.8 to make it work as [constant-keyword](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/keyword.html#constant-keyword-field-type) breaks things since 7.9 for es 7.4.0

**Comment by ruflin** [comment]
In general I would recommend that because of this Elasticsearch should be newer or equal the Beats version. Unfortunately we never fully enforced this which leads to exactly this issue :-( I assume you can't upgrade to 7.8 or 7.9 Elasticsearch?
