### ISSUE TITLE
Improve RDS dashboard in Metricbeat AWS module

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#26207]
Instead of displaying insert and select latency, it would be good to plot read and write latency instead for RDS.
Also adding CPU utilization,  free storage space, read/write IOPS into the dashboard.

@Udayel Thank you for the input!!

**Comment by Udayel** [comment]
Thank you, @kaiyan-sheng. If possible please add Database load(Average active sessions (AAS)), Top waits, Top SQL, Top Users and Top Databases.
