### ISSUE TITLE
[Heartbeat] Improve the error message from synthetics failure

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/beats#26210]
+ When the synthetic command fails, heartbeat `exec` process consumes the `stderr` and does not provide enough details on why the current job failed.
```
2021-06-08T08:35:06.597+0200	WARN	synthexec/synthexec.go:179	Error executing command '/Users/name/.nvm/versions/node/v14.17.0/bin/elastic-synthetics --capability trace metrics filmstrips ssblocks --inline --rich-events --outfd 3': exit status 1
```

This message is clearly not helpful and we need to print the proper stderror logs from the synthetic agent when exit status is 1.

**Comment by andrewvc** [comment]
Are we certain there's a real error in the command and not just a test failure? I think the real issue here is that the synthetics command always returns a status > 0 when there's a failing test. We should add an option to disable this behavior, thus suppressing this frequent message.

**Comment by andrewvc** [comment]
Fixed in: https://github.com/elastic/synthetics/pull/357
