### ISSUE TITLE
metricset 'system/load' is not registered (on Windows)

### ISSUE THREAD

**Issue by LeeDr** [elastic/beats#2623]
- Version: 5.0.0-beta1
- Operating System: Windows 10
- Steps to Reproduce: 

1) start metricbeat.exe with the default metricbeat.yml (actually it was the .full.yml)
2) Fatal error as shown below

```
D:\5.0.0-beta1\metricbeat>metricbeat.exe
Exiting: 1 error: metricset 'system/load' is not registered, metricset not found
```

3) I commented out the `- load` line and now it starts fine
```
#------------------------------- System Module -------------------------------
- module: system
  metricsets:
    # CPU stats
    - cpu

    # System Load stats
    #- load
```

**Comment by pnigam-informatica** [comment]
Still facing this issue in ES 6.2.4

**Comment by ruflin** [comment]
@pnigam-informatica The load metricset is not available on Windows.

**Comment by YI-Gyo** [comment]
@pnigam-informatica 
Hi, I am facing the same problem. How did you solve it? Would you mind sharing your solution?
