### ISSUE TITLE
MAC OSS start auditbeat  failed

### ISSUE THREAD

**Issue by yhf597869822** [elastic/beats#26236]
I try to download from [auditbeat download page](https://www.elastic.co/cn/downloads/beats/auditbeat) for MAC , start auditbeat with the error that is `the auditd module is only supported on Linux`.
And I also use brew install auditbeat,`brew install elastic/tap/auditbeat-oss`,there is the same error.
The auditbeat version is `7.13.1`
here are details:
`2021-06-10T20:37:35.997+0800	INFO	eslegclient/connection.go:99	elasticsearch url: https://192.168.12.145:9200
2021-06-10T20:37:35.997+0800	INFO	[publisher]	pipeline/module.go:113	Beat name: HangfandeMacBook-Pro
2021-06-10T20:37:35.997+0800	INFO	instance/beat.go:442	auditbeat stopped.
2021-06-10T20:37:35.997+0800	ERROR	instance/beat.go:989	Exiting: 1 error: the auditd module is only supported on Linux
Exiting: 1 error: the auditd module is only supported on Linux`

**Comment by andrewkroh** [comment]
I download the macos version of the artifacts (both OSS and Elastic licensed) and neither have the `auditd` module enabled in the auditbeat.yml file that it ships with.

Did you add the auditd module into your config? That module is only available for Linux as the error indicates.

**Comment by yhf597869822** [comment]
> I download the macos version of the artifacts (both OSS and Elastic licensed) and neither have the `auditd` module enabled in the auditbeat.yml file that it ships with.
> 
> Did you add the auditd module into your config? That module is only available for Linux as the error indicates.

Yep,the auditd module is Commented out in my config file,and auditbeat is working! Clearer documentation may be needed !
