### ISSUE TITLE
Functionbeat not sending all logs from GCP to ES

### ISSUE THREAD

**Issue by jasonslater2000** [elastic/beats#26249]
using functionbeat v7.11.1 (7.12 and 7.13 not supported on GCP due to functionbeat using Golang 1.15 and GCP supporting Golang 1.13)

everything is in place now for easy reproduction

`functionbeat.provider.gcp.location_id: "us-central1"
functionbeat.provider.gcp.project_id: "elastic-sa"
functionbeat.provider.gcp.storage_name: "jslater-functionbeat-deploy"
functionbeat.provider.gcp.functions:
functionbeat.provider.gcp.functions:
  - name: jslater-pubsub-function
    enabled: true
    type: pubsub
    description: "Google Cloud Function for Pub/Sub"
    trigger:
      resource: "projects/elastic-sa/topics/jslater-pubsub-topic-2"
      service: "pubsub.googleapis.com"
`

easily reproducible.  intermittent, but happens quite often.

working:
last 5 min in GCP log explorer (4 events):
![image](https://user-images.githubusercontent.com/1718983/121594882-81177980-c9f2-11eb-9085-786a5ce116b5.png)

last 5 min in ES (4 events):
![image](https://user-images.githubusercontent.com/1718983/121594986-a1473880-c9f2-11eb-9693-0b8bea9ac4d2.png)

tried again (8 events in GCP)
![image](https://user-images.githubusercontent.com/1718983/121706480-845e4400-ca8a-11eb-9d69-8ac7939866aa.png)

but only 7 events in ES:
![image](https://user-images.githubusercontent.com/1718983/121706559-98a24100-ca8a-11eb-9261-edd51eb9c0f0.png)

This is the log output from functionbeat:
![image](https://user-images.githubusercontent.com/1718983/121707931-eec3b400-ca8b-11eb-9d18-8313e8c1f77a.png)

I don't see any pattern which would explain certain messages being intermittently dropped.  Since there is no ingest pipeline in the middle, I assume that functionbeat is intermittently dropping messages.  In my example, 7/8 were sent to ES.  In the customer's situation, around half of the events are not being sent.

**Comment by ChrsMark** [comment]
@kvch any comments here?

**Comment by jlind23** [comment]
We endeavor to address Functionbeat use cases via the new Serverless Forwarder project (https://github.com/elastic/elastic-serverless-forwarder)with a better integration with serverless functionality provided by major cloud providers. Enhancements to the current Functionbeat will therefore be limited.
