### ISSUE TITLE
[input awss3] Selective use of role_arn 

### ISSUE THREAD

**Issue by christianherweg0807** [elastic/beats#26245]
We´ve the following Setup for consuming Logs for many teams to our ECE environment:

![grafik](https://user-images.githubusercontent.com/39617537/121557271-e8462580-ca14-11eb-981c-4351a19e4cca.png)

There is the SQS Queue in our Account for queueing the messages and the S3 Bucket in the other account. To Access the Bucket we need a  role provided by the remote team. For the SQS bucket we can´t use this role, because the role has an explicit scope.

**Describe a specific use case for the enhancement or feature:**
To solve this we need an explicit configuration Item for each of the AWS resources inside awss3. e.g:
```json
- module: aws
  cloudtrail:
    var.sqs.role_arn:
    var.s3.role_arn:
```
or something like this.

Any idea?

regards
Christian

**Comment by ChrsMark** [comment]
cc: @kaiyan-sheng

**Comment by kaiyan-sheng** [comment]
@christianherweg0807 Thanks for reaching out. Currently we are not supporting S3-SQS setup in two different accounts. Is there a reason why the S3 bucket and SQS queue have to be in two separate AWS accounts? We recommend setting up S3(enable bucket notification) and SQS directly without SNS in the middle. 
cc @leehinman

**Comment by christianherweg0807** [comment]
Hmm, we have multiple fanouts for these messages from SNS  to SQS (for logging) or other SQS Queues for "other usecases".  
For this the devolpment teams have these SNS Queues and S3 buckts in there Accountss and every usecase subscribes to this topic with it´ss own SQS queue.
