### ISSUE TITLE
[Heartbeat] Stopping adding `monitor.status` field to `step/end` events

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#26325]
Synthetics step/end events should not include the `monitor.status` field as they currently do.  There is a `synthetics.step.status` field that should be used instead.

**Comment by awahab07** [comment]
**Post FF Testing**

LGTM
- Uptime UI looks and works as expected.
- `"monitor.status"` is only present in documents of type "heartbeat/summary" i.e. `synthetics.type: "heartbeat/summary"`. - `"monitor.status"` is not present in documents with the following `synthetics.type`:
  - `journey/browserconsole`
  - `journey/network_info`
  - `journey/start`
  - `screenshot/block`
  - `step/end`
  - `step/metrics`
  - `step/screenshot_ref`


### Testing approach

Synthetic events for an HTTP and a Browser monitor are recorded from on an old build and recent build. Events from old build of heartbeat do contain `monitor.status` in documents other than those of type `synthetics.type: "heartbeat/summary"` whereas event from the recent build of heartbeat don't contain `monitor.status` in documents other than `synthetics.type: "heartbeat/summary"`.

#### Example (Browser Monitor)
A browser monitor has the followings pings, where only one of the ping is from the old build of heartbeat (before inclusion of this PR):

Total pings: 8. 
Pings from old build: 1. 
Pings from new build: 7.
![Screenshot 2021-12-31 at 00 44 20](https://user-images.githubusercontent.com/2748376/147796746-dd8c28ad-5e49-4396-8d47-f822014954a3.png)

Each ping contains 6 journey steps. `monitor.status` is present only in 6 documents (steps pushed from an old heartbeat config).
![Screenshot 2021-12-31 at 00 57 56](https://user-images.githubusercontent.com/2748376/147796898-7b78cae4-abbb-4f1b-b08d-caf3f772736a.png)

`monitor.status` is not present in 42 documents (steps pushed from recent heartbeat config).
![Screenshot 2021-12-31 at 00 58 14](https://user-images.githubusercontent.com/2748376/147796929-da3d86de-218a-49ec-8259-eeea207c6f87.png)

No documents of type `synthetics.type: "heartbeat/summary"` has `monitor.status` NOT present, either from old or recent heartbeat build.
![Screenshot 2021-12-31 at 01 57 19](https://user-images.githubusercontent.com/2748376/147797065-c8382cb3-6560-4b0a-9912-e3d06f80a625.png)


#### Example (HTTP Monitor)

Documents of type `synthetics.type: "step/end"` have `monitor.status` present only in pings pushed from old build of heartbeat.
![Screenshot 2021-12-31 at 01 01 28](https://user-images.githubusercontent.com/2748376/147797088-42a9d04f-ceb7-4af4-9387-8d1a09fad57f.png)

All documents of type `synthetics.type: "step/end"` DOES NOT have `monitor.status` present in pings pushed from recent heartbeat build.
![Screenshot 2021-12-31 at 01 01 50](https://user-images.githubusercontent.com/2748376/147797124-2a7a82cd-4ac0-4ddf-8073-11d7617e8dfd.png)
