### ISSUE TITLE
Refactor add_cloud_metadata processor to improve ECS fields handling

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#26337]
We can reorganize this processor so the fetchers return the cluster data under the `cloud` name and the orchestrator data under `orchestrator`, so we don't need to make so much mangling of this meta.

_Originally posted by @jsoriano in https://github.com/elastic/beats/pull/26056#discussion_r648572922_

We could change the format of the metadata that are returned to sth like this:

```
{
"cloud": {},
"orchestrator": {},
"other.ecs.fields": {},
}
```

With this, the data manipulation at https://github.com/elastic/beats/blob/8a8c6d1bde023b4837a0b2d22f7e87a2ed202ea1/libbeat/processors/add_cloud_metadata/add_cloud_metadata.go#L115-L141 would be more smooth.

**Comment by ChrsMark** [comment]
@kaiyan-sheng I'm assigning this to myself but free to pick it up if you have free cycles.

**Comment by kaiyan-sheng** [comment]
@ChrsMark It's all yours!! Thank you!!
