### ISSUE TITLE
Filebeat memory usage

### ISSUE THREAD

**Issue by st4r-fish** [elastic/beats#26342]
Hi,

I'm trying to figure out how to limit Filebeat's memory usage. I have dozens of containers running on a VM and each of them has Filebeat in it and I have several issues with how it works now. Unfortunately, changing the queue limit has too big an impact on the performance, I don't have I/O or network bottlenecks, but as you may know, RAM is a scarce resource. I started researching this because a network issue stalled event shipping and when it stabilized, all of the processes started to fill up the memory with the events that were waiting. It caused a sudden surge in memory consumption that resulted in OOM and brought down the VM.

First, Filebeat won't release memory (I'm monitoring it with Metricbeat --> "system.process.cgroup.memory.mem.usage.bytes" field) until it restarts. This means for the 150 FB process if all of them use 70MB of memory, I can't utilize ~6.8GB of RAM (150*45MB since FB needs 25MB just for running). Naturally, I don't want to restart Filebeat every X minutes to get the precious memory back.

Second, when I tried to use disk queue, Filebeat used 30% more memory than without the disk queue which is quite interesting, I did want to save memory, not using more. When I combined this with memory limit (~50M) Filebeat crashed at a point.

Third, I tried to limit memory with [systemd](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#MemoryMax=bytes). The process doesn't start until I set the limit to at least ~25M. However, that won't be enough for anything. Until I raised the memory to ~70M, Filebeat **restarted every minute** and did a very poor job (compared to itself) shipping the events to a remote VM. 

I tested the above on a "clean" VM with one container, plenty of resources available. The test file was ~90MB in size with mocked access log entries  (~300K events). Unfortunately, there wasn't any log entry when Filebeat crashed or restarted by itself. The logging level was set to "info" because on "debug" level each event is added to the log too which takes up a lot of space and makes reading the logs very hard. I didn't see anything at the end of the log file with debug level.

So the questions:
- Why can't I get back the memory if it isn't used anymore?
- Is there a way to limit memory usage without heavily impacting event shipping performance?
- What am I doing wrong when I set up the disk queue?

OS: Ubuntu 20.04.2 LTS
Filebeat: 7.11.0

Configs:
[filebeat.yaml.txt](https://github.com/elastic/beats/files/6663032/filebeat.yaml.txt)
[test.yaml.txt](https://github.com/elastic/beats/files/6663033/test.yaml.txt)

systemd file had only one setting (that I modified during my tests):
```
[Service]
MemoryMax=70M
```

**Comment by Lauri-Kinsta** [comment]
Some clarification for this part:

> Third, I tried to limit memory with systemd. The process doesn't start until I set the limit to at least ~25M. However, that won't be enough for anything. Until I raised the memory to ~70M, Filebeat restarted every minute and did a very poor job (compared to itself) shipping the events to a remote VM.

So it seems that when Filebeat starts harvesters and start throwing stuff into memory, it'll run into the system memory limit which will kill it and restart the process. I have an environment where Filebeat uses around 200MB continuously which is interesting since when I checked none of the logs were active (offset 0 in the registry), aside from one which receives one small entry every minute.

**Comment by st4r-fish** [comment]
Some clarification for this part:

> Third, I tried to limit memory with systemd. The process doesn't start until I set the limit to at least ~25M. However, that won't be enough for anything. Until I raised the memory to ~70M, Filebeat restarted every minute and did a very poor job (compared to itself) shipping the events to a remote VM.

So it seems that when Filebeat starts harvesters and start throwing stuff into memory, it'll run into the system memory limit which will kill it and restart the process. I have an environment where Filebeat uses around 200MB continuously which is interesting since when I checked none of the logs were active (offset 0 in the registry), aside from one which receives one small entry every minute.
