### ISSUE TITLE
GCP billing reports wrong account ID 

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#26357]
Thank you @fxdgear for pointing out that the account ID in events reported by `gcp.billing` is not the actual account ID. It is using project ID instead.

**Comment by legoguy1000** [comment]
@kaiyan-sheng if u haven't already worked this, I can get a PR in for this today.

**Comment by kaiyan-sheng** [comment]
@legoguy1000 Thank you so much for the contribution!
