### ISSUE TITLE
Unable to view data in discover tab for journalbeat

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#26369]
Link followed: https://www.elastic.co/guide/en/beats/libbeat/current/beats-reference.html

Artifact links used: https://artifacts.elastic.co/downloads/beats/heartbeat/journalbeat-7.13.2-linux-x86_64.tar.gz

-Download the heartbeat and extracted the artifacts.

Commands used:
```
sudo ./journalbeat -e -c journalbeat.yml
./journalbeat setup
sudo chown root journalbeat.yml 
sudo ./journalbeat -e
```

**Journalbeat observations:**
- unable to install journalbeat with provided steps at user guide.
yml file: [journalbeat_yml.txt](https://github.com/elastic/beats/files/6676960/journalbeat_yml.txt)
logs file: [journal-beat-logs-at-console.txt](https://github.com/elastic/beats/files/6676962/journal-beat-logs-at-console.txt)

**Screenshot:** 
![image](https://user-images.githubusercontent.com/72375798/122559615-2e2a6b80-d05d-11eb-9372-017ce8496022.png)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
this seems likely related to https://github.com/elastic/beats/issues/26366 for heartbeat - but maybe not.

**Comment by kvch** [comment]
Same applies here for Journalbeat as well: https://github.com/elastic/beats/issues/26366#issuecomment-889859125

There is no dashboard and index template for the Beat.

**Comment by vipulsrivastava-qasource** [comment]
Hi @kvch

We have performed installation for Journalbeat on 8.0.0 Snapshot build and getting no error while executing the Journalbeat installation command. [Please refer the screenshot for the same]

**Screenshot**
![Journalbeat-data](https://user-images.githubusercontent.com/69579402/130059319-4baf8944-f367-41e3-9627-b73ae7791135.png)

We have checked the journalbeat data on Uptime tab as details shared by you as well on other Kibana tab like : Discover, Dashboard and Logs tab and unable to view data related to journalbeat.

**Query:** : Could you please confirm where we can view data for Journal beat?

Please let us know if we are missing something.

Thanks!!

**Comment by kvch** [comment]
Data is supposed to be under Discover. Could you please share the logs of journalbeat? By default, they are saved in the folder `/var/log/journalbeat`.

**Comment by vipulsrivastava-qasource** [comment]
Hi @kvch 

Thank you for sharing the information.

Please find the logs for journalbeat and let me know if anything else is required from our end.
[journalbeat.zip](https://github.com/elastic/beats/files/7020308/journalbeat.zip)

Thanks!!

**Comment by kvch** [comment]
Is that all? These are like ~20 lines of logs with where Journalbeat does not even logs that it has started running.

**Comment by vipulsrivastava-qasource** [comment]
Hi @kvch 

We have re-attempted and got same shared logs below.
[logs.zip](https://github.com/elastic/beats/files/7036746/logs.zip)
[kibana.zip](https://github.com/elastic/beats/files/7036748/kibana.zip)

Please let us know if we are missing anything.

Thanks!!

**Comment by kvch** [comment]
My last guess is that journalbeat does not have permission to read from the system journal. The index template is correct and loaded to Kibana. Unfortunately, with the lack of logs I am unable to track down the problem. Also, locally I am able to send logs and see them in the Discover page.
