### ISSUE TITLE
[Elastic Agent] Provide link to troubleshooting guide on fatal errors

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#26367]
Can we please provide a link to the troubleshooting guide when Elastic Agent exits with a fatal error? This will help users identify the cause of the problem and how to fix, as well as links to our github repos and discuss forums. 

The current error says:
```
$ sudo ./elastic-agent install -f --url=https://elasticsearch:8220 --enrollment-token=STRSc2ozWUItWXNuWE5oZzdERFU6anJtY0FIMzhSRGlzeTJYcUF5UklfUQ==
The Elastic Agent is currently in BETA and should not be used in production
...
Error: enroll command failed with exit code: 1
```

Can we add a link here to help people fix their problem?
```
Error: enroll command failed with exit code: 1
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html
```

**Comment by ph** [comment]
@nimarezainia This seems like a low effort, high reward type of issue, I presume we want to redirect the users to the documentation of the current version. @dedemorton is there any prior art in other products for this?

**Comment by dedemorton** [comment]
@ph That's a good question. I'm not aware of any products that do this, but I think it's a good idea. The main challenges are:

1. Providing a link that is versioned. We don't want users on older versions of the product ending up in the current docs.
2. Validating the link. Links get stale over time; we need to make sure links embedded in the product get validated somehow.

**Comment by nimarezainia** [comment]
@dedemorton could we just point to the "current" troubleshooting URL? My gut feel is that troubleshooting is not really version based. Sure there are bugs etc that are version based but how someone goes about troubleshooting shouldn't be version based.
