### ISSUE TITLE
[Question:]Unable to deploy Functionbeat due to lack of permission 

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#26364]
**Functionbeat Deployment issue:**
As we are unable to update the user permissions for aws  due to lack of permissions, hence unable to validate functionbeat installation.

To run Functionbeat, we need to update aws_access_key as per steps shared in user guide. We tried to look for same at location shown in below screenshot. However, due to unavailability of required info we are unable to validate above beats installation.

**Screenshot:**

![image](https://user-images.githubusercontent.com/72375798/123632100-2a54d100-d835-11eb-8bc7-fa513f92e001.png)

yml file:
[functionbeat_yml.txt](https://github.com/elastic/beats/files/6676323/functionbeat_yml.txt)

@EricDavisX Could you please have a look at this if need to cover under our tests.

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
Hi - team, I will defer to Andres overall for if Functionbeat manual test is needed now.  But since you've started, I think we clearly have a lacking bit of Docs somewhere or a worse bug, so at a minimum we can track that down use this or log a separate ticket for any follow up.

**Comment by jlind23** [comment]
We endeavor to address Functionbeat use cases via the new Serverless Forwarder project (https://github.com/elastic/elastic-serverless-forwarder)with a better integration with serverless functionality provided by major cloud providers. Enhancements to the current Functionbeat will therefore be limited.
