### ISSUE TITLE
Create a guide on how to tune beats (performance)

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#2638]
I was thinking of something very similar to: https://www.elastic.co/guide/en/logstash/current/performance-troubleshooting.html

There will probably one generic section about outputs, but there will also be beat specific segments. Should they all be in one place?

**Comment by dedemorton** [comment]
@ruflin Is this still something that we want to do? This has been open for awhile.

**Comment by dedemorton** [comment]
Closing in favor of https://github.com/elastic/beats/issues/3850
