### ISSUE TITLE
Update Palo Alto docs with supported sources

### ISSUE THREAD

**Issue by jamiehynds** [elastic/beats#26383]
From 7.14 our Palo Alto module will support additional log sources including [GlobalProtect](https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/globalprotect-log-fields/globalprotect-log-fields-for-pan-os-913-and-later-releases.html#id5795bd71-1dc5-4f82-872d-a9ba6cb7cedf), [HIP Match](https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/hip-match-log-fields.html) and [User-ID](https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/user-id-log-fields.html) logs.

Our documentation for both [Filebeat module](https://www.elastic.co/guide/en/beats/filebeat/7.13/filebeat-module-panw.html) + agent integration, needs to reflect support for these sources, in addition to our existing support for Threat and Traffic logs.

**Comment by willemdh** [comment]
Please also update the supported versions. Version 10.x is not listed, when can we expect the module to work for the latest panw version?

**Comment by M-Matos** [comment]
Please also add support for log source [SYSTEM], if required I can foward some Logs.thanks

**Comment by jamiehynds** [comment]
Docs updated to reflect supported sources. This issue will track support for all log types and PAN-OS v10: https://github.com/elastic/integrations/issues/2988
