### ISSUE TITLE
[Heartbeat] 'complete' Agent image (synthetics deps included)

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#26398]
Takes over from https://github.com/elastic/beats/issues/22932

This issue covers the creation of a new elastic agent docker image that contains larger dependencies that would not be a good fit for the baseline elastic agent image. Specifically this covers the dependencies needed for synthetics which significantly increase the size of the agent image. While alternate approaches such as auto downloading synthetics images https://github.com/elastic/beats/issues/26153 might make sense in the future this approach will be needed for those who would rather not download dependencies, some of which are quite sizable, on demand.

While the precipitating factor here is heartbeat we are naming this image more generically "off-line" for the reason that other things might fall in this category in the future.

**Comment by kuisathaverat** [comment]
We cam probably reuse some of the work made for the IronBank Docker images, these are the dependencies to install synthetics about 200MB on RPM packages https://repo1.dso.mil/dsop/elastic/beats/heartbeat/-/blob/development/hardening_manifest.yaml

**Comment by andrewvc** [comment]
Closing, this is done in https://github.com/elastic/beats/pull/27052
