### ISSUE TITLE
"make package" for community beat

### ISSUE THREAD

**Issue by raboof** [elastic/beats#2639]
Hi,

I'm having some trouble packaging my community beat (https://github.com/raboof/connbeat).

When I 'make package':

```
echo "Start building packages for connbeat"
Start building packages for connbeat
mkdir -p /home/aengelen/dev/go/src/github.com/raboof/connbeat/build/upload
if [ true = true ]; then \
	 make prepare-package-cgo; \
else \
	make prepare-package; \
fi
make[1]: Entering directory '/home/aengelen/dev/go/src/github.com/raboof/connbeat'
# cross compile on ubuntu
docker run --rm \
	-v /home/aengelen/dev/go/src/github.com/elastic/beats/dev-tools/packer/xgo-scripts:/scripts \
	-v /home/aengelen/dev/go/src/github.com/raboof:/source \
	-v /home/aengelen/dev/go/src/github.com/raboof/connbeat/build:/build \
	-e PACK=connbeat \
	-e BEFORE_BUILD=before_build.sh \
	-e SOURCE=/source \
	-e TARGETS="linux/amd64 linux/386 windows/amd64 windows/386 darwin/amd64" \
	-e BUILDID=8045e664e0cfc7dd13c16ca10a6216d73ebe3826 \
	tudorg/beats-builder \
	github.com/raboof/connbeat
Working directory=/go/src/github.com/raboof
Copying main source folder /source to folder /go/src/github.com/raboof/connbeat
Fetching dependencies...
Execute /scripts/before_build.sh github.com/raboof/connbeat
make: *** No rule to make target `install-home'.  Stop.
../../elastic/beats/libbeat/scripts/Makefile:348: recipe for target 'prepare-package-cgo' failed
make[1]: *** [prepare-package-cgo] Error 2
make[1]: Leaving directory '/home/aengelen/dev/go/src/github.com/raboof/connbeat'
../../elastic/beats/libbeat/scripts/Makefile:384: recipe for target 'package' failed
make: *** [package] Error 2
```

What I notice is that my the github.com/raboof directory is mounted to /source 
```
	-v /home/aengelen/dev/go/src/github.com/raboof:/source \
```

... but that then it appears to be copied to github.com/raboof/connbeat:

```
Copying main source folder /source to folder /go/src/github.com/raboof/connbeat
```

This *seems* inconsistent, and it *seems* choosing to mount `$(abspath ../)` on `/source` in  https://github.com/elastic/beats/blob/master/libbeat/scripts/Makefile#L351 is the culprit. Could that perhaps be something like `$GOPATH/src/$BEAT_DIR`?

**Comment by ruflin** [comment]
`package` requires the `github.com/elastic/beats` to be part of your vendor directory. It doesn't work if it is only in your GOPATH. Based on the error I assume this is the problem.

Did you use the beat-generator to create the beat? The most recent version should copy it over to the vendor directory.

I'm very happy to see that you are building a beat. Lets use discuss for further discussion (except obviously for confirmed bugs): https://discuss.elastic.co/c/beats/community-beats I'm closing this one and happy to further assist on discuss.

**Comment by raboof** [comment]
Thanks for the super fast response! I can reproduce the problem even with a freshly generated beat... started a thead at https://discuss.elastic.co/t/packaging-community-beats/61917
