### ISSUE TITLE
Topbeat has no 5.0 beta1 download link

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#2640]
All the other beats have their corresponding 5.0 beta1 download sections below their 1.x download sections, but the download page for topbeat (https://www.elastic.co/downloads/beats/topbeat) only shows the 1.x download links and is missing downloads for 5.0 beta1

![image](https://cloud.githubusercontent.com/assets/7216393/18812889/12793794-8298-11e6-8278-8cf51a046038.png)

**Comment by ruflin** [comment]
There does not exist any Topbeat 5.0 version. It is "replaced" by Metricbeat which includes the Topbeat features and adds more. Closing this as this is intended.

**Comment by ppf2** [comment]
Oh yah, missed that note in the paragraph makes sense :)
