### ISSUE TITLE
[Integrations] MSSQL server image is outdated

### ISSUE THREAD

**Issue by mdelapenya** [elastic/beats#26437]
Running x-pack/metricbeat system-tests fails because the `2017-GA` tag does not exist anymore. Instead, it's been replaced with `2017-GA-ubuntu`

- Docker Hub: https://hub.docker.com/_/microsoft-mssql-server
- See the available tags here: https://mcrflowprodcentralus.data.mcr.microsoft.com/mcrprod/mssql/server?P1=1624445408&P2=1&P3=1&P4=H4w0lWyvxuvd60C1%2B6N6XJO2pSitpSmMrnB%2F%2FNm%2BM0w%3D&se=2021-06-23T10%3A50%3A08Z&sig=OWwqxML5Kzr5xkrNZEK0HzpLS3YHYKEGjxU8bQgB%2F4w%3D&sp=r&sr=b&sv=2015-02-21

cc/ @jsoriano

**Comment by mdelapenya** [comment]
I'm currently testing the new image tag and eventually sending a fix

**Comment by jsoriano** [comment]
Thanks @mdelapenya. We could also add the `supported-versions.yml` file so the image is cached and this doesn't causes issues in the future.
