### ISSUE TITLE
Filbeat stops crawling the file after some time

### ISSUE THREAD

**Issue by neuronring** [elastic/beats#2643]
Filebeat stops crawling the files after some time. I tried several different methods and changed the scan frequency and back off seconds. But the filebeat wouldnt detect any new patterns after ~5 mins. I works only the very first time after the installation and whenever i modify the include_lines:[], it wont parse any of the patterns any more.

I tried it without any regex filtering and it works fine as long as it sends everything in the file. After i communicated that we are going to use filebeat in my team for log forwarding and parsing, it is so frustrating to find it not working.. Please assist when this bug will be resolved.

Attached is my filebeat.yml file.  I have elasticsearch configured and it is working fine.

[my_filebeat.txt](https://github.com/elastic/beats/files/493742/my_filebeat.txt)

- Version: 1.3.1
- Operating System: Windows 
- Steps to Reproduce: Windows 2008 R2 Enterprise

**Comment by neuronring** [comment]
More information: 
Whenever i write something to the file in the configured prospectors, it says the below, but not capturing any events matching the include_lines: config value. 

`2016-09-26T15:08:22-05:00 INFO Registry file updated. 59 states written.
2016-09-26T15:08:22-05:00 INFO Harvester started for file: e:\test_log\one.log
2016-09-26T15:09:12-05:00 INFO Registry file updated. 59 states written.
2016-09-26T15:09:12-05:00 INFO Harvester started for file: e:\test_log\new_one.log
2016-09-26T15:13:53-05:00 INFO Registry file updated. 59 states written.
2016-09-26T15:13:53-05:00 INFO Harvester started for file: e:\test_log\myfile.log
`

**Comment by neuronring** [comment]
issue was with the File encoding. I was saving the log files in Unicode format which ended up creating space between each characters. After i changed the encoding to ANSI or UTF-8 it worked fine, Thanks to the debug mode.

**Comment by ruflin** [comment]
@neuronring Glad you found a solution and thanks for reporting it too here. In the future please try to use discuss first so we can confirm the bug before an issue is opened: https://discuss.elastic.co/c/beats/filebeat
