### ISSUE TITLE
[Palo Alto/panw.panos] Support Syslog RFC5424

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#26430]
Panos devices can send logs in RFC5424 (newer syslog) format, but the module is hardcoded to rfc3164 (older syslog).

Currently the only workaround is to edit the `module/panw/panos/config/input.yml` file and enable the new RFC with the `format` config option for syslog input (added by https://github.com/elastic/beats/pull/23954):

```diff
  type: syslog
+ format: 5424   
  protocol.udp:
    host: "{{.syslog_host}}:{{.syslog_port}}"
```

We should expose this configuration via a module setting or update the panw module to do it's own syslog parsing supporting both RFCs.

**Comment by jamiehynds** [comment]
We're currently working on RFC5424 support for the Palo Alto and all firewall integrations. Closing this issue in favour of the issue we're working on here: https://github.com/elastic/integrations/issues/1878
