### ISSUE TITLE
7.13.1 Agent is not signed for macOS

### ISSUE THREAD

**Issue by ferullo** [elastic/beats#26447]
I checked, both 7.13.0 and 7.13.2 are signed for macOS but 7.13.1 is not. I wouldn't expect 7.13.1 to be retroactively signed but figured I'd open an issue in case it's lack of a signature is unknown and the is a release process that needs looking in to.

**Comment by ruflin** [comment]
I'm wondering how this could happen as all the signing is fully automated. @mgreau @andrewkroh Any ideas?

**Comment by blakerouse** [comment]
This has been fixed for future releases, and was not closed.
