### ISSUE TITLE
Filebeat OOM when encounter a huge docker partial log

### ISSUE THREAD

**Issue by erenming** [elastic/beats#26464]
Hi, all!
I have found a special scenario. I use filebeat as an daemon process to collect docker log which use docker-json engine, it works pertty well at most time.
But, when a container print a huge log message, for example 50M, and docker will split it to 3200 partial lines(each partial size is 16KB). 
And this will result a huge memory usage in code `libbeat.reader.readjson.docker_json.go`. 
```go
// Next returns the next line.
func (p *DockerJSONReader) Next() (reader.Message, error) {
	var bytes int
	for {
		message, err := p.reader.Next()

		// keep the right bytes count even if we return an error
		bytes += message.Bytes
		message.Bytes = bytes

		if err != nil {
			return message, err
		}

		var logLine logLine
		err = p.parseLine(&message, &logLine)
		if err != nil {
			p.logger.Errorf("Parse line error: %v", err)
			continue
		}

		// Handle multiline messages, join partial lines
		for p.partial && logLine.Partial {
			next, err := p.reader.Next()

			// keep the right bytes count even if we return an error
			bytes += next.Bytes
			message.Bytes = bytes

			if err != nil {
				return message, err
			}
			err = p.parseLine(&next, &logLine)
			if err != nil {
				p.logger.Errorf("Parse line error: %v", err)
				continue
			}
			message.Content = append(message.Content, next.Content...)
		}

		if p.stream != "all" && p.stream != logLine.Stream {
			continue
		}

		return message, err
	}
}
```
`message.Content = append(message.Content, next.Content...)` this line will usage a huge memory and OOM at worst case.
![image](https://user-images.githubusercontent.com/19617947/123235430-6e329800-d50e-11eb-8548-12b0e2730ae6.png)

And I think, we should support a parameter such as `maxBytes` to limit the conent size.

**Comment by erenming** [comment]
So, is there any different opinion? I have fixed it on our fork, and would like to make a PR for this.

**Comment by ph** [comment]
@urso @kvch WDYT? Did we solve that with the filestream input?

**Comment by erenming** [comment]
> @urso @kvch WDYT? Did we solve that with the filestream input?

Is there any progress？

**Comment by urso** [comment]
Just noticed that issue. There is a `max_bytes` setting on the input. The default is 10MB, which can still cause OOM if we have a burst of long-line-events in the log file. With 10MB default and 4K events in the memory queue, memory usage can easily grow into higher GB usage.

Normally users would be recommended to reduce `max_bytes`. This will be handled by the `LineReader` in `libbeat/reader/readfile`. In case of multiline or other parsers producing a very long message, the `LimitReader` is used to post process the Content, by copying only up to `max_bytes` into a new buffer.

The parser setup in the logs and container setup is slightly different from the filestream input, but I'm not exactly sure if that helps with the issue at hand. The default `max_bytes` is still very high and one might consider to reduce that setting, e.g. to 1KB (pretty agressive).

In general, adding a limit to the docker json reader might be helpful as well to reduce memory usage during the read. @kvch would that be applied to the filestream parsers as well?

**Comment by erenming** [comment]
> Just noticed that issue. There is a `max_bytes` setting on the input. The default is 10MB, which can still cause OOM if we have a burst of long-line-events in the log file. With 10MB default and 4K events in the memory queue, memory usage can easily grow into higher GB usage.
> 
> Normally users would be recommended to reduce `max_bytes`. This will be handled by the `LineReader` in `libbeat/reader/readfile`. In case of multiline or other parsers producing a very long message, the `LimitReader` is used to post process the Content, by copying only up to `max_bytes` into a new buffer.
> 
> The parser setup in the logs and container setup is slightly different from the filestream input, but I'm not exactly sure if that helps with the issue at hand. The default `max_bytes` is still very high and one might consider to reduce that setting, e.g. to 1KB (pretty agressive).
> 
> In general, adding a limit to the docker json reader might be helpful as well to reduce memory usage during the read. @kvch would that be applied to the filestream parsers as well?

I use `container` which is based on `log` as the filebeat input. 

And the `LimitReader` take effect after the `DockerJSONReader`. When docker container print a huge log, docker will spit it to multiline partial line. And the `DockerJSONReader` will merge all those partial line default, at the end, if the merged message's size large than memory limit, filebeat will OOM.

![image](https://user-images.githubusercontent.com/19617947/124693210-9c05dc80-df11-11eb-865b-03c61ecc7c07.png)


So, even i set the `max_bytes` and memory queue size properly, above case will still happen.

**Comment by urso** [comment]
> And the LimitReader take effect after the DockerJSONReader. When docker container print a huge log, docker will spit it to multiline partial line. And the DockerJSONReader will merge all those partial line default, at the end, if the merged message's size large than memory limit, filebeat will OOM.

Agreed, this is potentially a problem and a PR with a fix would definitely be welcome.

But how big is your event that you experience an OOM on a single log event? At which limit is FB killed because of OOM? Normally it is the sum of big log events still in memory which trigger an OOM. Reducing `max_bytes`, even with the current code would help to reduce memory pressure.

**Comment by erenming** [comment]
> > And the LimitReader take effect after the DockerJSONReader. When docker container print a huge log, docker will spit it to multiline partial line. And the DockerJSONReader will merge all those partial line default, at the end, if the merged message's size large than memory limit, filebeat will OOM.
> 
> Agreed, this is potentially a problem and a PR with a fix would definitely be welcome.
> 
> But how big is your event that you experience an OOM on a single log event? At which limit is FB killed because of OOM? Normally it is the sum of big log events still in memory which trigger an OOM. Reducing `max_bytes`, even with the current code would help to reduce memory pressure.

Really thanks for your help, and i'll make PR to fix this later.

By the way, in our environment, the app print some huge log event which is about 50MB~100MB occasionally, and the memory limit of filebeat is 512MB. When FB is very busy, and run out of CPU, it will more like to OOM
