### ISSUE TITLE
Option to put metadata like offset into the metadata array

### ISSUE THREAD

**Issue by mrjameshamilton** [elastic/beats#2649]
In filebeat, currently offset and others are put into the root. I think this should go into the metadata array.

**Comment by ruflin** [comment]
Can you share some more details on why you need this and your use case?

Currently the metadata array only contains information like fields and tags which are set manually and normally the same across all events of one log line.

**Comment by mrjameshamilton** [comment]
Because I think the data in the root of the document should be "my" data rather than the information about the data (i.e. the offset in the file). I don't actually want to store the offset information in ES so I remove the field in Logstash.

**Comment by ruflin** [comment]
Thanks for sharing your thoughts. As far as I understand, also if it would be in meta, you would still have to remove it? Or would that simplify your problem?

As a side note: In filebeat 5.0 filters / processors were introduced so you can already fields you don't want on the filebeat side (like offset).

**Comment by mrjameshamilton** [comment]
The metadata array in Logstash isn't sent forward to the outputs. So it would be available in Logstash for some processing if required but not forwarded to the outputs.

I didn't know about the filters so I will look into that but I'd still vote for moving the offset to the metadata :-)

**Comment by ruflin** [comment]
I think we should not mix manual set meta data with auto generated meta data as then the question arises which one overwrites which one. This said, in case we decide to group together things like offset or potentially line number, inode etc. into a namespace, we would require and additional name for that namespace. `fields` and `tags` is taken by the manually set fields. `meta` would kind of still be available.

**Comment by mrjameshamilton** [comment]
Isn't overwriting data also a problem now? If I have a manually set field named offset, one has to overwrite the other?

For example, the elasticsearch input can put the document meta data into the metadata field https://www.elastic.co/blog/logstash-metadata (docinfo_in_metadata => true).

**Comment by ruflin** [comment]
Unless you set `fields_under_root` this is not a problem and is the reason that fields are in their own namespace. Same is true for json fields. It is possible to move data around on the LS or ES side, but then the overwriting happens on purpose and is not happening acidentially. By default overwriting does not happen, but it is always possible to configure it that way.

**Comment by mrjameshamilton** [comment]
ah, yes true. I set fields_under_root => true because I wanted to manually put some fields using the fields option which appear on the root.
