### ISSUE TITLE
[Fleet]: No logs available for agents under agent "Logs" tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#26490]
**Kibana version:** 7.14.0 Snapshot Kibana cloud environment

**Host OS and Browser version:** Windows 10, All

**Build Details:**
```
 Build: 41846
 Commit: 3cfbe712030c898819006195e6c9ddae6cbd0a3a
 Artifact Link: https://snapshots.elastic.co/7.14.0-52b7d996/downloads/beats/elastic-agent/elastic-agent-7.14.0-SNAPSHOT-windows-x86_64.zip
```

**Preconditions:**
1. 7.14.0 Snapshot Kibana cloud environment should be available.
2. Agent must be installed with Default policy having System Integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Agents> agent "Logs" tab,
3. Observe no agent logs under Logs tab. 

**Expected Result:**
Logs should be available for agents under agent "Logs" tab.

Logs:
[logs.zip](https://github.com/elastic/kibana/files/6684889/logs.zip)

**Screenshot:**
![7](https://user-images.githubusercontent.com/77374876/122724012-2d7a1b00-d291-11eb-82cb-a93a4f36dd65.JPG)

**Comment by EricDavisX** [comment]
If I had to guess, I'd say this is Agent side - so I transfered it from Kibana to Beats repo.

**Comment by EricDavisX** [comment]
In the end I think this is the same issue as https://github.com/elastic/beats/issues/26518 - the dataset isn't being ingested.  The other logs are there, if you select them, and then if you use the date picker to force a re-pull of the data.  The UI is showing some flakiness I will ask Jen and team in slack if they are related or not, seems not, and i'll log a new bug.

I think we can close this as a dupe, but it may have helpful logs in it and was actually logged a few days earlier than the above noted (but I've already raised that ticket up so am fine to stick with that one).

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 

>The other logs are there, if you select them, and then if you use the date picker to force a re-pull of the data.

We have re-attempted to change Date/Time on our end. However we haven't observed any logs under Logs tab.
Not about any particular(elastic_agent) dataset issue, we are unable to see any dataset logs. 
This Logs UI bug was observed when this https://github.com/elastic/beats/issues/26518 issue wasn't reproducible.

Please let us know if anything else is required from our end.
Thanks
QAS

**Comment by EricDavisX** [comment]
in the screenshot it shows only 1 dataset as selected, which i assume is the 'default' setting of Elastic Agent (which indeed has no logs that i can see) however, if you click the other dataset options and then refresh the page, for me, logs show up for the other components.  I'm still hopeful this will be resolved - let me know if the added description for working-around this doesn't help?

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
Thank you for the feedback, we are able to see logs after selecting all the available datasets under Datasets dropdown.
Hence we are closing this issue.

Further we are unable to see "elastic_agent" under dropdown.

Screenshots:
![6](https://user-images.githubusercontent.com/77374876/123930906-c86ba700-d9ad-11eb-9f6b-8d08a696609c.JPG)
![5](https://user-images.githubusercontent.com/77374876/123930922-cbff2e00-d9ad-11eb-887c-94e52c889e57.JPG)

Thanks
QAS

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We are able to reproduce this issue on 7.14.0 Snapshot.

**Observations:**
- No logs available under Logs tab.
- No filter options are available under "Dataset" and "Log level" dropdowns under agent "Logs" tab.

**Build details:**
```
Build: 42333
Commit: d2904ca073e91582a2c5fa6ef6e712491cf3521f
```

**Screenshot:**
![3](https://user-images.githubusercontent.com/77374876/124733179-93250300-df31-11eb-8f6b-5b96a3eb5b5a.JPG)

Hence we are re-opening this issue.

Thanks
QAS

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this issue on 7.14.0 Snapshot and found it **fixed**.
- Logs are available under Logs tab now.
- Filter options are now available under "Dataset" and "Log level" dropdowns under agent "Logs" tab.

Build details:
```
Build: 42366
Commit: 22dee04008b9936be37225b97a6456e750d559a7
Artifact Link: https://snapshots.elastic.co/7.14.0-ef1f955b/downloads/beats/elastic-agent/elastic-agent-7.14.0-SNAPSHOT-windows-x86_64.zip
```

Hence we are closing this out.
Thanks
QAS
