### ISSUE TITLE
clean_removed removes state of files that are still on disc

### ISSUE THREAD

**Issue by shoggeh** [elastic/beats#2652]
Hi,
- Version: Filebeat beta1
- Operating System: CentOS6
- Steps to Reproduce: 

The entire issue is described under https://discuss.elastic.co/t/filebeat-beta1-resends-random-data-upon-every-restart-registry-file-not-updated-properly/61813 

It looks like filebeat with clean_removed: true randomly removes registry entries of files that are still on disc.

**Comment by ruflin** [comment]
@shoggeh See my comment in https://discuss.elastic.co/t/filebeat-beta1-resends-random-data-upon-every-restart-registry-file-not-updated-properly/61813/3 Lets use the discuss post to get to the bottom of this and follow up here when we know more details.

**Comment by ruflin** [comment]
@shoggeh I'm closing this one as several improvements were made to the close_* handling since then. It would be very nice if you could test 5.0.1 to see if the problem still persists. Please reopen or comment if it shows up again.
