### ISSUE TITLE
Fix test_dashboards in x-pack metricbeat

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#26536]
See https://github.com/elastic/beats/pull/26526

Failure seems to be caused by `Metricbeat-aws-billing-overview.json` dashboard.

Can be reproduced with the following command from `x-pack/metricbeat`.
```
PYTEST_ADDOPTS="-k test_dashboards" mage pythonIntegTest
```

Trace:
```
E         2021-06-28T15:03:22.125Z	ERROR	instance/beat.go:971	Exiting: Failed to import dashboard: Failed to load directory /go/src/github.com/elastic/beats/x-pack/metricbeat/build/system-tests/run/test_xpack_base.Test.test_dashboards/kibana/7/dashboard:
E           error loading /go/src/github.com/elastic/beats/x-pack/metricbeat/build/system-tests/run/test_xpack_base.Test.test_dashboards/kibana/7/dashboard/Metricbeat-aws-billing-overview.json: returned 500 to import file: <nil>. Response: {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred."}
E         Exiting: Failed to import dashboard: Failed to load directory /go/src/github.com/elastic/beats/x-pack/metricbeat/build/system-tests/run/test_xpack_base.Test.test_dashboards/kibana/7/dashboard:
E           error loading /go/src/github.com/elastic/beats/x-pack/metricbeat/build/system-tests/run/test_xpack_base.Test.test_dashboards/kibana/7/dashboard/Metricbeat-aws-billing-overview.json: returned 500 to import file: <nil>. Response: {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred."}
E         
E       assert 1 == 0
```

**Comment by blakerouse** [comment]
This is blocking my progress on #26665? Is there an update on this? Can we skip the test?

**Comment by kaiyan-sheng** [comment]
@blakerouse Not sure if I can only skip certain dashboard from this pythonIntegTest. I will look into how to fix it today.

**Comment by kaiyan-sheng** [comment]
@blakerouse btw x-pack/metricbeat test dashboard is already disabled in PR https://github.com/elastic/beats/pull/26537. Do you need to reenable the test for your PR?

**Comment by blakerouse** [comment]
@kaiyan-sheng I am seeing this error with last merge of master into my PR. Seems like the exact same issue that is reported here.

https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-26665/15/

**Comment by kaiyan-sheng** [comment]
Thanks for the link! It's the same problem but happening under `beats/metricbeat` instead of `beats/x-pack/metricbeat`. Maybe https://github.com/elastic/beats/pull/26972 will fix it!
