### ISSUE TITLE
misleading actual available memory value in metricbeat 5.0-beta1

### ISSUE THREAD

**Issue by alextxm** [elastic/beats#2653]
Actual available memory reported by Metricbeat 5.0-beta1 is a bit misleading from the user POV.
If you analyze the JSON data on ES (please see the attached screenshot) you can see that values of system.memory.free, system.memory.total and system.memory.used.bytes are correctly related but the system.memory.actual.free one is quite unintelligible.
```
system": {
      "memory": {
        "actual": {
          "free": 140701896896512,
          "used": {
            "bytes": 35591327744,
            "pct": 4.1949
          }
        },
[... omitted...]
        "total": 8484442112,
        "used": {
          "bytes": 5603889152,
          "pct": 0.6605
        }
      }
```
In the docs I read: "system.memory.actual.free : [...] On Windows, it is the amount of unreserved and uncommitted memory currently in the user-mode portion of the virtual address space of the calling process.". btw I still can't get why its value is so high.

![image](https://cloud.githubusercontent.com/assets/6169392/18991928/cc03ca94-871b-11e6-8ea8-149f79d78722.png)

Tested with Metricbeat 5.0-beta1 on Windows 10 x64

**Comment by andrewkroh** [comment]
On Windows, system.memory.actual.free = [MEMORYSTATUSEX.ullAvailVirtual](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366770(v=vs.85).aspx). This doesn't seem to be consistent with the other OS'es since it's virtual memory.

The value in @alextxm's example does seem really high.

**Comment by monicasarbu** [comment]
@alextxm Thank you for posting the issue. I think we have now a fix in https://github.com/elastic/gosigar/issues/49. On Windows, the actual free memory is similar with the free memory, as there is nothing specific returned under [MEMORYSTATUSEX](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366770(v=vs.85).aspx.).

**Comment by monicasarbu** [comment]
Closing for now, as the fixed was merged.
