### ISSUE TITLE
Nomad autodiscover event missing task fields

### ISSUE THREAD

**Issue by wjordan** [elastic/beats#26538]
#### Description
Using `${data.nomad.task.name}` in a Nomad autodiscover config template (following the documentation examples) results in an invalid template reference error. The variable can currently only be accessed via `${data.meta.nomad.task.name}`, which is inconsistent with the current documentation.

There is some previous discussion in https://github.com/elastic/beats/pull/26498#discussion_r659178956 related to some ongoing documentation updates, but it wasn't just a simple documentation change so I opened this separate issue.

#### Details

According to the following documentation for the Nomad autodiscover feature, the `nomad.task.*` fields should be available on the emitted autodiscover event for config templating:
https://github.com/elastic/beats/blob/5960d7f9cce1317cf15d08af1d5ef862149e8d38/libbeat/docs/shared-autodiscover.asciidoc#L408-L422

https://github.com/elastic/beats/blob/5960d7f9cce1317cf15d08af1d5ef862149e8d38/libbeat/docs/shared-autodiscover.asciidoc#L473-L474

This is consistent with various examples throughout the documentation which include `${data.nomad.task.name}` in path templates.

Most of these fields are present on the event as expected, however it appears that the `task` fields are not on the `nomad` field directly but only on a `nomad.meta` field, which contains a copy of the `nomad` metadata with `task` merged into it. Here is the relevant code:

https://github.com/elastic/beats/blob/076e0a693c18617454388c6759c4010e821c0f59/x-pack/libbeat/autodiscover/providers/nomad/nomad.go#L197-L210

#### Discussion

It appears that the duplicated `nomad.meta` field was introduced as part of code review feedback (see https://github.com/elastic/beats/pull/14954#discussion_r395827096). Based on that discussion, my understanding is that the `nomad` field allows for simpler template references (`${data.nomad.*}` instead of `${data.meta.nomad.*}`), while the duplicated `meta.nomad` field is used to support enriching events by processors. If so, merging the `task` metadata into the `nomad` field in addition to `meta.nomad` sounds like a fix that would resolve this issue without needing to update the existing documentation.

**Comment by jsoriano** [comment]
`meta` is in principle used for enrichment of events, it doesn't need to be available for config templates. I think we should review that both alloc and task data is both in events and available for template configs and hints.

Probably this `allocMeta` should instead be a map with both the alloc and the task info: https://github.com/elastic/beats/blob/076e0a693c18617454388c6759c4010e821c0f59/x-pack/libbeat/autodiscover/providers/nomad/nomad.go#L202
