### ISSUE TITLE
[documentation/cli help] Default path to Filebeat configuration (/filebeat.yml)

### ISSUE THREAD

**Issue by strarsis** [elastic/beats#2654]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For confirmed bugs, please report:
- Version: Filebeat 1.3.1
- Operating System: Debian 7 amd64
- Steps to Reproduce: ````filebeat --help````

In Filebeat command line help (filebeat --help), 
the default configuration file path is indicated as "/filebeat.yml".

However, practically testing this shows that it actually looks for the configuration file in "./filebeat.yml" (relative to cwd ("./[...]") where the command is invoked).

Related discussion: 
https://discuss.elastic.co/t/documentation-issue-default-path-to-filebeat-configuration-filebeat-yml/61831

**Comment by monicasarbu** [comment]
@dedemorton By default, any Beat searches for the configuration file in the directory where the package is, and not in `/etc/` as it's stated in the documentation: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation.html

**Comment by monicasarbu** [comment]
I would change to "for example C:\Program Files\Filebeat\filebeat.yml or /etc/filebeat/filebeat.yml for windows and deb/rpm packages"

**Comment by tsg** [comment]
@strarsis Filebeat looks for the config file in the current working directory, indeed, but `-h` prints the absolute path. I suspect you were in `/` when running `filebeat -h`? That would explain it.

**Comment by strarsis** [comment]
@tsg Right, the help text shows the cwd with '/filebeat.yml' as default value.

**Comment by tsg** [comment]
@strarsis What I'm saying is that the default changes depending on the cwd :-). This is kind of weird and we changed it already in master, but technically correct if at the time you ran the command you were in `/`.

**Comment by tsg** [comment]
Closing this one as the default has changed in 5.0, being more conventional:

```
  -c value
       	Configuration file, relative to path.config (default packetbeat.yml)
```
