### ISSUE TITLE
[MMSQL] module support for additional metrics

### ISSUE THREAD

**Issue by liladler** [elastic/beats#26565]
**Describe the enhancement:**
We would like to monitor our 2012/2016 MSSQL Databases and have support for additional metrics - 
```
transactions
active_temp_tables
connections_reset_per_sec
logins_per_sec
logouts_per_sec
cache_hit.pct
page_life_expectancy.sec
buffer.checkpoint_pages_per_sec
buffer.database_pages
buffer.target_pages
```

And also the following for MSSQL 2012 - 
```
space_usage.since_last_backup.bytes
space_usage.total.bytes
space_usage.used.bytes
space_usage.used.pct
stats.active_size.bytes
stats.backup_time
stats.recovery_size.bytes
stats.since_last_checkpoint.bytes
stats.total_size.bytes
```

If this would be possilbe it would be a great help for monitoring our use case!
**Describe a specific use case for the enhancement or feature:**

**Comment by ManojS-shetty** [comment]
This has been addressed in microsoft_sqlserver package integration as performance and transaction_log data stream and it will be released in 8.3 release of microsoft sqlserver package.
