### ISSUE TITLE
Filebeat OOM When encountering log files that are too large

### ISSUE THREAD

**Issue by Cynicis** [elastic/beats#26563]
I use filebeat as an daemon process to collect docker log , it works pertty well at most time.
But, when a container print a huge log message, for example 100M, filebeat container reboot due to Out Of Memory，It killed by k8s。The filebeat service cannot start up and run properly.Can I configure the specified size of log files not to be collected？

**Comment by erenming** [comment]
it seems same as my issue #26464

**Comment by ChrsMark** [comment]
Hi! Unfortunately not, you cannot reject a log line without first reading it :). Please consider increasing the resource limits for Filebeat container so as to avoid this OOM kills.
