### ISSUE TITLE
[Elastic Agent] Uniquely Identify a Host End Point

### ISSUE THREAD

**Issue by nimarezainia** [elastic/beats#26572]
**Describe the enhancement:**
There are many use cases where an Elastic Agent needs to be uniquely identified and persistent across disruptions. One of the main use cases is for us to be able to reconcile the logs and events data in Elasticsearch for an agent that goes through these transitions. By uniquely identifying a host end point we should be able to recognize whether the host had previously enrolled with fleet-server, if so then all records associated with that agent can be reconciled.

**Describe a specific use case for the enhancement or feature:**

- As a security user, I want to prioritize high-risk hosts for investigation and uncover technical risks in order to get them into risk management workflows.

-     As an operations or incident response person, I need to quickly and accurately identify and locate hosts that have been identified in high-priority cases in order to undertake live response.

-     As a security analytics user or developer, I want to consider host and asset types when tuning rules and applying rules, policies, and exceptions, in order to realize high signal/noise ratios and prioritize cases involving critical assets.

-     As an Observability user, for traceability I need to have the past logs/events correlated to a host which was moved (switched off then back on) to a different location

Some of the proposals are documented in [0]

[0] https://docs.google.com/document/d/1p2aihQNxVLbPwln5pKPeA6GmoiIa2W5-JuYSf50TLSQ/edit?usp=sharing

**Comment by michel-laterman** [comment]
The [go-sysinfo](https://github.com/elastic/go-sysinfo) library that is already used by the host provider in the agent collects the os UUID values (such as `/etc/machine-id`) as expected and provides them as `host.id`.

**Comment by SourinPaul** [comment]
@nimarezainia just trying to get a quick state of this for 7.15. A quick update will greatly help to align dependencies. Thanks.

**Comment by michel-laterman** [comment]
Confirmed that the `host.id` currently does not change when the agent is uninstalled or unenrolled then re-installed

**Comment by michel-laterman** [comment]
Here's a table of the host.id and agent.ids during my validation (running on stack v7.14.0)
<img width="1607" alt="Screen Shot 2021-08-17 at 2 37 11 PM" src="https://user-images.githubusercontent.com/82832767/129804103-4c530520-1787-47a0-b945-71cfea3a1966.png">

**Comment by nimarezainia** [comment]
@SourinPaul I was taking this discussion over to email. We were planning on setting the host.id uniquely but As you can see the host.id is **already** being set and is consistent/unique across disruption. So I'm discussing with the team further what we need to do.

As you recall there are many different use cases. Aside from the VDI use case, can anyone in your team test this to see if Elastic detection engine does what it's meant to?

I'll get back to you on my findings.

**Comment by SourinPaul** [comment]
Thanks for the update here. I also noticed the email follow-up (where most related team members are copied). Maybe it's best to reconcile the next steps offline and update here. Thoughts?

@randomuserid @MikePaquette  in case you have not already seen the host.id examples in [this](https://github.com/elastic/beats/issues/26572#issuecomment-900649415) thread ^^.

**Comment by nimarezainia** [comment]
Since the host.id field is uniquely defined already we can close this issue. Working with teh security team to see if there are other issues/concerns regarding the VDI use case.

**Comment by EricDavisX** [comment]
I have pinged the test team to make sure there is a specific on-going test case that validates this is continues to work

**Comment by amolnater-qasource** [comment]
Hi @michel-laterman 
We have installed multiple OS agents on 7.16.0 Snapshot.
We compared host.id under Security>Hosts tab.

**On Linux:**
Host id is available for Linux agent and under `etc/machine-id` same id is available.
![2](https://user-images.githubusercontent.com/77374876/141749734-117c5138-b7d8-422b-adef-4ce61b59244c.JPG)

**On MAC:**
MAC host.id is available under Hosts tab. 

**QUERY 1:**
Could you please share the location(if any) just like `etc/machine-id` to find host.id on MAC?

**On Windows:**
Windows host.id is available under Hosts tab. 

**QUERY 2:**
Could you please share any way to find out way to find host.id for Windows endpoint?
As per our research and understanding we attempted it with `ipconfig /all` and considered physical address as `host id`.
However this physical address is **not equal** to the one available under hosts tab.
![5](https://user-images.githubusercontent.com/77374876/141750903-8aa6c667-3018-4d70-9a84-264f0aa4c61c.JPG)

![3](https://user-images.githubusercontent.com/77374876/141750912-d24901b3-e467-496d-838b-5cd7b4a6db30.JPG)

Further we are not able to find the similar location shared at screenshot https://github.com/elastic/beats/issues/26572#issuecomment-900649415

**QUERY 3:**
Could you please confirm where to test this for host.id, as shared above we have tested this under Security>Hosts tab?

We will create testcases as soon as we complete our testing on the same.
cc: @EricDavisX 
Thanks

**Comment by EricDavisX** [comment]
@mostlyjason can you help me confirm this last question # 3 above?  I think the question / answer has 2 sides:
Where in the UI should we look to confirm that the right host.id is displayed for Fleet?  I'll add @jen-huang too, maybe she can comment if we have it exposed anywhere?  

As to the data, as viewed in logs /Discover tab, I submit the answer is the same value for host.id should be seen in any document coming from the same actual host in all data from the same Agent install (for all beats then, Endpoint, OSQuerybeat, etc). Does that sound correct?  If so, then the test is to install Agent and Endpoint and OSQuery and make sure in a sample document from each, that the host.id is the same across a different sub-sources within Agent.

**Comment by amolnater-qasource** [comment]
Hi @michel-laterman 
Thanks for sharing valuable feedback we are now able to find host id on our mac and windows VM.

**Screenshots:**
Windows:
![10](https://user-images.githubusercontent.com/77374876/141972184-b8e153b7-f1fd-4038-abe8-06082acfe6f0.JPG)

MAC:
![9](https://user-images.githubusercontent.com/77374876/141972209-e8b43d8d-5519-4c78-9eb4-d8f4c211487f.JPG)

We have created **05 test cases** under our Ingest manager test suite at link:
[Uniquely Identify Host Endpoint](https://elastic.testrail.io/index.php?/suites/view/27&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=34795)

Further we will be updating these testcases whenever we will receive feedback on Query 3 shared at https://github.com/elastic/beats/issues/26572#issuecomment-968722847

Please let us know if anything else is required from our end.
cc: @EricDavisX 
Thanks

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
As per discussion in yesterday's call, we have revalidated host.id on other tabs. 
We have tested this on 7.16.0 BC-5 Kibana cloud-staging environment.

We are able to get `host.id` filter under Discover tab for various data sets after installing agents with Endpoint Security.

Please find below detailed screenshots for the same:
**Windows:**
![5](https://user-images.githubusercontent.com/77374876/142388119-d9790fd1-6a20-4a71-9686-2b99a5b77b8e.JPG)
![6](https://user-images.githubusercontent.com/77374876/142388127-7609caf5-2258-4304-af3b-65afaba6cc81.JPG)

**Linux:**
![8](https://user-images.githubusercontent.com/77374876/142388247-e9ee7241-19ad-42bd-be03-4352048c05ca.JPG)
![7](https://user-images.githubusercontent.com/77374876/142388283-765a7310-1528-4b6a-8ae4-51ec2f436643.JPG)

**MAC:**
![9](https://user-images.githubusercontent.com/77374876/142388360-b71ded82-47da-47c2-810c-8699929a1204.JPG)
![10](https://user-images.githubusercontent.com/77374876/142388382-f3b5fc94-31ad-48f0-8dce-585f95ae3a64.JPG)

Further we have logged a question ticket for an unknown host.id available under Discover tab at https://github.com/elastic/beats/issues/29028

Please let us know if anything else is required from our end.

Thanks

**Comment by EricDavisX** [comment]
we can call this good - and we'll track the one issue noted separately. cheers.

**Comment by mostlyjason** [comment]
@nimarezainia have you considered showing the host ID in the agent details view? Is that valuable for the use cases you are targeting?

![image](https://user-images.githubusercontent.com/6370704/142499851-f4afc19e-8d19-4453-a044-86c952287cf7.png)

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have executed **05** testcases for this feature under [Ingest Manager 7.16.0 New Feature uniquely identify host endpoint Test Plan](https://elastic.testrail.io/index.php?/runs/view/2531&group_by=cases:section_id&group_order=asc&group_id=34795)

Thanks
