### ISSUE TITLE
Issue with drop_fields short-circuiting on unknown field

### ISSUE THREAD

**Issue by Cord-Thomas** [elastic/beats#2664]
There appears to be a bug in the latest winlogbeat.  I am trying to skip some fields, so using the drop_fields feature.  If there is an event that doesn't contain a field, the beat appears to ignore the remaining fields in the drop_fields list.

For confirmed bugs, please report:
- Version: 5.0 beta
- Operating System:  Windows 10
- Steps to Reproduce:  using the below snippet in the winlogbeat.yml config.  If field "user_made_up" doesn't exist, the remaining fields are ignored

processors:
  - drop_fields:
     fields: [computer_name, user.domain, user_made_up, beat.hostname, ...]

As suggested by @andrewkroh, the following work - each drop_fields is processed separately.

processors:
- drop_fields:
   fields:
     - computer_name
- drop_fields:
   fields:
     - beat.hostname
- drop_fields:
   fields:
     - user.domain
- drop_fields:
   fields:
     - user.name

**Comment by monicasarbu** [comment]
@Cord-Thomas Thank you for posting the issue. I think I fixed the issue with the PR #2685
