### ISSUE TITLE
auditbeat: auditd error messages after update to 7.13.2

### ISSUE THREAD

**Issue by ynirk** [elastic/beats#26668]
After updating auditbeat to 7.13.2 (from 7.12.0) we start seeing the following error message:

```
2021-06-29T12:48:37.782Z#011ERROR#011[auditd]#011auditd/audit_linux.go:204#011get status request failed:failed to get audit status reply: no reply received
```

It only happens on a small proportion of deployed servers after auditbeat restart. Exemple on a specific instance 
<img width="1112" alt="Screenshot 2021-06-29 at 15 15 31" src="https://user-images.githubusercontent.com/33804891/124138696-2fa95a00-da87-11eb-9810-b57c14a218c4.png">

logs started right after the update and we see some after auditbeat restart the next day.

The update has been deployed to fix kauditd deadlock issue (https://github.com/elastic/beats/issues/26031) we were experiencing on some hosts. I'm wondering if it could be the same root cause ?

**Comment by efd6** [comment]
@ynirk Can I check whether it is consistently the same hosts? and whether the hosts are under load during this start up?
 
Looking at the relevant changes between 7.12.0 and 7.13.2 there is no change that would introduce this behaviour, but the previous deadlock behaviour may have hidden it by failing out.

Are you able to test increasing the [number of retries](https://github.com/elastic/go-libaudit/blob/59e6a0e41fce8699e148adbf93fb9d7ca5d9e8dd/audit.go#L482) or increasing the [backoff](https://github.com/elastic/go-libaudit/blob/59e6a0e41fce8699e148adbf93fb9d7ca5d9e8dd/audit.go#L489) on the retries?

**Comment by ynirk** [comment]
@efd6 sorry for the delay i totally miss the ping.
I see this behavior on lots of hosts (~2k hosts in the last 7 days) so it's not easy to tell if hosts are under pressure when it occurs.

**Comment by efd6** [comment]
Thanks, @ynirk. Are you able to test whether this behaviour persists with a version built with the retry relaxations I mention above?

Also, are you able to provide the log lines that follow that error? The [loop](https://github.com/elastic/beats/blob/686ba416a74193f2e69dcfa2eb142f4364a79307/auditbeat/module/auditd/audit_linux.go#L189-L216) that handles this retries until there is catastrophic failure and no audit monitoring client can be started. It would be helpful to know how many loop iterations fail to obtain a response and interesting to know how many events are lost (log lines corresponding to [this func](https://github.com/elastic/beats/blob/686ba416a74193f2e69dcfa2eb142f4364a79307/auditbeat/module/auditd/audit_linux.go#L405-L421)).
