### ISSUE TITLE
[Elastic Agent] Auto-enroll on first startup

### ISSUE THREAD

**Issue by blakerouse** [elastic/beats#26667]
## Overview
In cloud deployments and/or physical system deployments there is a case where you want an Elastic Agent to enroll into Fleet on first startup and not at installation time. Example being a prepared gold image for a cloud deployment, or a prepared sys-prepped Windows image for an organization.

## Idea
The idea is to add an option to the `install` command to not have it actually start the service and to not actually enroll at that time.

```
.\elastic-agent install --delay-enroll --url https://my.fleet.server --enrollment-token ${token}
```

## Implementation
This would proceed to install the Elastic Agent, write an `enroll.yml` (with the url and enrollment token) file next to the `elastic-agent.yml` file and not start the service.

Then on the first start of the service (which is normally on boot up of a fresh deployment) then the Elastic Agent would notice that a `enroll.yml` file is present, load that perform enrollment, re-exec into Fleet mode, and then delete the `enroll.yml`.

**Comment by blakerouse** [comment]
@nimarezainia @mukeshelastic ^

**Comment by nimarezainia** [comment]
Spoke to @blakerouse about this. I think adding the flag is a great idea to delay the enrollment so let's move ahead with this and the work on the unique agent id separately. All of these efforts should help in addressing the VDI use cases.

**Comment by EricDavisX** [comment]
I tagged @lthach2 to look into this, we can try to test it out.

**Comment by lthach2** [comment]
@EricDavisX I tested this on Windows, Mac, and Linux with results below.

**Windows:**
- Successfully installed Agent with enrollment delayed, service is installed but not started, and endpoint is not registered in Kibana
![image](https://user-images.githubusercontent.com/58046702/130140870-2b9aa33c-3bd5-4c78-8311-36059ba0e83e.png)

![image](https://user-images.githubusercontent.com/58046702/130141004-393be1e2-f505-4f97-84ed-c6715430aca3.png)

- Rebooted the endpoint but the Agent service does not start automatically even though it is set to
- Manually starting the Agent service is successful and it is registered in Kibana

**Linux:**
- Successfully installed Agent with enrollment delayed
![image](https://user-images.githubusercontent.com/58046702/130141216-5000b5c1-f094-4f58-a48b-f220dd2985a4.png)
- Rebooted the endpoint but the Agent service does not start automatically
- Attempting to start the Agent manually fails initially but subsequent attempt is successfull

**MacOS:**
- Successfully installed Agent with enrollment delayed
- Rebooted the endpoint but the Agent service does not start automatically
- Attempting to start the Agent manually fails
![image](https://user-images.githubusercontent.com/58046702/130141845-ece3ab78-f75e-4e5c-b2b6-61c4749056f2.png)

**Comment by EricDavisX** [comment]
I spoke with Amol who reports that testing from the BC build is working, tested on all 3 OS variants, too. I am wondering if @lthach2 had an older build?  Can you post the version / hash used during the test, Lee? I think the 7.15 build snapshot only became available today, so your code would be older and maybe from the 7.x (pre-branch) builds...  ?  I'm not sure here.

**Comment by lthach2** [comment]
Sure thing, this is the version I was using:

Binary: 7.15.0-SNAPSHOT (build: 1413b6cd17cbe530508f02652680b08e258b58c3 at 2021-08-17 16:59:11 +0000 UTC)

**Comment by lthach2** [comment]
Re-tested with the BC version on the 3 OS'es and it's working as expected.

**Comment by EricDavisX** [comment]
@IgorGuz2000 if you want to look at this, we can create an e2e scenario - would want to you research + create + copy over the relevant details to a new e2e-testing ticket?  Thank you
