### ISSUE TITLE
Add module to fetch Cloudflare logs

### ISSUE THREAD

**Issue by hartfordfive** [elastic/beats#2666]
Would be great to add a module for Cloudflare logs.  The ability to get request logs over HTTP is only [available for enterprise customers](https://support.cloudflare.com/hc/en-us/articles/216672448-Enterprise-Log-Share-REST-API), although this would still be a useful feature.

**Comment by tsg** [comment]
To clarify, the request is to fetch the logs over the HTTP API? Perhaps the Logstash [HTTP input plugin](https://www.elastic.co/blog/introducing-logstash-input-http-plugin) could help? In general, my first reacting is that this seems like a better match for Logstash than Beats.

**Comment by hartfordfive** [comment]
@tsg I haven't started working with the Cloudflare logs API yet, although I know they are fetched by issuing requests to their API although you also need a state file to keep track of which log entries you've already consumed.  To my knowledge, there's no way to do this out of the box by only using the Logstash HTTP plugin.  

I realize that an input plugin could also be created in Logstash for this, although it would be nice to see have the ability to collect the logs with the metricbeat process, which is generally easier to deploy and has lower CPU/memory usage.   For example, running metricbeat on Docker would be easier to setup and more efficient then installing a JVM and running Logstash.

I guess another option would be to simple create a custom beat, say "cloudflarebeat", which could fetch the logs and then ship them via either logstash or elasticsearch output.  What do you think?

**Comment by ruflin** [comment]
As we recommend to install metricbeat on the edge node, having a cloudfare module does currently not really fit into it as @tsg described. I would also see it either as a logstash plugin or an independent community beat. In case of a community beat, to not have to reinvent all the stuff in Metricbeat, Metricbeat can also be used as a library to create a beat: https://www.elastic.co/guide/en/beats/metricbeat/current/creating-beat-from-metricbeat.html

**Comment by tsg** [comment]
@hartfordfive Yeah, a Cloudflarebeat would make sense at this point, IMO. It will also make it easy to measure the community interest in it, and perhaps adopt it at some point as an official Elastic beat. Thanks for the understanding!

**Comment by hartfordfive** [comment]
@tsg, @ruflin this sounds reasonable to me.  I'll look into creating a community beat for Cloudflare logs and then let you know once it's completed.  Thanks for your help.

**Comment by tbragin** [comment]
@ruflin I heard a request for Cloudflare integration in a conversation with a user this week. I wonder if our thinking on this has evolved? Metricbeat now does more and more pull based work. Do we still think we'd need a new beat for this, or can it be a metricbeat modules? 

Separately, I wonder if anyone tried this tool: https://github.com/cloudflare/logshare

cc @makwarth

**Comment by ruflin** [comment]
We definitively evolved here. With the AWS module we also do remote polling so getting logs and metrics out of Cloudfare could also fit into it.

**Comment by tbragin** [comment]
I think it's still a valid request.

**Comment by 111andre111** [comment]
There is a valid use case for using access logs of CloudFlare that I am aware of.
https://developers.cloudflare.com/logs/log-fields
Apart from grabbing the CloudFlare logs using the API, the module could use S3 as well to grab from them and then ingest it:
https://developers.cloudflare.com/logs/logpush/aws-s3

**Comment by legoguy1000** [comment]
THis would be cool to see

**Comment by legoguy1000** [comment]
@hartfordfive I am working on a cloudflare integration for the Elastic Agent.  Do you have sample logs that I could use to test the ingest pipelines as well as perhaps test the HTTP or AWS S3 inputs??

**Comment by hartfordfive** [comment]
@legoguy1000  unfortunately I haven't worked with Cloudflare or its services in years.  Best to check with someone else in the community (maybe even Cloudflare?) who may have some sample logs they could share with you.

**Comment by ruflin** [comment]
Going to close this as it seems we have now a Cloudflare integration: https://github.com/elastic/integrations/pull/984
