### ISSUE TITLE
[Elastic Agent] Enable Jenkins Pipeline for M1 workers

### ISSUE THREAD

**Issue by nimarezainia** [elastic/beats#26686]
**Describe the enhancement:**
As we create binaries for the Agent to run on a Mac equipped with an M1 chip, we need to ensure that this platform build is part of our Jenkins CI pipeline. 

**Describe a specific use case for the enhancement or feature:**

**Comment by AndersonQ** [comment]
@nimarezainia, could you clarify which jenkins pipeline needs M1 workers?

**Comment by jlind23** [comment]
Closing as it's already supported.
