### ISSUE TITLE
[Elastic Agent] Beats and Elastic Agent to compile natively on a Mac M1 machine

### ISSUE THREAD

**Issue by nimarezainia** [elastic/beats#26683]
**Describe the enhancement:**
We need the Elastic Agent to be compiled so it can execute on a Mac with the M1 chip without any emulation software. With MacOS 11 the lowest required operating system.

- [ ] Add a new target to the existing platforms
- [ ] Investigate how the build will work with our crossbuild images.
- [ ] Enable Fleet Server to be built for M1

**Describe a specific use case for the enhancement or feature:**

As a user operating in a mixed environment, I want to download the Elastic Agent binary and know that it can operate on a variety of machines and operating systems in my environment. tested and supported by Elastic. Ensuring the best possible performance (no emulation)

**Comment by AndersonQ** [comment]
Splitting this issue into 2, one for [beats](https://github.com/elastic/beats/issues/29582), another for [Elastic Agent](https://github.com/elastic/beats/issues/29583). Check the [meta issue](https://github.com/elastic/beats/issues/26396) for the overall progress supporting M1 chips.
