### ISSUE TITLE
Prometheus rate calculation across counter resets is inconsistent with promql rate()

### ISSUE THREAD

**Issue by da77a** [elastic/beats#26700]
Promql, when it encounters a new counter value that is less than the previous value, assumes that there was a reset *to a value of 0* between when the the previous counter value was sampled and the new sample. Under this assumption the "true rate" is not less than the new sample value. What it definitely is not (unless the new value is 0) is 0.

metricbeat prometheus module should apply the same logic/calculation that promql uses for improved accuracy and consistency with prometheus.

Contrast this definition: https://promlabs.com/blog/2021/01/29/how-exactly-does-promql-calculate-rates#dealing-with-counter-resets with this code:
https://github.com/elastic/beats/blob/507d0d878b042c419413a6881dff90229aa6e448/x-pack/metricbeat/module/prometheus/collector/counter.go#L57-L60

**Comment by da77a** [comment]
in case not obvious I think this should simply be
```
 if prev.(uint64) > value { 
 	// counter reset to 0, then incremented from 0..value
 	return value, true 
 } 
```

**Comment by ChrsMark** [comment]
@exekias any thoughts on this?

cc: @MichaelKatsoulis @jsoriano

**Comment by exekias** [comment]
I think this is a good point, we could review the implementation to better handle these

**Comment by da77a** [comment]
Happy to do a PR with tests, as noted actual code change is trivial.

**Comment by da77a** [comment]
I should do that PR...
