### ISSUE TITLE
Apt-get (or dpkg) warns of weaks digest algorithm use by signature

### ISSUE THREAD

**Issue by domtoupin** [elastic/beats#2670]
**Beats version**: 1.3.1

**OS version**: Ubuntu 16.04.1 (and 16.04)

**Description of the problem including expected versus actual behavior**:
Warning from apt-get when installing any Beat: `W: https://packages.elastic.co/beats/apt/dists/stable/Release.gpg: Signature by key 46095ACC8548582C1A2699A9D27D666CD88E42B4 uses weak digest algorithm (SHA1)`

Notes:
- It installs just fine, it just warns.

**Steps to reproduce**:

1. Add elastic GPG key as explained in the documentation
1. Add beats repository to sources list and update: `apt-get update`
1. Run `apt-get install filebeat -y` or `apt-get install topbeat -y`

See [elastic/elasticsearch#17724](https://github.com/elastic/elasticsearch/issues/17724), [elastic/logstash#5761](https://github.com/elastic/logstash/issues/5761)

**Comment by andrewkroh** [comment]
@domtoupin Would you mind testing this repo for 5.0 too? 

`echo "deb https://artifacts.elastic.co/packages/5.x-prerelease/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list`

We are changed the code that does the signing for 5.x. I think it has SHA256 signatures.

**Comment by domtoupin** [comment]
@andrewkroh I tried the repo you indicated and ended up with the following warnings:
```
W: The repository 'https://artifacts.elastic.co/packages/5.x-prerelease/apt stable Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
```

I found a reference to this repo in [Kibana documentation](https://www.elastic.co/guide/en/kibana/5.0/setup-repositories.html) and tried running `wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -` but did not get a different result.

**Comment by andrewkroh** [comment]
Oh, I think there was an issue with that 5.x repo not being signed. That should be fixed with the next RC. Would be good to test that when it comes out. I'll look into fixing this issue for the 1.x releases.

**Comment by andrewkroh** [comment]
I opened https://github.com/elastic/beats-packer/pull/61 to address this for 1.X.

**Comment by andrewkroh** [comment]
@domtoupin I believe we have fixed the issue for the 1.X repo.

**Comment by domtoupin** [comment]
@andrewkroh I confirm that the warning is no longer present when using the steps described in the issue.

Thanks for the quick fix!
