### ISSUE TITLE
CI AWS account: write scripts to clean used resources

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#26711]
The idea of this issue is to enable some scripting to remove/clean old resources that have been used during tests.  We can't always trust Terraform that it will remove all resources. The process running "tf" or the entire CI machine may go down and these resources will stay forever.

Possible solutions:
* Lambda function which periodically cleans old resources.

Most likely we'll face same problem in elastic/integrations.

cc @jsoriano @kaiyan-sheng

**Comment by mtojek** [comment]
There are few players in the game:

cloud nuke - https://github.com/gruntwork-io/cloud-nuke
auto cleanup - https://github.com/servian/aws-auto-cleanup
awsweeper - https://github.com/jckuester/awsweeper

**Comment by jsoriano** [comment]
Terraform state [is archived by the jenkins pipeline](https://github.com/elastic/beats/blob/8c3f0d52d32d5ee7e0930a390dce9fe97c0c3ad1/Jenkinsfile#L887). This could be used to discover resources created but not destroyed. Though this would mean to look through all the jobs that may create these scenarios, and won't work for removed jobs.

**Comment by mtojek** [comment]
Yeah, that's actually the reason, why I personally prefer to simplify the logic and just depend on the timestamp (old enough? nuke it please).

I assume we need it for EC2 instances, DynamoDB databases, SQS queues, SNS topics. Is there anything else? Do we create also other resources?

**Comment by kaiyan-sheng** [comment]
Good point! 

> I assume we need it for EC2 instances, DynamoDB databases, SQS queues, SNS topics. Is there anything else? Do we create also other resources?

S3 bucket also?

**Comment by kuisathaverat** [comment]
The easy way is to tag everything created from the CI, then nuke everything with those tags every daily. If we add the tag `CI` and another like `created-DAY_OF_YEAR` we can nuke resources safely a day after they are created.

**Comment by mtojek** [comment]
👍

**Comment by kuisathaverat** [comment]
@v1v is this on your radar?

**Comment by v1v** [comment]
IIRC, all the bits and pieces regarding the tagging/labelling was done with:
- https://github.com/elastic/beats/pull/31355

There is some automation in place to delete all the leftovers, @amannocci can you confirm if the automation is enabled to delete those resources when needed?

https://github.com/elastic/beats/blob/5d4d48c24f752f328a00f7e23d1060cd0245ffe2/Jenkinsfile#L46 is the current AWS region

**Comment by amannocci** [comment]
Currently, only EC2 instances are handled by cloud-reaper.
AFAIK we will need to add support for S3, SNS & SQS services.
It should be easy for S3 and a bit less obvious for SNS and SQS services.
Should we add those items in an iteration? @v1v

**Comment by v1v** [comment]
> Should we add those items in an iteration? @v1v

Would you mind raising an issue in our project, so we can prioritise it

**Comment by amannocci** [comment]
This issue was addressed with internal tooling.
