### ISSUE TITLE
filebeat deconde json insert into clickhouse

### ISSUE THREAD

**Issue by azeng528** [elastic/beats#26726]
clickhouse Data compression ratio is best for elasticesearch（10 times）and clickhouse query is like mysql sql，it's best for user

**Comment by azeng528** [comment]
how to add team label?

**Comment by ChrsMark** [comment]
Hi! Is this an enhancement request? Also isn't this related to Elasticsearch itself? Please open a proper enhancement request to elasticsearch repository providing as much information/detail about your proposal.
I'm gonna close this now, thanks!
