### ISSUE TITLE
[Self-managed]: Upgraded 7.13.3 snapshot agent to 7.14.0 snapshot agent goes to offline state temporarily on upgraded 7.14.0

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#26738]
**Kibana version:** 7.13.3 Snapshot upgraded to 7.14.0 Snapshot Kibana managed environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
Build: 42320
Commit: e6ccbe1e10a6a4d2ee85b5fbbe57612af77fa0fe
Artifact Link: https://snapshots.elastic.co/7.13.3-4fbca986/downloads/beats/elastic-agent/elastic-agent-7.13.3-SNAPSHOT-windows-x86_64.zip
```

**Preconditions:**
1. 7.14.0 Snapshot Kibana upgraded from 7.13.3 Snapshot Kibana self-managed environment should be available.
2. Windows agent must be installed using Default policy having System, Endpoint Security and Fleet Server..

**Steps to reproduce:**
1. Login to Kibana environment.
2. Upgrade 7.13.3 Snapshot agent to 7.14.0 Snapshot.
3. Observe all agents went to offline state including Fleet Server.

**Expected Result:**
 Upgraded 7.13.3 snapshot agent to 7.14.0 snapshot agent should not go to offline state after upgrade and should directly get back Healthy.

**What else not working:**
- Upgraded agent goes to Updating state then goes Offline and then gets back to Healthy state.
- No new Logs  under Logs tab was observed.

**Logs:**
[logs.zip](https://github.com/elastic/beats/files/6770681/logs.zip)

**Screenshots:**
![9](https://user-images.githubusercontent.com/77374876/124614835-4b9b6a00-de92-11eb-802f-c29fce4a52dd.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @andresrc 

CC: @EricDavisX

**Comment by EricDavisX** [comment]
@amolnater-qasource about how long would you say it stays in unhealthy?  it is not ideal, but if it is brief enough it will be clear to users still and will be ignored correctly.  If it is more than a full minute, I might suggest we raise the priority of this and discuss with the team in slack if there is much to be done.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have reported this issue to avoid any gap.
>If it is more than a full minute

After upgrade it was offline just for 15-20 seconds. Hence, we are closing this issue for now.

Thanks
