### ISSUE TITLE
[Agents]: All agents went offline including Fleet Server on 7.13.3 BC-2 upgraded to 7.14.0 BC-1 Kibana

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#26730]
**Kibana version:** 7.13.3 BC-2 upgraded to 7.14.0 BC-1 Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
Build: 41006
Commit: d19e726c3cf6c1d392ec05bd8b9d1b8b9c6fd617
Artifact Link: https://staging.elastic.co/7.13.3-2a16d0f1/summary-7.13.3.html
```

**Preconditions:**
1. 7.13.3 BC-2 Kibana cloud environment should be available.
2. Windows, Linux and MAC Agents must be installed using Default policy having System and Endpoint Security.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Upgrade 7.13.3 BC-2 Kibana to 7.14.0 BC-1
3. Observe all agents went to offline state including Fleet Server.

**Expected Result:**
Agents should remain healthy after upgrade from 7.13.3 BC-2 to 7.14.0 BC-1 Kibana.

**Windows Agent Logs:**
[logs.zip](https://github.com/elastic/beats/files/6769056/logs.zip)

**Screenshots:**
![7](https://user-images.githubusercontent.com/77374876/124577962-63132c80-de6b-11eb-807b-f6e767813675.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @andresrc 

CC @EricDavisX

**Comment by urso** [comment]
Are you testing in the right environment? The cloud staging environment might not be ready yet.

**Comment by michalpristas** [comment]
reproducible on staging, not reproducible on qa cloud. closing

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this on cloud-qa with 7.13.3 upgrade to 7.14.0 and we have found it **not reproducible** now.

**Screenshot:**
![8](https://user-images.githubusercontent.com/77374876/125065054-fb5d1b80-e0ce-11eb-94c6-59bc1368a453.JPG)

cc: @michalpristas 
Thanks
QAS
