### ISSUE TITLE
[Heartbeat] Hook Errors from synthetics are not captured correctly 

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/beats#26780]
+ When user code has errors that is thrown in `beforeAll` hooks in the Synthetics agent, These will be captured as part of `journey/end` events. 
+ Right now heartbeat only captures the `step/end` errors and reports summary without capturing the errors from other event types.

**Comment by justinkambic** [comment]
I configured a test journey that throws an error in the `beforeEach` hook of the TODOs journey, and the error showed up.

![image](https://user-images.githubusercontent.com/18429259/125974637-f8b14435-a47c-4c92-b342-ba0a7a05417e.png)
