### ISSUE TITLE
[Update Module] Threat Intel Filebeat Module Dataset - Anomali

### ISSUE THREAD

**Issue by peasead** [elastic/beats#26792]
The current Threat Intel Filebeat module for Anomali Limo data uses `event.dataset : threatintel.anomali`. I recommend that dataset is changed to `event.dataset : threatintel.anomalilimo` for Anomali Limo data.

Another option would be to put everything in `event.dataset : anomali` and add a field that differentiates between ThreatStream or Limo. Maybe something like `service.name : {threatstream,limo}`

I believe this is a requirement because we've added Anomali ThreatStream as a dataset (`threatintel.dataset : anomalithreatstream`) and the ability to clarify the two Anomali datasets is important.

**Comment by ecezalp** [comment]
this is a breaking change for CTI Dashboard Link Panel on Overview Page, so let's make sure that there is some coordination around this change 👍

**Comment by peasead** [comment]
Any update on this? Is this closed?

**Comment by peasead** [comment]
Checking on this Issue, has it just been moved to be fixed with the TI package?

**Comment by peasead** [comment]
I'm going to close this and we can revisit if needed. RIght now, these will be in TI packages.
