### ISSUE TITLE
Monitor the entire certificate chain, including the expiration of the certification authority

### ISSUE THREAD

**Issue by thbkrkr** [elastic/beats#26827]
When Heartbeat monitors a certificate, the certificate authority expiry is not taken into account, only the leaf certificate expiry. It would be great that Hearbeat could watch at the entire chain.

For example, this would be very convenient for ECK users that use self-managed certificates by ECK and Cross-Cluster search. When a CCS Elasticsearch cluster is outside the Kubernetes cluster where ECK lives, it is necessary to copy the CA issued by ECK so that clusters trust each other (see [ECK Remote clusters documentation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-remote-clusters.html)). Then you have to udpate this CA before it expires, hence the need to monitor its expiration.

Relates to https://github.com/elastic/cloud-on-k8s/issues/4613.

**Comment by legoguy1000** [comment]
This is already done, https://github.com/elastic/beats/blob/23e4403ae093fcc8f7905345cad2c7ad256976d8/heartbeat/monitors/active/dialchain/tlsmeta/tlsmeta.go#L123. The entire chain is monitored and the smallest timeframe is provided.
