### ISSUE TITLE
[Agent]Allowing an array of hosts for --fleet-server-es argument when installing fleet server

### ISSUE THREAD

**Issue by P1llus** [elastic/beats#26823]
While installing the fleet server for the first time, there is a need to run for example:

`sudo ./elastic-agent install -f --fleet-server-es=ESURL --fleet-server-service-token=TOKEN`

However `--fleet-server-es` only supports a single host as an argument, which means that it will only be connected to a single ES node, instead of allowing it to communicate with the whole cluster.

This issue is to request the possibility to allow an array of hosts as an argument to `--fleet-server-es`

**Comment by aron-nagy** [comment]
Any updates on this topic? It would be very helpful to have multiple hosts configured for fleet-server. 
Thank you
