### ISSUE TITLE
Flaky Test [Build&Test / x-pack/metricbeat-goIntegTest / TestData – github.com/elastic/beats/v7/x-pack/metricbeat/module/airflow/statsd]

### ISSUE THREAD

**Issue by aspacca** [elastic/beats#26840]
## Flaky Test

* **Test Name:** TestData
* **Link:** https://github.com/elastic/beats/blob/master/x-pack/metricbeat/module/airflow/statsd/data_test.go#L53
* **Branch:** master/7.x
* **Artifact Link:** https://beats-ci.elastic.co/job/Beats/job/beats/job/7.x/837/testReport/junit/github/com_elastic_beats_v7_x-pack_metricbeat_module_airflow_statsd/Build_Test___x_pack_metricbeat_unitTest___TestData/
* **Notes:** An UDP server is started from the module and we send messages to it. We wait up to 5secs in order to receive the messages. after this time we fail the test. Fix will try to wait for a longer time

### Stack Trace

```
=== RUN   TestData
    data_test.go:70: received no events
--- FAIL: TestData (5.01s)
```

**Comment by kaiyan-sheng** [comment]
Reopening this issue because https://github.com/elastic/beats/pull/28037 in 7.x branch is seeing this flaky test again.

**Comment by aspacca** [comment]
seems solved
