### ISSUE TITLE
Metricbeat GCP billing metricset does not work with alphanumerical project ids

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#26855]
Metricbeat GCP billing metricset is using BigQuery to collect billing data. When GCP billing project ID includes alphanumeric, it returns an errors: 
```
bigquery Wait failed: googleapi: Error 400: Syntax error: Missing whitespace between literal and alias at [9:41], invalidQuery
```

Turned out the BigQuery query is missing quotes in Metricbeat code. For example, instead of `FROM some-project-name-with-dashes.Dataset_Name.gcp_billing_export_v1_xxx`, the syntax should be 

```
FROM `some-project-name-with-dashes`.Dataset_Name.gcp_billing_export_v1_xxx
```

cc @endorama

**Comment by endorama** [comment]
As specified in the BigQuery [doc on Identifiers](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical):

> Identifiers are names that are associated with columns, tables, and other database objects. They can be unquoted or quoted.
> [...]
> -   Unquoted identifiers must begin with a letter or an underscore character. Subsequent characters can be letters, numbers, or underscores.
> -   Quoted identifiers must be enclosed by backtick (`) characters.
>     - Quoted identifiers can contain any character, such as spaces or symbols.
> [...]

This confirms that the issue is in the `-` present in the unquoted table name.

**Comment by endorama** [comment]
By looking at the BigQuery docs about Identifiers:


> # Identifiers
> 
> Identifiers are names that are associated with columns, tables, and other database objects. They can be unquoted or quoted.
> 
> [...]
> 
> - Unquoted identifiers must begin with a letter or an underscore character. Subsequent characters can be letters, numbers, or underscores.
> - Quoted identifiers must be enclosed by backtick (`) characters.
>   - Quoted identifiers can contain any character, such as spaces or symbols.
> 
> [...]

Unquoted identifiers cannot contain `-`, that is probably the cause for behaviour observed in the linked SDH.

As Quoted identifiers can contain all characters of Unquoted identifiers + more I'm going to always quote that table identifier.
