### ISSUE TITLE
Filebeat Module - Microsoft Graph API Security

### ISSUE THREAD

**Issue by dwlfrth** [elastic/beats#26878]
A lot of Microsoft insights are being fetched through Filebeat modules tho, one important is missing in my opinion.
Microsoft Graph API Security https://docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-1.0

Especially the alerts. There is already the Microsoft Module which include M365Defender but the graph API security endpoint offer theses alerts along with multiple others.

**Comment by dwlfrth** [comment]
No longer required

**Comment by C4pt41nNRex** [comment]
> No longer required

Hi Derek,

I'm just curious. How did you solve your problem? I would like to connect my Elasticsearch with Microsoft Graph API Security too.

Thank you in advance.

Best regards,

Rex
