### ISSUE TITLE
Filebeat loadbalance on per file base

### ISSUE THREAD

**Issue by runningman84** [elastic/beats#2693]
It would be cool if filebeat would ensure that all messages from a single file gets forwarded to the same logstash host. 

There are a couple of log files which do not have high precision timestamps or many log lines with the same timestamp. Right now this leads to a mixed logfile view in Graylog/kibana...

Yes you could try to sort messages by offset but I prefer a simple solution here...

**Comment by ruflin** [comment]
I don't fully understand how sending all log lines to a single logstash instances solves this problem? Do you add a incremental counter to each line on the LS side?

**Comment by runningman84** [comment]
We use a group of logstash servers. They send the logs to a single graylog server. Graylog displays logs ordered by timestamp and insert order. It is not possible to order the results by offset...

**Comment by ruflin** [comment]
So the issue is related to Graylog, not elasticsearch or Kibana?

**Comment by runningman84** [comment]
Yes

**Comment by runningman84** [comment]
hmm the latest release of graylog also supports sorting by other fields...
