### ISSUE TITLE
bgrewrite.last_status cannot contain '.'

### ISSUE THREAD

**Issue by trevorndodds** [elastic/beats#2694]
Elasticsearch 2.4.1
Using metricbeat 5 beta 1 with the supplied 2.x template I'm unable to use the redis metricbeat module. 

"error"=>{"type"=>"mapper_parsing_exception", "reason"=>"Field name bgrewrite.last_status] cannot contain '.'"}

**Comment by ruflin** [comment]
@trevorndodds Thanks for reporting this. I will create a fix for it.

**Comment by ruflin** [comment]
https://github.com/elastic/beats/pull/2695 should solve the issue. I'm kind of surprised you get this issue in 2.4 and not previous versions and that the error is a mapper parsing exception. I still need to do some further investigations here.

**Comment by ruflin** [comment]
@trevorndodds The issue happened in 2.4 as dots are disabled by default: https://www.elastic.co/guide/en/elasticsearch/reference/current/dots-in-names.html#_enabling_support_for_dots_in_field_names

**Comment by trevorndodds** [comment]
@ruflin thanks! I did notice that 2.4 supported dots.in.names but I was hesitant to restart every node in the cluster with the flag for only a few metrics.
