### ISSUE TITLE
Whether it supports AWS cloudwatch streaming data?

### ISSUE THREAD

**Issue by zhaoyi0113** [elastic/beats#26951]
**Describe the enhancement:**

I am deploying applications to AWS including various services. I am planning to use Kibana and Elasticsearch to view metrics from Cloudwatch. I know I can configure metricbeat by using AWS module which works as a crawler to pull metrics data from AWS to Elasticsearch. But there is another mode which is to use Cloudwatch metric stream to stream metics data to analytics platform.

I wonder how does metricbeat support stream data to Elasticsearch. Is there a metrics server I can use to listen on the metric data stream?

**Comment by ChrsMark** [comment]
cc: @kaiyan-sheng

**Comment by kaiyan-sheng** [comment]
Hello, thanks for creating this. But we would kindly ask you to post all questions and issues on https://discuss.elastic.co/c/beats before opening a Github Issue. Your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue or open a new one with more details. Thanks in advance!

For cloudwatch metric streams, unfortunately we currently don't support it in Metricbeat but we are looking into it right now. There is a separate github issue to track the work there. Thanks!!
