### ISSUE TITLE
Add config option to enable debug level log in AWS SDK

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#26985]
We encountered some issues in Filebeat s3 input that the error message does not contain enough information to debug. For example: https://github.com/elastic/beats/issues/23226, response is OK but error is not nil. It would be very helpful if we can enable debug level log in AWS sdk to get more information. 

Thanks @aspacca for your idea!

**Comment by aspacca** [comment]
investigation to be made about how to tie filebeat log level to debug logs for the aws sdk
