### ISSUE TITLE
Metricbeat: collects k8s pods cpu which is lower than actually used

### ISSUE THREAD

**Issue by SperChung-11** [elastic/beats#26986]
Hi, We are using metricbeat to collects k8s pods cpu. In the beginning, it can collects the cpu correctly. After running for serveral weeks or serveral months, we found that the pods cpu metricbeat collects is lower than actually used. Finally, it recovers while we restart the metricbeat. We can see as follows graph. 

1.Metricbeat configuration:
![image](https://user-images.githubusercontent.com/74529952/126419014-7c48346f-4639-47ab-8488-461ffd2f5ca1.png)

2.After restart metricbeat:
![image](https://user-images.githubusercontent.com/74529952/127081121-5d56f195-b63f-4fbe-8f5f-ed888d103679.png)

And also, "docker stats" shows the value of cpu usage is equal to bigger value

For confirmed bugs, please report:
- Version:  7.6.0
- Operating System:  EulerOS 2.7
- Discuss Forum URL:  https://discuss.elastic.co/t/metricbeat-collects-k8s-pods-cpu-which-is-lower-than-actually-used/279215
- Steps to Reproduce: it happenes randomly

**Comment by SperChung-11** [comment]
> This issue doesn't have a `Team:<team>` label.

@

**Comment by ChrsMark** [comment]
cc: @MichaelKatsoulis

**Comment by SperChung-11** [comment]
hi. @MichaelKatsoulis @ChrsMark is this a bug ?

**Comment by MichaelKatsoulis** [comment]
Hi @SperChung-11 ! When the problem occurs have you checked the stats that `kubelet` reports ?

**Comment by SperChung-11** [comment]
Hi, we have checked the kubelet reports, it is ok. And when we restart the metricbeat and the problem was solved

**Comment by SperChung-11** [comment]
Hi, @MichaelKatsoulis i wants to know that how did metricbeat calculate the usage of cpu ? we collects the kubelet's data by **accessing the kubelet metrics/cadvisor directly**, but we found that there are some metrics like **container_cpu_system_seconds_total, container_cpu_usage_seconds_total** and so on. 

container_cpu_cfs_periods_total{container="container-0",id="/kubepods/pod3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5/15d356051b601ba1179c75c76cdd1b01a28b91b2efaf33038a250d862b27c7fb",image="sha256:9d7274349d7d4ac2de2849b70adcb820c308387cd0a8a871206258c8b0c54d9c",name="k8s_container-0_statefulset-mysql-1_iot_3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5_0",namespace="iot",pod="statefulset-mysql-1"} 1.865709e+06 1629874251336
container_cpu_cfs_throttled_periods_total{container="container-0",id="/kubepods/pod3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5/15d356051b601ba1179c75c76cdd1b01a28b91b2efaf33038a250d862b27c7fb",image="sha256:9d7274349d7d4ac2de2849b70adcb820c308387cd0a8a871206258c8b0c54d9c",name="k8s_container-0_statefulset-mysql-1_iot_3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5_0",namespace="iot",pod="statefulset-mysql-1"} 13 1629874251336
container_cpu_cfs_throttled_seconds_total{container="container-0",id="/kubepods/pod3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5/15d356051b601ba1179c75c76cdd1b01a28b91b2efaf33038a250d862b27c7fb",image="sha256:9d7274349d7d4ac2de2849b70adcb820c308387cd0a8a871206258c8b0c54d9c",name="k8s_container-0_statefulset-mysql-1_iot_3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5_0",namespace="iot",pod="statefulset-mysql-1"} 0.068035377 1629874251336
container_cpu_load_average_10s{container="container-0",id="/kubepods/pod3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5/15d356051b601ba1179c75c76cdd1b01a28b91b2efaf33038a250d862b27c7fb",image="sha256:9d7274349d7d4ac2de2849b70adcb820c308387cd0a8a871206258c8b0c54d9c",name="k8s_container-0_statefulset-mysql-1_iot_3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5_0",namespace="iot",pod="statefulset-mysql-1"} 0 1629874251336
container_cpu_system_seconds_total{container="container-0",id="/kubepods/pod3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5/15d356051b601ba1179c75c76cdd1b01a28b91b2efaf33038a250d862b27c7fb",image="sha256:9d7274349d7d4ac2de2849b70adcb820c308387cd0a8a871206258c8b0c54d9c",name="k8s_container-0_statefulset-mysql-1_iot_3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5_0",namespace="iot",pod="statefulset-mysql-1"} 6100.13 1629874251336
100 1004k    0 1004k    0     0  12.1M      0 --:--:-- --:--:-- --:--:-- 12.2M
* Connection #0 to host 10.10.16.14 left intact
container_cpu_usage_seconds_total{container="container-0",cpu="total",id="/kubepods/pod3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5/15d356051b601ba1179c75c76cdd1b01a28b91b2efaf33038a250d862b27c7fb",image="sha256:9d7274349d7d4ac2de2849b70adcb820c308387cd0a8a871206258c8b0c54d9c",name="k8s_container-0_statefulset-mysql-1_iot_3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5_0",namespace="iot",pod="statefulset-mysql-1"} 17130.521556958 1629874251336
container_cpu_user_seconds_total{container="container-0",id="/kubepods/pod3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5/15d356051b601ba1179c75c76cdd1b01a28b91b2efaf33038a250d862b27c7fb",image="sha256:9d7274349d7d4ac2de2849b70adcb820c308387cd0a8a871206258c8b0c54d9c",name="k8s_container-0_statefulset-mysql-1_iot_3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5_0",namespace="iot",pod="statefulset-mysql-1"} 8009.99 1629874251336
container_spec_cpu_period{container="container-0",id="/kubepods/pod3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5/15d356051b601ba1179c75c76cdd1b01a28b91b2efaf33038a250d862b27c7fb",image="sha256:9d7274349d7d4ac2de2849b70adcb820c308387cd0a8a871206258c8b0c54d9c",name="k8s_container-0_statefulset-mysql-1_iot_3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5_0",namespace="iot",pod="statefulset-mysql-1"} 100000
container_spec_cpu_quota{container="container-0",id="/kubepods/pod3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5/15d356051b601ba1179c75c76cdd1b01a28b91b2efaf33038a250d862b27c7fb",image="sha256:9d7274349d7d4ac2de2849b70adcb820c308387cd0a8a871206258c8b0c54d9c",name="k8s_container-0_statefulset-mysql-1_iot_3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5_0",namespace="iot",pod="statefulset-mysql-1"} 200000
container_spec_cpu_shares{container="container-0",id="/kubepods/pod3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5/15d356051b601ba1179c75c76cdd1b01a28b91b2efaf33038a250d862b27c7fb",image="sha256:9d7274349d7d4ac2de2849b70adcb820c308387cd0a8a871206258c8b0c54d9c",name="k8s_container-0_statefulset-mysql-1_iot_3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5_0",namespace="iot",pod="statefulset-mysql-1"} 2048

**Comment by MichaelKatsoulis** [comment]
Hi @SperChung-11 ! Metricbeat gets Kubelet data from `/stats/summary` endpoint. For example about a `redis` instance:
[kubelet-redis-stats.zip](https://github.com/elastic/beats/files/7045199/kubelet-redis-stats.zip)

Container CPU usage is calculated by`cpu.usageCoreNanoSeconds/1e9/nodeCores` where `nodeCores` are the total allocatable cpus of each node (You can get that by describing a node).

Fields `kubernetes.pod.cpu.usage.node.pct` and `kubernetes.container.cpu.usage.node.pct` are created by that calculation and indexed in Elasticsearch.

[Line in code](https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/container/data.go#L121)

**Comment by SperChung-11** [comment]
Hi @MichaelKatsoulis ! Thanks for your answer.  I collects some container ("uid": "3cf49da1-9a3d-49f2-8f29-6f0f83ac23c5") cpu data by `/stats/summary` as follows:
"usageNanoCores": 18102214972987,
"usageNanoCores": 18122076649072,
"usageNanoCores": 18123455645199,
"usageNanoCores": 18126832124362,
![image](https://user-images.githubusercontent.com/74529952/130769689-5a54e76b-22c5-4146-97e6-613f504410a1.png)


using the calculation method, the number of node core is 4 :
18102214972987 / 1e9 / 4 = 4525
![image](https://user-images.githubusercontent.com/74529952/130769429-cdac9785-38e7-4e3c-b172-8aee5434684f.png)

is it right ?

**Comment by MichaelKatsoulis** [comment]
> is it right ?
The calculation is `cpu.usageNanoCores/1e9/nodeCores` as seen in [code](https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/container/data.go#L121) (Sorry for writing usageCoreNanoSeconds before).
So actually in your case it would be `92960300/1e9/4`==`0.02324`==`2,324%`

**Comment by MichaelKatsoulis** [comment]
@SperChung-11  do you still face the same problem or can we close this issue?

**Comment by SperChung-11** [comment]
thanks, @MichaelKatsoulis.
