### ISSUE TITLE
filebeat Postgres module parse log error 

### ISSUE THREAD

**Issue by nguoingoai** [elastic/beats#26980]
version using is 7.13.3 , OS centos7 

Follow instruction at https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-postgresql.html

```
log_line_prefix = '%m [%p] %q%u@%d '
log_duration = 'on'
log_statement = 'none'
log_min_duration_statement = 0
log_destination = 'csvlog'
logging_collector = on
```
Log was exported and put in kibana success but the Grok parsing meet the following error

`Provided Grok expressions do not match field value: [2021-07-20 16:07:24.606 +07,"postgres","hr",4988,"[local]",60f6920d.137c,3,"SELECT",2021-07-20 16:06:21 +07,9/0,0,LOG,00000,"duration: 445.927 ms statement: select * from events_102078;",,,,,,,,,"psql"]`

The raw log line in postgres_log.csv is

`2021-07-20 16:07:24.606 +07,"postgres","hr",4988,"[local]",60f6920d.137c,3,"SELECT",2021-07-20 16:06:21 +07,9/0,0,LOG,00000,"duration: 445.927 ms statement: select * from events_102078;",,,,,,,,,"psql"`

So how can I fix this or what is the right raw log format this module can parse ?

**Comment by ChrsMark** [comment]
cc: @sayden

**Comment by legoguy1000** [comment]
What version of postgres? The module is expecting the timezone to be letters like `UTC`, not `+07`. I'd change that first and then see if it works.

**Comment by sayden** [comment]
Also Postgres module only support default configs. `log_destination` default config is `stderr`. `csvlog`, as you have, is not supported. Closing this but feel free to reopen if you have some related question or still have issues.
