### ISSUE TITLE
topbeat: Filter by mount point

### ISSUE THREAD

**Issue by florentvaldelievre** [elastic/beats#2699]
Hi,

I was wondering if it was possible to filter by mount point ?
Exemple: I have ten partitions per host but I am only interested in '/' mount point. Is it possible ?

Thanks

**Comment by ruflin** [comment]
In metricbeat 5.0 you can use the mount point field (https://www.elastic.co/guide/en/beats/metricbeat/5.0/exported-fields-system.html#_system_filesystem_mount_point) and then apply a filter / processor for it as documented here: https://www.elastic.co/guide/en/beats/metricbeat/5.0/filtering-and-enhancing-data.html#metricbeat-filtering-overview

I'm closing this issue as we try to keep all questions in https://discuss.elastic.co/c/beats/metricbeat For further questions, please open a topic there.

**Comment by andrewkroh** [comment]
For Metricbeat there is a mount_point filter example in the documentation that uses a regular expression. See https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-system-filesystem.html#_filtering
