### ISSUE TITLE
[Agent] Support labels dedot in k8s provider

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#27019]
We need to support label's dedoting or use `flattened` type as proposed at https://github.com/elastic/beats/pull/26801#discussion_r673891761. We need to verify which option works best for us so the scope of this issue is to investigate the option of `flattened` and evaluate if it could be used instead of dedoting the labels (and annotations) as it was the case in Beats.

cc: @MichaelKatsoulis @akshay-saraswat @exekias

**Comment by ChrsMark** [comment]
Regarding the [pros/cons](https://github.com/elastic/obs-dc-team/issues/461) of `flattened` type it seems that the only issue here is that `flattened` type is not yet supported in Kibana (https://github.com/elastic/kibana/issues/25820). 
We are not hitting any licensing issue with Agent and also k8s labels are stored as keywords so we are not affected by [numeric value support](https://github.com/elastic/elasticsearch/issues/61550) issue.

Speaking of this, @exekias @jsoriano do you think it is a good time now to consider using `flattened`. I guess it depends on how quick the support in Kibana will come?

It is true that currently we don't use any labels in our dashboards/visualisations but maybe users want to create custom visualisation based on labels, so I think this is something quite important for us in order to adopt this type.

**Comment by ChrsMark** [comment]
Note that this is tightly coupled with the implementation of https://github.com/elastic/beats/issues/24495. If we aim to use the same interfaces/libs (see the draft PR linked to #24495) with Beats in order to generate metadata then the dettoting comes along: https://github.com/elastic/beats/blob/4933aef29ae45f75930af62a27f066be418aa733/libbeat/common/kubernetes/metadata/resource.go#L92

If we conclude to use `flattened` though in Agent then we can just hardcode the dedot config to false when we call the libs from Agent. Btw sth I miss here is where these fields are defined in Agent, do you know that @exekias?

**Comment by exekias** [comment]
> If we conclude to use `flattened` though in Agent then we can just hardcode the dedot config to false when we call the libs from Agent. Btw sth I miss here is where these fields are defined in Agent, do you know that @exekias? Do we have sth similar to
> 
> https://github.com/elastic/beats/blob/86f00e4716a82e8e461c7cfe8d2baf8c98e2a7dc/libbeat/processors/add_kubernetes_metadata/_meta/fields.yml#L41
> 
> for Agent 🤔 ? It seems that [elastic/package-spec#199](https://github.com/elastic/package-spec/issues/199) is related.

I don't think Agent is defining these anywhere, it relies on default `metrics-*` and `logs-*` mappings, which will default to keyword for these labels. This won't work as soon as you want to use a custom type like flattened. cc @mtojek @jsoriano for awareness

**Comment by jsoriano** [comment]
> Btw sth I miss here is where these fields are defined in Agent

At the moment some common agent fields, as the ones for cloud or containers, are defined on each integration in the `fields/agent.yml` field of each integration, but this doesn't scale long term and is error-prone.

> It seems that elastic/package-spec#199 is related.

Yes, this would be the long-term solution.

**Comment by ChrsMark** [comment]
It seems that even if the `flattened` type looks promising it cannot be used in this specific case at the moment because of:
1. It doesn't support Kibana visualisation etc, sth that we consider quite important for k8s labels.
2. We dont have a way to define it in the mappings until elastic/package-spec#199 is landed.

In this I would suggest to move it forward using the old dedot approach we had in Beats and try to move to `flattened` type when it is better supported (sounds highly possible that we will be dealing with a breaking change with this but we should be able to come with a nice deprecation plan). @exekias @jsoriano let me know if that's ok for you.


@mukeshelastic @akshay-saraswat it would be nice if we could have an estimation about 1, and maybe check again with Kibana folks what is the status and if they plan to work on this soon.
@mtojek this is another case that would take advantage of elastic/package-spec#199 :).

**Comment by ChrsMark** [comment]
Closed  by #27691
