### ISSUE TITLE
[Elastic Agent] Expose httpprof for Elastic Agent

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#27059]
Beats can be run with the `--httpprof` [flag](https://www.elastic.co/guide/en/beats/filebeat/current/command-line-options.html) to expose an http server for [profiling](https://pkg.go.dev/net/http/pprof). For debugging purpose, this should also be supported by Elastic Agent.

If Elastic Agent is started with --httpprof, how will this affect the sub processes? What about the ones written in a different language? How can a subprocess like metricbeat be profiled?

**Comment by jlind23** [comment]
@ruflin shouldn't we close this one and rather use: https://github.com/elastic/beats/issues/29304?

**Comment by ruflin** [comment]
I think this issue can be closed with the recent work that @michel-laterman was doing related pprof.
