### ISSUE TITLE
VOIP monitoring in ELASTIC STACK

### ISSUE THREAD

**Issue by raj467690** [elastic/beats#2707]
Hi All,

Am using Elastic stack for the past few months.Found it really cool and fantastic combination.

But am now more concerned with VOIP monitoring .Is it possible to monitor the call quality and other factors like *packet loss,jitter and latency in Filebeat or Packetbeat?

Is its possible how can be done in few words?

It would be really helpful for my career.

Thanks in advance,
Raj

**Comment by andrewkroh** [comment]
Please do not cross post.

Duplicate: https://discuss.elastic.co/t/voip-monitoring-with-elk/62372

**Comment by raj467690** [comment]
Sorry for creating a cross post :(
