### ISSUE TITLE
[Agent Error logs]:  local error: tls: bad record MAC message recorded in agent logs.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#27099]
**Kibana version:** 7.14 BC4 Kibana Cloud-staging environment

**Browser version:** Chrome, Firefox and edge
**Host OS**: Windows 10, windows server 2016, debian, centos, Catalina.

**Preconditions:**
1. 7.14 BC4 Kibana Cloud-staging environment should be available.

**Build Details:**
```
BUILD 42656
COMMIT 82a4f6a7fa23946667599787cdb1b2d82c1d0dfb
artifact link : https://staging.elastic.co/7.14.0-b3779639/summary-7.14.0.html

```
- Agents on Windows 10, windows server 2016, debian, centos OSs should be installed.

**Steps to reproduce:**
	- Login to Kibana.
	- Navigate to Agents tab.
	- Select 'error' logging level filter on agent logs tab.
	- Observe, local error: tls: bad record MAC message recorded in agent logs.
	
**Expected result:**
 - no error messages are displayed about this

**Screenshot:** 
![image](https://user-images.githubusercontent.com/72375798/127325864-08026ae3-a10b-4909-a534-789123229de3.png)

On mac OS:
![image](https://user-images.githubusercontent.com/72375798/127325924-361c35d4-4bd0-486a-9c55-ec2da7ca0fb9.png)

**Agent logs:**
[elastic-agent-mac.txt](https://github.com/elastic/beats/files/6893305/elastic-agent-mac.txt)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@andresrc @ruflin posting another logs-based error found.  Actual Agent functionality / impact is TBD, we may want to research it to know more before deciding.

**Comment by andresrc** [comment]
Are we able to reproduce this one with 7.15? Thanks!
