### ISSUE TITLE
[Elastic Agent] Agent CA / certs problem on RHEL 7.3 (Requires --insecure to Install successfully)

### ISSUE THREAD

**Issue by charlie-pichette** [elastic/beats#27116]
The RPM installation does not enroll in Fleet on RHEL 7.3.

- Version: Binary: 7.14.0 (build: 331b419cb92cc0029d462b626c53ee5987c8af37 at 2021-07-22 02:24:07 +0000 UTC)
- Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
- Steps to Reproduce: 
	- Create a 7.14.0-BC4 cluster on Elastic Cloud Staging
	- Create a RHEL 7.3 host
	- Download the Elastic Agent RPM package to the host https://staging.elastic.co/7.14.0-b3779639/downloads/beats/elastic-agent/elastic-agent-7.14.0-x86_64.rpm)
	- Install the RPM package (`sudo rpm -vi elastic-agent-7.14.0-x86_64.rpm`)
	- Enroll the agent (`sudo elastic-agent enroll --url=<url> --enrollment-token=<token>`)

This results in the following output:
```
sudo elastic-agent enroll -f --url=<url> --enrollment-token=<token>
2021-07-28T14:43:23.329-0400	INFO	cmd/enroll_cmd.go:405	Starting enrollment to URL: https://fleet-url:443/
Error: fail to enroll: fail to execute request to fleet-server: x509: certificate signed by unknown authority
```

No log files are generated.  Adding `--insecure` allows the enrollment to proceed.

**Comment by EricDavisX** [comment]
the phrasing in the short desc is offering the work-around of --insecure option... but I'd phrase it as this environment / version seems to have some problem with using the self-signed certs from hosted Fleet Server.

The support matrix shows CentOS/RHEL 7 as supported, https://www.elastic.co/support/matrix

And I know we'e tested with .tar.gz deploys and I don't think we've had this problem - so as a guess it seems specific to the RPM use.  we can test more and confirm as needed.

**Comment by EricDavisX** [comment]
@andresrc @nimarezainia @mostlyjason - do we want to review this with any urgency (even if not for 7.14) ?

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have attempted to install rpm agent on rhel 7.3 and observed this issue reproducible on 7.14.0 BC-5 Kibana Cloud environment.

> I know we'e tested with .tar.gz deploys and I don't think we've had this problem

Yes Eric, we have tested this earlier on Ubuntu 20, Ubuntu 18, Centos 8.0 and we have not covered rhel machine. However it was working well on those machines.

Further we have attempted to install .tar.gz agent using install command, available under Add Agent fly-out.
We have observed the same issue **reproducible for .tar.gz** artifact on rhel 7.3.

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/127441920-1d682ea1-fbe7-4722-a3b0-6724490de079.JPG)

**Note:** 
cc: @charlie-pichette 
Thanks
QAS

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have also observed this issue reproducible for .tar.gz and .rpm agents on rhel 8.0 on 7.14.0 BC-5 Kibana Cloud environment.
```
Error: fail to enroll: fail to execute request to fleet-server: status code: 0,                                                                                         fleet-server returned an error: , message: The requested resource is currently u                                                                                        navailable.
Error: enroll command failed with exit code: 1
```

**Screenshot:**
![2](https://user-images.githubusercontent.com/77374876/127449945-ab694dc4-58aa-4fdb-86e2-f990f6413fe1.JPG)

Thanks

**Comment by michalpristas** [comment]
wondering if:
- ca authority is trusted (can we update those?) 
- FIPS is enabled

**Comment by blakerouse** [comment]
Based on the description and error you are using a self-signed certificate, is that correct? From the command line you provided you are not passing in a CA, so is the CA installed into the system?

Based on this documentation you need to use `trust anchor` to get it installed into the system https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-shared-system-certificates

**Comment by EricDavisX** [comment]
I closed a duplicate to this so I'll post the brief notes, and include notes from the other ticket:

Amol had posted logs from his 7.3 system:
{"log.level":"error","@timestamp":"2021-07-29T08:39:09.195-0400","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/output.go","file.line":154},"message":"Failed to connect to backoff(elasticsearch(https://eae9a99ad36e4c8d9bc36c02f47f64f8.us-central1.gcp.foundit.no:443)): Get \"https://eae9a99ad36e4c8d9bc36c02f47f64f8.us-central1.gcp.foundit.no:443\": x509: certificate signed by unknown authority","service.name":"filebeat","event.dataset":"filebeat_monitor-json.log","ecs.version":"1.6.0"}

He notes also that he confirmed that it was note specific to the RPM installer, it happens with .tar.gz as well.  

and Michal replies...
looks like OS issue not the issue of the agent.
are trusted cert authorities up to date

-----------

So, I tested on Debian 10 with the DEB installer and had no issues installing Agent or Endpoint and getting all expected logs.  I also tested on RHEL 8 (I thought it was a v7 os but it wasn't!) with the tar.gz installer as well as the RPM and both worked fine as well.

**Comment by EricDavisX** [comment]
I found I did have a well known working CentOS 7 environment and have used the .tar.gz installer there and had no issues.  I sounds like it may very well be because Charlie / Amol updated something on the template they very likely will have shared for the tests. 

@charlie-pichette do you have any bandwidth to follow thru further?

**Comment by michalpristas** [comment]
i ran a fresch 7.3 machine only thing i ran prior to installing agent was `yum install epel-release` and `yum update`
agent installed and worked OK.

**Comment by EricDavisX** [comment]
@charlie-pichette do you think you'll be able to make time to review the rhel 7.3 image in use here to help confirm our current understnding?

**Comment by charlie-pichette** [comment]
I ran `sudo yum install epel-release` and `sudo yum update` and I still get `Error: fail to enroll: fail to execute request to fleet-server: x509: certificate signed by unknown authority`.

**Comment by EricDavisX** [comment]
I was discussing with Charlie off line, we'll post back a summary -but a short update is that all of the RHEL7.3 templates in the End game vSphere cluster seem to have this, but it works in other 7.3 installs.  we will keep researching

**Comment by charlie-pichette** [comment]
I built a new VM from the RHEL 7.9 ISO and everything work fine.  I am not sure what is going on with the 7.3 template we are cloning in vSphere but I am closing this as it has been shown to work with other 7.3 instances and on the 7.9 instance we will be using in the future.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this issue on 7.15 Snapshot Kibana Cloud environment with new `RHEL 7.9` and below are the observations of it:
- We are successfully able to install elastic-agent with .rpm artifact.
- Required data is generating under Data Streams tab.
- Logs are available for Rhel rpm agent under Logs tab.
- Agent is visible under Endpoints tab when installed with Endpoint Security.

**Build details:**
```
Build: 42976
Commit: 92a4a4e843758b8cf74ea5f387d0a4cadf2d715a
Artifact Link: https://snapshots.elastic.co/7.15.0-2cefb6a4/downloads/beats/elastic-agent/elastic-agent-7.15.0-SNAPSHOT-x86_64.rpm
```
**Screenshots:**
Agents tab:
![2](https://user-images.githubusercontent.com/77374876/128305947-6728fc24-7582-483c-af7a-2fa0092041c2.JPG)

Endpoints tab:
![3](https://user-images.githubusercontent.com/77374876/128305978-01b29484-5195-4b82-b553-f8d25d670d0f.JPG)

Thanks
QAS
