### ISSUE TITLE
Topbeat Index is not getting created

### ISSUE THREAD

**Issue by Bonythomasv** [elastic/beats#2712]
Logs:

[ topbeat]$ /usr/bin/topbeat -c /etc/topbeat/topbeat.yml -e -v
2016/10/06 14:01:16.233026 beat.go:156: DBG  Initializing output plugins
2016/10/06 14:01:16.233060 geolite.go:24: INFO GeoIP disabled: No paths were set under output.geoip.paths
2016/10/06 14:01:16.234436 logstash.go:106: INFO Max Retries set to: 3
2016/10/06 14:01:16.234450 client.go:100: DBG  connect
2016/10/06 14:01:16.239900 outputs.go:126: INFO Activated logstash as output plugin.
2016/10/06 14:01:16.239917 publish.go:232: DBG  Create output worker
2016/10/06 14:01:16.239947 publish.go:274: DBG  No output is defined to store the topology. The server fields might not be filled.
2016/10/06 14:01:16.240053 publish.go:288: INFO Publisher name: .
2016/10/06 14:01:16.240225 async.go:78: INFO Flush Interval set to: 1s
2016/10/06 14:01:16.240236 async.go:84: INFO Max Bulk Size set to: 2048
2016/10/06 14:01:16.240243 async.go:92: DBG  create bulk processing worker (interval=1s, bulk size=2048)
2016/10/06 14:01:16.240275 beat.go:168: INFO Init Beat: topbeat; Version: 1.3.1
2016/10/06 14:01:16.240476 topbeat.go:88: DBG  Init topbeat
2016/10/06 14:01:16.240506 topbeat.go:89: DBG  Follow processes [".*"]
2016/10/06 14:01:16.240514 topbeat.go:90: DBG  Period 30s
2016/10/06 14:01:16.240520 topbeat.go:91: DBG  System statistics true
2016/10/06 14:01:16.240525 topbeat.go:92: DBG  Process statistics true
2016/10/06 14:01:16.240531 topbeat.go:93: DBG  File system statistics true
2016/10/06 14:01:16.240536 topbeat.go:94: DBG  Cpu usage per core false
2016/10/06 14:01:16.240711 beat.go:194: INFO topbeat sucessfully setup. Start running.
2016/10/06 14:02:16.264431 publish.go:109: DBG  Publish: {
  "@timestamp": "2016-10-06T14:02:16.264Z",
  "beat": {
    "hostname": ".",
    "name": "."
  },
  "count": 1,
  "cpu": {
    "user": 18653,
    "user_p": 0.0027,
    "nice": 13,
    "system": 12921,
    "system_p": 0.0012,
    "idle": 51716838,
    "iowait": 39867,
    "irq": 0,
    "softirq": 25,
    "steal": 3977
  },
  "load": {
    "load1": 0,
    "load5": 0.01,
    "load15": 0.05
  },
  "mem": {
    "total": 3975475200,
    "used": 2130919424,
    "free": 1844555776,
    "used_p": 0.54,
    "actual_used": 272654336,
    "actual_free": 3702820864,
    "actual_used_p": 0.07
  },
  "swap": {
    "total": 0,
    "used": 0,
    "free": 0,
    "used_p": 0
  },
  "tags": [
    "dev"
  ],
  "type": "system"
}

2016/10/06 14:02:16.300345 publish.go:109: DBG  Publish: {
  "@timestamp": "2016-10-06T14:02:16.298Z",
  "beat": {
    "hostname": ".",
    "name": "."
  },
  "count": 1,
  "fs": {
    "device_name": "binfmt_misc",
    "total": 0,
    "used": 0,
    "used_p": 0,
    "free": 0,
    "avail": 0,
    "files": 0,
    "free_files": 0,
    "mount_point": "/proc/sys/fs/binfmt_misc"
  },
  "tags": [
    "dev"
  ],
  "type": "filesystem"
}
2016/10/06 14:02:16.300401 publish.go:109: DBG  Publish: {
  "@timestamp": "2016-10-06T14:02:16.298Z",
  "beat": {
    "hostname": ".",
    "name": "."
  },
  "count": 1,
  "fs": {
    "device_name": "tmpfs",
    "total": 397549568,
    "used": 0,
    "used_p": 0,
    "free": 397549568,
    "avail": 397549568,
    "files": 485287,
    "free_files": 485286,
    "mount_point": "/run/user/1001"
  },
  "tags": [
    "dev"
  ],
  "type": "filesystem"
}
2016/10/06 14:02:17.240490 output.go:87: DBG  output worker: publish 119 events
2016/10/06 14:02:17.240536 client.go:146: DBG  Try to publish 119 events to logstash with window size 49
2016/10/06 14:02:17.253811 client.go:227: DBG  update max ok window size: 41 < 49
2016/10/06 14:02:17.253838 client.go:231: DBG  increase window size to: 74
2016/10/06 14:02:17.253847 client.go:124: DBG  49 events out of 119 events sent to logstash. Continue sending ...
2016/10/06 14:02:17.253854 client.go:146: DBG  Try to publish 70 events to logstash with window size 74
2016/10/06 14:02:17.265729 client.go:124: DBG  70 events out of 70 events sent to logstash. Continue sending ...
2016/10/06 14:02:17.265771 single.go:135: DBG  send completed
2

**Comment by Bonythomasv** [comment]
[cloud-user@stcstack-0926-dev-alertsreceiver01 ~]$ cat /etc/topbeat/topbeat.yml
input:
  period: 30
  procs:
  - ".*"
output:
  logstash:
    hosts:
    - logstash URL
    index: topbeat-stc
logging:
  to_files: true
  files:
    path: /var/log/topbeat
    name: topbeat.log
    rotateeverybytes: 10485760 # = 10MB
  selectors: ['*']
  level: debug
shipper:
  tags:
  - dev

**Comment by Bonythomasv** [comment]
[cloud-user@stcstack-0926-dev-alertsreceiver01 ~]$ cat /etc/topbeat/topbeat.yml
input:
  period: 30
  procs:
  - ".*"
output:
  logstash:
    hosts:
    - logstash URL
    index: topbeat-stc
logging:
  to_files: true
  files:
    path: /var/log/topbeat
    name: topbeat.log
    rotateeverybytes: 10485760 # = 10MB
  selectors: ['*']
  level: debug
shipper:
  tags:
  - dev

**Comment by ruflin** [comment]
Please use discuss for questions: https://discuss.elastic.co/c/beats/topbeat Also state there which logstash and elasticsearch version you are using and make sure to format your posts with 3 ticks ` around the code to make it better readable.
