### ISSUE TITLE
Elastic Agent Diagnostics support

### ISSUE THREAD

**Issue by urso** [elastic/beats#27138]
The Elastic Agent currently sends logs and metrics to the monitoring cluster, which currently is the Elasticsearch cluster used to manage Agent. In the standalone case logs and metrics are also available locally.
For debugging purposes and a detailed analysis of ongoing issues, the available data might not be enough. Users might want to share additional information like internal configurations, profiling data, memory allocation details, and more that will allow developers to actually get better insights into observed problems.

We want to provide tools and APIs our users and support can use to collect detailed information often requested by developers to handle support cases including troubleshooting bugs, misconfigurations, instabilities, or performance issues.

**Comment by jlind23** [comment]
@michel-laterman it seems that your work on the diagnostic command overlap this issue, am i wrong?
cc @ruflin

**Comment by ruflin** [comment]
I think we can close this as most of the information listed above is now collected by the `diagnostic` command. We need to keep adding data there.
