### ISSUE TITLE
filebeat-<agent.version>-cisco-asa-asa-ftd-pipeline creates fields network.inner as string 

### ISSUE THREAD

**Issue by hungnguyen-elastic** [elastic/beats#27137]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 7.13.4
- Operating System: NA
- Discuss Forum URL:
- Steps to Reproduce: 
  - Running this log sample through the parser ```filebeat-7.13.4-cisco-asa-asa-ftd-pipeline```, user will get field network.inner as a string field while the filebeat  ECS mapping for this field expects an object - [see here](https://www.elastic.co/guide/en/ecs/master/ecs-vlan.html#_field_reuse_26)
  
   ```
  Jul 29 08:35:29 12.12.12.12 Jul 29 2021 08:35:29 12.12.12.12 : %ASA-6-602304: IPSEC: An outbound LAN-to-LAN SA (SPI= 0xABCXYZ) between 12.12.12.12 and 12.12.12.12 (user= 12.12.12.12) has been deleted.
   ```

**Comment by legoguy1000** [comment]
I can add this to my #26879 PR.
