### ISSUE TITLE
How to use the docker module in metric beats?

### ISSUE THREAD

**Issue by jbh6** [elastic/beats#2718]
Hi

I am using the metric beat 5.0.0-beta1 version (https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-installation.html)  on a centos machine. I have a docker container running on this machine, and I would like to know how can I add the docker module to the config file for metric beat? Has it been released in this version? 

Also, I have a doubt regarding its functionality. If I have multiple metricbeats agent running on a host machine, is it possible that a single metric beats agent will send all the containers information, or will I have to set up multiple metricbeat agents for each container? 

Thanks!

**Comment by ruflin** [comment]
The docker module is not part of the 5.0.0-beta1 release. If you are interested to try it out you can use the snapshot builds: https://beats-nightlies.s3.amazonaws.com/index.html?prefix=metricbeat/ As we just added it feedback is more then welcome.

You can monitor all containers of one host machine by mounting the socket into one of the containers. This is identical to what is documented here with `dockbeat`: https://github.com/Ingensi/dockbeat#run-in-a-docker-container

For questions please use discuss in the future as we try to keep Github for bugs and feature requests: https://discuss.elastic.co/c/beats/metricbeat

Closing this issue but happy to further assist on discuss.

**Comment by jbh6** [comment]
@ruflin , I have created a topic on discuss for further discussion. 
https://discuss.elastic.co/t/optimal-way-for-monitoring-host-and-docker-containers-metrics/62478 

Thanks!
