### ISSUE TITLE
[Agent][8.0-alpha1]: "Error - failed version compatibility check with elasticsearch" on running agent install command.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#27191]
**Kibana version:** 8.0-alpha1-qa Kibana cloud environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
Build: 44759
Commit: fa7fd32e249a095dede8cd0ef676b21e7d4707bc
```

**Preconditions:**
1. 8.0-alpha1 Kibana cloud-qa environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Artifacts used:
https://staging.elastic.co/8.0.0-alpha1-3693e96c/downloads/beats/elastic-agent/elastic-agent-8.0.0-alpha1-windows-x86_64.zip
3. Extract and run Agent install command.
```
.\elastic-agent.exe install  -f `
 --fleet-server-es=https://5f83e162928e49xxxx3eff62b512c8fe.us-central1.gcp.qa.cld.elstc.co:443 `
--fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2Mjc5MDI3OTg1MTQ6VDRvWE5PZURSUkNlRE5JdjdpQxxxxx`
--fleet-server-policy=59d4afe0-f356-11eb-92df-f3671xxxxxx
```
4. Observe errors: `Error - failed version compatibility check with elasticsearch` on running install command.

**Note:**
As we didn't have the hosted (pre-installed) Fleet Server, we attempted to install agent with Policy having Fleet Server integration.
![13](https://user-images.githubusercontent.com/77374876/127865022-5fa54289-bf0a-4542-806f-05286d36f286.JPG)

**Expected Result:**
Agent should be installed on running install command.

**Screenshot:**
![12](https://user-images.githubusercontent.com/77374876/127862023-96182c02-96e8-47a4-afdd-38a09b91c857.JPG)

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@blakerouse mentions in the x-team meeting that this is from our Semver usage / restraint and that it isn’t compatible with the string that is in place for the release:
8.0.0-alpha1

It should be adjusted in Fleet Server and also checked in Beats/Agent side, as well, for a likely adjustment needed.

And he notes that both the recent issues logged by test team are likely the same.  I’ll link them:
https://github.com/elastic/fleet-server/issues/608

**Comment by EricDavisX** [comment]
i'm marking this as a dupe to the above Fleet Server issue and will transfer over the neat cli details.
