### ISSUE TITLE
[Heartbeat] `ignore-https-errors` should work for browsers

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#27202]
TLS options for browser based monitors are complex since it's not the golang HTTP client, but rather the Chromium browser with its own TLS settings that don't line up exactly. We could, however, add support for disabling SSL verification by setting the `ignoreHTTPSErrors` playwright option. We may need to add a capability for ignoring TLS to the CLI args as well.

Another option would be more full support for custom CAs, but I believe that should come later since it's more complex given that CAs for chromium can only be added system-wide, not on a per-monitor basis.

- [x] Synthetics support https://github.com/elastic/synthetics/pull/361
- [x] Heartbeat support https://github.com/elastic/beats/pull/27412
- [ ] Integration support

**Comment by andrewvc** [comment]
I've updated this issue to recommend a new flag instead of using the existing `heartbeat` `ssl.verification_mode` flag. The behavior is sufficiently different that it really should be separated.

**Comment by dominiqueclarke** [comment]
Tested with heartbeat 7.15.0 and @elastic/synthetics `1.0.0-beta.12`. Working as expected all the way through to the UI. 
<img width="1179" alt="Screen Shot 2021-08-20 at 3 51 20 PM" src="https://user-images.githubusercontent.com/11356435/130286636-2a684c7d-2395-4ddc-abc0-ff5c032a2e2e.png">
