### ISSUE TITLE
Filebeat Meraki module bugs

### ISSUE THREAD

**Issue by amemkdm** [elastic/beats#27214]
I have observed that the meraki module is not able to parse all the logs correctly, I have many events have dissect parsing error in the ingested logs.

**Comment by legoguy1000** [comment]
Can u provide specific examples?

**Comment by jamiehynds** [comment]
@amemkdm we're about to start a new integration for Meraki MX, which will replace the current experimental integration. Would you be willing to supply some sample logs (raw) to ensure we have broad event coverage as we build this new integration.
