### ISSUE TITLE
[Metricbeat][System module] psi: pressure stall information

### ISSUE THREAD

**Issue by b-deam** [elastic/beats#27223]
**Describe the enhancement:**

Since 4.2, Linux exposes contention metrics for CPU, Memory, and IO in `procfs` under the  `/proc/pressure` path for a system as a whole, or for [cgroup2](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html) the subdirectory for each cgroup controller in the cgroupfs mount point contains `cpu.pressure`, `memory.pressure`, and `io.pressure` files.

An extra `system` metricset (perhaps called `psi`?) that collects these metrics on a defined interval would be extremely useful, both for specific cgroups and for systems as a whole.

**Further Reading**:
- https://www.kernel.org/doc/html/latest/accounting/psi.html
- https://lwn.net/Articles/759658/
- https://facebookmicrosites.github.io/psi/docs/overview.html

**Comment by ruflin** [comment]
@exekias @fearful-symmetry Would be great to get your take on this.

**Comment by exekias** [comment]
Thanks for bringing this up! Actually @fearful-symmetry have been working cgroups v2 support here: https://github.com/elastic/beats/pull/27242, I see Pressure is actually retrieved.

Would you see this information useful if attached to the process documents?

**Comment by b-deam** [comment]
Not so much `process` documents - but rather the system as a whole (reading directly from `/proc/pressure`, kind of like system load averages are for the system as a whole.

I gave the PR a quick skim, but couldn't tell if that implementation will also allow collection at the host level if no cgroups are in use? Is that correct?

**Comment by exekias** [comment]
That's correct!, @fearful-symmetry would love your thoughts on this

**Comment by fearful-symmetry** [comment]
Considering we're already adding this in cgroups, I don't see any reason why we couldn't add global pressure stats as well. I'm not sure where this would go, though. Maybe just a new `linux/pressure` metricset?

**Comment by b-deam** [comment]
I agree, `linux/pressure` makes more sense than `system` IMO - I also noticed (if you weren't already aware) that the existing [prometheus/profcs package](https://github.com/prometheus/procfs/blob/v0.0.11/proc_psi.go#L59-L99) already includes a method to retrieve these.
