### ISSUE TITLE
[Agent][Windows]: Agent goes to Unhealthy state on reboot and no new data under Data Streams tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#27229]
**Kibana version:** 8.0-alpha1 BC-3 Kibana cloud environment

**Host OS and Browser version:** Windows 10 x64, All

**Build details:**
```
Build: 44993
Commit: 1ddb1eedf72380b1959ece8ece82d9f3bd84949f
Artifact Link: https://staging.elastic.co/8.0.0-alpha1-5d2ed18b/downloads/beats/elastic-agent/elastic-agent-8.0.0-alpha1-windows-x86_64.zip
```

**Preconditions:**
1. 8.0-alpha1 BC-3 Kibana cloud environment should be available.
2. Agent must be installed using Default policy having System and Endpoint Security.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Reboot `Elastic Agent` from Services.
3. Observe no new logs under Logs tab.
4. No new data under Data Streams tab.
5. Agent moves to "Unhealthy" state after few minutes.
6. Unable to change logging level.

**Logs:**
[logs.zip](https://github.com/elastic/beats/files/6929977/logs.zip)

**Endpoint Logs:**
[endpoint-000000.zip](https://github.com/elastic/beats/files/6929973/endpoint-000000.zip)

**Policy:**
[elastic-agent.zip](https://github.com/elastic/beats/files/6929979/elastic-agent.zip)

**Note:**
-  This issue is **not observed** on MAC, Linux tar, Linux .rpm and Linux .deb agents.
- This issue is also reproducible with only System integration.

**Expected Result:**
Agent should come back to Healthy state on reboot and new data should generate under Data Streams tab.

**Screenshots:**
![4](https://user-images.githubusercontent.com/77374876/128154814-5ea6cd8b-1e80-4167-9604-15d9a3e65186.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
Please find below "debug" level agent logs reproduced for another agent:
[Agent2_logs.zip](https://github.com/elastic/beats/files/6930261/Agent2_logs.zip)

Thanks

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX  @fearful-symmetry 

We have also observed that, if we are using windows integration in agent policy[having system integration too], then also agent went to unhealthy state after some time. 

@fearful-symmetry can you please have a look. 

Agent logs at debug level: 
[logs.zip](https://github.com/elastic/beats/files/6930972/logs.zip)

Please let us know if anything else is required. Build details are shared in defect summary.

Thanks
QAS

**Comment by fearful-symmetry** [comment]
Okay, so in the first error logs you posted, I'm seeing this:
```
"message":"Failed to render configuration with latest context from composable controller: fail to extract program configuration: invalid configuration missing outputs configuration","ecs.version":"1.6.0"}
```

However, looking at the config you posted, I can see the output config:
```
outputs:
  default:
    type: elasticsearch
    hosts:
      - 'https://9cf1e392f6fc4d67b3ff623c6cd697e8.us-central1.gcp.foundit.no:443'
```

I'm going to tentatively say that this is _not_ a system issue. This is kind of baffling, though.

**Comment by EricDavisX** [comment]
we have 2 sets of logs (if not more) let's ask the @elastic/agent team to review / triage further.

**Comment by michalpristas** [comment]
> Okay, so in the first error logs you posted, I'm seeing this:
> 
> ```
> "message":"Failed to render configuration with latest context from composable controller: fail to extract program configuration: invalid configuration missing outputs configuration","ecs.version":"1.6.0"}
> ```
> 
> However, looking at the config you posted, I can see the output config:
> 
> ```
> outputs:
>   default:
>     type: elasticsearch
>     hosts:
>       - 'https://9cf1e392f6fc4d67b3ff623c6cd697e8.us-central1.gcp.foundit.no:443'
> ```
> 
> I'm going to tentatively say that this is _not_ a system issue. This is kind of baffling, though.

this is related to standalone and should not have impact on this. what is bothering is beats being restarting/crashing all over, logs from beats would be helpful

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this issue on 7.15.0 BC-1 and on 8.0.0 Snapshot Kibana Cloud environment with Windows agent.
We have found this issue **fixed** now.

**Observations:**
- Agent gets back to "Healthy" status after reboot.
- New data continue to generate under Data Streams tab.

**Build details 7.15.0 BC-1:**
```
Build: 43636
Commit: d791226d9385122f33f4a5ca38fa5369012fbec3
Artifact Link: https://staging.elastic.co/7.15.0-d9929120/downloads/beats/elastic-agent/elastic-agent-7.15.0-windows-x86_64.zip
```

**Build details 8.0.0 Snapshot:**
```
Build: 45534
Commit: 442d9c3274bb923ee48098e4b34c9a71a689605b
Artifact Link: https://snapshots.elastic.co/8.0.0-56a61c29/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip
```
Hence we are **closing** this issue.

Thanks
