### ISSUE TITLE
[Elastic Agent] Heartbeat logs do not show up in Elastic Agent docker image

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/beats#27238]
When running heartbeat in the Elastic Agent docker images, heartbeat logs do not appear. Logs cannot be viewed from the logs component on the fleet agents page.

Heartbeat is confirmed to be working and indexing documents.

<img width="1289" alt="Screen Shot 2021-08-04 at 2 44 05 PM" src="https://user-images.githubusercontent.com/11356435/128237869-e6e24640-7389-46b3-8046-39fc27622248.png">

For confirmed bugs, please report:
- Version:   7.15.0-SNAPSHOT, 8.0.0-SNAPSHOT
- Operating System: MacOS
- Steps to Reproduce: 

1. Bring up the elastic stack with the elastic-package cli tool. Run `elastic package stack up`.
2. Log into kibana
3. Navigate to the fleet integrations page and choose Synthetics. You can create a basic monitor by clicking add integration, naming the integration, adding a simple url like `https://www.elastic.co`, and clicking save.
4. Navigate to the Uptime overview to observe that heartbeat is running and indexing documents.
5. Navigate to the fleet agent page associated with the default policy. Observe that heartbeat logs are not available.

**Comment by michalpristas** [comment]
do we see some heartbeat related logs?  is it running?
i believe permissions should be set correctly and we are allowed to create all the things needed

**Comment by ruflin** [comment]
We indeed miss the permissions in the list. We should get this fixed and backported to 7.14. In addition we should follow up to the Elastic Agent package to make sure support for it is also added there.

@dominiqueclarke Could you take care of the Kibana change needed?

**Comment by ruflin** [comment]
I opened https://github.com/elastic/integrations/pull/1460 on the package side to be ready as soon as the Kibana implementation is using the package: https://github.com/elastic/kibana/issues/107738

**Comment by dominiqueclarke** [comment]
- [ ] elastic/integrations#1460 
- [ ] elastic/kibana#107989

Both these PRs have been merged, and the heartbeat logs are appearing appropriately. Closing this ticket 
<img width="1206" alt="Screen Shot 2021-08-18 at 4 52 05 PM" src="https://user-images.githubusercontent.com/11356435/129970742-fe475635-5498-4936-bda8-39313dc728ca.png">
