### ISSUE TITLE
Agent stops sending data on re-assigning to another policy or on changing log level.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#27259]
**Kibana version:** 8.0-alpha1 BC-3 Kibana cloud environment

**Host OS and Browser version:** Windows 10 x64, All

**Build details:**
```
Build: 44993
Commit: 1ddb1eedf72380b1959ece8ece82d9f3bd84949f
Artifact Link: https://staging.elastic.co/8.0.0-alpha1-5d2ed18b/downloads/beats/elastic-agent/elastic-agent-8.0.0-alpha1-windows-x86_64.zip
```

**Preconditions:**
1. 8.0-alpha1 BC-3 Kibana cloud environment should be available.
2. Agent must be installed using Default policy having System Integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Change logging level to `debug`
3. Observe Agent stopped sending data under Data Streams tab.
4. Observe no new logs under Logs tab.

**Logs:**
[logs.zip](https://github.com/elastic/beats/files/6938107/logs.zip)

**Expected Result:**
Agent should send new data on re-assigning to another policy and on changing log level.

Note:
- Similar issue is observed on assigning agent to new policy
-  This issue is not observed for Linux agents.

**Comment by amolnater-qasource** [comment]
@karanbirsingh-qasource Please review.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
This issue is similar to issue reported at https://github.com/elastic/beats/issues/27229
We are blocked to test windows agents, as its failing on almost every action performed on it.

Please let us know if anything else is required from our end.
Thanks

**Comment by EricDavisX** [comment]
@andresrc This sounds very severe, I will send a note to the team via email to follow through - unsure if we can / should target a near term fix.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
While testing on 7.15.0 Snapshot we have found this issue reproducible there as well.
- Windows Agent stop sending data on re-assigning to another policy and on changing logging level. After sometime agent also moves to Unhealthy state.

**Build details:**
```
Build: 43271
Commit: 00fcc2cd00d309f4c17db4ec7d552bc54fbd1b81
Artifact Link: https://snapshots.elastic.co/7.15.0-83f2fe8a/downloads/beats/elastic-agent/elastic-agent-7.15.0-SNAPSHOT-windows-x86_64.zip
```
**Logs:**
[logs.zip](https://github.com/elastic/beats/files/6967516/logs.zip)

Further we are still blocked to test on Linux and MAC machines because of Vsphere blocker issue.

Thanks
QAS

**Comment by amolnater-qasource** [comment]
We have also observed this issue, on adding any integration to the Policy.
- Agent goes to unhealthy state and no new data under Data Streams tab.

Thanks

**Comment by michalpristas** [comment]
this can be found in Metricbeat
`Exiting: data path already locked by another beat. Please make sure that multiple beats are not sharing the same data path`
what's weird is that even with monitoring enabled i dont see monitoring logs. instead there's just one log file which looks like contains logs from multiple processes.

what it looks like is that agent does not cancel/close/restart its beats as PID stays the same. 
this is indeed very weird and looks like a new issue

**Comment by EricDavisX** [comment]
@amolnater-qasource we can test this on the 8.0 snapshot build, and in 7.15 BC please.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this issue on 7.15.0 BC-1 and on 8.0.0 Snapshot Kibana Cloud environment with Windows agent.
We have found this issue **fixed** now.

**Observations:**
- Agent not going Unhealthy on re-assigning to another policy.
- Agent remains sending new data on changing log level and assigning new policy.

**Build details 7.15.0 BC-1:**
```
Build: 43636
Commit: d791226d9385122f33f4a5ca38fa5369012fbec3
Artifact Link: https://staging.elastic.co/7.15.0-d9929120/downloads/beats/elastic-agent/elastic-agent-7.15.0-windows-x86_64.zip
```

**Build details 8.0.0 Snapshot:**
```
Build: 45534
Commit: 442d9c3274bb923ee48098e4b34c9a71a689605b
Artifact Link: https://snapshots.elastic.co/8.0.0-56a61c29/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip
```
Hence we are **closing** this issue.

Thanks
