### ISSUE TITLE
[MAC-Bigsur-11.0.1]: Inconsistent behaviour on rebooting MAC agent when Endpoint is in Agent Policy

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#27251]
**Kibana version:** 7.14.0 released Kibana cloud environment

**Host OS and Browser version:** MAC Bigsur 11.0.1, All

**Build details:**
```
Build: 42747
Commit: f032cf9bdbf6f74b70db5e43b7b1d30f5de22d3e
Artifact Link: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.14.0-darwin-x86_64.tar.gz
```

**Preconditions:**
1. 7.14.0 released Kibana Kibana cloud environment should be available.
2. MAC Agent must be installed using Default policy having System and Endpoint Security.

**Observations:**
- On installing a MAC agent, it shows up "HEALTHY" on Kibana UI
- No Logs are observed till then and then gets offline for approximately 2 minutes.
- Gets back Healthy and then generate Logs and data under Data Streams tab.

Further on rebooting the MAC machine we observed below inconsistent issues. 
<HTML>
<BODY TEXT="#000000">
<TABLE FRAME=VOID CELLSPACING=0 COLS=5 RULES=NONE BORDER=0>
	<COLGROUP><COL WIDTH=86><COL WIDTH=86><COL WIDTH=173><COL WIDTH=207><COL WIDTH=218></COLGROUP>
	<TBODY>
		<TR>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" WIDTH=86 HEIGHT=18 ALIGN=CENTER VALIGN=MIDDLE><B>Issue No.</B></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" WIDTH=86 ALIGN=CENTER VALIGN=MIDDLE><B>Endpoint</B></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" WIDTH=173 ALIGN=CENTER VALIGN=MIDDLE><B>Reboot behaviour</B></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" WIDTH=207 ALIGN=CENTER VALIGN=MIDDLE><B>Time Duration for reboot Issue</B></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" WIDTH=218 ALIGN=CENTER VALIGN=MIDDLE><B>Remarks</B></TD>
		</TR>
		<TR>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" HEIGHT=34 ALIGN=CENTER VALIGN=MIDDLE><B>Issue 1</B></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Bigsur 11.0.1</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Agent goes Unhealthy</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>6-8 minutes</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Agent gets back healthy after 6-8 minutes of being unhealthy</TD>
		</TR>
		<TR>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" HEIGHT=34 ALIGN=CENTER VALIGN=MIDDLE><B>Issue 2</B></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Bigsur 11.0.1</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Once gets healthy and then Agent goes offline</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Approximately 7 minutes</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Agent gets back healthy after minutes of being offline</TD>
		</TR>
	</TBODY>
</TABLE>
</BODY>

</HTML>

**Agent Policy Used:**
[elastic-agent.zip](https://github.com/elastic/beats/files/6937207/elastic-agent.zip)

**Logs for Issue 1:**
[elastic-agent-e127fc-logs.zip](https://github.com/elastic/beats/files/6937210/elastic-agent-e127fc-logs.zip)
[endpoint-000000.zip](https://github.com/elastic/beats/files/6937212/endpoint-000000.zip)

**Logs for Issue 2:**
[elastic-agent-e127fc-logs.zip](https://github.com/elastic/beats/files/6937215/elastic-agent-e127fc-logs.zip)
[endpoint-000000.zip](https://github.com/elastic/beats/files/6937217/endpoint-000000.zip)

**Note:**
- Issue reproduced ratio 3:1:1
 <HTML>
<BODY TEXT="#000000">
<TABLE FRAME=VOID CELLSPACING=0 COLS=2 RULES=NONE BORDER=0>
	<COLGROUP><COL WIDTH=86><COL WIDTH=174></COLGROUP>
	<TBODY>
		<TR>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" WIDTH=86 HEIGHT=34 ALIGN=CENTER VALIGN=MIDDLE><B><BR></B></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" WIDTH=174 ALIGN=CENTER VALIGN=MIDDLE><B>MAC Bigsur Endpoints tested</B></TD>
		</TR>
		<TR>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" HEIGHT=18 ALIGN=CENTER VALIGN=MIDDLE><B>Issue 1</B></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE SDVAL="3" SDNUM="1033;">3</TD>
		</TR>
		<TR>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" HEIGHT=18 ALIGN=CENTER VALIGN=MIDDLE><B>Issue 2</B></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE SDVAL="1" SDNUM="1033;">1</TD>
		</TR>
		<TR>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" HEIGHT=18 ALIGN=CENTER VALIGN=MIDDLE><B>No Issue</B></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE SDVAL="1" SDNUM="1033;">1</TD>
		</TR>
	</TBODY>
</TABLE>
</BODY>

</HTML>

- These issues are not reproducible on Catalina 10.15.6

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
Please find debug level logs reproduced for Issue 1 below:
[logs.zip](https://github.com/elastic/beats/files/6937793/logs.zip)

Thanks

**Comment by EricDavisX** [comment]
@amolnater-qasource - It would be helpful to isolate if this was due to the Endpoint Integration being in play, if you could do one or two more iterations without it to get some stats.  Still, it seems severe, good to know it is not occuring on older macOS versions (like Catalina).  I'll add it to the urgent list.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We are currently blocked for testing using Endpoints because of VSphere issue. We will test this as soon as Vsphere issue will be resolved.

Thanks

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
> It would be helpful to isolate if this was due to the Endpoint Integration being in play, if you could do one or two more iterations without it to get some stats.

We have revalidated this issue on 2 different Bigsur 11.0. We installed MAC agent with Default policy having only System integration and found this issue not reproducible.
- Agent directly gets installed with "Healthy" state.

**Build details:**
```
Build: 42747
Commit: f032cf9bdbf6f74b70db5e43b7b1d30f5de22d3e
Artifact Link: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.14.0-darwin-x86_64.tar.gz
```

**Note:**
This issue is only reproducible if agent is installed with Policy having Endpoint Security integration before installation.

Please let us know if anything else is required from our end.
Thanks

**Comment by EricDavisX** [comment]
@ferullo do you have any ideas why this is problematic only when Endpoint is included in the Agent policy?  Anything seen on your side of the testing house?

**Comment by ferullo** [comment]
I don't see anything in the Agent or Endpoint logs to indicate agent is unhealthy. This happens with a 7.14.0 Kibana and 7.14.0 Agent?

**Comment by amolnater-qasource** [comment]
@ferullo Yes we were using 7.14.0 Kibana[released production] environment and 7.14.0 Agent.
- We installed the MAC agent with Default policy having System and Endpoint Security. We observed the inconsistent behaviour of agent after installation as shared above.

Thanks

**Comment by EricDavisX** [comment]
@amolnater-qasource can you re-test please with 7.15 BC?  I'd like to raise this as urgent, and if it is still reproducible (not sure if we have super easy vSphere access at this point, but maybe soon we will).

**Comment by ferullo** [comment]
@amolnater-qasource if you can reproduce this please reach out to @willyu-elastic and @ricardoungureanu for help.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have re-validated these inconsistent issues on 7.15.0 BC-4 Kibana Cloud environment with Bigsur 11.0.1.
We installed 2 different mac agents and we have below observations.
**Observations:**
- No Unhealthy status observed after installation for both of the Bigsur agents.
- Agent didn't get offline after installation.
- After reboot agents came back healthy and no Unhealthy status observed.

**Build details:**
Build: 43886
Commit: 29a6969dc230abf16dc65a41c535cb534ae64fa7
Artifact Link: https://staging.elastic.co/7.15.0-9e0972b3/downloads/beats/elastic-agent/elastic-agent-7.15.0-darwin-x86_64.tar.gz

As these issues are **not reproducible** on 7.15.0 BC-4 and **closing** this ticket.
Thanks
