### ISSUE TITLE
[Agents]: Agent is not uninstalling completely on running uninstall command.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#27255]
**Kibana version:** 8.0-alpha1 BC-3 Kibana cloud environment

**Host OS and Browser version:** Windows 10 x64, All

**Build details:**
```
Build: 44993
Commit: 1ddb1eedf72380b1959ece8ece82d9f3bd84949f
Artifact Link: https://staging.elastic.co/8.0.0-alpha1-5d2ed18b/downloads/beats/elastic-agent/elastic-agent-8.0.0-alpha1-windows-x86_64.zip
```

**Preconditions:**
1. 8.0-alpha1 BC-3 Kibana cloud environment should be available.
2. Agent must be installed using Default policy having only System.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Elastic\Agent and run Agent uninstallation command `.\elastic-agent.exe uninstall -f`
3. Attempt to delete Elastic folder.
4. Observe error message "file is open in another program".
5. Observe few folders remained and didn't get remove on agent uninstallation command.

**Note:**
-  User is able to delete Elastic folder after restarting machine.

**Expected Result:**
- Agent should uninstall completely on running uninstall command.
- No open services should be remained after uninstall.

**Screenshots:**
![5](https://user-images.githubusercontent.com/77374876/128332231-6f515583-282c-4ec4-86ed-8d657f46e5bf.JPG)

**Comment by amolnater-qasource** [comment]
@karanbirsingh-qasource Please review

**Comment by EricDavisX** [comment]
This is high severity, but I can see if we don't want to call it a blocker for 8.0 Alpha release.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
While testing on 7.15.0 Snapshot we have found this issue reproducible there as well.
- Agent folders are not removed completely on running uninstall command. 

**Build details:**
```
Build: 43271
Commit: 00fcc2cd00d309f4c17db4ec7d552bc54fbd1b81
Artifact Link: https://snapshots.elastic.co/7.15.0-83f2fe8a/downloads/beats/elastic-agent/elastic-agent-7.15.0-SNAPSHOT-windows-x86_64.zip
```
Thanks
QAS

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this issue on 7.15.0 BC-1 and found it **fixed** now.
- Agent is uninstalled completely on running uninstall command.

**Build details:**
```
Build: 43636
Commit: d791226d9385122f33f4a5ca38fa5369012fbec3
Artifact Link: https://staging.elastic.co/7.15.0-d9929120/downloads/beats/elastic-agent/elastic-agent-7.15.0-windows-x86_64.zip
```

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/130406023-f9c4c682-cff3-4649-b55c-df97fabf6f40.JPG)

Hence we are **closing** this issue.
Thanks
