### ISSUE TITLE
Filestream input: Fingerprint for inode race detection

### ISSUE THREAD

**Issue by urso** [elastic/beats#27278]
Log collection using the filestream or logs input sometimes can treat an old file as a new file if we are seing an inode being reused. The `clean_removed` setting allows us to remove the state from the registry more early (filestream input can even detect removal asynchronously), but especially with autodiscovery in place we might have the input being shutdown before we managed to detect that the file was removed.

In order to better detect the inode reuse race condition, we want the harvester/prospector to add a fingerprint to the file metadata in the registry. The fingerprint would be computed from the first 4KB (configurable). The harvester (prospector) would check the fingerprint after opening the file, in order to check that the contents matches the original file.

https://github.com/elastic/beats/issues/19990 Also discusses fingerprinting for identity tracking. But the solution proposed here is supposed to be used in conjunction with any other identity tracking we already have in place.

**Comment by nimarezainia** [comment]
This issue will be addressed by https://github.com/elastic/beats/issues/34419
(@belimawr & @pierrehilbert please confirm and ensure this use case is addressed in sprint 10)

**Comment by pierrehilbert** [comment]
I will close this one for now and we will reopen it if it's not fixed by https://github.com/elastic/beats/issues/34419
