### ISSUE TITLE
Elastic Agent - CA file removal bug. Causing excessive network sessions. 

### ISSUE THREAD

**Issue by PublicDisplayName** [elastic/beats#27272]
- Version:  Fleet upgrade from 7.13.3-4 "Others may be effected unable to test"
- Operating System: Windows Server 2016/2019
- Discuss Forum URL: https://discuss.elastic.co/t/elastic-7-13-3-update-to-7-13-4-ouch-that-was-an-interesting-bug/280354

Steps to Reproduce: 
1. Have 7.13.3 or .4 install with a local CA file if it is in Agent folder. 
1A. Most common failures are on 7.13.4
2. In fleet select upgrade agent. 
3. Wait for upgrade to complete. If agent failed upgrade these are the ones you want to look at. 
4. Check folder for to verify CA file still exist. 
5. Rerun upgrade. -- This is where its 50/50. Unable to find exact failure point. 
6. Upgrade removes CA certificate on server OS on upgrade. Dose not seem to happen on Win 10.
7. If agent upgrade is successful CA file is missing a large part of the time. Preventing connection to Elastic but in Fleet the agent is healthy. Requires manual check of folder and agent logs as nothing is streamed to Elastic. 

The failure will on occasion create an issue with the agent attempting to connect to elastic will spawn unlimited network connection request with no success due to untrusted certificate. Several failures have resulted in agent attempting 17,000 network session connections with no logs being created. This results in a 1Gb link being fully utilized.

**Comment by michalpristas** [comment]
is CA file sitting in a root of Agent dir or do you put it somewhere more deeply?

**Comment by andresrc** [comment]
@EricDavisX Let's try to reproduce with 7.14.1

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource can help I think.  Thanks Diksha!

**Comment by EricDavisX** [comment]
Diksha slacked me an update:
Hi Eric We have attempted it [and was] able to install 7.13.4 agent once on 7.14.0 self managed kibana. After upgrading agent we observed agent was upgraded however went to unhealthy state. 

[it] is very slow and taking around 7-8 minutes to fetch any tab. So we are unable to pull current logs [to help compare symptoms].

@dikshachauhan-qasource thanks for the efforts, I know our test env is under strain and not working well.  Can you attempt this on AWS based Windows hosts when you're next on-line?  We can keep trying and pair up with Engineering to resolve it.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX , For now also, we tried to run things on aws windows server 2019. Beacuse of Instance type selected as t2.micro I think instance running very hard with less memory. We reattempted with t2.medium instance type but anyhow instance got corrupted. However, surely we will try again with better instance type and will let you know.

Thanks
QAS

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have tried to reproduce the issue on 7.14.1 self managed Kibana with 7.13.4 agent upgrade using certs. However, found it unable to reproduce.

**Observations:**
- We were successfully able to upgrade the agent with local CA file in Agent folder.
- CA folder was still available under installed \Elastic\Agent after agent was upgraded successfully.
- We couldn't find any logs data missing .

Screenshots:
![image1](https://user-images.githubusercontent.com/72375798/133432352-3c718418-85ce-4ac9-90ad-652ed10908a6.png)

![image2](https://user-images.githubusercontent.com/72375798/133432377-16143d72-b85a-449c-90f4-2defba8fbc05.png)

![image3](https://user-images.githubusercontent.com/72375798/133432395-7d8296c2-5e6a-46be-a72c-e30d44bb6b44.png)

![image4](https://user-images.githubusercontent.com/72375798/133432417-80a84504-b138-4802-bbd5-36bb9c8fa4dc.png)

Please let us know if further is required at our end.

Thanks
QAS

**Comment by EricDavisX** [comment]
With this confirmation, we need more info to push this on - there is some missing piece of data that we cannot (have not been able to yet) guess, to enable us to see the problem, so we can address it.

**Comment by PublicDisplayName** [comment]
When I was able to trigger the failures it was not a single agent being updated. Try a mix of 7.13.3 and 7.13.4 and at least 10 or more agent updates. Normally the machine will have been on for 30+ days under load before which would cause Endpoint to fail to unload from the OS which then caused the upgrade to fail and agent will remain the original. If it was continued with the failed Endpoint removal and it was successful in the update it wipes the certificate from the agent folder but not all the time "strange behavior". Manually running .\elastic-endpoint uninstall on the target machine would normally end with the same results with endpoint uninstall failing to unload which causes issues with agent being cleanly updated. Almost like agent uninstall moved to the backup force removal and uses the elastic-agent in the data folder which is a clean wipe of the folder at least is has been every time I've resorted to using it.

Unverified but worth noting when a pending updates are waiting on a restart then the agent is installed after updates is normally when oddities happen. 2021-06,07 were both very troublesome. 2021-06 causes considerable issues across the board but was never able to track down why. 

Not sure what changed in 7.14.1 or if it was just OS based but I'm unable to reproduce the issue with the cert being removed from the Agent folder any more. So far 95% of the upgrades from 7.14.0 to .1 have gone off without a hitch. The 5% was due to various unforeseen issues and can be caulked up to OS related issues. Did happen to notice upgrades will fail if your target machine is behind a round robin load balancer.

I appreciate you awesome guys looking into this odd issue. For now I'm going to close out as it's very difficult to pin down and hasn't happened again with 7.14.1. If it does happen I'll be sure to let you know.

**Comment by EricDavisX** [comment]
Thanks so much - this give us yet even more info to help increase our minimum standards for asserting things are 'ok' during upgrade and uninstall usage.  It isn't new that we'd want to focus on stability/scale data being ingested prior to running a given automation or manual test, but it can inform our priority on it's need.  @ruflin @andresrc fairly helpful.
