### ISSUE TITLE
[Heartbeat] Monitor - Add ability for check an array of objects from a JSON payload response

### ISSUE THREAD

**Issue by gchiartosini** [elastic/beats#27283]
**Describe the enhancement:**
Add the ability for check an array of objects from a JSON payload response.

**Describe a specific use case for the enhancement or feature:**
I received a sample JSON payload containing an array of objects in my Heartbeat HTTP monitor:
`{
  "result": {
    "status": "OK"
  },
  "something": [
    {
        "item1": "value1",
        "item2": "value2"
    },
	{
        "item1": "value3",
        "item2": "value4"
    }
  ]
}`

where the HTTP monitor option would be able to check response using something like:
`check.response:
    status: [200]
    json:
      - description: equals
        condition:
          equals:
            something[0].item1: "value1"`

or
`check.response:
    status: [200]
    json:
      - description: equals and exists
        condition:
          and:
            - equals:
                result.status: "OK"
            - has_fields: ['something[0].item1']`

Furthermore, the ability to verify the size of the array would also be useful.

**Comment by jsoriano** [comment]
@gchiartosini would synthetics cover your use case? https://www.elastic.co/guide/en/observability/7.14/synthetic-monitoring.html

**Comment by gbschenkel** [comment]
I would like to heartbeat check objects on JSON array. I saw this subject keep been abandoned. #11884 #12490 #13982
And I can't see how synthetic-monitoring can help with that. If synthetic-monitoring is able to read a JSON array, why can't heartbeat do the same?

I am trying monitoring Brazilian Open Banking API Status, but heartbeats can't do it on a simple way.
Brazilian Open Banking are using this type of structure:
```
{
  "data": {
    "status": [
      {
        "code": "SCHEDULED_OUTAGE",
        "explanation": "Manutenção Planejada",
        "detectionTime": "2020-01-01T01:00:00Z",
        "expectedResolutionTime": "2020-01-01T01:00:00Z",
        "updateTime": "2020-01-02T01:00:00Z",
        "unavailableEndpoints": [
          "https://api.banco.com.br/open-banking/channels/v1/branches"
        ]
      },
      {
        "code": "PARTIAL_FAILURE",
        "explanation": "Falha na execução do serviço",
        "detectionTime": "2020-01-01T01:00:00Z",
        "expectedResolutionTime": "2020-01-01T01:00:00Z",
        "updateTime": "2020-01-02T01:00:00Z",
        "unavailableEndpoints": [
          "https://api.banco.com.br/open-banking/channels/v1/electronic-channels"
        ]
      }
    ],
    "links": {
      "self": "https://api.banco.com.br/open-banking/discovery/v1/status"
    },
    "meta": {
      "totalRecords": 1,
      "totalPages": 1
    }
  }
}
```
accessible by using the specific url:
https://api.[bank.com.br]/open-banking/discovery/v1/status or
https://openbanking.[bank.com.br]/open-banking/discovery/v1/status

I would like to use just `data.status.[0].code: OK` or `data.status.0.code: OK`

**Comment by gchiartosini** [comment]
> @gchiartosini would synthetics cover your use case? https://www.elastic.co/guide/en/observability/7.14/synthetic-monitoring.html

I agree with what @gbschenkel has written.
Also I am already in production environment with a hearbeat on premise installation and I cannot foresee an architectural change to install the synthetics solution currently only available on docker.

**Comment by andrewvc** [comment]
Thanks for all the feedback, I've opened https://github.com/elastic/beats/pull/28073 to improve the validation of JSON responses by validating with `gval` under the hood. Let me know in the PR if there are any concerns or other thoughts about the approach there.
