### ISSUE TITLE
Agent & Logs Application issue:  7.12.X used to be able to read from multiple indices?

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#27282]
I have dropped this issue in from a slack conversation, unsure how to get it to the Logs team, we may want to transfer it from Beats repo at some point:

before 7.13, in the Logs application settings, we could get logs from several indices such as logs-, filebeat-.  

When I upgraded to 7.13, I kept filebeat-* in the indices read by the Logs application. I have deployed 4 elastic-agents... I wanted to do some debug, and set the logging level accordingly. But in the Elastic-Agent logs, (in Elastic-Agent page), I spent hours waiting for some lines of log to come in...and I could not understand why nothing appeared. I reinstalled my agents and so on. 

I realized that I had to go the Logs application settings and switch for Logs-* instead of filebeat-* . And back to the Elastic-Agent log panel, it worked

Conclusion: please could you have the Logs application in observability be able to read many indices instead of 1 only like before in 7.12?

**Comment by weltenwort** [comment]
This seems to be an issue on the Kibana side. More specifically, the agent logs page that embed the logs stream doesn't define their own log source, but rely on the space-specific user configuration. They should use the `defineInternalSourceConfiguration` function exposed on the `infra` plugin's `setup` contract to register a space-independent source configuration targeting the agent logs.

**Comment by weltenwort** [comment]
I have created elastic/kibana#107920 to track this.

**Comment by EricDavisX** [comment]
let's close this out then, thanks so much all.
