### ISSUE TITLE
Filebeat 5.0beta1 with kafka output: batches not fully acked are resend again

### ISSUE THREAD

**Issue by psychonaut** [elastic/beats#2735]
This is follow up to https://discuss.elastic.co/t/filebeat-5-0beta1-with-kafka-output-multiplication-of-log-lines/62513

For confirmed bugs, please report:
- Version: filebeat 5.0beta1
- Operating System: centos 7
- Steps to Reproduce:

**Comment by urso** [comment]
Code fix + minor improvements in #2737

**Comment by ruflin** [comment]
Closing this as https://github.com/elastic/beats/pull/2737 was merged.

@psychonaut The fix should be available very soon in the snapshot builds here: https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/ It would be great if you could test it. It will also be backported to the 5.0 branch.

**Comment by psychonaut** [comment]
is fix included in 5.0rc1?

**Comment by ruflin** [comment]
@psychonaut Unfortunately it missed the 5.0rc1 release train by a few hours but it will be part of the next release.
