### ISSUE TITLE
[Agent] Determining Agent Capabilities in fleet

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#27366]
Some integrations like elastic synthetics are only able to run on certain agents. The current user experience is poor because a user might configure the integration and deploy it to a group of agents that have no capability to run it! The only feedback the user would get his errors in the agents logs (and the lack of data from their selected integrations).

One approach to fixing this would be to have greater awareness agent capabilities throughout fleet and agent. What we need is a workflow where integrations like synthetics can only be applied to agent policies that can run the "complete" image. We also need to have agent policies that can only be joined to by agents that can run the "complete" image. This would mean that we need to distinguish between policies that apply to the standard agent and the "complete" agent. This distinction would need to be made by fleet and elastic agent itself when subscribing to agent policy.

I'm open to other approaches to improving this experience if others have thoughts!

**Comment by blakerouse** [comment]
I think this relates to status reporting and the ability to report a status per input defined in the policy. That way in the case that an input is added to a policy that the Elastic Agent doesn't support it can report the status of not capable and give a reason.

I think this relates to #26457 and #22396

**Comment by andrewvc** [comment]
@blakerouse sort of, we want this to happen *before* you save the monitor.

**Comment by ruflin** [comment]
This is similar to when a user wants to collect windows metrics but only has linux boxes. Ideally we should warn the user in advance. One more challenge here is that it might not apply to all Elastic Agents. Lets assume the users created a policy with some Elastic Agents using the "complete" docker image and some don't. This works fine to configure pings but not for synthetics. What should we do in this scenario?
