### ISSUE TITLE
Functionbeat v.7.14.0 Failure to deploy bug

### ISSUE THREAD

**Issue by ScottHoward4** [elastic/beats#27372]
For confirmed bugs, please report:
- Version: 7.14.0
- Operating System: Windows, Mac, and Linux 
- Steps to Reproduce: Simply follow the quick start guide here- https://www.elastic.co/guide/en/beats/functionbeat/current/functionbeat-installation-configuration.html
- Description: When deploying functionbeat, the deploy fails and gives the error `Function: PublicApiFunctionbeat, could not deploy, error: bucket 'functionbeat-publicapi-logging' already exist and you don't have permission to access it: MissingRegion: could not find region configuration
Fail to deploy 1 function(s)`

We are sure that the accounts/credentials used were correct and the environment variables were properly set. We fixed the error by downloading an earlier version (7.12.1). Using the exact same configuration and environments, we got a different error message that was a simple fix. After making slight adjustments, functionbeat worked properly. We tried this on Windows, Mac, and WSL2 and got the same error on all 3 systems.

**Comment by chemalopezp** [comment]
Same here, it is also happening on 7.14.1, actually it seems the bug resurrected after 7.13.4. 

Ironically, that version had a bug with the region where the functionbeat stack was deployed, so it is getting tricky (I had to rollback to 7.10). Could be that the attempt to solve the region bug messed with the bucket region?

**Comment by talovicnedim** [comment]
> Same here, it is also happening on 7.14.1, actually it seems the bug resurrected after 7.13.4.
> 
> Ironically, that version had a bug with the region where the functionbeat stack was deployed, so it is getting tricky (I had to rollback to 7.10). Could be that the attempt to solve the region bug messed with the bucket region?

I tested this with 7.10.0, 7.7.13, and 8.2.0 and still get the same error. I provided AWS root credentials for testing purposes, but still doesn't work.
