### ISSUE TITLE
Consistent _source ordering

### ISSUE THREAD

**Issue by nik9000** [elastic/beats#27371]
**Describe the enhancement:**
A while back I was experimenting with the size of an Elasticsearch index. I grabbed a dump of some data indexed by beats 7.6.2 and noticed that I could save a couple of percentage points on the disk space when the `_source` is sorted. In other words. My test data was one doc per line and I made it into bulk files like this:

```
zstdcat data.json.zst | \
  jq -c . | \
  sed -e 's/^/{"index":{}}\n/' | \
  split --lines 10000 --suffix-length 6 --additional-suffix .json - $TMP/data.
```

When I sorted the data like:

```
zstdcat data.json.zst | \
  jq -Sc . | \
  sed -e 's/^/{"index":{}}\n/' | \
  split --lines 10000 --suffix-length 6 --additional-suffix .json - $TMP/data.
```

Note the `jq -S` to get the sorting. I'm not interested in the results being sorted. I mean, that might be nice, but as long as everything spits out a consistent order I don't think it matters. Sorting is just an easy way to get that.

Anyway, that got me a couple percentage points space savings. 9% when I using best compression, but I was on a weird development branch that is likely to make that % higher than normal. So I wouldn't expect 9% everywhere.

**Describe a specific use case for the enhancement or feature:**
Everything?

**Comment by ruflin** [comment]
This is interesting, @jpountz we should feed this into the compression comparisons too. @nik9000 Thanks for sharing!

**Comment by nik9000** [comment]
I think maybe synthetic source is more important than this. Maybe just
close it.
