### ISSUE TITLE
MySQL password from connection String gets indexed in metricset.host field and is visible

### ISSUE THREAD

**Issue by kerk1v** [elastic/beats#2738]
Hello, 

I've been testing Metricbeats on a smallish MySQL database I run. It is a great utility that provides good insight in queries, traffic and many other fine things happening in MySQL. 

However, I have noticed that the field metricset.host field includes the full connection string of the MySQL database, including the password. OK, I am running metricbeat against my MySQL with a users with as low privileges it needs in order to work, but in some enviroments even that may be considered unacceptable, particularly if Shield or other tools are not being used. 

Any advice?

Thanks in advance

**Comment by ruflin** [comment]
In the mysql module you have the option to pass username and password as a separate string and not part of the DSN directly. If you do that, it should not show up in the host. Can you try that out?

I realised the docs are missing for this but you can find an example here: https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.full.yml#L123

**Comment by kerk1v** [comment]
Perfect. Again, the source is the documentation :+1:

**Comment by ruflin** [comment]
@kerk1v I opened a PR here to have it also in the docs: https://github.com/elastic/beats/pull/2751
