### ISSUE TITLE
[Fleet]: event.datasets field is blank with logs under Logs tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#27404]
**Kibana version:** 7.15.0 Snapshot Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
Build: 43322
Commit: f448fcd00b319a3be0d1a1ae356956446e4d7ef8
Artifact Link: https://snapshots.elastic.co/7.15.0-af472020/downloads/beats/elastic-agent/elastic-agent-7.15.0-SNAPSHOT-linux-x86_64.tar.gz
```

**Preconditions:**
1. 7.15.0 Snapshot Kibana cloud environment should be available.
2. An agent must be installed with Default policy having System integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Agents>Logs tab.
3. Observe blank event.datasets with logs in the Logs field.

**Expected Result:**
event.datasets field should not be black with logs under Logs tab. The dataset selected from Datasets dropdown should be visible under event.datasets field.

**Note:**
- Datasets filter showing correct data as per selected filter under Logs tab, however just not event.datasets field is blank.

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/129154996-916d7d80-5692-4f96-8e61-02e92e91a441.JPG)

**Comment by EricDavisX** [comment]
if this is coming from a 7.14 Agent, I'd ask for further review to see how impactful this may be.  we might fix it more urgently if it is impactful.

**Comment by michel-laterman** [comment]
I'll take a look, the issue is present on 7.14.0
<img width="1215" alt="Screen Shot 2021-08-16 at 12 09 05 PM" src="https://user-images.githubusercontent.com/82832767/129617216-e0a7bf37-a162-4927-a0f0-23c46e3c0f16.png">

looking into the actual log entries, `event.dataset` appears as two keys in the document.
```
    "event": {
      "dataset": "elastic_agent.metricbeat"
    },
```
Once with the expected value
```
    "event.dataset": [
      "elastic_agent.metricbeat",
      "metricbeat-json.log"
    ]
```
and at the end with an array

**Comment by andrewkroh** [comment]
Does anyone know where the `event.dataset` value of `{beatname}-json.log` originates? The `_source` looks like this

```
"_source": {
    ...
    "event": {
      "agent_id_status": "verified",
      "ingested": "2021-08-16T19:19:01Z",
      "dataset": "elastic_agent.filebeat"
    },
    "event.dataset": "filebeat-json.log"
}
```

Agent adds `[event][dataset]` in the Filebeat config that's generated to collect logs. Those logs are parsed as JSON, so I wonder if the original log contained `event.dataset: {beatname}-json.log`?

https://github.com/elastic/beats/blob/084ba4eb0a01dda363a25a90648bf342baa7fee9/x-pack/elastic-agent/pkg/agent/operation/monitoring.go#L322-L329.

**Comment by jen-huang** [comment]
@michel-laterman Interesting that your UI screenshot actually displays values in the `event.dataset` column when it is an array (mine off of master shows blank). What version of Kibana are you running?

**Comment by michel-laterman** [comment]
`7.14.0` using elastic-package

**Comment by michel-laterman** [comment]
@andrewkroh, It looks like the filename event.dataset entries are being written directly into the logs. For example `filebeat-json.log` contains:
```js
{
  "log.level":"info",
  "@timestamp":"2021-08-16T20:02:19.901Z",
  "log.logger":"api",
  "log.origin": {
    "file.name":"api/server.go",
    "file.line":62
  },
  "message":"Starting stats endpoint",
  "service.name":"filebeat",
  "event.dataset":"filebeat-json.log",
  "ecs.version":"1.6.0"
}
```
this only occurs with the log entries (no dataset arrays for metrics)

**Comment by michel-laterman** [comment]
the filename dataset entries are added as part of the ECS annotations:
https://github.com/elastic/beats/blob/afde058fb35f32220b7db96c1972567d5cce5a14/libbeat/logp/core.go#L199-L205

**Comment by jen-huang** [comment]
@hop-dev Can you take a look on the Fleet side to see why the `LogStream` UI component might be showing different behavior on 7.15/master (empty column) vs 7.14 (column correctly shows array values)?

**Comment by ruflin** [comment]
Adding the LogFileName as `event.dataset` sounds like a bug and is not ECS conform. It was added here: https://github.com/elastic/beats/pull/25998 @axw Do you remember by chance what it was added to event.dataset? @michel-laterman We should remove this I think.

**Comment by ruflin** [comment]
@felixbarny I see you suggested `apm-server.log` as `event.dataset` in https://github.com/elastic/beats/issues/25997? This sounds off.

**Comment by felixbarny** [comment]
@ruflin is that because the `data_stream.dataset` and `event.dataset` fields are already set by Elastic agent's Filebeat config? Or is there a more fundamental reason why `event.dataset="${service.name}.log"` is not a good idea?

The idea was that each Beat/shipper defines its dataset and that the Filebeat config to ship the log files looks the same for every shipper, without needing to define the dataset. However, that requires event routing so that all logs can be sent to the same routing pipeline that routes the events based on the `data_stream.dataset` that's set in the logs.
Right now, it's probably premature to populate the dataset in the ECS logger config as it conflicts with the one set in the Filebeat config.

**Comment by ruflin** [comment]
In general I like the idea that the `dataset` is already set in the log file. I think we have 2 problems here:

* Having `.log` in the dataset name is a bit unfortunate. That it is a log should be defined by the `type` already. Lets remove it.
* Filebeat can be run in standalone and with Elastic Agent. Depending on how it is run, logs should be shipped to a different place. When run by Elastic Agent the `dataset` value is `elastic_agent.filebeat`. For APM it is `elastic_agent.apm_server`. Where should these logs go in standalone? `logs-apm_server-*`?

Most important, there can only be a single dataset value in the logs or in the end event. I think the short term fix is that we get rid of the `.log` in the code and make sure elastic agent overwrites and not appends the dataset.

**Comment by felixbarny** [comment]
> Having .log in the dataset name is a bit unfortunate. That it is a log should be defined by the type already. Lets remove it.

This seemed to be a best practice looking at datasets like `haproxy.log`, `kibana.log`, etc. Is that a practice you are moving away from? If so, we should also update the [ECS logging spec](https://github.com/elastic/ecs-logging/blob/a617a4431fefbd10775429de7af4748e482fc9f4/spec/spec.json#L96).

> Depending on how it is run, logs should be shipped to a different place.

Why not have the same datastream regardless of how it's run?

> Most important, there can only be a single dataset value in the logs or in the end event.
++

**Comment by ruflin** [comment]
I must confess I'm a but surprised by the "best practice" in ECS Logging. Why would we include `.log` if it is already defined by the `type`?

> Why not have the same datastream regardless of how it's run?

I don't think I have good pure technical argument on this one. The way I think of it is: If you run just filebeat, this is the service you run and is monitored. As soon as you run Elastic Agent, it will run some processes which is an implementation detail for the user. How it writes logs is also an implementation detail. All the logs can be consumed under `elastic_agent.*`. If tomorrow filebeat becomes `foobeat` it should not change the basics around logging. I would go so far to say it is not ideal that each process has its own log file. That is why I should ship it to two different dataset.

**Comment by felixbarny** [comment]
> I must confess I'm a but surprised by the "best practice" in ECS Logging. Why would we include .log if it is already defined by the type?

Looking at examples (maybe from Beats modules, not sure), I thought that this was an established best practice, so I added it to the ECS logging spec as a default value. I don't feel strongly about the `.log` suffix at all and am happy to revise the spec. What would a better default be? Just the service name?

**Comment by hop-dev** [comment]
I believe the root cause of the field not being shown in the table is that `event.dataset` is missing from the mapping, this is being tracked in https://github.com/elastic/beats/issues/27405

**Comment by felixbarny** [comment]
> Looking at examples (maybe from Beats modules, not sure), I thought that this was an established best practice

@ruflin See also the example in the [logs app docs](https://www.elastic.co/guide/en/observability/current/tail-logs.html)

<img width="754" alt="Screen Shot 2021-08-19 at 08 07 11" src="https://user-images.githubusercontent.com/2163464/130016661-ff098107-a95c-4371-ba67-b0a13c02364e.png">

Do you have a suggestion for a better default?

**Comment by ruflin** [comment]
I wonder where these values come from. In modules / packages we don't use `.log` and also don't use `camelCase`. The value of `event.dataset` consists normally of `{service}.{more-details}` so in the case of nginx it is `nginx.access`, `nginx.error`. If there is only a single log file for a service I would go just for `{service}`. We should also expand a bit on the dataset description of ECS: https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-dataset

In case of filebeat I assume the json logs and non json logs contain exactly the same content. So in the ideal scenario there is an ingest pipeline that converts both into the same format so we could just use `filebeat` as the dataset.
