### ISSUE TITLE
[Winlogbeat] Sysmon Registry Value bug

### ISSUE THREAD

**Issue by willemdh** [elastic/beats#27408]
- Version: 7.13.1
- Operating System: Red Hat 8 / All Windows Versions
- Discuss Forum URL: 
  - https://discuss.elastic.co/t/winlogbeat-sysmon-configuration-registry-fields-seems-to-map-the-wrong-value-of-the-registry/281521
  - https://discuss.elastic.co/t/winlogbeat-sysmon-configuration-registry-fields-seems-to-map-the-wrong-value-of-the-registry/273733
  - https://discuss.elastic.co/t/winlogbeat-sysmon-configuration-registry-fields-seems-to-map-the-wrong-value-of-the-registry/277879
- Steps to Reproduce: Enable Sysmon registry events and index them with Winlogbeat Sysmon module

https://github.com/elastic/beats/blob/ee5ed90dec9e1c8091f7cddf88ba50198668714b/x-pack/winlogbeat/module/sysmon/test/testdata/sysmon-11-registry.evtx.golden.json#L39-L46

**Comment by efd6** [comment]
I believe this is working as intended; the `registry.value` field is the [name of the registry entry](https://www.elastic.co/guide/en/ecs/current/ecs-registry.html#field-registry-value). The actual value that is stored is in [`registry.data.strings`](https://www.elastic.co/guide/en/ecs/current/ecs-registry.html#field-registry-data-strings), with the type in [`registry.data.type`](https://www.elastic.co/guide/en/ecs/current/ecs-registry.html#field-registry-data-type).

Zooming out from the snippet above we can see the expected "4".

https://github.com/elastic/beats/blob/ee5ed90dec9e1c8091f7cddf88ba50198668714b/x-pack/winlogbeat/module/sysmon/test/testdata/sysmon-11-registry.evtx.golden.json#L29-L49

**Comment by willemdh** [comment]
@efd6 

?? I don't have registry.data.strings set in my sysmon registry data:

![image](https://user-images.githubusercontent.com/6462991/144979767-8ac0d6ff-395e-4dca-afc6-b2a34a701ee1.png)

Tested multiple examples..

**Comment by efd6** [comment]
6th and 7th field? "2" and "SZ_DWORD"

**Comment by willemdh** [comment]
Omg, sorry.... Completely missed that. Closing....
