### ISSUE TITLE
Per-process thread count metrics

### ISSUE THREAD

**Issue by matschaffer** [elastic/beats#27415]
**Describe the enhancement:** Linux tracks thread counts per pid, for example:

```
grep Threads /proc/$(pgrep -n metricbeat)/status
Threads:	39
```

It'd be useful to have that data collected along side the rest of the system module statistics. Thread count and CPU performance are often related.

**Describe a specific use case for the enhancement or feature:**

We were tracking metricbeat threads for profiling of stack monitoring data collection via metricbeat. For the time being I just used SSH to get the information, but I was hoping it was already indexed.

Doesn't look like it is today.

**Comment by jlind23** [comment]
Removing it for the current iteration for now. cc @cmacknz
