### ISSUE TITLE
Import beats dashboard fails with unsupported media type

### ISSUE THREAD

**Issue by liza-mae** [elastic/beats#27418]
For confirmed bugs, please report:
- Version: 8.0
- Operating System:  Ubuntu
- Steps to Reproduce: 
Run ```./filebeat setup```

```
Exiting: 1 error: error loading index pattern: returned 415 to import file: Unsupported Media Type: <nil>. Response: {"statusCode":415,"error":"Unsupported Media Type","message":"Unsupported Media Type"}
```

Is it possibly related to recent change: https://github.com/elastic/beats/pull/27220, as part of https://github.com/elastic/kibana/issues/41439?

**Comment by ruflin** [comment]
@kvch Any idea here? I wonder if it is related to your recent change or maybe one of the saved object types is not supported anymore?

**Comment by ruflin** [comment]
Related issue? https://github.com/elastic/beats/issues/27417

**Comment by kvch** [comment]
PR to fix it: https://github.com/elastic/beats/pull/27424
