### ISSUE TITLE
7.14 Fleet server communication issues: Failed agent enrollment

### ISSUE THREAD

**Issue by nimarezainia** [elastic/beats#27441]
Elastic Agent 7.14 on-prim Elastic cluster. Effected OS Windows Server 2016/2019 both OS's have the same issue.
Error pulled from a failed enrollment attempt of the client directly.
Fleet agent in prod is running on CentOS Stream. Test Fleet server was Ubuntu.

Steps used:

    Remove 7.13.4
    Install windows updates.
    Reboot server.
    Delete the existing Agent folder from C:\Pro~\Elastic\Agent
    Enroll agent from the 7.14 download.
    Start chanting no whammies, no whammies, no whammies.
    If whammy occurs go to Fleet unenroll failed agent. If you attempt to re-run the enrollment again you will have duplicate agents and it will be stuck in updating state forever.
    Restart fleet server agent. Reenroll.

//
2021-08-16T11:46:18.366-0700 ERROR cmd/watch.go:61 failed to load markeropen C:\Program Files\Elastic\Agent\data.update-marker: The system cannot find the file specified.
2021-08-16T11:46:18.591-0700 INFO [composable.providers.docker] docker/docker.go:43 Docker provider skipped, unable to connect: protocol not available
2021-08-16T11:46:18.593-0700 INFO [api] api/server.go:62 Starting stats endpoint
2021-08-16T11:46:18.594-0700 INFO application/managed_mode.go:291 Agent is starting
2021-08-16T11:46:18.594-0700 INFO [api] api/server.go:64 Metrics endpoint listening on: \.\pipe\elastic-agent (configured: npipe:///elastic-agent)
2021-08-16T11:46:18.694-0700 WARN application/managed_mode.go:304 failed to ack update open C:\Program Files\Elastic\Agent\data.update-marker: The system cannot find the file specified.
2021-08-16T11:46:19.069-0700 WARN [tls] tlscommon/tls_config.go:98 SSL/TLS verifications disabled.
2021-08-16T11:46:19.330-0700 ERROR fleet/fleet_gateway.go:205 Could not communicate with fleet-server Checking API will retry, error: status code: 400, fleet-server returned an error: BadRequest
//

This happens when the elastic fleet agent hits 600+ MB of memory usage. Restarting the service and you are good to go and the error will not show again until the fleet agent is 600+ MB usage.

After the fleet agent restarts in Kibana GUI:
circuit_breaking_exception: [circuit_breaking_exception] Reason: [in_flight_requests] Data too large, data for [<http_request>] would be [8875977956/8.2gb], which is larger than the limit of [8589934592/8gb]

This has also causing another issue I posted about. Excessive network sessions. Was finally able to track that down to the same issue above. When the fleet agent stall's out you will have clients or the fleet agent starting to sending thousands of open network sessions. Average per agents is 17,000 which turns out to be 1GB traffic per agent. I mean it's fun seeing if your network is build to handle massive session limit's but not good for production as you can saturate uplinks.

For confirmed bugs, please report:
- Version: 7.14.0
- Operating System:  Windows Server 2016/2019
- Discuss Forum URL:   https://discuss.elastic.co/t/elastic-agent-7-14-strange-bug-during-enrollment-elastic-fleet-agent-bug/281594
- 
- Steps to Reproduce: see above

**Comment by EricDavisX** [comment]
Hi, we've tested on all of the supported OSes, and with the details we have so far I'm not seeing the same problems.

So, I wanted to ask for some clarification, if I could - I know there was good discussion outside of this ticket, so thank you in advance and I hope nothing is a repeat, but apologies if it is!  Is there any way we can clarify on what was being tested too... on-prem vs 'prod' vs test agent.  I don't understand, I may be missing context or not making intended assumptions.

Also, I don't know what certs/ CA usage is in play here and it is easy to have mistakes / problems between Windows + non-Windows in that regard.  It would be helpful to confirm the basics, and start at the beginning - I'd like to see the (redacted) strings used on the command line to install Fleet Server as well as the command used in powershell or command-prompt in Windows to deploy that Agents.  

And I don't mean to be difficult, but I do want to call out the Troubleshooting and FAQ questions in our formal Docs.  If we are stuck on assessing a given point, I'd personally love to know where and what we can add in to make it better.  Here is the troubleshooting doc: https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html

I'm not sure the user is tracking this issue yet, so I will post this, and also post it to the forum in case it helps.

**Comment by EricDavisX** [comment]
@nimarezainia confirmed it is on his list to follow up.

**Comment by EricDavisX** [comment]
This was discussed and closed in the last team meeting, the manual test group is being tasked with one final barrage of tests to validate where the current product is to see if we can expect any of the relating bugs to show in subsequent releases.  If anything comes we will report back here.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We attempted to reproduce above scenario and found it working fine. Below are the steps followed:

1 Installed 7.14.2 version snapshot agent using policy say 'Test1' having only system integration on 7.15 snapshot Kibana cloud.
2 Installed a separate Fleet Server Agent host under Policy say 'Fleet server' having only Fleet server integration.
3 Deleted the cloud FS url from Fleet settings.
4 Added Endpoint security to agent policy 'test1', and updated Agent logging level to 'debug'
5 Leave the environment for a day to let data come in. Also do lots of 'actions' on host. 
6 On next day, Unenroll 7.14.2 Agent from Kibana UI.
7 Installed windows updates.
8 Reboot Agent host machine.
9 Deleted the existing Agent folder from C:\Pro~\Elastic\Agent
10 Download the latest 7.15 snapshot artifacts.
11 Upgrade Fleet server agent to 7.15 version from kibana UI.
12 Attempt to enroll 7.15 agent.
13 Observe, enrollment was done successfully.

Build details:
```
Kibana version:  7.15 snapshot Kibana cloud-staging environment
BUILD 44071
COMMIT 103671892c9171860567f8e848ada359f9e8f62a
Artifact : https://snapshots.elastic.co/7.15.0-0aca9817/downloads/beats/elastic-agent/elastic-agent-7.15.0-SNAPSHOT-windows-x86_64.zip
https://snapshots.elastic.co/7.14.2-dd01e432/downloads/beats/elastic-agent/elastic-agent-7.14.2-SNAPSHOT-windows-x86_64.zip

```

Screenshots:
Before upgrade:
![image](https://user-images.githubusercontent.com/72375798/135271933-8ca475b9-fa62-4b15-bdf2-dd31abcbc981.png)

After upgrade:
![image](https://user-images.githubusercontent.com/72375798/135271737-3d2bc91b-70db-4b4f-9f03-e055351b2ca9.png)

![image](https://user-images.githubusercontent.com/72375798/135271782-c5b816b8-4238-451b-b168-ed0bf08fb4c8.png)

Please let us know if anything else is required.

Thanks
QAS
