### ISSUE TITLE
Document incompatibility of topbeat data with new Metricbeat dashboard

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#2745]
When we switch from topbeat to metricsbeat in 5.0, the previous recorded topbeat data will no longer be compatible with the 5.0 dashboard due to the changes in the underlying data structures.  It will be helpful to set some expectations as part of the upgrade section below.

https://www.elastic.co/guide/en/beats/libbeat/5.0/_upgrading_from_1_x_to_5_x.html#_upgrading_topbeat_to_metricbeat

**Comment by tsg** [comment]
Agreed, will do.

**Comment by dedemorton** [comment]
Closed with #2822
