### ISSUE TITLE
Update metricbeat used in CI to test the beat module

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#27495]
https://github.com/elastic/beats/pull/27416 tried to update the versions of the stack used for CI in master branch to 7.14, but there was an error related to the beat module, so it was not updated them. Opening this issue to don't lose track of this.

The failure observed was this one:
```
E               Exception: Key 'beat.stats.info.version' found in event is not documented!
``` 

This may be a signal of some problem in the beat module.

Update metricbeat used in CI for the beat module to the latest released version, in master and 7.x branches.

**Comment by endorama** [comment]
I found that [`beat` module `fields.yml` contains `beat.stats.beat.version`](https://github.com/elastic/beats/blob/master/metricbeat/module/beat/_meta/fields.yml#L320) which feels very similar to `beat.stats.info.version`.

**Comment by jsoriano** [comment]
> I've not been able to backtrace why this discrepancy exists.

#24427 may be related. It wasn't backported, this could explain why 7.14 testing environments can be used in 7.14 and 7.15 branches but not in master.

cc @sayden
