### ISSUE TITLE
[Elastic Agent] [7.13.x] Install command on Windows-2019 hangs out for ever

### ISSUE THREAD

**Issue by mdelapenya** [elastic/beats#27501]
We are seeing a consistent failure in our e2e test suite that, for 7.13.x branch, the `install` command on Windows-2019 is not able to continue, waiting indefinitely until running out the default timeout.

CI build: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.13.x/161/pipeline/497
Logs:
>[2021-08-19T11:28:00.512Z] time="2021-08-19T11:28:00Z" level=trace msg="Executing command" args="[install -e -v --force --insecure --enrollment-token=OWJ3cVhuc0JQSXh5NUNKVHplYXk6N0dBVnpVTnpUd3VBd0FzTWozc3dUdw== --url http://10.224.0.131:8220]" command="C:\\elastic-agent\\elastic-agent.exe"

We are in the process of extracting the fleet-server logs once https://github.com/elastic/e2e-testing/pull/1480 is merged and backported to 7.13.x

**Comment by mdelapenya** [comment]
Did not mention it, but our test scenarios and code are the very same for 7.13, 7.14, 7.x and master, and the test only fail for that combination: windows-2019 on 7.13

**Comment by EricDavisX** [comment]
This is a new scenario, have we ever seen it pass on 7.13 for windows (specifically)?  

I might suggest the 7.13 line is stable and may not get many / any more backports now that we are branching for 7.16 and we can safely ignore this as the product is confirmed working on 7.13.x line on Win 2019.

So, I'd suggest we update the e2e-testing with this work: https://github.com/elastic/e2e-testing/issues/1484 to create new branch and close out 7.13 and skip it unless it fails on the newer line.  it isn't worth chasing down, as I see it.  @mdelapenya thank you for putting the ticket in and citing it. let me know what you think

**Comment by mdelapenya** [comment]
Will close once we create 7.16.

Thanks @EricDavisX for your invaluable support!

**Comment by EricDavisX** [comment]
I think we can close now... the 7.16 branch is imminent and 7.14.x and 7.15.x or 8.0 didn't show it
