### ISSUE TITLE
console output doesn't work on windows

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#2756]
Using the console output fails on Windows.
- Version: 1.3.1 (didn't test 5.x but it's probably affected)
- Operating System: Windows 2012 (`vagrant up win2012`)
- Steps to Reproduce: Enable console output and start a the beat on the command line (foreground).

```
2016/10/12 03:49:27.119948 outputs.go:120: ERR failed to initialize console plugin as output: console output initialization failed with: GetFileInformationByHandle /dev/stdout: Incorrect function. Error Initialising publisher: console output initialization failed with: GetFileInformationByHandle /dev/stdout: Incorrect function.
2016/10/12 03:49:27.120904 beat.go:161: CRIT console output initialization failld with: GetFileInformationByHandle /dev/stdout: Incorrect function.
```

**Comment by maddin2016** [comment]
Hi @andrewkroh, i'm currently steped through this issue. If i debug with VSCode, output works as expected. 
![image](https://cloud.githubusercontent.com/assets/19551763/19808094/5c6cf1ba-9d23-11e6-946c-b556b88ad33f.png)

Is it ok if i investigate further? Or is this fixed?

**Comment by andrewkroh** [comment]
Yes, please investigate/fix.

I believe the issue is that it doesn't like our use of `Stat()` on the `/dev/stdout` handle at https://github.com/elastic/beats/blob/master/libbeat/outputs/console/console.go#L30-L33

The docs for [`GetFileInformationByHandle`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364952%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) state that "This handle should not be a pipe handle."
