### ISSUE TITLE
Possible memory leak in rate_limit processor

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#27639]
There seems to be a small memory leak in the `rate_limit` processor. At least metrics created by this processor are never removed.

This is not a problem with the usual use case where `rate_limit` is used as a global processor in the main configuration file, but it can be a problem if used with dynamically created inputs, as can happen with kubernetes autodiscover.

Apart of the possible memory leak caused by this, it can also cause inconveniences every time metrics need to be logged or collected.

I would suggest to implement `Close()` in this processor to remove this metric when an specific instance is removed. It may be also good to profile filebeat when inputs with the `rate_limit` are removed, in case there are other leaks.

For confirmed bugs, please report:
- Version: Confirmed in 7.13, possibly all versions affected since 7.11.
- Steps to Reproduce:
  * Use filebeat with hints-based autodiscover (it can be possibly reproduced with autodiscover templates too).
  * Define a `rate_limit` processor in a hint (i.e. `co.elastic.logs/processors.rate_limit.limit: 200/m`)
  * Restart the pods using this configuration.
  * Check that eventually several `processor.rate_limit.<number>.dropped` metrics exist.

**Comment by StephanErb** [comment]
@jsoriano you write:

> This is not a problem with the usual use case where rate_limit is used as a global processor in the main configuration file, but it can be a problem if used with dynamically created inputs, as can happen with kubernetes autodiscover.

In reverse, is it correct to assume that using a global filter is safe, even with high cardinality fields? The limiter implementation https://github.com/elastic/beats/blob/db73681d67be859f5c048d07da985eadaa780e21/libbeat/processors/ratelimit/token_bucket.go looks as if it would properly clean up and not leak. Maybe you can help me confirm.

Example config I am considering:

    processors:
    - rate_limit:
       fields:
       - "kubernetes.container.id"
       limit: "20000/h"

**Comment by jsoriano** [comment]
@StephanErb regarding to the issue reported here, using a global filter as the one you mention should be safe. Regarding high cardinality, it should be safe enough too, but better try with the cardinality you have.
