### ISSUE TITLE
es index segmentation question(through filebeat)

### ISSUE THREAD

**Issue by ShenBanma** [elastic/beats#27678]
Hey, I have a question. I stay at UTC+8, and I use filebeat to collect logs from k8s, then sending to es.But the default index segmentation is decided by UTC, not UTC+8. So I will find logs of 2021.9.1(UTC+8) in filebeat-2021.08.31 16:00 to filebeat-2021.09.01 15:59(show in figure 1). I expect to find my logs in  filebeat-2021.09.01 00:00 to filebeat-2021.09.01 23:59. I want to know how to configure filebeat to achieve it.
figure 1:
![image](https://user-images.githubusercontent.com/13790821/131609595-f0746dd1-00ba-4ded-abc4-c20e7b46334e.png)
Nevertheless, I find the code from souce:
![image](https://user-images.githubusercontent.com/13790821/131609753-c20912de-0ebc-479b-a5e6-cfe6e6e3c4e0.png)
is right?

**Comment by kaiyan-sheng** [comment]
Hello, thanks for creating this. But we would kindly ask you to post all questions and issues on https://discuss.elastic.co/c/beats before opening a Github Issue. Your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue or open a new one with more details. Thanks in advance!

For your question, I don't think there is a processor for doing that but maybe you can try manipulating it with ingest node.
