### ISSUE TITLE
[Security Solution]Error is coming on setting up the file beat on window 64 bit

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/beats#27756]
**Describe the bug**
Error is coming on setting up the file beat on window 64 bit

**Build Details:**
```
Version:7.15.0 BC4
Commit:29a6969dc230abf16dc65a41c535cb534ae64fa7
Build:43886
```

**Browser Details:**
N/A

**Preconditions**
1. Deployed 7.15.0 on cloud production build.

**Steps to Reproduce**
1. RDP to the windows 64 bit vm.
2. Download and extract the filebeat-7.15.0-windows-x86_64.zip.
3. Run power shell in admin mode.
4. Run .\filebeat modules enable threatintel 
4. Run .\install-service-filebeat.ps1
5. Run .\filebeat setup
6. Observed that below error is coming:

```
Overwriting ILM policy is disabled. Set setup.ilm.overwrite: true for enabling.

Index setup finished.
Loading dashboards (Kibana must be running and reachable)
Exiting: Failed to import dashboard: Failed to load directory C:\Program Files\filebeat-7.15.0-windows-x86_64\kibana/7:
error loading C:\Program Files\filebeat-7.15.0-windows-x86_64\kibana\7\dashboard\Filebeat-threatintel-recordedfuture.json: error dashboard asset: returned 0 to import file: fail to execute the HTTP POST request: Post "https://27bf49cb9fac4fe989754909e72c675e.europe-west1.gcp.cloud.es.io:443/api/saved_objects/_import?overwrite=true": context deadline exceeded (Client.Timeout exceeded while awaiting headers). Response:
error loading C:\Program Files\filebeat-7.15.0-windows-x86_64\kibana\7\dashboard\filebeat-network-flows-top-n.json: error dashboard asset: returned 0 to import file: fail to execute the HTTP POST request: Post "https://27bf49cb9fac4fe989754909e72c675e.europe-west1.gcp.cloud.es.io:443/api/saved_objects/_import?overwrite=true": context deadline exceeded (Client.Timeout exceeded while awaiting headers). Response:
```

**Actual Result**
Error is coming on setting up the file beat on window 64 bit

**Expected Result**
file beat should be installed correctly on the windows 64 bit 

**What's Working**
- N/A

**What's Not Working**
- N/A

**Screen-Shot**
![image](https://user-images.githubusercontent.com/61860752/132174008-edced099-2b7d-44f0-a3c7-5fcd0eade459.png)

**Comment by deepikakeshav-qasource** [comment]
@manishgupta-qasource Please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @MadameSheema

**Comment by ChrsMark** [comment]
Maybe related to https://github.com/elastic/beats/issues/27586

**Comment by deepikakeshav-qasource** [comment]
Hi,

We have validated this ticket on **7.15.0 BC5** build and observed that issue is **Fixed**. Filebeat is installed successfully on the windows 64 bit

**Build Details:**
```
Version:7.15.0 BC5
Commit:0239ff6864dd9930cfe9bcd9a679272f2b7465c2
Build:43957
```

**Screenshot:**

![image](https://user-images.githubusercontent.com/61860752/133029907-9a5fb878-40a9-4161-a13d-4f9e072d9024.png)


Hence, We are closing this ticket and marking as QA Validated

Thanks!!
