### ISSUE TITLE
[Agent]: Upgraded 7.14.1>7.15.0 Snapshot Agent is not completely uninstalled on running uninstall command

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#27769]
**Kibana version:**  7.15.0 Snapshot Kibana Cloud environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
Build: 43944
Commit: 951240e085cc4465167ab4d6bcdf6f267446a874
Artifact Link: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.14.1-windows-x86_64.zip
```

**Preconditions:**
1. 7.15.0 Snapshot Kibana Cloud environment should be available.
2. 7.14.1 released agent must be installed with Default policy having System integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Upgrade 7.14.1 agent from Fleet UI.
3. After agent is successfully upgraded.
4. Run uninstall command from CLI at location `C:\Program Files\Elastic\Agent`:
`.\elastic-agent.exe uninstall -f`
5. Observe many subfolders are still available at Elastic\Agent location.

**Expected Result:**
Upgraded 7.14.1>7.15.0 Snapshot Agent should be completely uninstalled on running uninstall command.

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/132317515-ded30036-d12f-4904-95c6-f22e4ecb801d.JPG)

**Note:**
- This issue is not reproducible at 7.14.1 Kibana cloud environment.
- This issue is not reproducible for 7.15.0 Agent.
- This issue is **specific to agent upgrade**.

Similar issue of incomplete uninstallation was reported on 8.0-alpha1 here https://github.com/elastic/beats/issues/27255. It was observed just after installation and no upgrading agent was involved.

**Comment by blakerouse** [comment]
You should not run the uninstall command from inside of the `C:\Program Files\Elastic\Agent` directory. Windows will not allow a directory to be removed that is being used, so it will prevent that directory from being removed.

@michalpristas Do you think maybe the watcher subcommand is still running? That might be why those files could not be removed. Thoughts?

**Comment by EricDavisX** [comment]
The watcher does hang around for (I think) 10 minutes?  That is long enough that it could certainly unsuspectingly be impacting testing (we'll need to make a note to wait MORE than 10 minutes after upgrading to do this particular assessment of un-installing)

Separate from the testing side, it is evident... and so We could tackle this from 2 angles:
1) confirm what is happening and then what we could do here (should we support it better, maybe including preventing it as the solution?) 

2) and then figure out if it is worthwhile for the effort versus a Docs fix.  

It may be helpful but we should evaluate risk and impact in a given fix, too.

**Comment by amolnater-qasource** [comment]
Hi @blakerouse 
>You should not run the uninstall command from inside of the C:\Program Files\Elastic\Agent directory. 

Usually, we run uninstall command from this location only and it gets successfully uninstalled everytime. Even on the docs available at- [Uninstall Elastic Agent](https://www.elastic.co/guide/en/fleet/master/uninstall-elastic-agent.html#uninstall-elastic-agent) same information is available.

>(we'll need to make a note to wait MORE than 10 minutes after upgrading to do this particular assessment of un-installing)

Yes @EricDavisX we attempted to uninstall after 10 minutes of upgrade and we observed Agent completely uninstalled. No other folders are available inside Elastic\Agent.

Please let us know if anything else is required from our end.
Thanks
QAS

**Comment by blakerouse** [comment]
Seems that waiting the 10 minutes solved the issue. I think this is acceptable behavior.

**Comment by EricDavisX** [comment]
This is painful on the process side / testing side, but I do think it is ok enough behavior for now - it is unlikely to be seen by production customers (upgrades usually happen when someone wants to keep the Agent around).  Thanks Blake + Amol.

**Comment by dikshachauhan-qasource** [comment]
### Bug conversion

Hi @EricDavisX 

We have created 01 testcase for above reported issue under bug conversion task. Testcase link is:

- [C150167](https://elastic.testrail.io/index.php?/cases/view/150167)

Thanks
QAS
