### ISSUE TITLE
[Discuss] Adding ingest stats to metricbeat ES module, and discussion around handling those metrics

### ISSUE THREAD

**Issue by P1llus** [elastic/beats#27768]
Currently the metricbeat Elasticsearch module (and `node_stats` fileset) is collecting all the available data from the `_node/stats` api.

However there is a schema that handpicks which fields will be in the resulting document sent to ES, example here:
https://github.com/elastic/beats/blob/master/metricbeat/module/elasticsearch/node_stats/data.go#L37

While adding the ingest stats to the schema is straight forward, it opens up a separate question, specifically how we are currently handling counters that are reset on node restart.
The _node/stats API seems to have 2 different types of stats, a `counter` and a `gauge`.

The first of those two are reset upon restart of a ES service or node, and I do wonder how this impacts the resulting data stored in ES (and later used in dashboarding and stack monitoring alerts).
We are already storing other stats like indices, which also resets upon restart, so I don't believe this is an issue, but I want to make sure this is actually the intended behavior, and how we counter this when visualizing the data?

@ruflin Would you be able to help me confirm that gathering data that resets is still okay, and that adding this to the above schema will be okay?
The fields are documented under `ingest` here:
https://www.elastic.co/guide/en/elasticsearch/reference/7.14//cluster-nodes-stats.html#cluster-nodes-stats-api-response-body

If this is okay I will go ahead an open a PR to update the schema.

**Comment by ruflin** [comment]
For the counters, it is likely a question what we do with it. In case we should a derivate I would assume the reset should not be a problem. But if we do something with the total value it could be a problem. We likely have to look at it case by case.

For adding ingest nodes field I ping @masci @exekias @jasonrhodes @matschaffer as they know better where we should be heading here.

**Comment by P1llus** [comment]
Il add a ping to @cjcenizal as well, as it is relevant to our last discussion.

**Comment by matschaffer** [comment]
A number of stack monitoring metrics are counter derivatives today already https://github.com/elastic/kibana/blob/master/x-pack/plugins/monitoring/server/lib/metrics/elasticsearch/metrics.js#L253-L270

It'd be awesome to have proper support in ES to avoid reset blips, but today the UI can help paper over it to provide a decent user experience.

**Comment by P1llus** [comment]
After some discussion with @matschaffer, it seems that we are okay with using the current ingest stats in metricbeat, and that the workarounds for resetting numbers and even them out will happen on the visualization side.

I will go ahead and make a preliminary PR, to see if people agree.
