### ISSUE TITLE
Provide a way to control the role naming for functionbeat to avoid exceeding the 64 character role name limit for auto created roles

### ISSUE THREAD

**Issue by geekpete** [elastic/beats#27767]
For a function with a sufficiently long name, the auto created role name could exceed the allowed limit of 64 characters.

An example is a function with a name of  `function-with-a-very-long-name1` that tries to create a role name of  `functionbeat-lambda-function-with-a-very-long-name1-eyAiUmSmIjogIkFXUz96U5VnaW9uIiB9`

![role-name-too-long-error](https://user-images.githubusercontent.com/2070843/131588050-ab15812c-832a-4cac-a2b7-2f1f2a6ed7a1.png)

If the naming of the resulting role name to be created was more configurable than just `<function_name>-<long_hash_value>` then this might give users a better way to avoid the limit generally.

There's probably a lot of possible methods to provide user customization of the naming and probably other caveats or requirements too (such as avoiding collisions or auto retrying on collision perhaps).

The result of some function names being longer than others can be that it's less obvious which ones will fail without putting some restriction in the app to guarantee the function name length upstream of the role creation.

**Comment by pushred** [comment]
Also encountering this and it seems like a bug. The only function name I've had success with is something that is 11 characters in length. The "default" function name in the [reference config](https://github.com/elastic/beats/blob/b8cfea6ef601b10fb378b4e51cdde9f2ad84a3b1/x-pack/functionbeat/functionbeat.reference.yml#L34) — `cloudwatch` — happens to also be 11 characters in length.

In my situation this is insufficient to name the function effectively anything else. We wanted to deploy an instance of the function for each application and 11 characters is insufficient for identifying them in a way that is meaningful within our broader AWS account.

**Comment by geekpete** [comment]
I think this one is still relevant since users want to be able to potentially use informative names for their functions and hard coding a set format that always has specific kinds of prefixes eats up the ability to use custom naming of any decent length.

AWS Lambda function name limitations appear to be documented here:
https://docs.aws.amazon.com/lambda/latest/dg/API_CreateAlias.html

There's also the ability to set an alias on a function that might be useful as part of a solution perhaps, if used in a smart way:
https://docs.aws.amazon.com/lambda/latest/dg/configuration-aliases.html

The problem also doesn't seem to be an uncommon one:
https://github.com/serverless/serverless/issues/526
https://github.com/serverless/serverless/issues/7056
