### ISSUE TITLE
[Elastic Agent] Migrate runtime data of processes upon upgrade

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#27773]
at the moment we have state file located in `{data}/run/default/{process_name}--{process_version}`
on upgrade beat uses a new location as versions differ and old state is ignored which means beat can end up processing some data multiple times.

**Step 1** should be migrating all data from old versioned directory to newer one. this way we don't produce duplicates on upgrade.

**Open question** is what we should do on rollback. If newer beat/process did some work and we don't do anything, we will end up with duplicates anyways.
But if we do migrate it back to older version data directory we may risk breaking state. Newer beat/process may have different contract/format which is not understood by older one. 

cc @ruflin

**Comment by kvch** [comment]
> at the moment we have state file located in `{data}/run/default/{process_name}--{process_version}`
> on upgrade beat uses a new location as versions differ and old state is ignored which means beat can end up processing some data multiple times.
> 
> **Step 1** should be migrating all data from old versioned directory to newer one. this way we don't produce duplicates on upgrade.
> 
> **Open question** is what we should do on rollback. If newer beat/process did some work and we don't do anything, we will end up with duplicates anyways.
> But if we do migrate it back to older version data directory we may risk breaking state. Newer beat/process may have different contract/format which is not understood by older one.

The registry format is versioned. On rollback, we can check if the version is the same; if yes, we can use the updated state. If the version has changed, there is nothing we can do. Maybe some heuristics, but I would not go down that road because we might end up with something unexpected.
We should add similar versioning to other data files so we can try to stay consistent during rollback.

**Comment by blakerouse** [comment]
I think that on rollback it goes back to its previous state (not a modified version from the next version). We need rollback to be a last resort and in the case that it needs to be used, it needs to be full proof. In that case rollback should just go back to the previous state.

**Comment by EricDavisX** [comment]
Can we also get a clear 'how to reproduce this' set of steps, using a particulars UI option for Agent, please?  Not sure if this will be easy to put a set of unit / system tests in, it might be feasible to add to the e2e-testing upgrade scenarios if we wanted, but that is likely more time consuming.  could be worthwhile though.

**Comment by EricDavisX** [comment]
Referencing an existing e2e ticket for remaining work: https://github.com/elastic/e2e-testing/issues/534

**Comment by ruflin** [comment]
The way I would imagine this happens is:

* Upgrade triggered
* Shutdown current instance
* Copy state to new state directory
* Start new instance
* Migration starts but fails
* Rollback triggered
* New instance stopped
* Old instance started again with old state in old state directory

Basically what @blakerouse described above.

**Comment by ruflin** [comment]
@EricDavisX For the filebeat registry case I think an e2e would be great to make sure we do not break this very common use case.
