### ISSUE TITLE
Redis input for log data

### ISSUE THREAD

**Issue by honzakral** [elastic/beats#27817]
**Describe the enhancement:** I would love to see an input that would read data from a queue in redis for lightweight deployments (no kafka, no logstash).

**Describe a specific use case for the enhancement or feature:** I want to gather logs from multiple machines and I don't want to run a separate logstash instance or a kafka cluster when a simple redis server would suffice.

**Comment by jsoriano** [comment]
Hey @HonzaKral,

There is already a redis https://www.elastic.co/guide/en/beats/filebeat/7.14/filebeat-input-redis.html. Have you tried it?

**Comment by HonzaKral** [comment]
@jsoriano  That input is not what I am describing here, it is just for consuming the slow log *of* redis, not using redis as a queue to consume events:
> Use the redis input to read entries from Redis slowlogs.

**Comment by jsoriano** [comment]
> @jsoriano That input is not what I am describing here, it is just for consuming the slow log _of_ redis, not using redis as a queue to consume events:
> 
> > Use the redis input to read entries from Redis slowlogs.

You are right, sorry.

**Comment by bert2002** [comment]
> @jsoriano That input is not what I am describing here, it is just for consuming the slow log _of_ redis, not using redis as a queue to consume events:
> 
> > Use the redis input to read entries from Redis slowlogs.

Thank you so much. I am trying to read the logs from redis for hours and now I know why they are not read. It would be perfect to have this working. My goal was to send logs from one logstash installation to another and have redis as cache in between and then write to a file.
