### ISSUE TITLE
Cannot enroll a Fleet Server on 8.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by joshdover** [elastic/beats#27839]
- Version: 8.0.0-SNAPSHOT
- Operating System: macOS 11.5.2 / Docker
- Discuss Forum URL:
- Steps to Reproduce: 
1. Start the latest Elasticsearch 8.0.0-SNAPSHOT
2. Start the latest Kibana 8.0.0-SNAPSHOT
3. Go to Fleet app in Kibana and go through the flow to setup a Fleet Server
4. Install an agent / fleet server with the given command from the UI or with this Docker command:
	```sh
	docker run --env FLEET_SERVER_ENABLE=true --env FLEET_SERVER_ELASTICSEARCH_HOST=http://<YOUR LOCAL IP>:9200 --env FLEET_SERVER_SERVICE_TOKEN=<SERVICE TOKEN FROM KIBANA UI> --env FLEET_SERVER_INSECURE_HTTP=1 -p 8220:8220 docker.elastic.co/beats/elastic-agent:8.0.0-SNAPSHOT
	```
5. Fleet Server fails to startup and repeats these logs:
	  ```
	  2021-09-09T12:25:46.530Z        INFO    log/reporter.go:40      2021-09-09T12:25:46Z - message: Application: fleet-server--8.0.0-SNAPSHOT[]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
	  2021-09-09T12:25:47.030Z        ERROR   status/reporter.go:236  Elastic Agent status changed to: 'error'
	  2021-09-09T12:25:47.030Z        ERROR   log/reporter.go:36      2021-09-09T12:25:47Z - message: Application: fleet-server--8.0.0-SNAPSHOT[]: State changed to FAILED: Error - elastic fail 403:security_exception:action [indices:monitor/fleet/global_checkpoints] is unauthorized for user [elastic/fleet-server] on indices [.fleet-actions], this action is granted by the index privileges [monitor,manage,all] - type: 'ERROR' - sub_type: 'FAILED'
	  2021-09-09T12:25:47.081Z        INFO    cmd/enroll_cmd.go:724   Fleet Server - Error - elastic fail 403:security_exception:action [indices:monitor/fleet/global_checkpoints] is unauthorized for user [elastic/fleet-server] on indices [.fleet-actions], this action is granted by the index privileges [monitor,manage,all]
	  ```

I have reason to suspect a bug in Elasticsearch with the elastic/fleet-server service account, but wanted someone from this team to take a look first before forwarding to the Elasticsearch team.

The reason I believe this is an Elasticsearch issue is that I also cannot successfully access this API using a service token that I create manually for the `elastic/fleet-server` service account or the one given from the UI:
```
# Create a token
$ curl -u elastic:changeme -XPOST localhost:9200/_security/service/elastic/fleet-server/credential/token

# Use the token against the checkpoints API
$ curl -H "Authorization: Bearer <service token>" localhost:9200/.fleet-actions/_fleet/global_checkpoints
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/.fleet-actions/_fleet/global_checkpoints]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/.fleet-actions/_fleet/global_checkpoints]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}},"status":401}
```

It's worth noting that both the Fleet Server enrollment and this manual access of this API work fine on Elasticsearch and Agent 7.15.

**Comment by joshdover** [comment]
@EricDavisX Do we have any e2e test coverage that should be testing this flow?

**Comment by blakerouse** [comment]
@aleksmaus any ideas on this? maybe this is an issue in elasticsearch?

**Comment by aleksmaus** [comment]
> @aleksmaus any ideas on this? maybe this is an issue in elasticsearch?

@blakerouse seems like permissions issue, asking ES team if anything changed in the latest snapshot.

**Comment by EricDavisX** [comment]
@joshdover hi - I don't know why it would fail now.
We do have e2e-testing scenarios that cover this (nearly all of them except for the standalone Agent cases), for example:
https://github.com/elastic/e2e-testing/blob/master/e2e/_suites/fleet/features/fleet_mode_agent.feature

And the recent tests passed on master line:
https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-mbp/job/master/1496/testReport/(root)/
I can tag you in slack too for the daily bot post in Agent room.

Is it possible our in-repo docs are out of date and need some tweak?  Can we reference against the on-line Docs to confirm?  It may yet be a bug of course.

**Comment by ywangd** [comment]
Since https://github.com/elastic/elasticsearch/pull/74212 (8.0 only), system indices are now treated as restricted result. As a result, fleet-server service account needs privileges to access restricted index names under the `.fleet-*` namespace. We missed that change in the PR. I raised a PR for fix: https://github.com/elastic/elasticsearch/pull/77531
Thanks for catching it.

**Comment by ruflin** [comment]
PR got merged about 5 hours ago but last snapshot is 7h old. I triggered a new snapshot build to have this available soonish.

**Comment by joshdover** [comment]
> We do have e2e-testing scenarios that cover this (nearly all of them except for the standalone Agent cases), for example:
> [https://github.com/elastic/e2e-testing/blob/master/e2e/_suites/fleet/features/fleet_mode_agent.feature](https://github.com/elastic/e2e-testing/blob/master/e2e/_suites/fleet/features/fleet_mode_agent.feature?rgh-link-date=2021-09-09T18%3A42%3A32Z)

Based on my cursory scan of these tests, it appears we don't test enrolling a Fleet server, only an Elastic Agent which won't hit this case. Thanks for adding this to elastic/obs-dc-team#489

**Comment by EricDavisX** [comment]
I think I was typing too fast, I forgot to explicitly cite that the Fleet Server enrollment is implied in all of the tests.  The Agent can't run in Fleet mode without a Fleet Server.  But it does call out that we have a test hole in not having more options for Fleet Server covered in its own .feature file.

We will get the back-fill automation done over time, manual tests cover it well.  We also have other nightly usage of the 8.0 snapshot that would catch items like this failing, and if I can make some time shortly I can confirm that (I see a jenkins job failing for an environment deploy and need to confirm if it is perhaps this same reason).

If you have concerns or want to dig in off-line with us I'd be very glad to review and figure out more, it is possible this case isn't covered, the devil may be in the details of it.  @joshdover thanks much

**Comment by joshdover** [comment]
> I think I was typing too fast, I forgot to explicitly cite that the Fleet Server enrollment is implied in all of the tests. The Agent can't run in Fleet mode without a Fleet Server. But it does call out that we have a test hole in not having more options for Fleet Server covered in its own .feature file.

Ah I think I misread the `nearly all of them except for the standalone Agent cases` statement to mean that we mostly covered standalone. Let's talk offline about how to better surface thee test failures to the team(s) and ensure that this case is being covered. Thanks for the context, @EricDavisX.

I have confirmed that this issue has been fixed, closing this issue.
