### ISSUE TITLE
[Journalbeat]: Journalbeat terminated with errors after running with `sudo ./journalbeat -e`

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#27832]
**Kibana version:**  7.15.0 BC-5 Kibana Cloud environment

**Host OS:** AWS-Ubuntu 20

**Build details:**
```
Build 43957
Commit: 0239ff6864dd9930cfe9bcd9a679272f2b7465c2
Artifact Link: https://staging.elastic.co/7.15.0-edd09abf/downloads/beats/journalbeat/journalbeat-7.15.0-linux-x86_64.tar.gz
```

**Steps to reproduce:**
1. Download and extract **journalbeat-7.15.0-linux-x86_64.tar.gz** artifact.
2. Update the `journalbeat.yml`:
```
cloud.id: "7150-i-o-optimized-deployment:ZXVyb3BlLXdlc3QxLmdjcC5jbG91ZC5lcy5pbyQ4MGM4NDgyYjRlODE0Yzkxxx=="
cloud.auth: "elastic:IEtKXRAmrH4zuGxxxxxxx"
```
3. Update `journalbeat.inputs:` in journalbeat.yml:
```
- paths:
    - "/home/ubuntu/journals/system.journal"
  seek: cursor
```
**We have copied this journal file from `var/log/journal/xxxxabc/` folder and granted chmod 777 permissions.**
Below attached system.journal:
[system.zip](https://github.com/elastic/beats/files/7135248/system.zip)

4. Run below commands:
```
./journalbeat setup -e
sudo chown root journalbeat.yml 
sudo ./journalbeat -e
```
5. Observe Journalbeat is started and terminated without giving any data and errors are attached below:
[errors after run command.txt](https://github.com/elastic/beats/files/7135078/errors.after.run.command.txt)

**journalbeat.yml:**
[journalbeat.zip](https://github.com/elastic/beats/files/7135084/journalbeat.zip)

**Expected Result:**
Journalbeat should run after running `sudo ./journalbeat -e` command.

**Reference Issue:**
https://github.com/elastic/beats/issues/26369

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @kvch

**Comment by EricDavisX** [comment]
Let's treat this with urgency, until we know more.  @amolnater-qasource can we test it with a different host type, either Linux or macOS?  Getting more data is helpful as it is late in the cycle

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
As per docs for Journalbeat at https://www.elastic.co/guide/en/beats/journalbeat/current/journalbeat-installation-configuration.html there are no steps for macOS.

Further, we have attempted to install Journalbeat on Debian 10 machine with above mentioned steps and **we are successfully able to install and get the data under Discover tab using Debian 10**. JFI, we have created `journalbeat-*` index manually.

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/132804027-f0626221-2591-4116-b15b-40a4d24f0a3e.JPG)

Hence, it seems to be **an issue with .tar artifacts as reported** above.

**Build details:**
```
Build 43957
Commit: 0239ff6864dd9930cfe9bcd9a679272f2b7465c2
Artifact Link: https://staging.elastic.co/7.15.0-edd09abf/downloads/beats/journalbeat/journalbeat-7.15.0-amd64.deb
```

Please let us know if anything else is required from our end.
Thanks

**Comment by EricDavisX** [comment]
Thank you Amol.  Ubuntu 20 is on our support matrix: https://www.elastic.co/support/matrix
 - I'd like to look at this, but if it is env specific I cite it shouldn't be a blocker.  it is merely high urgency.

**Comment by EricDavisX** [comment]
Discussed, this is being reduced in severity - Journalbeat is still in Beta and we rather are not surprised to have incompatibilities between or bugs on newer Linux Distros (with systemd).  So we can get back to this later - removing from urgent list

**Comment by jlind23** [comment]
@EricDavisX as journalbeat is not supported anymore (Removed in 7.16) we may close this issue.
cc @kvch

**Comment by amolnater-qasource** [comment]
Thanks @jlind23 for confirming that journalbeat is not supported anymore and closing this issue.
