### ISSUE TITLE
Docs missing for elastic-agent proxy configuration

### ISSUE THREAD

**Issue by nerophon** [elastic/beats#27845]
In 7.14.x it is possible to run Elastic Agent via proxy. There is a flag:
`--proxy-url`

However, currently this flag isn't documented. Note that proxy mode was actually broken in 7.14.0 and fixed in 7.14.1. Please see: https://github.com/elastic/beats/issues/27114.

Note also we observed the following:
> Elastic Agent appears to configure various Beats to send logging/metric data to Elasticsearch. In the configuration file for Filebeat (which is created by the Elastic Agent), it doesn't appear to have any configuration for using the proxy. From a quick glance it appears that the "enroll --proxy-url" option does nothing for the Beats.

> By trial and error, we've gotten it to work using --proxy-url to enroll the agent and environment variables (HTTP_PROXY, HTTPS_PROXY, NO_PROXY) so the Beats are also aware of the proxy settings. As we've used the RPM file to install the Elastic Agent (which runs as a Systemd service), we've had to configure Systemd to provide these Environment Variables to the elastic-agent.service.

This must also be documented; having said that, perhaps Agent should handle this when doing automatic configuration?

**Comment by dedemorton** [comment]
Closing this issue as a duplicate because we are tracking the requirement here: https://github.com/elastic/observability-docs/issues/593

From what I understand, there were some problems related to proxy support in 7.15. It is on our radar for 7.16. Thanks!
