### ISSUE TITLE
[Elastic Agent] system.yml is not disabled in Metricbeat

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#27857]
We have seen several reports where Elastic Agent tried to ingest data into a `metricbeat-*` index but did not have permissions. It turned out that for some reason on Windows the `system.yml` file in the modules.d directory is not renamed to `system.yml.disabled` which causes this. The workaround for now is to rename the file manually.

We need to investigate why this happens in the first place.

## Links

* [Discuss topic](https://discuss.elastic.co/t/action-indices-admin-auto-create-is-unauthorized-for-api-key-id-of-user-elastic-fleet-server-on-indices-metricbeat-7-14-1-2021-09-08-this-action-is-granted-by-the-index-privileges-auto-configure-create-index-manage-all/283608/28)

**Comment by ruflin** [comment]
Under https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/spec/metricbeat.yml#L12 we rename the `system.yml` to `system.yml.preference` so I assume the issue is somewhere there. @michalpristas Instead of moving files around I would think it is better to just disable the modules.d feature completely. We could do this through introducing a `enabled: false` flag or likely an easier way is to set `metricbeat.config.modules.path: ""`. Like this, it will never find any modules file. It might cause issues because it is an invalid path but that needs to be validated. In addition, we should make sure the reloading is also disabled so no process runs frequently to check for changes.

**Comment by ruflin** [comment]
Digging more into the code, it seems a enabled flag already exists: https://github.com/elastic/beats/blob/master/metricbeat/beater/metricbeat.go#L231 But I'm not sure if this only disables the reloading or all loading of the modules.d directory. @exekias Might remember.

**Comment by exekias** [comment]
I think it would actually disable them, this should be easy to test

**Comment by ruflin** [comment]
I opened a PR trying this out: https://github.com/elastic/beats/pull/27860
