### ISSUE TITLE
Darwin .tar.gz shows a 'cpu error' when trying to install Elastic Agent on M1 chip macOS

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#27861]
This is 7.15 BC5 of Elastic Agent + Stack, on an M1 mac Mini the Security team had to offer for testing.  I can share connection details offline.

- Steps to Reproduce: 
1) download and unarchive the .tar.gz Darwin Elastic Agent package 
2) run:
sudo ./elastic-agent install -f url=https://<url>:443 --enrollment-token=<token...>
3) see error in command line

This would appear to be regression, as the prior Agent was seen working on M1 architecture.  But, it may actually be a problem with the specific test environment, we have too few of them to be able to test further just now.  Testing an older Agent there, an testing a different host is the next steps.

screenshot:
![hoghledfibchippn](https://user-images.githubusercontent.com/12970373/132858980-3a53968f-1287-4812-8ee5-cc0a6b3231d4.png)

**Comment by EricDavisX** [comment]
@amolnater-qasource and team were following up to see if they can test an older Agent to confirm.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have re-validated this issue with 7.14.1 and 7.13.4 shipped agents, we observed same issue `CPU error` on both the agents on running install command.

**Screenshots:**
![6](https://user-images.githubusercontent.com/77374876/132860284-c01afce5-4e45-4b6f-ba2c-9d10fa21a54e.JPG)
![5](https://user-images.githubusercontent.com/77374876/132860273-128bc295-b145-4550-a093-fc68f70acf2c.JPG)

Please let us know if anything else is required from our end.
Thanks

**Comment by EricDavisX** [comment]
I'd like the team to find another M1 macOS to test out on to compare - It seems very possible something specific about that host is not well.  It may yet be a real bug, but prior shipped versions that we know worked are not working here so it is suspicious and reduced in severity/impact.

Let's see if anyone else in the group has a mac and can comparison test.

**Comment by willyu-elastic** [comment]
I was able to test on my mac M1 mini, while I was using macOS 12, I was still able to run 7.15 for both agent and endpoint security

![screen_shot_2021-09-10_at_10 49 55_am](https://user-images.githubusercontent.com/56367822/132899521-14c6b35c-f2d0-43bb-8def-23c662e1b7bf.png)

**Comment by fearful-symmetry** [comment]
@EricDavisX I have an M1 floating around. What specific executable is this?

**Comment by nimarezainia** [comment]
@EricDavisX Which version of the agent was last tested? officially we don't currently have support for M1.

**Comment by EricDavisX** [comment]
Thanks so much, Will.

Thanks @fearful-symmetry - we use the darwin tar.gz for macOS Agent tests.  like this:
elastic-agent-7.14.1-darwin-x86_64.tar.gz
  It runs in a compatibility mode, not with a native M1 compiled binary.

@nimarezainia we have been testing for several releases, to ensure it works as well as it can, per the current state of development.  This was with 7.15 latest BC it seems.

I will question what's going on with the machine that was tested on prior, I see no reason why it wouldn't work, so we can review that as desired now or put it to the backburner if we need to focus elsewhere.

**Comment by fearful-symmetry** [comment]
Alright, ran this, could not reproduce. Looks similar to this? https://apple.stackexchange.com/questions/408375/zsh-bad-cpu-type-in-executable

**Comment by EricDavisX** [comment]
Ah!  @fearful-symmetry is thinking better than me! :)  I bet the vm on the QA / Engineering Productivity team was reset to clear it for fresh tests (may even be done often) - and it doesn't currently have Rosetta installed.  @jesse-sant do you mind to check?  And if so, we can document expectations for the larger testing team.  If it DOES have Rosetta, it still sounds familiar and an area we could follow up around.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We attempted to install .darwin.tar.gz agent on mac mini using 7.16 snapshot artifact and found that, we are able to install agent on same today, without any errors. 

Screenshot:
![image](https://user-images.githubusercontent.com/72375798/134502905-e3467063-0186-4e8d-a45a-b3d4fee5408e.png)

Thanks
QAS

**Comment by EricDavisX** [comment]
with this, I would like to close it out.  we can re-open if / when it is reproducible.  thanks all.
