### ISSUE TITLE
[libbeat] ILM writes should use `require_alias=true`

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#27874]
It's pretty common that we see issues around ILM where users have deleted their write alias causing running beats instances to auto-create an index where the write alias should (with auto-mappings to boot, since the template won't be applied). 

We could easily fix this by setting `require_alias=true` in the bulk requests, which is [documented here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#docs-bulk-api-query-params). Even though we're currently moving toward fleet and data streams, this will still help a lot of users since that change over will take some time.

I've marked this as a bug since the current behavior really is broken IMHO. 

CC @ruflin @kvch

**Comment by ruflin** [comment]
+1 on enabling this. @andrewvc What is the behaviour of `require_alias=true` if the target is a data stream? 

PS: If I remember correctly, `require_alias` feature actually comes out of the "pre" development of data streams and was the initially approach that Elastic Agent planned to take.

**Comment by andrewvc** [comment]
I'm not sure on either of those points unfortunately ruflin. I'd think they'd be easy to resolve whenever work starts on this. Any idea on timeframe, is this scheduled for anytime in the near future?

**Comment by jlind23** [comment]
@kvch worked on it recently, she will quickly keep you posted here.

**Comment by kvch** [comment]
I have opened a new pull request for this that targets 7.17 branch: https://github.com/elastic/beats/pull/29879

As mentioned in the description, there is no need for this on 8.x because we use data streams there.

**Comment by jlind23** [comment]
Closed by: #29879
