### ISSUE TITLE
Filebeat to ES - insecure: true

### ISSUE THREAD

**Issue by mrjameshamilton** [elastic/beats#2787]
I have set insecure: true in the Filebeat configuration but it's still complaining: "certificate signed by unknown authority"

**Comment by monicasarbu** [comment]
Please provide us with more details, like what version of Filebeat are you using, and your configuration file. In the FAQ section of the documentation, we provide a few solutions for [x509: cannot validate certificate](https://www.elastic.co/guide/en/beats/filebeat/5.0/faq.html#cannot-validate-certificate).

**Comment by monicasarbu** [comment]
Closing the issue as there is no further feedback.
