### ISSUE TITLE
Filebeat kubernetes provider mixed logs another containers from same pod

### ISSUE THREAD

**Issue by froheik** [elastic/beats#27882]
Filebeat 7.14.1
RH OpenShift version 4.7.22 / centos
https://discuss.elastic.co/t/filebeat-kubernetes-provider-mixed-logs-another-containers-from-same-pod/283784

    filebeat.autodiscover:
      providers:
        - type: kubernetes
          include_pod_uid: true
          in_cluster: true
          templates:
            - config:
                - type: container
                  paths:
                    - /var/log/pods/*_${data.kubernetes.pod.uid}/*/*.log

With that config, part of logs from 2 containers in single pod are mixed.
On input - container1 ( log.file.path=/var/log/pods/container1-uid/0.log ),  and container2 ( log.file.path=/var/log/pods/container2-uid/0.log )
In elastic -  kubernetes.container.name: container1 and log.file.path=/var/log/pods/container2-uid/0.log 
That bug happen only with part of logs. No any errors in filebeat log, harvesters for both containers started normally.
![Screenshot from 2021-09-09 16-48-03](https://user-images.githubusercontent.com/11730623/133017686-10a19199-222c-42cb-aaf4-56f8212ac930.png)

**Comment by jsoriano** [comment]
I think this is a configuration issue more than a bug, closing here and following in the discuss issue https://discuss.elastic.co/t/filebeat-kubernetes-provider-mixed-logs-another-containers-from-same-pod/283784
