### ISSUE TITLE
[Filebeat][Cisco][Nexus] Add support for more log messages

### ISSUE THREAD

**Issue by philippkahr** [elastic/beats#27911]
Version: 7.14.1

Here are some example messages that need parsing:

```
<189>: 2021 Sep  9 12:30:37 UTC: %VSHD-5-VSHD_SYSLOG_CONFIG_I: Configured from vty by philippkahr on 192.168.11.14@pts/2
<188>: 2021 Sep 10 09:21:10 UTC: %ETHPORT-4-IF_SFP_WARNING: Interface Ethernet1/35, High Rx Power Warning cleared
<188>: 2021 Sep 10 09:16:10 UTC: %ETHPORT-4-IF_SFP_WARNING: Interface Ethernet1/35, High Rx Power Warning
```

all three messages show `dissect_parsing_error`. We should be rethinking if a module that does not support a message should throw a `dissect_parsing_error` or instead something that is more helpful? It is a parsing error per se, but in reality it ain't because it is a not yet supported messages. Maybe something like `not_yet_supported`. We could add some documentation about `not_yet_supported` to lead them to open GitHub issues with example log messages so we can make this module better

**Comment by admlko** [comment]
Same issue here.

Here are a couple of sample log lines:
`<189>routerhostname: 2021 Oct 6 08:21:12.231 UTC: %ETHPORT-5-IF_TX_FLOW_CONTROL: Interface Ethernet1/6, operational Transmit Flow Control state changed to off`
`<189>routerhostname: 2021 Oct 19 22:11:43.226 UTC: %VSHD-5-SYSLOG_CONFIG_I: Configured from vty by admin on 1.2.3.4@pts0/0 (message repeated 1 time)`
`<189>routerhostname: 2021 Oct 1 11:01:54.936 UTC: %ETHPORT-5-IF_HARDWARE: Interface Ethernet1/6, hardware type changed to 10G`
