### ISSUE TITLE
Document add_cloud_metadata processor

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#2791]
We need to add documentation for the `add_cloud_metadata` (#2728)  processor. I can write up the initial draft for this.

In support of new processors, we should probably look at reorganizing the [documentation](https://www.elastic.co/guide/en/beats/winlogbeat/5.0/configuration-processors.html) for processors. Other products have a page per processor.

**Comment by tsg** [comment]
+1 for some sort of standard format for processors docs. Pinging @dedemorton for early suggestions.

**Comment by monicasarbu** [comment]
+1 great idea to have one page for processor.

**Comment by dedemorton** [comment]
How about bumping processors up in the nav so there is container called Processors that appears at the same level as Configuration Options? The Processors topic would describe what a processor is and how you use it (including how to define conditional logic). Then, nested under Processors, you would have a topic for each processor (arranged alphabetically). The content would be single-sourced like we do for config options. So something like this (using Winlogbeat as a random example):
...
Configuring Winlogbeat
  Configuration Options (collapsed)
  Processors
    add_cloud_metadata
    drop_event
    drop_files
    etc...
