### ISSUE TITLE
[Winlogbeat][Windows-cert support]: Unable to install winlogbeat using certs through logstash.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#27934]
**Kibana version:**  7.15.0 BC-5 Kibana self-managed environment

**Host OS:** AWS-Windows server 2012 r2

**Build details:**
```
Build 43957
Commit: 0239ff6864dd9930cfe9bcd9a679272f2b7465c2
Artifact Link: https://staging.elastic.co/7.15.0-edd09abf/summary-7.15.0.html
```

**Pre-requirements:**
1. ELK setup should be completed.
2. Winlogbeat artifact should be downloaded and extracted in `Program Files`.

**Steps to reproduce:**
1. Setup winlogbeat.yml:
[winlogbeat.zip](https://github.com/elastic/beats/files/7168561/winlogbeat.zip)

2. Setup logstash.conf:
[logstash.zip](https://github.com/elastic/beats/files/7168566/logstash.zip)

3. Run `curl -v --cacert ca.crt https://localhost:5044`
4. Observe below errors:
![4](https://user-images.githubusercontent.com/77374876/133404712-74bee828-f416-45b0-8d80-b6b09c39f070.JPG)

5. Run winlogbeat setup command:  `.\winlogbeat.exe setup -e`
6. Observe below errors:
![5](https://user-images.githubusercontent.com/77374876/133404731-43bf8de1-d7aa-48e7-831e-24dd74787f2e.JPG)

**Reference Link:**
https://discuss.elastic.co/t/winlogbeat-ignores-ca-certificates-in-windows-certificate-store/48209/
https://www.elastic.co/guide/en/beats/winlogbeat/current/configuring-ssl-logstash.html

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @mostlyjason 

CC: @EricDavisX

**Comment by EricDavisX** [comment]
I think this is a known unsupported situation.  We can evaluate if the Windows store works for Agent tho, as Agent is the intended path forward into the future (long term) for everyone.  I'll follow up with you on that offline Amol, thanks.

**Comment by mostlyjason** [comment]
Yeah I think this is a known limitation. Reassigning to @nimarezainia who is the PM for Beats to determine if this should be supported or not.

**Comment by andrewkroh** [comment]
> Observe below errors:

The errors in this images indicate that the YAML contents of the config file are invalid. Fix the errors then use the `winlogbeat test output` command to test connectivity to Logstash. Please share the winlogbeat.yml file so we can understand how Winlogbeat has been configured.

**Comment by amolnater-qasource** [comment]
Hi @andrewkroh 
We have attempted to revalidate this issue today on 7.15.0 self-managed kibana cloud environment, we got similar errors as shared above.

However as per the steps shared above we are not able to install the winlogbeat using certificates.

Due to which we are not able to run `winlogbeat test output`.

Please find below attached winlogbeat.yml:
[winlogbeat.zip](https://github.com/elastic/beats/files/7351061/winlogbeat.zip)

Please let us know any specific steps to run winlogbeat using certificates and through logstash(if it's supported)/
Thanks

**Comment by amolnater-qasource** [comment]
Hi @andrewkroh 
We have re-attempted this on self-managed 7.15.0 Kibana and done the required changes to test it without certificates with `ssl_verify_mode => "none"`.

We are **successfully** able to view winlogbeat data under Discover tab when installed through logstash _(without certs)_.

**Screenshot:**
![11](https://user-images.githubusercontent.com/77374876/138243965-d726f69d-e33a-4f1c-8479-9b2122bb1166.JPG)

So it seems to be issue with the certs. 

Please let us know if certs error can be resolved.
cc: @EricDavisX 

Thanks

**Comment by EricDavisX** [comment]
@andrewkroh if you don't mind, I'll unassign myself - you wanna take it?
