### ISSUE TITLE
[Heartbeat] Add throttling options

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#27952]
When https://github.com/elastic/synthetics/issues/284 is complete we'll need to add support for it.

ACs:
* Add `--throttling <d/u/l>` and `--no-throttling` options (as defined in Synthetics)

**Comment by awahab07** [comment]
**Post FF Testing**

To test the impact of modified Networking Conditions as a result of configured `throttling` parameters in **yml**, I created a small web application which first _downloads_ and then _uploads_ a large image (3MB in size), without requiring user interaction. To upload the image, the downloaded image's blob is uploaded as _FormData_.

**Comment by awahab07** [comment]
@andrewvc @vigneshshanmugam Given the default `throttling` and while POSTing a large payload (3MB image to localhost, following this [suggestion](https://github.com/elastic/synthetics/issues/284#issuecomment-956142103)), journey doesn't wait for the POST request to complete. Any assertion dependent on request completion fails and the request is not captured in the breakdown.

I've tried extending Playwright's assertion timeouts. Is there any other configuration which controls the journey's timeout as a whole? The journey is an inline script in yml file.

**Comment by vigneshshanmugam** [comment]
@awahab07 Can you paste the script you have tested? There are multiple ways to control a request timeout, would like to see the script and propose solution.

**Comment by awahab07** [comment]
```typescript
step('Upload/Download Image - Default throttling', async () => {
  await page.goto('http://localhost:3300/');
  await page.click('text=Download');
  await page.click('text=Image downloaded!', { timeout: 60 * 1000 });
  await page.click('button:has-text("Upload")');
  await page.click('text=Image uploaded!', { timeout: 60 * 1000 });
});
```
@vigneshshanmugam Clicking of the buttons Download and Upload initiates the downloading and posting of the image data. Download request gets captured. Whereas the last assertion fails because the journey ends while the upload is in progress.

**Comment by paulb-elastic** [comment]
Where I've done something similar in the past, I've made the page add some text when it's finished the task, for example with something like this:

`document.getElementById("finishedLocation").innerText="hello world"`

Then made Playwright wait for that to exist on the page, for example:

`await page.waitForSelector('text=hello world');`

**Comment by vigneshshanmugam** [comment]
Proposed solution from Paul also works. There is also other way to wait for that upload request to complete using Playwright API. Use wait for response from the upload endpoint - https://playwright.dev/docs/api/class-page#page-wait-for-response

**Comment by awahab07** [comment]
When the timeout for `waitForSelector` or `waitForResponse` is around 10 seconds, pings are not pushed to the monitor at all. Is it an expected behavior?

**Comment by awahab07** [comment]
**Post FF Testing**

To test the impact of modified Networking Conditions as a result of configured `throttling` parameters in **yml**, a small web application is created which first downloads and then uploads a large payload (3MB image). To upload the image, the downloaded image's blob is POSTed as FormData ([following](https://github.com/elastic/synthetics/issues/284#issuecomment-956142103)).

Five different monitors with varied throttling values: Throttling disabled, Default throttling, High latency, Low upload and Low download rate are tested. Then network performance breakdown for download and upload requests for each monitor is noted. Notable properties of NetworkInformation are also captured during tests ([following](https://github.com/elastic/synthetics/issues/284#issuecomment-957115743)).

**LGTM**
- With low download rate, payload takes significantly longer to download (**Content downloading** has high values). Also `NetworkInformation.downlink` is lower.
- With low upload rate, either upload fails or takes longer.
- With high latency, TTFB takes approximately the same time as configured `l` value in `throttling`. Also `NetworkInformation.rtt` reflects the same value.

**Notables**
- When throttling is configured for 50Mbps download speed, the **NetworkInformation.downlink** reads 10Mpbs.
- When throttling is configured for 20ms latency, the **NetworkInformation.rtt** reads 0.

Findings (all times are in **ms**):
 Condition | `throttling` | Action | Request start | Waiting (TTFB) | Content downloading
 --- | :---: | --- | ---: | ---: | ---: 
| No Throttling  | false  | Download | 389.46 | 3.65 | 8.79 
|   |  | Upload | 879.08 | 2.39 | 0.31 
| Default Throttling  | (empty)  | Download | 1262.69 | 20.74 | 4615.00
|   |  | Upload | 6313.40 | 22.64 | 1.00
| High Latency  | 500d/300u/100l  | Download | 571.37 | 100.81 | 62.16 
|   |  | Upload | 1211.95 | 101.01 | 0.44 
| Low Upload  | 100d/1u/20l  | Download | 433.10 | 20.24 | 236.36 
|   |  | Upload | 1187.01 | 20.14 | 0.59
| Low Download  | 5d/50u/20l  | Download | 1162.26 | 23.16 | 4613.84 |
|   |  | Upload | 6182.48 | 21.51 | 0.47 

Snapshots:
Monitor | `throttling` | **NetworkInformation** | Download | Upload
--- | :---: | :---: | :---: | :---:
No Throttling | false | <img width="619" alt="No Throttlign NetworkInformation" src="https://user-images.githubusercontent.com/2748376/140099899-878e0077-3286-48f6-9e2b-f6ce018f86f8.png"> | <img width="460" alt="No Thottling Download" src="https://user-images.githubusercontent.com/2748376/140099902-276da72c-ef03-4850-8f7d-837355ee2193.png"> | <img width="467" alt="No Throttlign Upload" src="https://user-images.githubusercontent.com/2748376/140099906-44bafc3c-8d59-440e-824d-4becb1d4a614.png">
Default Throttling | (empty) | <img width="620" alt="Default NetworkInformation" src="https://user-images.githubusercontent.com/2748376/140100285-82b78bb9-7c3e-437c-baee-f6a63e57221a.png"> | <img width="468" alt="Default Download" src="https://user-images.githubusercontent.com/2748376/140100281-1665cdbb-915d-4bb5-b2b6-c91c7dfbeeef.png"> | <img width="467" alt="Default Upload" src="https://user-images.githubusercontent.com/2748376/140100288-d2a4bcf6-0834-4236-a754-506e9057ac24.png">
High Latency | 500d/300u/100l | <img width="616" alt="Latency NetworkInformation" src="https://user-images.githubusercontent.com/2748376/140100580-fbf03870-656b-4beb-86ce-b996581f0f8b.png"> | <img width="463" alt="Latency Download" src="https://user-images.githubusercontent.com/2748376/140100583-f325d4a4-3249-4203-aa6a-732a3bc8f103.png"> | <img width="467" alt="Latency Upload" src="https://user-images.githubusercontent.com/2748376/140100972-8f352444-f963-4500-8c5b-2709ba017ac1.png">
Low Upload | 100d/1u/20l | <img width="614" alt="Low Upload NetworkInformation" src="https://user-images.githubusercontent.com/2748376/140101212-ab835a90-9b17-4ee5-87ca-adbed2096a47.png"> | <img width="463" alt="Low Upload Download" src="https://user-images.githubusercontent.com/2748376/140101215-b218ed4a-a942-4774-9088-99f0bf5d16ba.png"> | <img width="468" alt="Low Upload Upload" src="https://user-images.githubusercontent.com/2748376/140101220-84b6eae6-691a-433f-94f2-c75b2b6f8a6a.png">
Low Download | 5d/50u/20l | <img width="618" alt="Low Download NetowrkInfomation" src="https://user-images.githubusercontent.com/2748376/140101277-0f26cd1d-9b69-4169-9a51-aaac8f7c4256.png"> | <img width="466" alt="Low Downlaod Download" src="https://user-images.githubusercontent.com/2748376/140101280-e6d13b13-c689-4272-87cd-85bfa01b48a7.png"> | <img width="470" alt="Low Download Upload" src="https://user-images.githubusercontent.com/2748376/140101284-1abba327-41a5-423a-9381-cd827e8e09ec.png">
