### ISSUE TITLE
Function beat requires extra permissions when enabling virtual_private_cloud

### ISSUE THREAD

**Issue by jmceniery** [elastic/beats#28013]
For confirmed bugs, please report:
- Version: 7.14
- Steps to Reproduce: 

When enabling virtual_private_cloud: https://www.elastic.co/guide/en/beats/functionbeat/current/configuration-functionbeat-options.html#functionbeat-virtual_private_cloud
the deployment fails as the role does not have eni attach permissions

The following was added to the role consumed by functionbeat.

```
yaml
- Action:
- ec2:DescribeNetworkInterfaces
- ec2:CreateNetworkInterface
- ec2:DeleteNetworkInterface
- ec2:DescribeInstances
- ec2:AttachNetworkInterface
Effect: Allow
Resource: "*"
```

**Comment by pushred** [comment]
For this to work in my case I had to use `functionbeat export function example > stack.json` and then modify the exported CloudFormation template to include the following for the generated function IAM execution role:

```json
"ManagedPolicyArns": [
  "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
 ]
```
