### ISSUE TITLE
Could not parse events from cloudwatch logs, error: EOF - Functionbeat AWS

### ISSUE THREAD

**Issue by felipeIntelipost** [elastic/beats#28011]
Hi, I'm deploying fucntionbeat to collect logs from cloudwatch and upload to elasticsearch.
I deployed the function, but I'm getting the following error when processing and sending the log:
ERROR	[cloudwatch_logs]	aws/cloudwatch_logs.go:122	Could not parse events from cloudwatch logs, error: EOF

**Comment by avoidik** [comment]
I assume empty input caused the problem, you can easily reproduce it by sending `{}` to a functionbeat function from the aws web console

**Comment by felipeIntelipost** [comment]
Hi, I've updated the functionbeat version to 7.15, now it's working correctly.
