### ISSUE TITLE
Metricbeat's include/fields.go never gets updated

### ISSUE THREAD

**Issue by MichaelKatsoulis** [elastic/beats#28021]
After updating some fields declared in libbeat `add_kubernetes_metadata` processor [(fields.yml)](https://github.com/elastic/beats/blob/master/libbeat/processors/add_kubernetes_metadata/_meta/fields.yml) and run `make update` in root beats I notice that for all beats (filebeat, packetbeat, heartbeat etc) include/fields.go files get updated automatically.

This is not the case for metricbeat  [include/fields/fields.go](https://github.com/elastic/beats/blob/master/metricbeat/include/fields/fields.go). The file never gets updated and this leads to tests failing because tests use [FieldsRegistry](https://github.com/elastic/beats/blob/master/libbeat/asset/registry.go#L54) in [testdata.go](https://github.com/elastic/beats/blob/master/metricbeat/mb/testing/testdata.go#L320) which is updated by the fields.go files.

It also looks weird that `metricbeat/include/fields/fields.go` does not follow the pattern of all the `include/fields.go` of the rest of the beats.  The file in metricbeat is one layer deeper (`include/fields/fields.go` instead of [`include/fields.go`](https://github.com/elastic/beats/blob/master/filebeat/include/fields.go)).

There is this [line](https://github.com/elastic/beats/blob/master/libbeat/scripts/Makefile#L356) in Makefile but is never executed.  I managed to manually update the file by running `go run ${INSTALL_FLAG} ../dev-tools/cmd/asset/asset.go  -pkg include -in fields.yml -out include/fields/fields.go metricbeat`

**Comment by MichaelKatsoulis** [comment]
cc @ruflin

**Comment by ruflin** [comment]
I remember there was a slight difference between filebeat and metricbeat and is why the additional nested fields.go exists but I would have to dig into the history to figure out why. But that it is not rebuilt is definitively a bug. My suspicion is that it went missing during a switch to mage from the Makefile (@andrewkroh rings a bell?).

@MichaelKatsoulis If you could open a separate PR to fix the bug and also backport it this would be great. Thanks for digging into it.

**Comment by MichaelKatsoulis** [comment]
https://github.com/elastic/beats/pull/28047 is created to fix the bug
