### ISSUE TITLE
How to config fiebeat.yml to implement multiline logic in openshift/kubernetes

### ISSUE THREAD

**Issue by lsy1990** [elastic/beats#28053]
Hi all，
    I deploy daemonset in openshift 3.11 to deploy filebeat.
the log is json  like below:
{"log":"W0922 10:48:03.257983       1 reflector.go:341] github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:668: watch of *v1.StorageClass ended with: The resourceVersion for the provided watch is too old.\n","stream":"stderr","time":"2021-09-22T10:48:03.258127725Z"}
{"log":"W0922 10:52:30.614798       1 reflector.go:341] github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:665: watch of *v1.PersistentVolume ended with: The resourceVersion for the provided watch is too old.\n","stream":"stderr","time":"2021-09-22T10:52:30.614938249Z"}

And the filebeat.yaml is below, when exception log is outputing,the log is not in a line.

  inputs:
    # Mounted `filebeat-inputs` configmap:
    path: ${path.config}/inputs.d/*.yml
    # Reload inputs configs as they change:
    reload.enabled: false
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

# Uncommnet this part and remove `filebeat.config.inputs` when running in Openshift and cri-o
filebeat.autodiscover:
  providers:
     - type: kubernetes
       include_pod_uid: true
       hints.enabled: true
       templates:
         - condition.regexp:
              kubernetes.container.name: '.+'
           config:
             - type: docker
               containers:
                 path: "/var/log/pods/*${data.kubernetes.pod.uid}/"
                 ids:
                   - "${data.kubernetes.container.name}"
               multiline.pattern: '^[[:space:]]'
               multiline.negate: false
               multiline.match: after
               processors:
                 - decode_json_fields:
                     process_array: true
                     max_depth: 10
                     target: ""
                     overwrite_keys: true
                     fields: ["message"]

# To enable hints based autodiscover, remove `filebeat.config.inputs` configuration and uncomment this:
#filebeat.autodiscover:
#  providers:
#    - type: kubernetes
#      hints.enabled: true

processors:
  - add_cloud_metadata:
  - drop_event:
      when:
        equals:
          kubernetes.container.name: "filebeat"
  - drop_event:
      when:
        regexp:
          message: "^DBG:"

**Comment by lsy1990** [comment]
filebeat

**Comment by ChrsMark** [comment]
Hi @lsy1990 !

You can find documentation about this at [https://www.elastic.co/guide/en/beats/filebeat/current/running-on-kubernetes.html](https://www.elastic.co/guide/en/beats/filebeat/current/running-on-kubernetes.html) and more specifically a dedicated part about extra steps required in Openshift. With these you should be covered.

I'm gonna close this issue for now.
