### ISSUE TITLE
[Getting Started] Update and Improve Integration Dashboards

### ISSUE THREAD

**Issue by alexfrancoeur** [elastic/beats#28071]
In 7.16, we plan to default to the integrations page for all add data activity (https://github.com/elastic/kibana/issues/111374). As a result, any new user that takes Elastic for a spin will more than likely have an agent / integration experience. First impressions are important and I believe we have an opportunity to improve ours. I know there have been some ongoing discussions around updating these dashboards over the years that follow best practices, improve aesthetics and take advantage of new capabilities (https://github.com/elastic/integrations/issues/269, https://github.com/elastic/beats/issues/27340) that would be great to implement.

As part of the getting started initiative, I'd like to prioritize this work so that new users are delighted by what we offer as part of their onboarding experience and can quickly "copy and paste" to iterate. I'd be interested in hearing this groups thoughts.  I believe this could have an impact on making users successful with our extended analytics capabilities for each solution use case.

cc: @tbragin @snide @VijayDoshi @mostlyjason @rayafratkina @AlonaNadler

**Comment by mostlyjason** [comment]
I believe @akshay-saraswat is the PM to drive improvements for dashboard guidelines since he is the PM for the ecosystem team

**Comment by akshay-saraswat** [comment]
I completely agree with you @alexfrancoeur. Without OOTB Dashboards, integrations provide less perceived value. Let's discuss and prioritize specific things that you plan to include in "getting started".

**Comment by mukeshelastic** [comment]
Hi @alexfrancoeur thanks for surfacing discussion on this topic. As a part of first user experience, we should evaluate the end to end user journeys for users choosing agent based data ingestion workflow. I see two user journeys that are owned by a specific integration, one is the integration policy configuration and other is the quality of assets.  The integration policy configuration is a precursor to ingesting data and having a cleaner user experience would be crucial for higher ingestion success. So I suggest  re-assessing UX for both journeys.  

Having said that, it will be a good start to prioritize this effort for few frequently used data sources over all supported data sources. Doing it selectively will help us understand and develop a process that we could apply to all other integrations over time. 

@akshay-saraswat For dashboards improvements, the integrations and lens team tracked [gaps issue](https://github.com/elastic/integrations/issues/265#issuecomment-766918346) and looks like most of the issues surfaced in them were fixed. So it would be good to start moving the dashboards using the lens and other good patterns described [here](https://github.com/elastic/integrations/issues/269) unless they have already been followed.
