### ISSUE TITLE
[Functionbeat] cannot find package "io/fs" in Google Cloud functions (go 1.13)

### ISSUE THREAD

**Issue by endorama** [elastic/beats#28132]
- Version: 7.15.0
- Operating System: N/A
- Discuss Forum URL: https://discuss.elastic.co/t/functionbeat-missing-package-io-fs/284975
- Steps to Reproduce: 
	1. run `functionbeat setup` targeting Google Cloud

Visible error:
```
Function: functionbeat-XXXXX, could not update, error: error while creating function (code: 3):

[89](/-/jobs/1615821324#L89)Build failed: src/pubsub/vendor/github.com/elastic/beats/v7/libbeat/metric/system/cgroup/cgv2/io_helper_linux.go:23:2: cannot find package "io/fs" in any of:
[90](/-/jobs/1615821324#L90) /workspace/src/pubsub/vendor/io/fs (vendor tree)
[91](/-/jobs/1615821324#L91) /usr/local/go/src/io/fs (from $GOROOT)
[92](/-/jobs/1615821324#L92) /workspace/src/io/fs (from $GOPATH); Error ID: 6191efcd
```

Functionbeat 7.15.0 cannot be deployed on GCP due to a missing package: `io/fs`.

This package is available in Go [since 1.16](https://pkg.go.dev/io/fs?tab=versions), but the runtime version we use to run functions is Go 1.13:
https://github.com/elastic/beats/blob/7e4affb6702a39f378170b8866f966d1b29e06fc/x-pack/functionbeat/manager/gcp/template_builder.go#L24

**Note** that Go 1.16 is still **preview** in [Google Cloud](https://cloud.google.com/functions/docs/concepts/go-runtime#gcloud):
![Screenshot from 2021-09-27 16-04-59](https://user-images.githubusercontent.com/526307/134924363-897cd8e1-1e2f-4312-a6aa-930c8a2f4d32.png)

**Comment by endorama** [comment]
Closed by error. Reopening.

This issue is related to https://github.com/elastic/beats/pull/27012

**Comment by kvch** [comment]
If this gets fixed we would only support it for a few weeks after its release. Hence, it does not make sense to fix it if we are removing it in the future.
