### ISSUE TITLE
Support hints based auto-discovery in Fleet managed agents

### ISSUE THREAD

**Issue by danielharada** [elastic/beats#28139]
**Describe the enhancement:**
To achieve parity with Beats, the Fleet managed agents need to support hints based auto-discovery in all container inputs such as Docker and Kubernetes.

**Comment by adammike** [comment]
This issue is blocking our adoption of elastic agent and elastic cloud. It's extremely urgent for our team.

**Comment by masci** [comment]
Duplicate of https://github.com/elastic/beats/issues/23876
