### ISSUE TITLE
[Self-managed 7.15]: No logs and data streams for second agent installed on self-managed fleet server.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#28152]
**Kibana version:**  7.15.0 Kibana self-managed environment

**Host OS:** Windows 10x64

**Build details:**
```
Build: 44040
Commit: add5d2c5ebeba1d8bcf6a79f8863cd78760e1b3e
Artifact Link: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.15.0-windows-x86_64.zip
```

**Pre-requirements:**
1. ELK setup should be completed.
2. Fleet Server must be setup on self-managed kibana.

**Steps to reproduce:**
1. Open ports for `8220` from advanced windows firewall settings.
2. Run agent install command on second machine.
3. Wait for 5 minutes and navigate to self managed Kibana.
4. Observe Agent shows up Healthy under Fleet>Agents tab.
5. Observe no logs under Logs tab and no data generated under Data Streams tab.

**Expected Result:**
Logs and data streams should generate for second agent installed on self-managed fleet server.

**Screenshots:**
![10](https://user-images.githubusercontent.com/77374876/135076548-f872c6c7-f035-47dd-bbb2-7831ac8611e8.jpg)
![8](https://user-images.githubusercontent.com/77374876/135076557-51c48f92-4d6a-4795-a6cb-ceb529aee221.JPG)
![9](https://user-images.githubusercontent.com/77374876/135076558-3712df2d-e10c-41eb-8039-33f8085e99e0.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned @blakerouse

CC: @EricDavisX

**Comment by EricDavisX** [comment]
Hi - this is basically indicating that all of Fleet / Agent isn't viable.  Which I'm sure (and really hope) isn't true.  Can we research your environment set up to see if anything new has been done or if it was known working prior?

Please tell us if you are using vSphere (Endgame cluster) or AWS hosts?  If vSphere, I would question the templates used during creation, we know that they were *just re-set back up and this is likely an artifact of something we expect to be set up that isn't yet.

I know it isn't easy to triage necessarily - do you have any working self-managed envs to compare to?  The Agent docs may help and it is a good chance to log tickets for improvement if they don't help enough!

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 

Thanks for your feedback, we have shared our environment details mail with you, subject "Environment details for #28152".
>Please tell us if you are using vSphere (Endgame cluster) or AWS hosts?

We have tested this with VSphere machines.
I used Windows 10 x64 template and also installed second agent on another Windows 10 x64. 
We have shared the IP for self-managed environment over the shared mail.

Please let us know if anything else is required from our end.
Thanks

**Comment by ruflin** [comment]
It would be good to have the logs from the Elastic Agent that does not seem to ship any data including the logs from processes (metricbeat / filebeat / ...)

**Comment by amolnater-qasource** [comment]
Hi @ruflin 
Please find below elastic-agent `debug` level logs:
[dlogs.zip](https://github.com/elastic/beats/files/7257711/dlogs.zip)

Please let us know if anything else is required from our end.
Thanks

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this issue on 7.15 AWS self managed kibana and found it **reproducible** there too:
**Scenarios covered:**
1. Vsphere Fleet Server and VSphere agent
2. Vsphere Fleet Server and AWS agent
3. AWS Fleet Server and AWS agent
4. AWS Fleet Server and VSphere agent

Inbound rules-Ports:
1. `8220`
2. `5555`

We are still not able to view any logs and data streams for these agents.

Please let us know if anything else is required from our end.
Thanks

**Comment by ruflin** [comment]
I see the following in the filebeat logs:

```
{"log.level":"error","@timestamp":"2021-09-30T03:50:37.910-0400","log.logger":"esclientleg","log.origin":{"file.name":"transport/logging.go","file.line":37},"message":"Error dialing dial tcp 127.0.0.1:9200: connectex: No connection could be made because the target machine actively refused it.","service.name":"filebeat","network":"tcp","address":"localhost:9200","ecs.version":"1.6.0"}
```

I wonder how the machine "actively" refused the connection? Any idea?

**Comment by EricDavisX** [comment]
I'll ask if anyone can dig in to review it - still hoping it may be a known bug.

**Comment by blakerouse** [comment]
Based on the description of the issue seems that the elasticsearch is also running on the Windows host. This will require that it is configured to bind to "0.0.0.0" as well as expose port 9200 through Windows firewall.

From what I have read, that has not been done.

Give that a try and see if it fixes the issue.

**Comment by amolnater-qasource** [comment]
@michalpristas We have re-attempted with the updated elasticsearch.yml:
[elasticsearch.zip](https://github.com/elastic/beats/files/7301810/elasticsearch.zip)

Re-installed the fleet server and Secondary Agent:
**elasticsearch host:** http://localhost:9200

When we changed it to the machine ip: we were unable to install Fleet Server.
We ran into following loop when executed install command for fleet server:
```
2021-10-07T10:06:38.367Z        INFO    cmd/enroll_cmd.go:724   Fleet Server - Restarting
2021-10-07T10:06:40.405Z        INFO    cmd/enroll_cmd.go:724   Fleet Server - Error - tls: first record does not look like a TLS handshake
```
Thanks!

**Comment by michalpristas** [comment]
I feel like we have a configuration problem exposing ES to the world rather than Elastic Agent issue

**Comment by jlind23** [comment]
@amolnater-qasource is it still relevant?
