### ISSUE TITLE
Packetbeat: wrong error message for flows timeout configuration

### ISSUE THREAD

**Issue by masaruh** [elastic/beats#2821]
- Version: Packetbeat 5.0.0-rc1
- Steps to Reproduce: set `100ms` to `packetbeat.flows.timeout`.

https://github.com/elastic/beats/blob/master/packetbeat/flows/worker.go#L22 should be something like `timeout must be >= 1s`?

**Comment by tsg** [comment]
I believe so, thanks for reporting!
