### ISSUE TITLE
Rename default overview dashboard

### ISSUE THREAD

**Issue by dadoonet** [elastic/beats#2823]
When you look at the default dashboards we have

![image](https://cloud.githubusercontent.com/assets/274222/19593804/98b5cf4e-9782-11e6-83b9-d34e02b65fde.png)

You can see that:
- Metricbeat is using:
  - Metricbeat system overview
  - Metricbeat overview
- Packetbeat is using:
  - Packetbeat Dashboard

Can we make that consistent so if someone search for "Dashboard" it will give the "where to start" for any beat?

![image](https://cloud.githubusercontent.com/assets/274222/19593902/fde35ba2-9782-11e6-83ab-2ac619e1f413.png)

**Comment by monicasarbu** [comment]
Closing this issue as a new convention for naming the dashboards and visualizations is defined in https://github.com/elastic/beats/issues/4984.
