### ISSUE TITLE
Do not log ERROR for watchers in not upgradable scenarios 

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#28334]
At the moment when we run agent in a container and it's not on usual path but e.g `/app/..`
we see error saying `failed to invoke rollback watcher` with a detail explaining executable could not be found.

When running in a container from different path as usual we should
- decrease log level to WARN
- investigate options to skip watcher execution in this scenario

**Comment by jlind23** [comment]
@AndersonQ this one could be a pretty good to start ramping up on the agent.

**Comment by AndersonQ** [comment]
This cannot be reproduced neither on the latest official docker image, `docker.elastic.co/beats/elastic-agent:7.16.2`, nor on master. Thus I'm closing it

**Comment by jlind23** [comment]
Thanks @AndersonQ for the work provided.
