### ISSUE TITLE
Metricbeat fstat on Windows always shows zero values

### ISSUE THREAD

**Issue by Cylindric** [elastic/beats#2842]
I'm running metricbeat on a bunch of Windows servers as a test, and I am seeing ES records for each drive on the server, but the values are always zero.

```
"system": {
      "diskio": {
        "io": {
          "time": 0
        },
        "name": "E:",
        "read": {
          "bytes": 0,
          "count": 0,
          "time": 0
        },
        "write": {
          "bytes": 0,
          "count": 0,
          "time": 0
        }
      }
    }

```

I am using metricbeat version 5.0.0-rc1 (amd64), libbeat 5.0.0-rc1.

**Comment by andrewkroh** [comment]
Is this for all drives? Or is it only for `E:\`? Is `E:\` a CD-ROM? Are there any errors/warnings in Metricbeat log? What version of Metricbeat are you running? What version of Windows are you running?

**Comment by stefanes** [comment]
Can confirm this behavior on all drives. I get the bytes (_system.diskio.write.bytes_ and _system.diskio.read.bytes_) but no times, ever.
Beats are running on several Windows Server 2008 SP1 and 2012 R2 machines.

**Comment by consulthys** [comment]
@ruflin any status on this? we have a case where `write.bytes` is always > 0 but `read.bytes` is always = 0.
Appreciate your input on this, thanks in advance

**Comment by ruflin** [comment]
@consulthys I don't think any changes happened here. Any errors in the logs? Which Metricbeat version?

**Comment by consulthys** [comment]
@ruflin no errors in the logs, `read.bytes` is simply always 0, which is weird.

**Comment by wheelq** [comment]
Same issue here

**Comment by jsoriano** [comment]
@wheelq with what version of metricbeat and windows?

**Comment by wheelq** [comment]
latest :)

**Comment by jsoriano** [comment]
We take these values directly from [`Win32_PerfFormattedData_PerfDisk_LogicalDisk` class](https://github.com/shirou/gopsutil/blob/8563278a9de317ae1ce9affdf6715ce7aee5bba9/disk/disk_windows.go#L147). I have found [some](https://social.technet.microsoft.com/Forums/en-US/34b43302-7476-4252-a16a-72a4aeb5eb32/vbscript-average-seconds-per-readwrite-returns-0) [reports](https://stackoverflow.com/questions/13905021/c-sharp-using-wmi-to-query-logicaldisk-information) of people with the same problem, zero values when querying this class. We'd need to investigate it further to see if we can find some workaround.

**Comment by wheelq** [comment]
Ok. What would you like me to provide you in order to investigate

**Comment by bebeo92** [comment]
![image](https://user-images.githubusercontent.com/9253836/55214901-91d0e000-522a-11e9-9022-60da3a6863ec.png)
I also facing this issue, currently I using metricbeat latest 6 version with ES 5.6

**Comment by bebeo92** [comment]
@andrewkroh Is there any progress, this bug seem to be report so longggggggggggggggggggggggggggggggggggggggggggggggg

**Comment by narph** [comment]
@bebeo92, I suspect you might be hitting the file system cache in this case (https://docs.microsoft.com/en-us/windows/desktop/fileio/file-caching). 
To rule this out (as I have encountered the same situation while reproducing), I suggest running any benchmark/performance monitoring tool (ex CrystalDiskMark) which will read/write directly on disk while you are collecting these metrics.
Keen to hear if the read/write values have increased and any details on your environment are more than welcome (os, type of disks, etc.)

**Comment by narph** [comment]
Replaced the current WMI query to get the system/diskio metrics for Windows
(SELECT * FROM Win32_PerfFormattedData_PerfDisk_LogicalDisk)
with DeviceIOControl Win32 API method using IOCTL_DISK_PERFORMANCE control code.
PR https://github.com/elastic/beats/pull/11635
Should reflect the `raw `instead of the  `precalculated `performance data from the counters that monitor logical partitions of a hard or fixed disk drive.

**Comment by bebeo92** [comment]
@andrewkroh sorry for late reply. I'm busy with other works
Currently I have 3 machine
1 have 16 core 32gb ram 1 ssd for os , 1 hdd
1 have 16 core 8gb ram 1 ssd for os
1 have 4 core 8gb ram 1 ssd for os , 1 hdd

All running on win 10

**Comment by bebeo92** [comment]
I saw there is a bug fix for it
One thing I forget to mention currently I using ES 5.x. I will try to test new package if it compatible with ES 5.x
