### ISSUE TITLE
[Heartbeat] Run Once mode

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#28437]
Heartbeat could use a mode in which it starts, runs each monitor exactly once, then exits. 

This was mostly accomplished in https://github.com/elastic/beats/pull/25972
But now I'm thinking it would be better to just put all the monitors in `heartbeat.monitors` and add a new `heartbeat.run_once: true` boolean that just changes the way `heartbeat.monitors` is handled instead.

This is experimental.

**Comment by shahzad31** [comment]
post FF testing

Works flawlessly , step to test

1. Build heartbeat locally
2. Turn the flag `heartbeat.run_once: true` on
3. Run an example monitor
4. Start heartbeat, it shut down after only one run
5. Tried it couple times,
6. worked each time
7. Verified the data within uptime plugin
8. 3 pings present for 3 runs
