### ISSUE TITLE
EREG in input to apply in tags value 

### ISSUE THREAD

**Issue by mcortinas** [elastic/beats#2844]
Hi,

 I'm starting working with filebeat and I want add tag with the value of regular expression in path 
```
filebeat.prospectors:
- paths:
    - /mnt/ssd/(.*).log --> EREG to obtain the application name 
  tags: [$app]   --> tagging with the application name
 ....
```
Could I do this? Apologies for my english, I tried to explain me as well as I can.

I think this feature could be expand CPU resources but i think simplifies the redeploy filebeat docker

Best,
Marc

**Comment by ruflin** [comment]
This is currently not possible. You can use Environment variables but this is probably not helpful in the above case. Please use https://discuss.elastic.co/c/beats/filebeat for questions as we want to keep issues only for confirmed bugs. Closing this issue.

**Comment by mcortinas** [comment]
Sorry @ruflin i'm newbie with ES, I opened a discussion https://discuss.elastic.co/t/ereg-in-input-to-apply-in-tags-value/65328
