### ISSUE TITLE
Elastic Agent not bundling ARM/aarch64 Endpoint

### ISSUE THREAD

**Issue by dwhyrock** [elastic/beats#28442]
The Endpoint team recently added an ARM/aarch64 version of the Endpoint for the `7.16.0` release.  It is being picked up in the Release Manager jobs, but it is not currently being bundled with the Elastic Agent.  

The Beats/Elastic Agent logic in the Release Manager should be updated to bundle the Endpoint Linux ARM/aarch64 package with Agent.

It's worth noting that the Endpoint file uses `aarch64` as the arch string, but some beats use `arm64`. I'm not sure if some of the logic will need updating in the Release Manager logic for Agent or not.

Related issue: https://github.com/elastic/beats/issues/27197

For confirmed bugs, please report:
- Version: `7.16.0`
- Operating System: Linux
- Discuss Forum URL:
- Steps to Reproduce: 

cc @ferullo

**Comment by dwhyrock** [comment]
This was sorted out with the above linked issues.  Closing.

**Comment by michalpristas** [comment]
with changes in infra in place, endpoint present in arm packages verified

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have attempted to reinstall endpoint on latest 7.16.0 Snapshot and found it almost **working fine**.
We installed linux-arm64.tar agent on AWS Ubuntu ARM64 and linux-arm64.rpm agent on AWS Centos8-ARM64. 

We added endpoint security integration and both the agents were visible under Endpoints tab.
- Endpoint Security- Logs were generated under agent logs tab.
- Endpoint Security- data was generated under Data Streams tab.
- Error logs were generated for Centos 8 .rpm, for which issue is reported at https://github.com/elastic/endpoint-dev/issues/10135
- No issues were observed on Agent or endpoint after reboot.

**Build details:**
Build: 45910
Commit: af229de1a1dfbe3a65089c75e178351c9d49e68d
Artifacts:
https://snapshots.elastic.co/7.16.0-df026734/downloads/beats/elastic-agent/elastic-agent-7.16.0-SNAPSHOT-aarch64.rpm
https://snapshots.elastic.co/7.16.0-df026734/downloads/beats/elastic-agent/elastic-agent-7.16.0-SNAPSHOT-linux-arm64.tar.gz

Please let us know if anything else is required from our end.
Thanks

**Comment by EricDavisX** [comment]
If the issue noted above is the only thing found then we are in great shape, let's call it done.  Thanks!
