### ISSUE TITLE
[Elastic-Agent]  system.hostfs option doesn't seem to work

### ISSUE THREAD

**Issue by DaveSys911** [elastic/beats#28459]
Overview:

Elastic-agent v 7.15 doesnt pass "system.hostfs" configuration option to the metricbeat process, resulting in metricbeat's system.process module not parsing /hostfs/proc directory.

Metricbeat standalone v 7.15 behaves as expected when supplied with the flag command.

How to replicate:

Deploy fleet managed or standalone elastic-agent on top of kind k8s,with system integration enabled, specify /hostfs/proc in the integration settings, and check for process data arriving.

**Comment by fearful-symmetry** [comment]
Okay, so, I'm still not sure how this bug got here, but I have a somewhat awkward fix. Should have a PR today or tomorrow.
