### ISSUE TITLE
Add support for SLES 11/12 and newer versions to Elastic Agent

### ISSUE THREAD

**Issue by crisdarocha** [elastic/beats#28467]
**Describe the enhancement:**
Add support to SLES 11/12 and newer versions to Elastic Agent

**Describe a specific use case for the enhancement or feature:**
SLES (Suse) 12 is supported by the Stack components, including the Beats, but not by Elastic Agent. This homogenizes the environments users can deploy and facilitate/increase adoption.

**Comment by jlind23** [comment]
Hey there - Following what is indicated in our support matrix: https://www.elastic.co/support/matrix
Elastic Agent 7.16 supports SLES15, could we close this issue then?

**Comment by crisdarocha** [comment]
I would say this is solved.
