### ISSUE TITLE
Remove journalbeat

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#28476]
After #27351 the `journald` input is available in filebeat, so we no longer need journalbeat.

- [X] Remove journalbeat from the packaging. https://github.com/elastic/infra/pull/32395
- [x] Remove the code https://github.com/elastic/beats/pull/29131
- [x] Remove other references. https://github.com/elastic/infra/issues/33342

Changes in documentation will be taken care of in https://github.com/elastic/observability-docs/issues/1173

**NOTE:** This cannot be implemented until journalbeat has been removed from the release manager and the CI pipeline.

**Comment by jlind23** [comment]
@mukeshelastic as discussed, could you at least remove it from the download page for 7.16?

**Comment by kvch** [comment]
@jlind23 It is already removed: https://github.com/elastic/infra/pull/32395

**Comment by kvch** [comment]
I would like to keep the issues in beats about Journalbeat for a while, so we can see if these issues impact journald input or not.

**Comment by nimarezainia** [comment]
> @jlind23 It is already removed: [elastic/infra#32395](https://github.com/elastic/infra/pull/32395)

i opened https://github.com/elastic/infra/issues/33342 to remove it from the download page>

**Comment by jlind23** [comment]
@nimarezainia @andresrc closing as all tasks have been done.
