### ISSUE TITLE
[Agent][MAC-12]: Lower version 7.14.2 Agent remains Unhealthy when installed with Endpoint Security.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#28494]
**Kibana version:**  7.15.1 Kibana Cloud Production environment

**Host OS and Browser version:** MAC Monterey 12, All

**Build details:**
```
Build: 44185
Commit: c1aa1ef8dc38b511ce4a647fe92ca0348aadd834
Artifact Link: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.14.2-darwin-x86_64.tar.gz
```

**Preconditions:**
1. 7.15.1 Kibana Cloud Production environment should be available.
2. Sip should be enabled for MAC agent.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Install 7.14.2 agent with Default policy having System and Endpoint Security.
3. Observe agent is install Healthy however goes to `Unhealthy` state after some time.

**Debug level Logs:**
[logs.zip](https://github.com/elastic/beats/files/7363528/logs.zip)
[endpoint-000000.log](https://github.com/elastic/beats/files/7363529/endpoint-000000.log)

**Expected Result:**
Lower version 7.14.2 Agent installed on MAC Monterey should not go to `Unhealthy` state when installed with Endpoint Security.

**Screenshots:**
![4](https://user-images.githubusercontent.com/77374876/137707015-0dddd142-15cf-4e04-90f7-ab762a6946c7.JPG)

**Endpoint failures:**
![1](https://user-images.githubusercontent.com/77374876/137707029-a28afd81-d80e-453c-8f49-a25da139f0a4.JPG)
![2](https://user-images.githubusercontent.com/77374876/137707034-dd681533-2e9d-4aac-8e1d-2006a75cf1e4.JPG)
![3](https://user-images.githubusercontent.com/77374876/137707035-b0e2af06-f954-41ff-b788-780161c7124f.JPG)

**Related ticket:**
https://github.com/elastic/security-team/issues/1728

**Note:**
- Agent gets back `Healthy` after reboot for sometime, however gets `Unhealthy` again.
- This issue was not observed when same version 7.15.1 agent was installed.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
>did you enable all of the disk access and such in the Mac Preferences settings? You didn't mention and I believe it is still required on new macOS 12 (I hadn't hear it wasn't).

Sorry we missed to add this information. Yes, these settings were enabled already. We installed 7.15.1 agent too, on 7.15.1 Kibana with Endpoint Security and it installed without any failure in Endpoint policy.
![image](https://user-images.githubusercontent.com/77374876/137849882-13ade77e-4cca-4a6e-9012-205d746a9845.png)

Further we have validated several times to ensure if it is not a user-error, but even on reinstalling 7.14.2 agent after 7.15.1(installed with no errors) this issue was reproducible.

JFI, we attempted to install lower version 7.14.2 MAC agent on Bigsur 11 and we observed no issues. Agent also upgraded successfully to 7.15.1.

**This issue is specific to MAC Monterey-12.**
@ferullo 
Could you please look into the same?

Thanks

**Comment by ferullo** [comment]
>  Lower version 7.14.2 Agent installed on MAC Monterey should not go to Unhealthy state when installed with Endpoint Security.

> This issue is specific to MAC Monterey-12.

As far as I can tell, this issue should be closed. 7.14 Endpoint does not support macOS 12 (Monterey). Only the upcoming 7.16.0 will support macOS 12, though provisional testing of 7.15 by @muskangulati-qasource has found that 7.15.0 does work on macOS 12 as well.

I'm hesitant to close this in case I misunderstand the issue. @EricDavisX can you close it if you agree.
