### ISSUE TITLE
[Heartbeat] Edited Synthetics Integration policies sometimes create duplicate monitor errors

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/beats#28518]
For confirmed bugs, please report:
- Version: Elastic Agent 8.0.0, Heartbeat 8.0.0
- Operating System: MacOS
- Discuss Forum URL:
- Steps to Reproduce: This bug is intermittent. To attempt to recreate, start the Elastic stack with `elastic-package stack up --version 8.0.0-SNAPSHOT -v`. Log in to Kibana at `localhost:5601`. Create an Elastic Synthetics policy, and wait for Uptime data to be indexed by heartbeat. Return to Fleet and edit the policy. Occasionally, editing the policy will create the following error in elastic agent's heartbeat logs, and data will stop being indexed.
```
13:43:14.904
elastic_agent.heartbeat
[elastic_agent.heartbeat][error] Error creating runner from config: monitor ID 90639f1a-094a-45cb-9fdc-62982ee67e82 is configured for multiple monitors! IDs must be unique values.
13:43:14.904
elastic_agent.heartbeat
[elastic_agent.heartbeat][error] 1 error: Error creating runner from config: monitor ID 90639f1a-094a-45cb-9fdc-62982ee67e82 is configured for multiple monitors! IDs must be unique values.
```

**Comment by paulb-elastic** [comment]
This will be targetting 7.16.1, not 7.16.0

**Comment by andrewvc** [comment]
This has been fixed in https://github.com/elastic/beats/pull/29041
