### ISSUE TITLE
Metricbeat logstash module payload size

### ISSUE THREAD

**Issue by admlko** [elastic/beats#28569]
**Describe the enhancement:**
My initial issue is that I have to use UDP to transmit all the data from Logstash to other Logstashes. But when I use Metricbeat Logstash module, the payload is so big it does not fit into UDP packet:
`Failed to send event, message size of 67374 too long {:error=>"#<Errno::EMSGSIZE: Message too long - No message available>", :backtrace=>["org/jruby/ext/socket/RubyUDPSocket.java:458:in 'send'" ...`

The packet size is always exactly the same: 67374 no matter if I select only node or node_stats metricset.

**Describe a specific use case for the enhancement or feature:**

It would be nice to be able to select to send only certain information about the status of the node, rather than sending everything.
Let's say I'm only interested about node tab: CPU usage, load average, JVM heap usage, events ingested, config reloads and version number.
I don't care about pipelines.

I thought this could be done selecting only node as a metricset, but for some reason it doesn't change the payload size.

**Comment by andresrc** [comment]
Payload size might not be related to event size and events might be batched for bette throughput. Please open an issue in the logstash repository or a topic in its discuss forum to discuss the limitations of the UDP output.

Thanks
