### ISSUE TITLE
[Agent] Elastic-Agent-Packaging-Linux is failed (there for e2e-testing pr support) which blocks merges - seems to be a Heartbeat container build problem

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#28570]
This is from a dev via slack:
PR 'tests' are failing...
"The E2E agent linux tests are super flaky at the moment and preventing us from making imports. Is that something currently being looked at?"
citing this PR as example:
https://github.com/elastic/beats/pull/28517

Manu helped bisect the pr failures and seemed to point towards the Heartbeat container not being available, so maybe a build problem there.

Victor noted that the e2e-testing support had been turned on (requiring that packaging) somewhat recently. PM me for slack convo link or team thread on the packaging change

image from slack:
![image (5)](https://user-images.githubusercontent.com/12970373/138100529-215acb2f-aac4-4401-b418-b4ee279208ad.png)

**Comment by jlind23** [comment]
@andrewvc seems that this is on Synthetics side.

**Comment by mdelapenya** [comment]
I'm checking that the only logs we are storing are kind logs, but not the cluster logs. In my local execution, meanwhile we provide the test framework to extract kind's logs (using `export logs` command), I was able to extract heartbeat pod's logs:

>2021-10-20T15:46:33.582605252Z stderr F Exiting: error loading config file: open /etc/heartbeat.yml: permission denied
