### ISSUE TITLE
[Filebeat] Service cannot start when using custom index names after upgrade to 7.15

### ISSUE THREAD

**Issue by drizzthacker** [elastic/beats#28571]
- Version:  7.15.0
- Operating System:  Debian 10
- Steps to Reproduce: Cluster, Kibana and Filebeat on 7.14, then upgrade all to 7.15. Then, the service for filebeat refuses to start only when using custom index names saying this: 

"2021-10-20T14:19:21.077+0200    ERROR   instance/beat.go:989    Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing directory /usr/share/filebeat/kibana: failed to import Kibana index pattern: 1 error: error setting index 'customname-*' in index pattern: empty index pattern"

On 7.14 I had 2 working instances, one with default index name and one with custom index name like this:

"filebeat-customname-2021.10"

And both were working, after the update, the instances are only working when I use the default filebeat index name

Things I've tried to solve:
-Delete all filebeat indices, templates, index patterns and dashboards
-Manually create the index pattern and index before starting Filebeat.

Here are the log and the config file:
[filebeat.yml.txt](https://github.com/elastic/beats/files/7381474/filebeat.yml.txt)
[filebeat.log.txt](https://github.com/elastic/beats/files/7381481/filebeat.log.txt)

Thanks

Update: If I roll back a filebeat instance to 7.14.2 maintaining kibana and elasticsearch on 7.15, it works nice

**Comment by kvch** [comment]
Have you tried the latest release of Filebeat 7.15? We added fixes to dashboards and custom index names.

**Comment by drizzthacker** [comment]
Hi @kvch Just updated the cluster, kibana and filebeat to 7.15.2 and still the same problem

**Comment by kvch** [comment]
Thanks. I have found the issue, the Beat tries to find a previously removed key in the dashboard JSON.

**Comment by drizzthacker** [comment]
Thanks! Is there a way to cheat it in the meantime?
