### ISSUE TITLE
Incorect memory report on RedHat 6.5

### ISSUE THREAD

**Issue by molsza** [elastic/beats#28604]
It seems that on RedHat 6.5 metricbeat is reporting a memory incorrectly. It is treating total memory as used memory.

Metricbeat report
![metricbeat](https://user-images.githubusercontent.com/41799777/138417778-d4c24ea9-533d-4077-85a9-359ae61ab57d.jpg)

Memory details of server (not at the same time, but quite close):
![free](https://user-images.githubusercontent.com/41799777/138417979-695908d5-981b-47ef-a028-b842e1c5b4ee.jpg)

This probably causes a strange visualization like this:
![metric_view](https://user-images.githubusercontent.com/41799777/138419921-0e481adf-5546-4c32-a310-c3f55a8c06a9.jpg)

from it looks like I have 30GB memory more than in reality and I have used 99% of it, while in real I still have 30% free.

**Comment by molsza** [comment]
@fearful-symmetry is this fix in any released version? If not, can you point me to night build build rpm with the fix?

**Comment by fearful-symmetry** [comment]
@molsza the fix should be in 7.15.2, which will be released on the 10th.

**Comment by fearful-symmetry** [comment]
Everything should be merged, closing.
