### ISSUE TITLE
Dockerhub Images *PLEASE*

### ISSUE THREAD

**Issue by qrpike** [elastic/beats#2866]
Amazing tool, but why isn't there a dockerhub image? I dont want to have to build my own images that I must keep up to date...

**Comment by tsg** [comment]
We're planning to have official docker images soon.

**Comment by ruflin** [comment]
Related to https://github.com/elastic/beats/issues/2300

**Comment by exekias** [comment]
Closing, as we now have official docker images in Dockerhub: https://hub.docker.com/publishers/elastic
