### ISSUE TITLE
[metricbeat] collect and index SLM stats metrics

### ISSUE THREAD

**Issue by dakrone** [elastic/beats#28684]
**Describe the enhancement:**

It would be very useful if metricbeat could be extended to collect SLM statistics. These statistics are available at `GET /_slm/stats` and look somewhat like the following (with the `human` flag):

```json
{
    "retention_runs": 0,
    "retention_failed": 0,
    "retention_timed_out": 0,
    "retention_deletion_time": "0s",
    "retention_deletion_time_millis": 0,
    "total_snapshots_taken": 1,
    "total_snapshots_failed": 0,
    "total_snapshots_deleted": 0,
    "total_snapshot_deletion_failures": 0,
    "policy_stats": [
        {
            "policy": "daily-snapshots",
            "snapshots_taken": 1,
            "snapshots_failed": 0,
            "snapshots_deleted": 0,
            "snapshot_deletion_failures": 0
        }
    ]
}
```

**Describe a specific use case for the enhancement or feature:**

When running ES as a service, it is useful to be able to track the successes and failures for SLM policies so that we can determine whether SLM is executing policies reasonably successfully, or whether there are problems creating snapshots.

**Comment by mduarte** [comment]
Is there any chance that this would get prioritized any time soon?

This would be very valuable in Cloud to be able to define SLIs/SLOs around the success rate of snapshots.
