### ISSUE TITLE
[heartbeat] Stop using `cap_net_raw` for docker image

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#28685]
The heartbeat docker image will not run in docker/k8s if all capabilities are dropped (if you use `--cap-drop` with docker you'll see this). We stopped doing this for agent in https://github.com/elastic/beats/pull/28504 and should probably do the same for heartbeat here since it's so confusing in terms of behavior.

Alternatively, if we can find a way to fail gracefully that would be fine. Ideally if no capabilities were set the binary would just run without those capabilities instead of failing.

**Comment by paulb-elastic** [comment]
Pushing to 8.0

**Comment by andrewvc** [comment]
Closing in favor of https://github.com/elastic/beats/issues/27651 and https://github.com/elastic/beats/pull/30200
