### ISSUE TITLE
override beat.hostname and/or supply beat.ipaddress

### ISSUE THREAD

**Issue by tronicum** [elastic/beats#2869]
for HA reasons I have a cluster where the cluster members share a hostname. Those get streamed with a beat.hostname 'our.cluster.name' value. 
To solve that I would like to 

a) override the hostname within the filebeat.yml. e.g. hostname: 'membera.cluster.name' (or ${REALHOSTNAME:membera.cluster.name}
b) set a devicename which IP should set within beat.ipaddress e.g. (beat.)ipaddress=${MYINTERFACE_VARIABLE:eth0}
(is https://www.elastic.co/guide/en/beats/filebeat/1.2/using-environ-vars.html up to date?)

That way I can distinguish the logstream even if they use the same hostname. 

(I know the option C is to set a custom flied ipaddress=1.2.3.4 within filebeat.yaml but within a dynamic/virtualized context I would have to change filebeat.yml each time it might change). 

It would be enough to check such values on startup or on reload/HUP.

**Comment by tsg** [comment]
I think easiest is to set the `beat.name` to a custom value and rely on that. By default `beat.name` is set to the same value as `beat.hostname`, but you can change it via the configuration file. In 5.0 that would be something like `name: ${REALHOSTNAME}`. In 1.x, the option is named `shipper.name`.

Would this work for you?

**Comment by tronicum** [comment]
I added 'name: ''membera.cluster.name-192.168.x.y' to filebeat.yml (and upgraded to 5.x). that worked as described. thanks!

**Comment by xoclutch** [comment]
I'm running Filebeats on FreeBSD and the hostname for the OS returns the FQDN, instead of just the hostname like in linux. 

Is there no way to fix this?  It's a bit anonying.
