### ISSUE TITLE
packetbeat panic - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by StianOvrevage** [elastic/beats#2870]
Version: packetbeat-5.0.0-rc1-windows-x86_64
OS: Windows 10 ver 1511

Getting a panic and crash after running packetbeat for a while (forth time now it crashes here).

Error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x170 pc=0x4ac841]

goroutine 4048 [running]:
panic(0xa702e0, 0xc04200c0b0)
        /usr/local/go/src/runtime/panic.go:500 +0x1af
github.com/elastic/beats/packetbeat/protos/memcache.(*transaction).Event(0x0, 0xc043eb7620, 0xc043eb7620, 0x0)
        /go/src/github.com/elastic/beats/packetbeat/protos/memcache/memcache.go:364 +0x41
github.com/elastic/beats/packetbeat/protos/memcache.(*Memcache).onTransaction(0xc04207eb00, 0x0)
        /go/src/github.com/elastic/beats/packetbeat/protos/memcache/memcache.go:183 +0x70
github.com/elastic/beats/packetbeat/protos/memcache.(*Memcache).finishTransaction(0xc04207eb00, 0x0, 0x0, 0x0)
        /go/src/github.com/elastic/beats/packetbeat/protos/memcache/memcache.go:177 +0x45
github.com/elastic/beats/packetbeat/protos/memcache.(*Memcache).onUdpTrans(0xc04207eb00, 0xc0444e32c0, 0x0, 0x0)
        /go/src/github.com/elastic/beats/packetbeat/protos/memcache/plugin_udp.go:198 +0x96
github.com/elastic/beats/packetbeat/protos/memcache.(*Memcache).ParseUdp.func1()
        /go/src/github.com/elastic/beats/packetbeat/protos/memcache/plugin_udp.go:132 +0x8d
created by time.goFunc
        /usr/local/go/src/time/sleep.go:154 +0x4b
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x170 pc=0x4ac841]

goroutine 4049 [running]:
panic(0xa702e0, 0xc04200c0b0)
        /usr/local/go/src/runtime/panic.go:500 +0x1af
github.com/elastic/beats/packetbeat/protos/memcache.(*transaction).Event(0x0, 0xc0448ad2c0, 0xc0448ad2c0, 0x0)
        /go/src/github.com/elastic/beats/packetbeat/protos/memcache/memcache.go:364 +0x41
github.com/elastic/beats/packetbeat/protos/memcache.(*Memcache).onTransaction(0xc04207eb00, 0x0)
        /go/src/github.com/elastic/beats/packetbeat/protos/memcache/memcache.go:183 +0x70
github.com/elastic/beats/packetbeat/protos/memcache.(*Memcache).finishTransaction(0xc04207eb00, 0x0, 0x0, 0x0)
        /go/src/github.com/elastic/beats/packetbeat/protos/memcache/memcache.go:177 +0x45
github.com/elastic/beats/packetbeat/protos/memcache.(*Memcache).onUdpTrans(0xc04207eb00, 0xc0444e3380, 0x0, 0x0)
        /go/src/github.com/elastic/beats/packetbeat/protos/memcache/plugin_udp.go:198 +0x96
github.com/elastic/beats/packetbeat/protos/memcache.(*Memcache).ParseUdp.func1()
        /go/src/github.com/elastic/beats/packetbeat/protos/memcache/plugin_udp.go:132 +0x8d
created by time.goFunc
        /usr/local/go/src/time/sleep.go:154 +0x4
```

Running with
  `packetbeat.exe -c packetbeat.yml -v -e`

Nothing fancy in the config, using the defaults and just specifying ES host and interface ID.

**Comment by tsg** [comment]
Pinging @urso.

**Comment by TeroPihlaja** [comment]
I have a very similar trace from version 7.3.0. I wonder if this is the same issue

Aug 14 15:51:30 vpngw-... packetbeat[16764]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 14 15:51:30 vpngw-... packetbeat[16764]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x220 pc=0x1082ee7]
Aug 14 15:51:30 vpngw-... packetbeat[16764]: goroutine 57321 [running]:
Aug 14 15:51:30 vpngw-... packetbeat[16764]: github.com/elastic/beats/packetbeat/protos/memcache.(*transaction).Event(0x0, 0xc00201aed0, 0x0, 0x0)
Aug 14 15:51:30 vpngw-... packetbeat[16764]: #011/go/src/github.com/elastic/beats/packetbeat/protos/memcache/memcache.go:382 +0x37
Aug 14 15:51:30 vpngw-... packetbeat[16764]: github.com/elastic/beats/packetbeat/protos/memcache.(*memcache).onTransaction(0xc001155500, 0x0)
Aug 14 15:51:30 vpngw-... packetbeat[16764]: #011/go/src/github.com/elastic/beats/packetbeat/protos/memcache/memcache.go:202 +0x6f
Aug 14 15:51:30 vpngw-... packetbeat[16764]: github.com/elastic/beats/packetbeat/protos/memcache.(*memcache).finishTransaction(...)
Aug 14 15:51:30 vpngw-... packetbeat[16764]: #011/go/src/github.com/elastic/beats/packetbeat/protos/memcache/memcache.go:194
Aug 14 15:51:30 vpngw-... packetbeat[16764]: github.com/elastic/beats/packetbeat/protos/memcache.(*memcache).onUDPTrans(0xc001155500, 0xc005317e80, 0x0, 0x0)
Aug 14 15:51:30 vpngw-... packetbeat[16764]: #011/go/src/github.com/elastic/beats/packetbeat/protos/memcache/plugin_udp.go:214 +0x8f
Aug 14 15:51:30 vpngw-.. packetbeat[16764]: github.com/elastic/beats/packetbeat/protos/memcache.(*memcache).ParseUDP.func1()
Aug 14 15:51:30 vpngw-... packetbeat[16764]: #011/go/src/github.com/elastic/beats/packetbeat/protos/memcache/plugin_udp.go:149 +0x7c
Aug 14 15:51:30 vpngw-... packetbeat[16764]: created by time.goFunc
Aug 14 15:51:30 vpngw-... packetbeat[16764]: #011/usr/local/go/src/time/sleep.go:169 +0x44
Aug 14 15:51:30 vpngw-... systemd[1]: packetbeat.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by urso** [comment]
@TeroPihlaja Thank you for following up. Just noticed there was no progress for years :( Some sample traffic would be nice. Is there a chance to get us some sample pcap which makes packetbeat crash for testing?

**Comment by TeroPihlaja** [comment]
Possibly. I would first have to take a look and see how often this happens in our environment.

Can you help me set up the capture filter by narrowing down what traffic is handled by this code?

I assume UDP traffic but is there more information to limit the amount of data being stored. Is only traffic to memcache port (in config file) handled by this code?

**Comment by urso** [comment]
Yes, only UDP + memcache port is handled by it. The error happens after correlating a response to a request. So I can't tell for sure what kind of message we'd need filter for.

**Comment by urso** [comment]
Have you tried running packetbeat in debug mode? I'd interested if we have any of these messages in the logs:
- `parsing memcache udp header failed`
- `new udp datagram requestId=` (should be the last packet before the stack trace)
- `udp connection: `
- `udp transaction (id=.*):`
- `number of datagram mismatches in stream`
- `failed to parse memcached(UDP) message: `
- `error processing memcache message: `
- `transaction timeout -> forward`

Checking the code the only reason for a nil pointer could be unfinished request/response parsing. Maybe triggered by packetloss (which could also be due to packets being send faster then packetbeat can process). Having requests and responses taking multiple packages and removing one packet from the pcap for each might trigger this problem.

**Comment by TeroPihlaja** [comment]
Hello,

I have not tried running in debug mode because this is a router with quite a lot of traffic.

I believe the error is caused by one of these packets (which are not memcache packets but happen to use the same port):

[eth1.cap.zip](https://github.com/elastic/beats/files/3502565/eth1.cap.zip)
