### ISSUE TITLE
incorrect default value of agent.download.timeout in Elastic Agent reference yaml

### ISSUE THREAD

**Issue by gbanasiak** [elastic/beats#28788]
As of 7.15.1 the default value of `agent.download.timeout` is 120s ([code](https://github.com/elastic/beats/blob/v7.15.1/x-pack/elastic-agent/pkg/artifact/config.go#L47-L48)), not 30s as shown in the [reference YAML](https://github.com/elastic/beats/blob/v7.15.1/x-pack/elastic-agent/_meta/elastic-agent.yml#L65-L66).
Please update the YAML.

**Comment by michel-laterman** [comment]
this is a simple fix, should we also backport to `7.15` (is there another patch planned)?

**Comment by jlind23** [comment]
@michel-laterman let's backport it to 7.15, merge you PR and close this issue.
