### ISSUE TITLE
Visualizations on the Kubernetes overview dashboard override index but shouldn't

### ISSUE THREAD

**Issue by jamiesmith** [elastic/beats#28792]
(Note that I got the data from agent, but probably the same with metricbeat)

There are two visualizations on the `[Metrics Kubernetes] Overview` dashboard that are overriding the index pattern but shouldn't be (they have "yes" checked, but don't specify it). This results in broken visualizations:
<img width="1630" alt="image" src="https://user-images.githubusercontent.com/220994/140130562-7b78f1b0-cb40-4971-8092-9781124b676a.png">
![image](https://user-images.githubusercontent.com/220994/140123050-8807ce1e-26fb-4ecf-b083-83bc14c0eabd.png)
(note that the `logs-*` in the picture isn't _actually_ the default-- there isn't one. That's just what it picked.

the visualizations in question are:
- Desired pods [Metrics Kubernetes]
- Unavailable pods [Metrics Kubernetes]

The radio button for override is set, but if the default index pattern isn't `metrics-*` (or, as was in my case, isn't set at all) it breaks. It should probably just be set to "no" for the override. Here's a before and after screenshot:
![image](https://user-images.githubusercontent.com/220994/140123854-e05b97e5-2b52-4189-bc6a-e151221e1bca.png)
![image](https://user-images.githubusercontent.com/220994/140123985-31ea23cd-06cb-43da-a27b-b2feb806c0cc.png)

For confirmed bugs, please report:
- Version: 7.15.1 & 7.16
- Operating System: running in kubernetes
- Discuss Forum URL: N/A, slack
- Steps to Reproduce: 
  - load kubernetes data (I did so via a policy with k8s integration and Elastic Agent / Fleet)
  - make sure that the default index pattern _isn't_ metrics
  - go to the Kubernetes overview dashboard
  - You should see the errors as above

**Comment by gabrielfsousa** [comment]
where i can get the [Metrics Kubernetes] Overview - dashboard. i dont have it

**Comment by gabrielfsousa** [comment]
@jamiesmith im using Agent & Fleet, and mine is all empty. is there a way to install it ?

![image](https://user-images.githubusercontent.com/722744/155987669-6aa5bc00-8133-4f87-8487-6eeed01ca8c7.png)

**Comment by gabrielfsousa** [comment]
kibana and everything 7.16.2

**Comment by jamiesmith** [comment]
It's strange because it's showing the _counts_ of them for you, but not the items (and it actually looks like it's got the right number of rows for them in the tables). 

Do any of the visualizations show up in the actual Kibana visualize library pane? 

I'd suggest opening a thread on the [Observability channel](https://discuss.elastic.co/c/observability/82) on the forums (or new issue here)- unfortunately, this is beyond me...

**Comment by gabrielfsousa** [comment]
yes, but no METRICS KUBERNETES

![image](https://user-images.githubusercontent.com/722744/155990094-c257f051-b419-4a78-8408-07aec839c9ed.png)
