### ISSUE TITLE
libbeat Kafka output not respecting cipher suite SSL setting

### ISSUE THREAD

**Issue by faec** [elastic/beats#28791]
- Version: Filebeat 7.14.1
- Operating System: Windows

When the Kafka configuration specifies an explicit cipher suite (`output.kafka.ssl.cipher_suites: ["RSA-AES-128-CBC-SHA"]`) it is observed in packet analysis to still send a TLS 1.2 client handshake allowing 3 additional cipher suites (`TLS_AES_128_GCM_SHA256`, `TLS_CHACHA20_POLY1305_SHA256`, and `TLS_AES_256_GCM_SHA384`).

**Comment by faec** [comment]
This is actually much broader than the Kafka output, and hits anything using Go's standard library for TLS support. What's happening is: cipher selection is not supported in TLS 1.3. Therefore, when TLS 1.3 is enabled in the client (which is true in Beats by default), the standard library automatically adds the default TLS 1.3 cipher suites to any cipher suite setting, even if the server itself only supports TLS 1.2.

The only way to definitely exclude ciphers with the current Go standard library is to set the desired cipher suite _and_ disable TLS 1.3, e.g. adding `ssl.supported_protocols: [TLSv1.2]` "fixes" the problem in Beats.

We might wish the logic was otherwise, but it seems like right now we have to more clearly document that the `cipher_suites` parameter only applies if TLS 1.3 is disabled.

**Comment by jlind23** [comment]
@faec could you then just make a document update as a first step?
