### ISSUE TITLE
beat name in YAML should be set actual name

### ISSUE THREAD

**Issue by YaSuenag** [elastic/beats#2880]
I've migrated [HSBeat](https://github.com/YaSuenag/hsbeat) to Metricbeat.

I set beat name in `make setup` , however it did not affect each config (YAML) files.
YAML has been overwritten as Metricbeat. I think `make setup` should set "real" beat name to all YAMLs.
- Version:  5 GA
- Operating System: Fedora 24
- Steps to Reproduce: 
  run `make setup`

**Comment by ruflin** [comment]
To make this possible, the following things must be changed:

* Metricbeat must be replaced by generation scripts with beatname
  * Config files: `metricbeat/etc/beat.yml` and `metricbeat/etc/beat.full.yml`
  * Module docs
  * Metricset docs 
* It must be checked if config loading with a different namespace already works (it should as it takes automatically the namespace of the beat itself) 

Some more things probably pop up when implementing it.

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/beats/pull/2903 was merged.
