### ISSUE TITLE
Cannot get packet when use php to communicate with mysql!

### ISSUE THREAD

**Issue by ximply** [elastic/beats#2883]
Use php mysql extension to communicate with mysql, do these packets cannot be get? 
I use packetbeat 5.0.0. on CentOS 6.4 X64.

**Comment by ruflin** [comment]
Hi @ximply We try to use Github for tracking issues. For questions please use discuss: https://discuss.elastic.co/c/beats/packetbeat Please also post there your configuration you are using.
