### ISSUE TITLE
Add version check for Winpcap

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#2886]
We have a scenario where `packetbeat -devices` command is returning `no devices found` on a Windows 2012 R2 64-bit server.  It turns out that winpcap installation was corrupted and we had to reinstall winpcap for the -devices command to work.

Per @tsg, there is apparently a way to verify the version of winpcap (https://www.winpcap.org/pipermail/winpcap-users/2009-March/003062.html), so it may be helpful to add this check and verify the version of winpcap.  If there is another lightweight winpcap call that will exercise some basic feature of winpcap, we can also consider adding it along with the version call just to verify if the winpcap installation is good.

**Comment by maddin2016** [comment]
Hi @ppf2, i have think about youre comment and tested something. First is the version check. Here we maybe can call `pcap.Verison()` or check for that registry key. But that doesn't help us to find out if winpcap is working correctly. So like in your case, you say that you had installed a corrupt version of winpacp. So in that case pcap should have thrown an error [here](https://github.com/elastic/beats/blob/master/packetbeat/sniffer/sniffer.go#L81). But it doens't have. So i think it's hard to find out if the installation is corrupt or just the winpcap has not started. @andrewkroh, @ruflin, what do you think.
