### ISSUE TITLE
[MAC-12 Agent]: Error logs on adding Endpoint Security integration to MAC12 agent under Logs tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#28880]
**Kibana version:**  7.16.0 BC-3 Kibana Cloud environment

**Host OS and Browser version:**  MAC, All

**Build details:**
```
Build: 45816
Commit: acaa761f4ce46680fd7cfbeba03a652c72dc786b
Artifact Link: https://staging.elastic.co/7.16.0-8dc8b6a1/downloads/beats/elastic-agent/elastic-agent-7.16.0-darwin-x86_64.tar.gz
```

**Preconditions:**
1.  7.16.0 BC-3 Kibana Cloud environment should be available.
2. MAC Agent must be installed with Policy having System integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Add Endpoint Security integration to the Default Policy.
3. Navigate to Agent>Logs tab.
4. Select `error` under Log level filter and `elastic_agent.endpoint_security` dataset filter.
4. Observe below error logs:
```
12:33:12.603
elastic_agent.endpoint_security
[elastic_agent.endpoint_security][error] Interfaces.cpp:123 Interface name too long to get MAC address; name [lo0], namelen [3], sdl_alen [0], sdl_nlen [3] (see net/if_dl.h -> sdl_data)
```
**Debug level Logs:**
[logs.zip](https://github.com/elastic/beats/files/7502772/logs.zip)
[endpoint-000000.zip](https://github.com/elastic/beats/files/7502775/endpoint-000000.zip)

**Expected Result:**
No Error logs under Logs tab should generate on adding Endpoint Security integration to MAC12  agent.

**Screenshot:**
![5](https://user-images.githubusercontent.com/77374876/140878483-bf5d9b9d-a581-4816-8313-ee507803045e.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @andresrc 

CC: @EricDavisX

**Comment by EricDavisX** [comment]
@amolnater-qasource this is an Endpoint controlled log, please open a new ticket in the endpoints-dev repo and we can close this.  It is also low/'minor impact, and fwiw this will not impact any support coming for macOS 12

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
Thanks for the feedback, we have logged this issue in `endpoints-dev` repo at link: https://github.com/elastic/endpoint-dev/issues/10135

Thanks
