### ISSUE TITLE
MongoDB password from connection string is indexed in metricset.host field and is visible

### ISSUE THREAD

**Issue by cwhenderson20** [elastic/beats#2888]
Similar to #2738. When connecting to a running instance of MongoDB, the user and password of the connection string are indexed into the metricset.host field.

However, unlike #2738, I'm not aware of another way to specify the connection string such that the user/pass is separated out. 

This prevents us from using the mongodb module as even logging the credentials of a users with minimal permissions is not acceptable.

**Comment by tsg** [comment]
Ah, good point :(. Only workaround for now is to use `drop_field` to remove the host information. Treating this as high prio.

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/beats/pull/2889 was merged.
