### ISSUE TITLE
Re-enrolled Agent went to unhealthy state on restart of agent service or on having Endpoint integration.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#28891]
*Kibana version:**  7.16 BC3 Kibana cloud-qa environment

**Browser version:** Chrome
**Host OS**: **AWS Graviton Linux 2 Kernel 5.4 ARM 64 template**

**Preconditions:**
1. 7.16 BC3 Kibana cloud-qa environment should be available.

**Build Details:**
```
BUILD 45816
COMMIT acaa761f4ce46680fd7cfbeba03a652c72dc786b
ARTIFACT: https://staging.elastic.co/7.16.0-8dc8b6a1/downloads/beats/elastic-agent/elastic-agent-7.16.0-linux-arm64.tar.gz

```
2. Arm agent should be installed using policy having below integrations:
- Endpoint, system, linux, Nginx

3. **Force unenroll and re-enroll agent.**

**Steps to reproduce:**
- Login to Kibana with admin account.
- Navigate to Agents tab.
- Notice, agent is running in healthy state.

**Scenario 1:** 
If still healthy, attempt to stop agent service and Observe, Agent went into unhealthy state.

**Scenario2:**
- Attempt to add windows integration.
- wait for few mins.

Observe, Agent went into unhealthy state.

**Screenshot:** 
![image](https://user-images.githubusercontent.com/72375798/140925806-16e95ea1-cfba-4060-b006-61a08960cf47.png)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed this ticket @EricDavisX

**Comment by jlind23** [comment]
@EricDavisX is this really a "bug" as we do not support graviton yet?

**Comment by EricDavisX** [comment]
@jlind23 yes we should consider it so.  It is a great discussion as to how we prefer to cite concerns as the team does the work on a new OS support task.  @nimarezainia and you can give ideas?  My thought is we could use private repo for bugs until it is confirmed as supported?  Any data points that come in can inform our decisions on support or not (imagine if a blocker was found).  

@dikshachauhan-qasource about this one, its critically helpful to know if other OSes with the same version behave this way or if they work (is it specific to AWS Linux in general)?  Can you cross-test or reference tests-already-done and confirm back please?

**Comment by jlind23** [comment]
@EricDavisX no no continue like this it's good, i'll add it to our backlog and fix it as soon as we want to support AWS Graviton. 👍🏼

**Comment by EricDavisX** [comment]
ok, sounds good. :) 

@dikshachauhan-qasource In re-reading I want to push this further along...  After cross-testing, can you split the 2 scenarios to separate tickets please?  the usage of Windows Integration (does it happen with other Integrations?) seems suspicious from past experience in a Linux context - and is very likely separate from an Agent (without Windows Integration) start/stop performance.  let's leave this one open for the start/stop. 

When logging the Integration centric issue be sure to post versions used of the Integrations at hand, and any cross-test info you have (like the same version of Integration/stack works on CentOS would be helpful)

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have re-attempted it with different OSs and found it that this issue is specific to AWS graviton Linux 2 machines when having endpoint security integration in agent policy.

Endpoint Security Version is 1.2.1

**Build details:**
```
BUILD 45816
COMMIT acaa761f4ce46680fd7cfbeba03a652c72dc786b
ARTIFACT: https://staging.elastic.co/7.16.0-8dc8b6a1/downloads/beats/elastic-agent/elastic-agent-7.16.0-linux-arm64.tar.gz
```

**Observation:**
This issue is reproducible on Agent re-enrollment with any policy having endpoint security in it. Further, we we attempt to start or stop agent service, it went in un-healthy state.

**Screenshots:**
![image](https://user-images.githubusercontent.com/72375798/141107837-e47e5791-b2e6-4b58-9ee4-367bdc54b79b.png)

Error logs:
![image](https://user-images.githubusercontent.com/72375798/141108004-1016a14e-542e-4f5f-a3f7-1fb329049e7b.png)

Agent status:
![image](https://user-images.githubusercontent.com/72375798/141108052-6ca57815-3432-4e09-a07c-d590a11b8a8e.png)


Logs:
[logs54kernel.zip](https://github.com/elastic/beats/files/7512625/logs54kernel.zip)
[logs510kernel.zip](https://github.com/elastic/beats/files/7512627/logs510kernel.zip)

Please let us if more is required.

Thanks
QAS

**Comment by EricDavisX** [comment]
We should pull in @ferullo to help assign/review logs and work this from Endpoint side.

**Comment by nicholasberlin** [comment]
I'm having trouble reproducing this :(

The only difference I can tell in my setup is the version of the System integration (my deployment has v1.6.2 vs v1.4.0)
<img width="1280" alt="Screen Shot 2021-11-10 at 1 25 32 PM" src="https://user-images.githubusercontent.com/56366649/141171742-36413bd9-26fa-4f27-bf46-c03bd349c874.png">

After force unenrolling (which I assume is checking the box when unenrolling), I re-executed the install command on the host.
```
$ sudo ./elastic-agent install -f  ....
```

Anyway, I will have a closer looks at the logs tomorrow, but they are agent logs and a bit foreign to me.
Can the endpoint logs be posted here?
`/opt/Elastic/Endpoint/state/log/endpoint-000000.log`

**Comment by stanek-michal** [comment]
I haven't been able to reproduce this issue either. I tried 5.4 and 5.10 AWS Graviton hosts with the agent build that is linked in this issue. Stopping the agent service causes status to switch to Offline and starting it again makes it go Healthy.
The System integration version is also different on my setup.

**Comment by dikshachauhan-qasource** [comment]
Hi @stanek-michal and @nicholasberlin 

Please re-validate it using below steps:

1. Install agent on AWS graviton kernel say 5.10 with agent policy having: system and Endpoint package.
2. Perform few actions on agent say reboot agent service.
3. Un-enroll agent.
4. Re-enroll agent under same policy.
5. observe agent is healthy.
6. Add Windows integration to agent policy.
7. Stop the agent service.
8. Restart the agent service.
9. Observe, agent went to unhealthy state.

With following error log:
```
16:02:55.657
elastic_agent
[elastic_agent][error] 2021-11-11T10:32:55Z - message: Application: endpoint-security--7.16.0[61a3d597-5f4f-4cb6-b0c7-a83ec9e19d6a]: State changed to FAILED: Missed two check-ins - type: 'ERROR' - sub_type: 'FAILED'
```

Please let us know if further info is required.

Thanks
QAS

**Comment by nicholasberlin** [comment]
Thanks for the detailed instructions.

I'm still having trouble recreating this.
Listed below is what I did. What am I missing?

>1. Install agent on AWS graviton kernel say 5.10 with agent policy having: system and Endpoint package.

Created a new agent policy with Endpoint Security v1.2.1 and System v1.6.2 and installed it on the Amazon Linux 2 running `Linux version 5.10.35-31.135.amzn2.aarch64`. And saw a healthy agent status.

> 2. Un-enroll agent.

Un-enrolled the agent from the fleet/agents page (made sure to check the force unenroll box)
After force unenrolling, I noted that elastic-agent, endpoint, and the beats were still running.

> 3. Re-enroll agent under same policy.

I re-enrolled by executing the same command used to install the agent initially with the custom policy.

> 4. observe agent is healthy.

It came back up in the fleet/agents kibana view and reported as healthy.

> 5. Add Windows integration to agent policy.

Added Windows v.1.2.2 integration to the policy, and saw the agent update to the new policy version with a healthy status.

> 6. Stop the agent service.

Ran `$ sudo systemctl stop elastic-agent.service` on the host to stop the agent service. After doing so, elastic-agent and the beats were no longer running, but elastic-endpoint *was* running. I also saw the agent's status go to `offline` in kibana.

> 7. Restart the agent service.

Ran `$ sudo systemctl start elastic-agent.service` on the host to restart the agent service.

> 8. Observe, agent went to unhealthy state.

Saw the agent return to a healthy status in kibana. The agent did not go into an unhealthy state. :(

**Comment by dikshachauhan-qasource** [comment]
Hi @nicholasberlin 

Yeah, I would like to confirm that you have missed step two written under Comment https://github.com/elastic/beats/issues/28891#issuecomment-966203941. We have have to perform few actions on agent before unenroll say Logging level change, reboot of agent services and policy change. After that we will e=un-enroll and then contu=inue with steps mentioned as by you.

Please let me know if you are still unable to reproduce, we can work together to debug then later after.

Thanks
QAS

**Comment by nicholasberlin** [comment]
@dikshachauhan-qasource and I had a zoom session, and we were unable to reproduce the bug together. Our testing today used BC5, where previous testing used early BCs. My understanding is that there may have been network issues involved over the last week.

The plan is to retest again on Monday, after the holiday (Guru Nanak Jayanti) tomorrow, with older BCs, and potentially close as fixed by the latest BC.

**Comment by dikshachauhan-qasource** [comment]
Hi @nicholasberlin cc @EricDavisX 

I have re-attempted to reproduce the Issue with BC3 to, however, was unable to reproduce today with BC5 too.

Assuming, that there may networks issues on that days when reported, we are closing this for now.

Thanks
QAS
