### ISSUE TITLE
Add APM instrumentation to Elastic Agent

### ISSUE THREAD

**Issue by simitt** [elastic/beats#28895]
**Describe the enhancement:**
Add apm instrumentation to the elastic agent. At least following configuration options should be supported:
* environment
* hosts
* secret-token | api-key

Ideally the Elastic Agent passes down apm tracing configuration to sub processes, which can ignore the configuration if they don't yet support apm.

**To be discussed**
There are no plans to support this in fleet at the moment. Therefore the agent will need to either understand environment variables or read the config from an initial config file, similar to how exposing the http monitoring endpoint can be configured. 

**Describe a specific use case for the enhancement or feature:**
Turning on APM tracing will help gain more insights into the Elastic Agent performance and errors. 

cc @elastic/apm-server @jlind23

**Comment by stuartnelson3** [comment]
For bookkeeping, add a table of the telemetry data being collected when the PR has been merged, similar to https://github.com/elastic/kibana/pull/119740#discussion_r757015951
