### ISSUE TITLE
multiple output in filebeat

### ISSUE THREAD

**Issue by rayshen3** [elastic/beats#28925]
is there planned support for multiple output in the near future?
thx

**Comment by businessbean** [comment]
The question is related to this [comment](https://github.com/elastic/beats/pull/27951#issuecomment-966557762)

**Comment by jlind23** [comment]
@nimarezainia could you jump in please?

**Comment by nimarezainia** [comment]
I believe the question is about supporting additional outputs to filebeat. The answer is No, there aren't any intention of supporting more outputs than what we currently have.

In the output section of the yaml you can add multiple supported outputs today.

**Comment by Marchelune** [comment]
Hello there / hi @nimarezainia, I stumbled upon this issue as I am searching for a way to use filebeat to output to several indices (from the same input). 

>  The answer is No, there aren't any intention of supporting more outputs than what we currently have.

Do you mean there aren't any plans to support more output _types_? Or multiple outputs of the same type?

My current use case is that I have a bunch of events collected by Filebeat, and I would like to index them in several [time series data streams](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html), each of them having a dedicated but reduced number of dimensions compared to the raw events, which allows for downsampling magic and query optimisation.
With multiple `elasticsearch` outputs (for the same input), it would be easy to setup everything within Elastic Cloud. With only one index output, I am not sure how to get this done without an external application "manually" pushing documents into thoses TSDS indices, thus questioning the use of Beat all together.

**Comment by nimarezainia** [comment]
Hi @Marchelune 
- there are no plans to support "more output types" (i know that is not relevant to your use case)
- We also don't have a plan to address the duplication as you describe, same event sent to multiple destinations, which I believe is the solution you desire here.

**Comment by Marchelune** [comment]
@nimarezainia thanks a lot for your answer 🙏. My use case is indeed duplication to several indices.

Should I create a feature request to manifest this interest?

I see it valuable for not just this use-case: in my research, I found several questions around that topic (https://github.com/elastic/elasticsearch/issues/68003 https://github.com/elastic/elasticsearch/issues/6240 or [stackoverflow]( https://stackoverflow.com/questions/61652310/sending-messages-to-multiple-elastic-search-indices)) but it seems the only solution is to use logstash, which allows several elasticsearch outputs - but it is another piece of software to manage and only in preview within ECK, whilst filebeat is well supported.

**Comment by nimarezainia** [comment]
> 

Feel free to open an enhancement request for the specific use case you are describing. Please tag me. 
Appreciate it @Marchelune
