### ISSUE TITLE
[Filebeat] shipping a huge amount of logfiles fails without error message

### ISSUE THREAD

**Issue by klaricl** [elastic/beats#28937]
I am trying to ship log files to logstash using filebeat. The folder structure of the input path is currently very branchy and very big.
We have a following structure: 
`<LOG_PATH>/<STREAM>/<WORKFLOW>/<TASK>/<EXECUTION_DATE>/<TRY_NUMBER>.log`

The logs are actually not that big, but the application produces every day an average of 300.000 new log files, depending which workflows are running and which tasks. Every newly created log creates a new execution_date folder containing the log file, and at the end we are having an unmanageable structure. A 'find' through the folder can take a week or more, and a 'ls' in some workflow folder can take for hours. I even wrote a python script to count the files and task folders using glob, but the execution was terminated after some time. 

As I could find out, filebeat is using filepath/glob, so my question is: how does filebeat "walk" through the input? can it be comparable to pythons glob, so that it just terminates after some time without any error log? can I assume that filebeat just can't handle this amount of files, under a shared volume?

**Comment by klaricl** [comment]
https://discuss.elastic.co/t/shipping-log-from-an-unmanagable-folder-structure-using-filebeat/289014

**Comment by jlind23** [comment]
@belimawr may you chime in please?

**Comment by belimawr** [comment]
@klaricl Are you using the `filestream` or the `log` input?

I saw your [message on discuss](https://discuss.elastic.co/t/filebeat-doesnt-harvest-folder-structure/286374), may I assume you're using the `log` input?

A couple of questions:
1. Do you have more logs aside the one in your discuss post?
2. What kind of shared volume are you using? NFS?

Please note that network shares need some extra configuration: https://www.elastic.co/guide/en/beats/filebeat/7.16/filebeat-input-log.html#file-identity

> how does filebeat "walk" through the input?

I'm looking into your question and I'll post here once I have an answer.

**Comment by belimawr** [comment]
For the `log` input ([that has been deprecated in 7.16](https://www.elastic.co/guide/en/beats/filebeat/7.16/filebeat-input-log.html)), for each path in the configuration file, Filebeat calls [`filepath.Glob`](https://pkg.go.dev/path/filepath#Glob), that returns a list of file paths. Filebeat then uses this list to collect some information about the files, check if it is a excluded file, etc and then opens the file for reading.

One important thing to notice about `filepath.Glob` is this bit of documentation:
> Glob ignores file system errors such as I/O errors reading directories. The only possible returned error is ErrBadPattern, when pattern is malformed.

So if `filepath.Glob` cannot expand the glob pattern to your huge list of  files, this issue will be silently ignored.

The `filestream` input is no different, it also uses `filepath.Glob` at some point to convert the glob pattern into a list of file paths that later on will be opened and harvested.

Does it answer your questions @klaricl?
