### ISSUE TITLE
Filebeat is unable to find files on a large, non C:\ NTFS drive on Windows

### ISSUE THREAD

**Issue by nostrebor** [elastic/beats#2893]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For confirmed bugs, please report:
- Version: 5.0.0
- Operating System: Windows Server 2012
- Steps to Reproduce: 
I have a drive `S:` which is a local NTFS drive. It resides on a physical machine, not a VM. When attempting to create a new prospector for a set of log files on `S:`, no files are found. Filebeat, however, [continues to consume more RAM (nearly 1gb)](https://i.imgur.com/LX6FIoW.png) as it finds no new files. My config is located [here](http://pastebin.com/U5eV7F9M).  Disregarding the `ignore_older` setting, I would expect that there are hundreds of thousands of matching log files on the drive (millions would not surprise me).

1. Mount a non C:\ NTFS drive. 
2. Populate it with folders, at least three deep. EDIT: make the last folder match the format of an IP address e.g. (123.123.123.123)
3. Populate these folders with files. My drive has multiple terabytes of information; the subfolder in question probably has 1TB of logs.
4. Modify the given filebeat config, and make sure to use at least four wildcards in the in the glob description. i.e. `S:\subdir\subdir\subdir\subdir\*\*\*\*.log`
5. Launch filebeat on the config file.

Expected: A matching file name should be found if one exists. Debug output should mention where it is in the scan process.

Actual: Debug logging appears as if no matching files were found. After running for 15+ minutes, no matching files are found.

Note: If the file glob description is modified as such:
`    - 's:\logs\iis\productlogs\devicemanagement\11111111-1111-1111-1111-1111111111111\11111111-1111-1111-1111-1111111111111\*\*.log' `
Matching files are found immediately.

**Comment by nostrebor** [comment]
To add more information:
It looks like a Read File is happening on the folder ip rather than the files in that subdir:
http://imgur.com/a/nwjIe. Which is why my depth 2 search is working, and depth 3+ are not.

**Comment by ruflin** [comment]
* Do you seen any indication in the logs if the first scan ever finishes or not? Could you share the log output?
* What do you mean by `Read File is happening on the folder ip`?

This is related to https://github.com/elastic/beats/issues/2084 I think?

**Comment by andrewkroh** [comment]
@ruflin This is the log output from one of the runs @nostrebor did. I don't see any indication that the prospector completed. WDYT? http://pastebin.com/yByH1SLR

**Comment by nostrebor** [comment]
@ruflin I do not believe that the prospector ever completes. my logs look like http://pastebin.com/yByH1SLR repeated. Even when running for 30 minutes. I've noticed that the access pattern is different in a successful run; when I run using the four depth wildcard on a single folder, a QueryDirectory happens on the folder and then a ReadFile happens on the contents of that folder. For my large directory structure, QueryDirectory happens on the folder, and then a ReadFile happens on the same folder.

**Comment by nostrebor** [comment]
For instance, look at the following [procmon log](https://cloud.githubusercontent.com/assets/7697492/19898559/bfe87234-a019-11e6-84c2-27515a6e76af.png)

**Comment by ruflin** [comment]
I also don't see any indication that the first scan every completes (Next scan only shows up once). It seems like it gets stuck on the first scan.

I don't remember we had a previous case with > 1 million files to be harvested. So this is getting interesting :-) I think there are 2 potential issues:

* glob pattern struggles with large number of files
* glob pattern struggles with depth > 2
* prospector struggles with large number of files
* ?

What is the number of files you have at depth 2? What is the number if you have at 3? 

For my personal interest to better understand the use case: What kind of files are these? Are these log files which are updated over time or files which are only written once?

**Comment by nostrebor** [comment]
At depth two very few. At depth three I would guess a few hundred thousand. These are files which are only written once; except for a few thousand which are not rotated.

**Comment by nostrebor** [comment]
Sorry I'm on my phone and don't see how to edit. These are files that are coming from external clients.

**Comment by ruflin** [comment]
Checking the logs again, I would expect to see at least a few lines with `check file for harvesting`. As this does not show up, it seems to already get stuck in the `getFiles()` part of the prospector.

I will try to reproduce this by creating some tests with > 1 million of files and see what happens on the prospector side when I start up. I'm not too surprised about a larger memory usage as filebeat will keep the state for all 1 million files in memory in case they don't fall under clean_inactive.

**Comment by ruflin** [comment]
@nostrebor Sorry, that somehow slipped through on my side. Any updates form your side in the meantime? Did you find a workaround?

**Comment by nostrebor** [comment]
I was actually on a two week vacation. I found no workarounds and I'm considering using nxlog :/

**Comment by nostrebor** [comment]
Could I get a status update on this? I'm looking into alternatives today, and it seems like I'm going to write my own log shipper to meet our use case -- I would like to avoid this work if this issue is getting traction.

**Comment by ruflin** [comment]
I run some tests on this on my OS X machine (not NTFS). I tried with 1.5 million files. Already `ls -l logs/ | wc -l` took more then 5 minutes. All generated logs files are in `logs/` and new files were generated during this time. Running filebeat on this directory with a simple `logs/*.log` pattern took filebeat a little bit more then 5 minutes to start seeing the files. This test was done a "normal" SSD.

Based on the rudimentary tests above I assume the more complex / extensive the glob pattern gets, the longer it will take to pick up the files. Based on the Glob implementation (https://golang.org/pkg/path/filepath/) will do a Stat command on each file. Looking at your logs you waited quite a bit longer. Did you see any peak and disk reading during this time? Did you try nxlog if  it can handle these patterns with the number of files? In general I would recommend to split the above up in multiple prospectors which have simpler glob patterns.

**Comment by urso** [comment]
This issue is for an old version of beats, I suggest to try out the latest version of beats. If this is still a problem in the newly released version feel free to reopen this issue. Thanks.
