### ISSUE TITLE
Add Cisco IronPort log ingest to existing filebeat Cisco module

### ISSUE THREAD

**Issue by colin-stubbs** [elastic/beats#28949]
Add support for ingest of Cisco IronPort logs, via both file and syslog listeners, to existing filebeat cisco module.

I will issue a pull request against this issue from a fork containing code/config to support this.

## Filebeat module

* [ ] Test log files exist for the grok patterns
* [ ] Generated output for at least 1 log file exists

**Comment by jamiehynds** [comment]
@colin-stubbs we just shipped a Cisco Secure Email Gateway (rebranded from Ironport I believe) integration. Will close this issue, and would be great to get your feedback if you deploy the new integration.
