### ISSUE TITLE
[Agent] [Kubernetes Integration] Log lines are in JSON format

### ISSUE THREAD

**Issue by zikphil** [elastic/beats#28975]
Hello,

I've recently switch from using standalone FileBeat instances to using Fleet managed-agents with the Kubernetes module. I am running latest version (7.15) and Im noticing that all the logs coming from the kubernetes.container_log dataset are in json format (in a string field). The content of the message field is as followed:

<img width="1028" alt="CleanShot 2021-11-15 at 12 39 27@2x" src="https://user-images.githubusercontent.com/1538854/141828861-cb60970a-1fcf-45a0-b583-0b14a31281fa.png">

Any way we can tell the integration to only use the "log" key as the message?

Thanks

**Comment by tetianakravchenko** [comment]
Hi @zikphil. I think you just need to upgrade to the latest version:
I could reproduce this behavior on version 7.15.1:
<img width="2216" alt="Screenshot 2021-12-21 at 12 11 52" src="https://user-images.githubusercontent.com/28299531/146921337-c411b0f3-0aac-4feb-925f-af4b6fb83c57.png">

thought with the version 7.16.2:
<img width="2221" alt="Screenshot 2021-12-21 at 12 16 36" src="https://user-images.githubusercontent.com/28299531/146921384-21edb74c-c64c-43a5-8af6-627af6513590.png">
only `log` content is stored in `message` field

**Comment by tetianakravchenko** [comment]
I will close this issue, as it should be fixed in newer stack version. Feel free to reopen it if you need any help
