### ISSUE TITLE
Sophos XG improvements

### ISSUE THREAD

**Issue by leehinman** [elastic/beats#29002]
- support `device_serial_id` as alternate for`device_id`
- support `dst_zone_type` as alternate for `dstzonetype`
- support `src_zone_type` as alternate for `srczonetype`
- preserver `srczone` an `dstzone` as custom fields

**Comment by bitnapper** [comment]
See [#28932](https://github.com/elastic/beats/pull/28932)

**Comment by legoguy1000** [comment]
See elastic/integrations#2158 and elastic/integrations#2163

**Comment by andrewkroh** [comment]
Relates:

- https://github.com/elastic/beats/pull/31038
- https://github.com/elastic/beats/pull/28932

**Comment by andrewkroh** [comment]
We have log samples in both https://github.com/elastic/beats/pull/31038 and https://github.com/elastic/integrations/pull/2163. I think the updated pipeline should handle both the old and new log format to have broader Sophos XG version compatibility.

There are fixes in both https://github.com/elastic/integrations/pull/2163 and https://github.com/elastic/beats/pull/28932. I think we should finish the elastic/integrations PR and then sync the whole pipeline back into the Filebeat module.

**Comment by piellick** [comment]
hello guys,

In meanwhile, i have found this doc who provide sample logs per log type fro 18.5.X version :
[https://docs.sophos.com/nsg/sophos-firewall/18.5/PDF/SF%20syslog%20guide%2018.5.pdf]
Could be very helpfull for you.
