### ISSUE TITLE
[Agents][Inconsistent]: `File used by another process` for filebeat and metricbeat errors on installing agent.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#29023]
**Kibana version:**  7.16.0 BC-5 Kibana Cloud-Staging environment

**Host OS and Browser version:**  Windows, All

**Build details:**
```
Build: 46061
Commit: f13296db8798dd0cd39ab6cc4a61a35a2a2b05cc
Artifact Link: https://staging.elastic.co/7.16.0-4d61fd94/downloads/beats/elastic-agent/elastic-agent-7.16.0-windows-x86_64.zip
```

**Preconditions:**
1.  7.16.0 BC-5 Kibana Cloud-Staging environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Run Agent install command for Windows Agent.
3. Observe agent inconsistently take more than usual time to get Healthy.
4. Under Agent Logs tab observe `File used by another process` error logs.

**Screenshot:**
![2](https://user-images.githubusercontent.com/77374876/142360038-48f91739-49c0-464f-a8e1-d055bc78a10a.JPG)

**These set of error logs were generated for filebeat service too.**

**Debug level logs of MACHINE 01:**

[Agent-logs-01.zip](https://github.com/elastic/beats/files/7560346/Agent-logs-01.zip)

[filebeat-logs-01.zip](https://github.com/elastic/beats/files/7560347/filebeat-logs-01.zip)

[metricbeat-logs-01.zip](https://github.com/elastic/beats/files/7560353/metricbeat-logs-01.zip)

**Debug level logs of MACHINE 02:**

[Agent-logs-02.zip](https://github.com/elastic/beats/files/7560356/Agent-logs-02.zip)

[filebeat-logs-02.zip](https://github.com/elastic/beats/files/7560359/filebeat-logs-02.zip)

[metricbeat-logs-02.zip](https://github.com/elastic/beats/files/7560365/metricbeat-logs-02.zip)

**Expected Result:**
`File used by another process` for filebeat and metricbeat errors should not be generated on installing agent.

**Note:**
- **This issue is inconsistent** and found this reproducible 5 times when attempted 7 times.
- There was **no network issue** at my end.
- All Elastic related folders were deleted before reinstallation.
- Install command tested using both with `-f` flag and without `-f` flag.

**What's Working:**
These error logs were not observed till BC-4.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mentioned to @andresrc  

CC: @EricDavisX

**Comment by jlind23** [comment]
@amolnater-qasource were they some processes still running while trying to install the agent?
Was the agent already installed or are they brand "new" machine?

**Comment by EricDavisX** [comment]
The commits are shown when you do an './elastic-agent version' command, even if not installed or running etc.
BC4 
edavis-mbp:elastic-agent-7.16.0-darwin-x86_64-bc4 edavis$ ./elastic-agent version
Binary: 7.16.0 (build: 1472c0acf05cfdcba4869a68b3239abc25cb4330 at 2021-11-11 15:41:25 +0000 UTC)

BC5
edavis-mbp:elastic-agent-7.16.0-darwin-x86_64-bc5 edavis$ ./elastic-agent version
Binary: 7.16.0 (build: b119cffa86b96173703d82c9e736c8fd61819379 at 2021-11-17 20:34:00 +0000 UTC)

**Comment by jlind23** [comment]
@fearful-symmetry may it be related to your commit about hostfs behaviour? https://github.com/elastic/beats/commit/472e45c6c780018f795d12f00ad50c8ac6a621ad

**Comment by fearful-symmetry** [comment]
Is this a windows-only issue? If so, `hostfs` doesn't impact any data collection done on windows. Also don't see any sign of a weird path in that in that log message.

**Comment by amolnater-qasource** [comment]
Hi @fearful-symmetry 
Yes this issue was only reproducible on Windows Agent installed on **7.16.0 cloud-staging environment.**

> they some processes still running while trying to install the agent?

@jlind23 Machine was clean and no agent was installed on it earlier.

However we attempted to revalidate this today on **7.16.0 cloud-production environment** and we didn't get these errors.
We even attempted to unenroll and then re-enroll the agent, however didn't observe these errors.

For now we will be **closing** this issue and we will keep track these error logs.
@EricDavisX 
Thanks
