### ISSUE TITLE
[Heartbeat] Arm support for browser monitors

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#29034]
Currently heartbeat does not work with browser monitors on ARM. One reason is that our seccomp filters are for x86 only. There are probably other issues. 

- [ ] the container needs to work on ARM with the correct deps
- [ ] make Heartbeat run on ARM (includes the seccomp filters)

**Comment by paulb-elastic** [comment]
Blocked on https://github.com/elastic/obs-dc-team/issues/613

**Comment by andrewvc** [comment]
I've spent a chunk of time on this today emulating arm64 on docker via qemu , and what I've learned is:

1. We'll probably need to bump to a more recent playwright version in https://github.com/elastic/synthetics for ARM to work properly, the version of chrome we're on won't even start
2. More recent versions of chrome start but get weird ptrace issues, likely related to ptrace not working on qemu

We'll need to do the dev work to fix this on a real ARM box. Maybe @devcorpio and I could spend a few hours pairing on this.

I'm going to push this out to 8.2 for now given that I think that's a more realistic target given those various changes. If you object @paulb-elastic feel free to bring it back

**Comment by vigneshshanmugam** [comment]
I have received my M1 as well. But did not even start the setup as I was afraid to get HB working 😄

**Comment by emilioalvap** [comment]
PostFF LGTM, tested on docker.elastic.co/beats/heartbeat:8.2.0-SNAPSHOT-arm64.

Steps I've taken to reproduce:

- Launch ARM EC2 instance:
````
$ uname -a
Linux ip-172-31-11-246 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:04:48 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
````

- Execute synthetics-demo on docker container:
````
 sudo docker run --rm /
    --volume="$PWD/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro" /
    docker.elastic.co/beats/heartbeat:8.2.0-SNAPSHOT-arm64 /
    -E cloud.id=<cloud id> /
    -E cloud.auth=<cloud auth>
````

- Checked that browser monitors are shown in Uptime:
![image](https://user-images.githubusercontent.com/95703246/163979829-f4169a31-46f9-481d-abe6-ebb4bab20755.png)
![image](https://user-images.githubusercontent.com/95703246/163979956-b394dca9-a27a-4132-b33b-237c096b0bef.png)
