### ISSUE TITLE
Make custom module generation easier

### ISSUE THREAD

**Issue by markwalkom** [elastic/beats#29061]
**Describe the enhancement:** It'd be great if we had a tool, or a flag in libbeat, that you would pass a directory path with a config, mappings, dashboard, ingest pipelines etc, and it'd create a module that you could distribute as a bundled (zip/tar/whatever) file.

This would be a great way to encourage creation of modules outside of the ones that we manage, as the [current process](https://www.elastic.co/guide/en/beats/devguide/current/filebeat-modules-devguide.html) is a little in depth.

**Describe a specific use case for the enhancement or feature:**
I've seen plenty of threads out in the community where users have created the fundamental parts of a module, they just haven't packaged it up per the docs. There's also been times I've personally wanted to create a module for something I've come across, but have been also put off by the overhead of doing this.

If we can reduce the friction of this, it should be pretty simple to foster the creation and up keep of a heap of non-official modules.

**Comment by jlind23** [comment]
ping @nimarezainia

**Comment by kvch** [comment]
I do not think we will address it in modules. The future is using integrations, not modules for Filebeat. Maybe it is worth opening an issue in https://github.com/elastic/integrations and ask about the support for this.

**Comment by jlind23** [comment]
@markwalkom if you agree we can close this issue in favour of a new one in https://github.com/elastic/integrations, what do you think?

**Comment by nimarezainia** [comment]
@kvch & @ruflin would idea of the custom input address the same use case (https://github.com/elastic/beats/issues/30019). 
i would much prefer enhancing Elastic Agent by addressing custom inputs for the community.

**Comment by kvch** [comment]
> would idea of the custom input address the same use case

To some degree yes. Modules are not only include the input, but they come with data parsing, visualizations, etc. Supporting custom inputs covers only just a fraction of a capabilities of module, the data collection part. However, Elasticsearch and Kibana assets (like Ingest pipelines, dashboards, etc.) must be covered by the integrations, not the custom input. Custom inputs are only about collecting data, then integrations provide a way to parse and visualize the collected data.
