### ISSUE TITLE
Loading YAML file from external source like Database or api call

### ISSUE THREAD

**Issue by SharmaBiswadev** [elastic/beats#29064]
**Description**
Currently metricbeat.yml is loaded from file system using go-ucfg module. Also if we can load the metricbeat.yml data from database or through external call.
**Usecase**
If we have a large pool of metrcibeat and corresponding configuration file metricbeat.yml, Each metrcibeat's metricbeat.yml is loaded from external source with single control panel attached to the external source.

Please let us know if we can load the configuration file from external source as database as a choice. 
Thank you

**Comment by ruflin** [comment]
It sounds like what you are looking for is Elastic Agent with Fleet: https://www.elastic.co/blog/elastic-agent-and-fleet-make-it-easier-to-integrate-your-systems-with-elastic In Fleet you have an API through which you can push config changes.
