### ISSUE TITLE
[Question]: Filebeat hits on discover tab are generated at different time lapse on Mac Monterey

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#29073]
Hi All,

We have raised this ticket in order to confirm filebeat events generation behavior on Mac monterey.

Currently, we have attempted to install filebeats on different mac VMs having OS 12 and recorded same behavior that filebeat is sending only one event on discover just after installation and adds up new records with inconsistent time lapse. So, we are unsure of this behavior as on earlier Mac versions say big sur, we have not seen this. 

While on big sur, vms continuously keeps on ingesting data to Kibana discover tab even with if there is milliseconds of difference in time.

So if anybody could confirm If new OS has new settings with regard to **system module** and thats why records are getting generated in such way, will be very helpful to understand the filebeat behavior on MAC OS 12.

**Screenshots:**
**Filebeat installation on MAC OS 12:**
![image](https://user-images.githubusercontent.com/72375798/142853610-6c7f485d-e998-48e8-91f2-2acc13047945.png)

![image](https://user-images.githubusercontent.com/72375798/142853693-9ca0ce4e-6345-4232-8a56-cc3548fa8339.png)

**Filebeat installation on MAC big sur:**
![image](https://user-images.githubusercontent.com/72375798/142853967-1f71004b-13cf-498f-b857-bb6241bb7e9a.png)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @andresrc

CC: @EricDavisX

**Comment by andresrc** [comment]
Either few logs are generated or they are sent somewhere else. @fearful-symmetry can you take a look?

**Comment by fearful-symmetry** [comment]
So, I'm not really a filebeat expert or MacOS expert, but have we confirmed this isn't something on the machine side? Can we confirm this isn't just newer versions of MacOS logging things differently, or using syslog differently?
