### ISSUE TITLE
Setup fails for Beats 7.15.2 on Windows 

### ISSUE THREAD

**Issue by norgro2601** [elastic/beats#29089]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 
- Operating System: 
- Discuss Forum URL:
- Steps to Reproduce:

Hello,

I've upgraded Beats to Version 7.15.2 running on Windows. I've noticed that the Setup for dashboards doesn't work and looking at the log in the console, I see, that in the path, there is a slash instead of a backslash. I've attached a screenshot showing this.

The behavior is the same to all beats, not only winlogbeat. 

Best regards,
Norbert 

![Error](https://user-images.githubusercontent.com/13552087/142995741-0599fe81-7401-4262-9c06-80fc353a3d17.png)

**Comment by kvch** [comment]
Could you please share debug logs?

**Comment by norgro2601** [comment]
> Could you please share debug logs?

I've run the setup command this way but can't find any debug logs. Is the command correct to get those logs?
.\winlogbeat.exe setup --dashboards -d "*"

**Comment by kvch** [comment]
Yes, the logs land under the `logs` folder. Alternatively, you can run the command like this: `.\winlogbeat.exe setup --dashboards -e -d "*"`, so the logs are printed to stdout.

**Comment by norgro2601** [comment]
Sorry for the late reply, here is the result of the setup command, I've done it for metricbeat, but I get get the same errors for winlogbeat. Due to the long time running and a delay of 90 sec on each error, it does not finsh.
[metricbeat.txt](https://github.com/elastic/beats/files/7633273/metricbeat.txt)

**Comment by kvch** [comment]
Is this still an issue? I cannot reproduce the problem.

**Comment by norgro2601** [comment]
Just tested with the same Beats version, but Kibana is already updated to 7.16.2. In this environment, the problem is no longer existing.

**Comment by jlind23** [comment]
Closing it as it can not be reproduced then.
