### ISSUE TITLE
[Heartbeat] Append synthetic journey duration to monitor.timespan for browser monitors

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/beats#29102]
Browser monitors are more likely to run longer than the scheduled interval. When this happens, it can create gaps in the `monitor.timespan` value for individual checks. For example, consider these two timespans from adjacent checks. The journey itself takes two minutes to complete, and it's interval is every 1 minute

```
            "timespan" : {
              "gte" : "2021-11-22T19:00:02.921Z",
              "lt" : "2021-11-22T19:01:02.921Z"
            }
```
```
            "timespan" : {
              "gte" : "2021-11-22T19:02:37.740Z",
              "lt" : "2021-11-22T19:03:37.740Z"
            },
```

Notice how there is now a 1 minute gap between the timespans of the two checks.

To mitigate this, we can append the journey duration to the journey start and use that as the monitor.timespan, when the the journey duration is greater than the interval.

### **Why is this important?** 
This behavior was identified when debugging reasons for flapping alerts for browser monitors in the Uptime UI. Alerts check for down monitors between now and the user configured time interval. When this interval is less than the duration of the journey, flapping can occur in which the alert resolves when the monitor is still down. 

This can be considered an edge case, but it might not be as big of an edge case as we think. It is true that users are likely to choose monitor and alerting intervals that are reasonable relative to their expected monitor time. However, when a monitor is consistently down, it can be long running for a variety of different reasons, including waiting for timeouts for selectors and slow loading pages. Monitors are therefore likely to take longer than the users expected duration when it is running into issues.

When it comes to Zip URL based monitors, the person configuring the alerts and monitors also may not have insight into the average monitor duration, and it may bloat as developers and qa add more tests. 

For this reason, I think it's important that we address this issue by adjusting the monitor timespan, rather than instructing our users to make approximations about the appropriate monitor intervals or rule intervals.

**Comment by andrewvc** [comment]
Maybe consider making the window in the alerts / kibana queries longer (say
2m). (OK back to vacation for me now).
