### ISSUE TITLE
Add --list-pipelines option and/or check pipeline existence at startup

### ISSUE THREAD

**Issue by dadoonet** [elastic/beats#2913]
This is a suggestion which might be not useful as anyone can also easily call elasticsearch directly for that with a `curl localhost:9200/_ingest/pipeline`.

But anyway, here is the proposal:

* One can call `filebeat --list-pipelines` which will call `localhost:9200/_ingest/pipeline` and will give a digestable list of existing pipelines in elasticsearch
* One can call `filebeat --check-pipelines` which will call `localhost:9200/_ingest/pipeline/xxxx` and will check that the pipeline defined in  `filebeat.yml` actually exists
* When you start filebeat and when a pipeline is defined, check at startup that the pipeline actually exists otherwise all logs will be rejected.

Feel free to close this if it does not make sense.
Note that it applies to any beat IMO so if implemented it should go to libbeat.

**Comment by ruflin** [comment]
The pipeline configuration option in Filebeat can also be a `format string`, which means the pipeline is potentially defined based on the event content and not hardcoded. This will make point 2 quite hard.

Turning around the problem, Filebeat could automatically load a pipeline into elasticsearch in case it does not exist yet (assuming the pipeline definition exists locally)
