### ISSUE TITLE
Allow registering Ingest Pipelines from filebeat (or other beats)

### ISSUE THREAD

**Issue by superdump** [elastic/beats#2914]
This issue is a feature request against beats 5.x.

Elasticsearch 5.0.0 gained the new ingest pipeline functionality. filebeat can make use of an ingest pipeline to process its log messages by specifying the pipeline id. This feels operationally awkward to use as one has to:
* deploy an elasticsearch instance
* identify the index pattern and type from the client that will be submitting log messages
* put the ingest pipeline into the index and type, giving it an id
* configure the client to use the pipeline id for its index submissions

I wrote a node server using the elasticsearch JS client lib and it was entirely natural to me to try to get the pipeline id for the index and type and if the pipeline is not present, put the pipeline into the index and type with the specified id. This seems operationally much simpler to me and looks like:
* deploy an elasticsearch instance
* deploy client configured with the processing pipeline and id

**Comment by ruflin** [comment]
@superdump We are discussing already internally how to do this best. At the moment beats ship with kibana dashboards and templates which are pushed to elasticsearch on startup. Pushing predefines pipelines is definitively a good idea.

**Comment by monicasarbu** [comment]
We are introducing Filebeat modules in the 5.3 release. Following fairly closely the model started in Metricbeat, a Filebeat module contains the out of the box configuration needed to read, parse and visualize data from various log files formats. This includes Ingest Node pipelines, Elasticsearch templates, Filebeat prospectors configurations, and Kibana dashboards. You can find more details about how to configure it under the meta ticket: https://github.com/elastic/beats/issues/3159.

I think Filebeat modules are a good start to solve your enhancement request, so I am closing the issue for now.
