### ISSUE TITLE
Filebeat setup issue. Asking for Setting up ML using setup --machine-learning

### ISSUE THREAD

**Issue by rohitml28** [elastic/beats#29149]
![Screenshot 2021-11-25 at 5 52 59 PM](https://user-images.githubusercontent.com/91941458/143442017-fb9d9d25-44d7-4e40-9b30-0d97dd2b600a.png)

AC-LAP-032:filebeat-7.15.2-darwin-x86_64 rohit$ ./filebeat modules enable system
Module system is already enabled
AC-LAP-032:filebeat-7.15.2-darwin-x86_64 rohit$ ./filebeat setup
Index setup finished.
Loading dashboards (Kibana must be running and reachable)
Loaded dashboards
Setting up ML using setup --machine-learning is going to be removed in 8.0.0. Please use the ML app instead.
See more: https://www.elastic.co/guide/en/machine-learning/current/index.html
Exiting: 1 error: Error setting up ML for apache_ecs: 10 errors: ; ; ; ; ; ; ; ; ; 
AC-LAP-032:filebeat-7.15.2-darwin-x86_64 rohit$

Any solution to overcome this error or to skip this part and process with system log setup.

**Comment by kvch** [comment]
The issue you are seeing usually shows up if the ML jobs already exist.

You can skip loading the ML jobs if you specify everything besides `--machine-learning`.

```sh
./filebeat setup --dashboards --index-management --pipelines --modules module1,module2
```

**Comment by amolnater-qasource** [comment]
Hi @kvch 
Thanks for providing the alternate command. 
We have revalidated this on 7.17.1 Kibana cloud environment and observed that it **fixes the ML errors**.

**Screenshot:**
![7](https://user-images.githubusercontent.com/77374876/158550676-20cac97a-a5f0-4d51-80d5-09a7f7707508.JPG)

**Build details:**
```
BUILD: 46635
COMMIT: 78e8422ed4e7d2054bd35b82a91299b3f7bd6231
Artifact Link: https://www.elastic.co/downloads/past-releases/filebeat-7-17-1
```

Thanks!
