### ISSUE TITLE
[Filebeat-8.0]: `module system is configured but has no enabled fileset:` error on running filebeat setup command.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#29175]
**Kibana version:**  8.0 Snapshot Kibana Cloud-qa environment

**Host OS:** Ubuntu 20(.tar), Centos 8(.rpm), Debian 10(.deb) and MAC

**Build details:**
```
Build: 48414
Commit: e5070e0ebad538dd152fbc8e016091a2580047b4
Artifact Link: https://snapshots.elastic.co/8.0.0-94dc1348/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-linux-x86_64.tar.gz
```

**Steps to reproduce:**
1. Download and extract filebeat artifact.
2. Update the `filebeat.yml`:
```
cloud.id: "XXXXXXXXXXXXXXXXXXXXXXXLXdlc3QxLmdjcC5jbG91ZC5lcy5pbyQ4MGM4NDgyYjRlODE0Yzkxxx=="
cloud.auth: "elastic:IEtKXRAmrH4zuGxxxxxxx"
```
3. Run: `./filebeat modules enable system`.
4. Run command:`./filebeat setup -e`.
5. Observe below error:

![3](https://user-images.githubusercontent.com/77374876/143838492-471a9fa7-71a1-43ee-89b4-2b8a47e7baaf.JPG)

**filebeat.yml:**
[filebeat.zip](https://github.com/elastic/beats/files/7616911/filebeat.zip)

**CLI-detailed steps:**
[CLI-filebeat.txt](https://github.com/elastic/beats/files/7616928/CLI-filebeat.txt)

**Expected Result:**
No error should be there on running filebeat setup -e command, and filebeat should show data under Discover tab.

**Reference Document:**
https://www.elastic.co/guide/en/beats/filebeat/7.15/filebeat-installation-configuration.html

**NOTE:**
- We are unable to get filebeat data on Ubuntu 20(.tar), Centos 8(.rpm), Debian 10(.deb) and MAC hosts.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mentioned to @andresrc 

CC: @EricDavisX

**Comment by kvch** [comment]
This is expected behaviour. From 8.0, all filesets are disabled by default and users have to enable them manually. An error is returned when nothing is enabled to let users know if they forgot turn on modules/filesets.

**Comment by kvch** [comment]
I talked with @amolnater-qasource offline, but I am sharing it here as well. To avoid this error, you have to enable `syslog` and `audit` filesets in the file `modules.d/system.yml`:

```yml
- module: system
  # Syslog
  syslog:
    enabled: true
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:

  # Authorization logs
  auth:
    enabled: true

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:
```

**Comment by amolnater-qasource** [comment]
Hi @kvch 
Thanks for sharing the update.
On updating both `syslog` and `auth` to true under `modules.d/system.yml`.
We are successfully able to get data under Discover tab.

**QUERY:**
Further under Discover tab: we got a new index could you please confirm **if this is an issue or expected**?:

![6](https://user-images.githubusercontent.com/77374876/144031735-84ba8d98-4613-4fb8-a221-6f85c591194c.JPG)

We have only enabled system module.

@EricDavisX 
We have updated our test content for Filebeat installation on this update. 

Please let us know if anything else is required.
Thanks

**Comment by kvch** [comment]
@ruflin Is this new "apm-*-transaction*..." template expected?

**Comment by ruflin** [comment]
@simitt @sqren You might be able to help with the above? I assume this is coming from APM?

**Comment by EricDavisX** [comment]
> Hi @kvch Thanks for sharing the update. On updating both `syslog` and `auth` to true under `modules.d/system.yml`. We are successfully able to get data under Discover tab.
> 
> @EricDavisX We have updated our test content for Filebeat installation as per this update.

Hi @amolnater-qasource can you do a Filebeat docs check to see if it was updated to indicate this new expectation and general info on how to update it to 'see' any data come in? If it needs it, we can log a separate docs ticket and ref this.

**Comment by sqren** [comment]
> @ruflin Is this new "apm-_-transaction_..." template expected?

Yes, it's automatically created when the APM UI app is opened.

**Comment by amolnater-qasource** [comment]
Hi @sqren 
We haven't accessed APM UI and haven't done anything related to APM.
These datasets were there on running Filebeat with both syslog and auth filesets from system.yml.
You can refer screenshot at: https://github.com/elastic/beats/issues/29175#issuecomment-982536819 
`agent.type`= filebeat.

Is that expected to get this for even Filebeat or it is an issue? 

@EricDavisX 
Under docs yes it is there that we need to enable the required filesets.
![13](https://user-images.githubusercontent.com/77374876/144197368-73e5fe12-ad47-447e-b54f-c2960d56f668.JPG)

However till 7.16 we never enabled these, as by default these filesets gets enabled on running `./filebeat modules enable system` for any module.
On 8.0 its set to false even after enabling system, user has to manually do it as confirmed at https://github.com/elastic/beats/issues/29175#issuecomment-982501933
It might be confusing for the first time.

Further for datastreams it is only mentioned to show for filebeat-* index.
On confirmation from @sqren we will log the required ticket.

cc: @ruflin 
Thanks

**Comment by sqren** [comment]
> Is that expected to get this for even Filebeat or it is an issue?

I don't see any problems here. The user can delete the data view (index pattern) manually and stop it from being created by setting `xpack.apm.autocreateApmIndexPattern: false`.

**Comment by amolnater-qasource** [comment]
Thanks @sqren  for sharing the feedback.

@EricDavisX 
- Documents do have these updates available for 8.0.
- There is no discussion of the new index("apm--transaction...") under the docs.
- However as confirmed above it is not an issue that a new index is created with filebeat-*.
Could you please confirm if any action is required for the same or we should mark this as done?

Thanks!

**Comment by EricDavisX** [comment]
excellent summary - @amolnater-qasource  please scan through the docs repo and put a ticket in if we don't see one for the docs.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
As per feedback we have logged a docs ticket for these changes regarding Filebeat installation at https://github.com/elastic/observability-docs/issues/1309

Thanks

**Comment by metalshanked** [comment]
Hi @kvch , @amolnater-qasource 
I am facing the error when using custom inputs for filebeat modules. Can anyone please advise on how to solve this in 8.0.0

```
filebeat.modules:   
  - module: panw
    panos:
      enabled: true
      var:
        input: custom
      input:
        type: kafka
        hosts:
```

```
"message":"Error creating runner from config: could not create module registry for filesets: module panw is configured but has no enabled filesets","service.name":"filebeat","ecs.version":"1.6.0"}
```

**Comment by drenze-athene** [comment]
> Hi @kvch Thanks for sharing the update. On updating both `syslog` and `auth` to true under `modules.d/system.yml`. We are successfully able to get data under Discover tab.

After enabling modules, as well as syslogs in the modules, I'm still having the same issue.

**Comment by smandolare** [comment]
> This is expected behaviour. From 8.0, all filesets are disabled by default and users have to enable them manually. An error is returned when nothing is enabled to let users know if they forgot turn on modules/filesets.

I am manually running the setup command on an independent management node and there are intentionally no filesets configured on any module the setup command is being run for. In version 7 this worked perfectly, not that there is a check on the assumption something is missing when it is intentionally left out breaks the process. Is there a way to ignore this check to complete the setups?
