### ISSUE TITLE
[Request] Update 7.16 Release Notes regarding Journalbeat replacement

### ISSUE THREAD

**Issue by nimarezainia** [elastic/beats#29185]
## Description

Need the following to be included in the release-notes for 7.16:

*Journalbeat, a lightweight shipper dedicated to collecting logs written by Journald system service, is being deprecated in this release. This functionality is instead provided as an input for Filebeat. Users should migrate to using Filebeat and it’s journald input as described in the [Elastic documentation](https://www.elastic.co/guide/en/beats/filebeat/7.16/filebeat-input-journald.html).

The users can also enable collection of Journald logs via the Elastic Agent by enabling the "Custom Journald Logs" integration. 
*

[NOTE: it would be great to point the user to the integrations docs for "Custom Journald Logs" - however  I don't have that URL]

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The docs team will lead producing the content

**Contact Person:**
@nimarezainia 

## Suggested Target Release

*7.16*

## Stakeholders

*(Please list any stakeholders for this issue.)*

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/beats/pull/29300
