### ISSUE TITLE
Make all config options visible in default config file

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#292]
Currently in the default config file, not all configuration options for packetbeat and libbeat are available. In the default config files all options with descriptions should be listed but commented out. 

A incomplete list of options from libbeat can be found here: https://github.com/elastic/libbeat/blob/master/outputs/outputs.go It should be checked if all options work as expected.

**Comment by monicasarbu** [comment]
@ruflin I think this issue needs to be divided in two parts:
[ ] add all configuration options to the configuration file. This is something that we need to discuss about.
[ ] check if all configuration options are documented

**Comment by ruflin** [comment]
@monicasarbu I'm voting for having all config options in the config file even though it could get really big. We should check how elasticsearch is doing it.

**Comment by ruflin** [comment]
Closing this as we introduced the `beatname.full.yml` config file which contains all options.
