### ISSUE TITLE
Do not overwrite index template if it has not changed

### ISSUE THREAD

**Issue by kvch** [elastic/beats#29202]
At the moment Beats always overwrite the index templates if `setup.template.overwrite` is set to true. However, we could check the contents of the template in Elasticsearch, and only load the template if it is different from what the Beat wants to load. Otherwise, we might end up with too many PUT template operations due to users forcing Beats to overwrite templates.

**Comment by rdner** [comment]
@kvch Why having PUT requests is worse than having GET and then PUT?

We would have to GET the template first, compare it (which can be not trivial because of formatting) and then PUT if it does not match, right?

**Comment by kvch** [comment]
> Why having PUT requests is worse than having GET and then PUT?

Sending PUT template request puts more load on an Elasticsearch instance than just performing a GET template. The goal is to decrease the number of PUT template requests made to ES. Basically we are moving more processing to Beats to free up resources in Elasticsearch.

> We would have to GET the template first, compare it (which can be not trivial because of formatting) and then PUT if it does not match, right?

Correct.
