### ISSUE TITLE
Decommission of Central Beats Management disambiguity

### ISSUE THREAD

**Issue by 111andre111** [elastic/beats#29210]
Sorry for the late notice here, but I still think we should fix this:

I had a case that uncovered a disambiguity in how we communicated to customers when we will remove Central Beats Management (CBM).
First of all, that's how the documentation page of CBM itself evolved:

  https://www.elastic.co/guide/en/beats/metricbeat/7.14/configuration-central-management.html
    Starting in version 7.14, Beats central management has been removed.
      https://www.elastic.co/guide/en/beats/metricbeat/7.4/configuration-central-management.html --> until that beta feature
      https://www.elastic.co/guide/en/beats/metricbeat/7.5/configuration-central-management.html --> discontinued

Then we were mentioning here we will remove CBM in version 8:
https://github.com/elastic/beats/pull/14018#pullrequestreview-300645675

In our release notes for 7.14.0 we say
  https://www.elastic.co/guide/en/kibana/7.14/release-notes-7.14.0.html
  "The following functionality is deprecated in 7.14.0, and will be removed in 8.0.0. Deprecated functionality does not have an immediate impact on your application, but we strongly recommend you make the necessary updates after you upgrade to 7.14.0.
  **Deprecates beats_management plugin**"

The last one should really go to a breaking change and we should not call it `Deprecates` but `Removes` would be better here.

The disambiguity is that in the beats release notes we mention that it will be removed with 7.14:
https://www.elastic.co/guide/en/beats/libbeat/7.14/release-notes-7.14.0.html
**Removed beats central management**

But unfortunately customer checked the kibana side release notes before upgrading.

So for any customers out there that still use CBM it is simply not very obvious what exactly is right. True, customers could install first a test version.

This is what the customer did, however in this case, they didn't try CBM in this test environment so it simply has fallen through the crack and we got in the meanwhile customer back into a good mood, leaving the CBM cluster at version 7.13 that still has CBM and they can now migrate towards fleet step by step.

I would please that we would correct this please.

@nimarezainia

**Comment by nimarezainia** [comment]
Hi @111andre111,
is your request here for us to change a release note from a past release? i understand the slight ambiguity here but all the public issues referring to this are saying "removed". I'm less inclined to make these changes right now for an older release. Could we wait and see if there are other users affected by this? thx

**Comment by 111andre111** [comment]
Yes, it's about the documentation pages. I know it's on an older release page, however I don't think it's a very good representative exposure, if there are ambiguous information on the documentation pages.
