### ISSUE TITLE
Support dots in keys of processor conditions

### ISSUE THREAD

**Issue by superdump** [elastic/beats#2921]
- Version: 5.0.0
- Operating System: N/A

docker-compose adds labels to every container it creates. If your docker log driver is configured to add those labels into the log file, they are placed under an `attrs` key such as:

```
    "attrs": {
      "com.docker.compose.service": "filebeat",
...
    },
```

Note that the key `com.docker.compose.service` contains dots.

If you then try to configure a processor to drop events from filebeat itself to avoid any possibility of a feedback loop, you cannot currently do so because of the way the conditional fields unpacker is implemented: https://github.com/elastic/beats/blob/81d4e25c8895cc267532f08375d8e46fd5dae5b7/libbeat/processors/config.go#L30-L59

It looks like there is no way to specify something like `"attrs['com.docker.compose.service']"` as the key and have the value be properly looked up. Simply using `attrs.com.docker.compose.service` will not work and nor will:
```
processors:
  - drop_event:
    when:
      equals:
        attrs:
          'com.docker.compose.service': filebeat
```

...as the unpacker will concatenate `attrs` with `.` and `com.docker.compose.service` resulting in an incorrect reference.

**Comment by andrewkroh** [comment]
Thanks for reporting the problem. I think the issue here is with [`MapStr.GetValue()`](https://github.com/elastic/beats/blob/master/libbeat/common/mapstr.go#L94) which interprets the dots to mean nested objects. I will look into this and propose a solution.

**Comment by andrewkroh** [comment]
The processor hasn't been changed yet, but Docker labels have (#3024). Labels are now put into an object instead of an array and the keys are de-dotted (`s/./_/g`).

See labels in sample event: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-metricset-docker-container.html

**Comment by cytim** [comment]
It would be very nice to support dotted fields in the processors. I am using Kubernetes to orchestrate my applications. It also adds dotted labels to the containers. I want to make use of the labels to drop some of the logs collected by Filebeat. Currently I have to drop the events by Logstash, which is not optimal because I have a lot of logs from a lot of servers.

**Comment by jlind23** [comment]
Backlog grooming: Closing for now until further activity, can still be reopened if needed
