### ISSUE TITLE
[Filebeat] Microsoft DHCP module not parsing logs

### ISSUE THREAD

**Issue by pemontto** [elastic/beats#29221]
Following up from this discussion that was never resolved - https://discuss.elastic.co/t/parsing-windows-dhcp-logs-with-filebeat-microsoft-module/254814/6

It appears the Microsoft DHCP module is not parsing some (all?) DHCP logs correctly. Instead the event gets returned with a `dissect_parsing_error` flag.
I'd usually get stuck into the processing code, but this autogenerated code is a little too intense to reason about for me:
https://github.com/elastic/beats/blob/master/x-pack/filebeat/module/microsoft/dhcp/config/liblogparser.js
https://github.com/elastic/beats/blob/master/x-pack/filebeat/module/microsoft/dhcp/config/pipeline.js

Sample config:
```yaml
filebeat.modules:
  - module: microsoft
    defender_atp.enabled: false
    m365_defender.enabled: false
    dhcp:
      enabled: true
      var.input: file
      var.paths:
        - /tmp/*.log
```

Sample data `/tmp/test.log`:
```csv
		Microsoft DHCP Service Activity Log


Event ID  Meaning
00	The log was started.
01	The log was stopped.
02	The log was temporarily paused due to low disk space.
10	A new IP address was leased to a client.
11	A lease was renewed by a client.
12	A lease was released by a client.
13	An IP address was found to be in use on the network.
14	A lease request could not be satisfied because the scope's address pool was exhausted.
15	A lease was denied.
16	A lease was deleted.
17	A lease was expired and DNS records for an expired leases have not been deleted.
18	A lease was expired and DNS records were deleted.
20	A BOOTP address was leased to a client.
21	A dynamic BOOTP address was leased to a client.
22	A BOOTP request could not be satisfied because the scope's address pool for BOOTP was exhausted.
23	A BOOTP IP address was deleted after checking to see it was not in use.
24	IP address cleanup operation has began.
25	IP address cleanup statistics.
30	DNS update request to the named DNS server.
31	DNS update failed.
32	DNS update successful.
33	Packet dropped due to NAP policy.
34	DNS update request failed.as the DNS update request queue limit exceeded.
35	DNS update request failed.
36	Packet dropped because the server is in failover standby role or the hash of the client ID does not match.
50+	Codes above 50 are used for Rogue Server Detection information.

QResult: 0: NoQuarantine, 1:Quarantine, 2:Drop Packet, 3:Probation,6:No Quarantine Information ProbationTime:Year-Month-Day Hour:Minute:Second:MilliSecond.

ID,Date,Time,Description,IP Address,Host Name,MAC Address,User Name, TransactionID, QResult,Probationtime, CorrelationID,Dhcid,VendorClass(Hex),VendorClass(ASCII),UserClass(Hex),UserClass(ASCII),RelayAgentInformation,DnsRegError.
17,11/20/20,00:00:05,DNS record not deleted,10.0.0.1,,,,0,6,,,,,,,,,0
30,11/20/20,00:00:05,DNS Update Request,10.0.0.2,hostname.contoso.com,,,0,6,,,,,,,,,0
30,11/20/20,00:00:05,DNS Update Request,10.0.0.3,hostname.contoso.com,,,0,6,,,,,,,,,0
31,11/20/20,00:00:05,DNS Update Failed,10.0.0.4,hostname.contoso.com,,,0,6,,,,,,,,,9005
24,11/15/21,00:00:06,Database Cleanup Begin,,,,,0,6,,,,,,,,,0
25,11/15/21,00:00:06,0 leases expired and 0 leases deleted,,,,,0,6,,,,,,,,,0
11,11/15/21,00:00:09,Renew,10.0.0.127,testhost1.example.com,01234123,,091234109,0,,,,0xDEADBEEF,MSFT 5.0,,,,0
11,11/15/21,00:29:56,Renew,10.0.0.129,testhost1.example.com,01234123,,091234101,0,,,,,,,,,0
24,11/15/21,00:52:21,Database Cleanup Begin,,,,,0,6,,,,,,,,,0
25,11/15/21,00:52:21,0 leases expired and 0 leases deleted,,,,,0,6,,,,,,,,,0
11,11/15/21,00:56:45,Renew,10.0.0.115,testhost6.example.com,01234123,,091234101,0,,,,0xDEADBEEF,MSFT 5.0,,,,0
11,11/15/21,00:56:46,Renew,10.0.0.111,testhost2.example.com,01234123,,091234105,0,,,,0xDEADBEEF,MSFT 5.0,,,,0
11,11/15/21,00:56:47,Renew,10.0.0.119,testhost4.example.com,01234123,,091234100,0,,,,0xDEADBEEF,MSFT 5.0,,,,0
```

**Comment by jamiehynds** [comment]
@pemontto we are about to ship a new DHCP integration with Elastic Agent, which includes much improved ECS mappings over the experimental module, along with an ingest pipeline for centralised processing. Is this something that you'd be willing to adopt? Note that the integration is only available via agent, not standalone beats. 

https://github.com/elastic/integrations/tree/master/packages/microsoft_dhcp

**Comment by pemontto** [comment]
@jamiehynds thanks for the prompt response. We're currently using Filebeat to load offline with log files on a Linux host. So if that's a supported deployment for the agent then sure.

Taking a quick peek this looks as if it moves the processing load onto the ES hosts, rather than at the agent/filebeat, is that correct? Regardless the [pipeline.yml](https://github.com/elastic/integrations/blob/master/packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/default.yml) is very useful, I've nabbed parts from that for our current Filebeat pipeline 🙌

**Comment by jamiehynds** [comment]
@pemontto by default, the integration points to C:\Windows\System32\DHCP\DhcpSrvLog-*.log for the DHCP logs, but if those .log files are being transferred to a Linux host, you could deploy the agent to that host and change the path in the integration config. 

Correct, re the processing load - it's all done through Ingest Node. We had another user leverage the pipeline recently, by just converting from yml to json and dropping our pipeline into a custom pipeline - https://elasticstack.slack.com/archives/CNEDGGJQ3/p1638201494373000

**Comment by andrewkroh** [comment]
We have an issue for dhcpv6. https://github.com/elastic/integrations/issues/2136
