### ISSUE TITLE
Winlogbeat NewProcessFields Function Missing Parent Process

### ISSUE THREAD

**Issue by veritasr3x** [elastic/beats#29237]
Hi Elastic Team ,

Github issue approval noted in [Elastic Discussion Forums](https://discuss.elastic.co/t/winlogbeat-newprocessfields-function-missing-parent-process/289679).

I'm writing to request an update to the winlogbeat [Windows Security module](https://github.com/elastic/beats/blob/master/x-pack/winlogbeat/module/security/config/winlogbeat-security.js) to add the parent process ID value for Windows Security event 4688.

Lines 2132 to 2142 handle field renames for parent/child process fields in 4688:

```var renameNewProcessFields = new processor.Chain()
        .Convert({
            fields: [
                {from: "winlog.event_data.NewProcessId", to: "process.pid", type: "long"},
                {from: "winlog.event_data.NewProcessName", to: "process.executable"},
                {from: "winlog.event_data.ParentProcessName", to: "process.parent.executable"}
            ],
            mode: "rename",
            ignore_missing: true,
            fail_on_error: false,
        })
```
The parent process ID is missing from the function, which affects Windows Security Event 4688. Looking at a raw sample for a 4688, the parent process in **friendly view** is re-labeled by Microsoft as _Creator Process ID_. However, the XML shows the parent process ID structured as _ProcessId_:

![image](https://user-images.githubusercontent.com/4089369/144331096-a19765d1-4744-4d78-a057-bf06f62b5448.png)

The winlogbeat security module variable _event4688_ references the _renameNewProcessFields_ function and is the only variable that does, so I propose the _renameNewProcessFields_ function be updated to include the parent process PID:

```var renameNewProcessFields = new processor.Chain()
        .Convert({
            fields: [
                {from: "winlog.event_data.NewProcessId", to: "process.pid", type: "long"},
                {from: "winlog.event_data.NewProcessName", to: "process.executable"},
                {from: "winlog.event_data.ParentProcessName", to: "process.parent.executable"}
                {from: "winlog.event_data.ProcessId", to: "process.parent.pid"}  //<---updated line
            ],
            mode: "rename",
            ignore_missing: true,
            fail_on_error: false,
        })
```

Since it's an event-dependent variable reference, the context will only be invoked for 4688s and not conflict with any others. 

label:Team:Elastic-Agent 
#

**Comment by efd6** [comment]
This should have been autoclosed by #31102.
