### ISSUE TITLE
[Processors] Add named range to network condition for host's IPs

### ISSUE THREAD

**Issue by a03nikki** [elastic/beats#29267]
**Describe the enhancement:**

https://www.elastic.co/guide/en/beats/auditbeat/7.15/defining-processors.html#condition-network
> **network**
> The network condition checks if the field is in a certain IP network range. Both IPv4 and IPv6 addresses are supported. The network range may be specified using CIDR notation, like "192.0.2.0/24" or "2001:db8::/32", or by using one of these named ranges:
> ...

It would be great if we could have a named range for the IP addresses assigned to a host.

**Describe a specific use case for the enhancement or feature:**

It would be great if we could exclude (aka [`drop_event`](https://www.elastic.co/guide/en/beats/auditbeat/7.15/drop-event.html)) not only the process communication on the loopback addresses (aka localhost) but communication between processes using the local host's IP address.  

For example, `host_ip` would exclude the host's IP address is `172.16.3.17` (which would be `172.16.3.17/32` by CIDR notation I believe):

```yaml
processors:
  - drop_event:
      when:
        network:
          destination.ip: [loopback, host_ip]
```

A work around could be #29266 or #29269, if we could compare source and destination IP addresses on events shipped by the Beats.  Another work around would be to manually add the host's IPs using config management tool (e.g. Puppet, Ansible, etc.) to add the ranges such as `172.16.3.17/32` to the list.

**Comment by legoguy1000** [comment]
`loopback` is already included https://github.com/elastic/beats/blob/055798ae3561da8cbb4749984d1ff57964fbee2f/libbeat/conditions/network.go#L46. other host ips not yet.
