### ISSUE TITLE
[Agents]: Agent is installed even if user passes "install agent as a service" confirmation as blank while running agent install command.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#29285]
**Kibana version:**  7.16.0 BC-7 Kibana Cloud environment

**Host OS:** All

**Build details:**
```
Build: 46197
Commit: b7b724b4f677db8b3ca0b7d5a35a822fef9766a0
Artifact Link: https://staging.elastic.co/7.16.0-e4040d4f/downloads/beats/elastic-agent/elastic-agent-7.16.0-windows-x86_64.zip
```

**Steps to reproduce:**
1. Download and extract elastic-agent artifact.
2. Run agent install command and observe confirmation:
`Elastic Agent will be installed at C:\Program Files\Elastic\Agent and will run as a service. Do you want to continue? [Y/n]:`
3. Press "Enter" without filling `Y/n`.
4. Observe agent is still installed successfully.

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/144824230-fdb0f791-deb2-4b8d-9808-2d4f727a0478.JPG)
![2](https://user-images.githubusercontent.com/77374876/144824234-c4b8ac69-5310-447f-8597-082eb60a3d08.JPG)
![3](https://user-images.githubusercontent.com/77374876/144824288-21279dd8-a3f4-43a7-af0b-bc2407317d3b.JPG)

**Expected Result:**
Agent should not be installed if user passes "install agent as a service" confirmation as blank while running agent install command.
- If validation is there, it must accepts a "y" for confirming agent install.

**NOTE:**
- No impact on agent working is observed.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @elastic/elastic-agent-control-plane 

CC: @EricDavisX

**Comment by blakerouse** [comment]
@manishgupta-qasource As you see there the `[Y/n]` the capital `Y` means that `Y`(aka. Yes) is default. So pressing enter is the expected behavior and matches standard CLI design.

If we want to change the default to `N` that is different but the `Y` is default and shown in the output correctly.

**Comment by amolnater-qasource** [comment]
Hi @blakerouse 
Thanks for confirming the expected functionality.
We have this information to our testcase at link: [C33948](https://elastic.testrail.io/index.php?/cases/view/33948)

Hence, **closing** this as resolved.
Thanks
