### ISSUE TITLE
Failing test test_dev_tool_export_dashboard_by_id_from_space

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#29327]
This test fails since some change in the stack, it was found in automated PRs for snapshots used in testing, seen at least https://github.com/elastic/beats/pull/29275 (master) and https://github.com/elastic/beats/pull/29277 (8.0), it seems to work with older images.

The test is: [`libbeat/tests/system/test_dashboard.py::Test::test_dev_tool_export_dashboard_by_id_from_space`](https://github.com/elastic/beats/blob/16d587b7338b5d37bf5ad81cb58c2311d7996182/libbeat/tests/system/test_dashboard.py#L213)

We have to confirm if this is expected due to some breaking change in 8.0, or if this is an actual issue.

**Comment by cmacknz** [comment]
I've been working on this in the background as way to understand the system tests. This test starts failing somewhere between these two versions of Kibana:

| Status | Container                    | Date     | Commit |
|--------|------------------------------|----------|--------|
| PASSES |kibana:8.0.0-3d27fc14-SNAPSHOT|2021-10-21|6c52cce0b854b144794d3278b23358d77c1e0592|
| FAILS |kibana:8.0.0-0ab1fe1f-SNAPSHOT |2021-10-29|2424ff2879acc18cb6c4e58a5ffa3efa69e313ed|

I haven't had a chance to bisect further to find the commit where it starts failing.
