### ISSUE TITLE
[Filebeat] gcppubsub input can stop unexpectedly

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#29352]
The gcppubsub input sometimes stops due to a timed-out context. Our input code does not use timed contexts AFAIK so I suspect the issue lies with the pubsub library. The library is supposed to automatically retry `Receive` calls as per https://pkg.go.dev/gocloud.dev/pubsub#Subscription.Receive.

So as a solution I think we can do two things:

- ✅ Upgrade the pubsub library from v1.0.1 to the latest on the hopes that this issue has been addressed.
- 🚫 Add our own retry loop with backoff that will continue the subscription.Receive call. (update: library update alone appears to be a reliable fix)

For confirmed bugs, please report:
- Version: 7.15.2
- Steps to Reproduce:
1. Configure pubsub input.
2. Let it run for a few days.
3. Input will stop.

`2021-11-09T14:37:40.604Z ERROR [gcp.pubsub] gcppubsub/input.go:141 context deadline exceeded`
`2021-11-09T14:37:40.604Z INFO [gcp.pubsub] gcppubsub/input.go:142 Pub/Sub input worker has stopped. `

Relevant code:

https://github.com/elastic/beats/blob/545598f48058408996529af3252b1b28d6dbf53d/x-pack/filebeat/input/gcppubsub/input.go#L168-L174

**Comment by andrewkroh** [comment]
PR to update pubsub library: https://github.com/elastic/beats/pull/29353

**Comment by efd6** [comment]
@andrewkroh Is this fixed now?

**Comment by andrewkroh** [comment]
Yeah, the library update alone was able to fix it.
