### ISSUE TITLE
[libbeat] Elasticsearch output validation may data loss

### ISSUE THREAD

**Issue by trixpan** [elastic/beats#2935]
For confirmed bugs, please report:
- Version: Filebeat 5
- Operating System: Centos 6
- Steps to Reproduce: 

1. setup filebeat with ES output and any input you want
2. use any simple HTTP server to respond requests so that:

GET request (ES ping) contain at least:

```
{
  "status" : 200,
  "name" : "",
  "cluster_name" : "Search",
  "version" : {
    "number" : "1.7.3",
    "build_hash" : "void",
    "build_timestamp" : "void",
    "build_snapshot" : false,
    "lucene_version" : "void"
  },
  "tagline" : "You Know, for Search"
}
```

3. chose between responding POST requests with:

a. Plain 200: filebeat will warn about missing "items" node in response but data will be consider sent

b. JSON message data will be seen as delivered but without warning:
```
{
   "took": 4,
   "errors": false, 
   "items": []
}
```

**Comment by andrewkroh** [comment]
I believe the behavior is still them same in the current version.

https://github.com/elastic/beats/blob/v6.4.0/libbeat/outputs/elasticsearch/client.go#L457-L480

**Comment by tsg** [comment]
I'll close this issue as it's quite old and I'm not sure if this is something that we'd want to fix.
