### ISSUE TITLE
[Question]: Auto configuration error on running elasticsearch.bat for VSphere VMs.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#29389]
**Reference ticket:** https://github.com/elastic/obs-dc-team/issues/668

**Build details:**
8.0 self-managed kibana environment
Build: 48703
Commit: a739f060ba0b563a157d640a7a7eb90ceb573811

**Steps followed:**
1. Setup elasticsearch and kibana for 8.0.0-Snapshot.
2. Below attached yml files used.
[yml files.zip](https://github.com/elastic/beats/files/7701893/yml.files.zip)
3. As per doc shared at https://docs.google.com/document/d/1ZzRkmArQex2PCiXmqfnrFkyIui4vMDoJlMGnwy9mGyA/edit#
and as per reference ticket shared.
we didnt get expected Fingerprint token on running elasticsearch.
4. We attempted to check filebeat.yml 
**Expected:**
```
output.elasticsearch:
  hosts: ["<es_url>"]
  username: "elastic"
  password: "<password>"
  ssl.ca_sha256: "<es_cert_fingerprint>"
setup.kibana:
  host: "<kibana_url>"
```
**Actual:**
![6](https://user-images.githubusercontent.com/77374876/145773429-2e401892-a861-49ac-acc2-062b66725fd8.JPG)

## Questions:

1. Is this testable on latest available 8.0 self-managed snapshot as the related tickets are merged.
2. Could you please confirm if we need to add any specific configuration into the elasticsearch.yml?
As per doc, it is expected to get enrollment token for Kibana instances and the hex-encoded SHA-256 fingerprint on running elasticsearch.
3. We even attempted to add xpack: xpack.security.enrollment.enabled: true to elasticsearch.yml.
We run elasticsearch-create-enrollment-token -s kibana and got below errors:
![7](https://user-images.githubusercontent.com/77374876/145776766-16dfc5a3-9636-4533-bcf5-0c7f8adee67b.JPG)
Could you please confirm if we need to create certificates for this?

Please let us know if we are missing anything.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @jlind23

**Comment by jlind23** [comment]
@mostlyjason wasn't Elasticsearch supposed to be secure by default? What parameter should we change to perform those tests?

**Comment by mostlyjason** [comment]
Yes ES is secure by default. @amolnater-qasource are you checking the beats configuration on the beats tutorial page? Try navigating to `/app/home#/tutorial/activemqLogs` to see if it matches there.

**Comment by amolnater-qasource** [comment]
Hi @mostlyjason 
Thanks for looking into this.
We have have checked filebeat configuration under `/app/home#/tutorial/activemqLogs` and observed below configuration:
![5](https://user-images.githubusercontent.com/77374876/146366461-f2754e59-ab8b-4a3d-b0c4-2f159b23c91a.JPG)

**Build details:**
Build: 48594
Commit: ad3660f3acbfe6eb809d869b908221edf2846313

Please let us know if we are missing anything.
Thanks

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have attempted to deploy a 8.0 Snapshot self-managed setup on AWS- Windows2019 server base instance.
We got expected details on running `elasticsearch.bat`:
![7](https://user-images.githubusercontent.com/77374876/146495314-1c340152-7032-4e36-9738-fb5f62badce4.JPG)

Further in the end we started receiving below warnings:
![6](https://user-images.githubusercontent.com/77374876/146495372-0fd8a7b4-2af5-409d-807b-54506f9a1350.JPG)

**Due to this we were unable to login to `http://localhost:9200`, however when we searched for `https://localhost:9200` we were able to login to elasticsearch.**

As per process when we run kibana.bat, we observed below errors:
![10](https://user-images.githubusercontent.com/77374876/146495591-82b04511-c102-4b6b-80fd-7396a7f25a22.JPG)

Could you please check and confirm if we are missing anything?

**elasticsearch.yml:**
[elasticsearch.zip](https://github.com/elastic/beats/files/7732335/elasticsearch.zip)

**kibana.yml:**
[kibana.zip](https://github.com/elastic/beats/files/7732336/kibana.zip)
(modified to resolve some errors like `Error connecting to http://localhost:9200`)
**NOTE:**
- We only got these expected details on aws-VMs and **not on VSphere VMs**. 

Is there any such system constraint?

cc: @mostlyjason 

Thanks

**Comment by amolnater-qasource** [comment]
Hi
Further update regarding below scenario:
>We only got these expected details on aws-VMs and not on VSphere VMs.

For VSphere VMs, we are getting auto configuration error on running elasticsearch.bat
![2](https://user-images.githubusercontent.com/77374876/146754237-d8707c16-008e-4ea8-9967-e0220147921c.JPG)
 

These errors are not observed for AWS VMs on running elasticsearch.bat

Further we are attempting to troubleshoot on AWS-instance regarding the shared error at https://github.com/elastic/beats/issues/29389#issuecomment-996464943

We will be sharing any details here if we got any success.
Thanks

**Comment by jlind23** [comment]
@amolnater-qasource As far as i can tell there is no such system constraint. @michel-laterman @blakerouse does it sound familiar?

**Comment by nchaulet** [comment]
Hi @amolnater-qasource Unfortunately to have the fingerprint correctly setup you need to use the Kibana interactive setup tool from the UI or the CLI with the enrollment token did you use it here? 



Just tested it with the latest 8.0 SNAPSHOT with the following instruction 

<details>

Running `./bin/elasticsearch` you should get
<img width="1627" alt="Screen Shot 2021-12-20 at 2 11 00 PM" src="https://user-images.githubusercontent.com/1336873/146820385-8d9f419f-f36b-45e5-a3d7-a84aa73c998a.png">

Then running `./bin/kibana` with nothing configured you should get
<img width="448" alt="Screen Shot 2021-12-20 at 2 15 24 PM" src="https://user-images.githubusercontent.com/1336873/146820435-9c829cb1-6b7b-431b-8e97-5d7c326f9eaa.png">

And here you follow the link to do the setup with the enrollment token.


</details>

**Comment by amolnater-qasource** [comment]
Hi @nchaulet 
Thanks for the feedback.
Now we are successfully able to setup Kibana using Kibana enrollment token on AWS Windows 2019 base. 
![7](https://user-images.githubusercontent.com/77374876/146883331-d6e54a85-5925-414e-aa5b-8f5e818c2171.JPG)

>@amolnater-qasource As far as i can tell there is no such system constraint.
 
Thanks @jlind23 for looking into this, we have shared the error line on only VSphere VM at https://github.com/elastic/beats/issues/29389#issuecomment-997819141

Further as shared above we are able to setup kibana with new changes. Hence we will be continuing our testing related to beats and agents installation using fingerprint settings on the same.

Thanks

**Comment by amolnater-qasource** [comment]
As the issue for beats is resolved and further testing results are shared at https://github.com/elastic/observability-test-plans/issues/249#issuecomment-998579743

We are updating the title for the discussion regarding VSphere auto configuration issue.

**Comment by jlind23** [comment]
@amolnater-qasource for the VSphere configuration, did you face it only in 8.0 or was it an issue you were already facing?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
Before 8.0, we used to manually change the `elasticsearch.yml` and `kibana.yml` for self-managed kibana setup.
While setting up 8.0 self-managed kibana on AWS, we observed that yml files now auto-configures during setup.

However on running the same on VSphere machine, we observed `Error: Aborting AUTO Configuration.`

Due to this we are not able to test Security on by default feature https://github.com/elastic/observability-test-plans/issues/249 on VSphere VMs, as kibana setup is done without enrollment token.

Thanks

**Comment by jlind23** [comment]
@amolnater-qasource looking at the logs it rather seems to be an elasticsearch auto config feature, am i correct? If yes, we should rather open an issue on their side then.

**Comment by amolnater-qasource** [comment]
Yes @jlind23 this is related to the elasticsearch auto config feature, which is working fine on AWS VMs and not working the same way on VSphere VMs.
We have logged an issue for this issue at https://github.com/elastic/elasticsearch/issues/82073

Hence we are **closing** this.
Thanks for looking into the same.

**Comment by CYANIDE-7** [comment]
> Hi Further update regarding below scenario:
> 
> > We only got these expected details on aws-VMs and not on VSphere VMs.
> 
> For VSphere VMs, we are getting auto configuration error on running elasticsearch.bat ![2](https://user-images.githubusercontent.com/77374876/146754237-d8707c16-008e-4ea8-9967-e0220147921c.JPG)
> 
> These errors are not observed for AWS VMs on running elasticsearch.bat
> 
> Further we are attempting to troubleshoot on AWS-instance regarding the shared error at [#29389 (comment)](https://github.com/elastic/beats/issues/29389#issuecomment-996464943)
> 
> We will be sharing any details here if we got any success. Thanks

I am facing the same issue please guide me to solution
