### ISSUE TITLE
Metricbeat: Github repository does not contain kibana dashboards

### ISSUE THREAD

**Issue by svanschalkwyk** [elastic/beats#29414]
Dashboards can be downloaded from the DEB/RPM...gz page though.

For confirmed bugs, please report:
- Version: 7.15/16
- Operating System: 
- Discuss Forum URL:
- Steps to Reproduce: git clone...

**Comment by kaiyan-sheng** [comment]
Hello, kibana dashboard in github is under each module. Which metricbeat dashboard are you looking for specifically?
