### ISSUE TITLE
Add ability to load sample dashboards for modules selectively

### ISSUE THREAD

**Issue by jamiejackson** [elastic/beats#29427]
> **The enhancement:** In Filebeat, it would be nice if we were able to specify which of the included sample dashboards we want to load, possibly by module. This can be done in either of the following ways:
> 
> 1. Provide a config option, say, `setup.dashboards.files`, that lets you specify the files you want to load (`Filebeat-nginx-logs.json,Filebeat-nginx-overview.json`), or:
> 2. Organise the dashboards within the local `kibana/7/dashboards` directory in sub-directories by module. This would allow us to use the existing `setup.dashboards.directory` option.
> 
> **Use case for the enhancement or feature:** I want to make use of the included Filebeat sample dashboards, but only the ones for Nginx, since that is the only module I'm using. Altogether, there are 139 sample dashboards, which is going to make navigation somewhat more confusing and stressful for other team members. I'm running Filebeat via Docker (Kubernetes). While I can modify the `cmd` so it reorganizes the dashboards as in (2) above, I would prefer not to.

----

Note: I'm ripping off @shalvah's description/title because stalebot closed #12167

**Comment by jsoriano** [comment]
Reopening the old one.
