### ISSUE TITLE
Metricbeat Docker module doesn't shutdown immediatelly

### ISSUE THREAD

**Issue by tsg** [elastic/beats#2944]
Terminating Metricbeat with the docker module loaded doesn't seem to work until one `period` passes.

To reproduce:

* Do a basic configuration like:

```
- module: docker
  metricsets: ["cpu", "info", "memory", "network", "diskio", "container"]
  enabled: true
  period: 10s
  #hosts: ["localhost"]
  socket: unix:///var/run/docker.sock
```

* Start metricbeat
* Press ^C

Happens:
* It takes up to 10s for metricbeat to shutdown

**Comment by ruflin** [comment]
The reason metricbeat does not directly shutdown is that fetching the docker stats takes at least 2 seconds: https://github.com/docker/docker/blob/master/cli/command/container/stats_helpers.go#L148 Unfortunately for a longer list of containers this can take a lot more time. We should find a way to stop the fetching loop.

**Comment by ruflin** [comment]
Closing this as the docker client is now setup with a timeout means it will block only based on the timeout and not until all is completed.
