### ISSUE TITLE
[Elastic Agent] Winlog input shows as beta 

### ISSUE THREAD

**Issue by nimarezainia** [elastic/beats#29464]
During debugging for an SDH in the following attached logs we see:  "BETA: The winlog input is beta","service.name"

Winlog input in not beta and this message should be corrected.

{"log.level":"info","@timestamp":"2021-11-24T18:54:23.886Z","log.logger":"crawler","log.origin":{"file.name":"beater/crawler.go","file.line":71},"message":"Loading Inputs: 2","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-11-24T18:54:23.887Z","log.logger":"crawler","log.origin":{"file.name":"beater/crawler.go","file.line":108},"message":"Loading and starting Inputs completed. Enabled inputs: 0","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-11-24T18:54:23.887Z","log.origin":{"file.name":"cfgfile/reload.go","file.line":164},"message":"Config reloader started","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-11-24T18:54:23.888Z","log.origin":{"file.name":"cfgfile/reload.go","file.line":224},"message":"Loading of config files completed.","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-11-24T18:54:23.994Z","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"management/manager.go","file.line":150},"message":"Status change to Configuring: Updating configuration","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-11-24T18:54:24.003Z","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"management/manager.go","file.line":271},"message":"Applying settings for filebeat.inputs","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2021-11-24T18:54:24.007Z","log.logger":"input","log.origin":{"file.name":"v2/loader.go","file.line":104},"message":"BETA: The winlog input is beta","service.name":"filebeat","input":"winlog","stability":"Beta","deprecated":false,"ecs.version":"1.6.0"}

**Comment by jlind23** [comment]
It has been updated here: https://github.com/elastic/integrations/commit/bad54e28a4e23502579bab2cf35e8d4627fc943a#diff-a75499ba2e478781b55ec6d46ea3d10049586e83ba214089bf0b906eb8cfe269
