### ISSUE TITLE
Enable the FileBeat Checkpoint module to read encrypted messages

### ISSUE THREAD

**Issue by martha-vargas** [elastic/beats#29481]
**Describe the enhancement:** 
Enable the FileBeat Checkpoint module to read encrypted messages

**Describe a specific use case for the enhancement or feature:**
We need to send encrypted log messages from a CheckPoint firewall over the network to the CheckPoint module.

This is the configuration done:

```
filebeat.modules:

module: checkpoint
firewall:
enabled: true
var.syslog_host: 0.0.0.0
var.syslog_port: 9001
var.ssl:
enabled: true
certificate_authorities: ["/data/certs/my-ca.pem"]
certificate: "/data/certs/filebeat-cert.pem"
key: "/data/certs/filebeat-key.pem"
client_authentication: "required"
```

This is how the message appears in Kibana:

```
message
�/�+�'�#�� �=5�</��
```

**Comment by legoguy1000** [comment]
Are u asking about TLS encrypted TCP (syslog) messages or is the message itself encrypted? Looking at the module config, it already supports TLS syslog.

**Comment by jamiehynds** [comment]
Closing as the Check Point module and integration both support TLS syslog.
