### ISSUE TITLE
[Heartbeat] Stop appending ` - inline` to monitors

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/beats#29505]
It makes sense that for the nested behaviour of suites, the suite name and journey name are concatenated (with ` - ` in between).  We also currently append ` - inline` to inline scripts (such as from the `heartbeat.yml`, or when using the inline flow as part of a Fleet Integration).

This isn’t really adding anything useful anymore, and also complicates the flow when using the Script Recorder, which under the hood, currently implements this as an inline script (so may be confusing to a user, as they didn’t use the inline flow, but the monitor gets named as such).

ACs:
* Do not append ` - inline` to any kind of monitor
  * Both the name and the `id`
  * Coordinate a change in Kibana to be done at the same time (Kibana currently expects the `id` to be `uuid-inline`)
* Do not change the behaviour for suites, keep them concatenating the suite / journey name as it does now
* Empty first document emitted by browser monitors no longer appears (also for suites) (it seems like we send an empty event to the wrappers)

**Comment by paulb-elastic** [comment]
Updated the description to clarify that this should be removed from the name and the `id`.

**Comment by shahzad31** [comment]
POST FF, Verified via service ran monitors, it's not appending --inline any more.

**Comment by BenB196** [comment]
Just an FYI, this doesn't seem to have been marked as a breaking change, but in pre-7.17, if you had rules setup to monitor via the `monitor.id` field or ML jobs which used the field. This silently broke the functionality here, as the `monitor.id` changed.

**Comment by andrewvc** [comment]
Apologies for that Ben.

I haven't had a chance yet to dive into how exactly this happened, but I'm pretty sure the issue here is that we made this change in the 'synthetics' library, which is called by heartbeat, but which wouldn't be reflected in beats changelogs. 

We'll have a discussion on this and try to find ways to surface these breaking changes better. This sort of thing shouldn't happen much anymore, but it probably will come up again at some point, and we'll need to track changes that are sort of non-breaking on one project but cause a breaking change in another.

**Comment by andrewvc** [comment]
I'll also mention that we don't make these changes in GA projects except in extreme cases, but for beta products we occasionally make these breaking changes if they significantly enhance the UX. Once again sorry for not communicating this as we should have

**Comment by BenB196** [comment]
Yeah, understandable that it's a `beta` product and is subject to breaking changes during minor releases (kind of expect it as it shows the product being refined). Guess like you kind of said, just a nice-to-have communication for "beta testers" to be able to understand/anticipate the changes.
