### ISSUE TITLE
Create Getting Started checklist

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#2952]
Users new to the stack frequently encounter the same problem. Be it indentation of YAML, EOF connecting to LS or SSL problems. We should provide these users a checklist they can go through to debug their issue. This will save us time answering always the same question on discuss and will allow the user to figure out the problem on its own without having to wait on an answer.

**Comment by dedemorton** [comment]
@ruflin Would this checklist also cover the Kibana side?

**Comment by ruflin** [comment]
@dedemorton Potentially. I think the checklists could be connected. You start with an initial question like: Data does not show up in Kibana -> did you check ... So probably it is more then 1 checklist.

**Comment by dedemorton** [comment]
@ruflin It sounds like what you're talking about is more of a troubleshooting checklist. So I'd suggest adding it to the troubleshooting section and pointing to the topic at the end of the getting stated maybe.

**Comment by dedemorton** [comment]
@ruflin Do you still think this is required now that we have things like modules and the solution pages to get new users up and running? This one has been open for awhile.

**Comment by ruflin** [comment]
I think we still need something like this. Perhaps the title is a bit misleading and it's more a "getting started debug checklist". I have a page in mind where we can point people to on discuss that have the top 5 issues on how to solve them. 2 examples:

* YAML Indentation -> how to validate it's a valid yaml file and compare it to reference file for indentation
* Connection to ES / LS -> we actually have tools now in each beat to validate this

This should reduce our overhead on answering the same questions again and again. I think there are more points here. I wonder where we should put this.
