### ISSUE TITLE
Allow dashboards to be created by Elasticsearch server

### ISSUE THREAD

**Issue by ephracis** [elastic/beats#2954]
We have a set up where Elasticsearch runs on a single server and the only server allowed to access it is the Logstash server.

When this server is deployed we would like it to be automatically populated with dashboard for metricbeat and winlogbeat. For metricbeat we just download the import_dashboard tool and run it. But the same tool for winlogbeat is an exe file and must therefore be executed on a Windows machine, however no such machine has access to the Elasticsearch server.

It would be nice if the import tools are available for more platforms than just the platform that the beats package is available on.

**Comment by tsg** [comment]
The `import_dashboard` tool is actually the same for all Beats, just the default for the `-beat` parameter is changed. Simply run it with `./import_dashboard -beat winlogbeat` and it should work for you.

Closing the ticket at the moment as a question. Feel free to reopen if there's still an enhancement request you want.
