### ISSUE TITLE
[Filebeat]: `enable system` available in docs for windows, it doesn't support filebeat system module.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#29568]
**Elastic guide:** https://www.elastic.co/guide/en/beats/filebeat/7.16/filebeat-installation-configuration.html
**Description:**
Modules enable command for filebeat installation on windows available in docs is: `.\filebeat.exe modules enable system nginx mysql`
However when we enable system module on Windows OS we are unable to start Filebeat Service.
**On 7.16.1 and below:**
![8](https://user-images.githubusercontent.com/77374876/145945818-f9706c39-8687-4527-8cb4-496f8f800746.JPG)

**On 8.0-Snapshot:**
We attempted on self-managed environment, we are able to run filebeat service with system module enabled, however no data for under Discover tab for filebeat-* index.

Further under system.yml we observed below filesets:
![9](https://user-images.githubusercontent.com/77374876/145946156-427896ac-6fee-4320-a485-08a3a3d82ce0.JPG)

As per our understanding Windows OS doesn't support these system filesets, just like we don't get system.syslog and system.auth datastreams for System integration with Windows agent.

Hence from elastic-guide below section should be updated for filebeat installation on windows:
![10](https://user-images.githubusercontent.com/77374876/145946515-4ef288a7-3f0f-4428-b921-6b868a948b22.JPG)

**Comment by amolnater-qasource** [comment]
Thanks for looking into this @jlind23 and @dedemorton 

Further it would be great if we can add a note about system module not working/compatible with Filebeat on windows OS.
We will be revalidating elastic-guide whenever this will be updated.

Thanks

**Comment by dedemorton** [comment]
The module docs already say:

"The system module collects and parses logs created by the system logging service of common Unix/Linux based distributions."

Do you think it's necessary to add, "This module does not work with Windows."

**Comment by amolnater-qasource** [comment]
Hi @dedemorton 
We have revalidated the docs for filebeat installation and found it **fixed** now.
- Enable system module is removed from filebeat installation guide.

**Screenshot:**
![15](https://user-images.githubusercontent.com/77374876/148188909-49c8a5bb-91ff-4f38-93bc-d674bbef9b5b.JPG)

> Do you think it's necessary to add, "This module does not work with Windows."

No if that is available under Modules docs, that's fine.

Thanks
