### ISSUE TITLE
Filebeat module cisco asa ECS event.outcome / event.type wrong

### ISSUE THREAD

**Issue by emalzer** [elastic/beats#29581]
Hi,

I'm using the cisco module to parse logs from an ASA. The ES ingest pipeline then sets also the fields for event.outcome which is fine. But it seems that the pipeline sets the outcome field different than what the documentation says.

https://www.elastic.co/guide/en/ecs/1.12/ecs-using-the-categorization-fields.html

Here is an example showing a firewall blocking a connection and the field event.outcome is set to `success`.
The ES pipeline sets the event.outcome field to `failure` in such a case:
Also the field event.type is set to `info` and should be set `connection`.

This look wrong to me. Any thoughts on this?

Example output from the pipeline (some fields removed / redacted):
```
{
    "_source": {
        "@timestamp": "2021-09-01T23:58:58.000Z",
        "@version": "1",
        "destination": {
            "address": "1.1.1.1",
            "ip": "1.1.1.1",
            "port": 23
        },
        "event": {
            "action": "firewall-rule",
            "category": [
                "network"
            ],
            "code": 710003,
            "created": "2021-12-21T21:10:41.874Z",
            "ingested": "2021-12-21T21:10:44.496078Z",
            "kind": "event",
            "outcome": "failure",
            "severity": 3,
            "type": [
                "info",
                "denied"
            ]
        },
        "log": {
            "level": "err"
        },
        "message": "%ASA-3-710003: TCP access denied by ACL from 2.2.2.2/35025 to RULENAME:1.1.1.1/23",
        "network": {
            "iana_number": 6,
            "transport": "tcp"
        },
        "observer": {
            "egress": {
                "interface": {
                    "name": "RULENAME"
                }
            },
            "type": "firewall",
            "vendor": "Cisco"
        },
        "related": {
            "ip": [
                "2.2.2.2",
                "1.1.1.1"
            ]
        },
        "source": {
            "address": "2.2.2.2",
            "ip": "2.2.2.2",
            "port": 35025
        },
        ....
    }
}
```

- Version: Elastic Stack 7.16.1 / Filebeat 7.15.1
- Operating System: Ubuntu 18.04
- Steps to Reproduce: Can also be seen in the tests: https://github.com/elastic/beats/blob/master/x-pack/filebeat/module/cisco/asa/test/asa.log-expected.json#L4987

**Comment by jamiehynds** [comment]
Thanks for flagging this @emalzer - you are correct, if the firewall is successfully denying traffic, `event.outcome` should be success. On the flipside, if the rule was intended to deny traffic, but allowed it, `event.outcome` would then be failure. 

I'll assign it to my team and we'll address it in the pipeline.
