### ISSUE TITLE
Add fleet policy id to event data

### ISSUE THREAD

**Issue by renekalff** [elastic/beats#29615]
**Describe the enhancement:**
Add information to all incoming data which allows to tie that data to the fleet policy applied to the endpoint at that moment in time.

**Describe a specific use case for the enhancement or feature:**
Based on the assigned policy we would like to enrich the event data with policy specific information. In our case that's the organization.id the policy is intended for. When new agents are deployed they're immediately assigned to a policy based on the deployment token but in the log and metric data no information is present to tie the incoming data to the applied policy.

We've identified two other options to solve this but both have side affects which makes them undesirable for us:
- Use a namespace per policy. This information in present in the form of datastream.namespace but acts as an index multiplier. Using this method each policy get's its own datastreams and a such its own set of backing indices which, at least in our case, results in tens of thousands additional shards.
- Add the policy_id using another ingest pipeline. The information can be extracted from the .fleet-agents index alias. The problem with this approach is that when the policy is applied an endpoint it immediately starts sending its complete log retention of event data. As the enrichment index won't be updated with the new information at that time all events will lack the intended enrichment information (in our case the orginization.id).

**Comment by nimarezainia** [comment]
@renekalff i believe adding the ability to apply processors at the global policy level would address this issue: https://github.com/elastic/beats/issues/29459

**Comment by nimarezainia** [comment]
From 8.15 users can add a [field:value] pairings at the Agent Policy level which would insert the field into all the events ingested by all the agents in the policy:

![image](https://github.com/user-attachments/assets/5d71db5e-0f0d-413e-b10f-452b83434cb0)

Closing this ER as the feature is now delivered.
