### ISSUE TITLE
[Linux Agent]: No logs available under Fleet>Agent>Logs tab for Linux agents.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#29656]
**Kibana version:**  8.1 Snapshot Kibana cloud environment

**Host OS and Browser version:** Ubuntu `.tar` , All

**Build details:**
```
BUILD: 49374
COMMIT: 828321c4c77453ee4836c7beb43125dc310e4e66
Artifact Link: https://snapshots.elastic.co/8.1.0-544a92d3/downloads/beats/elastic-agent/elastic-agent-8.1.0-SNAPSHOT-linux-x86_64.tar.gz
```

**Preconditions:**
1. 8.1 Snapshot Kibana cloud environment should be available.
2. Linux agent must be installed with Default Policy having System integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Fleet>Agents tab.
3. Navigate to Linux agent>Logs tab.
4. Observe no logs available for Linux Agent

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/147806704-0fc496c0-313d-48f8-88be-72e988ca9025.JPG)

**Logs:**
[logs.zip](https://github.com/elastic/beats/files/7795434/logs.zip)

**Expected Result:**
 Logs should be available under Fleet>Agent>Logs tab for Linux agents.

**NOTE:**
- This issue is not observed on 8.0 Snapshot.
- This issue is also reproducible on Centos 8 with .rpm artifacts.
- No System- logs are available on Data Streams tab for only Linux .tar agent.

**Comment by manishgupta-qasource** [comment]
Reviewed and mention to @elastic/elastic-agent-control-plane

**Comment by fearful-symmetry** [comment]
This might be an input issue:
```
Loading and starting Inputs completed. Enabled inputs: 0
```
@amolnater-qasource can you dump the fleet config?

**Comment by amolnater-qasource** [comment]
Hi @fearful-symmetry 
We are facing some issues in deploying 8.1 Snapshot for which we have logged an issue at https://github.com/elastic/fleet-server/issues/1082

We will be sharing the same as soon as deployment issue will be fixed.

Thanks

**Comment by jlind23** [comment]
@amolnater-qasource deployment issue seems to be fixed, could you share what @fearful-symmetry asked please?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
The deployment issue for 8.1 Snapshot is still **not fixed**.
We have reopened the logged issue https://github.com/elastic/fleet-server/issues/1082

We are keeping track of this and will be sharing the details whenever build issue will be resolved.
Thanks!

**Comment by amolnater-qasource** [comment]
Hi @fearful-symmetry 
We have revalidated this issue on latest 8.1 Snapshot and found it **working fine** now.
- Logs for linux based agents(.tar and .rpm) are available under Agent>Logs tab.
- System data is available under Data Streams tab.

**Screenshots:**
![5](https://user-images.githubusercontent.com/77374876/150916095-50dac210-aa8d-49fb-849f-75438d47f2f5.JPG)
![6](https://user-images.githubusercontent.com/77374876/150916109-4bcdb54d-f030-4613-8d05-4bd99af22c93.JPG)

**Build details:**
BUILD: 49753
COMMIT: ab5741ff78bfbf7a9df6a664c741278f21582ea7
Artifact Link: https://snapshots.elastic.co/8.1.0-aa69d697/downloads/beats/elastic-agent/elastic-agent-8.1.0-SNAPSHOT-x86_64.rpm

Hence we are **closing** this issue.

Thanks
