### ISSUE TITLE
[Heartbeat] Better error controls for suite monitors

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/beats#29709]
### Issue: 
Currently, we don't have a good way to deal with these below situations when one of the error occurs on running monitors that are zip url endpoints.

- Network Error : ZIP url endpoint is not reachable, downloadable.
- Syntax Error: Cannot run journeys due to syntax errors in one of the journey files

### Proposal

We need to solve for both the very first run and subsequent runs from the Heartbeat.

#### Subsequent runs

Collect enough metadata in the download/discovery phase when heartbeat extracts the zip contents for the first time. A simple solution would be to store all the metadata while running the Synthetics runner and extracting and storing `journey/register` documents in parallel. 

1. Extract the ZIP endpoint and store the zip locally in a target/temporary directory which can be controlled via the zip url configuration.
2. Create a metadata file in the target directory running the Synthetics CLI in `dry-run` mode. The `metadata.json` contents would like below
```json
{"name": "monitor-journey-1", "steps": ["step-1", "step2", "step3"]}
{"name": "monitor-journey-2", "steps": ["step-1", "step2", "step3"]}
```
3. Subsequent runs would continue to run and update this metadata file whenever new journeys are added/deleted. Basically this file acts as a `gitkeep` or state of the suite monitors.
4. Whenever we encounter Network or Syntax Error, Heartbeat would consider that as if the Etag is unchanged (Using the extracted zip cache) and use the metadata that we extracted on the last successful run and write `error/summary` documents to the ES
5. Uptime monitor does not require any changes as we would get the summary as down with same error message across all journeys. 

### Very First run

We treat the errors (both network and syntax errors) same way in the HB side and create a single `error/summary` document to the ES which can be used in the Overview page or Error discovery page (Design TBD). 

### Added benefits

The main reason for adding the `journey/register` events was to eventually shard/parallelize the journeys that would come from zip endpoints as there could be multiples of them. With this discovery phase, we would be in a better situation as we know more about the journeys associated with the zip endpoints. 

Related to https://github.com/elastic/uptime/issues/425

**Comment by paulb-elastic** [comment]
I like the separation of the discovery phase, and agree that these can then be treated as separate monitors in the future.  Thinking about how this could fit in with the service, where they can then be scheduled and then executed in parallel.

Is the `metadata.json` an actual file (in which case we need to have a store location for it, irrespective of having a cache for the ZIP contents themselves), or would/could it be stored in ES?  This is especially relevant for the service where we’d have to handle that **state**, which does add complexity.

Also, is the intention for the `metadata.json` to become the source of truth for the monitor configs, or just a ‘link’ to the monitors discovered during the last successful `dry-run`, that are used just to be able to add an `error/summary` to, in the event of some kind of failure?

**Comment by andrewvc** [comment]
I think this solves one class of problems, syntax errors in the suite and other things that would make it un-runnable, but it doesn't solve the problem as completely as https://github.com/elastic/uptime/issues/431 / https://github.com/elastic/uptime/issues/432 so I'm not sure what the advantage is here given that https://github.com/elastic/uptime/issues/431 is probably an acceptable bridge to https://github.com/elastic/uptime/issues/432 which I think is a bit more clean, and doesn't require us to figure out the tricky state issue.

I'd love to hear your thoughts on pro / cons between this proposal and those. I realize we could store this state remotely, which effectively makes it similar to https://github.com/elastic/uptime/issues/432, but less powerful AFAICT. Your thoughts?
