### ISSUE TITLE
[Heartbeat] Read certs in windows system store

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#29715]
Heartbeat today supports custom SSL certs, but on windows does not read the certs on the windows system store, it should to make working with SSL more straightforward. See [this discuss post](https://discuss.elastic.co/t/configure-ssl-on-heartbeat-with-certificates-in-the-system-store/289499/5) for more info.

**Comment by FreerideTheWorld** [comment]
Bump. :)
