### ISSUE TITLE
[Filebeat] Kafka Input not working in 7.16.2

### ISSUE THREAD

**Issue by LeonBirk** [elastic/beats#29746]
As per the forum post: https://discuss.elastic.co/t/filebeat-kafka-input-not-able-to-process-messages/293255
When using version 7.15.2 with the same config, everything worked fine - hence the bug report for 7.16.2.

I'm currently facing an issue with the Filebeat Kafka input. The event flow is Data Source > Logstash > Kafka > Filebeat > Logstash > Elasticsearch. Kafka is used to handle event ingestion spikes and ES cluster failures as described here. I'd like to use Filebeat to parse the incoming logs with the built-in modules.

The error I'm getting is related to JSON serialization, though I'm not sure where the issue comes from - the messages seem fine at every step except the filebeat input. Here's the relevant error lines:

```
2021-12-31T10:26:47.767Z        ERROR   [file]  fileout/file.go:128     Failed to serialize the event: unsupported
2021-12-31T10:26:47.767Z        DEBUG   [file]  fileout/file.go:132     Failed event: &{{2021-12-31 10:26:46.708 +0000 UTC Not valid json: json: unsupported type: func() {"agent":{"ephemeral_id":"b1070c2d-fbe0-45e5-858e-6bfebaf62bbb","hostname":"ca3b5315a976","id":"9af1c238-66aa-415b-95f1-b51243ba8c60","name":"ca3b5315a976","type":"filebeat","version":"7.16.2"},"ecs":{"version":"1.12.0"},"host":"xxxxx","input":{"type":"kafka"},"kafka":{"headers":[],"key":"","offset":4,"partition":2,"topic":"cyberark"},"message":"2021-12-31T10:26:46.650Z server.domain.net why is this failing?"} <nil> false} 1 {map[]}}
```

This is the Logstash pipeline I'm using to produce to the Kafka topic:
```
input {
  tcp {
    port => 5146
    id => "ls-tag-1-cyberark-input"
  }
}

filter {
    mutate {
        id => "ls-tag-1-cyberark-add-customer-label"
        add_field => { "[labels][customer]" => "Customer Name" }
    }
}

output {
  kafka {
    id => "ls-tag-1-kafka-output-cyberark"
    client_id => "ls-tag-1"
    bootstrap_servers => "server1:9092,server2:9092,server3:9092"
    topic_id => "cyberark"
  }
}
```

I sent some lines to the Logstash host through like this nc:

```
[root@server4~]# nc server5 5146
this should definitely not be json
why is this failing?
```

They're correctly received by Logstash and pushed to Kafka:

`/opt/kafka/bin/kafka-console-consumer.sh --topic cyberark --from-beginning --bootstrap-server localhost:9092`

```
2021-12-31T10:07:29.837Z server6 this should definitely not be json
2021-12-31T10:26:46.650Z server6 why is this failing?
```

This is the configuration of the Kafka topic:
```
/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --describe --topics-with-overrides
Topic: __consumer_offsets       TopicId: qk6IHkcDRn6V_cR3vV57mg PartitionCount: 50      ReplicationFactor: 3    Configs: compression.type=producer,cleanup.policy=compact,segment.bytes=104857600
Topic: cyberark      TopicId: p2BhSdPMT2afRLz1T4-_Dw PartitionCount: 3       ReplicationFactor: 3    Configs: segment.bytes=1073741824
```

And finally this is the filebeat.yml with the Kafka input that produces the error:
```
filebeat.inputs:
  - type: kafka
    hosts:
      - server1:9092
      - server2:9092
      - server3:9092
    topics: ["cyberark"]
    group_id: "filebeat"
#    parsers:
 #     - ndjson:
  #      keys_under_root: true
   #     add_error_key: true
    #    message_key: log


output.file:
  path: "/usr/share/filebeat/kfk.out"

logging.level: debug
```

I tried the same with the Logstash Kafka output set to json codec, and the ndjson parser enabled as commented in the filebeat.yml - still no luck:

```
&{{2021-12-29 17:16:25.084 +0000 UTC Not valid json: json: unsupported type: func() {"@version":"1","agent":{"ephemeral_id":"3e041218-fee8-46b5-93cb-0ac6fd22c1b9","hostname":"ca3b5315a976","id":"9af1c238-66aa-415b-95f1-b51243ba8c60","name":"ca3b5315a976","type":"filebeat","version":"7.16.2"},"ecs":{"version":"1.12.0"},"host":"xxxxx","input":{"type":"kafka"},"kafka":{"headers":[],"key":"","offset":0,"partition":1,"topic":"cyberark"},"labels":{"customer":"Customer"},"message":"{\"port\":41658,\"host\":\"server1\",\"@timestamp\":\"2021-12-29T17:16:25.031Z\",\"@version\":\"1\",\"labels\":{\"customer\":\"Customer\"},\"message\":\"this is nice\"}","port":41658} <nil> false} 1 {map[]}}
I think somehow that last part from the error message is added at some point between Kafka and Filebeat - <nil> false} 1 {map[]} and breaks the json parsing, though I don't understand where - the configuration seems pretty straightforward.
```

For confirmed bugs, please report:
- Version: 7.16.2
- Operating System: CENTOS 8
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-kafka-input-not-able-to-process-messages/293255
- Steps to Reproduce: 
  1. set up filebeat.yml with Kafka import
  2. try to output events to file / stdout / logstash

**Comment by jlind23** [comment]
@faec Could you chime in?

**Comment by immavalls** [comment]
From a user reporting this, it seems that if we drop some fields:

```yaml
processors:
- drop_fields:
fields: ["@metadata", "ecs", "host", "agent"]
ignore_missing: true
```

The error `2022-01-05T08:23:10.460Z        ERROR   [console]       console/console.go:137  Unable to encode event: unsupported` in the logs disappears. Though we still see is that the offset is not committed (also since `7.16.0`, it works in `7.15.x`). Not sure if this will be the same issue, of we need to create a separate one.

**Comment by faec** [comment]
> Though we still see is that the offset is not committed 

That does make the offset more likely to be a somewhat-independent bug; perhaps there's an issue with updating the kafka offset when some events are dropped? I'd be surprised if that was always the case but it could be a factor.

**Comment by ThorbenJ** [comment]
Kafka input receiving plain text single line messages -> console output.

```
filebeat.inputs:
- type: kafka
  hosts: ["example.elasticsa.co.:9094"]
  ssl:
    enabled: true
    ...
  topics: 
  - plain-text-test-topic
  group_id: "filebeat1"

output.console:
  pretty: true
```

On 7.15.2 works fine no issue.

On 7.16.3:
```
...
2022-02-07T09:54:50.138Z	ERROR	[console]	console/console.go:137	Unable to encode event: unsupported
2022-02-07T09:54:50.138Z	ERROR	[console]	console/console.go:137	Unable to encode event: unsupported
2022-02-07T09:54:50.138Z	ERROR	[console]	console/console.go:137	Unable to encode event: unsupported
2022-02-07T09:54:50.138Z	ERROR	[console]	console/console.go:137	Unable to encode event: unsupported
2022-02-07T09:54:50.138Z	ERROR	[console]	console/console.go:137	Unable to encode event: unsupported
2022-02-07T09:54:50.138Z	ERROR	[console]	console/console.go:137	Unable to encode event: unsupported
2022-02-07T09:54:50.138Z	ERROR	[console]	console/console.go:137	Unable to encode event: unsupported
2022-02-07T09:54:50.138Z	ERROR	[console]	console/console.go:137	Unable to encode event: unsupported
...
```

I am surprised that this is flag for fix in 8.2 and not 7.last.

**Comment by jlind23** [comment]
@ThorbenJ this is the fix for the version in which we are currently working on. But it can be backported when it is a bugfix.

**Comment by metalshanked** [comment]
Hi @jlind23 - Is this fix available in Filebeat 8.0.1?  We use the Kafka file input and are waiting to upgrade to v8.x due to this issue.

Thanks in advance!

**Comment by cmacknz** [comment]
@metalshanked yes this was in 8.0.1: https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-8.0.1.html

**Comment by ThorbenJ** [comment]
Was this bugfix also back ported to 7.x? - Thanks
