### ISSUE TITLE
filebeats: No ability to interpolate lists of values via environment variables

### ISSUE THREAD

**Issue by skade** [elastic/beats#2978]
Details:
- Version: 5.0.0
- Operating System: all
- Steps to Reproduce: try to pass a list of values per environment variable
- Previous discussion: https://discuss.elastic.co/t/interpolate-list-from-environment-variable-in-filebeats/65517

Details:

Older Filebeat versions document a syntax for including a list of e.g. hosts from an environment variable into filebeat.yml.

https://www.elastic.co/guide/en/beats/filebeat/1.2/using-environ-vars.html1

This feature seems to have vanished from newer releases. It is now not documented anymore, with no appropriate replacement.

We could use `["${KAFKA_BROKER_1}", "${KAFKA_BROKER_2}"]`, but this would fix us to an exact size of the seed host set and would not work in other scenarios, like passing a list of files to tail.

**Comment by tsg** [comment]
This was fixed a while ago by the PR referenced above.
