### ISSUE TITLE
Misleading documentation for 8.0 

### ISSUE THREAD

**Issue by tobio** [elastic/beats#29802]
In https://github.com/elastic/beats/pull/28450, `setup.ilm.rollover_alias` has been removed. Previously, this was relied upon to ingest into custom indices. 

The current [docs](https://www.elastic.co/guide/en/beats/filebeat/8.0/ilm.html#setup-ilm-rollover_alias-option) [still](https://www.elastic.co/guide/en/beats/filebeat/8.0/elasticsearch-output.html#index-option-es) reference this option. 

Further, the documentation around `output.elasticsearch.index` suggests this option should be configured for daily indices, however setting this up as a datastream appears to work as expected. Should this option be used to configure a custom datastream name? If not, how is that accomplished in 8x? 

Related to https://github.com/elastic/cloud/issues/94969#issuecomment-1009582694

/cc @ruflin @kvch

**Comment by tobio** [comment]
@jlind23 I'm not sure what the bar is but if this is just a docs change and the underlying behaviour is going out in 8.0 is it possible to backport this to 8.0?

**Comment by jlind23** [comment]
@tobio If it is just a doc update indeed it can be backported to 8.0.
If you look at the attached PR: Follow up changes in documentation about data streams #29819
@kvch already added this 8.0 backport label.
