### ISSUE TITLE
Flaky Test [x-pack/filebeat-cloudAWS / TestInput/Test_first_event – github.com/elastic/beats/v7/x-pack/filebeat/input/httpjson]

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#29847]
## Flaky Test

* **Test Name:** github.com/elastic/beats/v7/x-pack/filebeat/input/httpjson TestInput
* **Link:** https://github.com/elastic/beats/blame/master/x-pack/filebeat/input/httpjson/input_test.go#L441
* **Branch:** master branch

### Stack Trace

```
 === RUN   TestInput/Test_first_event
    input_test.go:441: 
        	Error Trace:	input_test.go:441
        	Error:      	Not equal: 
        	            	expected: map[string]interface {}{"first":"a", "foo":"b"}
        	            	actual  : map[string]interface {}{"first":"none", "foo":"b"}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,3 @@
        	            	 (map[string]interface {}) (len=2) {
        	            	- (string) (len=5) "first": (string) (len=1) "a",
        	            	+ (string) (len=5) "first": (string) (len=4) "none",
        	            	  (string) (len=3) "foo": (string) (len=1) "b"
        	Test:       	TestInput/Test_first_event
    --- FAIL: TestInput/Test_first_event (2.01s)
 ```

**Comment by efd6** [comment]
@kaiyan-sheng Do you have more context for this (GOOS, GOARCH, test invocation, platform, commit sha, etc)? I have attempted to reproduce this with the current tip (8acaed96150f6f6dacd90aca9181ea81807a8799) with with a large number of repetitions, but have not been able to get a failure.

**Comment by kaiyan-sheng** [comment]
Hi @efd6 sorry I only remember it happened once in PR https://github.com/elastic/beats/pull/29844. But I didn't save any more info... I will definitely update this issue if I see this flaky test again.

**Comment by efd6** [comment]
I took a look around the code today and its one of those thing that Should Never Happen™, so if it does again yes please paste the info here.

**Comment by andrewkroh** [comment]
Duplicate of https://github.com/elastic/beats/issues/34929 which has more details.
