### ISSUE TITLE
filebeat 8.0.0-snapshot can not detect changes in some files when debug logging is off

### ISSUE THREAD

**Issue by igorfraa** [elastic/beats#29840]
filebeat-8.0.0-SNAPSHOT docker image on Linux stuck on some (likely random) files and reports 
`log/harvester.go:340    File is inactive. Closing because close_inactive of 5m0s reached.`

However, there are changes in the files, which can be seen with 'tail -f' command.

What is perfectly strange, when 'logging.level' is set to DEBUG all changes in files are detected.

Downgrading to 7.16.0 fixed the issue.

**Comment by kvch** [comment]
Could you please share your configuration and both regular and debug logs?

**Comment by igorfraa** [comment]
@kvch 
the config is essentially the same and comes from Helm template:
```  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
    
    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
```

Could you please point me which parts of debug logs do we need?
