### ISSUE TITLE
Unclear installation documentation

### ISSUE THREAD

**Issue by ctindel** [elastic/beats#2989]
I followed the docs here when installing:

https://www.elastic.co/guide/en/beats/metricbeat/5.0/metricbeat-configuration.html

and because the docs seemed to imply that I should paste both of those examples into the .yml file (or I'm just stupid) I ended up with an obscure problem where I had two metricbeats.modules sections and the first one was ignored.

I think we could make the docs more clear that if you want to use both of those examples they need to be combined into a single section.  Perhaps with a 3rd block showing them merged together or something.

**Comment by tsg** [comment]
Ping @dedemorton
