### ISSUE TITLE
elastic-agent diagnostics: filebeat and metricbeat configuration

### ISSUE THREAD

**Issue by jlind23** [elastic/beats#29898]
The `elastic-agent diagnostics collect` command should bundle the config that it generates for underlying beat processes

**Comment by ph** [comment]
@jlind this issue is in the **review** state in the board? Does that mean you are waiting for evaluation or design?

**Comment by jlind23** [comment]
@ph waiting for evaluation on the attached PR: https://github.com/elastic/beats/pull/29902
