### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MarkSettleES** [elastic/beats#29916]
I think I may have spotted an error in the documentation for our [Threat Intel module for Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-threatintel.html#_the_available_filesets_are).

Among the eight list items in the section, **`The available filesets are:`** are these two items, which I strongly suspect to describe the same source:

> - [abusemalware](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-threatintel.html#abusemalware): Supports gathering Malware/Payload entities from Abuse.ch.
> - [malwarebazaar](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-threatintel.html#malwarebazaar): Supports gathering Malware/Payload entities from Malware Bazaar.

MalwareBazaar is abuse.ch's malware-related threat intel project, thus my worry that our documentation might repeat itself.

cc: @P1llus

**Comment by dedemorton** [comment]
As usual, Pius is correct. :-) They are separate modules that read from different APIs.

But I wonder...do we need to add any guidance about when to enable one of these modules instead of the other? It is potentially confusing for users when we have multiple ways to collect similar data.

@marc-gr Do you have any thoughts on this question?

**Comment by marc-gr** [comment]
> As usual, Pius is correct. :-) They are separate filesets that read from different APIs.
> 
> But I wonder...do we need to add any guidance about when to enable one of these filesets instead of the other? It is potentially confusing for users when we have multiple ways to collect similar data.
> 
> @marc-gr Do you have any thoughts on this question?
> 
> (Edited: meant to say filesets, not modules.)

Agreed in that extra clarification would be nice. Are there any tips or specifics a user need to take into account when choosing @P1llus ?
