### ISSUE TITLE
[Filebeat][Azure] azure.signinlogs.properties.authentication_requirement_policies created as keyword should be an object instead.

### ISSUE THREAD

**Issue by philippkahr** [elastic/beats#29925]
For confirmed bugs, please report:
- Version:  7.16.3

The key `azure.signinlogs.properties.authentication_requirement_policies` is returned by azure as an object but filebeat creates it as a keyword.

https://discuss.elastic.co/t/filebeat-azure-plugin-parsing-error-on-azure-signinlogs-properties-authentication-requirement-policies-field/292586

**Comment by SpeedyFireCyclone** [comment]
Encountering the same with filebeat 8.0.0 still.

**Comment by kaiyan-sheng** [comment]
Hello! This should be fixed by https://github.com/elastic/beats/pull/31062 and it's backported to 8.x and 7.17.
