### ISSUE TITLE
[Processors] Add Set Processor

### ISSUE THREAD

**Issue by mr1716** [elastic/beats#29935]
This adds an set processor to be able to append data to ECS values.

The use case for this specific enhancement is that the majority of filebeat modules already contain the set processor at least 1 time in the ECS Modules, and this would allow beat-side processing to occur rather than on the Elastic side.
Team: Filebeat

**Comment by mr1716** [comment]
Team: Filebeat

**Comment by mr1716** [comment]
@botelastic Team: Filebeat

**Comment by legoguy1000** [comment]
The `add_fields` processor is the beats equivalent of the elasticsearch set processor.

**Comment by mr1716** [comment]
@legoguy1000 The add_fields only adds new processors, whereas the elastic set processor says that "if the field already exists, its value will be replaced with the provided one." The add_fields does not do this. Therefore, there is a gap. How would one close this gap?

**Comment by legoguy1000** [comment]
The add field can overwrite fields that already exists

**Comment by mr1716** [comment]
The documentation doesn't mention the ability to overwrite: [Add Fields](https://www.elastic.co/guide/en/beats/filebeat/current/add-fields.html)
If this is indeed the case, can we get this feature/fact added to the documentation?

**Comment by legoguy1000** [comment]
I agree the docs don't say anything about it but the code appears to show that its hard coded to overwrite fields, https://github.com/elastic/beats/blob/53c7c51be99a798a484f87d63e633350ecc44df6/libbeat/processors/actions/add_fields.go#L110

**Comment by mr1716** [comment]
Thanks. Much appreciated. Do you know if there is any chance that there will be a possibility for an append field anytime soon to be added?

**Comment by legoguy1000** [comment]
I can't say but the issue that you made is the first step.

**Comment by mr1716** [comment]
Ok, thanks. Will close this request. Not sure how to get the other request to have the right tags/teams/labels so it can get redirected to the proper people/eyes.
