### ISSUE TITLE
Filebeat can not send log to redis 

### ISSUE THREAD

**Issue by Tenderne-art** [elastic/beats#29942]
This is my config  file:
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/httpd/*.log
  tags: ["system"]
  setup.template.name: "hr"
  setup.template.pattern: "hr-"
  setup.template.enabled: false
  setup.template.overwrite: true
  setup.ilm.enabled: auto
  setup.ilm.rollover_alias: "hr"
  setup.ilm.pattern: "{now/d}"
  fields:
    filebeat_tag: "system"
  fields_under_root: true
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:
  host: "http://172.16.55.2:5601"

output.redis:

  hosts: ["172.16.15.2:6379"]
  password: "elktest"
  keys:
    - key: "system"
      when.contains:
        event.module: "system"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata:
but when I run the filebeat  
ERROR   instance/beat.go:932    Exiting: Index management requested but the Elasticsearch output is
Exiting: Index management requested but the Elasticsearch output is not configured/enabled

**Comment by mtojek** [comment]
Hi @Tenderne-art! Please use code tags to adjust the config first, then we can take a look at your problem.
