### ISSUE TITLE
[Filebeat][httpjson input] Add status check API calls. 

### ISSUE THREAD

**Issue by vinit-elastic** [elastic/beats#29959]
This is a request for enhancement of httpjson for **Status Check API calls**.

Status check API calls are common for many security platforms. The platforms are based on export mechanism for their endpoints. The export mechanism consists of three steps:
1. Initiating export.
2. Checking export status.
3. Getting exported documents.

## Step 1: Initiating export
This API consists of the time-range and other parameters. 
### Request:
```
URL : POST  www.example.com/export 
BODY : { “some-prams…” }
```
### Response: 
```
{
    “export-id”: “9ef0e6a5-f2fd-43f7-beef-a867f66089c8”,
}
```

## Step 2: Checking export status 
The "export-id" from the first request is used in the URL to get the status of a specific export job. One has to check the status of the job periodically. There can be multiple types of status such as “started”, “In-progress”, “completed”, “error” etc. The successful export job would return the status “completed” along with a set of chunk-id, which will be used for downloading the data. 
### Request:
```
URL : GET www.example.com/export/<export-id>/status
Ex. www.example.com/9ef0e6a5-f2fd-43f7-beef-a867f66089c8/status
```
### Response: 
```
{ “status”: “in-progress” }
...
{ 
    “status”: “completed”,
    “chunks”: [ id-1, id-2, …]
}
```

## Step 3: Getting exported documents
Once the export job is completed, to fetch the data, we need to go through all the chunk-id and use those in the download API endpoint. Each chunk would contain an array of documents.
### Request:
```
URL : GET www.example.com/export/<export-id>/chunk/<chunk-id>
Ex. www.example.com/9ef0e6a5-f2fd-43f7-beef-a867f66089c8/chunk/1234124213
```
### Response: 
```
{ 
    [
	{ doc-1 },
	{ doc-2 },
	…
    ]
}	
```

An issue for the chained request has already been reported. link: https://github.com/elastic/beats/issues/22590
With the chained requests we can achieve step 1 and step 3 whereas, step 2 is not possible.

In the above example we would also require response/request parameters from "Step 2: Checking export status" in the "Step 3: Getting exported documents" requests.

**Comment by marc-gr** [comment]
Could the chain feature also add a `while` or similar step, such as we can wait until a condition is met? (in this case a result from the status api), this way we could use the same chain semantics. For the shared data, we could add a way to define global variables that could be accessed for utility if that is needed. Do you think that makes sense @vinit-elastic ?

**Comment by vinit-elastic** [comment]
Yes, @marc-gr. If that functionality is implemented in the httpjson we can leverage that. 
But I have one doubt in the process, which you mentioned above, that is at what frequency we are going to make status check calls? Are you going to add some rate-limiter, like 5 calls/sec, for such calls?

**Comment by SteveMcGrath** [comment]
In many of these cases, you may want to consider backoff with an upper bound to querying those kind of status calls, as they are generally associated to a longer-running async job.  In my own experiences, what I have done is something similar to the following workflow:

1. Make job request call `POST www.example.com/export` to get the job id
2. Make status calls using `GET www.example.com/export/{id}/status` to wait for the conditions to be met (e.g. a page/chunk of the job is available or the job entered a completed state)
3. Pull down each chunk of data for processing `GET www.example.com/export/{id}/chunk/{chunk_id}`

When querying the status APIs in my own python libraries over the years I have instituted logic similar to:

```python
calls = 0
resp = session.get(f'/export/{export_id}/status').json()
while resp.get('job_status') not in ['completed', 'failed']:
    calls += 1
    time.sleep(calls if calls < 30 else 30)
    resp = session.get(f'/export/{export_id}/status').json()
````
