### ISSUE TITLE
Probably should think about using two dashboards per row instead of 3

### ISSUE THREAD

**Issue by ctindel** [elastic/beats#2998]
These are the default dashboards with 5.0, but you can see things are too narrow and the labels on the bottom of the visualizations get cut off.

<img width="1358" alt="mongodb_packetbeat_dashboards" src="https://cloud.githubusercontent.com/assets/1863749/20273611/f4db2770-aa5f-11e6-800d-90feb4952170.png">

**Comment by andrewkroh** [comment]
Kibana has got better at handling different sized windows. I think this isn't as big of problem now in the latest version.
