### ISSUE TITLE
Establish first class monitoring procedure for elasticsearch

### ISSUE THREAD

**Issue by matschaffer** [elastic/beats#29980]
@DaveCTurner raised in [slack](https://elastic.slack.com/archives/C0D8ST60Y/p1643012452032300?thread_ts=1642991134.031900&cid=C0D8ST60Y) that:

> The JSON representation of the cluster state is, however, only really for debugging purposes (it’s not stable between versions) and definitely isn’t intended to be indexed as a document back into Elasticsearch.

But it's exactly what [metricbeat](https://github.com/elastic/beats/blob/master/metricbeat/module/elasticsearch/cluster_stats/data.go#L230-L231) (and internal collection) is indexing into ES to power stack monitoring functions.

We should consider establishing stable APIs for ingesting the cluster information needed to power our stack monitoring feature.

In the short term we should at least make sure we're not indexing things like node ids as keys (https://github.com/elastic/beats/issues/30390)

![image](https://user-images.githubusercontent.com/690/150914709-d05fdd16-c28e-4850-b155-2f17fa27f38c.png)

Longer term we should look at having a first class API and delivery mechanism that's intended for monitoring and can be checked for stability across releases.

**Comment by DaveCTurner** [comment]
> it's exactly what metricbeat (and internal collection) is indexing into ES

Can't comment on metricbeat but are you sure that internal collection pushes the cluster state JSON into the monitoring cluster? I'm surprised to hear that it does this and can't see any obvious code that would do so.

**Comment by wandergeek** [comment]
hey @matschaffer, this screenshot is just from discover in [one of our monitoring clusters](https://monitor.us-east-1.aws.elastic-cloud.com/goto/1b8a8cc0-7fd1-11ec-853a-6ffc8afeec2d). Examining a [single document](https://monitor.ap-southeast-1.aws.elastic-cloud.com/app/discover#/doc/.monitoring-es-*/.monitoring-es-7-mb-2022.01.28?id=umwZnn4BmybgG9Z4IoCk) you can see the agent is `metricbeat`.

**Comment by matschaffer** [comment]
Thanks! So it could be that metricbeat is collecting more of the cluster state than we really need.

**Comment by jasonrhodes** [comment]
Once we finish https://github.com/elastic/kibana/issues/127209 we should circle back here and use that information to answer some of the most urgent questions here.
