### ISSUE TITLE
The "default config" fallback doesn't work properly

### ISSUE THREAD

**Issue by srenatus** [elastic/beats#3]
As figured out in #2, when there's an error in the config file, packetbeat logs [that it will use the defaults](https://github.com/packetbeat/packetbeat/blob/master/main.go#L199).  However, the following pcap.Openlive [fails](https://github.com/packetbeat/packetbeat/blob/master/main.go#L223) to open [device](https://github.com/packetbeat/packetbeat/blob/master/main.go#L221):

``` console
# packetbeat -e -c /root/packetbeat.conf 
TOML config parsing failed on /root/packetbeat.conf: Near line 21, key 'protocols.http.ports': Near line 21: Expected an array value terminator ',' or an array terminator ']', but got '8' instead.. We will use defaults.
main.go:225: ERR  pcap.Openlive failed(): : No such device exists (SIOCGIFHWADDR: No such device))
```

I don't find any reference to defaults in the code either, but I've never used toml before...

Thanks
Stephan

**Comment by ubaidvh** [comment]
I have problem when i run this script :

docker run --net='container:ub-mysql' -t -i --name packetbeat-agent-ub  packetbeat/packetbeat-agent packetbeat -e -c ~/ubaid/packetbeat.conf

this a response :
TOML config parsing failed on /home/administrator/ubaid/packetbeat.conf: open /home/administrator/ubaid/packetbeat.conf: no such file or directory. Exiting.

how to solve...????
couse packetbeat.conf is right file and in folder.
thank you....

**Comment by srenatus** [comment]
@ubaidvh just a guess, but your shell might resolv the `~/ubaid/packetbeat.conf` to `/home/administrator/ubaid/packetbeat.conf`, which _doesn't exist_ in the container. Either correct the path or put the file there (cannot guess what you've done before). Not a packetbeat problem, I think.

**Comment by ubaidvh** [comment]
the file packetbeat.conf in my host.....
should be in a container...???

**Comment by srenatus** [comment]
[It  should end in the container...](https://github.com/packetbeat/packetbeat-docker/blob/master/Dockerfile#L9)
