### ISSUE TITLE
[Metricbeat] aws cloudwatch module need `ec2:DescribeInstances` permission to set instance metadata

### ISSUE THREAD

**Issue by kwinstonix** [elastic/beats#30015]
# 1. problem

When I check cloudwatch package, I find it add some instance metatdata to the event(e.g. ip、state、machineType)， That is very useful. But there is no metadata except tags  in event. 

*  logp.Error didn't report error log to stdout, so I didn't realize the problem of iam policy 

https://github.com/elastic/beats/blob/e0053f7e3544ddaed87d44a1ad32e196a16ea549/x-pack/metricbeat/module/aws/cloudwatch/metadata/ec2/ec2.go#L29-L34

*  Document should add the permission `ec2:DescribeInstances`

https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-aws-cloudwatch.html#_aws_permissions_2

```
ec2:DescribeRegions
cloudwatch:GetMetricData
cloudwatch:ListMetrics
tag:getResources
sts:GetCallerIdentity
iam:ListAccountAliases
```

**Comment by kaiyan-sheng** [comment]
Hey @kwinstonix 👋 collecting EC2 metadata only happens when using the aws ec2 metricset. That's why `ec2:DescribeInstances` is documented under the AWS permissions section in ec2 metricset: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-aws-ec2.html#_aws_permissions_4

**Comment by kwinstonix** [comment]
Thank you, I understand that. In my case I create a _ec2 metric set with few metrics, because built-in ec2 metricset contains too much metrics.😅
