### ISSUE TITLE
Support for multiple errors in one Metricbeat Fetch event

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#3004]
The EventsFetcher interface currently looks as following:

```
type EventsFetcher interface {
	MetricSet
	Fetch() ([]common.MapStr, error)
}
```

It returns a list of events or 1 error. The problem with this interface is that for example in Kafka it is possible that some of the events are successfully created and for an error should be returned. This would require to change the interface to:

```
// EventsFetcher is a MetricSet that returns a multiple events when collecting
// data.
type EventsFetcher interface {
	MetricSet
	Fetch() ([]common.MapStr, []error)
}
```
A list of errors would be returned instead of just one. For each error an error event would be sent.

**Comment by andrewkroh** [comment]
What do you want Metricbeat to do with the errors that a MetricSet generates?

I like the https://github.com/joeshaw/multierror package for when I wish to collect all errors and then return (versus failing on first error and returning). It's quite simple to use.

```
	var errs multierror.Errors
	for {
		// do something
		if err != nil {
			errs = append(errs, err)
		}
	}

	// This will return a nil `error` if no errors occurred. 
	return x, errs.Err()
```

**Comment by ruflin** [comment]
So far I was thinking of the behaviour, that for each error an event is sent and for each event an event is sent. `totalEvents = len([]common.MapStr) + len([]error)`

In case a connection is down, only 1 error should be returned. But for example in case of Kafka if there is a failure for some of the partitions, each error should be reported separately and the successful partitions should be returned. This will make it possible to have a "count" for the error partition events. I see that this could also have the potential to be overwhelming, but it should be up to the metricset implementation to make sure the returned errors are reasonable.

If we use `[]error` or ` MultiError` does not matter too much to me as `MultiError` is only  a wrapper around `[]error`. One reason for `[]error` would be that people directly know how to use it and don't have to look up the API of `MultiError` even though it is very simple.

**Comment by andrewkroh** [comment]
> totalEvents = len([]common.MapStr) + len([]error)

This can be accomplished with [`Reporter`](https://godoc.org/github.com/elastic/beats/metricbeat/mb#Reporter).
