### ISSUE TITLE
[MetricBeat] aws cloudwatch module add rate field for each sum statistic metric  

### ISSUE THREAD

**Issue by kwinstonix** [elastic/beats#30050]
I found there is a function `calculateRate` in ec2 metadata module.  It is very useful for the metrics with  sum statistic.  I have some suggestions for this function 

* `period` is a fixed value.  It is better to use config params

* There are many metrics those have sum statistic(e.g. EBS, ELB ).   If we could call this logic in  `cloudwatch.go` Fetch or createEvents method, that would be more valuable
 
https://github.com/elastic/beats/blob/72a43be9ed23efc3dc2b371e2cadf5a7c575e429/x-pack/metricbeat/module/aws/cloudwatch/metadata/ec2/ec2.go#L164-L179

**Comment by ravikesarwani** [comment]
Is there specific metrics that needs this extra calculation? Is there any customer evidence of the need?
