### ISSUE TITLE
elastic-agent diagnostics: filebeat.sock: connect: connection refused

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#30059]
Hi Team,

I'm investigating a potential issue around https://github.com/elastic/integrations/issues/2602. It seems we have a dead (paniced?) filebeat:

```
elastic-agent@docker-fleet-agent:~$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
elastic+     1  0.0  0.0   2500   524 ?        Ss   12:54   0:00 /usr/bin/tini -- /usr/local/bin/docker-entrypoint
elastic+     8  9.4  0.2 2251460 70560 ?       Sl   12:54   1:18 elastic-agent container
elastic+  1350  0.1  0.0   4228  3504 pts/0    Ss   12:57   0:01 /bin/bash
elastic+  7002  0.0  0.0   5904  2948 pts/0    R+   13:08   0:00 ps aux
``` 

so I tried to use `diagnostics`:

```
elastic-agent@docker-fleet-agent:~$ ./elastic-agent diagnostics
elastic-agent  version: 7.17.0
               build_commit: a574d89ab5ad8c5254d6851bd39d4add7f69ce32  build_time: 2022-01-27 03:53:01 +0000 UTC  snapshot_build: true
Applications:
  *  name: filebeat  route_key: default
     error: Get "http://unix/": dial unix /usr/share/elastic-agent/state/data/tmp/default/filebeat/filebeat.sock: connect: connection refused
```

Is it intended or a bug?

**Comment by mtojek** [comment]
just in case:

```
elastic-agent@docker-fleet-agent:~$ ./elastic-agent status
Status: FAILED
Message: (no message)
Applications:
  * filebeat               (FAILED)
                           Missed two check-ins
  * metricbeat             (STOPPING)
                           Stopped
  * filebeat_monitoring    (STOPPING)
                           Stopped
  * metricbeat_monitoring  (STOPPING)
                           Stopped
```

**Comment by michel-laterman** [comment]
strange, are there logs from the filebeat instance?

**Comment by mtojek** [comment]
We found this, when filebeat crashed due to a panic.

**Comment by michel-laterman** [comment]
what was the panic message? what are the log messages?

**Comment by mtojek** [comment]
I linked the issue in the description. The root cause of it was that panic, investigated with Tiago, copied to comment. Did you look at it?

**Comment by michel-laterman** [comment]
My mistake (I thought this was to investigate the filebeat crashing), having a connection refused error when a process has crashed is expected behaviour at this point

**Comment by mtojek** [comment]
What if there are 2 processes running, filebeat and metricbeat, shouldn't `diagnostics` dump the state from the other one?

**Comment by michel-laterman** [comment]
If one has crashed it should dump the state of the running process, and an error message (connection refused) for the crashed one. If it's not doing that i think we should add it to https://github.com/elastic/beats/issues/29818 (improve diagnostics when a call fails)

**Comment by mtojek** [comment]
Not doing, hence my concerns.

**Comment by michel-laterman** [comment]
I've added this case a a comment for under #29818

**Comment by jlind23** [comment]
@mtojek may I close this one then and keep tracking progress in #29818?

**Comment by mtojek** [comment]
Yes, please do.
