### ISSUE TITLE
Heartbeat doesn't sends summary document if browser hangs/crashes or doesn't exit

### ISSUE THREAD

**Issue by shahzad31** [elastic/beats#30052]
We should timeout browser checks if all the steps are completing but browser isn't exiting. 

If browser doesn't exits in a way that synthetics agent doesn't sends the exit command, we don't send the summary document. 

Either we should handle this on agent side to make sure it always exits. 

Or we add some sort of timeout in heartbeat to send eventually summary document.

**Comment by shahzad31** [comment]
This can also happens if pod has low memory

**Comment by vigneshshanmugam** [comment]
This is fixed by https://github.com/elastic/synthetics/pull/447

> If browser doesn't exits in a way that synthetics agent doesn't sends the exit command

This is not relevant, Synthetics agent takes care of closing browser and also cleaning up all browser related handles when page is crashed or closed.
