### ISSUE TITLE
[Metricbeat] Add Redis commandstats (INFO all) to metricset

### ISSUE THREAD

**Issue by ghost** [elastic/beats#3008]
According to Andrewkroh reply : https://discuss.elastic.co/t/redis-info-metricset-should-provide-commandstats/66125

Could someone make a PR to change redis **INFO** to **INFO all** or add an option ?

Thanks a lot.

**Comment by andrewkroh** [comment]
The redis/info metricset reports the `default` [INFO](https://redis.io/commands/info), but with a simple minor change to request `all` then it could report a bunch more metrics.

https://github.com/elastic/beats/blob/7b0fb0450486b08b3bf1bbcb307f323e17bd1159/metricbeat/module/redis/info/info.go#L78

**Comment by rjnienaber** [comment]
Correct me if I'm wrong but the only difference I can see between `INFO`, `INFO default` and `INFO all` is that `INFO all` adds values for `cmdstat_command` and `cmdstat_info`.

```
# no differences between 'info' and 'info default'
$ diff <(redis-cli info | grep -Pv '^\s*$|^\#' | cut -d ':' -f 1 | sort) <(redis-cli info default | grep -Pv '^\s*$|^\#' | cut -d ':' -f 1 | sort)
```

```
# 'info all' adds 2 extra fields vs 'info default'
$ diff <(redis-cli info default | grep -Pv '^\s*$|^\#' | cut -d ':' -f 1 | sort) <(redis-cli info all | grep -Pv '^\s*$|^\#' | cut -d ':' -f 1 | sort)
27a28,29
> cmdstat_command
> cmdstat_info
```
