### ISSUE TITLE
[GCP] upgrade google cloud compute service SDK to `cloud.google.com/go/compute`

### ISSUE THREAD

**Issue by kwinstonix** [elastic/beats#30098]
## 1. `google.golang.org/api/compute/v1`

* older version of google cloud client

* IDE can't  resolve data type and package document, that is not handy for coding

## 2. `cloud.google.com/go/compute` 

* latest version of google cloud client

* recommended option

    https://cloud.google.com/apis/docs/client-libraries-explained

    > Cloud Client Libraries use our latest client library model and are our recommended option for accessing Cloud APIs programmatically, where available

After learning the details of packages in metricbeat GCP module, maybe I could add some features or enhancements.  When I check google cloud API documents,  there are two version client libraries,  I thought it is worth discussing that .

**Comment by endorama** [comment]
@elastic/obs-cloud-monitoring what's your opinion on this? I think it's worth to investigate the effort and proceed if it's not massive.

**Comment by kaiyan-sheng** [comment]
+1 on dedicating some time on this investigation!!
