### ISSUE TITLE
[Heartbeat] Better handling of subfolders in package.json

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#30119]
It is currently the case that heartbeat browser options only copy the exact folder specified to the tmp directory used for actually running it. This can be confusing to users who specify a path in a subfolder below their `package.json`, and can result in failed includes etc.

This issue proposes:

1. Returning an error if the specified folder does not contain a `package.json` file
2. Adding a new `filter_journeys.folder` option to let users actually filter by folder.

In the case of using the new `filter_journeys.folder` option heartbeat will run `npm @elastic/synthetics $filter_journeys.folder` to do the filtering.

**Comment by vigneshshanmugam** [comment]
Two questions here,

- Isnt this already solved by `target_directory`? 
- Also, if the folder does not contain package.json, Synthetics runner already does error out which would be captured as part of `stderr` with our new changes - #30013

**Comment by andrewvc** [comment]
Hmmm, the user who reported this was using local folders. So maybe it's just those that need additional error handling?

`target_directory` only unzips that folder.

If your folder structure is:

````
README.md
synthetics/package.json
synthetics/tests-a/test-a.ts
synthetics/tests-b/test-b.ts
synthetics/common.ts
```

and you have a `target_directory` of `synthetics/tests-a` things won't work right since we're missing the `package.json` and presumably the user wants `common.ts` (if it's used as a `require`)

In this case, what I'm saying is there'd be a separate `filter_journeys.folder` option that would be set to `synthetics/tests-a`, but the user would set `synthetics` as the `target_directory`

**Comment by vigneshshanmugam** [comment]
> you have a target_directory of synthetics/tests-a things won't work right since we're missing the package.json

If the user passed in `synthetics/tests-a` as the local path, then he wont get message from Synthetics runner as we cannot find the root `package.json` as we dont know the project structure due to missing parent folder. 

In this case, the runner would throw error as it cannot find root package.json file - https://github.com/elastic/synthetics/blob/251f504aa859ab0c4a119b5a59f7bbc84c586510/src/helpers.ts#L151

I am not sure about if its worth adding folder level filtering, We do already support names and tags filtering.

**Comment by andrewvc** [comment]
We agreed that we'll not add the new `filter_journeys` option, but we will change the `target_directory` option's behavior. We will now unpack the full zip and just `cwd` to that directory to avoid dependency issues.

**Comment by paulb-elastic** [comment]
Replaced by the PUSH option
