### ISSUE TITLE
[Metricbeat] gcp metrics module should improve efficiency of querying instance metatdata

### ISSUE THREAD

**Issue by kwinstonix** [elastic/beats#30153]
**Describe the enhancement:**

I found that events are reported too slowly when there are hundreds instances in my gcp account.

After querying TimeSeries,  additional instance metadata will be set  by `instances.get` API ,  but it is not an efficient way to query instances one by one.  `metadataCollector.instanceCache`  is working at its best.

https://github.com/elastic/beats/blob/b8d1fd791d04b306cc094942820f10bf08e45540/x-pack/metricbeat/module/gcp/metrics/compute/metadata.go#L145-L156

**Describe a specific use case for the enhancement or feature:**

We should use `instances.aggregatedList` API to reduce the number of GCP API calls.

**Comment by endorama** [comment]
Hi @kwinstonix thanks for opening this issue. I'll review the attached PR soon.
