### ISSUE TITLE
Reduce the number of requests to Elasticsearch when loading pipelines

### ISSUE THREAD

**Issue by kvch** [elastic/beats#30165]
At the moment, if a fileset is configured multiple times, Filebeat makes unnecessary requests to Elasticsearch. When an Ingest pipeline is loaded, first Filebeat checks if a pipeline with the given ID exists and if not it loads the pipeline. Unless overwrite is forced, then there is no extra check, just loading: https://github.com/elastic/beats/blob/master/filebeat/fileset/pipelines.go#L115-L135

We could decrease the number of requests to Elasticsearch if Filebeat cached which pipelines it has loaded already to Elasticsearch during setup and runtime.

**Comment by clock21am** [comment]
@kvch is this issue fixed?
If not I would like to work on it

**Comment by faec** [comment]
@clock21am Noémi isn't on the Beats team anymore but I believe this issue is still open. If you send us a PR it should be auto-assigned reviewers, if you have trouble getting attention on it feel free to ping me. Thanks!
