### ISSUE TITLE
Error with Azure Billing Metrics Integration - Version API incorrect

### ISSUE THREAD

**Issue by Teckinfor** [elastic/beats#30163]
Hello,

For my internship project, I have to integrate the monitoring of costs in a monitoring tool.

So I wanted to use the Azure Billing Metrics integration. The problem is that I get nothing at all because of the following error:
"Error fetching data for metricset azure.billing: error retrieving usage information: Retrieving usage details failed in client: consumption.UsageDetailsClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="400" Message="Subscription scope usage is not supported for current api version. Please use api version after 2019-10-01 (Request ID: 1f921262-183a-48cd-bf91-6b97f575cf55)".

I would like to clarify that my API works fine with the Azure Monitor Metrics integration. Do you have any idea how I can fix this please?

Thanks in advance for your help

**Comment by Teckinfor** [comment]
Please help, it's very important for me.

**Comment by endorama** [comment]
Closing as the same question have been answered here: https://discuss.elastic.co/t/error-with-azure-billing-metrics-integration-version-api-incorrect/296056

This is also a known issue, documented here: https://github.com/elastic/beats/issues/20758
