### ISSUE TITLE
[Heartbeat] Summary events override `cmd/status` events

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#30170]
Heartbeat's handling of `cmd/status` events https://github.com/elastic/beats/blob/master/x-pack/heartbeat/monitors/browser/synthexec/enrich.go#L136 is breaking the reporting of fatal script errors in the Uptime UI in that we no longer have `cmd/status` events sent to Uptime that can be used to trigger the view of stdout/stderr logs.

The behavior of the previously referenced code black ignores the `cmd/status` event in favor of creating a `heartbeat/summary` event. We should, instead, create a second `heartbeat/summary` event after the `cmd/status` event. This is a bit awkward in the current code structure since the enricher can only modify events, not create additional ones.

I'd recommend fixing this bug after we implement `discovery` mode, if we can transition things to the point where a single invocation of the synthetics node agent correlates to one journey that should simplify the code path.

**Comment by vigneshshanmugam** [comment]
> I'd recommend fixing this bug after we implement discovery mode, if we can transition things to the point where a single invocation of the synthetics node agent correlates to one journey that should simplify the code path.

Lots of boiler plate in Heartbeat enricher would go away once we have the discovery phase.

**Comment by andrewvc** [comment]
So, for this to really work right, I think we need to eliminate any code paths where synthetics outputs > 1 journey, which means that there needs to be a local discovery mode, where we essentially create one monitor per journey. That eliminates the need to track the journey context in a stateful way

**Comment by andrewvc** [comment]
For this reason I'm bumping this to 8.2 since it's related to journeys and isn't an urgent bug.
