### ISSUE TITLE
Libbeat - scripts/generate_index_pattern.py

### ISSUE THREAD

**Issue by florck** [elastic/beats#3017]
Hello,
In scripts/generate_index_pattern.py,
Line 38
 ` print "ERROR: Field", path, "is duplicated. Please delete it and try again. Fields already are", unique_fields `

should use python 3 syntax
`  print ("ERROR: Field", path, "is duplicated. Please delete it and try again. Fields already are", unique_fields)`
Thank you

**Comment by monicasarbu** [comment]
@florck Thanks for your feedback. I will fix it in a separate PR.
