### ISSUE TITLE
[Metricbeat][IIS][Application Pool] Capture application pool states

### ISSUE THREAD

**Issue by BenB196** [elastic/beats#30195]
**Describe the enhancement:**

Currently, the [iis application pool module](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-iis-application_pool.html) only captures running app pools. It would be nice if it captured all apps pools and included the state of them.

**Describe a specific use case for the enhancement or feature:**

IIS app pools can have [many different states](https://github.com/prometheus-community/windows_exporter/blob/master/collector/iis.go#L337-L342), currently, it is only possible to get data on running app pools. This limits the usability of this module. 

If I want to alert when an app pool stops, I need to look for when logs related to the app pool stop for X duration. This is less than ideal, as if I remove an app pool, then this alert would also trigger. Or if an app pool exists, but has never been started, then the alert would never trigger as there was no initial data to collect, to see a detla.

**Comment by Erikg346** [comment]
👍 
need this!

**Comment by Thunderer0** [comment]
Any Updates for this issue? I am facing same issue.

**Comment by Erikg346** [comment]
Did this never get resolved?
