### ISSUE TITLE
Metricbeat - GCP module - Pubsub - Ability to have topics labels 

### ISSUE THREAD

**Issue by naj-h** [elastic/beats#30217]
**Describe the enhancement:** Add [labels](https://cloud.google.com/pubsub/docs/labels) to the Metricbeat GCP module pubsub 

**Describe a specific use case for the enhancement or feature:**

In GCP projects, one can have multiple topics and subscriptions which each serve a certain functional scope. One way to categorise them is to use labels.
[If metricbeat does not report labels](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-gcp-pubsub.html), then one cannot use them to build specific visualisations by functional domain.
Example below to give an idea :
![image](https://user-images.githubusercontent.com/90753689/152506811-80250b50-6402-43e1-85ef-15b672236b70.png)

**Comment by sayden** [comment]
This is a known issue. The GCP integration can only handle metadata of Compute services and Beats need to develop the proper workarounds on lightweight modules to extract the labels data.

The code to achieve this must be stored in the `metrics` Metricset. An example of how to do this can be found in the compute folder here https://github.com/elastic/beats/tree/main/x-pack/metricbeat/module/gcp/metrics/compute
