### ISSUE TITLE
Update 8.1 branch to 8.0.0 after its release

### ISSUE THREAD

**Issue by kvch** [elastic/beats#30242]
On 8.1, the testing environment was updated to 8.0.0, but it had not been released yet. In https://github.com/elastic/beats/pull/30241 we reverted the updates of the testing environment so backport to 8.1 is not failing.

When 8.0.0 is out, we should change back the environment to 8.0.0.

CC @andresrc

**Comment by jlind23** [comment]
@kvch what shall we do with this one?

**Comment by kvch** [comment]
I take it back. Things are up to date.
