### ISSUE TITLE
Function beat not getting Deployed - Role Name error

### ISSUE THREAD

**Issue by jigar82** [elastic/beats#30270]
Deploying function beat on AWS failing starting 7.12 version
If functionbeat name is more then 11 character then it results into IAM rolename which is more then 64 character which is generated automatically by functionbeat and throws error 

For example:
function beat name:  test-functionbeat 

It will throw below error
`1 validation error detected: Value 'functionbeat-lambda-test-functionbeat-aayAiUcVmIjogIkFXUzo6UmVnaW9uIi4' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: <>; Proxy: null)`

Due to this issue deployment of functionbeat failing which was created before 7.12 and had longer function beat name

For confirmed bugs, please report:
- Version: 
- Operating System: 
- Discuss Forum URL:
- Steps to Reproduce:

**Comment by rfeiten** [comment]
Facing the same issue. I confirmed the max length possible would be 4 characters length (!!)

```
functionbeat.provider.aws.functions:
  # Define the list of function availables, each function required to have a unique name.
  # Create a function that accepts events coming from cloudwatchlogs.
  - name: foo
```

That would be the only workaround, but this needs to get fixed as it totally invalidates guides we find in Elastic page.
