### ISSUE TITLE
Elastic Agent does not pass down input id to filestream

### ISSUE THREAD

**Issue by jlind23** [elastic/beats#30300]
When using filestream with multiple input you can specify for each input an id such as follow:

`    - type: filestream
      enabled: true
      id: id1
      paths:
       - /var/log/k8sapps/myapp/*.log
      fields:
       app.name: "myapp"
      fields_under_root: true

    - type: filestream
      enabled: true
      id: id2
      paths:
       - /var/log/k8sapps/secondapp/*.log
      fields:
       app.name: "secondapp"
      fields_under_root: true`

For now there is a bug and Elastic Agent does not pass down this id parameter to its filestream inputs

**Comment by ph** [comment]
@jlind23 I see this labeled as `critical` what is the effect of not propagating the id down to the input?

**Comment by jlind23** [comment]
It causes data duplication when multiple input are set in filestream config.
https://github.com/elastic/beats/issues/30061

**Comment by ph** [comment]
We can populate down, but I do agree with @kvch we would need to investigate the root cause.

**Comment by ph** [comment]
> Yes, but even if the rootcause is found, it is still a bug on our end to not populate parameters.
@kvch does every input now support an ID?

**Comment by kvch** [comment]
Yes, all inputs support IDs in Filebeat. Passing down IDs is also important for `log`, not only `filestream`. Otherwise, we cannot collect the same file from multiple inputs.

**Comment by ph** [comment]
@kvch Ok, well it's only done for FB input in the linked PR.
