### ISSUE TITLE
import_dashboards on for filebeat and metricbeat don't load anything on master

### ISSUE THREAD

**Issue by LeeDr** [elastic/beats#3033]
- Version: master 6.0.0-alpha1
- Operating System: Ubuntu
- Steps to Reproduce: I use the same integration test script to import_dashboards that works on 5.0 branch but on master it doesn't load anything;

Although I'm running this command from the metricbeat/scripts folder, the tmp folder ends in /packetbeat.  Not sure if that's related to the problem.  Same for filebeat, tmp folder is packetbeat.

```
root@packer-virtualbox-iso-1474651890:/usr/share/metricbeat/scripts# ./import_dashboards -user elastic -pass changeme -url http://${BASEURL}/downloads/beats/beats-dashboards/beats-dashboards-6.0.0-alpha1-SNAPSHOT.zip
Create temporary directory /tmp/tmp354790697
Downloading http://snapshots.elastic.co/downloads/beats/beats-dashboards/beats-dashboards-6.0.0-alpha1-SNAPSHOT.zip
Unzip archive  /tmp/tmp354790697
/tmp/tmp354790697/beats-dashboards-6.0.0-alpha1-SNAPSHOT/packetbeat
root@packer-virtualbox-iso-1474651890:/usr/share/metricbeat/scripts#
```

**Comment by ruflin** [comment]
Closing this as we removed away from the import dashboard script with 6.0. @LeeDr please reopen if this is still an issue.
