### ISSUE TITLE
[Packetbeat] How to distinguish flows from different interface device in log?

### ISSUE THREAD

**Issue by 492917328** [elastic/beats#30334]
Packetbeat supports capturing all messages sent or received by the server on which Packetbeat is installed：

packetbeat.interfaces.device: any

But when I set the output  to elasticsearch, I found that the field interface.device does not exist on its log . In other words, How to distinguish netflow from different interface device in log?

**Comment by adriansr** [comment]
[According to ECS](https://www.elastic.co/guide/en/ecs/current/ecs-interface.html) this information must reside under `observer.ingress.interface.*`
