### ISSUE TITLE
Filebeat httpjson input response.split fails on an array of arrays 

### ISSUE THREAD

**Issue by wasserman** [elastic/beats#30345]
When trying to split a response of arrays I get the following error:
`error(*errors.errorString) *{s: "split was expecting field to be an object"}
`
It happens here:
https://github.com/elastic/beats/blob/2c0970807ef1b1493d9d6763fdda739a8db39562/x-pack/filebeat/input/httpjson/internal/v2/split.go#L145

Returned from here:
https://github.com/elastic/beats/blob/2c0970807ef1b1493d9d6763fdda739a8db39562/x-pack/filebeat/input/httpjson/internal/v2/split.go#L214

Keep in mind that the default should be `array` and the flow does go down this path.

My scenario is similar to the example I'm providing here, but I just used the Elastic demo site to make it easy to test and reproduce.

A sample input generated by the following from https://demo.elastic.co/app/dev_tools#/console:
```
POST _xpack/sql
{
  "query": "SELECT * FROM flights LIMIT 5"
}
```

Saved the output and served as a static file from local Web server for simplicity:
```
{
  "columns" : [
    {
      "name" : "AvgTicketPrice",
      "type" : "float"
    },
    {
      "name" : "Cancelled",
      "type" : "boolean"
    },
    {
      "name" : "Carrier",
      "type" : "text"
    },
    {
      "name" : "Dest",
      "type" : "text"
    },
    {
      "name" : "DestAirportID",
      "type" : "text"
    },
    {
      "name" : "DestCityName",
      "type" : "text"
    },
    {
      "name" : "DestCountry",
      "type" : "text"
    },
    {
      "name" : "DestLocation.lat",
      "type" : "text"
    },
    {
      "name" : "DestLocation.lon",
      "type" : "text"
    },
    {
      "name" : "DestRegion",
      "type" : "text"
    },
    {
      "name" : "DestWeather",
      "type" : "text"
    },
    {
      "name" : "DistanceKilometers",
      "type" : "float"
    },
    {
      "name" : "DistanceMiles",
      "type" : "float"
    },
    {
      "name" : "FlightDelay",
      "type" : "boolean"
    },
    {
      "name" : "FlightDelayMin",
      "type" : "long"
    },
    {
      "name" : "FlightDelayType",
      "type" : "text"
    },
    {
      "name" : "FlightNum",
      "type" : "text"
    },
    {
      "name" : "FlightTimeHour",
      "type" : "float"
    },
    {
      "name" : "FlightTimeMin",
      "type" : "float"
    },
    {
      "name" : "Origin",
      "type" : "text"
    },
    {
      "name" : "OriginAirportID",
      "type" : "text"
    },
    {
      "name" : "OriginCityName",
      "type" : "text"
    },
    {
      "name" : "OriginCountry",
      "type" : "text"
    },
    {
      "name" : "OriginLocation.lat",
      "type" : "text"
    },
    {
      "name" : "OriginLocation.lon",
      "type" : "text"
    },
    {
      "name" : "OriginRegion",
      "type" : "text"
    },
    {
      "name" : "OriginWeather",
      "type" : "text"
    },
    {
      "name" : "dayOfWeek",
      "type" : "long"
    },
    {
      "name" : "timestamp",
      "type" : "datetime"
    }
  ],
  "rows" : [
    [
      690.4515,
      false,
      "Logstash Airways",
      "Zurich Airport",
      "ZRH",
      "Zurich",
      "CH",
      "47.464699",
      "8.54917",
      "CH-ZH",
      "Clear",
      261.0023,
      162.1793,
      false,
      0,
      "No Delay",
      "0VA8ULZ",
      0.24166878,
      14.500127,
      "Turin Airport",
      "TO11",
      "Torino",
      "IT",
      "45.200802",
      "7.64963",
      "IT-21",
      "Rain",
      3,
      "2018-05-31T15:14:59.000Z"
    ],
    [
      265.5823,
      false,
      "Kibana Airlines",
      "Zurich Airport",
      "ZRH",
      "Zurich",
      "CH",
      "47.464699",
      "8.54917",
      "CH-ZH",
      "Damaging Wind",
      16323.602,
      10143.016,
      true,
      180,
      "Late Aircraft Delay",
      "6TFDEZN",
      25.671669,
      1540.3002,
      "Melbourne International Airport",
      "MEL",
      "Melbourne",
      "AU",
      "-37.673302",
      "144.843002",
      "SE-BD",
      "Hail",
      1,
      "2018-05-29T08:44:16.000Z"
    ],
    [
      960.86975,
      true,
      "Kibana Airlines",
      "Rajiv Gandhi International Airport",
      "HYD",
      "Hyderabad",
      "IN",
      "17.23131752",
      "78.42985535",
      "SE-BD",
      "Cloudy",
      7044.367,
      4377.167,
      true,
      15,
      "NAS Delay",
      "M05KE88",
      10.033843,
      602.0306,
      "Milano Linate Airport",
      "MI11",
      "Milan",
      "IT",
      "45.445099",
      "9.27674",
      "IT-25",
      "Heavy Fog",
      0,
      "2018-05-28T12:09:35.000Z"
    ],
    [
      479.79047,
      false,
      "Logstash Airways",
      "Sydney Kingsford Smith International Airport",
      "SYD",
      "Sydney",
      "AU",
      "-33.94609833",
      "151.177002",
      "SE-BD",
      "Rain",
      15551.353,
      9663.162,
      false,
      0,
      "No Delay",
      "OHLGFR3",
      17.279282,
      1036.7568,
      "Lester B. Pearson International Airport",
      "YYZ",
      "Toronto",
      "CA",
      "43.67720032",
      "-79.63059998",
      "CA-ON",
      "Clear",
      1,
      "2018-05-29T16:20:44.000Z"
    ],
    [
      648.5135,
      false,
      "JetBeats",
      "Sydney Kingsford Smith International Airport",
      "SYD",
      "Sydney",
      "AU",
      "-33.94609833",
      "151.177002",
      "SE-BD",
      "Hail",
      15913.688,
      9888.308,
      false,
      0,
      "No Delay",
      "PJOSR23",
      13.261407,
      795.6844,
      "Oslo Gardermoen Airport",
      "OSL",
      "Oslo",
      "NO",
      "60.19390106",
      "11.10039997",
      "NO-02",
      "Clear",
      3,
      "2018-05-31T12:46:33.000Z"
    ]
  ]
}
```

Filebeat input config as follows:
```
- type: httpjson
  interval: 30s
  config_version: 2
  request.url: http://localhost:8000/output.json
  request.method: GET

  response.split:
    target: body.rows
```

Tested on Filebeat 7.16.2.

I hope that this is a simple thing to fix. 

Bonus points for some smart way to map the `columns` to `rows` after such a split so Filebeat can output documents!

Thanks!

**Comment by legoguy1000** [comment]
Same issue happens if u have an array of strings. Its caused by the forced casting here, https://github.com/elastic/beats/blob/2c0970807ef1b1493d9d6763fdda739a8db39562/x-pack/filebeat/input/httpjson/internal/v2/split.go#L249.  I added the below to the Switch and it seems to work.
```
	case string, []interface{}:
		temp := make(map[string]interface{})
		temp["data"] = t
		return common.MapStr(temp), true
```

**Comment by tompipe** [comment]
Was annoyingly hit with this issue too, with json with this structure: 

```json
{
   "row_headers":[
      "Date",
      "Time Spent (seconds)"
   ],
   "rows":[
      [
         "2022-06-18T00:00:00",
         123
      ],
      [
         "2022-06-18T00:00:00",
         456
      ]
   ]
}
```

Was banging my head for a while, as first time using go templates, but eventually I managed to come up with this as a workaround.

```yml
- set:
    target: body.rows
    value_type: json		
    value: '[		   
	[[- $last_row := len (slice .last_response.body.rows 1) -]]                               		
	[[- $headers := .last_response.body.row_headers -]]
	[[- range $row_idx, $row := .last_response.body.rows -]]
            {
                [[- $last_cell := len (slice $row 1) -]]     
                [[- range $cell_idx, $cell := $row -]]
                  [[- sprintf "%q : %q" (js (index $headers $cell_idx)) (js $cell) -]]
                  [[- if lt $cell_idx $last_cell -]][[- sprintf ","]][[end]]
                [[end]]
            }
            [[- if lt $row_idx $last_row -]][[- sprintf ","]][[end]]                
	[[end]]
    ]'
```

Which converts each element in the row array to json objects, with their values keyed by the appropriate header. 

I ran into some encoding issues on some of the data, hence the js call to encode the values. 

Resulting in body.rows looking something like this

```json
[
    {
       "Date" : "2022-06-18T00:00:00",
       "Time Spent (seconds)" : "123"
    },
    {
       "Date" : "2022-06-18T00:00:00",
       "Time Spent (seconds)" : "456"
    }
]
```

Hope it helps others before the fix above gets merged and becomes available (or someone points out a better approach 😉 ) 



> 
> Bonus points for some smart way to map the `columns` to `rows` after such a split so Filebeat can output documents!
> 
> Thanks!

[Here](https://go-template-playground.writtn.com/#d:1Ffbbtu6Ev0VQtgbaICYIMWLRAPnIc2lyc7FReKeoqmKgrEYh61MpRSd1Aj87weSHFtUbTdt9XB2XmIPOYtrZtYM6afABf3g6akH7q027hYkwcckAL35PHEAgMQkrlz8K5OF-2zzR9D_D8iUAa-KTI8UgDZ_LADeKR3A9r_EJW4Jd6dkqmxRosFRnk0npqjOXKxbacYK_GXzx886_b5bfar2VsdVG5vQHv0kMU8gSQxYhGHaRFbxjFSWtQKqTmrEs959wa_0XxB8hqr8Nx9bx11ufKVNqr6vMrEE29nsvozx72-gD6ook8QlSRI8yGyqyg998Pe33caCm90v7WVS5kkAXn0pns-FRk7UTm0pCex4i6XzBjo1IX0LMrei3kxrbz5_eloS3q0LUtp6QJm0Xu4BlRVqnXbWx79w3F78-bq6N8guRNWQdJtqRVOZdB2tWp9LIu3DP9WHB7tBWrZVSSIJFgJPAtAHH2teT8_0kqCsQLWUBHsP46EefVXurdUjVVJZ7qrqWO-6zXLpkqBem-9uA9yXpiyGSjdh3eR5pqR5KZq1WtlNWE59fyGtA1W4blD2tL3PrTs56AZuX7vZRWXqBC2fGmdn3YCd5SPpdG5gJl3XiLnpBvFSjXVXWO-VdHediE0XrmyDU53lE-WULTporGfQc52pLvCOMj2-cwcqk7NOWrWBd643ViTLzfiX8YaV_59WpQa8mE66ghrqiTrOp7azYpSAW3L3C3gDq8e6g7aocToceTVgd0NvgdfV2Kvhuh18bcy8s7p0NfxqtM7GXypng9v3Sn398yHg9EQVTk7uN0Gl0qly0xKu_Pdpt34FlU_35hPo4zMEFwhShtkS81ZmhWqccJaPCyeLO7Cn7aOc-fP2emr1qFoqu8Jfujxes9Uz7fs7aAQpp1wIzxpDRgWOWo69a993P1OyWa-QY4hQSJYGzEOII0E2xIkaWBc5-PEuQP_di9-dXTdsCIYUcx5H8eoQChlCOIwajsOp1WZthoYDjH1DbrXJPdPJ0E8RgyFCMQo9awQ5FZy0HHuhj34pvTFIGkshwnEPsR7BQ8z6mPaZgAih62cpfdptqSbkDLI4JBtVc6pvpJFl2Jk26v9UNAdyIsfajMF7bZqPdMxJSCBH4cqCMCUQYb60ODtdxYvjpn7OpFNldCMrb90aKfHh0cHh9UVTrQzyCHMuVoiMIkhQg0ISnKvsJp9ao8CJccqaaojKbG0izw_P_O_Pvp517533tUciyCNCWvLClMKYlmQ889Vh77V_DR5LnTXTuEZhoRiiuE9pH_PtChMcwZiLiK3P-HaFXcov-gG8kSa90y9I1vGHVhyzVFl5I_0fbicXflYiGBJMcMRazRhDGoqYMcJ-kq79LJ-mTWlEiFJI-Gp6UBJFEDcMvupYc2jtXa2R2jlip4dx3CwKgoiQmK5al6MQIoJ4001n0uTgTJuFlH_U10lrdlUuPxldlDLUalQBw4hH9IfR5efuWMmHGTjKx83xu05d8RCHfST6hG1XF40EjASi0e9de1ez1KgZONVmXNzmNgVXE-3uXqC0q5bSaqDtPUmgoByJmPgDHjMMcRT9vCtbcx8zxjAkbCUAwTmBmIe_ezUOjs_eHF022ZW9EYkwbg5QwmHEeNxMsSqcsuA1BG-VtEVuXpDADx-u21dmbpx_Z-7v-cIjkEdRiBDxM9WLBOQEMSFE3PLvDS62vi42TDbM-yHqU7pde5zGkGGy-cX1j3KvlXT_Ysm1LwImMIE8XhVfxHEMCYp_V3Jv_xlcXYae5AgMOaZo1dGRYJDHlDaVWmQ5eCNtquwkV-tfZYMr_-YsfTzDxcC_zRHEggiEEfeThSFGiAghopZ7r5W_tro2vczCPuV9Qnx1VY_8xMyD-f8CAAD__w) is a slightly modified (and not perfect) version, which appears to work with your example @wasserman - do I win the bonus points? 🏆 😄

**Comment by jsanz** [comment]
> I managed to come up with this as a workaround.

@tompipe thanks for your workaround! Could you share the rest of the filebeat definition? I understand you use your snippet as a [`response.transform`](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-httpjson.html#response-transforms) and without adding any `request.split`, right?
