### ISSUE TITLE
[+DOC] Info on interpretting non-zero metrics log

### ISSUE THREAD

**Issue by stefnestor** [elastic/beats#30348]
For Beats Docs team, I’d like to recommend an appendage to [Troubleshooting](https://www.elastic.co/guide/en/beats/functionbeat/master/enable-functionbeat-debugging.html?edit) to inform users about interpreting “Non-zero metrics”. This applies across Beats & AFAICT does not yet exist. Is there a way to write this for all Beats & have linked in each or somewhere in a parent area?

E.g. for Filebeat

> We’ve previously resolved Filebeat OOM & CPU issues. Can we check for current throughput? Usually we’d enable [Filebeat Monitoring ](https://www.elastic.co/guide/en/beats/filebeat/current/monitoring.html) (you may already have this equivalent running) & running Filebeat in diagnostic mode (or checking its logs), we’ll search for “Non-zero metrics in the last 30s” which will then
> - outline these three JSON object pathways we’ll want to proportion check
>   - Incoming: monitoring.metrics.filebeat.events
>   - Processing: monitoring.metrics.libbeat.pipeline
>   - Outgoing: monitoring.metrics.libbeat.output
> - where we want to make sure their ratios are even & high. If they aren’t then example ratio implications (incoming:processing:outgoing):
>   - 100:12:10 indicates the processing pipeline may need tuning
>   - 10:10:10 indicates we may need to horizontally scale or look at the Filebeat module’s input levers
>   - 100:98:10 indicates we need to tune the [Elasticsearch output](https://www.elastic.co/blog/how-to-tune-elastic-beats-performance-a-practical-example-with-batch-size-worker-count-and-more) some more

Current ish-docs for [Functionbeat](https://www.elastic.co/guide/en/beats/functionbeat/7.1/configuration-logging.html#_logging_metrics_enabled)

**Comment by dedemorton** [comment]
Hi. Yes, there is a way to add the info to all the Beats. We have files set up for single sourcing. If you plan to contribute content, reach out to me and I can help you get started. Otherwise this issue will get added to the existing docs backlog for Beats. Thanks!

**Comment by stefnestor** [comment]
👋🏼 @dedemorton & I haven't been able to meet, so I'm going to pass this back to y'all as my ongoing weekend work schedule doesn't overlap well. TIA!

**Comment by dedemorton** [comment]
@stefnestor Sorry about that...I was on PTO. If you (or someone on your team) wants to open a PR, you can add the troubleshooting info to this topic:

https://github.com/elastic/beats/blob/main/libbeat/docs/shared-faq.asciidoc

And it will get pulled into the Beats documentation. For example, if you look here, you see that the shared files is included:
https://github.com/elastic/beats/blob/main/filebeat/docs/faq.asciidoc

If you want someone on the docs team to write the content, I'll add this to our project board and we'll prioritize it along with all the other stuff we're working on.

**Comment by dedemorton** [comment]
Added needs-input label because we need more information from the PM or product development teams to begin writing this content. We need someone to:

* Confirm that the details here are still accurate.
* Fill in gaps. The example shows Filebeat, but is there similar content for other Beats that we need to provide?

We need a Subject Matter Expert (SME) to partner with us on this content.

**Comment by jlind23** [comment]
@karenzone this log line just means that some metrics were ingested and that it is working.
It is a periodical metrics report by the Beat.

Not sure if this was the expected answer though?

**Comment by stefnestor** [comment]
👋 @jlind23 the requested validation from @dedemorton AFAIK is if my write-up is correct on how a user should interpret input>process>output  metrics for troubleshooting when these log lines do occur. 

IF Dev agrees on the general how-to-troubleshoot theory, then after we could add in common examples, e.g. 
- Filebeat `output.active: 4096` is it hitting the [internal queue default](https://www.elastic.co/guide/en/beats/filebeat/8.8/configuring-internal-queue.html)

**Comment by jlind23** [comment]
@rdner or @belimawr are definitely the most knowledgeable here.

Functionbeat does not need to be updated as it is now deprecated in favour of serverless-forwarder.

**Comment by stefnestor** [comment]
Answered by https://www.elastic.co/guide/en/beats/filebeat/8.12/understand-filebeat-logs.html, cheers
