### ISSUE TITLE
Documentation is missing the link for offline package of beats dashboards

### ISSUE THREAD

**Issue by JalehD** [elastic/beats#3037]
The link for offline package containing all beats dashboards is missing from documentation.
https://artifacts.elastic.co/downloads/beats/beats-dashboards/beats-dashboards-5.0.1.zip

**Comment by dedemorton** [comment]
The link gets set automatically by the import_dashboards script, but I don't think it hurts to document the URL, so I'll push an update to the docs.

**Comment by dedemorton** [comment]
Fixed in PR #3041
