### ISSUE TITLE
[Winlogbeat] add tests for ingest node pipelines

### ISSUE THREAD

**Issue by leehinman** [elastic/beats#30406]
**Describe the enhancement:**

#29435 switched modules from Javascript processor to Ingest Node pipelines.  The tests that were used for the Javascript processor are no longer valid.  We need to:

1. remove the old Javascript processor tests and golden files
2. Add fixture to run sample documents through ingest node pipelines
3. Add new tests that use the new fixture

**Comment by efd6** [comment]
Closed by #31833
