### ISSUE TITLE
[8.0.0] Metricbeat's Docker Kibana dashboard references fields removed in 8.0.0 due to deprecation

### ISSUE THREAD

**Issue by Nirusu** [elastic/beats#30413]
**The issue:**
https://github.com/elastic/beats/pull/27933 (commit: https://github.com/elastic/beats/commit/2c47ac8d7e3af05dc84c19ae5ff81aeaf3cca875) breaks the default Kibana dashboards for Metricbeat's Docker module. Running ElasticSearch, Kibana and MetricBeat at version 8.0.0, you end up with a dashboard that looks like this:
![image](https://user-images.githubusercontent.com/26608194/154169090-079e1ea5-f5d0-4004-bca6-808438a034ac.png)
![docker diskio total](https://user-images.githubusercontent.com/26608194/154169259-3e6f5fe2-8f9e-49a8-9033-a18869edf4c2.png)
![docker network in bytes](https://user-images.githubusercontent.com/26608194/154169262-4e4e30fe-47ca-4b30-94e4-ffde43733cb9.png)

**Suggested solution:**
Given that these field were deprecated and now completely removed, the visualizations in the dashboard need to be replaced with other fields that give a good picture.

**Comment by ChrsMark** [comment]
So I guess that https://github.com/elastic/beats/pull/27933 should also had tuned the Dashboards but we missed that? @mtojek could you confirm if that's the case here and then we can work on tuning the dashboards.

**Comment by mtojek** [comment]
Confirmed, looks like I missed dashboards. I will prepare a renaming fix and park it for 8.0.1.

**Comment by ChrsMark** [comment]
@mtojek thanks for the fix! Do we also need to tune the package too?
