### ISSUE TITLE
[Metricbeat] GCP module should not error when period is less than minimum

### ISSUE THREAD

**Issue by endorama** [elastic/beats#30434]
**Describe the enhancement:** Currently GCP module errors when a period less than a minimum given by GCP APIs is specified. It should not produce an error, correct the value to the minimum and produce a warning log message.

**Describe a specific use case for the enhancement or feature:** `gpc.compute` integration package specify a default period of 10s. When the integration is installed and setup to collect metrics from GCP metricbeat fails initializing data collection. This behaviour is correct but suboptimal, as debugging it requires delving into the Elastic Agent logs (identifying this issue from the log console in Kibana failed me multiple times). Given that the minimal period is known, is possible to correct this error without requiring user input.

Separately this should be addressed in the integration configuration by updating the default value **and** specifying the minimum valid value in the description.

**Comment by ishleenk17** [comment]
@endorama 
I am working on the GCP Improvements. 
I see that the default value of period is 1 minute in beats and in integrations.
Only a mention in the description about the minimum period should be sufficient here ?

**Comment by endorama** [comment]
@ishleenk17 thank you!

> Only a mention in the description about the minimum period should be sufficient here ?

I don't think so. The main issue is that if you specify 30 seconds in the beat or integration configuration, the underlying collector is going to halt due to an error. Debugging these errors is difficult, especially in complex configurations.
I think the outcome we want (for our customers and our troubleshooting efforts) is: it should not produce an error, correct the value to the minimum and produce a warning log message for inspections by human.

**Comment by lalit-satapathy** [comment]
@ishleenk17, Can this be moved to backlog?
