### ISSUE TITLE
captured wrong container id  with new version of containerd

### ISSUE THREAD

**Issue by masonlu2014** [elastic/beats#30444]
For confirmed bugs, please report:
- Version: Setup Beat: auditbeat; Version: 8.0.0-8.0.29.
- Operating System:  kubernets
- Discuss Forum URL:
- Steps to Reproduce: 

i want to report a bug,  we are using auditbeat in our k8s infra to do audit work, however when our k8s infra upgrade containerd runtime to  "containerd 1.4.6", we found auditbeat capture wrong contain id like below

```
"container": {
      "id": "cri-containerd-d39dc1d69fe60e18660fe98e598c76991dcdfdb6213b32032aab3d23711613b2.scope"
}
```

last year  our k8s infra using contained :1.2.4, our auditbeat running fine

**Comment by endorama** [comment]
Hi @masonlu2014, I'm not very familiar with auditbeat, may you help me clarify what is going wrong so I can forward this to the appropriate team? 
From my understanding, containers ID changed from containerd 1.2.4 to 1.4.6 and are different than before, but collection is still working. Why do you consider this a bug in auditbeat and not a change in containerd?

**Comment by masonlu2014** [comment]
sorry, i have fix it by using cgrop_regex, we can close the issue now
