### ISSUE TITLE
Don't include empty MetricSet data on error

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#3044]
For example, consider the event below. Should we not include the `kafka` key in this case? This applies to all events because it occurs in the [builder](https://github.com/elastic/beats/blob/master/metricbeat/beater/event.go#L37).

```
{
  "@timestamp": "2016-11-22T00:07:20.231Z",
  "beat": {
    "hostname": "macbook13.data.sr.local.crowbird.com",
    "name": "macbook13.data.sr.local.crowbird.com",
    "version": "6.0.0-alpha1"
  },
  "error": "kafka: client has run out of available brokers to talk to (Is your cluster reachable?)",
  "kafka": {
    "partition": {}
  },
  "metricset": {
    "host": "localhost:9092",
    "module": "kafka",
    "name": "partition",
    "rtt": 767145
  },
  "type": "metricsets"
}
```

**Comment by ruflin** [comment]
This will potentially break usage of `exists` query for `kafka.partition` in this example. But I agree we should not send empty fields and encourage users to filter for metricset.module and metricset.name.

**Comment by andrewkroh** [comment]
I think this is the case now because we do a `len()` check when constructing the file `beat.Event`.

https://github.com/elastic/beats/blob/1c088e47ae8346854a6e3f2113acd712cab4e871/metricbeat/mb/event.go#L49
