### ISSUE TITLE
Metricbeat process_summary missing Parked <P> process state

### ISSUE THREAD

**Issue by Linexos** [elastic/beats#30475]
- Version: 7.16.3
- Operating System: Almalinux 8.5 (Arctic Sphynx)
- Kernel Version: 4.18.0-305.el8.x86_64

The Parking \<P> process state is missing in metricbeat code for the module process_summary.

I have multiple process in Parked state "P" : 
\# ps -aux | grep ' P '

> root          32  0.0  0.0      0     0 ?        P    févr.17   0:00 [cpuhp/4]
> root          33  0.0  0.0      0     0 ?        P    févr.17   0:00 [watchdog/4]
> root          34  0.0  0.0      0     0 ?        P    févr.17   0:00 [migration/4]
> root          35  0.0  0.0      0     0 ?        P    févr.17   0:00 [ksoftirqd/4]
> root          38  0.0  0.0      0     0 ?        P    févr.17   0:00 [cpuhp/5]
> root          39  0.0  0.0      0     0 ?        P    févr.17   0:00 [watchdog/5]
> root          40  0.0  0.0      0     0 ?        P    févr.17   0:00 [migration/5]
> root          41  0.0  0.0      0     0 ?        P    févr.17   0:00 [ksoftirqd/5]
> root          44  0.0  0.0      0     0 ?        P    févr.17   0:00 [cpuhp/6]
> root          45  0.0  0.0      0     0 ?        P    févr.17   0:00 [watchdog/6]
> root          46  0.0  0.0      0     0 ?        P    févr.17   0:00 [migration/6]
> root          47  0.0  0.0      0     0 ?        P    févr.17   0:00 [ksoftirqd/6]
> root          50  0.0  0.0      0     0 ?        P    févr.17   0:00 [cpuhp/7]
> root          51  0.0  0.0      0     0 ?        P    févr.17   0:00 [watchdog/7]
> root          52  0.0  0.0      0     0 ?        P    févr.17   0:00 [migration/7]
> root          53  0.0  0.0      0     0 ?        P    févr.17   0:00 [ksoftirqd/7]

And in Metricbeat log's, I have many errors : 

> ERROR        process_summary/process_summary.go:105        Unknown or unexpected state \<P> for process with pid 32
> ERROR        process_summary/process_summary.go:105        Unknown or unexpected state \<P> for process with pid 33
> ERROR        process_summary/process_summary.go:105        Unknown or unexpected state \<P> for process with pid 34
> ERROR        process_summary/process_summary.go:105        Unknown or unexpected state \<P> for process with pid 35
> ...

**Comment by belimawr** [comment]
@Linexos do you face the same issue with 7.17.0 or 8.0.0?

Could you also post your configuration so we can take a better look at it?

@fearful-symmetry could you give some help here?

**Comment by fearful-symmetry** [comment]
So, I did some googling, and the `Parked` state was only in kernels 3.9-3.13, however, RHEL 7 is still on those versions, so I'm surprised I haven't seen this before now. 

It's a bit odd we're seeing this in `4.18.0` though. Almalinux aims for RHEL compatibility though, so I wonder if there's some kernel shenanigans going on.

Either way, this should be an easy fix.

**Comment by fearful-symmetry** [comment]
Did some more hunting through the kernel, and I can see where a handful of states were removed after ~3.13, but `parked` is still there, despite the docs in `man proc` stating otherwise.

**Comment by Linexos** [comment]
After several tests, I was able to determine that these processes appear in "parked" state following a hot reduction of vCPU (Proxmox hotplug CPU). The processes listed above are started for each CPU on the host. After hot shrinking vCPUs, these processes are not terminated but put in "parked" state.

**Comment by fearful-symmetry** [comment]
Alright. Currently working on a fix, would like to have  it in for 8.2. Unfortunately, due to the scope of change throughout the code we use to do process collection, I don't think we can backport into 7.x.

**Comment by fearful-symmetry** [comment]
change merged, closing.
