### ISSUE TITLE
Elastic Agent health check improvements

### ISSUE THREAD

**Issue by cakarlen** [elastic/beats#30479]
**Describe the enhancement:**
This enhancement is needed for agents that are reported as unhealthy and do not provide a reason for why. It would be fantastic to be able to hover over an agent's status that would report if an integration or a specific part of an integration is failing, which may result in the agent's status as being unhealthy.

**Describe a specific use case for the enhancement or feature:**
This could solve many headaches as to why some agent's report as unhealthy but providing a reason for _why_ they are unhealthy.

**Comment by jlind23** [comment]
@belimawr It seems like it similar to this one: https://github.com/elastic/beats/issues/21413 what do you think?

**Comment by belimawr** [comment]
> @belimawr It seems like it similar to this one: #21413 what do you think?

I agree. #21413 looks like a pretty good solution for this issue.

**Comment by jlind23** [comment]
Closing and following it up in https://github.com/elastic/beats/issues/21413
