### ISSUE TITLE
[Packetbeat] Error is shown on installing packetbeat

### ISSUE THREAD

**Issue by prachigupta-qasource** [elastic/beats#30493]
**Describe the bug:**

Error is shown on installing packetbeat

**Build Details:**

```
Version: 8.1.0 BC3
Build: 50346
Commit: 0335dd6a26ef29ae9021d0fae9347dc88f3b7d6e
```
**Precondition:**

Deploy 8.1.0 BC3 Elastic Cloud Build on Production Platform

**Steps to Reproduce**

1. RDP to the windows 64 bit vm.
2. Download and extract the packetbeat-8.1.0-windows-x86_64.zip.
3. Run power shell in admin mode.
4. Run `.\install-service-packetbeat.ps1`
5. Run `.\packetbeat setup`
6. Run `Start-Service packetbeat`
7. Observed that error is shown.

**Actual Result:**
Error is shown on Starting Services of packetbeat on window 64 bit

**Expected Result:**
Packet beat services should be started on the windows 64 bit

**Screenshot:**

![image](https://user-images.githubusercontent.com/97870262/154897565-397c28a6-e4e7-41ab-916e-41a697fc0766.png)

**What's not working:**

This issue also exists for Deploying 8.1.0 BC3 Elastic Cloud Build on Staging Platform

**Comment by dikshachauhan-qasource** [comment]
Reviewed and assigned to @kvch

**Comment by jlind23** [comment]
@adriansr it rather seems to be falling in your area. Am I correct?

**Comment by adriansr** [comment]
You're right, @jlind23 , having a look.

**Comment by adriansr** [comment]
@prachigupta-qasource 

I'm reproducing the error. It seems that aprox 50% of the time the Packetbeat service starts and then terminates after a few seconds (crashes?). Is this what you observe, that it can start sometimes? When it fails the logs end in:

> {"log.level":"info","@timestamp":"2022-02-21T15:29:49.442Z","log.logger":"esclientleg","log.origin":{"file.name":"eslegclient/connection.go","file.line":105},"message":"elasticsearch url: http://localhost:9200","service.name":"packetbeat","ecs.version":"1.6.0"}
> {"log.level":"info","@timestamp":"2022-02-21T15:29:49.443Z","log.logger":"publisher","log.origin":{"file.name":"pipeline/module.go","file.line":113},"message":"Beat name: asr-testing-windows-removeme","service.name":"packetbeat","ecs.version":"1.6.0"}

Can you confirm?

**Comment by efd6** [comment]
Yes, if there is no Npcap/WinPcap installed on the system, I would not expect the startup to work without those fixes backported (the bundled npcap installer will never be run). I would expect packetbeat to attempt to collect interfaces to listen on, fail that and so terminate. Is that what you saw, @adriansr?

I'm curious about the even-odd behaviour; that is not something that I would expect. I don't think `/no_kill` would have any effect here since we never try to uninstall the library.

**Comment by efd6** [comment]
This should be fixed by #30509, including the odd-even behaviour.

**Comment by prachigupta-qasource** [comment]
Hi @adriansr,

In response to your query. We have collected logs from the host and attached here for your reference.

[Logs.zip](https://github.com/elastic/beats/files/8132237/Logs.zip)

Further we have also verified this behaviour when starting packetbeat on powershell and found below error.

However we could not find any error logs there generated there

![image](https://user-images.githubusercontent.com/97870262/155519237-69b68e64-a6a0-47bf-9570-44a79b2d97f7.png)


```
> I'm reproducing the error. It seems that aprox 50% of the time the Packetbeat service starts and then terminates after a few seconds (crashes?). Is this what you observe, that it can start sometimes? When it fails the logs end in:
>
> > {"log.level":"info","`@timestamp`":"2022-02-21T15:29:49.442Z","log.logger":"esclientleg","log.origin":{"file.name":"eslegclient/connection.go","file.line":105},"message":"elasticsearch url: [http://localhost:9200/","service.name":"packetbeat","ecs.version":"1.6.0"}](http://localhost:9200/%22,%22service.name%22:%22packetbeat%22,%22ecs.version%22:%221.6.0%22%7D)
> > {"log.level":"info","`@timestamp`":"2022-02-21T15:29:49.443Z","log.logger":"publisher","log.origin":{"file.name":"pipeline/module.go","file.line":113},"message":"Beat name: asr-testing-windows-removeme","service.name":"packetbeat","ecs.version":"1.6.0"}
>
> Can you confirm?
```

We will validate this ticket on the 8.1.0 BC4 build once it is available.

Thanks!

**Comment by adriansr** [comment]
Thanks @prachigupta-qasource 

We're confident the problem will be gone in BC4. Looking forward to your feedback.

**Comment by prachigupta-qasource** [comment]
Hi Team

We have validated this issue on **8.1.0 BC4** and observed that issue is **Fixed**. ✔️ .

Please find below the testing details:

**Build Details:**

```
Version: 8.1.0 BC4
Build: 50428
Commit: 015578b81c26a5843747ba53b2fd92d40f0453cb
```

**Screenshot**

![image](https://user-images.githubusercontent.com/97870262/155934313-493f50ea-d4fd-4ea2-9598-f7dfe1bb41da.png)

Hence, we are closing this issue and marking as QA Validated.

Thanks!
