### ISSUE TITLE
Add linting based on the elastic-agent-libs for Beats

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#30545]
Now that a base configuration for [golangci-lint](https://golangci-lint.run/) has been created and setup for [elastic-agent-libs](https://github.com/elastic/elastic-agent-libs) we should do the same for the beats repository.

See https://github.com/elastic/beats/issues/30150 for the related PRs.

Since the beats repository is so large we will need to be more careful when rolling it out to ensure the new linters do not slow down the development workflow. 

We will likely also only want to have the linter only prevent new issues initially, rather than fixing all existing issues. PRs to address existing issues can be quite large, for example https://github.com/elastic/beats/pull/30483. 

See go-libaudit for an example of how to configure the linter to only find new issues: https://github.com/elastic/go-libaudit/blob/227948a588b4c181d09a55154a476372525be193/.github/workflows/golangci-lint.yml#L29-L30

**Comment by rdner** [comment]
> See go-libaudit for an example of how to configure the linter to only find new issues: https://github.com/elastic/go-libaudit/blob/227948a588b4c181d09a55154a476372525be193/.github/workflows/golangci-lint.yml#L29-L30

Just to avoid future problems, this configuration simply does not work. I tested it manually and had to use `--whole-file` additionally to this flag, see https://github.com/elastic/elastic-agent-libs/pull/11/files#diff-520109d035a196d29d0a86e9c4e6c98e98abf056141b84df68c0d48167b87b25R127-R132

**Comment by cmacknz** [comment]
I assigned this to you @rdner, if you run out of time for it feel free to send it back to me.

**Comment by cmacknz** [comment]
I think it stalled due to other priorities, I don't think @rdner is actively working on this. 

It's not critical to do in 8.2. We can unassign it change the label if we want and someone can take it once they have time for it.

**Comment by cmacknz** [comment]
Perfect, assigned back to you then
