### ISSUE TITLE
Elastic agent can unexpectedly map source object as a keyword in Filebeat logs indices

### ISSUE THREAD

**Issue by danielharada** [elastic/beats#30578]
- Version: 7.16.0

For `.ds-logs-elastic_agent.filebeat-*` indices we are expecting to receive an object in the `source` field, however, it's possible that some integrations can send a string or set the mapping on this field as a `keyword` instead.  This can break downstream functionality that acts upon the `source.*` fields.

In our case, the SIEM app IP address exception lists no longer worked, since this acts on `source.ip`, which does not exist when `source` is mapped as a keyword.

**Comment by kaiyan-sheng** [comment]
(I didn't go through all integrations and all filesets in beats) So far I found two places defining `name: source` field as a keyword type: 
1. In `threadintel` Filebeat module `anomalithreadstream` fileset: https://github.com/elastic/beats/blob/main/x-pack/filebeat/module/threatintel/anomalithreatstream/_meta/fields.yml#L66
2. In `ti_anomali` integration: https://github.com/elastic/integrations/blame/main/packages/ti_anomali/data_stream/threatstream/fields/fields.yml#L59

Could @P1llus @marc-gr take a look please? TIA!!

**Comment by kaiyan-sheng** [comment]
I think this can be closed by https://github.com/elastic/beats/pull/30688.
