### ISSUE TITLE
Metricbeat sytem module expects /etc/mtab which does not exist on all container runtimes

### ISSUE THREAD

**Issue by pebrc** [elastic/beats#30590]
- Version: 8.0

Metricbeats system module expects the `/etc/mtab` symlink to `/proc/mounts` be present for example for the fsstat metricset. When running in a containerised environment this symlink is not present on all container runtimes. For example `containerd` and `cri-o` do not create this symlink. 

We noticed this because ECK e2e tests started failing. https://github.com/elastic/cloud-on-k8s/issues/5345#issuecomment-1049024021 is the related issue where we track and analysed the build failures. 

We are using the following manifest for our e2e tests: https://github.com/elastic/cloud-on-k8s/blob/4bbfdd8dc14544db7926486afba92855f146b38a/config/recipes/elastic-agent/system-integration.yaml

**Comment by fearful-symmetry** [comment]
So, this issue is actually in elastic/gosigar, which means it needs to get wrapped into this issue, since that library is getting deprecated: https://github.com/elastic/observability-dev/issues/1217

**Comment by jlind23** [comment]
@pebrc is it something you faced with production environment or does it happen only when a particular config is in place?

**Comment by jlind23** [comment]
@pebrc it answers partially. My other question is, why do we see it only now as 8.0 was out for a couple of months already. Did something change on your end?

**Comment by pebrc** [comment]
@jlind23 if you look at the Git history for configuration I shared you see that this test has been in place since December 2020. I don't think anything we changed since then has an impact on this problem. The only variable I see at the moment is the version upgrade of the Elastic stack.

**Comment by jlind23** [comment]
Got it! Thanks for the detailed answer.
So @fearful-symmetry following our yesterday discussion, yes this is something we should fix asap.
But the question is, how?
cc @cmacknz

**Comment by fearful-symmetry** [comment]
This isn't a particularly complicated fix, I don't think. This would be mostly fixed by the "normal" refactoring process undertaken as part of https://github.com/elastic/observability-dev/issues/1217 as, the bug isn't in `elastic/beats`, but the result of a single function in `elastic/gosigar`. As @pebrc points out, `/etc/mtab` is merely a symlink, and I don't see why we would need a hard-dependency on it, assuming a containerized environment has been set up properly.

**Comment by kbujold** [comment]
We see this issue in 7.17 also

**Comment by fearful-symmetry** [comment]
Fix (in theory) is here, but is currently blocked: https://github.com/elastic/beats/pull/31001

**Comment by cmacknz** [comment]
> Fix (in theory) is here, but is currently blocked

What is this blocked on? What do we need to do to unblock it?

**Comment by fearful-symmetry** [comment]
@cmacknz This needs to get merged, then I can move the PR From the beats repo to `elastic-agent-system-metrics` https://github.com/elastic/elastic-agent-system-metrics/pull/1

**Comment by abstract-entity** [comment]
+1 got this bug in 8.1.2
