### ISSUE TITLE
Filebeat5.0 multiline doesn't work for large files

### ISSUE THREAD

**Issue by YingjiJu** [elastic/beats#3060]
I'm using filebeat5.0 to send events to logstash. Here is my configuration for filebeat.

filebeat.prospectors:
- input_type: log
  paths:
    - /home/spark/*.log
  ignore_older: 24h
  clean_inactive: 25h
  multiline.pattern: '^\[0-9]'
  multiline.negate: true
  multiline.match: after
  multiline.max_lines: 1000000
  max_bytes: 104857600
  multiline.timeout: 3m
output.logstash:
  hosts: ["localhost:5044"]
logging.level: debug
logging.files:
  keepfiles: 100

I have some files which is larger than 30M, filebeat is can find them and keeps watching these files, but it just doesn't send them to logstash and the offset in the registry file is always 0. But it works for new generated files which have small size. What the problem in this condition?

**Comment by ruflin** [comment]
I think this is a double post of https://discuss.elastic.co/t/filebeat-5-0-doesnt-work-for-large-files/66964/2 Please do not double post. I'm closing this so we can continue the discussion on discuss.
