### ISSUE TITLE
[Heartbeat] Investigate Logstash breaking screenshots

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#30615]
We've received reports that heartbeat is somehow, perhaps, mangling screenshots from synthetics. We should try to confirm / repro this.

Depending on what the nature of the issue is (if there even is a bug), we should consider whether supporting Logstash for synthetic monitors makes much sense. There's a lot to configure to get things right, and there's not a lot of benefit for the synthetics use case.

CC @drewpost @paulb-elastic

**Comment by andrewvc** [comment]
See also https://github.com/elastic/beats/issues/30628 , if we decide not to support this use case we won't go ahead here.

**Comment by jugsofbeer** [comment]
As this effects me, im wondering if its related to the connection to logstash and eventual disconnection of the tcp session. 

It is odd that when the screenshots are not displaying, that if we change the heartbeat to go direct to elasticsearch it repairs the broken ones and they display.

**Comment by paulb-elastic** [comment]
Discussed in refinement, we're not going to do this investigation, instead clarifying not to use LS with browser based monitors, as defined in https://github.com/elastic/beats/issues/30628
