### ISSUE TITLE
[Heartbeat] Clarify that non-direct ES connection from Heartbeat with browser monitors is not supported

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/beats#30628]
It is recommended for Heartbeat to connect directly to Elasticsearch when running with Synthetic (browser) monitors (as opposed to connecting via Logstash for example).  We should add a warning message in Heartbeat if running in this configuration, as well as update the documentation to clarify this.

ACs:
* If Heartbeat is running with at least one *browser* type monitor and the output is not configured directly to Elasticsearch, then log a warning message (`You are using Heartbeat with at least one browser monitor with a non-ES output, that is not supported!`)
* Update the documentation to clarify that it is only supported for Heartbeat to write directly back to Elasticsearch when using browser type monitors

**Comment by andrewvc** [comment]
Related to https://github.com/elastic/beats/issues/30615 , if we go ahead here we probably won't investigate that issue.

**Comment by emilioalvap** [comment]
Closing in favour of https://github.com/elastic/beats/issues/34725
