### ISSUE TITLE
Heartbeat: add support for DNS check 

### ISSUE THREAD

**Issue by nugroho-exp** [elastic/beats#30670]
**Describe the enhancement:**

Currently Heartbeat only supports HTTP, TCP and ICMP. It would be great if Heartbeat can support DNS check. 

See similar implementation by other solutions:

* https://grafana.com/docs/grafana-cloud/synthetic-monitoring/checks/#dns
* https://docs.datadoghq.com/integrations/dns_check/

**Describe a specific use case for the enhancement or feature:**

We have several DNS servers that we need to monitor to make sure it returns expected result. It would be nice to use heartbeat (elastic agent) to monitor those servers and display it in Uptime.

**Comment by BenB196** [comment]
Just an FYI, this post: https://discuss.elastic.co/t/heartbeat-tcp-dns-query/296180/2?u=benb196 examples how you currently monitor DNS via Heartbeat TCP check. It isn't very direct implementation, but works well from using it in the real world.

**Comment by nugroho-exp** [comment]
@BenB196  Thank you for the tips.

However we use elastic agent and processor is not supported yet and also it supports only reverse lookup and it does not support other record type such as A, TXT that we also want to check.

It would be great to have an easy DNS check setup using Fleet and use Kibana alerting to create an alert if DNS server does not return expected result.

**Comment by thethirstyturtle** [comment]
A DNS check is definitely needed for this type of service. Please add the functionality.
