### ISSUE TITLE
SQS message ChangeMessageVisibility error handling incomplete

### ISSUE THREAD

**Issue by montaguethomas** [elastic/beats#30675]
Filebeat version 7.17.0
Operating System: Linux

The checking of the error from `p.sqs.ChangeMessageVisibility` [here](https://github.com/elastic/beats/blob/d62ecf0d68a17dc0a569b27a3bffb55ccb31d7bd/x-pack/filebeat/input/awss3/sqs_s3_event.go#L190-L195) does not handle `InvalidParameterValue` cases.

The PR #29480 implemented a solution to stop the `keepalive` process when the `ReceiptHandle` became invalid. The problem is that SQS API can return both `ReceiptHandleIsInvalid` and `InvalidParameterValue` errors. See [here](https://aws.amazon.com/premiumsupport/knowledge-center/sqs-receipt-handle-error/) and [here](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/CommonErrors.html).

Of note, the aws-sdk-go lib does _not_ currently implement a constant for this error. I've created https://github.com/aws/aws-sdk-go/issues/4301 requesting it to be implemented.

When a keepalive ChangeMessageVisibility call is made after the receipt handle expired or hit maximum:
```
Extending SQS message visibility timeout.
Failed to extend message visibility timeout. sqs ChangeMessageVisibility failed: InvalidParameterValue: Value <REDACTED> for parameter ReceiptHandle is invalid. Reason: The receipt handle has expired.
	status code: 400, request id: <REDACTED>
```

When a message gets deleted but a keepalive ChangeMessageVisibility call is made still:
```
Extending SQS message visibility timeout.
Failed to extend message visibility timeout. sqs ChangeMessageVisibility failed: InvalidParameterValue: Value <REDACTED> for parameter ReceiptHandle is invalid. Reason: Message does not exist or is not available for visibility timeout change.
	status code: 400, request id: <REDACTED>
```

**Comment by andrewkroh** [comment]
PR: https://github.com/elastic/beats/pull/31499
