### ISSUE TITLE
[Metricbeat] Process modules produces very high load / cpu usage

### ISSUE THREAD

**Issue by dosera** [elastic/beats#30683]
After upgrading metricbeat from 7.11.2 to 7.16.3 I notice very high load/cpu usage for the metricbeat process.
I narrowed it down to the process module in combination with a python process.
Furthermore I tried several versions of which at least `7.17.x`, `7.16.x`, `7.15.x` and `7.14.x` are affected

**Version:** 7.16.3 (7.17.x, 7.15.x, 7.14.x)
**Operating System:** CentOS 7

#### Config

```
#==========================  Modules configuration ============================

metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - core
      - load
      - memory
      - network
      - process
    ticks: False
    enabled: True
    period: 10s
    process.cgroups.enabled: True
    processes:
      - .*
  - module: system
    metricsets:
      - diskio
      - uptime
    enabled: True
    period: 60s
  - module: system
    metricsets:
      - filesystem
      - fsstat
    enabled: True
    period: 60s
    filesystem.ignore_types: []

  - module: docker
    metricsets:
      - cpu
      - memory
    enabled: True
    period: 10s
    hosts:
      - "unix:///var/run/docker.sock"
  - module: docker
    metricsets:
      - container
      - event
      - healthcheck
      - info
      - network
    enabled: True
    period: 60s
    hosts:
      - "unix:///var/run/docker.sock"


#================================ General =====================================

# The 'name' property refers to the host name
# This field is added as "host.name" to the event
name: my-host
fields:
  env: production
tags:
  - myhost
max_procs: 2

#============================== Processors ====================================

processors:
  - add_host_metadata:
      netinfo.enabled: true
      cache.ttl: 60m

#================================ Outputs =====================================

output.logstash:
  enabled: true
  hosts:
    - logstash:6033
  index: metricbeat
  compression_level: 3
  worker: 1
  loadbalance: true
  pipelining: 0
  slow_start: true

output.console:
  enabled: false
  pretty: true

#================================ Logging =====================================

logging.level: info
logging.selectors: []

logging.to_syslog: false
logging.to_files: true
logging.files:
  rotateeverybytes: 10485760 # = 10MB
  keepfiles: 7
```

Any input is highly appreciated!

#### Workarounds:

* downgrade to 7.13.4
* disable the process module

**Comment by fearful-symmetry** [comment]
So, the only thing that changed in the process code between 7.14.0 and 7.13.4 was that we used the `system/memory` libraries to calculate process memory usage. So, if you aren't also seeing a spike in resource usage with the `memory` metricset as well, I suspect it might be something outside of process itself.

You can try adding the following to your system module config to see if this is more a processing issue with the volume of metrics, perhaps due to changes in other parts of metricbeat:

```
  process.include_top_n:
    enabled: true
    by_cpu: 5
```

the `system/process` metricset tends to ingest a fairly large number of metrics compared to other processes, so it could be exacerbating an underling issue. Does swapping the output from `logstash` to `file` have any change?

**Comment by dosera** [comment]
> So, the only thing that changed in the process code between 7.14.0 and 7.13.4 was that we used the `system/memory` libraries to calculate process memory usage. So, if you aren't also seeing a spike in resource usage with the `memory` metricset as well, I suspect it might be something outside of process itself.
Only the `process` metricset seems to be causing the issue

> You can try adding the following to your system module config to see if this is more a processing issue with the volume of metrics, perhaps due to changes in other parts of metricbeat:
> 
> ```
>   process.include_top_n:
>     enabled: true
>     by_cpu: 5
> ```

I tried this and with a current number of ~200 processes (`ps aux | wc -l`) `top_n` has an effect as can be seen in the following graph:

![metricbeat_cpu_usage](https://user-images.githubusercontent.com/10059422/157631056-d1fd07f2-9a9e-4c9e-b43d-35076576d57b.png)

> Does swapping the output from `logstash` to `file` have any change?

Changing the output did not have an effect.

**Comment by germain05** [comment]
+1

**Comment by germain05** [comment]
👍
