### ISSUE TITLE
can't filter the dedicated process in metricbeat

### ISSUE THREAD

**Issue by sitanxin** [elastic/beats#3069]
- Version: metricbeat 5.0
- Operating System: RHEL 6
- Steps to Reproduce: 
When I use metricbeat to collect the process informaiton, it works well with ['.*'], but when I want to only show some dedicated process (like include path as keywork /bpms/IS01_1111), ['.*/bpms/IS01_1111.*'], then it can't fetch any process information. Would you advise how to set the expression?

**Comment by tsg** [comment]
It's better to open these kind of questions on discuss, because more people from the community can help there, and we're trying to reserve Github for confirmed bugs and enh requests only.

Please try: `['\\.\\/bpms\\/IS01_1111.*']`
