### ISSUE TITLE
[Filebeat] Increase Number of Logs Pulled from Okta

### ISSUE THREAD

**Issue by dfavero** [elastic/beats#30700]
**Describe the enhancement:** The Okta module in Filebeat should pull more logs by default from the Okta appliance per pull. By default, the API returns 100 events per pull. For larger environments, this is insufficient given the other rate limits. The API allows us to pull a maximum of 1000 events per pull. The limit should be increased by default to 1,000. Documentation here: https://developer.okta.com/docs/reference/api/system-log/#request-parameters

**Describe a specific use case for the enhancement or feature:** For larger environments, 100 events per pull is insufficient. More events are created than we can pull and we are slowly falling behind for logon events.

**Comment by jamiehynds** [comment]
Closing as we're tracking via this issue in the integrations repo: https://github.com/elastic/integrations/issues/2776
