### ISSUE TITLE
tail_files does not work with filestream in filebeat(v7.4.2)

### ISSUE THREAD

**Issue by zenglingmin168** [elastic/beats#30725]
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
  tail_files: true
I configure tail_files true,but filebeat still read at the beginning position of file.

**Comment by jlind23** [comment]
@zenglingmin168 you are using a pretty "old" version of filebeat. Any change to upgrade?

**Comment by zenglingmin168** [comment]
But after I tried filebeat-8.0.0,it still had problem,the configuration is as follows:
filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/log/*.log
  ignore_inactive: since_last_start

**Comment by jlind23** [comment]
Ok, thanks for the update. Could you please then open a discuss question before creating a bug issue here? Our engineers will look at it and try to provide you some guidance as soon as possible.

**Comment by zenglingmin168** [comment]
OK，thank you，I ask question in Discuss forum now.

**Comment by zenglingmin168** [comment]
I hava commit a question on the Discuss forum just now.

**Comment by jlind23** [comment]
Closing for now and we will reopen it if it is a real bug.

**Comment by zenglingmin168** [comment]
ok,thanks!
