### ISSUE TITLE
Updated Filebeat to 5; not working after copying registry

### ISSUE THREAD

**Issue by mrjameshamilton** [elastic/beats#3072]
I installed Filebeat via the RPM, copied the config file, and the old registry file to the new location. And now Filebeat does not read any new logs. There are no errors and in the Filebeat log it says it upgraded the registry file entries. But there are no new entries being forward to Logstash.

**Comment by mrjameshamilton** [comment]
OK, I did something - not sure what - but it's working now.

**Comment by ruflin** [comment]
@mrjameshamilton Let us know in case you see this again in the future.
