### ISSUE TITLE
why my packetbeat keeps logging sniffer/sniffer.go:185  Interrupted

### ISSUE THREAD

**Issue by yangwangxing** [elastic/beats#30731]
why my packetbeat keeps logging sniffer/sniffer.go:185  Interrupted.

And I notice that my packetbeat flow.final = true statistic not correct, source.bytes and destication.bytes always smaller than the actual size. 
Maybe Interrupted caused some network packet not calculated and dropped?

Packetbeat version: 7.12.1 7.11.1
OS: centos

**Comment by efd6** [comment]
>Maybe Interrupted caused some network packet not calculated and dropped?

Yes, this is the case. The log line you see will happen if either the packet capture times out polling for a new packet (the timeout value is hard-coded at 500ms) or the poll call was interrupted by a signal — the first is more likely here.

We have updated the backing library that does the packet capture work in 8.0. Are you able to try that to see if this improves the situation?

**Comment by yangwangxing** [comment]
thanks, I'll try that first and rely later

**Comment by yangwangxing** [comment]
same in 8.0 and 8.1
