### ISSUE TITLE
Winlogbeat - Reading large events causes error "The array bounds are invalid."

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#3076]
- Version: 5.0.2 (probably exists in all versions)
- Operating System: Windows 2012 Server R2 (probably affects Vista and newer)
- Steps to Reproduce: 

When reading a batch of large event log records the Windows function [`EvtNext`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa385405%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) returns errno 1734 (0x6C6) which is [RPC_S_INVALID_BOUND](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681386(v=vs.85).aspx#RPC_S_INVALID_BOUND) ("The array bounds are invalid."). This seems to be a bug in Windows because there is no documentation about this behavior.

It seems that when calling `EvtNext` that internally it is allocating space for the events whose handles it will return. So if the combined size of the events being returned by `EvtNext` reaches some limit the RPC_S_INVALID_BOUND error is returned. In Winlogbeat, if you increase the `batch_read_size` you are more likely to encounter the problem, but even with a `batch_read_size` of 64 (default is 100) I was able to hit the error when reading large events.

Recovering from this problem is not as simple as calling `EvtNext` again with a smaller batch size. The internal read position associated with the event log handle is being updated even when `EvtNext` returns the RPC_S_INVALID_BOUND error. So if we just called it again we would lose events. We will have to close the event log and re-open it from the last read event and decrease the `batch_read_size` until success.

- Workaround: Set a lower value for `batch_read_size`.

**Comment by maddin2016** [comment]
Hi @andrewkroh, i have found [this](https://msdn.microsoft.com/de-de/library/windows/desktop/aa363679(v=vs.85).aspx) (See return values). Maybe there are events which are too large. So it's not the count of the events more the size of each event.

**Comment by andrewkroh** [comment]
@maddin2016 Thanks for investigating a bit. I did see the link that you posted and I had the same suspicion originally. I wrote a test case keeps the individual event size constant and continuously decreases (starting from 1024) the number of event handles that it tries to read. Once the number of events to read was small enough (around 32 with ~32k events), `EvtNext` returned without an error and was able to read each of the events.

**Comment by maddin2016** [comment]
So this means we should max the handles from (what is the actually max?) to 32 to read from? But i think it's more a problem of size. Maybe we reach the limit with 10 handles if there are "big" events inside.

**Comment by andrewkroh** [comment]
I determined empirically on Windows 2012 that the maximum number of handles that can be read is 1024. Anything greater returns an invalid parameter error.

Using a larger batch size seems to have a positive impact on the read throughput. So having some sort of "dynamic" batch size that can decrease when these errors occur would be ideal. Need to do some tests and benchmarks.

**Comment by maddin2016** [comment]
Hi @andrewkroh, what do you think of this
```
func EventHandles(subscription EvtHandle, maxHandles int) ([]EvtHandle, error) {
	eventHandles := make([]EvtHandle, maxHandles)
	var numRead uint32

	err := _EvtNext(subscription, uint32(len(eventHandles)),
		&eventHandles[0], 0, 0, &numRead)
	if err != nil {
		// Munge ERROR_INVALID_OPERATION to ERROR_NO_MORE_ITEMS when no handles
		// were read. This happens you call the method and there are no events
		// to read (i.e. polling).
		if err == ERROR_INVALID_OPERATION && numRead == 0 {
			return nil, ERROR_NO_MORE_ITEMS
		}
		if err == RPC_S_INVALID_BOUND {
			return EventHandles(subscription, maxHandles/2)
		}
		return nil, err
	}

	return eventHandles[:numRead], nil
}
```
So if we detect the error, just half the maxread and try again. I have tested, but the recursion not working correctly. How can i achive this in go??
