### ISSUE TITLE
Network keyword in log files can lead to indexation failure

### ISSUE THREAD

**Issue by robeatoz** [elastic/beats#30775]
Like https://github.com/elastic/beats/issues/30667 with keyword `network`. 

The `filebeat` container logs:

```json
{
  ...
  "message": "Error dialing dial tcp 172.21.0.2:9200: connect: connection refused",
  "network": "tcp",
  ...
}
```

This causes the following log in the `filebeat` container:

```json
{
  "type": "mapper_parsing_exception",
  "reason": "object mapping for [network] tried to parse field [network] as object, but found a concrete value"
}
```

Because of [ECS Network Fields](https://www.elastic.co/guide/en/ecs/current/ecs-network.html)

For confirmed bugs, please report:
- Version: `8.1.0`
- Operating System: `Docker on Ubuntu`
- Discuss Forum URL: `-`
- Steps to Reproduce: 
  - Use the minimal showcase in https://github.com/robeatoz/filebeat-minimal-showcase
  - Follow the steps described here: https://github.com/elastic/beats/pull/30482#issuecomment-1052776114
  - Restart the Elasticsearch container

**Comment by jsoriano** [comment]
Hey @robeatoz,

Thanks for reporting, I think the issue is in https://github.com/elastic/beats/blob/42c5c678648f84db75dfa6bf7056ef0e0aa6d65d/libbeat/common/transport/logging.go#L34

These fields end up in logs and should follow ECS.
