### ISSUE TITLE
[Heartbeat] Config validation is not as thorough as it could be

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#30786]
We could be more thorough in terms of config validation

- [ ] We currently do not properly validate `schedule` entries when loading configs. We should reject invalid schedules such as `m` where possible. Only valid schedules such as `3m` should pass.
- [ ] Having no config file still returns a `Config OK`.
- [ ] Renaming `hosts` to `host` still returns `Config OK`

**Comment by lowryxiao** [comment]
If no one started to working on this issue, I'd like to contribute the changes.

**Comment by andrewvc** [comment]
I'd be glad to accept these changes, thanks @lowryxiao ! 

One thing to note, we've improved our error strategy over the past year, where in the past we'd usually just log an error then not run the monitor, errors now passed up at monitor creation / validation time should still 'run' every $interval, just always return an error. The  reason is it's generally better for the error to appear in the Uptime UI or Kibana dashboards via the `error.*` fields, which requires documents to be sent. It's much less confusing than digging through logs.

Take a look at https://github.com/elastic/beats/blob/main/heartbeat/monitors/monitor.go#L154 which is the key place where we surface those errors. In general, I'm 70% certain this block would catch any new validations you add and do the right thing, but I thought I'd mention it since it's important to keep in mind.

Another thing to note, we're trying to conform all new errors to the ECS error field definitions, and are consolidating them here: https://github.com/elastic/beats/blob/main/heartbeat/ecserr/ecserr.go

**Comment by lowryxiao** [comment]
Sorry for the delay, I'm still working on it, will file a PR soon.
