### ISSUE TITLE
[doc improvement] Add footnote to section under log file beats shipper

### ISSUE THREAD

**Issue by louisong** [elastic/beats#30792]
In 8.1.0, osquerybeat logs for Osquery Manager switched from .json to .ndjson.
Would make sense if we could add existing [footnote](https://www.elastic.co/guide/en/fleet/8.1/installation-layout.html#_footnoteref_1) to the "Log file beats shipper" section as well.

```
Logs file names end with a date and optional number: log-date.ndjson, log-date-1.ndjson,
and so on as new files are created during rotation.
```

<img width="780" alt="Screenshot 2022-03-14 at 3 07 49 PM" src="https://user-images.githubusercontent.com/26863726/158121856-688e39c8-52d0-42ac-88e3-c5ce9cb0d323.png">

**Comment by dedemorton** [comment]
cc @elastic/ingest-docs
