### ISSUE TITLE
[Packetbeat]After the version of packetbeat8, an error is reported after opening af_packet mode

### ISSUE THREAD

**Issue by chinaxushi** [elastic/beats#30822]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version:  Packetbeat 8.0    8.01   8.10
- Operating System:  Rocky Linux 8.5
- Discuss Forum URL: https://discuss.elastic.co/t/packetbeat8-0-af-packet-report-errors/298180
- Steps to Reproduce:  Add "packetbeat. Interfaces. Type: af_packet" in the default configuration file, and nothing else will be changed
                                     ./packetbeat -c packetbeat.yml

After the "af_packet" mode is enabled in the configuration file, Packetbeat will report an error and prompt "exiting: sniffer loop failed: sniffing error: packet poll timeout expired"
On the same machine, Packetbeat7.17 has no problem running the same configuration file
In most cases, it will report an error and exit soon. Occasionally, it will exit after running for a period of time. Today, it has been running for more than 2 minutes

`{"log.level":"info","@timestamp":"2022-03-02T15:07:30.143+0800","log.logger":"monitoring","log.origin":{"file.name":"log/log.go","file.line":193},"message":"Uptime: 2m0.402134077s","service.name":"packetbeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-02T15:07:30.143+0800","log.logger":"monitoring","log.origin":{"file.name":"log/log.go","file.line":160},"message":"Stopping metrics logging.","service.name":"packetbeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-02T15:07:30.143+0800","log.origin":{"file.name":"instance/beat.go","file.line":504},"message":"packetbeat stopped.","service.name":"packetbeat","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-03-02T15:07:30.143+0800","log.origin":{"file.name":"instance/beat.go","file.line":1025},"message":"Exiting: sniffer loop failed: Sniffing error: packet poll timeout expired","service.name":"packetbeat","ecs.version":"1.6.0"}
Exiting: sniffer loop failed: Sniffing error: packet poll timeout expired`

**Comment by efd6** [comment]
Related https://github.com/elastic/beats/issues/30731 which also appears to affect 7.12.1 and 7.11.1.

**Comment by chinaxushi** [comment]
This problem seems to be caused by the update of libbeat in versions after 8.0

**Comment by efd6** [comment]
@chinaxushi Can you confirm that this does not affect your use with 7.12.1 and 7.11.1? It would be good to be know if these are separate issues.

**Comment by efd6** [comment]
@chinaxushi I identified the cause and am working on a fix, so you do not need to test those versions.

**Comment by chinaxushi** [comment]
> @chinaxushi I identified the cause and am working on a fix, so you do not need to test those versions.

I was just about to say to find the version for testing, and I saw your reply.

**Comment by efd6** [comment]
In the mean time, as you know from having posted it on the discuss forum (thankyou, it was very helpful in tracking down the issue), a work around until the fix is released is to use pcap instead of af_packet.
