### ISSUE TITLE
Flaky Test - Metricbeat kubernetes/controllermanager TestFetchMetricset

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#30834]
## Flaky Test

* **Test Name:** metricbeat/module/kubernetes/controllermanager TestFetchMetricset
* **Link:** Link to file/line number in github.
* **Branch:** 7.17
* **Artifact Link:** https://beats-ci.elastic.co/job/Beats/job/beats/job/7.17/183/
* **Notes:** Branch and PR builds to 7.17 have been failing.

<img width="335" alt="Screen Shot 2022-03-15 at 18 28 29" src="https://user-images.githubusercontent.com/4565752/158482858-4ce7b782-af0f-4be2-8891-97e1ee3c286d.png">

### Stack Trace

```
 === Failed
 === FAIL: metricbeat/module/kubernetes/controllermanager TestFetchMetricset (0.01s)
     controllermanager_integration_test.go:37: Expected 0 error, had 1. [error getting processed metrics: error making http request: Get "http://localhost:10252/metrics": dial tcp [::1]:10252: connect: connection refused]
 
 === FAIL: metricbeat/module/kubernetes/scheduler TestFetchMetricset (0.00s)
     scheduler_integration_test.go:37: Expected 0 error, had 1. [error getting processed metrics: error making http request: Get "http://localhost:10251/metrics": dial tcp [::1]:10251: connect: connection refused]
 
 DONE 32 tests, 2 failures in 64.192s
 Error: failed modules: kubernetes

```

**Comment by tetianakravchenko** [comment]
Fix PR: https://github.com/elastic/beats/pull/30870
