### ISSUE TITLE
Security vulnerabilities glibc-2.31-0ubuntu9.2 and golangruntime-1.17.6

### ISSUE THREAD

**Issue by vishrantgupta** [elastic/beats#30875]
I am using filebeat version 8.1.0, in the vulnerabilities scan I see the attached issues
[export.pdf](https://github.com/elastic/beats/files/8268851/export.pdf)

**Comment by andrewkroh** [comment]
What did you scan to get this report? The tar.gz, rpm, and deb distributions do not include glibc (the binaries are linked with libc but don't actually include it) and will use your system's glibc as found at runtime.

**Comment by vishrantgupta** [comment]
I used the latest docker image:

```
docker pull docker.elastic.co/beats/filebeat:8.1.0 | gzip > filebeat_8.1.0
```

this created the gzip file which I used to scan the filebeat.

**Comment by andrewkroh** [comment]
On the each release the packages inside the container are updated to the latest from the upstream apt repo. So that should bring in a new glibc version.

We are updating to Go 1.17.8 in https://github.com/elastic/beats/pull/30787. That will probably be released with 8.1.2.

**Comment by andrewkroh** [comment]
The project is on Go 1.17.8 now. https://github.com/elastic/beats/pull/30787

**Comment by vishrantgupta** [comment]
@andrewkroh what is the expected release date for 8.1.2?

**Comment by andrewkroh** [comment]
Early April.

**Comment by vishrantgupta** [comment]
@andrewkroh filebeat 8.1.2 continues to have critical vulnerabilities, and it's still using Go version 1.17.6:

![image](https://user-images.githubusercontent.com/1741243/161801613-511c1b26-bb99-4e0d-b54a-6c1b01adf855.png)

![image](https://user-images.githubusercontent.com/1741243/161801665-a7ebe5fb-a545-440e-ab7b-8ddce065983a.png)
