### ISSUE TITLE
Filebeat fails with journald input

### ISSUE THREAD

**Issue by Azertooth** [elastic/beats#30919]
```
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.
```
[Inputs error journald](https://discuss.elastic.co/t/inputs-error-journald/299804)

The problem highlighted in [#30797](https://github.com/elastic/beats/issues/30797) persist.
I need to ingest journald and while I was successfully doing it with journalbeat, [it's adviced](https://www.elastic.co/guide/en/beats/journalbeat/current/journalbeat-overview.html) to switch to filebeat with journald input instead. But when I try to setup filebeat (latest version, 8.1) the service stops as it's started with this error

`Exiting: Failed to start crawler: starting input failed: Error while initializing input: Error creating input. No such input type exist: 'journald'`

Although journald it's stated as a valid input both in the online [Filebeat Reference [8.1]](https://www.elastic.co/guide/en/beats/filebeat/8.1/index.html) and in the package filebeat.reference.yml file, it seems like it was removed somehow or at least that's my guess.

It's a production breaking problem so please do not automatically close this without interaction

**Comment by kvch** [comment]
@andrewkroh Is this expected? I thought we enabled journald input by default.

**Comment by Azertooth** [comment]
> > Is this expected? I thought we enabled journald input by default.
> 
> That is not expected. Linux builds use the `withjournald` tag.
> 
> https://github.com/elastic/beats/blob/432675080bccb0afbbb721739c8046b3d775b7e2/filebeat/scripts/mage/build.go#L61
> 
> The input is present in the 8.1.0 build I checked. @Azertooth what specific package type (tar.gz, rpm, deb, docker) are you using and what architecture?
> 
> ```
> $ cat filebeat.journal.yml 
> filebeat.inputs:
> - type: journald
> 
> output.console.pretty: true
> 
> $ docker run -it --rm -v `pwd`:/fb docker.elastic.co/beats/filebeat:8.1.0 filebeat -c /fb/filebeat.journal.yml -e
> {"log.level":"info","@timestamp":"2022-03-21T14:35:08.250Z","log.logger":"beat","log.origin":{"file.name":"instance/beat.go","file.line":1057},"message":"Build info","service.name":"filebeat","system_info":{"build":{"commit":"da4d9c00179e062b6d88c9dbe07d89b3d195d9d0","libbeat":"8.1.0","time":"2022-03-03T17:04:28.000Z","version":"8.1.0"},"ecs.version":"1.6.0"}}
> {"log.level":"info","@timestamp":"2022-03-21T14:35:25.424Z","log.logger":"input.journald","log.origin":{"file.name":"compat/compat.go","file.line":132},"message":"Input 'journald' stopped","service.name":"filebeat","id":"C103E8C237E2290E","ecs.version":"1.6.0"}
> ```

Hi @andrewkroh and thank you for joining
I'm using the [arch aur package](https://aur.archlinux.org/packages/filebeat) that's stated to be built on `beats-8.1.0.tar.gz`

**Comment by andrewkroh** [comment]
You should file an issue with archlinux. They are not using the binary packages Elastic produces.

Our builds use `mage crossBuild` which builds the binaries for all platforms in a linux/amd64 Docker container. The containerized build environment includes the necessary build-time dependencies like systemd. The build enables the `withjournald` build tag which includes the journald input.

If they are not using the `crossBuild` target then Beats might need to add way to set build tags as part of the `mage build` command (like via an env var) to be friendly with their build setup.

**Comment by Azertooth** [comment]
> You should file an issue with archlinux. They are not using the binary packages Elastic produces.
> 
> Our builds use `mage crossBuild` which builds the binaries for all platforms in a linux/amd64 Docker container. The containerized build environment includes the necessary build-time dependencies like systemd. The build enables the `withjournald` build tag which includes the journald input.
> 
> If they are not using the `crossBuild` target then Beats might need to add way to set build tags as part of the `mage build` command (like via an env var) to be friendly with their build setup.

Thank you for your time and this detailed insight, I will proceed that way
