### ISSUE TITLE
Support special characters in password across modules

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#30947]
### Problem

- Metricbeat module doesn’t understand all characters that some systems identifie as valid characters for a password. Enterprise companies usually use password generation tools that create strong passwords with special characters like `%` and `\`. This problem exists with every Elastic integration available.

### Solution

- Metricbeat must be able to accept any character displayed on your keyboard in any sequence or any repetition.

### Use Story

- As an Elastic metricbeat user, I want metricbeat to understand all characters available on a keyboard for the password field value so that I could use automatic password generation tools to create strong passwords for authentication.

**Comment by taylor-swanson** [comment]
Related SDH: elastic/sdh-beats#2742 (Oracle Integration/sql metricbeat module)
