### ISSUE TITLE
[Oracle Module] Improve connection documentation

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#30949]
### Problem

- Oracle module’s documentation is confusing and not updated. Currently, it states that Oracle client must be installed as a pre-requisite which is not true. If you have OCI Oracle server which comes with these libraries pre-installed, you don't need a separate client installation, all you need is just the correct configuration settings. Since in this case, Oracle metricbeat module is tied to systemD running on Linux so the trick is to create a systemD configuration file that is pulled when metricbeat starts. This configuration file would provide environment variables that will help the Oracle module in finding the required libraries. It can take new customers weeks to figure out and troubleshoot.
### Solution

- Connectivity to Oracle can be facilitated in two ways either by using official Oracle libraries or by using a JDBC driver. These two approaches must be clearly spelled out in the documentation, whether they are supported or not and what libraries and settings must be configured, and where. Clear workflows and steps must be documented in a blog or a documentation page.

### User Story

- As an Oracle DBA and first-time Elastic user, I would like Elastic documentation to handhold me and clearly provide configurations for different Oracle setups and connectivity options so that I could understand how Oracle connects with Elastic Cloud and doesn’t have to waste time in experimentation and troubleshooting.

**Comment by yug-elastic** [comment]
Based on our analysis, there does not seem to be a way to connect the Oracle instance with Metricbeat using JDBC Drivers. We would need a Java Application to connect with the database using JDBC. There might be a way to facilitate a connection using logstash, but it seems kind of irrelevant for our use case.

Is there any other way it is supported in the existing module? Or should we explicitly call it out in the documentation that it is not supported?

**Comment by mtojek** [comment]
I have a feeling that this issue falls into the @elastic/obs-service-integrations domain. It would be nice to pair with the team. cc @rameshelastic

**Comment by agithomas** [comment]
Looking into it.
