### ISSUE TITLE
[Filebeat][Okta] Parse additonal debug data risk field for Okta module

### ISSUE THREAD

**Issue by ynirk** [elastic/beats#30961]
**Describe the enhancement:**

This request is similar to #25689

Okta enrich their system log events with a risk score [ref](https://help.okta.com/en/prod/Content/Topics/Security/Security_Risk_Scoring.htm) in `debugContext.debugData.risk` but it's not parsed by filebeat and it would be valuable.

Exemple of values extracted from `event.original`:

```
"risk":"{reasons=Suspicious rate of requests, level=HIGH}"
"risk":"{level=HIGH}"
```

In addition to parse `debugContext.debugData.risk` field, other information might be valuable in `debugData` and it could be a flattened field

**Describe a specific use case for the enhancement or feature:**

A security analyst would need the risk score parsed in order to build a detection from it.

**Comment by efd6** [comment]
@ynirk Are you able to provide a few redacted example log lines to include in tests?

**Comment by efd6** [comment]
Thanks. I'll see how far I get and may get back to you with more questions.

**Comment by efd6** [comment]
@ynirk I've made a sketch of this for the okta integration first (elastic/integrations#3362), since it's easier to work there. Would you take a look to confirm that it is what you were looking for, once that's done, I'll port over to filebeat.

**Comment by ynirk** [comment]
@efd6 I made some comments there. I did not realize Okta format is also not consistent depending on risk field location - it's a bit painfull

**Comment by efd6** [comment]
> I did not realize Okta format is also not consistent depending on risk field location - it's a bit painfull

Yes, that's why I pulled it out into `okta.debug_context.debug_data.risk_level` as a consistent format.
