### ISSUE TITLE
Filebeat stops updating registry

### ISSUE THREAD

**Issue by sprysprocket** [elastic/beats#3098]
It appears that the combination of publish_async and loadbalance can cause filebeat to stop updating the registry. Filebeat's basic functions seem to continue unabated, with new files being prospected, and log lines being shipped to the logstash cluster. The registry is simply not updated to make the state durable.

This issue is based on the discussion thread located [here](https://discuss.elastic.co/t/filebeat-stops-updating-the-registry/67553). The thread contains all of the information regarding software versions, filebeat configuration, as well as links to the [filebeat logs and registry](https://gist.github.com/sprysprocket/a0467aed961ea41d9ec21aba8323b069). I will continue to use that thread to record the results of any actions taken as part of the investigation.

**Comment by sprysprocket** [comment]
Thanks @ruflin for the ping. I updated the discussion to indicate that the reported issue was for CentOS 6.x, not Windows.

**Comment by urso** [comment]
The issue has not been updated for a long time + investigation did eventually stop. The outputs, pipelines, ACK handling and registry writing have been change a lot since. Please comment if the issue still occurs with the recent Beats versions and we can reopen the issue for investigation. Thanks.
