### ISSUE TITLE
[Filebeat] Input to ingest data from WebSocket API

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#30991]
As a user I would like to be able to ingest data from an API that use a WebSocket based connection. Filebeat would establish a WebSocket connection to the server and then the server would push messages to Filebeat. Each message may be compressed (e.g. deflate, gzip).

An example API is Proofpoint. https://docs.cyderes.cloud/files/proofpoint-on-demand-log-api-rev-c.pdf

**Comment by SpencerLN** [comment]
+1. An input that acts as a client for a generic WebSocket server would be useful for multiple integrations. For example, I stumbled on this issue when looking for a way to ingest [Certstream](https://certstream.calidog.io/) data.
