### ISSUE TITLE
Improve loading time of Kubernetes package Dashboards 

### ISSUE THREAD

**Issue by MichaelKatsoulis** [elastic/beats#31021]
We have found some opportunities for optimization in the dashboards::

1. Top CPU intensive pods gets the max of `kubernetes.container.cpu.usage.core.ns`, then uses derivative aggregation over it and keeps the positive values.  We can simply use `kubernetes.container.cpu.usage.node.pct` instead and group by the pod name. 

2. Same for Top Memory intensive pods

3. CPU Usage by node sums all cpu usage nanocores per container, then uses a painless script to normalise it to the metricset period and groups by the node name. Instead we can use the node metric `Kubernetes.node.cpu.usage.nanocores` and divide it with `kubernetes.node.cpu.allocatable.cores`. Same approach is used in metrics UI

4. Same for Memory Usage by node. We can divide `kubernetes.node.memory.usage.bytes` to `kubernetes.node.memory.allocatable.bytes`  

5. Same approach for network in and out bytes

I tested that by creating a separate dashboard with all those visualisations optimised and the loading time for 24h range decreased from 1m and 10 seconds down to 30 seconds.

**Comment by MichaelKatsoulis** [comment]
My suggestion regarding the default kubernetes dashboard optimization is to split it into 2 different dashboards.
The split can be based on the concept of each visualisation's data.
Meaning that some of them make sense to be displayed per time, while others make more sense to display  the current value as a number.

For example for the number of available/desired/unavailable  pods or number of nodes  it is most important is to display  the current situation in the cluster.

While for other visualisations like `Top CPU intensive pods` or `CPU utilization per node` it would be insightful to display the evolution of the value per time. A user would like to see how the cpu utilisations of a specific pod or node has changed over the past week.

The two dashboards could like this: 

Time series dashboard:

<img width="1662" alt="kubernetes 2 1" src="https://user-images.githubusercontent.com/26270880/160821319-210704db-6e23-4458-9174-a1480592db85.png">

<img width="1653" alt="kubernetes 2 2" src="https://user-images.githubusercontent.com/26270880/160816908-d868320a-c6c6-4166-babc-62273dad1015.png">

Current state dashboard:
<img width="1768" alt="Kubernetes last value" src="https://user-images.githubusercontent.com/26270880/160818896-b2b17384-abd0-47d8-b68a-995af7f4efb5.png">

This grouping can make the dashboards more performant as less queries will be performed simultaneously. 
Also costly queries with aggregations over big time range will only be performed for the vis that make sense.

**Comment by MichaelKatsoulis** [comment]
cc @ChrsMark , @tetianakravchenko , @ruflin

**Comment by ruflin** [comment]
++ on splitting up the dashboards. Will the dashboards link to each other?

**Comment by ChrsMark** [comment]
That would be great. We do the same for [Istio module](https://github.com/elastic/beats/tree/main/x-pack/metricbeat/module/istio/_meta/kibana/7/dashboard) to split the control plane from data plane views:
https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-istio.html#_dashboard_30

**Comment by MichaelKatsoulis** [comment]
Yes I was thinking something like Istio tab view! That would be great! Does this allow to set different time ranges to each one?

**Comment by ruflin** [comment]
I thought by now there is a new / better way on how to link dashboards together. @alexfrancoeur You might be able to point us to the right direction here?

**Comment by alexfrancoeur** [comment]
Thanks for the ping @ruflin. I think there are a number of best practices these integration dashboards can start to leverage. I've listed a bunch [here](https://github.com/elastic/integrations/issues/269#issuecomment-854122717) in the past. 

Kibana has drilldown capabilities in a dashboard (https://www.elastic.co/guide/en/kibana/current/drilldowns.html#create-drilldowns). This is great for creating workflows from dashboard to dashboard. An overview dashboard to a details dashboard for example. We support dashboard to dashboard and dashboard to external URLs (paid feature). For the integrations dashboard, a combination of markdown for general navigation and drilldowns for workflows is probably the best option.

If you'd like to sit down with some kibana folks and discuss best practices, we're happy to engage. For example we no longer need to ship 100's of visualizations referenced by a dashboard, we can simplify to package all in a single dashboard JSON now.

This is off topic, but while we're on the topic of dashboard linking, I think it's worth raising if we should be linking to solutions as well. There is probably some low hanging fruit here. Rather than taking that context and navigating to a dashboard, we could apply it to a solution view to create solution drilldowns. I hack together this all the time for demos using the URL drilldowns. Meaning if there's a host IP in a dashboard, let's click into that to navigate to a filtered view in the metrics app. Building these experiences as part of our integrations add for a much more integrated experience when onboarding a new data source. If there's interest in collaborating on something like this, let's have a quick chat with myself and @sixstringcode

**Comment by ruflin** [comment]
Thanks for the list @alexfrancoeur . The drilldown one is the one I was looking for. There lots of other great hints in the issue you linked.

About "as value" I just had a conversation with your team and we should figure out ways how to automatically convert it. @ChrsMark @MichaelKatsoulis If we redo the k8s dashboards, lets use these best practices directly as an example and also switch to "value".

On the linking to solutions, ++. It is a topic we should also involve @jasonrhodes from unified observability.

**Comment by ruflin** [comment]
I've been attending the TSDB meeting yesterday and @Mpdreamz showed off a demo for using TSDB in APM. A first version of the metrics parts are merged into main in Elasticsearch and available in the snapshot builds. I think it is also worth trying this out for the k8s data to see what impact it has.

My understanding is that currently the storage and query part are available but we can't make use of it yet in Kibana. Also in the package-spec we don't support the time series fields yet. What it means is that we have to adjust the templates manually and see what affect it has.

@imotov Tried to find some public docs I can point the team to around mappings and TSDI but was not successful. Is this already available?

**Comment by ruflin** [comment]
I filed https://github.com/elastic/package-spec/issues/311 to get support for TSDB in the package-spec.

**Comment by MichaelKatsoulis** [comment]
Additional thoughts following @ChrsMark suggestions in https://github.com/elastic/enhancements/issues/14008#issuecomment-1088524593

We could have:
1. Different dashboards per Kubernetes resource (deployments, Daemonsets, StatefulSets) with useful informations for the pods controlled by them (cpu, memory, network, disk). 
2. Each dashboard could have a dropdown menu where user can choose pods of which namespace and which deployment/daemonset/statefulset name to see metrics for.
3. Separate dashboard for node metrics of the cluster with dropdown menu for each node name.
4. An overview dashboard with some cluster wide information (number of deployments replicas available , number of daemonset replicas available , number of nodes). Each of the vis of this dashboard can be a drill down that leads to the more detailed dashboards  of step 1 and 3.
5. Stream/log k8s events should also be part of the dashboards.

**Comment by ruflin** [comment]
@MichaelKatsoulis I like your proposal above. It would be great if we could work on these dashboards in collaboration with the team from @flash1293 We can't necessarily achive everything with Lens now and all the other great features in Kibana but we should be able to eventually. Please keep the conversations going.

**Comment by MichaelKatsoulis** [comment]
I played around with drill down. It doesn't work exactly as demonstrated and documented in https://www.elastic.co/guide/en/kibana/current/drilldowns.html#_create_the_dashboard_drilldown. I was expecting a `Go to dashboard` option when creating a new drill down. But I only see a `Go to URL`. I use version 8.1.2 and also tried with 8.2.0-SNAPSHOT.
<img width="1785" alt="Drilldown 8 1 2" src="https://user-images.githubusercontent.com/26270880/162169810-fe38b667-0d1c-43b5-b065-1e49d3e91159.png">

**Comment by flash1293** [comment]
@MichaelKatsoulis This is expected for metric visualizations - the "Go to Dashboard" drilldown is tied to the filter trigger, that means it's only shown in case the visualization can place a filter (and if it happens, it will prompt the user to go to the other dashboard instead). There are no plans for TSVB, but we do plan to add this functionality for Lens metric visualizations: https://github.com/elastic/kibana/issues/122879

**Comment by MichaelKatsoulis** [comment]
@flash1293 thanks for the clarification. To be honest I don't understand why it is tied to the filter trigger. 
In our case I want an overview dash like
<img width="1633" alt="Overview Dash" src="https://user-images.githubusercontent.com/26270880/162184245-1f56566c-1263-4e22-87c6-fc1fe7219091.png">

and when the user wants to see extra detailed info for the Nodes(currently tsvb but could be lens) it will point to
<img width="1783" alt="Node details" src="https://user-images.githubusercontent.com/26270880/162184380-073fb6d8-cefc-48d7-8f11-9053725d28e6.png">

I have currently created drilldown with `go to URL` but this won't work for an out of the box dashboard as the url of the dash will be different.

**Comment by flash1293** [comment]
Completely agree, that’s what we will work on for Lens in 8.3

**Comment by MichaelKatsoulis** [comment]
@flash1293 I agree with your second bullet. That would be a good way. As it is now, there is no way a user can understand there is something more. The word `drilldown` also does not mean anything to someone that doesn't know what it is.

**Comment by MichaelKatsoulis** [comment]
As an update for the effort so far:

I have created the following dashboards which are connected with drilldown (with `go to url`, waiting for the `go to dashboards` in lens)
<img width="1660" alt="Kubernetes Overview" src="https://user-images.githubusercontent.com/26270880/162228037-a7ff6300-a21b-4b51-adf1-bc410f93501e.png">
<img width="1788" alt="Nodes details" src="https://user-images.githubusercontent.com/26270880/162228050-1a38ae90-36d1-4940-87ea-80f665869981.png">
<img width="1725" alt="Pods Details" src="https://user-images.githubusercontent.com/26270880/162228061-63bc7a21-74ed-4383-b724-67cd7fca359b.png">
<img width="1783" alt="Deployments details" src="https://user-images.githubusercontent.com/26270880/162228089-c19cd3b4-d071-4fd2-afc0-73741c4335a1.png">
<img width="1786" alt="DaemonSets details" src="https://user-images.githubusercontent.com/26270880/162228107-34cb1f71-5a84-47cb-a3eb-fbd228ed5266.png">

**Comment by MichaelKatsoulis** [comment]
@flash1293  Could we arrange a zoom call whenever possible to ask you about best ways to show some metrics in Kibana?
I want to create some nice gauges but to get those numbers, series aggregations are needed  and then mathematical formulas like division. 
<img width="1652" alt="Gauge" src="https://user-images.githubusercontent.com/26270880/163818391-32a0f86e-cf77-4d72-8727-9c3a9d509465.png">

**Comment by jasonrhodes** [comment]
@katefarrar @mlunadia it would be great for us to try to understand what it is about these dashboards that people want/need/use as we try to think through the infrastructure UI.

**Comment by MichaelKatsoulis** [comment]
We had a nice discussion with @flash1293 about ways to create some visualizations and we concluded that some things are not possible yet. But they can be in the near future.
Until then we can use some workarounds when showing informations like `memory reserved`, `memory used`, `cores reserved`, `cores used`, `pods reserved` using the mark-down option.
<img width="257" alt="pods" src="https://user-images.githubusercontent.com/26270880/164415391-aff5411b-e005-4ee0-82b7-ee49738cdea3.png">
<img width="513" alt="memory" src="https://user-images.githubusercontent.com/26270880/164415405-655711db-29d4-42b9-80c8-ad0d59b3273a.png">

Ideally we would like to be able to math calculation with the numbers in each vis to get the percentage.
Also we are waiting for the drill down option to be available in Lens in 8.3 or 8.4 release to better connect the dashboards between each other.

**Comment by mlunadia** [comment]
@jasonrhodes 100% we have plans to tackle this holistically and will for now address any low hanging fruit. We have already started working on establishing a baseline with different discovery activities one of them will be bringing your input in.

**Comment by jasonrhodes** [comment]
@elastic/infra-monitoring-ui I wonder if there are things we can learn from the optimizations in this issue that could be applied to any other querying we are doing for infra UI.

**Comment by miltonhultgren** [comment]
I guess there are two things we can do:
1) From a joint product perspective look at which visualizations we have in the UI today that could be changed to a gauge or single value instead of a trendline. I think today we almost only use trendlines? Changing that could allow us to change to a more performant query while also giving better feedback about the data to the user.
2) Optimize the queries themselves. I'm a bit hesitant about this since it also requires the in-depth domain knowledge about which field means what and which aggregations causes that field to mean something else. What we could do however is try to take stock of the queries we do and how they perform (similar to the SM work we're doing) and then pick the top X and see if we can optimize them or feed them into point 1.

**Comment by jasonrhodes** [comment]
@miltonhultgren thanks! These sound like good ideas to me. I'm wondering if there are specific optimizations made in the work related to this issue (from @MichaelKatsoulis and others) that we could use to inform how we might optimize our own queries, but you're right that there is likely some work we'll need to do to understand whether that kind of overlap exists.

**Comment by ChrsMark** [comment]
Further improvements will take place with the usage of TSDB features. We are currently investigating these at https://github.com/elastic/obs-dc-team/issues/759 and https://github.com/elastic/observability-dev/issues/2194.
