### ISSUE TITLE
Wrong detection of cloud.provider since Beats 8.0 (openstack as huawei)

### ISSUE THREAD

**Issue by kesslerm** [elastic/beats#31022]
User reported:

After deploying elastic agent via fleet (ECE 3.1) on a VM on an internal OpenStack Cloud, all log entries - regardless of being delivered by filebeat or metricbeat - show the field "cloud.provider" = "huawei". The cloud platform is plain OpenStack.

Pre-8.0 versions correctly identified the cloud provider as OpenStack.

The regression may have been introduced by https://github.com/elastic/beats/pull/27607.

**Comment by andrewkroh** [comment]
Discussion and potential PR: https://github.com/elastic/beats/pull/35184#issuecomment-1662731272
