### ISSUE TITLE
Wrong container image reference in metricbeat kubernetes deployment file

### ISSUE THREAD

**Issue by amritpalnagrame** [elastic/beats#31051]
https://github.com/elastic/beats/blob/5b4d983673683c28ff290b1c1021b3c721691630/deploy/kubernetes/metricbeat-kubernetes.yaml#L154

There is no image with tag 7.17.2 but there's 7.17.1 only

**Comment by tetianakravchenko** [comment]
I was able to pull `7.17.2`, also this version is mentioned in full list of docker images: https://www.docker.elastic.co/r/beats/metricbeat
