### ISSUE TITLE
Disable dynamic mapping for stack component modules

### ISSUE THREAD

**Issue by miltonhultgren** [elastic/beats#31066]
Based on https://github.com/elastic/elasticsearch/pull/85447 and https://github.com/elastic/beats/issues/30390, it would be good if we could disable dynamic mapping for the Elasticsearch/Kibana/Beats/Logstash/Enterprise search modules to avoid a field mapping explosion and to align with how internal collection and `xpack.enabled: true` works.

**Comment by miltonhultgren** [comment]
It seems it is not possible to disable dynamic mappings in Metricbeat using the shared Metricbeat index templates.

**Comment by smith** [comment]
Closing this. If it becomes a problem for customers we'll reconsider.
