### ISSUE TITLE
Auditbeat Add Regex to File_Integrity

### ISSUE THREAD

**Issue by dwissm1** [elastic/beats#31060]
Hello,

Is it possible to put wildcards/regex in File Integrity Paths in auditbeat.yml?
I did a lot of digging, and you can exclude files or include files but looking for a wildcard nested dir.

Something on OSX like:
- /Users/*/Library/LaunchAgents

Motivation came from an Elastic Internal Security Briefing at B-Side Lux:
[YOUTUBE Elastic Threat Hunting OSX](https://youtu.be/teq6r7XbBug?t=1702)

I tried a few things:
- /Users/'*'/Library/LaunchAgents
- /Users/('*')/Library/LaunchAgents

Thank you.

**Comment by efd6** [comment]
Currently we do not expand glob syntax when adding paths to the watch list.

This is reasonably straightforward to do [here](https://github.com/elastic/beats/blob/34bdc3d46852532c9348591e0411e5b763b49663/auditbeat/module/file_integrity/config.go#L94-L96), but I am concerned that it makes it easy for users to get themselves into a bad situation performance-wise by starting many independent filesystem watchers; making a config that does `/path/to/bigdir/*/interesting/subdir` can end up creating many if bigdir is very big and would do so without being obvious that it was. (This is unlikely to be the case in the example above where the parent directory is `/Users`, but it could bite elsewhere).

**Comment by dwissm1** [comment]
Understood.  If someone were to do say /Library and do recursive: True would that have the same type of effect?

**Comment by efd6** [comment]
Yes, that's right.
