### ISSUE TITLE
Updating ECS version in Beats

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/beats#31085]
The problem:
During the update to ECS version 8.2.0, I've bumped into the error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "composable template [metricbeat-8.2.0] template after composition is invalid"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "composable template [metricbeat-8.2.0] template after composition is invalid",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "invalid composite mappings for [metricbeat-8.2.0]",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "Limit of total fields [10000] has been exceeded"
      }
    }
  },
  "status": 400
}
```
if counting inner objects, the total number of fields was 10936 (exceeding the limit of `template.settings.index.mapping.total_fields.limit =10000` )

If we keep adding all the new ECS fields for each release to all beats, the template size keeps growing even though a large portion of the fields are not used by some of the Beats. Instead Beats templates should only contain the fields from ECS which are actually used.

This is not a new problem but attempt to update ECS version to 8.2 made it more obvious that we should find some solution here, instead of keep adding new fields.

**Comment by tetianakravchenko** [comment]
@ruflin @ebeahan @elastic/security-external-integrations 
this issue is a follow up of comment https://github.com/elastic/beats/pull/30958#issuecomment-1080592628 for further discussion araout the ecs update topic.

**Comment by ruflin** [comment]
The core problem from my perspective is that we just include all the ECS fields into Beats. Instead as pointed out by @tetianakravchenko we should only contain the fields that are actually used per beat. Including all fields likely started when Beats was still using the majority of the ECS fields but as the number of ECS fields keeps growing, this is not the case yet.

I don't see any benefit of having all the ECS fields in Beats. I think the tricky part is how we find the fields we used. In the packages there is a reference feature for ECS fields, we could do something similar in Beats. 

Going further, I wonder if we even have to keep following each update to the ECS fields. Most of the changes in ECS are addition any not breaking changes. There are times when all of Beats benefits from changes in ECS to existing fields but these could be applied manually.

@andrewkroh @ebeahan Would like to pull you into this conversation. One way to heavily reduce the mapping of ECS is only have a very "core" template that contains the most important fields like `@timestamp` and the rest is dynamic mappings which will map most of the fields correct.

**Comment by ebeahan** [comment]
As mentioned in #30958, this error shouldn't happen using the current version of https://github.com/elastic/ecs/blob/8.2/generated/beats/fields.ecs.yml. While ECS continues adding fields to support more use cases, ECS contains ~1500 total fields with all the nestings and reuses as 8.2. Beats shouldn't be blocked from updating to a new ECS version using the current method.

I agree that the existing method isn't ideal and continues to bloat the Beats field mappings further, but isn't this a problem the Agent/Fleet ecosystem already helps solve? It's unclear what's gained by implementing such changes into Beats.

**Comment by ruflin** [comment]
The issue is partially solve by integrations. But as soon as we have pure input packages, we will face a similar issue. I filed https://github.com/elastic/ecs/issues/1869 to have a more general discussion on this topic. Over the past weeks it bubbled up in multiple places.

**Comment by andrewkroh** [comment]
> if counting inner objects, the total number of fields was 10936 

How many fields were there before updating the ECS fields?
