### ISSUE TITLE
Filebeat not useful on MacOS Sierra - Need Maclogbeat??

### ISSUE THREAD

**Issue by MikePaquette** [elastic/beats#3109]
Need a method to ingest MacOS logs after the logging changes (Unified Logging) in Sierra (MacOS 10.12.1).  

From the [Apple Developer API Reference - Logging ](https://developer.apple.com/reference/os/1891852-logging)
 
"Unified logging is available in iOS 10.0 and later, macOS 10.12 and later, tvOS 10.0 and later, and watchOS 3.0 and later, and supersedes ASL (Apple System Logger) and the Syslog APIs. Historically, log messages were written to specific locations on disk, such as /etc/system.log.  **The unified logging system stores messages in memory and in a data store, rather than writing to text-based log files.**"

Seems that a filebeat based approach will not work, a new beat is required.

**Comment by andrewkroh** [comment]
There are no APIs that I could find for querying logs. Hopefully those will be coming soon.

Here's the WWDC 2016 session [video](https://developer.apple.com/videos/play/wwdc2016/721/) on "Unified Logging and Activity Tracing".

**Comment by tsg** [comment]
This article contains some tools that we might use as an inspiration on how to address this: https://eclecticlight.co/2018/03/19/macos-unified-log-1-why-what-and-how/

**Comment by leeramsay** [comment]
In the latest macOS, which is currently in beta, apple have shipped a logging framework complete with API's for querying logs.

https://developer.apple.com/documentation/logging

Doesn't help for older macOS support, but it's something moving forward at least.

**Comment by opoplawski** [comment]
I don't suppose the source for the "log" utility is available?  Because "log stream" seems to be basically what we want to do.
