### ISSUE TITLE
[Filebeat][Inputs][HTTP JSON] Multi-Step/API Requests

### ISSUE THREAD

**Issue by BenB196** [elastic/beats#31117]
**Describe the enhancement:**

I'd like to request the ability to specify running multiple steps (API calls) in a single HTTP JSON input configuration.

**Describe a specific use case for the enhancement or feature:**

There are some APIs which require you to first authenticate against an `auth` endpoint, to get an API token, to then use to execute an API call. This requires 2 different URLs/APIs to be used in a single input.

### Example Flow

An example of this type of flow.

1. You have a `clientId` and a `secret`, and you make a call like:
```shell
curl -X POST -u "<clientId>:<secret>" my-api.com/auth
```
4. This API returns a JSON value like:
```json
{"accessToken": "<some_access_token>"}
``` 
5. You then use this token in a second request to auth against the actual API:
```shell
curl -X GET -H "Authorization: <accessToken>" my-api.com/realAPI
```
6. You then get the actual data you wanted.
```json
{"APIData": "<api_data>"}
```

Reading through the [docs](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-httpjson.html), this doesn't seem possible currently.

**Comment by cmacknz** [comment]
Some support multi-step or chained httpjson calls was added in https://github.com/elastic/beats/pull/29816. It is tagged for 8.3 but looks like it made the cutoff for the upcoming 8.2 release.

I'm not sure it would support setting the Authorization header as in your example though, it likely needs to be extended further to allow that.

**Comment by efd6** [comment]
I have a work-in-progress that would be able to do this in #31233. If this goes in, it is likely to be in the new V2 input system.

**Comment by ShourieG** [comment]
@jamiehynds @efd6 @andrewkroh will take this as part of 8.5 , the basic foundations of having a separate client per step in httpjson have been laid in 8.4.

**Comment by ShourieG** [comment]
@BenB196 Hey there, are you still looking for this feature to be implemented in httpjson or were you able to solve the issue you were facing ?

**Comment by ShourieG** [comment]
@BenB196 any updates on this ?

**Comment by BenB196** [comment]
Hi @ShourieG I was looking into this, but unless I'm missing something the [chain](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-httpjson.html#chain) configuration options aren't available via the Fleet Integration UI (I'm on Kibana 8.4.2), so I don't think I can actually test this feature in a custom integration setup currently.

**Comment by andrewkroh** [comment]
This is likely fully possible with the new CEL input.

**Comment by ShourieG** [comment]
Closing this issue for the moment, since an alternative solution using CEL is available
