### ISSUE TITLE
Metrics logging should support gauges

### ISSUE THREAD

**Issue by tsg** [elastic/beats#3114]
The metrics logging messages (i.e. the "Non-zero metrics in the last 30s:` messages) are printing deltas since the last interval, and skip the metrics for which the delta is 0. This doesn't play well with gauges type of metrics, and Filebeat has recently got some: `filebeat.harvester.open_files` and `filebeat.harvester.running`.

We need a mechanism where the gauges are printed as an absolute value rather than a delta.

**Comment by ph** [comment]
See also the need for a strconstant type, https://github.com/elastic/beats/pull/6028/files#r160730042
