### ISSUE TITLE
[Heartbeat]-[Feature Request]- LDAP request Support

### ISSUE THREAD

**Issue by mazoutte** [elastic/beats#31155]
**Describe the enhancement:**
LDAP/cLDAP Query Support to validate the health of LDAP Servers, with configurable TCP/UDP port.

**Describe a specific use case for the enhancement or feature:**
This is very similar to what PortQry (from MS) is offering for checking Opened ports for LDAP. 
- Run a LDAP query to validate if there is an answer. You can add maybe a more sophisticated answer to be checked.
- possibility to code a specific LDAP request with credentials - if needed.
- RootDSE is really a must have. It's a standard simple query which calls "RootDSE", that does not need Authentication (default behavior at least on MS AD/ADLDS).
- With this method, it's possible to check on LDAP UDP port as well. (largely used in MS world, and known as PingLDAP - cLDAP compliant - essential during authentication and discovering AD services) 
- Can be extended to LDAPS as well.

**Comment by drewpost** [comment]
Thanks for this suggestion. It's not something that's on our current roadmap as we're focussing on getting our new Synthetics app and real browser agent to 1.0 but I've added it to our backlog and keep track of people requesting it.
