### ISSUE TITLE
azure.signinlogs.properties Can't get text on a START_OBJECT at 1:2686

### ISSUE THREAD

**Issue by mahpatil** [elastic/beats#31207]
Similar to the PR that fixed the azure activity logs issue https://github.com/elastic/beats/pull/31170, we are also seeing issues with the azure sign in logs. 
```
the (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse field [azure.signinlogs.properties.authentication_requirement_policies] of type [keyword] in document with id 'COZZA4ABjACQL03F_CRL'. Preview of field's value: '{detail=Conditional Access, requirement_provider=multiConditionalAccess}'","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:2686"}}, dropping event!
```
For confirmed bugs, please report:
- Version: 8.1
- Steps to Reproduce:

**Comment by toby-sutor** [comment]
This might be a dupe of https://github.com/elastic/beats/pull/31062.

**Comment by mahpatil** [comment]
yes right. i only searched issues and not pull requests so hadn't found this. closing this
