### ISSUE TITLE
Security vulnerabilities golangruntime-1.17.6

### ISSUE THREAD

**Issue by vishrantgupta** [elastic/beats#31232]
Filebeat 8.1.2 continues to have critical vulnerabilities, and it's still using Go version 1.17.6, based on [this comment](https://github.com/elastic/beats/issues/30875#issuecomment-1075150081) it should have been fixed in 8.1.2.

![image](https://user-images.githubusercontent.com/1741243/162511534-2dbef7e0-a7c8-4810-ad23-674eadbbc966.png)

![image](https://user-images.githubusercontent.com/1741243/162511547-0405ff71-43e0-4e52-9d9a-804672fe1cc2.png)

**Comment by cmacknz** [comment]
The 8.1 branch has been updated to build with Go 1.17.8:

https://github.com/elastic/beats/blob/f541d83096e16216ec2567a806be0cf4596a03ff/.go-version#L1

I think it just missed the 8.1.2 release cutoff. There is an 8.1.3 release scheduled for the end of next week that will be built with 1.17.8 to address this. 

I'm going to close this as there is no additional work to do besides waiting for 8.1.3.
