### ISSUE TITLE
Adding Custom log to json converter to filebeat source

### ISSUE THREAD

**Issue by AShabana** [elastic/beats#3126]
Dears , this is not a bug as descriped in the subject 

we simply have plain text CDRs (i.e. access logs ) and need to ship it to aws elastic search as a json format to be  indexed properly at kebana dashboard *and we do not encourage using 3rd party tools for this mediation *

I reviewed the src code ,  I think this could accomplished by editing some where at the harvester  folder ? , your advice is highly appreciated .

**Comment by ruflin** [comment]
To do something like that, log parsing on the beats side would be required which we currently do not plan to add. Here are some additional discussions: https://github.com/elastic/beats/issues/679 If you don't want to add Logstash, you can use ingest pipelines to do this in elasticsearch 5.0 which support grok, user_agent, geoip and more which should be sufficient.

I'm closing this as I think this is already solved by ingest-node. Please feel free to further comment on this issue or reopen if needed.

**Comment by y0299** [comment]
@ruflin i have a question about this, if my log like this `192.168.1.2  "GET /ubuntu.iso HTTP/1.0"`, which have double quotation marks `“”` in the log. if i use  ingest-node grok processor to parse it, there always has error, point out my log format is not a *json*. how can i do this situation?

**Comment by ruflin** [comment]
@y0299 Please use the discuss forum for questions: https://discuss.elastic.co/c/beats/filebeat
