### ISSUE TITLE
beats/filebeat/registrar/migrate.go dealing data.json need tuning by sharememory 

### ISSUE THREAD

**Issue by heming79** [elastic/beats#31271]
**Describe the enhancement:**
My server has more than 20 dockers running Java and has written more than 40 log files
Therefore, filebeat needs to monitor more than 40 log files and run more than 40 threads
Each thread needs to maintain data. json。 New data. JSON, data. JSON may be greater than 30K.
Filebeat will generate 25m / s physical disk IO, as shown in the figure below. It is unacceptable。
![image](https://user-images.githubusercontent.com/14069019/163101319-2820f0e9-f7c8-4dd3-b49c-29cd4aa3803e.png)

strace -p 126891
![image](https://user-images.githubusercontent.com/14069019/163102467-7e0ea09d-947d-414c-b94f-4c5c552c8798.png)

**Describe a specific use case for the enhancement or feature:**
My optimization suggestions:
Multiple threads should maintain this data in shared memory JSON memory. Then the main thread maintains the data JSON file landing. Instead of each thread endlessly operating on this file
My Email:  heming@emar.com

**Comment by cmacknz** [comment]
Would increasing [filebeat.registry.flush](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-general-options.html#_registry_flush) from 0s (immediately write to disk) solve this for you?

We are considering changing the default value to batch disk writes: https://github.com/elastic/beats/issues/30279

**Comment by heming79** [comment]
add this two parameters 
  close_removed: true
  close_inactive: 1h
 filebeat change to this files :   
[root@yz-018182 /]# ll /var/lib/filebeat/registry/filebeat/
total 6648
-rw------- 1 root root   54495 Apr 14 11:07 352664.json
-rw------- 1 root root      47 Apr 14 11:07 active.dat
-rw------- 1 root root 6735078 Apr 14 17:51 log.json
-rw------- 1 root root      16 Apr 13 17:32 meta.json

now disk IO is OK

**Comment by cmacknz** [comment]
Thanks, I'll close this as resolved then. We are thinking about how to use less IO by default.
