### ISSUE TITLE
[Heartbeat] Adjust ARM Seccomp profile

### ISSUE THREAD

**Issue by emilioalvap** [elastic/beats#31285]
**Describe the enhancement:**

[Actual seccomp profile](https://github.com/elastic/beats/blob/5478d735e6cc4b0c1c517ec9df7c769dce5a3033/heartbeat/security/security.go#L242) for ARM architectures in Heartbeat is too open. Since there is no deny-by-default profile provided by `libbeat`, we need to record a complete list of systemcalls, match it to [ARMs supported list](https://github.com/elastic/go-seccomp-bpf/blob/01b0ad6a76ec4b2becfbd71b61b99b8736156616/arch/zsyscalls.go) and override the default profile with the new configuration as a deny-by-default profile.

**Comment by andrewvc** [comment]
Post-FF tested on a graviton instance
