### ISSUE TITLE
Add support to AWS AutoScalingGroup metrics

### ISSUE THREAD

**Issue by nithril** [elastic/beats#31303]
Hello,

Is it possible to add the support of the AWS ASG metrics to the AWS metricbeat module?

Thank you

**Comment by kaiyan-sheng** [comment]
cc @ravikesarwani

**Comment by ravikesarwani** [comment]
Are you thinking about utilizing [Elastic Agent & Fleet](https://www.elastic.co/guide/en/fleet/current/index.html) in the near future? Any enhancements like this would be more focused towards Elastic Agent & integrations (than metricbeat).

**Comment by nithril** [comment]
:+1: still relevant on our side

**Comment by nithril** [comment]
>Are you thinking about utilizing [Elastic Agent & Fleet](https://www.elastic.co/guide/en/fleet/current/index.html) in the near future? Any enhancements like this would be more focused towards Elastic Agent & integrations (than metricbeat).

@ravikesarwani we did actually, AFAIK, Elastic Agent is simply a wrapper around the beats
