### ISSUE TITLE
UDP Panic Error [CEF Input Plugin] [bug]

### ISSUE THREAD

**Issue by Kamui26** [elastic/beats#31340]
Hello! 
I am using CEF plugin for receiving logs in CEF format, everything worked OK, but after 1 hour after i am opening UDP port, module is crashing and UDP port for log receiving closes.

filebeat logs:

`2022-04-19T09:12:40.138+0600    ERROR   [UDP]   logp/logger.go:218      Panic handling datagram. Recovering, but please report this.{panic 25 0  runtime error: slice bounds out of range [:-67]} {stack 15 0 github.com/elastic/beats/v7/libbeat/logp.(*Logger).Recover
        /go/src/github.com/elastic/beats/libbeat/logp/logger.go:218
runtime.gopanic
        /usr/local/go/src/runtime/panic.go:1038
runtime.goPanicSliceAlen
        /usr/local/go/src/runtime/panic.go:100
github.com/elastic/beats/v7/x-pack/filebeat/processors/decode_cef/cef.replaceEscapes
        /go/src/github.com/elastic/beats/x-pack/filebeat/processors/decode_cef/cef/cef.go:173
github.com/elastic/beats/v7/x-pack/filebeat/processors/decode_cef/cef.(*Event).unpack
        cef.rl:76
github.com/elastic/beats/v7/x-pack/filebeat/processors/decode_cef/cef.(*Event).Unpack
        /go/src/github.com/elastic/beats/x-pack/filebeat/processors/decode_cef/cef/cef.go:125
github.com/elastic/beats/v7/x-pack/filebeat/processors/decode_cef.(*processor).Run
        /go/src/github.com/elastic/beats/x-pack/filebeat/processors/decode_cef/decode_cef.go:89
github.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Run
        /go/src/github.com/elastic/beats/libbeat/publisher/processing/processors.go:121
github.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Run
        /go/src/github.com/elastic/beats/libbeat/publisher/processing/processors.go:121
github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).publish
        /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/client.go:101
github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).Publish
        /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/client.go:80
github.com/elastic/beats/v7/filebeat/beater.(*countingClient).Publish
        /go/src/github.com/elastic/beats/filebeat/beater/channels.go:136
github.com/elastic/beats/v7/filebeat/channel.(*outlet).OnEvent
        /go/src/github.com/elastic/beats/filebeat/channel/outlet.go:58
github.com/elastic/beats/v7/filebeat/harvester.(*Forwarder).Send
        /go/src/github.com/elastic/beats/filebeat/harvester/forwarder.go:50
github.com/elastic/beats/v7/filebeat/input/syslog.GetCbByConfig.func3
        /go/src/github.com/elastic/beats/filebeat/input/syslog/input.go:202
github.com/elastic/beats/v7/filebeat/inputsource/common/dgram.DatagramReaderFactory.func1.1
        /go/src/github.com/elastic/beats/filebeat/inputsource/common/dgram/handler.go:88
github.com/elastic/beats/v7/filebeat/inputsource/common/dgram.(*Listener).connectAndRun
        /go/src/github.com/elastic/beats/filebeat/inputsource/common/dgram/server.go:122
github.com/elastic/beats/v7/filebeat/inputsource/common/dgram.(*Listener).Start.func1
        /go/src/github.com/elastic/beats/filebeat/inputsource/common/dgram/server.go:112
github.com/elastic/go-concert/unison.(*TaskGroup).Go.func1
        /go/pkg/mod/github.com/elastic/go-concert@v0.2.0/unison/taskgroup.go:163 <nil>}
`

```
module config:
- module: cef
  log:
    enabled: true
    var:
      syslog_host: 0.0.0.0
      syslog_port: 9543
      tags: ["dlp-logs"]
```

i am using filebeat version 7.16.3 on RHEL8.5 Oopta

sorry for my bad english

**Comment by Kamui26** [comment]
pinging @andrewkroh

**Comment by Kamui26** [comment]
Help me :(

**Comment by andrewkroh** [comment]
Please upgrade to the latest 7.17 release and retest. It might be caused by https://github.com/elastic/beats/pull/30038.
