### ISSUE TITLE
Reduce the number of build platform in mage/platforms.go

### ISSUE THREAD

**Issue by ph** [elastic/beats#31351]
In the [mage/platforms.go](https://github.com/elastic/beats/blob/main/dev-tools/mage/platforms.go#L29-L71) There is a really large list of build platform, this was generated using the `go tool dist list -json`. This list is in fact all the supported platforms of the go compiler. 

This list contains platforms that aren't officially supported in [our matrix](https://www.elastic.co/support/matrix) and cause [unnecessary work and confusion regarding our golang-crossbuild images](https://github.com/elastic/golang-crossbuild/issues/173).

I suggest we reduce the number of items in this list to the officially supported platform.

**Comment by kuisathaverat** [comment]
see also https://github.com/elastic/beats/blob/35d0fc8933afa82619a2c16324b36e7e68b63539/dev-tools/mage/crossbuild.go#L258-L298
