### ISSUE TITLE
[Heartbeat] change throttling format for browser monitors 

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/beats#31362]
**Describe the enhancement:** 

+ As per our last team discussion and decision around the `monitor` DSL changes that will be required for uploading/pushing monitors to the Monitor management UI https://github.com/elastic/synthetics/issues/451#issuecomment-1069305122 , we are changing the structure of `throttling` flags to be JSON object instead of string format `<5d/3u/20l>`. 
```js
  throttling: {
    download: 5,
    upload: 3,
    latency: 20,
  },
```
+ The configured throttling settings will be applied to Chrome CDP session settings when running synthetics tests. 

+ Synthetics flag changes are done as part of this PR - https://github.com/elastic/synthetics/pull/493

**Comment by shahzad31** [comment]
POST FF Testing 

Can see throttling in desired format

`--throttling {\"download\":5,\"latency\":20,\"upload\":3}
`
`{"log.level":"info","@timestamp":"2022-06-07T19:54:03.666Z","log.origin":{"file.name":"synthexec/synthexec.go","file.line":153},"message":"Running command: /tmp/elastic-synthetics-unzip-4286063442/node_modules/.bin/elastic-synthetics /tmp/elastic-synthetics-unzip-4286063442/node_modules/.bin/elastic-synthetics /tmp/elastic-synthetics-unzip-4286063442 --playwright-options {\"deviceScaleFactor\":2,\"hasTouch\":true,\"headless\":true,\"isMobile\":true,\"userAgent\":\"Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1\",\"viewport\":{\"height\":667,\"width\":375}} --screenshots on --throttling {\"download\":5,\"latency\":20,\"upload\":3} --rich-events --match check-if-input-placeholder-is-correct --params \"{1 hidden params}\" in directory: '/tmp/elastic-synthetics-unzip-4286063442'","service.name":"heartbeat","ecs.version":"1.6.0"}
`
