### ISSUE TITLE
decode_xml and decode_xml_wineventlog fail on UTF-16 charsets

### ISSUE THREAD

**Issue by jvalente-salemstate** [elastic/beats#31395]
I'm trying to parse a field that contains XML and it logs the following error:

`failed in decode_xml on the "winlog.event_data.param2" field: error decoding XML field: xml: encoding "utf-16" declared but Decoder.CharsetReader is nil`

The field itself is formatted as such:
```
<?xml version="1.0" encoding="utf-16"?>
<AuditBase xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="FreshCredentialAudit">
  snip
  </ContextComponents>
</AuditBase>
```

This was reported, but closed due to no responses, in February here: https://discuss.elastic.co/t/decode-xml-fails-on-utf-16-formatted-input/295996

When on logstash, the filter worked fine, but since moving to elastic agent (until 8.2 when Logstash output may be available) this means most of the data in ADFS authentication logs, for example, isn't available as the user, IP, user agent, and other relevant info is all in the XML.

**Comment by andrewkroh** [comment]
How is this XML being read? I assume that despite the XML header saying the encoding is utf-16, that data is already UTF-8 as a result of whatever read the data.

I'm curious if you strip away the encoding specification in the header if it works? Like if you add a processor before the decode_xml.

```
- script:
    lang: javascript
    source: |
      var regex = /(<\?.*)(\s+encoding="UTF-16")(\?>)/gm;
      function process(evt) {
        var msg = evt.Get('message');
        msg = msg.replace(regex, '$1$3');
        evt.Put('message', msg);
      }
- decode_xml:
    field: message
```

**Comment by jvalente-salemstate** [comment]
> How is this XML being read? I assume that despite the XML header saying the encoding is utf-16, that data is already UTF-8 as a result of whatever read the data.
> 
> I'm curious if you strip away the encoding specification in the header if it works? Like if you add a processor before the decode_xml.
> 
> ```
> - script:
>     lang: javascript
>     source: |
>       var regex = /(<\?.*)(\s+encoding="UTF-16")(\?>)/gm;
>       function process(evt) {
>         var msg = evt.Get('message');
>         msg = msg.replace(regex, '$1$3');
>         evt.Put('message', msg);
>       }
> - decode_xml:
>     field: message
> ```

Thanks.  This works (just changed the UTF-16 to utf-16). I had tried to look up which processor could do this but didn't consider doing it with Javascript. The actual data within the field shouldn't "need" to be read as UTF-16 (usernames, passwords, and user agents)  so this workaround is seems to get the job done.

**Comment by jvalente-salemstate** [comment]
> So the data is being read by Winlogbeat?

The data is being read by FIlebeat as it seems that (rather than Winlogbeat) is what Elastic Agent uses to read the Security Channel (via the System Integration) on Windows, as well as the "Custom Windows Event Logs" integration.  

However, since it seem the code for the processor is the same between different beats, I'd guess this would also occur for users doing the same on Winlogbeat.  When these hosts were using Winlogbeat and forwarding to logstash, I did not encounter the issue as the filter-plugin (both 7.x and 8.x) worked.

**Comment by efd6** [comment]
If we can guarantee that the encoding declarations in the proc inst are lying when they say anything other than UTF-8, we can silence this by adding a `CharsetReader` to the underlying xml decoder that returns the input `io.Reader` unaltered independent of the encoding. This would require that we ensure that we never hand anything other than UTF-8 to the decoder.
```diff
diff --git a/libbeat/common/encoding/xml/decode.go b/libbeat/common/encoding/xml/decode.go
index 8fcc790ca5..11be0d22f3 100644
--- a/libbeat/common/encoding/xml/decode.go
+++ b/libbeat/common/encoding/xml/decode.go
@@ -33,7 +33,10 @@ type Decoder struct {
 
 // NewDecoder returns a new decoder that reads from r.
 func NewDecoder(r io.Reader) *Decoder {
-       return &Decoder{xmlDec: xml.NewDecoder(r)}
+       dec := xml.NewDecoder(r)
+       // Assume all text has already been converted to UTF-8, so ignore encoding declarations.
+       dec.CharsetReader = func(_ string, input io.Reader) (io.Reader, error) { return input, nil }
+       return &Decoder{xmlDec: dec}
 }
 
 // PrependHyphenToAttr causes the Decoder to prepend a hyphen ('-') to to all
```

This has a risk that real non-UTF-8 text may be handed in, but this will already fail when it attempts to decode the xml, just now with a different error.

**Comment by andrewkroh** [comment]
@efd6 That is also the fix I was thinking of.

**Comment by jvalente-salemstate** [comment]
@efd6 In all my tests, it seems that yes it's UTF-8. When using the processor suggested by @andrewkroh even with emojis and non-english (e.g. simplified Chinese, Ethiopic) everything parses correctly.  It may be specific to how ADFS is handling credentials, but at least here I don't think it _needs_ UTF-16 or can be coerced into input that'd be such. 

I'm not certain why MS specifies it as utf-16, but in the case of AD FS logging, it does not look like it matters.
