### ISSUE TITLE
Packetbeat-Cassandra.json has colons in the visualization names

### ISSUE THREAD

**Issue by LeeDr** [elastic/beats#3140]
`beats-dashboards-5.1.1/packetbeat/dashboard/Packetbeat-Cassandra.json` has colons in the visualization names

- Version: 5.1.1 build candidate from 2016-12-06
- Operating System: Ubuntu 32-bit
- Steps to Reproduce: 
1. ./import_dashboards -user $ELASTICUSER -pass $ELASTICPWD -url http://${BASEURL}/downloads/beats/beats-dashboards/beats-dashboards-5.1.1.zip

End of Output:
```
Import search  /tmp/tmp885745225/beats-dashboards-5.1.1/packetbeat/search/Thrift-transactions.json
Import vizualization  /tmp/tmp885745225/beats-dashboards-5.1.1/packetbeat/visualization/Top-Thrift-RPC-calls-with-errors.json
Import search  /tmp/tmp885745225/beats-dashboards-5.1.1/packetbeat/search/Thrift-errors.json
fail to import dashboards: fail to load directory /tmp/tmp885745225/beats-dashboards-5.1.1/packetbeat/dashboard: error loading /tmp/tmp885745225/beats-dashboards-5.1.1/packetbeat/dashboard/Packetbeat-Cassandra.json: fail to read /tmp/tmp885745225/beats-dashboards-5.1.1/packetbeat/visualization/Cassandra:-ResponseKeyspace.json. Error: open /tmp/tmp885745225/beats-dashboards-5.1.1/packetbeat/visualization/Cassandra:-ResponseKeyspace.json: no such file or directory
```

**Comment by ruflin** [comment]
@LeeDr Thanks for reporting. A fix is provided here: https://github.com/elastic/beats/pull/3146 It seems we forgotten to correct the links in the Cassandra dashboards when the visualisations were renamed in https://github.com/elastic/beats/pull/2946 :-(
