### ISSUE TITLE
[Heartbeat] Executing Synthetics zipped monitors from suites/push command

### ISSUE THREAD

**Issue by lucasfcosta** [elastic/beats#31408]
# Summary & ACs

Heartbeat should be able to execute synthetics' zipped monitors (which are also base64 encoded) created using the push command described in https://github.com/elastic/synthetics/issues/470.

Once these monitors run, Heartbeat should be able to push results to Kibana.

> ⚠️ Just as it happens now, it should be possible to report the exact step at which a monitor failed so that Kibana can display its full code.

**Comment by vigneshshanmugam** [comment]
Its a duplicate - https://github.com/elastic/beats/issues/31363
