### ISSUE TITLE
package: rename docker tar.gz packages to docker-image-linux-<arch>.tar.gz

### ISSUE THREAD

**Issue by v1v** [elastic/beats#31457]
**Describe the enhancement:**

Rename docker tar.gz packages to `docker-image-linux-<arch>.tar.gz`

**Describe a specific use case for the enhancement or feature:**

The Unified Release process, aka the one in charge to generate the distributable, uses the format `docker-image-linux-<arch>.tar.gz`. Though, it exports those docker images in a different manner instead using those `tar.gz` directly, but since the Daily Releasable Artifacts is in place, then it's up to the Beats build system to support it.

Therefore, the artifacts need to be renamed to be name complacence with the unified release process. https://github.com/elastic/beats/blob/87949288faf8450b35a12ae946050444d4272c18/.ci/scripts/prepare-release-manager.sh#L22-L38 is the script in charge to do so

The APM Server also requires to rename them as per https://github.com/elastic/apm-server/blob/a3e8d075b29e723c0451e2e09be7ecc08b645a58/.ci/scripts/prepare-release-manager.sh#L21-L32

By changing the package to support the new names then the APM Server can benefit from

## Proposal:

https://github.com/elastic/beats/pull/30895

## Questions

- Are those docker.tar.gz files used somewhere else?
- @elastic/observablt-robots , what are your thoughts?

## Stakeholders

@mgreau 
@cmacknz 
@jlind23 
@axw

**Comment by cachedout** [comment]
> https://github.com/orgs/elastic/teams/observablt-robots , what are your thoughts?

No objections here, if this is what DRA requires.
