### ISSUE TITLE
Metricbeat Elasticsearch module reports version information incorrectly

### ISSUE THREAD

**Issue by miltonhultgren** [elastic/beats#31481]
In the Internal Collection documents, the version of the Elasticsearch cluster* is listed under `_source.version`.
In the Metricbeat documents, the version field is found under `_source.elasticsearch.version` but the value that is populated there is incorrect.

It seems the value is the version of the cluster state which is derived from a monotonic clock value (such as `102`). In the Internal Collection document, this value is found under `_source.cluster_state.version`.

Similarly `elasticsearch.cluster.stats.state.version` is not being populated at all.

\* How this version is defined I don't know, does it take into account rolling upgrades?

<details>
  <summary>Internal collection document</summary>
  
{
  "cluster_uuid": "B68oreuTQrOudr1JTImCcg",
  "timestamp": "2022-05-02T08:20:00.179Z",
  "interval_ms": 10000,
  "type": "cluster_stats",
  "source_node": {
    "uuid": "mngkehMPQK-XFEVDuJRrPw",
    "host": "127.0.0.1",
    "transport_address": "127.0.0.1:9300",
    "ip": "127.0.0.1",
    "name": "Miltons-MBP.lan",
    "timestamp": "2022-05-02T08:20:00.151Z"
  },
  "cluster_name": "elasticsearch",
  "version": "8.3.0",
  "license": {
    "status": "active",
    "uid": "1925a9fe-570b-4cd9-9b26-d0a4653c2079",
    "type": "trial",
    "issue_date": "2022-05-02T08:15:29.142Z",
    "issue_date_in_millis": 1651479329142,
    "expiry_date": "2022-06-01T08:15:29.142Z",
    "expiry_date_in_millis": 1654071329142,
    "max_nodes": 1000,
    "max_resource_units": null,
    "issued_to": "elasticsearch",
    "issuer": "elasticsearch",
    "start_date_in_millis": -1,
    "cluster_needs_tls": true
  },
  "cluster_stats": {
    "cluster_uuid": "B68oreuTQrOudr1JTImCcg",
    "timestamp": 1651479600161,
    "status": "green",
    "indices": {
      "count": 12,
      "shards": {
        "total": 12,
        "primaries": 12,
        "replication": 0,
        "index": {
          "shards": {
            "min": 1,
            "max": 1,
            "avg": 1
          },
          "primaries": {
            "min": 1,
            "max": 1,
            "avg": 1
          },
          "replication": {
            "min": 0,
            "max": 0,
            "avg": 0
          }
        }
      },
      "docs": {
        "count": 418,
        "deleted": 491
      },
      "store": {
        "size_in_bytes": 7349872,
        "total_data_set_size_in_bytes": 7349872,
        "reserved_in_bytes": 0
      },
      "fielddata": {
        "memory_size_in_bytes": 0,
        "evictions": 0
      },
      "query_cache": {
        "memory_size_in_bytes": 0,
        "total_count": 0,
        "hit_count": 0,
        "miss_count": 0,
        "cache_size": 0,
        "cache_count": 0,
        "evictions": 0
      },
      "completion": {
        "size_in_bytes": 0
      },
      "segments": {
        "count": 39,
        "memory_in_bytes": 0,
        "terms_memory_in_bytes": 0,
        "stored_fields_memory_in_bytes": 0,
        "term_vectors_memory_in_bytes": 0,
        "norms_memory_in_bytes": 0,
        "points_memory_in_bytes": 0,
        "doc_values_memory_in_bytes": 0,
        "index_writer_memory_in_bytes": 281496,
        "version_map_memory_in_bytes": 0,
        "fixed_bit_set_memory_in_bytes": 1448,
        "max_unsafe_auto_id_timestamp": -1,
        "file_sizes": {}
      },
      "mappings": {
        "field_types": [
          {
            "name": "boolean",
            "count": 7,
            "index_count": 3,
            "script_count": 0
          },
          {
            "name": "constant_keyword",
            "count": 3,
            "index_count": 1,
            "script_count": 0
          },
          {
            "name": "date",
            "count": 20,
            "index_count": 5,
            "script_count": 0
          },
          {
            "name": "float",
            "count": 12,
            "index_count": 2,
            "script_count": 0
          },
          {
            "name": "half_float",
            "count": 8,
            "index_count": 2,
            "script_count": 0
          },
          {
            "name": "integer",
            "count": 22,
            "index_count": 1,
            "script_count": 0
          },
          {
            "name": "ip",
            "count": 1,
            "index_count": 1,
            "script_count": 0
          },
          {
            "name": "keyword",
            "count": 133,
            "index_count": 5,
            "script_count": 0
          },
          {
            "name": "long",
            "count": 219,
            "index_count": 4,
            "script_count": 0
          },
          {
            "name": "nested",
            "count": 4,
            "index_count": 2,
            "script_count": 0
          },
          {
            "name": "object",
            "count": 147,
            "index_count": 5,
            "script_count": 0
          },
          {
            "name": "text",
            "count": 11,
            "index_count": 4,
            "script_count": 0
          },
          {
            "name": "version",
            "count": 1,
            "index_count": 1,
            "script_count": 0
          }
        ],
        "runtime_field_types": []
      },
      "analysis": {
        "char_filter_types": [],
        "tokenizer_types": [],
        "filter_types": [],
        "analyzer_types": [],
        "built_in_char_filters": [],
        "built_in_tokenizers": [],
        "built_in_filters": [],
        "built_in_analyzers": []
      },
      "versions": [
        {
          "version": "8.3.0",
          "index_count": 12,
          "primary_shard_count": 12,
          "total_primary_bytes": 7349872
        }
      ]
    },
    "nodes": {
      "count": {
        "total": 1,
        "coordinating_only": 0,
        "data": 1,
        "data_cold": 1,
        "data_content": 1,
        "data_frozen": 1,
        "data_hot": 1,
        "data_warm": 1,
        "ingest": 1,
        "master": 1,
        "ml": 1,
        "remote_cluster_client": 1,
        "transform": 1,
        "voting_only": 0
      },
      "versions": [
        "8.3.0"
      ],
      "os": {
        "available_processors": 16,
        "allocated_processors": 16,
        "names": [
          {
            "name": "Mac OS X",
            "count": 1
          }
        ],
        "pretty_names": [
          {
            "pretty_name": "Mac OS X",
            "count": 1
          }
        ],
        "architectures": [
          {
            "arch": "x86_64",
            "count": 1
          }
        ],
        "mem": {
          "total_in_bytes": 68719476736,
          "adjusted_total_in_bytes": 68719476736,
          "free_in_bytes": 43108745216,
          "used_in_bytes": 25610731520,
          "free_percent": 63,
          "used_percent": 37
        }
      },
      "process": {
        "cpu": {
          "percent": 1
        },
        "open_file_descriptors": {
          "min": 556,
          "max": 556,
          "avg": 556
        }
      },
      "jvm": {
        "max_uptime_in_millis": 289934,
        "versions": [
          {
            "version": "18",
            "vm_name": "OpenJDK 64-Bit Server VM",
            "vm_version": "18+36",
            "vm_vendor": "Eclipse Adoptium",
            "bundled_jdk": true,
            "using_bundled_jdk": true,
            "count": 1
          }
        ],
        "mem": {
          "heap_used_in_bytes": 970352128,
          "heap_max_in_bytes": 1610612736
        },
        "threads": 165
      },
      "fs": {
        "total_in_bytes": 1000240963584,
        "free_in_bytes": 878370766848,
        "available_in_bytes": 878370766848
      },
      "plugins": [],
      "network_types": {
        "transport_types": {
          "security4": 1
        },
        "http_types": {
          "security4": 1
        }
      },
      "discovery_types": {
        "multi-node": 1
      },
      "packaging_types": [
        {
          "flavor": "default",
          "type": "tar",
          "count": 1
        }
      ],
      "ingest": {
        "number_of_pipelines": 1,
        "processor_stats": {
          "remove": {
            "count": 0,
            "failed": 0,
            "current": 0,
            "time_in_millis": 0
          },
          "script": {
            "count": 0,
            "failed": 0,
            "current": 0,
            "time_in_millis": 0
          },
          "set": {
            "count": 0,
            "failed": 0,
            "current": 0,
            "time_in_millis": 0
          },
          "set_security_user": {
            "count": 0,
            "failed": 0,
            "current": 0,
            "time_in_millis": 0
          }
        }
      },
      "indexing_pressure": {
        "memory": {
          "current": {
            "combined_coordinating_and_primary_in_bytes": 0,
            "coordinating_in_bytes": 0,
            "primary_in_bytes": 0,
            "replica_in_bytes": 0,
            "all_in_bytes": 0
          },
          "total": {
            "combined_coordinating_and_primary_in_bytes": 0,
            "coordinating_in_bytes": 0,
            "primary_in_bytes": 0,
            "replica_in_bytes": 0,
            "all_in_bytes": 0,
            "coordinating_rejections": 0,
            "primary_rejections": 0,
            "replica_rejections": 0
          },
          "limit_in_bytes": 0
        }
      }
    }
  },
  "cluster_state": {
    "nodes_hash": -660186877,
    "status": "green",
    "cluster_uuid": "B68oreuTQrOudr1JTImCcg",
    "version": 104,
    "state_uuid": "N_oTbgPjQwWDmmic9rBLHQ",
    "master_node": "mngkehMPQK-XFEVDuJRrPw",
    "nodes": {
      "mngkehMPQK-XFEVDuJRrPw": {
        "name": "Miltons-MBP.lan",
        "ephemeral_id": "oE80gm9bTP-xzlGBZmhcsw",
        "transport_address": "127.0.0.1:9300",
        "attributes": {
          "ml.max_jvm_size": "1610612736",
          "xpack.installed": "true",
          "ml.machine_memory": "68719476736"
        },
        "roles": [
          "data",
          "data_cold",
          "data_content",
          "data_frozen",
          "data_hot",
          "data_warm",
          "ingest",
          "master",
          "ml",
          "remote_cluster_client",
          "transform"
        ]
      }
    }
  },
  "stack_stats": {
    "apm": {
      "found": false
    },
    "xpack": {
      "aggregate_metric": {
        "available": true,
        "enabled": true
      },
      "analytics": {
        "available": true,
        "enabled": true,
        "stats": {
          "boxplot_usage": 0,
          "cumulative_cardinality_usage": 0,
          "string_stats_usage": 3,
          "top_metrics_usage": 0,
          "t_test_usage": 0,
          "moving_percentiles_usage": 0,
          "normalize_usage": 0,
          "rate_usage": 0,
          "multi_terms_usage": 0
        }
      },
      "ccr": {
        "available": true,
        "enabled": true,
        "follower_indices_count": 0,
        "auto_follow_patterns_count": 0
      },
      "data_streams": {
        "available": true,
        "enabled": true,
        "data_streams": 2,
        "indices_count": 2
      },
      "data_tiers": {
        "available": true,
        "enabled": true,
        "data_warm": {
          "node_count": 1,
          "index_count": 0,
          "total_shard_count": 0,
          "primary_shard_count": 0,
          "doc_count": 0,
          "total_size_bytes": 0,
          "primary_size_bytes": 0,
          "primary_shard_size_avg_bytes": 0,
          "primary_shard_size_median_bytes": 0,
          "primary_shard_size_mad_bytes": 0
        },
        "data_frozen": {
          "node_count": 1,
          "index_count": 0,
          "total_shard_count": 0,
          "primary_shard_count": 0,
          "doc_count": 0,
          "total_size_bytes": 0,
          "primary_size_bytes": 0,
          "primary_shard_size_avg_bytes": 0,
          "primary_shard_size_median_bytes": 0,
          "primary_shard_size_mad_bytes": 0
        },
        "data_cold": {
          "node_count": 1,
          "index_count": 0,
          "total_shard_count": 0,
          "primary_shard_count": 0,
          "doc_count": 0,
          "total_size_bytes": 0,
          "primary_size_bytes": 0,
          "primary_shard_size_avg_bytes": 0,
          "primary_shard_size_median_bytes": 0,
          "primary_shard_size_mad_bytes": 0
        },
        "data_content": {
          "node_count": 1,
          "index_count": 10,
          "total_shard_count": 10,
          "primary_shard_count": 10,
          "doc_count": 406,
          "total_size_bytes": 7291956,
          "primary_size_bytes": 7291956,
          "primary_shard_size_avg_bytes": 729195,
          "primary_shard_size_median_bytes": 41333,
          "primary_shard_size_mad_bytes": 41108
        },
        "data_hot": {
          "node_count": 1,
          "index_count": 2,
          "total_shard_count": 2,
          "primary_shard_count": 2,
          "doc_count": 12,
          "total_size_bytes": 57916,
          "primary_size_bytes": 57916,
          "primary_shard_size_avg_bytes": 28958,
          "primary_shard_size_median_bytes": 28958,
          "primary_shard_size_mad_bytes": 8320
        }
      },
      "eql": {
        "available": true,
        "enabled": true,
        "features": {
          "joins": {
            "join_queries_three": 0,
            "join_queries_two": 0,
            "join_until": 0,
            "join_queries_five_or_more": 0,
            "join_queries_four": 0
          },
          "sequence": 0,
          "keys": {
            "join_keys_two": 0,
            "join_keys_one": 0,
            "join_keys_three": 0,
            "join_keys_five_or_more": 0,
            "join_keys_four": 0
          },
          "join": 0,
          "sequences": {
            "sequence_queries_three": 0,
            "sequence_queries_four": 0,
            "sequence_queries_two": 0,
            "sequence_until": 0,
            "sequence_maxspan": 0,
            "sequence_queries_five_or_more": 0
          },
          "event": 0,
          "pipes": {
            "pipe_tail": 0,
            "pipe_head": 0
          }
        },
        "queries": {
          "all": {
            "total": 0,
            "failed": 0
          },
          "_all": {
            "total": 0,
            "failed": 0
          }
        }
      },
      "frozen_indices": {
        "available": true,
        "enabled": true,
        "indices_count": 0
      },
      "graph": {
        "available": true,
        "enabled": true
      },
      "ilm": {
        "policy_count": 19,
        "policy_stats": [
          {
            "phases": {
              "warm": {
                "min_age": 172800000,
                "actions": [
                  "shrink",
                  "forcemerge",
                  "migrate"
                ],
                "configurations": {
                  "forcemerge": {
                    "max_num_segments": 1
                  },
                  "shrink": {
                    "number_of_shards": 1
                  }
                }
              },
              "cold": {
                "min_age": 2592000000,
                "actions": [
                  "migrate"
                ],
                "configurations": {}
              },
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "30d",
                    "max_age_millis": 2592000000,
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              },
              "delete": {
                "min_age": 7776000000,
                "actions": [
                  "delete",
                  "migrate"
                ],
                "configurations": {}
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "30d",
                    "max_age_millis": 2592000000,
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              },
              "delete": {
                "min_age": 7776000000,
                "actions": [
                  "delete",
                  "migrate"
                ],
                "configurations": {}
              }
            },
            "indices_managed": 1
          },
          {
            "phases": {
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "3d",
                    "max_age_millis": 259200000,
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              },
              "delete": {
                "min_age": 345600000,
                "actions": [
                  "delete",
                  "migrate"
                ],
                "configurations": {}
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "warm": {
                "min_age": 172800000,
                "actions": [
                  "shrink",
                  "forcemerge",
                  "migrate"
                ],
                "configurations": {
                  "forcemerge": {
                    "max_num_segments": 1
                  },
                  "shrink": {
                    "number_of_shards": 1
                  }
                }
              },
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "30d",
                    "max_age_millis": 2592000000,
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              },
              "delete": {
                "min_age": 2592000000,
                "actions": [
                  "delete",
                  "migrate"
                ],
                "configurations": {}
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "30d",
                    "max_age_millis": 2592000000,
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "1d",
                    "max_age_millis": 86400000,
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              },
              "delete": {
                "min_age": 86400000,
                "actions": [
                  "delete",
                  "migrate"
                ],
                "configurations": {}
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "30d",
                    "max_age_millis": 2592000000,
                    "max_size": "50gb",
                    "max_size_bytes": 53687091200
                  }
                }
              },
              "delete": {
                "min_age": 7776000000,
                "actions": [
                  "delete",
                  "migrate"
                ],
                "configurations": {}
              }
            },
            "indices_managed": 1
          },
          {
            "phases": {
              "hot": {
                "min_age": 0,
                "actions": [
                  "migrate"
                ],
                "configurations": {}
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "30d",
                    "max_age_millis": 2592000000,
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "warm": {
                "min_age": 0,
                "actions": [
                  "forcemerge",
                  "migrate"
                ],
                "configurations": {
                  "forcemerge": {
                    "max_num_segments": 1
                  }
                }
              },
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "3d",
                    "max_age_millis": 259200000,
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              },
              "delete": {
                "min_age": 259200000,
                "actions": [
                  "delete",
                  "migrate"
                ],
                "configurations": {}
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "30d",
                    "max_age_millis": 2592000000,
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              },
              "delete": {
                "min_age": 7776000000,
                "actions": [
                  "delete",
                  "migrate"
                ],
                "configurations": {}
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "30d",
                    "max_age_millis": 2592000000,
                    "max_size": "300gb",
                    "max_size_bytes": 322122547200
                  }
                }
              },
              "delete": {
                "min_age": 7776000000,
                "actions": [
                  "delete",
                  "migrate"
                ],
                "configurations": {}
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "warm": {
                "min_age": 172800000,
                "actions": [
                  "shrink",
                  "forcemerge",
                  "migrate"
                ],
                "configurations": {
                  "forcemerge": {
                    "max_num_segments": 1
                  },
                  "shrink": {
                    "number_of_shards": 1
                  }
                }
              },
              "cold": {
                "min_age": 2592000000,
                "actions": [
                  "migrate"
                ],
                "configurations": {}
              },
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "30d",
                    "max_age_millis": 2592000000,
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              },
              "delete": {
                "min_age": 31536000000,
                "actions": [
                  "delete",
                  "migrate"
                ],
                "configurations": {}
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "warm": {
                "min_age": 172800000,
                "actions": [
                  "shrink",
                  "forcemerge",
                  "migrate"
                ],
                "configurations": {
                  "forcemerge": {
                    "max_num_segments": 1
                  },
                  "shrink": {
                    "number_of_shards": 1
                  }
                }
              },
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "7d",
                    "max_age_millis": 604800000,
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              },
              "delete": {
                "min_age": 604800000,
                "actions": [
                  "delete",
                  "migrate"
                ],
                "configurations": {}
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "30d",
                    "max_age_millis": 2592000000,
                    "max_primary_shard_size": "10gb",
                    "max_primary_shard_size_bytes": 10737418240
                  }
                }
              },
              "delete": {
                "min_age": 2592000000,
                "actions": [
                  "delete",
                  "migrate"
                ],
                "configurations": {}
              }
            },
            "indices_managed": 1
          },
          {
            "phases": {
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "30d",
                    "max_age_millis": 2592000000,
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "warm": {
                "min_age": 172800000,
                "actions": [
                  "shrink",
                  "forcemerge",
                  "migrate"
                ],
                "configurations": {
                  "forcemerge": {
                    "max_num_segments": 1
                  },
                  "shrink": {
                    "number_of_shards": 1
                  }
                }
              },
              "cold": {
                "min_age": 2592000000,
                "actions": [
                  "migrate"
                ],
                "configurations": {}
              },
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "30d",
                    "max_age_millis": 2592000000,
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              },
              "delete": {
                "min_age": 15552000000,
                "actions": [
                  "delete",
                  "migrate"
                ],
                "configurations": {}
              }
            },
            "indices_managed": 0
          },
          {
            "phases": {
              "hot": {
                "min_age": 0,
                "actions": [
                  "rollover",
                  "migrate"
                ],
                "configurations": {
                  "rollover": {
                    "max_age": "30d",
                    "max_age_millis": 2592000000,
                    "max_primary_shard_size": "50gb",
                    "max_primary_shard_size_bytes": 53687091200
                  }
                }
              }
            },
            "indices_managed": 0
          }
        ]
      },
      "logstash": {
        "available": true,
        "enabled": true
      },
      "ml": {
        "available": true,
        "enabled": true,
        "jobs": {
          "_all": {
            "count": 0,
            "detectors": {
              "total": 0,
              "min": 0,
              "avg": 0,
              "max": 0
            },
            "created_by": {},
            "model_size": {
              "total": 0,
              "min": 0,
              "avg": 0,
              "max": 0
            },
            "forecasts": {
              "total": 0,
              "forecasted_jobs": 0
            }
          }
        },
        "datafeeds": {
          "_all": {
            "count": 0
          }
        },
        "data_frame_analytics_jobs": {
          "memory_usage": {
            "peak_usage_bytes": {
              "total": 0,
              "min": 0,
              "avg": 0,
              "max": 0
            }
          },
          "_all": {
            "count": 0
          },
          "analysis_counts": {}
        },
        "inference": {
          "ingest_processors": {
            "_all": {
              "pipelines": {
                "count": 0
              },
              "time_ms": {
                "sum": 0,
                "min": 0,
                "max": 0
              },
              "num_docs_processed": {
                "sum": 0,
                "min": 0,
                "max": 0
              },
              "num_failures": {
                "sum": 0,
                "min": 0,
                "max": 0
              }
            }
          },
          "trained_models": {
            "model_size_bytes": {
              "total": 0,
              "min": 0,
              "avg": 0,
              "max": 0
            },
            "estimated_operations": {
              "total": 0,
              "min": 0,
              "avg": 0,
              "max": 0
            },
            "count": {
              "total": 1,
              "prepackaged": 1,
              "other": 0
            },
            "_all": {
              "count": 1
            }
          },
          "deployments": {
            "inference_counts": {
              "total": 0,
              "min": 0,
              "avg": 0,
              "max": 0
            },
            "model_sizes_bytes": {
              "total": 0,
              "min": 0,
              "avg": 0,
              "max": 0
            },
            "time_ms": {
              "avg": 0
            },
            "count": 0
          }
        },
        "node_count": 1
      },
      "monitoring": {
        "available": true,
        "enabled": true,
        "collection_enabled": true,
        "enabled_exporters": {
          "local": 1
        }
      },
      "rollup": {
        "available": true,
        "enabled": true
      },
      "searchable_snapshots": {
        "available": true,
        "enabled": true,
        "indices_count": 0,
        "full_copy_indices_count": 0,
        "shared_cache_indices_count": 0
      },
      "security": {
        "available": true,
        "enabled": true,
        "realms": {
          "file": {
            "name": [
              "default_file"
            ],
            "available": true,
            "cache": [
              {
                "size": 0
              }
            ],
            "size": [
              0
            ],
            "enabled": true,
            "order": [
              -2147483648
            ]
          },
          "ldap": {
            "available": true,
            "enabled": false
          },
          "native": {
            "name": [
              "default_native"
            ],
            "available": true,
            "cache": [
              {
                "size": 0
              }
            ],
            "size": [
              1
            ],
            "enabled": true,
            "order": [
              -2147483648
            ]
          },
          "jwt": {
            "available": true,
            "enabled": false
          },
          "saml": {
            "available": true,
            "enabled": false
          },
          "kerberos": {
            "available": true,
            "enabled": false
          },
          "oidc": {
            "available": true,
            "enabled": false
          },
          "active_directory": {
            "available": true,
            "enabled": false
          },
          "pki": {
            "available": true,
            "enabled": false
          }
        },
        "roles": {
          "file": {
            "dls": false,
            "size": 0,
            "fls": false
          },
          "native": {
            "dls": false,
            "size": 1,
            "fls": false
          },
          "dls": {
            "bit_set_cache": {
              "memory_in_bytes": 0,
              "memory": "0b",
              "count": 0
            }
          }
        },
        "role_mapping": {
          "native": {
            "size": 0,
            "enabled": 0
          }
        },
        "ssl": {
          "http": {
            "enabled": false
          },
          "transport": {
            "enabled": false
          }
        },
        "token_service": {
          "enabled": false
        },
        "api_key_service": {
          "enabled": true
        },
        "audit": {
          "enabled": false
        },
        "ipfilter": {
          "http": false,
          "transport": false
        },
        "anonymous": {
          "enabled": false
        },
        "fips_140": {
          "enabled": false
        },
        "operator_privileges": {
          "available": true,
          "enabled": false
        }
      },
      "slm": {
        "available": true,
        "enabled": true
      },
      "spatial": {
        "available": true,
        "enabled": true
      },
      "sql": {
        "available": true,
        "enabled": true,
        "features": {
          "having": 0,
          "subselect": 0,
          "limit": 0,
          "orderby": 0,
          "where": 0,
          "join": 0,
          "groupby": 0,
          "local": 0,
          "command": 0
        },
        "queries": {
          "cli": {
            "total": 0,
            "paging": 0,
            "failed": 0
          },
          "rest": {
            "total": 0,
            "paging": 0,
            "failed": 0
          },
          "canvas": {
            "total": 0,
            "paging": 0,
            "failed": 0
          },
          "odbc": {
            "total": 0,
            "paging": 0,
            "failed": 0
          },
          "jdbc": {
            "total": 0,
            "paging": 0,
            "failed": 0
          },
          "odbc32": {
            "total": 0,
            "paging": 0,
            "failed": 0
          },
          "odbc64": {
            "total": 0,
            "paging": 0,
            "failed": 0
          },
          "translate": {
            "count": 0
          },
          "_all": {
            "total": 0,
            "paging": 0,
            "failed": 0
          }
        }
      },
      "transform": {
        "available": true,
        "enabled": true
      },
      "voting_only": {
        "available": true,
        "enabled": true
      },
      "watcher": {
        "available": true,
        "enabled": true,
        "execution": {
          "actions": {
            "_all": {
              "total": 0,
              "total_time_in_ms": 0
            }
          }
        },
        "watch": {
          "input": {
            "_all": {
              "total": 0,
              "active": 0
            }
          },
          "trigger": {
            "_all": {
              "total": 0,
              "active": 0
            }
          }
        },
        "count": {
          "total": 0,
          "active": 0
        }
      },
      "archive": {
        "available": true,
        "enabled": true,
        "indices_count": 0
      }
    }
  }
}
</details>

<details>
  <summary>Metricbeat document</summary>
{
  "elasticsearch": {
    "version": 102,
    "cluster": {
      "name": "elasticsearch",
      "id": "84LZheH2SpODXi-mveFr4A",
      "stats": {
        "indices": {
          "store": {
            "size": {
              "bytes": 3031147
            }
          },
          "fielddata": {
            "memory": {
              "bytes": 0
            }
          },
          "docs": {
            "total": 186
          },
          "total": 10,
          "shards": {
            "count": 10,
            "primaries": 10
          }
        },
        "status": "yellow",
        "stack": {
          "xpack": {
            "ccr": {
              "enabled": true,
              "available": true
            }
          }
        },
        "license": {
          "start_date_in_millis": -1,
          "max_nodes": 1000,
          "issue_date_in_millis": 1651479695933,
          "uid": "5723e990-dc06-485a-bcc1-d77f05d71135",
          "type": "trial",
          "cluster_needs_tls": true,
          "status": "active",
          "issue_date": "2022-05-02T08:21:35.933Z",
          "expiry_date": "2022-06-01T08:21:35.933Z",
          "issued_to": "elasticsearch",
          "issuer": "elasticsearch",
          "expiry_date_in_millis": 1654071695933
        },
        "state": {
          "state_uuid": "n8Qd9JAiQq2h_kWIdKJjtw",
          "nodes": {
            "atE852ujT_2Ti0-mZlGJZA": {
              "ephemeral_id": "vuyfvNeHSUeVL1XMqiWRHg",
              "transport_address": "127.0.0.1:9300",
              "attributes": {
                "ml.max_jvm_size": "1610612736",
                "xpack.installed": "true",
                "ml.machine_memory": "68719476736"
              },
              "roles": [
                "data",
                "data_cold",
                "data_content",
                "data_frozen",
                "data_hot",
                "data_warm",
                "ingest",
                "master",
                "ml",
                "remote_cluster_client",
                "transform"
              ],
              "name": "Miltons-MBP.lan"
            }
          },
          "nodes_hash": 1295361615,
          "master_node": "atE852ujT_2Ti0-mZlGJZA"
        },
        "nodes": {
          "master": 1,
          "fs": {
            "total": {
              "bytes": 1000240963584
            },
            "available": {
              "bytes": 878391582720
            }
          },
          "jvm": {
            "max_uptime": {
              "ms": 78641
            },
            "memory": {
              "heap": {
                "used": {
                  "bytes": 700721216
                },
                "max": {
                  "bytes": 1610612736
                }
              }
            }
          },
          "versions": [
            "8.3.0"
          ],
          "count": 1
        }
      }
    }
  },
}
</details>

**Comment by miltonhultgren** [comment]
@elastic/es-data-management Can you offer insight about how the version is decided when using Internal Collection?

**Comment by dakrone** [comment]
It appears to use `Version.CURRENT.toString();`, so the current version of whatever ES instance created the (internal) document.

**Comment by miltonhultgren** [comment]
@dakrone That sounds like fun, so during a rolling update we might get different versions displayed depending on which node the current document is created on (unless only the master node creates those documents)?

**Comment by dakrone** [comment]
> (unless only the master node creates those documents)?

In this case, I was looking at the `ClusterStatsCollector` which creates the `ClusterStatsMonitoringDoc` which runs on the master node, so it will use the version from the current master.

**Comment by miltonhultgren** [comment]
@dakrone Thanks for looking that up! Much appreciated!
