### ISSUE TITLE
Requests for various improvements

### ISSUE THREAD

**Issue by sangkyunkim89** [elastic/beats#31523]
I'm writing this post for some improvements and feature requests.

1. It is inconvenient that the time does not appear when you hover your mouse over the matrix 
When I searched for a long start and end time, I thought it was really inconvenient.

2. There are also metrics that do not appear when the start and end times are short.
Of course, if I give it a little longer, it's me, but I think it's right to come out

3. I wish I could show other metrics as well as average delay
ex) 1 percentlie, 50, 99, N ....

![image](https://user-images.githubusercontent.com/65607130/166856722-d8bb0fa5-039d-4f39-916a-b72a674ad7b3.png)

![image](https://user-images.githubusercontent.com/65607130/166856590-1eb5cb19-3964-4eaf-aaeb-95d595a37085.png)

![image](https://user-images.githubusercontent.com/65607130/166856987-722e2288-c9ae-4d80-83e4-6d75b45bc51e.png)

I hope you will reflect it, thank you!

**Comment by tetianakravchenko** [comment]
Hi @sangkyunkim89, from which module this dashboard is coming from?

**Comment by sangkyunkim89** [comment]
@tetianakravchenko 

It's the data I got from metricbeat and I'm seeing it on kibana


![image](https://user-images.githubusercontent.com/65607130/167136534-6d7dd23c-659f-4782-a41c-8c9103535ec4.png)

stack monitoring

**Comment by kaiyan-sheng** [comment]
cc @elastic/stack-monitoring for awareness

**Comment by smith** [comment]
These are valid requests but not something we're going to be prioritizing any time soon. We would welcome a pull request with these enhancements, and some of them look like they could be achieved by some configuration of Elastic Charts.
