### ISSUE TITLE
Offline/queuing mode

### ISSUE THREAD

**Issue by markwalkom** [elastic/beats#3155]
If you're running metricbeat on a laptop, or on a remote host with spotty network connectivity, you may have periods where you cannot reach your ES cluster to upload stats. This means you lose the stats over these periods of disconnect, which may actually prove to be useful.

In these sorts of instances it'd be great if we could still collect stats, store them locally, then upload them upon reconnection to the endpoint cluster.

I'm imagining some kind of compressed file that we store somewhere after a configurable period of time, then slowly stream to ES.

**Comment by ruflin** [comment]
@markwalkom We are discussing a potential local queue on the beats side for some time which would help in these cases. The change will probably happen in libbeat so it is available to all beats.

**Comment by DirkAmelinckx** [comment]
+1

**Comment by loekvangool** [comment]
+1

**Comment by devKlausS** [comment]
+1
