### ISSUE TITLE
GA Beats msi installer

### ISSUE THREAD

**Issue by jamiehynds** [elastic/beats#31575]
Our .msi installers for Beats, have been in Beta for quite some time but should be GA to convey to users that the installers are fully supported. 

Can we GA these installers across all relevant Beats?

`

**Comment by nimarezainia** [comment]
@jamiehynds yes this belongs to us. thanks

**Comment by nimarezainia** [comment]
Our focus is to provide an msi installer for the agent, therefore closing this issue.

**Comment by a03nikki** [comment]
One of the issues for Elastic Agent is at https://github.com/elastic/beats/issues/24825.

**Comment by nimarezainia** [comment]
Elastic Agent MSI will be available for download in 8.13
