### ISSUE TITLE
[Filebeat] aws-s3 input - support multiple expand_event_list_from_field

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#31583]
**Describe the enhancement:**

Allow the aws-s3 input to accept `expand_event_list_from_field` as a list (and a string for backwards compatibility). It would try the fields in order until it finds one that exists.

**Describe a specific use case for the enhancement or feature:**

Some AWS logs use a mix of `configurationItems` and `configurationItem` so this would allow the input to work with both when it's not possible to identify the logs based on their path using `file_selectors`.

**Comment by legoguy1000** [comment]
Could this potentially be implemented with my #29951 PR?
