### ISSUE TITLE
Add docs for the Recorded Future fileset

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/beats#31596]
The [Threat Intel module](https://www.elastic.co/guide/en/beats/filebeat/8.2/filebeat-module-threatintel.html) topic need to be updated to reflect that an integration for the [Recorded Future](https://docs.elastic.co/integrations/ti_recordedfuture) threat feed is now available. In addition, I'll need to insert a new section for the Recorded Future fileset configuration details.

Related issues/PRs:
- https://github.com/elastic/integrations/pull/2757
- https://github.com/elastic/integrations/pull/2916
- https://github.com/elastic/integrations/pull/3042

cc: @dedemorton @adriansr

**Comment by nastasha-solomon** [comment]
I'll be working with @dedemorton to make sure the CI checks pass on the PR I'll eventually be opening.

**Comment by dedemorton** [comment]
So based on Adrian's PR [here](https://github.com/elastic/beats/pull/31581), it looks like we can close this issue because the Recorded Future fileset does not exist in the Filebeat module.
