### ISSUE TITLE
Osquerybeat: Improve live query timeout handling 

### ISSUE THREAD

**Issue by aleksmaus** [elastic/beats#31638]
One of our users inquired about the way to increase the timeout for the live query. The queries that they run exceed the default timeout of 1 minute.

The .fleet-action timeout setting is not exposed anywhere on the UI, but can be adjusted with the .fleet-action document ```timeout``` property, expressed in seconds. This ```timeout``` property allows to change the time interval the Elastic Agent awaits for Osquerybeat to respond with the action (query) result.
The Agent responds with the action timeout error when Osquerybeat doesn't respond with the result in the given action ```timeout``` interval. 

There is no timeout for the query execution over the connection between Osquerybeat and Osqueryd processes.

There are few side effects to this approach:
1. Osquerybeat could still be running possibly an expensive query, taking up the resources.
2. The https://github.com/osquery/osquery-go client that is used for communication between Osquerybeat and Osqueryd doesn't have any thread-safety, so there is a code in place in Osquerybeat to have only one query running over the client connection at a time. The long running query could potentially block other queries from being executed.

Presently there is no timeouts on the query execution, when Osquerybeat is sending the query request to Osqueryd over the thrift protocol,  unless there is some built-in query execution timeout implemented insides of osqueryd(to be verified). So the query will run as long as takes to complete.

**Describe the enhancement:**

In order to avoid the problems listed above, the Osquerybeat needs to be modified to cancel the query execution if the action timeout is exceeded. The query/action timeout would need to be exposed through the UI and API on Kibana side in order to be able to the client increase the timeout if needed.

ATTN!!!: Increasing the timeout will block other queries from executing until the initial query completes. Use it carefully.

**Describe a specific use case for the enhancement or feature:**

The use case: 
1. The client starts an expensive live query that takes longer than the fleet action timeout (one minute by default).
2. The client starts another query. The execution of that query will be blocked until the previous query completes, which potentially can cause the second query to timeout as well. 
The expected result: The initial query execution is canceled after the given timeout and the Osqueryd client is immediately available for the second query execution.

**Comment by melissaburpo** [comment]
Team meeting notes about this from today:
* This option only applies to Live queries. 
* Design proposal: add an Action Timeout option (name TBD) that shows the default setting and allows users to change the value if desired. For example, if they want to run a resource intensive query, they have an option to increase the timeout for that specific query.

**Comment by aleksmaus** [comment]
This is done with https://github.com/elastic/beats/pull/36722. Closing.
