### ISSUE TITLE
loadbalnce: true and Windows

### ISSUE THREAD

**Issue by centran** [elastic/beats#3165]
This is not a bug but more of something that you may want to note in the documentation. 

We discovered that with the loadbalancing set to true and a longer list of hosts(we had 7) that there is a "feature" in Windows with the base filtering engine (BSE). The featured is turned on by default for Windows Server 2012 > and other personal versions. It silently blocks packets it thinks are either a syn attack or a port scan.

What was happening for us was logstash was ack'ing events but filebeat never received the ack since windows blocked it. The block is really bad since it happens at a lower level then the windows firewall so it is hard to track down and turn off. The issue arises when there was multiple logstash servers trying to talk to filebeat. Since filebeat is a beat that must ack a event and doesn't have a timeout if filebeat was shutdown it would start reading logs from the start again since it never wrote its position in the registry file.

This isn't a beat or filebeat bug but something you may want to note in the documentation under the loadbalance config.

The normal round robin loadbalancing of hosts is fine so putting in multiple hosts isn't an issue. It is only an issue with loadbalance:true and running on Windows servers.

**Comment by ruflin** [comment]
@centran Thanks a lot for pointing to this. We had a few issues in the past on Windows that we kept scratching our head but could be explained by this. Can you share what the exact config is that has to be changed?

@sprysprocket You might be very interested in this one as this could be potentially the solution to https://github.com/elastic/beats/issues/3098.  

@urso @ph FYI

**Comment by sprysprocket** [comment]
@ruflin Thanks for the heads up. We are running into #3098 on CentOS 6.x hosts, and this sounds Windows specific. That said, I realize I didn't provide this detail in my discussion thread, or in the bug report. I'll update those to reflect the OS.

**Comment by maddin2016** [comment]
Hi @centran, what happens if you disabled the service?

**Comment by maddin2016** [comment]
Background of my question is we can not document that BFE blocks metricbeat without to prove that it's really the BFE Engine. Maybe it's some Anti Virus program that blocks this packets. We have sometimes big trouble with McAfee. @ruflin, or i'm wrong??

**Comment by centran** [comment]
We saw security events in the event viewer that suggested BFE. Adding an any - any rule with the firewall on and then disabling the firewall corrected the issue. The rule had to be added first as just disabling didn't work... Yeah, weird stuff happens with BFE. This issue does not happen if we do not set loadbalance to true which of I understand it correctly opens a connection to all servers in the host list. We had 7.

Our servers do have McCrappy so maybe that was playing a role. Also it could be our crazy firewalled off network but we couldn't find any indication the blocks where caused there.  I can try to test the anti virus next week and see what happens. 

As for IIS not causing an issue, you are right. However I was informed by our systems team that they saw a similar issue with our Active directory setup. That previous issue pointed us in the BFE direction which we believed was the cause. 

We just went with regular round robin of the host list and haven't seen an issue yet. We only saw a very small performance increase with loadbalance set to true so investigating further wasn't worth it.

**Comment by centran** [comment]
I'll also try to find some of the articles I was looking at with people having similar issues with other products.

**Comment by ruflin** [comment]
@centran Some links to articles with similar issues would be very nice.
@maddin2016 Having a note in the docs that it could be BFE I don't think is wrong. Until this issue popped up I was not even aware of BFE (I'm not really a Windows user). So I think already a note can be helpful for people to further investigate tools outside of the beat itself, in case something goes wrong. We could make it more generic by mentioning firewall or anti virus application an mention BFE and some anti virus systems as examples.

**Comment by maddin2016** [comment]
>So I think already a note can be helpful for people to further investigate tools outside of the beat itself
👍. But then this note should be for all beats which has `loadbalance` as an option.

**Comment by dedemorton** [comment]
@ruflin Is this doc issue still valid now that `publish_async` has been removed? Can I close this issue?

**Comment by ruflin** [comment]
Lots of changes happened in the pipeline in 6.0 related to the pipeline, loadbalance and `publish_async` which was removed. I think it would be best if @urso could comment here and decide if this is still needed.

**Comment by urso** [comment]
I'm not really familiar with BFE. But from reading the issue, I'm not even sure it's BFE or just firewall or the interaction of a many tools involved. It's good to keep these kind of potential issues in mind when doing support, but not sure we want to have it officially documented, if we don't really yet understand what's really going on (on OS and network layer). Even NAT or any kind of TCP proxy with low connect state timeout can trigger this issue (yay for firewalls filtering out RST packages). TCP is a kinda fragile protocol TBH, and there a many things that can go wrong thanks to third party devices/software/firewals/etc... .

As this is an issue with load-balancing (having a many connections), the problem should still be the same with 5.x and 6.x .

**Comment by urso** [comment]
This issue has seen no progress for quite some time. Plus, we don't really have an understanding of the actual cause. I'm closing the issue for now. Feel free to re-open when we have new evidence, or if it becomes clear what exactly to document.
