### ISSUE TITLE
LibBeat testsuite - Python 3 compatibility ./vendor/github.com/elastic/beats/dev-tools/aggregate_coverage.py

### ISSUE THREAD

**Issue by florck** [elastic/beats#3166]
- Version: current master, with python3

- Operating System: all

- Steps to Reproduce: 
Configure a new beat project with libbeat and test it:
```bash
make testsuite
```

- Error : 
```bash
make coverage-report
make[1] : on entre dans le répertoire « /home/fthoni/.goenv/vspherebeat/src/git.teamwork.net/BeatsTeamwork/vspherebeat »
python ./vendor/github.com/elastic/beats/dev-tools/aggregate_coverage.py -o /home/fthoni/Documents/Travail/TW/elastic/vspherebeat/git.teamwork.net/BeatsTeamwork/vspherebeat/build/coverage/full.cov /home/fthoni/Documents/Travail/TW/elastic/vspherebeat/git.teamwork.net/BeatsTeamwork/vspherebeat/build/coverage
Traceback (most recent call last):
  File "./vendor/github.com/elastic/beats/dev-tools/aggregate_coverage.py", line 49, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./vendor/github.com/elastic/beats/dev-tools/aggregate_coverage.py", line 39, in main
    if lines.has_key(position):
AttributeError: 'dict' object has no attribute 'has_key'
make[1]: *** [vendor/github.com/elastic/beats/libbeat/scripts/Makefile:224: coverage-report] Error 1
make[1] : on quitte le répertoire « /home/fthoni/.goenv/vspherebeat/src/git.teamwork.net/BeatsTeamwork/vspherebeat »
make: *** [vendor/github.com/elastic/beats/libbeat/scripts/Makefile:206: testsuite] Error 2
```
- Analysis 
In python 3, has_key has been deprecated. Now one is supposed to do 
```python
if position in lines:
```

- Localisation of the problem
  File "./vendor/github.com/elastic/beats/dev-tools/aggregate_coverage.py", line 39, in main

**Comment by ruflin** [comment]
@florck Thanks for bringing this up. We are aware that there are quite a few things that are not fully compatible with Python 3, but we try to keep it compatible. Could you open a PR with the change?

@ESamir I removed the bug label as it is more a version problem. But I agree we probably should not state in https://github.com/elastic/beats/blob/master/CONTRIBUTING.md `>= 2.7.9` but `>= 2.7.9 AND <= 3.0`.
