### ISSUE TITLE
[Fliebeat][haproxy module] Grok error on long haproxy.http.request.raw_request_line 

### ISSUE THREAD

**Issue by pontostroy** [elastic/beats#31681]
I got grok error if the raw_reques line is > 665-670 symbols
Error example:
`Provided Grok expressions do not match field value: [May 19 11:24:44 INFO:  10.0.11.91:40404 [19/May/2022:11:23:25.572] apps_frontend xxxxxxxxxxx-c/xxxxxxxxxXXx-3 0/0/0/6/78670 101 411 - - ---- 175/175/50/50/0 0/0 {XXXXXXXXXXXX|XXXXXXXXXXXX|xxxxxxxxxx-x.xxxXXXxxxxxx.xxx|Mozilla/5.0 (Linux; Android 10; M20XXXXXXX) AppleWebKit/537.36 (KHTML, like Geck|https://XXXXXXXX.xxxxxxxx.com} {} \"GET /signalr/connect?transport=webSockets&clientProtocol=1.5&XXXXXXXXXXId=XXXXXX5&ClientConnected=&ClientDisconnected=&Currency=XXX&XXXXXXId=XXXX&XXXX=XXXXXXXXXXXXXXXXXXXXXXXX&XXXXCode=vXXXXXXXXX&XXXXXXXXX=&XXXXXXXXXXXId=332232888XXXXXX&HubName=XXXXWindow&HubUrl=https%3A%2F%2Fxxxxxxxxxx-x.xxxxxxxxx.xxx%2F&Id=&Ip=XXXXXXXXXX&IsMobile=true&Jurisdiction=XXXXXX&LaunchUrl=&xxxxxxxxType=XXXXxxXX&XXXxXXXXUserId=XXXXXXXXX&Sid=a8ecdfe6-146b-48dc-8a98-5dc5750e45ce&Token=13487714_2130_ML5vFCrxJEWCjH87Rh&UseV3Version=false&XXXXId=13487714&Vendor=XXXXXXxxxXXXX&VXXXXXxxxXX=214&connectionToken=%2FbSAypa6kshRsABvLns8elgGYnpivjtjqzAxTFjZFiWUhC5xuPZJT2KPQQgWvzjUMXqPSh8VpKxCG25hXXXXX]`

ELK and FIlebeat version = 7.17.3
Ubuntu 20.04
HA-Proxy version 2.0.13-2ubuntu0.5

**Comment by hrak** [comment]
Experienced the same, then found out that HAproxy by default truncates log lines if they exceed 1024 bytes, causing f.e. the http version field to get truncated off the log line, which breaks the grok pattern.
