### ISSUE TITLE
Metricbeat fails to collect "node" metrics from a logstash instance with multiple pipelines

### ISSUE THREAD

**Issue by lukeyeager** [elastic/beats#31698]
Let's look at this code: https://github.com/elastic/beats/blob/v8.2.0/metricbeat/module/logstash/node/data.go#L45-L120

1. `fields` is created on line 91 - **before** the pipeline loop starts
2. The first iteration of the pipelines loop calls `commonFieldsMapping()` on line 119
3. After accessing values from `fields`, they are deleted e.g. see line 55
4. The next loop iteration fails with `Error fetching data for metricset logstash.node: Could not find field 'id' in Logstash API response`

If you browse [the commit](https://github.com/elastic/beats/commit/ae83e461cbfbc0f0613fc92810ac18b4e4dd4038) which introduced this bug, you'll see that the pattern works fine for all other metricsets where it's used - it's just logstash.node which breaks because it's done in a loop.

This was previously reported here (but never root-caused): https://discuss.elastic.co/t/299651.

**Comment by matschaffer** [comment]
Closing in favor of https://github.com/elastic/beats/issues/31739

**Comment by matschaffer** [comment]
whoops. Actually closing.
