### ISSUE TITLE
[Heartbeat] Use fixed synthetics-agent versions in Heartbeat images

### ISSUE THREAD

**Issue by lucasfcosta** [elastic/beats#31732]
# Summary

We can accomplish this by only pulling the `stack_release` label from NPM, rather that `latest`. This is currently blocked on us putting that label into production. This will make it easier to determine which version of the agent is out in heartbeat, and ensure that we have adequate time to E2E test that version before it makes it into a bulid candidate.

~We should use fixed versions of the [elastic/synthetics](https://github.com/elastic/synthetics) package in Heartbeat images.~

~That's necessary because it allows us to:~

~1. Use the synthetics-agent version as part of the tag we'll use to build Heartbeat image versions on-demand.~
~2. Makes it easier to determine the actual package version shipped with a particular HB version.~ 
~Right now, to figure that out, we have to look at when a version was released, then look at what version of the package was released at the time.~
~. Diminishes the chance of us breaking HB by releasing a broken the agent version which ends-up getting picked up by HB which always uses `latest`.~

**Comment by andrewvc** [comment]
This is currently blocked until we can release `synthetics` packages with the `stack_release` label. Edited main issue to reflect that.
