### ISSUE TITLE
Support for conf.d style configuration

### ISSUE THREAD

**Issue by bacoboy** [elastic/beats#3174]
I'm been combing the documentation for beats (filebeat specifically) and want to use it as a central log relay for a server.  However, I'm creating a base image (with prospectors for system logs, etc) and then creating additional derived images which have their own logs I'd like to add prospectors for.

To support this kind of piecemeal assembly, many unix tools have started using configuration directories in addition to a master configuration file.  For instance:
* logrotate -> main config: /etc/logrotate.conf + config directory: /etc/logrotate.d/*
* sudo -> /etc/sudoers + /etc/sudoers.d/
* sysctl -> /etc/sysctl.conf + /etc/sysctl.d/

and so on.

Using this scheme, I can configure common things (like the main outputs) in the base configuration file and have each application that gets installed pepper-in additional prospectors as I build up images.  Adding squid proxy? -- add a config for /var/log/squid/*.log, etc...

I've considered using things like templates to construct this, but figured I'd ask as this seems to be a common pattern beats don't currently support with a single configuration file (and the inability to include snippets in YAML)

**Comment by andrewkroh** [comment]
See [config_dir](https://www.elastic.co/guide/en/beats/filebeat/5.1/configuration-global-options.html#_config_dir) in the official docs and [StackOverflow: Can Filebeat use multiple config files?](https://stackoverflow.com/questions/39983918/can-filebeat-use-multiple-config-files/39987501#39987501).

**Comment by bacoboy** [comment]
Thanks this is super helpful.  Do you think it is worth keeping this open to update the docs/sample configuration files/packages to create a conf.d placeholder directory which is empty but included automatically?

**Comment by andrewkroh** [comment]
You can open a new enhancement issue for this. I'd mention this one in it. https://github.com/elastic/beats-packer/issues/27
