### ISSUE TITLE
[Stack Monitoring] Mapping for elasticsearch.node.stats.os.cgroup.memory.limit.bytes is incorrect

### ISSUE THREAD

**Issue by matschaffer** [elastic/beats#31765]
https://github.com/elastic/beats/blob/87949288faf8450b35a12ae946050444d4272c18/metricbeat/module/elasticsearch/node_stats/_meta/fields.yml#L295-L300 (and https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/resources/monitoring-es-mb.json#L742 which derives from fields.yml) maps `elasticsearch.node.stats.os.cgroup.memory.limit.bytes` as long, but according to https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html it's a string value.

Normally the implicit conversion is fine, but in some cases ([forum example](https://discuss.elastic.co/t/metricbeat-8-2-1-monitoring-elasticsearch-8-2-1-template-issue/305649/3)) it will return `max` which causes an error at indexing time due to the `long` mapping in the template.

**Comment by matschaffer** [comment]
cc @elastic/infra-monitoring-ui for awareness

**Comment by gbit-is** [comment]
Having the same trouble on 8.3.0 and 8.3.1
can't monitor the cluster because of this

**Comment by matschaffer** [comment]
This came up on https://discuss.elastic.co/t/stack-monitoring-elasticsearch-nodes-not-displayed-as-monitored-with-metricbeat/307979/3 as well

**Comment by matschaffer** [comment]
Another forum post https://discuss.elastic.co/t/metricbeat-fails-to-parse-field/308446
