### ISSUE TITLE
[libbeat] The output.events.active metric can be negative

### ISSUE THREAD

**Issue by HugoKuo** [elastic/beats#31782]
For confirmed bugs, please report:
- Version:  filebeat.x86_64                  7.10.2-1                 @/filebeat-oss-7.10.2-x86_64LtGs8_
- Operating System:  CentOS Linux release 7.9.2009 (Core)
- Discuss Forum URL: https://discuss.elastic.co/t/how-to-read-the-monitoring-log-of-filebeat/305721
- Steps to Reproduce: Running filebeat in the frontground. There're a thoudsand nodes sending logs to elasticsearch.out 6 hosts. 

The active -1140 is kind confusing.
"output":{"events":{"acked":9332,"active":-1140,"batches":8,"total":8192}

**Comment by cmacknz** [comment]
We have seen this before but never found the root cause. Possibly the same problem as in https://github.com/elastic/beats/issues/31582
