### ISSUE TITLE
FileBeat's File Output class does not accept variables for path or filename

### ISSUE THREAD

**Issue by kklemmicknvidia** [elastic/beats#3178]
FileBeat Version: 5.1.1

Existing docs suggest that config file strings can use "format strings" to substitute tokens in strings:
https://www.elastic.co/guide/en/beats/libbeat/current/config-file-format-type.html#_format_string_sprintf

However, when I try to name my output file dynamically by using a field in the event it doesn't work:

```
output.file:
  path: '/logs/'
  filename: 'job%{[jobid]}.log'
```

This just outputs a file named 'job%{[jobid]}.log'.

Looking at the source code, it's clear why. The fileOutput object uses the FileRotator object to do its IO, and the FileRotator does no substitution when determining the FilePath:

```
func (rotator *FileRotator) FilePath(file_no int) string { 
	if file_no == 0 { 
		return filepath.Join(rotator.Path, rotator.Name) 
	} 
	filename := strings.Join([]string{rotator.Name, strconv.Itoa(file_no)}, ".") 
	return filepath.Join(rotator.Path, filename) 
}
```

Doing substitution in this case would require additional changes though, as (a) FileRotate tracks size as an increment on each write, and this wouldn't be the case if each write could potentially go to a different file, and (b) FileRotate only opens the file once in the Rotate() method, but would instead need to open it on each Write call, since each call could go to a different destination. (c) fileOutput passes a simply byte array representation of the json to Write rather than a json object, so doing the substitution there would require changing the call parameters or adding a separate call into the FileRotate object.

Of course, this is all doable, but isn't a trivial change. It would allow this kind of string formatting though, which is a useful feature.

I might be willing to do this work if this is a feature that folks think is worthwhile and is likely to get picked up. I don't want to rely on a branch of the source code.

Thoughts?

**Comment by andrewkroh** [comment]
Related discussion: https://discuss.elastic.co/t/can-filebeat-be-configured-to-output-dynamic-file-names/68615

**Comment by andrewkroh** [comment]
Another request: https://discuss.elastic.co/t/beat-file-output-dynamic-naming/98583

**Comment by meckhardt** [comment]
:+1:

**Comment by wangycc** [comment]
https://docs.fluentd.org/v1.0/articles/out_file

**Comment by undying** [comment]
Wow, four years have passed but there is no changes.
Sad :(
