### ISSUE TITLE
export the number of CPU cores

### ISSUE THREAD

**Issue by sitanxin** [elastic/beats#3186]
As discuss, would you help to provide the export the number of CPU cores in metribeat?

For confirmed bugs, please report:
- Version: metricbeat 5.0.1
- Operating System: RHEL 6
- Steps to Reproduce: 
As mentioned in https://discuss.elastic.co/t/how-to-check-the-cpu-number-from-metricbeat/68803

**Comment by sitanxin** [comment]
And also, can it export the OS version or allow to run the command in the beat? like cat /etc/redhat-release ?

**Comment by maddin2016** [comment]
Hi @ruflin, @monicasarbu. What do you think of if we add a simple helper function 
```
func GetCores() int {
	cores := runtime.NumCPU()
	return cores
}
```
my problem currently is where to store this information. Into every fetch? I dont think this is a good solution. Because it is more of an onetime value. Is there a place to store such values?

**Comment by ruflin** [comment]
I suggest to put it under `system.cpu.cores: 4`. We do not have a special place for values that do not change that often. Such values should also compress quite well.

@sitanxin Can you open a second feature request for the os version as this is a different request?

**Comment by maddin2016** [comment]
Ok, then i open a PR.
