### ISSUE TITLE
Flaky Test: TestMaxBytesLimit intermittently fails

### ISSUE THREAD

**Issue by taylor-swanson** [elastic/beats#31863]
## Flaky Test

* **Test Name:** TestMaxBytesLimit
* **Link:** [libbeat/reader/readfile/line_test.go](https://github.com/elastic/beats/blob/main/libbeat/reader/readfile/line_test.go#L402)
* **Branch:** main
* **Notes:** This test may have been broken by a recent change introduced in https://github.com/elastic/beats/pull/31824. The test seems to fail roughly 30% of the time, but this can highly vary. It's best to run the test with the `-count` flag, otherwise the test will likely pass, and Go will cache the results.
* 
```
cd libbeat/reader/readfile
go test -test.run TestMaxBytesLimit -count 100 .
```

### Error

```
--- FAIL: TestMaxBytesLimit (0.00s)
    line_test.go:402: the bytes read are not equal to the bytes input, expected: 81273 got: 76439
```

**Comment by liuwenping** [comment]
sorry, I'll fix this problem today.

**Comment by cmacknz** [comment]
Fixed by https://github.com/elastic/beats/pull/31882
