### ISSUE TITLE
Have the `add_cloud_metadata` processor enrich events with EC2 tags

### ISSUE THREAD

**Issue by psypuff** [elastic/beats#31899]
**Describe the enhancement:**
Similar to #12263 but not for a specific module, for anything beats is monitoring within an EC2 VM.
Since [Jan 2022](https://aws.amazon.com/about-aws/whats-new/2022/01/instance-tags-amazon-ec2-instance-metadata-service/) EC2 tags are also available through the Instance Metadata Service. This is where the `add_cloud_metadata` processor fetches metadata from anyway so it doesn't seem like a big change.

**Describe a specific use case for the enhancement or feature:**
This will allow filtering and grouping hosts based on EC2 tags (e.g. Name) in the Observability metrics inventory view of Kibana (and probably some other views as well). This is much more useable than IPs or instance IDs.

**Comment by hatdropper1977** [comment]
@cmacknz - Can we get this feature enabled?

**Comment by cmacknz** [comment]
@bturquet would know if this is planned for the near future.

**Comment by dejongm** [comment]
@bturquet Any word on this feature? This would be extremely useful!

**Comment by george-viaud** [comment]
This feature would be very useful for our org.  Presently we need to modify logs to include this data individually.  Having it provided natively would reduce a lot off pain at the instance level.  Thank you

**Comment by Kavindu-Dodan** [comment]
IMDS [1] only exposes tags if instance explicitly expose them in metadata ,

> The instance tags associated with the instance. Only available if you explicitly allow access to tags in instance metadata. [2]

Enabling tags can be done through the console or CLI [3]. 

[1] - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html
[2] - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-categories
[3] - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/work-with-tags-in-IMDS.html
