### ISSUE TITLE
filebeat input/output support apache pulsar middware

### ISSUE THREAD

**Issue by azeng528** [elastic/beats#31963]
# Metricbeat Module / Dataset release checklist

apache pulsar is good middware

* Team: Microsoft
## Filebeat module

* [ ] filebeat output pulsar
* [ ] filebeat input pulsar

**Comment by azeng528** [comment]
Team:<microsoft>

**Comment by belimawr** [comment]
Closing as it's a duplicated by: https://github.com/elastic/beats/issues/31962
