### ISSUE TITLE
Document that the max_bytes configured for the filebeat log input may be multiplied by 4

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#31984]
When setting `max_bytes` in Filebeat to ignore log lines that are larger than a specific amount in  bytes, it seems whatever value is put in `max_bytes` gets multiplied by 4. We should add a note to https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#_max_bytes_2

E.g.: setting

```yml
max_bytes: 128000
```

What you see in FB logs:

```yml
filebeat_1  | 2022-03-16T17:09:47.146Z  WARN    [reader_line]   readfile/line.go:178     Exceeded 512000 max bytes in line limit, skipped 939352 bytes line
```

The 4x multiplier is intentional to account for UTF-8 character sizes: https://github.com/elastic/beats/pull/19552/files#r449142711

Let's document that this is the behaviour so users are not surprised when expecting to see the byte limit they configured used in the logs.

**Comment by deepto98** [comment]
Can I pick this up?

**Comment by cmacknz** [comment]
@deepto98 sure, if it's unassigned nobody else is working on it (at least not from Elastic).

**Comment by R55555** [comment]
Is the issue solved? Can I pick this up?

**Comment by R55555** [comment]
I have created a PR. Is it OK?
