### ISSUE TITLE
Multiple System module configuration in metric beats

### ISSUE THREAD

**Issue by kumar1993** [elastic/beats#3200]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version: 
- Operating System: 
- Steps to Reproduce:

**Comment by kumar1993** [comment]
Is there a way to add multiple boxes system module in metric beat, say i have box1 and box2 running a bunch of process is there a way to configure metric beat to send load on  both the boxes to elasticsearch?

**Comment by ruflin** [comment]
Yes, this is possible. Have a look at https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-configuration.html

For questions please us discuss as pointed out in the github issue above ;-) Closing this one.
