### ISSUE TITLE
[Metricbeat] Incorrect Logstash module mappings and duplication of fields on documents

### ISSUE THREAD

**Issue by Kerry350** [elastic/beats#32038]
Please see here: https://github.com/elastic/beats/pull/31985#issue-1275320143 and here: https://github.com/elastic/beats/pull/31985#issuecomment-1160285520

> looks like the aliases were lost in translation when creating the logstash integrations (which the .monitoring-{product}-mb mappings are based on) because they were defined in the [7.x version](https://github.com/elastic/beats/blob/7.17/metricbeat/module/logstash/node/_meta/fields.yml#L1)

Several aliases, for example `logstash.node.host` to `host.hostname`, `logstash.node.version` to `service.version` etc are missing in the mappings. [These existed in 7](https://github.com/elastic/beats/blob/7.17/metricbeat/module/logstash/node/_meta/fields.yml#L8), but [not in 8](https://github.com/elastic/integrations/blob/main/packages/logstash/data_stream/node/fields/fields.yml#L5).

As a side effect these fields exist in two locations on the document (in their event "root" location and nested under `node`). This is the code that *should* be responsible for placing fields on the root of the event, and removing them from the metricset level fields: https://github.com/elastic/beats/blob/main/metricbeat/module/logstash/node/data.go#L46 

Once the correct aliases exist in the mappings we can simply swap this line: https://github.com/elastic/beats/blob/main/metricbeat/module/logstash/node/data.go#L120

**above** this line: https://github.com/elastic/beats/blob/main/metricbeat/module/logstash/node/data.go#L118

this will ensure we only index what's needed (and not the `.node` duplicates).

Nothing is broken right now as the data is indexed in the two locations, however this is wasteful, does not accurately reflect what's in the docs, and isn't the intended behaviour so we probably want to fix this soon.

**Comment by llermaly** [comment]
Hello @Kerry350 , we are facing this issue in 8.3.3 stack

![image](https://user-images.githubusercontent.com/8575569/187203126-640ff9e5-c919-4659-8c0e-100d22be79a4.png)

What you are suggesting is this error is not related to this PR? Thank you!

**Comment by Kerry350** [comment]
Hello,

This original PR: https://github.com/elastic/beats/pull/31985 fixes this issue: https://github.com/elastic/beats/issues/31739

This seems to be the same issue you're referencing in your screenshot. The PR is merged, and should have been released with 8.4 (so would need to upgrade from 8.3.3).

This ticket is for a followup cleanup issue that came about from that work.
