### ISSUE TITLE
[Stack Monitoring] Request paginated index stats from ES

### ISSUE THREAD

**Issue by matschaffer** [elastic/beats#32041]
https://github.com/elastic/elasticsearch/issues/87555 is open to add paging to the index stats API.

Once it's available, we should update metricbeat to issue paged queries to timing out on very large responses.

**Comment by original-brownbear** [comment]
@matschaffer as discussed linking https://github.com/elastic/elasticsearch/issues/87555 here for the suggested approach to paginating the index stats API.
