### ISSUE TITLE
failed to install dashboards

### ISSUE THREAD

**Issue by kofemann** [elastic/beats#3204]
Hi, 

after installing packetbeat I fail to install dashboards: 

./import_dashboards
Create temporary directory /tmp/tmp716928970
Downloading https://artifacts.elastic.co/downloads/beats/beats-dashboards/beats-dashboards-5.1.1.zip
Unzip archive  /tmp/tmp716928970
/tmp/tmp716928970/beats-dashboards-5.1.1/filebeat
/tmp/tmp716928970/beats-dashboards-5.1.1/heartbeat
/tmp/tmp716928970/beats-dashboards-5.1.1/metricbeat
/tmp/tmp716928970/beats-dashboards-5.1.1/packetbeat
Import directory  /tmp/tmp716928970/beats-dashboards-5.1.1/packetbeat/index-pattern
......
fail to import dashboards: fail to load directory /tmp/tmp716928970/beats-dashboards-5.1.1/packetbeat/dashboard: error loading /tmp/tmp716928970/beats-dashboards-5.1.1/packetbeat/dashboard/Packetbeat-Cassandra.json: fail to read /tmp/tmp716928970/beats-dashboards-5.1.1/packetbeat/visualization/Cassandra:-ResponseKeyspace.json. Error: open /tmp/tmp716928970/beats-dashboards-5.1.1/packetbeat/visualization/Cassandra:-ResponseKeyspace.json: no such file or directory

For confirmed bugs, please report:
- Version:  5.1.1
- Operating System:  CentOS 7.3
- Steps to Reproduce:   download packetbeat rpm and run import

**Comment by ruflin** [comment]
Thanks for reporting the the issue. I assume this is a duplicate of https://github.com/elastic/beats/issues/3140 This should be already be fixed in the next release.

**Comment by kofemann** [comment]
ah, did not notice that it was already fixed. My apologies for the noise.
