### ISSUE TITLE
[Metricbeat] [AWS Fargate] Include 'DesiredStatus' and 'KnownStatus' fields with module/agent integration

### ISSUE THREAD

**Issue by stephenshepperd** [elastic/beats#32077]
Looking to bring in the `KnownStatus` and `DesiredStatus` fields with the AWS Fargate module as well as Elastic Agent Integration.

A customer of ours is looking to be able to query via Elasticsearch and create reports in Kibana focusing on the number of tasks that fall under a specific status bucket at any given time. They are provided this in the AWS console and would like to create this within Kiabana as well so they can report on it. Below is a screenshot of what they see in AWS and what they are looking to replicate in Kibana.

![image](https://user-images.githubusercontent.com/75761987/175361960-2bccb61a-2503-4e95-921e-19cd7eea3cbb.png)

**Comment by girodav** [comment]
Related issue in integrations: https://github.com/elastic/integrations/issues/3576
