### ISSUE TITLE
Benchmark the shipper output's conversion from publisher.Event

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#32081]
When beats are run under agent, they will soon be able to use the the new Elastic [agent data shipper](https://github.com/elastic/elastic-agent-shipper/issues/3). Events are sent to the shipper using the shipper gRPC output which involves conversion from `publisher.Event` to the shipper event format.

https://github.com/elastic/beats/blob/ef6096f24629ba08d3f11b6607b831941e228e7a/libbeat/outputs/shipper/shipper.go#L240-L243

Write a set of Go benchmarks for this conversion and attempt to minimize the the overhead of this conversion process. This conversion will be directly in the data path of every beat and we should be careful to avoid introducing performance regressions when using the shipper. At a minimum the benchmarks should help developers avoid making the current performance worse as the protocol evolves.

**Comment by jlind23** [comment]
@cmacknz any reason why you added the 8.5-candidate label here?

**Comment by cmacknz** [comment]
Removed it, it's already in 8.4.
