### ISSUE TITLE
[Heartbeat] Better defaults for browser concurrency

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#32082]
When running browser monitors we should automatically limit the number of concurrent browser monitors based on available system memory, requiring 750MiB free per monitor. 

This should limit problems when running monitors via fleet, where concurrently running monitors can quickly trigger an OOM.

See also #23687 .

**Comment by andrewvc** [comment]
Looking at docker on my system `/sys/fs/cgroup/memory/memory.limit_in_bytes` does seem to set the right amount. 

I propose that we:

1. Check for this file, and set our limit based on 1.5GiB per monitor
2. If not present default to 2 monitors concurrently and warn about this.

Any objection?

**Comment by emilioalvap** [comment]
Not an objection but adding an example as to why I'm wary of this feature.

- `/sys/fs/cgroup/memory/memory.limit_in_bytes` is only available for `cgroup v1`, if the kernel is using `cgroup v2`, the correct file to check would be  `/sys/fs/cgroup/memory.max`. And we'd need to compute available memory as cgroups can be shared, in theory. 

For reference, this tool implements a similar check: https://github.com/freeipa/freeipa/blob/3237ade3d2df20c3aeba4405f46a45a2130fbc7e/ipaserver/install/installutils.py#L1084

**Comment by lucasfcosta** [comment]
I've just tested this PR by:

1. Creating 12 inline browser monitors in my Heartbeat config
2. Starting Heartbeat itself
3. Check that there were only 2 monitors as child processes of Heartbeat
    ![Screenshot 2022-08-04 at 12 51 40](https://user-images.githubusercontent.com/6868147/182840690-480b7771-becd-4016-8112-b15aaeadc82c.png)
4. Change the `heartbeat.jobs.browser.limit` setting to `4`
5. Check that there were actually 4 child processes
    ![Screenshot 2022-08-04 at 12 53 27](https://user-images.githubusercontent.com/6868147/182840680-c70dac2c-7b85-4d94-b684-904a5591f39c.png)
