### ISSUE TITLE
Enhance the GenericSQL module to support below mentioned features and resolve below mentioned issues

### ISSUE THREAD

**Issue by agithomas** [elastic/beats#32089]
Enhance the GenericSQL module to support below mentioned features and resolve below mentioned issues

- [x] Create setup for the development
- [x] Connection string for Oracle does not handle special characters properly
- [x] Modify the driver used for oracle connectivity
- [x] Integration testing not available for GenericSQL Oracle integration
- [x] System testing for GenericSQL oracle is not adequate
- [x] Perform integration testing for other database flavours (MySQL and Postgres are used as sample) supported by Generic SQL
- [x] Perform team review
- [x] Improve the documentation

**Comment by agithomas** [comment]
https://docs.google.com/document/d/1Rem6Jkn2M1AQGQibJKWxoLMcnAlqTXad2Z6PLlYdjQg/edit#heading=h.3x1b1b24zocl

**Comment by rameshelastic** [comment]
@agithomas is this good to be closed?

**Comment by agithomas** [comment]
> @agithomas is this good to be closed?

This PR is pending review.  Review of this PR & review feedback fix (if any ) will be part of 8.6
