### ISSUE TITLE
AWS module cloudwatch metricset collecting RDS metrics with delay

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#32098]
With 8.1.3 Metricbeat, user sees the metrics were polled every 6-7 minutes and Kibana discover and Dashboards were updated after another 20-30 minutes after data ingestion. 
But same configuration using 7.17.1, everything works(no delay).

Config:
```
- module: aws
period: 5m
metricsets:
- cloudwatch
latency: 15m
metrics:
- namespace: AWS/RDS
resource_type: rds
statistic: ["Average"]
```

**Comment by girodav** [comment]
I tried to reproduce the issue with metricbeat 8.1.3 and the following configuration 

```
- module: aws
period: 5m
metricsets:
- cloudwatch
latency: 15m
metrics:
- namespace: AWS/RDS
resource_type: rds
statistic: ["Average"]
```
but the metrics were published every 5 minutes as expected (see example screenshot below). I also didn't encounter any particular delays in having the data available in Kibana.

![Screenshot 2022-07-07 at 10 24 28](https://user-images.githubusercontent.com/1390902/177741131-f44802ba-7a83-485d-bbd0-f00b5b41c4dd.png)
