### ISSUE TITLE
community beats: how to extend "make clean" ?

### ISSUE THREAD

**Issue by cyrilleverrier** [elastic/beats#3212]
### Problem

`clean` Makefile rule is defined as follow in `libbeats/scripts/Makefile`

```
.PHONY: clean
clean:
	rm -rf build ${BEATNAME} ${BEATNAME}.test ...
```

And this rule is used as a dependency for `testsuite` rule

If I want to extend `clean` rule in my Makefile:

```
clean: protoclean
	rm -Rf static/a_static.go
````

Then running `make clean` yields the following warning:
```
Makefile:81: warning: overriding recipe for target 'clean'
vendor/github.com/elastic/beats/libbeat/scripts/Makefile:115: warning: ignoring old recipe for target 'clean'
```

### Potential fix

`clean` is defined with the **Double-Colon Rules** syntax:
https://www.gnu.org/software/make/manual/html_node/Double_002dColon.html

```
clean::
	rm -rf build ${BEATNAME} ${BEATNAME}.test ...
```
I don't know `make` enough to see if there are any potential drawbacks with using double-colon rule for `clean`. I guess the order of execution does not really matter for a rule such as `clean`

**Comment by ruflin** [comment]
Interesting, I was not even aware of the double colon feature. Our current approach for such cases was creating a convention. In the case of `update`, it depends on an `collect` rule which each beat must implement. There it makes sense as `collect` must be run before `update`. For clean I can see that the order should not matter. 

As far as I understand the docs, both targets would have to be called `clean::` and when running make both are executed, but the order is not fixed. +1 on this if it works as expected :-)

**Comment by cyrilleverrier** [comment]
> As far as I understand the docs, both targets would have to be called clean:: and when running make both are executed, but the order is not fixed. +1 on this if it works as expected :-)

What you described is how it works when I tested against GNU Make 4.1.
- The community beat may or may not have the double colon `clean::`.
- The order is unspecified

If the single colon `make clean:` is used wrongly, the following error is outputted:
`
make clean
Makefile:80: *** target file 'clean' has both : and :: entries.  Stop.
`

If you aggree, I can open a PR.

**Comment by ruflin** [comment]
Fully agree to use this feature. I could also need this already today in metricbeat :-)

**Comment by cyrilleverrier** [comment]
See PR #3255

**Comment by cyrilleverrier** [comment]
PR #3255 has been merged to master.
