### ISSUE TITLE
[Heartbeat] Install `stack_release` tag of synthetics, not any-old release

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#32142]
The synthetics agent is released on a separate schedule from the regular stack. However, the beats/elastic agent build process pulls the latest synthetics agent into the docker image at build time. A release prior to the final BC risks pulling in a new release that just doesn't get the bake time most releases get in the FF process. We would appropriately label a release around FF and keep it frozen till later.

We'll need to modify the docker template to use this tag instead of latest.

**Comment by paulb-elastic** [comment]
@andrewvc as discussed, closing this as covered in https://github.com/elastic/beats/issues/31732
