### ISSUE TITLE
Use default elasticsearch X-Pack credentials when importing dashboards

### ISSUE THREAD

**Issue by dadoonet** [elastic/beats#3219]
When using beats with a default secured elasticsearch cluster with X-Pack, it could be nice to automatically run `import_dashboards` with `-user elastic -pass changeme`. So people will have a better OOTB experience.

Even if elasticsearch does not have x-pack installed, I think that passing those values by default won't cause any trouble.

**Comment by andrewkroh** [comment]
This is the behavior in 6.x. The `setup.kibana` credentials default to the `output.elasticsearch` values.

https://www.elastic.co/guide/en/beats/metricbeat/6.4/setup-kibana-endpoint.html#_literal_setup_kibana_username_literal
