### ISSUE TITLE
filebeat ilm option don't work 

### ISSUE THREAD

**Issue by busishe** [elastic/beats#32193]
more details:
i edit filebeat.yml set "setup.ilm.policy_name" to my own test policy created by kibana.

filebeat log shows the option worked.
{"log.level":"info","@timestamp":"2022-07-04T02:51:11.473Z","log.logger":"index-management.ilm","log.origin":{"file.name":"ilm/std.go","file.line":118},**"message":"ILM policy my-1day-test exists already."**,"service.name":"filebeat","ecs.version":"1.6.0"}

i use kibana to see es index details
however, the ilm policy don't setup to the index correctly.

**"lifecycle": { "name": ""**, "parse_origination_date": "false", "step": { "wait_time_threshold": "12h" }, "indexing_complete": "false", "rollover_alias": "", "origination_date": "-1" },

**Comment by mtojek** [comment]
Please go with the Discuss forum first. Once we confirm it's a bug, we will open an issue. Thanks.
