### ISSUE TITLE
The metricbeat beat module mappings for libbeat.config.module stats use shorts instead of longs

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#32211]
The metrics defined in libbeat for monitoring module configuration restarts are int64 counters:

https://github.com/elastic/beats/blob/d9e77c6ec0daeb528df8c8af750634f4cbe148d4/libbeat/cfgfile/reload.go#L51-L55

The Elasticsearch mappings appear to be defined as `short` (see [documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-beat.html#_libbeat)), causing issues when the counters overflow the 16 bit range of a short:

```
- failed to parse field [beat.stats.libbeat.config.stops] of type [short] in document with id 'xyGPYYEBHTtIsttEOY6O'.
- Preview of field's value: '7713579'
- reason: Numeric value (7713579) out of range of Java short[\\n](file://n/) at [Source: (byte[])
- failed to parse field [beat.stats.libbeat.config.starts] of type [short] in document with id '-SGPYYEBHTtIsttEQJAo'.
- Preview of field's value: '91453'
- reason: Numeric value (91453) out of range of Java short[\\n](file://n/) at [Source: (byte[])
```

**Comment by matschaffer** [comment]
Looks like these are the templates which need updating https://github.com/elastic/elasticsearch/blob/51fa9e3a5ca42636f2671a831be3a419ea5aa4e9/x-pack/plugin/core/src/main/resources/monitoring-beats-mb.json#L737-L745

**Comment by matschaffer** [comment]
The corresponding internal collection template has it correct https://github.com/elastic/elasticsearch/blob/51fa9e3a5ca42636f2671a831be3a419ea5aa4e9/x-pack/plugin/core/src/main/resources/monitoring-beats.json#L746-L767

**Comment by crespocarlos** [comment]
According to the documentation, `reloads` field is also missing from the map, am I right?
