### ISSUE TITLE
Make Beats documentation easier to maintain by reducing dependencies

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#32212]
**Describe the enhancement:**

The Beats documentation makes extensive use of conditional coding and shared files to avoid duplicating source content in multiple places.  This strategy saved us a lot of time in the beginning when the Beats were changing rapidly, but it introduced dependencies that make it very easy to break the doc build.  A change in one of the shared files can easily break the doc build for all of the Beats. Also because the source content lives in many shared files, it's more difficult for contributors to make simple changes to the documentation because the content structure is harder to understand. Plus the Edit link in the published docs doesn't work for included files, making it harder to contribute changes that way.

To solve this problem, we should:

* Re-evaluate all the places where we pull in shared content.
* In places where we can reduce complexity by duplicating content, replace the includes with the text. For example, instead of using includes to pull in small snippets of text, we should provide the text directly. 
* In places where we want to maintain a single source of truth (for example, libbeat settings), clean up conditional coding to remove conditions that are no longer valid (such as the conditions added for APM).
* Organize the content in the libbeat docs directory so that it's clear which files are shared.
* Document the single sourcing strategy and other idiosyncrasies.

***Alternate approach***

The fix I've described here is the simplest and fastest way to reduce complexity. A better approach might be to reduce duplication by putting all the Beats content into a single book, eliminating the need for extensive content reuse. However this approach would take more time to implement and require re-architecting the content, which probably isn't worth the effort since we are moving to next docs.

**Describe a specific use case for the enhancement or feature:**

Reducing dependencies and simplifying the source file structure will make it easier for contributors to maintain the content over time. It may also make it easier for us to migrate the content to next docs in the future.

**Comment by dedemorton** [comment]
@jlind23 I'm especially interested in your input here. Doing some clean up work will make the transition easier.

**Comment by jlind23** [comment]
@dedemorton having a single doc entry point for our ingest experience overall (Beats/Elastic Agent/ Logstash) would be the best long term approach.
For now removing links and duplicate would be a good first step as you stated in your items list.
Thus, we should have separate docs Standalone beats and Elastic Agent (Including Elastic Agent Libs, Elastic Agent Shipper, Fleet server, Elastic Agent inputs). Does it make sens?

**Comment by dedemorton** [comment]
Looking at this issue again, I think we should not spend time on this until we know what the migration path to next docs will look like. If we end up going from html to markdown, restructuring the Beats docs will be wasted effort.

**Comment by dedemorton** [comment]
Closing and will re-open if we decide to revisit this.
