### ISSUE TITLE
Heartbeat appends stream name in monitor.id for synthetics integration monitors

### ISSUE THREAD

**Issue by shahzad31** [elastic/beats#32224]
When a monitor is created using synthetics integration, it prefixes it with stream name, for example

`synthetics/browser-synthetics-59c507bf-bc0f-400a-973c-cc88e6568e80
`

we shouldn't append synthetics/browser-synthetics- to the monitorId.

**Comment by andrewvc** [comment]
Should only be set if `origin: ui` is set.

**Comment by vigneshshanmugam** [comment]
Post FF LGTM, Monitor ID is set correctly when origin field exists and when doesn't.
