### ISSUE TITLE
[http metricbeat module] Enhance the http metricbeat module to split a nested array into documents

### ISSUE THREAD

**Issue by yug-rajani** [elastic/beats#32246]
**Describe the enhancement:**

The current `http metricbeat module` has a provision of the flag `json.is_array` to split the response when the JSON response contains an array of JSON objects. However, there does not seem to be a provision to split the array when the array is nested inside the response (example response below, see array `nodes`). It would be great to have a flag such as `response.split` ([reference](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-httpjson.html#response-split)) which is present in `httpjson filebeat input` to perform the same task (particularly for this use case, it wouldn't be possible to leverage `httpjson` because it doesn't have provision of support for multiple hosts i.e. an array of hosts).

Sample Response:
```
{
    "name": "default",
    "nodes": [
        {
            "hostname": "172.17.0.2:8091",
            "systemStats": {
                "cpu_utilization_rate": 5.486725663716814,
                "cpu_stolen_rate": 0,
                "swap_total": 4126142464,
                "swap_used": 11866112,
                "mem_total": 8343732224,
                "mem_free": 2711244800,
                "mem_limit": 8343732224,
                "cpu_cores_available": 4,
                "allocstall": 28
            },
            "interestingStats": {
                "couch_docs_actual_disk_size": 129984427,
                "couch_views_actual_disk_size": 132147,
                "curr_items": 71177,
                "curr_items_tot": 71177,
                "ep_bg_fetched": 0,
                "couch_docs_data_size": 52834322,
                "mem_used": 138546320,
                "vb_replica_curr_items": 0,
                "vb_active_num_non_resident": 63288,
                "cmd_get": 0,
                "get_hits": 0,
                "ops": 0,
                "couch_spatial_disk_size": 0,
                "index_data_size": 50020,
                "index_disk_size": 45686968,
                "couch_spatial_data_size": 0,
                "couch_views_data_size": 132147
            },
            "uptime": "245240",
            "memoryTotal": 8343732224,
            "memoryFree": 2711244800,
            "mcdMemoryReserved": 6365,
            "mcdMemoryAllocated": 6365
        }
    ]
}
```

**Describe a specific use case for the enhancement or feature:**

To create an integration package for `Couchbase` (https://github.com/elastic/integrations/issues/613), the above sample response is for the `nodes` metrics. The given example contains just one object in the array, there can be multiple objects. Hence, there is a requirement to split the nodes, to ingest one array object per document into Elasticsearch.

**Workaround:**
In this specific case for `Couchbase`, we can leverage the `node` metricset of the [Couchbase metricbeat module](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-couchbase.html).

**Comment by yug-elastic** [comment]
CC: @lalit-satapathy @akshay-saraswat

**Comment by yug-elastic** [comment]
CC: @lalit-satapathy @ruflin
