### ISSUE TITLE
golang 1.18.3 Compilation normal, run error

### ISSUE THREAD

**Issue by blissnmx** [elastic/beats#32299]
Beats version : 7.11.2
golang version: 1.18.3
Team:blissnmx
hello, while Filebeat listening to the log ,the following error is emitted,causing the Filebeat process to stop ; Are there any plans to support the golang version?
`unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0xdfd0bf]

goroutine 93 [running]:
runtime.throw({0x272f212?, 0x0?})
        /opt/go1.18.3/src/runtime/panic.go:992 +0x71 fp=0xc0007b58c0 sp=0xc0007b5890 pc=0xdcb4f1
runtime.sigpanic()
        /opt/go1.18.3/src/runtime/signal_unix.go:825 +0x305 fp=0xc0007b5910 sp=0xc0007b58c0 pc=0xde2045
aeshashbody()
        /opt/go1.18.3/src/runtime/asm_amd64.s:1343 +0x39f fp=0xc0007b5918 sp=0xc0007b5910 pc=0xdfd0bf
runtime.mapiternext(0xc00005b4c0)
        /opt/go1.18.3/src/runtime/map.go:934 +0x2cb fp=0xc0007b5988 sp=0xc0007b5918 pc=0xda422b
runtime.mapiterinit(0xda1825?, 0x0?, 0xd0?)
        /opt/go1.18.3/src/runtime/map.go:861 +0x228 fp=0xc0007b59a8 sp=0xc0007b5988 pc=0xda3f08
reflect.mapiterinit(0xc0007b5a98?, 0x7fc0adae1318?, 0xd0?)
        /opt/go1.18.3/src/runtime/map.go:1373 +0x19 fp=0xc0007b59d0 sp=0xc0007b59a8 pc=0xdf8c39
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
        /root/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:112
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc000116870, 0xc0005a0128, 0xc0003e0840)
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_map.go:291 +0x225 fp=0xc0007b5b40 sp=0xc0007b59d0 pc=0x16e9265
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc0002219a0?, 0x0?, 0x0?)
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_optional.go:70 +0xa4 fp=0xc0007b5b90 sp=0xc0007b5b40 pc=0x16ee5c4
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0004f7830, 0xc0005a0128, 0xc0001161e0?)
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:219 +0x82 fp=0xc0007b5bc8 sp=0xc0007b5b90 pc=0x16e1642
github.com/json-iterator/go.(*Stream).WriteVal(0xc0003e0840, {0x264b200, 0xc0005a0128})
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:98 +0x158 fp=0xc0007b5c38 sp=0xc0007b5bc8 pc=0x16e0958`

**Comment by cmacknz** [comment]
I don't actually see any Filebeat code in the stack trace provided here, just [`json-iterator`](https://github.com/json-iterator/go)
