### ISSUE TITLE
[7.17] Filebeat is not connecting to Elasticsearch

### ISSUE THREAD

**Issue by liza-mae** [elastic/beats#32311]
For confirmed bugs, please report:
- Version: 7.17
- Operating System: Linux 
- Discuss Forum URL:
- Steps to Reproduce: 

Install Elasticsearch and Filebeat
Start Elasticsearch
Start Filebeat, expect it connects to Elasticsearch, but it does not and there are no errors present in the logs
I though it might be a configuration issue, as this started to fail recently, but I am not sure.

Started failing ```July 8```, has something changed in 7.17 that needs to be updated in the automation? or could this be a bug?

**Comment by jlind23** [comment]
@liza-mae would you please be able to start a discuss thread in order to have a full analysis run on this?

**Comment by liza-mae** [comment]
Discuss was not appropriate for this, as it was a snapshot build not yet released and running in CI.. I was trying to determine what changed since no errors were found in the logs.  

FYI...In any case, something was back ported with in the last day that fixed the issue. 

![Screenshot from 2022-07-12 10-04-01](https://user-images.githubusercontent.com/23424008/178540137-f9fd6d2d-a78e-42e5-8fee-eb80b901e375.png)
