### ISSUE TITLE
Make the shipper output to acknowledge batches based on `PersistedIndex` not `AcceptedCount`

### ISSUE THREAD

**Issue by rdner** [elastic/beats#32329]
**Describe the enhancement:**

Currently, [the shipper is acknowledging](https://github.com/elastic/beats/blob/06bf5dafec2de3ef0d3d858bd0f84cd7864b441d/libbeat/outputs/shipper/shipper.go#L175-L178) the event batch based on [`AcceptedCount`](https://github.com/elastic/elastic-agent-shipper-client/blob/de07abfef00ae4e1cd5012a1ff216d3c511fe3c5/api/messages/publish.proto#L68-L71) coming from the shipper as a part of the `PublishReply`.

This is unsafe because `AcceptedCount` does not mean that the actual final output (e.g. Elasticsearch) acknowledged these events from the Shipper's queue, it just means that the shipper put it in its own queue for processing. So, the data can be lost if the shipper process dies.

To fix this we need to use [`PersistedIndex`](https://github.com/elastic/elastic-agent-shipper-client/blob/de07abfef00ae4e1cd5012a1ff216d3c511fe3c5/api/messages/publish.proto#L80-L82) from `PublishReply` or a separate [`PersistedIndex` endpoint](https://github.com/elastic/elastic-agent-shipper-client/blob/de07abfef00ae4e1cd5012a1ff216d3c511fe3c5/api/shipper.proto#L29-L30) to acknowledge the events.

**Comment by cmacknz** [comment]
The primary use case we need to support is ensuring inputs like filebeat only update their persistent registry when events have been accepted by the output.

Filebeat's events should only be acknowledged based on the shipper's persisted index. Ideally we can create test cases proving that acknowledgements work correctly when either filebeat or the shipper restarts unexpectedly.
