### ISSUE TITLE
Filebeat httpjson docs need corrections

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#32321]
From https://www.elastic.co/guide/en/beats/filebeat/8.2/filebeat-input-httpjson.html#_chain_step_request

<img width="843" alt="Screen Shot 2022-07-12 at 10 26 01" src="https://user-images.githubusercontent.com/15056957/178448815-dbdf638e-6198-4f3e-8fe4-2bead5ac63a2.png">

**Comment by adriansr** [comment]
I'm also unsure about the "response" hyperlinks in some examples, shouldn't we duplicate the snippets instead of adding a link to existing ones so that it's easier to understand?

**Comment by ebeahan** [comment]
Appears resolved in https://github.com/elastic/beats/pull/32975
