### ISSUE TITLE
Use heuristics to avoid data duplication when filestream inputs use non-unique IDs

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#32335]
Each filestream input created in a filebeat or Elastic agent instance must have a unique ID to allow the input to track the files it is responsible for in its persistent registry. Without unique IDs filestream inputs will track files they were not associated with leading to data duplication.

The best way to solve this problem is to make the `id` parameter a required field in the filestream configuration. This would be a breaking change causing all filebeat instances configured with filestream inputs without unique IDs to refuse to start. The current thinking is that unexpected data duplication that can be mitigated with a simple configuration change is preferable to creating a release that breaks a user's filebeat deployment.

Given our strong preference to avoid a breaking change one option to minimize the chance of data duplication would be to use a heuristic based on the filestream configuration to generate a suitable ID.

Consider two simple filestream inputs:

```yml
- type: filestream
  enabled: true
  paths:
    - /var/log/*.log
    - /logs/*.log
 
- type: filestream
  enabled: true
  paths:
    - /var/tests/test*.log
```

The two have a non-overlapping set of paths. We could generate a UUID and associate it with the list of currently configured paths in a persistent file, using the UUID as the ID. 

At startup filebeat could associate the configured filestream instances to the existing set of UUIDs based on the similarity of the paths. In most cases where the configuration was not edited the lists would match exactly. 

To handle cases where the paths were edited we could use a similarity scoring algorithm to pick the closest match. For string matching there are some examples at https://github.com/adrg/strutil. For more complex cases, or if we wanted to match against the entire configuration instead of just the paths, we could consider calculating [cosine similarity](https://en.wikipedia.org/wiki/Cosine_similarity) or a similar similarity metric that is commonly available in numerical or machine learning packages.

**Comment by belimawr** [comment]
Adding a few more details regarding some usecases

> The two have a non-overlapping set of paths.

Unfortunately we cannot count on that, one of the filestream features is that different input instances can harvest the same file without interfering with each other, there is a very good example on the second snippet from this comment: https://github.com/elastic/integrations/pull/3672#issuecomment-1181403413

> At startup filebeat could associate the configured filestream instances to the existing set of UUIDs based on the similarity of the paths. In most cases where the configuration was not edited the lists would match exactly.

That needs to be at the input initialisation, inputs can be started dynamically via Elastic-Agent, autodiscovery, watching configuration file changes, etc.
