### ISSUE TITLE
[Heartbeat] Add timeout to browser monitors in HB side

### ISSUE THREAD

**Issue by emilioalvap** [elastic/beats#32388]
**Describe the enhancement:**

Add a configurable timeout for synthetic monitors, in case `node` process goes unresponsive. This timeout will be used from HB to kill synthetic monitor's in case `node` goes unresponsive, as seen in #32387. HB will wait for `node` process to exit and will proceed to kill it with `SIGKILL` if it doesn't do it before timeout is reached.

Additionaly, a sensible default should be used so this timeout can kick in before container eviction timeout inside synthetics service. @andrewc suggested ~14 min.

**ACs:**

- Timeout is configurable from `heartbeat.yml`.
- Test run is marked as failed if timeout is reached and appropriate summary is included in the monitor run.

**Comment by vigneshshanmugam** [comment]
POST FF testing LGTM 
<img width="2280" alt="Screen Shot 2022-08-01 at 11 42 40 AM" src="https://user-images.githubusercontent.com/3902525/182221016-4845acc1-33ee-4d5d-89e1-1e866893d2d9.png">
