### ISSUE TITLE
cisco_amp5.ndjson.log  There is Trojan virus in it 

### ISSUE THREAD

**Issue by spy666666** [elastic/beats#32385]
## Flaky Test

* **Test Name:** Name of the failing test.
* **Link:** Link to file/line number in github.
* **Branch:** Git branch the test was seen in. If a PR, the branch the PR was based off.
* **Artifact Link:** If available, attach the generated zip artifact associated with the stack trace for this failure.
* **Notes:** Additional details about the test. e.g. theory as to failure cause

### Stack Trace

```
paste stack trace here
```
Scan beats/x-pack/filebeat/moudule/cisco/amp/test/cisco_amp5.ndjson.log  with Kaspersky , There is Trojan virus in it .
DetectName=HEUR:Trojan.PowerShell.Generic
DetectType=Trojware
May I ask how to solve this problem

**Comment by andrewkroh** [comment]
cisco_amp5.ndjson.log is log sample from Cisco AMP, software that does advanced malware protection, and it contains logs about malware it detected. For example, the logs contains base64 encoding PowerShell scripts that it detected. But this is a test file, that’s the point of it. This file does not ship with our releases, and it is for testing purposes only.

**Comment by andrewkroh** [comment]
>  May I ask how to solve this problem

Since this file is not included in releases, did you git clone this repo? I would whitelist the beats dir that you checked out or this test file.

**Comment by spy666666** [comment]
The source code I download through https://codeload.github.com/elastic/beats/zip/refs/tags/v7.15.2 contains the beats/x-pack/filebeat/moudule/cisco/amp/test/cisco_amp5.ndjson.log file. As a result,the source code of the project contains Trojan horses.Can beats modify the content of the test file to ensure that the file does not contain Trojan horses?



---Original---
From: "Andrew ***@***.***&gt;
Date: Wed, Jul 20, 2022 23:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [elastic/beats] cisco_amp5.ndjson.log  There is Trojan virus init  (Issue #32385)




  
May I ask how to solve this problem
  
Since this file is not included in releases, did you git clone this repo? I would whitelist the beats dir that you checked out or this test file.
