### ISSUE TITLE
error handling for cloudwatch on getLogEventsFromCloudWatch

### ISSUE THREAD

**Issue by aspacca** [elastic/beats#32436]
https://github.com/elastic/beats/blob/master/x-pack/filebeat/input/awscloudwatch/cloudwatch.go#L68-L71

whenever there will be an error from getLogEventsFromCloudWatch it will be reported always as RequestCanceledError, even if it's another type of error, since we shadow `err` on https://github.com/elastic/beats/blob/master/x-pack/filebeat/input/awscloudwatch/cloudwatch.go#L67

**Comment by gpop63** [comment]
This issue seems partially resolved by #31224 in the `main` branch: https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awscloudwatch/cloudwatch.go#L63

However, the first argument in `errors.As` should be the error returned from the function `getLogEventsFromCloudWatch`.
