### ISSUE TITLE
Visualization of cumulative metrics in grafana

### ISSUE THREAD

**Issue by Elufimov** [elastic/beats#3243]
Hi! Right now postgres module makes query to `pg_stat_database` and convert result to events for each database. There is no transformation of query result. However some of metrics in `pg_stat_database` are cumulative. For example transactions and rows. It would be good to have these metrics like difference between the past and the current value.

**Comment by kpa6uk** [comment]
I'd like to have these feature too.

**Comment by ruflin** [comment]
@Elufimov Is this a similar request to this one? https://github.com/elastic/beats/issues/2783

**Comment by Elufimov** [comment]
Yes, very similar. But my problem lays only in visualization matters. I found the answer in this comment https://github.com/elastic/beats/issues/2783#issuecomment-262365033 This is an example
![3b1807f0715a51e531273a149f8c38c7](https://cloud.githubusercontent.com/assets/423130/21711974/5a6eec96-d40b-11e6-95fd-7ebfffcac62b.png)

**Comment by Elufimov** [comment]
I renamed issue for everyone who will have similar problem. Thx for your comment @ruflin it was very useful!
