### ISSUE TITLE
[Heartbeat] Support OPTIONS for lightweight cehcks

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#32457]
Per [this forum post](https://discuss.elastic.co/t/heartbeat-http-method-options/310280) it would be nice if we supported the HTTP Options verb for lightweight HTTP checks.

**Comment by lowryxiao** [comment]
I'd like to perform the change after read the original forum post.
Actually, I've done the code change since it's a very small change and I'm looking forward how to test and verify this change in the beats testsuit.
Will keep you posted.
