### ISSUE TITLE
Panic from concurrent map write after system metrics package update

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#32467]
Introduced by https://github.com/elastic/beats/pull/32336 which incorporated the changes from https://github.com/elastic/elastic-agent-system-metrics/pull/40.

We have one confirmed case of APM server crashing with a panic from a concurrent map write when it is run under agent with monitoring enabled.

Stack trace:

> {"log.level":"error","@timestamp":"2022-07-22T06:24:18.918Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"apm-server stderr: \"fatal error: concurrent map writes\\n\"","agent.console.name":"apm-server","agent.console.type":"stderr","ecs.version":"1.6.0"}
> {"log.level":"error","@timestamp":"2022-07-22T06:24:18.922Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"apm-server stderr: \"\\ngoroutine 47 [running]:\\nruntime.throw({0xaaaad510411d, 0x15})\\n\\truntime/panic.go:1198 +0x54 fp=0x400275eb10 sp=0x400275eae0 pc=0xaaaad3387814\\nruntime.mapassign(0xaaaad6a97640, 0x40004a8db0, 0x400275ed88)\\n\\truntime/map.go:585 +0x4d0 fp=0x400275eb90 sp=0x400275eb10 pc=0xaaaad335e7a0\\ngithub.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).GetSelf(0x40002024b0)\\n\\tgithub.com/elastic/elastic-agent-system-metrics@v0.4.3/metric/system/process/process.go:137 +0x1d0 fp=0x400275f140 sp=0x400275eb90 pc=0xaaaad43fecf0\\ngithub.com/elastic/elastic-agent-system-metrics/report.InstanceCPUReporter.func1(0x1, {0xaaaad6ed7598, 0x4000d2a000})\\n\\tgithub.com/elastic/elastic-agent-system-metrics@v0.4.3/report/report.go:68 +0x98 fp=0x400275f6f0 sp=0x400275f140 pc=0xaaaad4405668\\ngithub.com/elastic/elastic-agent-libs/monitoring.(*Func).Visit(0x4000011038, 0x1, {0xaaaad6ed7598, 0x4000d2a000})\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.9/monitoring/metrics.go:221 +0x44 fp=0x400275f720 sp=0x400275f6f0 pc=0xaaaad383a2a4\\ngithub.com/elastic/elastic-agent-libs/monitoring.(*Registry).doVisit(0x40005a0cc0, 0x1, {0xaaaad6ed7598, 0x4000d2a000})\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.9/monitoring/registry.go:83 +0x1bc fp=0x400275f7f0 sp=0x400275f720 pc=0xaaaad383b82c\\ngithub.com/elastic/elastic-agent-libs/monitoring.(*Registry).Visit(0x40005a0cc0, 0x1, {0xaaaad6ed7598, 0x4000d2a000})\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.9/monitoring/registry.go:65 +0x40 fp=0x400275f820 sp=0x400275f7f0 pc=0xaaaad383b650\\ngithub.com/elastic/elastic-agent-libs/monitoring.(*Registry).doVisit(0x40000ac700, 0x1, {0xaaaad6ed7598, 0x4000d2a000})\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.9/monitoring/registry.go:83 +0x1bc fp=0x400275f8f0 sp=0x400275f820 pc=0xaaaad383b82c\\ngithub.com/elastic/elastic-agent-libs/monitoring.(*Registry).Visit(...)\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.9/monitoring/registry.go:65\\ngithub.com/elastic/elastic-agent-libs/monitoring.CollectStructSnapshot(0x40000ac700, 0x1, 0x0)\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.9/monitoring/snapshot.go:89 +0xd4 fp=0x400275f9c0 sp=0x400275f8f0 pc=0xaaaad383cda4\\ngithub.com/elastic/beats/v7/libbeat/api.makeAPIHandler.func1({0xaaaad6e8c810, 0x400017b260}, 0x4000f1a300)\\n\\tgithub.com/elastic/beats/v7@v7.0.0-alpha2.0.20220722011543-0c1f1a945d3a/libbeat/api/routes.go:74 +0x118 fp=0x400275fa20 sp=0x400275f9c0 pc=0xaaaad426fab8\\nnet/http.HandlerFunc.ServeHTTP(0x400007b5b0, {0xaaaad6e8c810, 0x400017b260}, 0x4000f1a300)\\n\\tnet/http/server.go:2047 +0x40 fp=0x400275fa50 sp=0x400275fa20 pc=0xaaaad370f560\\nnet/http.(*ServeMux).ServeHTTP(0x40005a1980, {0xaaaad6e8c810, 0x400017b260}, 0x4000f1a300)\\n\\tnet/http/server.go:2425 +0x18c fp=0x400275fab0 sp=0x400275fa50 pc=0xaaaad3710ecc\\nnet/http.serverHandler.ServeHTTP({0x400017a000}\"","agent.console.name":"apm-server","agent.console.type":"stderr","ecs.version":"1.6.0"}

**Comment by LeeDr** [comment]
Does this meet any of these guidelines for a blocker?  Is there a work-around?  How many users would this impact?

Here are some rough guidelines for identifying bugs that block releases:

- The bug causes users to lose data.
- It causes a severe security issue that the Security team has approved.
- It impacts functionality used by a majority of the users.
- It's embarrassing. For example: users can't even start Logstash in its basic form.

**Comment by fearful-symmetry** [comment]
@LeeDr based on a quick 10-minute lookover of the bug, it's originating in beat's monitoring/reporting of its own resource usage, probably because the self-monitoring is the only thing that access a single instance of the process monitoring libs in multiple threads; I don't _think_ this issue is arising in user-facing metricsets.  That being said, it's a quick fix, and I should have a PR today.

**Comment by fearful-symmetry** [comment]
> The impact appears to be that any beat run in standalone mode or started by agent can crash unexpectedly based on a race condition when HTTP monitoring is enabled

I'm kind of surprised this causes a whole crash of the application. Metricbeat will catch panics of threads from metricsets, I would have assumed that monitoring did something similar, although I guess it's not too surprising that it doesn't.

**Comment by cmacknz** [comment]
@fearful-symmetry the error above is coming from inside APM server, not any of our own beats. Likely we need to update libbeat in APM server for this fix to take effect.

**Comment by cmacknz** [comment]
Is anyone from @elastic/apm-server available to help us evaluate the impact here and make sure we fix this in the correct place? CC @simitt @axw

**Comment by cmacknz** [comment]
The change was brought into API server with https://github.com/elastic/apm-server/pull/8612. We'll need a PR to update the beats dependency there and then ensure the APM server artifacts are staged for the DRA process to pick them up.

**Comment by cmacknz** [comment]
Cloudbeat is not affected, their [beats dependency in the 8.3](https://github.com/elastic/cloudbeat/blob/671464dfc963e59101076909d71c03baf630cbe4/go.mod#L62) branch is pinned to https://github.com/elastic/beats/commit/cab8871124af 
from June before this change was introduced on July 13 in main and July 14 in 8.3.

Agent is [pinned to v0.3.0](https://github.com/elastic/elastic-agent/blob/be3c48e98171548f61f7aa4de16e48d1a288cff7/go.mod#L17). Fleet server is [pinned to v0.3.0](https://github.com/elastic/fleet-server/blob/873a669fa2a09fb0643129a5f21c6340834db9b3/go.mod#L10). Both are unaffected as the change was introduced in [elastic-agent-system-metrics@v0.4.3](https://github.com/elastic/elastic-agent-system-metrics/releases/tag/v0.4.3).

**Comment by cmacknz** [comment]
To get the fastest and lowest risk resolution for 8.3.3 I am going to revert the offending change from beats. APM server has automation in place to update beats we can hopefully trigger to resolve the problem there quickly.

**Comment by cmacknz** [comment]
I opened https://github.com/elastic/beats/pull/32470 against main as the APM server automation appears to pick up changes from the beats main branch. The 8.3 backport PR will follow this one.

**Comment by cmacknz** [comment]
The Jenkins jobs to update APM server can be found at https://apm-ci.elastic.co/job/apm-server/job/update-beats-mbp. We should be able to manually trigger the one for 8.3 once the backport is merged.

**Comment by cmacknz** [comment]
https://github.com/elastic/dev/issues/2071#issuecomment-1192799064

We are going to downgrade the elastic-agent-system-metrics package in the affected repositories to resolve this for the 8.3 release. We will continue fixing the root cause of the problem separately.

**Comment by b0le** [comment]
@LeeDr @cmacknz @fearful-symmetry No pressure but we have hit this issue in production after upgrading to Elastic Stack 8.3.3 from 7.17.1. Out of 8 Elastic Agents we are running with APM integration enabled about half has encountered this issue within the first 2-4 hours after the upgrade. Worse yet there's not automatic restart of the APM server. Following the crash Elastic Agent does not reap the child APM server process by `wait`-in on it, leaving behind zombies.

In which version can we expect a fix and are there any workarounds in the mean time?

**Comment by cmacknz** [comment]
@b0le that is surprising, this specific problem should not occur in released versions of 8.3.3.

For beats and apm-server the package downgrade the fixes this problem is included in the 8.3.3 release commits:
- https://github.com/elastic/beats/commits/1755b5dd3127bf755ee39deb25a802438bdac620
- https://github.com/elastic/apm-server/commits/f39045c2366eefb537ebdc70125a1e8e6be0367c

This problem should be fixed in 8.3.3 from what I can see.

**Comment by LeeDr** [comment]
@fearful-symmetry I think the v8.3.0 label on this PR is incorrect and might confuse people.  I think this fix was in the 8.3.3 release?

**Comment by fearful-symmetry** [comment]
@LeeDr going through the version tags, the 8.3.3 release contains @cmacknz 's rollback to a previous version, so either this bug is older than we think, or it's a different but similar-looking bug.

**Comment by cmacknz** [comment]
I don't think this bug was ever released either, it would only have been affecting snapshot versions of 8.3.3.

Most likely this is an unrelated problem that requires more investigation.

**Comment by LeeDr** [comment]
Sorry, I think I commented in the wrong place.  I really don't care too much on the version label on the issue.  It's the version labels on the PRs that are important.  I'll comment instead on https://github.com/elastic/elastic-agent-system-metrics/pull/43#event-7058826751

**Comment by b0le** [comment]
@cmacknz @fearful-symmetry We are afraid that the release with the problematic elastic-agent-system-metrics v0.4.3 has somehow made it into the wild as we are seeing the following log lines with Elastic Agent 8.3.3, note the third error message with the stack trace which includes the string `elastic-agent-system-metrics@v0.4.3/metric/system/process/process.go:137`:

```
"apm-server stderr: \"fatal error: concurrent map writes\\n\""
"apm-server stderr: \"\\ngoroutine 382 [running]:\\nruntime.throw({0x559feefb4b73?, 0x0?})\\n\\truntime/panic.go\""
"apm-server stderr: \":992 +0x71 fp=0xc0020d14c0 sp=0xc0020d1490 pc=0x559fecffe011\\nruntime.mapassign(0xc0029ac3e6?, 0xa?, 0x559feef97562?)\\n\\truntime/map.go:595 +0x4d6 fp=0xc0020d1540 sp=0xc0020d14c0 pc=0x559fecfd5f36\\ngithub.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).GetSelf(_)\\n\\tgithub.com/elastic/elastic-agent-system-metrics@v0.4.3/metric/system/process/process.go:137 +0x239 fp=0xc0020d1ad0 sp=0xc0020d1540 pc=0x559fee1e9c99\\ngithub.com/elastic/elastic-agent-system-metrics/report.MemStatsReporter.func1(0x1, {0x559fefe57598, 0xc0027eaa80})\\n\\tgithub.com/elastic/elastic-agent-system-metrics@v0.4.3/report/report.go:\""
"apm-server stderr: \"52 +0x1e5 fp=0xc0020d36e8 sp=0xc0020d1ad0 pc=0x559fee1f2785\\ngithub.com/elastic/elastic-agent-libs/monitoring.(*Func).Visit(0xc00297d770?, 0x1c?, {0x559fefe57598?, 0xc0027eaa80?})\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.9/monitoring/metrics.go\""
"apm-server stderr: \":221 +0x2e fp=0xc0020d3710 sp=0xc0020d36e8 pc=0x559fed55b64e\\ngithub.com/elastic/elastic-agent-libs/monitoring.(*Registry).doVisit(0xc000361780, 0x1, {0x559fefe57598\""
"apm-server stderr: \", 0xc0027eaa80})\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.9/monitoring/registry.go:83 +0x1c3 fp=0xc0020d37f0 sp=0xc0020d3710 pc=0x559fed55d023\\ngithub.com/elastic/elastic-agent-libs/monitoring.(*Registry).Visit(0xc00297d880?, 0xa9\""
"apm-server stderr: \"?, {0x559fefe57598?, 0xc0027eaa80?})\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.9/monitoring/registry.go:65 +0x25 fp=0xc0020d3820 sp=0xc0020d37f0 pc=0x559fed55ce25\\ngithub.com/elastic/elastic-agent-libs/monitoring.(*Registry).doVisit(0xc00005c740, 0x1, {0x559fefe57598, 0xc0027eaa80\""
"apm-server stderr: \"})\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.9/monitoring/registry.go:83 +0x1c3 fp=0xc0020d3900 sp=0xc0020d3820 pc=0x559fed55d023\\ngithub.com/elastic/elastic-agent-libs/monitoring.(*Registry).Visit(...)\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.9/monitoring/registry.go:\""
"apm-server stderr: \"65\\ngithub.com/elastic/elastic-agent-libs/monitoring.CollectStructSnapshot(0xc00007e540?, 0xb0?, 0x0)\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.9/monitoring/snapshot.go:89 +\""
"apm-server stderr: \"0xcc fp=0xc0020d39c8 sp=0xc0020d3900 pc=0x559fed55ea4c\\ngithub.com/elastic/beats/v7/libbeat/api.makeAPIHandler.func1({0x559fefe4f0a8, 0xc0007530a0}\""
"apm-server stderr: \", 0xc002901600)\\n\\tgithub.com/elastic/beats/v7@v7.0.0-alpha2.0.20220722214259-1755b5dd3127/libbeat/api/routes.go:74 +0xde fp=0xc0020d3a20 sp=0xc0020d39c8 pc=\"
```

Full logs from one of the instances that has crashed are attached as [elastic-agent-diagnostics-2022-08-10T16-34-42Z-00-redacted.zip](https://github.com/elastic/beats/files/9312341/elastic-agent-diagnostics-2022-08-10T16-34-42Z-00-redacted.zip).

For any users encountering this: disabling Elastic Agent's metrics collection is a reliable workaround. We have not seen any crashes in the past 8 hours since disabling it.

**Comment by fearful-symmetry** [comment]
So, it looks like it did sneak into the 8.3.3 tag there during a bot's dependency update:

https://github.com/elastic/apm-server/blob/f39045c2366eefb537ebdc70125a1e8e6be0367c/go.mod#L85

However, the `8.3` and `8.4` branches currently have the correct version

**Comment by joshdover** [comment]
> For any users encountering this: disabling Elastic Agent's metrics collection is a reliable workaround. We have not seen any crashes in the past 8 hours since disabling it.

If this works, then my guess is the error only happens when APM's `/stats` endpoint is called. 

One problem is that in our Cloud service, our own internal monitoring likely calls this endpoint which we can't really disable. What I'm not sure about is whether or not this endpoint is only called when in standalone (legacy) APM mode or not since we don't run Agent monitoring directly on Cloud.

In my own cluster where APM is running in managed mode, it does seem that we're still collecting metrics, so I would suspect that this could be affecting all APM Server instances in Cloud. This makes me think we should move to release a new patch version to fix this. @cmacknz do you agree?

**Comment by cmacknz** [comment]
> So, it looks like it did sneak into the 8.3.3 tag there during a bot's dependency update:

What I think happened is that in the [automated apm-server PR](https://github.com/elastic/apm-server/pull/8694/files) that updated to the beats version with the [fix](https://github.com/elastic/beats/commit/fba8b8639d1f), it did not actually update the elastic-agent-system-metrics package transitive dependency.

You can see that https://github.com/elastic/apm-server/pull/8694 only updates go.sum and not go.mod. We would have needed to manually `go get github.com/elastic/elastic-agent-system-metrics@v0.4.2` in the `apm-server` repository. Seeing it now this the expected behaviour from the Go tooling in this case (prefer the highest version that satisfies the transitive dependency) but we trusted the automation here too much during a last might fix before a release.

> This makes me think we should move to release a new patch version to fix this. @cmacknz do you agree?

Yes, the impact of this is a race condition that will randomly cause APM server to panic. We should never have released this, the original issue was a blocker for 8.3.3.

**Comment by cmacknz** [comment]
The head of the 8.3 branch in apm-server is at https://github.com/elastic/elastic-agent-system-metrics/releases/tag/v0.4.4 which adds a mutex to the map in question to fix the problem. 

For beats we reverted to v0.4.2 in the 8.3 release which removes a bug fix for agent monitoring (CPU reporting as zero in the agent dashboard) that introduced the concurrency problem. v0.4.4 has both this agent CPU bug fix and the concurrency bug fix.

**Comment by cmacknz** [comment]
Given that there is a probable work around in [a comment above](https://github.com/elastic/beats/issues/32467#issuecomment-1212541627), we may not need an 8.3.4 release given that 8.4.0 is planned for a little more than a week from now.

> For any users encountering this: disabling Elastic Agent's metrics collection is a reliable workaround. We have not seen any crashes in the past 8 hours since disabling it.

**Comment by Mpdreamz** [comment]
I believe on ESS the user can not disable all metrics collection e.g the following is baked into the Integration Server docker container:

https://github.com/gcpagano/cloud/blob/master/scala-services/runner/src/main/scala/no/found/runner/allocation/stateless/ApmDockerContainer.scala#L285

**Comment by Mpdreamz** [comment]
Reopening this and assigning myself while we figure out if we need and can do an 8.3.4 release.
