### ISSUE TITLE
if http response content-type is text/html; charset=UTF-8 , response body chinese uncode error

### ISSUE THREAD

**Issue by blackhu** [elastic/beats#3250]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version: 
- Operating System: 
- Steps to Reproduce:

**Comment by tsg** [comment]
I'm guessing this is about Packetbeat? Can you add the details requested by the ticket template, please?
