### ISSUE TITLE
which version will support filebeat output to kafka 2.7 or newer version(kafka)

### ISSUE THREAD

**Issue by yang65** [elastic/beats#32532]
# Metricbeat Module / Dataset release checklist

This checklist is intended for Devs which create or update a module to make sure modules are consistent.

## Modules

For a metricset to go GA, the following criterias should be met:

* [ ] Supported versions are documented
* [ ] Supported operating systems are documented (if applicable)
* [ ] Integration tests exist
* [ ] System tests exist
* [ ] Automated checks that all fields are documented
* [ ] Documentation
* [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] Dashboards exists (if applicable)
* [ ] Kibana Home Tutorial (if applicable)
  * Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).

## Filebeat module

* [ ] Test log files exist for the grok patterns
* [ ] Generated output for at least 1 log file exists

## Metricbeat module

* [ ] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [ ] Test environment in Docker exist for integration tests

**Comment by belimawr** [comment]
Hey @yang65 I'm a bit confused by this issue you opened. The title and body don't seem to match.

Is it just about asking when support for Kafka >= 2.7 will be introduced?

We use GitHub to track feature requests and bug reports, please don't open issues to ask questions, for questions like that we use our Discuss forums: https://discuss.elastic.co/c/beats.

I'll close this issue for now.
