### ISSUE TITLE
Add HTTP Output

### ISSUE THREAD

**Issue by mr1716** [elastic/beats#32553]
**Describe the enhancement:**
Just like there is an HTTP Input for beats such as Filebeat, this request is to add an output HTTP endpoint.

**Describe a specific use case for the enhancement or feature:**
The usecase is where one wants to send the HTTP output to another service that isnt an existing output. This would expand the existing usecases for the beats platform because it would increase compatibility with other programs

**Comment by UcanInfosec** [comment]
If this were incorporated, I would implement beats!
