### ISSUE TITLE
beats/libbeat/scripts/generate_template.py does not create _types from -keys

### ISSUE THREAD

**Issue by blacktop** [elastic/beats#3262]
For confirmed bugs, please report:
- Version: master + @andrewkroh's pull request `ip` fix.
- Operating System: OSX
- Steps to Reproduce: 
```
make update
```

So I was able to figure out how to add more `sub-fields` except that the way that it works is it creates nested fields under the `_default` mapping.

I usually like to use document `_types` to pull apart.. well document types.  Is there a reason you have designed it this way?  I can see that you are going to start using the concept of modules.  For example an **nginx** filebeat module that I assume would create fields like this:

```
_index: filebeat-*
_type: filebeat
nginx.access.request.method: GET
```

To me it makes sense to have it be like:

```
_index: filebeat-*
_type: nginx-access
request.method: GET
```

I just think more deeply nested field names are harder to query?

Thoughts?

I will pose this to the forum also incase you don't believe this is an issue.

**Comment by blacktop** [comment]
Also create form entry here - https://discuss.elastic.co/t/how-to-add-other--types-to-the-etc-fields-yml-in-beats/70241/7?u=blacktop

**Comment by tsg** [comment]
We've discussed this at length when starting on the Metricbeat modules. For a bit of background, we know that document types tend to cause confusion among Elasticsearch users (many associate types with SQL tables, but they are just a simple extra field) and there are plans to deprecate and remove them from Elasticsearch on the medium term. So we wanted to minimize our usage of types.

While the current approach results in longer field names, which I agree tend to be more annoying, it's most efficient at avoiding name and type conflicts. Document types don't help with conflicts. We could split by default to multiple indices, but that comes with its own issues. Plus, name conflicts would still be problematic in Kibana, where everything meets in the end.

I'm closing for now, but happy to discuss further if you want, ideally on discuss / irc :).

**Comment by blacktop** [comment]
@tsg is there a beats irc chan?

**Comment by tsg** [comment]
There's #beats on freenode. Might be a little quiet at the moment due to the holiday.
