### ISSUE TITLE
Metricbeat pod not using current ServiceAccount tokens

### ISSUE THREAD

**Issue by ronak-ag** [elastic/beats#32638]
**Bug Description**

On k8s clusters running 1.21+ mounted service account tokens can be created with an expiry. I've started noticing metricbeat agents getting into states with errors like failed to set up sandbox container ...: Unauthorized.

BoundServiceAccountTokenVolume Kubernetes feature (graduated to stable in 1.22) improves security of service account tokens by requiring a one hour expiry time, over the previous default of no expiration. This means that metric-agent should refetch service account tokens periodically.

_Version Used_
metricbeat = 7.17.3

_How can you resolve the issue?_

To make the transition to time bound service account tokens easier, Kubernetes has updated the below official versions of client SDKs to automatically refetch tokens before the one hour expiration:

Go v0.15.7 and later
Python v12.0.0 and later
Java v9.0.0 and later
Javascript v0.10.3 and later
Ruby master branch
Haskell v0.3.0.0

**Comment by tetianakravchenko** [comment]
Hi @ronak-ag. In version 7.17 is already used older version than 0.15.7 - https://github.com/elastic/beats/blob/7.17/go.mod#L192-L194. Could you please try to update to the latest 7.17 version and verify if you still see the same error?

**Comment by tgeo-cambrian** [comment]
@ronak-ag did you manage to solve this?

exact same issue, AWS EKS 1.21 and metricbeat v7.10.2
`image: docker.elastic.co/beats/metricbeat:7.10.2`

this should not be an issue as https://github.com/elastic/beats/blob/aacf9ecd9c494aa0908f61fbca82c906b16562a8/go.mod#L186
`	k8s.io/client-go v0.18.3` already > than 0.15.7 which is the requirement

filebeat that is the same version does not have the same behaviour.
