### ISSUE TITLE
[HTTP JSON Chain Call] Need support for Pagination in Nested Chain Calls

### ISSUE THREAD

**Issue by vinit-elastic** [elastic/beats#32647]
**Describe the enhancement:**
This issue requests you to add pagination for nested chain calls(second and third call) in HTTP JSON input. In pagination, it will call every time only the first call, the second and third call did not happen in this pagination section. 

Moreover, Pagination and Chained calls work fine individually, but they fail when combined. 

While investigating, we saw that in the https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/httpjson/pagination.go#L141, they iterate the first request every time. In this function, we have to call chain requests in this function.

**Comment by jamiehynds** [comment]
The Trend Micro Vision One integration was originally blocked by this issue, but we were able to use a different API endpoint with Trend, to overcome the issue. Will close this out for now and re-open if we discover other integrations blocked by this.

**Comment by epixa** [comment]
Just marking this closed/not-resolved so it's clear that this change didn't actually happen.
