### ISSUE TITLE
Exiting: error loading config file: yaml: line 101: could not find expected ':'

### ISSUE THREAD

**Issue by OsMaster** [elastic/beats#32714]
Problem with winlogbeat

after editing the file with elastic cloud id and cloud id auth 

Exiting: error loading config file: yaml: line 101: could not find expected ':'

# =============================== Elastic Cloud ================================

# These settings simplify using Winlogbeat with the Elastic Cloud (https://cloud.elastic.co/).

# The cloud.id setting overwrites the `output.elasticsearch.hosts` and
# `setup.kibana.host` options.
# You can find the `cloud.id` in the Elastic Cloud web UI.
cloud.id:"company:ZXVyb3BlLXdlc3QzLmdjcC5jbG91ZC5lcy5pbzo0NDMkMDM13213121MGMxfdfdsfdfew3r3r32r3r32r32r32r321MGM1ZDM5NDQ0ZDk1YzA1OTgxOWJlNWFkNWQkMzQ5YzA5MTQ1fefewfewfewfewfewfewfewfOTZjYzU="

The cloud.auth setting overwrites the `output.elasticsearch.username` and `output.elasticsearch.password` settings. The format is `<user>:<pass>`. #
cloud.auth: "elastic:fefefewffwfewfewfewfewbDs3"

getting this error . Tried two versions. None of them work.

8.1.0

8.3.3

help please??

**Comment by jsoriano** [comment]
This is probably a syntax error in the configuration file.

Could you check what you have in line 101?

If you configuration file is like the one you pasted in the description, it looks like you have uncommented the line starting with `The cloud.auth setting`... Try commenting this line adding a `#` before the text.
