### ISSUE TITLE
GCP metadata instance cache is never refreshed but also never used

### ISSUE THREAD

**Issue by endorama** [elastic/beats#32734]
`gcp.compute` metricset implements a caching mechanism for GCP Instance metadata. These metadata are collected as part of instance data collection.

An investigation into how the current caching works highlighted a major flaw in it's invalidation behaviour.

**TL;DR**: current cache behaviour is useless and cache is not used, the reason for having a cache (high number of calls to `instances.Get` GCP API) has been removed and invalidating the cache is problematic (there is no way to know when data changes in GCP, with the high risk of providing stale data). Due to this the proposal is to remove the code and introduce it back if needed, as we foresee this not to be needed anymore.

we reduced a lot the number of API calls involved that justified caching and caching invalidation for this use case is very error prone; can we remove it entirely?

## How instance metadata collection works

<details>
<summary>Details</summary>

Instance metadata collection is enabled when `exclude_labels` is set to `true` in metricset configuration.

When enabled, the code instantiate a [`gcp.MetadataService`](https://github.com/elastic/beats/blob/7449e5c4b944c661299de8099d5423bafd458ee2/x-pack/metricbeat/module/gcp/metadata.go#L18):
https://github.com/elastic/beats/blob/7449e5c4b944c661299de8099d5423bafd458ee2/x-pack/metricbeat/module/gcp/metrics/metricset.go#L215-L219

which in the case of `gcp.compute` means calling this function:
https://github.com/elastic/beats/blob/7449e5c4b944c661299de8099d5423bafd458ee2/x-pack/metricbeat/module/gcp/metrics/compute/metadata.go#L29-L38

For each collection period, the `gcp.MetadataService` `Metadata` function is called to gather instance metadata.

We can assume, as knowledge of why this cache is in place has been lost, that the reason was avoiding calling the [`instances.get` GCP API endpoint](https://cloud.google.com/compute/docs/reference/rest/v1/instances/get) at each collection iteration, to avoid costly API calls and network latency. This API was called for each instance to retrieve metadata for, which also poses a scaling problem with big instance number.

This behaviour has been altered in March 2022 with this PR https://github.com/elastic/beats/pull/30154, where the single API call per instance has been improved by using [`instances.aggregatedList` GCP API](https://cloud.google.com/compute/docs/reference/rest/v1/instances#aggregatedlist) that returns batched results (up to 500 instances per result page).

So with the current implementation concerns for scaling (performance and cost wise) for this operation are greatly reduced; with 1000 instances monitored with metadata collection enabled metricbeat now performs 2 API calls instead of 1000.

</details>

## The cache

<details>
<summary>Details</summary>

The cache, called `instanceCache` in `compute.NewMetadataService` is instantiated with:
https://github.com/elastic/beats/blob/3fda4699146f9e2aa0b472a45302dc234ce53b44/x-pack/metricbeat/module/gcp/metrics/compute/metadata.go#L35

Where values are:
https://github.com/elastic/beats/blob/3fda4699146f9e2aa0b472a45302dc234ce53b44/x-pack/metricbeat/module/gcp/metrics/compute/metadata.go#L24-L25

[`common.Cache`](https://github.com/elastic/beats/blob/fc2212d7056108f0cc147791554e5f2f6099db4d/libbeat/common/cache.go) is our libbeat common cache implementation.

</details>

## What is cached

<details>
<summary>Details</summary>

When `gcp.MetadataService` `Metadata` is called its first step is to gather current instance metadata (by instance ID), which triggers a cache refresh:
https://github.com/elastic/beats/blob/7449e5c4b944c661299de8099d5423bafd458ee2/x-pack/metricbeat/module/gcp/metrics/compute/metadata.go#L144-L145

Iterating over pages of results cache refresh add the result of `instances.aggregatedList` API to `instanceCache`.

</details>

### Issue 1 - expired elements are not cleaned up

TL;DR: once filled the cache is never really refreshed because the condition expects an empty cache, but this case does not happen.

<details>
<summary>Details</summary>

The problem starts with this lines:
https://github.com/elastic/beats/blob/7449e5c4b944c661299de8099d5423bafd458ee2/x-pack/metricbeat/module/gcp/metrics/compute/metadata.go#L173-L176

This check was implemented to prevent refreshing the cache at each iteration, and wait for cache to be empty before performing a cache refresh.

But in which case `Size()` return `0`? Looking at its implementation:
https://github.com/elastic/beats/blob/fc2212d7056108f0cc147791554e5f2f6099db4d/libbeat/common/cache.go#L230-L236

we notice that `Size()` returns the number of all active and **expired** elements (that have not been yet cleaned up).

When does clean-up happens? When [`Cleanup()`](https://github.com/elastic/beats/blob/fc2212d7056108f0cc147791554e5f2f6099db4d/libbeat/common/cache.go#L197-L201) is  called, something that **never happens** in metricbeat code.

This is the first issue: once filled the cache is never really refreshed because the condition expects an empty cache, but this case does not happen.

</details>

### Issue 2 - element expiration time is extended on access

TL;DR: the expiration time for elements is changed on access, so elements would never be cleaned up (and cache size would never be 0 after the first fill).

<details>
<summary>Details</summary>

But there is a second problem: even if the cache was correctly cleaned-up, when an element is considered expired?   
The `get` function implementing cached element retrieval may update the element expiration time, depending on an internal attribute (`accessExpire`). 

Metricbeat code instantiate the cache with `common.NewCache(...)` which implemented is:
https://github.com/elastic/beats/blob/fc2212d7056108f0cc147791554e5f2f6099db4d/libbeat/common/cache.go#L82-L84

The second parameter is `accessExpire`:
https://github.com/elastic/beats/blob/fc2212d7056108f0cc147791554e5f2f6099db4d/libbeat/common/cache.go#L102

which is set to `true` by default. 

This is the second problem: the expiration time for elements is changed on access, so elements would never be cleaned up (and cache size would never be 0 after the first fill).

</details>

### Issue 3 - cache expires between periods

TL;DR: all elements expire after 30 seconds and we access them every 60 seconds, but due to not cleaning them up they are not retrieved from cache and the cache is not refreshed neither.

<details>
<summary>Details</summary>

Up to this point it seems the cache is not really working as expected, but there is another wrong behaviour.

[Cache timeout](https://github.com/elastic/beats/blob/fc2212d7056108f0cc147791554e5f2f6099db4d/libbeat/common/cache.go#L71) is initialized to `cacheTTL`, which is set to:
https://github.com/elastic/beats/blob/7449e5c4b944c661299de8099d5423bafd458ee2/x-pack/metricbeat/module/gcp/metrics/compute/metadata.go#L24

In `gcp` any period less that `60` seconds cannot be configured because that's the minimum valid for collection on GCP API side. 

This is the third issue: all elements expire after 30 seconds and we access them every 60 seconds, but due to not cleaning them up they are not retrieved from cache and the cache is not refreshed neither.

</details>

### Issue 4 - MetadataService is instantiated at each period

The cache is instantiated in [`compute.NewMetadataService`](https://github.com/elastic/beats/blob/3fda4699146f9e2aa0b472a45302dc234ce53b44/x-pack/metricbeat/module/gcp/metrics/compute/metadata.go#L29). This function is:
- called by [`gcp.NewMetadataService`](https://github.com/elastic/beats/blob/3fda4699146f9e2aa0b472a45302dc234ce53b44/x-pack/metricbeat/module/gcp/metrics/metadata_services.go#L17)
- which is called by [`gcp.eventMapping`](https://github.com/elastic/beats/blob/3fda4699146f9e2aa0b472a45302dc234ce53b44/x-pack/metricbeat/module/gcp/metrics/metricset.go#L216)
- which is called by [`gcp.Fetch`](https://github.com/elastic/beats/blob/3fda4699146f9e2aa0b472a45302dc234ce53b44/x-pack/metricbeat/module/gcp/metrics/metricset.go#L194)

This is the fourth issue: the cache instance is created for each data collection, so it always starts empty.

## Conclusions

Due to these 4 issues:
- the cache is effectively not used
- it would be filled and never refreshed
- expired items would never been cleaned up
- items would never expire because their expiration time is expanded upon access
- the cache is instantiated fresh at each collection period

the cache behaviour is wrong **and** the cache is never used.

**Comment by gabriel0270** [comment]
Should the current API call be used after cache removal or revert to the old API call? Wouldn't the current API call be too expensive to use since it would collect data for all instances?

Current:
https://github.com/elastic/beats/blob/a49b362d67a6ca05afe98fc200e45c92c5aa0ab2/x-pack/metricbeat/module/gcp/metrics/compute/metadata.go#L186

Previous:
https://github.com/elastic/beats/blob/533932724a7683e2d7de814909813afae9a255d0/x-pack/metricbeat/module/gcp/metrics/compute/metadata.go#L159

**Comment by gpop63** [comment]
Should the current API call be used after cache removal or revert to the old API call? Wouldn't the current API call be too expensive to use (without a cache) since it would collect data for all instances?

Current:
https://github.com/elastic/beats/blob/a49b362d67a6ca05afe98fc200e45c92c5aa0ab2/x-pack/metricbeat/module/gcp/metrics/compute/metadata.go#L186

Previous:
https://github.com/elastic/beats/blob/533932724a7683e2d7de814909813afae9a255d0/x-pack/metricbeat/module/gcp/metrics/compute/metadata.go#L159

**Comment by endorama** [comment]
The current API is optimized for querying a big list of instances, so I don't think we need to change it.

As of now is already being used without a cache, so I would first remove the cache (as is broken code) then think on ways to reduce it's impact (the issue with caching is that is quite difficult to establish when the cache should be refreshed)
