### ISSUE TITLE
Environment variable documentation not accurate, needs updating

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#32764]
This request  came from an Enhancement Request created for a customer:

Customer Details - Workarounds (if any): Found obscure references to prefix environment variables with "env." No references on this as an option or what conditions defines when to use this over what is stated in the docs

Customer Details - Feature Request: review documentation https://www.elastic.co/guide/en/beats/filebeat/current/using-environ-vars.html and add when to. use explicit references to host defined environment variables vs. when those same variables need to be prefixed with "env.variablename"

**Comment by colleenmcginnis** [comment]
👋  @joshdover can you please take a look here and help me identify what specifically needs to be updated in the docs? Thank you!

**Comment by joshdover** [comment]
I'm not aware of this behavior anywhere in Beats. @elastic/elastic-agent-data-plane any ideas?

**Comment by cmacknz** [comment]
I can't find this syntax used anywhere in Beats, or our configuration parsing library. Perhaps it was an old requirement that was removed.

Do we know what the obscure references to this syntax are?

**Comment by colleenmcginnis** [comment]
Closing here since we haven't gotten additional details from the customer. We can reopen if we get details.
