### ISSUE TITLE
Erroneous ECS field type

### ISSUE THREAD

**Issue by nmkoremblum** [elastic/beats#32929]
Hi!

I was reviewing the ECS tests for `auditd` logs and I've found, on the expected outputs, the following field:
https://github.com/elastic/beats/blob/3668fd6909afa261edc563d710a12fa879d5d588/filebeat/module/auditd/log/test/test.log-expected.json#L33
Shouldn't it be a `boolean`? As stated in the documentation: https://docs.elastic.co/en/integrations/auditd

Best regards,

Mariano Koremblum

**Comment by andrewkroh** [comment]
>  Shouldn't it be a boolean? As stated in the documentation: https://docs.elastic.co/en/integrations/auditd

The code you linked to is part of the Filebeat audit integration (https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-auditd.html) that parses log files with an ingest pipeline.

But the documentation you linked to is for the [Fleet integration](https://github.com/elastic/integrations/tree/main/packages/auditd). The boolean mapping looks correct for the Fleet integration given that its pipeline seems to be munging yes/no to boolean.
