### ISSUE TITLE
Wrong BEAT_PATH for metricbeat based community beats

### ISSUE THREAD

**Issue by fjgal** [elastic/beats#3294]
See [discuss](https://discuss.elastic.co/t/make-package-broken-for-community-beats/70511) for background information. @ruflin advised to create an issue for it

DST_FOLDER is not correctly set in [build.sh](https://github.com/elastic/beats/blob/master/dev-tools/packer/docker/xgo-image/base/build.sh) when building a metricbeat based community beat.

"make package" fails as follows:

```
Working directory=/go/src/github.com
Copying main source folder /source to folder /go/src/github.com
Fetching dependencies...
Execute /scripts/before_build.sh github.com/someuser
/scripts/before_build.sh: 13: cd: can't cd to /go/src/github.com/someuser
make[1]: *** [prepare-package-cgo] Error 2
make: *** [package] Error 2
```

The issue seems to be that the argument passed to build.sh is the value of the BEAT_DIR variable in the generated Makefile that doesn't contain the beat name.

Extract from generated Makefile
```
BEATNAME=somebeat
BEAT_DIR=github.com/someuser
```

build.sh is extracting the directory name using the dirname command, thus removing the last part of the BEAT_DIR variable

Extract from build.sh

```
BEAT_PATH=$1
DST_FOLDER=`dirname $GOPATH/src/$BEAT_PATH`
GIT_REPO=$BEAT_PATH
```

In the example BEAT_PATH is "github.com/someuser", DST_FOLDER will be "/go/src/github.com". build.sh creates the DST_FOLDER (/go/src/github.com). Then [before_build.sh](https://github.com/elastic/beats/blob/master/dev-tools/packer/xgo-scripts/before_build.sh) is called with $BEAT_PATH (github.com/someuser) as argument and tries to change directory to /go/src/${1} (/go/src/github.com/someuser) and fails.

To workaround the issue I modified build.sh to:

```
BEAT_NAME=$PACK
BEAT_PATH=$1/$BEAT_NAME
DST_FOLDER=`dirname $GOPATH/src/$BEAT_PATH`
GIT_REPO=$BEAT_PATH
```

There are multiple ways in which this could be solved, I tried a few, but this is the only one I found that didn't have side-effects. Not sure if this is the correct way though.

I'll submit a PR with the changes described above.

Tested on 5b973a073a02ab3753a0b1e61c7947df48f656b0
OS: Ubuntu 14.04
Steps to reproduce:

```
$ cd $GOPATH/src/github.com/someuser
$ cookiecutter $GOPATH/src/github.com/elastic/beats/generate/metricbeat/metricset
project_name [Examplebeat]: somebeat
github_name [your-github-name]: someuser
beat [somebeat]: somebeat
beat_path [github.com/someuser]: github.com/someuser
full_name [Firstname Lastname]: Some User

$ cd somebeat/
$ make setup
$ make update
$ make package
```

**Comment by ruflin** [comment]
@fjgal I found the issue. When I worked with the BEAT_PATH I update the generator for the beat, but not the one for metricbeat. So the change that should fix it, is actually updating your BEAT_PATH in your makefile and include the BEAT_NAME. Here is a fix for the generator: https://github.com/elastic/beats/pull/3300

Can you test if the above fixes your problem with packaging?

**Comment by fjgal** [comment]
Thanks @ruflin !

See comments in #3300 . It solves the issue but introduces a new one (broken imports in generated include/list.go). I proposed an additional change to fix the imports but I'm afraid it can break something since it basically reverts an existing commit. Full details in PR.
