### ISSUE TITLE
add_process_metadata: cgroup_regex should support containerd

### ISSUE THREAD

**Issue by fionera** [elastic/beats#32961]
**Describe the enhancement:**
Currently the cgroup doesnt match the name correctly:

`/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0d137909_8596_495c_92b3_048a901457b2.slice/cri-containerd-b203a127cd4bfe477ca1a85311fa00113e2edaca3cd12a28cab03b4136c6bfef.scope/`

The correct regex would be:
```
cgroup_regex: "^\/.+\/.+\/.+\/cri-containerd-([0-9a-f]{64}).scope"
```

**Describe a specific use case for the enhancement or feature:**
Matching Containerd Container cgroups

**Comment by andrewkroh** [comment]
EKS 1.24 only uses containerd[^1] so we should prioritize fixing this.

[^1]: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

**Comment by andrewkroh** [comment]
Here are some sample cgroup paths I have gathered.

```
/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2d5133c0_65f3_40b2_b375_c04866d418e1.slice/cri-containerd-e01a26336924e2fb8089bcf4cf943954fd9ea616cc5678f38f65928307979459.scope

/user.slice/user-1000.slice/user@1000.service/user.slice/libpod-conmon-ee059a097566fdc5ac9141bfcdfbed0c972163da891de076e0849d7b53597aac.scope

/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod69349abe_d645_11ea_9c4c_08002709c05c.slice/docker-80d85a3a585f1575028ebe468d83093c301eda20d37d1671ff2a0be50fc0e460.scope

/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod69349abe_d645_11ea_9c4c_08002709c05c.slice/crio-80d85a3a585f1575028ebe468d83093c301eda20d37d1671ff2a0be50fc0e460.scope

/docker/485776c9f6f2c22e2b44a2239b65471d6a02701b54d1cb5e1c55a09108a1b5b9
```

Based on those paths, I think we could add a default `cgroup_regex: '([0-9a-f]{64})(\.scope)?$'` to the processor and it would match them all out of the box.

**Comment by andrewkroh** [comment]
Relates: https://github.com/elastic/go-sysinfo/issues/191
