### ISSUE TITLE
json log using multiline exception

### ISSUE THREAD

**Issue by Iatbzh** [elastic/beats#32971]
log:
{"message":"","thread":"cccccccf1-d147-ccc-cccccd-0cccccccccccc9","pageSysId":"64","href":"http://tset/test?from=%2test","pageSpDomain":"","@timestamp":"2022-09-03T15:29:54.272Z","time":"2022-09-03 15:29:54.271","level":"INFO","container":{"image":{"name":"test:test"},"id":"cccccccccccccccccccccccccccccccctteateststset"}}

filebeat config:
`filebeat.autodiscover:
providers:
- type: kubernetes
#scope: cluster
node: ${NODE_NAME}
#unique: true
templates:
- condition:
- contains:
kubernetes.namespace: "sup"
config:
- type: container
paths:
- /var/log/containers/*${data.kubernetes.container.id}.log
multiline:
type: pattern
pattern: '^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.\d{3}\s'
negate: true
match: after
max_lines: 20000
processors:

drop_fields:
fields:
- host.name
- ecs
- log
- agent
- input
- stream
- thread
- kubernetes.node.labels
- kubernetes.node.uid
- kubernetes.node.hostname
- kubernetes.replicaset
- kubernetes.namespace_uid
- kubernetes.labels.pod-template-hash
- container.runtime
ignore_missing: true
output.kafka:
hosts: [test1:9092,test2:9092,test3:9092]
topic: test
partition.round_robin:
reachable_only: false
required_acks: 1
compression: gzip
max_message_bytes: 4194304`
Result: This log will not be collected

**Comment by mtojek** [comment]
Hi @Iatbzh! Please format your issue first using `code tags` to be clear about what is it.

**Comment by Iatbzh** [comment]
Sorry, I need to get a new code

**Comment by Iatbzh** [comment]
`filebeat config:
`filebeat.autodiscover:
providers:

type: kubernetes
#scope: cluster
node: ${NODE_NAME}
#unique: true
templates:
condition:
contains:
kubernetes.namespace: "sup"
config:
type: container
paths:
/var/log/containers/*${data.kubernetes.container.id}.log
multiline:
type: pattern
pattern: '^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.\d{3}\s'
negate: true
match: after
max_lines: 20000
processors:
drop_fields:
fields:

host.name
ecs
log
agent
input
stream
thread
kubernetes.node.labels
kubernetes.node.uid
kubernetes.node.hostname
kubernetes.replicaset
kubernetes.namespace_uid
kubernetes.labels.pod-template-hash
container.runtime
ignore_missing: true
output.kafka:
hosts: [test1:9092,test2:9092,test3:9092]
topic: test
partition.round_robin:
reachable_only: false
required_acks: 1
compression: gzip
max_message_bytes: 4194304``

**Comment by Iatbzh** [comment]
My problem is: when I use auto discovery to collect business container logs, the json log that takes up two lines cannot be collected

**Comment by mtojek** [comment]
As I said, please reformat your post using [code tags](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

**Comment by Iatbzh** [comment]
```
filebeat config: filebeat.autodiscover:
providers:

type: kubernetes
#scope: cluster
node: ${NODE_NAME}
#unique: true
templates:
condition:
contains:
kubernetes.namespace: "sup"
config:
type: container
paths:
/var/log/containers/*${data.kubernetes.container.id}.log
multiline:
type: pattern
pattern: '^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.\d{3}\s'
negate: true
match: after
max_lines: 20000
processors:
drop_fields:
fields:

host.name
ecs
log
agent
input
stream
thread
kubernetes.node.labels
kubernetes.node.uid
kubernetes.node.hostname
kubernetes.replicaset
kubernetes.namespace_uid
kubernetes.labels.pod-template-hash
container.runtime
ignore_missing: true
output.kafka:
hosts: [test1:9092,test2:9092,test3:9092]
topic: test
partition.round_robin:
reachable_only: false
required_acks: 1
compression: gzip
max_message_bytes: 4194304``
```

**Comment by endorama** [comment]
Hello @Iatbzh, in order for us to follow up this issue we need it to be clearer than what it is now.

To help us debug this, please format your posts using the appropriate formatting; [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) is a link to the GitHub docs about formatting code.

You may want to refer at the documentation for [handling multiline in filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html) and explain what is the bug here. 
Please note that we use this issue tracker only for bugs and don't answer usage question here, if it's not a bug or you are unsure about it please ask this question on our [Elastic Discuss](https://discuss.elastic.co/) forum first.

Thank you!
