### ISSUE TITLE
 Size of Filebeat index 

### ISSUE THREAD

**Issue by milandangol** [elastic/beats#33002]
Greetings everyone,
Team: Filebeat

I have a question regarding filebeat index. The scenarios is:

I am transferring Nginx access and error logs from filebeat to my Elasticsearch server. Is the size of filbeat index is equal to the size of access and error log?

Note: Any reference link will be helpful <3

Thank you in advance <3

**Comment by mtojek** [comment]
Hi,

could you please post your question on the [Discuss](https://discuss.elastic.co/c/beats/) forum first? We prefer to keep GH issues for bugs and confirmed issues.

Thanks!
