### ISSUE TITLE
ARM support in documentation

### ISSUE THREAD

**Issue by smith** [elastic/beats#33042]
In the [Metricbeat installation instructions](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-installation-configuration.html#install) and [Filebeat installation instructions](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation-configuration.html#installation) as well as the [installation instructions for Kibana packages](https://github.com/elastic/kibana/blob/98f671b1d1a06013a9a7d0f8a33b430bb3b6eec5/src/plugins/home/server/tutorials/instructions/metricbeat_instructions.ts), all instructions point to the x86 versions. ARM versions are available on the downloads page but this is not indicated in these instructions.

If have an ARM CPU and look at these instructions I wouldn't get the impression that ARM versions are available. The system integration installation instructions show the x86 links but do have a note at least mentioning ARM: 
![image](https://user-images.githubusercontent.com/9912/189424890-699c5cbd-213c-4487-8c16-af7005762253.png)

If I'm on MacOS and download the x86 version when I'm using ARM, it should work thanks to the Rosetta translation layer, but I'm not sure if this is the case on Linux and Windows.

**Comment by pierrehilbert** [comment]
Thanks @smith for bringing this issue.

@jlind23 / @kpollich could you please have a look for the Fleet part?
@kilfoyle could you please have a look for the doc part?

**Comment by kilfoyle** [comment]
I'll look after the docs part in the next sprint.

**Comment by jlind23** [comment]
@pierrehilbert the fleet message is included [here](https://github.com/elastic/kibana/blob/main/x-pack/plugins/fleet/public/components/agent_enrollment_flyout/installation_message.tsx) what should be the new copy?

**Comment by pierrehilbert** [comment]
Probably just specify that the example is with AMD but that we have ARM binaries too.
`Guidance below is for AMD but you should adapt this to your device architecture`

**Comment by kilfoyle** [comment]
How about `This guidance is for AMD but you can adapt it to your device architecture.` 
(Accessibility guidelines suggest avoiding directional terms like `below`.)

**Comment by kilfoyle** [comment]
Here are PRs for the [Beats install docs](https://github.com/elastic/beats/pull/36644) and the [Elastic Agent install docs](https://github.com/elastic/ingest-docs/pull/510).

**Comment by kilfoyle** [comment]
The Beats docs are all updated now to mention ARM support. Here's the [Metricbeat install page](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-installation-configuration.html#install), as an example.
