### ISSUE TITLE
[Heartbeat/Synthetics] Ability to map resolving DNS server(s)

### ISSUE THREAD

**Issue by BenB196** [elastic/beats#33055]
**Describe the enhancement:**

I would like the ability to track/map the DNS server(s) which were used for resolving a host.

**Describe a specific use case for the enhancement or feature:**

Today, Heartbeat/synthetics tracks the time to resolve a host via the field `resolve.rtt.us`. An issue/gap here though, is it doesn't track which DNS server(s) it attempted to contact for this. If I provide a list of DNS servers to Heartbeat/synthetics, it is my understand that Heartbeat will follow the OSes DNS server order (ex: Linux tries DNS servers in the order they're in in resolve.conf). It would be helpful for troubleshooting to know which DNS server Heartbeat/synthetics got a response from, to help troubleshoot potential DNS related issues.

**Comment by andrewvc** [comment]
Thanks for the ping @BenB196 , it's a great idea, but candidly one we haven't had much interest in. Would you be interested in submitting a patch? We'd be glad to review one, but it probably won't land on our roadmap anytime soon without broader interest.

**Comment by andrewvc** [comment]
By the way @BenB196 I am curious to hear more about your use case etc, if you'd like to connect on a call sometime reach out on the community slack channel , we'd love to hear from you. You can find it here: https://elasticstack.slack.com/archives/CNRTHRCLD
