### ISSUE TITLE
[Heartbeat] Add log and docs indicating permanent beta status / eventual removal in 8.8.0 of zip_url / local monitors

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/beats#33068]
As part of deprecating ZIP URLs, we need to start notifying users that this (beta) feature will be going away, with a preference to use [Project Monitors](https://www.elastic.co/guide/en/observability/current/synthetic-run-tests.html#synthetic-monitor-choose-project) instead.

ACs: (to be confirmed)
* Add log output and docs to clarify that ZIP URLs will be going away in the near future, and that they should migrate them to [Project Monitors](https://www.elastic.co/guide/en/observability/current/synthetic-run-tests.html#synthetic-monitor-choose-project)
* This should only happen when Heartbeat is configured with at least 1 ZIP URL monitor

**Comment by dominiqueclarke** [comment]
Post FF testing LGTM. Seeing the following log only when using zip url monitors
```
{"log.level":"warn","@timestamp":"2022-09-26T15:45:27.972-0400","log.origin":{"file.name":"source/zipurl.go","file.line":46},"message":"Zip URL browser monitors are now deprecated! Please use project monitors instead. See the Elastic synthetics docs at https://www.elastic.co/guide/en/observability/current/synthetic-run-tests.html#synthetic-monitor-choose-project","service.name":"heartbeat","ecs.version":"1.6.0"}
```
