### ISSUE TITLE
beats/libbeat/scripts/generate_template.py to support empty "nested" or "object" type definitions

### ISSUE THREAD

**Issue by christiangalsterer** [elastic/beats#3307]
Currently it is not possible to configure a type "nested" or "object" for a field but don't have any child fields defined. Currently this leads to an error.
This would be useful when the the child fields are not known in advance and/or are that many that you don't want to explicitly map them but would like to fall back to dynamic templates for the unmapped fields.

**Comment by ruflin** [comment]
Very similar to the request here: https://github.com/elastic/beats/issues/3303 I think I'm ok with adding support for it.

**Comment by christiangalsterer** [comment]
@breml: Is this maybe something you can add together with #3303?

**Comment by breml** [comment]
@christiangalsterer I had a look into this request and I have the following questions:

* In `generate_template.py` there is currently no type "object". Do you mean "group" instead?
* For the type "nested" what should be the resulting template? Could you please provide an example of the `_meta/fields.yml` and your expectation for the resulting template.

**Comment by ruflin** [comment]
@christiangalsterer @breml Be aware that we have already `nested`, `list` and `dict`: https://github.com/elastic/beats/blob/fa3ec2abda7e809a811202055977e51ac9e9c5fc/libbeat/scripts/generate_template.py#L244 https://github.com/elastic/beats/blob/fa3ec2abda7e809a811202055977e51ac9e9c5fc/libbeat/scripts/generate_template.py#L288 `list` and `dict` apply a dynamic template.

**Comment by christiangalsterer** [comment]
@breml : Will do 
@ruflin: Thanks, will look into it. I'm currently on 5.1.x of beats.

**Comment by christiangalsterer** [comment]
Here an example what I want to achieve:
[fields.txt](https://github.com/elastic/beats/files/699775/fields.txt)

The complete source code is available at: https://github.com/christiangalsterer/httpbeat
The interesting part is the jsonBody field. It contains an arbitrary ison structure which depends on the HTTP endpoint. Therefore no fixed mapping can be defined. My idea was here to use object/nested.

Currently this is generated:
`
"jsonBody": {
              "ignore_above": 1024,
              "type": "keyword"
            }
`

But I would like this to be generated:
`
"jsonBody": {
                "properties": {}
            }
`
When I use 
`
        - name: jsonBody
          type: nested
          description: >
            HTTP response body returned by the URL endpoint in JSON format.
`

I get the following error:
`
Traceback (most recent call last):
  File "./vendor/github.com/elastic/beats/libbeat/scripts/generate_template.py", line 327, in <module>
    fields_to_es_template(args, fields, output, args.beatname + "-*", version_data['version'])
  File "./vendor/github.com/elastic/beats/libbeat/scripts/generate_template.py", line 98, in fields_to_es_template
    defaults, "")
  File "./vendor/github.com/elastic/beats/libbeat/scripts/generate_template.py", line 161, in fill_section_properties
    prop, dynamic = fill_field_properties(args, field, defaults, path)
  File "./vendor/github.com/elastic/beats/libbeat/scripts/generate_template.py", line 263, in fill_field_properties
    prop, dynamic = fill_section_properties(args, field, defaults, path)
  File "./vendor/github.com/elastic/beats/libbeat/scripts/generate_template.py", line 161, in fill_section_properties
    prop, dynamic = fill_field_properties(args, field, defaults, path)
  File "./vendor/github.com/elastic/beats/libbeat/scripts/generate_template.py", line 276, in fill_field_properties
    prop, dynamic = fill_section_properties(args, field, defaults, path)
  File "./vendor/github.com/elastic/beats/libbeat/scripts/generate_template.py", line 160, in fill_section_properties
    for field in section["fields"]:
KeyError: 'fields'
make: *** [update] Error 1
`
