### ISSUE TITLE
Elasticsearch module has missing fields

### ISSUE THREAD

**Issue by miltonhultgren** [elastic/beats#33104]
The field reference and mappings of the Elasticsearch module, for the datasets `cluster_stats` and `index`, define fields that are not being populated in the events.

For `cluster_stats`, the field `elasticsearch.cluster.stats.nodes.data` is missing, due to it not being defined in the schema used to copy properties from the API response [here](https://github.com/elastic/beats/blob/main/metricbeat/module/elasticsearch/cluster_stats/data.go#L43-L44).

For `index`, the fields `elasticsearch.index.total.query_cache.memory_size_in_bytes` and `elasticsearch.index.total.request_cache.memory_size_in_bytes` are missing, since they are not part of the types used to parse the JSON payload from the API [here](https://github.com/elastic/beats/blob/main/metricbeat/module/elasticsearch/index/data.go#L73-L112).

The fixes for these two issues is pretty straight forward but we might want to check if any other fields are missing due to similar misses.

### AC

- Missing fields are added to schema/type so they are shipped with the events
- (Maybe) Any other missing field is noted and added as well

**Comment by Kerry350** [comment]
> OR update the fields.yml to only include the currently indexed fields?

Yeah, that could also work. That would also be the easiest approach. Like you say they're not being indexed so there aren't any real backwards compatibility (etc) worries.
