### ISSUE TITLE
[Filebeat][httpjson] request_body_on_pagination is not working

### ISSUE THREAD

**Issue by vinit-elastic** [elastic/beats#33132]
While using `request_body_on_pagination: true`, we are not able to access the body of the last response in the pagination request.

We tried to access the body parameter in the code around the following line. However, the request body that we got was always `nil`.
https://github.com/elastic/beats/blob/21f76589f4b24716a12c3e6df45c916d345126b0/x-pack/filebeat/input/httpjson/pagination.go#L33

Describe a specific use case for the enhancement or feature:
https://github.com/elastic/integrations/issues/1157

**Comment by ShourieG** [comment]
On extensive testing, I was found that the request_body_on_pagination is working and there seems to be no issue at the moment.
