### ISSUE TITLE
Add resource metadata in all possible Kubernetes module metricsets

### ISSUE THREAD

**Issue by MichaelKatsoulis** [elastic/beats#33144]
As described in https://github.com/elastic/beats/issues/33108 resource metadata such as namespace and node labels/annotations are present only in specific kubernetes metricsets.

In 8.1 release with https://github.com/elastic/beats/pull/29133 , the metricset level enrichers where enhanced to add those metadata. But that was only for pod/container and service. 

It makes sense to add those metadata for other namespaced resources such as deployment, replicates, jobs, cronjob, statefulset and daemonset.

**Comment by tetianakravchenko** [comment]
PR https://github.com/elastic/beats/pull/33763 was backported to 7.17, 8.5 and 8.6 versions
