### ISSUE TITLE
Packetbeat Cassandra dashboard doesn't use the right search

### ISSUE THREAD

**Issue by tsg** [elastic/beats#3314]
- Version: 5.1.2

Even though I don't have any cassandra traffic, the dashboard shows data for some widgets. This is because it doesn't filter for the cassandra type, but gets all transactions:

<img width="1008" alt="screen shot 2017-01-09 at 18 01 08" src="https://cloud.githubusercontent.com/assets/101817/21772889/bbf383f0-d695-11e6-8549-006501dfa999.png">

**Comment by monicasarbu** [comment]
Duplicates https://github.com/elastic/beats/issues/3149

**Comment by monicasarbu** [comment]
Fixed with https://github.com/elastic/beats/pull/3317
