### ISSUE TITLE
Agent V2: Check that a stream ID exists before generating an add_fields processor for it

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#33168]
In the feature-arch-v2 branch we automatically add a processor to inject the stream ID from the agent policy as event metdata, but we don't check if the stream ID exists before doing this. We should include a check for an empty stream ID before adding the processor.

This is the relevant code in the feature-arch-v2 branch:

https://github.com/elastic/beats/blob/a528bd212543af278528e0130ed3b34d7668527f/x-pack/libbeat/management/generate.go#L193-L196

**Comment by jlind23** [comment]
Closing this per https://github.com/elastic/beats/pull/33335 merge
