### ISSUE TITLE
[Stack Monitoring] Update metricbeat's elasticsearch mappings

### ISSUE THREAD

**Issue by crespocarlos** [elastic/beats#33211]
Following up the work done in https://github.com/elastic/kibana/issues/141305, we need also need to update metricbeat's mapping

**Comment by matschaffer** [comment]
From examining https://github.com/elastic/elasticsearch/pull/90203/files it looks like the changes are:

- pending_tasks.(time_in_queue,source,priority,insert_order,ms) - remove extra nexting, move fields under pending_tasks, remove `pending_task`
- add `indices.bulk` object with operations, total_size, avg_size,total_time,avg_time
- add shards.primaries (long)
- add `total.bulk` object with avg_time_in_millis,avg_size_in_bytes,total_time_in_millis,total_operations,total_size_in_bytes
