### ISSUE TITLE
[Heartbeat] States ES connection should reset on fleet reload (mandatory for 8.6)

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#33244]
Per @fearful-symmetry 's [comment](https://github.com/elastic/beats/pull/33157#issuecomment-1266116410) we should reconnect to ES with our states client when the fleet config changes.

Our states PR doesn't correctly interop with fleet for now, and won't until this is complete.

**Comment by emilioalvap** [comment]
Closed via #33405.

**Comment by justinkambic** [comment]
Post-FF Testing LGTM
