### ISSUE TITLE
How to generate list.go and fields.go files

### ISSUE THREAD

**Issue by seaung** [elastic/beats#33313]
Hey！I have a problem
I extended the packetbeat sybase database protocol
When I enter this directory（beats/dev-tools/cmd/asset/asset.go）, I execute the following command to get this error message
go run asset.go -in packetbeat -name sybase

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
	/home/xxxx/Go/src/github.com/xxxx/beats/dev-tools/cmd/asset/asset.go:77 +0x694
exit status 2

How do I execute asset.go to generate fields.go files？

go version 1.19
OS:  archlinux

**Comment by efd6** [comment]
@seaung You can see how the generator is invoked here https://github.com/elastic/beats/blob/adc85eecfcd8f9de18150a1b5ecf8717d882b222/libbeat/scripts/Makefile#LL357C51-L357C56

What you are missing is the beat name which it passed to the command as a non-flagged command line arg.

**Comment by seaung** [comment]
Ok, thank you very much
