### ISSUE TITLE
Macos auditbeat workflow fails regularly

### ISSUE THREAD

**Issue by matschaffer** [elastic/beats#33337]
## Flaky Test

* https://github.com/elastic/beats/actions/workflows/macos-auditbeat.yml

### Stack Trace

The failure I noticed was on https://github.com/elastic/beats/actions/runs/3231561566/jobs/5291216321

```
Extracting Go...
/usr/bin/tar xz -C /Users/runner/work/_temp/92936884-9ee4-4749-8fce-71c67fa6c982 -f /Users/runner/work/_temp/121c1fca-5969-4b64-ba6a-759ede53bfe5
Successfully extracted go to /Users/runner/work/_temp/92936884-9ee4-4749-8fce-71c67fa6c982
Adding to the cache ...
Assertion failed: (timeout != -1), function uv__io_poll, file ../deps/uv/src/unix/kqueue.c, line 256.
```

But looking at the run log it seems to fail at least once per day with a few different errors.

**Comment by andrewkroh** [comment]
That particular assertion is from NodeJS (which has no part of Auditbeat testing). So I think this is related to GitHub actions (probably setup-go) and caching.
