### ISSUE TITLE
[Heartbeat] States loader should only be enabled in narrow situations

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#33357]
The new states loader should only be enabled for monitors configured via central management due to it not being as compatible with the current ES output's output settings, and additionally to ensure that users of legacy heartbeat configs don't see spurious error messages in the console regarding states not being loadable.

This may be a bit tricky to detect at startup when we initially create the ES client, however, if we can detect that we're either:

1. Running in the service
2. Running under agent

That should be sufficient

**Comment by emilioalvap** [comment]
Closing as superseded by #33405
