### ISSUE TITLE
Merge feature-arch-v2 into main

### ISSUE THREAD

**Issue by pierrehilbert** [elastic/beats#33359]
Having v2 control protocol progress merged into main branch.
First step will be to merge main into feature-arch-v2 to ensure that the current delta won't break anything.

Tasks:
- [x]  Merge main branch into feature-arch-v2
- [x]  Testing to validate that everything is still working
- [ ]  Merge feature-arch-v2 branch into main after @blakerouse merged his branch October 26 at 9am PDT

**Comment by fearful-symmetry** [comment]
Branch is updated and tested. I don't suspect there will be many issues with the merge itself, as the beats V2 code touches components that don't see much activity.
