### ISSUE TITLE
MySQL Dashboard not ported over?

### ISSUE THREAD

**Issue by madhavajay** [elastic/beats#3343]
Is there a reason the MySQL Dashboard was not moved over from the old repo?

https://github.com/elastic/beats-dashboards/blob/master/dashboards/dashboard/Packetbeat-MySQL-performance.json

It would be great if there was a default example MySQL Dashboard in the metric beat install script.

**Comment by ruflin** [comment]
The dashboard you linked to is a MySQL Dashboard for packetbeat, not metricbeat. We hope to have some dashboards for mysql in the near future. Contributions are also welcome ;-)
