### ISSUE TITLE
Filebeat on macOS documentation error, breaking change

### ISSUE THREAD

**Issue by maxried** [elastic/beats#33441]
I'm running filebeat on macOS. It starts as a launchd service. After upgrading from 7 to 8, the daemon didn't run. I investigated this issue, and found that its command-line included --environment macos_service which is still suggested by the [documentation 1](https://www.elastic.co/guide/en/beats/filebeat/8.4/command-line-options.html), and worked prior to the upgrade.
Now it just makes the service die.

You can try the following which contradicts the documentation.
```
# /usr/local/filebeat/filebeat --environment macos_service
Error: invalid argument "macos_service" for "--environment" flag: 'macos_service' is not supported
[...]
```

**Comment by cmacknz** [comment]
To let us investigate this, which version of MacOS are you using? Is it an ARM (M1 or M2) system?

**Comment by maxried** [comment]
Hi @cmacknz,
I originally openend this issue for 8.4, but verified it still applies to 8.5.

The machine is a 
```
[...]
    Hardware Overview:

      Model Name: Mac mini
      Model Identifier: Macmini7,1
      Processor Name: Dual-Core Intel Core i5

[...]

    System Software Overview:

      System Version: macOS 10.15.7 (19H2026)
[...]
```

The filebeat version is 8.5.0, and is missing the `macos_service` option:
```
osx:~ root# /usr/local/filebeat/filebeat version
filebeat version 8.5.0 (amd64), libbeat 8.5.0 [6d6754fcb0adf6a2191b055d35f694c961c8ba40 built 2022-10-24 09:37:49 +0000 UTC]
osx:~ root# /usr/local/filebeat/filebeat --environment macos_service
Error: invalid argument "macos_service" for "--environment" flag: 'macos_service' is not supported
```

The documentation for 8.5 still lists it as a valid option.
https://www.elastic.co/guide/en/beats/filebeat/8.5/command-line-options.html#global-flags

Regards,
Max
