### ISSUE TITLE
In freebsd gmake error

### ISSUE THREAD

**Issue by WalterZhangYTTXG** [elastic/beats#33454]
I want to install Filebeat in FreeBSD 12.3.

So, I did these:
# mkdir -p ${GOPATH}/src/github.com/elastic
# git clone https://github.com/elastic/beats ${GOPATH}/src/github.com/elastic/beats
# cd ${GOPATH}/src/github.com/elastic/beats/filebeat

And then, wait a log time for download, I got the undefined error!!!
# gmake
go build -ldflags "-X github.com/elastic/beats/libbeat/version.buildTime=2022-10-25T08:54:40Z -X github.com/elastic/beats/libbeat/version.commit=51d0a0ad27fd8583856a5b5f72e85b6d925ef123"
github.com/elastic/beats/v7/libbeat/autodiscover/providers/kubernetes
../libbeat/autodiscover/providers/kubernetes/node.go:45:11: undefined: Config
../libbeat/autodiscover/providers/kubernetes/node.go:53:108: undefined: Eventer
../libbeat/autodiscover/providers/kubernetes/node.go:56:12: undefined: defaultConfig
../libbeat/autodiscover/providers/kubernetes/node.go:200:3: undefined: ShouldPut
../libbeat/autodiscover/providers/kubernetes/pod.go:43:20: undefined: Config
../libbeat/autodiscover/providers/kubernetes/pod.go:58:105: undefined: Eventer
../libbeat/autodiscover/providers/kubernetes/pod.go:61:12: undefined: defaultConfig
../libbeat/autodiscover/providers/kubernetes/pod.go:364:2: undefined: ShouldPut
../libbeat/autodiscover/providers/kubernetes/service.go:43:20: undefined: Config
../libbeat/autodiscover/providers/kubernetes/service.go:52:109: undefined: Eventer
../libbeat/autodiscover/providers/kubernetes/pod.go:364:2: too many errors
gmake: *** [../libbeat/scripts/Makefile:137: filebeat] Error 2

So, What should I do? Or imort some packages below file(../libbeat/autodiscover/providers/kubernetes/service.go) ?
![image](https://user-images.githubusercontent.com/89920931/197730908-c2c4631f-5b39-4493-ab04-8d1474dab678.png)

**Comment by zghzcl** [comment]
I get it. 
In the autodiscover go code, there have some limit to build in freebsd. Like:
`//go:build linux || darwin || windows`
`// +build linux darwin windows`
So, some code will not be built in freebsd.

You can disable built the autodiscover at all, by edit ${GOPATH}/src/github.com/elastic/beats/filebeat/autodiscover/defaults.go

**Comment by zghzcl** [comment]
Well, do not forget comment or delete the limit in `${GOPATH}/go/src/github.com/elastic/beats/libbeat/autodiscover/providers/kubernetes/config.go` and `${GOPATH}/go/src/github.com/elastic/beats/libbeat/autodiscover/providers/kubernetes/kubernetes.go` files. 
Like
` 18 ////go:build linux || darwin || windows`
 `19 //// +build linux darwin windows`

**Comment by michel-laterman** [comment]
Hi @WalterZhangYTTXG, freebsd is not officially supported by the beats: https://www.elastic.co/support/matrix

**Comment by WalterZhangYTTXG** [comment]
> Hey, @WalterZhangYTTXG, have you managed to compile filebeat on freebsd? I followed your steps and I am having a hard time.

 maybe you can show me the error

**Comment by WalterZhangYTTXG** [comment]
> Hey, @WalterZhangYTTXG, have you managed to compile filebeat on freebsd? I followed your steps and I am having a hard time.

 maybe you can show me the error

**Comment by WalterZhangYTTXG** [comment]
> Hey, @WalterZhangYTTXG, have you managed to compile filebeat on freebsd? I followed your steps and I am having a hard time.

I have upload what I built on the [https://github.com/WalterZhangYTTXG/freebsd-filebeat](https://github.com/WalterZhangYTTXG/freebsd-filebeat)

**Comment by lmarquesatlas** [comment]
> maybe you can show me the error

Sure. Thanks a lot for sending the build.

I was trying again here. Just to be clear, you cloned the beats repository, altered the lines in filebeat/autodiscover/defaults.go to be:

//go:build linux || darwin || windows
// +build linux darwin freebsd windows

////go:build !aix
//// +build !aix

And in the kubernetes folder in libbeat you altered the lines to:
////go:build linux || darwin || windows
//// +build linux darwin windows

Right? You did not wrote freebsd in those sections?

Then you just hit the gmake?

**Comment by lmarquesatlas** [comment]
I just baked a blank virtual machine and following your steps it worked! Thanks a lot for your help

**Comment by WalterZhangYTTXG** [comment]
> I just baked a blank virtual machine and following your steps it worked! Thanks a lot for your help

Congratulations!
