### ISSUE TITLE
Suggested configuration of Logstash output is broken 

### ISSUE THREAD

**Issue by fdartayre** [elastic/beats#33480]
The suggested Elasticsearch output for Logstash configuration in https://github.com/elastic/beats/blob/main/libbeat/outputs/logstash/docs/logstash.asciidoc doesn't work as is because of this bug https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/1070

The workaround is to add `action => "create"` to the config
```
output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "%{[@metadata][beat]}-%{[@metadata][version]}"
    action => "create"
  }
}
```
The documentation should include the workaround (and explain why) until the bug is fixed.

**Comment by dedemorton** [comment]
@fdartayre Do you think it's good enough to cover this in the Beats release notes as a known problem and workaround? I'm a little concerned folks might miss it in the release notes, but generally we don't change the main config docs to show workarounds. WDYT?

**Comment by fdartayre** [comment]
@dedemorton As an afterthought, I agree it makes sense to not refer to this line as a workaround. What about just adding `action => "create"` to the configuration without mentioning that the output should default to it? It doesn't hurt to add it explicitly as this is the only `op_type` value supported by data streams (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#docs-index-api-op_type).
