### ISSUE TITLE
Update the Beats to use the v2 agent diagnostics implementation

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#33515]
The v2 agent diagnostics implementation was merged in https://github.com/elastic/elastic-agent-client/commit/c29f5dc424c21a2b5a6a6ba48b8fe8d20e2eb8cd#diff-3c9d2164a39c92f1361955b4483509f7b321536355994587b26acca7828c2b39.

That change adds a default set of diagnostics that collects pprof information. We need to update the version of the elastic-agent-client used on the feature-arch-v2 branch to include this change, currently the version is not up to date: https://github.com/elastic/beats/blob/6421c5cf59f932420094554d965ace255ee4a160/go.mod#L73 The commit used here is https://github.com/elastic/elastic-agent-client/commit/b0328d2fe484f3ecfe6d52efdf18058431743e83 which is before the diagnostics change.

We should also start a few of the Beats (Filebeat or Metricbeat are sufficient) and ensure that when they are run with the v2 agent the `elastic-agent diagnostics collect` and `elastic-agent diagnostics collect --pprof` commands work produce the expected results.

**Comment by fearful-symmetry** [comment]
closed by https://github.com/elastic/beats/pull/33552
