### ISSUE TITLE
Fix Beats links to prep for master > main link renaming

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#33577]
**Describe the enhancement:**
We need to fix all the links that will break when we rename `master` to `main` in our doc URLs.

Related to https://github.com/elastic/docs/pull/2521

**Background**
At some point in the near future, we want to use `master` instead of `main` in the doc URLS on elastic.co. Unfortunately, some of the books use hard-coded URLS instead of asciidoc attributes to resolve link paths. We need to figure out the best way to fix those links with minimal work.

**Links to fix**
Here is a list of the links that are breaking in https://github.com/elastic/docs/pull/2521.

17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.10/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.11/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.12/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.13/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.14/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.15/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.16/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.17/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.2/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.3/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.4/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.5/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.6/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.7/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.8/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/7.9/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/8.2/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/8.3/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/8.4/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/8.4/metricset-details.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/mapping-types.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/8.5/creating-metricbeat-module.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/metricbeat/master/metricbeat-module-mysql.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/8.5/metricset-details.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/mapping-types.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/filebeat/5.0/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/filebeat/5.1/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/filebeat/5.2/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/filebeat/5.3/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/filebeat/5.4/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/filebeat/5.5/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/filebeat/5.6/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/heartbeat/5.2/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/heartbeat/5.3/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/heartbeat/5.4/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/heartbeat/5.5/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/heartbeat/5.6/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/libbeat/1.0.1/new-beat.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/devguide/master/index.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/libbeat/1.1/new-beat.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/devguide/master/index.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/libbeat/1.2/new-beat.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/devguide/master/index.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/libbeat/1.3/new-beat.html contains broken links to:
17:25:18 INFO:build_docs:   - en/beats/devguide/master/index.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/5.0/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/5.0/metricset-details.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/mapping-types.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/5.1/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/5.1/metricset-details.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/mapping-types.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/5.2/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/5.2/metricset-details.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/mapping-types.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/5.3/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/5.3/metricset-details.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/mapping-types.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/5.4/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/5.4/metricset-details.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/mapping-types.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/5.5/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/5.5/metricset-details.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/mapping-types.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/5.6/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/5.6/metricset-details.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/mapping-types.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/8.4/metricbeat-metricset-elasticsearch-node.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/cluster-nodes-info.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/8.4/metricbeat-metricset-elasticsearch-node_stats.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/cluster-nodes-stats.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/8.5/metricbeat-metricset-elasticsearch-node.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/cluster-nodes-info.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/8.5/metricbeat-metricset-elasticsearch-node_stats.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/cluster-nodes-stats.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/current/metricbeat-metricset-elasticsearch-node.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/cluster-nodes-info.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/current/metricbeat-metricset-elasticsearch-node_stats.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/reference/master/cluster-nodes-stats.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/5.0/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/5.0/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/5.1/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/5.1/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/5.2/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/5.2/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/5.3/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/5.3/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/5.4/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/5.4/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/5.5/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/5.5/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/5.6/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/5.6/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/6.0/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/6.1/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/6.2/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/6.3/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/6.4/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/6.5/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/6.6/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/6.7/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/6.8/exported-fields-common.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/using-ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/winlogbeat/5.0/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/winlogbeat/5.1/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/winlogbeat/5.2/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/winlogbeat/5.3/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/winlogbeat/5.4/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/winlogbeat/5.5/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html
17:25:18 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/winlogbeat/5.6/configuration-general.html contains broken links to:
17:25:18 INFO:build_docs:   - en/elasticsearch/plugins/master/ingest-geoip.html

**Comment by dedemorton** [comment]
@elastic/obs-docs Before I spend more time playing whack-a-mole, I'm wondering if anyone has a clever way to make sure we don't create 200+ PRs. I want to:

* Batch these changes in as few PRs as possible.
* Avoid having to resolve file conflicts because it takes time.

Creating a script that checks out each branch, searches for the links that will break, and replaces them might be the sanest way forward, but I want a gut check. 

I think the backport capabilities in the Beats repo do not support backporting very far, so the other option is to use the backport tool. 

WDYT?

**Comment by dedemorton** [comment]
Lookin at Lisa's fixes in https://github.com/elastic/beats/pull/33318, looks like _most_ of the backports went OK. Rather than trying to script this, we might be able to batch the changes in a few PRs and backport the changes.

**Comment by dedemorton** [comment]
@bmorelli25 I need to make a final decision about whether to continue this work. I've come up with a plan for batching these changes, but it still involves creating ~30 PRs. These PRs will use compute resources for CI plus will need to be reviewed. I couldn't get all the changes made last week (on the plane and in the hotel) because the wifi was not good. I don't think changing master to main is a high enough priority to warrant spending any more time on this, but wanted to get your OK before I shelve this work. It might be worth merging the PRs that I have open, but I don't want to spend even a few hours on this unless you think it's worth the time.

With your permission, I will close this issue and indicate that we will not do this work.

cc @lcawl

**Comment by bmorelli25** [comment]
I tend to agree. I think, unfortunately, we don't have the resources to dedicate time to this effort right now.

**Comment by dedemorton** [comment]
Closing this issue because it sounds like we have an approach that is more efficient than manually updating all these links.
