### ISSUE TITLE
Is there any plan that filebeat supports the hdfs output directly

### ISSUE THREAD

**Issue by gangxie112** [elastic/beats#33615]
**Describe the enhancement:**
Need hdfs output
**Describe a specific use case for the enhancement or feature:**

In some product env, we have no kafka, and willing to upload the log data to hdfs directly. So Is there any plan that filebeat supports the hdfs output directly?

**Comment by pierrehilbert** [comment]
@nimarezainia, could you please review this need?

**Comment by nimarezainia** [comment]
@whua3 an @gangxie112 there are currently no plans to support HDFS directly.
