### ISSUE TITLE
We need to load a different template for 6x than 5x

### ISSUE THREAD

**Issue by tsg** [elastic/beats#3368]
Elasticsearch 6.x rejects templates that set any `_all` settings. We do that in our templates, so we'll need to create different templates for 5.x and 6.x.

Marking this as a blocker for 5.3, in case we're releasing 5.3 from the current master.

**Comment by ruflin** [comment]
We currently only used `norms: false` under all. As almost all fields (except for some `raw` fields`) are part of the template, we could set `norms:false` for each field in the template. This should have an almost identical outcome and would require only 1 template for 5.x and 6.x.

**Comment by tsg** [comment]
Hmm, I'm not sure it would be the same. In 5.x, `_all` is an actual field with its own settings, unrelated to the fields it is build from.

**Comment by ruflin** [comment]
@tsg you are right, I mixed up two different things 👎

**Comment by tsg** [comment]
The (temporary) solution for 5.3 is to add back the `_all` setting, but only in the 5.3 branch. We still need a proper solution for a future version, probably for 5.4.

**Comment by exekias** [comment]
This was fixed by https://github.com/elastic/beats/pull/3778, master uses a different approach too: https://github.com/elastic/beats/blob/18031fbf504da0c14c832445a798389dd8eec5ab/libbeat/template/template.go#L113
