### ISSUE TITLE
Add tests for importing dashboards

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#3370]
The import_dashboard tests were broken because they tested the exit code which was always 0.

In #3252 we fixed the exit code, but the tests are broken because they are part of libbeat where they depend on the index patterns in each of the beats which are not generated when the test runs. The beats may depend on libbeat, but libbeat may not depend any beat.

So one solution is to test the dashboards in each of the beats' test. We could have some kind of dummy data in libbeat to test the `import_dashboards` tool without creating a dependency on a beat.

**Comment by andrewkroh** [comment]
@ruflin has been adding tests for dashboards.

- [X] Metricbeat #5770
- [X] Auditbeat #5938

**Comment by kvch** [comment]
`import_dashboards` tool has been removed. Closing.
