### ISSUE TITLE
[flaky test] Filebeat http_endpoint - TestServerPool/inconsistent_tls_config

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#33717]
## Flaky Test

* **Test Name:** `TestServerPool/inconsistent_tls_config`
* **Link:** https://github.com/elastic/beats/blob/d45c34993f4999436846cf3ff0694b1b39d44bf6/x-pack/filebeat/input/http_endpoint/input_test.go#L203
* **Branch:** Git branch the test was seen in. If a PR, the branch the PR was based off.
* **Artifact Link:**
  - https://github.com/elastic/beats/pull/33710#issuecomment-1317956483
* **Notes:** 
It looks like a possible race condition because the ordering TLS config is opposite of what is expected in the error message. The `old` and the `new` configs are swapped (the verification_modes are got=[3,1] and want=[1,3]).

### Stack Trace

```
 === RUN   TestServerPool/inconsistent_tls_config
    input_test.go:245: unexpected error calling serve: 
got=`inconsistent TLS configuration on 127.0.0.1:9001: 
configuration options do not agree: 
old={"ca_sha256":[],"certificate":"","certificate_authorities":[],"cipher_suites":[],"client_authentication":0,"curve_types":[],"key":"","key_passphrase":"","supported_protocols":[],"verification_mode":3} 
new={"ca_sha256":[],"certificate":"","certificate_authorities":[],"cipher_suites":[],"client_authentication":0,"curve_types":[],"key":"","key_passphrase":"","supported_protocols":[],"verification_mode":1}`, 

want=`inconsistent TLS configuration on 127.0.0.1:9001: 
configuration options do not agree: 
old={"ca_sha256":[],"certificate":"","certificate_authorities":[],"cipher_suites":[],"client_authentication":0,"curve_types":[],"key":"","key_passphrase":"","supported_protocols":[],"verification_mode":1} 
new={"ca_sha256":[],"certificate":"","certificate_authorities":[],"cipher_suites":[],"client_authentication":0,"curve_types":[],"key":"","key_passphrase":"","supported_protocols":[],"verification_mode":3}`
    --- FAIL: TestServerPool/inconsistent_tls_config (1.00s)
```

**Comment by efd6** [comment]
I think the race assessment is correct; it looks like a logic race in the ordering of running the configs. This should only show up in testing for the exact error. The two options I see would be to test against all orderings in the test or to canonicalise the order of the configs in some way, most likely lexically on the serialized config.
