### ISSUE TITLE
[docs] Filebeat | Input filestream reference documentation

### ISSUE THREAD

**Issue by JohannesMahne** [elastic/beats#33727]
Could you please have a look at the documentation, especially the following discrepancy:

- The `target` option of the `ndjson` configuration is mentioned in the [documentation](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html)
- but, the [reference configuration](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-reference-yml.html) does not mention it.

**Comment by dedemorton** [comment]
Looks like the field was added in this PR, but the yaml file was not updated as it should have been: https://github.com/elastic/beats/pull/31387

This change also needs to be made for the kafka input.

**Comment by JohannesMahne** [comment]
@dedemorton - is there something that we should do so that this can be updated?

**Comment by dedemorton** [comment]
I'm going to change the team label here because we really want the development team (not docs) to own updates to the reference.yml files. The docs simply pull the existing file in so it's discoverable through a docs search.
