### ISSUE TITLE
Document replace processor

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#33757]
**Describe the enhancement:**

The replace processor is documented [here](https://github.com/elastic/beats/blob/main/libbeat/processors/actions/docs/replace.asciidoc), but was never added to the TOC, so the docs were not published. Was this intentional? Do we want to add the processor to the published docs?

**Describe a specific use case for the enhancement or feature:**
Users might want to use this processor, but can't if it's not documented.

**Comment by dedemorton** [comment]
@pierrehilbert Can you ask someone on the team to take a look at this processor and confirm that we want to publish these docs? I can help get the content building; just want to make sure there's not some historical reason why the docs weren't published.

**Comment by cmacknz** [comment]
This was unintentional from what I can tell.

**Comment by pierrehilbert** [comment]
I agree

**Comment by faec** [comment]
Yes, this is safe to publish

**Comment by dedemorton** [comment]
I will get this processor updated and building because I need to get it into the agent docs, too.
