### ISSUE TITLE
Support RHEL 9 / Alma 9 OSs

### ISSUE THREAD

**Issue by a03nikki** [elastic/beats#33839]
**Describe the enhancement:**

The [support matrix](https://www.elastic.co/support/matrix#show_compatibility), does not include RHEL 9 or Alma 9.  Please include and support these

**Describe a specific use case for the enhancement or feature:**

[RHEL 9](https://www.redhat.com/en/blog/hot-presses-red-hat-enterprise-linux-9) is the latest [Red Hat Enterprise Linux](https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux) version.  Users are starting to have it deployed in their environments as it was released in May 2022.

[Alma 9](https://almalinux.org/blog/almalinux-9-now-available/) is the latest [Alma Linux](https://almalinux.org/) which was also released in May 2022.

Users who already using Filebeat and Auditbeat on RHEL 8 or Alma 8 would like to continue to do so when they upgrade their operating systems (OSs).

Related https://github.com/elastic/elastic-agent/issues/1803.

**Comment by jlind23** [comment]
@nimarezainia could you comment here please?

**Comment by 111andre111** [comment]
Hi folks,
Please don't forget to update the Support matrix as well appropriately:
https://www.elastic.co/support/matrix#matrix_os

**Comment by epixa** [comment]
RHEL9 Packetbeat: https://github.com/elastic/beats/issues/34576
RHEL9 Auditbeat: https://github.com/elastic/beats/issues/34577

**Comment by nimarezainia** [comment]
Alma Linux 9 and Rocky Linux 9 are added to the matrix or 8.10
