### ISSUE TITLE
[Metricbeat/Kibana/Stats] `GET /api/status` crashes the agent when 503 status code is received

### ISSUE THREAD

**Issue by afharo** [elastic/beats#33838]
Metricbeat's Kibana module uses the `GET /api/status` in some places:

1. The `status` metricset: https://github.com/elastic/beats/blob/a1a6bd8cd569182aeb0082e252ecbabad338a797/metricbeat/module/kibana/status/status.go#L41
2. The `stats` metricset: https://github.com/elastic/beats/blob/a1a6bd8cd569182aeb0082e252ecbabad338a797/metricbeat/module/kibana/stats/stats.go#L90-L93

When any of the **core** services in Kibana is not available, the `GET /api/status` returns `503` while the body keeps the expected 200 body structure.

Running ECK locally, I noticed that the Kibana k8s service takes longer to start when the `monitoring.metrics` options set up because the `metricbeat` container bootloop-crashes (with backoff retries) while Kibana fully starts up and `GET /api/status` returns `200`.

```NDJSON
{"log.level":"info","@timestamp":"2022-11-28T12:35:12.661Z","log.origin":{"file.name":"instance/beat.go","file.line":432},"message":"metricbeat stopped.","service.name":"metricbeat","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-11-28T12:35:12.661Z","log.origin":{"file.name":"instance/beat.go","file.line":1062},"message":"Exiting: 4 errors: HTTP error 503 in : 503 Service Unavailable; HTTP error 503 in : 503 Service Unavailable; HTTP error 503 in : 503 Service Unavailable; HTTP error 503 in : 503 Service Unavailable","service.name":"metricbeat","ecs.version":"1.6.0"}
```

_For details about how to set up a monitoring architecture in k8s, follow the steps explained in https://github.com/elastic/kibana/issues/145558#issuecomment-1323509356_

IMO, metricbeat should not crash on 503 and, on top of that, still process the response body for the Kibana metricsets.

**Comment by smith** [comment]
We're not planning to do this at this time.

**Comment by smith** [comment]
Reopening and putting on Stack Monitoring board.
