### ISSUE TITLE
Support Ubuntu 22.04 OS for Auditbeat

### ISSUE THREAD

**Issue by a03nikki** [elastic/beats#33840]
**Describe the enhancement:**

The [support matrix](https://www.elastic.co/support/matrix#show_compatibility), does not include Ubuntu 22.04 for Audtibeat.  Please include and support it.

**Describe a specific use case for the enhancement or feature:**

Ubuntu 22.04 is already listed as a supported version for Filebeat and Metriceat, it would be helpful if it included Auditbeat as well.  [Ubuntu 22.04](https://canonical.com/blog/ubuntu-22-04-lts-released) has been out since April 2022.  Users are starting to migrate to this OS version.

Users who already using Filebeat and Auditbeat on earlier versions of Ubuntu would like to continue to do so when they upgrade their operating systems (OSs).

**Comment by jamiehynds** [comment]
@andrewkroh is Ubuntu 22.04 included as part of our automated testing? If not, is it possible to include with a view to adding support for it?

**Comment by andrewkroh** [comment]
Relates: https://github.com/elastic/beats/pull/34315

**Comment by jamiehynds** [comment]
Closing, as we are adding support for Auditbeat on Ubuntu 22.04 as part of the 8.9 release. This will be reflected on the support matrix once 8.9 is released.
