### ISSUE TITLE
[Metricbeat] Excluding bind mounts

### ISSUE THREAD

**Issue by abraxxa** [elastic/beats#3384]
Feature request per https://discuss.elastic.co/t/excluding-bind-mounts/71509

- Version: 5.1.2
- Operating System: Debian 8 Linux 64bit
- Steps to Reproduce: 
install and configure metricbeat to collect filesystem/fsstat data
look at both installed Kibana dashboards, storage space is counted multiple times when bind mounts exist

Suggested solution:
Add a filesystem type field to the mapping, add a filter to the default config or hardcode exclude bind mounts (that would always make sense for fsstat as the total space is wrong with them).

**Comment by willemdh** [comment]
The fsstat module is really useless atm, please exclude mount points and subpaths by default.

**Comment by jsoriano** [comment]
After #6819, each filesystem should appear only once even if it is mounted multiple times, if it is, only the shorter mount path is reported. Bind mounts won't be reported as it is assumed that the source/parent filesystem is also mounted and reported on its own.

Also, file systems of "virtual" filesystem types won't be reported by default (these types are autodiscovered when possible and added to [`filesystem.ignore_types`](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-system-filesystem.html)).

I hope it helps to make these metricsets more useful by default, closing this by now.

**Comment by abraxxa** [comment]
Sounds great, thanks! In which version will this be included?

**Comment by ruflin** [comment]
@abraxxa 6.3
