### ISSUE TITLE
Metricbeat not collecting tags for AWS - Apigateway `resource_type:restapis`

### ISSUE THREAD

**Issue by laraMorenoIgle** [elastic/beats#33913]
**Bug description:**
With the below configuration to collect metrics from AWS/Apigateway and include the tags for the restapis service. 
````
  metrics:
    - namespace: "AWS/ApiGateway"
      resource_type: apigateway:restapis
````
However, It was detected that the tags are not being collected for such resource type.
 
**Version:** 8.4.3
**Steps to Reproduce:**
- we collect all the tags for a given resource type
- we obtain a list of resource ARNs of the given type
- from the above list we extract from the ARNs the resource information and collect them with their related tags
- we then collect the metrics for the namespace
- we obtain a list of metrics with their dimensions, that usually include the resource information part of the ARN
- we match the resource information part of the ARN in the metrics list with the one from the collection of tags

This proofed to work for EC2, RDS etc and in general all the predefined module we have in metricbeat, but does not seem to work for restapis: that's because the information in the metrics dimensions and the information in the tag list, related to the resource, it's different

Here's an example from EC2, see the matching of the two values highlighted:
![image](https://user-images.githubusercontent.com/221530/205026755-7f2e1d9a-a70f-4308-8492-e4d0935bfcc2.png)

Here's the same from restapi, see how the subIdentifier (the information coming from metrics dimentions) is the name of the rest api, but the resource information in the tags collection coming from the ARN does not match:
![image](https://user-images.githubusercontent.com/49395637/205034868-7233782a-d5dd-4c8a-8b49-3ee789265431.png)

**Comment by endorama** [comment]
Updates on my investigation. TLDR: this is not possible to fix in its entirety but there are a couple of workarounds worth exploring that would help mitigating the problem.

# Why it can't be fixed?

As mentioned in the previous comments, there is no data to match the metric data and the tags.

The identifier used by the metrics comes from metric labels:
https://github.com/elastic/beats/blob/af41650a00153c599992736ee0acb37e661b80e6/x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go#L545
https://github.com/elastic/beats/blob/af41650a00153c599992736ee0acb37e661b80e6/x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go#L528
https://github.com/elastic/beats/blob/af41650a00153c599992736ee0acb37e661b80e6/x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go#L523
https://github.com/elastic/beats/blob/af41650a00153c599992736ee0acb37e661b80e6/x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go#L465

`GetMetricsDataResults` returns `([]types.MetricDataResult, error)` ([source](
https://github.com/aws/aws-sdk-go-v2/blob/69119818ef63fe807b5613a9f554f90308480409/service/cloudwatch/types/types.go#L625): `Id` does not contain identifiable information; `Label` does and is in this format: `"5XXError|AWS/ApiGateway|Average|ApiName|PetStore"`

API Gateway API name is used, no other identifiable information is available.

On the other hand, tags are collected separately. When they are matched with the incoming metrics, this is an example situation:
* `resourceTagMap` is a `map[string][]github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi/types.Tag` ([source](https://github.com/aws/aws-sdk-go-v2/blob/69119818ef63fe807b5613a9f554f90308480409/service/cloudwatch/types/types.go#L957)) containing:
```
        "i747znhp4g": [(0xc00108cd20), (0xc00108cd38),],
        "/restapis/i747znhp4g": [(0xc00108cd20), (0xc00108cd38),],
        "v7o6rbtm6i": [(0xc00061f560),(0xc00061f578),(0xc00061f590),(0xc00061f5a8),],
        "/restapis/v7o6rbtm6i": [(0xc00061f560),(0xc00061f578),(0xc00061f590),(0xc00061f5a8),],
```
`i747znhp4g` and `v7o6rbtm6i` are API Gateway IDs. The ID and the `/restapis/ID` keys contain the same tags.
* `labels` is a `[]string` containing:
```
["4XXError","AWS/ApiGateway","Average","ApiName","PetStore",]
```
The fourth index is used as metric identifier, resulting in `PetStore`

Nowhere in the logic the code knows the ID of the API Gateway, thus we can conclude that there is no way to match the API Gateway metric with the appropriate labels.

To workaround this it should be possible to match API Gateways names with Ids through [`apigateway#Client.GetRestApis`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/apigateway#Client.GetRestApis): it returns a [`apigateway#GetRestApisOutput`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/apigateway#GetRestApisOutput) containing a slice of [`apigateway/types#RestApi`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/apigateway/types#RestApi), containing API Gateway unique ID **and** name.

This would work **but** API Gateways can have the duplicated names (as uniqueness is guaranteed from the ID).

Thus univocally matching an API Gateway metric to a tag is not possible.

# Workaround 1

When `namespace` is `AWS/APIGateway` and `resource_type` is `restapis` we use `GetRestApis` to find the API Gateway Id from name and use that to match metrics.

Pitfall: does not work when there are multiple API Gateway with the same name.
Trade off: if this happen, tag collection will be skipped and a message will be logged by metricbeat; documentation would document this use case mentioning this limitation.

# Workaround 2

We request customers to apply a tag to the API Gateway resource. The tag must have an unique and known Key, which we use to find the appropriate tags in the `resourceTagMap`.

Pitfall: is unpredictable if there are multiple API Gateway with the same name.
Trade off: this can't be solved by the code itself, as using tags would prevent it from knowing that is in the "multiple resource with same tag" case; documentation could help; this could potentially resolve the pitfall of Workaround 1 but in a more complex way.

**Comment by tommyers-elastic** [comment]
hey thanks edo and andrea for the investigations into this so far. 

from my point of view, neither of the workarounds presented here really offer a great solution for the user. i think for the time being we should document this as a known limitation of the integration and we should follow up with AWS to see if we can find a solution to getting the restapi ID, instead of the name.

let's park any further work on this for now.

**Comment by PBoff** [comment]
@tommyers-elastic - can you please clarify what we can offer to the customer, I see we need to amend our documentation but is there a way forward we can offer or is there nothing we can do?.

**Comment by RobDTech** [comment]
Agreed, the workarounds don't work for us either. Would be great to hear how you get on with AWS.

**Comment by axw** [comment]
Reopening as https://github.com/elastic/beats/pull/40755 has been reverted. CI started failing after that was merged; it doesn't look likely that it's specific to the change, but all the same Beats CI needed to be stabilised.

**Comment by damianpfister** [comment]
@axw - any suggestions on where the problem might be here, that required the revert? Just keen to get an idea whether the merge will be applied again in the near-term or rather requires deeper investigation.

**Comment by axw** [comment]
@damianpfister as far as I know, investigation is ongoing (https://github.com/elastic/beats/pull/41087#issuecomment-2399999992). @gizas is that right?

**Comment by gizas** [comment]
@damianpfister still investigation is ongoing: https://github.com/elastic/beats/issues/41270

**Comment by rdner** [comment]
@damianpfister @gizas the investigation is over and the linker problem was solved, see https://github.com/elastic/beats/issues/41270#issuecomment-2429291137

https://github.com/elastic/beats/pull/40755 can be re-applied again.

**Comment by gizas** [comment]
Thank you @rdner ! Opened https://github.com/elastic/beats/pull/41388

**Comment by gizas** [comment]
Closing this as PR was merged and keeping https://github.com/elastic/sdh-beats/issues/5103#event-15300976051
