### ISSUE TITLE
metricbeat.reference.yml contradict the official documentation

### ISSUE THREAD

**Issue by ker2x** [elastic/beats#33938]
In [metricbeat.reference.yml](https://github.com/elastic/beats/blob/main/metricbeat/metricbeat.reference.yml), the documentations says : 
```
# Disable the check for an existing lifecycle policy. The default is true. If
# you disable this check, set setup.ilm.overwrite: true so the lifecycle policy
# can be installed.
#setup.ilm.check_exists: true
```

It is misleading and imply that the ilm policy can be installed even if check_exist is false. 
But this is not the case (tested on 8.4.2) and the official documentation agree.

A correct comment would be (shortened copy/paste from the official doc): 
```
# Disable the check for an existing lifecycle policy. The default is true. 
# If you set this option to false, lifecycle policy will not be installed, 
# even if setup.ilm.overwrite is set to true.
#setup.ilm.check_exists: true
```

If setup.ilm.check_exists is set to false, the ILM policy is silently ignored.

- Link to the official documentation : https://www.elastic.co/guide/en/beats/metricbeat/master/ilm.html
- I commited a change in a fork : https://github.com/elastic/beats/commit/98399a8864770c736f328d4916ffb9705d11b76e

I can create a pull request if you want. 
Or a contributor can just modify the 4 line. 
the PR process is needlessly complicated for such a non-functional (but important) modification.

_hugs_

**Comment by ker2x** [comment]
i rechecked the official documentation and it still contradict the comment in the yml

**Comment by belimawr** [comment]
@ker2x here is the PR: https://github.com/elastic/beats/pull/37430

Thanks for the help!
