### ISSUE TITLE
[Metricbeat] beat module - add metricset for input metrics

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#33953]
**Describe the enhancement:**

Add a new `input` metricset to the [Beat module](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-beat.html) to collect metrics from various inputs with Beats (e.g. [aws-s3](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-aws-s3.html#_metrics), winlog, udp). Several of the inputs already export per instance metrics and we are exposing those metrics under `/inputs/` on the Beat http monitoring endpoint.

**Describe a specific use case for the enhancement or feature:**

Once we can collect these metrics we can build dashboards to help understand and diagnose issues with input behavior or configuration. For example this metricset could be enabled as part of Agent monitoring to collect input metrics from Filebeat. Then dashboards could be created in the `elastic_agent` Fleet integration package for each input type to make sense of the data.

### Relates

- #33859
- #33870 
- #33922

**Comment by andrewkroh** [comment]
On this we are going to pivot to using the [`http.json`](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-http-json.html) metricset with Metricbeat rather than adding new code in the Beat module. This should work given that `/inputs/` is returning an array.

**Comment by kcreddy** [comment]
Thanks for the updates. I will get started and test it standalone

**Comment by kcreddy** [comment]
CC: @epixa

**Comment by andrewkroh** [comment]
This was implemented via the http.json metricset in Metricbeat. There was no need to add a new metricset to implement this. See https://github.com/elastic/integrations/pull/5077 and https://github.com/elastic/elastic-agent/pull/2171.
