### ISSUE TITLE
[Automation] Terraform AWS integration tests are skipped for Filebeat

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#34003]
The integrations tests with AWS for Filebeat's aws-s3 input are skipped. CI config needs to be modified to provide the tests with access to data produced by Terraform. According to analysis in https://github.com/elastic/beats/pull/33893, CI "stashes" the results of Terraform before executing the Filebeat tests and therefore Filebeat cannot access the data it needs to execute the tests.

See https://github.com/elastic/beats/pull/33893 for more analysis.

**Comment by aspacca** [comment]
> CI config needs to be modified to provide the tests with access to data produced by Terraform

@andrewkroh that's a [drFT PR](https://github.com/elastic/beats/pull/32774) from @v1v that tries to do that
