### ISSUE TITLE
filebeat: improve debug logging in udp/tcp inputs

### ISSUE THREAD

**Issue by efd6** [elastic/beats#34060]
While working on a customer issue in filebeat relating to the udp input I noticed that this input does very little debug logging. Examples of this are that not all transitions are logged during execution and details of the address/port are not logged making it difficult to differentiate what is logged when more than one port or address is being listened on.

It would be good to improve this situation and it may be worth looking over the other inputs to check how well useful information is being logged in them as well.

**Comment by aleksmaus** [comment]
> Examples of this are that not all transitions are logged during execution and details of the address/port are not logged making it difficult to differentiate what is logged when more than one port or address is being listened on.

This seems like a pretty old ticket.
Just tested with TCP input, and it includes the the source and destination addresses and ports now:
```
{"log.level":"debug","@timestamp":"2024-09-30T15:40:28.017-0400","log.logger":"tcp","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/inputsource/common/streaming.(*Listener).handleConnection","file.name":"streaming/listener.go","file.line":194},"message":"New client connection.","service.name":"filebeat","address":"localhost:32001","remote_address":"127.0.0.1:49748","active_clients":1,"ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2024-09-30T15:40:28.018-0400","log.logger":"tcp","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/inputsource/common/streaming.(*Listener).handleConnection.func2","file.name":"streaming/listener.go","file.line":197},"message":"Client disconnected.","service.name":"filebeat","address":"localhost:32001","remote_address":"127.0.0.1:49748","active_clients":0,"ecs.version":"1.6.0"}
```

What else is missing?

**Comment by efd6** [comment]
I think that I was probably thinking of [in here](https://github.com/elastic/beats/blob/5e989b8742fa37b89efc373d6466991b392835ad/filebeat/input/tcp/input.go#L112) and [in here](https://github.com/elastic/beats/blob/5e989b8742fa37b89efc373d6466991b392835ad/filebeat/input/udp/input.go#L102). Could also include [in here](https://github.com/elastic/beats/blob/5e989b8742fa37b89efc373d6466991b392835ad/filebeat/input/unix/input.go#L105). Basically logging the network metadata and the data len.

**Comment by aleksmaus** [comment]
Something like this then:

```
{"log.level":"debug","@timestamp":"2024-09-30T20:41:02.152-0400","log.logger":"input.tcp","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/tcp.(*server).Run.func1","file.name":"tcp/input.go","file.line":112},"message":"Data received","service.name":"filebeat","id":"FEAD914EAB357583","host":"localhost:32001","bytes":7,"remote_address":"127.0.0.1:52756","truncated":false,"ecs.version":"1.6.0"}
```

```
{"log.level":"debug","@timestamp":"2024-09-30T20:42:39.869-0400","log.logger":"input.udp","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/udp.(*server).Run.func1","file.name":"udp/input.go","file.line":102},"message":"Data received","service.name":"filebeat","id":"5CF62520E29C9FC3","host":"localhost:32001","bytes":8,"remote_address":"127.0.0.1:52667","truncated":false,"ecs.version":"1.6.0"}
```

```
{"log.level":"debug","@timestamp":"2024-09-30T20:45:22.175-0400","log.logger":"input.unix","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/unix.(*server).Run.func1","file.name":"unix/input.go","file.line":105},"message":"Data received","service.name":"filebeat","id":"A41E47DC48C253F1","path":"/Users/amaus/filebeat.sock","bytes":7,"ecs.version":"1.6.0"}
```

**Comment by efd6** [comment]
Yeah, I think that's good.
