### ISSUE TITLE
Nil reference on agent policy change

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#34137]
When trying to reproduce reopened elastic/elastic-agent#1926 i encountered occasional nil reference here:
```
Unit state changed log-default-logfile-system-dfb73c57-14fc-4724-83d7-3b34fabed84a (STARTING->FAILED): [output unit has no config]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1049cb690]
goroutine 2182 [running]:
github.com/elastic/beats/v7/x-pack/metricbeat/cmd.metricbeatCfg(0x0, 0xc001282968?)
github.com/elastic/beats/v7/x-pack/metricbeat/cmd/agent.go:25 +0x50
github.com/elastic/beats/v7/x-pack/libbeat/management.(*TransformRegister).Transform(0x5?, 0x19?, 0x200000002?)
github.com/elastic/beats/v7/x-pack/libbeat/management/generate.go:60 +0x103
github.com/elastic/beats/v7/x-pack/libbeat/management.generateBeatConfig(0xc001697190?, 0xc001282a98?)
github.com/elastic/beats/v7/x-pack/libbeat/management/generate.go:232 +0x26
github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).reloadInputs(0xc000a23440, {0xc00028da20, 0x1, 0x0?})
github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:540 +0x155
github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).reload(0xc000a23440, 0xc001282da8?)
github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:450 +0x56b
github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).unitListen(0xc000a23440)
github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:379 +0x405
created by github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).Start
github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:178 +0x116
``` 

this resulted in agent reporting not healthy with `1 or more components/units in a failed state`

**Comment by cmacknz** [comment]
This seems to mostly affect the monitoring metricbeat instance with the `beat/metrics` input type.

For whatever reason it is getting an expected input and output configuration that is `nil` when the output type changes.

**Comment by cmacknz** [comment]
What is happening here is that we are getting a UnitExpected message where both the input and output configs are `nil` but the state is Healthy. Something is definitely wrong here, I'm not sure which part of the system the problem is in though.

It does seem to self-correct though.

**Comment by cmacknz** [comment]
It appears to be possible that the agent will send the units with `nil` configurations at startup. I suspect it is sending the log level before any other information is available.

Example message from dumping out the contents of the `CheckinExpected` message on the Beat side when this happens:
```json
{"log.level":"info","@timestamp":"2022-12-29T01:36:05.733Z","message":"CheckinExpected: units:{id:\"http/metrics-monitoring\"  type:OUTPUT  state:HEALTHY  config_state_idx:2  log_level:INFO}  units:{id:\"http/metrics-monitoring-metrics-monitoring-agent\"  state:HEALTHY  config_state_idx:1  log_level:INFO}  agent_info:{id:\"d8a450ce-b83e-4d99-8b35-829e48764dbe\"  version:\"8.6.0\"  snapshot:true}","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"http/metrics-monitoring","type":"http/metrics"},"ecs.version":"1.6.0"}
```

**Comment by cmacknz** [comment]
This is often causing a second restart of the Beats after they restart to apply an output change, resulting in Beats that are not running for up to 20s with the current process restart timeout.

**Comment by cmacknz** [comment]
I think the root of this issue is that when a process started by the agent exits, the agent itself isn't resetting the last observed unit states causing it to send CheckinExpected messages as if the process didn't just exit and was in sync with the agent.

We could equivalently work around this on the Beat side but really this should be properly detected as an error.

**Comment by cmacknz** [comment]
Something like this in the elastic agent client_v2.go implementation seems to protect from it (needs a lot more testing):

```diff
@@ -376,15 +379,19 @@ func (c *clientV2) syncUnits(expected *proto.CheckinExpected) {
                unit := c.findUnit(agentUnit.Id, UnitType(agentUnit.Type))
                if unit == nil {
                        // new unit
-                       unit = newUnit(agentUnit.Id, UnitType(agentUnit.Type), UnitState(agentUnit.S
tate), UnitLogLevel(agentUnit.LogLevel), agentUnit.Config, agentUnit.ConfigStateIdx, c)
-                       c.units = append(c.units, unit)
-                       c.unitsCh <- UnitChanged{
-                               Type: UnitChangedAdded,
-                               Unit: unit,
+                       if agentUnit.Config == nil {
+                               unit = newUnit(agentUnit.Id, UnitType(agentUnit.Type), UnitState(agentUnit.State), UnitLogLevel(agentUnit.LogLevel), agentUnit.Config, agentUnit.ConfigStateIdx, c)
+                               c.units = append(c.units, unit)
+                               c.unitsCh <- UnitChanged{
+                                       Type: UnitChangedAdded,
+                                       Unit: unit,
+                               }
                        }
```

It doesn't really make sense to add a unit with no configuration (at least currently) so this is a simple way to hide the panic. I still think the right fix is on the agent side, this was just simple to test and confirm as a possible way to avoid the panic.

**Comment by cmacknz** [comment]
I should note that I observe this panic happening every time I change the agent output at all. This is 100% reproducible behaviour.

**Comment by cmacknz** [comment]
The agent appears to be behaving properly in this situation. I think the nil config is coming in in the Beat side of the V2 client somehow.

**Comment by cmacknz** [comment]
What is happening is that the agent is send an expected state of STARTING to the Beat with a configIdx set properly but the configuration set to `nil`.

There is then another checkin briefly after this where the expected state of HEALTHY is set with the actual config, but the same config indexes. So the Beat thinks it has the latest config but it really doesn't.

I think this actually a bug in the agent, it shouldn't be sending the STARTING state to the Beat at all.

The unit debounce on the Beat side is preventing the Beat from trying to reload with just the starting state, which would at least report an error:

https://github.com/elastic/beats/blob/75ebd50e5d6a87eff626a502d63a8360a6c5cf00/x-pack/libbeat/management/managerV2.go#L423-L427

**Comment by cmacknz** [comment]
Closed with https://github.com/elastic/elastic-agent/pull/2036
