### ISSUE TITLE
Metricbeat fails to start if kibana module is down

### ISSUE THREAD

**Issue by CedricP-AM** [elastic/beats#34135]
### Summary
`node_rules`, `node_actions`, `cluster_rules` and `cluster_actions` metricsets include [http calls to Kibana in their constructor](https://github.com/elastic/beats/blob/main/metricbeat/module/kibana/node_rules/node_rules.go#L62-L71). It appears that metricsets are initialized during process startup and if the Kibana instance targeted by the module is unavailable when starting metricbeat, the calls will return an error shutting down the process early.

We should move these http calls to the metricsets [Fetch method](https://github.com/elastic/beats/blob/main/metricbeat/module/kibana/node_rules/node_rules.go#L82) so that an unavailable kibana doesn't prevent metricbeat from starting, and instead have data collection retried on each interval like other modules (ie elasticsearch/logstash).

### Acceptance criteria
- unreachable kibana does not stop the metricbeat process from starting
- metricsets are continuously called on configured interval even if the kibana is unreachable

---

### Original bug report

- Version: 8.5.0
- Operating System: CentOS 7.6
- Steps to Reproduce: 

I assume that we have got an Elasticsearch cluster instance up and that Kibana is already installed and running fine on the local machine.

**Download and install Metricbeat** 8.5.0 RPM file.
Configure output in metricbeat.yml : `output.elasticsearch.hosts: ["http://x.x.x.x:9200"]`
Enable kibana-xpack module : `metricbeat modules enable kibana-xpack`
Start the service : `systemctl start metricbeat`
=> Check that everything is working fine

**Stop Kibana** : `systemctl stop kibana`
=> Metricbeat displays error messages in the log file but this is normal. Everything is fine.
> {"log.level":"error","@timestamp":"2022-12-28T15:40:58.371+0100","log.origin":{"file.name":"module/wrapper.go","file.line":256},"message":"Error fetching data for metricset kibana.stats: error making http request: Get \"http://localhost:5601/api/status\": dial tcp [::1]:5601: connect: connection refused","service.name":"metricbeat","ecs.version":"1.6.0"}

**Restart Metricbeat** : `systemctl restart metricbeat`
**=> Metricbeat fails to start with this error message** :
> {"log.level":"error","@timestamp":"2022-12-28T15:41:59.327+0100","log.origin":{"file.name":"instance/beat.go","file.line":1056},"message":"Exiting: 4 errors: error making http request: Get \"http://localhost:5601/api/status\": dial tcp 127.0.0.1:5601: connect: connection refused; error making http request: Get \"http://localhost:5601/api/status\": dial tcp [::1]:5601: connect: connection refused; error making http request: Get \"http://localhost:5601/api/status\": dial tcp [::1]:5601: connect: connection refused; error making http request: Get \"http://localhost:5601/api/status\": dial tcp [::1]:5601: connect: connection refused","service.name":"metricbeat","ecs.version":"1.6.0"}

I tried with the Logstash module and can't reproduce the issue : Metricbeat starts even if Logstash process is down.
It seems that there is something special with the Kibana module.

**This is quite annoying that Metricbeat fails to start when the Kibana module is enabled and Kibana process is down.
What do you think ?**

**Comment by archoversight** [comment]
This is frustrating when using metric beat in a docker-compose setup because Kibana doesn't have a valid healthcheck endpoint to set up a healthcheck to make sure Kibana is ready to serve before starting up metric beat.

**Comment by hendry-lim** [comment]
The same happens on `8.6.2`. Metricbeat will exit if we have `kibana` module enabled but unable to connect to Kibana. There seems to be a behaviour change compared to previous versions, where it would continue running.

**Comment by archon810** [comment]
I just arrived here after hitting the issue in our setup. This used to work in v7, but in v8, which we upgraded to recently, restarting kibana and then restarting metricbeat, like so:
```
systemctl restart elasticsearch && systemctl restart kibana && systemctl restart metricbeat && systemctl restart auditbeat && systemctl restart filebeat
```
results in metricbeat dying with the following right away, without waiting any number of seconds to retry:
```
{"log.level":"error","@timestamp":"2023-03-28T14:34:32.944-0700","log.origin":{"file.name":"instance/beat.go","file.line":1071},"message":"Exiting: 4 errors: error making http request: Get \"http://localhost:5601/api/status\": dial tcp 127.0.0.1:5601: connect: connection refused; error making http request: Get \"http://localhost:5601/api/status\": dial tcp 127.0.0.1:5601: connect: connection refused; error making http request: Get \"http://localhost:5601/api/status\": dial tcp 127.0.0.1:5601: connect: connection refused; error making http request: Get \"http://localhost:5601/api/status\": dial tcp 127.0.0.1:5601: connect: connection refused","service.name":"metricbeat","ecs.version":"1.6.0"}
```

Note that neither filebeat nor auditbeat suffer from this issue. This feels like a regression bug.

**Comment by klacabane** [comment]
> This feels like a regression bug.

This behavior was introduced by [this change](https://github.com/elastic/beats/pull/29899) in 8.3. The change adds new metricsets that make http calls to Kibana in their constructor ([node_rules example](https://github.com/elastic/beats/blob/main/metricbeat/module/kibana/node_rules/node_rules.go#L51-L77)), and these constructors are probably called synchronously during metricbeat startup and crash the process before it completes its initialization. Removing the relevant calls from the metricset constructors fixes the issue, allowing metricbeat to correctly boot and the retrying logic to execute.

I'll update the issue description with findings and put that bug on our board for the next release

**Comment by archon810** [comment]
Fantastic, thank you for the triage, @klacabane.
