### ISSUE TITLE
[Stack Monitoring] Kibana log showing `field [json] doesn't exist` in `error.message` field

### ISSUE THREAD

**Issue by crespocarlos** [elastic/beats#34210]
## Summary 

A [change](https://github.com/elastic/beats/pull/33236) was introduced to Kibana log ingest pipeline, to fix a problem in which the pipeline was not considering fields included in the module configuration.

After this change, if a user sets` json.keys_under_root` is `true` in the module configuration, it will make the pipeline fail.

```yml
 - module: kibana
    log:
      enabled: true
      var.paths:
        - PATH_TO/kibana-json*.log
      input:
        json.keys_under_root: true -> breaks it
```

![Image](https://user-images.githubusercontent.com/2767137/211285682-c2255da0-55ce-45f9-acce-f4150f29c4ec.png)

### Details
This happens because:
- If ` json.keys_under_root: true` is present in the module configuration, it will move all attributes present in `message` to the object root 
- By the time filebeat tries to [put all attributes](https://github.com/crespocarlos/beats/blob/3028b52ca7b74ba18798893f0071465b4cb3a0a9/filebeat/module/kibana/log/config/log.yml#L10) from `message` into  an object named `json`, `message` will already be empty
- When filebeat [makes the decision](https://github.com/crespocarlos/beats/blob/3028b52ca7b74ba18798893f0071465b4cb3a0a9/filebeat/module/kibana/log/ingest/pipeline.yml) of which pipeline to run, `json` is empty. so it will default to `pipeline-7` (causing ECS formatted logs to fail)

**Side note:** even with the `error.message` the error mentioned, Logs UI will look OK, because the log ingested is ECS formatted.

![Image](https://user-images.githubusercontent.com/2767137/211286348-6b47e538-1c2a-4535-9f6a-dfbb4e8c1f8e.png)

### Acceptance criteria

- The pipeline should work, even with `json.keys_under_root: true` in the module configuration.

**Comment by fludo** [comment]
Do you have any progress regarding this issue ? 
We are waiting for it on a case in elastic cloud: https://support.elastic.co/cases/5008X00002LWDXZQA5

Regards

**Comment by crespocarlos** [comment]
@fludo a PR has been opened to address this issue.
