### ISSUE TITLE
[Packetbeat]: Packetbeat service is not starting and an error occurs on running `Start-Service` command.

### ISSUE THREAD

**Issue by ghost** [elastic/beats#34272]
**Kibana version:**  8.7-SNAPSHOT kibana cloud environment

**Host OS and Browser version:** Windows, All

**Describe the bug:**
Packetbeat service is not starting and an error occurs on running installation command.

**Build details:**
```
VERSION: 8.7-SNAPSHOT Kibana cloud environment
BUILD: 59793
COMMIT: 832a128e2aae7d3a61a6df48779fe03126b30308
```
**Preconditions:**
1. 8.7-SNAPSHOT kibana cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Now, Navigate to Program Files\packetbeat-8.7.0-SNAPSHOT-windows-x86_64 
3. Run packetbeat installation command.
```
.\install-service-packetbeat.ps1
.\packetbeat.exe setup
 Start-Service packetbeat
```
5. Observe that packetbeat service is not starting and an error occurs on running `Start-Service` command.

**Screenshot:**
![Annotation 2023-01-16 142734](https://user-images.githubusercontent.com/84007952/212637514-6b2238dc-037c-4c7b-87c3-5bdddb2d90f9.jpg)

**NOTE:** 
The issue is reproducible on multiple machines.

**Comment by samratbhadra-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by efd6** [comment]
@samratbhadra-qasource Can you provide packetbeat logs for this. Also, would you mind changing the OS constraints in the issue from "All" to "Windows".

**Comment by samratbhadra-qasource** [comment]
Hi @efd6

Apologies for missing to update the OS constraints earlier. We have updated the details in the issue to Windows.
Further, please find the required packetbeat logs in attached file.

**[logs.zip](https://github.com/elastic/beats/files/10432190/logs.zip)**

Kindly let us know if anything else is required from our end.

Thanks!

**Comment by efd6** [comment]
@samratbhadra-qasource Unfortunately there is no indication of any failure in the log provided. Is that the entirety of the logs from an attempt to start the service?

**Comment by martinscholz83** [comment]
Looks like an permission issue. Can you check what permission are set for the target folder and check in ServiceControlManager (services.msc) under what user account the service is running. You could try to install the service from a different location then `C:\Program Files\...`. Try with a folder under you user account.

**Comment by karanbirsingh-qasource** [comment]
Hi @martinscholz83 

Thanks for looking into the issue.

We have re-validated the issue on `8.7.0 BC1` and found the issue to fixed now ✔️ . Now we are able to start the packet beat service.

**Build Details:**
```
Version: 8.7.0-BC1
Commit: d3b239d76aa04f073836f6100782134ac86887e2
Build: 60614
```

**Screen-Shot**

![image](https://user-images.githubusercontent.com/59917825/218648395-142da8cc-40c4-4372-92b3-7b89b9a84669.png)

![image](https://user-images.githubusercontent.com/59917825/218648661-fd98e7ea-b4e0-448d-858f-fed6563722b8.png)


Hence we are closing this issue and adding "QA:Validated" tag to it.

thanks !!
