### ISSUE TITLE
[filebeat/o365audit] Duplicate events sent under certain conditions

### ISSUE THREAD

**Issue by taylor-swanson** [elastic/beats#34304]
Seen in this SDH: https://github.com/elastic/sdh-beats/issues/2921

Filebeat version: 8.4.3
Input: o365audit (beta)

It was observed in the filebeat logs that the last event of the previous response was being included again in the current response from the O365 Management API. This may be an issue with the O365 API in that particular case, but there should be logic in the input to skip already seen events. This doesn't appear to be working, though, as filebeat will process and forward the duplicate event. In the O365 integration, the pipeline wasn't setting the `_id` field, so Elasticsearch would index the duplicate event.

A workaround is being addressed in elastic/integrations#5046 to add a fingerprint processor so `_id` can be set, preventing the duplicate event from being indexed.

It is also being proposed that the integration switch to using either the httpjson or cel input in elastic/integrations#5045. Since this input is beta and it is more likely that it will be slated for deprecation/removal, it may only be addressed in the integration changes.

**Comment by efd6** [comment]
@taylor-swanson Are you happy that elastic/integrations#6621 and elastic/integrations#5047 together have closed this?

**Comment by taylor-swanson** [comment]
@efd6, seems like those two issues would address the problem. If we're not seeing it anymore, I'm good with this closing.
