### ISSUE TITLE
[Winlogbeat] `failed to parse field [winlog.event_data.Id] of type [keyword] ` when id contains `.`

### ISSUE THREAD

**Issue by narph** [elastic/beats#34345]
Running Winlogbeat on  other language OS's (in this case Spanish).

EX message 

```
"message": "CommandInvocation(Get-Date): \"Get-Date\"\n\n\nContexto:\n Gravedad = Informational\n Nombre de host = ConsoleHost\n Versión de host = 5.1.19041.1320\n Id. de host = 56995afd-2444-424e-871c-4c5513731a3b\n Aplicación host = C:\\…
```

Each part \n Id. is being parsed into a field under a Id object that is prefixed with de
```
…\n Id. de host = 56…
…320\n Id. de espacio de ejecución = fc8f1c...\n Id. de canalización = 1\n Nombre…
…la\n Usuario conectado = \n Id. de shell = Microsoft.PowerShell\n\n\nDatos…

```
Becomes

 
                        "Id": {
                            " de host": "56995afd-2444-424e-871c-4c5513731a3b",
                            " de shell": "Microsoft.PowerShell",
                            " de espacio de ejecución": "fc8f1...",
                            " de canalización": "1"
                        },
causing
```
"failed to parse field [winlog.event_data.Id] of type [keyword] in document with id '0434AIABa-64rEwC2A60'.
```

Potential fault at line: https://github.com/elastic/beats/blob/89bcc33a9a90cbacceaa61fceec0e8d23073574c/winlogbeat/sys/winevent/maputil.go#L66 where id  gets parsed.

**Comment by andrewkroh** [comment]
In short, we should not use `mapstr.Put` because the key names contain dots. The dots imply nested objects in `Put`. Our mappings for `winlog.event_data.*` expect string values only (no objects). Instead we should write directly into the map (e.g. `h[k] = kv.Value`).

**Comment by efd6** [comment]
@narph Is the XML event that contains the example available to include in a test?
