### ISSUE TITLE
`harvester_limit` does not work as expected

### ISSUE THREAD

**Issue by belimawr** [elastic/beats#34342]
- Version: `main`, `8.6.0`, probably affects older versions as well
- Operating System: Linux

When `harvester_limit` is set, the limit is respected, but only `harvester_limit` files are ingested, the others are not ingested unless data is appended to them.

The problem seems to be related to two facts:
1. The startHarvester error is ignored according to the TastGroup configuration.
     https://github.com/elastic/beats/blob/69ebd98fc41aa268acd7f99c429a44f2833c8dd3/filebeat/input/filestream/internal/input-logfile/harvester.go#L147
    
    https://github.com/elastic/beats/blob/69ebd98fc41aa268acd7f99c429a44f2833c8dd3/filebeat/input/filestream/internal/input-logfile/input.go#L74

2. The file watcher is unaware of the harvester status and only send the "createEvent" once
    https://github.com/elastic/beats/blob/69ebd98fc41aa268acd7f99c429a44f2833c8dd3/filebeat/input/filestream/fswatch.go#L138-L211

Another thing to notice is lack of any log informing about harvesters not beings started. There is a log entry stating the harvester is starting, but no followup on its success/error.
https://github.com/elastic/beats/blob/69ebd98fc41aa268acd7f99c429a44f2833c8dd3/filebeat/input/filestream/internal/input-logfile/harvester.go#L145

## Workaround
Currently there is no workaround for filestream input, however the [log input](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html), even though deprecated, will work as expected when setting `harvester_limit`

**Comment by kakoni** [comment]
Ping @AndersonQ 
I just tried `8.12.1` version. 
I've set filestream as 
```
filebeat.inputs:
- type: filestream
  paths:
    - logs/logs*.log
  harvester_limit: 1
  close_timeout: 5s 
```

This will only pick up one file. If I change the type to `log` then this works as expected.

**Comment by AndersonQ** [comment]
> Ping @AndersonQ I just tried `8.12.1` version. I've set filestream as
> 
> ```
> filebeat.inputs:
> - type: filestream
>   paths:
>     - logs/logs*.log
>   harvester_limit: 1
>   close_timeout: 5s 
> ```
> 
> This will only pick up one file. If I change the type to `log` then this works as expected.

Hello @kakoni,

I see, I'd need some more information to understand it better. Could you open a bug for that and add more details about your setup? Like how many log files are there, is the 1st log file fully ingested? is there data being added to the log file that is ingested, could you provide logs and the full config from you test run. Even better could describe in details how to reproduce your setup?

CC: @pierrehilbert
