### ISSUE TITLE
[Filebeat] Improve documentation about file identifiers/device ID

### ISSUE THREAD

**Issue by belimawr** [elastic/beats#34418]
Filebeat by default uses a combination of inode and device ID to identify files on its registry, however in some cases the device ID can change during boot, leading to data duplication.

One of those cases is when using [LVM](https://en.wikipedia.org/wiki/Logical_Volume_Manager_%28Linux%29) according to [Red Hat Enterprise documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/logical_volume_manager_administration/lv#persistent_numbers).

One know workaround for that is to set the `file_identity` to `path` as described on our [documentation](https://www.elastic.co/guide/en/beats/filebeat/7.17/filebeat-input-filestream.html#filestream-file-identity).

This issue is about better document this issue when using LVM.

**Comment by pierrehilbert** [comment]
@karenzone: could you please add this to your backlog?

**Comment by geekpete** [comment]
Do the docs changes as part of https://github.com/elastic/beats/pull/35734 satisfy this docs requirement?

**Comment by belimawr** [comment]
> Do the docs changes as part of #35734 satisfy this docs requirement?

Maybe. This bit does help:
> Enable this option if you're experiencing data loss or data duplication due to unstable file identifiers provided by the file system.

However my original thinking was to be more explicit about it in the main file identity section, mentioning the LVM issue instead of just being a small note in the fingerprint.

**Comment by kilfoyle** [comment]
@belimawr  Sorry it took me so long to get to this!  Here's a PR for the docs change: https://github.com/elastic/beats/pull/37959

Please let me know if I understood things correctly. :-)
