### ISSUE TITLE
[Stack Monitoring] shard activity does not show total time for metricbeat data

### ISSUE THREAD

**Issue by klacabane** [elastic/beats#34427]
### Summary
Shard activity component expect `start_time_in_millis` and `total_time_in_millis` properties from the server to display the total time of a shard recovery. This works for legacy collector but metricbeat formats the start time in [a different shape](https://github.com/elastic/beats/blob/main/metricbeat/module/elasticsearch/index_recovery/data.go#L76-L82) and doesn't parse the total time at all (the field is however mapped in both the integration and the `.monitoring` mapping)

### AC
- total time property should be parsed in the [index_recovery metricset](https://github.com/elastic/beats/blob/main/metricbeat/module/elasticsearch/index_recovery/data.go#L35)
- stack monitoring api should return a common response schema, whether the data in coming from metricbeat or legacy collector

<img width="990" alt="Screenshot 2023-01-30 at 22 52 44" src="https://user-images.githubusercontent.com/5239883/215607530-4eb90bc3-3d2f-4917-87aa-6261963e08ce.png">

**Comment by miltonhultgren** [comment]
An update on this: 
The Integration and X-Pack Metricbeat mappings have the total_time field but not the alias to the Internal Collection field, so we'll need to add that, I still need to check if the Metricbeat mappings have it or not. 

Then we'll need to make the Metricset pass that data along as well and finally update the SM UI code to read from the right fields (today it tries to read from the legacy format for the Metricbeat documents).

**Comment by MakoWish** [comment]
Please backport this. This was first reported in June 2022 when we had 8.2.0, and we are now on 8.6.2 with the issue still unresolved.

**Comment by MakoWish** [comment]
This is unfortunately still not fixed in 8.8.1. We just upgraded today and are quite disappointed this issue is more than a year old now and still not resolved.

**Comment by miltonhultgren** [comment]
@MakoWish I left you a [reply](https://github.com/elastic/kibana/issues/135041#issuecomment-1588748332) in the Kibana repo issue, let's debug there!

**Comment by MakoWish** [comment]
Just responded there. I have no idea why (nothing changed since yesterday), but it is now showing correctly.
