### ISSUE TITLE
Document new config options for decode_json_fields processor

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#3443]
For 5.2 there are two new config options for `decode_json_fields`, namely `target` and `overwrite_keys`. Here's a description of these new fields.

- `target` - Target specifies the field under which the decoded JSON shall be written. By default the decoded JSON object replaces the string field from which it was read. To merge the decoded JSON fields into the root of the event, specify target with an empty value (`target:`).
- `overwrite_keys` - This specifies whether or not keys that already exist in the event are overwritten by keys from the decoded JSON object. The default value is false.

Links

- New options in code: https://github.com/elastic/beats/blob/5.2/libbeat/processors/actions/decode_json_fields.go#L27-L29
- Current docs: https://www.elastic.co/guide/en/beats/filebeat/master/decode-json-fields.html

**Comment by dedemorton** [comment]
Closed by #3512
