### ISSUE TITLE
[Auditbeat Enhancement] Implement flat buffers & improve state persistence

### ISSUE THREAD

**Issue by ShourieG** [elastic/beats#34441]
**Enhancement:**

1) Improve existing schema structures for better maintainability with flat buffers.

2) Migrate schema to flat buffers, with binary saved in persistent datastore. 

3) This should be backwards compatible with current gob encoded persistence - (people upgrading to the new version would initially have auditbeat read from gob encoded storage, but then write it to a flatbuffer there onwards).

4) Improve State persistence - currently State is not persisted and tied to an instance of auditbeat running, but rather as a global state. This can cause various issue when multiple instances of auditbeat is running on the same system. This needs to be iterated upon. 

## Related issues
- Relates  #33765

**Comment by epixa** [comment]
I see the linked PR is merged, should this be closed as done?

**Comment by ShourieG** [comment]
@epixa yes we can close this, though point number 4 has not yet been addressed as it needs further discussions.
