### ISSUE TITLE
Metricbeat system module - collect total thread count

### ISSUE THREAD

**Issue by nimarezainia** [elastic/beats#34461]
We are exploring the use of Metricbeat to monitor our core servers and while we do like how it all comes together (especially with Kibana's dashboards) we've noticed that metricbeat is not collecting all the metrics we require

> The missing metric is total number of threads. This metric is an important one for our Operational Team to monitor, so would be great to know if there are plans for Metricbeat to collect it as part of system (or any other module) module?

**Comment by AndersonQ** [comment]
@nimarezainia after looking at the info here and in the enhancement request, I'd like to confirm if I'm understanding the scope correctly.

 - collect the `total thread count` **per process**
 - OS must have: linux
 - OS nice to have: mac, windows
 - do we need for containers and Kubernetes as well?
 
do we want to deliver it "per platform", that means a PR per platform, thus delivering value quicker or rather have a big PR with all possible platforms?

**Comment by nimarezainia** [comment]
> @nimarezainia after looking at the info here and in the enhancement request, I'd like to confirm if I'm understanding the scope correctly.
> 
>     * collect the `total thread count` **per process**
> 
>     * OS must have: linux
> 
>     * OS nice to have: mac, windows
> 
>     * do we need for containers and Kubernetes as well?
> 
> 
> do we want to deliver it "per platform", that means a PR per platform, thus delivering value quicker or rather have a big PR with all possible platforms?
> 
> cc: @pierrehilbert

thx @AndersonQ.

The scope:
- "total thread count per process" correct. the original fix was https://github.com/elastic/beats/pull/33614 which just addressed the total thread count.
- Should be applied everywhere so we are consistent across the board (again similar to the original fix)
- I don't think a PR per platform makes sense unless there are testing considerations that I am unaware of.
