### ISSUE TITLE
[Filebeat] GCS input - invalid printf format string

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#34492]
`%w` is not a valid format string for printf style strings. In `gcs/job.go` the `logp.Errorf` method is called with a format string containing `%w` to log an error, but it should use `%v`. Personally I would move to a fully structured log call like `j.log.Errorw("job encountered an error", "gcs.id", id, "error", err)`.

https://github.com/elastic/beats/blob/69ebd98fc41aa268acd7f99c429a44f2833c8dd3/x-pack/filebeat/input/gcs/job.go#L82

https://github.com/elastic/beats/blob/69ebd98fc41aa268acd7f99c429a44f2833c8dd3/x-pack/filebeat/input/gcs/job.go#L97

**Comment by GaurvKumar** [comment]
I have updated the change in my PR please someone review it.
PR: https://github.com/elastic/beats/pull/34619
