### ISSUE TITLE
[Heartbeat] Don’t run legacy Synthetics Integration monitors

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/beats#34506]
From 8.8 we need to stop running any legacy Elastic Synthetics Integration monitors (these are the ones created as browser - ZipURL/Inline, or Lightweight, prior to 8.6).

It’s not been possible to set up new monitors since 8.6 (and Zip URLs aren’t likely to have worked since 8.4) and we have [increased deprecation notices](https://github.com/elastic/kibana/issues/150287) in 8.7.  https://github.com/elastic/kibana/issues/137505 covers the deprecation needs in Kibana.

ACs:
- Heartbeat will no longer run any monitors that have been defined through the Synthetics Integration monitor configuration
  - Includes browser monitors (Zip URL and Inline), HTTP, TCP and ICMP
- Heartbeat will log an info message that the legacy monitor is not being run
- Heartbeat will write a document back to ES of the _failed_ run (i.e. it will appear as a _down_ monitor, so doesn't stop running quietly)
- Standalone Agent  configurations should continue to run (albeit we don't support it) (i.e. consider if `config_id` is the right detection mechanism)

**Comment by paulb-elastic** [comment]
@andrewvc @emilioalvap should we do the same for any browser based configs in the `heartbeat.yml`, in that we'll only run such monitors via Private Locations?

**Comment by emilioalvap** [comment]
Updated description to reflect `zip_url` and `local` sources will be removed [here](https://github.com/elastic/beats/pull/35429).

**Comment by paulb-elastic** [comment]
Moving to post 8.8

**Comment by paulb-elastic** [comment]
We're not going to actively do this now, but refer folks to the [supported configurations](https://www.elastic.co/guide/en/observability/current/synthetics-support-matrix.html), and the legacy integration is not one of them.
