### ISSUE TITLE
Feature: Alllow filtering out some filesystem types

### ISSUE THREAD

**Issue by guenhter** [elastic/beats#3459]
Feature Request
============

Original Thread: 
https://discuss.elastic.co/t/disk-space-metrics-wrong-when-working-with-overlay-mounts/72442

There is currently a problem when using overlay mounts. In such case, the mount point has the same disk size as the original disk. In Kibana, these sizes are summed what is not the reality.

It should be possible, to allow filtering out all such types to only transmit the real size of the disk.

**Comment by cv** [comment]
`sigar.FileSystem.SysTypeName` isn't being indexed, which makes it nearly impossible to filter out overlay filesystems. I added that field (in the PR above) so you could tell your query to drop whatever filesystem types you're not interested in.

**Comment by guenhter** [comment]
That's great!
