### ISSUE TITLE
Handle Panic error  : inconsistent import 

### ISSUE THREAD

**Issue by douaejeouit** [elastic/beats#3465]
I had this error when I tried to run the Make check for metricbeat. Actually, the problem occured when I upgraded the go version ( 1.6 -> 1.7 ). Appenrtly, I had some outdated packages compiled by two different versions of the compiler.
To resolve this issue, I had to remove the $GOPATH/pkg/  folder & then a recompiled everything with the 1.7  go compiler version. 
**What I **suggest** , if possible, is to hundle this error  instead of panic on failure !**

Here's the trace of the error : 

mb/mb_test.go:98: possible formatting directive in Error call
exit status 1
module/mysql/status/status_test.go:75: possible formatting directive in Error call
exit status 1
panic: inconsistent import:
        var time.UTC *time.Location
previously imported as:
        var UTC *time.Location
 [recovered]
        panic: inconsistent import:
        var time.UTC *time.Location
previously imported as:
        var UTC *time.Location

goroutine 1 [running]:
panic(0x674b20, 0xc420293550)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
go/types.(*Checker).handleBailout(0xc4200b41c0, 0xc42020b8d8)
        /usr/local/go/src/go/types/check.go:213 +0xae
panic(0x674b20, 0xc420293550)
        /usr/local/go/src/runtime/panic.go:458 +0x243
go/internal/gcimporter.(*importer).declare(0xc420298a90, 0x7f64a0, 0xc42032c370)
        /usr/local/go/src/go/internal/gcimporter/bimport.go:175 +0x17c
go/internal/gcimporter.(*importer).obj(0xc420298a90, 0xfffffffffffffffc)
        /usr/local/go/src/go/internal/gcimporter/bimport.go:195 +0x1b4
go/internal/gcimporter.BImportData(0xc420013020, 0xc4202dc000, 0x39d40, 0x3fe00, 0xc42015eb11, 0x4, 0x0, 0x4, 0xc42028cab0, 0xc42020b098)
        /usr/local/go/src/go/internal/gcimporter/bimport.go:88 +0x390
go/internal/gcimporter.Import(0xc420013020, 0xc42015eb11, 0x4, 0x7ffcabf4f048, 0x12, 0xc420202fa0, 0x0, 0x0)

**Comment by ruflin** [comment]
As far as I understand this was a binary problem related to golang versions. Can you elaborate on why we should make a change for this in our code? How would this be beneficial?
