### ISSUE TITLE
Support pprof metricset for golang  programs

### ISSUE THREAD

**Issue by medcl** [elastic/beats#3466]
As we discussed today, golang’s performance tool `pprof` is very powerful tool for you to monitoring and export GO program's runtime performance, maybe we can add a `pprof` metricset module in Metricbeat, that said we can monitoring golang's runtime performance and do a long-term performance analysis, performance issue such as memory leak can be found quickly.

The `pprof` can provide too much information such as call graph or goroutine stacktrace, in Metricbeat, we may just focus the high level runtime metrics, such as:
- [ ] <del>CPU: utilization </del>
- [x] Heap: HeapAlloc, HeapSys, HeapObjects, HeapReleased, Sys, Sys-HeapReleased, StackSy
- [ ] Goroutine: num of goroutines
- [x] GC: GC time, GC count
- [ ] Some interesting calls: cgo calls, syscall.Read/Write, runtime.mallocgc

Once we found some potential performance issue from these metrics, we can then use some specify tools to investigate the problem. 

Relevant links:
[https://golang.org/pkg/runtime/#MemStats](https://golang.org/pkg/runtime/#MemStats)
[https://golang.org/pkg/net/http/pprof/](https://golang.org/pkg/net/http/pprof/)
[https://blog.golang.org/profiling-go-programs](https://blog.golang.org/profiling-go-programs)
[https://software.intel.com/en-us/blogs/2014/05/10/debugging-performance-issues-in-go-programs](https://software.intel.com/en-us/blogs/2014/05/10/debugging-performance-issues-in-go-programs)

**Comment by urso** [comment]
all but CPU utilization should be available. All the GC/Heap info are available via runtime.MemStats (already exposed via expvar "memstats").

expvar also exposes the command line used to start the process. This should be added as well, so it's more clear, which process is currently being monitored.

**Comment by medcl** [comment]
@urso i was thinking, in metricbeat, if  the pprof address user specified is a not local one, such as `http://another_remote_ip:6060/debug/pprof/`, there maybe a issue with CPU utilization, and for other info like heap or GC  i think should get from the `pprof` API, what's you opinion?

**Comment by ruflin** [comment]
I would also not get CPU for the moment as our recommendation is to install beats as local as possible. Assuming in the case of containers you need remote IP's we support docker and cgroups.

Can we start with memory related data which helps to find memory leaks? I think that could be quite useful.

**Comment by pbennett** [comment]
DataDog's agent supports pulling memstat data from expvar which is extremely handy.  It would be trivial to add the same to metricbeat.   It's independent of the pprof data - perhaps I should create another issue so it's not lost.

**Comment by ruflin** [comment]
@pbennett I think the memstat data would be quite a good starting point. So no need to open a new issue I think :-)

**Comment by medcl** [comment]
`expvar` seems to be more general purpose, like `jmx`, people can specify what they need to collect, i am +1 to create another `expvar` metricbeat module

**Comment by ruflin** [comment]
Closing this issue as we have a Golang module now.

@medcl Thanks for making this happen.
