### ISSUE TITLE
Metricbeat: “error getting group status: open /proc/<PID>/cgroup”

### ISSUE THREAD

**Issue by anaconda2196** [elastic/beats#34670]
OpenSearch v2.5.0

Running Metricbeat-oss (docker.elastic.co/beats/metricbeat-oss:7.10.2) seeing the following error in logs:

instance/metrics.go:285 error getting group status: open /proc/<PID>/cgroup: no such file or directory"

Using ref document - https://www.elastic.co/guide/en/beats/metricbeat/7.10/running-on-kubernetes.html

Any suggestions or pointers to resources would be very much appreciated.

cc @lalit-satapathy @klacabane @roshan-elastic @yug-elastic @fearful-symmetry

**Comment by anaconda2196** [comment]
Hello @fearful-symmetry 

What is also interesting is that metricbeat pushes the other ksm metrics (e.g. pod status, pod phase), but not the limits and requests. That is really odd.
Is there any dependency with cgroup error ?

**Comment by michel-laterman** [comment]
@anaconda2196, 7.10.x is no longer supported. Please upgrade to 7.17.9 if you wish to continue using the 7.x releases

**Comment by anaconda2196** [comment]
> @anaconda2196, 7.10.x is no longer supported. Please upgrade to 7.17.9 if you wish to continue using the 7.x releases

Does that mean if I want container metrics limits and requests Then I need to upgrade to Metricbeat 7.19.9?

kube-state-metrics v2.x and later no longer export metrics

kube_pod_container_resource_requests_cpu_cores
kube_pod_container_resource_requests_memory_bytes
kube_pod_container_resource_limits_cpu_cores
kube_pod_container_resource_limits_memory_bytes

I tried to backport the support from the metricbeat 7.15.x code base to 7.10.2, but it didn’t work out.

**Comment by anaconda2196** [comment]
> > @anaconda2196, 7.10.x is no longer supported. Please upgrade to 7.17.9 if you wish to continue using the 7.x releases
> 
> @michel-laterman Does that mean if I want container metrics limits and requests Then I need to upgrade to Metricbeat 7.19.9?
> 
> kube-state-metrics v2.x and later no longer export metrics
> 
> kube_pod_container_resource_requests_cpu_cores kube_pod_container_resource_requests_memory_bytes kube_pod_container_resource_limits_cpu_cores kube_pod_container_resource_limits_memory_bytes
> 
> I tried to backport the support from the metricbeat 7.15.x code base to 7.10.2, but it didn’t work out.

cc 

@MichaelKatsoulis - I read your comments on https://github.com/elastic/beats/issues/21520 related to this issue.
Can you guide me ?
