### ISSUE TITLE
kibana/stats metricset will initialize a new CLI handler with every fetch, potentially spamming the logs

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#34682]
The `kibana/stats` metricset will call an `init()` function with every `Fetch()` call:

https://github.com/elastic/beats/blob/b5c00fd2346b19ee8f7dedbd0aab847095a89ddd/metricbeat/module/kibana/stats/stats.go#L70-L106

In cases where `ssl.verification_mode` has been set to `none`, this frequent `init()` call, which in turn calls `helper.NewHTTP(m.BaseMetricSet)` , will spam the logs with a `SSL/TLS verifications disabled`, which isn't great. Ideally the HTTP helpers should be called once in `New()`, and not every time in `Fetch()`.

**Comment by miltonhultgren** [comment]
@smith Can you provide some guidance on the priority for this?

**Comment by lucabelluccini** [comment]
Milton I've shared some feedback to Nathan regarding this issue.
