### ISSUE TITLE
[Winlogbeat] Crashes with an exception when shipping Forwarded Events

### ISSUE THREAD

**Issue by pfzim** [elastic/beats#34705]
Winlogbeat crashes with an exception when shipping Forwarded Events

A similar problem has been fixed in **telegraf**: https://github.com/influxdata/telegraf/issues/12328

```
winlogbeat.event_logs:
  - name: ForwardedEvents
    tags: [forwarded]
```

```
Exception 0xc0000005 0x1 0x0 0x7ffea479e254
PC=0x7ffea479e254

runtime.cgocall(0xc2c3e0, 0xc0001812c0)
	runtime/cgocall.go:157 +0x4a fp=0xc000c90dd0 sp=0xc000c90d98 pc=0xbc458a
syscall.SyscallN(0x1e?, {0xc000c90e68?, 0x0?, 0xc000a151a0?})
	runtime/syscall_windows.go:556 +0x109 fp=0xc000c90e48 sp=0xc000c90dd0 pc=0xc27429
syscall.Syscall9(0xc000a151a0?, 0x1?, 0x1?, 0xc000c90f10?, 0x159a26f?, 0xc120c9?, 0x365f620?, 0xc00018e290?, 0xc000c90f28?, 0x0, ...)
	runtime/syscall_windows.go:506 +0x78 fp=0xc000c90ec0 sp=0xc000c90e48 pc=0xc27138
github.com/elastic/beats/v7/winlogbeat/sys/wineventlog._EvtFormatMessage(0xc00018e290?, 0xc000f42778?, 0x0, 0x0, 0x0?, 0x1, 0x0, 0xc000d1c340?, 0x1e?)
	github.com/elastic/beats/v7/winlogbeat/sys/wineventlog/zsyscall_windows.go:132 +0xe5 fp=0xc000c90f58 sp=0xc000c90ec0 pc=0x15aecc5
github.com/elastic/beats/v7/winlogbeat/sys/wineventlog.evtFormatMessage(0xc000b517c0?, 0x1e?, 0x0?, {0x0?, 0x0, 0x1?}, 0x1?)
	github.com/elastic/beats/v7/winlogbeat/sys/wineventlog/format_message.go:82 +0x9e fp=0xc000c91028 sp=0xc000c90f58 pc=0x159f43e
github.com/elastic/beats/v7/winlogbeat/sys/wineventlog.getMessageString(0xc000d1c340?, 0x4000?, 0x4000?, {0x0?, 0xc2703b?, 0x100fea1c9a970?})
	github.com/elastic/beats/v7/winlogbeat/sys/wineventlog/format_message.go:58 +0x45 fp=0xc000c91070 sp=0xc000c91028 pc=0x159f2e5
github.com/elastic/beats/v7/winlogbeat/sys/wineventlog.getMessageStringFromHandle(...)
	github.com/elastic/beats/v7/winlogbeat/sys/wineventlog/format_message.go:34
github.com/elastic/beats/v7/winlogbeat/sys/wineventlog.Message(0x4000?, {0xc0005f8000?, 0x3ef6e40?, 0xc0003e5980?}, 0xc000c91168)
	github.com/elastic/beats/v7/winlogbeat/sys/wineventlog/wineventlog_windows.go:274 +0x12e fp=0xc000c91140 sp=0xc000c91070 pc=0x15ad40e
github.com/elastic/beats/v7/winlogbeat/eventlog.newWinEventLog.func5(0xc0007db6c0?)
	github.com/elastic/beats/v7/winlogbeat/eventlog/wineventlog.go:568 +0x55 fp=0xc000c91188 sp=0xc000c91140 pc=0x22f3635
github.com/elastic/beats/v7/winlogbeat/eventlog.(*winEventLog).Read(0xc0007db6c0)
	github.com/elastic/beats/v7/winlogbeat/eventlog/wineventlog.go:333 +0x792 fp=0xc000c917e8 sp=0xc000c91188 pc=0x22f1592
github.com/elastic/beats/v7/winlogbeat/beater.(*eventLogger).run(0xc0003e15c0, 0xc00020ccc0, {0x3f14170?, 0xc0001bd340}, {{0xc00057d780, 0xf}, 0x18c5e4, {0x35f58810, 0xedb90461e, 0x0}, ...}, ...)
	github.com/elastic/beats/v7/winlogbeat/beater/eventlogger.go:154 +0x9f2 fp=0xc000c91ed8 sp=0xc000c917e8 pc=0x22f7f12
github.com/elastic/beats/v7/winlogbeat/beater.(*Winlogbeat).processEventLog(0x2020200a35313437?, 0x7561666564202020?, 0x646c6569665f746c?, {{0xc00057d780, 0xf}, 0x18c5e4, {0x35f58810, 0xedb90461e, 0x0}, {0xc00007a150, ...}}, ...)
	github.com/elastic/beats/v7/winlogbeat/beater/winlogbeat.go:196 +0xb3 fp=0xc000c91f70 sp=0xc000c91ed8 pc=0x22fa393
github.com/elastic/beats/v7/winlogbeat/beater.(*Winlogbeat).Run.func2()
	github.com/elastic/beats/v7/winlogbeat/beater/winlogbeat.go:164 +0x55 fp=0xc000c91fe0 sp=0xc000c91f70 pc=0x22fa115
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc000c91fe8 sp=0xc000c91fe0 pc=0xc2ab21
created by github.com/elastic/beats/v7/winlogbeat/beater.(*Winlogbeat).Run
	github.com/elastic/beats/v7/winlogbeat/beater/winlogbeat.go:164 +0x2df
```

Version: 8.6.2
Operating System: Windows Server 2022 Standard 21H2 20348.1487

**Comment by efd6** [comment]
@pfzim I understand that this will likely be a difficult question to answer since the beat crashes before any event can be emitted, but are you able to determine which event might have caused this issue (approach below).

Looking at the code this code path is only executed when an event with no message is found, as part of an event integrity salvage operation.

If you look at events on your host directly with the Windows Event Viewer, do you see any event without a message in the log stream immediately or shortly after the last successfully ingested log event?

**Comment by pfzim** [comment]
I don't know what message is causing the error here, but I can show an example message that caused a similar failure in telegraf: https://github.com/influxdata/telegraf/issues/12328#issuecomment-1341405323

There is also a solution to the same problem.

**Comment by efd6** [comment]
Thanks, yeah, I had a look at their issue and the approach they take to the fix.

The situation here is a little different even if the underlying Windows API call is crashing the same way. As far as I can see, the event there would not cause the same kind of crash with our code; you can see in the stack trace that you posted that the execution goes through `github.com/elastic/beats/v7/winlogbeat/eventlog/wineventlog.go:333` (context [here](https://github.com/elastic/beats/blob/9b77c2c135c228c2eedc310f6e975bb1a76169b1/winlogbeat/eventlog/wineventlog.go#L332-L338)) and calls an anonymous function (`l.message`). This closure is what calls `EvtFormatMessage` resulting in the exception, but that can't happen with the event in the telegraf comment because that event has a 'Message' field, "The Network Setup Service service entered the running state.", and `winevent.go:332` excludes those.

So I'm expecting some event that does not have a valid publisher handle, but doesn't have a 'Message' field. This seems unlikely, but here we are.

**Comment by pfzim** [comment]
_I'm sorry, my English is not very good._

Can you add some debug information to the output so we can see the EventId before the crash? How it was done in telegraf. Then we would definitely be able to know on which event it falls.

**Comment by efd6** [comment]
We can add debugging logs as an enhancement, but that unfortunately doesn't really help here since we are bound by release cycles. In the absence of this debug logging, I would look at the timestamp of the last ingested event from the provider that is failing, and then look at the logs using the event viewer to find the first (or first few) event(s) after that last known good event.

**Comment by pfzim** [comment]
@efd6 As I can see, the crash occurs on the following event:
![image](https://user-images.githubusercontent.com/6803907/234531822-9536d746-b319-4e3d-8a8b-31f8422ae794.png)
![image](https://user-images.githubusercontent.com/6803907/234531985-7d95eea1-03b7-4259-abd4-10a8d2b7e51a.png)
![image](https://user-images.githubusercontent.com/6803907/234532138-be29999d-0bc6-426a-8c04-e07a0cf879c9.png)
![image](https://user-images.githubusercontent.com/6803907/234532223-459ec8b9-1efe-41b1-abf0-c325e40b901f.png)

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-SharePoint Products-SharePoint Foundation" Guid="{6FB7E0CD-52E7-47DD-997A-241563931FC2}" /> 
  <EventID>6398</EventID> 
  <Version>15</Version> 
  <Level>1</Level> 
  <Task>12</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x4000000000000000</Keywords> 
  <TimeCreated SystemTime="2023-04-24T14:59:16.983840700Z" /> 
  <EventRecordID>1971750</EventRecordID> 
  <Correlation ActivityID="{385FACA0-8DD4-5072-4502-31532723D177}" /> 
  <Execution ProcessID="21020" ThreadID="17264" /> 
  <Channel>Application</Channel> 
  <Computer>sever.name.was.here</Computer> 
  <Security UserID="S-1-5-21-1576167569-1136612613-995515920-16396" /> 
  </System>
- <EventData>
  <Data Name="string0">Microsoft.Office.Server.UserProfiles.UserProfileImportJob</Data> 
  <Data Name="string1">4b0eda19-92fb-43f1-bf70-20047bafa28d</Data> 
  <Data Name="string2">Operation is not valid due to the current state of the object.</Data> 
  </EventData>
- <RenderingInfo Culture="en-US">
  <Message>The Execute method of job definition Microsoft.Office.Server.UserProfiles.UserProfileImportJob (ID 4b0eda19-92fb-43f1-bf70-20047bafa28d) threw an exception. More information is included below. Operation is not valid due to the current state of the object.</Message> 
  <Level>Critical</Level> 
  <Task>Timer</Task> 
  <Opcode>Info</Opcode> 
  <Channel>Application</Channel> 
  <Provider>Microsoft-SharePoint Products-SharePoint Foundation</Provider> 
  <Keywords /> 
  </RenderingInfo>
  </Event>
```

**Comment by efd6** [comment]
Thanks @pfzim. Just to clarify, if winlogbeat is crashing on this event, how are we seeing it in the index? Am I missing something?

![index](https://user-images.githubusercontent.com/6803907/234531822-9536d746-b319-4e3d-8a8b-31f8422ae794.png)

Does this event only happen when winlogbeat is running?

**Comment by pfzim** [comment]
@efd6 The event that failed is not in the index. Look closely at the time. He was able to transmit messages of the same type, but for some reason crash on a similar message at 17:58. Last message at 17:57.

**Comment by pfzim** [comment]
Another event where the application crashed.
![image](https://user-images.githubusercontent.com/6803907/234778414-98dd1505-59f3-424d-88f0-e33ff8d36063.png)
![image](https://user-images.githubusercontent.com/6803907/234778021-640c90d9-892d-4ec8-bc5c-6fd427c152ea.png)

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Kernel-Power" Guid="{331c3b3a-2005-44c2-ac5e-77220c37d6b4}" /> 
  <EventID>41</EventID> 
  <Version>6</Version> 
  <Level>1</Level> 
  <Task>63</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000400000000002</Keywords> 
  <TimeCreated SystemTime="2023-04-26T15:25:16.275958600Z" /> 
  <EventRecordID>98200</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="4" ThreadID="8" /> 
  <Channel>System</Channel> 
  <Computer>10-0013-3.domain.name.here</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <EventData>
  <Data Name="BugcheckCode">0</Data> 
  <Data Name="BugcheckParameter1">0x0</Data> 
  <Data Name="BugcheckParameter2">0x0</Data> 
  <Data Name="BugcheckParameter3">0x0</Data> 
  <Data Name="BugcheckParameter4">0x0</Data> 
  <Data Name="SleepInProgress">0</Data> 
  <Data Name="PowerButtonTimestamp">0</Data> 
  <Data Name="BootAppStatus">0</Data> 
  <Data Name="Checkpoint">0</Data> 
  <Data Name="ConnectedStandbyInProgress">false</Data> 
  <Data Name="SystemSleepTransitionsToOn">0</Data> 
  <Data Name="CsEntryScenarioInstanceId">0</Data> 
  <Data Name="BugcheckInfoFromEFI">false</Data> 
  <Data Name="CheckpointStatus">0</Data> 
  </EventData>
  </Event>
```

**Comment by efd6** [comment]
@pfzim Thank you for clarifying, my eyes are clearly not good enough.
