### ISSUE TITLE
[Heartbeat] [Docs] Clarify Synthetics needs a direct connection to ES (not through Logstash or Ingest Pipelines)

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/beats#34725]
Some users use Logstash as a mechanism for writing to Elasticsearch.  This can be for a variety of reasons, but ends up being an intermediary between producers of data such as Heartbeat, and Elasticsearch.

This is not supported by Heartbeat, which requires a direct connection to Elasticsearch as it needs a read connection (as well as writing result data).

Similarly, Ingest pipelines provide the ability to transform data, but the Synthetics and Uptime Kibana apps expect data to be complete, so there have been cases where Ingest pipelines cause problems that are difficult to troubleshoot.

Document:
* That Heartbeat requires a direct Elasticsearch connection. Logstash outputs are also not supported (and are specifically prevented).
  * Consider documenting some help that users may find useful for typical use cases why Logstash is being used (for example centralised writes to Elasticsearch).
* Not to configure Ingest pipelines that transform Heartbeat or Synthetics data

**Comment by thethirstyturtle** [comment]
We have a current case open with Elastic regarding this same problem. We tried to push the data through Logstash, but the heartbeat service won't even turn on.
