### ISSUE TITLE
IPFIX/Netflow interface name

### ISSUE THREAD

**Issue by DmitryTep** [elastic/beats#34727]
Good day.
Tell me, please, I collect netflow using filebeat.
There are fields
''''
"egress_interface" : 199,
"ingress_interface" : 277,
''''
Through SNMP, I found out which network interfaces correspond to these indexes.
How can I overwrite these values ​​on the described ones?

Perhaps it can be done somehow through
''''
"observer.ingress.interface.name": [
"eth0" ],
or
"egress_interface_name" : ***,
''''
If this is so, please tell me where exactly it is necessary to specify these parameters?
Thank you

**Comment by leweafan** [comment]
This is not a bug and not an issue and should not be posted here. As said in description questions should be posted on https://discuss.elastic.co/
