### ISSUE TITLE
Cover possible processor re-use with tests

### ISSUE THREAD

**Issue by rdner** [elastic/beats#34783]
**Describe the enhancement:**

We caught a high-impact bug recently https://github.com/elastic/beats/pull/34761 and we need to introduce some testing in order to prevent this bug from reappearing. Or even to make sure we've fixed all the occurrences.

It should be enough to:

* create a config with a processor
* configure a Filebeat pipeline
* create a pipeline client
* close it
* create another pipeline client and try to publish an event
* after https://github.com/elastic/beats/pull/34647 and before https://github.com/elastic/beats/pull/34761 this should return an error

also, before both changes calling `Close` twice would cause a panic on `add_kubernetes_metadata`.

The test should reproduce the issue on the old code before being accepted.

**Comment by cmacknz** [comment]
It would be good to pair this with https://github.com/elastic/beats/issues/34792, to identify why the Beat becomes non-functional and generates a seemingly infinite number of processing errors when a processor is reused so we can introduce a more graceful failure mode if this happens again.
