### ISSUE TITLE
Feature: add add_host_metadata similar to add_cloud_metadata but for self hosted environments

### ISSUE THREAD

**Issue by jakommo** [elastic/beats#3480]
In some use cases it could be beneficial to gather more information's on the sending side. 
E.g. get the source IP of the client sending the event.
While we already have `beat.hostname`, there are environments where this is not unique enough.
It's already possible to work around this by adding a custom field and using a environment variable with the IP as a value, but it's complicated when there are multiple interfaces and it needs to be deployed on a lot of (differently configured) hosts. 

Proposing to have something like [add_cloud_metadata](https://www.elastic.co/guide/en/beats/filebeat/master/add-cloud-metadata.html) but for self hosted environments, that hold additional information on the host sending the event.

**Comment by andrewkroh** [comment]
This seems related to this request https://github.com/elastic/beats/issues/4356 (system.info metricset request).

**Comment by jakommo** [comment]
@andrewkroh I think it's related but not the same.  https://github.com/elastic/beats/issues/4356 sounds more like reading those stats from the OS, while this issue was intended to get the IP of the interface sending the event. 

I could imagine that this would be none static, i.e. if one interface / network goes down and another interface / route is used, it should reflect that by tagging the events with that new interface IP. 

I saw this request a few times already, but mostly related to Filebeat. So maybe we should change the Label?

**Comment by ruflin** [comment]
I started some work here: https://github.com/elastic/beats/pull/5968

I changed the label to `libbeat` as this would be a processor in libbeat.

**Comment by urso** [comment]
Feature has been merged last year, plus 'beta' label has been removed recently.
