### ISSUE TITLE
Elastic Synthetic package will be installed before every check

### ISSUE THREAD

**Issue by denizco** [elastic/beats#34875]
We are currently implementing Synthetic Monitoring for a customer and we experienced an issue with the installation of the Elastic Synthetic NPM package before every check.

Environment:
- beats/elastic-agent-complete (official docker image) version 8.6.1 
  - The Docker image above contains `@elastic/synthetics@1.0.0-beta.38`
  - Docker image with Elastic Agent configured as private location
- A Linux VM which contains the Synthetic Project (customer tried both latest version and the `@elastic/synthetics@1.0.0-beta.38` when creating a project for test purposes)
  - Synthetic Monitoring project was created and pushed according to the guide (https://www.elastic.co/guide/en/observability/master/synthetics-get-started-project.html)

While checking the logs we noticed the @elastic/synthetics package will be installed before every check: 

![image](https://user-images.githubusercontent.com/9119894/226674479-b3344a54-87e2-466f-8d29-35a948891830.png)

We can see the installed files in the `/tmp` folder:

![image](https://user-images.githubusercontent.com/9119894/226674091-a807034b-d010-4bf1-a541-ca680fcab0a1.png)

package.json from the Synthetic Project:

```
{
  "name": "tour-005",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "push": "npx @elastic/synthetics push"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@elastic/synthetics": "1.0.0-beta.38"
  }
}
```

package.json from the installed synthetic nmp packages:

```
{
  "name": "project-journey",
  "private": true,
  "dependencies": {
    "@elastic/synthetics": "file:/usr/share/elastic-agent/.node/node/lib/node_modules/@elastic/synthetics"
  }
}
```

This is not desirable because of a couple of things. First of all it causes an overhead to each check, meaning that each check will take longer to complete. Additionally, there is no cleaning process for the installed package files. After a while, this will cause a storage problem.

**Comment by andrewvc** [comment]
I'm looking into this at the moment, but based on the log messages you posted it looks more like we aren't correctly cleaning up tmp folders rather than doing a re-install. The log line you snapshotted shows the suite being run, not the npm package being installed.

**Comment by denizco** [comment]
We were able to identify the issue because on customer's environment the installation of the package took more time than it would take on my own machine, because it is an "airtight" environment (see the error below). We could workaround that issue, but the npm package will still be installed before every check. 

![image](https://user-images.githubusercontent.com/9119894/227323960-5651d312-ae9f-4d45-903d-e97e937580e6.png)

Is it possible that more customers actually experience this issue (download & install the package before every check), but not notice because the installation process takes less time (~10s)?

**Comment by andrewvc** [comment]
@denizco can we get the complete log from the customer? At least say the few hundred lines before that screenshot? 

Additionally, it'd be helpful to confirm that they are only configuring monitors through the projects feature. It was previously possible to configure monitors directly in the fleet UI. Is it possible they still have any configured in that way?

**Comment by denizco** [comment]
@andrewvc Here is a complete log from heartbeat we generated today (we filtered by agent id):

[heartbeat-logs.json.zip](https://github.com/elastic/beats/files/11088704/heartbeat-logs.json.zip)

Yes, customer is configuring monitors through the projects feature. No monitors are configured via UI.
