### ISSUE TITLE
[Heartbeat] Lightweight monitors - Monitors with malformed params do not produce a summary document with error

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/beats#34926]
- Version: 8.8.0

I'm currently testing [lightweight params](https://github.com/elastic/kibana/pull/148634) using the dev service environment. 

While the feature is generally working well, I encountered some uncaught parsing errors. These errors will typically cause the param to be passed to the configuration value raw. For example
```
check.request.headers : { Authorization: 'Basic ${es_token}' }
```

While those errors have been addressed by making the Kibana code even more defense, I've noticed that when parameters are passed to heartbeat this way, the monitor does not run at all or report any errors. 

It would be helpful for heartbeat to produce a summary document with an error to provide debugging context to our users.

**Comment by emilioalvap** [comment]
Closing without action, not reproducible.
