### ISSUE TITLE
my log files are flooded with a message regarding redis.go 

### ISSUE THREAD

**Issue by CharlesJUDITH** [elastic/beats#35]
I have this message in my log file:

usr/bin/packetbeat[26848]: redis.go:482: Response from unknown transaction. Ignoring.

It's just a warning, so I think more help is welcome for log configuration in packetbeat.conf.

For now I comment redis lines in protocols section because right know I don't have transaction.

**Comment by hiteshmahajan** [comment]
Same issue :(

**Comment by ruflin** [comment]
For reference. Follow up in https://github.com/elastic/packetbeat/issues/384
