### ISSUE TITLE
Packetbeat - Support for subdomain in DNS question

### ISSUE THREAD

**Issue by gingerwizard** [elastic/beats#3503]
Its common to need the highest resolvable domain and sub domain for ML.  Currently this isn't provided by Packetbeat. A native painless integration is [here](https://github.com/elastic/prelert-legacy/pull/787/files#diff-a2703332b6e989ca2bbd7b2a0916cc7a)

Could we support this natively in Packetbeat or alternatively provide as a painless function @jdconrad .

**Comment by andrewkroh** [comment]
@gingerwizard Could you provide an example of a HRD. Like for www.amazon.co.uk what is the HRD?

**Comment by andrewkroh** [comment]
Is highest resolvable domain the same as the [effective top level domain](https://en.wikipedia.org/wiki/Public_Suffix_List) (eTLD) plus one label?

For `www.amazon.co.uk`:
eTLD=`co.uk`
eTLD+1=`amazon.co.uk`

For Packetbeat this information is reported in the [`dns.question.etld_plus_one`](https://www.elastic.co/guide/en/beats/packetbeat/current/exported-fields-dns.html#_dns_question_etld_plus_one) field. The data for determine the eTLD comes from https://publicsuffix.org/. We also report this info for the hostname that we reverse lookup in the [system socket](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-system-socket.html) metricset.

It would make sense IMO to turn this into a processor that can be applied to any field based on config.

**Comment by gingerwizard** [comment]
Ah thanks @andrewkroh. I should have noticed  `dns.question.etld_plus_one`. I would only propose we add the subdomain to the question field then. This is what we look for when we detect high entropy through DNS exfiltration.

**Comment by gingerwizard** [comment]
so a separate field with `name - dns.question.etld_plus_one`. Obviously minor now as easily achieved through a painless script.

**Comment by gingerwizard** [comment]
Im not sure domain is as simple as `name - dns.question.etld_plus_one` unfortunately.  For example, if the request is to the TLD we get the following:

```
"etld_plus_one": "outbrain.com.",
"name": "www.outbrain.com.",
```
