### ISSUE TITLE
[Filebeat] TCP/UDP input cause a panic on Linux under certain conditions

### ISSUE THREAD

**Issue by belimawr** [elastic/beats#35064]
- Version: `v8.7.0`, `main`
- Operating System: Linux

## Steps to Reproduce
1. Start Filebeat with UDP input (or any input that uses UDP, like syslog)
   ```yaml
   filebeat.inputs:
   - type: udp
     host: "localhost:9009"

   output.console:
     enabled: true
   ```
2. Wait for about a minute (no need to ingest any data), you'll see a panic
   ```
   panic: runtime error: index out of range [1] with length 0
   
   goroutine 62 [running]:
   github.com/elastic/beats/v7/filebeat/input/udp.procNetUDP({0xc0002b0980?, 0x1, 0x2})
           /home/tiago/devel/beats/filebeat/input/udp/input.go:271 +0x552
   github.com/elastic/beats/v7/filebeat/input/udp.(*inputMetrics).poll(0xc000458680, {0xc0002b0980, 0x1, 0x2}, 0x0?, 0xc00066e040)
           /home/tiago/devel/beats/filebeat/input/udp/input.go:242 +0xd1
   created by github.com/elastic/beats/v7/filebeat/input/udp.newInputMetrics
           /home/tiago/devel/beats/filebeat/input/udp/input.go:216 +0xa70
   ```

# The problem
The panic comes from the `procNetUDP` function that gathers some UDP metrics from `/proc/net/udp`:
https://github.com/elastic/beats/blob/a8dbc6c06381f4fe33a5dc23906d63c04c9e2444/filebeat/input/udp/input.go#L256-L288

It seems some times the data is on a format different than what the function expects.

# Workaround
Currently the only know workaround is to downgrade to `v8.6.2`.

**Comment by andrewkroh** [comment]
PR to fix: #35068 35068

**Comment by andrewkroh** [comment]
I found the same bug in the TCP input as well. Fixing it in #35074.

**Comment by mmguero** [comment]
Same for me. Was fixed in 8.7.1, broken again in 8.8.0.

**Comment by efd6** [comment]
The issue here is a typo in the param name to `containsUnspecifiedAddr` in the tcp package. The same error does not exist in the udp package. Sending a fix.

**Comment by mmguero** [comment]
Apologies if I'm just not looking in the right place, do you know if this fix is in the recent v8.8.1 release?

**Comment by jlind23** [comment]
@mmguero I don't think it is, it has been merged last week https://github.com/elastic/beats/pull/35637 so it missed the deadline.

**Comment by xseth03** [comment]
I'm having the same problem with version 8.8.1

**Comment by ebeahan** [comment]
@xseth03 This fix will be included in 8.8.2

**Comment by mussi** [comment]
panic stop ... but : 

```
Jul 21 10:56:07 n321p004875 filebeat[1650953]: {"log.level":"warn","@timestamp":"2023-07-21T13:56:07.936Z","log.logger":"input.tcp","log.origin":{"file.name":"tcp/input.go","file.line":299},"message":"failed to get tcp6 stats from /proc: /proc/net/tcp6 entry not found for [00000000FFFF00000000000000000000:283F]","service.name":"filebeat","id":"6EB4C102F4E0399A","host":"0.0.0.0:10303","ecs.version":"1.6.0"}
Jul 21 10:56:07 n321p004875 filebeat[1650953]: {"log.level":"warn","@timestamp":"2023-07-21T13:56:07.936Z","log.logger":"input.tcp","log.origin":{"file.name":"tcp/input.go","file.line":299},"message":"failed to get tcp6 stats from /proc: /proc/net/tcp6 entry not found for [00000000FFFF00000000000000000000:2845]","service.name":"filebeat","id":"5872C6C9A4153FA7","host":"0.0.0.0:10309","ecs.version":"1.6.0"}
Jul 21 10:56:07 n321p004875 filebeat[1650953]: {"log.level":"warn","@timestamp":"2023-07-21T13:56:07.940Z","log.logger":"input.tcp","log.origin":{"file.name":"tcp/input.go","file.line":299},"message":"failed to get tcp6 stats from /proc: /proc/net/tcp6 entry not found for [00000000FFFF00000000000000000000:176F]","service.name":"filebeat","id":"61E9ADA6C2E2638E","host":"0.0.0.0:5999","ecs.version":"1.6.0"}
Jul 21 10:56:07 n321p004875 filebeat[1650953]: {"log.level":"warn","@timestamp":"2023-07-21T13:56:07.940Z","log.logger":"input.tcp","log.origin":{"file.name":"tcp/input.go","file.line":299},"message":"failed to get tcp6 stats from /proc: /proc/net/tcp6 entry not found for [00000000FFFF00000000000000000000:2840]","service.name":"filebeat","id":"C14B93EF60A1E5FC","host":"0.0.0.0:10304","ecs.version":"1.6.0"}
Jul 21 10:56:07 n321p004875 filebeat[1650953]: {"log.level":"warn","@timestamp":"2023-07-21T13:56:07.941Z","log.logger":"input.tcp","log.origin":{"file.name":"tcp/input.go","file.line":299},"message":"failed to get tcp6 stats from /proc: /proc/net/tcp6 entry not found for [00000000FFFF00000000000000000000:284B]","service.name":"filebeat","id":"5E0A30A3AE8C0514","host":"0.0.0.0:10315","ecs.version":"1.6.0"}
Jul 21 10:56:07 n321p004875 filebeat[1650953]: {"log.level":"warn","@timestamp":"2023-07-21T13:56:07.941Z","log.logger":"input.tcp","log.origin":{"file.name":"tcp/input.go","file.line":299},"message":"failed to get tcp6 stats from /proc: /proc/net/tcp6 entry not found for [00000000FFFF00000000000000000000:2848]","service.name":"filebeat","id":"838FE3E8F8D8995B","host":"0.0.0.0:10312","ecs.version":"1.6.0"}
```

it bothers :)

**Comment by efd6** [comment]
@mussi can you provide the config for the udp listener that you have configured?

**Comment by mussi** [comment]
i create in inputs.d a file with : 
```
- type: syslog
  format: auto
  protocol.udp:
    host: "0.0.0.0:514"
  timezone: "UTC"
  processors:
    - add_locale: ~
  fields_under_root: true
  fields:
    dtp.ambiente: "dev"
    dtp.categoria: "syslogpadrao"
    dtp.type: "syslog"

- type: syslog
  format: auto
  protocol.tcp:
    host: "0.0.0.0:514"
  timezone: "UTC"
  processors:
    - add_locale: ~
  fields_under_root: true
  fields:
    dtp.ambiente: "dev"
    dtp.sistema: "syslogpadrao"
    dtp.type: "syslog"
```
my output is for redis.

**Comment by efd6** [comment]
@mussi Thanks. I should have said TCP, but you have provided that. The port in that configuration does not agree with the set of addresses in the logs, all the check are for ports 5999, 10303, 10304, 10309, 10312 and 10315, but your config is specifying 514.

What do you get if you `grep ':0202' /proc/net/tcp6` on your host? Do you have other configurations where the ports above are specified?

**Comment by mussi** [comment]
sorry :)
today : 
Aug 10 14:06:23 n121p000135 filebeat[2464050]: {"log.level":"warn","@timestamp":"2023-08-10T14:06:23.779-0300","log.logger":"input.udp","log.origin":{"file.name":"udp/input.go","file.line":293},"message":"failed to get udp6 stats from /proc: /proc/net/udp6 entry not found for [00000000FFFF00000000000000000000:2840]","service.name":"filebeat","id":"F2E8ED3CD8515C98","host":"0.0.0.0:10304","ecs.version":"1.6.0"}
Aug 10 14:06:23 n121p000135 filebeat[2464050]: {"log.level":"warn","@timestamp":"2023-08-10T14:06:23.779-0300","log.logger":"input.udp","log.origin":{"file.name":"udp/input
.go","file.line":293},"message":"failed to get udp6 stats from /proc: /proc/net/udp6 entry not found for [00000000FFFF00000000000000000000:2845]","service.name":"filebeat",
"id":"9FAD6F8E4810BC2F","host":"0.0.0.0:10309","ecs.version":"1.6.0"}
Aug 10 14:06:23 n121p000135 filebeat[2464050]: {"log.level":"warn","@timestamp":"2023-08-10T14:06:23.783-0300","log.logger":"input.tcp","log.origin":{"file.name":"tcp/input
.go","file.line":299},"message":"failed to get tcp6 stats from /proc: /proc/net/tcp6 entry not found for [00000000FFFF00000000000000000000:176F]","service.name":"filebeat",
"id":"4AC9BAF6E38A7B61","host":"0.0.0.0:5999","ecs.version":"1.6.0"}
Aug 10 14:06:23 n121p000135 filebeat[2464050]: {"log.level":"warn","@timestamp":"2023-08-10T14:06:23.787-0300","log.logger":"input.tcp","log.origin":{"file.name":"tcp/input
.go","file.line":299},"message":"failed to get tcp6 stats from /proc: /proc/net/tcp6 entry not found for [00000000FFFF00000000000000000000:283F]","service.name":"filebeat",
"id":"A84080E7765B21C7","host":"0.0.0.0:10303","ecs.version":"1.6.0"}


:cat /proc/net/tcp6
  sl  local_address                         remote_address                        st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode
   0: 00000000000000000000000000000000:2675 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 40092 1 ffff8ac57ce40000 100 0 0 10 0
   1: 00000000000000000000000001000000:0277 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 38963 1 ffff8acf4f561480 100 0 0 10 0
   2: 00000000000000000000000000000000:213E 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 22473 1 ffff8acf494970c0 100 0 0 10 0
   3: 00000000000000000000000000000000:283F 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 2248513517 1 ffff8acee808bd80 100 0 0 10 0
   4: 00000000000000000000000000000000:2840 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 2248523827 1 ffff8acf182eb340 100 0 0 10 0
   5: 00000000000000000000000000000000:1F01 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 20149 1 ffff8ac57cea3d80 100 0 0 10 0
   6: 00000000000000000000000000000000:2742 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000  1115        0 2239876016 1 ffff8ac57ce38a40 100 0 0 10 0
   7: 00000000000000000000000000000000:1F02 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 40084 1 ffff8ac57ce40a40 100 0 0 10 0
   8: 00000000000000000000000000000000:2646 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 36602 1 ffff8acf4943e680 100 0 0 10 0
   9: 00000000000000000000000000000000:2427 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 40085 1 ffff8ac57ce45c40 100 0 0 10 0
  10: 00000000000000000000000000000000:2848 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 2248505823 1 ffff8acfe6de47c0 100 0 0 10 0
  11: 00000000000000000000000000000000:2849 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 2248523825 1 ffff8acf182ea900 100 0 0 10 0
  12: 00000000000000000000000000000000:13CA 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 2248507887 1 ffff8acf49493340 100 0 0 10 0
  13: 00000000000000000000000000000000:284B 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 2248521022 1 ffff8acf56dd8000 100 0 0 10 0
  14: 00000000000000000000000000000000:176F 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 2248524807 1 ffff8ac5d43d70c0 100 0 0 10 0
  15: 00000000000000000000000000000000:20F2 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 132537 1 ffff8acf4ce8b340 100 0 0 10 0
  16: 0000000000000000FFFF00000100007F:1F01 0000000000000000FFFF00000100007F:E785 01 00000000:00000000 02:0001EB0E 00000000     0        0 9830801 2 ffff8acef308bd80 20 4 1 10 -1

:cat /proc/net/udp6 
  sl  local_address                         remote_address                        st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode ref pointer drops
22367: 00000000000000000000000000000000:8BB3 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000    70        0 37929 2 ffff8acf0273a840 0
25012: 00000000000000000000000000000000:9608 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2647080 2 ffff8ac5b664ed40 0
52654: 00000000000000000000000000000000:0202 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248513515 2 ffff8acea1e38b80 0
53831: 00000000000000000000000000000000:069B 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2666458 2 ffff8ac5b664d640 0
57493: 00000000000000000000000000000000:14E9 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000    70        0 37927 2 ffff8acf0272bf40 0
60078: 00000000000000000000000000000000:1F02 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 40082 2 ffff8ac57ce33f40 0
62440: 00000000000000000000000000000000:283C 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248524806 2 ffff8ac5eaefcac0 0
62441: 00000000000000000000000000000000:283D 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248505821 2 ffff8acf8527ed40 0
62442: 00000000000000000000000000000000:283E 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248509037 2 ffff8acf182ae1c0 0
62443: 00000000000000000000000000000000:283F 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248524811 2 ffff8ac5eaef8b80 0
62444: 00000000000000000000000000000000:2840 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248524810 2 ffff8ac5eaefa280 0
62445: 00000000000000000000000000000000:2841 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248505822 2 ffff8acf8527b980 0
62446: 00000000000000000000000000000000:2842 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248524804 2 ffff8ac5eaefd640 0
62447: 00000000000000000000000000000000:2843 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248513516 2 ffff8acea1e3f300 0
62448: 00000000000000000000000000000000:2844 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248523824 2 ffff8acee7015640 0
62449: 00000000000000000000000000000000:2845 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248523829 2 ffff8acee7014ac0 0
62450: 00000000000000000000000000000000:2846 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248511731 2 ffff8ac526412e00 841184
62452: 00000000000000000000000000000000:2848 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248524809 2 ffff8ac5eaef9700 0
62453: 00000000000000000000000000000000:2849 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248513514 2 ffff8acea1e3a280 0
62454: 00000000000000000000000000000000:284A 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248511732 2 ffff8ac526413f40 0
62455: 00000000000000000000000000000000:284B 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248523823 2 ffff8acee7015080 0
62456: 00000000000000000000000000000000:284C 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248505825 2 ffff8acf8527a840 0
62457: 00000000000000000000000000000000:284D 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248503272 2 ffff8ac4b0020b80 0
62462: 00000000000000000000000000000000:2852 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248521024 2 ffff8acea681d640 0
62463: 00000000000000000000000000000000:2853 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248524812 2 ffff8ac5eaeff300 0
62464: 00000000000000000000000000000000:2854 00000000000000000000000000000000:0000 07 00000000:00000000 00:00000000 00000000     0        0 2248518880 2 ffff8ac5263e5c00 0

**Comment by efd6** [comment]
@mussi Thanks. Can you provide equivalent output for /proc/net/tcp and /proc/net/udp?
