### ISSUE TITLE
[filebeat][http endpoint] Support more flexible response logic

### ISSUE THREAD

**Issue by marc-gr** [elastic/beats#35100]
**Describe the enhancement:**

HTTP Endpoint lets you customize a static response per url path, but there are use cases (eg [Zoom CRC flow](https://developers.zoom.us/docs/api/rest/webhook-reference/#validate-your-webhook-endpoint)) that require more advanced response logic.

**Describe a specific use case for the enhancement or feature:**

[Zoom CRC flow](https://developers.zoom.us/docs/api/rest/webhook-reference/#validate-your-webhook-endpoint) and any other than needs to change its response based on request contents or other criteria that is not just based on the path.

**Comment by P1llus** [comment]
Not often I see this functionality required, but I see that twitter for example also has this. Maybe we should compare it, to determine if there is a common/generic way in which this is usually required by third parties, so that the functionality we write can be reused.
https://developer.twitter.com/en/docs/twitter-api/enterprise/account-activity-api/guides/securing-webhooks

**Comment by chemamartinez** [comment]
Even though the CRC flow for most of webhooks are based in the same concept, I have found some differences that we have to be aware of if we want to generalize this approach.

**[Zoom CRC validation](https://developers.zoom.us/docs/api/rest/webhook-reference/#validate-your-webhook-endpoint)**
- Using a POST request
- The challenge is in the message payload
- The response is the hash in hex format

**[Twitter CRC validation](https://developer.twitter.com/en/docs/twitter-api/enterprise/account-activity-api/guides/securing-webhooks)**
**[Facebook validation](https://developers.facebook.com/docs/messenger-platform/webhooks#security)**
**[Linkedin CRC validation](https://learn.microsoft.com/en-us/linkedin/shared/api-guide/webhook-validation)**
- Using a GET request
- The challenge is a parameter in the request
- The algorithms and response are different in each one

**Comment by P1llus** [comment]
After some discussion we ended up with having the CRC functionality as generic as possible, but it seems like we would need to add vendor specific functionality as well, that could be controlled with a config entry for example.
