### ISSUE TITLE
Add Parquet file support to aws s3 filebeat input

### ISSUE THREAD

**Issue by ShourieG** [elastic/beats#35102]
Purpose : Ability for the aws s3 input to support amazon security lake.

Goals : 

1) Ability to read and parse parquet files via sqs queues / s3 buckets configured through 
    amazon security lake, using role arn.

2) Ability to map OCSF schema using schema files, if provided.

**Comment by andrewkroh** [comment]
This seems like a duplicate of #34662.

**Comment by ShourieG** [comment]
Closing this issue, since its a duplicate
