### ISSUE TITLE
filebeat8.7.0 error：missing field accessing '0.audit' (source:'/root/filebeat-8.7.0-linux-x86_64/modules.d/gcp.yml.disabled'

### ISSUE THREAD

**Issue by gophernancy** [elastic/beats#35124]
- Version: 8.7.0
- Operating System:  Linux bogon 4.19.0-240.23.11.el8_2.bclinux.x86_64 x86_64 x86_64 x86_64 GNU/Linux
- Discuss Forum URL:  none

Steps to reproduce: 
1. I downloaded filebeat from the URL: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.7.0-linux-x86_64.tar.gz
2. Modified filebeat.yml
3. Exec "./filbeat setup -e"
> When I went to reproduce the problem I found another similar error, see the picture below.
4. When I delete the file `modules.d/gcp.yml.disabled` and exec "./filebeat setup -e" then it is okay.

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/3292071/233012477-6529b18e-eeb5-43ef-a25e-b27c71443a65.png">

**Comment by Obeyed** [comment]
I encountered a similar error with the disabled gcp module config. I commented out all lines that had `${path.config}` which seemed to solve this issue.
