### ISSUE TITLE
[Meta] Improve Azure blob storage input

### ISSUE THREAD

**Issue by ShourieG** [elastic/beats#35126]
1) Add root level splitting for JSON arrays, similar to GCS input.
2) Add expand event list from field, similar to awss3 input. 
3) ~~Revisit the dynamic cursor implementation and make concurrency improvements similar to the ones made in the gcs 
     input.~~
4) Add file-selector support similar to awss3 input.
5) Add debug logs.
6) Add a date filter for blobs.
7) ~~Decouple object timeout from from scheduler timeout.~~
8) ~~Fix flakey tests.~~ 

Some open issues requesting similar enhancements: 
1) https://github.com/elastic/beats/issues/35186

**Comment by narph** [comment]
- add debug logging
