### ISSUE TITLE
Add decode_json_fields processor to Beats config files

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#3513]
The decode_json_fields processor is missing from the config.full.yml file:

https://github.com/elastic/beats/blob/master/libbeat/_meta/config.reference.yml#L110

**Comment by f-ld** [comment]
Note: the new `target` parameter added in PR #3169 (see issue #3134 ) is not even in the documentation (check https://www.elastic.co/guide/en/beats/filebeat/master/decode-json-fields.html, only appears in release notes of 5.2.0: https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-5.2.0.html)

**Comment by jdragonbae** [comment]
I would like working on this. :)

**Comment by andrewkroh** [comment]
Fixed by  #8344.
