### ISSUE TITLE
[libbeat] add_cloud_metadata processor logs confusing warnings for AWS even when running on other CSPs

### ISSUE THREAD

**Issue by tommyers-elastic** [elastic/beats#35147]
When running filebeat on GCP for example, we get log messages at WARN level from the AWS EC2 provider, which could be confusing to the user. 

e.g. 

```
{"log.level":"warn","@timestamp":"2023-04-10T15:51:30.060Z","message":"error when check request status for getting IMDSv2 token: http request status 404. No token in the metadata request will be used.","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"httpjson-zocalo_logs","type":"httpjson"},"log":{"source":"httpjson-zocalo_logs"},"service.name":"filebeat","ecs.version":"1.6.0","log.logger":"add_cloud_metadata","log.origin":{"file.line":97,"file.name":"add_cloud_metadata/provider_aws_ec2.go"},"ecs.version":"1.6.0"} 
```

**Comment by tommyers-elastic** [comment]
the way this processor works is kinda weird. for example, even if the token request fails, a fetcher is still added to the list.

if we are running outside a CSP, we end up with two separate timeouts (1 for the token, then 1 for the metadata request). the token timeout logs a warn log (e.g. `read token request for getting IMDSv2 token returns empty: Put \"http://169.254.169.254/latest/api/token\": context deadline exceeded (Client.Timeout exceeded while awaiting headers). No token in the metadata request will be used.`), the metadata timeout logs a debug log (e.g. `add_cloud_metadata: received disposition for aws after 1.140125ms. result=[provider:aws, error=failed requesting aws metadata: Get \"http://169.254.169.254/2014-02-25/dynamic/instance-identity/document\": dial tcp 169.254.169.254:80: connect: host is down, metadata={}]`.

it would be preferable not to add the fetcher if the token request fails. 

if we are running in a CSP, then the token request fails due to 404, but the fetch happens, again logging a debug message.

i think we improve this up to save on making these requests where possible. but for now a sensible solution would be to just change the warn messages in the aws token requester to debug i think. my first thought was to handle 404 as a special case, but this still leaves the warn message if you enable the processor when not running on a CSP. maybe this is ok, not sure.

**Comment by zmoog** [comment]
@aspacca, I see you introduced the support for IMDSv2 in the processors: do you have thoughts on this topic? Would change the log level from "warning" to "debug" make sense?

**Comment by aspacca** [comment]
@zmoog the `add_cloud_metadata` processor runs for every cloud provider, once enabled.
you are right: the `warning` in most of the case is a false positive.
we also had the case were one provider metadata fetcher was "matching" the endpoint of another provider and returns misleading metadata (it was the openstack/huawei ones if I remember correctly)

ì

> Would change the log level from "warning" to "debug" make sense? Or considering the timeout error condition as a "we are not on AWS" hint?

I'm fine with both: while it will be expected that most of the time the `warning` will be a false positive, hiding it at `debug` level could make more difficult to spot when it's a true positive. just minor, if we opt for the hint "we might not be on AWS"

**Comment by andrewkroh** [comment]
This issue appears to be related to the number (2) bullet in https://github.com/elastic/beats/issues/33058.

**Comment by aspacca** [comment]
coming from https://github.com/elastic/beats/blob/main/libbeat/processors/add_cloud_metadata/provider_aws_ec2.go#L97
