### ISSUE TITLE
Filebeat module Fortinet-FortiManager - add ECS authentication fields for SIEM 

### ISSUE THREAD

**Issue by leweafan** [elastic/beats#35176]
**Describe the enhancement:**

There are event.action = "auth-logon/auth-logout" in expected test files but ECS fields important for SIEM like
event.category missing and event.action should be renamed to be ECS compliant.

Successful authentication message should have fields:

- event.category = "authentication"
- event.action = "logged-in"
- event.outcome = "success"

Failed authentication message should have fields:

- event.category = "authentication"
- event.action = "logon-failed"
- event.outcome = "failure"

**Describe a specific use case for the enhancement or feature:**

**Comment by taylor-swanson** [comment]
Closing issue as the fortinet fortimanager fileset has been deprecated.
