### ISSUE TITLE
Document `unknown` as `filesystem.ignore_types` metricbeat configuration value

### ISSUE THREAD

**Issue by bczifra** [elastic/beats#35187]
**Describe the enhancement:**
In https://github.com/elastic/gosigar/pull/164, https://github.com/elastic/gosigar/blob/v0.14.2/sys/windows/syscall_windows.go#L345-L360 was modified to ignore an error from GetVolumeInformationW system call and return `unavailable` as the file system type.

This can result in metricbeat logging this error:
```
{"log.level":"error","@timestamp":"2023-04-06T08:59:18.495+0200","log.origin":{"[file.name](https://file.name/)":"module/wrapper.go","file.line":256},"message":"Error fetching data for metricset system.filesystem: error getting filesystem usage for [Z:\\](file:///Z://): GetDiskFreeSpaceEx failed: The device is not ready.","[service.name](https://service.name/)":"metricbeat","ecs.version":"1.6.0"}
```

This error can be filtered out by specifying:
```
metricbeat.modules:
  - module: system
    filesystem.ignore_types: [unknown]
```

It would be helpful to document this in https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-system-filesystem.html .

**Comment by automate-this** [comment]
Just FYI: I think you meant
filesystem.ignore_types: [unavailable]
not "unknown".
"unavailable" works for me and "unknown" does not.

**Comment by NateUT99** [comment]
I am seeing a similar message in the agent metrics data collected by the Elastic Agent for my Windows servers. Is there a way to suppress this error when these are managed by a Fleet server?

**Comment by automate-this** [comment]
Yes. You can put unknown and/or unavailable in the "ignore filesystem" option of the system integration that is assigned to your agent policy.

**Comment by NateUT99** [comment]
Circling back on this, we put both unknown and unavailable in the ignore list, but we continue to receive the error message
"error getting filesystem usage for D:\: GetDiskFreeSpaceEx failed: The device is not ready." from the Windows agent metrics. Assuming this is correct, would best course of action be to open a support case?

<img width="753" alt="Screenshot 2023-07-12 at 8 22 10 AM" src="https://github.com/elastic/beats/assets/48816468/96ca4593-023e-49ae-9a5b-17fe236fac97">

**Comment by muralidharanvenkataraman** [comment]
We would like to be added to this request as well.

**Comment by jrodewig** [comment]
Thanks @bczifra. I've opened https://github.com/elastic/beats/pull/36946 to address the missing docs and close this issue.

@NateUT99 Your issue seems to be related to https://github.com/elastic/integrations/issues/7703. Essentially, there's a bug in the UI that prevents you from setting `filesystem.ignore_types` as a an array. Since that's a separate problem, I'd use that issue to track progress. Thanks!
