### ISSUE TITLE
Problem including extra options for filebeat service args on centos 6.7

### ISSUE THREAD

**Issue by geekpete** [elastic/beats#3521]
- Version: 5.2.0 (anecdotal evidence of this also being a problem in v1.2.3 as well, yet to test it though) 
- Operating System: Centos 6.7

```# uname -a
Linux 4e8931e51b2c 4.9.4-moby #1 SMP Wed Jan 18 17:04:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/redhat-release
CentOS release 6.7 (Final)
```

- Steps to Reproduce:

```
rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch
```

```
echo "[elastic-5.x]
name=Elastic repository for 5.x packages
baseurl=https://artifacts.elastic.co/packages/5.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md" >> /etc/yum.repos.d/elastic.repo
```

```
yum install initscripts filebeat -y
```

so from this point, if I wanted to add the extra options of `"-httpprof :6060"` to the service args, this can't be done out of the box?

I could do something like:
```
echo 'EXTRA_ARGS="-httpprof :6060"' > /etc/sysconfig/filebeat
```
but there's nowhere in the `/etc/init.d/filebeat `script that includes any obvious EXTRA_ARGS or EXTRA_OPTS type env var to be able to set in the `/etc/sysconfig/filebeat` to be included.

To achieve this can only be done by editing the main init script, you'd expect it to already be in place to allow the user to just add some extra opts in the `/etc/sysconfig/filebeat` file.

A default `/etc/sysconfig/filebeat` is also missing from the install package.

**Comment by tsg** [comment]
A bit hacky. but you can add extra parameters by overriding the `BEATS_AGENT` env var, for example:

```
BEATS_AGENT="/usr/share/filebeat/bin/filebeat -httpprof :6060"
```

I marked this as an enhancement request, since there should be a cleaner way to do this.
