### ISSUE TITLE
[MSSQL] Metricbeat documentation needs update

### ISSUE THREAD

**Issue by muthu-mps** [elastic/beats#35228]
As the mssql metricbeat module is already moved to` ga`. This sentence below is not relevant. The documentation has to be updated.

This is the [Microsoft SQL 2017](https://www.microsoft.com/en-us/sql-server/sql-server-2017) Metricbeat module. `It is still under active development to add new Metricsets and introduce enhancements.`

**Comment by bizmate** [comment]
why dont you add a PR to fix it? Documentation is rather simple
