### ISSUE TITLE
Add deployment considerations to the Heartbeat docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#35255]
**Describe the enhancement:**

We are currently streamlining the content in the Observability Guide to remove duplicated content about Beats (specifically the getting started content about ingesting data). The content that we are removing contains deployment considerations for Heartbeat that AFAIK are not covered in the Heartbeat docs.

I'm opening this issue to raise awareness. I can help you get this content into the Heartbeat docs, but would like confirmation that this documentation should be included.

Someone needs to review the content (intro and deployment considerations) in the [existing (old) topic](https://www.elastic.co/guide/en/observability/8.7/ingest-uptime.html) and determine if it should be copied over to the Heartbeat docs. 

The PR that removes the content is [here](https://github.com/elastic/observability-docs/pull/2880). The current plan is to backport this PR to 8.7 and later, so you might need to look at 8.6 to see the original file.

**Comment by nimarezainia** [comment]
@drewpost  Someone from your team probably would need to review these before changes are made.
