### ISSUE TITLE
Heartbeat rtt.us field is not documented

### ISSUE THREAD

**Issue by tsg** [elastic/beats#3530]
Version: 5.2.0

Heartbeat adds a `rtt.us` field which doesn't seem documented and the definition of which is not obvious to me, since there is also a `duration.us` which has slightly different values.

<img width="1052" alt="screen shot 2017-02-04 at 21 21 38" src="https://cloud.githubusercontent.com/assets/101817/22621267/003404ec-eb20-11e6-920a-e44371fd3c4e.png">

cc @urso

**Comment by urso** [comment]
The `rtt` field seem to be some leftover only reported by the HTTP client. It's more related too "http_rtt". The difference is, `rtt.us` measure duration of `client.Do` call (including overhead in code + redirections...) and `http_rtt` measures the time we start writing a request and time we start reading the response. The timestamps are reset between every redirect, so `http_rtt` should measure the final HTTP transaction only.

Makes me wonder if we want to add some more measures to HTTP module:
- # of redirects
- per redirect 'rtt' on different protocol layers ?
- rename 'rtt' to some other value and change to being the sum of all redirects?
- duration until response has been read in full (might overlap with `validation_rtt`, as validation checks the body if configured)?

**Comment by urso** [comment]
RTT values have been reworked and documented in #4091
