### ISSUE TITLE
winlogbeat / packetbeat: Sample Dashboards broken with ES 5.2 

### ISSUE THREAD

**Issue by jochen-st** [elastic/beats#3533]
After upgradeing KIbana and Elasticsearch 5.2 from 5.1.2, the sample winlogbeat dashboards / visualizations provided from https://artifacts.elastic.co/downloads/beats/beats-dashboards/beats-dashboards-5.2.0.zip do not work anymore.

Kibana displays the following error:

    Error: [illegal_argument_exception] [terms] exclude doesn't support values of type: START_OBJECT

The issue is likely caused by https://github.com/elastic/elasticsearch/issues/22933

Fix is to replace

    "exclude": {"pattern": "\"\""},

with

    "exclude": "\"\"",

in the affected visualisations:
winlogbeat: Event-Levels.json and Evolution-of-the-CPU-times-per-process.json
packetbeat: NFS-errors.json

**Comment by jochen-st** [comment]
see https://github.com/jochen-st/beats/commit/eedc7c1834d8c5d9bb0d2c2e5a0a963be64ee215 for possible fix

**Comment by tsg** [comment]
Closing as fixed.
