### ISSUE TITLE
[Filebeat][aws-s3] Need to split event by using expand_event_list_from_field in aws-s3 input

### ISSUE THREAD

**Issue by brijesh-elastic** [elastic/beats#35344]
I am getting below log format in JSON file while using S3 Bucket.

**Example :**
```
[{"id":"1234","message":"success"},{"id":"5678","message":"failure"}]
```

Here, I want to publish individual events to elasticsearch. But I am unable to split the data using `expand_event_list_from_field` parameter.

**Describe a specific use case for the enhancement or feature:**

While creating Trellix EDR integration

**Comment by P1llus** [comment]
@kaiyan-sheng If the "root" is an array, without a key, should this not split by default with no additional options?

**Comment by kaiyan-sheng** [comment]
hmm with the current implementation, the root array is treated as one single string. I don't think it's split by default. Good catch! We probably should split by default in this case.

**Comment by jamiehynds** [comment]
@kaiyan-sheng is this something your team can address or best for security integrations to handle it? It's currently blocking an integration being developed by Crest.

**Comment by andrewkroh** [comment]
This will be supported in 8.9.0 by using `expand_event_list_from_field: '.[]'` in your config.
