### ISSUE TITLE
[Packetbeat] bpf_filter setting does not work in packetbeat 8.x.

### ISSUE THREAD

**Issue by md-irohas** [elastic/beats#35363]
- Version: at least 8.7.0 or later
- Operating System: confirmed in Linux, but OS-independent
- Discuss Forum URL: https://discuss.elastic.co/t/packetbeat-bpf-filter-setting-does-not-work-in-packetbeat-8-x/332622
- Steps to Reproduce: 
  - Add `packetbeat.interfaces.bpf_filter` setting to packetbeat.yml and start the packetbeat.

I am using packetbeat (v8.7.0) in my home network and find that the `packetbeat.interfaces.bpf_filter` setting in packetbeat.yml does not work. 

I read the source code and find that the bpf_filter value is not addressed correctly in packetbeat/sniffer/sniffer.go (even in the latest commit).

The bpf_filter value in packetbeat.yml is loaded to an `InterfaceConfig` instance in the sniffer.go, and a `sniffer` instance uses its `filter` attribute when executing `openPcap`/`openAFPacket` functions. However, the `InterfaceConfig.BpfFilter` value is not copied to the `sniffer.filter`, so the 'filter' value passed to the openPcap/openAFPacket functions is always an empty string and that's why the bpf_filter setting does not work.

Maybe, just adding one line is enough to fix this bug (if there are no side effects). 

```diff
diff --git a/packetbeat/sniffer/sniffer.go b/packetbeat/sniffer/sniffer.go
index efb12d045a..73b50771b5 100644
--- a/packetbeat/sniffer/sniffer.go
+++ b/packetbeat/sniffer/sniffer.go
@@ -141,6 +141,7 @@ func New(testMode bool, _ string, decoders Decoders, interfaces []config.Interfa
                }
 
                child.config = iface
+               child.filter = iface.BpfFilter
                s.sniffers[i] = child
        }
```

**Comment by ebeahan** [comment]
From my testing, the `packetbeat.interfaces.bpf_filter` setting works in 8.4 and earlier, but not in 8.5+.

Possibly introduced in the refactor during https://github.com/elastic/beats/pull/32732
