### ISSUE TITLE
Packetbeat SetUID/SetGID not functional on Linux.

### ISSUE THREAD

**Issue by jarpy** [elastic/beats#3542]
Attempting to drop privileges with `packetbeat.runoptions` fails with "_operation not supported_" on Linux.

Since [Go 1.4](https://golang.org/doc/go1.4), the Linux implementations of `syscall.Setuid` and `syscall.Setgid` are one-liners that return errors. 

Calls in Packbeat: https://github.com/elastic/beats/blob/81d4e25c8895cc267532f08375d8e46fd5dae5b7/libbeat/common/droppriv/droppriv_unix.go#L32

Golang implementation:
https://github.com/golang/go/blob/master/src/syscall/syscall_linux.go#L862

**Comment by andrewkroh** [comment]
Seems like this is a feature in Beats that is seldom used if it has been broken since Go 1.4.

Maybe we should remove it and recommend as an alternative running as a non-root user that has CAP_NET_ADMIN privs.

**Comment by andrewkroh** [comment]
As a workaround `setcap cap_net_raw,cap_net_admin=eip packetbeat` can be used.

**Comment by jarpy** [comment]
Thanks. That's what we have adopted in the Docker image.
