### ISSUE TITLE
Disable ECS transformations in winlogbeat

### ISSUE THREAD

**Issue by zschmerber** [elastic/beats#35511]
Hello I am working on a project where we going to transform Win event data to OCSF schema. I cannot find a way to turn off ECS in wingbeats and just send JSON formatted win event data to logstash, where I will apply OCSF mapping. I do not want to map ECS->OCSF as that seems like extra compute and confusion. 

My questions:
1. Is there a switch to turn of the ECS mapping in winlogbeats and just send JSON formatted win event data to logstash? 
2. If not can this be a feature request?
3. If this is not an option where can I insert logic to change the ECS transformations to map to OCSF instead (is this better to do in logstash or in winlognbeats)? 

https://schema.ocsf.io/

**Comment by zschemrber** [comment]
It has beed a few weeks, we are publishing [OCSF](https://schema.ocsf.io/) RC3 next week and I will need to get started with this.

**Comment by ebeahan** [comment]
I don't know of a single switch to disable of ECS mapping in `winlogbeat`.

You could experiment with changing the default config to disable the [ingest pipeline](https://github.com/elastic/beats/blob/main/x-pack/winlogbeat/winlogbeat.yml#L125) (may not apply since you're already outputting to Logstash vs. Elasticsearch) and [processors](https://github.com/elastic/beats/blob/main/x-pack/winlogbeat/winlogbeat.yml#L143) to limit processing done before `winlogbeat` ships events.

**Comment by ebeahan** [comment]
@jamiehynds anything you can share about plans to support ECS->OCSF in Beats?

**Comment by jamiehynds** [comment]
@zschemrber we are currently working through ECS to OCSF mappings as part of an integration with Amazon Security Lake. However, based on your description, am I correct that you want to avoid ECS -> OCSF and instead ingest raw Windows events and map to OCSF via Logstash and/or an ingest pipeline? 

Curious if you plan to leverage the OCSF mapped data within Elastic Security somehow, or just using it for search and visualisation and not for analytics use cases (such as detection rules, ML jobs, etc, which rely on ECS)?

**Comment by zschemrber** [comment]
@jamiehynds you are correct that I want to avoid ECS -> OCSF. However if you plan on mapping all fields for all logs related to windows and sysmon to OCSF from ECS. I would like to know more, that is a lot of mapping and I would like to not have to keep it up myself. The reason behind wanting to use raw logs was to share mappings across other orgs.

**Comment by zschmerber** [comment]
If there has not had any traction in fixing this issue or producing an OCSF winlogbeats output,  I think our path forward will be to remove winlogbeats and change our collection method.  @jamiehynds @ebeahan  do you have any updates?

**Comment by andrewkroh** [comment]
> Is there a switch to turn of the ECS mapping in winlogbeats and just send JSON formatted win event data to logstash?

ECS mappings are handled through [Winlogbeat modules](https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-modules.html) which you must opt into. So you may omit that part of the configuration to skip the additional transformations.

Additionally, if you want to use the original XML as your starting point you could enable [`include_xml: true`](https://www.elastic.co/guide/en/beats/winlogbeat/8.11/configuration-winlogbeat-options.html#_event_logs_include_xml) in the event reader configuration. You would receive Winlogbeat's normal JSON representation of a Windows event plus the original XML content in the `event.original` field.

**Comment by zschmerber** [comment]
Ended up just changing the org off of winlog beats to minifi to solve this.
