### ISSUE TITLE
[CEL Filebeat input] Enhance the CEL input to support HTTP Digest Authentication

### ISSUE THREAD

**Issue by milan-elastic** [elastic/beats#35514]
**Describe the enhancement:**
Filebeat CEL input does not have support for [HTTP Digest Authentication](https://man7.org/linux/man-pages/man1/curl.1.html#:~:text=will%20be%20used.-,%2D%2Ddigest,-(HTTP)%20Enables%20HTTP). Digest Authentication is designed to be more secure than traditional basic authentication schemes. Many products expose their metrics on endpoints that use digest authentication, which can't be accessed using the current CEL input module, Internally Digest authentication is using MD5 hash algorithm for the authentication that is also not supported in CEL to pass the hashed creds in Header.

**Describe a specific use case for the enhancement or feature:**

To create an https://github.com/elastic/integrations/issues/3744 we need to access endpoints that require [HTTP Digest Authentication](https://www.mongodb.com/docs/atlas/reference/api/process-measurements/#:~:text=HTTP%20Digest%20Authentication).
For example, if we try to access following endpoint [GET https://cloud.mongodb.com/api/atlas/v1.0/groups/{GROUP-ID}/processes/{HOST}:{PORT}/measurements](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#operation/returnMeasurementsOfOneDiskForOneMongodbProcess:~:text=One%20MongoDB%20Process-,Returns,-measurements%20of%20the) we get the following error.

`{"detail": "You are not authorized for this resource.", "error": 401, "reason": "Unauthorized"}`

To access this endpoint we can perform the following curl command.

`curl --user "{PUBLIC-KEY}:{PRIVATE-KEY}" --digest \ --header "Content-Type: application/json" \ --include \ --request GET "https://cloud.mongodb.com/api/atlas/v1.0/groups/{GROUP-ID}/processes/{HOST}:{PORT}/measurements?granularity=PT1M&period=PT1M&pretty=true"`

**Comment by efd6** [comment]
RFC: https://datatracker.ietf.org/doc/html/rfc2069

**Comment by andrewkroh** [comment]
@efd6 and I talked about this feature. One idea I had was to move the digest auth handling into the HTTP transport code. For the most part the CEL program would not need to be concerned with it authentication. The user would add the digest creds to the input config.

I found some discussion about this `http.Transport` approach in https://github.com/golang/go/issues/29409.
