### ISSUE TITLE
Beats dashboards raise error on index-pattern refresh

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#3556]
When visualizing the Metricbeat-cpu dashboard, the following error shows up:
`Saved "field" parameter is now invalid. Please select a new field.`

This issue seems to be related to the Kibana issue: https://github.com/elastic/kibana/issues/9571, and it seems to appear every time you refresh the index-pattern in Kibana 5.2.0 or later.

Steps to reproduce:
1. Load the Metricbeat dashboards. This will create the metricbeat-* index pattern.
2. Refresh the `metricbeat-*` index pattern in Kibana. This will delete some of the fields that have no data.
3. Go to the `Metricbeat-cpu` dashboard and the error appears.

Temporary solution: avoid refreshing the index-pattern
Fixing the issue: load again the dashboards to overwrite the index pattern description

**Comment by michalpristas** [comment]
Kibana related issue is solved, closing. If issue reappears let's open a new one
