### ISSUE TITLE
Beats release notes for 8.7.0 are missing some older versions

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#35580]
This bug was identified in a forum post:

https://discuss.elastic.co/t/beats-release-docs-for-8-6-2-missing/329335

After last release [8.7.0 1](https://www.elastic.co/guide/en/beats/libbeat/8.7/release-notes-8.7.0.html) notes for 8.6.2 missing and [8.6.1](https://www.elastic.co/guide/en/beats/libbeat/8.7/release-notes-8.6.1.html) present. Can you fix it?

It looks like there are some breaking changes that didn't get added either.

**Comment by geekpete** [comment]
I'll add another release notes specific problem to this issue since it seems potentially related, the overview page seems to omit the 8.7 links whereas the menu on the left seems to have the full list of links:
https://www.elastic.co/guide/en/beats/libbeat/8.8/release-notes.html

![2023-07-20_10-24](https://github.com/elastic/beats/assets/2070843/667ffcee-10c0-4286-b9eb-b301dbf3d5d0)

**Comment by karenzone** [comment]
@pierrehilbert, looks like something got weird with our 8.7.0 release notes. Will you please take a look to see what went wrong?  If it's a process thing, we might need to tweak our internal process docs to prevent similar problems going forward.

**Comment by pierrehilbert** [comment]
@karenzone I did the necessary, need to wait to see the change on the official doc now

**Comment by pierrehilbert** [comment]
@karenzone I think you need to run your automation on 8.7 version to get my changes applied

**Comment by jlind23** [comment]
Closing this one as done as per @pierrehilbert comment. Will reopen if needed

**Comment by geekpete** [comment]
The list in the menu is fixed but the main release notes page is still missing 8.7 links on the 8.8 release notes page. 8.9/8.7 release notes pages look correct though, so only 8.8 still looks broken as per:
https://github.com/elastic/beats/issues/35580#issuecomment-1642935361

**Comment by pierrehilbert** [comment]
I open a PR to fix it in 8.8
