### ISSUE TITLE
Report Metrics from filestream input

### ISSUE THREAD

**Issue by lprakashv** [elastic/beats#35583]
**Describe the enhancement:**
Add some some metrics to report the internal health of filestream input.

**Describe a specific use case for the enhancement or feature:**
There are a lot of metrics being reported by `log` input but since that has been deprecated and migrating to `filestream` input is highly recommended. Some of the older `filebeat.harvester.*` and other metrics have become useless. We need some metrics for `filestream` input equivalent to:
- filebeat.input.log.files.truncated
- filebeat.harvester.running
- filebeat.harvester.skipped
- and other valuables metrics (started, closed, stopped etc.)

**Comment by mikeh-elastic** [comment]
The metrics for /datastream are also absent when filestream is used compared to the log input.
