### ISSUE TITLE
[Docs] Incorrect privileges listed in API key documentation

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#35612]
The documentation lists the the index privileges are `create_doc` and `view_index_metadata`, but because Beats use data streams the required privileges are `auto_configure` and `create_doc`.

Related:
- https://discuss.elastic.co/t/events-get-dropped-by-restricting-api-key-winlogbeat-kibana-help-plz/329403/2
- https://www.elastic.co/guide/en/elasticsearch/reference/8.8/docs-bulk.html#docs-bulk-api-prereqs

### Affected doc pages

- https://www.elastic.co/guide/en/beats/filebeat/8.8/beats-api-keys.html#beats-api-key-publish
- https://www.elastic.co/guide/en/beats/filebeat/8.8/privileges-to-publish-events.html

### Screenshots

<img width="868" alt="Screenshot 2023-05-30 at 10 15 48" src="https://github.com/elastic/beats/assets/4565752/5ce0fedb-ac09-4c02-9f35-031b62719cec">
<img width="855" alt="Screenshot 2023-05-30 at 10 16 11" src="https://github.com/elastic/beats/assets/4565752/6d8f7cb5-35c4-41cc-ae11-1fa17138d2b3">

**Comment by herrBez** [comment]
https://github.com/elastic/beats/pull/38534 has been merged. I'll close the issue. Feel free to reopen it, if something is missing.
