### ISSUE TITLE
What are the devices that filebeat netflow does not support

### ISSUE THREAD

**Issue by SandeepaDevin** [elastic/beats#35610]
I have a server where customer configured netflow devices to send data. During Wireshark analysis I found about 40 devices sending data but in my Filebeat-Elasticsearch environment I see way less devices.

Essentially some routers that send netflow data reach the server but filebeat doesn't capture. I have changed queue_size, time_out parameters to enhance performance but no difference.

Are there any constraint, where filebeat only pick netflow data from certain devices and not others ?

**Comment by SandeepaDevin** [comment]
Most of these devices are huawei-AR models and most of them seems to be "template missing" when analyzed from Wireshark

**Comment by andrewkroh** [comment]
Until the Netflow template is transmitted by the exporter the Netflow data cannot be used and is therefore dropped by the Filebeat collector. I recommend to check the interval at which the device is sending its templates and possibly reduce the interval.

Some details on template management from Netflow 9: https://datatracker.ietf.org/doc/html/draft-claise-netflow-9-08#section-7

**Comment by ebeahan** [comment]
https://github.com/elastic/beats/issues/35610#issuecomment-1572196190 appears to have addressed questions.
