### ISSUE TITLE
Azure Billing integration - start/end interval in Forecast API call causes 2 day records gap at the end of each month

### ISSUE THREAD

**Issue by tdancheva** [elastic/beats#35633]
The Azure billing information queries two APIs:

-  API 1) [Usage Details API ](https://learn.microsoft.com/en-us/rest/api/consumption/usage-details/list?tabs=HTTP): provides detailed information about the cost within the defined scope (for ex. per subscription, per resource group, per resource etc.) This API produces this example document:
```

“azure”: {
    “subscription_id”: “7657426d-c4c3-44ac-88a2-3b2cd59e6dba”,
    “resource”: {
      “name”: “testthis”,
      “type”: “Microsoft.Storage”,
      “group”: “alex-test-resources”
    },
    “billing”: {
      “product”: “Bandwidth Inter-Region - Data Transfer Out - North America”,
      “pretax_cost”: 0.000002327970961,
      “usage_start”: “2021-11-15T00:00:00.000Z”,
      “usage_end”: “2021-11-15T23:59:59.000Z”,
      “department_name”: “Department”,
      “account_name”: “R\u0026D”,
      “currency”: “USD”,
      “billing_period_id”: “/subscriptions/7657426d-c4c3-44ac-88a2-3b2cd59e6dba/providers/Microsoft.Billing/billingPeriods/20211101"
    }
}

```
You can identify these documents if you search for the field
azure.billing.pretax_cost : *

 - API 2) [Cost Management API - Forecast](https://learn.microsoft.com/en-us/rest/api/consumption/) (for enterprise customers only) as pointed out by @lucabelluccini : Produces the actual_cost and forecast_cost, without any details for the usage_date.

This API produces the following example document :

For the past days  in the billing period with **a one day delay** i.e. the day of yesterday is not available:
```
“azure”: {
    “subscription_id”: “7657426d-c4c3-44ac-88a2-3b2cd59e6dba”,
    “resource”: {
      “name”: “testthis”,
      “type”: “Microsoft.Storage”,
      “group”: “alex-test-resources”
    },
    “billing”: {
	 “azure.billing.actual_cost”: 41.130905,
 	 “azure.billing.currency”: “EUR”,
  	 “azure.billing.usage_date”: “2023-05-01T00:00:00.000Z”
	}
}
```

You can identify these documents when you search for the field
azure.billing.actual_cost : *

or for today and the upcoming days of the billing period:
```
“azure”: {
    “subscription_id”: “7657426d-c4c3-44ac-88a2-3b2cd59e6dba”,
    “resource”: {
      “name”: “testthis”,
      “type”: “Microsoft.Storage”,
      “group”: “alex-test-resources”
    },
    “billing”: {
	 “azure.billing.forecast_cost”: 41.130905,
 	 “azure.billing.currency”: “EUR”,
  	 “azure.billing.usage_date”: “2023-05-01T00:00:00.000Z”
	}
}

```
You can identify these documents when you search for the field
`azure.billing.forecast_cost : *`

So there is some redundancy because collect `actual_cost` that we could actually deduce just from the API 1). However, there is no data loss. The user can try searching for these documents in API 1), and can also take a look at the usage plot in the Billing dashboard that does sum them up over a period of time.

The current implementation does result in a **gap** of two days the users can see because there is a delay in making the data available from the Azure side. So, the billing period range which starts on the 1st of the month does not match the interval in which the data is provided by the API. What we can do is match the interval by modifying the start data -48h, such that we close the gap (visible in the forecast visualization). However, we are not able to do anything about the delay and this was a design decision at the time and probably belongs to a different discussion. 

<!-- 
For confirmed bugs, please report:
- Version: 
- Operating System: 
- Discuss Forum URL:
- Steps to Reproduce: 
--!>

**Comment by muthu-mps** [comment]
The forecast API provides data only for -24h and not for -48h. The appraoch is to fetch forecast API metrics for 30 days and by modifying the start date to now - 24h.
