### ISSUE TITLE
Packetbeat drive internal clocks/timeouts by packet timestamps

### ISSUE THREAD

**Issue by urso** [elastic/beats#3565]
Using packetbeat with pcap files, the timestamps and clocks/timeouts do not resemble the original traffic, potentially giving different results for traffic processed via pcap and life traffic. With timeouts and timestamps using the packet timestamps, results are more reproducible, especially when using `-t`.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Related to https://github.com/elastic/beats/issues/8255.
