### ISSUE TITLE
[Heartbeat] Run_once mode should exit early if ES is unavailable

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#35706]
When running heartbeat in `run_once` mode heartbeat can get stuck if ES is unavailable, if the monitors are finished the process should wait for ES to come back for some grace period then exit.

**Comment by emilioalvap** [comment]
@andrewvc this should have been addressed by https://github.com/elastic/beats/pull/35376, is it different somehow?

**Comment by vigneshshanmugam** [comment]
@emilioalvap The PR #35376 address only part of the problem - If the ES stack is down during the time when the HB runs gets scheduled, we retry 3 times and stop the current HB run. 

But there is a case, when the customer's ESS stack is not healthy in the middle of a HB run, then we wont be able to detect it and would result in HB run taking the whole maximum allowed time as we keep retrying endlessly to report back the data to the ES. This results in wasted resources on the service.

**Comment by andrewvc** [comment]
PostFF testing passed. I tested this with the redis output because the ES output won't start on account of the state loader causing heartbeat to exit first
