### ISSUE TITLE
Include device ID and inode in each event ingested from a file

### ISSUE THREAD

**Issue by rdner** [elastic/beats#35801]
**Describe the enhancement:**

The only information about the file that is attached to the event at the moment is:

```json
{
  "offset": 0,
  "file": {
    "path": "path/to/log"
  }
}
```

We should attach additional metadata like the inode and the device ID in this code:

https://github.com/elastic/beats/blob/77c2119f401d909769146cf5ee10133f46b16064/libbeat/reader/readfile/metafields.go#L35-L62

The only implication here is a slightly bigger event size but I think it should be okay. We don't need additional `fs.Stat()` calls since this information is already available.

**Describe a specific use case for the enhancement or feature:**

Some of our customers requested this data to be attached to events. It makes it also more debuggable for developers in case of issue caused by unstable inode on a file system.

**Comment by pierrehilbert** [comment]
If we decide to implement this one (@nimarezainia), we should for sure add a perf test in the DoD to validate the impact of adding this to our events (as it won't be used by every users).

**Comment by rdner** [comment]
I don't think adding to integer fields would significantly impact the event size. It's not just beneficial for the customer but for us for improved debugging as well.

**Comment by nimarezainia** [comment]
based on the SDH seems like the right thing to be doing per @rdner.
