### ISSUE TITLE
Use ES normalize for Keyword fields

### ISSUE THREAD

**Issue by brandonmensing** [elastic/beats#3582]
Elasticsearch 5.2 now offers a normalizer for folding and case:
https://www.elastic.co/guide/en/elasticsearch/reference/5.2/normalizer.html

This would allow the user to normalize something like hostnames that differ only in capitalization.

**Comment by andrewkroh** [comment]
Windows usernames could be a candidate for normalization. https://discuss.elastic.co/t/duplicate-windows-user-names-when-filtering/79709/2
