### ISSUE TITLE
Unify -waitstop and shutdown_timeout

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#3588]
Filebeat has a `shutdown_timeout` config option and packetbeat a `-waitstop` option. These two should be unified into 1 option.

**Comment by glefloch** [comment]
In your opinion, which option should we keep? The one from config file or the one from argument command line? 

Can this be added to common config?

**Comment by ruflin** [comment]
I think we should keep the `shutdown_timeout` as the options should also be part of the config. If we can generalise the concept, it should also be part of the common config, but that means it must happen in libbeat.
