### ISSUE TITLE
Impossible to get "system.process.cpu.total.ticks" field

### ISSUE THREAD

**Issue by OlivierPT** [elastic/beats#3590]
It seems like there is no way to activate the "system.process.cpu.total.ticks" field with Metricbeat. Tested with version 5.1.2 and 5.2.0, the "cpu_ticks" option doesn't work. It only adds ticks information in "cpu" and "core" modules events.
Either the option should also activate the fields for "process" module, either we need an additional option. 

- Version:  5.1.2 and 5.2.0 
- Operating System: Linux
- Steps to Reproduce: Start Metricbeat with "process" module activated and "cpu_ticks: true" option. Check in Elasticsearch/Kibana the content for "process" events. The "system.process.cpu.total.ticks" field is not present.

**Comment by tsg** [comment]
Thanks for the report. Looking briefly over the code, it seems that the process metricset has support for "ticks", but the configuration setting is never actually checked.

**Comment by OlivierPT** [comment]
Is this bug planned to be assigned/fixed in a futur version?

**Comment by ruflin** [comment]
@OlivierPT Definitively. We will try to look into this in more detail soonish.

**Comment by andrewkroh** [comment]
I opened a PR to fix this: #3776
