### ISSUE TITLE
[Metricbeat] Unusual traffic spikes in host.network.egress.bytes and host.network.ingress.bytes metrics

### ISSUE THREAD

**Issue by crespocarlos** [elastic/beats#35944]
> **Affected Issues**
> - [ ] https://github.com/elastic/kibana/issues/148052
> - [ ] https://github.com/elastic/kibana/issues/160392

The `host.network.egress.bytes` and `host.network.ingress.bytes` metrics are presenting high volume spikes of traffic with unrealistic petabit/exabit values

- Version:  8.9 (first reported in 8.5)
- Operating System: Ubuntu 20.04.6 LTS
- Steps to Reproduce: 
Deploy a cluster on ESS
Configure a k8s cluster to report metrics
Check the Observability overview page after a few minutes

This problem has been reported by some customers and also internally. We can observe the issue on our edge-oblt cluster:

<img width="1378" alt="image" src="https://github.com/elastic/beats/assets/2767137/aedb78b0-9c2d-464c-8605-5658b98fe83a">

Contents of `/proc/net/dev` obtained from the edge-oblt cluster:

```bash
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo: 7963008922 5463536    0    0    0     0          0         0 7963008922 5463536    0    0    0     0       0          0
  eth0: 398444176031 113433103    0    0    0     0          0         0 101889838567 106565184    0    0    0     0       0          0
docker0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
veth6670df22: 514618373 1547898    0    0    0     0          0         0 528358917 1539922    0    0    0     0       0          0
veth46fce54b: 1372847132 13810810    0    0    0     0          0         0 68795908814 15049988    0    0    0     0       0          0
veth80b394bf: 381102744 4399867    0    0    0     0          0         0 3323567373 4212968    0    0    0     0       0          0
veth3fac0d3a: 1069716043 3369370    0    0    0     0          0         0 11282617637 3689656    0    0    0     0       0          0
veth3b200419:     308       4    0    0    0     0          0         0      446       5    0    0    0     0       0          0
veth44b2ac6c:   36323     457    0    0    0     0          0         0  2815590     505    0    0    0     0       0          0
vethc4bb14c8:   35702     429    0    0    0     0          0         0  2827840     464    0    0    0     0       0          0
veth93f91757:   18808     200    0    0    0     0          0         0  2646887     251    0    0    0     0       0          0
vetha7cff99a:   20128     195    0    0    0     0          0         0  2641971     249    0    0    0     0       0          0
veth2c664383:   21595     231    0    0    0     0          0         0  2703706     262    0    0    0     0       0          0
veth1305edb0:   16621     195    0    0    0     0          0         0  2627343     226    0    0    0     0       0          0
veth23fc0f56:     628       8    0    0    0     0          0         0      446       5    0    0    0     0       0          0
veth65891994:     308       4    0    0    0     0          0         0      446       5    0    0    0     0       0          0
vethdc791306: 389968462  723281    0    0    0     0          0         0 350535082  731321    0    0    0     0       0          0
vethdbb1e8cc: 966415949 3412980    0    0    0     0          0         0 3786100854 3417295    0    0    0     0       0          0
veth08cafe8e: 1488277219  959331    0    0    0     0          0         0 151128472  610027    0    0    0     0       0          0
vethc48fd2d7: 7901294175 2354094    0    0    0     0          0         0 2915337605 2345844    0    0    0     0       0          0
veth2bf4c62f: 547312101 1007781    0    0    0     0          0         0 150262077 1166200    0    0    0     0       0          0
veth93d9e375: 5800146319 4086288    0    0    0     0          0         0 2372657603 3670868    0    0    0     0       0          0
veth0228c277: 4522851970 1217721    0    0    0     0          0         0 92417022  876822    0    0    0     0       0          0
veth2f280795: 3026042574 2295286    0    0    0     0          0         0 14061850234 2758346    0    0    0     0       0          0
vetha9cf24aa: 6695686090 2813131    0    0    0     0          0         0 2402989575 2645630    0    0    0     0       0          0
veth613a14c9: 3158414047 2131687    0    0    0     0          0         0 1973949394 1925351    0    0    0     0       0          0
vethe584bff8: 3499555388 2158277    0    0    0     0          0         0 854125987 2034534    0    0    0     0       0          0
veth9d517f8c: 7897675838 9099992    0    0    0     0          0         0 3335685281 7343157    0    0    0     0       0          0
veth8e6b8c88: 7869425980 2383121    0    0    0     0          0         0 2933011516 2376166    0    0    0     0       0          0
```

Please note that the edge-oblt cluster utilizes agents. The system module configuration can be accessed at the following link: https://edge-oblt.kb.us-west2.gcp.elastic-cloud.com/app/integrations/edit-integration/38dac300-ed79-11ed-ba87-cbb4e1494a97

I couldn't reproduce this problem on my local machine, and it seems to be happening on cloud deployments.

**Comment by cmacknz** [comment]
@fearful-symmetry ideas on what is causing us to report these network counters as gigantic values? Possibly we are not handling wrap around in the underlying `/proc/net/dev` counters?

**Comment by roshan-elastic** [comment]
Thanks @cmacknz  for taking a look a this! 

@nimarezainia / @cmacknz let me know if you need any additional context to help prioritise this.

In short, here are the couple of issues where this is surfacing in the UI:

- [ ] https://github.com/elastic/kibana/issues/148052
[UI Link](https://edge-lite-oblt.kb.us-west2.gcp.elastic-cloud.com/app/observability/overview?rangeFrom=now-15m&rangeTo=now) _not happening in this environment though_
![image](https://github.com/elastic/beats/assets/117740680/61b4dff8-ce8d-440b-8d04-d8ffef308382)

- [ ] https://github.com/elastic/kibana/issues/160392
[UI Link](https://edge-lite-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/hosts?waffleFilter=(expression:%27%27,kind:kuery)&waffleTime=(currentTime:1688027278271,isAutoReloading:!f)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),source:default,timelineOpen:!f,view:map)) _not happening in this environment though_
<img width="1001" alt="image" src="https://github.com/elastic/beats/assets/117740680/8a8f5c74-b00f-49e1-87b6-b72ba3e32d53">

**Comment by fearful-symmetry** [comment]
@cmacknz 
That value posted in the first screenshot is basically MAX_INT; it's a rollover issue. The code in system/network/network.go tries to create a gauge from the previous value:
```
		r.Event(mb.Event{
			RootFields: mapstr.M{
				"host": mapstr.M{
					"network": mapstr.M{
						"ingress": mapstr.M{
							"bytes":   networkInBytes - m.prevCounters.prevNetworkInBytes,
							"packets": networkInPackets - m.prevCounters.prevNetworkInPackets,
						},
						"egress": mapstr.M{
							"bytes":   networkOutBytes - m.prevCounters.prevNetworkOutBytes,
							"packets": networkOutPackets - m.prevCounters.prevNetworkOutPackets,
						},
					},
				},
			},
		})
```

When the counter exposed via `/proc/net` rolls over, we get a negative number. Then some type conversion...somewhere turns it into an integer and we the get `2^63`.

This problem has existed elsewhere and has been fixed elsewhere, you just detect the rollover and to some math to get the correct value.

**Comment by fearful-symmetry** [comment]
Currently working on a fix. Somewhat complicated, as different network drivers in the kernel report metrics differently.

**Comment by fearful-symmetry** [comment]
Now that I think of it, I'm kind of worried about the types used by ES here. The fact we rolled over at  approx `2^63-1` seems to indicate that something, somewhere is ending up a signed integer, despite us handing off a uint64 in `r.Event()`

It's probably not relevant to this, since we're dealing with much smaller values in a gauge, but I get the feeling we should audit our use of `long` vs `unsigned_long` in field mappings. @cmacknz
