### ISSUE TITLE
packetbeat  analyze http protocol if request content-type is multipart/form-data,request body hide_keywords set Invalid

### ISSUE THREAD

**Issue by blackhu** [elastic/beats#3595]
packetbeat version 5.2.1
e.g.
      1. packetbeat configure:
                {
                       ...
                       packetbeat.protocals.http:
                                ...
                                hide_keywords:["password"]
                        ...
}
      2. http request:
               http.request.headers.content-type:multipart/form-data; boundary=----WebKitFormBoundaryp6iAntCcEpnDABOp
               http.request.body:------WebKitFormBoundaryp6iAntCcEpnDABOp Content-Disposition: form-data; name="password" iampassword

**Comment by ruflin** [comment]
@blackhu Is this a feature request, question or a bug report? Can you add some more details?

**Comment by blackhu** [comment]
In order to filter the sensitive information，i setup “hide_keywords” ,but i find only have hide "http.request.params" specify's keyword,for “http.request.body” not hide.

**Comment by ruflin** [comment]
That means this is a feature request? If you want to remove fields, you can also use processors.
