### ISSUE TITLE
[Hearbeat] Nil panic inside ELB provider

### ISSUE THREAD

**Issue by emilioalvap** [elastic/beats#35989]
- Version: `8.8`.
- Operating System: `any`
- Discuss Forum URL: https://discuss.elastic.co/t/heartbeat-auto-discover-not-working-for-aws-elb/337187

## Summary

ELB provider is trying to derefrence a nil pointer at one point, causing panic:

```
github.com/elastic/beats/v7/x-pack/libbeat/autodiscover/providers/aws/elb.(*fetchRequest).fetchListeners(0xc000322b00, {{0xc000cda7e0, 0x4, 0x4}, 0xc001069590, 0xc000b89548, 0x0, 0xc001069560, {0xc00005ab84, 0x4}, ...})
github.com/elastic/beats/v7/x-pack/libbeat/autodiscover/providers/aws/elb/fetch.go:204
```

This is the derefence:
https://github.com/elastic/beats/blob/f7fa407aff97e3218d5fa2a89cc940a1c00f8608/x-pack/libbeat/autodiscover/providers/aws/elb/fetch.go#L204

**Comment by paulb-elastic** [comment]
Linking to https://github.com/elastic/beats/issues/29782

**Comment by emilioalvap** [comment]
Closing this one since AWS ELB autodiscovery has been deprecated by https://github.com/elastic/beats/issues/29782 for a while and will be removed in a future release.
