### ISSUE TITLE
`add_cloud_metadata` produces errors running in non-cloud elastic-agent install

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#36018]
For confirmed bugs, please report:
- Version: 8.9.0
- Operating System: Linux
- Steps to Reproduce: Install beats via elastic-agent 8.9.0 on a local Linux instance

Discovered during 8.9.0 testing. Right now, in non-cloud environments, `add_cloud_metadata` logs a few errors:

```
{"log.level":"warn","@timestamp":"2023-07-06T18:24:06.085Z","message":"error fetching EC2 Identity Document: operation error ec2imds: GetInstanceIdentityDocument, canceled, context deadline exceeded.","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-monitoring","type":"filestream"},"log":{"source":"filestream-monitoring"},"log.logger":"add_cloud_metadata","log.origin":{"file.line":91,"file.name":"add_cloud_metadata/provider_aws_ec2.go"},"service.name":"filebeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
```

I assume this is an innocuous error, but it is a tad annoying.

**Comment by tommyers-elastic** [comment]
can we close this as a dup of https://github.com/elastic/beats/issues/35147 ?
