### ISSUE TITLE
new protocol: SSL envelope

### ISSUE THREAD

**Issue by urso** [elastic/beats#3604]
Add protocol analyzer for parsing and analyzing the SSL envelope. Information like protocol used und cipher suites can still be gathered. Some SSL/TLS implmentations do close the connection if handshake fails. Report this as a special event. 

Some information gathered can be added to flows.

This is not about decrypting the payload!

RFC overview: https://tools.ietf.org/wg/tls/
[TLS 1.2](https://tools.ietf.org/html/rfc5246), [TLS 1.1](https://tools.ietf.org/html/rfc4346), [TLS 1.0](https://tools.ietf.org/html/rfc2246), [SSL 3.0](https://tools.ietf.org/html/rfc6101)

- [x] add support for storing raw certificates
- [ ] update CHANGELOG
- [ ] refactor as per [tcp-protocol](https://github.com/elastic/beats/blob/master/packetbeat/scripts/tcp-protocol/README.md)
- [x] update docs
- [x] dashboard

**Comment by tsg** [comment]
I think we can consider this one closed by https://github.com/elastic/beats/pull/5476.

**Comment by adriansr** [comment]
I had pending to do some small changes (store binary certificates) and a little cleanup before closing this, but up to you

**Comment by tsg** [comment]
@adriansr Ah, that sounds good. Feel free to edit the original description and add checkboxes with what's left to do. Then we can transform it in a meta issue (like, for example, this one: https://github.com/elastic/beats/issues/5432)

**Comment by lctrcl** [comment]
any chance to add support for [ja3](https://github.com/salesforce/ja3) as well?

**Comment by adriansr** [comment]
@lctrcl looks easy to implement. Feel free to open a feature request

**Comment by tsg** [comment]
This can be considered done.
