### ISSUE TITLE
File states never get deleted from the filestream registry

### ISSUE THREAD

**Issue by rdner** [elastic/beats#36056]
Instead of using the delete operation the current implementation sets TTL to 0 instead.
 https://github.com/elastic/beats/blob/5d974fd6442550e74f219fcedf8a10f724843214/filebeat/input/filestream/internal/input-logfile/store.go#L381-L388

I suppose the intention was to optimise the deletion process and delay it until some kind of garbage collection.

However when we delete files:

1. We retain their states in-memory (might be even until next restart)
2. We make another `set` operation record in the registry log, which is much larger than the `delete` operation line

**Comment by belimawr** [comment]
I was looking into a similar issue, but from another perspective and ended up opening https://github.com/elastic/beats/issues/36761. The TTL might not be the issue here. Anyway because they could be different, I ended up opening the new issue.

**Comment by rdner** [comment]
Re-assigning to @belimawr since he already has a fixing PR open.
