### ISSUE TITLE
new protocol: SSH envelope

### ISSUE THREAD

**Issue by urso** [elastic/beats#3605]
Add protocol analyzer for parsing and analyzing the SSH envelope. 

Some information gathered can be added to flows.

This is not about decrypting the payload!

RFC overview: https://tools.ietf.org/wg/secsh/

**Comment by marknelsonengineer** [comment]
Again, this is not about decrypting traffic.  I'd like the ability to analyze some of the fields in the SSH connection attempt.

**Comment by andrewkroh** [comment]
Related: https://github.com/elastic/beats/issues/7970
