### ISSUE TITLE
[Heartbeat] Set TZ=UTC for synthetics executions if none set.

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#36117]
It currently is possible for synthetic monitors to have no timezone set which can result in weird behavior from sites that expect one to always exists as it does on user machines. To fix this we would set `TZ=UTC` on docker containers where no system TZ is specified. The current behavior is very close to this, the only exception being that the browser will no send a TZ in the headers over to sites it visits.

**Comment by awahab07** [comment]
**Post FF Testing**

Tested `docker.elastic.co/beats/heartbeat:8.10.0-SNAPSHOT` and it LGTM.

|Before|After|
|:--:|:--:|
|<img width="1172" alt="Screenshot 2023-08-31 at 18 59 58" src="https://github.com/elastic/beats/assets/2748376/e029f50b-330c-4377-b22b-ea219a3046c0">|<img width="1054" alt="Screenshot 2023-09-01 at 19 18 26" src="https://github.com/elastic/beats/assets/2748376/bb5467a4-971f-4fb4-9102-525f339fa953">|
