### ISSUE TITLE
TLS: Auditbeat does not do proper hostname verification when verification_mode is set to "full"

### ISSUE THREAD

**Issue by hannes-256** [elastic/beats#36131]
Auditbeat successfully connected to an Elastic instance via its IP address, even though the certificate of that instance is only valid for the domain "example.com"

auditbeat version 8.8.2 (amd64), libbeat 8.8.2 [\92c6b2370e46e549acda91b396f665a7e51e249c built 2023-06-23 19:03:53 +0000 UTC]

**Comment by rdner** [comment]
Thank you for reporting the issue. Since it's a security-related problem, please follow our official security policy here https://github.com/elastic/beats/security/policy
