### ISSUE TITLE
Heartbeat check custom fields

### ISSUE THREAD

**Issue by mathieuisabel** [elastic/beats#3623]
It would be beneficial to support custom fields for individual checks in Heartbeat. For instance, it would be good to be able to have an environment field for the check. Right now we have to stuff this data in the name field which is not convenient for aggregation purposes.

**Comment by urso** [comment]
TODO: Add support for `tags` and `fields` per monitor, as supported by the other beats.

**Comment by glefloch** [comment]
@urso, I would be interested into contributing on this issue. Is it possible to mark it as `adopt me`?

**Comment by ruflin** [comment]
@glefloch no need for the adopt me flag. Just go for it :-D Leave a quick comment here when you start working on it so people know that it's in progress.

**Comment by glefloch** [comment]
ok, then, I start working on it. :)

**Comment by urso** [comment]
Any contribution is very welcome ;)

I'd say you want to have a look at the `annotated` function in `util.go`.

Note, we're doing some event format update according to #3406 also touching the same function. Just to give you a warning that some merge conflict might come up (easily resolvable via rebase). We can help in PR if this happens.

**Comment by glefloch** [comment]
Great, thank you. 

I will be careful when pushing my changes.
