### ISSUE TITLE
When using pprof http server a beat can panic sometimes

### ISSUE THREAD

**Issue by nicorevin** [elastic/beats#3630]
Looks like we try to use Logger before it has been initialised fully.

```
Feb 21 09:46 systemd[1]: Started journalbeat.
Feb 21 09:46 journalbeat[14061]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 21 09:46 journalbeat[14061]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x461e8f]
Feb 21 09:46 journalbeat[14061]: goroutine 8 [running]:
Feb 21 09:46 journalbeat[14061]: panic(0x8bdbe0, 0xc42000e040)
Feb 21 09:46 journalbeat[14061]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Feb 21 09:46 journalbeat[14061]: log.(*Logger).Output(0x0, 0x4, 0xc4200f0900, 0x14, 0x0, 0x0)
Feb 21 09:46 journalbeat[14061]:         /usr/local/go/src/log/log.go:147 +0x6f
Feb 21 09:46 journalbeat[14061]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/logp.send(0x4, 0x6, 0x94e0e8, 0x5, 0x9599bb, 0x14, 0x0, 0x0, 0x0)
Feb 21 09:46 journalbeat[14061]:         /src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/logp/log.go:56 +0x308
Feb 21 09:46 journalbeat[14061]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/logp.msg(0x6, 0x94e0e8, 0x5, 0x9599bb, 0x14, 0x0, 0x0, 0x0)
Feb 21 09:46 journalbeat[14061]:         /src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/logp/log.go:84 +0x9d
Feb 21 09:46 journalbeat[14061]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/logp.Info(0x9599bb, 0x14, 0x0, 0x0, 0x0)
Feb 21 09:46 journalbeat[14061]:         /src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/logp/log.go:89 +0x71
Feb 21 09:46 journalbeat[14061]: github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/service.BeforeRun.func1()
Feb 21 09:46 journalbeat[14061]:         /src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/service/service.go:74 +0x55
Feb 21 09:46 journalbeat[14061]: created by github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/service.BeforeRun
Feb 21 09:46 journalbeat[14061]:         /src/github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/service/service.go:76 +0x6e
Feb 21 09:46 systemd[1]: journalbeat.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

- Version: v5.2.1
- Operating System: linux
- Steps to Reproduce:

**Comment by ruflin** [comment]
@nicorevin Did you see this only with journalbeat or also other beats?

**Comment by nicorevin** [comment]
@ruflin I haven't had a chance to check with other beats yet. Even with journalbeat it occurs randomly.

**Comment by ruflin** [comment]
@urso I remember we did some time ago some changes to the logging, so it does not log to early or logs go to stderr?

**Comment by nicorevin** [comment]
@ruflin @urso 

The main change seems to be [`var _log Logger`](https://github.com/elastic/beats/blob/5.2/libbeat/logp/log.go#L39) -> [`var _log = Logger{}`](https://github.com/elastic/beats/blob/5.3/libbeat/logp/log.go#L43)

But this will just pass through all the cases in https://github.com/elastic/beats/blob/5.3/libbeat/logp/log.go#L80 and `logp.Info(...)` call will just not do anything.

If I'm not mistaken it would be enough to swap [this](https://github.com/elastic/beats/blob/1391731699f858ded18a3c4232957ddbad3dcbef/libbeat/beat/beat.go#L188-L189) with [this](https://github.com/elastic/beats/blob/1391731699f858ded18a3c4232957ddbad3dcbef/libbeat/beat/beat.go#L191-L193) to resolve the issue.

**Comment by ruflin** [comment]
@nicorevin Thanks for the investigations here. We will definitively look into this. Changes here are always a bit tricky as everything needs to happen in the right order (which it seems above it doesn't). @urso WDYT?

**Comment by urso** [comment]
Looks like a race to me. on `(*Beat).launch`, `handleFlags` calls `logp.HandleFlags` to pre-init the logger to stderr. This is so we can have some error/debug log to console during startup (before config file is read). After having read the config file `(*Beat).configure` resets and reconfigures the logger by calling `logp.Init`. That is, before calling `logp.Init` no concurrent goroutines using the logger must exist. Unfortunately `svc.BeforeRun` starts a goroutine printing a log message and starting the http endpoint. @nicorevin As you pointed out, swapping these 2 lines fixes the race. Alternatively move the initial log message before the goroutine start will also help. You want to provide a PR with fix?

**Comment by nicorevin** [comment]
@urso done!
