### ISSUE TITLE
[Azure - Billing Metrics] - Fails to ingest tags resource field

### ISSUE THREAD

**Issue by muthu-mps** [elastic/beats#36373]
### Tags
In Azure tags is one of the essential field which allows us to organize the resources. The tags is used to group the billing data and categorize the cost by runtime environment.

### Issue:

- I was trying to test the flattened type use case mentioned in this [PR](https://github.com/elastic/integrations/pull/6975) in billing metrics and found that the tags field is not available in Elasticsearch.
- The current Azure billing metrics module is not ingesting the `tags` field into Elasticsearch. The Azure billing API offers the tags attribute in the response. I am adding the Azure API [link](https://learn.microsoft.com/en-us/rest/api/consumption/usage-details/list?tabs=HTTP#usagedetailslist-legacy) for reference.

### Sample Billing Metrics [No `tags`]
<img width="1178" alt="Screenshot 2023-08-19 at 3 55 37 PM" src="https://github.com/elastic/beats/assets/101238137/665f86d6-380c-463a-9348-742d402f0502">

### Solution:

As the tags field is available in the API response value, we need to map the field from the response to the billing metrics module.

**Comment by zmoog** [comment]
@muthu-mps are the tags available in the Usage Details API? If this is the case, are they available in both [legacy](https://github.com/elastic/beats/blob/eca0a0bb71d89b639f9026f7fda2373f7bbb7704/x-pack/metricbeat/module/azure/billing/data.go#L47-L82) and [modern](https://github.com/elastic/beats/blob/eca0a0bb71d89b639f9026f7fda2373f7bbb7704/x-pack/metricbeat/module/azure/billing/data.go#L83-L116) data formats?

**Comment by muthu-mps** [comment]
@zmoog - Yes, it's available as a part of the API response in both formats. Please find the sample response below,
<img width="1112" alt="Screenshot 2023-08-21 at 3 18 41 PM" src="https://github.com/elastic/beats/assets/101238137/71b2cf7a-c70e-46fd-94a7-d4a7ec2151b6">

<img width="685" alt="Screenshot 2023-08-21 at 3 21 43 PM" src="https://github.com/elastic/beats/assets/101238137/44f60079-77ee-43c7-882f-42ba7cf7c55e">

**Comment by zmoog** [comment]
This is great. Supporting both legacy and modern formats sometimes requires jumping hoops, but this does look like a straightforward case.

**Comment by zmoog** [comment]
Do the Integrations team or you already have plans about taking on this?

**Comment by zmoog** [comment]
I am able to get tags from others existing resources:

![CleanShot 2023-08-28 at 11 50 31@2x](https://github.com/elastic/beats/assets/25941/a5a9ae87-044e-4cd2-980a-801880627331)

We already have an [existing mapping](https://github.com/elastic/beats/blob/3d55242556cb2a535c4f81d1b42a459eea322c97/x-pack/metricbeat/module/azure/_meta/fields.yml#L31-L36) for `azure.resource.tags.*` from Azure module.

**Comment by lalit-satapathy** [comment]
>I am able to get tags from others existing resources:

Since the [changes](https://github.com/elastic/beats/pull/36428) is in beats now, assuming no additional code change needed for the tags to be visible in the integration run. Do we need to add a similar [mapping](https://github.com/elastic/beats/blob/3d55242556cb2a535c4f81d1b42a459eea322c97/x-pack/metricbeat/module/azure/_meta/fields.yml#L31-L36) in the integrations?

**Comment by muthu-mps** [comment]
> > I am able to get tags from others existing resources:
> 
> Since the [changes](https://github.com/elastic/beats/pull/36428) is in beats now, assuming no additional code change needed for the tags to be visible in the integration run. Do we need to add a similar [mapping](https://github.com/elastic/beats/blob/3d55242556cb2a535c4f81d1b42a459eea322c97/x-pack/metricbeat/module/azure/_meta/fields.yml#L31-L36) in the integrations?

- We already have the mappings for tags defined in the [package fields](https://github.com/elastic/integrations/blob/main/packages/azure_billing/data_stream/billing/fields/package-fields.yml#L36C2-L39C33) in the integrations. No need to make any changes. @zmoog please confirm.
- Once this change is available we can update the sample-events.json with tags in the integrations.
- @lalit-satapathy - Based on the above link referencing the beats mapping for tags field. I was able to find differences in the tags field for beats and integrations.  Beats use the `object` type and the integrations are updated to the `flattened` type. The reason here is this is a meta field that is used across Azure modules. Are we considering updating the mapping in Beats to flattened type?
- Flattened type fields in [billing](https://github.com/elastic/integrations/pull/6975) integrations.

**Comment by zmoog** [comment]
> * We already have the mappings for tags defined in the [package fields](https://github.com/elastic/integrations/blob/main/packages/azure_billing/data_stream/billing/fields/package-fields.yml#L36C2-L39C33) in the integrations. No need to make any changes. @zmoog please confirm.

Yep, the mapping for the `azure.resource.tags` is available in most (and probably all) Azure Metrics integrations.

> * Once this change is available we can update the sample-events.json with tags in the integrations.

Yep!

> * @lalit-satapathy - Based on the above link referencing the beats mapping for tags field. I was able to find differences in the tags field for beats and integrations. Beats use the `object` type and the integrations are updated to the `flattened` type. The reason here is this is a meta field that is used across Azure modules. Are we considering updating the mapping in Beats to flattened type?
> * Flattened type fields in [billing](https://github.com/elastic/integrations/pull/6975) integrations.

I see Azure integrations are not all using the same mapping for `azure.resource.tags`:

object:
- storage account
- monitor
- database account
- container service
- container registry
- container instance
- compute vm scaleset
- compute vm

flattened
- billing
- app insights
- app state

AWS is using the `object` type only.

I wonder why we picked different approaches. 

What are the pros and cons of each mapping strategy for a key/value data type like tags? The `object` type probably gives users more flexibility and query options at the cost of a higher index size. On the contrary, `flattened` is storage efficient but may impose query limits.

Am I overlooking something important?
