### ISSUE TITLE
add_process_metadata - report linux capabilities

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#36403]
**Describe the enhancement:**

The [`add_process_metadata`](https://www.elastic.co/guide/en/beats/filebeat/current/add-process-metadata.html) processor should be able to report the Linux capabilities associated with a process. ECS has these two new fields in 8.10.0.

- [`process.thread.capabilities.effective`](https://www.elastic.co/guide/en/ecs/master/ecs-process.html#field-process-thread-capabilities-effective)
- [`process.thread.capabilities.permitted`](https://www.elastic.co/guide/en/ecs/master/ecs-process.html#field-process-thread-capabilities-permitted)

The data would be read from `/proc/<pid>/status`. go-sysinfo supports fetching this data ([source](https://github.com/elastic/go-sysinfo/blob/9ea2eba5301c77b511c0475d7137ea3437a55a9a/types/process.go#L141C1-L154C2)), but the returned strings are not in the exact format expected by ECS.

**Describe a specific use case for the enhancement or feature:**

A user might want to enrich `auditd` execve events with Linux capability info.

**Comment by norrietaylor** [comment]
https://github.com/elastic/go-sysinfo/pull/196

**Comment by andrewkroh** [comment]
I think this has been implemented in https://github.com/elastic/beats/pull/38252. Closing.
