### ISSUE TITLE
Network Packet Capture with default npcap 1.71 on win 11 pro unable to capture domain name

### ISSUE THREAD

**Issue by jasoncyp** [elastic/beats#36405]
With Network Packet Capture integration on Elastic Agent 8.9 and if the windows platform is WIn 11 Pro, you won't see domain name being captured in DNS tab due to the npcap 1.71 is installed by default.

- Version: Elastic Agent 8.9
- Operating System: Windows 11 Pro
- Steps to Reproduce: Install Elastic Agent 8.9 with Elastic Defend and Network Capture Integrations on Win 11 Pro, the network domain cannot be captured and you won't see and domain name under DNS tab. Turn on "Never install Npcap on Windows" -> uninstall npcap 1.71 manually --> download npcap 1.76 from official website and install it --> domain name start capturing and you can see under DNS tab

**Comment by jamiehynds** [comment]
Thanks for reporting @jasoncyp. We are working on bumping the version of Npcap we ship with to 1.76, which will avoid having to uninstall v1.71 and manually installing v1.76

https://github.com/elastic/beats/issues/36539
