### ISSUE TITLE
Windows Service Issues 

### ISSUE THREAD

**Issue by BrunoMacias** [elastic/beats#36465]
I am seeing two issues across multiple beats when a beat is installed as a service on windows hosts. 

So far I am seeing this with both Winlogbeat and Filebeat 

1. After the beat is installed generic queries to Win32_Service hang `Get-CimInstance Win32_Service` 
2. The service itself is difficult to stop
 

- Version: 8.9.0+ 
- Operating System: Windows 10 21H2, fully patched 
- Discuss Forum URL: https://discuss.elastic.co/t/win32-service-queries-hanging/341133
- Steps to Reproduce:
	- Follow the directions to install a beat as a service https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-installation-configuration.html#installation

	- Open a PowerShell Window and run the Win32_Service query 
		`Get-CimInstance Win32_Service`
		Often this works fine on the first and second try but eventually queries hang 
		
		Issue can be resolved by killing the beats process `Get-Process Winlogbeat | Stop-Process -Force`
		
	- Second issue is with simply trying to stop the service
		`Get-Service Winlogbeat | Stop-Service` can hang for a long time and often time not finish at all

**Comment by frankhetterich** [comment]
Hello,
 we can confirm this issues. We where facing this on multiple servers (W2k16 and W2k19). Downgrade to Version 8.8.2 solves the issue for us.

**Comment by BrunoMacias** [comment]
This continues to be an issue with the new version of beats 8.9.2

**Comment by toby-sutor** [comment]
We have customer reports that it works correctly on 8.6.2, 8.8.2 and 8.10.2. 
But it fails in 8.9.0 and 8.9.2.
As such, updating to 8.10. might be a feasible workaround.
