### ISSUE TITLE
Elasticsearch not allowing Metricbeat user to generate index events

### ISSUE THREAD

**Issue by WolfangAukang** [elastic/beats#3647]
I have been configuring Metricbeat v5.2.1 on my ELK configuration in RHEL 6.

The Metricbeat user I configured has the following roles:
```

POST /_xpack/security/role/metricbeat_writer
{
  "cluster": ["manage_index_templates", "monitor"],
  "indices": [
    {
      "names": [ "metricbeat-*" ], 
      "privileges": ["read","write","create_index"]
    }
  ]
}
```

```
POST _xpack/security/role/metricbeat_reader
{
  "indices": [
    {
      "names": [ "metricbeat-*" ], 
      "privileges": ["read","view_index_metadata"]
    }
  ]
}
```

When I execute Metricbeat on my system, I receive the following message repeated times on the log:

`2017-02-21T14:22:38-06:00 WARN Can not index event (status=403): {"type":"security_exception","reason":"action [indices:admin/create] is unauthorized for user [metricbeat_internal]"}`

And even assigning the create privilege and restarting everything, it keeps throwing the same message.

I had the workaround of setting the superuser role on that user, and it works alright, but this is not a proper solution.

**Comment by ruflin** [comment]
You post above the role `metricbeat_write` and `metricbeat_reader`, but in the error message there is `metricbeat_internal`? Please use discuss for questions (https://discuss.elastic.co/c/beats/metricbeat) as we try to keep github for confirmed bugs and feature requests.

**Comment by ruflin** [comment]
@WolfangAukang I'm closing this one. Please open a discuss topic as mentioned above. Happy to continue helping there.

**Comment by WolfangAukang** [comment]
Excuse me, I forgot to tell metricbeat_internal is the user configurated to post stuff Elasticsearch
