### ISSUE TITLE
Same in Winlogbeat 8.10.1 why we get no help? What do you need? More Logs? Problem comes with the 8.9.2 Update...

### ISSUE THREAD

**Issue by cemetery84** [elastic/beats#36628]
Same in Winlogbeat 8.10.1 why we get no help? What do you need? More Logs? Problem comes with the 8.9.2 Update...

_Originally posted by @cemetery84 in https://github.com/elastic/beats/issues/37080

**Comment by cemetery84** [comment]
No help for us?

**Comment by ebeahan** [comment]
Per #37080, this appears resolved via https://github.com/elastic/beats/pull/37085.
