### ISSUE TITLE
Metricbeat 5.3 does not start on Linux systems without cgroups

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#3666]
Since Metricbeat 5.3 cgroups are enabled by default. Starting metricbeat on a Linux machine without cgroups (for example MIPS router) will stop Metricbeat with the following message:

```
2017/02/24 08:36:10.647142 process.go:66: DBG  process cgroup data collection is enabled
2017/02/24 08:36:10.647782 beat.go:450: CRIT Exiting: 1 error: error initializing cgroup reader: open /proc/cgroups: no such file or directory
Exiting: 1 error: error initializing cgroup reader: open /proc/cgroups: no such file or directory
```

This was not an issue previously as cgroups was disabled by default. Having it enabled by default, some auto detection should be done if cgroups are around or not.

Potential solutions discussed so far:

* Introduce GOARCH checks. Potential problem: Can cgroups be disable on all Linux distros?
* Use auto discovery if cgroups is not configured. Log a message when it is not available and do not stop on error.

The challenge with option two is on how a user could "enforce" the check for cgroups as it is now? `enabled` would need 3 options: `false`, `auto`, `true`. This could potentially be done, that if `enabled` is not in the config (and is `nil`) that `nil == auto`.

**Comment by andrewkroh** [comment]
There are two conditions that we should handle more gracefully.

1. The kernel was compiled without cgroups. Using `CONFIG_CGROUPS=n` when compiling.
This leads to the problem that @ruflin is reporting in this issue where `/proc/cgroups` flat out does not exist.

2. Certain groups have been disabled as boot time using `cgroup_disable=memory` for example.

    This results in `/proc/cgroups` have a 0 in the enabled column. Our implementation does not look at this bit. This should be checked by the `cgroup.SupportedSubsystems` function in gosigar.

    ```
    #subsys_name    hierarchy      num_cgroups    enabled
    cpuset          4              1              0
    ```

I'd say that if cgroups are unavailable in the kernel and the option was requested in the metricbeat config that we just log a warning.

**Comment by andrewkroh** [comment]
The requisite fixes for gosigar are in https://github.com/elastic/gosigar/pull/64.

**Comment by jsoriano** [comment]
Something similar seems to be happening here with the `add_host_metadata` processor: https://stackoverflow.com/questions/53542451/elastic-filebeat-6-5-1-error-failed-to-read-process-cgroups
