### ISSUE TITLE
[elasticsearch] Don't break when some indices are closed

### ISSUE THREAD

**Issue by miltonhultgren** [elastic/beats#36677]
https://github.com/elastic/elasticsearch/issues/88752 describes an issue with the`/_stats` API when there are any indices that are closed, that can be worked around by sending different query parameters.
We should update the Elasticsearch module to account for this possibility so that collection does not stop simply because there are closed indices.

**Comment by miltonhultgren** [comment]
In verifying this, the issue is rather that it fails when stats for a closed index are collected because the closed index is behind an alias. 
It's most likely that we need to handle this error more gracefully and inform the user to either open the index or remove it from the alias to allow collection to proceed.

**Comment by BenB196** [comment]
I haven't tested it, but would supporting setting `?forbid_closed_indices=false` as described, https://github.com/elastic/elasticsearch/issues/88752#issuecomment-1207932612, fix the issue without requiring user intervention and not breaking stats collection?

**Comment by miltonhultgren** [comment]
Yes, I have a PR here doing this https://github.com/elastic/beats/pull/38408

**Comment by miltonhultgren** [comment]
The above PR was merged.
