### ISSUE TITLE
Serverless: expand packaging scripts to build in serverless version strings

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#36701]
cc @cmacknz 
One of the features of serverless Elasticsearch is the `Elastic-Api-Version` header, which serves to version REST API responses. After a discussion on Slack, it appears that the most reliable way to do this is to build it into the beats binary as part of an automation or packaging process.  Because these API versions are not tied to stack releases this might be a little more complicated, so there's two options:

1) coordinate with the relevant teams to "tie" a beats release to a given `Elastic-Api-Version` that is set as part of release automation 
2) Automate the process as part of release packaging; integration tests run against the latest `Elastic-Api-Version`, then during the build step the version obtained from the REST API is built into the binary.

**Comment by cmacknz** [comment]
> One of the features of serverless Elasticsearch is the Elastic-Api-Version header, which serves to version REST API responses.

Can you clarify what problem we are trying to solve here for me? Why do we need to embed this into the Beats binary?

Beats itself is a client, so shouldn't the version negotiation take care of compatibility concerns?

Without other context, it seems like we want to keep the client we use up to date as it updates. We can definitely automate that.

**Comment by fearful-symmetry** [comment]
@cmacknz so, I think the idea is that the header is used to negotiate API behavior,  similar to how other REST APIs just put a major version in the URL path. So, the client should have some opinion about what versions it can talk to, and without updating the header, our other defaults are "hard-code the oldest version to specify "8.0-like" behavior, or omit it entirely, and have the serverless instance default to the newest version of the API. I assume that dynamically updating it is preferable, but maybe not?

This also isn't really a blocker right now, as there's only one released version of serverless.

**Comment by cmacknz** [comment]
Is there an authoritative source for what version of the API is the latest? We need to know that before we can automate it.

If it is in a Github repository and new version are published as releases we can have dependabot update it for us automatically with a PR for one example.

**Comment by fearful-symmetry** [comment]
Alright, so, had another chat with the serverless folks, and apparently  the `Elastic-Api-Version` header is set to be a static, non-changing value in the medium to long term, and no changes to the API are planned. Closing this for now.
