### ISSUE TITLE
Improve DSL reference documentation to work by default

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#36733]
This is a follow up from https://github.com/elastic/beats/pull/36649

The default DSL pattern is currently defined as follows (using Filebeat as an example):

https://github.com/elastic/beats/blob/1d70a83623a2503ed380631c1b6142fdfd70fcdd/filebeat/filebeat.reference.yml#L2445-L2447

This is correct in that the index pattern to match the version exactly should be `filebeat-8.11.0`, but the current example of `setup.dsl.data_stream_pattern: "filebeat-%{[agent.version]}"` does not work by default because the placeholder `%{[agent.version]}` wont' match anything.

We should ideally template in the actual stack version, which for docs purposes is defined in https://github.com/elastic/beats/blob/1d70a83623a2503ed380631c1b6142fdfd70fcdd/libbeat/docs/version.asciidoc#L1 or https://github.com/elastic/beats/blob/1d70a83623a2503ed380631c1b6142fdfd70fcdd/libbeat/version/version.go#L21 in Go.

If that cannot be done, we should default to `setup.dsl.data_stream_pattern: "filebeat-*"` which is too broad but will at least work by default for a user trying Beats for the first time.

As an additional documentation nit, the end of the DSL section in the reference configuration needs a newline at the end to be consistent with the other sections:

https://github.com/elastic/beats/blob/1d70a83623a2503ed380631c1b6142fdfd70fcdd/filebeat/filebeat.reference.yml#L2460-L2464

**Comment by fearful-symmetry** [comment]
So, technically the `filebeat-%{[agent.version]}` string is the default, as that's what the config will fall back on if you don't configure anything, and the built-in fmtstr library in libbeat will just resolve that to `filebeat-8.11`. My instinct says that the commented-out config should be the same as the actual default, and if anything we should either explain how the template works, or just change the documentation. Of course, setting the documentation to `filebeat-8.11` would technically produce the same config as `filebeat-%{[agent.version]}`.

**Comment by cmacknz** [comment]
When I wrote this I did not even know that `filebeat-%{[agent.version]}` would be resolved by the Beat, I forgot this was the fmtstr syntax.

If it works as expected I'm fine keeping it if we explain this in the configuration.
