### ISSUE TITLE
Adding additional kube-state-metrics state_deployment metrics

### ISSUE THREAD

**Issue by rudolf** [elastic/beats#36820]
**Describe the enhancement:**

The kube-state-metrics deployment state metricset currently contain only a subset of metrics https://github.com/elastic/beats/blob/main/metricbeat/module/kubernetes/state_deployment/state_deployment.go#L30-L34

https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-kubernetes.html#_deployment_2

For all available metrics see https://github.com/kubernetes/kube-state-metrics/blob/main/docs/deployment-metrics.md

We're specifically missing `kube_deployment_created`

**Describe a specific use case for the enhancement or feature:**
We'd like to monitor and alert on deployments with a high number of unavailable replicas. However, shortly after being created it's expected that a deployment/replicaset won't have all it's requested replicas available. Having `kube_deployment_created` would allow us to exclude newly created deployments from our monitoring.

**Comment by rayafratkina** [comment]
We worked around this limitation by using custom metrics in kibana controller
