### ISSUE TITLE
[Serverless]: No data for running filebeat under Discover tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#36873]
**Serverless Build details:**
```
VERSION: 8.12.0
BUILD: 68058
COMMIT: 326ef31677a6df2fe3cfaebd4e3fe251d8b26c12
```

**Host OS:**  All

**Preconditions:**
1. 8.12.0 Serverless environment should be available.

**Steps to reproduce:**
1. Setup the filbeat.yml and enable system module.
2. Enable system.yml modules to get the data.
3. Run `./filebeat setup --index-management` and observe the template is created under `IndexManagement- Data Streams`.
4. Run the filebeat using: `sudo ./filebeat -e`
5. Observe beat runs successfully, however no data under Discover tab.

**Screen Recording:**

https://github.com/elastic/beats/assets/77374876/5ee5bf37-9c33-41b9-9c1c-dc099f50226a

**NOTE:**
- We have tested this on Windows 2022 server:
  - Filebeat- threatintel module enabled
  - Metricbeat- system enabled
- SLES 15:
  - Filebeat- system module enabled

However no data is observed under Discover tab of serverless environment.
 
**Expected Result:**
Data for running filebeat should be available under Discover tab.

**filebeat.yml:**
[filebeat.zip](https://github.com/elastic/beats/files/12927545/filebeat.zip)

**sudo filebeat -e output:**
[filebeat running output.txt](https://github.com/elastic/beats/files/12927540/filebeat.running.output.txt)

**dsl_policy:**
[dsl_policy.zip](https://github.com/elastic/beats/files/12927538/dsl_policy.zip)

**filebeat logs:**
[logs.zip](https://github.com/elastic/beats/files/12927536/logs.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @cmacknz @jlind23

**Comment by jlind23** [comment]
@pierrehilbert @fearful-symmetry would you mind taking a look at this please?

**Comment by fearful-symmetry** [comment]
Looks like we have some kind of versioning issue:
```
{"log.level":"error","@timestamp":"2023-10-17T10:05:38.797Z","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/client_worker.go","file.line":148},"message":"Failed to connect to backoff(elasticsearch(https://amol-serverless-c4ae3e.es.us-east-1.aws.elastic.cloud:443)): Connection marked as failed because the onConnect callback failed: Elasticsearch is too old. Please upgrade the instance. If you would like to connect to older instances set output.elasticsearch.allow_older_versions to true. ES=8.11.0, Beat=8.12.0","service.name":"filebeat","ecs.version":"1.6.0"}
```

This can be fixed with the `output.elasticsearch.allow_older_versions` flag. However, more confused by how this happened, since I thought Serverless wasn't pegged to any stack release and was just locked to `8.0`. Going to ask around.

**Comment by fearful-symmetry** [comment]
Alright, so it turns out that serverless is pinned at 8.11, and we never noticed until after the feature freeze, since, well, it was all 8.11. Serverless will have to bypass version checks.

**Comment by cmacknz** [comment]
I would be in favor of just removing this version check entirely and just replacing it with a warning log message when ES is older than the Beats. We can default `allow_older_versions: true` instead and just log the difference.

I'm not sure what problem it is solving, and I know this does cause problems during rolling upgrades of ES nodes.

**Comment by fearful-symmetry** [comment]
Initial PR here: https://github.com/elastic/beats/pull/36884

**Comment by amolnater-qasource** [comment]
Hi Team,

Thank you for the fixes.
We have revalidated this issue on latest 8.12.0 Serverless environment and found it **fixed now**.

**Observations:**
- Data is now available under Discovering tab on running beat.

**Build details:**
BUILD: 68058
COMMIT: 326ef31677a6df2fe3cfaebd4e3fe251d8b26c12
Artifact Link: https://snapshots.elastic.co/8.12.0-0f0dbad4/downloads/beats/metricbeat/metricbeat-8.12.0-SNAPSHOT-windows-x86_64.zip

**Screen Recording:**


https://github.com/elastic/beats/assets/77374876/56b29c28-2e54-42db-bd9b-6f68afd6b809


Hence, we are **closing** this issue and marking as **QA:Validated**.

Thanks!

**Comment by harshitgupta-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in exploratory testing.

 Thanks!
