### ISSUE TITLE
Document config file ownership and permission requirements

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#3695]
I'm not sure where this should go in the docs so I'll provide the information here and leave it to be added by the professionals ✍️ . BTW this is new for 5.3 and does not apply to Windows (that's non-POSIX).

--------

All configuration files read by Beats on systems with POSIX file permissions are subject to ownership and file permissions checks. The purpose is to prevent unauthorized users from providing or modifying configurations that are run by the Beat. The owner of the configuration file must be either `root` or the user that is executing the Beat process. The permissions on the file must disallow writes by anyone other than the owner.

When installed via an RPM or DEB package the config file at `/etc/{beatname}/{beatname}.yml` will have the proper owner and permissions. The file is owned by `root` and has file permissions of `0644` (`-rw-r--r--`).

These are the two errors that you may encounter due to these checks.

`Exiting: error loading config file: config file ("{beatname}.yml") must be owned by the beat user (uid=501) or root`

To correct this problem you can use either `chown root {beatname}.yml` or `chown 501 {beatname}.yml` to change the owner of the configuration file.

`Exiting: error loading config file: config file ("{beatname}.yml") can only be writable by the owner but the permissions are "-rw-rw-r--" (to fix the permissions use: 'chmod go-w /etc/{beatname}/{beatname}.yml')`

To correct the problem use `chown go-w /etc/{beatname}/{beatname}.yml` to remove write privileges from anyone other than the owner.

Disabling the Checks

The checks can be disable on the command line using `-strict.perms=false`, but we strongly encourage your to leave the checks enabled.

**Comment by tsg** [comment]
Pinging @dedemorton on this one.

**Comment by dedemorton** [comment]
Closed by #3753
