### ISSUE TITLE
Filebeat pipeline setup broken under serverless

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#36965]
cc @cmacknz 
Discovered while running the tests in https://github.com/elastic/elastic-agent/pull/3658.

Right now tests for filebeat pipeline setup are failing with `got response from pipeline setup: Exiting: error loading pipeline for fileset apache/access: error querying _nodes/ingest: 404 Not Found: {"error":"Request for uri [/_nodes/ingest] with method [GET] exists but is not available when running in serverless mode"}`

This happens because of a call to `checkAvailableProcessors()` in `LoadPipelines()` as part of pipeline setup. It looks like the underlying call to `/_nodes/ingest` has been disabled under serverless since the last time we tested this. It seems like it should be relatively safe to disable this check under serverless, but going to ask around anyway.

**Comment by cmacknz** [comment]
Pulling into the sprint, needs to be fixed before the release of 8.11
