### ISSUE TITLE
[Filebeat][aws-s3] Add support for KMS keys for decryption

### ISSUE THREAD

**Issue by taylor-swanson** [elastic/beats#37071]
We received an enhancement request for the Carbon Black Cloud integration for supporting the usage of encrypted S3 buckets with user-provided KMS keys. Upon initial investigation, it looks like the AWS S3 input does not support providing KMS keys for decryption. In order to support this in the integration, support will need to be added for this feature in the input.

## Related

- elastic/integrations#4654

**Comment by jamiehynds** [comment]
@taylor-swanson is this something we can implement on our side and contribute? I think @P1llus had some initial thoughts on how we can approach it.

**Comment by taylor-swanson** [comment]
@jamiehynds, I'm sure we could. I'm not personally familiar with the input, but if @P1llus has some ideas on how to implement it, that'd be good place to start.

@aspacca originally mentioned taking it on, or at least getting it on the schedule. @aspacca, would you be getting to this issue soon, or do you think SEI should take it on?

**Comment by ebeahan** [comment]
With investigation and testing, found the `awss3` input supports KMS with S3 server-side encryption. Did file a suggested docs improvement to note the additional IAM privs necessary in https://github.com/elastic/beats/issues/37387.
