### ISSUE TITLE
[Metricbeat Autodiscover] Provider Kubernetes always creates watcher for namespaces and nodes 

### ISSUE THREAD

**Issue by constanca-m** [elastic/beats#37179]
## Issue

`add_resource_metadata` is enabled at all times for two resources, `namespaces` and `nodes`.

There is an option to disable them (**warning**: hints should also be disabled, otherwise this will not work). For simplicity, I will only use namespace for this issue:

```yaml
add_resource_metadata:
  namespace.enabled: false
```

However, when creating the watcher, we don't check if it is enabled or not:

https://github.com/elastic/beats/blob/cc39376a5d4c87cc1a034396f8fe6f0fb54dec73/libbeat/autodiscover/providers/kubernetes/pod.go#L110

And only later when it is time to add events, do we check for that:

https://github.com/elastic/beats/blob/cc39376a5d4c87cc1a034396f8fe6f0fb54dec73/libbeat/autodiscover/providers/kubernetes/pod.go#L160-L163

The problem with this approach is that we always need to have permissions to list namespaces within the cluster scope, when we shouldn't force the user to have them. But if they don't, we always face the error:

```
W1122 12:17:27.683394      23 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.4/tools/cache/reflector.go:167: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:kube-system:metricbeat" cannot list resource "namespaces" in API group "" at the cluster scope
```

We face this issue when resource is set to `pod` (default) and `service`. 

We also need to prevent namespace/node watchers from being created when using enrichers.

## To complete

- [x] Update code to stop watchers from starting unless `add_resource_metadata` or `hints` are enabled: 
   - [x] Beats: https://github.com/elastic/beats/pull/38762
   - [ ] Elastic agent:

**Comment by jeanfabrice** [comment]
Hey @constanca-m 👋 
Any updates on this issue? Is https://github.com/elastic/beats/issues/37243 the right issue to track for progression?
At the moment, it looks like 7.10.2 is the latest release that is free from this bug. But 7.10.2 is EOL. Thanks!

**Comment by constanca-m** [comment]
Hi @jeanfabrice. Yes, https://github.com/elastic/beats/issues/37243 is the right issue to track right now. It takes a long time to merge because it modifies a lot of sensitive code.
