### ISSUE TITLE
How to enable measurements

### ISSUE THREAD

**Issue by dahendel** [elastic/beats#372]
I looked through the docs, but could not see where I could enable the measurements fields outlined in the fields.yml documentation.

**Comment by tsg** [comment]
You only need to configure the ports where your protocols are running and all the fields should be automatically indexed. Which protocols do you want to monitor. Please also post your configuration file.

**Comment by dahendel** [comment]
I am looking for the dnstime, connecttime, and loadtime . I get the responsetime and bytes_in and bytes_out.

I am only using http protocol.

  http:
    # Configure the ports where to listen for HTTP traffic. You can disable
    # the HTTP protocol by commenting out the list of ports.
    ports: [8080, 7200, 80]

    hide_keywords: ["pass", "password", "passwd"]
    send_headers: ["User-Agent", "Cookie", "Set-Cookie", "Host", "Referer"]
    split_coookie: true
    real_ip_header: "X-Forwarded-For"
    send_response: true
    include_body_for: ["application/json"]

**Comment by tsg** [comment]
Sorry for not updating it since then, it slipped through the cracks. In the mean time, we removed those fields from the docs. They were never actually implemented, and only added to `fields.yml` as an example of what could be done.

**Comment by sohaibomr** [comment]
Do you plan to implement domloadtime, connecttime, and loadtime measurements or they are left for good?
