### ISSUE TITLE
Azure Monitor may skip a metric collection depending on the timing

### ISSUE THREAD

**Issue by zmoog** [elastic/beats#37204]
I found a regression on Azure Metrics while testing the PR https://github.com/elastic/beats/pull/37177 to backport  https://github.com/elastic/beats/pull/36823 to 8.11.

![CleanShot 2023-11-26 at 09 27 09@2x](https://github.com/elastic/beats/assets/25941/fc517196-9c30-492a-919c-2edea61e670e)

The metricset does not collect all the metric values during each iteration. 

Here's what I can see on the Compute VM dashboard:

1. Two consecutive collections, and then one skipped; then repeat.
2. As a workaround, if I set the collection period to a lower value than the smallest time grain — for example, from 300s to 60s — I get data for every metric with a time grain of PT5M or greater.

**Comment by zmoog** [comment]
The root cause of this behavior is setting `referenceTime` to "now" for every metric. 

To avoid being affected by timing, I set `referenceTime` once (truncated to seconds) at the beginning of each collection, and use this value only when the metricset need to decide if collect the values or not.

This approach is working fine in the PR https://github.com/elastic/beats/pull/37203/

**Comment by tetianakravchenko** [comment]
I've tested version 8.11.2 and still can reproduce the issue:
- I've enabled all datastreams with the default collection period (300s) and could see the periodic gaps:
<img width="2519" alt="Screenshot 2023-12-08 at 12 20 20" src="https://github.com/elastic/beats/assets/28299531/2bc17db9-af8d-4f28-99dd-53c3d8ca46a0">

After changing collection period to 60s and running it for 2h:
<TODO>

additionally:
- it would be helpful during the debugging to add the metricset name to the structured logs

**Comment by zmoog** [comment]
@tetianakravchenko, I ported the PR https://github.com/elastic/beats/pull/37365 changes to 8.11 and build a a custom agent for testing:

- version: 8.11.3-SNAPSHOT
- image id: `51ad6522096f`

Changes:
- Round reference time to the nearest second instead of truncating it.

**Comment by zmoog** [comment]
It's a drop in replacement for the agent running on your local stack. 

You can stop or assign another policy to the current agent, and start a new `zmoog/elastic-agent:8.11.3-SNAPSHOT` agent with:

```
export FLEET_ENROLLMENT_TOKEN="<token>"

docker run  --rm \
  --network elastic-package-stack_default \
  -e FLEET_URL=https://fleet-server:8220 \
  -e FLEET_ENROLL=true \
  -e FLEET_INSECURE=true \
  -e FLEET_ENROLLMENT_TOKEN=${ENROLLMENT_TOKEN} \
  -i zmoog/elastic-agent:8.11.3-SNAPSHOT
```

**Comment by zmoog** [comment]
I am still not able to reproduce the issue running agent 8.11.2 on my three testing agents:

- local stack: macOS Sonoma / arm
- Mac mini: macOS Sonoma / intel
- EC2

I have no gaps.

I ran 8.11.3-SNAPSHOT on the local stack and EC2 using two different Azure account and I get no gaps:

![CleanShot 2023-12-09 at 08 48 39@2x](https://github.com/elastic/beats/assets/25941/0a3b4b4b-4f57-41d2-aded-49c8f62dd549)

![CleanShot 2023-12-09 at 08 49 13@2x](https://github.com/elastic/beats/assets/25941/c9c1719d-efde-4931-b155-1de4461e4cc2)

**Comment by zmoog** [comment]
Can you try 8.11.3-SNAPSHOT in the environment where you get gaps?

**Comment by zmoog** [comment]
@tetianakravchenko, could you test this image on your local stack?

- version: 8.11.3-SNAPSHOT
- image id: `d1ef3377af3b`

Changes:
- remove rounding and switch to timestamp comparison with a 1-second jitter. 

In this build, I'm keeping the jitter value to 1-second.
