### ISSUE TITLE
Replace EOL `github.com/Azure/azure-event-hubs-go/v3`

### ISSUE THREAD

**Issue by AndersonQ** [elastic/beats#37233]
The module `github.com/Azure/azure-event-hubs-go/v3` is not maintained any more.

It's the Go client library for Azure Event Hubs which has been replaced by `https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs`:
> Please note, a newer package is available: [azeventhubs](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/README.md) as of [2023-05-09]. We strongly encourage you to upgrade. See the [Migration Guide](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/migrationguide.md) for more details.

The changes should be done for `main` and the `7.17` branch.

**Comment by pierrehilbert** [comment]
cc @bturquet to ensure this is under your radar.

**Comment by zmoog** [comment]
@AndersonQ, @pierrehilbert I am tracking this issue at https://github.com/elastic/beats/issues/33815 and trying to raise this as a priority.

**Comment by pierrehilbert** [comment]
Closing as https://github.com/elastic/beats/issues/33815 is done.
