### ISSUE TITLE
Add latency metric to libbeat.output metrics

### ISSUE THREAD

**Issue by leehinman** [elastic/beats#37258]
**Describe the enhancement:**

Add a latency metric to libbeat.output metrics that are shown in 30s metrics.

**Describe a specific use case for the enhancement or feature:**

Adding a latency metric to the libbeat.output section would make it much easier to see when writes to the output slow down or are the cause of a performance bottleneck.

An average latency over the 30s timeframe is the minimum, but would be nice to have std dev or percentiles.

**Comment by fearful-symmetry** [comment]
@leehinman by _latency_ do you mean the delay between the event reaching the libbeat pipeline, and the event reaching ES? If so, should that be measured by the time it reaches the bulk index API, or by the time it reaches some other part of the go ES API?

**Comment by leehinman** [comment]
> @leehinman by _latency_ do you mean the delay between the event reaching the libbeat pipeline, and the event reaching ES? If so, should that be measured by the time it reaches the bulk index API, or by the time it reaches some other part of the go ES API?

Nope.  For elasticsearch it would be how long the HTTP PUT to the bulk API takes.

**Comment by fearful-symmetry** [comment]
@leehinman Ah, so we're talking _just_ the delay in the HTTP request itself for this metric?

**Comment by leehinman** [comment]
> @leehinman Ah, so we're talking _just_ the delay in the HTTP request itself for this metric?

It will be different for each output, but for elasticsearch yes.  For something like the file output we would want to know how long the `Write` took.

The debug log [here](https://github.com/elastic/beats/blob/dcd09e98bb200780e0dccfd8602df44db7599071/libbeat/outputs/elasticsearch/client.go#L266) is close for elasticsearch output, but it isn't in the metrics

**Comment by fearful-symmetry** [comment]
Currently prototyping this. It's a bit odd compared to other metrics, since it's not a counter, but a continual rolling value. Current idea is to add some kind of average functionality to the registry reporter in elastic-agent-libs, since reporting it as either an average value or an array seems like the best way to do this. Unless you have other ideas @leehinman

**Comment by leehinman** [comment]
> Currently prototyping this. It's a bit odd compared to other metrics, since it's not a counter, but a continual rolling value. Current idea is to add some kind of average functionality to the registry reporter in elastic-agent-libs, since reporting it as either an average value or an array seems like the best way to do this. Unless you have other ideas @leehinman

For the input metrics, we use github.com/rcrowley/go-metrics with a "NewUniformSample" and then a Histogram.  Take a look at processing time [here](https://github.com/elastic/beats/blob/fe9b7ce5a9180ba820d1c0719fe12f8cf7738917/filebeat/input/tcp/input.go#L189)
