### ISSUE TITLE
[Packetbeat] Update Npcap version to v1.78

### ISSUE THREAD

**Issue by kgeller** [elastic/beats#37300]
We are currently bundling Npcap with Packetbeat, and the Network Packet Capture integration with version 1.76. Since that update, version 1.78 has been released that fixes memory leaks in v1.76 & 1.77. 

https://github.com/nmap/npcap/blob/master/CHANGELOG.md#npcap-178-2023-10-18

- [x] update cross builder images — (see elastic/golang-crossbuild#315 for previous process) — elastic/golang-crossbuild#360
- [ ] update version in x-pack/packetbeat/magefile.go (see #33172 for pattern, copyright dates are [now 2013-2023](https://github.com/nmap/npcap/blob/b1d8f91cf1a6c9cd53df2ecb6939ae04756be9c2/LICENSE#L5)) — #37370

**Comment by efd6** [comment]
I doubt we will get this fix into v8.11.2.

**Comment by ebeahan** [comment]
@efd6 I see https://github.com/elastic/golang-crossbuild/pull/360 was merged. Any other necessary steps to take?

**Comment by efd6** [comment]
The issue was https://github.com/elastic/golang-crossbuild/pull/361. That is now merged. The second part can now be done.

**Comment by cmacknz** [comment]
I believe this is (or something related to this) is blocking the upgrade to Go 1.20.12 in https://github.com/elastic/beats/pull/37350 since it is failing trying to pull `docker.elastic.co/observability-ci/golang-crossbuild:1.20.12-npcap-1.76-debian9`

**Comment by efd6** [comment]
@cmacknz There is now a PR to change the npcap version and it should be asking for 1.78.
