### ISSUE TITLE
filebeat doesn't update new content

### ISSUE THREAD

**Issue by haleywon** [elastic/beats#3733]
- Version:  filebeat version 1.2.2 (amd64)
- Operating System: Red Hat Enterprise Linux Server release 6.5 (Santiago)
- Steps to Reproduce: 
Hi, I'm currently struggling with the filebeat issue..
now I'm trying to rotate my db log file everyday and trying filebeat to read them as below.

cat /dev/null > /home/haley/session.log
cat /home/db/original.log > /home/haley/session.log

(filebeat prospector)

paths:
- /home/haley/session.log
encoding: UTF-8
input_type: log
document_type: "XXXXX"
scan_frequency: 300s

but even though log is overwritten by cronjob, filebeat doesn't update new content..

only 2 way can read new content
1. shutdown filebeat and delete registry file and startup filebeat (<-this read whole log files in config path..so entries in KIBANA is duplicated)
2. change inode by editing log file with vi editor (<-this read the whole log file content again.)

Is it a problem of version? or my prospector or way of logrotation are wrong ?

below is part of ./filebeat -c config.yml -e -d "*" result.

2017/03/09 06:08:41.679734 log.go:270: DBG  harvest: "/home/haley/session.log" position:124098 (offset snapshot:0)
2017/03/09 06:08:41.679744 log.go:113: INFO Harvester started for file: /home/haley/session.log
2017/03/09 06:08:41.679762 reader.go:138: DBG  End of file reached: /home/haley/session.log; Backoff now.

2017/03/09 06:08:41.679825 crawler.go:71: DBG  Registrar will re-save state for /home/haley/session.log
2017/03/09 06:08:41.682390 prospector.go:264: DBG  Check file for harvesting: /home/haley/session.log
2017/03/09 06:08:41.682397 prospector.go:389: DBG  Update existing file for harvesting: /home/haley/session.log
2017/03/09 06:08:41.682403 prospector.go:435: DBG  Not harvesting, file didn't change: /home/haley/session.log

...

**Comment by ruflin** [comment]
I assume this is the same topic as here: https://discuss.elastic.co/t/filebeat-doesnt-update-rotated-log-files-new-content/77798/2 Please do not double post and use discuss for questions. Closing this one.
