### ISSUE TITLE
import_dashboards.exe Error 400 Bad Request

### ISSUE THREAD

**Issue by Exocomp** [elastic/beats#3740]
See output dump below, I believe the reason is "**Unzip archive**", in the folder where it claims to unzip I don't see the unzipped folder, that command may not be working.

C:\Users\Win10-x64\Downloads\winlogbeat-5.2.2-windows-x86_64>scripts\import_dashboards.exe -es http://192.168.1.121:9200/
fail to set the mapping. Error: 400 Bad Request
Create temporary directory C:\Users\WIN10-~1\AppData\Local\Temp\tmp541042443
Downloading https://artifacts.elastic.co/downloads/beats/beats-dashboards/beats-dashboards-5.2.2.zip
Unzip archive  C:\Users\WIN10-~1\AppData\Local\Temp\tmp541042443
C:\Users\WIN10-~1\AppData\Local\Temp\tmp541042443\beats-dashboards-5.2.2\filebeat
C:\Users\WIN10-~1\AppData\Local\Temp\tmp541042443\beats-dashboards-5.2.2\heartbeat
C:\Users\WIN10-~1\AppData\Local\Temp\tmp541042443\beats-dashboards-5.2.2\metricbeat
C:\Users\WIN10-~1\AppData\Local\Temp\tmp541042443\beats-dashboards-5.2.2\packetbeat
C:\Users\WIN10-~1\AppData\Local\Temp\tmp541042443\beats-dashboards-5.2.2\winlogbeat
Import directory  C:\Users\WIN10-~1\AppData\Local\Temp\tmp541042443\beats-dashboards-5.2.2\winlogbeat/index-pattern
Import index to /.kibana/index-pattern/winlogbeat-* from C:\Users\WIN10-~1\AppData\Local\Temp\tmp541042443\beats-dashboards-5.2.2\winlogbeat\index-pattern\winlogbeat.json
ERROR:  couldn't load json. Error: 400 Bad Request
fail to import index-pattern: fail to load directory C:\Users\WIN10-~1\AppData\Local\Temp\tmp541042443\beats-dashboards-5.2.2\winlogbeat/index-pattern: error loading C:\Users\WIN10-~1\AppData\Local\Temp\tmp541042443\beats-dashboards-5.2.2\winlogbeat\index-pattern\winlogbeat.json: couldn't load json. Error: 400 Bad Request

**Comment by Exocomp** [comment]
It turned to be the slash at the end of the elastic search path.

This failed:  http://192.168.1.121:9200/
This worked:  http://192.168.1.121:9200

**Comment by liketic** [comment]
@ruflin  Is this still an issue?

**Comment by ruflin** [comment]
@liketic TBH haven't checked recently and didn't do the investigation yet. In case you investigated the issue let us know if it is still there.

**Comment by tsg** [comment]
@liketic This is kind of moot now because in master/6.0 we no longer have an `import_dashboards` script that downloads the archive, but the `setup` command that loads the local dashboards (they come with the Beat).

We also didn't see other reports for this one, so I'd rather close it for now.

**Comment by liketic** [comment]
@ruflin @tsg I just want to say the command has been removed so this issue should been closed now. But the document is not updated, we already had a issue for that. So nothing we can do for this now.
