### ISSUE TITLE
Heartbeat report TLS details

### ISSUE THREAD

**Issue by urso** [elastic/beats#3741]
When heartbeat is connecting via TLS, report information on server certificate and connection details if possible:

- TLS version used
- cipher being used
- server certificate expiration date

**Comment by RobertoFlores** [comment]
There is a date to include this feature on Heartbeat?

**Comment by ruflin** [comment]
@RobertoFlores There is no specific date.

**Comment by andrewvc** [comment]
As an update we now support the expiration dates. I'm on the fence WRT the other info as that crosses into security scanning tools when we're thinking about auditing things like cipher suites and TLS versions.

On the other hand, these are simple tiny fields.

**Comment by andrewvc** [comment]
I propose we close this for now unless there are any objections. TLS version and cipher suite are usually in the realm of vulnerability scanning tools. I'm not sure they belong in heartbeat.
