### ISSUE TITLE
New Metricbeat Module for Windows Performance Counters

### ISSUE THREAD

**Issue by maddin2016** [elastic/beats#3742]
Hi @tsg and @andrewkroh,

after some pause working on my metricbeat i think it is ready to publish. How i should go on. Should i post the whole source as a PR and you extract what you need? [Here](https://github.com/maddin2016/pdhbeat) is the source.

**Comment by ruflin** [comment]
@maddin2016 Best would be if you could open a PR with your source code.

**Comment by andrewkroh** [comment]
This has been added for 6.0 and remaining work is tracked in #3828.
