### ISSUE TITLE
filebeat‘s output.kafka have a phenomenon of loss data.

### ISSUE THREAD

**Issue by heyujiaan** [elastic/beats#3747]
I used filebeat to collect logs to kafka, but found that some data was lost when transmitting to kafka
， and the filebeat log had the following information when the data was lost.

> 2017-03-14T05:12:57Z   WARN client/metadata fetching metadata for all topics from broker 
What happened the output.kafka?

**Comment by ruflin** [comment]
Lets move this discussion to https://discuss.elastic.co/c/beats/filebeat We try to keep Github for confirmed bugs. 

The above message comes from the saram client. Please share on discuss the filebeat version you are using, the config file, more details on the Kafka setup and if possible. the full log file.
