### ISSUE TITLE
make `annotateEvent` as an interface

### ISSUE THREAD

**Issue by vjsamuel** [elastic/beats#3752]
Today, the publisher has `annotateEvent` as a method that specifically annotates events with beat meta. If we make this as an interface similar to processors, we could support annotation of messages with any information. Ideally add_cloud_metadata would be a perfect fit for an annotator rather than a processor. The beat annotator can be a separate module which could be turned on by default and also disable-able if the user wishes to disable publishing beat information.

**Comment by ruflin** [comment]
What is form your point of view the different between an `annotator` and a `processor`? I was more thinking that `tags` and `fields` should potentially also be processors.

**Comment by vjsamuel** [comment]
@ruflin: This is my take on it. A processor is something that takes an input and generates an output based on a manipulation. It can be something like keeping fields, removing fields, changing fields from one format to another format. 

Annotations are key value pairs that add more information to the event most likely about its whereabouts. Things like which AZ, cloud provider or cluster manager the event belongs to. 

If we split processors and annotators as two different entities, it would keep the processors light and clean. For example: `add_cloud_metadata` has to contact a provider API, get information and this information is added to each event. `annotatebeat` also does the same by talking to the Kube API server. Providing a standard `annotate` interface to query metadata for all running workloads and annotating each event would be a good to have. Annotators would also need to be dynamic in nature when we support dynamic workloads especially when they run with the help of cluster managers like Kubernetes where workloads come and disappear on each host(similar would apply to `docker` and `rkt`).

Processors could potentially just structurally manipulate events and not have any external dependencies to function, whereas annotators need the required external dependencies to be available.

By having an annotate API we could potentially have native support for various cluster managers/runtimes like `kubernetes`, `docker`, `mesos`, `rkt`. Today `metricbeat` treats container running on a host as a cgroup and hence there is no additional information. By adding annotation apis for `docker`, `rkt` we can say, "this cgroup id maps to this docker container which in turn has this name and labels, add them to the metric and ship it out".

Thoughts?

**Comment by ruflin** [comment]
I think I have to add some history on the processors here:

* Initially we called it filters as it was strictly about reducing the data structure
* Then we renamed it to processors when added `add_cloud_metadata` and were discussing `lookup` features. One of the idea was to call it lookup processors.
* Also processors allowed us to add json_decoder which fits well here

Lets call the feature of checking external meta data "annotate" for the moment as I try not to discuss naming yet :-)

One of the questions that I ask myself is when should the different things happen? Taking metricbeat as an example: 

* Filters can happen on the module level but also on a global level
* Some of the processors only properly work on the global level because only then the complete event exists
* When should annotate happen? Directly after all processors were applied? Or should it be configurable per module, as not all module will need the same annotation?

**Comment by vjsamuel** [comment]
Let's take the kubernetes/Docker environment as an example. How do I as an annotator discover where the log and the metric came from? For logs I will be able to find it from the log file path. It would either have a container id or a container layer id. For a metric ip:port would be the corresponding identifier. Hence I would agree with you that annotating all events may not be required but they would need to ideally happen at the specific module level. It would ideally happen after all processing at the module level as this Metadata is not subject to be played around with. 

The interfaces that are required to make this happen are :

`UpdateMeta` which would be updating a local store of metadata each time a workload is added removed or modified in the host. 

`Annotate` which would look for a field in the event that can essentially be used to figure out if the metadata can be looked up and added to the event.

**Comment by exekias** [comment]
Hi @vjsamuel I think I understand your point, but I don't fully get what's missing on processors to perform the same operations. For instance, talking about a Docker processor (to add docker metadata from the container) it could potentially work this way:

 -  When the processor is instantiated it starts by creating a list of running containers, and keeps updating it in the background.

 - Processor.Run checks every event and looks for known fields (log file path, cgroup, etc). If it matches a known container we enrich the event with metadata from that container.

Maybe this example help us on clarifying what's missing here?

**Comment by vjsamuel** [comment]
@exekias, the thought is to keep static processors away from modules that append metadata and make things like adding beat metadata as configurable. I completely agree with you, it is totally doable with processors today but do we really do it via processors?

**Comment by vjsamuel** [comment]
@ruflin @exekias, i have been thinking about this topic a lot and maintaining processors for `docker`, `kubernetes` may not be a bad idea instead of breaking them out as `annotators`. the only caveat is that we would need to build processors for each beat. metricbeat would append metadata based on `ip:port` and `filebeat` would annotate based on containerid present in the log file.

**Comment by ruflin** [comment]
I'm hoping that the we can have a general docker lookup part to fetch info and then some config options in the processor on what data to add. But I see the potential problem that it will work quite differently in the different beats. Definitively something we must take into account.

I like the idea of having everything under "processors" for simplicity for the user so he does not have to learn to concept. Perhaps we can use naming (which is really hard) to indicate some differences between the processors.

@vjsamuel About the metadata: Agree that it should also be a process. I'm mainly thinking of tags and fields. Did you have some other things in mind? Were you thinking of `beat.*`?

**Comment by vjsamuel** [comment]
@ruflin: Metadata is typically fields in this case. Ex: pod name, pod ip, namespace name, labels (which are arbitrary <key, value> pairs.

**Comment by urso** [comment]
just a side-node, processors can be 'namespaced'. That is, we can have a `annotate.X` namespace to logically group annotate processors (e.g. lookup-exec branch uses `lookup.exec`).

**Comment by vjsamuel** [comment]
@ruflin @urso @exekias , I am in the process of moving annoatebeat into a processor. let me put it up for review in the next day or two and let's see how we can take it forward.

**Comment by exekias** [comment]
I'm closing this as it seems we already have a working solution
