### ISSUE TITLE
Flaky Test - TestDocker (a packaging test) fails validating exported images

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#37726]
## Flaky Test

* **Test Name:** TestDocker
* **Link:** https://github.com/elastic/beats/blob/3198a686db03c76ef387e0b76e0ad941c4212cca/dev-tools/packaging/package_test.go#L748-L752
* **Branch:** main
* **Artifact Link:** If available, attach the generated zip artifact associated with the stack trace for this failure.
* **Notes:** The docker engine version being used on CI has changed to export images in the [OCI Image Layout](https://github.com/opencontainers/image-spec/blob/970322241ad9c8868d15e6859c9b446ad06b944d/image-layout.md). Our test is expecting to find a JSON file in the root of the image, but that is now moved into a `blobs/sha256/<layer>` where the path is determined by reading `jq '.[].Config manifest.json'`.

### Stack Trace

```
>> Testing package contents
 --- FAIL: TestDocker (2.82s)
     package_test.go:234: error reading file /var/lib/jenkins/workspace/Beats_packaging_main/src/github.com/elastic/beats/metricbeat/build/distributions/metricbeat-oss-8.13.0-SNAPSHOT-linux-amd64.docker.tar.gz: no entrypoint
 FAIL
 FAIL	command-line-arguments	9.253s
 FAIL
 package ran for 10m34.012428251s
 Error: running "go test /var/lib/jenkins/workspace/Beats_packaging_main/src/github.com/elastic/beats/dev-tools/packaging/package_test.go --modules --min-modules 1 --modules.d -root-owner -files /var/lib/jenkins/workspace/Beats_packaging_main/src/github.com/elastic/beats/metricbeat/build/distributions/*" failed with exit code 1

```

**Comment by cmacknz** [comment]
Thanks, we need to update this check to handle both formats. As we have just learned, Beats itself isn't in control of when the format can change.

**Comment by andrewkroh** [comment]
Potential fix: https://github.com/elastic/beats/pull/37727
