### ISSUE TITLE
[RSA2ELK] Remove deprecated modules

### ISSUE THREAD

**Issue by jamiehynds** [elastic/beats#37746]
We announced deprecation of the experimental 'RSA2ELK' modules in 8.12 and now need to remove these modules from 8.14 onwards. For the majority of these modules, users can move towards agent integrations which have been built from scratch and no longer rely on the RSA2ELK pipelines. 

List of modules to remove:

Barracuda
Bluecoat
Cisco Nexus (fileset within Cisco module)
Cisco Meraki (as above)
Cylance
F5
Fortinet Client Endpoint (fileset within Fortinet)
Fortinet Fortimail (as above)
Fortimanager (as above)
Imperva
Infoblox
Juniper Junos
Juniper Netscreen
Microsoft DHCP
Netscout
Proofpoint
Radware
Snort
Sonicwall
Sophos UTM
Squid
Tomcat
Zscaler

**Comment by marc-gr** [comment]
> For the majority of these modules, users can move towards agent integrations which have been built from scratch and no longer rely on the RSA2ELK pipelines.

Is there any action or plan for the ones without direct replacement?
