### ISSUE TITLE
Queue flush settings interact badly with output's `bulk_max_size`

### ISSUE THREAD

**Issue by faec** [elastic/beats#37757]
(See also https://github.com/elastic/beats/issues/37754)

The memory queue's flush timeout and event threshold are internal performance hints that interact in some counterintuitive ways with output batch settings. This can cause pipeline slowdown in some scenarios. Recent changes to the default configuration, particularly [increasing the queue flush timeout from 1s to 10s](https://github.com/elastic/elastic-agent/issues/3797), have made these scenarios much more likely. However, more careful configuration checking and buffer management could prevent most of them.

## Scenario 1: `flush.min_events > bulk_max_size`

`bulk_max_size` represents the largest batch of events that the output will ever ask for. `flush.min_events` represents the size of the internal buffers the queue uses to accumulate events. A common setting (including the defaults) is for `flush.min_events` to equal half the queue size.

If `bulk_max_size` is smaller than an internal queue buffer, then the queue will split that buffer across multiple output batches. This comes with some implicit costs:
- Even if the output requests a small batch (e.g. 50 events), the queue will not make one available until it fills an entire buffer (currently defaulting to 1600 events) unless the flush interval expires. This was not so bad when the flush interval was 1 second, but now it means the outputs may be completely idle for 10 seconds even when there was plenty of data to generate full batches.
- _All_ events from an internal queue buffer must be ingested and acknowledged before _any_ of them can be deallocated. If there is a full queue consisting of 2 internal buffers, this means all input processing will be blocked until one of the buffers (50% of the queue's full capacity) is completely acknowledged. This is even worse if there are multiple output workers, because the entire queue buffer is gated by the ingestion speed of its slowest batch -- the queue may be well over 50% consumed and acknowledged before _any_ input workers can resume.

## Scenario 2: `bulk_max_size > flush.min_events`

This scenario has fewer pitfall than the previous one, enough that the [documentation](https://www.elastic.co/guide/en/beats/filebeat/current/configuring-internal-queue.html#configuration-internal-queue-memory) merely says "values of `bulk_max_size` greater than `flush.min_events` have no effect." This is also less likely to arise in the wild, since the default for `flush.min_events` is fairly high and it's uncommon for users to override it.

However, if this does happen, it means that the queue will never provide `bulk_max_size` events in response to an output request, even if there are that many events available.

### Temporary workaround for affected users

Revert `flush.timeout` to `1`. This was the baseline before 8.12, and resolves the issue in practice, but loses the efficiency gains of ingesting in larger batches.

### Partial internal solution

Cap `flush.min_events` at `bulk_max_size`.
- This mitigates the worst case, which is when there are several output workers and a correspondingly lowered `bulk_max_size` but `flush.min_events` is still high.
- This might have to be special-cased, since not all outputs support `bulk_max_size`.

### Full internal solution

Remove `flush.min_events` entirely and base batch size on the value requested by the output workers.
- This flag is a performance hint to allow the queue to prepare full batches before they are requested. At the time it was added, it was important that batches be backed by single contiguous buffer slices. Changes to the batch and acknowledgement APIs since then have removed this requirement.
- Nobody understands what this flag actually does, which makes using it risky.
- We have the ability (these days) to just use a static ring buffer and always return a batch of optimal size based on a given request, which would make `flush.min_events` redundant.

**Comment by cmacknz** [comment]
100% agree having both `flush.min_events` and `bulk_max_size` is confusing, it is more or less impossible to understand entirely without reading the code first.

What is the effort difference between the partial solution and the full solution? Is the full solution significantly more than more than 1 week of extra work vs the partial solution?

It's also not clear to me what we'd do for users that have set `flush.min_events` but not `bulk_max_size` in the full solution.

**Comment by faec** [comment]
> What is the effort difference between the partial solution and the full solution? Is the full solution more than 1 week of extra work vs the partial solution?

I'd estimate the bare implementation time for the full solution at 2-3 days (a lot of preparations have already been made). Testing and benchmarking are potentially bigger concerns, though we'll probably be doing more of that either way.

> It's also not clear to me what we'd do for users that have set flush.min_events but not bulk_max_size in the full solution.

flush.min_events is much less known/used than bulk_max_size (and only recently became accessible via custom yaml in Agent), so I think this is a rare case, but when it happens behavior will depend on how the default bulk_max_size compares to flush.min_events:

- If default bulk_max_size < flush.min_events, then bulk_max_size was already capping the batch size, and all flush.min_events was doing was adding a bit of latency and some inconsistency to batch sizes. This change would be neutral-to-positive.
- If default bulk_max_size > flush.min_events, then bulk_max_size was being ignored, and the queue always produced batches of size flush.min_events, or as close as it could get within a flush interval. This change would instead allow batches (within the flush interval) to grow up to bulk_max_size, which might be negative if their setup depends on small batches.
  * However, this is effectively the same tradeoff we made when increasing bulk_max_size from 50 to 1600, right up to the same resolution for affected users (just set bulk_max_size to the batch size you really want).

I think the full solution has a lot fewer risks than the config defaults changes that prompted this issue, and since it means we'd never have to troubleshoot a confusing parameter value again, I think it's worth it. (It would also let us delete a big chunk of memory queue code, since there would no longer be any reason to keep two completely separate implementations for the buffered and unbuffered case.)

**Comment by cmacknz** [comment]
> I think the full solution has a lot fewer risks than the config defaults changes that prompted this issue, and since it means we'd never have to troubleshoot a confusing parameter value again, I think it's worth it

Agreed, thanks for the details and for confirming it isn't significantly more work or risk.

> If default bulk_max_size < flush.min_events

There are a few real world use cases where `bulk_max_size: 0` has been configured. To try to avoid having this be a breaking change, would it make sense to consider `flush.min_events` to be an alias for the new unified parameter (which I assume would keep the name `bulk_max_size`)? 

That is if we see `bulk_max_size: 0` in the configuration we implicitly set it to the value of `flush.min_events` or the default `flush.min_events` that would have taken effect if it isn't set?

**Comment by faec** [comment]
> That is if we see bulk_max_size: 0 in the configuration we implicitly set it to the value of flush.min_events or the default flush.min_events that would have taken effect if it isn't set?

That sounds reasonable, or to reframe it a bit: let's redefine `flush.min_events` as "the most events the queue will produce for any one Get request". We can switch to a ring buffer internally so that value no longer controls arcane buffer chain parameters -- that gets rid of the main hazard, blocking output workers even though there is enough data available -- but still enforce it as a global batch maximum, so anyone who was using it to control batch size will get no change in behavior, and everyone else will get slightly more consistent latency + batch sizes. Then in the documentation we can just say "this limits the maximum event batch size, it's deprecated, use bulk_max_size instead".
