### ISSUE TITLE
[Filebeat] Netflow input - disable event normalization

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#37764]
**Describe the enhancement:**

Disable Beat event normalization for the input. Event normalization should not be needed for the input because it only uses basic types in its events. This will save CPU time for each event that is `Publish()`ed.

Example:

https://github.com/elastic/beats/blob/4586146d92aacfe78cfc182e0125703081304362/x-pack/filebeat/input/awss3/input.go#L158-L166

**Describe a specific use case for the enhancement or feature:**

This will marginally speed up the input's processing times (like 2%).

### Related Issues

- Depends on https://github.com/elastic/beats/issues/37865

**Comment by pkoutsovasilis** [comment]
hi @andrewkroh, please correct me if I am wrong, but to achieve disabling the `EventNormalization` first the netflow input needs to be migrated to plugin.v2 implementation right?

**Comment by andrewkroh** [comment]
You're right. It does need to be using the v2 API. I forgot that we had inputs that haven't been migrated.

**Comment by pkoutsovasilis** [comment]
thx for acknowledging my understanding @andrewkroh . I think that this issue should come first before #37762 and #37761 to get this first as a plugin v2 and then work our way through these

**Comment by andrewkroh** [comment]
I created a separate issue for the conversion. https://github.com/elastic/beats/issues/37865

**Comment by pkoutsovasilis** [comment]
because of this [issue](https://github.com/elastic/beats/issues/38703) event normalization has been re-enabled [here](https://github.com/elastic/beats/pull/38780) for netflow. Thus, I am reopening this issue, to disable event normalization without any regressions 🙂
