### ISSUE TITLE
metricbeat.yml not found when binary executed from different directory

### ISSUE THREAD

**Issue by djschny** [elastic/beats#3777]
- Version: 5.2.1
- Operating System: Mac 10.12.3
- Steps to Reproduce: 

* Execute metricbeat from a different directory then where the configuration file exists and notice the error:

```
$ metricbeat-5.2.1-darwin-x86_64/metricbeat 
Exiting: error loading config file: open metricbeat.yml: no such file or directory
```

Expectation would be that be default it would look for the config in the same directory as where the binary exists.

**Comment by ruflin** [comment]
This was introduced in https://github.com/elastic/beats/pull/2245 I think we kept it this way for BC compatibility. We should discuss to change this for 6.0

@tsg Your commit message in https://github.com/elastic/beats/pull/2245/commits/a4afb65a8d3312c34cf7bfb7cf2ae04f75ec0fcc and the text in https://github.com/elastic/beats/pull/2245 contradict each other. Which one is correct? I assume the commit message ...
