### ISSUE TITLE
Bad hyperlink syntax in Format Strings docs

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#3783]
See https://www.elastic.co/guide/en/beats/libbeat/current/config-file-format-type.html#_format_string_sprintf

<img width="785" alt="screen shot 2017-03-21 at 11 16 22 am" src="https://cloud.githubusercontent.com/assets/4565752/24154549/da64e634-0e27-11e7-85bf-7ab864459c9c.png">

**Comment by dedemorton** [comment]
Fixed in #3803
