### ISSUE TITLE
Support Azure in add_cloud_metadata Processor

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#3784]
I had a request at ElasticON for support Azure in the [add_cloud_metadata](https://www.elastic.co/guide/en/beats/metricbeat/current/add-cloud-metadata.html) processor. I'm not finding much documentation via Google (maybe I should be trying Live). I'll see about getting an Azure account to spin up and instance and see what's available from http://169.254.169.254/metadata/v1/maintenance.

References:
- https://azure.microsoft.com/en-us/blog/what-just-happened-to-my-vm-in-vm-metadata-service/
- https://azure.microsoft.com/en-us/blog/accessing-and-using-azure-vm-unique-id/

**Comment by saada** [comment]
I'll give this a shot this weekend
