### ISSUE TITLE
Module/Prospector level processor support

### ISSUE THREAD

**Issue by vjsamuel** [elastic/beats#3785]
I understand that today we only support `include_lines`, `exclude_lines`, and `exclude_files` as processors at a prospector level and support `filters` at metricbeat module level where a user can provide any processor as a filter for the given module. This is a great feature to have in filebeat as well. Can the same be extended to filebeat where a user can say:
```
filters:
  - processor1
  - processor2
```

This is especially useful when custom processing needs to be done for specific log files. Putting them as global processors only slows down the pipeline as each and every log line needs to be verified.

**Comment by ruflin** [comment]
We will also need this to better support the reloading feature. Currently it is not possible to add a new prospector and have a specific processor for it.

I remember we wanted to add this in the past but there was an issue that the event format on the processor level is not in the format the processor expects it. So it could be that some previous refactoring is needed.

**Comment by vjsamuel** [comment]
not valid anymore :)
