### ISSUE TITLE
[journald] Add configuration example to the default configurations

### ISSUE THREAD

**Issue by pierrehilbert** [elastic/beats#37877]
## Issue
Meta issue: https://github.com/elastic/beats/issues/37086
To have journald GA, we should update Beats and Elastic Agent default configurations to include an example of using the journald input to read system logs.

## Acceptance Criteria 
- [ ] Example in Beats default configuration
- [ ] Example in Elastic Agent default configuration

**Comment by belimawr** [comment]
Elastic-Agent PR: https://github.com/elastic/elastic-agent/pull/6414
