### ISSUE TITLE
Add environment checks to custom beat generator

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#3791]
A common problem when creating a beat is that the environment is not set up correctly. The generate.py script should support the user in detecting potential problems. Because of this the script should check for:

* Correct Golang version
* Correct setup / existence of GOPATH
* Correct python version
* Virtualenv installed

Further checks could be potentially added. In addition it would be nice to report to the user based on which branch he created the beat.

**Comment by exekias** [comment]
A common thing I've seen so far is that I don't define GOPATH, since it defaults to ~/go, several Makefiles expect it to be defined anyway, hasn't been a problem anyway

**Comment by jsoriano** [comment]
This has changed a lot with the migration of these scripts to mage, but we could probably still add some checks. // cc @fearful-symmetry
