### ISSUE TITLE
distribution@v2.8.0+incompatible: checksum mismatch

### ISSUE THREAD

**Issue by sharbuz** [elastic/beats#37948]
The issue was found during the pipeline's migration process from Jenkins to Buildkite.
The issue is related to the  `7.17` branch and GO/Python integration tests
description of the issue: https://github.com/distribution/distribution/issues/3590
examples of the issue: 
https://buildkite.com/elastic/beats-metricbeat/builds/2364#018d8d22-a487-4d18-8889-8af2214925c3
https://buildkite.com/elastic/beats-libbeat/builds/1203#018d8e8b-7967-41cb-a1da-6b6e4b8a5218

```
verifying github.com/docker/distribution@v2.8.0+incompatible: checksum mismatch
	downloaded: h1:u9vuu6qqG7nN9a735Noed0ahoUm30iipVRlhgh72N0M=
	go.sum:     h1:l9EaZDICImO1ngI+uTifW+ZYvvz7fKISBAKpg+MbWbY=
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
For more information, see 'go help module-auth'.
=== Errors
verifying github.com/docker/distribution@v2.8.0+incompatible: checksum mismatch
	downloaded: h1:u9vuu6qqG7nN9a735Noed0ahoUm30iipVRlhgh72N0M=
	go.sum:     h1:l9EaZDICImO1ngI+uTifW+ZYvvz7fKISBAKpg+MbWbY=
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
For more information, see 'go help module-auth'.
```
Solution:
Change the version of the package: https://github.com/elastic/beats/blob/50fa7652e310c4480252e5ab6c41599dfb7348c7/go.mod#L231

**Comment by dliappis** [comment]
@pierrehilbert / @jlind23 could the dev team backport this exclusion to 7.17 so that we can finish the winlogbeat migration from Jenkins to BK?

**Comment by pierrehilbert** [comment]
Sorry @dliappis I was in PTO last week. 
I can't see any objection with having this exclusion in 7.17, cc @cmacknz just in case I missed something.
