### ISSUE TITLE
Metricbeat process module cmdline does not update even though process alters it

### ISSUE THREAD

**Issue by eldondevcg** [elastic/beats#3799]
- Version: 5.1.2
- Operating System: Linux 4.8.0-41-generic 44~16.04.1-Ubuntu SMP
- Steps to Reproduce: 
  - Start MetricBeat
  - Cause process to alter command line to change the results reported by `ps` and other tools
  - MetricBeat continues to report old cmdline.

It is not uncommon[1](https://pypi.python.org/pypi/setproctitle) [2](https://docs.ruby-lang.org/en/2.1.0/Process.html) [3](https://github.com/lxc/lxc/blob/master/src/lxc/utils.c#L1411)  for some linux tools to modify /proc/cmdline contents to make monitoring tools more intelligible, and sometimes to add status information about a process, such as "sleeping", "idle", "running", etc.
Unfortunately, metricbeats seems to cache this information. I think it would be preferable not to cache this information at all, but at the very least an option to avoid caching it would be nice.

**Comment by tsg** [comment]
I think we added the cache due to performance issues on Windows. It makes sense to me to add an option to disable it.

**Comment by tsg** [comment]
Or even make it default off on non-Windows.

**Comment by maddin2016** [comment]
Hi @tsg. I think it is [this](https://github.com/elastic/beats/blob/master/metricbeat/module/system/process/helper.go#L345) line where you cache the cmdline, right?

**Comment by andrewkroh** [comment]
@maddin2016 Yeah, that is where the grabs the cached `cmdline`. And [this](https://github.com/elastic/beats/blob/v5.3.0/metricbeat/module/system/process/helper.go#L87-L93) is where it skips the fetching if it already knows the `cmdline`.

**Comment by maddin2016** [comment]
What about an option `process.cmdline.cache: false` ?

**Comment by ruflin** [comment]
I somehow dislike different behaviour on different OS so I think a config option would work best here.

**Comment by eldondevcg** [comment]
I would be happy with a config option.

**Comment by maddin2016** [comment]
If everyone is happy with a config option I would adopt this issue.

**Comment by tsg** [comment]
Thanks @maddin2016!
