### ISSUE TITLE
[awss3 input] unescape characters in s3 file names

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/beats#38012]
At some point there was introduced this fix https://github.com/elastic/beats/pull/18370 to unescape characters in s3 file names.
Since then it seems that the implementation has changed and now there is similar error:
```
failed processing S3 event for object key "2024-02-08T08:35:00 00:00.json" in bucket "xxxx": failed to get s3 object (elapsed_time_ns=143737473): s3 GetObject failed: operation error S3: GetObject, https response error StatusCode: 404, RequestID: ...
```
Filname: `2024-02-08T08:35:00+00:00.json`

this error seems to be coming from the [GetObject](https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/interfaces.go#L233) call

**Comment by zmoog** [comment]
The error happens because the poller turns the original key 

```
2024-02-08T08:35:00+00:02.json.gz
```

Into 

```
2024-02-08T08:35:00 00:02.json.gz
```

The Poller performs this change at: https://github.com/elastic/beats/blob/aba91a412323133ecfbbe569a438d27a7d41f2da/x-pack/filebeat/input/awss3/s3.go#L211-L212

Quick test using the Go Playground: 
https://go.dev/play/p/GvQcEQG607C

This only happens when using the S3 input in polling mode; the S3 input  in SQS mode can successfully process the same object.

As a workaround, I recommend using the S3 input in SQS mode.

**Comment by zmoog** [comment]
@kaiyan-sheng, @aspacca, please let me know what you think. 

If the `url.QueryUnescape(*object.Key)` is no longer required, I can open a PR.

**Comment by kaiyan-sheng** [comment]
@zmoog Thanks for looking into it! Yes I think we can remove the `QueryUnescape` in s3 polling!

**Comment by zmoog** [comment]
> Yes I think we can remove the QueryUnescape in s3 polling!

Great. I'll draft a PR and run a couple of tests then. 

@aspacca, let me know what you think 🙇

**Comment by aspacca** [comment]
@zmoog, yes, you're totally on spot!

The bug was already reported https://github.com/elastic/beats/issues/33998 and I came to the same conclusion

As mentioned in my comment on that issue:
> there is indeed a bug in the filebeat input, since we should unescape the s3 object key only when the value comes from an s3-sqs notification. in your case, since you are using the direct s3 listing input, the key is not escaped and we should not unescape it.

so, as @kaiyan-sheng also mentioned, we should remove `QueryUnescape` only when dealing with s3 polling

**Comment by aspacca** [comment]
@zmoog , sorry, please note that https://github.com/elastic/beats/pull/18370 is the old version of the input.

it was refactored as we know, this is the place where `QueryUnescape` is invoked now here for sqs-s3: https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/sqs_s3_event.go#L279

We should not remove this call.

But rather this one: https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/s3.go#L212
That's the one made for s3-listing mode
