### ISSUE TITLE
[Metricbeat][Oracle] Field `oracle.tablespace.space.total.bytes` is missing

### ISSUE THREAD

**Issue by kush-elastic** [elastic/beats#38051]
### Description
The field oracle.tablespace.space.total.bytes is absent from the Table Space Metric set.

### Cause
The query used to retrieve the Table Space metric for other than TEMP space is missing the calculation for Total bytes based on the collected bytes of read and write operations. This calculation is present for TEMP spaces but not for other spaces.
Query: [Link to the query](https://github.com/elastic/beats/blob/main/x-pack/metricbeat/module/oracle/tablespace/data_files.go#L33)
Performing an aggregation (SUM) on the field BYTES will provide us with the total bytes for the tablespace.

**Comment by agithomas** [comment]
@niraj-elastic , Unless there exists any reason for not using the logic used in the Integrations, the same approach can be used in Oracle Metricbeat module.

**Comment by niraj-elastic** [comment]
@agithomas, Currently if tablespace is `TEMP` than `space.total.bytes` is collected as total bytes of `TEMP` tablespace. If we choose to implement integration logic, we will have to make change in logic of `TEMP` tablespace as well, because in integration `space.total.bytes` field shows sum of all the bytes of `TEMP` and `NON-TEMP` tablespaces (total bytes of all the tablespaces). So if we choose to go with integration logic there will be major logical changes for current users of this metricset.

**Comment by agithomas** [comment]
Ok, what are you proposing?

**Comment by niraj-elastic** [comment]
By doing some more analysis it seems that `space.total.bytes` is incorrectly set for TEMP tablespace as well in metricbeat module. based on this [description](https://github.com/elastic/beats/blob/9c9ae3568309bb4c715fe1c25834eafd06f0f82a/x-pack/metricbeat/module/oracle/tablespace/_meta/docs.asciidoc?plain=1#L25), `space.total.bytes` should be sum of all the tablespaces just like integration. So changing logic to integration logic ( SUM([bytes](https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/DBA_FREE_SPACE.html#GUID-0FFCB990-4013-4D8A-A2FC-CF4B38DB7CC8:~:text=of%20the%20extent-,BYTES,-NUMBER)) of DBA_DATA_FILES + SUM([bytes](https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/DBA_TEMP_FILES.html#GUID-9251BF75-0FC4-4271-8736-8AAD4C549563:~:text=the%20file%20belongs-,BYTES,-NUMBER)) of DBA_TEMP_FILES ) of `space.total.bytes` field for TEMP and adding same logic for NON-TEMP tablespace seems right approach, let me know your thoughts here.
