### ISSUE TITLE
New protocol support: AVRO

### ISSUE THREAD

**Issue by darrenmoen** [elastic/beats#382]
Created from discussion here:
https://discuss.elastic.co/t/new-protocol-avro/34826

**Comment by darrenmoen** [comment]
Started working on this here:
https://github.com/darrenmoen/packetbeat/tree/avro/protos/avro

**Comment by monicasarbu** [comment]
Sounds great. Please let us know if you need any help.

**Comment by darrenmoen** [comment]
Is there a preference between using a 3rd party go lang avro library to do the decoding (such as https://github.com/linkedin/goavro) or doing it myself?

**Comment by monicasarbu** [comment]
It's ok to use 3rd party libraries if they have a compatible license and they work well for your needs.
