### ISSUE TITLE
Look for filebeat.yml in /etc/filebeat by default

### ISSUE THREAD

**Issue by mcandre** [elastic/beats#3820]
Instead of requiring an explicit flag `-c /etc/filebeat/filebeat.yml`, could filebeat simply set the default configuration file location to `/etc/filebeat/filebeat.yml`?

**Comment by monicasarbu** [comment]
@mcandre Please ask questions like these in the forum instead: https://discuss.elastic.co/
The github issues list is reserved for bug reports and feature requests only. Thanks!
