### ISSUE TITLE
Capture application pool states - IIS

### ISSUE THREAD

**Issue by parilsanghvi** [elastic/beats#38248]
**Describe the enhancement**:

Currently, the [iis application pool module](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-iis-application_pool.html) only captures running app pools. It would be nice if it captured all apps pools and included the state of them.

**Describe a specific use case for the enhancement or feature**:

IIS app pools can have [many different states](https://github.com/prometheus-community/windows_exporter/blob/master/pkg/collector/iis/iis.go#L438), currently, it is only possible to get data on running app pools. This limits the usability of this module.

If I want to alert when an app pool stops, I need to look for when logs related to the app pool stop for X duration. This is less than ideal, as if I remove an app pool, then this alert would also trigger. Or if an app pool exists, but has never been started, then the alert would never trigger as there was no initial data to collect, to see a detla.

**Comment by jrykowski-huron** [comment]
This is an issue we also faced, and as work around create a custom function as ingest process to bulk import IIS AppPool info including status.   We have been great to simply enable iis module to get this info ingested!

**Comment by jrykowski-huron** [comment]
@parilsanghvi  I see this has been closed because "completed".   Is there a link to related PR where this was added?  What version of beat service includes update to module for iis that handled ingest of the app pool states?

**Comment by parilsanghvi** [comment]
@jrykowski-huron I found same issue opened over here #39061. So I closed this one to avoid repetition of same issue.
