### ISSUE TITLE
We need tests to cover host metric monitoring on docker

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#38241]
@cmacknz 
We've had a number of bugs stemming from us not paying enough attention to how metricbeat is monitoring the host system when run from inside docker:

- https://github.com/elastic/elastic-agent-system-metrics/issues/132
- https://github.com/elastic/elastic-agent-system-metrics/pull/129

We really need some kind of integration test that specifically tests the case of metricbeat monitoring the host system from inside a container. It would also help if this test could also be aware of the version of the host OS the test is running on, as we've seen a lot of edge cases stemming from how different linux versions setup cgroups and docker.

These tests also need to have control over the host system, and not just run from within docker, as tests man need to start processes on the host system to monitor, tinker with cgroups, etc.

**Comment by cmacknz** [comment]
> These tests also need to have control over the host system, and not just run from within docker, as tests man need to start processes on the host system to monitor, tinker with cgroups, etc.

So what you need is a more like a native Buildkite running that has Docker installed so it can launch containers, instead of just having a Docker running?

This should be possible, speak with ingest eng prod to get a sense of if this is something that is possible now or needs some additional set up work.

**Comment by fearful-symmetry** [comment]
@cmacknz So, according to slack, this shouldn't actually be too hard (at least in theory). We can set the `agents` field in the buildkite runner and get a VM with access to docker.

The kind of remaining question is if we want to build a more complex test matrix out of this. We could easily build out a test infrastructure where we spin up 3-5 agents running different agents to get a spread of cgroups/OS config setups. I kind of think we _should_ do that, but we can discuss it further once buildkite is properly setup in beats.
