### ISSUE TITLE
Heartbeat names conflict with another package on Ubuntu

### ISSUE THREAD

**Issue by tsg** [elastic/beats#3826]
The `heartbeat` name is taken on ubuntu and probably other distributions. This results in a bad experience while trying to install our heartbeat.

We've discussed some potential options:

* Rename our Heartbeat to something else (e.g. Upbeat or Uptimebeat)
* Reimplement the original `heartbeat` HA functionality in Heartbeat  and supersede it (just kidding :)) 
* Rename the DEB and RPM files to something like `elastic-heartbeat-....deb`.

The last option currently seems the most appealing. We probably want to add the `elastic-` prefix to all beats, not only Heartbeat, to keep the packaging process consistent. Some potential issues that we need to investigate:

* This might affect the unified build process
* The dash might be problematic to use in the package names / file names
* We'd need to smoothly upgrade from one version of the other (i.e. use `Replaces:` on Debian, etc.)
* We should consider if we want the `elastic-heartbeat` name in all DEB/RPM names or only in the ones that we put in the repositories. Similarly, we could name the package `elastic-heartbeat` but keep the filename as `heartbeat...deb`.

We plan to figure this out by 6.0.

**Comment by exekias** [comment]
joining all different beats under the same project would fix the issue too. Just "beats"  :dango:

**Comment by andrewkroh** [comment]
It looks like FreeBSD ports moved to "beats" partially due to the heartbeat name collision.

From: https://www.freshports.org/sysutils/beats/

> The reason is to make the port more maintainable and also that the new heartbeat beat would
conflict with sysutils/heartbeat.

**Comment by tsg** [comment]
Closing in favor of #3765. I moved my comment there.
