### ISSUE TITLE
Ignore missing @timestamp in Apache module

### ISSUE THREAD

**Issue by cwurm** [elastic/beats#3834]
Version: filebeat-5.3.0

When ingesting some Apache logs I hit an error when the `rename` processor in https://github.com/elastic/beats/blob/master/filebeat/module/apache2/access/ingest/default.json failed.

Would we ever have a `@timestamp` when ingesting directly from the log file using the module? If not, we might want to remove the processor altogether.

Anyway, setting `ignore_missing: true` to the processor, together with fixing the grok pattern (https://github.com/elastic/beats/issues/3833) allowed me to successfully ingest the logs.

The `rename` processor now looks like this for me:
```
    {
        "rename": {
          "field": "@timestamp",
          "ignore_missing": true,
          "target_field": "read_timestamp"
        }
      }
```

**Comment by ruflin** [comment]
Each beats event should always have a `@timestamp`, so it should always be there. Can you share the config you used on the beats side? Which version of ES are you using?

**Comment by cwurm** [comment]
Hm, I can't reproduce it anymore. Closing for now - sorry about the noise.
