### ISSUE TITLE
Heartbeat: Exported Fields - Name

### ISSUE THREAD

**Issue by dosera** [elastic/beats#3838]
The configured monitor field `name` overwrites the field `type` if it is set (as is documented [here](https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-heartbeat-options.html#monitor-name)).

E.g.

*Configuration*
```
- name: myname
  type: http
  urls:
    - http://www.myurl.com:123
  ...
```

currently results in a document like
```
...
{
   "monitor": "http@http://www.myurl.com:123",
   "type":  "myname",
   ...
}
```
If the name would have *not* been set, the result would look like
```
...
{
   "monitor": "http@http://www.myurl.com:123",
   "type":  "http",
   ...
}
```

I don't think this is very intuitive. Furthermore, if one wanted to get the `type` field while the `name` was specified, it would be required to parse the `monitor` field again.

Therefore I propose to change it, s.t. the name is an optional field that emerges only if it is set, e.g.

```
...
{
   "monitor": "http@http://www.myurl.com:123",
   "name":  "myname",
   "type": "http",
   ...
}
```
In the current proposal the `monitor` field is unchanged - maybe this should be adjusted like
`"monitor": "$name@$type@$url"` for example.

BR

[Elastic issue](https://discuss.elastic.co/t/exported-fields-name/80074/3).

**Comment by ruflin** [comment]
I think this also related to the discussion here about the general structure: https://github.com/elastic/beats/issues/3406

**Comment by monicasarbu** [comment]
@dosera Setting this issue as a bug, as the `monitor` should contain the name and not the type, and the `type` should contain the type, not the name. For example:
```
{
   "monitor": "myname@http://www.myurl.com:123",
   "type":  "http",
}
```
I agree with you that we need to also export the `name` in addition, so I am keeping the issue as an enhancement request as well.

**Comment by urso** [comment]
Event format and usage of name has been changed in #4091.
