### ISSUE TITLE
Support sampling and throttling

### ISSUE THREAD

**Issue by vjsamuel** [elastic/beats#3847]
It maybe a good idea to implement mechanisms through which we can dynamically start sampling the data from a source and also completely throttle events. This gives us the flexibility to dynamically change configs of a prospector to start sampling/throttling data from a give source if downstream starts to complain of over whelming data rates.

**Comment by monicasarbu** [comment]
Related to: https://github.com/elastic/beats/issues/1721

**Comment by lcaballero** [comment]
@vjsamuel I was thinking along the same lines.  I started a suggestion for the idea: [Rate limit published event](url).  Perhaps you can add a comment and provide some ideas about what the end implementation might look like.

**Comment by wu0407** [comment]
need this function

**Comment by mostlyjason** [comment]
I created a new meta-issue to track this request. Closing this one for now.

**Comment by amomchilov** [comment]
@mostlyjason Could you link it with this one, please?

**Comment by mostlyjason** [comment]
@amomchilov posted here https://github.com/elastic/beats/issues/17775
