### ISSUE TITLE
Not handling 100-continue properly

### ISSUE THREAD

**Issue by michaelgibson** [elastic/beats#385]
We have an application that uses the Expect: 100-continue header.
When packetbeat sees a response with a 100 status, it terminates the message and marks it complete.

The result is the next packet(the real response) is dropped:
 WARN Response from unknown transaction. Ignoring: TcpTuple src[x:x] dst[x:x] stream_id[25]

It seems like it should either recognize the 100 packet as part of the same stream, or ignore it and continue to the next response?

2015/11/18 00:47:27.426361 http.go:359: DBG  HTTP Method=POST, RequestUri=/xxxx
2015/11/18 00:47:27.426391 http.go:368: DBG  HTTP version 1.1
2015/11/18 00:47:27.426406 http.go:267: DBG  Header: 'content-type' Value: 'application/x-www-form-urlencoded; charset=UTF-8'
2015/11/18 00:47:27.426415 http.go:267: DBG  Header: 'host' Value: 'xxxxx'
2015/11/18 00:47:27.426425 http.go:267: DBG  Header: 'cookie' Value: 'xxxxx'
2015/11/18 00:47:27.426449 http.go:267: DBG  Header: 'content-length' Value: '400'
2015/11/18 00:47:27.426463 http.go:267: DBG  Header: 'expect' Value: '100-continue'
2015/11/18 00:47:27.426473 http.go:267: DBG  Header: 'x-cnection' Value: 'Close'
2015/11/18 00:47:27.426495 http.go:267: DBG  Header: 'x-forwarded-for' Value: 'xxxx'
2015/11/18 00:47:27.426515 http.go:404: DBG  Read body
2015/11/18 00:47:27.426812 http.go:223: DBG  parseResponseStatus: 100 Continue
2015/11/18 00:47:27.426829 http.go:338: DBG  HTTP status_code=100, status_phrase=Continue
2015/11/18 00:47:27.426841 http.go:368: DBG  HTTP version 1.1
2015/11/18 00:47:27.426853 http.go:385: DBG  Terminate response, status code 100
2015/11/18 00:47:27.426891 http.go:814: DBG  Received response with tuple: TcpTuple src[x:x] dst[x:x] stream_id[25]
2015/11/18 00:47:27.426927 http.go:818: WARN Response from unknown transaction. Ignoring: TcpTuple src[x:x] dst[x:x] stream_id[25]

**Comment by tsg** [comment]
Right, I consider this a bug. Thanks for reporting.
