### ISSUE TITLE
uint64 larger than 2^63-1 are not indexed

### ISSUE THREAD

**Issue by tsg** [elastic/beats#3877]
For several fields created by the Beats (e.g. the Metricbeat `system.network.in.packets` & friends) we use `uint64` counters on the Go side. The Elasticsearch numeric type used for them (long), however, is signed. Trying to index a number larger than 2^63-1, results in an ES exception:

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse [system.network.in.packets]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse [system.network.in.packets]",
    "caused_by": {
      "type": "json_parse_exception",
      "reason": "Numeric value (9223372036854775808) out of range of long (-9223372036854775808 - 9223372036854775807)\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@2d6b432e; line: 5, column: 39]"
    }
  },
  "status": 400
}
```

This means that it's possible for long running systems to get into a long period of time in which all documents are rejected because of this.

A potential solution for this would be clear the highest order bit automatically in Beats, before publishing the events. This would mean that the counters wrap at 2^63-1 instead of 2^64-1, effectively meaning that we switch to "uint63".

We should investigate how this is displayed by Kibana when the 1st derivative is taken.

CC @stevedodson @simianhacker

**Comment by ruflin** [comment]
This issue here is related: https://github.com/elastic/beats/issues/3687

**Comment by urso** [comment]
Beats 7.0 automatically applies a mask limiting uint64 values to `2^63 -1`.
Follow up: https://github.com/elastic/beats/issues/9271
