### ISSUE TITLE
beats-dashboard doesn't have mysql metricbeat dashboards

### ISSUE THREAD

**Issue by vjsamuel** [elastic/beats#3880]
I tried getting https://artifacts.elastic.co/downloads/beats/beats-dashboards/beats-dashboards-5.3.0.zip and loading them on metricbeat 5.3 using import_dashboards utility but mysql dashboards didnt get loaded. On looking closer into the zip file, looks like the metricbeat dashboards for mysql seem to be missing.

**Comment by ruflin** [comment]
The mysql dashboards didn't make it into 5.3. They will only be part of 5.4: https://github.com/elastic/beats/pull/3720 Any reason you expected them to be in 5.3?
