### ISSUE TITLE
feature reguest: Logstash module for Logstash Monitoring API

### ISSUE THREAD

**Issue by JakeFromTheDark** [elastic/beats#3886]
Why to download, compile, package, deploy and maintain a community [LogstashBeat](https://github.com/consulthys/logstashbeat), if MetricBeat is the ideal tool for collecting [Logstash5 Monitoring API](https://www.elastic.co/guide/en/logstash/current/monitoring.html)?

**Comment by ruflin** [comment]
Closing as a basic LS module was added to Metricbeat. More metrics have to be added over time.
