### ISSUE TITLE
feature reguest: RabbitMQ module for RabbitMQ Management HTTP Stats

### ISSUE THREAD

**Issue by JakeFromTheDark** [elastic/beats#3887]
It's useful to collect [RabbitMQ Management HTTP Stats](https://rawcdn.githack.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_9/priv/www/doc/stats.html).

**Comment by ruflin** [comment]
Fully agree, it would be great to have a RabbitMQ module in metricbeat. As it seems to be HTTP and JSON, it should be fairly easy to do as there are several existing helpers.

**Comment by amandahla** [comment]
Can I give it a try? :-)

**Comment by ruflin** [comment]
@amandahla That would be great.

**Comment by ruflin** [comment]
Closing this as we have a quite a few PR's related to this in the repo now.
