### ISSUE TITLE
[Linux Integrations] [Auditbeat] Missing Fields causing Mapping conflicts

### ISSUE THREAD

**Issue by Omolola-Akinleye** [elastic/beats#38989]
When looking at the Data View, I see there are some mapping conflicts where `host.pid_ns_ino`, `process.entry_leader.start`, `process.group_leader.start`,  and  `process.session_leader.start`. 

For confirmed bugs, please report:
- Version: 8.14.0
- Operating System: Linux

See [Session View Credentials](https://p.elstc.co/paste/Ci0L3gSA#ASz3bkZps3AsJQyDlHDagExU2LK0-cLTuqc+aq/sf1E)

1. Go to Stacks Management> Data Views
2. Select `.alerts-security.alerts-default,apm-*-transaction*,auditbeat-*,endgame-*,filebeat-*,logs-*,packetbeat-*,traces-apm*,winlogbeat-*,-*elastic-cloud-logs-* ` index
3. Click `View Conflicts` under Mapping conflicts
4. Click edit icon and you see field value is not set
<img width="1025" alt="image" src="https://github.com/elastic/beats/assets/17135495/31c7da2f-e481-455b-b7d0-2c35e757fcbf">
5. Copy `_id` value and query `_id` in Discover
<img width="1683" alt="image" src="https://github.com/elastic/beats/assets/17135495/9b7fc4e4-67d3-4251-92a3-e593d1177949">

**Comment by mjwolf** [comment]
Completed with https://github.com/elastic/beats/pull/38994
