### ISSUE TITLE
upgrade winlogbeat from 8.12.2 to 8.13.2 MSI added trailing slashes to service regkey

### ISSUE THREAD

**Issue by rismoney** [elastic/beats#38992]
Operating System: Windows 10,11 and 2019

registryPath = "HKLM:\SYSTEM\CurrentControlSet\Services\winlogbeat\Imagepath"

C:\Program Files\Elastic\Beats\8.13.2\winlogbeat\winlogbeat.exe" --path.home "C:\Program Files\Elastic\Beats\8.13.2\winlogbeat\" --path.config "C:\Program Files\Elastic\Beats\8.13.2\winlogbeat\" --path.data "C:\Program Files\Elastic\Beats\8.13.2\winlogbeat\" --path.logs "C:\Program Files\Elastic\Beats\8.13.2\winlogbeat\" -E logging.files.redirect_stderr=true'

The above 4 paths improperly contain a trailing slash, preventing the service from starting.
Removal of them allows the service to properly start.

**Comment by jlind23** [comment]
Thanks @rismoney for creating this. This is a known issue for which the fix has been merged on https://github.com/elastic/elastic-stack-installers/pull/264
