### ISSUE TITLE
Filebeats prerequisite: GeoIP plugin

### ISSUE THREAD

**Issue by bohyun-e** [elastic/beats#3910]
We ask the users to install the ingest-geoip plugin but do not explain why the users need them. 

![image](https://cloud.githubusercontent.com/assets/18126877/24677081/64d5b16e-193a-11e7-9795-dcfd5d5e7a34.png)

cc: @tsg for providing the reasons why the users might need them (p.s. how far do we want to go about explaining the why here? )

cc: @dedemorton for docs

**Comment by dedemorton** [comment]
#3928 closes this issue.
