### ISSUE TITLE
Start Filebeat instruction

### ISSUE THREAD

**Issue by bohyun-e** [elastic/beats#3911]
Not sure if this is just me but when I run
`filebeat -e -modules=system -setup`
-bash: filebeat: command not found

Following the documentation, Filebeat modules don't start.
![image](https://cloud.githubusercontent.com/assets/18126877/24678705/8559778a-1940-11e7-9bcf-3e2c5b08e85c.png)

I have to run `./filebeat -e -modules=system -setup` 

cc: @tsg @dedemorton

**Comment by andrewkroh** [comment]
And if you install via RPM or deb then you probably should use the wrapper script which is on the `PATH`.

`$ filebeat.sh  -e -modules=system -setup`

**Comment by dedemorton** [comment]
We should probably look at the issue from the perspective of how we tell users to run commands in general. Do we always provide a variation for each supported platform? Or do we expect the users to know enough about their OS to execute a program without giving them the exact syntax for each platform? We are relatively inconsistent in general wrt how we do this (sometimes we show `./filebeat` for example, and sometimes we show `filebeat`. In some places, we provide examples for each platform:
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-starting.html

Obviously, showing the command for each platform is the clearest, but might actually make the doc harder to read, especially where we provide multiple examples.  

I wonder why we can't have a more OS-agnostic command for running Beats (similar to what Elasticsearch and Logstash do).  @andrewkroh Any thoughts about this last point?

**Comment by bohyun-e** [comment]
>In some places, we provide examples for each platform:
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-starting.html

I really like the fact that we do this in many parts of our doc. 

>Or do we expect the users to know enough about their OS to execute a program without giving them the exact syntax for each platform? 

I think we can't expect this even though the users may know what OS they are on, when it comes to using new products and given a documentation, it is in human nature to sometimes blindly follow the guide.

**Comment by tbragin** [comment]
@dedemorton Would you consider this issue closed? I ran into some other docs related issues with the Filebeat system module. I'll open a new ticket if that's alright

**Comment by dedemorton** [comment]
@tbragin No, it's not closed yet because it affects more than just running filebeat modules. TBH, this has been lower on my list of priorities than other tasks because the problem does not seem to be a common pain point for users.

**Comment by dedemorton** [comment]
I guess as a stop-gap, I can change the commands to use ./ so that we're at least consistent in places where we don't provide examples for multiple platforms.

**Comment by dedemorton** [comment]
I'm closing this issue because I haven't seen any support issues or forum discussions about users who were confused about how to run the Filebeat executable on their OS. I've already updated the examples to use the more Mac-friendly `./` syntax, so I think we're covered.
