### ISSUE TITLE
Elasticsearch output can report an incorrect count for active events

### ISSUE THREAD

**Issue by faec** [elastic/beats#39146]
The metrics value `monitoring.metrics.beat.libbeat.output.events.active` can be skewed to inaccurate totals. I observed this in `main` after heavy ingestion that concluded (with all events ingested and no genuine active events) with an `events.active` of 959. `filebeat.events.active` showed the correct total of 0. (Of the two, Filebeat is usually the lagging metric, since it receives acknowledgment notifications later than the output.)

The run where this issue was observed involved both batch splitting and 529 errors from upstream, so either or both of those could be factors.

**Comment by yugalkaushik** [comment]
hi everyone, I just stepped into open-source and can anyone guide me through the documentations.

**Comment by yugalkaushik** [comment]
Noo I was going through some issues but realised I need to go through the
documentation of your organization to contribute with efficiency. So is
there any medium I can learn and get an idea a.

**Comment by pierrehilbert** [comment]
Best would be to open another issue to discuss this and avoid bringing content not related to this issue here.
You can start by looking at https://www.elastic.co/guide/en/beats/devguide/current/beats-contributing.html to get more information about how to contribute.
