### ISSUE TITLE
Collect kube_pod_status_ready_time from KSM for kubernetes.state_pod metriscet

### ISSUE THREAD

**Issue by MichaelKatsoulis** [elastic/beats#39158]
Kube-state-metrics reports `kube_pod_status_ready_time` metric:
```
kube_pod_status_ready_time{namespace="kube-system",pod="kube-apiserver-kind-control-plane",uid="8cb4d4e1-b8b3-4bab-adc2-3e9d3687724c"} 1.698675692e+09
```

This metric indicates how long it took for a pod to become ready.  In kubernetes `state_pod` metricset, we are currently collecting it.
It is a useful metric for Elastic's serverless platform for monitoring how long it took for applications to start.

**Comment by mduarte** [comment]
I was actually thinking that perhaps we could also get other time metrics since they could be used to monitor other issues and alert on them.

e.g.
```
kube_pod_start_time
kube_pod_completion_time
kube_pod_status_ready_time
kube_pod_status_scheduled_time
```
