### ISSUE TITLE
Heartbeat - Use IP type in Elasticsearch mapping

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#3926]
For Heartbeat it would be nice to the the `ip` type in Elasticsearch mapping for the `ip` field. This would enable users to answer questions like, "what's the average RTT for hosts in the subnet where `ip:10.10.0.0/16`?"

- Version: 5.3

**Comment by andrewkroh** [comment]
For example, the two distinct groups in this graph are made of hosts from different regions that are separate subnets. And I want to select by subnet.
<img width="1429" alt="icmp-rtt" src="https://cloud.githubusercontent.com/assets/4565752/24722983/bad025b6-1a13-11e7-9a2f-96dfc0b392d3.png">

**Comment by glefloch** [comment]
Hi, I would like to start contributing to the project.
 Can this issue be part of an external contribution?

**Comment by andrewkroh** [comment]
Yes, absolutely. To you get started, I think the mapping in question comes from [fields.yml](https://github.com/elastic/beats/blob/master/heartbeat/_meta/fields.yml#L38). After making changes to that file run `make update` in the heartbeat dir.
