### ISSUE TITLE
Remove the yellow box from the dev guide docs pages

### ISSUE THREAD

**Issue by tsg** [elastic/beats#3934]
After recent changes in the "create your own Beat" workflow, we recommend people to base their work on the stable version of libbeat, not the master one. This means we no longer need this warning: 

![screen shot 2017-04-06 at 10 45 11](https://cloud.githubusercontent.com/assets/101817/24745470/2492dfbe-1ab6-11e7-9219-67cf3b48f495.png)

Pinging @dedemorton :)

**Comment by dedemorton** [comment]
Closed with #3958
