### ISSUE TITLE
Please add authentication on couchbase metricbeat module

### ISSUE THREAD

**Issue by chdorb** [elastic/beats#3940]
The metricbeat couchbase module works fine, but when password is set on bucket, the module get 401 responses, and there is no way to pass credentials.

**Comment by andrewkroh** [comment]
Have you tried adding a username and password to the config?

```
- module: couchbase
  metricsets: ["cluster", "node", "bucket"]
  hosts: ["localhost:8091"]
  username: me
  password: shh
```

Or embed the params in the URL:

```
- module: couchbase
  metricsets: ["cluster", "node", "bucket"]
  hosts: ["http://me:shh@localhost:8091"]
```

**Comment by andrewkroh** [comment]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

**Comment by chdorb** [comment]
Ok that works fine with username and password to config.
Sorry…
