### ISSUE TITLE
[Filebeat] CEL input - set the default User-Agent

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#39502]
**Describe the enhancement:**

Set a `User-Agent` string for the CEL input by default that identifies it as Filebeat and includes the version.

**Describe a specific use case for the enhancement or feature:**

When monitoring the logs of services that Fleet integrations connect to or proxies the requests pass through, it is very useful to have an identifiable User-Agent string. The current header from CEL defaults to:

`User-Agent: Go-http-client/1.1`

**Comment by efd6** [comment]
The design intention here was to do that in the CEL program since different programs really should have different UAs.
