### ISSUE TITLE
Filebeat process lookup

### ISSUE THREAD

**Issue by urso** [elastic/beats#3957]
Would be nice for filebeat to lookup processes reading/writing files being shipped (optionally). The process-metadata (if available) will be used to enhance the file events.

Note: the information can also be used to close a rotated file, by forcing harvester to close a file on EOF, if no process is having an open file-descriptor.

**Comment by tsg** [comment]
Recently @andrewkroh mentioned a similar idea (just wanted to ping him here :) ).
