### ISSUE TITLE
Delay in sending logs with fielbeat 8.12.1

### ISSUE THREAD

**Issue by sasikiranvaddi** [elastic/beats#39614]
There has been a noticeable delay observed when sending logs to using filebat 8.12.1

filebeat configuration used
-----------------------------------
filebeat.inputs:
- type: stdin
  json.keys_under_root: true
processors:
- drop_event:
    when:
      !java.util.LinkedHashMap
      or: 
      - !java.util.LinkedHashMap
         equals: !java.util.LinkedHashMap
            exclude: Hello
      - !java.util.LinkedHashMap
         equals: !java.util.LinkedHashMap
            exclude2: Hello Testing

- drop_fields:
   fields: ["input","offset","log","@metadata","host","beat","prospector","source"]
output.console:
  pretty: false

**Comment by pierrehilbert** [comment]
Hello @sasikiranvaddi 
Have you seeing the same delay without the multiple exclusion filters? Is it only for the first events or every events?
Would like to understand if this is linked to the new defaults we introduced in 8.12: https://www.elastic.co/fr/blog/using-elastic-agent-performance-presets-in-8-12

**Comment by sasikiranvaddi** [comment]
Hi @pierrehilbert,
Yes we fine tuned flush timeout as specified [1], by setting queue.mem.flush.timeout: 1s in output section on monday and observed the logs are receiving faster. We are trying to perform some more tests to confirm that it has improved.

[1]: https://github.com/elastic/beats/blob/v8.12.1/CHANGELOG.asciidoc

**Comment by pierrehilbert** [comment]
Keep me honest here but it doesn't seem to be a problem with the exclusion filters then but with the new default you have compare to the behavior you were expecting.
@faec do you have some recommendation to share here to help them getting the expected behavior?

**Comment by sasikiranvaddi** [comment]
Hi @pierrehilbert,
After a quick test, the behavior of delayed events are observed from 8.12.1 even without including exclusion/inclusion filters. After adding queue.mem.flush.timeout then the events are sent faster to the output source.
I'll update the title accordingly.

**Comment by pierrehilbert** [comment]
Yes this is definitively related to this parameter that we changed to improve overall performances observed by the users.

**Comment by sasikiranvaddi** [comment]
Thank you @pierrehilbert,
We will keep this Bug open for few days once our tests are concluded and if the results found to be positive then we can close the Bug.

**Comment by faec** [comment]
Yes, it sounds to me like this is caused by the presets changes. If you want to stick with a general preset you can try `preset: latency`, but you can also just customize your performance parameters as before. If latency is at a premium you might even consider `queue.mem.flush.timeout: 0`, which will send events without any delay.

**Comment by sasikiranvaddi** [comment]
Hi @faec,
Got your point. Thank you for the info.

**Comment by sasikiranvaddi** [comment]
Hi @faec, @pierrehilbert ,
The test results looks promising. Thank you for the support.
I will be closing the ticket.
