### ISSUE TITLE
Unable to use apm-server dynamic kafka topic with elastic-agent-standalone

### ISSUE THREAD

**Issue by heisGarvit** [elastic/beats#39628]
Hi,

I am using the following config:

    kafka-output:
            type: kafka
            hosts:
              - 'kafka:9092'
            client_id: kafka-output
            topic: '%{[data_stream.type]}-%{[data_stream.dataset]}-%{[data_stream.namespace]}'

and am getting the following error:

    {
      "log.level": "error",
      "@timestamp": "2024-05-20T12:45:50.189Z",
      "message": "runner returned with an error",
      "component": {
        "binary": "apm-server",
        "dataset": "elastic_agent.apm_server",
        "id": "kafka-output",
        "type": "apm"
      },
      "log": {
        "source": "kafka-output"
      },
      "error": {
        "message": "failed to create libbeat output pipeline: topic '%{[data_stream.type]}-%{[data_stream.dataset]}-%{[data_stream.namespace]}' is invalid, it must match '[a-zA-Z0-9._-]' accessing 'output.kafka'"
      },
      "ecs.version": "1.6.0",
      "log.origin": {
        "file.line": 190,
        "file.name": "beatcmd/reloader.go",
        "function": "github.com/elastic/apm-server/internal/beatcmd.(*Reloader).reload.func1"
      },
      "service.name": "apm-server"
    }

Related Code:

https://github.com/elastic/beats/blob/0fd63999c524cb681dc4c6d760d73c94125227bb/libbeat/outputs/kafka/config.go#L198

My Question is how do I use dynamic topic config?

**Comment by ycombinator** [comment]
Hi @heisGarvit, we use GitHub issues in this repository for bug reports and enhancement requests.  For questions such as yours, please use https://discuss.elastic.co/c/elastic-stack/beats/28.  Thank you!
