### ISSUE TITLE
Filebeat increasing memory consumption until eventually restarts.

### ISSUE THREAD

**Issue by jecjecx** [elastic/beats#39625]
So filebeat keeps on increasing memory consumption until eventually it restarts. We have tried the config 
queue.mem:
    events: 2048
    flush.min_events: 256
    flush.timeout: 5s
    
And as some other forums suggested the autodiscover or cronjob being disabled, but we do not have those in our config files. Any help with this?

![MicrosoftTeams-image (1)](https://github.com/elastic/beats/assets/70559946/a40b8e8f-f897-4a19-a525-75d3c22107ea)

**Comment by ycombinator** [comment]
What version of Filebeat are you running? What platform are you running on?

**Comment by jecjecx** [comment]
> What version of Filebeat are you running? What platform are you running on?

We are currently in Filebeat 8.13

**Comment by faec** [comment]
@jecjecx Can you provide a copy of your `filebeat.yml` to troubleshoot? Also, what is the memory limit that you're hitting?

**Comment by pierrehilbert** [comment]
Closing for now, @jecjecx don't hesitate to reopen if needed.
