### ISSUE TITLE
Filebeat issue,Container.Name -Docker contaibner logs are not retrieved at elestice search

### ISSUE THREAD

**Issue by prasanna7763** [elastic/beats#39640]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

filebeat.inputs:

- type: log
  scan_frequency: 1s
  path:
  - '/mnt/docker-data-v2/volumes/*/*/*.log'
    
- type: container
  enabled: true
  paths:
    - '/mnt/docker-data-v2/containers/*/*.log'
    - '/mnt/docker-data-v2/volumes/*/*/*.log' 

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

setup.template.settings:
  index.number_of_shards: 1
   
processors:
- add_docker_metadata: ~
    match_source: true
    match_source_index: 3

output.elasticsearch:
  hosts: ["XX.xx.xx.xx:9200"]
  username: "elastic"
  password: "***************"

From the above code all the docker container logs are not retrieved ,Front end logs are coming,Backend logs are not retrieved.
How to to get all docker logs in docker machine.

**Comment by prasanna7763** [comment]
From the above the docker logs are not retrieved ,Front end logs are coming,Backend logs are not retrieved

**Comment by ycombinator** [comment]
Hi @prasanna7763, we use GitHub issues in this repository for bug reports and enhancement requests. For questions such as yours, please use https://discuss.elastic.co/c/elastic-stack/beats/28. Thank you!
