### ISSUE TITLE
x-pack/filebeat/input/cel TestInput/retry_failure on Windows

### ISSUE THREAD

**Issue by dliappis** [elastic/beats#39657]
## Flaky Test

* **Test Name:** x-pack/filebeat/input/cel
* **Link:** https://buildkite.com/elastic/beats-xpack-filebeat/builds/2898#018f9eea-cbed-4f71-b082-7a697679a36b/98-468
* **Branch:** Seen in PRs against main
* **Artifact Link:** If available, attach the generated zip artifact associated with the stack trace for this failure.
* **Notes:** As the error is `failed to unmarshal JSON message: unexpected end of JSON input` it indicates that perhaps the timeout was too short for the CI agent (Windows)

### Stack Trace

```
=== Failed
=== FAIL: x-pack/filebeat/input/cel TestInput/retry_failure (1.03s)
    input_test.go:1602: unexpected result for event 0: got:- want:+
          mapstr.M{
        - 	"error": map[string]any{
        - 		"message": string("failed eval: ERROR: <input>:2:19: failed to unmarshal JSON message: unexpected end of JSON input\n |  get(state.url).as(resp, {\n "...),
        - 	},
        + 	"hello": string("world"),
          }
=== FAIL: x-pack/filebeat/input/cel TestInput (31.40s)
```

**Comment by alexsapran** [comment]
I'm just linking another occurrence of this for the 8.14 branch: https://buildkite.com/elastic/beats-xpack-filebeat/builds/3010#018fb87a-f9bb-4c4a-ac9f-6b294e20b093. This time, it happened with the Linux tests, not Windows.
