### ISSUE TITLE
feature request: Support epoch seconds in timeformat

### ISSUE THREAD

**Issue by JakeFromTheDark** [elastic/beats#3969]
It's missing here for no reason: https://godoc.org/github.com/elastic/beats/libbeat/common/dtfmt

It's SUPER useful to send heartbeat HTTP messages with a field filled by actual date in UNIX timestamp format, you know?

**Comment by ruflin** [comment]
@JakeFromTheDark Thanks for opening the feature request. I don't know how easy this would be to add but @urso can comment on that one.

**Comment by urso** [comment]
I think it would be quite easy, but result will be a string type. Not sure which format string character to reserve though. Plus, you want the timestamp depend on localhost or adjust to another zimezone (e.g. UTC 0)?

**Comment by JakeFromTheDark** [comment]
_Unix time (also known as POSIX time or epoch time) is defined as the number of seconds that have elapsed since 00:00:00 Coordinated Universal Time (UTC), Thursday, 1 January 1970, not counting leap seconds._ So it's already in UTC. It's an integer type but converted to a string at the end. 

Next to it, still _Not yet supported_  **S** (fraction of second in millis) is also welcome, because then one can create rough times "1492505607" ("%{+U}") or even precise "1492505607.987" ("%{+U.S}") ;)

**Comment by urso** [comment]
Thanks for the clarification.

+1 for `U=Unix time` and adding support for `S`.
