### ISSUE TITLE
[Elastic Agent] Allow Metricbeat metricsets to report their status to the Elastic Agent

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#39736]
In https://github.com/elastic/beats/issues/39735 a status reporter was passed into the Beats object reloader and propagated through to Filebeat inputs via the input V2 interface.

Identify how to propagate the status reporter into Metricbeat metricsets to allow them to report their status to the Elastic Agent when they encounter errors.

Choose a metricset to use as a reference implementation and have it report errors using the control protocol.

**Comment by cmacknz** [comment]
https://github.com/elastic/beats/issues/39737 is an obvious candidate to do alongside this one, but we could also pick a metricset that requires a username/password combination as it will have a much clearer criteria for when to report the failed state.

**Comment by VihasMakwana** [comment]
@jlind23 @pierrehilbert attaching the screenshot of Kibana with a custom build.

<img width="1503" alt="Screenshot 2024-07-19 at 2 02 29 PM" src="https://github.com/user-attachments/assets/8bf7b7d8-8460-41c9-a485-ab0f4e64cb06">

**Comment by VihasMakwana** [comment]
Waiting on https://github.com/elastic/beats/pull/40298

**Comment by VihasMakwana** [comment]
<img width="527" alt="Screenshot 2024-07-24 at 3 00 33 PM" src="https://github.com/user-attachments/assets/b8cb7d7a-f17e-4a1c-a6df-c89209d57962">

Screenshot of error event.
