### ISSUE TITLE
Store secrets in a keystore

### ISSUE THREAD

**Issue by tsg** [elastic/beats#3982]
The Beats configuration files tend to contain a lot of credentials, which can be problematic if the configuration files are accidentally posted online or leaked in any other way. The Beats are already strict about the file permissions of their configuration file, refusing to start if the files are writable or readable by anyone else.

The next step in protecting these secrets is to store them in a separate binary keystore, where they are at least obfuscated (true encryption might be difficult to bootstrap).

We plan to follow the Elasticsearch model started in https://github.com/elastic/elasticsearch/pull/22335. We aim to align as much as possible with ES at the user interface level, meaning similar commands to manage these key stores and a similar way of referencing them in the YAML files. The actual binary representation of the keystore might be different.

**Comment by ph** [comment]
I am starting to take a look at this issue.

**Comment by tylersmalley** [comment]
@ph, I almost have a PR ready for Kibana using AES 256 GCM. Let me know if you would like to chat.

**Comment by ph** [comment]
@tylersmalley Awesome is there is a link to that code anywhere?

**Comment by tylersmalley** [comment]
@ph Here is the WIP PR: https://github.com/elastic/kibana/pull/14714

**Comment by ph** [comment]
# Password Keystore

We are currently defining our secrets directly in our configuration or on the command line (-E), we want to allow users to securely store the data on disk and be able to reference it in either the configuration file or the command line.

Lets take the example or the current credentials definition:

```yaml
output.elasticsearch:
  hosts: ["localhost:9200"]
  username: "elastic"
  password: "changeme"
```

We would turn this definition into something like this:

```yaml
output.elasticsearch:
  hosts: ["localhost:9200"]
  username: "elastic"
  password: %{keystore:output.elasticsearch.password}
```

After the configuration file is parsed we will have access to the concrete unencrypted values, I think this is OK for the first iteration.

**There is two type of secrets that we need to take into consideration.**

1. Static credentials, that will be always valid and never changes
2. Temporary credentials that can revoked or renewed (vault)


For the first iteration we will do 1.

## Implementation notes

- We assume that we are loading a local file: `data/keystore`
- The password for the store wont be configurable in the first iteration
- check minimal permission/mask on the keystore file
- Managing secrets will be a beats subcommand `keystore` that we will wrap into a `beat-keystore` shell script.
  - create: creates a new keystore (Need to think about different key store provider)
  - list: list entries in the keystore
  - add: add a string in the keystore
  - remove: remove a settings from the keystore
- File backend will probably need a version number, we might change the structure so we will need to upgrade from the original format.
- First version doesn't allow to set a password on the keystore
- if possible provide flexibility for future backend
- PKCS12 format


#### High level interaction with the store

```golang
keystore := NewKeystore("~/hola.keystore", "secret-password")
keystore.store("elasticsearch.password", "abc1234")
keystore.save() # persist?
secret = keystore.retrieve("elasticsearch.password")
secret.Get() => "abc1234" # I prefer not returning the primitive because of string revokation/renewal that could done in a upcoming feature, also add guard to prevent serialization to log

```

## Steps in other PRs

- Add support for user to set a password on the keystore
- Add support for entering password on boot
- Create a `SecureString` type that can be used by other part of the code to access credentials, but will prevent leak to the log and can also deal with password renewal.

## Open questions

- Do we need to restrict who can access the store? Module A vs Module B

---

Implementation references:

Kibana:
 - https://github.com/elastic/kibana/pull/14714

Logstash:
https://github.com/elastic/logstash/issues/6892

Elasticsearch:
- https://github.com/elastic/elasticsearch/pull/22335
-https://www.elastic.co/guide/en/elasticsearch/reference/5.5/secure-settings.html

**Comment by ph** [comment]
forgot to ping you on this @joshbressers ^

**Comment by joshbressers** [comment]
This looks good to me. To answer your question, I wouldn't worry about restricting access to keystores. If admins want this functionality they should be running separate processes with different permissions.

**Comment by ph** [comment]
@tsg @urso  Concerning the syntax in the configuration file, I've made a conscious choice to use `%` instead of `$`, to make sure we can distinct the **keystore** values vs the [environment variables](https://www.elastic.co/guide/en/beats/filebeat/6.x/using-environ-vars.html)

We could also normalize the syntax for 7.X to allow user to define environment variable using the following syntax:

```
```

**Comment by tylersmalley** [comment]
Is there a reason for requiring the YAML file to reference values from the keystore? In Elasticsearch, adding a setting can either be persisted either in the `elasticsearch.yml` or the Keystore. I want to make sure we don't diverge too much from app-to-app.

**Comment by ph** [comment]
@tylersmalley You are right, the integration diverge from ES and your implementation, I need to give it some thoughts. We could certainly do the same things, I am a little worried about the flexibility in our context.

This doesn't change the underlying structure to keep the secret only the integration in our products.

**Comment by ph** [comment]
@tylersmalley after looking at the code we can do it the same way, it will be similar to our current behavior on `-E`, we can always add the parsing of theses _template tag_ later.

**Comment by joshbressers** [comment]
I sort of like the template tag idea. I'd love to see the ability to also grab secrets from vault or some other system in the future for example.

**Comment by tsg** [comment]
I'm +1 on starting with overrides like ES and KB first, and then also add support for template tags.

What I like about overrrides is that we don't need to change anything in the current configuration and the following will work (pseudo-code):

```
./metricbeat secrets set cloud.auth
   <prompts for the secret>
  cloud.auth=....
./metricbeat -E cloud.id='<cloud-id>'
```

And with the above we require no configuration edits, and we leak no passwords in the `ps` output or the shell history.

**Comment by urso** [comment]
Merging some 'encrypted' settings into the config should be quite easy to implement.

Reason for referencing credentials with variables could be us wanting some external 'vault/store/service' + allowing users to configure potentially multiple 'vaults'.

This discussion is clearly about storing secret data local to the beat. In the end, we might have both.  The  local store being basically encrypted config overwrites and still allow for passwords via external service using variables.

**Comment by ph** [comment]
Just one more thing, I would expect we have this priority in the merge, if we redefine keys.

1. yaml
2. keystore
3. -E (cli override)


the last one is necessary for quick debug.

**Comment by ph** [comment]
following this discussion I have update my [original comment](https://github.com/elastic/beats/issues/3982#issuecomment-342582320)

**Comment by ph** [comment]
@jaymode @joshbressers @tylersmalley 

I've looked at the kibana implementation, it's doesn't seem to save anything in the PKCS12 format, PKCS12 format support writing in golang seems a [bit hairy](https://github.com/golang/go/issues/14125) even reading is problematic in some case. 

The kibana implementation seems to have gone to write their own format to disk, I don't the discussion anywhere? 

I have a similar flow here, that use the same _Password-Based Key Derivation Function 2_ + aes-gcm to encrypt data on disk.

**Comment by tylersmalley** [comment]
@ph, PKCS12 format would have been pretty difficult for us as well which is why we went the route we did.

**Comment by joshbressers** [comment]
No PKCS12 is fine.

The Kibana issue can be found here:
https://github.com/elastic/kibana/issues/11091

**Comment by ph** [comment]
After sync with @jakelandis, @tylersmalley, @joshbressers and internally with the beats team we have decided to implement the template solution to make this choices explicit instead of implicit first. The main reason was the unfriendly usage of the implicit configuration when using modules.

We will revisit the implicit after 6.2.

The template will be the same as the environment variables syntax and will have the following priority:

- Keystore
- Environment variable
- variable expansion (referencing other yaml keys)

**Comment by gekkeharry13** [comment]
Hello, I would like to know if any progress is being made regarding this feature. Next to this I would like to know if Windows Certificate Store for the Windows beats is also considered for implementation. This would significally enhance the implementation process for Windows collecting.
