### ISSUE TITLE
The 7.17.22 release notes do not exist

### ISSUE THREAD

**Issue by edhgoose** [elastic/beats#39916]
The [GitHub Tag for v7.17.22](https://github.com/elastic/beats/releases/tag/v7.17.22) refers to this url for the release notes:

https://www.elastic.co/guide/en/beats/libbeat/7.17/release-notes-7.17.22.html

This page does not exist.

Can it be published?

**Comment by jlind23** [comment]
Thanks @edhgoose for raising this. Once https://github.com/elastic/beats/pull/39855 is merged the release note will be updated accordingly, I am sorry for any trouble this might have caused.

**Comment by jlind23** [comment]
Release note is now available hence closing this as fixed.

**Comment by edhgoose** [comment]
Thanks @jlind23 :)
