### ISSUE TITLE
Update curl examples in docs to use the required headers

### ISSUE THREAD

**Issue by tsg** [elastic/beats#3991]
Newer than 5.3 ES version require to set the Content-Type on PUT and GET request. Wherever we have `curl` examples in the docs ([example](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-template.html#load-template-manually)) we should replace them with: `curl -H "Content-Type: application/json" -XGET ...`

**Comment by dedemorton** [comment]
Closing because this is fixed in #4020
