### ISSUE TITLE
Doc:  Clarify features regexp support applies to

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#3995]
Currently, the filebeat regex support doc (https://www.elastic.co/guide/en/beats/filebeat/current/regexp-support.html) is under its own top level heading.  While it links to managing multiline page for additional examples, it doesn't explicitly call out what features support regexp (eg. multiline, include_lines, exclude_lines, etc.).  At the top of the page, it simply says "Filebeat regular expression support is based on RE2.".

One place that does not support regular expressions is the [propsector path](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#prospector-paths) which only supports Golang Glob patterns.

It can be helpful to call this out on the https://www.elastic.co/guide/en/beats/filebeat/current/regexp-support.html page directly.  We can probably simply put a note in there that says prospector paths must use Golang glob patterns instead (and cross reference the Goland glob pattern link or the #prospector-paths anchor).

**Comment by superwhykz** [comment]
Thank you @ppf2 !

**Comment by dedemorton** [comment]
this is fixed in #4451
