### ISSUE TITLE
Filebeat Google Cloud Storage Input requires JSON or file credentials for authentication which causes issues when using workload identity

### ISSUE THREAD

**Issue by bkaznowski** [elastic/beats#39977]
**Describe the enhancement:**
Make `auth.credentials_json.account_key` and `auth.credentials_file.path` optional so you can configure filebeat to set up the Google Storage client without either option.

**Describe a specific use case for the enhancement or feature:**
If you are running Filebeat in a Kubernetes cluster and want to use workload identity to authenticate with GCS then the documentation doesn't make it clear how to achieve this and the behaviour would suggest this isn't possible. It would be nice to either specifically call out the workaround in the documentation or to make both config options optional.

[This is the guide I was following](https://www.elastic.co/guide/en/beats/filebeat/8.14/filebeat-input-gcs.html) which says you must provide either a credentials JSON or a credentials file. However, workload identity doesn't require either.

**Existing workaround:**
There is a workaround that exists for now, which is to set an empty credentials file path. For example, `auth.credentials_file.path: ""`. This makes [filebeat think the credentials file path is set](https://github.com/elastic/beats/blob/8.14/x-pack/filebeat/input/gcs/client.go#L28-L32) and the Google Storage client will set this path. However, the GCS client treats an empty path identically to the scenario where a path isn't provided.

**Comment by andrewkroh** [comment]
I think the same logic used by the GCP Pub/Sub input could be implemented by the GCS input. If none of the config options are set then it checks if it can load application default credentials before failing.

https://github.com/elastic/beats/blob/d2c4c2d7150cb4cac8c929bf56bc7c1df34f1d45/x-pack/filebeat/input/gcppubsub/config.go#L45-L68

Does that sound correct to you @bkaznowski?

**Comment by bkaznowski** [comment]
Yes, I believe this sounds right. We use the gcp-pubsub input too and we haven't had any issues with using it alongside workload identity. It would also be a nice solution to bring both of these under the same behaviour

**Comment by alelevinas** [comment]
Hi @efd6  

I'm wondering how you are setting up Workload Identity because I'm having the same issue here.
I can authenticate correctly with GCS on filebeat 8.10 and `auth.credentials_file.path: ""` but when upgrading to 8.15 (and removing that line) I get 

```
{"log.level":"error","@timestamp":"2024-08-29T16:39:43.768Z","log.logger":"input.gcs","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/v2/compat.(*runner).Start.func1","file.name":"compat/compat.go","file.line":139},"message":"Input 'gcs' failed with: input logs-consumer failed: no valid auth specified","service.name":"filebeat","id":"logs-co
nsumer","ecs.version":"1.6.0"}
```

I'm running on GKE.
Service Account has the `iam.gke.io/gcp-service-account: ****` annotation and it works with filebeat 8.10


How are you setting up Workload Identity so that now it works???

**Comment by efd6** [comment]
Thanks @alelevinas, it looks like part of the process was omitted. Sending that now.
