### ISSUE TITLE
Regression: `host.hostname` is being lowercased

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#39993]
### Version
`8.15.0-SNAPSHOT`, `8.13.2`, likely any version >= `8.9.0`.

### Operating System
Windows 10, but quite likely this is happening on any Windows versions, and likely on any OS that allows setting a hostname with uppercase characters in it.

### Steps to Reproduce
1. Ensure that the host on which Agent is going to run has a hostname with uppercase characters in it, e.g. `DESKTOP-E39GQOG`.
1. Enroll Elastic Agent in Fleet, using the default policy with the `system` integration enabled.
2. About 30 seconds after enrolling, go to Kibana > Discover and look at the `logs-*` indices for data from the Agent.  Set up the columns as shown in the screenshot below.
   ![8 15 0-SNAPSHOT](https://github.com/elastic/beats/assets/51061/5f7e9489-8278-409e-beae-584e5760ba2b)
4. Note the values in the `host.hostname` column.

### Expected behavior
The values of the `host.hostname` field should be exactly the same as of the hostname from step 1 above, including matching the case exactly.

### Observed behavior
The values of the `host.hostname` field are lowercased.

### Other relevant information
This behavior is not observed in `8.8.2`:
![8 8 2](https://github.com/elastic/beats/assets/51061/a0b1a11d-3f2b-442c-9ebd-fd5c0a011613)

⚠️ When fixing this regression, only the value of the `host.hostname` field should be fixed.  The value of `host.name` should remain lowercased, as [mandated by ECS](https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-name).  Similarly, the value of `agent.name` should not be impacted by the fix either.

**Comment by efd6** [comment]
It looks to me like this happens because of elastic/go-sysinfo#180. This was picked up in e35a094c0cf432732391a536d079f2b763771dfc which is in the 8.9.
