### ISSUE TITLE
Docker memory metrics don't consider cgroups version of running container

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#40060]
Right now, the docker/memory metrics just do this to fetch RSS memory:

`totalRSS := myRawStat.Stats.MemoryStats.Stats["total_rss"]`

The problem is, the `Stats` object reports different metrics depending on the cgroups version: https://github.com/moby/moby/blob/master/daemon/stats_unix.go. That `total_rss` field isn't on V2.

The code doesn't consider this, and the docs only mention it briefly: https://docs.docker.com/engine/api/v1.45/#tag/Container/operation/ContainerStats

**Comment by andrew-moldovan** [comment]
@fearful-symmetry @pierrehilbert any updates on this one? It would really help us out with https://elasticco.atlassian.net/browse/CP-2371

**Comment by fearful-symmetry** [comment]
huh, I thought this was fixed months ago, I can take a look.
