### ISSUE TITLE
Document limitation of multiple host output interaction with LS when multiline is configured on the LS side

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#4008]
This is a high priority doc issue.

Here is the scenario:

* Beats is configured to have output.logstash output with multiple hosts in the hosts list.
* Logstash pipeline has a beats input with multiline codec in place to perform multiline processing.

The problem with the above setup is that if filebeat does not know about multiline (i.e. multiline is not configured via filebeat but as part of a LS input - this does not only apply to LS beats input, but any LS input that supports multiple hosts), it does not know which events belong together so it will happen that parts are sent to one host and other parts to an other host, causing a mixing of streams and corrupted event data generated.

Per @ruflin This is a known limitation and there isn't really a solution other than to configure multiline in beats instead of in Logstash.

Also, while filebeat knows which line is coming from which file, but without itself being configured for multiline, it will assume that they are independent events and will spool and batch them together over a single connection (for performance reasons).   This is also why it is recommended to configure multiline in the beats tier vs. Logstash.

I will suggest calling this out in both the multiline example section (https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html) and the hosts configuration for the LS output (https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html#hosts).

Related doc request for LS: https://github.com/logstash-plugins/logstash-input-beats/issues/199

**Comment by dedemorton** [comment]
Resolved in #4086
