### ISSUE TITLE
Rate limit "Cannot index event" log messages

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#40157]
https://github.com/elastic/beats/blob/032a4cfd5f3b8fa8354ac1e0062a0e1f196c60d0/libbeat/outputs/elasticsearch/client.go#L487-L491

The "Cannot index event" logs messages are a useful signal in the logs that events are being dropped and (as of 8.15.0) you should look at the local event log for the reason. 

Since this log message does not contain any useful debugging information, and has the potential to be generated for every event that flows through the pipeline, there is no value in logging it for each event.

Instead we should rate limit it so that it only appears once in a fixed interval when events are being dropped. The rate limit is initially proposed to be one message every 10 seconds. 

The rate limited message should include the number of events that dropped in the current interval. The message can be changed to something like **"Failed to index N events in last M seconds. Look at the event log to view the events and cause."**

**Comment by jlind23** [comment]
@pierrehilbert bumping the priority on this one as it recently had an impact on some users.
cc @lucabelluccini @nimarezainia

**Comment by AndersonQ** [comment]
@cmacknz, one question, should the report summarise how many events per status code? E.g.:
 - 10 events dropped:
   - 5: 402
   - 5: 403

**Comment by cmacknz** [comment]
It's useful if it is easy to do, if it adds significant complexity I wouldn't bother. The status code will be in the event logs.

**Comment by nimarezainia** [comment]
after speaking with @pierrehilbert, we would love to celebrate the benefits of the outcomes from this issue. Are we able to quantify the reduction in events/logs sent?

**Comment by AndersonQ** [comment]
> after speaking with @pierrehilbert, we would love to celebrate the benefits of the outcomes from this issue. Are we able to quantify the reduction in events/logs sent?

yes, if we have access to old logs, we can quantify it. I was actually thinking about quantifying it as well and add to the PR, but I got busy with other tasks.

let me try to make a quick and rough estimation

**Comment by konnextv** [comment]
I came across this error today in a Metricbeat log and am wondering where to find the mentioned event log? 
From my understanding I am looking at it and this is where I see the warning as well: `/var/log/metricbeat/metricbeat-20241002-7.ndjson`

**Comment by cmacknz** [comment]
You need to be on 8.15+, by default they are next to the regular logs. If you are below 8.15, you can see the cause by turning on debug logging in the regular log files.

See https://github.com/elastic/beats/blob/e345f285634d1478874a9a0ca8e4aab3611d33d4/metricbeat/metricbeat.reference.yml#L2458
