### ISSUE TITLE
mesos module : Track mesos run time stats with Metricbeat

### ISSUE THREAD

**Issue by shamimgeek** [elastic/beats#4018]
Is there any plan for mesos module ?. 

https://discuss.elastic.co/t/track-mesos-run-time-stats-with-metricbeat/78776

http://mesos.apache.org/documentation/latest/monitoring/

**Comment by tsg** [comment]
I'm not aware of anyone working on this, but we'd gladly accept it as a community contribution if anyone is wiling to spend the time.

**Comment by ruflin** [comment]
@shamimgeek I just did a quick local test with a mesos setup, and the endpoint seems all to be in http and json. That means adding it should be fairly simple. As an example have a look at the kubelet implementation: https://github.com/elastic/beats/blob/master/metricbeat/module/kubelet/node/node.go

Here is the dev guide: https://www.elastic.co/guide/en/beats/metricbeat/current/creating-metricsets.html
