### ISSUE TITLE
Custom Processor helper methods aren't exported

### ISSUE THREAD

**Issue by hartfordfive** [elastic/beats#4024]
Current Version: Master branch (34764057a533742c4ed3b5a1e61016a1797f85c0)

Currently I'm attempting to write a custom processor in a custom beat I'm creating although the [three helper methods](https://github.com/elastic/beats/blob/master/libbeat/processors/actions/checks.go) that are used when registering a processor `configChecked()`, `requiredFields()`, and `allowedFields()` aren't exported thus are only available to the processors within the **[actions](https://github.com/elastic/beats/tree/master/libbeat/processors/actions)** package.  

These functions appear to be relatively generic therefore it may be beneficial to export them so that any developers can take advantage of these methods when building custom beats.

It would also be great to have some documentation regarding creating custom processors for community beats, including a few examples.

**Comment by ruflin** [comment]
I think it is ok to make these functions public. Could you open a PR for it?

+1 on adding more docs about how to create custom processors. You are probably one of the first one to do so, means you have probably to go through all the extra hoops like the one above.

Curious to hear more what you are buidling.
