### ISSUE TITLE
x-pack/metricbeat AWS tests failure

### ISSUE THREAD

**Issue by oakrizan** [elastic/beats#40242]
## Flaky Test

* **Test Name:**  x-pack/metricbeat/module/aws/sqs TestFetch
* **Link:** [Link to file/line number in github.](https://github.com/elastic/beats/blob/main/x-pack/metricbeat/module/aws/sqs/sqs_integration_test.go#L28)
* **Branch:** main
* **Artifact Link:** https://buildkite.com/elastic/beats-xpack-metricbeat/builds/5164#0190b59b-0ca1-4371-bc12-819a10ada908/655-1025
* **Notes:** The tests were [successful](https://buildkite.com/elastic/beats-xpack-metricbeat/builds/5078#0190a2f4-ee9d-4b99-8311-924166b10128 ) last week

### Stack Trace

```
=== Failed
--
  | === FAIL: x-pack/metricbeat/module/aws/sqs TestFetch (17.64s)
  | sqs_integration_test.go:28:
  | Error Trace:	/go/src/github.com/elastic/beats/x-pack/metricbeat/module/aws/sqs/sqs_integration_test.go:28
  | Error:      	Should NOT be empty, but was []
  | Test:       	TestFetch
```

To execute AWS tests on CI `aws` label should added to the PR

**Comment by dliappis** [comment]
FYI @elastic/obs-ds-hosted-services

**Comment by dliappis** [comment]
Another occurrence in `8.15`: https://buildkite.com/elastic/beats-aws-tests/builds/7#0190b668-7c28-4025-a25a-0f52da04aa32/584-968

**Comment by zmoog** [comment]
Hey @dliappis, we're checking the tests. @kaiyan-sheng thinks we may need to update the latency settings.

**Comment by kaiyan-sheng** [comment]
I created a SQS queue at 9:35 AM but the first cloudwatch metric didn't show up till 9:41 AM. With 5min latency configured, unless we wait for a long time before checking for events, we have a high chance not seeing any data point.

**Comment by zmoog** [comment]
We may need to fetch the metrics more than once for latency. Testing in progress.

**Comment by zmoog** [comment]
@dliappis, the PR https://github.com/elastic/beats/pull/40251 is in review.

We added a `PeriodicReportingFetchV2Error` function that tries to fetch the metrics multiple times until it gets values or the timeout expires. The (non-periodic) `ReportingFetchV2Error` only fetches the metric values once, resulting in much higher chances of not getting any metric value.

I tried running the tests five times with five successful executions. 

There are other aspects we want to investigate and improve, but I hope these changes will remove the flakiness.

**Comment by dliappis** [comment]
> @dliappis, the PR #40251 is in review.

Thank you @zmoog for the quick actions here! Looking forward to getting the PR merged/resolve the issue asap as pretty much all branches now, most of the time, are hitting this issue (example: https://buildkite.com/elastic/beats-pipeline-scheduler/builds/89#0190bdfe-8bed-442a-9f72-5b7074694c12, see also [here](https://elastic.slack.com/archives/C042HTEB27R/p1721175585206839)).

**Comment by zmoog** [comment]
I'm closing this since the issue seems to be resolved. Feel free to reopen it in case the problem shows up again.
