### ISSUE TITLE
Move some file detection logs to info loglevel to make troubleshooting easier

### ISSUE THREAD

**Issue by jori-be** [elastic/beats#40255]
Is it possible to switch the follow logs in filebeat from debug to info loglevel?
It would make troubleshooting a bit easier because debug loglevel is very verbose if you are harvesting multiple logs files.

File [file] has been renamed to..
```
{"log.level":"debug","@timestamp":"2024-04-22T18:05:08.204+0200","log.logger":"input.filestream","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/filestream.(*fileProspector).onFSEvent","file.name":"filestream/prospector.go","file.line":215},"message":"File /data/log/app/appparsed/TEST-LOG-01/app-TEST-LOG-01.log has been renamed to /data/log/app/appparsed/TEST-LOG-01/app-TEST-LOG-01.log_rotated","service.name":"filebeat","id":"app_log","prospector":"file_prospector","operation":"rename","source_name":"native::748582-64768","os_id":"748582-64768","new_path":"/data/log/app/appparsed/TEST-LOG-01/app-TEST-LOG-01.log_rotated","old_path":"/data/log/app/appparsed/TEST-LOG-01/app-TEST-LOG-01.log","ecs.version":"1.6.0"}
```

A new file...

```
{"log.level":"debug","@timestamp":"2024-04-22T18:05:08.213+0200","log.logger":"input.filestream","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/filestream.(*fileProspector).onFSEvent","file.name":"filestream/prospector.go","file.line":179},"message":"A new file /data/log/app/appparsed/TEST-LOG-03/app-TEST-LOG-03.log has been found","service.name":"filebeat","id":"app_log","prospector":"file_prospector","operation":"create","source_name":"native::33971680-64768","os_id":"33971680-64768","new_path":"/data/log/app/appparsed/TEST-LOG-03/app-TEST-LOG-03.log","ecs.version":"1.6.0"}
```

Thanks in advance!

**Comment by pierrehilbert** [comment]
Hello @jori-be 
Lately we tried to decrease the amount of unnecessary logs in info level to avoid too much noise.
I'm not against switching the log level for those logs but I would like to get @nimarezainia's opinion first.

**Comment by nimarezainia** [comment]
> Hello @jori-be Lately we tried to decrease the amount of unnecessary logs in info level to avoid too much noise. I'm not against switching the log level for those logs but I would like to get @nimarezainia's opinion first.

I agree @pierrehilbert, we can't really increase the verbosity of the info in this manner as for overwhelming majority of users this is the default out of the box log level.
