### ISSUE TITLE
OSS filebeat harvester_test.go should not depend on Elastic-licensed code

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#40293]
There a depguard lint rule failing because we have OSS test code depending on Elastic-licensed code from the x-pack/ directory. Due to licensing, dependencies are only allowed in the opposite direction. The code in question is test code so it doesn't taint any of our OSS release artifacts. Nonetheless, we should fix it (perhaps by moving the helper code from x-pack to oss).

> filebeat/input/filestream/internal/input-logfile/harvester_test.go:36:2: import 'github.com/elastic/beats/v7/x-pack/dockerlogbeat/pipelinemock' is not allowed from list 'apache-licensed-code': Apache 2.0 licensed code cannot depend on Elastic licensed code (x-pack/). (depguard)

Related

- https://github.com/elastic/beats/issues/38719
- https://github.com/elastic/beats/pull/40132#issuecomment-2234162445

**Comment by violetguos** [comment]
Hi, can I take this issue? thanks

**Comment by andrewkroh** [comment]
Yes, please do.
