### ISSUE TITLE
GeoIPCity instead of GeoIPCity-lite

### ISSUE THREAD

**Issue by chron0** [elastic/beats#403]
I've been trying to get packetbeat to work with MaxMind's GeoIPCity.dat database, but it seems, it only works with GeoIPCity-lite. Is there a trick to get it to work with GeoIPCity.dat for better resolution/precision?

**Comment by andrewkroh** [comment]
The library used to read the data files says it only supports the lite databases. https://github.com/nranchev/go-libGeoIP

Unless we find a different library or enhance that one, it won't be possible. 

However, you can send the data to Logstash and enrich it with the [GeoIP filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-geoip.html) which should work with the paid versions (not v2) of the database.

**Comment by urso** [comment]
I'm closing this, because Beats do not resolve geo IP themselves for a long time. All geo IP lookup is done in Ingest Node nowadays.
