### ISSUE TITLE
Add message size information into s3-sqs input metrics

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#40306]
It will be very beneficial to have the information about S3 object size and number of events included in each object when debugging AWS s3-sqs input performance. These metrics are missing from the existing input metrics right now. 

For input metrics, please see https://github.com/elastic/beats/pull/25711 for more details.

**Comment by Kavindu-Dodan** [comment]
Discussed with @kaiyan-sheng  on _what_ metrics to include. We decided to include a histogram to measure,

1. Processed individual S3 object size
2. Number of logs included in each object

These values should help to understand the distribution of processed data at beats allowing us to help users better.
