### ISSUE TITLE
Extend HTTP processing

### ISSUE THREAD

**Issue by urso** [elastic/beats#404]
HTTP is often used e.g. REST APIs using either JSON or XML (e.g. CouchDB, Elasticsearch, Docker). Also AVRO and others seem to be based on HTTP.

HTTP module should allow (based on some criteria like content-type, ports and/or other header fields) for processing the HTTP body.

**Comment by urso** [comment]
I've got some time thinking about implementation and documentation. So here my proposal.

First check Http configuration [documentation](https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-configuration.html#_http_configuration_options). The HTTP already has an option 'include_body_for'. This option will be basically replaced by this proposal.

With multiple services potentially using the same content-type it would be nice if we can distinguish the service types from within kibana. For this to work we want to filter at least on content-type and port number. Next we will need to add tags or additional fields to be added to the event for filtering indexed documents. With multiple similar body 'analysers', the first one matching shall be used. So one might add a generic JSON analyser in case at the end of the list to parse all json bodies if not handled by any service.

Example config:

    http:
      ports: [80, 8080, 8000, 9200, 5984, 2376]
    
      body:
        # json analyzers. will register application/json content-type by default
        - type: json
          ports: [9200]
          tags: ["elasticsearch"]
    
        - type: json
          ports: [5984]
          tags: ["couchdb"]
    
        - type: json
          ports: [2376]
          tags: ["docker"]
    
        # generic json if other json filters did not match
        - type: json

        # handle multipart/form-data (parse request triggered by HTML forms)
        - type: form
    
        # xml handlers
        - type: xml
    
        # registers binary/avro by default
        - type: avro
    
        # register application/octet-stream.
        # Count number of bytes + # If 'content-disposition:' header with filename
        # given, the filename will be added
        - type: stream


The default config file is:

    http:
      ...
    
      body:
        - type: json
        - type: xml

The event reported will contain a field 'body' with all meta data extracted from content-type plugin. Open question: how do we want to report multipart/mixed or multipart/alternative bodies (really required?)

**Comment by ruflin** [comment]
@urso I like it. I would call it body_type or something similar so we don't run into the type conflict again.

**Comment by Keylor42** [comment]
Would it also be possible to parse the url of the request ? For example, in Couchdb, I would like to have the name of the database and the document ID in fields in Kibana for monitoring purposes. Requests for couchdb are structured like that : GET  /{database}/{doc_id}.

**Comment by urso** [comment]
Good point. I didn't think about parsing URLs. But would be required for Elasticsearch too. Any proposals?

**Comment by Keylor42** [comment]
For me, the perfect thing would be to have a kind of "ParseRESTrequest" method, similar to the Parse and ParseUDP method, which would allow the user to have as parameters the url of the request, the response, headers, body etc. and do what he/she wants with it. Like splitting the url and filling specific fields of the protocol. I don't know if it's technically possible for Packetbeat right now but for me it would be the best solution.

**Comment by urso** [comment]
Just having a method is clear. I am also talking about configuration. Do you deal with additional path prefixes when parsing the URL? In general I'm not sure we need specialised plug-ins for parsing REST API URLs as these are quite simple. But then I wonder if this is already doable with logstash.

**Comment by Keylor42** [comment]
You mean you would not be interested by a plugin for couchdb ? That is ok for me, I can code it just for my company, but I would like to know if I should wait for your interface or not. I don't deal with additional path prefix for now, I'm testing couchdb on my localhost and I parse the url directyl from the root path, byt maybe there will be additional prefix on real databases in the future.

**Comment by urso** [comment]
@Keylor42 I mean, I'm still undecided if:
- we should introduce plugins for URL parsing
- have generic URL parsing functionality (no need for additional plugins, as parsing URLs is pretty easy?)
- no URL parsing support in packetbeat at all and rely on Logstash grok filters to do URL parsing. Should be already possible. It's Logstashs raison d'être to add additional value/processing to events.

**Comment by urso** [comment]
@Keylor42 If we were to have URL parsing support + JSON content-type support, what is it a  specialised CouchDB plugin (on top of HTTP) will have in additional features to set it apart?

I'm definitely seeing value in these features, but  we're more in a thinking/design phase yet. Don't expect an interface being available soon. Maybe it makes sense to have a CouchDB plugin (even if only temporary), but maybe not.

**Comment by michalpristas** [comment]
closing issue upon agreement with @urso
