### ISSUE TITLE
Install Elastic Agent and autoenroll onto Fleet Server?

### ISSUE THREAD

**Issue by riahc3** [elastic/beats#40474]
Hello

Im running this:

Start-Process -FilePath "msiexec.exe" -ArgumentList '/i', 'elastic-agent-8.13.4-windows-x86_64.msi', 'INSTALLARGS="--url=http://fleetserver.domain.local:8220 --enrollment-token=VnJKfUlwgUJHN2RBQ0Jfb3MwvzI6bWfHLXVNZ3rR50Jqal2Zfm9vw09WZw== --insecure --force"', '/quiet', '/norestart', '-L*V', 'elasticlog.txt' -Wait -NoNewWindow

But it does not enroll....The log doesnt say anything detailed.

Since it does not work, the agent isnt fully installed. 

How do I install this and get this to work properly?

Thanks

**Comment by ycombinator** [comment]
Hi @riahc3, please post this as a question in https://discuss.elastic.co/c/elastic-stack/elastic-agent/91.  We use GitHub issues for confirmed bugs and enhancement requests.  When you post your question, please include all logs and output as well.  Thanks!

**Comment by riahc3** [comment]
> Hi @riahc3, please post this as a question in https://discuss.elastic.co/c/elastic-stack/elastic-agent/91. We use GitHub issues for confirmed bugs and enhancement requests. When you post your question, please include all logs and output as well. Thanks!

The issue is that there are barely any answers on those forums.
