### ISSUE TITLE
Investigate the best way to decide when to read system logs from files or journald

### ISSUE THREAD

**Issue by belimawr** [elastic/beats#40526]
Debian 12 has stopped writing system logs to traditional log files and now only uses journald by default (see [release notes](https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.en.html#changes-to-system-logging)).

This makes the system module unable to ingest data because it expects to read direct from files.

We need to find the best way to detect the whether files or journald is used to store the system logs and configure the correct input (log/filestream or journald).

There is a similar issue in the integrations repository to handle the System Integration for Elastic-Agent: https://github.com/elastic/integrations/issues/10797

**Comment by belimawr** [comment]
Reopening as we ended up reverting it, so the feature is not available any more.

**Comment by cmacknz** [comment]
If we can't use conditions the way agent does, we could just leave it as a manual choice. I would prefer to avoid having agent and beats solve this problem in two different ways unless there is a strong reason for this.

**Comment by belimawr** [comment]
> If we can't use conditions the way agent does, we could just leave it as a manual choice. I would prefer to avoid having agent and beats solve this problem in two different ways unless there is a strong reason for this.

That's what I've been doing on my PR: https://github.com/elastic/beats/pull/41555
