### ISSUE TITLE
Add synthetics to the new Wolfi image of Heartbeat

### ISSUE THREAD

**Issue by rdner** [elastic/beats#40564]
**Describe the enhancement:**
At the time of adding the new Wolfi-based Docker image for Heartbeat, it didn't appear possible to install synthetics on Wolfi due to the [lack of support](https://playwright.dev/docs/intro#system-requirements) on the Playwright's end.

We need to install Playwright dependencies in order to make it work and it did not seem to be possible on Wolfi. Perhaps there is a workaround or manual way to do so.

https://github.com/elastic/beats/blob/813eaa8dc5bb7ed2fe94ba4a56e702e97faece06/dev-tools/packaging/templates/docker/Dockerfile.tmpl#L164

Additionally, the fonts we install for synthetics are not available in apk on Wolfi:

https://github.com/elastic/beats/blob/813eaa8dc5bb7ed2fe94ba4a56e702e97faece06/dev-tools/packaging/templates/docker/Dockerfile.tmpl#L166-L167

**Describe a specific use case for the enhancement or feature:**

Using Synthetics with Heartbeat.

Follow up to https://github.com/elastic/beats/pull/40524

**Comment by emilioalvap** [comment]
@rdner Please let us know if @elastic/obs-ds-hosted-services-synthrum can help on the migration.

**Comment by pierrehilbert** [comment]
Hey @emilioalvap,
FYI @rdner is in PTO.
We will indeed need your help here to solve the issue as this is not something we are familiar with.

**Comment by jlind23** [comment]
@emilioalvap @graphaelli were you able to make any progress on this? This would block Beats if not resolved in time.
cc @amitkanfer

**Comment by emilioalvap** [comment]
@pierrehilbert @jlind23 I'm working on a PR to install synthetics on wolfi based images.
@jlind23 if you don't mind me asking, in what sense does this block beats migration to wolfi? This restriction only affects heartbeat-wolfi images afaik.

**Comment by emilioalvap** [comment]
@jlind23 just to clarify, will you be replicating these changes on the elastic-agent-complete template or would you like me to create the PR for that?

**Comment by jlind23** [comment]
@emilioalvap it is ok for now, @rdner will take care of the elastic-agent-complete. Thanks for your help 🙏🏼
