### ISSUE TITLE
[metricbeat][Kubernetes] Pod tokens to access Kubelet API are not refreshed

### ISSUE THREAD

**Issue by constanca-m** [elastic/beats#40627]
Metricbeat pod has a token that can be found in:

https://github.com/elastic/beats/blob/cc561ff8b28e5c6bc73f746e9bf14045010c8855/deploy/kubernetes/metricbeat/metricbeat-configmap.yaml#L124

This token is initialized only one time at the start of each metricset. The metricsets using it are:

https://github.com/elastic/beats/blob/cc561ff8b28e5c6bc73f746e9bf14045010c8855/deploy/kubernetes/metricbeat/metricbeat-configmap.yaml#L115-L120

When fetching the metrics, each of these metricsets make a request to the kubelet API, like this:

https://github.com/elastic/beats/blob/cc561ff8b28e5c6bc73f746e9bf14045010c8855/metricbeat/module/kubernetes/container/container.go#L89

Inside this function, we then create a HTTP request and try to get the response like this:

https://github.com/elastic/beats/blob/cc561ff8b28e5c6bc73f746e9bf14045010c8855/metricbeat/module/kubernetes/kubernetes.go#L150-L153

If the token was refreshed and the one used in the beginning is no longer valid, the error will be `HTTP error 401 in : 401 Unauthorized`. It will always be like this until a user restarts once again metricbeat so the token is refreshed.

**WARNING**: Please investigate if there are other ways to identify this issue. I am testing this by adding a new volume for the token in the metricbeat pod, and the error seems to not be present in the logs. However, we are not receiving more metrics.

A possible worked is to check which error we got. If the error is`HTTP error 401 in : 401 Unauthorized`, we could always cause a refresh. A bit like this:

```go
	if statsCache.lastFetchTimestamp.IsZero() || now.Sub(statsCache.lastFetchTimestamp) > m.Config().Period {
		statsCache.sharedStats, statsCache.lastFetchErr = http.FetchContent()
		if statsCache.lastFetchErr == 401 ERROR {
                   // read file again
                   // http.SetHeader(AUTHORIZATION, new token)
                   // make new call
                   // if error 401 persist, then give up - cause is likely something else
                }
		statsCache.lastFetchTimestamp = now
	}
```

**Comment by gizas** [comment]
I like the idea and approach to have a config().Period. (ok the name to change)

As another idea, what also worths trying is to use [http.Client.Timeout](https://pkg.go.dev/net/http#Client) field and then check for [StatusRequestTimeout](https://pkg.go.dev/net/http#Client.Get). This way we will handle the token timeouts with a more `native` library way

Another scenario that should be included in the integrations tests of ours

**Comment by constanca-m** [comment]
I also would prefer to change the HTTP helper @gizas, but since it is being used by many modules, we would have to implement a solution that starts at the error we get once we make the HTTP request.

**Comment by jstrassb** [comment]
I came across this when working on a similar but slightly different case, which led to https://github.com/elastic/sdh-beats/issues/5439.

There was a knowledge base draft for this aspect of the Kubelet API and I combined it with my case for Kube apiserver and made it public:
Metricbeat stop collecting Kubernetes metrics due to 401 Unauthorized error
https://support.elastic.dev/knowledge/view/043ecc1d
https://support.elastic.co/knowledge/043ecc1d
