### ISSUE TITLE
configtest should fail if no paths are defined for a prospector

### ISSUE THREAD

**Issue by eherot** [elastic/beats#4072]
E.g.
```
$ sudo /usr/share/filebeat/bin/filebeat -c /etc/filebeat/filebeat.yml -path.home /usr/share/filebeat -path.config /etc/filebeat -path.data /var/lib/filebeat -path.logs /var/log/filebeat -configtest
Config OK

$ sudo /usr/share/filebeat/bin/filebeat -c /etc/filebeat/filebeat.yml -path.home /usr/share/filebeat -path.config /etc/filebeat -path.data /var/lib/filebeat -path.logs /var/log/filebeat
Exiting: Error in initing prospector: No paths were defined for prospector accessing 'filebeat.prospectors.0' (source:'/etc/filebeat/conf.d/prospector.yml')
```

It's probably obvious enough from the above output, but here's the prospector yaml:
```
filebeat:
  prospectors:
  - paths: []
    fields:
      app: myapp
    input_type: log
    document_type: my_type
```

**Comment by ruflin** [comment]
Configtest does currently only some very basic tests like validating the yaml file. The challenge is that there are quite a few dependencies which can only be detected when running the beat. 

As an example, not having any prospector is not allowed normally, but when having reloading activated it is.

We are working on improving the configtest option but it will not cover all the cases.
