### ISSUE TITLE
Remove functionbeat binaries

### ISSUE THREAD

**Issue by jlind23** [elastic/beats#40745]
Functionbeat has now been fully deprecated but binaries are still shipped as part of the standard release process, those should be removed.

cc @strawgate @nimarezainia 

- [ ] Remove functionbeat binaries starting from version 9.0
- [ ] Remove functionbeat source code starting from version 9.0

For the record a more detailed list of PRs and issues that are dependencies on other than the beats repo for this task can be found on the PR for this issue:
 - https://github.com/elastic/beats/pull/41506

**Comment by jlind23** [comment]
After chatting with @nimarezainia today we are wondering which one of the approach we should pick:
- Removing Functionbeat binary and deleting this download page - https://www.elastic.co/downloads/beats/functionbeat 
- Keeping Functionbeat binary but highlighting that this is EOL on the download page itself
- Switching Functionbeat download page and point to the serverless forwarder download page

@cmacknz @amitkanfer @strawgate any thoughts?

**Comment by jlind23** [comment]
> Maybe this, and then add a paragraph on the serverless forwarder page that talk about Functionbeat deprecation and a link to an archive?

What would be the benefit of mentioning Functionbeat in the Serverless forwarder page?

> Switching Functionbeat download page and point to the serverless forwarder download page

@nimarezainia do you know who could help us to that? I guess the team in charge of the release pages?

**Comment by nimarezainia** [comment]
@jlind23 i'll take care of it. I suppose we need to remove the DRA also?

**Comment by jlind23** [comment]
> I suppose we need to remove the DRA also?

So you mean that we don't want to push binaries anymore?

**Comment by cmacknz** [comment]
The least disruptive option is to remove the binaries completely in 9.0 and keep them around on 8.x.

If we can I would completely delete the functionbeat source code in the 9.0 branch, with it only existing in 8.x.

**Comment by jlind23** [comment]
Thanks @cmacknz, added the two related actions in the description.

**Comment by nimarezainia** [comment]
> Thanks [@cmacknz](https://github.com/cmacknz), added the two related actions in the description.

Just to clarify - target removal of the download page at 9.0 as well?

**Comment by jlind23** [comment]
> Just to clarify - target removal of the download page at 9.0 as well?

Yes.

**Comment by pierrehilbert** [comment]
After discussing with @AndersonQ, this issue is a Small in term of work but requires sync with other teams and to have things in movement so could take more than the sprint to have it through the finish line.

**Comment by AndersonQ** [comment]
As it's clear on the beats PR for this issue, removing function betas also affects Kibana. One of the affected features is the ability to track telemetry regarding functionbeat as Abdul Zahid pointed out [here](https://github.com/elastic/kibana/pull/199301/commits/d8bc37bec040a1020f87311e9f8ae338aa3baaf8#r1837885394). Those were not removed for now. I myself believe we can keep them, but ultimately it's a product decision. So @strawgate @nimarezainia as you two are in cc for this issue, I believe you might be able to help me here in deciding if we should keep or not the tracking of functionbeat telemetry in 9.0.

cc: @pierrehilbert @cmacknz

**Comment by nimarezainia** [comment]
> As it's clear on the beats PR for this issue, removing function betas also affects Kibana. One of the affected features is the ability to track telemetry regarding functionbeat as Abdul Zahid pointed out [here](https://github.com/elastic/kibana/pull/199301/commits/d8bc37bec040a1020f87311e9f8ae338aa3baaf8#r1837885394). Those were not removed for now. I myself believe we can keep them, but ultimately it's a product decision. So [@strawgate](https://github.com/strawgate) [@nimarezainia](https://github.com/nimarezainia) as you two are in cc for this issue, I believe you might be able to help me here in deciding if we should keep or not the tracking of functionbeat telemetry in 9.0.
> 
> cc: [@pierrehilbert](https://github.com/pierrehilbert) [@cmacknz](https://github.com/cmacknz)

keeping the tracking telemetry in there is fine IMO.

**Comment by jlind23** [comment]
@nimarezainia @AndersonQ as we decided to keep telemetry, are we good to close this issue as done?

**Comment by nimarezainia** [comment]
> [@nimarezainia](https://github.com/nimarezainia) [@AndersonQ](https://github.com/AndersonQ) as we decided to keep telemetry, are we good to close this issue as done?

sure. when the PR is merged.
