### ISSUE TITLE
non reported fields for metricbeat

### ISSUE THREAD

**Issue by Matt-Dee** [elastic/beats#4083]
HI, I just installed metricbeat and I see that there are about 326 fields available for the metricbeat indexes on the kibana dashboard.

I'm only seeing 71 fields that are being populated.

I'm particulary interested in(but they're not being populated):
system.process.cpu.system
system.process.cpu.user

I'm currently running centos 7.1.1503 and metricbeat version 5.4

My config file is as follows( I typed it in so there might be some mistypes):

metricbeat.modules:
- module: system
metricsets:
- cpu
- load
- core
- diskio
- filesystem
- fsstat
- memory
- network
- process
enabled: true
period: 10s
processes: ['.*']

cpu_ticks: false

output.elasticsearch:
hosts: ["foo", "bar]

**Comment by andrewkroh** [comment]
Cross posted: https://discuss.elastic.co/t/metricbeat-and-availables-metrics/83092
