### ISSUE TITLE
[GCP] Metricset metrics client allow overriding the endpoint

### ISSUE THREAD

**Issue by alexsapran** [elastic/beats#40848]
The GCP metricset metric as I was looking at https://github.com/elastic/beats/blob/38ba816ecc6c9ebde8db32ff1be10f10e5ff2df7/x-pack/metricbeat/module/gcp/metrics/metricset.go#L143

We are not able to override the api endpoint. It would be good to be able to do that if we want to test against a fake GCP API endpoint.

Looking at the source code of the client https://github.com/googleapis/google-cloud-go/blob/4265accaab624984d7ea60025e24198a0a0db6d3/monitoring/apiv3/metric_client.go#L55 it looks it gives us the ability to define the option `option.WithEndpoint(...)`

Preferably, it would be good to override with some env var.

This will be useful in the effort we are starting with doing performance work for metricbeat.

Not sure which team is more suited for this ask; I am just pinging both teams from the [codeowners](https://github.com/elastic/beats/blob/main/.github/CODEOWNERS#L198)
@elastic/obs-ds-hosted-services or @elastic/obs-infraobs-integrations

Sorry for the noise. If you feel you are in the wrong group or the file is not up-to-date.

/cc @cachedout @ablnk

**Comment by graphaelli** [comment]
@lalit-satapathy can you help with this one?

**Comment by lalit-satapathy** [comment]
> [@lalit-satapathy](https://github.com/lalit-satapathy) can you help with this one?

Hi @Linu-Elias, Can you please take a look at this?
