### ISSUE TITLE
Beats do not log to stderr when running in a container or systemd environment

### ISSUE THREAD

**Issue by belimawr** [elastic/beats#41118]
For confirmed bugs, please report:
- Version: 8.15.0 and later versions
- Operating System: All
- Discuss Forum URL: https://discuss.elastic.co/t/no-output-to-stdout-stderr-from-docker-image-after-upgrading-to-v8-15-x/
- Steps to Reproduce: Run any beat (Filebeat as an exmaple) in a container or with `-environment container`

Reproducing with Docker:
```
docker run --rm docker.elastic.co/beats/filebeat:8.14.3
```
Will log to stderr

```
docker run --rm docker.elastic.co/beats/filebeat:8.15.2
```
Will produce no logs on stderr.

When using `-environment systemd` this issue can also be observed.

## Workaround
Pass the `-e` flag when running the Beat or add `logging.to_stderr: true` to your configuration file.

**Comment by mauri870** [comment]
@belimawr I'm confused, isn't this behaving as expected according to https://github.com/elastic/beats/pull/38767?

> 6. Look at the logs (container) and assert no event data is going to stderr: 

> If you want to see the event logs going to stderr, uncomment the following lines from the configuration:
>
>          # "-E",
>          # "logging.event_data.to_stderr=true"

**Comment by mauri870** [comment]
This seems to be a bug introduced in https://github.com/elastic/elastic-agent-libs/pull/208, the default location for container logs was silently changed to files instead of stderr. It should be fixed by https://github.com/elastic/elastic-agent-libs/pull/236.

**Comment by mauri870** [comment]
Reopening as we need to track the PRs updating the lib in Beats as well as backport PRs.

**Comment by mauri870** [comment]
FYI I updated this ticket to mention that `-environment systemd` is also affected.
