### ISSUE TITLE
Non-beats index names and prebuilt dashboards

### ISSUE THREAD

**Issue by markwalkom** [elastic/beats#4113]
I was playing around with the stack today and I pushed metricbeat data to LS to give me stats in Monitoring, which works no problems.

However because I am not sending directly to ES I am not using the `metricbeat-` index pattern, but the LS default of `logstash-`. The problem there is that metricbeat has a bunch of really awesome prebuilt dashboards that I can't use because they are tied to the `metricbeat-*` index pattern.

It crossed my mind that we could do something with the `import_dashboards` script, where by passing a flag like `-index logstash` we do a regex on the fly to change the index pattern and allow them to be altered accordingly.

Not sure if this is sane, of if we should perhaps provide an out-of-the-box config for Logstash so that we can push into `metricbeat` (or whatever beat) index patterns. But I guess this is a good place to start that conversation 😄

**Comment by derickson** [comment]
Is there a workaround for this like just setting the index output in the logstash config? @markwalkom 
Asking for a friend

**Comment by dedemorton** [comment]
In the documentation, we do tell users to set the index in the logstash output config:

https://www.elastic.co/guide/en/beats/libbeat/5.3/logstash-installation.html#logstash-setup

See step 2:

```
input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => "localhost:9200"
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}" 
    document_type => "%{[@metadata][type]}" 
  }
}
```

**Comment by markwalkom** [comment]
Thanks @dedemorton I didn't see that.

@derickson per above, yeah ;) But I was still thinking there might be a better way to make this a smoother process. Perhaps I am a little early on this given some of the centralised LS config stuff that is coming.

**Comment by ruflin** [comment]
There is also in the import_dashboard script the `-i` option which can be used to define a different index pattern: https://www.elastic.co/guide/en/beats/libbeat/current/import-dashboards.html

**Comment by markwalkom** [comment]
Wow, ok so I suck at reading the docs/help closely :(
