### ISSUE TITLE
where is flows_event functionality?

### ISSUE THREAD

**Issue by purplesrl** [elastic/beats#4116]
I am unable to find this anywhere in the source code, it is documented on the website, any idea where it is?

- key: flows_event
  title: "Flow Event"
  description: >
    These fields contain data about the flow itself.

https://www.elastic.co/guide/en/beats/packetbeat/current/exported-fields-flows_event.html

**Comment by ruflin** [comment]
I think that is what you are looking for: https://www.elastic.co/guide/en/beats/packetbeat/5.3/configuration-flows.html For questions in the future please use discuss and not Github: https://discuss.elastic.co/c/beats/packetbeat

**Comment by purplesrl** [comment]
Actually, I read the initial message to not post here, but I posted here because I am unable to find those fields in the source of packetbeat.

I solved my problem in another way though, thanks
