### ISSUE TITLE
Filebeat: Live Reload incorrectly stops prospectors

### ISSUE THREAD

**Issue by grantwu** [elastic/beats#4133]
Bug around stopping prospectors confirmed here: https://discuss.elastic.co/t/error-when-reloading-prospectors-for-filebeat/83082

- Version: 5.3
- Operating System: CentOS6.9
- Steps to Reproduce: 
1.) Start a filebeat with a prospector config in the live-reload dir. 
2.) Add another prospector in addition to the existing one in the live-reload dir (does not matter if its in the same file or not)
3.) The first prospector will stop running once the reload occurs.

**Comment by ruflin** [comment]
@grantwu Thanks for the report. I think I managed to create some tests for it and fix it in https://github.com/elastic/beats/issues/4133 Will ping you when its merged to master.

**Comment by SlavaValAl** [comment]
where can I find filebeat package including this fix?

**Comment by tsg** [comment]
@SlavaValAl This is included in the 5.4.1 release: https://www.elastic.co/downloads/beats/filebeat

**Comment by SlavaValAl** [comment]
Hi @tsg! Thank you for fast response!
