### ISSUE TITLE
Remove docker mention in system module docs

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#4143]
In the [system module](https://github.com/elastic/beats/edit/5.3/metricbeat/docs/modules/system.asciidoc) there is a misplaced paragraph. I think it should be completely removed.

> It is strongly recommended to not run docker metricsets with a period smaller then 3 seconds. The request to the docker API already takes up to 2s seconds. Otherwise all the requests would timeout and no data is reported.

**Comment by dedemorton** [comment]
Closed by #4147
