### ISSUE TITLE
[Filebeat] CEL / broken mito version

### ISSUE THREAD

**Issue by pudovd** [elastic/beats#41486]
I use an Agent CR with ECK to get logs from the Loki via CEL integration.

It works well on the agent versions `8.13.4` and `8.14.3`
But it fails with version `8.15.3`.

I've found out that the reason is the new version of mito.  
There is compatible matrix the mito versions and my code (see attachements):

| beats version | mito version | ok? |
| ------------------ | ---------------- | ----- |
| 8.13.0 | 1.9.0 | true |
| 8.14.0 | 1.10.0 | true |
| 8.15.0 | 1.13.1 | false |
| - | 1.14.0 | false |
| - | 1.15.0 | true |

The error is:
```shell
$ go install github.com/elastic/mito/cmd/mito@v1.13.1
$ mito -data loki-gitlab-audit.state.json loki-gitlab-audit.cel 
failed program instantiation: failed compilation: ERROR: <input>:77:29: type 'list(map(string, dyn))' does not support field selection
 |                 val.map(v, v.timestamp != state.cursor.inputs.start_ts ? v : {}).drop_empty().as(filtered,
 | ............................^
ERROR: <input>:77:72: found no matching overload for '_?_:_' applied to '(bool, list(map(string, dyn)), map(dyn, dyn))'
 |                 val.map(v, v.timestamp != state.cursor.inputs.start_ts ? v : {}).drop_empty().as(filtered,
 | .......................................................................^
```
[loki-gitlab-audit.cel.txt](https://github.com/user-attachments/files/17575703/loki-gitlab-audit.cel.txt)
[loki-gitlab-audit.state.json](https://github.com/user-attachments/files/17575704/loki-gitlab-audit.state.json)

**Comment by efd6** [comment]
This is an issue with the type checker that was tickled in the change to the new runtime. It can be worked around by converting the `v` value to a `dyn` type.
```
                val.map(v, dyn(v).timestamp != state.cursor.inputs.start_ts ? dyn(v) : {}).drop_empty().as(filtered,
```
This hides the concrete type from the type checker and so when the program hits it, it gets the dynamic type, which is correct, and continues.

This workaround will continue to work after the unbroken version is in place. Apologies for the trouble.

The relevant commits (in mito) are:
(the breakage)
```
commit 9cf104614fd14a95fe3b49eebcafddd200d226ef
Author: Dan Kortschak <dan.kortschak@elastic.co>
Date:   Tue Apr 9 10:44:17 2024 +0930

    lib: update function definitions to new api
    
    This also fixes a compile-time type checking issue.
```
(the fix)
```
commit f538a8dae4cacbfb3f125dd09bc038ce2ae43a51
Author: Dan Kortschak <dan.kortschak@elastic.co>
Date:   Fri Jul 19 06:12:04 2024 +0930

    lib: relax type hints on flatten function
    
    The documented type signature of the flatten function is <list<dyn>> ->
    <list<dyn>>, but the implementation was <list<typeV>> -> <list<typeV>>.
    This has an impact on uses of flatten where the input is a nested set of
    lists, the exact intended use-case. In this situation, the type checker
    is told that the returned value is a list of lists..., resulting in
    rejection of valid programs. There is a work-around that can be used,
    but instead, just make the implementation match the documentation and
    intention.
```

**Comment by efd6** [comment]
@pudovd I'm going to close this since there is a fix merged and there is a work-around available. Please re-open if you feel that more needs to be addressed.
