### ISSUE TITLE
Wrong "make collect" statement documented instead of "make update" when documentation should be regenerated

### ISSUE THREAD

**Issue by christiangalsterer** [elastic/beats#4154]
https://www.elastic.co/guide/en/beats/metricbeat/current/creating-metricbeat-module.html
documents that the user should run `make collect` when some of the documentation input fields are changed and the documentation should be regenerated. The correct command to run is `make update`.

**Comment by christiangalsterer** [comment]
PR #4155 available

**Comment by andrewkroh** [comment]
Fixed by #4155.
