### ISSUE TITLE
Kafka output retrying infinitely on message that cannot be produced

### ISSUE THREAD

**Issue by weichuliu** [elastic/beats#4166]
- Version:
`filebeat version 5.3.0 (amd64), libbeat 5.3.0`
- Operating System:
`CentOS 6`
- Steps to Reproduce:

Start filebeat with the following configure:

```
output:
  kafka:
    hosts: ["kafka1:9092","kafka2:9092","kafka3:9092"]
    bulk_max_size: 10
    topic: '%{[non_existed_field]}'
    version: '0.10'

filebeat:
  prospectors:
  - input_type: log
    document_type: log
    paths:
    - /tmp/foo.log
    fields_under_root: true
```

If the dynamically generated topic doesn't exist, the filebeat will still try (and keep trying forever) to produce the message.

It will result like:

```
2017/05/02 03:48:13.088910 metrics.go:39: INFO Non-zero metrics in the last 30s: libbeat.kafka.call_count.PublishEvents=805363 libbeat.kafka.published_but_not_acked_events=805364
2017/05/02 03:48:43.088839 metrics.go:39: INFO Non-zero metrics in the last 30s: libbeat.kafka.call_count.PublishEvents=835167 libbeat.kafka.published_but_not_acked_events=835166
2017/05/02 03:49:13.089692 metrics.go:39: INFO Non-zero metrics in the last 30s: libbeat.kafka.call_count.PublishEvents=819975 libbeat.kafka.published_but_not_acked_events=819975
```

Possible solution:
1. Before producing, there should be a check whether a topic(or message_key) can be properly realized or not, to prevent such message being produced.
2. Filebeat should not by default retry unlimitedly, and should apply a waiting before every retry. (instead of retrying 800k times in a second)
3. After a certain failures, Filebeat should throw an error and drop the message.

Also, `libbeat.kafka.published_but_not_acked_events` is kind of misleading. It is not message not being acked, but message cannot be sent due to lacking the topic.

**Comment by ruflin** [comment]
Thanks for the report. Currently I would suggest we should probably follow suggestion 2 and introduce a backoff. It could be that on startup a topic is not there but later added I assume. 

Did you get any errors in the log? If not, we should improve the logging here.

**Comment by ruflin** [comment]
@urso Would be nice to get your thoughts on this one.

**Comment by weichuliu** [comment]
> Did you get any errors in the log

With the `-d "*"` I can only see a not directly related "circuit breaker is open" error.

> It could be that on startup a topic is not there but later added I assume.

By "is not therer", do you mean that there was no topic in Kafka so the output could be rejected?

However the subject of this issue is:
If dynamic topic(or message_key) is set in configuration, it is possible that the fields that are needed to format real topic name are not existed in either message or configuration. If I understand correctly, the topic realization happens only on *beat side so it is not related to Kafka's status.

**Comment by GiedriusS** [comment]
Still reproducible on Filebeat 7.8.0. Filled this related issue here: https://github.com/Shopify/sarama/issues/1755

**Comment by dnck** [comment]
This is happens... many years later
