### ISSUE TITLE
Support PUT for `check.request.method` in heartbeat http check

### ISSUE THREAD

**Issue by shahzad31** [elastic/beats#41811]
**Describe the enhancement:**

We realized we don't support PUT in `check.request.method` for http check, to fix the issue https://github.com/elastic/kibana/issues/197356 

instead of removing it from UI, we can add support for it in the request client, i don't see a reason why we can't.

**Comment by strawgate** [comment]
For reference, here's the PR from the last time we added an HTTP method (OPTIONS) to the check 
https://github.com/elastic/beats/pull/32987
