### ISSUE TITLE
Filebeat - Error in load states when enable the recursive glob

### ISSUE THREAD

**Issue by Kirax00** [elastic/beats#4182]
Please help to check the problem.
Version: master
Operating System: SUSE11
Steps to Reproduce: 
1. enable the recursive glob.
2. use ** in the path as /home/cmp/**/*.log
3. start the main_test, and it will collect the log
4. restart the filebeat, when it load the exist states, it will drop the actually marched source.
<pre><code>		match, err = filepath.Match(glob, filePath)
		if err != nil {
			logp.Debug("prospector", "Error matching glob: %s", err)
			continue
		}</code></pre>
The glob is /home/cmp/**/*.log, if the filePath is /home/cmp/a/b/c.log, the match will be *false*. Then the source will be dropped, which is an unexpected behavior.
Then the filebeat will collect the log from beginning, which is duplicately.

**Comment by ruflin** [comment]
@Kirax00 Thanks for the report. This is definitively a bug. On startup the prospector compares the pattern to the prospector config and in the comparison part we use the old matching as you pointed out above. 

@7AC Can you look into this?
