### ISSUE TITLE
Document file permissions for Config Reloading

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#4189]
The config reload documentation should mention file permissions and link to the libbeat documentation on _Config File Ownership and Permissions_. 

https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-configuration-reloading.html
https://www.elastic.co/guide/en/beats/filebeat/5.3/filebeat-configuration-reloading.html
https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html

Discuss: https://discuss.elastic.co/t/filebeat-5-3-1-config-dir-files-needs-644-permissions/84108

**Comment by dedemorton** [comment]
Closed by #5513
