### ISSUE TITLE
Make default config option platform independent.

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#419]
Currently we have in libbeat platform specific code based on where to look for the log file: https://github.com/elastic/libbeat/blob/master/cfgfile/cfgfile.go#L32

I suggest that we set the same directory as the binary to the default location and configure platform specific directories with the -c flag in the startup service scripts.

This will make it possible to download a binary with a config and start it also without the -c flag by default. This is similar to elasticsearch which checks the file in the config directory.

For reference see also discussion here: https://github.com/elastic/libbeat/pull/341#issuecomment-160987964

**Comment by monicasarbu** [comment]
I think it's a good idea to solve the problem this way, by looking in the same directory (in the etc directory?) by default and set `-c` option in the startup service scripts.  You can then delete the check from the cfgfile.go.

**Comment by monicasarbu** [comment]
Kibana & Elasticsearch keep the configuration files under `config`. We can also rename the `etc` directory to `config` to be similar.

**Comment by ruflin** [comment]
@monicasarbu I like the idea of renaming it to `config` especially as it is consistent elasticsearch. Renaming the etc. directory will bring naming conflicts but is definitively doable. The less nice part is that currently our download has 3 files, afterwards it would be 1 binary + folder with 2 files (config and template)? Still +1 on this change.

**Comment by andrewkroh** [comment]
The default config file location is now platform independent. It looks in the directory where the beat binary lives for a `<beatname>.yml`. No changes were made to add a `config`.
