### ISSUE TITLE
Document how to run Beats in a container 

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#4192]
We currently document how to [run Metricbeat in a container](https://www.elastic.co/guide/en/beats/metricbeat/current/running-in-container.html), but we don't provide this info for other Beats. We need to document this info for all Beats and provide specifics. For example:

Packetbeat - how to monitor the host's network traffic, what capabilities to add to the container so that it can run as non-privileged (cap_net_raw cap_net_admin)
Filebeat - how to monitor the host's logs, how to monitor docker logs

There will be some shared content, so we probably want to use a shared file in libbeat. The content that's unique to a specific Beat can be conditionally code.

**Comment by exekias** [comment]
@jarpy opened this PR https://github.com/elastic/beats/pull/4312

**Comment by dedemorton** [comment]
Fixed in #4312
