### ISSUE TITLE
Load / cores metric 

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#420]
Duplicated from: https://github.com/elastic/topbeat/issues/128

Knowing the load of a machine, or even the cpu time spent (percentage) is not very useful if you don't know the number of cores. i.e. a load of 3.1 is still healthy if you have a 4-core machine, but very unhealthy if you have a 2-core machine.
Would it be possible to add another metric to the system messages indicating the value of ( load / cores ) ?

**Comment by pietervogelaar** [comment]
What is the status of this issue? I really want this, because a system load that is not divided by cores is not very useful to show on a Kibana dashboard for Linux systems.

**Comment by monicasarbu** [comment]
@pietervogelaar This is implemented in https://github.com/elastic/beats/pull/2101 it will be available in the next release, 5.0.0-alpha5, that is coming out this week.

**Comment by monicasarbu** [comment]
Closing this issue as it's implemented in #2101.
