### ISSUE TITLE
Use MemAvailable from /proc/meminfo in the Linux 3.14 kernel

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#4202]
A great new metric has been introduced in “/proc/meminfo” in the Linux 3.14 kernel — MemAvailable:
```
An estimate of how much memory is available for starting new applications, without 
swapping. 
Calculated from MemFree, SReclaimable, the size of the file LRU lists, and the 
low watermarks in each zone.

The estimate takes into account that the system needs some page cache to function well, 
and that not all reclaimable slab will be reclaimable, due to items being in use. 
The impact of those factors will vary from system to system.
```
We need to adjust the gosigar library to use MemAvailable when it's available in "/proc/meminfo".

**Comment by cytim** [comment]
I just wanted to create the same issue and found this. 👍 

Related discussion on the forum:

- [Metricbeat system.memory.actual.free - is it accurate?](https://discuss.elastic.co/t/metricbeat-system-memory-actual-free-is-it-accurate/80650)
- [Incorrect “system.memory.actual.free” metrics](https://discuss.elastic.co/t/incorrect-system-memory-actual-free-metrics/83783)

**Comment by tony2k84** [comment]
Is this fixed and which release?
