### ISSUE TITLE
Export only percentage metrics of the cpu usage fields

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#421]
Duplicates https://github.com/elastic/topbeat/issues/146

Currently we export the following fields:
# cpu.idle 42,093,003
# cpu.iowait 0
# cpu.irq 0
# cpu.nice 0
# cpu.softirq 0
# cpu.steal 0
# cpu.system 3,484,300
# cpu.system_p 22%
# cpu.user 5,094,559
# cpu.user_p 74%

For the user these huge numbers don't mean much, so I suggest to export by default the following:

cpu.user_p
cpu.system_p
cpu.idle_p
cpu.iowait_p

This change can be done in the next major release as it removes fields.
And add another option in Topbeat to export all the other cpu usage related metrics.

**Comment by ndimer** [comment]
Anyone to implement this feature?

**Comment by kvch** [comment]
This issue has already been addressed. Please reopen if it's still valid.
