### ISSUE TITLE
*-god should be included in the TGZ release

### ISSUE THREAD

**Issue by trixpan** [elastic/beats#4219]
Filebeat's deb and rpm package include the filebeat-god binary, however this is nowhere to be found in the tgz. 

It would be great if the wrapper was added to the tgz so to easily allow users of non RPM or DEB based distros to make use of filebeat without having to compile it (and the god wrapper) from scratch.

**Comment by petercelentano** [comment]
when might this be a possibility? +1

**Comment by keebl** [comment]
I'd like that as well. But since it was requested 2 years ago im guessing it wont come anytime soon:) 
Atm i just take the -god and init script from the rpm package and use those.
