### ISSUE TITLE
Disk IO stats

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#422]
Requested by https://github.com/elastic/topbeat/issues/147

Would be great if topbeat also reported disk utilization, the percentage of time the device is used, not the space used on it. On linux it's the %util column of iostat -d -x. nmon (then d) also reports this nicely. The bandwidth read/written could also be useful, also reported by the same command.

<pre>
iostat -d -x, the %util column:
</pre>
![687474703a2f2f692e696d6775722e636f6d2f5966437a784d592e706e67](https://cloud.githubusercontent.com/assets/11757159/11534796/e8a68d34-9910-11e5-81e6-136755cfd62a.png)

<pre>
nmon - d, the Busy column:
</pre>

![687474703a2f2f692e696d6775722e636f6d2f35514d4b6132352e706e67](https://cloud.githubusercontent.com/assets/11757159/11534828/1a8d40a4-9911-11e5-890d-4d43291d799e.png)

Disk utilization is the only metric I really miss in topbeat for a complete overview of our servers health.

**Comment by allenmchan** [comment]
+1. 
With disk I/O metrics removed from Marvel 2.x, elastic employees has been pointing me to topbeat to fulfill this requirement. Please add disk IO metrics as I/O is a major bottleneck in elasticsearch and should be monitored closely

**Comment by joe-armstrong** [comment]
+1

**Comment by marv2097** [comment]
+1

**Comment by Qtax** [comment]
+1

**Comment by sempervictus** [comment]
+1

**Comment by oazabir** [comment]
+1

**Comment by sarkis** [comment]
+1

**Comment by danievanzyl** [comment]
+1

**Comment by jforjohn** [comment]
+1

**Comment by Beast12** [comment]
+1. Would be excellent!!

**Comment by bwgriffith** [comment]
+1

**Comment by ranrub** [comment]
+1

**Comment by easyrasta** [comment]
+1

**Comment by goobersmooch** [comment]
+1

**Comment by dimatha** [comment]
+1

**Comment by naeemhaq** [comment]
+1

**Comment by aranya-danno** [comment]
+1

**Comment by ees** [comment]
+1

**Comment by Eilyre** [comment]
+1

**Comment by ruflin** [comment]
Disk IO was now added to metricbeat: https://github.com/elastic/beats/pull/1620

**Comment by monicasarbu** [comment]
Closing it, as the PR is already merged.
