### ISSUE TITLE
Add cpu.idle_p and cpu.iowait_p (for system stats) 

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#423]
Duplicated from: https://github.com/elastic/topbeat/issues/145

For system stats it would be nice to have cpu.idle_p and cpu.iowait_p (as in the top header) so that you could easily see the total system usage (1-idle_p), and have clearer stats of IO bottlenecks.

At the moment I'm using an inline script that does system_p + user_p, but it would be nicer to use idle_p if it available.

The cpu.idle and cpu.iowait just contain huge numbers that always keep growing (as do cpu.system, cpu.user, etc), and I'm not sure what to do with those or how to use them in any meaningful way. Shouldn't those be deltas? Is this by design? (Couldn't find any mention of what these numbers are or what they should be in the docs.)

**Comment by hkbakke** [comment]
This should also include cpu.steal_p, and why not irq and softirq too but these are not as important. cpu.steal_p is perhaps the most critical cpu parameter to monitor in addition to iowait_p in virtualized environments, none of which are currently available.

**Comment by McStork** [comment]
Maybe it was implemented since this ticket was open? Idk.

Anyway, if I recall it correctly, units of those huge numbers are in number of ticks (also called jiffies).
To get the percentages, you should do:
percentage_idle = delta_idle / delta_ticks
percentage_iowait = delta_iowait / delta_ticks

Hope that helps

**Comment by monicasarbu** [comment]
It was not yet implemented. I think it makes more sense to export only the percentages (by default) as they are more human readable, so we can export cpu.steal_p as well. Thank you @hkbakke for your feedback.

**Comment by yaronp68** [comment]
Closing this one and replacing by https://github.com/elastic/beats/issues/8694
