### ISSUE TITLE
Reduce the exported fields for memory stats

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#4230]
In Metricbeat, the `memory` metricset of the `system` module  exports the following fields:
- system.memory.total
- system.memory.used.bytes
- system.memory.used.pct
- system.memory.free
- system.memory.actual.used.bytes
- system.memory.actual.used.pct
- system.memory.actual.free

Starting with Kibana 5.4 (that includes Time Series Visual Builder), you are able to do calculations using the Painless script based on the exported fields, so you don't need to store everything in Elasticsearch, and only the most used fields. I propose to delete `system.memory.actual.used` as it can be calculated as `system.memory.total` - `system.memory.actual.free`.

This change affects our dashboards.

cc-ed @simianhacker

**Comment by ruflin** [comment]
+1 on this change. Probably best do it for 6.0 as it is a breaking change.

**Comment by monicasarbu** [comment]
Before removing `system.memory.actual.used`, we need to export `cached` and/or `buffers` as they are  used in the dashboards.

**Comment by ruflin** [comment]
There has been an initial approach to fix this in https://github.com/elastic/beats/pull/4280 but it didn't make it into 6.0 so we can't remove the fields at the moment. We should discuss again on how we move forward here.

**Comment by ruflin** [comment]
As this is quite an old issue and hasn't been an issue recently, going to close this one.
