### ISSUE TITLE
Metricbeats 5.4.0 import_dashboards Error importing URL/file: Failed to unzip the archive

### ISSUE THREAD

**Issue by naeem-ahmed** [elastic/beats#4244]
Hi. Getting this error when trying to import dashboards on MacBook Darwin Kernel Version 16.5.0

Create temporary directory /var/folders/6b/nmt5qwls3h98jzk3629gbt540000gn/T/tmp755021367
Downloading https://artifacts.elastic.co/downloads/beats/beats-dashboards/beats-dashboards-5.4.0.zip
Unzip archive /var/folders/6b/nmt5qwls3h98jzk3629gbt540000gn/T/tmp755021367
Error importing URL/file: Failed to unzip the archive: /var/folders/6b/nmt5qwls3h98jzk3629gbt540000gn/T/tmp755021367/beats-dashboards-5.4.0.zip
Exiting

Thanks

**Comment by tsg** [comment]
@naeem-ahmed Thanks for the report, this is indeed a bug. You can work around it by setting `ulimit -n 2048` before running the import_dashboard program.

**Comment by naeem-ahmed** [comment]
That works, thanks.
