### ISSUE TITLE
ERR Error decoding JSON: invalid character 'x' in string escape code

### ISSUE THREAD

**Issue by minminmsn** [elastic/beats#4256]
hello 
filebeat-5.2.2-1.x86_64

1,nginx logs   json format
for example
{ "@timestamp": "2017-05-09T15:20:04+08:00", "clientRealIp": "46.161.9.48", "size": 5568,  "url": "/qiche/\xE5\xAE\xBF\xE5\xB7\x9E\xE6\x80\xA7\xE8\x8D\xAF\xE5\x93\x81\xE6\x89\xB9\xE5\x8F\x91\xE7\xBD\x91\xE3\x80\x90\xE5\x85\xA8\xE5\xA4\xA9\xE6\x9C\x8D\xE5\x8A\xA1\xE7\xA7\x8B\xE7\xA7\x8B=25317oo285\xE3\x80\x91\xE4\xB9\x96\xE4\xB9\x96\xE8\x8D\xAF\xE6\x9C\x89\xE4\xBB\x80\xE4\xB9\x88\xE7\x94\xA8/", "referrer": "-", "agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:26.1) Gecko/20100101 Firefox/26.0", "status": "200"} 

2,filebeat log
2017-05-09T15:21:39+08:00 ERR Error decoding JSON: invalid character 'x' in string escape code
2017-05-09T15:21:40+08:00 ERR Error decoding JSON: invalid character 'x' in string escape code
2017-05-09T15:21:40+08:00 ERR Error decoding JSON: invalid character 'x' in string escape code
2017-05-09T15:21:40+08:00 ERR Error decoding JSON: invalid character 'x' in string escape code

who can tell me waht i can do ?
tks!

**Comment by minminmsn** [comment]
use  $request_uri  inside  $uri，ok.

**Comment by ruflin** [comment]
Please use discuss for questions: https://discuss.elastic.co/c/beats/filebeat

Open a topic there and share the following in addition to the above:

* filebeat config
* A few example log lines (is the above the json event with the strange url?)

Happy to help there.
