### ISSUE TITLE
Move cpu_ticks config under namespace

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#4263]
`cpu_ticks` is a top level config option in the system module in metricbeat. After `cpu_ticks` was introduced we started to move all config options under the namespace of the metricset to not have conflicts and make it obvious to which metricset a config option belongs. `cpu_ticks` should be move under all metricsets which support the feature.

As this is a breaking change it should be made during the 6.0.0-alpha releases.

**Comment by tsg** [comment]
I think this is no longer relevant. @ruflin, maybe reopen if you think we still need this issue.
