### ISSUE TITLE
Make permisson on logfile configureable

### ISSUE THREAD

**Issue by florian-asche** [elastic/beats#4295]
Please see this change: https://github.com/elastic/beats/pull/3387

Can we make the permissions configureable?
(We use other admin user than user the software run under)...

**Comment by batrako** [comment]
in our case, beat  user is only for run filebeat (with no login). We use other shell users to view filebeat logs and enter to system. We need specify another default mask  to filebeat log files (not valid 600 for us).

**Comment by atoulme** [comment]
Possibly as a new setting under logging.files? https://www.elastic.co/guide/en/beats/filebeat/current/configuration-logging.html

**Comment by florian-asche** [comment]
yes

**Comment by atoulme** [comment]
Tye team merged my changes just now. @florian-asche if you agree we can close this issue.

**Comment by florian-asche** [comment]
mhmh. im missing a parameter for user/group. that whould be more secure instead of readable to all users.

**Comment by atoulme** [comment]
I did not understand what you meant, sorry. Would you please clarify?

**Comment by atoulme** [comment]
I think I understand. If you'd like to set a different group, you should probably use the setgid flag on the directory where the logs will be created.
