### ISSUE TITLE
can't start filebeat on windows 2008 r2

### ISSUE THREAD

**Issue by depend** [elastic/beats#431]
```bash
Start-Service : Service 'filebeat (filebeat)' cannot be started due to the following error: Cannot start service filebe
at on computer '.'.
At line:1 char:14
+ start-Service <<<<  filebeat
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand
```

I don't see any error in event viewer or the logging location defined in filebeat.yml. Is there a way to troubleshoot this?

**Comment by andrewkroh** [comment]
Here are few things to check.

- Are you running the command from an elevated prompt (run as administrator)?
- Is your config valid? Test it with `.\filebeat.exe -c filebeat.yaml -configtest`
- Can you start Filebeat on its own (not through a service)? `.\filebeat.exe -c filebeat.yml -e -v`
- Does the path to Filebeat contains spaces? See elastic/beats-packer#32

**Comment by depend** [comment]
Yeah it's caused by space in path. Thanks!

**Comment by omerlh** [comment]
I have the same issue. I've already checked the configuration file, and even started filebeat with the same parameters as the service does. I've tried it also in a path that does not have spaces and the service still not starting. What else can be the problem?
Thanks

**Comment by ruflin** [comment]
@omerlh Could you please open a new topic on discuss with your problem and share all the details like version, OS, config, log outputs? https://discuss.elastic.co/c/beats/filebeat

**Comment by omerlh** [comment]
Sure, thanks
