### ISSUE TITLE
Corrections for "Features and configuration" section of Jolokia metricset documentation

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#4319]
https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-jolokia-jmx.html#_features_and_configuration

Few things to address here:

* We attempted to use code formatting but it's not working and showing the literally markdown syntax.

```
``` - module: jolokia metricsets: ["jmx"] hosts: ["localhost:8778"] namespace: "metrics" jmx.mappings: - mbean: java.lang:type=Runtime attributes: - attr: Uptime field: uptime ```
```

* "it`s structure" -> its structure

* "For examples please refer to the /jolokia/jmx/test/config.yml." -> For examples please refer to https://github.com/elastic/beats/blob/master/metricbeat/module/jolokia/jmx/_meta/test/config.yml.
(Though we probably want to sub in the appropriate/corresponding version of the config.yml instead of pointing to master for all releases).

**Comment by dedemorton** [comment]
Monica fixed the code formatting issue in https://github.com/elastic/beats/commit/fefa288cca1556dba21dd9d58a27bdcf4b7862ad. I still need to edit this topic though (it's on my list).

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/beats/pull/4320
