### ISSUE TITLE
Use Index date index name processor for filebeat modules

### ISSUE THREAD

**Issue by gingerwizard** [elastic/beats#4325]
Enhancement to assist with bulk indexing of historical log files. This only applies if using filebeat modules - as otherwise we can assume the user has deeper knowledge of the downstream ingestion process.

If ingesting directly from Filebeat to ES, logs are indexed into timestamped indices by default - the date used is the current system time as the logs themselves are obviously unknown at the filebeat layer (date parsing is handled by an ingest processor). If using a module to ingest historical data from a system, the resulting documents are therefore indexed into a single index using the current date if if entries in the file are older - this can present initial scaling issues and later management issues e.g. if using curator to delete data based on index timestamp.

This enhancement requests suggests we use the  [date index name processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/date-index-name-processor.html)  for filebeat modules - so that documents are indexed into the correct index. This could be enabled via a simple module level switch e.g. use_file_date_for_index or just enabled by default.

**Comment by amonhuang** [comment]
I have same problem too when I setting prospector to parse files and it cause great impact on system time which not in UTC+0. It is strongly recommended to fix it as soon as possible.

**Comment by dadoonet** [comment]
+1 to this:

The current pipeline for nginx module for example does that for errors:

```json
      {
        "date": {
          "field": "nginx.error.time",
          "target_field": "@timestamp",
          "formats": [
            "YYYY/MM/dd H:m:s"
          ]
        }
      },
```

We basically need to add:

```json
    {
      "date_index_name" : {
        "field" : "@timestamp",
        "index_name_prefix" : "filebeat-6.1.2-",
        "date_rounding" : "d"
      }
    }
```

**Comment by ruflin** [comment]
@tsg I remember we discussed some changes here but not sure if we ever did some fixes?
