### ISSUE TITLE
logstash output on master bug

### ISSUE THREAD

**Issue by joshbressers** [elastic/beats#4337]
I discovered this working with filebeat on a raspberry pi (ARM) system. I did not try to reproduce on an x86 system.

Here is my configuration file:
$ grep -v '#' filebeat.yml | sed '/^$/d'
filebeat.prospectors:
- input_type: log
 paths:
   - /var/log/*
output.logstash:
 hosts: ["macbook-pro:5044"]
logging.level: debug

The output from running filebeat is below. I can log directly to ES without problems. I also have no problems when I built a binary using the 5.4 branch. I've done no investigation as the builds take a very very long time on the pi.

----------------------------------------------------------------------------

panic: interface conversion: interface {} is nil, not string
 
goroutine 25 [running]:
github.com/elastic/beats/libbeat/outputs/logstash.makeLogstashEventEncoder.func1(0x78eed8, 0x119be008, 0x37ee78, 0xc40de8, 0x11116a20, 0x3, 0x0)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/libbeat/outputs/logstash/json.go:37 +0x2d4
github.com/elastic/beats/vendor/github.com/elastic/go-lumber/client/v2.(*Client).serialize(0x11203ce0, 0xc41628, 0x11870000, 0x1187a000, 0xa, 0xa, 0x0, 0x0)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/vendor/github.com/elastic/go-lumber/client/v2/client.go:207 +0x4c
github.com/elastic/beats/vendor/github.com/elastic/go-lumber/client/v2.(*Client).Send(0x11203ce0, 0x1187a000, 0xa, 0xa, 0x1141bca8, 0x119be050)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/vendor/github.com/elastic/go-lumber/client/v2/client.go:123 +0x19c
github.com/elastic/beats/vendor/github.com/elastic/go-lumber/client/v2.(*SyncClient).Send(0x110e3218, 0x1187a000, 0xa, 0xa, 0xa, 0xa, 0x3)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/vendor/github.com/elastic/go-lumber/client/v2/sync.go:60 +0x38
github.com/elastic/beats/libbeat/outputs/logstash.(*client).sendEvents(0x11203ca0, 0x1120e000, 0xa, 0x7f2, 0x2, 0x0, 0x1)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/libbeat/outputs/logstash/sync.go:134 +0x128
github.com/elastic/beats/libbeat/outputs/logstash.(*client).publishWindowed(0x11203ca0, 0x1120e000, 0x7f2, 0x7f2, 0x705c4, 0x2ce994, 0x112220b0)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/libbeat/outputs/logstash/sync.go:116 +0x140
github.com/elastic/beats/libbeat/outputs/logstash.(*client).PublishEvents(0x11203ca0, 0x1120e000, 0x7f2, 0x7f2, 0x0, 0x0, 0x7, 0x0, 0x0)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/libbeat/outputs/logstash/sync.go:75 +0x68
github.com/elastic/beats/libbeat/outputs/mode/single.(*Mode).PublishEvents.func1(0x11203d00)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/libbeat/outputs/mode/single/single.go:89 +0x58
github.com/elastic/beats/libbeat/outputs/mode/single.(*Mode).publish(0x11203d00, 0xc44d40, 0x11a34410, 0x1, 0x1141bdc8, 0x5, 0x83c2ae)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/libbeat/outputs/mode/single/single.go:144 +0x238
github.com/elastic/beats/libbeat/outputs/mode/single.(*Mode).PublishEvents(0x11203d00, 0xc44d40, 0x11a34410, 0x1, 0x1120e000, 0x7f2, 0x7f2, 0x1, 0x1)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/libbeat/outputs/mode/single/single.go:99 +0x58
github.com/elastic/beats/libbeat/outputs/logstash.(*logstash).BulkPublish(0x1121a1f0, 0xc44d40, 0x11a34410, 0x1, 0x1120e000, 0x7f2, 0x7f2, 0x1101f784, 0x0)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/libbeat/outputs/logstash/logstash.go:195 +0x58
github.com/elastic/beats/libbeat/publisher.(*outputWorker).sendBulk(0x11222180, 0x1101f68c, 0x1120e000, 0x7f2, 0x7f2)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/libbeat/publisher/output.go:112 +0xe4
github.com/elastic/beats/libbeat/publisher.(*outputWorker).onBulk(0x11222180, 0x1101f68c, 0x1120e000, 0x7f2, 0x7f2)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/libbeat/publisher/output.go:88 +0x20c
github.com/elastic/beats/libbeat/publisher.(*outputWorker).onMessage(0x11222180, 0x11230de0, 0x101, 0xc44d40, 0x11a34410, 0x0, 0x0, 0x1120e000, 0x7f2, 0x7f2)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/libbeat/publisher/output.go:70 +0x70
github.com/elastic/beats/libbeat/publisher.(*messageWorker).onEvent(0x11222180, 0x11230de0, 0x101, 0xc44d40, 0x11a34410, 0x0, 0x0, 0x1120e000, 0x7f2, 0x7f2)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/libbeat/publisher/worker.go:83 +0x60
github.com/elastic/beats/libbeat/publisher.(*messageWorker).run(0x11222180)
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/libbeat/publisher/worker.go:69 +0x15c
created by github.com/elastic/beats/libbeat/publisher.(*messageWorker).init
    /home/jenkins/workspace/Filebeat/src/github.com/elastic/beats/libbeat/publisher/worker.go:57 +0xfc

**Comment by tsg** [comment]
Thanks for posting the report, in the meantime we should have a fix in progress at: https://github.com/elastic/beats/pull/4331
