### ISSUE TITLE
Call out Jolokia agent installation requirement in metricbeat documentation

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#4344]
Users out there may not have heard of Jolokia before.  

Currently, our [documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-jolokia.html) does not reference their installation guide or call out the Jolokia agent as a pre-requisite for this metricbeat module (we have users looking at our metricset named "jmx" and expecting it to work directly against any jmx server).

In the https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-jolokia-jmx.html section, we simply mention that this is tested against Jolokia 1.3.4.

It will be helpful to call out Jolokia agent being required.  In fact, we don't link to Jolokia documentation other than in the limitations section of our guide.

The following will be helpful to provide as a reference:

https://jolokia.org/reference/html/agents.html

>Jolokia is an agent based approach to JMX, which requires that clients install an extra piece of software, the so-called agent. This software either needs to be deployed on the target server which should be accessed via remote JMX (Section 2.1, “Agent mode”), or it can be installed on a dedicated proxy server (Section 2.2, “Proxy Mode”). 

i.e. Users must first install the agent either on the target server, or on a dedicated proxy server.

We probably also want to have a short paragraph in the doc that talks about how we interact with Jolokia, eg.

Metricbeat simply communicates with the Jolokia HTTP/REST endpoint made available by the Jolokia agent (installed either as an agent running on the target JMX sever, or on a dedicated proxy server).  This HTTP/REST endpoint will expose the JMX metrics over HTTP/REST/JSON for consumption by the metricbeat.

**Comment by Budman17r** [comment]
+1

**Comment by ppf2** [comment]
Furthermore, I just found out from @ruflin that our Jolokia module implementation does not currently support communicating with a Jolokia agent when the agent is installed using the proxy mode.  

>https://jolokia.org/reference/html/agents.html
Jolokia is an agent based approach to JMX, which requires that clients install an extra piece of software, the so-called agent. This software either needs to be deployed on the target server which should be accessed via remote JMX (Section 2.1, “Agent mode”), or it can be installed on a dedicated proxy server (Section 2.2, “Proxy Mode”).

So in addition to adding general pre-requisite information to the documentation on Jolokia agent installation, let's call out the agent mode as the only mode we support today.

**Comment by dedemorton** [comment]
This was fixed in https://github.com/elastic/beats/pull/7969, but didn't get closed.
