### ISSUE TITLE
MetricBeat - System Info Metricset

### ISSUE THREAD

**Issue by ragurajendran86** [elastic/beats#4356]
Enhancement Request to report OS version Info as part of system module. Following fields are expected,

- OperatingSystem
   - Name
   - Architecture
   - Machine
   - Version
   - PatchLevel
   - Vendor
   - VendorVersion
   - VendorCodeName
   - DataModel
   - CpuEndian
   - IPAddress
   - FQDN
- CPU
   - ProcessorDetails
   - No.of Cores
- Mem
   - InstalledRAM
- AdditionalInfo
   - Uptime

Discuss: https://discuss.elastic.co/t/metricbeat-sytem-module-missing-version-details-metric/86189?u=andrewkroh

**Comment by ruflin** [comment]
Sounds like this could be the `system.info` metricset.

**Comment by ragurajendran86** [comment]
@ruflin, yes we can call it as system.info.

**Comment by webmstr** [comment]
How about including network interface speed (e.g. /sys/class/net/eth0/speed), which could then be used with system.network.*.bytes to compute utilization.

**Comment by FirassGzayil** [comment]
Hi All,
I am examining metricbeat to be our monitoring data collector. and it looks very well
But it doesn't provide system information as suggested in this thread.

Do you guy have estimation when would this feature be developed?

**Comment by ragurajendran86** [comment]
@ruflin Is this enhancement requirement in beats roadmap?

**Comment by andresrc** [comment]
Most of the data is already included by `add_host_metadata` or in other metricsets. If we could complete the missing fields (if any) there, what would be the use case to satisfy with a different metricset just for this?
