### ISSUE TITLE
Can't run filebeat on Windows Server 2012R2

### ISSUE THREAD

**Issue by ricardojdsilva87** [elastic/beats#436]
Hello,

I've tested the last version of Filebeat available on the elastic website and I can't put it running.

I'm using the following command just to debug:
C:\Scripts\filebeat\filebeat -c C:\Scripts\filebeat\filebeat.yml -d "*" -v

I've tested also the last nightly and it has the same behaviour.
https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/

I know that it isn't a problem on the configuration file, because if I use a beta version that I was using until know, it works (filebeat-1.0.0-beta4-windows).
Even running the configtest seems to have no effect, it just creates a new line on powershell.

Also I've noticed that the powershell script to create the service has a strange path, altough I didn't try to run it yet
![image](https://cloud.githubusercontent.com/assets/12953702/11563780/b0ae458a-99cd-11e5-845d-b1c3bf3139e3.png)

On the script itself:
-binaryPathName "$workdir\\filebeat.exe -c $workdir\\filebeat.yml"

What can I do to solve the problem, since a beta version seems to work correctly?
If more info is missing I can provide it.

Thanks for the help

**Comment by ruflin** [comment]
@ricardojdsilva87 Could it be that your issue is related to this issue here with the space? https://github.com/elastic/beats-packer/pull/32

Can you run the following and share the output? It would also be helpful to see your config file. There are some BC breaks we had from beta4 to 1.0.0 like in the outputs.
```
C:\Scripts\filebeat\filebeat -c C:\Scripts\filebeat\filebeat.yml -d "*" -e
```

**Comment by ricardojdsilva87** [comment]
Hello @ruflin 

I have runned with the -e flag and checked why it was not working.
Basically the files were being read correctly, but nothing was not being sent, and no error was being logged.
Solution: comment logstash-forwarder and comment beats

I forgot that I have the servers running with logstash forwarder and needed to change the input plugin

Sorry about that...

As for the configuration file, it works without any quotation marks, here it is what I'm using:

############################# Filebeat ######################################
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    # Each - is a prospector. Below are the prospector specific configurations
    -
      paths:
        - C:\inetpub\logs\LogFiles\*\*.*
      input_type: log
      document_type: iis-logs
      ignore_older: 24h
      #fields:
      #  type: iis-logs
      #scan_frequency: 10s

############################# Output ##########################################

# Configure what outputs to use when sending the data collected by filebeat.
# You can enable one or multiple outputs by setting enabled option to true.
output:
  logstash:
    enabled: true
    hosts: ["server:port"]
    index: iis-logs
    tls:
      certificate_authorities: ['C:\Scripts\filebeat\logstash-forwarder.crt']
      certificate: 'C:\Scripts\filebeat\logstash-forwarder.crt'
      certificate_key: 'C:\Scripts\filebeat\logstash-forwarder.key'

Thanks for the help

**Comment by ruflin** [comment]
@ricardojdsilva87 That means now all is working as expected, right?

**Comment by ricardojdsilva87** [comment]
Yes everything working as expected

Thanks again
