### ISSUE TITLE
Logging API

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#4365]
It would be nice if beats can have a logging api like Logstash where users can dynamically enable/increase the logging level of different classes.  This will be helpful for production environment/live troubleshooting.

**Comment by ruflin** [comment]
Currently beats does not have an endpoint to interact with a beat. We recently introduce a configurable http endpoint to look at stats. In general this seems more something that would have to be done through config reloading or centralised configuration.

In general we are thinking about redoing parts of the logging like also moving to json. It would definitively be interesting to enable something like this especially for debugging.

For the reference, LS logging API: https://www.elastic.co/guide/en/logstash/current/logging.html
