### ISSUE TITLE
Metricbeat Windows service fails to start at boot

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#4373]
For confirmed bugs, please report:
- Version: 5.4 (other versions appear to be affected)
- Operating System: Windows 2012 R2
- Steps to Reproduce:
  - Install metricbeat as a service, enable service, reboot.
  - Check the event log and see that the service failed to start due to a timeout.

Discuss:
- https://discuss.elastic.co/t/metricbeat-windows-fails-to-start-on-reboot-timeout/84973
- https://discuss.elastic.co/t/metricbeat-5-1-2-does-not-start-automatically/86165/6

**Comment by radoondas** [comment]
Little information from setup might help as report from systems with this issue:
On the server with metricbeat 5.1.2 "Automatic Delayed Start" helped.
But on the server with metricbeat 5.4.0 didn't.

**Comment by Elufimov** [comment]
We use delayed start as workaround on all beats.

**Comment by ismael-hasan** [comment]
- Version 5.2.2
- WIndows 10
- Steps to reproduce
  - Install Metricbeat as a service
  - Set startup to automatic
  - Restart

Upon restart, the service is not restarted; it seems it times out; Windows event logs show: 
```
EventID 7009 - A timeout was reached (30000 milliseconds) while waiting for the metricbeat service to connect.
```
```
EventID 7000 - The metricbeat service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.
```
Using automatic delayed start solves the issue

**Comment by PhaedrusTheGreek** [comment]
I'm experiencing this issue with Metricbeat and Filebeat 5.4 under Windows, and setting the service the "Automatic Delayed Start" **did not** resolve the issue.

From the Event Log:

```
The DataHub metricbeat service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.
```

```
A timeout was reached (30000 milliseconds) while waiting for the DataHub metricbeat service to connect.
```

**Comment by andrewkroh** [comment]
These are PRs to the various release branches.

5.4 - #4499
5.5 - #4500
6.0 (master) - #4491

**Comment by ismael-hasan** [comment]
Thank you @andrewkroh !

**Comment by HusseinKothari26** [comment]
I'm still facing the same issue. I tried installing metricbeat 5.4.3 and 5.5.0 but Metricbeat Windows service still fails to start. It seems this fix is not working.

**Comment by andrewkroh** [comment]
@HusseinKothari26 Is there any log output from the Beat when it fails to startup?

**Comment by PhaedrusTheGreek** [comment]
Any other issues circumstances might be due to this issue:  https://github.com/elastic/beats/issues/5453, where the reason for startup failure just isn't conveniently visible.
