### ISSUE TITLE
loadbalance:true doesn't work?

### ISSUE THREAD

**Issue by mrjameshamilton** [elastic/beats#4376]
I've set loadbalance:true with two Logstash instances in the array of hosts. One instances gets way more than the other. I'm using the metrics plugin to see the throughput and one gets 100s per second, the other 10s per second.

**Comment by ruflin** [comment]
Could you share your Beat version and the full output config?

**Comment by mrjameshamilton** [comment]
5.3.0-1

`  logstash:
    # The Logstash hosts
    hosts: ["host1:5044","host2:5044"]

    # Number of workers per Logstash host.
    #worker: 1

    # The maximum number of events to bulk into a single batch window. The
    # default is 2048.
    #bulk_max_size: 2048

    # Set gzip compression level.
    #compression_level: 3

    # Optional load balance the events between the Logstash hosts
    loadbalance: true

    # Optional index name. The default index name depends on the each beat.
    # For Packetbeat, the default is set to packetbeat, for Topbeat
    # top topbeat and for Filebeat to filebeat.
    #index: filebeat

    # Optional TLS. By default is off.
    #tls:
      # List of root certificates for HTTPS server verifications
      #certificate_authorities: ["/etc/pki/root/ca.pem"]

      # Certificate for TLS client authentication
      #certificate: "/etc/pki/client/cert.pem"

      # Client Certificate Key
      #certificate_key: "/etc/pki/client/cert.key"

      # Controls whether the client verifies server certificates and host name.
      # If insecure is set to true, all server host names and certificates will be
      # accepted. In this mode TLS based connections are susceptible to
      # man-in-the-middle attacks. Use only for testing.
      #insecure: true

      # Configure cipher suites to be used for TLS connections
      #cipher_suites: []

      # Configure curve types for ECDHE based cipher suites
      #curve_types: []
`

**Comment by ruflin** [comment]
Could you also share your log file. The lumberjack protocol does throttle automatically if one of the instance is not fast enough. `loadbalance` does not necessarely evenly distribute the events. But @urso knows more details here.

Does the uneven distribution cause any issues?

**Comment by kvch** [comment]
Closing as it's an old question. If you still have a problem feel free to post it on our Discuss forum: https://discuss.elastic.co
