### ISSUE TITLE
Expose RenegotiateFreelyAsClient for SSL/TLS

### ISSUE THREAD

**Issue by brandonmensing** [elastic/beats#4386]
By default, Apache will occasionally trigger a renegotiation for the SSL session. When Heartbeat gets the reset, there is an error in the logs: local error: tls: no renegotiation.

This feature in Go would allow Heartbeat to deal with this:
https://golang.org/pkg/crypto/tls/#RenegotiationSupport

**Comment by andrewkroh** [comment]
I opened PR #5353 to get this feature into 6.1. After that merges I'll do a backport to get it into a future 5.6 release (it missed the 5.6.3 freeze).

**Comment by brandonmensing** [comment]
@andrewkroh If we're going to add this to a patch release in 5.6, could we also add it to a patch in 6.0.x?

**Comment by andrewkroh** [comment]
We can patch 6.0 too. I'll have to remember to update the 6.0 branch after the GA release is made.
