### ISSUE TITLE
[Feature] - Metricbeat for libvirt/KVM

### ISSUE THREAD

**Issue by rikatz** [elastic/beats#4402]
This is a feature request:

It would be great if Metricbeat could collect libvirt stats (primary domains, but other stats are welcome).

A Go library I've found and may help:

- https://github.com/digitalocean/go-libvirt

Thanks!

**Comment by ruflin** [comment]
@rikatz Would be great to have support for this. Interested to contribute a module? :-)

**Comment by rikatz** [comment]
@ruflin I've talked to @amandahla and she will take a look at this, after she finishes the RabbitMQ module ;)

**Comment by ruflin** [comment]
Awesome. 🎉

**Comment by amandahla** [comment]
@rikatz I'll try this one, ok?
https://github.com/libvirt/libvirt-go

**Comment by rikatz** [comment]
@amandahla Not sure it's a good idea, as this depends on system libraries (as libvirt.so, libvirt-qemu.so and libvirt-lxc.so) and goes against the 'independency' of metricbeats.

This is way I've suggested to use the go-libvirt from digitalocean :) it seems its independent of system libs and programs.

Tks

**Comment by amandahla** [comment]
@rikatz Ok, just mind the warning "All packages contained in this repository should be treated as pre-production software with an unstable API."... ;-)

**Comment by exekias** [comment]
Awesome you are working on this! As for the library, yes, we always look for alternatives having multi OS support in mind. I suggest you look around, https://github.com/digitalocean/go-libvirt doesn't look bad anyway, you can flag this module as experimental in first versions

cheers!

**Comment by amandahla** [comment]
Waiting for this [PR](https://github.com/digitalocean/go-libvirt/pull/39) so I can start working here. :-)

**Comment by FROSADO** [comment]
Hello, there is any progress on this feature?

**Comment by amandahla** [comment]
@FROSADO I'll try to remember where did I stop here. Any help/opinions are welcome. 😄

**Comment by jsoriano** [comment]
@amandahla @rikatz now that #6265 has been merged, should we clouse this issue or do you want to leave this open to track the progress on other possible metric sets for kvm?

**Comment by jsoriano** [comment]
Perfect :+1: closing this.
