### ISSUE TITLE
Configuration Validation

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/beats#4416]
- Version: filebeat-6.0.0-alpha1
- Operating System:  OSX
- Steps to Reproduce: 

Filebeat Config:

```
output.logstash:
  hosts: ["test-cname.test-zone.com:5044"]
ssl.certificate_authorities: ["/ca/cacert.pem"]
```

The result of this configuration is that the SSL configuration is ignored.     Because some of the default configuration files have many comments in them, it's difficult to visually line up the YML, and so a new user might easily make an indentation error that would go unchecked.

**Comment by tsg** [comment]
Yeah, this is the source of a lot of frustration, unfortunately it's tricky to do with the current YAML lib that we are using. We'll discuss it internally.

**Comment by ppf2** [comment]
Hope this improves with Agent :)

**Comment by jlind23** [comment]
Backlog grooming: Stalled issue, closing for now. Feel free to reopen it if needed
