### ISSUE TITLE
Support Jolokia agent in proxy mode

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#4421]
Currently, we [do not support](https://github.com/elastic/beats/issues/4344) the Jolokia agent when it is run in [proxy](https://jolokia.org/features/proxy.html) mode.  There are users out there with IT restrictions and not able to get approvals for installing a direct agent so supporting the proxy mode will be helpful for these situations.

**Comment by tsg** [comment]
I wonder how come the proxy mode is not supported? Any idea on what exactly we're missing? Or is one of the limitations listed there affecting us?

**Comment by ruflin** [comment]
The reason I think it is not going to work in proxy mode is that proxy mode requires the url, username and password passed. And that is not possible in our config at the moment:

```
  {
    "type":"READ"
    "mbean":"java.lang:type=Threading",
    "attribute":"ThreadCount",
    "target": { 
                "url":"service:jmx:rmi:///jndi/rmi://jboss-as:8686/jmxrmi",
                "password":"admin",
                "user":"s!cr!t"
              },
  }
```

**Comment by ruflin** [comment]
@whale-shark Looking at this issue I saw that you did a commit referencing this issue. Does the commit you made work? If yes, any chance to contribute it back?

**Comment by whale-shark** [comment]
@ruflin Thank you for pointing out. I read a procedure and made a request. Please tell me if there is any mistake. #6475

**Comment by ruflin** [comment]
@whale-shark Awesome. Left some comments on the PR.

Are you using this code on your end in production / testing? Did you compile your own beat?

**Comment by whale-shark** [comment]
@ruflin Thank you for checking.

I built it locally on my CentOS.
I was able to get the HeapMemoryUsage from remote Java VM  by using the result of building.

The bundled test did not work well from the beginning, so I could not do it.
For more details, I wrote in PR.

**Comment by balamacab** [comment]
Any binary to test it?

**Comment by ruflin** [comment]
@balamacab For a binary you would have to check out https://github.com/elastic/beats/pull/6475 and run `make` or `go build` on your end.

**Comment by ruflin** [comment]
Yes, proxy mode should now be supported. @jsoriano Please correct me if that is not the case.
