### ISSUE TITLE
Proc monitoring with Packetbeat on tcp6

### ISSUE THREAD

**Issue by tomaszrichert** [elastic/beats#4443]
There is a simple bug in proc monitoring feature of packetbeat, that tcp6 ports are not being scanned.
I've described it here:
https://discuss.elastic.co/t/packetbeat-support-for-tcp6/87894

I believe i've found the issue in code, I've corrected it and made a pull request: https://github.com/elastic/beats/pull/4442

With this change its working and scanning also tcp6 file, however it's not able to parse some entries due to next error:

> Error parsing IP and port: strconv.ParseInt: parsing "0000000000000000FFFF00000100007F": value out of range

Edit:
fixed parse bug for ipv6 - included in pull request.

**Comment by andrewkroh** [comment]
Fixed in #4442.
