### ISSUE TITLE
Change filebeat error field mapping from keyword to text + review other keyword mapping

### ISSUE THREAD

**Issue by stevedodson** [elastic/beats#4446]
- Version: Filebeat 5.4.0 
- Operating System: Linux ip-xxx 4.9.20-11.31.amzn1.x86_64 #1 SMP Thu Apr 13 01:53:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Steps to Reproduce: See below

Note: these notes apply to the Nginx module:

If a message doesn't match a grok pattern then an `error` field is set via:
```
     {
        "set": {
          "field": "error",
          "value": "{{ _ingest.on_failure_message }}"
        }
      }
```
This error field is currently mapped via `filebeat.template.json` as:
```
        "error": {
          "ignore_above": 1024,
          "type": "keyword"
        },
```

The error message contains the input message and so if the input message is large (> 1024 characters) the error message is not indexed as (`ignore_above:1024` by default). Sample Nginx logs from a large site have a large number of input messages > 1024 characters. This makes searching for error messages difficult (see **https://github.com/elastic/elasticsearch/issues/24256**).

The proposal is to change the type of the `error` field to `text`. Other `keyword` fields that could be large, and whether the policy should be `text` + `keyword` should be reviewed.

**Comment by tsg** [comment]
Looks like the error field is already marked as `text` for 6.0: https://github.com/elastic/beats/blob/master/libbeat/_meta/fields.common.yml#L51

Thanks for the report.
