### ISSUE TITLE
[Winlogbeat] Add option to read .evt and .evtx files

### ISSUE THREAD

**Issue by ghost** [elastic/beats#4450]
Would it be possible to have a functionality which would allow to read .evt files directly ? 
Something like : 

winlogbeat:
  prospectors:
    - input_type: winlog
      paths:
        - C:\System32\Winevt\Logs\ *.evt

**Comment by andrewkroh** [comment]
What are the use cases for reading from .evt/.evtx files?

- Is this for loading older historical data? Like for back-filling old log data in a one-off task manner?

- Or is there a use case where you need to continuously monitor a directory for new files?

**Comment by andrewkroh** [comment]
I've opened a PR for this at https://github.com/elastic/beats/pull/11361.
