### ISSUE TITLE
Metricbeat with Jolokia metricset gives "cannot unmarshal object into Go value of type []jmx.Entry"

### ISSUE THREAD

**Issue by svpace** [elastic/beats#4460]
Hi,

- Version: 5.4.0
- Operating System: Centos 7
- Steps to Reproduce:
  - Configure some JMX metrics
  - Wait a couple of minutes/hours
  - All JMX events fail with error "cannot unmarshal object into Go value of type []jmx.Entry"
  - Restart metricbeat service and everything works again

Regards

**Comment by tsg** [comment]
@svpace Can you post the configuration file and the log file of Metricbeat, please? If you can, enabling debug output `-d "*"` might also be useful.

**Comment by svpace** [comment]
Hi,

Thank you for the "-d" tip.

The problem, apparently , was due to the IP restriction security configuration on the Jolokia side. A couple of servers were responding with status 403. Problem solved. Thank you.

Although it is stated in the docs that authentication is not supported at this time, perhaps a more specific error message would be nice improvement.
