### ISSUE TITLE
Metricbeat - Vsphere Module - Virtualmachine metricset - Get custom fields values

### ISSUE THREAD

**Issue by amandahla** [elastic/beats#4464]
Obtain custom fields values when collect metrics from virtual machines.

From here:
https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.CustomFieldsManager.Value.html

**Comment by exekias** [comment]
https://github.com/elastic/beats/pull/4469 was merged

**Comment by ishleenk17** [comment]
@amandahla : Thanks for your contibution for Vsphere
I was working at taking Vsphere integration to GA. 
Wanted to test out the custom fields part. I am using the vcsim and as I read here, you mentioned simulator does not provide testing of this. 
Although, I was able to create a custom field using govc. But not sure how we can test it out to see it in Kibana, Anything else to be done from vcsim side. Any ideas ?

**Comment by amandahla** [comment]
@ishleenk17 Hi, sorry for the delay.

In order to collect custom fields, it's necessary to change the configuration as described here:
https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-vsphere.html#_example_configuration_63

Custom fields aren't collected by default, so if you want them, you need to set "get_custom_fields" to true.

**Comment by balajivedagiri** [comment]
Hi Amandahla,

Can you guide in collecting custom fields, we have set "get_custom_fields" to true, but there is no proper documentation available on how to utilize this feature.

Regards,
Balaji
