### ISSUE TITLE
package repository

### ISSUE THREAD

**Issue by zabbal** [elastic/beats#447]
It was pretty convenient when packages.elasticsearch.org existed. Right now docs recommend to manually download and install packages which is inconvenient, does not scale and pose huge security risk. If critical vulnerability is discovered in ES or FB there is no way to get notified about it in case of manual installation. If proper repository were to be used, than update would be shipped automatically.

Moreover, there isn't much overhead compared to current situation: same packages, same web server - just slightly different directory structure and couple of trivial metadata files to serve. Any chance to get this implemented?

**Comment by andrewkroh** [comment]
Both apt and yum repositories exist for Beats. See: [Beats Platform Reference [1.0.0] » Repositories for APT and YUM](https://www.elastic.co/guide/en/beats/libbeat/current/setup-repositories.html)

Doc source: https://github.com/elastic/beats/blob/master/libbeat/docs/repositories.asciidoc
