### ISSUE TITLE
MetricSet - Add System Socket Summary

### ISSUE THREAD

**Issue by yaule** [elastic/beats#4474]
MetricSet - Add System Socket Summary

**Comment by tsg** [comment]
I think I know what this means, but could you give us a bit more details one what is that you are asking for and what is it useful for?

**Comment by yaule** [comment]
> I think I know what this means, but could you give us a bit more details one what is that you are asking for and what is it useful for?


Like modules system. process_summary .
count tcp and udp status.

Listen:  `ss -tln | grep -v State | wc -l`
………………

Use the linux "ss-a" command to count the information
