### ISSUE TITLE
document communication security

### ISSUE THREAD

**Issue by zabbal** [elastic/beats#448]
While going through documentation for filebeat I've found note that TLS is disabled by default but can be enabled for connecting to logstash. However it's unclear if it possible to TLS (and if so - how) when connecting to elastic directly.

Would be nice to get that clarified in documentation.

**Comment by andrewkroh** [comment]
Have you seen this section [TLS](https://www.elastic.co/guide/en/beats/libbeat/current/configuration.html#_tls)?

The same TLS options for Logstash can also be configured for Elasticsearch.

**Comment by dedemorton** [comment]
Just an FYI that the Filebeat Reference now contains information about all the config options (including options that are available through libbeat). This change makes it more obvious that TLS is supported for other outputs.
