### ISSUE TITLE
update.sh cannot be run on ubuntu

### ISSUE THREAD

**Issue by mrkschan** [elastic/beats#449]
There is a `sed` difference between linux and bsd ... see http://stackoverflow.com/a/5694430/433662.

I cannot run `make update` because of the `sed` difference.

**Comment by ruflin** [comment]
I assume you are referring to this line here: https://github.com/elastic/beats/blob/master/libbeat/scripts/update.sh#L39 I remember I had some troubles getting it working. I'm not sure what the best solution here is. Perhaps not use sed at all?

**Comment by mrkschan** [comment]
Can we `cp` to a temporary file, `sed` on the temporary file without
inplace flag and output to the original file. Then drop the temporary file?

**Comment by tsg** [comment]
So annoying... +1 to using a tmp file, we should support Linux :-).
