### ISSUE TITLE
Services metric

### ISSUE THREAD

**Issue by quardo** [elastic/beats#4509]
Hey, I want to get metrics of windows services (like get-services command data) .
I have not seen any metric module that doing so.
Does someone know any?

Thanks !

**Comment by andrewkroh** [comment]
Metricbeat has a [windows/service](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-windows-service.html) metricset that monitors Windows services.

There's also a windows performance monitor metricset that could be useful depending on what you want to collect.
