### ISSUE TITLE
Metricbeat - Audit module - Audit events logged to kernel log

### ISSUE THREAD

**Issue by praseodym** [elastic/beats#4513]
While evaluating the audit module in Metricbeat 6.0.0-alpha2 on Ubuntu 16.04.2 (Xenial) I noticed that the kernel will log audit events to the kernel log. The auditd daemon does not exhibit this behaviour; when it is running, audit logs only appear in `/var/log/audit/audit.log`. I would prefer audit logs not being sent to the kernel log when Metricbeat is handling them.

I'm not sure whether this is something that should be addressed in Metricbeat, e.g. by documenting additional OS configuration to change the behaviour, or that some code should be added to go-libaudit to suppress the kernel's own logging.

**Comment by andrewkroh** [comment]
Can you please enable debug logging from Metricbeat and use the "audit.kernel" selector. I'm interested in the output from [this](https://github.com/elastic/beats/blob/master/metricbeat/module/audit/kernel/audit_linux.go#L146) log message.

```
logging.level: debug
logging.selectors: ["audit.kernel"]
```

Are all events being written to the kernel log? Some events?

**Comment by praseodym** [comment]
I'm seeing the following after reboot:
```
[audit.kernel] audit status from kernel at start: status=&{Mask:0 Enabled:1 Failure:1 PID:0 RateLimit:0 BacklogLimit:8192 Lost:9 Backlog:0 FeatureBitmap:7 BacklogWaitTime:15000}
```

Additionally, I've made the following observations
* When Metricbeat *is not* running, logs appear in both `dmesg` and `journalctl` (the systemd journal).
* When Metricbeat *is* running, logs appear in `journalctl` and get picked up by Metricbeat as well.

Apparently, systemd-journald has its own way to collect audit events from the kernel ('systemd-journald-audit.socket'). From some mailing list posts I gather that `systemctl mask systemd-journald-audit.socket` should disable this behaviour (but I have yet to verify this). Furthermore, it looks like [netlink multicast functionality was added](https://github.com/torvalds/linux/commit/451f921639fea4600dfb9ab2889332bdcc7b48d3) to support this behaviour (maybe a feature go-libaudit could leverage as well?).

One thing I'm still uncertain about is why the kernel will log to `dmesg` only without Metricbeat running, while audit messages appear in `journalctl` no matter what.

**Comment by andrewkroh** [comment]
Given that journald-audit.socket has its own subscription to the messages from from the kernel I'm not concerned with the messages being logged there. Thanks for the information about the multicast feature, I wasn't aware of that so I'll look at the code and see how go-libaudit can make use of it.

I tested the behavior when auditd is disabled and I do see regular audit messages in `dmesg`. So that's the same behavior with Metricbeat. The only way I found to stop this was to disable audit in the kernel (`auditctl -e 0`).

I have a PR open that [disables](https://github.com/elastic/beats/pull/4516/files#diff-347f2c425ca532d4b3e822491ae4c334R81) auditing in the kernel when the Metricbeat audit module stops.

Additionally the PR gives Metricbeat the ability to set the failure mode. This controls the kernel's behavior when there are errors delivering audit messages to userspace. So if you don't want to see messages in the dmesg output _on error_ you can set the `kernel.failure_mode: silent` (which I made the default).

**Comment by praseodym** [comment]
I don't like the idea of disabling auditing when Metricbeat is not running. Wouldn't there be a way for the kernel to (temporarily) buffer audit events when there is no process consuming them?

Also, the question that remains is why the systemd journal doesn't produce audit logging when using auditd (vs. when using Metricbeat). I'll try to investigate this some more.

**Comment by andrewkroh** [comment]
> I don't like the idea of disabling auditing when Metricbeat is not running. Wouldn't there be a way for the kernel to (temporarily) buffer audit events when there is no process consuming them?

Since I was mostly undecided about that change, I will remove it.

> systemd journal doesn't produce audit logging when using auditd

Oh, it wasn't clear to me journald stopped recording logs when auditd was running. Maybe it some kind of inter-dependency between the systemd services (total guess).

**Comment by andrewkroh** [comment]
Are you sure that journald multicast subscriber stops receiving audit logs when auditd is running? That seems to be contrary to my understanding of the purpose of the multicast enhancement to the kernel.

It it looks like it is a known issue that audit logs spam the kernel log when auditing is enabled and auditd is not running. https://bugzilla.redhat.com/show_bug.cgi?id=1160046

**Comment by praseodym** [comment]
This was the behaviour difference that triggered me to open this issue. I also saw the reports about this occurring with auditd; it might be a difference in Ubuntu vs. other distros. I'll post a new comment when I know more.

**Comment by praseodym** [comment]
I cannot reproduce the issue any more. I'd suggest just adding documentation on how to disable logging to the systemd journal (through `sudo systemctl mask systemd-journald-audit.socket`, which I noticed is also mentioned in the [slackhq/go-audit documentation]).

[slackhq/go-audit documentation]: https://github.com/slackhq/go-audit#i-am-seeing-duplicate-entries-in-syslog

**Comment by praseodym** [comment]
When trying to reproduce #7157 on a clean Ubuntu 18.04 box I hit this issue again, but only when Auditbeat was configured with `socket_type: multicast`. It indeed looks like I'm hitting [kernel bug #1160046](https://bugzilla.redhat.com/show_bug.cgi?id=1160046) here. I'm not sure why `failure_mode: silent` doesn't help though.
