### ISSUE TITLE
Provide add_fields processor in filebeat

### ISSUE THREAD

**Issue by monitoringit** [elastic/beats#4518]
Today filebeat doesnt have add_fields processor feature which will really be helpful in enriching output event based on conditions.

This feature will allow addition of new fields whose value can be set based on processor conditions.

Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version: 
- Operating System: 
- Steps to Reproduce:

**Comment by monitoringit** [comment]
Please refer to https://discuss.elastic.co/t/harvesting-same-file-with-different-prospector-config/89546/8?u=monitoring_it

**Comment by ruflin** [comment]
This could replace on what we have with `fields` at the moment and make it more powerful. Could having both be confusing?

The advantage of `fields` is that it is probably more efficient implementation wise and simpler to use, disadvantage is it's less powerful. As I don't like two code bases doing the same thing one option could be keeping both configs but that in the background `fields:` config actually calls the fields processor.

**Comment by monitoringit** [comment]
So in the proposed solution how will one specify add_fields processor in fields: config section. Will there be processor id/name that fields will refer to. Can you share what the two configs will look like?

**Comment by andrewkroh** [comment]
The main benefit of adding fields through a processor is that conditions can be applied.

We could treat the current `fields:` config option as alias for the `add_fields` processor in the code (but this would probably be ugly to implement everywhere). With myself also being in favor of having a single way to accomplishing something, maybe would should create an `add_fields` and `add_tags` processor and deprecate `fields` and `tags`.

**Comment by monitoringit** [comment]
Any idea when can this feature be added?

**Comment by monitoringit** [comment]
Any updates?

**Comment by ruflin** [comment]
@urso @ph This could be a nice addition for 7.0 to deprecate the current global fields definitions.

**Comment by ph** [comment]
@ruflin Agree, and another common use case is to get values from the environment :)

**Comment by urso** [comment]
New processoors for fields and tags will be available in 7.0
