### ISSUE TITLE
Homebrew formula doesn't work with 6.0

### ISSUE THREAD

**Issue by tsg** [elastic/beats#4524]
Because the template file no longer exists in the repo, see: https://github.com/Homebrew/homebrew-core/blob/master/Formula/filebeat.rb#L28

Reported by @tsouza

**Comment by ruflin** [comment]
The same probably applies to all other beats with homebrew formulas.

**Comment by ruflin** [comment]
Closing this one as I think it's resolved. But I found an other potential issue that `modules.d` directory is missing. Will open a separate issue.
