### ISSUE TITLE
Metricbeat Output: Could you consider adding the host shadow feature like device shadow in IOT ?

### ISSUE THREAD

**Issue by pkgplus** [elastic/beats#4535]
Could you consider adding the host shadow feature like device shadow in IOT ?Getting host any monitor data from host shadow 
Using host shadow storage to get the lastest monitor data of every item will be faster and higher performance.

**Comment by andrewkroh** [comment]
Are you talking about maintaining a summary document for each host in Elasticsearch that contains only the latest metrics?

**Comment by xuebing1110** [comment]
yes, or set a fixed key for every record. For example, the fixed key for metricset `system-diskio` can use `beat.name+metricset.module+metricset.name+system.diskio.name`
