### ISSUE TITLE
beat.name default value is host name. Can it be beat name itself?

### ISSUE THREAD

**Issue by dkolli** [elastic/beats#4545]
Hi, We are using type field from Beats agent to differentiate metricbeat vs filebeat, as we create separate indices for them. MetricBeat uses the default type as "metricsets". 

In our current setup, both filebeat and metricbeat communicate with logstash on same port and we route them to different indices based on the type. 

In version 6.0 alpha version, we read and tested that type is going away and there is no type field. That will break our setup. I tried other fields like beats.name, the default value is hostname as opposed to beat name itself, and there is already a beat.hostname that contains hostname where beat runs. In my opinion that is duplication. why can't we have beat.name to be the beatname itself like metricbeat and filebeat? if that enhancement is not possible, what is the cleaner way of identifying at the logstash level between these beats other than us setting in yaml file (if we explitly set in the yml and user changes that, that would impact the logic)

**Comment by ruflin** [comment]
To differentiate between filebeat and metricbeat you could check for the `metricset` field and in filebeat for `prospector.type`. We had in the past the discussion if we should have `beat.type` which is the actual beat like `filebeat` or `metricbeat` and `beat.name` is as now as everyone can assign his own name.

**Comment by andrewkroh** [comment]
The event sent to Logstash includes an `@metadata.beat` field that you can use to determine what Beat sent the event.
