### ISSUE TITLE
Distribute tools and framework for creating modules in binary artifacts?

### ISSUE THREAD

**Issue by joshuar** [elastic/beats#4577]
It would be useful if the filebeat package that you install came with the necessary tools and framework required to be able to create a new module for a different log format.  This means I wouldn't need to clone the GH repo just to start developing my own modules.  Might also help people quickly extend an existing filebeat install with custom modules for niche log formats?

**Comment by ruflin** [comment]
I like the idea. So this would generate the base structure of the files?

@exekias I'm thinking of `filebeat module create ...` ;-)

**Comment by exekias** [comment]
Closing this one as it's too old, we are thinking about providing a tool like this outside of Filebeat
