### ISSUE TITLE
Metricbeat modules status

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#4579]
Metricbeat modules:

- **apache** 
- **ceph** (Beta / Experimental)
     - cluster_disk (Experimental)
     - pool_disk (Experimental)
     - cluster_health (Beta)
     - monitor_health (Beta)
- **couchbase** (Beta)
- **docker** (Beta)
- **dropwizard** (Beta)
- **elasticsearch** 
- **golang** (Experimental)
- **haproxy**
- **http** (Beta)
- **jolokia** (Beta)
- **kafka** (Beta)
- **kibana** (Experimental in docs)
- **Kubernetes** (Beta/Experimental)
     - event (Experimental)
     - container, node, pod, state_container, state_deployment, state_node, state_pod, state_replicaset, system, volume (Beta)
- **memcached**
- **mongodb** (Experimental)
- **mysql**
- **nginx**
- **php_fpm** (Beta)
- **postgresql**
- **prometheus** (Beta)
- **rabbitmq** (Experimental)
- **redis**
- **system**
- **vsphere** (Experimental)
- **windows** (Beta)
- **zookeeper**

Questions: ???
- Shouldn't be Elasticsearch  experimental?

cc-ed @ruflin @brandonmensing

**Comment by ruflin** [comment]
Closing this as we have now an identical auto generated list here: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-modules.html
