### ISSUE TITLE
Go-lua sometimes causing issues

### ISSUE THREAD

**Issue by tsg** [elastic/beats#4596]
The `go-lua` dependency is sometimes breaking the build, see for example [here](https://travis-ci.org/elastic/beats/jobs/249563632#L2019).

In addition, it increases the size of the repository and binary for relatively little benefit (it's used by the aerospike client). This ticket is to investigate if we can make that module work without go-lua.

**Comment by exekias** [comment]
Any idea of why is this happening randomly?

**Comment by tsg** [comment]
No, I didn't investigate. Seems to have worked on restart.

**Comment by tsg** [comment]
Happened also on Jeknins: https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/588/beat=libbeat,label=ubuntu/console

I suspect there's some sort of modtime issue that makes Go think it needs to recompile the yacc files.

**Comment by exekias** [comment]
https://github.com/elastic/beats/pull/4649 was merged, fixes this
