### ISSUE TITLE
Run metricbeat within docker error.

### ISSUE THREAD

**Issue by wangxf1987** [elastic/beats#4604]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version: 
   5.4.1

- Operating System:  
   CentOS Linux release 7.3.1611 (Core)

- Steps to Reproduce: 
   I want to run the metricbeat in docker, but when executed the command.
   `docker run \
  --volume=/proc:/hostfs/proc:ro \ 
  --volume=/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro \ 
  --volume=/:/hostfs:ro \ 
  --net=host 
  docker.elastic.co/beats/metricbeat:5.4.3 -system.hostfs=/hostfs`
  Return:
  `stat -system.hostfs=/hostfs: no such file or directory".`
  I think that the ENTRYPOINT set error when run a docker, so I try to modified the command like this:
  `docker run \
  --volume=/proc:/hostfs/proc:ro \ 
  --volume=/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro \ 
  --volume=/:/hostfs:ro \ 
  --net=host 
  docker.elastic.co/beats/metricbeat:5.4.3 metricbeat -e -system.hostfs=/hostfs`
There is no error in the sreen, But I not sure that the metericbeat is really work.
So, please check my steps and give me correct answer if your want.

**Comment by exekias** [comment]
Hi @wangxfbelieve, as you figured out, the issue is that the docker image doesn't provide an `ENTRYPOINT`, see https://github.com/elastic/beats-docker/issues/6

Your PR (https://github.com/elastic/beats/pull/4611) should fix docs

**Comment by andrewkroh** [comment]
There is an ENTRYPOINT now in all beat docker images.
