### ISSUE TITLE
Beats central monitoring via Elasticsearch - Phase 1

### ISSUE THREAD

**Issue by tbragin** [elastic/beats#463]
Migrated from: https://github.com/elastic/libbeat/issues/201

**Comment by jacobluo** [comment]
i cannot say any hearbeat config in filebeat.full.yml (version 5.1), please help

**Comment by andrewkroh** [comment]
@jacobluo Use https://discuss.elastic.co/beats for questions.

**Comment by monicasarbu** [comment]
Closing the issue as it duplicates https://github.com/elastic/beats/issues/3422
