### ISSUE TITLE
beats requires additional security privileges to read .kibana index

### ISSUE THREAD

**Issue by LeeDr** [elastic/beats#4631]
- Version: master 6.0.0-alpha3 SNAPSHOT
- Operating System: Ubuntu (installed from .deb packages)
- Steps to Reproduce: 
In 5.x I could create a role and user like these and use this user in the *beats.yml files to enable writes to Elasticsearch.  But in master this user doesn't work.   I'm looking at metricbeat specifically right now but I think it's probably all beats.  When I enable audit logging in Elasticsearch I see this message;

`[access_denied]   origin_type=[rest], origin_address=[127.0.0.1], principal=[beats_internal], action=[indices:admin/get], indices=[.kibana], request=[GetIndexRequest]`

I know if I add `superuser` role to the beats user then the writes work OK.  And I can probably add the `kibana_system` role instead of superuser.  But any additional permissions should be minimized and documented as breaking changes.

I'm marking this with bug and docs labels, but those might need to be adjusted.

I don't know yet if/how this might impact 5.6.0

**Comment by LeeDr** [comment]
I see I didn't actually show what role and user I was using.   Here they are;

```
curl -k -POST ${ESURL}/_xpack/security/role/beats_writer -H 'Content-Type: application/json' -d '{
  "cluster": ["manage_index_templates","monitor"],
  "indices": [
    {
      "names": [ "*beat-*" ],
      "privileges": ["write","delete","create_index"]
    }
  ]
}'

curl -k -POST ${ESURL}/_xpack/security/user/beats_internal -H 'Content-Type: application/json' -d '{
  "password" : "changeme",
  "roles" : [ "beats_writer" ],
  "full_name" : "beats_internal",
  "email" : "beats_internal@test.co"
}'
```

**Comment by LeeDr** [comment]
We think this is fixed by https://github.com/elastic/beats/commit/e6daf4a4c40e962889e4a9ce63ca3ec43f5f576c

**Comment by tsg** [comment]
@LeeDr Did you had the chance to verify the fix? Can we close the issue?

**Comment by LeeDr** [comment]
@tsg no, I haven't had a chance yet.  I'm working on a 5.x task right now but I'll try to get back to this very soon.
I don't think I was clear in the original description that I thought this problem was related to beats writing data to Elasticsearch, not beats creating dashboards.  But I think the default behavior now is that every time the beat starts it checks if they're there in .kibana index? Is that true?  Or maybe depends on some parameters?

**Comment by tsg** [comment]
@LeeDr Sorry for the late reply, it should only check for the `.kibana` index when called with `--setup` or `setup`.

**Comment by LeeDr** [comment]
Yes, this seems to be working for me now that I understand what I'm doing.

My .yml file has an `output.elasticearch username:`  which is my user which can write beats data to Elasticsearch but does not have access to .kibana index.

and a `setup.kibana username:` which I'm currently using the kibana user for.
