### ISSUE TITLE
Use Elasticsearch as a central config store for beats - Phase 1

### ISSUE THREAD

**Issue by tbragin** [elastic/beats#464]
Migrated from: https://github.com/elastic/libbeat/issues/200

**Comment by friesoft** [comment]
Any news on centralized configuration for beats through Kibana? We really want this feature :)

**Comment by jakauppila** [comment]
It's been a few months; curious if there's any update on this?

**Comment by ph** [comment]
@jakauppila We are still planning to do it, no timeline yet.
