### ISSUE TITLE
Fix logrus dependency

### ISSUE THREAD

**Issue by mcandre** [elastic/beats#4642]
github.com/Sirupsen/logrus has moved to github.com/sirupsen/logrus, update dependencies accordingly.

**Comment by tsg** [comment]
Thanks @mcandre, will do.

**Comment by liketic** [comment]
@tsg Can I take this?

**Comment by ruflin** [comment]
@liketic Would be great.

**Comment by andrewkroh** [comment]
Fixed in #11330.
