### ISSUE TITLE
heartbeat: spread monitor scheduling over time

### ISSUE THREAD

**Issue by fredericve** [elastic/beats#4664]
We're using heartbeat to monitor over 100 http(s) urls which all point to the same machine. The internal scheduling of heartbeat runs all of these monitors at the same time, causing burst traffic to the server.

This would be solved by spreading the monitor checks over time, having a more distributed load on both the server and the client machine.

So here's a feature request for just that :-)

**Comment by urso** [comment]
Have you tried the [scheduler.limit](https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-heartbeat-options.html#heartbeat-scheduler-limit) setting? 

This limits the number of concurrently executed tasks. the http monitor splits it's tasks into name resolution and connect+http-request. While this is not a rate-limiting setting, it still ensures HTTP requests can be made one after another.

**Comment by fredericve** [comment]
Hello @urso,

That setting is indeed activated in our config:
```
heartbeat.scheduler:
  limit: 60
```

Unfortunately, despite this setting all requests still fire at the same time.

**Comment by andrewvc** [comment]
@fredericve how many hosts do you monitor? Is it less than 60?

**Comment by fredericve** [comment]
@andrewvc currently we're at 183 url's we're monitoring.

We stopped using heartbeat for this in the meantime. I don't know if this might be applicable to other heartbeat users though.

**Comment by andrewvc** [comment]
@fredericve thanks for the feedback. I'm wondering if setting that value lower might have helped.

That said, users shouldn't have to configure things like that, they should just work. This is something we should definitely fix in a subsequent version.

**Comment by andrewvc** [comment]
@fredericve also, what was the interval of pinging? Was it `1s`?

**Comment by fredericve** [comment]
@andrewvc no. From the old configuration file: `schedule: '@every 30s'`

**Comment by andrewvc** [comment]
@fredericve hmmm, that's interesting and useful information. So, there's no chance of checks overlapping, which can happen when the interval is 1s, but endpoints take say 2s to respond. 

It seems to just be about the initial burst of traffic. Something for us to test and reproduce ourselves. Thanks!
