### ISSUE TITLE
Metricbeat dashboards for Kafka

### ISSUE THREAD

**Issue by hartfordfive** [elastic/beats#4665]
I've downloaded the pre-made dashboard archive from [here](https://www.elastic.co/guide/en/beats/libbeat/5.5/import-dashboards.html), although there are no dashboards for the Kafka module.  Are there any plans on adding those?  It would be a nice feature to have them pre-built and only need to import the dashboards/visualizations.

**Comment by ppf2** [comment]
Related: https://github.com/elastic/beats/issues/5451

**Comment by jsoriano** [comment]
A dashboard is in progress as discussed [here](https://github.com/elastic/beats/issues/5451#issuecomment-408049000).

**Comment by jsoriano** [comment]
A dashboard has been merged to master (#8457), we expect to release it in 6.5.0.
