### ISSUE TITLE
How to dynamically change the logging level without having to restart a beat?

### ISSUE THREAD

**Issue by Mercedechf** [elastic/beats#4678]
The log level of filebeat can not be dynamically modified, why not filebeat use log4go?

**Comment by ruflin** [comment]
Just had a quick look at log4go and it does not seem to be under development: https://github.com/alecthomas/log4go

If I understand you correctly this is a feature request to dynamically change the logging level without having to restart a beat? Could you please adjust title and text of this issue accordingly?

**Comment by Mercedechf** [comment]
I have updated the issue, Is there anyway to solve the problem?

**Comment by ruflin** [comment]
@Mercedechf There is still lots of boiler plate in the issue. Could you remove that?

Currently your only way is to restart the beat.

**Comment by Mercedechf** [comment]
That is awful！Any plan in the future?
