### ISSUE TITLE
Metricbeat option to ignore NFS auto-mount

### ISSUE THREAD

**Issue by brandonmensing** [elastic/beats#4685]
With drop_event.when.regexp.mount_point set, metricbeat does not send stats for those filtered out file systems, but it still touches them keeping mount points active. Eventually systems started to have thousands of mount points causing input/output errors for new workers. Need a setting like ignore_nfs_automount. Metricbeat will NOT touch nfs automounts at all, so the mount point timeout can kick in.

**Comment by andrewkroh** [comment]
It looks like we already have the filesystem types internally from when we query `/etc/mtab` to get a list of filesystems. So if we introduce a new filter option like `filesystem.ignore_types: [nfs]`, we can apply that filter [before](https://github.com/elastic/beats/blob/e39b3474636e390b58ea8e2779e1fd796b20b81f/metricbeat/module/system/filesystem/filesystem.go#L37-L43) continuing to `stat` the filesystems.

The same filter would also need to be applied to the `fsstat` metricset.

**Comment by andrewkroh** [comment]
Branches:
- 5.6 - https://github.com/elastic/beats/pull/4823 (it likely was merged in time for v5.6.0)
- 6.0 - TBD (this branch is under a feature freeze)
- master - https://github.com/elastic/beats/pull/4906 (will be v6.1.0)
