### ISSUE TITLE
Add generic TLS support to any REST/HTTP based metricbeat module

### ISSUE THREAD

**Issue by brandonmensing** [elastic/beats#4694]
When Metricbeat is connecting to a service over HTTP/REST, there are cases where a reverse proxy is in place, which means users need TLS preferably with PKI.

**Comment by exekias** [comment]
I think this is a duplicate of https://github.com/elastic/beats/issues/4268? Basically the feature is implemented but not documented

**Comment by brandonmensing** [comment]
Thanks!
