### ISSUE TITLE
Creating custom output plugins

### ISSUE THREAD

**Issue by kornicameister** [elastic/beats#473]
Hi there,

do you plan to create/add functionality to register custom output plugins? I mean next to ES, Logstash there would be an option to install totally custom output plugin ? 

As far as I understood Beats is meant to be lightweight and just to ship logs somewhere else for further processing, so perhaps that's why I couldn't find something relevant regarding installation of the custom output. 

Thx for any information :)

**Comment by urso** [comment]
As go does not support go based plugins yet, there is no way to have loadable plugins?

But internally the outputs are already handled like plugins. See ES/LS outputers registering with the ouput/publisher on startup. Basically you can initialize your own 'plugin' in your custom beat. E.g. by importing the packetbeat package and basically writing your own main method (See this as example: https://github.com/elastic/beats/blob/master/packetbeat/main.go) you could register your own additional output plugin.
