### ISSUE TITLE
 abnormal shutdown ,registry file content is \0x00\0x00

### ISSUE THREAD

**Issue by skynice** [elastic/beats#4733]
- Version: 5.4.2
- Operating System: windows 2008 r2
- Steps to Reproduce: 
  1. server abnormal shutdown
  2.filebeat service can not start
  3.see filebeat registry ,the content is \0x00\0x00....registry.old is json content
  4.delete registry* ,the service started.

**Comment by andrewkroh** [comment]
I saw a similar issue in Winlogbeat and made this [change](https://github.com/elastic/beats/pull/2434). I don't recall hearing any recent reports that the issue was still occurring so that change probably fixed the issue and now we should do the change to Filebeat's registry file.

**Comment by urso** [comment]
This should be fixed in recent 6.x and upcoming 7.0 release. We added a missing `fsync` call.
