### ISSUE TITLE
Metricbeat module for Uwsgi

### ISSUE THREAD

**Issue by lagrianitis** [elastic/beats#4746]
We are using Elastic stack 5.5.0
In our ecosystem we have an API fully build in python with UWSGi processes.
I would be nice to build a metricbeat module for UWSGi reading from statsd.

**Comment by tsg** [comment]
Can you explain a bit more what you mean by "UWSGi reading from statsd"? You want UWSGI to publish using the statsd protocol?

Btw, I see that [uwsgi supports the graphite protocol](http://uwsgi-docs.readthedocs.io/en/latest/Carbon.html) for which we add support in #4734. Would that fill the need?

**Comment by lagrianitis** [comment]
Hello @tsg and thanks for your reply.
Let me elaborate a bit. The way we are currently retrieving uwsgi metrics is by using the stats server: http://uwsgi-docs.readthedocs.io/en/latest/StatsServer.html
which is part of UWSGi. Of course I am open in other suggestions as long as the results are the same. I believe both should be supported for more flexibility though

**Comment by tsg** [comment]
@lagrianitis From what I understand the StatsServer opens an HTTP server that offers the metrics over JSON, right? This seems like a perfect match for the [http module](https://www.elastic.co/guide/en/beats/metricbeat/6.0/metricbeat-module-http.html) which you can find in 6.0.0-alpha2.

**Comment by lagrianitis** [comment]
Hello @tsg, It actually opens a socket. We run a uwsgi application with stats server like this:

`uwsgi --http :9090 --wsgi-file foobar.py --stats /tmp/foobar-stats.sock`

We currently have some monitoring with Zabbix by reading the sock file (which is exposing json information indeed)

I was actually checking https://github.com/mrkschan/uwsgibeat which is very similar of what I want to achieve but without having to install another agent in the server, as I'm already using metricbeat's system and nginx modules.

**Comment by tsg** [comment]
I see, we'd be welcoming a uwsgi module in Metricbeat, if you or @mrkschan want to contirbute the equivalent of the uwsgibeat :)

I'll also add it to an internal wish list.

**Comment by lagrianitis** [comment]
@tsg Thanks alot. I'd love to contribute but I am an absolutely amateur with golang. I've created an issue in @mrkschan repo though.
I am more than happy to help with testing though

**Comment by fearful-symmetry** [comment]
We now have UWSGI: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-uwsgi.html

Closing this.
