### ISSUE TITLE
Unable to specify Docker host on Windows using named pipes

### ISSUE THREAD

**Issue by godefroi** [elastic/beats#4748]
I'm using Metricbeat 5.4.2 on Windows Server 2016. I have configured the Docker module as so:

    - module: docker
      metricsets:
        - container
      hosts: ["npipe://./pipe/docker_engine"]
      enabled: true
      period: 30s

This configuration passes `metricbeat -configtest`, but it doesn't actually work. The error message reported in Elasticsearch is this:

    Get http://unix.sock/containers/json?: open /pipe/docker_engine: The system cannot find the path specified.

If I use `npipe:////./pipe/docker_engine` as the host (which matches what I use for Registrator), `metricbeat -configtest` complains:

    PS C:\Program Files\Metricbeat> .\metricbeat.exe -configtest
    Exiting: 1 error: host parsing failed for docker-container: error parsing URL: empty host

**Comment by godefroi** [comment]
It looks to me like the Docker module is using fsouza's go-dockerclient, which is the same client used by Registrator. As Registrator works correctly, this looks to me like it is simply an issue in URI validation. Maybe  all that is needed is a special case in ParseURL (beats/metricbeat/mb/parse/url.go) where if the URI starts with npipe:// it just returns the raw string?

**Comment by exekias** [comment]
I've opened https://github.com/elastic/beats/pull/4751, do you have any way to build and test that branch? Unfortunately, I don't have a Windows scenario to test this fix :innocent:

**Comment by godefroi** [comment]
Hm; I built Registrator, it's possible I could work out how to build Metricbeat. Note that it would probably be more correct to use `npipe:////./pipe/docker_engine` in your tests because that's the URI that go-dockerclient is going to require.

**Comment by godefroi** [comment]
I put my comments in the PR. I don't know if my simple test is enough to get your PR merged, but it LGTM.

**Comment by exekias** [comment]
Thanks for the report @godefroi, this fix should make it to next release! (6.0)
