### ISSUE TITLE
Unable to stop test suite/coverage during Make process

### ISSUE THREAD

**Issue by xrl** [elastic/beats#4750]
I am unable to just build libbeat/filebeats from source. It always runs the test coverage, test suite, and tries to use docker-compose. This should easier to disable and/or documented.

- Version: master
- Operating sytem: alpine linux
- Steps to reproduce:

Use this Dockerfile:

```
FROM golang:1.8.3-alpine

RUN apk add --update bash git make gcc musl-dev python p2-pip libpcap libpcap-dev
RUN mkdir -p ${GOPATH}/src/github.com/elastic && \
	cd ${GOPATH}/src/github.com/elastic && \
	git clone --depth=1 https://github.com/elastic/beats.git \
	pip install virtualenv
```

Then hop in to the docker container:

```
$ docker run --rm -it that-image bash
$ cd /go/src/github.com/elastic/beats/filebeat
$ make SYSTEM_TESTS=false TEST_ENVIRONMENT=false
... LOTS OF OUTPUT
.... Runs testify (takes forever)
$ 
```

What environment variables do I need to set to skip straight to building the filebeats executable?

**Comment by exekias** [comment]
just try `make filebeat`
