### ISSUE TITLE
Use ProgramData for Windows service logs

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#4764]
The logs for Beats that are running as Windows services are currently written to `C:\Program Files\[beatname]\logs` (or the extract path which is `path.home`). Our Getting Started guides say that the logs go to `C:\ProgramData\[beatname]\Logs`.

I think we should move the logs to `C:\ProgramData\[beatname]` which is also where we store the registry files and metadata.

**Comment by tsg** [comment]
I think this can be closed.
