### ISSUE TITLE
Support tailing custom log file paths inside docker containers 

### ISSUE THREAD

**Issue by vjsamuel** [elastic/beats#4766]
Today we are able to use filebeat to tail logs that are being written to a json log file using Docker's json-logging driver. The logs of the application that are written into `stdout`/`stderr` are listened to by filebeat by configuring a prospector to point to `/var/lib/docker/containers/*/*.log`. this works fine when an application only writes to `stdout`/`stderr`.

Take tomcat as an example, `catalina.out` logs are written to `stdout` but access logs and startup logs are just files inside of the container. 

Other problems with relying on data coming from stdout is that if two different kinds of logs are being written into stdout then we have no context as to which file the log line is coming from and configs like multiline can not be generic enough to accept any kind of logs being generated.

Hence a mechanism is required to be able to tail logs from inside of the containers by filebeat.

**Comment by jstoja** [comment]
hello @vjsamuel the advised method to handle that is simply to either:
* mount the logfile on the host with docker and add a prospector to read it (for example mount your catalina.out to some /var/log/catalina.log and process it with filebeat). Docker containers have a "separate" part of the FS so filebeat won't be able to access it if not shared in some way.
* Tail from inside your container every logfile you care about and parse them using logstash.

Filebeat cannot (and shouldn't) cross containers boundaries for obvious security reasons.

**Comment by ph** [comment]
@vjsamuel I am closing this issue because I think this is now resolved. Feel free to reopen it.
