### ISSUE TITLE
Use regex to select dashboards to export

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#4774]
We could use the saved_objects API to list the dashboards, match against the names, then use the export API to get the matching dashboards and their deps.

```
$ curl -s "http://localhost:5601/api/saved_objects/dashboard?per_page=10000" | jq '.saved_objects[] | {title: .attributes.title, id: .id}'
{
  "title": "My Dashboard",
  "id": "c9dea300-72f3-11e7-bb5f-6bf23f27ae74"
}
{
  "title": "My Dashboard Copy",
  "id": "371c43d0-72f6-11e7-bb5f-6bf23f27ae74"
}
```

**Comment by pemontto** [comment]
Have you tried using the search and search_fields params? I'm pretty sure it passes it directly through ES so you can use wildcards too.

```
curl "http://localhost:5601/api/saved_objects/dashboard?search=Copy&fields=title&search_fields=_id&per_page=10000"
```

**Comment by monicasarbu** [comment]
I thought about this solution to make it easier to export dashboards. In the end, I have created a yml file that describes the dashboards that are associated with a Beat. This way, we make sure that we are exporting the right dashboards, without relying on the title. 

Here is an example of [module.yml](https://github.com/elastic/beats/blob/master/filebeat/module/nginx/module.yml) file available in the nginx module of Filebeat.

Here is an example of [dashboards.yml](https://github.com/elastic/beats/blob/master/packetbeat/dashboards.yml) file available for Packetbeat.

With this yml file, you specify what dashboards to export for each Beat/module:
```
cd metricbeat/module/system
go run ../../../dev-tools/cmd/dashboards/export_dashboards.go -yml module.yml
```
