### ISSUE TITLE
Command line -E flag can't overwrite module settings

### ISSUE THREAD

**Issue by tsg** [elastic/beats#4780]
Version: 6.0.0-beta1

The beats-tester runs metricbeat with the following command line on macOS:

```
sudo ./metricbeat -e -E output.elasticsearch.enabled=false -E output.file.path=/tmp/output -E "metricbeat.modules.0.period=1s"
```

This doesn't seem to work with the new `modules.d` configuration layout. It results in the following error:

```
2017/07/28 09:35:33.097278 beat.go:656: CRIT Exiting: 1 error: missing required field accessing 'metricbeat.modules.0.module' (source:'command line flag')
```

Removing the `-E "metricbeat.modules.0.period=1s"` makes it work.

Not sure if we can do anything about it, but the fact that the `-E` flag can no longer set modules settings feels like a regression.

**Comment by urso** [comment]
The behavior with modules.d somewhat makes sense.

Configuring modules in the global metricbeat.yml file gets you one array only. Using the index in the name gives you access to a particular configuration. We only merge flags globally.

When loading modules via modules.d, then each config file in modules.d has it's own list. That is, each enabled module has a `metricbeat.modules.0.period` setting. By introducing modules.d we can not directly address a particular modules settings anymore via CLI, as there is no unique setting/path anymore.

@tsg I'm in favor of closing this. WDYT?

**Comment by tsg** [comment]
I'm ok with closing, given that we didn't receive complaints about this since 6.0.
