### ISSUE TITLE
Default dashboard "Metricbeat host overview" filters for hostname "mar.local".

### ISSUE THREAD

**Issue by jarpy** [elastic/beats#4789]
I think this filter may have slipped into the dashboard accidentally.

https://github.com/elastic/beats/blob/1fa64ba847aa03791a8831995793e55a6861de06/metricbeat/module/system/_meta/kibana/default/dashboard/Metricbeat-host-overview.json#L353

**Comment by tsg** [comment]
Yeah, I noticed it as well, we'll fix it. Thanks for the report!

cc @monicasarbu

**Comment by tsg** [comment]
Fixed in the meantime.
