### ISSUE TITLE
Add limited support for SSL monitoring

### ISSUE THREAD

**Issue by sammcj** [elastic/beats#48]
```
/usr/bin/packetbeat[1812]: pgsql.go:275: Postgresql Message too short. 53 (length=1). Wait for more.
```

Relates to #46 - except I don't want to disable SSL on our database servers!
Is there any way we can still use packetbeat to see flows with PostgreSQL and SSL?

**Comment by strootman** [comment]
Is this gonna make it into v5.0.0?

**Comment by monicasarbu** [comment]
@strootman Just to clarify here, for 5.1 we are targeting to extract more information from the SSL envelope. We are not planning to do any decryption yet.

**Comment by strootman** [comment]
@monicasarbu Thank you for the clarification!

**Comment by PinXo** [comment]
@monicasarbu any advance? has it been replanned/rejected/delayed/forgotten?
At the moment i'm using ssldump to capture https traffic and certificates and it would be a great feature for packetbeat.

**Comment by monicasarbu** [comment]
@PinXo Packetbeat has already support for [flows](https://github.com/elastic/beats/issues/670). Please see more [details](https://www.elastic.co/guide/en/beats/packetbeat/5.2/configuration-flows.html) in our documentation about how to configure it.

**Comment by monicasarbu** [comment]
Closing this as flows were added in https://github.com/elastic/beats/pull/756

**Comment by monicasarbu** [comment]
More enhancements for flows can be found [here](https://github.com/elastic/beats/issues/3444).

**Comment by monicasarbu** [comment]
Other enhancements related: https://github.com/elastic/beats/issues/3604, https://github.com/elastic/beats/issues/3605
