### ISSUE TITLE
Unable to install nightly build on Debian: 'Version' field string 'nightly151208141331': version number does not start with digit

### ISSUE THREAD

**Issue by marnovdm** [elastic/beats#481]
dpkg -i filebeat_nightly.latest_amd64.deb 
dpkg: error processing archive filebeat_nightly.latest_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'filebeat':
 error in 'Version' field string 'nightly151208141331': version number does not start with digit
Errors were encountered while processing:
 filebeat_nightly.latest_amd64.deb

Trying to install on Debian 8 64 bit VM. The stable release can be installed, but I would like to test some of the resolved issues in the latest nightly build.

EDIT: Got the filebeat nightlies from here: https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/

**Comment by ruflin** [comment]
@marnovdm Can you try to install the most recent nightly with a timestamp instead of the one with the latest name? They are identical.

**Comment by marnovdm** [comment]
Thanks for the quick reply. Unfortunately that doesn't seem to make a difference;

dpkg -i filebeat_nightly.151208141331_amd64.deb 
dpkg: error processing archive filebeat_nightly.151208141331_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'filebeat':
 error in 'Version' field string 'nightly151208141331': version number does not start with digit
Errors were encountered while processing:
 filebeat_nightly.151208141331_amd64.deb

Also, for Salt Stack install integration, a static URL with 'latest' instead of a timestamp would be preferred so we can always track the latest changes in our development environment. Thanks!

**Comment by ruflin** [comment]
We introduced latest for the same reason on our side, mainly for testing. Unfortunately we also hit the version number issue with the deb packages you describe above. The packaging scripts can be found in this repository: https://github.com/elastic/beats-packer Do you mind moving the issue there?

I'm not sure if we could solve the problem by making it `beatname_timestamp.nightly_...` I remember playing around with it and then hitting some other issues, but don't remember exactly what it was.

**Comment by marnovdm** [comment]
Thanks for the explanation. I'm not a packaging guru, but literally interpreting the error message "error in 'Version' field string 'nightly151208141331': version number does not start with digit" would suggest a version of "1nightly151208141331" or even just the timestamp "151208141331" could work...

I've also created https://github.com/elastic/beats-packer/issues/40 as per your request. I assume the issue in this repo can be closed now?

**Comment by ruflin** [comment]
Yes, that would solve it, but not sure if it had some other side affects. Our normal releases have that: `filebeat-1.0.0-...`. I will close this issue. Also feel free to open a PR in beats-packer for a potential change.
