### ISSUE TITLE
Filebeat 5.5.1-1 not processing auditd events via auditd module

### ISSUE THREAD

**Issue by bartdenotte** [elastic/beats#4816]
- Version: Filebeat 5.5.1-1
- Operating System: Centos 7
- Steps to Reproduce: 

Filebeat picks up new auditd events from /var/log/audit/audit.log and tries to send them directly to elasticsearch.

I see the event in the filebeat log file (in debug mode)

2017-08-02T11:47:55+02:00 DBG  Publish: {
  "@timestamp": "2017-08-02T09:47:53.775Z",
  "beat": {
    "hostname": "infra-host.int",
    "name": "infra-host.int",
    "version": "5.5.1"
  },
  "input_type": "log",
  "message": "node=infra-host.int type=PATH msg=audit(1501667273.322:97023): item=1 name=\"/lib64/ld-linux-x86-64.so.2\" inode=2149390606 dev=08:03 mode=0100755 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:ld_so_t:s0 objtype=NORMAL",
  "offset": 4619936,
  "source": "/var/log/audit/audit.log",
  "type": "log"
}

Then following message occurs in the filebeat log

2017-08-02T11:47:55+02:00 WARN Can not index event (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse [error]","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:662"}}

This happens for all auditd events.

Best regards

**Comment by feiyuw** [comment]
I met the same issue. I wrote a custom filebeat module to publish log to elasticsearch directly.
* Filebeat Version: 5.6.3
* OS version: CentOS 7.3
* Log:

```
2017/10/25 13:07:55.807050 client.go:214: DBG  Publish: {
  "@timestamp": "2017-10-25T13:07:51.559Z",
  "beat": {
    "hostname": "anode-1.prismcdn.internal",
    "name": "anode-1.prismcdn.internal",
    "version": "5.6.3"
  },
  "fileset": {
    "module": "prismcdn",
    "name": "xnode"
  },
  "input_type": "log",
  "message": "[2017-10-25T13:07:43.050Z][D]\u003cdetect\u003e recv forwarding flag:c1,101.28.57.239:48910 flag:c1,101.28.57.239:48910 to 101.28.57.239:48910 ",
  "offset": 89429034,
  "source": "/opt/prismcdn/anode-srv/access.log",
  "type": "log"
}
2017/10/25 13:07:55.842918 client.go:447: WARN Can not index event (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse [error]","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:394"}}
```

The log is like "[2017-10-25T13:07:43.050Z][D]<detect> recv forwarding flag:c1,101.28.57.239:48910 flag:c1,101.28.57.239:48910 to 101.28.57.239:48910", and the ingest/pipeline.json is like below:

```
{
    "description": "Pipeline for parsing  xnode logs",
    "processors": [{
            "grok": {
                    "field": "message",
                    "patterns": [
                            "\\[%{DATA:prismcdn.xnode.time}\\]\\[%{DATA:prismcdn.xnode.level}\\]<%{DATA:prismcdn.xnode.type}> %{GREEDYDATA:prismcdn.xnode.message}"
                            ],
                    "ignore_missing": true
            }
    }, {
            "remove": {
                    "field": "message"
            }
    }],
    "on_failure" : [{
            "set" : {
                    "field" : "error.message",
                    "value" : "{{ _ingest.on_failure_message }}"
            }
    }]
}
```

Thanks!

**Comment by urso** [comment]
Closing, due to age and the `error` namespace being better defined thanks to ECS. If problem persists with filebeat 7.x, feel free to reopen.
