### ISSUE TITLE
Beats users permissions for the default modules using ingest pipelines

### ISSUE THREAD

**Issue by astefan** [elastic/beats#4826]
In the documentation the permissions needed for a Beats user are ok for a setup that doesn't use one of the default modules.

But, if I configure the use of the `system` module in Filebeat for example, the user that I need to create does require `manage_pipeline` permission, because the modules do have pre-defined ingest pipelines that are added to Elasticsearch. In a configuration where Filebeat sends the events directly to ES, of course.

**Comment by andrewkroh** [comment]
In the docs we should also make sure we account for the permissions for installing ML jobs (6.x) and Kibana dashboads/index patterns.

**Comment by willemdh** [comment]
Fyi it's the `manage_ingest_pipelines` cluster privilege that is required.
