### ISSUE TITLE
Filebeat JSON input parsing errors on special fields

### ISSUE THREAD

**Issue by urso** [elastic/beats#4836]
When parsing json, the `@timestamp` field is tried to be parsed. The supported format is currently very strict, giving errors if `@timestamp` field is used.

error message: ` JSON: Won't overwrite @timestamp because of parsing error: parsing time "2017-05-12T18:58:42+0000" as "2006-01-02T15:04:05Z07:00": cannot parse "+0000" as "Z07:00"`.

For timestamps and other special fields treated somewhat special options to adapt the behaviour would help in reducing errors when parsing JSON. For example:
- Rename to another field. Always or on error only
- Configurable timestamp format

**Comment by 2knarf** [comment]
Any update on this? Having the same issue.
