### ISSUE TITLE
Travis errors on chmod command after generating new Beat

### ISSUE THREAD

**Issue by makkes** [elastic/beats#4837]
I’ve just created a new Beat using the documentation from https://www.elastic.co/guide/en/beats/libbeat/current/new-beat.html. However, the generated `.travis.yml` file causes Travis to fail:

![aa2b44b97707e900355cb9a81d248abe3400a6db](https://user-images.githubusercontent.com/387444/29027132-98d35e74-7b7f-11e7-9868-5ce588682607.png)

The `chmod` call is conducted on a non-existing directory. Simply removing the line containing the `chmod` command resolves the error.

**Comment by ruflin** [comment]
I think this line here is a left over and should be removed: https://github.com/elastic/beats/blob/master/generator/beat/%7Bbeat%7D/.travis.yml#L31
