### ISSUE TITLE
Document beats startup and dashboard setup when auth is needed

### ISSUE THREAD

**Issue by tbragin** [elastic/beats#4839]
At the moment, beats documentation does not explicitly show you how to start the beat (and use the "setup" dashboards option) when auth is in place (e.g. when using X-Pack or Elastic Cloud). We should consider adding those instructions explicitly, because otherwise user has to realize that -E options have to be used, which is not easy to figure out from the docs or using the -h flag. 

Example metricbeat setup command: `./metricbeat setup -e -E output.elasticsearch.username=elastic -E output.elasticsearch.password=elastic -E setup.kibana.username=elastic -E setup.kibana.password=elastic`

@skearns64 @tsg @monicasarbu @brandonmensing

**Comment by tsg** [comment]
I think this was solved by the linked PR.
