### ISSUE TITLE
Heartbeat @timestamp value is wrong

### ISSUE THREAD

**Issue by pmusa** [elastic/beats#4851]
- Version: 6.0.0-beta1-linux-x86_64
- Operating System: Ubuntu 16.04
- Steps to Reproduce: 
Start heartbeat with the default configuration and check that the `@timestamp` value generated is always the same for every new event that is generated. (I imagine it is using the wrong timestamp variable to set it.)

**Comment by michaelgoconnor** [comment]
This issue is also reproducible on Windows
