### ISSUE TITLE
Eliminate deprecation warnings on scripts

### ISSUE THREAD

**Issue by kvch** [elastic/beats#4865]
Deprecation warnings show up in logs of ES 6.x:
```
[2017-08-10T11:00:54,152][WARN ][o.e.d.i.c.ScriptProcessor$Factory] Specifying script sourcewith [inline] is deprecated, use [source] instead.
```

The format of scripts in ingest data should follow the docs: https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-using.html

**Comment by ruflin** [comment]
@kvch I assume this problem will be solved with https://github.com/elastic/beats/pull/5339

I removed `bug` label as I think the feature works as expected and it only throws a deprecation warning. This doesn't mean we should not change it.

**Comment by urso** [comment]
@kvch Any update on this?

**Comment by kvch** [comment]
Nothing, but I added good first issue.
