### ISSUE TITLE
Add process blacklist to Metricbeat system module.

### ISSUE THREAD

**Issue by robelastic** [elastic/beats#4882]
Currently Metricbeat provides a whitelist for processes to be monitored. While this helps reduce the number of unnecessary processes for which Metricbeat will send data, it may cause one to miss important processes that the user was unaware of, especially if those processes are transient in nature and not always running (so not always visible using ps command for example).

Instead of specifically adding processes to a whitelist, a blacklist would allow users to easily ignore processes that they know they don't want to collect data on. Due to the varying hardware/VM that metricbeat may be running on, the blacklist should accept wildcards or even full regular expressions to match process names.

Consider this list of 90 processes from a CentOS Linux system...

```
agetty
ata_sff
auditd
bioset
crond
crypto
dbus-daemon
deferwq
fsnotify_mark
ipv6_addrconf
irqbalance
kauditd
kblockd
kdevtmpfs
khugepaged
khungtaskd
kintegrityd
kmpath_rdacd
kpsmoused
ksmd
ksoftirqd/0
ksoftirqd/1
kswapd0
kthreadd
kthrotld
kworker/0:0
kworker/0:0H
kworker/0:1
kworker/0:1H
kworker/0:2
kworker/1:0
kworker/1:0H
kworker/1:1H
kworker/1:2
kworker/u4:0
kworker/u4:2
master
md
metricbeat
migration/0
migration/1
mpt/0
mpt_poll_0
mysqld
mysqld_safe
netns
NetworkManager
nfit
ntpd
packetbeat
pickup
polkitd
qmgr
rcu_bh
rcu_sched
rsyslogd
scsi_eh_0
scsi_eh_1
scsi_eh_2
scsi_tmf_0
scsi_tmf_1
scsi_tmf_2
snmpd
sshd
systemd
systemd-journal
systemd-logind
systemd-udevd
ttm_swap
tuned
vmtoolsd
watchdog/0
watchdog/1
writeback
xfs-buf/sda1
xfs-buf/sda3
xfs-cil/sda1
xfs-cil/sda3
xfs-conv/sda1
xfs-conv/sda3
xfs-data/sda1
xfs-data/sda3
xfs-eofblocks/s
xfs-log/sda1
xfs-log/sda3
xfs-reclaim/sda
xfs_mru_cache
xfsaild/sda1
xfsaild/sda3
xfsalloc
```
The blacklist should allow something like...

`process.blacklist: [ "k*", "migration*", "mpt*", "rcu_*", "scsi_*", "systemd*", "watchdog*", "xfs*" ]`

The list of monitored processes would be reduced to only 31 process...

```
agetty
ata_sff
auditd
bioset
crond
crypto
dbus-daemon
deferwq
fsnotify_mark
ipv6_addrconf
irqbalance
master
md
metricbeat
mysqld
mysqld_safe
netns
NetworkManager
nfit
ntpd
packetbeat
pickup
polkitd
qmgr
rsyslogd
snmpd
sshd
ttm_swap
tuned
vmtoolsd
writeback
```
Such a config would reduce the amount data collected and stored, but also be more portable between systems as it wouldn't be necessary to first inventory important processes prior to setting up a whitelist.

This would also allow users to start with a blacklist, and after they better understand the other processes running on the system they will be able to define a more well informed whitelist.

**Comment by praseodym** [comment]
Your process list contains a lot of kernel processes that would be more easily filtered out by excluding any processes with PPID 2. For example, with ps, try [`ps --ppid 2 -p 2 --deselect`](https://unix.stackexchange.com/questions/78583/can-ps-display-only-non-kernel-processes-on-linux). This is less fragile than name blacklisting (especially blacklisting something like `"k*"`)

**Comment by tsg** [comment]
+1 on the general feature, as it would resemble the `include_lines` / `exclude_lines` options we have in Filebeat. However, I think this could be done today with a processor, like we do for the filesystems [here](https://github.com/elastic/beats/blob/master/metricbeat/modules.d/system.yml#L23-L25).

**Comment by jruzicka** [comment]
Yes - looks like you can use drop_event to make this work.  This worked to exclude all svchost.exe processes running in Windows.

processors:
  - drop_event:
      when:
        or: 
          - equals:
              system.process.name: svchost.exe

**Comment by london2016** [comment]
But processors still process the processes that you do not want to process. I have a process that I am not interested in which also happens to not hold a valid command line string causing Metricbeat to throw an error every x seconds. Using Processors to strip out unwanted processes is just wasted resource, you should be able to just tell Metricbeat to ignore it in the first place.
