### ISSUE TITLE
supply system.cpu.total.pct

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/beats#4898]
Although it can be calculated in the pipeline, it would be very convenient to have a `system.cpu.total.pct` and `system.cpu.total.norm.pct` field supplied automatically, as this is a common requirement.

**Comment by tsg** [comment]
+1 for this feature, I think we should do it especially because we provide a total per process.

**Comment by ctindel** [comment]
Definitely, even if it's just automatically creating a script field for the normalized percentage because we need this to be able to do CPU threshold alerts with the new threshold alerting UI.
