### ISSUE TITLE
Add support for script fields in fields.yml

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#4899]
Some dashboards in Kibana require script fields. As `fields.yml` currently does not support script fields and the index pattern is generated from `fields.yml`, these dashboards do not work. Either the `fields.yml` should support to define script fields or we should find an other automated way on how to load them.

The advantage of using `fields.yml` is that then these fields could potentially also shown in the docs or used in other places.

An example script fields looks as following after exporting:

In the `fields` string in the index pattern:
```
{
	"name": "error id icon",
	"type": "string",
	"count": 0,
	"scripted": true,
	"script": "doc['error.checksum'].value",
	"lang": "painless",
	"searchable": true,
	"aggregatable": true,
	"readFromDocValues": false
}
```

Under `fieldFormatMap` in the index pattern:

```
"error id icon":{  
   "id":"url",
   "params":{  
      "labelTemplate":"-"
   }
}
```

**Comment by monicasarbu** [comment]
That's a great addition to the `fields.yml`. I suggest to use the field name as in Kibana, so `language` instead of `lang`. This should support to add a `type` and a `format` for the scripted fields.

**Comment by ruflin** [comment]
I suggest in the config options to `skip` the language part and only support `painless`. It seems I even missed part for the data that has to be generated as in Kibana there are also options like `Url Template` which should be taken into account.

**Comment by simitt** [comment]
Scripted fields are generally supported now. Additional attributes can be added as they are needed, so I suggest to close this issue.
