### ISSUE TITLE
Add support for PKI auth in Kubernetes module

### ISSUE THREAD

**Issue by trondhindenes** [elastic/beats#4914]
Kubernetes pods can interact with the kubernetes api given that they're authenticated. The (imho) best way to set up this, is to create a ServiceAccount, which will then inject a client cert into the pod, at the path "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt". A pod can then issue requests against the kubernetes api simply using a request like:
curl -v --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes/

It would be great if the Kubernetes module in Metricbeats supported this, as it would allow us to set up completely self-contained systems without having to rely on kubectl-proxy sidecar containers.

**Comment by exekias** [comment]
That may be possible already if you put the token in an env var, would that be possible?

We support TLS + header settings in all HTTP based modules, check https://github.com/elastic/beats/issues/4268 for more details, as this feature is still undocumented.

**Comment by exekias** [comment]
I'm keeping this issue in any case, as it would be nice to support this as a first class citizen, like we do in `add_kubernetes_metadata` processor with the `in_cluster` setting

**Comment by trondhindenes** [comment]
Could be that it's just missing a bit of documentation. I can certainly test the envvar option. Will report back with findings.

**Comment by trondhindenes** [comment]
Um, looked at the referenced issue now. I can't find any clear info in what the available environment vars are. I'm aware that I can "template in" environment variables into filebeat.yml using the ${VAR} pattern, but I got the impression from this thread that there are some "first-class" envvars that don't require templating filebeat.yml? If so, I fail to find any reference to them.
