### ISSUE TITLE
Not all fields are present when importing the index-pattern to Kibana 5.6

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#4920]
Steps to reproduce:
- start Elasticsearch and Kibana 5.6
- load Metricbeat dashboards to Kibana 5.6, including the rabbitmq ones available under https://github.com/elastic/beats/pull/4912
- Check in Kibana->Management->Index pattern that the fields starting with `rabbitmq` are missing from the `metricbeat-*` index-pattern.

cc-ed @simianhacker

**Comment by tsg** [comment]
@monicasarbu I can't reproduce this with either rc1 and beta1, I tried from linux and mac. Not sure what could have been wrong in your run.

**Comment by ruflin** [comment]
@tsg @monicasarbu Should we close this one?

**Comment by urso** [comment]
No update for 1+ year, plus not reproduced so far.
