### ISSUE TITLE
How to access overall configuration from plugin initializer?

### ISSUE THREAD

**Issue by mcandre** [elastic/beats#4922]
The current API appears to pass only the `output.<plugin>` section of the filebeat configuration to filebeat initializer functions. Is there another way for a plugin to access the larger configuration during setup?

**Comment by andrewkroh** [comment]
It's not possible AFAIK. I'm curious why the plugin needs access to config data outside of it's namespace.

The underlying `common.Config` value is a wrapped `ucfg.Config`. Perhaps it's possible to cast it and use this [Parent()](https://godoc.org/github.com/elastic/go-ucfg#Config.Parent) method.

In any case it would be best follow up using the [Beats Developer forum](https://discuss.elastic.co/c/beats/libbeat).
