### ISSUE TITLE
Metricbeat with Jolokia metricset gives "Cannot unmarshal json response: invalid character '\\x00' looking for beginning of value"

### ISSUE THREAD

**Issue by yhf597869822** [elastic/beats#4934]
Version: 5.5.1
Operating System: Centos 7
Steps to Reproduce:
        Configure some JMX metrics
        Wait a couple of seconds
        All JMX events fail with error "Cannot unmarshal json response: invalid character '\\x00' looking for beginning of value"
        Restart metricbeat service and everything works again
my configuration as follows:
`metricbeat.modules:

- module: jolokia
  metricsets: ["jmx"]
  enabled: true
  period: 2s
  namespace: "jolokia_metrics"
  hosts: ["localhost:7089"]
  jmx.mappings:
    - mbean: 'java.lang:type=Runtime'
      attributes:
        - attr: Uptime
          field: uptime
    - mbean: 'java.lang:type=GarbageCollector,name=ConcurrentMarkSweep'
      attributes:
        - attr: CollectionTime
          field: gc.cms_collection_time
        - attr: CollectionCount
          field: gc.cms_collection_count
    - mbean: 'java.lang:type=Memory'
      attributes:
        - attr: HeapMemoryUsage
          field: memory.heap_usage
        - attr: NonHeapMemoryUsage
          field: memory.non_heap_usage
output.file:
  path: "/tmp/metricbeat"
  filename: metricbeat`

**Comment by ruflin** [comment]
Do you get any events that work? Reminds me off https://discuss.elastic.co/t/metricbeat-jolokia-module-cannot-unmarshal-json-response/89744

Could you please post this on discuss (https://discuss.elastic.co/c/beats/metricbeat) as we like to keep Github for confirmed bugs? Closing this one.

**Comment by yhf597869822** [comment]
@ruflin Thanks a lot!
