### ISSUE TITLE
AIX install beats

### ISSUE THREAD

**Issue by fenggnay** [elastic/beats#4946]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version: 
- Operating System: 
- Steps to Reproduce:

**Comment by andrewkroh** [comment]
If you have a question please use https://discuss.elastic.co/c/beats.
