### ISSUE TITLE
RDS monitoring 

### ISSUE THREAD

**Issue by hiteshmahajan** [elastic/beats#498]
Packetbeat does not support RDS monitoring can we have this feature in future

**Comment by urso** [comment]
Can you add some more details? You talking about protocol or Amazon RDS? If later onw, you want to monitor the REST API calls or your database instance?

**Comment by monicasarbu** [comment]
It looks like RDS-MySQL is working for some of our users if the encryption is set to off. Please let us know what exactly you are using, RDS-MySQL, RDS-PostgresSQL or something else. Is encryption off or on?

**Comment by hiteshmahajan** [comment]
@urso yes we need to monitor the API calls on our database instance & need to get query log.

@monicasarbu we are using RDS-MySQL and encryption is off.

**Comment by monicasarbu** [comment]
@hiteshmahajan It should work you. It's enough if Packetbeat gets the traffic from the client side or from the server side. Please let us know if it works for you.

**Comment by lifeofguenter** [comment]
I installed packetbeat on the same instance as Laravel, and it does not seem to log MySQL (RDS) queries - other queries by the Laravel application work (memcache & redis).
