### ISSUE TITLE
Discard packets issued by load balancer

### ISSUE THREAD

**Issue by bqk-** [elastic/beats#499]
Hello,

I am using PacketBeats to monitor the traffic on our application, I use the "RealIp" feature since it is situated behind a load balancer.
However, the load balancer issues a request every second pretty much to ping the servers.

Could an option like "Ignore packets without real ip" or "blacklist ips" be useful ?

**Comment by ruflin** [comment]
We are working on a filtering concept which can be found here: https://github.com/elastic/beats/issues/462 This could help with this.

**Comment by bqk-** [comment]
Great news, thanks!

**Comment by tsg** [comment]
Closing as duplicate of #462.
