### ISSUE TITLE
If packetbeat can show the ratio of packet loss

### ISSUE THREAD

**Issue by nobleXu** [elastic/beats#5029]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version: Packetbeat-5.5.1
- Operating System: Centos7
- Steps to Reproduce: 
I can't find the function to get the packet loss rate which is very important to me.

**Comment by andrewkroh** [comment]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.
