### ISSUE TITLE
Include selector name in debug output

### ISSUE THREAD

**Issue by roncohen** [elastic/beats#5042]
It would be useful if the debug output included the selector name so you the selector for each log line and you can more easily update your `-d` filter to include/exclude them:

This:
```
2017/08/29 09:13:28.898295 server.go:85: DBG Request: URI=/v1/errors, method=POST, content-length=156
```
would be
```
2017/08/29 09:13:28.898295 server.go:85: DBG handler Request: URI=/v1/errors, method=POST, content-length=156
```

if the call was
```
logp.Debug("handler", "Request...")
```

Potential alternatives are:
```
2017/08/29 09:13:28.898295 server.go:85: DBG/handler Request: URI=/v1/errors, method=POST, content-length=156
```

```
2017/08/29 09:13:28.898295 server.go:85: DBG:handler Request: URI=/v1/errors, method=POST, content-length=156
```

**Comment by exekias** [comment]
+1, linked it with https://github.com/elastic/beats/issues/5000

**Comment by andrewkroh** [comment]
How about `DBG [selector]`? I've [been using](https://github.com/elastic/beats/blob/5261079122227eee53b74a2d86cbe59eeeaa12d3/auditbeat/module/audit/kernel/audit_linux.go#L25) this in Auditbeat (and I think in a few places in Metricbeat).

`2017/08/29 09:13:28.898295 server.go:85: DBG [handler] Request: URI=/v1/errors, method=POST, content-length=156`

**Comment by roncohen** [comment]
@andrewkroh I like that 👍
