### ISSUE TITLE
`load` is not being populated on Windows Server

### ISSUE THREAD

**Issue by kamranayub** [elastic/beats#505]
I have topbeats 1.0 installed and running on a test server (Windows Server 2012 R2). It's running as a service and as Local System. I have it shipping data to a file (period: 10s, system, process, etc.) and then using nxLog to ship that to Elastic (we couldn't get it shipping directly, but we're working on it).

Anyway, here's the data I see coming back and notice how `load` fields are all returning 0 even during running a system benchmark with >95% CPU load.

![image](https://cloud.githubusercontent.com/assets/563819/11726029/4567be44-9f42-11e5-8dd0-381555b1fae6.png)

Any ideas? I also confirmed the output file on the server contains the same data, so it's being written to the filesystem with the same values.

**Comment by kamranayub** [comment]
Alright, it's probably because load isn't implemented for Windows.

https://github.com/elastic/gosigar/blob/master/sigar_windows.go

But `cpu.system_p` also is just 0 100% of the time. Is this on purpose?

**Comment by monicasarbu** [comment]
yes, `load` information is not available on Windows, only on Unix systems. `cpu.system_p` should not be zero in Kibana. Can you please tell me what is the value of the `cpu.system_p` printed in the Discovery page under JSON?

**Comment by kamranayub** [comment]
I updated my comment with a question about possible miscalculation. Here's what I see for CPU:

![image](https://cloud.githubusercontent.com/assets/563819/11727297/bf6729e0-9f48-11e5-826c-47848afea353.png)

It's always 0 for all the data written.

**Comment by monicasarbu** [comment]
<pre>
sy: system cpu time (or) % CPU time spent in kernel space
</pre>
This is the definition from the top command. In my opinion, I think it doesn't make sense to be the time spent in kernel space plus the time spent in user time. 

I checked the psutil code and other gosigar library and they are setting system = kernel - idle as well.

**Comment by monicasarbu** [comment]
Let me try to see how it's working for me.

**Comment by kamranayub** [comment]
Sure, whatever is appropriate is fine--I just need a way of seeing load on the machine, however it works since I'm not seeing anything that does on Windows at least.

**Comment by monicasarbu** [comment]
I think the 3% that you see in the Task Manager is `cpu.user_p` not `cpu.system_p`. Would be possible to display cpu.user_p as well near cpu.system_p? Thanks!

**Comment by kamranayub** [comment]
Here's the system under some load:

![image](https://cloud.githubusercontent.com/assets/563819/11728622/7d1664f4-9f50-11e5-99bd-2e4b1203359f.png)

And corresponding data I see in Kibana:

![image](https://cloud.githubusercontent.com/assets/563819/11728639/92a6a0f4-9f50-11e5-9696-637731e9d292.png)

At least a few of the values should have been higher than 0, if not all of them, with a 10s period.

**Comment by kamranayub** [comment]
I saw one data point that had a value of 1. It looks like it's either 0 or 1, never a value in-between. Rounding errors?

![image](https://cloud.githubusercontent.com/assets/563819/11728976/71b4dae4-9f52-11e5-82b6-842dca3d9653.png)

**Comment by kamranayub** [comment]
I'm still not convinced the calculation is correct. Yet another source has the same type of calculation going on but does `system = kernel + user` and later subtracts idle when generating the %.

http://stackoverflow.com/questions/7216645/c-sharp-system-cpu-usage-and-syncing-with-windows-task-manager

```
TimeSpan sysIdleTs = GetTimeSpanFromFileTime(sysIdle);
TimeSpan sysKernelTs = GetTimeSpanFromFileTime(sysKernel);
TimeSpan sysUserTs = GetTimeSpanFromFileTime(sysUser);

TimeSpan sysIdleDiffenceTs = sysIdleTs.Subtract(_sysIdleOldTs);
TimeSpan sysKernelDiffenceTs = sysKernelTs.Subtract(_sysKernelOldTs);
TimeSpan sysUserDiffenceTs = sysUserTs.Subtract(_sysUserOldTs);

_sysIdleOldTs = sysIdleTs;
_sysKernelOldTs = sysKernelTs;
_sysUserOldTs = sysUserTs;

TimeSpan system = sysKernelDiffenceTs.Add(sysUserDiffenceTs);

Double cpuUsage = (((system.Subtract(sysIdleDiffenceTs).TotalMilliseconds) * 100) / system.TotalMilliseconds);
```

I know kernel time contains both kernel and idle time [per MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724400(v=vs.85).aspx).

```
A pointer to a FILETIME structure that receives the amount of time that the system has spent executing in Kernel mode (including all threads in all processes, on all processors). This time value also includes the amount of time the system has been idle.
```

**Comment by monicasarbu** [comment]
I tested on my windows machine and I get the same thing as you:
<pre>

  "cpu": {
    "user": 89,
    "user_p": 0,
    "nice": 0,
    "system": 60,
    "system_p": 0,
    "idle": 3848,
    "iowait": 0,
    "irq": 0,
    "softirq": 0,
    "steal": 0
  },
</pre>

**Comment by monicasarbu** [comment]
I tested on my windows machines and it seems to work fine for me. I did a small test:
- start a [burn](https://github.com/elastic/beats/blob/master/topbeat/tests/burn.go) application written by us that raises the cpu usage to 100%
<pre>
GOMAXPROCS=4 go run burn.go -cpus 4
</pre>
- start Task Manager on Windows and check that cpu usage is 100%
- configure topbeat with the settings:
topbeat.yml
<pre>
input:
  # In seconds, defines how often to read server statistics
  period: 10

  # Regular expression to match the processes that are monitored
  # By default, all the processes are monitored
  procs: [".*"]

  # Statistics to collect (all enabled by default)
  stats:
    system: true
    proc: false
    filesystem: false
</pre>

- start topbeat in foreground
<pre>
topbeat.exe -c topbeat.yml -d "publish" -e
</pre>

- check if exports cpu.user_p: 0.95 (or close to 1), this means close to 100%

Please notice that the values that you get with Task Manager might be different with the ones reported by topbeat. That's normal. They might have a different way to calculate the cpu usage. Also, the calculations are done over different periods of time that make the big difference.

**Comment by kamranayub** [comment]
I'm not sure a 100% CPU test is an accurate test, as even with baseline CPU > 3-4% CPU (this is a server after all), I'm not seeing any useful data from topbeat (either 0 or 1). At this point, topbeat is not useful for us for operational insights--but it doesn't seem like this is intentional, since getting system CPU time should provide accurate data.

I will try to run my own tests with some modified calculations (in C# since I don't know Go but still using `GetSystemTimes` native code) and try to report back a comparison, with different periods so I can provide better details and understand what the issue is. Thanks for your help so far!

**Comment by monicasarbu** [comment]
@kamranayub I spent a day trying different calculations for cpu usage (including the one you proposing) and the result was the same. It might be that Task Manager has a different algorithm for calculating the cpu usage and this explains why we get different values. Please let me know if you discover something by running the C# implementations. I am happy to help you in finding a better solution.

**Comment by monicasarbu** [comment]
@kamranayub I did another interesting test. [psutil library](https://pypi.python.org/pypi/psutil) has a similar implementation as we have, so I checked the results returned by this library with the results returned by Task Manager and they look more or less the same on my windows machine if I didn't do any mistakes. 
Here are the commands that I entered in a python terminal to print 30 times the cpu usage in percentage:
<pre>
import psutil
for x in range(30):
     psutil.cpu_percent(interval=10)
</pre>

**Comment by monicasarbu** [comment]
@kamranayub Closing the issue as it's originally related to load on Windows, that is not available on Windows. If you have more questions, feel free to contact us on https://discuss.elastic.co/c/beats.

**Comment by kamranayub** [comment]
Thanks, we are seeing the data we expect, so everything's working nicely
now.
