### ISSUE TITLE
BurrowBeat Issue

### ISSUE THREAD

**Issue by taraldesai** [elastic/beats#5054]
Hi ,

Need help as I am trying to install burrow beat and getting below error

 make setup
/burrowbeat/src/github.com/elastic/beats/libbeat/scripts/Makefile:90: warning: overriding recipe for target `libbeat'
/burrowbeat/src/github.com/elastic/beats/libbeat/scripts/Makefile:86: warning: ignoring old recipe for target `libbeat'
make update
make[1]: Entering directory `/burrowbeat/github.com/goomzee/burrowbeat'
/burrowbeat/src/github.com/elastic/beats/libbeat/scripts/Makefile:90: warning: overriding recipe for target `libbeat'
/burrowbeat/src/github.com/elastic/beats/libbeat/scripts/Makefile:86: warning: ignoring old recipe for target `libbeat'
New python executable in /burrowbeat/github.com/goomzee/burrowbeat/build/python-env/bin/python
Installing setuptools, pip, wheel...done.
make[1]: *** No rule to make target `collect', needed by `update'.  Stop.
make[1]: Leaving directory `/burrowbeat/github.com/goomzee/burrowbeat'
make: *** [setup] Error 2

I have downloaded the current version of beats and burrowbeat.

**Comment by ruflin** [comment]
Closing this in favor of where I think this also belongs: https://github.com/Goomzee/burrowbeat/issues/5
