### ISSUE TITLE
 Packetbeat cannot running ?

### ISSUE THREAD

**Issue by stefansaye** [elastic/beats#5064]
Hi

Hi! Can u help me pls? Why is it not starting?  packetbeat is running with same configuration.

    govind :~ # /etc/init.d/packetbeat start
    /etc/init.d/packetbeat: line 35: /etc/rc.d/init.d/functions: No such file or directory
    /etc/init.d/packetbeat: line 39: status: command not found
    Starting packetbeat: 2017/08/31 05:21:07.173725 beat.go:285: INFO Home path: [/usr/share /packetbeat] Config path: [/etc/packetbeat] Data path: [/var/lib/packetbeat] Logs path: [/var/log/packetbeat]
    2017/08/31 05:21:07.173746 beat.go:186: INFO Setup Beat: packetbeat; Version: 5.5.2
    2017/08/31 05:21:07.173871 metrics.go:23: INFO Metrics logging every 30s
    2017/08/31 05:21:07.173941 output.go:258: INFO Loading template enabled. Reading template file:    /etc/packetbeat/packetbeat.template.json
    2017/08/31 05:21:07.174910 output.go:269: INFO Loading template enabled for Elasticsearch 2.x.  Reading template file: /etc/packetbeat/packetbeat.template-es2x.json
    2017/08/31 05:21:07.175887 output.go:281: INFO Loading template enabled for Elasticsearch 6.x. Reading template file: /etc/packetbeat/packetbeat.template-es6x.json
    2017/08/31 05:21:07.176777 client.go:128: INFO Elasticsearch url: http://192.168.3.122:9201
    2017/08/31 05:21:07.176796 client.go:128: INFO Elasticsearch url: http://192.168.3.122:9202
    2017/08/31 05:21:07.176804 client.go:128: INFO Elasticsearch url: http://192.168.3.122:9203
    2017/08/31 05:21:07.176824 client.go:128: INFO Elasticsearch url: http://192.168.3.122:9204
    2017/08/31 05:21:07.176833 client.go:128: INFO Elasticsearch url: http://192.168.3.122:9206
    2017/08/31 05:21:07.177146 outputs.go:108: INFO Activated elasticsearch as output plugin.
    2017/08/31 05:21:07.177255 publish.go:295: INFO Publisher name: packetbeat
    2017/08/31 05:21:07.177465 async.go:63: INFO Flush Interval set to: 1s
    2017/08/31 05:21:07.177473 async.go:64: INFO Max Bulk Size set to: 50
    2017/08/31 05:21:07.177577 procs.go:79: INFO Process matching disabled
    2017/08/31 05:21:07.177718 protos.go:89: INFO registered protocol plugin: mysql
    2017/08/31 05:21:07.177725 protos.go:89: INFO registered protocol plugin: nfs
    2017/08/31 05:21:07.177730 protos.go:89: INFO registered protocol plugin: dns
    2017/08/31 05:21:07.177747 protos.go:89: INFO registered protocol plugin: http
    2017/08/31 05:21:07.177751 protos.go:89: INFO registered protocol plugin: memcache
    2017/08/31 05:21:07.177756 protos.go:89: INFO registered protocol plugin: pgsql
    2017/08/31 05:21:07.177760 protos.go:89: INFO registered protocol plugin: redis
    2017/08/31 05:21:07.177765 protos.go:89: INFO registered protocol plugin: thrift
    2017/08/31 05:21:07.177770 protos.go:89: INFO registered protocol plugin: amqp
    2017/08/31 05:21:07.177803 protos.go:89: INFO registered protocol plugin: cassandra
    2017/08/31 05:21:07.177807 protos.go:89: INFO registered protocol plugin: mongodb
    Config OK
    /etc/init.d/packetbeat: line 55: daemon: command not found

my System specification

    govind ~/packetbeat-5.5.2-darwin-x86_64 # uname -m
    x86_64

     govind ~/packetbeat-5.5.2-darwin-x86_64 # file packetbeat
    packetbeat: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>

    govind ~/packetbeat-5.5.2-darwin-x86_64 #  cat /etc/gentoo-release
    Gentoo Base System release 2.3

    govind ~/packetbeat-5.5.2-darwin-x86_64 # uname -r
    4.12.5-gentoo-v1

Please help
Thanks

**Comment by exekias** [comment]
You downloaded the package for MacOS systems (darwin), check the download page and get the correct one (Linux 64bits).
