### ISSUE TITLE
rpm installation fails due to depencency /bin/sh not found ?

### ISSUE THREAD

**Issue by stefansaye** [elastic/beats#5065]
hi all,

i am trying to install a peacketbeat using rpm, 
Steps i followed,

    curl -L -O https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-5.5.2-x86_64.rpm
    rpm -vi packetbeat-5.5.2-x86_64.rpm
while insatlling. The error i am getting is 

    # rpm -vi packetbeat-5.5.2-x86_64.rpm
    warning: packetbeat-5.5.2-x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY
    error: Failed dependencies:
        /bin/sh is needed by packetbeat-5.5.2-1.x86_64

please help
thank you

**Comment by tsg** [comment]
Related discussion: https://discuss.elastic.co/t/rpm-installation-fails-due-to-depencency-bin-sh-not-found/98941/5

This seems specific to Gentoo systems. As Gentoo is not on our supported platforms list, let's continue the discussion on Discuss, and open a ticket if we figure out something that can be done on the Beats side. Closing for now, just to have a single place where this is discussed.
