### ISSUE TITLE
Access Windows counters

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#507]
Access all the counters that windows has to offer by using `perfmon` to view the available counters.

A lot of those custom counters can come in very useful, e.g. SQL Server:Locks "Average Wait Time (ms)"

If you're periodically firing up powershell to check those counters there can be a pretty noticeable CPU hit, perfmon seems to be a lighter option.
I noticed the powershell overhead when performance testing Splunk data collection and found this in reference to it:
https://powertoe.wordpress.com/2012/06/27/how-to-execute-powershell-scripts-without-the-cpu-hit-to-start-powershell/

**Comment by monicasarbu** [comment]
Duplicate the issue from: https://github.com/elastic/topbeat/issues/28

**Comment by elvarb** [comment]
This already exists in a very solid package 

https://github.com/MattHodge/Graphite-PowerShell-Functions

Runs once and then polls the metrics at an interval and sends in graphite format someplace. 

Been using this for well over a year with great results. But I'm hoping a beat to be able to do the same in the future.

**Comment by monicasarbu** [comment]
@elvarb thanks for sharing with us.

**Comment by ESamir** [comment]
+1

**Comment by ArtyomBaranovskiy** [comment]
+1

**Comment by sylbae** [comment]
+1

**Comment by eskibars** [comment]
Related: I added a community beat at https://github.com/eskibars/wmibeat which can execute arbitrary WMI queries, including access to perfmon counters

**Comment by andrewkroh** [comment]
Metricbeat 6.x is adding a windows/perfmon metricset for reading Windows Performance Counters. Progress is tracked in https://github.com/elastic/beats/issues/3828.
