### ISSUE TITLE
"Container" dashboard in 6.0.0-beta2 shows "cgroups", not just Docker "containers"

### ISSUE THREAD

**Issue by joshuar** [elastic/beats#5074]
Minor nitpick, but in 6.0.0-beta2, the *[Metricbeat System] Containers overview* dashboard is not showing just Docker containers, but all cgroups on the system.  So on a systemd-based distro, you'll get something like this:

![image](https://user-images.githubusercontent.com/7401/29958321-89b70e6c-8f35-11e7-8a74-14080233bf1a.png)

That may be intended and I might full be not following the current overloaded usage of "container" :)  Not sure if we want to clarify anywhere, rename the dashboard, or add further filtering so this dashboard only shows Docker/rkt type containers? 

Possibly a systemd specific dashboard might be useful that displays per-unit metrics?

**Comment by tsg** [comment]
@andrewkroh @monicasarbu I remember we discussed this issue before, but don't remember if we made any plan to solve it or reduce the confusion. Perhaps renaming the dashboards is the way to go?

**Comment by andrewkroh** [comment]
We could rename the dashboard and apply some kind of `drop_field` filter to the default metricbeat config to drop cgroup data if it doesn't contain docker/rkt/runc.

**Comment by jsoriano** [comment]
I agree that we could rename the dashboard to indicate that it is about cgroups.

> Possibly a systemd specific dashboard might be useful that displays per-unit metrics?

This has been added in the upcoming Metricbeat 7.6.0: https://www.elastic.co/guide/en/beats/metricbeat/7.6/metricbeat-metricset-system-service.html
