### ISSUE TITLE
Request for enhancement - Windows Services

### ISSUE THREAD

**Issue by DanBraga** [elastic/beats#5082]
It would be nice if metricbeats (or any other beats) to be able to collect windows services status, instead of only the actual processes, since there is a number of services that run as svchost.

**Comment by andrewkroh** [comment]
Metricbeat has [windows/service](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-windows-service.html) metricset dedicated to monitoring Windows services.
