### ISSUE TITLE
Warning on docs regarding deleting data

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/beats#5083]
[The docs here](https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-template.html) make a reference to deleting data in order to re-apply templates, but should offer a warning.

**Comment by dedemorton** [comment]
@PhaedrusTheGreek Good idea. How about something like:

WARNING: This command will delete all indexes that match the pattern `winlogbeat-*`. Before running this command, make sure you want to delete all indexes that match the pattern.
