### ISSUE TITLE
metricbeat export template fails on installed pacakges

### ISSUE THREAD

**Issue by tsg** [elastic/beats#5089]
- Version: 6.0.0-beta2
- Operating System: Linux
- Steps to Reproduce: 
   * Install deb
   * Run:

```
metricbeat export template --es.version 5.5.2
Error generating template: open fields.yml: no such file or directoryroot@squeeze64:/home/
```

Looks like it's looking in the wrong path.

**Comment by tsg** [comment]
Running like this makes it work:

```
metricbeat -e -E "setup.template.fields=/etc/metricbeat/fields.yml" export template
```

@exekias FYI.

**Comment by exekias** [comment]
This is weird, theoretically it should check into `${path.home}/${setup.template.fields}`, let me look into this
