### ISSUE TITLE
Beats Won't Start if Modules Can't Connect

### ISSUE THREAD

**Issue by ChristopherCorcoran** [elastic/beats#5090]
If I use a filebeats module, like 'system' or 'nginx', filebeats will fail to start if elasticsearch isn't up and running. There's no retry logic in the modules, like there is when you run beats without them. Same is true with metricbeats and the mongodb module. If mongod isn't up, then the metric module won't even start.

This effectively means that modules cannot be reliably used in production, despite the great benefit they provide on perfect, problem free systems.

**Comment by tsg** [comment]
Which version of Beats are you on? Generally speaking, only the `--setup` flag / `setup` command require ES to be up when starting. That's mainly needed for loading the Kibana dashboards. Without `setup`, which is how the the init scripts start the Beats, they don't need ES to up.

The modules in Metricbeat should all keep polling until the monitored service is up. Let me know the version and the module if that's not the case.

**Comment by ChristopherCorcoran** [comment]
Version 5.5.2. Not using setup here.

Here's the mongo module entry from my metricbeat.yml:

- module: mongodb
  metricsets: ["status","dbstats"]
  hosts: ["localhost:27017"]

And from my filebeat.yml:

filebeat.modules:
- module: nginx
- module: system

In the former case, metricbeat won't start unless mongod is running, and in the latter case, filebeat won't start, unless elasticsearch is running (output works fine, without these modules).

**Comment by tsg** [comment]
You are right on both accounts.

For Filebeat modules, that was fixed a while ago in https://github.com/elastic/beats/pull/4479, and the fix is in 6.0.0-beta2, but wasn't backported to 5.5. Is using 6.0.0-beta2 an option for you?

For the Metricbeat MongoDB issue, I opened #5120 with a fix.

**Comment by ChristopherCorcoran** [comment]
We'll hold off on the beta for now since we have a filebeats workaround (manually specifying the pipeline on the client to deliver syslog and nginx to, without using the modules).

Thanks for addressing the mongo issue. We can probably hold off on that until 6.0 is released.
