### ISSUE TITLE
 Packetbeat processing but not sending them to Elasticsearch 

### ISSUE THREAD

**Issue by stefansaye** [elastic/beats#5113]
Hi,
I only want to count the flows count from the device,
so I try to let packetbeat output to my elastsearch and  events showed up in Kibana as expected.

packetbeat : packetbeat-5.5.2
elasticsearch: 5.5
Kibana: Version: 5.5.0

start packetbeat as you can see below,

     # ps aux | grep packetbeat
     root     11763  0.1  0.0 1578716 77460 ?       Ssl  Sep05   2:31 /usr/share/packetbeat/bin/packetbeat -c /etc/packetbeat/packetbeat.yml -path.home /usr/share/packetbeat -path.config /etc/packetbeat -path.data /var/lib/packetbeat -path.logs /var/log/packetbeat

I query in the Elasticsearch, the packetbeat indexes are unavailable.

     # curl '10.10.0.168:9200/_cat/indices?v' | grep packetbeat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  134k  100  134k    0     0  68897      0  0:00:02  0:00:02 --:--:-- 64997

I have loading template manually ,so I set "template.overwrite: false"
part of my packetbeat.yaml, 

    output.elasticsearch:
      # Array of hosts to connect to.
      hosts: ["10.10.0.168:9200","10.10.0.168:9201"]
     index: "packetbeat-%{+yyyy.MM.dd}"
     template.name: "packetbeat"
     template.path: "packetbeat.template.json"
     template.overwrite: false

Packetbeat processing packets but not sending them to Elasticsearch , am I missing anything ?
How can I get packetbeat debug log ?
I will be grateful if you can help me to figure out the root cause. Thank you.

**Comment by andrewkroh** [comment]
Hopefully you got an answer to your question, but if not please post your questions to https://discuss.elastic.co/c/beats/packetbeat. We use Github issues only for tracking bugs and features.
