### ISSUE TITLE
Out of box Metricbeat dashboards not working properly

### ISSUE THREAD

**Issue by bahaaldine** [elastic/beats#5122]
For confirmed bugs, please report:
- Version: 6.0 beta2
- Operating System: macOS Sierra
- Steps to Reproduce: install Elasticsearch, Kibana, and Metricbeat, load kibana dashboards.

When I access the dashboard, here the message I get:

<img width="1260" alt="capture d ecran 2017-09-07 a 12 41 33" src="https://user-images.githubusercontent.com/820299/30160477-d3106e1e-93cc-11e7-822e-857f10dae319.png">

**Comment by monicasarbu** [comment]
How did you load the dashboards? Did you use the command `./metricbeat setup` for loading the dashboards?

**Comment by bahaaldine** [comment]
Hello @monicasarbu yes, i did use the command in the documentation: https://www.elastic.co/guide/en/beats/metricbeat/6.0/load-kibana-dashboards.html

**Comment by nellicus** [comment]
@bahaaldine may I ask what config and setup did you use?

I was unable to load the dashboards as per https://github.com/elastic/beats/issues/5203

**Comment by fearful-symmetry** [comment]
This issue is old and abandoned, closing.
