### ISSUE TITLE
metricbeat/main.go import issue

### ISSUE THREAD

**Issue by Matty9191** [elastic/beats#5140]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version: Head
- Operating System: CentOS 7
- Steps to Reproduce: Build metricbeat

I attempted to build the latest version of metricbeat today and noticed that one of the imports in metricbeat/main.go doesn't exist:

$ cat metricbeat/main.go
/*
Package metricbeat contains the entrypoint to Metricbeat which is a lightweight
data shipper for operating system and service metrics. It ships events directly
to Elasticsearch or Logstash. The data can then be visualized in Kibana.

Downloads: https://www.elastic.co/downloads/beats/metricbeat
*/
package main

import (
	"os"

	"github.com/elastic/beats/metricbeat/cmd"
)

func main() {
	if err := cmd.RootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}
$ curl -I https://github.com/elastic/beats/metricbeat/cmd 2>/dev/null | grep HTTP
HTTP/1.1 404 Not Found

Is this intentional? It's causing the build process to fail on my system.

**Comment by andrewkroh** [comment]
The package definitely exists. You can browse the serve at https://github.com/elastic/beats/tree/master/metricbeat/cmd.

**Comment by Matty9191** [comment]
Thanks for the feedback Andrew. I did some additional troubleshooting this morning and it looks like I was attempting to build metricbeat with go 1.7. Switching to go 1.8 allowed the build to complete w/o issue. Are the go pre-requisites (version, environment, etc.) documented anywhere? Thanks again for your response.
