### ISSUE TITLE
Filebeat - Failing test cases over Windows SMB Share

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#515]
I noticed that some unit testes and some system tests fail when running them inside of Vagrant. Vagrant mounts the git repository over SMB so all of the tests are run on a shared filesystem.

This could be related to: https://discuss.elastic.co/t/filebeat-from-a-windows-network-share/36966/2

[Console Output](http://pastebin.com/raw.php?i=1FUkUVqm)

**Comment by ruflin** [comment]
@andrewkroh See the note here: https://www.elastic.co/guide/en/beats/filebeat/current/_getting_support.html#_network_volumes As far as I remember, one of the three identifiers changes quite frequently on shared volumes which leads to the problem, that it assume it is a new file: https://msdn.microsoft.com/en-us/library/aa363788(v=vs.85).aspx That is the reasons I stopped using shared drives for vagrant tests.

**Comment by ruflin** [comment]
@andrewkroh @guyboertje I think this issue would be resolved with introducing fingerprints.

**Comment by ruflin** [comment]
@andrewkroh I'm closing this issue as it is documented and the only solution here is fingerprinting I think. Please reopen if you think we should keep it open.
