### ISSUE TITLE
Metricbeat: Postgresql Module Missing Field Error

### ISSUE THREAD

**Issue by kwojcicki** [elastic/beats#5155]
Tested using metricbeat 5.6.0 and 6.0.0-beta2 with following metricbeat.yml module for postgres
```
- module: postgresql
  name: postgresql
  enabled: true
  period: 10s
  metricsets: ["database", "bgwriter", "activity"]
  hosts: ["postgres://postgres:5432?sslmode=disable"]
  username: postgres
  password: postgres
```
The metricbeat docker container outputs the following
```
2017/09/11 19:32:04.738097 schema.go:41: ERR Error on field 'query_start': Missing field: query_start, Error: Error converting param to time.Time: query_start. Original: 
2017/09/11 19:32:04.738124 schema.go:41: ERR Error on field 'waiting': Missing field: waiting, Error: Key `waiting` not found
```
The metrics are still put into elasticsearch but perhaps this message should be put down to a warning or is there a way to set these parameters to optional?

**Comment by kwojcicki** [comment]
This was caused by one of our services in correctly connecting to postgres and the table pg_stat_activity to have a partially empty row.

**Comment by kwojcicki** [comment]
Reopening this because I dont think the default behaviour of metricbeat is very intuitive. Running metricbeat 5.5 and postgres 9.5. If in one terminal i I go into my docker postgres container and enter psql
`docker exec -it -u postgres postgres_container sh
psql`

I can then repeat that process and in the second session run the following search
`select * usename,query_start,query,state from pg_stat_activity;`

One of the rows returned has a few empty columns (one of those being query_start) due to the session created in the first terminal. This causes metricbeat to output errors such as the following
2017/10/12 18:36:28.555664 schema.go:38: ERR Error on field 'query_start': Error converting param to time.Time: query_start. Original:

Not sure the best approach to handle this but potentially changing the query from
`SELECT * FROM pg_stat_activity` to
`SELECT * FROM pg_stat_activity WHERE query_start is NOT null`

**Comment by ruflin** [comment]
It seems like we should set `query_start` and `waiting` as an optional field to prevent the error: https://github.com/elastic/beats/blob/master/metricbeat/module/postgresql/activity/data.go#L29

Did you see any other fields with errors?

**Comment by kwojcicki** [comment]
Sometimes it has also complained about state_change but setting those 3 to optional should fix it I believe.

**Comment by ruflin** [comment]
Seem like @liketic already started to work on a solution here: https://github.com/elastic/beats/pull/5398

**Comment by GRomR1** [comment]
I want to monitor PostgreSQL 9.4 and have this error:
`ERR  Error on field 'port': Missing field: port, Error: Error converting param to int: client_port`
I've run a query `select * from pg_stat_activity;` and got next columns:
- datid            
- datname          
- pid              
- usesysid         
- usename          
- application_name 
- client_addr      
- client_hostname  
- client_port      
- backend_start    
- xact_start       
- query_start      
- state_change     
- waiting          
- state            
- backend_xid      
- backend_xmin     
- query

**Comment by ruflin** [comment]
@GRomR1 Please open a topic on this with your question: https://discuss.elastic.co/c/beats/metricbeat
