### ISSUE TITLE
Logging:  Log attempts from Beats to re-establish connections

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#5175]
Currently, at the default logging level, we are not logging entries on when Logstash attempts to re-establish connections (eg. due to DNS for downstream servers not available).  For example, after these messages when the DNS issue is resolved:

```
2017-09-07T02:50:43-07:00 WARN DNS lookup failure "<hostname>": lookup <hostname> on <ip>: read udp <ip>:51430-><ip>: i/o timeout
2017-09-07T02:50:43-07:00 ERR Connect failed with: lookup <hostname> on <ip>: read udp <ip>:51430-><ip>: i/o timeout
```

Having this information logger at the default level can help with troubleshooting.

**Comment by liketic** [comment]
Hi @ppf2 seems like it's a low hanging fruit issue, can I take it? 😄

**Comment by ruflin** [comment]
@liketic Of course, all contributions are welcome.

**Comment by brandonmensing** [comment]
@liketic https://github.com/elastic/beats/issues/5198 may be tempting for you as well, and thanks for any contribution here!

**Comment by agathver** [comment]
Hi, I'm currently looking at beats source code and getting familiar with it. I'm interested to give this a try.
