### ISSUE TITLE
HAProxy module authentication support for metrics

### ISSUE THREAD

**Issue by sgelastic** [elastic/beats#5178]
HAProxy metrics can be configured with authentication. The MetricBeat HAProxy module does not seem to be able to pull this data when authentication is supported. My client is adamant he needs this feature to monitor sensitive production devices.

**Comment by andrewkroh** [comment]
What type of authentication are you referring to? Can you please provide an example configuration for the HAProxy side. That will help us with coming up with a test case.

**Comment by sgelastic** [comment]
This is how you configure HAProxy to collect and display metrics with authentication:

listen stats :9000  # Listen on localhost:9000
mode http
stats enable  # Enable stats page
stats hide-version  # Hide HAProxy version
stats realm Haproxy\ Statistics  # Title text for popup window
stats uri /haproxy_stats  # Stats URI
stats auth Username:Password  # Authentication credentials

https://www.datadoghq.com/blog/how-to-collect-haproxy-metrics/

**Comment by exekias** [comment]
This should be working already, we just have to update docs, please check https://github.com/elastic/beats/issues/4457

**Comment by sgelastic** [comment]
Has anyone actually tested this, because we could not get it to work, which is why I opened this ticket.

**Comment by ruflin** [comment]
@sgelastic https://github.com/elastic/beats/pull/5819 was just merged thanks to @jsoriano . Would be great if you could test this with a snapshot build again.
