### ISSUE TITLE
Packetbeat: Developer Guide still mentions godep instead of glide

### ISSUE THREAD

**Issue by darxriggs** [elastic/beats#518]
see https://www.elastic.co/guide/en/beats/packetbeat/current/_developer_guide_adding_a_new_protocol.html#_a_note_about_dependencies

**Comment by dedemorton** [comment]
@ruflin It looks like you've removed the section about godep from the doc in master and 1.1. Can I close this item, or do we want to add something that talks about glide?

**Comment by ruflin** [comment]
@dedemorton Correct. Closing this one.
