### ISSUE TITLE
[ Filebeat file input/output: Simple regex for log filtering ]

### ISSUE THREAD

**Issue by jerome83136** [elastic/beats#5187]
Hi,

I wonder if I can use filebeat (because it needs very few resources on the system); to filter my log files.

I want to read some lof files (file input) and to write them into several output files bases on the content on the input log files.

Example:

My source log file contains apache2 access logs and these lines will be written to the corresponding output files:
 "myip1 myuser1 timestamp mycountry1 myapp1 blah" --> output file: /tmp/myapp1_mycountry1.txt
 "myip2 myuser2 timestamp mycountry2 myapp1 blah" --> output file /tmp/myapp1_mycountry2.txt

As you can see; I would like to use the content of the "message" field to match the correct output file name (my logs are apache2 access logs, so they should be automaticay parsed, right ?)

I know that Filebeat can't do complex regex matching and fields extractions. But I wonder if the processors with the regex could help me ?

Thanks for your help

Best regards
Jérôme

**Comment by andrewkroh** [comment]
Filebeat can only write to a single output file so it would not be suitable for this application. Logstash would be well suited for this task.
