### ISSUE TITLE
Logging:  Log file descriptor warning ahead of time

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#5206]
Running out of file descriptors on a machine can cause beats to stop/fail to connect to downstream collectors.  It will be nice to write a warning message to the beats log file ahead of time when it detects only N % of file descriptors are available.

**Comment by ruflin** [comment]
If a OS or user only has a lower number of file descriptors available, we recommend to use `harvester_limit`. This has the side affect in case the output is stuck, new files can be deleted by the OS as they will never be opened.

FB itself should report the total number of open file handlers it has (we already have that in the internal metrics) and for example metricbeat should be able to tell how much file handlers are available in total, so the 2 values could be compared. 

I definitively see the need for such a feature but I'm not sure if it fits into Filebeat itself or should be outside as part of the monitoring system. It's probably a combination.
