### ISSUE TITLE
Monitor filesystem usage in metricbeat

### ISSUE THREAD

**Issue by henrikno** [elastic/beats#5209]
It would be nice if the metricbeat elasticsearch module could report file system usage as reported by Elasticsearch. It'd allow to alert when going low on disk and tracking usage over time.

```
      "fs" : {
        "timestamp" : 1491553781646,
        "total" : {
          "total_in_bytes" : 67371577344,
          "free_in_bytes" : 51743817728,
          "available_in_bytes" : 48291119104
        },
```

It is reported by ES stats here:
https://github.com/elastic/beats/blob/c2bd3efb2994606731b25e1a761b877f3b70dd25/metricbeat/module/elasticsearch/node_stats/_meta/test/node_stats.522.json#L355-L357

The `store.size.bytes` is not accurate enough when indices are closed or not loaded.

**Comment by ruflin** [comment]
@henrikno Please have a look at https://github.com/elastic/beats/pull/5230
