### ISSUE TITLE
Filebeat: How to build filebeat-god?

### ISSUE THREAD

**Issue by benben** [elastic/beats#521]
I tried to crosscompile for arm. How can I also compile the `filebeat-god`binary?

**Comment by benben** [comment]
found it. its in the https://github.com/elastic/beats-packer repo

**Comment by XooR** [comment]
beats use go-daemon:
https://github.com/tsg/go-daemon

**Comment by qgicup** [comment]
Can you post a link, where you've found it?

**Comment by ruflin** [comment]
All the packaging stuff now moved under `dev-tools/packer`: https://github.com/elastic/beats/tree/master/dev-tools/packer

**Comment by klud1** [comment]
I'm stuck in this one, trying to compile it for arm as well

**Comment by tsg** [comment]
@klud1 It's better to open a [discuss](https://discuss.elastic.co) topic for this. But I'd expect something like `gcc -Wall -o filebeat-god god.c` to work.
