### ISSUE TITLE
Automated testing in modules for multiple versions of 3rd party tools 

### ISSUE THREAD

**Issue by brandonmensing** [elastic/beats#5210]
Enhancement to our testing would allow us to more easily support multiple versions of a software/service (apache, haproxy, etc, etc).

**Comment by ruflin** [comment]
@exekias I'm thinking perhaps we can modify your new tool to also pass a list of versions which should be tested for each module.

**Comment by exekias** [comment]
Yeah, I guess we can extend current API to support this somehow

**Comment by ruflin** [comment]
A first example of multiple version testing: https://github.com/elastic/beats/pull/6793 Probably not the most scalable approach yet but it gets the job done.
