### ISSUE TITLE
run the official docker image with k8s failed

### ISSUE THREAD

**Issue by pnuzyf** [elastic/beats#5224]
I got the following message:

Message:          oci runtime error: container_linux.go:262: starting container process caused "exec: \"filebeat\": executable file not found 

my daemonset.yaml :

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    app: filebeat
spec:
  template:
    metadata:
      labels:
        app: filebeat
      name: filebeat
    spec:
      containers:
      - name: filebeat
        image: 10.25.10.9:8050/tools/filebeat:5.6.1
        env:
          - name: LOGSTASH_HOSTS
            value: logstash:5044
          - name: LOG_LEVEL
            value: info
          - name: FILEBEAT_HOST
            valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        volumeMounts:
        - name: varlog
          mountPath: /var/log/containers
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: filebeat-config
          mountPath: /usr/share/filebeat
        - name: registry
          mountPath: /usr/share/filebeat/data
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/containers
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: filebeat-config
        configMap:
          name: filebeat-config
      - name: registry
        hostPath:
          path: /var/lib/filebeat/data

**Comment by exekias** [comment]
Please use [discuss](https://discuss.elastic.co/c/beats) for questions, are you certain that's the official image, binary should be under `/usr/share/filebeat/filebeat`

**Comment by pnuzyf** [comment]
yes, I just tag it to my private registry! mybe due to the default account of filebeat?
