### ISSUE TITLE
Deprecation warning about the `-setup` flag

### ISSUE THREAD

**Issue by tsg** [elastic/beats#5226]
Currently says:

```
2017/09/22 10:13:59.165746 cfgwarn.go:18: WARN DEPRECATED: -setup flag has been deprectad, use setup subcommand Will be removed in version: 6.0
```

That's not true, we're not removing it in 6.0.

**Comment by liketic** [comment]
@tsg Maybe this is not issue now because I can find the log in master branch.

**Comment by exekias** [comment]
This was actually backported here: https://github.com/elastic/beats/pull/4926/files but some other refactoring introduced it back. I'll open a PR for 6.0

**Comment by liketic** [comment]
@exekias This can be closed.
