### ISSUE TITLE
beat name of the form "my-shipper-1" or "my.shipper.1" doesn't show up correctly in Kibana

### ISSUE THREAD

**Issue by amitsaha** [elastic/beats#523]
When the beat name (verified with topbeat) is of the form "my-shipper-1" (or 
"my.shipper.1"), "my", "shipper", "1" are treated as separate beat names in the Kibana UI. I would be happy to delve deeper into this and give more information and perhaps even work on a patch. 

I have a feeling this is a dashboard issue, so let me know and I can file this as a issue in the beats-dashboard project.

**Comment by gerardorochin** [comment]
The topbeat template is not loaded into elasticsearch?https://www.elastic.co/guide/en/beats/topbeat/current/topbeat-getting-started.html#topbeat-template

**Comment by amitsaha** [comment]
I tried it again, here is the template:
```
http://<ip>:9200/_template/topbeat

{
topbeat: {
order: 0,
template: "topbeat-*",
settings: {
index: {
refresh_interval: "5s"
}
},
mappings: {
_default_: {
dynamic_templates: [
{
template1: {
mapping: {
ignore_above: 1024,
index: "not_analyzed",
type: "{dynamic_type}",
doc_values: true
},
match: "*"
}
}
],
_all: {
norms: {
enabled: false
},
enabled: true
},
properties: {
proc: {
properties: {
mem: {
properties: {
rss_p: {
type: "float",
doc_values: "true"
}
}
},
cpu: {
properties: {
user_p: {
type: "float",
doc_values: "true"
}
}
}
}
},
@timestamp: {
type: "date"
},
load: {
properties: {
load5: {
type: "float",
doc_values: "true"
},
load1: {
type: "float",
doc_values: "true"
},
load15: {
type: "float",
doc_values: "true"
}
}
},
mem: {
properties: {
used_p: {
type: "float",
doc_values: "true"
},
actual_used_p: {
type: "float",
doc_values: "true"
}
}
},
swap: {
properties: {
used_p: {
type: "float",
doc_values: "true"
},
actual_used_p: {
type: "float",
doc_values: "true"
}
}
},
cpu: {
properties: {
user_p: {
type: "float",
doc_values: "true"
},
system_p: {
type: "float",
doc_values: "true"
}
}
},
fs: {
properties: {
used_p: {
type: "float",
doc_values: "true"
}
}
}
}
}
},
aliases: { }
}
}
```

I have a beat named as ``ubuntu-1`` and this is how it appears in the dashboard:
![topbeat1](https://cloud.githubusercontent.com/assets/512598/11800249/f5e9a882-a32e-11e5-9ef9-0da9324c9027.png)

The raw CSV looks like this:

```
"beat.name: Descending","Average cpu.user_p","Average cpu.system_p","Max mem.total","Max mem.used","Max mem.used_p","Max mem.free"
1,0,"0.03166666666666667",8236027904,6116544512,"0.74",2190585856
macosx1,0,"0.0022448979591836735",17179869184,7334821888,"0.43",9853046784
ubuntu,0,"0.03166666666666667",8236027904,6116544512,"0.74",2190585856

```

**Comment by monicasarbu** [comment]
@amitsaha After you load the template for topbeat in Elasticsearch, you need to delete the old documents from topbeat-* in order to force Kibana to look at the newest documents. You can use:
<pre>
curl -XDELETE 'http://127.0.0.1:9200/topbeat-*'
</pre>

**Comment by amitsaha** [comment]
Thank you @monicasarbu - that was the issue, closing it now.
