### ISSUE TITLE
[Feature request - Heartbeat] Allow response body parsing

### ISSUE THREAD

**Issue by radoondas** [elastic/beats#5234]
Hi!
this is a feature request for Heartbeat as it is not possible to parse responses.

Allow parsing of response body and take action based on results. 

This would be efficient for use case where endpoint respond with not only status (it is always 200) but also respond with response body which contains more information about service. 

This feature could simply look for defined strings, or expected values (not full response body). Regular expressions would be best to allow for string definition.
 
Thanks

**Comment by CamiloSierraH** [comment]
+1

**Comment by andrewvc** [comment]
Closing because we've had this feature for a while now supporting regexp and JSON parsing.
