### ISSUE TITLE
JSON decoder - target: (merge with root) not working as advertised

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/beats#5239]
[decode_json_fields docs](https://www.elastic.co/guide/en/beats/filebeat/current/decode-json-fields.html) say that you can use `target:` to merge with root, but it doesn't work unless you do `target: ""` 

cc @andrewkroh

**Comment by dedemorton** [comment]
Unfortunately this doc was fixed (with the change merged in 5.5), but never got ported to the other branches. I am doing that now. Thanks for opening the issue!
