### ISSUE TITLE
Extending to metricbeat error

### ISSUE THREAD

**Issue by caibaoying** [elastic/beats#5244]
when I use "make setup" accoring to https://www.elastic.co/guide/en/beats/devguide/current/creating-beat-from-metricbeat.html1. it appends error:

    rm -r _meta/kibana/dashboard _meta/kibana/search _meta/kibana/visualization
    rm: cannot remove 鈥榑meta/kibana/dashboard鈥 No such file or directory
    rm: cannot remove 鈥榑meta/kibana/search鈥 No such file or directory
    rm: cannot remove 鈥榑meta/kibana/visualization鈥 No such file or directory
    make[1]: [kibana] Error 1 (ignored)
    mkdir -p _meta/kibana
    cp -r module//_meta/kibana _meta/
    cp: cannot stat 鈥榤odule//_meta/kibana鈥 No such file or directory
    make[1]: [kibana] Error 1 (ignored)
    mkdir -p include
    python ./vendor/github.com/elastic/beats/metricbeat/scripts/generate_imports.py github.com/caibaoying/axtxmetricbeat > include/list.go
    make[1]: Leaving directory `/home/cby/gopath/src/github.com/caibaoying/axtxmetricbeat'

env: golang 1,7,6 metricbeat -v 5.4.3

if you answer my quesstion. I will appreciate you.

**Comment by kaiyan-sheng** [comment]
This issue is for an old version of beats, I suggest to try out the latest version of beats. If this is still a problem in the newly released version feel free to reopen this issue. Thanks.
