### ISSUE TITLE
Beats field-names are not aligned

### ISSUE THREAD

**Issue by xlammertink** [elastic/beats#5267]
I implemented multiple products of the beats family on a hosts. I configured the beats products to send beats to logstash and logstash should store this in elasticsearch.

However, I noticed that after connecting multiple beats products, I was not able to see the logs popping up in elasticsearch. While debugging this issue in logstash I noticed that some field types were not matching. (I think this was the combination of packetbeat and metricbeat)

As soon as I made sure that the logs ended up in different indices there were no problems anymore.

I think that in order to properly solve this, there should be one generic naming scheme for all the beats products that ensures that all metrics can be stored in one index.

Details when experiencing the bug:
- Products: Metricbeat, Packetbeat, Winlogbeat, Auditbeat (but also holds for other beats products)
- Version: 5.6 and 6.0
- Operating System: Windows 10
- Steps to Reproduce: Install multiple beats products (think it was metricbeat and packetbeat that caused this issue) and make sure that output is stored in the same index.

**Comment by ruflin** [comment]
Unfortunately there are a few conflicts between the beats for historical reasons. In general it is recommended to feed the data for each beat in it's own index. You can still query across multiple indices if you use a similar prefix or specify multiple indice patterns to search one.

We are aware of the above issue and work on aligning the data models but it's a bit tricky as these are breaking changes.

I would be interested to hear a bit more details on what exactly the data is that you want to correlate between the beats?

**Comment by andrewkroh** [comment]
I don't think there is anything specifically actionable in this issue so I'm going to close it. We are working to align some of the fields that are commonly used to query across datasets. First we are working on defining a schema in https://github.com/elastic/ecs then we will update Beats for the next major version.
