### ISSUE TITLE
Make general elasticsearch/logstash output idempotent

### ISSUE THREAD

**Issue by jordansissel** [elastic/beats#5269]
Related: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/690

Background: When Elasticsearch shuts down normally (via SIGINT/SIGTERM), it closes all open HTTP connections even for in flight requests. The impact of this is that the client (beats) determines this to be a failed request and will resubmit (Excellent!). Unfortunately, for these interrupted requests, Elasticsearch still has accomplished the work in most cases (in my testing). This means the client saw an error when Elasticsearch was actually successful in performing the task.

Impact: When Elasticsearch restarts, beats will resend the last request (because the connection was closed), and create duplicates in Elasticsearch.

Here's what filebeat logs, for example, when Elasticsearch shuts down while an active /_bulk is going on:

```
2017/09/28 13:15:13.060732 client.go:255: ERR Failed to perform any bulk index operations: Post http://localhost:9200/_bulk: EOF
```

Reproducing:

* `bin/elasticsearch `
* `seq -f '{ "sequence": %g }' 40000 | ./filebeat`

While filebeat is indexing, stop Elasticsearch with ctrl+c and let it safely exit. Then restart Elasticsearch and let filebeat finish its work.

Then I scan the whole index and look for duplicates, and I find a range of sequence numbers (from my input) that are duplicated: 2499-2548 (50 contiguous documents).

----

Logstash has this same problem when talking to Elasticsearch and ES shuts down (https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/690). 

----

## Proposal

(copied from the logstash issue)

Given: 

We must accept that normal operator maintenance of Elasticsearch is indistinguishable from a network fault. Therefore, we should try to make this plugin's common case idempotent.

Proposed solution:

Beats should create document ids for any events not already having a document id. This ensures that any retransmissions will have the same document id and therefore the operation will not result in duplicates. It should use `create` action in _bulk requests to ensure that already-present documents are rejected and duplicates are avoided. I propose this behavior be the default behavior.

**Comment by jordansissel** [comment]
Additional proposal that Beats create the document ids when sending to either Logstash or Elasticsearch, this way any retransmission through the flow beats->logstash->elasticsearch are deduplicated by Elasticsearch.

**Comment by tsg** [comment]
This is related to https://github.com/elastic/beats/issues/1492. We had a few attempts to solve it, but nothing stuck so far.

**Comment by tsg** [comment]
The fact that duplicates happen during normal operation is a new twist to it, though, I didn't know that's the case.

**Comment by jordansissel** [comment]
For many beats, it's possible that generating a random id is good enough (because the data is ephemeral). For example: metricbeat, heartbeat, and packetbeat all are sourcing from ephemeral things (packets, OS stats, etc). For beats which have some kind of seekable cursor or replayability (filebeat, winlogbeat, auditbeat maybe?) I think is where we'd need some kind of computable id for a given event.

As a separate problem, beats which read from persistent sources (filebeat, winlogbeat) could use some values to derive a reproducible id: 
* filebeat: host, path, inode, byte offset 
* winlogbeat: host, log name (application, etc), and offset

To solve separately (and I think Logstash will do this as well), maybe start by having every event get a unique ID. That will reduce the problem space from "duplicates during network faults" to "duplicates during filebeat replaying of files" (same for Logstash file input, s3 input, etc). We can separately work on generating computable+reproducible identifiers for things like files.

**Comment by waroca** [comment]
Pinging this thread to see if anybody was able to solve this any other way using beats? It still seems like a useful feature. Wondering if there was any traction/plan or it was solved.

**Comment by ph** [comment]
I am closing this issue we are tracking the work in https://github.com/elastic/beats/issues/1492 and @ycombinator has a PR open at https://github.com/elastic/beats/pull/14524
