### ISSUE TITLE
6.0 Metricbeat dashboards switched name key?

### ISSUE THREAD

**Issue by jamiesmith** [elastic/beats#5276]
I am trying out the 6.0 metricbeat and kibana dashboards, in preparation for getting some screenshots for the new scheme, and I ran in to an issue.

In the 5.x versions of the metricbeat dashboards, the host stuff was keyed on `beat.name` (which defaults to the hostname, but can be overridden by setting the name in the config, https://www.elastic.co/guide/en/beats/metricbeat/5.6/configuration-general.html#_name)

With the 6.0 the visualizations are keyed on beat.*hostname* - which cannot be overridden.  Was this a choice that was made?  Or perhaps someone simply picked the wrong field for all of the visualizations?

I was told the change was intentional, but I am looking for a discussion before GA.

I think the `beat.name` makes a lot more sense - customers can either accept the hostname, or override the beat name and use that.  I see a lot of value in overriding - host names might be something generated, like `us-east-dc-1-rack-3`, but when they were keyed off of the overridable `name`, it could show up as `webserver1`.  they can always go back to look at the source data to find out the hostname webserver1 - because that is in the data.  

@monicasarbu @tsg @simianhacker

**Comment by tsg** [comment]
We've discussed this in our team meeting and decided to go back to using `beat.name` as it allows more flexibility. See https://github.com/elastic/kibana/issues/14332 for a prime example of this. I'm currently working on a fix.
