### ISSUE TITLE
Metricbeat 6.0 Dashboards are not compatible with Kibana Master (7.x)

### ISSUE THREAD

**Issue by simianhacker** [elastic/beats#5278]
Kibana changed the format of the query argument for SavedObjects. This is causing the 6.0 dashboards to not work in Kibana 7.x (master). We will need to install separate dashboards for 5.x, 6.x and 7.x

**Comment by tsg** [comment]
@simianhacker Wouldn't be possible to do the translation at import time, in the Kibana plugin? I imagine that Kibana will need anyway a plan to upgrade existing dashboards, like they have for the 5 to 6 transition, right?

**Comment by urso** [comment]
@ruflin @simianhacker Can this be closed?

**Comment by ruflin** [comment]
@urso Closing as only MB 6.7 will work with 7.0.
