### ISSUE TITLE
Get Container IPAddress

### ISSUE THREAD

**Issue by wangxfbelieve** [elastic/beats#5282]
Hi guys，
    we have a specical requirement, It's that get the IPAddress of container under the swam cluster,
and i change the code, such as：
    open  the file, beats/metricbeat/module/docker/container/data.go:
```
func eventMapping(cont *dc.APIContainers) common.MapStr {
        event := common.MapStr{
                "created": common.Time(time.Unix(cont.Created, 0)),
                "id":      cont.ID,
                "name":    docker.ExtractContainerName(cont.Names),
                "command": cont.Command,
                "IPAddres": cont.Networks,
                "image":   cont.Image,
                "size": common.MapStr{
                        "root_fs": cont.SizeRootFs,
                        "rw":      cont.SizeRw,
                },
                "status": cont.Status,
        }
```
your will be see the ipaddress in the container info schema.

**Comment by exekias** [comment]
Adding the IP address looks good to me, do you think you could open a PR for it? I think we would need to convert cont.Networks structure into a list of IPs

**Comment by liketic** [comment]
@exekias If no one is working one this, may I take it?

**Comment by exekias** [comment]
sure! feel free to take it, and ping us if you need any help :smiley:
