### ISSUE TITLE
Set default query for "[Metricbeat System] Host overview" dashboard

### ISSUE THREAD

**Issue by xeraa** [elastic/beats#5284]
The Metricbeat *Host overview* appears empty whereas the general *Overview* shows data by default, because it has set the default query to `*` (via `"kibanaSavedObjectMeta.searchSourceJSON.query":"*"`).

I think we should set the same default search value for the *Host overview*, so it doesn't look empty and people get confused (like I did).

**Comment by jamiesmith** [comment]
Maybe we can include a "Current Beat" metric viz on the host overview dashboard showing the currently selected beat?  Plus, add a tip on the "system overview" dashboard that you can double click to focus on one host.  

If the "Host Overview" dashboard isn't useful without the context, maybe it shouldn't be directly accessible from that top level dashboard, and only have "System Overview | Containers Overview"?

**Comment by xeraa** [comment]
I assume "showing the currently selected beat" should be host, right? From what I know this kind of drill down is on the todo list, but not yet done. Time Series Visual Builder has a way to link to another visualization, but it requires an absolute URL from what I know (and it's not really nice to configure)
