### ISSUE TITLE
Need to proofread any externally visible strings

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#529]
The following PR got me thinking: https://github.com/elastic/beats/pull/526. The PR fixes one typo, but there's another typo in the same comment: "use it’s name to fill" should be "use its name to fill." 

I'd like to read through any files that contain text strings that we externalize (that is, text that users see) to check for typos. I'm not proposing a full technical edit. I just want to ferret out any typos that might make our user-visible strings look unpolished. At the very least, I should check all the comments in the configuration files.

@elastic/beats  WDYT? If you want me to do this work, let me know which files to check. I can fix the problems myself or open a PR. Let me know what you prefer.

**Comment by andrewkroh** [comment]
I think this is a good idea. You could basically look through all `.go` files in the repo (skipping the `/vendor` directory and the `*_test.go` files). There are 115 files by my count. The strings that a user could potentially see would be in calls to `logp` or `fmt`.

**Comment by dedemorton** [comment]
I'm going to close this because...well...it's very old. We should continue to use spellcheckers to check for spelling errors.
