### ISSUE TITLE
Readable names as IDs for all shipped dashboards

### ISSUE THREAD

**Issue by brandonmensing** [elastic/beats#5294]
Many dashboards shipped with various Beats have an ID similar to the name which is readable and friendlier for linking. The IDs we have do work for linking but we should clean up and make the consistent.

Here's a readable ID: https://github.com/elastic/beats/blob/master/metricbeat/module/apache/_meta/kibana/default/dashboard/Metricbeat-apache-overview.json#L150

And here's a generic generated ID: https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/_meta/kibana/default/dashboard/Metricbeat-kubernetes-overview.json#L277

**Comment by tsg** [comment]
From what I know, Kibana currently doesn't offer a mechanism to set human readable IDs. The main reason we have some is that they were created before Kibana moved to generated IDs. We could do some hacks and get them in, but hacks like that come with a bit of risk and maintenance overhead.  So it's debatable if it's worth it.

**Comment by brandonmensing** [comment]
Hmmm, but can't we just replace the ID string in the JSON right there and it'll just work when it gets imported? I don't know enough about the export/edit process to know what trouble that's asking for :)

**Comment by jsoriano** [comment]
We are tending towards using the ids generated by kibana on the process of creation, even if it is not so nice for linking it is easier to maintain and less prone to conflicts.
I am closing this by now, we may reconsider this decission in the future.
