### ISSUE TITLE
filebeat sending logs only once

### ISSUE THREAD

**Issue by TehesFR** [elastic/beats#530]
Hello there,

I'm using filebeat in a PHP/apache docker container to send logs to an elk container.
I've configured everything, and I can see filebeat processes running inside my container.

    root       490  0.0  0.0   9400   568 ?        Sl   18:30   0:00 /usr/bin/filebeat-god -r / -n -p /var/run/filebeat.pid -- /usr/bin/filebeat -c /etc/filebeat/filebeat.yml
    root       491  0.0  0.3 352736  9712 ?        Sl   18:30   0:00 /usr/bin/filebeat -c /etc/filebeat/filebeat.yml

When the container starts, my apache logs are correctly sent to my elk container, and I can browse them in Kibana, but it only works once...

If I generate new entries in my apache logs by browsing my website, filebeat will not send them to logstash anymore. If I restart filebeat service, it will send my new logs to logstash, but once again, it works only one time.

I tried to change the "scan_frequency" in filebeat.yml but it didn't helped.

I think filebeat is the issue because if I listen on port 5044 on my network interface, I can see the packets sent to my elk container when filebeat service starts, but after that, nothing is sent anymore even if my logs files are modified.

Am I doing something wrong ?
Tell me if you need additional information.

Thank you

**Comment by TehesFR** [comment]
Sorry my bad.

In my filebeat.yml I had:

    elasticsearch:
        enabled: false
        hosts: ["localhost:9200"]

and then:

    logstash:
        # The Logstash hosts
        hosts: ["elk:5044"]

I thought it would disable elasticsearch but obviously it didn't work. I removed the elasticsearch part and everything work now.

Thank you for filebeat :)

**Comment by tsg** [comment]
For background, the `enabled` option was removed as kind of redundant before 1.0.0. Thanks for following back and for using filebeat! <3

**Comment by seppaleinen** [comment]
Thanks!
This solved my problem as well!
