### ISSUE TITLE
Beats should not enforce `setup.template.name` and `pattern` if templates are disabled.

### ISSUE THREAD

**Issue by pmusa** [elastic/beats#5308]
When you set `output.elasticsearch.index: "my_index"` Beats force you to also set `setup.template.name` and `setup.template.pattern` (`Exiting: setup.template.name and setup.template.pattern have to be set if index name is modified.`). However, if you don't want Beats to manage templates and set `setup.template.enabled: false` it still complains about the settings above, but it should not.

**Comment by kurtado** [comment]
Maybe these could be added to the default config and just left commented out? Would be much easier for users to figure out and fix.

**Comment by ruflin** [comment]
I opened a PR here to fix the issue: https://github.com/elastic/beats/pull/5319

@kurtado If this will be a common issue that people change the index pattern, we should add it to the default config options to make it easily modifiable. I'm kind of hoping the default is not changed that often as also the setting to change the ES index is not in the default config.
