### ISSUE TITLE
Filebeat sometimes gets stuck in continuous error

### ISSUE THREAD

**Issue by nickcarenza** [elastic/beats#5311]
Sometime filebeat will start erroring and it won't correct itself until I restart the process. There are ~30 servers running filebeat and pushing to the same logstash. Once in a while one of them will start erroring all by itself.

filebeat version 5.5.2 (amd64), libbeat 5.5.2

> metrics.go:34: No non-zero metrics in the last 30s
sync.go:85: Failed to publish events caused by: EOF
single.go:91: Error publishing events (retrying): EOF
metrics.go:39: Non-zero metrics in the last 30s: libbeat.logstash.call_count.PublishEvents=1 libbeat.logstash.publish.read_errors=1 libbeat.logstash.publish.write_bytes=1639 libbeat.logstash.published_but_not_acked_events=48

**Comment by ruflin** [comment]
@nickcarenza We are trying to keep Github for confirmed bug. Can you please open a topic on discuss with this: https://discuss.elastic.co/c/beats/filebeat

Please post there also your config for Filebeat and Logstash and add the Logstash logs if possible.
