### ISSUE TITLE
Problem with two outputs in metricbeat.yml

### ISSUE THREAD

**Issue by githubmui** [elastic/beats#5317]
Metribeat-Version 6.0.RC1:
How to configure file and elasticsearch output at the same time in metricbeat.yaml ?

output.file:
  path: "d:\temp\"
  filename: metricbeat.dat
  rotate_every_kb: 10000
  number_of_files: 5 

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]

Error is: 
error unpacking config data: more then one namespace configured accessing 'output' (source:'metricbeat.yml')

**Comment by ruflin** [comment]
Support for multiple outputs was removed in 6.0. See https://www.elastic.co/guide/en/beats/libbeat/6.0/breaking-changes-6.0.html#breaking-changes-single-output

For questions please use discuss in the future: https://discuss.elastic.co/c/beats

**Comment by japzio** [comment]
> Support for multiple outputs was removed in 6.0. See https://www.elastic.co/guide/en/beats/libbeat/6.0/breaking-changes-6.0.html#breaking-changes-single-output
> 
> For questions please use discuss in the future: https://discuss.elastic.co/c/beats

Thanks,
