### ISSUE TITLE
Read kMDItemWhereFroms attribute with file integrity module

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#5336]
On macOS the `kMDItemWhereFroms` extended file attribute stores information about where a file came from. Browsers like [Chrome](https://codereview.chromium.org/220037) add the download URL and the HTTP referrer to this attribute. Mail programs add sender and subject info. This can be useful in determining the initial source of a malicious payload and would be interesting data to have indexed.

```
$ mdls -name kMDItemWhereFroms ~/Downloads/filebeat-5.6.2-windows-x86_64.zip 
kMDItemWhereFroms = (
    "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.6.2-windows-x86_64.zip",
    "https://www.elastic.co/downloads/beats/filebeat"
)

$ mdls -name kMDItemWhereFroms ~/Downloads/Mail\ Attachment.txt 
kMDItemWhereFroms = (
    "USPS <USPSInformedDelivery@usps.gov>",
    "Informed Delivery Daily Digest",
    "message:%3C853373976.1039183.1507203954481.JavaMail.prmin@eagnmncom1ab7.usps.gov%3E"
)
```

I didn't see any existing Go code for reading the data (not even any `getxattr` syscall usage on darwin).

- Objective-C example - https://gist.github.com/scottjacksonx/5929155
- `kMDItemWhereFroms` documentation -
 https://developer.apple.com/library/content/documentation/CoreServices/Reference/MetadataAttributesRef/Reference/CommonAttrs.html#//apple_ref/doc/uid/TP40001694-SW1
- CLI example - https://apple.stackexchange.com/questions/110239/where-is-the-where-from-meta-data-stored-when-downloaded-via-chrome#110241

**Comment by andrewkroh** [comment]
@ruflin @MikePaquette We are going to add this metadata to the file information produced by the File Integrity module in Auditbeat. Any suggestions on field naming?

I am thinking `file.origin` and the value will be list of keywords.

**Comment by ruflin** [comment]
@andrewkroh Are the keys always the same (didn't check the doc links above)? Do you plan to make this data searchable or only have it as part of the document? I wonder if you will need to do some cleanup on the keys in case they contains `.` or other things which should not be in a key?

**Comment by andrewkroh** [comment]
The key name is audit.file.origin (it will be just file.origin after I do a rename of all fields). So no cleanup will be required for the keys.

The value is a list of keywords. But we should probably make this data analyzed so I’m thinking to use a multi-field here.

**Comment by ruflin** [comment]
So it would be `file.origin: ["a", "b", ...]` correct?

**Comment by andrewkroh** [comment]
Exactly.

**Comment by andrewkroh** [comment]
Added in #5951
