### ISSUE TITLE
The sample config for Logstash fails

### ISSUE THREAD

**Issue by tsg** [elastic/beats#535]
When trying the sample config given [here](https://www.elastic.co/guide/en/beats/libbeat/current/configuration.html#logstash-output) in the docs with Logstash 2.1.1, I get a deprecation error:

<pre>
Error: The setting `host` in plugin `elasticsearch` is obsolete and is no longer available. Please use the 'hosts' setting instead. You can specify multiple entries separated by comma in 'host:port' format. If you have any questions about this, you are invited to visit https://discuss.elastic.co/c/logstash and ask.
You may be interested in the '--configtest' flag which you can
use to validate logstash's configuration before you choose
to restart a running system.
</pre>

This alternate configuration worked:

<pre>
input {
    beats {
        port => 5044
    }
}

output {
    elasticsearch {
        hosts => ["localhost:9200"]
        index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
        document_type => "%{[@metadata][type]}"
    }
}
</pre>

**Comment by dedemorton** [comment]
@tsg I think you might have used the configuration that is meant for the Elasticsearch 1.5. Notice that the configuration example is introduced by the sentence, "The following Logstash 1.5 configuration file sets Logstash to use the index and document type reported by Beats for indexing events into Elasticsearch."

I can see where someone going through the docs might miss that the configuration is meant for 1.5, though.

So, I'm wondering...do we still need to show the 1.5 configuration? (I guess it depends on which versions we are officially supporting.)

If we do, I can add  a section header or bold text or something to make it clear that the example applies to Elasticsearch 1.5.

**Comment by tsg** [comment]
You are right of course :-)

I'd leave 1.5 there until the next LS major. Sorry for the noise.
