### ISSUE TITLE
No body in HTTP messages (request/response); 'content-type' missing in HTTP header.

### ISSUE THREAD

**Issue by manittrivedi** [elastic/beats#5357]
Please check the issue I have raised in the Elastic Discussion Forum:
https://discuss.elastic.co/t/how-do-i-get-the-actual-content-of-the-http-messages-body/102951

I am running Packetbeat on a remote server running CentOS.
Packetbeat version is `5.6.1`.

Question: How do I get the `http.request.body` and `http.response.body` when there is no `content-type` field in the HTTP message header?

Packetbeat needs the configuration `include_body_for` to distinguish between the type of the body in HTTP messages. How can I get the body regardless if I use the `include_body_for` or not?

Please check the [Related Code Path](https://github.com/elastic/beats/blob/master/packetbeat/protos/http/http.go#L586).

**Comment by xizhimen** [comment]
I have the same needs

**Comment by hmilkovi** [comment]
+1

**Comment by hmilkovi** [comment]
This one can be a big issue due to optional charset encoding in
content type header.

**Comment by adriansr** [comment]
You can get the body without a `content-type` field simply by passing an empty string: `include_body_for: [ "" ]`

Tested it in 6.3
