### ISSUE TITLE
Question: Is it possible to capture PICO process with metricbeat?

### ISSUE THREAD

**Issue by michaelhidalgo** [elastic/beats#5371]
Hi folks,

As described in this blog post ( https://blogs.msdn.microsoft.com/wsl/2016/05/23/pico-process-overview/) and very detailed on the video, and also asked in this thread https://github.com/Microsoft/BashOnWindows/issues/1031, the PICO process does not seem to have many information displayed on common tools like Process Hacker and/or Process Explorer.

At the moment a PICO process looks like this http://i.imgur.com/taJq5bx.png  in common process analysis tools.

Is it possible from Metricbeat to be able to capture those process within the operating system?

At the moment I'm able to see the bash.exe in Microsoft but not other underlaying commands 

<img width="379" alt="screen shot 2017-10-09 at 8 00 07 pm" src="https://user-images.githubusercontent.com/1732035/31366092-9405d8d4-ad2c-11e7-91d6-b02cc99ac566.png">

Also note that if ping command is triggered via a PICO process, it does not show relevant information on standard tools (aka process hacker), so my question is if metricbeat is able to capture those events.

<img width="454" alt="screen shot 2017-10-09 at 8 12 22 pm" src="https://user-images.githubusercontent.com/1732035/31366474-51872a74-ad2e-11e7-98d8-2ff9d36fc29c.png">

**Comment by michaelhidalgo** [comment]
any comments?

**Comment by andrewkroh** [comment]
> Is it possible from Metricbeat to be able to capture those process within the operating system?

Metricbeat is using [NtQueryInformationProcess](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684280%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) to collect the process info so I suspect that it will have the same problems as the other tools.

**Comment by jsoriano** [comment]
@andrewkroh @narph do you think we can do something to monitor these PICO processes?

**Comment by andrewkroh** [comment]
I don't think we can unless Microsoft publishes some details on what APIs and structs to use. I found one project called "pico-toolbox" that did some reverse engineering, but I'd rather not use some undocumented methods.

**Comment by jsoriano** [comment]
Then let's close this issue. Please reopen if some stable and documented API is released.

Thanks!
