### ISSUE TITLE
filebeat add_kubernetes_metadata requires namespace param

### ISSUE THREAD

**Issue by tarasglek** [elastic/beats#5378]
If I deploy filebeat in kubernetes under namespace that is not kube-system, it fails to add kubernetes metadata.

```
    processors:
    - add_kubernetes_metadata:
        namespace: default
```
This should  be set automatically from `/var/run/secrets/kubernetes.io/serviceaccount/namespace`

**Comment by exekias** [comment]
This is what we have been using so far: https://github.com/elastic/beats/blob/master/deploy/kubernetes/filebeat/filebeat-daemonset.yaml#L34-L37, but your idea looks good to me, do you have any link on the docs for this?
