### ISSUE TITLE
packetbeat feature request - support http outbound packets only

### ISSUE THREAD

**Issue by hiroyukki** [elastic/beats#5387]
In some scenes, we can only captured outbound packets due to out-only port mirroring, HTTP request information still useful for behavioural analysis.
Can packetbeat support outbound?

**Comment by andrewkroh** [comment]
We made some changes to Packetbeat since this request was logged. In particular, https://github.com/elastic/beats/pull/6794 changed Packetbeat such that is can report an HTTP response event when it is not matched with the request.
