### ISSUE TITLE
Filebeat json input with tags not supported

### ISSUE THREAD

**Issue by urso** [elastic/beats#5389]
- Version: Any filebeat version supporting JSON input
- Steps to Reproduce: 
  - json input with events having a tags field as array of string
  - add additional tags in filebeat configuration to the events
  - events from configuration file are not applied

Problem is the json parser converts the strings on input to `[]interface{}`, but when adding any new tags, a type check testing for `[]string` is in place only.

**Comment by uschtwill** [comment]
For reference: https://discuss.elastic.co/t/filebeat-tags-not-applied-if-json-event-already-has-a-tags-field/102974
