### ISSUE TITLE
As an atheist I'd prefer '-master', '-control' or '-supervisor' instead of a '-god' process

### ISSUE THREAD

**Issue by marnovdm** [elastic/beats#539]
As an atheist I'd prefer '-master', '-control' or '-supervisor' instead of a '-god' process. Obviously this is not a big deal but I feel it would look more professional.

**Comment by andrewkroh** [comment]
Here is a little background on this. "god" stands for "go daemon" and comes from this project https://github.com/fiorix/go-daemon.

**Comment by marnovdm** [comment]
@andrewkroh thanks for the explanation!
