### ISSUE TITLE
filebeat is not closing the file descriptor incase of file is been removed/rotated with version 5.5 and due to which  disk usage is full

### ISSUE THREAD

**Issue by swethamahesh** [elastic/beats#5391]
filebeat is not closing the file descriptor incase of file is been removed/rotated with version 5.5 and due to which  disk usage is full

 14327    0 lrwx------   1 xxx     xxx           64 Oct 13 13:23 /proc/1079/fd/7 -> /tmp/ffi4PXrM7\ (deleted)
 15953    0 l-wx------   1 xxx    xxx            64 Oct 13 13:23 /proc/1265/fd/3 -> /var/log/temp.log\ (deleted)

my filebeat configuration looks as below:

filebeat.prospectors:
- document_type: log
  encoding: utf-8
  fields: {app_name: xxx, service_name: xxx}
  fields_under_root: true
  input_type: log
  paths: [/var/log/temp.log]
  close_inactive: 1m
  close_renamed: true
  close_removed: true
  clean_older: 1m

kindly please help in understanding how to solve this issue

**Comment by ruflin** [comment]
In general this issue normally appears, if the is back pressure from the Logstash output. Please open a topic on discuss for this as we try to keep Github for confirmed bugs: https://discuss.elastic.co/c/beats/filebeat Happy to help there.

On discuss please share your full filebeat config file, the log files from filebeat, the setup you are using. If your output is putting back pressure on and you still want to close the files, have a look at `close_timeout` which will force close files.

**Comment by swethamahesh** [comment]
Thanks for the inputs Nicolas..

by using close_timeout there could be chances of data being lost.

how shall we over come this problem.

**Comment by ruflin** [comment]
@swethamahesh Please open an topic on Discuss and link this issue as reference with the above mentioned details.

**Comment by swethamahesh** [comment]
i have opened ticket https://discuss.elastic.co/t/filebeat-is-not-closig-the-file-descriptor-once-the-file-is-deleted-renamed/104077
