### ISSUE TITLE
Add IP-addresses and MAC-addresses to event

### ISSUE THREAD

**Issue by hypp** [elastic/beats#5396]
This is a feature request as requested [here](https://discuss.elastic.co/t/add-ip-addresses-and-mac-addresses-to-event/103465/2).

I would like to dynamically add all IP-addresses and all MAC-addresses of the sender host to each event sent by filebeat.

I propose that it is implemented as a new processor similar to add_locale.
Something like:
Loop over net.Interfaces() to get the HardwareAddr field,
skip loopback interfaces,
skip empty HardwareAddr fields,
convert to a string and store them in a list, 
and then event.Put(key, list) to every event. 
And a second inner loop over Interface.Addrs() to get the IP-addresses in a similar way. 

I think that "key" should be user configurable.

If needed I can contribute with the code for this.

**Comment by ruflin** [comment]
Thanks for filing this. I think we still need to figure out where this would fit best in. I could see this as a processor like `add_host_metadata` which probably does more then just ip address and mac address, but for example also fetches the OS. @andrewkroh Other thoughts?

**Comment by omairkhalid20** [comment]
Hi, @ruflin  @andrewkroh  and @hypp  , so has this feature been developed or has been parked for now.

**Comment by ruflin** [comment]
@omairkhalid20 We recently added the `add_host_metadata` processor but by now it does not contain yet the mac address. But this is probably a good time to restart the discussion. 

@hypp @omairkhalid20 Interested in opening a PR against the add_host_metadata processor? That would probably fast track the discussion.

**Comment by hypp** [comment]
Done!
https://github.com/elastic/beats/issues/6867

**Comment by hypp** [comment]
@ruflin I can open a PR for this. Just so I understand correctly: I fork the beats repo, create a new topic branch, make my code changes, and then submit a pull request?

**Comment by ruflin** [comment]
@hypp exactly. On the PR we can then directly discuss if we should have config options for it etc. Feel free to open a PR early.

**Comment by hypp** [comment]
Ok, should be done now. I have never contributed before, so I hope that I got it right?

**Comment by ruflin** [comment]
@hypp Looks great, left some comments on the PR. Let's continue the discussion there.

**Comment by gk4** [comment]
I'm looking for this patch to apply to beats-6.2.2 and/or 6.3  Where can I find it?

**Comment by ruflin** [comment]
It didn't make it into 6.3. For snapshot builds see https://github.com/elastic/beats/pull/6878#issuecomment-387323512

**Comment by q2dg** [comment]
It isn't in Journalbeat 6.7   :-(

**Comment by q2dg** [comment]
It isn't in Journalbeat 7.6 :-(

**Comment by andrewkroh** [comment]
The feature to add IPs and MACs to events has existed since 6.4. It's disabled by default for the add_host_metadata processor. If you set `netinfo.enabled: true` it will be enabled. See the [docs](https://www.elastic.co/guide/en/beats/journalbeat/current/add-host-metadata.html#add-host-metadata). Very recently in https://github.com/elastic/beats/pull/16077 the processor was changed to make `netinfo.enabled: true` the default value.
```
processors:
- add_host_metadata:
    netinfo.enabled: true
```
