### ISSUE TITLE
Unable to get mysql data

### ISSUE THREAD

**Issue by Rafff** [elastic/beats#54]
Hey.
I'm trying to use packetbeat to monitor my LAMP stack activity running on my ubuntu 12.04.4
Unfortunately, I cannot see the mysql data come into the kibana dashboard but I can monitor my http trafic.

First my problem was coming from using sockets instead of the network. But now, even if I can see the mysql network trafic into wireshark/packetbeat -e/tcpdump on 3306 port, it never ends displaying into my kibana dashboard.

While running the "sudo packetbeat -e -c /etc/packetbeat/packetbeat.conf -d mysql,mysqldetailed" command, I can see lines like these :

`mysql.go:115: DBG  MySQL Header: Packet length 91, Seq 0, Type=10
mysql.go:115: DBG  MySQL Header: Packet length 92, Seq 1, Type=141`

That can be followed by others like these (not occuring all the time):

`procs.go:253: ERR  FindSocketsOfPid: Open: open /proc/4945/fd: no such file or directory
procs.go:253: ERR  FindSocketsOfPid: Open: open /proc/13855/fd: no such file or directory`

Do you have any idea how I may solve this ?

Thank you.

**Comment by Akhilesh-Anb** [comment]
Unable to get mysql performance in packetbeat.. im getting http performance.. what is the problem.. please tell me.. Mysql port is 3306

**Comment by tsg** [comment]
@Akhilesh-Anb best way is to create a [trace](https://www.elastic.co/guide/en/beats/packetbeat/current/_recording_a_trace.html) for us (note that those instructions work only for 1.0.0-Beta1) and start a topic on the [forums](https://discuss.elastic.co/c/beats/packetbeat). Feel free to also ask us on IRC (#beats on freenode)
