### ISSUE TITLE
metricbeat - vsphere module config example is wrong

### ISSUE THREAD

**Issue by alextxm** [elastic/beats#5403]
The default file for the vsphere module (modules.d/vsphere.yml.disabled) contains an invalid configuration example:
`metricsets: ["datastore, host, virtualmachine"]`

but this will cause metricbeat to report an invalid metricsets error at startup.
The correct configuration is:

`metricsets: ["datastore", "host", "virtualmachine"]`

Please also note the same error can be found in the official docs at https://www.elastic.co/guide/en/beats/metricbeat/6.0/metricbeat-module-vsphere.html

Tested with metricbeat 6.0.0-rc1 on Windows Server 2008R2.

**Comment by andrewkroh** [comment]
Thanks for the report. If anyone wants to fix contribute a PR this problematic file is [metricbeat/module/vsphere/_meta/config.yml](https://github.com/elastic/beats/blob/65ea8cf4ff50573fc18a9f9224f6e8e37a19fc25/metricbeat/module/vsphere/_meta/config.yml#L2). After editing the file you need to run `make update` from inside the `metricbeat` dir.

**Comment by sitaramshelke** [comment]
Hey, @andrewkroh I can take this if available. Looks pretty straightforward.

**Comment by ruflin** [comment]
@sitaramshelke go for it :-)

**Comment by amandahla** [comment]
Great! I made the correction here too time ago (https://github.com/elastic/beats/pull/4883) but we had problems with Vic :|

**Comment by sitaramshelke** [comment]
Hello @amandahla, I can see changes in the commit. @ruflin So should we have a separate PR just for this change? 
Let me know what you think.

**Comment by ruflin** [comment]
@sitaramshelke I suggest to do a separate PR to get it in quicker.
