### ISSUE TITLE
Packetbeat - Associate a process with generic TCP/UDP flows

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#541]
If Packetbeat is being used to monitor traffic on a single host (rather than consuming a data from a port mirror) it would be nice to associate each flow with a process on that host.

Possible ways to obtain that info:
Windows: [GetExtendedTcpTable](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365928%28v=vs.85%29.aspx) / [GetExtendedUdpTable](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365930%28v=vs.85%29.aspx)

**Comment by tsg** [comment]
If I get it right, we already have this for Linux, with some limitations, see [here](https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-configuration.html#configuration-processes). Marked this as an enhancement for Windows, it might be that this can be implemented easier and more accurate on Windows.

**Comment by monicasarbu** [comment]
+1 It would be great if we can get the process info on windows as well.

**Comment by asekhar** [comment]
+1 not sure if there is a way of "upvoting" on feature requests.

**Comment by andrewkroh** [comment]
This got auto-closed by the PR merging. We still need to make the feature work for flows so I'm reopening it.

// cc: @adriansr

**Comment by andrewkroh** [comment]
This feature will now work with flows on Linux/Windows so closing.

**Comment by adriansr** [comment]
@andrewkroh it's still missing UDP support, which I was planning to implement (process monitor only supported TCP). WDYT?

**Comment by andrewkroh** [comment]
I was doing some testing on Windows. A few comments / questions:

- It looks like there is an escape issue somewhere: `"client_cmdline": "\"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\" ",`.

- Is there a way to enrich all events without specifying a `cmdline_grep`?

**Comment by adriansr** [comment]
@andrewkroh 

* I think it's normal in Windows, when the path contains spaces, to have it enclosed in quotes. The rest is JSON escaping the quotes and the backslash separator. Is that what you mean?
* All events are enriched with the `cmdline` and `client_cmdline`, if possible. The patterns at `packetbeat.procs.monitored` only affect the `proc` and `client_proc` fields. Are you experiencing otherwise? I did all my testing with just: `packetbeat.procs.enabled: true`

**Comment by andrewkroh** [comment]
Yeah, I meant the quotes rather than the JSON escaping. I think we should trim the qoutes. Does Metricbeat’s system process metricset do this too on Windows?

**Comment by andrewkroh** [comment]
Ok, thanks for checking Metricbeat. If Metricbeat does this too then let's leave it alone for now.

With ECS, the cmdline will be become `process.args` which should be indexed as a `[]string`. So then the quoting can go away as each item becomes an element in the array.
