### ISSUE TITLE
Compile import dashboard

### ISSUE THREAD

**Issue by WisdomPill** [elastic/beats#5414]
I'm trying to compile metricbeats on a raspberry pi but I don't get how to create the import dashboard script executable.

I compiled the whole thing, then I created the service and it works, but I'm facing some issues importing the kibana dashboards, I created a simple python script that puts the json files in the folder "/go/src/github.com/elastic/beats/metricbeat/module/system/_meta/kibana/5.x" in the .kibana index.

I see the visualizations but not the dashboards. Is there any way to compile import_dashboards?
I'm asking because on my laptop uing ubuntu 16.04 I find the file in scripts but compiling metricbeats I don't have import_dashboards executable.

To compile I used make in the metricbeats folder.

**Comment by exekias** [comment]
What version of Metricbeat are you using? For master version you can use the tool to import the dashboards for you: Check `make import-dashboards` and `metricbeat setup` subcommand

**Comment by WisdomPill** [comment]
Doesn't work. I used another method to solve my issue.
Correct me if I'm wrong but as I see if you put the modules in the module/system folder filbeat updates the dashboards everytime it starts by default

**Comment by andrewkroh** [comment]
All of the import dashboard logic has been incorporated into the Beat binary now and there is not a separate tool for that.

And we have improved packaging support and you can cross-compile a .deb package targeting linux/arm for your rpi (we have [snapshots for download](https://beats-ci.elastic.co/job/elastic+beats+6.x+multijob-package-linux/gcsObjects/) from Jenkins for testing purposes).

For example, to cross-compile and package for Raspberry Pi you would checkout a release tag and then build the package. This requires Docker for the build process.

```
git checkout v6.4.1
cd metricbeat
PLATFORMS='+all linux/armv7' make package
```
