### ISSUE TITLE
[Filebeat] Customer request: Provide launchd config for running as macOS daemon

### ISSUE THREAD

**Issue by jkelastic** [elastic/beats#5415]
We need official documentation on how to setup Filebeat daemon on OSX.

I saw a customer use plist in the post below to setup a Filebeat daemon on OSX.

https://discuss.elastic.co/t/deploying-filebeat-on-macos-x/37785/11

What need ES best practice and official support steps in achieving a OSX launch-able daemon.

**Comment by andrewkroh** [comment]
We should provide the launchd config to enable running as a daemon and then document how to apply that config. So first we need to develop and test launchd config (and account for the agent starting before the networking is up and before the hostname has been set).

**Comment by dedemorton** [comment]
Changed the title to reflect the need to provide launchd config instead of documentation. When the config is available, we'll add docs for it.
