### ISSUE TITLE
Document backoff setting

### ISSUE THREAD

**Issue by urso** [elastic/beats#5419]
Output Backoff parameters have become configurable. Add missing settings to docs:

- [ ] Logstash [backoff settings](https://github.com/elastic/beats/blob/master/libbeat/outputs/logstash/config.go#L23)

Note: check all outputs expose backoff settings

**Comment by dedemorton** [comment]
@urso It looks like these settings aren't shown in the reference.yml files. Do we still want to document these? Looks like Logstash, Elasticsearch, and Kafka all have backoff settings. I can help add the content to the docs, but I don't see the options in the reference.yml.

**Comment by ruflin** [comment]
We should also add them to the reference file if they are missing.

**Comment by urso** [comment]
Checking the code, we have different backoff behavior/config per output.

Elasticsearch/Logstash have `backoff.init` and `backoff.max` settings. Both employ exponential backoff, with `init` (default=1s) being the initial waiting time and max (default=60s) being the max waiting time.

The kafka backoff setting is available regarding the meta-data update only. Setting is `output.kafka.metadata.retry.backoff`. Unfortunately the client doesn't always handle backoff correctly. This needs to be resolved.

Checking the redis output, we don't have any backoff settings in here.

If backoff settings are missing from reference.yml, they should be added as well. Anyways, backoff behavior needs some overhaul, so we can guarantee same settings/semantics for all outputs.

**Comment by urso** [comment]
I created issue: #6791

For now let's add only Elasticsearch and Logstash to the reference configs only.

**Comment by dedemorton** [comment]
I've added the backoff settings for the ES and LS outputs here: https://github.com/elastic/beats/issues/5419.
