### ISSUE TITLE
Unify the Auditbeat Event Schema

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#5423]
In order to make it possible to correlate data produced by one module with data from another module we need to ensure that a common set of field names is used by all modules (e.g. common data like user ID should be called `uid` rather than `audit.kernel.uid` and `audit.file.uid`).

I'd like to review the field names and make changes where possible.

**Comment by ruflin** [comment]
WDYT of instead of using a global `uid` having `user.id`? Or could we put `uid` under `unix` namespace as uid is pretty unix typical: `unix.uid`. I kind of like `uid` as a name as it's very common but would prefer not to have it in the global namespace. `gid` would fit in the same bucket.

**Comment by andrewkroh** [comment]
I like the notion of group all the user related info under `user`. I think `user.id` would work. And on *nix this is the UID and on Windows this is the SID.

**Comment by andrewkroh** [comment]
I started a [spreadsheet](https://docs.google.com/spreadsheets/d/1BtSnAT4sZmGUeddz4Bes1E8iEGLxHXyb8LIXylZ-jK8/edit#gid=1592309553) to map out some possible field renames.

**Comment by ruflin** [comment]
@andrewkroh With https://github.com/elastic/beats/pull/5995 I'm not sure if this is completed or if this was only the first step.

**Comment by andrewkroh** [comment]
That was only half of it. I'm working on changes to the auditd data.
