### ISSUE TITLE
How to put custom json logs to filebeat and also keep source format

### ISSUE THREAD

**Issue by artemus717** [elastic/beats#5450]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version: 5.6.3
- Operating System:CentOS 
- Steps to Reproduce: 

I  want to tranport nginx logs in json format using filebeat , but all logs goes into message part , i want to keep them in top level .

Tried several ways , but nothing help. 

My Log Format:
{ "kong_id":"-","time_local":"26/Oct/2017:22:22:36 +0800","remote_addr":"10.42.174.255","http_forward_for":"-","cache_status":"-","request_referer":"-","request_user_agent":"curl/7.29.0","request_body":"-","request_sequence":"82447","request_url":"http://auth.pgc/","request_method":"GET","request_time":"0.033s","respons_status":"500" }

What filebeat output:
{"@timestamp":"2017-10-26T14:16:38.561Z","beat":{"hostname":"4050c3322b6c","name":"filebeat","version":"5.6.3"},"input_type":"log","message":"{ \"kong_id\":\"-\",\"time_local\":\"26/Oct/2017:22:16:38 +0800\",\"remote_addr\":\"10.42.174.255\",\"http_forward_for\":\"-\",\"cache_status\":\"-\",\"request_referer\":\"-\",\"request_user_agent\":\"curl/7.29.0\",\"request_body\":\"-\",\"request_sequence\":\"81699\",\"request_url\":\"http://auth.pgc/\",\"request_method\":\"GET\",\"request_time\":\"0.031s\",\"respons_status\":\"500\" }","offset":608065,"source":"/log/auth.2017-10-26.log","tags":["pgc"],"type":"log"}

**Comment by andrewkroh** [comment]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

Hint: https://www.elastic.co/guide/en/beats/filebeat/5.6/configuration-filebeat-options.html#config-json
