### ISSUE TITLE
Add a Make task for building the Docker image

### ISSUE THREAD

**Issue by eherot** [elastic/beats#5454]
Specifically the image on the public docker hub (e.g. docker.elastic.co/beats/metricbeat:6.0.0-rc1)

Something basically like this:
```bash
cd beats/metricbeat
make docker
```
so that I could then do
```
docker run newly_built_image:latest setup --dashboard
```
and then also add documentation about it to the [setting up your dev environment docs](https://www.elastic.co/guide/en/beats/devguide/current/beats-contributing.html#setting-up-dev-environment).

**Comment by ph** [comment]
The `mage package` command in each directory will now build the docker images, from what I see we cannot just build the docker images but you can restrict the platforms to `linux/amd64` using the following:

`PLATFORMS=linux/amd64 mage package`

Concerning adding the documentations to the dev environment I do not think it's necessary for now and it will be a bit harder to maintain.
