### ISSUE TITLE
Adjust CSV version of the notice file

### ISSUE THREAD

**Issue by tsg** [elastic/beats#5463]
We've already got `./dev-tools/generate_notice.py --csv`, which generates a CSV version of the NOTICE file. This ticket is about adjusting the output to match a common format that will be shared across the stack:

* name: dependency name
* version: dependency version
* revision: VCS commit hash. optional if the version is defined.
* url: dependency URL (website, github repository…)
* license: the license SPDX short identifier (ie: MIT, Apache-2.0…) The full list is available on spdx.org website
* copyright: authorship, company... (optional)

Example:

```
"name","version","url","license","copyright"
"go-winio","v0.4.5","https://github.com/Microsoft/go-winio","MIT","Microsoft"
"gopsutil","v2.17.09","https://github.com/shirou/gopsutil","BSD 3-clause","WAKAYAMA Shirou"
```

**Comment by liketic** [comment]
I can take this.
