### ISSUE TITLE
Issue with Metricbeat - Displaying units( like MB, GB or %) for filesystem data

### ISSUE THREAD

**Issue by get2arun** [elastic/beats#5464]
Having running ELK with metricbeat in Redhat server. I have 2 ELK setup for test and prod. In one environment, seeing the units for filesystem used, total and pct fields. In the second environment, not seeing the units. 
Also, I have open the discussion
https://discuss.elastic.co/t/metricbeat-filesystem-usage-setting-in-units/105572 

I have installed below ELK stack.
elasticsearch-5.0.1-1.noarch
logstash-5.0.1-1.noarch
kibana-5.0.1-1.x86_64
metricbeat-5.2.2-1.x86_64

 Env-01
 # system.filesystem.free        199.999GB
 # system.filesystem.free_files           7,402,970
 t system.filesystem.mount_point           /var/opt
 # system.filesystem.total           199.102GB
 # system.filesystem.used.bytes          1.374GB
 # system.filesystem.used.pct         1.24%
 t type          metricsets
  
Env-02
 # system.filesystem.free         186,999,999
 # system.filesystem.free_files           63,956
 t system.filesystem.mount_point           /var/opt
 # system.filesystem.total          249,699,759
 # system.filesystem.used.bytes          62,699,040
 # system.filesystem.used.pct           0.251
 t type         metricsets

Any work around for this issue? please suggest.

**Comment by andrewkroh** [comment]
Please do not cross-post questions. We try to reserve Github for confirmed bugs and enhancement requests.
