### ISSUE TITLE
Feature request: add option to not check for truncated file

### ISSUE THREAD

**Issue by akking** [elastic/beats#5465]
We are tailing logs from Windows shares mounted on the our Linux box. I know it's not recommended but we can't do anything on the Windows boxes. We have issue related to "File was truncated. Begin reading file from offset 0" but we can guarantee it's not the case. 
We tried many remedies but none of them works flawlessly. After deleting the [code](https://github.com/elastic/beats/blob/master/filebeat/prospector/log/log.go#L116-L121) related to check for truncated file we are running smoothly 24x7.
I think our case is not unique so I added this feature request and if the user guarantees the file never get truncated, it is safe to do that. Thank you.

**Comment by ruflin** [comment]
The above probably means the size reported by the shared file system is cached somehow and is not reported correctly as it's already outdated. It would be great if Filebeat would be able to not read from the cache. @andrewkroh I remember we discussed something like this in the past?

**Comment by ruflin** [comment]
@akking It would probably not be too hard to introduce a configuration option to disable it. But I would prefer not to have a config option and solve the problem in an other way as this does not solve the actual problem that Filebeat receives wrong information.
