### ISSUE TITLE
Add Amazon Elasticsearch support to Elasticsearch output

### ISSUE THREAD

**Issue by s12v** [elastic/beats#5467]
We're trying to use filebeats to ship logs directly to our Elasticsearch running as a service in AWS.
AWS requires each request to be signed with security credentials.

Please have a look at PR https://github.com/elastic/beats/pull/5466

**Comment by exekias** [comment]
Closing this one. After the conversation in https://github.com/elastic/beats/pull/5466#issuecomment-340450460
