### ISSUE TITLE
Support http status phrase in Metricbeat Http module

### ISSUE THREAD

**Issue by christiangalsterer** [elastic/beats#5470]
Add support for HTTP status phrase in addition to HTTP status code using the same naming as in Packetbeat HTTP module

**Comment by christiangalsterer** [comment]
Add support for HTTP status phrase in addition to HTTP status code using the same naming as in Packetbeat HTTP module

**Comment by liketic** [comment]
Hi @exekias I wan to take this. Where should I get start from ? thanks!

**Comment by exekias** [comment]
Great! Have a look to https://github.com/elastic/beats/blob/master/metricbeat/module/http/json/json.go, events are built there from HTTP responses :) You will want to add status phrase from the HTTP Response object https://golang.org/src/net/http/response.go

Ping me if you need help :)
