### ISSUE TITLE
6.x has different post-install script from 6.0

### ISSUE THREAD

**Issue by tsg** [elastic/beats#5477]
It looks like in the 6.x branch we no longer have this [post-install script](https://github.com/elastic/beats/blob/6.0/dev-tools/packer/platforms/debian/run.sh.j2#L10-L12). Instead, I think FPM generates default post-install/pre-rm scripts that cause the apm-server 6.0 to behave slightly different from MB/FB 6.0. In particular, apm-server starts automatically when installed, while the Beats don't.

Opening this to further investigate the issue. cc @ruflin

**Comment by tsg** [comment]
The change seems to have happened in https://github.com/elastic/beats/pull/5086

**Comment by ruflin** [comment]
@tsg Anything I can help here with? Not sure what the status is.

**Comment by tsg** [comment]
Initially I thought that you did the change when integrating APM, but turns out it wasn't you. So nothing for you to do.
