### ISSUE TITLE
Metricbeat returns incorrect, or misleading, disk usage percentage on linux filesystems

### ISSUE THREAD

**Issue by hogarthj** [elastic/beats#5494]
Details posted to discuss before filing the bug as required:

https://discuss.elastic.co/t/bug-incorrect-disk-usage-statistics/103207

For confirmed bugs, please report:
- Version: 5.6.0 
- Operating System: RHEL 6.8.z 
- Steps to Reproduce:  
  * Check the values returned on a system in system.filesystem.used.pct 
  * Compare to df on a target system
  * Observe the 5% difference (by default on ext4... may be different on other filesystems dependent on implementation and configuration of reserved space)

**Comment by troelsh** [comment]
I can confirm this:

* Metricbeat version
* OS: Ubuntu 16.04.2 @ Kernel 4.4.0-31-generic

df -h shows 74% usage on root /
Metricbeat (system.filesystem.used.pct) shows 69% free

**Comment by andrewkroh** [comment]
I opened #6231 to address this issue. Once this is merged it would be great if you all could test the [snapshot build](https://s3-us-west-2.amazonaws.com/beats-package-snapshots/index.html?prefix=metricbeat/) and verify the `system.filesystem.used.pct` values against `df`.

**Comment by troelsh** [comment]
@andrewkroh i will try and get some time to testing this. As i normally use the packaged versions i will have to setup a test env for this so might take some time before i can test.
