### ISSUE TITLE
Doc links broken in packaged version of README.md files

### ISSUE THREAD

**Issue by robbavey** [elastic/beats#5497]
The README.md file packaged inside beats distributions has broken links to the elastic documentation - the minor version of the documentation branch is being stripped out for 6.0 downloads - eg   `https://www.elastic.co/guide/en/beats/filebeat/6/filebeat-getting-started.html`.

For example, the README.md file from https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.0.0-rc2-darwin-x86_64.tar.gz reads:

```
# Welcome to filebeat 6.0.0-rc2

Filebeat sends log files to Logstash or directly to Elasticsearch.

## Getting Started

To get started with filebeat, you need to set up Elasticsearch on your localhost first. After that, start filebeat with:

     ./filebeat -c filebeat.yml -e

This will start the beat and send the data to your Elasticsearch instance. To load the dashboards for filebeat into Kibana, run:

    ./filebeat setup -e

For further steps visit the [Getting started](https://www.elastic.co/guide/en/beats/filebeat/6/filebeat-getting-started.html) guide.

## Documentation

Visit [Elastic.co Docs](https://www.elastic.co/guide/en/beats/filebeat/6/index.html) for the full filebeat documentation.

## Release notes

https://www.elastic.co/guide/en/beats/libbeat/6/release-notes-6.0.0-rc2.html

```

This appears to be across different beats, and different platforms - [packetbeat for Linux](https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-6.0.0-rc2-linux-x86_64.tar.gz)  exhibits the same behaviour, for example.

**Comment by dedemorton** [comment]
I'm closing this issue because it's old and fixed in later versions. However, because I goofed awhile back ago and didn't set up all the redirects that were required, I have opened a [request ](https://github.com/elastic/website-www.elastic.co/issues/2428) against the website to have redirects set up just in case someone has an old version installed somewhere.
