### ISSUE TITLE
Remove POD_NAMESPACE setting from kubernetes manifests

### ISSUE THREAD

**Issue by exekias** [elastic/beats#5501]
It's no longer needed since #5482 autodetects it, we can now remove POD_NAMESPACE env var, and `namespace` key under config: https://github.com/elastic/beats/blob/master/deploy/kubernetes/filebeat/filebeat-daemonset.yaml#L34

**Comment by liketic** [comment]
Hi @exekias So we need to remove POD_NAMESPACE and `metadata.namespace` in kubernetes module? Thanks!

**Comment by exekias** [comment]
No need to update code on this one, this is about testing this still works after removing these lines https://github.com/elastic/beats/blob/f122937db5c2f77299b88684b93abe054f12bc1e/deploy/kubernetes/filebeat/filebeat-daemonset.yaml#L38-L41

I was planning to do this in the following days :smile:

**Comment by palash25** [comment]
Is anyone working on this? If not then I would like to take this up.

**Comment by exekias** [comment]
Thank you for volunteering @palash25! I'm afraid I did the job some time ago, but forgot to update this issue :disappointed:

This was fixed by #5963, thank you for bringing this up, I think we can close it now
