### ISSUE TITLE
how to load the customized filebeat module in filebeat?

### ISSUE THREAD

**Issue by qingweiqm** [elastic/beats#5514]
hi, all

I have build a customized filebeat module by following the guide on https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-modules-devguide.html#filebeat-modules-devguide, after I setup all the files on fileset, how to using my own module in filebeat, just copy the directory to the filebeat directory which filebeat has been installed, then using it in filebeat.yml.
Am I understanding it right or wrong.
Any input is appreciated.

**Comment by qingweiqm** [comment]
or I need to build the beat from source with my own module fileset ?
can someone show me some doc if I need to go this way.
Many thanks!

**Comment by qingweiqm** [comment]
I excute the make on the filebeat source directory, and then I got an filebeat binary file, should I just replace the filebeat on existing installed filebeat environment, and modify the filebeat.yml ?

**Comment by ruflin** [comment]
For filebeat modules you don't need to rebuild it from source. As soon as it is in the right directory path you should be able to use it from the config file. I'm closing this issue as we would like to keep Github for confirmed bugs and enhancement requests. Please open a discuss topic here: https://discuss.elastic.co/c/beats/filebeat Can you also share there the config your are using trying to load it?
