### ISSUE TITLE
[libbeat] Support certificate revocation via OCSP in outputs

### ISSUE THREAD

**Issue by 9nativ** [elastic/beats#5519]
We are using Filebeat (version 5.4.2) to ship our customer's logs to logstash servers and we are testing the process of server certificate revocation.

While beats is using the golang TLS stack, CLR/OCSP seems not to be available out of the box.

Can we ask to support the implementation for OCSP validation?

**Comment by sagarkal** [comment]
Hi,

We need this feature too

**Comment by sagarkal** [comment]
Is there a plan to address this anytime sooner?

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
