### ISSUE TITLE
Write only once into log for services with no uptime

### ISSUE THREAD

**Issue by martinscholz83** [elastic/beats#5528]
Actually the new windows service metricset writes a logging entry for every fetch if the uptime for a service is not available. This can happens if metricbeat is not running with specific privileges. To avoid blow up the log, it would be a good idea to cache the services and log only once if the the uptime is not available.
```golang
var protectedServices = make(map[string]struct{})
...
...
//Get uptime for service
	if ServiceState(rawService.ServiceStatusProcess.DwCurrentState) != ServiceStopped {
		processUpTime, err := getServiceUptime(rawService.ServiceStatusProcess.DwProcessId)
		if err != nil {
			s := strings.ToLower(service.ServiceName)
			if _, ok := protectedServices[s]; !ok {
				protectedServices[s] = struct{}{}
				logp.Warn("Uptime for service %v is not available", service.ServiceName)
			}
		}
		service.Uptime = processUpTime / time.Millisecond
	}
...
```

**Comment by martinscholz83** [comment]
@andrewkroh, can you take look on this.

**Comment by andrewkroh** [comment]
I like the idea of squelching this message when the reason is permissions. So I think it should check the error code before ignoring the problem.

I would rather `protectedServices` not be stored as a global, but as a per instance variable.

**Comment by martinscholz83** [comment]
You get an wrapped error code. So its hard to say why it failed. See [here](https://github.com/elastic/beats/blob/master/vendor/github.com/elastic/gosigar/sigar_windows.go#L333)

**Comment by andrewkroh** [comment]
That’s what errors.Cause is for. https://godoc.org/github.com/pkg/errors#Cause
