### ISSUE TITLE
Add option to import specific dashboards

### ISSUE THREAD

**Issue by alepuccetti** [elastic/beats#5538]
Running `scripts/import_dashboards` imports all the available visualization, dashboard, and search. It would be useful to be able to specify which dashboard the user wants to import because not everyone uses all the dashboards but often only a subset.

**Comment by SMMAN** [comment]
Sample dashboards are a good idea and it makes sense to offer them. But: if you just want to show a few of them (either: e.g. only metricbeats or: specific ones of one type) then it makes no sense to do it as it is done right now.

- Beats / dashboards / related objects get more and more from version (minor / major) to version.
- you have dead stuff in your system that noone needs - this goes against my / our housekeeping policy
- visibility for our customers is a nitghtmare. Keep in mind: there can be already quite some dashboards / objects made by internal customers as well

The wish is just to pick that objects /dashboards I or the internal customer need. You could do it by offering a list with checkboxes. But of course you could also still say: I want them all.

**Comment by willemdh** [comment]
Totally agree the way ot works now is not optimal.  Dashboards provided by Elastic and the community should be accessible and selectable from Kibana imho.

**Comment by mgoritzk** [comment]
+1

**Comment by jsoriano** [comment]
Hey,

I think we can close this. In general the use case of installing specific resources related to specific services is going to be solved by the [Fleet](https://www.elastic.co/guide/en/kibana/current/fleet.html) project and [integrations](https://github.com/elastic/integrations). In the future, Elastic packages or integrations could be also a way to distribute community contributed dashboards or other resources (actually the repository is already open for contributions :slightly_smiling_face: ).

In the meantime, for Beats, even if not very optimal, there are some ways to install specific dashboards using `metricbeat setup --dashboards`. For example with `-E setup.dashboards.directory=directory/with/dashboards` one can install a subset of dashboards in a directory.
There are some other options to configure dashboards setup that can be found here: https://www.elastic.co/guide/en/beats/metricbeat/7.13/configuration-dashboards.html.
