### ISSUE TITLE
close_renamed is no effect in dockers with log archive

### ISSUE THREAD

**Issue by ZhiqinYang** [elastic/beats#5546]
In extreme conditions ， inode not release and disk use up !
I'am run docker with follow comand:
/usr/bin/dockerd  --graph=/var/lib/docker --log-opt max-size=1024m --log-opt max-file=2
i products log 5w/s , and when docker acrchive log i found that the inode not release

**Comment by ruflin** [comment]
Can you please open a topic on discuss with this? https://discuss.elastic.co/c/beats/filebeat We try to keep Github for confirmed bugs and feature enhancmenents.

Please share on discuss your config, filebeat version and logs of filebeat if possible. Best put it into a gist. Also some more details about your setup would be useful.

**Comment by ZhiqinYang** [comment]
@ruflin  
thank you! I made a topic https://discuss.elastic.co/t/filebeat-not-release-inode/107265, could you help me!
