### ISSUE TITLE
suggestion on optimization

### ISSUE THREAD

**Issue by ZhiqinYang** [elastic/beats#5547]
func (s *State) IsEqual(c *State) bool {
     // return s.ID() == c.ID()
      return (s.FileStateOS.Inode == c.FileStateOS.Inode && s.FileStateOS.Device == c.FileStateOS.Device)
  }
s.Id not init at begin lead to every time need to excute s.FileStateOS.String()

**Comment by ruflin** [comment]
Can you share some more details here?  The current code checks if the id is already set. If yet it directly returns. So `String` is only called once.

```
// ID returns a unique id for the state as a string
func (s *State) ID() string {
	// Generate id on first request. This is needed as id is not set when converting back from json
	if s.Id == "" {
		s.Id = s.FileStateOS.String()
	}
	return s.Id
}

// IsEqual compares the state to an other state supporing stringer based on the unique string
func (s *State) IsEqual(c *State) bool {
	return s.ID() == c.ID()
}
```

**Comment by ZhiqinYang** [comment]
@ruflin 
327 func (h *Harvester) sendEvent(data *util.Data) bool {
  328     if h.source.HasState() {
  329         h.states.Update(data.GetState())
  330     }
  331     err := h.forwarder.Send(data)
  332     return err == nil
  333 }
data.GetState() is value copy  , s.Id no init , each time would do s.Id = s.FileStateOS.String()

**Comment by ruflin** [comment]
The above code would make it work only for Linux and not Windows. Did you hit any performance issues with the current code? Happy to do such a change if needed but we should add some benchmarks to it then to compare it.

**Comment by ZhiqinYang** [comment]
I used it in Linux. and you ignored that in Harvester the stats in source id is "", data.GetState() is only value copy, id always is "", so each time would execute  follow:  
     s.Id = s.FileStateOS.String()

**Comment by ruflin** [comment]
@ZhiqinYang As mentioned before, you are right about the execution each time. I'm open for a PR if it also takes changes on other platforms into account. It would be good to have a quick benchmark test with it to confirm the performance improvement.

**Comment by ZhiqinYang** [comment]
thank you very much

**Comment by andrewkroh** [comment]
Some changes were made in #6323 so this may be moot. If we want to discuss further I suggest opening a PR with a benchmark test so we can discuss the impact quantitatively.
