### ISSUE TITLE
Metricbeat system - More disk metrics

### ISSUE THREAD

**Issue by brandonmensing** [elastic/beats#5555]
Enhancement to add more metrics to the system module in Metricbeat for disks:

- Disk queue
- Number of pending read/write requests

**Comment by andrewkroh** [comment]
In master we have some new metrics that are similar to what iostat provides. See https://github.com/elastic/beats/pull/4648/files. Are these the metrics you want?

**Comment by robin13** [comment]
Yes!  Thank you. :)
