### ISSUE TITLE
Example Kubernetes Filebeat configuration should consider log re-shipping

### ISSUE THREAD

**Issue by jstangroome** [elastic/beats#5557]
The Filebeat DaemonSet uses an `emptyDir` volume as the backing storage for `/usr/share/filebeat/data`:
https://github.com/elastic/beats/blob/8ae5b4be36462d3c8dfd97c4f900ff2964b71352/deploy/kubernetes/filebeat/filebeat-daemonset.yaml#L75-L76

If the running Filebeat DaemonSet Pod is re-created by Kubernetes due to a Pod failure or because the DaemonSet is updated to refer to a new point release of the Filebeat Docker image or because the Elasticsearch password environment variable is changed, then the `emptyDir` volume will be destroyed and re-created as empty for the new Filebeat process.

This will discard the Filebeat registry which was tracking which files, and which lines, had already been shipped and will result in the new Filebeat process re-shipping all the existing log data.

Consider using a `hostPath` volume for the Filebeat data directory to address this.

**Comment by exekias** [comment]
Thank you for your feedback!, I agree, we need persistent storage for the registry. `hostPath` sounds good to me, we will need to figure out a safe path for it.

**Comment by jstangroome** [comment]
@exekias a safe path for cluster environments may be difficult. I would have initially suggested using the same hostPath as the path used inside the Filebeat Docker image but I know that won't work on at least two Kubernetes platforms:

* [minikube](https://github.com/kubernetes/minikube/blob/master/docs/persistent_volumes.md) dedicates `/data/` on the host for persistent data.
* Google Container Engine nodes running the recommended [Container OS](https://cloud.google.com/container-optimized-os/docs/resources/faq#are_there_persistent_writable_directories_in_container-optimized_os) have a mostly read-only disk with only `/mnt/stateful_partition/` and home directories available for persistence.

**Comment by exekias** [comment]
Yes, I think we cannot do this change without a safe path that will work for any deploy. In the mid-term we may have external storage backends for filebeat data `registry`, but until then, we can either:

 * Find a safe path that works everywhere
 * Update docs to explain how to use `hostPath` to store filebeat data

**Comment by ruflin** [comment]
We should definitively start with option 2 in the list and also explain a bit the problem on why there is no default path (at the moment).

**Comment by exekias** [comment]
This was done here: https://github.com/elastic/beats/pull/7437
