### ISSUE TITLE
Clarify documentation about indexers and matchers

### ISSUE THREAD

**Issue by exekias** [elastic/beats#5566]
We could clarify `add_kubernetes_metadata` indexers and matchers functionality: https://www.elastic.co/guide/en/beats/filebeat/6.0/add-kubernetes-metadata.html

Indexers extract pod metadata from kubernetes events and store it in a map in memory
Matchers process beat events and enrich them with metadata from the in-memory map

We should try to avoid indexing related words to avoid confusion with ES indexing, as this is totally unrelated

**Comment by huskerdhf** [comment]
I would suggest expanding the scope of the documentation updates to also include:

- Document the available indexers and matchers
- For each beat, document the default indexer(s) and matcher(s)
- Document how to configure each indexer and matcher

I'm currently trying to get the add_kubernetes_metadata feature working with our Metricbeat deployment (without any luck yet) and having this type of documentation would be very helpful. At this point I'm having to dig through the beats code to try and understand all of this information which clearly is not the most efficient means for a user to find out how to use a feature.

**Comment by offero** [comment]
It's 2021 and it's still confusing
