### ISSUE TITLE
Failing perfmon test

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#5571]
The following test failed on Jenkins today: `perfmon.TestWildcardQuery`. See https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-windows/2022/beat=metricbeat,label=windows/testReport/junit/(root)/perfmon/TestWildcardQuery/ One of the reasons could be that this is a fresh windows installation and all follow up builds will pass (just an assumption). I opened a Github issue for it to better track it and mention @maddin2016 on it :-)

Here is the full content from Jenkins:

```
Error Message

Failed
Stacktrace

assertions.go:225: 
Error Trace:	pdh_integration_windows_test.go:280
	
Error:		Should NOT be empty, but was 0
	
pdh_integration_windows_test.go:282: [{"processor":{"name":"_Total","time":{"pct":0}}} {"processor":{"name":"0,_Total","time":{"pct":0}}} {"processor":{"name":"0,0","time":{"pct":0}}} {"processor":{"name":"0,1","time":{"pct":0}}} {"processor":{"name":"0,2","time":{"pct":0.09760464026645765}}} {"processor":{"name":"0,3","time":{"pct":0}}}]
```

**Comment by maddin2016** [comment]
@ruflin, thanks for track this issue. From the description of this counter
>%Processor Time is the percentage of elapsed time that the processor spends to execute a non-Idle thread.

So maybe it's not a good idea to check if one of the instances is not `0`. Maybe we just should check if the key `processor.time.pct` for `_Total` instance is present.
```
pctKey, err := values[0].HasKey("processor.time.pct")
	if err != nil {
		t.Fatal(err)
	}

	assert.True(t, pctKey)
```

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/beats/pull/5607 was merged. @maddin2016 Thanks.
