### ISSUE TITLE
Packetbeat can't show Client locations

### ISSUE THREAD

**Issue by Howard-Chang** [elastic/beats#5576]
I installed Packetbeat, but the Client locations didn't show anything only the map.
![image](https://user-images.githubusercontent.com/19474557/32772718-b69afe28-c961-11e7-8192-c26edea0ebfb.png)

thank you in advance.

**Comment by ruflin** [comment]
Hi @Howard-Chang 

Please open an issue on discuss with your question: https://discuss.elastic.co/c/beats/packetbeat We try to keep Github for bugs and feature requests.

On discuss please share your config, packetbeat version, more details on your setup and packetbeat log files.
