### ISSUE TITLE
CI test should check for doc links that point to current

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#5585]
Links to documentation should never be coded to point to a the current branch because those links sometimes break when we switch versions for a new release (causing a lot of last-minute thrashing to clean up the broken links before we can publish the docs).

We can avoid this problem in some instances by testing for links that point to the `current` docs. The build for a PR should fail if the docs contains such links.

So we should never have links to our internal docs that looks like this:

https://www.elastic.co/guide/en/elasticsearch/reference/current/setup.html

Instead, the links should use an asciidoc attribute to resolve the path.

**Comment by dedemorton** [comment]
Talking to Clint et al about adding the check to the doc build itself. But maybe we would still want it as a check on the PR...because it avoids a broken build. I think it's worth having.

**Comment by ruflin** [comment]
@dedemorton I'm curious how they will implement it. Perhaps we can then just reuse the code.

**Comment by dedemorton** [comment]
I'm closing this for now because we are looking into other build software that will alleviate some of the pain involved with resolving build errors.
