### ISSUE TITLE
Heartbeat monitor SSL settings docs

### ISSUE THREAD

**Issue by urso** [elastic/beats#5599]
The SSL settings on monitors do not point to the general SSL/TLS settings as available for outputs. That is, not all available SSL settings are available from docs.

See: https://discuss.elastic.co/t/client-certificate/107617

**Comment by exekias** [comment]
Related to https://github.com/elastic/beats/issues/4268, I guess it should be documented in a common place?

**Comment by dedemorton** [comment]
There are some links, but maybe it's not obvious that the links point to info about additional settings. Also the topic "Specify SSL settings" should show an example of setting ssl options on monitors.
