### ISSUE TITLE
Add service trigger info to Windows Service metricset

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#5601]
It would be useful to know if a Windows service with an Automatic startup type is started by a trigger. This would allow a user to more accurately alert when a service is stopped but it is supposed be started automatically. The reason you need to know about triggers is so you can ignore stopped services that can started by a trigger at a later time.

In services.msc it displays "Automatic (Trigger State)". It would be nice to have this added to our `windows.service.start_type` field.

<img width="1250" alt="services-msc" src="https://user-images.githubusercontent.com/4565752/32851075-fc4dd51c-ca01-11e7-997b-ed588c48418c.png">

In the dashboard below I'm trying to show services that are stopped but are supposed to be running. I want to filter out the "Remote Registry" service because it is started automatically as needed.

<img width="1990" alt="windows-service-dashboard" src="https://user-images.githubusercontent.com/4565752/32851082-0008259a-ca02-11e7-8aa2-5327fa831479.png">

**Comment by maddin2016** [comment]
We get this from [QueryConfig2](https://msdn.microsoft.com/de-de/library/windows/desktop/ms684935(v=vs.85).aspx). We could add a new helper function `getOptionalInfo`. There we check for `SERVICE_CONFIG_TRIGGER_INFO` and then maybe override the start type if the service has a trigger configured.

**Comment by maddin2016** [comment]
BTW we should do the same for `Automatic (Delayd Start)`.

**Comment by maddin2016** [comment]
@andrewkroh, are working on this? Otherwise i can open PR.

**Comment by andrewkroh** [comment]
That would be great! I'm not working on it. I was just playing with the metricset and trying to envision some different use cases for it.

**Comment by maddin2016** [comment]
What would you choose. `Automatic_Triggered` or `Automatic (Triggered)`

**Comment by andrewkroh** [comment]
I like `Automatic (Triggered)`.

**Comment by maddin2016** [comment]
My favorite too :+1:

**Comment by maddin2016** [comment]
There also services that are automatic delayed and triggered

![image](https://user-images.githubusercontent.com/19551763/32939580-454abfa8-cb80-11e7-97d6-a4b5bc2e8acc.png)

For them i would prefer `Automatic (Triggered, Delayed)`
