### ISSUE TITLE
Feature: Generate bash autocomplete for subcommands

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#5617]
I'd ~like~ love to have a way to generate an bash or zsh autocomplete file for the beat's sub-commands.

Maybe we could install this for all users with our .deb and .rpm packages too.

**Comment by exekias** [comment]
We already have this implemented for bash in all beats, just run: `<beat> completion bash`, that subcommand is hidden as it's not minded for end users but packaging. 

We still have to add zsh support and make use of this from the packaging

**Comment by andrewkroh** [comment]
Awesome. I didn't know about that.

**Comment by ph** [comment]
@exekias 
What do you meant by `from the packaging`, Is there any other project packaging doing that?

**Comment by ph** [comment]
@andrewkroh support fo zsh is in https://github.com/elastic/beats/pull/5761, I am not too familiar with the packaging.

**Comment by exekias** [comment]
I mean generate autocompletion files during packaging and add them to the resulting package so both bash and zsh use it if when you install from deb/rpm
