### ISSUE TITLE
Packetbeat:  Feature request - add the pid to the exported fields

### ISSUE THREAD

**Issue by hamelg** [elastic/beats#562]
In the environmental packetbeat fields, we have the proc field.
proc >> the name of the process that served the transaction.

It would be very useful to add the pid.
We collect http protocol and we have hundreds apache/php processes on each server. Each process does outbound connections to mysql databases and others remote HTTP webservices. Having the pid, would allow us to identify and follow connections by apache process.
should it be possible to add this field ?

**Comment by joedissmeyer** [comment]
This is a feature that we would very much like as well!

**Comment by andrewkroh** [comment]
`process.pid`, `client.process.pid`, and `server.process.pid` were added as part of the ECS migration effort in https://github.com/elastic/beats/pull/9303.
