### ISSUE TITLE
add thrift and redis protocol support to heartbeat

### ISSUE THREAD

**Issue by jiangzhileaf** [elastic/beats#5636]
it would be useful to add thrift and redis protocol support to heartbeat,
so we easy to check whether the service is alive.

**redis**
now i can use the heartbeat to ping the redis through the tcp protocol，
send："ping\r\n"
receive: "+PONG"

it would be easy to add redis protocol to slimpify the config.

**thrift**
i try to ping my simple thrift interface through the tcp protocol,
but it doesn't work because of the yaml config problem.
[https://discuss.elastic.co/t/try-to-use-heartbeat-to-ping-thrift-interface/108106/2](url)

**Comment by andrewvc** [comment]
I don't think this fits with our current vision for uptime, so we're going to close this for now. If that changes, we may revive it. Thank you for opening this issue however.
