### ISSUE TITLE
schema.go:41: ERR Error on field 'server_uptime': Missing field: server_uptime, Error: Key `ServerUptimeSeconds` not found

### ISSUE THREAD

**Issue by binary64** [elastic/beats#5637]
18/11/2017 12:51:492017/11/18 12:51:49.692005 schema.go:41: ERR Error on field 'server_uptime': Missing field: server_uptime, Error: Key `ServerUptimeSeconds` not found
18/11/2017 12:51:492017/11/18 12:51:49.692028 schema.go:41: ERR Error on field 'user': Missing field: user, Error: Key `CPUUser` not found
18/11/2017 12:51:492017/11/18 12:51:49.692037 schema.go:41: ERR Error on field 'system': Missing field: system, Error: Key `CPUSystem` not found
18/11/2017 12:51:492017/11/18 12:51:49.692044 schema.go:41: ERR Error on field 'children_user': Missing field: children_user, Error: Key `CPUChildrenUser` not found
18/11/2017 12:51:492017/11/18 12:51:49.692051 schema.go:41: ERR Error on field 'children_system': Missing field: children_system, Error: Key `CPUChildrenSystem` not found

My `server-status?auto` looks like this:-

```

Total Accesses: 65
Total kBytes: 52
CPULoad: .00496689
Uptime: 604
ReqPerSec: .107616
BytesPerSec: 88.1589
BytesPerReq: 819.2
BusyWorkers: 2
IdleWorkers: 5
Scoreboard: __W___K...............................................................................................................................................

```

Apache Version | Apache/2.4.10 (Debian)

**Comment by ruflin** [comment]
This is interesting as we use `2.4.20` Docker container for testing. Which version of debian is this? How did you install apache? I wonder why here for example `ServerUptimeSeconds` is missing. 

I remember we had a discussion about making some more fields optional in apache in an issue but I couldn't find it :-(

**Comment by ruflin** [comment]
@radoondas Pinging you on this one, perhaps you know more?

**Comment by binary64** [comment]
I used `FROM php:7.1-apache` and `RUN a2enmod status`

**Comment by ruflin** [comment]
@binary64 Thanks for the info. That is pretty useful. I wonder what the difference is between the version in the `httpd` Docker container and the one shipped with php. Do you know any details here?

**Comment by ruflin** [comment]
@jsoriano Closing this as https://github.com/elastic/beats/pull/6450 is merged and should resolve this issue.
