### ISSUE TITLE
Build after clone source from github fails

### ISSUE THREAD

**Issue by dlasrado** [elastic/beats#5644]
If the local source is empty, the build script clones the code from Github. But the source code is copied to a wrong folder which causes build_before to fail during docker run.
The code should be copied to github.com/elastic rather than github.com/elastic/beats
(Line 57 in dev-tools/packer/docker/xgo_image/base/build.sh)

**Comment by ruflin** [comment]
Linking the PR here: https://github.com/elastic/beats/pull/5645

**Comment by andrewkroh** [comment]
We have completely refactored how packaging is done since this was opened. I suggest giving the latest a try.
