### ISSUE TITLE
Old Red Hat panic in starting filebeats

### ISSUE THREAD

**Issue by antoniotvr** [elastic/beats#5650]
I'm on Red Hat 4 (Red Hat Enterprise Linux AS release 4 (Nahant Update 6))

I've just installed filebeat version 6.0.0 but when I try to start service I obtain the following error:

/etc/init.d/filebeat start
Starting filebeat: panic: open /dev/urandom: function not implemented

goroutine 1 [running]:
github.com/elastic/beats/vendor/github.com/satori/go%2euuid.safeRandom(0xa514000, 0x10, 0x10)
        /go/src/github.com/elastic/beats/vendor/github.com/satori/go.uuid/uuid.go:115 +0x6c
github.com/elastic/beats/vendor/github.com/satori/go%2euuid.NewV4(0x0, 0x0)
        /go/src/github.com/elastic/beats/vendor/github.com/satori/go.uuid/uuid.go:457 +0x68
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.newDyn(0x0, 0x0, 0x0, 0x0, 0x0, 0x1dd5280, 0xa490f60, 0x0)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/types.go:170 +0x48
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.newRef(0x0, 0x0, 0x0, 0x0, 0x0, 0xa490f60, 0x0)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/types.go:162 +0x69
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.normalizeString(0x0, 0x0, 0x0, 0x0, 0xa4ac380, 0x1606dbf, 0xc, 0xa41a240, 0x1de6c40, 0xa490ea0, ...)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/merge.go:430 +0x335
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.normalizeValue(0xa4ac380, 0xa40000, 0x0, 0x0, 0x0, 0x0, 0x149f960, 0xa4147d0, 0x94, 0x149f960, ...)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/merge.go:392 +0xf5d
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.normalizeSetField(0xa490ea0, 0xa4ac380, 0x0, 0x1600f5b, 0x6, 0x149f960, 0xa4147d0, 0x94, 0x94, 0x0)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/merge.go:280 +0xaf
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.normalizeMapInto(0xa490ea0, 0xa4ac380, 0x14b8f80, 0xa490db0, 0x15, 0xa4a3880, 0xb16849)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/merge.go:216 +0x21b
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.normalizeMap(0xa4ac380, 0x14b8f80, 0xa490db0, 0x15, 0xa4a38f8, 0xa3bbae, 0xa4a3910)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/merge.go:198 +0xfc
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.normalizeMapValue(0xa4ac380, 0x0, 0x0, 0x0, 0x0, 0x14b8f80, 0xa490db0, 0x15, 0xa9c584, 0x1e9ef60, ...)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/merge.go:319 +0x5c
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.normalizeValue(0xa4ac380, 0xa40000, 0x0, 0x0, 0x0, 0x0, 0x149f960, 0xa480f20, 0x94, 0x149f960, ...)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/merge.go:396 +0xb84
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.normalizeSetField(0xa490e70, 0xa4ac380, 0x0, 0x15ff5d8, 0x4, 0x149f960, 0xa480f20, 0x94, 0x94, 0x30)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/merge.go:280 +0xaf
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.normalizeMapInto(0xa490e70, 0xa4ac380, 0x14b8f80, 0xa490de0, 0x15, 0xd3a6bc, 0x15)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/merge.go:216 +0x21b
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.normalizeMap(0xa4ac380, 0x14b8f80, 0xa490de0, 0x15, 0x14b8f01, 0x15, 0x8)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/merge.go:198 +0xfc
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.normalize(0xa4ac380, 0x14b8f80, 0xa490de0, 0xa4ac380, 0x1509420, 0xa49f01)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/merge.go:168 +0x475
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.(*Config).Merge(0xa490e10, 0x14b8f80, 0xa490de0, 0x1e9e950, 0x3, 0x3, 0x501034d2169129f8, 0xa4a3e20)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/merge.go:62 +0x78
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg.NewFrom(0x14b8f80, 0xa490de0, 0x1e9e950, 0x3, 0x3, 0xa494f28, 0x186b6100, 0xa490de0)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/ucfg.go:74 +0xef
github.com/elastic/beats/libbeat/common.NewConfigFrom(0x14b8f80, 0xa490de0, 0x1db54d0, 0xa4a3eb8, 0xa480f00)
        /go/src/github.com/elastic/beats/libbeat/common/config.go:80 +0x59
github.com/elastic/beats/libbeat/cfgfile.mustNewConfigFrom(0x14b8f80, 0xa490de0, 0xa4a3e98)
        /go/src/github.com/elastic/beats/libbeat/cfgfile/cfgfile.go:50 +0x35
github.com/elastic/beats/libbeat/cfgfile.init()
        /go/src/github.com/elastic/beats/libbeat/cfgfile/cfgfile.go:30 +0x7f3
github.com/elastic/beats/filebeat/cmd.init()
        /go/src/github.com/elastic/beats/filebeat/cmd/root.go:30 +0x53
main.init()
        /go/src/github.com/elastic/beats/filebeat/main.go:22 +0x49

It is possible to solve this issue or I have to use an earlier release of filebeat for this machine?

Thank you

**Comment by andrewkroh** [comment]
Beat are written in Go. Go supports RHEL 6+. Therefore I wouldn't expect any of the Beats to work on your version of RHEL. See the [support matrix](https://www.elastic.co/support/matrix).

**Comment by antoniotvr** [comment]
Thank you, I miss that page.

You can close the issue, I will update this machine in next months so we
can use beats also on this machine.

Thank you
