### ISSUE TITLE
Missing mention of `module/{module}/module.yml` file in the developper guide

### ISSUE THREAD

**Issue by ph** [elastic/beats#5658]
When developing module we have to create a `module.yml` file inside the root of the module, this file helps when using the export_dashboards program (-yml option)

I don't see mention of it in the [documentation](https://www.elastic.co/guide/en/beats/devguide/6.0/filebeat-modules-devguide.html)

Depends on: #5657, the tooling need to take care of generate the file before updating the doc.

**Comment by dedemorton** [comment]
We do document the module.yml file [here](https://www.elastic.co/guide/en/beats/devguide/current/export-dashboards.html). Do we just need to update [Creating a new Filebeat module](https://www.elastic.co/guide/en/beats/devguide/6.0/filebeat-modules-devguide.html) to show that the yml file needs to be created when the module is developed?

**Comment by kvch** [comment]
`module.yml` is generated now when a module is generated along with sample dashboard names. But it would be nice to indicate that dashboard names might be modified in the file, if a user provides a different name for the exported object.
