### ISSUE TITLE
add support for condition on bool type

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/beats#5659]
Currently

[Doc](https://www.elastic.co/guide/en/beats/packetbeat/current/defining-processors.html#condition-equals) does not support `bool` type.
```
With the equals condition, you can compare if a field has a certain value. The condition accepts only an integer or a string value.
```

When I did so, I got this warning packetbeat.

```
2017/11/21 01:10:50.019224 condition.go:235: WARN unexpected type bool in equals condition as it accepts only integers and strings. 
```

**Comment by ewgRa** [comment]
This problem looks like duplicate of #4637, probably one of them can be closed in favor of another.

Merged PR #5954 looks like solution for both issues.
