### ISSUE TITLE
Clarify documentation around reloading configs

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#5676]
For users who land on this page directly https://www.elastic.co/guide/en/beats/filebeat/6.0/_live_reloading.html via search or google search on reloading, it will be helpful to clarify that live reloading _only_ works on externally configured files (https://www.elastic.co/guide/en/beats/filebeat/6.0/filebeat-configuration-reloading.html#filebeat-configuration-reloading) and does not work on the main filebeat config file (eg. /etc/filebeat/filebeat.yml) itself.

Also, we are beginning to see users who are switching from a single filebeat config file into multiple ones to make use of the reloading feature, except that it is common for copy and paste to end up producing something like the following:

```
filebeat.prospectors:
  - type: log
... and so on
```

Instead of the expected
```
  - type: log
... and so on
```

It will be helpful to create a warning box on this page (https://www.elastic.co/guide/en/beats/filebeat/6.0/filebeat-configuration-reloading.html) to remind the users that the definitions in these externally config files must start with `-type:` always without the filebeat.prospectors: or filebeat.modules lines.

**Comment by dedemorton** [comment]
Closing because this was fixed in #6046
