### ISSUE TITLE
Import dashboards can create duplicated index patterns

### ISSUE THREAD

**Issue by ismael-hasan** [elastic/beats#5683]
The import dashboard functionality (https://www.elastic.co/guide/en/beats/filebeat/5.6/filebeat-index-pattern.html) does not seem to check if a pattern with the same title exists already. 

To reproduce it

1. Create some filebeat indices
2. Manually create in Kibana the `filebeat-*` pattern 
3. Run the tool in the link to create the Filebeats dashboards
4. There are 2 index patterns defined in Kibana with the same title (different IDs, of course)

When we create an index pattern via the Kibana UI it checks if the same title already exists; it would be good to have the same behavior when importing dashboards in Beats, to prevent having duplicated index patterns.

**Comment by ruflin** [comment]
@simianhacker Perhaps you can comment here? How is the behaviour when loaded through Kibana in 6.x?

**Comment by simianhacker** [comment]
This is due to the new unique id system that Kibana implemented for all saved objects. There needs to be a way to check if the index pattern exists (from Beats) before importing the new index pattern. Currently the only way it will override is if the id match.
