### ISSUE TITLE
Minor typos + issue in yml files for the beats

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#569]
A couple of minor issues that I noticed in passing while I was looking at the config files.

issue 1:
Says "top topbeat" instead of "to topbeat":
    # Optional index name. The default index name depends on the each beat.
    # For Packetbeat, the default is set to packetbeat, for Topbeat
    # top topbeat and for Filebeat to filebeat.
    #index: beatname

issue 2:
For the rotate_every_kb description, we should show the default value in kilobytes, not MB, since the user is expected to specify the value in kb:
    # Maximum size in kilobytes of each file. When this size is reached, the files are
    # rotated. The default value is 10 MB.
    #rotate_every_kb: 10000

**Comment by andrewkroh** [comment]
Fixed in #1129
