### ISSUE TITLE
Heartbeat ports exported as string

### ISSUE THREAD

**Issue by urso** [elastic/beats#5696]
Just noticed port numbers in the json document exported by heartbeat are string, not numbers. See sample output from event refactoring: https://github.com/elastic/beats/pull/4091

The fields.yml file already configures the port number to be an integer.

**Comment by ruflin** [comment]
I just tested this on master and it seems to be integer there now. Must be a change between 5.x and 6.x where we fixed this?

The initial thread where this popped up: https://discuss.elastic.co/t/what-type-is-the-port-field-in-heartbeat-output/108586/11

**Comment by andrewvc** [comment]
Given that it's fixed in 6.x I'm going to close this since 5.x isn't supported.
