### ISSUE TITLE
Typo in Metricbeat golang/heap metricset

### ISSUE THREAD

**Issue by mountkin** [elastic/beats#5703]
optained -> obtained
https://github.com/elastic/beats/blob/554701f0a04fe25229be4afd6cccd745f2844860/metricbeat/module/golang/heap/_meta/fields.yml#L86

**Comment by ruflin** [comment]
@mountkin Looks like it. We must also change it in the code. Want to open a PR?

**Comment by mountkin** [comment]
@ruflin Opened PR #5716
