### ISSUE TITLE
Inconsistent behavior of `make check` locally and on travis.

### ISSUE THREAD

**Issue by ph** [elastic/beats#5704]
This was found with #5691, this problems does not seems to be triggered on the CI, only on my local environment when I run make check, I am running go 1.9.2.

```
Checking file template/config.go
Checking file template/load.go
Checking file template/processor.go
Checking file template/template.go
Checking file template/processor_test.go
template/processor_test.go:141: github.com/elastic/beats/libbeat/common.DynamicType composite literal uses unkeyed fields
template/processor_test.go:147: github.com/elastic/beats/libbeat/common.DynamicType composite literal uses unkeyed fields
template/processor_test.go:153: github.com/elastic/beats/libbeat/common.DynamicType composite literal uses unkeyed fields
Checking file template/template_test.go
exit status 1
```

When I run 1.7.2 locally `make check` doesn't raise that error. The current theory is either:

- Make check on travis doesn't use the 1.9.2 version.
- Some caching occur?

**Comment by ruflin** [comment]
@ph What is your local OS?

**Comment by ph** [comment]
@ruflin high sierra, 10.13.1.

**Comment by andrewkroh** [comment]
I don't believe we have this problem anymore, but I'm not sure how it was resolved.
