### ISSUE TITLE
Cache values missing in Memory Usage [Metricbeat System] Visualization

### ISSUE THREAD

**Issue by ajpahl1008** [elastic/beats#5706]
- Version: 6.0.0
- Operating System: Ubuntu Linux 17.10

- Steps to Reproduce: 
 
   Setting up the default metricbeat via -setup argument, the graph for Memory usage shows 0.0B of cache used.  The operating system's "free" and "nmon" show significant usage (~18GB). 

<img width="1344" alt="brokengraph" src="https://user-images.githubusercontent.com/842456/33214847-912e9c7a-d0fb-11e7-8bf1-7d880b1c89c2.png">
<img width="607" alt="free_output" src="https://user-images.githubusercontent.com/842456/33214867-97f5b674-d0fb-11e7-8131-31904e2fe5d3.png">
<img width="570" alt="nmon_output" src="https://user-images.githubusercontent.com/842456/33214869-9a4b3c28-d0fb-11e7-9e27-9eaabac0582b.png">

To see cache I modified the aggregation in the cache series 
from
    system.memory.actual.used bytes
to
    system.memory.actual.free

<img width="1343" alt="config_change_made" src="https://user-images.githubusercontent.com/842456/33214888-a46708a4-d0fb-11e7-9098-fbfabfd04d41.png">

And I could begin to see cache statistics in the graph.

<img width="1340" alt="fixedgraph" src="https://user-images.githubusercontent.com/842456/33214852-94531214-d0fb-11e7-859d-099612b5881d.png">

**Comment by ajpahl1008** [comment]
**Created branch** 
https://github.com/elastic/beats/tree/metricbeats_cache_fix

Going to attempt to test it locally before putting a merge request in.

**Comment by ruflin** [comment]
Not sure if that could also be related? https://github.com/elastic/gosigar/pull/82

**Comment by andrewkroh** [comment]
This appears to have been fixed since this was opened. This was taken from a Metricbeat 6.3.1 env.

<img width="769" alt="screen shot 2018-09-18 at 6 49 29 pm" src="https://user-images.githubusercontent.com/4565752/45720809-a2194b80-bb73-11e8-8fb0-9953979b0074.png">
