### ISSUE TITLE
New protocol support: DB2

### ISSUE THREAD

**Issue by MingchunZhao** [elastic/beats#571]
Created from discussion here : 
https://discuss.elastic.co/t/packetbeat-support-for-db2-database/27886

**Comment by skundrik** [comment]
DB2 uses DRDA protocol so it would also cover `Informix` and `Apache Derby`. `Oracle` supposedly supports it as well.

**Comment by MingchunZhao** [comment]
Start working on this issue. 
Attached a trace file which traced DRDA dataflows exchanged between application requester and DB2 server.
[db2drdat.txt](https://github.com/elastic/beats/files/107778/db2drdat.txt)

**Comment by salyh** [comment]
not yet production ready but its a beginning (contributions welcome) https://github.com/salyh/beats/tree/drda/

**Comment by urso** [comment]
@salyh there has been some restructuring in packetbeat (See #1101) to simplify protocol plugin generation and registration. If you plan to have your change merged, check out #1101 for required changes (move config to protocol local `config.go` file, have 'New' function to initialize plugin and import module in packetbeat/main.go). Docs update is still pending (See #1111)

I started a cookiecutter template for new TCP based protocols: https://github.com/urso/packetbeat-tcp-generator.

**Comment by salyh** [comment]
done https://github.com/elastic/beats/pull/1118

**Comment by elvarb** [comment]
It's mentioned here that it's possibly used by Oracle, does anyone know for sure?

**Comment by tsg** [comment]
@elvarb from what I know, Oracle uses primarely another protocol (TNS). It might be that it's possible to use it with Oracle, but I don't think it's being usually used.
