### ISSUE TITLE
Flaky Logstash node_stats tests

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#5712]
Currently the Logstash node_stats test is flaky. It faily with the following error:

```
--- FAIL: TestFetch (2.74s)
	Error Trace:	node_stats_integration_test.go:21
	Error:		Received unexpected error "HTTP error 500 in node_stats: 500 Internal Server Error"
		
FAIL
```

Interestingly the `node` integration tests pass consistently without issue, meaning LS is running fine.  I wonder under which circumstances node_stats returns a 500. As it can't be reproduced manually I assume it's kind of a timing issue that `node_stats` is not ready or similar. Unfortunately there are no LS logs here for now.

This is running against Logstash master.

@elastic/logstash Any hints are appreciated here.

**Comment by ruflin** [comment]
Perhaps related to this: When the node_stats metricset does not return a 500, sometimes it fails with:

```
ERR Error on field \'in\': Missing field: in, Error: Expected integer, found <nil>
```

This means the `out` and `filtered` fields are available but the `in` field is not available yet. We can make this field optional on the MB side but it would be good to know if this is expected.

**Comment by original-brownbear** [comment]
@ruflin the `500` is a result of https://github.com/elastic/logstash/issues/8004, the missing fields (that should really only ever happen for a split second though and not very frequently) are too.

**Comment by ruflin** [comment]
@original-brownbear Thanks for having a look at this. Looks like I need to update the LS healthcheck. If I get a 200 for _node/stats will also go the missing `in` part away? Or are the two not related?

**Comment by original-brownbear** [comment]
@ruflin best to update the health check, those two are related and not necessarily gonna go away anytime soon :(

**Comment by ruflin** [comment]
@original-brownbear I updated the health check here: https://github.com/elastic/beats/commit/29678a06d2ebb6d8cf64e2ec31e051e3099272f9 Lets see if that fixes the issue.
