### ISSUE TITLE
Which properties are normalized?

### ISSUE THREAD

**Issue by danielserrao** [elastic/beats#5719]
Hi,

I have been looking to documentation to understand if some cpu properties are normalized or not. What I mean is if it can go only up to 100% (cores average/normalized) or more than 100% (cores sum).

For example, is not clear for me if the property system.cpu.idle.pct is normalized or not. If it isn't, there is another property that I can use to fetch the normalized version?

The metric beat version that we are using is 5.6.

Thanks for any help.

**Comment by andrewkroh** [comment]
Those values are not normalized. The comment on [system.cpu.user.pct](https://www.elastic.co/guide/en/beats/metricbeat/5.6/exported-fields-system.html#_system_cpu_user_pct) applies to all of the `system.cpu.*.pct` fields.

In 6.0 there are [system.cpu.*.norm.pct](https://www.elastic.co/guide/en/beats/metricbeat/6.0/exported-fields-system.html#_cpu_fields_7) values that are normalized. You need to enable them [via configuration](https://www.elastic.co/guide/en/beats/metricbeat/6.0/metricbeat-metricset-system-cpu.html#_configuration_3).
