### ISSUE TITLE
Convert 6.x dashboards to 5.x

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#5720]
These are dashboards that need to be converted to 5.x. The process for doing so is to import them into 5.6 via the Kibana API and then export them using the export_dashboards.py script that gets the data from the `.kibana` index.

- [ ] Metricbeat - windows/service
- [x] Auditbeat - all
- [ ] Packetbeat - tls #5722

**Comment by andrewkroh** [comment]
This is blocked by https://github.com/elastic/beats/issues/6090.

**Comment by exekias** [comment]
I guess we are not longing doing this as 7.0 is out
