### ISSUE TITLE
Packetbeat.yml with_vlans cannot work?

### ISSUE THREAD

**Issue by stefansaye** [elastic/beats#5730]
Hello there,
I will greatly appreciate help in making packetbeats work.
I  have add the option "with_vlans" , but still  not show vlan in my document
How do I enable the option to packetbeat with_vlans?

my packetbeat version:
packetbeat version 5.5.2, libbeat 5.5.2 

I have the following configuration.

    packetbeat.interfaces.device: eth0
    packetbeat.interfaces.snaplen: 1514
    packetbeat.interfaces.type: af_packet
    packetbeat.interfaces.buffer_size_mb: 100
    packetbeat.interfaces.with_vlans: true
    #================================== Flows =====================================
    #Set `enabled: false` or comment out all options to disable flows reporting.
    packetbeat.flows:
    #Set network flow timeout. Flow is killed if no packet is received before being
    # timed out.
    timeout: 30s
    # Configure reporting period. If set to -1, only killed flows will be reported
    period: -1s
    .............

Can you help?

**Comment by andrewkroh** [comment]
Cross-posted: https://discuss.elastic.co/t/packetbeat-yml-with-vlans-cannot-work/109340
