### ISSUE TITLE
Can't package beats: error while generating package.yml

### ISSUE THREAD

**Issue by xy795** [elastic/beats#5753]
When running make package, the process always fails with message
`Failed to parse standard input: yaml: line 10: did not find expected key`
`make[1]: *** [../libbeat/scripts/Makefile:404: prepare-package-cgo] Error 1`
`make[1]: Leaving directory '/home/amarquis/code/go/beats/metricbeat'`
`make: *** [../libbeat/scripts/Makefile:456: package] Error 2`

Seems like the call of sed (dev-tools/packer/xgo-scripts/before_build.sh:58) is the reason for this issue, cause it alters the line 
`:doc_branch:  "master"`
to
`:doc_branch "m" aster`
of the package.yml in {BEAT_PATH}/build

Should be (?)
`:doc_branch: "m"`

**Comment by exekias** [comment]
I think this is a regression from https://github.com/elastic/beats/pull/5727/files, I didn't realize `master` was an option
