### ISSUE TITLE
Filter out docker filesystems in Metricbeat fsstat module

### ISSUE THREAD

**Issue by vkurup** [elastic/beats#5767]
Please see the [discussion](https://discuss.elastic.co/t/metricbeat-fsstat-values-are-too-high/107453) for more details.

In short, I am running docker on a host and the fsstat module reports filesystem size values that are about 10 times too high, because it seems to be counting docker aufs mount points in addition to the host filesystem. There are options to filter out these entries using the filesystem module, but not for the fsstat module.

For confirmed bugs, please report:
- Version: 5.6
- Operating System: Ubuntu 16.04

**Comment by ruflin** [comment]
@vkurup Thanks for opening the issue. I change the title a bit as I think this is a feature request to make it possible to filter out the docker filesystems.
