### ISSUE TITLE
docs/configuration.asciidoc.fields_under_root

### ISSUE THREAD

**Issue by EamonZhang** [elastic/beats#580]
document say : If the custom field names conflict with other field names added by Filebeat, the custom fields overwrite the other fields.
but the field 'request' in fields does not overwrite the field with same name .
my test below
----config filebeats.yml
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    -
      paths:
        - /var/log/nginx/pro_access.log
      input_type: log
      fields:
          level: debug
          review: 1
          request: new_field_request
      fields_under_root: true

------------logstash result
                     "count" => 1,
                "input_type" => "log",
                     "level" => "debug",
                    "offset" => 22615,
                   "request" => [
        [0] "new_field_request",
        [1] "POST /test\" HTTP/1.1"
    ],
                    "review" => "1",
                    "source" => "/var/log/nginx/pro_access.log",
                      "type" => "log",

**Comment by monicasarbu** [comment]
Filebeat doesn't export any `request` field by default. [Here](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields.html) is the list of the exported fields. In this case, the `request` field is added to the exported fields. I tested your Filebeat configuration on my computer and Filebeat exports:
<pre>
{
  "@timestamp": "2015-12-22T16:42:47.722Z",
  "beat": {
    "hostname": "mar",
    "name": "mar"
  },
  "count": 1,
  "input_type": "log",
  "level": "debug",
  "message": "dsh frsf kefjwre jkewj e",
  "offset": 0,
  "request": "new_field_request",
  "review": "1",
  "source": "/tmp/log/1.log",
  "type": "log"
}
</pre>

**Comment by EamonZhang** [comment]
@monicasarbu Thank you for your attention，
from you field 'message', I know I does't describe clearly！
my message like this.
"message" => "127.0.0.1 | - | 23/Dec/2015:09:04:30 +0800 | POST /test HTTP/1.1 | 200 | 51 | - | curl/7.35.0 | - | 0.000 | application/json | - | {\\x22some2\\x22:{\\x22foo\\x22:\\x22bar\\x22,\\x22a\\x22:3\\x22}}"

logstash config
```javascript
filter{
  ruby {
        init => "@kname = ['remote_addr','remote_user','time_local','request','status','body_bytes_sent','http_referer','http_user_agent','http_x_forwarded_for','request_time','content_type','upstream_response_time','request_body']"
        code => "event.append(Hash[@kname.zip(event['message'].split(' | '))])"
  }
```

there are two fields named 'request',one is defined at filebeats and the other is defined at logstash.
overwrite , i can't understand. 

Sorry . My english is poor!

**Comment by ruflin** [comment]
@EamonZhang What we are referring to in the docs with "it will overwrite is", that in case for example `offset` is also defined in the fields, it would overwrite the existing offset on the root level. 

If I understand your issue correctly, you are doing some filters in LS which also have request field and you would expect it to overwrite the field from filebeat? The first question here is why you then use fields_under_root if it should be overwritten anyways? Second, this sounds more like a Logstash issue then Filebeat. If this is the case, I recommend to post your question here: https://discuss.elastic.co/c/logstash

**Comment by ruflin** [comment]
Closing this issue as no updates recently. In case the issue persists, please open a topic under https://discuss.elastic.co/c/beats/filebeat
