### ISSUE TITLE
Winlogbeat 6.0.0 Resending event logs after service restart

### ISSUE THREAD

**Issue by krasekhi** [elastic/beats#5814]
For confirmed bugs, please report:
- Version: Winlogbeat 6.0.0
- Operating System: Windows 10
- Steps to Reproduce: 

**Logstash output**
if [event_id] == 4624 {
		elasticsearch {
        hosts => [ "localhost:9200" ]
		index => "last_logon"
		document_id => "%{computer_name}"
    }
}

- Install Winlogbeat with the following config 
    winlogbeat.event_logs:
      - name: Security
        event_id: 4624
- Monitor registry file ProgramData\winlogbeat\.winlogbeat.yml
- Start Service winlogbeat 
- Wait for event logs to finish sending - note .winlogbeat.yml recorded last record sent
- restart winlogbeat service
- Notice .winlogbeat.yml record_number resets
- Continue to refresh last_logon index - notice its resending the event logs already sent.

reference : https://discuss.elastic.co/t/winlogbeat-6-0-0-registry-file/110384

**Comment by andrewkroh** [comment]
This was fixed in 6.1.0. https://github.com/elastic/beats/issues/5813
