### ISSUE TITLE
Build fails on FreeBSD 

### ISSUE THREAD

**Issue by jalaluddeen** [elastic/beats#583]
getting this error when I run  the command go get -t ./...

github.com/elastic/beats/filebeat/harvester

harvester/encoding.go:23: cannot use utf8Encoding literal (type utf8Encoding) as type encoding.Encoding in map value:
utf8Encoding does not implement encoding.Encoding (wrong type for NewDecoder method)
have NewDecoder() transform.Transformer
want NewDecoder() *encoding.Decoder
harvester/encoding.go:24: cannot use utf8Encoding literal (type utf8Encoding) as type encoding.Encoding in map value:
utf8Encoding does not implement encoding.Encoding (wrong type for NewDecoder method)
have NewDecoder() transform.Transformer
want NewDecoder() *encoding.Decoder
harvester/encoding.go:25: cannot use utf8Encoding literal (type utf8Encoding) as type encoding.Encoding in map value:
utf8Encoding does not implement encoding.Encoding (wrong type for NewDecoder method)
have NewDecoder() transform.Transformer
want NewDecoder() *encoding.Decoder

**Comment by monicasarbu** [comment]
Filebeat should work on FreeBSD 8-STABLE or later, it might be a problem with the encoding. @urso is the expert here.

**Comment by andrewkroh** [comment]
We use the [Go 1.5 Vendor Experiment](https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit) so you must `export GO15VENDOREXPERIMENT=1` before doing any building. Try that instead of fetching the dependencies yourself.

If you use our Makefiles this is done for you.

**Comment by andrewkroh** [comment]
If you don't care about building and just want a binary for FreeBSD you can download a binary built by our Jenkins server from [here](https://beats-nightlies.s3.amazonaws.com/index.html?prefix=jenkins/filebeat/). The directory format is {jenkins build number}-{git commit hash} (watch out because the directory listing on that page isn't sorted nicely).

**Comment by jalaluddeen** [comment]
Thanks!, I was able to get it working using the binary

**Comment by mahkorayem** [comment]
I tried to install it on FreeBSD
FreeBSD SERVERNAME 10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25 02:10:02 UTC 2016     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

Downloaded from https://beats-nightlies.s3.amazonaws.com/index.html?prefix=jenkins/filebeat/1318-e288cf6548dc929aa93718367da7dbd966095c0c/

`pkg add filebeat-freebsd-amd64`
And I got this


```
pkg: archive_read_open_filename(filebeat-freebsd-amd64): Unrecognized archive format

Failed to install the following 1 package(s): filebeat-freebsd-amd64
```

**Comment by mahkorayem** [comment]
Sorry I just found it is just an executable !

nice, thanks
