### ISSUE TITLE
Define an official set of labels/annotations to do autodiscovery

### ISSUE THREAD

**Issue by exekias** [elastic/beats#5837]
Both for the Docker & Kubernetes use case, define a set of well-known labels (Docker) and annotations (Kubernetes, [example](https://kubernetes.io/docs/reference/labels-annotations-taints/)) that we can understand and do autodiscover on.

The goal is to let the maintainer of the container, or the person deploying it a way of telling us how to monitor it. For example:
 `co.elastic.filebeat.module`: `nginx`
 `co.elastic.filebeat.multiline.pattern`: `^\[`
 ...

This issue aims to both define the initial set of labels and implement their usage from autodiscover

**Comment by ruflin** [comment]
That is a very interesting idea. I wonder if in the above we could leave out the `beat` name and automatically detect if there is a log specific config it would be turned on (like multiline above). If it has `co.elastic.module: nginx` by default Metricbeat and Filebeat are triggered. Now writing it I realised that it would be great if both options would work.

For Metricbeat, would it get the hostname and port out of the meta information?

Perhaps @vjsamuel has also some ideas / inputs here?

**Comment by vjsamuel** [comment]
collectbeat does it as:
```
io.collectbeat.logs/pattern: ^\[
io.collectbeat.metrics/type: prometheus
io.collectbeat.metrics/endpoints: ":8080/metrics"
io.collectbeat.metrics/namespace: "foobar"
```
it is mandatory that we come up with a good convention to discovery logs and metrics and our annotations need to be namespaced like above.

**Comment by ruflin** [comment]
@vjsamuel Does the `/` have some special meaning that you use it over a `.` for example?

To get started I think it's easier that we are specific by using the specific beat name as @exekias suggested but looking forward it would be great to just say get me everything form container x that you can fetch (logs, metrics, ...).

**Comment by exekias** [comment]
Closing this as the change went in already
