### ISSUE TITLE
filebeat: silently dies when Configfile is broken.

### ISSUE THREAD

**Issue by C0RD** [elastic/beats#585]
Hello,

I accidently added a TAB-Character in my Configfile. When running filebeat with it it silently dies. 

Config-Example: (I put &lt;TAB&gt; in it)

filebeat:
  prospectors:
  -
    paths:
      -&lt;TAB&gt;/var/log/squid/access_log
    type: log

filebeat should interpret whitespace-characters as spaces. (or produce some kind of meainingful error)

**Comment by andrewkroh** [comment]
We are working providing better configuration parsing and validation. Follow at https://github.com/elastic/beats/issues/657

The error for the [tab character in the YAML file](http://www.yaml.org/faq.html) was probably routed to the default logging destination which is syslog. Adding `-e` to the filebeat arguments will route the log stderr. But that's not very intuitive.
