### ISSUE TITLE
Unable to create filebeat-* index in kibana after running filebeat

### ISSUE THREAD

**Issue by blacktop** [elastic/beats#5851]
For confirmed bugs, please report:
- Version: 6.0.1
- Operating System: Alpine Docker via OSX
- Steps to Reproduce:  https://github.com/elastic/examples/tree/master/Common%20Data%20Formats/nginx_logs

I believe this is related to this: https://github.com/elastic/kibana/issues/15110

and more specifically this might be the cause? https://github.com/elastic/kibana/issues/15110#issuecomment-348008323

However, it works perfectly with Elastic/Kibana 5.6.5

Thanks!

**Comment by jsoriano** [comment]
Closing as this shouldn't be an issue in recent versions, please reopen if it still is.
