### ISSUE TITLE
Extra information about a process to distinguish same-named processes

### ISSUE THREAD

**Issue by Cylindric** [elastic/beats#590]
I am trying out TopBeat to monitor MS SQL servers, and my servers have several instances of SQL running on them at once.
TopBeat correctly logs these with the process name of "sqlservr.exe" and the relevant PID.

My question is, how could I track these individually over time? The PIDs will change as the services are restarted, and even move from cluster node to cluster node, so it's very difficult to get any sort of persistent trends analysed.

Ideally, if the logged data could contain either the path to the process (which is unique and consistent across the instances) or the user the process is running as (unique for us, but not necessarily for everyone), that would solve all our problems.

**Comment by monicasarbu** [comment]
Related to https://github.com/elastic/topbeat/issues/36

**Comment by monicasarbu** [comment]
Related to https://github.com/elastic/beats/issues/533

**Comment by monicasarbu** [comment]
I think it would be easier to export the full command line of process than the process username, so we will try to add this information first. What OS do you use?

**Comment by Cylindric** [comment]
Full path would be perfect in my case. It's Windows Server 2012 in this particular instance. 

You're spot on with those two linked issues though - if they apply to Windows processes too, either would solve my issue.

**Comment by biswajit86** [comment]
+1

any ideas if this is being targeted for some release

**Comment by eonarheim** [comment]
I've committed a potential fix for user name information on my fork of gosigar, I'm just going to confirm it works when rolled into topbeat on windows.

**Comment by KptnKMan** [comment]
+1

I have the same issue in my environments, when usign Topbeat there are a lot of same named processes, and also useful for our sqlservr.exe processes.

process command path would be critically useful here.
process userid would be very useful.

Is there any idea if/when this would be developed?

**Comment by andrewkroh** [comment]
The user and the full command line have been implemented and will be released in 1.2.0. Documentation for the new fields is [here](https://www.elastic.co/guide/en/beats/topbeat/master/exported-fields-process.html#_proc_cmdline).

**Comment by andrewkroh** [comment]
@KptnKMan Here's the link to the Windows [development build](https://beats-nightlies.s3.amazonaws.com/topbeat/topbeat-5.0.0-nightlylatest-windows.zip) that has the feature if you want to test it.

**Comment by KptnKMan** [comment]
@andrewkroh
Thanking you kindly, I found the nightlies and I'm going to try. Just 1 question: is it advisable to use the 5.0.0 latest or 1.2.0, as I see the fix has been backported. Is there a major difference?

Thanks!

**Comment by andrewkroh** [comment]
The 1.2.0 nightlies are no longer being updated (a limitation of our current build setup) and do not contain the backport. So you would have to use the 5.0.0 nightly to test this feature or build the 1.2 branch yourself. The CHANGELOG for 5.0 is [here](https://raw.githubusercontent.com/elastic/beats/master/CHANGELOG.asciidoc) if you want to see all the changes since 1.1.1.
