### ISSUE TITLE
Improve logging of index failures

### ISSUE THREAD

**Issue by zytek** [elastic/beats#5904]
I had to run filebeat in debug mode  to fix issue with dynamic index name creation. IMO Filebeat by default should log much more verbose messages if they are hard errors.

Steps to reproduce:
- configure filebeat to create dynamic indexes like this example for Kubernetes:
```
output.elasticsearch:
        hosts: ['${ELASTICSEARCH_ENDPOINT}']
        index: "filebeat-%{[kubernetes.namespace]}-%{+yyyy.MM.dd}"
```
- filebeat fails to send all logs to ES with not very informative message:

```
2017/12/18 13:39:08.574944 output.go:92: ERR Failed to publish events: temporary bulk send failure
2017/12/18 13:39:08.575113 logger.go:22: INFO retryer: send unwait-signal to consumer
2017/12/18 13:39:08.575129 logger.go:22: INFO   done
2017/12/18 13:39:08.575136 logger.go:22: INFO retryer: send wait signal to consumer
2017/12/18 13:39:08.575141 logger.go:22: INFO   done
```

- the actual error is a hard error and should be reported with much higher log level:
```
2017/12/18 13:39:07.574752 client.go:469: DBG Bulk item insert failed (i=48, status=500): {"type":"string_index_out_of_bounds_exception","reason":"String index out of range: 0"}
```
Filebeat version 6.0.1

**Comment by ruflin** [comment]
@zytek Is this different from https://github.com/elastic/beats/issues/5905 ?

**Comment by zytek** [comment]
@ruflin you could consider this related, but this issue is about proper debug levels (more meaningful error messages without the need to run filebeat in debug mode) and the second one is about actual error, why it happens and how to correct it :)

**Comment by ruflin** [comment]
Got it, thx.
