### ISSUE TITLE
Filebeat skips log events if it cannot create index name 

### ISSUE THREAD

**Issue by zytek** [elastic/beats#5905]
I am trying to separate ES indexes per Kubernetes namespace, to implement custom retention policies. Unfortunately when a field is not available then Filebeat skips log event as it gets 500's from Elasticsearch

Steps to reproduce: 
- configure similar ES output with nonexistent field:
```
    output.elasticsearch:
        hosts: ['${ELASTICSEARCH_ENDPOINT}']
        index: "filebeat-%{[beat.nonexistent]}-%{+yyyy.MM.dd}"
```
Expected behaviour: filebeat should create index `filebeat--2017.12.19` OR provide a way to set default variable for [beat.nonexistent] field.

Currently it must try to submit empty index name to ES as per debug log:
```
2017/12/18 14:19:38.663565 client.go:469: DBG Bulk item insert failed (i=42, status=500): {"type":"string_index_out_of_bounds_exception","reason":"String index out of range: 0"}
```

which seems plain wrong  (it should bail out before sending wrong requests to ES)

Filebeat version 6.0.1

**Comment by ruflin** [comment]
@zytek This might already help for your use case? https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html#_literal_indices_literal 

I agree we should fail earlier and provide a better error message.

**Comment by zytek** [comment]
Yes, it seems I could achieve what I want with indices conditions. Thanks!

Still, this could be handled better as now it seems the whole batch is dropped when one entry contains invalid (empty?) index name.

**Comment by ruflin** [comment]
I think if the field exists but is empty, it "should" still work. If it is not existant but required for the index name, it will drop. That is why the condition should make sure it does not match in such cases.

**Comment by sgendler-stem** [comment]
I have a case where my logs are already output as JSON.  I use one of the fields of that JSON object as part of the index name.  However, there are always a couple of lines of output before the log infrastructure is initialized in the app which go out as plain text instead of json. Those are missing that field.  Is there any way to conditionally add a field such that it won't override the field of the same name if it already exists?
