### ISSUE TITLE
Metricbeat Host Overview Dashboard for 6.1 seems to be "off"

### ISSUE THREAD

**Issue by morgango** [elastic/beats#5907]
The dashboards for metricbeat seem to be "off", displaying in a multiline manner regardless of the browser, size of the screen, or the font chosen.  While this isn't a show stopper, it makes it difficult to read the first text read on the dashboard.

It looks like this:

![image](https://user-images.githubusercontent.com/3835173/34125290-635946b6-e3fb-11e7-910a-0b4b4a37934f.png)

I have tried making the font large/smaller and changing the size of the web browser, it does not make a difference.  However, going into the visualization and making the font to 9 and it removes the multiline display.

Changing it makes it look like:

![image](https://user-images.githubusercontent.com/3835173/34125470-ee471e24-e3fb-11e7-9f6a-7e9c6490c0f1.png)

- Version: 6.1
- Operating System: Mac OS X (used Chrome and Safari)
- Steps to Reproduce: Install Metricbeat, Dashboard, load with data.

**Comment by ruflin** [comment]
@simianhacker @monicasarbu I wonder if this is an issue of our dashboards or Kibana itself?

**Comment by simianhacker** [comment]
I think Kibana changed the CSS which probably affected how things display on the dashboard.

**Comment by urso** [comment]
Issue has not been updated for 1+ year. Closing. Please re-open the issue if the problem still persists with newer versions.
