### ISSUE TITLE
Filebeat documentation

### ISSUE THREAD

**Issue by ChrisCooney** [elastic/beats#5935]
Hi All, i'm just raising an issue to point out a documentation issue I spotted.

https://www.elastic.co/guide/en/beats/filebeat/1.2/using-environ-vars.html

The following document indicates that one can add in a host from environment variables with a syntax like this:

```
hosts: [$ELK_URL]
```

However filebeat appears to ignore this. It does, however, parse this fine: 

```
hosts: ["${ELK_URL}"]
```

**Comment by markwalkom** [comment]
Thanks for this! Note that 1.2 has reached [EOL](https://www.elastic.co/support/eol), so if you are using it then please do upgrade ASAP :)

**Comment by ChrisCooney** [comment]
Hi Mark, thanks for the update. We'll look into upgrading.

**Comment by dedemorton** [comment]
Closing because this should have been closed awhile back ago because 1.2 is EOL and later versions of the doc show the correct syntax.
