### ISSUE TITLE
Add geoip option in mapping

### ISSUE THREAD

**Issue by markwalkom** [elastic/beats#594]
I was chatting to someone on IRC today as they were having issues getting geoip to work correctly with filebeat+LS.

It seems to me that this would be an increasingly common use case, so it would make sense to add a geoip mapping section like what [LS already has](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json#L82-L90).

Thoughts?

**Comment by ruflin** [comment]
@markwalkom I would probably not add this section on the beats side (yet) as it is LS that processes the geoip information. So this mapping only works, if the data goes through LS. We try to keep the mapping compatible with both options. This could change with having geoip as part of node-ingest in ES (https://github.com/elastic/elasticsearch/pull/14208). What could help here is to have some example on how to create your own mappings with the most common use cases.

**Comment by markwalkom** [comment]
Understand, but for 9 lines I think it's an easy way to close the gap.
LS ultimately listens to whatever you tell it to do, and most people use the `filebeat-` index pattern we provide, even with LS in the middle.

**Comment by ruflin** [comment]
In case we add this change, we should probably also think about our default LS config we provide here: https://www.elastic.co/guide/en/beats/libbeat/1.0.1/getting-started.html#logstash-setup Should it have some also the geoip filter inside?

I'm still hesitant to add it even though I agree it is a common use case. I would prefer that the default only contains the minimal required fields. At the same it should be as easy to start which brings up the question, are there other "fields" which are required in most use cases?

This topic gets even more interesting in case we load the template automatically (https://github.com/elastic/libbeat/issues/62) as this would mean, everyone uses the default template.

**Comment by markwalkom** [comment]
If it makes sense to put it into libbeat, then yep :)
