### ISSUE TITLE
Allow for modifying json field names with dots in them in beats

### ISSUE THREAD

**Issue by dl1ely** [elastic/beats#5942]
Following the suggestion in https://discuss.elastic.co/t/allow-for-renaming-of-json-fields-in-http-module-output/112461 i open this issue to discuss the challenges regarding json field names with dots in them when these get collected/created by beats, especially metricbeat.

The problem is also described in https://discuss.elastic.co/t/v6-0-0-beta2-http-module-mapping-trouble/99703?source_topic_id=112461 and was already addressed in httpbeat, the predecessor of the metricbeat http module (https://github.com/christiangalsterer/httpbeat/blob/master/config/config.go#L34). Unfortunately, the http module does not allow a replacement of dots in json keys collected from the source.

The issue also surfaced in Spring Boot Actuator https://github.com/spring-projects/spring-boot/issues/10449 but it affects other producers of metrics data too, and will not be fixed in Spring Boot 1.5

**Comment by christiangalsterer** [comment]
@ruflin: If you have an idea/preference/suggestion how to address this I can have a look into it.

**Comment by ruflin** [comment]
I think this is actually problem we have to solve in different places but probably have a method internally to do it. In general we should have  a method replacing dot separated keys with `_`  as we already do for example for docker labels.

Here the different fixes we should do:

* Jolokia: We should do it here by default as part of the metricset as it happens too often
* http json metricset: Have a config option there
* JSON processor: We should allow to do this as an option there too, which probably internally can be used by the http/ json metricset.

@christiangalsterer Would be great to have a PR for the `http/json` metricset, I will have a look at the jolokia one.

**Comment by ruflin** [comment]
BTW here is the discussion from the Jolokia side: https://discuss.elastic.co/t/include-fields-problem/109809

**Comment by ruflin** [comment]
@christiangalsterer You can use the dedot function introduced here: https://github.com/elastic/beats/pull/5957

**Comment by christiangalsterer** [comment]
@ruflin: Thanks for the info. Will have a look into the `http/json` metricset.

**Comment by ruflin** [comment]
@christiangalsterer Awesome. Ping me if I can be of any help.

**Comment by walktall** [comment]
Just like docker labels, add_kubernetes_metadata processors also need to handle k8s labels and annotations.

[This method](https://github.com/elastic/beats/blob/master/libbeat/processors/add_kubernetes_metadata/indexers.go#L123) should also apply common.DeDot introduced in https://github.com/elastic/beats/pull/5957 for keys of labelMap and annotationsMap.

**Comment by christiangalsterer** [comment]
PR #5970 available.

**Comment by ruflin** [comment]
Based on a discussion started about dots here (https://github.com/micrometer-metrics/micrometer/issues/154#issuecomment-364792276) I'm now thinking we probably need an additional conversion options to keep the `dots` but add `.value` or `.count` to the keys which conflict.
