### ISSUE TITLE
add beat and type to the "beat" section added to each document

### ISSUE THREAD

**Issue by robin13** [elastic/beats#5948]
Currently beats add the following fields to the document:

```
  "beat": {
    "name": "es-rclarke",
    "hostname": "es-rclarke",
    "version": "5.6.3"
  }
```
And the following data is transmitted in the beats protocol and made available in logstash under the `@metadata` field:

```
     "@metadata": {
        "type": "metricsets",
        "beat": "metricbeat"
    }
```

Would it be possible to (optionally) add the fields `beat` and `type` to the basic `beat` field in the document? 

Rational - if using another message queue other than logstash (e.g. Kafka) the metadata detailing the beat/type is lost.  The only workaround currently is to add a custom field in the beats configuration, but this is not elegant and error prone.

**Comment by ruflin** [comment]
I assume as the `type` is the same for all events we would only need to add the name of the beat?

**Comment by robin13** [comment]
I don't know... is the `type` _always_ the same for all beats?  From the example above (metricbeat has `"type":"metricsets"`) I doubt it...

**Comment by ruflin** [comment]
It's not the same type for all Beats but we are diverging in a direction that each beat should only have one type which was the same as `_type` in the past. Now that we don't have `_type` anymore we should probably completely remove the notion of a type.

**Comment by brandonmensing** [comment]
Some of the concepts in ECS will subsume these needs but for now it seems reasonable to add this option and also likely plan to drop anything called 'type' as of 7.0 (which is when it completely disappears from ES as well).

**Comment by ruflin** [comment]
@brandonmensing Moving forward on this I don't think we should add it to the meta info but directly starting to use ECS. This means we should potentially introduce `agent.name: filebeat` for example as part of our event with 6.x.
