### ISSUE TITLE
Add command to output full config

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#5964]
With modules and dynamic config directories and modules it became harder to see which config is actually used. For debugging purpose it would be nice to have a command like `filebeat config show` that prints out the full config which is collected from the different files and combines it into one file.

**Comment by Hexilee** [comment]
@ruflin The sub command `<beat> export config` is not full enough?

**Comment by ruflin** [comment]
If you run `metricbeat export config` as an example it will only output the config you have in the `metricbeat.yml` file. All the enabled modules under `modules.d` directory will not be in there. Same for filebeat if a `config.propspector.path` is used. 

With autodiscovery it goes further that modules are loaded for which nothing exists on disk but the config is only in memory. Would be nice to be able to output the full state.

**Comment by andrewkroh** [comment]
I think it would be a good improvement to make `export config` include the data from modules.d / conf.d.

If we had a CLI tool that could query the running Beat then I would think that would be a good place to add the command for dumping the running config which includes things started by auto-discovery.
