### ISSUE TITLE
[heartbeat] HTTP check.body enhancements proposal

### ISSUE THREAD

**Issue by Crazybus** [elastic/beats#5981]
As discussed with @ruflin I would like to make some enhancements to the `check.body` option in heartbeat. Happy to write the implementation but first wanted to discuss how this should look configuration wise since that is the main challenge. 

## Current situation
`check.response.body` calls the function [checkBody](https://github.com/elastic/beats/blob/e8b8fa9bb857f74e424a07295a3550a7523e2b0d/heartbeat/monitors/active/http/check.go#L87) which compares the entire reponse body to make sure it is equal. In the `body: '{"status": "ok"}'` that works perfectly however if you have an entire webpage it isn't practical to paste the entire webpage into `check.response.body`
```
check.response:
  body: '{"status": "ok"}'
```

## Proposal check.response.body with contains
Modify `func checkBody` to check if the body contains the string rather than being equal

## Proposal check.response.body with regex
Make `check.response.body` a regex pattern for matching the body
```
check.response:
  body: /ok/
```

## Bonus proposal check.resonse.bodyJSON
Instead of checking for a JSON string actually parse the JSON and compare fields.
```
check.response:
  bodyJSON:
    status: "ok"
```

**Comment by ruflin** [comment]
I like both suggestion. For option 1 we keep the existing functionality but also allow regexp expression in addition. We already use someting similar for `exclude_lines` in FB an other places:

```
	ExcludeLines []match.Matcher         `config:"exclude_lines"`
```

An other more powerful option could be to introduce somehow the query language we use in processor. Something like

```
check.response:
  when.equals:
    body: 123
```
This would allow to use the full power of the query language like conditions etc: https://www.elastic.co/guide/en/beats/filebeat/5.3/configuration-processors.html#conditions I wonder if in this case we should even write above `check.when.equals: repsonse.body: ...` to directly mention the full field. This would even make it possible to mix request / response and header / body etc together.

Taking the above into account, I'm thinking for the response but it should be possible to define that the response is in json directly as part of the monitor outside the check. Then the above query language could be used to access all the fields which would be put under the response namespace.

**Comment by Crazybus** [comment]
@ruflin I really really like the option of using the query language. However I can imagine that would be rather difficult to implement and keep backwards compatible with current heartbeat configurations. 

Would you be open to me implementing option 1 for now and opening a separate issue for using the query language for checks?

**Comment by ruflin** [comment]
+1 on moving forward as you suggested.

Related to breaking changes: We plan a few in Heartbeat before going GA but we didn't get time for it yet: https://github.com/elastic/beats/issues/3952

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/beats/pull/6539 got merged.
