### ISSUE TITLE
Reintroduce crosscompile on tested platforms

### ISSUE THREAD

**Issue by kvch** [elastic/beats#5984]
Cross-compilation Travis jobs is removed for a time being in #5545. Right now CGO is not enabled for these tests. Introduction of CGO, a bigger change is required in setting up test environments. To avoid blocking the merge of CPU usage, this task is moved to a different issue.

Most of the temporarily removed platforms are not supported officially. It might interfere with compiling master branch of Beats on these platforms, as a new release of `gosigar` is required and must be move to `vendor`.

The tests can be still run locally using `make crosscompile`.

**Comment by ruflin** [comment]
As part of this we should add crosscompile builds also to jenkins.

It also reminds of this old issue here: https://github.com/elastic/beats/issues/2251

**Comment by kvch** [comment]
Resolved in #5993
