### ISSUE TITLE
Filebeat 6.1.1 multiline is not working.

### ISSUE THREAD

**Issue by tamoraes** [elastic/beats#5985]
As mentioned, I'm not being capable of making multiline work on filebeat. The message is getting received on logstash without considering the multiline. I've made it work on debbugers, but not on the real deal. What am i doing wrong here?

Here is the message that i'm trying to parse:

2017-12-28 00:05:00,634 INFO  [CBILL_ESB_PROFILER_LOGGER] (pool-192-thread-1) ProfilerStat [serviceName=jms:instance.node.com.br:15199#queue/soa/saveCustomerService, error=false, timeToExecute=2017-12-28 00:05:00 - 222ms, 
messageRequest=
<cus:customerSaveRequest xmlns:cus="http://com.test/services/crud/CustomerSaveRequest" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <gen:userIdentification xmlns:gen="http://com.test/services/crud/GenericSaveRequest">WS_SOL</gen:userIdentification>
   <gen:saveDate xmlns:gen="http://com.test/services/crud/GenericSaveRequest">2017-12-28T00:05:00</gen:saveDate>
   <cus:customer>
      <cus1:personType xmlns:cus1="http://com.test/types/Customer">1</cus1:personType>
      <cus1:companyAssociations xmlns:cus1="http://com.test/types/Customer">
         <cus1:companyAssociation>
            <cus2:nrc xmlns:cus2="http://com.test/types/CustomerCompanyAssociation">6983877</cus2:nrc>
         </cus1:companyAssociation>
      </cus1:companyAssociations>
      <cus1:birthday xmlns:cus1="http://com.test/Customer">1987-07-04</cus1:birthday>
   </cus:customer>
</cus:customerSaveRequest>

messageResponse=
<ns130:customerSaveResponse xmlns="adresses">
   <ns130:resultItem>
      <ns130:customerIdentification>
         <ns130:nrc>xxxxxxx</ns130:nrc>
         <ns130:companyIdentification>xxxxxx</ns130:companyIdentification>
      </ns130:customerIdentification>
   </ns130:resultItem>
</ns130:customerSaveResponse>
]

and here is my filebeat.yml, with configurations of multiline:

filebeat.prospectors:

- type: log

  enabled: true

  paths:
    - /var/log/*.log

  multiline.pattern: '^.*\[CBILL_ESB_PROFILER_LOGGER\]'
  multiline.negate: true
  multiline.match: after
  multiline.flush_pattern: '\]'

**Comment by ruflin** [comment]
For questions please open an issue on discuss: https://discuss.elastic.co/c/beats/filebeat We will try to answer there. Make sure post your Filbeat version, the logs of filebeat and the full config formatted or as gist.
