### ISSUE TITLE
Feature Request: Packetbeat in docker network

### ISSUE THREAD

**Issue by jamiesmith** [elastic/beats#5989]
It would be nice if packetbeat were more "docker aware", and if the `add_docker_metadata` could enrich docker container networks.  

For example, we have a stack set up on one host, communicating using a bridge network. The packetbeat container is on the same stack, monitoring the host network.

**Comment by ruflin** [comment]
@exekias Any thoughts?

**Comment by exekias** [comment]
This is doable, and a nice to have. We already support this with `add_kubernetes_metadata`, we need to index containers by IP address, so we can match the `ip` field from Packetbeat events :+1:
