### ISSUE TITLE
metricbeat cgroup memory reporting isn't quite correct

### ISSUE THREAD

**Issue by benzo-elastic** [elastic/beats#6033]
It would appear the memsw/kmem reporting for cgroups isn't being reported correctly & after a discussion with @andrewkroh it seems to originate from 
https://github.com/elastic/beats/blob/master/metricbeat/module/system/process/cgroup.go#L120 
where it's not using the local `data` variable, so all mem/memsw/kmem reporting is just using `memory.Mem` counters.

**Comment by andrewkroh** [comment]
I have opened a PR to fix this at https://github.com/elastic/beats/pull/6034.
