### ISSUE TITLE
Autogenerate reference configuration based on Config struct

### ISSUE THREAD

**Issue by pmoust** [elastic/beats#6036]
It would be sweet to have a wrapper generating `${foo}.yml` and `${foo}.reference.yml` for a `foo` beat based on the `Config` struct declaration.

**Comment by ruflin** [comment]
Great idea. I would assume this is a feature we would need in `go-ucfg` (@urso).

@pmoust You showed in Slack some nice examples, perhaps you can add these to the PR here for easier understanding what is meant.

**Comment by pmoust** [comment]
And about a year later, I noticed I haven't replied..

The idea is that the `Config` struct is really the point where reference configuration should stem from for all possible options, and `defaultConfig` contains the defaults.
That convention I believe is followed in every beat, as it's declared in `libbeat` with the help of `ucfg`.

For example, see [auditbeat's auditd module Config](https://github.com/elastic/beats/blob/master/auditbeat/module/auditd/config.go#L45-L68) and its [default configuration](https://github.com/elastic/beats/blob/master/auditbeat/module/auditd/config.go#L82-L93)

Also outputs, processors and others are common, and their properties/settings defined in `libbeat`, using the same mechanism described above.

Those should be enough to populate the reference config yaml files. 

This would provide a single source of maintaining config (the actual code) that ensures reference configs are not generated by a human, and enables a path forward for autogenerated documentation too.
