### ISSUE TITLE
govendor -> Failed for "github.com/docker/docker/client" (failed to sync repo to 83d94aa2b98f10c4534d77077645d5e328533ce4)

### ISSUE THREAD

**Issue by cyrilleverrier** [elastic/beats#6056]
For confirmed bugs, please report:
- Version: Libbeat v6.1.1

I am trying to switch to the tool `govendor` to manage the dependencies

1. Create a new beat
2. Copy https://raw.githubusercontent.com/elastic/beats/v6.1.1/vendor/vendor.json to your vendor folder
3. Add 
4. govendor sync

```
# cd /home/cyrille/code/go/.cache/govendor/github.com/exekias/moby; git reset --hard 83d94aa2b98f10c4534d77077645d5e328533ce4
fatal: Could not parse object '83d94aa2b98f10c4534d77077645d5e328533ce4'.
# cd /home/cyrille/code/go/.cache/govendor/github.com/exekias/moby; git reset --hard 83d94aa2b98f10c4534d77077645d5e328533ce4
fatal: Could not parse object '83d94aa2b98f10c4534d77077645d5e328533ce4'.
# cd /home/cyrille/code/go/.cache/govendor/github.com/exekias/moby; git reset --hard 83d94aa2b98f10c4534d77077645d5e328533ce4
fatal: Could not parse object '83d94aa2b98f10c4534d77077645d5e328533ce4'.
# cd /home/cyrille/code/go/.cache/govendor/github.com/exekias/moby; git reset --hard 83d94aa2b98f10c4534d77077645d5e328533ce4
fatal: Could not parse object '83d94aa2b98f10c4534d77077645d5e328533ce4'.
Error: Remotes failed for:
	Failed for "github.com/docker/docker/client" (failed to sync repo to 83d94aa2b98f10c4534d77077645d5e328533ce4): exit status 128
	Failed for "github.com/docker/docker/pkg/system" (failed to sync repo to 83d94aa2b98f10c4534d77077645d5e328533ce4): exit status 128

```

The commit https://github.com/exekias/moby/commit/83d94aa2b98f10c4534d77077645d5e328533ce4 is no longer reachable.
I guess the following commit is the correct one: https://github.com/exekias/moby/commit/f0ad590efaf759401da79248010913a73023182e

Question: 
What is the best way to get/update my vendor/github.com/elastic/beats/libbeat ?

This command get libbeat v6.1.1 but it also fetches the latest versions of the libbeat's vendor dependencies
```
govendor fetch -v -tree github.com/elastic/beats/libbeat@v6.1.1
```

I want to get the versions specified in https://raw.githubusercontent.com/elastic/beats/v6.1.1/vendor/vendor.json

**Comment by ruflin** [comment]
@exekias Did we ever contribute this back?

I remember looking into the docker / moby renaming and updating docker when it happened but it was very messy so I didn't touch it. Perhaps we should do one more attempt here to get a more recent version and clean up the dependencies?

@cyrilleverrier I did in apm-server some tooling around updating beats dependencies to seperate Golang and tooling dependencies: https://github.com/elastic/apm-server/blob/master/Makefile#L21 I was hoping to get this into the generator one day to make it available to all beats. Feel free to copy / get inspired by these.

**Comment by exekias** [comment]
We didn't push this to upstream, as the change was just disabling some code paths to avoid cross-compilation issues. I'll have a look to this, probably I did some rebase and forgot to update our vendors

**Comment by exekias** [comment]
Ok, this should be fixed now, I didn't update `vendor.json`, I just recovered the existing rev in my repo, @cyrilleverrier could you please check now and report back? I suspect we may have other broken sources

**Comment by exekias** [comment]
Closing this after some testing, feel free to reopen if you hit a new issue

**Comment by cyrilleverrier** [comment]
@exekias Thank you for the fix :+1:
