### ISSUE TITLE
Tweak uWSGI metricset fields

### ISSUE THREAD

**Issue by iahmedov** [elastic/beats#6062]
As suggested by @ruflin here #6006, 
- field names should be tweaked https://github.com/elastic/beats/pull/6006#discussion_r161130119
- data generation in metricset examples should be autogenerated https://github.com/elastic/beats/pull/6006#discussion_r161130237

If any other suggestions please include here.

(Can someone assign it to me?)

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
