### ISSUE TITLE
RFE: System diskio positive selection

### ISSUE THREAD

**Issue by stefws** [elastic/beats#6083]
It might be nice with an option for system.diskio like:

diskio.name_match_regexp: '^(dm-|vd)'

to make diskio only collectd and submit data for device names matching such regexp

as discussed [here](https://discuss.elastic.co/t/system-diskio-positive-selection/115536)

**Comment by ruflin** [comment]
@stefws See my comment in https://github.com/elastic/beats/pull/6085

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/beats/pull/6085 was merged.
