### ISSUE TITLE
setup.dashboards.always_kibana doesn't work with Kibana 5.6

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#6090]
Attempts to use `-E setup.dashboards.always_kibana=true` with Kibana 5.6 always result in an error. This is the code in question:

https://github.com/elastic/beats/blob/6130ef3b464008b9cdfae9476bdcf03076e642fd/libbeat/setup/kibana/client.go#L172-L182

After it successfully falls back to unmarshaling with the 5.x data type the code path always hits line 181 which is to return an error like the one below.

```
Exiting: Error importing Kibana dashboards: fail to create the Kibana loader: Error creating Kibana client: fail to get the Kibana version:fail to unmarshal the response from GET http://localhost:5601/api/status: json: cannot unmarshal string into Go struct field kibanaVersionResponse.version of type struct { Number string "json:\"number\""; Snapshot bool "json:\"build_snapshot\"" }. Response: {"name":"kibana","version":"5.6.6","buildNum":15605,"buildSha":"b67ac57661fc94df6ee476d0af6b3734211df61c","uuid":"25e5ec36-a8a6-4934-9010-5e78e2e345eb","status":{"overall":{"state":"green","title":"Green","nickname":"Looking good","icon":"success","s... (truncated)
```

**Comment by andrewkroh** [comment]
Discuss: https://discuss.elastic.co/t/kibana-5-6-error-importing-kibana-dashboards-fail-to-get-the-kibana-version/115365

**Comment by jdambly** [comment]
+1 I am also having this issue with metricbeat

`ansible@sv5knfs04:~$ sudo metricbeat setup --dashboards -E setup.dashboards.always_kibana=true -E setup.dashboards.kibana_index=.kibana-5.x
Exiting: Error importing Kibana dashboards: fail to create the Kibana loader: Error creating Kibana client: fail to get the Kibana version:fail to unmarshal the response from GET http://kibana01.mgt.sv5.nskope.net:5601/api/status: json: cannot unmarshal string into Go struct field kibanaVersionResponse.version of type struct { Number string "json:\"number\""; Snapshot bool "json:\"build_snapshot\"" }. Response: {"name":"kibana01","version":"5.6.5","buildNum":15592,"buildSha":"80f98787eb860a4e7ef9b6500cf84b65e331d1fc","uuid":"dd391d64-8a93-4821-a09a-5ed999f4e38b","status":{"overall":{"state":"green","title":"Green","nickname":"Looking good","icon":"success",... (truncated)
ansible@sv5knfs04:~$`
