### ISSUE TITLE
Developer Documentation Update - Beater/lsbeat

### ISSUE THREAD

**Issue by nwaringa** [elastic/beats#6093]
The Beats developer documentation for building a Beat in 6.x (page linked below) refers to the Beater page of 5.x (right hand chevron navigational item).

https://www.elastic.co/guide/en/beats/devguide/current/compiling-and-running.html

On this Beater page are details on the old pre-6.x Run methods in the Run section.

![image](https://user-images.githubusercontent.com/16107123/35048091-10efff9c-fb6a-11e7-99fd-3580b3753b64.png)

Right hand chevron navigation from the Beater page refers to lsbeat as an example which is also built on 5.x and provides inaccurate guidance similar to that above.

For confirmed bugs, please report:
- Version: 6.x
- Operating System: N/A
- Steps to Reproduce: See above

**Comment by dedemorton** [comment]
Closing in favor of #7159 because some of the details of this old issue are no longer relevant.
