### ISSUE TITLE
Support live reload of metricsets

### ISSUE THREAD

**Issue by vjsamuel** [elastic/beats#6096]
Currently metricbeat modules that expose a server like Graphite and HTTP do not have a mechanism to be able to "live reload" their config. If there is a change in the config, the server needs to be taken down and brought back up again. There needs to be an API that these metricsets can implement to allow live reloading. This will be useful for configs placed in `modules.d` with reload enabled and also for auto discover. This will minimize downtimes and drop in metrics that are incoming.

This came out as part of a discussion with @exekias on autodiscover for push based metricsets.

**Comment by ruflin** [comment]
@vjsamuel I assume your worry here about is loosing of events. The reloading should be fairly quick (milli seconds) but still you could loose events. Which part of the config did you have in mind to reload?

**Comment by vjsamuel** [comment]
@ruflin the portion that has to be reloaded is metricset specific. Example: `templates` would need to be reloaded for Grafana server metricset and `paths` would need to be reloaded for HTTP server metricset. Ideally each metricset must be able to live reload based on what portion it wants to reload.

**Comment by ruflin** [comment]
Reminds me quite a bit of the reloading which happens in heartbeat. So far the plan was to replace the heartbeat reloading with our generic one but based on your comment I wonder if the two potentially should be merged. What I would like to prevent is having too many different reloading functionalities.

For the 7s: I assume this is related to that the connections have to be shut down first.

Perhaps there are solution to this where we could reuse the existing capabilities. One idea is to allow the `http.server` metricset to be specified multiple times an each could have only 1 path. There would be a global `server` running as long as one metricset exists and paths can be added / removed.

**Comment by vjsamuel** [comment]
Yes that is the thought I have as well. If a template is added/removed from a graphite.server then we just reload the tree implementation that it uses while keeping the port intact. the tree could potentially be locked so that we still receive events from the port and are processed only after reload is complete. 

similar would be the case for http.server and anything else that requires such a mechanism. as long as we can provide an optional interface to be implemented metricsets/prospectors/anything else should be able to implement it.

**Comment by ruflin** [comment]
@vjsamuel Want to take a stab on it? :-)

**Comment by vjsamuel** [comment]
of course :)
