### ISSUE TITLE
Update golang.org/x/... packages that are vendored in libbeat?

### ISSUE THREAD

**Issue by cyrilleverrier** [elastic/beats#6102]
- Version: libbeat 6.1

`golang.org/x/net/...` and `golang.org/x/text/...` packages that vendored in libbeat are quite old.

This is a problem when a beat application imports other dependencies that requires more recent versions of `golang.org/x/net/...` and `golang.org/x/text/...`

Steps to reproduce
This is an artificial way of showing the issue
1. clone https://github.com/elastic/apm-server
2. Edit `main.go` as  follow:
```
package main

//go:generate go run script/inline_schemas/inline_schemas.go
//go:generate go run script/output_data/output_data.go

import (
	"os"

	"github.com/elastic/apm-server/cmd"
	"google.golang.org/grpc"
)

func main() {
	grpc.Dial("test")
	if err := cmd.RootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}
```

3. `govendor fetch google.golang.org/grpc/...@v1.9.1`
4.  `make`
```
go build -i -ldflags "-s -X github.com/elastic/apm-server/version.buildTime=2018-01-18T11:13:19Z -X github.com/elastic/apm-server/version.commit=19c5ed5f719e33b704106ad27f0de9087165ad1b"
# github.com/elastic/apm-server/vendor/google.golang.org/grpc/transport
vendor/google.golang.org/grpc/transport/http_util.go:486:6: f.fr.SetReuseFrames undefined (type *http2.Framer has no field or method SetReuseFrames)
_beats/libbeat/scripts/Makefile:96: recipe for target 'apm-server' failed
```

Workaround:
```
govendor remove golang.org/x/net/...
govendor remove golang.org/x/text/...
govendor fetch  golang.org/x/net/...
govendor fetch  golang.org/x/text/...
```

**Comment by ruflin** [comment]
@cyrilleverrier I suggest we should update the dependency on our side to a more recent version. I remember there were some issues in the past with this that required refactoring but not sure anymore what it was. If not, even better. PR? :-D

**Comment by cyrilleverrier** [comment]
@ruflin let's try this PR https://github.com/elastic/beats/pull/6246
All beats compile with the updated vendor package.
Please review the changes carefully as I don't know what can break :)

**Comment by ruflin** [comment]
Thanks, see comments there.

**Comment by cyrilleverrier** [comment]
Fixed by:

- https://github.com/elastic/beats/pull/6336
- https://github.com/elastic/beats/pull/6337
- https://github.com/elastic/beats/pull/6338
- https://github.com/elastic/beats/pull/6339
- https://github.com/elastic/beats/pull/6340
- https://github.com/elastic/beats/pull/6341
