### ISSUE TITLE
Logs with single line of text, without newline at the end

### ISSUE THREAD

**Issue by sergiu-tot** [elastic/beats#6132]
Hello guys,

I have a Magento2 instance for which I collect the logs using prospectors in filebeat-5.2.1. This is happening on a docker container based on ubuntu xenial (16.04).

The Magento2 report is a valid json file with a single line, but contain no newline at the end of the string which results in logs not being sent - https://www.elastic.co/guide/en/beats/filebeat/current/faq.html#newline-character-required-eof

A way to check the logs without newline character would be useful, if you could add it in the next versions.

https://discuss.elastic.co/t/filebeat-and-magento2-reports/116226

**Comment by aureliomarcoag** [comment]
@sergiu-tot I've got the exact same use case. For now we'll be using a not so pretty workaround on a cron:

`#!/bin/bash
MAGENTO_REPORT_PATH=${MAGENTO_REPORT_PATH:-/var/www/var/report/}
for file in $(find $MAGENTO_REPORT_PATH -maxdepth 1 -type f) ; do
    # Make sure we're dealing with reports here
    if [[ $file =~ .*/var/report/[0-9]*$ ]] ; then
        if ! [ -f "${file}-newline" ] ; then
            cat "$file" <(echo) > "${file}-newline"
        fi
    fi
done`

I can't say it makes me happy, but at least the reports show up now. I'd very much like this implemented as well :)
