### ISSUE TITLE
Make `-e` on by default

### ISSUE THREAD

**Issue by roncohen** [elastic/beats#6134]
Today, starting any beat will by default not output anything to STDOUT. To newcomers it looks like the beat is just stuck. This can be confusing. I suggest we enable `-e` by default so no arguments are required to see something in the console when starting a beat. We could also investigate checking for a TTY and only setting `-e` if there's a TTY attached. See `IsTerminal`: https://godoc.org/golang.org/x/crypto/ssh/terminal#IsTerminal

**Comment by ph** [comment]
> To newcomers it looks like the beat is just stuck

I agree with that part, It is a bit surprising if you just want to test out beats and nothing is show.

**Comment by ruflin** [comment]
+1 on this. If we can find a (mostly) backward compatible way to implement this we can already do it in 6.x, otherwise definitively for 7.0.

I wonder if we enable `-e` by default if we need an other option to disable it or if that is not even a use case that should be covered. In other tools this would probably be something like `-s` (silent).

**Comment by crazyvikas23** [comment]
We can remove the `-e` option altogether and log the output to STDOUT by default. We can add a `-q` flag to quiet the output in case anyone wants it.

**Comment by kvch** [comment]
+1
I think the option @ruflin is referring to is `--quiet` or `-q`.

**Comment by roncohen** [comment]
So, is it a backwards incompatible change if the beat started outputting to STDOUT by default?

adding `-q` definitely makes sense by the way

**Comment by ruflin** [comment]
@roncohen I think that is the big question. I wonder if there are use cases in the way people start a beat with a script and don't expect output but have one after updating. But can't really think of a reasonable example. Thoughts?

**Comment by roncohen** [comment]
I can certainly think of situations where this would be annoying and unexpected, but I would expect very few people to experience that and the fix is simple: add the `-q` flag. 

I'm +1 on changing this for 6.3, but APM Server doesn't have the install base that Filebeat has, so I understand if you feel differently.

**Comment by ruflin** [comment]
@roncohen Can you elaborate on the cases you think it will breaking, that will make it easier to decide if we are ok with breaking these. In general I'm +1 on this change in a minor. @elastic/beats other opinions / thoughts?

**Comment by Hexilee** [comment]
I think using -q flag to disable outputting to STDOUT is easy to understand for senior user while using -e flag to enable outputting to STDOUT may be a litter confusing for newcomers.
