### ISSUE TITLE
Fileset generator creates outdated kibana directory

### ISSUE THREAD

**Issue by kvch** [elastic/beats#6161]
The layout of the kibana dir was changed, but it was not followed up in the generator script.
Expected:
```
 └── kibana
     └── 6
```
Actual:
```
└── kibana
    └── default
```

**Comment by crazyvikas23** [comment]
@kvch are you talking about hardcoding directory structure in [this](https://github.com/elastic/beats/blob/master/filebeat/scripts/generator/fileset/main.go#L36) line?

**Comment by kvch** [comment]
Yes, I am. It supposed to be 6 instead of default.
