### ISSUE TITLE
Filebeat Issue

### ISSUE THREAD

**Issue by Vikran** [elastic/beats#617]
Hi Team.

I have recently migrated from logstash forwarder to filebeat and the migration was smooth and i was seeing logs in kibana but excitement was short lived as it stopped logging. Logstash has following errors:
```
"@timestamp"=>"2016-01-04T12:16:44.377Z", "beat"=>{"hostname"=>"blinded", "name"=>"blinded"}, "count"=>1, "fields"=>nil, "input_type"=>"log", "offset"=>54743, "source"=>"/var/log/trans.log", "type"=>"trans", "host"=>"blinded", "client"=>"10.168.1.101", "port"=>"47473", "que"=>"51.60.141.41.in-addr.arpa", server"=>"10.168.1.186"}, "que"]}>>, :level=>:error}
```
I have noticed error "IP Field contained invalid IP address or hostname " for que field i am using grok IPORHOST the changed to NOTSPACE to troubleshoot but error and issue remains.

Followed by slowing down error but i dont get anything in elasticsearch or kibana : 
```
{:timestamp=>"2016-01-04T12:55:08.014000+0000", :message=>"CircuitBreaker::rescuing exceptions", :name=>"Lumberjack input", :exception=>LogStash::SizedQueueTimeout::TimeoutError, :level=>:warn}
``````
Any help is appreciated else i have to go back to logstash .

Regards
Vik

**Comment by ruflin** [comment]
@Vikran This actually more looks like an issue in the logstash-beats-plugin. Which version of the plugin do you have installed? Can you update the plugin to make sure you have the most recent version? The plugin code can be found here: https://github.com/logstash-plugins/logstash-input-beats @ph Can you help here?

**Comment by ph** [comment]
@Vikran This  usually mean something is slowing down the ingestion, do you have other configured inputs? Are they succeeding to insert data into elasticsearch?

**Comment by Vikran** [comment]
@ruflin I am using 2.0.4 should i be updating ?

**Comment by Vikran** [comment]
@ph i have other inputs using logstash-forwarder, this is the first input which i am migrated to filebeat without issue.
