### ISSUE TITLE
Incorrect module path reported when no modules configured

### ISSUE THREAD

**Issue by ceeeekay** [elastic/beats#6171]
Testing filebeat in the foreground with a basic config I noticed an error in the reported module path. I'm not sure if this affects anything as I"m not currently using modules.

- Version: 6.1.2
- Operating System: Ubuntu 14.04.5
- Steps to Reproduce: Install filebeat-6.1.2-amd64.deb and run from cmdline.

Output:
`2018/01/25 00:45:22.190134 modules.go:95: ERR Not loading modules. Module directory not found: /usr/share/filebeat/bin/module`

Note `bin` in path.

**Comment by exekias** [comment]
Hi @ceeeekay, how did you launch filebeat? Normally you would use a wrapper script we leave under `/usr/bin/filebeat`, it configures the right paths for settings and logs, including modules directory

**Comment by ceeeekay** [comment]
Hi there, normally for testing purposes I would use `/usr/share/filebeat/bin/filebeat -c /etc/filebeat.yml -e -d "*"` to get output to stdout. Is this no longer correct?

**Comment by exekias** [comment]
You can use it like that, but some paths are not correctly configured, this is the wrapper we use: 
https://github.com/elastic/beats/blob/master/dev-tools/packer/platforms/debian/beatname.sh.j2

As you can see, it takes care of setting `path.home`, `path.config`, `path.data` and `path.logs`

**Comment by ceeeekay** [comment]
@exekias OK, thanks - I wasn't aware it had changed - I've been using this method to start it manually for quite a while :)
