### ISSUE TITLE
Packetbeat HTTP parsing fails on empty status phrase

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#6176]
An HTTP response whose status phrase is empty causes the following error:

> 2018-01-25T10:50:49Z WARN Failed to understand HTTP response status: 302

For example :
```
HTTP/1.1 302
Location: http://172.17.0.12:8080/resources/userinfo
Content-Length: 0
Date: Thu, 25 Jan 2018 10:50:48 GMT
Connection: close

```

The response parser in https://github.com/elastic/beats/blob/master/packetbeat/protos/http/http_parser.go#L224 is expecting the status-phrase to be non-empty.

From [this question on discuss](https://discuss.elastic.co/t/failed-to-understand-http-response/117036).

**Comment by mbudnick** [comment]
The warning tells status:302 so the status seems to be parsed?

See my full log file for more examples: [packetbeat.log](https://github.com/elastic/beats/files/1664021/packetbeat.log)

Packetbeat and tomcat running together in a docker-container. Maybe there is a problem with docker network because of logged messages "Ignore empty non-FIN packet"?

**Comment by adriansr** [comment]
@mbudnick It is failing because it expects something else after the status code. Your server status response is in the form:
> HTTP/1.1 200
> HTTP/1.1 302

When packetbeat is expecting a non-empty status phrase:
> HTTP/1.1 200 OK
> HTTP/1.1 302 Found

**Comment by jreyeshdez** [comment]
Hello @adriansr 

I was checking and testing this issue and about to commit it to my fork but it seemed to obvious to me where the issue might be that I'd rather leave the question in this issue before actually make a PR.

In the function [`parseResponseStatus`](https://github.com/elastic/beats/blob/81f55f89fd1db748d0063e4e3c0564913e23ee46/packetbeat/protos/http/http_parser.go#L210) I would only do the following:
→  `return uint16(statusCode), []byte(http.StatusText(statusCode)), nil` 
And delete the `phrase := s[p+1:]` as well as the `if-statement check`

Let me know what you think about this change.

**Comment by adriansr** [comment]
Hi @jreyeshdez 

I think it's better to just return the phrase, even if empty, instead of an error.
Also, it will be cool if you can add a test case in http_test.go

**Comment by xkoomy** [comment]
Hi @adriansr
I see an implementation HTTP 1.1 where in status line is no space after status code (i.e. HTTP/1.1 200\r\n). In this case parseResponseStatus still doesn't work even after the patch. We can debate that HTTP standard says the space is mandatory but life looks different. For instance I got this case now during my job and have to workaround it. 
Could you consider change parseResponseStatus to support such status lines too?
--
xkoomy

**Comment by adriansr** [comment]
@xkoomy I've submitted a patch for the issue: #6631
