### ISSUE TITLE
Windows instructions vary

### ISSUE THREAD

**Issue by roncohen** [elastic/beats#6196]
Sometimes there's a `.\` sometimes there isn't. In our tests in PS, it seemed that the `.\` was necessary.

![image](https://user-images.githubusercontent.com/744/35450779-507837f2-02c1-11e8-8649-1fa486c28126.png)

**Comment by andrewkroh** [comment]
+1  The `.\` is needed in these cases.

We don't instruct the user to put our binaries on their PATH.

**Comment by ruflin** [comment]
@dedemorton As #6941 is merged, can this one be closed?

**Comment by dedemorton** [comment]
Yes. Closing....
