### ISSUE TITLE
MetricBeat get system socket data incomplete

### ISSUE THREAD

**Issue by yang59324** [elastic/beats#6218]
Beats version 5.5.1
Elasticsearch output cluster version 2.3.5.
Operating system Centos6.5 64 bit.

MetricBeat start (or restart) can get a lot of system.socket.remote.ip, but the next time collection, system.socket.remote.ip becomes one, there is a lot of view on the server terminal socket link Upgrade to 5.6.6 version and 6.1.2 version of this problem still exists.

**Comment by yang59324** [comment]
But since then has been only one remote_ip, in fact, there are many remote_ip. How do we use metricbeat redis connection statistics?

**Comment by andrewkroh** [comment]
> How do we use metricbeat redis connection statistics?

Please use https://discuss.elastic.co/c/beats for questions.

**Comment by andrewkroh** [comment]
> But since then has been only one remote_ip, in fact, there are many remote_ip.

Can you please share the configuration you are using.

Can you provide details about what events you are seeing reported and what's missing. Show the events system.socket reports and show what `ss` reports that is missing from Metricbeat's data.

**Comment by ruflin** [comment]
Closing this as I assume the question has either been resolved or moved to discuss.
