### ISSUE TITLE
Logging level issues

### ISSUE THREAD

**Issue by roncohen** [elastic/beats#6239]
@simitt found a problem with logging configuration:

* log level warning actually needs to be warn, otherwise an error is thrown and the server doesn't start (fixed in https://github.com/elastic/beats/pull/6184/commits/5f597df1d2cf402fa3bfa3e32a26e8f7904466e1)
* log level error still outputs info and warn logs.
* log level warn still outputs info logs.

**Comment by andrewkroh** [comment]
This looks like the cause. It is supposed to have been a check for the -v flag but I forgot to check the ‘verbose’ value.

https://github.com/elastic/beats/blob/master/libbeat/logp/configure/logging.go#L43

Want to open a PR to fix it? I won’t be online for a bit. The needs to be applied to 6.2.
