### ISSUE TITLE
Topbeat: Different interval for proc, fs, cpu

### ISSUE THREAD

**Issue by oazabir** [elastic/beats#624]
Usually file system changes are slow where proc and CPU states change quite frequently. it would be good to have different intervals for each type of event. We can save a lot of storage this way. 

Eg. Filesystem interval 10 mins.
CPU every minute.
Proc every 5 min.

**Comment by ruflin** [comment]
In metricbeat a module can be defined multiple times with metricsets and different periods. That will solve the above problem. Closing this issue.
