### ISSUE TITLE
how to fix this sh*t?

### ISSUE THREAD

**Issue by Nurlan199206** [elastic/beats#6257]
Ubuntu 17.10

in` filebeat.yml ` i am already binded `IP`

```
setup.kibana:
host: "172.27.1.54:5601"
```

root@fssp:/etc/filebeat# filebeat setup --dashboards

Exiting: Error importing Kibana dashboards: fail to create the Kibana loader: Error creating Kibana client: fail to get the Kibana version:HTTP GET request to /api/status fails: fail to execute the HTTP GET request: Get http://localhost:5601/api/status: dial tcp [::1]:5601: getsockopt: connection refused. Response: .

**Comment by andrewkroh** [comment]
Use the correct indentation for the YAML configuration. See the example in the [documentation](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration.html).

```
setup.kibana:
  host: "172.27.1.54:5601"
```

You can also write it like this:

```
setup.kibana.host: "172.27.1.54:5601"
```

Please use https://discuss.elastic.co/c/beats for questions.

**Comment by Nurlan199206** [comment]
Thank you dude, it's now working

**Comment by weyderfs** [comment]
Here not works :(

**Comment by philiahe** [comment]
Here not works :(

**Comment by jmontoyac** [comment]
Does not work even with the correct indentation.

**Comment by mdnuts** [comment]
just a note in the event someone runs across this (like I did).  I had the setup.kibana.host as 127.0.0.1:5601 which always gave a connection failed.  Changing it to the FQDN:5601 worked.
