### ISSUE TITLE
Hyper-V Monitoring using ELK Stack

### ISSUE THREAD

**Issue by PauliniMrtns** [elastic/beats#6282]
Hello all!

I'm currently deploying an ELK cluster for monitoring several virtualization platforms.
I'm currently using vSphere module for monitoring VMWare vCenter resources using Metricbeats, but and I also have some Miscrosoft Hyper-V hypervisors running.

I tried to search all around for an Hyper-V plugin for Logstash or a module for Beats but I wasn't so lucky :)

Before venturing into developing my own module/input, can anyone give me some feedback on such an issue, has anyone came across with this at anytime or may there be something out there that I've missed?

Thank you all in advance for your help!
Cheers!
PM

**Comment by exekias** [comment]
We don't have a module for this in Metricbeat, but a contribution would be really appreciated! Feel free to ask for pointers if you decide to go for implementing it :innocent: This is a good start: https://www.elastic.co/guide/en/beats/devguide/current/metricbeat-developer-guide.html

**Comment by davemaharshi7** [comment]
Hi @exekias,
I was looking for requirements for implementing a new module for monitoring Hyper-V in the metricbeat.

Thanks,
MD

**Comment by Nulluzz** [comment]
👌🏻👌🏻
