### ISSUE TITLE
Add compression to file output

### ISSUE THREAD

**Issue by gwsales** [elastic/beats#6288]
Add gzip compression for file output to save on disk space or other compression that works well with go.

**Comment by agathver** [comment]
Hi,
I'm interested to take this one up.

Should this be added as a new key like `filter` or `compressor`?

**Comment by ruflin** [comment]
Let's discuss first a bit more details on how this would work and the uses cases. 

@gwsales Can you share a bit more details on your use case?

**Comment by gwsales** [comment]
Sure. Logstash has a gzip option on its file output, that’s basically what functionality I’d like to see on beats. Beats currently can write to disk but there is no compression, I’d like to limit my filebeat, auditbeat and winlogbeat outputs to 100M of disk space when using file output and would like some basic compression on the output files.

**Comment by andrewkroh** [comment]
I recently refactored the [file writing code](https://github.com/elastic/beats/blob/master/libbeat/common/file/rotator.go) that is shared between the file output and logger. I imagine that it would be relatively easy to hook in an optional compression feature that runs on rotation.

Any contributions would need tests to ensure that the existing rotation code work properly with a mix of gzip and non-gzipped files.

**Comment by ruflin** [comment]
@agathver Do you want to open a PR with a proposal? This could make discussing the details easier and see where the hidden problems are.

**Comment by agathver** [comment]
@ruflin Yes I intend to start a PR. Was reading the code around `rotator.go`

Here are some quick questions:

1. Rotator currently has a `maxSizeBytes`, to limit the maximum size of bytes written. How would this work with a compression writer? That is, should `maxSizeBytes` refer to the compressed data size or uncompressed data size?
2. Another popular method of compressing logs is deferring the compression till rotation, in this file is written uncompressed and backups older than a certain threshold (say 1 day old) are compressed in the background. After rotation, compression of an older backup is automatically triggered.

**Comment by ruflin** [comment]
@andrewkroh you might be best to comment on the above questions?

**Comment by andrewkroh** [comment]
The compression is being deferred until rotation in the PR (#6577) and I like this behavior. And +1 for gzip.

**Comment by Euqaidoz** [comment]
Hi, this would be a very nice thing to have!
