### ISSUE TITLE
Add disk cache for outputs when destination is down

### ISSUE THREAD

**Issue by gwsales** [elastic/beats#6289]
For mobile clients that frequently go off network I need a cache on disk that will retain X number of events until the host is back online. 

Set limit to be in Kb or total number of events to cache. Should store in compressed files until connectivity is restored to the destination, when online send real-time events as a priority and work through the cache as allowed. 

Current workaround is to use winlogbeats to write to rotating json files and read the logs with filebeats or other agents.

**Comment by ph** [comment]
This is linked to #575

**Comment by ph** [comment]
I will close this in favor of the disk/spooling issue.
