### ISSUE TITLE
[Request]  Any way to set the permissions for the registry file.

### ISSUE THREAD

**Issue by umisora** [elastic/beats#6293]
refs : https://discuss.elastic.co/t/filebeat-registry-permissions/113850

We want to change permission to registry files.

Usecase:
  I want to monitor filebeat process by datadog agent.
  Datadog Agent use registry file when monitor. 
  Datadog Agent runs with dd-agent user. so registry file can't read.
   I want change permission 600 to 644.

  refs : https://github.com/DataDog/integrations-extras/blob/master/filebeat/check.py#L35

For confirmed bugs, please report:
- Version: filebeat version 5.3.1 (amd64), libbeat 5.3.1
- Operating System: CentOS release 6.8 (Final)

thank you.

**Comment by jaipradeesh** [comment]
@monicasarbu Should the permission be set to `0644` by default or configurable?

**Comment by jaipradeesh** [comment]
@monicasarbu https://github.com/jaipradeesh/beats/commit/f5122c6cc5c67c4bab5155361472e6dc8afd00e4 works?

Will create a PR with updates to docs, configuration reference, etc, .. post approval.

**Comment by kvch** [comment]
@jaipradeesh Please open a PR with the description of your changes. It makes reviewing your code easier. Also, we can discuss possible changes if needed.

**Comment by jaipradeesh** [comment]
@kvch https://github.com/elastic/beats/pull/6455

Yet to update docs, configuration reference, etc,..

**Comment by wk8** [comment]
Thanks @umisora ! We need this too :) ....

**Comment by urso** [comment]
I think this has been merged long ago :)
