### ISSUE TITLE
HTTP Module JSON Metricset POST Method Content-Type Header Undefined

### ISSUE THREAD

**Issue by preiner** [elastic/beats#6320]
MB 6.2 HTTP Module fails to defined any value for Content-Type header when method is set to POST. Preferably there should be a configuration setting to set it to whatever value the user requires.

Currently the header is completely missing and java spring framework throws a http 415 error that it wont allow Content-Type set to null

metricbeat.modules:
  - module: http
    metricsets: ["json"]
    period: 10s
    hosts: ["localhost:8080"]
    namespace: "json_namespace"
    path: "/healthcheck"
    body: "dummydata"
   **method: "POST"**
    #request.enabled: true
    #response.enabled: false
    #dedot.enabled: false
    **Content-Type: "application/json"**  __*proposed new configuration setting*__

**Comment by exekias** [comment]
I think you can use `headers` setting to define it, something like this:

```
module: http
metricsets: ["json"]
period: 10s
hosts: ["localhost:8080"]
namespace: "json_namespace"
path: "/healthcheck"
body: "dummydata"
method: "POST"
headers:
   Content-Type: "application/json" proposed new configuration setting
```

**Comment by preiner** [comment]
Unless I am misreading the source, headers isnt a defined field in the struct (neither is it in the documentation).
Below is the snippet from the http module structure definition.
`
type MetricSet struct {
	mb.BaseMetricSet
	namespace       string
	http            *helper.HTTP
	method          string
	body            string
	requestEnabled  bool
	responseEnabled bool
	deDotEnabled    bool
}`

**Comment by iahmedov** [comment]
@preiner http module uses `github.com/elastic/beats/metricbeat/helper` package for HTTP requests [http, err := helper.NewHTTP(base)](https://github.com/elastic/beats/blob/master/metricbeat/module/http/json/json.go#L81), which in turn has this configs:
```
TLS     *outputs.TLSConfig `config:"ssl"`
Timeout time.Duration      `config:"timeout"`
Headers map[string]string  `config:"headers"`
```

probably this should be a documentation enhancement

**Comment by preiner** [comment]
thanks. Ill try this tomorrow.

**Comment by ruflin** [comment]
@preiner I'm going to close this issue as I assume the above worked. Please reopen if you still have the issue. On our end we need to add the docs for it.
