### ISSUE TITLE
Update documentation to mention that beats monitoring works only with Elasticsearch + Xpack 6.2.0

### ISSUE THREAD

**Issue by ph** [elastic/beats#6329]
Currently beats monitoring will only work on Elasticsearch + Xpack 6.2.0, before that version the monitoring API doesn't know about beats data. We should add the requirement in the monitoring docs.

It will also display a cryptic error to the users see #6328

**Comment by ph** [comment]
@dedemorton Is there any special warning/tag we should use for that in the docs?

**Comment by moshe0076** [comment]
Thanks!

**Comment by dedemorton** [comment]
Closed in #6651
