### ISSUE TITLE
Allow searching and aggregations on the `nginx.access.url` field

### ISSUE THREAD

**Issue by karmi** [elastic/beats#6349]
Currently, the `nginx.access.url` field in the Nginx module is set to be mapped as `keyword`: https://github.com/elastic/beats/blob/e60549527f3c5a8fe3ced17b7106e9cd12fc2112/filebeat/module/nginx/access/_meta/fields.yml#L26-L27

Therefore, the whole URL, eg. `/application.css`, `application.js?t=12345`, `index.html`, `index.php?id=foo`, `index.php?id=bats`, and so on, is indexed as one big string.

This makes it unnecesary hard for users to answer questions like "what percentage of requests is for CSS assets", to satisfy a requirement like "filter this dashboard only for *.html requests".

I suggest, as a first step, that the Elasticsearch template is extended with the [`fields` ("multi-fields")](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html) configuration, so the `nginx.access.url` field is indexed as `keyword` by default, keeping the current behaviour, but also eg. with the standard analyzer, ie. as `nginx.access.url.text`. (If this would be problematic, another field, `nginx.access.url_text` can be added, but I'd rather use the Elasticsearch's `fields` mapping configuration, because that would allow adding other analyzers in future in a predictable and clean way.)

As a next step, the whole URL path and parameters can be made more friendly for search and aggregations: eg. automatically extracting the `extension` in the [ingest pipeline](https://github.com/elastic/beats/blob/e60549527f3c5a8fe3ced17b7106e9cd12fc2112/filebeat/module/nginx/access/ingest/default.json), therefore making a search or aggregation for `extension:png` trivial and fast. Even the URL parameters could be extracted into key:value pairs, eg. `key:id` and `value:foo`, therefore making it possible to search for `key:id AND value:foo` without blowing up the mapping.

The general motivation is to make the URL field as rich as eg. the `remote_ip ` or `user_agent` fields, which automatically extract geographical information, or operation system details.

**Comment by ruflin** [comment]
+1 on using multi_fields as a first improvement. This can be added in the `fields.yml` here: https://github.com/elastic/beats/issues/6349 Here is an example how multi_fields works in `fields.yml`: https://github.com/elastic/beats/blob/master/auditbeat/_meta/fields.common.yml#L26

@karmi For the ingest part, it would be nice if there would be an ingest processor that can be used for url fields so we don't have to create it ourselfs. Or a field type in ES that supports URI would also be nice ;-) We could also use this for file paths ...

**Comment by jswidler** [comment]
I'm a first time user of beats in the past week (been using ELK for a while), and this issue jumped out to me immediately - my use case is to group by prefixes, (ie compares counts of `api/v1/*` to `api/v2/*`).

+1 on better field typing for nginx.access.url

**Comment by karmi** [comment]
> (...) Or a field type in ES that supports URI would also be nice ;-) We could also use this for file paths ...
There's the [`path_hierarchy`](https://www.elastic.co/guide/en/elasticsearch/reference/master/analysis-pathhierarchy-tokenizer.html) tokenizer, which could be a good fit. But we would need to experiment with good support for _both_ searching and aggregations.

**Comment by alvarolobato** [comment]
This should be fixed with ECS migration.

**Comment by ruflin** [comment]
The issue will not directly fixed with ECS but we will have an advice for the users todo on this. It will the addition of `.text` as multifield proposed by karmi above.

And if the url should be split, we have support for this in ECS: https://github.com/elastic/ecs#url 

Closing also based on the comment from @webmat above and the follow up issue.
