### ISSUE TITLE
Filebeat 6.1 is not publishing syslog and container_log to kafka 0.11.0.1

### ISSUE THREAD

**Issue by sandeepsrkr** [elastic/beats#6354]
Hi @all,

I am using filebeat 6.1 and kafka 0.11.0.1 to push logs. From filebeat logs I could see that login credentials are validated successfully but then logs are not getting pushed.
Also when I updated filebeat’s output.kafka.version to 0.11.0.1 I get error message :
```
2018/02/08 09:41:15.417691 beat.go:635: CRIT Exiting: error initializing publisher:  unknown/unsupported kafka version '0.11.0.1' accessing 'output.kafka' (source:'/etc/filebeat/filebeat.yml')
Exiting: error initializing publisher: unknown/unsupported kafka version '0.11.0.1' accessing 'output.kafka' (source:'/etc/filebeat/filebeat.yml')
```
If I comment output.kafka.version and proceed I encounter 
```
Kafka publish failed with: circuit breaker is open
```
I used kafka 0.10.2.0 and updated filebeat’s output.kafka.version to 0.10.2.0 and the error message is gone but I do not get any logs in kafka. Filebeate throws
```
Kafka publish failed with: circuit breaker is open
```
And after some time it throws below message in a loop:
```
2018/02/09 15:08:13.075932 client.go:234: DBG [kafka] Kafka publish failed with: circuit breaker is open
2018/02/09 15:08:13.110793 client.go:220: DBG [kafka] finished kafka batch
2018/02/09 15:08:13.110814 client.go:234: DBG [kafka] Kafka publish failed with: circuit breaker is open
2018/02/09 15:08:13.149482 metrics.go:39: INFO Non-zero metrics in the last 30s: beat.info.uptime.ms=30000 beat.memstats.gc_next=18583840 beat.memstats.memory_alloc=17667464 beat.memstats.memory_total=3883962925856 filebeat.harvester.open_files=11 filebeat.harvester.running=10 libbeat.config.module.running=0 libbeat.output.events.batches=832 libbeat.output.events.failed=1703936 libbeat.output.events.total=1703936 libbeat.pipeline.clients=2 libbeat.pipeline.events.active=4118 libbeat.pipeline.events.retry=1703936 registrar.states.current=21
```
Also I built filebeat 6.0 from source and used kafka 0.11.0.1 but I was facing similar issues.

I test filebeat 5.6.4 with kafka 0.11.0.1 and it is working just fine. 
My OS is `Linux  4.1.12-112.14.13.el7uek.x86_64`.

Please let me know if you require further information. 

Thanks for helping out.
Sandeep Sarkar

**Comment by danielmotaleite** [comment]
+1 with the same problem, filebeat 6.2.4, kafka 1.0

**Comment by danielmotaleite** [comment]
Found my problem, the field variable used to define the topic had a typo, so it was always empty. Without topic, filebeat kafka output returns this error.  

I do not know if there other reasons to return this too, but at least recheck your kafka output config and if you use fields variables, try to temporally replace then with hardcode string to test.

**Comment by kvch** [comment]
This issue is for an old version of beats, I suggest to try out the latest version of beats. If this is still a problem in the newly released version feel free to reopen this issue. Thanks. Also, if you have any questions, please post a question on our Discuss forum: https://discuss.elastic.co

**Comment by inqueue** [comment]
Relates to https://github.com/elastic/beats/pull/20094?

**Comment by VertexC** [comment]
Still got the same issue
- filebeat: 7.9.2
- kafka: 2.13

Kafka topic is already hardcoded in config.
```yml
  173 # ----------------------------- Kafka Output--------------------------------
  174 output.kafka:
  175   enable: true
  176   hosts: ["kafka1:9092"]
  177   topic: "test"
  178   partition.round_robin:
  179     reachable_only: false
  180   required_acks: 1
  181   compression: gzip
  182   max_message_bytes: 1000000
```

```bash
2020-10-21T15:36:55.937+0800    DEBUG   [kafka] kafka/client.go:277     finished kafka batch
2020-10-21T15:36:55.937+0800    DEBUG   [kafka] kafka/client.go:291     Kafka publish failed with: circuit breaker is open
2020-10-21T15:36:55.937+0800    INFO    [publisher]     pipeline/retry.go:219   retryer: send unwait signal to consumer
2020-10-21T15:36:55.937+0800    INFO    [publisher]     pipeline/retry.go:223     done
2020-10-21T15:36:55.938+0800    DEBUG   [kafka] kafka/client.go:277     finished kafka batch
2020-10-21T15:36:55.938+0800    DEBUG   [kafka] kafka/client.go:291     Kafka publish failed with: circuit breaker is open
2020-10-21T15:36:55.938+0800    INFO    [publisher]     pipeline/retry.go:219   retryer: send unwait signal to consumer
2020-10-21T15:36:55.938+0800    INFO    [publisher]     pipeline/retry.go:223     done
```
