### ISSUE TITLE
Please provide static templates and dashboards

### ISSUE THREAD

**Issue by sempervictus** [elastic/beats#6355]
We deploy ELK with Chef, on Linux systems. Beats get pushed to Linux and Windows hosts, and have to send data back to LogStash (we close up ES and Kibana, leaving only LS and nginx+tls+httpauth exposed). We cant generate templates and push them to ES from the windows hosts, ES is firewalled off. We also cant generate the winlogbeat templates on linux machines and push them up, nor can we import Kibana dasboards without localhost:5601 access from an ELK member (again Linux, and doesnt have all the beats installed on it).

Usually we keep the templates and dashboards with the ELK cookbooks, while our beats CB just handles the endpoint deployment and config. Now we are stuck because beats 6 seems to assume direct access to ES and Kibana which is not safe by any means (http://bfy.tw/GYiv).

Can Elastic Co provide static index templates and kibana dashboards/vis/search in a consistent place for each beat/all beats? There used to be a repo for this... The current system of having beats generate this stuff on the fly severely constrains operations and makes even the most basically isolated services (for security purposes) impossible to use. Please consider that log data is often seen as beholden to compliance regulations, so log aggregation platforms have to be locked down in quite a few places precluding direct access to APIs which could alter data in ES from systems other than the host running ELK (or its peer cluster members for replication).

**Comment by ruflin** [comment]
There is the command `metricbeat export template` where you can generate the file. I wonder if that is enough for the template?

**Comment by sempervictus** [comment]
That's how I've been trying to feed chef - first time I get a new version set up I run all the beats exporters, collect results and push to elk with net/http... However, winlogbeat doesn't run on the Linux host where I'm testing the cookbook, so I guess I'll need to collect from one separately. Its silly. Why not include the default beats templates in es or at least as json on github? The yaml stuff is clever for custom deployments but not friendly in the least.

**Comment by ruflin** [comment]
Let me take a step back on why we removed the template and started to dynamically generate it. It all started with 1 template which was shipped. Going forward we had a 2.x and 5.x template and came to the point where we had to add not only a template for 6.x but potentially also for minor versions to make use of new versions. Out of `fields.yml` we can generate all the different templates for the target elasticsearch instance. This would also mean in Git we would have quite a few files versioned. 

Getting back to your problem above: The Winlogbeat issue is definitively I haven't though of. This part of Winlogbeat would work on any machine but we don't provide the binary. One work around here would be to use the `fields.yml` from Winlogbeat and use Metricbeat to create the json template. This should work as the code is not beat specific. 

So far what we recommended for loading the templates or dashboards in larger deployment is exactly what you did above. Except that we missed the winlogbeat case. I wonder if for this reason there should also be a linux binary for winlogbeat? Alternatively there could be a `beats-helper` binary that only has the command functionalities like loading templates, dashboards, testing connections but no actually beats functionality that can be used in the above cases.

**Comment by sempervictus** [comment]
I tried the trick of using filebeat on the wiblogbeat yml, doesn't fly - the resulting template is still for file beat but with some winlogbeat fields :-).
Thanks for looking into this

**Comment by ruflin** [comment]
Here is a workaround that should work: `./filebeat export template -E setup.template.pattern=winlogbeat-6.2.2-*` The generated template should be identical to the one from winlogbeat. 

We discussed the issue internally but didn't come to a conclusion yet on how to solve it best.

**Comment by sempervictus** [comment]
Including a default template for the same version of ES (makes life a lot easier to version match em) couldn't hurt, right? The yaml options' still there for the folks tuning it.
Thanks for looking into it, will try the winlogbeat bit again.

**Comment by ruflin** [comment]
Having ES and Beats version in sync is definitively something we encourage. But unfortunately I would say in the majority of the cases either Beats is behind or ahead. The part I worry with adding a template.json file to be shipped with Beats is that people will just apply it manually to their ES version if they can't apply it automatically and don't think about the versions and compatibility. Loading the wrong versions of the templates is unfortunately one of the more common issues we see on discuss.

Still your use case is a very good example on why it could be useful especially because of the winlogbeat export problem. I'm hoping the work around works for now and that we can come up with a more generic solution in the long run here.

**Comment by sempervictus** [comment]
Indices are versioned for beats, maybe do the same with the template file for clarity about versioning? Thanks for digging into this, we have a number of large deploys this year, prefer to avoid monkeypatching...

**Comment by jordansissel** [comment]
@sempervictus In the meantime, specific to winlogbeat, I've got a docker image that works around it and lets me run `winlogbeat setup` on Linux. I've only tested it with winlogbeat 7.3.2. More details on [this issue](https://github.com/elastic/beats/issues/13707#issuecomment-532329554).

**Comment by ruflin** [comment]
Over the last months we have been working on a new project called Ingest Manager. It centralises the management of dashboards and templates to solve exactly the above problems. Have a look here: https://www.elastic.co/guide/en/ingest-management/current/ingest-management-getting-started.html

**Comment by jsoriano** [comment]
I guess this can be considered as solved by [fleet](https://www.elastic.co/guide/en/fleet/7.12/fleet-overview.html)? :slightly_smiling_face:

Closing by now, please reopen if something would be missing.
