### ISSUE TITLE
Metricbeat - Add config to Ignore failures for non-existent counters

### ISSUE THREAD

**Issue by krasekhi** [elastic/beats#6362]
Add config option to ignore failures for non-existent counters

Issue - when one of the defined perfmon WMI counters no longer exists the service stops and will not start back up until the WMI counter is fixed. Being able to ignore the failures for non-existent counters would be massive improvement so all the data is not lost from the endpoint.

**Comment by krasekhi** [comment]
Looks like the enhancement request above may be a duplicate and is already being developed -  https://github.com/elastic/beats/pull/6432 ? Should this threat be closed?

Thanks

**Comment by andrewkroh** [comment]
Yep, sounds like it's in the works now so we can close this. Thanks
