### ISSUE TITLE
[docs] SSL mutual authentication requirements for Logstash Beats input

### ISSUE THREAD

**Issue by inqueue** [elastic/beats#6373]
Version 6.1.

The [documentation](https://www.elastic.co/guide/en/beats/metricbeat/6.1/configuring-ssl-logstash.html) for securing communication with Logstash by using SSL should be clear that SSL mutual authentication is required by the Logstash Beats input plugin. The opening statement:

```
You can use SSL mutual authentication to secure connections between Metricbeat and Logstash. 
```

is leaving the belief that SSL mutual authentication is optional when setting up SSL. If SSL between Beats and Logstash is desired, mutual authentication must be configured or the connection fails with an error on the Logstash side.

```
[2018-02-13T11:52:58,079][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: undefined] Exception: javax.net.ssl.SSLHandshakeException: error:100000c0:SSL routines:OPENSSL_internal:PEER_DID_NOT_RETURN_A_CERTIFICATE
```

Related to this, could the SSL section of the Logstash output [documentation](https://www.elastic.co/guide/en/beats/metricbeat/6.1/logstash-output.html#_literal_ssl_literal_2) point to the relevant document [here](https://www.elastic.co/guide/en/beats/metricbeat/6.1/configuring-ssl-logstash.html)?

**Comment by andrewkroh** [comment]
@inqueue, Are you sure the Logstash requires mutual authentication? My understanding is that client authentication is not required by default. [ssl_verify_mode](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html#plugins-inputs-beats-ssl_verify_mode) defaults to `none` in the Logstash beats input.

**Comment by inqueue** [comment]
@andrewkroh @ph uncovered the real [issue](https://github.com/logstash-plugins/logstash-input-beats/issues/300), so we can close this one.
