### ISSUE TITLE
Topbeat's own CPU usage

### ISSUE THREAD

**Issue by oazabir** [elastic/beats#638]
I was looking at topbeat's own CPU usage and the numbers look quite high:

proc.name:topbeat.exe 
proc.cpu.user:6,575,234 
proc.cpu.user_p:1% 
proc.cpu.system:7,027,703 
proc.cpu.total:13,602,937

Should they be so high?

**Comment by andrewkroh** [comment]
"proc.cpu.user_p:1%" - That doesn't look high.

I cannot judge the `proc.cpu.total`, `proc.cpu.user`, or `proc.cpu.system` values since they are cumulative.

I suggest looking at the data over time using Kibana.
