### ISSUE TITLE
Add allocatable and capacity totals for pod, memory and cpu to the node metricset for Kubernetes

### ISSUE THREAD

**Issue by simianhacker** [elastic/beats#6380]
Add the following fields to the `node` metricset:

- `kubernetes.node.pod.allocatable.total`
- `kubernetes.node.pod.capacity.total`
- `kubernetes.node.memory.allocatable.bytes`
- `kubernetes.node.cpu.allocatable.nanocores`

This way they can be queried with `beat.hostname`

**Comment by exekias** [comment]
ey @simianhacker, is this still valid or you think we can close it already?

**Comment by exekias** [comment]
closing, please reopen if needed
