### ISSUE TITLE
Beat uninstall-service-[beatname].ps1 do not stop the service before remove

### ISSUE THREAD

**Issue by palethorper** [elastic/beats#6389]
The uninstall-service-[beatname].ps1 script do not have a section to stop the service before removing it.
The install script do already include the log to atop the service before installing new version.

- Operationing System : Windows
- Version: up to 6.2.1

- Steps to reproduce:
1. Have a beat (filebeat, winlogbeat, metricbeat etc) service installed and running on windows
2. Run the uninstall script that is included in the package. e.g. uninstall-service-filebeat.ps1

The uninstall will not succeed.

Fix:
Include the stop service log in the uninstall script
`# delete service if it already exists
if (Get-Service filebeat -ErrorAction SilentlyContinue) {
  $service = Get-WmiObject -Class Win32_Service -Filter "name='filebeat'"
  $service.StopService()
  Start-Sleep -s 1
  $service.delete()
}`

**Comment by andrewkroh** [comment]
Could you please open a pull request for this change?

The file that needs the modification is at https://github.com/elastic/beats/blob/master/dev-tools/packer/platforms/windows/uninstall-service.ps1.j2. It is a template that is shared by all Beats so any time you need to reference the name use the variable `{{.beat_name}}`.

**Comment by palethorper** [comment]
Yep - just forked it and doing it now.

**Comment by michha** [comment]
As I look into https://github.com/elastic/beats/blob/master/dev-tools/packaging/templates/windows/uninstall-service.ps1.tmpl it has the StopService call implemented, but filebeat-6.3.2 x64 (24th July) is still missing the StopService in the uninstall PowerShell script

**Comment by michha** [comment]
Version 6.4 released yesterday fixed this 👍 
This issue can be resolved as fixed in v6.4
