### ISSUE TITLE
Kubernetes dashboard memory calculation is time range dependent 

### ISSUE THREAD

**Issue by mbrancato** [elastic/beats#6395]
In the Kubernetes dashboard from metricbeat 6.2.1, the `Memory usage by node [Metricbeat Kubernetes]` dashboard places a red line to show available memory. This line is time range dependent on the query, it expects a 15 minute time range. Changing the time range results in a scaled graph.

- Version:  6.2.1
- Operating System: Linux / Kubernetes 1.9.2
- Steps to Reproduce: Change time range on Kubernetes dashboard

e.g.

    Quick -> Last 15 Minutes

![image](https://user-images.githubusercontent.com/8493275/36286387-7c56b7ce-127d-11e8-8ddf-b4ddccbbe961.png)

    Quick -> Last 4 hours

![image](https://user-images.githubusercontent.com/8493275/36286413-a8da7f10-127d-11e8-9008-83ecaa600465.png)

There's some strange scaling on `CPU usage by node [Metricbeat Kubernetes]` as well but I'm not sure if it is a bug or some averaging / min / max thing.

**Comment by exekias** [comment]
Thank you for reporting this, I'm now working on a fix

**Comment by mbrancato** [comment]
This appears to affect the CPU and available / unavailable pods. Its a different scaling issue, but same cause. Should we open a separate issue for those graphs? At 24 hours, the available pod counts are event 60x higher than the actual counts.

    15 minutes

![image](https://user-images.githubusercontent.com/8493275/36788598-83e7fbc2-1c5c-11e8-89c6-48a1edc2654a.png)

    1 hour

![image](https://user-images.githubusercontent.com/8493275/36788558-62ebe56e-1c5c-11e8-8245-b8d02457e1de.png)

    24 hours

![image](https://user-images.githubusercontent.com/8493275/36788625-a2a97892-1c5c-11e8-8b36-c1677a8c10f3.png)

**Comment by exekias** [comment]
Thanks @mbrancato, no need for a new issue for those, I will treat it in the same PR, thanks :)
