### ISSUE TITLE
6.2 version of metricbeat has a different mapping, giving errors in elasticsearch/Kibana

### ISSUE THREAD

**Issue by vioan** [elastic/beats#6399]
I have a few machines which send logs to an ELK machine. Yesterday I installed a new machine and then I observed Elasticsearch and Kibana giving errors:

**Elasticsearch:**
org.elasticsearch.transport.RemoteTransportException: [enc-monitoring][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [beat.name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.

**KIbana**
Courier Fetch: 5 out of 20 shards failed.

After having a look, I discovered that on that machine a new version was installed for metricbeat and the mapping is not the same as for the old version. Here is the mapping for the old version:

```
  "metricbeat-6.1.3-2018.02.07": {
    "mappings": {
      "doc": {
        "beat.name": {
          "full_name": "beat.name",
          "mapping": {
            "name": {
              "type": "keyword",
              "ignore_above": 1024
            }
          }
        }
      }
    }
  }
```
and here is the mapping for the new version:

```
  "metricbeat-6.2.1-2018.02.14": {
    "mappings": {
      "doc": {
        "beat.name": {
          "full_name": "beat.name",
          "mapping": {
            "name": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        }
      }
    }
  }
```
My quick solution was to delete that index with `curl -XDELETE localhost:9200/metricbeat-6.2.1-2018.02.14` and install the same version for metricbeat which I had on the other machines, 6.1.3

**Comment by andrewkroh** [comment]
What does this return for you?

`curl -XGET "http://localhost:9200/_template/metricbeat-6.2.1"`

**Comment by vioan** [comment]
now is not returning anything, because I don't have anymore indexes created with 6.2.1. I had just one index for 6.2.1 created when I installed and run the first time 6.2.1. I saw the errors, removed the new created index, and everything ok again

```
$ curl -XGET "http://localhost:9200/_template/metricbeat-6.2.1"
{}
```

**Comment by vioan** [comment]
and forgot to mention that Elasticsearch is 6.1.2, Logstash is 6.1.2 and Kibana is 6.1.3. Operating system is CentOS 7.4.1708

**Comment by andrewkroh** [comment]
It sounds like the Metricbeat index template for 6.2.1 was not installed. If you are sending the data through Logstash then you must install the index template manually. The instructions for doing so can be found [here](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-template.html#load-template-manually).

**Comment by vioan** [comment]
Actually on that machine I had SUSE and I had installed metricbeat 6.1.3 and I did:
```
metricbeat setup --template -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["localhost:9200”]'

metricbeat setup --dashboards
```
Then, I reinstalled the machine with CentOS, installed metricbeat 6.2.1 and the above happened. So, the index template was already in Elasticsearch from 6.1.3. Or, am I missing something?

**Comment by andrewkroh** [comment]
The index templates are versioned (hence the path `_template/metricbeat-6.2.1`) and only apply to indices created by that specific version of the Beat.

If you examine the template you'll see what indicies that it applies to.

```
$ ./metricbeat export template | head
{
  "index_patterns": [
    "metricbeat-6.2.1-*"
  ]
```

Therefore you must install the template from 6.2.1. Just having the 6.1.3 template installed is not sufficient.

**Comment by vioan** [comment]
ok, I understand. This also means that every time the *beat is updated I need to add manually the template, right?

**Comment by andrewkroh** [comment]
Yes, install the index template before ingesting data to avoid mapping problems.

**Comment by vioan** [comment]
Thank you!
