### ISSUE TITLE
Network bandwidth usage in topbeat

### ISSUE THREAD

**Issue by oazabir** [elastic/beats#640]
It would be great if topbeat could publish bytes in/out through the network adapters, which can then be shown on Kibana as Mbits/sec, or Gbits/sec. This would allow us to monitor network utilization on the servers and identify whether we are hitting network bottleneck. 

Something like what you see in Windows Performance Monitor:
![image](https://cloud.githubusercontent.com/assets/1611494/12140992/e48478c4-b463-11e5-927d-bb245694cdb9.png)

**Comment by mrkschan** [comment]
And, `nethogs` on linux :)

**Comment by S54B32** [comment]
Beats is great, though I would love to see this feature implemented! I've recently installed Topbeat and as far as I can see network interface usage monitoring is the only thing missing for my use case.

**Comment by tommyorndorff** [comment]
+1, this would be great

**Comment by tsdrach** [comment]
for me too )

**Comment by ruflin** [comment]
This feature request should be mostly covered by the system/network metricset in Metricbeat. Please test this out and let us know if that is what you needed. Closing this issue.
