### ISSUE TITLE
Make UDP input JSON aware 

### ISSUE THREAD

**Issue by maurorappa** [elastic/beats#6405]
Hi,
I noticed the UDP input (correctly marked as experimental) does not parse Json data but simply encapsulate the whole UDP payload in the message field.
Is there any plan to make it work like the log (file based) input?
Shall I try to make a patch for it?

Cheers

**Comment by ruflin** [comment]
You should be able to use the json decode processor here: https://www.elastic.co/guide/en/beats/filebeat/current/decode-json-fields.html

**Comment by maurorappa** [comment]
Thank you for the quick reply, I tested but it doesn't seem to work. 
I using the last stable with this bare minimum config:
````

**Comment by ruflin** [comment]
@maurorappa Let's move this to discuss. Please open a topic there: https://discuss.elastic.co/c/beats/filebeat

Can you please share there also the exact filebeat version you are using and sharing your full debug log?

Please make to format your config with ticks to make it readable.
