### ISSUE TITLE
Topbeat: Apply regex filter before sending events

### ISSUE THREAD

**Issue by oazabir** [elastic/beats#642]
It would be great if there was a support to add filters in terms of regex before sending events. For ex, I would like to filter out events where cpu = 0, memory = 0. That's majority of the payload. In my case, I get  over 5000 events every minute from topbeat from just 10 servers. However, when I remove the cpu = 0, and memory = 0 events, I end up having < 400 events only. So, 90% saving!

It would be great to have something like this in the topbeat.yml, which is a regex applied over the json:

filter: [/"cpu_p": 0/, /"mem_p": 0/]

**Comment by ruflin** [comment]
Here you can find the general filtering proposal which I think should also cover your case: https://github.com/elastic/beats/issues/451 I will close this issue as duplicate. Please reopen if that is not the case.
