### ISSUE TITLE
Revert #6416 To use the Elasticsearch and X-pack latest snapshot for integration testing

### ISSUE THREAD

**Issue by ph** [elastic/beats#6422]
The Elasticsearch/x-pack 7.0.0-snapshots was making our test fails for multiples days in a row, to move forward and keep our CI greener we have decided to point the master branch to the latest 6.X version.

Once Elasticsearch is stable again we need to revert https://github.com/elastic/beats/pull/6416

**Comment by jsoriano** [comment]
#6944 merged, closing this
