### ISSUE TITLE
Add tenant information to vsphere module Metricbeat

### ISSUE THREAD

**Issue by PauliniMrtns** [elastic/beats#6445]
Dear all,

The vSphere module is just awesome in my opinion, still I think it lacks some features. 
It would be great if it would pull also some tenant information/permissions for each VM so it would be possible to identify which user/customer it belongs. 

Do you think this can be done?

Thank you!
PM

**Comment by ruflin** [comment]
@PauliniMrtns If the information is available through the library we use it definitively should be possible to add it. I marked it as an enhancement request and contributions are more then welcome ;-)

**Comment by amandahla** [comment]
@PauliniMrtns Please, please, can you upload a picture of where do you see this information in VCenter?
  
I know that this concept exists in vRealize as: "A tenant is an organizational unit in a vRealize Automation deployment. A tenant can represent a business unit in an enterprise or a company that subscribes to cloud services from a service provider."
