### ISSUE TITLE
`filebeat modules list` is empty from inside filebeat modules directory

### ISSUE THREAD

**Issue by dilchenko** [elastic/beats#6454]
### Issue:

`filebeat modules list` looks empty when current working directory == `filebeat.config.modules.path`. In fact, it *only* seems to work when current working directory == `path.config`.

### Example:
```
~# grep -B2 path /etc/filebeat/filebeat.yml | grep -B2 modul
  path: "/var/log/filebeat"
--
  modules:
    enabled: true
    path: "modules.d/*.yml"
~#
```
```
~# filebeat modules list
Enabled:
system

Disabled:
apache2
auditd
icinga
kafka
logstash
mysql
nginx
osquery
postgresql
redis
traefik
~# pwd
/etc/filebeat
~# filebeat modules list
Enabled:
system

Disabled:
apache2
auditd
icinga
kafka
logstash
mysql
nginx
osquery
postgresql
redis
traefik
~# cd modules.d/
~# filebeat modules list
Enabled:

Disabled:
~#
```

### Example 2:
```
~# cd ~    #(whoami is root)
~# filebeat modules list
Enabled:

Disabled:
~# cd /etc/filebeat/
~# filebeat modules list
Enabled:
system

Disabled:
apache2
auditd
icinga
kafka
logstash
mysql
nginx
osquery
postgresql
redis
traefik
~#
```

### Effect
Aside from head-scratching and trying to figure out where did all the modules suddenly disappear, this is (to best of my knowledge) harmless.

**Comment by dilchenko** [comment]
Updated the report.

**Comment by exekias** [comment]
Hi @dilchenko,

Thanks for the feedback, I'm guessing here, did you change the default config file? By default we write:
```
filebeat.config.modules:
   path: ${path.config}/modules.d/*.yml
```
That ensures paths are not relative and work in any case

**Comment by dilchenko** [comment]
Yes, I believe the modules part of our config file has been taken from the Filebeat docs. We have since removed the `path` settings as I settled on adding modules configs into the `filebeat.yml` inline, which does not seem to play nicely with `modules.path`.

However, I would argue that asking a used to prepend a config path to the modules path in order for the `list` action to work, or simply not showing any modules if the modules path is not prepended, is a bad experience, at best (I'd argue it's a bug in the CLI). Desired behavior would be:
* CLI spits out the absolute, resolved, path that it looks for modules in
* CLI figures out if the path is relative, and if it is - prepends `path.config`
* If the path is absolute, an error or a notice is printed stating there are no modules found in the dir

**Comment by urso** [comment]
Filebeat needs to find filebeat.yml when you call `filebeat modules list`. By default filebeat looks for the default config file in the current working directory, unless one uses `-c`. Plus `$path.config` is by default the current working directory.

How is filebeat installed? When installing linux via package manager a wrapper script that sets `-c` and `-path.config` is used.

**Comment by dilchenko** [comment]
At the time, this was on CentOS 7, installed via RPMs IIRC.
