### ISSUE TITLE
Traefik module: frontend_name and backend_url fields are classified as String only.

### ISSUE THREAD

**Issue by darkl0rd** [elastic/beats#6467]
In the Traefik module, the 'traefik.access.frontend_name' and the 'traefik.access.backend_url' are currently classified as 'String' fields. This means, that in Kibana one can only search on these fields, but not visualize them.

We should change these to either Keywords, or make it a multikey field to support both use-cases.

**Comment by darkl0rd** [comment]
Issue created as per request here: https://discuss.elastic.co/t/backend-and-frontend-fields-cannot-be-used-in-visualizations/120729

**Comment by iwex** [comment]
any updates?

**Comment by sayden** [comment]
We are currently working on this module right now so we will consider this issue too. You can follow the PR here https://github.com/elastic/beats/pull/8768

**Comment by sayden** [comment]
Fixed in https://github.com/elastic/beats/pull/9005
