### ISSUE TITLE
Support arrays in in http/json metricset

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#6472]
Currently the http/json metricset in Metricbeat only can query information from http endpoints which expose map[string]interface{}. For endpoints which expose and array on the root level the json metricset does not work.

It's a common problem to have such endpoints. Either the http/json metricset should support such endpoints or a new http/json_list metricset should be added.

If a list is retrieved from an endpoint, each entry should be sent as an event from the metricset.

We discussed previously to autodetect if it's an array or not. To get started I prefer to have either a separate metricset or a config option like `json.list: true`. Having a config option has the advantage that auto detection could be added.

**Comment by ruflin** [comment]
For reference, here is the initial issue: https://github.com/elastic/beats/issues/6027

**Comment by jaipradeesh** [comment]
I was thinking to do the following way ..

```go
	switch body := jsonBody.(type) {
	case []map[string]interface{}:
            for _, obj := range {
                // Prepare `event` and return
            }
	case map[string]interface{}:
		// Prepare `event` and return
	default:
		// Log error
	}
```
.. but to match the `EventFetcher` (or) `EventsFetcher` interface, it would be better to go with `json_list` metricset.

```go
// EventFetcher is a MetricSet that returns a single event when collecting data.
// Use ReportingMetricSet for new MetricSet implementations.
type EventFetcher interface {
	MetricSet
	Fetch() (common.MapStr, error)
}

// EventsFetcher is a MetricSet that returns a multiple events when collecting
// data. Use ReportingMetricSet for new MetricSet implementations.
type EventsFetcher interface {
	MetricSet
	Fetch() ([]common.MapStr, error)
}
```

**Comment by ruflin** [comment]
I'm more going in the direction of not adding a metricset for this an always use the second interface even if there is just one event. If it's just a single event, it has to be convered to []common.MapStr

The implementation you suggest above looks a lot like auto detection. I would prefer not to do that and use a config option instead. So if someone configures array but a non array json object is returned, an error is logged. We can still later add a config that enables auto detection.

**Comment by christiangalsterer** [comment]
As commented in #6027 I can look into this in the next days.
W.r.t. to the implementation I would change to EventsFetcher interface but have a preference for auto-detection of arrays as this is more user-friendly and requires less configuration, but we can also add it later if this is currently the preferred way.

**Comment by christiangalsterer** [comment]
Just saw that there is #6480 already on the way.. so will have a look into that one.

**Comment by ruflin** [comment]
@christiangalsterer Yep, work already started and I see you already commented 👍 I always prefer to start with no magic and add it later if needed.

**Comment by jaipradeesh** [comment]
@ruflin This can be closed.
