### ISSUE TITLE
Support for munin module in Metricbeat

### ISSUE THREAD

**Issue by medcl** [elastic/beats#6473]
Munin: http://munin-monitoring.org/

> Munin is a networked resource monitoring tool that can help analyze resource trends and "what just happened to kill our performance?" problems. It is designed to be very plug and play. A default installation provides a lot of graphs with almost no work.

Munin is a widely used monitoring solution, and support a lot of platforms, such as OpenWRT, Solaris/SmartOS(which beats is not able to reach, for now, limited by Golang's implementation),

Also with a lot of metric collect plugins: 

- https://github.com/munin-monitoring/munin/tree/master/plugins
- https://github.com/munin-monitoring/contrib/tree/master/plugins

Munin can be deployed as Munin-node in the edge machine, listen on tcp port 9494, 
and a Munin server pulling these metrics via that agent's ip and port and generate reports, seems works like that, please correct me if I am wrong.

But Munin metrics analysis layer is kindly of out-dated, it uses a cron style to generate static html reports, neat but not enough, some modern analysis features are not there.

If we can leverage Munin-node to collect metrics, as they are pretty mature, and then use Metricbeat to collect these metrics and send to elasticsearch, now the world will rocks. 

@elastic/beats Any thoughts?

**Comment by ruflin** [comment]
I like the idea. I would imagine it would work pretty similar to our http or prometheus module. In the best case metricbeat would be installed along the munin node agent but for not supported system it could be also remote.

**Comment by jsoriano** [comment]
@medcl we have merged #6517 with a new experimental module for munin, this should be enough by now to collect metrics from a munin node agent.

I was wondering if we can also setup something for visualization.

Munin nodes also provide "[config](http://guide.munin-monitoring.org/en/latest/master/network-protocol.html#config)" about how each metric they expose should be represented, this info is used by munin masters to periodically generate the static reports. We could maybe reuse this config to generate kibana dashboards but I think it doesn't fit so well with our current setup workflow: munin metrics config is though to be retrieved during runtime, and `metricbeat setup` is intended to be run as a previous step. I guess that the ideal approach (from munin point of view) would be to have the ability to setup kibana dashboards dynamically during runtime.

Other options would be to have kibana dashboards for well-known munin plugins, or to have an only dashboard that is generated depending on the information in the index or the events (maybe vega can help on that?)

@mattapperson @ruflin thoughts about this?

**Comment by tsg** [comment]
+1 for dashboards for the most popular munin plugins, or for what we don't support currently natively with Metricbeat.

**Comment by medcl** [comment]
@jsoriano Awesome! that's so quickly!

**Comment by ruflin** [comment]
Closing this as we munin is in master.
