### ISSUE TITLE
Documentation - Mention empty lines ignored

### ISSUE THREAD

**Issue by dmontemayors** [elastic/beats#6476]
Opening ticket per discussion: https://discuss.elastic.co/t/filebeat-not-sending-empty-lines/118060/5

Documentation isn't clear that empty lines are ignored by default.  Configuration options 'hint' that all lines are exported, but this is not the case since empty lines are not.  Can you update the documentation to reflect this?  Thank you.

1. https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#exclude-lines

A list of regular expressions to match the lines that you want Filebeat to exclude. Filebeat drops any lines that match a regular expression in the list. **By default, no lines are dropped.** <- Correction needed

2. https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#include-lines

A list of regular expressions to match the lines that you want Filebeat to include. Filebeat exports only the lines that match a regular expression in the list. **By default, all lines are exported.** <- Correction needed.

**Comment by dedemorton** [comment]
Closed in https://github.com/elastic/beats/pull/6654
