### ISSUE TITLE
Filebeat: Test config not detecting incorrect scan_frequency setting

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#6482]
```
#=========================== Filebeat prospectors =============================
# Frequency for scanning directory logs
# Might affect on CPU load
scan_frequency: 30s


filebeat.prospectors:

# Each - is a prospector. Most options can be set at the prospector level, so
# you can use different prospectors for various configurations.
# Below are the prospector specific configurations.

- type: log

  # Change to true to enable this prospector configuration.
  enabled: true
```

6.2.1

Have a config that has scan_frequency incorrectly defined at the root level (instead of under a prospector).  Test config returns OK.

There is also not an indication in the log file that the setting is invalid and will be ignored.  It will be nice for test config to detect it (and indicate that the setting does not apply at the root level, and only at the prospector level) and fail the run until the setting is set properly, etc..

**Comment by ruflin** [comment]
This is not an issue related to scan_frequency but in general how yaml configs work on the beats side. At the moment we cannot detect if there are additional configs as there we don't have global knowledge of which config options are used. AFAIK @urso is currently thinking about some ideas on how we could solve this. I thought we had a more generic place to track this but couldn't fin the issue.

**Comment by ewgRa** [comment]
Actually there is kind of obvious idea just for config validation convert yaml files to json and then just use power of json schema validation.

But I don't get problem with "cannot detect ... additional config". Is it biggest problem? Can it be solved by something like "find . -name *.yml" ?

About generic place, maybe it make sense to create generic issue, and collect there cases and close other issues as duplication. Similar to https://github.com/elastic/beats/issues/1869, that probably was generic issue for previous iteration.

**Comment by urso** [comment]
I'm closing this in favor of the more generic #4416 (Configuration validation) issue.
