### ISSUE TITLE
filebeat Apache module config changes to add response time. 

### ISSUE THREAD

**Issue by ap924g** [elastic/beats#6486]
Hi ,
We are planning to use apache file beat module to export IBM Http server access logs . We are able to view the data in kibana dashboard but the response time value is not showing.  Below is a sample of our access log.

20.20.X.X - - [23/Feb/2018:12:48:48 -0500] "GET /v1files/?v=9052&op=tile&info=true&pages=1, HTTP/1.1" 200 **459 11570 +**

**Comment by ap924g** [comment]
I have updated the grok statements in the ingest pipeline and getting the results as expected. Closing this issue.

**Comment by ruflin** [comment]
@ap924g Would you mind opening a PR with your changes so it's also available to others?

**Comment by ibouchakour** [comment]
@ap924g can you tell you how did you fix the problem ?

**Comment by KarelJakubec** [comment]
@ap924g I am trying to solve the same problem, would you be able to paste here a code snippet that works for you?

**Comment by ap924g** [comment]
Hi All,
Apologies for not responding to this thread . I updated the pipeline with the below content and it worked for me . I just added another variable as "%{DATA:apache2.access.dummy}" at the end of the pattern to get this working . This variable will come as blank when you view in kibana but you will get the other fields as expected .


"filebeat-6.2.1-apache2-access-default": {
    "description": "Pipeline for parsing IBM Http server access logs. Requires the geoip and user_agent plugins.",
    "processors": [
      {
        "grok": {
          "field": "message",
          "patterns": [
            """%{IPORHOST:apache2.access.remote_ip} - %{DATA:apache2.access.user_name} \[%{HTTPDATE:apache2.access.time}\] "%{WORD:apache2.access.method} %{DATA:apache2.access.url} HTTP/%{NUMBER:apache2.access.http_version}" %{NUMBER:apache2.access.response_code} (?:%{NUMBER:apache2.access.body_sent.bytes}|-) (?:%{NUMBER:apache2.access.response_time}|-) %{DATA:apache2.access.connection_status} %{DATA:apache2.access.dummy}?""",
            """%{IPORHOST:apache2.access.remote_ip} - %{DATA:apache2.access.user_name} \[%{HTTPDATE:apache2.access.time}\] "-" %{NUMBER:apache2.access.response_code} -"""
          ],
          "ignore_missing": true
        }
      },
      {
        "remove": {
          "field": "message"
        }
      },
      {
        "rename": {
          "target_field": "read_timestamp",
          "field": "@timestamp"
        }
      },
      {
        "date": {
          "field": "apache2.access.time",
          "target_field": "@timestamp",
          "formats": [
            "dd/MMM/YYYY:H:m:s Z"
          ]
        }
      },
      {
        "remove": {
          "field": "apache2.access.time"
        }
      },
      {
        "user_agent": {
          "target_field": "apache2.access.user_agent",
          "ignore_failure": true,
          "field": "apache2.access.agent"
        }
      },
      {
        "remove": {
          "field": "apache2.access.agent",
          "ignore_failure": true
        }
      },
      {
        "geoip": {
          "field": "apache2.access.remote_ip",
          "target_field": "apache2.access.geoip"
        }
      }
    ],
    "on_failure": [
      {
        "set": {
          "field": "error.message",
          "value": "{{ _ingest.on_failure_message }}"
        }
      }
    ]
  }

**Comment by ruflin** [comment]
@ap924g Not sure we got this in TBH. Any chance you could open a PR?

**Comment by jvkassi** [comment]
Has a PR already been created ?

**Comment by ibouchakour** [comment]
Hi, it been a while but if i remember, i added in filebeat.template.json 
"response_time": {
                  "type": "long"
                },

under the response_code in the apache section,

**Comment by jvkassi** [comment]
hmm i'm talking about a PR to add a new field "response_time" here filebeat/module/apache/access/ingest/pipeline.yml.
Is it the right way to do it ? @ruflin

**Comment by ruflin** [comment]
I haven't worked on the apache part in a while. @exekias might be able to help here?
