### ISSUE TITLE
Clarify server metricset of http module

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#6494]
Documentation around http module's server metricset is quite light today (https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-http-server.html).  It will be helpful to provide some details on things like 1) intended use case for this metricset, 2) the module actually launching a http server, 3) can the http server launched be configured to have some level of protection?

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
