### ISSUE TITLE
[Filebeat] Include Offset when logging json.SyntaxError

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#6515]
When debugging JSON decoding issues in Filebeat it would be helpful to include the `Offset` value contained in the [`json.SyntaxError`](https://golang.org/pkg/encoding/json/#SyntaxError).

```
2018-02-22T22:41:14.912Z        ERROR   reader/json.go:32       Error decoding JSON: invalid character 'x' in string escape code
```

The user would benefit from having both the filename and offset in the message. Then they can use `head -c [offset] [filename]` to examine the line.

**Comment by crazyvikas23** [comment]
@andrewkroh We can get `offset` field from [`json.SyntaxError`](https://golang.org/pkg/encoding/json/#SyntaxError) struct but how do we get the filename we are currently processing.

**Comment by andrewkroh** [comment]
Questions about Filebeat internals are probably test answered by @ruflin or @ph.

One possible solution is to not do logging from `json.go`, and instead pass the error details back to the caller and let it do the logging. The caller should have more contextual information that it can add to the log message.

**Comment by ruflin** [comment]
+1 on returning the error. The json reader does not have the above knowledge about the source and offset as the reader are pretty generic. I prefer not to introduce global knowledge here.
