### ISSUE TITLE
Add a separate topic to describe how events are handled when max_retries is exceeded

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#652]
See #608 for background information.

I've refined the description of max_retries in outputconfig.asciidoc to explain that some beats (like Filebeat) ignore max_retries. However, because the description is shared across the Beats, I don't want to go into too much detail about specific Beat functionality wrt max_retries because it would make the shared description potentially confusing. 

Since there have been at least a couple of customers confused by this setting and how it affects the value of other options, such as backoff, I think it might be worth adding a separate topic that describes how the max_retries option affects publishing for each Beat and how the setting relates to other configuration options (such as backoff, max_backoff, and backoff_factor)--especially for any Beats where these settings affect performance or cause events to be dropped unexpectedly.

Of course, it only makes sense to add a separate topic if we think it's likely that customers will want to tweak these settings (or if they are likely to be confused by the settings).

In general, my goal is to provide more guidance to users about setting related options. Right now, we provide reference information for each configuration option, but we don't provide a lot of guidance about which options should be tweaked and why. The sheer number of config options must be a bit overwhelming for customers who are trying to figure out what to configure, especially when some settings affect others.  

WDYT?

**Comment by ruflin** [comment]
I think in general there are quite a few options which need a separate page to discuss different combination of options. Some are libbeat specific, others are specific to a beat. One example here is multiline from filebeat which should also be discussed in more details with its sub config options. It would be great if we have a general approach to organise and linke these pages. @dedemorton +1 on this :-)

**Comment by dedemorton** [comment]
I agree. Once we've identified the list of topics, we'll organize them logically by task.

**Comment by brandonmensing** [comment]
Relevant threads:
https://discuss.elastic.co/t/reliability-of-filebeat/47627
https://discuss.elastic.co/t/recovery-mechanism-in-filebeat/47539

Over time I expect us to see more and more folks asking for descriptions of behaviors and edge cases. This will grow into our larger resiliency story (involving both ES and LS). 

For the goals here I would encourage us to offer documentation toward a use case in addition to specific configuration topics. Maybe there are two most-common circumstances that people typically are trying to optimize for (e.g. "log fast, drop things if necessary" vs "never miss a log if you can help it"). Showing these options together will help people make the right choices.

**Comment by dedemorton** [comment]
Assigning a priority to this because I keep seeing questions related to retry behavior. 

In addition to talking about max_retries, we need to to describe the general behavior of each beat wrt  handling network issues. 

This question comes up a lot: 

Q: how does beats handle network issues (eg an outage for 15min)?
and are they all the same? i'd imagine filebeat can resume more easily than packetbeat?

A: filebeat and winlogbeat to “at least once” delivery, so they will patiently wait the 15m and not further progress with reading files topbeat and packetbeat do “at most once”, so they will drop after their output buffers get filled these are basically the two modes in libbeat, sync and async

**Comment by dedemorton** [comment]
@elastic/beats  This issue is a bit old and unfortunately keeps falling to the bottom of my to-do list. There have been a lot of changes to Beats since I created this issue, and I'm wondering if there is still a need for this content. With Filebeat at least, we've created a topic called "[How Filebeat works](https://www.elastic.co/guide/en/beats/filebeat/current/how-filebeat-works.html)" that talks about at-last-once delivery. WDYT?

**Comment by brandonmensing** [comment]
I like the how-it-works topic and over time I'd love to see similar topics for the other Beats as well as a little cheatsheet/table that shows you the delivery semantics for each Beat in one place. 

(I'm ok closing out this one as written)

**Comment by dedemorton** [comment]
Closing as recommended by Brandon.
