### ISSUE TITLE
[Metricbeat] Don't require instance_name when there's a single perfmon counter instance

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#6528]
- Beat: Metricbeat
- Module: windows
- Metricset: perfmon
- Version: 6.2.2
- Operating System: Windows 
- Steps to Reproduce:
  - Monitor a counter that does not have multiple instances. For example, `query: '\UDPv4\Datagrams Sent/sec'`.
  - Don't set the `instance_name` configuration option.
  - Start Metricbeat and you will get the error of: `Exiting: 1 error: 1 error: initialization failed: query doesn't contain an instance name. In this case you have to define 'instance_name'`

If a counter does not have multiple instances then the `instance_label` and `instance_name` options don't need to be used or required. The general structure for a counter path is: `\\PerfObject( ParentInstance/ObjectInstance#InstanceIndex )\\Counter`. And it seems that the instance section is optional.

So my proposal is to not require `instance_name` when the counter path doesn't include any "instance" information. This will likely lead to wanting to be able to group related counter data into a single event, like all counters from the `UDPv4` perf object into a single event.

**Comment by crossan007** [comment]
I think I'm seeing this issue with the following as well:

```
    - instance_label: memory
      measurement_label: memory.committed.pct
      query: "\\Memory\\% Committed Bytes In Use"
```

**Comment by crossan007** [comment]
Update - I was completely off-base in my assessment of my environment exhibiting this issue.   

I *did* have some confusion about the behavior of `instance_name`; however, the issue I was facing stemmed from multiple tweaks to my `perfmon.counters` collection in `windows.yml` *after* having already added perfmon documents to the ES index; thereby causing the index pattern to not fit the incoming perfmon data.  This caused _new_ perfmon data to fail to parse and be inserted to the index.  The symptoms were that the metricbeat.log file showed everything as "fine", but no data was showing up in kibana.   My "ah-ha" moment came from examining my logstash logs.
