### ISSUE TITLE
[Filebeat] set output in prospectors section

### ISSUE THREAD

**Issue by yodog** [elastic/beats#6531]
as per https://discuss.elastic.co/t/two-filebeat-instances/123132 i believe it would be of benefit if we could set the output on a `prospector` basis instead of a global, yml wide, `output.elasticsearch` or `output.logstash`

currently i have two instances of filebeat running, one for each output, that could easily be set like below:

```
filebeat.prospectors:

- type  : log
  output: elasticsearch
  paths :
    - /opt/zimbra/log/mailbox.log

- type  : log
  output: logstash
  paths :
    - /var/log/myapp/*/*.log

```
or

```
filebeat.prospectors:

- type: log
  output.elasticsearch:
    enable: true
    hosts : ["localhost"]
  paths:
    - /opt/zimbra/log/mailbox.log

- type: log
  output.logstash:
    enable: true
    hosts : ["host.domain"]
  paths :
    - /var/log/myapp/*/*.log

```

**Comment by zvanderbilt** [comment]
I would also like to see this feature implemented

**Comment by danky78** [comment]
I would like to see this implemented too

**Comment by muraveynovosibirsk** [comment]
+

**Comment by jaredj** [comment]
:+1:

**Comment by yodog** [comment]
https://github.com/elastic/beats/issues/14445
