### ISSUE TITLE
CPU load on windows servers

### ISSUE THREAD

**Issue by jmreymond** [elastic/beats#6555]
We are running filebeat 5.5.2 on Linux servers (Red Hat 7.2) and Windows servers (Windows Server 2008)

We can notice that it is very, very fast on linux servers. If we avoid path syntax like/logs/*/*/* , we have a work load of 1% max
Unfortunaly, it is a nighmare with Windows 2008 servers with a workload of 25% to 35% for 1200 lines/sec
To be sure, we have copied datas and config file from Windows server to a small linux VM and it works like a charm with 1% of workload
So, what's wrong with Windows servers ? Is it Go langage and I/O broken on Windows servers ?
Thanks for your tips

**Comment by ruflin** [comment]
Could you please open a topic on discuss with this as we try to keep Github for confirmed bugs? https://discuss.elastic.co/c/beats/filebeat

Please share their your full config and the log output from filebeat.
