### ISSUE TITLE
[Metricbeat] RabbitMQ cluster - node metrics reported multiple times (duplicates)

### ISSUE THREAD

**Issue by Constantin07** [elastic/beats#6556]
For a RabbitMQ cluster, metricbeat sends 3 beats for each node instead of just one thus triplicating the number of metrics which is unnecessary.

The issue in details is described [here](https://discuss.elastic.co/t/rabbitmq-cluster-node-metrics-reported-multiple-times/123592)

- Version: 6.2.2
- Operating System: Linux Ubuntu 16.04
- Steps to Reproduce: Install metricbeat on all nodes of RabbitMQ cluster and check the records in Elasticsearch.

**Comment by Constantin07** [comment]
looks like API does support per node stats via  `/api/nodes/name` https://pulse.mozilla.org/api/

**Comment by ruflin** [comment]
Thanks for opening the issue. As quick summary of the issue: With each API request to the `nodes` API each node exposes all stats for the other nodes too. This means there are in the end `n*n` events if n nodes are monitored. By default only the information for the connected node should be returned.
