### ISSUE TITLE
Duration format support discrepancy between Beats and Elasticsearch

### ISSUE THREAD

**Issue by jkakavas** [elastic/beats#6561]
Durations from settings, i.e. [xpack.monitoring.elasticsearch.period](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-monitor.html#_literal_period_literal) are parsed as [Duration](https://godoc.org/time#Duration) and when relayed to Elasticsearch i.e. as parameters in a request to ` /_xpack/monitoring/_bulk`, the value is converted to a string using [Duration.String](https://godoc.org/time#Duration.String)

That means that the Duration's value is formatted in a string like "72h3m35s"

Elasticsearch on the other hand, parses time strings in [the following manner](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/unit/TimeValue.java#L327) and only supports strings that end with `d`, `h`, `m`, `s`, `ms`, `micros`, `nanos`

Steps to reproduce:
- Configure monitoring and set `xpack.monitoring.elasticsearch.period: "60s" in `filebeat.yml`
- Get `org.elasticsearch.ElasticsearchParseException: failed to parse [1m0s]` in the Elasticsearch logs

Reference: https://discuss.elastic.co/t/filebeat-xpack-monitoring-elasticsearch-period/123765

**Comment by urso** [comment]
@ph Is duration parsing supported in Logstash? There might be other durations in beats, which get converted to strings via `(time.Duration).String()`. We will need a default encoding. E.g. for ES I'm thinking to use `nanos`, so we keep the values original granularity.

**Comment by andrewkroh** [comment]
+1 for ensuring these are converted to nanoseconds.

fyi: The structured logger [is configured](https://github.com/elastic/beats/blob/794f430f25c302f762ca918bee9c37e1abb644bf/libbeat/logp/encoding.go#L17) to use nanos for durations too.

**Comment by ph** [comment]
@urso Yes theses duration are parsed in LS, we used the same logic as ES.

+1 to have a custom type that can correctly cast the duration.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
