### ISSUE TITLE
Configuration handling

### ISSUE THREAD

**Issue by urso** [elastic/beats#657]
I think it makes sense to parse configs into an intermediate representation (independent of file format or source), which can be used populate the structs.

Main advantage will be support for per module decoupled configuration definitions and handling. E.g. for plugin-like modules we've got in packetbeat and metricsbeat.

    type Config {
        ...
    }
    
    var (
        ErrMissing = errors.New("field name missing")
        ErrTypeMismatch = errors.New("...")
    )
    
    func NewConfigYAML(in io.Reader) (*Config, error) { ... }
    func NewConfigYAMLFile(path string) (*Config, error) { ... }
    
    func (c *Config) GetFields() []string { ... }
    func (c *Config) HasField(name string) (bool) { ... }
    
    // ******************************************************************************
    // Low level getters and setters (do we actually need this?)
    // ******************************************************************************
    
    // number of elements for this field. If config value is a list, returns number
    // of elements in list
    func (c *Config) CountField(name string) (int, error) { ... }
    
    // Config getters. If config value is actually a list, idx can be used to access
    // values at said index
    func (c *Config) Bool(name string, idx int) (bool, error) { ... }
    func (c *Config) Str(name string, idx int) (string, error) { ... }
    func (c *Config) Int(name string, idx int) (int, error) { ... }
    func (c *Confog) Child(name string, idx int) (*Config, error) { ... }
    
    func (c *Config) SetBool(name string, idx int, value bool) { ... }
    func (c *Config) SetStr(name string, idx int, value string) { ... }
    func (c *Config) SetInt(name string, idx int, value int) { ... }
    func (c *Config) SetChild(name string, idx int, value int) { ... }
    
    // ******************************************************************************
    // High level interface
    // ******************************************************************************
    
    type reifyOptions func(opts options) options
    
    // check if config has options not known to type to be filled
    func CheckUnknown(opts options) options
    
    // all fields given in input type must be present in config file
    func CheckRequired(opts options) options
    
    // (optional)
    // func (c *Config) Validate(t reflect.Type, opts ..reifyOptions)
    
    // unpack config into 'to'. Default values will already be set in 'to'.
    func (c *Config) Materialize(to interface{}, opts ...reifyOptions)
    
    // add and overwrite fields in config by input (e.g. set defaults)
    func (c *Config) Incorporate(input interface{})

Having an API like this, we can easily re-interpret a configuration:

    config, _ := NewConfigYAMLFile("config.yml")

    var genericConfig struct {
        Period int `config:"period"`
    }
    err := config.Materialize(&genericConfig, CheckRequired)

    ...

    var myModuleConfig struct {
        Hostnames []string `config:"hosts"`
        Port int `config:"port"`
    } {
        Port: 12345, // set some defaults
    }
    err := config.Materialize(&myModuleConfig)
    ...

The struct-tags to be supported:

    -  : ignore field in config
    omitempty: ignore if not present in config
    inline: include fields from inner struct in outer struct

**Comment by urso** [comment]
This makes handling subsection easier, as these will be interpreted only optionally and if required.

**Comment by andrewkroh** [comment]
:+1: I think this is an important enhancement because it will enable us to have much better configuration validation. So many of the problems we see are with invalid configuration and simply having the ability to detect unknown configuration options will be a big help to users.

**Comment by tsg** [comment]
+1 to this. I think hashicorp handles this similarly by using [mapstructure](https://github.com/mitchellh/mapstructure). I.e. use goyaml to parse into an `map[string]interface{}` then use `mapstructure` to materialize into structures as needed.

**Comment by ruflin** [comment]
Part of the solution was provided with the implementation of https://github.com/urso/ucfg
