### ISSUE TITLE
Example visualizations not working, grouping by .name instead of .name.keyword

### ISSUE THREAD

**Issue by kshade** [elastic/beats#6580]
- Version: 6.2
- Operating System: Devuan Jessie
- Steps to Reproduce:

1. Install ELK stack + beats via Debian packages
2. Load the example dashboards from Metricbeat (and others)
3. Try viewing one that groups by name, for example "Interfaces by Incoming traffic [Metricbeat System]"
4. No data is shown/the gauges show 0
5. Add .keyword to the name field to make it work

Forum discussion: https://discuss.elastic.co/t/various-metricbeat-example-visualizations-dont-work-ootb-missing-keyword-in-group-by-field/124101

**Comment by kaiyan-sheng** [comment]
Tested with 6.2.2 ES, Kibana and Metricbeat on Mac OS, the dashboard works fine with group by `system.network.name`. Also I tried to add `.keyword` after `system.network.name` and because it's a drop down list, it won't let me. I guess this is a problem specifically on Debian packages?!

**Comment by exekias** [comment]
Hi @kshade, did you create the index pattern in kibana by yourself or did it by running `metricbeat setup`? I think I saw a similar behavior when the index pattern wasn't set correctly

**Comment by kshade** [comment]
Sorry for the delay, but i have recreated the problem with the current (7.0) Debian packages. The indices were created by running `metricbeat setup -e -E output.logstash.enabled=false -E output.elasticsearch.hosts=['localhost:9200'] ...` , as per the documentation.

**Comment by gittygoo** [comment]
I am getting the exact same problems with version 7.2, also set it up according to the manuals with metricbeat setup
