### ISSUE TITLE
[Winlogbeat] Compare performance of event rendering without using XML

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#6585]
We should so a comparison test between the current implementation that receives events as XML from Windows versus a prototype implementation that receives events in a binary format. The goal is to see what the performance difference is. We can use our [benchmark](https://github.com/elastic/beats/blob/e3f055f865fe9c17e2baca28ed5044682364f050/winlogbeat/eventlog/bench_test.go) tests for perform the measurements ([here's](https://github.com/elastic/beats/pull/6150#discussion_r163857460) this last run we did of these tests).

Additionally we should check if the Windows API is thread-safe such that multiple threads can be reading batches of events concurrently.

#### Details

When Winlogbeat calls [EvtRender](https://msdn.microsoft.com/en-us/library/windows/desktop/aa385471(v=vs.85).aspx) it passes the [EvtRenderEventXml](https://msdn.microsoft.com/en-us/library/windows/desktop/aa385563(v=vs.85).aspx) flag. In this test we want to utilize the `EvtRenderEventValues` flag. Then Winlogbeat will receive a buffer containing an array of [EVT_VARIANT](https://msdn.microsoft.com/en-us/library/windows/desktop/aa385611(v=vs.85).aspx) objects that it needs to extract the event parameters from.

**Comment by JPvRiel** [comment]
> Additionally we should check if the Windows API is thread-safe such that multiple threads can be reading batches of events concurrently.

This post looks helpful/relevant: https://stackoverflow.com/a/53439276/5472444

**Comment by andrewkroh** [comment]
Another thing I'd like to test/compare is using the ETW APIs to read from event logs (assuming that's possible).
