### ISSUE TITLE
RFE - Add the ability to monitor the status of Linux Services

### ISSUE THREAD

**Issue by kresss** [elastic/beats#6595]
It would be nice to have the ability to monitor system services. The Windows module gives the capability of pulling the status of services. The system module provides the capability of monitoring processes. These are both nice, but I feel like there is a gap for Linux services.

User Story: When running a RHEL 7 systemd services they may or may not have processes associated with them. A given service may have multiple processes associated with it. Monitoring the state of these services is important to the overall health of the systems. It is also cumbersome to monitor for process that are not running using the system monitor. Services need to be monitored at the service level and not the process level.

Maybe it would be possible to bring the Windows service monitoring functionality under the system module and implement the new Linux service monitoring with it. This would keep like data together.

Thank you for your consideration.

**Comment by dcode** [comment]
This is really critical for proper infrastructure monitoring. If you want to replace something like Zappix or Nagios, you need the capabilities that metricbeat already gives, plus basic service monitoring. systemd is really the best place to get this in the Linux space.

This information is exposed in [coreos/go-systemd](https://github.com/coreos/go-systemd) using the dbus module. Should be able to subscribe to start/stop/failure events, as well as poll every _n_ seconds. This would allow us to chart service uptime using a Kibana dashbaord and also provide an immediate notification using a Logstash webhook or Kibana Alert.

Without this feature I had to run metricbeat and Zappix on my servers, which involved a fair amount of feature overlap.
