### ISSUE TITLE
Metricbeat vsphere module: Add fields based on existing fields

### ISSUE THREAD

**Issue by PauliniMrtns** [elastic/beats#6617]
Dear all,

I'm currently pulling information from VMWare vCenter using the vSphere Module in Metricbeats. I'm trying to find a way to enrich the information collected from the module, byt I'm having some trouble.
Consider the following example, I collect info from a certain Virtal Machine:
```
{
          "host" => "elastictest.localdomain",
        "tenant" => "[vsphere][virtualmachine][name]",
    "@timestamp" => 2018-03-21T12:37:24.046Z,
       "vsphere" => {
        "virtualmachine" => {
                   "cpu" => {
                "used" => {
                    "mhz" => 0
                }
            },
                  **"name" => "PauliniEnterprise_VMXPTOXXXX",**
            "datacenter" => "LAB",
                "memory" => {
                 "used" => {
                     "host" => {
                        "bytes" => 0
                    },
                    "guest" => {
                        "bytes" => 0
                    }
                },
                "total" => {
                    "guest" => {
                        "bytes" => 4294967296
                    }
                },
                 "free" => {
                    "guest" => {
                        "bytes" => 4294967296
                    }
                }
            }
        }
    },
          "beat" => {
            "name" => "elastictest.localdomain",
         "version" => "6.1.3",
        "hostname" => "elastictest.localdomain"
    },
      "@version" => "1",
     "metricset" => {
          "host" => "https://10.150.168.30/sdk",
          "name" => "virtualmachine",
        "module" => "vsphere",
           "rtt" => 237852
    }
}
```
I want to be able to create a new field based on the virtual machine name PauliniEnterprise_VMXPTOXXXX and create a field named "tenant" or "client" that is just PauliniEnterprise because my procedure on the onboarding of new clients considers that there is a template on the naming of new VMs, where the string until the first underscore (_) is the client name or ID.

I would like to keep this simple and add fields to metricbeat but if necessary I can run this information in Logstash and go from there (some guidelines please 👍  )  

Can you please give me a little help :) 

Thanks!!
PM

**Comment by amandahla** [comment]
@PauliniMrtns I'm not sure if I get this right but...Wouldn't be easier to create field on the virtual machine callend "tenant" or "client" with the value "PauliniEnterprise"?

Then you can set "get_custom_fields" to true and receive this value on vsphere.virtualmachine.custom_fields

**Comment by andrewkroh** [comment]
> I want to be able to create a new field based on the virtual machine name PauliniEnterprise_VMXPTOXXXX and create a field named "tenant" or "client" that is just PauliniEnterprise

That sounds like a task for Logstash. You could grok the name to create a `tenant` and `instance` field.

**Comment by PauliniMrtns** [comment]
I agree with both of you, the issue here is our VMWare infrastructure is quite large and I don't have the influence to change those custom fields as I should :) 
I like the Logstash approach, I actually tried to do a .conf file to capture this data but I'm having some difficulty because I still couldn't catch vsphere module data with a filter, how do you recommend doing this?

Thanks!
PM

**Comment by andrewkroh** [comment]
Something like

```
filters {
  if [metricset][name] == "virtualmachine" {
    grok {
      // Parse the [vsphere][virtualmachine][name] field.
    }
  }
}
```

**Comment by kaiyan-sheng** [comment]
Seems like logstash is the proper way to solve this here. Closing this issue.
