### ISSUE TITLE
Support TLS configuration in metricbeat mongodb module

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#6619]
Support [TLS configuration](https://docs.mongodb.com/manual/reference/program/mongo/#tls-ssl-options) in metricbeat mongodb module.

It could be supported by adding a `DialServer` to [`DialInfo`](https://godoc.org/gopkg.in/mgo.v2#DialInfo), that sets up connection configuration with TLS options when they need to be used.

**Comment by BoyCook** [comment]
Hi - any idea on if/when this is going to be implemented? This is a blocker for me.

**Comment by twatson83** [comment]
:thumbsup:

**Comment by BoyCook** [comment]
Does this also apply to Packetbeat?

**Comment by jsoriano** [comment]
@BoyCook this only applies to metricbeat

**Comment by BoyCook** [comment]
Do we know what release this will be available in?

**Comment by jsoriano** [comment]
Most likely in 6.4.

**Comment by pdanysz** [comment]
When 6.4.0 will be released ?

**Comment by jsoriano** [comment]
@pdanysz 6.4.0 will be released soon, most likely in a few weeks. It will contain this fix.
