### ISSUE TITLE
[Beats][feature request] Could we add IMAP protocol support?

### ISSUE THREAD

**Issue by kunisen** [elastic/beats#6624]
Would be happy if we can sniff/monitor traffic on these protocols...

  imaps:
    ports: [993]

similar issue:
https://github.com/elastic/beats/issues/388

from @ruflin 's comment, I tried to access the following link, but no results returned.
https://github.com/elastic/beats/issues/388#issuecomment-158296548

So I raised it here again.

**Comment by kunisen** [comment]
any updates here?

**Comment by skmizuho** [comment]
This will be really useful for those teams that need to monitor a mailbox.
