### ISSUE TITLE
 system.filesystem.used.pct calculation in metricbeat

### ISSUE THREAD

**Issue by krisko** [elastic/beats#6628]
For confirmed bugs, please report:
- Version: No specific version
- Operating System: RHEL 6
- Steps to Reproduce: start metricbeat and observe reported values

Symptoms:

df utility reports different FS used % than system.filesystem.used.pct in MetricBeat.
MB **system.filesystem.used.pct** is calculated from **system.filesystem.used.bytes**, which does not consider reserved blocks and reports lower % on FS usage.
If this is not desired, we can use maybe system.filesystem.free for this calculation...?

<pre>
$ tune2fs -l /dev/mapper/vg00-lv_data
...
Reserved block count:     52428
Block size:               4096
...

$ bc -l
52028*4096/1024/1024
203.23437 MB is reserved for system (root)

$ df -h /data/
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg00-lv_data
                      3.9G  2.4G  1.3G  66% /data

# this means that df calculates used FS as (Used + Reserved) / Size
# but metricbeat calculates this as Used / Size
# what we can do here is calculate this as (Size - Available) / Size
</pre>

**Comment by jsoriano** [comment]
It should be reporting disk usage like `df` after #6231 @krisko with what metricbeat version are you finding this issue?

**Comment by andrewkroh** [comment]
#6231 hasn't been released yet. In the meantime you can try a snapshot build from https://s3-us-west-2.amazonaws.com/beats-package-snapshots/index.html?prefix=metricbeat/.

**Comment by krisko** [comment]
Yes, the snapshot works.
65.14% 7.0.0-alpha1
61.72% 6.2.3

Thanks!

**Comment by andrewkroh** [comment]
Thanks for confirming. That will get released in 6.3.0.
