### ISSUE TITLE
[Packetbeat] Move gocql dependency to vendor/

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#6635]
There's a Go dependency used by the cassandra plugin that exists outside of the vendor directory. It needs to be moved to the `vendor/` dir. This will ensure that it's tracked in our NOTICE file.

https://github.com/elastic/beats/tree/master/packetbeat/protos/cassandra/internal/gocql

**Comment by andrewkroh** [comment]
Or we can update the NOTICE.txt file to include this dep.

**Comment by urso** [comment]
@andrewkroh I think one of the reasons it is not vendored is: this is not the original. Some symbols that have not been available in the original have been exported, so to make it reusable by the parser.

**Comment by andrewkroh** [comment]
In that case then I think the script for generating the NOTICE should make sure to include the original gocql license even if the source is modified.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
