### ISSUE TITLE
Some files in the IIS and Nginx modules show "prospector" instead of "input"

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#6642]
It looks like the renaming from prospector > input was not made in some of the files for the IIS and Nginx modules (not sure why):

* In the filebeat.reference.yml file, the IIS and Nginx module sections still use prospector instead of input. for example: https://github.com/elastic/beats/blob/master/filebeat/filebeat.reference.yml#L133

* The manifest files for IIS and Nginx still refer to prospectors. For example: https://github.com/elastic/beats/blob/master/filebeat/module/iis/access/manifest.yml#L13

**Comment by dedemorton** [comment]
@ph Can we still fix this for 6.3, or is it too late? I think users are going to be confused if they see a mixture of "input" and "prospector" in our reference config files. I think both will work (right?) but the docs are going to be confusing to anyone who is looking for info about prospector settings.

**Comment by dedemorton** [comment]
hmm...looks like some of the manifest files still refer to prospectors, too.

**Comment by ph** [comment]
I will make a PR tomorrow for that I think we can get that in before the release.

**Comment by ph** [comment]
both will work , but I prefer that we remove any confusion good catch.

**Comment by ph** [comment]
@dedemorton  I also found theses mentions in the kubernetes examples files and created https://github.com/elastic/beats/pull/7080
