### ISSUE TITLE
Example config mismatch for Metricbeat Jolokia module

### ISSUE THREAD

**Issue by agathver** [elastic/beats#6643]
In the sample config at https://github.com/elastic/beats/blob/master/metricbeat/modules.d/jolokia.yml.disabled#L7 we have `jmx.mapping`

While we expect `jmx.mappings` here: https://github.com/elastic/beats/blob/master/metricbeat/module/jolokia/jmx/jmx.go#L49

https://discuss.elastic.co/t/metricbeat-jolokia-configuration/125305

Perhaps we should even add more examples in the sample file

**Comment by jsoriano** [comment]
Thanks for reporting this @agathver, actually this sample configuration file also contains some non-existing fields, would you like to prepare a PR fixing this?

**Comment by agathver** [comment]
@jsoriano Sure,
I have been working in those parts of metricbeats recently. 

Should we add config for some common MBeans like Uptime, Heap memory?

**Comment by jsoriano** [comment]
Hi @adamliuzehui, please use https://discuss.elastic.co/c/beats for general questions about Beats. Thanks!
