### ISSUE TITLE
[Metricbeat] support kubernetes ressourcequotas

### ISSUE THREAD

**Issue by f0** [elastic/beats#6659]
it would be nice if metricbeat would fetch the kubernetes ressourcequotas.
This is very usefull to e.g display quotas per namespace vs. usage per namespace

**Comment by exekias** [comment]
It make sense to include this info, I've been checking `kube-state-metrics` and it doesn't retrieve these, so we would need to get them from the API server

**Comment by f0** [comment]
@exekias   hm kube-state-metrics should include this https://github.com/kubernetes/kube-state-metrics/blob/master/collectors/resourcequota.go

**Comment by exekias** [comment]
That's right! I didn't see it in the docs, good to know, it should make things easier to implement then :+1:

**Comment by jarrocha** [comment]
@exekias @f0 
I have taken a look here:
`https://github.com/elastic/beats/tree/master/metricbeat/module/kubernetes`
and here:
`https://github.com/kubernetes/kube-state-metrics/tree/release-1.3/Documentation`
Does this involve creating a new state_resourcequotas package as in the first link?

**Comment by exekias** [comment]
yes, something similar to any of the `state_*` packages under https://github.com/elastic/beats/tree/master/metricbeat/module/kubernetes

**Comment by jarrocha** [comment]
I'll be working on this one.

**Comment by ruflin** [comment]
@jarrocha Great to hear. Thank you.

**Comment by jarrocha** [comment]
I have started work on this but there's some information that I am missing. Do you know where I can find more documentation to find usage for the different metric methods as it relates to Prometheus:

This is is from:
[https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/state_node/state_node.go#L42](url)
```
"kube_node_info":                            p.InfoMetric(),
"kube_node_status_allocatable_pods":         p.Metric("pod.allocatable.total"),
"kube_node_spec_unschedulable":              p.BooleanMetric("status.unschedulable"),
"kube_node_status_ready":                    p.LabelMetric("status.ready", "condition"),
```
Also, for testing, will something similar to this work on Linux?
[https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/_meta/test/README.md](url)

**Comment by jsoriano** [comment]
> I have started work on this but there's some information that I am missing. Do you know where I can find more documentation to find usage for the different metric methods as it relates to Prometheus:
> 
> This is is from:
> https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/state_node/state_node.go#L42
> 
> ```
> "kube_node_info":                            p.InfoMetric(),
> "kube_node_status_allocatable_pods":         p.Metric("pod.allocatable.total"),
> "kube_node_spec_unschedulable":              p.BooleanMetric("status.unschedulable"),
> "kube_node_status_ready":                    p.LabelMetric("status.ready", "condition"),
> ```
> 

Do you have some specific question about these methods?
Automated godocs can be found [here](https://godoc.org/github.com/elastic/beats/metricbeat/helper/prometheus) (not sure how updated they are). And you can always check the source in  https://github.com/elastic/beats/blob/master/metricbeat/helper/prometheus/metric.go

For examples you can look at the `state_*` metricsets in the kubernetes module.

> Also, for testing, will something similar to this work on Linux?
> https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/_meta/test/README.md

Yes, for Linux you can also use `minikube`, you will need to install [`kube-state-metrics`](https://github.com/kubernetes/kube-state-metrics) service for these metrics.

If you want to use the docker daemon of the minikube VM you can do it with `eval $(minikube docker-env)`. You may need to use it to pull or build images into the VM.
