### ISSUE TITLE
Mix of enabled:false and enabled:true in metricbeat.reference.yml

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#6672]
In the `metricbeat.reference.yml` we have a mix of modules which have `enabled: false` and some which are missing it. We should either have all modules enabled or disabled by default. As we normally go with the default I suggest to have all modules enabled by default, meaning having with each module config a line `enabled: true`.

**Comment by dedemorton** [comment]
@ruflin Can we close this now?

**Comment by ruflin** [comment]
Yes
