### ISSUE TITLE
Clarify use of TCP or UDP for transmission

### ISSUE THREAD

**Issue by markwalkom** [elastic/beats#668]
[Here](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html#_tls_2) we mention;
> Logstash must also be configured to use TCP for Logstash input.

While [here](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html) we don't mention anything.

It'd be worth further clarifying that filebeat uses TCP only to ensure delivery, rather than having it as a footnote in a different document area.

**Comment by tsg** [comment]
691 is merged now.
