### ISSUE TITLE
Jenkins build fails on AmazonLinux

### ISSUE THREAD

**Issue by pillarsdotnet** [elastic/beats#6699]
On (at least) Amazon Linux, the [virtualenv](https://virtualenv.pypa.io/en/stable/) tool configures python with the following `sys.path` directories:

- `''`
- `'${PYTHON_ENV}/local/lib64/python2.7/site-packages'`
- `'${PYTHON_ENV}/local/lib/python2.7/site-packages'`
- `'${PYTHON_ENV}/lib64/python2.7'`
- `'${PYTHON_ENV}/lib/python2.7'`
- `'${PYTHON_ENV}/lib64/python2.7/site-packages'`
- `'${PYTHON_ENV}/lib/python2.7/site-packages'`
- `'${PYTHON_ENV}/lib64/python2.7/lib-dynload'`
- `'${PYTHON_ENV}/local/lib/python2.7/dist-packages'`
- `'${PYTHON_ENV}/local/lib/python2.7/dist-packages'`
- `'${PYTHON_ENV}/lib/python2.7/dist-packages'`
- `'/usr/lib64/python2.7'`
- `'/usr/lib/python2.7'`

However, running `pip install PyYAML` in that same virtualenv will install the `yaml` module in the `${PYTHON_ENV}/lib64/python2.7/dist-packages` directory, which is not on the search path.

I have submitted #6698 to workaround the problem, and a [topic](https://discuss.elastic.co/t/jenkins-build-fails-on-at-least-amazon-linux/126126) on discuss.elastic.co.

**Comment by andrewkroh** [comment]
Closed by #6698.
