### ISSUE TITLE
packetbeat IP/TCP flows support (phase 1)

### ISSUE THREAD

**Issue by urso** [elastic/beats#670]
Collect and report statistics per flow on IP/TCP, UDP, SSL layer only.

Phase 1 is about defining flows in packetbeat + combining required meta data across multiple network layers. Only metrics collected yet will be number of packets and bytes being send.

Flows will be bidirectional for having some denormalized data for use with elasticsearch.

## Collection
- Count packet sizes + collect metadata per flow
- report collected stats every N seconds (configurable)

## Flow

We basically consider a flow to be a number of packets observed in a timeslot sharing some common properties like address and protocol. 

- flow is uniquely identified by meta data
- statistics are collected per flow
- flows can be defined on different layers (Ethernet, IP, TCP/UDP, TLS, Application Layer):
  - each layer will be assigned an unique id
  - unique id per layer must be independent of flow direction

## Flow ID

- One Flow ID is defined per layer in packet (up to TCP/UDP/SSL and optional application layer)
- ID is generated by lexically sorting (on byte sequence) the address pair on the given layer.
    - MAC-ID Layer: min(src mac, dst mac) + max(src mac, dst mac)
    - IP Layer: min(src ip, dst ip) + max(src ip, dst ip)
    - TCP: min(src port, dst port) + max(src port, dst port)
- The concatenation of all IDs up to layer of interest uniquely identifies a bidirectional flow on given layer:
  - concatenation is not precomputed, but must be done via elasticsearch/kibana filters

  - Stateful protocols (e.g. establishing a connection - TCP) will generate a flow sub-id to differentiate multiple different connections (in time).

List of layers flow id will be generated for:

- MAC
- IP4/IP6
- outer IP4/IP6
- TCP
- UDP

## Document structure

    {
        // ethernet layer + vlan meta
        "source_mac": <string>,
        "dest_mac": <string>,
        "vlan": <num>,

        // ip layer meta data
        "outer_source_ip": <string>,
        "outer_dest_ip": <string>,
        "source_ip": <string>,
        "dest_ip": <string>,
        "qos": <num>,
        "ip6_flow_label": <num>,
        "depth": <num>,
        "ip_payload_type": <string>,

        // tcp/udp layer meta data
        “source_port”: <num>,
        “dest_port”: <num>,
        “applayer_type”: <string>, // application layer protocol type

        // flow-id
        “flow_id”: {
            “mac”: <string>,
            “outer_ip”: <string>,
            “ip”: <string>,
            “tcp”: <string>
        },

        // stats ‘->’
	“source_dest_stats”: {
        },
	“dest_source_stats”: {
            ...
        },
    }

**Comment by ruflin** [comment]
Looks good. As you describe in the beginning, only 2 metrics will be collected in the beginning. I would also add them to the json structure for completeness.

**Comment by urso** [comment]
will remove the flow id from document. The flow-id sub-document kinda duplicates other metadata

**Comment by urso** [comment]
update json-document structure:

    {
        "@timestamp": ...
        "type": "flow",
        "beat": { ... },
    
        // MAC address (if known)
        "mac_source": ... ,
        "mac_dest": ... ,
    
        // vlan
        "outter_vlan": ...,
        "vlan": ...,
    
        // ip4
        "outter_ip4_source": ...,
        "outter_ip4_dest": ...,
        "ip4_source": ...,
        "ip4_dest": ...,
    
        // ip6
        "outter_ip6_source": ...,
        "outter_ip6_dest": ...,
        "ip6_source": ...,
        "ip6_dest": ...,
    
        // udp/tcp
        "port_source": ...,
        "port_dest": ...,
        "transp": ...,  // "udp" or "tcp"
        "connection_id": ..., // base64 encoded internal tcp connection id
    
        // source -> dest stats
        "stats_source": {
            "net_bytes_total": ...,
            "net_packets_total": ...
        },
    
        // dest -> source stats (if reverse flow present)
        "stats_dest": {
            "net_bytes_total": ...,
            "net_packets_total": ...
        }
    }

**Comment by monicasarbu** [comment]
@urso, Nice, I like the last version of the json object.

**Comment by andrewkroh** [comment]
Implemented by #756
