### ISSUE TITLE
Response from unknown transaction?

### ISSUE THREAD

**Issue by tpnoonan** [elastic/beats#672]
I'm receiving a message in syslog using the pgsql beat that says:

/usr/bin/packetbeat[pid]: pgsql.go:875: Response from unknown transaction. Ignoring.

I will perform a packet capture and send to the info email i saw in another thread.

**Comment by urso** [comment]
Packetbeat requires request and response for creating transactions. On startup, or if there was some packetloss, then Packetbeat might not see all messages.

This issue has not been updated for some time. We will close it now. If you still have problems feel free to comment, or try to seek help from the [community forums](https://discuss.elastic.co).
