### ISSUE TITLE
make package is Failing on Ubuntu

### ISSUE THREAD

**Issue by marian-craciunescu** [elastic/beats#6729]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version: latest 
- Operating System:  Ubuntu 17.10
- Steps to Reproduce: run  make package

make -C ./vendor/github.com/elastic/beats/dev-tools/packer deps images
make[1]: Entering directory '/home/marian/CODE/GO_PROJECTS/src/github.com/berfinsari/tracebeat/vendor/github.com/elastic/beats/dev-tools/packer'
go get -u github.com/tsg/gotpl
cd /home/marian/CODE/GO_PROJECTS/src/github.com/berfinsari/tracebeat/vendor/github.com/elastic/beats/dev-tools/packer/docker/xgo-image/; ./build.sh
Sending build context to Docker daemon  317.4kB
Step 1/26 : FROM ubuntu:14.04
 ---> a35e70164dfb
Step 2/26 : MAINTAINER Tudor Golubenco <tudor@elastic.co>
 ---> Using cache
 ---> 9bcd9913f2b4
Step 3/26 : ENV PATH   /usr/local/go/bin:$PATH
 ---> Using cache
 ---> f64e09f9b7c3
Step 4/26 : ENV GOPATH /go
 ---> Using cache
 ---> 36026eefa5d2
Step 5/26 : ADD fetch.sh /fetch.sh
 ---> Using cache
 ---> c7a2560410ba
Step 6/26 : ENV FETCH /fetch.sh
 ---> Using cache
 ---> 3e1ce9949654
Step 7/26 : RUN chmod +x $FETCH
 ---> Using cache
 ---> 14792c8515aa
Step 8/26 : RUN   apt-get update &&   apt-get install -y automake autogen build-essential ca-certificates               gcc-arm-linux-gnueabi g++-arm-linux-gnueabi libc6-dev-armel-cross               gcc-multilib  g++-multilib mingw-w64 clang llvm-dev                             libtool libxml2-dev uuid-dev libssl-dev swig pkg-config patch                   make xz-utils cpio wget zip unzip p7zip git mercurial bzr texinfo help2man      binutils-multiarch rsync                                                        --no-install-recommends
 ---> Using cache
 ---> d311aa1f6bee
Step 9/26 : ENV OSX_SDK     MacOSX10.11.sdk
 ---> Using cache
 ---> d787e1396a9a
Step 10/26 : ENV OSX_NDK_X86 /usr/local/osx-ndk-x86
 ---> Using cache
 ---> b4f738238326
Step 11/26 : RUN   OSX_SDK_PATH=https://github.com/phracker/MacOSX-SDKs/releases/download/MacOSX10.11.sdk/MacOSX10.11.sdk.tar.xz &&   $FETCH $OSX_SDK_PATH f3430e3d923644e66c0c13f7a48754e7b6aa2e3f       &&     git clone https://github.com/tpoechtrager/osxcross.git &&   mv `basename $OSX_SDK_PATH` /osxcross/tarballs/        &&     sed -i -e 's|-march=native||g' /osxcross/build_clang.sh /osxcross/wrapper/build.sh &&   UNATTENDED=yes OSX_VERSION_MIN=10.6 /osxcross/build.sh                             &&   mv /osxcross/target $OSX_NDK_X86                                                   &&     rm -rf /osxcross
 ---> Using cache
 ---> 8d1ef5a610f8
Step 12/26 : ADD patch.tar.xz $OSX_NDK_X86/SDK/$OSX_SDK/usr/include/c++
 ---> Using cache
 ---> d454761b31d4
Step 13/26 : ENV PATH $OSX_NDK_X86/bin:$PATH
 ---> Using cache
 ---> 3d6f4df2fad6
Step 14/26 : ADD bootstrap.sh /bootstrap.sh
 ---> Using cache
 ---> 4bb5d4733e62
Step 15/26 : ENV BOOTSTRAP /bootstrap.sh
 ---> Using cache
 ---> 764ad183819a
Step 16/26 : RUN chmod +x $BOOTSTRAP
 ---> Using cache
 ---> b414404636aa
Step 17/26 : ADD bootstrap_pure.sh /bootstrap_pure.sh
 ---> Using cache
 ---> 0067b888091c
Step 18/26 : ENV BOOTSTRAP_PURE /bootstrap_pure.sh
 ---> Using cache
 ---> e40195c380ac
Step 19/26 : RUN chmod +x $BOOTSTRAP_PURE
 ---> Using cache
 ---> 02b0bc767b5f
Step 20/26 : ADD build_deps.sh /build_deps.sh
 ---> Using cache
 ---> 084e870a2b70
Step 21/26 : ENV BUILD_DEPS /build_deps.sh
 ---> Using cache
 ---> c733c6a98672
Step 22/26 : RUN chmod +x $BUILD_DEPS
 ---> Using cache
 ---> 5d7cb17b86db
Step 23/26 : ADD build.sh /build.sh
 ---> Using cache
 ---> 40ad5c48bc0d
Step 24/26 : ENV BUILD /build.sh
 ---> Using cache
 ---> 0465494e5a40
Step 25/26 : RUN chmod +x $BUILD
 ---> Using cache
 ---> a1b74ac62b93
Step 26/26 : ENTRYPOINT ["/build.sh"]
 ---> Using cache
 ---> c22376961da4
Successfully built c22376961da4
Successfully tagged tudorg/xgo-base:latest
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM tudorg/xgo-base
 ---> c22376961da4
Step 2/3 : MAINTAINER Tudor Golubenco <tudor@elastic.co>
 ---> Using cache
 ---> e08c848d4267
Step 3/3 : RUN   export ROOT_DIST="https://storage.googleapis.com/golang/go1.7.6.linux-amd64.tar.gz" &&   export ROOT_DIST_SHA1="6a7014f34048d95ab60247814a1b8b98018810ff" &&     $BOOTSTRAP_PURE
 ---> Using cache
 ---> 77e55168d0ef
Successfully built 77e55168d0ef
Successfully tagged tudorg/xgo-1.7.6:latest
Sending build context to Docker daemon  286.7kB
Step 1/11 : FROM tudorg/xgo-1.7.6
 ---> 77e55168d0ef
Step 2/11 : MAINTAINER Tudor Golubenco <tudor@elastic.co>
 ---> Using cache
 ---> f29ad172f9d3
Step 3/11 : RUN 	dpkg --add-architecture i386 && 	apt-get update && 	apt-get install -y libpcap0.8-dev
 ---> Using cache
 ---> 2e2ffda24ee1
Step 4/11 : RUN 	mkdir -p /libpcap && 	apt-get download libpcap0.8-dev:i386 && 	dpkg -x libpcap0.8-dev_*_i386.deb /libpcap/i386 && 	apt-get download libpcap0.8-dev && 	dpkg -x libpcap0.8-dev_*_amd64.deb /libpcap/amd64 && 	rm libpcap0.8-dev*.deb
 ---> Using cache
 ---> 762da52c863f
Step 5/11 : ENV WPDPACK_URL https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
 ---> Using cache
 ---> 23e8a77f2cd9
Step 6/11 : RUN 	./fetch.sh $WPDPACK_URL f5c80885bd48f07f41833d0f65bf85da1ef1727a && 	unzip `basename $WPDPACK_URL` -d /libpcap/win && 	rm `basename $WPDPACK_URL`
 ---> Using cache
 ---> fb49615b23c1
Step 7/11 : RUN go get github.com/tsg/gotpl
 ---> Using cache
 ---> 27b78810500a
Step 8/11 : ADD gopacket_pcap.patch /gopacket_pcap.patch
 ---> Using cache
 ---> 3edbbf6c7c0a
Step 9/11 : ENV WINPCAP_DLL_SHA1 d2afb08d0379bd96e423857963791e2ba00c9645
 ---> Using cache
 ---> eed84cc28793
Step 10/11 : ADD wpcap.dll /libpcap/win/wpcap.dll
 ---> Using cache
 ---> 489a47ec051e
Step 11/11 : RUN     apt-get install mingw-w64-tools &&     cd /libpcap/win &&     echo "$WINPCAP_DLL_SHA1 wpcap.dll" | sha1sum -c - &&     gendef /libpcap/win/wpcap.dll &&     x86_64-w64-mingw32-dlltool --as-flags=--64 -m i386:x86-64 -k --output-lib /libpcap/win/WpdPack/Lib/x64/libwpcap.a --input-def wpcap.def &&     rm wpcap.def wpcap.dll
 ---> Using cache
 ---> acc396af14be
Successfully built acc396af14be
Successfully tagged tudorg/beats-builder:latest
# copy build.sh script in the xgo-image-deb6 to avoid code duplication
cp /home/marian/CODE/GO_PROJECTS/src/github.com/berfinsari/tracebeat/vendor/github.com/elastic/beats/dev-tools/packer/docker/xgo-image/base/build.sh /home/marian/CODE/GO_PROJECTS/src/github.com/berfinsari/tracebeat/vendor/github.com/elastic/beats/dev-tools/packer/docker/xgo-image-deb6/base/build.sh
cd /home/marian/CODE/GO_PROJECTS/src/github.com/berfinsari/tracebeat/vendor/github.com/elastic/beats/dev-tools/packer/docker/xgo-image-deb6/; ./build.sh
Sending build context to Docker daemon  20.48kB
Step 1/22 : FROM debian:6
 ---> a873733ef581
Step 2/22 : MAINTAINER Tudor Golubenco <tudor@elastic.co>
 ---> Using cache
 ---> ff1c164afd6a
Step 3/22 : ADD sources.list /etc/apt/sources.list
 ---> Using cache
 ---> 33cf91d3475b
Step 4/22 : ENV PATH   /usr/local/go/bin:$PATH
 ---> Using cache
 ---> bf0c6b0ada5d
Step 5/22 : ENV GOPATH /go
 ---> Using cache
 ---> 5e2dc3049663
Step 6/22 : ADD fetch.sh /fetch.sh
 ---> Using cache
 ---> f850ce697377
Step 7/22 : ENV FETCH /fetch.sh
 ---> Using cache
 ---> 06cce35f796a
Step 8/22 : RUN chmod +x $FETCH
 ---> Using cache
 ---> b41bc776e34b
Step 9/22 : RUN   apt-get -o Acquire::Check-Valid-Until=false update &&   apt-get install -y automake autogen build-essential ca-certificates     gcc-multilib     clang llvm-dev  libtool libxml2-dev uuid-dev libssl-dev pkg-config     patch make xz-utils cpio wget unzip git mercurial bzr rsync --no-install-recommends
 ---> Running in 48a548d6a18e
Get:1 http://archive.debian.org squeeze Release.gpg [1655 B]
Get:2 http://archive.debian.org squeeze-lts Release.gpg [819 B]
Get:3 http://archive.debian.org squeeze Release [96.0 kB]
Ign http://archive.debian.org squeeze Release
Get:4 http://archive.debian.org squeeze-lts Release [34.3 kB]
Get:5 http://archive.debian.org squeeze/main amd64 Packages [8370 kB]
Get:6 http://archive.debian.org squeeze/contrib amd64 Packages [61.7 kB]
Get:7 http://archive.debian.org squeeze-lts/main amd64 Packages [390 kB]
Fetched 8955 kB in 19s (469 kB/s)
Reading package lists...
W: GPG error: http://archive.debian.org squeeze Release: The following signatures were invalid: KEYEXPIRED 1520281423 KEYEXPIRED 1501892461
Reading package lists...
Building dependency tree...
Reading state information...
xz-utils is already the newest version.
The following extra packages will be installed:
  autoconf autotools-dev binfmt-support binutils bzip2 cpp cpp-4.4 dpkg-dev
  file g++ g++-4.4 gcc gcc-4.4 gcc-4.4-multilib guile-1.8-libs lib32gcc1
  lib32gomp1 libc-dev-bin libc6-dev libc6-dev-i386 libc6-i386 libcurl3-gnutls
  libdb4.7 libdpkg-perl liberror-perl libexpat1 libffi-dev libffi5 libgcrypt11
  libgdbm3 libglib2.0-0 libgmp3c2 libgnutls26 libgomp1 libgpg-error0
  libgssapi-krb5-2 libidn11 libk5crypto3 libkeyutils1 libkrb5-3
  libkrb5support0 libldap-2.4-2 libltdl7 libmagic1 libmpfr4 libncursesw5
  libopts25 libopts25-dev libpcre3 libpopt0 libsasl2-2 libsqlite3-0
  libssl0.9.8 libstdc++6-4.4-dev libtasn1-3 libtimedate-perl libxml2
  linux-libc-dev llvm llvm-runtime m4 mercurial-common mime-support openssl
  perl perl-modules python python-central python-configobj python-minimal
  python-support python2.6 python2.6-minimal ucf zlib1g-dev
Suggested packages:
  autoconf2.13 autoconf-archive gnu-standards autoconf-doc gettext
  binutils-doc bzip2-doc bzr-gtk bzr-svn python-pycurl xdg-utils
  python-kerberos bzr-doc cpp-doc gcc-4.4-locales debian-keyring g++-multilib
  g++-4.4-multilib gcc-4.4-doc libstdc++6-4.4-dbg manpages-dev automake1.9
  flex bison gdb gcc-doc libmudflap0-4.4-dev libgcc1-dbg libgomp1-dbg
  libmudflap0-dbg libcloog-ppl0 libppl-c2 libppl7 lib32mudflap0 git-doc
  git-arch git-cvs git-svn git-email git-daemon-run git-gui gitk gitweb
  glibc-doc rng-tools gnutls-bin krb5-doc krb5-user libstdc++6-4.4-doc
  libtool-doc automaken gfortran fortran95-compiler gcj llvm-doc make-doc qct
  wish vim emacs kdiff3 tkdiff meld xxdiff python-mysqldb python-pygments
  python-openssl ed diffutils-doc perl-doc libterm-readline-gnu-perl
  libterm-readline-perl-perl python-doc python-tk python-profiler
  python2.6-doc python2.6-profiler openssh-client openssh-server zip
Recommended packages:
  bzrtools python-paramiko llvm-2.7-dev fakeroot libalgorithm-merge-perl less
  ssh-client libglib2.0-data shared-mime-info libgpm2 libsasl2-modules
  libltdl-dev xml-core
The following NEW packages will be installed:
  autoconf autogen automake autotools-dev binfmt-support binutils
  build-essential bzip2 bzr ca-certificates clang cpio cpp cpp-4.4 dpkg-dev
  file g++ g++-4.4 gcc gcc-4.4 gcc-4.4-multilib gcc-multilib git
  guile-1.8-libs lib32gcc1 lib32gomp1 libc-dev-bin libc6-dev libc6-dev-i386
  libc6-i386 libcurl3-gnutls libdb4.7 libdpkg-perl liberror-perl libexpat1
  libffi-dev libffi5 libgcrypt11 libgdbm3 libglib2.0-0 libgmp3c2 libgnutls26
  libgomp1 libgpg-error0 libgssapi-krb5-2 libidn11 libk5crypto3 libkeyutils1
  libkrb5-3 libkrb5support0 libldap-2.4-2 libltdl7 libmagic1 libmpfr4
  libncursesw5 libopts25 libopts25-dev libpcre3 libpopt0 libsasl2-2
  libsqlite3-0 libssl-dev libssl0.9.8 libstdc++6-4.4-dev libtasn1-3
  libtimedate-perl libtool libxml2 libxml2-dev linux-libc-dev llvm llvm-dev
  llvm-runtime m4 make mercurial mercurial-common mime-support openssl patch
  perl perl-modules pkg-config python python-central python-configobj
  python-minimal python-support python2.6 python2.6-minimal rsync ucf unzip
  uuid-dev wget zlib1g-dev
0 upgraded, 96 newly installed, 0 to remove and 0 not upgraded.
Need to get 111 MB of archives.
After this operation, 337 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libgdbm3 libncursesw5 libpopt0 libdb4.7 libgpg-error0 libkeyutils1
  libsasl2-2 libsqlite3-0 m4 patch perl-modules perl python-minimal python
  python-central python-support ucf autoconf libgmp3c2 libltdl7 guile-1.8-libs
  libopts25 libopts25-dev autogen autotools-dev automake binfmt-support
  libmpfr4 cpp-4.4 cpp libgomp1 gcc-4.4 gcc libstdc++6-4.4-dev g++-4.4 g++
  make libtimedate-perl bzip2 build-essential python-configobj bzr
  ca-certificates libffi5 clang lib32gcc1 lib32gomp1 gcc-4.4-multilib
  gcc-multilib liberror-perl git libffi-dev libglib2.0-0 zlib1g-dev libtool
  llvm-runtime llvm llvm-dev pkg-config rsync uuid-dev
E: There are problems and -y was used without --force-yes
The command '/bin/sh -c apt-get -o Acquire::Check-Valid-Until=false update &&   apt-get install -y automake autogen build-essential ca-certificates     gcc-multilib     clang llvm-dev  libtool libxml2-dev uuid-dev libssl-dev pkg-config     patch make xz-utils cpio wget unzip git mercurial bzr rsync --no-install-recommends' returned a non-zero code: 100
Makefile:48: recipe for target 'xgo-image' failed
make[1]: *** [xgo-image] Error 100
make[1]: Leaving directory '/home/marian/CODE/GO_PROJECTS/src/github.com/berfinsari/tracebeat/vendor/github.com/elastic/beats/dev-tools/packer'
vendor/github.com/elastic/beats/libbeat/scripts/Makefile:393: recipe for target 'package-setup' failed
make: *** [package-setup] Error 2

**Comment by andrewkroh** [comment]
What commit of elastic/beats do you have vendored? Try using the latest version from master because we are [not seeing any issues](https://beats-ci.elastic.co/job/elastic+beats+master+package/) with this at the moment.

**Comment by andrewkroh** [comment]
We have completely refactored how packaging works. I suggest trying the latest version of Beats.
