### ISSUE TITLE
Unable to install additional plugins

### ISSUE THREAD

**Issue by mouliveera** [elastic/beats#6731]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version: 5.6
- Operating System: Mac
- Steps to Reproduce: 
https://github.com/mouliveera/shell_scripts/pull/9

I need to install additional plugins. like redis, mongodb along with metricbeat on remote hosts. 

Can someone help me in fixing it.

**Comment by andrewkroh** [comment]
https://discuss.elastic.co/t/need-to-install-additional-plugins-along-with-metricbeat/126449
