### ISSUE TITLE
Proposal for adding a reference Kubernetes manifest for auditbeat

### ISSUE THREAD

**Issue by mumoshu** [elastic/beats#6733]
It seems like we have ones for filebeat and metricbeat but for auditbeat in https://github.com/elastic/beats/tree/master/deploy/kubernetes

According to [the explanation for running autitbeat in a docker container](https://www.elastic.co/guide/en/beats/auditbeat/current/running-on-docker.html), probably we should just start by running auditbeat in a privileged container in pods managed by a daemonset.

**Comment by jsoriano** [comment]
Added on #7642, @mumoshu it'd be great if you could take a look and give it a try :slightly_smiling_face:
