### ISSUE TITLE
[Auditbeat] export auditd key_name

### ISSUE THREAD

**Issue by jstoja** [elastic/beats#6736]
Hello,

I'm currently using auditbeat and it seems that it's not reading the key_name (`-k`) field from audit.rules(7).
At least, I don't see it either in the docs or in the `go-libaudit` codebase. Is there a reason not to have it?

If needed I can open an issue on go-libaudit instead.

For confirmed bugs, please report:
- Version: 6.2.2
- Operating System: Docker/Debian

**Comment by andrewkroh** [comment]
Keys are supported in audit rules with `-k <key>`. The [examples](https://github.com/elastic/beats/blob/5956ddd72e4756d6deed07587b1cd7b1432fbc06/auditbeat/auditbeat.yml#L36-L38) in the default config file use `-k`. And go-libaudit has [several tests](https://github.com/elastic/go-libaudit/search?utf8=%E2%9C%93&q=%22-k%22&type=) for the `-k` flag. Additionally keys can be added to syscall rules with `-F key=mytag`.

Could you please provide more detail about what is not working and how to reproduce the problem.

**Comment by jstoja** [comment]
> Keys are basically a mechanism for tagging and hence Auditbeat appends any keys to the tags field.

Okay! That was the information I was missing. I didn’t even thought about the tags, that’s a neat idea.

Since I didn’t find it in the docs, that could be a nice addition. I’ll try to add it ;)
