### ISSUE TITLE
Different case-sensitive behavior in the prospectors for Windows paths depending on the use of wildcards

### ISSUE THREAD

**Issue by ismael-hasan** [elastic/beats#6737]
When using direct paths in the Filebeat prospector in Windows, they are case-insensitive. If wildcards are involved, they become case-sensitive. 

- Version: 5.6, 6.2.3
- Operating System: Windows 10
- Steps to Reproduce: 

Create a file `C:\tmp\aA.txt` . Create a basic configuration for Filebeat as follows: 

```
filebeat.prospectors:

- type: log 
  paths: 
    - C:\tmp\aA.txt
  tail_files: false
output.console:
  pretty: true
```

Now, running some tests: 
- As configured, it works and gets the file
- Changing the path to `C:\tMp\Aa.txt` still reads the file - i.e, case insensitive 
- Changing the path to `C:\tMp\a*.txt` still reads the file - we are using wildcards in the filename and we have the same case in both the pattern and the original filename.
- Changing the path to `C:\tMp\A*.txt` does not read the file - i.e, case sensitive when using wildcards.

Checking the [Golang Glob syntax for patterns](https://golang.org/pkg/path/filepath/#Match), it does not seem to do special handling for case-insensitive matches (like the `i` flag in regex).

**Comment by andrewkroh** [comment]
I can see how this happens. In most cases the file system in Windows is case-insensitive. So if you specify the full-path to a file the casing doesn't matter because Windows resolves it for you. But when you switch to globs the matching happens in Go and its sensitivity behavior doesn't match that of the file-system.

Unfortunately Go doesn't expose a way control the behavior of the glob matching function.

Related
- https://github.com/golang/go/issues/5441#issuecomment-66079166

**Comment by urso** [comment]
Right, it's a limitation in the stdlib. Glob is not only used for walking a path, but also validating/checking a path in-memory only. That is, we will also need to track if we want glob to be case-sensitive or case-insensitive.

Is windows always case-insensitive, or is it a 'depends' on FS. E.g. with network shares NFS/Samba and a case-sensitive FS on the remote, what happens on the windows side?

**Comment by lachlann562** [comment]
all local paths are case insensitive, but it appears NFS shares can be case sensitive.
https://blogs.technet.microsoft.com/sfu/2010/05/28/nfs-share-name-is-case-sensitive/

**Comment by kiju98** [comment]
FYI, https://github.com/elastic/beats/issues/9176
