### ISSUE TITLE
Change topic titles in Getting Started documents to improve SEO rankings

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#674]
Users are running into problems when they configure the output for Filebeat because they are searching on "ELK tutorial" and finding the following 3rd party tutorial, which tells them to use an old (removed) option: https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elk-stack-on-ubuntu-14-04

We really want users to find our getting started information first: https://www.elastic.co/guide/en/beats/libbeat/current/getting-started.html 

I'll work with marketing to figure out if we can do anything on the web side to fix this problem. In the mean time, I'll improve the titles in the documentation to help search engines find and rank our content more accurately.

So, in the libbeat doc, instead of saying "Getting Started" we should say something like "Getting Started with Beats and the Elastic Stack" or "Getting Started with Beats and the Elastic (ELK) Stack"

@sejiek @Amy725 Is is OK for me to refer to use ELK parenthetically to help users find our info?

**Comment by Amy725** [comment]
@dedemorton hmmm that's tough because we really want to stop using ELK, but I understand your SEO concerns. I am no SEO expert, but is there anything we can do in the SEO fields vs. copy on the page to help with this? Any other alternatives that would help?

**Comment by dedemorton** [comment]
@Amy725  We source the doc in ASCIIDOC (text markup that gets built into HTML pages). I need to look more closely at the ASCIIDOC documentation, but it might be difficult for us to get meta tags added to specific topics. Plus it's my understanding that search engines don't give much weight to meta tags because they are so often abused. The way to really get something found is to put it in the title of a document. See our problem? Do you know if we have any SEO experts at Elastic who might know more about this?

**Comment by davgibney1** [comment]
Could try adding an invisible <div> at the top of the page (invisible as in, the font is white on white background, or something similar). It could be enough to add weight to the search terms

**Comment by dedemorton** [comment]
Note that I also asked the author of the Digital Ocean tutorial to fix the tutorial, and he has.
