### ISSUE TITLE
Feature request - Beats to report FQDN

### ISSUE THREAD

**Issue by TimWardOrigami** [elastic/beats#6741]
Beats report the hostname via beat.hostname (which often ends up in various other fields as well). But this is often or usually just the leaf part of the hostname, ie the "host" bit of "host.example.com".

This feature request is to add a field that gives the fully qualified domain name, ie "host.example.com" in the example above, appreciating that this won't always be easy, or indeed possible, to define or produce. But just returning the result of "hostname -f" on Linux would be a good start.

Use case: In an Elasticsearch index, I would like to be able to determine from which host a document originated. beat.hostname only works if the system as a naming scheme in which leaf names are unique, and not one that includes hosts named things like "node2.cassandra.staging.example.com", "node2.kafka.production.example.com", "node2.elastic.test.example.com" etc.

**Comment by bmagistro** [comment]
Currently running a mix of filebeat and most recently winlogbeat.  Our filebeat is reporting the full fqdn (CentOS 7 w/ filebeat 6.4) but winlogbeat is just reporting the host.  Would really like to see it report the FQDN from winlogbeat.
