### ISSUE TITLE
Improve section on configuring Filebeat to use Logstash

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#675]
The current documentation does not explicitly tell users that they need to disable elasticsearch output by commenting it out and enable logstash output by uncommenting the logstash section.

I want to make this very explicit because users are finding old tutorials on the web that tell them to use the enabled option. 

The topic section that needs to be changed is here: 
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-getting-started.html#_configuring_filebeat_to_use_logstash

**Comment by davgibney1** [comment]
Oh, this must be why I couldn't get logstash to work! I was following tutorials that said to have a line under the elasticsearch section that put the following,
enabled: false

But now, to actually disable it, you have to comment it out? Ah hah.

**Comment by ruflin** [comment]
@davgibney1 Exactly.
@dedemorton One way of solving this issue could also be creating a github issue with a good title that shows up on Google and has the solution inside ...

**Comment by dedemorton** [comment]
@ruflin Good idea. What is the common symptom that people see when they get the config wrong? Might help them find the issue more easily.

**Comment by davgibney1** [comment]
@dedemorton
This is an issue that I commented on when I was trying to setup my ELK stack:
https://github.com/logstash-plugins/logstash-input-beats/issues/35#issuecomment-168753620

**Comment by ruflin** [comment]
@dedemorton Thinking more about this I think we should actually go with the approach initially proposed by @urso as far as I remember: Creating an FAQ. That would be a page under the elastic.co docs that contains all the questions which most people will google for first to find an answer. An example here is enabled / disabled or SSL connection to LS not working.

**Comment by dedemorton** [comment]
+1 I actually have that on my list of stuff that I'd like to do.

**Comment by davgibney1** [comment]
Question about design: why the change from allowing the conf to specify "enabled:{true|false}" , to instead requiring elasticsearch component to be commented out in order to be disabled? Why not let it work both ways?

**Comment by davgibney1** [comment]
Would it be possible to design the "configtest" flag of the program to be able to determine if your config is messed up in this way? When I ran into this issue and tried troubleshooting, I would do a config test but it would return OK

**Comment by ruflin** [comment]
For your first question: The change was based on this discussion: https://github.com/elastic/libbeat/issues/264

For the second about config errors: That is definitively something we want to improve. Best is to follow the issue here: https://github.com/elastic/beats/issues/657
