### ISSUE TITLE
Support a delimiter parameter for the log prospector to allow dividing events on something other than a newline character?

### ISSUE THREAD

**Issue by joshuar** [elastic/beats#6751]
In Logstash, the file input supports a [delimiter parameter](https://www.elastic.co/guide/en/logstash/6.0/plugins-inputs-file.html#plugins-inputs-file-delimiter),  which allows you to divide up a file which does not use `\n` as the line separator into events. This is great for handling esoteric file formats.

Could we get a similar parameter for the log prospector in Filebeat to allow similar behaviour?

**Comment by ph** [comment]
We could use that I have in the TCP input (#6266) to split lines. I will check it after.
