### ISSUE TITLE
filebeat lost and duplicate issue

### ISSUE THREAD

**Issue by kfox1111** [elastic/beats#678]
So, I'm looking at adding filebeat running in a container to set of containerized applications we're running.

The plan to share the volume from the container generating logs with the container running filebeat and with a log rolling container since filebeat doesn't support log rolling itself. (That would be a useful feature. As would roll and delete log files after uploading).

Since the log files fill up rather quickly, we need log rolling and want to ensure log rolling does the right thing, but that filebeat will not duplicate or drop logs. Since its all dockerized, we also would like to be able to easily rebuild the container set without that happening. We can persist the log files and registry to help with that.

So far, I've not figured out how to configure it so that messages don't get duplicated/deleted.

Config option 1:
  * match on /var/log/kfox-test/*.log
  * log roll to /var/log/kfox-test/x.log.whatever
Tried this:
<pre>
echo c > /var/log/kfox-test/test7.log
echo c2 >> /var/log/kfox-test/test7.log
sleep 10
mv /var/log/kfox-test/test7.log /var/log/kfox-test/test7.log.old
echo c3 >> /var/log/kfox-test/test7.log.old
echo c4 >> /var/log/kfox-test/test7.log
sleep 10
/etc/init.d/filebeat restart
</pre>
log results was c, c2, c4. the c3 message was lost. So, this doesn't seem like the right way to configure it...

Config option 2:
  * match on /var/log/kfox-test/*.log
  * log roll to /var/log/kfox-test/x.0.log
Tried this:
<pre>
echo d > /var/log/kfox-test/test8.log
echo d2 >> /var/log/kfox-test/test8.log
sleep 10
mv /var/log/kfox-test/test8.log /var/log/kfox-test/test8.0.log
echo d3 >> /var/log/kfox-test/test8.log.old
echo d4 >> /var/log/kfox-test/test8.log
</pre>
and saw d, d2, d4, but not d3. but worse, if you then restart test8.0.log shows in the logs, with d, and d2 again, but not d3. puzzling...

So, I can't think of a way to properly configure filebeat for log rolling.

I have not exhaustively tested it but I think there are other race conditions too.

I believe part of the problem may be with the registry only keeping one set of file inode numbers in the database. When the system is processing quickly (or possibly everything's processing slowly), you can hit a race condition where part of filebeat detects the new file before the old file is finished off, the new inode/position replaces the old one, and file beats forgets about the old one I think. I believe each record should be persisted until a discovery pass completes and detects the inode is no longer on the file system. Any new filenames should then be able to find out that it had an old name and continue where it left off, preventing the race.

For the test, I just ran filebeat-1.0.1-x86_64.rpm on a host, and started with the init script, and ran the commands in that same terminal. No docker involved.

**Comment by tsg** [comment]
In both your examples, the c3/d3 is written to a `.old` file that doesn't match the pattern. I think Filebeat never checks the files that don't match the pattern, so that is expected. For the second example, it looks like a type and you meant to write to `test8.0.log`? Other than that, I'd expect the second example to work.

One thing to keep in mind, Filebeat aims to guarantee that no log lines are lost, but cannot guarantee that there are no duplicates created. This is mainly because the connection to ES/LS can be lost and we retransmit the same log lines.

**Comment by kfox1111** [comment]
Your right. It was a typo. Thanks for catching that.

I still think there are cases that it can loose data when there is a filebeat restart involved around the time a log rolling happens. Do you test for those cases? I think it will be important to be able to restart the container running the service and the filebeat container together to make it work nicely with container orchestration tools like Kubernetes.

So what is the correct configuration? To exclude the rolled files from the search, or include them? Either way the file crawler can still potentially see them.

Thanks,
Kevin

**Comment by ruflin** [comment]
Filebeat is able to handle log rotation as it doesn't compare the files based on file name, but based on the  inode and device id on Linux. This is also tested and should work as expected. So whenever you rotate files make sure that the rotated file is still tracked by filebeat so do you don't loose any log lines.

One thing to note here, is that there are some issues with shared file systems. You note above that you restart the filebeat container, which means to me you probably have a shared volume somewhere that you read from. The problem with shared volumes is that sometimes inodes or device id's just change. This leads to the problem, that filebeat thinks it's a new file. I didn't test if this is also the case with docker volumes, we saw it in the past on shared windows volumes.

**Comment by ruflin** [comment]
Closing this issue as no updates recently. For further questions please use https://discuss.elastic.co/c/beats/filebeat
