### ISSUE TITLE
[Auditbeat] - Enrich process.ppid data to aid intrusion detection work

### ISSUE THREAD

**Issue by kholia** [elastic/beats#6789]
According to https://www.elastic.co/guide/en/beats/auditbeat/master/exported-fields-auditd.html page, the `process.ppid` contains the parent process ID. The auditd exported fields do not contain the name and the age of the parent process.

This feature request is about adding extra fields (`process.ppid_name`, `process.ppid_age`) to the list of exported fields. These fields will contain the name, and the age of the parent process respectively.

When doing intrusion detection work, it is crucial to understand in what context a process was launched. Example intrusion detection scenario question -> Was the shell process launched by a cron job (expected on that server), or was the shell process launched by a PHP web application (where it isn't expected, and is an indicator of machine compromise)?

Some problem(s) I can see in implementing this feature,

1. Fetching information about the ppid process can be perhaps racy because it happens *after* monitoring the execve call, and noticing the ppid value in auditd data. There is a very tiny time window in which the the original ppid process can go away and pid range recycling can happen. The addition of `process.ppid_age` field will help us in detecting such cases.

2. The ppid process might go away by the time auditbeat goes about fetching its metadata. I am not sure now how common such a scenario could be. It would be good to know when this happens. Empty values of the `process.ppid_name` and `process.ppid_age` would indicate when this happens.

When monitoring execve (and family) calls on a busy system using Auditbeat, we really need to reduce the noise (by filtering out known, safe ppid<->pid relationships) to detect intrusions. I believe that adding `process.ppid_name`, and `process.ppid_age` fields can help us in doing so.

Thanks!

**Comment by kholia** [comment]
CC @pmoust.

**Comment by kholia** [comment]
CC @blaklaybul.

**Comment by pmoust** [comment]
This would be very handy to have, but would need to be marked in docs as "best-effort" and the caveats of it being explicitly declared.

Due to that information (`comm` of `ppid`) not being available in an atomic way in Linux audit framework, augmenting a log event with this information would be potentially affected by race conditions (TOCTOU).

**Comment by andrewkroh** [comment]
This would be nice to have. Maybe we could have a processor for this.

```
processors:
- add_process_metadata:
    match_pids: [process.ppid]
    target_fields:
    - process.parent.name: '%{[process.name]}%'
    - process.parent.args: '%{[process.args]}'
```

It would look up information about a process using the PID fields defined in `match_pids`. It would internally generate a document containing the information about that process: 

```json
{
  "process": {
    "name": "cat",
    "comm": "cat",
    "title": "cat /etc/passwd",
    "exe": "/usr/bin/cat",
    "args": [
      "cat",
      "/etc/passwd"
    ],
    "env": {
      "USER": "akroh"
    },
    "pid": 10011,
    "ppid": 1
  }
}
```

Then target_fields would specify how to map that data into the current event. You would use our [format string](https://www.elastic.co/guide/en/beats/libbeat/current/config-file-format-type.html#_format_string_sprintf) for accessing fields and assigning them. Or maybe the format strings are not even necessary and we could just have a mapping `process.parent.name: process.name`

**Comment by kholia** [comment]
I am looking forward to write a `- drop_event -> - equals -> process.parent.name: /usr/sbin/cron` rule.
