### ISSUE TITLE
Beats common backoff behavior

### ISSUE THREAD

**Issue by urso** [elastic/beats#6791]
The different outputs have different backoff settings and behaviour on error and when to backoff. The redis output does not even support exponential backoff.

Update all outputs, in order to have similar backoff behaviour.

**Comment by urso** [comment]
#7781 adds backoff support to the redis output.

**Comment by ppf2** [comment]
While this is not an "output" per say, the Beats monitoring connection to Elasticsearch (https://github.com/elastic/beats/issues/7966) can use an exponential backoff policy as well.

**Comment by urso** [comment]
Closing. There has been some improvements thanks to @ph.
