### ISSUE TITLE
Filebeat - nginx module - grok fail

### ISSUE THREAD

**Issue by Detzler** [elastic/beats#6798]
If some fcgi application like php throws errors to nginx then they look like this in the nginx error log:

```
2018/04/07 20:21:45 [error] 16234#0: *88661 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'TEST' in /var/www/vhosts/src/index.php:19
Stack trace:
#0 /var/www/vhosts/src/index.php(7): {closure}()
#1 /var/www/vhosts/src/index.php(19): awd::run(Object(Closure))
#2 {main}
  thrown in /var/www/vhosts/src/index.php on line 19" while reading response header from upstream, client: 79.237.34.117, server: localhost.net, request: "GET /?awd=de HTTP/2.0", upstream: "fastcgi://unix:///var/www/vhosts/system/php-fpm.sock:", host: "localhost.net"
```

The grok pattern in the filebeat nginx module can not parse this format.
The field `error.message` contains:

`Provided Grok expressions do not match field value: `...

- Version: filebeat version 6.2.3 (amd64), libbeat 6.2.3
- Operating System: Debian 8.10

**Comment by ruflin** [comment]
The current implementation of the nginx error fileset does not expect a multiline event. To support this we need a multiline definition on the prospector config side and adjust the grok pattern.

@Detzler Can you share your nginx config. Do you use an specific params for logging?

**Comment by Detzler** [comment]
hey @ruflin, it's a default nginx setup with `log_format combined`, nothing special.

Here is another one where grok fails:

`127.0.0.1 - - [12/Apr/2018:09:48:40 +0200] "" 400 0 "-" "-"`

**Comment by kvch** [comment]
I see the problem now. I am going to open a PR with the fix in a few hours.

**Comment by Odko** [comment]
@Detzler @ruflin 

Then, Any workaround to the multiline nginx error log ?

**Comment by kvch** [comment]
Could you provide an example log?

**Comment by Odko** [comment]
Mine is similar with the one in the issue description
> 2018/04/07 20:21:45 [error] 16234#0: *88661 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'TEST' in /var/www/vhosts/src/index.php:19
Stack trace:
#0 /var/www/vhosts/src/index.php(7): {closure}()
#1 /var/www/vhosts/src/index.php(19): awd::run(Object(Closure))
#2 {main}
  thrown in /var/www/vhosts/src/index.php on line 19" while reading response header from upstream, client: 79.237.34.117, server: localhost.net, request: "GET /?awd=de HTTP/2.0", upstream: "fastcgi://unix:///var/www/vhosts/system/php-fpm.sock:", host: "localhost.net"

**Comment by WerIstPeterHack** [comment]
@Odko

This worked for me: I put the filebeat multiline settings to the nginx module config file (/etc/filebeat/modules.d/nginx.yml), like so:

```
  error:
    enabled: true
    input:
      multiline.pattern: '^\d{4}\/\d{2}\/\d{2}'
      multiline.negate: true
      multiline.match: after

    var.paths:
      - /var/nginx/foobar_delogs/error.log*
```

**Comment by lgnap** [comment]
Another case/sample:
```
2019/05/29 23:29:41 [error] 3375#0: *92483 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function fsdf() in /srv/monitoring/test-error.php:2
Stack trace:
#0 {main}
  thrown in /srv/monitoring/test.php on line 2" while reading response header from upstream, client: 91.178.82.49, server: monitoring.fake.ovh, request: "GET /test-error.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/monitoring.sock:", host: "monitoring.fake.ovh"
```
