### ISSUE TITLE
Filebeat/Winlogbeat registry file

### ISSUE THREAD

**Issue by urso** [elastic/beats#6810]
Filebeat and Winlogbeat each use a very incompatible registry file format. A common file format should be provided by libbeat for use by filebeat, winlogbeat and potentially community beats.

Some problems we're facing with both registry file formats:
- Full snapshot + sync on every single update. Large registries, with only a small set of event sources being updated generate quite some encoding overhead.
- Filebeat has different workers updating a subset of fields, while overwriting the other workers fields. This fact very much complicates all processing in filebeat, enforcing an arbitrary order on state updates and startup/shutdown handling.

A key-value store with selective updates on fields or a simple parent-child relation of meta-data helps resolving most issues we're facing. The registry should be to hook up with the publisher pipeline itself, such that a beat only has to provide the fields to be updated with an event. The pipeline/registry will take care of everything else.

**Comment by jlind23** [comment]
@kvch as you recently worked on the registry, is this something still accurate?
