### ISSUE TITLE
Add auditbeat package to Elastic's Debian repository

### ISSUE THREAD

**Issue by kholia** [elastic/beats#6816]
It seems that Auditbeat is not currently available from Elastic's Debian repository (http://packages.elastic.co/beats/apt).

It would be awesome if Auditbeat could be installed from Elastic's Debian repository.

Thanks!

**Comment by andrewkroh** [comment]
The instructions for installing Beats from an APT repo can be found at https://www.elastic.co/guide/en/beats/auditbeat/current/setup-repositories.html. The full Elastic stack is contained in that repository.

The repo you gave is not what's listed in the current instructions.

**Comment by kholia** [comment]
Thanks @andrewkroh!

I found that URL in the https://github.com/elastic/ansible-beats/blob/master/tasks/beats-debian.yml file.

I will make sure that I follow the latest documentation :-)
