### ISSUE TITLE
Reevaluate Elasticsearch default bulk_max_size

### ISSUE THREAD

**Issue by urso** [elastic/beats#6818]
The default `bulk_max_size` for the Elasticsearch output is 50 events only. The value has been chosen (for beats 1.0.0) to be very conservative, to accomodate very small Elasticsearch 2.x clusters/nodes.

Let's check if the default value can be increased for Elasticsearch 6.x:
- Good value for small one node cluster?
- Good value for default elastic cloud cluster?

**Comment by ph** [comment]
I think we could also use a  `max_bytes_size` instead of `bulk_max_size`, we could use the same logic to split events for the logstash or the ES output at the pipeline level.

**Comment by urso** [comment]
Or both. I think the ES pipeline is indeed in events/documents, not byte usage. If the `bulk_max_size` is too big, single events might get a 429 (in bursts), no matter the event size.

**Comment by ph** [comment]
Adding a note here from @jsvd if we ever plan to split based on the size of the batch.

> ES output checks for the bulk size after compression, but ES checks the size after decompression, so you can send a small bulk request that still returns a 413 due to heavy compression
