### ISSUE TITLE
MongoDB Metricbeat Module Can't Find Reachable SSL Servers

### ISSUE THREAD

**Issue by ChristopherCorcoran** [elastic/beats#6821]
Using metricbeat-5.6.8, I am unable to connect to local mongo instance, using the mongo metricbeat module. The error I get is:

`ERR Error establishing direct connection to mongo node at [localhost]. Error output: no reachable servers.`

According to a developer in this issue:

https://discuss.elastic.co/t/ssl-options-for-metricbeat-when-connecting-to-mongo/84497

It's because SSL is not currently supported. Could we please get that added?

Thank You,
Chris

**Comment by jsoriano** [comment]
Thanks for reporting this, I'm closing it as there is already another issue about supporting TLS in mongodb module (#6619), please reopen if you consider it is a different issue.
