### ISSUE TITLE
MySQL Prepared Statement support

### ISSUE THREAD

**Issue by urso** [elastic/beats#683]
mysql plugin currently handles only query statements.

Add support for prepared-statements to analyzer.

**Comment by ferrydg** [comment]
Yes, please do.

**Comment by nokiomanz** [comment]
+1

I used to gather all my mysql data.
Since we changed to pdo I had to stop using packetbeat for mysql.

**Comment by danielzheng** [comment]
+1

orm odb operations rely heavily on prepare statements and packetbeat can do nothing about it.:frowning:

**Comment by swift1911** [comment]
+1 
Yes, i hope to Do
