### ISSUE TITLE
Add IP- and MAC-addresses to add_host_metadata

### ISSUE THREAD

**Issue by hypp** [elastic/beats#6867]
This is a PR as requested [here](https://github.com/elastic/beats/issues/5396#issuecomment-381143725).

I would like to dynamically add all IP-addresses and all MAC-addresses of the sender host to each event sent by filebeat.

**Comment by ruflin** [comment]
@hypp I think there was a slight misunderstanding. By PR I meant pull request with the code changes :-) I think for the tracking we are good with the other one. Do you mind if I close this issue here again to not have two?

**Comment by hypp** [comment]
Sorry for that, please go ahead and close the duplicate.




Den mån 16 apr. 2018 08:42Nicolas Ruflin <notifications@github.com> skrev:
