### ISSUE TITLE
RabbitMQ module queue metricset logs error

### ISSUE THREAD

**Issue by xadcoh** [elastic/beats#6876]
Hello.

This issue based on https://discuss.elastic.co/t/rabbitmq-module-path-prefix/127292/9

When RabbitMQ configured with option:
`management.path_prefix = /<prefix>`
And metricbeat rabbitmq module configured with:
```
- module: rabbitmq
  metricsets: ["queue"]
  period: 10s
  hosts: ["<ip>:15672/<prefix>/api/queues"]
  username: rabbitmetricbeatuser
  password: strongpass
```
Error occured in metricbeat logs:
```
2018-04-16T08:27:10.043Z        ERROR   schema/schema.go:41     Error on field 'count': Missing field: count, Error: Key disk_writes not found
2018-04-16T08:27:10.043Z        ERROR   schema/schema.go:41     Error on field 'count': Missing field: count, Error: Key disk_reads not found
```

For confirmed bugs, please report:
- Version: 
  metricbeat: 6.2.3
  kibana: 6.2.2
  elasticsearch: 6.2.2
- Operating System:
  centos 7 
- Steps to Reproduce: 
1. Install RabbitMQ
2. Put `management.path_prefix = /<prefix>` in /etc/rabbitmq/rabbitmq.conf
3. Install metricbeat
4. Configure rabbitmq module:
```
- module: rabbitmq
  metricsets: ["queue"]
  period: 10s
  hosts: ["<ip>:15672/<prefix>/api/queues"]
  username: rabbitmetricbeatuser
  password: strongpass
```

**Comment by ruflin** [comment]
Thanks for filing. I assume the path should here have no effect. If rabbitmq is configured without a prefix path you see the same errors?

Could you also share the exact rabbitmq version + rabbitmq config if possible?

**Comment by xadcoh** [comment]
If rabbitmq configured without `management.path_prefix = /<prefix>` there still same errors in log.

rabbitmq 3.7.4, Erlang 20.1.7

rabbitmq.conf:

```
    ## Clustering
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = ip
    cluster_formation.node_cleanup.interval = 10
    cluster_formation.node_cleanup.only_log_warning = false
    cluster_partition_handling = autoheal

    management.load_definitions = /etc/rabbitmq/definitions.json
    management.path_prefix = /rabbit

    ## The default "guest" user is only permitted to access the server
    ## via a loopback interface (e.g. localhost)
    loopback_users.guest = false

    ## Memory-based Flow Control threshold
    vm_memory_high_watermark.absolute = 256MB
```
```
  enabled_plugins: |
    [
      rabbitmq_consistent_hash_exchange,
      rabbitmq_federation,
      rabbitmq_federation_management,
      rabbitmq_management,
      rabbitmq_peer_discovery_k8s,
      rabbitmq_shovel,
      rabbitmq_shovel_management
    ]
```

in definitions.json users, queues, exchanes and bindings are described

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/beats/pull/6887 was merged.
