### ISSUE TITLE
mysql5.7.19 slow log format had change 

### ISSUE THREAD

**Issue by liuhuang9492** [elastic/beats#6882]
For confirmed bugs, please report:
- Version: filebeat 6.2.3 
- Operating System:  CentOS 6.9
 the MySQL 5.7.19 the slow log format
```
# Time: 2018-04-17T17:44:15.372281+08:00
# User@Host: root[root] @ localhost []  Id: 576311
# Query_time: 1.790578  Lock_time: 0.000138 Rows_sent: 0  Rows_examined: 896846
SET timestamp=1523958255;
SELECT source, reason, COUNT(id) AS report_count FROM report WHERE type = 'circle_article' AND deleted_at IS NULL GROUP BY source, reason HAVING report_count > 9 ORDER BY report_count DESC;
```
BTW the mysql modules pipeline.json is
```    
"gsub": {
      "field": "mysql.slowlog.query",
       "pattern": "\n# Time: [0-9]+ [0-9][0-9]:[0-9][0-9]:[0-9][0-9](\\.[0-9]+)?$",
       "replacement": "",
       "ignore_failure": true
    }
```
so I have change the pattern:
```    
"gsub": {
      "field": "mysql.slowlog.query",
       "pattern": "\n# Time: [0-9]+-[0-9]+-[0-9]+T[0-9]+:[0-9]+:[0-9]+.[0-9]+(\+[0-9]+:[0-9])?$",
       "replacement": "",
       "ignore_failure": true
    }
```
but I find some not correct info, in the kibana the mysql.slowlog.query like this:
```
SELECT source, reason, COUNT(id) AS report_count FROM report WHERE type = 'circle_article' AND deleted_at IS NULL GROUP BY source, reason HAVING report_count > 9 ORDER BY report_count DESC;
# Time: 2018-04-17T17:30:01.845052+08:00
```

but it not all mysql.slowlog.query have "# Time: 2018-04-17T17:30:01.845052+08:00 " 
so what happend and my changes is correct?

**Comment by ruflin** [comment]
@liuhuang9492 If I understand your request correctly, our mysql pipeline does not match the log file you have in your mysql slow logs. Now you change the pipeline but you get a wrong result?

Can you share what are the exact parts which didn't work and how you tried to fix it. Reverse engineering grok patterns is pretty hard :-)

**Comment by liuhuang9492** [comment]
@ruflin  hi，
    I am sorry that I had a error test. I had the test in localhost mysql and execute the slow sql in localhost. and I find the slow log format is not the same when I excuted the same slow SQL but in localhost and remote server. the slow log format is 
```
# Time: 180418 17:29:36
# User@Host: root[root] @ localhost []  Id: 165675344
# Query_time: 2.012857  Lock_time: 0.000039 Rows_sent: 1  Rows_examined: 7138643
SET timestamp=1524043776;
SELECT count(id) as total FROM user WHERE deleted_at=0;
```
```
# Time: 180418 17:33:26
# User@Host: remix[remix] @  [10.10.10.10]  Id: 165674369
# Query_time: 5.317408  Lock_time: 0.000118 Rows_sent: 653  Rows_examined: 3569801
use remix_liveroom;
SET timestamp=1524044006;
SELECT count(id) as total FROM user WHERE deleted_at=0;
```
you can find execute sql in the localhost the slow log show ```# User@Host: root[root] @ localhost []  Id: 165675344``` and excute sql in  the remote server the slow log show ```# User@Host: remix[remix] @  [10.10.10.10]  Id: 165674369``` so I also change the grok patterns
change before
```
      "patterns":[
        "^# User@Host: %{USER:mysql.slowlog.user}(\\[[^\\]]+\\])? @ %{HOSTNAME:mysql.slowlog.host} \\[(%{IP:mysql.slowlog.ip})?\\](\\s*Id:\\s* %{NUMBER:mysql.slowlog.id})?\n# Query_time: %{NUMBER:mysql.slowlog.query_time.sec}\\s* Lock_time: %{NUMBER:mysql.slowlog.lock_time.sec}\\s* Rows_sent: %{NUMBER:mysql.slowlog.rows_sent}\\s* Rows_examined: %{NUMBER:mysql.slowlog.rows_examined}\n(SET timestamp=%{NUMBER:mysql.slowlog.timestamp};\n)?%{GREEDYMULTILINE:mysql.slowlog.query}"
        ],
```
change after: ```(\\s*%{HOSTNAME:mysql.slowlog.host})? ``` but it seem error. 
so do you can get me a example? and what should I do ?

**Comment by gingerwizard** [comment]
Seems its reported via https://github.com/elastic/beats/issues/6492

**Comment by gingerwizard** [comment]
Reopening. Using Logstash isn't a solution. We need to fix the pipeline.
