### ISSUE TITLE
More flexibility in selector logging level

### ISSUE THREAD

**Issue by roncohen** [elastic/beats#6885]
Today you cannot configure a general logging level, but override certain selectors to log at another level. For example, we'd like to generally log at `WARN`, but also log `[monitoring]` at the `INFO` level. 

I discussed with @andrewkroh and he had the idea to add something like `logging.info.selectors: monitoring`. This would mean, regardless of the general logging level, set the level for the `monitoring` selector to `INFO`. 

That effectively means `logging.selectors` would be equivalent to `logging.debug.selectors`.

**Comment by ruflin** [comment]
I really like the idea. The advantage `logging.info.selectors` is that we could add it as a non breaking change.

One idea I'm playing around with is that the logging level can be changed through the API / central config without having to restart the Beat. This should make debugging issues easier. The above enhancement will allow the changes to be even more granular.
