### ISSUE TITLE
Filebeats missing IIS module

### ISSUE THREAD

**Issue by digitalmedia34** [elastic/beats#6890]
Maybe I am missing something, but I downloaded filebeat-6.2.4-windows-x86_64.zip but its missing IIS module??

**Comment by andrewkroh** [comment]
IIS is a new feature so it will be included in the next minor release. We don’t usually add new features to patch releases, just bug and security fixes. We use semantic versioning https://semver.org.

In the meantime you can try a snapshot build: https://beats-package-snapshots.s3.amazonaws.com/index.html?prefix=filebeat/

**Comment by digitalmedia34** [comment]
Thanks for you fast reply. I downloaded snapshot and I release its far from being a major release but I am seeing this error that maybe its a known issue:
 - Visualize: "field" is a required parameter
