### ISSUE TITLE
Filebeat 6.2.2 modules - Error JSON decoding the pipeline file: ingest/default.json

### ISSUE THREAD

**Issue by hawk199** [elastic/beats#6914]
hi,i am make an module for mys iis log,i use the grok to parse the message,it is wrong when the pattern field contains some regular expressions,but in the grok  debugger it's ok,
the grok config:
 "grok": {
      "field": "message",
      "patterns":[
        "\"%{DATA:iis.access.vhost}\" \"%{IPORHOST:iis.access.remote_ip}\,*\s*.*\" \"-\" %{DATA:iis.access.user_name} %{TIMESTAMP_ISO8601:iis.access.time} %{WORD:iis.access.method} %{DATA:iis.access.url} %{NOTSPACE:iis.access.query_string} \"HTTP\/%{NUMBER:iis.access.http_version}\" %{NUMBER:iis.access.response_code} %{NUMBER:iis.access.body_sent.bytes} \"%{DATA:iis.access.referrer}\" (?=\-|\"%{DATA:iis.access.user_agent}\")"
        ],
      "ignore_missing": true
    }
filebeat log error:
2018-04-21T21:47:08.934+0800	ERROR	pipeline/output.go:74	Failed to connect: Connection marked as failed because the onConnect callback failed: Error getting pipeline for fileset iis/access: Error JSON decoding the pipeline file: ingest/default.json: invalid character ',' in string escape code

i escape the json ,it's ok,but  the Provided Grok expressions do not match field value .

 "grok": {
      "field": "message",
      "patterns":[
        "\"%{DATA:iis.access.vhost}\" \"%{IPORHOST:iis.access.remote_ip}\\,*\\s*.*\" \"-\" %{DATA:iis.access.user_name} %{TIMESTAMP_ISO8601:iis.access.time} %{WORD:iis.access.method} %{DATA:iis.access.url} %{NOTSPACE:iis.access.query_string} \"HTTP\/%{NUMBER:iis.access.http_version}\" %{NUMBER:iis.access.response_code} %{NUMBER:iis.access.body_sent.bytes} \"%{DATA:iis.access.referrer}\" (?=\\-|\"%{DATA:iis.access.user_agent}\")"
        ],
      "ignore_missing": true
    }

my iis log: 
"wapapi.433.com" "113.16.249.49, 14.116.141.83" "-" - 2018-04-21 10:07:27.457 POST /app/v2/common/CheckDataIsUpdate - "HTTP/1.1" 200 560 "http://m.433.com/views/score/score_index.html?moduleid=score" "Mozilla/5.0 (Linux; U; Android 7.0; zh-CN; BLN-AL40 Build/HONORBLN-AL40) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 UCBrowser/11.9.4.974 Mobile Safari/537.36"

**Comment by ruflin** [comment]
@hawk199 Happy to see that you are trying to create a module. Could you post your question on discuss: https://discuss.elastic.co/c/beats/filebeat We try to keep  Github for confirmed bugs.

Please make sure when you post it on discuss, that you try to format the code as otherwise it's very hard to read.
