### ISSUE TITLE
error decoding json: invalid character '\\x00' looking for beginning of value

### ISSUE THREAD

**Issue by ohanaali** [elastic/beats#6915]
i am using file beat to read from high load report that are written to a local location in the disc.
the size of each log-file is up to 100 MB and log rotation is 10.
the writing speed is about 500 rows per second

each row is a valid json (i have tripped checked it with every tool exists)

my problem is i keep on receiving this error for no apparent reason (it is 1 log for every 200,000 rows give or take)
error decoding json: invalid character '\x00' looking for beginning of value

the error messages look like this
message: """\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000{"some keys": "info", "message": "the main key", "@timestamp": 2018-04-18T08:12:15.15Z", "additionl_info": " info "}"""
or
message: """\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000ys": "info", "message": "the main key", "@timestamp": 2018-04-18T08:12:15.15Z", "additionl_info": " info "}"""

again i have checked multiple time, the original data is valid and does not contains \x00 byts

your help is appriciated

my conf file contains:
json.keys_under_root: true
json.add_error_key: true
json.message_key: message
tail_files: true
json.overwrite_keys: true
json.overwrite_keys: true

**Comment by ruflin** [comment]
Are you reading from a local disk or a shared file system?

**Comment by ohanaali** [comment]
shared smb network drive, mounted to my ubuntu server

**Comment by ruflin** [comment]
Smb explains the above and is one of the reasons we don't recommend to use network volumes but install Filebeat on each edge node: https://www.elastic.co/guide/en/beats/filebeat/current/faq.html#filebeat-network-volumes I remember debugging an issue with a similar output quite some time ago and if I remember correctly the above \u0000 are actually what filebeat gets when it reads the file because of some caching, network flakyness or something like that (sorry, don't remember exactly what it was).

You solution is to read it directly from the machine where the disk is instead of mounting it through smb.

**Comment by ohanaali** [comment]
i have made the relevant changes and now i am reading it from the local disk.
problem persists with lower occurrence. (now it happens 1 for every 1.5 million logs)

**Comment by ruflin** [comment]
Can you share your full config? What kind of file system is it?

**Comment by shanghai-Jerry** [comment]
i am use nfs filesystem,  reading file always having null values like that. still don't konw why?

data likes belove:
![Image](https://github.com/user-attachments/assets/362c5380-a877-4b5d-ab27-232db0f51e71)
