### ISSUE TITLE
Beats Dashboards interval in TSVB should be updated to >=10s 

### ISSUE THREAD

**Issue by simianhacker** [elastic/beats#6924]
The auto interval doesn't work well with beats dashboard the the default frequency we use to ship data. We should update the interval on all TSVB visualizations to use `>=10s` or something similar.

See https://github.com/elastic/kibana/issues/17843 for background details and screen shot

**Comment by liza-mae** [comment]
I noticed this in 6.3.0 BC6 testing, all my TSVB dashboards showed zero data however the data showed up in the reports just fine.  Changing the interval from auto to >=1m got my dashboards showing again.

**Comment by kaiyan-sheng** [comment]
@simianhacker With `metricset.period` added into each event, do we have a separate issue to track using `metricset.period` as the interval?
