### ISSUE TITLE
Enhancement Request - Add ability to aggregate data at the beat level

### ISSUE THREAD

**Issue by krasekhi** [elastic/beats#6940]
It would be great if there was an ability to aggregate the data at the agent level (possibly in the processors?) before sending it logstash saving unnecessary data being sent across the network. 

* Ability to aggregate data into a new event while still send all events used in the aggregation
* Ability to aggregate data into a new event and drop all events used in the aggregation

**Comment by krasekhi** [comment]
Sure, one example would Metricbeat process data -

The ability to see the sum of CPU / Memory / # of Events being utilized by the chrome.exe for each collection period.

For Metricbeat where system.process.name:chrome.exe we get an event for each tab of chrome that is open.  It is possible to sum the data in Kibana by system.process.name but once you are not longer able to graph the collection time period (for this example - 1 minute periods) it then buckets the data into a higher interval that will sum all of the data for that period instead of keeping the sum collection interval then averaging the collection period into the new visualization bucket.

So in this case if we don't care about the Process ID we could aggregate the data at the agent level creating a new event i.e - system.process.total.cpu.pct and system.process.total.count with the sum for that collection period and have the option to drop / keep all events that were aggregated  it would be helpful for not only visualizing the data but also saving network bandwidth from sending unnecessary data.

**Comment by thisisunreal** [comment]
I would also like the ability to aggregate on the beats level before sending through to logstash. A big reason we don't use beats is because of this issue. For example, when we ingest firewall data, on average the aggregation works out to be an about 80% change in EPS volumes.
