### ISSUE TITLE
Filebeat setup is throwing a security exception

### ISSUE THREAD

**Issue by liza-mae** [elastic/beats#6951]
Version: 6.3.0 Snapshot
OS: Ubuntu 16.04 
Steps to Reproduce: 
Install latest 6.3.0 snapshot and run filebeat setup, I am getting a security exception below. 

./filebeat setup
Loaded index template
Loading dashboards (Kibana must be running and reachable)
Loaded dashboards
Exiting: 1 error: Error setting up ML for apache2: 10 errors: [security_exception] action [cluster:admin/xpack/ml/datafeeds/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/datafeeds/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/datafeeds/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/datafeeds/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/datafeeds/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/job/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/job/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/job/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/job/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/job/put] is unauthorized for user [kibana]

**Comment by tsg** [comment]
@kvch @jgowdyelastic  FYI, if you have an idea on this one.

**Comment by jgowdyelastic** [comment]
By default the `kibana` user has a limited set of privileges.
You'll need to use a user who has the `machine_learning_admin` role to be able to create ML jobs.

**Comment by tsg** [comment]
@liza-mae Which config did you use on the Filebeat side?

**Comment by liza-mae** [comment]
@tsg I don't think I set anything.  I am using elastic user and I ran filebeat setup as root.  Is there some place you would like me to check ?

**Comment by tsg** [comment]
@liza-mae We can't reproduce the error that you're getting, but we get a maybe-related problem if the `setup.kibana.username` and `setup.kibana.password` are not set. 

I'm still not sure why you get a different error from us, could you get the filebeat.yml for us?

**Comment by liza-mae** [comment]
@tsg attached is my filebeat.yml 

[filebeat.yml.txt](https://github.com/elastic/beats/files/1968183/filebeat.yml.txt)

**Comment by kvch** [comment]
@tsg I would like to try reproducing it again tomorrow. I had environment problems in the afternoon during testing. So I might missed something.

**Comment by liza-mae** [comment]
Just tried 6.3.0 BC2 and it happens there too for me.

**Comment by tsg** [comment]
@liza-mae I see you're using the `elastic` user to connect to Elasticsearch, but the `kibana` user to connect to Kibana. I think you should use the `elastic` user for both. From what I know the `kibana` user is supposed to be used by the Kibana server itself, not by end users.

**Comment by tsg** [comment]
I'd expect your configuration to work with BC2 if you change `kibana` into `elastic`. It's great that you're testing with security and TLS enabled, btw, I think we don't currently do that in our own tests.

**Comment by liza-mae** [comment]
Thanks @tsg I will make the script updates and I confirmed the error does not occur with elastic user.

**Comment by tsg** [comment]
Thank you @liza-mae , that's good to hear, I'm closing this ticket.

I have a small request: Starting with BC3, it will be enough to specify the `username` and `password` only in the ES section of the config (`output.elasticsearch`), the Kibana part (`setup.kibana`) of the config will automatically inherit them from there. Therefore, would it be possible to remove the `setup.kibana.username` and `setup.kibana.password` from your config? This would help us with the test coverage for this use-case, which is important because it's used by the solution pages.

**Comment by liza-mae** [comment]
Thanks @tsg I will make those updates for BC3.

**Comment by LeeDr** [comment]
Best security practice would be to configure and use users with the minimal privileges needed.  For my testing I create a role and user for the `output.elasticsearch` section like this;

`role/beats_writer { "cluster": ["manage_index_templates","monitor"], "indices": [ { "names": [ "*beat-*" ], "privileges": ["write","delete","create_index"] } ] }`

`user/beats_internal { "password" : "changeme",  "roles" : [ "beats_writer","kibana_system" ], "full_name" : "beats_internal", "email" : "beats_internal@test.co"}`

And another role and user for the `setup.kibana` section like this (for metricbeat and packetbeat I use the kibana user but for filebeat now I use this new beats_setup user);

`role/beats_reader { "cluster": [], "indices": [ { "names": [ "*beat-*" ], "privileges": ["read", "view_index_metadata"] } ]}`

`user/beats_setup { "password" : "changeme", "roles" : [ "kibana_system", "machine_learning_admin", "beats_reader" ], "full_name" : "beats_setup", "email" : "beats_setup@test.co" }`

**Comment by liza-mae** [comment]
I can add testing with minimal user permissions in addition to superuser I think both cases is best to test.
