### ISSUE TITLE
Filebeat integration suite is failling on `test_load.Test.test_no_missing_events`

### ISSUE THREAD

**Issue by ph** [elastic/beats#6961]
I've been working on another FB issue and I've discovered a problem with the integration test suite on Filebeat. I can make `test_load.Test.test_no_missing_events` fails all the time on my mac, on Linux we only see one failure. When I run the test individually, It doesn't fails, but running the whole test suite with `make test` cause the problem.

After running git bisect, it seems related to some refactoring 0923a4cca8bce224283fafc9b6fc19c99bf51e5d

```
======================================================================
ERROR: Test that filebeat does not loose any events under heavy file rotation and load
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ph/go/src/github.com/elastic/beats/filebeat/tests/system/test_load.py", line 71, in test_no_missing_events
    max_timeout=15)
  File "/Users/ph/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 325, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 15 seconds.
-------------------- >> begin captured logging << --------------------
beats-logger: DEBUG: 0
```

**Comment by urso** [comment]
Is this somehow related to #6879 ?

**Comment by ph** [comment]
@urso I thought so at the beginning, but running bisect point me to to this change and there is no panic in the log.

**Comment by ph** [comment]
Updated the description with the actual test failures

**Comment by ph** [comment]
Still looking into this, this seems a legit error. I haven't figured why no other in the team are affected by this issue.

Looking at the artifacts from the test run we have the following:

```
run/test_load.Test.test_no_missing_events/log$ cat * | wc -l
    1000

cat filebeat  | wc -l
     832


```

**Comment by ph** [comment]
I seems to hit the fd limit on my laptop, not sure what changed.

**Comment by ph** [comment]
For posterity, since Apple like to change how to deal with fd limits, I found this guide https://gist.github.com/devinrhode2/4cbf7f02a9701510d61f5be0515b8286 handy.
