### ISSUE TITLE
Duplicate menu link for elasticsearch node_stats metricset

### ISSUE THREAD

**Issue by sophiec20** [elastic/beats#6968]
Issue in online docs "6.2 (current)". 
"Elasticsearch node_stats metricset" appears twice in the rhs menu. Only one of the links works.

https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-elasticsearch-node_stats.html

https://www.elastic.co/guide/en/beats/metricbeat/current/_elasticsearch_node_stats_metricset.html

![image](https://user-images.githubusercontent.com/4185750/39377210-471505c8-4a4c-11e8-8926-b1f94a3ddd04.png)

**Comment by jsoriano** [comment]
Fixed in #6972 and #6973
