### ISSUE TITLE
Clarify max_retries for kafka output

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#6982]
https://www.elastic.co/guide/en/beats/filebeat/current/kafka-output.html#_literal_max_retries_literal_3

>max_retries
The number of times to retry publishing an event after a publishing failure. After the specified number of retries, the events are typically dropped.
Filebeat will ignore the max_retries setting and retry until all events are published.
The default is 3.

Because we are reusing the definition of max_retries across beats, it can be helpful to clarify the above in the documentation.  Afaik, filebeat will ignore Beat's general output `max_retries` setting, as well as the underlying Sarama client's `Producer.Retry.Max` setting (which defaults to 3). Instead, it will always retry indefinitely for guaranteed delivery.

I believe the same applies to winlogbeat as well, but the winlogbeat documentation seems to indicate that it will only retry 3 times:
https://www.elastic.co/guide/en/beats/winlogbeat/current/kafka-output.html#_literal_max_retries_literal_3

>max_retriesedit
The number of times to retry publishing an event after a publishing failure. After the specified number of retries, the events are typically dropped.
Set max_retries to a value less than 0 to retry until all events are published.
The default is 3.

**Comment by dedemorton** [comment]
@andrewkroh Can you confirm that Winlogbeat ignores max_retries for the kafka output?
