### ISSUE TITLE
For ML setup, Kibana credentials are not inherited from the Elasticsearch output

### ISSUE THREAD

**Issue by tsg** [elastic/beats#6992]
- Version: 6.3
- Steps to Reproduce: 

* Install ES and KB with security enabled.
* Configure the Elasticsearch output with `username: elastic` and `password: changeme`.
* Try `./filebeat setup -e --machine-learning`

You get an error because Kibana doesn't have the credentials. I was expecting the Kibana connection to inherit the credentials from the ES output, and that works fine for the dashboards.

If you add `setup.kibana.username: elastic` and `setup.kibana.password: changeme`, loading ML configs works again.

**Comment by ruflin** [comment]
@tsg As https://github.com/elastic/beats/pull/6993 is merged, can this one be closed?

**Comment by tsg** [comment]
Yes, I linked the wrong issue in the commit. Thanks!

**Comment by LeeDr** [comment]
I don't think inheriting the credentials makes sense.  We shouldn't assume everyone is using the super user everywhere in their stack.
In my testing, I create a user who has write access to `*beats*` index patterns and use that in the output.elasticsearch section.  And I use the kibana server user in the setup.kibana section (and even that is using more privileges than needed).
