### ISSUE TITLE
Topbeat: See complete command line options

### ISSUE THREAD

**Issue by biswajit86** [elastic/beats#702]
Is there a way in topbeat to see the complete list of arguments that are part of the process.

For ex , one of our processes is marked as 
    regression_listener_fs cadence 3.16.1 Performance 289562235

In the topbeat output this is *truncated*  to `regression_listener_fs` . 

Is there any way to get the command line alongwith the full list of parameters ?

**Comment by andrewkroh** [comment]
See #590

**Comment by andrewkroh** [comment]
PR #749 added this feature to the master branch.

**Comment by andrewkroh** [comment]
This will be released in 1.2.0.
