### ISSUE TITLE
Add support for pg_stat_statements to MetricBeat Postgresql module

### ISSUE THREAD

**Issue by zinefer** [elastic/beats#7048]
# MetricBeat statements metricset 

I think adding support for `pg_stat_statements` to the postgresql module would be a useful improvement. With this metricset I can:
- Calculate a Query Per Second
- Calculate CPU usage per query
- Identify long running queries
- Count unique queries
- Get query run count
- Get block data per query

I will attempt a Pull Request but this will be my first time writing GO.

[Postgresql pg_stat_statments](https://www.postgresql.org/docs/9.4/static/pgstatstatements.html)
[Forum Discussion](https://discuss.elastic.co/t/metricbeat-statements-metricset/131055)

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/beats/pull/7060 was merged.
