### ISSUE TITLE
Filebeat.autodiscover for docker container logs

### ISSUE THREAD

**Issue by venkiradkris** [elastic/beats#7077]
Hi - How to configure file beat yml to read logs of all docker containers?

Below is the configuration i am using now (Working perfectly fine) which i feel is not clean way of coding.

filebeat.autodiscover:
  # List of enabled autodiscover providers
  providers:
    - type: docker
      templates:
        - condition.not:
            equals.docker.container.image: ABCD
          config:
            - type: log
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

Regards
Venkat

**Comment by kvch** [comment]
Github issues are for reporting bugs and opening enhancement requests. Also, please don't ask the same question multiple times.
