### ISSUE TITLE
Document rough disk space requirement for running modules

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#7084]
We need to add a statement to our getting started docs (including product solution pages) to clarify disk requirements. Something like:

Elasticsearch requires at least 10% free disk space to work correctly.

Why? We make it pretty simple for users to get started with modules. They just run a few commands, and it works. However, if they're running a module like Metricbeat on a system that doesn't have sufficient disk space, they'll exceed the low disk watermark:

````
[2018-05-11T15:58:27,023][INFO ][o.e.c.r.a.DiskThresholdMonitor] [VIea7nB] low disk watermark 
[85%] exceeded on [VIea7nBYSZiElH32II4G1A][VIea7nB][/Users/dedemorton/BuildTesting
/demo_getting_started/outputdir/elasticsearch-6.3.0/data/nodes/0] free: 25.3gb[10.8%], replicas will 
not be assigned to this node
````

They *should* be looking at the output and clear up some space, but novice users, who don't know what a replica is, might not even realize it's a problem. If they run the setup command, they end up with  indexes in Kibana that are read-only. Then, when they try to view the Beats dashboards, they see errors like: 

```
blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];: [cluster_block_exception] blocked 
by: [FORBIDDEN/12/index read-only / allow delete (api)];
```

**Comment by ruflin** [comment]
+1 on adding such a note. I wonder if there are other things users should know about?

Could we phrase this more generic to something like "make sure your elasticsearch cluster is healthy and can accept more data" and then link to the appropriate docs in the Elasticsearch docs? I'm worried that if we pick a specific number it will get outdated and it can also be use case specific.

**Comment by dedemorton** [comment]
Closing this issue because it's been open for quite awhile and I haven't noticed many users getting snagged by it.
