### ISSUE TITLE
[metricbeat] support daemonset stats

### ISSUE THREAD

**Issue by f0** [elastic/beats#7086]
it would be usefull if metricbeat has support for daemonset stats , like deployment stats

**Comment by ruflin** [comment]
@f0 Are you referring to k8s?

**Comment by exekias** [comment]
Hi @f0, I guess you want DaemonSet stats in the same way we support Deployment stats, this is, with metrics from `kube-state-metrics`. We have a broader issue with many of the features we want to support for k8s use case, which includes DaemonSet: https://github.com/elastic/beats/issues/7058

Closing as a duplicate, please reopen if you are talking about something else.
