### ISSUE TITLE
Simplify the Golang update process

### ISSUE THREAD

**Issue by ph** [elastic/beats#7090]
Updating Beats to a newer version of Golang requires multiple changes in different files and also renaming a few directories. We should automate that process to simplify it and rely as much as possible on the version defined in `.go-version`.

See #7088 for the list of required changes.

**Comment by ph** [comment]
Since this issue might require refactoring some part of the code it would a good idea to move to sha256 when doing it. (https://github.com/elastic/beats/issues/7104)

**Comment by michalpristas** [comment]
most of the things are done in cross  build but i think we still need to provide something like make golang {version}` command which will update `.go.version` and all Dockerfiles to same version so we dont forget to update those

**Comment by ph** [comment]
@michalpristas I believe its was already done by @mikemadden42  in https://github.com/elastic/beats/blob/master/dev-tools/cmd/update_go/update_go_version.go

I am going to close this.
