### ISSUE TITLE
Use sha256 for golang when bootstrapping our docker image.

### ISSUE THREAD

**Issue by ph** [elastic/beats#7104]
The docker images are using a sha1 to do the checksum, the official Golang distribution has moved to  sha256 for quite some time.

https://github.com/elastic/beats/blob/master/dev-tools/packer/docker/xgo-image-deb7/go-1.10.2/Dockerfile#L13

https://github.com/elastic/beats/blob/master/dev-tools/packer/docker/xgo-image/go-1.10.2/Dockerfile#L11-L13

**Comment by urso** [comment]
@ph @mikemadden42 	Is this still an issue or can we close it?

**Comment by ph** [comment]
We can close this everything is done in the crossbuild repository.
