### ISSUE TITLE
Proxy settings in heartbeat

### ISSUE THREAD

**Issue by kvalev** [elastic/beats#7119]
According to the [documentation](https://www.elastic.co/guide/en/beats/heartbeat/master/configuration-heartbeat-options.html#monitor-http-proxy-url), one can configure a proxy to be used for an HTTP monitory by either providing the `proxy_url` parameter or by setting the `HTTP_PROXY` environment variable. However it seems that the HTTP_PROXY environment is actually ignored (and even if it isnt, it does not take NO_PROXY into account).
From what I can tell, the [elasticsearch output](https://github.com/elastic/beats/blob/32c60c136eda2256f25cac361c7ab37444f4a260/libbeat/docs/outputconfig.asciidoc#proxy_url) that takes the environment variables into account.

**Comment by ruflin** [comment]
Can you share your full config, heartbeat version and heartbeat logs?

**Comment by kvalev** [comment]
I am not using a publicly accessible systems, so there is no point in sharing the config. Anyway the issue was quite easy to solve (see patch below).
However it seems to be another, a bit more complicated problem - when using an heartbeat monitor for an https endpoint that goes through an http proxy, the ssl verification mode is being ignored.

```
From e7053d8b8ebabe06ddfcc66d41b7699c0e501561 Mon Sep 17 00:00:00 2001
From: Krassimir Valev <krassimir_valev@yahoo.com>
Date: Thu, 17 May 2018 09:52:05 +0200
Subject: [PATCH] Advanced proxy settings for the http heartbeat monitor

---
 heartbeat/monitors/active/http/http.go | 14 +++++++-------
 heartbeat/monitors/active/http/task.go |  2 +-
 2 files changed, 8 insertions(+), 8 deletions(-)

diff --git a/heartbeat/monitors/active/http/http.go b/heartbeat/monitors/active/http/http.go
index 986f1b0..eceed85 100644
--- a/heartbeat/monitors/active/http/http.go
+++ b/heartbeat/monitors/active/http/http.go
@@ -57,12 +57,12 @@ func create(
 
 	jobs := make([]monitors.Job, len(config.URLs))
 
-	if config.ProxyURL != "" {
-		transport, err := newRoundTripper(&config, tls)
-		if err != nil {
-			return nil, err
-		}
+	transport, err := newRoundTripper(&config, tls)
+	if err != nil {
+		return nil, err
+	}
 
+	if transport.Proxy != nil {
 		for i, url := range config.URLs {
 			jobs[i], err = newHTTPMonitorHostJob(url, &config, transport, enc, body, validator)
 			if err != nil {
@@ -71,7 +71,7 @@ func create(
 		}
 	} else {
 		for i, url := range config.URLs {
-			jobs[i], err = newHTTPMonitorIPsJob(&config, url, tls, enc, body, validator)
+			jobs[i], err = newHTTPMonitorIPsJob(url, &config, tls, enc, body, validator)
 			if err != nil {
 				return nil, err
 			}
@@ -82,7 +82,7 @@ func create(
 }
 
 func newRoundTripper(config *Config, tls *transport.TLSConfig) (*http.Transport, error) {
-	var proxy func(*http.Request) (*url.URL, error)
+	proxy := http.ProxyFromEnvironment
 	if config.ProxyURL != "" {
 		url, err := url.Parse(config.ProxyURL)
 		if err != nil {
diff --git a/heartbeat/monitors/active/http/task.go b/heartbeat/monitors/active/http/task.go
index f48ae83..4978b89 100644
--- a/heartbeat/monitors/active/http/task.go
+++ b/heartbeat/monitors/active/http/task.go
@@ -68,8 +68,8 @@ func newHTTPMonitorHostJob(
 }
 
 func newHTTPMonitorIPsJob(
-	config *Config,
 	addr string,
+	config *Config,
 	tls *transport.TLSConfig,
 	enc contentEncoder,
 	body []byte,
-- 
2.9.0


```

**Comment by ruflin** [comment]
Could share a generalised version of your config file? This should make why the code change above helps easier to understand. Perhaps you can open a PR with the change and we can discuss more details there?

**Comment by kvalev** [comment]
Here is a somewhat generalized version of the config file:
```
heartbeat.monitors:
- type: http
  schedule: '@every 2m'
  watch.poll_file:
    path: monitors/http.json
    interval: 30s
  check.response.status: 200

- type: http
  schedule: '@every 2m'
  watch.poll_file:
    path: monitors/http-via-proxy.json
    interval: 30s
  proxy_url: 'myproxy'
  check.response.status: 200

output.elasticsearch:
  hosts: ["hello:9200"]
```

Some of the hosts are only reachable via a proxy, which requires separating them from the others, so that the `proxy_url` can be configured. Leaving out the proxy configuration, leads to connection issues (even though the HTTP(S)/NO_PROXY environment variables are set).

I managed to reproduce both issues in a unit test and will submit it as a PR to showcase the problems.

**Comment by cawoodm** [comment]
So there's no support for http:// or https:// schemas when configuring a proxy?

**Comment by andrewvc** [comment]
@cawoodm please see the example in our now updated docs here https://www.elastic.co/guide/en/beats/heartbeat/master/configuration-heartbeat-options.html#monitor-tcp-proxy-url . Closing due to the linked PR no longer being something we'll pursue.
