### ISSUE TITLE
[Auditbeat] Crash when validating faulty configuration

### ISSUE THREAD

**Issue by kholia** [elastic/beats#7130]
Version: Auditbeat 6.2.4 (Linux + macOS)

```
$ auditbeat test config --strict.perms=false -c auditbeat-crasher-minimal.yml.txt
...
panic: should not happen [recovered]
	panic: should not happen

goroutine 1 [running]:
github.com/elastic/beats/vendor/gopkg.in/yaml%2ev2.handleErr(0xc42025b808)
	/go/src/github.com/elastic/beats/vendor/gopkg.in/yaml.v2/yaml.go:153 +0x9f
panic(0x4a94880, 0x4cf8ca0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/elastic/beats/vendor/gopkg.in/yaml%2ev2.yaml_parser_save_simple_key(0xc4200c9080, 0x0)
	/go/src/github.com/elastic/beats/vendor/gopkg.in/yaml.v2/scannerc.go:877 +0x2b7
github.com/elastic/beats/vendor/gopkg.in/yaml%2ev2.yaml_parser_fetch_plain_scalar(0xc4200c9080, 0x202)
	/go/src/github.com/elastic/beats/vendor/gopkg.in/yaml.v2/scannerc.go:1417 +0x40
```

Expected result: Auditbeat should fail the validation gracefully instead of crashing.

I am attaching the [reproducer here](https://github.com/elastic/beats/files/2015769/auditbeat-crasher-minimal.yml.txt). It seems that missing a terminating double-quote (`"`) in the configuration can lead to such crashes. The `process.exe: "/sbin/auplink` seems to be problematic.

**Comment by kholia** [comment]
The fault seems to lie in a library package and not in auditbeat itself (perhaps?).

**Comment by faec** [comment]
This appears to be fixed in current versions, closing
