### ISSUE TITLE
[Auditbeat] Add file.extension field

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#7138]
When reporting events containing file information it would be useful to include a field containing the file's extension.

```yaml
file.path: /etc/apache/httpd.conf
file.extension: conf
```

**Comment by denishpatel** [comment]
@andrewkroh any chance to get this field in auditbeat 7.3.2 release?

**Comment by andrewstucki** [comment]
This was added in https://github.com/elastic/beats/pull/18012
