### ISSUE TITLE
Need info on if we can connect establish extract logs from Mongo Db using filebeat and then transfer it to RabitMQ ?

### ISSUE THREAD

**Issue by prashantharaonv** [elastic/beats#7147]
I am new to filebeat, though I have heard people using it for extracting logs from mongo db and saving it in file. What I would like to achieve is to further transfer logs collected from mongo db via filebeat to put in RabitMQ? It would also be great if we can do some preprocessing(add headers) before transferring to RabitMQ?

Is it possible? If so, would some one throw lights into this?

Thanks,
Prashantha

**Comment by kvch** [comment]
Github issues are reserved for bug reports and enhancement requests. Please open a topic on Discuss with your question: https://discuss.elastic.co/
