### ISSUE TITLE
[Docs] Update the API used in `docs/devguide/newbeat.asciidoc`

### ISSUE THREAD

**Issue by ph** [elastic/beats#7159]
The content of the [file](https://github.com/elastic/beats/blob/master/docs/devguide/newbeat.asciidoc) need to be updated with the the beats generator.

```golang
	event := common.MapStr{ (1)
			"@timestamp": common.Time(time.Now()), (2)
			"type":       b.Name,
			"counter":    counter,
		}
		bt.client.PublishEvent(event) (3)
		logp.Info("Event sent")
		counter++
```

TODO:
- [ ] use `bt.client.Publish()`
- [ ] use `beat.Event` instead of using directly a `common.MapStr`
- [ ] update the description.

**Comment by jlind23** [comment]
Backlog grooming: Closing for now until further update
