### ISSUE TITLE
[Filebeat] Give the ability to have a registry file per prospector

### ISSUE THREAD

**Issue by jerome83136** [elastic/beats#7171]
Hi,

I currently have one agent per server. As I have several applications per server; I have more than one log file to read from the same filebeat agent.
To address it, I have 1 prospector configuration file per application; pointing to the relevant application's log file.

Sometimes I need to read a specific log file from the beginning, but I don't want to delete the whole registry file to do this because it would make filebeat reading all my local application's log files from the beginning.

Is there a way to specify a specific registry file per prospector ?
Example:

- server's filebeat agent
  -- prospector for myapp1  --> registry file myapp1
  -- prospector for myapp2  --> registry file myapp2
  -- ...

So that if I clean the registry file of myapp1 and restart the agent, only the log files of myapp1 will be read again from the beginning

Thank you for your help

Best regards
Jérôme

**Comment by ph** [comment]
The registry is currently a global setting.

```
# Name of the registry file. If a relative path is used, it is considered relative to the
# data path.
#filebeat.registry_file: ${path.data}/registry
```

I see values in this feature,  we might need way to uniquely define an input, some kind of ID.

@jerome83136 in your proposal it would be possible to have 2 inputs (prospectors) to watch the same files?

**Comment by ruflin** [comment]
We discussed this quite a bit in the past and it would required as indicated above each prospector to have persistent unique identifier as otherwise it would not be possible across restarts to identify which files belong where.

I think an other approach here would be to provide a command like `filebeat clean registry `/your/path.*` that would remove all the states for these files. I think the user should not have to modify the registry file manually.

**Comment by ph** [comment]
still another thing, that could lead to some inconsistency with physical disk vs in memory, this will require more toughs.

**Comment by jerome83136** [comment]
Hi,
Glad to see this idea could maybe help

Some more ideas to help:

- I think the registry file should not be in-memory, because if the filebeat agent process dies it will not be able to restart from the last know processed line
- I also agrees in the fact that the user should never have to manually alter the registry file. Maybe some kind of filebeat API entry point could be used to instruct the agent to clean this file ? Or maybe a command ?

Hope it could help
Best regards
Jérôme
