### ISSUE TITLE
vSphere Beats module - inconsistent usage of host name vs host ID 

### ISSUE THREAD

**Issue by bogd** [elastic/beats#7187]
[ Initially reported on the forum - see [here](https://discuss.elastic.co/t/vsphere-beats-module-inconsistent-usage-of-host-name-vs-host-id/133321) for the original conversation ]

 I noticed a strange inconsistency regarding the "host" fields:

In the "host" metricset:
`vsphere.host.name	esx01.lab.example.com`

In the "virtualmachine" metricset:
`vsphere.virtualmachine.host	host-961`

It looks like the "vsphere.host.name" is using the actual hostname, and "vsphere.virtualmachine.host" is using the internal host ID (or, to be more specific, the managed object ID/managed object reference).

While it isn't difficult to map the two together manually, this requires an additional step in order to aggregate data from VMs running on the same host. Also, it seems to contradict the documentation, which specifically lists the "vsphere.virtualmachine.host" field as "hostname".

Looking at the code, the host code pulls hs.Summary.Config.Name (HostSystem.Summary.Config.Name - a string containing the host name), while the virtualmachine code pulls vm.Summary.Runtime.Host.Value (HostSystem.Value, which seems to return the host ID. Shouldn't this one also be vm.Summary.Runtime.Host.Summary.Config.Name?)

Is there any chance this could be changed in a future release of the Beats module?
[Edited to clarify: I'm not looking for a change in the behavior of `vsphere.virtualmachine.host` - that could break existing implementations. I'm referring to adding the actual hostname as a new metric (maybe `vsphere.virtualmachine.hostname`?) - that would solve my issue beautifully 😁 ]

Thank you!

**Comment by ruflin** [comment]
Thanks for the detailed report. +1 on adding the hostname field. We could use here directly `host.name` for this field from ECS: https://github.com/elastic/ecs#host

@bogd Intersted to open a PR with the change as you already looked at the code?

**Comment by marian-craciunescu** [comment]
@ruflin  I will open a pull request  soon.I'm already working on it

**Comment by marian-craciunescu** [comment]
https://github.com/elastic/beats/pull/7213

**Comment by notorious-cow** [comment]
@marian-craciunescu Hi Marian.  Just wanted to see if there was any progress on this issue?  Thanks
