### ISSUE TITLE
Filebeat: File specific document type, fields, tags

### ISSUE THREAD

**Issue by oazabir** [elastic/beats#719]
We usually host multiple virtual directories in a web server. We need to configure one file beat instance to ship logs of all the virtual directories. However, logs for each file needs to have its own tags, document type and fields. Otherwise they have to be all in one format and gets dumped into one index. 

We should have a hierarchical format like this:

path:
 - /var/httpd/site1.log
   - input_type: log
   - document_type: apachecommon
   - fields: [ "system": "site1", "group": "apachelog" ]
   - tags: [ "site1" ]
   - index: site1-logstash-YY.MM.dd
 - /var/weblogic/site2.log
  - input_type: log
  - document_type: weblogic
   - fields: [ "system": "site2", "group": "weblogiclog" ]
   - tags: [ "site2" ]
   - index: site2-logstash-YY.MM.dd

**Comment by oazabir** [comment]
Or we could adopt a fluentd style model where each path just gets a tag. Then later part of the configuration file, we define the fields, index, document_type etc attributes for each tag. 

For ex, 

    path: 
       tag1: /var/httpd/site1.log
       tag2: /var/httpd/site2.log


    tags:
       tag1: 
              input_type: log
              document_type: apachecommon
              ...
       tag2:
              index: ....
              fields: ....

**Comment by ruflin** [comment]
You can have different fields per file if you use one prospector per file and define fields for each prospectors. We already have tags per beat. Are there things you cannot map with the fields in the prospector?

**Comment by oazabir** [comment]
Ah that should do. I did not notice the multiple prospector. 

Now just need different tags for different prospector.

**Comment by ruflin** [comment]
With tags you mean fields? Or is fields not sufficient and you need tags in addition?

**Comment by MiguelMoll** [comment]
Found this ticket while looking for a possible solution. Hopefully this is a good place. Would be great to have a list of "tags" along with key:value fields per prospector. Such as:

`tags: [ "site2", "thistag", "thattag"]`

**Comment by ruflin** [comment]
@MiguelMoll Can you briefly elaborate on how you use tags differently from fields. It is important for me to understand the use case.

**Comment by MiguelMoll** [comment]
Hard to answer exactly but going by how we've used `tags` in the past with logstash. It allows another avenue for filtering in Kibana.

If fields weren't strictly key:value where the value has to be a string also a list that would work too.

```
fields:
    level: debug
    tags: [ "site2", "thistag", "thattag"]
```

With `fields_under_root` and we'd be good to go.

**Comment by ruflin** [comment]
If you put tags under fields this should already be possible in the upcoming 1.1 thanks to @magnusbaeck  https://github.com/elastic/beats/pull/506

**Comment by MiguelMoll** [comment]
Excellent news! Hopefully I didn't derail this ticket too much.

**Comment by ruflin** [comment]
The question is if the above would also solve the problem from @oazabir ?

@MiguelMoll Feel free to try the snapshots for 1.1. Links can be found in this post: https://discuss.elastic.co/t/insufficient-throughput-from-filebeat/39564/4

**Comment by ruflin** [comment]
Here is the generic tag / fields implementation @andrewkroh did: https://github.com/elastic/beats/pull/1092 I think this resolves the above issues. Closing this issue, but happy to discuss further.

**Comment by sunilmchaudhari** [comment]
Hi,
How can I create indexes on the basis of fields created in FB?
fields:
    level: debug
    tags: [ "site2", "thistag", "thattag"]
   Application: "myapp"

So the index should be created as myap-YYYY-MM-DD

**Comment by ruflin** [comment]
@sunilmchaudhari This is currently only possible with Logstash. For questions please use https://discuss.elastic.co/c/beats/filebeat and not Github issues.
