### ISSUE TITLE
Refactor: Filebeat registry ACK handler

### ISSUE THREAD

**Issue by ph** [elastic/beats#7212]
The current ACKing strategy requires that all events have some kind of `file.State` and the ACK will be sent to the registry; the registry will make the final publish and will update the `wgEvents` counters. This makes sense when you have a file on disk, and you have to keep track of offsets.  But when your inputs are stateless like the TCP/UDP/Redis or even STDIN input it doesn't make sense.

I think we should allow the input to define a custom ack strategy. This will open Filebeat to other use cases.

**NOTE:** we currently have a work around for the STDIN we use `-` as the Source.

**Comment by urso** [comment]
We recently added support for inputs to register their custom ACK handler.
