### ISSUE TITLE
aggregate_coverage.py does not aggregate the coverage reports of the same tracked lines.

### ISSUE THREAD

**Issue by cyrilleverrier** [elastic/beats#722]
# Steps to reproduce:

```bash
cd ${GOPATH}/src/github.com/elastic/beats/filebeat
make system-tests
go tool cover -html=build/coverage/system.cov -o build/coverage/system.html
```
- open ./build/coverage/system.html
- select crawler.go in the dropdown menu

# Expected result
 crawler.go line 34: `return fmt.Errorf("No prospectors defined. You must have at least one prospector defined in the config file.")` is covered

In system.cov, there is only one occurrence of the line `github.com/elastic/beats/filebeat/crawler/crawler.go:33.33,35.3 1  <counter>`

# Actual result
 crawler.go line 34: `return fmt.Errorf("No prospectors defined. You must have at least one prospector defined in the config file.")` is not covered. Marked in red in the html file

In system.cov, there is many occurrences of the line `github.com/elastic/beats/filebeat/crawler/crawler.go:33.33,35.3 1 <counter>`
Many lines with counter to 0 and 1 occurrence with counter=1.

**Comment by ruflin** [comment]
If you run the above, the python script to do the "magic" is not called. If I run:

```
make system-tests
make coverage-reports
```

and have a look at full.html, the result is as expected. Can you confirm that?

**Comment by ruflin** [comment]
@cyrilleverrier I think I now understand based on #723 the direction you want to go and I like it. I think the report worked before, but instead of for example (10) it only reported (1).

**Comment by cyrilleverrier** [comment]
> have a look at full.html, the result is as expected. Can you confirm that?
Exactly the same behavior as mentioned in my first comment.

I generated ` full.html` with `make system-tests && make coverage-reports`
Before my patch, crawler.go got 86.1% of coverage
After my patch, crawler.go got 100% of coverage.

**Comment by ruflin** [comment]
We should definitively get your script in. As you mentioned, it is some "unexpected" that out of unit.cov, full.html is generated. The nicest part would be if we adapt it that for each coverage file, also a html report is generated. So if we have a unit.cov, we have as output unit.html and full.html, if we have unit.cov and system.cov, we have unit.html, system.html and the combined full.html @cyrilleverrier Would it make more sense to you like this?

**Comment by cyrilleverrier** [comment]
@ruflin Yes I agree with your last comment
