### ISSUE TITLE
Filebeat Exception - Cannot get text on a start object 

### ISSUE THREAD

**Issue by tarpanpathak** [elastic/beats#7237]
We are running `filebeat` through a Helm chart and without changes to the environment started seeing the following messages across all our environments: 

```
2018/05/30 00:22:19.159723 client.go:465: WARN Can not index event (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse [log]","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:225"}}
2018/05/30 00:22:19.159734 client.go:465: WARN Can not index event (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse [log]","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:301"}}
2018/05/30 00:22:19.159748 client.go:465: WARN Can not index event (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse [log]","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:260"}}
```
The Helm chart version is: `filebeat-0.1.2`

I've looked through some of the available documentation online but could not find the root cause or guidance on how to begin debugging this error. Any help/response is greatly appreciated. 

Let me know if more details are required to help you understand this issue.

**Comment by ruflin** [comment]
Could you please open a topic on discuss for this? https://discuss.elastic.co/c/beats/filebeat I don't think this is a bug but a problem in the helm chart.

On discuss please provide a link to the specific helm chart and share the full config it uses. Also share there if possible some events that filebeat outputs. My current guess is that it might be a conflict on the `log` field (object vs string).
