### ISSUE TITLE
Update Paketbeat to support Npcap native mode

### ISSUE THREAD

**Issue by Paqi** [elastic/beats#7257]
Currently, to use Paketbeat on a Windows OS, [users need to install Npcap in WinPcap API-compatible mode](https://www.elastic.co/guide/en/beats/packetbeat/current/faq.html#packetbeat-loopback-interface) (/winpcap_mode=yes), or Packetbeat will be unable to find the required DLLs.

This works, but there may be peformance benefits to supporting Npcap native mode. From @hsluoyz's [comment](https://github.com/elastic/beats/issues/4364#issuecomment-303096641) in this issue:

> I found that the current beats doesn't support the Npcap native mode (Npcap DLLs will be installed in System32\Npcap instead of System32). The impact is that the user has to install Npcap with WinPcap Compatible Mode option checked to use (aka winpcap_mode=yes). Otherwise, beats cannot find Npcap DLLs. And enabling this option will install another copy of Npcap driver that is compatible with WinPcap (like installing the DLLs to System32), which may affect the performance. So Npcap suggests all its downstream software to support Npcap native mode. Now software like Wireshark, Nmap, GNS3 has already supported Npcap native mode.

**Comment by aliciascott** [comment]
Please also update the [documentation](https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-installation.html) link to reflect the need to install Npcap in Winpcap compatible mode.

**Comment by dedemorton** [comment]
@aliciascott I've updated the link in the docs. Sorry I didn't see this sooner, but we use the `docs` label instead of `needs_docs`. It's an old label that should probably be removed, but I'll remember to check it going forward. The fix is in https://github.com/elastic/beats/pull/12481

**Comment by andrewkroh** [comment]
go-packet has been updated to support both npcap and winpcap. Packetbeat's vendored version of go-packet should be updated to pull in this change. Then I believe npcap's winpcap compatibility mode won't be needed.

https://github.com/google/gopacket/commit/774602d97db189d3d235c0c8d10184d772dda49c

**Comment by andrewkroh** [comment]
@efd6 This is now implemented, correct? What versions of Packetbeat is this true for?

**Comment by efd6** [comment]
Yes this is implemented. The earliest version to use the up-to-date gopacket and the npcap over winpcap is 8.1.

**Comment by efd6** [comment]
Adjusted label due to issues in the earlier 8.1 versions.
