### ISSUE TITLE
Clarify support (or lack of) for CentOS/RHEL 5.x

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#727]
Beats are written in Go, and [Go doesn't support](https://golang.org/doc/install) CentOS/RHEL 5.x.

However, "a some point during the RHEL5 release cycle support for vDSO vsyscalls was added to RedHat’s 2.6.18 kernel. However that point appears to differ by point release. For example, for RedHat 5, kernel 2.6.18-238.el5 does not work, whereas 2.6.18-238.19.1.el5 does. Running CentOS 5.9 with kernel 2.6.18.348.el5 does work." - http://dave.cheney.net/2013/06/18/how-to-install-go-1-1-on-centos-5

**Comment by dedemorton** [comment]
@monicasarbu Andrew suggested that the [support matrix](https://www.elastic.co/support/matrix) already covers this. Since you recently flagged the issue as P1, though, I wanted to check with you before closing the issue. Is the support matrix OK as it is, or do we need to say more?

**Comment by monicasarbu** [comment]
@dedemorton Sorry about that. I actually wanted to set P3 to this one, but I think we can close it now as you suggested.

**Comment by vvign** [comment]
Hi,
working in a large company means having to handle many unsupported OSs. To be able to think about re-launching commercial solutions that support os like windows 2003 and rehat 2 it would be interesting to be able to compile on metricbeats on these systems.
Best Regards.
