### ISSUE TITLE
Scrubbing logs for sensitive data

### ISSUE THREAD

**Issue by amvaidya** [elastic/beats#7273]
Our applications/systems are deployed in multiple security zones but we have a centralized log repository.
When logs are shipped from a higher security zone to the centralized repository (in a lower security zone), these logs need to be "scrubbed" to ensure that no sensitive (PII, PCI) data elements are being shipped.
We need the ability in Beats to be able to configure patterns for data elements that may be sensitive (SSN, Credit Card numbers etc). When Beats encounters these data elements in the log line, the data should be masked before it is shipped out.

**Comment by amvaidya** [comment]
@tsg

**Comment by ph** [comment]
@amvaidya How much structure theses patterns have? I wonder if you could use the [dissect](https://www.elastic.co/guide/en/beats/filebeat/master/dissect.html) processor and drop field to remove the sensitive information.

One way to do this would be to add either a grok processor (regular expression) but we were always on the fence to add this for performance reason, but maybe we could provide an optimized parser for familiar pieces of information.

**NOTE**: Dissect is only available in master.
