### ISSUE TITLE
IIS data type filebeat 6.3

### ISSUE THREAD

**Issue by stestaz** [elastic/beats#7275]
Hi,
I'm trying to put iis logs in kibana using filebeat, I've seen that the stable version 6.2 still not have this implemented so I've compiled the new 6.3 version.
In this version de module is present but the data are not correctly converted, for example there is no location (only lat and lon in 2 separated fields) anche the iis.access.request_time_ms is not a float but a keyword.
So i've compiled the 7.0 alpha version and there everything is working, but I think it will be good to fix it in the 6.3 isn't it?

**Comment by ph** [comment]
I will take a look, we might be missing a commit in 6.3

**Comment by ph** [comment]
I've diffed both branches, and there are only minor changes in the files between master and 6.3 and the changes are related to refactoring changes.

The problems you are describing for _request_time_ms_ and _location_ looks more related to a template/mapping issue. By default, our template is versioned and will target specific indices that contain the version in the name.

Can you check your template and their mapping? You should see a template  for 6.3.0 and 6.2.x?

```
http://localhost:9200/_template?pretty
```

Also look at the mapping for the indices you are querying.
```
http://localhost:9200/your_indices/_mapping/doc
```

You should mapping related to IIS fields.

**Comment by michalpristas** [comment]
closing 6.3 not supported now
