### ISSUE TITLE
[Packetbeat] Corrupted messages when using PGSQL protocol

### ISSUE THREAD

**Issue by liqw33d** [elastic/beats#7277]
Hi,
There seem to be a bug when SQL statements contain character `;` which is not supposed to be a delimiter.
- Version: 6.2.4
- Operating System: Debian Jessie 
- Discuss Forum URL: https://discuss.elastic.co/t/corrupted-messages-when-using-pgsql-protocol/134051
- Steps to Reproduce: `select 1, ';';` gets logged as: `select 1, '` so part with `;'` was lost.

**Comment by dplavcic** [comment]
Hi liqw33d,

.he same thing is happening on latest master. I'll take look at this issue.
