### ISSUE TITLE
add filebeat 1.1 to apt/yup repo

### ISSUE THREAD

**Issue by annisele** [elastic/beats#729]
I use the filebeat yum repo to install filebeat. Noticed that filebeat is at version 1.1 but it doesnt look like the yum repo has been updated. Can we get v1.1 there soon?

**Comment by andrewkroh** [comment]
When 1.1 is released it will published to the yum repo. The latest version is 1.0.1 as reflected [here]( https://www.elastic.co/downloads/beats/filebeat). I think 1.1 is being released next week.

**Comment by annisele** [comment]
thanks!
