### ISSUE TITLE
[Heartbeat] Add ICMP packet loss percentage

### ISSUE THREAD

**Issue by dearco** [elastic/beats#7291]
There is only icmp_rtt_us ,the RTT time ,adding a "packet loss percent" would be wonderful....

**Comment by ruflin** [comment]
Over which time period would this packet loss percent be? I think we could calculate this in Kibana based on a count of `monitor.status="up"` and `monitor.status="down"` and then use a script field.

This would make it always correct for the time period the user looks at in KB.

**Comment by florian-asche** [comment]
Sad to see that this is still not resolved. I mean should i switch back to nagios check_icmp?
