### ISSUE TITLE
Clock drift on Windows Server 2008 R2 when running latest version of winlogbeat (or any version > 6.1.0)

### ISSUE THREAD

**Issue by drstokes** [elastic/beats#7308]
- Version: 6.24 or (6.10+)
- Operating System: Windows Server 2008 R2 
- Discuss Forum URL:  https://discuss.elastic.co/t/winlogbeat-speeding-up-clocks-on-windows-servers-by-1-second-every-minute/135175/4
- Steps to Reproduce: Run winlogbeat 6.10 or above and watch time increase by 1+ seconds per minute

Looks to be an issue with go 1.9.  A custom build with Go 1.8.7 works without any clock drift.  Would it be possible to get an official version that doesn't have the issue

**Comment by ruflin** [comment]
For reference from the initial discuss topic for readers: This is a golang issue that describes a very similar issue: https://github.com/golang/go/issues/24489

**Comment by alpharaouf** [comment]
Where can i find this custom build and how can i build my custom any tuto

**Comment by adriansr** [comment]
@alpharaouf see our [Contribution Guide](https://www.elastic.co/guide/en/beats/devguide/current/beats-contributing.html#setting-up-dev-environment) for information on how to build your own beats.

**Comment by ruflin** [comment]
For a snapshot build from master see https://beats-package-snapshots.s3.amazonaws.com/index.html?prefix=winlogbeat/

**Comment by kvch** [comment]
This issue is for an old version of beats, I suggest to try out the latest version of beats. If this is still a problem in the newly released version feel free to reopen this issue. Thanks.
