### ISSUE TITLE
Allow to add condition that matches all events in autodiscover templates

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#7310]
Currently there is no explicit way to define a condition that matches all events in autodiscover templates, we could make that the empty condition matches all, or and some kind of `condition: true`.

**Comment by ruflin** [comment]
What about `condition: *`?

**Comment by exekias** [comment]
I would say no condition field should match everything, the same way processors without a `when` clause are always applied

**Comment by jsoriano** [comment]
Fixed by #9029
