### ISSUE TITLE
Fix glide version of golang.org/x/text

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#734]
See https://github.com/elastic/beats/commit/a69e7bfb4ffe7b071cef592a00e24389987e51f3#commitcomment-15470231

**Comment by andrewkroh** [comment]
Also, `github.com/StackExchange/wmi` should be:

```
- package: github.com/StackExchange/wmi
  version: f3e2bae1e0cb5aef83e319133eabfee30013a4a5
```

Apparently I cannot copy paste. :astonished:
