### ISSUE TITLE
Create add_fields processor

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#7350]
Currently fields are added through the following config options:

```
fields:
  foo: bar
field_under_root: true
```
To bring this more in line with our other processor I suggest we introduce an `add_fields` processor. This should also allow more features like defining a target prefix for the fields or enable / disable overwriting fields.

Follow up from https://github.com/elastic/beats/pull/7309#discussion_r194993059

**Comment by urso** [comment]
add_fields processor will be in 7.0
