### ISSUE TITLE
Trouble with 'make import' in custom metricset

### ISSUE THREAD

**Issue by crayzeigh** [elastic/beats#7366]
Running into python errors when trying to build out a custom metricset, after some tracking this appears to be linked to changes from [this commit](https://github.com/elastic/beats/commit/a26cd254903330489dcd3babb0a608b9839b0159) that generalized the `generate_imports.py` script for use with beats other than metricbeat. 

Error:
```
Traceback (most recent call last):
  File "./vendor/github.com/elastic/beats/script/generate_imports.py", line 7, in <module>
    from generate_imports_helper import comment, get_importable_lines
ImportError: No module named generate_imports_helper
```

Creating a symlink in  `${GOPATH}/github.com/crayzeigh/testbeat03/vendor/github.com/elastic/beats/script` to `${GOPATH}/github.com/crayzeigh/testbeat03/vendor/github.com/elastic/beats/metricbeat/scripts/generate_imports_helper.py` functions as a workaround.

Issue created by request from @kvch

**Comment by ruflin** [comment]
@crayzeigh Could you try again to see if this fixes your issue?

**Comment by crayzeigh** [comment]
Confirmed this works. @ruflin
