### ISSUE TITLE
Beats on SUSE Linux

### ISSUE THREAD

**Issue by inqueue** [elastic/beats#737]
There have been a few requests to support Beats on SUSE Linux, specifically Filebeat, Packetbeat and Topbeat. It appears that at least Filebeat and Topbeat will run on SUSE, but the init script provided in the RPM package does not work for SUSE; i.e., SUSE 10/11. Systemd may work for SUSE 12, but it is currently untested.

**Comment by andrewkroh** [comment]
One of the requests was from Discuss: https://discuss.elastic.co/t/beats-on-suse-10-11/34654

**Comment by jerrac** [comment]
Can you add SLES/OES to this? Or create a new issue for it, since they have diverged from OpenSUSE. According to my co-worker. https://discuss.elastic.co/t/what-kind-of-init-script-support-will-we-get/32810/3?u=jerrac

I know it may be a while before anything can be done, but it'd be nice to have an official place to track it. Or to know for sure that it won't happen. 

Thanks. :smile:

**Comment by salyh** [comment]
When will SLES 11/12 be officially supported by beats (see https://www.elastic.co/support/matrix)? Is the lack of official support only due to packaging or are there issues on SLES with go runtime and/or linux kernel.

**Comment by kayatate** [comment]
My SUSE ISV team has another request from a large customer for Beats 1.x support on SUSE Linux Enterprise 12. SLES 11 is also still supported too and would be helpful. If you want to use _systemd_, you will want to move to SLES 12.

**Comment by gitmopp** [comment]
For SLES11 I found this start script here [https://build.opensuse.org/package/view_file/home:TNeuburger/filebeat/filebeat.init?expand=1](url)
I fixed a small typo and changed the path:

```
#!/bin/sh
# Init script for filebeat
# Created by Thomas Neuburger
# Implemented based on SLE11_3 /etc/init.d/skeleton file
#
### BEGIN INIT INFO
# Provides:          filebeat
# Required-Start:    $syslog $remote_fs
# Should-Start:      $time ypbind smtp
# Required-Stop:     $syslog $remote_fs
# Should-Stop:       ypbind smtp
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: Starts Filebeat as Daemon
# Description:       Starts Filebeat as Daemon (Ships logs to elasticsearch or logstash)
### END INIT INFO

# set params
FILEBEAT_CONF=/etc/filebeat/filebeat.yml

# Check for missing binaries (stale symlinks should not happen)
# Note: Special treatment of stop for LSB conformance
FILEBEAT_BIN=/usr/bin/filebeat.sh
test -x $FILEBEAT_BIN || { echo "$FILEBEAT_BIN not installed";
        if [ "$1" = "stop" ]; then exit 0;
        else exit 5; fi; }


# Source LSB init functions
# providing start_daemon, killproc, pidofproc,
# log_success_msg, log_failure_msg and log_warning_msg.
# This is currently not used by UnitedLinux based distributions and
# not needed for init scripts for UnitedLinux only. If it is used,
# the functions from rc.status should not be sourced or used.
#. /lib/lsb/init-functions

# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     be verbose in local rc status and clear it afterwards
#      rc_status -v -r  ditto and clear both the local and overall rc status
#      rc_status -s     display "skipped" and exit with status 3
#      rc_status -u     display "unused" and exit with status 3
#      rc_failed        set local and overall rc status to failed
#      rc_failed <num>  set local and overall rc status to <num>
#      rc_reset         clear both the local and overall rc status
#      rc_exit          exit appropriate to overall rc status
#      rc_active        checks whether a service is activated by symlinks
. /etc/rc.status

# Reset status of this service
rc_reset

# Return values acc. to LSB for all commands but status:
# 0          - success
# 1       - generic or unspecified error
# 2       - invalid or excess argument(s)
# 3       - unimplemented feature (e.g. "reload")
# 4       - user had insufficient privileges
# 5       - program is not installed
# 6       - program is not configured
# 7       - program is not running
# 8--199  - reserved (8--99 LSB, 100--149 distrib, 150--199 appl)
#
# Note that starting an already running service, stopping
# or restarting a not-running service as well as the restart
# with force-reload (in case signaling is not supported) are
# considered a success.

case "$1" in
    start)
        echo -n "Starting filebeat "
        ## Start daemon with startproc(8). If this fails
        ## the return value is set appropriately by startproc.
        /sbin/startproc $FILEBEAT_BIN -c $FILEBEAT_CONF

        # Remember status and be verbose
        rc_status -v
        ;;
    stop)
        echo -n "Shutting down filebeat "
        ## Stop daemon with killproc(8) and if this fails
        ## killproc sets the return value according to LSB.

        /sbin/killproc -TERM $FILEBEAT_BIN

        # Remember status and be verbose
        rc_status -v
        ;;
    restart)
        ## Stop the service and regardless of whether it was
        ## running or not, start it again.
        $0 stop
        $0 start

        # Remember status and be quiet
        rc_status
        ;;
    reload)
        echo -n "Reload service filebeat "
        ## filebeat does not support reload:
        rc_failed 3
        rc_status -v
        ;;
    status)
        echo -n "Checking for service filebeat "
        ## Check status with checkproc(8), if process is running
        ## checkproc will return with exit status 0.

        # Return value is slightly different for the status command:
        # 0 - service up and running
        # 1 - service dead, but /var/run/  pid  file exists
        # 2 - service dead, but /var/lock/ lock file exists
        # 3 - service not running (unused)
        # 4 - service status unknown :-(
        # 5--199 reserved (5--99 LSB, 100--149 distro, 150--199 appl.)

        # NOTE: checkproc returns LSB compliant status values.
        /sbin/checkproc $FILEBEAT_BIN
        # NOTE: rc_status knows that we called this init script with
        # "status" option and adapts its messages accordingly.
        rc_status -v
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|reload}"
        exit 1
        ;;
esac
rc_exit
```

**Comment by FlorianHeigl** [comment]
This init script looks good, is there any other problem why this couldn't be available?

**Comment by ruflin** [comment]
@FlorianHeigl We didn't test the above script on our side. If we add such a script to our packages we want to make sure tested it in detail as we also have to support it from then on. If it work for you, feel free to use it.

**Comment by FlorianHeigl** [comment]
So, um.
You say you need to test it well and that you didn't test it.
This doesn't really help at all.

Do you have considered to have it on your well testing schedule for some point in the, say, next 2 years or should just everyone work it out without you?

If yes, can this be indicated in docs better?
It's not like we *need* the project to get an init script, but funnily enough the init script is the only reason why docs advise to use a tarball on SLES11.

Florian

**Comment by ruflin** [comment]
@FlorianHeigl To which point of the docs are you referring to? The support matrix?

**Comment by FlorianHeigl** [comment]
This was an error on my end.
Elasticsearch has similar issues with a broken init script and there they advice to use the tarball.

So this was not in the filebeat doc.
Instead, https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation.html has no mention of SLES at all. Just because of this? :(

**Comment by ruflin** [comment]
If you look at the support matrix and check out the ** for SLES, you will see some additional notes: https://www.elastic.co/support/matrix As you see the there is quite a list of systems we officially support. We try to have automated tests on all these systems, so adding and additional system is involves quite a bit of work and also has consequences from a support perspective. Obviously we try to add more systems over time but there is no guaranteed timeline when this will happen.

**Comment by tsg** [comment]
An update on this one, I tried metricbeat RPMs on [this SLES12 VM](https://app.vagrantup.com/elastic/boxes/sles-12-x86_64) and things seemed to be working fine. It seems to me like SLES12 might "just work", in which case we only need to add the VM to beats-tester in order to claim support.

Opensuse is already tested regularly by beats-tester.

SLES11 still has the issue that we need to provide a specialised init script.

**Comment by kayatate** [comment]
Hi again,
I have another customer who wants to run Beats on SLES 12. Could we get that one set up anyway, even if 11 is not completely fixed?

**Comment by andrewkroh** [comment]
Beats should be working fine with SLES 12. We added some regular testing in https://github.com/elastic/beats-tester/pull/84.

**Comment by andrewkroh** [comment]
We will be added SLES 12 to support matrix in the near future. Stay tuned.

**Comment by kayatate** [comment]
I see it! Thanks so much! Our mutual customer will be very pleased.

**Comment by brandonmensing** [comment]
Thanks @kayatate, closing this out!

**Comment by asharafshahi** [comment]
Can someone explain how to use the snippet shown by gitmopp above?
