### ISSUE TITLE
Syslog inputs should correctly parses relayed syslog events.

### ISSUE THREAD

**Issue by ph** [elastic/beats#7378]
Currently, the Syslog parser will not correctly extract the information from the string when the Syslog event was relayed from a collector; this setup is common with appliance generating Syslog event like a Cisco switch.

Example message:
```
<190>2018-06-19 02:13:38 Local7.Info HOST-1111-PQWER-SWT1 2018-06-19T02:13:38.635322-07:00 HOST-1111-PQWER-SWT1 Acl: %ACL-6-IPACCESS: list Isolation-4E Vlan100 denied tcp 10.10.10.10(56393) -> 13.14.14.53(443)
```

Generated events:
```
{
  "@timestamp": "2018-06-19T06:13:38.000Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "doc",
    "version": "7.0.0-alpha1",
    "truncated": false
  },
  "event": {
    "severity": 6
  },
  "host": {
    "name": "sashimi"
  },
  "source": "127.0.0.1:53198",
  "hostname": "Local7.Info",
  "syslog": {
    "priority": 190,
    "severity_label": "Informational",
    "facility": 23,
    "facility_label": "local7"
  },
  "process": {},
  "message": "HOST-1111-PQWER-SWT1 2018-06-19T02:13:38.635322-07:00 HOST-1111-PQWER-SWT1 Acl: %ACL-6-IPACCESS: list Isolation-4E Vlan100 denied tcp 10.10.10.10(56393) -\u003e 13.14.14.53(443)",
  "prospector": {
    "type": "syslog"
  },
  "input": {
    "type": "syslog"
  },
  "beat": {
    "name": "sashimi",
    "hostname": "sashimi",
    "version": "7.0.0-alpha1"
  }
}

```

In this situation, the important information are contained inside the "message" key.

```
2018-06-19T02:13:38.635322-07:00 HOST-1111-PQWER-SWT1 Acl: %ACL-6-IPACCESS: list Isolation-4E Vlan100 denied tcp 10.10.10.10(56393) -\u003e 13.14.14.53(443)
```

**Comment by ph** [comment]
In the case of syslog-ng, I think we can remove the details using the 

```
Enable the keep-hostname() and disable the chain-hostnames() options. (For details on how these options work, see Section chain-hostnames().)
```

doc: https://syslog-ng.com/documents/html/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/procedure-configuring-syslog-ng-relays.html

**Comment by kvch** [comment]
What do you mean by details? Additions added by the relay?

**Comment by ph** [comment]
@kvch  thanks this is a bummer, it makes the parsing a lot more complex in the case of relay, I will mark this as a bug and will work on fixing it.  I would have like a way to just relay the original information without changing anything.

**Comment by faec** [comment]
Looks like this has been stalled for four years (with other major changes to syslog processing in the meantime), closing.
