### ISSUE TITLE
Add recommendation to avoid using symlinks in filebeat documentation

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#7386]
It sounds like our general recommendation when dealing with file rotation is to avoid using symlinks.  Instead of using a symlink in the prospector path definition, we recommend pointing the harvester to the original file(s) and with the path pattern match the file data is written to and all its rotated files. 

It will be helpful to add a note [here](https://www.elastic.co/guide/en/beats/filebeat/6.2/configuration-filebeat-options.html) upfront, esp. since later on the same page, we provide an option for the harvester to handle [symlinks](https://www.elastic.co/guide/en/beats/filebeat/6.2/configuration-filebeat-options.html#_literal_symlinks_literal) - which is disabled by default.

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/beats/pull/7950
