### ISSUE TITLE
Force reload of ingest pipeline

### ISSUE THREAD

**Issue by danielkasen** [elastic/beats#7394]
Currently if you ever want to update an ingest pipeline via FB you have to delete it first then restart the FB agent. Is there any way to just have FB update the pipeline without doing this? Like a filebeat command or anything that can force the update?

**Comment by danielkasen** [comment]
Looks like this option was added in 6.3 but can't seem to find the document describing it: filebeat.overwrite_pipelines: true

**Comment by kvch** [comment]
You can find a short documentation in the reference config file:
```
# By default Ingest pipelines are not updated if a pipeline with the same ID
# already exists. If this option is enabled Filebeat overwrites pipelines
# everytime a new Elasticsearch connection is established.
#filebeat.overwrite_pipelines: false
```

Alternatively, you could use `filebeat setup --piplines` which updates Ingest pipelines of enabled modules.

**Comment by kvch** [comment]
But next time please ask questions on our Discuss forums. GH Issues are reserved for enhancement requests and bug reports.

https://discuss.elastic.co/
