### ISSUE TITLE
filesystem.ignore_types not filtering unwanted filesystems/mounts

### ISSUE THREAD

**Issue by sgreszcz** [elastic/beats#7395]
I'm trying to use the filesystem metric beats module and looking to filter out unwanted filesystems/mounts on my Ubuntu servers as I'm only interested in:

/dev/mapper/cdc--alln--001--vg-root mounted on /
/dev/sda1 mounted on /boot
/dev/sdb1 mounted on /data

- Version: 6.3
- Operating System: Ubuntu 16.04 LTS
- Discuss Forum URL: https://discuss.elastic.co/t/configuring-system-filesystem-to-show-useful-mount-stats/136914
- Steps to Reproduce: 

Attempted to use both 

```
processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
```

and

`filesystem.ignore_types: [sysfs, proc, devpts, securityfs, cgroup, systemd-1, hugetlbfs, mqueue, fusectl, lxcfs, overlay, shm, nsfs, binfmt_misc, tracefs, udev, tmpfs]`

to get rid of unwanted filesystems/mounts but they still keep coming through and the mount parts are quite weird too.  I don't know where metricbeats system.filesystem is getting those from.  

Finally Kibana is not showing any of the system.filesystem fields under "discover" in the metricbeat-* index even though they show up when creating a kibana filter.

<img width="612" alt="screen shot 2018-06-21 at 21 16 03" src="https://user-images.githubusercontent.com/22910494/41743341-62c946a4-7598-11e8-87b9-d808852f6e13.png">
<img width="1636" alt="screen shot 2018-06-21 at 21 12 48" src="https://user-images.githubusercontent.com/22910494/41743342-62e5c004-7598-11e8-9928-ed77bdea04a0.png">
<img width="1634" alt="screen shot 2018-06-21 at 21 12 12" src="https://user-images.githubusercontent.com/22910494/41743343-63033972-7598-11e8-9a14-25d82b4b3e8c.png">
<img width="1634" alt="screen shot 2018-06-21 at 21 11 42" src="https://user-images.githubusercontent.com/22910494/41743344-63213260-7598-11e8-8fa6-30536edcb2d2.png">

**Comment by jsoriano** [comment]
Hi @sgreszcz, thanks for posting your question, but lets continue the discussion in the discuss post.
