### ISSUE TITLE
Document regexp support in Beats

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#740]
Opening a separate issue to track the issue  @ruflin brought up in #597 : "currently the documentation for Regexp is not clear. This includes exclude / include line as they use the same regexp. We should separately document the regexp which can be used or link to a good documentation."

It would be good to link to existing doc on regexp, if possible, rather than trying to document it ourselves.

**Comment by dedemorton** [comment]
@urso Adding you to this thread  because I'm hoping you can point me to some resources that clarify Beats support for regular expressions plus something that explains how the YAML parser affects escaping.

**Comment by urso** [comment]
Documentation for regex support in go is unfortunately quite lacking or much too technical.

[1. re2 implementation details](https://swtch.com/~rsc/regexp/regexp2.html#posix) 
[2. re2 syntax](https://github.com/google/re2/wiki/Syntax)
[3. go regex tutorial](https://github.com/StefanSchroeder/Golang-Regex-Tutorial/blob/master/01-chapter2.markdown)

playing with regexes I did find support between Compile and CompilePOSIX to be kinda inconsistent to the Syntax document. So I create a small [test compiling different regex patterns](http://play.golang.org/p/6eJMz4QzCv). Currently we're using the Re2POSIX implementation which seems to be lacking (no support for case-sensitivity flags, no \s pattern).

Output:

    Re2	Re2POSIX	pattern			description
    true	true	x			single character
    true	true	.			any character
    true	true	[xyz]			character class
    true	true	[^xyz]			neg character class
    true	false	\d			perl character class
    true	false	\D			neg perl character class
    true	true	[[:alpha:]]			ASCII character class
    true	true	[[:^alpha:]]			neg ASCII character class
    true	false	\pN			unicode character class
    true	false	\p{Greek}			unicode character class
    true	false	\PN			neg unicode character class
    true	false	\P{Greek}			neg unicode character class
    true	true	ab			concatenation
    true	true	a|b			or composition
    true	true	x*			zero or more
    true	true	x+			one or more
    true	true	x?			zero or one
    true	true	x{1,3}			n or n+1 or ... or m x, prefer more
    true	true	x{2,}			n or more x, prefer more
    true	true	x{4}			exactly n
    true	true	x*?			zero or more x (prefer fewer)
    true	true	x+?			one or more x (prefer fewer)
    true	true	x??			zero or one (prefer zero)
    true	true	x{3,5}?			n or n+1 or ... or m x, prefer fewer
    true	true	x{4,}?			n or more x, prefer fewer
    true	true	x{4}?			exactly n x
    true	true	(re)			numbered capturing group (submatch)
    true	false	(?P<name>re)			named & numbered capturing group (submatch)
    true	false	(?:re)			non-capturing group
    true	false	(?i)abc			set flags within current group; non-capturing
    true	false	(?i:re)			set flags during re; non-capturing
    true	false	(?i)PaTTeRN			case-insensitive (default false)
    true	false	(?m)multiline			multi-line mode: ^ and $ match begin/end line in addition to begin/end text (default false)
    true	false	(?s)pattern.			let . match \n (default false)
    true	false	(?U)x*abc			ungreedy: swap meaning of x* and x*?, x+ and x+?, etc (default false)
    true	true	^beginning			at beginning of text or line (m=true)
    true	true	end of line$			at end of text (like \z not \Z) or line (m=true)
    true	false	\Aabc			at beginning of text
    true	false	\bword			at ASCII word boundary (\w on one side and \W, \A, or \z on the other)
    true	false	\Bpattern			not at ASCII word boundary
    true	false	end of text\z			at end of text
    true	true	\a			bell (≡ \007)
    true	true	\f			form feed (≡ \014)
    true	true	\t			horizontal tab (≡ \011)
    true	true	\n			newline (≡ \012)
    true	true	\r			carriage return (≡ \015)
    true	true	\v			vertical tab character (≡ \013)
    true	true	\*			literal *, for any punctuation character *
    true	true	\123			octal character code (up to three digits)
    true	true	\x7F			hex character code (exactly two digits)
    true	true	\x{10FFFF}			hex character code
    false	false	\C			match a single byte even in UTF-8 mode
    true	false	\Q...\E			literal text ... even if ... has punctuation
    true	false	\d			digits (≡ [0-9])
    true	false	\D			not digits (≡ [^0-9])
    true	false	\s			whitespace (≡ [\t\n\f\r ])
    true	false	\S			not whitespace (≡ [^\t\n\f\r ])
    true	false	\w			word characters (≡ [0-9A-Za-z_])
    true	false	\W			not word characters (≡ [^0-9A-Za-z_])
    true	true	[[:alnum:]]			alphanumeric (≡ [0-9A-Za-z])
    true	true	[[:alpha:]]			alphabetic (≡ [A-Za-z])
    true	true	[[:ascii:]]			ASCII (≡ [\x00-\x7F])
    true	true	[[:blank:]]			blank (≡ [\t ])
    true	true	[[:cntrl:]]			control (≡ [\x00-\x1F\x7F])
    true	true	[[:digit:]]			digits (≡ [0-9])
    true	true	[[:graph:]]			#$%&'()*+,\-./:;<=>?@[\\\]^_`{|}~])
    true	true	[[:lower:]]			lower case (≡ [a-z])
    true	true	[[:print:]]			printable (≡ [ -~] == [ [:graph:]])
    true	true	[[:punct:]]			punctuation (≡ [!-/:-@[-`{-~])
    true	true	[[:space:]]			whitespace (≡ [\t\n\v\f\r ])
    true	true	[[:upper:]]			upper case (≡ [A-Z])
    true	true	[[:word:]]			word characters (≡ [0-9A-Za-z_])
    true	true	[[:xdigit:]]			hex digit (≡ [0-9A-Fa-f])

**Comment by urso** [comment]
Yaml supports like 5 ways to do strings. Most important are unquoted, quoted and double quoted. Depending on style used, escaping rules might differ, plus some kind of strings (e.g. bool, true) must be quoted to differentiated them from other types.

I didn't find a good readable YAML reference. Best I could find is (in the docs of symfony - a php web development framework)[http://symfony.com/doc/current/components/yaml/yaml_format.html]. Depending on yaml implementation/library mileage may vary ;)

**Comment by xifanyan** [comment]
took me hours to find this, it has to be documented somewhere more obvious.

**Comment by dedemorton** [comment]
@xifanyan We are working on improving the documentation about regular expression support and will add additional content in the future.  However, I'm wondering if you had trouble finding the following topic in the documentation: 

https://www.elastic.co/guide/en/beats/filebeat/current/regexp-support.html

If you go to the main [docs page](https://www.elastic.co/guide/index.html) and search for regular expressions (click the magnifying glass icon), the topic comes up as the first hit. I'm curious to know where you ran into problems so that I can help other users find the content more easily.

**Comment by dedemorton** [comment]
Closing this because all the doc changes related to regexp support are complete.
