### ISSUE TITLE
tcpdump.org unavailable prevents packaging

### ISSUE THREAD

**Issue by graphaelli** [elastic/beats#7402]
libpcap is fetched during packaging: https://github.com/elastic/beats/blob/35a7882f69d6daf9ab72f36c6509a00aaa2904d0/dev-tools/packer/docker/xgo-image-deb7/beats-builder/Dockerfile#L16

WIth tcpdump.org down, as it is currently, we're unable to build packages.  Two thoughts:
* Is the release on https://github.com/the-tcpdump-group/libpcap/releases trustworthy?  It has a different sha1sum but I expect just metadata differences (will compare contents when tcpdump.org returns to service)
* Can this be hosted within the elastic infrastructure to eliminate this external dependency?

**Comment by ruflin** [comment]
Currently @andrewkroh is reworking our packaging: https://github.com/elastic/beats/pull/7388 Not sure if it will have an affect on the above but he is probably the best to comment.

**Comment by andrewkroh** [comment]
I saw some of that flakyness on ~Friday. In #7388 I have mirrored the libpcap source to S3. 

And also libpcap will no longer be included in the [base images](https://github.com/elastic/golang-crossbuild) used for cross-compiling since it's not a common dependency needed by Beats.
