### ISSUE TITLE
Help Help ,thank you

### ISSUE THREAD

**Issue by boxrice007** [elastic/beats#7433]
I am setup autodiscover is kubernetes.When start filebeat,it;s log hints KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICEPORT not defined.
![default](https://user-images.githubusercontent.com/13794560/41968936-7471fa00-7a38-11e8-952b-76419cef1aaf.png)
![default](https://user-images.githubusercontent.com/13794560/41968947-80647202-7a38-11e8-8626-4f66613ba068.png)

Please Please  Please  Thank you

**Comment by exekias** [comment]
Hi @boxrice007,

Kubernetes autodiscover provider expects to run inside kubernetes by default, as it needs access to the logs from the filesystem. Have a look to our docs on how to run Filebeat on Kubernetes: https://www.elastic.co/guide/en/beats/filebeat/6.3/running-on-kubernetes.html

I've also opened a pull request to document the parameters to change the default behavior, but probably you don't want to do that: https://github.com/elastic/beats/pull/7436

Please refer further questions to our forum, we use Github issues for enhancement requests and bug reports: https://discuss.elastic.co/c/beats

Best regards
