### ISSUE TITLE
Filebeat postgresql doesn't like numerical value for the timezone offset.

### ISSUE THREAD

**Issue by ph** [elastic/beats#7438]
Reported on discuss at https://discuss.elastic.co/t/postgres-logs-not-properly-parsed-by-filebeat/137371/3

---

The following log statement created by a default postgresql 9.4 will produce a grok parser error.

```
2018-06-27 18:26:29 +09 [7484-2] LOG: MultiXact member wraparound protections are now enabled
```

This is because of the regular expression use the WORD pattern and it doesn't work with + since we are expecting boundaries around the text value.
```
WORD \b\w+\b
```

**Comment by alvarolobato** [comment]
Probably related to https://github.com/elastic/beats/issues/7439 needs investigation.

**Comment by jsoriano** [comment]
I think we need more information to solve this issue. According to PostgreSQL documentation, timezone can only take the value of one of the timezones in the `timezonesets` files included in the PostgreSQL distribution. Looking at this file in PostgreSQL (checked in 9.6 and 12.6), only timezone abbreviations (such as `CET`, or `JST`) are available, all of them match the current `WORD` pattern.
I tried to set numeric timezones (`+0900`, `+09:00`, `UTC+09`) and the server fails to start. Or with some combinations (like `+09`) it starts, but showing an empty timezone in the logs.

So I wonder how this log was generated.

In the original discuss issue it is also mentioned that dates were logged as in 1970 (Unix epoch), and there were other oddities with host names, so I wonder if there was something weird in this machine, or the log patterns (`log_line_prefix`) were customized to something not very usual.

**Comment by jsoriano** [comment]
Closing, please reopen if this happens again and/or there is more information about the settings used to generate these logs.
