### ISSUE TITLE
Filebeat postgresql ingest pipeline doesn't timezone to parse the extracted dat`e

### ISSUE THREAD

**Issue by ph** [elastic/beats#7439]
The current ingest pipeline correctly extract both the timestamp and the timezone but we don't use the extracted timezone to parse the date.

But I am not sure if we can use the timezone as is because the date parser seems to accept the 'America/Toronto' format as the timezone description and the extracted data can be the following:

1.  Numerical offset (+09,+0900, +09:00)
2. Can be a word for the timezone (CEST)

**Comment by andresrc** [comment]
@jsoriano there were several fixes for timezone handling, can this be already solved?

**Comment by jsoriano** [comment]
This should be fixed by #12338.
