### ISSUE TITLE
geolocation support for IPv6 addresses

### ISSUE THREAD

**Issue by cleesmith** [elastic/beats#745]
Libbeat provides the **GetLocationByIP** lookup method via [go-libGeoIP](https://github.com/nranchev/go-libGeoIP). However, this only provides geolocation information for IPv4 addresses via [GeoIP Legacy databases](http://dev.maxmind.com/geoip/).

Instead, is it possible to use [maxminddb-golang](https://github.com/oschwald/maxminddb-golang) for both IPv4 and **IPv6** address lookups?  This package uses the GeoLite2 and GeoIP2 databases. However, it does **not** load the entire database into memory, rather it uses **mmap** to access the database file. Perhaps, both approaches are similar with the data actually _living in memory_, but my only limited experience with memory mapped files is Kafka.

Would using maxminddb-golang cause performance or other issues ?

Thanks.

**Comment by leehinman** [comment]
GeoIP processor can now do IPv4 & IPv6
