### ISSUE TITLE
Filebeat Auditd fields.yml implies that Geo-IP not required

### ISSUE THREAD

**Issue by brandonmensing** [elastic/beats#7477]
The description of the geoip field in the auditd module of Filebeat indicates:
https://github.com/elastic/beats/blob/v5.6.5/filebeat/module/auditd/log/_meta/fields.yml#L57-L58

`Only present if the GeoIP Elasticsearch plugin is available used.`

This should be removed as the plugin is considered a prereq:
https://www.elastic.co/guide/en/beats/filebeat/6.3/filebeat-modules-quickstart.html#_prerequisites

For confirmed bugs, please report:
- Version: 5.x, 6.x
- Operating System: All
- Discuss Forum URL:  - 
- Steps to Reproduce: This is essentially a doc/description mismatch. Confusing for users.

**Comment by roncohen** [comment]
thanks @brandonmensing. The GeoIP plugin is now enabled as a processor by default. We should update the docs accordingly.
