### ISSUE TITLE
"make python-env" fails on current Homebrew

### ISSUE THREAD

**Issue by beniwohli** [elastic/beats#7489]
Since some time, `python` defaults to Python 3 when using Homebrew on OSX. Python 3 is also the default on Ubuntu 18.04.

`make python-env` defaults to use `python`, and when that points to a Python 3 binary, promptly fails, trying to install `functools32`:

https://github.com/elastic/beats/blob/a8da1868564c9851a8f23d35e563a09cab2df2e7/libbeat/tests/system/requirements.txt#L13

    Collecting functools32==3.2.3.post2 (from -r ./_beats/libbeat/tests/system/requirements.txt (line 13))
    Using cached https://files.pythonhosted.org/packages/c5/60/6ac26ad05857c601308d8fb9e87fa36d0ebf889423f47c3502ef034365db/functools32-3.2.3-2.tar.gz
        Complete output from command python setup.py egg_info:
        This backport is for Python 2.7 only.
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/fd/pwc3ll_s05v3cqbqsnv9r77r0000gn/T/pip-install-ns9id84h/functools32/

Even after fixing that (and `enum34`), the tests and other Python scripts won't run on Python 3 (see https://github.com/elastic/beats/issues/5950).

As a workaround, one can create the virtualenv manually using Python 2

    virtualenv -p python2 build/python-env

**Comment by ruflin** [comment]
@elastic/beats Time to go to python 3?

**Comment by Tethik** [comment]
Another workaround which worked for me was to add:
```
VIRTUALENV_PARAMS?=-p python2
```
to `beats/libbeat/scripts/Makefile`

**Comment by urso** [comment]
Maybe we should set VIRTUALENV_PARAMS in the Makefile for the time being. Having to remember to set an env variable or setup a private virtualenv as workaround is not really user-friendly.

**Comment by amandahla** [comment]
I have set this variable and it works but it shows the warning: 
"DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7."

At least, it seems that everything worked as expected for the "make create-metricset".

**Comment by amandahla** [comment]
Update: now I had to use "export PYTHON_EXE=/usr/bin/python2" too

**Comment by fearful-symmetry** [comment]
This should be fixed by #14798

**Comment by jsoriano** [comment]
#14798 finished, we are now in the Python 3 age :slightly_smiling_face:, what should solve this problems.
