### ISSUE TITLE
Incorrect default for Filebeat logging.files.keepfiles

### ISSUE THREAD

**Issue by lachlancooper** [elastic/beats#7494]
The [documented default](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-logging.html) for Filebeat's `logging.files.keepfiles` is 7, but in my testing this doesn't seem to be accurate. The actual default seems to be 0, meaning Filebeat doesn't keep any rotated log files.

- Version: Filebeat 6.3.0
- Operating System: Ubuntu 14.04
- Discuss Forum URL: https://discuss.elastic.co/t/incorrect-default-for-filebeat-logging-files-keepfiles/138293
- Steps to Reproduce: 

1. Install Filebeat.
1. Confirm that `/etc/filebeat/filebeat.yml` does not define any value for `logging.files.keepfiles`.
1. Start the service: `service filebeat start`.
1. Confirm that a log file is created at `/var/log/filebeat/filebeat`.
1. Restart the service: `service filebeat restart`, triggering a log rotate.
1. Confirm that the previous log file was overwritten when it should have been rotated: only one file exists under `/var/log/filebeat`.
1. Explicitly set `logging.files.keepfiles: 7` in `/etc/filebeat/filebeat.yml`.
1. Restart the service: `service filebeat restart`, triggering another log rotate.
1. Observe behaviour change: the previous log file was rotated correctly, and now exists at `/var/log/filebeat/filebeat.1`.

**Comment by andrewkroh** [comment]
Looks like we need to add `MaxFiles: 7` here. It was a regression during the logp refactoring around ~v6.2.

https://github.com/elastic/beats/blob/v6.3.0/libbeat/logp/config.go#L36-L39
