### ISSUE TITLE
PHP Agent

### ISSUE THREAD

**Issue by loranger** [elastic/beats#75]
As a feature request, I think it would be interresting to get a PHP protocol which would be (firstly) able to store errors (warning, notice, debug, fatal ?) and graph them such as the mysql protocol does.

**Comment by monicasarbu** [comment]
Moved to libbeat as it's a new beat request. https://github.com/elastic/libbeat/issues/55

**Comment by ruflin** [comment]
Reopening again as libbeat was merged back into this repo: https://github.com/elastic/libbeat/issues/55

**Comment by Hikariii** [comment]
+1

**Comment by fnzv** [comment]
+1

**Comment by monicasarbu** [comment]
Maybe the php-fpm module in Metricbeat can be helpful here.

**Comment by loranger** [comment]
Never mind
