### ISSUE TITLE
memstat.rss reports negative values

### ISSUE THREAD

**Issue by vjsamuel** [elastic/beats#7505]
Where found: master

We have noticed that `memstats.rss` reports negative values. A sample can be found below:
```"memstats":{"gc_next":7296944,"memory_alloc":4251912,"memory_total":36722840592,"rss":-733184}}```

**Comment by kvch** [comment]
I think this might be related to this issue: https://github.com/elastic/beats/issues/5433
Do you see other metrics reporting negative values?

**Comment by ruflin** [comment]
See my comment there, I think it's related to our "non gauge" handling.
