### ISSUE TITLE
Need to load modules from x-pack directory

### ISSUE THREAD

**Issue by webmat** [elastic/beats#7524]
Some of the security analytics modules will come as part of x-pack. There will presumably be more modules that come as part of x-pack in the future.

To make this possible, we will need to look for modules in a new directory. After speaking to @tsg, here's what I know about this:

* The x-pack modules will be located under `x-pack/[beat name]/module`
* It's ok if the x-pack modules get copied to the same directory as the other modules, upon installation.

In order to do this, I'm not sure if we need to do more than add a string to an array, however. Are there other considerations, or other code to modify?

**Comment by webmat** [comment]
Based on the discussion over in https://github.com/elastic/dev/issues/1030, it looks like one of the options may be to split the module in two. Ingestion in OSS and Kibana Objects + ML in x-pack. Just a thing to keep in mind.

**Comment by webmat** [comment]
Foundational work for this is the license check. It's happening here #7946.

**Comment by alvarolobato** [comment]
Hi @webmat we were reviewing this in our planning. Is there still work to be done here?

**Comment by webmat** [comment]
No it's pretty much done, as far as I know. Closing.
