### ISSUE TITLE
Filebeat - iis module - iis.access.hostname should be case-insensitive

### ISSUE THREAD

**Issue by mhunsber** [elastic/beats#7534]
The iis-access-default pipeline should have either "lowercase" or "uppercase" processors for the field "iis.access.hostname" because RFC 4343 says DNS names are case-insensitive.

You could have a site hosted at mysite.com, and if the client connects to MySite.Com, filebeat will log these two hostnames as separate.

Most sites also have case-insensitive urls, but it is not standard.

**Comment by ruflin** [comment]
@mhunsber Makes sense. Interested to open a PR?

**Comment by knrt10** [comment]
@ruflin I would like to work on this.
