### ISSUE TITLE
Question about plugin/extension ability

### ISSUE THREAD

**Issue by jacob-koren-zooz** [elastic/beats#7539]
I'm thinking about extending filebeat to make changes and processing of the logs (like data masking). 
Before I dive into golang, I wanted to know if you have plugins mechanism I can use?

**Comment by ruflin** [comment]
What you are probably looking for is our processor interface? Here are some processors we already have: https://github.com/elastic/beats/tree/master/libbeat/processors

Perhaps you can share a bit more detail on what you plan to build to make sure it's not already there.

**Comment by jacob-koren-zooz** [comment]
Hi, thanks for the quick response. I want to mask personal data from logs, like a phone for example. Can the processor interface receive custom script?

**Comment by ruflin** [comment]
What you mean by customer scripts? Implemented in Golang or third party?

This reminds me of https://github.com/elastic/beats/issues/7273 Perhaps we should have this feature in a more generic way?

**Comment by jacob-koren-zooz** [comment]
Language does not matter. I just want to implement a masking solution:
`
input: {name: service1,hostname:1.1.1.1,pid:1,level:30,msg:"text sensitive text",time:2018-07-11T06:37:53.936Z,v:0}
output: {name: service1,hostname:1.1.1.1,pid:1,level:30,msg:"text XXXXXX text",time:2018-07-11T06:37:53.936Z,v:0}
`
Can I use the processor interface to achieve it? 
Can I write my own processor and/or action? Some other way? 
Also, do you think such manipulation on the logs will have a significant performance effect?

**Comment by ruflin** [comment]
You can write a processor to make these modifications. Forking the project and adding your own processor is probably the quickest way to get started. Processor work mostly like "plugins" (they even can be go plugins) and are imported here: https://github.com/elastic/beats/blob/master/libbeat/cmd/instance/beat.go#L69

This should allow you to only modify the imports here but keep it easily in sync with up-stream project.

Would be great if you could share the outcome of your processor here so we can further discuss if it's something we could adapt in Beats in general.

**Comment by faec** [comment]
It looks like there's no ongoing issue here and it's been idle for a while, so I'm closing it. Feel free to follow up with any general questions in the [discuss forums](https://discuss.elastic.co/c/beats)
