### ISSUE TITLE
libbeat: panic on exit

### ISSUE THREAD

**Issue by cyrilleverrier** [elastic/beats#754]
Steps to reproduce:
1. cd  $GOPATH/src/github.com/elastic/beats/filebeat
2. git pull origin master
3. `make system-tests`
4. `cat build/system-tests/run/test_crawler.Test.test_default_include_exclude_lines/filebeat.log`

In all the log files, you can see that the application panicked on exit.

**Comment by cyrilleverrier** [comment]
Patch on its way...

**Comment by ruflin** [comment]
That is a nasty one I quite recently introduced in https://github.com/elastic/beats/pull/626 and definitively should have spotted the problem in the log :-(
