### ISSUE TITLE
[Filebeat] docker input support nanoseconds timestamp

### ISSUE THREAD

**Issue by pytimer** [elastic/beats#7559]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version:  6.3.0
- Operating System:  Centos7.4
- Discuss Forum URL:  
https://discuss.elastic.co/t/low-timestamp-precision-cause-wrong-order-of-events-with-docker-input/137051

- Steps to Reproduce: 
Use Filebeat with kubernetes to collect docker logs. 

I also have above forum url problem.

Docker use nanoseconds timestamp to store log, Filebeat only support millisecond timestamp precision, if store log to elasticsearch with millisecond, docker logs will be slightly unordered.So hope Filebeat can support nanoseconds timestamp precision. 

I already implement nanoseconds, this forum have insturctions, but i think it is not the best way to implement it.If this feature need to do, anyone have other idea to implement it.

Thanks.

**Comment by ruflin** [comment]
In think the blocking part here is Elasticsearch as does not support yet nano seconds. But they are working on supporting it: https://github.com/elastic/elasticsearch/issues/27330

**Comment by archvill** [comment]
@ruflin do we have any objections to not to start supporting it now in filebeat? Theoretically stream destination can be something other than Elasticsearch, for example Splunk, right? :)

PS. There's a patch available to support this and we can create a pull request if it would have a chance to merge.
https://github.com/pytimer/beats/commit/8996d4f0e27415eb7d390ccc0da694bad76969bf

**Comment by pytimer** [comment]
I can store logs to elasticsearch, and search logs from elasticsearch order by nanoseconds timestamp. 

Now on my project, i use this way. Does it affect the elasticsearch?

**Comment by archvill** [comment]
@pytimer I'm not an expert, AFAIK the default field to store timestamp is `@timestamp`. This is what Kibana expect in index structure. `@timestamp` field is in turn created with `date` type in Elasticsearch index mapping by default. Dates in Elasticsearch have millisecond precision. You can use your custom field to store timestamp, it can be `string` or numeric type for example. But it will be slower than filtering/sorting by default `date` field.

**Comment by pytimer** [comment]
Thanks for your reply.

Can we add a configuration option to change timestamp precision? deault value is millisecond. If someone want to high timestamp precision, config it. I am not sure is it reasonable?

**Comment by pytimer** [comment]
@archvill I'm look over elasticsearch logs data, found `@timestamp` type is `date`, i don't understand elasticsearch too much. I'm not use Kibana to view logs, i use a simple web to do it, beacuse  i know Kibana seems that can not search log with nanoseconds.

Below are my Elasticsearch data.

Elasticsearch search url:
`http://10.33.46.109:30397/kubernetes_kube-system_2018.07.11/_search?pretty&sort=[@timestamp:desc]`

Elasticsearch part of  logs data:
```json
"hits" : [
    {
        "_index":"kubernetes_kube-system_2018.07.11",
        "_type":"doc",
        "_id":"Or7OfGQBDQ7lJslTjX7p",
        "_score":1,
        "_source":{
            "@timestamp":"2018-07-11T02:11:05.272787936Z",
            "offset":23561723,
            "prospector":{
                "type":"docker"
            },
            "beat":{
                "name":"filebeat-588n8",
                "hostname":"filebeat-588n8",
                "version":"7.0.0-alpha1"
            },
            "input":{
                "type":"docker"
            }
        }
    },
    {
        "_index":"kubernetes_kube-system_2018.07.11",
        "_type":"doc",
        "_id":"O77OfGQBDQ7lJslTjX7p",
        "_score":1,
        "_source":{
            "@timestamp":"2018-07-11T02:11:04.815929674Z",
            "stream":"stderr",
            "input":{
                "type":"docker"
            },
            "offset":16298720,
            "prospector":{
                "type":"docker"
            },
            "beat":{
                "name":"filebeat-588n8",
                "hostname":"filebeat-588n8",
                "version":"7.0.0-alpha1"
            }
        }
    }
]
```

- Elasticsearch index part of mapping structure:
```json
{
    "kubernetes_kube-system_2018.07.11":{
        "mappings":{
            "doc":{
                "_meta":{
                    "version":"7.0.0-alpha1"
                },
                "dynamic_templates":[
                    {
                        "fields":{
                            "path_match":"fields.*",
                            "match_mapping_type":"string",
                            "mapping":{
                                "type":"keyword"
                            }
                        }
                    },
                    {
                        "docker.container.labels":{
                            "path_match":"docker.container.labels.*",
                            "match_mapping_type":"string",
                            "mapping":{
                                "type":"keyword"
                            }
                        }
                    },
                    {
                        "strings_as_keyword":{
                            "match_mapping_type":"string",
                            "mapping":{
                                "ignore_above":1024,
                                "type":"keyword"
                            }
                        }
                    }
                ],
                "date_detection":false,
                "properties":{
                    "@timestamp":{
                        "type":"date"
                    },
                    "input":{
                        "properties":{
                            "type":{
                                "type":"keyword",
                                "ignore_above":1024
                            }
                        }
                    },
                    "message":{
                        "type":"text",
                        "norms":false
                    },
                    "offset":{
                        "type":"long"
                    },
                    "read_timestamp":{
                        "type":"keyword",
                        "ignore_above":1024
                    },
                    "source":{
                        "type":"keyword",
                        "ignore_above":1024
                    },
                    "stream":{
                        "type":"keyword",
                        "ignore_above":1024
                    }
                    "tags":{
                        "type":"keyword",
                        "ignore_above":1024
                    }
                }
            }
        }
    }
}
```

**Comment by ruflin** [comment]
It did some testing on my end with ES. We can ingest timestamps with more precision into Elasticsearch and it will be stored in _source. But for querying etc. the value is stored as a long and currently the maximum resolution is milli seconds.

As Elasticsearch is planning to support nano seconds I definitively like the idea of having a config option to already enable it now if poeple want. There we can also clearly the limitation and if someone runs lets say 6.4 Beats vs 7.0 ES he potentially would get nanoseconds for querying.

@archvill Would be great if you could open a PR.

**Comment by archvill** [comment]
@pytimer @ruflin https://github.com/elastic/beats/pull/7576
