### ISSUE TITLE
(file)beat does not support redis sentinels [feature-request]

### ISSUE THREAD

**Issue by fsperling** [elastic/beats#7566]
It would be great if filebeat was able to support redis sentinels.
We run a redis master-slave setup with 3 redis-sentinels.
Where only the master allows writes. The sentinels provide you with the current master (and also promote the slave in case of a problem).

If I only provide the redis master in the filebeat config it works until a failover. After that filebeat gets an error that it can't write to the slave.

If I provide both redis master and slave and loadbalance half of the requests go to the slave.

There should be an option to provide a list of redis sentinels from which filebeat retrieves the current master.

**Comment by ruflin** [comment]
I assume you are referring to the filebeat redis input?

**Comment by fsperling** [comment]
Hi ruflin,
no, we need it for the filebeat redis output.
Our messages go through filebeat -> redis -> logstash -> elasticsearch

**Comment by pytimer** [comment]
I think @fsperling  said right. On my case, some application write data to redis, it also need to connect redis sentinels, the reason like @fsperling  said. `go-redis` lib support redis sentinels, doc: https://godoc.org/github.com/go-redis/redis#FailoverOptions. 

This is only my idea. :)

**Comment by ruflin** [comment]
Thanks for the additional details. Filed it under `output` now.

**Comment by G-Paradis** [comment]
@Any news about this feature request?

Using Redis as a 'buffer' between Filebeat and Logstash is quite useless if that buffer becomes a single point of failure. Using Redis Sentinel would greatly improve reliability, allowing writes to go directly to the master.

**Comment by jeremyzhou** [comment]
which version of filebeat support redis cluster?

**Comment by auqf** [comment]
you can use the a proxy to proxy the sentinel,recommand you to use the predixy。

**Comment by nemphys** [comment]
+1 on supporting redis sentinels
