### ISSUE TITLE
[Feature Request] Implement idle_timeout feature for better network behavior

### ISSUE THREAD

**Issue by kholia** [elastic/beats#7581]
Filebeat and Auditbeat use a long-lived persistent TCP connection to talk to Logstash.

On the Logstash side, the default value of `client_inactivity_timeout` options is set to 60 secods.

Due to this, Filebeat/Auditbeat and Logstash do not play well with each other out-of-the box.

I recently opened https://github.com/elastic/beats/issues/7575 (Network connection related errors in logs) regarding this matter.

Each instance of Auditbeat + Filebeat also (tries to) hog a socket connection on the Logstash side. This may lead to resource exhaustion problems when operating at scale. It would be nice to release the socket when Auditbeat/Filebeat are in an idle state. This idle state configuration should be tweakable with the new proposed `idle_timeout` option.

Thanks!

CC @robgil @urso.

**Comment by robgil** [comment]
@urso in our particular use case, we have an AWS ELB inbetween. The default TCP idle timeout is 60s on the AWS ELB. For our particular use case, we should either set the `ttl` to either <60s, or enable `keep_alive` with a probe time of < 60s so the connection is kept open before the idle timeout on the ELB. 

As for defaults, setting the `ttl` to 60s or less would be a reasonable default and cover the typical defaults of both Linux hosts as well as AWS ELBs. `keep_alive` is something that should be enabled only if its desirable to keep the connections open all the time. In large scale environments, this can increase the resources needed to maintain large numbers of open connections.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
