### ISSUE TITLE
generator: First time `make setup` runs, it will fail trying to run the `update` target

### ISSUE THREAD

**Issue by jordansissel** [elastic/beats#7592]
Tested on beats master.

```
⓿ toast(/mnt/d/projects/go/src/github.com/elastic) master
% python beats/script/generate.py
...
% cd mybeat
% make setup
mkdir -p vendor/github.com/elastic
cp -R /home/jls/projects/go/src/github.com/elastic/beats vendor/github.com/elastic/
rm -rf vendor/github.com/elastic/beats/.git vendor/github.com/elastic/beats/x-pack
mkdir -p vendor/github.com/magefile
cp -R /home/jls/projects/go/src/github.com/elastic/beats/vendor/github.com/magefile/mage vendor/github.com/magefile
make: *** No rule to make target 'update', needed by 'setup'.  Stop.
```

I believe this is because `update` target is provided by a file that doesn't exist the first time `make setup` runs:

```
ES_BEATS?=./vendor/github.com/elastic/beats
...
# Path to the libbeat Makefile
-include $(ES_BEATS)/libbeat/scripts/Makefile
```

This Makefile doesn't exist yet because `copy-vendor` hasn't run.

Maybe we can change the `setup` target to do this instead which will ensure a new `make` is run after `copy-vendor` happens such that the vendor'd beats Makefile is loaded?

```diff
-setup: copy-vendor update git-init
+setup: copy-vendor
+  $(MAKE) update git-init
```

**Comment by ruflin** [comment]
I like the idea.

I wonder if we should get rid of the `setup` call completely and instead change the docs.

First run `make` which will automatically call the first target `copy-vendor` and then run `make update`.

Should we really do the `git-init` automatically for the users or should it be his decision to run it?

**Comment by Crocmagnon** [comment]
I'm still not able to `make` the generated beat following the docs.
What would the workaround be ?

**Comment by jsoriano** [comment]
I think this is not an issue anymore after the migration of the generators to mage/go (https://github.com/elastic/beats/pull/13610), @fearful-symmetry wdyt?
