### ISSUE TITLE
Adapt packetbeat process monitor to ECS

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#7595]
With 6.4, the process monitor in packetbeat has been revamped to add the command-line of processes (https://github.com/elastic/beats/pull/7135).

It might make sense to take the oportunity and rename the fields to adhere to [ECS](https://github.com/elastic/ecs#process) before 6.4 is released (breaking change).

**Comment by adriansr** [comment]
cc/ @ruflin

**Comment by andrewkroh** [comment]
Fixed by 
https://github.com/elastic/beats/pull/9303.
