### ISSUE TITLE
Document debug selectors

### ISSUE THREAD

**Issue by markwalkom** [elastic/beats#7603]
It'd be handy if we had a list of the possible selectors [here](https://www.elastic.co/guide/en/beats/filebeat/current/enable-filebeat-debugging.html), [here](https://www.elastic.co/guide/en/beats/packetbeat/current/enable-packetbeat-debugging.html) etc etc.

Alternatively it may make more sense to put them all here - https://www.elastic.co/guide/en/beats/libbeat/current/index.html - and link them to the per-beat debug pages.

**Comment by dedemorton** [comment]
We made a conscious decision awhile back ago to leave the debug selectors undocumented because we didn't want to expose details about Beat processing that were likely to change over time.

@urso Is that still our position?

**Comment by ph** [comment]
@dedemorton I think we could have a high level list, _we might_ miss some but I think its worth to experiment. We could keep that list up to date with make update and create the asciidoc.
