### ISSUE TITLE
add memory-usage metrics to schema of memcached-module of metricbeats

### ISSUE THREAD

**Issue by Hooddominator** [elastic/beats#7618]
...forwarded as suggested in elasticsearch-forum ( https://discuss.elastic.co/t/add-memory-usage-metrics-to-schema-of-memcached-module-of-metricbeats/140303 )

To determ memory-usage of a memcached-instance it would be really helpfull if we can add two additional metrics which are allready present in scanned/parsed "stats"-data of memcached. The field with key " limit_maxbytes" contains the maximum defined memory for the instance and the field with key "bytes" contains the currently used memory. If we add these fields to the scheme which is used for mapping by the scanner, we can calculate the used-memory against max memory of an instance (eg. as percental value by calculate limit_maxbytes / bytes * 100 in a pipeline via logstash or ingestnode). This metric would be ways more usefull to determ an instance which memory reaching max than notice occuring evictions - when max memory is allready reached...

Due my ultra low knowledge of golang and nearly zero-experience of setup a golang-dev-env i failed to get a working build of my branch with relevant changes, thus i hope these gist may also be usefull:

https://gist.github.com/Hooddominator/27af3c383b13bb838c4d5a415e3f905f

thanks in advance

**Comment by ruflin** [comment]
@Hooddominator Feel free to push your existing branch with the changes even if does not go green. We then can either help you to get it to green or take over the branch from there. Should make it easier to have a look at the diff and discuss it.

**Comment by Hooddominator** [comment]
Okay, i created a pull with my changes: https://github.com/elastic/beats/pull/7630

**Comment by Hooddominator** [comment]
changes merged allready in #7740
