### ISSUE TITLE
Filebeat log for timeout limit

### ISSUE THREAD

**Issue by danielkasen** [elastic/beats#7626]
Is there any way to know filebeat has hit the  close_timeout option set for a log file? I'm not seeing anything in the INFO logging and this would be good to know when you hit this after a log rotation. Since currently the user might be losing events that don't show up as dropped because the harvester never got to them.

**Comment by ruflin** [comment]
If a file is closed because of `close_timeout` there should be a log message like  ` Closing harvester because close_timeout was reached:`. Let's continue this discussion on discuss: https://discuss.elastic.co/c/beats/filebeat Feel free to open a topic there.
