### ISSUE TITLE
[Metricbeat] system.cpu.total.*.pct includes IOWait

### ISSUE THREAD

**Issue by axw** [elastic/beats#7627]
The total CPU% is calculated as the amount of time spent in the non-idle state:

https://github.com/elastic/beats/blob/494620259c81c1a724828afa57e2a7fcd2cc18b7/libbeat/metric/system/cpu/cpu.go#L119

I would expect that IOWait time to be excluded also.

**Comment by ruflin** [comment]
Note: This also effects the data reported to Monitoring.

**Comment by henrikno** [comment]
I was curious why this changed, but then I read http://veithen.github.io/2013/11/18/iowait-linux.html which explained it pretty well.
