### ISSUE TITLE
[Filebeat] Kafka input

### ISSUE THREAD

**Issue by ytc301** [elastic/beats#7641]
Whether filebeat adds support for kafka input

Processor in a Pipeline

filebeat_agent_log-----> kafka -----> kafkainput_filebeat_esout -----> elasticsearch
    Pipeline -----------------------------------Pipeline

**Comment by ruflin** [comment]
Is this a feature request for kafka filebeat input? If yes, could rephrase the title a bit to make it more clear?

**Comment by exekias** [comment]
@faec I understand this can be closed already? https://github.com/elastic/beats/issues/7641 was merged
