### ISSUE TITLE
Duplicate entries for Metricbeat module docs

### ISSUE THREAD

**Issue by acchen97** [elastic/beats#7643]
In the Metricbeat module docs, it looks like kvm, munin, and uwsgi have duplicates. kvm and munin also have duplicate metricset docs.

https://www.elastic.co/guide/en/beats/metricbeat/6.3/_munin_node_metricset.html

/cc @dedemorton

**Comment by ruflin** [comment]
PR to fix this opened here: https://github.com/elastic/beats/pull/7650
