### ISSUE TITLE
Add Telemetry fields for Kibana Spaces

### ISSUE THREAD

**Issue by legrego** [elastic/beats#7667]
@ycombinator [suggested that I open an issue](https://github.com/elastic/kibana/pull/20581#issuecomment-406006872) to get telemetry fields added for the new Kibana Spaces feature. We won't need this until sometime after 6.4.

I'm happy to give this a shot myself, if someone can point me in the right direction!

**Comment by ruflin** [comment]
For my understanding: This is a request to add the metrics reported by Spaces to the Kibana metricbeat module / metricset to be reported to the Monitoring cluster. From there it's up to Telemetry to pick it up.

**Comment by ycombinator** [comment]
That's correct @ruflin. This issue is just for the "shipping to monitoring" part.

**Comment by ycombinator** [comment]
BTW, this issue might be moot if we can get https://github.com/elastic/beats/pull/7684 and the corresponding Kibana PR (TBC) done. Just a heads up.

**Comment by ycombinator** [comment]
@legrego Now that https://github.com/elastic/beats/pull/7684 is merged, we shouldn't need this issue (or future ones like it) any more! Closing...
