### ISSUE TITLE
Metricbeat Kibana Stats Metricset to look for Canvas usage data

### ISSUE THREAD

**Issue by tsullivan** [elastic/beats#7685]
Similar to https://github.com/elastic/beats/issues/7667, the Kibana `/api/stats` endpoint will feature Canvas usage data. The Metricbeat Metricset will need to be aware of the new data fields.

This will depend on:
 - https://github.com/elastic/kibana-canvas/pull/823
 - https://github.com/elastic/kibana/pull/21053

cc @ruflin @ycombinator 

### Example:
```
"usage": {
  "kibana_canvas": {
    "elements": {
      "per_page": {
        "avg": 1,
        "max": 1,
        "min": 1
      },
      "total": 1
    },
    "functions": {
      "in_use": [
        "filters",
        "demodata",
        "markdown",
        "render"
      ],
      "per_element": {
        "avg": 4,
        "max": 4,
        "min": 4
      },
      "total": 4
    },
    "pages": {
      "per_workpad": {
        "avg": 1,
        "max": 1,
        "min": 1
      },
      "total": 1
    },
    "workpads": {
      "total": 1
    }
  }
}
```

**Comment by ycombinator** [comment]
Thanks for creating this issue, @tsullivan, but now that https://github.com/elastic/beats/pull/7684 is merged, we should no longer need this issue (or future ones like it). Closing.
