### ISSUE TITLE
building the test binary of a community beat includes all vendor packages

### ISSUE THREAD

**Issue by cyrilleverrier** [elastic/beats#769]
## Steps to reproduce:
Community beat that uses `glide` to save dependencies into the vendor package
`make system-tests`

## Actual Result:
Makefile creates the following action for the `libbeat.test` rule:
`go test -c -covermode=atomic -coverpkg ./...` builds `mybeat.test` with code coverage for all the source code including all the vendor packages.

Many warnings and errors are output. 
Test application can't be built

## Expected result:
Makefile should create the following action for the `libbeat.test` rule:
`go test -c -covermode=atomic -coverpkg github.org/mybeat/mybeat,github.org/mybeat/mybeat/beat,github.org/mybeat/mybeat/config`

**Comment by andrewkroh** [comment]
Fixed by #770
