### ISSUE TITLE
Fields.yml generation ignores files in nested folders

### ISSUE THREAD

**Issue by jalvz** [elastic/beats#7705]
The previous packaging did look up folders recursively, so I am marking this as a bug.

**Comment by jalvz** [comment]
This fixes the issue we found: https://github.com/elastic/apm-server/pull/1177/commits/d76ad5e240e32d64ae181fa6473fc5179dc8cc84

`model/metric/system/_meta/fields.yml` wasn't picked up

**Comment by andrewkroh** [comment]
Related discussion: https://github.com/elastic/apm-server/pull/1177#discussion_r204803226

https://github.com/elastic/apm-server/blob/master/magefile.go#L102-L104

**Comment by urso** [comment]
@andrewkroh @jalvz The issue is quite old. Does the problem still exist, or has it been fixed by now?

**Comment by andrewkroh** [comment]
I think things are working. The field generator code understands the structure of modules as they exist in beats today and can collect fields.yml from those. If there's a different structure then I think some customization must be done.
