### ISSUE TITLE
Improve Filebeat inputs metrics visibility to help identify back pressure

### ISSUE THREAD

**Issue by ph** [elastic/beats#7743]
**Context:**

When back pressure happens on the target system, the pressure is communicated back to the inputs following this high-level flow: output -> queue -> inputs.

Let's take the log inputs, by default the input is frequently scanning the file system to detect new files. When a new file is detected, it starts reading that file into a new goroutine.  Each new line is pushed to the queue if an error occurs when reading we do some checks to decide what to do:

**Example of checks:**
- EOF
- close_inactive
- deletion of file

These calls execute 'inline' of the reading action.

When back-pressure reaches the log input, the scanner is continually creating new goroutine on a new file, existing goroutine and the new one are blocked on push.

This blocking scenario is causing the following:

- goroutines will be stuck.
- high number of go routine
- inline checks not executed
- FD are keep for a more extended period.

The problem is the current stats exposed by libbeat are not sufficient to understand what is going on and with the default behavior, currently, they show a working and green system and no actionable items.

**Things we could exports:**

- Expose each harvester reading rate.
  This value can be compared to the system event rate or filling rate.

- Expose time to insert to the queue.
   higher values mean higher latency.

- Input backlog
  AKA Consumer backlog, current offset vs file size, how far are we from the tail, this would give us a good idea how far behind we are.

- Expose the available disk space this is a side effect of having multiple FD.

**The above metrics or insights are all linked.**

Higher time to insert to queue -> Lower reading rate -> offset < tail and increasing.

**Comment by ppf2** [comment]
Thanks! Related: https://github.com/elastic/beats/issues/5205

**Comment by ph** [comment]
related to https://github.com/elastic/beats/issues/7886

**Comment by ph** [comment]
Added a note concerning tracking available disk space in a scenario when we have a lot of back pressure.

**Comment by henrikno** [comment]
The metrics added in https://github.com/elastic/beats/pull/13395 are great, however as they are currently they're not directly usable.
They got disabled by default due to mapping explosion, https://github.com/elastic/beats/issues/19745.

What we need is an aggregated metric of the same data, similar to what's described in https://github.com/elastic/beats/issues/7743#issuecomment-408119091, which can then be enabled by default and e.g. displayed in stack monitoring.
