### ISSUE TITLE
[Auditbeat] file_integrity folders and files notification failure

### ISSUE THREAD

**Issue by gwsales** [elastic/beats#7760]
When using directories and full file paths for the file_integrity module, the files are ignored and only directories are monitored. 

If your config is looking for specific file paths within directories already monitored, you'd never notice this. 

example: 
```
- module: file_integrity
  paths:
  - /etc
  - /opt/custom_file.cfg
```
With this example, the custom_file.cfg is never alerted on when it's changed, it is scanned only on auditbeat restart.

**Comment by cwurm** [comment]
@gwsales It should not do that, and it works on my system with the configuration.

Can you attach a few more details?
1. Auditbeat version
2. OS
3. full config
4. debug log (start auditbeat with `-d "*"`)
5. Steps to reproduce (incl. how you changed `custom_file.cfg`)

**Comment by konnykonny50** [comment]
Hello,
I also encountered this bug in version 7.6.0. Does anybody know whether there has been any progress since then?
Thanks

**Comment by scottgeary** [comment]
I think this actually related to bug with using `recursive: true`.
See https://github.com/elastic/beats/issues/23098
