### ISSUE TITLE
additional vsphere metric in metricbeat - feature request

### ISSUE THREAD

**Issue by drav3nmc** [elastic/beats#7782]
Is it possible for the vsphere module in metricbeats to get the following additional metric

virtualmachine cpu.usage.average

**Comment by amandahla** [comment]
I'm not sure if vSphere API provides this information. Do you know that?

This module gets the information documented [here](https://code.vmware.com/apis/42/vsphere#/doc/vim.vm.Summary.QuickStats.html) and related to CPU the following properties are available:

* overallCpuDemand: Basic CPU performance statistics, in MHz. Valid while the virtual machine is running. 
* overallCpuUsage (we use this): Basic CPU performance statistics, in MHz. Valid while the virtual machine is running. 
* staticCpuEntitlement: The static CPU resource entitlement for a virtual machine.

**Comment by jsoriano** [comment]
It seems that this and many other metrics can be collected using performance metrics. There is an example about this here: https://github.com/vmware/govmomi/blob/master/performance/example_test.go

**Comment by jsoriano** [comment]
Metricbeat 7.14 will include metrics for total and free CPU per virtualmachine, based on the configured CPU reservation (https://github.com/elastic/beats/pull/26167).

Closing this by now, other metrics would be covered by https://github.com/elastic/beats/issues/20313.
