### ISSUE TITLE
Support add_docker_metadata in Windows

### ISSUE THREAD

**Issue by wflyer** [elastic/beats#7797]
I'm trying to collect docker logs using filebeat in Windows, but I've found that it can't be done due to current limitation.

In the current master branch, `source` field is used to get docker container id of the log.

Since `source` field of docker logs in Windows looks like `"C:\\ProgramData\\docker\\containers\\{{ docker container id }}\\{{ docker container id }}-json.log"`, the path can't be parsed because the separator is `/` (https://github.com/elastic/beats/blob/fb0d7d4be9c7c26fd175af057b6b8246378df770/libbeat/processors/add_docker_metadata/add_docker_metadata.go#L88)

I think it would be better to use `func SplitList(path string) []string` in `path/filepath` package rather than using `extract_field` processor to get the container id. Or, at least, the directory separator should be configurable.

**Comment by exekias** [comment]
Probably passing `os.PathSeparator` there would fix the issue
