### ISSUE TITLE
Add support for Postgres extended queries (unnamed prepared statements)

### ISSUE THREAD

**Issue by boymaas** [elastic/beats#78]
Hai, I am trying to get postgresql logging to work on a core-os machine. Everything is setup, and registration of transactions is functioning when connecting with a "psql" client (v9.3) from local-machine and remote. For some reason packetbeat does not recogise "transactions" when using the JDBC client.

I am using JDBC from within clojure with the following settings:

{:classname "org.postgresql.Driver"
                        :subprotocol "postgresql"
                        :subname "//xx.xx.xx.xx:5432/foo"
                        :user "fooo"
                        :password "foo"
                        :protocolVersion "3"
                        }

and running simple select * from ... limit 1 queries. 

Is this a known issue?  That some libraries communicate in a somewhat different protocol, and break the loggin capacities of packetbeat?

I have made a packetdump. Let me know if you need it ...

-Boy

**Comment by whisk3y** [comment]
Has this been added yet?

**Comment by syunusic** [comment]
Same problem here... I did a packet capture and I see this "T/D/C/Z" thing... Any clue when it will be supported? Thanks!

**Comment by navenel** [comment]
Anu idea when it will be supported ?

**Comment by easyrasta** [comment]
+1

**Comment by shaunrampersad** [comment]
+1

**Comment by sqshq** [comment]
+1

**Comment by MingchunZhao** [comment]
+1

**Comment by MingchunZhao** [comment]
I've tried to deal with this issue, and got expected output for Extended Queries via JDBC Driver.

So,
1. How can I contribute my code?
2. Could anyone review my code including test cases?

I will appreciate any help with this situation.

**Comment by tsg** [comment]
@MingchunZhao Sounds great! To contribute you need to open a Pull Request with your code, please see our [contributing guide](https://github.com/elastic/beats/blob/master/CONTRIBUTING.md) for more details. If you need help with that process, you can ask in the [forums](https://discuss.elastic.co/c/beats/packetbeat) or on IRC (#beats channel on freenode).

**Comment by MingchunZhao** [comment]
Thanks, will do.

**Comment by andrewkroh** [comment]
Added in #939
