### ISSUE TITLE
Lost the top several letters

### ISSUE THREAD

**Issue by erdun** [elastic/beats#7811]
with the warning of logstash, I found it's possible that filebeat collect incomplete log.

origin logs
```
2018-07-30T12:51:54.573Z INFO request 2aab2cea-25ba-4843-ab8b-ca7b25103012 GET 200 /platform?_source=702e65070fc8db919cf77bbf5299d0d6 123.58.9.33 88667 34
```

but filebeat lost the first two letters
```
2018/07/30 12:52:02.922470 client.go:184: DBG  Publish: {
  "@timestamp": "2018-07-30T12:52:01.057Z",
  "beat": {
    "hostname": "hz_node_potal_002",
    "name": "hz_node_potal_002",
    "version": "5.0.0"
  },
  "input_type": "log",
  "message": "18-07-30T12:51:54.573Z INFO request 2aab2cea-25ba-4843-ab8b-ca7b25103012 GET 200 /platform?_source=702e65070fc8db919cf77bbf5299d0d6 123.58.9.33 88667 34 ",
  "offset": 558954,
  "source": "/code/logs/request.log",
  "tags": [
    "smart",
    "frontend",
    "release"
  ],
  "type": "frontend_log"
}
```

filebeat version: filebeat version 5.0.0 (amd64), libbeat 5.0.0

docker image: alpine

**Comment by jsoriano** [comment]
Hi @erdun,
Thanks for reporting this problem, could you try to upgrade filebeat? In case the problem persist, could you also share your filebeat configuration?

**Comment by urso** [comment]
No update for 6+ months. Without logs and configuration we can not really debug this.
Closing. Please reopen, and provide logs+configs if issue persists with newer docker images/releases.
