### ISSUE TITLE
Clarify recommendation for scan_frequency setting in Filebeat doc

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#783]
The documentations for scan_frequency currently says:

"If you specify 0s, the directory is scanned as frequently as possible. We recommend that you do not specify 0."

It's not just that we don't recommend; it's a really bad idea for users to set the scan frequency to 0. The lowest setting should probably be 0.1s because a setting of 0 makes filebeat scan the disk in a tight loop.

I think the text should be changed to say: Set the value of scan_frequency to 0.1s to scan the directory as frequently as possible.

**Comment by ruflin** [comment]
We should not even recommend lower then 1s. 0.1s is only for our testing environment.

**Comment by andrewkroh** [comment]
The documentation change was merged to 1.1.
