### ISSUE TITLE
Metricbeat - Elasticsearch module - missing some node metrics 

### ISSUE THREAD

**Issue by yaronp68** [elastic/beats#7848]
For confirmed bugs, please report:
- Version: 6.4 
- Operating System: OSX

- Steps to Reproduce: 
Deploy elasticsearch cluster with metricbeat over K8S. 
Configure metricbeat to report metrics to elasticsearch and look at metricbeat index in kibana 
The following metricsets are missing comapred to [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html):

* Operating system stats, load average, mem, swap
* Process statistics, memory consumption, cpu usage, open file descriptors (except for mlockall which is reported)
* Statistics about each thread pool, including current size, queue and rejected tasks
* Transport statistics about sent and received bytes in cluster communication
* breaker - Statistics about the field data circuit breaker
* Discovery - Statistics about the discovery
* Ingest - Statistics about ingest preprocessing
* adaptive_selection - Statistics about adaptive replica selection

**Comment by ruflin** [comment]
* Load average etc. you should get from the system module, same for process stats
* For the other metrics, could you share in which Elasticsearch endpoint they are available and the name of each to make sure we talk about the same metric?

**Comment by ycombinator** [comment]
@yaronp68 Any ideas about this question from @ruflin in the previous comment?

> For the other metrics, could you share in which Elasticsearch endpoint they are available and the name of each to make sure we talk about the same metric?

**Comment by yaronp68** [comment]
@ycombinator  https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html

**Comment by ruflin** [comment]
I don't think we should just add all metrics from the node stats endpoint but be selective which metrics we send to Elasticsearch. We rather define the visualisations and alerts we want to create first and then derive which metrics we need.

**Comment by ycombinator** [comment]
Makes sense, @ruflin. As you can see in the PR (#7993), it's a lot of data so I'm 👍 for culling it down based on what actual visualizations/alerts we think might be useful to users.

If I had to choose, based on my experience with "supporting" ES clusters, the metrics I'd add for now are:
* thread pool metrics, but only for `index`, `search`, `get`, `write`, `snapshot`, and `refresh` thread pools. I can imagine users wanting to monitor the usages of these threadpools over time to decide whether they need to tweak any of their sizes.

* field data circuit breaker metrics. I can imagine users setting alerts for these.

@yaronp68 WDYT of the above set for now?

**Comment by ycombinator** [comment]
@yaronp68 *bump*

**Comment by tsg** [comment]
@ruflin did you intend to add the SecOps label on this one? Maybe I miss the relation?

**Comment by ruflin** [comment]
@tsg No, only wanted to add stack-monitoring and SecOps somehow slipped in. Removed again.

**Comment by cdenneen** [comment]
module configured:
```
$ cat elasticsearch.yml
# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/6.5/metricbeat-module-elasticsearch.html

- module: elasticsearch
  metricsets:
    - node
    - node_stats
    - index
    - index_recovery
    - index_summary
    - shard
    #- ml_job
  period: 10s
  hosts: ["http://localhost:9200","http://localhost:9201"]
  #username: "user"
  #password: "secret"
```

Metrics are sending over:
```
2019-02-15T16:47:01.980-0500	INFO	[monitoring]	log/log.go:144	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":87900,"time":{"ms":352}},"total":{"ticks":234200,"time":{"ms":883},"value":234200},"user":{"ticks":146300,"time":{"ms":531}}},"handles":{"limit":{"hard":4096,"soft":1024},"open":19},"info":{"ephemeral_id":"b5a5bbbf-2ac0-4169-a5ba-a8990cef650e","uptime":{"ms":8733049}},"memstats":{"gc_next":9003488,"memory_alloc":6264056,"memory_total":23789357552}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"acked":77,"batches":3,"total":77},"read":{"bytes":1500},"write":{"bytes":67409}},"pipeline":{"clients":8,"events":{"active":0,"published":77,"total":77},"queue":{"acked":77}}},"metricbeat":{"elasticsearch":{"node":{"events":6,"success":6},"node_stats":{"events":6,"success":6}},"system":{"cpu":{"events":3,"success":3},"filesystem":{"events":4,"success":4},"fsstat":{"events":1,"success":1},"load":{"events":3,"success":3},"memory":{"events":3,"success":3},"network":{"events":24,"success":24},"process":{"events":24,"success":24},"process_summary":{"events":3,"success":3}}},"system":{"load":{"1":2.7,"15":2.94,"5":2.96,"norm":{"1":0.0844,"15":0.0919,"5":0.0925}}}}}}
```
but still nothing showing up for elasticsearch in the Kibana UI

<img width="144" alt="screen shot 2019-02-15 at 4 50 41 pm" src="https://user-images.githubusercontent.com/720097/52886294-dce2d800-3141-11e9-98a8-0c40ff92ebc0.png">

**Comment by cachedout** [comment]
@yaronp68 We are waiting on a reply from you before we can move forward here. :)

**Comment by yaronp68** [comment]
@cachedout @ycombinator 
Agree about thread pools metrics & circuit breaker trips

Also recommend adding the fs disks metrics although linux only (windows is  less than 10% of clusters)
```fs.io_stats.devices (Linux only)
Array of disk metrics for each device that is backing an Elasticsearch data path. These disk metrics are probed periodically and averages between the last probe and the current probe are computed.```

**Comment by ycombinator** [comment]
Many of these metrics are now being collected so I'm closing this issue. For any **specific** ones that are still missing, please look at existing [open Stack Monitoring issues](https://github.com/elastic/beats/labels/Stack%20monitoring) or create a new one.
