### ISSUE TITLE
[libbeat] - Spool to disk permissions issues on Windows

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#7849]
When starting disk spooling it checks the permissions of the existing file and if they are more permissive that the configured `queue.spool.file.permissions` it results in an error.

https://github.com/elastic/beats/blob/36411a3616882547eb961cea13b7c2199bb31b3b/libbeat/publisher/queue/spool/spool.go#L82-L86

But Windows does not have standard POSIX file permissions since it uses a DACL. So we should skip this check for Windows. Take a look at how the mode bits get set on Windows in: https://github.com/golang/go/blob/4c77cb3087363f2ebab565bd2b46935749ca7dd2/src/os/types_windows.go#L36-L40

`
2018-08-02T12:09:17.067+0800 ERROR instance/beat.go:691 Exiting: error initializing publisher: file permissions must be more strict (required permissions: -rw-------, actual permissions: -rw-rw-rw-)
`

For confirmed bugs, please report:
- Version: 6.3.1
- Operating System: Windows 10
- Discuss Forum URL: https://discuss.elastic.co/t/metricbeat-fail-safe-over-function-on-output/142466
- Steps to Reproduce: 
- Workaround:
  - Set `queue.spool.file.permissions: 0777` (probably 0666 would work too).

**Comment by andrewkroh** [comment]
The error would be better it mentioned that it was related to disk spooling and if it included the path to the file that failed the permission check.

**Comment by ph** [comment]
cc @urso since you are working on the error handling refactoring.
