### ISSUE TITLE
[Auditbeat] Support Pkg Reconciliation

### ISSUE THREAD

**Issue by ndubss** [elastic/beats#7862]
Hello, for file integrity monitoring, depending on your environment, there can be tons of changes that create noise. The biggest task is trying to identify the authorized vs unauthorized. It would be awesome if some of this logic could be worked into auditbeat. Essentially, try to identify the changes coming management systems, whether puppet, chef, salt. We are going to leverage auditd command execution events to provide us this context for now. Identifying the source user of fim changes (again w/o auditd) could make solving this problem easier, as well..

**Comment by strawgate** [comment]
Something that would help with this would be digital signature detection for files in addition to hash

**Comment by nickwedlake** [comment]
Agree, signatures would really help with this equation.

**Comment by cwurm** [comment]
On Linux, we use `inotify` to capture changes which does not tell us which user or process is responsible for the change. I'm not sure if there's another way to learn that apart from the audit framework.

I'm curious about digital signatures - what does that usually look like when using deployment automation tools such as puppet?

**Comment by strawgate** [comment]
I dont think you'd feed the hashes from Puppet or Ansible into Auditbeat or Elasticsearch, more likely you'd include whether the file is digitally signed and whether that signature is valid.

Then you'd largely just exclude file change events of files from trusted vendors and focus on unsigned items or items from untrusted vendors.

**Comment by andrewkroh** [comment]
I could see integrating data from package managers. Like checking if the file is owned by a package (e.g. `rpm -qf file`) and then checking if that package was signed and still verifies (`rpm -v`).

**Comment by nickwedlake** [comment]
Yea signing would probably be the best solution. I’m not sure how well rpms are signed today. In this type of use case, you would probably want to resign all the rpms, with your pki anyways.
