### ISSUE TITLE
[Winlogbeat] Clarify need to escape `\` character in YAML config and that unescaped `/` can be used in its place

### ISSUE THREAD

**Issue by bczifra** [elastic/beats#7870]
The `registry_file` documentation for Winlogbeat indicates:
> The forward slashes (/) in the path are automatically changed to backslashes (\) for Windows compatibility. You can use either forward or backslashes. Forward slashes are easier to work with in YAML because there is no need to escape them.

However, this isn't made clear for other settings that also require paths, such as [certificate](https://www.elastic.co/guide/en/beats/winlogbeat/6.3/configuration-ssl.html#certificate).

This should be easily discernible for any setting that requires a path.

**Comment by urso** [comment]
YAML has different string types. For regular expressions and file paths it is better to use single quotes like `path: 'C:\abc\def\file.txt'`. Single quotes are not subject to string escaping. This is also mentioned in the config file format FAQ: https://www.elastic.co/guide/en/beats/libbeat/current/config-file-format-tips.html#wrap-paths-in-quotes
