### ISSUE TITLE
Deprecated LS/redis ports followup

### ISSUE THREAD

**Issue by urso** [elastic/beats#7881]
The ports setting in the Logstash/Redis output has been deprecated in 5.0. But in the documentation only.

In the 6.x release cycle:
- change Logstash default port number to 5044 (this port is commonly used in docs and by users)
- print a 'deprecated' warning in Logstash/Redis output if `port` is used
- add deprecated notice to reference configs

For 7.0:
- remove ports setting from docs, reference configs and code

**Comment by kvch** [comment]
This issue has been resolved.
