### ISSUE TITLE
The default Mysqlslowlog template is not supported on mysql 5.7.22

### ISSUE THREAD

**Issue by philiahe** [elastic/beats#7892]
**mysql 5.7.22 slowlog**

```
# Time: 2018-08-07T16:27:47.169604+08:00
# User@Host: root[root] @  [218.76.8.37]  Id:  7234
# Query_time: 15.000223  Lock_time: 0.000000 Rows_sent: 1  Rows_examined: 0
SET timestamp=1533630467;
select sleep(15)
```

**Test use default grok**
![image](https://user-images.githubusercontent.com/8486693/43764198-5f3c0fb2-9a5f-11e8-9e5b-0c0e1f57ee30.png)

**Comment by chenjianbin** [comment]
I have the same problem,a slow log event will be split into two events.
one is:  # Time: 2018-08-07T16:27:47.169604+08:00
the other is:  # User@Host: root[root] @  [218.76.8.37]  Id:  7234
                      # Query_time: 15.000223  Lock_time: 0.000000 Rows_sent: 1  Rows_examined: 0
                      SET timestamp=1533630467;
                      select sleep(15)

**Comment by chenjianbin** [comment]
I am experiencing the same problem in filebeat mysql slowlog module ,a slow log event will be split into two events.
one is: # Time: 2018-08-07T16:27:47.169604+08:00
the other is: # User@Host: root[root] @ [218.76.8.37] Id: 7234
# Query_time: 15.000223 Lock_time: 0.000000 Rows_sent: 1 Rows_examined: 0
SET timestamp=1533630467;
select sleep(15)

**Comment by chenjianbin** [comment]
I am experiencing the same problem in filebeat mysql slowlog module ,a slow log event will be split into two events.
one is: 
# Time: 2018-08-07T16:27:47.169604+08:00
the other is: 
# User@Host: root[root] @ [218.76.8.37] Id: 7234
# Query_time: 15.000223 Lock_time: 0.000000 Rows_sent: 1 Rows_examined: 0
SET timestamp=1533630467;
select sleep(15)

**Comment by chenjianbin** [comment]
I am experiencing the same problem in filebeat mysql slowlog module ,a slow log event will be split into two events.
one is: 
  # Time: 2018-08-07T16:27:47.169604+08:00
the other is: 
  # User@Host: root[root] @ [218.76.8.37] Id: 7234
  # Query_time: 15.000223 Lock_time: 0.000000 Rows_sent: 1 Rows_examined: 0
  SET timestamp=1533630467;
  select sleep(15)

**Comment by chenjianbin** [comment]
I am experiencing the same problem in filebeat mysql slowlog module ,a slow log event will be split into two events.
one is: 
```
  # Time: 2018-08-07T16:27:47.169604+08:00
```
the other is: 
```
  # User@Host: root[root] @ [218.76.8.37] Id: 7234
  # Query_time: 15.000223 Lock_time: 0.000000 Rows_sent: 1 Rows_examined: 0
  SET timestamp=1533630467;
  select sleep(15)
```
