### ISSUE TITLE
Replace _xpack ES API endpoints with new bridge APIs

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#7909]
Sometime in 7.x, the Elasticsearch team is planning on deprecating all REST API endpoints starting with `_xpack` and offering alternative bridge API endpoints instead. For example, `_ml` instead of `_xpack/ml`. In 8.0, the REST API endpoints starting with `_xpack` will be removed entirely.

This issue is to track updating any Beats code that uses ES REST API endpoints starting with `_xpack`.

**Note: this change needs to be made for 7.x code only, after ES has made the API changes on their side first.**

**Comment by openmohan** [comment]
I would like to work on this.

**Comment by ruflin** [comment]
@openmohan Thanks for your interest in working on this. I think not all API changes have been made yet in the Elasticsearch team so it's a bid early to tackle this I think.

**Comment by knrt10** [comment]
@ruflin I would like to work on this.

**Comment by ruflin** [comment]
@knrt10 Not sure if you are too early on this one. @ycombinator can comment here.

**Comment by ycombinator** [comment]
These bridge APIs are not yet available in Elasticsearch. I just built a fresh copy of ES from `master` and verified. Removing the `Hacktoberfest` label for now.

**Comment by kanishk98** [comment]
Hello, I'm just getting familiar with the Elastic stack and I think this is a good place to start. @ycombinator is this issue still relevant?

**Comment by ycombinator** [comment]
Apologies for not keeping this issue updated. But it was resolved via https://github.com/elastic/beats/pull/9656.
