### ISSUE TITLE
A panic of dumplicated kafka output 

### ISSUE THREAD

**Issue by yuz11** [elastic/beats#7938]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version: SHA-1: 6fe02a4dfc2de58490270a15affaa0aec0f5f8df
- Operating System: Centos
- Discuss Forum URL: https://discuss.elastic.co/t/a-panic-of-dumplicated-kafka-output/143645
- Steps to Reproduce: Bad situation of network, links broke now and then

**Comment by urso** [comment]
Adding some context from discuss:

```
panic: output type 'kafka' exists already

goroutine 5 [running]:
github.com/elastic/beats/libbeat/outputs.RegisterType(0xe8c100, 0x5, 0xecf2e8)
e:/work_space/Go/src/github.com/elastic/beats/libbeat/outputs/output_reg.go:30 +0x170
github.com/elastic/beats/libbeat/outputs/kafka.init.0.func1() 1
e:/work_space/Go/src/github.com/elastic/beats/libbeat/outputs/kafka/kafka.go:118 +0x11d
created by github.com/elastic/beats/libbeat/outputs/kafka.init.0 1
e:/work_space/Go/src/github.com/elastic/beats/libbeat/outputs/kafka/kafka.go:109 +0x170
```

message from @yuz11:
I may find a problem may lead to my issue... it's in the kafka lib sarama/broker.go
It does not set a readtimeout duraling SASL handshake.
I may block in the io.ReadFull,waiting for response.

**Comment by urso** [comment]
(response from discuss):

The stack trace makes no sense to me. I checked out said commit, but Line 109 is empty and line 118 is a function definition, but no call. The stack-trace also indicates that the second call (namely `func1`) is using a closure. We don't use a closure in the init function.

Have you made any modifications to kafka.go?

In go init is called before the beat actually starts up. The init function for each package is run exactly once. Unless you have a second output or modified the init function to register the output 'lazily' or whatever, then this panic can not occur.

Additional info:
output.RegisterType must be called exactly once by each output type. It registers a constructor for an output, not an instance of a running output. The panic on RegisterType is correctly complaining about an already existing kafka output.

**Comment by kaiyan-sheng** [comment]
No updates on this issue for a year, closing this. Please feel free to open a new issue if you see this behavior again. Thanks!
