### ISSUE TITLE
Filebeat.yml ignoring path.home on Mac OS

### ISSUE THREAD

**Issue by tmotley** [elastic/beats#7947]
I am running Filebeat 6.2.4 on my local Mac OS (High Sierra), installed via Homebrew.

When I run FB, it ignores my path.home declaration in my filebeat.yml file. However, I can verify that yml is being parsed and read, because if I include an error in it, startup fails with appropriate error message. Because of the home path read failure, FB cannot resolve my modules directory and fails.

As a workaround, to get FB to recognize my home path, I have to pass it in as CLI variable.

Here is the location of my yml config file: _/usr/local/etc/filebeat/filebeat.yml_

Below is my path.home variable in that file:

```
path.home: /usr/local/etc/filebeat
```

Here is the startup logs, where you see the incorrect home path reported:

```
filebeat -e
2018-08-09T21:12:49.253-0700	INFO	instance/beat.go:468	Home path: [/usr/local/Cellar/filebeat/6.2.4] Config path: [/usr/local/etc/filebeat] Data path: [/usr/local/var/lib/filebeat] Logs path: [/usr/local/var/log/filebeat]
2018-08-09T21:12:49.254-0700	INFO	instance/beat.go:475	Beat UUID: 2b058feb-772a-4bd1-abd7-4137e2d4bbe3
2018-08-09T21:12:49.254-0700	INFO	instance/beat.go:213	Setup Beat: filebeat; Version: 6.2.4
2018-08-09T21:12:49.255-0700	INFO	elasticsearch/client.go:145	Elasticsearch url: http://localhost:9200
2018-08-09T21:12:49.256-0700	INFO	pipeline/module.go:76	Beat name: hero-c02rg00ug8wq.lan
2018-08-09T21:12:49.256-0700	ERROR	fileset/modules.go:95	Not loading modules. Module directory not found: /usr/local/Cellar/filebeat/6.2.4/module
```

**Comment by ruflin** [comment]
Could you share your full filebeat.yml file here?

**Comment by tmotley** [comment]
I shall try attaching directly on github...

**Comment by tmotley** [comment]
[filebeat.yml.txt](https://github.com/elastic/beats/files/2290648/filebeat.yml.txt)

**Comment by tmotley** [comment]
@ruflin  - I had to change the file extension to .txt, and Github would accept it. Thanks.

**Comment by ruflin** [comment]
I think it potentially now understand the issue. The `filebeat` that you call contains something like this:

```
exec /usr/local/Cellar/filebeat/6.2.4/libexec/bin/filebeat         --path.config /usr/local/etc/filebeat         --path.data /usr/local/var/lib/filebeat         --path.home /usr/local/Cellar/filebeat/6.2.4         --path.logs /usr/local/var/log/filebeat         "$@"
```

As the command line flag overloads the config setting it in the config will not work. A workaround for this would be to call the filebeat binary directly.

**Comment by joyoungzhang** [comment]
I just tried this out on my mac and was able to reproduce it.
filebeat version is 6.2.4

**Comment by imvkmark** [comment]
I copy file from `/usr/local/etc/filebeat/module` to folder `/usr/local/Cellar/filebeat/6.2.4/`, the question resolved. 

![image](https://user-images.githubusercontent.com/150127/53561308-77eba100-3b89-11e9-947b-156f948aa612.png)

**Comment by tmotley** [comment]
> I think it potentially now understand the issue. The `filebeat` that you call contains something like this:
> 
> ```
> exec /usr/local/Cellar/filebeat/6.2.4/libexec/bin/filebeat         --path.config /usr/local/etc/filebeat         --path.data /usr/local/var/lib/filebeat         --path.home /usr/local/Cellar/filebeat/6.2.4         --path.logs /usr/local/var/log/filebeat         "$@"
> ```
> 
> As the command line flag overloads the config setting it in the config will not work. A workaround for this would be to call the filebeat binary directly.

Thanks @ruflin  - this is/was the problem.  The Homebrew installation of Filebeat is setting the --path.home explicitly in the run script, so my command line override would be masked by that. I adjusted Homebrew exec script and Filebeat can now see my Modules dir.

**Comment by tmotley** [comment]
Closed as the problem lies with the Homebrew exec script, and not a bug in Filebeat.

**Comment by petervandenabeele** [comment]
The workaround I am using is to add this symlink from the Cellar dir to /usr/loca/etc/ context:

```
➜  6.2.4 pwd
/usr/local/Cellar/filebeat/6.2.4
➜  6.2.4 ln -s /usr/local/etc/filebeat/module
➜  6.2.4 ls -dl module
lrwxr-xr-x  1 peter_v  staff  30 Jul 16 13:42 module -> /usr/local/etc/filebeat/module
```
