### ISSUE TITLE
Packetbeat's visualize  Top 10 HTTP requests issue

### ISSUE THREAD

**Issue by yekeqiang** [elastic/beats#797]
when i use Packetbeat’s visualize, I met this problem， the Top 10 HTTP requests is not accurate，
in my index, the field "query" is like this:

```
GET /api/oauth/permission/check_permission
```
<img width="758" alt="p1" src="https://cloud.githubusercontent.com/assets/2832031/12473033/49689996-c049-11e5-9b2e-14595b736852.png">

but the "Top 10 HTTP requests"  field "query" is not right,in the visualize the field "query" became "/api" and "check_permission"，not "GET /api/oauth/permission/check_permission"

<img width="560" alt="p2" src="https://cloud.githubusercontent.com/assets/2832031/12473043/59e9db7c-c049-11e5-8a83-f0677df9aed5.png">

how can i fix it

**Comment by monicasarbu** [comment]
Similar with: https://discuss.elastic.co/t/packetbeats-dashboard-issue/39724

**Comment by yekeqiang** [comment]
@monicasarbu i have fix it, because i forget load the pecketbeats template, ths
