### ISSUE TITLE
[Packetbeat] - Monitor SSH key exchanges

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#7970]
As a user I'd like to be able to audit the SSH traffic in and out of my network to ensure that only approved encryption and MAC algorithms are used.

A common requirement is to only use SSHv2 with FIPS 140-2-approved MACs and ciphers (e.g. hmac-sha2-256/hmac-sha2-512 and aes128-ctr/aes192-ctr/aes256-ctr).

RHEL7 STIG refs:
- https://www.stigviewer.com/stig/red_hat_enterprise_linux_7/2017-12-14/finding/V-72253
- https://www.stigviewer.com/stig/red_hat_enterprise_linux_7/2017-12-14/finding/V-72221

Passively Packetbeat should be able to capture for SSHv2 traffic:
- Client and server SSH versions
- Algorithms supported by both the client and server

**Comment by 0x4D31** [comment]
@andrewkroh Looking forward to this. And then I can help adding support for HASSH (https://github.com/salesforce/hassh).
