### ISSUE TITLE
[Metricbeat] TestReadService in service_integration_windows_test fails

### ISSUE THREAD

**Issue by kvch** [elastic/beats#7977]
`TestReadService` unit test fails on Windows.
Jenkins: https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-windows/6087/beat=metricbeat,label=windows/testReport/junit/(root)/service/TestReadService/

```
Package: github.com/elastic/beats/metricbeat/module/windows/service
Test:    TestReadService
assertions.go:247:
Error: go test failed: 1 test failures

   Error Trace:    service_integration_windows_test.go:79

   Error:          Not equal:

                   expected: 0x0

                   actual  : 0x5e4

   Test:           TestReadService
assertions.go:247:

   Error Trace:    service_integration_windows_test.go:81

   Error:          Not equal:

                   expected: "Stopped"

                   actual  : "Running"

   Test:           TestReadService
```

**Comment by andrewkroh** [comment]
The first step here should be to add more detail to the failure messages so we can understand what services are causing the failures. 

It could some kind of on-demand service that is stopping and starting in between the period in which we collect the data via Windows APIs and the time when we verify that against what WMI reports for each service.

**Comment by narph** [comment]
fixed with https://github.com/elastic/beats/pull/11662
