### ISSUE TITLE
Basic telemetry for Beats central configuration

### ISSUE THREAD

**Issue by tbragin** [elastic/beats#7979]
When we ship the Beats central configuration issue, we should track basic telemetry metrics around usage, to help us improve the feature going forward.

Initial idea is to add number of Beats enrolled with central management, split up by type of Beat. This could serve as a basic measure of adoption.

Down the road, we should discuss other metrics that might be a good measure of ongoing engagement, such as # of configuration changes tracked over time, etc..

cc: @ruflin @exekias @mattapperson

**Comment by yaronp68** [comment]
@tbragin I have few more suggestions for telemetry KPIs:
- Count by module
- Count by OS: Linux / Windows
- Is deployed over K8S
- Number of tags applied - gives information about the way management profiles are used and potentially how many different deployments /apps

**Comment by exekias** [comment]
Sounds like adding a flag telling if the beat is enrolled should do most of the job, as the rest of things (for instance modules) would be reported by telemetry already.

Number of tags is an interesting one too :+1:

**Comment by exekias** [comment]
Just opened https://github.com/elastic/beats/pull/8671 to tackle this
