### ISSUE TITLE
[Kafka] processors config 

### ISSUE THREAD

**Issue by InspurKelly** [elastic/beats#7985]
Hi,
I use metricbeat collecting kafka metrics, i want to filter data when  kafka.partition.partition.leader not equals kafka.partition.partition.replica,

metricbeat.modules:
- module: kafka
  name: "kafka"
  metricsets: ["consumergroup", "partition"]
  period: 10s
  hosts: ["********"]
  enabled: true
  processors:
  - drop_event.when.not.equals: 
      kafka.partition.partition.leader: kafka.partition.partition.replica

How do I configure it?

**Comment by ruflin** [comment]
Hi @InspurKelly 

For questions please use our discuss forum: https://discuss.elastic.co/c/beats/metricbeat
