### ISSUE TITLE
make docs does not work if GOPATH not set

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#7989]
Since Go 1.8 a GOPATH is set by default to `$HOME/go`. Our `build_docs.sh` script relies on at least one GOPATH to be set: https://github.com/elastic/beats/blob/master/script/build_docs.sh#L20

In case no GOPATH is set it should fall back to the default.

**Comment by graphaelli** [comment]
you could use `${GOPATH:-$(go env GOPATH)}`
