### ISSUE TITLE
[libbeat] crashes when the eventMap contains an implementation of type *encoding.TextMarshaler and value nil

### ISSUE THREAD

**Issue by cyrilleverrier** [elastic/beats#7998]
Version: libbeat any version (tested against mater 264e7b428389e73246deaf05913f274cf6fd5e2b)

**Steps to reproduce**

```
var completed *time.Time // not yet completed
event := common.MapStr{
    "date.completed": completed
}
esclient.Publish(event)
```

**Expected result**

The `date.completed` field is dropped similar to other nil pointers

**Actual result**
```
panic: value method time.Time.MarshalText called using nil *Time pointer [recovered]
        panic: value method time.Time.MarshalText called using nil *Time pointer
```

**Reason:**
`time.Time` implements `encoding.TextMarshaler`. therefore it goes to a specific case that doesn't check for nil values

**Comment by cyrilleverrier** [comment]
PR #7998: ignore event fields that contains a nil interface of type encoding.TextMarshaler

**Comment by ruflin** [comment]
@cyrilleverrier Thanks for the PR and welcome back ;-)
