### ISSUE TITLE
syslog input plugin don't extract fields correctly

### ISSUE THREAD

**Issue by benkeil** [elastic/beats#8017]
For confirmed bugs, please report:
- Version: 6.3.2
- Operating System: Docker, Kubernetes

We send our nginx logs via syslog to filebeat with an son body and it's impossible to parse the message, because the message contains not only the son body from nginx.

```json
"message": "mls-8dc4c8d-mxnlv mls_nginx_access: {\"remote_addr\":\"192.168.99.1\",\"remote_user\":\"\",\"time_iso8601\":\"2018-08-18T00:34:22+02:00\",\"msec\":\"1534545262.743\",\"request_method\":\"GET\",\"server_protocol\":\"HTTP/1.1\",\"http_host\":\"mls.mls.local.dev.de\",\"request_uri\":\"/health/status\",\"uri\":\"/health/status/index.php\",\"query_string\":\"\",\"status\":\"200\",\"body_bytes_sent\":\"140\",\"http_referer\":\"\",\"http_user_agent\":\"curl/7.54.0\",\"http_x_forwarded_for\":\"192.168.99.1\",\"request_time\":\"0.439\",\"upstream_connect_time\":\"0.002\",\"sedo_request_id\":\"3485d51c91e5457129977514892045a6\"}",
```

Why the host and facility not added to top level fields, so I can convert the message with the son decide plugin?

**Comment by ruflin** [comment]
Hi @benkeil 

We are trying to keep Github reserved for confirmed bugs. Could you open a topic here: https://discuss.elastic.co/c/beats/filebeat 

Please also share there the exact config you are using. Also what do you mean by `son body`? `json body`? Let's continue the discussion on discuss.
