### ISSUE TITLE
PostgreSQL module documentation - Minimum privileges required

### ISSUE THREAD

**Issue by StephenGoodall** [elastic/beats#8033]
It would be great to have something in the documentation that shows the minimum privileges the Postgres user will need in order to collect the metrics.

Similar to this Oracle plugin documentation for New Relic:
https://www.sparkred.com/confluence/display/NEWRELIC/Oracle+Database+Plugin#OracleDatabasePlugin-SystemUsers

**Comment by Leaf-Lin** [comment]
This is related to the following discussions too:
- https://discuss.elastic.co/t/postgresql-module-cannot-connect/220916
- https://discuss.elastic.co/t/unable-to-get-data-by-using-postgresql-module-of-metricbeat-7-6-2/229422/3

It would be great to add something into https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-postgresql.html to include what's the required `POSTGRES_HOST_AUTH_METHOD` method and what's the compatible `pg_hba.conf` connection method.

**Comment by adamkozuch** [comment]
Hi Team, Could I work on that?
