### ISSUE TITLE
Kubernetes Metricbeat manifest references docker image which does not exist

### ISSUE THREAD

**Issue by kierenj** [elastic/beats#8034]
The manifest uses

`docker.elastic.co/beats/metricbeat:7.0.0-alpha1`

...which does not exist.  I'm following the docs/guidance/conf video which all suggest to use the manifest here.  I'm guessing this is just out of date?

**Comment by exekias** [comment]
Hi @kierenj,

You are probably following master docs, which talk about an unreleased version. You should follow the guide for latest released version: https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-kubernetes.html

**Comment by kierenj** [comment]
Hi exekias, I just followed the link given in the video ,  go.es.io/beats-k8s .  Maybe worth redirecting that link, or adding something to the readme?

**Comment by kierenj** [comment]
(Thank you, btw!:))

**Comment by exekias** [comment]
Do you have a link to the video? I'm not sure which one are we talking about :innocent:

**Comment by exekias** [comment]
@DanRoscigno I realize now maybe you created that link, can you have a look? If possible I would change it from `master` to `current`

**Comment by DanRoscigno** [comment]
I can find the reference to docker.elastic.co/beats/metricbeat:7.0.0-alpha1 in the master Metricbeat docs, but I do not know which video is the "conf video".  @kierenj can you please give the URL for the conf video so we can fix that?  We can't point master to current, but we can add a note to the video.

**Comment by kierenj** [comment]
https://www.elastic.co/elasticon/conf/2018/sf/kubernetes-docker-and-containers-at-elastic-monitoring-logging-and-more

**Comment by DanRoscigno** [comment]
Thanks @kierenj .  @exekias this is the session that you and Tyler hosted at Elastic{ON} 2018.  At 31 minutes Tyler talks about using the default manifests from Github, and again at 38 minutes.

I think this is what we need:

 - Have a "current" set of manifests
 - Edit the [main README](https://github.com/elastic/beats/blob/master/deploy/kubernetes/README.md) to point to the current README for Filebeat and Metricbeat manifests instead of master

**Comment by exekias** [comment]
@tylerjl any chance we can update that link (`go.es.io/beats-k8s`) to point to `https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-kubernetes.html`?

**Comment by tylerjl** [comment]
@exekias unfortunately, it looks like I can't change a bit.ly shortcut after creating it 😕 That's my bad for not pointing the link at a permalink instead of simple GitHub URL.

**Comment by exekias** [comment]
ok no worries!, I think we can live with that, will check if I can add a note to master, explaining it won't work there
