### ISSUE TITLE
"[Metricbeat Kubernetes] Overview" dashboard on Kibana shows 0 nodes, 0 deployments, but gives node stats

### ISSUE THREAD

**Issue by kierenj** [elastic/beats#8039]
As per video.  Version 6.3.2.

https://kierenj.tinytake.com/sf/Mjg1NTQ0Nl84NTcxODg0

For the "Kubernetes - Nodes" visualisation, `kubernetes.node.name` is not set anywhere.  Likewise for "Kubernetes - Deployments", `kubernetes.deployment.name` is not set either.

I'm using the stock manifest, stock index template and stock dashboard.  I feel like this dashboard should be fully populated?

Let me know if I can provide any other info to help.

**Comment by exekias** [comment]
Hi @kierenj, it looks like `kube-sate-metrics` is not available? You can follow the instructions here for info on how to deploy it: https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-kubernetes.html

Please use https://discuss.elastic.co/c/beats for questions, we try to keep Github issues for confirmed bugs :slightly_smiling_face:
