### ISSUE TITLE
[Auditbeat] Map file changes to users in FIM module

### ISSUE THREAD

**Issue by ndubss** [elastic/beats#8042]
In Auditbeat, specifically for FIM events, it would be nice to have user information about who made each specific change. We are looking at the context given from auditd, with primary and secondary actors, which is extremely useful. It would be great to get this same level of data, without having a dependency on auditd. I don't believe any open source FIMs do this today.

**Comment by SHolzhauer** [comment]
Together with #7860 this would greatly improve FIM. Seeing *who* changed *what* is extremely usefull during SIEM/SOC analysis and a bit lacking at this time i.m.o.
