### ISSUE TITLE
How can we use journald as input type in filebeat ? 

### ISSUE THREAD

**Issue by jain108shubhamtbt** [elastic/beats#8060]
How can we use journald as input type in filebeat ? Please help me .

**Comment by exekias** [comment]
This is not supported yet, although it's planned to be implemented in the future, you can subscribe to this issue for updates: https://github.com/elastic/beats/issues/7955

**Comment by jain108shubhamtbt** [comment]
@exekias, may i know, in which version of filebeat introduce journald ?

can we use any alternate for journald ?

**Comment by exekias** [comment]
We don't know when this will be introduced. As an alternative, there is a community project (not supported by us) that seems to support journald: https://github.com/mheese/journalbeat

**Comment by jain108shubhamtbt** [comment]
can we make build of journalbeat without docker ?
