### ISSUE TITLE
Make the Beat scripts more generic to be used by all Beats

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#807]
It would be nice if all the beats will use the same scripts for generating docs and template, so we don't have a `scripts` directory in each Beat. We can store them in `libbeat`, so everyone can make use of them.

The question is if the new beat creators would make use of these scripts:
Generating the documentation might be not that useful for the community building beats, but the template generator can be handful. To generate the template, you need to create etc/fields.yml first.I am wondering what would be easier to write the etc/fields.yml or write directly the Beat template.

**Comment by ruflin** [comment]
I think in any case we should unify the scripts as it makes maintenance much easier for us. I already merged the system-test scripts and also wanted to "briefly" merge these scripts, but realised the all have small but subtle differences.

If we have it unified we can make it available in the template and see if people make use of it. Interestingly when I look at the community beats, most have the script folder. Not sure if they also make use of it (I assume some).

+1 on moving forward.

**Comment by mrkschan** [comment]
May I ask if update.sh can manage part of `etc/fields.yml` as well? There're some fields emitted from libbeat which I don't want to update them manually for ES index template and docs.

**Comment by ruflin** [comment]
@mrkschan I like the idea of `make update` also bringing this up-to-date. See also https://github.com/elastic/beats/issues/820

What do you mean emitted? You mean the script does not catch them?

**Comment by mrkschan** [comment]
@ruflin I just mean libbeat would add fields to the event emitted, e.g. uuid, shipper, etc. These fields would need to be put onto `etc/fields.yml`.

**Comment by ruflin** [comment]
@mrkschan Got it. Good idea, this would be a similar behaviour to the way the config file is generated.

**Comment by ruflin** [comment]
On the master branch there is now only one script directory left and also available in beat-generator. Closing this issue.
