### ISSUE TITLE
Event publishing improvements

### ISSUE THREAD

**Issue by urso** [elastic/beats#8080]
While event publishing is tailored for the standard Beats, we identified a few improvements to event publishing, which will benefit apm-server:

### 1. Composable PublishMode 

Change beat.PublishMode, so settings can be combined. And support for `DropIfFull | GuaranteedSend`. If both flags are configured, an event will be dropped if the queue is full, but once an event is scheduled, it is guaranteed to be delivered until the output returned an ACK

### 2. Support to disable event cancelling

Option to disable 'Cancel' on published events. When closing `beat.Client` instance, the client will forward a cancel signal. A cancel signal might remove unscheduled events from queue (non-deterministic). Add an option (or re-use PublishMode flag) to disable cancelling on close.

### 3. Better semantics for DropIfFull

Improve 'DropIfFull' support in memory/spool queues. Both queue types use a broker, with a small work-queue. Right now `DropIfFull` might lead to event drops, even if the queue is not full. The event drops happen due to the broker being busy with other management tasks and the work-queue being filled up.
=> Update producer to block with timeout if `DropIfFull` is set, but queue is known not to be full (some atomic flag will be required). We still must guarantee progress with small waiting times. Therefore we will introduce a Timeout setting, which is effective only if `DropIfFull` is set:
- if queue is marked as full -> drop event
- if queue is not marked as full:
  - `timeout < 0`: block until publish request can progress, only if queue is known not to be full
  - `timeout = 0`: do not block if channel is full
  - `timeout > 0`: block with timeout on broker channel

In packetbeat we will use a timeout of  0. Internally `apm-server` implements a queue with timeout of 1s.

### 4. Publish return value

Publish does not return any value. Before scheduling an event, the event can be dropped/failing due to processors or 'DropIfFull'. So to inform the caller what happened to the event (best effort, event can still be dropped by output) we will return a signal (enumeration) like:

```
type PublishInfo uint8

const (
  EventScheduled PublishInfo = iota
  EventFiltered  // removed by processor
  EventError     // some processor errored on the event
  EventDropped   // event has been dropped due to DropIfFull
)
```

Progress:
- [ ] 1. Composable PublishMode 
- [ ] 2. Support to disable event cancelling
- [ ] 3. Better semantics for DropIfFull
- [ ] 4. Publish return value

**Comment by adriansr** [comment]
@urso I'm currently working on a Packetbeat case where it took me a while to realize that packets weren't lost by Packetbeat but that they were being dropped due to the small (20) work queue in broker being full even though the mem.queue was almost empty.

Due to this small work queue, DropIfFull reacts poorly to small bursts of events and the solution proposed in here could have fixed the problem (with a timeout different than zero for Packetbeat). Is there a reason why this issue was closed? Are there other plans to improve this?
