### ISSUE TITLE
Move content about configuring security to the guides for each beat

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#809]
@elastic/beats We currently have the following topic in the Beats Platform Reference, and it’s duplicated in the Packetbeat reference (https://www.elastic.co/guide/en/beats/libbeat/current/_https_and_basic_authentication.html).  I want to include the content in all the guides (because it's beat-specific configuration information), and remove it from the Platform Reference.  I’ll use asciidoc include tags to pull the content from libbeat so that we aren’t duplicating the content. Let me know if you have any issues with the change. I probably should have moved this when I restructured the config options.

**Comment by andrewkroh** [comment]
SGTM
