### ISSUE TITLE
[Metricbeat] modules.d installed to wrong location

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#8104]
In 6.4.0 the .deb and .rpm packages install the modules.d directory to `/usr/share/metricbeat/modules.d` but they are expected to be at `/etc/metricbeat/modules.d`.

As a workaround you can copy or move the files. Or you can tell metricbeat to look in the /usr with`metricbeat.config.modules.path: '${path.home}/modules.d/*.yml'`. You can test if that works with `metricbeat modules list`.

**Comment by tsg** [comment]
The good news is that this doesn't seem to affect upgrades (because the old `modules.d` folder is still in place), only new installations. I tested the following command and seems to do the trick, as a workaround:

```
sudo cp -r /usr/share/metricbeat/modules.d /etc/metricbeat/
```
