### ISSUE TITLE
Dissect: tag events when a parse failure occur

### ISSUE THREAD

**Issue by ph** [elastic/beats#8123]
Currently, we only log a debug message when a parse failure occurs inside dissect, for future processing and development of Dissect patterns we should instead tag an event with some sort of failure. Doing so will allow us to filter the problematic events in Kibana and update our configuration.

The above scenario is exactly what Logstash is doing for dissect and also grok.

**Comment by ruflin** [comment]
I like the idea to have such `tags` for things that happen during the processing. Any suggestion on the field these should go int? `processor.tags`, `error.tags`, `error.meta`, `processor.status`, ...?
