### ISSUE TITLE
Metricbeat dashboard top CPU does not account for cores

### ISSUE THREAD

**Issue by mbrancato** [elastic/beats#8174]
In the Metricbeat dashboards, the CPU usage is for a single core. This leads to CPU usages > 100% in the top hosts by CPU visualization.

I fixed this by adding a Math section and dividing by the system.cpu.cores value.

- Version: 6.3.2

**Comment by ruflin** [comment]
There is also an entry `system.cpu.total.norm.pct` which contains the normalised percentage value and already did the calculation for you.

It's an ongoing discussion which one should be shown by default. Could you share some background why you prefer one over the other?

**Comment by mbrancato** [comment]
@ruflin I tried teh `system.cpu.total.norm.pct` and all the graph showed was 0%, but the bar graph were not ordered and were different lengths.
![image](https://user-images.githubusercontent.com/8493275/45768745-c294e480-bc0b-11e8-866c-e1b10c457e5f.png)

I'm leaving our math  section in place. To answer your question, showing overall CPU is a better display for this graph which attempts to show hosts using the most CPU. I think it better serves the dashboard to show the overall CPU usage, not just the first core. If you want to not average, what I would do is find a different way to visualize all the cores, not a bar graph. Something that shows max, min, and mean/median core usage... I sound like I'm describing a box plot, but I don't mean to suggest that.

**Comment by mbrancato** [comment]
@willemdh except with 6.3.2 it seems `system.cpu.total.norm.pct` is always showing 0%. But yes, showing overall CPU is much more useful than summing all the CPU core percentages.

**Comment by DPattee** [comment]
Agreed on showing normalized by default. 

When I'm viewing information directly on a single system I want the real 'non-normalized' information since it is a higher resolution / more meaningful data point. But when I am comparing multiple servers of a single service type that may have different physical core or vcpu assignments (i.e. a set of web servers on physical hardware of slightly different generations so maybe 8 and 12 cores) I want to be able to quickly see which machines are overtaxed and need upgrading.

**Comment by kaiyan-sheng** [comment]
Great suggestions, thank you! I will keep this issue open for these potential changes.
> Looks like the default changes I'd want to see would be:
> in system.yml= cpu.metrics: [percentages, normalized_percentages]
> in top hosts by cpu (realtime) [metricbeat system] = switch to system.cpu.user.norm.pct
> in hosts histogram by cpu usage [metricbeat system] = switch to system.cpu.user.norm.pct

**Comment by FreerideTheWorld** [comment]
After seeing the "Top Hosts by CPU" visualization hit ovdef 1100% during testing yesterday I'd like to see this visualization fixed as well.  I had to go into the server and look at how many cores it had, 32, and start doing some mental math.  I don't really see how showing a customer 1100% makes this visualization useful and only puts more work on my plate.

**Comment by nelsomd** [comment]
Im on version 7.10.1 and this is till an issue. I have some CPUs showing over 100%.  Is there a plan to resolve this or do some background math so it makes sense?

**Comment by kaiyan-sheng** [comment]
@fearful-symmetry Maybe we discussed this before, do you know if we are planning to switch to displaying normalized cpu in visualization?

**Comment by fearful-symmetry** [comment]
In theory it feels like we should be using normalized percentages, and the choice to _not_ use them seems odd enough that I wonder if we had some kind of reasoning for it. I'm gonna try and run some tests to see if swapping over to `norm` breaks anything, since this could be an easy fix, assuming we consider it to not be a breaking change.

**Comment by DPattee** [comment]
FWIW I updated the chart in my dashboard back when this first came up, and the heatmap has been displayed correctly through multiple updates of beats.

**Comment by fearful-symmetry** [comment]
I've merged a fix to use `norm.pct` in the system integrations package, that should be reflected in the package repos soon.

**Comment by nugroho-expereo** [comment]
@fearful-symmetry I have updated integration to the latest version, It looks good for the System Overview but for the Host Overview Dashboard the CPU gauge calculation does not seems right.

When I check the calculation it shows: (system.norm + user.norm)/cores

Why the normalized value need to be divided again by cores?

![image](https://user-images.githubusercontent.com/35025861/128314986-09829bef-0d14-42de-ac7d-bba14ec9c344.png)

**Comment by fearful-symmetry** [comment]
That's...probably a bug. Lemme look.

**Comment by fearful-symmetry** [comment]
Sorry for the delayed update: A fix is currently in the snapshot for integrations, and is being promoted to staging now.
