### ISSUE TITLE
Topbeat: Very high CPU when cluster recovers from red

### ISSUE THREAD

**Issue by oazabir** [elastic/beats#819]
My ES cluster went mad, I had to restart. It remained red for quite some time and the topbeat index was unavailable. When it did come back, I saw topbeat processes in all the servers consume very high CPU:

![image](https://cloud.githubusercontent.com/assets/1611494/12517167/681504c0-c129-11e5-9429-7fadcb1f5d96.png)

**Comment by oazabir** [comment]
Also the memory has gone very high as well:

![image](https://cloud.githubusercontent.com/assets/1611494/12517228/a198ebd0-c129-11e5-8d86-6ed1b12e69ca.png)

**Comment by tsg** [comment]
What topbeat version do you have? There used to be an issue that could cause high memory usage when Elasticsearch is not available prior to 1.0.1.

**Comment by urso** [comment]
topbeat 1.1 behaves much better regarding memory usage, as buffering is much more constrained by then.

Having accumulated this much space in memory I wonder how many events are hanging in buffers. Problem is, when ES comes up, topbeat will process, encode and forward all buffered events. CPU usage seems to point downwards and topbeat should stabilize after some time.

**Comment by oazabir** [comment]
Topbeat is now stuck at a certain CPU for a long time, and not going back to its usual usage. I am using 1.0.1. 

![image](https://cloud.githubusercontent.com/assets/1611494/12517931/4a9cf4e4-c12d-11e5-8f15-dcabcb8f0316.png)

**Comment by oazabir** [comment]
Memory is not getting released either.

**Comment by oazabir** [comment]
Is there a way I can configure it not to buffer events?

**Comment by oazabir** [comment]
Picking this up. I was wondering if you had any solution to high memory and memory not getting released. My topbeat process is now running at 380MB on average. Precious RAM for nodes running elasticsearch. Badly need topbeat to release memory and maintain low footprint.

**Comment by urso** [comment]
see my comment from 7 days ago. Have you tried with 1.1 or nightly builds yet?

**Comment by oazabir** [comment]
Haven't tried nightly builds but I am on 1.0.1.

**Comment by monicasarbu** [comment]
@oazabir did you try a newer version of Topbeat? We would love to hear if the problem persists in a newer version of Topbeat.

**Comment by andrewkroh** [comment]
This should be fixed now. I tested with Metricbeat and took ES offline for a bit and brought it back online and there was not high CPU or memory usage.

If you do retest with a newer version and find the issue again please reopen.
