### ISSUE TITLE
[libbeat] Add support for specifying the Linux VRF interface

### ISSUE THREAD

**Issue by pkking** [elastic/beats#8197]
Hi, dear team
       I have some linux boxes seperated by a few vrf networks, is it possible for filebeat to be set up and work with any specific vrf?

**Comment by andrewkroh** [comment]
This is no way of specifying a specific VRF interface to bind to when creating the socket associated with an output connection.

- https://www.kernel.org/doc/Documentation/networking/vrf.txt
- [`syscall.BindToDevice`](https://golang.org/pkg/syscall/#BindToDevice) for setting the `SO_BINDTODEVICE` socket option.
