### ISSUE TITLE
CI should validate fields.yml and fields.asciidoc are in sync

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#820]
I propose we add a check to one of our CI builds that generates each of the `fields.asciidoc` files and then diffs it against the checked in version. If there is a difference, then fail the build.

**Comment by tsg** [comment]
+1

**Comment by ruflin** [comment]
+1 We should do the same for the *beat.yml file.

**Comment by exekias** [comment]
Closing as this is already done
