### ISSUE TITLE
[Auditbeat] Flaky TestRecursive on Windows

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#8208]
[TestRecursive](https://github.com/elastic/beats/blob/980a90f5c3480e4ea29e6bbe40da25376fb80451/auditbeat/module/file_integrity/monitor/monitor_test.go#L75-L115) is failing on Windows [often](https://beats-ci.elastic.co/job/elastic+beats+master+multijob-windows/beat=auditbeat,label=windows/).

```
Unit testing auditbeat
>> go test: Unit Testing
FAILURES:
Package: github.com/elastic/beats/auditbeat/module/file_integrity/monitor
Test:    TestRecursive
monitor_test.go:317: 
		Error Trace:	monitor_test.go:317
		            				monitor_test.go:112
		Error:      	Not equal: 
		            	expected: "C:\\Users\\JENKIN~1.BEA\\AppData\\Local\\Temp\\monitor219775002\\subdir\\file2.txt"
		            	actual  : "C:\\Users\\JENKIN~1.BEA\\AppData\\Local\\Temp\\monitor219775002\\subdir"
		            	Diff:
		            	--- Expected
		            	+++ Actual
		            	@@ -1 +1 @@
		            	-C:\Users\JENKIN~1.BEA\AppData\Local\Temp\monitor219775002\subdir\file2.txt
		            	+C:\Users\JENKIN~1.BEA\AppData\Local\Temp\monitor219775002\subdir
		Test:       	TestRecursive
monitor_test.go:318: 
		Error Trace:	monitor_test.go:318
		            				monitor_test.go:112
		Error:      	Not equal: 
		            	expected: 0x1
		            	actual  : 0x2
		Test:       	TestRecursive
Error: go test failed: 1 test failures
monitor_test.go:333: 
		Error Trace:	monitor_test.go:333
		            				monitor_test.go:112
		Error:      	Not equal: 
		            	expected: 0x4
		            	actual  : 0x1
		Test:       	TestRecursive
----
SUMMARY:
  Fail:     1
  Skip:     4
  Pass:     61
  Packages: 3
  Duration: 8.8701905s
```

Logs: https://beats-ci.elastic.co/job/elastic+beats+master+multijob-windows/12/beat=auditbeat,label=windows/console

**Comment by andrewvc** [comment]
Well, I did take the time to test out one theory in https://github.com/elastic/beats/pull/8317 that turns out to be incorrect. 

 I assumed the root cause was that on win there were two change events, one for the directory, and another for the file.

That appears to not be the case. I won't be able to look at this for at least a few more days, so it'd be good if someone else could tackle this issue since it is so common.
