### ISSUE TITLE
Not able to validate Total Socket Directions using Metricbeat (PLease help)

### ISSUE THREAD

**Issue by mayank-mahajan-guavus** [elastic/beats#8229]
netstat info
# netstat | wc -l
502

and Kibana UI attached.
<img width="1425" alt="kibana ui" src="https://user-images.githubusercontent.com/26953132/45077393-b3417180-b10a-11e8-8e47-da9dfe1d515c.png">

Please help me understand, How Can I validate the information shown by Kibana from System

OS: CentOS 7.x
Kibana: 6.4
ES: 6.4

**Comment by ruflin** [comment]
Hi @mayank-mahajan-guavus 

Please post all questions first on discuss: https://discuss.elastic.co/c/beats/metricbeat. I'm going to close this issue.
