### ISSUE TITLE
filebeat and metricbeat documentation for openshift usage

### ISSUE THREAD

**Issue by mikeh-elastic** [elastic/beats#8253]
Filebeat changes needed to docs for openshift:

update the DaemonSet container spec in the manifest:

        securityContext:
          runAsUser: 0
          privileged:
            true

Run this command to enable the container to be privileged as an administrator for Openshift:

`oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:filebeat`

Metricbeat changes needed to docs for openshift:

update the ConfigMap metricbeat-daemonset-modules manifest to this for the kubernetes module:

       hosts: ["https://${HOSTNAME}:10250"]
       bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
       ssl.certificate_authorities:
         - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt

Run this command to enable the container to be privileged as an administrator for Openshift:

`oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:metricbeat`

**Comment by mikeh-elastic** [comment]
Also for metric beat ClusterRole

add these to resources:

  - nodes/metrics
  - nodes/stats

**Comment by willemdh** [comment]
Hello,

Just wanted to say cool to see other Openshift users using Filebeat / Metricbeat and not Red Hat's fluentd solution. :) 

We tried running the daemonsets a half year ago and stumbled into multiple issues. In the end we switched from using the daemonsets to installing the Beats on all nodes.


For Filebeat, we ran into selinux issues:

We opened a ticket with Red Hat and this was their response:

```
I reproduced the issue and hence could see the same as yours.

But the most important point here is, if you try posting /var/lib/docker/container folder inside a pod then you see the issue of permission denied and it is the same case here when I tried reproducing on my test environment. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sh-4.2# cd /var/lib/docker/containers/06a90b7a57a6bb1b880d00b3d15c44726e8e0af9a67c5575faef9029bd0a8c77/

sh-4.2# ls

config.v2.json   hostconfig.json secrets

sh-4.2# ls -ll

ls: cannot access hostconfig.json: Permission denied

ls: cannot access config.v2.json: Permission denied total 0

-?????????? ? ?   ?    ?           ? config.v2.json

-?????????? ? ?   ?    ?           ? hostconfig.json

drwxr-xr-x. 5 root root 84 Jan 17 16:09 secrets sh-4.2# ls -lZ

ls: cannot access hostconfig.json: Permission denied

ls: cannot access config.v2.json: Permission denied

?--------- ?   ?                                    config.v2.json

?--------- ?   ?                                    hostconfig.json

drwxr-xr-x. root root system_u:object_r:svirt_sandbox_file_t:s0:c1

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Now here, the point is, I had privileged access and still there is permission denied issue on here. This might be because of selinux policy. I checked with my team internally and also found that we do not recommend to mount this '/var/log/docker/container' because of selinux context as they are denying the access to the files having the context 'container_var_lib_t'.

Hence we need to customize the selinux so that the container can access it, but I would not recommend you to do it because if you customise things here, it might let other things down in your Openshift environment.
```

As we just started with Openshift,we followed Red Hat's directions and choose to not customize selinux to prevent other issues.

For Metricbeat we ran into weird issues, casuing kdump service to crash on nodes and other weird disk related issues (df and du unusable for example). The moment we remove the metricbeat daemonset, we are no longer experiencing issues. 
We also opened a Rad Hat ticket and Red Hat also suggested to stop usign the Metricbeat daemonset...

Watching my documentation from half a year ago, the steps we took to install the daemonsets:

Filebeat:

`oadm policy add-scc-to-user hostmount-anyuid system:serviceaccount:kube-system:filebeat`

Metricbeat:

`oadm policy add-scc-to-user hostmount-anyuid system:serviceaccount:kube-system:metricbeat`

Add the service accocunts to the scc privileged:

```
	seLinuxContext:
	  type: RunAsAny
	seccompProfiles:
	- '*'
	supplementalGroups:
	  type: RunAsAny
	users:
        - ..
	- system:serviceaccount:kube-system:filebeat
        - system:serviceaccount:kube-system:metricbeat
```

Grtz

**Comment by jeffspahr** [comment]
@willemdh The filebeat selinux issue can be resolved by adding the following to the pod's securityContext:

```
        securityContext:
          privileged: true
```

**Comment by mikeh-elastic** [comment]
Additionally for openshift daemonsets be sure to set the kube-system namespace or your own custom namespace to allow for scheduling on any node, the default defaultNodeSelector will skip master nodes:

    # oc patch namespace kube-system -p \
    '{"metadata": {"annotations": {"openshift.io/node-selector": ""}}}'

As per https://docs.okd.io/3.10/dev_guide/daemonsets.html
