### ISSUE TITLE
How do I send logs to elastic search which is set up on a VM , from a docker filebeat

### ISSUE THREAD

**Issue by rohitpatwari84** [elastic/beats#8267]
Thhis is my filebeat.yml -

output:
  elasticsearch:
    enabled: true
    hosts:
      - http://<my_external_host_having_elasticsearch_instance>:9200
   # ssl:
    #  certificate_authorities:
     #   - /etc/pki/tls/certs/logstash-beats.crt
    timeout: 15

filebeat:
  prospectors:
    -
      paths:
        - /var/log/vmware-vmsvc.log
        - /var/log/auth.log
      document_type: syslog
    -
      paths:
        - "/var/log/nginx/*.log"
      document_type: nginx-access

**Comment by webmat** [comment]
Usage discussions should be brought up in the forums, at https://discuss.elastic.co, look for the "Beats" section. 

GitHub issues should only be used for confirmed bugs or feature requests.

Thank you!
