### ISSUE TITLE
Feature Request: Filebeat timestamp on docker input

### ISSUE THREAD

**Issue by anandsinghkunwar** [elastic/beats#8279]
In case of docker input, filebeat attaches the @timestamp field from the docker timestamp. I want to capture the time when filebeat actually read this log along with the docker timestamp in a field, say, @filebeattimestamp. The usecase of this could be as a metric to measure filebeat's latency in pumping logs. 

This is a feature request for appending a filebeat timestamp, the name of which could be configurable for docker input. 

This is a reference to the discussion https://discuss.elastic.co/t/filebeat-timestamp-on-docker-input/147686

**Comment by anandsinghkunwar** [comment]
Is there any update to this? @exekias

**Comment by anandsinghkunwar** [comment]
Do we have an update @exekias?

**Comment by exekias** [comment]
I think this is fair. we could fill `event.created` with the current timestamp when the log message is read, according to ECS: https://www.elastic.co/guide/en/ecs/current/ecs-event.html

**Comment by anandsinghkunwar** [comment]
@exekias I can make this change, should I make this just for docker input itself? What do you suggest?
