### ISSUE TITLE
[Auditbeat] Allow flushing of auditd rules

### ISSUE THREAD

**Issue by kholia** [elastic/beats#8280]
Auditbeat doesn't flush auditd rules upon daemon exit. This leads to `/var/log/kern.log` getting flooded with all the audit messages.

Furthermore, it seems that auditbeat doesn't have a CLI option to flush the auditd rules.

It seems that auditd too doesn't flush rules on daemon exit.

```
# systemctl start auditd

# auditctl -l
No rules

# auditctl -a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time_change
# auditctl -l
-a always,exit -F arch=b64 -S adjtimex,settimeofday -F key=time_change

# systemctl stop auditd

# auditctl -l
-a always,exit -F arch=b64 -S adjtimex,settimeofday -F key=time_change
```

If flushing rules on daemon exit is not appropriate, then the auditbeat CLI shoould at least provide a way to flush the rules manually.

Details,

- Version: Auditbeat 6.4.0
- Operating System: Ubuntu 16.04 LTS / 18.04 LTS

**Comment by urso** [comment]
@andrewkroh any idea?

**Comment by andrewkroh** [comment]
I think this would be a good option to add to Auditbeat. And also add a subcommand to clear the rules (#11825).

**Comment by rbabyuk-vs** [comment]
we faced this problem as well, this caused huge problems. I vote for mechanism to flush rules by using AB itself.
