### ISSUE TITLE
Unable to fetch prometheus c++ exporter stats on metricbeat 

### ISSUE THREAD

**Issue by krishan-agrawal-guavus** [elastic/beats#8291]
Prometheus C++ exporter was modified to export our application stats and we planned to export these stats to Metricbeat (and to ElasticSearch) on some remote server.
My issues is that I am able to get Prometheus stats from my Kafka cluster using JMX exporter configuring the correct port details.
However, when using the cpp exporter I have not been able to get these stats into Metricbeat.
Although, when I do request using browser or curl request on configured port, then I can see those stats.

Do I need to take care of any pre-requisites while exporting Prometheus stats using this c++ exporter Or any specific conditions to be met so that metric beat can read and export these stats?

Sample exporter stats:
collector_stats{status="YYY",type="XXX"} 0.000000

**Comment by exekias** [comment]
Hi @krishan-agrawal-guavus we will need some more info in order to debug this issue. Could you share these?:

- Metricbeat settings you are using
- Metricbeat logs when running it
- The full dump you get when manually fetching the metrics from the C++ exporter

Best regards

**Comment by krishan-agrawal-guavus** [comment]
Metric beat settings:
1) Enable prometheus and system stats
2) The output of prometheus.yml:
<- module: prometheus
  #metricsets:
  # - stats
  period: 10s
  hosts: ["localhost:8090"]
  metrics_path: /metrics
  namespace: example1>
The version is 6.4

The logs of metricbeat are attached.
[metricbeat.gz](https://github.com/elastic/beats/files/2377749/metricbeat.gz)
<img width="1436" alt="screen shot 2018-09-13 at 10 36 56 am" src="https://user-images.githubusercontent.com/30039204/45468193-0043ca00-b741-11e8-899a-b585c3800f54.png">



Here are the dump of  metrics from the C++ exporter
<# HELP exposer_bytes_transferred bytesTransferred to metrics services
# TYPE exposer_bytes_transferred counter
exposer_bytes_transferred 17701173.000000
# HELP exposer_total_scrapes Number of times metrics were scraped
# TYPE exposer_total_scrapes counter
exposer_total_scrapes 16166.000000
# HELP exposer_request_latencies Latencies of serving scrape requests, in microseconds
# TYPE exposer_request_latencies summary
exposer_request_latencies_count 16166
exposer_request_latencies_sum 10217747.000000
exposer_request_latencies_quantile{quantile="0.500000"} 531.000000
exposer_request_latencies_quantile{quantile="0.900000"} 582.000000
exposer_request_latencies_quantile{quantile="0.990000"} 631.000000
# HELP collector_stats metrics related to collector
# TYPE collector_stats gauge
collector_stats{status="process",type="EdrFlow"} 1166.000000
collector_stats{status="drop",type="EdrFlow"} 319.000000
# HELP collector_stats metrics related to collector
# TYPE collector_stats gauge
collector_stats{status="process",type="EdrHttp"} 12.000000
collector_stats{status="drop",type="EdrHttp"} 0.000000/>

**Comment by exekias** [comment]
Thanks for the detailed report. From what I see `collector_stats` is somehow duplicated and that's causing the client library to fail when parsing the metrics with this error:
`text format parsing error in line 19: second HELP line for metric name "collector_stats"`

This error is not currently reported but I think we should change that.

**Comment by exekias** [comment]
this module was refactored here: https://github.com/elastic/beats/pull/9948, I think the problem should be gone now, please reopen if you are able to reproduce again with 7.0 (once released)
