### ISSUE TITLE
Create a section about running on containers

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#8305]
Right now, the Filebeat and Metricbeat documentation include several topics that describe how to install and run on containers. For example:

https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html
https://www.elastic.co/guide/en/beats/filebeat/current/running-on-kubernetes.html
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover.html

The Kubernetes and Docker topics appear under the "Setting Up and Running" section. However, because they contain a mix of information (installation, configuration, and run commands), they don't really belong there. I propose that we create a new container at the same level as "Setting Up and Running" that pulls all the topics about running on containers into a single section. This will also make it easier for users to find config info that's important for running on containers (like autodiscover).

**Comment by exekias** [comment]
:+1: this would allow spawning in several sub topics, as right now we are not explaining some basic things, and rely on blog posts

**Comment by dedemorton** [comment]
@exekias Do you have a list of the topics you'd like to see in this section? I'd really like to get the information into the docs where it will get updated regularly when stuff changes. Would be nice to have more conceptual info (in general, our docs are too lean in that area right now).

**Comment by exekias** [comment]
I would say these should be the path for a user when coming to us on containers:

- Initial deploy and how to get (fb: logs from all containers, mb: common system + docker/kubernetes metrics)
- Custom fetching based on conditions: autodiscover
- Defining config through labels & annotations: Hints based autodiscover

I think @DanRoscigno has been thinking on this too, so his help here could be awesome

**Comment by DanRoscigno** [comment]
@dedemorton How is this different than this [issue](https://github.com/elastic/stack-docs/issues/108)?

**Comment by dedemorton** [comment]
Bumping the priority of this work which has been on the back burner for a long time.

Not that we might take a different tack and focus on specific use cases like Kubernetes monitoring rather than trying to refactor all the topics about container monitoring in the Beats docs.

**Comment by DanRoscigno** [comment]
Maybe we should zoom, deploy in docker and k8s, and make a list of topics.  Should be something like config file, secrets, autodiscover, metadata.
