### ISSUE TITLE
Edit Heartbeat content about automatic reloading

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#8332]
Content added in https://github.com/elastic/beats/pull/8227 needs a light edit.

**Comment by andrewvc** [comment]
I've merged #8227 if you'd like to do a subsequent edit.

**Comment by andrewvc** [comment]
@dedemorton just a ping on this. Does it still need work?

**Comment by dedemorton** [comment]
@andrewvc There are a few places where we can tighten up the language. However, that's true of a lot of the docs at this point (especially the stuff that's been around for awhile). At some point, I need to do a full book edit, so I'm OK with closing this for now. Thanks!
