### ISSUE TITLE
Spooling option

### ISSUE THREAD

**Issue by sentient** [elastic/beats#8348]
A question on the spooling to disk:

When events cannot be send to Elastic Search, events are nicely written to disk.
On restart the events are send to ElasticSearch.

I was wondering, do we always need to restart? Or can we set an option to retry to submit after XX time period? Or when other events are again successfully submitted, can we resubmit the pending events.

**Comment by webmat** [comment]
I apologize for the inconvenience, but this is a usage question, and should be
asked at https://discuss.elastic.co.

GitHub should be used for reporting bugs, suggesting improvement and opening pull requests.
