### ISSUE TITLE
Rename the issue label "adoptme" to "help wanted"

### ISSUE THREAD

**Issue by xeraa** [elastic/beats#8350]
Elasticsearch just renamed their "adoptme" to "help wanted", which is also in line with the [special labels GitHub supports](https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/). IMO it would be cool if we could stick to the convention and also keep it in sync across projects :)

**Comment by andrewkroh** [comment]
SGTM. I made the change. I didn't find any label documentation that needed to be updated as a result of the change.
