### ISSUE TITLE
[Auditbeat] Allow setting kernel audit config immutable

### ISSUE THREAD

**Issue by ndubss** [elastic/beats#8352]
I don't believe auditbeat supports any type of tamper feature of this type. Specifically, this is to prevent an attacker from disabling the system that would be used to alert to intrusion.

The closest thing I can find is failure_mode: log
Although I haven't tested yet.

There is also an auditd immutability mode (-e) that auditbeat will not allow in the accepted config. I do like that an attacker would likely go after auditd first (with auditctl -l), see rules, and then attempt auditctl -D. That (and any other recon) would be logged.

**Comment by ceeeekay** [comment]
+1 for allowing auditbeat to set `-e 2`

**Comment by jondoxley** [comment]
+1 to auditbeat setting -e 2

**Comment by dmlary** [comment]
Workaround for CentOS/RHEL:

* Edit the auditbeat.service, and add the following line to the `[Service]` section:
```ini
ExecStartPre=/usr/sbin/augenrules --load
```
* Keep your rules files in `/etc/audit/rules.d/*.rules`.
* Comment out both `audit_rules_files` and `audit_rules` in `auditbeat.yml`

Now, `augenrules` is responsible for parsing & loading audit rules out of `/etc/audit/rules.d/*.rules` before auditbeat starts.  Auditbeat will not add any rules.

**Comment by dmlary** [comment]
### Workaround for unicast-only systems

Along the same lines as the previous workaround, modify `auditbeat.service` and add the following line to the `[Service]` section:
```ini
ExecStartPost=/bin/sh -c "/usr/bin/sleep 5;/usr/sbin/augenrules --load"
```

The key here is the sleep.  When I did just `augenrules --load`, sometimes the rules would be immutable before auditbeat performed the check to see if the rules were locked.

I'd also suggest throwing `RefuseManualStop=yes` into `[Unit]` so you don't accidentally restart auditbeat.  Once you do that, it can't receive the audit events anymore.

**Comment by admlko** [comment]
This really needs to be implemented.

**Comment by Erni** [comment]
Is there any plan to implement this in the near future?

**Comment by ndubss** [comment]
@andrewkroh thank you! This can be closed. https://github.com/elastic/go-libaudit/pull/68/commits/ba0bbabcbcf804bf48a2dc721182927e32d72801

**Comment by andrewkroh** [comment]
I did add support for this feature in the go-libaudit library, but Auditbeat still needs updated to use the feature and also to provide helpful errors when certain actions cannot be performed due to the kernel being immutable.

**Comment by cynorsense** [comment]
This is still a problem on 7.10.1 auditbeat. Not sure if this will come up as highest priority.

**Comment by wilrodriguez** [comment]
Does anyone know when this change might occur?
