### ISSUE TITLE
Default application ports of Elastic stack in addresses without ports

### ISSUE THREAD

**Issue by kvch** [elastic/beats#8355]
When someone tries to connect to or load object to other elements of our stack, the target cannot be on a protocols default port. Meaning if the port number is missing from the address of the target, Beats silently adds the default port of Kibana or Elasticsearch.

```shell
libbeat/kibana/client.go:       kibanaURL, err := common.MakeURL(config.Protocol, config.Path, config.Host, 5601)
libbeat/monitoring/report/elasticsearch/elasticsearch.go:       url, err := common.MakeURL(config.Protocol, "", host, 9200)
libbeat/outputs/elasticsearch/elasticsearch.go:         esURL, err := common.MakeURL(config.Protocol, config.Path, host, 9200)
libbeat/outputs/elasticsearch/elasticsearch.go:         esURL, err := common.MakeURL(config.Protocol, config.Path, host, 9200)
```

Functions responsible:
* https://github.com/elastic/beats/blob/master/libbeat/common/url.go#L33 in `MakeURL`
* https://github.com/elastic/beats/blob/master/libbeat/outputs/transport/client.go#L85 in `fullAddress`
```golang
func fullAddress(host string, defaultPort int) string {
	if _, _, err := net.SplitHostPort(host); err == nil {
		return host
	}

	idx := strings.Index(host, ":")
	if idx >= 0 {
		// IPv6 address detected
		return fmt.Sprintf("[%v]:%v", host, defaultPort)
	}
	return fmt.Sprintf("%v:%v", host, defaultPort)
}
```

I propose we get rid of this behaviour, because it does not let users to configure their Elastic stack properly. But as some people might be depending on this behaviour, we might need to postpone releasing the fix until 7.0. (Given that we agree on this solution.)

**Comment by andrewkroh** [comment]
Based on the principle of least surprise I too think we should revert to using the default ports associated with the protocols (80 and 443). But making this change certainly could cause users a lot of problems so we should be careful here.

If we do make the change we could add some warnings in 6.x for anytime the Beat makes use of a default port like 5601 or 9200 because the URL didn't have one.

**Comment by ph** [comment]
I like @andrewkroh proposal, but I think this hurts users so we have to take extra care into providing information to resolve their problems.

**Comment by kvch** [comment]
As users need to configure an option named `host`, not `url` (or `domain`), it is acceptable to default to the default port of other stack elements.

A new warning is going to be displayed when a user does not provide a port number, stating that the Beat is connecting to the default port of Kibana or Elasticsearch. 

If someone would like to connect to a default port of HTTP or HTTPS, he/she needs to provide the port number. E.g. `hosts: ["http://my-elastic-search.org:80"]`
