### ISSUE TITLE
[metricbeat] Add Windows service user name

### ISSUE THREAD

**Issue by willemdh** [elastic/beats#8364]
It would be nice if the windows service metricset would allow us to add the user configured for this service as `windows.service.user.name`. As some services (eg backup / Altiris / SAP) require elevated permissions, it would be useful to know where specific users are set etc..

- Version: 6.4.0
- Operating System: Windows
- Discuss Forum URL: https://discuss.elastic.co/t/windows-service-user-would-be-awesome/148642/2
- Steps to Reproduce: Enable Metricbeat's windows service metricset, there is no way to add `windows.service.user.name`

Grtz

**Comment by kaiyan-sheng** [comment]
@narph Is this start_name the same as service user name?

**Comment by narph** [comment]
a PR was built based on this initial issue https://github.com/elastic/beats/pull/8561 (referenced above) and then a continuation PR based on the initial PR https://github.com/elastic/beats/pull/11877, already merged.

The `start_name` should be the account name under which a service runs. 
Depending on the service type, the account name may be in the form of "DomainName\Username" or UPN format ("*Username@DomainName*") etc.

This issue can be considered closed, we might want to rename start_name to user.name to follow ECS guidelines.

**Comment by kaiyan-sheng** [comment]
Sounds good, thanks @narph. I will close this issue and you can open a new issue to track the renaming work later.
