### ISSUE TITLE
drop default version qualifier

### ISSUE THREAD

**Issue by graphaelli** [elastic/beats#8384]
#8310 added a version qualifier, including a default for 7.0.0, for use during the build system transition.  This serves as a reminder to remove the default for 7.0.0, though it's unclear whether we'll want that back for 8.x.

While changing this up, let's also drop the `BEAT_` prefix from the env variable, leaving just `VERSION_QUALIFIER`.

**Comment by andrewkroh** [comment]
`dev-tools/jenkins_release.sh` will need updated too. https://github.com/elastic/beats/pull/8542
