### ISSUE TITLE
no way to have beats resend/harvest files based on file timestamp

### ISSUE THREAD

**Issue by ghost** [elastic/beats#8388]
the time that I'm talking about is the time on the file itself ... the messages in the file have no timestamps on them ... and they are all files created between 9/14/2018 @ 12:00:00 to 9/17/2018 @ 18:00:00

I'm sure elastic has had customers that inadvertently blown away a day of an index in the past and needed that data resent to rebuild that days index ... how was that accomplished?

https://discuss.elastic.co/t/harvest-logs-between-a-certain-date/149194

**Comment by DigitalTargit** [comment]
Hey there ... Yeah I removed my  account and created a new one. So I'll just re-add my earlier comments 👍 

the time that I'm talking about is the time on the file itself ... the messages in the file have no timestamps on them ... and they are all files created between 9/14/2018 @ 12:00:00 to 9/17/2018 @ 18:00:00

I'm sure elastic has had customers that inadvertently blown away a day of an index in the past and needed that data resent to rebuild that days index ... how was that accomplished?

https://discuss.elastic.co/t/harvest-logs-between-a-certain-date/149194
