### ISSUE TITLE
Support metrics collection with metricbeat using IPMI

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#8398]
Supporting metrics collection using [IPMI](https://en.wikipedia.org/wiki/Intelligent_Platform_Management_Interface) could be useful in bare-metal datacenters. It can be challenging to support multiple implementations, but an initial module could be done that could be improved with additional contributions.

This module could support two operation modes, one from the node itself, and another one from a central point to monitor devices that could be powered off.

**Comment by Leaf-Lin** [comment]
++

**Comment by Leaf-Lin** [comment]
@jstrassb

**Comment by fearful-symmetry** [comment]
++ On this. IPMI support was a huge request at my old job.

**Comment by PrplHaz4** [comment]
still relevant IMO...

**Comment by vishpat** [comment]
Need it

**Comment by PrplHaz4** [comment]
bump 👍

**Comment by johncollaros** [comment]
bump 👍
