### ISSUE TITLE
[Filebeat] Handle geoip changes in filebeat modules system test (test_modules_...)

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#8400]
Filebeat `test_modules` system test tests ingest pipelines with running Elasticsearch instances. Modules using the geoip plugin are error prone, as geoip data can change or fields can be added or removed. We should change how we check these fields.

[This build](https://travis-ci.org/elastic/beats/jobs/432188448) fails because some coordinates have changed (#8401).

elastic/beats#8204 was about fields added with ES 6.5.

**Comment by ruflin** [comment]
I remove the label bug and flaky-test for now as I think it's not the typical flaky tests we discuss otherwise. This "should" only break in the non stable branches where we pull in the most recent builds of Elasticsearch. In branches like 7.0 this should not happen.
