### ISSUE TITLE
Packetbeat fails to build on ARM64

### ISSUE THREAD

**Issue by mnaser** [elastic/beats#8408]
I am trying to get Packetbeat ARM64 packages and they're failing to build for me.

https://gist.github.com/mnaser/c4943c070df3b4c3c21866cf0158f7a1

With the above instructions, if you add `packetbeat` to the list, it'll fail because of `pcap.h` error?

**Comment by andrewkroh** [comment]
This was fixed in master with https://github.com/elastic/beats/pull/7809. You could apply the same fix to you local branch and it should let you build.

**Comment by andrewkroh** [comment]
I'm back-porting that fix into 6.x and 6.4.

**Comment by mnaser** [comment]
Awesome.  I was trying to build the tag of 6.4.1.  I'll look forward for the next release (6.4.2).
