### ISSUE TITLE
Kafka output config docs need config example under "topics" setting

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#8423]
While adding more detail to the config settings `topics` (see https://github.com/elastic/beats/pull/8290), I noticed that we don't provide a config example like we do under similar settings (such as `indices`). We should provide an example because it's hard to understand the `mappings` setting without seeing a config example.

**Comment by darshanbm89** [comment]
Stumbled upon this after looking for solution to https://discuss.elastic.co/t/filebeat-kafka-topic-mappings/233584.
