### ISSUE TITLE
Auditbeat resolve_ids doesn't work reliably in docker

### ISSUE THREAD

**Issue by ndubss** [elastic/beats#8453]
Hello, I hope I'm doing something wrong and this isn't actually a bug. 

When running with(resolve_ids:true in config): docker run -e redacted --pid=host --cap-add=AUDIT_CONTROL --cap-add=AUDIT_READ -v $PWD/auditbeat.yml:/etc/auditbeat/auditbeat.yml -v /etc/audit/rules.d/audit.conf:/etc/audit/rules.d/audit.conf  redacted/vjsamuel/auditbeat:7.0.0

I get this output(on executed event_type):
actor_primary:	 79004	
actor_secondary:	 79004	

actor_primary:	 110288129	
actor_secondary:	 0	

When taking this same config and running on same VM, as regular auditd binary, I get this:
actor_primary:	 nwedlake	
actor_secondary:	 root	

The above is running on Ubuntu 14.04.5 LTS. I'm also stuck testing w 7.x on this host. I'm having trouble getting my mac docker env back up, otherwise I would confirm there as well. If someone can quickly test on 6.4, I would appreciate it.

**Comment by andrewkroh** [comment]
If the auditbeat process is containerized then it is going to be using the containerized `/etc/passwd` and `/etc/group` to resolve values. So try mounting the host's files inside the container (e.g. `-v /etc/passwd:/etc/passwd -v /etc/group:/etc/group`).

**Comment by ndubss** [comment]
Andrew, thanks for the help, but we have another variable. I added /etc/passwd and /etc/group. That is now mapping our service accts. Our user accounts are tied with ldap and not stored locally. I've only figured out how to get the mapping from getent, but that obviously doesn't work in the container. Any thoughts?

**Comment by andrewkroh** [comment]
Does `resolve_ids` work correctly when Auditbeat is run outside of a container w.r.t. the LDAP based accounts? Auditbeat relies on Go's `os/user` package which uses `getpwuid_r` to resolve the IDs. So perhaps some additional config is needed inside of the container to make it work. I don't have much experience configuring LDAP on Linux unfortunately.

**Comment by ndubss** [comment]
Okay thanks. Yes it works when run on that same host, outside the container. I'll see if we can reverse engineer getpwuid_r.
