### ISSUE TITLE
Packetbeat running on docker missing a required parameter

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/beats#8454]
The "Bind-mounted configuration" section of the Packetbeat docs is missing an arg "--cap-add=NET_ADMIN"

- Version: 6.4.0, probably all
- Operating System: Linux, OS X
- Steps to Reproduce: Run the command 
```
docker run \
  --mount type=bind,source="$(pwd)"/packetbeat.yml,target=/usr/share/packetbeat/packetbeat.yml \
  docker.elastic.co/beats/packetbeat:6.4.1
```
and you will see:

`/usr/local/bin/docker-entrypoint: line 8: /usr/share/packetbeat/packetbeat: Operation not permitted`

I tried to edit the docs page, but it is a common page across Beats and the rest do not need the extra arg that Packetbeat needs.

The full command should be:

```
docker run \
 --cap-add=NET_ADMIN  \
 --mount type=bind,source="$(pwd)"/packetbeat.yml,target=/usr/share/packetbeat/packetbeat.yml   \
docker.elastic.co/beats/packetbeat:6.4.1
```

**Comment by slmingol** [comment]
I used the above tip regarding `--cap-add=NET_ADMIN` to run an interactive container where I could interact w/ packetbeat as well:

```
$ docker image list|grep pack
docker.elastic.co/beats/packetbeat                                    7.0.0               e89405c3243d        2 weeks ago         291MB
docker.elastic.co/beats/packetbeat                                    6.5.1               e0609eba9214        5 months ago        344MB
```

```
$ docker run --cap-add=NET_ADMIN --user 0 -it e89405c3243d /bin/bash
```
