### ISSUE TITLE
[Heartbeat] Multiple connection attempts to a host in a single beat

### ISSUE THREAD

**Issue by zoonage** [elastic/beats#8482]
# Current State

Heartbeat can only perform a single connection (possibly to multiple hosts) and reports stats based on that.

# Proposed Improvement

Allow Heartbeat to connect to Y hosts X times. This would allow for the possibility of things such as;

1. Packet loss % monitoring at a particular instant (relates to #7291) 
2. Reducing the size of data indexed in ES as the current way to do this would be to run a ping every 5 seconds, this results in a lot of duplicated fields across documents, whereas this method could create a single document that contains aggregated data.
3. It doesn't prevent the use case above from being used, as you can set the number of requests to be 1 with an appropriate time interval

Heartbeat could then ship metrics like

icmp.rtt.max
icmp.rtt.avg
icmp.rtt.min
icmp.packet_loss
resolve.max
resolve.avg
resolve.min

This would result in higher document size for the single request instance, so maybe this could be a separate monitor called `icmp_group` to get the best of both worlds

**Comment by zoonage** [comment]
Also should add metrics like jitter

**Comment by andrewvc** [comment]
Hey, just adding here that I really like this idea. I think there's some complexity to it, but it makes a lot of sense for ICMP in particular.
