### ISSUE TITLE
auditbeat for s390x

### ISSUE THREAD

**Issue by jesslh** [elastic/beats#8486]
Hi, I am building an auditbeat for s390x, following the next guide: https://github.com/linux-on-ibm-z/docs/wiki/Building-Beats

The version that I download of beats was first 6.4, then 6.2 in order to follow the guide.

In both cases, the beat compile but when I run the auditbeat the following error is shown:

ERROR      instance/beat.go:758         Existing: 1 error: 1 error: failed to create audit client; failed to get audit status: failed to get audit status ack: no reply received.

- The version of elastic that I have installed is 6.4.0
- auditd service is stopped

For confirmed bugs, please report:
- Version: ELK 6.4.0; beats I try with 6.4 and 6.2
- Operating System: Linux s390x (3.10 kernel version)

**Comment by michalpristas** [comment]
closing as this is for old version
