### ISSUE TITLE
Push tudor/* docker images to Docker HUB

### ISSUE THREAD

**Issue by cyrilleverrier** [elastic/beats#849]
@tsg : May I kindly ask you to update the following docker images in your docker hub repository:
```
tudorg/beats-builder-deb6
tudorg/xgo-deb6-1.5.3
tudorg/xgo-deb6-base
tudorg/beats-builder
tudorg/xgo-1.5.3
tudorg/xgo-base 
tudorg/fpm
```

In order to pack my own beat. I had to regenerate them from scratch using :
```
cd vendor/github.com/elastic/beats/dev-tools/packer/
make fpm-image
make xgo-image
```
It takes about one hour !

Please discard this request if you are going to change the packer system drastically.

**Comment by tsg** [comment]
I just pushed them, see https://hub.docker.com/r/tudorg/

**Comment by cyrilleverrier** [comment]
@tsg Thank you, I can pack my beat with your docker images now.
