### ISSUE TITLE
Throttling messages - Question

### ISSUE THREAD

**Issue by harshapic** [elastic/beats#8499]
Best way to throttle messages based quantity per time basis i.e 500msgs per second or 10mb of messages per second something like that any way i can achieve this from filebeat?

**Comment by sayden** [comment]
Hi @harshapic :)

Questions and issues should be post first on Discuss (https://discuss.elastic.co/c/beats), see contribution guidelines https://github.com/elastic/beats/blob/master/CONTRIBUTING.md We'll be happy yo help you and follow your issue there too.

Closing this issue to avoid confusion.
