### ISSUE TITLE
Can not making tar.gz form of filebeat logs, when going for back up ?

### ISSUE THREAD

**Issue by jain108shubhamtbt** [elastic/beats#8503]
Can not making tar.gz form of filebeat logs, when going for back up ?

# Filebeat Version : 
filebeat 6.4.1

# Golang Version : 
go version go1.11 windows/amd64

# Getting logs : 
Perform command ls in linux 
filebeat.log    filebeat.log.2  filebeat.log.4  filebeat.log.6
filebeat.log.1  filebeat.log.3  filebeat.log.5  filebeat.log.7

# Need : 
filebeat.log    filebeat.log.2.tar.gz  filebeat.log.4.tar.gz  filebeat.log.6.tar.gz
filebeat.log.1.tar.gz  filebeat.log.3.tar.gz  filebeat.log.5.tar.gz  filebeat.log.7.tar.gz

# Filebeat configure : 

logging.to_files: true
logging.files:
  // Configure the path where the logs are written. The default is the logs directory
  // under the home path (the binary location).
  path: /var/log/filebeat

  // The name of the files where the logs are written to.
  name: filebeat

  // Configure log file size limit. If limit is reached, log file will be
  // automatically rotated
  rotateeverybytes: 10485760 # = 10MB

  // Number of rotated log files to keep. Oldest files will be deleted first.
  keepfiles: 7

  // The permissions mask to apply when rotating log files. The default value is 0600.
  // Must be a valid Unix-style file permissions mask expressed in octal notation.
  permissions: 0600

**Comment by ph** [comment]
@jain108shubhamtbt If I understand correctly you want that filebeat logs get compressed when we rotate them?

**Comment by jain108shubhamtbt** [comment]
Thanks, @Pier-Hugues Pellerin for adding it as enhancement.

Yes.
