### ISSUE TITLE
libbeat: incorrect message in common.LoadGeoIPData

### ISSUE THREAD

**Issue by cleesmith** [elastic/beats#851]
```logp.Info("GeoIP disabled: No paths were set under output.geoip.paths")```
should be:
```logp.Info("GeoIP disabled: No paths were set under shipper.geoip.paths")```

**Comment by ruflin** [comment]
@cleesmith Thanks for reporting this. Feel free to also directly open a PR to fix.

**Comment by cleesmith** [comment]
It seemed a small thing, not really worth mentioning or a PR ... but the more eyes, the better.

**Comment by ruflin** [comment]
It's these small things that confuse the user in the end and lead to wrong configuration. I will include it in one of my next PR's.

**Comment by ruflin** [comment]
Closing as fixed in https://github.com/ruflin/beats/commit/5f4ebd9bde07b672626a79114f0d3fff6799e0d3
