### ISSUE TITLE
xpack.monitoring.logstash request

### ISSUE THREAD

**Issue by kaem2111** [elastic/beats#8536]
**This is an enhancement request.**

According to https://www.elastic.co/guide/en/beats/filebeat/6.4/configuration-monitor.html
you can specify xpack.monitoring.elasticsearch as a monitoring destination.  

Unfortunaly sometimes customer does not want to expose an elasticsearch endpoint to their beats located in a DMZ to avoid downloading the whole cluster with one correct user password.
 
I would appreciate to specify logstash as a destination, which in turn could forward data over arbitary network segments using Logstash-to-Logstash communication (https://www.elastic.co/guide/en/logstash/current/ls-to-ls.html) to an elastic cluster. 

As an alternative, a new option xpack.monitoring.file  could dump the json to a local file, where filebeat can get it and send it to logstash.

Maybe this leads to a discussion, why xpack.monitoring does not use/offer the same output options, like beat
already does (https://www.elastic.co/guide/en/beats/filebeat/current/configuring-output.html).

**Comment by akqopensystems** [comment]
+1

**Comment by cskowronnek** [comment]
+1
Would be highly appreciated for the same reasons. We have a lot of devices running beats over the internet and we don't want to expose our ES cluster (not a even a dedicated monitoring cluster).

**Comment by mtojek** [comment]
Not a high priority at the moment. Resolving.
