### ISSUE TITLE
Not LF but CRLF for configuration files in Windows packages

### ISSUE THREAD

**Issue by sakurai-youhei** [elastic/beats#8544]
- Version: 6.4.2
- Operating System: Windows 10 v1803 (build 17134.285)
- Discuss Forum URL: https://discuss.elastic.co/t/could-this-be-a-bug-not-crlf-but-lf-is-used-in-metricbeat-yml-of-windows-package/150809
- Steps to Reproduce: 1) Download one of Beat installation packages for Windows, 2) unzip it and 3) open `xxxbeat.yml` using notepad.

**Current result**

I can't modify the `xxxbeat.yml` because all lines are wrapped into one line.

**Expected result**

I can modify the `xxxbeat.yml`.

**Problem on pure Windows environment**

Until [extended line endings support in Notepad](https://blogs.msdn.microsoft.com/commandline/2018/05/08/extended-eol-in-notepad/) will have been released and deployed widely, builtin notepad is useless to modify text files consisting of LF (0x0A) line separator, i.e. Configuration of the Beats requires 3rd-party text editor like Notepad++ on Windows.

I hope you could imagine how 3rd-party and/or unauthorized applications are sometimes restricted in secured Windows environment.

**Comment by andrewkroh** [comment]
I've always use Wordpad on Windows when no other tools were available.
