### ISSUE TITLE
reload.go does not check for auditd rule changes

### ISSUE THREAD

**Issue by ndubss** [elastic/beats#8556]
Hello, we have set the config reloader to check every 30 seconds.

This loads successfully: 2018-10-03T13:31:15.200-0700	INFO	cfgfile/reload.go:141	Config reloader started

BUT, when you implement new auditd rules, these are not checked and auditbeat must be reloaded for the changes to deploy.

**Comment by andrewkroh** [comment]
Are you referring to the `/etc/auditbeat/audit.rules.d/*` files? Those are not monitored for changes at the moment, but that would be nice to add in the future.

The `/etc/auditbeat/modules.d/*yml` files should be reloaded along the lines of what's described [here](https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-configuration-reloading.html).

**Comment by ndubss** [comment]
Yes, that's exactly the issue. We are trying to make this more dynamic and right now, this would be the only reason why we would need to restart all the agents. Please consider supporting this :)

**Comment by ObscurityThroughSecurity** [comment]
+. We would like rules to be reloaded on the fly along with the auditbeat configuration.
Please implement this.

**Comment by andrewkroh** [comment]
There is a PR open in #10835, but it must have some tests added to help ensure the change does not introduce race conditions.
