### ISSUE TITLE
Bug in http.request/response.header beats vs template name

### ISSUE THREAD

**Issue by vbohata** [elastic/beats#8564]
There is a difference between templates and real event fields generated by metricbeat. According to doc and (https://github.com/elastic/beats/blob/99824df163863478d27688206e18ec27bc1b3ac5/metricbeat/module/http/json/json.go ... if I am not looking in wrong place) it generates field http.request.headers and http.response.headers. But in template there is http.request.header and http.response.header (without ending s). In fact it is not a problem, but it makes object definition here useless.

**Comment by ruflin** [comment]
This indeed seems to be a bug. Thanks for raising. @sayden Could you have a look?

**Comment by sayden** [comment]
Fixed here https://github.com/elastic/beats/pull/8585
