### ISSUE TITLE
Add support for GET method in Jolokia metricbeat module

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#8566]
Current Jolokia module makes requests using POST method, but depending on the environment where Jolokia agent is deployed, POST method can be unavilable.

Jolokia also supports GET method, the module could have an option to select the method used.

Using GET method with Jolokia is a bit tricky, as parameters need to be carefully escaped and sent in the query parameters instead of using the request body. Also, according to documentation, not all Jolokia features are available when using the GET method, we'd have to check for these limitations when using this method.

**Comment by manios** [comment]
Hello!

May I try to take up this issue? Some first thoughts for discussion:

1. Regarding configuration, shall we add a new ```http_method``` parameter to ```config.yml``` which by default will have the value ```POST``` and can accept ```GET``` as well?
1. Regarding the special path parameter treatment of ```GET``` method, is ```GET``` request going to use this form ```<base-url>/<type>/<arg1>/<arg2>/..../``` as described in [6.1.1. GET requests](https://jolokia.org/reference/html/protocol.html#get-request) abiding by [Table 6.1. Escaping rules](https://jolokia.org/reference/html/protocol.html#escape-rules)?
1. Regarding features unavalable in ```GET``` read request:
    1. [Proxy requests](https://jolokia.org/reference/html/protocol.html#protocol-proxy) are not supported in ```GET```, thus shall we log a warning message and continue or throw an error?
    1. Bulk requests are only possible with ```POST```. Shall we log a warning message and continue or throw an error?

Thanks in advance.

**Comment by jsoriano** [comment]
Hi @manios, thanks for offering your help on this issue! :slightly_smiling_face:

I will assign this issue to you, but feel free to ping me for any question.

> Regarding configuration, shall we add a new http_method parameter to config.yml which by default will have the value POST and can accept GET as well?

Yes, we should add a new parameter, `http_method` with `POST` by default looks good to me.

> Regarding the special path parameter treatment of GET method, is GET request going to use this form ```<base-url>/<type>/<arg1>/<arg2>/..../``` as described in 6.1.1. GET requests abiding by Table 6.1. Escaping rules?

Yes, I guess we will have to build this kind of urls.

> Regarding features unavalable in GET read request: 

Thanks for looking for the unavailable features! :smile: 

> Proxy requests are not supported in GET, so if they exist in configuration shall we ignore them, log a warning message and continue or throw an error?

I'd throw an error as the configuration should be considered invalid, we could mention in the error message that this is supported using POST method.

> Bulk requests are only possible with POST. What will we do for multiple jmx.mappings in beat configuration?. Shall we log a warning message and use only the first mapping, make multiple GET requests or throw an error?

I think we could workaround this by making multiple GET requests.

**Comment by jsoriano** [comment]
@manios I think I cannot assign this issue to you, but you can take it, feel free to open a PR.

**Comment by manios** [comment]
@jsoriano Thanks for the clarifications! I will start it and make a PR when ready! Cheers!
