### ISSUE TITLE
pipeline/output.go:74   Failed to connect: Connection marked as failed because the onConnect callback failed: Error loading Elasticsearch template: error creating template from file /etc/filebeat/fields.yml: open /etc/filebeat/fields.yml: no such file or directory

### ISSUE THREAD

**Issue by zhaoyun006** [elastic/beats#8580]
I deploy filebeat in docker container

Logs appear as follows

2018-10-05T13:08:47.972+0800    INFO    elasticsearch/client.go:690     Connected to Elasticsearch version 6.4.2
2018-10-05T13:08:47.973+0800    INFO    template/load.go:55     Loading template for Elasticsearch version: 6.4.2
pipeline/output.go:74   Failed to connect: Connection marked as failed because the onConnect callback failed: Error loading Elasticsearch template: error creating template from file /etc/filebeat/fields.yml: open /etc/filebeat/fields.yml: no such file or directory

 Setup Beat: filebeat; Version: 6.2.3

filebeat configure 
output.elasticsearch:
  enable: True
  hosts: ["192.168.54.200:9200"]

# ps uax
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0 644676 27832 ?        Ssl  Oct04   0:09 filebeat -e -c /etc/filebeat/filebeat.yml
root         23  0.0  0.0   4348  1624 ?        Ss   12:42   0:00 sh
root         88  0.0  0.0  17512  2132 ?        R+   13:14   0:00 ps uax

How to operate？

**Comment by jsoriano** [comment]
Hi @zhaoyun006,

Could you please ask this question in https://discuss.elastic.co/ ? If it is confirmed to be some kind of bug you can reopen this issue, I'm closing it by now.

Thanks!
