### ISSUE TITLE
Need service for filebeat install and uninstall through cmd in windows platform ?

### ISSUE THREAD

**Issue by jain108shubhamtbt** [elastic/beats#8599]
This is not running in cmd.

# Delete and stop the service if it already exists.
if (Get-Service filebeat -ErrorAction SilentlyContinue) {
  $service = Get-WmiObject -Class Win32_Service -Filter "name='filebeat'"
  $service.StopService()
  Start-Sleep -s 1
  $service.delete()
}

$workdir = Split-Path $MyInvocation.MyCommand.Path

# Create the new service.
New-Service -name filebeat `
  -displayName Filebeat `
  -binaryPathName "`"$workdir\filebeat.exe`" -c `"$workdir\filebeat.yml`" -path.home `"$workdir`" -path.data `"C:\ProgramData\filebeat`" -path.logs `"C:\ProgramData\filebeat\logs`""

# Delete and stop the service if it already exists.
if (Get-Service filebeat -ErrorAction SilentlyContinue) {
  $service = Get-WmiObject -Class Win32_Service -Filter "name='filebeat'"
  $service.StopService()
  Start-Sleep -s 1
  $service.delete()
}

Please help me .

**Comment by jain108shubhamtbt** [comment]
# Filebeat version 

filebeat-6.4.2-windows-x86_64

**Comment by andrewkroh** [comment]
> This is not running in cmd.

We provide scripts for PowerShell, not cmd.exe. See [Getting Started](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation.html).
