### ISSUE TITLE
Getting ERROR when run .ps1 file in powershell in filebeat filebeat-6.4.2-windows-x86_64 ?

### ISSUE THREAD

**Issue by jain108shubhamtbt** [elastic/beats#8600]
When running install-service-filebeat.ps1 and uninstall-service-filebeat.ps1 getting error .

PS C:\filebeat-6.4.2-windows-x86_64\filebeat-6.4.2-windows-x86_64>.\install-service-filebeat.ps1
.\install-service-filebeat.ps1 : File
C:\Users\shubham.jain\Downloads\filebeat-6.4.2-windows-x86_64\filebeat-6.4.2-windows-x86_64\install-service-filebeat.ps1 cannot be loaded because
running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\install-service-filebeat.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by faulander** [comment]
as your error message clearly shows, execution of scripts is disabled. Did you open Powershell as Admin?

**Comment by jsoriano** [comment]
As @faulander mentions this looks like a permissions problem, please use [discuss](https://discuss.elastic.co/) for questions about usage of Beats.
