### ISSUE TITLE
Docs incorrectly list `d` (days) as allowed time unit

### ISSUE THREAD

**Issue by forana** [elastic/beats#8603]
- Version: 6.4.2
- Operating System: n/a
- Discuss Forum URL: n/a
- Steps to Reproduce:  visit https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#time-units

`d` is _not_ a valid time unit for `time.Duration` strings. `beats` uses [elastic/go-ucfg](https://github.com/elastic/go-ucfg)'s `Config` object, which internally passes to [time.ParseDuration](https://golang.org/pkg/time/#ParseDuration): https://github.com/elastic/go-ucfg/blob/9b0b552a081bae9253b7f378006d76df88a296c2/reify.go#L748

The current [live docs for `time.ParseDuration`] say:

> Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".

And the source reflects this as well: https://github.com/golang/go/blob/ad644d2e86bab85787879d41c2d2aebbd7c57db8/src/time/format.go#L1278

**Comment by andrewkroh** [comment]
Beats has its own [config file data types documentation](https://www.elastic.co/guide/en/beats/libbeat/current/config-file-format-type.html#_duration) that does not mention `d`. You are looking at Elasticsearch's documentation. The two projects don't share the same config parsing code so unfortunately there are some differences.
