### ISSUE TITLE
fields.yml is ignored but still shipped with packages

### ISSUE THREAD

**Issue by roncohen** [elastic/beats#8607]
For 6.4 and possibly earlier versions, `fields.yml` is embedded in the binaries. `fields.yml` is still included in packages, but is ignored. 
Looks like `#setup.template.fields: "${path.config}/fields.yml"` should be on by default

**Comment by ruflin** [comment]
The change was made in https://github.com/elastic/beats/pull/4834 I remember the thinking around setting it off by default was that previously we didn't document / recommend to modify fields.yml so it was not considered breaking change.

Long term I'm thinking the fields.yml should be removed and for modifications `append_fields` should be used. There should be an option to export the fiel for modifications if needed and then load it. So I like the current behaviour that it's not default but I see the point that it's confusing in case of modifications. Should we add better docs around it so we can at least point users to it?
