### ISSUE TITLE
Provide more detailed documentation on log levels

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#861]
Filing based on user experience in the field.

https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html#_level

> level
> Minimum log level. One of debug, info, warning, error or critical. If debug is used, but no selectors are configured, the \* selector will be used. The default log level is error.

It looks like if everything is running fine, and no errors are logged, we do not even create the log file (at the default error level).  This can be misleading so that end users may think that their logging configuration is actually incorrect.  It will be nice to document this behavior.

At the debug level, it will print out all the events that are being flushed by filebeat, which is quite a useful debugging tool.  And if someone wants just the # of events published (to see that it is actually doing something), level: info is the one to use.  Perhaps we can also mention this as well. Thx!

**Comment by ruflin** [comment]
@ppf2 Thanks a lot for bringing this up and also directly making the suggestions for improvements. We should definitively improve this part of the docs as we also put quite a bit of work in improving the logging part recently.

@dedemorton FYI

**Comment by dedemorton** [comment]
Closed by #4405. Sorry it took me so long to get around to this. I think some of the changes to default behavior (such as having `info` instead of `error` as the default level) has probably helped clear up some of the confusion expressed in this issue.
