### ISSUE TITLE
Create Documentation for Template Creation

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#862]
See https://github.com/elastic/beats/pull/639

* [x] Introduce it in Getting Started Guide
  * Replace default by using beat config instead of script
  * Mention that if LS is used and not ES directly, still the script has to be used
* [x] Add it to the configuration options

**Comment by ruflin** [comment]
@dedemorton I split this out from https://github.com/elastic/beats/pull/639 as when I looked at the outputconfig it already looks quite packed and I wanted to discuss where to put these new options best.

**Comment by dedemorton** [comment]
@ruflin Soon I'll be restructuring the reference info about config options so that each section is a separate topic (to make each topic shorter and the information easier to retrieve). I'm also changing the TOC structure so that we can add some nested sub-topics.
