### ISSUE TITLE
Consolidate python dependencies on CI builds

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#8642]
Current CI builds use multiple `requirements.txt` files, and still some dependencies are installed using pip directly. We should review that:

* All python dependencies are installed from `requirements.txt` files
* All dependencies have fixed versions
* No python package is installed directly, without being fixed in a `requirements.txt` file, with pip or similar tools

**Comment by andrewkroh** [comment]
It would be great if we could get to one requirements.txt and one virtual environment directory (like top-level `beats/build/ve`.

Over in beats-tester I have a bit of Makefile logic that automatically updates the virtual env if requirements.txt is changed (based on mod time). https://github.com/elastic/beats-tester/blob/e3f0e831841b819db52da929762b420510c63668/Makefile#L9-L14

**Comment by jsoriano** [comment]
Most of the dependencies, if not all are fixed now, but there is still one `requirements.txt` per beat.
