### ISSUE TITLE
The fields.yml file used by Asset packer should be generated in the build directory

### ISSUE THREAD

**Issue by ph** [elastic/beats#8663]
The problem is when you are doing `make update` a fields.yml file is generated in the directory of the beat, this file is under _gitignore_ and not committed to the repository. But the purpose of this temporary file is confusing I propose that instead of generating this file at the root of a beat we should instead generate this file under the `build` directory.

**Comment by ruflin** [comment]
The main goal historically was that for running the Beat locally just `./metricbeat` could be used and everything would be in the right place. Unfortunately already today kibana dashboards path as to be set to make it working. Also with the x-pack binaries around it has become more complicated. +1 on moving generated files under `build` to make it more obvious but we should find a way that still makes it very easy to just run a binary locally.
