### ISSUE TITLE
filebeat stats endpoint via socket

### ISSUE THREAD

**Issue by danielkasen** [elastic/beats#8687]
Not sure if this is already being tackled but I couldn't find it. Anyway, is there a way to expose the _stats API endpoint via a socket opposed to a network port? Since we run filebeat everywhere it's hard to ensure a port number that would be free and I believe it would be a safer process as I can have a user that has access to these metrics vs anyone on the machine. Not sure if this is tied into storing these metrics in the registry file though.

**Comment by ruflin** [comment]
Hi @danielkasen. Thanks for bring this up. It's actually something we discussed in the past that we would like to do as an alternative to the http endpoint for all the above reasons. I don't think having a socket available would be related to the registry file.

@andrewkroh @urso FYI

**Comment by danielkasen** [comment]
Cool, glad to see it's in the discussions :+1:
