### ISSUE TITLE
Question: Using the beat.hostname variable in Logstash config

### ISSUE THREAD

**Issue by sdkarthik** [elastic/beats#869]
Hello,

I am using filebeats to stream logs from clients to a central logstash server. How do I get the hostname of the client on logstash server without hardcoding anything on the client.

As of now, this is the configs I have

on client machine--filebeat.yml config --
filebeat:
  prospectors:
    -
      paths:
        - /apps/home/tripcars/logs/*.log

      input_type: log
      ignore_older: 30m
      document_type: log

      fields:
        application: tripcars
        hostname: ny-rse-p01

Logstash config
output {

if[gds] {
    file {
      codec => line {}
      gzip => true
      path => "/apps/home/engadmin/testLogs/%{application}/%{hostname}/%{gds}/%{filename}.log"
    }
  stdout { codec => rubydebug }
}

As you can see I am sending hostname as a field in filebeat and reading it in logstash. It would be difficult to hardcode the hostname on all the servers we have. Is there a way to avoid this?

**Comment by ruflin** [comment]
Actually filebeat sends with each event under beat.hostname the hostname of the machine. No additional field is needed.

**Comment by andrewkroh** [comment]
In Logstash, the logstash-input-beats plugin automatically copies the `beat.hostname` field into `host` to match the behavior of must plugins. In your Logstash config you can just refer to that `host` variable. So change `hostname` to `host` in your output config. 

```
      path => "/apps/home/engadmin/testLogs/%{application}/%{host}/%{gds}/%{filename}.log"
```

Also like ruflin said, you don't need the `hostname` field in your Filebeat config.

**Comment by sdkarthik** [comment]
I tried that too..I tried both %{host} and %{hostname}..Nothing works.

This is what I am seeing in logstash --

$ pwd

/apps/home/engadmin/testLogs/tripcars

$ ls -ltr

total 56

drwxrwxr-x 8 engadmin engadmin 28672 Jan 27 11:00 ny-rse-p01

drwxrwxr-x 2 engadmin engadmin  4096 Jan 27 11:56 %{hostname}

drwxrwxr-x 2 engadmin engadmin  4096 Jan 27 12:02 %{host}



And the logstash config i have is --

"/apps/home/engadmin/testLogs/%{application}/%{host}/%{gds}/%{filename}.log"

**Comment by andrewkroh** [comment]
What version of the logstash-input-beats plugin do you have installed? Maybe you need to update it?

`/opt/logstash/bin/plugin list --verbose logstash-input-beats`
`/opt/logstash/bin/plugin update logstash-input-beats`

**Comment by andrewkroh** [comment]
You can also write `path => "/var/log/%{[beat][hostname]}.log"`, but that would be Beat specific. I just tested both ways (`%{host}` and `%{[beat][hostname]}`) using logstash-input-beats 2.1.2 with logstash 2.1.1.

If you have additional questions in the future please use the forums at https://discuss.elastic.co/c/beats. There your questions will likely be seen by a wider audience. We like to reserve Github issues for bugs or enhancement requests.

**Comment by sdkarthik** [comment]
Thanks, It works now.

**Comment by andrewkroh** [comment]
What was the resolution for the sake of others? Version update?

**Comment by sdkarthik** [comment]
yes, version upgrade.

**Comment by teranth** [comment]
Just to be sure others that have this issue can fix it. I also had to switch from the field syntax beat.hostname to [beat][hostname] to get it to work with the file output properly. Hopefully save someone else some time in the future as well.
