### ISSUE TITLE
Delay Start of Beats as Windows Service

### ISSUE THREAD

**Issue by urso** [elastic/beats#8711]
According to https://github.com/golang/go/issues/23479 go based service can hang and time out on startup while Windows is Booting. The `main` Function might not even be executed in this time span.

Configuring delayed auto startup seems to resolve the issue. Setting the registry key `HKLM\SYSTEM\CurrentControlSet\services\<service name>\DelayedAutostart` to 1 will mark the process as delayed. Some Windows versions seem to support a per service delay setting via `HKLM\SYSTEM\CurrentControlSet\services\<service name>\AutoStartDelay` (DWORD in seconds).

When installing beats as services on Windows, we should enable Delayed Autostart and try to set the delay to 60s (default is 120s).

**Comment by andrewkroh** [comment]
To implement this we need to add some PowerShell scripting to [install-service.ps1](https://github.com/elastic/beats/blob/master/dev-tools/packaging/templates/windows/install-service.ps1.tmpl) that sets the registry keys associated with the service. Then do some testing to make sure that it works across Windows versions.

**Comment by rwaight** [comment]
Since we are using PowerShell to create a service, we can use PowerShell to set it to delayed start *after* creating the service.  For filebeat, this would be something like:
```
$svcDelayed='config "{0}" start=delayed-auto' -f 'filebeat'
Start-Process -FilePath sc.exe -ArgumentList $svcDelayed
```
You could obviously pass whatever service when you declare $svcDelayed

Please let me know if you would like some help with this, thanks!
