### ISSUE TITLE
[Discuss][Design Philosophy] Distributed parsing vs centralized

### ISSUE THREAD

**Issue by amitavmohanty01** [elastic/beats#8727]
The current architecture mandates a certain way of interaction between Filebeat and Logstash in which some processing is done in Filebeat and some more processing is offloaded to Logstash. A typical setup will have Filebeat (or any other beat) setup on many machines pushing data to a set of logstash machines located centrally.

This raises the following questions:
1. Why can't we do the log processing once?
2. Why can't we distribute the log processing load and get rid of the centralized logstash or at least do more in Filebeat and less in Logstash? The current supported plugins and filters of logstash allow more rich parsing than what Filebeat supports. I am trying to understand why can't we let Filebeat have the same options and allow the system designer the flexibility of choosing between centralized parsing and distributed parsing.

A simple example is dropping of some characters, like HTML tags. This reduces the amount of data transferred over the wire and speeds up the entire pipeline but the only option to do so currently is in Logstash or in an ingest node.

**Comment by amitavmohanty01** [comment]
My question was regarding the design philosophy and not the usage. The explanations you have provided are valid and I am aware of those. I put the question here because it is about how we should look at the design of beats.

I also provided a concrete example in support of my ideas. I request you to re-open the thread for discussing the design philosophy and goals.

**Comment by webmat** [comment]
For your questions 1 and 2, we have been adding new processors to Beats, so this need is acknowledged, and we're working on it. From 8 processors [in 6.0](https://www.elastic.co/guide/en/beats/filebeat/6.0/filtering-and-enhancing-data.html), we've gone up to 11 [in 6.4](https://www.elastic.co/guide/en/beats/filebeat/6.4/filtering-and-enhancing-data.html), and 13 [in the imminent 6.5 release](https://www.elastic.co/guide/en/beats/filebeat/6.5/filtering-and-enhancing-data.html).

If you have specific requests of new processors you'd like to see, you're welcome to create issues to ask for them directly.

For example grok or a processor with some HTML parsing ability may be required to help accomplish the task from your example. I'll let other chime in on whether grok has been attempted in Beats.

**Comment by exekias** [comment]
Closing this as it has been open for a while now. A few good points were discussed
