### ISSUE TITLE
Topbeat: daemon mode

### ISSUE THREAD

**Issue by biswajit86** [elastic/beats#873]
I am trying to figure out if there is a flag to start topbeat(or any of the beats) in daemon mode.

Could someone please tell me if I can start topbeat in daemon mode via any flag or if `nohup` is the only way to run topbeat in daemon mode.

**Comment by andrewkroh** [comment]
There is no daemon flag as you will see in the CLI docs. https://www.elastic.co/guide/en/beats/topbeat/current/command-line-options.html

When Topbeat is installed using the RPM or deb packaging then it also installs the scripts that allow you to use operating system's service manager. You'll find all of the scripts associated with the packages [here](https://github.com/elastic/beats/tree/master/dev-tools/packer/platforms) in case you want to look at them.

For Windows we rely on the service manager. The zip packaging for windows includes a script to create the service.

For OS X we do not provide any scripts, but you can use [launchd](https://discuss.elastic.co/t/deploying-filebeat-on-macos-x/37785/11) to run the process.

**Comment by tsg** [comment]
Question was answered, thanks @andrewkroh.
