### ISSUE TITLE
Add test for invalid configs to `manager_test.go`

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#8740]
Moved from this comment: https://github.com/elastic/beats/pull/8726#discussion_r227895110 .

We need to add a test for what happens with central config when invalid configs are registered. We currently only test for the scenario where configs work.

**Comment by urso** [comment]
@ph Is the CM manager still used, or will it be deprecated and removed in the future?

**Comment by ph** [comment]
I am going to keep it open and move it to fleet project.

**Comment by ph** [comment]
No needed anymore.
