### ISSUE TITLE
[Docs] Duplicate envoyproxy in metricbeat modules 

### ISSUE THREAD

**Issue by johtani** [elastic/beats#8759]
Duplicate envoyproxy in Table of Contents for metricbeat

<img width="912" alt="screen shot 2018-10-26 at 16 06 47" src="https://user-images.githubusercontent.com/1142449/47552551-ed2b3900-d93f-11e8-893f-f2d795765486.png">

And the envoyproxy module page is separated. It should be 1 page.
Page 1: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-envoyproxy.html
Page 2: https://www.elastic.co/guide/en/beats/metricbeat/current/_envoyproxy_module.html

**Comment by ruflin** [comment]
Thanks @johtani for pointing this out. @sayden Can you have a look at this? I think the issue is that we have the title on the module asciidoc but switched to generating it automatically a few months ago so it needs removal in the module asciidoc.
