### ISSUE TITLE
Docker autodiscover docs are incomplete

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#8803]
The `Host`, `TLS`, and `Prefix` [options](https://github.com/elastic/beats/blob/master/libbeat/autodiscover/providers/docker/config.go#L27) for the docker autodiscover provider are not documented anywhere. This came up when reviewing this [discuss post](https://discuss.elastic.co/t/filebeat-autodiscover-when-running-on-windows-filebeat-can-not-be-started/153801).

New options added in elastic/beats#10905 (`cleanup_timeout`) and elastic/beats#10911 ( `default.disable`) are also not documented in autodiscover doc page.

We should fully document these.

**Comment by jsoriano** [comment]
Cleanup timeout added in #10905 and default disable added in #10911 should be added too, I will update description.
