### ISSUE TITLE
Add output version to state API endpoint

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#8804]
To better understand the versions of Elasticsearch, Logstash, Kafka and Redis Beats are used with, the version of theses services should be reported as part of the state endpoint.

The current reporting looks as following for `http://localhost:5066/state`:

```
...
output: {
   name: "elasticsearch"
}
...
```

The version number should be added as following:
```
...
output: {
   name: "elasticsearch",
   version: "6.4.2"
}
...
```

The version number should be reported for all the outputs where it's available.

**Comment by ruflin** [comment]
@tbragin FYI

**Comment by ruflin** [comment]
@urso @ycombinator Perhaps one of you could take this on?

**Comment by ruflin** [comment]
I'm happy if we start with ES only as I think it's the most important one to know because of compatibility with Ingest pipelines, dashboards etc.

**Comment by danishprakash** [comment]
Mind if I pick this up?
