### ISSUE TITLE
[heartbeat] Dashboard broken in 6.5

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#8812]
In 6.5 the pie chart diagram for the up/down status of monitors in the heartbeat dashboard is broken due to some stricter parsing on the values used in filters. We had specified in the UI `monitor.status: up`. Changing it to `monitor.status:up` (removing the extra whitespace) fixed it.

Thanks to @DanRoscigno for bringing this to my attention.

**Comment by ruflin** [comment]
I wonder if this will affect other dashboards too?

**Comment by andrewvc** [comment]
@ruflin that is correct. This is now a kibana blocker https://github.com/elastic/kibana/issues/24838

I'm going to close this for now. If, somehow this gets pushed back to us, we can reopen.
