### ISSUE TITLE
Some ingest pipelines fail to parse hostnames with underscores

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#8814]
Log lines including hostnames with underscores fail to be parsed, this affect all pipelines using directly or indirectly the [`HOSTNAME` pattern](https://github.com/elastic/elasticsearch/blob/v6.4.2/libs/grok/src/main/resources/patterns/grok-patterns#L30), that is included in `SYSLOGHOST`, `IPORHOST`, `HOSTPORT` and possibly others.

There was a [discussion](https://github.com/logstash-plugins/logstash-patterns-core/pull/107) in the logstash plugin about accepting underscores, but at the end it was proposed to use other patterns for that.

Issue found after report in discuss: https://discuss.elastic.co/t/ssh-field-not-showing-up-with-system-module/154599

**Comment by sayden** [comment]
What's the approach we must follow to fix this? I mean, I see two approaches:

* Replace all pipelines with a customized _HOSTNAME_ pattern that fix this
* Update the original _HOSTNAME_ pattern (where? here? https://github.com/elastic/elasticsearch/blob/v6.4.2/libs/grok/src/main/resources/patterns/grok-patterns)

I have done some tests with this pattern `\b(?:[0-9A-Za-z][_0-9A-Za-z-]{0,62})(?:\.(?:[0-9A-Za-z][_0-9A-Za-z-]{0,62}))*(\.?|\b)` and it seems to work

**Comment by jsoriano** [comment]
Thanks for investigating this :slightly_smiling_face: 

> What's the approach we must follow to fix this?

I don't have a clear answer.

I'd prefer the approach of supporting these hosts in the grok patterns, I also opened an issue for that https://github.com/elastic/elasticsearch/issues/35081 (that hasn't generated a lot of interest :slightly_smiling_face:).

The problem with replacing all filebeat pipelines with a custom pattern is that we don't only need to replace `HOSTNAME`, but also many of the patterns that make use of this one, like `SYSLOGHOST`, `IPORHOST`, `HOSTPORT`. And after that we have to maintain these patterns. I think that whatever solution we give should be consistent along the stack.

**Comment by sayden** [comment]
I have created this draft PR only to show how it would look like to modify every module: https://github.com/elastic/beats/pull/13136

I think that it's better to have consistency between the stack as you suggested too. As you can see in the PR, every pattern that uses `HOSTNAME` must be override inside the Pipeline so, definitely, not nice.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.

**Comment by daneengquist** [comment]
Hi @jlind23 - I have a customer that seems to be running into this. Is there any way for them to use a processor to remove underscores interpreted from a log or some other workaround the customer can implement?
