### ISSUE TITLE
Negative HTTP responsetime

### ISSUE THREAD

**Issue by sk163** [elastic/beats#882]
why responsetime less than 0?
![packetbeat_bug](https://cloud.githubusercontent.com/assets/2271609/12668467/a8a8e94e-c691-11e5-8c90-05ddb8eca107.jpg)

**Comment by ruflin** [comment]
Hi @sk163 

I assume you use filebeat with logstash as filebeat itself does not have a responsetime. For questions and discussions please use https://discuss.elastic.co/c/beats/filebeat Make sure to provide all the information listed here: https://discuss.elastic.co/t/beats-how-to-report-an-issue/38301 I'm closing this issue but looking forward to discuss it on discuss.

**Comment by monicasarbu** [comment]
The same issue was reported https://discuss.elastic.co/t/negative-http-responsetime/59988

**Comment by Elufimov** [comment]
I see it too. 
Windows server 2012 r2/Windows server 2016
packetbet 5.4 and lower
winpcap 4.1.3/npcap 0.86
