### ISSUE TITLE
Geo data format not match with the kibana-dashboard

### ISSUE THREAD

**Issue by yeasy** [elastic/beats#883]
Using packetbeat and https://github.com/elastic/beats-dashboards.

Both the version is 1.0.1.

However, the packetbeat generate geo point string like "35.994003, -78.898598", while the dashboard require a geo_point type.

This can repeat by using the code at https://github.com/yeasy/docker-compose-files/tree/master/packetbeat_ek.

**Comment by edwardsb** [comment]
I can't get any geo_point data to show up. I have the config file pointing to my GeoLiteCity.dat file location:

# Configure local GeoIP database support.
  # If no paths are not configured geoip is disabled.
  geoip:
    paths:
      - "/users/edwardsb/Downloads/GeoLiteCity.dat"

Where am I going wrong?

**Comment by andrewkroh** [comment]
Closing due to age. Packetbeat no longer does geoip enrichment because this can be done by Elasticsearch Ingest Node.
