### ISSUE TITLE
All beats should have a standardized way to report progress counts

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#884]
Filebeat has a nice way to report progress via `logp.Info("Events sent: %d", len(events))` which is written out to the `info` logging level.  Topbeat is missing such progress entries, it will be nice to write something out periodically like filebeat at periodic intervals so that admins can tell that topbeat is still functioning normally.  And of course, will be nice to standardize such messaging across all beats.

**Comment by cleesmith** [comment]
Agreed, this would be nice.

**Comment by ruflin** [comment]
To standardise this across beats, it would be best to have such a counter with the log line on the libbeat side.

**Comment by ruflin** [comment]
All beats now write every 30 seconds a stats report. Closing this issue.
