### ISSUE TITLE
Falling test on metricbeat system/socket_summary output

### ISSUE THREAD

**Issue by ph** [elastic/beats#8848]
I am hitting the following failure on Metricbeat 6.5 and master.

https://travis-ci.org/elastic/beats/jobs/448818231

```
======================================================================
ERROR: Test system/socket_summary output.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/gopath/src/github.com/elastic/beats/metricbeat/tests/system/test_system.py", line 473, in test_socket_summary
    summary = evt["system"]["socket"]["summary"]
KeyError: 'system'

----------------------------------------------------------------------
```
I've looked at the existing issue in our repo and I found this one https://github.com/elastic/beats/issues/7973, but the fix was for windows and I've seen it fails on darwin.

**Comment by ph** [comment]
@jsoriano have you seen this one?

**Comment by jsoriano** [comment]
@ph no, this is new for me, I wonder why it has started to fail now. OSX image in travis hasn't changed. Have you been able to reproduce it locally?

**Comment by jsoriano** [comment]
@ph btw, I don't think #7973 is related, do you mean #7868? For Windows there is no implementation, this is why we disabled the test for this OS, but it should work for OSX.

**Comment by ph** [comment]
I meant https://github.com/elastic/beats/issues/7868.
I've tested it locally on OSX

```
======================================================================
ERROR: Test system/socket_summary output.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ph/go/src/github.com/elastic/beats/metricbeat/tests/system/test_system.py", line 473, in test_socket_summary
    summary = evt["system"]["socket"]["summary"]
KeyError: 'system'

----------------------------------------------------------------------
```
same error, I am running macOS mojave.

**Comment by jsoriano** [comment]
This is also failing in Jenkins since https://beats-ci.elastic.co/job/elastic+beats+master+multijob-darwin/beat=metricbeat,label=macosx/156/

**Comment by ph** [comment]
I think I know why, I believe I am the responsable for that, le me take a quick look.

**Comment by ph** [comment]
@jsoriano Its my bad, I though it was a flaky test and I was wrong.

I've created the PR https://github.com/elastic/beats/pull/8849 to fix it.

**Comment by ph** [comment]
@jsoriano Its my bad, I though it was a flaky test and I was wrong.

I've created the PR https://github.com/elastic/beats/pull/8849 to fix it.
