### ISSUE TITLE
Functionbeat: Add integration tests for cloudwatch

### ISSUE THREAD

**Issue by ph** [elastic/beats#8850]
Integration tests for functionbeat:

- Create function
- Create function when log group doesn't exists
- Create function if the lambda already exists
- Remove function
- Remove a function that doesn't exist.

**Comment by jlind23** [comment]
We endeavor to address Functionbeat use cases via the new Serverless Forwarder project (https://github.com/elastic/elastic-serverless-forwarder)with a better integration with serverless functionality provided by major cloud providers. Enhancements to the current Functionbeat will therefore be limited.
