### ISSUE TITLE
Move back to goformation original repository

### ISSUE THREAD

**Issue by ph** [elastic/beats#8857]
Because of some compiler issues on windows with the long filename use in the goformation library. We are currently using our own fork to make the compiler works on windows.

Upstream issue at https://github.com/awslabs/goformation/issues/138

**Comment by andrewkroh** [comment]
Will your changes to jenkins_ci.ps1 allow us to move back to the upstream version?

**Comment by ph** [comment]
@kvch Since you are upgrading some libraries we could also upgrade the `goformation` sdk they have fixed the windows issues so could depend on the official repository instead of my fork.

**Comment by kvch** [comment]
I updated the PR: https://github.com/elastic/beats/pull/15231
