### ISSUE TITLE
Uptime monitoring curated dashboard for AWS/Docker/K8s

### ISSUE THREAD

**Issue by dov0211** [elastic/beats#8860]
Since we are developing the AWS autodiscovery capabilities in heartbeart we should consider providing a curated experience for the end user, we could extend it for Docker/K8s as well
here are some examples from the infra Ops solution
![image](https://user-images.githubusercontent.com/38371227/47816192-193d2480-dd5b-11e8-82be-8f4bde8097fe.png)
![image](https://user-images.githubusercontent.com/38371227/47816242-425db500-dd5b-11e8-82eb-f524eff61e31.png)
![image](https://user-images.githubusercontent.com/38371227/47816286-6620fb00-dd5b-11e8-87a8-810ab235b792.png)
@andrewvc @justinkambic

**Comment by andrewvc** [comment]
The AWS PR is #8680

**Comment by shahzad31** [comment]
@justinkambic  and @andrewvc i think this more or less relates to https://github.com/elastic/uptime/issues/81 and https://github.com/elastic/uptime/issues/21
Once we have custom filter saving option, we can open a curated status page or dashboard page for those filtered monitors. For example we can create a filter for Docker and click on that filter to lead to curated dashboard.
