### ISSUE TITLE
Idea: Strictly require synthetic PK for all heartbeat monitors

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#8862]
One thing we'd like to do in the future is reconcile monitoring data from a heartbeat monitor to a specific item that has been centrally configured. Ideally, we would be able to edit that centrally configured item, and cross link from read views of the monitor to update views.

Currently monitors are uniquely identified by a combination of attributes, or a natural PK in SQL speak, that is the synthesis of some but not all fields. This leads to a number of problems.

The problem with this is that determining exactly which centrally configured item created the monitor is not strictly possible.

I propose that we attempt to fix this by requiring users to create a synthetic PK for each created monitor in 7.0+ versions of heartbeat.

**Edit**: Users would also be able to add a human readable `name` field for use in error messages and the like. The `id` field must be a token that never changes, while the name field would be free-form text, and also searchable.

This would mean that monitors would look like the following going forward:

```
heartbeat.monitors:
- id: myMonitorName
  name: My Monitor Name
  type: tcp
  hosts: ["127.0.0.1:1234"]
```

This ID would be reflected in the `monitor.id` field in our schema, which currently looks like `tcp-tcp://127.0.0.1:1234`.

The positive effects would extend beyond just a future GUI. Including a unique ID in alerts, for instance, would let users more easily pinpoint the check used in any config files.

**Comment by ruflin** [comment]
@exekias @urso I remember we discussed similar things for prospectors and modules in the past to identify them. 

@andrewvc What about only making it a requirement if users want to have these additional features?

**Comment by andrewkroh** [comment]
+1 to the idea. Like @ruflin this concept would be very helpful in modules, prospectors, winlogbeat event_logs, or any case where there is persistence, but no stable means of identification.

**Comment by andrewkroh** [comment]
> That would make detecting duplicates much easier, and be more concise syntactically.

Or would duplicates be silently ignored with our current config code?

**Comment by ruflin** [comment]
Currently duplicates would be silently ignored AFAIK. @urso might know more.

Alternative to keep compatibility:

```
heartbeat.monitors:
  -  type: tcp
      hosts: ["127.0.0.1:1234"]

heartbeat.monitor.myMonitorName:
    type: tcp
    hosts: ["127.0.0.1:1234"]
```

I would like to prevent that on upgrade to 7 all users have to rewrite all monitors.

**Comment by ruflin** [comment]
Additional thought after I sent the above. The advantage of the initial proposal is that with central management monitors could be "upgraded". Meaning a monitor is started without a name, then central management is used to assign a name. Form heartbeat perspective it will be a new monitor but from the central management perspective it could be just "updating" a config and the old one is stopped.

**Comment by exekias** [comment]
I'm wondering if the extra burden for the user is worth it here.

If we need this to solve something in central management, why not solving it there? This unique id could be added in central management, giving a clear path to identify each config. The beat can get awareness of that when reporting issues to CM (or even in the reported events).

Translating this to other beats would have some problems too, how would this play with the `enable module` logic?

**Comment by andrewvc** [comment]
I think the upgrade case cinches it for me. Let's keep the list and add the property. It's a big ask to rewrite everything on an upgrade.

I do think we should, however, have a warning for configs without a PK however.

**Comment by urso** [comment]
Is this some feature we strictly consider for CCM only? For CCM we will have to introduce some generated/configurable ID anyways. With the tags functionality we have in CCM, actual beats, tags + configs are somewhat orthogonal. The PK for one module will consist of: beats UUID + tag name + config ID within tag. This proposal is about adding the later one. For CCM only it doesn't really matter who defines/configures the ID.

We will need the ID/PK for CCM, so we can correlate errors/logs/metrics with centrally configured modules for display in the UI.

In general I like this idea. Also will make it easier for users to figure out there is a change. But heartbeat potentially creates a many tasks jobs per monitor. And so do filebeat/metricbeat modules. The unique PK will still be based on ID+moduleset+host?


> Thinking about it further, what does everyone think about enforcing this by changing the config structure to a map instead of a list. That is:

+1 on using a map. We're thinking about using maps and list-style configs interchangeable for quite some time. Actually go-ucfg event stores them in the same data-structure, so to treat them the same. Exactly with this use-case in mind. Problem is the YAML parser we use. The YAML parser does not detect duplicates, but happily replaces your old key-value pair without notice :( (It's yet another area needing improvement).

**Comment by andrewvc** [comment]
@urso I like the idea of opting in by converting to map, it's definitely the cleaner datastructure.

I think for the PK to be unique it needs to be the hash of all values in the config, not just a limited set of fields. That's of course the great thing about synthetic PKs. If the user changes a field like `timeout`, the hash wouldn't change.
