### ISSUE TITLE
Autodiscover should not require identical metadata for start/stop events

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#8863]
I'm currently in the process of writing an AWS ELB autodiscover adapter in #8680 .

One design issue I'm hitting, which probably didn't come up before, is that the event data published here is mutable. In other words, an ELB might be in a different state at stop than start, yielding different metadata. This is important because autodiscover de-duplication and stop/start code relies on hashing metadata consistently.

This breaks with AWS autodiscover since a number of items in the metadata are mutable. While it may be possible to remove those, it would be better to not handicap this provider.

I propose that we modify the autodiscover code to have two paths. One for the current method, and the other using a synthetic PK, which in the case of AWS is an item's `ARN`. 

This would mean that we would maintain a second hash table per provider in `autodiscover.go` for items of this type of the . form `map[string][]config`, where `string` is that synthetic PK and `[]config` is the list of configs rendered for that unique resource.

**Comment by ruflin** [comment]
@exekias Would be great to get your opinion on this one.

**Comment by exekias** [comment]
Interestingly enough, I started just this 18h ago: https://github.com/elastic/beats/pull/8851 :smile:

**Comment by andrewvc** [comment]
I actually don't need the current path so one works for me!
