### ISSUE TITLE
FreeBSD-10-i386 + VIA-C3 processor + filebeat-freebsd-386 1.2.0-NIGHTLY build 229 (2016-01-29T14:18:30) = illegal hardware instruction

### ISSUE THREAD

**Issue by bsamorodov** [elastic/beats#887]
Hi All!

I have a couple of hosts running FreeBSD 9/10/11 i386/amd64 with filebeat. All hosts but one run filebeat just fine. Here is the error at the problem host.

`% ./filebeat-freebsd-386 -version`
`illegal hardware instruction (core dumped)`

The system:
`% uname -srm`
`FreeBSD 10.2-RELEASE-p9 i386`

The processor:
`FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
CPU: VIA Samuel 2 (532.65-MHz 686-class CPU)
  Origin="CentaurHauls"  Id=0x673  Family=0x6  Model=0x7  Stepping=3
  Features=0x803035<FPU,DE,TSC,MSR,MTRR,PGE,MMX>
  AMD Features=0x80000000<3DNow!>
real memory  = 536870912 (512 MB)`

Gdb session:
`#0  runtime.check () at /home/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/1.5.3/src/runtime/runtime1.go:146`

Thank you
-- 
bsam

**Comment by andrewkroh** [comment]
This looks to be relevant. https://groups.google.com/forum/#!topic/golang-nuts/SmY82rp7QQU It could be that this processor isn't supported by Go.

**Comment by bsamorodov** [comment]
Yep, seems so. Thanks!

Just a note. Well, if go generates code for P-PRO, then the binary should be named as filebeat-586, as opposed to filebeat-386.

**Comment by andrewkroh** [comment]
I don't disagree. The naming follows from the GOOS and GOARCH values used when cross-compiling using the Go compiler. See https://golang.org/doc/install/source#environment

**Comment by bsamorodov** [comment]
That's it. Thanks.
