### ISSUE TITLE
Do not collect CCR metrics unless user has appropriate license

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#8915]
Currently, running the `elasticsearch/ccr` metricset against an Elasticsearch cluster with a Basic license will cause the following documents to be indexed into `metricbeat-*` indices:

```
   ...
   },
    "metricset": {
      "host": "localhost:9200",
      "rtt": 7337,
      "name": "ccr",
      "module": "elasticsearch"
    },
    "error": {
      "message": "HTTP error 403 in ccr: 403 Forbidden"
    }
```

This is because CCR is not available with a Basic license.

The `elasticsearch/ccr` metricset should detect the license and only attempt to collect CCR metrics if the license is appropriate.

**Comment by ruflin** [comment]
What happens if the license changes over time?

If someone configures CCR I kind of expect that the users want to monitor it. This changes a bit if it's part of our defaults means if the user does configure no metricsets and ccr is in there. We should come up of with a nice way of notifying the user that his config might be wrong.

**Comment by ycombinator** [comment]
What do you think about checking the license in the `Fetch` method of the `ccr` metricset? If the license is incorrect, we can emit a log message telling the user to disable/remove the `ccr` metricset from their configuration or make sure they have the right license?

The only issue I see with this is that we might spam their log every 10s. Maybe we can keep a timer to prevent that and only emit the message every minute or something instead?

Another idea, probably for the longer term, might be to keep the existing functionality (of recording the 403 error in the `metricbeat-*` indices) and having the Monitoring UI display an actionable error message.

**Comment by ruflin** [comment]
I like the idea of moving the check into CCR so it's all in the metricset itself. As each metricset can have a state we can store in the metricset when we checked last as then report it every x units as you proposed above.

We can even combine the two approaches and check ones, log an error and send an error event so also the UI is aware of it but we don't spam docs and logs.

**Comment by ycombinator** [comment]
I'm going to keep the UI-related functionality for later, once all data is going into `metricbeat-*` indices (and not `.monitoring-*` indices). In any case, no point logging errors into `metricbeat-*` until the UI is ready to read from them. /cc @chrisronline as a heads up on this idea + if you have any comments here as well.

For the immediate term to make progress on this issue, I'm going to just implement the logging every x units as discussed above.

**Comment by ycombinator** [comment]
I take back what I said above about only logging and not reporting the error for now. Looks like we're already doing both in many other cases. So I'm going to follow your suggestion of combining both approaches: the `Fetch` method will check every 10s (or whatever the configured `period` is) but only log and report the error every minute so as to not spam the log and index too much.

**Comment by chrisronline** [comment]
Yea I think it makes sense to notify in two places: in the metricbeat log itself but also persist the error into the monitoring docs so the UI can also notify

**Comment by ruflin** [comment]
To clarify my comment above: I think we should only not repeat errors if it's a license issue. In other cases if CCR for whatever reason is not available or reports and error back, we should report the error every time.

**Comment by ycombinator** [comment]
@ruflin A couple of questions about your latest comment, especially in light of the discussion @jsoriano and I are having [on the PR](https://github.com/elastic/beats/pull/9003):

>  I think we should only not repeat errors...

Just to clarify, I thought you [said earlier](https://github.com/elastic/beats/issues/8915#issuecomment-436224252) that it was okay to repeat errors, just at a lower frequency.

> ... if it's a license issue. In other cases if CCR for whatever reason is not available or reports and error back, we should report the error every time.

In [my discussion with @jsoriano on the PR](https://github.com/elastic/beats/pull/9003#discussion_r232160744), we agreed to treat the license issue and also the API unavailability issue (due to running an older version of ES) as the same when it comes to error reporting. Are you okay with this approach? For all other errors, we are treating them as we do usually in our metricsets.

**Comment by ruflin** [comment]
I think overall we are on the same page. Let's sync up separately on what our general approach is for when we send a error event and when we log an error. The two must not necessarily have the exact same behaviour.
