### ISSUE TITLE
metricbeat - filesystem & fsstat not collecting mount path on windows machines

### ISSUE THREAD

**Issue by HawkUser** [elastic/beats#8916]
Hi,

it's look like the metricbeat not collecting any data of devices without drive letter on windows machines (mount path), the reason for that is metricbeat relay wrong command:
 get-psdrive -PSProvider filesystem
this powershell syntax by design not returning mount path.
they should relay on different command:
Get-WmiObject Win32_Volume | Format-Table Name, Label, FreeSpace, Capacity

metricbeat 6.2.4

**Comment by jsoriano** [comment]
I have started [a branch](https://github.com/jsoriano/gosigar/commits/windows-filesystems-without-letter) to try to list filesystems using WMI, with this I have managed to list volumes configured with access paths but without a drive letter.
I still have to do some tests with this.

**Comment by jsoriano** [comment]
This should be fixed by #10196
