### ISSUE TITLE
[Module Request] Metricbeat modules for Tomcat, Websphere and Weblogic

### ISSUE THREAD

**Issue by yaronp68** [elastic/beats#8922]
This request makes sense since it's probably a low hanging fruit using jolokia
Tomcat, Websphere and Weblogic are still widely used with Java apps in the enterprise
Monitoring should include the common JVM heap, GC, CPU and threads information but can be extended through additional JMX beans to cover additional metrics. 
- Websphere App server has IBM instrumentation through PMI that is accessible through JMX
- Weblogic App server can be monitored via JMX mbeans
- Tomcat can be monitored using JMX mbeans
Things that can be covered are
- servlet response time
- threadpools 
- JDBC connection pools
- number of active sessions
and more

**Comment by andresrc** [comment]
Tomcat metricbeat integration: #13860
