### ISSUE TITLE
filebate stop api

### ISSUE THREAD

**Issue by zhaoya881010** [elastic/beats#8955]
hi,
  i plan to use filebeat as a module in my agent application.
in my code:
       ......
	if err := cmd.RootCmd.Execute(); err != nil {
		fmt.Println(err.Error())
	}
     ......
i have a question?i not found stop api,reset filebeat and  reboot my app?

**Comment by zhaoya881010** [comment]
i am use global filebeat fb and fb.Stop() it's ok.

**Comment by jsoriano** [comment]
Hi @zhaoya881010,

Yes, you should be able to use the `Stop()` method.

Please, use [discuss](https://discuss.elastic.co/) for questions on Beats usage or its APIs.
