### ISSUE TITLE
[Dashboards] Kuberentes Top CPU Intensive pods visualisation shows error

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#8957]
* Version: 6.5-Snapshot

After loading the dashboards into Kibana for Kubernetes, the "Top CPU Intensive pods [Metricbeat Kubernetes]" visualisations shows an error (see screenshot below).

![screen shot 2018-11-07 at 09 19 35](https://user-images.githubusercontent.com/244900/48120178-af001480-e271-11e8-96be-f1b669186d9d.png)

**Comment by ruflin** [comment]
This seems to also affect the system dashboards. @simianhacker you might now more. Looks like the `Positive only` feature.

**Comment by ruflin** [comment]
I tested the same with 6.4.3 and the issue does not seem to exist there.

**Comment by exekias** [comment]
As @ruflin said, System dashboard (and maybe others) is affected too  This is how it looks:

![image](https://user-images.githubusercontent.com/299804/48127599-66058b80-e284-11e8-83f9-083da80c2d54.png)

We may need to consider this a blocker. Thoughts?

cc @tsg @monicasarbu @tbragin

**Comment by tsg** [comment]
Closing for now, we have https://github.com/elastic/elasticsearch/issues/35351 as a follow up.
