### ISSUE TITLE
Improve docs generator for exported fields 

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#897]
Related to: https://github.com/elastic/beats/pull/890

The generated docs for the exported fields looks ok except the fact that the indentation is bad for some fields. 
![screen shot 2016-02-01 at 7 13 36 pm](https://cloud.githubusercontent.com/assets/11757159/12726529/62c4d09e-c918-11e5-93e9-4313474f7fec.png)

**Comment by dedemorton** [comment]
@monicasarbu  It looks like asciidoc does not support level 5 headings (this might be a limitation of our doc build, but I think it's an asciidoc limit). Most doc folks would argue that anything beyond a 4th level heading introduces too much nesting.

**Comment by ruflin** [comment]
It looks like fields.yml != docs indentation in the future. Because I think from a logical perspective the indentation is correct, but not from a user perspective.

**Comment by monicasarbu** [comment]
@ruflin I am wondering what has changed as it used to work in the previous version. Somehow a new level of identention is added everywhere.

**Comment by monicasarbu** [comment]
@ruflin @dedemorton  In the previous version of the script, to avoid these errors, I used "===" for the title defining the group section and "====" for each field. I think the result looks much nicer like this, so I "reverted" to the old version in the PR #901. Please see attached a screenshot with the result in the PR.

**Comment by ruflin** [comment]
Closing this as #901 was merged and we made further improvements here.
