### ISSUE TITLE
Beats setup does not support kibana on a subpath

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#8976]
We should support kibana running on a sub path. Will fill in more detail later.

**Comment by webmat** [comment]
Tip: to test Kibana nested at a path, you don't need to set up a local web server proxying to it.

You just need to build kibana from source, run it with `yarn start` and make sure **not** to pass the `--no-base-path` argument. Every time you start it, it'll be nested under an arbitrary 3 letter path.

**Comment by kvch** [comment]
@andrewvc Could you please add more details about this issue?
