### ISSUE TITLE
Metricbeat failed to parse metrics.

### ISSUE THREAD

**Issue by kuzm1ch** [elastic/beats#8987]
Similar to `https://github.com/elastic/beats/issues/8773` but related to metricbeat.

- Version: 
metricbeat: 6.4.2
kubernetes: v1.10.6
kube-state-metrics: k8s.gcr.io/addon-resizer:1.8.3

error: 
`(status=400): {"type":"mapper_parsing_exception","reason":"object mapping for [kubernetes.labels.role] tried to parse field [role] as object, but found a concrete value"}` 

why this issue occurred: 
for k8s component 
quay.io/calico/node:v2.6.7
quay.io/calico/cni:v1.11.2
quay.io/calico/kube-controllers:v1.0.3

```
kubernetes.labels.role: 
{
  "kubernetes": {
    "io/networking": "1"
  }
}
```
should be parse as kubernetes.labels : role.kubernetes.io/networking=1 
because what we have an k8s calico default pod 
`kubectl describe pods ...`
```
Labels:         controller-revision-hash=2862843400
                k8s-app=calico-node
                pod-template-generation=1
                role.kubernetes.io/networking=1
```
The same issue exist for ingress-nginx `kubernetes.labels.app`: 
```
Labels:         app.kubernetes.io/name=ingress-nginx
                app.kubernetes.io/part-of=ingress-nginx
                pod-template-hash=944731672
```

**Comment by jsoriano** [comment]
Hi @kuzm1ch, thanks for taking the time of reporting this issue. I think it is the same problem as in #8773. I am going to close this one so we keep all discussions in the same thread.
