### ISSUE TITLE
Filebeat: 'fields' should be omitted when null

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#899]
When have no `fields` configured in my filebeat.yml I get `null` in all published events. This seems to be a regression of elastic/filebeat#126.

```
    ...
    "count": 1,
    "fields": null,
    "input_type": "log",
    ...
```

Relavant source: https://github.com/elastic/beats/blob/master/filebeat/input/file.go#L78

**Comment by crashev** [comment]
This seems to be still a problem in 1.2.3 version

**Comment by monicasarbu** [comment]
Closing this issue as it won't be fixed in the 1.x versions.
