### ISSUE TITLE
Document API for enrolling beats in central management

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#9001]
Beats central management was added in 6.5, but the API for enrolling Beats is not yet document. Users need to enroll through the UI.

**Comment by dedemorton** [comment]
@mattapperson Is there progress on this? Need help? Let me know!

**Comment by mattapperson** [comment]
@dedemorton We have been making changes to the API, significant ones, and wanted to ensure the API is what it needs to be for GA before taking the time to document. That said, it's starting to look good. I think we are 1 or 2 smaller changes away from being ready to call it stable enough to document. I am thinking no later then the end of Feb it will be good to go.

**Comment by dedemorton** [comment]
@mattapperson It sounds like other teams (Kibana, cloud) plan to someday use OpenAPI to generate the API docs. Right now, they aren't generating the API docs, but they are following the same basic structure. 

If we can use OpenAPI to generate the docs, that would be ideal (not sure what is possible from your perspective).

But even if can't, we should the same format that they are following. Here’s an example:  https://www.elastic.co/guide/en/kibana/6.6/saved-objects-api-get.html.

**Comment by dedemorton** [comment]
Closing because this work is no longer required.
