### ISSUE TITLE
Add documentation about filebeat pipelines setup

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#9037]
Filebeat is able to automatically install the required ingest pipelines when it has Elasticsearch as output.

Since filebeat 6.3.0 `filebeat setup` is able to install pipelines using the `--pipelines` flag, this allows to install the pipelines by an operator when filebeats don't have Elasticsearch as output (in architectures with logstash, kafka...).

There is documentation in the [guide](https://www.elastic.co/guide/en/beats/filebeat/6.5/filebeat-getting-started.html) about installing index templates and kibana dashboards, but not about pipelines, and it can be difficult to know when it is needed to do it manually and how to do it.

**Comment by ruflin** [comment]
Related to https://github.com/elastic/beats/issues/9268

**Comment by dedemorton** [comment]
I've added some docs for LS that contains more info about loading and using ingest pipelines with Logstash. I'll add a link to the Filebeat doc after the LS PR is merged: https://github.com/elastic/logstash/pull/10438

**Comment by dedemorton** [comment]
I've also created a PR to add some links in the Beats docs that point the new content in the Logstash docs: https://github.com/elastic/beats/pull/10859.

Closing this issue because I think it's covered now.
