### ISSUE TITLE
Metricbeat parse docker image and node labels error 

### ISSUE THREAD

**Issue by opsnull** [elastic/beats#9038]
- Version: metricbeat 6.4.3
- Operating System:  centos 7.5
- Discuss Forum URL: 
  https://discuss.elastic.co/t/metricbeat-parse-docker-image-labels-error/152986
  https://discuss.elastic.co/t/metricbeat-kubernetes-module-state-node-metricset-failed-to-parse-node-labels/156269

# metricbeat parse node lable error：
```
$ kubectl get node  m7-devops-128071 --show-labels
m7-devops-128071 Ready <none> 110d v1.8.15 active=true,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,es-data=true,ip-masq-fix=true,kubernetes.io/hostname=m7-devops-128071,mysql-master=true,node.alpha.4pd.io/group-0816=true,node.alpha.4pd.io/group-group1112=true,project=maze.ingress,prophet.4paradigm.com/addon=true,prophet.4paradigm.co
m/app=true,prophet.4paradigm.com/elasticsearch=true,prophet.4paradigm.com/gpu=true,prophet.4paradigm.com/offline=true,prophet.4paradigm.com/online=true,prophet.4paradigm.com/prometheus=true,prophet.4paradigm.com/rtidb-nameserver=true,prophet.4paradigm.com/rtidb-tablet=true,prophet.4paradigm.com/system=true,prophet=true
```

metricbeat log：

> 2018-11-12T17:54:45.479+0800 WARN elasticsearch/client.go:520 Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Time{wall:0xbef27156c82fe362, ext:1463147003462, loc:(*time.Location)(0x37e0b20)}, Meta:common.MapStr(nil), Fields:common.MapStr{"metricset":common.MapStr{"host":"172.27.128.71:8794", "rtt":9019564, "namespace":"kubernetes.
> node", "name":"state_node", "module":"kubernetes"}, "kubernetes":common.MapStr{"labels":common.MapStr{"ip-masq-fix":"true", "node":common.MapStr{"alpha":common.MapStr{"4pd":common.MapStr{"io/group-group1112":"true"}}}, "beta":common.MapStr{"kubernetes":common.MapStr{"io/os":"linux", "io/arch":"amd64"}}, "kubernetes":common.MapStr{"io/hostname":"m7-devops-128071
> }, "prophet":common.MapStr{"4paradigm":common.MapStr{"com/offline":"true", "com/app":"true", "com/elasticsearch":"true", "com/online":"true", "com/system":"true", "com/addon":"true"}, "value":"true"}, "es-data":"true"}, "node":common.MapStr{"pod":common.MapStr{"capacity":common.MapStr{"total":220}, "allocatable":common.MapStr{"total":220}}, "status":common.MapSt
> r{"unschedulable":false, "ready":"true"}, "memory":common.MapStr{"allocatable":common.MapStr{"bytes":2.70272487424e+11}, "capacity":common.MapStr{"bytes":2.70377345024e+11}}, "cpu":common.MapStr{"allocatable":common.MapStr{"cores":40}, "capacity":common.MapStr{"cores":40}}, "name":"m7-devops-128071"}}, "beat":common.MapStr{"name":"metricbeat-128071-bin", "hostna
> me":"m7-devops-128071", "version":"6.4.3"}, "host":common.MapStr{"name":"m7-devops-128071", "id":"61432cc588f747f4aec71029ea9e9408", "containerized":true, "architecture":"x86_64", "os":common.MapStr{"platform":"centos", "version":"7 (Core)", "family":"redhat", "codename":"Core"}}}, Private:interface {}(nil)}, Flags:0x0} (status=400): {"type":"mapper_parsing_exce
> ption","reason":"failed to parse [kubernetes.labels.node]","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:222"}}

# metricbeat parse image label error

docker version：18.06.0-ce

```
{
  "_index": "metricbeat-power-6.4.1-2018.10.18",
  "_type": "doc",
  "_id": "yD3PhmYBo726M9O3TIlB",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2018-10-18T10:53:25.167Z",
    "metricset": {
      "module": "docker",
      "host": "/var/run/docker.sock",
      "rtt": 49248,
      "name": "image"
    },
    "docker": {
      "image": {
        "labels": {
          "org_label-schema_schema-version": "= 1.0     org.label-schema.name=CentOS Base Image     org.label-schema.vendor=CentOS     org.label-schema.license=GPLv2     org.label-schema.build-date=20180531"
        },
        "id": {
          "current": "sha256:d3923d82ce305febd8a9b4c88e949995ebf4b3c725c7388e389c1b1ae40ee6ed",
          "parent": ""
        },
        "created": "2018-10-11T12:39:24.000Z",
        "size": {
          "regular": 352640809,
          "virtual": 352640809
        },
        "tags": []
      }
    },
    "beat": {
      "hostname": "m7-power-128050",
      "version": "6.4.1",
      "name": "m7-power-128050"
    },
    "host": {
      "name": "m7-power-128050",
      "architecture": "x86_64",
      "os": {
        "codename": "Core",
        "platform": "centos",
        "version": "7 (Core)",
        "family": "redhat"
      },
      "id": "14759c8d771e43a2b10f7402e8060d8a",
      "containerized": true
    }
  },
  "fields": {
    "@timestamp": [
      "2018-10-18T10:53:25.167Z"
    ],
    "docker.image.created": [
      "2018-10-11T12:39:24.000Z"
    ]
  },
  "highlight": {
    "beat.hostname": [
      "@kibana-highlighted-field@m7-power-128050@/kibana-highlighted-field@"
    ],
    "metricset.name": [
      "@kibana-highlighted-field@image@/kibana-highlighted-field@"
    ],
    "metricset.module": [
      "@kibana-highlighted-field@docker@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1539860005167
  ]
}
```

**Comment by Mokto** [comment]
Hi,

Just wanted to tell that it is still happening on 6.7.0.

**Comment by exekias** [comment]
Hi,

Starting with 6.7 you can "dedot" labels and annotations to avoid mapping issues when ingesting. This was done here:  #9939 

You should be able to enable the new behavior by passing these parameters to `add_kubernetes_metadata` or `kubernetes` autodiscover provider, whatever you are using:

processors:
 -  add_kubernetes_metadata:
      labels.dedot: true
      annotations.dedot: true

This will be the default starting with 7.0
