### ISSUE TITLE
Heartbeat Task Based Schema Proposal

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#9053]
The current heartbeat schema works great, but for more advanced check, like the one proposed in #9043  we could use a more powerful schema that has a more generic idea of multipart jobs.

## The Situation

Today most heartbeat jobs are often multi-part jobs, by which I mean a check against `http://github.com` will actually execute *two* checks, one for each `A` record in the DNS lookup for `github.com`. This will yield two separate documents which contain the key fields:

```json
{
  "monitor": {"id": "http-http://github.com", "ip": "123.123.123.123"}
}
```

where the `monitor.id` is a unique key for the job (see elastic/beats#8862 for additional thoughts on this), and `monitor.ip` is essentially a subtask for a single `A` record. Consequently, the website may experience a situation where one `A` record host is up, and the other is down. What to make of this situation?

## The Problem

There are a number of problems the current schema does not solve:

1. Is github.com up if one `A` record endpoint is down?
2. How do we know if two given checks were done concurrently? In other words, how do we pair them? Matching similar timestamps?
3. How do we present these graphically?
4. If we create a new monitor type that segments a check by something other than IP, how can the GUI know?

## The Proposal

The proposal here is to:

1. Add the `task_id`, `invocation_id`, `name`, and `task_name` fields to yield the following key fields. Note, that we wouldn't remove or stop using existing fields, but these fields would be the most important ones across monitors:
2. To, for each check, create a summary document rolling up all the data gleaned from each task, and crucially summarizing the state as either up or down. We should mark the summary `monitor.status` as `down` if a single other check fails.

```json
{
  "monitor": {
    "id": "someKeywordIdentifyingTheConfigJobUniquely",
    "name": "Human readable name for this job",
    "task_id": "someKeyIdentifyingTheSubtaskUniquely",
    "task_name": "Human readable name for the task",
    "invocation_id": "Unique ID for this invocation of the task, used to correlate data",
    "type": "typeOfJob"
  }
}
```

So, for a job checking github.com we'd wind up with the following three documents:

```json
{
  "monitor": {
    "id": "http-check-github.com",
    "name": "Check Github HTTP",
    "task_id": "__summary__",
    "task_name": "",
    "invocation_id": "123",
    "type": "http",
    "status": "down",
  }
}
{
  "monitor": {
    "id": "http-check-github.com",
    "name": "Check Github HTTP",
    "task_id": "A:192.30.253.113",
    "task_name": "Check HTTP",
    "invocation_id": "123",
    "type": "http",
    "status": "up",
  }
}
{
  "monitor": {
    "id": "http-check-github.com",
    "name": "Check Github HTTP",
    "task_id": "A:192.30.253.112",
    "task_name": "Check HTTP",
    "invocation_id": "123",
    "type": "http",
    "status": "down"
  }
}
```

This schema would solve all the previously mentioned problems for the following reasons:

*. It would make displaying compound jobs easy, we just display the summary
*. It would make adding new compound jobs like elastic/beats#9043 easy, since you just add a new `task_id`.
*. It would make correlating grouped jobs possible via the `invocation_id`.
*. It would solve the problem of how to present the up or down status of a group of monitors in the GUI. The heartbeat monitor would decide when creating the `__summary__` document.

One thing that we still need to figure out is whether to make two documents for checks with a single task. It feels wasteful to do that. OTOH, it's more consistent. I'm leaning toward consistency.

**Comment by ruflin** [comment]
+1 on the idea to make it possible to correlated "subtasks". I'm not a fan of sending out a summary from Heartbeat as I think this should be a job of Elasticsearch to group the data together. In case multiple Heartbeat instances run on different servers and execute the same tasks, I would expect that the invocation_id can be different but it's the same task_id. The question that then Elasticsearch / the UI must answer what if we have data from 5 servers and 8 out of 10 data points are up, 2 are down. Or as we have 2 IP adresses, 4 for one are up and 4 for the other one are up.

An alternative idea for the `invocation_id` could be that it's a rounded timestamp to the second. Like this it could be the same across servers.
