### ISSUE TITLE
[filebeats] Registry (auto) clean up

### ISSUE THREAD

**Issue by vladimirdolzhenko** [elastic/beats#9064]
Filebeats has been configured to look after some specific file for a while. Later on it has been decided to stop keeping track of this specific file while application is still writing to it while file entry is still in file registry and remaining there (`clean_inactive` / `clean_removed` does not help as well).

The only solution is manual clean up of a registry file that is not very convenient.

**Comment by ph** [comment]
We are in the process of refactoring the registry, pinging @urso for awareness.
