### ISSUE TITLE
Kafka Output Feature

### ISSUE THREAD

**Issue by jeromefroe** [elastic/beats#907]
Hello, I was curious if there were any plans to add a Kafka output for Beats in a future release? We use Kafka in front of our Logstash instances to buffer requests so that any surge in messages does not crash Logstash. At the moment though it does not appear that we can use Beats to ship messages to Kafka which hinders our ability to adopt Beats. Thanks!

**Comment by biswajit86** [comment]
+1

**Comment by jeromefroe** [comment]
After doing a little more research, this feature request is the same as this [one](https://github.com/elastic/filebeat/issues/132) but with Kafka instead of Redis and may therefore be redundant. My apologies.

**Comment by andrewkroh** [comment]
Kafka has been implemented #942 and will be released in [v5](https://www.elastic.co/v5).
