### ISSUE TITLE
The heartbeat monitor script generates the old code

### ISSUE THREAD

**Issue by xu001186** [elastic/beats#9090]
The monitor creates function is using the PluginBuilder type.
type PluginBuilder func(string, *common.Config) (jobs []Job, endpoints int, err error)
However, The "{{monitor}}.go.tmpl" still generates the old type code 

func create(
	info monitors.Info,
	cfg *common.Config,
) ([]monitors.Job, error)

**Comment by andrewvc** [comment]
Where is this `{{monitor}}.go.tmpl` file? It sounds like you tried to create a new monitor. I don't see it in our source.

**Comment by andrewvc** [comment]
Fixed in #9132
