### ISSUE TITLE
Reduce logging frequency of fetch errors

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#9091]
Fetch errors in metricbeat (and maybe in other beats too) are usually logged every time the operation fails, this can lead to flooding logs if some service is down or misconfigured and metricbeat tries to fetch from it every few seconds. Also having lots of repeated errors doesn't help.

Add some kind of helper that can be used in metricbeat fetchers to log errors with less frequency than the collection period. Not sure if this should be added only in metricbeat or in libbeat.
Ideally it should help to log when the error situation starts, and when it gets solved. It could still log something periodically, but with less frequency than the collection period.

Even if errors are not logged or reported because of this, error counters should still be increased.

**Comment by ruflin** [comment]
+1 on this idea. If we get this feature I think it's important that we log all the different errors at least once. For example if we first get a 500 error and then a 404 error, these should be logged separately. It will be interesting on how we manage to log that something was resolved. Sounds like that would need local logic.
