### ISSUE TITLE
Windows packages don't include x-pack binaries

### ISSUE THREAD

**Issue by exekias** [elastic/beats#9096]
I downloaded  https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.5.0-windows-x86_64.zip and it seems `enroll` subcommand is not available.

I've checked the binary resulting from crossbuild and that one is correct, so I believe we are packaging the wrong binary for windows.

This was first reported here: https://discuss.elastic.co/t/filebeat-6-5-0-error-unknown-command-enroll-for-filebeat/156729/4

**Comment by ph** [comment]
building the artifact in the filebeat directory with the following command:

```
PLATFORMS=windows/amd64 mage package
```

It Generates 2 windows artifacts, one OSS and the other with the Elastic license, the elastic one does include the **enroll** subcommand and the oss does not.

**NOTES**: same problem with Metricbeat.

**Comment by ph** [comment]
I will take a look at our Release manager, I suspect the problems is there.

**Comment by ph** [comment]
Okay shame on me, actually I have fixed that in master in #8836. When we assumed the risk we didn't think it had an impact on the packaging generation but we were wrong. I have fixed it and created two backport for https://github.com/elastic/beats/pull/9103 and https://github.com/elastic/beats/pull/9103 https://github.com/elastic/beats/pull/9104

I have added a changelog for both branch.

**Comment by tsg** [comment]
Closed by merging those PRs.
