### ISSUE TITLE
Flaky test:  file_integrity.TestIncludedExcludedFiles on auditbeat/windows

### ISSUE THREAD

**Issue by ph** [elastic/beats#9126]
## Flaky Test

* **Test Name:** file_integrity.TestIncludedExcludedFiles
* **Job**: beat/auditbeat on windows https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-windows/1605/
* **Link:** https://github.com/elastic/beats/blob/master/auditbeat/module/file_integrity/metricset_test.go#L286
* **Branch:** See in https://github.com/elastic/beats/pull/9109 from master

### No Stack Trace

```
assertions.go:256: 
		Error Trace:	metricset_test.go:286
		Error:      	Should be true
		Test:       	TestIncludedExcludedFiles
```

**Comment by andrewkroh** [comment]
This test still fails on occasion on Windows (24 times in last 1 year). So let's keep this open until we do something to make it more robust.

<img width="1329" alt="Screen Shot 2020-01-06 at 10 59 32 AM" src="https://user-images.githubusercontent.com/4565752/71829942-a4a6f980-3073-11ea-9381-25b24d06de1c.png">
