### ISSUE TITLE
Remove Heartbeat Monitor Generation Script

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#9132]
In elastic/beats#9090 @xu001186 reported that our [generator](https://github.com/elastic/beats/tree/master/heartbeat/scripts/generate_monitor) for monitors broke with some internal changes.

This is a seldom used feature, and probably not worth the maintenance burden to document. I propose that we remove all generators for now.

To solve the general problem of users performing custom checks I would propose that we come up with a solution that doesn't require forking / recompilation. Instead we could do something like Nagios' NPAPI, where we invoke a process and use stdin/stdout to check the status of the monitor.

**Comment by ruflin** [comment]
Sounds a lot like the `exec` module we have been discussing for a while (@exekias ).

**Comment by andrewvc** [comment]
I'm realizing that there are two parts to this issue:

1. Is maintaining the monitor generator worth it?
2. Should we make an exec thing.

I'd like us to answer those separately if possible. I think we can remove the generator script without a replacement for now.

**Comment by ruflin** [comment]
+1 on removing the generator script.

**Comment by xu001186** [comment]
Before the new monitor plugin is introduced, it might be a good idea to keep the old template. 
Anyway, I created a shell plugin based on the old template.

**Comment by andrewvc** [comment]
@xu001186 is your shell plugin open source? It'd be awesome to check it out!
