### ISSUE TITLE
[libbeat] add_host_metadata failing on RedHat Linux

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#9134]
On RedHat 7.5 the `host.os.family` is not being populated. The other `host.os` fields are being correctly populated.

The system in question has:

```
$cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```

For confirmed bugs, please report:
- Version: Filebeat 6.4.2
- Operating System: RedHat Linux 7.5

**Comment by willemdh** [comment]
This issue persists on 6.61..

![image](https://user-images.githubusercontent.com/6462991/53171328-bcec6200-35e2-11e9-9b77-3ed56a2721b1.png)
