### ISSUE TITLE
Enhancement: Topbeat ignore some filesystems

### ISSUE THREAD

**Issue by samuraiii** [elastic/beats#914]
It would be nice to have a way to ignore some filesystems from topbeat reports (e.g. nfs mounts...)

**Comment by ruflin** [comment]
I think this could be solved with the filtering in the future: https://github.com/elastic/beats/issues/451

**Comment by monicasarbu** [comment]
This should be easily done using the generic filtering feature where you can drop the event for certain filesystems.

**Comment by andrewkroh** [comment]
If you wanted to be able to filter by filesystem type that would only be possible if Topbeat was enhanced to report the filesystem type (e.g. nfs, ext4).

**Comment by ruflin** [comment]
Closing this issue as generic filtering is now available for all beats.
