### ISSUE TITLE
Adding Functionbeat and Journalbeat to Beats overview docs

### ISSUE THREAD

**Issue by acchen97** [elastic/beats#9140]
We should consider adding Functionbeat and Journalbeat to the [Beats overview in the libbeat docs](https://www.elastic.co/guide/en/beats/libbeat/current/beats-reference.html).

Functionbeat: Cloud data
Journalbeat: systemd journals

/cc @dedemorton

**Comment by dedemorton** [comment]
Agreed! It’s already on my checklist of loose ends to resolve next week.
