### ISSUE TITLE
host.os.codename and host.containerized are missing from documentation and index template

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#9154]
6.5.0

Heartbeat generates `host.os.codename` and `host.containerized` in its output fields:

```
          "host" : {
            "os" : {
              "platform" : "centos",
              "version" : "6.7 (Final)",
              "family" : "redhat",
              "codename" : "Final"
            },
            "containerized" : true,
            "name" : "ff7065209158",
            "architecture" : "x86_64"
          }
```

But these fields are [not documented](https://www.elastic.co/guide/en/beats/heartbeat/current/exported-fields-host-p) today, and also not defined in the index template created by heartbeat.

**Comment by ppf2** [comment]
Possibly related to ECS missing these fields to begin with: https://github.com/elastic/ecs/issues/75

**Comment by ruflin** [comment]
This is actually not only an issue related to Heartbeat but all Beats. The fields should be documented in the `add_host_metadata` processor: https://github.com/elastic/beats/blob/master/libbeat/processors/add_host_metadata/_meta/fields.yml

@ppf2 How did you discover the fields are not in the template? Did it cause any issues?

**Comment by ppf2** [comment]
@ruflin I ran heartbeat from within a Docker container and configured it to output to Elasticsearch so that it will generate the index template for it.  Then I checked the template and mappings to confirm that those fields are not defined.  I don't believe having ES generate dynamic mappings for them will cause an issue since it did create containerized as a boolean.  For codename, the heartbeat template will simply treat it as an unknown string and will automatically map it as a keyword which should be fine as well.  Certainly, having these fields documented and explicitly defined in the mapping will be nice.  If anything from a consistency point of view.  Thanks!

**Comment by ruflin** [comment]
We should definitively fix it on our end. I was just curious how you discovered it as I would normally assume based on a bug / issue, good to hear that is not the case.

**Comment by andrewvc** [comment]
I've opened a PR here: https://github.com/elastic/ecs/pull/294

**Comment by andrewvc** [comment]
Closing this as we have switched away from the host namespace the the observer namespace with the new `add_observer_metadata` processor. These fields are part of ECS so won't appear in those docs.
