### ISSUE TITLE
Heartbeat incorrectly populates type field with name value

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#9157]
5.6.13

When https://www.elastic.co/guide/en/beats/heartbeat/5.6/configuration-heartbeat-options.html#monitor-name is set, it is supposed to populate https://www.elastic.co/guide/en/beats/heartbeat/5.6/configuration-heartbeat-options.html#monitor-name with the custom name of the heartbeat job.   However, it is incorrectly populating https://www.elastic.co/guide/en/beats/heartbeat/5.6/exported-fields-common.html#_type.

For example:

```
heartbeat.monitors:
- type: http
  name: my_monitor 
```

Result in:

```
  "monitor": "my_monitor@http://localhost:9200",
  "port": 9200,
  "resolve_rtt": {
    "us": 303
  },
  "scheme": "http",
  "tcp_connect_rtt": {
    "us": 256
  },
  "type": "my_monitor",   <----- INCORRECT, should be http
```

**Comment by ppf2** [comment]
This appears to be fixed in a later version for 6.5.0 is correctly returning:

```
 "monitor" : {
            "duration" : {
              "us" : 2530
            },
            "status" : "up",
            "scheme" : "http",
            "id" : "my_monitor@http://localhost:9200",
            "name" : "my_monitor",
            "type" : "http",
            "host" : "localhost",
            "ip" : "127.0.0.1"
          }
```

One workaround will be to use the `fields` setting instead of `name` to set the custom name, and post-process downstream to replace name with the value from fields.

**Comment by andrewvc** [comment]
@JakeFromTheDark Can you not switch to 6.x? Heartbeat was a beta product until 6.5. We generally do not backport things to previous beta releases unless there is a severe security concern.

**Comment by JakeFromTheDark** [comment]
Sure I can. I just found something strange and it's up to you if/where you wanna to fix it.

**Comment by andrewvc** [comment]
@JakeFromTheDark Thanks for the report! It is appreciated. Given the age and unsupported nature of that version we're going to close this issue out.
