### ISSUE TITLE
Filebeat IIS module ignores ignore_older: setting

### ISSUE THREAD

**Issue by blarsonrp** [elastic/beats#9182]
**Describe the enhancement:**
When testing Filebeat 6.5.0 on windows with the IIS module it appears to ignore the ignore_older: setting completely when adding it in the iis.yml or filebeat.yml file. Filebeat captures all available IIS logs regardless of this setting.

**Describe a specific use case for the enhancement or feature:**
This would allow you to retain local copies of historical logs locally but only send new logs to Elasticsearch.

**Comment by ph** [comment]
@blarsonrp You should be able to override any input settings in filebeat from a module definition.

Did you try a config similar to this?

```yaml
- module: iis
  access:
    enabled: true
    input:
      ignore_older: 12h

**Comment by blarsonrp** [comment]
You are correct, I will close this issue. my issue was not having ignore_older under the input: field.
