### ISSUE TITLE
Possibility to disable per cpu core stats in metricbeat docker module

### ISSUE THREAD

**Issue by henrikno** [elastic/beats#9187]
**Describe the enhancement:**
The docker cpu metrics are extremely detailed when having many cores:
![image](https://user-images.githubusercontent.com/147660/48810269-40916c80-ecdd-11e8-9e15-b7f161262c97.png)
This takes up a lot of storage that we don't need, so we have to filter it out. It would be nice if it was possible to disable it in metricbeat directly.

**Suggestion**
Config option for enabling/disabling per cpu-core cpu usage.

The same goes for system per process with cgroup stats, which is stored per core. I can open a separate issue for that if necessary.
https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-metricset-system-process.html

**Comment by jsoriano** [comment]
Fixed by #9194

**Comment by jsoriano** [comment]
I have created #9326 for the cgroup metrics.
