### ISSUE TITLE
[Filebeat] Module for Palo Alto Logs

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#9199]
As a user I want to be able to ingest logs from Palo Alto PAN-OS. Of the available [log types](https://www.paloaltonetworks.com/documentation/71/pan-os/pan-os/monitoring/log-types-and-severity-levels) I'm thinking to start with:

- Traffic Logs
- Threat Logs

We'll need to map the fields in these logs to ECS.

**Comment by MikePaquette** [comment]
Here are some WIP logical mappings (no config files) of PAN log fields to ECS fields 

Traffic Logs - [Google Sheet](https://docs.google.com/spreadsheets/d/1ZgUrh16w7yzv3FRLXpnKNuFL2KOgHSCtCA6Gipm-_Jk/edit#gid=244680676)
Threat Logs - [Google Sheet](https://docs.google.com/spreadsheets/d/1ZgUrh16w7yzv3FRLXpnKNuFL2KOgHSCtCA6Gipm-_Jk/edit#gid=951465957)

Also, there are some sample log snippets in this [Google Team Drive folder](https://drive.google.com/drive/folders/1ox-kPT7447fKE2YwWr1XmuESo2vdSv40).  However, most of these are in CEF or LEEF format.  I have requested samples of pan_traffic and pan_threat in syslog format and PAN has agreed to find or create some additional samples for us after Thanksgiving.

These samples appear to use only RFC 1918 addresses and public addresses from entities like Google and Akamai, so we can use these as samples.

**Comment by Rukas** [comment]
Hello, 

We're interested in this as well.  Has there been any movement on this?

**Comment by MikePaquette** [comment]
Sorry for the trouble with those Google Docs.
Please see https://github.com/elastic/ecs/issues/352 for these examples.

@Rukas @andrewkroh

**Comment by willemdh** [comment]
Just wondering why a Filebeat module is preferred over a Logstash module?

**Comment by davidhowell-tx** [comment]
In reviewing the code for the panw filebeat module I noticed that certain fields are duplicated, such as client.ip, source.ip, client.address.  Is there a reason why duplicating the data is preferred instead of using an alias?

**Comment by learnitall** [comment]
I'm not sure if this answers your question @davidhowell-tx, but I don't believe those fields are meant to be exact duplicates in the purest sense. From the [ECS client field schema](https://github.com/elastic/ecs/blob/ccba36bb06f0eff7092305ab79f9c059df83bf30/schemas/source.yml):

> Some event sources are defined ambiguously. The even will sometimes list an IP, a domain or a unix socket. You should always store the raw address in the `.address` field. Then it should be duplicated to `.ip` or `.domain`, depending on which on it is.

It's my understanding that if you added aliases for client.ip and client.domain that pointed to client.address, all data placed into the client.address field could then technically be interpreted as both an ip and a domain. By only duplicating the data to the appropriate field when needed, the interpretation of the data becomes clearer, as I don't think you can set aliases per-event.

I think this same line of reasoning applies when talking about the difference between client/source and server/destination.

**Comment by learnitall** [comment]
Also I'd like to add that I think it might be a good idea to explore the ability to specify the Panos version in the Beats config, and then add support for a wide range of Panos versions. This way regardless of the version of Panos a user is has they can still use the module. Plus we'd have a defined way to update the module when a new version of Panos comes out that uses a different schema.

**Comment by strawgate** [comment]
We would very much like to see support added for the remainder of palo alto logs

**Comment by andrewkroh** [comment]
Closed by #11999.

Module docs: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-panw.html

**Comment by andrewkroh** [comment]
@strawgate For the other logs types that you are have interest in being parsed by the module please open a new issue.
