### ISSUE TITLE
Need to Reload full filebeat.yml [Enhancement]

### ISSUE THREAD

**Issue by jain108shubhamtbt** [elastic/beats#9220]
**Describe the enhancement:**
We need to reload full filebeat.yml, same as logstash provide us to reload all input, filter, output config settings.

**Describe a specific use case for the enhancement or feature:**
For Example : 

1) Change any settings in #-------------------------- Elasticsearch output ------------------------------

host and port, etc

2) Change any settings in #============= Filebeat inputs ====

type, multiline, etc

3) Change any settings in #============= General ====

max_procs, etc

4) Change any settings in #============= Logging ====

loglevel, name, etc

**Comment by jain108shubhamtbt** [comment]
in linux, can we implement it using through signals concept's.


From your side when will be got (in which release provide) us

**Comment by niyanchun** [comment]
need +1
