### ISSUE TITLE
Restrict event type

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#923]
Duplicates https://github.com/elastic/libbeat/issues/125. 

Currently the event type is defined as `MapStr` (map[string]interface{}) which is too generic (interface{} accepts anything) and requires reflection every time you access it. The reflection is costly and it can  affect the performance. A problem might appear when applying the filters on events in [generic_filtering](https://github.com/elastic/beats/pull/830) as filtering is done in libbeat after the event is created.

The generic_filtering expects to receive an event that contains only `primitive values` (int, string, bool, etc) and `MapStr`, not structures or pointers. Unfortunately the beats are not respecting this and [here](https://github.com/elastic/beats/issues/925) is a list with all the limitations.

We cannot rely on the user that the event is structured properly before calling the publisher so I can think of two options/phases:
### Phase 1

This is an intermediary phase and I see two options here:
1. Add a event checker in `PublishEvent` function before calling generic_filtering to make sure it has the right structure and throw an exception when there is an unexpected type in the event.
2. Convert the event that is passed to the publisher to an event that contains only MapStr and primitives (int, string, bool, etc).

The first option is already partially implemented in #830 by using the [reflectwalk](https://github.com/mitchellh/reflectwalk) library. The second option is more complex and it can be done by following the implementation of [copystructure](https://github.com/mitchellh/copystructure/blob/master/copystructure.go) but instead of just copying the fields, it transforms the struct fields to MapStr.
### Phase 2

In the phase 2, we should remove the usage of reflection by creating a special Event where the user doesn't have to create the event by himself from scratch and it can use different methods of the Event.
This would require changes in all beats.

**Comment by ruflin** [comment]
One addition here: I would like to see that the Event Type also supports meta data which is shared across all events. Currently this is @timestamp, type, index and I would include everything inside beat/shipper namespace. The goal should be, that this meta data is not part of the event itself and is added to the event by the output. The output can decide about the structure. The Event object would then have a function for example `event.setTimestamp(...)` or `event.setType(...)`.

**Comment by ycombinator** [comment]
We now have an Event type that's a `struct` (instead of a `map[string]interface{}`):

https://github.com/elastic/beats/blob/9b2440959d81efa2e55dab588aa86c65465af0d0/libbeat/beat/event.go#L31-L41

So I believe this issue can be closed. Please reopen if I misunderstood what was being asked.

**Comment by ph** [comment]
This look like a really old issue,  I believe we can close this until we have a better plan for it.
