### ISSUE TITLE
[Functionbeat] Add support for Azure functions

### ISSUE THREAD

**Issue by ph** [elastic/beats#9232]
From discuss: https://discuss.elastic.co/t/azure-functions-support/157766/3

---

We are currently only supporting AWS lambda, it would be nice to also add support for Azure functions.

TODO: 

- Add Event trigger to support.

**Comment by afuggetta** [comment]
Is this feature under development? We could really use this.
Thanks.

**Comment by felix-lessoer** [comment]
@ph Any updates on this ticket?

**Comment by felix-lessoer** [comment]
@elastic/beats Who can help with the status of this request?

**Comment by 0xtf** [comment]
Any update on this?

**Comment by cskowronnek** [comment]
Any updates?
