### ISSUE TITLE
Generic filtering limitation due to event being MapStr

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#925]
### Topbeat

PR #802 updates the event object to contain only MapStr, so filtering should work on any field.
### Packetbeat
- You cannot apply filtering on any of the header from request_headers or response_headers as they are defined as map[string]common.NetString instead of MapStr. This is an optimization needed in order to be able to call easily `len` on any header values.

**Comment by ph** [comment]
We can close this issue, everything is now  a MapStr and effort has moved to heartbeat.
