### ISSUE TITLE
When did windows beats packages got zipped using another method?

### ISSUE THREAD

**Issue by vchan2002** [elastic/beats#9259]
While this is not necessarily a bug in beats itself, it's causing downstream effects for users who are using the chef to install beats zip packages for windows

https://github.com/chef-cookbooks/windows/issues/459

The TL:DR of that issue is that, it seems that chef cannot handle zip files created using Compress-Archive However, it seems to work OK if the zip is created with [System.IO.Compression.ZipFile]::CreateFromDirectory.  

It would seem that the change happened somewhere in between version 6.3.2 to 6.4.2, as I am able to use the same chef recipe to install beats on 6.3.2, but not with 6.4.2.

On 6.4.2, chef's methods would not extract everything in the archive, including subdirectories and the powershell install/uninstall scripts, and fails subsequently.  

So, I'd like to know when that change took affect, so that we can pin our installs to the latest version with the working compression method, until that bug is fixed.

**Comment by andrewkroh** [comment]
6.4.0 was the first release made with the updated packaging code. The zip is built with a bit of Go code from [here](
https://github.com/elastic/beats/blob/1c1b7d7427a422ec9da0707b1830e9cb03837266/dev-tools/mage/pkgtypes.go#L496). IIUC the problem is caused by intermediary directories not being listed in the zip.

**Comment by vchan2002** [comment]
When I debugged this, I managed to find the chef cache directory where the zip file is extracted.  Not only are the subdirectories of the zip file are missing, but the install and uninstall powershell scripts are missing as well.  In fact, the cookbook I used failed because it could not find the powershell file.  Very strange indeed.
