### ISSUE TITLE
[Metricbeat] Exported fields list has two entries named "Docker fields"

### ISSUE THREAD

**Issue by jstrassb** [elastic/beats#9272]
The documentation for the exported fields mentions two distinct `Docker fields`, from the [processor](https://github.com/elastic/beats/blob/master/metricbeat/docs/fields.asciidoc#docker-fields) and the [docker module](https://github.com/elastic/beats/blob/master/metricbeat/docs/fields.asciidoc#docker-fields-1) respectively.

These should ideally be better distinguishable from the exported fields list https://www.elastic.co/guide/en/beats/metricbeat/6.5/exported-fields.html.
The second one also mentions `docker fields` twice in a second headline.

Thanks!

**Comment by andrewvc** [comment]
@ruflin  I switched the label here to  metricbeat. I don't think thas was meant to be tagged as a heartbeat issue.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
