### ISSUE TITLE
Elasticsearch deprecation logs are not creating the `event.dataset` field

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#9278]
When testing the `elasticsearch/deprecation` fileset, @chrisronline noticed that there was no easy way for him to filter docs in `filebeat-*` to just deprecation logs docs.

Upon some digging it looks like these docs are missing the `event.dataset` field, whose value should be set to `deprecation`. Additionally, we should make sure the `event.module` field is being set to `elasticsearch`. These two fields can then be combined to filter out just ES deprecation logs from all `filebeat-*` docs.

**Comment by ycombinator** [comment]
Here's a sample deprecation log doc that @chrisronline saw in his `filebeat-*` index:

```json
{
    "@timestamp": "2018-11-28T21:37:15.994Z",
    "input": {
        "type": "log"
    },
    "beat": {
        "name": "Elastic-MBP.local",
        "hostname": "Elastic-MBP.local",
        "version": "7.0.0-alpha1"
    },
    "host": {
        "name": "Elastic-MBP.local"
    },
    "message": "[2018-11-28T16:37:14,796][WARN ][o.e.d.r.a.s.RestSearchAction] [one] The {index}/{type}/_search endpoint is deprecated, use {index}/_search instead",
    "source": "/Users/chris/Development/es-master/logs/main_deprecation.log",
    "offset": 14593964,
    "prospector": {
        "type": "log"
    }
}
```

**Comment by ycombinator** [comment]
One odd thing I notice about the sample doc in the previous comment is that there are no parsed fields at all, e.g. `elasticsearch.server.component`, `log.level`, or `log.offset`. 

Also, when I ran the integration tests for the `elasticsearch` module and [generated](#9279) the expected JSON files for the `deprecation` fileset, I do see these fields as well as `event.module` and `event.dataset`.

**Comment by ycombinator** [comment]
@chrisronline I just tried to reproduce this issue and everything worked as expected for me. Here are the steps I took:

1. Run Elasticsearch from the `master` branch. I didn't do any special configuration as deprecation logging is enabled at the `WARN` level by default.

   ```
   cd elasticsearch-7.0.0-SNAPSHOT
   ./bin/elasticsearch
   ```

2. Verify that deprecations logs are indeed being generated by ES:

   ```
   ls -al logs/*deprecation*
   ```

3. Enable the `elasticsearch` module in Filebeat:

   ```
   cd filebeat
   ./filebeat modules enable filebeat
   ```

4. Edit `modules.d/elasticsearch.yml` to configure the `deprecation` fileset in the `elasticsearch` module to look in the right place for my ES deprecation logs:

   ```
    deprecation:
      enabled: true
      var.paths:
        - /Users/shaunak/elasticsearch-7.0.0-alpha1-SNAPSHOT/logs/*deprecation*
   ```

5. Start up Filebeat:

   ```
   ./filebeat -e
   ```

6. Check the filebeat logs to see that deprecation logs are being harvested. You should see lines like these:

   ```
   2018-11-28T15:13:25.216-0800    INFO    log/input.go:138        Configured paths: [/Users/shaunak/elasticsearch-7.0.0-alpha1-SNAPSHOT/logs/*deprecation*]
   ...
   2018-11-28T15:13:25.232-0800    INFO    log/harvester.go:254    Harvester started for file: /Users/shaunak/elasticsearch-7.0.0-alpha1-SNAPSHOT/logs/elasticsearch_deprecation.log
   ```

7. Check ES to see if deprecation logs show up in `filebeat-*`:

   ```
   POST filebeat-*/_search
   {
     "query": {
       "bool": {
         "filter": {
           "bool": {
             "must": [
               {
                 "term": {
                   "event.module": "elasticsearch"
                 }
               },
               {
                 "term": {
                   "event.dataset": "deprecation"
                 }
               }
             ]
           }
         }
       }
     }
   }
   ```

**Comment by chrisronline** [comment]
@ycombinator You're right. This works now for me. Thanks!
