### ISSUE TITLE
Add iis.access.user_agent.original to be searchable / displayable?

### ISSUE THREAD

**Issue by blarsonrp** [elastic/beats#9291]
**Describe the enhancement:**

Hello,
Is it possible to make the index filed for Apache or IIS or Nginx for the .access.user_agent.original string show up as searchable and aggregatable?

**Describe a specific use case for the enhancement or feature:**

The issue i'm experiencing is that with a spoofed or incorrect user agent that doesn't register with the plugin simply gets shown as "other".

When troubleshooting issues, such as performance or security issues, it's helpful to aggregate and visualize the types of requests not only from the normal user agent family but others as well. Viewing only "normal" traffic limits visibility into issues.

**Comment by ruflin** [comment]
We actually plan to change this with ECS to make it a `keyword` instead of `text`. See the example here https://github.com/elastic/ecs/blob/master/use-cases/filebeat-apache-access.md
