### ISSUE TITLE
Panic runtime error after 'Read line error: EOF'

### ISSUE THREAD

**Issue by bargenson** [elastic/beats#930]
Hi everyone,

I would like to pipe an HTTP stream with curl to filebeats but I get the following error each time the stream close:

> 2016/02/05 01:42:32.412929 reader.go:87: INFO Reached end of file: /dev/stdin
> 2016/02/05 01:42:32.412971 log.go:157: INFO Read line error: EOF
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xb code=0x1 addr=0x10 pc=0x54d0e4]
> 
> goroutine 18 [running]:
> github.com/elastic/beats/filebeat/harvester.(*Harvester).Harvest.func1(0xc82008e5a0)
> 	/go/src/github.com/elastic/beats/filebeat/harvester/log.go:91 +0x34
> github.com/elastic/beats/filebeat/harvester.(*Harvester).Harvest(0xc82008e5a0)
> 	/go/src/github.com/elastic/beats/filebeat/harvester/log.go:158 +0xa6e
> created by github.com/elastic/beats/filebeat/harvester.(*Harvester).Start
> 	/go/src/github.com/elastic/beats/filebeat/harvester/harvester.go:80 +0x35
> 
> goroutine 1 [select]:
> github.com/elastic/beats/filebeat/crawler.(*Registrar).Run(0xc82004b500)
> 	/go/src/github.com/elastic/beats/filebeat/crawler/registrar.go:91 +0x4df
> github.com/elastic/beats/filebeat/beat.(*Filebeat).Run(0xc82000ede0, 0xc820015180, 0x0, 0x0)
> 	/go/src/github.com/elastic/beats/filebeat/beat/filebeat.go:100 +0x624
> github.com/elastic/beats/libbeat/beat.(*Beat).Run(0xc820015180)
> 	/go/src/github.com/elastic/beats/libbeat/beat/beat.go:176 +0x31c
> github.com/elastic/beats/libbeat/beat.Run(0x948480, 0x8, 0x933540, 0x5, 0x7f462b7b10c8, 0xc82000ede0, 0xc8200f41d0)
> 	/go/src/github.com/elastic/beats/libbeat/beat/beat.go:86 +0x25b
> main.main()
> 	/go/src/github.com/elastic/beats/filebeat/main.go:21 +0x9d
> 
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
> 	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
> 
> goroutine 5 [syscall]:
> os/signal.loop()
> 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
> created by os/signal.init.1
> 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
> 
> goroutine 10 [select]:
> github.com/elastic/beats/libbeat/publisher.(*messageWorker).run(0xc820001e00)
> 	/go/src/github.com/elastic/beats/libbeat/publisher/worker.go:61 +0x449
> created by github.com/elastic/beats/libbeat/publisher.(*messageWorker).init
> 	/go/src/github.com/elastic/beats/libbeat/publisher/worker.go:55 +0x11e
> 
> goroutine 11 [select]:
> github.com/elastic/beats/libbeat/publisher.(*bulkWorker).run(0xc82004ddc0)
> 	/go/src/github.com/elastic/beats/libbeat/publisher/bulk.go:57 +0x3ca
> created by github.com/elastic/beats/libbeat/publisher.newBulkWorker
> 	/go/src/github.com/elastic/beats/libbeat/publisher/bulk.go:41 +0x20a
> 
> goroutine 12 [select, locked to thread]:
> runtime.gopark(0xa15258, 0xc820024728, 0x93b4a0, 0x6, 0x42db18, 0x2)
> 	/usr/local/go/src/runtime/proc.go:185 +0x163
> runtime.selectgoImpl(0xc820024728, 0x0, 0x18)
> 	/usr/local/go/src/runtime/select.go:392 +0xa64
> runtime.selectgo(0xc820024728)
> 	/usr/local/go/src/runtime/select.go:212 +0x12
> runtime.ensureSigM.func1()
> 	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
> runtime.goexit()
> 	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
> 
> goroutine 13 [chan receive]:
> github.com/elastic/beats/libbeat/service.HandleSignals.func1(0xc820019ce0, 0xc8202b8020, 0xc8202b0100)
> 	/go/src/github.com/elastic/beats/libbeat/service/service.go:29 +0x3a
> created by github.com/elastic/beats/libbeat/service.HandleSignals
> 	/go/src/github.com/elastic/beats/libbeat/service/service.go:32 +0x1f8
> 
> goroutine 15 [select]:
> github.com/elastic/beats/filebeat/beat.(*Spooler).Run(0xc8200158b0)
> 	/go/src/github.com/elastic/beats/filebeat/beat/spooler.go:85 +0x7c2
> created by github.com/elastic/beats/filebeat/beat.(*Filebeat).Run
> 	/go/src/github.com/elastic/beats/filebeat/beat/filebeat.go:90 +0x421
> 
> goroutine 16 [sleep]:
> time.Sleep(0x3b9aca00)
> 	/usr/local/go/src/runtime/time.go:59 +0xf9
> github.com/elastic/beats/filebeat/crawler.(*Prospector).stdinRun(0xc820059a00, 0xc8202ca000)
> 	/go/src/github.com/elastic/beats/filebeat/crawler/prospector.go:224 +0x274
> github.com/elastic/beats/filebeat/crawler.(*Prospector).Run(0xc820059a00, 0xc8202ca000)
> 	/go/src/github.com/elastic/beats/filebeat/crawler/prospector.go:140 +0x1c1
> created by github.com/elastic/beats/filebeat/crawler.(*Crawler).Start
> 	/go/src/github.com/elastic/beats/filebeat/crawler/crawler.go:52 +0x47c
> 
> goroutine 19 [select]:
> github.com/elastic/beats/filebeat/beat.(*syncLogPublisher).Start.func1(0xc82004b780)
> 	/go/src/github.com/elastic/beats/filebeat/beat/publish.go:92 +0x693
> created by github.com/elastic/beats/filebeat/beat.(*syncLogPublisher).Start
> 	/go/src/github.com/elastic/beats/filebeat/beat/publish.go:113 +0x58

After that, the script running this command just die (without even executing my bash trap).

The command I use looks like this: 
`curl -s --no-buffer -XGET --unix-socket /tmp/some.sock http:/somePath | /filebeat/filebeat -e -v`

Is it a bug or am I doing something wrong?

Thanks.

**Comment by andrewkroh** [comment]
What version and what OS?

**Comment by bargenson** [comment]
Ubuntu Wily (15.10) and Filebeat 1.1.0 x86_64.

Thanks :-)

**Comment by andrewkroh** [comment]
Would you be able to test with the 1.2.0 nightly build? I had a similar failure recently when stdin was closed and made a change.

The nightly builds are here: https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/

**Comment by bargenson** [comment]
Fix the issue, thanks :-)
