### ISSUE TITLE
adding the possibility to load dashboards in multiple Kibana Spaces

### ISSUE THREAD

**Issue by zozo6015** [elastic/beats#9306]
**Describe the enhancement:**
I would like to have the possibility to configure multiple spaces in the beats config files at `spacesid:` in order to be able to load the dashboards into all the required spaces.  Altermatively we should be able to specify all the spaces in command line options when running `*beat setup --space "list,of,spaces"` or `*beat setup --space space1 --space space2  ...`

**Describe a specific use case for the enhancement or feature:**

When setting up different spaces for different access level currently we need to modify the config file for each space separately then run the setup command.

**Comment by ruflin** [comment]
Hi @zozo6015 Thanks for the request. I understand the issue that you want to have the dashboards in all spaces. But not sure if Beats is the right tool for that. Historically Beats is loading the dashboards but we are in the progress of moving more and more of these things into Kibana as it's probably the right place for it.

As I think it's unlikely that this will happen directly in Beats @zozo6015 perhaps you can phrase your issue in a more general way that you need "a tool" to load the dashboards to all spaces?

**Comment by Jeeppler** [comment]
There is already a similar forum post: https://discuss.elastic.co/t/avoid-to-create-new-visualizations/156866/4

Is X-Pack required for Kibana spaces?

**Comment by zozo6015** [comment]
Basic x-pack comes shipped with elasticsearch by default. Nothing else is required for using spaces.
