### ISSUE TITLE
Filebeat: HAProxy Sample Dashboard Not Created

### ISSUE THREAD

**Issue by doublewhammy** [elastic/beats#9307]
Issue:
When running the filebeat setup to create sample dashboards in Kibana, HAProxy sample dashboard is not created.

Details:
-Version: Filebeat 6.5.1
-Operating System: CentOS Linux release 7.5.1804 (Core)
-Steps to reproduce: filebeat -e setup
-Output: Sample dashboards are created with the exception of HAProxy - no error messages are displayed.
Additional Output from command:
2018-11-27T16:34:15.283Z INFO beater/filebeat.go:101 Enabled modules/filesets: haproxy (log), ()
Loading dashboards (Kibana must be running and reachable)
2018-11-27T16:34:15.284Z INFO elasticsearch/client.go:163 Elasticsearch url: http://x.x.x.x:9200
2018-11-27T16:34:15.287Z INFO elasticsearch/client.go:712 Connected to Elasticsearch version 6.5.0
2018-11-27T16:34:15.288Z INFO kibana/client.go:118 Kibana url: http://x.x.x.x:5601
2018-11-27T16:34:45.596Z INFO instance/beat.go:717 Kibana dashboards successfully loaded.
Loaded dashboards

**Comment by jsoriano** [comment]
Hi @doublewhammy,

It actually looks to be placed in the wrong place, I have started #9313 to fix this.

Thanks for reporting!

**Comment by SoboLAN** [comment]
@jsoriano I think I ran into this same issue while using ES/Kibana 6.5.3. Is there any way I can manually fix this on my end without upgrading? (upgrading seems kind of complicated imo)
Thanks

**Comment by sayden** [comment]
@SoboLAN you just need to move the dashboard JSON file to the same location that appears in the PR where @jsoriano fixed it before running setup. Check the PR, it's really easy :wink:

**Comment by SoboLAN** [comment]
@sayden Thanks, I'll give it a try. Restarting is probably needed for that, right?

**Comment by sayden** [comment]
> @sayden Thanks, I'll give it a try. Restarting is probably needed for that, right?

Move the file and re-run the setup as described in the first message on this issue. This should load the dashboards on Elasticsearch so they are available on Kibana
