### ISSUE TITLE
Docs: Please state minimum Go version

### ISSUE THREAD

**Issue by magnusbaeck** [elastic/beats#9321]
The documentation at https://www.elastic.co/guide/en/beats/devguide/current/newbeat-getting-ready.html (and possibly other developer documentation) only tells the user to install Go but doesn't mention the minimum version required.

I think that paragraph should include such information since Beats has specific Go compiler requirements (at least 1.9 must be used because of type aliases) and the error messages when your Go compiler is too old can be pretty confusing.

Another option could be to introduce a version check in one of the makefiles so that the build fails if a too-old compiler is used.

**Comment by ph** [comment]
We should use the version defined in `.go-version` when we generate the doc so we don't have to keep track of updating that file.

**Comment by dedemorton** [comment]
Sorry, this issue got lost in the queue. We did update the docs quite a while ago to include the go version. Closed in https://github.com/elastic/beats/pull/14400
