### ISSUE TITLE
100% CPU used if Logstash isn't available.

### ISSUE THREAD

**Issue by chad-upton** [elastic/beats#935]
Amazon Linux x64 (latest)
Amazon EC2

Latest filebeat, logstash, elasticsearch.

If I stop my logstash aggregators where filebeat is sending to, filebeat immediately shoots to over 100% cpu usage until they come back online.

**Comment by ruflin** [comment]
I assume by latest filebeat you refer to 1.1.0 and not the nightly latest? It would be good to specify the exact versions as latest changes over time.

Can you filebeat and LS config?

**Comment by chad-upton** [comment]
Yea sorry I should have been more concise.

```
filebeat version 1.0.1 (amd64)
```

I think I've found the issue why but haven't had time to really test it.  I'm pretty sure it happens when setting loadbalance = true.  Once those are both set only add one host to your connection string.

Example:
```
output:
  logstash:
    hosts: ["logs.example.com:5044"]
    worker: 2
    loadbalance: true
```

My guess it has to do with only having one host in the string but loadbalance is expecting 2 or more.  So when that host is unavailable it ends up in a loop?

**Comment by ruflin** [comment]
Could you update to the 1.1 release? There were quite a few improvements in this area.
