### ISSUE TITLE
Metricbeat Docker Container metrics uses different field name format

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#9350]
In docker container module, we are using DeDot method before storing the event. But in libbeat add_docker_metadata processor it doesn't seem to use DeDot. This is causing inconsistency metric name/format for the same docker container metrics. Please see https://discuss.elastic.co/t/metricbeat-docker-container-uses-different-field-name-format/158422 for more details.

**Comment by jsoriano** [comment]
Related to #6066
