### ISSUE TITLE
Metricbeat export dashboard needs to use --decode flag by default

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#9387]
**Describe the enhancement:**
./metricbeat export dashboard command needs to use --decode flag as default. 

**Describe a specific use case for the enhancement or feature:**
When I ran ```./metricbeat export dashboard -id a6d6d930-f7f0-11e8-af03-c999c9dea608 >> Metricbeat-aws.json```, it generated Metricbeat-aws.json with invalid json format fields like 
``` 
"kibanaSavedObjectMeta": {
        "searchSourceJSON": "\"\\\"{\\\\\\\"index\\\\\\\":\\\\\\\"metricbeat-*\\\\\\\",\\\\\\\"query\\\\\\\":{\\\\\\\"language\\\\\\\":\\\\\\\"kuery\\\\\\\",\\\\\\\"query\\\\\\\":\\\\\\\"\\\\\\\"},\\\\\\\"filter\\\\\\\":[]}\\\"\""
}
```
After loading this dashboard into Kibana, it can not be opened and it showed error ```Invalid searchSourceJSON in dashboard ```.

Turned out, if I run ```./metricbeat export dashboard -id a6d6d930-f7f0-11e8-af03-c999c9dea608 --decode >> Metricbeat-aws.json```, the output gives the right format.

**Comment by ruflin** [comment]
The default should be without `--decode` as it's only used for developers that create modules for Beats. If users use it they don't need the decoded version. The version that is packaged with each beat is the encoded one which is equal to what you get when you run export without decode. I suggest to close this issue. Please reopen if you think it should be still changed.
