### ISSUE TITLE
HAProxy saved objects won't import

### ISSUE THREAD

**Issue by bigphilwa** [elastic/beats#9389]
After moving the Filebeat-haproxy-overview.json file to the correct location and running filebeat setup --dashboards, there is an error when the program trys to load the HAProxy json file. It seems that the nested json objects in the file are expected to be text fields and NOT json. All other modules work just fine and their json files all contain escaped json text strings instead of plain json. The following error is logged when running setup:

> 2018-12-04T08:25:35.822-0800	ERROR	instance/beat.go:800	Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing directory C:\ELASTIC\filebeat-6.5.1-windows-x86_64\kibana: Failed to import dashboard: Failed to load directory C:\ELASTIC\filebeat-6.5.1-windows-x86_64\kibana/6/dashboard:
error loading C:\ELASTIC\filebeat-6.5.1-windows-x86_64\kibana\6\dashboard\Filebeat-haproxy-overview.json: failed to parse field [visualization.kibanaSavedObjectMeta.searchSourceJSON] of type [text]. Response: {"objects":[{"id":"55251360-aa32-11e8-9c06-877f0445e3e0","type":"visualization","error":{"message":"failed to parse field [visualization.kibanaSavedObjectMeta.searchSourceJSON] of type [text]"}},{"id":"7fb671f0-aa32-11e8-9c06-877f0445e3e0","type":"vi... (truncated)

I've confirmed the saved objects (visualizations and dashboard) load without issue when I converted the objects to text strings. So not only that, but after the objects were loaded, I found two other issues noted below:
1) in the visualization "IP Geohashes [Filebeat HAProxy]" it is referencing "haproxy.client_ip" where it should be "haproxy.client.ip" as that is what is in the mapping and index template.
2) the panelsJSON is null in the dashboard object. This should included the visualizations that were created.

Please include configurations and logs if available.
s
For confirmed bugs, please report:
- Version: Filebeat 6.5.1
- Operating System: Windows Server 2016
- Discuss Forum URL: https://discuss.elastic.co/t/haproxy-dashboard-error-loading/159398
- Steps to Reproduce: Attempt to load dashboards for Windows Filebeat.

**Comment by ruflin** [comment]
What is the exact file you moved? You can't take the file from the Github repo and move it into the package as the encoding is done during packaging. Closing as this should be fixed by https://github.com/elastic/beats/pull/9313

**Comment by jsoriano** [comment]
@ruflin actually there is something wrong with this dashboard, let me take a look.

**Comment by jsoriano** [comment]
@bigphilwa thanks for reporting this, there were actually some issues with this dashboard, I have opened #9417 to fix them.

**Comment by ruflin** [comment]
@jsoriano Thanks for double checking.
@bigphilwa Sorry for closing this one too quickly.
