### ISSUE TITLE
module names for the same service different between beats (apache and apache2)

### ISSUE THREAD

**Issue by skh** [elastic/beats#9395]
While working on the services part of the Infrastructure UI I noticed that filebeat has an `apache2` module, whereas metricbeat has `apache`. Should the module names be unified at some point?

(See also https://github.com/elastic/kibana/issues/26617 )

**Comment by roncohen** [comment]
This would be nice to get fixed. Would need to happen in a major release.

**Comment by exekias** [comment]
I agree, let's try to do it for 7.0

**Comment by exekias** [comment]
I'm more in favor of just unifying to `apache`, as doing `filebeat modules enable apache_logs` may be annoying for users (Filebeat is for logs, so that part is redundant).

We can probably revisit this decision when/if a single agent happens?

**Comment by jsoriano** [comment]
+1 to unify names by now and revisit the decision on single agent.

If we unify agents we may also want to unify modules as seen by the user, so `singlebeat modules enable apache` enables collection of logs and metrics.

**Comment by ph** [comment]
I would unify it into a single name, the metrics/logs is IMHO only a suffix where _apache_ is the concept to watch and align to.

+1 to @roncohen it need to be done in major release.

**Comment by ruflin** [comment]
Seems like we are all on the same then. Let's do it.

@skh Did you stumble over any other that need alignment?

**Comment by jsoriano** [comment]
I think this is the only one with different names, I can do the changes, I'll open a PR.

**Comment by webmat** [comment]
And keep in mind that the name of what everyone calls "Apache" is actually **httpd**. Apache is the name of the foundation.

 🔧=> ⚙️  ;-)
