### ISSUE TITLE
MySQL Metricbeat module do not close db connection

### ISSUE THREAD

**Issue by sayden** [elastic/beats#9415]
The MySQL metricbeat module opens a connection to the database here https://github.com/elastic/beats/blob/master/metricbeat/module/mysql/mysql.go#L103

It seems that the `Close()` call is not being done as needed by the Golang `sql` driver https://golang.org/pkg/database/sql/driver/#Conn

**Comment by andrewkroh** [comment]
Fixed by #10355.
