### ISSUE TITLE
Functionbeat failing to deploy due to Alphanumeric Error

### ISSUE THREAD

**Issue by musayev-io** [elastic/beats#9420]
# Summary
Looking at the CloudFormation resource that Functionbeat creates from the functionbeat.yml, the dashes get converted to "" but the underscores remain underscores, causing the ValidationError.

- **Version:** functionbeat-6.5.2-darwin-x86_64
- **Operating System:** MacOS High Sierra 10.13.6
- [Discuss Forum Post](https://discuss.elastic.co/t/functionbeat-failing-to-deploy-due-to-alphanumeric-error/159650)
- **Steps to Reproduce:** Deploy a CloudWatch function with triggers to log groups that contain underscores in the name

**Comment by musayev-io** [comment]
Hey guys! Just wanted to check up and see if there was any timeline for this bug to get fixed. We're evaluating Lambda monitoring solutions and would hate to disqualify ELK because we couldn't set it up.

Thanks!!

**Comment by PosicubeBeege** [comment]
When can we expect a release with this merge? Just so I know when to come back to adding our AWS logs (all using _ as word delimiters) into our new ELK setup. Thanks!

**Comment by musayev-io** [comment]
According to Elastic, this fix will be part of the 6.6.1 release which is targeted sometime between 2/12/19- 2/22/19.
