### ISSUE TITLE
Document configuration blocks that are supported in Central Management

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#9423]
Right now, we don't do a very good job of describing the configuration blocks that are supported in central management. We need to indicate which options are supported so users don't need to play whack-a-mole to figure out what's allowed.

**Comment by dedemorton** [comment]
We also need to document restrictions more clearly.

**Comment by dedemorton** [comment]
@exekias @mattapperson I want to make sure we don't have any holes here. Can you help me identify the config settings that are (or aren't) supported in CM?

**Comment by mattapperson** [comment]
Pinging @ph and @urso

**Comment by ph** [comment]
The way that CM currently works it to listen to some configuration block, looking at what we have the following keys and eveything under them are handled by CM.


```yaml
filebeat.modules:
metribeat.modules:
filebeat.inputs:
output:
```

Anything outside the above keys are OK to be modified by the user.

**Comment by ph** [comment]
Currently as of today only the **elasticsearch output** should be supported, we might add support for _kafka_ or _redis_, the console and the file output will not be exposed by CM and they will be blacklisted #9099 


All current Metricbeat, Filebeat modules should be exposed in the UI and we don't have currently any limitation on them.

**Comment by mattapperson** [comment]
Kafka is supported, as is logstash

**Comment by dedemorton** [comment]
@ph So to clarify, I think you are saying:

- After users enroll a Beat in central management, all the configs under the following sections need to be defined through the UI in Kibana:
  - filebeat.modules:
  - metribeat.modules:
  - filebeat.inputs:
  - output:

  Question: If they _are_ defined in the yml, what happens? Are they ignored? 

- Any configs not in this list ^^ can be defined in the local filebeat.yml or metricbeat.yml configuration files after the user has enrolled the Beat.

Is that correct?

**Comment by martin-br** [comment]
@ph I fully agree, to support Redis output in CM should be the target 👍 Should I create a new issue dedicated ?

**Comment by ph** [comment]
@martin-br Yes and I will track it. :)
