### ISSUE TITLE
[packetbeat] Request to add support for mDNS

### ISSUE THREAD

**Issue by shed909** [elastic/beats#9428]
**Describe the enhancement:**
To add support for sniffing Multicast DNS packets on port 5353, UDP.

**Describe a specific use case for the enhancement or feature:**
Monitoring traffic to and from certain devices and detecting and visualising broadcast storms or other issues.

I have an issue with some devices not being discovered on my network. 
It would be great to be able to monitor the protocol as a whole and also look at each hosts traffic to determine what was occurring at the time certain issues occur.

**Comment by andrewkroh** [comment]
I think we want to have supported added to miekg/dns for parsing the mDNS records before we could add support to Packetbeat.

https://github.com/miekg/dns/issues/436#issuecomment-485230134
