### ISSUE TITLE
Instructions for enrolling beats don't update correctly

### ISSUE THREAD

**Issue by clintongormley** [elastic/beats#9451]
In 6.5.1, the command line for enrolling a beat doesn't update correctly:

* Click on Management in Kibana
* Click on Central Management
* Click on Enroll Beat
* Change Beat Type to "Metricbeat"
* CLI instructions refer to filebeat:

![image](https://user-images.githubusercontent.com/56599/49689150-5dbb9d00-fb1d-11e8-964a-ce23128ecb9e.png)

* Change Beat Type back to "Filebeat"
* Change OS to "MacOS"
* Change Beat Type to "Metricbeat"
* OS changes back to "DEB/RPM" and CLI instructions refer to filebeat:

![image](https://user-images.githubusercontent.com/56599/49689174-aecb9100-fb1d-11e8-8682-73aeae84eeae.png)

**Comment by monicasarbu** [comment]
Duplicated https://github.com/elastic/kibana/issues/25372
