### ISSUE TITLE
Load only selected dashboards

### ISSUE THREAD

**Issue by markwalkom** [elastic/beats#9455]
**Describe the enhancement:** When loading dashboards and ML jobs, it's be great if we could either;

1. Load selected dashboards via a command, or
1. Load the dashboards related to the modules that are enabled

**Describe a specific use case for the enhancement or feature:**
Not everyone needs *all* of the dashboards that are loaded, so we currently need to load all of them and then delete the ones we don't want. I'd rather just do one of the above two options.

**Comment by sophiec20** [comment]
+1

related https://github.com/elastic/beats/issues/11350 https://github.com/elastic/beats/issues/11349
