### ISSUE TITLE
Cannot enable monitoring centrally

### ISSUE THREAD

**Issue by clintongormley** [elastic/beats#9456]
When you enroll a beat in central management, it overwrites the local monitoring config, but there is no way to turn monitoring on again centrally.

**Comment by clintongormley** [comment]
Similarly, there is no where to specify Kibana config in central mgmt

**Comment by ph** [comment]
> Similarly, there is no where to specify Kibana config in central mgmt


It was possible but not documented, you can use the same options in `management.kibana` that you do in `setup.Kibana`. The #9752 Make it a bit more obvious, if you use the flag `-E` to configuration any TLS options they will be persisted to the management section.

Maybe worth to add some docs about it. @dedemorton

**Comment by ph** [comment]
I've created this https://github.com/elastic/beats/issues/9456 to take the "whole" setup phase of beats. I will close this specific one.

**Comment by Beren-G** [comment]
> I've created this #9456 to take the "whole" setup phase of beats. I will close this specific one.

@ph, did you mean to reference this ticket or is there another one for the whole setup phase of beats?

Is there a workaround for configuring beats monitoring centrally?

**Comment by n0othing** [comment]
@berengamble  I don't believe there are any workarounds at this time, but we have https://github.com/elastic/beats/issues/11576 which would address this issue's original ask.
