### ISSUE TITLE
Replace _xpack/monitoring/* with _monitoring/* ES API calls

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#9480]
Starting 7.0, the `_xpack/monitoring/*` API endpoints in Elasticsearch will be [deprecated](https://github.com/elastic/elasticsearch/pull/36130) in favor of `monitoring/*` API endpoints. We should update any references to the deprecated endpoints in the Beats codebase and replace them with the new ones.

**Comment by ycombinator** [comment]
Pinging @elastic/stack-monitoring

**Comment by jakelandis** [comment]
@urso @ycombinator - Can we try to get this is in for 7.0.0 ? While testing, I noticed that this can create quite a bit of noise in the logs for Elasticsearch.  The change should be easy and `/_xpack/monitoring/_bulk` --> `/_monitoring/bulk`.  Here is the PR for Logstash: https://github.com/elastic/logstash/pull/10528/files

**Comment by ycombinator** [comment]
@jakelandis Yes, I will work on this ASAP.

**Comment by ycombinator** [comment]
Just as an FYI: looks like this somehow got missed in https://github.com/elastic/beats/pull/9656.
