### ISSUE TITLE
Remove default HTTP and HTTPS ports from the ES URL

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#952]
When connecting to ES on HTTP port 80 we use a URL of `http://host:80/`. The port number is not needed. The same is true for HTTPS and port 443. The side effect is that the Host header contains the `:80` or `:443`. I have seen a few proxy and reverse proxy rules that make incorrect assumptions and do not expect these ports to be present for 80 and 443. It would be nice to [normalize](https://tools.ietf.org/html/rfc3986#section-6.2.3) the URL used to connect to ES.

https://discuss.elastic.co/t/winlogbeat-transport-problem-on-non-9200-port/40965/14

**Comment by poochwashere** [comment]
Hmmm, I am having this issue now, which results in this error message `Failed to perform any bulk index operations: 308 Permanent Redirect: <html>` I am not sure how to configure my `nginx` proxy to handle this.
