### ISSUE TITLE
Enable ILM by default in 7.0

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#9521]
The idea is to enable ILM as the default mechanism to ingest data in 7.0. To get there a few things need to be figured out:

* How will users migrate from 6.x that not have ILM or enabled?
* What is happens with users using the OSS version of Elasticsearch and don't have ILM available?
* What is the default in the setup command? See https://github.com/elastic/beats/issues/9470

**Comment by urso** [comment]
Closed by: https://github.com/elastic/beats/pull/10347
