### ISSUE TITLE
Test PR with latest code of the target branch

### ISSUE THREAD

**Issue by ph** [elastic/beats#9524]
Instead of only testing the PR code in isolation in the branch I would like to rebase the PR with the latest version of the target branch and then run the tests. When the PR tests are green and the PR is ready to merge it doesn't mean the branch will stay green after the merge.

**Comment by jsoriano** [comment]
I agree that it'd be great to have something like this, specially if the number of people contributing to beats grows.

This needs an automated integration pipeline that for every PR ready to be merged it tests the result of the merge. And ideally we'd also need to reduce flaky tests and merge conflicts so the automated process can actually work most of the time.

**Comment by ph** [comment]
> This needs an automated integration pipeline that for every PR ready to be merged it tests the result of the merge. And ideally we'd also need to reduce flaky tests and merge conflicts so the automated process can actually work most of the time.

We are on the road for that, we will get there.

**Comment by andresrc** [comment]
@elastic/observablt-robots Are we already using merge commits to run the builds? (at least in Jenkins)

**Comment by v1v** [comment]
Let me see how the JJB/JJBB is managed for the beats-ci instance.
IIRC, that's the approach we use in the `apm-ci` instance by default.

_NOTE_: JJBB is the term used for the customized Jenkins Job Builder.

**Comment by kuisathaverat** [comment]
the new pipeline makes a merge before to build, the old build jobs no

![Screenshot 2020-01-14 at 15.10.43.png](https://zube.io/files/elastic/ba755a6d4e83f89e9e082f75dcc3ce47-screenshot-2020-01-14-at-15-10-43.png)

**Comment by v1v** [comment]
Old build jobs are not using that particular merge feature, if it's required then we might need to include the equivalent JJBB for the below screenshot

![image.png](https://zube.io/files/elastic/23143c0c905ed62318ee162c14c0dd81-image.png)

[configuration view](https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/configure)

**Comment by kuisathaverat** [comment]
this is done, we can close it.
