### ISSUE TITLE
Kibana Filebeat module could miss important messages from .stderr 

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/beats#9530]
Currently the Kibana Filebeat module reads the `STDOUT` logfile, which is well structured.  Currently the `stderr` file is ignored, and also is [poorly formatted](https://github.com/elastic/kibana/issues/8269).   Either we should support `stderr` as to not miss important / critical events, or Kibana team should deprecate its use.

**Comment by ycombinator** [comment]
Ping @elastic/stack-monitoring

**Comment by smith** [comment]
This is not planned.
