### ISSUE TITLE
[CM] Generate a basic file to list the support modules and outputs

### ISSUE THREAD

**Issue by ph** [elastic/beats#9535]
Currently, the list of modules and outputs are currently hard coded in the CM UI, we should generate the list from the beats source code and use that list to create the documentation and keep the UI in sync.

Later we can add:
- Validation
- Make beats push the supported modules to the UI.

cc @mattapperson

**Comment by exekias** [comment]
@ph I guess this can be closed?

**Comment by ph** [comment]
yes :+1:
