### ISSUE TITLE
[Broken Link] Download Functionbeat Package

### ISSUE THREAD

**Issue by Alsheh** [elastic/beats#9580]
The [docs](https://www.elastic.co/guide/en/beats/functionbeat/current/functionbeat-installation.html#functionbeat-installation) has a broken link to `Functionbeat-6.5.3` package . Currently, available version download link is for the `Functionbeat-6.5.1` package.

**Comment by acchen97** [comment]
Hi @Alsheh, currently the code snippets are showing 6.5.3 and the download page link shows 6.5.3 as well. Can you double check and confirm?

**Comment by dedemorton** [comment]
The version in the download page is correct. The problem is that the path changed. See my comments here https://github.com/elastic/beats/pull/9636#issuecomment-448439111.

**Comment by PosicubeBeege** [comment]
This is still an issue
