### ISSUE TITLE
Allow a beats to subscribe to a tag when enrolling

### ISSUE THREAD

**Issue by ph** [elastic/beats#9596]
Currently when you enroll a beats it will not follow any tags, this makes the beats does nothing after the initial enroll. When dealing with large deployment of beats it would be nice to be able to enroll a beats and set a default tags where the beats should pick up his configuration.

**Comment by ph** [comment]
@mattapperson What do you think if we solve it in three front:

1. When we have web token, the enrolling tags could be specified there.
2. We could allow users to use --tags "one,two,three", that would be friendly to automation tool.
3. we could have a `management.enrolling_tags: "one,two,three"`

**Comment by vaivars** [comment]
I support this request, its a major thing needed for full automation of enrolling and configuring new systems with CBM

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
