### ISSUE TITLE
[Auditbeat] file.uid and file.gid are numbers instead of strings

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#9607]
We use keyword for `file.uid` and `file.gid` in the index template to allow for Windows SID values to be written to the same field. But the code writes numbers. This shouldn't be causing a problem because we have the index template in place, but the code should be changed to write strings.

https://github.com/elastic/beats/blob/ded3b7652939f13e7c26fd99356c454b45169090/auditbeat/module/file_integrity/event.go#L252-L253

For confirmed bugs, please report:
- Version: Auditbeat 6.2+
- Operating System: all
- Discuss Forum URL:
- Steps to Reproduce:

**Comment by webmat** [comment]
Good catch.

Pretty sure I've been guilty of coercing a bunch of Linux UIDs and GIDs to ints, during the recent round of Filebeat migrations. I will undo that mistake this week.
