### ISSUE TITLE
Provide an option to have WinlogBeat automatically reload config changes

### ISSUE THREAD

**Issue by aagupta1** [elastic/beats#9618]
**Describe the enhancement:**
Provide an option to have WinlogBeat automatically reload config changes

**Describe a specific use case for the enhancement or feature:**
I want to avoid having to restart WinlogBeats everytime I make config changes.  Config changes should be picked up automatically if I provide the option to do so.

**Comment by urso** [comment]
@jsoriano @andrewkroh This looks like a duplicate of #8281. Can we close this issue?

**Comment by jsoriano** [comment]
@urso you are right, it looks like a duplicate, closing this, thanks!
