### ISSUE TITLE
[CM] Change config block data structure

### ISSUE THREAD

**Issue by mattapperson** [elastic/beats#9637]
Currently each config has its own data structure often using dynamic object keys. This is very hard to type on its own let alone when no 2 config types are the same.

Thus we would like to move all blocks to the following shape:
```
{
  _sub_type: 'elasticsearch', // this key will define things like output type, or module type
  hosts: ['foo', 'bar'],
  username: 'foo',
  password: 'string',
}
```

**Comment by ph** [comment]
After looking at the management code with @mattapperson , I think we can do it in two steps, the fastest steps would be to just transpose the data from format X to format Y. 

This will allow him to have type safety on his side and will provide a path to have type satefy on our side as a step 2 once we do the schema.

**Comment by mattapperson** [comment]
ping @urso

**Comment by toddferg** [comment]
I don't know if this is related, but what about Beatcm SSL output configurations?

**Comment by ph** [comment]
@toddferg No it's not it related to the communicatin between beats <-> kibana

**Comment by ph** [comment]
implement in 6.7
