### ISSUE TITLE
kafka output zone awareness

### ISSUE THREAD

**Issue by danielmotaleite** [elastic/beats#9675]
**Describe the enhancement:**
Right now filebeat outputs to all kafka nodes and partitions, even if in a different zone.
With a new option, kafka output should look to it own zone and find kafkas in the same zone and use then, only fallback to the other zone kafkas if the first one is unavailable/inexistent.

**Describe a specific use case for the enhancement or feature:**
This will save costs, having one zone filebeat talking to their own kafka node will reduce cross-zone traffic. Kafka will then rebalance their partitions and replicas between zones. Later logstash could do the same zone awareness for consuming events.
Check this example:
https://amplitude.engineering/reducing-costs-with-az-awareness-efc92bc7113a

**Comment by danielmotaleite** [comment]
Of course, the same issue can be applied while talking to logstash or elasticsearch directly, so maybe this could be renamed beat output zone awareness?

**Comment by hamishforbes** [comment]
Has there been any progress on this? I'm interested in this as a feature too

FWIW segmentio/kafka-go [supports](https://github.com/segmentio/kafka-go/blob/master/example_groupbalancer_test.go#L17) rack-aware balancing, it may be easier to switch out sarama than re-implement the functionality

**Comment by hamishforbes** [comment]
This would still be a useful feature, not stale!

**Comment by kimxogus** [comment]
https://github.com/elastic/beats/issues/41594
