### ISSUE TITLE
Investigate Layers for deploying and distributing Functionbeat

### ISSUE THREAD

**Issue by ph** [elastic/beats#9692]
Wu should look closer on the AWS lambda layers as a mean to distribute and manage Functionbeat for the AWS platform.

https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html

> You can create layers, or use layers published by AWS and other AWS customers. Layers support resource-based policies for granting permission specific AWS accounts, AWS Organizations, or all accounts.

**Comment by ph** [comment]
As part of the release manager we could export that layer and make it available to anyone, that would make deploying much simple and remove the need to push the binary to a bucket.

**Comment by jlind23** [comment]
We endeavor to address Functionbeat use cases via the new Serverless Forwarder project (https://github.com/elastic/elastic-serverless-forwarder)with a better integration with serverless functionality provided by major cloud providers. Enhancements to the current Functionbeat will therefore be limited.
