### ISSUE TITLE
Show version 6.5.5 of libbeat in 6.5.4 tags

### ISSUE THREAD

**Issue by Moebius2722** [elastic/beats#9733]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 6.5.4
- Operating System: Debian
- Discuss Forum URL:
- Steps to Reproduce: metribeat version => 6.5.5 of 6.5.4 binary

After build metribeat 6.5.4 tags branch, the command "metribeat version" display "metricbeat version 6.5.5 (arm), libbeat 6.5.5 [unknown built unknown]"

The index generate in elasticsearch by logstash is named "metricbeat-6.5.5-2018.12.21"

The error is in "beats/libbeat/version/version.go" file.
![image](https://user-images.githubusercontent.com/19503838/50317526-594b9880-04bc-11e9-857f-01278b87b41f.png)

**Comment by kvch** [comment]
This issue is for an old version of beats, I suggest to try out the latest version of beats. If this is still a problem in the newly released version feel free to reopen this issue. Thanks.
