### ISSUE TITLE
Filebeat system module pipelines setup doesn't honor module settings

### ISSUE THREAD

**Issue by bczifra** [elastic/beats#9747]
**Version**: Filebeat,Elasticsearch 6.5.3
**Steps to Reproduce:**

When pipelines are created just by running filebeat process, the expected pipelines are created, considering the module configuration.

When pipelines are created via command:
```
./filebeat setup --pipelines --modules system
```

The pipelines are created but specific settings from `modules.d/system.yml` file are ignored, for example: `var.convert_timezone: true` in syslog and auth submodules.

Pipeline `filebeat-6.5.3-system-syslog-pipeline` created just running filebeat includes:
```
        "date": {
          "timezone": "{{ beat.timezone }}",
          "ignore_failure": true,
          "field": "system.syslog.timestamp",
          "target_field": "@timestamp",
          "formats": [
            "MMM  d HH:mm:ss",
            "MMM dd HH:mm:ss"
          ]
        }
# that is correct, it includes timezone field.
```

And running `./filebeat setup --pipelines --modules system`

```
     {
        "date": {
          "formats": [
            "MMM  d HH:mm:ss",
            "MMM dd HH:mm:ss"
          ],
          "ignore_failure": true,
          "field": "system.syslog.timestamp",
          "target_field": "@timestamp"
        }
      }
# that is missing timezone field, that should be added by the setting var.convert_timezone.
```

**Comment by exekias** [comment]
@urso I think you folks are looking into `setup` command, can you add this to the check list?

**Comment by jsoriano** [comment]
I could reproduce this too in 6.7 and 7.0, as a workaround to fix the pipelines I had installed I run filebeat  with `-E filebeat.overwrite_pipelines=true`.
