### ISSUE TITLE
Beats won't compile.

### ISSUE THREAD

**Issue by rvlander** [elastic/beats#975]
Disclaimer: I am  a total noob in Go.

When running from Getting Ready section in Developpers's guide:
```sh
go get github.com/elastic/beats
```

I have the following error:
```sh
package github.com/elastic/beats: no buildable Go source files in <GOPATH>/src/github.com/elastic/beats
```

**Comment by ruflin** [comment]
@rvlander Can you please open a discuss topic with this here? https://discuss.elastic.co/c/beats We try to have only technical project issues in Github and keep all questions on discuss. Thank you.
