### ISSUE TITLE
Incorrect timezone reported with logstash and elasticsearch Filebeat modules

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#9756]
Timestamps in neither Elasticsearch nor Logstash logs contain timezone information. Currently the `elasticsearch` and `logstash` Filebeat modules simply index these timestamps as-is (without any timezone information), causing Kibana to interpret them as being in UTC.

Like the `system` Filebeat module, the `elasticsearch` and `logstash` Filebeat modules should support the `var.convert_timezone` configuration setting.

**Comment by ruflin** [comment]
@ycombinator I think we should investigate why LS and ES don't log the timezone in the first place too.

**Comment by ycombinator** [comment]
@ruflin said:

> I think we should investigate why LS and ES don't log the timezone in the first place too.

Elasticsearch is getting structured logging in the future. This would be a good opportunity to include the time zone in their log timestamps. I started a conversation about this on the structured logging PR here: https://github.com/elastic/elasticsearch/pull/36833/files#r244225243

For Logstash, I created this issue: https://github.com/elastic/logstash/issues/10238

**Comment by ycombinator** [comment]
Resolved via https://github.com/elastic/beats/pull/9797 and https://github.com/elastic/beats/pull/9761
