### ISSUE TITLE
Respond to ingest-geoip now being packaged as a module

### ISSUE THREAD

**Issue by jasontedor** [elastic/beats#9771]
Starting with Elasticsearch 6.7.0, `ingest-geoip` will be installed as a module. This issue is a meta-issue for the work needed on the Beats side to respond to this change:
 - when communicating with an Elasticsearch >= 6.7.0 node, no detection is needed in Beats modules that `ingest-geoip` is installed elastic/elasticsearch#36898

 - docs on how to install the `ingest-geoip` plugin need to be removed; for now we have added a placeholder page to avoid breaking the Beats docs build: elastic/elasticsearch#36958   but would like to remove this page as soon as Beats is ready

**Comment by ruflin** [comment]
Great news that geoip is now shipped by default. I think on our side it's simplest to keep the check in place so we don't have to introduce additional version checks on our end. In general it is recommended that ES version >= Beats but there are also users where Beats > ES which means the check is still needed to at least give a good error message. 

@dedemorton Could you take on the cleanup of the docs so the pages are not needed anymore on the ES side?

**Comment by ruflin** [comment]
@jasontedor Got it. I falsely assumed ES would still report them the same way. We definitively need an adjustment for this then.
