### ISSUE TITLE
Respond to ingest-user-agent being packaged as a module

### ISSUE THREAD

**Issue by jasontedor** [elastic/beats#9773]
Starting with Elasticsearch 6.7.0, `ingest-user-agent` will be installed as a module. This issue is a meta-issue for the work needed on the Beats side to respond to this change:
 - when communicating with an Elasticsearch >= 6.7.0 node, no detection is needed in Beats modules that `ingest-user-agent` is installed elastic/elasticsearch#36956

 - docs on how to install the `ingest-user-agent` plugin need to be removed; for now we have added a placeholder page to avoid breaking the Beats docs build: elastic/elasticsearch#36956  but would like to remove this page as soon as Beats is ready

**Comment by ph** [comment]
I think our side we just need to update the modules and remove the "plugin: ingest-user-agent", we will also need to update the docs to remove any mention of it.

cc @ruflin

**Comment by ruflin** [comment]
As commented in https://github.com/elastic/beats/issues/9771 I think we should keep the check and the requirement in for older version.
