### ISSUE TITLE
init.sh.tmpl is not enforcing filebeat to run on the background using start-stop-daemon --background

### ISSUE THREAD

**Issue by lchayoun** [elastic/beats#9774]
- Version: 6.2.4
- Operating System: Ubuntu 14.04.5 LTS
- Steps to Reproduce: 

when running filebeat as a service using upstart, filebeat SID is not the PGID causing the process to be killed as part of stopping the process that started it.

this can be prevented by running it with the `--background` flag to `start-stop-daemon --start` command.
similarly to how docker daemon service is configured:
[sysvinit-debian/docker](https://github.com/docker/docker-ce/blob/8a582e89b407639018e067123eb17f61dbfd10ee/components/engine/contrib/init/sysvinit-debian/docker#L107)

**Comment by urso** [comment]
Using `start-stop-daemon` with `--background` does an implicit fork. It's required for applications not daemonizing correctly.

From man page:
> Typically used with programs that don't detach on their own.
> This option will force start-stop-daemon to fork before
> starting the process, and force it into the background.

So to not have to rely on `--background` beats uses [go-daemon](https://github.com/fiorix/go-daemon), which should do the right thing (I hope).

The difference to docker is not only the `--background` flag, but also the actual binary (wrapper) used to start the binary.

**Comment by michalpristas** [comment]
closing
