### ISSUE TITLE
Whether the filebeat enabled mysql module supports direct pass to kafka

### ISSUE THREAD

**Issue by ytc301** [elastic/beats#9816]
I want to use the filebeat mysql module to directly pass the stream to the kafka cluster through the own pipeline, but found that the delivery is unsuccessful, the kafka cluster consumer does not generate logs, I try to pass directly to es is normal. So I want to confirm whether the mysql module is passed directly to kafka or not.

**Comment by ytc301** [comment]
filebeat 打印的日志

<img width="457" alt="tt" src="https://user-images.githubusercontent.com/9103314/50499700-aca68380-0a86-11e9-97c9-40c4d1af8b77.png">

**Comment by ytc301** [comment]
version:filebeat-6.5.4
os:centos6.9

**Comment by ruflin** [comment]
For questions please use discuss as we try to keep Github for confirmed bugs or feature requests: https://discuss.elastic.co/c/beats/filebeat Closing this.
