### ISSUE TITLE
Add GO15VENDOREXPERIMENT to developer guide

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#983]
See https://discuss.elastic.co/t/following-developpers-guide-beats-wont-compile/41592

**Comment by kkirsche** [comment]
Is it worth noting that this is not considered experimental anymore in Golang 1.6?

**Comment by ruflin** [comment]
Good point. This issue gets obsolete as soon as we switched to Golang 1.6 as it is enabled by default. Perhaps still a note should be added that we use the vendor directories.

**Comment by ruflin** [comment]
Closing this one as we moved to Golang 1.6
