### ISSUE TITLE
[filebeat] Add convert_timezone to nginx module

### ISSUE THREAD

**Issue by pc-jedi** [elastic/beats#9839]
Currently the nginx module does not have a `convert_timezone` configuration option.
Since Kibana assumes a timestamp field to be stored as UTC in ES, you will see your logs having a wrong timestamp.
This would not be a big issue.
But if you have configured your server timezone to UTC+1 and insert a nginx log with `[02/Jan/2019:10:00:00 +0100]`, which is 9AM UTC, the `@timestamp` will be 10AM UTC.
If you now want to see your log in Kibana this will not be possible, because queries in Kibana are limited by the current timestamp. Therefore you have to wait util it is 10AM UTC to be able to see your log in Kibana.

The easiest workaround for that would be setting your server timezone to UTC, which I don't like.

It would be nice to have something like the [system module convert_timezone](https://www.elastic.co/guide/en/beats/filebeat/6.5/filebeat-module-system.html#_literal_syslog_literal_fileset_settings).

Since there are also some more module, which don't have this option it would be the best to add this to all modules.

**Comment by kaiyan-sheng** [comment]
This seems to be a subtask for https://github.com/elastic/beats/issues/9993

**Comment by pc-jedi** [comment]
@kaiyan-sheng I think you made a small mistake.
https://github.com/elastic/beats/blob/master/filebeat/module/nginx/access/ingest/default.json#L77
I think the field must be `beat.timezone` and not ``event.timezone` according to the [docu](https://www.elastic.co/guide/en/beats/filebeat/6.6/add-locale.html)

Same here:
https://github.com/elastic/beats/blob/master/filebeat/module/nginx/error/ingest/pipeline.json#L21
