### ISSUE TITLE
start beats as a background process

### ISSUE THREAD

**Issue by gnhuy91** [elastic/beats#984]
I know we can do something like `filebeat -c filebeat.yml &`, but I'd love to have an official run option.

**Comment by kkirsche** [comment]
Please be aware that there are known runtime concerns with daemonizing within Golang golang/go#227 there are also additional concerns for daemonizing if a goroutine has occurred prior to the event.

**Comment by Vinu2903** [comment]
you can install it as a service: 

https://www.elastic.co/guide/en/beats/libbeat/current/setup-repositories.html

then you can use #service filebeat start

**Comment by LakshithaH** [comment]
Installing filebeat as a service is a problem when you don't have sudo privileges. Better if we can have a demon start and stop like this
```
filebeat -c filebeat.yml start
filebeat -c filebeat.yml stop
```

**Comment by romber2001** [comment]
i also wonder why there is no option like --daemon or -d, to start it as background process...

**Comment by tarun7631** [comment]
use screen -d -m ./filebeat -e -c filebeat.yml -d "publish" to run filebeat as a background process

**Comment by kkirsche** [comment]
Or the simpler ‘nohup longrunningcmd &’

Either way, neither screen or nohup are replacements for service management systems like systemd, etc.

**Comment by romain-chanu** [comment]
If you run `nohup filebeat &` in a SSH session and the SSH session is closed, the filebeat process will be stopped. There is a [signal handler](https://github.com/elastic/beats/blob/e9537aa779f1988a1f33ef6028a908615eb19e34/libbeat/service/service.go#L54) implemented in the beats code. I believe this overwrites the signal handler set by `nohup` in the first place. Running filebeat as a service (`sudo service filebeat start`) would be an alternative.

**Comment by MuChenMuXuan** [comment]
@romain-chanu  yes，you all right.

https://discuss.elastic.co/t/filebeat-stopped-automatically/267950/3
