### ISSUE TITLE
CI broken becasue filebeat haproxy, redis and system test failed with wrong timestamp 

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#9849]
Redis filebeat module: `98738:M 30 May 12:23:52.442 * Saving the final RDB snapshot before exiting.` is the log entry in `filebeat/module/redis/log/test/test.log` but it doesn’t have a `year` on the timestamp. So in `test.log-expected.json`, the timestamp used to be 2018  but now it changed to 2019. That's why CI is failing with error like: https://travis-ci.org/elastic/beats/jobs/474342333#L2082

Same problem in haproxy filebeat module: `Sep 20 15:42:59 1.2.3.4 haproxy[24551]: Connect from 1.2.3.4:40780 to 1.2.3.4:5000 (main/HTTP)` is from `filebeat/module/haproxy/log/test/default.log`. CI failure example: https://travis-ci.org/elastic/beats/jobs/474342333#L1373

These errors are also exist in master branch, for example: https://travis-ci.org/elastic/beats/jobs/474520532#L1344

**Comment by andrewkroh** [comment]
@jsoriano's comment is relevant here: https://github.com/elastic/beats/pull/9840#issuecomment-450925010

> To avoid this happening on next year, should we add exceptions for these timestamps as the ones we have for icinga? Or replace the years before checking?
