### ISSUE TITLE
TCP Input?

### ISSUE THREAD

**Issue by mgcrea** [elastic/beats#985]
I'm looking for a replacement to fluentd as a system logging collector. Beats looked like a good fit, but I can't find a way to send/forward a JSON object via TCP, is it possible? If not do you plan to add it? Currently I'm using this [NodeJS library](https://github.com/fluent/fluent-logger-node) to forward custom metrics to elasticsearch via fluentd.

**Comment by ruflin** [comment]
We haven an open issue for a TCP input here: https://github.com/elastic/beats/issues/536
A discussion on JSON can be found here: https://github.com/elastic/filebeat/issues/311

Would the combination of the two solve your issue?

**Comment by ruflin** [comment]
I suggest we continue the discussion in https://github.com/elastic/beats/issues/536 and close this one as a duplicate.
