### ISSUE TITLE
functionbeat: better support for environment variables (kms/ssm)

### ISSUE THREAD

**Issue by lifeofguenter** [elastic/beats#9864]
**Describe the enhancement:**

Currently it is not possible to make usage of environment variables inside the configuration file (`functionbeat.yml`).

It would be great if functionbeat could support that, and even go further to support ssm+kms environment variables (see: https://github.com/remind101/ssm-env) as lambda currently only offers encryption at rest, but the env-vars would still be plaintext in the console or zip: https://github.com/hashicorp/terraform/issues/12225

**Describe a specific use case for the enhancement or feature:**

* the config can contain sensitive credentials (for example passwords for certain outputs)
* we do not want that config to be visible in the `package.zip` or via the lambda-console

**Comment by Jamalarm** [comment]
This would be extremely useful for us as well, the current process of having to package a .yml config file containing everything is quite annoying and against the standard method of deploying lambdas.

**Comment by Jamalarm** [comment]
There appears to be some support for this now: https://www.elastic.co/guide/en/beats/functionbeat/current/using-environ-vars.html, but there seems to be no support for secure environment variables (KMS/SSM)

**Comment by clarkritchie** [comment]
👍 for SSM support.

**Comment by bminahan-kc** [comment]
👍 for environment variable support.

**Comment by adrian-skybaker** [comment]
Even with environment variable support it doesn't seem possible to avoid ending up with a plaintext `cloud.auth` value in the generated template.yml that's inside the zip created by `functionbeat package`.

Tooling should not be writing secrets out in plaintext. It looks like the safest approach is to avoid the config/package commands altogether and manually assemble a zip and config file.

**Comment by benberg86** [comment]
👍 for SSM or secrets manager support ($$ here). Ability to provide ARN of a secret manager secret/SSM parameter to use in an env var is how we have implemented - lambda goes and grabs the secret/SSM at run time.

**Comment by nimarezainia** [comment]
We won't be making enhancements to Functionbeat as there are efforts to replace this functionality in a more modern serevrless models. We will be concentrating on addressing high priority support issues.
