### ISSUE TITLE
Empty _index value and no error from Beats on invalid output.elasticsearch.index

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#9871]
I cannot index documents when using Filebeat 7.0.0 configured with the default `output.elasticsearch.index` value.

For confirmed bugs, please report:
- Version:
  - filebeat version 7.0.0 (amd64), libbeat 7.0.0 [700e982220cfef7e59c5b17d98ba698e8b228722 built 2019-01-03 04:30:45 +0000 UTC]
  - elasticsearch 6.5.2 with x-pack security enabled
- Operating System: Tested with linux and darwin.
- Discuss Forum URL:
- Steps to Reproduce: 
  - Configure `output.elasticsearch.index` to its [documented](https://www.elastic.co/guide/en/beats/filebeat/master/elasticsearch-output.html#elasticsearch-output) defaults.

```
output.elasticsearch:
  hosts: ["http://localhost:9200"]
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"
```

  - Capture a pcap of the traffic on 9200.
  - Look at the _bulk request.

```
{
  "index": {
    "_index": "",
    "_type": "_doc"
  }
}
{
  "@timestamp": "2019-01-03T15:40:00.785Z",
  "agent": {
    "ephemeral_id": "baad81cd-4a17-42ee-8bef-3004392445f9",
    "hostname": "host.com",
    "id": "921434fb-fde2-4e17-ae2a-710bd55983b9",
    "type": "filebeat",
    "version": "7.0.0"
  },
```

  - In Filebeat's log I see a HTTP 403 since the _index is not set.

`2019-01-03T10:53:53.877-0500	WARN	elasticsearch/client.go:531	Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Time{wall:0xbf03a9e43347f5d0, ext:10050047056, loc:(*time.Location)(0x58bbdc0)}, Meta:common.MapStr(nil), Fields:common.MapStr{"ecs":common.MapStr{"version":"1.0.0-beta2"}, "agent":common.MapStr{"type":"filebeat", "hostname":"xx", "version":"7.0.0", "id":"xx", "ephemeral_id":"0571775a-51e6-4629-8e6c-5996fa17c731"}, "host":common.MapStr{"os":common.MapStr{"platform":"darwin", "version":"10.14.2", "family":"darwin", "name":"Mac OS X", "kernel":"18.2.0", "build":"18C54"}, "name":"xx", "architecture":"x86_64"}, "log":common.MapStr{"offset":1831760, "file":common.MapStr{"path":"/var/log/corecaptured.log"}}, "message":"Jan 03 06:33:36 CCPipeMonitor::ccfree Exit - Destroyed lock", "input":common.MapStr{"type":"log"}}, Private:file.State{Id:"", Finished:false, Fileinfo:(*os.fileStat)(0xc000472680), Source:"/var/log/corecaptured.log", Offset:1831820, Timestamp:time.Time{wall:0xbf03a9e271ff9368, ext:3028718807, loc:(*time.Location)(0x58bbdc0)}, TTL:-1, Type:"log", Meta:map[string]string(nil), FileStateOS:file.StateOS{Inode:0x1063a1, Device:0x1000004}}}, Flags:0x1} (status=403): {"type":"security_exception","reason":"action [indices:admin/create] is unauthorized for user [filebeat_internal]"}`

**Comment by andrewkroh** [comment]
The problem is caused by the change of `beat.version` to `agent.version`. The documentation needs to be updated to fix any `index` and `indices` examples that reference it. And we need to make sure that it's in the breaking changes docs (if not already there). It caught me because I use custom index patterns to do weekly indexes.

The other problem is that this does not result in any error. `getIndex` in client.go is returning an empty string and no error. We have a test case for missing keys in the fmtstr, but it's passing so more investigation is needed.

https://github.com/elastic/beats/blob/5b3066f69f5a6f07734c5c5b2b74d71db9d4b9ae/libbeat/common/fmtstr/formatevents_test.go#L182-L185

**Comment by urso** [comment]
QQ @ruflin : Will Beats 6.6/6.7 use `agent.version` or `beat.version` ?

**Comment by ruflin** [comment]
Beats 6.6 / 6.7 uses beat.version and agent.version is only an alias.

@andrewkroh So in your case you had commented out the `index` config and upgraded?

**Comment by andrewkroh** [comment]
@ruflin I was using the config shown in the description (`output.elasticsearch.index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"`). I had this in my config file because I was upgrading from 6.x. After updating the config with `s/beat.version/agent.version/` it works fine, but the lack of any error on the Beat side when using `[beat.version]` is the problem.

**Comment by jlind23** [comment]
Backlog grooming: closing for now.

**Comment by marcbuhler** [comment]
In case this helps anyone you get the same error if you PUT to ElasticSearch but have a double `/` in your URL.
