### ISSUE TITLE
packetbeat nonsupport thrift port server reuse ?

### ISSUE THREAD

**Issue by zhangbo1** [elastic/beats#988]
thrift Port service reuse! responsetime:0 ,thrift.return.value is null,

**Comment by zhangbo1** [comment]
@andrewkroh    thrift TMultiplexedProcessor running server, get responsetime:0 ,thrift.return.value is null,

**Comment by zhangbo1** [comment]
@tsg  2016/02/19 09:18:16.178253 thrift.go:1014: DBG  Response from another request received 'userService:sendResetTradePasswordSMS' 'sendResetTradePasswordSMS'. Ignoring.

**Comment by andrewkroh** [comment]
Was there a question in there?
