### ISSUE TITLE
Index template generated by Beats 6.x does not work on ES 7.x

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#9882]
### Filebeat 6.0.0

The template generated for Elasticsearch 7.0.0 uses `doc`, but should use `_doc`. This causes an exception when sending to ES 7.

`"error"=>{"type"=>"mapper_parsing_exception", "reason"=>"Root mapping definition has unsupported parameters:  [doc : {_meta={version=6.6.0}`

I'd expect to see some more differences than number_of_routing_shards when running:

```
$ diff <(sudo filebeat export template --es.version 7.0.0-alpha2) <(sudo filebeat export template --es.version 6.0.0)
4550d4549
<       "number_of_routing_shards": 30,
```

The template itself contains

```
  "mappings": {
    "doc": {
```

`$ filebeat version
filebeat version 6.6.0 (arm), libbeat 6.6.0 [e264b84377e1ad3bd8c9a62d75078c1b447a083a built 2019-01-03 16:27:02 +0000 UTC]`

### Filebeat 7.0.0

The template generated by Filebeat 7.0.0 always uses `_doc`. But does not use `doc` for 6.0.

```
$ diff <(./filebeat export template --es.version=7.0.0) <(./filebeat export template --es.version=6.0.0)
3220d3219
<       "number_of_routing_shards": 30,
```

The template itself contains

```
  "mappings": {
    "_doc": {
```

$ ./filebeat version
filebeat version 7.0.0 (amd64), libbeat 7.0.0 [5b3066f69f5a6f07734c5c5b2b74d71db9d4b9ae built 2019-01-04 00:09:53 +0000 UTC]

**Comment by kaiyan-sheng** [comment]
Same problem happened to me yesterday when I was testing a new metricbeat module with 6.5.0 ES. `"Rejecting mapping update to [metricbeat-7.0.0-2019.01.03] as the final mapping would have more than 1 type: [_doc, doc]"}`

**Comment by cachedout** [comment]
+1. I just hit this. It appears at present, it is not possible to attach the HEAD version of Metricbeat to an ES 6.5.4.

To replicate this issue, I simply followed the instructions for connecting Metricbeat to ES which are found here: https://www.elastic.co/guide/en/elasticsearch/reference/6.5/configuring-metricbeat.html but used a version of Metricbeat built myself from source with the following commit hash: 079807ec3301be831cfef4edcf5042171019eecf
