### ISSUE TITLE
Ability to pull/push configs from Source Control to Central management

### ISSUE THREAD

**Issue by mark54g** [elastic/beats#9897]
**Describe the enhancement:**
Looking to create a method by which centrally managed beats can be pulled from Source Control systems as a "Source of truth" (but not automatically, as that opens up other issues).

**Describe a specific use case for the enhancement or feature:**
Allows users already controlling their environments from source control to maintain that point of truth to create and update configs for their beats in a centrally managed way

Similar to:
https://github.com/elastic/logstash/issues/10252

**Comment by wolframhaussig** [comment]
This sounds interesting, but why not automatically? If it would be possible to point Elastic to the a branch in GIT anyone could edit the file in the development branch and after you accept the change and merge it into the test branch your Test ystem could automatically get the config and install it. After the tests succeeded your merge the change into the  master branch and the production system of Elastic could automatically get the config and install it.
Another possiblity would be to only get a tagged version automatically - in this case Elastic could even show the version info(tag name) of the loaded config

**Comment by wolframhaussig** [comment]
:thumbsup: Leaving the user the option is always the best option as this largely depends on the development process and which way supports the requirements best.

**Comment by mtojek** [comment]
Stale, resolving.
