### ISSUE TITLE
Add beat as a '/bin/mail' command replacement

### ISSUE THREAD

**Issue by ludovicc** [elastic/beats#991]
Hello,

On my Ubuntu server, I install packages such as unattended-upgrades and failtoban, in an attempt to secure my servers. Those packages rely on the mailer daemon from mailutils to send emails to the administrator to inform him about various events - upgrades, security issues and more.

Instead of configuring a mailer, beats could be used to send and centralize those messages to Elasticsearch.

**Comment by ruflin** [comment]
Would it be possible to do this with filebeat? I assume all of the above tools could also write some log messages?

**Comment by ludovicc** [comment]
Hello Nicolas, it looks like you are right, unattended-upgrades does logs
as well as fail2ban. So filebeat looks perfect in that situation. Thanks!

2016-02-18 19:33 GMT+01:00 Nicolas Ruflin <notifications@github.com>:

**Comment by ruflin** [comment]
@ludovicc Good to hear. Closing this issue. Feel free to reopen it if needed.
