### ISSUE TITLE
Stream AWS load balancer logs (ELB/ALB/NLB) via S3

### ISSUE THREAD

**Issue by s12v** [elastic/beats#9910]
**Describe the enhancement:**

I think it's useful to ship AWS load balancer access logs to Elasticsearch.

Currently we use some custom lambdas subscribed to s3 logs buckets. Perhaps, it would be a nice addition to `functionbeat`, what do you think?

**Comment by justinwalz** [comment]
This was recently created https://github.com/elastic/beats/issues/12893

**Comment by kaiyan-sheng** [comment]
@s12v Thanks for creating this enhancement request. Currently we are working on adding s3 input to filebeat(#12582). With that, we will be able to create a module for ELB access logs (#12893).

**Comment by exekias** [comment]
thank you for your request! I'm closing this one in favor of #12893, feel free to comment there!
