### ISSUE TITLE
Ability to proxy Beats monitoring and centralized management connections through Logstash

### ISSUE THREAD

**Issue by admlko** [elastic/beats#9916]
**Describe the enhancement:**
We have deployed multiple Logstash and Kibana instances to separate geolocations and there are multiple Beats instances connected to each Logstash instance in their own geolocation. In a way, it is a distributed setup to different sites, so each site has their own set of Beats and one Logstash and Kibana instance. All the Logstash and Kibana instances are connected to a central Elasticsearch cluster.
None of the Beats are allowed to talk directly to the Elasticsearch cluster, only Logstash and Kibana instances are connected to the Elasticsearch cluster directly. Kibana instances are configured to use their own .kibana-<site> index, so that they don't get mixed up (multi-tenancy).
The Elasticsearch cluster and one master Kibana instance resides in a master site.

**Describe a specific use case for the enhancement or feature:**
It would be really handy if there would be a way to enable Beats monitoring and centralized configuration through Logstash, so there wouldn't be a need to enable port forward on each of the Logstash machines, but a new input and output could be added to Logstash configurations in order to enable Beats monitoring and management through Logstash.
I am not familiar with Beats centralized management internal design, but in this setup it is not desired that site local Kibanas could configure Beats - only master site Kibana should be able to configure Beats. Site local Kibanas could provide an access to Elasticsearch cluster though.

**Comment by kaem2111** [comment]
+1 
I also need beat central management over cascaded logstash instances and I don't want to expose a kibana nor elasticsearch endpoint in my DMZ's to use CM

**Comment by cskowronnek** [comment]
+1 for a beats monitoring output for logstash

**Comment by mtojek** [comment]
Stale, resolving
