### ISSUE TITLE
make beats-dashboards fails

### ISSUE THREAD

**Issue by kvch** [elastic/beats#9928]
Steps to reproduce:
1. Go to the root of the repo
2. Run `make beats-dashboards`

The error message is the following:
```
15:04:25 Error: no dashboards found for x-pack/metricbeat
15:04:25 make[1]: *** [beats-dashboards] Error 1
15:04:25 Makefile:188: recipe for target 'beats-dashboards' failed
```

The problem is `x-pack/metricbeat/_meta/kibana.generated` is missing.

**Comment by andrewkroh** [comment]
`x-pack/metricbeat` doesn't have any dashboards or logic to generate dashboards. It needs to be replace by plain old `metricbeat` at

https://github.com/elastic/beats/blob/323ed08e1a36d35a9026acfca808990b437408db/magefile.go#L40

for 6.x and 6.6. And make sure to test `make beats-dashboards`.

**Comment by andrewkroh** [comment]
Relates to:

- #9917
- #9918

**Comment by andrewkroh** [comment]
Fixes:

- 6.x: https://github.com/elastic/beats/pull/9930
- 6.6: https://github.com/elastic/beats/pull/9929
