### ISSUE TITLE
[Filebeat] Add Zeek (formerly Bro) Module

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#9931]
Add a new Filebeat module for ingesting logs from the [Zeek Network Security Monitor](https://www.zeek.org/) (formerly Bro).

## Filebeat module checklist

* [x] Supported Zeek versions are documented
* [x] Supported operating systems are documented (if applicable)
* [x] Integration tests exist
* [x] Automated checks that all fields are documented
* [x] Documentation for module and required Bro configuration
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] Dashboards exists
* [x] Kibana Home Tutorial
* [x] Test log files exist for the grok patterns
* [x] Generated output for at least 1 log file exists

**Comment by andrewkroh** [comment]
@alakahakai For the last remaining bullet there is a guide at https://www.elastic.co/guide/en/kibana/current/add-data-guide.html. This adds content to the Kibana home screen's "Add Data" section. You'll see that there is a page for Suricata there too.

**Comment by alakahakai** [comment]
Added Kibana home tutorial for zeek module - Kibana pull #31774
