### ISSUE TITLE
Export Index Template with Dynamic Fields

### ISSUE THREAD

**Issue by abaskin** [elastic/beats#9983]
I am working on a beat where the field names and types it returns are not known until run time. There is the option to use a custom index template so the user could build such an index template and add it to the beat config. However all the information to create an index template is available at runtime based on the config file for the beat. Is it possible to modify the "export template" command to dynamically build the field list based on information dynamically provided by the beat at runtime as opposed to pulling it from the static fields.yaml file? Since each implementation would potentially generate the template data differently, I would envision some sort of hook to supply the template information in a standard format.

**Comment by ruflin** [comment]
Can you elaborate a bit more on from where your Beat gets all the info during runtime for all the fields? In your case it means each instance of the Beat could have different fields? This could become a problem as if you have multiple instance of the same Beat with a different template all sending to the same index, which template do you use?

There is a bit a hidden config to add your own fields here: https://github.com/elastic/beats/blob/master/libbeat/_meta/config.reference.yml#L868

**Comment by abaskin** [comment]
Yes, each instance of the Beat can return a unique set of fields, as the Beat makes SNMP queries and returns the results. The OID’s to be queried are specified in the config file and are thus known at runtime as well as the data types of the returned items (either from MIB information or the SNMP response).  If there are multiple instances of the Beat each returning a unique set of fields then each instance of the Beat should be configured to use the correct index which includes the fields it returns. Alternatively one could use one index that is a superset of all the fields returned and use filtered aliases to separate out the data later. In either case the template returned by the Beat should match the fields that the given instance of the Beat produces based on the config file.

**Comment by ruflin** [comment]
> the Beat should match the fields that the given instance of the Beat produces based on the config file

If there is always a config file, append_fields should work for you?

**Comment by abaskin** [comment]
Yes, append_fields turns out to be a workable solution.  What I am able to do is to manipulate template.DefaultConfig.AppendFields on startup to add the required fields. In addition I can change the template.DefaultConfig.Pattern value to reflect the index defined in output.elasticsearch. Lastly by  removing and adding back the "export template" command I am able to add information to the help for the command explaining how the template is generated.

**Comment by andresrc** [comment]
Closing for now. Please reopen or open a discuss topic if a follow up is needed. Thanks!
